Kodi Documentation: CVideoInfoTag Class Reference
CVideoInfoTag Class Reference
#include <VideoInfoTag.h>
Classes
class CAssetInfo
struct SetInfo
< Struct holding information about a movie set
Public Types
typedef std::vector< SActorInfo >::const_iterator iCast
Public Member Functions
CVideoInfoTag ()
virtual ~CVideoInfoTag ()=default
void Reset ()
bool Load (const TiXmlElement *element, bool append=false, bool prioritise=false)
bool Save (TiXmlNode *node, const std::string &tag, bool savePathInfo=true, const TiXmlElement *additionalNode=NULL)
void Merge (CVideoInfoTag &other)
void Archive (CArchive &ar) override
void Serialize (CVariant &value) const override
void ToSortable (SortItem &sortable, Field field) const override
const CRating GetRating (std::string type="") const
const std::string & GetDefaultRating () const
const std::string GetUniqueID (std::string type="") const
const std::map< std::string, std::string > & GetUniqueIDs () const
const std::string & GetDefaultUniqueID () const
bool HasUniqueID () const
virtual bool HasYear () const
virtual int GetYear () const
bool HasPremiered () const
const CDateTime & GetPremiered () const
const CDateTime & GetFirstAired () const
const std::string GetCast (bool bIncludeRole=false) const
bool HasStreamDetails () const
bool IsEmpty () const
const std::string & GetPath () const
void SetDuration (int duration)
set the duration in seconds
unsigned int GetDuration () const
retrieve the duration in seconds. Prefers the duration from stream details if available.
unsigned int GetStaticDuration () const
retrieve the duration in seconds. Ignores the duration from stream details even if available.
void SetBasePath (std::string basePath)
void SetDirector (std::vector< std::string > director)
void SetWritingCredits (std::vector< std::string > writingCredits)
void SetGenre (std::vector< std::string > genre)
void SetCountry (std::vector< std::string > country)
void SetTagLine (std::string tagLine)
void SetPlotOutline (std::string plotOutline)
void SetTrailer (std::string trailer)
void SetPlot (std::string plot)
std::string const & GetTitle () const
void SetTitle (std::string title)
void SetSortTitle (std::string sortTitle)
void SetPictureURL (CScraperUrl &pictureURL)
void SetRating (float rating, int votes, const std::string &type="", bool def=false)
void SetRating (CRating rating, const std::string &type="", bool def=false)
void SetRating (float rating, const std::string &type="", bool def=false)
void RemoveRating (const std::string &type)
void SetRatings (RatingMap ratings, const std::string &defaultRating="")
void SetVotes (int votes, const std::string &type="")
void SetUniqueIDs (std::map< std::string, std::string > uniqueIDs)
void SetPremiered (const CDateTime &premiered)
void SetPremieredFromDBDate (const std::string &premieredString)
virtual void SetYear (int year)
void SetArtist (std::vector< std::string > artist)
void SetSet (std::string set)
void SetSetOverview (std::string setOverview)
void SetTags (std::vector< std::string > tags)
void SetFile (std::string file)
void SetPath (std::string path)
void SetMPAARating (std::string mpaaRating)
void SetFileNameAndPath (std::string fileNameAndPath)
void SetOriginalTitle (std::string originalTitle)
void SetEpisodeGuide (std::string episodeGuide)
void SetStatus (std::string status)
void SetProductionCode (std::string productionCode)
void SetShowTitle (std::string showTitle)
void SetStudio (std::vector< std::string > studio)
void SetAlbum (std::string album)
void SetShowLink (std::vector< std::string > showLink)
void SetUniqueID (const std::string &uniqueid, const std::string &type="", bool def=false)
void RemoveUniqueID (const std::string &type)
void SetNamedSeasons (std::map< int, std::string > namedSeasons)
void SetUserrating (int userrating)
virtual int GetPlayCount () const
Get this videos's play count.
virtual bool SetPlayCount (int count)
Set this videos's play count.
virtual bool IncrementPlayCount ()
Increment this videos's play count.
virtual void ResetPlayCount ()
Reset playcount.
virtual bool IsPlayCountSet () const
Check if the playcount is set.
virtual CBookmark GetResumePoint () const
Get this videos's resume point.
virtual bool SetResumePoint (const CBookmark &resumePoint)
Set this videos's resume point.
const CAssetInfo & GetAssetInfo () const
Get the video's asset info.
CAssetInfo & GetAssetInfo ()
bool HasVideoVersions () const
Whether the item has multiple video versions.
void SetHasVideoVersions (bool hasVersions)
Set whether this video has video versions.
bool HasVideoExtras () const
Whether the item has video extras.
void SetHasVideoExtras (bool hasExtras)
Set whether this video has video extras.
bool IsDefaultVideoVersion () const
Whether the item is the default video version.
void SetIsDefaultVideoVersion (bool isDefaultVideoVersion)
Set whether the item is the default version.
bool GetUpdateSetOverview () const
Get whether the Set Overview should be updated. If an NFO contains a <name> but no <overview> then this allows the current Overview to be kept. Otherwise it is overwritten. Default is true - so if updated by a scraper the Overview will be overwritten.
virtual bool SetResumePoint (double timeInSeconds, double totalTimeInSeconds, const std::string &playerState)
Set this videos's resume point.
Static Public Member Functions
static unsigned int GetDurationFromMinuteString (const std::string &runtime)
get the duration in seconds from a minute string
Public Attributes
std::string m_basePath
int m_parentPathID
std::vector< std::string > m_director
std::vector< std::string > m_writingCredits
std::vector< std::string > m_genre
std::vector< std::string > m_country
std::string m_strTagLine
std::string m_strPlotOutline
std::string m_strTrailer
std::string m_strPlot
CScraperUrl m_strPictureURL
std::string m_strTitle
std::string m_strSortTitle
std::vector< std::string > m_artist
std::vector< SActorInfo > m_cast
SetInfo m_set
Assigned movie set.
std::vector< std::string > m_tags
std::string m_strFile
std::string m_strPath
std::string m_strMPAARating
std::string m_strFileNameAndPath
std::string m_strOriginalTitle
std::string m_strEpisodeGuide
CDateTime m_premiered
bool m_bHasPremiered
std::string m_strStatus
std::string m_strProductionCode
CDateTime m_firstAired
std::string m_strShowTitle
std::vector< std::string > m_studio
std::string m_strAlbum
CDateTime m_lastPlayed
std::vector< std::string > m_showLink
std::map< int, std::string > m_namedSeasons
int m_iTop250
int m_year
int m_iSeason
int m_iEpisode
int m_iIdUniqueID
int m_iDbId
int m_iFileId
int m_iSpecialSortSeason
int m_iSpecialSortEpisode
int m_iTrack
RatingMap m_ratings
int m_iIdRating
int m_iUserRating
CBookmark m_EpBookmark
int m_iBookmarkId
int m_iIdShow
int m_iIdSeason
CFanart m_fanart
CStreamDetails m_streamDetails
CDateTime m_dateAdded
MediaType m_type
int m_relevance
int m_parsedDetails
std::vector< EmbeddedArtInfo > m_coverArt
art information
unsigned int m_duration
duration in seconds
Private Member Functions
void ParseNative (const TiXmlElement *element, bool prioritise)
std::string Trim (std::string &&value)
std::vector< std::string > Trim (std::vector< std::string > &&items)
Private Attributes
std::string m_strDefaultRating
std::string m_strDefaultUniqueID
std::map< std::string, std::string > m_uniqueIDs
int m_playCount
CBookmark m_resumePoint
CAssetInfo m_assetInfo
bool m_hasVideoVersions {false}
bool m_hasVideoExtras {false}
bool m_isDefaultVideoVersion {false}
bool m_updateSetOverview {true}
Static Private Attributes
static const int PLAYCOUNT_NOT_SET = -1
Additional Inherited Members
Protected Member Functions inherited from IArchivable
virtual ~IArchivable ()=default
Protected Member Functions inherited from ISerializable
~ISerializable ()=default
Protected Member Functions inherited from ISortable
~ISortable ()=default
Member Typedef Documentation
iCast
typedef std::vector<SActorInfo>::const_iterator CVideoInfoTag::iCast
Constructor & Destructor Documentation
CVideoInfoTag()
CVideoInfoTag::CVideoInfoTag () inline
References Reset().
~CVideoInfoTag()
virtual CVideoInfoTag::~CVideoInfoTag () virtual default
Member Function Documentation
Archive()
void CVideoInfoTag::Archive (CArchive & ar) override virtual
Implements IArchivable.
References CVideoInfoTag::CAssetInfo::Archive(), data(), CDateTime::GetAsDBDateTime(), CScraperUrl::GetData(), GetPlayCount(), CVideoInfoTag::SetInfo::id, CArchive::IsStoring(), m_artist, m_assetInfo, m_basePath, m_bHasPremiered, m_cast, m_country, m_coverArt, m_dateAdded, m_director, m_duration, m_EpBookmark, m_fanart, m_firstAired, m_genre, m_hasVideoExtras, m_hasVideoVersions, m_iBookmarkId, m_iDbId, m_iEpisode, m_iFileId, m_iIdSeason, m_iIdShow, m_isDefaultVideoVersion, m_iSeason, m_iSpecialSortEpisode, m_iSpecialSortSeason, m_iTop250, m_iTrack, m_iUserRating, m_lastPlayed, m_namedSeasons, m_parentPathID, m_playCount, m_premiered, m_ratings, m_resumePoint, m_set, m_showLink, m_strAlbum, m_strDefaultRating, m_strDefaultUniqueID, m_streamDetails, m_strEpisodeGuide, m_strFile, m_strFileNameAndPath, m_strMPAARating, m_strOriginalTitle, m_strPath, m_strPictureURL, m_strPlot, m_strPlotOutline, m_strProductionCode, m_strShowTitle, m_strSortTitle, m_strStatus, m_strTagLine, m_strTitle, m_strTrailer, m_studio, m_tags, m_type, m_uniqueIDs, m_writingCredits, CFanart::m_xml, name, CVideoInfoTag::SetInfo::overview, CBookmark::playerState, CRating::rating, CScraperUrl::SetData(), CDateTime::SetFromDBDateTime(), SetRating(), SetUniqueID(), CBookmark::timeInSeconds, CVideoInfoTag::SetInfo::title, CBookmark::totalTimeInSeconds, value, and CRating::votes.
GetAssetInfo() [1/2]
CAssetInfo & CVideoInfoTag::GetAssetInfo () inline
References m_assetInfo.
GetAssetInfo() [2/2]
const CAssetInfo & CVideoInfoTag::GetAssetInfo () const inline
Get the video's asset info.
Returns
The info.
References m_assetInfo.
Referenced by CVideoThumbLoader::FillLibraryArt(), CVideoDatabase::GetDefaultVideoVersion(), CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetVideoVersions(), Merge(), CGUIDialogVideoInfo::OnSearchItemFound(), anonymous_namespace{VideoDatabase.cpp}::RewriteVideoVersionURL(), and XBMCAddon::xbmc::InfoTagVideo::setVideoAssetTitleRaw().
GetCast()
const std::string CVideoInfoTag::GetCast (bool bIncludeRole = false) const
References g_localizeStrings, CLocalizeStrings::Get(), and m_cast.
Referenced by XBMCAddon::xbmc::InfoTagVideo::getCast().
GetDefaultRating()
const std::string & CVideoInfoTag::GetDefaultRating () const
References m_strDefaultRating.
Referenced by CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::UpdateDetailsForMovie(), and CVideoDatabase::UpdateDetailsForTvShow().
GetDefaultUniqueID()
const std::string & CVideoInfoTag::GetDefaultUniqueID () const
References m_strDefaultUniqueID.
Referenced by CVideoDatabase::AddUniqueIDs(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
GetDuration()
unsigned int CVideoInfoTag::GetDuration () const
retrieve the duration in seconds. Prefers the duration from stream details if available.
References CStreamDetails::GetVideoDuration(), m_duration, and m_streamDetails.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording(), PVR::CPVRRecording::EndTimeAsUTC(), XBMCAddon::xbmc::InfoTagVideo::getDuration(), CLabelFormatter::GetMaskContent(), PVR::CPVRRecording::operator==(), ParseItem(), Save(), Serialize(), ToSortable(), and CVideoDatabase::UpdateDetailsForTvShow().
GetDurationFromMinuteString()
unsigned int CVideoInfoTag::GetDurationFromMinuteString (const std::string & runtime) static
get the duration in seconds from a minute string
Parameters
runtime the runtime string from a scraper or similar
Returns
the time in seconds, if decipherable.
References CLog::Log(), LOGWARNING, and str2uint64().
Referenced by ParseNative().
GetFirstAired()
const CDateTime & CVideoInfoTag::GetFirstAired () const
References m_firstAired.
Referenced by GetYear().
GetPath()
const std::string & CVideoInfoTag::GetPath () const inline
References m_strFileNameAndPath, and m_strPath.
Referenced by CVideoDatabase::AddFile(), CVideoDatabase::AddNewEpisode(), CVideoDatabase::AddNewMovie(), CVideoDatabase::AddNewMusicVideo(), CVideoThumbLoader::DetectAndAddMissingItemData(), CVideoDatabase::GetFileId(), JSONRPC::CPlayerOperations::GetItem(), CMime::GetMimeType(), UPNP::GetMimeType(), CGUIDialogVideoInfo::Play(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMusicVideo(), ToSortable(), and CVideoDatabase::UpdateFileDateAdded().
GetPlayCount()
int CVideoInfoTag::GetPlayCount () const virtual
Get this videos's play count.
Returns
the play count.
References IsPlayCountSet(), and m_playCount.
Referenced by CVideoDatabase::AddFile(), KODI::VIDEO::CVideoInfoScanner::AddVideo(), Archive(), CVideoDatabase::GetDetailsForTvShow(), CVideoDatabase::GetEpisodesByWhere(), CVideoDatabase::GetFileInfo(), CGUIWindowVideoNav::GetFirstUnwatchedItemIndex(), PVR::CPVRRecording::GetLocalPlayCount(), CLabelFormatter::GetMaskContent(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideosByWhere(), XBMCAddon::xbmc::InfoTagVideo::getPlayCount(), CFileItem::GetThumbHideIfUnwatched(), GroupUtils::Group(), PVR::CPVRRecording::IncrementPlayCount(), CONTEXTMENU::CVideoMarkWatched::IsVisible(), CONTEXTMENU::CVideoMarkUnWatched::IsVisible(), Merge(), CGUIDialogVideoInfo::OnSearch(), Save(), Serialize(), JSONRPC::CVideoLibrary::SetEpisodeDetails(), JSONRPC::CFileOperations::SetFileDetails(), JSONRPC::CVideoLibrary::SetMovieDetails(), JSONRPC::CVideoLibrary::SetMusicVideoDetails(), CVideoDatabase::SetPlayCount(), ToSortable(), and UPNP::CMediaBrowser::UpdateItem().
GetPremiered()
const CDateTime & CVideoInfoTag::GetPremiered () const
References m_premiered.
Referenced by CVideoDatabase::GetDetailsForTvShow(), CVideoDatabase::GetMatchingTvShow(), XBMCAddon::xbmc::InfoTagVideo::getPremiered(), XBMCAddon::xbmc::InfoTagVideo::getPremieredAsW3C(), GetYear(), Merge(), PVR::CPVRRecording::operator==(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMusicVideo(), and CVideoDatabase::UpdateDetailsForMovie().
GetRating()
const CRating CVideoInfoTag::GetRating (std::string type = "") const
References m_ratings, and m_strDefaultRating.
Referenced by CLabelFormatter::GetMaskContent(), XBMCAddon::xbmcgui::ListItem::getRating(), XBMCAddon::xbmc::InfoTagVideo::getRating(), XBMCAddon::xbmcgui::ListItem::getVotes(), XBMCAddon::xbmc::InfoTagVideo::getVotesAsInt(), GroupUtils::Group(), Serialize(), and ToSortable().
GetResumePoint()
CBookmark CVideoInfoTag::GetResumePoint () const virtual
Get this videos's resume point.
Returns
the resume point.
Reimplemented in PVR::CPVRRecording.
References m_resumePoint.
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), CSaveFileState::DoWork(), CVideoDatabase::GetFileInfo(), PVR::CPVRRecording::GetLocalResumePoint(), CFileItem::GetResumePoint(), PVR::CPVRRecording::GetResumePoint(), XBMCAddon::xbmc::InfoTagVideo::getResumeTime(), XBMCAddon::xbmc::InfoTagVideo::getResumeTimeTotal(), GroupUtils::Group(), CFileItem::IsResumable(), Merge(), CApplication::PlayFile(), UPNP::CMediaBrowser::SaveFileState(), XBMCAddon::xbmc::InfoTagVideo::setResumePointRaw(), and UPNP::CMediaBrowser::UpdateItem().
GetStaticDuration()
unsigned int CVideoInfoTag::GetStaticDuration () const
retrieve the duration in seconds. Ignores the duration from stream details even if available.
References m_duration.
GetTitle()
std::string const & CVideoInfoTag::GetTitle () const
References m_strTitle.
Referenced by CVideoDatabase::GetSameVideoItems(), CGUIDialogVideoManagerVersions::ProcessVideoVersion(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo(), and KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow().
GetUniqueID()
const std::string CVideoInfoTag::GetUniqueID (std::string type = "") const
References m_strDefaultUniqueID, and m_uniqueIDs.
Referenced by ADDON::CScraper::GetArtwork(), XBMCAddon::xbmc::InfoTagVideo::getIMDBNumber(), CVideoDatabase::GetMatchingTvShow(), XBMCAddon::xbmc::InfoTagVideo::getUniqueID(), XBMCAddon::xbmcgui::ListItem::getUniqueID(), Save(), Serialize(), CVideoDatabase::SetDetailsForMovie(), SetUniqueIDs(), and CGUIWindowVideoBase::ShowInfo().
GetUniqueIDs()
const std::map< std::string, std::string > & CVideoInfoTag::GetUniqueIDs () const
References m_uniqueIDs.
Referenced by CVideoDatabase::AddUniqueIDs().
GetUpdateSetOverview()
bool CVideoInfoTag::GetUpdateSetOverview () const inline
Get whether the Set Overview should be updated. If an NFO contains a <name> but no <overview> then this allows the current Overview to be kept. Otherwise it is overwritten. Default is true - so if updated by a scraper the Overview will be overwritten.
References m_updateSetOverview.
Referenced by CVideoDatabase::SetDetailsForMovie().
GetYear()
int CVideoInfoTag::GetYear () const virtual
Reimplemented in PVR::CPVRRecording.
References GetFirstAired(), GetPremiered(), CDateTime::GetYear(), CDateTime::IsValid(), m_firstAired, m_premiered, and m_year.
Referenced by CVideoDatabase::ExportToXML(), CLabelFormatter::GetMaskContent(), CVideoDatabase::GetSameVideoItems(), XBMCAddon::xbmc::InfoTagVideo::getYear(), GroupUtils::Group(), Save(), Serialize(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMusicVideo(), ToSortable(), and CVideoDatabase::UpdateDetailsForMovie().
HasPremiered()
bool CVideoInfoTag::HasPremiered () const
References m_bHasPremiered.
Referenced by Save(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMusicVideo(), and CVideoDatabase::UpdateDetailsForMovie().
HasStreamDetails()
bool CVideoInfoTag::HasStreamDetails () const
References CStreamDetails::HasItems(), and m_streamDetails.
Referenced by CVideoDatabase::AddVideoAsset(), CSaveFileState::DoWork(), CPlayerSelectionRule::GetPlayers(), CVideoThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemLookup(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), and CVideoDatabase::SetDetailsForMusicVideo().
HasUniqueID()
bool CVideoInfoTag::HasUniqueID () const
References m_uniqueIDs.
Referenced by ADDON::CScraper::GetArtwork(), CVideoDatabase::GetMatchingTvShow(), and CVideoDatabase::SetDetailsForMovie().
HasVideoExtras()
bool CVideoInfoTag::HasVideoExtras () const inline
Whether the item has video extras.
Returns
True if the item has video extras, false otherwise.
References m_hasVideoExtras.
Referenced by CFileItem::HasVideoExtras().
HasVideoVersions()
bool CVideoInfoTag::HasVideoVersions () const inline
Whether the item has multiple video versions.
Returns
True if the item has multiple video versions, false otherwise.
References m_hasVideoVersions.
Referenced by CFileItem::HasVideoVersions().
HasYear()
bool CVideoInfoTag::HasYear () const virtual
Reimplemented in PVR::CPVRRecording.
References CDateTime::IsValid(), m_firstAired, m_premiered, and m_year.
Referenced by CVideoDatabase::ExportToXML(), CLabelFormatter::GetMaskContent(), CVideoDatabase::GetSameVideoItems(), Save(), and CVideoDatabase::SetDetailsForMovie().
IncrementPlayCount()
bool CVideoInfoTag::IncrementPlayCount () virtual
Increment this videos's play count.
Returns
True if play count was increased successfully, false otherwise.
Reimplemented in PVR::CPVRRecording.
References IsPlayCountSet(), and m_playCount.
Referenced by CSaveFileState::DoWork(), and PVR::CPVRRecording::IncrementPlayCount().
IsDefaultVideoVersion()
bool CVideoInfoTag::IsDefaultVideoVersion () const inline
Whether the item is the default video version.
Returns
True if the item is the default version, false otherwise.
References m_isDefaultVideoVersion.
IsEmpty()
bool CVideoInfoTag::IsEmpty () const
References m_strFile, m_strPath, and m_strTitle.
Referenced by JSONRPC::CVideoLibrary::FillFileItemList(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetBool(), CVideoDatabase::GetEpisodeBasicInfo(), CVideoDatabase::GetEpisodeInfo(), CVideoDatabase::GetFileInfo(), CVideoDatabase::GetMovieInfo(), CVideoDatabase::GetMusicVideoInfo(), CVideoDatabase::GetSetInfo(), CVideoDatabase::GetTvShowInfo(), and CGUIWindowVideoNav::OnMessage().
IsPlayCountSet()
bool CVideoInfoTag::IsPlayCountSet () const virtual
Check if the playcount is set.
Returns
True if play count value is set
References m_playCount, and PLAYCOUNT_NOT_SET.
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), GetPlayCount(), IncrementPlayCount(), and Merge().
Load()
bool CVideoInfoTag::Load (const TiXmlElement * element, bool append = false, bool prioritise = false)
References ParseNative(), and Reset().
Referenced by ADDON::CScraper::GetArtwork(), ADDON::CScraper::GetVideoDetails(), and CVideoDatabase::ImportFromXML().
Merge()
void CVideoInfoTag::Merge (CVideoInfoTag & other)
References GetAssetInfo(), CFanart::GetNumFanarts(), GetPlayCount(), GetPremiered(), GetResumePoint(), CScraperUrl::HasData(), CStreamDetails::HasItems(), CVideoInfoTag::SetInfo::id, IsPlayCountSet(), CBookmark::IsSet(), CDateTime::IsValid(), m_artist, m_assetInfo, m_basePath, m_cast, m_country, m_coverArt, m_dateAdded, m_director, m_duration, m_EpBookmark, m_fanart, m_firstAired, m_genre, m_hasVideoExtras, m_hasVideoVersions, m_iBookmarkId, m_iDbId, m_iEpisode, m_iFileId, m_iIdRating, m_iIdSeason, m_iIdShow, m_iIdUniqueID, m_isDefaultVideoVersion, m_iSeason, m_iSpecialSortEpisode, m_iSpecialSortSeason, m_iTop250, m_iTrack, m_iUserRating, m_lastPlayed, m_namedSeasons, m_parentPathID, m_parsedDetails, m_premiered, m_ratings, m_relevance, m_set, m_showLink, m_strAlbum, m_strDefaultRating, m_strDefaultUniqueID, m_streamDetails, m_strFile, m_strFileNameAndPath, m_strMPAARating, m_strOriginalTitle, m_strPath, m_strPictureURL, m_strPlot, m_strPlotOutline, m_strProductionCode, m_strShowTitle, m_strSortTitle, m_strStatus, m_strTagLine, m_strTitle, m_strTrailer, m_studio, m_tags, m_type, m_uniqueIDs, m_writingCredits, m_year, CVideoInfoTag::CAssetInfo::Merge(), CVideoInfoTag::SetInfo::overview, SetPlayCount(), SetPremiered(), SetResumePoint(), and CVideoInfoTag::SetInfo::title.
Referenced by CFileItem::MergeInfo().
ParseNative()
void CVideoInfoTag::ParseNative (const TiXmlElement * element, bool prioritise) private
References CStreamDetails::AddStream(), CStreamDetails::DetermineBestStreams(), CScraperUrl::GetData(), XMLUtils::GetDate(), XMLUtils::GetDateTime(), XMLUtils::GetDouble(), GetDurationFromMinuteString(), XMLUtils::GetFloat(), XMLUtils::GetInt(), CServiceBroker::GetSettingsComponent(), XMLUtils::GetString(), XMLUtils::GetStringArray(), CScraperUrl::GetUrls(), m_artist, m_assetInfo, m_bHasPremiered, m_cast, m_country, m_dateAdded, m_director, m_duration, m_EpBookmark, m_fanart, CStreamDetailVideo::m_fAspect, m_firstAired, m_genre, CStreamDetailAudio::m_iChannels, CStreamDetailVideo::m_iDuration, m_iEpisode, CStreamDetailVideo::m_iHeight, m_iSeason, m_iSpecialSortEpisode, m_iSpecialSortSeason, m_iTop250, m_iTrack, m_iUserRating, CStreamDetailVideo::m_iWidth, m_lastPlayed, m_namedSeasons, m_playCount, m_premiered, m_resumePoint, m_showLink, CStreamDetailVideo::m_strCodec, CStreamDetailAudio::m_strCodec, m_strDefaultRating, m_strDefaultUniqueID, m_streamDetails, m_strEpisodeGuide, CStreamDetailVideo::m_strHdrType, CStreamDetailVideo::m_strLanguage, CStreamDetailAudio::m_strLanguage, CStreamDetailSubtitle::m_strLanguage, m_strPictureURL, CStreamDetailVideo::m_strStereoMode, m_studio, m_tags, m_updateSetOverview, m_writingCredits, CFanart::m_xml, name, node, CScraperUrl::Parse(), CScraperUrl::ParseAndAppendUrl(), CVideoInfoTag::CAssetInfo::ParseNative(), CBookmark::playerState, CRating::rating, SetAlbum(), SetArtist(), SetBasePath(), SetCountry(), CScraperUrl::SetData(), SetDirector(), SetFile(), SetFileNameAndPath(), SetGenre(), SetMPAARating(), SetOriginalTitle(), SetPath(), SetPlot(), SetPlotOutline(), SetProductionCode(), SetRating(), SetSet(), SetSetOverview(), SetShowLink(), SetShowTitle(), SetSortTitle(), SetStatus(), SetStudio(), SetTagLine(), SetTags(), SetTitle(), SetTrailer(), SetUniqueID(), CScraperUrl::SetUrls(), SetWritingCredits(), SetYear(), SActorInfo::strName, tags, CBookmark::timeInSeconds, CBookmark::totalTimeInSeconds, CFanart::Unpack(), value, and CRating::votes.
Referenced by Load().
RemoveRating()
void CVideoInfoTag::RemoveRating (const std::string & type)
References m_ratings, and m_strDefaultRating.
Referenced by JSONRPC::CVideoLibrary::UpdateVideoTag().
RemoveUniqueID()
void CVideoInfoTag::RemoveUniqueID (const std::string & type)
References m_uniqueIDs.
Referenced by JSONRPC::CVideoLibrary::UpdateVideoTag().
Reset()
void CVideoInfoTag::Reset ()
References CScraperUrl::Clear(), CVideoInfoTag::CAssetInfo::Clear(), CBookmark::EPISODE, CVideoInfoTag::SetInfo::id, m_artist, m_assetInfo, m_basePath, m_bHasPremiered, m_cast, m_country, m_coverArt, m_dateAdded, m_director, m_duration, m_EpBookmark, m_fanart, m_firstAired, m_genre, m_hasVideoExtras, m_hasVideoVersions, m_iBookmarkId, m_iDbId, m_iEpisode, m_iFileId, m_iIdRating, m_iIdSeason, m_iIdShow, m_iIdUniqueID, m_isDefaultVideoVersion, m_iSeason, m_iSpecialSortEpisode, m_iSpecialSortSeason, m_iTop250, m_iTrack, m_iUserRating, m_lastPlayed, m_namedSeasons, m_parentPathID, m_parsedDetails, m_playCount, m_premiered, m_ratings, m_relevance, m_resumePoint, m_set, m_showLink, m_strAlbum, m_strDefaultRating, m_strDefaultUniqueID, m_streamDetails, m_strFile, m_strFileNameAndPath, m_strMPAARating, m_strOriginalTitle, m_strPath, m_strPictureURL, m_strPlot, m_strPlotOutline, m_strProductionCode, m_strShowTitle, m_strSortTitle, m_strStatus, m_strTagLine, m_strTitle, m_strTrailer, m_studio, m_tags, m_type, m_uniqueIDs, m_updateSetOverview, m_writingCredits, CFanart::m_xml, m_year, CVideoInfoTag::SetInfo::overview, PLAYCOUNT_NOT_SET, CBookmark::Reset(), CDateTime::Reset(), CStreamDetails::Reset(), CBookmark::RESUME, CVideoInfoTag::SetInfo::title, and CBookmark::type.
Referenced by CNfoFile::Create(), CVideoInfoTag(), CVideoInfoDownloader::GetDetails(), CVideoDatabase::GetDetailsByTypeAndId(), CVideoInfoDownloader::GetEpisodeDetails(), ADDON::CScraper::GetVideoDetails(), Load(), PVR::CPVRRecording::Reset(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo(), and KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow().
ResetPlayCount()
void CVideoInfoTag::ResetPlayCount () virtual
Reset playcount.
References m_playCount, and PLAYCOUNT_NOT_SET.
Save()
bool CVideoInfoTag::Save (TiXmlNode * node, const std::string & tag, bool savePathInfo = true, const TiXmlElement * additionalNode = NULL)
References CStreamDetails::GetAudioChannels(), CStreamDetails::GetAudioCodec(), CStreamDetails::GetAudioLanguage(), CStreamDetails::GetAudioStreamCount(), CScraperUrl::GetData(), GetDuration(), GetPlayCount(), CStreamDetails::GetStereoMode(), CStreamDetails::GetSubtitleLanguage(), CStreamDetails::GetSubtitleStreamCount(), GetUniqueID(), CStreamDetails::GetVideoAspect(), CStreamDetails::GetVideoCodec(), CStreamDetails::GetVideoDuration(), CStreamDetails::GetVideoHdrType(), CStreamDetails::GetVideoHeight(), CStreamDetails::GetVideoStreamCount(), CStreamDetails::GetVideoWidth(), GetYear(), CScraperUrl::HasData(), CStreamDetails::HasItems(), HasPremiered(), HasYear(), m_artist, m_assetInfo, m_basePath, m_cast, m_country, m_dateAdded, m_director, m_EpBookmark, m_fanart, m_firstAired, m_genre, m_hasVideoExtras, m_hasVideoVersions, m_iEpisode, m_isDefaultVideoVersion, m_iSeason, m_iSpecialSortEpisode, m_iSpecialSortSeason, m_iTop250, m_iTrack, m_iUserRating, m_lastPlayed, m_namedSeasons, m_premiered, m_ratings, m_resumePoint, m_set, m_showLink, m_strAlbum, m_strDefaultRating, m_strDefaultUniqueID, m_streamDetails, m_strEpisodeGuide, m_strFile, m_strFileNameAndPath, m_strMPAARating, m_strOriginalTitle, m_strPath, m_strPictureURL, m_strPlot, m_strPlotOutline, m_strProductionCode, m_strShowTitle, m_strSortTitle, m_strStatus, m_strTagLine, m_strTitle, m_strTrailer, m_studio, m_tags, m_uniqueIDs, m_writingCredits, CFanart::m_xml, node, CVideoInfoTag::SetInfo::overview, CXBMCTinyXML::Parse(), CBookmark::playerState, CVideoInfoTag::CAssetInfo::Save(), XMLUtils::SetBoolean(), XMLUtils::SetDate(), XMLUtils::SetDateTime(), XMLUtils::SetDouble(), XMLUtils::SetFloat(), XMLUtils::SetInt(), XMLUtils::SetString(), XMLUtils::SetStringArray(), CBookmark::timeInSeconds, CVideoInfoTag::SetInfo::title, CBookmark::totalTimeInSeconds, and value.
Referenced by CVideoDatabase::ExportToXML().
Serialize()
void CVideoInfoTag::Serialize (CVariant & value) const override virtual
Implements ISerializable.
References CDateTime::GetAsDBDate(), CDateTime::GetAsDBDateTime(), GetDuration(), GetPlayCount(), GetRating(), GetUniqueID(), GetYear(), CVideoInfoTag::SetInfo::id, CDateTime::IsValid(), m_artist, m_assetInfo, m_cast, m_country, m_dateAdded, m_director, m_firstAired, m_genre, m_hasVideoExtras, m_hasVideoVersions, m_iDbId, m_iEpisode, m_iFileId, m_iIdSeason, m_iIdShow, m_isDefaultVideoVersion, m_iSeason, m_iSpecialSortEpisode, m_iSpecialSortSeason, m_iTop250, m_iTrack, m_iUserRating, m_lastPlayed, m_premiered, m_ratings, m_resumePoint, m_set, m_showLink, m_strAlbum, m_strDefaultRating, m_streamDetails, m_strEpisodeGuide, m_strFile, m_strFileNameAndPath, m_strMPAARating, m_strOriginalTitle, m_strPath, m_strPlot, m_strPlotOutline, m_strProductionCode, m_strShowTitle, m_strSortTitle, m_strStatus, m_strTagLine, m_strTitle, m_strTrailer, m_studio, m_tags, m_type, m_uniqueIDs, m_writingCredits, CVideoInfoTag::SetInfo::overview, CRating::rating, CVideoInfoTag::CAssetInfo::Serialize(), CStreamDetails::Serialize(), CBookmark::timeInSeconds, CVideoInfoTag::SetInfo::title, CBookmark::totalTimeInSeconds, IMAGE_FILES::URLFromFile(), value, CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
Referenced by PVR::CPVRRecording::Serialize().
SetAlbum()
void CVideoInfoTag::SetAlbum (std::string album)
References m_strAlbum, and Trim().
Referenced by ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setAlbumRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetArtist()
void CVideoInfoTag::SetArtist (std::vector< std::string > artist)
References m_artist, and Trim().
Referenced by ParseNative(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetBasePath()
void CVideoInfoTag::SetBasePath (std::string basePath)
References m_basePath, and Trim().
Referenced by ParseNative().
SetCountry()
void CVideoInfoTag::SetCountry (std::vector< std::string > country)
References m_country, and Trim().
Referenced by ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setCountriesRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetDirector()
void CVideoInfoTag::SetDirector (std::vector< std::string > director)
References m_director, and Trim().
Referenced by ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setDirectorsRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetDuration()
void CVideoInfoTag::SetDuration (int duration)
set the duration in seconds
Parameters
duration the duration to set
References m_duration.
Referenced by PVR::CPVRRecording::CPVRRecording(), CVideoDatabase::GetDetailsForTvShow(), ParseItem(), ParseItemBoxee(), ParseItemItunes(), ParseItemZink(), XBMCAddon::xbmc::InfoTagVideo::setDurationRaw(), PVR::CPVRRecording::Update(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetEpisodeGuide()
void CVideoInfoTag::SetEpisodeGuide (std::string episodeGuide)
References m_strEpisodeGuide, and Trim().
Referenced by XBMCAddon::xbmc::InfoTagVideo::setEpisodeGuideRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetFile()
void CVideoInfoTag::SetFile (std::string file)
References m_strFile, and Trim().
Referenced by ParseNative().
SetFileNameAndPath()
void CVideoInfoTag::SetFileNameAndPath (std::string fileNameAndPath)
References m_strFileNameAndPath, and Trim().
Referenced by ParseNative(), and XBMCAddon::xbmc::InfoTagVideo::setFilenameAndPathRaw().
SetGenre()
void CVideoInfoTag::SetGenre (std::vector< std::string > genre)
References m_genre, and Trim().
Referenced by ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setGenresRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetHasVideoExtras()
void CVideoInfoTag::SetHasVideoExtras (bool hasExtras)
Set whether this video has video extras.
Parameters
hasExtras The extras flag.
References m_hasVideoExtras.
Referenced by CVideoDatabase::GetDetailsForMovie().
SetHasVideoVersions()
void CVideoInfoTag::SetHasVideoVersions (bool hasVersions)
Set whether this video has video versions.
Parameters
hasVersion The versions flag.
References m_hasVideoVersions.
Referenced by CVideoDatabase::GetDetailsForMovie().
SetIsDefaultVideoVersion()
void CVideoInfoTag::SetIsDefaultVideoVersion (bool isDefaultVideoVersion)
Set whether the item is the default version.
Parameters
isDefaultVideoVersion The default flag.
References m_isDefaultVideoVersion.
Referenced by CVideoDatabase::GetDetailsForMovie().
SetMPAARating()
void CVideoInfoTag::SetMPAARating (std::string mpaaRating)
References m_strMPAARating, and Trim().
Referenced by ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setMpaaRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetNamedSeasons()
void CVideoInfoTag::SetNamedSeasons (std::map< int, std::string > namedSeasons)
References m_namedSeasons.
SetOriginalTitle()
void CVideoInfoTag::SetOriginalTitle (std::string originalTitle)
References m_strOriginalTitle, and Trim().
Referenced by ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setOriginalTitleRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetPath()
void CVideoInfoTag::SetPath (std::string path)
References m_strPath, and Trim().
Referenced by CVideoDatabase::GetMusicVideoAlbumsNav(), ParseNative(), and XBMCAddon::xbmc::InfoTagVideo::setPathRaw().
SetPictureURL()
void CVideoInfoTag::SetPictureURL (CScraperUrl & pictureURL)
References m_strPictureURL.
SetPlayCount()
bool CVideoInfoTag::SetPlayCount (int count) virtual
Set this videos's play count.
Parameters
count play count.
Returns
True if play count was set successfully, false otherwise.
Reimplemented in PVR::CPVRRecording.
References m_playCount.
Referenced by PVR::CPVRRecording::CPVRRecording(), CVideoDatabase::GetDetailsForEpisode(), CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetDetailsForMusicVideo(), CVideoDatabase::GetDetailsForTvShow(), CVideoDatabase::GetFileInfo(), GroupUtils::Group(), Merge(), ParseItemBoxee(), ParseItemMRSS(), ParseItemZink(), JSONRPC::CVideoLibrary::SetEpisodeDetails(), PVR::CPVRRecording::SetLocalPlayCount(), JSONRPC::CVideoLibrary::SetMovieDetails(), JSONRPC::CVideoLibrary::SetMusicVideoDetails(), PVR::CPVRRecording::SetPlayCount(), XBMCAddon::xbmc::InfoTagVideo::setPlaycountRaw(), PVR::CPVRRecording::Update(), PVR::CPVRRecording::UpdateMetadata(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetPlot()
void CVideoInfoTag::SetPlot (std::string plot)
References m_strPlot, and Trim().
Referenced by ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setPlotRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetPlotOutline()
void CVideoInfoTag::SetPlotOutline (std::string plotOutline)
References m_strPlotOutline, and Trim().
Referenced by ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setPlotOutlineRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetPremiered()
void CVideoInfoTag::SetPremiered (const CDateTime & premiered)
References CDateTime::IsValid(), m_bHasPremiered, and m_premiered.
Referenced by Merge(), SetPremieredFromDBDate(), XBMCAddon::xbmc::InfoTagVideo::setPremieredRaw(), PVR::CPVRRecording::Update(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetPremieredFromDBDate()
void CVideoInfoTag::SetPremieredFromDBDate (const std::string & premieredString)
References CDateTime::SetFromDBDate(), and SetPremiered().
Referenced by CVideoDatabase::GetDetailsForEpisode(), CVideoDatabase::GetDetailsForMovie(), and CVideoDatabase::GetDetailsForMusicVideo().
SetProductionCode()
void CVideoInfoTag::SetProductionCode (std::string productionCode)
References m_strProductionCode, and Trim().
Referenced by ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setProductionCodeRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetRating() [1/3]
void CVideoInfoTag::SetRating (CRating rating, const std::string & type = "", bool def = false)
References m_ratings, m_strDefaultRating, and CRating::rating.
SetRating() [2/3]
void CVideoInfoTag::SetRating (float rating, const std::string & type = "", bool def = false)
References m_ratings, m_strDefaultRating, and CRating::rating.
SetRating() [3/3]
void CVideoInfoTag::SetRating (float rating, int votes, const std::string & type = "", bool def = false)
References SetRating().
Referenced by Archive(), CVideoDatabase::GetDetailsForEpisode(), CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetDetailsForTvShow(), ParseItemMRSS(), ParseItemVoddler(), ParseItemZink(), ParseNative(), SetRating(), XBMCAddon::xbmc::InfoTagVideo::setRatingRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetRatings()
void CVideoInfoTag::SetRatings (RatingMap ratings, const std::string & defaultRating = "")
References m_ratings, and m_strDefaultRating.
SetResumePoint() [1/2]
bool CVideoInfoTag::SetResumePoint (const CBookmark & resumePoint) virtual
Set this videos's resume point.
Parameters
resumePoint resume point.
Returns
True if resume point was set successfully, false otherwise.
Reimplemented in PVR::CPVRRecording.
References m_resumePoint.
Referenced by PVR::CPVRRecording::CPVRRecording(), CSaveFileState::DoWork(), CVideoDatabase::GetDetailsForEpisode(), CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetDetailsForMusicVideo(), CVideoDatabase::GetFileInfo(), Merge(), XBMCAddon::xbmcgui::ListItem::setProperty(), PVR::CPVRRecording::SetResumePoint(), PVR::CPVRRecording::SetResumePoint(), XBMCAddon::xbmc::InfoTagVideo::setResumePointRaw(), PVR::CPVRRecording::Update(), and PVR::CPVRRecording::UpdateMetadata().
SetResumePoint() [2/2]
bool CVideoInfoTag::SetResumePoint (double timeInSeconds, double totalTimeInSeconds, const std::string & playerState) virtual
Set this videos's resume point.
Parameters
timeInSeconds the time of the resume point
totalTimeInSeconds the total time of the video
playerState the player state
Returns
True if resume point was set successfully, false otherwise.
Reimplemented in PVR::CPVRRecording.
References m_resumePoint, CBookmark::playerState, CBookmark::RESUME, CBookmark::timeInSeconds, CBookmark::totalTimeInSeconds, and CBookmark::type.
SetSet()
void CVideoInfoTag::SetSet (std::string set)
References m_set, CVideoInfoTag::SetInfo::title, and Trim().
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setSetRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetSetOverview()
void CVideoInfoTag::SetSetOverview (std::string setOverview)
References m_set, CVideoInfoTag::SetInfo::overview, and Trim().
Referenced by ParseNative(), and XBMCAddon::xbmc::InfoTagVideo::setSetOverviewRaw().
SetShowLink()
void CVideoInfoTag::SetShowLink (std::vector< std::string > showLink)
References m_showLink, and Trim().
Referenced by ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setShowLinksRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetShowTitle()
void CVideoInfoTag::SetShowTitle (std::string showTitle)
References m_strShowTitle, and Trim().
Referenced by ParseNative(), and XBMCAddon::xbmc::InfoTagVideo::setTvShowTitleRaw().
SetSortTitle()
void CVideoInfoTag::SetSortTitle (std::string sortTitle)
References m_strSortTitle, and Trim().
Referenced by ParseNative(), JSONRPC::CVideoLibrary::SetSeasonDetails(), XBMCAddon::xbmc::InfoTagVideo::setSortTitleRaw(), CVideoDatabase::UpdateDetailsForTvShow(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetStatus()
void CVideoInfoTag::SetStatus (std::string status)
References m_strStatus, and Trim().
Referenced by ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setTvShowStatusRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetStudio()
void CVideoInfoTag::SetStudio (std::vector< std::string > studio)
References m_studio, and Trim().
Referenced by ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setStudiosRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetTagLine()
void CVideoInfoTag::SetTagLine (std::string tagLine)
References m_strTagLine, and Trim().
Referenced by ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setTagLineRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetTags()
void CVideoInfoTag::SetTags (std::vector< std::string > tags)
References m_tags, tags, and Trim().
Referenced by ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setTagsRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetTitle()
void CVideoInfoTag::SetTitle (std::string title)
References m_strTitle, and Trim().
Referenced by ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setTitleRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetTrailer()
void CVideoInfoTag::SetTrailer (std::string trailer)
References m_strTrailer, and Trim().
Referenced by ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setTrailerRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetUniqueID()
void CVideoInfoTag::SetUniqueID (const std::string & uniqueid, const std::string & type = "", bool def = false)
References m_strDefaultUniqueID, and m_uniqueIDs.
Referenced by Archive(), CVideoDatabase::GetDetailsForEpisode(), CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetDetailsForMusicVideo(), CVideoDatabase::GetDetailsForTvShow(), CVideoDatabase::GetUniqueIDs(), ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setIMDBNumberRaw(), XBMCAddon::xbmc::InfoTagVideo::setUniqueIDRaw(), XBMCAddon::xbmc::InfoTagVideo::setUniqueIDsRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetUniqueIDs()
void CVideoInfoTag::SetUniqueIDs (std::map< std::string, std::string > uniqueIDs)
References GetUniqueID(), m_strDefaultUniqueID, and m_uniqueIDs.
Referenced by XBMCAddon::xbmc::InfoTagVideo::setUniqueIDsRaw().
SetUserrating()
void CVideoInfoTag::SetUserrating (int userrating)
References m_iUserRating.
SetVotes()
void CVideoInfoTag::SetVotes (int votes, const std::string & type = "")
References m_ratings, and m_strDefaultRating.
Referenced by XBMCAddon::xbmc::InfoTagVideo::setVotesRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetWritingCredits()
void CVideoInfoTag::SetWritingCredits (std::vector< std::string > writingCredits)
References m_writingCredits, and Trim().
Referenced by ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setWritersRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
SetYear()
void CVideoInfoTag::SetYear (int year) virtual
Reimplemented in PVR::CPVRRecording.
References m_year.
Referenced by CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetDetailsForMusicVideo(), GroupUtils::Group(), ParseItemVoddler(), ParseNative(), XBMCAddon::xbmc::InfoTagVideo::setYearRaw(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
ToSortable()
void CVideoInfoTag::ToSortable (SortItem & sortable, Field field) const override virtual
Implements ISortable.
References FieldAirDate, FieldAlbum, FieldArtist, FieldAudioChannels, FieldAudioCodec, FieldAudioLanguage, FieldCountry, FieldDateAdded, FieldDirector, FieldEpisodeNumber, FieldEpisodeNumberSpecialSort, FieldFilename, FieldGenre, FieldId, FieldInProgress, FieldLastPlayed, FieldMediaType, FieldMPAA, FieldNumberOfEpisodes, FieldNumberOfWatchedEpisodes, FieldOriginalTitle, FieldPath, FieldPlaycount, FieldPlot, FieldPlotOutline, FieldProductionCode, FieldRating, FieldRelevance, FieldSeason, FieldSeasonSpecialSort, FieldSet, FieldSortTitle, FieldStereoMode, FieldStudio, FieldSubtitleLanguage, FieldTag, FieldTagline, FieldTime, FieldTitle, FieldTop250, FieldTrackNumber, FieldTrailer, FieldTvShowStatus, FieldTvShowTitle, FieldUserRating, FieldVideoAspectRatio, FieldVideoAssetTitle, FieldVideoCodec, FieldVideoResolution, FieldVotes, FieldWriter, FieldYear, g_localizeStrings, CLocalizeStrings::Get(), CDateTime::GetAsDBDate(), CDateTime::GetAsDBDateTime(), CStreamDetails::GetAudioChannels(), CStreamDetails::GetAudioCodec(), CStreamDetails::GetAudioLanguage(), GetDuration(), GetPath(), GetPlayCount(), GetRating(), CStreamDetails::GetStereoMode(), CStreamDetails::GetSubtitleLanguage(), CVideoInfoTag::CAssetInfo::GetTitle(), CStreamDetails::GetVideoAspect(), CStreamDetails::GetVideoCodec(), CStreamDetails::GetVideoHeight(), GetYear(), CBookmark::IsPartWay(), CDateTime::IsValid(), m_artist, m_assetInfo, m_country, m_dateAdded, m_director, m_firstAired, m_genre, m_iDbId, m_iEpisode, m_iSeason, m_iSpecialSortEpisode, m_iSpecialSortSeason, m_iTop250, m_iTrack, m_iUserRating, m_lastPlayed, m_premiered, m_relevance, m_resumePoint, m_set, m_strAlbum, m_streamDetails, m_strFile, m_strMPAARating, m_strOriginalTitle, m_strPlot, m_strPlotOutline, m_strProductionCode, m_strShowTitle, m_strSortTitle, m_strStatus, m_strTagLine, m_strTitle, m_strTrailer, m_studio, m_tags, m_type, m_writingCredits, MediaTypeSeason, CRating::rating, CVideoInfoTag::SetInfo::title, and CRating::votes.
Referenced by CFileItem::ToSortable(), and PVR::CPVRRecording::ToSortable().
Trim() [1/2]
std::string CVideoInfoTag::Trim (std::string && value) private
References value.
Referenced by SetAlbum(), SetArtist(), SetBasePath(), SetCountry(), SetDirector(), SetEpisodeGuide(), SetFile(), SetFileNameAndPath(), SetGenre(), SetMPAARating(), SetOriginalTitle(), SetPath(), SetPlot(), SetPlotOutline(), SetProductionCode(), SetSet(), SetSetOverview(), SetShowLink(), SetShowTitle(), SetSortTitle(), SetStatus(), SetStudio(), SetTagLine(), SetTags(), SetTitle(), SetTrailer(), and SetWritingCredits().
Trim() [2/2]
std::vector< std::string > CVideoInfoTag::Trim (std::vector< std::string > && items) private
Member Data Documentation
m_artist
std::vector<std::string> CVideoInfoTag::m_artist
Referenced by Archive(), CVideoDatabase::ExportToXML(), XBMCAddon::xbmc::InfoTagVideo::getArtist(), CLabelFormatter::GetMaskContent(), CVideoDatabase::GetMusicVideoAlbumsNav(), Merge(), ParseNative(), Reset(), Save(), Serialize(), SetArtist(), XBMCAddon::xbmc::InfoTagVideo::setArtistsRaw(), CVideoDatabase::SetDetailsForMusicVideo(), ToSortable(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
m_assetInfo
CAssetInfo CVideoInfoTag::m_assetInfo private
Referenced by Archive(), GetAssetInfo(), GetAssetInfo(), Merge(), ParseNative(), Reset(), Save(), Serialize(), and ToSortable().
m_basePath
std::string CVideoInfoTag::m_basePath
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), Archive(), CVideoDatabase::GetDetailsForTvShow(), CUtil::GetVideoBasePathAndFileName(), GroupUtils::Group(), Merge(), Reset(), Save(), and SetBasePath().
m_bHasPremiered
bool CVideoInfoTag::m_bHasPremiered
Referenced by Archive(), CVideoDatabase::GetDetailsForTvShow(), HasPremiered(), ParseNative(), Reset(), and SetPremiered().
m_cast
std::vector< SActorInfo > CVideoInfoTag::m_cast
Referenced by Archive(), XBMCAddon::xbmc::InfoTagVideo::getActors(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), GetCast(), CVideoDatabase::GetDetailsForEpisode(), CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetDetailsForMusicVideo(), CVideoDatabase::GetDetailsForTvShow(), Merge(), ParseItemMRSS(), ParseNative(), Reset(), Save(), Serialize(), XBMCAddon::xbmc::InfoTagVideo::setCastRaw(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMusicVideo(), and CVideoDatabase::UpdateDetailsForTvShow().
m_country
std::vector<std::string> CVideoInfoTag::m_country
Referenced by Archive(), Merge(), ParseNative(), Reset(), Save(), Serialize(), SetCountry(), CVideoDatabase::SetDetailsForMovie(), ToSortable(), CVideoDatabase::UpdateDetailsForMovie(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
m_coverArt
std::vector<EmbeddedArtInfo> CVideoInfoTag::m_coverArt
art information
Referenced by Archive(), CVideoThumbLoader::FillThumb(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), CVideoThumbLoader::LoadItemLookup(), Merge(), and Reset().
m_dateAdded
CDateTime CVideoInfoTag::m_dateAdded
Referenced by CVideoDatabase::AddFile(), Archive(), CVideoDatabase::GetDetailsForEpisode(), CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetDetailsForMusicVideo(), CVideoDatabase::GetDetailsForTvShow(), CVideoDatabase::GetFileInfo(), CLabelFormatter::GetMaskContent(), GroupUtils::Group(), Merge(), ParseNative(), Reset(), Save(), Serialize(), XBMCAddon::xbmc::InfoTagVideo::setDateAddedRaw(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMusicVideo(), CVideoDatabase::SetDetailsForTvShow(), ToSortable(), CVideoDatabase::UpdateDetailsForMovie(), CVideoDatabase::UpdateFileDateAdded(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
m_director
std::vector<std::string> CVideoInfoTag::m_director
Referenced by Archive(), XBMCAddon::xbmc::InfoTagVideo::getDirector(), XBMCAddon::xbmc::InfoTagVideo::getDirectors(), Merge(), ParseItemMRSS(), ParseNative(), Reset(), Save(), Serialize(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMusicVideo(), SetDirector(), ToSortable(), CVideoDatabase::UpdateDetailsForMovie(), CVideoDatabase::UpdateDetailsForTvShow(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
m_duration
unsigned int CVideoInfoTag::m_duration
duration in seconds
Referenced by Archive(), GetDuration(), PVR::CPVRRecording::GetResumePoint(), GetStaticDuration(), Merge(), ParseNative(), Reset(), and SetDuration().
m_EpBookmark
CBookmark CVideoInfoTag::m_EpBookmark
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), Archive(), CVideoDatabase::GetDetailsForEpisode(), Merge(), ParseNative(), Reset(), and Save().
m_fanart
CFanart CVideoInfoTag::m_fanart
Referenced by Archive(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), CGUIWindowVideoNav::GetDirectory(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::GetRemoteArt(), CVideoDatabase::GetVideoVersions(), Merge(), ParseNative(), Reset(), Save(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::UpdateEmbeddedArt(), CVideoDatabase::UpdateFanart(), and KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::UpdateRemoteArt().
m_firstAired
CDateTime CVideoInfoTag::m_firstAired
Referenced by Archive(), PVR::CPVRRecording::CPVRRecording(), PVR::CPVRRecording::FirstAired(), CVideoDatabase::GetEpisodesByWhere(), XBMCAddon::xbmc::InfoTagVideo::getFirstAired(), GetFirstAired(), XBMCAddon::xbmc::InfoTagVideo::getFirstAiredAsW3C(), CLabelFormatter::GetMaskContent(), GetYear(), HasYear(), Merge(), PVR::CPVRRecording::operator==(), ParseItemZink(), ParseNative(), KODI::VIDEO::CVideoInfoScanner::ProcessItemByVideoInfoTag(), Reset(), Save(), Serialize(), XBMCAddon::xbmc::InfoTagVideo::setFirstAiredRaw(), ToSortable(), PVR::CPVRRecording::Update(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
m_genre
std::vector<std::string> CVideoInfoTag::m_genre
Referenced by Archive(), PVR::CPVRRecording::Genre(), CVideoDatabase::GetDetailsForEpisode(), XBMCAddon::xbmc::InfoTagVideo::getGenre(), XBMCAddon::xbmc::InfoTagVideo::getGenres(), PVR::CPVRRecording::GetGenresLabel(), CLabelFormatter::GetMaskContent(), Merge(), PVR::CPVRRecording::operator==(), ParseItemMRSS(), ParseNative(), Reset(), Save(), PVR::CPVRRecording::Serialize(), Serialize(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMusicVideo(), PVR::CPVRRecording::SetGenre(), SetGenre(), ToSortable(), PVR::CPVRRecording::Update(), CVideoDatabase::UpdateDetailsForMovie(), CVideoDatabase::UpdateDetailsForTvShow(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
m_hasVideoExtras
bool CVideoInfoTag::m_hasVideoExtras {false} private
Referenced by Archive(), HasVideoExtras(), Merge(), Reset(), Save(), Serialize(), and SetHasVideoExtras().
m_hasVideoVersions
bool CVideoInfoTag::m_hasVideoVersions {false} private
Referenced by Archive(), HasVideoVersions(), Merge(), Reset(), Save(), Serialize(), and SetHasVideoVersions().
m_iBookmarkId
int CVideoInfoTag::m_iBookmarkId
Referenced by Archive(), Merge(), and Reset().
m_iDbId
int CVideoInfoTag::m_iDbId
Referenced by CGUIDialogVideoInfo::AddItemsToTag(), CVideoDatabase::AddNewEpisode(), CVideoDatabase::AddNewMovie(), CVideoDatabase::AddNewMusicVideo(), KODI::VIDEO::CVideoInfoScanner::AddVideo(), CVideoDatabase::AddVideoAsset(), Archive(), CVideoDatabase::DeleteResumeBookMark(), CSaveFileState::DoWork(), CVideoDatabase::ExportToXML(), ContentUtils::GeneratePlayableTrailerItem(), CGUIDialogVideoManagerVersions::GetAllOtherMovies(), CVideoDatabase::GetBasicDetailsForEpisode(), XBMCAddon::xbmc::InfoTagVideo::getDbId(), CVideoDatabase::GetDefaultVideoVersion(), CVideoDatabase::GetDetailsForEpisode(), CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetDetailsForMusicVideo(), CVideoDatabase::GetDetailsForTvShow(), CGUIWindowVideoNav::GetDirectory(), JSONRPC::CVideoLibrary::GetEpisodeDetails(), JSONRPC::CVideoLibrary::GetMovieDetails(), CVideoDatabase::GetMoviesByWhere(), JSONRPC::CVideoLibrary::GetMovieSetDetails(), CGUIDialogVideoInfo::GetMoviesForSet(), CVideoDatabase::GetMusicVideoAlbumsNav(), JSONRPC::CVideoLibrary::GetMusicVideoDetails(), CVideoDatabase::GetSameVideoItems(), JSONRPC::CVideoLibrary::GetSeasonDetails(), CVideoDatabase::GetSeasonInfo(), CGUIDialogVideoInfo::GetSetForMovie(), CGUIDialogVideoManagerVersions::GetSimilarMovies(), JSONRPC::CVideoLibrary::GetTVShowDetails(), CVideoDatabase::GetVideoVersions(), CGUIDialogVideoInfo::LinkMovieToTvShow(), CVideoThumbLoader::LoadItemLookup(), Merge(), CGUIWindowVideoBase::OnItemInfo(), CGUIDialogVideoInfo::OnSearchItemFound(), UPNP::CUPnPServer::OnUpdateObject(), CGUIDialogVideoInfo::Play(), JSONRPC::CVideoLibrary::RefreshEpisode(), JSONRPC::CVideoLibrary::RefreshMovie(), JSONRPC::CVideoLibrary::RefreshMusicVideo(), JSONRPC::CVideoLibrary::RefreshTVShow(), CGUIDialogVideoInfo::RemoveItemsFromTag(), Reset(), anonymous_namespace{VideoDatabase.cpp}::RewriteVideoVersionURL(), Serialize(), XBMCAddon::xbmc::InfoTagVideo::setDbIdRaw(), CGUIDialogVideoManagerVersions::SetDefaultVideoVersion(), CVideoDatabase::SetDetailsForItem(), JSONRPC::CVideoLibrary::SetEpisodeDetails(), JSONRPC::CVideoLibrary::SetMovieDetails(), CGUIDialogVideoInfo::SetMovieSet(), JSONRPC::CVideoLibrary::SetMovieSetDetails(), JSONRPC::CVideoLibrary::SetMusicVideoDetails(), CVideoDatabase::SetPlayCount(), JSONRPC::CVideoLibrary::SetSeasonDetails(), JSONRPC::CVideoLibrary::SetTVShowDetails(), ToSortable(), and CVideoDatabase::UpdateFanart().
m_iEpisode
int CVideoInfoTag::m_iEpisode
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), Archive(), anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording(), PVR::CPVRRecording::CPVRRecording(), CNfoFile::Create(), CVideoDatabase::ExportToXML(), CVideoDatabase::GetDetailsForTvShow(), XBMCAddon::xbmc::InfoTagVideo::getEpisode(), CVideoDatabase::GetEpisodeInfo(), CGUIWindowVideoNav::GetFirstUnwatchedItemIndex(), CLabelFormatter::GetMaskContent(), CVideoTagLoaderNFO::Load(), Merge(), KODI::VIDEO::CVideoInfoScanner::OnProcessSeriesFolder(), PVR::CPVRRecording::operator==(), ParseItemBoxee(), ParseItemMRSS(), ParseItemZink(), ParseNative(), PVR::CPVRRecording::Reset(), Reset(), Save(), Serialize(), CVideoDatabase::SetDetailsForEpisode(), XBMCAddon::xbmc::InfoTagVideo::setEpisodeRaw(), ToSortable(), PVR::CPVRRecording::Update(), PVR::CPVRRecording::UpdatePath(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
m_iFileId
int CVideoInfoTag::m_iFileId
Referenced by CVideoDatabase::AddFile(), CVideoDatabase::AddNewEpisode(), CVideoDatabase::AddNewMovie(), CVideoDatabase::AddNewMusicVideo(), Archive(), CVideoDatabase::DeleteResumeBookMark(), CVideoDatabase::ExportToXML(), ContentUtils::GeneratePlayableTrailerItem(), CVideoDatabase::GetAndFillFileId(), CVideoDatabase::GetBasicDetailsForEpisode(), CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetDetailsForMusicVideo(), CVideoDatabase::GetFileId(), CVideoDatabase::GetFileInfo(), CVideoDatabase::GetStreamDetails(), CFileItem::IsSamePath(), CVideoThumbLoader::LoadItemCached(), Merge(), Reset(), Serialize(), and CVideoDatabase::UpdateFileDateAdded().
m_iIdRating
int CVideoInfoTag::m_iIdRating
Referenced by Merge(), Reset(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::UpdateDetailsForMovie(), and CVideoDatabase::UpdateDetailsForTvShow().
m_iIdSeason
int CVideoInfoTag::m_iIdSeason
Referenced by Archive(), CVideoDatabase::GetBasicDetailsForEpisode(), CGUIWindowVideoNav::GetDirectory(), CVideoDatabase::GetSeasonInfo(), Merge(), CGUIDialogVideoInfo::OnSearchItemFound(), Reset(), Serialize(), and CGUIWindowVideoBase::ShowInfo().
m_iIdShow
int CVideoInfoTag::m_iIdShow
Referenced by Archive(), CVideoDatabase::GetBasicDetailsForEpisode(), CVideoDatabase::GetDetailsForEpisode(), JSONRPC::CVideoLibrary::GetEpisodeDetails(), anonymous_namespace{VideoDatabase.cpp}::GetSeasonAvailableArt(), anonymous_namespace{VideoDatabase.cpp}::GetSeasonAvailableArtTypes(), JSONRPC::CVideoLibrary::GetSeasonDetails(), CVideoDatabase::GetSeasonInfo(), Merge(), CGUIWindowVideoBase::OnItemInfo(), CGUIDialogVideoInfo::Play(), JSONRPC::CVideoLibrary::RefreshEpisode(), Reset(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), Serialize(), CVideoDatabase::SetDetailsForItem(), and JSONRPC::CVideoLibrary::SetSeasonDetails().
m_iIdUniqueID
int CVideoInfoTag::m_iIdUniqueID
Referenced by Merge(), Reset(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMusicVideo(), CVideoDatabase::UpdateDetailsForMovie(), and CVideoDatabase::UpdateDetailsForTvShow().
m_isDefaultVideoVersion
bool CVideoInfoTag::m_isDefaultVideoVersion {false} private
Referenced by Archive(), IsDefaultVideoVersion(), Merge(), Reset(), Save(), Serialize(), and SetIsDefaultVideoVersion().
m_iSeason
int CVideoInfoTag::m_iSeason
Referenced by CVideoFileItemListModifier::AddQueuingFolder(), KODI::VIDEO::CVideoInfoScanner::AddVideo(), Archive(), anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording(), PVR::CPVRRecording::CPVRRecording(), CVideoDatabase::ExportToXML(), CVideoDatabase::GetDetailsForTvShow(), CGUIWindowVideoNav::GetDirectory(), JSONRPC::CVideoLibrary::GetEpisodeDetails(), CVideoDatabase::GetEpisodeInfo(), CVideoDatabase::GetEpisodesByWhere(), CGUIWindowVideoNav::GetFirstUnwatchedItemIndex(), CLabelFormatter::GetMaskContent(), XBMCAddon::xbmc::InfoTagVideo::getSeason(), CVideoDatabase::GetSeasonInfo(), Merge(), KODI::VIDEO::CVideoInfoScanner::OnProcessSeriesFolder(), CGUIDialogVideoInfo::OnSearchItemFound(), PVR::CPVRRecording::operator==(), ParseItemBoxee(), ParseItemMRSS(), ParseItemZink(), ParseNative(), CGUIDialogVideoInfo::Play(), PVR::CPVRRecording::Reset(), Reset(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), Save(), Serialize(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForSeason(), CFileItem::SetFromVideoInfoTag(), XBMCAddon::xbmc::InfoTagVideo::setSeasonRaw(), CGUIWindowVideoBase::ShowInfo(), ToSortable(), PVR::CPVRRecording::Update(), PVR::CPVRRecording::UpdatePath(), JSONRPC::CVideoLibrary::UpdateVideoTag(), and CVideoLibraryRefreshingJob::Work().
m_iSpecialSortEpisode
int CVideoInfoTag::m_iSpecialSortEpisode
Referenced by Archive(), CGUIWindowVideoNav::GetFirstUnwatchedItemIndex(), Merge(), ParseNative(), Reset(), Save(), Serialize(), XBMCAddon::xbmc::InfoTagVideo::setSortEpisodeRaw(), and ToSortable().
m_iSpecialSortSeason
int CVideoInfoTag::m_iSpecialSortSeason
Referenced by Archive(), CGUIWindowVideoNav::GetFirstUnwatchedItemIndex(), Merge(), ParseNative(), Reset(), Save(), Serialize(), XBMCAddon::xbmc::InfoTagVideo::setSortSeasonRaw(), and ToSortable().
m_iTop250
int CVideoInfoTag::m_iTop250
Referenced by Archive(), Merge(), ParseNative(), Reset(), Save(), Serialize(), XBMCAddon::xbmc::InfoTagVideo::setTop250Raw(), ToSortable(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
m_iTrack
int CVideoInfoTag::m_iTrack
Referenced by Archive(), CLabelFormatter::GetMaskContent(), XBMCAddon::xbmc::InfoTagVideo::getTrack(), Merge(), ParseNative(), Reset(), Save(), Serialize(), XBMCAddon::xbmc::InfoTagVideo::setTrackNumberRaw(), ToSortable(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
m_iUserRating
int CVideoInfoTag::m_iUserRating
Referenced by Archive(), CVideoDatabase::GetBasicDetailsForEpisode(), CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetDetailsForMusicVideo(), CVideoDatabase::GetDetailsForTvShow(), CLabelFormatter::GetMaskContent(), CVideoDatabase::GetSeasonInfo(), XBMCAddon::xbmc::InfoTagVideo::getUserRating(), Merge(), ParseNative(), Reset(), Save(), Serialize(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMusicVideo(), CVideoDatabase::SetDetailsForSeason(), SetUserrating(), XBMCAddon::xbmc::InfoTagVideo::setUserRatingRaw(), ToSortable(), CVideoDatabase::UpdateDetailsForMovie(), CVideoDatabase::UpdateDetailsForTvShow(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
m_lastPlayed
CDateTime CVideoInfoTag::m_lastPlayed
Referenced by CVideoDatabase::AddFile(), KODI::VIDEO::CVideoInfoScanner::AddVideo(), Archive(), CSaveFileState::DoWork(), CVideoDatabase::GetDetailsForEpisode(), CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetDetailsForMusicVideo(), CVideoDatabase::GetDetailsForTvShow(), CVideoDatabase::GetFileInfo(), XBMCAddon::xbmc::InfoTagVideo::getLastPlayed(), XBMCAddon::xbmc::InfoTagVideo::getLastPlayedAsW3C(), CLabelFormatter::GetMaskContent(), GroupUtils::Group(), Merge(), ParseNative(), Reset(), Save(), Serialize(), JSONRPC::CVideoLibrary::SetEpisodeDetails(), JSONRPC::CFileOperations::SetFileDetails(), XBMCAddon::xbmc::InfoTagVideo::setLastPlayedRaw(), JSONRPC::CVideoLibrary::SetMovieDetails(), JSONRPC::CVideoLibrary::SetMusicVideoDetails(), ToSortable(), UPNP::CMediaBrowser::UpdateItem(), PVR::CPVRRecording::UpdateMetadata(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
m_namedSeasons
std::map<int, std::string> CVideoInfoTag::m_namedSeasons
Referenced by XBMCAddon::xbmc::InfoTagVideo::addSeasonRaw(), Archive(), CVideoDatabase::ExportToXML(), Merge(), ParseNative(), Reset(), Save(), SetNamedSeasons(), and CVideoDatabase::UpdateDetailsForTvShow().
m_parentPathID
int CVideoInfoTag::m_parentPathID
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), Archive(), CVideoDatabase::GetDetailsForTvShow(), Merge(), and Reset().
m_parsedDetails
int CVideoInfoTag::m_parsedDetails
Referenced by CVideoDatabase::GetDetailsForEpisode(), CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetDetailsForMusicVideo(), CVideoDatabase::GetDetailsForTvShow(), Merge(), and Reset().
m_playCount
int CVideoInfoTag::m_playCount private
Referenced by Archive(), GetPlayCount(), IncrementPlayCount(), IsPlayCountSet(), ParseNative(), Reset(), ResetPlayCount(), and SetPlayCount().
m_premiered
CDateTime CVideoInfoTag::m_premiered
Referenced by Archive(), CVideoDatabase::GetDetailsForTvShow(), GetPremiered(), GetYear(), PVR::CPVRRecording::GetYear(), HasYear(), PVR::CPVRRecording::HasYear(), Merge(), ParseNative(), Reset(), Save(), Serialize(), SetPremiered(), PVR::CPVRRecording::SetYear(), and ToSortable().
m_ratings
RatingMap CVideoInfoTag::m_ratings
Referenced by Archive(), CVideoDatabase::GetDetailsForEpisode(), CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetDetailsForTvShow(), GetRating(), Merge(), RemoveRating(), Reset(), Save(), Serialize(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), SetRating(), SetRating(), SetRatings(), SetVotes(), CVideoDatabase::UpdateDetailsForMovie(), and CVideoDatabase::UpdateDetailsForTvShow().
m_relevance
int CVideoInfoTag::m_relevance
Referenced by CLabelFormatter::GetMaskContent(), Merge(), Reset(), and ToSortable().
m_resumePoint
CBookmark CVideoInfoTag::m_resumePoint private
Referenced by Archive(), GetResumePoint(), ParseNative(), Reset(), Save(), Serialize(), SetResumePoint(), SetResumePoint(), and ToSortable().
m_set
SetInfo CVideoInfoTag::m_set
Assigned movie set.
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), Archive(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), CVideoDatabase::GetDetailsForMovie(), CGUIDialogVideoInfo::GetSetForMovie(), CVideoDatabase::ImportFromXML(), Merge(), Reset(), Save(), Serialize(), CVideoDatabase::SetDetailsForMovie(), CGUIDialogVideoInfo::SetMovie(), SetSet(), XBMCAddon::xbmc::InfoTagVideo::setSetIdRaw(), SetSetOverview(), ToSortable(), and CVideoDatabase::UpdateDetailsForMovie().
m_showLink
std::vector<std::string> CVideoInfoTag::m_showLink
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), Archive(), CVideoDatabase::GetDetailsForMovie(), Merge(), ParseNative(), Reset(), Save(), Serialize(), SetShowLink(), CVideoDatabase::UpdateDetailsForMovie(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
m_strAlbum
std::string CVideoInfoTag::m_strAlbum
Referenced by Archive(), XBMCAddon::xbmc::InfoTagVideo::getAlbum(), CLabelFormatter::GetMaskContent(), CVideoDatabase::GetMusicVideoAlbumsNav(), Merge(), Reset(), Save(), Serialize(), SetAlbum(), and ToSortable().
m_strDefaultRating
std::string CVideoInfoTag::m_strDefaultRating private
Referenced by Archive(), GetDefaultRating(), GetRating(), Merge(), ParseNative(), RemoveRating(), Reset(), Save(), Serialize(), SetRating(), SetRating(), SetRatings(), and SetVotes().
m_strDefaultUniqueID
std::string CVideoInfoTag::m_strDefaultUniqueID private
Referenced by Archive(), GetDefaultUniqueID(), GetUniqueID(), Merge(), ParseNative(), Reset(), Save(), SetUniqueID(), and SetUniqueIDs().
m_streamDetails
CStreamDetails CVideoInfoTag::m_streamDetails
Referenced by XBMCAddon::xbmc::InfoTagVideo::addStreamRaw(), KODI::VIDEO::CVideoInfoScanner::AddVideo(), CVideoDatabase::AddVideoAsset(), Archive(), CVideoThumbLoader::DetectAndAddMissingItemData(), CSaveFileState::DoWork(), XBMCAddon::xbmc::InfoTagVideo::finalizeStreamsRaw(), ContentUtils::GeneratePlayableTrailerItem(), GetDuration(), CDVDFileInfo::GetFileStreamDetails(), CPlayerSelectionRule::GetPlayers(), HasStreamDetails(), Merge(), CApplicationPlayerCallback::OnPlayerCloseFile(), ParseNative(), CDVDFileInfo::ProcessExternalSubtitles(), Reset(), Save(), Serialize(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMusicVideo(), ToSortable(), PVR::CPVRRecording::UpdateMetadata(), and JSONRPC::CVideoLibrary::UpdateResumePoint().
m_strEpisodeGuide
std::string CVideoInfoTag::m_strEpisodeGuide
Referenced by Archive(), KODI::VIDEO::CVideoInfoScanner::OnProcessSeriesFolder(), ParseNative(), Save(), Serialize(), and SetEpisodeGuide().
m_strFile
std::string CVideoInfoTag::m_strFile
Referenced by Archive(), XBMCAddon::xbmc::InfoTagVideo::getFile(), IsEmpty(), Merge(), Reset(), Save(), Serialize(), SetFile(), and ToSortable().
m_strFileNameAndPath
std::string CVideoInfoTag::m_strFileNameAndPath
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), Archive(), AudioClassifyTest::AudioClassifyTest(), CFileItem::CFileItem(), PVR::CPVRRecording::DeleteMetadata(), CVideoDatabase::DeleteResumeBookMark(), CSaveFileState::DoWork(), CFileItem::Exists(), CVideoDatabase::ExportToXML(), CVideoDatabase::GetDetailsForEpisode(), CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetDetailsForMusicVideo(), CVideoThumbLoader::GetEmbeddedThumbURL(), CVideoDatabase::GetEpisodesByWhere(), CVideoDatabase::GetFileInfo(), XBMCAddon::xbmc::InfoTagVideo::getFilenameAndPath(), CDVDFileInfo::GetFileStreamDetails(), KODI::ART::GetLocalFanart(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideosByWhere(), anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), GetPath(), CVideoDatabase::GetVideoVersions(), KODI::VIDEO::IsDiscStub(), CFileItem::IsSamePath(), Merge(), CGUIWindowVideoNav::OnMessage(), CXBMCApp::onNewIntent(), PVR::CPVRRecording::operator==(), CExecString::Parse(), CApplication::PlayFile(), PVR::CPVRRecording::Reset(), Reset(), Save(), Serialize(), SetFileNameAndPath(), CFileItem::SetFromVideoInfoTag(), KODI::VIDEO::anonymous_namespace{VideoGeneratedImageFileLoader.cpp}::SetupRarOptions(), StubDefinition::StubDefinition(), TEST_P(), PVR::CPVRRecording::UpdateMetadata(), PVR::CPVRRecording::UpdatePath(), JSONRPC::CVideoLibrary::UpdateResumePoint(), and VideoClassifyTest::VideoClassifyTest().
m_strMPAARating
std::string CVideoInfoTag::m_strMPAARating
Referenced by Archive(), CVideoDatabase::GetDetailsForEpisode(), CLabelFormatter::GetMaskContent(), Merge(), ParseItemMRSS(), Reset(), Save(), Serialize(), SetMPAARating(), and ToSortable().
m_strOriginalTitle
std::string CVideoInfoTag::m_strOriginalTitle
Referenced by Archive(), XBMCAddon::xbmc::InfoTagVideo::getOriginalTitle(), Merge(), Reset(), Save(), Serialize(), SetOriginalTitle(), and ToSortable().
m_strPath
std::string CVideoInfoTag::m_strPath
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), Archive(), CVideoDatabase::ExportToXML(), CVideoDatabase::GetDetailsForEpisode(), CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetDetailsForMusicVideo(), CVideoDatabase::GetDetailsForTvShow(), CVideoDatabase::GetEpisodesByWhere(), CVideoDatabase::GetFileInfo(), KODI::ART::GetLocalFanart(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideosByWhere(), XBMCAddon::xbmc::InfoTagVideo::getPath(), GetPath(), CGUIWindowVideoBase::GetScraperForItem(), KODI::VIDEO::CVideoInfoScanner::GetSeasonThumbs(), CVideoDatabase::GetTvShowsByWhere(), GroupUtils::Group(), CVideoDatabase::ImportFromXML(), KODI::VIDEO::IsDiscStub(), IsEmpty(), Merge(), CGUIWindowVideoBase::OnItemInfo(), Reset(), Save(), Serialize(), CFileItem::SetFromVideoInfoTag(), SetPath(), and StubDefinition::StubDefinition().
m_strPictureURL
CScraperUrl CVideoInfoTag::m_strPictureURL
Referenced by XBMCAddon::xbmc::InfoTagVideo::addAvailableArtworkRaw(), Archive(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), anonymous_namespace{VideoDatabase.cpp}::GetMovieSetAvailableArt(), anonymous_namespace{VideoDatabase.cpp}::GetMovieSetAvailableArtTypes(), XBMCAddon::xbmc::InfoTagVideo::getPictureURL(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkMovieSetHandler::GetRemoteArt(), anonymous_namespace{VideoDatabase.cpp}::GetSeasonAvailableArt(), anonymous_namespace{VideoDatabase.cpp}::GetSeasonAvailableArtTypes(), KODI::VIDEO::CVideoInfoScanner::GetSeasonThumbs(), CVideoDatabase::GetVideoVersions(), Merge(), ParseNative(), Reset(), Save(), and SetPictureURL().
m_strPlot
std::string CVideoInfoTag::m_strPlot
Referenced by Archive(), PVR::CPVRRecording::CPVRRecording(), CGUIWindowVideoNav::GetDirectory(), XBMCAddon::xbmc::InfoTagVideo::getPlot(), GroupUtils::Group(), Merge(), PVR::CPVRRecording::operator==(), ParseItem(), ParseItemItunes(), Reset(), Save(), Serialize(), CVideoDatabase::SetDetailsForMovieSet(), SetPlot(), ToSortable(), and PVR::CPVRRecording::Update().
m_strPlotOutline
std::string CVideoInfoTag::m_strPlotOutline
Referenced by Archive(), PVR::CPVRRecording::CPVRRecording(), XBMCAddon::xbmc::InfoTagVideo::getPlotOutline(), Merge(), PVR::CPVRRecording::operator==(), ParseItem(), ParseItemItunes(), Reset(), Save(), Serialize(), SetPlotOutline(), ToSortable(), and PVR::CPVRRecording::Update().
m_strProductionCode
std::string CVideoInfoTag::m_strProductionCode
Referenced by Archive(), CLabelFormatter::GetMaskContent(), Merge(), Reset(), Save(), Serialize(), SetProductionCode(), and ToSortable().
m_strShowTitle
std::string CVideoInfoTag::m_strShowTitle
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), Archive(), PVR::CPVRRecording::CPVRRecording(), CGUIDialogVideoInfo::DoSearch(), PVR::CPVRRecording::EpisodeName(), CVideoDatabase::GetDetailsForEpisode(), CVideoDatabase::GetDetailsForTvShow(), CGUIWindowVideoNav::GetDirectory(), CLabelFormatter::GetMaskContent(), XBMCAddon::xbmc::InfoTagVideo::getTVShowTitle(), Merge(), PVR::CPVRRecording::operator==(), ParseItemBoxee(), ParseItemMRSS(), Reset(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), Save(), Serialize(), SetShowTitle(), ToSortable(), PVR::CPVRRecording::Update(), and PVR::CPVRRecording::UpdatePath().
m_strSortTitle
std::string CVideoInfoTag::m_strSortTitle
Referenced by Archive(), CVideoDatabase::GetSeasonInfo(), Merge(), Reset(), Save(), Serialize(), CVideoDatabase::SetDetailsForSeason(), SetSortTitle(), ToSortable(), and CVideoDatabase::UpdateDetailsForTvShow().
m_strStatus
std::string CVideoInfoTag::m_strStatus
Referenced by Archive(), Merge(), Reset(), Save(), Serialize(), SetStatus(), and ToSortable().
m_strTagLine
std::string CVideoInfoTag::m_strTagLine
Referenced by Archive(), XBMCAddon::xbmc::InfoTagVideo::getTagLine(), Merge(), ParseItemVoddler(), Reset(), Save(), Serialize(), SetTagLine(), and ToSortable().
m_strTitle
std::string CVideoInfoTag::m_strTitle
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), Archive(), UPNP::BuildObject(), PVR::CPVRRecording::CPVRRecording(), CGUIDialogVideoInfo::DoSearch(), CVideoDatabase::ExportToXML(), ContentUtils::GeneratePlayableTrailerItem(), CVideoDatabase::GetDefaultVideoVersion(), KODI::VIDEO::CVideoInfoScanner::GetDetails(), CVideoDatabase::GetDetailsForTvShow(), CLabelFormatter::GetMaskContent(), CVideoDatabase::GetMatchingTvShow(), CFileItem::GetMovieName(), CVideoDatabase::GetSeasonInfo(), XBMCAddon::xbmc::InfoTagVideo::getTitle(), GetTitle(), CVideoDatabase::GetVideoVersions(), GroupUtils::Group(), IsEmpty(), Merge(), KODI::VIDEO::CVideoInfoScanner::OnProcessSeriesFolder(), PVR::CPVRRecording::operator==(), PVR::CPVRRecording::Rename(), Reset(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), Save(), Serialize(), CVideoDatabase::SetDetailsForMovieSet(), CFileItem::SetFromVideoInfoTag(), SetTitle(), ToSortable(), PVR::CPVRRecording::Update(), CVideoDatabase::UpdateDetailsForMovie(), and PVR::CPVRRecording::UpdatePath().
m_strTrailer
std::string CVideoInfoTag::m_strTrailer
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), Archive(), CVideoDatabase::ExportToXML(), ContentUtils::GeneratePlayableTrailerItem(), XBMCAddon::xbmc::InfoTagVideo::getTrailer(), Merge(), ParseItemVoddler(), Reset(), Save(), Serialize(), SetTrailer(), and ToSortable().
m_studio
std::vector<std::string> CVideoInfoTag::m_studio
Referenced by Archive(), CVideoDatabase::GetDetailsForEpisode(), CLabelFormatter::GetMaskContent(), Merge(), ParseItemMRSS(), ParseNative(), Reset(), Save(), Serialize(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMusicVideo(), SetStudio(), ToSortable(), CVideoDatabase::UpdateDetailsForMovie(), CVideoDatabase::UpdateDetailsForTvShow(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
m_tags
std::vector<std::string> CVideoInfoTag::m_tags
Referenced by Archive(), CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetDetailsForMusicVideo(), CVideoDatabase::GetDetailsForTvShow(), Merge(), ParseNative(), Reset(), Save(), Serialize(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMusicVideo(), SetTags(), ToSortable(), CVideoDatabase::UpdateDetailsForMovie(), CVideoDatabase::UpdateDetailsForTvShow(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
m_type
MediaType CVideoInfoTag::m_type
Referenced by CVideoFileItemListModifier::AddQueuingFolder(), KODI::VIDEO::CVideoInfoScanner::AddVideo(), CVideoInfoTag::CAssetInfo::Archive(), Archive(), CGUIDialogVideoInfo::DoSearch(), CSaveFileState::DoWork(), CVideoDatabase::ExportToXML(), CVideoDatabase::GetBasicDetailsForEpisode(), CVideoDatabase::GetDefaultVideoVersion(), CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetDetailsForMusicVideo(), CVideoDatabase::GetDetailsForTvShow(), CGUIWindowVideoNav::GetDirectory(), XBMCAddon::xbmc::InfoTagVideo::getMediaType(), CVideoDatabase::GetMusicVideoAlbumsNav(), ContentUtils::GetPreferredArtImage(), CVideoDatabase::GetSameVideoItems(), CVideoDatabase::GetSeasonInfo(), CFileItem::GetThumbHideIfUnwatched(), CVideoDatabase::GetVideoVersions(), KODI::UTILS::GUILIB::CGUIContentUtils::HasInfoForItem(), anonymous_namespace{ContentUtils.cpp}::HasPreferredArtType(), KODI::VIDEO::UTILS::IsAutoPlayNextItem(), CONTEXTMENU::CVideoInfo::IsVisible(), CVideoThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemLookup(), CVideoInfoTag::CAssetInfo::Merge(), Merge(), CGUIWindowVideoBase::OnItemInfo(), CGUIDialogVideoInfo::OnSearchItemFound(), UPNP::CUPnPServer::OnUpdateObject(), CVideoInfoTag::CAssetInfo::ParseNative(), CGUIDialogVideoInfo::Play(), CGUIDialogVideoManagerVersions::ProcessVideoVersion(), Reset(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), CVideoInfoTag::CAssetInfo::Save(), CVideoInfoTag::CAssetInfo::Serialize(), Serialize(), CVideoDatabase::SetDetailsForItem(), JSONRPC::CVideoLibrary::SetEpisodeDetails(), XBMCAddon::xbmc::InfoTagVideo::setMediaTypeRaw(), CGUIDialogVideoInfo::SetMovie(), JSONRPC::CVideoLibrary::SetMovieDetails(), JSONRPC::CVideoLibrary::SetMovieSetDetails(), JSONRPC::CVideoLibrary::SetMusicVideoDetails(), JSONRPC::CVideoLibrary::SetSeasonDetails(), JSONRPC::CVideoLibrary::SetTVShowDetails(), CVideoInfoTag::CAssetInfo::SetType(), CGUIWindowVideoBase::ShowInfo(), ToSortable(), and CVideoLibraryRefreshingJob::Work().
m_uniqueIDs
std::map<std::string, std::string> CVideoInfoTag::m_uniqueIDs private
Referenced by Archive(), GetUniqueID(), GetUniqueIDs(), HasUniqueID(), Merge(), RemoveUniqueID(), Reset(), Save(), Serialize(), SetUniqueID(), and SetUniqueIDs().
m_updateSetOverview
bool CVideoInfoTag::m_updateSetOverview {true} private
Referenced by GetUpdateSetOverview(), ParseNative(), and Reset().
m_writingCredits
std::vector<std::string> CVideoInfoTag::m_writingCredits
Referenced by Archive(), XBMCAddon::xbmc::InfoTagVideo::getWriters(), XBMCAddon::xbmc::InfoTagVideo::getWritingCredits(), Merge(), ParseItemItunes(), ParseItemMRSS(), ParseNative(), Reset(), Save(), Serialize(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), SetWritingCredits(), ToSortable(), CVideoDatabase::UpdateDetailsForMovie(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
m_year
int CVideoInfoTag::m_year
Referenced by GetYear(), HasYear(), Merge(), Reset(), and SetYear().
PLAYCOUNT_NOT_SET
const int CVideoInfoTag::PLAYCOUNT_NOT_SET = -1 static private
Referenced by IsPlayCountSet(), Reset(), and ResetPlayCount().
The documentation for this class was generated from the following files:
VideoInfoTag.h
VideoInfoTag.cpp