Kodi Documentation: PERIPHERALS::CAndroidJoystickTranslator Class Reference
PERIPHERALS::CAndroidJoystickTranslator Class Reference
#include <AndroidJoystickTranslator.h>
Static Public Member Functions
static const char * TranslateAxis (int axisId)
Translate an axis ID to an Android enum suitable for logging.
static const char * TranslateKeyCode (int keyCode)
Translate a key code to an Android enum suitable for logging.
static const char * TranslateJoystickButton (int buttonKeycode)
Translate a button key code to a feature on the default controller.
Member Function Documentation
TranslateAxis()
const char * CAndroidJoystickTranslator::TranslateAxis (int axisId) static
Translate an axis ID to an Android enum suitable for logging.
Parameters
axisId The axis ID given in <android/input.h>
Returns
The translated enum label, or "unknown" if unknown
Referenced by PERIPHERALS::CAndroidJoystickState::Initialize(), and PERIPHERALS::CPeripheralBusAndroid::LogInputDevice().
TranslateJoystickButton()
const char * CAndroidJoystickTranslator::TranslateJoystickButton (int buttonKeycode) static
Translate a button key code to a feature on the default controller.
Parameters
buttonKeycode The key code given in <android/keycodes.h>
Returns
The translated feature, or "" if unknown
References KODI::GAME::CDefaultController::FEATURE_A, KODI::GAME::CDefaultController::FEATURE_B, KODI::GAME::CDefaultController::FEATURE_BACK, KODI::GAME::CDefaultController::FEATURE_DOWN, KODI::GAME::CDefaultController::FEATURE_GUIDE, KODI::GAME::CDefaultController::FEATURE_LEFT, KODI::GAME::CDefaultController::FEATURE_LEFT_BUMPER, KODI::GAME::CDefaultController::FEATURE_LEFT_THUMB, KODI::GAME::CDefaultController::FEATURE_LEFT_TRIGGER, KODI::GAME::CDefaultController::FEATURE_RIGHT, KODI::GAME::CDefaultController::FEATURE_RIGHT_BUMPER, KODI::GAME::CDefaultController::FEATURE_RIGHT_THUMB, KODI::GAME::CDefaultController::FEATURE_RIGHT_TRIGGER, KODI::GAME::CDefaultController::FEATURE_START, KODI::GAME::CDefaultController::FEATURE_UP, KODI::GAME::CDefaultController::FEATURE_X, and KODI::GAME::CDefaultController::FEATURE_Y.
Referenced by PERIPHERALS::CAndroidJoystickState::MapButton().
TranslateKeyCode()
const char * CAndroidJoystickTranslator::TranslateKeyCode (int keyCode) static
Translate a key code to an Android enum suitable for logging.
Parameters
keyCode The key code given in <android/keycodes.h>
Returns
The translated enum label, or "unknown" if unknown
Referenced by PERIPHERALS::CAndroidJoystickState::Initialize(), PERIPHERALS::CPeripheralBusAndroid::LogInputDevice(), CAndroidKey::onKeyboardEvent(), and PERIPHERALS::CAndroidJoystickState::ProcessEvent().
The documentation for this class was generated from the following files:
AndroidJoystickTranslator.h
AndroidJoystickTranslator.cpp