Kodi Documentation: VAAPI::CDecoder Class Reference
VAAPI::CDecoder Class Reference
#include <VAAPI.h>
Classes
struct AVBufferRefDeleter
Public Member Functions
CDecoder (CProcessInfo &processInfo)
~CDecoder () override
bool Open (AVCodecContext *avctx, AVCodecContext *mainctx, const enum AVPixelFormat) override
CDVDVideoCodec::VCReturn Decode (AVCodecContext *avctx, AVFrame *frame) override
bool GetPicture (AVCodecContext *avctx, VideoPicture *picture) override
void Reset () override
virtual void Close ()
long Release () override
bool CanSkipDeint () override
unsigned GetAllowedReferences () override
CDVDVideoCodec::VCReturn Check (AVCodecContext *avctx) override
const std::string Name () override
void SetCodecControl (int flags) override
void FFReleaseBuffer (uint8_t *data)
Public Member Functions inherited from IHardwareDecoder
IHardwareDecoder ()=default
~IHardwareDecoder () override=default
Public Member Functions inherited from IDVDResourceCounted< IHardwareDecoder >
IDVDResourceCounted ()
IDVDResourceCounted (const IDVDResourceCounted &)=delete
virtual ~IDVDResourceCounted ()=default
IDVDResourceCounted & operator= (const IDVDResourceCounted &)=delete
virtual IHardwareDecoder * Acquire ()
Static Public Member Functions
static int FFGetBuffer (AVCodecContext *avctx, AVFrame *pic, int flags)
static IHardwareDecoder * Create (CDVDStreamInfo &hint, CProcessInfo &processInfo, AVPixelFormat fmt)
static void Register (IVaapiWinSystem *winSystem, bool deepColor)
Static Public Attributes
static IVaapiWinSystem * m_pWinSystem = nullptr
Protected Types
enum EDisplayState { VAAPI_OPEN , VAAPI_RESET , VAAPI_LOST , VAAPI_ERROR }
Protected Member Functions
void SetWidthHeight (int width, int height)
bool ConfigVAAPI ()
bool CheckStatus (VAStatus vdp_st, int line)
void FiniVAAPIOutput ()
void ReturnRenderPicture (CVaapiRenderPicture *renderPic)
long ReleasePicReference ()
bool CheckSuccess (VAStatus status, const std::string &function)
Protected Attributes
enum VAAPI::CDecoder::EDisplayState m_DisplayState
CCriticalSection m_DecoderSection
CEvent m_DisplayEvent
int m_ErrorCount
bool m_vaapiConfigured
CVaapiConfig m_vaapiConfig
CVideoSurfaces m_videoSurfaces
int m_getBufferError
COutput m_vaapiOutput
CVaapiBufferStats m_bufferStats
CEvent m_inMsgEvent
CVaapiRenderPicture * m_presentPicture = nullptr
int m_codecControl
CProcessInfo & m_processInfo
Static Protected Attributes
static bool m_capGeneral = false
static bool m_capDeepColor = false
Private Attributes
std::unique_ptr< AVBufferRef, AVBufferRefDeleter > m_deviceRef
Friends
class CVaapiBufferPool
Additional Inherited Members
Public Attributes inherited from IDVDResourceCounted< IHardwareDecoder >
std::atomic< long > m_refs
Member Enumeration Documentation
EDisplayState
enum VAAPI::CDecoder::EDisplayState protected
Enumerator
VAAPI_OPEN
VAAPI_RESET
VAAPI_LOST
VAAPI_ERROR
Constructor & Destructor Documentation
CDecoder()
CDecoder::CDecoder (CProcessInfo & processInfo) explicit
References VAAPI::CVaapiConfig::configId, VAAPI::CVaapiConfig::context, m_DisplayState, m_getBufferError, m_processInfo, m_vaapiConfig, m_vaapiConfigured, m_videoSurfaces, VAAPI::CVaapiConfig::processInfo, VAAPI_OPEN, and VAAPI::CVaapiConfig::videoSurfaces.
~CDecoder()
CDecoder::~CDecoder () override
References Close().
Member Function Documentation
CanSkipDeint()
bool CDecoder::CanSkipDeint () override virtual
Reimplemented from IHardwareDecoder.
References VAAPI::CVaapiBufferStats::CanSkipDeint(), and m_bufferStats.
Check()
CDVDVideoCodec::VCReturn CDecoder::Check (AVCodecContext * avctx) override virtual
Implements IHardwareDecoder.
References ConfigVAAPI(), VAAPI::CVaapiConfig::context, VAAPI::CVAAPIContext::EnsureContext(), FiniVAAPIOutput(), CLog::Log(), LOGDEBUG, LOGERROR, LOGVIDEO, m_DecoderSection, m_DisplayEvent, m_DisplayState, m_getBufferError, m_vaapiConfig, VAAPI::CVAAPIContext::Release(), KODI::TIME::Sleep(), VAAPI_ERROR, VAAPI_LOST, VAAPI_OPEN, VAAPI_RESET, CDVDVideoCodec::VC_ERROR, CDVDVideoCodec::VC_FLUSHED, CDVDVideoCodec::VC_NOBUFFER, CDVDVideoCodec::VC_NONE, and CEvent::Wait().
Referenced by Decode().
CheckStatus()
bool VAAPI::CDecoder::CheckStatus (VAStatus vdp_st, int line) protected
CheckSuccess()
bool CDecoder::CheckSuccess (VAStatus status, const std::string & function) protected
References CLog::Log(), LOGERROR, m_DisplayState, m_ErrorCount, VAAPI_ERROR, and VAAPI_OPEN.
Referenced by ConfigVAAPI(), FiniVAAPIOutput(), and Release().
Close()
void CDecoder::Close () virtual
References VAAPI::CVaapiConfig::context, FiniVAAPIOutput(), CLog::Log(), LOGINFO, m_DecoderSection, m_deviceRef, m_vaapiConfig, and VAAPI::CVAAPIContext::Release().
Referenced by ~CDecoder().
ConfigVAAPI()
bool CDecoder::ConfigVAAPI () protected
References VAAPI::COutputControlProtocol::ACC, VAAPI::CVideoSurfaces::AddSurface(), VAAPI::CVaapiConfig::attrib, VAAPI::CVaapiConfig::bitDepth, CheckSuccess(), VAAPI::CVaapiConfig::configId, VAAPI::CVaapiConfig::context, VAAPI::CVAAPIContext::CreateConfig(), VAAPI::COutput::Dispose(), VAAPI::CVaapiConfig::dpy, VAAPI::CVAAPIContext::GetAttrib(), VAAPI::CVAAPIContext::GetDisplay(), CServiceBroker::GetWinSystem(), VAAPI::COutputControlProtocol::INIT, CLog::Log(), LOGERROR, m_bufferStats, VAAPI::COutput::m_controlPort, m_ErrorCount, m_inMsgEvent, m_vaapiConfig, m_vaapiConfigured, m_vaapiOutput, m_videoSurfaces, VAAPI::CVaapiConfig::maxReferences, VAAPI::CVaapiConfig::profile, Actor::Message::Release(), VAAPI::CVaapiBufferStats::Reset(), CEvent::Reset(), Actor::Protocol::SendOutMessageSync(), Actor::Message::signal, VAAPI::COutput::Start(), VAAPI::CVaapiConfig::stats, success, VAAPI::CVaapiConfig::surfaceHeight, and VAAPI::CVaapiConfig::surfaceWidth.
Referenced by Check(), and Open().
Create()
IHardwareDecoder * CDecoder::Create (CDVDStreamInfo & hint, CProcessInfo & processInfo, AVPixelFormat fmt) static
References CServiceBroker::GetSettingsComponent(), and SETTING_VIDEOPLAYER_USEVAAPI.
Referenced by Register().
Decode()
CDVDVideoCodec::VCReturn CDecoder::Decode (AVCodecContext * avctx, AVFrame * frame) override virtual
Implements IHardwareDecoder.
References Check(), Actor::Message::data, VAAPI::CVaapiBufferStats::DecRender(), DVD_CODEC_CTRL_DRAIN, DVD_CODEC_CTRL_HURRY, DVD_CODEC_CTRL_NO_POSTPROC, VAAPI::CVaapiDecodedPicture::DVDPic, VAAPI::COutputControlProtocol::ERROR, VAAPI::CVaapiBufferStats::Get(), VAAPI::CVideoSurfaces::HasFree(), VideoPicture::iFlags, VAAPI::CVaapiBufferStats::IncDecoded(), VAAPI::CVideoSurfaces::IsValid(), CLog::Log(), LOGERROR, LOGWARNING, m_bufferStats, m_codecControl, VAAPI::COutput::m_controlPort, VAAPI::COutput::m_dataPort, m_DecoderSection, m_DisplayState, m_inMsgEvent, m_presentPicture, m_vaapiConfigured, m_vaapiOutput, m_videoSurfaces, VAAPI::CVideoSurfaces::MarkRender(), VAAPI::COutputDataProtocol::NEWFRAME, VAAPI::COutputDataProtocol::PICTURE, Actor::Protocol::ReceiveInMessage(), CVideoBuffer::Release(), Actor::Message::Release(), Actor::Protocol::SendOutMessage(), VAAPI::CVaapiBufferStats::SetParams(), Actor::Message::signal, VAAPI::COutputControlProtocol::STATS, VAAPI_ERROR, CDVDVideoCodec::VC_BUFFER, CDVDVideoCodec::VC_EOF, CDVDVideoCodec::VC_ERROR, CDVDVideoCodec::VC_NOBUFFER, CDVDVideoCodec::VC_NONE, CDVDVideoCodec::VC_PICTURE, VAAPI::CVaapiDecodedPicture::videoSurface, and CEvent::Wait().
FFGetBuffer()
int CDecoder::FFGetBuffer (AVCodecContext * avctx, AVFrame * pic, int flags) static
References IDVDResourceCounted< T >::Acquire(), VAAPI::CVAAPIContext::FFReleaseBuffer(), VAAPI::CVaapiBufferStats::Get(), VAAPI::CVideoSurfaces::GetFree(), ICallbackHWAccel::GetHWAccel(), CLog::Log(), LOGERROR, LOGWARNING, m_bufferStats, m_DecoderSection, m_DisplayState, m_getBufferError, m_videoSurfaces, and VAAPI_OPEN.
Referenced by Open().
FFReleaseBuffer()
void CDecoder::FFReleaseBuffer (uint8_t * data)
References VAAPI::CVideoSurfaces::ClearReference(), data(), m_DecoderSection, m_videoSurfaces, and IDVDResourceCounted< IHardwareDecoder >::Release().
Referenced by VAAPI::CVAAPIContext::FFReleaseBuffer().
FiniVAAPIOutput()
void CDecoder::FiniVAAPIOutput () protected
References CheckSuccess(), VAAPI::CVaapiConfig::configId, VAAPI::COutput::Dispose(), VAAPI::CVaapiConfig::dpy, CLog::Log(), LOGDEBUG, LOGVIDEO, m_vaapiConfig, m_vaapiConfigured, m_vaapiOutput, m_videoSurfaces, VAAPI::CVideoSurfaces::RemoveNext(), VAAPI::CVideoSurfaces::Reset(), and VAAPI::CVideoSurfaces::Size().
Referenced by Check(), and Close().
GetAllowedReferences()
unsigned VAAPI::CDecoder::GetAllowedReferences () inline override virtual
Reimplemented from IHardwareDecoder.
GetPicture()
bool CDecoder::GetPicture (AVCodecContext * avctx, VideoPicture * picture) override virtual
Implements IHardwareDecoder.
References VAAPI::CVaapiRenderPicture::DVDPic, m_DecoderSection, m_DisplayState, m_presentPicture, CVideoBuffer::Release(), VideoPicture::SetParams(), VAAPI_OPEN, and VideoPicture::videoBuffer.
Name()
const std::string VAAPI::CDecoder::Name () inline override virtual
Implements IHardwareDecoder.
Open()
bool CDecoder::Open (AVCodecContext * avctx, AVCodecContext * mainctx, const enum AVPixelFormat fmt) override virtual
Implements IHardwareDecoder.
References VAAPI::CVaapiConfig::aspect, VAAPI::CVaapiConfig::attrib, VAAPI::CVaapiConfig::bitDepth, ConfigVAAPI(), VAAPI::CVaapiConfig::context, VAAPI::CVaapiConfig::dpy, VAAPI::CVaapiConfig::driverIsMesa, VAAPI::CVAAPIContext::EnsureContext(), FFGetBuffer(), VAAPI::CVideoSurfaces::GetAtIndex(), VAAPI::CVAAPIContext::GetAttrib(), VAAPI::CVAAPIContext::GetDisplay(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGDEBUG, LOGERROR, LOGVIDEO, LOGWARNING, m_capDeepColor, m_capGeneral, m_deviceRef, m_DisplayState, m_getBufferError, m_presentPicture, m_vaapiConfig, m_vaapiConfigured, m_videoSurfaces, VAAPI::CVaapiConfig::maxReferences, VAAPI::CVaapiConfig::outHeight, VAAPI::CVaapiConfig::outWidth, VAAPI::CVaapiConfig::profile, SETTING_VIDEOPLAYER_USEVAAPIAV1, SETTING_VIDEOPLAYER_USEVAAPIAVC, SETTING_VIDEOPLAYER_USEVAAPIHEVC, SETTING_VIDEOPLAYER_USEVAAPIMPEG2, SETTING_VIDEOPLAYER_USEVAAPIMPEG4, SETTING_VIDEOPLAYER_USEVAAPIVC1, SETTING_VIDEOPLAYER_USEVAAPIVP8, SETTING_VIDEOPLAYER_USEVAAPIVP9, VAAPI::CVideoSurfaces::Size(), VAAPI::CVAAPIContext::SupportsProfile(), VAAPI::CVaapiConfig::surfaceHeight, VAAPI::CVaapiConfig::surfaceWidth, VAAPI_OPEN, VAAPI::CVaapiConfig::vidHeight, and VAAPI::CVaapiConfig::vidWidth.
Register()
void CDecoder::Register (IVaapiWinSystem * winSystem, bool deepColor) static
References VAAPI::CVaapiConfig::context, Create(), VAAPI::CVAAPIContext::EnsureContext(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGERROR, m_capDeepColor, m_capGeneral, m_pWinSystem, CDVDFactoryCodec::RegisterHWAccel(), VAAPI::CVAAPIContext::Release(), SETTING_VIDEOPLAYER_PREFERVAAPIRENDER, SETTING_VIDEOPLAYER_USEVAAPI, SETTING_VIDEOPLAYER_USEVAAPIAV1, SETTING_VIDEOPLAYER_USEVAAPIAVC, SETTING_VIDEOPLAYER_USEVAAPIHEVC, SETTING_VIDEOPLAYER_USEVAAPIMPEG2, SETTING_VIDEOPLAYER_USEVAAPIMPEG4, SETTING_VIDEOPLAYER_USEVAAPIVC1, SETTING_VIDEOPLAYER_USEVAAPIVP8, and SETTING_VIDEOPLAYER_USEVAAPIVP9.
Release()
long CDecoder::Release () override virtual
Reimplemented from IDVDResourceCounted< IHardwareDecoder >.
References VAAPI::COutputControlProtocol::ACC, CheckSuccess(), VAAPI::CVaapiConfig::dpy, CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, LOGERROR, LOGVIDEO, VAAPI::COutput::m_controlPort, m_DecoderSection, m_DisplayState, m_presentPicture, m_vaapiConfig, m_vaapiConfigured, m_vaapiOutput, m_videoSurfaces, VAAPI::COutputControlProtocol::PRECLEANUP, CVideoBuffer::Release(), IDVDResourceCounted< IHardwareDecoder >::Release(), Actor::Message::Release(), VAAPI::CVideoSurfaces::RemoveNext(), Actor::Protocol::SendOutMessageSync(), Actor::Message::signal, success, and VAAPI_ERROR.
ReleasePicReference()
long CDecoder::ReleasePicReference () protected
References IDVDResourceCounted< IHardwareDecoder >::Release().
Referenced by VAAPI::CVaapiBufferPool::Return().
Reset()
void CDecoder::Reset () override virtual
Reimplemented from IHardwareDecoder.
References VAAPI::COutputControlProtocol::ACC, VAAPI::COutputControlProtocol::FLUSH, CLog::Log(), LOGERROR, m_bufferStats, VAAPI::COutput::m_controlPort, m_DecoderSection, m_DisplayState, m_getBufferError, m_presentPicture, m_vaapiConfigured, m_vaapiOutput, CVideoBuffer::Release(), Actor::Message::Release(), VAAPI::CVaapiBufferStats::Reset(), Actor::Protocol::SendOutMessageSync(), Actor::Message::signal, success, and VAAPI_ERROR.
ReturnRenderPicture()
void CDecoder::ReturnRenderPicture (CVaapiRenderPicture * renderPic) protected
References VAAPI::COutput::m_dataPort, m_vaapiOutput, VAAPI::COutputDataProtocol::RETURNPIC, and Actor::Protocol::SendOutMessage().
Referenced by VAAPI::CVaapiBufferPool::Return().
SetCodecControl()
void CDecoder::SetCodecControl (int flags) override virtual
Reimplemented from IHardwareDecoder.
References DVD_CODEC_CTRL_DRAIN, DVD_CODEC_CTRL_HURRY, and m_codecControl.
SetWidthHeight()
void VAAPI::CDecoder::SetWidthHeight (int width, int height) protected
Friends And Related Symbol Documentation
CVaapiBufferPool
friend class CVaapiBufferPool friend
Member Data Documentation
m_bufferStats
CVaapiBufferStats VAAPI::CDecoder::m_bufferStats protected
Referenced by CanSkipDeint(), ConfigVAAPI(), Decode(), FFGetBuffer(), and Reset().
m_capDeepColor
bool CDecoder::m_capDeepColor = false static protected
Referenced by Open(), and Register().
m_capGeneral
bool CDecoder::m_capGeneral = false static protected
Referenced by Open(), and Register().
m_codecControl
int VAAPI::CDecoder::m_codecControl protected
Referenced by Decode(), and SetCodecControl().
m_DecoderSection
CCriticalSection VAAPI::CDecoder::m_DecoderSection protected
Referenced by Check(), Close(), Decode(), FFGetBuffer(), FFReleaseBuffer(), GetPicture(), Release(), and Reset().
m_deviceRef
std::unique_ptr<AVBufferRef, AVBufferRefDeleter> VAAPI::CDecoder::m_deviceRef private
Referenced by Close(), and Open().
m_DisplayEvent
CEvent VAAPI::CDecoder::m_DisplayEvent protected
Referenced by Check().
m_DisplayState
enum VAAPI::CDecoder::EDisplayState VAAPI::CDecoder::m_DisplayState protected
Referenced by CDecoder(), Check(), CheckSuccess(), Decode(), FFGetBuffer(), GetPicture(), Open(), Release(), and Reset().
m_ErrorCount
int VAAPI::CDecoder::m_ErrorCount protected
Referenced by CheckSuccess(), and ConfigVAAPI().
m_getBufferError
int VAAPI::CDecoder::m_getBufferError protected
Referenced by CDecoder(), Check(), FFGetBuffer(), Open(), and Reset().
m_inMsgEvent
CEvent VAAPI::CDecoder::m_inMsgEvent protected
Referenced by ConfigVAAPI(), and Decode().
m_presentPicture
CVaapiRenderPicture* VAAPI::CDecoder::m_presentPicture = nullptr protected
Referenced by Decode(), GetPicture(), Open(), Release(), and Reset().
m_processInfo
CProcessInfo& VAAPI::CDecoder::m_processInfo protected
Referenced by CDecoder().
m_pWinSystem
IVaapiWinSystem * CDecoder::m_pWinSystem = nullptr static
Referenced by Register(), and VAAPI::CVAAPIContext::SetVaDisplayForSystem().
m_vaapiConfig
CVaapiConfig VAAPI::CDecoder::m_vaapiConfig protected
Referenced by CDecoder(), Check(), Close(), ConfigVAAPI(), FiniVAAPIOutput(), Open(), and Release().
m_vaapiConfigured
bool VAAPI::CDecoder::m_vaapiConfigured protected
Referenced by CDecoder(), ConfigVAAPI(), Decode(), FiniVAAPIOutput(), Open(), Release(), and Reset().
m_vaapiOutput
COutput VAAPI::CDecoder::m_vaapiOutput protected
Referenced by ConfigVAAPI(), Decode(), FiniVAAPIOutput(), Release(), Reset(), and ReturnRenderPicture().
m_videoSurfaces
CVideoSurfaces VAAPI::CDecoder::m_videoSurfaces protected
Referenced by CDecoder(), ConfigVAAPI(), Decode(), FFGetBuffer(), FFReleaseBuffer(), FiniVAAPIOutput(), Open(), and Release().
The documentation for this class was generated from the following files:
VAAPI.h
VAAPI.cpp