Kodi Documentation: KODI::GAME::CPhysicalTopology Class Reference
KODI::GAME::CPhysicalTopology Class Reference
Games
Represents the physical topology of controller add-ons.
#include <PhysicalTopology.h>
Public Member Functions
CPhysicalTopology ()=default
CPhysicalTopology (bool bProvidesInput, std::vector< CPhysicalPort > ports)
void Reset ()
bool ProvidesInput () const
Check if the controller can provide player input.
const std::vector< CPhysicalPort > & Ports () const
Get a list of ports provided by this controller.
bool Deserialize (const tinyxml2::XMLElement *pElement)
Private Attributes
bool m_bProvidesInput = true
std::vector< CPhysicalPort > m_ports
Detailed Description
Represents the physical topology of controller add-ons.
The physical topology of a controller defines how many ports it has and whether it can provide player input (hubs like the Super Multitap don't provide input).
Constructor & Destructor Documentation
CPhysicalTopology() [1/2]
KODI::GAME::CPhysicalTopology::CPhysicalTopology () default
CPhysicalTopology() [2/2]
CPhysicalTopology::CPhysicalTopology (bool bProvidesInput, std::vector< CPhysicalPort > ports)
Member Function Documentation
Deserialize()
bool CPhysicalTopology::Deserialize (const tinyxml2::XMLElement * pElement)
References KODI::GAME::CPhysicalPort::Deserialize(), XMLUtils::GetAttribute(), LAYOUT_XML_ATTR_PROVIDES_INPUT, LAYOUT_XML_ELM_PORT, CLog::Log(), LOGDEBUG, m_bProvidesInput, m_ports, and Reset().
Referenced by KODI::GAME::CControllerLayout::Deserialize().
Ports()
const std::vector< CPhysicalPort > & KODI::GAME::CPhysicalTopology::Ports () const inline
Get a list of ports provided by this controller.
Returns
The ports
References m_ports.
ProvidesInput()
bool KODI::GAME::CPhysicalTopology::ProvidesInput () const inline
Check if the controller can provide player input.
This allows hubs to specify that they provide no input
Returns
True if the controller can provide player input, false otherwise
References m_bProvidesInput.
Reset()
void CPhysicalTopology::Reset ()
Referenced by Deserialize().
Member Data Documentation
m_bProvidesInput
bool KODI::GAME::CPhysicalTopology::m_bProvidesInput = true private
Referenced by Deserialize(), and ProvidesInput().
m_ports
std::vector<CPhysicalPort> KODI::GAME::CPhysicalTopology::m_ports private
Referenced by Deserialize(), and Ports().
The documentation for this class was generated from the following files:
PhysicalTopology.h
PhysicalTopology.cpp