Kodi Documentation: DX Namespace Reference
DX Namespace Reference
Namespaces
namespace DisplayMetrics
Classes
class DeviceResources
struct SizeGen
Functions
virtual void OnDXDeviceRestored ()=0
const std::string DXGIFormatToString (const DXGI_FORMAT format)
const std::string DXGIColorSpaceTypeToString (DXGI_COLOR_SPACE_TYPE type)
const std::string D3D11VideoProcessorFormatSupportToString (D3D11_VIDEO_PROCESSOR_FORMAT_SUPPORT value)
void BreakIfFailed (HRESULT hr)
float ConvertDipsToPixels (float dips, float dpi)
float ConvertPixelsToDips (float pixels, float dpi)
float RationalToFloat (DXGI_RATIONAL rational)
void GetRefreshRatio (uint32_t refresh, uint32_t *num, uint32_t *den)
std::string GetFeatureLevelDescription (D3D_FEATURE_LEVEL featureLevel)
constexpr std::string_view GetGFXProviderName (UINT vendorId)
constexpr std::string_view DXGIFormatToShortString (const DXGI_FORMAT format)
Function Documentation
BreakIfFailed()
void DX::BreakIfFailed (HRESULT hr) inline
References FAILED.
ConvertDipsToPixels()
float DX::ConvertDipsToPixels (float dips, float dpi) inline
References DX::DisplayMetrics::Dpi100.
Referenced by DX::DeviceResources::GetDisplayMode(), GetScreenPoint(), and DX::DeviceResources::UpdateRenderTargetSize().
ConvertPixelsToDips()
float DX::ConvertPixelsToDips (float pixels, float dpi) inline
References DX::DisplayMetrics::Dpi100.
Referenced by CWinSystemWin10::AdjustWindow(), CWinSystemWin10::ChangeResolution(), and CWinSystemWin10::FinishWindowResize().
D3D11VideoProcessorFormatSupportToString()
const std::string DX::D3D11VideoProcessorFormatSupportToString (D3D11_VIDEO_PROCESSOR_FORMAT_SUPPORT value)
References value.
Referenced by DXVA::CEnumeratorHD::IsFormatSupportedInternal().
DXGIColorSpaceTypeToString()
const std::string DX::DXGIColorSpaceTypeToString (DXGI_COLOR_SPACE_TYPE type)
References CASEDXGICOLORSPACETYPE.
Referenced by DXVA::CEnumeratorHD::LogAndListConversions(), DXVA::CEnumeratorHD::LogSupportedConversions(), DX::DeviceResources::ResizeBuffers(), DX::DeviceResources::SetHdrColorSpace(), DXVA::CEnumeratorHD::SupportedConversions(), and DXVA::ProcessorConversion::ToString().
DXGIFormatToShortString()
constexpr std::string_view DX::DXGIFormatToShortString (const DXGI_FORMAT format) constexpr
Referenced by DX::DeviceResources::GetDebugInfo(), and CRendererBase::GetDebugInfo().
DXGIFormatToString()
const std::string DX::DXGIFormatToString (const DXGI_FORMAT format)
References CASEDXGIFORMAT, and UNKNOWN.
Referenced by CConvolutionShaderSeparable::ChooseIntermediateD3DFormat(), CD3DTexture::Create(), CRendererBase::CreateIntermediateTarget(), DXVA::CContext::CreateSurfaces(), DXVA::CContext::GetConfig(), DXVA::CContext::GetFormatAndConfig(), DXVA::CEnumeratorHD::GetProcessorFormats(), DXVA::CEnumeratorHD::GetProcessorRGBOutputFormats(), CRendererDXVA::GetWeight(), DXVA::CEnumeratorHD::IsFormatSupportedInternal(), DXVA::CEnumeratorHD::LogSupportedConversions(), DXVA::CDecoder::Open(), DXVA::CEnumeratorHD::ProbeProcessorCaps(), CRenderBuffer::QueueCopyFromGPU(), DX::DeviceResources::ResizeBuffers(), and DXVA::ProcessorConversion::ToString().
GetFeatureLevelDescription()
std::string DX::GetFeatureLevelDescription (D3D_FEATURE_LEVEL featureLevel) inline
Referenced by DXVA::CContext::CreateContext(), and DX::DeviceResources::CreateDeviceResources().
GetGFXProviderName()
constexpr std::string_view DX::GetGFXProviderName (UINT vendorId) constexpr
References PCIV_AMD, PCIV_Intel, PCIV_MICROSOFT, and PCIV_NVIDIA.
Referenced by VideoDriverInfo::Log().
GetRefreshRatio()
void DX::GetRefreshRatio (uint32_t refresh, uint32_t * num, uint32_t * den) inline
Referenced by CWinSystemWin32DX::FixRefreshRateIfNecessary().
OnDXDeviceRestored()
virtual void DX::OnDXDeviceRestored () pure virtual
RationalToFloat()
float DX::RationalToFloat (DXGI_RATIONAL rational) inline
References RATIONAL_TO_FLOAT.
Referenced by DX::DeviceResources::SetFullScreen().