Kodi Documentation: ADDON::Interface_GUIDialogContextMenu Struct Reference
ADDON::Interface_GUIDialogContextMenu Struct Reference
Global gui Add-on to Kodi callback functions.
#include <ContextMenu.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static int open (KODI_HANDLE kodiBase, const char *heading, const char *entries[], unsigned int size)
callback functions from add-on to kodi
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold functions not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/dialogs/ContextMenu.h"
Member Function Documentation
DeInit()
void ADDON::Interface_GUIDialogContextMenu::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::dialogContextMenu, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
Init()
void ADDON::Interface_GUIDialogContextMenu::Init (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::dialogContextMenu, AddonToKodiFuncTable_Addon::kodi_gui, open(), AddonToKodiFuncTable_kodi_gui_dialogContextMenu::open, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
open()
int ADDON::Interface_GUIDialogContextMenu::open (KODI_HANDLE kodiBase, const char * heading, const char * entries[], unsigned int size) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References CContextButtons::Add(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, CGUIDialogContextMenu::Show(), and WINDOW_DIALOG_CONTEXT_MENU.
Referenced by Init().
The documentation for this struct was generated from the following files:
interfaces/gui/dialogs/ContextMenu.h
ContextMenu.cpp