Kodi Documentation: anonymous_namespace{TestDefaultMouseTranslator.cpp} Namespace Reference
anonymous_namespace{TestDefaultMouseTranslator.cpp} Namespace Reference
Functions
JOYSTICK::FEATURE_TYPE GetButtonType (MOUSE::BUTTON_ID buttonId, const ControllerPtr &controller, unsigned int &count)
JOYSTICK::FEATURE_TYPE GetPointerType (MOUSE::POINTER_DIRECTION direction, const ControllerPtr &controller)
GAME::ControllerPtr GetController ()
Function Documentation
GetButtonType()
JOYSTICK::FEATURE_TYPE anonymous_namespace{TestDefaultMouseTranslator.cpp}::GetButtonType (MOUSE::BUTTON_ID buttonId, const ControllerPtr & controller, unsigned int & count)
References KODI::GAME::CDefaultMouseTranslator::TranslateMouseButton().
Referenced by TEST().
GetController()
GAME::ControllerPtr anonymous_namespace{TestDefaultMouseTranslator.cpp}::GetController ()
References ADDON::CHOICE_YES, DEFAULT_MOUSE_ID, EXPECT_EQ(), EXPECT_NE(), EXPECT_TRUE(), ADDON::GAME_CONTROLLER, ADDON::CAddonMgr::GetAddon(), and CServiceBroker::GetAddonMgr().
Referenced by TEST(), and TEST().
GetPointerType()
JOYSTICK::FEATURE_TYPE anonymous_namespace{TestDefaultMouseTranslator.cpp}::GetPointerType (MOUSE::POINTER_DIRECTION direction, const ControllerPtr & controller)
References KODI::GAME::CDefaultMouseTranslator::TranslateMousePointer().
Referenced by TEST().