Kodi Documentation: ActiveAE::CEngineStats Class Reference
ActiveAE::CEngineStats Class Reference
#include <ActiveAE.h>
Classes
struct StreamStats
Public Member Functions
void Reset (unsigned int sampleRate, bool pcm)
void UpdateSinkDelay (const AEDelayStatus &status, int samples)
void AddSamples (int samples, const std::list< CActiveAEStream * > &streams)
void GetDelay (AEDelayStatus &status)
void AddStream (unsigned int streamid)
void RemoveStream (unsigned int streamid)
void UpdateStream (CActiveAEStream *stream)
void GetDelay (AEDelayStatus &status, CActiveAEStream *stream)
void GetSyncInfo (CAESyncInfo &info, CActiveAEStream *stream)
float GetCacheTime (CActiveAEStream *stream)
float GetCacheTotal ()
float GetMaxDelay () const
float GetWaterLevel ()
void SetSuspended (bool state)
void SetCurrentSinkFormat (const AEAudioFormat &SinkFormat)
void SetSinkCacheTotal (float time)
void SetSinkLatency (float time)
void SetSinkNeedIec (bool needIEC)
bool IsSuspended ()
AEAudioFormat GetCurrentSinkFormat ()
Protected Attributes
float m_sinkCacheTotal
float m_sinkLatency
int m_bufferedSamples
unsigned int m_sinkSampleRate
AEDelayStatus m_sinkDelay
bool m_suspended
AEAudioFormat m_sinkFormat
bool m_pcmOutput
bool m_sinkNeedIecPack {false}
CCriticalSection m_lock
std::vector< StreamStats > m_streamStats
Member Function Documentation
AddSamples()
void CEngineStats::AddSamples (int samples, const std::list< CActiveAEStream * > & streams)
References m_bufferedSamples, m_lock, and UpdateStream().
Referenced by ActiveAE::CActiveAE::Configure(), and ActiveAE::CActiveAE::RunStages().
AddStream()
void CEngineStats::AddStream (unsigned int streamid)
References ActiveAE::CEngineStats::StreamStats::m_bufferedTime, ActiveAE::CEngineStats::StreamStats::m_resampleRatio, ActiveAE::CEngineStats::StreamStats::m_streamId, m_streamStats, ActiveAE::CEngineStats::StreamStats::m_syncError, ActiveAE::CEngineStats::StreamStats::m_syncState, and CAESyncInfo::SYNC_OFF.
Referenced by ActiveAE::CActiveAE::CreateStream().
GetCacheTime()
float CEngineStats::GetCacheTime (CActiveAEStream * stream)
References ActiveAE::CActiveAEStream::m_bufferedTime, ActiveAE::CActiveAEStream::m_id, m_lock, ActiveAE::CActiveAEStream::m_statsLock, and m_streamStats.
Referenced by ActiveAE::CActiveAE::GetCacheTime(), and ActiveAE::CActiveAE::RunStages().
GetCacheTotal()
float CEngineStats::GetCacheTotal ()
Referenced by ActiveAE::CActiveAE::GetCacheTotal().
GetCurrentSinkFormat()
AEAudioFormat CEngineStats::GetCurrentSinkFormat ()
References m_lock, and m_sinkFormat.
Referenced by ActiveAE::CActiveAE::GetCurrentSinkFormat().
GetDelay() [1/2]
void CEngineStats::GetDelay (AEDelayStatus & status)
References AEDelayStatus::delay, CAEStreamInfo::GetDuration(), m_bufferedSamples, m_lock, m_pcmOutput, m_sinkDelay, m_sinkFormat, m_sinkSampleRate, and AEAudioFormat::m_streamInfo.
Referenced by ActiveAE::CActiveAE::GetDelay(), ActiveAE::CActiveAE::RunStages(), and ActiveAE::CActiveAE::StateMachine().
GetDelay() [2/2]
void CEngineStats::GetDelay (AEDelayStatus & status, CActiveAEStream * stream)
References AEDelayStatus::delay, CAEStreamInfo::GetDuration(), m_bufferedSamples, ActiveAE::CActiveAEStream::m_bufferedTime, ActiveAE::CActiveAEStream::m_id, m_lock, m_pcmOutput, m_sinkDelay, m_sinkFormat, m_sinkLatency, m_sinkSampleRate, ActiveAE::CActiveAEStream::m_statsLock, AEAudioFormat::m_streamInfo, and m_streamStats.
GetMaxDelay()
float CEngineStats::GetMaxDelay () const
References m_sinkCacheTotal.
Referenced by ActiveAE::CActiveAE::Configure(), and ActiveAE::CActiveAE::GetMaxDelay().
GetSyncInfo()
void CEngineStats::GetSyncInfo (CAESyncInfo & info, CActiveAEStream * stream)
References AEDelayStatus::delay, AEDelayStatus::GetDelay(), CAEStreamInfo::GetDuration(), m_bufferedSamples, ActiveAE::CActiveAEStream::m_bufferedTime, ActiveAE::CActiveAEStream::m_id, m_lock, m_pcmOutput, m_sinkDelay, m_sinkFormat, m_sinkLatency, m_sinkSampleRate, ActiveAE::CActiveAEStream::m_statsLock, AEAudioFormat::m_streamInfo, and m_streamStats.
Referenced by ActiveAE::CActiveAE::GetSyncInfo().
GetWaterLevel()
float CEngineStats::GetWaterLevel ()
References CAEStreamInfo::GetDuration(), m_bufferedSamples, m_lock, m_pcmOutput, m_sinkFormat, m_sinkSampleRate, and AEAudioFormat::m_streamInfo.
Referenced by ActiveAE::CActiveAE::ApplySettingsToFormat(), and ActiveAE::CActiveAE::RunStages().
IsSuspended()
bool CEngineStats::IsSuspended ()
References m_lock, and m_suspended.
Referenced by ActiveAE::CActiveAE::IsSuspended().
RemoveStream()
void CEngineStats::RemoveStream (unsigned int streamid)
References m_streamStats.
Referenced by ActiveAE::CActiveAE::DiscardStream().
Reset()
void CEngineStats::Reset (unsigned int sampleRate, bool pcm)
References m_bufferedSamples, m_lock, m_pcmOutput, m_sinkDelay, m_sinkSampleRate, m_suspended, and AEDelayStatus::SetDelay().
Referenced by ActiveAE::CActiveAE::CActiveAE(), ActiveAE::CActiveAE::Configure(), and ActiveAE::CActiveAE::FlushEngine().
SetCurrentSinkFormat()
void CEngineStats::SetCurrentSinkFormat (const AEAudioFormat & SinkFormat)
References m_lock, and m_sinkFormat.
Referenced by ActiveAE::CActiveAE::InitSink().
SetSinkCacheTotal()
void ActiveAE::CEngineStats::SetSinkCacheTotal (float time) inline
References m_sinkCacheTotal.
Referenced by ActiveAE::CActiveAE::InitSink().
SetSinkLatency()
void ActiveAE::CEngineStats::SetSinkLatency (float time) inline
References m_sinkLatency.
Referenced by ActiveAE::CActiveAE::InitSink().
SetSinkNeedIec()
void ActiveAE::CEngineStats::SetSinkNeedIec (bool needIEC) inline
References m_sinkNeedIecPack.
Referenced by ActiveAE::CActiveAE::InitSink().
SetSuspended()
void CEngineStats::SetSuspended (bool state)
References m_lock, and m_suspended.
Referenced by ActiveAE::CActiveAE::StateMachine().
UpdateSinkDelay()
void CEngineStats::UpdateSinkDelay (const AEDelayStatus & status, int samples)
References CLog::Log(), LOGERROR, m_bufferedSamples, m_lock, and m_sinkDelay.
Referenced by ActiveAE::CActiveAESink::OutputSamples().
UpdateStream()
void CEngineStats::UpdateStream (CActiveAEStream * stream)
References CAEStreamInfo::GetDuration(), ActiveAE::CSyncError::GetLastError(), ActiveAE::CActiveAEStream::m_bufferedTime, ActiveAE::CActiveAEStream::m_id, m_lock, m_pcmOutput, ActiveAE::CActiveAEStream::m_processingBuffers, ActiveAE::CActiveAEStream::m_processingSamples, m_sinkFormat, ActiveAE::CActiveAEStream::m_statsLock, AEAudioFormat::m_streamInfo, m_streamStats, ActiveAE::CActiveAEStream::m_syncError, and ActiveAE::CActiveAEStream::m_syncState.
Referenced by AddSamples(), ActiveAE::CActiveAE::RunStages(), and ActiveAE::CActiveAE::SFlushStream().
Member Data Documentation
m_bufferedSamples
int ActiveAE::CEngineStats::m_bufferedSamples protected
Referenced by AddSamples(), GetDelay(), GetDelay(), GetSyncInfo(), GetWaterLevel(), Reset(), and UpdateSinkDelay().
m_lock
CCriticalSection ActiveAE::CEngineStats::m_lock protected
Referenced by AddSamples(), GetCacheTime(), GetCurrentSinkFormat(), GetDelay(), GetDelay(), GetSyncInfo(), GetWaterLevel(), IsSuspended(), Reset(), SetCurrentSinkFormat(), SetSuspended(), UpdateSinkDelay(), and UpdateStream().
m_pcmOutput
bool ActiveAE::CEngineStats::m_pcmOutput protected
Referenced by GetDelay(), GetDelay(), GetSyncInfo(), GetWaterLevel(), Reset(), and UpdateStream().
m_sinkCacheTotal
float ActiveAE::CEngineStats::m_sinkCacheTotal protected
Referenced by GetMaxDelay(), and SetSinkCacheTotal().
m_sinkDelay
AEDelayStatus ActiveAE::CEngineStats::m_sinkDelay protected
Referenced by GetDelay(), GetDelay(), GetSyncInfo(), Reset(), and UpdateSinkDelay().
m_sinkFormat
AEAudioFormat ActiveAE::CEngineStats::m_sinkFormat protected
Referenced by GetCurrentSinkFormat(), GetDelay(), GetDelay(), GetSyncInfo(), GetWaterLevel(), SetCurrentSinkFormat(), and UpdateStream().
m_sinkLatency
float ActiveAE::CEngineStats::m_sinkLatency protected
Referenced by GetDelay(), GetSyncInfo(), and SetSinkLatency().
m_sinkNeedIecPack
bool ActiveAE::CEngineStats::m_sinkNeedIecPack {false} protected
Referenced by SetSinkNeedIec().
m_sinkSampleRate
unsigned int ActiveAE::CEngineStats::m_sinkSampleRate protected
Referenced by GetDelay(), GetDelay(), GetSyncInfo(), GetWaterLevel(), and Reset().
m_streamStats
std::vector<StreamStats> ActiveAE::CEngineStats::m_streamStats protected
Referenced by AddStream(), GetCacheTime(), GetDelay(), GetSyncInfo(), RemoveStream(), and UpdateStream().
m_suspended
bool ActiveAE::CEngineStats::m_suspended protected
Referenced by IsSuspended(), Reset(), and SetSuspended().
The documentation for this class was generated from the following files:
ActiveAE.h
ActiveAE.cpp