Kodi Documentation: ADDON::CBinaryAddonCache Class Reference
ADDON::CBinaryAddonCache Class Reference
#include <BinaryAddonCache.h>
Public Member Functions
virtual ~CBinaryAddonCache ()
void Init ()
void Deinit ()
void GetAddons (VECADDONS &addons, AddonType type)
void GetDisabledAddons (VECADDONS &addons, AddonType type)
void GetInstalledAddons (VECADDONS &addons, AddonType type)
AddonPtr GetAddonInstance (const std::string &strId, AddonType type)
Protected Member Functions
void Update ()
void OnEvent (const AddonEvent &event)
Protected Attributes
CCriticalSection m_critSection
std::multimap< AddonType, VECADDONS > m_addons
Constructor & Destructor Documentation
~CBinaryAddonCache()
ADDON::CBinaryAddonCache::~CBinaryAddonCache () virtual
References Deinit().
Member Function Documentation
Deinit()
void ADDON::CBinaryAddonCache::Deinit ()
References ADDON::CAddonMgr::Events(), and CServiceBroker::GetAddonMgr().
Referenced by ~CBinaryAddonCache().
GetAddonInstance()
AddonPtr ADDON::CBinaryAddonCache::GetAddonInstance (const std::string & strId, AddonType type)
References addons, m_addons, and m_critSection.
Referenced by KODI::GAME::CGameClient::GetRunningInstance().
GetAddons()
void ADDON::CBinaryAddonCache::GetAddons (VECADDONS & addons, AddonType type)
References addons, CServiceBroker::GetAddonMgr(), GetInstalledAddons(), and ADDON::CAddonMgr::IsAddonDisabled().
Referenced by KODI::GAME::CGameUtils::GetGameClients(), and KODI::GAME::CGameUtils::GetGameExtensions().
GetDisabledAddons()
void ADDON::CBinaryAddonCache::GetDisabledAddons (VECADDONS & addons, AddonType type)
References addons, CServiceBroker::GetAddonMgr(), GetInstalledAddons(), and ADDON::CAddonMgr::IsAddonDisabled().
GetInstalledAddons()
void ADDON::CBinaryAddonCache::GetInstalledAddons (VECADDONS & addons, AddonType type)
References addons, m_addons, and m_critSection.
Referenced by GetAddons(), GetDisabledAddons(), and KODI::GAME::CGameUtils::HasGameExtension().
Init()
void ADDON::CBinaryAddonCache::Init ()
References ADDON::CAddonMgr::Events(), CServiceBroker::GetAddonMgr(), OnEvent(), and Update().
OnEvent()
void ADDON::CBinaryAddonCache::OnEvent (const AddonEvent & event) protected
References ADDON::AddonEvent::addonId, ADDON::ADDONS_TO_CACHE, CServiceBroker::GetAddonMgr(), ADDON::CAddonMgr::HasType(), and Update().
Referenced by Init().
Update()
void ADDON::CBinaryAddonCache::Update () protected
References addons, ADDON::ADDONS_TO_CACHE, CServiceBroker::GetAddonMgr(), ADDON::CAddonMgr::GetInstalledAddons(), m_addons, and m_critSection.
Referenced by Init(), and OnEvent().
Member Data Documentation
m_addons
std::multimap<AddonType, VECADDONS> ADDON::CBinaryAddonCache::m_addons protected
Referenced by GetAddonInstance(), GetInstalledAddons(), and Update().
m_critSection
CCriticalSection ADDON::CBinaryAddonCache::m_critSection protected
Referenced by GetAddonInstance(), GetInstalledAddons(), and Update().
The documentation for this class was generated from the following files:
BinaryAddonCache.h
BinaryAddonCache.cpp