Kodi Documentation: CPosixResourceCounter Class Reference
CPosixResourceCounter Class Reference
#include <PosixResourceCounter.h>
Public Member Functions
CPosixResourceCounter ()
virtual ~CPosixResourceCounter ()
double GetCPUUsage ()
void Reset ()
Protected Attributes
struct rusage m_usage
struct timeval m_tmLastCheck
double m_dLastUsage
Constructor & Destructor Documentation
CPosixResourceCounter()
CPosixResourceCounter::CPosixResourceCounter ()
References Reset().
~CPosixResourceCounter()
CPosixResourceCounter::~CPosixResourceCounter () virtual default
Member Function Documentation
GetCPUUsage()
double CPosixResourceCounter::GetCPUUsage ()
References CLog::Log(), LOGERROR, m_dLastUsage, m_tmLastCheck, m_usage, and usage.
Reset()
void CPosixResourceCounter::Reset ()
References CLog::Log(), LOGERROR, m_dLastUsage, m_tmLastCheck, and m_usage.
Referenced by CPosixResourceCounter().
Member Data Documentation
m_dLastUsage
double CPosixResourceCounter::m_dLastUsage protected
Referenced by GetCPUUsage(), and Reset().
m_tmLastCheck
struct timeval CPosixResourceCounter::m_tmLastCheck protected
Referenced by GetCPUUsage(), and Reset().
m_usage
struct rusage CPosixResourceCounter::m_usage protected
Referenced by GetCPUUsage(), and Reset().
The documentation for this class was generated from the following files:
PosixResourceCounter.h
PosixResourceCounter.cpp