Kodi Documentation: KODI::GAME::CGameServices Class Reference
KODI::GAME::CGameServices Class Reference
Games
#include <GameServices.h>
Public Member Functions
CGameServices (CControllerManager &controllerManager, RETRO::CGUIGameRenderManager &renderManager, PERIPHERALS::CPeripherals &peripheralManager, const CProfileManager &profileManager, CInputManager &inputManager)
~CGameServices ()
ControllerPtr GetController (const std::string &controllerId)
ControllerPtr GetDefaultController ()
ControllerPtr GetDefaultKeyboard ()
ControllerPtr GetDefaultMouse ()
ControllerVector GetControllers ()
std::string TranslateFeature (const std::string &controllerId, const std::string &featureName)
Translate a feature on a controller into its localized name.
std::string GetSavestatesFolder () const
CGameSettings & GameSettings ()
RETRO::CGUIGameRenderManager & GameRenderManager ()
CAgentInput & AgentInput ()
Private Attributes
CControllerManager & m_controllerManager
RETRO::CGUIGameRenderManager & m_gameRenderManager
const CProfileManager & m_profileManager
std::unique_ptr< CGameSettings > m_gameSettings
std::unique_ptr< CAgentInput > m_agentInput
Constructor & Destructor Documentation
CGameServices()
CGameServices::CGameServices (CControllerManager & controllerManager, RETRO::CGUIGameRenderManager & renderManager, PERIPHERALS::CPeripherals & peripheralManager, const CProfileManager & profileManager, CInputManager & inputManager)
~CGameServices()
CGameServices::~CGameServices () default
Member Function Documentation
AgentInput()
CAgentInput & KODI::GAME::CGameServices::AgentInput () inline
References m_agentInput.
Referenced by KODI::GAME::CGUIAgentControllerList::Deinitialize(), KODI::GAME::CGUIGameController::DoProcess(), KODI::GAME::CGUIGameControllerList::GetPortAddress(), KODI::GAME::CGUIAgentControllerList::Initialize(), KODI::GAME::CGUIAgentControllerList::OnControllerSelect(), KODI::GAME::CGUIAgentControllerList::Refresh(), KODI::RETRO::CRenderContext::StartAgentInput(), KODI::RETRO::CRenderContext::StopAgentInput(), KODI::GAME::CGUIGameControllerList::UpdateInfo(), and KODI::GAME::CGUIGameControllerList::UpdatePort().
GameRenderManager()
RETRO::CGUIGameRenderManager & KODI::GAME::CGameServices::GameRenderManager () inline
References m_gameRenderManager.
Referenced by KODI::RETRO::CRetroPlayer::RegisterWindowCallbacks(), and KODI::RETRO::CRetroPlayer::UnregisterWindowCallbacks().
GameSettings()
CGameSettings & KODI::GAME::CGameServices::GameSettings () inline
References m_gameSettings.
Referenced by KODI::RETRO::CRetroPlayer::CloseFile(), KODI::RETRO::CReversiblePlayback::CReversiblePlayback(), KODI::GAME::CDialogGameOSD::OnAction(), KODI::GAME::CDialogGameOSD::OnDeinitWindow(), KODI::JOYSTICK::CJoystickEasterEgg::OnFinish(), KODI::RETRO::CGameWindowFullScreen::OnInitWindow(), KODI::RETRO::CRetroPlayer::OpenFile(), KODI::RETRO::CReversiblePlayback::UpdateMemoryStream(), and KODI::RETRO::CReversiblePlayback::~CReversiblePlayback().
GetController()
ControllerPtr CGameServices::GetController (const std::string & controllerId)
References KODI::GAME::CControllerManager::GetController(), and m_controllerManager.
Referenced by KODI::GAME::CGUIGameController::ActivateController(), KODI::GAME::CGameClientDevice::GetController(), KODI::GAME::CGameClientInput::GetControllers(), and KODI::GAME::CGUIGameControllerList::UpdateInfo().
GetControllers()
ControllerVector CGameServices::GetControllers ()
References KODI::GAME::CControllerManager::GetControllers(), and m_controllerManager.
Referenced by KODI::GAME::CGUIControllerList::RefreshControllers().
GetDefaultController()
ControllerPtr CGameServices::GetDefaultController ()
References KODI::GAME::CControllerManager::GetDefaultController(), and m_controllerManager.
Referenced by KODI::GAME::CGameClientInput::GetControllers(), and KODI::GAME::CGUIControllerList::RefreshControllers().
GetDefaultKeyboard()
ControllerPtr CGameServices::GetDefaultKeyboard ()
References KODI::GAME::CControllerManager::GetDefaultKeyboard(), and m_controllerManager.
GetDefaultMouse()
ControllerPtr CGameServices::GetDefaultMouse ()
References KODI::GAME::CControllerManager::GetDefaultMouse(), and m_controllerManager.
GetSavestatesFolder()
std::string CGameServices::GetSavestatesFolder () const
References CProfileManager::GetSavestatesFolder(), and m_profileManager.
Referenced by KODI::GAME::CGameClientInGameSaves::GetPath(), and KODI::GAME::CGameClient::Initialize().
TranslateFeature()
std::string CGameServices::TranslateFeature (const std::string & controllerId, const std::string & featureName)
Translate a feature on a controller into its localized name.
Parameters
controllerId The controller ID that the feature belongs to
featureName The feature name
Returns
The localized feature name, or empty if the controller or feature doesn't exist
References m_controllerManager, and KODI::GAME::CControllerManager::TranslateFeature().
Referenced by ControllerFeatureReplacer().
Member Data Documentation
m_agentInput
std::unique_ptr<CAgentInput> KODI::GAME::CGameServices::m_agentInput private
Referenced by AgentInput().
m_controllerManager
CControllerManager& KODI::GAME::CGameServices::m_controllerManager private
Referenced by GetController(), GetControllers(), GetDefaultController(), GetDefaultKeyboard(), GetDefaultMouse(), and TranslateFeature().
m_gameRenderManager
RETRO::CGUIGameRenderManager& KODI::GAME::CGameServices::m_gameRenderManager private
Referenced by GameRenderManager().
m_gameSettings
std::unique_ptr<CGameSettings> KODI::GAME::CGameServices::m_gameSettings private
Referenced by GameSettings().
m_profileManager
const CProfileManager& KODI::GAME::CGameServices::m_profileManager private
Referenced by GetSavestatesFolder().
The documentation for this class was generated from the following files:
GameServices.h
GameServices.cpp