Kodi Documentation: kodi::addon::PVRSettingKeyValuePair Class Reference
kodi::addon::PVRSettingKeyValuePair Class Reference
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 1. General » class PVRSettingKeyValuePair
#include <General.h>
Public Member Functions
PVRSettingKeyValuePair ()=default
Default class constructor.
PVRSettingKeyValuePair (unsigned int key, int value)
Class constructor with integrated value set.
PVRSettingKeyValuePair (unsigned int key, const std::string &value)
Class constructor with integrated value set.
PVRSettingKeyValuePair (unsigned int key, PVR_SETTING_TYPE eType, int intValue, const std::string &stringValue)
Class constructor with integrated value set.
void SetKey (unsigned int key)
To set with the key.
unsigned GetKey () const
To get with the key.
void SetType (PVR_SETTING_TYPE eType)
required
This key value pair's type.
PVR_SETTING_TYPE GetType () const
To get with SetType changed values.
void SetIntValue (int value)
To set with the value.
int GetIntValue () const
To get with the value.
void SetStringValue (const std::string &value)
To set with the value.
std::string GetStringValue () const
To get with the value.
Public Member Functions inherited from kodi::addon::DynamicCStructHdl< PVRSettingKeyValuePair, PVR_SETTING_KEY_VALUE_PAIR >
DynamicCStructHdl ()
DynamicCStructHdl (const DynamicCStructHdl &cppClass)
DynamicCStructHdl (const PVR_SETTING_KEY_VALUE_PAIR *cStructure)
DynamicCStructHdl (PVR_SETTING_KEY_VALUE_PAIR *cStructure)
const DynamicCStructHdl & operator= (const DynamicCStructHdl &right)
const DynamicCStructHdl & operator= (const PVR_SETTING_KEY_VALUE_PAIR &right)
virtual ~DynamicCStructHdl ()
operator PVR_SETTING_KEY_VALUE_PAIR * ()
operator const PVR_SETTING_KEY_VALUE_PAIR * () const
const PVR_SETTING_KEY_VALUE_PAIR * GetCStructure () const
PVR_SETTING_KEY_VALUE_PAIR * release ()
Static Public Member Functions
static PVR_SETTING_KEY_VALUE_PAIR * AllocAndCopyData (const std::vector< PVRSettingKeyValuePair > &values)
static PVR_SETTING_KEY_VALUE_PAIR * AllocAndCopyData (const PVR_SETTING_KEY_VALUE_PAIR *source, unsigned int size)
static void AllocResources (const PVR_SETTING_KEY_VALUE_PAIR *source, PVR_SETTING_KEY_VALUE_PAIR *target)
static void FreeResources (PVR_SETTING_KEY_VALUE_PAIR *target)
static void FreeResources (PVR_SETTING_KEY_VALUE_PAIR *pairs, unsigned int size)
static void ReallocAndCopyData (PVR_SETTING_KEY_VALUE_PAIR **source, unsigned int *size, const std::vector< PVRSettingKeyValuePair > &values)
Private Member Functions
PVRSettingKeyValuePair (const PVR_SETTING_KEY_VALUE_PAIR *pair)
PVRSettingKeyValuePair (PVR_SETTING_KEY_VALUE_PAIR *pair)
Friends
class CInstancePVRClient
Additional Inherited Members
Protected Attributes inherited from kodi::addon::DynamicCStructHdl< PVRSettingKeyValuePair, PVR_SETTING_KEY_VALUE_PAIR >
PVR_SETTING_KEY_VALUE_PAIR * m_cStructure
Constructor & Destructor Documentation
PVRSettingKeyValuePair() [1/2]
kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair (const PVR_SETTING_KEY_VALUE_PAIR * pair) inline private
PVRSettingKeyValuePair() [2/2]
kodi::addon::PVRSettingKeyValuePair::PVRSettingKeyValuePair (PVR_SETTING_KEY_VALUE_PAIR * pair) inline private
Member Function Documentation
AllocAndCopyData() [1/2]
static PVR_SETTING_KEY_VALUE_PAIR * kodi::addon::PVRSettingKeyValuePair::AllocAndCopyData (const PVR_SETTING_KEY_VALUE_PAIR * source, unsigned int size) inline static
References AllocResources(), PVR_SETTING_KEY_VALUE_PAIR::eType, PVR_SETTING_KEY_VALUE_PAIR::iKey, and PVR_SETTING_KEY_VALUE_PAIR::iValue.
AllocAndCopyData() [2/2]
static PVR_SETTING_KEY_VALUE_PAIR * kodi::addon::PVRSettingKeyValuePair::AllocAndCopyData (const std::vector< PVRSettingKeyValuePair > & values) inline static
References AllocResources(), PVR_SETTING_KEY_VALUE_PAIR::eType, kodi::addon::DynamicCStructHdl< PVRSettingKeyValuePair, PVR_SETTING_KEY_VALUE_PAIR >::GetCStructure(), PVR_SETTING_KEY_VALUE_PAIR::iKey, PVR_SETTING_KEY_VALUE_PAIR::iValue, and values.
Referenced by kodi::addon::PVRTimer::AllocResources(), and ReallocAndCopyData().
AllocResources()
static void kodi::addon::PVRSettingKeyValuePair::AllocResources (const PVR_SETTING_KEY_VALUE_PAIR * source, PVR_SETTING_KEY_VALUE_PAIR * target) inline static
References kodi::addon::AllocAndCopyString(), and PVR_SETTING_KEY_VALUE_PAIR::strValue.
Referenced by AllocAndCopyData(), and AllocAndCopyData().
FreeResources() [1/2]
static void kodi::addon::PVRSettingKeyValuePair::FreeResources (PVR_SETTING_KEY_VALUE_PAIR * pairs, unsigned int size) inline static
References FreeResources().
FreeResources() [2/2]
static void kodi::addon::PVRSettingKeyValuePair::FreeResources (PVR_SETTING_KEY_VALUE_PAIR * target) inline static
References kodi::addon::FreeString(), and PVR_SETTING_KEY_VALUE_PAIR::strValue.
Referenced by FreeResources(), kodi::addon::PVRTimer::FreeResources(), and ReallocAndCopyData().
ReallocAndCopyData()
static void kodi::addon::PVRSettingKeyValuePair::ReallocAndCopyData (PVR_SETTING_KEY_VALUE_PAIR ** source, unsigned int * size, const std::vector< PVRSettingKeyValuePair > & values) inline static
References AllocAndCopyData(), FreeResources(), and values.
Referenced by kodi::addon::PVRTimer::SetCustomProperties().
Friends And Related Symbol Documentation
CInstancePVRClient
friend class CInstancePVRClient friend
The documentation for this class was generated from the following file:
kodi-dev-kit/include/kodi/addon-instance/pvr/General.h