Kodi Documentation: class PeripheralEvent
class PeripheralEvent
C++ » Interface - kodi::addon » Addon type instances » Peripheral » Definitions, structures and enumerators » 2. Peripheral
Wrapper class for peripheral events
To handle data of change events between add-on and Kodi.
Classes
class kodi::addon::PeripheralEvent
Functions
kodi::addon::PeripheralEvent::PeripheralEvent ()=default
Constructor.
kodi::addon::PeripheralEvent::PeripheralEvent (unsigned int peripheralIndex, unsigned int buttonIndex, JOYSTICK_STATE_BUTTON state)
Constructor.
kodi::addon::PeripheralEvent::PeripheralEvent (unsigned int peripheralIndex, unsigned int hatIndex, JOYSTICK_STATE_HAT state)
Constructor.
kodi::addon::PeripheralEvent::PeripheralEvent (unsigned int peripheralIndex, unsigned int axisIndex, JOYSTICK_STATE_AXIS state)
Constructor.
PERIPHERAL_EVENT_TYPE kodi::addon::PeripheralEvent::Type (void) const
Get type of event.
unsigned int kodi::addon::PeripheralEvent::PeripheralIndex (void) const
Get peripheral index.
unsigned int kodi::addon::PeripheralEvent::DriverIndex (void) const
Get driver index.
JOYSTICK_STATE_BUTTON kodi::addon::PeripheralEvent::ButtonState (void) const
Get button state.
JOYSTICK_STATE_HAT kodi::addon::PeripheralEvent::HatState (void) const
Get hat state.
JOYSTICK_STATE_AXIS kodi::addon::PeripheralEvent::AxisState (void) const
Get axis state.
JOYSTICK_STATE_MOTOR kodi::addon::PeripheralEvent::MotorState (void) const
Get motor state.
void kodi::addon::PeripheralEvent::SetType (PERIPHERAL_EVENT_TYPE type)
Set type of event.
void kodi::addon::PeripheralEvent::SetPeripheralIndex (unsigned int index)
Set peripheral index.
void kodi::addon::PeripheralEvent::SetDriverIndex (unsigned int index)
Set driver index.
void kodi::addon::PeripheralEvent::SetButtonState (JOYSTICK_STATE_BUTTON state)
Set button state.
void kodi::addon::PeripheralEvent::SetHatState (JOYSTICK_STATE_HAT state)
Set hat state.
void kodi::addon::PeripheralEvent::SetAxisState (JOYSTICK_STATE_AXIS state)
Set axis state.
void kodi::addon::PeripheralEvent::SetMotorState (JOYSTICK_STATE_MOTOR state)
Set motor state.
Detailed Description
Wrapper class for peripheral events
To handle data of change events between add-on and Kodi.
Used on kodi::addon::CInstancePeripheral::GetEvents() and kodi::addon::CInstancePeripheral::SendEvent().
@ingroup cpp_kodi_addon_peripheral_Defs_Peripheral_PeripheralEvent
The following table contains values that can be set with class PeripheralEvent :
Name Type Set call Get call
Peripheral event type PERIPHERAL_EVENT_TYPE SetType Type
Peripheral index unsigned int SetPeripheralIndex PeripheralIndex
Peripheral event driver index unsigned int SetDriverIndex DriverIndex
Peripheral event button state JOYSTICK_STATE_BUTTON SetButtonState ButtonState
Peripheral event hat state JOYSTICK_STATE_HAT SetHatState HatState
Peripheral event axis state JOYSTICK_STATE_AXIS (float) SetAxisState AxisState
Peripheral event motor state JOYSTICK_STATE_MOTOR (float) SetMotorState MotorState
Further are several class constructors with values included.
Function Documentation
AxisState()
JOYSTICK_STATE_AXIS kodi::addon::PeripheralEvent::AxisState (void) const inline
Get axis state.
Returns
Axis state
References kodi::addon::PeripheralEvent::m_axisState.
Referenced by PERIPHERALS::CPeripheralAddon::ProcessEvents().
ButtonState()
JOYSTICK_STATE_BUTTON kodi::addon::PeripheralEvent::ButtonState (void) const inline
Get button state.
Returns
Button state as JOYSTICK_STATE_BUTTON
References kodi::addon::PeripheralEvent::m_buttonState.
DriverIndex()
unsigned int kodi::addon::PeripheralEvent::DriverIndex (void) const inline
Get driver index.
Returns
Driver index number
References kodi::addon::PeripheralEvent::m_driverIndex.
Referenced by PERIPHERALS::CPeripheralAddon::ProcessEvents().
HatState()
JOYSTICK_STATE_HAT kodi::addon::PeripheralEvent::HatState (void) const inline
Get hat state.
Returns
Hat state
References kodi::addon::PeripheralEvent::m_hatState.
Referenced by PERIPHERALS::CPeripheralAddon::ProcessEvents().
MotorState()
JOYSTICK_STATE_MOTOR kodi::addon::PeripheralEvent::MotorState (void) const inline
Get motor state.
Returns
Motor state
References kodi::addon::PeripheralEvent::m_motorState.
PeripheralEvent() [1/4]
kodi::addon::PeripheralEvent::PeripheralEvent () default
Constructor.
PeripheralEvent() [2/4]
kodi::addon::PeripheralEvent::PeripheralEvent (unsigned int peripheralIndex, unsigned int axisIndex, JOYSTICK_STATE_AXIS state) inline
Constructor.
Parameters
[in] peripheralIndex Peripheral index
[in] axisIndex Axis index
[in] state Joystick state axis
PeripheralEvent() [3/4]
kodi::addon::PeripheralEvent::PeripheralEvent (unsigned int peripheralIndex, unsigned int buttonIndex, JOYSTICK_STATE_BUTTON state) inline
Constructor.
Parameters
[in] peripheralIndex Peripheral index
[in] buttonIndex Button index
[in] state Joystick state button
PeripheralEvent() [4/4]
kodi::addon::PeripheralEvent::PeripheralEvent (unsigned int peripheralIndex, unsigned int hatIndex, JOYSTICK_STATE_HAT state) inline
Constructor.
Parameters
[in] peripheralIndex Peripheral index
[in] hatIndex Hat index
[in] state Joystick state hat
PeripheralIndex()
unsigned int kodi::addon::PeripheralEvent::PeripheralIndex (void) const inline
Get peripheral index.
Returns
Peripheral index number
References kodi::addon::PeripheralEvent::m_peripheralIndex.
Referenced by PERIPHERALS::CPeripheralAddon::ProcessEvents().
SetAxisState()
void kodi::addon::PeripheralEvent::SetAxisState (JOYSTICK_STATE_AXIS state) inline
Set axis state.
Parameters
[in] state Axis state as JOYSTICK_STATE_AXIS (float)
References kodi::addon::PeripheralEvent::m_axisState.
SetButtonState()
void kodi::addon::PeripheralEvent::SetButtonState (JOYSTICK_STATE_BUTTON state) inline
Set button state.
Parameters
[in] state Button state as JOYSTICK_STATE_BUTTON
References kodi::addon::PeripheralEvent::m_buttonState.
SetDriverIndex()
void kodi::addon::PeripheralEvent::SetDriverIndex (unsigned int index) inline
Set driver index.
Parameters
[in] index Driver index number
References index(), and kodi::addon::PeripheralEvent::m_driverIndex.
SetHatState()
void kodi::addon::PeripheralEvent::SetHatState (JOYSTICK_STATE_HAT state) inline
Set hat state.
Parameters
[in] state Hat state as JOYSTICK_STATE_HAT (float)
References kodi::addon::PeripheralEvent::m_hatState.
SetMotorState()
void kodi::addon::PeripheralEvent::SetMotorState (JOYSTICK_STATE_MOTOR state) inline
Set motor state.
Parameters
[in] state Motor state as JOYSTICK_STATE_MOTOR (float)
References kodi::addon::PeripheralEvent::m_motorState.
SetPeripheralIndex()
void kodi::addon::PeripheralEvent::SetPeripheralIndex (unsigned int index) inline
Set peripheral index.
Parameters
[in] index Peripheral index number
References index(), and kodi::addon::PeripheralEvent::m_peripheralIndex.
SetType()
void kodi::addon::PeripheralEvent::SetType (PERIPHERAL_EVENT_TYPE type) inline
Set type of event.
Parameters
[in] type Type defined with PERIPHERAL_EVENT_TYPE
References kodi::addon::PeripheralEvent::m_type.
Type()
PERIPHERAL_EVENT_TYPE kodi::addon::PeripheralEvent::Type (void) const inline
Get type of event.
Returns
Type defined with PERIPHERAL_EVENT_TYPE
References kodi::addon::PeripheralEvent::m_type.
Referenced by PERIPHERALS::CPeripheralAddon::ProcessEvents().