Kodi Documentation: CocoaPowerSyscall.cpp File Reference
CocoaPowerSyscall.cpp File Reference
#include "CocoaPowerSyscall.h"
#include "ServiceBroker.h"
#include "application/Application.h"
#include "powermanagement/PowerManager.h"
#include "utils/SystemInfo.h"
#include "utils/log.h"
#include "platform/darwin/osx/CocoaInterface.h"
#include <ApplicationServices/ApplicationServices.h>
#include <IOKit/ps/IOPSKeys.h>
#include <IOKit/ps/IOPowerSources.h>
#include <IOKit/pwr_mgt/IOPMLib.h>
Typedefs
typedef unsigned char BYTE
Functions
OSStatus SendAppleEventToSystemProcess (AEEventID eventToSendID)
static bool stringsAreEqual (CFStringRef a, CFStringRef b)
Typedef Documentation
BYTE
typedef unsigned char BYTE
Function Documentation
SendAppleEventToSystemProcess()
OSStatus SendAppleEventToSystemProcess (AEEventID eventToSendID)
Referenced by CCocoaPowerSyscall::Powerdown(), CCocoaPowerSyscall::Reboot(), and CCocoaPowerSyscall::Suspend().
stringsAreEqual()
static bool stringsAreEqual (CFStringRef a, CFStringRef b) static
Referenced by CCocoaPowerSyscall::OSPowerSourceCallBack().