Kodi Documentation: WsgiErrorStream
WsgiErrorStream
Python » Library - xbmcwsgi
Represents the wsgi.errors stream to write error messages.
Classes
class XBMCAddon::xbmcwsgi::WsgiErrorStream
Functions
XBMCAddon::xbmcwsgi::WsgiErrorStream::flush ()
XBMCAddon::xbmcwsgi::WsgiErrorStream::write (...)
XBMCAddon::xbmcwsgi::WsgiErrorStream::writelines (...)
Detailed Description
Represents the wsgi.errors stream to write error messages.
Class: WsgiErrorStream()
This implementation writes the error messages to the application's log file.
Function Documentation
flush()
XBMCAddon::xbmcwsgi::WsgiErrorStream::flush ()
Function: flush()
Since nothing is buffered this is a no-op.
write()
void XBMCAddon::xbmcwsgi::WsgiErrorStream::write (...)
Function: write(str)
Writes the given error message to the application's log file.
Parameters
str A string to save in log file
Note
A trailing \n is removed.
References CLog::Log(), LOGERROR, XBMCAddon::xbmcwsgi::WsgiErrorStream::m_request, and HTTPPythonRequest::url.
Referenced by XBMCAddon::xbmcwsgi::WsgiErrorStream::writelines().
writelines()
void XBMCAddon::xbmcwsgi::WsgiErrorStream::writelines (...)
Function: writelines(seq)
Joins the given list of error messages (without any separator) into a single error message which is written to the application's log file.
Parameters
seq A list of strings which will be logged.
References XBMCAddon::xbmcwsgi::WsgiErrorStream::write().