Kodi Documentation: KODI::RETRO::CRPRendererOpenGLES Class Reference
KODI::RETRO::CRPRendererOpenGLES Class Reference
#include <RPRendererOpenGLES.h>
Public Member Functions
CRPRendererOpenGLES (const CRenderSettings &renderSettings, CRenderContext &context, std::shared_ptr< IRenderBufferPool > bufferPool)
~CRPRendererOpenGLES () override
bool Supports (RENDERFEATURE feature) const override
SCALINGMETHOD GetDefaultScalingMethod () const override
Public Member Functions inherited from KODI::RETRO::CRPBaseRenderer
CRPBaseRenderer (const CRenderSettings &renderSettings, CRenderContext &context, std::shared_ptr< IRenderBufferPool > bufferPool)
virtual ~CRPBaseRenderer ()
IRenderBufferPool * GetBufferPool ()
Get the buffer pool used by this renderer.
bool Configure (AVPixelFormat format)
void FrameMove ()
void PreRender (bool clear)
Performs whatever necessary before rendering the frame.
void SetBuffer (IRenderBuffer *buffer)
void RenderFrame (bool clear, uint8_t alpha)
bool IsCompatible (const CRenderVideoSettings &settings) const
virtual void Flush ()
const CRenderSettings & GetRenderSettings () const
void SetScalingMethod (SCALINGMETHOD method)
void SetStretchMode (STRETCHMODE stretchMode)
void SetRenderRotation (unsigned int rotationDegCCW)
void SetPixels (const std::string &pixelPath)
bool IsVisible () const
IRenderBuffer * GetRenderBuffer () const
Static Public Member Functions
static bool SupportsScalingMethod (SCALINGMETHOD method)
Protected Member Functions
void RenderInternal (bool clear, uint8_t alpha) override
void FlushInternal () override
void ClearBackBuffer ()
Set the entire backbuffer to black.
void DrawBlackBars ()
Draw black bars around the video quad.
virtual void Render (uint8_t alpha)
Protected Member Functions inherited from KODI::RETRO::CRPBaseRenderer
virtual bool ConfigureInternal ()
Protected Attributes
GLuint m_mainIndexVBO
GLuint m_mainVertexVBO
GLuint m_blackbarsVertexVBO
GLenum m_textureTarget = GL_TEXTURE_2D
float m_clearColour = 0.0f
Protected Attributes inherited from KODI::RETRO::CRPBaseRenderer
CRenderContext & m_context
std::shared_ptr< IRenderBufferPool > m_bufferPool
bool m_bConfigured = false
AVPixelFormat m_format = AV_PIX_FMT_NONE
CRenderSettings m_renderSettings
IRenderBuffer * m_renderBuffer = nullptr
CRect m_sourceRect
std::array< CPoint, 4 > m_rotatedDestCoords {}
Constructor & Destructor Documentation
CRPRendererOpenGLES()
CRPRendererOpenGLES::CRPRendererOpenGLES (const CRenderSettings & renderSettings, CRenderContext & context, std::shared_ptr< IRenderBufferPool > bufferPool)
References m_blackbarsVertexVBO, m_mainIndexVBO, and m_mainVertexVBO.
~CRPRendererOpenGLES()
CRPRendererOpenGLES::~CRPRendererOpenGLES () override
References m_blackbarsVertexVBO, m_mainIndexVBO, and m_mainVertexVBO.
Member Function Documentation
ClearBackBuffer()
void CRPRendererOpenGLES::ClearBackBuffer () protected
Set the entire backbuffer to black.
References m_clearColour.
Referenced by RenderInternal().
DrawBlackBars()
void CRPRendererOpenGLES::DrawBlackBars () protected
Draw black bars around the video quad.
This is more efficient than glClear() since it only sets pixels to black that aren't going to be overwritten by the game.
References DEFAULT, KODI::RETRO::CRenderContext::DisableGUIShader(), KODI::RETRO::CRenderContext::EnableGUIShader(), KODI::RETRO::CRenderContext::GetScreenHeight(), KODI::RETRO::CRenderContext::GetScreenWidth(), KODI::RETRO::CRenderContext::GUIShaderGetDepth(), KODI::RETRO::CRenderContext::GUIShaderGetPos(), KODI::RETRO::CRenderContext::GUIShaderGetUniCol(), m_blackbarsVertexVBO, m_clearColour, KODI::RETRO::CRPBaseRenderer::m_context, and KODI::RETRO::CRPBaseRenderer::m_rotatedDestCoords.
Referenced by RenderInternal().
FlushInternal()
void CRPRendererOpenGLES::FlushInternal () override protected virtual
Reimplemented from KODI::RETRO::CRPBaseRenderer.
References KODI::RETRO::CRPBaseRenderer::m_bConfigured.
GetDefaultScalingMethod()
SCALINGMETHOD KODI::RETRO::CRPRendererOpenGLES::GetDefaultScalingMethod () const inline override virtual
Implements KODI::RETRO::CRPBaseRenderer.
References KODI::RETRO::NEAREST.
Render()
void CRPRendererOpenGLES::Render (uint8_t alpha) protected virtual
Reimplemented in KODI::RETRO::CRPRendererDMA.
References KODI::UTILS::GL::A, KODI::UTILS::GL::B, color, KODI::RETRO::CRenderContext::DisableGUIShader(), KODI::RETRO::CRenderContext::EnableGUIShader(), KODI::UTILS::GL::G, KODI::UTILS::GL::GetChannelFromARGB(), KODI::RETRO::IRenderBuffer::GetHeight(), KODI::RETRO::CRPBaseRenderer::GetRenderSettings(), KODI::RETRO::IRenderBuffer::GetWidth(), KODI::RETRO::CRenderContext::GUIShaderGetCoord0(), KODI::RETRO::CRenderContext::GUIShaderGetDepth(), KODI::RETRO::CRenderContext::GUIShaderGetPos(), KODI::RETRO::CRenderContext::GUIShaderGetUniCol(), KODI::RETRO::LINEAR, KODI::RETRO::CRPBaseRenderer::m_context, m_mainIndexVBO, m_mainVertexVBO, KODI::RETRO::CRPBaseRenderer::m_renderBuffer, KODI::RETRO::CRPBaseRenderer::m_rotatedDestCoords, KODI::RETRO::CRPBaseRenderer::m_sourceRect, m_textureTarget, KODI::UTILS::GL::R, TEXTURE_NOALPHA, KODI::RETRO::CRenderBufferOpenGLES::TextureID(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by RenderInternal().
RenderInternal()
void CRPRendererOpenGLES::RenderInternal (bool clear, uint8_t alpha) override protected virtual
Implements KODI::RETRO::CRPBaseRenderer.
References ClearBackBuffer(), DrawBlackBars(), and Render().
Supports()
bool CRPRendererOpenGLES::Supports (RENDERFEATURE feature) const override virtual
Implements KODI::RETRO::CRPBaseRenderer.
References KODI::RETRO::PIXEL_RATIO, KODI::RETRO::ROTATION, KODI::RETRO::STRETCH, and KODI::RETRO::ZOOM.
SupportsScalingMethod()
bool CRPRendererOpenGLES::SupportsScalingMethod (SCALINGMETHOD method) static
References KODI::RETRO::LINEAR, and KODI::RETRO::NEAREST.
Referenced by KODI::RETRO::CRenderBufferPoolDMA::IsCompatible(), and KODI::RETRO::CRenderBufferPoolOpenGLES::IsCompatible().
Member Data Documentation
m_blackbarsVertexVBO
GLuint KODI::RETRO::CRPRendererOpenGLES::m_blackbarsVertexVBO protected
Referenced by CRPRendererOpenGLES(), DrawBlackBars(), and ~CRPRendererOpenGLES().
m_clearColour
float KODI::RETRO::CRPRendererOpenGLES::m_clearColour = 0.0f protected
Referenced by ClearBackBuffer(), and DrawBlackBars().
m_mainIndexVBO
GLuint KODI::RETRO::CRPRendererOpenGLES::m_mainIndexVBO protected
Referenced by CRPRendererOpenGLES(), Render(), KODI::RETRO::CRPRendererDMA::Render(), and ~CRPRendererOpenGLES().
m_mainVertexVBO
GLuint KODI::RETRO::CRPRendererOpenGLES::m_mainVertexVBO protected
Referenced by CRPRendererOpenGLES(), Render(), KODI::RETRO::CRPRendererDMA::Render(), and ~CRPRendererOpenGLES().
m_textureTarget
GLenum KODI::RETRO::CRPRendererOpenGLES::m_textureTarget = GL_TEXTURE_2D protected
Referenced by Render(), and KODI::RETRO::CRPRendererDMA::Render().
The documentation for this class was generated from the following files:
RPRendererOpenGLES.h
RPRendererOpenGLES.cpp