Kodi Documentation: JSONRPC::CFileOperations Class Reference
JSONRPC::CFileOperations Class Reference
#include <FileOperations.h>
Static Public Member Functions
static JSONRPC_STATUS GetRootDirectory (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetDirectory (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetFileDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetFileDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS PrepareDownload (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Download (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static bool FillFileItem (const std::shared_ptr< CFileItem > &originalItem, std::shared_ptr< CFileItem > &item, const std::string &media="", const CVariant &parameterObject=CVariant(CVariant::VariantTypeArray))
static bool FillFileItemList (const CVariant &parameterObject, CFileItemList &list)
Static Public Member Functions inherited from JSONRPC::CJSONUtils
static void MillisecondsToTimeObject (int time, CVariant &result)
Additional Inherited Members
Static Protected Member Functions inherited from JSONRPC::CFileItemHandler
static void FillDetails (const ISerializable *info, const std::shared_ptr< CFileItem > &item, std::set< std::string > &fields, CVariant &result, CThumbLoader *thumbLoader=nullptr)
static void HandleFileItemList (const char *ID, bool allowFile, const char *resultname, CFileItemList &items, const CVariant &parameterObject, CVariant &result, bool sortLimit=true)
static void HandleFileItemList (const char *ID, bool allowFile, const char *resultname, CFileItemList &items, const CVariant &parameterObject, CVariant &result, int size, bool sortLimit=true)
static void HandleFileItem (const char *ID, bool allowFile, const char *resultname, const std::shared_ptr< CFileItem > &item, const CVariant &parameterObject, const CVariant &validFields, CVariant &result, bool append=true, CThumbLoader *thumbLoader=nullptr)
static void HandleFileItem (const char *ID, bool allowFile, const char *resultname, const std::shared_ptr< CFileItem > &item, const CVariant &parameterObject, const std::set< std::string > &validFields, CVariant &result, bool append=true, CThumbLoader *thumbLoader=nullptr)
static bool FillFileItemList (const CVariant &parameterObject, CFileItemList &list)
Static Protected Member Functions inherited from JSONRPC::CJSONUtils
static void HandleLimits (const CVariant &parameterObject, CVariant &result, int size, int &start, int &end)
static bool ParseSorting (const CVariant &parameterObject, SortBy &sortBy, SortOrder &sortOrder, SortAttribute &sortAttributes)
static void ParseLimits (const CVariant &parameterObject, int &limitStart, int &limitEnd)
static bool ParameterExists (const CVariant &parameterObject, const std::string &key, unsigned int position)
Checks if the given object contains a parameter.
static bool IsValueMember (const CVariant &value, const std::string &key)
Checks if the given object contains a value with the given key.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position)
Returns the json value of a parameter.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position, const CVariant &fallback)
Returns the json value of a parameter or the given default value.
static std::string GetString (const CVariant &value, const char *defaultValue)
Returns the given json value as a string.
static TransportLayerCapability StringToTransportLayer (const std::string &transport)
Returns a TransportLayerCapability value of the given string representation.
static JSONSchemaType StringToSchemaValueType (const std::string &valueType)
Returns a JSONSchemaType value for the given string representation.
static std::string SchemaValueTypeToString (JSONSchemaType valueType)
Returns a string representation for the given JSONSchemaType.
static void SchemaValueTypeToJson (JSONSchemaType valueType, CVariant &jsonObject)
Converts the given json schema type into a json object.
static const char * ValueTypeToString (CVariant::VariantType valueType)
static bool IsParameterType (const CVariant &parameterObject, const char *key, unsigned int position, JSONSchemaType valueType)
Checks if the parameter with the given name or at the given position is of a certain type.
static bool IsType (const CVariant &value, JSONSchemaType valueType)
Checks if the given json value is of the given type.
static void SetDefaultValue (CVariant &value, JSONSchemaType valueType)
Sets the value of the given json value to the default value of the given type.
static bool HasType (JSONSchemaType typeObject, JSONSchemaType type)
static bool ParameterNotNull (const CVariant &parameterObject, const std::string &key)
static void CopyStringArray (const CVariant &jsonStringArray, std::vector< std::string > &stringArray)
Copies the values from the jsonStringArray to the stringArray. stringArray is cleared.
static void SetFromDBDate (const CVariant &jsonDate, CDateTime &date)
static void SetFromDBDateTime (const CVariant &jsonDate, CDateTime &date)
static bool GetXspFiltering (const std::string &type, const CVariant &filter, std::string &xsp)
Member Function Documentation
Download()
JSONRPC_STATUS CFileOperations::Download (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ITransportLayer::Download(), JSONRPC::InvalidParams, and JSONRPC::OK.
FillFileItem()
bool CFileOperations::FillFileItem (const std::shared_ptr< CFileItem > & originalItem, std::shared_ptr< CFileItem > & item, const std::string & media = "", const CVariant & parameterObject = CVariant(CVariant::VariantTypeArray)) static
References XFILE::CDirectory::Exists(), CFileUtils::Exists(), JSONRPC::CAudioLibrary::FillFileItem(), JSONRPC::CVideoLibrary::FillFileItem(), URIUtils::GetFileName(), CUtil::GetTitleFromPath(), and label.
Referenced by FillFileItemList(), GetDirectory(), and GetFileDetails().
FillFileItemList()
bool CFileOperations::FillFileItemList (const CVariant & parameterObject, CFileItemList & list) static
References CFileItemList::Add(), CVariant::asString(), XFILE::DIR_FLAG_DEFAULTS, CUtil::ExcludeFileOrFolder(), FillFileItem(), FillFileItemList(), XFILE::CDirectory::GetDirectory(), CServiceBroker::GetFileExtensionProvider(), CFileExtensionProvider::GetMusicExtensions(), CFileItem::GetPath(), CFileExtensionProvider::GetPictureExtensions(), CServiceBroker::GetSettingsComponent(), CFileExtensionProvider::GetVideoExtensions(), CFileItem::HasMusicInfoTag(), CVariant::isBoolean(), CVariant::isMember(), KODI::PLAYLIST::IsPlayList(), KODI::PLAYLIST::IsSmartPlayList(), URIUtils::IsUPnP(), CFileItemList::Size(), CFileItemList::Sort(), SortByFile, and SortOrderAscending.
Referenced by JSONRPC::CFileItemHandler::FillFileItemList(), and FillFileItemList().
GetDirectory()
JSONRPC_STATUS CFileOperations::GetDirectory (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CFileItemList::Add(), CVariant::append(), CVariant::asString(), XFILE::DIR_FLAG_DEFAULTS, CVariant::end_array(), CUtil::ExcludeFileOrFolder(), FillFileItem(), JSONRPC::CAudioLibrary::GetAdditionalDetails(), JSONRPC::CVideoLibrary::GetDetailsFromJsonParameters(), XFILE::CDirectory::GetDirectory(), CServiceBroker::GetFileExtensionProvider(), CFileExtensionProvider::GetMusicExtensions(), CFileItem::GetPath(), CFileExtensionProvider::GetPictureExtensions(), CServiceBroker::GetSettingsComponent(), CFileExtensionProvider::GetVideoExtensions(), CURL::GetWithoutUserDetails(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::InvalidParams, CVariant::isMember(), URIUtils::IsUPnP(), JSONRPC::OK, CFileUtils::RemoteAccessAllowed(), CFileItem::SetPath(), CGUIListItem::SetProperty(), CFileItemList::Size(), and CVariant::VariantTypeArray.
GetFileDetails()
JSONRPC_STATUS CFileOperations::GetFileDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::append(), CVariant::asString(), CFileItemList::Contains(), XFILE::DIR_FLAG_DEFAULTS, CVariant::end_array(), CFileUtils::Exists(), FillFileItem(), CFileItemList::Get(), XFILE::CDirectory::GetDirectory(), URIUtils::GetDirectory(), JSONRPC::CFileItemHandler::HandleFileItem(), JSONRPC::InvalidParams, CVariant::isMember(), URIUtils::IsUPnP(), JSONRPC::OK, CFileUtils::RemoteAccessAllowed(), and CVariant::VariantTypeArray.
GetRootDirectory()
JSONRPC_STATUS CFileOperations::GetRootDirectory (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CFileItemList::Add(), CVariant::append(), CVariant::asString(), CMediaSourceSettings::GetInstance(), CMediaSourceSettings::GetSources(), CURL::GetWithoutUserDetails(), JSONRPC::CFileItemHandler::HandleFileItemList(), LOCK_STATE_LOCKED, JSONRPC::OK, CFileItem::SetPath(), CFileItemList::Size(), and CVariant::VariantTypeArray.
PrepareDownload()
JSONRPC_STATUS CFileOperations::PrepareDownload (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asString(), JSONRPC::FileDownloadDirect, JSONRPC::ITransportLayer::GetCapabilities(), JSONRPC::InvalidParams, JSONRPC::OK, and JSONRPC::ITransportLayer::PrepareDownload().
SetFileDetails()
JSONRPC_STATUS CFileOperations::SetFileDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVideoDatabase::AddFile(), CVariant::asInteger(), CVariant::asString(), CFileUtils::Exists(), CVideoDatabase::GetFileInfo(), CVideoInfoTag::GetPlayCount(), JSONRPC::InternalError, JSONRPC::InvalidParams, CDateTime::IsValid(), CVideoInfoTag::m_lastPlayed, JSONRPC::CJSONRPCUtils::NotifyItemUpdated(), CVideoDatabase::Open(), CFileUtils::RemoteAccessAllowed(), CDateTime::Reset(), JSONRPC::CJSONUtils::SetFromDBDateTime(), CVideoDatabase::SetPlayCount(), and JSONRPC::CVideoLibrary::UpdateResumePoint().
The documentation for this class was generated from the following files:
FileOperations.h
FileOperations.cpp