Kodi Documentation: class PVRTypeIntValue
class PVRTypeIntValue
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 1. General
PVR add-on int type value
Representation of a <int, std::string> value.
Modules
Value Help
Classes
class kodi::addon::PVRTypeIntValue
Functions
kodi::addon::PVRTypeIntValue::PVRTypeIntValue ()=default
Default class constructor.
kodi::addon::PVRTypeIntValue::PVRTypeIntValue (int value, const std::string &description)
Class constructor with integrated value set.
void kodi::addon::PVRTypeIntValue::SetValue (int value)
To set with the identification value.
int kodi::addon::PVRTypeIntValue::GetValue () const
To get with the identification value.
void kodi::addon::PVRTypeIntValue::SetDescription (const std::string &description)
To set with the description text of the value.
std::string kodi::addon::PVRTypeIntValue::GetDescription () const
To get with the description text of the value.
Detailed Description
PVR add-on int type value
Representation of a <int, std::string> value.
The following table contains values that can be set with class PVRTypeIntValue :
Name Type Set call Get call
Value int SetValue GetValue
Description std::string SetDescription GetDescription
Remarks
Further can there be used his class constructor to set values.
Function Documentation
GetDescription()
std::string kodi::addon::PVRTypeIntValue::GetDescription () const inline
To get with the description text of the value.
References kodi::addon::DynamicCStructHdl< PVRTypeIntValue, PVR_ATTRIBUTE_INT_VALUE >::m_cStructure, and PVR_ATTRIBUTE_INT_VALUE::strDescription.
GetValue()
int kodi::addon::PVRTypeIntValue::GetValue () const inline
To get with the identification value.
References PVR_ATTRIBUTE_INT_VALUE::iValue, and kodi::addon::DynamicCStructHdl< PVRTypeIntValue, PVR_ATTRIBUTE_INT_VALUE >::m_cStructure.
PVRTypeIntValue() [1/2]
kodi::addon::PVRTypeIntValue::PVRTypeIntValue () default
Default class constructor.
PVRTypeIntValue() [2/2]
kodi::addon::PVRTypeIntValue::PVRTypeIntValue (int value, const std::string & description) inline
Class constructor with integrated value set.
Parameters
[in] value Type identification value
[in] description Type description text
References kodi::addon::PVRTypeIntValue::SetDescription(), kodi::addon::PVRTypeIntValue::SetValue(), and value.
SetDescription()
void kodi::addon::PVRTypeIntValue::SetDescription (const std::string & description) inline
To set with the description text of the value.
References kodi::addon::DynamicCStructHdl< PVRTypeIntValue, PVR_ATTRIBUTE_INT_VALUE >::m_cStructure, kodi::addon::ReallocAndCopyString(), and PVR_ATTRIBUTE_INT_VALUE::strDescription.
Referenced by kodi::addon::PVRTypeIntValue::PVRTypeIntValue().
SetValue()
void kodi::addon::PVRTypeIntValue::SetValue (int value) inline
To set with the identification value.
References PVR_ATTRIBUTE_INT_VALUE::iValue, kodi::addon::DynamicCStructHdl< PVRTypeIntValue, PVR_ATTRIBUTE_INT_VALUE >::m_cStructure, and value.
Referenced by kodi::addon::PVRTypeIntValue::PVRTypeIntValue().