Kodi Documentation: CContextButtons Class Reference
CContextButtons Class Reference
#include <GUIDialogContextMenu.h>
Public Member Functions
void Add (unsigned int, const std::string &label)
void Add (unsigned int, int label)
Member Function Documentation
Add() [1/2]
void CContextButtons::Add (unsigned int button, const std::string & label)
References label, and push_back().
Referenced by anonymous_namespace{GUIWindowPVRGuide.cpp}::CContextMenuFunctions< A >::Add(), CGUIDialogVideoBookmarks::AddEpisodeBookmark(), KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::ChoosePlayOrResume(), XBMCAddon::xbmcgui::Dialog::contextmenu(), CGUIDialogContextMenu::GetContextButtons(), CGUIWindowEventLog::GetContextButtons(), KODI::GAME::CGUIWindowGames::GetContextButtons(), CGUIWindowMusicBase::GetContextButtons(), CGUIWindowMusicNav::GetContextButtons(), CGUIWindowMusicPlayList::GetContextButtons(), CGUIWindowPictures::GetContextButtons(), PVR::CGUIWindowPVRChannelsBase::GetContextButtons(), PVR::CGUIWindowPVRGuideBase::GetContextButtons(), PVR::CGUIWindowPVRRecordingsBase::GetContextButtons(), PVR::CGUIWindowPVRSearchBase::GetContextButtons(), CGUIWindowVideoBase::GetContextButtons(), CGUIWindowVideoNav::GetContextButtons(), CGUIWindowVideoPlaylist::GetContextButtons(), CGUIDialogVideoInfo::ManageVideoItem(), PVR::CGUIWindowPVRChannelsBase::OnContextButtonManage(), KODI::GAME::CDialogGameSaves::OnContextMenu(), KODI::GAME::CDialogInGameSaves::OnMenuAction(), CGUIWindowMusicPlaylistEditor::OnPlaylistContext(), CGUIDialogFileBrowser::OnPopupMenu(), CGUIWindowSettingsProfile::OnPopupMenu(), PVR::CGUIDialogPVRChannelManager::OnPopupMenu(), CGUIWindowLoginScreen::OnPopupMenu(), CGUIWindowFileManager::OnPopupMenu(), CGUIDialogSmartPlaylistEditor::OnPopupMenu(), CGUIDialogVideoBookmarks::OnPopupMenu(), PVR::CGUIDialogPVRGroupManager::OnPopupMenu(), CGUIWindowMusicBase::OnSelect(), CGUIWindowMusicPlaylistEditor::OnSourcesContext(), CGUIDialogSubtitles::OnSubtitleServiceContextMenu(), ADDON::Interface_GUIDialogContextMenu::open(), CPlayerCoreFactory::SelectPlayerDialog(), CONTEXTMENU::ShowFor(), and CGUIDialogContextMenu::SwitchMedia().
Add() [2/2]
void CContextButtons::Add (unsigned int button, int label)
References g_localizeStrings, CLocalizeStrings::Get(), label, and push_back().
The documentation for this class was generated from the following files:
GUIDialogContextMenu.h
GUIDialogContextMenu.cpp