Kodi Documentation: CMediaManager Class Reference
CMediaManager Class Reference
#include <MediaManager.h>
Public Member Functions
CMediaManager ()
void Initialize ()
void Stop ()
bool LoadSources ()
bool SaveSources ()
void GetLocalDrives (std::vector< CMediaSource > &localDrives, bool includeQ=true)
void GetRemovableDrives (std::vector< CMediaSource > &removableDrives)
void GetNetworkLocations (std::vector< CMediaSource > &locations, bool autolocations=true)
bool AddNetworkLocation (const std::string &path)
bool HasLocation (const std::string &path) const
bool RemoveLocation (const std::string &path)
bool SetLocationPath (const std::string &oldPath, const std::string &newPath)
void AddAutoSource (const CMediaSource &share, bool bAutorun=false)
void RemoveAutoSource (const CMediaSource &share)
bool IsDiscInDrive (const std::string &devicePath="")
bool IsAudio (const std::string &devicePath="")
bool HasOpticalDrive ()
std::string TranslateDevicePath (const std::string &devicePath, bool bReturnAsDevice=false)
DriveState GetDriveStatus (const std::string &devicePath="")
std::string GetDiscPath ()
void SetHasOpticalDrive (bool bstatus)
bool Eject (const std::string &mountpath)
void EjectTray (const bool bEject=true, const char cDriveLetter='\0')
void CloseTray (const char cDriveLetter='\0')
void ToggleTray (const char cDriveLetter='\0')
void ProcessEvents ()
std::vector< std::string > GetDiskUsage ()
void OnStorageAdded (const MEDIA_DETECT::STORAGE::StorageDevice &device) override
Callback executed when a new storage device is added.
void OnStorageSafelyRemoved (const MEDIA_DETECT::STORAGE::StorageDevice &device) override
Callback executed when a new storage device is safely removed.
void OnStorageUnsafelyRemoved (const MEDIA_DETECT::STORAGE::StorageDevice &device) override
Callback executed when a new storage device is unsafely removed.
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
bool playStubFile (const CFileItem &item)
Public Member Functions inherited from IStorageEventsCallback
virtual ~IStorageEventsCallback ()=default
Public Member Functions inherited from IJobCallback
virtual ~IJobCallback ()=default
Destructor for job call back objects.
virtual void OnJobAbort (unsigned int jobID, CJob *job)
An optional callback function used when a job will be aborted.
virtual void OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob *job)
An optional callback function that a job may call while processing.
Protected Attributes
std::vector< CNetworkLocation > m_locations
CCriticalSection m_muAutoSource
CCriticalSection m_CritSecStorageProvider
bool m_bhasoptical
std::string m_strFirstAvailDrive
Private Member Functions
void LoadAddonSources () const
Loads the addon sources for the different supported browsable addon types.
CMediaSource GetRootAddonTypeSource (const std::string &type) const
Get the addons root source for the given content type.
CMediaSource ComputeRootAddonTypeSource (const std::string &type, const std::string &label, const std::string &thumb) const
Generate the addons source for the given content type.
UTILS::DISCS::DiscInfo GetDiscInfo (const std::string &mediaPath)
void RemoveDiscInfo (const std::string &devicePath)
Private Attributes
std::unique_ptr< IStorageProvider > m_platformStorage
std::map< std::string, UTILS::DISCS::DiscInfo > m_mapDiscInfo
Constructor & Destructor Documentation
CMediaManager()
CMediaManager::CMediaManager ()
References m_bhasoptical.
Member Function Documentation
AddAutoSource()
void CMediaManager::AddAutoSource (const CMediaSource & share, bool bAutorun = false)
References CMediaSourceSettings::AddShare(), CServiceBroker::GetGUI(), CMediaSourceSettings::GetInstance(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE_SOURCES, and CMediaSource::strPath.
Referenced by CDetectDisc::DoWork().
AddNetworkLocation()
bool CMediaManager::AddNetworkLocation (const std::string & path)
References CNetworkLocation::id, m_locations, CNetworkLocation::path, and SaveSources().
Referenced by CGUIDialogFileBrowser::OnAddNetworkLocation().
CloseTray()
void CMediaManager::CloseTray (const char cDriveLetter = '\0')
References TranslateDevicePath().
ComputeRootAddonTypeSource()
CMediaSource CMediaManager::ComputeRootAddonTypeSource (const std::string & type, const std::string & label, const std::string & thumb) const private
Generate the addons source for the given content type.
Parameters
type the type of addon content desired
label the name of the addons source
thumb image to use as the icon
Returns
the given CMediaSource for the addon root directory
References label, CMediaSource::m_iDriveType, CMediaSource::m_ignore, CMediaSource::m_strThumbnailImage, CMediaSource::SOURCE_TYPE_VPATH, CMediaSource::strName, and CMediaSource::strPath.
Referenced by GetRootAddonTypeSource().
Eject()
bool CMediaManager::Eject (const std::string & mountpath)
References m_CritSecStorageProvider, and m_platformStorage.
Referenced by CONTEXTMENU::CEjectDrive::Execute(), and CGUIDialogContextMenu::OnContextButton().
EjectTray()
void CMediaManager::EjectTray (const bool bEject = true, const char cDriveLetter = '\0')
References TranslateDevicePath().
Referenced by KODI::CDRIP::CCDDARipJob::DoWork().
GetDiscInfo()
UTILS::DISCS::DiscInfo CMediaManager::GetDiscInfo (const std::string & mediaPath) private
References URIUtils::AddFileToFolder(), CFileUtils::Exists(), UTILS::DISCS::ProbeBlurayDiscInfo(), UTILS::DISCS::ProbeDVDDiscInfo(), and TranslateDevicePath().
GetDiscPath()
std::string CMediaManager::GetDiscPath ()
GetDiskUsage()
std::vector< std::string > CMediaManager::GetDiskUsage ()
References m_CritSecStorageProvider, and m_platformStorage.
Referenced by CGUIWindowSystemInfo::FrameMove().
GetDriveStatus()
DriveState CMediaManager::GetDriveStatus (const std::string & devicePath = "")
References m_bhasoptical, NOT_READY, and TranslateDevicePath().
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), XBMCAddon::xbmc::getDVDState(), and CWin32StorageProvider::Initialize().
GetLocalDrives()
void CMediaManager::GetLocalDrives (std::vector< CMediaSource > & localDrives, bool includeQ = true)
References m_CritSecStorageProvider, and m_platformStorage.
Referenced by CGUIDialogVideoManagerExtras::AddVideoExtra(), CGUIDialogVideoManagerVersions::AddVideoVersionFilePicker(), XBMCAddon::xbmcgui::Dialog::browseMultiple(), XBMCAddon::xbmcgui::Dialog::browseSingle(), FAVOURITES_UTILS::ChooseAndSetNewThumbnail(), PVR::CPVRGUIActionsEPG::ChooseIconForSavedSearch(), ExportLibrary(), CGUIControlButtonSetting::GetPath(), ADDON::Interface_GUIDialogFileBrowser::GetVECShares(), CGUIWindowAddonBrowser::InstallFromZip(), CGUIDialogVideoInfo::ManageVideoItemArtwork(), CGUIDialogSmartPlaylistRule::OnBrowse(), PVR::CGUIDialogPVRChannelManager::OnClickButtonChannelLogo(), CGUIDialogContextMenu::OnContextButton(), CGUIDialogMusicInfo::OnGetArt(), CGUIDialogSongInfo::OnGetArt(), CGUIDialogInfoProviderSettings::OnSettingAction(), CGUIDialogProfileSettings::OnSettingAction(), CGUIDialogLibExportSettings::OnSettingAction(), CDisplaySettings::OnSettingAction(), CMediaSettings::OnSettingAction(), SetFile(), SetImage(), SetPath(), CGUIDialogFileBrowser::SetSources(), CGUIDialogFileBrowser::ShowAndGetFile(), and CGUIDialogFileBrowser::ShowAndGetSource().
GetNetworkLocations()
void CMediaManager::GetNetworkLocations (std::vector< CMediaSource > & locations, bool autolocations = true)
References g_localizeStrings, CLocalizeStrings::Get(), ADDON::CVFSAddonCache::GetAddonInstances(), CLocalizeStrings::GetAddonString(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetVFSAddonCache(), CURL::GetWithoutUserDetails(), CServiceBroker::IsAddonInterfaceUp(), CMediaSource::m_ignore, m_locations, CSettings::SETTING_SERVICES_UPNP, CMediaSource::strName, and CMediaSource::strPath.
Referenced by CGUIDialogVideoManagerExtras::AddVideoExtra(), CGUIDialogVideoManagerVersions::AddVideoVersionFilePicker(), XBMCAddon::xbmcgui::Dialog::browseMultiple(), XBMCAddon::xbmcgui::Dialog::browseSingle(), ExportLibrary(), CGUIControlButtonSetting::GetPath(), ADDON::Interface_GUIDialogFileBrowser::GetVECShares(), CGUIWindowAddonBrowser::InstallFromZip(), CGUIDialogInfoProviderSettings::OnSettingAction(), CGUIDialogLibExportSettings::OnSettingAction(), CMediaSettings::OnSettingAction(), SetPath(), and CGUIDialogFileBrowser::ShowAndGetSource().
GetRemovableDrives()
void CMediaManager::GetRemovableDrives (std::vector< CMediaSource > & removableDrives)
References m_CritSecStorageProvider, and m_platformStorage.
Referenced by CHTTPVfsHandler::CHTTPVfsHandler(), CVideoDatabase::CleanDatabase(), CVideoDatabase::CleanMediaType(), ExportLibrary(), XFILE::CSourcesDirectory::GetDirectory(), XFILE::CVirtualDirectory::GetSources(), ADDON::Interface_GUIDialogFileBrowser::GetVECShares(), CGUIDialogInfoProviderSettings::OnSettingAction(), CGUIDialogLibExportSettings::OnSettingAction(), CMediaSettings::OnSettingAction(), CFileUtils::RemoteAccessAllowed(), and CGUIMediaWindow::Update().
GetRootAddonTypeSource()
CMediaSource CMediaManager::GetRootAddonTypeSource (const std::string & type) const private
Get the addons root source for the given content type.
Parameters
type the type of addon content desired
Returns
the given CMediaSource for the addon root directory
References ComputeRootAddonTypeSource(), g_localizeStrings, CLocalizeStrings::Get(), and LOGERROR.
Referenced by LoadAddonSources().
HasLocation()
bool CMediaManager::HasLocation (const std::string & path) const
References URIUtils::CompareWithoutSlashAtEnd(), and m_locations.
HasOpticalDrive()
bool CMediaManager::HasOpticalDrive ()
References m_strFirstAvailDrive.
Referenced by playStubFile().
Initialize()
void CMediaManager::Initialize ()
References IDiscDriveHandler::CreateInstance(), IStorageProvider::CreateInstance(), m_platformStorage, and m_strFirstAvailDrive.
IsAudio()
bool CMediaManager::IsAudio (const std::string & devicePath = "")
References MEDIA_DETECT::CCdInfo::IsAudio(), and m_bhasoptical.
IsDiscInDrive()
bool CMediaManager::IsDiscInDrive (const std::string & devicePath = "")
References URIUtils::IsDVD(), m_bhasoptical, m_muAutoSource, and TranslateDevicePath().
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), CGUIWindowFileManager::OnSort(), and CApplication::PlaybackCleanup().
LoadAddonSources()
void CMediaManager::LoadAddonSources () const private
Loads the addon sources for the different supported browsable addon types.
References CMediaSourceSettings::AddShare(), CMediaSourceSettings::GetInstance(), GetRootAddonTypeSource(), and CServiceBroker::GetSettingsComponent().
Referenced by LoadSources().
LoadSources()
bool CMediaManager::LoadSources ()
References CNetworkLocation::id, LoadAddonSources(), CXBMCTinyXML2::LoadFile(), CLog::Log(), LOGERROR, m_locations, MEDIA_SOURCES_XML, and CNetworkLocation::path.
Referenced by CApplication::Initialize().
OnJobComplete()
void CMediaManager::OnJobComplete (unsigned int jobID, bool success, CJob * job) inline override virtual
The callback used when a job completes.
OnJobComplete is called at the completion of the job's DoWork() function, and is used to return information to the caller on the result of the job. On returning form this function the CJobManager will destroy this job.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
success the result from the DoWork call
job the job that has been processed. The job will be destroyed after this function returns
See also
CJobManager and CJob
Implements IJobCallback.
OnStorageAdded()
void CMediaManager::OnStorageAdded (const MEDIA_DETECT::STORAGE::StorageDevice & device) override virtual
Callback executed when a new storage device is added.
See also
IStorageEventsCallback
Parameters
device the storage device
Implements IStorageEventsCallback.
References g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetJobManager(), CServiceBroker::GetSettingsComponent(), CGUIDialogKaiToast::Info, MEDIA_DETECT::STORAGE::StorageDevice::label, CLog::Log(), LOGDEBUG, MEDIA_DETECT::STORAGE::OPTICAL, MEDIA_DETECT::STORAGE::StorageDevice::path, CJob::PRIORITY_HIGH, CJob::PRIORITY_LOW, CGUIDialogKaiToast::QueueNotification(), CSettings::SETTING_AUDIOCDS_AUTOACTION, CSettings::SETTING_DVDS_AUTORUN, TOAST_DISPLAY_TIME, and MEDIA_DETECT::STORAGE::StorageDevice::type.
OnStorageSafelyRemoved()
void CMediaManager::OnStorageSafelyRemoved (const MEDIA_DETECT::STORAGE::StorageDevice & device) override virtual
Callback executed when a new storage device is safely removed.
See also
IStorageEventsCallback
Parameters
device the storage device
Implements IStorageEventsCallback.
References g_localizeStrings, CLocalizeStrings::Get(), CGUIDialogKaiToast::Info, MEDIA_DETECT::STORAGE::StorageDevice::label, CGUIDialogKaiToast::QueueNotification(), and TOAST_DISPLAY_TIME.
OnStorageUnsafelyRemoved()
void CMediaManager::OnStorageUnsafelyRemoved (const MEDIA_DETECT::STORAGE::StorageDevice & device) override virtual
Callback executed when a new storage device is unsafely removed.
See also
IStorageEventsCallback
Parameters
device the storage device
Implements IStorageEventsCallback.
References g_localizeStrings, CLocalizeStrings::Get(), MEDIA_DETECT::STORAGE::StorageDevice::label, CGUIDialogKaiToast::QueueNotification(), and CGUIDialogKaiToast::Warning.
playStubFile()
bool CMediaManager::playStubFile (const CFileItem & item)
References g_localizeStrings, CLocalizeStrings::Get(), CGUIListItem::GetLabel(), CFileItem::GetPath(), XMLUtils::GetString(), HasOpticalDrive(), CXBMCTinyXML2::LoadFile(), CLog::Log(), LOGINFO, CGUIDialogPlayEject::ShowAndGetInput(), and KODI::MESSAGING::HELPERS::ShowOKDialogText().
Referenced by CApplication::PlayFile().
ProcessEvents()
void CMediaManager::ProcessEvents ()
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE_SOURCES, m_CritSecStorageProvider, m_platformStorage, and m_strFirstAvailDrive.
Referenced by CApplication::ProcessSlow().
RemoveAutoSource()
void CMediaManager::RemoveAutoSource (const CMediaSource & share)
References CMediaSourceSettings::DeleteSource(), CServiceBroker::GetGUI(), CMediaSourceSettings::GetInstance(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE_SOURCES, RemoveDiscInfo(), CMediaSource::strName, CMediaSource::strPath, and TranslateDevicePath().
Referenced by CWIN32Util::ToggleTray(), and CWinEventsWin32::WndProc().
RemoveDiscInfo()
void CMediaManager::RemoveDiscInfo (const std::string & devicePath) private
References m_mapDiscInfo, and TranslateDevicePath().
Referenced by RemoveAutoSource().
RemoveLocation()
bool CMediaManager::RemoveLocation (const std::string & path)
References URIUtils::CompareWithoutSlashAtEnd(), m_locations, and SaveSources().
Referenced by CGUIDialogFileBrowser::OnPopupMenu().
SaveSources()
bool CMediaManager::SaveSources ()
References m_locations, MEDIA_SOURCES_XML, CXBMCTinyXML2::SaveFile(), and value.
Referenced by AddNetworkLocation(), RemoveLocation(), and SetLocationPath().
SetHasOpticalDrive()
void CMediaManager::SetHasOpticalDrive (bool bstatus)
References m_bhasoptical, and m_muAutoSource.
Referenced by CWin32StorageProvider::Initialize(), and CStorageProvider::Initialize().
SetLocationPath()
bool CMediaManager::SetLocationPath (const std::string & oldPath, const std::string & newPath)
References URIUtils::CompareWithoutSlashAtEnd(), m_locations, and SaveSources().
Referenced by CGUIDialogFileBrowser::OnPopupMenu().
Stop()
void CMediaManager::Stop ()
References m_platformStorage.
ToggleTray()
void CMediaManager::ToggleTray (const char cDriveLetter = '\0')
References TranslateDevicePath().
Referenced by Eject(), CONTEXTMENU::CEjectDisk::Execute(), and CGUIDialogPlayEject::OnMessage().
TranslateDevicePath()
std::string CMediaManager::TranslateDevicePath (const std::string & devicePath, bool bReturnAsDevice = false)
Todo:
translate cdda://<device>/
References m_bhasoptical, m_muAutoSource, m_strFirstAvailDrive, and URIUtils::RemoveSlashAtEnd().
Referenced by CWIN32Util::CloseTray(), CloseTray(), CDVDFactoryInputStream::CreateInputStream(), EjectTray(), CWIN32Util::EjectTray(), GetDiscInfo(), GetDriveStatus(), IsDiscInDrive(), RemoveAutoSource(), RemoveDiscInfo(), CWIN32Util::ToggleTray(), and ToggleTray().
Member Data Documentation
m_bhasoptical
bool CMediaManager::m_bhasoptical protected
Referenced by CMediaManager(), GetDriveStatus(), IsAudio(), IsDiscInDrive(), SetHasOpticalDrive(), and TranslateDevicePath().
m_CritSecStorageProvider
CCriticalSection CMediaManager::m_CritSecStorageProvider protected
Referenced by Eject(), GetDiskUsage(), GetLocalDrives(), GetRemovableDrives(), and ProcessEvents().
m_locations
std::vector<CNetworkLocation> CMediaManager::m_locations protected
Referenced by AddNetworkLocation(), GetNetworkLocations(), HasLocation(), LoadSources(), RemoveLocation(), SaveSources(), and SetLocationPath().
m_mapDiscInfo
std::map<std::string, UTILS::DISCS::DiscInfo> CMediaManager::m_mapDiscInfo private
Referenced by RemoveDiscInfo().
m_muAutoSource
CCriticalSection CMediaManager::m_muAutoSource protected
Referenced by IsDiscInDrive(), SetHasOpticalDrive(), and TranslateDevicePath().
m_platformStorage
std::unique_ptr<IStorageProvider> CMediaManager::m_platformStorage private
Referenced by Eject(), GetDiskUsage(), GetLocalDrives(), GetRemovableDrives(), Initialize(), ProcessEvents(), and Stop().
m_strFirstAvailDrive
std::string CMediaManager::m_strFirstAvailDrive protected
Referenced by HasOpticalDrive(), Initialize(), ProcessEvents(), and TranslateDevicePath().
The documentation for this class was generated from the following files:
MediaManager.h
MediaManager.cpp