Kodi Documentation: MusicDatabase.cpp File Reference
MusicDatabase.cpp File Reference
#include "MusicDatabase.h"
#include "Album.h"
#include "Artist.h"
#include "FileItem.h"
#include "FileItemList.h"
#include "GUIInfoManager.h"
#include "LangInfo.h"
#include "ServiceBroker.h"
#include "Song.h"
#include "TextureCache.h"
#include "URL.h"
#include "Util.h"
#include "addons/Addon.h"
#include "addons/AddonManager.h"
#include "addons/AddonSystemSettings.h"
#include "addons/Scraper.h"
#include "addons/kodi-dev-kit/include/kodi/c-api/addon-instance/audiodecoder.h"
#include "dbwrappers/dataset.h"
#include "dialogs/GUIDialogKaiToast.h"
#include "dialogs/GUIDialogProgress.h"
#include "dialogs/GUIDialogSelect.h"
#include "events/EventLog.h"
#include "events/NotificationEvent.h"
#include "filesystem/Directory.h"
#include "filesystem/DirectoryCache.h"
#include "filesystem/File.h"
#include "filesystem/MusicDatabaseDirectory/DirectoryNode.h"
#include "guilib/GUIComponent.h"
#include "guilib/GUIWindowManager.h"
#include "guilib/LocalizeStrings.h"
#include "guilib/guiinfo/GUIInfoLabels.h"
#include "imagefiles/ImageFileURL.h"
#include "interfaces/AnnouncementManager.h"
#include "messaging/helpers/DialogHelper.h"
#include "messaging/helpers/DialogOKHelper.h"
#include "music/MusicDbUrl.h"
#include "music/MusicLibraryQueue.h"
#include "music/tags/MusicInfoTag.h"
#include "network/Network.h"
#include "network/cddb.h"
#include "playlists/SmartPlayList.h"
#include "profiles/ProfileManager.h"
#include "settings/AdvancedSettings.h"
#include "settings/MediaSourceSettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "storage/MediaManager.h"
#include "utils/FileUtils.h"
#include "utils/LegacyPathTranslation.h"
#include "utils/MathUtils.h"
#include "utils/Random.h"
#include "utils/StringUtils.h"
#include "utils/URIUtils.h"
#include "utils/XMLUtils.h"
#include "utils/log.h"
#include <inttypes.h>
Classes
struct translateJSONField
Macros
#define RECENTLY_PLAYED_LIMIT 25
#define MIN_FULL_SEARCH_LENGTH 3
Functions
static void AnnounceRemove (const std::string &content, int id)
static void AnnounceUpdate (const std::string &content, int id, bool added=false)
Variables
static const translateJSONField JSONtoDBArtist []
static const size_t NUM_ARTIST_FIELDS = sizeof(JSONtoDBArtist) / sizeof(translateJSONField)
static const translateJSONField JSONtoDBAlbum []
static const size_t NUM_ALBUM_FIELDS = sizeof(JSONtoDBAlbum) / sizeof(translateJSONField)
static const translateJSONField JSONtoDBSong []
static const size_t NUM_SONG_FIELDS = sizeof(JSONtoDBSong) / sizeof(translateJSONField)
Macro Definition Documentation
MIN_FULL_SEARCH_LENGTH
#define MIN_FULL_SEARCH_LENGTH 3
RECENTLY_PLAYED_LIMIT
#define RECENTLY_PLAYED_LIMIT 25
Function Documentation
AnnounceRemove()
static void AnnounceRemove (const std::string & content, int id) static
References ANNOUNCEMENT::AudioLibrary, data(), CServiceBroker::GetAnnouncementManager(), CMusicLibraryQueue::GetInstance(), and id.
Referenced by CMusicDatabase::RemoveSongsFromPath().
AnnounceUpdate()
static void AnnounceUpdate (const std::string & content, int id, bool added = false) static
References ANNOUNCEMENT::AudioLibrary, data(), CServiceBroker::GetAnnouncementManager(), CMusicLibraryQueue::GetInstance(), and id.
Referenced by CMusicDatabase::AddSong(), CMusicDatabase::UpdateAlbum(), CMusicDatabase::UpdateArtist(), CMusicDatabase::UpdateArtistScrapedMBID(), and CMusicDatabase::UpdateSong().
Variable Documentation
JSONtoDBAlbum
const translateJSONField JSONtoDBAlbum[] static
Referenced by CMusicDatabase::GetAlbumsByWhereJSON().
JSONtoDBArtist
const translateJSONField JSONtoDBArtist[] static
Referenced by CMusicDatabase::GetArtistsByWhereJSON().
JSONtoDBSong
const translateJSONField JSONtoDBSong[] static
Referenced by CMusicDatabase::GetSongsByWhereJSON().
NUM_ALBUM_FIELDS
const size_t NUM_ALBUM_FIELDS = sizeof(JSONtoDBAlbum) / sizeof(translateJSONField) static
Referenced by CMusicDatabase::GetAlbumsByWhereJSON().
NUM_ARTIST_FIELDS
const size_t NUM_ARTIST_FIELDS = sizeof(JSONtoDBArtist) / sizeof(translateJSONField) static
Referenced by CMusicDatabase::GetArtistsByWhereJSON().
NUM_SONG_FIELDS
const size_t NUM_SONG_FIELDS = sizeof(JSONtoDBSong) / sizeof(translateJSONField) static
Referenced by CMusicDatabase::GetSongsByWhereJSON().