Kodi Documentation: AddonToKodiFuncTable_kodi_gui_general Struct Reference
AddonToKodiFuncTable_kodi_gui_general Struct Reference
#include <general.h>
Public Attributes
void(* lock)()
void(* unlock)()
int(* get_screen_height)(KODI_HANDLE kodiBase)
int(* get_screen_width)(KODI_HANDLE kodiBase)
int(* get_video_resolution)(KODI_HANDLE kodiBase)
int(* get_current_window_dialog_id)(KODI_HANDLE kodiBase)
int(* get_current_window_id)(KODI_HANDLE kodiBase)
ADDON_HARDWARE_CONTEXT(* get_hw_context)(KODI_HANDLE kodiBase)
AdjustRefreshRateStatus(* get_adjust_refresh_rate_status)(KODI_HANDLE kodiBase)
Member Data Documentation
get_adjust_refresh_rate_status
AdjustRefreshRateStatus(* AddonToKodiFuncTable_kodi_gui_general::get_adjust_refresh_rate_status) (KODI_HANDLE kodiBase)
Referenced by ADDON::Interface_GUIGeneral::Init().
get_current_window_dialog_id
int(* AddonToKodiFuncTable_kodi_gui_general::get_current_window_dialog_id) (KODI_HANDLE kodiBase)
Referenced by ADDON::Interface_GUIGeneral::Init().
get_current_window_id
int(* AddonToKodiFuncTable_kodi_gui_general::get_current_window_id) (KODI_HANDLE kodiBase)
Referenced by ADDON::Interface_GUIGeneral::Init().
get_hw_context
ADDON_HARDWARE_CONTEXT(* AddonToKodiFuncTable_kodi_gui_general::get_hw_context) (KODI_HANDLE kodiBase)
Referenced by ADDON::Interface_GUIGeneral::Init().
get_screen_height
int(* AddonToKodiFuncTable_kodi_gui_general::get_screen_height) (KODI_HANDLE kodiBase)
Referenced by ADDON::Interface_GUIGeneral::Init().
get_screen_width
int(* AddonToKodiFuncTable_kodi_gui_general::get_screen_width) (KODI_HANDLE kodiBase)
Referenced by ADDON::Interface_GUIGeneral::Init().
get_video_resolution
int(* AddonToKodiFuncTable_kodi_gui_general::get_video_resolution) (KODI_HANDLE kodiBase)
Referenced by ADDON::Interface_GUIGeneral::Init().
lock
void(* AddonToKodiFuncTable_kodi_gui_general::lock) ()
Referenced by ADDON::Interface_GUIGeneral::Init().
unlock
void(* AddonToKodiFuncTable_kodi_gui_general::unlock) ()
Referenced by ADDON::Interface_GUIGeneral::Init().
The documentation for this struct was generated from the following file:
kodi-dev-kit/include/kodi/c-api/gui/General.h