Kodi Documentation: anonymous_namespace{Util.cpp} Namespace Reference
anonymous_namespace{Util.cpp} Namespace Reference
Functions
void GetTrailingDiscNumberSegmentInfoFromPath (const std::string &pathIn, size_t &pos, std::string &number)
Variables
static std::map< std::string, std::string > CursorFallbackNameMap
Function Documentation
GetTrailingDiscNumberSegmentInfoFromPath()
void anonymous_namespace{Util.cpp}::GetTrailingDiscNumberSegmentInfoFromPath (const std::string & pathIn, size_t & pos, std::string & number)
References KODI::UTILS::StringUtils::Format(), g_localizeStrings, CLocalizeStrings::Get(), and URIUtils::RemoveSlashAtEnd().
Variable Documentation
CursorFallbackNameMap
std::map<std::string, std::string> anonymous_namespace{Util.cpp}::CursorFallbackNameMap static