Kodi Documentation: ActiveAE::CActiveAESettings Class Reference
ActiveAE::CActiveAESettings Class Reference
#include <ActiveAESettings.h>
Public Member Functions
CActiveAESettings (CActiveAE &ae)
~CActiveAESettings () override
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Static Public Member Functions
static void SettingOptionsAudioDevicesFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
static void SettingOptionsAudioDevicesPassthroughFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
static void SettingOptionsAudioQualityLevelsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void SettingOptionsAudioStreamsilenceFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static bool IsSettingVisible (const std::string &condition, const std::string &value, const std::shared_ptr< const CSetting > &setting, void *data)
Static Protected Member Functions
static void SettingOptionsAudioDevicesFillerGeneral (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, bool passthrough)
Protected Attributes
CActiveAE & m_audioEngine
CCriticalSection m_cs
Static Protected Attributes
static CActiveAESettings * m_instance = nullptr
Constructor & Destructor Documentation
CActiveAESettings()
ActiveAE::CActiveAESettings::CActiveAESettings (CActiveAE & ae)
References CServiceBroker::GetSettingsComponent(), m_cs, m_instance, CSettings::SETTING_AUDIOOUTPUT_AC3PASSTHROUGH, CSettings::SETTING_AUDIOOUTPUT_AC3TRANSCODE, CSettings::SETTING_AUDIOOUTPUT_ATEMPOTHRESHOLD, CSettings::SETTING_AUDIOOUTPUT_AUDIODEVICE, CSettings::SETTING_AUDIOOUTPUT_CHANNELS, CSettings::SETTING_AUDIOOUTPUT_CONFIG, CSettings::SETTING_AUDIOOUTPUT_DTSHDCOREFALLBACK, CSettings::SETTING_AUDIOOUTPUT_DTSHDPASSTHROUGH, CSettings::SETTING_AUDIOOUTPUT_DTSPASSTHROUGH, CSettings::SETTING_AUDIOOUTPUT_EAC3PASSTHROUGH, CSettings::SETTING_AUDIOOUTPUT_GUISOUNDMODE, CSettings::SETTING_AUDIOOUTPUT_MAINTAINORIGINALVOLUME, CSettings::SETTING_AUDIOOUTPUT_MIXSUBLEVEL, CSettings::SETTING_AUDIOOUTPUT_PASSTHROUGH, CSettings::SETTING_AUDIOOUTPUT_PASSTHROUGHDEVICE, CSettings::SETTING_AUDIOOUTPUT_PROCESSQUALITY, CSettings::SETTING_AUDIOOUTPUT_SAMPLERATE, CSettings::SETTING_AUDIOOUTPUT_STEREOUPMIX, CSettings::SETTING_AUDIOOUTPUT_STREAMNOISE, CSettings::SETTING_AUDIOOUTPUT_STREAMSILENCE, CSettings::SETTING_AUDIOOUTPUT_TRUEHDPASSTHROUGH, SettingOptionsAudioDevicesFiller(), SettingOptionsAudioDevicesPassthroughFiller(), SettingOptionsAudioQualityLevelsFiller(), and SettingOptionsAudioStreamsilenceFiller().
~CActiveAESettings()
ActiveAE::CActiveAESettings::~CActiveAESettings () override
References CServiceBroker::GetSettingsComponent(), m_cs, and m_instance.
Member Function Documentation
IsSettingVisible()
bool ActiveAE::CActiveAESettings::IsSettingVisible (const std::string & condition, const std::string & value, const std::shared_ptr< const CSetting > & setting, void * data) static
References ActiveAE::CActiveAE::IsSettingVisible(), m_audioEngine, m_cs, m_instance, and value.
Referenced by CSettingConditions::Initialize().
OnSettingChanged()
void ActiveAE::CActiveAESettings::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References m_audioEngine, m_cs, m_instance, and ActiveAE::CActiveAE::OnSettingsChange().
SettingOptionsAudioDevicesFiller()
void ActiveAE::CActiveAESettings::SettingOptionsAudioDevicesFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References SettingOptionsAudioDevicesFillerGeneral().
Referenced by CActiveAESettings().
SettingOptionsAudioDevicesFillerGeneral()
void ActiveAE::CActiveAESettings::SettingOptionsAudioDevicesFillerGeneral (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, bool passthrough) static protected
References ActiveAE::CActiveAE::EnumerateOutputDevices(), m_audioEngine, m_cs, and m_instance.
Referenced by SettingOptionsAudioDevicesFiller(), and SettingOptionsAudioDevicesPassthroughFiller().
SettingOptionsAudioDevicesPassthroughFiller()
void ActiveAE::CActiveAESettings::SettingOptionsAudioDevicesPassthroughFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References SettingOptionsAudioDevicesFillerGeneral().
Referenced by CActiveAESettings().
SettingOptionsAudioQualityLevelsFiller()
void ActiveAE::CActiveAESettings::SettingOptionsAudioQualityLevelsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References AE_QUALITY_GPU, AE_QUALITY_HIGH, AE_QUALITY_LOW, AE_QUALITY_MID, AE_QUALITY_REALLYHIGH, g_localizeStrings, CLocalizeStrings::Get(), m_audioEngine, m_cs, m_instance, and ActiveAE::CActiveAE::SupportsQualityLevel().
Referenced by CActiveAESettings().
SettingOptionsAudioStreamsilenceFiller()
void ActiveAE::CActiveAESettings::SettingOptionsAudioStreamsilenceFiller (const std::shared_ptr< const CSetting > & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References g_localizeStrings, CLocalizeStrings::Get(), m_audioEngine, m_cs, m_instance, and ActiveAE::CActiveAE::SupportsSilenceTimeout().
Referenced by CActiveAESettings().
Member Data Documentation
m_audioEngine
CActiveAE& ActiveAE::CActiveAESettings::m_audioEngine protected
Referenced by IsSettingVisible(), OnSettingChanged(), SettingOptionsAudioDevicesFillerGeneral(), SettingOptionsAudioQualityLevelsFiller(), and SettingOptionsAudioStreamsilenceFiller().
m_cs
CCriticalSection ActiveAE::CActiveAESettings::m_cs protected
Referenced by CActiveAESettings(), IsSettingVisible(), OnSettingChanged(), SettingOptionsAudioDevicesFillerGeneral(), SettingOptionsAudioQualityLevelsFiller(), SettingOptionsAudioStreamsilenceFiller(), and ~CActiveAESettings().
m_instance
CActiveAESettings * ActiveAE::CActiveAESettings::m_instance = nullptr static protected
Referenced by CActiveAESettings(), IsSettingVisible(), OnSettingChanged(), SettingOptionsAudioDevicesFillerGeneral(), SettingOptionsAudioQualityLevelsFiller(), SettingOptionsAudioStreamsilenceFiller(), and ~CActiveAESettings().
The documentation for this class was generated from the following files:
ActiveAESettings.h
ActiveAESettings.cpp