Kodi Documentation: KODI::GUILIB::GUIINFO::CGUIInfoLabel Class Reference
KODI::GUILIB::GUIINFO::CGUIInfoLabel Class Reference
#include <GUIInfoLabel.h>
Classes
class CInfoPortion
Public Types
typedef std::function< std::string(const std::string &)> StringReplacerFunc
Public Member Functions
CGUIInfoLabel ()=default
CGUIInfoLabel (const std::string &label, const std::string &fallback="", int context=INFO::DEFAULT_CONTEXT)
void SetLabel (const std::string &label, const std::string &fallback, int context=INFO::DEFAULT_CONTEXT)
const std::string & GetLabel (int contextWindow, bool preferImage=false, std::string *fallback=NULL) const
Gets a label (or image) for a given window context from the info manager.
int GetIntValue (int contextWindow) const
Gets the label and returns it as an int value.
const std::string & GetItemLabel (const CGUIListItem *item, bool preferImage=false, std::string *fallback=nullptr) const
Gets a label (or image) for a given listitem from the info manager.
bool IsConstant () const
bool IsEmpty () const
const std::string & GetFallback () const
Static Public Member Functions
static std::string GetLabel (const std::string &label, int contextWindow, bool preferImage=false)
static std::string GetItemLabel (const std::string &label, const CGUIListItem *item, bool preferImage=false)
static std::string ReplaceLocalize (const std::string &label)
Replaces instances of $LOCALIZE[number] with the appropriate localized string.
static std::string ReplaceAddonStrings (std::string &&label)
Replaces instances of $ADDON[id number] with the appropriate localized addon string.
static std::string ReplaceControllerStrings (std::string &&label)
Replaces instances of $FEATURE[feature name, controller ID] with the appropriate localized controller string.
static bool ReplaceSpecialKeywordReferences (const std::string &strInput, const std::string &strKeyword, const StringReplacerFunc &func, std::string &strOutput)
Replaces instances of $strKeyword[value] with the appropriate resolved string.
static bool ReplaceSpecialKeywordReferences (std::string &work, const std::string &strKeyword, const StringReplacerFunc &func)
Replaces instances of $strKeyword[value] with the appropriate resolved string in-place.
Private Member Functions
void Parse (const std::string &label, std::vector< CInfoPortion > &infoPortion, int context)
Parse a provided label string into the list of info portions that may compose the label. Info portions mean the portions of complex infolabels along with their composition operations (and, or, etc) or skin variables. The label is also rewritten to resolve localized strings and other dynamic expressions.
const std::string & CacheLabel (bool rebuild) const
return (and cache) built label from info portions.
void RebuildLabel (std::string &label, const std::vector< CInfoPortion > &infoPortion) const
Rebuild a label value, based on the provided already resolved info portions (a localized string, multiple infolabels, etc)
bool LabelNeedsUpdate (int context, bool preferImages, std::string *fallback, const std::vector< CInfoPortion > &infoPortion) const
Checks if a given label needs to be updated, based on the provided info portions (a localized string, multiple infolabels, etc)
bool ItemLabelNeedsUpdate (const CGUIListItem *item, bool preferImages, std::string *fallback, const std::vector< CInfoPortion > &infoPortion) const
Checks if a given item label needs to be updated, based on the provided info portions (a localized string, multiple infolabels, etc)
Private Attributes
bool m_dirty = false
std::string m_label
std::string m_fallback
std::vector< CInfoPortion > m_infoLabel
std::vector< CInfoPortion > m_infoFallback
Member Typedef Documentation
StringReplacerFunc
typedef std::function<std::string(const std::string&)> KODI::GUILIB::GUIINFO::CGUIInfoLabel::StringReplacerFunc
Constructor & Destructor Documentation
CGUIInfoLabel() [1/2]
KODI::GUILIB::GUIINFO::CGUIInfoLabel::CGUIInfoLabel () default
CGUIInfoLabel() [2/2]
CGUIInfoLabel::CGUIInfoLabel (const std::string & label, const std::string & fallback = "", int context = INFO::DEFAULT_CONTEXT) explicit
References label, and SetLabel().
Member Function Documentation
CacheLabel()
const std::string & CGUIInfoLabel::CacheLabel (bool rebuild) const private
return (and cache) built label from info portions.
Parameters
rebuild whether we need to rebuild the label
See also
GetLabel, GetItemLabel
References m_dirty, m_fallback, m_infoFallback, m_infoLabel, m_label, and RebuildLabel().
Referenced by GetItemLabel(), and GetLabel().
GetFallback()
const std::string & KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetFallback () const inline
References m_fallback.
Referenced by CGUIImage::GetFallback(), CGUIImage::ProcessAllocation(), and TEST_P().
GetIntValue()
int CGUIInfoLabel::GetIntValue (int contextWindow) const
Gets the label and returns it as an int value.
Parameters
contextWindow the context in which to evaluate the expression.
Returns
int value.
See also
GetLabel
References GetLabel(), and label.
Referenced by CDirectoryProvider::UpdateLimit().
GetItemLabel() [1/2]
const std::string & CGUIInfoLabel::GetItemLabel (const CGUIListItem * item, bool preferImage = false, std::string * fallback = nullptr) const
Gets a label (or image) for a given listitem from the info manager.
Parameters
item listitem in question.
preferImage caller is specifically wanting an image rather than a label. Defaults to false.
fallback if non-NULL, is set to an alternate value to use should the actual value be not appropriate. Defaults to nullptr.
Returns
label (or image).
References CacheLabel(), CGUIListItem::IsFileItem(), ItemLabelNeedsUpdate(), m_dirty, m_infoFallback, m_infoLabel, and m_label.
Referenced by CApplication::ExecuteXBMCAction(), KODI::GAME::CGUIGameController::SetControllerAddress(), KODI::GAME::CGUIGameController::SetControllerID(), KODI::GAME::CGUIGameController::SetPeripheralLocation(), KODI::GAME::CGUIGameController::SetPortAddress(), CGUIImage::UpdateInfo(), CGUIListLabel::UpdateInfo(), CGUIMultiImage::UpdateInfo(), CGUITextBox::UpdateInfo(), KODI::RETRO::CGUIGameControl::UpdateInfo(), and KODI::GAME::CGUIGameController::UpdateInfo().
GetItemLabel() [2/2]
std::string CGUIInfoLabel::GetItemLabel (const std::string & label, const CGUIListItem * item, bool preferImage = false) static
References label.
GetLabel() [1/2]
std::string CGUIInfoLabel::GetLabel (const std::string & label, int contextWindow, bool preferImage = false) static
References label.
GetLabel() [2/2]
const std::string & CGUIInfoLabel::GetLabel (int contextWindow, bool preferImage = false, std::string * fallback = NULL) const
Gets a label (or image) for a given window context from the info manager.
Parameters
contextWindow the context in which to evaluate the expression.
preferImage caller is specifically wanting an image rather than a label. Defaults to false.
fallback if non-NULL, is set to an alternate value to use should the actual value be not appropriate. Defaults to NULL.
Returns
label (or image).
References CacheLabel(), LabelNeedsUpdate(), m_dirty, m_infoFallback, m_infoLabel, and m_label.
Referenced by CGUIListLabel::CGUIListLabel(), CGUIMultiImage::CGUIMultiImage(), CGUIStaticItem::CGUIStaticItem(), CGUIControlFactory::Create(), CApplication::ExecuteXBMCAction(), CGUIButtonControl::GetDescription(), CGUILabelControl::GetDescription(), XBMCAddon::xbmc::getInfoLabel(), CGUIControlFactory::GetInfoLabels(), GetIntValue(), CGUIButtonControl::GetLabel2(), CDirectoryProvider::GetTarget(), CGUIButtonControl::ProcessText(), CGUIEditControl::ProcessText(), CGUILabelControl::SetCursorPos(), CGUIImage::SetInfo(), CGUIMultiImage::SetInfo(), CGUIButtonControl::SetLabel(), CGUILabelControl::SetLabel(), CGUIButtonControl::SetLabel2(), TEST_P(), CGUIInfoManager::TranslateSingleString(), CDirectoryProvider::Update(), CDirectoryProvider::UpdateBrowse(), CGUIImage::UpdateInfo(), CGUILabelControl::UpdateInfo(), CGUIListLabel::UpdateInfo(), CGUIMultiImage::UpdateInfo(), CGUITextBox::UpdateInfo(), CDirectoryProvider::UpdateSort(), and CDirectoryProvider::UpdateURL().
IsConstant()
bool CGUIInfoLabel::IsConstant () const
References m_infoLabel.
Referenced by CGUIListLabel::CGUIListLabel(), CGUIMultiImage::CGUIMultiImage(), CGUIStaticItem::CGUIStaticItem(), CGUIImage::FreeTextures(), CGUIImage::OnMessage(), CGUIMultiImage::OnMessage(), CGUIImage::SetInfo(), CGUIMultiImage::SetInfo(), CGUIImage::UpdateInfo(), CGUIListLabel::UpdateInfo(), and CGUIMultiImage::UpdateInfo().
IsEmpty()
bool CGUIInfoLabel::IsEmpty () const
References m_infoLabel.
ItemLabelNeedsUpdate()
bool CGUIInfoLabel::ItemLabelNeedsUpdate (const CGUIListItem * item, bool preferImages, std::string * fallback, const std::vector< CInfoPortion > & infoPortion) const private
Checks if a given item label needs to be updated, based on the provided info portions (a localized string, multiple infolabels, etc)
Parameters
item listItem in question.
preferImages caller is specifically wanting an image rather than a label.
fallback if non-NULL, is set to an alternate value to use should the actual value be not appropriate. This is used by infoproviders to to re-write the fallback label
infoPortion the list of info portions
Returns
true if an update is needed, false otherwise
References CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetItemImage(), and CGUIInfoManager::GetItemLabel().
Referenced by GetItemLabel().
LabelNeedsUpdate()
bool CGUIInfoLabel::LabelNeedsUpdate (int context, bool preferImages, std::string * fallback, const std::vector< CInfoPortion > & infoPortion) const private
Checks if a given label needs to be updated, based on the provided info portions (a localized string, multiple infolabels, etc)
Parameters
context the context where the info expressions need to be evaluated (currently window ids)
preferImages caller is specifically wanting an image rather than a label.
fallback if non-NULL, is set to an alternate value to use should the actual value be not appropriate. This is used by infoproviders to to re-write the fallback label
infoPortion the list of info portions
Returns
true if an update is needed, false otherwise
References CServiceBroker::GetGUI(), CGUIInfoManager::GetImage(), CGUIComponent::GetInfoManager(), and CGUIInfoManager::GetLabel().
Referenced by GetLabel().
Parse()
void CGUIInfoLabel::Parse (const std::string & label, std::vector< CInfoPortion > & infoPortion, int context) private
Parse a provided label string into the list of info portions that may compose the label. Info portions mean the portions of complex infolabels along with their composition operations (and, or, etc) or skin variables. The label is also rewritten to resolve localized strings and other dynamic expressions.
Parameters
label [in, out] the string label in question (e.g. "$LOCALIZE[xxx]")
infoPortion [in, out] the list of info portions that may have been parsed from the string
context the context where the info expressions need to be evaluated (currently window ids)
References FORMATESCINFO, FORMATESCVAR, FORMATVAR, g_SkinInfo, CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), infoformatmap, label, CLog::Log(), LOGERROR, LOGWARNING, m_dirty, NONE, CGUIInfoManager::RegisterSkinVariableString(), ReplaceAddonStrings(), ReplaceControllerStrings(), ReplaceLocalize(), infoformat::str, CGUIInfoManager::TranslateSkinVariableString(), CGUIInfoManager::TranslateString(), and infoformat::val.
Referenced by SetLabel().
RebuildLabel()
void CGUIInfoLabel::RebuildLabel (std::string & label, const std::vector< CInfoPortion > & infoPortion) const private
Rebuild a label value, based on the provided already resolved info portions (a localized string, multiple infolabels, etc)
Parameters
label[in,out] label value where to store the processed result
infoPortion the list of info portions
References label.
Referenced by CacheLabel().
ReplaceAddonStrings()
std::string CGUIInfoLabel::ReplaceAddonStrings (std::string && label) static
Replaces instances of $ADDON[id number] with the appropriate localized addon string.
Parameters
label text to replace
Returns
text with any localized strings filled in.
References AddonReplacer(), label, and ReplaceSpecialKeywordReferences().
Referenced by Parse().
ReplaceControllerStrings()
std::string CGUIInfoLabel::ReplaceControllerStrings (std::string && label) static
Replaces instances of $FEATURE[feature name, controller ID] with the appropriate localized controller string.
Parameters
label The text to replace
Returns
text with any controller strings filled in
References ControllerFeatureReplacer(), label, and ReplaceSpecialKeywordReferences().
Referenced by Parse().
ReplaceLocalize()
std::string CGUIInfoLabel::ReplaceLocalize (const std::string & label) static
Replaces instances of $LOCALIZE[number] with the appropriate localized string.
Parameters
label text to replace
Returns
text with any localized strings filled in.
References label, LocalizeReplacer(), NumberReplacer(), and ReplaceSpecialKeywordReferences().
Referenced by Parse(), CGUIInfoManager::Register(), and CGUIInfoManager::TranslateString().
ReplaceSpecialKeywordReferences() [1/2]
bool CGUIInfoLabel::ReplaceSpecialKeywordReferences (const std::string & strInput, const std::string & strKeyword, const StringReplacerFunc & func, std::string & strOutput) static
Replaces instances of $strKeyword[value] with the appropriate resolved string.
Parameters
strInput text to replace
strKeyword keyword to look for
func function that does the actual replacement of each bracketed value found
strOutput the output string
Returns
whether anything has been replaced.
References index(), CLog::Log(), and LOGERROR.
Referenced by ReplaceAddonStrings(), ReplaceControllerStrings(), ReplaceLocalize(), and ReplaceSpecialKeywordReferences().
ReplaceSpecialKeywordReferences() [2/2]
bool CGUIInfoLabel::ReplaceSpecialKeywordReferences (std::string & work, const std::string & strKeyword, const StringReplacerFunc & func) static
Replaces instances of $strKeyword[value] with the appropriate resolved string in-place.
Parameters
work text to replace in-place
strKeyword keyword to look for
func function that does the actual replacement of each bracketed value found
Returns
whether anything has been replaced.
References ReplaceSpecialKeywordReferences().
SetLabel()
void CGUIInfoLabel::SetLabel (const std::string & label, const std::string & fallback, int context = INFO::DEFAULT_CONTEXT)
References label, m_fallback, m_infoFallback, m_infoLabel, and Parse().
Referenced by CDirectoryProvider::CDirectoryProvider(), CGUIInfoLabel(), CGUIControlFactory::GetInfoLabelFromElement(), CGUITextBox::OnMessage(), CGUIImage::SetFileName(), CGUIButtonControl::SetLabel(), CGUILabelControl::SetLabel(), and CGUIButtonControl::SetLabel2().
Member Data Documentation
m_dirty
bool KODI::GUILIB::GUIINFO::CGUIInfoLabel::m_dirty = false mutable private
Referenced by CacheLabel(), GetItemLabel(), GetLabel(), and Parse().
m_fallback
std::string KODI::GUILIB::GUIINFO::CGUIInfoLabel::m_fallback mutable private
Referenced by CacheLabel(), GetFallback(), and SetLabel().
m_infoFallback
std::vector<CInfoPortion> KODI::GUILIB::GUIINFO::CGUIInfoLabel::m_infoFallback private
Referenced by CacheLabel(), GetItemLabel(), GetLabel(), and SetLabel().
m_infoLabel
std::vector<CInfoPortion> KODI::GUILIB::GUIINFO::CGUIInfoLabel::m_infoLabel private
Referenced by CacheLabel(), GetItemLabel(), GetLabel(), IsConstant(), IsEmpty(), and SetLabel().
m_label
std::string KODI::GUILIB::GUIINFO::CGUIInfoLabel::m_label mutable private
Referenced by CacheLabel(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::CInfoPortion::Get(), GetItemLabel(), GetLabel(), and KODI::GUILIB::GUIINFO::CGUIInfoLabel::CInfoPortion::NeedsUpdate().
The documentation for this class was generated from the following files:
GUIInfoLabel.h
GUIInfoLabel.cpp