Kodi Documentation: CAESinkWASAPI Class Reference
CAESinkWASAPI Class Reference
#include <AESinkWASAPI.h>
Public Member Functions
CAESinkWASAPI ()
virtual ~CAESinkWASAPI ()
const char * GetName () override
bool Initialize (AEAudioFormat &format, std::string &device) override
void Deinitialize () override
void GetDelay (AEDelayStatus &status) override
Return a timestamped status structure with delay and sink info.
double GetCacheTotal () override
unsigned int AddPackets (uint8_t **data, unsigned int frames, unsigned int offset) override
Adds packets to be sent out, this routine MUST block or sleep.
void Drain () override
Public Member Functions inherited from IAESink
IAESink ()=default
virtual ~IAESink ()=default
virtual double GetLatency ()
virtual void AddPause (unsigned int millis)
instruct the sink to add a pause
virtual bool HasVolume ()
virtual void SetVolume (float volume)
Static Public Member Functions
static void Register ()
static std::unique_ptr< IAESink > Create (std::string &device, AEAudioFormat &desiredFormat)
static void EnumerateDevicesEx (AEDeviceInfoList &deviceInfoList, bool force=false)
Private Member Functions
bool InitializeExclusive (AEAudioFormat &format)
bool IsUSBDevice ()
Static Private Member Functions
static void BuildWaveFormatExtensibleIEC61397 (AEAudioFormat &format, WAVEFORMATEXTENSIBLE_IEC61937 &wfxex)
Private Attributes
HANDLE m_needDataEvent {0}
IAEWASAPIDevice * m_pDevice {nullptr}
Microsoft::WRL::ComPtr< IAudioClient > m_pAudioClient
Microsoft::WRL::ComPtr< IAudioRenderClient > m_pRenderClient
Microsoft::WRL::ComPtr< IAudioClock > m_pAudioClock
AEAudioFormat m_format {}
unsigned int m_encodedChannels {0}
unsigned int m_encodedSampleRate {0}
CAEChannelInfo m_channelLayout
std::string m_device
enum AEDataFormat sinkReqFormat = AE_FMT_INVALID
enum AEDataFormat sinkRetFormat = AE_FMT_INVALID
bool m_running {false}
bool m_initialized {false}
bool m_isSuspended {false}
bool m_isDirty {false}
double m_avgTimeWaiting {50.0}
double m_sinkLatency {0.0}
unsigned int m_uiBufferLen {0}
uint64_t m_sinkFrames {0}
uint64_t m_clockFreq {0}
std::vector< uint8_t > m_buffer
int m_bufferPtr {0}
Constructor & Destructor Documentation
CAESinkWASAPI()
CAESinkWASAPI::CAESinkWASAPI ()
References m_channelLayout, and CAEChannelInfo::Reset().
~CAESinkWASAPI()
CAESinkWASAPI::~CAESinkWASAPI () virtual
Member Function Documentation
AddPackets()
unsigned int CAESinkWASAPI::AddPackets (uint8_t ** data, unsigned int frames, unsigned int offset) override virtual
Adds packets to be sent out, this routine MUST block or sleep.
Parameters
data array of pointers to planes holding audio data
frames number of audio frames in data
offset offset in frames where audio data starts
Returns
number of frames consumed by the sink
Implements IAESink.
References data(), FAILED, CWIN32Util::FormatHRESULT(), LOGDEBUG, LOGERROR, m_avgTimeWaiting, m_buffer, m_bufferPtr, m_format, AEAudioFormat::m_frames, AEAudioFormat::m_frameSize, m_initialized, m_isDirty, m_needDataEvent, m_pAudioClient, m_pRenderClient, m_running, m_sinkFrames, and _LARGE_INTEGER::QuadPart.
BuildWaveFormatExtensibleIEC61397()
void CAESinkWASAPI::BuildWaveFormatExtensibleIEC61397 (AEAudioFormat & format, WAVEFORMATEXTENSIBLE_IEC61937 & wfxex) static private
References CAESinkFactoryWin::BuildWaveFormatExtensible().
Referenced by InitializeExclusive().
Create()
std::unique_ptr< IAESink > CAESinkWASAPI::Create (std::string & device, AEAudioFormat & desiredFormat) static
Referenced by Register().
Deinitialize()
void CAESinkWASAPI::Deinitialize () override virtual
Implements IAESink.
References CloseHandle(), LOGDEBUG, m_bufferPtr, m_initialized, m_isDirty, m_needDataEvent, m_pAudioClient, m_pAudioClock, m_pDevice, m_pRenderClient, m_running, m_sinkFrames, and SafeRelease().
Drain()
void CAESinkWASAPI::Drain () override virtual
Reimplemented from IAESink.
References AEDelayStatus::GetDelay(), GetDelay(), LOGDEBUG, m_pAudioClient, m_running, m_sinkFrames, and KODI::TIME::Sleep().
EnumerateDevicesEx()
void CAESinkWASAPI::EnumerateDevicesEx (AEDeviceInfoList & deviceInfoList, bool force = false) static
References IAEWASAPIDevice::Activate(), CAESinkFactoryWin::ActivateWASAPIDevice(), AE_DEVTYPE_HDMI, AE_FMT_FLOAT, AE_FMT_INVALID, AE_FMT_RAW, AE_FMT_S16NE, AE_FMT_S24BE4, AE_FMT_S24NE4MSB, AEChannelNames, CAEUtil::DataFormatToBits(), FAILED, CWIN32Util::FormatHRESULT(), CAESinkFactoryWin::GetRendererDetails(), CSysInfo::GetWindowsDeviceFamily(), LOGDEBUG, LOGERROR, LOGINFO, CAEDeviceInfo::m_channels, CAEDeviceInfo::m_dataFormats, CAEDeviceInfo::m_deviceName, CAEDeviceInfo::m_deviceType, CAEDeviceInfo::m_displayName, CAEDeviceInfo::m_displayNameExtra, CAEDeviceInfo::m_onlyPassthrough, CAEDeviceInfo::m_sampleRates, CAEDeviceInfo::m_streamTypes, CAEDeviceInfo::m_wantsIECPassthrough, CAEChannelInfo::Reset(), SafeRelease(), CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, CAEStreamInfo::STREAM_TYPE_TRUEHD, CAEUtil::StreamTypeToStr(), WASAPI_SPEAKER_COUNT, WASAPIChannelOrder, WASAPISampleRateCount, WASAPISampleRates, and CSysInfo::Xbox.
Referenced by Register().
GetCacheTotal()
double CAESinkWASAPI::GetCacheTotal () override virtual
Implements IAESink.
References m_initialized, and m_sinkLatency.
GetDelay()
void CAESinkWASAPI::GetDelay (AEDelayStatus & status) override virtual
Return a timestamped status structure with delay and sink info.
Parameters
status structure filled with sink status
Implements IAESink.
References CurrentHostFrequency(), AEDelayStatus::delay, EXIT_ON_FAILURE, m_bufferPtr, m_clockFreq, m_format, m_initialized, m_pAudioClock, AEAudioFormat::m_sampleRate, m_sinkFrames, rescale_u64(), AEDelayStatus::SetDelay(), and AEDelayStatus::tick.
Referenced by Drain().
GetName()
const char * CAESinkWASAPI::GetName () inline override virtual
Implements IAESink.
Initialize()
bool CAESinkWASAPI::Initialize (AEAudioFormat & format, std::string & device) override virtual
Implements IAESink.
References IAEWASAPIDevice::Activate(), CAESinkFactoryWin::ActivateWASAPIDevice(), AE_FMT_INVALID, CloseHandle(), EXIT_ON_FAILURE, CAESinkFactoryWin::GetDefaultDeviceId(), IID_IAudioClock, IID_IAudioRenderClient, InitializeExclusive(), LOGERROR, LOGINFO, m_buffer, m_bufferPtr, m_clockFreq, AEAudioFormat::m_dataFormat, m_device, m_format, m_initialized, m_isDirty, m_needDataEvent, m_pAudioClient, m_pAudioClock, m_pDevice, m_pRenderClient, m_uiBufferLen, SafeRelease(), sinkReqFormat, and sinkRetFormat.
InitializeExclusive()
bool CAESinkWASAPI::InitializeExclusive (AEAudioFormat & format) private
References IAEWASAPIDevice::Activate(), AE_FMT_FLOAT, AE_FMT_INVALID, AE_FMT_MAX, AE_FMT_RAW, AE_FMT_S16NE, AE_FMT_S24NE3, AE_FMT_S24NE4MSB, AE_FMT_S32NE, CAESinkFactoryWin::AEChannelsFromSpeakerMask(), sampleFormat::bitsPerSample, CAESinkFactoryWin::BuildWaveFormatExtensible(), BuildWaveFormatExtensibleIEC61397(), CAESinkFactoryWin::ChLayoutToChMask(), CAEChannelInfo::Count(), CAEUtil::DataFormatToStr(), FAILED, CWIN32Util::FormatHRESULT(), IsUSBDevice(), CSysInfo::IsWindowsVersionAtLeast(), layoutsList, CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, LOGWARNING, m_channelLayout, m_encodedChannels, m_encodedSampleRate, m_pAudioClient, m_pDevice, m_sinkLatency, m_uiBufferLen, CAESinkFactoryWin::SpeakerMaskFromAEChannels(), sampleFormat::subFormat, sampleFormat::subFormatType, testFormats, sampleFormat::validBitsPerSample, WASAPISampleRateCount, WASAPISampleRates, and CSysInfo::WindowsVersionWin10.
Referenced by Initialize().
IsUSBDevice()
bool CAESinkWASAPI::IsUSBDevice () private
References IAEWASAPIDevice::IsUSBDevice(), and m_pDevice.
Referenced by InitializeExclusive().
Register()
void CAESinkWASAPI::Register () static
References Create(), AE::AESinkRegEntry::createFunc, EnumerateDevicesEx(), AE::AESinkRegEntry::enumerateFunc, AE::CAESinkFactory::RegisterSink(), and AE::AESinkRegEntry::sinkName.
Referenced by CWinSystemWin10::CWinSystemWin10(), and CWinSystemWin32::CWinSystemWin32().
Member Data Documentation
m_avgTimeWaiting
double CAESinkWASAPI::m_avgTimeWaiting {50.0} private
Referenced by AddPackets().
m_buffer
std::vector<uint8_t> CAESinkWASAPI::m_buffer private
Referenced by AddPackets(), and Initialize().
m_bufferPtr
int CAESinkWASAPI::m_bufferPtr {0} private
Referenced by AddPackets(), Deinitialize(), GetDelay(), and Initialize().
m_channelLayout
CAEChannelInfo CAESinkWASAPI::m_channelLayout private
Referenced by CAESinkWASAPI(), and InitializeExclusive().
m_clockFreq
uint64_t CAESinkWASAPI::m_clockFreq {0} private
Referenced by GetDelay(), and Initialize().
m_device
std::string CAESinkWASAPI::m_device private
Referenced by Initialize().
m_encodedChannels
unsigned int CAESinkWASAPI::m_encodedChannels {0} private
Referenced by InitializeExclusive().
m_encodedSampleRate
unsigned int CAESinkWASAPI::m_encodedSampleRate {0} private
Referenced by InitializeExclusive().
m_format
AEAudioFormat CAESinkWASAPI::m_format {} private
Referenced by AddPackets(), GetDelay(), and Initialize().
m_initialized
bool CAESinkWASAPI::m_initialized {false} private
Referenced by AddPackets(), Deinitialize(), GetCacheTotal(), GetDelay(), and Initialize().
m_isDirty
bool CAESinkWASAPI::m_isDirty {false} private
Referenced by AddPackets(), Deinitialize(), and Initialize().
m_isSuspended
bool CAESinkWASAPI::m_isSuspended {false} private
m_needDataEvent
HANDLE CAESinkWASAPI::m_needDataEvent {0} private
Referenced by AddPackets(), Deinitialize(), and Initialize().
m_pAudioClient
Microsoft::WRL::ComPtr<IAudioClient> CAESinkWASAPI::m_pAudioClient private
Referenced by AddPackets(), Deinitialize(), Drain(), Initialize(), and InitializeExclusive().
m_pAudioClock
Microsoft::WRL::ComPtr<IAudioClock> CAESinkWASAPI::m_pAudioClock private
Referenced by Deinitialize(), GetDelay(), and Initialize().
m_pDevice
IAEWASAPIDevice* CAESinkWASAPI::m_pDevice {nullptr} private
Referenced by Deinitialize(), Initialize(), InitializeExclusive(), and IsUSBDevice().
m_pRenderClient
Microsoft::WRL::ComPtr<IAudioRenderClient> CAESinkWASAPI::m_pRenderClient private
Referenced by AddPackets(), Deinitialize(), and Initialize().
m_running
bool CAESinkWASAPI::m_running {false} private
Referenced by AddPackets(), Deinitialize(), and Drain().
m_sinkFrames
uint64_t CAESinkWASAPI::m_sinkFrames {0} private
Referenced by AddPackets(), Deinitialize(), Drain(), and GetDelay().
m_sinkLatency
double CAESinkWASAPI::m_sinkLatency {0.0} private
Referenced by GetCacheTotal(), and InitializeExclusive().
m_uiBufferLen
unsigned int CAESinkWASAPI::m_uiBufferLen {0} private
Referenced by Initialize(), and InitializeExclusive().
sinkReqFormat
enum AEDataFormat CAESinkWASAPI::sinkReqFormat = AE_FMT_INVALID private
Referenced by Initialize().
sinkRetFormat
enum AEDataFormat CAESinkWASAPI::sinkRetFormat = AE_FMT_INVALID private
Referenced by Initialize().
The documentation for this class was generated from the following files:
AESinkWASAPI.h
AESinkWASAPI.cpp