Kodi Documentation: CWin32StorageProvider Class Reference
CWin32StorageProvider Class Reference
#include <Win32StorageProvider.h>
Public Member Functions
virtual ~CWin32StorageProvider ()
virtual void Initialize ()
virtual void Stop ()
virtual void GetLocalDrives (std::vector< CMediaSource > &localDrives)
virtual void GetRemovableDrives (std::vector< CMediaSource > &removableDrives)
virtual std::string GetFirstOpticalDeviceFileName ()
virtual bool Eject (const std::string &mountpath)
virtual std::vector< std::string > GetDiskUsage ()
virtual bool PumpDriveChangeEvents (IStorageEventsCallback *callback)
Public Member Functions inherited from IStorageProvider
virtual ~IStorageProvider ()=default
Static Public Member Functions
static void SetEvent ()
Static Public Member Functions inherited from IStorageProvider
static std::unique_ptr< IStorageProvider > CreateInstance ()
Called by media manager to create platform storage provider.
Static Public Attributes
static bool xbevent = false
Static Private Member Functions
static void GetDrivesByType (std::vector< CMediaSource > &localDrives, Drive_Types eDriveType=ALL_DRIVES, bool bonlywithmedia=false)
static DEVINST GetDrivesDevInstByDiskNumber (long DiskNumber)
Constructor & Destructor Documentation
~CWin32StorageProvider()
virtual CWin32StorageProvider::~CWin32StorageProvider () inline virtual
Member Function Documentation
Eject()
bool CWin32StorageProvider::Eject (const std::string & mountpath) virtual
Implements IStorageProvider.
References CloseHandle(), GetDrivesDevInstByDiskNumber(), INVALID_HANDLE_VALUE, MAX_PATH, OPEN_EXISTING, and KODI::PLATFORM::WINDOWS::ToW().
GetDiskUsage()
std::vector< std::string > CWin32StorageProvider::GetDiskUsage (void) virtual
Implements IStorageProvider.
References KODI::PLATFORM::WINDOWS::FromW(), g_localizeStrings, CLocalizeStrings::Get(), _ULARGE_INTEGER::QuadPart, and KODI::PLATFORM::WINDOWS::ToW().
GetDrivesByType()
void CWin32StorageProvider::GetDrivesByType (std::vector< CMediaSource > & localDrives, Drive_Types eDriveType = ALL_DRIVES, bool bonlywithmedia = false) static private
Todo:
Sorting should depend on driver letter
References AddOrReplace(), ALL_DRIVES, DVD_DRIVES, KODI::PLATFORM::WINDOWS::FromW(), g_localizeStrings, CLocalizeStrings::Get(), LOCAL_DRIVES, CMediaSource::m_iDriveType, CMediaSource::m_ignore, MAX_PATH, REMOVABLE_DRIVES, CMediaSource::SOURCE_TYPE_LOCAL, CMediaSource::SOURCE_TYPE_OPTICAL_DISC, CMediaSource::SOURCE_TYPE_REMOTE, CMediaSource::SOURCE_TYPE_REMOVABLE, CMediaSource::SOURCE_TYPE_UNKNOWN, CMediaSource::strName, CMediaSource::strPath, and CMediaSource::strStatus.
Referenced by GetFirstOpticalDeviceFileName(), GetLocalDrives(), GetRemovableDrives(), and Initialize().
GetDrivesDevInstByDiskNumber()
DEVINST CWin32StorageProvider::GetDrivesDevInstByDiskNumber (long DiskNumber) static private
References CloseHandle(), INVALID_HANDLE_VALUE, and OPEN_EXISTING.
Referenced by Eject().
GetFirstOpticalDeviceFileName()
std::string CWin32StorageProvider::GetFirstOpticalDeviceFileName () virtual
Reimplemented from IStorageProvider.
References DVD_DRIVES, and GetDrivesByType().
GetLocalDrives()
void CWin32StorageProvider::GetLocalDrives (std::vector< CMediaSource > & localDrives) virtual
Implements IStorageProvider.
References KODI::PLATFORM::WINDOWS::FromW(), g_localizeStrings, CLocalizeStrings::Get(), GetDrivesByType(), LOCAL_DRIVES, CMediaSource::m_iDriveType, CMediaSource::m_ignore, MAX_PATH, CMediaSource::SOURCE_TYPE_LOCAL, CMediaSource::strName, CMediaSource::strPath, and CSpecialProtocol::TranslatePath().
GetRemovableDrives()
void CWin32StorageProvider::GetRemovableDrives (std::vector< CMediaSource > & removableDrives) virtual
Implements IStorageProvider.
References GetDrivesByType(), and REMOVABLE_DRIVES.
Initialize()
void CWin32StorageProvider::Initialize () virtual
Implements IStorageProvider.
References CLOSED_MEDIA_PRESENT, DVD_DRIVES, GetDrivesByType(), CMediaManager::GetDriveStatus(), CServiceBroker::GetJobManager(), CServiceBroker::GetMediaManager(), CLog::Log(), LOGDEBUG, and CMediaManager::SetHasOpticalDrive().
PumpDriveChangeEvents()
bool CWin32StorageProvider::PumpDriveChangeEvents (IStorageEventsCallback * callback) virtual
Implements IStorageProvider.
References xbevent.
SetEvent()
static void CWin32StorageProvider::SetEvent () inline static
References xbevent.
Referenced by CWinEventsWin32::WndProc().
Stop()
virtual void CWin32StorageProvider::Stop () inline virtual
Implements IStorageProvider.
Member Data Documentation
xbevent
bool CWin32StorageProvider::xbevent = false static
Referenced by PumpDriveChangeEvents(), and SetEvent().
The documentation for this class was generated from the following files:
Win32StorageProvider.h
Win32StorageProvider.cpp