Kodi Documentation: DXVA::CEnumeratorHD Class Reference
DXVA::CEnumeratorHD Class Reference
#include <DXVAEnumeratorHD.h>
Public Member Functions
CEnumeratorHD ()
virtual ~CEnumeratorHD ()
bool Open (unsigned int width, unsigned int height, DXGI_FORMAT input_dxgi_format)
void Close ()
void OnCreateDevice () override
void OnDestroyDevice (bool) override
ProcessorCapabilities ProbeProcessorCaps ()
bool CheckConversion (DXGI_FORMAT inputFormat, DXGI_COLOR_SPACE_TYPE inputCS, DXGI_FORMAT outputFormat, DXGI_COLOR_SPACE_TYPE outputCS)
Check if a conversion is supported by the dxva processor.
bool IsFormatSupportedInput (DXGI_FORMAT format)
Check dxva processor for support of the format as input texture.
bool IsFormatSupportedOutput (DXGI_FORMAT format)
Check dxva processor for support of the format as output texture.
void LogSupportedConversions (const DXGI_FORMAT inputFormat, const DXGI_COLOR_SPACE_TYPE inputNativeCS)
Outputs in the log a list of conversions supported by the DXVA processor.
bool IsInitialized () const
bool IsEnumerator1Available ()
Returns the availability of the interface ID3D11VideoProcessorEnumerator1 (Windows 10 supporting HDR and above)
ComPtr< ID3D11VideoProcessor > CreateVideoProcessor (UINT RateConversionIndex)
ComPtr< ID3D11VideoProcessorInputView > CreateVideoProcessorInputView (ID3D11Resource *pResource, const D3D11_VIDEO_PROCESSOR_INPUT_VIEW_DESC *pDesc)
ComPtr< ID3D11VideoProcessorOutputView > CreateVideoProcessorOutputView (ID3D11Resource *pResource, const D3D11_VIDEO_PROCESSOR_OUTPUT_VIEW_DESC *pDesc)
ProcessorConversions SupportedConversions (const SupportedConversionsArgs &args)
Return a list of conversions supported by the processor for the given parameters.
Public Member Functions inherited from ID3DResource
virtual ~ID3DResource ()
Static Public Member Functions
static DXGI_COLOR_SPACE_TYPE AvToDxgiColorSpace (const DXGIColorSpaceArgs &csArgs)
Converts ffmpeg AV parameters to a DXGI color space.
Protected Member Functions
void UnInit ()
bool OpenEnumerator ()
ProcessorFormats GetProcessorFormats (bool inputFormats, bool outputFormats) const
Retrieve the list of DXGI_FORMAT supported by the DXVA processor.
std::vector< DXGI_FORMAT > GetProcessorRGBOutputFormats () const
Retrieve the list of RGB DXGI_FORMAT supported as output by the DXVA processor.
bool CheckConversionInternal (DXGI_FORMAT inputFormat, DXGI_COLOR_SPACE_TYPE inputCS, DXGI_FORMAT outputFormat, DXGI_COLOR_SPACE_TYPE outputCS) const
Check if a conversion is supported by the dxva processor.
bool IsFormatSupportedInternal (DXGI_FORMAT format, D3D11_VIDEO_PROCESSOR_FORMAT_SUPPORT support) const
Check dxva processor for support of the format as input texture.
ProcessorConversions ListConversions (DXGI_FORMAT inputFormat, const std::vector< DXGI_COLOR_SPACE_TYPE > &inputColorSpaces, const std::vector< DXGI_FORMAT > &outputFormats, const std::vector< DXGI_COLOR_SPACE_TYPE > &outputColorSpaces) const
Iterate over all combinations of the input parameters and return a list of the combinations that are supported conversions.
ProcessorConversions LogAndListConversions (const DXGIColorSpaceArgs &inputArgs, const DXGIColorSpaceArgs &outputArgs) const
Helper function that outputs input/output to log and returns the results of ListConversions for the input parameters.
AVChromaLocation DefaultChromaSiting (const SupportedConversionsArgs &args) const
Suggest chroma siting derived from source charateristics. Has limited functionality at this time and supports values that make sense for dxgi.
AVChromaLocation AlternativeChromaSiting (const AVChromaLocation &location) const
Suggest an alternative chroma siting to help with dxva processor that don't support some dxgi color spaces.
Protected Member Functions inherited from ID3DResource
void Register ()
void Unregister ()
Protected Attributes
CCriticalSection m_section
uint32_t m_width = 0
uint32_t m_height = 0
ComPtr< ID3D11VideoDevice > m_pVideoDevice
ComPtr< ID3D11VideoProcessorEnumerator > m_pEnumerator
ComPtr< ID3D11VideoProcessorEnumerator1 > m_pEnumerator1
DXGI_FORMAT m_input_dxgi_format {DXGI_FORMAT_UNKNOWN}
Protected Attributes inherited from ID3DResource
bool m_bRegistered = false
Constructor & Destructor Documentation
CEnumeratorHD()
CEnumeratorHD::CEnumeratorHD ()
~CEnumeratorHD()
CEnumeratorHD::~CEnumeratorHD () virtual
References m_section, and UnInit().
Member Function Documentation
AlternativeChromaSiting()
AVChromaLocation CEnumeratorHD::AlternativeChromaSiting (const AVChromaLocation & location) const protected
Suggest an alternative chroma siting to help with dxva processor that don't support some dxgi color spaces.
Parameters
location original chroma siting
Returns
suggested alternative chroma siting
Referenced by SupportedConversions().
AvToDxgiColorSpace()
DXGI_COLOR_SPACE_TYPE CEnumeratorHD::AvToDxgiColorSpace (const DXGIColorSpaceArgs & csArgs) static
Converts ffmpeg AV parameters to a DXGI color space.
Parameters
csArgs ffmpeg AV picture parameters
Returns
DXGI color space. Special value DXGI_COLOR_SPACE_CUSTOM used when there is no match.
References DXVA::DXGIColorSpaceArgs::chroma_location, DXVA::DXGIColorSpaceArgs::color_space, DXVA::DXGIColorSpaceArgs::color_transfer, DXVA::DXGIColorSpaceArgs::full_range, and DXVA::DXGIColorSpaceArgs::primaries.
Referenced by CRendererDXVA::Configure(), LogAndListConversions(), and SupportedConversions().
CheckConversion()
bool CEnumeratorHD::CheckConversion (DXGI_FORMAT inputFormat, DXGI_COLOR_SPACE_TYPE inputCS, DXGI_FORMAT outputFormat, DXGI_COLOR_SPACE_TYPE outputCS)
Check if a conversion is supported by the dxva processor.
Parameters
inputFormat the input format
inputCS the input color space
outputFormat the output format
outputCS the output color space
Returns
true when the conversion is supported, false when it is not or the API used to validate is not availe (Windows < 10)
References CheckConversionInternal(), and m_section.
CheckConversionInternal()
bool CEnumeratorHD::CheckConversionInternal (DXGI_FORMAT inputFormat, DXGI_COLOR_SPACE_TYPE inputCS, DXGI_FORMAT outputFormat, DXGI_COLOR_SPACE_TYPE outputCS) const protected
Check if a conversion is supported by the dxva processor.
Parameters
inputFormat the input format
inputCS the input color space
outputFormat the output format
outputCS the output color space
Returns
true when the conversion is supported, false when it is not or the API used to validate is not available (Windows < 10)
References CWIN32Util::FormatHRESULT(), LOGERROR, m_pEnumerator, and m_pEnumerator1.
Referenced by CheckConversion(), and ListConversions().
Close()
void CEnumeratorHD::Close ()
References m_pEnumerator, m_pEnumerator1, m_pVideoDevice, and m_section.
Referenced by Open(), and UnInit().
CreateVideoProcessor()
ComPtr< ID3D11VideoProcessor > CEnumeratorHD::CreateVideoProcessor (UINT RateConversionIndex)
References FAILED, CWIN32Util::FormatHRESULT(), LOGDEBUG, m_pEnumerator, m_pVideoDevice, and m_section.
CreateVideoProcessorInputView()
ComPtr< ID3D11VideoProcessorInputView > CEnumeratorHD::CreateVideoProcessorInputView (ID3D11Resource * pResource, const D3D11_VIDEO_PROCESSOR_INPUT_VIEW_DESC * pDesc)
References FAILED, CWIN32Util::FormatHRESULT(), LOGERROR, LOGWARNING, m_pEnumerator, m_pVideoDevice, and m_section.
CreateVideoProcessorOutputView()
ComPtr< ID3D11VideoProcessorOutputView > CEnumeratorHD::CreateVideoProcessorOutputView (ID3D11Resource * pResource, const D3D11_VIDEO_PROCESSOR_OUTPUT_VIEW_DESC * pDesc)
References FAILED, CWIN32Util::FormatHRESULT(), LOGERROR, LOGWARNING, m_pEnumerator, m_pVideoDevice, and m_section.
DefaultChromaSiting()
AVChromaLocation CEnumeratorHD::DefaultChromaSiting (const SupportedConversionsArgs & args) const protected
Suggest chroma siting derived from source charateristics. Has limited functionality at this time and supports values that make sense for dxgi.
Parameters
args description of the sourcce
Returns
suggested chroma siting.
Referenced by SupportedConversions().
GetProcessorFormats()
ProcessorFormats CEnumeratorHD::GetProcessorFormats (bool inputFormats, bool outputFormats) const protected
Retrieve the list of DXGI_FORMAT supported by the DXVA processor.
Parameters
inputFormats yes/no populate the input formats vector of the returned structure
outputFormats yes/no populate the output formats vector of the returned structure
Returns
requested list of input and/or output formats.
References DX::DXGIFormatToString(), CWIN32Util::FormatHRESULT(), formats, LOGWARNING, and m_pEnumerator.
Referenced by GetProcessorRGBOutputFormats(), and ProbeProcessorCaps().
GetProcessorRGBOutputFormats()
std::vector< DXGI_FORMAT > CEnumeratorHD::GetProcessorRGBOutputFormats () const protected
Retrieve the list of RGB DXGI_FORMAT supported as output by the DXVA processor.
Returns
Vector of formats
References DX::DXGIFormatToString(), formats, GetProcessorFormats(), and name.
Referenced by LogSupportedConversions().
IsEnumerator1Available()
bool DXVA::CEnumeratorHD::IsEnumerator1Available () inline
Returns the availability of the interface ID3D11VideoProcessorEnumerator1 (Windows 10 supporting HDR and above)
Returns
true when the interface is available and initialized, false otherwise
References m_pEnumerator1.
IsFormatSupportedInput()
bool CEnumeratorHD::IsFormatSupportedInput (DXGI_FORMAT format)
Check dxva processor for support of the format as input texture.
Parameters
format the format
Returns
true supported, false not supported
References IsFormatSupportedInternal(), and m_section.
IsFormatSupportedInternal()
bool CEnumeratorHD::IsFormatSupportedInternal (DXGI_FORMAT format, D3D11_VIDEO_PROCESSOR_FORMAT_SUPPORT support) const protected
Check dxva processor for support of the format as input texture.
Parameters
format the format
Returns
true supported, false not supported
References DX::D3D11VideoProcessorFormatSupportToString(), DX::DXGIFormatToString(), LOGERROR, and m_pEnumerator.
Referenced by IsFormatSupportedInput(), and IsFormatSupportedOutput().
IsFormatSupportedOutput()
bool CEnumeratorHD::IsFormatSupportedOutput (DXGI_FORMAT format)
Check dxva processor for support of the format as output texture.
Parameters
format the format
Returns
true supported, false not supported
References IsFormatSupportedInternal(), and m_section.
IsInitialized()
bool DXVA::CEnumeratorHD::IsInitialized () const inline
References m_pEnumerator.
ListConversions()
ProcessorConversions CEnumeratorHD::ListConversions (DXGI_FORMAT inputFormat, const std::vector< DXGI_COLOR_SPACE_TYPE > & inputColorSpaces, const std::vector< DXGI_FORMAT > & outputFormats, const std::vector< DXGI_COLOR_SPACE_TYPE > & outputColorSpaces) const protected
Iterate over all combinations of the input parameters and return a list of the combinations that are supported conversions.
Parameters
inputFormat The input format
inputColorSpaces The possible source color spaces
outputFormats The possible output formats
outputColorSpaces The possible output color spaces
Returns
List of the supported conversion.
References CheckConversionInternal(), m_pEnumerator, and m_pEnumerator1.
Referenced by LogAndListConversions(), and LogSupportedConversions().
LogAndListConversions()
ProcessorConversions CEnumeratorHD::LogAndListConversions (const DXGIColorSpaceArgs & inputArgs, const DXGIColorSpaceArgs & outputArgs) const protected
Helper function that outputs input/output to log and returns the results of ListConversions for the input parameters.
Parameters
inputArgs description of the source
outputColorSpaces description of the destination
Returns
List of the supported conversion.
References AvToDxgiColorSpace(), DX::DXGIColorSpaceTypeToString(), DX::DeviceResources::Get(), ListConversions(), LOGDEBUG, m_input_dxgi_format, and DXVA::DXGIColorSpaceArgs::primaries.
Referenced by SupportedConversions().
LogSupportedConversions()
void CEnumeratorHD::LogSupportedConversions (const DXGI_FORMAT inputFormat, const DXGI_COLOR_SPACE_TYPE inputNativeCS)
Outputs in the log a list of conversions supported by the DXVA processor.
Parameters
inputFormat the source format
inputNativeCS the input color space that would be used with a direct mapping from avcodec to D3D11, without any workarounds or tricks.
References DX::DXGIColorSpaceTypeToString(), DX::DXGIFormatToString(), FAILED, CWIN32Util::FormatHRESULT(), DX::DeviceResources::Get(), GetProcessorRGBOutputFormats(), ListConversions(), LOGDEBUG, LOGVIDEO, m_pEnumerator, m_pEnumerator1, and m_section.
OnCreateDevice()
void DXVA::CEnumeratorHD::OnCreateDevice (void) inline override virtual
Implements ID3DResource.
References m_height, m_section, m_width, and OpenEnumerator().
OnDestroyDevice()
void DXVA::CEnumeratorHD::OnDestroyDevice (bool) inline override virtual
Implements ID3DResource.
References m_section, and UnInit().
Open()
bool CEnumeratorHD::Open (unsigned int width, unsigned int height, DXGI_FORMAT input_dxgi_format)
References Close(), m_height, m_input_dxgi_format, m_section, m_width, and OpenEnumerator().
Referenced by CRendererDXVA::GetWeight().
OpenEnumerator()
bool CEnumeratorHD::OpenEnumerator () protected
References FAILED, CWIN32Util::FormatHRESULT(), DX::DeviceResources::Get(), LOGDEBUG, LOGWARNING, m_height, m_pEnumerator, m_pEnumerator1, m_pVideoDevice, and m_width.
Referenced by OnCreateDevice(), and Open().
ProbeProcessorCaps()
ProcessorCapabilities CEnumeratorHD::ProbeProcessorCaps ()
References DXVA::ProcAmpFilter::cap, DX::DXGIFormatToString(), FAILED, DXVA::ProcAmpFilter::filter, CWIN32Util::FormatHRESULT(), formats, CServiceBroker::GetLogging(), GetProcessorFormats(), LOGDEBUG, LOGINFO, LOGVIDEO, LOGWARNING, m_pEnumerator, m_section, name, DXVA::NUM_FILTERS, and DXVA::PROCAMP_FILTERS.
SupportedConversions()
ProcessorConversions CEnumeratorHD::SupportedConversions (const SupportedConversionsArgs & args)
Return a list of conversions supported by the processor for the given parameters.
Parameters
args parameters
Returns
list of conversions
References AlternativeChromaSiting(), AvToDxgiColorSpace(), DefaultChromaSiting(), DX::DXGIColorSpaceTypeToString(), CServiceBroker::GetLogging(), LogAndListConversions(), LOGDEBUG, LOGVIDEO, LOGWARNING, m_input_dxgi_format, m_pEnumerator, m_pEnumerator1, and m_section.
Referenced by CRendererDXVA::GetWeight().
UnInit()
void CEnumeratorHD::UnInit () protected
References Close().
Referenced by OnDestroyDevice(), and ~CEnumeratorHD().
Member Data Documentation
m_height
uint32_t DXVA::CEnumeratorHD::m_height = 0 protected
Referenced by OnCreateDevice(), Open(), and OpenEnumerator().
m_input_dxgi_format
DXGI_FORMAT DXVA::CEnumeratorHD::m_input_dxgi_format {DXGI_FORMAT_UNKNOWN} protected
Referenced by LogAndListConversions(), Open(), and SupportedConversions().
m_pEnumerator
ComPtr<ID3D11VideoProcessorEnumerator> DXVA::CEnumeratorHD::m_pEnumerator protected
Referenced by CheckConversionInternal(), Close(), CreateVideoProcessor(), CreateVideoProcessorInputView(), CreateVideoProcessorOutputView(), GetProcessorFormats(), IsFormatSupportedInternal(), IsInitialized(), ListConversions(), LogSupportedConversions(), OpenEnumerator(), ProbeProcessorCaps(), and SupportedConversions().
m_pEnumerator1
ComPtr<ID3D11VideoProcessorEnumerator1> DXVA::CEnumeratorHD::m_pEnumerator1 protected
Referenced by CheckConversionInternal(), Close(), IsEnumerator1Available(), ListConversions(), LogSupportedConversions(), OpenEnumerator(), and SupportedConversions().
m_pVideoDevice
ComPtr<ID3D11VideoDevice> DXVA::CEnumeratorHD::m_pVideoDevice protected
Referenced by Close(), CreateVideoProcessor(), CreateVideoProcessorInputView(), CreateVideoProcessorOutputView(), and OpenEnumerator().
m_section
CCriticalSection DXVA::CEnumeratorHD::m_section protected
Referenced by CheckConversion(), Close(), CreateVideoProcessor(), CreateVideoProcessorInputView(), CreateVideoProcessorOutputView(), IsFormatSupportedInput(), IsFormatSupportedOutput(), LogSupportedConversions(), OnCreateDevice(), OnDestroyDevice(), Open(), ProbeProcessorCaps(), SupportedConversions(), and ~CEnumeratorHD().
m_width
uint32_t DXVA::CEnumeratorHD::m_width = 0 protected
Referenced by OnCreateDevice(), Open(), and OpenEnumerator().
The documentation for this class was generated from the following files:
DXVAEnumeratorHD.h
DXVAEnumeratorHD.cpp