Kodi Documentation: JSONRPC::CPVROperations Class Reference
JSONRPC::CPVROperations Class Reference
#include <PVROperations.h>
Static Public Member Functions
static JSONRPC_STATUS GetProperties (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetChannelGroups (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetChannelGroupDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetChannels (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetChannelDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetClients (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetBroadcasts (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetBroadcastDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetBroadcastIsPlayable (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetTimers (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetTimerDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetRecordings (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetRecordingDetails (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS AddTimer (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS DeleteTimer (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS ToggleTimer (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Record (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Scan (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static std::shared_ptr< CFileItem > GetRecordingFileItem (int recordingId)
Static Public Member Functions inherited from JSONRPC::CJSONUtils
static void MillisecondsToTimeObject (int time, CVariant &result)
Static Private Member Functions
static JSONRPC_STATUS GetPropertyValue (const std::string &property, CVariant &result)
static void FillChannelGroupDetails (const std::shared_ptr< const PVR::CPVRChannelGroup > &channelGroup, const CVariant &parameterObject, CVariant &result, bool append=false)
Additional Inherited Members
Static Protected Member Functions inherited from JSONRPC::CFileItemHandler
static void FillDetails (const ISerializable *info, const std::shared_ptr< CFileItem > &item, std::set< std::string > &fields, CVariant &result, CThumbLoader *thumbLoader=nullptr)
static void HandleFileItemList (const char *ID, bool allowFile, const char *resultname, CFileItemList &items, const CVariant &parameterObject, CVariant &result, bool sortLimit=true)
static void HandleFileItemList (const char *ID, bool allowFile, const char *resultname, CFileItemList &items, const CVariant &parameterObject, CVariant &result, int size, bool sortLimit=true)
static void HandleFileItem (const char *ID, bool allowFile, const char *resultname, const std::shared_ptr< CFileItem > &item, const CVariant &parameterObject, const CVariant &validFields, CVariant &result, bool append=true, CThumbLoader *thumbLoader=nullptr)
static void HandleFileItem (const char *ID, bool allowFile, const char *resultname, const std::shared_ptr< CFileItem > &item, const CVariant &parameterObject, const std::set< std::string > &validFields, CVariant &result, bool append=true, CThumbLoader *thumbLoader=nullptr)
static bool FillFileItemList (const CVariant &parameterObject, CFileItemList &list)
Static Protected Member Functions inherited from JSONRPC::CJSONUtils
static void HandleLimits (const CVariant &parameterObject, CVariant &result, int size, int &start, int &end)
static bool ParseSorting (const CVariant &parameterObject, SortBy &sortBy, SortOrder &sortOrder, SortAttribute &sortAttributes)
static void ParseLimits (const CVariant &parameterObject, int &limitStart, int &limitEnd)
static bool ParameterExists (const CVariant &parameterObject, const std::string &key, unsigned int position)
Checks if the given object contains a parameter.
static bool IsValueMember (const CVariant &value, const std::string &key)
Checks if the given object contains a value with the given key.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position)
Returns the json value of a parameter.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position, const CVariant &fallback)
Returns the json value of a parameter or the given default value.
static std::string GetString (const CVariant &value, const char *defaultValue)
Returns the given json value as a string.
static TransportLayerCapability StringToTransportLayer (const std::string &transport)
Returns a TransportLayerCapability value of the given string representation.
static JSONSchemaType StringToSchemaValueType (const std::string &valueType)
Returns a JSONSchemaType value for the given string representation.
static std::string SchemaValueTypeToString (JSONSchemaType valueType)
Returns a string representation for the given JSONSchemaType.
static void SchemaValueTypeToJson (JSONSchemaType valueType, CVariant &jsonObject)
Converts the given json schema type into a json object.
static const char * ValueTypeToString (CVariant::VariantType valueType)
static bool IsParameterType (const CVariant &parameterObject, const char *key, unsigned int position, JSONSchemaType valueType)
Checks if the parameter with the given name or at the given position is of a certain type.
static bool IsType (const CVariant &value, JSONSchemaType valueType)
Checks if the given json value is of the given type.
static void SetDefaultValue (CVariant &value, JSONSchemaType valueType)
Sets the value of the given json value to the default value of the given type.
static bool HasType (JSONSchemaType typeObject, JSONSchemaType type)
static bool ParameterNotNull (const CVariant &parameterObject, const std::string &key)
static void CopyStringArray (const CVariant &jsonStringArray, std::vector< std::string > &stringArray)
Copies the values from the jsonStringArray to the stringArray. stringArray is cleared.
static void SetFromDBDate (const CVariant &jsonDate, CDateTime &date)
static void SetFromDBDateTime (const CVariant &jsonDate, CDateTime &date)
static bool GetXspFiltering (const std::string &type, const CVariant &filter, std::string &xsp)
Member Function Documentation
AddTimer()
JSONRPC_STATUS CPVROperations::AddTimer (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, AddTimer(), PVR::CPVRTimerInfoTag::CreateFromEpg(), PVR::CPVRManager::EpgContainer(), JSONRPC::FailedToExecute, CServiceBroker::GetPVRManager(), PVR::CPVREpgContainer::GetTagByDatabaseId(), JSONRPC::InvalidParams, and PVR::Timers.
Referenced by AddTimer(), and ToggleTimer().
DeleteTimer()
JSONRPC_STATUS CPVROperations::DeleteTimer (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, JSONRPC::FailedToExecute, CServiceBroker::GetPVRManager(), JSONRPC::InvalidParams, and PVR::CPVRManager::Timers().
FillChannelGroupDetails()
void CPVROperations::FillChannelGroupDetails (const std::shared_ptr< const PVR::CPVRChannelGroup > & channelGroup, const CVariant & parameterObject, CVariant & result, bool append = false) static private
References CFileItemList::Add(), CVariant::append(), JSONRPC::CFileItemHandler::HandleFileItemList(), CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
Referenced by GetChannelGroupDetails(), and GetChannelGroups().
GetBroadcastDetails()
JSONRPC_STATUS CPVROperations::GetBroadcastDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References PVR::CPVRManager::EpgContainer(), JSONRPC::FailedToExecute, CServiceBroker::GetPVRManager(), PVR::CPVREpgContainer::GetTagByDatabaseId(), JSONRPC::CFileItemHandler::HandleFileItem(), JSONRPC::InvalidParams, and JSONRPC::OK.
GetBroadcastIsPlayable()
JSONRPC_STATUS CPVROperations::GetBroadcastIsPlayable (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References PVR::CPVRManager::EpgContainer(), JSONRPC::FailedToExecute, CServiceBroker::GetPVRManager(), PVR::CPVREpgContainer::GetTagByDatabaseId(), JSONRPC::InvalidParams, and JSONRPC::OK.
GetBroadcasts()
JSONRPC_STATUS CPVROperations::GetBroadcasts (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CFileItemList::Add(), PVR::CPVRManager::ChannelGroups(), JSONRPC::FailedToExecute, CServiceBroker::GetPVRManager(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::InternalError, JSONRPC::InvalidParams, JSONRPC::OK, CFileItemList::Size(), and tags.
GetChannelDetails()
JSONRPC_STATUS CPVROperations::GetChannelDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References PVR::CPVRManager::ChannelGroups(), JSONRPC::FailedToExecute, PVR::CPVRManager::Get(), CServiceBroker::GetPVRManager(), JSONRPC::CFileItemHandler::HandleFileItem(), JSONRPC::InvalidParams, and JSONRPC::OK.
GetChannelGroupDetails()
JSONRPC_STATUS CPVROperations::GetChannelGroupDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References PVR::CPVRManager::ChannelGroups(), JSONRPC::FailedToExecute, FillChannelGroupDetails(), CServiceBroker::GetPVRManager(), JSONRPC::InvalidParams, and JSONRPC::OK.
GetChannelGroups()
JSONRPC_STATUS CPVROperations::GetChannelGroups (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References PVR::CPVRManager::ChannelGroups(), end(), JSONRPC::FailedToExecute, FillChannelGroupDetails(), CServiceBroker::GetPVRManager(), JSONRPC::CJSONUtils::HandleLimits(), index(), and JSONRPC::OK.
GetChannels()
JSONRPC_STATUS CPVROperations::GetChannels (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CFileItemList::Add(), PVR::CPVRManager::ChannelGroups(), JSONRPC::FailedToExecute, CServiceBroker::GetPVRManager(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::InvalidParams, and JSONRPC::OK.
GetClients()
JSONRPC_STATUS CPVROperations::GetClients (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::append(), PVR::CPVRManager::Clients(), end(), JSONRPC::FailedToExecute, CServiceBroker::GetPVRManager(), JSONRPC::CJSONUtils::HandleLimits(), index(), and JSONRPC::OK.
GetProperties()
JSONRPC_STATUS CPVROperations::GetProperties (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CVariant::asString(), JSONRPC::FailedToExecute, GetPropertyValue(), CServiceBroker::GetPVRManager(), index(), JSONRPC::OK, CVariant::size(), and CVariant::VariantTypeObject.
GetPropertyValue()
JSONRPC_STATUS CPVROperations::GetPropertyValue (const std::string & property, CVariant & result) static private
References PVR::CPVRManager::Get(), CServiceBroker::GetPVRManager(), JSONRPC::InvalidParams, PVR::CPVRManager::IsStarted(), JSONRPC::OK, and PVR::CPVRManager::PlaybackState().
Referenced by GetProperties().
GetRecordingDetails()
JSONRPC_STATUS CPVROperations::GetRecordingDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::FailedToExecute, CServiceBroker::GetPVRManager(), JSONRPC::CFileItemHandler::HandleFileItem(), JSONRPC::InvalidParams, JSONRPC::OK, and PVR::CPVRManager::Recordings().
GetRecordingFileItem()
std::shared_ptr< CFileItem > CPVROperations::GetRecordingFileItem (int recordingId) static
References CServiceBroker::GetPVRManager(), and PVR::CPVRManager::Recordings().
Referenced by JSONRPC::CVideoLibrary::FillFileItemList().
GetRecordings()
JSONRPC_STATUS CPVROperations::GetRecordings (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CFileItemList::Add(), JSONRPC::FailedToExecute, CServiceBroker::GetPVRManager(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::OK, and PVR::CPVRManager::Recordings().
GetTimerDetails()
JSONRPC_STATUS CPVROperations::GetTimerDetails (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::FailedToExecute, CServiceBroker::GetPVRManager(), JSONRPC::CFileItemHandler::HandleFileItem(), JSONRPC::InvalidParams, JSONRPC::OK, and PVR::CPVRManager::Timers().
GetTimers()
JSONRPC_STATUS CPVROperations::GetTimers (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CFileItemList::Add(), JSONRPC::FailedToExecute, CServiceBroker::GetPVRManager(), JSONRPC::CFileItemHandler::HandleFileItemList(), JSONRPC::OK, tags, and PVR::CPVRManager::Timers().
Record()
JSONRPC_STATUS CPVROperations::Record (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, PVR::CPVRManager::ChannelGroups(), JSONRPC::FailedToExecute, CServiceBroker::GetPVRManager(), JSONRPC::InternalError, JSONRPC::InvalidParams, PVR::CPVRManager::PlaybackState(), and PVR::CPVRManager::Timers().
Scan()
JSONRPC_STATUS CPVROperations::Scan (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, JSONRPC::FailedToExecute, CServiceBroker::GetPVRManager(), and CVariant::isMember().
ToggleTimer()
JSONRPC_STATUS CPVROperations::ToggleTimer (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, AddTimer(), CVariant::asBoolean(), PVR::CPVRTimerInfoTag::CreateFromEpg(), PVR::CPVRManager::EpgContainer(), JSONRPC::FailedToExecute, PVR::CPVRManager::Get(), CServiceBroker::GetPVRManager(), PVR::CPVREpgContainer::GetTagByDatabaseId(), JSONRPC::InvalidParams, and PVR::CPVRManager::Timers().
The documentation for this class was generated from the following files:
PVROperations.h
PVROperations.cpp