Kodi Documentation: XFILE::CShoutcastFile Class Reference
XFILE::CShoutcastFile Class Reference
#include <ShoutcastFile.h>
Public Member Functions
CShoutcastFile ()
~CShoutcastFile () override
int64_t GetPosition () override
int64_t GetLength () override
bool Open (const CURL &url) override
bool Exists (const CURL &url) override
int Stat (const CURL &url, struct __stat64 *buffer) override
ssize_t Read (void *lpBuf, size_t uiBufSize) override
int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET) override
void Close () override
int IoControl (EIoControl request, void *param) override
void Process () override
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool OpenForWrite (const CURL &url, bool bOverWrite=false)
virtual bool ReOpen (const CURL &url)
virtual int Stat (struct __stat64 *buffer)
virtual ssize_t Write (const void *bufPtr, size_t bufSize)
virtual bool ReadString (char *szLine, int iLineLength)
virtual void Flush ()
virtual int Truncate (int64_t size)
virtual int GetChunkSize ()
virtual double GetDownloadSpeed ()
virtual bool Delete (const CURL &url)
virtual bool Rename (const CURL &url, const CURL &urlnew)
virtual bool SetHidden (const CURL &url, bool hidden)
virtual const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
virtual const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Protected Member Functions
bool ExtractTagInfo (const char *buf)
void ReadTruncated (char *buf2, int size)
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Private Types
using TagInfo = std::pair< int64_t, std::shared_ptr< MUSIC_INFO::CMusicInfoTag > >
Private Member Functions
std::string DecodeToUTF8 (const std::string &str)
Private Attributes
CCurlFile m_file
std::string m_fileCharset
int m_metaint
int m_discarded
int m_currint
char * m_buffer
std::string m_title
CFileCache * m_cacheReader
CEvent m_tagChange
CCriticalSection m_tagSection
std::queue< TagInfo > m_tags
std::shared_ptr< MUSIC_INFO::CMusicInfoTag > m_masterTag
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Member Typedef Documentation
TagInfo
using XFILE::CShoutcastFile::TagInfo = std::pair<int64_t, std::shared_ptr<MUSIC_INFO::CMusicInfoTag> > private
Constructor & Destructor Documentation
CShoutcastFile()
CShoutcastFile::CShoutcastFile ()
References m_buffer, m_cacheReader, m_currint, m_discarded, and m_metaint.
~CShoutcastFile()
CShoutcastFile::~CShoutcastFile () override
References Close().
Member Function Documentation
Close()
void CShoutcastFile::Close () override virtual
Implements XFILE::IFile.
References XFILE::CCurlFile::Close(), m_buffer, m_file, m_masterTag, m_tagChange, m_tags, m_tagSection, m_title, CEvent::Set(), and CThread::StopThread().
Referenced by ~CShoutcastFile().
DecodeToUTF8()
std::string CShoutcastFile::DecodeToUTF8 (const std::string & str) private
References HTML::CHTMLUtil::ConvertHTMLToW(), g_charsetConverter, and m_fileCharset.
Referenced by ExtractTagInfo(), and Open().
Exists()
bool XFILE::CShoutcastFile::Exists (const CURL & url) inline override virtual
Implements XFILE::IFile.
ExtractTagInfo()
bool CShoutcastFile::ExtractTagInfo (const char * buf) protected
References CVariant::asString(), DecodeToUTF8(), CURL::Get(), XFILE::CCurlFile::Get(), XFILE::CCurlFile::GetHttpHeader(), CRegExp::GetMatch(), CHttpHeader::GetMimeType(), CUrlOptions::GetOptions(), XFILE::CCurlFile::GetPosition(), CURL::GetProtocol(), CServiceBroker::GetSettingsComponent(), m_file, m_masterTag, m_tagChange, m_tags, m_tagSection, m_title, CJSONVariantParser::Parse(), CRegExp::RegComp(), CRegExp::RegFind(), and CEvent::Set().
Referenced by Read().
GetLength()
int64_t CShoutcastFile::GetLength () override virtual
Implements XFILE::IFile.
GetPosition()
int64_t CShoutcastFile::GetPosition () override virtual
Implements XFILE::IFile.
References XFILE::CCurlFile::GetPosition(), m_discarded, and m_file.
IoControl()
int CShoutcastFile::IoControl (EIoControl request, void * param) override virtual
Reimplemented from XFILE::IFile.
References CThread::Create(), XFILE::IFile::IoControl(), XFILE::IOCTRL_SET_CACHE, m_cacheReader, and m_tagSection.
Open()
bool CShoutcastFile::Open (const CURL & url) override virtual
Implements XFILE::IFile.
References DecodeToUTF8(), XFILE::FILE_PROPERTY_CONTENT_CHARSET, XFILE::CCurlFile::GetHttpHeader(), XFILE::CCurlFile::GetProperty(), CURL::GetProtocol(), CURL::GetProtocolOptions(), CHttpHeader::GetValue(), m_buffer, m_file, m_fileCharset, m_masterTag, m_metaint, m_tagChange, m_tags, m_tagSection, XFILE::CCurlFile::Open(), CEvent::Set(), CURL::SetProtocol(), and CURL::SetProtocolOptions().
Process()
void CShoutcastFile::Process (void) override virtual
Reimplemented from CThread.
References CServiceBroker::GetAppMessenger(), XFILE::CFileCache::GetPosition(), CThread::m_bStop, m_cacheReader, m_tagChange, m_tags, m_tagSection, CThread::Sleep(), TMSG_UPDATE_CURRENT_ITEM, and CEvent::Wait().
Read()
ssize_t CShoutcastFile::Read (void * bufPtr, size_t bufSize) override virtual
Attempt to read bufSize bytes from currently opened file into buffer bufPtr.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully read bytes if any bytes were read and stored in buffer, zero if no bytes are available to read (end of file was reached) or undetectable error occur, -1 in case of any explicit error
Implements XFILE::IFile.
References ExtractTagInfo(), m_buffer, m_currint, m_discarded, m_file, m_metaint, XFILE::CCurlFile::Read(), ReadTruncated(), and SSIZE_MAX.
ReadTruncated()
void CShoutcastFile::ReadTruncated (char * buf2, int size) protected
References m_file, and XFILE::CCurlFile::Read().
Referenced by Read().
Seek()
int64_t CShoutcastFile::Seek (int64_t iFilePosition, int iWhence = SEEK_SET) override virtual
Implements XFILE::IFile.
Stat()
int XFILE::CShoutcastFile::Stat (const CURL & url, struct __stat64 * buffer) inline override virtual
Fills struct __stat64 with information about file specified by url. For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
url specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Implements XFILE::IFile.
Member Data Documentation
m_buffer
char* XFILE::CShoutcastFile::m_buffer private
Referenced by Close(), CShoutcastFile(), Open(), and Read().
m_cacheReader
CFileCache* XFILE::CShoutcastFile::m_cacheReader private
Referenced by CShoutcastFile(), IoControl(), and Process().
m_currint
int XFILE::CShoutcastFile::m_currint private
Referenced by CShoutcastFile(), and Read().
m_discarded
int XFILE::CShoutcastFile::m_discarded private
Referenced by CShoutcastFile(), GetPosition(), and Read().
m_file
CCurlFile XFILE::CShoutcastFile::m_file private
Referenced by Close(), ExtractTagInfo(), GetPosition(), Open(), Read(), and ReadTruncated().
m_fileCharset
std::string XFILE::CShoutcastFile::m_fileCharset private
Referenced by DecodeToUTF8(), and Open().
m_masterTag
std::shared_ptr<MUSIC_INFO::CMusicInfoTag> XFILE::CShoutcastFile::m_masterTag private
Referenced by Close(), ExtractTagInfo(), and Open().
m_metaint
int XFILE::CShoutcastFile::m_metaint private
Referenced by CShoutcastFile(), Open(), and Read().
m_tagChange
CEvent XFILE::CShoutcastFile::m_tagChange private
Referenced by Close(), ExtractTagInfo(), Open(), and Process().
m_tags
std::queue<TagInfo> XFILE::CShoutcastFile::m_tags private
Referenced by Close(), ExtractTagInfo(), Open(), and Process().
m_tagSection
CCriticalSection XFILE::CShoutcastFile::m_tagSection private
Referenced by Close(), ExtractTagInfo(), IoControl(), Open(), and Process().
m_title
std::string XFILE::CShoutcastFile::m_title private
Referenced by Close(), and ExtractTagInfo().
The documentation for this class was generated from the following files:
ShoutcastFile.h
ShoutcastFile.cpp