Kodi Documentation: CScriptInvocationManager Class Reference
CScriptInvocationManager Class Reference
#include <ScriptInvocationManager.h>
Classes
struct LanguageInvokerThread
Public Member Functions
void Process ()
void Uninitialize ()
void RegisterLanguageInvocationHandler (ILanguageInvocationHandler *invocationHandler, const std::string &extension)
void RegisterLanguageInvocationHandler (ILanguageInvocationHandler *invocationHandler, const std::set< std::string > &extensions)
void UnregisterLanguageInvocationHandler (ILanguageInvocationHandler *invocationHandler)
bool HasLanguageInvoker (const std::string &script) const
LanguageInvokerPtr GetLanguageInvoker (const std::string &script)
int GetReusablePluginHandle (const std::string &script)
Returns addon_handle if last reusable invoker is ready to use.
int ExecuteAsync (const std::string &script, const ADDON::AddonPtr &addon=ADDON::AddonPtr(), const std::vector< std::string > &arguments=std::vector< std::string >(), bool reuseable=false, int pluginHandle=-1)
Executes the given script asynchronously in a separate thread.
int ExecuteAsync (const std::string &script, const LanguageInvokerPtr &languageInvoker, const ADDON::AddonPtr &addon=ADDON::AddonPtr(), const std::vector< std::string > &arguments=std::vector< std::string >(), bool reuseable=false, int pluginHandle=-1)
Executes the given script asynchronously in a separate thread.
int ExecuteSync (const std::string &script, const ADDON::AddonPtr &addon=ADDON::AddonPtr(), const std::vector< std::string > &arguments=std::vector< std::string >(), uint32_t timeoutMs=0, bool waitShutdown=false)
Executes the given script synchronously.
int ExecuteSync (const std::string &script, const LanguageInvokerPtr &languageInvoker, const ADDON::AddonPtr &addon=ADDON::AddonPtr(), const std::vector< std::string > &arguments=std::vector< std::string >(), uint32_t timeoutMs=0, bool waitShutdown=false)
Executes the given script synchronously.
bool Stop (int scriptId, bool wait=false)
bool Stop (const std::string &scriptPath, bool wait=false)
void StopRunningScripts (bool wait=false)
Stop all running scripts.
bool IsRunning (int scriptId) const
bool IsRunning (const std::string &scriptPath) const
Static Public Member Functions
static CScriptInvocationManager & GetInstance ()
Protected Member Functions
void OnExecutionDone (int scriptId)
Private Types
typedef std::map< int, LanguageInvokerThread > LanguageInvokerThreadMap
typedef std::map< std::string, ILanguageInvocationHandler * > LanguageInvocationHandlerMap
Private Member Functions
CScriptInvocationManager ()=default
CScriptInvocationManager (const CScriptInvocationManager &)=delete
CScriptInvocationManager const & operator= (CScriptInvocationManager const &)=delete
virtual ~CScriptInvocationManager ()
LanguageInvokerThread getInvokerThread (int scriptId) const
Private Attributes
LanguageInvocationHandlerMap m_invocationHandlers
LanguageInvokerThreadMap m_scripts
CLanguageInvokerThreadPtr m_lastInvokerThread
int m_lastPluginHandle = -1
std::map< std::string, int > m_scriptPaths
int m_nextId = 0
CCriticalSection m_critSection
Friends
class CLanguageInvokerThread
Member Typedef Documentation
LanguageInvocationHandlerMap
typedef std::map<std::string, ILanguageInvocationHandler*> CScriptInvocationManager::LanguageInvocationHandlerMap private
LanguageInvokerThreadMap
typedef std::map<int, LanguageInvokerThread> CScriptInvocationManager::LanguageInvokerThreadMap private
Constructor & Destructor Documentation
CScriptInvocationManager() [1/2]
CScriptInvocationManager::CScriptInvocationManager () private default
CScriptInvocationManager() [2/2]
CScriptInvocationManager::CScriptInvocationManager (const CScriptInvocationManager &) private delete
~CScriptInvocationManager()
CScriptInvocationManager::~CScriptInvocationManager () private virtual
References Uninitialize().
Member Function Documentation
ExecuteAsync() [1/2]
int CScriptInvocationManager::ExecuteAsync (const std::string & script, const ADDON::AddonPtr & addon = ADDON::AddonPtr(), const std::vector< std::string > & arguments = std::vector<std::string>(), bool reuseable = false, int pluginHandle = -1)
Executes the given script asynchronously in a separate thread.
Parameters
script Path to the script to be executed
addon (Optional) Addon to which the script belongs
arguments (Optional) List of arguments passed to the script
Returns
-1 if an error occurred, otherwise the ID of the script
References ExecuteAsync(), CFileUtils::Exists(), GetLanguageInvoker(), CLog::Log(), and LOGERROR.
Referenced by CApplicationPowerHandling::ActivateScreenSaver(), ExecuteAsync(), CScriptRunner::ExecuteScript(), ExecuteSync(), CApplication::ExecuteXBMCAction(), CApplication::OnApplicationMessage(), CGUIMediaWindow::OnClick(), CGUIWindowFileManager::OnStart(), RunScript(), and ADDON::CServiceAddonManager::Start().
ExecuteAsync() [2/2]
int CScriptInvocationManager::ExecuteAsync (const std::string & script, const LanguageInvokerPtr & languageInvoker, const ADDON::AddonPtr & addon = ADDON::AddonPtr(), const std::vector< std::string > & arguments = std::vector<std::string>(), bool reuseable = false, int pluginHandle = -1)
Executes the given script asynchronously in a separate thread.
Parameters
script Path to the script to be executed
languageInvoker Language invoker to be used to execute the script
addon (Optional) Addon to which the script belongs
arguments (Optional) List of arguments passed to the script
Returns
-1 if an error occurred, otherwise the ID of the script
References CFileUtils::Exists(), CLog::Log(), LOGERROR, m_critSection, m_lastInvokerThread, m_lastPluginHandle, m_nextId, m_scriptPaths, and m_scripts.
ExecuteSync() [1/2]
int CScriptInvocationManager::ExecuteSync (const std::string & script, const ADDON::AddonPtr & addon = ADDON::AddonPtr(), const std::vector< std::string > & arguments = std::vector<std::string>(), uint32_t timeoutMs = 0, bool waitShutdown = false)
Executes the given script synchronously.
The script is actually executed asynchronously but the calling thread is blocked until either the script has finished or the given timeout has expired. If the given timeout has expired the script's execution is stopped and depending on the specified wait behaviour we wait for the script's execution to finish or not.
Parameters
script Path to the script to be executed
addon (Optional) Addon to which the script belongs
arguments (Optional) List of arguments passed to the script
timeout (Optional) Timeout (in milliseconds) for the script's execution
waitShutdown (Optional) Whether to wait when having to forcefully stop the script's execution or not.
Returns
-1 if an error occurred, 0 if the script terminated or ETIMEDOUT if the given timeout expired
References ExecuteSync(), CFileUtils::Exists(), GetLanguageInvoker(), CLog::Log(), and LOGERROR.
Referenced by ExecuteSync(), and CHTTPPythonHandler::HandleRequest().
ExecuteSync() [2/2]
int CScriptInvocationManager::ExecuteSync (const std::string & script, const LanguageInvokerPtr & languageInvoker, const ADDON::AddonPtr & addon = ADDON::AddonPtr(), const std::vector< std::string > & arguments = std::vector<std::string>(), uint32_t timeoutMs = 0, bool waitShutdown = false)
Executes the given script synchronously.
The script is actually executed asynchronously but the calling thread is blocked until either the script has finished or the given timeout has expired. If the given timeout has expired the script's execution is stopped and depending on the specified wait behaviour we wait for the script's execution to finish or not.
Parameters
script Path to the script to be executed
languageInvoker Language invoker to be used to execute the script
addon (Optional) Addon to which the script belongs
arguments (Optional) List of arguments passed to the script
timeout (Optional) Timeout (in milliseconds) for the script's execution
waitShutdown (Optional) Whether to wait when having to forcefully stop the script's execution or not.
Returns
-1 if an error occurred, 0 if the script terminated or ETIMEDOUT if the given timeout expired
References ExecuteAsync(), IsRunning(), KODI::TIME::Sleep(), and Stop().
GetInstance()
CScriptInvocationManager & CScriptInvocationManager::GetInstance () static
Referenced by CApplicationPowerHandling::ActivateScreenSaver(), CApplication::Cleanup(), CServiceManager::DeinitStageOne(), CWeatherJob::DoWork(), CContextMenuItem::Execute(), CScriptRunner::ExecuteScript(), CApplication::ExecuteXBMCAction(), CHTTPPythonHandler::HandleRequest(), CServiceManager::InitStageOne(), CApplication::OnApplicationMessage(), CGUIMediaWindow::OnClick(), CGUIWindowFileManager::OnStart(), CApplication::Process(), CRunningScriptObserver::Run(), RunScript(), CRunningScriptsHandler< TScript >::RunScript(), ADDON::CServiceAddonManager::Start(), ADDON::CServiceAddonManager::Stop(), CApplication::Stop(), StopScript(), and CScriptRunner::WaitOnScriptResult().
getInvokerThread()
CScriptInvocationManager::LanguageInvokerThread CScriptInvocationManager::getInvokerThread (int scriptId) const private
References m_scripts.
Referenced by IsRunning(), and Stop().
GetLanguageInvoker()
LanguageInvokerPtr CScriptInvocationManager::GetLanguageInvoker (const std::string & script)
References URIUtils::GetExtension(), CLog::Log(), LOGDEBUG, m_critSection, m_invocationHandlers, and m_lastInvokerThread.
Referenced by ExecuteAsync(), and ExecuteSync().
GetReusablePluginHandle()
int CScriptInvocationManager::GetReusablePluginHandle (const std::string & script)
Returns addon_handle if last reusable invoker is ready to use.
References m_critSection, m_lastInvokerThread, and m_lastPluginHandle.
Referenced by CRunningScriptsHandler< TScript >::RunScript().
HasLanguageInvoker()
bool CScriptInvocationManager::HasLanguageInvoker (const std::string & script) const
References URIUtils::GetExtension(), m_critSection, and m_invocationHandlers.
IsRunning() [1/2]
bool CScriptInvocationManager::IsRunning (const std::string & scriptPath) const
References IsRunning(), m_critSection, and m_scriptPaths.
IsRunning() [2/2]
bool CScriptInvocationManager::IsRunning (int scriptId) const
References CScriptInvocationManager::LanguageInvokerThread::done, getInvokerThread(), m_critSection, and CScriptInvocationManager::LanguageInvokerThread::thread.
Referenced by ExecuteSync(), IsRunning(), and CScriptRunner::WaitOnScriptResult().
OnExecutionDone()
void CScriptInvocationManager::OnExecutionDone (int scriptId) protected
References m_critSection, and m_scripts.
Referenced by CLanguageInvokerThread::OnException(), and CLanguageInvokerThread::OnExit().
operator=()
CScriptInvocationManager const & CScriptInvocationManager::operator= (CScriptInvocationManager const &) private delete
Process()
void CScriptInvocationManager::Process ()
References m_critSection, m_invocationHandlers, m_scriptPaths, and m_scripts.
Referenced by CApplication::Process(), and Uninitialize().
RegisterLanguageInvocationHandler() [1/2]
void CScriptInvocationManager::RegisterLanguageInvocationHandler (ILanguageInvocationHandler * invocationHandler, const std::set< std::string > & extensions)
References RegisterLanguageInvocationHandler().
RegisterLanguageInvocationHandler() [2/2]
void CScriptInvocationManager::RegisterLanguageInvocationHandler (ILanguageInvocationHandler * invocationHandler, const std::string & extension)
References ILanguageInvocationHandler::Initialize(), m_critSection, and m_invocationHandlers.
Referenced by CServiceManager::InitStageOne(), and RegisterLanguageInvocationHandler().
Stop() [1/2]
bool CScriptInvocationManager::Stop (const std::string & scriptPath, bool wait = false)
References m_critSection, m_scriptPaths, and Stop().
Stop() [2/2]
bool CScriptInvocationManager::Stop (int scriptId, bool wait = false)
References getInvokerThread(), m_critSection, and CScriptInvocationManager::LanguageInvokerThread::thread.
Referenced by ExecuteSync(), Stop(), StopRunningScripts(), StopScript(), and CScriptRunner::WaitOnScriptResult().
StopRunningScripts()
void CScriptInvocationManager::StopRunningScripts (bool wait = false)
Stop all running scripts.
Parameters
wait if kodi should wait for each script to finish (default false)
References m_scripts, and Stop().
Referenced by CApplication::Stop().
Uninitialize()
void CScriptInvocationManager::Uninitialize ()
References m_critSection, m_invocationHandlers, m_lastInvokerThread, m_scriptPaths, m_scripts, and Process().
Referenced by CApplication::Cleanup(), and ~CScriptInvocationManager().
UnregisterLanguageInvocationHandler()
void CScriptInvocationManager::UnregisterLanguageInvocationHandler (ILanguageInvocationHandler * invocationHandler)
References m_critSection, m_invocationHandlers, and ILanguageInvocationHandler::Uninitialize().
Referenced by CServiceManager::DeinitStageOne().
Friends And Related Symbol Documentation
CLanguageInvokerThread
friend class CLanguageInvokerThread friend
Member Data Documentation
m_critSection
CCriticalSection CScriptInvocationManager::m_critSection mutable private
Referenced by ExecuteAsync(), GetLanguageInvoker(), GetReusablePluginHandle(), HasLanguageInvoker(), IsRunning(), IsRunning(), OnExecutionDone(), Process(), RegisterLanguageInvocationHandler(), Stop(), Stop(), Uninitialize(), and UnregisterLanguageInvocationHandler().
m_invocationHandlers
LanguageInvocationHandlerMap CScriptInvocationManager::m_invocationHandlers private
Referenced by GetLanguageInvoker(), HasLanguageInvoker(), Process(), RegisterLanguageInvocationHandler(), Uninitialize(), and UnregisterLanguageInvocationHandler().
m_lastInvokerThread
CLanguageInvokerThreadPtr CScriptInvocationManager::m_lastInvokerThread private
Referenced by ExecuteAsync(), GetLanguageInvoker(), GetReusablePluginHandle(), and Uninitialize().
m_lastPluginHandle
int CScriptInvocationManager::m_lastPluginHandle = -1 private
Referenced by ExecuteAsync(), and GetReusablePluginHandle().
m_nextId
int CScriptInvocationManager::m_nextId = 0 private
Referenced by ExecuteAsync().
m_scriptPaths
std::map<std::string, int> CScriptInvocationManager::m_scriptPaths private
Referenced by ExecuteAsync(), IsRunning(), Process(), Stop(), and Uninitialize().
m_scripts
LanguageInvokerThreadMap CScriptInvocationManager::m_scripts private
Referenced by ExecuteAsync(), getInvokerThread(), OnExecutionDone(), Process(), StopRunningScripts(), and Uninitialize().
The documentation for this class was generated from the following files:
ScriptInvocationManager.h
ScriptInvocationManager.cpp