Kodi Documentation: COverlayCodecWebVTT Class Reference
COverlayCodecWebVTT Class Reference
#include <OverlayCodecWebVTT.h>
Public Member Functions
COverlayCodecWebVTT ()
~COverlayCodecWebVTT () override=default
bool Open (CDVDStreamInfo &hints, CDVDCodecOptions &options) override
OverlayMessage Decode (DemuxPacket *pPacket) override
void Reset () override
void Flush () override
std::shared_ptr< CDVDOverlay > GetOverlay () override
Public Member Functions inherited from CDVDOverlayCodec
CDVDOverlayCodec (const char *name)
virtual ~CDVDOverlayCodec ()=default
const std::string & GetName () const
Private Attributes
std::shared_ptr< CDVDOverlay > m_pOverlay
CWebVTTISOHandler m_webvttHandler
bool m_isISOFormat {false}
bool m_allowFlush {true}
std::vector< int > m_previousSubIds
Additional Inherited Members
Static Protected Member Functions inherited from CDVDOverlayCodec
static void GetAbsoluteTimes (double &starttime, double &stoptime, DemuxPacket *pkt)
Private Member Functions inherited from CSubtitlesAdapter
CSubtitlesAdapter ()
virtual ~CSubtitlesAdapter ()
bool Initialize ()
Initialize the subtitles adapter.
int AddSubtitle (std::string &text, double startTime, double stopTime)
Add a subtitle.
int AddSubtitle (std::string &text, double startTime, double stopTime, KODI::SUBTITLES::STYLE::subtitleOpts *opts)
Add a subtitle with supplementary options.
void AppendToSubtitle (int subtitleId, const char *text)
Append text to the specified subtitle ID.
int DeleteSubtitles (int nSubtitles, int threshold)
Delete old subtitles only if the total number of subtitles added reaches the threshold.
void ChangeSubtitleStopTime (int subtitleId, double stopTime)
Change the stop time of a subtitle ID with the specified time.
void FlushSubtitles ()
std::shared_ptr< CDVDOverlay > CreateOverlay ()
virtual void PostProcess (std::string &text)
Post processing of subtitle, will be called before processing AddSubtitle method.
Constructor & Destructor Documentation
COverlayCodecWebVTT()
COverlayCodecWebVTT::COverlayCodecWebVTT ()
~COverlayCodecWebVTT()
COverlayCodecWebVTT::~COverlayCodecWebVTT () override default
Member Function Documentation
Decode()
OverlayMessage COverlayCodecWebVTT::Decode (DemuxPacket * pPacket) override virtual
Implements CDVDOverlayCodec.
References CSubtitlesAdapter::AddSubtitle(), CSubtitlesAdapter::ChangeSubtitleStopTime(), CWebVTTHandler::CheckSignature(), data(), CWebVTTHandler::DecodeLine(), CWebVTTISOHandler::DecodeStream(), DEMUX_PACKET::dts, DEMUX_PACKET::iSize, m_isISOFormat, m_pOverlay, m_previousSubIds, DemuxPacket::m_ptsOffsetCorrection, m_webvttHandler, KODI::SUBTITLES::STYLE::subtitleOpts::marginLeft, KODI::SUBTITLES::STYLE::subtitleOpts::marginRight, KODI::SUBTITLES::STYLE::subtitleOpts::marginVertical, OC_DONE, OC_ERROR, OC_OVERLAY, DEMUX_PACKET::pData, CCharArrayParser::ReadNextLine(), CWebVTTHandler::Reset(), CCharArrayParser::Reset(), CWebVTTHandler::SetPeriodStart(), and KODI::SUBTITLES::STYLE::subtitleOpts::useMargins.
Flush()
void COverlayCodecWebVTT::Flush () override virtual
Implements CDVDOverlayCodec.
References CSubtitlesAdapter::FlushSubtitles(), m_allowFlush, m_pOverlay, and m_previousSubIds.
Referenced by Reset().
GetOverlay()
std::shared_ptr< CDVDOverlay > COverlayCodecWebVTT::GetOverlay () override virtual
Implements CDVDOverlayCodec.
References CSubtitlesAdapter::CreateOverlay(), CWebVTTHandler::IsForcedMargins(), m_allowFlush, m_pOverlay, and m_webvttHandler.
Open()
bool COverlayCodecWebVTT::Open (CDVDStreamInfo & hints, CDVDCodecOptions & options) override virtual
Implements CDVDOverlayCodec.
References CDVDStreamInfo::extradata, FFmpegExtraData::GetData(), FFmpegExtraData::GetSize(), CSubtitlesAdapter::Initialize(), CWebVTTHandler::Initialize(), m_allowFlush, m_isISOFormat, m_pOverlay, and m_webvttHandler.
Reset()
void COverlayCodecWebVTT::Reset () override virtual
Implements CDVDOverlayCodec.
References Flush().
Member Data Documentation
m_allowFlush
bool COverlayCodecWebVTT::m_allowFlush {true} private
Referenced by Flush(), GetOverlay(), and Open().
m_isISOFormat
bool COverlayCodecWebVTT::m_isISOFormat {false} private
Referenced by Decode(), and Open().
m_pOverlay
std::shared_ptr<CDVDOverlay> COverlayCodecWebVTT::m_pOverlay private
Referenced by Decode(), Flush(), GetOverlay(), and Open().
m_previousSubIds
std::vector<int> COverlayCodecWebVTT::m_previousSubIds private
Referenced by Decode(), and Flush().
m_webvttHandler
CWebVTTISOHandler COverlayCodecWebVTT::m_webvttHandler private
Referenced by Decode(), GetOverlay(), and Open().
The documentation for this class was generated from the following files:
OverlayCodecWebVTT.h
OverlayCodecWebVTT.cpp