Kodi Documentation: CRendererDXVA Class Reference
CRendererDXVA Class Reference
#include <RendererDXVA.h>
Classes
class CRenderBufferImpl
Public Member Functions
~CRendererDXVA ()=default
CRenderInfo GetRenderInfo () override
bool Supports (ESCALINGMETHOD method) const override
bool Supports (ERENDERFEATURE feature) const override
bool WantsDoublePass () override
bool Configure (const VideoPicture &picture, float fps, unsigned orientation) override
bool NeedBuffer (int idx) override
Public Member Functions inherited from CRendererHQ
bool Supports (ESCALINGMETHOD method) const override
Public Member Functions inherited from CRendererBase
virtual ~CRendererBase ()
virtual bool Configure (const VideoPicture &picture, float fps, unsigned int orientation)
void AddVideoPicture (const VideoPicture &picture, int index)
void Render (int index, int index2, CD3DTexture &target, const CRect &sourceRect, const CRect &destRect, const CRect &viewRect, unsigned flags)
void Render (CD3DTexture &target, const CRect &sourceRect, const CRect &destRect, const CRect &viewRect, unsigned flags=0)
void ManageTextures ()
int NextBuffer () const
void ReleaseBuffer (int idx)
bool Flush (bool saveBuffers)
void SetBufferSize (int numBuffers)
DEBUG_INFO_VIDEO GetDebugInfo (int idx)
Static Public Member Functions
static CRendererBase * Create (CVideoSettings &videoSettings)
static void GetWeight (std::map< RenderMethod, int > &weights, const VideoPicture &picture)
static DXGI_FORMAT GetDXGIFormat (AVPixelFormat format, DXGI_FORMAT default_fmt)
Static Public Member Functions inherited from CRendererBase
static DXGI_FORMAT GetDXGIFormat (const VideoPicture &picture)
static DXGI_FORMAT GetDXGIFormat (CVideoBuffer *videoBuffer)
static AVPixelFormat GetAVFormat (DXGI_FORMAT dxgi_format)
static DXGI_HDR_METADATA_HDR10 GetDXGIHDR10MetaData (CRenderBuffer *rb)
Protected Member Functions
CRendererDXVA (CVideoSettings &videoSettings)
void CheckVideoParameters () override
void RenderImpl (CD3DTexture &target, CRect &sourceRect, CPoint(&destPoints)[4], uint32_t flags) override
CRenderBuffer * CreateBuffer () override
virtual std::string GetRenderMethodDebugInfo () const
Protected Member Functions inherited from CRendererHQ
CRendererHQ (CVideoSettings &videoSettings)
virtual ~CRendererHQ ()=default
void OnOutputReset () override
void CheckVideoParameters () override
void UpdateVideoFilters () override
void FinalOutput (CD3DTexture &source, CD3DTexture &target, const CRect &sourceRect, const CPoint(&destPoints)[4]) override
void SelectPSVideoFilter ()
bool HasHQScaler () const
Protected Member Functions inherited from CRendererBase
CRendererBase (CVideoSettings &videoSettings)
bool CreateIntermediateTarget (unsigned int width, unsigned int height, bool dynamic=false, DXGI_FORMAT format=DXGI_FORMAT_UNKNOWN)
void OnCMSConfigChanged (AVColorPrimaries srcPrimaries)
void ReorderDrawPoints (const CRect &destRect, CPoint(&rotatedPoints)[4]) const
bool CreateRenderBuffer (int index)
void DeleteRenderBuffer (int index)
void ProcessHDR (CRenderBuffer *rb)
bool ActualRenderAsHDR ()
Call after rendering has started to find out if the output is configured as SDR or HDR.
virtual void OnViewSizeChanged ()
Private Member Functions
void FillBuffersSet (CRenderBuffer *(&buffers)[8])
CRect ApplyTransforms (const CRect &destRect) const
DXVA::ProcessorConversion ChooseConversion (const DXVA::ProcessorConversions &conversions) const
Choose the best available conversion for the given source and output constraints.
Private Attributes
std::unique_ptr< DXVA::CProcessorHD > m_processor
std::shared_ptr< DXVA::CEnumeratorHD > m_enumerator
DXVA::ProcessorConversion m_conversion
DXVA::SupportedConversionsArgs m_conversionsArgs
bool m_tryVSR {false}
Additional Inherited Members
Static Protected Member Functions inherited from CRendererBase
static bool IntendToRenderAsHDR (const VideoPicture &picture)
Call before rendering begins to find out if rendering will be attempted as SDR or HDR.
Protected Attributes inherited from CRendererHQ
ESCALINGMETHOD m_scalingMethod = VS_SCALINGMETHOD_AUTO
ESCALINGMETHOD m_scalingMethodGui = VS_SCALINGMETHOD_AUTO
std::unique_ptr< CConvolutionShader > m_scalerShader = nullptr
bool m_bUseHQScaler = false
Protected Attributes inherited from CRendererBase
bool m_toneMapping = false
bool m_useDithering = false
bool m_cmsOn = false
bool m_lutIsLoading = false
bool m_useHLGtoPQ = false
ETONEMAPMETHOD m_toneMapMethod = VS_TONEMAPMETHOD_OFF
int m_iBufferIndex = 0
int m_iNumBuffers = 0
int m_iBuffersRequired = 0
int m_ditherDepth = 0
int m_cmsToken = -1
int m_lutSize = 0
unsigned m_sourceWidth = 0
unsigned m_sourceHeight = 0
unsigned m_viewWidth = 0
unsigned m_viewHeight = 0
unsigned m_renderOrientation = 0
float m_fps = 0.0f
uint64_t m_frameIdx = 0
AVPixelFormat m_format = AV_PIX_FMT_NONE
CD3DTexture m_IntermediateTarget
std::shared_ptr< COutputShader > m_outputShader
std::unique_ptr< CColorManager > m_colorManager
Microsoft::WRL::ComPtr< ID3D11ShaderResourceView > m_pLUTView
CVideoSettings & m_videoSettings
std::map< int, CRenderBuffer * > m_renderBuffers
DXGI_HDR_METADATA_HDR10 m_lastHdr10 = {}
HDR_TYPE m_HdrType = HDR_TYPE::HDR_INVALID
bool m_AutoSwitchHDR = false
bool m_initialHdrEnabled = false
std::string m_renderMethodName
Constructor & Destructor Documentation
~CRendererDXVA()
CRendererDXVA::~CRendererDXVA () default
CRendererDXVA()
CRendererDXVA::CRendererDXVA (CVideoSettings & videoSettings) explicit protected
References CRendererBase::m_renderMethodName.
Member Function Documentation
ApplyTransforms()
CRect CRendererDXVA::ApplyTransforms (const CRect & destRect) const private
References CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), CRendererBase::m_renderOrientation, CRendererBase::ReorderDrawPoints(), and CGraphicContext::StereoCorrection().
Referenced by RenderImpl().
CheckVideoParameters()
void CRendererDXVA::CheckVideoParameters () override protected virtual
Reimplemented from CRendererBase.
References CRendererBase::ActualRenderAsHDR(), ChooseConversion(), CRenderBuffer::color_space, CRenderBuffer::color_transfer, CRendererBase::CreateIntermediateTarget(), CRenderBuffer::full_range, CRendererHQ::HasHQScaler(), LOGINFO, m_conversion, m_conversionsArgs, m_enumerator, CRendererBase::m_iBufferIndex, DXVA::ProcessorConversion::m_outputFormat, m_processor, CRendererBase::m_renderBuffers, CRendererBase::m_sourceHeight, CRendererBase::m_sourceWidth, CRendererBase::m_viewHeight, CRendererBase::m_viewWidth, CRenderBuffer::primaries, and DXVA::ProcessorConversion::ToString().
ChooseConversion()
ProcessorConversion CRendererDXVA::ChooseConversion (const DXVA::ProcessorConversions & conversions) const private
Choose the best available conversion for the given source and output constraints.
Parameters
conversions list of supported conversions
Returns
best match
References LOGDEBUG, LOGWARNING, and m_tryVSR.
Referenced by CheckVideoParameters(), and Configure().
Configure()
bool CRendererDXVA::Configure (const VideoPicture & picture, float fps, unsigned orientation) override
References DXVA::CEnumeratorHD::AvToDxgiColorSpace(), ChooseConversion(), GetDXGIFormat(), CVideoBuffer::GetFormat(), CServiceBroker::GetLogging(), VideoPicture::iHeight, CRendererBase::IntendToRenderAsHDR(), DXVA::CProcessorHD::IsSuperResolutionSuitable(), VideoPicture::iWidth, LOGDEBUG, LOGERROR, LOGINFO, LOGVIDEO, m_conversion, m_conversionsArgs, m_enumerator, CRendererBase::m_format, m_processor, m_tryVSR, DXVA::ProcessorConversion::ToString(), and VideoPicture::videoBuffer.
Create()
CRendererBase * CRendererDXVA::Create (CVideoSettings & videoSettings) static
CreateBuffer()
CRenderBuffer * CRendererDXVA::CreateBuffer () override protected virtual
Implements CRendererBase.
References CRendererBase::m_format, CRendererBase::m_sourceHeight, and CRendererBase::m_sourceWidth.
FillBuffersSet()
void CRendererDXVA::FillBuffersSet (CRenderBuffer *(&) buffers[8]) private
References CRenderBuffer::frameIdx, CRendererBase::m_iBufferIndex, CRendererBase::m_iNumBuffers, and CRendererBase::m_renderBuffers.
Referenced by RenderImpl().
GetDXGIFormat()
DXGI_FORMAT CRendererDXVA::GetDXGIFormat (AVPixelFormat format, DXGI_FORMAT default_fmt) static
References CRendererDXVA::CRenderBufferImpl::GetDXGIFormat().
Referenced by Configure(), and GetWeight().
GetRenderInfo()
CRenderInfo CRendererDXVA::GetRenderInfo () override virtual
Reimplemented from CRendererBase.
References VS_INTERLACEMETHOD_DXVA_AUTO.
GetRenderMethodDebugInfo()
std::string CRendererDXVA::GetRenderMethodDebugInfo () const protected virtual
Reimplemented from CRendererBase.
References m_processor.
GetWeight()
void CRendererDXVA::GetWeight (std::map< RenderMethod, int > & weights, const VideoPicture & picture) static
References DVP_FLAG_INTERLACED, DX::DXGIFormatToString(), FAILED, DX::DeviceResources::Get(), GetDXGIFormat(), CVideoBuffer::GetFormat(), VideoPicture::iFlags, VideoPicture::iHeight, VideoPicture::iWidth, LOGWARNING, DXVA::CEnumeratorHD::Open(), RENDER_DXVA, DXVA::CEnumeratorHD::SupportedConversions(), and VideoPicture::videoBuffer.
NeedBuffer()
bool CRendererDXVA::NeedBuffer (int idx) override virtual
Reimplemented from CRendererBase.
References DVP_FLAG_INTERLACED, CRendererBase::m_iBufferIndex, m_processor, and CRendererBase::m_renderBuffers.
RenderImpl()
void CRendererDXVA::RenderImpl (CD3DTexture & target, CRect & sourceRect, CPoint(&) destPoints[4], uint32_t flags) override protected virtual
Implements CRendererBase.
References ApplyTransforms(), CWIN32Util::CropSource(), FillBuffersSet(), CRenderBuffer::frameIdx, CD3DTexture::Get(), CD3DTexture::GetHeight(), CRectGen< T >::GetQuad(), CD3DTexture::GetWidth(), CRendererHQ::HasHQScaler(), CVideoSettings::m_Brightness, CVideoSettings::m_Contrast, CRendererBase::m_iBufferIndex, m_processor, CRendererBase::m_renderBuffers, CRendererBase::m_renderOrientation, and CRendererBase::m_videoSettings.
Supports() [1/2]
bool CRendererDXVA::Supports (ERENDERFEATURE feature) const override virtual
Reimplemented from CRendererBase.
References m_processor, RENDERFEATURE_BRIGHTNESS, RENDERFEATURE_CONTRAST, RENDERFEATURE_ROTATION, and CRendererBase::Supports().
Supports() [2/2]
bool CRendererDXVA::Supports (ESCALINGMETHOD method) const override virtual
Implements CRendererBase.
References VS_SCALINGMETHOD_DXVA_HARDWARE.
WantsDoublePass()
bool CRendererDXVA::WantsDoublePass () inline override virtual
Reimplemented from CRendererBase.
Member Data Documentation
m_conversion
DXVA::ProcessorConversion CRendererDXVA::m_conversion private
Referenced by CheckVideoParameters(), and Configure().
m_conversionsArgs
DXVA::SupportedConversionsArgs CRendererDXVA::m_conversionsArgs private
Referenced by CheckVideoParameters(), and Configure().
m_enumerator
std::shared_ptr<DXVA::CEnumeratorHD> CRendererDXVA::m_enumerator private
Referenced by CheckVideoParameters(), and Configure().
m_processor
std::unique_ptr<DXVA::CProcessorHD> CRendererDXVA::m_processor private
Referenced by CheckVideoParameters(), Configure(), GetRenderMethodDebugInfo(), NeedBuffer(), RenderImpl(), and Supports().
m_tryVSR
bool CRendererDXVA::m_tryVSR {false} private
Referenced by ChooseConversion(), and Configure().
The documentation for this class was generated from the following files:
RendererDXVA.h
RendererDXVA.cpp