Kodi Documentation: CVideoSyncIos Class Reference
CVideoSyncIos Class Reference
#include <VideoSyncIos.h>
Public Member Functions
CVideoSyncIos (CVideoReferenceClock *clock, CWinSystemIOS &winSystem)
bool Setup () override
void Run (CEvent &stopEvent) override
void Cleanup () override
float GetFps () override
void OnResetDisplay () override
void IosVblankHandler ()
Public Member Functions inherited from CVideoSync
CVideoSync (CVideoReferenceClock *clock)
virtual ~CVideoSync ()=default
virtual void RefreshChanged ()
Private Member Functions
virtual bool InitDisplayLink ()
virtual void DeinitDisplayLink ()
Private Member Functions inherited from IDispResource
virtual ~IDispResource ()=default
virtual void OnLostDisplay ()
virtual void OnAppFocusChange (bool focus)
Private Attributes
int64_t m_LastVBlankTime = 0
CEvent m_abortEvent
CWinSystemIOS & m_winSystem
Additional Inherited Members
Protected Attributes inherited from CVideoSync
float m_fps
CVideoReferenceClock * m_refClock
Constructor & Destructor Documentation
CVideoSyncIos()
CVideoSyncIos::CVideoSyncIos (CVideoReferenceClock * clock, CWinSystemIOS & winSystem) inline
Member Function Documentation
Cleanup()
void CVideoSyncIos::Cleanup () override virtual
Implements CVideoSync.
References DeinitDisplayLink(), CLog::Log(), LOGDEBUG, m_winSystem, and CWinSystemIOS::Unregister().
DeinitDisplayLink()
void CVideoSyncIos::DeinitDisplayLink () private virtual
References CWinSystemIOS::DeinitDisplayLink(), and m_winSystem.
Referenced by Cleanup().
GetFps()
float CVideoSyncIos::GetFps () override virtual
Implements CVideoSync.
References CGraphicContext::GetFPS(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, and CVideoSync::m_fps.
InitDisplayLink()
bool CVideoSyncIos::InitDisplayLink () private virtual
References CWinSystemIOS::InitDisplayLink(), CLog::Log(), LOGDEBUG, and m_winSystem.
Referenced by Setup().
IosVblankHandler()
void CVideoSyncIos::IosVblankHandler ()
References CurrentHostCounter(), CurrentHostFrequency(), int64_t(), CVideoSync::m_fps, m_LastVBlankTime, CVideoSync::m_refClock, MathUtils::round_int(), and CVideoReferenceClock::UpdateClock().
OnResetDisplay()
void CVideoSyncIos::OnResetDisplay () override virtual
Reimplemented from IDispResource.
References m_abortEvent, and CEvent::Set().
Run()
void CVideoSyncIos::Run (CEvent & stopEvent) override virtual
Implements CVideoSync.
References m_abortEvent.
Setup()
bool CVideoSyncIos::Setup () override virtual
Implements CVideoSync.
References CurrentHostCounter(), InitDisplayLink(), CLog::Log(), LOGDEBUG, m_abortEvent, m_LastVBlankTime, m_winSystem, CWinSystemIOS::Register(), and CEvent::Reset().
Member Data Documentation
m_abortEvent
CEvent CVideoSyncIos::m_abortEvent private
Referenced by OnResetDisplay(), Run(), and Setup().
m_LastVBlankTime
int64_t CVideoSyncIos::m_LastVBlankTime = 0 private
Referenced by IosVblankHandler(), and Setup().
m_winSystem
CWinSystemIOS& CVideoSyncIos::m_winSystem private
Referenced by Cleanup(), DeinitDisplayLink(), InitDisplayLink(), and Setup().
The documentation for this class was generated from the following files:
VideoSyncIos.h
VideoSyncIos.cpp