Kodi Documentation: CPackerMAT Class Reference
CPackerMAT Class Reference
#include <PackerMAT.h>
Classes
struct MATState
Public Member Functions
CPackerMAT ()
~CPackerMAT ()=default
bool PackTrueHD (const uint8_t *data, int size)
std::vector< uint8_t > GetOutputFrame ()
Private Member Functions
void WriteHeader ()
void WritePadding ()
void AppendData (const uint8_t *data, int size, Type type)
uint32_t GetCount () const
int FillDataBuffer (const uint8_t *data, int size, Type type)
void FlushPacket ()
Private Attributes
MATState m_state {}
uint32_t m_bufferCount {0}
std::vector< uint8_t > m_buffer
std::deque< std::vector< uint8_t > > m_outputQueue
Constructor & Destructor Documentation
CPackerMAT()
CPackerMAT::CPackerMAT ()
References m_buffer.
~CPackerMAT()
CPackerMAT::~CPackerMAT () default
Member Function Documentation
AppendData()
void CPackerMAT::AppendData (const uint8_t * data, int size, Type type) private
References DATA, data(), m_buffer, m_bufferCount, m_state, and CPackerMAT::MATState::matFramesize.
Referenced by FillDataBuffer().
FillDataBuffer()
int CPackerMAT::FillDataBuffer (const uint8_t * data, int size, Type type) private
References AppendData(), DATA, data(), FillDataBuffer(), GetCount(), and PADDING.
Referenced by FillDataBuffer(), PackTrueHD(), and WritePadding().
FlushPacket()
void CPackerMAT::FlushPacket () private
References GetCount(), m_buffer, m_bufferCount, and m_outputQueue.
Referenced by PackTrueHD().
GetCount()
uint32_t CPackerMAT::GetCount () const inline private
References m_bufferCount.
Referenced by FillDataBuffer(), FlushPacket(), and PackTrueHD().
GetOutputFrame()
std::vector< uint8_t > CPackerMAT::GetOutputFrame ()
References m_outputQueue.
PackTrueHD()
bool CPackerMAT::PackTrueHD (const uint8_t * data, int size)
References DATA, data(), FillDataBuffer(), FlushPacket(), GetCount(), CPackerMAT::MATState::init, CLog::Log(), LOGINFO, m_buffer, m_bufferCount, m_outputQueue, m_state, CPackerMAT::MATState::matFramesize, CPackerMAT::MATState::padding, CPackerMAT::MATState::prevFrametime, CPackerMAT::MATState::prevFrametimeValid, CPackerMAT::MATState::prevMatFramesize, CPackerMAT::MATState::ratebits, WriteHeader(), and WritePadding().
WriteHeader()
void CPackerMAT::WriteHeader () private
References m_buffer, m_bufferCount, m_state, CPackerMAT::MATState::matFramesize, and CPackerMAT::MATState::padding.
Referenced by PackTrueHD().
WritePadding()
void CPackerMAT::WritePadding () private
References FillDataBuffer(), m_state, CPackerMAT::MATState::matFramesize, PADDING, and CPackerMAT::MATState::padding.
Referenced by PackTrueHD().
Member Data Documentation
m_buffer
std::vector<uint8_t> CPackerMAT::m_buffer private
Referenced by AppendData(), CPackerMAT(), FlushPacket(), PackTrueHD(), and WriteHeader().
m_bufferCount
uint32_t CPackerMAT::m_bufferCount {0} private
Referenced by AppendData(), FlushPacket(), GetCount(), PackTrueHD(), and WriteHeader().
m_outputQueue
std::deque<std::vector<uint8_t> > CPackerMAT::m_outputQueue private
Referenced by FlushPacket(), GetOutputFrame(), and PackTrueHD().
m_state
MATState CPackerMAT::m_state {} private
Referenced by AppendData(), PackTrueHD(), WriteHeader(), and WritePadding().
The documentation for this class was generated from the following files:
PackerMAT.h
PackerMAT.cpp