Kodi Documentation: CFFmpegImage Class Reference
CFFmpegImage Class Reference
#include <FFmpegImage.h>
Public Member Functions
CFFmpegImage (const std::string &strMimeType)
~CFFmpegImage () override
bool LoadImageFromMemory (unsigned char *buffer, unsigned int bufSize, unsigned int width, unsigned int height) override
Load an image from memory with the format m_strMimeType to determine it's size and orientation.
bool Decode (unsigned char *const pixels, unsigned int width, unsigned int height, unsigned int pitch, unsigned int format) override
Decodes the previously loaded image data to the output buffer in 32 bit raw bits.
bool CreateThumbnailFromSurface (unsigned char *bufferin, unsigned int width, unsigned int height, unsigned int format, unsigned int pitch, const std::string &destFile, unsigned char *&bufferout, unsigned int &bufferoutSize) override
Encodes an thumbnail from raw bits of given memory location.
void ReleaseThumbnailBuffer () override
Frees the output buffer allocated by CreateThumbnailFromSurface.
bool Initialize (unsigned char *buffer, size_t bufSize)
std::shared_ptr< Frame > ReadFrame ()
Public Member Functions inherited from IImage
virtual ~IImage ()=default
unsigned int Width () const
unsigned int Height () const
unsigned int originalWidth () const
unsigned int originalHeight () const
unsigned int Orientation () const
bool hasAlpha () const
Private Member Functions
AVFrame * ExtractFrame ()
bool DecodeFrame (AVFrame *m_pFrame, unsigned int width, unsigned int height, unsigned int pitch, unsigned char *const pixels)
void CleanupLocalOutputBuffer ()
Static Private Member Functions
static void FreeIOCtx (AVIOContext **ioctx)
static int EncodeFFmpegFrame (AVCodecContext *avctx, AVPacket *pkt, int *got_packet, AVFrame *frame)
static int DecodeFFmpegFrame (AVCodecContext *avctx, AVFrame *frame, int *got_frame, AVPacket *pkt)
static AVPixelFormat ConvertFormats (AVFrame *frame)
Private Attributes
std::string m_strMimeType
MemBuffer m_buf
AVIOContext * m_ioctx = nullptr
AVFormatContext * m_fctx = nullptr
AVCodecContext * m_codec_ctx = nullptr
AVFrame * m_pFrame
uint8_t * m_outputBuffer
Additional Inherited Members
Protected Attributes inherited from IImage
unsigned int m_width = 0
unsigned int m_height = 0
unsigned int m_originalWidth = 0
original image width before scaling or cropping
unsigned int m_originalHeight = 0
original image height before scaling or cropping
unsigned int m_orientation = 0
bool m_hasAlpha = false
Constructor & Destructor Documentation
CFFmpegImage()
CFFmpegImage::CFFmpegImage (const std::string & strMimeType) explicit
References IImage::m_hasAlpha, m_outputBuffer, and m_pFrame.
~CFFmpegImage()
CFFmpegImage::~CFFmpegImage () override
References CleanupLocalOutputBuffer(), MemBuffer::data, FreeIOCtx(), m_buf, m_codec_ctx, m_fctx, m_ioctx, m_pFrame, MemBuffer::pos, and MemBuffer::size.
Member Function Documentation
CleanupLocalOutputBuffer()
void CFFmpegImage::CleanupLocalOutputBuffer () private
References m_outputBuffer.
Referenced by CreateThumbnailFromSurface(), ReleaseThumbnailBuffer(), and ~CFFmpegImage().
ConvertFormats()
AVPixelFormat CFFmpegImage::ConvertFormats (AVFrame * frame) static private
Referenced by DecodeFrame().
CreateThumbnailFromSurface()
bool CFFmpegImage::CreateThumbnailFromSurface (unsigned char * bufferin, unsigned int width, unsigned int height, unsigned int format, unsigned int pitch, const std::string & destFile, unsigned char *& bufferout, unsigned int & bufferoutSize) override virtual
Encodes an thumbnail from raw bits of given memory location.
Remarks
Caller need to call ReleaseThumbnailBuffer() afterwards to free the output buffer
Parameters
bufferin The memory location where the image data can be found
width The width of the thumbnail
height The height of the thumbnail
format The format of the input buffer (JpegIO only)
pitch The pitch of the input texture stored in bufferin
destFile The destination path of the thumbnail to determine the image format from the extension
bufferout The output buffer (will be allocated inside the method)
bufferoutSize The output buffer size
Returns
true if the thumbnail was successfully created
Implements IImage.
References ThumbDataManagement::avOutctx, CleanupLocalOutputBuffer(), ThumbDataManagement::codec, EncodeFFmpegFrame(), ThumbDataManagement::frame_input, ThumbDataManagement::frame_temporary, CServiceBroker::GetSettingsComponent(), ThumbDataManagement::intermediateBuffer, CLog::Log(), LOGERROR, m_outputBuffer, m_strMimeType, ThumbDataManagement::sws, table, and XB_FMT_A8R8G8B8.
Decode()
bool CFFmpegImage::Decode (unsigned char *const pixels, unsigned int width, unsigned int height, unsigned int pitch, unsigned int format) override virtual
Decodes the previously loaded image data to the output buffer in 32 bit raw bits.
Parameters
pixels The output buffer
width The width of the image
height The height of the image
pitch The pitch of the output buffer
format The format of the output buffer (JpegIO only)
Returns
true if the image data could be decoded to the output buffer
Implements IImage.
References DecodeFrame(), CLog::Log(), LOGERROR, IImage::m_height, m_pFrame, IImage::m_width, and XB_FMT_A8R8G8B8.
DecodeFFmpegFrame()
int CFFmpegImage::DecodeFFmpegFrame (AVCodecContext * avctx, AVFrame * frame, int * got_frame, AVPacket * pkt) static private
Referenced by ExtractFrame().
DecodeFrame()
bool CFFmpegImage::DecodeFrame (AVFrame * m_pFrame, unsigned int width, unsigned int height, unsigned int pitch, unsigned char *const pixels) private
References ConvertFormats(), CLog::Log(), LOGDEBUG, LOGERROR, IImage::m_height, IImage::m_originalHeight, IImage::m_originalWidth, IImage::m_width, and table.
Referenced by Decode(), and ReadFrame().
EncodeFFmpegFrame()
int CFFmpegImage::EncodeFFmpegFrame (AVCodecContext * avctx, AVPacket * pkt, int * got_packet, AVFrame * frame) static private
Referenced by CreateThumbnailFromSurface().
ExtractFrame()
AVFrame * CFFmpegImage::ExtractFrame () private
References DecodeFFmpegFrame(), CLog::Log(), LOGDEBUG, LOGERROR, m_codec_ctx, m_fctx, IImage::m_hasAlpha, IImage::m_height, IImage::m_orientation, IImage::m_originalHeight, IImage::m_originalWidth, and IImage::m_width.
Referenced by LoadImageFromMemory(), and ReadFrame().
FreeIOCtx()
void CFFmpegImage::FreeIOCtx (AVIOContext ** ioctx) static private
Referenced by Initialize(), and ~CFFmpegImage().
Initialize()
bool CFFmpegImage::Initialize (unsigned char * buffer, size_t bufSize)
References MemBuffer::data, FreeIOCtx(), CLog::Log(), LOGERROR, m_buf, m_codec_ctx, m_fctx, m_ioctx, m_strMimeType, mem_file_read(), mem_file_seek(), MemBuffer::pos, and MemBuffer::size.
Referenced by CGUITextureManager::Load(), and LoadImageFromMemory().
LoadImageFromMemory()
bool CFFmpegImage::LoadImageFromMemory (unsigned char * buffer, unsigned int bufSize, unsigned int width, unsigned int height) override virtual
Load an image from memory with the format m_strMimeType to determine it's size and orientation.
Parameters
buffer The memory location where the image data can be found
bufSize The size of the buffer
width The ideal width of the texture
height The ideal height of the texture
Returns
true if the image could be loaded
Implements IImage.
References ExtractFrame(), Initialize(), and m_pFrame.
ReadFrame()
std::shared_ptr< Frame > CFFmpegImage::ReadFrame ()
References DecodeFrame(), and ExtractFrame().
Referenced by CGUITextureManager::Load().
ReleaseThumbnailBuffer()
void CFFmpegImage::ReleaseThumbnailBuffer () override virtual
Frees the output buffer allocated by CreateThumbnailFromSurface.
Reimplemented from IImage.
References CleanupLocalOutputBuffer().
Member Data Documentation
m_buf
MemBuffer CFFmpegImage::m_buf private
Referenced by Initialize(), and ~CFFmpegImage().
m_codec_ctx
AVCodecContext* CFFmpegImage::m_codec_ctx = nullptr private
Referenced by ExtractFrame(), Initialize(), and ~CFFmpegImage().
m_fctx
AVFormatContext* CFFmpegImage::m_fctx = nullptr private
Referenced by ExtractFrame(), Initialize(), and ~CFFmpegImage().
m_ioctx
AVIOContext* CFFmpegImage::m_ioctx = nullptr private
Referenced by Initialize(), and ~CFFmpegImage().
m_outputBuffer
uint8_t* CFFmpegImage::m_outputBuffer private
Referenced by CFFmpegImage(), CleanupLocalOutputBuffer(), and CreateThumbnailFromSurface().
m_pFrame
AVFrame* CFFmpegImage::m_pFrame private
Referenced by CFFmpegImage(), Decode(), LoadImageFromMemory(), and ~CFFmpegImage().
m_strMimeType
std::string CFFmpegImage::m_strMimeType private
Referenced by CreateThumbnailFromSurface(), and Initialize().
The documentation for this class was generated from the following files:
FFmpegImage.h
FFmpegImage.cpp