Kodi Documentation: CAEEncoderFFmpeg Class Reference
CAEEncoderFFmpeg Class Reference
#include <AEEncoderFFmpeg.h>
Public Member Functions
CAEEncoderFFmpeg ()
~CAEEncoderFFmpeg () override
bool IsCompatible (const AEAudioFormat &format) override
bool Initialize (AEAudioFormat &format, bool allow_planar_input=false) override
void Reset () override
unsigned int GetBitRate () override
AVCodecID GetCodecID () override
unsigned int GetFrames () override
int Encode (uint8_t *in, int in_size, uint8_t *out, int out_size) override
int GetData (uint8_t **data) override
double GetDelay (unsigned int bufferSize) override
Public Member Functions inherited from IAEEncoder
IAEEncoder ()=default
virtual ~IAEEncoder ()=default
Private Member Functions
unsigned int BuildChannelLayout (const int64_t ffmap, CAEChannelInfo &layout)
Private Attributes
std::string m_CodecName
AVCodecID m_CodecID
unsigned int m_BitRate = 0
AEAudioFormat m_CurrentFormat
AVCodecContext * m_CodecCtx
SwrContext * m_SwrCtx
CAEChannelInfo m_Layout
uint8_t m_Buffer [8+AV_INPUT_BUFFER_MIN_SIZE]
int m_BufferSize = 0
int m_OutputSize = 0
double m_OutputRatio = 0.0
double m_SampleRateMul = 0.0
unsigned int m_NeededFrames = 0
bool m_NeedConversion = false
Constructor & Destructor Documentation
CAEEncoderFFmpeg()
CAEEncoderFFmpeg::CAEEncoderFFmpeg ()
~CAEEncoderFFmpeg()
CAEEncoderFFmpeg::~CAEEncoderFFmpeg () override
References m_CodecCtx, m_SwrCtx, and Reset().
Member Function Documentation
BuildChannelLayout()
unsigned int CAEEncoderFFmpeg::BuildChannelLayout (const int64_t ffmap, CAEChannelInfo & layout) private
References AE_CH_BC, AE_CH_BL, AE_CH_BR, AE_CH_FC, AE_CH_FL, AE_CH_FLOC, AE_CH_FR, AE_CH_FROC, AE_CH_LFE, AE_CH_SL, AE_CH_SR, AE_CH_TBC, AE_CH_TBL, AE_CH_TBR, AE_CH_TC, AE_CH_TFC, AE_CH_TFL, AE_CH_TFR, CAEChannelInfo::Count(), and CAEChannelInfo::Reset().
Referenced by Initialize(), and IsCompatible().
Encode()
int CAEEncoderFFmpeg::Encode (uint8_t * in, int in_size, uint8_t * out, int out_size) override virtual
Encodes the supplied samples into a provided buffer
Parameters
in the PCM samples encoder requested format
in_size input buffer size
output buffer
out_size output buffer size
Returns
size of encoded data
@TODO: This is a workaround for our current design. The caller should be made
Implements IAEEncoder.
References err(), CLog::Log(), LOGERROR, m_CodecCtx, and FFMPEG_HELP_TOOLS::FFMpegException::what().
GetBitRate()
unsigned int CAEEncoderFFmpeg::GetBitRate () override virtual
Returns the bitrate of the encoder
Returns
bit rate in bits per second
Implements IAEEncoder.
References m_BitRate.
GetCodecID()
AVCodecID CAEEncoderFFmpeg::GetCodecID () override virtual
Returns the AVCodecID of the encoder
Returns
the ffmpeg codec id
Implements IAEEncoder.
References m_CodecID.
GetData()
int CAEEncoderFFmpeg::GetData (uint8_t ** data) override virtual
Get the encoded data
Parameters
data return pointer to the buffer with the current encoded block
Returns
the size in bytes of *data
Implements IAEEncoder.
References data(), m_Buffer, and m_BufferSize.
GetDelay()
double CAEEncoderFFmpeg::GetDelay (unsigned int bufferSize) override virtual
Get the delay in seconds
Parameters
bufferSize how much encoded data the caller has buffered to add to the delay
Returns
the delay in seconds including any un-fetched encoded data
Implements IAEEncoder.
References m_BufferSize, m_CodecCtx, m_NeededFrames, m_OutputRatio, and m_SampleRateMul.
GetFrames()
unsigned int CAEEncoderFFmpeg::GetFrames () override virtual
Return the number of frames needed to encode
Returns
number of frames (frames * channels = samples * bits per sample = bytes)
Implements IAEEncoder.
References m_NeededFrames.
Initialize()
bool CAEEncoderFFmpeg::Initialize (AEAudioFormat & format, bool allow_planar_input = false) override virtual
Called to setup the encoder to accept data in the specified format
Parameters
format the desired audio format, may be changed to suit the encoder
allow_planar_input allow engine to use with planar formats
Returns
true on success, false on failure
Implements IAEEncoder.
References AC3_ENCODE_BITRATE, AE_FMT_DOUBLE, AE_FMT_FLOAT, AE_FMT_FLOATP, AE_FMT_S16NE, AE_FMT_S32NE, AE_FMT_U8, BuildChannelLayout(), CAEUtil::DataFormatToBits(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGERROR, LOGINFO, m_BitRate, m_CodecCtx, m_CodecID, m_CodecName, m_CurrentFormat, AEAudioFormat::m_frames, m_Layout, m_NeedConversion, m_NeededFrames, m_OutputRatio, m_OutputSize, m_SampleRateMul, m_SwrCtx, Reset(), and CSettings::SETTING_AUDIOOUTPUT_AC3PASSTHROUGH.
IsCompatible()
bool CAEEncoderFFmpeg::IsCompatible (const AEAudioFormat & format) override virtual
Return true if the supplied format is compatible with the current open encoder.
Parameters
format the format to compare
Returns
true if compatible, false if not
Implements IAEEncoder.
References BuildChannelLayout(), AEAudioFormat::m_channelLayout, m_CodecCtx, m_CurrentFormat, AEAudioFormat::m_dataFormat, and AEAudioFormat::m_sampleRate.
Reset()
void CAEEncoderFFmpeg::Reset () override virtual
Reset the encoder for new data
Implements IAEEncoder.
References m_BufferSize.
Referenced by Initialize(), and ~CAEEncoderFFmpeg().
Member Data Documentation
m_BitRate
unsigned int CAEEncoderFFmpeg::m_BitRate = 0 private
Referenced by GetBitRate(), and Initialize().
m_Buffer
uint8_t CAEEncoderFFmpeg::m_Buffer[8+AV_INPUT_BUFFER_MIN_SIZE] private
Referenced by GetData().
m_BufferSize
int CAEEncoderFFmpeg::m_BufferSize = 0 private
Referenced by GetData(), GetDelay(), and Reset().
m_CodecCtx
AVCodecContext* CAEEncoderFFmpeg::m_CodecCtx private
Referenced by Encode(), GetDelay(), Initialize(), IsCompatible(), and ~CAEEncoderFFmpeg().
m_CodecID
AVCodecID CAEEncoderFFmpeg::m_CodecID private
Referenced by GetCodecID(), and Initialize().
m_CodecName
std::string CAEEncoderFFmpeg::m_CodecName private
Referenced by Initialize().
m_CurrentFormat
AEAudioFormat CAEEncoderFFmpeg::m_CurrentFormat private
Referenced by Initialize(), and IsCompatible().
m_Layout
CAEChannelInfo CAEEncoderFFmpeg::m_Layout private
Referenced by Initialize().
m_NeedConversion
bool CAEEncoderFFmpeg::m_NeedConversion = false private
Referenced by Initialize().
m_NeededFrames
unsigned int CAEEncoderFFmpeg::m_NeededFrames = 0 private
Referenced by GetDelay(), GetFrames(), and Initialize().
m_OutputRatio
double CAEEncoderFFmpeg::m_OutputRatio = 0.0 private
Referenced by GetDelay(), and Initialize().
m_OutputSize
int CAEEncoderFFmpeg::m_OutputSize = 0 private
Referenced by Initialize().
m_SampleRateMul
double CAEEncoderFFmpeg::m_SampleRateMul = 0.0 private
Referenced by GetDelay(), and Initialize().
m_SwrCtx
SwrContext* CAEEncoderFFmpeg::m_SwrCtx private
Referenced by Initialize(), and ~CAEEncoderFFmpeg().
The documentation for this class was generated from the following files:
AEEncoderFFmpeg.h
AEEncoderFFmpeg.cpp