Kodi Documentation: VAAPI::CVppPostproc Class Reference
VAAPI::CVppPostproc Class Reference
#include <VAAPI.h>
Public Member Functions
CVppPostproc ()
~CVppPostproc () override
bool PreInit (CVaapiConfig &config, SDiMethods *methods=NULL) override
bool Init (EINTERLACEMETHOD method) override
bool AddPicture (CVaapiDecodedPicture &inPic) override
bool Filter (CVaapiProcessedPicture &outPic) override
void ClearRef (CVaapiProcessedPicture &pic) override
void Flush () override
bool UpdateDeintMethod (EINTERLACEMETHOD method) override
bool DoesSync () override
bool WantsPic () override
bool UseVideoSurface () override
void Discard (COutput *output, ReadyToDispose cb) override
Public Member Functions inherited from VAAPI::CPostproc
virtual ~CPostproc ()=default
Protected Member Functions
bool CheckSuccess (VAStatus status, const std::string &function)
void Dispose ()
void Advance ()
Protected Attributes
VAConfigID m_configId = VA_INVALID_ID
VAContextID m_contextId = VA_INVALID_ID
CVideoSurfaces m_videoSurfaces
std::deque< CVaapiDecodedPicture > m_decodedPics
VABufferID m_filter = VA_INVALID_ID
int m_forwardRefs
int m_backwardRefs
int m_currentIdx
int m_frameCount
EINTERLACEMETHOD m_vppMethod
ReadyToDispose m_cbDispose = nullptr
COutput * m_pOut = nullptr
Protected Attributes inherited from VAAPI::CPostproc
CVaapiConfig m_config
int m_step
Detailed Description
VAAPI post processing
Constructor & Destructor Documentation
CVppPostproc()
CVppPostproc::CVppPostproc ()
~CVppPostproc()
CVppPostproc::~CVppPostproc () override
References Dispose().
Member Function Documentation
AddPicture()
bool CVppPostproc::AddPicture (CVaapiDecodedPicture & inPic) override virtual
Implements VAAPI::CPostproc.
References VAAPI::CVaapiDecodedPicture::index, VAAPI::CPostproc::m_config, m_decodedPics, m_frameCount, VAAPI::CPostproc::m_step, VAAPI::CVaapiBufferStats::SetCanSkipDeint(), and VAAPI::CVaapiConfig::stats.
Advance()
void CVppPostproc::Advance () protected
References VAAPI::CVideoSurfaces::ClearRender(), m_backwardRefs, VAAPI::CPostproc::m_config, m_currentIdx, m_decodedPics, m_forwardRefs, and VAAPI::CVaapiConfig::videoSurfaces.
Referenced by Filter().
CheckSuccess()
bool CVppPostproc::CheckSuccess (VAStatus status, const std::string & function) protected
References CLog::Log(), and LOGERROR.
Referenced by Dispose(), Filter(), PreInit(), and UpdateDeintMethod().
ClearRef()
void CVppPostproc::ClearRef (CVaapiProcessedPicture & pic) override virtual
Implements VAAPI::CPostproc.
References VAAPI::CVideoSurfaces::ClearReference(), VAAPI::CVideoSurfaces::HasRefs(), m_cbDispose, m_pOut, m_videoSurfaces, and VAAPI::CVaapiProcessedPicture::videoSurface.
Discard()
void CVppPostproc::Discard (COutput * output, ReadyToDispose cb) override virtual
Reimplemented from VAAPI::CPostproc.
References VAAPI::CVideoSurfaces::HasRefs(), m_cbDispose, m_pOut, and m_videoSurfaces.
Dispose()
void CVppPostproc::Dispose () protected
References CheckSuccess(), VAAPI::CVaapiConfig::dpy, Flush(), VAAPI::CVideoSurfaces::GetAtIndex(), VAAPI::CPostproc::m_config, m_configId, m_contextId, m_filter, m_videoSurfaces, VAAPI::CVideoSurfaces::RemoveNext(), VAAPI::CVideoSurfaces::Reset(), and VAAPI::CVideoSurfaces::Size().
Referenced by ~CVppPostproc().
DoesSync()
bool CVppPostproc::DoesSync () override virtual
Implements VAAPI::CPostproc.
Filter()
bool CVppPostproc::Filter (CVaapiProcessedPicture & outPic) override virtual
Implements VAAPI::CPostproc.
References Advance(), CheckSuccess(), VAAPI::CVideoSurfaces::ClearReference(), VAAPI::CVaapiConfig::dpy, DVD_CODEC_CTRL_SKIPDEINT, DVD_NOPTS_VALUE, VAAPI::CVaapiDecodedPicture::DVDPic, VAAPI::CVaapiProcessedPicture::DVDPic, DVP_FLAG_INTERLACED, DVP_FLAG_REPEAT_TOP_FIELD, DVP_FLAG_TOP_FIELD_FIRST, VAAPI::CVideoSurfaces::GetFree(), VideoPicture::iFlags, VAAPI::CVaapiDecodedPicture::index, CLog::Log(), LOGERROR, m_backwardRefs, VAAPI::CPostproc::m_config, m_contextId, m_currentIdx, m_decodedPics, m_filter, m_forwardRefs, VAAPI::CPostproc::m_step, m_videoSurfaces, m_vppMethod, VideoPicture::pts, VideoPicture::SetParams(), VAAPI::CVaapiProcessedPicture::source, VAAPI::CVaapiConfig::surfaceHeight, VAAPI::CVaapiConfig::surfaceWidth, VAAPI::CVaapiDecodedPicture::videoSurface, VAAPI::CVaapiProcessedPicture::videoSurface, and VS_INTERLACEMETHOD_NONE.
Flush()
void CVppPostproc::Flush () override virtual
Implements VAAPI::CPostproc.
References VAAPI::CVideoSurfaces::ClearRender(), VAAPI::CPostproc::m_config, m_decodedPics, and VAAPI::CVaapiConfig::videoSurfaces.
Referenced by Dispose().
Init()
bool CVppPostproc::Init (EINTERLACEMETHOD method) override virtual
Implements VAAPI::CPostproc.
References m_backwardRefs, m_currentIdx, m_forwardRefs, m_frameCount, m_vppMethod, UpdateDeintMethod(), and VS_INTERLACEMETHOD_AUTO.
PreInit()
bool CVppPostproc::PreInit (CVaapiConfig & config, SDiMethods * methods = NULL) override virtual
Implements VAAPI::CPostproc.
References VAAPI::CVideoSurfaces::AddSurface(), CheckSuccess(), VAAPI::SDiMethods::diMethods, VAAPI::CVaapiConfig::dpy, CLog::Log(), LOGDEBUG, LOGVIDEO, VAAPI::CPostproc::m_config, m_configId, m_contextId, m_videoSurfaces, NUM_RENDER_PICS, VAAPI::SDiMethods::numDiMethods, VAAPI::CVaapiConfig::profile, VAAPI::CVaapiConfig::surfaceHeight, VAAPI::CVaapiConfig::surfaceWidth, VS_INTERLACEMETHOD_VAAPI_BOB, VS_INTERLACEMETHOD_VAAPI_MACI, and VS_INTERLACEMETHOD_VAAPI_MADI.
UpdateDeintMethod()
bool CVppPostproc::UpdateDeintMethod (EINTERLACEMETHOD method) override virtual
Implements VAAPI::CPostproc.
References CheckSuccess(), VAAPI::CVaapiConfig::dpy, m_backwardRefs, VAAPI::CPostproc::m_config, m_contextId, m_filter, m_forwardRefs, m_vppMethod, VAAPI::CVaapiConfig::processInfo, CProcessInfo::SetVideoDeintMethod(), VS_INTERLACEMETHOD_NONE, VS_INTERLACEMETHOD_VAAPI_BOB, VS_INTERLACEMETHOD_VAAPI_MACI, and VS_INTERLACEMETHOD_VAAPI_MADI.
Referenced by Init().
UseVideoSurface()
bool CVppPostproc::UseVideoSurface () override virtual
Implements VAAPI::CPostproc.
WantsPic()
bool CVppPostproc::WantsPic () override virtual
Reimplemented from VAAPI::CPostproc.
References m_videoSurfaces, and VAAPI::CVideoSurfaces::NumFree().
Member Data Documentation
m_backwardRefs
int VAAPI::CVppPostproc::m_backwardRefs protected
Referenced by Advance(), Filter(), Init(), and UpdateDeintMethod().
m_cbDispose
ReadyToDispose VAAPI::CVppPostproc::m_cbDispose = nullptr protected
Referenced by ClearRef(), and Discard().
m_configId
VAConfigID VAAPI::CVppPostproc::m_configId = VA_INVALID_ID protected
Referenced by Dispose(), and PreInit().
m_contextId
VAContextID VAAPI::CVppPostproc::m_contextId = VA_INVALID_ID protected
Referenced by Dispose(), Filter(), PreInit(), and UpdateDeintMethod().
m_currentIdx
int VAAPI::CVppPostproc::m_currentIdx protected
Referenced by Advance(), Filter(), and Init().
m_decodedPics
std::deque<CVaapiDecodedPicture> VAAPI::CVppPostproc::m_decodedPics protected
Referenced by AddPicture(), Advance(), Filter(), and Flush().
m_filter
VABufferID VAAPI::CVppPostproc::m_filter = VA_INVALID_ID protected
Referenced by Dispose(), Filter(), and UpdateDeintMethod().
m_forwardRefs
int VAAPI::CVppPostproc::m_forwardRefs protected
Referenced by Advance(), Filter(), Init(), and UpdateDeintMethod().
m_frameCount
int VAAPI::CVppPostproc::m_frameCount protected
Referenced by AddPicture(), and Init().
m_pOut
COutput* VAAPI::CVppPostproc::m_pOut = nullptr protected
Referenced by ClearRef(), and Discard().
m_videoSurfaces
CVideoSurfaces VAAPI::CVppPostproc::m_videoSurfaces protected
Referenced by ClearRef(), Discard(), Dispose(), Filter(), PreInit(), and WantsPic().
m_vppMethod
EINTERLACEMETHOD VAAPI::CVppPostproc::m_vppMethod protected
Referenced by Filter(), Init(), and UpdateDeintMethod().
The documentation for this class was generated from the following files:
VAAPI.h
VAAPI.cpp