Kodi Documentation: ISetting Class Reference
ISetting Class Reference
Settings
Interface defining the base of all setting objects.
#include <ISetting.h>
Public Member Functions
ISetting (const std::string &id, CSettingsManager *settingsManager=nullptr)
Creates a new setting object with the given identifier.
virtual ~ISetting ()=default
virtual bool Deserialize (const TiXmlNode *node, bool update=false)
Deserializes the given XML node into the properties of the setting object.
const std::string & GetId () const
Gets the identifier of the setting object.
virtual bool IsVisible () const
Whether the setting object is visible or hidden.
virtual void SetVisible (bool visible)
Sets the visibility state of the setting object.
int GetLabel () const
Gets the localizeable label ID of the setting group.
void SetLabel (int label)
Sets the localizeable label ID of the setting group.
int GetHelp () const
Gets the localizeable help ID of the setting group.
void SetHelp (int help)
Sets the localizeable help ID of the setting group.
virtual bool MeetsRequirements () const
Whether the setting object meets all necessary requirements.
virtual void CheckRequirements ()
Checks if the setting object meets all necessary requirements.
virtual void SetRequirementsMet (bool requirementsMet)
Sets whether the setting object meets all necessary requirements.
Static Public Member Functions
static bool DeserializeIdentification (const TiXmlNode *node, std::string &identification)
Deserializes the given XML node to retrieve a setting object's identifier.
Static Protected Member Functions
static bool DeserializeIdentificationFromAttribute (const TiXmlNode *node, const std::string &attribute, std::string &identification)
Deserializes the given XML node to retrieve a setting object's identifier from the given attribute.
Protected Attributes
std::string m_id
CSettingsManager * m_settingsManager
Static Protected Attributes
static constexpr int DefaultLabel = -1
Private Attributes
bool m_visible = true
int m_label = DefaultLabel
int m_help = -1
bool m_meetsRequirements = true
CSettingRequirement m_requirementCondition
Detailed Description
Interface defining the base of all setting objects.
Constructor & Destructor Documentation
ISetting()
ISetting::ISetting (const std::string & id, CSettingsManager * settingsManager = nullptr)
Creates a new setting object with the given identifier.
Parameters
id Identifier of the setting object
settingsManager Reference to the settings manager
~ISetting()
virtual ISetting::~ISetting () virtual default
Member Function Documentation
CheckRequirements()
void ISetting::CheckRequirements () virtual
Checks if the setting object meets all necessary requirements.
References CSettingCondition::Check(), m_meetsRequirements, and m_requirementCondition.
Deserialize()
bool ISetting::Deserialize (const TiXmlNode * node, bool update = false) virtual
Deserializes the given XML node into the properties of the setting object.
If the update parameter is true, the checks for mandatory properties are skipped and values are only updated.
Parameters
node XML node containing the properties of the setting object
update Whether to perform checks for mandatory properties or not
Returns
True if deserialization was successful, false otherwise
Reimplemented in CSetting, CSettingList, CSettingBool, CSettingInt, CSettingNumber, CSettingString, CSettingAction, CSettingGroup, CSettingCategory, CSettingSection, CSettingAddon, and CSettingPath.
References CBooleanLogic::Deserialize(), XMLUtils::GetBoolean(), m_help, m_label, m_requirementCondition, m_visible, node, SETTING_XML_ATTR_HELP, SETTING_XML_ATTR_LABEL, SETTING_XML_ELM_REQUIREMENT, SETTING_XML_ELM_VISIBLE, and value.
Referenced by CSetting::Deserialize(), CSettingGroup::Deserialize(), CSettingCategory::Deserialize(), and CSettingSection::Deserialize().
DeserializeIdentification()
bool ISetting::DeserializeIdentification (const TiXmlNode * node, std::string & identification) static
Deserializes the given XML node to retrieve a setting object's identifier.
Parameters
node XML node containing a setting object's identifier
identification Will contain the deserialized setting object's identifier
Returns
True if a setting object's identifier was deserialized, false otherwise
References DeserializeIdentificationFromAttribute(), node, and SETTING_XML_ATTR_ID.
Referenced by CSettingCategory::Deserialize(), CSettingSection::Deserialize(), CSetting::DeserializeIdentification(), and CSettingsManager::Initialize().
DeserializeIdentificationFromAttribute()
bool ISetting::DeserializeIdentificationFromAttribute (const TiXmlNode * node, const std::string & attribute, std::string & identification) static protected
Deserializes the given XML node to retrieve a setting object's identifier from the given attribute.
Parameters
node XML node containing a setting object's identifier
attribute Attribute which contains the setting object's identifier
identification Will contain the deserialized setting object's identifier
Returns
True if a setting object's identifier was deserialized, false otherwise
References node.
Referenced by DeserializeIdentification(), and CSetting::DeserializeIdentification().
GetHelp()
int ISetting::GetHelp () const inline
Gets the localizeable help ID of the setting group.
Returns
Localizeable help ID of the setting group
References m_help.
Referenced by CSetting::Copy(), and CSetting::MergeBasics().
GetId()
const std::string & ISetting::GetId () const inline
Gets the identifier of the setting object.
Returns
Identifier of the setting object
References m_id.
Referenced by CApplicationPowerHandling::OnSettingAction(), CApplicationPowerHandling::OnSettingChanged(), CApplicationSkinHandling::OnSettingChanged(), and CApplicationVolumeHandling::OnSettingChanged().
GetLabel()
int ISetting::GetLabel () const inline
Gets the localizeable label ID of the setting group.
Returns
Localizeable label ID of the setting group
References m_label.
Referenced by CSetting::Copy(), and CSetting::MergeBasics().
IsVisible()
virtual bool ISetting::IsVisible () const inline virtual
Whether the setting object is visible or hidden.
Returns
True if the setting object is visible, false otherwise
Reimplemented in CSetting.
References m_visible.
Referenced by CSetting::GetVisible(), and CSetting::IsVisible().
MeetsRequirements()
virtual bool ISetting::MeetsRequirements () const inline virtual
Whether the setting object meets all necessary requirements.
Returns
True if the setting object meets all necessary requirements, false otherwise
References m_meetsRequirements.
Referenced by CSetting::Copy(), and CSetting::MergeBasics().
SetHelp()
void ISetting::SetHelp (int help) inline
Sets the localizeable help ID of the setting group.
Parameters
label Localizeable help ID of the setting group
References m_help.
Referenced by CSetting::Copy(), and CSetting::MergeBasics().
SetLabel()
void ISetting::SetLabel (int label) inline
Sets the localizeable label ID of the setting group.
Parameters
label Localizeable label ID of the setting group
References label, and m_label.
Referenced by CSetting::Copy(), CSettingAction::CSettingAction(), CSettingBool::CSettingBool(), CSettingInt::CSettingInt(), CSettingInt::CSettingInt(), CSettingList::CSettingList(), CSettingNumber::CSettingNumber(), CSettingString::CSettingString(), and CSetting::MergeBasics().
SetRequirementsMet()
virtual void ISetting::SetRequirementsMet (bool requirementsMet) inline virtual
Sets whether the setting object meets all necessary requirements.
Parameters
visible Whether the setting object meets all necessary requirements or not
References m_meetsRequirements.
Referenced by CSetting::Copy(), and CSetting::MergeBasics().
SetVisible()
virtual void ISetting::SetVisible (bool visible) inline virtual
Sets the visibility state of the setting object.
Parameters
visible Whether the setting object shall be visible or not
References m_visible.
Referenced by CSetting::Copy(), and CSetting::MergeBasics().
Member Data Documentation
DefaultLabel
constexpr int ISetting::DefaultLabel = -1 static constexpr protected
m_help
int ISetting::m_help = -1 private
Referenced by Deserialize(), GetHelp(), and SetHelp().
m_id
std::string ISetting::m_id protected
Referenced by CSettingList::copy(), CSetting::Deserialize(), CSettingList::Deserialize(), CSettingBool::Deserialize(), CSettingInt::Deserialize(), CSettingNumber::Deserialize(), CSettingString::Deserialize(), CSettingAddon::Deserialize(), CSettingPath::Deserialize(), CSettingList::fromValues(), GetId(), CSetting::MakeReference(), CSettingInt::UpdateDynamicOptions(), and CSettingString::UpdateDynamicOptions().
m_label
int ISetting::m_label = DefaultLabel private
Referenced by Deserialize(), GetLabel(), and SetLabel().
m_meetsRequirements
bool ISetting::m_meetsRequirements = true private
Referenced by CheckRequirements(), MeetsRequirements(), and SetRequirementsMet().
m_requirementCondition
CSettingRequirement ISetting::m_requirementCondition private
Referenced by CheckRequirements(), and Deserialize().
m_settingsManager
CSettingsManager* ISetting::m_settingsManager protected
Referenced by CSetting::Copy(), CSetting::Deserialize(), CSettingInt::Deserialize(), CSettingString::Deserialize(), CSettingGroup::Deserialize(), CSettingCategory::Deserialize(), CSettingSection::Deserialize(), CSetting::IsEnabled(), CSettingInt::UpdateDynamicOptions(), and CSettingString::UpdateDynamicOptions().
m_visible
bool ISetting::m_visible = true private
Referenced by Deserialize(), IsVisible(), and SetVisible().
The documentation for this class was generated from the following files:
ISetting.h
ISetting.cpp