Kodi Documentation: CGUIInfoManager Class Reference
CGUIInfoManager Class Reference
Guilib classes » Strings and Localization
#include <GUIInfoManager.h>
Classes
class Property
class for holding information on properties
Public Member Functions
CGUIInfoManager (void)
~CGUIInfoManager (void) override
void Initialize ()
void Clear ()
void ResetCache ()
int GetMessageMask () override
Should return the message mask that it wishes to receive messages for.
void OnApplicationMessage (KODI::MESSAGING::ThreadMessage *pMsg) override
This gets called whenever a message matching the registered message mask is processed.
INFO::InfoPtr Register (const std::string &expression, int context=0)
Register a boolean condition/expression This routine allows controls or other clients of the info manager to register to receive updates of particular expressions, in a particular context (currently windows).
void UnRegister (const INFO::InfoPtr &expression)
Unregister a boolean condition/expression This routine allows controls or other clients of the info manager to unregister a previously registered boolean condition/expression.
bool ConditionsChangedValues (const std::map< INFO::InfoPtr, bool > &map)
iterates through boolean conditions and compares their stored values to current values. Returns true if any condition changed value.
bool EvaluateBool (const std::string &expression, int context, const std::shared_ptr< CGUIListItem > &item=nullptr)
Evaluate a boolean expression.
int TranslateString (const std::string &strCondition)
Translates a string as given by the skin into an int that we use for more efficient retrieval of data. Can handle combined strings on the form Player.Caching + VideoPlayer.IsFullscreen (Logical and) Player.HasVideo | Player.HasAudio (Logical or)
int TranslateSingleString (const std::string &strCondition, bool &listItemDependent)
std::string GetLabel (int info, int contextWindow, std::string *fallback=nullptr) const
std::string GetImage (int info, int contextWindow, std::string *fallback=nullptr)
Obtains the filename of the image to show from whichever subsystem is needed.
bool GetInt (int &value, int info, int contextWindow, const CGUIListItem *item=nullptr) const
bool GetBool (int condition, int contextWindow, const CGUIListItem *item=nullptr)
std::string GetItemLabel (const CFileItem *item, int contextWindow, int info, std::string *fallback=nullptr) const
std::string GetItemImage (const CGUIListItem *item, int contextWindow, int info, std::string *fallback=nullptr) const
bool GetItemInt (int &value, const CGUIListItem *item, int contextWindow, int info) const
Get integer value of info.
bool GetItemBool (const CGUIListItem *item, int contextWindow, int condition) const
void SetCurrentItem (const CFileItem &item)
Set currently playing file item.
void ResetCurrentItem ()
void UpdateCurrentItem (const CFileItem &item)
void SetCurrentAlbumThumb (const std::string &thumbFileName)
const MUSIC_INFO::CMusicInfoTag * GetCurrentSongTag () const
const CVideoInfoTag * GetCurrentMovieTag () const
const KODI::GAME::CGameInfoTag * GetCurrentGameTag () const
void UpdateAVInfo ()
int RegisterSkinVariableString (const INFO::CSkinVariableString *info)
int TranslateSkinVariableString (const std::string &name, int context)
void RegisterInfoProvider (KODI::GUILIB::GUIINFO::IGUIInfoProvider *provider)
register a guiinfo provider
void UnregisterInfoProvider (KODI::GUILIB::GUIINFO::IGUIInfoProvider *provider)
unregister a guiinfo provider
KODI::GUILIB::GUIINFO::CGUIInfoProviders & GetInfoProviders ()
get access to the registered guiinfo providers
Public Member Functions inherited from KODI::MESSAGING::IMessageTarget
virtual ~IMessageTarget ()=default
Private Types
typedef std::set< INFO::InfoPtr, bool(*)(const INFO::InfoPtr &, const INFO::InfoPtr &)> INFOBOOLTYPE
Private Member Functions
void SplitInfoString (const std::string &infoString, std::vector< Property > &info)
Split an info string into it's constituent parts and parameters Format is:
int TranslateSingleString (const std::string &strCondition)
Translates a string as given by the skin into an int that we use for more efficient retrieval of data.
int TranslateListItem (const Property &cat, const Property &prop, int id, bool container)
int TranslateMusicPlayerString (const std::string &info) const
int TranslateVideoPlayerString (const std::string &info) const
int TranslatePlayerString (const std::string &info) const
std::string GetMultiInfoLabel (const KODI::GUILIB::GUIINFO::CGUIInfo &info, int contextWindow, std::string *fallback=nullptr) const
bool GetMultiInfoInt (int &value, const KODI::GUILIB::GUIINFO::CGUIInfo &info, int contextWindow, const CGUIListItem *item) const
bool GetMultiInfoBool (const KODI::GUILIB::GUIINFO::CGUIInfo &info, int contextWindow, const CGUIListItem *item)
std::string GetMultiInfoItemLabel (const CFileItem *item, int contextWindow, const KODI::GUILIB::GUIINFO::CGUIInfo &info, std::string *fallback=nullptr) const
std::string GetMultiInfoItemImage (const CFileItem *item, int contextWindow, const KODI::GUILIB::GUIINFO::CGUIInfo &info, std::string *fallback=nullptr) const
std::string GetSkinVariableString (int info, int contextWindow, bool preferImage=false, const CGUIListItem *item=nullptr) const
int AddMultiInfo (const KODI::GUILIB::GUIINFO::CGUIInfo &info)
int ResolveMultiInfo (int info) const
bool IsListItemInfo (int info) const
void SetCurrentSongTag (const MUSIC_INFO::CMusicInfoTag &tag)
void SetCurrentVideoTag (const CVideoInfoTag &tag)
Static Private Member Functions
static TIME_FORMAT TranslateTimeFormat (const std::string &format)
Private Attributes
std::vector< KODI::GUILIB::GUIINFO::CGUIInfo > m_multiInfo
CFileItem * m_currentFile
INFOBOOLTYPE m_bools
unsigned int m_refreshCounter = 0
std::vector< INFO::CSkinVariableString > m_skinVariableStrings
CCriticalSection m_critInfo
KODI::GUILIB::GUIINFO::CGUIInfoProviders m_infoProviders
Member Typedef Documentation
INFOBOOLTYPE
typedef std::set<INFO::InfoPtr, bool(*)(const INFO::InfoPtr&, const INFO::InfoPtr&)> CGUIInfoManager::INFOBOOLTYPE private
Constructor & Destructor Documentation
CGUIInfoManager()
CGUIInfoManager::CGUIInfoManager (void)
~CGUIInfoManager()
CGUIInfoManager::~CGUIInfoManager (void) override
References m_currentFile.
Member Function Documentation
AddMultiInfo()
int CGUIInfoManager::AddMultiInfo (const KODI::GUILIB::GUIINFO::CGUIInfo & info) private
References id, CLog::Log(), LOGERROR, m_multiInfo, MULTI_INFO_END, and MULTI_INFO_START.
Referenced by TranslateListItem(), and TranslateSingleString().
Clear()
void CGUIInfoManager::Clear ()
References InfoBoolComparator(), CLog::Log(), LOGDEBUG, m_bools, m_critInfo, and m_skinVariableStrings.
Referenced by CApplicationSkinHandling::UnloadSkin().
ConditionsChangedValues()
bool CGUIInfoManager::ConditionsChangedValues (const std::map< INFO::InfoPtr, bool > & map)
iterates through boolean conditions and compares their stored values to current values. Returns true if any condition changed value.
References INFO::DEFAULT_CONTEXT.
Referenced by CGUIWindow::NeedLoad().
EvaluateBool()
bool CGUIInfoManager::EvaluateBool (const std::string & expression, int context, const std::shared_ptr< CGUIListItem > & item = nullptr)
Evaluate a boolean expression.
Parameters
expression the expression to evaluate
context the context in which to evaluate the expression (currently windows)
Returns
the value of the evaluated expression.
See also
Register
References Register().
Referenced by CGUIAction::ExecuteActions(), XBMCAddon::xbmc::getCondVisibility(), CGUIAction::GetNavigation(), CGUIAction::HasActionsMeetingCondition(), anonymous_namespace{AddonSettings.cpp}::InfoBool(), XFILE::CLibraryDirectory::LoadXML(), and OnApplicationMessage().
GetBool()
bool CGUIInfoManager::GetBool (int condition, int contextWindow, const CGUIListItem * item = nullptr)
References INFO::DEFAULT_CONTEXT, KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetBool(), KODI::GUILIB::GUIINFO::GetCurrentListItem(), GetInt(), GetItemBool(), GetMultiInfoBool(), LISTITEM_END, LISTITEM_START, m_currentFile, m_infoProviders, m_multiInfo, MULTI_INFO_END, and MULTI_INFO_START.
Referenced by INFO::InfoSingle::Update().
GetCurrentGameTag()
const KODI::GAME::CGameInfoTag * CGUIInfoManager::GetCurrentGameTag () const
References CFileItem::GetGameInfoTag(), CFileItem::HasGameInfoTag(), and m_currentFile.
Referenced by XBMCAddon::xbmc::Player::getGameInfoTag().
GetCurrentMovieTag()
const CVideoInfoTag * CGUIInfoManager::GetCurrentMovieTag () const
References CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), and m_currentFile.
Referenced by JSONRPC::CPlayerOperations::GetItem(), and XBMCAddon::xbmc::Player::getVideoInfoTag().
GetCurrentSongTag()
const MUSIC_INFO::CMusicInfoTag * CGUIInfoManager::GetCurrentSongTag () const
References CFileItem::GetMusicInfoTag(), CFileItem::HasMusicInfoTag(), and m_currentFile.
Referenced by CGUIWindowVisualisation::FrameMove(), JSONRPC::CPlayerOperations::GetItem(), XBMCAddon::xbmc::Player::getMusicInfoTag(), CGUIWindowVisualisation::OnMessage(), CGUIVisualisationControl::Process(), CAirTunesServer::RefreshMetadata(), and CGUIVisualisationControl::UpdateTrack().
GetImage()
std::string CGUIInfoManager::GetImage (int info, int contextWindow, std::string * fallback = nullptr)
Obtains the filename of the image to show from whichever subsystem is needed.
References CONDITIONAL_LABEL_END, CONDITIONAL_LABEL_START, KODI::GUILIB::GUIINFO::GetCurrentListItem(), GetItemImage(), GetLabel(), GetMultiInfoLabel(), GetSkinVariableString(), LISTITEM_ACTUAL_ICON, LISTITEM_ART, LISTITEM_ICON, LISTITEM_OVERLAY, LISTITEM_THUMB, m_multiInfo, MULTI_INFO_END, and MULTI_INFO_START.
Referenced by XBMCAddon::xbmc::getInfoImage(), UPNP::CUPnPRenderer::GetMetadata(), GetMultiInfoBool(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::LabelNeedsUpdate(), and CXBMCApp::UpdateSessionMetadata().
GetInfoProviders()
KODI::GUILIB::GUIINFO::CGUIInfoProviders & CGUIInfoManager::GetInfoProviders () inline
get access to the registered guiinfo providers
Returns
the guiinfo providers
References m_infoProviders.
Referenced by CMusicDatabase::CommitTransaction(), CVideoDatabase::CommitTransaction(), CGUIWindowVisualisation::FrameMove(), CGUIDialogPictureInfo::FrameMove(), PVR::CPVRGUIChannelNavigator::HideInfo(), CMusicDatabase::ImportFromXML(), CProfileManager::LoadProfile(), CApplication::OnAction(), CGUIWindowVisualisation::OnAction(), CGUIWindowFullScreen::OnAction(), CGUIWindowSlideShow::OnDeinitWindow(), KODI::RETRO::CGameWindowFullScreen::OnInitWindow(), CGUIWindowVisualisation::OnMessage(), CGUIWindowFullScreen::OnMessage(), CGUIWindowMusicBase::OnRemoveSource(), CGUIWindowManager::PreviousWindow(), MUSIC_INFO::CMusicInfoScanner::Process(), KODI::VIDEO::CVideoInfoScanner::Process(), CGUIWindowDebugInfo::Process(), CGUIWindowSlideShow::Process(), CApplication::Render(), CSkinSettings::Reset(), CGUIBaseContainer::SetContainerMoving(), CGUIWindow::SetInitialVisibility(), CGUIDialogPictureInfo::SetPicture(), PVR::CPVRGUIChannelNavigator::ShowInfo(), PVR::CPVRGUIChannelNavigator::SubscribeToShowInfoEventStream(), and CGUIViewControl::UpdateViewVisibility().
GetInt()
bool CGUIInfoManager::GetInt (int & value, int info, int contextWindow, const CGUIListItem * item = nullptr) const
References KODI::GUILIB::GUIINFO::GetCurrentListItem(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetInt(), GetItemInt(), GetMultiInfoInt(), LISTITEM_END, LISTITEM_START, m_currentFile, m_infoProviders, m_multiInfo, MULTI_INFO_END, MULTI_INFO_START, and value.
Referenced by GetBool(), CGUIDialogSeekBar::GetEpgEventProgress(), GetMultiInfoBool(), CGUIDialogSeekBar::GetProgress(), CGUIDialogSeekBar::GetTimeshiftProgress(), and SeekPercentage().
GetItemBool()
bool CGUIInfoManager::GetItemBool (const CGUIListItem * item, int contextWindow, int condition) const
References KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetBool(), CGUIListItem::IsFileItem(), CFileItem::IsParentFolder(), CGUIListItem::IsSelected(), LISTITEM_IS_FOLDER, LISTITEM_IS_PARENTFOLDER, LISTITEM_ISSELECTED, CGUIListItem::m_bIsFolder, m_infoProviders, and value.
Referenced by GetBool(), and GetMultiInfoBool().
GetItemImage()
std::string CGUIInfoManager::GetItemImage (const CGUIListItem * item, int contextWindow, int info, std::string * fallback = nullptr) const
References GetMultiInfoItemImage(), and CGUIListItem::IsFileItem().
Referenced by GetImage(), GetMultiInfoBool(), and KODI::GUILIB::GUIINFO::CGUIInfoLabel::ItemLabelNeedsUpdate().
GetItemInt()
bool CGUIInfoManager::GetItemInt (int & value, const CGUIListItem * item, int contextWindow, int info) const
Get integer value of info.
Parameters
value int reference to pass value of given info
info id of info
context the context in which to evaluate the expression (currently windows)
item optional listitem if want to get listitem related int
Returns
true if given info was handled
See also
GetItemInt, GetMultiInfoInt
References KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetInt(), m_infoProviders, and value.
Referenced by GetInt(), and GetMultiInfoInt().
GetItemLabel()
std::string CGUIInfoManager::GetItemLabel (const CFileItem * item, int contextWindow, int info, std::string * fallback = nullptr) const
References GetMultiInfoItemLabel().
Referenced by GetLabel(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::ItemLabelNeedsUpdate(), and KODI::GUILIB::GUIINFO::CGUIInfoColor::Update().
GetLabel()
std::string CGUIInfoManager::GetLabel (int info, int contextWindow, std::string * fallback = nullptr) const
References CONDITIONAL_LABEL_END, CONDITIONAL_LABEL_START, KODI::GUILIB::GUIINFO::GetCurrentListItem(), GetItemLabel(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetLabel(), GetMultiInfoLabel(), GetSkinVariableString(), LISTITEM_END, LISTITEM_START, m_currentFile, m_infoProviders, m_multiInfo, MULTI_INFO_END, and MULTI_INFO_START.
Referenced by CGUIWindowSystemInfo::FrameMove(), GetImage(), XBMCAddon::xbmc::getInfoLabel(), GetMultiInfoLabel(), JSONRPC::CGUIOperations::GetPropertyValue(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::LabelNeedsUpdate(), OnApplicationMessage(), CGUIWindowSystemInfo::SetControlLabel(), KODI::GUILIB::GUIINFO::CGUIInfoColor::Update(), CGUIRangesControl::UpdateInfo(), CGUIDialogPictureInfo::UpdatePictureInfo(), and UPNP::CUPnPRenderer::UpdateState().
GetMessageMask()
int CGUIInfoManager::GetMessageMask () override virtual
Should return the message mask that it wishes to receive messages for.
The message mask is defined in "messaging/ApplicationMessenger.h" pick the next one available when creating a new
Implements KODI::MESSAGING::IMessageTarget.
References TMSG_MASK_GUIINFOMANAGER.
GetMultiInfoBool()
bool CGUIInfoManager::GetMultiInfoBool (const KODI::GUILIB::GUIINFO::CGUIInfo & info, int contextWindow, const CGUIListItem * item) private
References CVariant::asBoolean(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetBool(), KODI::GUILIB::GUIINFO::GetCurrentListItem(), KODI::GUILIB::GUIINFO::CGUIInfo::GetData1(), GetImage(), KODI::GUILIB::GUIINFO::CGUIInfo::GetInfoFlag(), GetInt(), GetItemBool(), GetItemImage(), CGUIListItem::GetProperty(), CGUIListItem::HasProperty(), INFOFLAG_LISTITEM_CONTAINER, INTEGER_EVEN, INTEGER_GREATER_OR_EQUAL, INTEGER_GREATER_THAN, INTEGER_IS_EQUAL, INTEGER_LESS_OR_EQUAL, INTEGER_LESS_THAN, INTEGER_ODD, CGUIListItem::IsFileItem(), IsListItemInfo(), label, LISTITEM_END, LISTITEM_PROPERTY, LISTITEM_START, m_currentFile, m_infoProviders, m_multiInfo, MULTI_INFO_START, ResolveMultiInfo(), STRING_CONTAINS, STRING_ENDS_WITH, STRING_IS_EMPTY, STRING_IS_EQUAL, STRING_STARTS_WITH, and value.
Referenced by GetBool().
GetMultiInfoInt()
bool CGUIInfoManager::GetMultiInfoInt (int & value, const KODI::GUILIB::GUIINFO::CGUIInfo & info, int contextWindow, const CGUIListItem * item) const private
References CVariant::asInteger(), KODI::GUILIB::GUIINFO::GetCurrentListItem(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetInt(), GetItemInt(), CGUIListItem::GetProperty(), CGUIListItem::HasProperty(), INTEGER_VALUEOF, LISTITEM_END, LISTITEM_PROPERTY, LISTITEM_START, m_currentFile, m_infoProviders, and value.
Referenced by GetInt().
GetMultiInfoItemImage()
std::string CGUIInfoManager::GetMultiInfoItemImage (const CFileItem * item, int contextWindow, const KODI::GUILIB::GUIINFO::CGUIInfo & info, std::string * fallback = nullptr) const private
References CONDITIONAL_LABEL_END, CONDITIONAL_LABEL_START, GetMultiInfoItemImage(), GetMultiInfoItemLabel(), GetSkinVariableString(), m_multiInfo, MULTI_INFO_END, and MULTI_INFO_START.
Referenced by GetItemImage(), GetMultiInfoItemImage(), and GetMultiInfoLabel().
GetMultiInfoItemLabel()
std::string CGUIInfoManager::GetMultiInfoItemLabel (const CFileItem * item, int contextWindow, const KODI::GUILIB::GUIINFO::CGUIInfo & info, std::string * fallback = nullptr) const private
References CVariant::asString(), CONDITIONAL_LABEL_END, CONDITIONAL_LABEL_START, g_charsetConverter, CGUIListItem::GetArt(), CDateTime::GetAsLocalizedDate(), CDateTime::GetAsLocalizedDateTime(), CDateTime::GetAsLocalizedTime(), CGUIListItem::GetCurrentItem(), URIUtils::GetExtension(), URIUtils::GetFileName(), CGUIListItem::GetLabel(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetLabel(), CGUIListItem::GetLabel2(), GetMultiInfoItemLabel(), CGUIListItem::GetOverlayImage(), URIUtils::GetParentPath(), CFileItem::GetPath(), CGUIListItem::GetProperty(), GetSkinVariableString(), CGUIListItem::GetSortLabel(), CFileItem::GetThumbHideIfUnwatched(), CURL::GetWithoutUserDetails(), CDateTime::IsValid(), LISTITEM_ACTUAL_ICON, LISTITEM_ART, LISTITEM_CURRENTITEM, LISTITEM_DATE, LISTITEM_DATETIME, LISTITEM_FILE_EXTENSION, LISTITEM_FILENAME, LISTITEM_FILENAME_AND_PATH, LISTITEM_FILENAME_NO_EXTENSION, LISTITEM_FOLDERNAME, LISTITEM_FOLDERPATH, LISTITEM_ICON, LISTITEM_LABEL, LISTITEM_LABEL2, LISTITEM_OVERLAY, LISTITEM_PATH, LISTITEM_PROGRAM_COUNT, LISTITEM_PROPERTY, LISTITEM_SIZE, LISTITEM_SORT_LETTER, LISTITEM_STARTDATE, LISTITEM_STARTTIME, LISTITEM_THUMB, CGUIListItem::m_bIsFolder, CFileItem::m_dateTime, CFileItem::m_dwSize, m_infoProviders, CFileItem::m_iprogramCount, m_multiInfo, MULTI_INFO_END, MULTI_INFO_START, URIUtils::RemoveExtension(), URIUtils::RemoveSlashAtEnd(), and value.
Referenced by GetItemLabel(), GetMultiInfoItemImage(), and GetMultiInfoItemLabel().
GetMultiInfoLabel()
std::string CGUIInfoManager::GetMultiInfoLabel (const KODI::GUILIB::GUIINFO::CGUIInfo & info, int contextWindow, std::string * fallback = nullptr) const private
References KODI::GUILIB::GUIINFO::GetCurrentListItem(), GetLabel(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetLabel(), GetMultiInfoItemImage(), LISTITEM_END, LISTITEM_START, m_currentFile, m_infoProviders, SYSTEM_ADDON_ICON, SYSTEM_ADDON_TITLE, and SYSTEM_ADDON_VERSION.
Referenced by GetImage(), and GetLabel().
GetSkinVariableString()
std::string CGUIInfoManager::GetSkinVariableString (int info, int contextWindow, bool preferImage = false, const CGUIListItem * item = nullptr) const private
References CONDITIONAL_LABEL_START, and m_skinVariableStrings.
Referenced by GetImage(), GetLabel(), GetMultiInfoItemImage(), and GetMultiInfoItemLabel().
Initialize()
void CGUIInfoManager::Initialize ()
References CServiceBroker::GetAppMessenger().
IsListItemInfo()
bool CGUIInfoManager::IsListItemInfo (int info) const private
References LISTITEM_END, LISTITEM_START, m_multiInfo, MULTI_INFO_END, and MULTI_INFO_START.
Referenced by GetMultiInfoBool().
OnApplicationMessage()
void CGUIInfoManager::OnApplicationMessage (KODI::MESSAGING::ThreadMessage * msg) override virtual
This gets called whenever a message matching the registered message mask is processed.
There are no ordering guarantees here so implementations should never rely on a certain ordering of messages.
Cleaning up any pointers stored in the message payload is not specified and is decided by the implementer of the message. In general prefer to delete any data in this method to keep the callsites cleaner and simpler but if data is to be passed back it's perfectly valid to handle it any way that fits the situation as long as it's documented along with the message.
To return a simple value the result parameter of
See also
ThreadMessage can be used as it will be used as the return value for
CApplicationMessenger::SendMsg. It is up to the implementer to decide if this is to be used and it should be documented along with any new message implemented.
Implements KODI::MESSAGING::IMessageTarget.
References INFO::DEFAULT_CONTEXT, KODI::MESSAGING::ThreadMessage::dwMessage, EvaluateBool(), GetLabel(), CFileItem::GetMusicInfoTag(), CFileItem::GetVideoInfoTag(), CFileItem::HasMusicInfoTag(), CFileItem::HasVideoInfoTag(), KODI::MESSAGING::ThreadMessage::lpVoid, KODI::MESSAGING::ThreadMessage::param1, KODI::MESSAGING::ThreadMessage::params, SetCurrentItem(), SetCurrentSongTag(), SetCurrentVideoTag(), TMSG_GUI_INFOBOOL, TMSG_GUI_INFOLABEL, TMSG_UPDATE_CURRENT_ITEM, and TranslateString().
Register()
INFO::InfoPtr CGUIInfoManager::Register (const std::string & expression, int context = 0)
Register a boolean condition/expression This routine allows controls or other clients of the info manager to register to receive updates of particular expressions, in a particular context (currently windows).
In the future, it will allow clients to receive pushed callbacks when the expression changes.
Parameters
expression the boolean condition or expression
context the context window
Returns
an identifier used to reference this expression
References m_bools, m_critInfo, m_refreshCounter, and KODI::GUILIB::GUIINFO::CGUIInfoLabel::ReplaceLocalize().
Referenced by CAnimation::Create(), INFO::CSkinVariable::CreateFromXML(), EvaluateBool(), INFO::InfoExpression::Initialize(), CContextMenuItem::IsVisible(), CGUIWindow::Load(), CGUIListItemLayout::LoadLayout(), CSkinTimerManager::LoadTimerInternal(), INFO::InfoExpression::Parse(), KODI::GUILIB::GUIINFO::CGUIInfoBool::Parse(), CGUIBaseContainer::SetAutoScrolling(), CGUITextBox::SetAutoScrolling(), CGUITextBox::SetAutoScrolling(), CGUIControl::SetEnableCondition(), CGUIRadioButtonControl::SetToggleSelect(), CGUIToggleButtonControl::SetToggleSelect(), CGUIStaticItem::SetVisibleCondition(), and CGUIControl::SetVisibleCondition().
RegisterInfoProvider()
void CGUIInfoManager::RegisterInfoProvider (KODI::GUILIB::GUIINFO::IGUIInfoProvider * provider)
register a guiinfo provider
Parameters
the guiinfo provider to register
References CServiceBroker::GetWinSystem(), m_infoProviders, and KODI::GUILIB::GUIINFO::CGUIInfoProviders::RegisterProvider().
Referenced by PVR::CPVRGUIInfo::Process().
RegisterSkinVariableString()
int CGUIInfoManager::RegisterSkinVariableString (const INFO::CSkinVariableString * info)
References CONDITIONAL_LABEL_START, m_critInfo, and m_skinVariableStrings.
Referenced by KODI::GUILIB::GUIINFO::CGUIInfoColor::Parse(), and KODI::GUILIB::GUIINFO::CGUIInfoLabel::Parse().
ResetCache()
void CGUIInfoManager::ResetCache ()
References m_critInfo, and m_refreshCounter.
Referenced by CProfileManager::LoadProfile(), CApplication::Render(), CSkinSettings::Reset(), CGUIWindow::SetInitialVisibility(), and CGUIViewControl::UpdateViewVisibility().
ResetCurrentItem()
void CGUIInfoManager::ResetCurrentItem ()
References KODI::GUILIB::GUIINFO::CGUIInfoProviders::InitCurrentItem(), m_currentFile, m_infoProviders, and CFileItem::Reset().
ResolveMultiInfo()
int CGUIInfoManager::ResolveMultiInfo (int info) const private
References m_multiInfo, MULTI_INFO_END, and MULTI_INFO_START.
Referenced by GetMultiInfoBool().
SetCurrentAlbumThumb()
void CGUIInfoManager::SetCurrentAlbumThumb (const std::string & thumbFileName)
References CFileUtils::Exists(), KODI::ART::FillInDefaultIcon(), m_currentFile, and CGUIListItem::SetArt().
Referenced by CAirTunesServer::RefreshCoverArt().
SetCurrentItem()
void CGUIInfoManager::SetCurrentItem (const CFileItem & item)
Set currently playing file item.
References KODI::ART::FillInDefaultIcon(), CServiceBroker::GetAnnouncementManager(), ANNOUNCEMENT::Info, KODI::GUILIB::GUIINFO::CGUIInfoProviders::InitCurrentItem(), m_currentFile, and m_infoProviders.
Referenced by PVR::CPVRGUIChannelNavigator::HideInfo(), CApplication::OnAction(), OnApplicationMessage(), CApplication::OnMessage(), CVideoPlayerAudioID3::ProcessID3v1(), CVideoPlayerAudioID3::ProcessID3v2(), CDVDRadioRDSData::ProcessUECP(), PVR::CPVRGUIChannelNavigator::SelectChannel(), PVR::CPVRGUIChannelNavigator::SetPlayingChannel(), and CApplication::UpdateCurrentPlayArt().
SetCurrentSongTag()
void CGUIInfoManager::SetCurrentSongTag (const MUSIC_INFO::CMusicInfoTag & tag) private
References m_currentFile, CFileItem::SetFromMusicInfoTag(), and CFileItem::SetStartOffset().
Referenced by OnApplicationMessage().
SetCurrentVideoTag()
void CGUIInfoManager::SetCurrentVideoTag (const CVideoInfoTag & tag) private
References m_currentFile, CFileItem::SetFromVideoInfoTag(), and CFileItem::SetStartOffset().
Referenced by OnApplicationMessage().
SplitInfoString()
void CGUIInfoManager::SplitInfoString (const std::string & infoString, std::vector< Property > & info) private
Split an info string into it's constituent parts and parameters Format is:
info1(params1).info2(params2).info3(params3) ...
where the parameters are an optional comma separated parameter list.
Parameters
infoString the original string
info the resulting pairs of info and parameters.
References CLog::Log(), and LOGERROR.
Referenced by TranslateSingleString().
TranslateListItem()
int CGUIInfoManager::TranslateListItem (const Property & cat, const Property & prop, int id, bool container) private
References AddMultiInfo(), INFOFLAG_LISTITEM_ABSOLUTE, INFOFLAG_LISTITEM_CONTAINER, INFOFLAG_LISTITEM_NOWRAP, INFOFLAG_LISTITEM_POSITION, INFOFLAG_LISTITEM_WRAP, LISTITEM_ART, listitem_labels, CGUIInfoManager::Property::name, CGUIInfoManager::Property::num_params(), CGUIInfoManager::Property::param(), and TranslateTimeFormat().
Referenced by TranslateSingleString().
TranslateMusicPlayerString()
int CGUIInfoManager::TranslateMusicPlayerString (const std::string & info) const private
References musicplayer.
Referenced by TranslateSingleString().
TranslatePlayerString()
int CGUIInfoManager::TranslatePlayerString (const std::string & info) const private
References player_labels.
Referenced by TranslateSingleString().
TranslateSingleString() [1/2]
int CGUIInfoManager::TranslateSingleString (const std::string & strCondition) private
Translates a string as given by the skin into an int that we use for more efficient retrieval of data.
References TranslateSingleString().
TranslateSingleString() [2/2]
int CGUIInfoManager::TranslateSingleString (const std::string & strCondition, bool & listItemDependent)
Todo:
change to IsScanning(Video)
Todo:
remove these, they're repeats
Todo:
remove these, they're repeats
Todo:
this doesn't support foo.xml
Todo:
The parameter for these should really be on the first not the second property
Todo:
The parameter for these should really be on the first not the second property
Todo:
replace with a single system.platform
Todo:
these two don't allow duration(foo) and also don't allow more than this number of levels...
Todo:
these two don't allow duration(foo) and also don't allow more than this number of levels...
Todo:
these two don't allow duration(foo) and also don't allow more than this number of levels...
Todo:
The parameter for these should really be on the first not the second property
References AddMultiInfo(), addons, container_bools, container_ints, CONTAINER_SORT_DIRECTION, container_str, CONTROL_GROUP_HAS_FOCUS, control_labels, data(), INFO::DEFAULT_CONTEXT, fanart_labels, CSkinSettings::GetInstance(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), integer_bools, INTEGER_VALUEOF, label, LIBRARY_HAS_BOXSETS, LIBRARY_HAS_COMPILATIONS, LIBRARY_HAS_MOVIE_SETS, LIBRARY_HAS_MOVIES, LIBRARY_HAS_MUSIC, LIBRARY_HAS_MUSICVIDEOS, LIBRARY_HAS_NODE, LIBRARY_HAS_ROLE, LIBRARY_HAS_SINGLES, LIBRARY_HAS_TVSHOWS, LIBRARY_HAS_VIDEO, LIBRARY_IS_SCANNING, LIBRARY_IS_SCANNING_MUSIC, LIBRARY_IS_SCANNING_VIDEO, mediacontainer, musicpartymode, MUSICPLAYER_CONTENT, MUSICPLAYER_PROPERTY, name, CGUIInfoManager::Property::name, network_labels, node, CGUIInfoManager::Property::num_params(), CGUIInfoManager::Property::param(), PLAYER_ITEM_ART, player_labels, player_param, player_process, player_times, playlist, pvr, pvr_times, rds, RDS_GET_RADIOTEXT_LINE, retroplayer, SKIN_BOOL, SKIN_HAS_THEME, SKIN_INTEGER, skin_labels, SKIN_STRING, SKIN_STRING_IS_EQUAL, SKIN_TIMER_ELAPSEDSECS, SKIN_TIMER_IS_RUNNING, slideshow, SortOrderAscending, SortOrderDescending, SortOrderNone, SplitInfoString(), string_bools, STRING_IS_EMPTY, SYSTEM_ADDON_ICON, SYSTEM_ADDON_TITLE, SYSTEM_ADDON_VERSION, SYSTEM_ALARM_LESS_OR_EQUAL, SYSTEM_ALWAYS_FALSE, SYSTEM_ALWAYS_TRUE, SYSTEM_DATE, SYSTEM_FREE_MEMORY, SYSTEM_FREE_MEMORY_PERCENT, SYSTEM_GET_BOOL, SYSTEM_IDLE_TIME, system_labels, SYSTEM_LOCALE, SYSTEM_LOCALE_REGION, system_param, SYSTEM_PLATFORM_ANDROID, SYSTEM_PLATFORM_DARWIN, SYSTEM_PLATFORM_DARWIN_IOS, SYSTEM_PLATFORM_DARWIN_OSX, SYSTEM_PLATFORM_DARWIN_TVOS, SYSTEM_PLATFORM_LINUX, SYSTEM_PLATFORM_UWP, SYSTEM_PLATFORM_WEBOS, SYSTEM_PLATFORM_WINDOWS, SYSTEM_TIME, SYSTEM_TOTAL_MEMORY, SYSTEM_USED_MEMORY, SYSTEM_USED_MEMORY_PERCENT, TIME_FORMAT_GUESS, TranslateListItem(), TranslateMusicPlayerString(), TranslatePlayerString(), TranslateSingleString(), TranslateString(), TranslateTimeFormat(), TranslateVideoPlayerString(), CWindowTranslator::TranslateWindow(), value, VIDEOPLAYER_ART, VIDEOPLAYER_CONTENT, VIDEOPLAYER_UNIQUEID, visualisation, weather, window_bools, WINDOW_INVALID, and WINDOW_PROPERTY.
Referenced by INFO::InfoSingle::Initialize(), TranslateSingleString(), TranslateSingleString(), and TranslateString().
TranslateSkinVariableString()
int CGUIInfoManager::TranslateSkinVariableString (const std::string & name, int context)
References CONDITIONAL_LABEL_START, m_skinVariableStrings, and name.
Referenced by KODI::GUILIB::GUIINFO::CGUIInfoColor::Parse(), and KODI::GUILIB::GUIINFO::CGUIInfoLabel::Parse().
TranslateString()
int CGUIInfoManager::TranslateString (const std::string & strCondition)
Translates a string as given by the skin into an int that we use for more efficient retrieval of data. Can handle combined strings on the form Player.Caching + VideoPlayer.IsFullscreen (Logical and) Player.HasVideo | Player.HasAudio (Logical or)
References KODI::GUILIB::GUIINFO::CGUIInfoLabel::ReplaceLocalize(), and TranslateSingleString().
Referenced by CGUIControlFactory::Create(), XBMCAddon::xbmc::getInfoImage(), XBMCAddon::xbmc::getInfoLabel(), OnApplicationMessage(), KODI::GUILIB::GUIINFO::CGUIInfoColor::Parse(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::Parse(), and TranslateSingleString().
TranslateTimeFormat()
TIME_FORMAT CGUIInfoManager::TranslateTimeFormat (const std::string & format) static private
References TIME_FORMAT_GUESS, TIME_FORMAT_H, TIME_FORMAT_H_MM_SS, TIME_FORMAT_H_MM_SS_XX, TIME_FORMAT_HH, TIME_FORMAT_HH_MM, TIME_FORMAT_HH_MM_SS, TIME_FORMAT_HH_MM_SS_XX, TIME_FORMAT_HOURS, TIME_FORMAT_M, TIME_FORMAT_MINS, TIME_FORMAT_MM, TIME_FORMAT_MM_SS, TIME_FORMAT_SECS, TIME_FORMAT_SS, and TIME_FORMAT_XX.
Referenced by TranslateListItem(), and TranslateSingleString().
TranslateVideoPlayerString()
int CGUIInfoManager::TranslateVideoPlayerString (const std::string & info) const private
References videoplayer.
Referenced by TranslateSingleString().
UnRegister()
void CGUIInfoManager::UnRegister (const INFO::InfoPtr & expression)
Unregister a boolean condition/expression This routine allows controls or other clients of the info manager to unregister a previously registered boolean condition/expression.
Parameters
expression the boolean condition or expression
References m_bools, and m_critInfo.
Referenced by CSkinTimerManager::Stop().
UnregisterInfoProvider()
void CGUIInfoManager::UnregisterInfoProvider (KODI::GUILIB::GUIINFO::IGUIInfoProvider * provider)
unregister a guiinfo provider
Parameters
the guiinfo provider to unregister
References CServiceBroker::GetWinSystem(), m_infoProviders, and KODI::GUILIB::GUIINFO::CGUIInfoProviders::UnregisterProvider().
Referenced by PVR::CPVRGUIInfo::Stop().
UpdateAVInfo()
void CGUIInfoManager::UpdateAVInfo ()
References CURRENT_STREAM, CServiceBroker::GetAppComponents(), CServiceBroker::GetDataCacheCore(), CApplicationPlayer::GetVideoStreamInfo(), m_infoProviders, and KODI::GUILIB::GUIINFO::CGUIInfoProviders::UpdateAVInfo().
Referenced by CGUIWindowManager::FrameMove().
UpdateCurrentItem()
void CGUIInfoManager::UpdateCurrentItem (const CFileItem & item)
References m_currentFile, and CFileItem::UpdateInfo().
Referenced by CApplication::OnApplicationMessage(), and CApplication::OnMessage().
Member Data Documentation
m_bools
INFOBOOLTYPE CGUIInfoManager::m_bools private
Referenced by Clear(), Register(), and UnRegister().
m_critInfo
CCriticalSection CGUIInfoManager::m_critInfo private
Referenced by Clear(), Register(), RegisterSkinVariableString(), ResetCache(), and UnRegister().
m_currentFile
CFileItem* CGUIInfoManager::m_currentFile private
Referenced by GetBool(), GetCurrentGameTag(), GetCurrentMovieTag(), GetCurrentSongTag(), GetInt(), GetLabel(), GetMultiInfoBool(), GetMultiInfoInt(), GetMultiInfoLabel(), ResetCurrentItem(), SetCurrentAlbumThumb(), SetCurrentItem(), SetCurrentSongTag(), SetCurrentVideoTag(), UpdateCurrentItem(), and ~CGUIInfoManager().
m_infoProviders
KODI::GUILIB::GUIINFO::CGUIInfoProviders CGUIInfoManager::m_infoProviders private
Referenced by GetBool(), GetInfoProviders(), GetInt(), GetItemBool(), GetItemInt(), GetLabel(), GetMultiInfoBool(), GetMultiInfoInt(), GetMultiInfoItemLabel(), GetMultiInfoLabel(), RegisterInfoProvider(), ResetCurrentItem(), SetCurrentItem(), UnregisterInfoProvider(), and UpdateAVInfo().
m_multiInfo
std::vector<KODI::GUILIB::GUIINFO::CGUIInfo> CGUIInfoManager::m_multiInfo private
Referenced by AddMultiInfo(), GetBool(), GetImage(), GetInt(), GetLabel(), GetMultiInfoBool(), GetMultiInfoItemImage(), GetMultiInfoItemLabel(), IsListItemInfo(), and ResolveMultiInfo().
m_refreshCounter
unsigned int CGUIInfoManager::m_refreshCounter = 0 private
Referenced by Register(), and ResetCache().
m_skinVariableStrings
std::vector<INFO::CSkinVariableString> CGUIInfoManager::m_skinVariableStrings private
Referenced by Clear(), GetSkinVariableString(), RegisterSkinVariableString(), and TranslateSkinVariableString().
The documentation for this class was generated from the following files:
GUIInfoManager.h
GUIInfoManager.cpp