Kodi Documentation: KODI::GAME::CGameClientTranslator Class Reference
KODI::GAME::CGameClientTranslator Class Reference
Games
Translates data types from Game API to the corresponding format in Kodi.
#include <GameClientTranslator.h>
Static Public Member Functions
static const char * ToString (GAME_ERROR error)
Translates game errors to string representation (e.g. for logging).
static const char * ToString (GAME_MEMORY error)
Translates game memory types to string representation (e.g. for logging).
static bool TranslateStreamType (GAME_STREAM_TYPE gameType, RETRO::StreamType &retroType)
Translate stream type (Game API to RetroPlayer).
static AVPixelFormat TranslatePixelFormat (GAME_PIXEL_FORMAT format)
Translate pixel format (Game API to RetroPlayer/FFMPEG).
static GAME_PIXEL_FORMAT TranslatePixelFormat (AVPixelFormat format)
Translate pixel format (RetroPlayer/FFMPEG to Game API).
static RETRO::PCMFormat TranslatePCMFormat (GAME_PCM_FORMAT format)
Translate audio PCM format (Game API to RetroPlayer).
static RETRO::AudioChannel TranslateAudioChannel (GAME_AUDIO_CHANNEL channel)
Translate audio channels (Game API to RetroPlayer).
static RETRO::VideoRotation TranslateRotation (GAME_VIDEO_ROTATION rotation)
Translate video rotation (Game API to RetroPlayer).
static GAME_KEY_MOD GetModifiers (KEYBOARD::Modifier modifier)
Translate key modifiers (Kodi to Game API).
static const char * TranslateRegion (GAME_REGION region)
Translate region to string representation (e.g. for logging).
static PORT_TYPE TranslatePortType (GAME_PORT_TYPE portType)
Translate port type (Game API to Kodi)
Private Member Functions
CGameClientTranslator ()=delete
Detailed Description
Translates data types from Game API to the corresponding format in Kodi.
This class is stateless.
Constructor & Destructor Documentation
CGameClientTranslator()
KODI::GAME::CGameClientTranslator::CGameClientTranslator () private delete
Member Function Documentation
GetModifiers()
GAME_KEY_MOD CGameClientTranslator::GetModifiers (KEYBOARD::Modifier modifier) static
Translate key modifiers (Kodi to Game API).
Parameters
modifiers The key modifiers to translate (e.g. Shift, Ctrl).
Returns
Translated key modifiers.
References GAME_KEY_MOD_ALT, GAME_KEY_MOD_CAPSLOCK, GAME_KEY_MOD_CTRL, GAME_KEY_MOD_META, GAME_KEY_MOD_NONE, GAME_KEY_MOD_NUMLOCK, GAME_KEY_MOD_SCROLLOCK, GAME_KEY_MOD_SHIFT, GAME_KEY_MOD_SUPER, and KODI::GAME::KEYBOARD.
Referenced by KODI::GAME::CGameClientKeyboard::OnKeyPress(), and KODI::GAME::CGameClientKeyboard::OnKeyRelease().
ToString() [1/2]
const char * CGameClientTranslator::ToString (GAME_ERROR error) static
Translates game errors to string representation (e.g. for logging).
Parameters
error The error to translate.
Returns
Translated error.
References GAME_ERROR_FAILED, GAME_ERROR_INVALID_PARAMETERS, GAME_ERROR_NO_ERROR, GAME_ERROR_NOT_IMPLEMENTED, GAME_ERROR_NOT_LOADED, GAME_ERROR_REJECTED, and GAME_ERROR_RESTRICTED.
Referenced by KODI::GAME::CGameClientInGameSaves::Load(), KODI::GAME::CGameClient::LogError(), and KODI::GAME::CGameClientInGameSaves::Save().
ToString() [2/2]
const char * CGameClientTranslator::ToString (GAME_MEMORY error) static
Translates game memory types to string representation (e.g. for logging).
Parameters
memory The memory type to translate.
Returns
Translated memory type.
References GAME_MEMORY_RTC, GAME_MEMORY_SAVE_RAM, GAME_MEMORY_SNES_BSX_RAM, GAME_MEMORY_SNES_GAME_BOY_RAM, GAME_MEMORY_SNES_GAME_BOY_RTC, GAME_MEMORY_SNES_SUFAMI_TURBO_A_RAM, GAME_MEMORY_SNES_SUFAMI_TURBO_B_RAM, GAME_MEMORY_SYSTEM_RAM, and GAME_MEMORY_VIDEO_RAM.
TranslateAudioChannel()
RETRO::AudioChannel CGameClientTranslator::TranslateAudioChannel (GAME_AUDIO_CHANNEL channel) static
Translate audio channels (Game API to RetroPlayer).
Parameters
format The audio channels to translate.
Returns
Translated audio channels.
References KODI::RETRO::CH_BC, KODI::RETRO::CH_BL, KODI::RETRO::CH_BLOC, KODI::RETRO::CH_BR, KODI::RETRO::CH_BROC, KODI::RETRO::CH_FC, KODI::RETRO::CH_FL, KODI::RETRO::CH_FLOC, KODI::RETRO::CH_FR, KODI::RETRO::CH_FROC, KODI::RETRO::CH_LFE, KODI::RETRO::CH_NULL, KODI::RETRO::CH_SL, KODI::RETRO::CH_SR, KODI::RETRO::CH_TBC, KODI::RETRO::CH_TBL, KODI::RETRO::CH_TBR, KODI::RETRO::CH_TC, KODI::RETRO::CH_TFC, KODI::RETRO::CH_TFL, KODI::RETRO::CH_TFR, GAME_CH_BC, GAME_CH_BL, GAME_CH_BLOC, GAME_CH_BR, GAME_CH_BROC, GAME_CH_FC, GAME_CH_FL, GAME_CH_FLOC, GAME_CH_FR, GAME_CH_FROC, GAME_CH_LFE, GAME_CH_SL, GAME_CH_SR, GAME_CH_TBC, GAME_CH_TBL, GAME_CH_TBR, GAME_CH_TC, GAME_CH_TFC, GAME_CH_TFL, and GAME_CH_TFR.
Referenced by KODI::GAME::CGameClientStreamAudio::TranslateProperties().
TranslatePCMFormat()
RETRO::PCMFormat CGameClientTranslator::TranslatePCMFormat (GAME_PCM_FORMAT format) static
Translate audio PCM format (Game API to RetroPlayer).
Parameters
format The audio PCM format to translate.
Returns
Translated audio PCM format.
References KODI::RETRO::FMT_S16NE, KODI::RETRO::FMT_UNKNOWN, and GAME_PCM_FORMAT_S16NE.
Referenced by KODI::GAME::CGameClientStreamAudio::TranslateProperties().
TranslatePixelFormat() [1/2]
GAME_PIXEL_FORMAT CGameClientTranslator::TranslatePixelFormat (AVPixelFormat format) static
Translate pixel format (RetroPlayer/FFMPEG to Game API).
Parameters
format The pixel format to translate.
Returns
Translated pixel format.
References GAME_PIXEL_FORMAT_0RGB1555, GAME_PIXEL_FORMAT_0RGB8888, GAME_PIXEL_FORMAT_RGB565, and GAME_PIXEL_FORMAT_UNKNOWN.
TranslatePixelFormat() [2/2]
AVPixelFormat CGameClientTranslator::TranslatePixelFormat (GAME_PIXEL_FORMAT format) static
Translate pixel format (Game API to RetroPlayer/FFMPEG).
Parameters
format The pixel format to translate.
Returns
Translated pixel format.
References GAME_PIXEL_FORMAT_0RGB1555, GAME_PIXEL_FORMAT_0RGB8888, and GAME_PIXEL_FORMAT_RGB565.
Referenced by KODI::GAME::CGameClientStreamSwFramebuffer::GetBuffer(), and KODI::GAME::CGameClientStreamVideo::TranslateProperties().
TranslatePortType()
PORT_TYPE CGameClientTranslator::TranslatePortType (GAME_PORT_TYPE portType) static
Translate port type (Game API to Kodi)
Parameters
portType The port type to translate
Returns
Translated port type
References KODI::GAME::CONTROLLER, GAME_PORT_CONTROLLER, GAME_PORT_KEYBOARD, GAME_PORT_MOUSE, KODI::GAME::KEYBOARD, KODI::GAME::MOUSE, and KODI::GAME::UNKNOWN.
TranslateRegion()
const char * CGameClientTranslator::TranslateRegion (GAME_REGION region) static
Translate region to string representation (e.g. for logging).
Parameters
error The region to translate (e.g. PAL, NTSC).
Returns
Translated region.
References GAME_REGION_NTSC, and GAME_REGION_PAL.
Referenced by KODI::GAME::CGameClient::LoadGameInfo().
TranslateRotation()
RETRO::VideoRotation CGameClientTranslator::TranslateRotation (GAME_VIDEO_ROTATION rotation) static
Translate video rotation (Game API to RetroPlayer).
Parameters
rotation The video rotation to translate.
Returns
Translated video rotation.
References GAME_VIDEO_ROTATION_180_CCW, GAME_VIDEO_ROTATION_270_CCW, GAME_VIDEO_ROTATION_90_CCW, KODI::RETRO::ROTATION_0, KODI::RETRO::ROTATION_180_CCW, KODI::RETRO::ROTATION_270_CCW, and KODI::RETRO::ROTATION_90_CCW.
Referenced by KODI::GAME::CGameClientStreamVideo::AddData().
TranslateStreamType()
bool CGameClientTranslator::TranslateStreamType (GAME_STREAM_TYPE gameType, RETRO::StreamType & retroType) static
Translate stream type (Game API to RetroPlayer).
Parameters
gameType The stream type to translate.
[out] retroType The translated stream type.
Returns
True if the Game API type was translated to a valid RetroPlayer type
References KODI::RETRO::AUDIO, GAME_STREAM_AUDIO, GAME_STREAM_HW_FRAMEBUFFER, GAME_STREAM_SW_FRAMEBUFFER, GAME_STREAM_VIDEO, KODI::RETRO::HW_BUFFER, KODI::RETRO::SW_BUFFER, and KODI::RETRO::VIDEO.
Referenced by KODI::GAME::CGameClientStreams::OpenStream().
The documentation for this class was generated from the following files:
GameClientTranslator.h
GameClientTranslator.cpp