Kodi Documentation: CDecoderFilterManager Class Reference
CDecoderFilterManager Class Reference
Class which handles multiple CDecoderFilter elements.
#include <DecoderFilterManager.h>
Public Member Functions
CDecoderFilterManager ()
virtual ~CDecoderFilterManager ()
void add (const CDecoderFilter &filter)
adds an CDecoderFilter if key [filter.name] is not yet existing.
bool isValid (const std::string &name, const CDVDStreamInfo &streamInfo)
Protected Member Functions
bool Load ()
bool Save () const
Private Attributes
bool m_dirty = false
std::set< CDecoderFilter > m_filters
CCriticalSection m_critical
Detailed Description
Class which handles multiple CDecoderFilter elements.
Constructor & Destructor Documentation
CDecoderFilterManager()
CDecoderFilterManager::CDecoderFilterManager () inline
References Load().
~CDecoderFilterManager()
virtual CDecoderFilterManager::~CDecoderFilterManager () inline virtual
References Save().
Member Function Documentation
add()
bool CDecoderFilterManager::add (const CDecoderFilter & filter)
adds an CDecoderFilter if key [filter.name] is not yet existing.
Parameters
filter the decoder filter to add / replace.
Returns
nothing.
References m_critical, m_dirty, and m_filters.
Referenced by CMediaCodecDecoderFilterManager::CMediaCodecDecoderFilterManager().
isValid()
bool CDecoderFilterManager::isValid (const std::string & name, const CDVDStreamInfo & streamInfo)
References m_critical, m_filters, and name.
Referenced by CDVDVideoCodecAndroidMediaCodec::Open().
Load()
bool CDecoderFilterManager::Load () protected
References XFILE::CFile::Exists(), HWDFFileName, CDecoderFilter::Load(), CXBMCTinyXML2::LoadFile(), LOGERROR, LOGINFO, m_critical, m_filters, TAG_FILTER, TAG_ROOT, and CUtil::TranslateSpecialSource().
Referenced by CDecoderFilterManager().
Save()
bool CDecoderFilterManager::Save () const protected
References HWDFFileName, m_critical, m_dirty, m_filters, node, root, CXBMCTinyXML2::SaveFile(), TAG_FILTER, TAG_ROOT, and CUtil::TranslateSpecialSource().
Referenced by CMediaCodecDecoderFilterManager::CMediaCodecDecoderFilterManager(), and ~CDecoderFilterManager().
Member Data Documentation
m_critical
CCriticalSection CDecoderFilterManager::m_critical mutable private
Referenced by add(), isValid(), Load(), and Save().
m_dirty
bool CDecoderFilterManager::m_dirty = false private
Referenced by add(), and Save().
m_filters
std::set<CDecoderFilter> CDecoderFilterManager::m_filters private
Referenced by add(), isValid(), Load(), and Save().
The documentation for this class was generated from the following files:
DecoderFilterManager.h
DecoderFilterManager.cpp