Kodi Documentation: KODI::GAME::CGameClient Class Reference
KODI::GAME::CGameClient Class Reference
Games
Interface between Kodi and Game add-ons.
#include <GameClient.h>
Public Member Functions
CGameClient (const ADDON::AddonInfoPtr &addonInfo)
~CGameClient () override
const CGameClientCheevos & Cheevos () const
const CGameClientInput & Input () const
const CGameClientProperties & AddonProperties () const
const CGameClientStreams & Streams () const
CGameClientCheevos & Cheevos ()
CGameClientInput & Input ()
CGameClientProperties & AddonProperties ()
CGameClientStreams & Streams ()
std::string LibPath () const override
ADDON::AddonPtr GetRunningInstance () const override
retrieve the running instance of an add-on if it persists while running.
bool SupportsStandalone () const
bool SupportsPath () const
bool SupportsVFS () const
const std::set< std::string > & GetExtensions () const
bool SupportsAllExtensions () const
bool IsExtensionValid (const std::string &strExtension) const
const std::string & GetEmulatorName () const
const std::string & GetPlatforms () const
bool Initialize (void)
void Unload ()
bool OpenFile (const CFileItem &file, RETRO::IStreamManager &streamManager, IGameInputCallback *input)
bool OpenStandalone (RETRO::IStreamManager &streamManager, IGameInputCallback *input)
void Reset ()
void CloseFile ()
const std::string & GetGamePath () const
bool RequiresGameLoop () const
bool IsPlaying () const
size_t GetSerializeSize () const
double GetFrameRate () const
double GetSampleRate () const
void RunFrame ()
size_t SerializeSize () const
bool Serialize (uint8_t *data, size_t size)
bool Deserialize (const uint8_t *data, size_t size)
AddonInstance_Game * GetInstanceInterface ()
To get the interface table used between addon and kodi.
bool LogError (GAME_ERROR error, const char *strMethod) const
void LogException (const char *strFunctionName) const
Public Member Functions inherited from ADDON::CAddonDll
CAddonDll (const AddonInfoPtr &addonInfo, BinaryAddonBasePtr addonBase)
CAddonDll (const AddonInfoPtr &addonInfo, AddonType addonType)
~CAddonDll () override
bool SaveSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
Save any user configured settings.
bool DllLoaded (void) const
CAddonVersion GetTypeVersionDll (int type) const
Get api version of moduleType type.
CAddonVersion GetTypeMinVersionDll (int type) const
Get api min version of moduleType type.
ADDON_STATUS CreateInstance (KODI_ADDON_INSTANCE_STRUCT *instance)
Function to create a addon instance class.
void DestroyInstance (KODI_ADDON_INSTANCE_STRUCT *instance)
Function to destroy a on addon created instance class.
bool IsInUse () const override
void RegisterInformer (CAddonDllInformer *informer)
void OnPreInstall () override
void OnPostInstall (bool update, bool modal) override
void OnPreUnInstall () override
void OnPostUnInstall () override
bool Initialized () const
Public Member Functions inherited from ADDON::CAddon
CAddon (const AddonInfoPtr &addonInfo, AddonType addonType)
~CAddon () override=default
AddonType MainType () const override
To get the main type of this addon.
AddonType Type () const override
To get the on this CAddon class processed addon type.
bool HasType (AddonType type) const override
To check complete addon (not only this) contains a type.
bool HasMainType (AddonType type) const override
To check complete addon (not only this) has a specific type defined in its first extension point including the provided subcontent e.g. video or audio.
const CAddonType * Type (AddonType type) const
The get for given addon type information and extension data.
std::string ID () const override
std::string Name () const override
bool IsBinary () const override
CAddonVersion Version () const override
CAddonVersion MinVersion () const override
std::string Summary () const override
std::string Description () const override
std::string Path () const override
std::string Profile () const override
std::string Author () const override
std::string ChangeLog () const override
std::string Icon () const override
ArtMap Art () const override
std::vector< std::string > Screenshots () const override
std::string Disclaimer () const override
AddonLifecycleState LifecycleState () const override
std::string LifecycleStateDescription () const override
CDateTime InstallDate () const override
CDateTime LastUpdated () const override
CDateTime LastUsed () const override
std::string Origin () const override
std::string OriginName () const override
uint64_t PackageSize () const override
const InfoMap & ExtraInfo () const override
const std::vector< DependencyInfo > & GetDependencies () const override
std::string FanArt () const override
bool SupportsMultipleInstances () const override
Check add-on for support from independent work instances.
AddonInstanceSupport InstanceUseType () const override
Return the used instance path type of the add-on type.
std::vector< AddonInstanceId > GetKnownInstanceIds () const override
Gives active, independently working instance identifiers for this add-on.
bool SupportsInstanceSettings () const override
Check whether the add-on supports individual settings per add-on instance.
bool DeleteInstanceSettings (AddonInstanceId instance) override
Delete selected instance settings from storage.
bool CanHaveAddonOrInstanceSettings () override
Check whether this add-on can be configured by the user.
bool HasSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
Check whether this add-on can be configured by the user.
bool HasUserSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
Check whether the user has configured this add-on or not.
void UpdateSetting (const std::string &key, const std::string &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new value.
bool UpdateSettingBool (const std::string &key, bool value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new boolean value.
bool UpdateSettingInt (const std::string &key, int value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new integer value.
bool UpdateSettingNumber (const std::string &key, double value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new number value.
bool UpdateSettingString (const std::string &key, const std::string &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new string value.
std::string GetSetting (const std::string &key, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value.
bool GetSettingBool (const std::string &key, bool &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value as boolean.
bool GetSettingInt (const std::string &key, int &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value as integer.
bool GetSettingNumber (const std::string &key, double &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value as number.
bool GetSettingString (const std::string &key, std::string &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value as string.
std::shared_ptr< CAddonSettings > GetSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
CAddonVersion GetDependencyVersion (const std::string &dependencyID) const override
get the required version of a dependency.
bool MeetsVersion (const CAddonVersion &versionMin, const CAddonVersion &version) const override
return whether or not this addon satisfies the given version requirements
bool ReloadSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
void ResetSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
Public Member Functions inherited from ADDON::IAddon
virtual ~IAddon ()=default
Private Member Functions
bool InitializeGameplay (const std::string &gamePath, RETRO::IStreamManager &streamManager, IGameInputCallback *input)
bool LoadGameInfo ()
void NotifyError (GAME_ERROR error)
std::string GetMissingResource ()
void LogAddonProperties (void) const
Private Member Functions inherited from KODI::GAME::CGameClientStruct
CGameClientStruct ()
~CGameClientStruct ()
Static Private Member Functions
static void cb_close_game (KODI_HANDLE kodiInstance)
Callback functions from addon to kodi.
static KODI_GAME_STREAM_HANDLE cb_open_stream (KODI_HANDLE kodiInstance, const game_stream_properties *properties)
static bool cb_get_stream_buffer (KODI_HANDLE kodiInstance, KODI_GAME_STREAM_HANDLE stream, unsigned int width, unsigned int height, game_stream_buffer *buffer)
static void cb_add_stream_data (KODI_HANDLE kodiInstance, KODI_GAME_STREAM_HANDLE stream, const game_stream_packet *packet)
static void cb_release_stream_buffer (KODI_HANDLE kodiInstance, KODI_GAME_STREAM_HANDLE stream, game_stream_buffer *buffer)
static void cb_close_stream (KODI_HANDLE kodiInstance, KODI_GAME_STREAM_HANDLE stream)
static game_proc_address_t cb_hw_get_proc_address (KODI_HANDLE kodiInstance, const char *sym)
static bool cb_input_event (KODI_HANDLE kodiInstance, const game_input_event *event)
static std::pair< std::string, std::string > ParseLibretroName (const std::string &addonName)
Parse the name of a libretro game add-on into its emulator name and platforms.
Private Attributes
GameClientSubsystems m_subsystems
bool m_bSupportsVFS
bool m_bSupportsStandalone
std::set< std::string > m_extensions
bool m_bSupportsAllExtensions = false
std::string m_emulatorName
std::string m_platforms
std::atomic_bool m_bIsPlaying
std::string m_gamePath
bool m_bRequiresGameLoop = false
size_t m_serializeSize = 0
IGameInputCallback * m_input = nullptr
double m_framerate = 0.0
double m_samplerate = 0.0
GAME_REGION m_region = GAME_REGION_UNKNOWN
std::unique_ptr< CGameClientInGameSaves > m_inGameSaves
CCriticalSection m_critSection
Private Attributes inherited from KODI::GAME::CGameClientStruct
KODI_ADDON_INSTANCE_STRUCT m_ifc
Additional Inherited Members
Protected Member Functions inherited from ADDON::CAddon
virtual bool SettingsInitialized (AddonInstanceId id=ADDON_SETTINGS_ID) const
Whether or not the settings have been initialized.
virtual bool SettingsLoaded (AddonInstanceId id=ADDON_SETTINGS_ID) const
Whether or not the settings have been loaded.
bool LoadSettings (bool bForce, bool loadUserSettings, AddonInstanceId id=ADDON_SETTINGS_ID)
Load the default settings and override these with any previously configured user settings.
virtual bool LoadUserSettings (AddonInstanceId id=ADDON_SETTINGS_ID)
Load the user settings.
virtual bool HasSettingsToSave (AddonInstanceId id=ADDON_SETTINGS_ID) const
Whether there are settings to be saved.
virtual bool SettingsFromXML (const CXBMCTinyXML &doc, bool loadDefaults, AddonInstanceId id=ADDON_SETTINGS_ID)
Parse settings from an XML document.
virtual bool SettingsToXML (CXBMCTinyXML &doc, AddonInstanceId id=ADDON_SETTINGS_ID) const
Write settings into an XML document.
Static Protected Member Functions inherited from ADDON::CAddonDll
static std::string GetDllPath (const std::string &strFileName)
Protected Attributes inherited from ADDON::CAddonDll
std::string m_parentLib
Protected Attributes inherited from ADDON::CAddon
const AddonInfoPtr m_addonInfo
Detailed Description
Interface between Kodi and Game add-ons.
The game add-on system is extremely large. To make the code more manageable, a subsystem pattern has been put in place. This pattern takes functionality that would normally be placed in this class, and puts it in another class (a "subsystem").
The architecture is relatively simple. Subsystems are placed in a flat struct and accessed by calling the subsystem name. For example, historically, OpenJoystick() was a member of this class. Now, the function is called like Input().OpenJoystick().
Although this pattern adds a layer of complexity, it enforces modularity and separation of concerns by making it very clear when one subsystem becomes dependent on another. Subsystems are all given access to each other by the calling mechanism. However, calling a subsystem creates a dependency on it, and an engineering decision must be made to justify the dependency.
CONTRIBUTING
If you wish to contribute, a beneficial task would be to refactor anything in this class into a new subsystem:
Using line count as a heuristic, the subsystem pattern has shrunk the .cpp from 1,200 lines to just over 600. Reducing this further is the challenge. You must now choose whether to accept.
Constructor & Destructor Documentation
CGameClient()
CGameClient::CGameClient (const ADDON::AddonInfoPtr & addonInfo) explicit
References EXTENSION_SEPARATOR, EXTENSION_WILDCARD, GAME_PROPERTY_EXTENSIONS, GAME_PROPERTY_SUPPORTS_STANDALONE, GAME_PROPERTY_SUPPORTS_VFS, GetValue(), m_bSupportsAllExtensions, m_bSupportsStandalone, m_bSupportsVFS, m_emulatorName, m_extensions, m_platforms, ADDON::CAddon::Name(), ParseLibretroName(), and ADDON::CAddon::Type().
~CGameClient()
CGameClient::~CGameClient (void) override
References CloseFile(), KODI::GAME::CGameClientSubsystem::DestroySubsystems(), and m_subsystems.
Member Function Documentation
AddonProperties() [1/2]
CGameClientProperties & KODI::GAME::CGameClient::AddonProperties () inline
References KODI::GAME::GameClientSubsystems::AddonProperties, and m_subsystems.
AddonProperties() [2/2]
const CGameClientProperties & KODI::GAME::CGameClient::AddonProperties () const inline
References KODI::GAME::GameClientSubsystems::AddonProperties, and m_subsystems.
Referenced by KODI::GAME::CGameClientSubsystem::AddonProperties(), and Initialize().
cb_add_stream_data()
void CGameClient::cb_add_stream_data (KODI_HANDLE kodiInstance, KODI_GAME_STREAM_HANDLE stream, const game_stream_packet * packet) static private
References KODI::GAME::IGameClientStream::AddData().
Referenced by Initialize().
cb_close_game()
void CGameClient::cb_close_game (KODI_HANDLE kodiInstance) static private
Callback functions from addon to kodi.
References ACTION_STOP, CServiceBroker::GetAppMessenger(), TMSG_GUI_ACTION, and WINDOW_INVALID.
Referenced by Initialize().
cb_close_stream()
void CGameClient::cb_close_stream (KODI_HANDLE kodiInstance, KODI_GAME_STREAM_HANDLE stream) static private
References KODI::GAME::CGameClientStreams::CloseStream(), and Streams().
Referenced by Initialize().
cb_get_stream_buffer()
bool CGameClient::cb_get_stream_buffer (KODI_HANDLE kodiInstance, KODI_GAME_STREAM_HANDLE stream, unsigned int width, unsigned int height, game_stream_buffer * buffer) static private
References KODI::GAME::IGameClientStream::GetBuffer().
Referenced by Initialize().
cb_hw_get_proc_address()
game_proc_address_t CGameClient::cb_hw_get_proc_address (KODI_HANDLE kodiInstance, const char * sym) static private
Todo:
Referenced by Initialize().
cb_input_event()
bool CGameClient::cb_input_event (KODI_HANDLE kodiInstance, const game_input_event * event) static private
References Input(), and KODI::GAME::CGameClientInput::ReceiveInputEvent().
Referenced by Initialize().
cb_open_stream()
KODI_GAME_STREAM_HANDLE CGameClient::cb_open_stream (KODI_HANDLE kodiInstance, const game_stream_properties * properties) static private
References KODI::GAME::CGameClientStreams::OpenStream(), and Streams().
Referenced by Initialize().
cb_release_stream_buffer()
void CGameClient::cb_release_stream_buffer (KODI_HANDLE kodiInstance, KODI_GAME_STREAM_HANDLE stream, game_stream_buffer * buffer) static private
References KODI::GAME::IGameClientStream::ReleaseBuffer().
Referenced by Initialize().
Cheevos() [1/2]
CGameClientCheevos & KODI::GAME::CGameClient::Cheevos () inline
References KODI::GAME::GameClientSubsystems::Cheevos, and m_subsystems.
Cheevos() [2/2]
const CGameClientCheevos & KODI::GAME::CGameClient::Cheevos () const inline
References KODI::GAME::GameClientSubsystems::Cheevos, and m_subsystems.
Referenced by KODI::GAME::CGameClientSubsystem::Cheevos(), KODI::RETRO::CCheevos::EnableRichPresence(), KODI::RETRO::CCheevos::GetRichPresenceEvaluation(), KODI::RETRO::CCheevos::LoadData(), and KODI::RETRO::CCheevos::ResetRuntime().
CloseFile()
void CGameClient::CloseFile ()
References KODI::GAME::CGameClientStreams::Deinitialize(), KODI_ADDON_INSTANCE_STRUCT::game, Input(), LogError(), LogException(), m_bIsPlaying, m_critSection, m_gamePath, KODI::GAME::CGameClientStruct::m_ifc, m_inGameSaves, m_input, m_serializeSize, KODI::GAME::CGameClientInput::Stop(), Streams(), and AddonInstance_Game::toAddon.
Referenced by OpenFile(), OpenStandalone(), and ~CGameClient().
Deserialize()
bool CGameClient::Deserialize (const uint8_t * data, size_t size)
References data(), KODI_ADDON_INSTANCE_STRUCT::game, LogError(), LogException(), m_bIsPlaying, m_critSection, KODI::GAME::CGameClientStruct::m_ifc, and AddonInstance_Game::toAddon.
Referenced by KODI::RETRO::CReversiblePlayback::AdvanceFrames(), KODI::RETRO::CReversiblePlayback::LoadSavestate(), and KODI::RETRO::CReversiblePlayback::RewindFrames().
GetEmulatorName()
const std::string & KODI::GAME::CGameClient::GetEmulatorName () const inline
References m_emulatorName.
GetExtensions()
const std::set< std::string > & KODI::GAME::CGameClient::GetExtensions () const inline
References m_extensions.
Referenced by KODI::GAME::CGameClientProperties::GetExtensions().
GetFrameRate()
double KODI::GAME::CGameClient::GetFrameRate () const inline
References m_framerate.
Referenced by KODI::RETRO::CReversiblePlayback::CommitSavestate().
GetGamePath()
const std::string & KODI::GAME::CGameClient::GetGamePath () const inline
References m_gamePath.
Referenced by KODI::RETRO::CReversiblePlayback::CommitSavestate(), KODI::RETRO::CCheevos::ConsoleID(), KODI::RETRO::CReversiblePlayback::CreateSavestate(), KODI::GAME::CGameClientInGameSaves::GetPath(), and KODI::RETRO::CCheevos::LoadData().
GetInstanceInterface()
AddonInstance_Game * KODI::GAME::CGameClient::GetInstanceInterface () inline
To get the interface table used between addon and kodi.
Todo:
This function becomes removed after old callback library system is removed.
References KODI_ADDON_INSTANCE_STRUCT::game, and KODI::GAME::CGameClientStruct::m_ifc.
GetMissingResource()
std::string CGameClient::GetMissingResource () private
References ADDON::CAddonMgr::GetAddon(), CServiceBroker::GetAddonMgr(), and ADDON::CAddon::GetDependencies().
Referenced by NotifyError().
GetPlatforms()
const std::string & KODI::GAME::CGameClient::GetPlatforms () const inline
References m_platforms.
GetRunningInstance()
ADDON::AddonPtr CGameClient::GetRunningInstance () const override virtual
retrieve the running instance of an add-on if it persists while running.
Reimplemented from ADDON::CAddonDll.
References ADDON::CBinaryAddonCache::GetAddonInstance(), CServiceBroker::GetBinaryAddonCache(), ADDON::CAddon::ID(), and ADDON::CAddon::Type().
GetSampleRate()
double KODI::GAME::CGameClient::GetSampleRate () const inline
References m_samplerate.
Referenced by KODI::GAME::CGameClientStreams::CreateStream().
GetSerializeSize()
size_t KODI::GAME::CGameClient::GetSerializeSize () const inline
References m_serializeSize.
Initialize()
bool CGameClient::Initialize (void)
References URIUtils::AddFileToFolder(), ADDON_STATUS_OK, AddonProperties(), AddonToKodiFuncTable_Game::AddStreamData, cb_add_stream_data(), cb_close_game(), cb_close_stream(), cb_get_stream_buffer(), cb_hw_get_proc_address(), cb_input_event(), cb_open_stream(), cb_release_stream_buffer(), AddonToKodiFuncTable_Game::CloseGame, AddonToKodiFuncTable_Game::CloseStream, ADDON::CAddonDll::CreateInstance(), KODI_ADDON_INSTANCE_STRUCT::game, CServiceBroker::GetGameServices(), KODI::GAME::CGameServices::GetSavestatesFolder(), AddonToKodiFuncTable_Game::GetStreamBuffer, AddonToKodiFuncTable_Game::HwGetProcAddress, ADDON::CAddon::ID(), KODI::GAME::CGameClientInput::Initialize(), Input(), AddonToKodiFuncTable_Game::InputEvent, AddonToKodiFuncTable_Game::kodiInstance, LogAddonProperties(), KODI::GAME::CGameClientStruct::m_ifc, AddonToKodiFuncTable_Game::OpenStream, ADDON::CAddon::Profile(), AddonToKodiFuncTable_Game::ReleaseStreamBuffer, AddonInstance_Game::toAddon, and AddonInstance_Game::toKodi.
InitializeGameplay()
bool CGameClient::InitializeGameplay (const std::string & gamePath, RETRO::IStreamManager & streamManager, IGameInputCallback * input) private
References KODI_ADDON_INSTANCE_STRUCT::game, Input(), LoadGameInfo(), m_bIsPlaying, m_gamePath, KODI::GAME::CGameClientStruct::m_ifc, m_inGameSaves, m_input, and KODI::GAME::CGameClientInput::Start().
Referenced by OpenFile(), and OpenStandalone().
Input() [1/2]
CGameClientInput & KODI::GAME::CGameClient::Input () inline
References KODI::GAME::GameClientSubsystems::Input, and m_subsystems.
Input() [2/2]
const CGameClientInput & KODI::GAME::CGameClient::Input () const inline
References KODI::GAME::GameClientSubsystems::Input, and m_subsystems.
Referenced by KODI::GAME::CGameClientJoystick::AcceptsInput(), cb_input_event(), CloseFile(), KODI::GAME::CGameClientJoystick::HasFeature(), KODI::GAME::CGameClientKeyboard::HasKey(), Initialize(), InitializeGameplay(), KODI::GAME::CGameClientSubsystem::Input(), KODI::GAME::CGameClientJoystick::OnAccelerometerMotion(), KODI::GAME::CGameClientJoystick::OnAnalogStickMotion(), KODI::GAME::CGameClientJoystick::OnButtonMotion(), KODI::GAME::CGameClientMouse::OnButtonPress(), KODI::GAME::CGameClientJoystick::OnButtonPress(), KODI::GAME::CGameClientMouse::OnButtonRelease(), KODI::GAME::CGameClientKeyboard::OnKeyPress(), KODI::GAME::CGameClientKeyboard::OnKeyRelease(), KODI::GAME::CGameClientMouse::OnMotion(), KODI::GAME::CGameClientJoystick::OnThrottleMotion(), KODI::GAME::CGameClientJoystick::OnWheelMotion(), and Unload().
IsExtensionValid()
bool CGameClient::IsExtensionValid (const std::string & strExtension) const
References m_extensions, and SupportsAllExtensions().
IsPlaying()
bool KODI::GAME::CGameClient::IsPlaying () const inline
References m_bIsPlaying.
LibPath()
std::string CGameClient::LibPath () const override virtual
Reimplemented from ADDON::CAddonDll.
References KODI_ADDON_INSTANCE_STRUCT::game, ADDON::CAddonDll::GetDllPath(), KODI::GAME::CGameClientStruct::m_ifc, AddonInstance_Game::props, AddonProps_Game::proxy_dll_count, and AddonProps_Game::proxy_dll_paths.
LoadGameInfo()
bool CGameClient::LoadGameInfo () private
References game_system_timing::fps, KODI_ADDON_INSTANCE_STRUCT::game, CLog::Log(), LOGERROR, LogError(), LogException(), LOGINFO, m_bRequiresGameLoop, m_framerate, KODI::GAME::CGameClientStruct::m_ifc, m_region, m_samplerate, m_serializeSize, game_system_timing::sample_rate, AddonInstance_Game::toAddon, and KODI::GAME::CGameClientTranslator::TranslateRegion().
Referenced by InitializeGameplay().
LogAddonProperties()
void CGameClient::LogAddonProperties (void) const private
References ADDON::CAddon::ID(), CLog::Log(), LOGINFO, m_bSupportsStandalone, m_bSupportsVFS, m_extensions, ADDON::CAddon::Name(), and ADDON::CAddon::Version().
Referenced by Initialize().
LogError()
bool CGameClient::LogError (GAME_ERROR error, const char * strMethod) const
References GAME_ERROR_NO_ERROR, ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and KODI::GAME::CGameClientTranslator::ToString().
Referenced by CloseFile(), Deserialize(), LoadGameInfo(), OpenFile(), OpenStandalone(), KODI::GAME::CGameClientCheevos::RCEnableRichPresence(), KODI::GAME::CGameClientCheevos::RCGenerateHashFromFile(), KODI::GAME::CGameClientCheevos::RCGetGameIDUrl(), KODI::GAME::CGameClientCheevos::RCGetPatchFileUrl(), KODI::GAME::CGameClientCheevos::RCGetRichPresenceEvaluation(), KODI::GAME::CGameClientCheevos::RCPostRichPresenceUrl(), KODI::GAME::CGameClientCheevos::RCResetRuntime(), Reset(), RunFrame(), and Serialize().
LogException()
void CGameClient::LogException (const char * strFunctionName) const
References ADDON::CAddon::Author(), ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by CloseFile(), KODI::GAME::CGameClientInput::CloseKeyboard(), KODI::GAME::CGameClientInput::CloseMouse(), KODI::GAME::CGameClientInput::ConnectController(), Deserialize(), KODI::GAME::CGameClientInput::DisconnectController(), LoadGameInfo(), KODI::GAME::CGameClientInput::LoadTopology(), OpenFile(), KODI::GAME::CGameClientInput::OpenKeyboard(), KODI::GAME::CGameClientInput::OpenMouse(), OpenStandalone(), KODI::GAME::CGameClientCheevos::RCEnableRichPresence(), KODI::GAME::CGameClientCheevos::RCGenerateHashFromFile(), KODI::GAME::CGameClientCheevos::RCGetGameIDUrl(), KODI::GAME::CGameClientCheevos::RCGetPatchFileUrl(), KODI::GAME::CGameClientCheevos::RCGetRichPresenceEvaluation(), KODI::GAME::CGameClientCheevos::RCPostRichPresenceUrl(), KODI::GAME::CGameClientCheevos::RCResetRuntime(), Reset(), RunFrame(), Serialize(), and KODI::GAME::CGameClientInput::SetControllerLayouts().
NotifyError()
void CGameClient::NotifyError (GAME_ERROR error) private
References g_localizeStrings, GAME_ERROR_RESTRICTED, CLocalizeStrings::Get(), GetMissingResource(), ADDON::CAddon::Name(), and KODI::MESSAGING::HELPERS::ShowOKDialogText().
Referenced by OpenFile(), and OpenStandalone().
OpenFile()
bool CGameClient::OpenFile (const CFileItem & file, RETRO::IStreamManager & streamManager, IGameInputCallback * input)
References CloseFile(), KODI::GAME::CGameClientStreams::Deinitialize(), CFileUtils::Exists(), g_localizeStrings, KODI_ADDON_INSTANCE_STRUCT::game, GAME_ERROR_FAILED, GAME_ERROR_NO_ERROR, CURL::Get(), CLocalizeStrings::Get(), CURL::GetProtocol(), KODI::GAME::CGameClientStreams::Initialize(), ADDON::CAddonDll::Initialized(), InitializeGameplay(), CLog::Log(), LOGDEBUG, LogError(), LogException(), m_bSupportsVFS, m_critSection, KODI::GAME::CGameClientStruct::m_ifc, NotifyError(), CURL::SetProtocol(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), Streams(), AddonInstance_Game::toAddon, and CSpecialProtocol::TranslatePath().
OpenStandalone()
bool CGameClient::OpenStandalone (RETRO::IStreamManager & streamManager, IGameInputCallback * input)
References CloseFile(), KODI::GAME::CGameClientStreams::Deinitialize(), KODI_ADDON_INSTANCE_STRUCT::game, GAME_ERROR_FAILED, GAME_ERROR_NO_ERROR, ADDON::CAddon::ID(), KODI::GAME::CGameClientStreams::Initialize(), ADDON::CAddonDll::Initialized(), InitializeGameplay(), CLog::Log(), LOGDEBUG, LogError(), LogException(), m_critSection, KODI::GAME::CGameClientStruct::m_ifc, NotifyError(), Streams(), and AddonInstance_Game::toAddon.
ParseLibretroName()
std::pair< std::string, std::string > CGameClient::ParseLibretroName (const std::string & addonName) static private
Parse the name of a libretro game add-on into its emulator name and platforms.
Parameters
addonName The name of the add-on, e.g. "Nintendo - SNES / SFC (Snes9x 2002)"
Returns
A tuple of two strings:
first: the emulator name, e.g. "Snes9x 2002"
second: the platforms, e.g. "Nintendo - SNES / SFC"
For cores that don't emulate a platform, such as 2048 with the add-on name "2048", then the emulator name will be the add-on name and platforms will be empty, e.g.:
first: "2048"
second: ""
Referenced by CGameClient().
RequiresGameLoop()
bool KODI::GAME::CGameClient::RequiresGameLoop () const inline
References m_bRequiresGameLoop.
Reset()
void CGameClient::Reset ()
References KODI_ADDON_INSTANCE_STRUCT::game, LogError(), LogException(), m_bIsPlaying, m_critSection, KODI::GAME::CGameClientStruct::m_ifc, and AddonInstance_Game::toAddon.
Referenced by KODI::GAME::CGameClientHardware::OnResetButton().
RunFrame()
void CGameClient::RunFrame ()
References KODI_ADDON_INSTANCE_STRUCT::game, LogError(), LogException(), m_bIsPlaying, m_critSection, KODI::GAME::CGameClientStruct::m_ifc, m_input, and AddonInstance_Game::toAddon.
Referenced by KODI::RETRO::CReversiblePlayback::FrameEvent(), and KODI::RETRO::CReversiblePlayback::RewindEvent().
Serialize()
bool CGameClient::Serialize (uint8_t * data, size_t size)
References data(), KODI_ADDON_INSTANCE_STRUCT::game, LogError(), LogException(), m_bIsPlaying, m_critSection, KODI::GAME::CGameClientStruct::m_ifc, and AddonInstance_Game::toAddon.
Referenced by KODI::RETRO::CReversiblePlayback::AddFrame(), and KODI::RETRO::CReversiblePlayback::CommitSavestate().
SerializeSize()
size_t KODI::GAME::CGameClient::SerializeSize () const inline
References m_serializeSize.
Referenced by KODI::RETRO::CReversiblePlayback::CommitSavestate(), KODI::RETRO::CReversiblePlayback::CreateSavestate(), KODI::RETRO::CReversiblePlayback::LoadSavestate(), and KODI::RETRO::CReversiblePlayback::UpdateMemoryStream().
Streams() [1/2]
CGameClientStreams & KODI::GAME::CGameClient::Streams () inline
References m_subsystems, and KODI::GAME::GameClientSubsystems::Streams.
Streams() [2/2]
const CGameClientStreams & KODI::GAME::CGameClient::Streams () const inline
References m_subsystems, and KODI::GAME::GameClientSubsystems::Streams.
Referenced by cb_close_stream(), cb_open_stream(), CloseFile(), OpenFile(), OpenStandalone(), and KODI::GAME::CGameClientSubsystem::Streams().
SupportsAllExtensions()
bool KODI::GAME::CGameClient::SupportsAllExtensions () const inline
References m_bSupportsAllExtensions.
Referenced by IsExtensionValid().
SupportsPath()
bool CGameClient::SupportsPath () const
References m_bSupportsAllExtensions, and m_extensions.
SupportsStandalone()
bool KODI::GAME::CGameClient::SupportsStandalone () const inline
References m_bSupportsStandalone.
SupportsVFS()
bool KODI::GAME::CGameClient::SupportsVFS () const inline
References m_bSupportsVFS.
Referenced by KODI::GAME::CGameClientProperties::InitializeProperties().
Unload()
void CGameClient::Unload ()
References KODI::GAME::CGameClientInput::Deinitialize(), ADDON::CAddonDll::DestroyInstance(), Input(), and KODI::GAME::CGameClientStruct::m_ifc.
Member Data Documentation
m_bIsPlaying
std::atomic_bool KODI::GAME::CGameClient::m_bIsPlaying private
Referenced by CloseFile(), Deserialize(), InitializeGameplay(), IsPlaying(), Reset(), RunFrame(), and Serialize().
m_bRequiresGameLoop
bool KODI::GAME::CGameClient::m_bRequiresGameLoop = false private
Referenced by LoadGameInfo(), and RequiresGameLoop().
m_bSupportsAllExtensions
bool KODI::GAME::CGameClient::m_bSupportsAllExtensions = false private
Referenced by CGameClient(), SupportsAllExtensions(), and SupportsPath().
m_bSupportsStandalone
bool KODI::GAME::CGameClient::m_bSupportsStandalone private
Referenced by CGameClient(), LogAddonProperties(), and SupportsStandalone().
m_bSupportsVFS
bool KODI::GAME::CGameClient::m_bSupportsVFS private
Referenced by CGameClient(), LogAddonProperties(), OpenFile(), and SupportsVFS().
m_critSection
CCriticalSection KODI::GAME::CGameClient::m_critSection private
Referenced by CloseFile(), Deserialize(), OpenFile(), OpenStandalone(), Reset(), RunFrame(), and Serialize().
m_emulatorName
std::string KODI::GAME::CGameClient::m_emulatorName private
Referenced by CGameClient(), and GetEmulatorName().
m_extensions
std::set<std::string> KODI::GAME::CGameClient::m_extensions private
Referenced by CGameClient(), GetExtensions(), IsExtensionValid(), LogAddonProperties(), and SupportsPath().
m_framerate
double KODI::GAME::CGameClient::m_framerate = 0.0 private
Referenced by GetFrameRate(), and LoadGameInfo().
m_gamePath
std::string KODI::GAME::CGameClient::m_gamePath private
Referenced by CloseFile(), GetGamePath(), and InitializeGameplay().
m_inGameSaves
std::unique_ptr<CGameClientInGameSaves> KODI::GAME::CGameClient::m_inGameSaves private
Referenced by CloseFile(), and InitializeGameplay().
m_input
IGameInputCallback* KODI::GAME::CGameClient::m_input = nullptr private
Referenced by CloseFile(), InitializeGameplay(), and RunFrame().
m_platforms
std::string KODI::GAME::CGameClient::m_platforms private
Referenced by CGameClient(), and GetPlatforms().
m_region
GAME_REGION KODI::GAME::CGameClient::m_region = GAME_REGION_UNKNOWN private
Referenced by LoadGameInfo().
m_samplerate
double KODI::GAME::CGameClient::m_samplerate = 0.0 private
Referenced by GetSampleRate(), and LoadGameInfo().
m_serializeSize
size_t KODI::GAME::CGameClient::m_serializeSize = 0 private
Referenced by CloseFile(), GetSerializeSize(), LoadGameInfo(), and SerializeSize().
m_subsystems
GameClientSubsystems KODI::GAME::CGameClient::m_subsystems private
Referenced by AddonProperties(), AddonProperties(), Cheevos(), Cheevos(), Input(), Input(), Streams(), Streams(), and ~CGameClient().
The documentation for this class was generated from the following files:
GameClient.h
GameClient.cpp