Kodi Documentation: PVR::CPVRClientMenuHooks Class Reference
PVR::CPVRClientMenuHooks Class Reference
#include <PVRClientMenuHooks.h>
Public Member Functions
CPVRClientMenuHooks ()=default
virtual ~CPVRClientMenuHooks ()=default
CPVRClientMenuHooks (const std::string &addonId)
void AddHook (const PVR_MENUHOOK &addonHook)
void Clear ()
std::vector< CPVRClientMenuHook > GetChannelHooks () const
std::vector< CPVRClientMenuHook > GetTimerHooks () const
std::vector< CPVRClientMenuHook > GetEpgHooks () const
std::vector< CPVRClientMenuHook > GetRecordingHooks () const
std::vector< CPVRClientMenuHook > GetDeletedRecordingHooks () const
std::vector< CPVRClientMenuHook > GetSettingsHooks () const
Private Member Functions
std::vector< CPVRClientMenuHook > GetHooks (const std::function< bool(const CPVRClientMenuHook &hook)> &function) const
Private Attributes
std::string m_addonId
std::unique_ptr< std::vector< CPVRClientMenuHook > > m_hooks
Constructor & Destructor Documentation
CPVRClientMenuHooks() [1/2]
PVR::CPVRClientMenuHooks::CPVRClientMenuHooks () default
~CPVRClientMenuHooks()
virtual PVR::CPVRClientMenuHooks::~CPVRClientMenuHooks () virtual default
CPVRClientMenuHooks() [2/2]
PVR::CPVRClientMenuHooks::CPVRClientMenuHooks (const std::string & addonId) inline explicit
Member Function Documentation
AddHook()
void PVR::CPVRClientMenuHooks::AddHook (const PVR_MENUHOOK & addonHook)
References PVR::CPVRContextMenuManager::AddMenuHook(), PVR::CPVRContextMenuManager::GetInstance(), m_addonId, and m_hooks.
Clear()
void PVR::CPVRClientMenuHooks::Clear ()
References PVR::CPVRContextMenuManager::GetInstance(), m_hooks, and PVR::CPVRContextMenuManager::RemoveMenuHook().
GetChannelHooks()
std::vector< CPVRClientMenuHook > PVR::CPVRClientMenuHooks::GetChannelHooks () const
References GetHooks(), and PVR::CPVRClientMenuHook::IsChannelHook().
GetDeletedRecordingHooks()
std::vector< CPVRClientMenuHook > PVR::CPVRClientMenuHooks::GetDeletedRecordingHooks () const
References GetHooks(), and PVR::CPVRClientMenuHook::IsDeletedRecordingHook().
GetEpgHooks()
std::vector< CPVRClientMenuHook > PVR::CPVRClientMenuHooks::GetEpgHooks () const
References GetHooks(), and PVR::CPVRClientMenuHook::IsEpgHook().
GetHooks()
std::vector< CPVRClientMenuHook > PVR::CPVRClientMenuHooks::GetHooks (const std::function< bool(const CPVRClientMenuHook &hook)> & function) const private
References PVR::CPVRClientMenuHook::IsAllHook(), and m_hooks.
Referenced by GetChannelHooks(), GetDeletedRecordingHooks(), GetEpgHooks(), GetRecordingHooks(), GetSettingsHooks(), and GetTimerHooks().
GetRecordingHooks()
std::vector< CPVRClientMenuHook > PVR::CPVRClientMenuHooks::GetRecordingHooks () const
References GetHooks(), and PVR::CPVRClientMenuHook::IsRecordingHook().
GetSettingsHooks()
std::vector< CPVRClientMenuHook > PVR::CPVRClientMenuHooks::GetSettingsHooks () const
References GetHooks(), and PVR::CPVRClientMenuHook::IsSettingsHook().
GetTimerHooks()
std::vector< CPVRClientMenuHook > PVR::CPVRClientMenuHooks::GetTimerHooks () const
References GetHooks(), and PVR::CPVRClientMenuHook::IsTimerHook().
Member Data Documentation
m_addonId
std::string PVR::CPVRClientMenuHooks::m_addonId private
Referenced by AddHook().
m_hooks
std::unique_ptr<std::vector<CPVRClientMenuHook> > PVR::CPVRClientMenuHooks::m_hooks private
Referenced by AddHook(), Clear(), and GetHooks().
The documentation for this class was generated from the following files:
PVRClientMenuHooks.h
PVRClientMenuHooks.cpp