Kodi Documentation: KODI::PLAYLIST::CPlayListXML Class Reference
KODI::PLAYLIST::CPlayListXML Class Reference
#include <PlayListXML.h>
Public Member Functions
CPlayListXML (void)
~CPlayListXML (void) override
bool Load (const std::string &strFileName) override
void Save (const std::string &strFileName) const override
Public Member Functions inherited from KODI::PLAYLIST::CPlayList
CPlayList (Id id=Id::TYPE_NONE)
virtual ~CPlayList (void)=default
virtual bool LoadData (std::istream &stream)
virtual bool LoadData (const std::string &strData)
void Add (const CPlayList &playlist)
void Add (const std::shared_ptr< CFileItem > &pItem)
void Add (const CFileItemList &items)
void Insert (const CPlayList &playlist, int iPosition=-1)
void Insert (const CFileItemList &items, int iPosition=-1)
void Insert (const std::shared_ptr< CFileItem > &item, int iPosition=-1)
int FindOrder (int iOrder) const
const std::string & GetName () const
void Remove (const std::string &strFileName)
void Remove (int position)
bool Swap (int position1, int position2)
bool Expand (int position)
void Clear ()
int size () const
int RemoveDVDItems ()
const std::shared_ptr< CFileItem > operator[] (int iItem) const
std::shared_ptr< CFileItem > operator[] (int iItem)
void Shuffle (int iPosition=0)
void UnShuffle ()
bool IsShuffled () const
void SetPlayed (bool bPlayed)
bool WasPlayed () const
void SetUnPlayable (int iItem)
int GetPlayable () const
void UpdateItem (const CFileItem *item)
const std::string & ResolveURL (const std::shared_ptr< CFileItem > &item) const
Additional Inherited Members
Protected Types inherited from KODI::PLAYLIST::CPlayList
typedef std::vector< std::shared_ptr< CFileItem > >::iterator ivecItems
Protected Attributes inherited from KODI::PLAYLIST::CPlayList
Id m_id
std::string m_strPlayListName
std::string m_strBasePath
int m_iPlayableItems
bool m_bShuffled
bool m_bWasPlayed
std::vector< std::shared_ptr< CFileItem > > m_vecItems
Constructor & Destructor Documentation
CPlayListXML()
KODI::PLAYLIST::CPlayListXML::CPlayListXML (void) default
~CPlayListXML()
KODI::PLAYLIST::CPlayListXML::~CPlayListXML (void) override default
Member Function Documentation
Load()
bool KODI::PLAYLIST::CPlayListXML::Load (const std::string & strFileName) override virtual
Reimplemented from KODI::PLAYLIST::CPlayList.
References KODI::PLAYLIST::CPlayList::Add(), KODI::PLAYLIST::CPlayList::Clear(), URIUtils::GetFileName(), URIUtils::GetParentPath(), KODI::PLAYLIST::GetString(), CXBMCTinyXML2::LoadFile(), LOCK_MODE_NUMERIC, LOCK_STATE_LOCKED, CLog::Log(), LOGERROR, KODI::PLAYLIST::CPlayList::m_strBasePath, KODI::PLAYLIST::CPlayList::m_strPlayListName, and name.
Save()
void KODI::PLAYLIST::CPlayListXML::Save (const std::string & strFileName) const override virtual
Reimplemented from KODI::PLAYLIST::CPlayList.
References LOCK_STATE_NO_LOCK, CLog::Log(), LOGERROR, KODI::PLAYLIST::CPlayList::m_vecItems, and CUtil::MakeLegalPath().
The documentation for this class was generated from the following files:
PlayListXML.h
PlayListXML.cpp