Kodi Documentation: CSysInfoJob Class Reference
CSysInfoJob Class Reference
#include <SystemInfo.h>
Public Member Functions
CSysInfoJob ()
bool DoWork () override
Main workhorse function of CJob instances.
const CSysData & GetData () const
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
virtual const char * GetType () const
Function that returns the type of job.
virtual bool operator== (const CJob *job) const
virtual bool ShouldCancel (unsigned int progress, unsigned int total) const
Function for longer jobs to report progress and check whether they have been cancelled.
Static Public Member Functions
static CSysData::INTERNET_STATE GetInternetState ()
Static Private Member Functions
static bool SystemUpTime (int iInputMinutes, int &iMinutes, int &iHours, int &iDays)
static std::string GetSystemUpTime (bool bTotalUptime)
static std::string GetMACAddress ()
static std::string GetIPAddress ()
static std::string GetNetMask ()
static std::string GetGatewayAddress ()
static std::string GetNetworkLinkState ()
static std::string GetVideoEncoder ()
static std::string GetBatteryLevel ()
static std::vector< std::string > GetDNSServers ()
Private Attributes
CSysData m_info
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Constructor & Destructor Documentation
CSysInfoJob()
CSysInfoJob::CSysInfoJob () default
Member Function Documentation
DoWork()
bool CSysInfoJob::DoWork () override virtual
Main workhorse function of CJob instances.
All CJob subclasses must implement this function, performing all processing. Once this function is complete, the OnJobComplete() callback is called, and the job is then destroyed.
See also
CJobManager, IJobCallback::OnJobComplete()
Implements CJob.
References CSysData::batteryLevel, CSysData::cpuFrequency, CSysData::dnsServers, CSysData::gatewayAddress, GetBatteryLevel(), CServiceBroker::GetCPUInfo(), GetDNSServers(), GetGatewayAddress(), GetInternetState(), GetIPAddress(), CSysInfo::GetKernelName(), CSysInfo::GetKernelVersionFull(), GetMACAddress(), GetNetMask(), GetNetworkLinkState(), CSysInfo::GetOsPrettyNameWithVersion(), GetSystemUpTime(), GetVideoEncoder(), CSysData::internetState, CSysData::ipAddress, m_info, CSysData::macAddress, CSysData::netMask, CSysData::networkLinkState, CSysData::osVersionInfo, CSysData::systemTotalUptime, CSysData::systemUptime, and CSysData::videoEncoder.
GetBatteryLevel()
std::string CSysInfoJob::GetBatteryLevel () static private
References CServiceBroker::GetPowerManager().
Referenced by DoWork().
GetData()
const CSysData & CSysInfoJob::GetData () const
References m_info.
GetDNSServers()
std::vector< std::string > CSysInfoJob::GetDNSServers () static private
References CNetworkBase::GetNameServers(), and CServiceBroker::GetNetwork().
Referenced by DoWork().
GetGatewayAddress()
std::string CSysInfoJob::GetGatewayAddress () static private
References CNetworkInterface::GetCurrentDefaultGateway(), CNetworkBase::GetFirstConnectedInterface(), and CServiceBroker::GetNetwork().
Referenced by DoWork().
GetInternetState()
CSysData::INTERNET_STATE CSysInfoJob::GetInternetState () static
References CSysData::CONNECTED, CSysData::DISCONNECTED, and XFILE::CCurlFile::IsInternet().
Referenced by DoWork(), and CSysInfo::HasInternet().
GetIPAddress()
std::string CSysInfoJob::GetIPAddress () static private
References CNetworkInterface::GetCurrentIPAddress(), CNetworkBase::GetFirstConnectedInterface(), and CServiceBroker::GetNetwork().
Referenced by DoWork().
GetMACAddress()
std::string CSysInfoJob::GetMACAddress () static private
References g_localizeStrings, CLocalizeStrings::Get(), CNetworkBase::GetFirstConnectedInterface(), CNetworkInterface::GetMacAddress(), and CServiceBroker::GetNetwork().
Referenced by DoWork().
GetNetMask()
std::string CSysInfoJob::GetNetMask () static private
References CNetworkInterface::GetCurrentNetmask(), CNetworkBase::GetFirstConnectedInterface(), and CServiceBroker::GetNetwork().
Referenced by DoWork().
GetNetworkLinkState()
std::string CSysInfoJob::GetNetworkLinkState () static private
References g_localizeStrings, CLocalizeStrings::Get(), CNetworkBase::GetFirstConnectedInterface(), CServiceBroker::GetNetwork(), and CNetworkInterface::IsConnected().
Referenced by DoWork().
GetSystemUpTime()
std::string CSysInfoJob::GetSystemUpTime (bool bTotalUptime) static private
References g_localizeStrings, g_sysinfo, CLocalizeStrings::Get(), CSysInfo::GetTotalUptime(), and SystemUpTime().
Referenced by DoWork().
GetVideoEncoder()
std::string CSysInfoJob::GetVideoEncoder () static private
References CRenderSystemBase::GetRenderRenderer(), and CServiceBroker::GetRenderSystem().
Referenced by DoWork().
SystemUpTime()
bool CSysInfoJob::SystemUpTime (int iInputMinutes, int & iMinutes, int & iHours, int & iDays) static private
Referenced by GetSystemUpTime().
Member Data Documentation
m_info
CSysData CSysInfoJob::m_info private
Referenced by DoWork(), and GetData().
The documentation for this class was generated from the following files:
SystemInfo.h
SystemInfo.cpp