Kodi Documentation: PVR::CPVRContextMenuManager Class Reference
PVR::CPVRContextMenuManager Class Reference
#include <PVRContextMenus.h>
Public Member Functions
const std::vector< std::shared_ptr< IContextMenuItem > > & GetMenuItems () const
void AddMenuHook (const CPVRClientMenuHook &hook)
void RemoveMenuHook (const CPVRClientMenuHook &hook)
CEventStream< PVRContextMenuEvent > & Events ()
Query the events available for CEventStream.
Static Public Member Functions
static CPVRContextMenuManager & GetInstance ()
Private Member Functions
CPVRContextMenuManager ()
CPVRContextMenuManager (const CPVRContextMenuManager &)=delete
CPVRContextMenuManager const & operator= (CPVRContextMenuManager const &)=delete
virtual ~CPVRContextMenuManager ()=default
Private Attributes
std::vector< std::shared_ptr< IContextMenuItem > > m_items
CEventSource< PVRContextMenuEvent > m_events
Constructor & Destructor Documentation
CPVRContextMenuManager() [1/2]
PVR::CPVRContextMenuManager::CPVRContextMenuManager () private
CPVRContextMenuManager() [2/2]
PVR::CPVRContextMenuManager::CPVRContextMenuManager (const CPVRContextMenuManager &) private delete
~CPVRContextMenuManager()
virtual PVR::CPVRContextMenuManager::~CPVRContextMenuManager () private virtual default
Member Function Documentation
AddMenuHook()
void PVR::CPVRContextMenuManager::AddMenuHook (const CPVRClientMenuHook & hook)
References PVR::ADD_ITEM, PVR::CPVRClientMenuHook::IsSettingsHook(), m_events, and m_items.
Referenced by PVR::CPVRClientMenuHooks::AddHook().
Events()
CEventStream< PVRContextMenuEvent > & PVR::CPVRContextMenuManager::Events () inline
Query the events available for CEventStream.
References m_events.
Referenced by CContextMenuManager::Deinit(), and CContextMenuManager::Init().
GetInstance()
CPVRContextMenuManager & PVR::CPVRContextMenuManager::GetInstance () static
Referenced by PVR::CPVRClientMenuHooks::AddHook(), PVR::CPVRClientMenuHooks::Clear(), CContextMenuManager::Deinit(), and CContextMenuManager::Init().
GetMenuItems()
const std::vector< std::shared_ptr< IContextMenuItem > > & PVR::CPVRContextMenuManager::GetMenuItems () const inline
References m_items.
operator=()
CPVRContextMenuManager const & PVR::CPVRContextMenuManager::operator= (CPVRContextMenuManager const &) private delete
RemoveMenuHook()
void PVR::CPVRContextMenuManager::RemoveMenuHook (const CPVRClientMenuHook & hook)
References PVR::CONTEXTMENUITEM::PVRClientMenuHook::GetHook(), PVR::CPVRClientMenuHook::IsSettingsHook(), m_events, m_items, and PVR::REMOVE_ITEM.
Referenced by PVR::CPVRClientMenuHooks::Clear().
Member Data Documentation
m_events
CEventSource<PVRContextMenuEvent> PVR::CPVRContextMenuManager::m_events private
Referenced by AddMenuHook(), Events(), and RemoveMenuHook().
m_items
std::vector<std::shared_ptr<IContextMenuItem> > PVR::CPVRContextMenuManager::m_items private
Referenced by AddMenuHook(), GetMenuItems(), and RemoveMenuHook().
The documentation for this class was generated from the following files:
PVRContextMenus.h
PVRContextMenus.cpp