Kodi Documentation: VDPAU::CDecoder Class Reference
VDPAU::CDecoder Class Reference
#include <VDPAU.h>
Classes
struct Desc
Public Member Functions
CDecoder (CProcessInfo &processInfo)
~CDecoder () override
bool Open (AVCodecContext *avctx, AVCodecContext *mainctx, const enum AVPixelFormat) override
CDVDVideoCodec::VCReturn Decode (AVCodecContext *avctx, AVFrame *frame) override
bool GetPicture (AVCodecContext *avctx, VideoPicture *picture) override
void Reset () override
virtual void Close ()
long Release () override
bool CanSkipDeint () override
unsigned GetAllowedReferences () override
CDVDVideoCodec::VCReturn Check (AVCodecContext *avctx) override
const std::string Name () override
void SetCodecControl (int flags) override
bool Supports (VdpVideoMixerFeature feature)
void OnLostDisplay () override
void OnResetDisplay () override
Public Member Functions inherited from IHardwareDecoder
IHardwareDecoder ()=default
~IHardwareDecoder () override=default
Public Member Functions inherited from IDVDResourceCounted< IHardwareDecoder >
IDVDResourceCounted ()
IDVDResourceCounted (const IDVDResourceCounted &)=delete
virtual ~IDVDResourceCounted ()=default
IDVDResourceCounted & operator= (const IDVDResourceCounted &)=delete
virtual IHardwareDecoder * Acquire ()
Public Member Functions inherited from IDispResource
virtual ~IDispResource ()=default
virtual void OnAppFocusChange (bool focus)
Static Public Member Functions
static bool IsVDPAUFormat (AVPixelFormat fmt)
static void FFReleaseBuffer (void *opaque, uint8_t *data)
static int FFGetBuffer (AVCodecContext *avctx, AVFrame *pic, int flags)
static int Render (struct AVCodecContext *s, struct AVFrame *src, const VdpPictureInfo *info, uint32_t buffers_used, const VdpBitstreamBuffer *buffers)
static IHardwareDecoder * Create (CDVDStreamInfo &hint, CProcessInfo &processInfo, AVPixelFormat fmt)
static void Register ()
Protected Types
enum EDisplayState { VDPAU_OPEN , VDPAU_RESET , VDPAU_LOST , VDPAU_ERROR }
Protected Member Functions
void SetWidthHeight (int width, int height)
bool ConfigVDPAU (AVCodecContext *avctx, int ref_frames)
bool CheckStatus (VdpStatus vdp_st, int line)
void FiniVDPAUOutput ()
void ReturnRenderPicture (CVdpauRenderPicture *renderPic)
long ReleasePicReference ()
Static Protected Member Functions
static void ReadFormatOf (AVCodecID codec, VdpDecoderProfile &decoder_profile, VdpChromaType &chroma_type)
Protected Attributes
enum VDPAU::CDecoder::EDisplayState m_DisplayState
CCriticalSection m_DecoderSection
CEvent m_DisplayEvent
int m_ErrorCount
bool m_vdpauConfigured
CVdpauConfig m_vdpauConfig
CVideoSurfaces m_videoSurfaces
AVVDPAUContext m_hwContext
COutput m_vdpauOutput
CVdpauBufferStats m_bufferStats
CEvent m_inMsgEvent
CVdpauRenderPicture * m_presentPicture = nullptr
int m_codecControl
CProcessInfo & m_processInfo
Static Protected Attributes
static bool m_capGeneral = false
Friends
class CVdpauBufferPool
Additional Inherited Members
Public Attributes inherited from IDVDResourceCounted< IHardwareDecoder >
std::atomic< long > m_refs
Detailed Description
VDPAU main class
Member Enumeration Documentation
EDisplayState
enum VDPAU::CDecoder::EDisplayState protected
Enumerator
VDPAU_OPEN
VDPAU_RESET
VDPAU_LOST
VDPAU_ERROR
Constructor & Destructor Documentation
CDecoder()
CDecoder::CDecoder (CProcessInfo & processInfo) explicit
References VDPAU::CVdpauConfig::context, m_DisplayState, m_processInfo, m_vdpauConfig, m_vdpauConfigured, m_videoSurfaces, VDPAU::CVdpauConfig::processInfo, VDPAU::CVdpauConfig::resetCounter, VDPAU_OPEN, and VDPAU::CVdpauConfig::videoSurfaces.
~CDecoder()
CDecoder::~CDecoder () override
References Close().
Member Function Documentation
CanSkipDeint()
bool CDecoder::CanSkipDeint () override virtual
Reimplemented from IHardwareDecoder.
References VDPAU::CVdpauBufferStats::CanSkipDeint(), and m_bufferStats.
Check()
CDVDVideoCodec::VCReturn CDecoder::Check (AVCodecContext * avctx) override virtual
Implements IHardwareDecoder.
References VDPAU::CVdpauConfig::context, VDPAU::CVDPAUContext::EnsureContext(), FiniVDPAUOutput(), CLog::Log(), LOGERROR, LOGINFO, m_DecoderSection, m_DisplayEvent, m_DisplayState, m_vdpauConfig, m_vdpauConfigured, VDPAU::CVDPAUContext::Release(), CDVDVideoCodec::VC_ERROR, CDVDVideoCodec::VC_FLUSHED, CDVDVideoCodec::VC_NONE, VDPAU_ERROR, VDPAU_LOST, VDPAU_OPEN, VDPAU_RESET, and CEvent::Wait().
Referenced by Decode().
CheckStatus()
bool CDecoder::CheckStatus (VdpStatus vdp_st, int line) protected
References VDPAU::CVdpauConfig::context, VDPAU::CVDPAUContext::GetProcs(), CLog::Log(), LOGERROR, m_DisplayEvent, m_DisplayState, m_ErrorCount, m_vdpauConfig, CEvent::Reset(), VDPAU::VDPAU_procs::vdp_get_error_string, VDPAU_ERROR, VDPAU_LOST, and VDPAU_OPEN.
Referenced by ConfigVDPAU(), FFGetBuffer(), FiniVDPAUOutput(), Open(), and Render().
Close()
void CDecoder::Close () virtual
References VDPAU::CVdpauConfig::context, VDPAU::COutput::Dispose(), FiniVDPAUOutput(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGINFO, m_DecoderSection, m_vdpauConfig, m_vdpauOutput, VDPAU::CVDPAUContext::Release(), and CWinSystemBase::Unregister().
Referenced by ~CDecoder().
ConfigVDPAU()
bool CDecoder::ConfigVDPAU (AVCodecContext * avctx, int ref_frames) protected
References VDPAU::COutputControlProtocol::ACC, CheckStatus(), VDPAU::CVdpauConfig::context, VDPAU::COutput::Dispose(), FiniVDPAUOutput(), VDPAU::CVDPAUContext::GetDevice(), VDPAU::CVDPAUContext::GetProcs(), CServiceBroker::GetWinSystem(), VDPAU::COutputControlProtocol::INIT, CLog::Log(), LOGERROR, LOGINFO, m_bufferStats, VDPAU::COutput::m_controlPort, m_ErrorCount, m_inMsgEvent, m_vdpauConfig, m_vdpauConfigured, m_vdpauOutput, VDPAU::CVdpauConfig::maxReferences, VDPAU::CVdpauConfig::outHeight, VDPAU::CVdpauConfig::outWidth, ReadFormatOf(), Actor::Message::Release(), VDPAU::CVdpauBufferStats::Reset(), CEvent::Reset(), VDPAU::CVdpauConfig::resetCounter, Actor::Protocol::SendOutMessageSync(), SetWidthHeight(), Actor::Message::signal, VDPAU::COutput::Start(), VDPAU::CVdpauConfig::stats, success, VDPAU::CVdpauConfig::surfaceHeight, VDPAU::CVdpauConfig::surfaceWidth, VDPAU::VDPAU_procs::vdp_decoder_create, VDPAU::CVdpauConfig::vdpau, VDPAU::CVdpauConfig::vdpChromaType, VDPAU::CVdpauConfig::vdpDecoder, VDPAU::CVdpauConfig::vidHeight, and VDPAU::CVdpauConfig::vidWidth.
Referenced by Render().
Create()
IHardwareDecoder * CDecoder::Create (CDVDStreamInfo & hint, CProcessInfo & processInfo, AVPixelFormat fmt) static
References CServiceBroker::GetSettingsComponent(), IsVDPAUFormat(), and CSettings::SETTING_VIDEOPLAYER_USEVDPAU.
Referenced by Register().
Decode()
CDVDVideoCodec::VCReturn CDecoder::Decode (AVCodecContext * avctx, AVFrame * frame) override virtual
Implements IHardwareDecoder.
References Check(), VideoPicture::color_space, CurrentHostCounter(), Actor::Message::data, VDPAU::CVdpauBufferStats::DecRender(), DVD_CODEC_CTRL_DRAIN, DVD_CODEC_CTRL_HURRY, DVD_CODEC_CTRL_NO_POSTPROC, VDPAU::CVdpauDecodedPicture::DVDPic, VDPAU::COutputControlProtocol::ERROR, VDPAU::CVdpauBufferStats::Get(), VideoPicture::iFlags, VDPAU::CVdpauBufferStats::IncDecoded(), VDPAU::CVideoSurfaces::IsValid(), CLog::Log(), LOGERROR, LOGWARNING, m_bufferStats, m_codecControl, VDPAU::COutput::m_controlPort, VDPAU::COutput::m_dataPort, m_DecoderSection, m_DisplayState, m_inMsgEvent, m_presentPicture, m_vdpauConfigured, m_vdpauOutput, m_videoSurfaces, VDPAU::CVideoSurfaces::MarkRender(), VDPAU::COutputDataProtocol::NEWFRAME, VDPAU::COutputDataProtocol::PICTURE, Actor::Protocol::ReceiveInMessage(), CVideoBuffer::Release(), Actor::Message::Release(), Actor::Protocol::SendOutMessage(), VDPAU::CVdpauBufferStats::SetParams(), Actor::Message::signal, VDPAU::COutputControlProtocol::STATS, CDVDVideoCodec::VC_BUFFER, CDVDVideoCodec::VC_EOF, CDVDVideoCodec::VC_ERROR, CDVDVideoCodec::VC_NONE, CDVDVideoCodec::VC_PICTURE, VDPAU_ERROR, VDPAU::CVdpauDecodedPicture::videoSurface, and CEvent::Wait().
FFGetBuffer()
int CDecoder::FFGetBuffer (AVCodecContext * avctx, AVFrame * pic, int flags) static
References VDPAU::CVideoSurfaces::AddSurface(), CheckStatus(), VDPAU::CVdpauConfig::context, FFReleaseBuffer(), VDPAU::CVDPAUContext::GetDevice(), VDPAU::CVideoSurfaces::GetFree(), ICallbackHWAccel::GetHWAccel(), VDPAU::CVDPAUContext::GetProcs(), CLog::Log(), LOGERROR, LOGWARNING, m_DecoderSection, m_DisplayState, m_vdpauConfig, m_videoSurfaces, ReadFormatOf(), VDPAU::VDPAU_procs::vdp_video_surface_create, VDPAU_OPEN, and VDPAU::CVdpauConfig::vdpChromaType.
Referenced by Open().
FFReleaseBuffer()
void CDecoder::FFReleaseBuffer (void * opaque, uint8_t * data) static
References VDPAU::CVideoSurfaces::ClearReference(), data(), m_DecoderSection, and m_videoSurfaces.
Referenced by FFGetBuffer().
FiniVDPAUOutput()
void CDecoder::FiniVDPAUOutput () protected
References CheckStatus(), VDPAU::CVdpauConfig::context, VDPAU::COutput::Dispose(), VDPAU::CVDPAUContext::GetProcs(), CLog::Log(), LOGDEBUG, LOGINFO, LOGVIDEO, m_vdpauConfig, m_vdpauConfigured, m_vdpauOutput, m_videoSurfaces, VDPAU::CVideoSurfaces::RemoveNext(), VDPAU::CVideoSurfaces::Reset(), VDPAU::CVideoSurfaces::Size(), VDPAU::VDPAU_procs::vdp_decoder_destroy, VDPAU::VDPAU_procs::vdp_video_surface_destroy, and VDPAU::CVdpauConfig::vdpDecoder.
Referenced by Check(), Close(), ConfigVDPAU(), and OnLostDisplay().
GetAllowedReferences()
unsigned VDPAU::CDecoder::GetAllowedReferences () inline override virtual
Reimplemented from IHardwareDecoder.
GetPicture()
bool CDecoder::GetPicture (AVCodecContext * avctx, VideoPicture * picture) override virtual
Implements IHardwareDecoder.
References VDPAU::CVdpauRenderPicture::DVDPic, m_DecoderSection, m_DisplayState, m_presentPicture, CVideoBuffer::Release(), VideoPicture::SetParams(), VDPAU_OPEN, and VideoPicture::videoBuffer.
IsVDPAUFormat()
bool CDecoder::IsVDPAUFormat (AVPixelFormat fmt) static
Referenced by Create().
Name()
const std::string VDPAU::CDecoder::Name () inline override virtual
Implements IHardwareDecoder.
OnLostDisplay()
void CDecoder::OnLostDisplay () override virtual
Reimplemented from IDispResource.
References VDPAU::CVdpauConfig::context, FiniVDPAUOutput(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGINFO, m_DecoderSection, m_DisplayEvent, m_DisplayState, m_vdpauConfig, VDPAU::CVDPAUContext::Release(), CEvent::Reset(), and VDPAU_LOST.
OnResetDisplay()
void CDecoder::OnResetDisplay () override virtual
Reimplemented from IDispResource.
References CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGINFO, m_DecoderSection, m_DisplayEvent, m_DisplayState, CEvent::Set(), VDPAU_LOST, and VDPAU_RESET.
Open()
bool CDecoder::Open (AVCodecContext * avctx, AVCodecContext * mainctx, const enum AVPixelFormat fmt) override virtual
Implements IHardwareDecoder.
References CheckStatus(), VDPAU::CVdpauConfig::context, CurrentHostCounter(), VDPAU::CVDPAUContext::EnsureContext(), FFGetBuffer(), VDPAU::CVDPAUContext::GetDevice(), VDPAU::CVDPAUContext::GetProcs(), CServiceBroker::GetRenderSystem(), CRenderSystemBase::GetRenderVendor(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), CDVDCodecUtils::IsVP3CompatibleWidth(), CLog::Log(), LOGERROR, LOGINFO, LOGWARNING, m_DisplayState, m_hwContext, m_presentPicture, m_vdpauConfig, m_vdpauConfigured, VDPAU::CVdpauConfig::numRenderBuffers, ReadFormatOf(), CWinSystemBase::Register(), Render(), CSettings::SETTING_VIDEOPLAYER_USEVDPAUMPEG2, CSettings::SETTING_VIDEOPLAYER_USEVDPAUMPEG4, CSettings::SETTING_VIDEOPLAYER_USEVDPAUVC1, VDPAU::CVdpauConfig::timeOpened, VDPAU::VDPAU_procs::vdp_decoder_create, VDPAU::VDPAU_procs::vdp_decoder_destroy, VDPAU::VDPAU_procs::vdp_decoder_query_caps, VDPAU::VDPAU_procs::vdp_get_error_string, VDPAU_OPEN, VDPAU::CVdpauConfig::vdpChromaType, and VDPAU::CVdpauConfig::vdpDecoder.
ReadFormatOf()
void CDecoder::ReadFormatOf (AVCodecID codec, VdpDecoderProfile & decoder_profile, VdpChromaType & chroma_type) static protected
Referenced by ConfigVDPAU(), FFGetBuffer(), and Open().
Register()
void CDecoder::Register () static
References Create(), VDPAU::CVDPAUContext::EnsureContext(), CServiceBroker::GetRenderSystem(), CRenderSystemBase::GetRenderVendor(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGERROR, m_capGeneral, CDVDFactoryCodec::RegisterHWAccel(), VDPAU::CVDPAUContext::Release(), CSettings::SETTING_VIDEOPLAYER_USEVDPAU, CSettings::SETTING_VIDEOPLAYER_USEVDPAUMIXER, CSettings::SETTING_VIDEOPLAYER_USEVDPAUMPEG2, CSettings::SETTING_VIDEOPLAYER_USEVDPAUMPEG4, and CSettings::SETTING_VIDEOPLAYER_USEVDPAUVC1.
Release()
long CDecoder::Release () override virtual
Reimplemented from IDVDResourceCounted< IHardwareDecoder >.
References VDPAU::COutputControlProtocol::ACC, VDPAU::CVdpauConfig::context, VDPAU::CVDPAUContext::GetProcs(), CLog::Log(), LOGERROR, LOGINFO, VDPAU::COutput::m_controlPort, m_DecoderSection, m_DisplayState, m_vdpauConfig, m_vdpauConfigured, m_vdpauOutput, m_videoSurfaces, VDPAU::COutputControlProtocol::PRECLEANUP, IDVDResourceCounted< IHardwareDecoder >::Release(), Actor::Message::Release(), VDPAU::CVideoSurfaces::RemoveNext(), Actor::Protocol::SendOutMessageSync(), Actor::Message::signal, success, VDPAU::VDPAU_procs::vdp_video_surface_destroy, and VDPAU_ERROR.
ReleasePicReference()
long CDecoder::ReleasePicReference () protected
References IDVDResourceCounted< IHardwareDecoder >::Release().
Referenced by VDPAU::CVdpauBufferPool::Return().
Render()
int CDecoder::Render (struct AVCodecContext * s, struct AVFrame * src, const VdpPictureInfo * info, uint32_t buffers_used, const VdpBitstreamBuffer * buffers) static
References CheckStatus(), ConfigVDPAU(), VDPAU::CVdpauConfig::context, CurrentHostCounter(), CurrentHostFrequency(), VDPAU::CVdpauBufferStats::Get(), ICallbackHWAccel::GetHWAccel(), VDPAU::CVDPAUContext::GetProcs(), VDPAU::CVideoSurfaces::IsValid(), CLog::Log(), LOGDEBUG, LOGERROR, LOGVIDEO, LOGWARNING, m_bufferStats, m_DecoderSection, m_DisplayState, m_vdpauConfig, m_vdpauConfigured, m_videoSurfaces, VDPAU::CVdpauConfig::maxReferences, VDPAU::VDPAU_procs::vdp_decoder_render, VDPAU_OPEN, and VDPAU::CVdpauConfig::vdpDecoder.
Referenced by Open().
Reset()
void CDecoder::Reset () override virtual
Reimplemented from IHardwareDecoder.
References VDPAU::COutputControlProtocol::ACC, VDPAU::COutputControlProtocol::FLUSH, CLog::Log(), LOGERROR, m_bufferStats, VDPAU::COutput::m_controlPort, m_DecoderSection, m_DisplayState, m_presentPicture, m_vdpauConfigured, m_vdpauOutput, CVideoBuffer::Release(), Actor::Message::Release(), VDPAU::CVdpauBufferStats::Reset(), Actor::Protocol::SendOutMessageSync(), Actor::Message::signal, success, and VDPAU_ERROR.
ReturnRenderPicture()
void CDecoder::ReturnRenderPicture (CVdpauRenderPicture * renderPic) protected
References VDPAU::COutput::m_dataPort, m_vdpauOutput, VDPAU::COutputDataProtocol::RETURNPIC, and Actor::Protocol::SendOutMessage().
Referenced by VDPAU::CVdpauBufferPool::Return().
SetCodecControl()
void CDecoder::SetCodecControl (int flags) override virtual
Reimplemented from IHardwareDecoder.
References DVD_CODEC_CTRL_DRAIN, DVD_CODEC_CTRL_HURRY, m_bufferStats, m_codecControl, and VDPAU::CVdpauBufferStats::SetDraining().
SetWidthHeight()
void CDecoder::SetWidthHeight (int width, int height) protected
References CWinSystemBase::GetGfxContext(), CGraphicContext::GetHeight(), CServiceBroker::GetSettingsComponent(), CGraphicContext::GetWidth(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, LOGVIDEO, m_vdpauConfig, VDPAU::CVdpauConfig::outHeight, VDPAU::CVdpauConfig::outWidth, MathUtils::round_int(), and VDPAU::CVdpauConfig::upscale.
Referenced by ConfigVDPAU().
Supports()
bool CDecoder::Supports (VdpVideoMixerFeature feature)
References VDPAU::CVdpauConfig::context, m_vdpauConfig, and VDPAU::CVDPAUContext::Supports().
Referenced by VDPAU::CMixer::DisableHQScaling(), VDPAU::CMixer::Init(), VDPAU::CMixer::PostProcOff(), VDPAU::CMixer::SetHWUpscaling(), VDPAU::CMixer::SetNoiseReduction(), and VDPAU::CMixer::SetSharpness().
Friends And Related Symbol Documentation
CVdpauBufferPool
friend class CVdpauBufferPool friend
Member Data Documentation
m_bufferStats
CVdpauBufferStats VDPAU::CDecoder::m_bufferStats protected
Referenced by CanSkipDeint(), ConfigVDPAU(), Decode(), Render(), Reset(), and SetCodecControl().
m_capGeneral
bool CDecoder::m_capGeneral = false static protected
Referenced by Register().
m_codecControl
int VDPAU::CDecoder::m_codecControl protected
Referenced by Decode(), and SetCodecControl().
m_DecoderSection
CCriticalSection VDPAU::CDecoder::m_DecoderSection protected
Referenced by Check(), Close(), Decode(), FFGetBuffer(), FFReleaseBuffer(), GetPicture(), OnLostDisplay(), OnResetDisplay(), Release(), Render(), and Reset().
m_DisplayEvent
CEvent VDPAU::CDecoder::m_DisplayEvent protected
Referenced by Check(), CheckStatus(), OnLostDisplay(), and OnResetDisplay().
m_DisplayState
enum VDPAU::CDecoder::EDisplayState VDPAU::CDecoder::m_DisplayState protected
Referenced by CDecoder(), Check(), CheckStatus(), Decode(), FFGetBuffer(), GetPicture(), OnLostDisplay(), OnResetDisplay(), Open(), Release(), Render(), and Reset().
m_ErrorCount
int VDPAU::CDecoder::m_ErrorCount protected
Referenced by CheckStatus(), and ConfigVDPAU().
m_hwContext
AVVDPAUContext VDPAU::CDecoder::m_hwContext protected
Referenced by Open().
m_inMsgEvent
CEvent VDPAU::CDecoder::m_inMsgEvent protected
Referenced by ConfigVDPAU(), and Decode().
m_presentPicture
CVdpauRenderPicture* VDPAU::CDecoder::m_presentPicture = nullptr protected
Referenced by Decode(), GetPicture(), Open(), and Reset().
m_processInfo
CProcessInfo& VDPAU::CDecoder::m_processInfo protected
Referenced by CDecoder().
m_vdpauConfig
CVdpauConfig VDPAU::CDecoder::m_vdpauConfig protected
Referenced by CDecoder(), Check(), CheckStatus(), Close(), ConfigVDPAU(), FFGetBuffer(), FiniVDPAUOutput(), OnLostDisplay(), Open(), Release(), Render(), SetWidthHeight(), and Supports().
m_vdpauConfigured
bool VDPAU::CDecoder::m_vdpauConfigured protected
Referenced by CDecoder(), Check(), ConfigVDPAU(), Decode(), FiniVDPAUOutput(), Open(), Release(), Render(), and Reset().
m_vdpauOutput
COutput VDPAU::CDecoder::m_vdpauOutput protected
Referenced by Close(), ConfigVDPAU(), Decode(), FiniVDPAUOutput(), Release(), Reset(), and ReturnRenderPicture().
m_videoSurfaces
CVideoSurfaces VDPAU::CDecoder::m_videoSurfaces protected
Referenced by CDecoder(), Decode(), FFGetBuffer(), FFReleaseBuffer(), FiniVDPAUOutput(), Release(), and Render().
The documentation for this class was generated from the following files:
VDPAU.h
VDPAU.cpp