Kodi Documentation: ADDON::CAddonMgr Class Reference
ADDON::CAddonMgr Class Reference
#include <AddonManager.h>
Public Member Functions
bool ReInit ()
bool Init ()
void DeInit ()
CAddonMgr ()
CAddonMgr (const CAddonMgr &)=delete
virtual ~CAddonMgr ()
CEventStream< AddonEvent > & Events ()
CEventStream< AddonEvent > & UnloadEvents ()
IAddonMgrCallback * GetCallbackForType (AddonType type)
bool RegisterAddonMgrCallback (AddonType type, IAddonMgrCallback *cb)
void UnregisterAddonMgrCallback (AddonType type)
bool GetAddon (const std::string &id, AddonPtr &addon, AddonType type, OnlyEnabled onlyEnabled) const
Retrieve a specific addon (of a specific type)
bool GetAddon (const std::string &id, AddonPtr &addon, OnlyEnabled onlyEnabled) const
Retrieve a specific addon (of no specific type)
bool HasType (const std::string &id, AddonType type)
bool HasAddons (AddonType type)
bool HasInstalledAddons (AddonType type)
bool GetAddonsForUpdate (VECADDONS &addons) const
bool GetAddons (VECADDONS &addons) const
bool GetAddons (VECADDONS &addons, AddonType type)
bool GetInstalledAddons (VECADDONS &addons)
bool GetInstalledAddons (VECADDONS &addons, AddonType type)
bool GetDisabledAddons (VECADDONS &addons)
bool GetDisabledAddons (VECADDONS &addons, AddonType type)
bool GetInstallableAddons (VECADDONS &addons)
bool GetInstallableAddons (VECADDONS &addons, AddonType type)
bool FindInstallableById (const std::string &addonId, AddonPtr &addon)
Get the installable addon depending on install rules or fall back to highest version.
void AddToUpdateableAddons (AddonPtr &pAddon)
void RemoveFromUpdateableAddons (AddonPtr &pAddon)
bool ReloadSettings (const std::string &addonId, AddonInstanceId instanceId)
std::vector< std::shared_ptr< IAddon > > GetAvailableUpdates () const
std::vector< std::shared_ptr< IAddon > > GetOutdatedAddons () const
bool HasAvailableUpdates ()
bool IsOrphaned (const std::shared_ptr< IAddon > &addon, const std::vector< std::shared_ptr< IAddon > > &allAddons) const
Checks if the passed in addon is an orphaned dependency.
bool FindAddons ()
Checks for new / updated add-ons.
bool FindAddon (const std::string &addonId, const std::string &origin, const CAddonVersion &addonVersion)
Checks whether given addon with given origin/version is installed.
bool GetIncompatibleEnabledAddonInfos (std::vector< AddonInfoPtr > &incompatible) const
Fills the the provided vector with the list of incompatible enabled addons and returns if there's any.
std::vector< AddonInfoPtr > MigrateAddons ()
std::vector< AddonInfoPtr > DisableIncompatibleAddons (const std::vector< AddonInfoPtr > &incompatible)
Try to disable addons in the given list.
void CheckAndInstallAddonUpdates (bool wait) const
bool UnloadAddon (const std::string &addonId)
bool LoadAddon (const std::string &addonId, const std::string &origin, const CAddonVersion &addonVersion)
void OnPostUnInstall (const std::string &id)
bool DisableAddon (const std::string &ID, AddonDisabledReason disabledReason)
Disable an addon. Returns true on success, false on failure.
bool UpdateDisabledReason (const std::string &id, AddonDisabledReason newDisabledReason)
Updates reason for a disabled addon. Returns true on success, false on failure.
bool EnableAddon (const std::string &ID)
Enable an addon. Returns true on success, false on failure.
bool IsAddonDisabled (const std::string &ID) const
bool IsAddonDisabledExcept (const std::string &ID, AddonDisabledReason disabledReason) const
Check whether an addon has been disabled via DisableAddon except for a particular reason In case the disabled cache does not know about the current state the database routine will be used.
bool CanAddonBeDisabled (const std::string &ID)
bool CanAddonBeEnabled (const std::string &id)
bool IsAddonInstalled (const std::string &ID)
bool IsAddonInstalled (const std::string &ID, const std::string &origin) const
bool IsAddonInstalled (const std::string &ID, const std::string &origin, const CAddonVersion &version)
bool CanAddonBeInstalled (const AddonPtr &addon)
bool CanUninstall (const AddonPtr &addon)
bool IsBundledAddon (const std::string &id)
Checks whether an addon is a bundled addon.
bool IsSystemAddon (const std::string &id)
Checks whether an addon is a system addon.
bool IsRequiredSystemAddon (const std::string &id)
Checks whether an addon is a required system addon.
bool IsOptionalSystemAddon (const std::string &id)
Checks whether an addon is an optional system addon.
bool AddUpdateRuleToList (const std::string &id, AddonUpdateRule updateRule)
Addon update rules.
bool RemoveAllUpdateRulesFromList (const std::string &id)
bool RemoveUpdateRuleFromList (const std::string &id, AddonUpdateRule updateRule)
bool IsAutoUpdateable (const std::string &id) const
void PublishEventAutoUpdateStateChanged (const std::string &id)
void UpdateLastUsed (const std::string &id)
void PublishInstanceAdded (const std::string &addonId, AddonInstanceId instanceId)
Launches event AddonEvent::InstanceAdded.
void PublishInstanceRemoved (const std::string &addonId, AddonInstanceId instanceId)
Launches event AddonEvent::InstanceRemoved.
bool LoadAddonDescription (const std::string &path, AddonPtr &addon)
Load the addon in the given path This loads the addon using c-pluff which parses the addon descriptor file.
bool ServicesHasStarted () const
bool IsCompatible (const std::shared_ptr< const IAddon > &addon) const
Check if given addon is compatible with Kodi.
bool IsCompatible (const AddonInfoPtr &addonInfo) const
Check given addon information is compatible with Kodi.
std::vector< DependencyInfo > GetDepsRecursive (const std::string &id, OnlyEnabledRootAddon onlyEnabledRootAddon)
Recursively get dependencies for an add-on.
bool GetAddonInfos (std::vector< AddonInfoPtr > &addonInfos, bool onlyEnabled, AddonType type) const
Get a list of add-on's with info's for the on system available ones.
std::vector< AddonInfoPtr > GetAddonInfos (bool onlyEnabled, const std::vector< AddonType > &types) const
Get a list of add-on's with info's for the on system available ones.
bool GetDisabledAddonInfos (std::vector< AddonInfoPtr > &addonInfos, AddonType type) const
Get a list of disabled add-on's with info's.
bool GetDisabledAddonInfos (std::vector< AddonInfoPtr > &addonInfos, AddonType type, AddonDisabledReason disabledReason) const
Get a list of disabled add-on's with info's for the on system available ones with a specific disabled reason.
const AddonInfoPtr GetAddonInfo (const std::string &id, AddonType type) const
const std::string & GetTempAddonBasePath ()
Get the path where temporary add-on files are stored.
AddonOriginType GetAddonOriginType (const AddonPtr &addon) const
bool IsAddonDisabledWithReason (const std::string &ID, AddonDisabledReason disabledReason) const
Check whether an addon has been disabled with a special reason.
bool SetAddonOrigin (const std::string &addonId, const std::string &repoAddonId, bool isUpdate)
Addon update and install management.
bool AddonsFromRepoXML (const RepositoryDirInfo &repo, const std::string &xml, std::vector< AddonInfoPtr > &addons)
Parse a repository XML file for addons and load their descriptors.
std::map< std::string, AddonWithUpdate > GetAddonsWithAvailableUpdate () const
Retrieves list of outdated addons as well as their related available updates and stores them into map.
std::vector< std::shared_ptr< IAddon > > GetCompatibleVersions (const std::string &addonId) const
Retrieves list of compatible addon versions of all origins.
const std::string & GetLastAvailableUpdatesCountAsString () const
Return number of available updates formatted as string this can be used as a lightweight method of retrieving the number of updates rather than using the expensive GetAvailableUpdates call.
std::vector< std::shared_ptr< IAddon > > GetOrphanedDependencies () const
returns a vector with all found orphaned dependencies.
Private Member Functions
CAddonMgr & operator= (CAddonMgr const &)=delete
std::vector< std::shared_ptr< IAddon > > GetAvailableUpdatesOrOutdatedAddons (AddonCheckType addonCheckType) const
returns a vector with either available updates or outdated addons. usually called by its wrappers GetAvailableUpdates() or GetOutdatedAddons()
bool GetAddonsInternal (AddonType type, VECADDONS &addons, OnlyEnabled onlyEnabled, CheckIncompatible checkIncompatible) const
bool EnableSingle (const std::string &id)
void FindAddons (ADDON_INFO_LIST &addonmap, const std::string &path)
bool GetIncompatibleAddonInfos (std::vector< AddonInfoPtr > &incompatible, bool includeDisabled) const
Fills the the provided vector with the list of incompatible addons and returns if there's any.
bool GetAddonUpdateCandidates (VECADDONS &updates) const
void SortByDependencies (VECADDONS &updates) const
Sort a list of addons for installation, i.e., defines the order of installation depending of each addon dependencies.
void InstallAddonUpdates (VECADDONS &updates, bool wait, AllowCheckForUpdates allowCheckForUpdates) const
Private Attributes
VECADDONS m_updateableAddons
std::mutex m_installAddonsMutex
std::map< std::string, AddonDisabledReason > m_disabled
CCriticalSection m_critSection
std::unique_ptr< CAddonDatabase > m_database
std::unique_ptr< CAddonUpdateRules > m_updateRules
CEventSource< AddonEvent > m_events
CBlockingEventSource< AddonEvent > m_unloadEvents
std::set< std::string > m_systemAddons
std::set< std::string > m_optionalSystemAddons
ADDON_INFO_LIST m_installedAddons
const std::string m_tempAddonBasePath = "special://temp/addons"
std::string m_lastAvailableUpdatesCountAsString
std::mutex m_lastAvailableUpdatesCountMutex
Static Private Attributes
static std::map< AddonType, IAddonMgrCallback * > m_managers
Detailed Description
Class - CAddonMgr Holds references to all addons, enabled or otherwise. Services the generic callbacks available to all addon variants.
Constructor & Destructor Documentation
CAddonMgr() [1/2]
ADDON::CAddonMgr::CAddonMgr ()
CAddonMgr() [2/2]
ADDON::CAddonMgr::CAddonMgr (const CAddonMgr &) delete
~CAddonMgr()
ADDON::CAddonMgr::~CAddonMgr () virtual
References DeInit().
Member Function Documentation
AddonsFromRepoXML()
bool ADDON::CAddonMgr::AddonsFromRepoXML (const RepositoryDirInfo & repo, const std::string & xml, std::vector< AddonInfoPtr > & addons)
Parse a repository XML file for addons and load their descriptors.
A repository XML is essentially a concatenated list of addon descriptors.
Parameters
[in] repo The repository info.
[in] xml The XML document from repository.
[out] addons returned list of addons.
Returns
true if the repository XML file is parsed, false otherwise.
Currently listed call sources:
CRepository::FetchIndex
References addons, ADDON::CAddonInfoBuilder::Generate(), CLog::Log(), LOGERROR, and CXBMCTinyXML2::Parse().
Referenced by ADDON::CRepository::FetchIndex().
AddToUpdateableAddons()
void ADDON::CAddonMgr::AddToUpdateableAddons (AddonPtr & pAddon)
References m_critSection, and m_updateableAddons.
Referenced by XBMCAddon::xbmcaddon::Addon::Addon().
AddUpdateRuleToList()
bool ADDON::CAddonMgr::AddUpdateRuleToList (const std::string & id, AddonUpdateRule updateRule)
Addon update rules.
member functions for handling and querying add-on update rules
Warning
This should be never used from other places outside of addon system directory.
References m_database, and m_updateRules.
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), and CGUIDialogAddonInfo::OnToggleAutoUpdates().
CanAddonBeDisabled()
bool ADDON::CAddonMgr::CanAddonBeDisabled (const std::string & ID)
References ADDON::CHOICE_NO, GetAddon(), ID, IsRequiredSystemAddon(), m_critSection, and ADDON::UNKNOWN.
Referenced by CanUninstall(), DisableAddon(), CONTEXTMENU::CDisableAddon::IsVisible(), and CGUIDialogAddonInfo::UpdateControls().
CanAddonBeEnabled()
bool ADDON::CAddonMgr::CanAddonBeEnabled (const std::string & id)
References IsAddonInstalled().
Referenced by CONTEXTMENU::CEnableAddon::IsVisible().
CanAddonBeInstalled()
bool ADDON::CAddonMgr::CanAddonBeInstalled (const AddonPtr & addon)
References ADDON::BROKEN, and IsAddonInstalled().
CanUninstall()
bool ADDON::CAddonMgr::CanUninstall (const AddonPtr & addon)
References CanAddonBeDisabled(), and IsBundledAddon().
Referenced by CGUIDialogAddonInfo::UpdateControls().
CheckAndInstallAddonUpdates()
void ADDON::CAddonMgr::CheckAndInstallAddonUpdates (bool wait) const
Install available addon updates, if any.
Parameters
wait If kodi should wait for all updates to download and install before returning
References ADDON::CHOICE_YES, GetAddonUpdateCandidates(), InstallAddonUpdates(), and m_installAddonsMutex.
Referenced by ADDON::CRepositoryUpdater::OnJobComplete().
DeInit()
void ADDON::CAddonMgr::DeInit ()
References XFILE::CDirectory::Exists(), m_database, m_tempAddonBasePath, XFILE::CDirectory::RemoveRecursive(), and CSpecialProtocol::TranslatePath().
Referenced by ReInit(), and ~CAddonMgr().
DisableAddon()
bool ADDON::CAddonMgr::DisableAddon (const std::string & ID, AddonDisabledReason disabledReason)
Disable an addon. Returns true on success, false on failure.
References CanAddonBeDisabled(), ADDON::CHOICE_NO, GetAddon(), CServiceBroker::GetEventLog(), CLog::Log(), LOGDEBUG, m_critSection, m_database, m_disabled, m_events, and ADDON::UNKNOWN.
Referenced by DisableIncompatibleAddons(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), CONTEXTMENU::CDisableAddon::Execute(), CGUIDialogAddonInfo::OnEnableDisable(), CGUIDialogSubtitles::OnSubtitleServiceContextMenu(), JSONRPC::CAddonsOperations::SetAddonEnabled(), and PVR::CPVRClients::UpdateClients().
DisableIncompatibleAddons()
std::vector< AddonInfoPtr > ADDON::CAddonMgr::DisableIncompatibleAddons (const std::vector< AddonInfoPtr > & incompatible)
Try to disable addons in the given list.
Parameters
[in] incompatible List of incompatible addon infos
Returns
list of all addon Infos that were disabled
References DisableAddon(), ADDON::CAddonSystemSettings::GetInstance(), ADDON::INCOMPATIBLE, CLog::Log(), LOGINFO, and LOGWARNING.
Referenced by CApplication::Initialize(), and MigrateAddons().
EnableAddon()
bool ADDON::CAddonMgr::EnableAddon (const std::string & ID)
Enable an addon. Returns true on success, false on failure.
References EnableSingle(), IsAddonInstalled(), CLog::Log(), LOGWARNING, and ADDON::ResolveDependencies().
Referenced by KODI::GAME::CGameUtils::Enable(), EnableAddon(), CONTEXTMENU::CEnableAddon::Execute(), KODI::GAME::CGameClientProperties::GetProxyAddons(), PERIPHERALS::CPeripheralJoystick::InstallSync(), LoadAddon(), CGUIDialogAddonInfo::OnEnableDisable(), PERIPHERALS::CPeripheralBusAddon::PromptEnableAddons(), CGUIWindowAddonBrowser::SelectAddonID(), and JSONRPC::CAddonsOperations::SetAddonEnabled().
EnableSingle()
bool ADDON::CAddonMgr::EnableSingle (const std::string & id) private
References ADDON::CHOICE_NO, Error, GetAddon(), CServiceBroker::GetEventLog(), ADDON::INCOMPATIBLE, IsCompatible(), CLog::Log(), LOGDEBUG, LOGERROR, m_critSection, m_database, m_disabled, m_events, ADDON::REPOSITORY, SetAddonOrigin(), ADDON::UNKNOWN, and UpdateDisabledReason().
Referenced by EnableAddon().
Events()
CEventStream< AddonEvent > & ADDON::CAddonMgr::Events () inline
References m_events.
Referenced by KODI::GAME::CControllerManager::CControllerManager(), KODI::ADDONS::CExtsMimeSupportList::CExtsMimeSupportList(), CFileExtensionProvider::CFileExtensionProvider(), PERIPHERALS::CPeripheralBusAddon::CPeripheralBusAddon(), PVR::CPVRClients::CPVRClients(), ADDON::CBinaryAddonCache::Deinit(), ADDON::CVFSAddonCache::Deinit(), CContextMenuManager::Deinit(), KODI::GAME::CGUIAgentControllerList::Deinitialize(), KODI::GAME::CGUIControllerList::Deinitialize(), KODI::GAME::CGUIActivePortList::Deinitialize(), KODI::GAME::CGUIPortList::Deinitialize(), ADDON::CBinaryAddonCache::Init(), ADDON::CVFSAddonCache::Init(), CContextMenuManager::Init(), KODI::GAME::CGUIControllerList::Initialize(), KODI::GAME::CGUIAgentControllerList::Initialize(), KODI::GAME::CGUIActivePortList::Initialize(), KODI::GAME::CGUIPortList::Initialize(), KODI::GAME::CGUIControllerWindow::OnDeinitWindow(), KODI::GAME::CGUIControllerWindow::OnInitWindow(), CGUIWindowAddonBrowser::OnMessage(), CDirectoryProvider::Reset(), ADDON::CRepositoryUpdater::Start(), ADDON::CServiceAddonManager::Start(), ADDON::CServiceAddonManager::Stop(), CDirectoryProvider::UpdateURL(), KODI::GAME::CControllerManager::~CControllerManager(), KODI::ADDONS::CExtsMimeSupportList::~CExtsMimeSupportList(), CFileExtensionProvider::~CFileExtensionProvider(), PERIPHERALS::CPeripheralBusAddon::~CPeripheralBusAddon(), PVR::CPVRClients::~CPVRClients(), ADDON::CRepositoryUpdater::~CRepositoryUpdater(), and ADDON::CServiceAddonManager::~CServiceAddonManager().
FindAddon()
bool ADDON::CAddonMgr::FindAddon (const std::string & addonId, const std::string & origin, const CAddonVersion & addonVersion)
Checks whether given addon with given origin/version is installed.
Parameters
addonId addon to check
origin origin to check
addonVersion version to check
Returns
True if installed, false otherwise
References ADDON::CAddonVersion::asString(), CSpecialProtocol::ComparePath(), FindAddons(), CLog::Log(), LOGINFO, m_critSection, m_database, m_disabled, m_installedAddons, and m_updateRules.
Referenced by LoadAddon().
FindAddons() [1/2]
bool ADDON::CAddonMgr::FindAddons ()
Checks for new / updated add-ons.
Returns
True if everything went ok, false otherwise
References CSpecialProtocol::ComparePath(), FindAddons(), CLog::Log(), LOGINFO, m_critSection, m_database, m_disabled, m_installedAddons, m_optionalSystemAddons, m_systemAddons, and m_updateRules.
Referenced by FindAddon(), FindAddons(), Init(), and UpdateLocals().
FindAddons() [2/2]
void ADDON::CAddonMgr::FindAddons (ADDON_INFO_LIST & addonmap, const std::string & path) private
References XFILE::DIR_FLAG_NO_FILE_DIRS, CFileUtils::Exists(), ADDON::CAddonInfoBuilder::Generate(), XFILE::CDirectory::GetDirectory(), CFileItem::GetPath(), CLog::Log(), LOGDEBUG, LOGWARNING, and CFileItemList::Size().
FindInstallableById()
bool ADDON::CAddonMgr::FindInstallableById (const std::string & addonId, AddonPtr & addon)
Get the installable addon depending on install rules or fall back to highest version.
Note
This function gets called in different contexts. If it's called for checking possible updates for already installed addons our update restriction rules apply. If it's called to (for example) populate an addon-select-dialog the addon is not installed yet, and we have to fall back to the highest version.
Parameters
addonId addon to check for update or installation
addon[out] the retrieved addon pointer - only use if the function returns true.
Returns
true if an addon matching the id is available.
References ADDON::CHOICE_NO, ADDON::CAddonRepos::DoAddonUpdateCheck(), GetAddon(), ADDON::CAddonRepos::GetLatestAddonVersionFromAllRepos(), ADDON::CAddonRepos::IsValid(), LOGADDONS, LOGDEBUG, m_critSection, and ADDON::UNKNOWN.
Referenced by CGUIDialogAddonInfo::BuildDependencyList(), ADDON::CRepositoryUpdateJob::DoWork(), GetDepsRecursive(), KODI::GAME::CGameClientProperties::InstallDependencies(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::ReportInstallError(), and CGUIDialogAddonInfo::ShowDependencyList().
GetAddon() [1/2]
bool ADDON::CAddonMgr::GetAddon (const std::string & id, AddonPtr & addon, AddonType type, OnlyEnabled onlyEnabled) const
Retrieve a specific addon (of a specific type)
Parameters
id the id of the addon to retrieve.
addon[out] the retrieved addon pointer - only use if the function returns true.
type type of addon to retrieve - defaults to any type.
onlyEnabled whether we only want enabled addons - set to false to allow both enabled and disabled addons - defaults to true.
Returns
true if an addon matching the id of the given type is available and is enabled (if onlyEnabled is true).
References ADDON::CHOICE_YES, ADDON::CAddonBuilder::Generate(), GetAddonInfo(), IsAddonDisabled(), and m_critSection.
Referenced by XBMCAddon::xbmcaddon::Addon::Addon(), CGUIDialogAddonInfo::BuildDependencyList(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::CAddonInstallJob(), CanAddonBeDisabled(), ADDON::CAddonInstaller::CheckDependencies(), DisableAddon(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), EnableSingle(), CONTEXTMENU::CAddonSettings::Execute(), CONTEXTMENU::CCheckForUpdates::Execute(), ADDON::CAddonRepos::FindDependency(), FindInstallableById(), ADDON::CAddonSystemSettings::GetActive(), GetAddon(), CPythonInvoker::getAddonModuleDeps(), anonymous_namespace{TestDefaultKeyboardTranslator.cpp}::GetController(), anonymous_namespace{TestDefaultMouseTranslator.cpp}::GetController(), KODI::GAME::CControllerManager::GetController(), GetDepsRecursive(), CGUIWindowAddonBrowser::GetDirectory(), KODI::GUILIB::GUIINFO::CAddonsGUIInfo::GetLabel(), KODI::GAME::CGameClient::GetMissingResource(), KODI::GAME::CGameClientProperties::GetProxyAddons(), KODI::GAME::CGameClientProperties::GetResourceDirectories(), CMusicDatabase::GetScraper(), CVideoDatabase::GetScraperForPath(), KODI::GAME::CDialogGameSaves::HandleGameClient(), HasType(), Init(), KODI::CDRIP::CEncoderFFmpeg::Init(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::Install(), ADDON::CAddonInstaller::InstallModal(), IsAddonInstalled(), IsAddonInstalled(), IsAddonInstalled(), IsCompatible(), XFILE::CAddonsDirectory::IsRepoDirectory(), CONTEXTMENU::CAddonSettings::IsVisible(), LoadAddon(), CContextMenuManager::OnEvent(), KODI::GAME::CDialogGameSaves::OnInitWindow(), CGUIDialogSubtitles::OnSubtitleServiceContextMenu(), CFavouritesURL::Parse(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::ReportInstallError(), ADDON::CServiceAddonManager::Start(), XFILE::CPluginDirectory::StartScript(), TEST(), UnloadAddon(), CGUIControlButtonSetting::Update(), and CGUIWindowScreensaverDim::UpdateVisibility().
GetAddon() [2/2]
bool ADDON::CAddonMgr::GetAddon (const std::string & id, AddonPtr & addon, OnlyEnabled onlyEnabled) const
Retrieve a specific addon (of no specific type)
Parameters
id the id of the addon to retrieve.
addon[out] the retrieved addon pointer - only use if the function returns true.
onlyEnabled whether we only want enabled addons - set to false to allow both enabled and disabled addons - defaults to true.
Returns
true if an addon matching the id of any type is available and is enabled (if onlyEnabled is true).
References GetAddon(), and ADDON::UNKNOWN.
GetAddonInfo()
const AddonInfoPtr ADDON::CAddonMgr::GetAddonInfo (const std::string & id, AddonType type) const
References m_critSection, m_installedAddons, and ADDON::UNKNOWN.
Referenced by ADDON::CRepository::CRepository(), GetAddon(), PVR::CPVRClients::GetEnabledClientInfos(), KODI::CDRIP::CCDDARipper::GetTrackName(), CGUIVisualisationControl::InitVisualization(), IsCompatible(), CGUIWindowScreensaver::OnMessage(), SetAddonOrigin(), KODI::CDRIP::CCDDARipJob::SetupEncoder(), KODI::ADDONS::CExtsMimeSupportList::Update(), ADDON::CVFSAddonCache::Update(), and UpdateLastUsed().
GetAddonInfos() [1/2]
std::vector< AddonInfoPtr > ADDON::CAddonMgr::GetAddonInfos (bool onlyEnabled, const std::vector< AddonType > & types) const
Get a list of add-on's with info's for the on system available ones.
Parameters
[in] onlyEnabled If true are only enabled ones given back, if false all on system available. Default is true.
[in] types List about requested types.
Returns
List where finded addon information becomes returned.
Note
ADDON_UNKNOWN should not used for here!
References m_critSection, m_disabled, m_installedAddons, t, ADDON::types, and ADDON::UNKNOWN.
GetAddonInfos() [2/2]
bool ADDON::CAddonMgr::GetAddonInfos (std::vector< AddonInfoPtr > & addonInfos, bool onlyEnabled, AddonType type) const
Get a list of add-on's with info's for the on system available ones.
Parameters
[out] addonInfos list where finded addon information becomes stored
[in] onlyEnabled If true are only enabled ones given back, if false all on system available. Default is true.
[in] type The requested type, with "ADDON_UNKNOWN" are all add-on types given back who match the case with value before. If a type id becomes added are only add-ons returned who match them. Default is for all types.
Returns
true if the list contains entries
Referenced by KODI::ADDONS::CExtsMimeSupportList::CExtsMimeSupportList(), CDVDFactoryInputStream::CreateInputStream(), PVR::CPVRDatabase::FixupClientIDs(), PVR::CPVRClients::GetAddonsWithStatus(), PVR::CPVRClients::GetCallableClients(), PVR::CPVRClients::GetClientProviderInfos(), GetIncompatibleAddonInfos(), ADDON::CVFSAddonCache::Init(), CFileExtensionProvider::SetAddonExtensions(), and PERIPHERALS::CPeripheralBusAddon::UpdateAddons().
GetAddonOriginType()
AddonOriginType ADDON::CAddonMgr::GetAddonOriginType (const AddonPtr & addon) const
References ADDON::MANUAL, ADDON::ORIGIN_SYSTEM, ADDON::REPOSITORY, and ADDON::SYSTEM.
GetAddons() [1/2]
bool ADDON::CAddonMgr::GetAddons (VECADDONS & addons) const
Returns all installed, enabled add-ons.
References addons, ADDON::CHOICE_NO, ADDON::CHOICE_YES, GetAddonsInternal(), and ADDON::UNKNOWN.
Referenced by ADDON::CRepositoryUpdater::CheckForUpdates(), ADDON::CRepositoryUpdater::ClosestNextCheck(), CLangInfo::ConvertEnglishNameToAddonLocale(), CPythonInvoker::execute(), CGUIDialogSubtitles::FillServices(), JSONRPC::CAddonsOperations::GetAddons(), CLangInfo::GetAddonsLanguageCodes(), CNfoFile::GetScrapers(), XFILE::CAddonsDirectory::GetScriptsAndPlugins(), ADDON::CRepositoryUpdater::LastUpdated(), GUIFontManager::LoadTTF(), CGUIDialogAddonInfo::PromptIfDependency(), CContextMenuManager::ReloadAddonItems(), XFILE::Repos(), XFILE::RunningAddons(), CGUIWindowAddonBrowser::SelectAddonID(), and ADDON::CServiceAddonManager::Start().
GetAddons() [2/2]
bool ADDON::CAddonMgr::GetAddons (VECADDONS & addons, AddonType type)
Returns enabled add-ons with given type.
References addons, ADDON::CHOICE_NO, ADDON::CHOICE_YES, and GetAddonsInternal().
GetAddonsForUpdate()
bool ADDON::CAddonMgr::GetAddonsForUpdate (VECADDONS & addons) const
Returns all installed, enabled and incompatible (and disabled) add-ons.
References addons, ADDON::CHOICE_YES, GetAddonsInternal(), and ADDON::UNKNOWN.
Referenced by GetAddonsWithAvailableUpdate(), and GetAvailableUpdatesOrOutdatedAddons().
GetAddonsInternal()
bool ADDON::CAddonMgr::GetAddonsInternal (AddonType type, VECADDONS & addons, OnlyEnabled onlyEnabled, CheckIncompatible checkIncompatible) const private
References addons, ADDON::CHOICE_NO, ADDON::CHOICE_YES, ADDON::CAddonBuilder::Generate(), ADDON::INCOMPATIBLE, IsAddonDisabled(), IsAddonDisabledExcept(), m_critSection, m_installedAddons, and ADDON::UNKNOWN.
Referenced by GetAddons(), GetAddons(), GetAddonsForUpdate(), GetInstalledAddons(), GetInstalledAddons(), and GetOrphanedDependencies().
GetAddonsWithAvailableUpdate()
std::map< std::string, AddonWithUpdate > ADDON::CAddonMgr::GetAddonsWithAvailableUpdate () const
Retrieves list of outdated addons as well as their related available updates and stores them into map.
Returns
map of outdated addons with their update
References ADDON::CAddonRepos::BuildAddonsWithUpdateList(), end(), GetAddonsForUpdate(), ADDON::CAddonRepos::IsValid(), CLog::Log(), LOGDEBUG, and m_critSection.
Referenced by XFILE::CAddonsDirectory::GenerateAddonListing().
GetAddonUpdateCandidates()
bool ADDON::CAddonMgr::GetAddonUpdateCandidates (VECADDONS & updates) const private
Get the list of of available updates
Parameters
[in,out] updates the vector of addons to be filled with addons that need to be updated (not blacklisted)
Returns
if there are any addons needing updates
References GetAvailableUpdates().
Referenced by CheckAndInstallAddonUpdates(), and MigrateAddons().
GetAvailableUpdates()
std::vector< std::shared_ptr< IAddon > > ADDON::CAddonMgr::GetAvailableUpdates () const
Get addons with available updates
References ADDON::AVAILABLE_UPDATES, GetAvailableUpdatesOrOutdatedAddons(), m_lastAvailableUpdatesCountAsString, and m_lastAvailableUpdatesCountMutex.
Referenced by GetAddonUpdateCandidates(), HasAvailableUpdates(), ADDON::CRepositoryUpdater::OnJobComplete(), XFILE::OutdatedAddons(), UpdateAddons::Run(), and UpdateAllowedAddons::Run().
GetAvailableUpdatesOrOutdatedAddons()
std::vector< std::shared_ptr< IAddon > > ADDON::CAddonMgr::GetAvailableUpdatesOrOutdatedAddons (AddonCheckType addonCheckType) const private
returns a vector with either available updates or outdated addons. usually called by its wrappers GetAvailableUpdates() or GetOutdatedAddons()
Parameters
[in] true to return outdated addons, false to return available updates
Returns
vector filled with either available updates or outdated addons
References ADDON::CAddonRepos::BuildUpdateOrOutdatedList(), end(), GetAddonsForUpdate(), ADDON::CAddonRepos::IsValid(), CLog::Log(), and LOGDEBUG.
Referenced by GetAvailableUpdates(), and GetOutdatedAddons().
GetCallbackForType()
IAddonMgrCallback * ADDON::CAddonMgr::GetCallbackForType (AddonType type)
References m_managers.
Referenced by ADDON::CAddonStatusHandler::Process().
GetCompatibleVersions()
std::vector< std::shared_ptr< IAddon > > ADDON::CAddonMgr::GetCompatibleVersions (const std::string & addonId) const
Retrieves list of compatible addon versions of all origins.
Parameters
[in] addonId addon to look up
Returns
vector containing compatible addon versions
References ADDON::CAddonRepos::BuildCompatibleVersionsList(), end(), ADDON::CAddonRepos::IsValid(), CLog::Log(), LOGDEBUG, and m_critSection.
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), and CGUIDialogAddonInfo::OnSelectVersion().
GetDepsRecursive()
std::vector< DependencyInfo > ADDON::CAddonMgr::GetDepsRecursive (const std::string & id, OnlyEnabledRootAddon onlyEnabledRootAddon)
Recursively get dependencies for an add-on.
Parameters
id the id of the root addon
onlyEnabledRootAddon whether look for enabled root add-ons only
References FindInstallableById(), GetAddon(), and ADDON::UNKNOWN.
Referenced by CGUIDialogAddonInfo::BuildDependencyList(), and ADDON::CFontResource::OnPostInstall().
GetDisabledAddonInfos() [1/2]
bool ADDON::CAddonMgr::GetDisabledAddonInfos (std::vector< AddonInfoPtr > & addonInfos, AddonType type) const
Get a list of disabled add-on's with info's.
Parameters
[out] addonInfos list where finded addon information becomes stored
[in] type The requested type, with "ADDON_UNKNOWN" are all add-on types given back who match the case with value before. If a type id becomes added are only add-ons returned who match them. Default is for all types.
Returns
true if the list contains entries
References GetDisabledAddonInfos(), and ADDON::NONE.
Referenced by PERIPHERALS::CPeripheralBusAddon::EnableButtonMapping(), GetDisabledAddonInfos(), and GetIncompatibleAddonInfos().
GetDisabledAddonInfos() [2/2]
bool ADDON::CAddonMgr::GetDisabledAddonInfos (std::vector< AddonInfoPtr > & addonInfos, AddonType type, AddonDisabledReason disabledReason) const
Get a list of disabled add-on's with info's for the on system available ones with a specific disabled reason.
Parameters
[out] addonInfos list where finded addon information becomes stored
[in] type The requested type, with "ADDON_UNKNOWN" are all add-on types given back who match the case with value before. If a type id becomes added are only add-ons returned who match them. Default is for all types.
[in] disabledReason To get all disabled addons use the value "AddonDiasbledReason::NONE". If any other value is supplied only addons with that reason will be returned.
Returns
true if the list contains entries
References m_critSection, m_disabled, m_installedAddons, ADDON::NONE, and ADDON::UNKNOWN.
GetDisabledAddons() [1/2]
bool ADDON::CAddonMgr::GetDisabledAddons (VECADDONS & addons)
References addons, GetDisabledAddons(), and ADDON::UNKNOWN.
Referenced by JSONRPC::CAddonsOperations::GetAddons(), and GetDisabledAddons().
GetDisabledAddons() [2/2]
bool ADDON::CAddonMgr::GetDisabledAddons (VECADDONS & addons, AddonType type)
References addons, and GetInstalledAddons().
GetIncompatibleAddonInfos()
bool ADDON::CAddonMgr::GetIncompatibleAddonInfos (std::vector< AddonInfoPtr > & incompatible, bool includeDisabled) const private
Fills the the provided vector with the list of incompatible addons and returns if there's any.
Parameters
[out] incompatible List of incompatible addons
[in] whether or not to include incompatible addons that are disabled
Returns
true if there are incompatible addons
References GetAddonInfos(), GetDisabledAddonInfos(), ADDON::INCOMPATIBLE, and ADDON::UNKNOWN.
Referenced by GetIncompatibleEnabledAddonInfos(), and MigrateAddons().
GetIncompatibleEnabledAddonInfos()
bool ADDON::CAddonMgr::GetIncompatibleEnabledAddonInfos (std::vector< AddonInfoPtr > & incompatible) const
Fills the the provided vector with the list of incompatible enabled addons and returns if there's any.
Parameters
[out] incompatible List of incompatible addons
Returns
true if there are incompatible addons
References GetIncompatibleAddonInfos().
GetInstallableAddons() [1/2]
bool ADDON::CAddonMgr::GetInstallableAddons (VECADDONS & addons)
Get all installable addons
References addons, GetInstallableAddons(), and ADDON::UNKNOWN.
Referenced by JSONRPC::CAddonsOperations::GetAddons(), GetInstallableAddons(), KODI::GAME::CControllerInstaller::Process(), and KODI::GAME::CGUIControllerWindow::UpdateButtons().
GetInstallableAddons() [2/2]
bool ADDON::CAddonMgr::GetInstallableAddons (VECADDONS & addons, AddonType type)
References addons, ADDON::CAddonRepos::GetLatestAddonVersions(), ADDON::CAddonRepos::IsValid(), and m_critSection.
GetInstalledAddons() [1/2]
bool ADDON::CAddonMgr::GetInstalledAddons (VECADDONS & addons)
Returns all installed, including disabled.
References addons, ADDON::CHOICE_NO, GetAddonsInternal(), and ADDON::UNKNOWN.
Referenced by XFILE::DependencyAddons(), JSONRPC::CAddonsOperations::GetAddons(), KODI::GAME::CControllerManager::GetControllers(), GetDisabledAddons(), ADDON::CBinaryAddonCache::Update(), and XFILE::UserInstalledAddons().
GetInstalledAddons() [2/2]
bool ADDON::CAddonMgr::GetInstalledAddons (VECADDONS & addons, AddonType type)
Returns installed add-ons, including disabled, with given type.
References addons, ADDON::CHOICE_NO, and GetAddonsInternal().
GetLastAvailableUpdatesCountAsString()
const std::string & ADDON::CAddonMgr::GetLastAvailableUpdatesCountAsString () const
Return number of available updates formatted as string this can be used as a lightweight method of retrieving the number of updates rather than using the expensive GetAvailableUpdates call.
Returns
number of available updates
References m_lastAvailableUpdatesCountAsString, and m_lastAvailableUpdatesCountMutex.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel().
GetOrphanedDependencies()
std::vector< std::shared_ptr< IAddon > > ADDON::CAddonMgr::GetOrphanedDependencies () const
returns a vector with all found orphaned dependencies.
Returns
the vector
References ADDON::CHOICE_NO, ADDON::CHOICE_YES, GetAddonsInternal(), IsOrphaned(), and ADDON::UNKNOWN.
Referenced by ADDON::CAddonInstaller::RemoveOrphanedDepsRecursively().
GetOutdatedAddons()
std::vector< std::shared_ptr< IAddon > > ADDON::CAddonMgr::GetOutdatedAddons () const
Get addons that are outdated
References GetAvailableUpdatesOrOutdatedAddons(), and ADDON::OUTDATED_ADDONS.
GetTempAddonBasePath()
const std::string & ADDON::CAddonMgr::GetTempAddonBasePath () inline
Get the path where temporary add-on files are stored.
Returns
the base path used for temporary addon paths
Warning
the folder and its contents are deleted when Kodi is closed
References m_tempAddonBasePath.
HasAddons()
bool ADDON::CAddonMgr::HasAddons (AddonType type)
References IsAddonDisabled(), m_critSection, and m_installedAddons.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), and ADDON::CRepositoryUpdater::ScheduleUpdate().
HasAvailableUpdates()
bool ADDON::CAddonMgr::HasAvailableUpdates ()
Returns true if there is any addon with available updates, otherwise false
References GetAvailableUpdates().
HasInstalledAddons()
bool ADDON::CAddonMgr::HasInstalledAddons (AddonType type)
References m_critSection, and m_installedAddons.
Referenced by anonymous_namespace{SettingConditions.cpp}::HasPeripheralLibraries().
HasType()
bool ADDON::CAddonMgr::HasType (const std::string & id, AddonType type)
References ADDON::CHOICE_NO, and GetAddon().
Referenced by CFileExtensionProvider::OnAddonEvent(), KODI::ADDONS::CExtsMimeSupportList::OnEvent(), ADDON::CRepositoryUpdater::OnEvent(), CContextMenuManager::OnEvent(), ADDON::CBinaryAddonCache::OnEvent(), and ADDON::CVFSAddonCache::OnEvent().
Init()
bool ADDON::CAddonMgr::Init ()
References ADDON::CHOICE_YES, FindAddons(), GetAddon(), ADDON::LoadManifest(), CLog::Log(), LOGERROR, LOGFATAL, m_critSection, m_database, m_optionalSystemAddons, m_systemAddons, and ADDON::UNKNOWN.
Referenced by ReInit().
InstallAddonUpdates()
void ADDON::CAddonMgr::InstallAddonUpdates (VECADDONS & updates, bool wait, AllowCheckForUpdates allowCheckForUpdates) const private
Install the list of addon updates via AddonInstaller
Parameters
[in,out] updates the vector of addons to install (will be sorted)
wait if the process should wait for all addons to install
allowCheckForUpdates indicates if content update checks are allowed after installation of a repository addon from the list
References ADDON::CAddonInstaller::GetInstance(), ADDON::CAddonInstaller::InstallAddons(), and SortByDependencies().
Referenced by CheckAndInstallAddonUpdates(), and MigrateAddons().
IsAddonDisabled()
bool ADDON::CAddonMgr::IsAddonDisabled (const std::string & ID) const
References ID, m_critSection, and m_disabled.
Referenced by JSONRPC::CAddonsOperations::FillDetails(), XFILE::CAddonsDirectory::GenerateAddonListing(), GetAddon(), ADDON::CBinaryAddonCache::GetAddons(), GetAddonsInternal(), PVR::CPVRClients::GetAddonsWithStatus(), KODI::GUILIB::GUIINFO::CAddonsGUIInfo::GetBool(), PVR::CPVRClients::GetClientProviderInfos(), ADDON::CBinaryAddonCache::GetDisabledAddons(), KODI::GAME::CGameClientProperties::GetProxyAddons(), HasAddons(), ADDON::Interface_General::is_addon_avilable(), PVR::CPVRClient::IsEnabled(), PVR::CPVRClients::IsEnabledClient(), CONTEXTMENU::CEnableAddon::IsVisible(), CONTEXTMENU::CDisableAddon::IsVisible(), LoadAddon(), CGUIWindowAddonBrowser::SelectAddonID(), JSONRPC::CAddonsOperations::SetAddonEnabled(), CGUIDialogInfoProviderSettings::Show(), KODI::ADDONS::CExtsMimeSupportList::Update(), CGUIDialogAddonInfo::UpdateControls(), and UpdateDisabledReason().
IsAddonDisabledExcept()
bool ADDON::CAddonMgr::IsAddonDisabledExcept (const std::string & ID, AddonDisabledReason disabledReason) const
Check whether an addon has been disabled via DisableAddon except for a particular reason In case the disabled cache does not know about the current state the database routine will be used.
Parameters
[in] ID id of the addon
[in] disabledReason the reason that will be an exception to being disabled
Returns
true if the addon was disabled except for the specified reason
See also
DisableAddon
References ID, m_critSection, and m_disabled.
Referenced by GetAddonsInternal().
IsAddonDisabledWithReason()
bool ADDON::CAddonMgr::IsAddonDisabledWithReason (const std::string & ID, AddonDisabledReason disabledReason) const
Check whether an addon has been disabled with a special reason.
Parameters
ID id of the addon
disabledReason reason we want to check for (NONE, USER, INCOMPATIBLE, PERMANENT_FAILURE)
Returns
true or false
References ID, m_critSection, and m_disabled.
Referenced by ADDON::CAddonRepos::FindAddonAndCheckForUpdate().
IsAddonInstalled() [1/3]
bool ADDON::CAddonMgr::IsAddonInstalled (const std::string & ID)
References ADDON::CHOICE_NO, GetAddon(), ID, and ADDON::UNKNOWN.
Referenced by CanAddonBeEnabled(), CanAddonBeInstalled(), EnableAddon(), JSONRPC::CAddonsOperations::FillDetails(), XFILE::CAddonsDirectory::GenerateAddonListing(), KODI::GUILIB::GUIINFO::CAddonsGUIInfo::GetBool(), KODI::GAME::CGameUtils::Install(), PERIPHERALS::CPeripheralJoystick::InstallSync(), CGUIWindowAddonBrowser::SelectAddonID(), UnloadAddon(), and CGUIDialogAddonInfo::UpdateControls().
IsAddonInstalled() [2/3]
bool ADDON::CAddonMgr::IsAddonInstalled (const std::string & ID, const std::string & origin) const
References ADDON::CHOICE_NO, GetAddon(), ID, ADDON::CAddonRepos::IsOfficialRepo(), ADDON::ORIGIN_SYSTEM, and ADDON::UNKNOWN.
IsAddonInstalled() [3/3]
bool ADDON::CAddonMgr::IsAddonInstalled (const std::string & ID, const std::string & origin, const CAddonVersion & version)
References ADDON::CHOICE_NO, GetAddon(), ID, ADDON::CAddonRepos::IsOfficialRepo(), ADDON::ORIGIN_SYSTEM, and ADDON::UNKNOWN.
IsAutoUpdateable()
bool ADDON::CAddonMgr::IsAutoUpdateable (const std::string & id) const
References m_updateRules.
Referenced by KODI::GUILIB::GUIINFO::CAddonsGUIInfo::GetBool(), UpdateAllowedAddons::Run(), and CGUIDialogAddonInfo::UpdateControls().
IsBundledAddon()
bool ADDON::CAddonMgr::IsBundledAddon (const std::string & id)
Checks whether an addon is a bundled addon.
Parameters
[in] id id of the addon
Returns
true if addon is bundled addon, false otherwise.
References XFILE::CDirectory::Exists(), and CSpecialProtocol::TranslatePath().
Referenced by CanUninstall().
IsCompatible() [1/2]
bool ADDON::CAddonMgr::IsCompatible (const AddonInfoPtr & addonInfo) const
Check given addon information is compatible with Kodi.
Parameters
[in] addonInfo Addon information to check
Returns
true if compatible, false if not
References GetAddonInfo(), and ADDON::UNKNOWN.
IsCompatible() [2/2]
bool ADDON::CAddonMgr::IsCompatible (const std::shared_ptr< const IAddon > & addon) const
Check if given addon is compatible with Kodi.
Parameters
[in] addon Addon to check
Returns
true if compatible, false if not
References ADDON::CHOICE_YES, GetAddon(), and ADDON::UNKNOWN.
Referenced by ADDON::CAddonRepos::BuildCompatibleVersionsList(), EnableSingle(), and ADDON::CAddonRepos::LoadAddonsFromDatabase().
IsOptionalSystemAddon()
bool ADDON::CAddonMgr::IsOptionalSystemAddon (const std::string & id)
Checks whether an addon is an optional system addon.
Parameters
[in] id id of the addon
Returns
true if addon is an optional system addon, false otherwise.
References m_critSection, and m_optionalSystemAddons.
Referenced by IsSystemAddon().
IsOrphaned()
bool ADDON::CAddonMgr::IsOrphaned (const std::shared_ptr< IAddon > & addon, const std::vector< std::shared_ptr< IAddon > > & allAddons) const
Checks if the passed in addon is an orphaned dependency.
Parameters
addon the add-on/dependency to check
allAddons vector of all installed add-ons
Returns
true or false
References CServiceBroker::GetAddonMgr(), ADDON::CAddonType::IsDependencyType(), and IsSystemAddon().
Referenced by XFILE::DependencyAddons(), and GetOrphanedDependencies().
IsRequiredSystemAddon()
bool ADDON::CAddonMgr::IsRequiredSystemAddon (const std::string & id)
Checks whether an addon is a required system addon.
Parameters
[in] id id of the addon
Returns
true if addon is a required system addon, false otherwise.
References m_critSection, and m_systemAddons.
Referenced by CanAddonBeDisabled(), and IsSystemAddon().
IsSystemAddon()
bool ADDON::CAddonMgr::IsSystemAddon (const std::string & id)
Checks whether an addon is a system addon.
Parameters
[in] id id of the addon
Returns
true if addon is system addon, false otherwise.
References IsOptionalSystemAddon(), and IsRequiredSystemAddon().
Referenced by IsOrphaned().
LoadAddon()
bool ADDON::CAddonMgr::LoadAddon (const std::string & addonId, const std::string & origin, const CAddonVersion & addonVersion)
Note
: should only be called by AddonInstaller
Returns true if the addon was successfully loaded and enabled; otherwise false.
References ADDON::CHOICE_NO, EnableAddon(), FindAddon(), GetAddon(), IsAddonDisabled(), CLog::Log(), LOGDEBUG, LOGERROR, m_critSection, m_events, m_unloadEvents, and ADDON::UNKNOWN.
LoadAddonDescription()
bool ADDON::CAddonMgr::LoadAddonDescription (const std::string & path, AddonPtr & addon)
Load the addon in the given path This loads the addon using c-pluff which parses the addon descriptor file.
Parameters
path folder that contains the addon.
addon [out] returned addon.
Returns
true if addon is set, false otherwise.
References ADDON::CAddonBuilder::Generate(), ADDON::CAddonInfoBuilder::Generate(), and ADDON::UNKNOWN.
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork().
MigrateAddons()
std::vector< AddonInfoPtr > ADDON::CAddonMgr::MigrateAddons ()
Migrate all the addons (updates all addons that have an update pending and disables those that got incompatible)
Returns
list of all addons (infos) that were modified.
References ADDON::CHOICE_NO, DisableIncompatibleAddons(), GetAddonUpdateCandidates(), GetIncompatibleAddonInfos(), InstallAddonUpdates(), CLog::Log(), LOGINFO, and m_installAddonsMutex.
Referenced by CApplication::Initialize().
OnPostUnInstall()
void ADDON::CAddonMgr::OnPostUnInstall (const std::string & id)
Note
: should only be called by AddonInstaller
Hook for clearing internal state after uninstall.
References m_critSection, m_disabled, m_events, and RemoveAllUpdateRulesFromList().
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonUnInstallJob::DoWork().
operator=()
CAddonMgr & ADDON::CAddonMgr::operator= (CAddonMgr const &) private delete
PublishEventAutoUpdateStateChanged()
void ADDON::CAddonMgr::PublishEventAutoUpdateStateChanged (const std::string & id)
References m_events.
Referenced by CGUIDialogAddonInfo::OnToggleAutoUpdates().
PublishInstanceAdded()
void ADDON::CAddonMgr::PublishInstanceAdded (const std::string & addonId, AddonInstanceId instanceId)
Launches event AddonEvent::InstanceAdded.
This is called when a new instance is added in add-on settings.
Parameters
[in] addonId Add-on id to pass through
[in] instanceId Identifier of the add-on instance
References m_events.
Referenced by CGUIDialogAddonSettings::ShowForMultipleInstances().
PublishInstanceRemoved()
void ADDON::CAddonMgr::PublishInstanceRemoved (const std::string & addonId, AddonInstanceId instanceId)
Launches event AddonEvent::InstanceRemoved.
This is called when an instance is removed in add-on settings.
Parameters
[in] addonId Add-on id to pass through
[in] instanceId Identifier of the add-on instance
References m_events.
Referenced by CGUIDialogAddonSettings::ShowForMultipleInstances().
RegisterAddonMgrCallback()
bool ADDON::CAddonMgr::RegisterAddonMgrCallback (AddonType type, IAddonMgrCallback * cb)
References m_managers.
Referenced by PVR::CPVRClients::CPVRClients().
ReInit()
bool ADDON::CAddonMgr::ReInit () inline
References DeInit(), and Init().
Referenced by CProfileManager::FinalizeLoadProfile().
ReloadSettings()
bool ADDON::CAddonMgr::ReloadSettings (const std::string & addonId, AddonInstanceId instanceId)
References m_critSection, and m_updateableAddons.
Referenced by ADDON::CAddon::SaveSettings().
RemoveAllUpdateRulesFromList()
bool ADDON::CAddonMgr::RemoveAllUpdateRulesFromList (const std::string & id)
References m_database, and m_updateRules.
Referenced by OnPostUnInstall(), and CGUIDialogAddonInfo::OnToggleAutoUpdates().
RemoveFromUpdateableAddons()
void ADDON::CAddonMgr::RemoveFromUpdateableAddons (AddonPtr & pAddon)
References m_critSection, and m_updateableAddons.
Referenced by XBMCAddon::xbmcaddon::Addon::~Addon().
RemoveUpdateRuleFromList()
bool ADDON::CAddonMgr::RemoveUpdateRuleFromList (const std::string & id, AddonUpdateRule updateRule)
References m_database, and m_updateRules.
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork().
ServicesHasStarted()
bool ADDON::CAddonMgr::ServicesHasStarted () const
SetAddonOrigin()
bool ADDON::CAddonMgr::SetAddonOrigin (const std::string & addonId, const std::string & repoAddonId, bool isUpdate)
Addon update and install management.
Parts inside here are used for changes about addon system.
Warning
This should be never used from other places outside of addon system directory.
Update addon origin data.
This becomes called from CAddonInstallJob to set the source repo and if update, to set also the date.
Note
This must be called after the addon manager has inserted a new addon with FindAddons() into database.
Parameters
[in] addonId Identifier of addon
[in] repoAddonId Identifier of related repository addon
[in] isUpdate If call becomes done on already installed addon and update only.
Returns
True if successfully done, otherwise false
Currently listed call sources:
CAddonInstallJob::DoWork
References GetAddonInfo(), CDateTime::GetCurrentDateTime(), m_critSection, m_database, and ADDON::UNKNOWN.
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), and EnableSingle().
SortByDependencies()
void ADDON::CAddonMgr::SortByDependencies (VECADDONS & updates) const private
Sort a list of addons for installation, i.e., defines the order of installation depending of each addon dependencies.
Parameters
[in,out] updates the vector of addons to sort
Referenced by InstallAddonUpdates().
UnloadAddon()
bool ADDON::CAddonMgr::UnloadAddon (const std::string & addonId)
Note
: should only be called by AddonInstaller
Unload addon from the system. Returns true if it was unloaded, otherwise false.
References ADDON::CHOICE_NO, GetAddon(), IsAddonInstalled(), CLog::Log(), LOGDEBUG, LOGERROR, m_critSection, m_installedAddons, m_unloadEvents, and ADDON::UNKNOWN.
UnloadEvents()
CEventStream< AddonEvent > & ADDON::CAddonMgr::UnloadEvents () inline
References m_unloadEvents.
Referenced by ADDON::CServiceAddonManager::Start(), ADDON::CServiceAddonManager::Stop(), and ADDON::CServiceAddonManager::~CServiceAddonManager().
UnregisterAddonMgrCallback()
void ADDON::CAddonMgr::UnregisterAddonMgrCallback (AddonType type)
References m_managers.
Referenced by PVR::CPVRClients::~CPVRClients().
UpdateDisabledReason()
bool ADDON::CAddonMgr::UpdateDisabledReason (const std::string & id, AddonDisabledReason newDisabledReason)
Updates reason for a disabled addon. Returns true on success, false on failure.
References id, IsAddonDisabled(), CLog::Log(), LOGDEBUG, m_critSection, m_database, and m_disabled.
Referenced by EnableSingle().
UpdateLastUsed()
void ADDON::CAddonMgr::UpdateLastUsed (const std::string & id)
References GetAddonInfo(), CDateTime::GetCurrentDateTime(), CServiceBroker::GetJobManager(), m_critSection, m_database, m_events, and ADDON::UNKNOWN.
Referenced by CGUIMediaWindow::GetDirectory(), and CGUIMediaWindow::OnClick().
Member Data Documentation
m_critSection
CCriticalSection ADDON::CAddonMgr::m_critSection mutable private
Referenced by AddToUpdateableAddons(), CanAddonBeDisabled(), DisableAddon(), EnableSingle(), FindAddon(), FindAddons(), FindInstallableById(), GetAddon(), GetAddonInfo(), GetAddonInfos(), GetAddonsInternal(), GetAddonsWithAvailableUpdate(), GetCompatibleVersions(), GetDisabledAddonInfos(), GetInstallableAddons(), HasAddons(), HasInstalledAddons(), Init(), IsAddonDisabled(), IsAddonDisabledExcept(), IsAddonDisabledWithReason(), IsOptionalSystemAddon(), IsRequiredSystemAddon(), LoadAddon(), OnPostUnInstall(), ReloadSettings(), RemoveFromUpdateableAddons(), SetAddonOrigin(), UnloadAddon(), UpdateDisabledReason(), and UpdateLastUsed().
m_database
std::unique_ptr<CAddonDatabase> ADDON::CAddonMgr::m_database private
Referenced by AddUpdateRuleToList(), DeInit(), DisableAddon(), EnableSingle(), FindAddon(), FindAddons(), Init(), RemoveAllUpdateRulesFromList(), RemoveUpdateRuleFromList(), SetAddonOrigin(), UpdateDisabledReason(), and UpdateLastUsed().
m_disabled
std::map<std::string, AddonDisabledReason> ADDON::CAddonMgr::m_disabled private
Referenced by DisableAddon(), EnableSingle(), FindAddon(), FindAddons(), GetAddonInfos(), GetDisabledAddonInfos(), IsAddonDisabled(), IsAddonDisabledExcept(), IsAddonDisabledWithReason(), OnPostUnInstall(), and UpdateDisabledReason().
m_events
CEventSource<AddonEvent> ADDON::CAddonMgr::m_events private
Referenced by DisableAddon(), EnableSingle(), Events(), LoadAddon(), OnPostUnInstall(), PublishEventAutoUpdateStateChanged(), PublishInstanceAdded(), PublishInstanceRemoved(), and UpdateLastUsed().
m_installAddonsMutex
std::mutex ADDON::CAddonMgr::m_installAddonsMutex mutable private
Referenced by CheckAndInstallAddonUpdates(), and MigrateAddons().
m_installedAddons
ADDON_INFO_LIST ADDON::CAddonMgr::m_installedAddons private
Referenced by FindAddon(), FindAddons(), GetAddonInfo(), GetAddonInfos(), GetAddonsInternal(), GetDisabledAddonInfos(), HasAddons(), HasInstalledAddons(), and UnloadAddon().
m_lastAvailableUpdatesCountAsString
std::string ADDON::CAddonMgr::m_lastAvailableUpdatesCountAsString mutable private
latest count of available updates
Referenced by GetAvailableUpdates(), and GetLastAvailableUpdatesCountAsString().
m_lastAvailableUpdatesCountMutex
std::mutex ADDON::CAddonMgr::m_lastAvailableUpdatesCountMutex mutable private
Referenced by GetAvailableUpdates(), and GetLastAvailableUpdatesCountAsString().
m_managers
std::map< AddonType, IAddonMgrCallback * > ADDON::CAddonMgr::m_managers static private
Referenced by GetCallbackForType(), RegisterAddonMgrCallback(), and UnregisterAddonMgrCallback().
m_optionalSystemAddons
std::set<std::string> ADDON::CAddonMgr::m_optionalSystemAddons private
Referenced by FindAddons(), Init(), and IsOptionalSystemAddon().
m_systemAddons
std::set<std::string> ADDON::CAddonMgr::m_systemAddons private
Referenced by FindAddons(), Init(), and IsRequiredSystemAddon().
m_tempAddonBasePath
const std::string ADDON::CAddonMgr::m_tempAddonBasePath = "special://temp/addons" private
Referenced by DeInit(), and GetTempAddonBasePath().
m_unloadEvents
CBlockingEventSource<AddonEvent> ADDON::CAddonMgr::m_unloadEvents private
Referenced by LoadAddon(), UnloadAddon(), and UnloadEvents().
m_updateableAddons
VECADDONS ADDON::CAddonMgr::m_updateableAddons private
Referenced by AddToUpdateableAddons(), ReloadSettings(), and RemoveFromUpdateableAddons().
m_updateRules
std::unique_ptr<CAddonUpdateRules> ADDON::CAddonMgr::m_updateRules private
Referenced by AddUpdateRuleToList(), FindAddon(), FindAddons(), IsAutoUpdateable(), RemoveAllUpdateRulesFromList(), and RemoveUpdateRuleFromList().
The documentation for this class was generated from the following files:
AddonManager.h
AddonManager.cpp