Kodi Documentation: CGenericTouchActionHandler Class Reference
CGenericTouchActionHandler Class Reference
Input » Touch » Touch
Generic implementation of ITouchActionHandler to translate touch actions into XBMC specific and mappable actions.
#include <GenericTouchActionHandler.h>
Public Member Functions
void OnTouchAbort () override
A touch action has been aborted.
bool OnSingleTouchStart (float x, float y) override
A single touch has started.
bool OnSingleTouchHold (float x, float y) override
A single touch has been held down for a certain amount of time.
bool OnSingleTouchMove (float x, float y, float offsetX, float offsetY, float velocityX, float velocityY) override
A single touch has moved.
bool OnSingleTouchEnd (float x, float y) override
A single touch has been lifted.
bool OnMultiTouchDown (float x, float y, int32_t pointer) override
An additional touch has been performed.
bool OnMultiTouchHold (float x, float y, int32_t pointers=2) override
Multiple simultaneous touches have been held down for a certain amount of time.
bool OnMultiTouchMove (float x, float y, float offsetX, float offsetY, float velocityX, float velocityY, int32_t pointer) override
A touch has moved.
bool OnMultiTouchUp (float x, float y, int32_t pointer) override
A touch has been lifted (but there are still active touches)
bool OnTouchGestureStart (float x, float y) override
A pan gesture with a single touch has been started.
bool OnTouchGesturePan (float x, float y, float offsetX, float offsetY, float velocityX, float velocityY) override
A pan gesture with a single touch is in progress.
bool OnTouchGestureEnd (float x, float y, float offsetX, float offsetY, float velocityX, float velocityY) override
A pan gesture with a single touch has ended.
void OnTap (float x, float y, int32_t pointers=1) override
A tap with a one or more touches has been performed.
void OnLongPress (float x, float y, int32_t pointers=1) override
One or more touches have been held down for a certain amount of time.
void OnSwipe (TouchMoveDirection direction, float xDown, float yDown, float xUp, float yUp, float velocityX, float velocityY, int32_t pointers=1) override
One or more touches has been moved quickly in a single direction in a short time.
void OnZoomPinch (float centerX, float centerY, float zoomFactor) override
Two simultaneous touches have been held down and moved to perform a zooming/pinching gesture.
void OnRotate (float centerX, float centerY, float angle) override
Two simultaneous touches have been held down and moved to perform a rotating gesture.
int QuerySupportedGestures (float x, float y)
Asks the control at the given coordinates for a list of the supported gestures.
Public Member Functions inherited from ITouchActionHandler
virtual ~ITouchActionHandler ()=default
Static Public Member Functions
static CGenericTouchActionHandler & GetInstance ()
Get an instance of the touch input manager.
Private Member Functions
CGenericTouchActionHandler ()=default
CGenericTouchActionHandler (const CGenericTouchActionHandler &)=delete
CGenericTouchActionHandler const & operator= (CGenericTouchActionHandler const &)=delete
~CGenericTouchActionHandler () override=default
void sendEvent (int actionId, float x, float y, float x2=0.0f, float y2=0.0f, float x3=0.0f, float y3=0.0f, int pointers=1)
void focusControl (float x, float y)
Detailed Description
Generic implementation of ITouchActionHandler to translate touch actions into XBMC specific and mappable actions.
See also
ITouchActionHandler
Constructor & Destructor Documentation
CGenericTouchActionHandler() [1/2]
CGenericTouchActionHandler::CGenericTouchActionHandler () private default
CGenericTouchActionHandler() [2/2]
CGenericTouchActionHandler::CGenericTouchActionHandler (const CGenericTouchActionHandler &) private delete
~CGenericTouchActionHandler()
CGenericTouchActionHandler::~CGenericTouchActionHandler () override private default
Member Function Documentation
focusControl()
void CGenericTouchActionHandler::focusControl (float x, float y) private
References CServiceBroker::GetAppPort(), XBMC_Event::type, and XBMC_SETFOCUS.
Referenced by OnSingleTouchStart().
GetInstance()
CGenericTouchActionHandler & CGenericTouchActionHandler::GetInstance () static
Get an instance of the touch input manager.
Referenced by CAndroidTouch::CAndroidTouch(), CLibInputTouch::CLibInputTouch(), CWinSystemWin10DX::CreateNewWindow(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::InitWindowSystem(), CWinEventsWin32::OnGesture(), CWinEventsWin32::OnGestureNotify(), and CAndroidTouch::onTouchEvent().
OnLongPress()
void CGenericTouchActionHandler::OnLongPress (float x, float y, int32_t pointers = 1) override virtual
One or more touches have been held down for a certain amount of time.
Parameters
x The x coordinate (with sub-pixel) of the touch
y The y coordinate (with sub-pixel) of the touch
pointers The number of pointers involved (default 1)
Returns
True if the event was handled otherwise false
See also
OnSingleTouchHold
Reimplemented from ITouchActionHandler.
References ACTION_TOUCH_LONGPRESS, and sendEvent().
OnMultiTouchDown()
bool CGenericTouchActionHandler::OnMultiTouchDown (float x, float y, int32_t pointer) override virtual
An additional touch has been performed.
Parameters
x The x coordinate (with sub-pixel) of the touch
y The y coordinate (with sub-pixel) of the touch
pointer The pointer that has performed the touch
Returns
True if the event was handled otherwise false
Reimplemented from ITouchActionHandler.
OnMultiTouchHold()
bool CGenericTouchActionHandler::OnMultiTouchHold (float x, float y, int32_t pointers = 2) override virtual
Multiple simultaneous touches have been held down for a certain amount of time.
Parameters
x The x coordinate (with sub-pixel) of the touch
y The y coordinate (with sub-pixel) of the touch
pointers The number of pointers involved (default 2)
Returns
True if the event was handled otherwise false
Reimplemented from ITouchActionHandler.
OnMultiTouchMove()
bool CGenericTouchActionHandler::OnMultiTouchMove (float x, float y, float offsetX, float offsetY, float velocityX, float velocityY, int32_t pointer) override virtual
A touch has moved.
Parameters
x The x coordinate (with sub-pixel) of the current touch
y The y coordinate (with sub-pixel) of the current touch
offsetX The covered distance on the x axis (with sub-pixel)
offsetX The covered distance on the y axis (with sub-pixel)
velocityX The velocity of the gesture in x direction (pixels/second)
velocityX The velocity of the gesture in y direction (pixels/second)
pointer The pointer that has performed the touch
Returns
True if the event was handled otherwise false
Reimplemented from ITouchActionHandler.
OnMultiTouchUp()
bool CGenericTouchActionHandler::OnMultiTouchUp (float x, float y, int32_t pointer) override virtual
A touch has been lifted (but there are still active touches)
Parameters
x The x coordinate (with sub-pixel) of the touch
y The y coordinate (with sub-pixel) of the touch
pointer The pointer that has performed the touch
Returns
True if the event was handled otherwise false
Reimplemented from ITouchActionHandler.
OnRotate()
void CGenericTouchActionHandler::OnRotate (float centerX, float centerY, float angle) override virtual
Two simultaneous touches have been held down and moved to perform a rotating gesture.
Parameters
centerX The x coordinate (with sub-pixel) of the center of the two touches
centerY The y coordinate (with sub-pixel) of the center of the two touches
angle The clockwise angle in degrees of the rotation
Returns
True if the event was handled otherwise false
Reimplemented from ITouchActionHandler.
References ACTION_GESTURE_ROTATE, and sendEvent().
Referenced by CWinEventsWin32::OnGesture().
OnSingleTouchEnd()
bool CGenericTouchActionHandler::OnSingleTouchEnd (float x, float y) override virtual
A single touch has been lifted.
Parameters
x The x coordinate (with sub-pixel) of the touch
y The y coordinate (with sub-pixel) of the touch
Returns
True if the event was handled otherwise false
See also
OnSingleTap
Reimplemented from ITouchActionHandler.
OnSingleTouchHold()
bool CGenericTouchActionHandler::OnSingleTouchHold (float x, float y) override virtual
A single touch has been held down for a certain amount of time.
Parameters
x The x coordinate (with sub-pixel) of the touch
y The y coordinate (with sub-pixel) of the touch
Returns
True if the event was handled otherwise false
See also
OnSingleLongPress
Reimplemented from ITouchActionHandler.
OnSingleTouchMove()
bool CGenericTouchActionHandler::OnSingleTouchMove (float x, float y, float offsetX, float offsetY, float velocityX, float velocityY) override virtual
A single touch has moved.
Parameters
x The x coordinate (with sub-pixel) of the current touch
y The y coordinate (with sub-pixel) of the current touch
offsetX The covered distance on the x axis (with sub-pixel)
offsetX The covered distance on the y axis (with sub-pixel)
velocityX The velocity of the gesture in x direction (pixels/second)
velocityX The velocity of the gesture in y direction (pixels/second)
Returns
True if the event was handled otherwise false
See also
OnTouchGesturePan
Reimplemented from ITouchActionHandler.
OnSingleTouchStart()
bool CGenericTouchActionHandler::OnSingleTouchStart (float x, float y) override virtual
A single touch has started.
Parameters
x The x coordinate (with sub-pixel) of the touch
y The y coordinate (with sub-pixel) of the touch
Returns
True if the event was handled otherwise false
See also
OnSingleTap
Reimplemented from ITouchActionHandler.
References focusControl().
OnSwipe()
void CGenericTouchActionHandler::OnSwipe (TouchMoveDirection direction, float xDown, float yDown, float xUp, float yUp, float velocityX, float velocityY, int32_t pointers = 1) override virtual
One or more touches has been moved quickly in a single direction in a short time.
Parameters
direction The direction (left, right, up, down) of the swipe gesture
xDown The x coordinate (with sub-pixel) of the first touch
yDown The y coordinate (with sub-pixel) of the first touch
xUp The x coordinate (with sub-pixel) of the last touch
yUp The y coordinate (with sub-pixel) of the last touch
velocityX The velocity of the gesture in x direction (pixels/second)
velocityX The velocity of the gesture in y direction (pixels/second)
pointers The number of pointers involved (default 1)
Returns
True if the event was handled otherwise false
Reimplemented from ITouchActionHandler.
References ACTION_GESTURE_SWIPE_DOWN, ACTION_GESTURE_SWIPE_LEFT, ACTION_GESTURE_SWIPE_RIGHT, ACTION_GESTURE_SWIPE_UP, sendEvent(), TouchMoveDirectionDown, TouchMoveDirectionLeft, TouchMoveDirectionRight, and TouchMoveDirectionUp.
OnTap()
void CGenericTouchActionHandler::OnTap (float x, float y, int32_t pointers = 1) override virtual
A tap with a one or more touches has been performed.
Parameters
x The x coordinate (with sub-pixel) of the touch
y The y coordinate (with sub-pixel) of the touch
pointers The number of pointers involved (default 1)
Returns
True if the event was handled otherwise false
Reimplemented from ITouchActionHandler.
References ACTION_TOUCH_TAP, and sendEvent().
Referenced by CWinEventsWin32::OnGesture().
OnTouchAbort()
void CGenericTouchActionHandler::OnTouchAbort () override virtual
A touch action has been aborted.
Reimplemented from ITouchActionHandler.
References ACTION_GESTURE_ABORT, and sendEvent().
OnTouchGestureEnd()
bool CGenericTouchActionHandler::OnTouchGestureEnd (float x, float y, float offsetX, float offsetY, float velocityX, float velocityY) override virtual
A pan gesture with a single touch has ended.
Parameters
x The x coordinate (with sub-pixel) of the current touch
y The y coordinate (with sub-pixel) of the current touch
offsetX The covered distance on the x axis (with sub-pixel)
offsetX The covered distance on the y axis (with sub-pixel)
velocityX The velocity of the gesture in x direction (pixels/second)
velocityX The velocity of the gesture in y direction (pixels/second)
Returns
True if the event was handled otherwise false
Reimplemented from ITouchActionHandler.
References ACTION_GESTURE_END, and sendEvent().
Referenced by CWinEventsWin32::OnGesture().
OnTouchGesturePan()
bool CGenericTouchActionHandler::OnTouchGesturePan (float x, float y, float offsetX, float offsetY, float velocityX, float velocityY) override virtual
A pan gesture with a single touch is in progress.
Parameters
x The x coordinate (with sub-pixel) of the current touch
y The y coordinate (with sub-pixel) of the current touch
offsetX The covered distance on the x axis (with sub-pixel)
offsetX The covered distance on the y axis (with sub-pixel)
velocityX The velocity of the gesture in x direction (pixels/second)
velocityX The velocity of the gesture in y direction (pixels/second)
Returns
True if the event was handled otherwise false
Reimplemented from ITouchActionHandler.
References ACTION_GESTURE_PAN, and sendEvent().
Referenced by CWinEventsWin32::OnGesture().
OnTouchGestureStart()
bool CGenericTouchActionHandler::OnTouchGestureStart (float x, float y) override virtual
A pan gesture with a single touch has been started.
Parameters
x The x coordinate (with sub-pixel) of the initial touch
y The y coordinate (with sub-pixel) of the initial touch
Returns
True if the event was handled otherwise false
Reimplemented from ITouchActionHandler.
References ACTION_GESTURE_BEGIN, and sendEvent().
Referenced by CWinEventsWin32::OnGesture().
OnZoomPinch()
void CGenericTouchActionHandler::OnZoomPinch (float centerX, float centerY, float zoomFactor) override virtual
Two simultaneous touches have been held down and moved to perform a zooming/pinching gesture.
Parameters
centerX The x coordinate (with sub-pixel) of the center of the two touches
centerY The y coordinate (with sub-pixel) of the center of the two touches
zoomFactor The zoom (> 1.0) or pinch (< 1.0) factor of the two touches
Returns
True if the event was handled otherwise false
Reimplemented from ITouchActionHandler.
References ACTION_GESTURE_ZOOM, and sendEvent().
Referenced by CWinEventsWin32::OnGesture().
operator=()
CGenericTouchActionHandler const & CGenericTouchActionHandler::operator= (CGenericTouchActionHandler const &) private delete
QuerySupportedGestures()
int CGenericTouchActionHandler::QuerySupportedGestures (float x, float y)
Asks the control at the given coordinates for a list of the supported gestures.
Parameters
x The x coordinate (with sub-pixel) of the touch
y The y coordinate (with sub-pixel) of the touch
Returns
EVENT_RESULT value of bitwise ORed gestures.
References CServiceBroker::GetGUI(), CGUIMessage::GetPointer(), GUI_MSG_GESTURE_NOTIFY, SendMessage(), and CGUIMessage::SetPointer().
Referenced by CAndroidTouch::onTouchEvent().
sendEvent()
void CGenericTouchActionHandler::sendEvent (int actionId, float x, float y, float x2 = 0.0f, float y2 = 0.0f, float x3 = 0.0f, float y3 = 0.0f, int pointers = 1) private
References CServiceBroker::GetAppPort(), XBMC_Event::type, and XBMC_TOUCH.
Referenced by OnLongPress(), OnRotate(), OnSwipe(), OnTap(), OnTouchAbort(), OnTouchGestureEnd(), OnTouchGesturePan(), OnTouchGestureStart(), and OnZoomPinch().
The documentation for this class was generated from the following files:
GenericTouchActionHandler.h
GenericTouchActionHandler.cpp