Kodi Documentation: kodi::addon::CInstanceScreensaver Class Reference
kodi::addon::CInstanceScreensaver Class Reference
#include <Screensaver.h>
Public Member Functions
CInstanceScreensaver ()
Screensaver class constructor.
CInstanceScreensaver (const IInstanceInfo &instance)
Screensaver class constructor used to support multiple instance types.
~CInstanceScreensaver () override=default
Destructor.
virtual bool Start ()
Used to notify the screensaver that it has been started.
virtual void Stop ()
Used to inform the screensaver that the rendering control was stopped.
virtual void Render ()
Used to indicate when the add-on should render.
kodi::HardwareContext Device ()
Device that represents the display adapter.
int X ()
Returns the X position of the rendering window.
int Y ()
Returns the Y position of the rendering window.
int Width ()
Returns the width of the rendering window.
int Height ()
Returns the height of the rendering window.
float PixelRatio ()
Pixel aspect ratio (often abbreviated PAR) is a ratio that describes how the width of a pixel compares to the height of that pixel.
Public Member Functions inherited from kodi::addon::IAddonInstance
IAddonInstance (const kodi::addon::IInstanceInfo &instance)
virtual ~IAddonInstance ()=default
virtual ADDON_STATUS CreateInstance (const kodi::addon::IInstanceInfo &instance, KODI_ADDON_INSTANCE_HDL &hdl)
std::string GetInstanceAPIVersion () const
virtual ADDON_STATUS SetInstanceSetting (const std::string &settingName, const kodi::addon::CSettingValue &settingValue)
bool IsInstanceSettingUsingDefault (const std::string &settingName)
std::string GetInstanceUserPath (const std::string &append="")
bool CheckInstanceSettingString (const std::string &settingName, std::string &settingValue)
std::string GetInstanceSettingString (const std::string &settingName, const std::string &defaultValue="")
void SetInstanceSettingString (const std::string &settingName, const std::string &settingValue)
bool CheckInstanceSettingInt (const std::string &settingName, int &settingValue)
int GetInstanceSettingInt (const std::string &settingName, int defaultValue=0)
void SetInstanceSettingInt (const std::string &settingName, int settingValue)
bool CheckInstanceSettingBoolean (const std::string &settingName, bool &settingValue)
bool GetInstanceSettingBoolean (const std::string &settingName, bool defaultValue=false)
void SetInstanceSettingBoolean (const std::string &settingName, bool settingValue)
bool CheckInstanceSettingFloat (const std::string &settingName, float &settingValue)
float GetInstanceSettingFloat (const std::string &settingName, float defaultValue=0.0f)
void SetInstanceSettingFloat (const std::string &settingName, float settingValue)
template<typename enumType >
bool CheckInstanceSettingEnum (const std::string &settingName, enumType &settingValue)
template<typename enumType >
enumType GetInstanceSettingEnum (const std::string &settingName, enumType defaultValue=static_cast< enumType >(0))
template<typename enumType >
void SetInstanceSettingEnum (const std::string &settingName, enumType settingValue)
Private Member Functions
void SetAddonStruct (KODI_ADDON_INSTANCE_STRUCT *instance)
Static Private Member Functions
static bool ADDON_start (const KODI_ADDON_SCREENSAVER_HDL hdl)
static void ADDON_stop (const KODI_ADDON_SCREENSAVER_HDL hdl)
static void ADDON_render (const KODI_ADDON_SCREENSAVER_HDL hdl)
Private Attributes
std::shared_ptr< kodi::gui::IRenderHelper > m_renderHelper
KODI_ADDON_SCREENSAVER_PROPS m_props = {}
Member Function Documentation
ADDON_render()
static void kodi::addon::CInstanceScreensaver::ADDON_render (const KODI_ADDON_SCREENSAVER_HDL hdl) inline static private
References m_renderHelper, and Render().
ADDON_start()
static bool kodi::addon::CInstanceScreensaver::ADDON_start (const KODI_ADDON_SCREENSAVER_HDL hdl) inline static private
References kodi::gui::GetRenderHelper(), m_renderHelper, and Start().
ADDON_stop()
static void kodi::addon::CInstanceScreensaver::ADDON_stop (const KODI_ADDON_SCREENSAVER_HDL hdl) inline static private
References m_renderHelper, and Stop().
SetAddonStruct()
void kodi::addon::CInstanceScreensaver::SetAddonStruct (KODI_ADDON_INSTANCE_STRUCT * instance) inline private
References AddonToKodiFuncTable_Screensaver::get_properties, KODI_ADDON_INSTANCE_STRUCT::hdl, KODI_ADDON_INSTANCE_STRUCT::info, KODI_ADDON_INSTANCE_INFO::kodi, KodiToAddonFuncTable_Screensaver::render, KODI_ADDON_INSTANCE_STRUCT::screensaver, KodiToAddonFuncTable_Screensaver::start, KodiToAddonFuncTable_Screensaver::stop, AddonInstance_Screensaver::toAddon, and AddonInstance_Screensaver::toKodi.
Member Data Documentation
m_props
KODI_ADDON_SCREENSAVER_PROPS kodi::addon::CInstanceScreensaver::m_props = {} private
m_renderHelper
std::shared_ptr<kodi::gui::IRenderHelper> kodi::addon::CInstanceScreensaver::m_renderHelper private
Referenced by ADDON_render(), ADDON_start(), and ADDON_stop().
The documentation for this class was generated from the following file:
kodi-dev-kit/include/kodi/addon-instance/ScreenSaver.h