Kodi Documentation: KODI::WINDOWING::WAYLAND::CInputProcessorPointer Class Reference
KODI::WINDOWING::WAYLAND::CInputProcessorPointer Class Reference final
#include <InputProcessorPointer.h>
Public Member Functions
CInputProcessorPointer (wayland::surface_t const &surface, IInputHandlerPointer &handler)
void SetCoordinateScale (std::int32_t scale)
void OnPointerEnter (CSeat *seat, std::uint32_t serial, const wayland::surface_t &surface, double surfaceX, double surfaceY) override
void OnPointerLeave (CSeat *seat, std::uint32_t serial, const wayland::surface_t &surface) override
void OnPointerMotion (CSeat *seat, std::uint32_t time, double surfaceX, double surfaceY) override
void OnPointerButton (CSeat *seat, std::uint32_t serial, std::uint32_t time, std::uint32_t button, wayland::pointer_button_state state) override
void OnPointerAxis (CSeat *seat, std::uint32_t time, wayland::pointer_axis axis, double value) override
Private Member Functions
CInputProcessorPointer (CInputProcessorPointer const &other)=delete
CInputProcessorPointer & operator= (CInputProcessorPointer const &other)=delete
std::uint16_t ConvertMouseCoordinate (double coord) const
void SetMousePosFromSurface (CPointGen< double > position)
void SendMouseMotion ()
void SendMouseButton (unsigned char button, bool pressed)
Private Attributes
wayland::surface_t m_surface
IInputHandlerPointer & m_handler
bool m_pointerOnSurface {}
CPointGen< std::uint16_t > m_pointerPosition
std::int32_t m_coordinateScale {1}
Additional Inherited Members
Protected Member Functions inherited from KODI::WINDOWING::WAYLAND::IRawInputHandlerPointer
~IRawInputHandlerPointer ()=default
Constructor & Destructor Documentation
CInputProcessorPointer() [1/2]
CInputProcessorPointer::CInputProcessorPointer (wayland::surface_t const & surface, IInputHandlerPointer & handler)
CInputProcessorPointer() [2/2]
KODI::WINDOWING::WAYLAND::CInputProcessorPointer::CInputProcessorPointer (CInputProcessorPointer const & other) private delete
Member Function Documentation
ConvertMouseCoordinate()
std::uint16_t CInputProcessorPointer::ConvertMouseCoordinate (double coord) const private
References m_coordinateScale.
Referenced by SetMousePosFromSurface().
OnPointerAxis()
void CInputProcessorPointer::OnPointerAxis (CSeat * seat, std::uint32_t time, wayland::pointer_axis axis, double value) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerPointer.
References m_pointerOnSurface, SendMouseButton(), value, XBMC_BUTTON_WHEELDOWN, and XBMC_BUTTON_WHEELUP.
OnPointerButton()
void CInputProcessorPointer::OnPointerButton (CSeat * seat, std::uint32_t serial, std::uint32_t time, std::uint32_t button, wayland::pointer_button_state state) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerPointer.
References m_pointerOnSurface, and SendMouseButton().
OnPointerEnter()
void CInputProcessorPointer::OnPointerEnter (CSeat * seat, std::uint32_t serial, const wayland::surface_t & surface, double surfaceX, double surfaceY) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerPointer.
References KODI::WINDOWING::WAYLAND::CSeat::GetGlobalName(), m_handler, m_pointerOnSurface, m_surface, KODI::WINDOWING::WAYLAND::IInputHandlerPointer::OnPointerEnter(), SendMouseMotion(), and SetMousePosFromSurface().
OnPointerLeave()
void CInputProcessorPointer::OnPointerLeave (CSeat * seat, std::uint32_t serial, const wayland::surface_t & surface) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerPointer.
References m_handler, m_pointerOnSurface, and KODI::WINDOWING::WAYLAND::IInputHandlerPointer::OnPointerLeave().
OnPointerMotion()
void CInputProcessorPointer::OnPointerMotion (CSeat * seat, std::uint32_t time, double surfaceX, double surfaceY) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IRawInputHandlerPointer.
References m_pointerOnSurface, SendMouseMotion(), and SetMousePosFromSurface().
operator=()
CInputProcessorPointer & KODI::WINDOWING::WAYLAND::CInputProcessorPointer::operator= (CInputProcessorPointer const & other) private delete
SendMouseButton()
void CInputProcessorPointer::SendMouseButton (unsigned char button, bool pressed) private
References m_handler, m_pointerPosition, KODI::WINDOWING::WAYLAND::IInputHandlerPointer::OnPointerEvent(), XBMC_Event::type, CPointGen< T >::x, XBMC_MOUSEBUTTONDOWN, XBMC_MOUSEBUTTONUP, and CPointGen< T >::y.
Referenced by OnPointerAxis(), and OnPointerButton().
SendMouseMotion()
void CInputProcessorPointer::SendMouseMotion () private
References m_handler, m_pointerPosition, KODI::WINDOWING::WAYLAND::IInputHandlerPointer::OnPointerEvent(), XBMC_Event::type, CPointGen< T >::x, XBMC_MOUSEMOTION, and CPointGen< T >::y.
Referenced by OnPointerEnter(), and OnPointerMotion().
SetCoordinateScale()
void KODI::WINDOWING::WAYLAND::CInputProcessorPointer::SetCoordinateScale (std::int32_t scale) inline
References m_coordinateScale.
SetMousePosFromSurface()
void CInputProcessorPointer::SetMousePosFromSurface (CPointGen< double > position) private
References ConvertMouseCoordinate(), m_pointerPosition, CPointGen< T >::x, and CPointGen< T >::y.
Referenced by OnPointerEnter(), and OnPointerMotion().
Member Data Documentation
m_coordinateScale
std::int32_t KODI::WINDOWING::WAYLAND::CInputProcessorPointer::m_coordinateScale {1} private
Referenced by ConvertMouseCoordinate(), and SetCoordinateScale().
m_handler
IInputHandlerPointer& KODI::WINDOWING::WAYLAND::CInputProcessorPointer::m_handler private
Referenced by OnPointerEnter(), OnPointerLeave(), SendMouseButton(), and SendMouseMotion().
m_pointerOnSurface
bool KODI::WINDOWING::WAYLAND::CInputProcessorPointer::m_pointerOnSurface {} private
Referenced by OnPointerAxis(), OnPointerButton(), OnPointerEnter(), OnPointerLeave(), and OnPointerMotion().
m_pointerPosition
CPointGen<std::uint16_t> KODI::WINDOWING::WAYLAND::CInputProcessorPointer::m_pointerPosition private
Referenced by SendMouseButton(), SendMouseMotion(), and SetMousePosFromSurface().
m_surface
wayland::surface_t KODI::WINDOWING::WAYLAND::CInputProcessorPointer::m_surface private
Referenced by OnPointerEnter().
The documentation for this class was generated from the following files:
InputProcessorPointer.h
InputProcessorPointer.cpp