Kodi Documentation: PERIPHERALS::CPeripheralAddonTranslator Class Reference
PERIPHERALS::CPeripheralAddonTranslator Class Reference
#include <PeripheralAddonTranslator.h>
Static Public Member Functions
static const char * TranslateError (PERIPHERAL_ERROR error)
static PeripheralType TranslateType (PERIPHERAL_TYPE type)
static PERIPHERAL_TYPE TranslateType (PeripheralType type)
static KODI::JOYSTICK::CDriverPrimitive TranslatePrimitive (const kodi::addon::DriverPrimitive &primitive)
static kodi::addon::DriverPrimitive TranslatePrimitive (const KODI::JOYSTICK::CDriverPrimitive &primitive)
static std::vector< KODI::JOYSTICK::CDriverPrimitive > TranslatePrimitives (const std::vector< kodi::addon::DriverPrimitive > &primitives)
static std::vector< kodi::addon::DriverPrimitive > TranslatePrimitives (const std::vector< KODI::JOYSTICK::CDriverPrimitive > &primitives)
static KODI::JOYSTICK::HAT_DIRECTION TranslateHatDirection (JOYSTICK_DRIVER_HAT_DIRECTION dir)
static JOYSTICK_DRIVER_HAT_DIRECTION TranslateHatDirection (KODI::JOYSTICK::HAT_DIRECTION dir)
static KODI::JOYSTICK::HAT_STATE TranslateHatState (JOYSTICK_STATE_HAT state)
static KODI::JOYSTICK::SEMIAXIS_DIRECTION TranslateSemiAxisDirection (JOYSTICK_DRIVER_SEMIAXIS_DIRECTION dir)
static JOYSTICK_DRIVER_SEMIAXIS_DIRECTION TranslateSemiAxisDirection (KODI::JOYSTICK::SEMIAXIS_DIRECTION dir)
static KODI::MOUSE::BUTTON_ID TranslateMouseButton (JOYSTICK_DRIVER_MOUSE_INDEX button)
static JOYSTICK_DRIVER_MOUSE_INDEX TranslateMouseButton (KODI::MOUSE::BUTTON_ID button)
static KODI::JOYSTICK::RELATIVE_POINTER_DIRECTION TranslateRelPointerDirection (JOYSTICK_DRIVER_RELPOINTER_DIRECTION dir)
static JOYSTICK_DRIVER_RELPOINTER_DIRECTION TranslateRelPointerDirection (KODI::JOYSTICK::RELATIVE_POINTER_DIRECTION dir)
static KODI::JOYSTICK::FEATURE_TYPE TranslateFeatureType (JOYSTICK_FEATURE_TYPE type)
static JOYSTICK_FEATURE_TYPE TranslateFeatureType (KODI::JOYSTICK::FEATURE_TYPE type)
static kodi::addon::DriverPrimitive Opposite (const kodi::addon::DriverPrimitive &semiaxis)
Member Function Documentation
Opposite()
kodi::addon::DriverPrimitive CPeripheralAddonTranslator::Opposite (const kodi::addon::DriverPrimitive & semiaxis) static
References kodi::addon::DriverPrimitive::Center(), kodi::addon::DriverPrimitive::DriverIndex(), kodi::addon::DriverPrimitive::Range(), and kodi::addon::DriverPrimitive::SemiAxisDirection().
TranslateError()
const char * CPeripheralAddonTranslator::TranslateError (PERIPHERAL_ERROR error) static
References PERIPHERAL_ERROR_CONNECTION_FAILED, PERIPHERAL_ERROR_FAILED, PERIPHERAL_ERROR_INVALID_PARAMETERS, PERIPHERAL_ERROR_NOT_CONNECTED, PERIPHERAL_ERROR_NOT_IMPLEMENTED, PERIPHERAL_ERROR_UNKNOWN, and PERIPHERAL_NO_ERROR.
Referenced by PERIPHERALS::CPeripheralAddon::LogError().
TranslateFeatureType() [1/2]
JOYSTICK::FEATURE_TYPE CPeripheralAddonTranslator::TranslateFeatureType (JOYSTICK_FEATURE_TYPE type) static
References JOYSTICK_FEATURE_TYPE_ABSPOINTER, JOYSTICK_FEATURE_TYPE_ACCELEROMETER, JOYSTICK_FEATURE_TYPE_ANALOG_STICK, JOYSTICK_FEATURE_TYPE_KEY, JOYSTICK_FEATURE_TYPE_MOTOR, JOYSTICK_FEATURE_TYPE_RELPOINTER, JOYSTICK_FEATURE_TYPE_SCALAR, JOYSTICK_FEATURE_TYPE_THROTTLE, and JOYSTICK_FEATURE_TYPE_WHEEL.
Referenced by PERIPHERALS::CPeripheralAddon::FeatureCount(), PERIPHERALS::CPeripheralAddon::FeatureType(), and PERIPHERALS::CAddonButtonMap::GetFeatureType().
TranslateFeatureType() [2/2]
JOYSTICK_FEATURE_TYPE CPeripheralAddonTranslator::TranslateFeatureType (KODI::JOYSTICK::FEATURE_TYPE type) static
References JOYSTICK_FEATURE_TYPE_ABSPOINTER, JOYSTICK_FEATURE_TYPE_ACCELEROMETER, JOYSTICK_FEATURE_TYPE_ANALOG_STICK, JOYSTICK_FEATURE_TYPE_KEY, JOYSTICK_FEATURE_TYPE_MOTOR, JOYSTICK_FEATURE_TYPE_RELPOINTER, JOYSTICK_FEATURE_TYPE_SCALAR, JOYSTICK_FEATURE_TYPE_THROTTLE, JOYSTICK_FEATURE_TYPE_UNKNOWN, and JOYSTICK_FEATURE_TYPE_WHEEL.
TranslateHatDirection() [1/2]
HAT_DIRECTION CPeripheralAddonTranslator::TranslateHatDirection (JOYSTICK_DRIVER_HAT_DIRECTION dir) static
References JOYSTICK_DRIVER_HAT_DOWN, JOYSTICK_DRIVER_HAT_LEFT, JOYSTICK_DRIVER_HAT_RIGHT, and JOYSTICK_DRIVER_HAT_UP.
Referenced by TranslatePrimitive(), and TranslatePrimitive().
TranslateHatDirection() [2/2]
JOYSTICK_DRIVER_HAT_DIRECTION CPeripheralAddonTranslator::TranslateHatDirection (KODI::JOYSTICK::HAT_DIRECTION dir) static
References JOYSTICK_DRIVER_HAT_DOWN, JOYSTICK_DRIVER_HAT_LEFT, JOYSTICK_DRIVER_HAT_RIGHT, JOYSTICK_DRIVER_HAT_UNKNOWN, and JOYSTICK_DRIVER_HAT_UP.
TranslateHatState()
HAT_STATE CPeripheralAddonTranslator::TranslateHatState (JOYSTICK_STATE_HAT state) static
References JOYSTICK_STATE_HAT_DOWN, JOYSTICK_STATE_HAT_LEFT, JOYSTICK_STATE_HAT_RIGHT, and JOYSTICK_STATE_HAT_UP.
Referenced by PERIPHERALS::CPeripheralAddon::ProcessEvents().
TranslateMouseButton() [1/2]
MOUSE::BUTTON_ID CPeripheralAddonTranslator::TranslateMouseButton (JOYSTICK_DRIVER_MOUSE_INDEX button) static
References JOYSTICK_DRIVER_MOUSE_INDEX_BUTTON4, JOYSTICK_DRIVER_MOUSE_INDEX_BUTTON5, JOYSTICK_DRIVER_MOUSE_INDEX_HORIZ_WHEEL_LEFT, JOYSTICK_DRIVER_MOUSE_INDEX_HORIZ_WHEEL_RIGHT, JOYSTICK_DRIVER_MOUSE_INDEX_LEFT, JOYSTICK_DRIVER_MOUSE_INDEX_MIDDLE, JOYSTICK_DRIVER_MOUSE_INDEX_RIGHT, JOYSTICK_DRIVER_MOUSE_INDEX_WHEEL_DOWN, and JOYSTICK_DRIVER_MOUSE_INDEX_WHEEL_UP.
Referenced by TranslatePrimitive(), and TranslatePrimitive().
TranslateMouseButton() [2/2]
JOYSTICK_DRIVER_MOUSE_INDEX CPeripheralAddonTranslator::TranslateMouseButton (KODI::MOUSE::BUTTON_ID button) static
References JOYSTICK_DRIVER_MOUSE_INDEX_BUTTON4, JOYSTICK_DRIVER_MOUSE_INDEX_BUTTON5, JOYSTICK_DRIVER_MOUSE_INDEX_HORIZ_WHEEL_LEFT, JOYSTICK_DRIVER_MOUSE_INDEX_HORIZ_WHEEL_RIGHT, JOYSTICK_DRIVER_MOUSE_INDEX_LEFT, JOYSTICK_DRIVER_MOUSE_INDEX_MIDDLE, JOYSTICK_DRIVER_MOUSE_INDEX_RIGHT, JOYSTICK_DRIVER_MOUSE_INDEX_UNKNOWN, JOYSTICK_DRIVER_MOUSE_INDEX_WHEEL_DOWN, and JOYSTICK_DRIVER_MOUSE_INDEX_WHEEL_UP.
TranslatePrimitive() [1/2]
CDriverPrimitive CPeripheralAddonTranslator::TranslatePrimitive (const kodi::addon::DriverPrimitive & primitive) static
References kodi::addon::DriverPrimitive::Center(), kodi::addon::DriverPrimitive::DriverIndex(), kodi::addon::DriverPrimitive::HatDirection(), JOYSTICK_DRIVER_PRIMITIVE_TYPE_BUTTON, JOYSTICK_DRIVER_PRIMITIVE_TYPE_HAT_DIRECTION, JOYSTICK_DRIVER_PRIMITIVE_TYPE_KEY, JOYSTICK_DRIVER_PRIMITIVE_TYPE_MOTOR, JOYSTICK_DRIVER_PRIMITIVE_TYPE_MOUSE_BUTTON, JOYSTICK_DRIVER_PRIMITIVE_TYPE_RELPOINTER_DIRECTION, JOYSTICK_DRIVER_PRIMITIVE_TYPE_SEMIAXIS, kodi::addon::DriverPrimitive::Keycode(), kodi::addon::DriverPrimitive::MouseIndex(), kodi::addon::DriverPrimitive::Range(), kodi::addon::DriverPrimitive::RelPointerDirection(), kodi::addon::DriverPrimitive::SemiAxisDirection(), TranslateHatDirection(), KODI::KEYBOARD::CKeyboardTranslator::TranslateKeysym(), TranslateMouseButton(), TranslateRelPointerDirection(), TranslateSemiAxisDirection(), and kodi::addon::DriverPrimitive::Type().
Referenced by PERIPHERALS::CAddonButtonMap::AddAccelerometer(), PERIPHERALS::CAddonButtonMap::AddAnalogStick(), PERIPHERALS::CAddonButtonMap::AddKey(), PERIPHERALS::CAddonButtonMap::AddRelativePointer(), PERIPHERALS::CAddonButtonMap::AddScalar(), PERIPHERALS::CAddonButtonMap::AddThrottle(), PERIPHERALS::CAddonButtonMap::AddWheel(), PERIPHERALS::CAddonButtonMap::CreateLookupTable(), PERIPHERALS::CAddonButtonMap::GetAccelerometer(), PERIPHERALS::CAddonButtonMap::GetAnalogStick(), PERIPHERALS::CAddonButtonMap::GetKey(), PERIPHERALS::CAddonButtonMap::GetRelativePointer(), PERIPHERALS::CAddonButtonMap::GetScalar(), PERIPHERALS::CAddonButtonMap::GetThrottle(), and PERIPHERALS::CAddonButtonMap::GetWheel().
TranslatePrimitive() [2/2]
kodi::addon::DriverPrimitive CPeripheralAddonTranslator::TranslatePrimitive (const KODI::JOYSTICK::CDriverPrimitive & primitive) static
References KODI::JOYSTICK::CDriverPrimitive::Center(), kodi::addon::DriverPrimitive::CreateButton(), kodi::addon::DriverPrimitive::CreateMotor(), kodi::addon::DriverPrimitive::CreateMouseButton(), KODI::JOYSTICK::CDriverPrimitive::HatDirection(), KODI::JOYSTICK::CDriverPrimitive::Index(), KODI::JOYSTICK::CDriverPrimitive::Keycode(), KODI::JOYSTICK::CDriverPrimitive::MouseButton(), KODI::JOYSTICK::CDriverPrimitive::PointerDirection(), KODI::JOYSTICK::CDriverPrimitive::Range(), KODI::JOYSTICK::CDriverPrimitive::SemiAxisDirection(), TranslateHatDirection(), KODI::KEYBOARD::CKeyboardTranslator::TranslateKeycode(), TranslateMouseButton(), TranslateRelPointerDirection(), TranslateSemiAxisDirection(), and KODI::JOYSTICK::CDriverPrimitive::Type().
TranslatePrimitives() [1/2]
std::vector< JOYSTICK::CDriverPrimitive > CPeripheralAddonTranslator::TranslatePrimitives (const std::vector< kodi::addon::DriverPrimitive > & primitives) static
Referenced by PERIPHERALS::CAddonButtonMap::Load(), and PERIPHERALS::CAddonButtonMap::SetIgnoredPrimitives().
TranslatePrimitives() [2/2]
std::vector< kodi::addon::DriverPrimitive > CPeripheralAddonTranslator::TranslatePrimitives (const std::vector< KODI::JOYSTICK::CDriverPrimitive > & primitives) static
TranslateRelPointerDirection() [1/2]
RELATIVE_POINTER_DIRECTION CPeripheralAddonTranslator::TranslateRelPointerDirection (JOYSTICK_DRIVER_RELPOINTER_DIRECTION dir) static
References JOYSTICK_DRIVER_RELPOINTER_DOWN, JOYSTICK_DRIVER_RELPOINTER_LEFT, JOYSTICK_DRIVER_RELPOINTER_RIGHT, and JOYSTICK_DRIVER_RELPOINTER_UP.
Referenced by TranslatePrimitive(), and TranslatePrimitive().
TranslateRelPointerDirection() [2/2]
JOYSTICK_DRIVER_RELPOINTER_DIRECTION CPeripheralAddonTranslator::TranslateRelPointerDirection (KODI::JOYSTICK::RELATIVE_POINTER_DIRECTION dir) static
References JOYSTICK_DRIVER_RELPOINTER_DOWN, JOYSTICK_DRIVER_RELPOINTER_LEFT, JOYSTICK_DRIVER_RELPOINTER_RIGHT, JOYSTICK_DRIVER_RELPOINTER_UNKNOWN, and JOYSTICK_DRIVER_RELPOINTER_UP.
TranslateSemiAxisDirection() [1/2]
SEMIAXIS_DIRECTION CPeripheralAddonTranslator::TranslateSemiAxisDirection (JOYSTICK_DRIVER_SEMIAXIS_DIRECTION dir) static
References JOYSTICK_DRIVER_SEMIAXIS_NEGATIVE, and JOYSTICK_DRIVER_SEMIAXIS_POSITIVE.
Referenced by TranslatePrimitive(), and TranslatePrimitive().
TranslateSemiAxisDirection() [2/2]
JOYSTICK_DRIVER_SEMIAXIS_DIRECTION CPeripheralAddonTranslator::TranslateSemiAxisDirection (KODI::JOYSTICK::SEMIAXIS_DIRECTION dir) static
References JOYSTICK_DRIVER_SEMIAXIS_NEGATIVE, JOYSTICK_DRIVER_SEMIAXIS_POSITIVE, and JOYSTICK_DRIVER_SEMIAXIS_UNKNOWN.
TranslateType() [1/2]
PeripheralType CPeripheralAddonTranslator::TranslateType (PERIPHERAL_TYPE type) static
References PERIPHERALS::PERIPHERAL_JOYSTICK, PERIPHERALS::PERIPHERAL_KEYBOARD, PERIPHERALS::PERIPHERAL_MOUSE, PERIPHERAL_TYPE_JOYSTICK, PERIPHERAL_TYPE_KEYBOARD, PERIPHERAL_TYPE_MOUSE, and PERIPHERALS::PERIPHERAL_UNKNOWN.
Referenced by PERIPHERALS::CPeripheralAddon::GetPeripheralInfo().
TranslateType() [2/2]
PERIPHERAL_TYPE CPeripheralAddonTranslator::TranslateType (PeripheralType type) static
References PERIPHERALS::PERIPHERAL_JOYSTICK, PERIPHERALS::PERIPHERAL_KEYBOARD, PERIPHERALS::PERIPHERAL_MOUSE, PERIPHERAL_TYPE_JOYSTICK, PERIPHERAL_TYPE_KEYBOARD, PERIPHERAL_TYPE_MOUSE, and PERIPHERAL_TYPE_UNKNOWN.
The documentation for this class was generated from the following files:
PeripheralAddonTranslator.h
PeripheralAddonTranslator.cpp