Kodi Documentation: CKey Class Reference
CKey Class Reference
Input » Keyboard
#include <Key.h>
Public Types
enum Modifier {
MODIFIER_CTRL = 0x00010000 , MODIFIER_SHIFT = 0x00020000 , MODIFIER_ALT = 0x00040000 , MODIFIER_RALT = 0x00080000 ,
MODIFIER_SUPER = 0x00100000 , MODIFIER_META = 0X00200000 , MODIFIER_LONG = 0X01000000 , MODIFIER_NUMLOCK = 0X02000000 ,
MODIFIER_CAPSLOCK = 0X04000000 , MODIFIER_SCROLLLOCK = 0X08000000
}
Public Member Functions
CKey (void)
CKey (uint32_t buttonCode, uint8_t leftTrigger=0, uint8_t rightTrigger=0, float leftThumbX=0.0f, float leftThumbY=0.0f, float rightThumbX=0.0f, float rightThumbY=0.0f, float repeat=0.0f)
CKey (uint32_t buttonCode, unsigned int held)
CKey (uint32_t keycode, uint8_t vkey, wchar_t unicode, char ascii, uint32_t modifiers, uint32_t lockingModifiers, unsigned int held)
CKey (const CKey &key)
void Reset ()
virtual ~CKey (void)
CKey & operator= (const CKey &key)
uint8_t GetLeftTrigger () const
uint8_t GetRightTrigger () const
float GetLeftThumbX () const
float GetLeftThumbY () const
float GetRightThumbX () const
float GetRightThumbY () const
float GetRepeat () const
bool FromKeyboard () const
bool IsAnalogButton () const
bool IsIRRemote () const
void SetFromService (bool fromService)
bool GetFromService () const
uint32_t GetButtonCode () const
uint32_t GetKeycode () const
uint8_t GetVKey () const
wchar_t GetUnicode () const
char GetAscii () const
uint32_t GetModifiers () const
uint32_t GetLockingModifiers () const
unsigned int GetHeld () const
Private Attributes
uint32_t m_buttonCode
uint32_t m_keycode
uint8_t m_vkey
wchar_t m_unicode
char m_ascii
uint32_t m_modifiers
uint32_t m_lockingModifiers
unsigned int m_held
uint8_t m_leftTrigger
uint8_t m_rightTrigger
float m_leftThumbX
float m_leftThumbY
float m_rightThumbX
float m_rightThumbY
float m_repeat
bool m_fromService
Member Enumeration Documentation
Modifier
enum CKey::Modifier
Enumerator
MODIFIER_CTRL
MODIFIER_SHIFT
MODIFIER_ALT
MODIFIER_RALT
MODIFIER_SUPER
MODIFIER_META
MODIFIER_LONG
MODIFIER_NUMLOCK
MODIFIER_CAPSLOCK
MODIFIER_SCROLLLOCK
Constructor & Destructor Documentation
CKey() [1/5]
CKey::CKey (void)
References Reset().
CKey() [2/5]
CKey::CKey (uint32_t buttonCode, uint8_t leftTrigger = 0, uint8_t rightTrigger = 0, float leftThumbX = 0.0f, float leftThumbY = 0.0f, float rightThumbX = 0.0f, float rightThumbY = 0.0f, float repeat = 0.0f)
References m_buttonCode, m_leftThumbX, m_leftThumbY, m_leftTrigger, m_repeat, m_rightThumbX, m_rightThumbY, m_rightTrigger, and Reset().
CKey() [3/5]
CKey::CKey (uint32_t buttonCode, unsigned int held)
References m_buttonCode, m_held, and Reset().
CKey() [4/5]
CKey::CKey (uint32_t keycode, uint8_t vkey, wchar_t unicode, char ascii, uint32_t modifiers, uint32_t lockingModifiers, unsigned int held)
References KEY_UNICODE, KEY_VKEY, m_ascii, m_buttonCode, m_held, m_keycode, m_lockingModifiers, m_modifiers, m_unicode, m_vkey, and Reset().
CKey() [5/5]
CKey::CKey (const CKey & key)
~CKey()
CKey::~CKey (void) virtual default
Member Function Documentation
FromKeyboard()
bool CKey::FromKeyboard () const
References KEY_INVALID, KEY_VKEY, and m_buttonCode.
Referenced by CInputManager::HandleKey().
GetAscii()
char CKey::GetAscii () const inline
References m_ascii.
GetButtonCode()
uint32_t CKey::GetButtonCode () const inline
References m_buttonCode.
Referenced by CAction::CAction(), KODI::KEYMAP::CButtonTranslator::GetActionCode(), CInputManager::HandleKey(), KODI::KEYMAP::CButtonTranslator::HasLongpressMapping_Internal(), IsAnalogButton(), IsIRRemote(), CInputManager::OnKey(), CInputManager::OnKeyUp(), and KODI::KEYMAP::CButtonStat::TranslateKey().
GetFromService()
bool CKey::GetFromService () const inline
References m_fromService.
Referenced by CInputManager::HandleKey(), and CInputManager::OnKey().
GetHeld()
unsigned int CKey::GetHeld () const inline
References m_held.
Referenced by CAction::CAction(), and KODI::KEYMAP::CButtonStat::TranslateKey().
GetKeycode()
uint32_t CKey::GetKeycode () const inline
References m_keycode.
Referenced by KODI::JOYSTICK::CButtonMapping::OnKeyPress(), KODI::KEYBOARD::CKeyboardInputHandling::OnKeyPress(), and KODI::KEYBOARD::CKeyboardInputHandling::OnKeyRelease().
GetLeftThumbX()
float CKey::GetLeftThumbX () const
References m_leftThumbX.
Referenced by CAction::CAction().
GetLeftThumbY()
float CKey::GetLeftThumbY () const
References m_leftThumbY.
Referenced by CAction::CAction().
GetLeftTrigger()
uint8_t CKey::GetLeftTrigger () const
References m_leftTrigger.
Referenced by CAction::CAction().
GetLockingModifiers()
uint32_t CKey::GetLockingModifiers () const inline
References m_lockingModifiers.
Referenced by KODI::KEYBOARD::CKeyboardInputHandling::OnKeyPress(), and KODI::KEYBOARD::CKeyboardInputHandling::OnKeyRelease().
GetModifiers()
uint32_t CKey::GetModifiers () const inline
References m_modifiers.
Referenced by CInputManager::HandleKey(), KODI::KEYBOARD::CKeyboardInputHandling::OnKeyPress(), and KODI::KEYBOARD::CKeyboardInputHandling::OnKeyRelease().
GetRepeat()
float CKey::GetRepeat () const
References m_repeat.
Referenced by CAction::CAction().
GetRightThumbX()
float CKey::GetRightThumbX () const
References m_rightThumbX.
Referenced by CAction::CAction().
GetRightThumbY()
float CKey::GetRightThumbY () const
References m_rightThumbY.
Referenced by CAction::CAction().
GetRightTrigger()
uint8_t CKey::GetRightTrigger () const
References m_rightTrigger.
Referenced by CAction::CAction().
GetUnicode()
wchar_t CKey::GetUnicode () const inline
References m_unicode.
Referenced by CAction::CAction(), CInputManager::HandleKey(), KODI::KEYBOARD::CKeyboardInputHandling::OnKeyPress(), and KODI::KEYBOARD::CKeyboardInputHandling::OnKeyRelease().
GetVKey()
uint8_t CKey::GetVKey () const inline
References m_vkey.
Referenced by CInputManager::HandleKey(), and KODI::KEYBOARD::CKeyboardEasterEgg::OnKeyPress().
IsAnalogButton()
bool CKey::IsAnalogButton () const
References GetButtonCode().
Referenced by CInputManager::HandleKey().
IsIRRemote()
bool CKey::IsIRRemote () const
References GetButtonCode().
operator=()
CKey & CKey::operator= (const CKey & key)
References m_ascii, m_buttonCode, m_fromService, m_held, m_keycode, m_leftThumbX, m_leftThumbY, m_leftTrigger, m_lockingModifiers, m_modifiers, m_repeat, m_rightThumbX, m_rightThumbY, m_rightTrigger, m_unicode, and m_vkey.
Reset()
void CKey::Reset ()
References KEY_INVALID, m_ascii, m_buttonCode, m_fromService, m_held, m_keycode, m_leftThumbX, m_leftThumbY, m_leftTrigger, m_lockingModifiers, m_modifiers, m_repeat, m_rightThumbX, m_rightThumbY, m_rightTrigger, m_unicode, and m_vkey.
Referenced by CKey(), CKey(), CKey(), CKey(), CInputManager::OnKey(), and CInputManager::OnKeyUp().
SetFromService()
void CKey::SetFromService (bool fromService)
References KEY_VKEY, m_buttonCode, m_fromService, and m_unicode.
Referenced by CInputManager::ProcessEventServer().
Member Data Documentation
m_ascii
char CKey::m_ascii private
Referenced by CKey(), GetAscii(), operator=(), and Reset().
m_buttonCode
uint32_t CKey::m_buttonCode private
Referenced by CKey(), CKey(), CKey(), FromKeyboard(), GetButtonCode(), operator=(), Reset(), and SetFromService().
m_fromService
bool CKey::m_fromService private
Referenced by GetFromService(), operator=(), Reset(), and SetFromService().
m_held
unsigned int CKey::m_held private
Referenced by CKey(), CKey(), GetHeld(), operator=(), and Reset().
m_keycode
uint32_t CKey::m_keycode private
Referenced by CKey(), GetKeycode(), operator=(), and Reset().
m_leftThumbX
float CKey::m_leftThumbX private
Referenced by CKey(), GetLeftThumbX(), operator=(), and Reset().
m_leftThumbY
float CKey::m_leftThumbY private
Referenced by CKey(), GetLeftThumbY(), operator=(), and Reset().
m_leftTrigger
uint8_t CKey::m_leftTrigger private
Referenced by CKey(), GetLeftTrigger(), operator=(), and Reset().
m_lockingModifiers
uint32_t CKey::m_lockingModifiers private
Referenced by CKey(), GetLockingModifiers(), operator=(), and Reset().
m_modifiers
uint32_t CKey::m_modifiers private
Referenced by CKey(), GetModifiers(), operator=(), and Reset().
m_repeat
float CKey::m_repeat private
Referenced by CKey(), GetRepeat(), operator=(), and Reset().
m_rightThumbX
float CKey::m_rightThumbX private
Referenced by CKey(), GetRightThumbX(), operator=(), and Reset().
m_rightThumbY
float CKey::m_rightThumbY private
Referenced by CKey(), GetRightThumbY(), operator=(), and Reset().
m_rightTrigger
uint8_t CKey::m_rightTrigger private
Referenced by CKey(), GetRightTrigger(), operator=(), and Reset().
m_unicode
wchar_t CKey::m_unicode private
Referenced by CKey(), GetUnicode(), operator=(), Reset(), and SetFromService().
m_vkey
uint8_t CKey::m_vkey private
Referenced by CKey(), GetVKey(), operator=(), and Reset().
The documentation for this class was generated from the following files:
Key.h
Key.cpp