Kodi Documentation: VideoClassifyTest Struct Reference
VideoClassifyTest Struct Reference
Public Member Functions
VideoClassifyTest (const std::string &path, bool res=true, const std::string &mime="", int tag_type=0)
Public Attributes
CFileItem item
bool result
Constructor & Destructor Documentation
VideoClassifyTest()
VideoClassifyTest::VideoClassifyTest (const std::string & path, bool res = true, const std::string & mime = "", int tag_type = 0) inline
References CFileItem::GetGameInfoTag(), CFileItem::GetMusicInfoTag(), CFileItem::GetPictureInfoTag(), CFileItem::GetVideoInfoTag(), item, CVideoInfoTag::m_strFileNameAndPath, KODI::GAME::CGameInfoTag::SetGameClient(), CPictureInfoTag::SetInfo(), CFileItem::SetMimeType(), and MUSIC_INFO::CMusicInfoTag::SetPlayCount().
Member Data Documentation
item
CFileItem VideoClassifyTest::item
Referenced by VideoClassifyTest().
result
bool VideoClassifyTest::result
The documentation for this struct was generated from the following file:
TestVideoFileItemClassify.cpp