Kodi Documentation: KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS Class Reference
KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS Class Reference
#include <WinSystemWaylandWebOS.h>
Public Member Functions
bool InitWindowSystem () override
std::string GetExportedWindowName ()
bool SetExportedWindow (CRect orig, CRect src, CRect dest)
bool SupportsExportedWindow ()
IShellSurface * CreateShellSurface (const std::string &name) override
bool CreateNewWindow (const std::string &name, bool fullScreen, RESOLUTION_INFO &res) override
~CWinSystemWaylandWebOS () noexcept override
bool HasCursor () override
void OnConfigure (std::uint32_t serial, CSizeInt size, IShellSurface::StateBitset state) override
Public Member Functions inherited from KODI::WINDOWING::WAYLAND::CWinSystemWayland
CWinSystemWayland ()
~CWinSystemWayland () noexcept override
const std::string GetName () override
bool DestroyWindowSystem () override
bool DestroyWindow () override
bool ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override
bool SetFullScreen (bool fullScreen, RESOLUTION_INFO &res, bool blankOtherDisplays) override
void FinishModeChange (RESOLUTION res) override
void FinishWindowResize (int newWidth, int newHeight) override
bool UseLimitedColor () override
void UpdateResolutions () override
bool CanDoWindowed () override
bool Minimize () override
void ShowOSMouse (bool show) override
std::string GetClipboardText () override
float GetSyncOutputRefreshRate ()
float GetDisplayLatency () override
Get average display latency.
float GetFrameLatencyAdjustment () override
Get time that should be subtracted from the display latency for this frame in milliseconds.
std::unique_ptr< CVideoSync > GetVideoSync (CVideoReferenceClock *clock) override
void Register (IDispResource *resource) override
void Unregister (IDispResource *resource) override
CSignalRegistration RegisterOnPresentationFeedback (const PresentationFeedbackHandler &handler)
std::vector< std::string > GetConnectedOutputs () override
bool MessagePump () override
Public Member Functions inherited from CWinSystemBase
CWinSystemBase ()
virtual ~CWinSystemBase ()
virtual CRenderSystemBase * GetRenderSystem ()
virtual bool DisplayHardwareScalingEnabled ()
virtual void UpdateDisplayHardwareScaling (const RESOLUTION_INFO &resInfo)
virtual bool MoveWindow (int topLeft, int topRight)
virtual bool CenterWindow ()
virtual bool IsCreated ()
virtual void NotifyAppFocusChange (bool bGaining)
virtual void NotifyAppActiveChange (bool bActivated)
virtual bool HasInertialGestures ()
virtual int NoOfBuffers ()
virtual void ForceFullScreen (const RESOLUTION_INFO &resInfo)
Forces the window to fullscreen provided the window resolution.
virtual bool Restore ()
virtual bool Hide ()
virtual bool Show (bool raise=true)
virtual void OnMove (int x, int y)
virtual unsigned int GetScreenId (const std::string &screen)
Get the screen ID provided the screen name.
virtual void MoveToScreen (unsigned int screenIdx)
Window was requested to move to the given screen.
virtual void OnChangeScreen (unsigned int screenIdx)
Used to signal the windowing system about the change of the current screen.
KODI::WINDOWING::COSScreenSaverManager * GetOSScreenSaver ()
Get OS screen saver inhibit implementation if available.
unsigned int GetWidth ()
unsigned int GetHeight ()
bool IsFullScreen ()
virtual bool SupportsScreenMove ()
Check if the windowing system supports moving windows across screens.
void SetWindowResolution (int width, int height)
std::vector< RESOLUTION_WHR > ScreenResolutions (float refreshrate)
std::vector< REFRESHRATE > RefreshRates (int width, int height, uint32_t dwFlags)
REFRESHRATE DefaultRefreshRate (const std::vector< REFRESHRATE > &rates)
virtual bool HasCalibration (const RESOLUTION_INFO &resInfo)
void RegisterRenderLoop (IRenderLoop *client)
void UnregisterRenderLoop (IRenderLoop *client)
void DriveRenderLoop ()
virtual CGraphicContext & GetGfxContext () const
virtual void * GetHWContext ()
Get OS specific hardware context.
std::shared_ptr< CDPMSSupport > GetDPMSManager ()
virtual bool SetHDR (const VideoPicture *videoPicture)
Set the HDR metadata. Passing nullptr as the parameter should disable HDR.
virtual bool IsHDRDisplay ()
virtual HDR_STATUS ToggleHDR ()
virtual HDR_STATUS GetOSHDRStatus ()
virtual CHDRCapabilities GetDisplayHDRCapabilities () const
virtual float GetGuiSdrPeakLuminance () const
virtual bool HasSystemSdrPeakLuminance ()
virtual bool SupportsVideoSuperResolution ()
System supports Video Super Resolution HW upscaler i.e.: "NVIDIA RTX Video Super Resolution" or "Intel Video Super Resolution".
virtual DEBUG_INFO_RENDER GetDebugInfo ()
Gets debug info from video renderer for use in "Debug Info OSD" (Alt + O)
bool IsHDRDisplaySettingEnabled ()
Return true when HDR display is available and enabled in settings.
bool IsVideoSuperResolutionSettingEnabled ()
Return true when "Video Super Resolution" is supported and enabled in settings.
bool IsHighPrecisionProcessingSettingEnabled ()
Return true when setting "High Precision Processing" is enabled.
std::pair< bool, int > GetDitherSettings ()
Get dither settings.
virtual bool BindTextureUploadContext ()
Binds a shared context to the current thread, in order to upload textures asynchronously.
virtual bool UnbindTextureUploadContext ()
Unbinds the shared context.
virtual bool HasContext ()
Checks if a graphics context is already bound to the current thread.
Public Member Functions inherited from KODI::WINDOWING::WAYLAND::IInputHandler
virtual ~IInputHandler ()=default
Public Member Functions inherited from KODI::WINDOWING::WAYLAND::IWindowDecorationHandler
virtual ~IWindowDecorationHandler ()=default
Public Member Functions inherited from KODI::WINDOWING::WAYLAND::IShellSurfaceHandler
virtual ~IShellSurfaceHandler ()=default
Protected Member Functions
std::unique_ptr< KODI::WINDOWING::IOSScreenSaver > GetOSScreenSaverImpl () override
std::unique_ptr< CSeat > CreateSeat (std::uint32_t name, wayland::seat_t &seat) override
Protected Member Functions inherited from KODI::WINDOWING::WAYLAND::CWinSystemWayland
CSizeInt GetBufferSize () const
std::unique_ptr< CConnection > const & GetConnection ()
wayland::surface_t GetMainSurface ()
IShellSurface * GetShellSurface ()
void PrepareFramePresentation ()
void FinishFramePresentation ()
virtual void SetContextSize (CSizeInt size)=0
void OnClose () override
Protected Member Functions inherited from CWinSystemBase
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, float refreshRate, uint32_t dwFlags)
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, int screenWidth, int screenHeight, float refreshRate, uint32_t dwFlags)
Private Member Functions
bool OnAppLifecycleEvent (LSHandle *sh, LSMessage *reply)
Static Private Member Functions
static bool OnAppLifecycleEventWrapper (LSHandle *sh, LSMessage *reply, void *ctx)
Private Attributes
std::unique_ptr< CRegistry > m_webosRegistry
std::string m_exportedWindowName
wayland::compositor_t m_compositor
wayland::webos_exported_t m_exportedSurface
wayland::webos_foreign_t m_webosForeign
std::unique_ptr< HContext, int(*)(HContext *)> m_requestContext
Additional Inherited Members
Public Types inherited from KODI::WINDOWING::WAYLAND::CWinSystemWayland
using PresentationFeedbackHandler = std::function< void(timespec, std::uint32_t, std::uint32_t, float, std::uint64_t)>
Static Public Member Functions inherited from CWinSystemBase
static std::unique_ptr< CWinSystemBase > CreateWinSystem ()
Static Public Attributes inherited from CWinSystemBase
static const char * SETTING_WINSYSTEM_IS_HDR_DISPLAY = "winsystem.ishdrdisplay"
Protected Attributes inherited from CWinSystemBase
int m_nWidth = 0
int m_nHeight = 0
int m_nTop = 0
int m_nLeft = 0
bool m_bWindowCreated = false
bool m_bFullScreen = false
bool m_bBlankOtherDisplay = false
float m_fRefreshRate = 0.0f
std::unique_ptr< KODI::WINDOWING::COSScreenSaverManager > m_screenSaverManager
CCriticalSection m_renderLoopSection
std::vector< IRenderLoop * > m_renderLoopClients
std::unique_ptr< IWinEvents > m_winEvents
std::unique_ptr< CGraphicContext > m_gfxContext
std::shared_ptr< CDPMSSupport > m_dpms
Constructor & Destructor Documentation
~CWinSystemWaylandWebOS()
KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::~CWinSystemWaylandWebOS () override noexcept
References m_exportedSurface, m_webosForeign, and m_webosRegistry.
Member Function Documentation
CreateNewWindow()
bool KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::CreateNewWindow (const std::string & name, bool fullScreen, RESOLUTION_INFO & res) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::CWinSystemWayland.
References KODI::WINDOWING::WAYLAND::CWinSystemWayland::CreateNewWindow(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::GetMainSurface(), CLog::Log(), LOGDEBUG, m_exportedSurface, m_exportedWindowName, m_webosForeign, and name.
CreateSeat()
std::unique_ptr< CSeat > KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::CreateSeat (std::uint32_t name, wayland::seat_t & seat) override protected virtual
Reimplemented from KODI::WINDOWING::WAYLAND::CWinSystemWayland.
References KODI::WINDOWING::WAYLAND::CWinSystemWayland::GetConnection(), and name.
CreateShellSurface()
IShellSurface * KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::CreateShellSurface (const std::string & name) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::CWinSystemWayland.
References CCompileInfo::GetAppName(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::GetConnection(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::GetMainSurface(), and name.
GetExportedWindowName()
std::string KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::GetExportedWindowName ()
Gets the exported window name. May return an empty string on non wayland-webos-foreign devices (pre webOS 5)
Returns
Exported window name
References m_exportedWindowName.
GetOSScreenSaverImpl()
std::unique_ptr< KODI::WINDOWING::IOSScreenSaver > KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::GetOSScreenSaverImpl () override protected virtual
Reimplemented from KODI::WINDOWING::WAYLAND::CWinSystemWayland.
HasCursor()
bool KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::HasCursor () override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::CWinSystemWayland.
InitWindowSystem()
bool KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::InitWindowSystem () override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::CWinSystemWayland.
References KODI::WINDOWING::WAYLAND::CWinSystemWayland::GetConnection(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::InitWindowSystem(), LOGWARNING, m_compositor, m_requestContext, m_webosForeign, m_webosRegistry, OnAppLifecycleEventWrapper(), CAESinkStarfish::Register(), CDVDVideoCodecStarfish::Register(), and CRendererStarfish::Register().
OnAppLifecycleEvent()
bool KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::OnAppLifecycleEvent (LSHandle * sh, LSMessage * reply) private
References KODI::WINDOWING::WAYLAND::CWinSystemWayland::GetShellSurface(), CLog::Log(), LOGDEBUG, CJSONVariantParser::Parse(), and KODI::WINDOWING::WAYLAND::IShellSurface::SetFullScreen().
Referenced by OnAppLifecycleEventWrapper().
OnAppLifecycleEventWrapper()
bool KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::OnAppLifecycleEventWrapper (LSHandle * sh, LSMessage * reply, void * ctx) static private
References OnAppLifecycleEvent().
Referenced by InitWindowSystem().
OnConfigure()
void KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::OnConfigure (std::uint32_t serial, CSizeInt size, IShellSurface::StateBitset state) override virtual
Reimplemented from KODI::WINDOWING::WAYLAND::CWinSystemWayland.
References ACTION_STOP, CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::OnConfigure(), TMSG_GUI_ACTION, and WINDOW_INVALID.
SetExportedWindow()
bool KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::SetExportedWindow (CRect orig, CRect src, CRect dest)
Sets up the an exported window for display. The display engine will merge the exported window with the UI layer. Therefore any UI element must be transparent for the exported window to punch through. Not available on non wayland-webos-foreign devices (pre webOS 5)
Parameters
src Original source window rect (video size)
src Source window rect crop window
dst Destination rect
Returns
True on success, else false
References CRectGen< T >::Height(), LOGINFO, m_compositor, m_exportedSurface, m_webosForeign, CRectGen< T >::Width(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CRendererStarfish::ManageRenderArea().
SupportsExportedWindow()
bool KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::SupportsExportedWindow ()
References m_webosForeign.
Member Data Documentation
m_compositor
wayland::compositor_t KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::m_compositor private
Referenced by InitWindowSystem(), and SetExportedWindow().
m_exportedSurface
wayland::webos_exported_t KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::m_exportedSurface private
Referenced by CreateNewWindow(), SetExportedWindow(), and ~CWinSystemWaylandWebOS().
m_exportedWindowName
std::string KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::m_exportedWindowName private
Referenced by CreateNewWindow(), and GetExportedWindowName().
m_requestContext
std::unique_ptr<HContext, int (*)(HContext*)> KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::m_requestContext private
Initial value:
{new HContext(),
                                                                 HUnregisterServiceCallback}
Referenced by InitWindowSystem().
m_webosForeign
wayland::webos_foreign_t KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::m_webosForeign private
Referenced by CreateNewWindow(), InitWindowSystem(), SetExportedWindow(), SupportsExportedWindow(), and ~CWinSystemWaylandWebOS().
m_webosRegistry
std::unique_ptr<CRegistry> KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::m_webosRegistry private
Referenced by InitWindowSystem(), and ~CWinSystemWaylandWebOS().
The documentation for this class was generated from the following files:
WinSystemWaylandWebOS.h
WinSystemWaylandWebOS.cpp