Kodi Documentation: ADDON::CAddonSettings Class Reference
ADDON::CAddonSettings Class Reference
#include <AddonSettings.h>
Classes
struct ConditionExpression
Public Member Functions
CAddonSettings (const std::shared_ptr< IAddon > &addon, AddonInstanceId instanceId)
~CAddonSettings () override=default
bool Initialize () override
Initializes the setting system with the generic settings definition and platform specific setting definitions.
bool Load () override
Loads the setting values.
bool Save () override
Saves the setting values.
std::shared_ptr< CSetting > CreateSetting (const std::string &settingType, const std::string &settingId, CSettingsManager *settingsManager=nullptr) const override
Creates a new setting of the given custom setting type.
void OnSettingAction (const std::shared_ptr< const CSetting > &setting) override
The given setting has been activated.
const std::string & GetAddonId () const
bool Initialize (const CXBMCTinyXML &doc, bool allowEmpty=false)
bool Load (const CXBMCTinyXML &doc)
bool Save (CXBMCTinyXML &doc) const
bool HasSettings () const
std::string GetSettingLabel (int label) const
std::shared_ptr< CSetting > AddSetting (const std::string &settingId, bool value)
std::shared_ptr< CSetting > AddSetting (const std::string &settingId, int value)
std::shared_ptr< CSetting > AddSetting (const std::string &settingId, double value)
std::shared_ptr< CSetting > AddSetting (const std::string &settingId, const std::string &value)
Public Member Functions inherited from CSettingControlCreator
std::shared_ptr< ISettingControl > CreateControl (const std::string &controlType) const override
Creates a new setting control of the given custom setting control type.
Public Member Functions inherited from ISettingControlCreator
virtual ~ISettingControlCreator ()=default
Public Member Functions inherited from CSettingCreator
std::shared_ptr< CSetting > CreateSetting (const std::string &settingType, const std::string &settingId, CSettingsManager *settingsManager=nullptr) const override
Creates a new setting of the given custom setting type.
Public Member Functions inherited from ISettingCreator
virtual ~ISettingCreator ()=default
Public Member Functions inherited from CSettingsBase
virtual ~CSettingsBase ()
CSettingsManager * GetSettingsManager () const
virtual bool IsInitialized () const
Returns whether the settings system has been initialized or not.
virtual void SetLoaded ()
Tells the settings system that all setting values have been loaded.
virtual bool IsLoaded () const
Returns whether the settings system has been loaded or not.
virtual void Unload ()
Unloads the previously loaded setting values.
virtual void Uninitialize ()
Uninitializes the settings system.
void RegisterCallback (ISettingCallback *callback, const std::set< std::string > &settingList)
Registers the given ISettingCallback implementation for the given set of settings.
void UnregisterCallback (ISettingCallback *callback)
Unregisters the given ISettingCallback implementation.
std::shared_ptr< CSetting > GetSetting (const std::string &id) const
Gets the setting with the given identifier.
std::vector< std::shared_ptr< CSettingSection > > GetSections () const
Gets the full list of setting sections.
std::shared_ptr< CSettingSection > GetSection (const std::string &section) const
Gets the setting section with the given identifier.
bool GetBool (const std::string &id) const
Gets the boolean value of the setting with the given identifier.
int GetInt (const std::string &id) const
Gets the integer value of the setting with the given identifier.
double GetNumber (const std::string &id) const
Gets the real number value of the setting with the given identifier.
std::string GetString (const std::string &id) const
Gets the string value of the setting with the given identifier.
std::vector< CVariant > GetList (const std::string &id) const
Gets the values of the list setting with the given identifier.
bool SetBool (const std::string &id, bool value)
Sets the boolean value of the setting with the given identifier.
bool ToggleBool (const std::string &id)
Toggles the boolean value of the setting with the given identifier.
bool SetInt (const std::string &id, int value)
Sets the integer value of the setting with the given identifier.
bool SetNumber (const std::string &id, double value)
Sets the real number value of the setting with the given identifier.
bool SetString (const std::string &id, const std::string &value)
Sets the string value of the setting with the given identifier.
bool SetList (const std::string &id, const std::vector< CVariant > &value)
Sets the values of the list setting with the given identifier.
bool SetDefault (const std::string &id)
Sets the value of the setting with the given identifier to its default.
void SetDefaults ()
Sets the value of all settings to their default.
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingChanged (const std::shared_ptr< const CSetting > &setting)
The value of the given setting has changed.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Protected Member Functions
void InitializeSettingTypes () override
void InitializeControls () override
void InitializeConditions () override
bool InitializeDefinitions () override
Protected Member Functions inherited from CSettingControlCreator
CSettingControlCreator ()=default
~CSettingControlCreator () override=default
Protected Member Functions inherited from CSettingCreator
CSettingCreator ()=default
~CSettingCreator () override=default
Protected Member Functions inherited from CSettingsBase
CSettingsBase ()
virtual void InitializeOptionFillers ()
virtual void UninitializeOptionFillers ()
virtual void UninitializeConditions ()
virtual void InitializeVisibility ()
virtual void InitializeDefaults ()
virtual void InitializeISettingsHandlers ()
virtual void UninitializeISettingsHandlers ()
virtual void InitializeISubSettings ()
virtual void UninitializeISubSettings ()
virtual void InitializeISettingCallbacks ()
virtual void UninitializeISettingCallbacks ()
bool InitializeDefinitionsFromXml (const CXBMCTinyXML &xml)
bool LoadValuesFromXml (const CXBMCTinyXML &xml, bool &updated)
Loads setting values from the given document in XML format.
bool SaveValuesToXml (CXBMCTinyXML &xml) const
Saves the setting values in XML format to the given document.
bool LoadValuesFromXml (const TiXmlElement *root, bool &updated)
Loads setting values from the given XML element.
bool LoadHiddenValuesFromXml (const TiXmlElement *root)
Loads hidden setting values from the given XML element.
Private Member Functions
bool AddInstanceSettings ()
bool InitializeDefinitions (const CXBMCTinyXML &doc)
bool ParseSettingVersion (const CXBMCTinyXML &doc, uint32_t &version) const
std::shared_ptr< CSettingGroup > ParseOldSettingElement (const TiXmlElement *categoryElement, const std::shared_ptr< CSettingCategory > &category, std::set< std::string > &settingIds)
std::shared_ptr< CSettingCategory > ParseOldCategoryElement (uint32_t &categoryId, const TiXmlElement *categoryElement, std::set< std::string > &settingIds)
bool InitializeFromOldSettingDefinitions (const CXBMCTinyXML &doc)
std::shared_ptr< CSetting > InitializeFromOldSettingAction (const std::string &settingId, const TiXmlElement *settingElement, const std::string &defaultValue)
std::shared_ptr< CSetting > InitializeFromOldSettingLabel ()
std::shared_ptr< CSetting > InitializeFromOldSettingBool (const std::string &settingId, const TiXmlElement *settingElement, const std::string &defaultValue)
std::shared_ptr< CSetting > InitializeFromOldSettingTextIpAddress (const std::string &settingId, const std::string &settingType, const TiXmlElement *settingElement, const std::string &defaultValue, const int settingLabel)
std::shared_ptr< CSetting > InitializeFromOldSettingNumber (const std::string &settingId, const TiXmlElement *settingElement, const std::string &defaultValue, const int settingLabel)
std::shared_ptr< CSetting > InitializeFromOldSettingPath (const std::string &settingId, const std::string &settingType, const TiXmlElement *settingElement, const std::string &defaultValue, const int settingLabel)
std::shared_ptr< CSetting > InitializeFromOldSettingDate (const std::string &settingId, const TiXmlElement *settingElement, const std::string &defaultValue, const int settingLabel)
std::shared_ptr< CSetting > InitializeFromOldSettingTime (const std::string &settingId, const TiXmlElement *settingElement, const std::string &defaultValue, const int settingLabel)
std::shared_ptr< CSetting > InitializeFromOldSettingSelect (const std::string &settingId, const TiXmlElement *settingElement, const std::string &defaultValue, const int settingLabel, const std::string &settingValues, const std::vector< std::string > &settingLValues)
std::shared_ptr< CSetting > InitializeFromOldSettingAddon (const std::string &settingId, const TiXmlElement *settingElement, const std::string &defaultValue, const int settingLabel)
std::shared_ptr< CSetting > InitializeFromOldSettingEnums (const std::string &settingId, const std::string &settingType, const TiXmlElement *settingElement, const std::string &defaultValue, const std::string &settingValues, const std::vector< std::string > &settingLValues)
std::shared_ptr< CSetting > InitializeFromOldSettingFileEnum (const std::string &settingId, const TiXmlElement *settingElement, const std::string &defaultValue, const std::string &settingValues)
std::shared_ptr< CSetting > InitializeFromOldSettingRangeOfNum (const std::string &settingId, const TiXmlElement *settingElement, const std::string &defaultValue)
std::shared_ptr< CSetting > InitializeFromOldSettingSlider (const std::string &settingId, const TiXmlElement *settingElement, const std::string &defaultValue)
std::shared_ptr< CSetting > InitializeFromOldSettingFileWithSource (const std::string &settingId, const TiXmlElement *settingElement, const std::string &defaultValue, std::string source)
bool LoadOldSettingValues (const CXBMCTinyXML &doc, std::map< std::string, std::string > &settings) const
bool ParseOldLabel (const TiXmlElement *element, const std::string &settingId, int &labelId)
bool ParseOldCondition (const std::shared_ptr< const CSetting > &setting, const std::vector< std::shared_ptr< const CSetting > > &settings, const std::string &condition, CSettingDependency &dependeny) const
Static Private Member Functions
static bool ParseOldConditionExpression (std::string str, ConditionExpression &expression)
static void FileEnumSettingOptionsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
Private Attributes
const std::string m_addonId
const std::string m_addonPath
const std::string m_addonProfile
const AddonInstanceId m_instanceId {ADDON_SETTINGS_ID}
std::weak_ptr< IAddon > m_addon
uint32_t m_unidentifiedSettingId = 0
int m_unknownSettingLabelId
std::map< int, std::string > m_unknownSettingLabels
Logger m_logger
Additional Inherited Members
Protected Attributes inherited from CSettingsBase
bool m_initialized = false
CSettingsManager * m_settingsManager
CCriticalSection m_critical
Constructor & Destructor Documentation
CAddonSettings()
ADDON::CAddonSettings::CAddonSettings (const std::shared_ptr< IAddon > & addon, AddonInstanceId instanceId)
~CAddonSettings()
ADDON::CAddonSettings::~CAddonSettings () override default
Member Function Documentation
AddInstanceSettings()
bool ADDON::CAddonSettings::AddInstanceSettings () private
References ADDON::ADDON_SETTING_INSTANCE_ENABLED_VALUE, ADDON::ADDON_SETTING_INSTANCE_GROUP, ADDON::ADDON_SETTING_INSTANCE_NAME_VALUE, CSettingsBase::GetSetting(), CSettingsBase::GetSettingsManager(), CLog::Log(), LOGDEBUG, m_addonId, and name.
Referenced by Initialize().
AddSetting() [1/4]
std::shared_ptr< CSetting > ADDON::CAddonSettings::AddSetting (const std::string & settingId, bool value)
References m_logger, and value.
AddSetting() [2/4]
std::shared_ptr< CSetting > ADDON::CAddonSettings::AddSetting (const std::string & settingId, const std::string & value)
References m_logger, and value.
AddSetting() [3/4]
std::shared_ptr< CSetting > ADDON::CAddonSettings::AddSetting (const std::string & settingId, double value)
References m_logger, and value.
AddSetting() [4/4]
std::shared_ptr< CSetting > ADDON::CAddonSettings::AddSetting (const std::string & settingId, int value)
References m_logger, and value.
CreateSetting()
std::shared_ptr< CSetting > ADDON::CAddonSettings::CreateSetting (const std::string & settingType, const std::string & settingId, CSettingsManager * settingsManager = nullptr) const override virtual
Creates a new setting of the given custom setting type.
Parameters
settingType string representation of the setting type
settingId Identifier of the setting to be created
settingsManager Reference to the settings manager
Returns
A new setting object of the given (custom) setting type or nullptr if the setting type is unknown
Implements ISettingCreator.
References CSettingCreator::CreateSetting().
FileEnumSettingOptionsFiller()
void ADDON::CAddonSettings::FileEnumSettingOptionsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static private
References XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::CDirectory::GetDirectory(), and CServiceBroker::GetFileExtensionProvider().
Referenced by InitializeFromOldSettingFileWithSource().
GetAddonId()
const std::string & ADDON::CAddonSettings::GetAddonId () const inline
References m_addonId.
Referenced by anonymous_namespace{AddonSettings.cpp}::AddSettingWithoutDefinition().
GetSettingLabel()
std::string ADDON::CAddonSettings::GetSettingLabel (int label) const
References label, m_unknownSettingLabelId, and m_unknownSettingLabels.
HasSettings()
bool ADDON::CAddonSettings::HasSettings () const
References CSettingsBase::GetSettingsManager(), CSettingsManager::HasSettings(), and CSettingsBase::IsInitialized().
Initialize() [1/2]
bool ADDON::CAddonSettings::Initialize () inline override virtual
Initializes the setting system with the generic settings definition and platform specific setting definitions.
Returns
True if the initialization was successful, false otherwise
Reimplemented from CSettingsBase.
Referenced by anonymous_namespace{AddonSettings.cpp}::AddSettingWithoutDefinition().
Initialize() [2/2]
bool ADDON::CAddonSettings::Initialize (const CXBMCTinyXML & doc, bool allowEmpty = false)
References AddInstanceSettings(), CSettingsBase::GetSettingsManager(), InitializeConditions(), InitializeControls(), InitializeDefinitions(), InitializeSettingTypes(), CSettingsBase::m_critical, CSettingsBase::m_initialized, m_instanceId, and CSettingsManager::SetInitialized().
InitializeConditions()
void ADDON::CAddonSettings::InitializeConditions () override protected virtual
Reimplemented from CSettingsBase.
References CSettingsManager::AddCondition(), CSettingsManager::AddDynamicCondition(), CSettingsBase::GetSettingsManager(), CSettingConditions::GetSimpleConditions(), and CSettingConditions::Initialize().
Referenced by Initialize().
InitializeControls()
void ADDON::CAddonSettings::InitializeControls () override protected virtual
Reimplemented from CSettingsBase.
References CSettingsBase::GetSettingsManager(), and CSettingsManager::RegisterSettingControl().
Referenced by Initialize().
InitializeDefinitions() [1/2]
bool ADDON::CAddonSettings::InitializeDefinitions () inline override protected virtual
Implements CSettingsBase.
Referenced by Initialize().
InitializeDefinitions() [2/2]
bool ADDON::CAddonSettings::InitializeDefinitions (const CXBMCTinyXML & doc) private
References CSettingsBase::InitializeDefinitionsFromXml(), InitializeFromOldSettingDefinitions(), m_logger, and ParseSettingVersion().
InitializeFromOldSettingAction()
SettingPtr ADDON::CAddonSettings::InitializeFromOldSettingAction (const std::string & settingId, const TiXmlElement * settingElement, const std::string & defaultValue) private
References XMLUtils::GetAttribute(), CSettingsBase::GetSettingsManager(), m_addonId, m_addonPath, and m_unidentifiedSettingId.
Referenced by ParseOldSettingElement().
InitializeFromOldSettingAddon()
SettingPtr ADDON::CAddonSettings::InitializeFromOldSettingAddon (const std::string & settingId, const TiXmlElement * settingElement, const std::string & defaultValue, const int settingLabel) private
References XMLUtils::GetAttribute(), CSettingsBase::GetSettingsManager(), m_logger, ADDON::CAddonInfo::TranslateType(), and ADDON::UNKNOWN.
Referenced by ParseOldSettingElement().
InitializeFromOldSettingBool()
SettingPtr ADDON::CAddonSettings::InitializeFromOldSettingBool (const std::string & settingId, const TiXmlElement * settingElement, const std::string & defaultValue) private
References CSettingsBase::GetSettingsManager().
Referenced by ParseOldSettingElement().
InitializeFromOldSettingDate()
SettingPtr ADDON::CAddonSettings::InitializeFromOldSettingDate (const std::string & settingId, const TiXmlElement * settingElement, const std::string & defaultValue, const int settingLabel) private
References CSettingsBase::GetSettingsManager().
Referenced by ParseOldSettingElement().
InitializeFromOldSettingDefinitions()
bool ADDON::CAddonSettings::InitializeFromOldSettingDefinitions (const CXBMCTinyXML & doc) private
References CSettingsManager::AddSection(), CSettingsBase::GetSettingsManager(), m_addonId, m_logger, ParseOldCategoryElement(), and root.
Referenced by InitializeDefinitions().
InitializeFromOldSettingEnums()
SettingPtr ADDON::CAddonSettings::InitializeFromOldSettingEnums (const std::string & settingId, const std::string & settingType, const TiXmlElement * settingElement, const std::string & defaultValue, const std::string & settingValues, const std::vector< std::string > & settingLValues) private
References Ascending, g_langInfo, g_localizeStrings, CLocalizeStrings::GetAddonString(), XMLUtils::GetAttribute(), CSettingsBase::GetSettingsManager(), label, m_addonId, value, and values.
Referenced by ParseOldSettingElement().
InitializeFromOldSettingFileEnum()
SettingPtr ADDON::CAddonSettings::InitializeFromOldSettingFileEnum (const std::string & settingId, const TiXmlElement * settingElement, const std::string & defaultValue, const std::string & settingValues) private
References InitializeFromOldSettingFileWithSource().
Referenced by ParseOldSettingElement().
InitializeFromOldSettingFileWithSource()
SettingPtr ADDON::CAddonSettings::InitializeFromOldSettingFileWithSource (const std::string & settingId, const TiXmlElement * settingElement, const std::string & defaultValue, std::string source) private
References URIUtils::AddFileToFolder(), FileEnumSettingOptionsFiller(), XMLUtils::GetAttribute(), CSettingsBase::GetSettingsManager(), m_addonPath, and m_addonProfile.
Referenced by InitializeFromOldSettingFileEnum(), and InitializeFromOldSettingSelect().
InitializeFromOldSettingLabel()
std::shared_ptr< CSetting > ADDON::CAddonSettings::InitializeFromOldSettingLabel () private
References CSettingsBase::GetSettingsManager(), and m_unidentifiedSettingId.
Referenced by ParseOldSettingElement().
InitializeFromOldSettingNumber()
SettingPtr ADDON::CAddonSettings::InitializeFromOldSettingNumber (const std::string & settingId, const TiXmlElement * settingElement, const std::string & defaultValue, const int settingLabel) private
References CSettingsBase::GetSettingsManager().
Referenced by ParseOldSettingElement().
InitializeFromOldSettingPath()
SettingPtr ADDON::CAddonSettings::InitializeFromOldSettingPath (const std::string & settingId, const std::string & settingType, const TiXmlElement * settingElement, const std::string & defaultValue, const int settingLabel) private
References XMLUtils::GetAttribute(), CServiceBroker::GetFileExtensionProvider(), CFileExtensionProvider::GetMusicExtensions(), CFileExtensionProvider::GetPictureExtensions(), CSettingsBase::GetSettingsManager(), and CFileExtensionProvider::GetVideoExtensions().
Referenced by ParseOldSettingElement().
InitializeFromOldSettingRangeOfNum()
SettingPtr ADDON::CAddonSettings::InitializeFromOldSettingRangeOfNum (const std::string & settingId, const TiXmlElement * settingElement, const std::string & defaultValue) private
References CSettingsBase::GetSettingsManager().
Referenced by ParseOldSettingElement().
InitializeFromOldSettingSelect()
SettingPtr ADDON::CAddonSettings::InitializeFromOldSettingSelect (const std::string & settingId, const TiXmlElement * settingElement, const std::string & defaultValue, const int settingLabel, const std::string & settingValues, const std::vector< std::string > & settingLValues) private
References XMLUtils::GetAttribute(), CSettingsBase::GetSettingsManager(), InitializeFromOldSettingFileWithSource(), m_logger, value, and values.
Referenced by ParseOldSettingElement().
InitializeFromOldSettingSlider()
SettingPtr ADDON::CAddonSettings::InitializeFromOldSettingSlider (const std::string & settingId, const TiXmlElement * settingElement, const std::string & defaultValue) private
References XMLUtils::GetAttribute(), CSettingsBase::GetSettingsManager(), m_logger, max, and min.
Referenced by ParseOldSettingElement().
InitializeFromOldSettingTextIpAddress()
SettingPtr ADDON::CAddonSettings::InitializeFromOldSettingTextIpAddress (const std::string & settingId, const std::string & settingType, const TiXmlElement * settingElement, const std::string & defaultValue, const int settingLabel) private
References XMLUtils::GetAttribute(), and CSettingsBase::GetSettingsManager().
Referenced by ParseOldSettingElement().
InitializeFromOldSettingTime()
SettingPtr ADDON::CAddonSettings::InitializeFromOldSettingTime (const std::string & settingId, const TiXmlElement * settingElement, const std::string & defaultValue, const int settingLabel) private
References CSettingsBase::GetSettingsManager().
Referenced by ParseOldSettingElement().
InitializeSettingTypes()
void ADDON::CAddonSettings::InitializeSettingTypes () override protected virtual
Reimplemented from CSettingsBase.
References CSettingsBase::GetSettingsManager(), and CSettingsManager::RegisterSettingType().
Referenced by Initialize().
Load() [1/2]
bool ADDON::CAddonSettings::Load () inline override virtual
Loads the setting values.
Returns
True if the setting values are successfully loaded, false otherwise
Implements CSettingsBase.
Load() [2/2]
bool ADDON::CAddonSettings::Load (const CXBMCTinyXML & doc)
References CSettingsBase::GetSetting(), id, LoadOldSettingValues(), CSettingsBase::LoadValuesFromXml(), CSettingsBase::m_critical, CSettingsBase::m_initialized, m_logger, ParseSettingVersion(), and CSettingsBase::SetLoaded().
LoadOldSettingValues()
bool ADDON::CAddonSettings::LoadOldSettingValues (const CXBMCTinyXML & doc, std::map< std::string, std::string > & settings) const private
References id, and value.
Referenced by Load().
OnSettingAction()
void ADDON::CAddonSettings::OnSettingAction (const std::shared_ptr< const CSetting > & setting) override virtual
The given setting has been activated.
This callback is triggered whenever the given setting has been activated. This callback is only fired for CSettingAction settings.
Parameters
setting The setting which has been activated.
Reimplemented from ISettingCallback.
References Action, CServiceBroker::GetAppMessenger(), m_addonId, m_addonPath, CGUIDialogAddonSettings::SaveAndClose(), and TMSG_EXECUTE_BUILT_IN.
ParseOldCategoryElement()
std::shared_ptr< CSettingCategory > ADDON::CAddonSettings::ParseOldCategoryElement (uint32_t & categoryId, const TiXmlElement * categoryElement, std::set< std::string > & settingIds) private
References g_localizeStrings, CLocalizeStrings::Get(), CSettingsBase::GetSettingsManager(), ParseOldLabel(), and ParseOldSettingElement().
Referenced by InitializeFromOldSettingDefinitions().
ParseOldCondition()
bool ADDON::CAddonSettings::ParseOldCondition (const std::shared_ptr< const CSetting > & setting, const std::vector< std::shared_ptr< const CSetting > > & settings, const std::string & condition, CSettingDependency & dependeny) const private
References CSettingDependency::And(), CSettingsBase::GetSettingsManager(), m_logger, ADDON::CAddonSettings::ConditionExpression::m_negated, ADDON::CAddonSettings::ConditionExpression::m_operator, ADDON::CAddonSettings::ConditionExpression::m_relativeSettingIndex, ADDON::CAddonSettings::ConditionExpression::m_value, CSettingDependency::Or(), ParseOldConditionExpression(), Static, StaticTranslatable, and String.
Referenced by ParseOldSettingElement().
ParseOldConditionExpression()
bool ADDON::CAddonSettings::ParseOldConditionExpression (std::string str, ConditionExpression & expression) static private
References Equals, GreaterThan, LessThan, ADDON::CAddonSettings::ConditionExpression::m_negated, ADDON::CAddonSettings::ConditionExpression::m_operator, ADDON::CAddonSettings::ConditionExpression::m_relativeSettingIndex, and ADDON::CAddonSettings::ConditionExpression::m_value.
Referenced by ParseOldCondition().
ParseOldLabel()
bool ADDON::CAddonSettings::ParseOldLabel (const TiXmlElement * element, const std::string & settingId, int & labelId) private
References m_unknownSettingLabelId, and m_unknownSettingLabels.
Referenced by ParseOldCategoryElement(), and ParseOldSettingElement().
ParseOldSettingElement()
std::shared_ptr< CSettingGroup > ADDON::CAddonSettings::ParseOldSettingElement (const TiXmlElement * categoryElement, const std::shared_ptr< CSettingCategory > & category, std::set< std::string > & settingIds) private
References Basic, Enable, XMLUtils::GetAttribute(), CSettingsBase::GetSettingsManager(), InitializeFromOldSettingAction(), InitializeFromOldSettingAddon(), InitializeFromOldSettingBool(), InitializeFromOldSettingDate(), InitializeFromOldSettingEnums(), InitializeFromOldSettingFileEnum(), InitializeFromOldSettingLabel(), InitializeFromOldSettingNumber(), InitializeFromOldSettingPath(), InitializeFromOldSettingRangeOfNum(), InitializeFromOldSettingSelect(), InitializeFromOldSettingSlider(), InitializeFromOldSettingTextIpAddress(), InitializeFromOldSettingTime(), Internal, m_logger, m_unknownSettingLabelId, m_unknownSettingLabels, ParseOldCondition(), ParseOldLabel(), and Visible.
Referenced by ParseOldCategoryElement().
ParseSettingVersion()
bool ADDON::CAddonSettings::ParseSettingVersion (const CXBMCTinyXML & doc, uint32_t & version) const private
References CSettingsBase::GetSettingsManager(), m_logger, CSettingsManager::ParseVersion(), root, and SETTING_XML_ROOT.
Referenced by InitializeDefinitions(), and Load().
Save() [1/2]
bool ADDON::CAddonSettings::Save () override virtual
Saves the setting values.
Returns
True if the setting values were successfully saved, false otherwise
Implements CSettingsBase.
References m_addon.
Save() [2/2]
bool ADDON::CAddonSettings::Save (CXBMCTinyXML & doc) const
References CSettingsBase::m_critical, CSettingsBase::m_initialized, m_logger, and CSettingsBase::SaveValuesToXml().
Member Data Documentation
m_addon
std::weak_ptr<IAddon> ADDON::CAddonSettings::m_addon private
Referenced by Save().
m_addonId
const std::string ADDON::CAddonSettings::m_addonId private
Referenced by AddInstanceSettings(), GetAddonId(), InitializeFromOldSettingAction(), InitializeFromOldSettingDefinitions(), InitializeFromOldSettingEnums(), and OnSettingAction().
m_addonPath
const std::string ADDON::CAddonSettings::m_addonPath private
Referenced by InitializeFromOldSettingAction(), InitializeFromOldSettingFileWithSource(), and OnSettingAction().
m_addonProfile
const std::string ADDON::CAddonSettings::m_addonProfile private
Referenced by InitializeFromOldSettingFileWithSource().
m_instanceId
const AddonInstanceId ADDON::CAddonSettings::m_instanceId {ADDON_SETTINGS_ID} private
Referenced by Initialize().
m_logger
Logger ADDON::CAddonSettings::m_logger private
Referenced by AddSetting(), AddSetting(), AddSetting(), AddSetting(), InitializeDefinitions(), InitializeFromOldSettingAddon(), InitializeFromOldSettingDefinitions(), InitializeFromOldSettingSelect(), InitializeFromOldSettingSlider(), Load(), ParseOldCondition(), ParseOldSettingElement(), ParseSettingVersion(), and Save().
m_unidentifiedSettingId
uint32_t ADDON::CAddonSettings::m_unidentifiedSettingId = 0 private
Referenced by InitializeFromOldSettingAction(), and InitializeFromOldSettingLabel().
m_unknownSettingLabelId
int ADDON::CAddonSettings::m_unknownSettingLabelId private
Referenced by GetSettingLabel(), ParseOldLabel(), and ParseOldSettingElement().
m_unknownSettingLabels
std::map<int, std::string> ADDON::CAddonSettings::m_unknownSettingLabels private
Referenced by GetSettingLabel(), ParseOldLabel(), and ParseOldSettingElement().
The documentation for this class was generated from the following files:
AddonSettings.h
AddonSettings.cpp