Kodi Documentation: JSONRPC::CJSONUtils Class Reference
JSONRPC::CJSONUtils Class Reference
Interfaces » JSON-RPC
Helper class containing utility methods to handle json rpc method calls.
#include <JSONUtils.h>
Static Public Member Functions
static void MillisecondsToTimeObject (int time, CVariant &result)
Static Protected Member Functions
static void HandleLimits (const CVariant &parameterObject, CVariant &result, int size, int &start, int &end)
static bool ParseSorting (const CVariant &parameterObject, SortBy &sortBy, SortOrder &sortOrder, SortAttribute &sortAttributes)
static void ParseLimits (const CVariant &parameterObject, int &limitStart, int &limitEnd)
static bool ParameterExists (const CVariant &parameterObject, const std::string &key, unsigned int position)
Checks if the given object contains a parameter.
static bool IsValueMember (const CVariant &value, const std::string &key)
Checks if the given object contains a value with the given key.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position)
Returns the json value of a parameter.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position, const CVariant &fallback)
Returns the json value of a parameter or the given default value.
static std::string GetString (const CVariant &value, const char *defaultValue)
Returns the given json value as a string.
static TransportLayerCapability StringToTransportLayer (const std::string &transport)
Returns a TransportLayerCapability value of the given string representation.
static JSONSchemaType StringToSchemaValueType (const std::string &valueType)
Returns a JSONSchemaType value for the given string representation.
static std::string SchemaValueTypeToString (JSONSchemaType valueType)
Returns a string representation for the given JSONSchemaType.
static void SchemaValueTypeToJson (JSONSchemaType valueType, CVariant &jsonObject)
Converts the given json schema type into a json object.
static const char * ValueTypeToString (CVariant::VariantType valueType)
static bool IsParameterType (const CVariant &parameterObject, const char *key, unsigned int position, JSONSchemaType valueType)
Checks if the parameter with the given name or at the given position is of a certain type.
static bool IsType (const CVariant &value, JSONSchemaType valueType)
Checks if the given json value is of the given type.
static void SetDefaultValue (CVariant &value, JSONSchemaType valueType)
Sets the value of the given json value to the default value of the given type.
static bool HasType (JSONSchemaType typeObject, JSONSchemaType type)
static bool ParameterNotNull (const CVariant &parameterObject, const std::string &key)
static void CopyStringArray (const CVariant &jsonStringArray, std::vector< std::string > &stringArray)
Copies the values from the jsonStringArray to the stringArray. stringArray is cleared.
static void SetFromDBDate (const CVariant &jsonDate, CDateTime &date)
static void SetFromDBDateTime (const CVariant &jsonDate, CDateTime &date)
static bool GetXspFiltering (const std::string &type, const CVariant &filter, std::string &xsp)
Detailed Description
Helper class containing utility methods to handle json rpc method calls.
Member Function Documentation
CopyStringArray()
static void JSONRPC::CJSONUtils::CopyStringArray (const CVariant & jsonStringArray, std::vector< std::string > & stringArray) inline static protected
Copies the values from the jsonStringArray to the stringArray. stringArray is cleared.
Parameters
jsonStringArray JSON object representing a string array
stringArray String array where the values are copied into (cleared)
References CVariant::begin_array(), CVariant::end_array(), and CVariant::isArray().
Referenced by JSONRPC::CAudioLibrary::SetAlbumDetails(), JSONRPC::CAudioLibrary::SetArtistDetails(), JSONRPC::CAudioLibrary::SetSongDetails(), and JSONRPC::CVideoLibrary::UpdateVideoTagField().
GetParameter() [1/2]
static CVariant JSONRPC::CJSONUtils::GetParameter (const CVariant & parameterObject, const std::string & key, unsigned int position) inline static protected
Returns the json value of a parameter.
Parameters
parameterObject Object containing all provided parameters
key Possible name of the parameter
position Possible position of the parameter
Returns
Json value of the parameter with the given name or at the given position
Returns the value of the parameter with the given key (if the given object is not an array) or of the parameter at the given position (if the given object is an array).
References IsValueMember().
Referenced by JSONRPC::JsonRpcMethod::checkParameter().
GetParameter() [2/2]
static CVariant JSONRPC::CJSONUtils::GetParameter (const CVariant & parameterObject, const std::string & key, unsigned int position, const CVariant & fallback) inline static protected
Returns the json value of a parameter or the given default value.
Parameters
parameterObject Object containing all provided parameters
key Possible name of the parameter
position Possible position of the parameter
fallback Default value of the parameter
Returns
Json value of the parameter with the given name or at the given position or the default value if the parameter does not exist
Returns the value of the parameter with the given key (if the given object is not an array) or of the parameter at the given position (if the given object is an array). If the parameter does not exist the given default value is returned.
References CVariant::isArray(), IsValueMember(), and CVariant::size().
GetString()
static std::string JSONRPC::CJSONUtils::GetString (const CVariant & value, const char * defaultValue) inline static protected
Returns the given json value as a string.
Parameters
value Json value to convert to a string
defaultValue Default string value
Returns
String value of the given json value or the default value if the given json value is no string
References value.
Referenced by JSONRPC::CJSONServiceDescription::addMethod(), JSONRPC::CJSONServiceDescription::AddNotification(), JSONRPC::JsonRpcMethod::Parse(), JSONRPC::JSONSchemaTypeDefinition::Parse(), and JSONRPC::JsonRpcMethod::parseParameter().
GetXspFiltering()
static bool JSONRPC::CJSONUtils::GetXspFiltering (const std::string & type, const CVariant & filter, std::string & xsp) inline static protected
References CVariant::isMember(), CVariant::isObject(), playlist, CVariant::push_back(), CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
Referenced by JSONRPC::CAudioLibrary::GetAlbums(), JSONRPC::CAudioLibrary::GetArtists(), JSONRPC::CVideoLibrary::GetEpisodes(), JSONRPC::CVideoLibrary::GetMovies(), JSONRPC::CVideoLibrary::GetMusicVideos(), JSONRPC::CAudioLibrary::GetSongs(), and JSONRPC::CVideoLibrary::GetTVShows().
HandleLimits()
static void JSONRPC::CJSONUtils::HandleLimits (const CVariant & parameterObject, CVariant & result, int size, int & start, int & end) inline static protected
References end().
Referenced by JSONRPC::CAddonsOperations::GetAddons(), JSONRPC::CAudioLibrary::GetAlbums(), JSONRPC::CAudioLibrary::GetArtists(), JSONRPC::CPVROperations::GetChannelGroups(), JSONRPC::CPVROperations::GetClients(), JSONRPC::CFavouritesOperations::GetFavourites(), JSONRPC::CAudioLibrary::GetSongs(), and JSONRPC::CFileItemHandler::HandleFileItemList().
HasType()
static bool JSONRPC::CJSONUtils::HasType (JSONSchemaType typeObject, JSONSchemaType type) inline static protected
Referenced by JSONRPC::JSONSchemaTypeDefinition::Check(), JSONRPC::CJSONServiceDescription::getReferencedTypes(), IsType(), JSONRPC::JSONSchemaTypeDefinition::Parse(), JSONRPC::JSONSchemaTypeDefinition::Print(), SchemaValueTypeToJson(), and SchemaValueTypeToString().
IsParameterType()
static bool JSONRPC::CJSONUtils::IsParameterType (const CVariant & parameterObject, const char * key, unsigned int position, JSONSchemaType valueType) inline static protected
Checks if the parameter with the given name or at the given position is of a certain type.
Parameters
parameterObject Object containing all provided parameters
key Possible name of the parameter
position Possible position of the parameter
valueType Expected type of the parameter
Returns
True if the specific parameter is of the given type otherwise false
References JSONRPC::AnyValue, CVariant::isArray(), IsType(), IsValueMember(), and CVariant::size().
IsType()
static bool JSONRPC::CJSONUtils::IsType (const CVariant & value, JSONSchemaType valueType) inline static protected
Checks if the given json value is of the given type.
Parameters
value Json value to check
valueType Expected type of the json value
Returns
True if the given json value is of the given type otherwise false
References JSONRPC::AnyValue, JSONRPC::ArrayValue, JSONRPC::BooleanValue, HasType(), JSONRPC::IntegerValue, JSONRPC::NumberValue, JSONRPC::ObjectValue, JSONRPC::StringValue, and value.
Referenced by JSONRPC::JSONSchemaTypeDefinition::Check(), IsParameterType(), and JSONRPC::JSONSchemaTypeDefinition::Parse().
IsValueMember()
static bool JSONRPC::CJSONUtils::IsValueMember (const CVariant & value, const std::string & key) inline static protected
Checks if the given object contains a value with the given key.
Parameters
value Value to check for the member
key Key of the member to check for
Returns
True if the given object contains a member with the given key otherwise false
References value.
Referenced by GetParameter(), GetParameter(), IsParameterType(), and ParameterExists().
MillisecondsToTimeObject()
static void JSONRPC::CJSONUtils::MillisecondsToTimeObject (int time, CVariant & result) inline static
Referenced by JSONRPC::CPlayerOperations::GetPropertyValue(), and CApplication::OnMessage().
ParameterExists()
static bool JSONRPC::CJSONUtils::ParameterExists (const CVariant & parameterObject, const std::string & key, unsigned int position) inline static protected
Checks if the given object contains a parameter.
Parameters
parameterObject Object to check for a parameter
key Possible name of the parameter
position Possible position of the parameter
Returns
True if the parameter is available otherwise false
Checks the given object for a parameter with the given key (if the given object is not an array) or for a parameter at the given position (if the given object is an array).
References CVariant::isArray(), IsValueMember(), and CVariant::size().
Referenced by JSONRPC::JsonRpcMethod::checkParameter().
ParameterNotNull()
static bool JSONRPC::CJSONUtils::ParameterNotNull (const CVariant & parameterObject, const std::string & key) inline static protected
References CVariant::isMember(), and CVariant::isNull().
Referenced by JSONRPC::CFavouritesOperations::AddFavourite(), JSONRPC::CAudioLibrary::SetAlbumDetails(), JSONRPC::CAudioLibrary::SetArtistDetails(), JSONRPC::CVideoLibrary::SetSeasonDetails(), JSONRPC::CAudioLibrary::SetSongDetails(), JSONRPC::CVideoLibrary::UpdateVideoTag(), and JSONRPC::CVideoLibrary::UpdateVideoTagField().
ParseLimits()
static void JSONRPC::CJSONUtils::ParseLimits (const CVariant & parameterObject, int & limitStart, int & limitEnd) inline static protected
Referenced by JSONRPC::CAudioLibrary::GetAlbums(), JSONRPC::CAudioLibrary::GetArtists(), JSONRPC::CVideoLibrary::GetEpisodes(), JSONRPC::CVideoLibrary::GetMovies(), JSONRPC::CVideoLibrary::GetMusicVideos(), JSONRPC::CAudioLibrary::GetSongs(), and JSONRPC::CVideoLibrary::GetTVShows().
ParseSorting()
static bool JSONRPC::CJSONUtils::ParseSorting (const CVariant & parameterObject, SortBy & sortBy, SortOrder & sortOrder, SortAttribute & sortAttributes) inline static protected
References CVariant::asString(), SortAttributeIgnoreArticle, SortAttributeNone, SortAttributeUseArtistSortName, SortUtils::SortMethodFromString(), SortUtils::SortOrderFromString(), and SortOrderNone.
Referenced by JSONRPC::CAudioLibrary::GetAlbums(), JSONRPC::CAudioLibrary::GetArtists(), JSONRPC::CVideoLibrary::GetEpisodes(), JSONRPC::CVideoLibrary::GetMovies(), JSONRPC::CVideoLibrary::GetMusicVideos(), JSONRPC::CAudioLibrary::GetSongs(), JSONRPC::CVideoLibrary::GetTVShows(), and JSONRPC::CFileItemHandler::Sort().
SchemaValueTypeToJson()
static void JSONRPC::CJSONUtils::SchemaValueTypeToJson (JSONSchemaType valueType, CVariant & jsonObject) inline static protected
Converts the given json schema type into a json object.
Parameters
valueTye json schema type(s)
jsonObject json object into which the json schema type(s) are stored
References JSONRPC::AnyValue, CVariant::append(), HasType(), SchemaValueTypeToString(), CVariant::size(), value, and CVariant::VariantTypeArray.
Referenced by JSONRPC::JSONSchemaTypeDefinition::Check(), JSONRPC::JsonRpcMethod::checkParameter(), and JSONRPC::JSONSchemaTypeDefinition::Print().
SchemaValueTypeToString()
static std::string JSONRPC::CJSONUtils::SchemaValueTypeToString (JSONSchemaType valueType) inline static protected
Returns a string representation for the given JSONSchemaType.
Parameters
valueType Specific JSONSchemaType
Returns
String representation of the given JSONSchemaType
References JSONRPC::AnyValue, JSONRPC::ArrayValue, JSONRPC::BooleanValue, HasType(), index(), JSONRPC::IntegerValue, JSONRPC::NullValue, JSONRPC::NumberValue, JSONRPC::ObjectValue, JSONRPC::StringValue, types, and value.
Referenced by JSONRPC::JSONSchemaTypeDefinition::Check(), and SchemaValueTypeToJson().
SetDefaultValue()
static void JSONRPC::CJSONUtils::SetDefaultValue (CVariant & value, JSONSchemaType valueType) inline static protected
Sets the value of the given json value to the default value of the given type.
Parameters
value Json value to be set
valueType Type of the default value
References JSONRPC::ArrayValue, JSONRPC::BooleanValue, JSONRPC::IntegerValue, JSONRPC::NumberValue, JSONRPC::ObjectValue, JSONRPC::StringValue, value, CVariant::VariantTypeArray, CVariant::VariantTypeBoolean, CVariant::VariantTypeDouble, CVariant::VariantTypeInteger, CVariant::VariantTypeNull, and CVariant::VariantTypeObject.
Referenced by JSONRPC::JSONSchemaTypeDefinition::Parse().
SetFromDBDate()
void JSONRPC::CJSONUtils::SetFromDBDate (const CVariant & jsonDate, CDateTime & date) static protected
References CVariant::asString(), CVariant::empty(), CVariant::isString(), CDateTime::Reset(), and CDateTime::SetFromDBDate().
Referenced by JSONRPC::CVideoLibrary::UpdateVideoTag().
SetFromDBDateTime()
void JSONRPC::CJSONUtils::SetFromDBDateTime (const CVariant & jsonDate, CDateTime & date) static protected
References CVariant::asString(), CVariant::empty(), CVariant::isString(), CDateTime::Reset(), and CDateTime::SetFromDBDateTime().
Referenced by JSONRPC::CFileOperations::SetFileDetails(), and JSONRPC::CVideoLibrary::UpdateVideoTag().
StringToSchemaValueType()
static JSONSchemaType JSONRPC::CJSONUtils::StringToSchemaValueType (const std::string & valueType) inline static protected
Returns a JSONSchemaType value for the given string representation.
Parameters
valueType String representation of the JSONSchemaType
Returns
JSONSchemaType value of the given string representation
References JSONRPC::AnyValue, JSONRPC::ArrayValue, JSONRPC::BooleanValue, JSONRPC::IntegerValue, JSONRPC::NullValue, JSONRPC::NumberValue, JSONRPC::ObjectValue, and JSONRPC::StringValue.
Referenced by JSONRPC::CJSONServiceDescription::parseJSONSchemaType().
StringToTransportLayer()
static TransportLayerCapability JSONRPC::CJSONUtils::StringToTransportLayer (const std::string & transport) inline static protected
Returns a TransportLayerCapability value of the given string representation.
Parameters
transport String representation of the TransportLayerCapability
Returns
TransportLayerCapability value of the given string representation
References JSONRPC::Announcing, JSONRPC::FileDownloadDirect, JSONRPC::FileDownloadRedirect, and JSONRPC::Response.
Referenced by JSONRPC::JsonRpcMethod::Parse().
ValueTypeToString()
static const char * JSONRPC::CJSONUtils::ValueTypeToString (CVariant::VariantType valueType) inline static protected
References CVariant::VariantTypeArray, CVariant::VariantTypeBoolean, CVariant::VariantTypeConstNull, CVariant::VariantTypeDouble, CVariant::VariantTypeInteger, CVariant::VariantTypeNull, CVariant::VariantTypeObject, CVariant::VariantTypeString, and CVariant::VariantTypeUnsignedInteger.
Referenced by JSONRPC::JSONSchemaTypeDefinition::Check().
The documentation for this class was generated from the following files:
JSONUtils.h
JSONUtils.cpp