Kodi Documentation: PVR::CPVRStringSettingValues Class Reference
PVR::CPVRStringSettingValues Class Reference
#include <PVRStringSettingValues.h>
Public Member Functions
CPVRStringSettingValues ()=default
CPVRStringSettingValues (struct PVR_ATTRIBUTE_STRING_VALUE *values, unsigned int valuesSize, const std::string &defaultValue, int defaultDescriptionResourceId=0)
virtual ~CPVRStringSettingValues ()=default
bool operator== (const CPVRStringSettingValues &right) const
const std::vector< SettingStringValue > & GetValues () const
const std::string & GetDefaultValue () const
Private Attributes
std::vector< SettingStringValue > m_values
std::string m_defaultValue
Constructor & Destructor Documentation
CPVRStringSettingValues() [1/2]
PVR::CPVRStringSettingValues::CPVRStringSettingValues () default
CPVRStringSettingValues() [2/2]
PVR::CPVRStringSettingValues::CPVRStringSettingValues (struct PVR_ATTRIBUTE_STRING_VALUE * values, unsigned int valuesSize, const std::string & defaultValue, int defaultDescriptionResourceId = 0)
References g_localizeStrings, CLocalizeStrings::Get(), m_values, value, and values.
~CPVRStringSettingValues()
virtual PVR::CPVRStringSettingValues::~CPVRStringSettingValues () virtual default
Member Function Documentation
GetDefaultValue()
const std::string & PVR::CPVRStringSettingValues::GetDefaultValue () const inline
References m_defaultValue.
Referenced by PVR::CPVRStringSettingDefinition::GetDefaultValue().
GetValues()
const std::vector< SettingStringValue > & PVR::CPVRStringSettingValues::GetValues () const inline
References m_values.
Referenced by PVR::CPVRStringSettingDefinition::GetValues().
operator==()
bool PVR::CPVRStringSettingValues::operator== (const CPVRStringSettingValues & right) const
References m_defaultValue, m_values, and right.
Member Data Documentation
m_defaultValue
std::string PVR::CPVRStringSettingValues::m_defaultValue private
Referenced by GetDefaultValue(), and operator==().
m_values
std::vector<SettingStringValue> PVR::CPVRStringSettingValues::m_values private
Referenced by CPVRStringSettingValues(), GetValues(), PVR::CPVRStringSettingDefinition::operator==(), and operator==().
The documentation for this class was generated from the following files:
PVRStringSettingValues.h
PVRStringSettingValues.cpp