Kodi Documentation: CContextMenuManager Class Reference
CContextMenuManager Class Reference
#include <ContextMenuManager.h>
Public Member Functions
CContextMenuManager (ADDON::CAddonMgr &addonMgr)
~CContextMenuManager ()
void Init ()
void Deinit ()
bool HasItems (const CFileItem &fileItem, const CContextMenuItem &root) const
Checks whether context menu items are available for a file item.
ContextMenuView GetItems (const CFileItem &fileItem, const CContextMenuItem &root) const
Gets the context menu items available for a file item.
bool HasAddonItems (const CFileItem &fileItem, const CContextMenuItem &root) const
Checks whether addon context menu items are available for a file item.
ContextMenuView GetAddonItems (const CFileItem &fileItem, const CContextMenuItem &root) const
Gets the addon context menu items available for a file item.
Static Public Attributes
static const CContextMenuItem MAIN = CContextMenuItem::CreateGroup("", "", "kodi.core.main", "")
static const CContextMenuItem MANAGE = CContextMenuItem::CreateGroup("", "", "kodi.core.manage", "")
Private Member Functions
CContextMenuManager (const CContextMenuManager &)=delete
CContextMenuManager & operator= (CContextMenuManager const &)=delete
bool IsVisible (const CContextMenuItem &menuItem, const CContextMenuItem &root, const CFileItem &fileItem) const
void ReloadAddonItems ()
void OnEvent (const ADDON::AddonEvent &event)
void OnPVREvent (const PVR::PVRContextMenuEvent &event)
Private Attributes
ADDON::CAddonMgr & m_addonMgr
CCriticalSection m_criticalSection
std::vector< CContextMenuItem > m_addonItems
std::vector< std::shared_ptr< IContextMenuItem > > m_items
Constructor & Destructor Documentation
CContextMenuManager() [1/2]
CContextMenuManager::CContextMenuManager (ADDON::CAddonMgr & addonMgr) explicit
~CContextMenuManager()
CContextMenuManager::~CContextMenuManager ()
References Deinit().
CContextMenuManager() [2/2]
CContextMenuManager::CContextMenuManager (const CContextMenuManager &) private delete
Member Function Documentation
Deinit()
void CContextMenuManager::Deinit ()
References ADDON::CAddonMgr::Events(), PVR::CPVRContextMenuManager::Events(), PVR::CPVRContextMenuManager::GetInstance(), m_addonMgr, and m_items.
Referenced by CProfileManager::PrepareLoadProfile(), and ~CContextMenuManager().
GetAddonItems()
ContextMenuView CContextMenuManager::GetAddonItems (const CFileItem & fileItem, const CContextMenuItem & root) const
Gets the addon context menu items available for a file item.
Parameters
fileItem the file item
root the root context menu item
Returns
the items
See also
ContextMenuView
References IsVisible(), m_addonItems, m_criticalSection, MANAGE, and root.
Referenced by PVR::CGUIDialogPVRItemsViewBase::ContextMenu(), CGUIDialogVideoInfo::ManageVideoItem(), CGUIMediaWindow::OnPopupMenu(), and CONTEXTMENU::ShowFor().
GetItems()
ContextMenuView CContextMenuManager::GetItems (const CFileItem & fileItem, const CContextMenuItem & root) const
Gets the context menu items available for a file item.
Parameters
fileItem the file item
root the root context menu item
Returns
the items
See also
ContextMenuView
Todo:
implement group support
References m_criticalSection, m_items, MAIN, and root.
Referenced by PVR::CGUIDialogPVRItemsViewBase::ContextMenu(), CGUIMediaWindow::OnPopupMenu(), and CONTEXTMENU::ShowFor().
HasAddonItems()
bool CContextMenuManager::HasAddonItems (const CFileItem & fileItem, const CContextMenuItem & root) const
Checks whether addon context menu items are available for a file item.
Parameters
fileItem the file item
root the root context menu item
Returns
true if any items are present, false otherwise
References m_addonItems, m_criticalSection, and root.
Referenced by CONTEXTMENU::HasAnyMenuItemsFor().
HasItems()
bool CContextMenuManager::HasItems (const CFileItem & fileItem, const CContextMenuItem & root) const
Checks whether context menu items are available for a file item.
Parameters
fileItem the file item
root the root context menu item
Returns
true if any items are present, false otherwise
Todo:
implement group support
References m_criticalSection, m_items, MAIN, and root.
Referenced by CONTEXTMENU::HasAnyMenuItemsFor().
Init()
void CContextMenuManager::Init ()
References ADDON::CAddonMgr::Events(), PVR::CPVRContextMenuManager::Events(), PVR::CPVRContextMenuManager::GetInstance(), m_addonMgr, m_criticalSection, m_items, OnEvent(), OnPVREvent(), and ReloadAddonItems().
Referenced by CProfileManager::FinalizeLoadProfile().
IsVisible()
bool CContextMenuManager::IsVisible (const CContextMenuItem & menuItem, const CContextMenuItem & root, const CFileItem & fileItem) const private
References CContextMenuItem::GetLabel(), CContextMenuItem::IsGroup(), CContextMenuItem::IsVisible(), m_addonItems, m_criticalSection, and root.
Referenced by GetAddonItems().
OnEvent()
void CContextMenuManager::OnEvent (const ADDON::AddonEvent & event) private
References ADDON::AddonEvent::addonId, ADDON::CAddonMgr::GetAddon(), ADDON::CAddonMgr::HasType(), CLog::Log(), LOGDEBUG, m_addonItems, m_addonMgr, m_criticalSection, and ReloadAddonItems().
Referenced by Init().
OnPVREvent()
void CContextMenuManager::OnPVREvent (const PVR::PVRContextMenuEvent & event) private
References PVR::PVRContextMenuEvent::action, PVR::PVRContextMenuEvent::item, m_criticalSection, and m_items.
Referenced by Init().
operator=()
CContextMenuManager & CContextMenuManager::operator= (CContextMenuManager const &) private delete
ReloadAddonItems()
void CContextMenuManager::ReloadAddonItems () private
References addons, ADDON::CAddonMgr::GetAddons(), CLog::Log(), LOGDEBUG, m_addonItems, m_addonMgr, and m_criticalSection.
Referenced by Init(), and OnEvent().
Member Data Documentation
m_addonItems
std::vector<CContextMenuItem> CContextMenuManager::m_addonItems private
Referenced by GetAddonItems(), HasAddonItems(), IsVisible(), OnEvent(), and ReloadAddonItems().
m_addonMgr
ADDON::CAddonMgr& CContextMenuManager::m_addonMgr private
Referenced by Deinit(), Init(), OnEvent(), and ReloadAddonItems().
m_criticalSection
CCriticalSection CContextMenuManager::m_criticalSection mutable private
Referenced by GetAddonItems(), GetItems(), HasAddonItems(), HasItems(), Init(), IsVisible(), OnEvent(), OnPVREvent(), and ReloadAddonItems().
m_items
std::vector<std::shared_ptr<IContextMenuItem> > CContextMenuManager::m_items private
Referenced by Deinit(), GetItems(), HasItems(), Init(), and OnPVREvent().
MAIN
const CContextMenuItem CContextMenuManager::MAIN = CContextMenuItem::CreateGroup("", "", "kodi.core.main", "") static
Referenced by ADDON::CContextMenuAddon::CContextMenuAddon(), PVR::CGUIDialogPVRItemsViewBase::ContextMenu(), CONTEXTMENU::CFavouritesTargetContextMenu::Execute(), GetItems(), HasItems(), CONTEXTMENU::CFavouritesTargetContextMenu::IsVisible(), anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor::OnChooseSelected(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::CVideoSelectActionProcessor::OnChooseSelected(), anonymous_namespace{GUIWindowVideoBase.cpp}::CVideoSelectActionProcessor::OnChooseSelected(), CDirectoryProvider::OnContextMenu(), and CGUIMediaWindow::OnPopupMenu().
MANAGE
const CContextMenuItem CContextMenuManager::MANAGE = CContextMenuItem::CreateGroup("", "", "kodi.core.manage", "") static
Referenced by ADDON::CContextMenuAddon::CContextMenuAddon(), GetAddonItems(), and CGUIDialogVideoInfo::ManageVideoItem().
The documentation for this class was generated from the following files:
ContextMenuManager.h
ContextMenuManager.cpp