Kodi Documentation: KODI::GAME::CGameClientProperties Class Reference
KODI::GAME::CGameClientProperties Class Reference
Games
C++ wrapper for properties to pass to the DLL.
#include <GameClientProperties.h>
Public Member Functions
CGameClientProperties (const CGameClient &parent, AddonProps_Game &props)
~CGameClientProperties (void)
bool InitializeProperties (void)
Private Member Functions
void ReleaseResources (void)
const char * GetLibraryPath (void)
const char ** GetProxyDllPaths (const ADDON::VECADDONS &addons)
unsigned int GetProxyDllCount (void) const
const char ** GetResourceDirectories (void)
unsigned int GetResourceDirectoryCount (void) const
const char * GetProfileDirectory (void)
const char ** GetExtensions (void)
unsigned int GetExtensionCount (void) const
bool GetProxyAddons (ADDON::VECADDONS &addons)
void AddProxyDll (const GameClientPtr &gameClient)
bool HasProxyDll (const std::string &strLibPath) const
Static Private Member Functions
static bool InstallDependencies (const std::vector< std::string > &addons)
Private Attributes
const CGameClient & m_parent
AddonProps_Game & m_properties
std::string m_strLibraryPath
std::vector< char * > m_proxyDllPaths
std::vector< char * > m_resourceDirectories
std::string m_strProfileDirectory
std::vector< char * > m_extensions
Detailed Description
C++ wrapper for properties to pass to the DLL.
Game client properties declared in addon-instance/Game.h.
Constructor & Destructor Documentation
CGameClientProperties()
CGameClientProperties::CGameClientProperties (const CGameClient & parent, AddonProps_Game & props)
~CGameClientProperties()
KODI::GAME::CGameClientProperties::~CGameClientProperties (void) inline
References ReleaseResources().
Member Function Documentation
AddProxyDll()
void CGameClientProperties::AddProxyDll (const GameClientPtr & gameClient) private
References HasProxyDll(), and m_proxyDllPaths.
Referenced by GetProxyDllPaths().
GetExtensionCount()
unsigned int CGameClientProperties::GetExtensionCount (void) const private
References m_extensions.
Referenced by InitializeProperties().
GetExtensions()
const char ** CGameClientProperties::GetExtensions (void) private
References KODI::GAME::CGameClient::GetExtensions(), m_extensions, and m_parent.
Referenced by InitializeProperties().
GetLibraryPath()
const char * CGameClientProperties::GetLibraryPath (void) private
References m_parent, m_strLibraryPath, URIUtils::RemoveSlashAtEnd(), and CSpecialProtocol::TranslatePath().
Referenced by InitializeProperties().
GetProfileDirectory()
const char * CGameClientProperties::GetProfileDirectory (void) private
References m_parent, m_strProfileDirectory, ADDON::CAddon::Profile(), URIUtils::RemoveSlashAtEnd(), and CSpecialProtocol::TranslatePath().
Referenced by InitializeProperties().
GetProxyAddons()
bool CGameClientProperties::GetProxyAddons (ADDON::VECADDONS & addons) private
References addons, ADDON::CAddonMgr::EnableAddon(), g_localizeStrings, CLocalizeStrings::Get(), ADDON::CAddonMgr::GetAddon(), CServiceBroker::GetAddonMgr(), ADDON::CAddon::GetDependencies(), InstallDependencies(), ADDON::CAddonMgr::IsAddonDisabled(), CLog::Log(), LOGDEBUG, LOGERROR, m_parent, CGUIDialogYesNo::ShowAndGetInput(), and KODI::MESSAGING::HELPERS::ShowOKDialogLines().
Referenced by InitializeProperties().
GetProxyDllCount()
unsigned int CGameClientProperties::GetProxyDllCount (void) const private
References m_proxyDllPaths.
Referenced by InitializeProperties().
GetProxyDllPaths()
const char ** CGameClientProperties::GetProxyDllPaths (const ADDON::VECADDONS & addons) private
References addons, AddProxyDll(), and m_proxyDllPaths.
Referenced by InitializeProperties().
GetResourceDirectories()
const char ** CGameClientProperties::GetResourceDirectories (void) private
References URIUtils::AddFileToFolder(), XFILE::CDirectory::Create(), XFILE::DIR_FLAG_DEFAULTS, XFILE::CDirectory::Exists(), KODI::GAME::GAME_CLIENT_RESOURCES_DIRECTORY, ADDON::CAddonMgr::GetAddon(), CServiceBroker::GetAddonMgr(), ADDON::CAddon::GetDependencies(), XFILE::CDirectory::GetDirectory(), CFileItemList::IsEmpty(), CLog::Log(), LOGDEBUG, m_parent, m_resourceDirectories, ADDON::CAddon::Path(), ADDON::CAddon::Profile(), URIUtils::RemoveSlashAtEnd(), and CSpecialProtocol::TranslatePath().
Referenced by InitializeProperties().
GetResourceDirectoryCount()
unsigned int CGameClientProperties::GetResourceDirectoryCount (void) const private
References m_resourceDirectories.
Referenced by InitializeProperties().
HasProxyDll()
bool CGameClientProperties::HasProxyDll (const std::string & strLibPath) const private
References m_proxyDllPaths.
Referenced by AddProxyDll().
InitializeProperties()
bool CGameClientProperties::InitializeProperties (void)
References addons, AddonProps_Game::extension_count, AddonProps_Game::extensions, AddonProps_Game::game_client_dll_path, GetExtensionCount(), GetExtensions(), GetLibraryPath(), GetProfileDirectory(), GetProxyAddons(), GetProxyDllCount(), GetProxyDllPaths(), GetResourceDirectories(), GetResourceDirectoryCount(), m_parent, m_properties, AddonProps_Game::profile_directory, AddonProps_Game::proxy_dll_count, AddonProps_Game::proxy_dll_paths, ReleaseResources(), AddonProps_Game::resource_directories, AddonProps_Game::resource_directory_count, AddonProps_Game::supports_vfs, and KODI::GAME::CGameClient::SupportsVFS().
InstallDependencies()
bool CGameClientProperties::InstallDependencies (const std::vector< std::string > & addons) static private
References addons, ADDON::CHOICE_NO, CGUIWindow::Close(), ADDON::CAddonMgr::FindInstallableById(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetAddonMgr(), CServiceBroker::GetGUI(), ADDON::CAddonInstaller::GetInstance(), CGUIComponent::GetWindowManager(), ADDON::CAddonInstaller::InstallOrUpdate(), CLog::Log(), LOGDEBUG, LOGERROR, CGUIDialog::Open(), CGUIListItem::SetArt(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), WINDOW_DIALOG_PROGRESS, and WINDOW_DIALOG_SELECT.
Referenced by GetProxyAddons().
ReleaseResources()
void CGameClientProperties::ReleaseResources (void) private
References m_extensions, m_proxyDllPaths, and m_resourceDirectories.
Referenced by InitializeProperties(), and ~CGameClientProperties().
Member Data Documentation
m_extensions
std::vector<char*> KODI::GAME::CGameClientProperties::m_extensions private
Referenced by GetExtensionCount(), GetExtensions(), and ReleaseResources().
m_parent
const CGameClient& KODI::GAME::CGameClientProperties::m_parent private
Referenced by GetExtensions(), GetLibraryPath(), GetProfileDirectory(), GetProxyAddons(), GetResourceDirectories(), and InitializeProperties().
m_properties
AddonProps_Game& KODI::GAME::CGameClientProperties::m_properties private
Referenced by InitializeProperties().
m_proxyDllPaths
std::vector<char*> KODI::GAME::CGameClientProperties::m_proxyDllPaths private
Referenced by AddProxyDll(), GetProxyDllCount(), GetProxyDllPaths(), HasProxyDll(), and ReleaseResources().
m_resourceDirectories
std::vector<char*> KODI::GAME::CGameClientProperties::m_resourceDirectories private
Referenced by GetResourceDirectories(), GetResourceDirectoryCount(), and ReleaseResources().
m_strLibraryPath
std::string KODI::GAME::CGameClientProperties::m_strLibraryPath private
Referenced by GetLibraryPath().
m_strProfileDirectory
std::string KODI::GAME::CGameClientProperties::m_strProfileDirectory private
Referenced by GetProfileDirectory().
The documentation for this class was generated from the following files:
GameClientProperties.h
GameClientProperties.cpp