Kodi Documentation: CGUISpinControl Class Reference
CGUISpinControl Class Reference
Guilib classes » Window Reference » Controls
#include <GUISpinControl.h>
Public Member Functions
CGUISpinControl (int parentID, int controlID, float posX, float posY, float width, float height, const CTextureInfo &textureUp, const CTextureInfo &textureDown, const CTextureInfo &textureUpFocus, const CTextureInfo &textureDownFocus, const CTextureInfo &textureUpDisabled, const CTextureInfo &textureDownDisabled, const CLabelInfo &labelInfo, int iType)
~CGUISpinControl () override=default
CGUISpinControl * Clone () const override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
bool OnAction (const CAction &action) override
void OnLeft () override
void OnRight () override
bool HitTest (const CPoint &point) const override
Used to test whether the point is inside a control.
bool OnMouseOver (const CPoint &point) override
Called when the mouse is over the control. Default implementation selects the control.
bool OnMessage (CGUIMessage &message) override
void AllocResources () override
void FreeResources (bool immediately=false) override
void DynamicResourceAlloc (bool bOnOff) override
void SetInvalid () override
void SetPosition (float posX, float posY) override
float GetWidth () const override
void SetRange (int iStart, int iEnd)
void SetFloatRange (float fStart, float fEnd)
void SetValue (int iValue)
void SetValueFromLabel (const std::string &label)
void SetFloatValue (float fValue)
void SetStringValue (const std::string &strValue)
int GetValue () const
float GetFloatValue () const
std::string GetStringValue () const
void AddLabel (const std::string &strLabel, int iValue)
void AddLabel (const std::string &strLabel, const std::string &strValue)
const std::string GetLabel () const
void SetReverse (bool bOnOff)
int GetMaximum () const
int GetMinimum () const
void SetSpinAlign (uint32_t align, float offsetX)
void SetType (int iType)
float GetSpinWidth () const
float GetSpinHeight () const
void SetFloatInterval (float fInterval)
void SetShowRange (bool bOnoff)
void SetShowOnePage (bool showOnePage)
void Clear ()
std::string GetDescription () const override
bool IsFocusedOnUp () const
bool IsVisible () const override
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
virtual void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions)
virtual void DoRender ()
virtual void RenderEx ()
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
React to a mouse event.
virtual void UnfocusFromPoint (const CPoint &point)
Unfocus the control if the given point on screen is not within it's boundary.
virtual int GetID (void) const
virtual void SetID (int id)
int GetParentID () const
virtual bool HasFocus () const
virtual bool IsDynamicallyAllocated ()
virtual bool CanFocus () const
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetHeight () const
virtual void AssignDepth ()
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetInitialVisibility ()
virtual void SetEnabled (bool bEnable)
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
virtual void QueueAnimation (ANIMATION_TYPE anim)
virtual bool IsAnimating (ANIMATION_TYPE anim)
virtual bool HasAnimation (ANIMATION_TYPE anim)
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void ResetAnimation (ANIMATION_TYPE type)
virtual void ResetAnimations ()
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsGroup () const
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
virtual void SaveStates (std::vector< CControlState > &states)
virtual CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr)
void SetControlStats (GUICONTROLSTATS *controlStats)
virtual void UpdateControlStats ()
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Protected Member Functions
CGUISpinControl (const CGUISpinControl &control)
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
bool UpdateColors (const CGUIListItem *item) override
virtual void RenderText (float posX, float posY, float width, float height)
Render the spinner text.
CGUILabel::COLOR GetTextColor () const
void PageUp ()
void PageDown ()
bool CanMoveDown (bool bTestReverse=true)
bool CanMoveUp (bool bTestReverse=true)
void MoveUp (bool bTestReverse=true)
void MoveDown (bool bTestReverse=true)
void ChangePage (int amount)
Protected Member Functions inherited from CGUIControl
virtual CPoint GetPosition () const
Return the coordinates of the top left of the control, in the control's parent coordinates.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool Animate (unsigned int currentTime)
virtual bool CheckAnimation (ANIMATION_TYPE animType)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Attributes
int m_iStart
int m_iEnd
float m_fStart
float m_fEnd
int m_iValue
float m_fValue
int m_iType
int m_iSelect
bool m_bReverse
float m_fInterval
std::vector< std::string > m_vecLabels
std::vector< int > m_vecValues
std::vector< std::string > m_vecStrValues
std::unique_ptr< CGUITexture > m_imgspinUp
std::unique_ptr< CGUITexture > m_imgspinDown
std::unique_ptr< CGUITexture > m_imgspinUpFocus
std::unique_ptr< CGUITexture > m_imgspinDownFocus
std::unique_ptr< CGUITexture > m_imgspinUpDisabled
std::unique_ptr< CGUITexture > m_imgspinDownDisabled
CGUILabel m_label
bool m_bShowRange
char m_szTyped [10]
int m_iTypedPos
int m_currentItem
int m_itemsPerPage
int m_numItems
bool m_showOnePage
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Additional Inherited Members
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Constructor & Destructor Documentation
CGUISpinControl() [1/2]
CGUISpinControl::CGUISpinControl (int parentID, int controlID, float posX, float posY, float width, float height, const CTextureInfo & textureUp, const CTextureInfo & textureDown, const CTextureInfo & textureUpFocus, const CTextureInfo & textureDownFocus, const CTextureInfo & textureUpDisabled, const CTextureInfo & textureDownDisabled, const CLabelInfo & labelInfo, int iType)
References CGUIControl::ControlType, CGUIControl::GUICONTROL_SPIN, m_bReverse, m_bShowRange, m_currentItem, m_fEnd, m_fInterval, m_fStart, m_fValue, m_iEnd, m_iSelect, m_iStart, m_itemsPerPage, m_iType, m_iTypedPos, m_iValue, m_numItems, m_showOnePage, m_szTyped, and SPIN_BUTTON_DOWN.
~CGUISpinControl()
CGUISpinControl::~CGUISpinControl () override default
CGUISpinControl() [2/2]
CGUISpinControl::CGUISpinControl (const CGUISpinControl & control) protected
References m_szTyped.
Member Function Documentation
AddLabel() [1/2]
void CGUISpinControl::AddLabel (const std::string & strLabel, const std::string & strValue)
References m_vecLabels, and m_vecStrValues.
AddLabel() [2/2]
void CGUISpinControl::AddLabel (const std::string & strLabel, int iValue)
References m_vecLabels, and m_vecValues.
Referenced by ADDON::Interface_GUIControlSpin::add_int_label(), ADDON::Interface_GUIControlSpin::add_string_label(), CGUIControlSpinExSetting::CGUIControlSpinExSetting(), CGUIControlSpinExSetting::FillIntegerSettingControl(), CGUIControlSpinExSetting::FillStringSettingControl(), and OnMessage().
AllocResources()
void CGUISpinControl::AllocResources () override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUISpinControlEx.
References CGUIControl::AllocResources(), m_imgspinDown, m_imgspinDownDisabled, m_imgspinDownFocus, m_imgspinUp, m_imgspinUpDisabled, m_imgspinUpFocus, CGUIControl::m_posX, and CGUIControl::m_posY.
Referenced by CGUISpinControlEx::AllocResources().
CanMoveDown()
bool CGUISpinControl::CanMoveDown (bool bTestReverse = true) protected
References CanMoveUp(), m_bReverse, m_currentItem, m_fEnd, m_fInterval, m_fValue, m_iEnd, m_iType, m_iValue, m_numItems, m_vecLabels, SPIN_CONTROL_TYPE_FLOAT, SPIN_CONTROL_TYPE_INT, SPIN_CONTROL_TYPE_PAGE, and SPIN_CONTROL_TYPE_TEXT.
Referenced by CanMoveUp(), and OnMessage().
CanMoveUp()
bool CGUISpinControl::CanMoveUp (bool bTestReverse = true) protected
References CanMoveDown(), m_bReverse, m_currentItem, m_fInterval, m_fStart, m_fValue, m_iStart, m_iType, m_iValue, SPIN_CONTROL_TYPE_FLOAT, SPIN_CONTROL_TYPE_INT, SPIN_CONTROL_TYPE_PAGE, and SPIN_CONTROL_TYPE_TEXT.
Referenced by CanMoveDown(), and OnMessage().
ChangePage()
void CGUISpinControl::ChangePage (int amount) protected
References CGUIControl::GetID(), CGUIControl::GetParentID(), GUI_MSG_NOTIFY_ALL, GUI_MSG_PAGE_CHANGE, m_currentItem, m_itemsPerPage, m_numItems, and CGUIControl::SendWindowMessage().
Referenced by MoveDown(), MoveUp(), PageDown(), and PageUp().
Clear()
void CGUISpinControl::Clear ()
References m_vecLabels, m_vecStrValues, m_vecValues, and SetValue().
Referenced by CGUIControlSpinExSetting::FillControl(), PVR::CGUIDialogPVRRadioRDSInfo::InitInfoControls(), and OnMessage().
Clone()
CGUISpinControl * CGUISpinControl::Clone (void) const inline override virtual
Implements CGUIControl.
Reimplemented in CGUISpinControlEx.
DynamicResourceAlloc()
void CGUISpinControl::DynamicResourceAlloc (bool bOnOff) override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUISpinControlEx.
References CGUIControl::DynamicResourceAlloc(), m_imgspinDown, m_imgspinDownDisabled, m_imgspinDownFocus, m_imgspinUp, m_imgspinUpDisabled, and m_imgspinUpFocus.
Referenced by CGUISpinControlEx::DynamicResourceAlloc().
FreeResources()
void CGUISpinControl::FreeResources (bool immediately = false) override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUISpinControlEx.
References CGUIControl::FreeResources(), m_imgspinDown, m_imgspinDownDisabled, m_imgspinDownFocus, m_imgspinUp, m_imgspinUpDisabled, m_imgspinUpFocus, m_iTypedPos, and m_szTyped.
Referenced by CGUISpinControlEx::FreeResources().
GetDescription()
std::string CGUISpinControl::GetDescription (void) const override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUISpinControlEx.
References GetMaximum(), and GetValue().
GetFloatValue()
float CGUISpinControl::GetFloatValue () const
References m_fValue.
Referenced by ADDON::Interface_GUIControlSpin::get_float_value(), and CGUIControlSpinExSetting::OnClick().
GetLabel()
const std::string CGUISpinControl::GetLabel () const
References m_iValue, and m_vecLabels.
Referenced by CGUISpinControlEx::GetCurrentLabel(), and CGUISpinControlEx::GetDescription().
GetMaximum()
int CGUISpinControl::GetMaximum () const
References m_fEnd, m_iEnd, m_iType, m_numItems, m_vecLabels, SPIN_CONTROL_TYPE_FLOAT, SPIN_CONTROL_TYPE_INT, SPIN_CONTROL_TYPE_PAGE, and SPIN_CONTROL_TYPE_TEXT.
Referenced by GetDescription(), and CGUIControlSpinExSetting::Update().
GetMinimum()
int CGUISpinControl::GetMinimum () const
References m_fStart, m_iStart, m_iType, SPIN_CONTROL_TYPE_FLOAT, SPIN_CONTROL_TYPE_INT, SPIN_CONTROL_TYPE_PAGE, and SPIN_CONTROL_TYPE_TEXT.
Referenced by CGUIControlSpinExSetting::Update().
GetSpinHeight()
float CGUISpinControl::GetSpinHeight () const inline
References m_imgspinUp.
Referenced by CGUISpinControlEx::AllocResources(), and CGUISpinControlEx::Process().
GetSpinWidth()
float CGUISpinControl::GetSpinWidth () const inline
References m_imgspinUp.
Referenced by CGUISpinControlEx::Process(), and CGUISpinControlEx::RenderText().
GetStringValue()
std::string CGUISpinControl::GetStringValue () const
References m_iType, m_iValue, m_vecLabels, m_vecStrValues, and SPIN_CONTROL_TYPE_TEXT.
Referenced by ADDON::Interface_GUIControlSpin::get_string_value(), and CGUIControlSpinExSetting::OnClick().
GetTextColor()
CGUILabel::COLOR CGUISpinControl::GetTextColor () const protected
References CGUILabel::COLOR_DISABLED, CGUILabel::COLOR_FOCUSED, CGUILabel::COLOR_TEXT, CGUIControl::HasFocus(), and CGUIControl::IsDisabled().
Referenced by RenderText().
GetValue()
int CGUISpinControl::GetValue () const
References m_iType, m_iValue, m_vecValues, and SPIN_CONTROL_TYPE_TEXT.
Referenced by ADDON::Interface_GUIControlSpin::get_int_value(), GetDescription(), CGUIControlSpinExSetting::OnClick(), OnMessage(), and PVR::CGUIDialogPVRRadioRDSInfo::OnMessage().
GetWidth()
float CGUISpinControl::GetWidth () const override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUISpinControlEx.
References m_imgspinDown.
HitTest()
bool CGUISpinControl::HitTest (const CPoint & point) const override virtual
Used to test whether the point is inside a control.
Parameters
point location to test
Returns
true if the point is inside the bounds of this control.
See also
SetHitRect
Reimplemented from CGUIControl.
Reimplemented in CGUISpinControlEx.
References CGUIControl::HitTest(), m_imgspinDownFocus, and m_imgspinUpFocus.
IsFocusedOnUp()
bool CGUISpinControl::IsFocusedOnUp () const
References m_iSelect, and SPIN_BUTTON_UP.
IsVisible()
bool CGUISpinControl::IsVisible () const override virtual
Reimplemented from CGUIControl.
References CGUIControl::IsVisible(), m_itemsPerPage, m_iType, m_numItems, m_showOnePage, and SPIN_CONTROL_TYPE_PAGE.
MoveDown()
void CGUISpinControl::MoveDown (bool bTestReverse = true) protected
References ChangePage(), CGUIControl::GetID(), CGUIControl::GetParentID(), GUI_MSG_CLICKED, m_bReverse, m_fEnd, m_fInterval, m_fStart, m_fValue, m_iEnd, m_iStart, m_iType, m_iValue, m_vecLabels, MoveUp(), CGUIControl::SendWindowMessage(), SPIN_CONTROL_TYPE_FLOAT, SPIN_CONTROL_TYPE_INT, SPIN_CONTROL_TYPE_PAGE, and SPIN_CONTROL_TYPE_TEXT.
Referenced by MoveUp(), OnAction(), OnMessage(), and OnMouseEvent().
MoveUp()
void CGUISpinControl::MoveUp (bool bTestReverse = true) protected
References ChangePage(), CGUIControl::GetID(), CGUIControl::GetParentID(), GUI_MSG_CLICKED, m_bReverse, m_fEnd, m_fInterval, m_fStart, m_fValue, m_iEnd, m_iStart, m_iType, m_iValue, m_vecLabels, MoveDown(), CGUIControl::SendWindowMessage(), SPIN_CONTROL_TYPE_FLOAT, SPIN_CONTROL_TYPE_INT, SPIN_CONTROL_TYPE_PAGE, and SPIN_CONTROL_TYPE_TEXT.
Referenced by MoveDown(), OnAction(), OnMessage(), and OnMouseEvent().
OnAction()
bool CGUISpinControl::OnAction (const CAction & action) override virtual
Reimplemented from CGUIControl.
References ACTION_PAGE_DOWN, ACTION_PAGE_UP, ACTION_SELECT_ITEM, CGUIControl::GetID(), CGUIControl::GetParentID(), GUI_MSG_CLICKED, m_bReverse, m_iEnd, m_iSelect, m_iType, m_iTypedPos, m_iValue, m_szTyped, m_vecLabels, MoveDown(), MoveUp(), CGUIControl::OnAction(), PageDown(), PageUp(), REMOTE_0, REMOTE_1, REMOTE_2, REMOTE_3, REMOTE_4, REMOTE_5, REMOTE_6, REMOTE_7, REMOTE_8, REMOTE_9, CGUIControl::SendWindowMessage(), SPIN_BUTTON_DOWN, SPIN_BUTTON_UP, SPIN_CONTROL_TYPE_INT, and SPIN_CONTROL_TYPE_TEXT.
OnLeft()
void CGUISpinControl::OnLeft () override virtual
Reimplemented from CGUIControl.
References m_iSelect, CGUIControl::MarkDirtyRegion(), CGUIControl::OnLeft(), SPIN_BUTTON_DOWN, and SPIN_BUTTON_UP.
OnMessage()
bool CGUISpinControl::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIControl.
References AddLabel(), CanMoveDown(), CanMoveUp(), Clear(), CGUIMessage::GetControlId(), CGUIControl::GetID(), CGUIMessage::GetLabel(), CGUIMessage::GetMessage(), CGUIMessage::GetParam1(), CGUIMessage::GetParam2(), CGUIMessage::GetPointer(), GetValue(), GUI_MSG_ITEM_SELECT, GUI_MSG_ITEM_SELECTED, GUI_MSG_LABEL_ADD, GUI_MSG_LABEL_RESET, GUI_MSG_MOVE_OFFSET, GUI_MSG_PAGE_DOWN, GUI_MSG_PAGE_UP, GUI_MSG_SET_LABELS, GUI_MSG_SHOWRANGE, m_bShowRange, m_currentItem, m_iSelect, m_itemsPerPage, m_iType, m_iValue, m_numItems, m_vecLabels, MoveDown(), MoveUp(), CGUIControl::OnMessage(), CGUIMessage::SetLabel(), CGUIMessage::SetParam1(), CGUIMessage::SetParam2(), SetValue(), SPIN_BUTTON_DOWN, SPIN_BUTTON_UP, SPIN_CONTROL_TYPE_PAGE, and SPIN_CONTROL_TYPE_TEXT.
OnMouseEvent()
EVENT_RESULT CGUISpinControl::OnMouseEvent (const CPoint & point, const KODI::MOUSE::CMouseEvent & event) override protected virtual
Perform a mouse action.
Mouse actions are sent from the window to all controls, and each control can react based on the event and location of the actions.
Parameters
point the location in transformed skin coordinates from the upper left corner of the parent control.
event the mouse event to perform
Returns
EVENT_RESULT corresponding to whether the control handles this event
See also
SendMouseEvent, HitTest, CanFocusFromPoint, CMouseEvent
Reimplemented from CGUIControl.
References ACTION_MOUSE_LEFT_CLICK, ACTION_MOUSE_WHEEL_DOWN, ACTION_MOUSE_WHEEL_UP, EVENT_RESULT_HANDLED, EVENT_RESULT_UNHANDLED, KODI::MOUSE::CMouseEvent::m_id, m_imgspinDownFocus, m_imgspinUpFocus, MoveDown(), and MoveUp().
OnMouseOver()
bool CGUISpinControl::OnMouseOver (const CPoint & point) override virtual
Called when the mouse is over the control. Default implementation selects the control.
Parameters
point location of the mouse in transformed skin coordinates
Returns
true if handled, false otherwise.
Reimplemented from CGUIControl.
References m_imgspinDownFocus, m_iSelect, CGUIControl::MarkDirtyRegion(), CGUIControl::OnMouseOver(), SPIN_BUTTON_DOWN, and SPIN_BUTTON_UP.
OnRight()
void CGUISpinControl::OnRight () override virtual
Reimplemented from CGUIControl.
References m_iSelect, CGUIControl::MarkDirtyRegion(), CGUIControl::OnRight(), SPIN_BUTTON_DOWN, and SPIN_BUTTON_UP.
PageDown()
void CGUISpinControl::PageDown () protected
References ChangePage(), CGUIControl::GetID(), CGUIControl::GetParentID(), GUI_MSG_CLICKED, m_iEnd, m_iType, m_iValue, m_vecLabels, CGUIControl::SendWindowMessage(), SPIN_CONTROL_TYPE_INT, SPIN_CONTROL_TYPE_PAGE, and SPIN_CONTROL_TYPE_TEXT.
Referenced by OnAction().
PageUp()
void CGUISpinControl::PageUp () protected
References ChangePage(), CGUIControl::GetID(), CGUIControl::GetParentID(), GUI_MSG_CLICKED, m_iStart, m_iType, m_iValue, CGUIControl::SendWindowMessage(), SPIN_CONTROL_TYPE_INT, SPIN_CONTROL_TYPE_PAGE, and SPIN_CONTROL_TYPE_TEXT.
Referenced by OnAction().
Process()
void CGUISpinControl::Process (unsigned int currentTime, CDirtyRegionList & dirtyregions) override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUISpinControlEx.
References CLabelInfo::align, CGUILabel::GetLabelInfo(), CGUILabel::GetTextWidth(), CGUIControl::HasFocus(), m_bShowRange, m_currentItem, m_fEnd, m_fValue, m_iEnd, m_imgspinDown, m_imgspinDownDisabled, m_imgspinDownFocus, m_imgspinUp, m_imgspinUpDisabled, m_imgspinUpFocus, m_itemsPerPage, m_iType, m_iTypedPos, m_iValue, m_label, m_numItems, CGUIControl::m_posX, CGUIControl::m_posY, m_szTyped, m_vecLabels, CGUIControl::MarkDirtyRegion(), CLabelInfo::offsetX, CGUILabel::Process(), CGUIControl::Process(), CGUILabel::SetText(), SPIN_CONTROL_TYPE_FLOAT, SPIN_CONTROL_TYPE_INT, SPIN_CONTROL_TYPE_PAGE, text, XBFONT_CENTER_X, and XBFONT_RIGHT.
Referenced by CGUISpinControlEx::Process().
Render()
void CGUISpinControl::Render () override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUISpinControlEx.
References CLabelInfo::align, CLabelInfo::font, CGUILabel::GetLabelInfo(), CGUILabel::GetRenderRect(), CGUILabel::GetTextWidth(), CGUIControl::HasFocus(), CGUIControl::IsDisabled(), CGUIControl::m_height, CGUIControl::m_hitRect, m_imgspinDown, m_imgspinDownDisabled, m_imgspinDownFocus, m_imgspinUp, m_imgspinUpDisabled, m_imgspinUpFocus, m_iSelect, m_label, CGUIControl::m_posX, CGUIControl::m_posY, CLabelInfo::offsetX, CGUIControl::Render(), RenderText(), SPIN_BUTTON_DOWN, SPIN_BUTTON_UP, XBFONT_CENTER_X, and XBFONT_RIGHT.
Referenced by CGUISpinControlEx::Render().
RenderText()
void CGUISpinControl::RenderText (float posX, float posY, float width, float height) protected virtual
Render the spinner text.
Parameters
posX position of the left edge of the text
posY positing of the top edge of the text
width width of the text
height height of the text
Reimplemented in CGUISpinControlEx.
References GetTextColor(), CServiceBroker::GetWinSystem(), m_label, CGUILabel::Render(), RENDER_ORDER_FRONT_TO_BACK, CGUILabel::SetColor(), and CGUILabel::SetMaxRect().
Referenced by Render(), and CGUISpinControlEx::RenderText().
SetFloatInterval()
void CGUISpinControl::SetFloatInterval (float fInterval)
References m_fInterval.
Referenced by CGUIControlSpinExSetting::CGUIControlSpinExSetting(), CGUIControlFactory::Create(), and ADDON::Interface_GUIControlSpin::set_float_interval().
SetFloatRange()
void CGUISpinControl::SetFloatRange (float fStart, float fEnd)
References m_fEnd, and m_fStart.
Referenced by CGUIControlSpinExSetting::CGUIControlSpinExSetting(), CGUIControlFactory::Create(), and ADDON::Interface_GUIControlSpin::set_float_range().
SetFloatValue()
void CGUISpinControl::SetFloatValue (float fValue)
References m_fValue.
Referenced by CGUIControlSpinExSetting::FillControl(), and ADDON::Interface_GUIControlSpin::set_float_value().
SetInvalid()
void CGUISpinControl::SetInvalid () override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUISpinControlEx.
References m_imgspinDown, m_imgspinDownDisabled, m_imgspinDownFocus, m_imgspinUp, m_imgspinUpDisabled, m_imgspinUpFocus, m_label, CGUIControl::SetInvalid(), and CGUILabel::SetInvalid().
Referenced by CGUISpinControlEx::SetHeight(), CGUISpinControlEx::SetInvalid(), CGUISpinControlEx::SetPosition(), SetStringValue(), SetValue(), SetValueFromLabel(), and CGUISpinControlEx::SetWidth().
SetPosition()
void CGUISpinControl::SetPosition (float posX, float posY) override virtual
Reimplemented from CGUIControl.
Reimplemented in CGUISpinControlEx.
References m_imgspinDown, m_imgspinDownDisabled, m_imgspinDownFocus, m_imgspinUp, m_imgspinUpDisabled, m_imgspinUpFocus, CGUIControl::m_posX, CGUIControl::m_posY, and CGUIControl::SetPosition().
Referenced by CGUISpinControlEx::Process().
SetRange()
void CGUISpinControl::SetRange (int iStart, int iEnd)
References m_iEnd, and m_iStart.
Referenced by CGUIControlFactory::Create(), and ADDON::Interface_GUIControlSpin::set_int_range().
SetReverse()
void CGUISpinControl::SetReverse (bool bOnOff)
References m_bReverse.
Referenced by CGUIControlFactory::Create().
SetShowOnePage()
void CGUISpinControl::SetShowOnePage (bool showOnePage) inline
References m_showOnePage.
Referenced by CGUIControlFactory::Create().
SetShowRange()
void CGUISpinControl::SetShowRange (bool bOnoff)
References m_bShowRange.
Referenced by CGUIControlFactory::Create().
SetSpinAlign()
void CGUISpinControl::SetSpinAlign (uint32_t align, float offsetX) inline
References CLabelInfo::align, CGUILabel::GetLabelInfo(), m_label, and CLabelInfo::offsetX.
SetStringValue()
void CGUISpinControl::SetStringValue (const std::string & strValue)
References m_iType, m_iValue, m_vecStrValues, SetInvalid(), and SPIN_CONTROL_TYPE_TEXT.
Referenced by CGUIControlSpinExSetting::FillStringSettingControl(), and ADDON::Interface_GUIControlSpin::set_string_value().
SetType()
void CGUISpinControl::SetType (int iType) inline
References m_iType.
Referenced by CGUIControlSpinExSetting::CGUIControlSpinExSetting(), and ADDON::Interface_GUIControlSpin::set_type().
SetValue()
void CGUISpinControl::SetValue (int iValue)
References m_iType, m_iValue, m_vecValues, CGUIControl::MarkDirtyRegion(), SetInvalid(), and SPIN_CONTROL_TYPE_TEXT.
Referenced by Clear(), CGUIControlSpinExSetting::FillFloatSettingControl(), CGUIControlSpinExSetting::FillIntegerSettingControl(), OnMessage(), and ADDON::Interface_GUIControlSpin::set_int_value().
SetValueFromLabel()
void CGUISpinControl::SetValueFromLabel (const std::string & label)
References label, m_iType, m_iValue, m_vecLabels, CGUIControl::MarkDirtyRegion(), SetInvalid(), and SPIN_CONTROL_TYPE_TEXT.
UpdateColors()
bool CGUISpinControl::UpdateColors (const CGUIListItem * item) override protected virtual
Reimplemented from CGUIControl.
Reimplemented in CGUISpinControlEx.
References CGUIControl::m_diffuseColor, m_imgspinDown, m_imgspinDownDisabled, m_imgspinDownFocus, m_imgspinUp, m_imgspinUpDisabled, m_imgspinUpFocus, m_label, CGUILabel::UpdateColors(), and CGUIControl::UpdateColors().
Referenced by CGUISpinControlEx::UpdateColors().
Member Data Documentation
m_bReverse
bool CGUISpinControl::m_bReverse protected
Referenced by CanMoveDown(), CanMoveUp(), CGUISpinControl(), MoveDown(), MoveUp(), OnAction(), and SetReverse().
m_bShowRange
bool CGUISpinControl::m_bShowRange protected
Referenced by CGUISpinControl(), OnMessage(), Process(), and SetShowRange().
m_currentItem
int CGUISpinControl::m_currentItem protected
Referenced by CanMoveDown(), CanMoveUp(), CGUISpinControl(), ChangePage(), OnMessage(), and Process().
m_fEnd
float CGUISpinControl::m_fEnd protected
Referenced by CanMoveDown(), CGUISpinControl(), GetMaximum(), MoveDown(), MoveUp(), Process(), and SetFloatRange().
m_fInterval
float CGUISpinControl::m_fInterval protected
Referenced by CanMoveDown(), CanMoveUp(), CGUISpinControl(), MoveDown(), MoveUp(), and SetFloatInterval().
m_fStart
float CGUISpinControl::m_fStart protected
Referenced by CanMoveUp(), CGUISpinControl(), GetMinimum(), MoveDown(), MoveUp(), and SetFloatRange().
m_fValue
float CGUISpinControl::m_fValue protected
Referenced by CanMoveDown(), CanMoveUp(), CGUISpinControl(), GetFloatValue(), MoveDown(), MoveUp(), Process(), and SetFloatValue().
m_iEnd
int CGUISpinControl::m_iEnd protected
Referenced by CanMoveDown(), CGUISpinControl(), GetMaximum(), MoveDown(), MoveUp(), OnAction(), PageDown(), Process(), and SetRange().
m_imgspinDown
std::unique_ptr<CGUITexture> CGUISpinControl::m_imgspinDown protected
Referenced by AllocResources(), DynamicResourceAlloc(), FreeResources(), GetWidth(), Process(), Render(), SetInvalid(), SetPosition(), and UpdateColors().
m_imgspinDownDisabled
std::unique_ptr<CGUITexture> CGUISpinControl::m_imgspinDownDisabled protected
Referenced by AllocResources(), DynamicResourceAlloc(), FreeResources(), Process(), Render(), SetInvalid(), SetPosition(), and UpdateColors().
m_imgspinDownFocus
std::unique_ptr<CGUITexture> CGUISpinControl::m_imgspinDownFocus protected
Referenced by AllocResources(), DynamicResourceAlloc(), FreeResources(), HitTest(), OnMouseEvent(), OnMouseOver(), Process(), Render(), SetInvalid(), SetPosition(), and UpdateColors().
m_imgspinUp
std::unique_ptr<CGUITexture> CGUISpinControl::m_imgspinUp protected
Referenced by AllocResources(), DynamicResourceAlloc(), FreeResources(), GetSpinHeight(), GetSpinWidth(), Process(), Render(), SetInvalid(), SetPosition(), and UpdateColors().
m_imgspinUpDisabled
std::unique_ptr<CGUITexture> CGUISpinControl::m_imgspinUpDisabled protected
Referenced by AllocResources(), DynamicResourceAlloc(), FreeResources(), Process(), Render(), SetInvalid(), SetPosition(), and UpdateColors().
m_imgspinUpFocus
std::unique_ptr<CGUITexture> CGUISpinControl::m_imgspinUpFocus protected
Referenced by AllocResources(), DynamicResourceAlloc(), FreeResources(), HitTest(), OnMouseEvent(), Process(), Render(), SetInvalid(), SetPosition(), and UpdateColors().
m_iSelect
int CGUISpinControl::m_iSelect protected
Referenced by CGUISpinControl(), IsFocusedOnUp(), OnAction(), OnLeft(), OnMessage(), OnMouseOver(), OnRight(), and Render().
m_iStart
int CGUISpinControl::m_iStart protected
Referenced by CanMoveUp(), CGUISpinControl(), GetMinimum(), MoveDown(), MoveUp(), PageUp(), and SetRange().
m_itemsPerPage
int CGUISpinControl::m_itemsPerPage protected
Referenced by CGUISpinControl(), ChangePage(), IsVisible(), OnMessage(), and Process().
m_iType
int CGUISpinControl::m_iType protected
Referenced by CanMoveDown(), CanMoveUp(), CGUISpinControl(), GetMaximum(), GetMinimum(), GetStringValue(), GetValue(), IsVisible(), MoveDown(), MoveUp(), OnAction(), OnMessage(), PageDown(), PageUp(), Process(), SetStringValue(), SetType(), SetValue(), and SetValueFromLabel().
m_iTypedPos
int CGUISpinControl::m_iTypedPos protected
Referenced by CGUISpinControl(), FreeResources(), OnAction(), and Process().
m_iValue
int CGUISpinControl::m_iValue protected
Referenced by CanMoveDown(), CanMoveUp(), CGUISpinControl(), GetLabel(), GetStringValue(), GetValue(), MoveDown(), MoveUp(), OnAction(), OnMessage(), PageDown(), PageUp(), Process(), SetStringValue(), SetValue(), and SetValueFromLabel().
m_label
CGUILabel CGUISpinControl::m_label protected
Referenced by CGUISpinControlEx::AllocResources(), Process(), Render(), RenderText(), CGUISpinControlEx::RenderText(), SetInvalid(), CGUISpinControlEx::SetItemInvalid(), SetSpinAlign(), and UpdateColors().
m_numItems
int CGUISpinControl::m_numItems protected
Referenced by CanMoveDown(), CGUISpinControl(), ChangePage(), GetMaximum(), IsVisible(), OnMessage(), and Process().
m_showOnePage
bool CGUISpinControl::m_showOnePage protected
Referenced by CGUISpinControl(), IsVisible(), and SetShowOnePage().
m_szTyped
char CGUISpinControl::m_szTyped[10] protected
Referenced by CGUISpinControl(), CGUISpinControl(), FreeResources(), OnAction(), and Process().
m_vecLabels
std::vector<std::string> CGUISpinControl::m_vecLabels protected
Referenced by AddLabel(), AddLabel(), CanMoveDown(), Clear(), GetLabel(), GetMaximum(), GetStringValue(), MoveDown(), MoveUp(), OnAction(), OnMessage(), PageDown(), Process(), and SetValueFromLabel().
m_vecStrValues
std::vector<std::string> CGUISpinControl::m_vecStrValues protected
Referenced by AddLabel(), Clear(), GetStringValue(), and SetStringValue().
m_vecValues
std::vector<int> CGUISpinControl::m_vecValues protected
Referenced by AddLabel(), Clear(), GetValue(), and SetValue().
The documentation for this class was generated from the following files:
GUISpinControl.h
GUISpinControl.cpp