Kodi Documentation: Shaders::CShader Class Reference
Shaders::CShader Class Reference abstract
#include <Shader.h>
Public Member Functions
CShader ()=default
virtual ~CShader ()=default
virtual bool Compile ()=0
virtual void Free ()=0
virtual GLuint Handle ()=0
virtual void SetSource (const std::string &src)
virtual bool LoadSource (const std::string &filename, const std::string &prefix="")
virtual bool AppendSource (const std::string &filename)
virtual bool InsertSource (const std::string &filename, const std::string &loc)
bool OK () const
std::string GetName () const
std::string GetSourceWithLineNumbers () const
Protected Attributes
std::string m_source
std::string m_lastLog
std::vector< std::string > m_attr
bool m_compiled = false
Private Attributes
std::string m_filenames
Constructor & Destructor Documentation
CShader()
Shaders::CShader::CShader () default
~CShader()
virtual Shaders::CShader::~CShader () virtual default
Member Function Documentation
AppendSource()
bool CShader::AppendSource (const std::string & filename) virtual
References CServiceBroker::GetRenderSystem(), CRenderSystemBase::GetShaderPath(), CLog::Log(), LOGERROR, m_filenames, and m_source.
Referenced by Shaders::GL::ConvolutionFilterShader::ConvolutionFilterShader(), Shaders::GLES::YUV2RGBFilterShader::YUV2RGBFilterShader(), Shaders::GL::YUV2RGBFilterShader4::YUV2RGBFilterShader4(), and Shaders::GL::YUV2RGBProgressiveShader::YUV2RGBProgressiveShader().
Compile()
virtual bool Shaders::CShader::Compile () pure virtual
Implemented in Shaders::CGLSLVertexShader, and Shaders::CGLSLPixelShader.
Referenced by Shaders::CGLSLShaderProgram::CompileAndLink().
Free()
virtual void Shaders::CShader::Free () pure virtual
Implemented in Shaders::CVertexShader, Shaders::CGLSLVertexShader, Shaders::CPixelShader, and Shaders::CGLSLPixelShader.
GetName()
std::string Shaders::CShader::GetName () const inline
References m_filenames.
Referenced by Shaders::CGLSLShaderProgram::CompileAndLink().
GetSourceWithLineNumbers()
std::string CShader::GetSourceWithLineNumbers () const
References m_source.
Referenced by Shaders::CGLSLShaderProgram::CompileAndLink().
Handle()
virtual GLuint Shaders::CShader::Handle () pure virtual
Implemented in Shaders::CVertexShader, and Shaders::CPixelShader.
InsertSource()
bool CShader::InsertSource (const std::string & filename, const std::string & loc) virtual
References CServiceBroker::GetRenderSystem(), CRenderSystemBase::GetShaderPath(), CLog::Log(), LOGERROR, m_filenames, and m_source.
Referenced by Shaders::GLES::YUV2RGBBobShader::YUV2RGBBobShader(), Shaders::GLES::YUV2RGBFilterShader::YUV2RGBFilterShader(), Shaders::GL::YUV2RGBFilterShader4::YUV2RGBFilterShader4(), Shaders::GL::YUV2RGBProgressiveShader::YUV2RGBProgressiveShader(), and Shaders::GLES::YUV2RGBProgressiveShader::YUV2RGBProgressiveShader().
LoadSource()
bool CShader::LoadSource (const std::string & filename, const std::string & prefix = "") virtual
References CServiceBroker::GetRenderSystem(), CRenderSystemBase::GetShaderPath(), CLog::Log(), LOGERROR, m_filenames, and m_source.
Referenced by Shaders::GL::BaseVideoFilterShader::BaseVideoFilterShader(), Shaders::GLES::BaseVideoFilterShader::BaseVideoFilterShader(), Shaders::GL::BaseYUV2RGBGLSLShader::BaseYUV2RGBGLSLShader(), Shaders::GLES::BaseYUV2RGBGLSLShader::BaseYUV2RGBGLSLShader(), CGLESShader::CGLESShader(), CGLESShader::CGLESShader(), CGLShader::CGLShader(), CGLShader::CGLShader(), Shaders::CGLSLShaderProgram::CGLSLShaderProgram(), Shaders::GLES::ConvolutionFilterShader::ConvolutionFilterShader(), Shaders::GL::ConvolutionFilterShader::ConvolutionFilterShader(), Shaders::GL::StretchFilterShader::StretchFilterShader(), Shaders::GLES::YUV2RGBBobShader::YUV2RGBBobShader(), Shaders::GLES::YUV2RGBFilterShader::YUV2RGBFilterShader(), Shaders::GL::YUV2RGBFilterShader4::YUV2RGBFilterShader4(), Shaders::GL::YUV2RGBProgressiveShader::YUV2RGBProgressiveShader(), and Shaders::GLES::YUV2RGBProgressiveShader::YUV2RGBProgressiveShader().
OK()
bool Shaders::CShader::OK () const inline
References m_compiled.
SetSource()
virtual void Shaders::CShader::SetSource (const std::string & src) inline virtual
References m_source.
Member Data Documentation
m_attr
std::vector<std::string> Shaders::CShader::m_attr protected
m_compiled
bool Shaders::CShader::m_compiled = false protected
Referenced by Shaders::CGLSLVertexShader::Compile(), Shaders::CGLSLPixelShader::Compile(), and OK().
m_filenames
std::string Shaders::CShader::m_filenames private
Referenced by AppendSource(), GetName(), InsertSource(), and LoadSource().
m_lastLog
std::string Shaders::CShader::m_lastLog protected
Referenced by Shaders::CGLSLVertexShader::Compile(), and Shaders::CGLSLPixelShader::Compile().
m_source
std::string Shaders::CShader::m_source protected
Referenced by AppendSource(), Shaders::CGLSLVertexShader::Compile(), Shaders::CGLSLPixelShader::Compile(), GetSourceWithLineNumbers(), InsertSource(), LoadSource(), and SetSource().
The documentation for this class was generated from the following files:
guilib/Shader.h
Shader.cpp