Kodi Documentation: PVRBuiltins.cpp File Reference
PVRBuiltins.cpp File Reference
#include "PVRBuiltins.h"
#include "GUIInfoManager.h"
#include "ServiceBroker.h"
#include "application/Application.h"
#include "application/ApplicationComponents.h"
#include "application/ApplicationPlayer.h"
#include "guilib/GUIComponent.h"
#include "guilib/GUIWindowManager.h"
#include "guilib/guiinfo/GUIInfoLabels.h"
#include "pvr/PVRManager.h"
#include "pvr/guilib/PVRGUIActionsTimers.h"
#include "pvr/windows/GUIWindowPVRGuide.h"
#include "utils/StringUtils.h"
#include "utils/log.h"
#include <algorithm>
#include <cstdlib>
#include <regex>
Namespaces
namespace anonymous_namespace{PVRBuiltins.cpp}
Functions
static int SearchMissingIcons (const std::vector< std::string > &params)
Search for missing channel icons.
static int ToggleRecordPlayingChannel (const std::vector< std::string > &params)
will toggle recording of playing channel, if any.
static int SeekPercentage (const std::vector< std::string > &params)
seeks to the given percentage in timeshift buffer, if timeshifting is supported.
int anonymous_namespace{PVRBuiltins.cpp}::EpgGridControl (const std::vector< std::string > &params)
Control PVR Guide window's EPG grid.
Function Documentation
SearchMissingIcons()
static int SearchMissingIcons (const std::vector< std::string > & params) static
Search for missing channel icons.
Parameters
params (ignored)
References CServiceBroker::GetPVRManager(), and PVR::CPVRManager::TriggerSearchMissingChannelIcons().
Referenced by CPVRBuiltins::GetOperations().
SeekPercentage()
static int SeekPercentage (const std::vector< std::string > & params) static
seeks to the given percentage in timeshift buffer, if timeshifting is supported.
Parameters
params The parameters
params[0] = percentage to seek to in the timeshift buffer.
References INFO::DEFAULT_CONTEXT, g_application, CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInt(), CLog::Log(), LOGERROR, PVR_TIMESHIFT_PROGRESS_BUFFER_START, and PVR_TIMESHIFT_PROGRESS_DURATION.
Referenced by CPVRBuiltins::GetOperations().
ToggleRecordPlayingChannel()
static int ToggleRecordPlayingChannel (const std::vector< std::string > & params) static
will toggle recording of playing channel, if any.
Parameters
params (ignored)
References PVR::CPVRManager::Get(), and CServiceBroker::GetPVRManager().
Referenced by CPVRBuiltins::GetOperations().