Kodi Documentation: KODI::PIPEWIRE::CPipewireContext Class Reference
KODI::PIPEWIRE::CPipewireContext Class Reference
#include <PipewireContext.h>
Classes
struct PipewireContextDeleter
Public Member Functions
CPipewireContext (CPipewireThreadLoop &loop)
CPipewireContext ()=delete
~CPipewireContext ()=default
pw_context * Get () const
CPipewireThreadLoop & GetThreadLoop () const
Private Attributes
CPipewireThreadLoop & m_threadLoop
std::unique_ptr< pw_context, PipewireContextDeleter > m_context
Constructor & Destructor Documentation
CPipewireContext() [1/2]
CPipewireContext::CPipewireContext (CPipewireThreadLoop & loop) explicit
References KODI::PIPEWIRE::CPipewireThreadLoop::Get(), CLog::Log(), LOGERROR, and m_context.
CPipewireContext() [2/2]
KODI::PIPEWIRE::CPipewireContext::CPipewireContext () delete
~CPipewireContext()
KODI::PIPEWIRE::CPipewireContext::~CPipewireContext () default
Member Function Documentation
Get()
pw_context * KODI::PIPEWIRE::CPipewireContext::Get () const inline
References m_context.
Referenced by KODI::PIPEWIRE::CPipewireCore::CPipewireCore().
GetThreadLoop()
CPipewireThreadLoop & KODI::PIPEWIRE::CPipewireContext::GetThreadLoop () const inline
References m_threadLoop.
Referenced by KODI::PIPEWIRE::CPipewireStream::Drained(), KODI::PIPEWIRE::CPipewireCore::OnCoreDone(), KODI::PIPEWIRE::CPipewireNode::Param(), KODI::PIPEWIRE::CPipewireStream::Process(), and KODI::PIPEWIRE::CPipewireStream::StateChanged().
Member Data Documentation
m_context
std::unique_ptr<pw_context, PipewireContextDeleter> KODI::PIPEWIRE::CPipewireContext::m_context private
Referenced by CPipewireContext(), and Get().
m_threadLoop
CPipewireThreadLoop& KODI::PIPEWIRE::CPipewireContext::m_threadLoop private
Referenced by GetThreadLoop().
The documentation for this class was generated from the following files:
PipewireContext.h
PipewireContext.cpp