Kodi Documentation: CDVDInputStreamNavigator Class Reference
CDVDInputStreamNavigator Class Reference
#include <DVDInputStreamNavigator.h>
Public Member Functions
CDVDInputStreamNavigator (IVideoPlayer *player, const CFileItem &fileitem)
~CDVDInputStreamNavigator () override
bool Open () override
void Close () override
int Read (uint8_t *buf, int buf_size) override
int64_t Seek (int64_t offset, int whence) override
int GetBlockSize () override
bool IsEOF () override
int64_t GetLength () override
ENextStream NextStream () override
void ActivateButton () override
void SelectButton (int iButton) override
void SkipStill () override
void SkipWait ()
void OnUp () override
void OnDown () override
void OnLeft () override
void OnRight () override
bool OnMenu () override
Open the Menu.
void OnBack () override
void OnNext () override
void OnPrevious () override
bool OnMouseMove (const CPoint &point) override
bool OnMouseClick (const CPoint &point) override
int GetCurrentButton () override
int GetTotalButtons () override
bool GetCurrentButtonInfo (CDVDOverlaySpu &pOverlayPicture, CDVDDemuxSPU *pSPU, int iButtonType)
MenuType GetSupportedMenuType () override
Get the supported menu type.
bool IsInMenu () override
double GetTimeStampCorrection () override
int GetActiveSubtitleStream ()
int GetSubTitleStreamCount ()
SubtitleStreamInfo GetSubtitleStreamInfo (const int iId)
bool SetActiveSubtitleStream (int iId)
void EnableSubtitleStream (bool bEnable)
bool IsSubtitleStreamEnabled ()
int GetActiveAudioStream ()
int GetAudioStreamCount ()
int GetActiveAngle ()
bool SetAngle (int angle)
bool SetActiveAudioStream (int iId)
AudioStreamInfo GetAudioStreamInfo (const int iId)
bool GetState (std::string &xmlstate) override
bool SetState (const std::string &xmlstate) override
int GetChapter () override
int GetChapterCount () override
void GetChapterName (std::string &name, int idx=-1) override
int64_t GetChapterPos (int ch=-1) override
bool SeekChapter (int iChapter) override
CDVDInputStream::IDisplayTime * GetIDisplayTime () override
int GetTotalTime () override
int GetTime () override
float GetVideoAspectRatio ()
CDVDInputStream::IPosTime * GetIPosTime () override
bool PosTime (int iTimeInMsec) override
std::string GetDVDTitleString ()
std::string GetDVDVolIdString ()
Get the DVD volume ID string. Alternative to the dvd title (since some DVD authors even forget to set it).
std::string GetDVDSerialString ()
void CheckButtons ()
VideoStreamInfo GetVideoStreamInfo ()
Public Member Functions inherited from CDVDInputStream
CDVDInputStream (DVDStreamType m_streamType, const CFileItem &fileitem)
virtual ~CDVDInputStream ()
virtual std::string & GetContent ()
virtual std::string GetFileName ()
virtual CURL GetURL ()
virtual void Abort ()
virtual bool CanSeek ()
virtual bool CanPause ()
virtual void SetReadRate (uint32_t rate)
Indicate expected read rate in bytes per second. This could be used to throttle caching rate. Should be seen as only a hint.
virtual bool GetCacheStatus (XFILE::SCacheStatus *status)
Get the cache status.
bool IsStreamType (DVDStreamType type) const
virtual BitstreamStats GetBitstreamStats () const
bool ContentLookup ()
virtual bool IsRealtime ()
void SetRealtime (bool realtime)
virtual IDemux * GetIDemux ()
virtual ITimes * GetITimes ()
virtual IChapter * GetIChapter ()
const CVariant & GetProperty (const std::string &key)
Public Member Functions inherited from CDVDInputStream::IDisplayTime
virtual ~IDisplayTime ()=default
Public Member Functions inherited from CDVDInputStream::IChapter
virtual ~IChapter ()=default
Public Member Functions inherited from CDVDInputStream::IPosTime
virtual ~IPosTime ()=default
Public Member Functions inherited from CDVDInputStream::IMenus
virtual ~IMenus ()=default
virtual bool CanSeek ()
Protected Member Functions
int ProcessBlock (uint8_t *buffer, int *read)
int GetAngleCount ()
void GetVideoResolution (uint32_t *width, uint32_t *height)
bool FillDVDState (DVDState &dvdstate)
Provided a pod DVDState struct, fill it with the current dvdnav state.
Static Protected Member Functions
static void SetAudioStreamName (AudioStreamInfo &info, const audio_attr_t &audio_attributes)
static void SetSubtitleStreamName (SubtitleStreamInfo &info, const subp_attr_t &subp_attributes)
Protected Attributes
DllDvdNav m_dll
bool m_bCheckButtons
bool m_bEOF
int m_holdmode
int m_iTotalTime
int m_iTime
int64_t m_iCellStart
bool m_bInMenu
int64_t m_iVobUnitStart
int64_t m_iVobUnitStop
int64_t m_iVobUnitCorrection
int m_iTitleCount
int m_iTitle
int m_iPartCount
int m_iPart
struct dvdnav_s * m_dvdnav
dvdnav_stream_cb m_dvdnav_stream_cb
std::unique_ptr< CDVDInputStreamFile > m_pstream
IVideoPlayer * m_pVideoPlayer
uint8_t m_lastblock [DVD_VIDEO_BLOCKSIZE]
int m_lastevent
std::map< int, std::map< int, int64_t > > m_mapTitleChapters
CDVDStateSerializer m_dvdStateSerializer
Protected Attributes inherited from CDVDInputStream
DVDStreamType m_streamType
BitstreamStats m_stats
std::string m_content
CFileItem m_item
bool m_contentLookup
bool m_realtime
Additional Inherited Members
Public Types inherited from CDVDInputStream
enum ENextStream { NEXTSTREAM_NONE , NEXTSTREAM_OPEN , NEXTSTREAM_RETRY }
Constructor & Destructor Documentation
CDVDInputStreamNavigator()
CDVDInputStreamNavigator::CDVDInputStreamNavigator (IVideoPlayer * player, const CFileItem & fileitem)
References dvd_inputstreamnavigator_cb_read(), dvd_inputstreamnavigator_cb_readv(), dvd_inputstreamnavigator_cb_seek(), DVDNAV_NOP, m_bCheckButtons, m_bEOF, m_bInMenu, m_dvdnav, m_dvdnav_stream_cb, m_holdmode, m_iCellStart, m_iPart, m_iPartCount, m_iTime, m_iTitle, m_iTitleCount, m_iTotalTime, m_iVobUnitCorrection, m_iVobUnitStart, m_iVobUnitStop, m_lastblock, m_lastevent, m_pVideoPlayer, dvd_reader_stream_cb::pf_read, dvd_reader_stream_cb::pf_readv, and dvd_reader_stream_cb::pf_seek.
~CDVDInputStreamNavigator()
CDVDInputStreamNavigator::~CDVDInputStreamNavigator () override
References Close().
Member Function Documentation
ActivateButton()
void CDVDInputStreamNavigator::ActivateButton () override virtual
Implements CDVDInputStream::IMenus.
References DllDvdNavInterface::dvdnav_button_activate(), DllDvdNavInterface::dvdnav_get_current_nav_pci(), m_dll, and m_dvdnav.
CheckButtons()
void CDVDInputStreamNavigator::CheckButtons ()
References DllDvdNavInterface::dvdnav_button_select(), DllDvdNavInterface::dvdnav_get_current_nav_pci(), GetCurrentButton(), CLog::Log(), LOGWARNING, m_bCheckButtons, m_dll, and m_dvdnav.
Close()
void CDVDInputStreamNavigator::Close () override virtual
Reimplemented from CDVDInputStream.
References CDVDInputStream::Close(), DllDvdNavInterface::dvdnav_close(), DllDvdNavInterface::dvdnav_err_to_string(), DVDNAV_STATUS_OK, CLog::Log(), LOGERROR, m_bEOF, m_dll, m_dvdnav, and m_pstream.
Referenced by Open(), and ~CDVDInputStreamNavigator().
EnableSubtitleStream()
void CDVDInputStreamNavigator::EnableSubtitleStream (bool bEnable)
References DllDvdNavInterface::dvdnav_toggle_spu_stream(), m_dll, and m_dvdnav.
Referenced by SeekChapter(), and SetState().
FillDVDState()
bool CDVDInputStreamNavigator::FillDVDState (DVDState & dvdstate) protected
Provided a pod DVDState struct, fill it with the current dvdnav state.
Parameters
[in,out] dvdstate the DVD state struct to be filled
Returns
true if it was possible to fill the state struct based on the current dvdnav state, false otherwise
References DVDState::audio_num, DVDState::current_angle, DllDvdNavInterface::dvdnav_current_title_program(), DllDvdNavInterface::dvdnav_err_to_string(), DVDNAV_STATUS_ERR, GetActiveAngle(), GetActiveAudioStream(), GetActiveSubtitleStream(), IsSubtitleStreamEnabled(), LOGERROR, m_dll, m_dvdnav, DVDState::pgcn, DVDState::pgn, DVDState::sub_enabled, DVDState::subp_num, and DVDState::title.
Referenced by GetState().
GetActiveAngle()
int CDVDInputStreamNavigator::GetActiveAngle ()
References DllDvdNavInterface::dvdnav_err_to_string(), DllDvdNavInterface::dvdnav_get_angle_info(), DVDNAV_STATUS_ERR, LOGERROR, m_dll, and m_dvdnav.
Referenced by FillDVDState().
GetActiveAudioStream()
int CDVDInputStreamNavigator::GetActiveAudioStream ()
References DllDvdNavInterface::dvdnav_get_active_audio_stream(), DllDvdNavInterface::dvdnav_get_audio_logical_stream(), GetAudioStreamCount(), m_dll, and m_dvdnav.
Referenced by FillDVDState(), and SeekChapter().
GetActiveSubtitleStream()
int CDVDInputStreamNavigator::GetActiveSubtitleStream ()
References DllDvdNavInterface::dvdnav_get_active_spu_stream(), DllDvdNavInterface::dvdnav_get_spu_logical_stream(), GetSubTitleStreamCount(), m_dll, and m_dvdnav.
Referenced by FillDVDState(), and SeekChapter().
GetAngleCount()
int CDVDInputStreamNavigator::GetAngleCount () protected
References DllDvdNavInterface::dvdnav_get_angle_info(), DVDNAV_STATUS_OK, m_dll, and m_dvdnav.
Referenced by GetVideoStreamInfo().
GetAudioStreamCount()
int CDVDInputStreamNavigator::GetAudioStreamCount ()
References DVD_AUDIO_STREAM, DllDvdNavInterface::dvdnav_get_number_of_streams(), m_dll, and m_dvdnav.
Referenced by GetActiveAudioStream().
GetAudioStreamInfo()
AudioStreamInfo CDVDInputStreamNavigator::GetAudioStreamInfo (const int iId)
References CLangCodeExpander::ConvertToISO6392B(), DllDvdNavInterface::dvdnav_get_audio_attr(), DVDNAV_STATUS_OK, g_LangCodeExpander, m_dll, m_dvdnav, and SetAudioStreamName().
GetBlockSize()
int CDVDInputStreamNavigator::GetBlockSize () inline override virtual
Reimplemented from CDVDInputStream.
References DVDSTREAM_BLOCK_SIZE_DVD.
GetChapter()
int CDVDInputStreamNavigator::GetChapter () inline override virtual
Implements CDVDInputStream::IChapter.
References m_iPart.
Referenced by GetChapterPos().
GetChapterCount()
int CDVDInputStreamNavigator::GetChapterCount () inline override virtual
Implements CDVDInputStream::IChapter.
References m_iPartCount.
Referenced by GetChapterPos().
GetChapterName()
void CDVDInputStreamNavigator::GetChapterName (std::string & name, int idx = -1) inline override virtual
Implements CDVDInputStream::IChapter.
GetChapterPos()
int64_t CDVDInputStreamNavigator::GetChapterPos (int ch = -1) override virtual
Implements CDVDInputStream::IChapter.
References GetChapter(), GetChapterCount(), m_iTitle, and m_mapTitleChapters.
GetCurrentButton()
int CDVDInputStreamNavigator::GetCurrentButton () override virtual
Implements CDVDInputStream::IMenus.
References DllDvdNavInterface::dvdnav_err_to_string(), DllDvdNavInterface::dvdnav_get_current_highlight(), DVDNAV_STATUS_ERR, LOGERROR, m_dll, and m_dvdnav.
Referenced by CheckButtons(), and GetCurrentButtonInfo().
GetCurrentButtonInfo()
bool CDVDInputStreamNavigator::GetCurrentButtonInfo (CDVDOverlaySpu & pOverlayPicture, CDVDDemuxSPU * pSPU, int iButtonType)
References CDVDOverlaySpu::crop_i_x_end, CDVDOverlaySpu::crop_i_x_start, CDVDOverlaySpu::crop_i_y_end, CDVDOverlaySpu::crop_i_y_start, DllDvdNavInterface::dvdnav_get_current_nav_pci(), DllDvdNavInterface::dvdnav_get_highlight_area(), DVDNAV_STATUS_OK, dvdnav_highlight_area_t::ex, dvdnav_highlight_area_t::ey, GetCurrentButton(), CDVDOverlaySpu::highlight_alpha, CDVDOverlaySpu::highlight_color, CDVDDemuxSPU::m_bHasClut, CDVDDemuxSPU::m_clut, m_dll, m_dvdnav, dvdnav_highlight_area_t::palette, dvdnav_highlight_area_t::sx, and dvdnav_highlight_area_t::sy.
GetDVDSerialString()
std::string CDVDInputStreamNavigator::GetDVDSerialString ()
References DllDvdNavInterface::dvdnav_get_serial_string(), DVDNAV_STATUS_OK, m_dll, and m_dvdnav.
GetDVDTitleString()
std::string CDVDInputStreamNavigator::GetDVDTitleString ()
References DllDvdNavInterface::dvdnav_get_title_string(), DVDNAV_STATUS_OK, m_dll, and m_dvdnav.
Referenced by UTILS::DISCS::ProbeDVDDiscInfo().
GetDVDVolIdString()
std::string CDVDInputStreamNavigator::GetDVDVolIdString ()
Get the DVD volume ID string. Alternative to the dvd title (since some DVD authors even forget to set it).
Returns
The DVD volume id
References DllDvdNavInterface::dvdnav_get_volid_string(), m_dll, and m_dvdnav.
GetIDisplayTime()
CDVDInputStream::IDisplayTime * CDVDInputStreamNavigator::GetIDisplayTime () inline override virtual
Reimplemented from CDVDInputStream.
GetIPosTime()
CDVDInputStream::IPosTime * CDVDInputStreamNavigator::GetIPosTime () inline override virtual
Reimplemented from CDVDInputStream.
GetLength()
int64_t CDVDInputStreamNavigator::GetLength () inline override virtual
Implements CDVDInputStream.
GetState()
bool CDVDInputStreamNavigator::GetState (std::string & xmlstate) override virtual
Implements CDVDInputStream::IMenus.
References DllDvdNavInterface::dvdnav_is_domain_vts(), CDVDStateSerializer::DVDStateToXML(), FillDVDState(), CLog::Log(), LOGWARNING, m_dll, m_dvdnav, and m_dvdStateSerializer.
GetSubTitleStreamCount()
int CDVDInputStreamNavigator::GetSubTitleStreamCount ()
References DVD_SUBTITLE_STREAM, DllDvdNavInterface::dvdnav_get_number_of_streams(), m_dll, and m_dvdnav.
Referenced by GetActiveSubtitleStream().
GetSubtitleStreamInfo()
SubtitleStreamInfo CDVDInputStreamNavigator::GetSubtitleStreamInfo (const int iId)
References CLangCodeExpander::ConvertToISO6392B(), DllDvdNavInterface::dvdnav_get_spu_attr(), DVDNAV_STATUS_OK, g_LangCodeExpander, m_dll, m_dvdnav, and SetSubtitleStreamName().
GetSupportedMenuType()
MenuType CDVDInputStreamNavigator::GetSupportedMenuType () inline override virtual
Get the supported menu type.
Returns
The supported menu type
Implements CDVDInputStream::IMenus.
References NATIVE.
GetTime()
int CDVDInputStreamNavigator::GetTime () override virtual
Implements CDVDInputStream::IDisplayTime.
References m_iTime.
GetTimeStampCorrection()
double CDVDInputStreamNavigator::GetTimeStampCorrection () inline override virtual
Reimplemented from CDVDInputStream::IMenus.
References m_iVobUnitCorrection.
GetTotalButtons()
int CDVDInputStreamNavigator::GetTotalButtons () override virtual
Implements CDVDInputStream::IMenus.
References DllDvdNavInterface::dvdnav_get_current_nav_pci(), m_dll, and m_dvdnav.
Referenced by OnNext(), OnPrevious(), and SeekChapter().
GetTotalTime()
int CDVDInputStreamNavigator::GetTotalTime () override virtual
Implements CDVDInputStream::IDisplayTime.
References m_iTotalTime.
GetVideoAspectRatio()
float CDVDInputStreamNavigator::GetVideoAspectRatio ()
References DllDvdNavInterface::dvdnav_get_video_aspect(), DllDvdNavInterface::dvdnav_get_video_scale_permission(), CLog::Log(), LOGINFO, m_dll, and m_dvdnav.
Referenced by GetVideoStreamInfo().
GetVideoResolution()
void CDVDInputStreamNavigator::GetVideoResolution (uint32_t * width, uint32_t * height) protected
References DllDvdNavInterface::dvdnav_err_to_string(), DllDvdNavInterface::dvdnav_get_video_resolution(), CLog::Log(), LOGWARNING, m_dll, and m_dvdnav.
Referenced by GetVideoStreamInfo().
GetVideoStreamInfo()
VideoStreamInfo CDVDInputStreamNavigator::GetVideoStreamInfo ()
References VideoStreamInfo::angles, GetAngleCount(), GetVideoAspectRatio(), GetVideoResolution(), and m_dvdnav.
IsEOF()
bool CDVDInputStreamNavigator::IsEOF () inline override virtual
Implements CDVDInputStream.
References m_bEOF.
IsInMenu()
bool CDVDInputStreamNavigator::IsInMenu () inline override virtual
Implements CDVDInputStream::IMenus.
References m_bInMenu.
Referenced by OnNext(), OnPrevious(), and SeekChapter().
IsSubtitleStreamEnabled()
bool CDVDInputStreamNavigator::IsSubtitleStreamEnabled ()
References DllDvdNavInterface::dvdnav_get_active_spu_stream(), m_dll, and m_dvdnav.
Referenced by FillDVDState(), and SeekChapter().
NextStream()
CDVDInputStream::ENextStream CDVDInputStreamNavigator::NextStream () override virtual
Reimplemented from CDVDInputStream.
References DVDNAV_VTS_CHANGE, m_bEOF, m_holdmode, m_lastevent, CDVDInputStream::NEXTSTREAM_NONE, CDVDInputStream::NEXTSTREAM_OPEN, and CDVDInputStream::NEXTSTREAM_RETRY.
OnBack()
void CDVDInputStreamNavigator::OnBack () override virtual
Implements CDVDInputStream::IMenus.
References DllDvdNavInterface::dvdnav_go_up(), m_dll, and m_dvdnav.
OnDown()
void CDVDInputStreamNavigator::OnDown () override virtual
Implements CDVDInputStream::IMenus.
References DllDvdNavInterface::dvdnav_get_current_nav_pci(), DllDvdNavInterface::dvdnav_lower_button_select(), m_dll, and m_dvdnav.
OnLeft()
void CDVDInputStreamNavigator::OnLeft () override virtual
Implements CDVDInputStream::IMenus.
References DllDvdNavInterface::dvdnav_get_current_nav_pci(), DllDvdNavInterface::dvdnav_left_button_select(), m_dll, and m_dvdnav.
OnMenu()
bool CDVDInputStreamNavigator::OnMenu () override virtual
Open the Menu.
Returns
true if the menu is successfully opened, false otherwise
Implements CDVDInputStream::IMenus.
References DVD_MENU_Escape, DllDvdNavInterface::dvdnav_menu_call(), DVDNAV_STATUS_OK, m_dll, and m_dvdnav.
OnMouseClick()
bool CDVDInputStreamNavigator::OnMouseClick (const CPoint & point) override virtual
Implements CDVDInputStream::IMenus.
References DllDvdNavInterface::dvdnav_get_current_nav_pci(), DllDvdNavInterface::dvdnav_mouse_activate(), DVDNAV_STATUS_OK, m_dll, m_dvdnav, CPointGen< T >::x, and CPointGen< T >::y.
OnMouseMove()
bool CDVDInputStreamNavigator::OnMouseMove (const CPoint & point) override virtual
Implements CDVDInputStream::IMenus.
References DllDvdNavInterface::dvdnav_get_current_nav_pci(), DllDvdNavInterface::dvdnav_mouse_select(), DVDNAV_STATUS_OK, m_dll, m_dvdnav, CPointGen< T >::x, and CPointGen< T >::y.
OnNext()
void CDVDInputStreamNavigator::OnNext () override virtual
Implements CDVDInputStream::IMenus.
References DllDvdNavInterface::dvdnav_next_pg_search(), GetTotalButtons(), IsInMenu(), m_dll, and m_dvdnav.
OnPrevious()
void CDVDInputStreamNavigator::OnPrevious () override virtual
Implements CDVDInputStream::IMenus.
References DllDvdNavInterface::dvdnav_prev_pg_search(), GetTotalButtons(), IsInMenu(), m_dll, and m_dvdnav.
OnRight()
void CDVDInputStreamNavigator::OnRight () override virtual
Implements CDVDInputStream::IMenus.
References DllDvdNavInterface::dvdnav_get_current_nav_pci(), DllDvdNavInterface::dvdnav_right_button_select(), m_dll, and m_dvdnav.
OnUp()
void CDVDInputStreamNavigator::OnUp () override virtual
Implements CDVDInputStream::IMenus.
References DllDvdNavInterface::dvdnav_get_current_nav_pci(), DllDvdNavInterface::dvdnav_upper_button_select(), m_dll, and m_dvdnav.
Open()
bool CDVDInputStreamNavigator::Open () override virtual
Bug:
libdvdnav isn't const correct
Bug:
libdvdnav isn't const correct
Bug:
libdvdnav isn't const correct
Reimplemented from CDVDInputStream.
References Close(), Cocoa_MountPoint2DeviceName(), dvd_logger(), DVD_MENU_Root, DVD_MENU_Title, DllDvdNavInterface::dvdnav_audio_language_select(), DllDvdNavInterface::dvdnav_err_to_string(), DllDvdNavInterface::dvdnav_get_disk_region_mask(), DllDvdNavInterface::dvdnav_get_next_cache_block(), DllDvdNavInterface::dvdnav_menu_call(), DllDvdNavInterface::dvdnav_menu_language_select(), DllDvdNavInterface::dvdnav_open(), DllDvdNavInterface::dvdnav_open2(), DllDvdNavInterface::dvdnav_open_stream(), DllDvdNav::dvdnav_open_stream2, DllDvdNavInterface::dvdnav_sector_search(), DllDvdNavInterface::dvdnav_set_PGC_positioning_flag(), DllDvdNavInterface::dvdnav_set_readahead_flag(), DllDvdNavInterface::dvdnav_set_region_mask(), DllDvdNavInterface::dvdnav_spu_language_select(), DVDNAV_STATUS_ERR, DVDNAV_STATUS_OK, g_langInfo, CFileItem::GetDynPath(), URIUtils::GetFileName(), URIUtils::GetParentPath(), CServiceBroker::GetSettingsComponent(), CFileItem::IsDiscImage(), DllDynamic::Load(), CLog::Log(), LOGDEBUG, LOGERROR, m_bCheckButtons, m_bEOF, m_bInMenu, m_dll, m_dvdnav, m_dvdnav_stream_cb, m_holdmode, m_iCellStart, m_iPart, m_iPartCount, CDVDInputStream::m_item, m_iTime, m_iTitle, m_iTitleCount, m_iTotalTime, m_iVobUnitCorrection, m_iVobUnitStart, m_iVobUnitStop, m_pstream, CDVDInputStream::Open(), dvdnav_logger_cb::pf_log, CEnvironment::putenv(), XFILE::READ_BITRATE, XFILE::READ_CHUNKED, XFILE::READ_TRUNCATED, URIUtils::RemoveSlashAtEnd(), CFileItem::SetMimeType(), CSettings::SETTING_DVDS_AUTOMENU, CSettings::SETTING_DVDS_PLAYERREGION, and CSpecialProtocol::TranslatePath().
PosTime()
bool CDVDInputStreamNavigator::PosTime (int iTimeInMsec) override virtual
Implements CDVDInputStream::IPosTime.
References DllDvdNavInterface::dvdnav_err_to_string(), DllDvdNavInterface::dvdnav_jump_to_sector_by_time(), DVDNAV_STATUS_ERR, CLog::Log(), LOGDEBUG, m_dll, m_dvdnav, and m_iTime.
ProcessBlock()
int CDVDInputStreamNavigator::ProcessBlock (uint8_t * buffer, int * read) protected
References dvdnav_cell_change_event_t::cell_start, DVDNAV_AUDIO_STREAM_CHANGE, DVDNAV_BLOCK_OK, DVDNAV_CELL_CHANGE, DllDvdNavInterface::dvdnav_current_title_info(), DllDvdNavInterface::dvdnav_describe_title_chapters(), DllDvdNavInterface::dvdnav_err_to_string(), DllDvdNavInterface::dvdnav_free_cache_block(), DllDvdNavInterface::dvdnav_get_current_nav_dsi(), DllDvdNavInterface::dvdnav_get_current_nav_pci(), DllDvdNavInterface::dvdnav_get_current_time(), DllDvdNavInterface::dvdnav_get_next_cache_block(), DllDvdNavInterface::dvdnav_get_number_of_parts(), DllDvdNavInterface::dvdnav_get_number_of_titles(), DllDvdNavInterface::dvdnav_get_position(), DVDNAV_HIGHLIGHT, DVDNAV_HOP_CHANNEL, DllDvdNavInterface::dvdnav_is_domain_vts(), DVDNAV_NAV_PACKET, DVDNAV_NOP, DVDNAV_SPU_CLUT_CHANGE, DVDNAV_SPU_STREAM_CHANGE, DVDNAV_STATUS_ERR, DVDNAV_STATUS_OK, DVDNAV_STILL_FRAME, DVDNAV_STOP, DVDNAV_VTS_CHANGE, DVDNAV_WAIT, int64_t(), CLog::Log(), LOGDEBUG, LOGERROR, m_bCheckButtons, m_bEOF, m_bInMenu, m_dll, m_dvdnav, m_holdmode, m_iCellStart, m_iPart, m_iPartCount, m_iTime, m_iTitle, m_iTitleCount, m_iTotalTime, m_iVobUnitCorrection, m_iVobUnitStart, m_iVobUnitStop, m_lastblock, m_lastevent, m_mapTitleChapters, m_pVideoPlayer, NAVRESULT_DATA, NAVRESULT_ERROR, NAVRESULT_HOLD, NAVRESULT_NOP, IVideoPlayer::OnDiscNavResult(), dvdnav_cell_change_event_t::pgc_length, and SkipWait().
Referenced by Read().
Read()
int CDVDInputStreamNavigator::Read (uint8_t * buf, int buf_size) override virtual
Implements CDVDInputStream.
References DVD_VIDEO_BLOCKSIZE, DVDNAV_ERROR, CLog::Log(), LOGERROR, m_bEOF, m_dvdnav, m_pVideoPlayer, NAVRESULT_DATA, NAVRESULT_ERROR, NAVRESULT_HOLD, NAVRESULT_NOP, IVideoPlayer::OnDiscNavResult(), and ProcessBlock().
Seek()
int64_t CDVDInputStreamNavigator::Seek (int64_t offset, int whence) override virtual
Implements CDVDInputStream.
References SEEK_POSSIBLE.
SeekChapter()
bool CDVDInputStreamNavigator::SeekChapter (int iChapter) override virtual
Implements CDVDInputStream::IChapter.
References DllDvdNavInterface::dvdnav_err_to_string(), DllDvdNavInterface::dvdnav_next_pg_search(), DllDvdNavInterface::dvdnav_part_play(), DllDvdNavInterface::dvdnav_prev_pg_search(), DVDNAV_STATUS_ERR, EnableSubtitleStream(), GetActiveAudioStream(), GetActiveSubtitleStream(), GetTotalButtons(), IsInMenu(), IsSubtitleStreamEnabled(), CLog::Log(), LOGDEBUG, LOGERROR, m_dll, m_dvdnav, m_iPart, m_iTitle, SetActiveAudioStream(), and SetActiveSubtitleStream().
SelectButton()
void CDVDInputStreamNavigator::SelectButton (int iButton) override virtual
Implements CDVDInputStream::IMenus.
References DllDvdNavInterface::dvdnav_button_select(), DllDvdNavInterface::dvdnav_get_current_nav_pci(), m_dll, and m_dvdnav.
SetActiveAudioStream()
bool CDVDInputStreamNavigator::SetActiveAudioStream (int iId)
References DVD_AUDIO_STREAM, DllDvdNavInterface::dvdnav_err_to_string(), DllDvdNavInterface::dvdnav_set_active_stream(), DVDNAV_STATUS_ERR, DVDNAV_STATUS_OK, CLog::Log(), LOGDEBUG, LOGERROR, m_dll, and m_dvdnav.
Referenced by SeekChapter(), and SetState().
SetActiveSubtitleStream()
bool CDVDInputStreamNavigator::SetActiveSubtitleStream (int iId)
References DVD_SUBTITLE_STREAM, DllDvdNavInterface::dvdnav_err_to_string(), DllDvdNavInterface::dvdnav_set_active_stream(), DVDNAV_STATUS_ERR, DVDNAV_STATUS_OK, LOGDEBUG, LOGERROR, m_dll, and m_dvdnav.
Referenced by SeekChapter(), and SetState().
SetAngle()
bool CDVDInputStreamNavigator::SetAngle (int angle)
References DllDvdNavInterface::dvdnav_angle_change(), DVDNAV_STATUS_OK, m_dll, and m_dvdnav.
SetAudioStreamName()
void CDVDInputStreamNavigator::SetAudioStreamName (AudioStreamInfo & info, const audio_attr_t & audio_attributes) static protected
References DVD_AUDIO_FORMAT_AC3, DVD_AUDIO_FORMAT_DTS, DVD_AUDIO_FORMAT_LPCM, DVD_AUDIO_FORMAT_MPEG, DVD_AUDIO_FORMAT_MPEG2_EXT, DVD_AUDIO_FORMAT_SDDS, DVD_AUDIO_FORMAT_UNKNOWN_1, DVD_AUDIO_FORMAT_UNKNOWN_5, FLAG_VISUAL_IMPAIRED, g_localizeStrings, and CLocalizeStrings::Get().
Referenced by GetAudioStreamInfo().
SetState()
bool CDVDInputStreamNavigator::SetState (const std::string & xmlstate) override virtual
Implements CDVDInputStream::IMenus.
References DVDState::audio_num, DVDState::current_angle, DllDvdNavInterface::dvdnav_angle_change(), DllDvdNav::dvdnav_program_play, EnableSubtitleStream(), LOGWARNING, m_dll, m_dvdnav, m_dvdStateSerializer, DVDState::pgcn, DVDState::pgn, SetActiveAudioStream(), SetActiveSubtitleStream(), DVDState::sub_enabled, DVDState::subp_num, DVDState::title, and CDVDStateSerializer::XMLToDVDState().
SetSubtitleStreamName()
void CDVDInputStreamNavigator::SetSubtitleStreamName (SubtitleStreamInfo & info, const subp_attr_t & subp_attributes) static protected
References FLAG_FORCED, FLAG_HEARING_IMPAIRED, g_localizeStrings, and CLocalizeStrings::Get().
Referenced by GetSubtitleStreamInfo().
SkipStill()
void CDVDInputStreamNavigator::SkipStill () override virtual
Implements CDVDInputStream::IMenus.
References DllDvdNavInterface::dvdnav_still_skip(), m_dll, and m_dvdnav.
SkipWait()
void CDVDInputStreamNavigator::SkipWait ()
References DllDvdNavInterface::dvdnav_wait_skip(), m_dll, and m_dvdnav.
Referenced by ProcessBlock().
Member Data Documentation
m_bCheckButtons
bool CDVDInputStreamNavigator::m_bCheckButtons protected
Referenced by CDVDInputStreamNavigator(), CheckButtons(), Open(), and ProcessBlock().
m_bEOF
bool CDVDInputStreamNavigator::m_bEOF protected
Referenced by CDVDInputStreamNavigator(), Close(), IsEOF(), NextStream(), Open(), ProcessBlock(), and Read().
m_bInMenu
bool CDVDInputStreamNavigator::m_bInMenu protected
Referenced by CDVDInputStreamNavigator(), IsInMenu(), Open(), and ProcessBlock().
m_dll
DllDvdNav CDVDInputStreamNavigator::m_dll protected
Referenced by ActivateButton(), CheckButtons(), Close(), EnableSubtitleStream(), FillDVDState(), GetActiveAngle(), GetActiveAudioStream(), GetActiveSubtitleStream(), GetAngleCount(), GetAudioStreamCount(), GetAudioStreamInfo(), GetCurrentButton(), GetCurrentButtonInfo(), GetDVDSerialString(), GetDVDTitleString(), GetDVDVolIdString(), GetState(), GetSubTitleStreamCount(), GetSubtitleStreamInfo(), GetTotalButtons(), GetVideoAspectRatio(), GetVideoResolution(), IsSubtitleStreamEnabled(), OnBack(), OnDown(), OnLeft(), OnMenu(), OnMouseClick(), OnMouseMove(), OnNext(), OnPrevious(), OnRight(), OnUp(), Open(), PosTime(), ProcessBlock(), SeekChapter(), SelectButton(), SetActiveAudioStream(), SetActiveSubtitleStream(), SetAngle(), SetState(), SkipStill(), and SkipWait().
m_dvdnav
struct dvdnav_s* CDVDInputStreamNavigator::m_dvdnav protected
Referenced by ActivateButton(), CDVDInputStreamNavigator(), CheckButtons(), Close(), EnableSubtitleStream(), FillDVDState(), GetActiveAngle(), GetActiveAudioStream(), GetActiveSubtitleStream(), GetAngleCount(), GetAudioStreamCount(), GetAudioStreamInfo(), GetCurrentButton(), GetCurrentButtonInfo(), GetDVDSerialString(), GetDVDTitleString(), GetDVDVolIdString(), GetState(), GetSubTitleStreamCount(), GetSubtitleStreamInfo(), GetTotalButtons(), GetVideoAspectRatio(), GetVideoResolution(), GetVideoStreamInfo(), IsSubtitleStreamEnabled(), OnBack(), OnDown(), OnLeft(), OnMenu(), OnMouseClick(), OnMouseMove(), OnNext(), OnPrevious(), OnRight(), OnUp(), Open(), PosTime(), ProcessBlock(), Read(), SeekChapter(), SelectButton(), SetActiveAudioStream(), SetActiveSubtitleStream(), SetAngle(), SetState(), SkipStill(), and SkipWait().
m_dvdnav_stream_cb
dvdnav_stream_cb CDVDInputStreamNavigator::m_dvdnav_stream_cb protected
Referenced by CDVDInputStreamNavigator(), and Open().
m_dvdStateSerializer
CDVDStateSerializer CDVDInputStreamNavigator::m_dvdStateSerializer protected
DVD state serializer handler
Referenced by GetState(), and SetState().
m_holdmode
int CDVDInputStreamNavigator::m_holdmode protected
Referenced by CDVDInputStreamNavigator(), NextStream(), Open(), and ProcessBlock().
m_iCellStart
int64_t CDVDInputStreamNavigator::m_iCellStart protected
Referenced by CDVDInputStreamNavigator(), Open(), and ProcessBlock().
m_iPart
int CDVDInputStreamNavigator::m_iPart protected
Referenced by CDVDInputStreamNavigator(), GetChapter(), Open(), ProcessBlock(), and SeekChapter().
m_iPartCount
int CDVDInputStreamNavigator::m_iPartCount protected
Referenced by CDVDInputStreamNavigator(), GetChapterCount(), Open(), and ProcessBlock().
m_iTime
int CDVDInputStreamNavigator::m_iTime protected
Referenced by CDVDInputStreamNavigator(), GetTime(), Open(), PosTime(), and ProcessBlock().
m_iTitle
int CDVDInputStreamNavigator::m_iTitle protected
Referenced by CDVDInputStreamNavigator(), GetChapterPos(), Open(), ProcessBlock(), and SeekChapter().
m_iTitleCount
int CDVDInputStreamNavigator::m_iTitleCount protected
Referenced by CDVDInputStreamNavigator(), Open(), and ProcessBlock().
m_iTotalTime
int CDVDInputStreamNavigator::m_iTotalTime protected
Referenced by CDVDInputStreamNavigator(), GetTotalTime(), Open(), and ProcessBlock().
m_iVobUnitCorrection
int64_t CDVDInputStreamNavigator::m_iVobUnitCorrection protected
Referenced by CDVDInputStreamNavigator(), GetTimeStampCorrection(), Open(), and ProcessBlock().
m_iVobUnitStart
int64_t CDVDInputStreamNavigator::m_iVobUnitStart protected
Referenced by CDVDInputStreamNavigator(), Open(), and ProcessBlock().
m_iVobUnitStop
int64_t CDVDInputStreamNavigator::m_iVobUnitStop protected
Referenced by CDVDInputStreamNavigator(), Open(), and ProcessBlock().
m_lastblock
uint8_t CDVDInputStreamNavigator::m_lastblock[DVD_VIDEO_BLOCKSIZE] protected
Referenced by CDVDInputStreamNavigator(), and ProcessBlock().
m_lastevent
int CDVDInputStreamNavigator::m_lastevent protected
Referenced by CDVDInputStreamNavigator(), NextStream(), and ProcessBlock().
m_mapTitleChapters
std::map<int, std::map<int, int64_t> > CDVDInputStreamNavigator::m_mapTitleChapters protected
Referenced by GetChapterPos(), and ProcessBlock().
m_pstream
std::unique_ptr<CDVDInputStreamFile> CDVDInputStreamNavigator::m_pstream protected
Referenced by Close(), and Open().
m_pVideoPlayer
IVideoPlayer* CDVDInputStreamNavigator::m_pVideoPlayer protected
Referenced by CDVDInputStreamNavigator(), ProcessBlock(), and Read().
The documentation for this class was generated from the following files:
DVDInputStreamNavigator.h
DVDInputStreamNavigator.cpp