Kodi Documentation: Actor::Protocol Class Reference
Actor::Protocol Class Reference
#include <ActorProtocol.h>
Public Member Functions
Protocol (std::string name, CEvent *inEvent, CEvent *outEvent)
Protocol (std::string name)
~Protocol ()
Message * GetMessage ()
void ReturnMessage (Message *msg)
bool SendOutMessage (int signal, const void *data=nullptr, size_t size=0, Message *outMsg=nullptr)
bool SendOutMessage (int signal, CPayloadWrapBase *payload, Message *outMsg=nullptr)
bool SendInMessage (int signal, const void *data=nullptr, size_t size=0, Message *outMsg=nullptr)
bool SendInMessage (int signal, CPayloadWrapBase *payload, Message *outMsg=nullptr)
bool SendOutMessageSync (int signal, Message **retMsg, std::chrono::milliseconds timeout, const void *data=nullptr, size_t size=0)
bool SendOutMessageSync (int signal, Message **retMsg, std::chrono::milliseconds timeout, CPayloadWrapBase *payload)
bool ReceiveOutMessage (Message **msg)
bool ReceiveInMessage (Message **msg)
void Purge ()
void PurgeIn (int signal)
void PurgeOut (int signal)
void DeferIn (bool value)
void DeferOut (bool value)
void Lock ()
void Unlock ()
Public Attributes
std::string portName
Protected Attributes
CEvent * containerInEvent
CEvent * containerOutEvent
CCriticalSection criticalSection
std::queue< Message * > outMessages
std::queue< Message * > inMessages
std::queue< Message * > freeMessageQueue
bool inDefered = false
bool outDefered = false
Constructor & Destructor Documentation
Protocol() [1/2]
Actor::Protocol::Protocol (std::string name, CEvent * inEvent, CEvent * outEvent) inline
Protocol() [2/2]
Actor::Protocol::Protocol (std::string name) inline
~Protocol()
Protocol::~Protocol ()
References freeMessageQueue, and Purge().
Member Function Documentation
DeferIn()
void Actor::Protocol::DeferIn (bool value) inline
References inDefered, and value.
DeferOut()
void Actor::Protocol::DeferOut (bool value) inline
References outDefered, and value.
GetMessage()
Message * Protocol::GetMessage ()
References criticalSection, Actor::Message::data, Actor::Message::event, freeMessageQueue, Actor::Message::isSync, Actor::Message::isSyncFini, Actor::Message::isSyncTimeout, Actor::Message::payloadSize, and Actor::Message::replyMessage.
Referenced by ActiveAE::CActiveAE::Process(), ActiveAE::CActiveAESink::Process(), VAAPI::COutput::Process(), VDPAU::CMixer::Process(), VDPAU::COutput::Process(), Actor::Message::Reply(), SendInMessage(), SendInMessage(), SendOutMessage(), SendOutMessage(), SendOutMessageSync(), and SendOutMessageSync().
Lock()
void Actor::Protocol::Lock () inline
References criticalSection.
Referenced by Actor::Message::Release(), and Actor::Message::Reply().
Purge()
void Protocol::Purge ()
References ReceiveInMessage(), ReceiveOutMessage(), and Actor::Message::Release().
Referenced by ActiveAE::CActiveAE::Dispose(), ActiveAE::CActiveAESink::Dispose(), VAAPI::COutput::Dispose(), VDPAU::CMixer::Dispose(), VDPAU::COutput::Dispose(), and ~Protocol().
PurgeIn()
void Protocol::PurgeIn (int signal)
References criticalSection, inMessages, and Actor::Message::signal.
PurgeOut()
void Protocol::PurgeOut (int signal)
References criticalSection, outMessages, and Actor::Message::signal.
Referenced by ActiveAE::CActiveAE::StateMachine().
ReceiveInMessage()
bool Protocol::ReceiveInMessage (Message ** msg)
References criticalSection, inDefered, and inMessages.
Referenced by VAAPI::CDecoder::Decode(), VDPAU::CDecoder::Decode(), VAAPI::COutput::Flush(), VDPAU::COutput::Flush(), ActiveAE::CActiveAE::Process(), VDPAU::COutput::Process(), and Purge().
ReceiveOutMessage()
bool Protocol::ReceiveOutMessage (Message ** msg)
References criticalSection, outDefered, and outMessages.
Referenced by VAAPI::COutput::Flush(), VDPAU::CMixer::Flush(), VDPAU::COutput::Flush(), ActiveAE::CActiveAE::Process(), ActiveAE::CActiveAESink::Process(), VAAPI::COutput::Process(), VDPAU::CMixer::Process(), VDPAU::COutput::Process(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::ProcessMessages(), Purge(), and ActiveAE::CActiveAESink::ReturnBuffers().
ReturnMessage()
void Protocol::ReturnMessage (Message * msg)
References criticalSection, and freeMessageQueue.
Referenced by Actor::Message::Release().
SendInMessage() [1/2]
bool Protocol::SendInMessage (int signal, const void * data = nullptr, size_t size = 0, Message * outMsg = nullptr)
References Actor::Message::buffer, containerInEvent, criticalSection, Actor::Message::data, data(), GetMessage(), inMessages, Actor::Message::isOut, CEvent::Set(), and Actor::Message::signal.
Referenced by Actor::Message::Reply(), VDPAU::CMixer::StateMachine(), VDPAU::COutput::StateMachine(), and VAAPI::COutput::StateMachine().
SendInMessage() [2/2]
bool Protocol::SendInMessage (int signal, CPayloadWrapBase * payload, Message * outMsg = nullptr)
References containerInEvent, criticalSection, GetMessage(), inMessages, Actor::Message::isOut, Actor::Message::payloadObj, CEvent::Set(), and Actor::Message::signal.
SendOutMessage() [1/2]
bool Protocol::SendOutMessage (int signal, const void * data = nullptr, size_t size = 0, Message * outMsg = nullptr)
References Actor::Message::buffer, containerOutEvent, criticalSection, Actor::Message::data, data(), GetMessage(), Actor::Message::isOut, outMessages, CEvent::Set(), and Actor::Message::signal.
Referenced by ActiveAE::CActiveAE::Configure(), VAAPI::CDecoder::Decode(), VDPAU::CDecoder::Decode(), ActiveAE::CActiveAE::DeviceChange(), ActiveAE::CActiveAE::DeviceCountChange(), VDPAU::COutput::EnsureBufferPool(), VDPAU::COutput::Flush(), ActiveAE::CActiveAE::FreeSound(), VDPAU::COutput::InitMixer(), ActiveAE::CActiveAE::InitSink(), ActiveAE::CActiveAE::KeepConfiguration(), ActiveAE::CActiveAE::MakeSound(), ActiveAE::CActiveAE::OnAppFocusChange(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::OnConfigure(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::OnOutputDone(), ActiveAE::CActiveAE::OnResetDisplay(), ActiveAE::CActiveAE::OnSettingsChange(), ActiveAE::CActiveAE::PauseStream(), ActiveAE::CActiveAE::PlaySound(), VDPAU::COutput::ProcessReturnPicture(), Actor::Message::Reply(), VAAPI::CDecoder::ReturnRenderPicture(), VDPAU::CDecoder::ReturnRenderPicture(), ActiveAE::CActiveAE::RunStages(), SendOutMessageSync(), SendOutMessageSync(), ActiveAE::CActiveAE::SetMute(), ActiveAE::CActiveAE::SetStreamAmplification(), ActiveAE::CActiveAE::SetStreamFade(), ActiveAE::CActiveAE::SetStreamFFmpegInfo(), ActiveAE::CActiveAE::SetStreamReplaygain(), ActiveAE::CActiveAE::SetStreamResampleMode(), ActiveAE::CActiveAE::SetStreamResampleRatio(), ActiveAE::CActiveAE::SetStreamVolume(), ActiveAE::CActiveAE::SetVolume(), VDPAU::COutput::StateMachine(), ActiveAE::CActiveAE::StateMachine(), ActiveAE::CActiveAE::StopSound(), ActiveAE::CActiveAE::Suspend(), and KODI::WINDOWING::WAYLAND::CWinSystemWayland::UpdateBufferScale().
SendOutMessage() [2/2]
bool Protocol::SendOutMessage (int signal, CPayloadWrapBase * payload, Message * outMsg = nullptr)
References containerOutEvent, criticalSection, GetMessage(), Actor::Message::isOut, outMessages, Actor::Message::payloadObj, CEvent::Set(), and Actor::Message::signal.
SendOutMessageSync() [1/2]
bool Protocol::SendOutMessageSync (int signal, Message ** retMsg, std::chrono::milliseconds timeout, const void * data = nullptr, size_t size = 0)
References criticalSection, data(), Actor::Message::event, GetMessage(), Actor::Message::isOut, Actor::Message::isSync, Actor::Message::isSyncTimeout, Actor::Message::Release(), Actor::Message::replyMessage, CEvent::Reset(), SendOutMessage(), and CEvent::Wait().
Referenced by VAAPI::CDecoder::ConfigVAAPI(), VDPAU::CDecoder::ConfigVDPAU(), ActiveAE::CActiveAE::DrainSink(), VDPAU::COutput::Flush(), ActiveAE::CActiveAE::FlushEngine(), ActiveAE::CActiveAE::FlushStream(), ActiveAE::CActiveAE::FreeStream(), ActiveAE::CActiveAE::InitSink(), ActiveAE::CActiveAE::MakeStream(), ActiveAE::CActiveAE::OnLostDisplay(), VAAPI::CDecoder::Release(), VDPAU::CDecoder::Release(), VAAPI::CDecoder::Reset(), VDPAU::CDecoder::Reset(), ActiveAE::CActiveAE::Resume(), ActiveAE::CActiveAE::Start(), VDPAU::COutput::StateMachine(), and ActiveAE::CActiveAE::UnconfigureSink().
SendOutMessageSync() [2/2]
bool Protocol::SendOutMessageSync (int signal, Message ** retMsg, std::chrono::milliseconds timeout, CPayloadWrapBase * payload)
References criticalSection, Actor::Message::event, GetMessage(), Actor::Message::isOut, Actor::Message::isSync, Actor::Message::isSyncTimeout, Actor::Message::Release(), Actor::Message::replyMessage, CEvent::Reset(), SendOutMessage(), and CEvent::Wait().
Unlock()
void Actor::Protocol::Unlock () inline
References criticalSection.
Referenced by Actor::Message::Release(), and Actor::Message::Reply().
Member Data Documentation
containerInEvent
CEvent* Actor::Protocol::containerInEvent protected
Referenced by SendInMessage(), and SendInMessage().
containerOutEvent
CEvent * Actor::Protocol::containerOutEvent protected
Referenced by SendOutMessage(), and SendOutMessage().
criticalSection
CCriticalSection Actor::Protocol::criticalSection protected
Referenced by GetMessage(), Lock(), PurgeIn(), PurgeOut(), ReceiveInMessage(), ReceiveOutMessage(), ReturnMessage(), SendInMessage(), SendInMessage(), SendOutMessage(), SendOutMessage(), SendOutMessageSync(), SendOutMessageSync(), and Unlock().
freeMessageQueue
std::queue<Message*> Actor::Protocol::freeMessageQueue protected
Referenced by GetMessage(), ReturnMessage(), and ~Protocol().
inDefered
bool Actor::Protocol::inDefered = false protected
Referenced by DeferIn(), and ReceiveInMessage().
inMessages
std::queue<Message*> Actor::Protocol::inMessages protected
Referenced by PurgeIn(), ReceiveInMessage(), SendInMessage(), and SendInMessage().
outDefered
bool Actor::Protocol::outDefered = false protected
Referenced by DeferOut(), and ReceiveOutMessage().
outMessages
std::queue<Message*> Actor::Protocol::outMessages protected
Referenced by PurgeOut(), ReceiveOutMessage(), SendOutMessage(), and SendOutMessage().
portName
std::string Actor::Protocol::portName
Referenced by VDPAU::CMixer::StateMachine(), VDPAU::COutput::StateMachine(), ActiveAE::CActiveAE::StateMachine(), ActiveAE::CActiveAESink::StateMachine(), and VAAPI::COutput::StateMachine().
The documentation for this class was generated from the following files:
ActorProtocol.h
ActorProtocol.cpp