Kodi Documentation: RenderFlags.cpp File Reference
RenderFlags.cpp File Reference
#include "RenderFlags.h"
#include <map>
#include <string>
Functions
unsigned int GetFlagsColorMatrix (unsigned int color_matrix, unsigned width, unsigned height)
unsigned int GetFlagsChromaPosition (unsigned int chroma_position)
unsigned int GetFlagsColorPrimaries (unsigned int color_primaries)
unsigned int GetFlagsStereoMode (const std::string &mode)
Function Documentation
GetFlagsChromaPosition()
unsigned int GetFlagsChromaPosition (unsigned int chroma_position)
References CONF_FLAGS_CHROMA_CENTER, CONF_FLAGS_CHROMA_LEFT, and CONF_FLAGS_CHROMA_TOPLEFT.
Referenced by CRendererDRMPRIME::Configure(), CRendererDRMPRIMEGLES::Configure(), CRendererMediaCodecSurface::Configure(), CRendererStarfish::Configure(), CLinuxRendererGL::Configure(), and CWinRenderer::Configure().
GetFlagsColorMatrix()
unsigned int GetFlagsColorMatrix (unsigned int color_matrix, unsigned width, unsigned height)
References CONF_FLAGS_YUVCOEF_240M, CONF_FLAGS_YUVCOEF_BT2020, CONF_FLAGS_YUVCOEF_BT601, and CONF_FLAGS_YUVCOEF_BT709.
Referenced by CRendererDRMPRIME::Configure(), CRendererDRMPRIMEGLES::Configure(), CRendererMediaCodecSurface::Configure(), CRendererStarfish::Configure(), and CWinRenderer::Configure().
GetFlagsColorPrimaries()
unsigned int GetFlagsColorPrimaries (unsigned int color_primaries)
References CONF_FLAGS_COLPRI_170M, CONF_FLAGS_COLPRI_240M, CONF_FLAGS_COLPRI_BT2020, CONF_FLAGS_COLPRI_BT470BG, CONF_FLAGS_COLPRI_BT470M, and CONF_FLAGS_COLPRI_BT709.
Referenced by CRendererDRMPRIME::Configure(), CRendererDRMPRIMEGLES::Configure(), CRendererMediaCodecSurface::Configure(), CRendererStarfish::Configure(), and CWinRenderer::Configure().
GetFlagsStereoMode()
unsigned int GetFlagsStereoMode (const std::string & mode)
References CONF_FLAGS_STEREO_CADANCE_LEFT_RIGHT, CONF_FLAGS_STEREO_CADANCE_RIGHT_LEFT, CONF_FLAGS_STEREO_MODE_SBS, and CONF_FLAGS_STEREO_MODE_TAB.
Referenced by CRendererDRMPRIME::Configure(), CRendererDRMPRIMEGLES::Configure(), CRendererMediaCodecSurface::Configure(), CRendererStarfish::Configure(), CLinuxRendererGL::Configure(), and CWinRenderer::Configure().