Kodi Documentation: CSettingNumber Class Reference
CSettingNumber Class Reference
Settings
Real number setting implementation.
#include <Setting.h>
Public Member Functions
CSettingNumber (const std::string &id, CSettingsManager *settingsManager=nullptr)
CSettingNumber (const std::string &id, const CSettingNumber &setting)
CSettingNumber (const std::string &id, int label, float value, CSettingsManager *settingsManager=nullptr)
CSettingNumber (const std::string &id, int label, float value, float minimum, float step, float maximum, CSettingsManager *settingsManager=nullptr)
~CSettingNumber () override=default
std::shared_ptr< CSetting > Clone (const std::string &id) const override
void MergeDetails (const CSetting &other) override
bool Deserialize (const TiXmlNode *node, bool update=false) override
Deserializes the given XML node into the properties of the setting object.
bool FromString (const std::string &value) override
std::string ToString () const override
bool Equals (const std::string &value) const override
bool CheckValidity (const std::string &value) const override
virtual bool CheckValidity (double value) const
void Reset () override
double GetValue () const
bool SetValue (double value)
double GetDefault () const
void SetDefault (double value)
double GetMinimum () const
void SetMinimum (double minimum)
double GetStep () const
void SetStep (double step)
double GetMaximum () const
void SetMaximum (double maximum)
Public Member Functions inherited from CTraitedSetting< double, SettingType::Number >
SettingType GetType () const override
Public Member Functions inherited from CSetting
CSetting (const std::string &id, CSettingsManager *settingsManager=nullptr)
CSetting (const std::string &id, const CSetting &setting)
~CSetting () override=default
void MergeBasics (const CSetting &other)
bool IsEnabled () const
bool GetEnabled () const
void SetEnabled (bool enabled)
bool IsDefault () const
const std::string & GetParent () const
void SetParent (const std::string &parentSetting)
SettingLevel GetLevel () const
void SetLevel (SettingLevel level)
std::shared_ptr< const ISettingControl > GetControl () const
std::shared_ptr< ISettingControl > GetControl ()
void SetControl (std::shared_ptr< ISettingControl > control)
const SettingDependencies & GetDependencies () const
void SetDependencies (const SettingDependencies &dependencies)
const std::set< CSettingUpdate > & GetUpdates () const
void SetCallback (ISettingCallback *callback)
bool IsReference () const
const std::string & GetReferencedId () const
void SetReferencedId (const std::string &referencedId)
void MakeReference (const std::string &referencedId="")
bool GetVisible () const
bool IsVisible () const override
Whether the setting object is visible or hidden.
void OnSettingAction (const std::shared_ptr< const CSetting > &setting) override
The given setting has been activated.
Public Member Functions inherited from ISetting
ISetting (const std::string &id, CSettingsManager *settingsManager=nullptr)
Creates a new setting object with the given identifier.
virtual ~ISetting ()=default
const std::string & GetId () const
Gets the identifier of the setting object.
virtual void SetVisible (bool visible)
Sets the visibility state of the setting object.
int GetLabel () const
Gets the localizeable label ID of the setting group.
void SetLabel (int label)
Sets the localizeable label ID of the setting group.
int GetHelp () const
Gets the localizeable help ID of the setting group.
void SetHelp (int help)
Sets the localizeable help ID of the setting group.
virtual bool MeetsRequirements () const
Whether the setting object meets all necessary requirements.
virtual void CheckRequirements ()
Checks if the setting object meets all necessary requirements.
virtual void SetRequirementsMet (bool requirementsMet)
Sets whether the setting object meets all necessary requirements.
Private Member Functions
virtual void copy (const CSettingNumber &setting)
Static Private Member Functions
static bool fromString (const std::string &strValue, double &value)
Private Attributes
double m_value = DefaultValue
double m_default = DefaultValue
double m_min = DefaultMin
double m_step = DefaultStep
double m_max = DefaultMax
Static Private Attributes
static constexpr Value DefaultValue = 0.0
static constexpr Value DefaultMin = DefaultValue
static constexpr Value DefaultStep = 1.0
static constexpr Value DefaultMax = DefaultValue
static Logger s_logger
Additional Inherited Members
Public Types inherited from CTraitedSetting< double, SettingType::Number >
typedef double Value
Static Public Member Functions inherited from CTraitedSetting< double, SettingType::Number >
static SettingType Type ()
Static Public Member Functions inherited from CSetting
static bool DeserializeIdentification (const TiXmlNode *node, std::string &identification, bool &isReference)
Deserializes the given XML node to retrieve a setting object's identifier and whether the setting is a reference to another setting or not.
Static Public Member Functions inherited from ISetting
static bool DeserializeIdentification (const TiXmlNode *node, std::string &identification)
Deserializes the given XML node to retrieve a setting object's identifier.
Protected Member Functions inherited from CTraitedSetting< double, SettingType::Number >
CTraitedSetting (const std::string &id, CSettingsManager *settingsManager=nullptr)
CTraitedSetting (const std::string &id, const CTraitedSetting &setting)
~CTraitedSetting () override=default
Protected Member Functions inherited from CSetting
bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting is being changed.
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode) override
The given setting needs to be updated.
void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName) override
The given property of the given setting has changed.
void Copy (const CSetting &setting)
template<class TSetting >
std::shared_ptr< TSetting > shared_from_base ()
Protected Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
Static Protected Member Functions inherited from ISetting
static bool DeserializeIdentificationFromAttribute (const TiXmlNode *node, const std::string &attribute, std::string &identification)
Deserializes the given XML node to retrieve a setting object's identifier from the given attribute.
Protected Attributes inherited from CSetting
ISettingCallback * m_callback = nullptr
bool m_enabled = true
std::string m_parentSetting
SettingLevel m_level = SettingLevel::Standard
std::shared_ptr< ISettingControl > m_control
SettingDependencies m_dependencies
std::set< CSettingUpdate > m_updates
bool m_changed = false
CSharedSection m_critical
std::string m_referencedId
Protected Attributes inherited from ISetting
std::string m_id
CSettingsManager * m_settingsManager
Static Protected Attributes inherited from ISetting
static constexpr int DefaultLabel = -1
Detailed Description
Real number setting implementation.
See also
CSetting
Constructor & Destructor Documentation
CSettingNumber() [1/4]
CSettingNumber::CSettingNumber (const std::string & id, CSettingsManager * settingsManager = nullptr)
CSettingNumber() [2/4]
CSettingNumber::CSettingNumber (const std::string & id, const CSettingNumber & setting)
References copy().
CSettingNumber() [3/4]
CSettingNumber::CSettingNumber (const std::string & id, int label, float value, CSettingsManager * settingsManager = nullptr)
CSettingNumber() [4/4]
CSettingNumber::CSettingNumber (const std::string & id, int label, float value, float minimum, float step, float maximum, CSettingsManager * settingsManager = nullptr)
References CLog::GetLogger(), CServiceBroker::GetLogging(), label, s_logger, and ISetting::SetLabel().
~CSettingNumber()
CSettingNumber::~CSettingNumber () override default
Member Function Documentation
CheckValidity() [1/2]
bool CSettingNumber::CheckValidity (const std::string & value) const override virtual
Implements CSetting.
References CheckValidity(), fromString(), and value.
Referenced by CheckValidity(), and SetValue().
CheckValidity() [2/2]
bool CSettingNumber::CheckValidity (double value) const virtual
References CSetting::m_critical, m_max, and m_min.
Clone()
SettingPtr CSettingNumber::Clone (const std::string & id) const override virtual
Implements CSetting.
copy()
void CSettingNumber::copy (const CSettingNumber & setting) private virtual
References CSetting::Copy(), CSetting::m_critical, m_default, m_max, m_min, m_step, and m_value.
Referenced by CSettingNumber().
Deserialize()
bool CSettingNumber::Deserialize (const TiXmlNode * node, bool update = false) override virtual
Deserializes the given XML node into the properties of the setting object.
If the update parameter is true, the checks for mandatory properties are skipped and values are only updated.
Parameters
node XML node containing the properties of the setting object
update Whether to perform checks for mandatory properties or not
Returns
True if deserialization was successful, false otherwise
Reimplemented from CSetting.
References CSetting::Deserialize(), XMLUtils::GetDouble(), CSetting::m_critical, m_default, ISetting::m_id, m_max, m_min, m_step, m_value, node, s_logger, SETTING_XML_ELM_CONSTRAINTS, SETTING_XML_ELM_DEFAULT, SETTING_XML_ELM_MAXIMUM, SETTING_XML_ELM_MINIMUM, SETTING_XML_ELM_STEP, and value.
Equals()
bool CSettingNumber::Equals (const std::string & value) const override virtual
Implements CSetting.
References fromString(), CSetting::m_critical, m_value, and value.
fromString()
bool CSettingNumber::fromString (const std::string & strValue, double & value) static private
References end(), and value.
Referenced by CheckValidity(), Equals(), and FromString().
FromString()
bool CSettingNumber::FromString (const std::string & value) override virtual
Implements CSetting.
References fromString(), SetValue(), and value.
GetDefault()
double CSettingNumber::GetDefault () const inline
References m_default.
GetMaximum()
double CSettingNumber::GetMaximum () const inline
References m_max.
GetMinimum()
double CSettingNumber::GetMinimum () const inline
References m_min.
GetStep()
double CSettingNumber::GetStep () const inline
References m_step.
GetValue()
double CSettingNumber::GetValue () const inline
References CSetting::m_critical, and m_value.
MergeDetails()
void CSettingNumber::MergeDetails (const CSetting & other) override virtual
Implements CSetting.
References CSetting::GetType(), m_default, m_max, m_min, m_step, m_value, and Number.
Reset()
void CSettingNumber::Reset () inline override virtual
Implements CSetting.
References m_default, and SetValue().
SetDefault()
void CSettingNumber::SetDefault (double value)
References CSetting::m_changed, CSetting::m_critical, m_default, m_value, and value.
SetMaximum()
void CSettingNumber::SetMaximum (double maximum) inline
References m_max.
SetMinimum()
void CSettingNumber::SetMinimum (double minimum) inline
References m_min.
SetStep()
void CSettingNumber::SetStep (double step) inline
References m_step.
SetValue()
bool CSettingNumber::SetValue (double value)
References CheckValidity(), CSetting::m_changed, CSetting::m_critical, m_default, m_value, CSetting::OnSettingChanged(), CSetting::OnSettingChanging(), and value.
Referenced by FromString(), and Reset().
ToString()
std::string CSettingNumber::ToString () const override virtual
Implements CSetting.
References m_value.
Member Data Documentation
DefaultMax
constexpr Value CSettingNumber::DefaultMax = DefaultValue static constexpr private
DefaultMin
constexpr Value CSettingNumber::DefaultMin = DefaultValue static constexpr private
DefaultStep
constexpr Value CSettingNumber::DefaultStep = 1.0 static constexpr private
DefaultValue
constexpr Value CSettingNumber::DefaultValue = 0.0 static constexpr private
m_default
double CSettingNumber::m_default = DefaultValue private
Referenced by copy(), Deserialize(), GetDefault(), MergeDetails(), Reset(), SetDefault(), and SetValue().
m_max
double CSettingNumber::m_max = DefaultMax private
Referenced by CheckValidity(), copy(), Deserialize(), GetMaximum(), MergeDetails(), and SetMaximum().
m_min
double CSettingNumber::m_min = DefaultMin private
Referenced by CheckValidity(), copy(), Deserialize(), GetMinimum(), MergeDetails(), and SetMinimum().
m_step
double CSettingNumber::m_step = DefaultStep private
Referenced by copy(), Deserialize(), GetStep(), MergeDetails(), and SetStep().
m_value
double CSettingNumber::m_value = DefaultValue private
Referenced by copy(), Deserialize(), Equals(), GetValue(), MergeDetails(), SetDefault(), SetValue(), and ToString().
s_logger
Logger CSettingNumber::s_logger static private
Referenced by CSettingNumber(), and Deserialize().
The documentation for this class was generated from the following files:
Setting.h
Setting.cpp