Kodi Documentation: CDriverMonitor Class Reference
CDriverMonitor Class Reference
Public Member Functions
CDriverMonitor ()=default
virtual ~CDriverMonitor ()
bool Start (bool allowPipeWireCompatServer)
bool IsInitialized ()
Public Attributes
CCriticalSection m_sec
Protected Attributes
pa_context * m_pContext = nullptr
pa_threaded_mainloop * m_pMainLoop = nullptr
bool m_isInit = false
Constructor & Destructor Documentation
CDriverMonitor()
CDriverMonitor::CDriverMonitor () default
~CDriverMonitor()
CDriverMonitor::~CDriverMonitor () virtual
References m_isInit, m_pContext, and m_pMainLoop.
Member Function Documentation
IsInitialized()
bool CDriverMonitor::IsInitialized ()
References m_isInit.
Referenced by SinkCallback().
Start()
bool CDriverMonitor::Start (bool allowPipeWireCompatServer)
References CLog::Log(), LOGINFO, ServerInfoStruct::m_isInfoSet, m_isInit, ServerInfoStruct::m_mainloop, m_pContext, m_pMainLoop, m_sec, ServerInfoStruct::m_serverName, ServerInfoCallback(), SetupContext(), and SinkCallback().
Member Data Documentation
m_isInit
bool CDriverMonitor::m_isInit = false protected
Referenced by IsInitialized(), Start(), and ~CDriverMonitor().
m_pContext
pa_context* CDriverMonitor::m_pContext = nullptr protected
Referenced by Start(), and ~CDriverMonitor().
m_pMainLoop
pa_threaded_mainloop* CDriverMonitor::m_pMainLoop = nullptr protected
Referenced by Start(), and ~CDriverMonitor().
m_sec
CCriticalSection CDriverMonitor::m_sec
Referenced by SinkCallback(), and Start().
The documentation for this class was generated from the following file:
AESinkPULSE.cpp