Kodi Documentation: JSONRPC::CJSONRPC Class Reference
JSONRPC::CJSONRPC Class Reference
Interfaces » JSON-RPC
JSON RPC handler.
#include <JSONRPC.h>
Static Public Member Functions
static void Initialize ()
Initializes the JSON-RPC handler.
static void Cleanup ()
static std::string MethodCall (const std::string &inputString, ITransportLayer *transport, IClient *client)
static JSONRPC_STATUS Introspect (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Version (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Permission (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS Ping (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS GetConfiguration (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS SetConfiguration (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS NotifyAll (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
Static Private Member Functions
static bool HandleMethodCall (const CVariant &request, CVariant &response, ITransportLayer *transport, IClient *client)
static bool IsProperJSONRPC (const CVariant &inputroot)
static void BuildResponse (const CVariant &request, JSONRPC_STATUS code, const CVariant &result, CVariant &response)
Static Private Attributes
static bool m_initialized = false
Detailed Description
JSON RPC handler.
Sets up and manages all needed information to process JSON-RPC requests and answering with the appropriate JSON-RPC response (actual response or error message).
Member Function Documentation
BuildResponse()
void CJSONRPC::BuildResponse (const CVariant & request, JSONRPC_STATUS code, const CVariant & result, CVariant & response) inline static private
References JSONRPC::ACK, JSONRPC::BadPermission, JSONRPC::FailedToExecute, JSONRPC::InternalError, JSONRPC::InvalidParams, JSONRPC::InvalidRequest, CVariant::isMember(), CVariant::isNull(), JSONRPC::MethodNotFound, JSONRPC::OK, and JSONRPC::ParseError.
Referenced by HandleMethodCall(), and MethodCall().
Cleanup()
void CJSONRPC::Cleanup () static
References JSONRPC::CJSONServiceDescription::Cleanup(), and m_initialized.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and CNetworkServices::~CNetworkServices().
GetConfiguration()
JSONRPC_STATUS CJSONRPC::GetConfiguration (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References ANNOUNCEMENT::ANNOUNCE_ALL, JSONRPC::IClient::GetAnnouncementFlags(), and JSONRPC::OK.
Referenced by SetConfiguration().
HandleMethodCall()
bool CJSONRPC::HandleMethodCall (const CVariant & request, CVariant & response, ITransportLayer * transport, IClient * client) static private
References CVariant::asString(), BuildResponse(), JSONRPC::CJSONServiceDescription::CheckCall(), JSONRPC::InvalidRequest, CVariant::isMember(), IsProperJSONRPC(), CLog::Log(), LOGERROR, JSONRPC::OK, and CJSONVariantWriter::Write().
Referenced by MethodCall().
Initialize()
void CJSONRPC::Initialize () static
Initializes the JSON-RPC handler.
References JSONRPC::CJSONServiceDescription::AddBuiltinMethod(), JSONRPC::CJSONServiceDescription::AddEnum(), JSONRPC::CJSONServiceDescription::AddNotification(), JSONRPC::CJSONServiceDescription::AddType(), KODI::ACTION::CActionTranslator::GetActions(), KODI::PLAYLIST::CSmartPlaylist::GetAvailableFields(), CTextureRule::GetAvailableFields(), CDatabaseQueryRule::GetAvailableOperators(), JSONRPC::CJSONServiceDescription::GetVersion(), CWindowTranslator::GetWindows(), index(), CLog::Log(), LOGINFO, m_initialized, ADDON::MAX_TYPES, JSONRPC::CJSONServiceDescription::ResolveReferences(), ADDON::CAddonInfo::TranslateType(), and ADDON::UNKNOWN.
Referenced by CProfileManager::FinalizeLoadProfile(), CApplication::Initialize(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
Introspect()
JSONRPC_STATUS CJSONRPC::Introspect (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::CJSONServiceDescription::Print().
IsProperJSONRPC()
bool CJSONRPC::IsProperJSONRPC (const CVariant & inputroot) inline static private
References CVariant::isArray(), CVariant::isMember(), CVariant::isObject(), and CVariant::isString().
Referenced by HandleMethodCall().
MethodCall()
std::string CJSONRPC::MethodCall (const std::string & inputString, ITransportLayer * transport, IClient * client) static
References CVariant::append(), CVariant::begin_array(), BuildResponse(), CVariant::end_array(), CServiceBroker::GetSettingsComponent(), HandleMethodCall(), JSONRPC::InvalidRequest, CVariant::isArray(), CVariant::isNull(), CLog::Log(), LOGDEBUG, LOGERROR, LOGJSONRPC, CJSONVariantParser::Parse(), JSONRPC::ParseError, CVariant::size(), and CJSONVariantWriter::Write().
Referenced by jni::CJNIXBMCJsonHandler::_requestJSON(), XBMCAddon::xbmc::executeJSONRPC(), CHTTPJsonRpcHandler::HandleRequest(), and JSONRPC::CTCPServer::CTCPClient::PushBuffer().
NotifyAll()
JSONRPC_STATUS CJSONRPC::NotifyAll (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, data(), CServiceBroker::GetAnnouncementManager(), and ANNOUNCEMENT::Other.
Permission()
JSONRPC_STATUS CJSONRPC::Permission (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::IClient::GetPermissionFlags(), JSONRPC::OK, JSONRPC::OPERATION_PERMISSION_ALL, and JSONRPC::PermissionToString().
Ping()
JSONRPC_STATUS CJSONRPC::Ping (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::OK, and CVariant::swap().
SetConfiguration()
JSONRPC_STATUS CJSONRPC::SetConfiguration (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References ANNOUNCEMENT::Application, ANNOUNCEMENT::AudioLibrary, JSONRPC::BadPermission, JSONRPC::IClient::GetAnnouncementFlags(), GetConfiguration(), ANNOUNCEMENT::GUI, ANNOUNCEMENT::Input, CVariant::isMember(), ANNOUNCEMENT::Other, ANNOUNCEMENT::Player, ANNOUNCEMENT::Playlist, JSONRPC::IClient::SetAnnouncementFlags(), ANNOUNCEMENT::System, and ANNOUNCEMENT::VideoLibrary.
Version()
JSONRPC_STATUS CJSONRPC::Version (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::CJSONServiceDescription::GetVersion(), and JSONRPC::OK.
Member Data Documentation
m_initialized
bool CJSONRPC::m_initialized = false static private
Referenced by Cleanup(), and Initialize().
The documentation for this class was generated from the following files:
JSONRPC.h
JSONRPC.cpp