Kodi Documentation: TestStopwatch.cpp File Reference
TestStopwatch.cpp File Reference
#include "threads/Thread.h"
#include "utils/Stopwatch.h"
#include <gtest/gtest.h>
Classes
class CTestStopWatchThread
Functions
TEST (TestStopWatch, Initialization)
TEST (TestStopWatch, Start)
TEST (TestStopWatch, Stop)
TEST (TestStopWatch, ElapsedTime)
TEST (TestStopWatch, Reset)
Function Documentation
TEST() [1/5]
TEST (TestStopWatch , ElapsedTime)
References CStopWatch::GetElapsedMilliseconds(), CStopWatch::GetElapsedSeconds(), and CStopWatch::Start().
TEST() [2/5]
TEST (TestStopWatch , Initialization)
References EXPECT_EQ(), CStopWatch::GetElapsedMilliseconds(), CStopWatch::GetElapsedSeconds(), and CStopWatch::IsRunning().
TEST() [3/5]
TEST (TestStopWatch , Reset)
References CStopWatch::GetElapsedMilliseconds(), CStopWatch::Reset(), and CStopWatch::StartZero().
TEST() [4/5]
TEST (TestStopWatch , Start)
References EXPECT_TRUE(), CStopWatch::IsRunning(), and CStopWatch::Start().
TEST() [5/5]
TEST (TestStopWatch , Stop)
References CStopWatch::IsRunning(), CStopWatch::Start(), and CStopWatch::Stop().