Kodi Documentation: KODI::WINDOWING::WINDOWS Namespace Reference
KODI::WINDOWING::WINDOWS Namespace Reference
Functions
static void DIB_InitOSKeymap ()
Variables
static std::array< XBMCKey, XBMCK_LAST > VK_keymap
Function Documentation
DIB_InitOSKeymap()
static void KODI::WINDOWING::WINDOWS::DIB_InitOSKeymap () static
References CServiceBroker::GetSettingsComponent(), VK_0, VK_1, VK_2, VK_3, VK_4, VK_5, VK_6, VK_7, VK_8, VK_9, VK_A, VK_APOSTROPHE, VK_B, VK_BACKSLASH, VK_BACKTICK, VK_C, VK_COMMA, VK_D, VK_E, VK_EQUALS, VK_F, VK_G, VK_GRAVE, VK_H, VK_I, VK_J, VK_K, VK_keymap, VK_L, VK_LBRACKET, VK_M, VK_MINUS, VK_N, VK_O, VK_OEM_102, VK_P, VK_PERIOD, VK_Q, VK_R, VK_RBRACKET, VK_S, VK_SEMICOLON, VK_SLASH, VK_T, VK_U, VK_V, VK_W, VK_X, VK_Y, VK_Z, XBMCK_0, XBMCK_1, XBMCK_2, XBMCK_3, XBMCK_4, XBMCK_5, XBMCK_6, XBMCK_7, XBMCK_8, XBMCK_9, XBMCK_a, XBMCK_b, XBMCK_BACKQUOTE, XBMCK_BACKSLASH, XBMCK_BACKSPACE, XBMCK_BREAK, XBMCK_BROWSER_BACK, XBMCK_BROWSER_FAVORITES, XBMCK_BROWSER_FORWARD, XBMCK_BROWSER_HOME, XBMCK_BROWSER_REFRESH, XBMCK_BROWSER_SEARCH, XBMCK_BROWSER_STOP, XBMCK_c, XBMCK_CAPSLOCK, XBMCK_CLEAR, XBMCK_COMMA, XBMCK_d, XBMCK_DELETE, XBMCK_DOWN, XBMCK_e, XBMCK_END, XBMCK_EQUALS, XBMCK_ESCAPE, XBMCK_f, XBMCK_F1, XBMCK_F10, XBMCK_F11, XBMCK_F12, XBMCK_F13, XBMCK_F14, XBMCK_F15, XBMCK_F2, XBMCK_F3, XBMCK_F4, XBMCK_F5, XBMCK_F6, XBMCK_F7, XBMCK_F8, XBMCK_F9, XBMCK_g, XBMCK_h, XBMCK_HELP, XBMCK_HOME, XBMCK_i, XBMCK_INSERT, XBMCK_j, XBMCK_k, XBMCK_KP0, XBMCK_KP1, XBMCK_KP2, XBMCK_KP3, XBMCK_KP4, XBMCK_KP5, XBMCK_KP6, XBMCK_KP7, XBMCK_KP8, XBMCK_KP9, XBMCK_KP_DIVIDE, XBMCK_KP_MINUS, XBMCK_KP_MULTIPLY, XBMCK_KP_PERIOD, XBMCK_KP_PLUS, XBMCK_l, XBMCK_LALT, XBMCK_LAUNCH_APP1, XBMCK_LAUNCH_APP2, XBMCK_LAUNCH_MAIL, XBMCK_LAUNCH_MEDIA_SELECT, XBMCK_LCTRL, XBMCK_LEFT, XBMCK_LEFTBRACKET, XBMCK_LSHIFT, XBMCK_LSUPER, XBMCK_m, XBMCK_MEDIA_NEXT_TRACK, XBMCK_MEDIA_PLAY_PAUSE, XBMCK_MEDIA_PREV_TRACK, XBMCK_MEDIA_STOP, XBMCK_MENU, XBMCK_MINUS, XBMCK_n, XBMCK_NUMLOCK, XBMCK_o, XBMCK_p, XBMCK_PAGEDOWN, XBMCK_PAGEUP, XBMCK_PAUSE, XBMCK_PERIOD, XBMCK_PRINT, XBMCK_q, XBMCK_QUOTE, XBMCK_r, XBMCK_RALT, XBMCK_RCTRL, XBMCK_RETURN, XBMCK_RIGHT, XBMCK_RIGHTBRACKET, XBMCK_RSHIFT, XBMCK_RSUPER, XBMCK_s, XBMCK_SCROLLOCK, XBMCK_SEMICOLON, XBMCK_SLASH, XBMCK_SPACE, XBMCK_t, XBMCK_TAB, XBMCK_u, XBMCK_UNKNOWN, XBMCK_UP, XBMCK_v, XBMCK_VOLUME_DOWN, XBMCK_VOLUME_MUTE, XBMCK_VOLUME_UP, XBMCK_w, XBMCK_x, XBMCK_y, and XBMCK_z.
Referenced by CWinEventsWin10::InitOSKeymap(), and CWinEventsWin32::WndProc().
Variable Documentation
VK_keymap
std::array<XBMCKey, XBMCK_LAST> KODI::WINDOWING::WINDOWS::VK_keymap static
Referenced by DIB_InitOSKeymap(), and CWinEventsWin10::Kodi_KeyEvent().