Kodi Documentation: AddonToKodiFuncTable_PVR Struct Reference
AddonToKodiFuncTable_PVR Struct Reference
Structure to transfer the methods from Kodi to addon.
#include <pvr.h>
Public Attributes
KODI_HANDLE kodiInstance
void(* AddMenuHook)(void *kodiInstance, const struct PVR_MENUHOOK *hook)
void(* RecordingNotification)(void *kodiInstance, const char *name, const char *fileName, bool on)
void(* ConnectionStateChange)(void *kodiInstance, const char *strConnectionString, enum PVR_CONNECTION_STATE newState, const char *strMessage)
void(* EpgEventStateChange)(void *kodiInstance, struct EPG_TAG *tag, enum EPG_EVENT_STATE newState)
void(* TransferChannelEntry)(void *kodiInstance, const PVR_HANDLE handle, const struct PVR_CHANNEL *chan)
void(* TransferProviderEntry)(void *kodiInstance, const PVR_HANDLE handle, const struct PVR_PROVIDER *chanProvider)
void(* TransferChannelGroup)(void *kodiInstance, const PVR_HANDLE handle, const struct PVR_CHANNEL_GROUP *group)
void(* TransferChannelGroupMember)(void *kodiInstance, const PVR_HANDLE handle, const struct PVR_CHANNEL_GROUP_MEMBER *member)
void(* TransferEpgEntry)(void *kodiInstance, const PVR_HANDLE handle, const struct EPG_TAG *epgentry)
void(* TransferRecordingEntry)(void *kodiInstance, const PVR_HANDLE handle, const struct PVR_RECORDING *recording)
void(* TransferTimerEntry)(void *kodiInstance, const PVR_HANDLE handle, const struct PVR_TIMER *timer)
void(* TriggerChannelUpdate)(void *kodiInstance)
void(* TriggerProvidersUpdate)(void *kodiInstance)
void(* TriggerChannelGroupsUpdate)(void *kodiInstance)
void(* TriggerEpgUpdate)(void *kodiInstance, unsigned int iChannelUid)
void(* TriggerRecordingUpdate)(void *kodiInstance)
void(* TriggerTimerUpdate)(void *kodiInstance)
void(* FreeDemuxPacket)(void *kodiInstance, struct DEMUX_PACKET *pPacket)
struct DEMUX_PACKET *(* AllocateDemuxPacket)(void *kodiInstance, int iDataSize)
struct PVR_CODEC(* GetCodecByName)(const void *kodiInstance, const char *strCodecName)
Detailed Description
Structure to transfer the methods from Kodi to addon.
Member Data Documentation
AddMenuHook
void(* AddonToKodiFuncTable_PVR::AddMenuHook) (void *kodiInstance, const struct PVR_MENUHOOK *hook)
Referenced by PVR::CPVRClient::ResetProperties().
AllocateDemuxPacket
struct DEMUX_PACKET *(* AddonToKodiFuncTable_PVR::AllocateDemuxPacket) (void *kodiInstance, int iDataSize)
Referenced by PVR::CPVRClient::ResetProperties().
ConnectionStateChange
void(* AddonToKodiFuncTable_PVR::ConnectionStateChange) (void *kodiInstance, const char *strConnectionString, enum PVR_CONNECTION_STATE newState, const char *strMessage)
Referenced by PVR::CPVRClient::ResetProperties().
EpgEventStateChange
void(* AddonToKodiFuncTable_PVR::EpgEventStateChange) (void *kodiInstance, struct EPG_TAG *tag, enum EPG_EVENT_STATE newState)
Referenced by PVR::CPVRClient::ResetProperties().
FreeDemuxPacket
void(* AddonToKodiFuncTable_PVR::FreeDemuxPacket) (void *kodiInstance, struct DEMUX_PACKET *pPacket)
Referenced by PVR::CPVRClient::ResetProperties().
GetCodecByName
struct PVR_CODEC(* AddonToKodiFuncTable_PVR::GetCodecByName) (const void *kodiInstance, const char *strCodecName)
Referenced by PVR::CPVRClient::ResetProperties().
kodiInstance
KODI_HANDLE AddonToKodiFuncTable_PVR::kodiInstance
Referenced by kodi::addon::PVRChannelsResultSet::Add(), kodi::addon::PVRChannelGroupsResultSet::Add(), kodi::addon::PVRChannelGroupMembersResultSet::Add(), kodi::addon::PVREPGTagsResultSet::Add(), kodi::addon::PVRProvidersResultSet::Add(), kodi::addon::PVRRecordingsResultSet::Add(), kodi::addon::PVRTimersResultSet::Add(), and PVR::CPVRClient::ResetProperties().
RecordingNotification
void(* AddonToKodiFuncTable_PVR::RecordingNotification) (void *kodiInstance, const char *name, const char *fileName, bool on)
Referenced by PVR::CPVRClient::ResetProperties().
TransferChannelEntry
void(* AddonToKodiFuncTable_PVR::TransferChannelEntry) (void *kodiInstance, const PVR_HANDLE handle, const struct PVR_CHANNEL *chan)
Referenced by kodi::addon::PVRChannelsResultSet::Add(), and PVR::CPVRClient::ResetProperties().
TransferChannelGroup
void(* AddonToKodiFuncTable_PVR::TransferChannelGroup) (void *kodiInstance, const PVR_HANDLE handle, const struct PVR_CHANNEL_GROUP *group)
Referenced by kodi::addon::PVRChannelGroupsResultSet::Add(), and PVR::CPVRClient::ResetProperties().
TransferChannelGroupMember
void(* AddonToKodiFuncTable_PVR::TransferChannelGroupMember) (void *kodiInstance, const PVR_HANDLE handle, const struct PVR_CHANNEL_GROUP_MEMBER *member)
Referenced by kodi::addon::PVRChannelGroupMembersResultSet::Add(), and PVR::CPVRClient::ResetProperties().
TransferEpgEntry
void(* AddonToKodiFuncTable_PVR::TransferEpgEntry) (void *kodiInstance, const PVR_HANDLE handle, const struct EPG_TAG *epgentry)
Referenced by kodi::addon::PVREPGTagsResultSet::Add(), and PVR::CPVRClient::ResetProperties().
TransferProviderEntry
void(* AddonToKodiFuncTable_PVR::TransferProviderEntry) (void *kodiInstance, const PVR_HANDLE handle, const struct PVR_PROVIDER *chanProvider)
Referenced by kodi::addon::PVRProvidersResultSet::Add(), and PVR::CPVRClient::ResetProperties().
TransferRecordingEntry
void(* AddonToKodiFuncTable_PVR::TransferRecordingEntry) (void *kodiInstance, const PVR_HANDLE handle, const struct PVR_RECORDING *recording)
Referenced by kodi::addon::PVRRecordingsResultSet::Add(), and PVR::CPVRClient::ResetProperties().
TransferTimerEntry
void(* AddonToKodiFuncTable_PVR::TransferTimerEntry) (void *kodiInstance, const PVR_HANDLE handle, const struct PVR_TIMER *timer)
Referenced by kodi::addon::PVRTimersResultSet::Add(), and PVR::CPVRClient::ResetProperties().
TriggerChannelGroupsUpdate
void(* AddonToKodiFuncTable_PVR::TriggerChannelGroupsUpdate) (void *kodiInstance)
Referenced by PVR::CPVRClient::ResetProperties().
TriggerChannelUpdate
void(* AddonToKodiFuncTable_PVR::TriggerChannelUpdate) (void *kodiInstance)
Referenced by PVR::CPVRClient::ResetProperties().
TriggerEpgUpdate
void(* AddonToKodiFuncTable_PVR::TriggerEpgUpdate) (void *kodiInstance, unsigned int iChannelUid)
Referenced by PVR::CPVRClient::ResetProperties().
TriggerProvidersUpdate
void(* AddonToKodiFuncTable_PVR::TriggerProvidersUpdate) (void *kodiInstance)
Referenced by PVR::CPVRClient::ResetProperties().
TriggerRecordingUpdate
void(* AddonToKodiFuncTable_PVR::TriggerRecordingUpdate) (void *kodiInstance)
Referenced by PVR::CPVRClient::ResetProperties().
TriggerTimerUpdate
void(* AddonToKodiFuncTable_PVR::TriggerTimerUpdate) (void *kodiInstance)
Referenced by PVR::CPVRClient::ResetProperties().
The documentation for this struct was generated from the following file:
c-api/addon-instance/pvr.h