Kodi Documentation: CVideoPlayerAudioID3 Class Reference
CVideoPlayerAudioID3 Class Reference
#include <VideoPlayerAudioID3.h>
Public Member Functions
CVideoPlayerAudioID3 (CProcessInfo &processInfo)
~CVideoPlayerAudioID3 () override
bool CheckStream (const CDVDStreamInfo &hints)
void Flush ()
void WaitForBuffers ()
bool OpenStream (CDVDStreamInfo hints) override
void CloseStream (bool bWaitForBuffers) override
void SendMessage (std::shared_ptr< CDVDMsg > pMsg, int priority=0) override
void FlushMessages () override
bool IsInited () const override
bool AcceptsData () const override
bool IsStalled () const override
Public Member Functions inherited from IDVDStreamPlayer
IDVDStreamPlayer (CProcessInfo &processInfo)
virtual ~IDVDStreamPlayer ()=default
Protected Member Functions
void OnExit () override
void Process () override
Private Member Functions
void ProcessID3 (const unsigned char *data, unsigned int length) const
void ProcessID3v1 (const TagLib::ID3v1::Tag *tag) const
void ProcessID3v2 (const TagLib::ID3v2::Tag *tag) const
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
virtual void OnStartup ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Static Private Member Functions
static std::vector< std::string > GetID3v2StringList (const TagLib::ID3v2::FrameList &frameList)
static std::vector< std::string > StringListToVectorString (const TagLib::StringList &stringList)
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Private Attributes
int m_speed = DVD_PLAYSPEED_NORMAL
CCriticalSection m_critSection
CDVDMessageQueue m_messageQueue
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Additional Inherited Members
Public Types inherited from IDVDStreamPlayer
enum ESyncState { SYNC_STARTING , SYNC_WAITSYNC , SYNC_INSYNC }
Protected Attributes inherited from IDVDStreamPlayer
CProcessInfo & m_processInfo
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Constructor & Destructor Documentation
CVideoPlayerAudioID3()
CVideoPlayerAudioID3::CVideoPlayerAudioID3 (CProcessInfo & processInfo) explicit
References CLog::Log(), and LOGDEBUG.
~CVideoPlayerAudioID3()
CVideoPlayerAudioID3::~CVideoPlayerAudioID3 () override
References CLog::Log(), LOGDEBUG, and CThread::StopThread().
Member Function Documentation
AcceptsData()
bool CVideoPlayerAudioID3::AcceptsData () const override virtual
Implements IDVDStreamPlayer.
References CDVDMessageQueue::IsFull(), and m_messageQueue.
CheckStream()
bool CVideoPlayerAudioID3::CheckStream (const CDVDStreamInfo & hints)
References STREAM_AUDIO_ID3, and CDVDStreamInfo::type.
CloseStream()
void CVideoPlayerAudioID3::CloseStream (bool bWaitForBuffers) override virtual
Implements IDVDStreamPlayer.
References CDVDMessageQueue::Abort(), CDVDMessageQueue::End(), CLog::Log(), LOGINFO, m_messageQueue, and CThread::StopThread().
Referenced by OpenStream().
Flush()
void CVideoPlayerAudioID3::Flush ()
References CDVDMessageQueue::Flush(), CDVDMsg::GENERAL_FLUSH, CDVDMessageQueue::IsInited(), m_messageQueue, and CDVDMessageQueue::Put().
Referenced by OpenStream().
FlushMessages()
void CVideoPlayerAudioID3::FlushMessages () override virtual
Implements IDVDStreamPlayer.
References CDVDMessageQueue::Flush(), and m_messageQueue.
GetID3v2StringList()
std::vector< std::string > CVideoPlayerAudioID3::GetID3v2StringList (const TagLib::ID3v2::FrameList & frameList) static private
References StringListToVectorString().
Referenced by ProcessID3v2().
IsInited()
bool CVideoPlayerAudioID3::IsInited () const override virtual
Implements IDVDStreamPlayer.
IsStalled()
bool CVideoPlayerAudioID3::IsStalled () const override virtual
Implements IDVDStreamPlayer.
OnExit()
void CVideoPlayerAudioID3::OnExit () override protected virtual
Reimplemented from CThread.
References CLog::Log(), and LOGINFO.
OpenStream()
bool CVideoPlayerAudioID3::OpenStream (CDVDStreamInfo hints) override virtual
Implements IDVDStreamPlayer.
References CloseStream(), CThread::Create(), Flush(), CDVDMessageQueue::Init(), CLog::Log(), LOGINFO, m_messageQueue, STREAM_AUDIO_ID3, and CDVDStreamInfo::type.
Process()
void CVideoPlayerAudioID3::Process (void) override protected virtual
Reimplemented from CThread.
References CDVDMsg::DEMUXER_PACKET, DVD_PLAYSPEED_PAUSE, CDVDMessageQueue::Get(), DEMUX_PACKET::iSize, CLog::Log(), LOGERROR, LOGINFO, CThread::m_bStop, m_critSection, m_messageQueue, m_speed, MSGQ_IS_ERROR, MSGQ_TIMEOUT, DEMUX_PACKET::pData, CDVDMsg::PLAYER_SETSPEED, ProcessID3(), and CDVDMessageQueue::ReceivedAbortRequest().
ProcessID3()
void CVideoPlayerAudioID3::ProcessID3 (const unsigned char * data, unsigned int length) const private
References data(), ProcessID3v1(), and ProcessID3v2().
Referenced by Process().
ProcessID3v1()
void CVideoPlayerAudioID3::ProcessID3v1 (const TagLib::ID3v1::Tag * tag) const private
References g_application, CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), MUSIC_INFO::CMusicInfoTag::SetAlbum(), MUSIC_INFO::CMusicInfoTag::SetArtist(), MUSIC_INFO::CMusicInfoTag::SetComment(), CGUIInfoManager::SetCurrentItem(), MUSIC_INFO::CMusicInfoTag::SetGenre(), MUSIC_INFO::CMusicInfoTag::SetTitle(), MUSIC_INFO::CMusicInfoTag::SetTrackNumber(), MUSIC_INFO::CMusicInfoTag::SetYear(), and String.
Referenced by ProcessID3().
ProcessID3v2()
void CVideoPlayerAudioID3::ProcessID3v2 (const TagLib::ID3v2::Tag * tag) const private
References g_application, CServiceBroker::GetGUI(), GetID3v2StringList(), CGUIComponent::GetInfoManager(), MUSIC_INFO::CMusicInfoTag::SetAlbum(), MUSIC_INFO::CMusicInfoTag::SetArtist(), MUSIC_INFO::CMusicInfoTag::SetComment(), CGUIInfoManager::SetCurrentItem(), MUSIC_INFO::CMusicInfoTag::SetGenre(), MUSIC_INFO::CMusicInfoTag::SetTitle(), MUSIC_INFO::CMusicInfoTag::SetTrackNumber(), and MUSIC_INFO::CMusicInfoTag::SetYear().
Referenced by ProcessID3().
SendMessage()
void CVideoPlayerAudioID3::SendMessage (std::shared_ptr< CDVDMsg > pMsg, int priority = 0) override virtual
Implements IDVDStreamPlayer.
References CDVDMessageQueue::IsInited(), m_messageQueue, and CDVDMessageQueue::Put().
StringListToVectorString()
std::vector< std::string > CVideoPlayerAudioID3::StringListToVectorString (const TagLib::StringList & stringList) static private
References value, and values.
Referenced by GetID3v2StringList().
WaitForBuffers()
void CVideoPlayerAudioID3::WaitForBuffers ()
References m_messageQueue, and CDVDMessageQueue::WaitUntilEmpty().
Member Data Documentation
m_critSection
CCriticalSection CVideoPlayerAudioID3::m_critSection private
Referenced by Process().
m_messageQueue
CDVDMessageQueue CVideoPlayerAudioID3::m_messageQueue private
Referenced by AcceptsData(), CloseStream(), Flush(), FlushMessages(), OpenStream(), Process(), SendMessage(), and WaitForBuffers().
m_speed
int CVideoPlayerAudioID3::m_speed = DVD_PLAYSPEED_NORMAL private
Referenced by Process().
The documentation for this class was generated from the following files:
VideoPlayerAudioID3.h
VideoPlayerAudioID3.cpp