Kodi Documentation: CWinSystemBase Class Reference
CWinSystemBase Class Reference abstract
#include <WinSystem.h>
Public Member Functions
CWinSystemBase ()
virtual ~CWinSystemBase ()
virtual CRenderSystemBase * GetRenderSystem ()
virtual const std::string GetName ()
virtual bool InitWindowSystem ()
virtual bool DestroyWindowSystem ()
virtual bool CreateNewWindow (const std::string &name, bool fullScreen, RESOLUTION_INFO &res)=0
virtual bool DestroyWindow ()
virtual bool ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop)=0
virtual bool SetFullScreen (bool fullScreen, RESOLUTION_INFO &res, bool blankOtherDisplays)=0
virtual bool DisplayHardwareScalingEnabled ()
virtual void UpdateDisplayHardwareScaling (const RESOLUTION_INFO &resInfo)
virtual bool MoveWindow (int topLeft, int topRight)
virtual void FinishModeChange (RESOLUTION res)
virtual void FinishWindowResize (int newWidth, int newHeight)
virtual bool CenterWindow ()
virtual bool IsCreated ()
virtual void NotifyAppFocusChange (bool bGaining)
virtual void NotifyAppActiveChange (bool bActivated)
virtual void ShowOSMouse (bool show)
virtual bool HasCursor ()
virtual bool HasInertialGestures ()
virtual bool UseLimitedColor ()
virtual int NoOfBuffers ()
virtual void ForceFullScreen (const RESOLUTION_INFO &resInfo)
Forces the window to fullscreen provided the window resolution.
virtual float GetDisplayLatency ()
Get average display latency.
virtual float GetFrameLatencyAdjustment ()
Get time that should be subtracted from the display latency for this frame in milliseconds.
virtual bool Minimize ()
virtual bool Restore ()
virtual bool Hide ()
virtual bool Show (bool raise=true)
virtual std::unique_ptr< CVideoSync > GetVideoSync (CVideoReferenceClock *clock)
virtual void OnMove (int x, int y)
virtual unsigned int GetScreenId (const std::string &screen)
Get the screen ID provided the screen name.
virtual void MoveToScreen (unsigned int screenIdx)
Window was requested to move to the given screen.
virtual void OnChangeScreen (unsigned int screenIdx)
Used to signal the windowing system about the change of the current screen.
KODI::WINDOWING::COSScreenSaverManager * GetOSScreenSaver ()
Get OS screen saver inhibit implementation if available.
unsigned int GetWidth ()
unsigned int GetHeight ()
virtual bool CanDoWindowed ()
bool IsFullScreen ()
virtual bool SupportsScreenMove ()
Check if the windowing system supports moving windows across screens.
virtual void UpdateResolutions ()
void SetWindowResolution (int width, int height)
std::vector< RESOLUTION_WHR > ScreenResolutions (float refreshrate)
std::vector< REFRESHRATE > RefreshRates (int width, int height, uint32_t dwFlags)
REFRESHRATE DefaultRefreshRate (const std::vector< REFRESHRATE > &rates)
virtual bool HasCalibration (const RESOLUTION_INFO &resInfo)
virtual std::string GetClipboardText (void)
virtual void Register (IDispResource *resource)=0
virtual void Unregister (IDispResource *resource)=0
void RegisterRenderLoop (IRenderLoop *client)
void UnregisterRenderLoop (IRenderLoop *client)
void DriveRenderLoop ()
virtual bool MessagePump ()
virtual CGraphicContext & GetGfxContext () const
virtual void * GetHWContext ()
Get OS specific hardware context.
std::shared_ptr< CDPMSSupport > GetDPMSManager ()
virtual bool SetHDR (const VideoPicture *videoPicture)
Set the HDR metadata. Passing nullptr as the parameter should disable HDR.
virtual bool IsHDRDisplay ()
virtual HDR_STATUS ToggleHDR ()
virtual HDR_STATUS GetOSHDRStatus ()
virtual CHDRCapabilities GetDisplayHDRCapabilities () const
virtual float GetGuiSdrPeakLuminance () const
virtual bool HasSystemSdrPeakLuminance ()
virtual bool SupportsVideoSuperResolution ()
System supports Video Super Resolution HW upscaler i.e.: "NVIDIA RTX Video Super Resolution" or "Intel Video Super Resolution".
virtual DEBUG_INFO_RENDER GetDebugInfo ()
Gets debug info from video renderer for use in "Debug Info OSD" (Alt + O)
virtual std::vector< std::string > GetConnectedOutputs ()
bool IsHDRDisplaySettingEnabled ()
Return true when HDR display is available and enabled in settings.
bool IsVideoSuperResolutionSettingEnabled ()
Return true when "Video Super Resolution" is supported and enabled in settings.
bool IsHighPrecisionProcessingSettingEnabled ()
Return true when setting "High Precision Processing" is enabled.
std::pair< bool, int > GetDitherSettings ()
Get dither settings.
virtual bool BindTextureUploadContext ()
Binds a shared context to the current thread, in order to upload textures asynchronously.
virtual bool UnbindTextureUploadContext ()
Unbinds the shared context.
virtual bool HasContext ()
Checks if a graphics context is already bound to the current thread.
Static Public Member Functions
static std::unique_ptr< CWinSystemBase > CreateWinSystem ()
Static Public Attributes
static const char * SETTING_WINSYSTEM_IS_HDR_DISPLAY = "winsystem.ishdrdisplay"
Protected Member Functions
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, float refreshRate, uint32_t dwFlags)
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, int screenWidth, int screenHeight, float refreshRate, uint32_t dwFlags)
virtual std::unique_ptr< KODI::WINDOWING::IOSScreenSaver > GetOSScreenSaverImpl ()
Protected Attributes
int m_nWidth = 0
int m_nHeight = 0
int m_nTop = 0
int m_nLeft = 0
bool m_bWindowCreated = false
bool m_bFullScreen = false
bool m_bBlankOtherDisplay = false
float m_fRefreshRate = 0.0f
std::unique_ptr< KODI::WINDOWING::COSScreenSaverManager > m_screenSaverManager
CCriticalSection m_renderLoopSection
std::vector< IRenderLoop * > m_renderLoopClients
std::unique_ptr< IWinEvents > m_winEvents
std::unique_ptr< CGraphicContext > m_gfxContext
std::shared_ptr< CDPMSSupport > m_dpms
Constructor & Destructor Documentation
CWinSystemBase()
CWinSystemBase::CWinSystemBase ()
~CWinSystemBase()
CWinSystemBase::~CWinSystemBase () virtual default
Member Function Documentation
BindTextureUploadContext()
virtual bool CWinSystemBase::BindTextureUploadContext () inline virtual
Binds a shared context to the current thread, in order to upload textures asynchronously.
Returns
Return true if a texture upload context exists and the binding succeeds.
Reimplemented in KODI::WINDOWING::GBM::CWinSystemGbmEGLContext, KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext, KODI::WINDOWING::X11::CWinSystemX11GLContext, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
CanDoWindowed()
virtual bool CWinSystemBase::CanDoWindowed () inline virtual
Reimplemented in KODI::WINDOWING::GBM::CWinSystemGbm, CWinSystemIOS, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWayland, and CWinSystemWin10.
CenterWindow()
virtual bool CWinSystemBase::CenterWindow () inline virtual
Reimplemented in CWinSystemWin32.
CreateNewWindow()
virtual bool CWinSystemBase::CreateNewWindow (const std::string & name, bool fullScreen, RESOLUTION_INFO & res) pure virtual
Implemented in CWinSystemAndroid, CWinSystemAndroidGLESContext, KODI::WINDOWING::GBM::CWinSystemGbmEGLContext, CWinSystemIOS, CWinSystemOSX, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWayland, KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext, KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS, CWinSystemWin10DX, CWinSystemWin32DX, KODI::WINDOWING::X11::CWinSystemX11, KODI::WINDOWING::X11::CWinSystemX11GLContext, KODI::WINDOWING::X11::CWinSystemX11GLESContext, CWinSystemWin10, and CWinSystemWin32.
CreateWinSystem()
static std::unique_ptr< CWinSystemBase > CWinSystemBase::CreateWinSystem () static
DefaultRefreshRate()
REFRESHRATE CWinSystemBase::DefaultRefreshRate (const std::vector< REFRESHRATE > & rates)
References RESOLUTION_INFO::fRefreshRate, CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), and RES_DESKTOP.
DestroyWindow()
virtual bool CWinSystemBase::DestroyWindow () inline virtual
Reimplemented in CWinSystemAndroid, KODI::WINDOWING::GBM::CWinSystemGbmEGLContext, CWinSystemIOS, CWinSystemOSX, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWayland, KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext, KODI::WINDOWING::X11::CWinSystemX11, KODI::WINDOWING::X11::CWinSystemX11GLContext, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
Referenced by CApplication::Cleanup(), and CApplication::OnApplicationMessage().
DestroyWindowSystem()
bool CWinSystemBase::DestroyWindowSystem () virtual
Reimplemented in CWinSystemAndroid, KODI::WINDOWING::GBM::CWinSystemGbm, KODI::WINDOWING::GBM::CWinSystemGbmEGLContext, CWinSystemIOS, CWinSystemOSX, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWayland, KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext, CWinSystemWin10, CWinSystemWin32, KODI::WINDOWING::X11::CWinSystemX11, KODI::WINDOWING::X11::CWinSystemX11GLContext, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
References m_screenSaverManager.
Referenced by CApplication::Cleanup(), and KODI::WINDOWING::WAYLAND::CWinSystemWayland::DestroyWindowSystem().
DisplayHardwareScalingEnabled()
virtual bool CWinSystemBase::DisplayHardwareScalingEnabled () inline virtual
Reimplemented in KODI::WINDOWING::GBM::CWinSystemGbm.
Referenced by KODI::RETRO::CRenderContext::DisplayHardwareScalingEnabled().
DriveRenderLoop()
void CWinSystemBase::DriveRenderLoop ()
References m_renderLoopClients, m_renderLoopSection, and MessagePump().
Referenced by CApplication::FrameMove().
FinishModeChange()
virtual void CWinSystemBase::FinishModeChange (RESOLUTION res) inline virtual
Reimplemented in KODI::WINDOWING::WAYLAND::CWinSystemWayland.
Referenced by CGraphicContext::ApplyModeChange().
FinishWindowResize()
virtual void CWinSystemBase::FinishWindowResize (int newWidth, int newHeight) inline virtual
Reimplemented in KODI::WINDOWING::WAYLAND::CWinSystemWayland, CWinSystemWin10, CWinSystemWin32, KODI::WINDOWING::X11::CWinSystemX11, KODI::WINDOWING::X11::CWinSystemX11GLContext, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
References ResizeWindow().
Referenced by CGraphicContext::ApplyWindowResize().
ForceFullScreen()
virtual void CWinSystemBase::ForceFullScreen (const RESOLUTION_INFO & resInfo) inline virtual
Forces the window to fullscreen provided the window resolution.
Parameters
resInfo - the resolution info
Reimplemented in CWinSystemWin10, and CWinSystemWin32.
Referenced by CAppInboundProtocol::HandleEvents().
GetClipboardText()
std::string CWinSystemBase::GetClipboardText (void) virtual
Reimplemented in CWinSystemOSX, KODI::WINDOWING::WAYLAND::CWinSystemWayland, CWinSystemWin10, and CWinSystemWin32.
Referenced by CGUIEditControl::OnPasteClipboard().
GetConnectedOutputs()
virtual std::vector< std::string > CWinSystemBase::GetConnectedOutputs () inline virtual
Reimplemented in KODI::WINDOWING::GBM::CWinSystemGbm, CWinSystemIOS, CWinSystemOSX, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWayland, CWinSystemWin32, and KODI::WINDOWING::X11::CWinSystemX11.
GetDebugInfo()
virtual DEBUG_INFO_RENDER CWinSystemBase::GetDebugInfo () inline virtual
Gets debug info from video renderer for use in "Debug Info OSD" (Alt + O)
Reimplemented in CWinSystemWin10DX, and CWinSystemWin32DX.
Referenced by CRenderManager::Render().
GetDisplayHDRCapabilities()
virtual CHDRCapabilities CWinSystemBase::GetDisplayHDRCapabilities () const inline virtual
Reimplemented in CWinSystemAndroid, and KODI::WINDOWING::GBM::CWinSystemGbm.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), and anonymous_namespace{SettingConditions.cpp}::SupportsDolbyVision().
GetDisplayLatency()
virtual float CWinSystemBase::GetDisplayLatency () inline virtual
Get average display latency.
The latency should be measured as the time between finishing the rendering of a frame, i.e. calling PresentRender, and the rendered content becoming visible on the screen.
Returns
average display latency in seconds, or negative value if unknown
Reimplemented in KODI::WINDOWING::WAYLAND::CWinSystemWayland.
Referenced by CGraphicContext::GetDisplayLatency(), and KODI::WINDOWING::WAYLAND::CWinSystemWayland::GetDisplayLatency().
GetDitherSettings()
std::pair< bool, int > CWinSystemBase::GetDitherSettings ()
Get dither settings.
Returns
std::pair containing dither enabled (bool) and dither depth (int)
References CServiceBroker::GetSettingsComponent(), CSettings::SETTING_VIDEOSCREEN_DITHER, and CSettings::SETTING_VIDEOSCREEN_DITHERDEPTH.
Referenced by CLinuxRendererGL::CLinuxRendererGL().
GetDPMSManager()
std::shared_ptr< CDPMSSupport > CWinSystemBase::GetDPMSManager ()
References m_dpms.
GetFrameLatencyAdjustment()
virtual float CWinSystemBase::GetFrameLatencyAdjustment () inline virtual
Get time that should be subtracted from the display latency for this frame in milliseconds.
Contrary to GetDisplayLatency, this value is calculated ad-hoc for the frame currently being rendered and not a value that is calculated/ averaged from past frames and their presentation times
Reimplemented in CWinSystemAndroidGLESContext, KODI::WINDOWING::WAYLAND::CWinSystemWayland, and KODI::WINDOWING::X11::CWinSystemX11GLContext.
GetGfxContext()
CGraphicContext & CWinSystemBase::GetGfxContext () const virtual
References m_gfxContext.
Referenced by CGUIWindowManager::AfterRender(), CRotateEffect::ApplyEffect(), CStereoscopicsManager::ApplyStereoMode(), CRendererDXVA::ApplyTransforms(), CGUIControl::AssignDepth(), PVR::CGUIEPGGridContainer::AssignDepth(), CRenderSystemGLES::BeginRender(), CBaseRenderer::CalcDestRect(), CGUITexture::CalculateSize(), CScreenshotSurfaceWindows::Capture(), CScreenshotSurfaceGL::Capture(), CScreenshotSurfaceGLES::Capture(), CWinSystemWin10::ChangeResolution(), CRenderManager::CheckEnableClockSync(), CRenderSystemDX::CheckInterlacedStereoView(), CResolutionUtils::ChooseBestResolution(), KODI::WINDOWING::X11::CVideoSyncGLX::Cleanup(), CLinuxRendererGL::ClearBackBuffer(), CLinuxRendererGLES::ClearBackBuffer(), CGUIWindow::ClearBackground(), CGUIWindowFullScreen::ClearBackground(), CGUIShaderDX::ClipToScissorParams(), CRendererMediaCodecSurface::Configure(), OVERLAY::CRenderer::ConvertLibass(), CApplication::CreateGUI(), CWinSystemAndroid::CreateNewWindow(), CGUIVisualisationControl::DeInitVisualization(), CGUIControl::DoProcess(), CGUIWindow::DoProcess(), CGUIWindowSettingsScreenCalibration::DoProcess(), CGUIControl::DoRender(), CGUIWindow::DoRender(), CLinuxRendererGL::DrawBlackBars(), CGUIFont::DrawScrollingText(), CGUIFont::DrawText(), CWinSystemIOS::FillInVideoModes(), CWinSystemTVOS::FillInVideoModes(), CRendererHQ::FinalOutput(), CGUIWindowSettingsScreenCalibration::FindCurrentResolution(), CResolutionUtils::FindResolutionFromOverride(), CResolutionUtils::FindResolutionFromWhitelist(), CGUIWindowFullScreen::FrameMove(), CGUIRenderingControl::FreeResources(), ADDON::Interface_GUIGeneral::get_screen_height(), ADDON::Interface_GUIGeneral::get_screen_width(), ADDON::Interface_GUIGeneral::get_video_resolution(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), CGUIFont::GetCharWidth(), CVideoSyncAndroid::GetFps(), CVideoSyncGbm::GetFps(), CVideoSyncIos::GetFps(), CVideoSyncOsx::GetFps(), CVideoSyncTVos::GetFps(), KODI::WINDOWING::X11::CVideoSyncGLX::GetFps(), KODI::WINDOWING::X11::CVideoSyncOML::GetFps(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), CGUIFont::GetLineHeight(), CResolutionUtils::GetMaxAllowedScreenResolution(), EVENTCLIENT::CEventClient::GetMousePos(), CDVDOverlayCodecFFmpeg::GetOverlay(), CRenderManager::GetResolution(), CGUIWindow::GetScaledBounds(), XBMCAddon::xbmcgui::getScreenHeight(), XBMCAddon::xbmcgui::getScreenWidth(), ADDON::CSkinInfo::GetSkinPath(), OVERLAY::GetStereoscopicDepth(), CGUIFont::GetTextBaseLine(), CGUIFont::GetTextHeight(), CGUIFont::GetTextWidth(), CVideoPlayer::GetVideoResolution(), PVR::CGUIEPGGridContainer::HandleChannels(), CAppInboundProtocol::HandleEvents(), PVR::CGUIEPGGridContainer::HandleProgrammeGrid(), PVR::CGUIEPGGridContainer::HandleRuler(), PVR::CGUIEPGGridContainer::HandleRulerDate(), CGUIRenderingControl::InitCallback(), CTeletextDecoder::InitDecoder(), CGUIVisualisationControl::InitVisualization(), CApplication::InitWindow(), CApplication::IsPlayingFullScreenVideo(), CGUIFontTTFDX::LastEnd(), CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), CGUIWindow::Load(), CApplicationSkinHandling::LoadSkin(), GUIFontManager::LoadTTF(), ADDON::Interface_GUIGeneral::lock(), CApplication::LockFrameMoveGuard(), CBaseRenderer::ManageRenderArea(), CRendererDRMPRIME::ManageRenderArea(), CRendererStarfish::ManageRenderArea(), CWinSystemIOS::Minimize(), CWinSystemTVOS::Minimize(), CWinSystemIOS::NotifyAppActiveChange(), CWinSystemTVOS::NotifyAppActiveChange(), CWinSystemWin32::NotifyAppFocusChange(), KODI::WINDOWING::X11::CWinSystemX11::NotifyXRREvent(), CApplication::OnAction(), CGUIWindowSlideShow::OnAction(), CGUIWindowSettingsScreenCalibration::OnAction(), CPlayerController::OnAction(), CApplication::OnApplicationMessage(), KODI::RETRO::CGameWindowFullScreen::OnDeinitWindow(), CGLShader::OnEnabled(), CGLESShader::OnEnabled(), KODI::RETRO::CGameWindowFullScreen::OnInitWindow(), VDPAU::CDecoder::OnLostDisplay(), CGUIWindowSlideShow::OnMessage(), CGUIWindowSettingsScreenCalibration::OnMessage(), CGUIWindowFullScreen::OnMessage(), CGUIWindowScreensaver::OnMessage(), CGUIWindow::OnMouseAction(), VDPAU::CDecoder::OnResetDisplay(), CApplicationSettingsHandling::OnSettingChanged(), CDisplaySettings::OnSettingChanging(), CVideoPlayer::OpenVideoStream(), CApplication::PlaybackCleanup(), CRenderManager::PrepareNextRender(), CResolutionUtils::PrintWhitelist(), CGUIControl::Process(), CSlideShowPic::Process(), CGUIControlGroup::Process(), CGUIControlGroupList::Process(), CGUIFadeLabelControl::Process(), CGUIListGroup::Process(), CGUIMultiImage::Process(), CGUITextBox::Process(), CGUIVisualisationControl::Process(), CGUIWindowDebugInfo::Process(), CGUIWindowSlideShow::Process(), CGUIWindowScreensaver::Process(), CGUIImage::ProcessFadingTransition(), PVR::CGUIEPGGridContainer::ProcessItem(), CGUIBaseContainer::ProcessItem(), CGUIEditControl::ProcessText(), KODI::WINDOWING::X11::CWinSystemX11::RecreateWindow(), CVideoSyncGbm::RefreshChanged(), GUIFontManager::ReloadTTFFonts(), CGUIWindowManager::Render(), CApplication::Render(), CGUIBaseContainer::Render(), CGUIBorderedImage::Render(), CGUIControlGroup::Render(), CGUIControlGroupList::Render(), CGUIFadeLabelControl::Render(), CGUIPanelContainer::Render(), CGUIProgressControl::Render(), CGUIRenderingControl::Render(), CGUITextBox::Render(), CGUIVideoControl::Render(), CGUIVisualisationControl::Render(), CGUIWindowSlideShow::Render(), CGUIWindowFullScreen::Render(), CGUIWindowDebugInfo::Render(), CGUIWindowScreensaver::Render(), CGUIWindowScreensaverDim::Render(), CGUIWindowSplash::Render(), OVERLAY::CRenderer::Render(), CGUITexture::Render(), CGUITextLayout::Render(), CGUITexture::Render(), CGUIWindowFullScreen::RenderEx(), CGUIBaseContainer::RenderItem(), PVR::CGUIEPGGridContainer::RenderItem(), PVR::CGUIEPGGridContainer::RenderProgressIndicator(), CGUITextLayout::RenderScrolling(), CGUIEditControl::RenderText(), CRendererMediaCodecSurface::RenderUpdate(), CWinRenderer::RenderUpdate(), CRendererMediaCodecSurface::Reset(), CGUIWindowSlideShow::Reset(), CGUIWindowSettingsScreenCalibration::ResetCalibration(), CGUIWindowSettingsScreenCalibration::ResetControls(), OVERLAY::CRenderer::ResetSubtitlePosition(), DX::DeviceResources::ResizeBuffers(), CSlideShowPic::Rotate(), CSeekHandler::Seek(), KODI::MESSAGING::CApplicationMessenger::SendMsg(), CGUIDialogTeletext::SetCoordinates(), DX::DeviceResources::SetFullScreen(), CWinSystemWin10::SetFullScreen(), CWinSystemWin32::SetFullScreen(), CSlideShowPic::SetTexture_Internal(), KODI::WINDOWING::X11::CVideoSyncGLX::Setup(), CBaseRenderer::SetViewMode(), VDPAU::CDecoder::SetWidthHeight(), KODI::WINDOWING::X11::CWinSystemX11GLContext::SetWindow(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::SetWindow(), SetWindowResolution(), ADDON::CGUIAddonWindowDialog::Show(), CRenderSystemBase::ShowSplash(), CGUIDialogKeyboardGeneric::ShowWordList(), ADDON::CSkinInfo::Start(), ADDON::Interface_GUIGeneral::unlock(), CApplication::UnlockFrameMoveGuard(), KODI::WINDOWING::X11::CWinSystemX11::UpdateCrtc(), CTimeUtils::UpdateFrameTime(), CGUIWindowSettingsScreenCalibration::UpdateFromControl(), CRenderManager::UpdateLatencyTweak(), CRenderManager::UpdateResolution(), KODI::WINDOWING::GBM::CWinSystemGbm::UpdateResolutions(), CWinSystemWin10::UpdateResolutions(), CWinSystemWin32::UpdateResolutions(), KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions(), CWinSystemAndroid::UpdateResolutions(), CGUIFont::UpdateScrollInfo(), and CSlideShowPic::Zoom().
GetGuiSdrPeakLuminance()
virtual float CWinSystemBase::GetGuiSdrPeakLuminance () const inline virtual
Reimplemented in CWinSystemAndroid, CWinSystemWin10, and CWinSystemWin32.
Referenced by CGLESShader::OnEnabled().
GetHeight()
unsigned int CWinSystemBase::GetHeight () inline
References m_nHeight.
GetHWContext()
virtual void * CWinSystemBase::GetHWContext () inline virtual
Get OS specific hardware context.
Returns
OS specific context or nullptr if OS not have
Note
This function is currently only related to Windows with DirectX, all other OS where use GL returns nullptr. Returned Windows class pointer is ID3D11DeviceContext1.
Reimplemented in CWinSystemWin10DX, and CWinSystemWin32DX.
Referenced by ADDON::Interface_GUIGeneral::get_hw_context().
GetName()
virtual const std::string CWinSystemBase::GetName () inline virtual
Reimplemented in KODI::WINDOWING::GBM::CWinSystemGbm, KODI::WINDOWING::WAYLAND::CWinSystemWayland, and KODI::WINDOWING::X11::CWinSystemX11.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel().
GetOSHDRStatus()
virtual HDR_STATUS CWinSystemBase::GetOSHDRStatus () inline virtual
Reimplemented in CWinSystemWin10DX, and CWinSystemWin32DX.
References HDR_UNSUPPORTED.
Referenced by CRenderManager::UpdateLatencyTweak().
GetOSScreenSaver()
KODI::WINDOWING::COSScreenSaverManager * CWinSystemBase::GetOSScreenSaver ()
Get OS screen saver inhibit implementation if available.
Returns
OS screen saver implementation that can be used with this windowing system or nullptr if unsupported. Lifetime of the returned object will usually end with DestroyWindowSystem, so do not use any more after calling that.
References GetOSScreenSaverImpl(), and m_screenSaverManager.
Referenced by CApplicationPowerHandling::CheckOSScreenSaverInhibitionSetting(), CApplicationPowerHandling::CheckScreenSaverAndDPMS(), and CXBMCApp::onResume().
GetOSScreenSaverImpl()
virtual std::unique_ptr< KODI::WINDOWING::IOSScreenSaver > CWinSystemBase::GetOSScreenSaverImpl () inline protected virtual
Reimplemented in CWinSystemAndroid, CWinSystemOSX, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWayland, KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS, and KODI::WINDOWING::X11::CWinSystemX11.
Referenced by GetOSScreenSaver().
GetRenderSystem()
virtual CRenderSystemBase * CWinSystemBase::GetRenderSystem () inline virtual
Reimplemented in CWinSystemAndroidGLESContext, KODI::WINDOWING::GBM::CWinSystemGbmGLContext, KODI::WINDOWING::GBM::CWinSystemGbmGLESContext, CWinSystemIOS, CWinSystemOSXGL, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL, KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES, CWinSystemWin10DX, CWinSystemWin32DX, KODI::WINDOWING::X11::CWinSystemX11GLContext, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
GetScreenId()
virtual unsigned int CWinSystemBase::GetScreenId (const std::string & screen) inline virtual
Get the screen ID provided the screen name.
Parameters
screen the name of the screen as presented on the application display settings
Returns
the screen index as known by the windowing system implementation (or the default screen by default)
Reimplemented in CWinSystemOSX.
GetVideoSync()
virtual std::unique_ptr< CVideoSync > CWinSystemBase::GetVideoSync (CVideoReferenceClock * clock) inline virtual
Reimplemented in CWinSystemAndroidGLESContext, KODI::WINDOWING::GBM::CWinSystemGbm, CWinSystemIOS, CWinSystemOSX, KODI::WINDOWING::WAYLAND::CWinSystemWayland, CWinSystemWin10, CWinSystemWin32, and KODI::WINDOWING::X11::CWinSystemX11GLContext.
Referenced by CVideoReferenceClock::Process().
GetWidth()
unsigned int CWinSystemBase::GetWidth () inline
References m_nWidth.
HasCalibration()
virtual bool CWinSystemBase::HasCalibration (const RESOLUTION_INFO & resInfo) inline virtual
Reimplemented in KODI::WINDOWING::X11::CWinSystemX11.
HasContext()
virtual bool CWinSystemBase::HasContext () inline virtual
Checks if a graphics context is already bound to the current thread.
Returns
Return true if so.
Reimplemented in KODI::WINDOWING::GBM::CWinSystemGbmEGLContext, KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext, KODI::WINDOWING::X11::CWinSystemX11GLContext, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
HasCursor()
virtual bool CWinSystemBase::HasCursor () inline virtual
Reimplemented in CWinSystemAndroid, CWinSystemIOS, CWinSystemOSX, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWayland, and KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS.
HasInertialGestures()
virtual bool CWinSystemBase::HasInertialGestures () inline virtual
Reimplemented in CWinSystemWin10, and CWinSystemWin32.
HasSystemSdrPeakLuminance()
virtual bool CWinSystemBase::HasSystemSdrPeakLuminance () inline virtual
Reimplemented in CWinSystemWin10, and CWinSystemWin32.
Referenced by anonymous_namespace{SettingConditions.cpp}::HasSystemSdrPeakLuminance().
Hide()
virtual bool CWinSystemBase::Hide () inline virtual
Reimplemented in CWinSystemAndroid, KODI::WINDOWING::GBM::CWinSystemGbm, CWinSystemIOS, CWinSystemOSX, CWinSystemTVOS, CWinSystemWin10, CWinSystemWin32, and KODI::WINDOWING::X11::CWinSystemX11.
Referenced by CExternalPlayer::Process().
InitWindowSystem()
bool CWinSystemBase::InitWindowSystem () virtual
Reimplemented in CWinSystemAndroid, CWinSystemAndroidGLESContext, KODI::WINDOWING::GBM::CWinSystemGbm, KODI::WINDOWING::GBM::CWinSystemGbmGLContext, KODI::WINDOWING::GBM::CWinSystemGbmGLESContext, CWinSystemIOS, CWinSystemOSX, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWayland, KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL, KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES, KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS, CWinSystemWin10, CWinSystemWin32, and KODI::WINDOWING::X11::CWinSystemX11.
References CDisplaySettings::ApplyCalibrations(), CDisplaySettings::GetInstance(), CResolutionUtils::PrintWhitelist(), and UpdateResolutions().
Referenced by CWinSystemAndroid::InitWindowSystem(), KODI::WINDOWING::GBM::CWinSystemGbm::InitWindowSystem(), CWinSystemIOS::InitWindowSystem(), CWinSystemOSX::InitWindowSystem(), CWinSystemTVOS::InitWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::InitWindowSystem(), CWinSystemWin10::InitWindowSystem(), CWinSystemWin32::InitWindowSystem(), and KODI::WINDOWING::X11::CWinSystemX11::InitWindowSystem().
IsCreated()
virtual bool CWinSystemBase::IsCreated () inline virtual
References m_bWindowCreated.
IsFullScreen()
bool CWinSystemBase::IsFullScreen () inline
References m_bFullScreen.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), CWinSystemWin32DX::OnMove(), and CPowerManager::OnWake().
IsHDRDisplay()
virtual bool CWinSystemBase::IsHDRDisplay () inline virtual
Reimplemented in CWinSystemAndroid, CWinSystemAndroidGLESContext, KODI::WINDOWING::GBM::CWinSystemGbm, CWinSystemWin10DX, and CWinSystemWin32DX.
Referenced by anonymous_namespace{SettingConditions.cpp}::IsHDRDisplay(), and IsHDRDisplaySettingEnabled().
IsHDRDisplaySettingEnabled()
bool CWinSystemBase::IsHDRDisplaySettingEnabled ()
Return true when HDR display is available and enabled in settings.
References CServiceBroker::GetSettingsComponent(), IsHDRDisplay(), and SETTING_WINSYSTEM_IS_HDR_DISPLAY.
Referenced by CGUIDialogVideoSettings::InitializeSettings(), CApplication::OnAction(), and CWinSystemAndroidGLESContext::SetHDR().
IsHighPrecisionProcessingSettingEnabled()
bool CWinSystemBase::IsHighPrecisionProcessingSettingEnabled ()
Return true when setting "High Precision Processing" is enabled.
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_VIDEOPLAYER_HIGHPRECISIONPROCESSING.
IsVideoSuperResolutionSettingEnabled()
bool CWinSystemBase::IsVideoSuperResolutionSettingEnabled ()
Return true when "Video Super Resolution" is supported and enabled in settings.
References CServiceBroker::GetSettingsComponent(), CSettings::SETTING_VIDEOPLAYER_USESUPERRESOLUTION, and SupportsVideoSuperResolution().
MessagePump()
virtual bool CWinSystemBase::MessagePump () inline virtual
Reimplemented in CWinSystemAndroid, CWinSystemIOS, CWinSystemOSX, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWayland, CWinSystemWin10, CWinSystemWin32, and KODI::WINDOWING::X11::CWinSystemX11.
Referenced by DriveRenderLoop().
Minimize()
virtual bool CWinSystemBase::Minimize () inline virtual
Reimplemented in CWinSystemAndroid, CWinSystemIOS, CWinSystemOSX, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWayland, CWinSystemWin10, CWinSystemWin32, and KODI::WINDOWING::X11::CWinSystemX11.
Referenced by CApplication::OnApplicationMessage().
MoveToScreen()
virtual void CWinSystemBase::MoveToScreen (unsigned int screenIdx) inline virtual
Window was requested to move to the given screen.
Parameters
screenIdx the screen index as known by the windowing system implementation
Reimplemented in CWinSystemOSX.
Referenced by CApplication::OnApplicationMessage().
MoveWindow()
virtual bool CWinSystemBase::MoveWindow (int topLeft, int topRight) inline virtual
NoOfBuffers()
int CWinSystemBase::NoOfBuffers (void) virtual
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_VIDEOSCREEN_NOOFBUFFERS.
Referenced by CGraphicContext::GetDisplayLatency().
NotifyAppActiveChange()
virtual void CWinSystemBase::NotifyAppActiveChange (bool bActivated) inline virtual
Reimplemented in CWinSystemIOS, CWinSystemTVOS, and KODI::WINDOWING::X11::CWinSystemX11.
NotifyAppFocusChange()
virtual void CWinSystemBase::NotifyAppFocusChange (bool bGaining) inline virtual
Reimplemented in CWinSystemWin10, CWinSystemWin32, and KODI::WINDOWING::X11::CWinSystemX11.
OnChangeScreen()
virtual void CWinSystemBase::OnChangeScreen (unsigned int screenIdx) inline virtual
Used to signal the windowing system about the change of the current screen.
Parameters
screenIdx the screen index as known by the windowing system implementation
Reimplemented in CWinSystemOSX.
Referenced by CAppInboundProtocol::HandleEvents().
OnMove()
virtual void CWinSystemBase::OnMove (int x, int y) inline virtual
Reimplemented in CWinSystemOSX, CWinSystemWin10DX, and CWinSystemWin32DX.
Referenced by CAppInboundProtocol::HandleEvents().
RefreshRates()
std::vector< REFRESHRATE > CWinSystemBase::RefreshRates (int width, int height, uint32_t dwFlags)
References AddRefreshRate(), D3DPRESENTFLAG_MODEMASK, RESOLUTION_INFO::dwFlags, CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, RES_DESKTOP, CDisplaySettings::ResolutionInfoSize(), and rrSortPredicate().
Referenced by CDisplaySettings::SettingOptionsRefreshRatesFiller().
Register()
virtual void CWinSystemBase::Register (IDispResource * resource) pure virtual
Implemented in CWinSystemWin10, CWinSystemWin32, CWinSystemAndroid, KODI::WINDOWING::GBM::CWinSystemGbm, CWinSystemIOS, CWinSystemOSX, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWayland, CWinSystemWin10DX, CWinSystemWin32DX, and KODI::WINDOWING::X11::CWinSystemX11.
Referenced by CVideoPlayer::CVideoPlayer(), VDPAU::CDecoder::Open(), CVideoSyncAndroid::Setup(), CVideoSyncGbm::Setup(), CVideoSyncOsx::Setup(), and ActiveAE::CActiveAE::StateMachine().
RegisterRenderLoop()
void CWinSystemBase::RegisterRenderLoop (IRenderLoop * client)
References m_renderLoopClients, and m_renderLoopSection.
Referenced by KODI::RETRO::CRetroPlayer::CRetroPlayer(), and CVideoPlayer::Process().
ResizeWindow()
virtual bool CWinSystemBase::ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) pure virtual
Implemented in CWinSystemAndroidGLESContext, KODI::WINDOWING::GBM::CWinSystemGbm, CWinSystemIOS, CWinSystemOSXGL, CWinSystemOSX, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWayland, CWinSystemWin10, CWinSystemWin10DX, CWinSystemWin32, CWinSystemWin32DX, KODI::WINDOWING::X11::CWinSystemX11, KODI::WINDOWING::X11::CWinSystemX11GLContext, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
Referenced by FinishWindowResize(), and CGraphicContext::SetVideoResolutionInternal().
Restore()
virtual bool CWinSystemBase::Restore () inline virtual
Reimplemented in CWinSystemIOS, CWinSystemOSX, CWinSystemTVOS, CWinSystemWin10, CWinSystemWin32, and KODI::WINDOWING::X11::CWinSystemX11.
Referenced by CExternalPlayer::Process().
ScreenResolutions()
std::vector< RESOLUTION_WHR > CWinSystemBase::ScreenResolutions (float refreshrate)
References AddResolution(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), RES_CUSTOM, CDisplaySettings::ResolutionInfoSize(), and resSortPredicate().
Referenced by CDisplaySettings::SettingOptionsResolutionsFiller().
SetFullScreen()
virtual bool CWinSystemBase::SetFullScreen (bool fullScreen, RESOLUTION_INFO & res, bool blankOtherDisplays) pure virtual
Implemented in CWinSystemAndroidGLESContext, KODI::WINDOWING::GBM::CWinSystemGbm, KODI::WINDOWING::GBM::CWinSystemGbmGLContext, KODI::WINDOWING::GBM::CWinSystemGbmGLESContext, CWinSystemIOS, CWinSystemOSXGL, CWinSystemOSX, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWayland, CWinSystemWin10, CWinSystemWin10DX, CWinSystemWin32, CWinSystemWin32DX, KODI::WINDOWING::X11::CWinSystemX11, KODI::WINDOWING::X11::CWinSystemX11GLContext, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
Referenced by CGraphicContext::SetVideoResolutionInternal().
SetHDR()
virtual bool CWinSystemBase::SetHDR (const VideoPicture * videoPicture) inline virtual
Set the HDR metadata. Passing nullptr as the parameter should disable HDR.
Reimplemented in CWinSystemAndroidGLESContext, and KODI::WINDOWING::GBM::CWinSystemGbm.
Referenced by CLinuxRendererGLES::Configure(), and CLinuxRendererGLES::UnInit().
SetWindowResolution()
void CWinSystemBase::SetWindowResolution (int width, int height)
References GetGfxContext(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), CServiceBroker::GetWinSystem(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, RESOLUTION_INFO::iSubtitles, RESOLUTION_INFO::iWidth, RES_WINDOW, and CGraphicContext::ResetOverscan().
Referenced by CWinSystemWin32::AdjustWindow(), CGraphicContext::ApplyWindowResize(), CApplication::CreateGUI(), CWinSystemOSX::CreateNewWindow(), CWinSystemWin32::CreateNewWindow(), and KODI::WINDOWING::WAYLAND::CWinSystemWayland::SetResolutionInternal().
Show()
virtual bool CWinSystemBase::Show (bool raise = true) inline virtual
Reimplemented in CWinSystemAndroid, KODI::WINDOWING::GBM::CWinSystemGbm, CWinSystemIOS, CWinSystemOSX, CWinSystemTVOS, CWinSystemWin10, CWinSystemWin32, and KODI::WINDOWING::X11::CWinSystemX11.
Referenced by CExternalPlayer::Process().
ShowOSMouse()
virtual void CWinSystemBase::ShowOSMouse (bool show) inline virtual
Reimplemented in CWinSystemIOS, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWayland, CWinSystemWin10, CWinSystemWin32, and KODI::WINDOWING::X11::CWinSystemX11.
Referenced by CMouseStat::SetActive().
SupportsScreenMove()
virtual bool CWinSystemBase::SupportsScreenMove () inline virtual
Check if the windowing system supports moving windows across screens.
Returns
true if the windowing system supports moving windows across screens, false otherwise
Referenced by anonymous_namespace{SettingConditions.cpp}::SupportsScreenMove().
SupportsVideoSuperResolution()
virtual bool CWinSystemBase::SupportsVideoSuperResolution () inline virtual
System supports Video Super Resolution HW upscaler i.e.: "NVIDIA RTX Video Super Resolution" or "Intel Video Super Resolution".
Reimplemented in CWinSystemWin32DX.
Referenced by IsVideoSuperResolutionSettingEnabled(), and anonymous_namespace{SettingConditions.cpp}::SupportsVideoSuperResolution().
ToggleHDR()
virtual HDR_STATUS CWinSystemBase::ToggleHDR () inline virtual
Reimplemented in CWinSystemWin10DX, and CWinSystemWin32DX.
References HDR_UNSUPPORTED.
Referenced by CApplication::OnAction().
UnbindTextureUploadContext()
virtual bool CWinSystemBase::UnbindTextureUploadContext () inline virtual
Unbinds the shared context.
Returns
Return true if the texture upload context has been unbound.
Reimplemented in KODI::WINDOWING::GBM::CWinSystemGbmEGLContext, KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext, KODI::WINDOWING::X11::CWinSystemX11GLContext, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
Referenced by CTexture::LoadToGPUAsync().
Unregister()
virtual void CWinSystemBase::Unregister (IDispResource * resource) pure virtual
Implemented in CWinSystemWin10, CWinSystemWin32, CWinSystemAndroid, KODI::WINDOWING::GBM::CWinSystemGbm, CWinSystemIOS, CWinSystemOSX, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWayland, CWinSystemWin10DX, CWinSystemWin32DX, and KODI::WINDOWING::X11::CWinSystemX11.
Referenced by CVideoSyncAndroid::Cleanup(), CVideoSyncGbm::Cleanup(), CVideoSyncOsx::Cleanup(), VDPAU::CDecoder::Close(), ActiveAE::CActiveAE::Dispose(), and CVideoPlayer::~CVideoPlayer().
UnregisterRenderLoop()
void CWinSystemBase::UnregisterRenderLoop (IRenderLoop * client)
References m_renderLoopClients, and m_renderLoopSection.
Referenced by CVideoPlayer::OnExit(), and KODI::RETRO::CRetroPlayer::~CRetroPlayer().
UpdateDesktopResolution() [1/2]
void CWinSystemBase::UpdateDesktopResolution (RESOLUTION_INFO & newRes, const std::string & output, int width, int height, float refreshRate, uint32_t dwFlags) protected
References UpdateDesktopResolution().
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWayland::CreateNewWindow(), CWinSystemOSX::FillInVideoModes(), CWinSystemIOS::FillInVideoModes(), CWinSystemTVOS::FillInVideoModes(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::SetResolutionInternal(), UpdateDesktopResolution(), CWinSystemIOS::UpdateResolutions(), CWinSystemOSX::UpdateResolutions(), CWinSystemTVOS::UpdateResolutions(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::UpdateResolutions(), CWinSystemWin10::UpdateResolutions(), CWinSystemWin32::UpdateResolutions(), and KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions().
UpdateDesktopResolution() [2/2]
void CWinSystemBase::UpdateDesktopResolution (RESOLUTION_INFO & newRes, const std::string & output, int width, int height, int screenWidth, int screenHeight, float refreshRate, uint32_t dwFlags) protected
References RESOLUTION_INFO::bFullScreen, OVERSCAN::bottom, D3DPRESENTFLAG_INTERLACED, D3DPRESENTFLAG_MODE3DSBS, D3DPRESENTFLAG_MODE3DTB, RESOLUTION_INFO::dwFlags, RESOLUTION_INFO::fPixelRatio, RESOLUTION_INFO::fRefreshRate, RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, RESOLUTION_INFO::iSubtitles, RESOLUTION_INFO::iWidth, OVERSCAN::left, RESOLUTION_INFO::Overscan, OVERSCAN::right, RESOLUTION_INFO::strMode, RESOLUTION_INFO::strOutput, and OVERSCAN::top.
UpdateDisplayHardwareScaling()
virtual void CWinSystemBase::UpdateDisplayHardwareScaling (const RESOLUTION_INFO & resInfo) inline virtual
Reimplemented in KODI::WINDOWING::GBM::CWinSystemGbm.
Referenced by KODI::RETRO::CRenderContext::UpdateDisplayHardwareScaling().
UpdateResolutions()
void CWinSystemBase::UpdateResolutions () virtual
Reimplemented in CWinSystemAndroid, KODI::WINDOWING::GBM::CWinSystemGbm, CWinSystemIOS, CWinSystemOSX, CWinSystemTVOS, KODI::WINDOWING::WAYLAND::CWinSystemWayland, CWinSystemWin10, CWinSystemWin32, and KODI::WINDOWING::X11::CWinSystemX11.
References RESOLUTION_INFO::bFullScreen, RESOLUTION_INFO::fPixelRatio, CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, RESOLUTION_INFO::iSubtitles, RESOLUTION_INFO::iWidth, RES_WINDOW, and RESOLUTION_INFO::strMode.
Referenced by InitWindowSystem(), CWinSystemIOS::UpdateResolutions(), CWinSystemOSX::UpdateResolutions(), CWinSystemTVOS::UpdateResolutions(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::UpdateResolutions(), CWinSystemWin10::UpdateResolutions(), CWinSystemWin32::UpdateResolutions(), KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions(), and CWinSystemAndroid::UpdateResolutions().
UseLimitedColor()
bool CWinSystemBase::UseLimitedColor () virtual
Reimplemented in KODI::WINDOWING::GBM::CWinSystemGbm, KODI::WINDOWING::WAYLAND::CWinSystemWayland, CWinSystemWin10, CWinSystemWin32, and KODI::WINDOWING::X11::CWinSystemX11.
Referenced by CRenderSystemDX::BeginRender(), CRenderSystemGL::BeginRender(), CRenderSystemGLES::BeginRender(), CLinuxRendererGL::CLinuxRendererGL(), CLinuxRendererGLES::CLinuxRendererGLES(), CLinuxRendererGL::Configure(), CLinuxRendererGLES::Configure(), CRenderSystemGL::InitialiseShaders(), CRenderSystemGLES::InitialiseShaders(), and KODI::RETRO::CRenderContext::UseLimitedColor().
Member Data Documentation
m_bBlankOtherDisplay
bool CWinSystemBase::m_bBlankOtherDisplay = false protected
Referenced by CWinSystemWin10::SetFullScreen(), and CWinSystemWin32::SetFullScreen().
m_bFullScreen
bool CWinSystemBase::m_bFullScreen = false protected
Referenced by CWinSystemAndroid::CreateNewWindow(), KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::CreateNewWindow(), CWinSystemOSX::CreateNewWindow(), CWinSystemWin10::CreateNewWindow(), CWinSystemWin32::CreateNewWindow(), KODI::WINDOWING::X11::CWinSystemX11::DestroyWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::FinishModeChange(), IsFullScreen(), KODI::WINDOWING::X11::CWinSystemX11::Minimize(), CWinSystemOSX::MoveToScreen(), KODI::WINDOWING::X11::CWinSystemX11::NotifyAppActiveChange(), KODI::WINDOWING::X11::CWinSystemX11::NotifyAppFocusChange(), CWinSystemOSX::OnChangeScreen(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::ProcessMessages(), KODI::WINDOWING::X11::CWinSystemX11::ResizeWindow(), CWinSystemIOS::SetFullScreen(), CWinSystemOSX::SetFullScreen(), CWinSystemTVOS::SetFullScreen(), CWinSystemWin10::SetFullScreen(), CWinSystemWin32::SetFullScreen(), KODI::WINDOWING::X11::CWinSystemX11::SetFullScreen(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::SetResolutionInternal(), KODI::WINDOWING::X11::CWinSystemX11::SetWindow(), and CWinSystemWin32::Show().
m_bWindowCreated
bool CWinSystemBase::m_bWindowCreated = false protected
Referenced by CWinSystemWin10::ChangeResolution(), CWinSystemAndroid::CreateNewWindow(), CWinSystemIOS::CreateNewWindow(), CWinSystemOSX::CreateNewWindow(), CWinSystemTVOS::CreateNewWindow(), KODI::WINDOWING::X11::CWinSystemX11::CreateNewWindow(), CWinSystemWin10::CreateNewWindow(), CWinSystemWin32::CreateNewWindow(), CWinSystemAndroid::DestroyWindow(), CWinSystemOSX::DestroyWindowInternal(), CWinSystemWin10::DestroyWindowSystem(), and IsCreated().
m_dpms
std::shared_ptr<CDPMSSupport> CWinSystemBase::m_dpms protected
Referenced by KODI::WINDOWING::GBM::CWinSystemGbm::CWinSystemGbm(), CWinSystemOSX::CWinSystemOSX(), CWinSystemWin32::CWinSystemWin32(), GetDPMSManager(), KODI::WINDOWING::X11::CWinSystemX11GLContext::RefreshGLContext(), and KODI::WINDOWING::X11::CWinSystemX11GLESContext::RefreshGLContext().
m_fRefreshRate
float CWinSystemBase::m_fRefreshRate = 0.0f protected
Referenced by CWinSystemAndroid::CreateNewWindow(), KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::CreateNewWindow(), CWinSystemWin10::CreateNewWindow(), CWinSystemWin32::CreateNewWindow(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::FinishModeChange(), CWinSystemWin32DX::FixRefreshRateIfNecessary(), CWinSystemWin10::SetFullScreen(), CWinSystemWin32::SetFullScreen(), and KODI::WINDOWING::WAYLAND::CWinSystemWayland::SetResolutionInternal().
m_gfxContext
std::unique_ptr<CGraphicContext> CWinSystemBase::m_gfxContext protected
Referenced by CWinSystemOSX::AnnounceOnResetDevice(), CWinSystemOSX::FillInVideoModes(), GetGfxContext(), and CWinSystemOSX::HasValidResolution().
m_nHeight
int CWinSystemBase::m_nHeight = 0 protected
Referenced by CWinSystemWin10::AdjustWindow(), CWinSystemWin32::AdjustWindow(), CWinSystemWin32::CenterWindow(), CWinSystemWin10::ChangeResolution(), CWinSystemAndroid::CreateNewWindow(), KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::CreateNewWindow(), CWinSystemOSX::CreateNewWindow(), CWinSystemWin10::CreateNewWindow(), CWinSystemWin32::CreateNewWindow(), CWinSystemWin10::FinishWindowResize(), CWinSystemWin32::FinishWindowResize(), KODI::WINDOWING::X11::CWinSystemX11::FinishWindowResize(), GetHeight(), CWinSystemOSX::MoveToScreen(), CWinSystemIOS::ResizeWindow(), CWinSystemOSX::ResizeWindow(), CWinSystemTVOS::ResizeWindow(), CWinSystemWin10::ResizeWindow(), CWinSystemWin32::ResizeWindow(), KODI::WINDOWING::X11::CWinSystemX11::ResizeWindow(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::SetFullScreen(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::SetFullScreen(), CWinSystemIOS::SetFullScreen(), CWinSystemOSX::SetFullScreen(), CWinSystemTVOS::SetFullScreen(), CWinSystemWin10::SetFullScreen(), CWinSystemWin32::SetFullScreen(), KODI::WINDOWING::X11::CWinSystemX11::SetFullScreen(), and KODI::WINDOWING::X11::CWinSystemX11::SetWindow().
m_nLeft
int CWinSystemBase::m_nLeft = 0 protected
Referenced by CWinSystemWin32::AdjustWindow(), CWinSystemWin32::CenterWindow(), CWinSystemWin32::CreateNewWindow(), CWinSystemWin32DX::OnMove(), CWinSystemWin10::ResizeWindow(), CWinSystemWin32::ResizeWindow(), CWinSystemWin10::SetFullScreen(), and CWinSystemWin32::SetFullScreen().
m_nTop
int CWinSystemBase::m_nTop = 0 protected
Referenced by CWinSystemWin32::AdjustWindow(), CWinSystemWin32::CenterWindow(), CWinSystemWin32::CreateNewWindow(), CWinSystemWin32DX::OnMove(), CWinSystemWin10::ResizeWindow(), CWinSystemWin32::ResizeWindow(), CWinSystemWin10::SetFullScreen(), and CWinSystemWin32::SetFullScreen().
m_nWidth
int CWinSystemBase::m_nWidth = 0 protected
Referenced by CWinSystemWin10::AdjustWindow(), CWinSystemWin32::AdjustWindow(), CWinSystemWin32::CenterWindow(), CWinSystemWin10::ChangeResolution(), CWinSystemAndroid::CreateNewWindow(), KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::CreateNewWindow(), CWinSystemOSX::CreateNewWindow(), CWinSystemWin10::CreateNewWindow(), CWinSystemWin32::CreateNewWindow(), CWinSystemWin10::FinishWindowResize(), CWinSystemWin32::FinishWindowResize(), KODI::WINDOWING::X11::CWinSystemX11::FinishWindowResize(), GetWidth(), CWinSystemOSX::MoveToScreen(), CWinSystemIOS::ResizeWindow(), CWinSystemOSX::ResizeWindow(), CWinSystemTVOS::ResizeWindow(), CWinSystemWin10::ResizeWindow(), CWinSystemWin32::ResizeWindow(), KODI::WINDOWING::X11::CWinSystemX11::ResizeWindow(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::SetFullScreen(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::SetFullScreen(), CWinSystemIOS::SetFullScreen(), CWinSystemOSX::SetFullScreen(), CWinSystemTVOS::SetFullScreen(), CWinSystemWin10::SetFullScreen(), CWinSystemWin32::SetFullScreen(), KODI::WINDOWING::X11::CWinSystemX11::SetFullScreen(), and KODI::WINDOWING::X11::CWinSystemX11::SetWindow().
m_renderLoopClients
std::vector<IRenderLoop*> CWinSystemBase::m_renderLoopClients protected
Referenced by DriveRenderLoop(), RegisterRenderLoop(), and UnregisterRenderLoop().
m_renderLoopSection
CCriticalSection CWinSystemBase::m_renderLoopSection protected
Referenced by DriveRenderLoop(), RegisterRenderLoop(), and UnregisterRenderLoop().
m_screenSaverManager
std::unique_ptr<KODI::WINDOWING::COSScreenSaverManager> CWinSystemBase::m_screenSaverManager protected
Referenced by DestroyWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::DestroyWindowSystem(), and GetOSScreenSaver().
m_winEvents
std::unique_ptr<IWinEvents> CWinSystemBase::m_winEvents protected
Referenced by CWinSystemAndroid::CWinSystemAndroid(), CWinSystemIOS::CWinSystemIOS(), CWinSystemTVOS::CWinSystemTVOS(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::CWinSystemWayland(), CWinSystemWin10::CWinSystemWin10(), CWinSystemWin32::CWinSystemWin32(), KODI::WINDOWING::X11::CWinSystemX11::CWinSystemX11(), CWinSystemAndroid::MessagePump(), CWinSystemIOS::MessagePump(), CWinSystemTVOS::MessagePump(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::MessagePump(), CWinSystemWin10::MessagePump(), CWinSystemWin32::MessagePump(), and KODI::WINDOWING::X11::CWinSystemX11::MessagePump().
SETTING_WINSYSTEM_IS_HDR_DISPLAY
const char * CWinSystemBase::SETTING_WINSYSTEM_IS_HDR_DISPLAY = "winsystem.ishdrdisplay" static
Referenced by IsHDRDisplaySettingEnabled(), and KODI::WINDOWING::GBM::CWinSystemGbm::SetHDR().
The documentation for this class was generated from the following files:
WinSystem.h
WinSystem.cpp