Kodi Documentation: ADDON::CLanguageResource Class Reference
ADDON::CLanguageResource Class Reference
#include <LanguageResource.h>
Public Member Functions
CLanguageResource (const AddonInfoPtr &addonInfo)
bool IsInUse () const override
void OnPostInstall (bool update, bool modal) override
bool IsAllowed (const std::string &file) const override
const CLocale & GetLocale () const
const std::string & GetGuiCharset () const
bool ForceUnicodeFont () const
const std::string & GetSubtitleCharset () const
const std::string & GetDvdMenuLanguage () const
const std::string & GetDvdAudioLanguage () const
const std::string & GetDvdSubtitleLanguage () const
const std::set< std::string > & GetSortTokens () const
Public Member Functions inherited from ADDON::CResource
~CResource () override=default
virtual std::string GetFullPath (const std::string &filePath) const
Public Member Functions inherited from ADDON::CAddon
CAddon (const AddonInfoPtr &addonInfo, AddonType addonType)
~CAddon () override=default
AddonType MainType () const override
To get the main type of this addon.
AddonType Type () const override
To get the on this CAddon class processed addon type.
bool HasType (AddonType type) const override
To check complete addon (not only this) contains a type.
bool HasMainType (AddonType type) const override
To check complete addon (not only this) has a specific type defined in its first extension point including the provided subcontent e.g. video or audio.
const CAddonType * Type (AddonType type) const
The get for given addon type information and extension data.
std::string ID () const override
std::string Name () const override
bool IsBinary () const override
CAddonVersion Version () const override
CAddonVersion MinVersion () const override
std::string Summary () const override
std::string Description () const override
std::string Path () const override
std::string Profile () const override
std::string LibPath () const override
std::string Author () const override
std::string ChangeLog () const override
std::string Icon () const override
ArtMap Art () const override
std::vector< std::string > Screenshots () const override
std::string Disclaimer () const override
AddonLifecycleState LifecycleState () const override
std::string LifecycleStateDescription () const override
CDateTime InstallDate () const override
CDateTime LastUpdated () const override
CDateTime LastUsed () const override
std::string Origin () const override
std::string OriginName () const override
uint64_t PackageSize () const override
const InfoMap & ExtraInfo () const override
const std::vector< DependencyInfo > & GetDependencies () const override
std::string FanArt () const override
bool SupportsMultipleInstances () const override
Check add-on for support from independent work instances.
AddonInstanceSupport InstanceUseType () const override
Return the used instance path type of the add-on type.
std::vector< AddonInstanceId > GetKnownInstanceIds () const override
Gives active, independently working instance identifiers for this add-on.
bool SupportsInstanceSettings () const override
Check whether the add-on supports individual settings per add-on instance.
bool DeleteInstanceSettings (AddonInstanceId instance) override
Delete selected instance settings from storage.
bool CanHaveAddonOrInstanceSettings () override
Check whether this add-on can be configured by the user.
bool HasSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
Check whether this add-on can be configured by the user.
bool HasUserSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
Check whether the user has configured this add-on or not.
bool SaveSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
Save any user configured settings.
void UpdateSetting (const std::string &key, const std::string &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new value.
bool UpdateSettingBool (const std::string &key, bool value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new boolean value.
bool UpdateSettingInt (const std::string &key, int value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new integer value.
bool UpdateSettingNumber (const std::string &key, double value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new number value.
bool UpdateSettingString (const std::string &key, const std::string &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Update a user-configured setting with a new string value.
std::string GetSetting (const std::string &key, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value.
bool GetSettingBool (const std::string &key, bool &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value as boolean.
bool GetSettingInt (const std::string &key, int &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value as integer.
bool GetSettingNumber (const std::string &key, double &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value as number.
bool GetSettingString (const std::string &key, std::string &value, AddonInstanceId id=ADDON_SETTINGS_ID) override
Retrieve a particular settings value as string.
std::shared_ptr< CAddonSettings > GetSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
CAddonVersion GetDependencyVersion (const std::string &dependencyID) const override
get the required version of a dependency.
bool MeetsVersion (const CAddonVersion &versionMin, const CAddonVersion &version) const override
return whether or not this addon satisfies the given version requirements
bool ReloadSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
void ResetSettings (AddonInstanceId id=ADDON_SETTINGS_ID) override
AddonPtr GetRunningInstance () const override
retrieve the running instance of an add-on if it persists while running.
void OnPreInstall () override
void OnPreUnInstall () override
void OnPostUnInstall () override
Public Member Functions inherited from ADDON::IAddon
virtual ~IAddon ()=default
Static Public Member Functions
static std::string GetAddonId (const std::string &locale)
static bool FindLegacyLanguage (const std::string &locale, std::string &legacyLanguage)
Private Attributes
CLocale m_locale
std::string m_charsetGui
bool m_forceUnicodeFont
std::string m_charsetSubtitle
std::string m_dvdLanguageMenu
std::string m_dvdLanguageAudio
std::string m_dvdLanguageSubtitle
std::set< std::string > m_sortTokens
Additional Inherited Members
Protected Member Functions inherited from ADDON::CResource
CResource (const AddonInfoPtr &addonInfo, AddonType addonType)
std::string GetResourcePath () const
Protected Member Functions inherited from ADDON::CAddon
virtual bool SettingsInitialized (AddonInstanceId id=ADDON_SETTINGS_ID) const
Whether or not the settings have been initialized.
virtual bool SettingsLoaded (AddonInstanceId id=ADDON_SETTINGS_ID) const
Whether or not the settings have been loaded.
bool LoadSettings (bool bForce, bool loadUserSettings, AddonInstanceId id=ADDON_SETTINGS_ID)
Load the default settings and override these with any previously configured user settings.
virtual bool LoadUserSettings (AddonInstanceId id=ADDON_SETTINGS_ID)
Load the user settings.
virtual bool HasSettingsToSave (AddonInstanceId id=ADDON_SETTINGS_ID) const
Whether there are settings to be saved.
virtual bool SettingsFromXML (const CXBMCTinyXML &doc, bool loadDefaults, AddonInstanceId id=ADDON_SETTINGS_ID)
Parse settings from an XML document.
virtual bool SettingsToXML (CXBMCTinyXML &doc, AddonInstanceId id=ADDON_SETTINGS_ID) const
Write settings into an XML document.
Protected Attributes inherited from ADDON::CAddon
const AddonInfoPtr m_addonInfo
Constructor & Destructor Documentation
CLanguageResource()
ADDON::CLanguageResource::CLanguageResource (const AddonInfoPtr & addonInfo) explicit
References ADDON::SExtValue::asBoolean(), ADDON::SExtValue::asString(), ADDON::CAddonExtensions::GetElement(), CLocale::GetLanguageCode(), ADDON::CAddonExtensions::GetValue(), ADDON::CAddonExtensions::GetValues(), m_charsetGui, m_charsetSubtitle, m_dvdLanguageAudio, m_dvdLanguageMenu, m_dvdLanguageSubtitle, m_forceUnicodeFont, m_locale, m_sortTokens, ADDON::RESOURCE_LANGUAGE, ADDON::CAddon::Type(), and values.
Member Function Documentation
FindLegacyLanguage()
bool ADDON::CLanguageResource::FindLegacyLanguage (const std::string & locale, std::string & legacyLanguage) static
References ADDON::CHOICE_YES, GetAddonId(), CServiceBroker::GetAddonMgr(), and ADDON::RESOURCE_LANGUAGE.
Referenced by LoadStr2Mem().
ForceUnicodeFont()
bool ADDON::CLanguageResource::ForceUnicodeFont () const inline
References m_forceUnicodeFont.
GetAddonId()
std::string ADDON::CLanguageResource::GetAddonId (const std::string & locale) static
References LANGUAGE_ADDON_PREFIX.
Referenced by FindLegacyLanguage(), CLangInfo::GetLanguageAddon(), and CLangInfo::GetLanguagePath().
GetDvdAudioLanguage()
const std::string & ADDON::CLanguageResource::GetDvdAudioLanguage () const inline
References m_dvdLanguageAudio.
GetDvdMenuLanguage()
const std::string & ADDON::CLanguageResource::GetDvdMenuLanguage () const inline
References m_dvdLanguageMenu.
GetDvdSubtitleLanguage()
const std::string & ADDON::CLanguageResource::GetDvdSubtitleLanguage () const inline
References m_dvdLanguageSubtitle.
GetGuiCharset()
const std::string & ADDON::CLanguageResource::GetGuiCharset () const inline
References m_charsetGui.
GetLocale()
const CLocale & ADDON::CLanguageResource::GetLocale () const inline
References m_locale.
GetSortTokens()
const std::set< std::string > & ADDON::CLanguageResource::GetSortTokens () const inline
References m_sortTokens.
GetSubtitleCharset()
const std::string & ADDON::CLanguageResource::GetSubtitleCharset () const inline
References m_charsetSubtitle.
IsAllowed()
bool ADDON::CLanguageResource::IsAllowed (const std::string & file) const override virtual
Implements ADDON::CResource.
IsInUse()
bool ADDON::CLanguageResource::IsInUse () const override virtual
Reimplemented from ADDON::CAddon.
References ADDON::CAddon::GetSettings(), CServiceBroker::GetSettingsComponent(), ADDON::CAddon::ID(), and CSettings::SETTING_LOCALE_LANGUAGE.
Referenced by OnPostInstall().
OnPostInstall()
void ADDON::CLanguageResource::OnPostInstall (bool update, bool modal) override virtual
Reimplemented from ADDON::CAddon.
References g_langInfo, g_SkinInfo, CServiceBroker::GetSettingsComponent(), ADDON::CAddon::ID(), IsInUse(), ADDON::CAddon::Name(), CSettings::SETTING_LOCALE_LANGUAGE, and KODI::MESSAGING::HELPERS::ShowYesNoDialogText().
Member Data Documentation
m_charsetGui
std::string ADDON::CLanguageResource::m_charsetGui private
Referenced by CLanguageResource(), and GetGuiCharset().
m_charsetSubtitle
std::string ADDON::CLanguageResource::m_charsetSubtitle private
Referenced by CLanguageResource(), and GetSubtitleCharset().
m_dvdLanguageAudio
std::string ADDON::CLanguageResource::m_dvdLanguageAudio private
Referenced by CLanguageResource(), and GetDvdAudioLanguage().
m_dvdLanguageMenu
std::string ADDON::CLanguageResource::m_dvdLanguageMenu private
Referenced by CLanguageResource(), and GetDvdMenuLanguage().
m_dvdLanguageSubtitle
std::string ADDON::CLanguageResource::m_dvdLanguageSubtitle private
Referenced by CLanguageResource(), and GetDvdSubtitleLanguage().
m_forceUnicodeFont
bool ADDON::CLanguageResource::m_forceUnicodeFont private
Referenced by CLanguageResource(), and ForceUnicodeFont().
m_locale
CLocale ADDON::CLanguageResource::m_locale private
Referenced by CLanguageResource(), and GetLocale().
m_sortTokens
std::set<std::string> ADDON::CLanguageResource::m_sortTokens private
Referenced by CLanguageResource(), and GetSortTokens().
The documentation for this class was generated from the following files:
LanguageResource.h
LanguageResource.cpp