Kodi Documentation: jni::CJNIXBMCJsonHandler Class Reference
jni::CJNIXBMCJsonHandler Class Reference
#include <JNIXBMCJsonHandler.h>
Classes
class CJNIClient
class CJNITransportLayer
Public Member Functions
CJNIXBMCJsonHandler (const jni::jhobject &object)
Static Public Member Functions
static void RegisterNatives (JNIEnv *env)
Protected Member Functions
~CJNIXBMCJsonHandler () override=default
Static Protected Member Functions
static jstring _requestJSON (JNIEnv *env, jobject thiz, jstring request)
Constructor & Destructor Documentation
CJNIXBMCJsonHandler()
jni::CJNIXBMCJsonHandler::CJNIXBMCJsonHandler (const jni::jhobject & object) inline
~CJNIXBMCJsonHandler()
jni::CJNIXBMCJsonHandler::~CJNIXBMCJsonHandler () override protected default
Member Function Documentation
_requestJSON()
jstring CJNIXBMCJsonHandler::_requestJSON (JNIEnv * env, jobject thiz, jstring request) static protected
References JSONRPC::CJSONRPC::MethodCall().
Referenced by RegisterNatives().
RegisterNatives()
void CJNIXBMCJsonHandler::RegisterNatives (JNIEnv * env) static
References _requestJSON(), and s_className.
Referenced by JNI_OnLoad().
The documentation for this class was generated from the following files:
JNIXBMCJsonHandler.h
JNIXBMCJsonHandler.cpp