Kodi Documentation: CSkinBuiltins Class Reference
CSkinBuiltins Class Reference
Class providing skin related built-in commands.
#include <SkinBuiltins.h>
Public Member Functions
CBuiltins::CommandMap GetOperations () const
Returns the map of operations.
Detailed Description
Class providing skin related built-in commands.
Member Function Documentation
GetOperations()
CBuiltins::CommandMap CSkinBuiltins::GetOperations () const
Returns the map of operations.
References ReloadSkin(), SelectBool(), SetAddon(), SetBool(), SetColor(), SetFile(), SetImage(), SetNumeric(), SetPath(), SetString(), SetTheme(), SkinDebug(), SkinReset(), SkinResetAll(), SkinTimerStart(), SkinTimerStop(), ToggleSetting(), and UnloadSkin().
The documentation for this class was generated from the following files:
SkinBuiltins.h
SkinBuiltins.cpp