Kodi Documentation: CCoreAudioDevice Class Reference
CCoreAudioDevice Class Reference
#include <CoreAudioDevice.h>
Public Member Functions
CCoreAudioDevice ()=default
CCoreAudioDevice (AudioDeviceID deviceId)
virtual ~CCoreAudioDevice ()
bool Open (AudioDeviceID deviceId)
void Close ()
void Start ()
void Stop ()
void RemoveObjectListenerProc (AudioObjectPropertyListenerProc callback, void *pClientData)
bool SetObjectListenerProc (AudioObjectPropertyListenerProc callback, void *pClientData)
AudioDeviceID GetId () const
std::string GetName () const
bool IsDigital () const
UInt32 GetTransportType () const
UInt32 GetTotalOutputChannels () const
UInt32 GetNumChannelsOfStream (UInt32 streamIdx) const
bool GetStreams (AudioStreamIdList *pList)
bool IsRunning ()
bool SetHogStatus (bool hog)
pid_t GetHogStatus ()
bool SetMixingSupport (UInt32 mix)
bool GetMixingSupport ()
bool SetCurrentVolume (Float32 vol)
bool GetPreferredChannelLayout (CCoreAudioChannelLayout &layout) const
bool GetPreferredChannelLayoutForStereo (CCoreAudioChannelLayout &layout) const
bool GetDataSources (CoreAudioDataSourceList *pList) const
bool GetDataSource (UInt32 &dataSourceId) const
bool SetDataSource (UInt32 &dataSourceId)
std::string GetDataSourceName (UInt32 dataSourceId) const
std::string GetCurrentDataSourceName () const
Float64 GetNominalSampleRate ()
bool SetNominalSampleRate (Float64 sampleRate)
UInt32 GetNumLatencyFrames ()
UInt32 GetBufferSize ()
bool SetBufferSize (UInt32 size)
bool AddIOProc (AudioDeviceIOProc ioProc, void *pCallbackData)
bool RemoveIOProc ()
Static Public Member Functions
static void RegisterDeviceChangedCB (bool bRegister, AudioObjectPropertyListenerProc callback, void *ref)
static void RegisterDefaultOutputDeviceChangedCB (bool bRegister, AudioObjectPropertyListenerProc callback, void *ref)
static void SuppressDefaultOutputDeviceCB (unsigned int suppressTimeMs)
Static Protected Member Functions
static OSStatus defaultOutputDeviceChanged (AudioObjectID inObjectID, UInt32 inNumberAddresses, const AudioObjectPropertyAddress inAddresses[], void *inClientData)
Protected Attributes
bool m_Started = false
AudioDeviceID m_DeviceId = 0
int m_MixerRestore = -1
AudioDeviceIOProc m_IoProc = nullptr
AudioObjectPropertyListenerProc m_ObjectListenerProc = nullptr
Float64 m_SampleRateRestore = 0.0
pid_t m_HogPid = -1
unsigned int m_frameSize = 0
unsigned int m_OutputBufferIndex = 0
unsigned int m_BufferSizeRestore = 0
Static Protected Attributes
static XbmcThreads::EndTime m_callbackSuppressTimer
static AudioObjectPropertyListenerProc m_defaultOutputDeviceChangedCB = NULL
Constructor & Destructor Documentation
CCoreAudioDevice() [1/2]
CCoreAudioDevice::CCoreAudioDevice () default
CCoreAudioDevice() [2/2]
CCoreAudioDevice::CCoreAudioDevice (AudioDeviceID deviceId) explicit
~CCoreAudioDevice()
CCoreAudioDevice::~CCoreAudioDevice () virtual
References Close().
Member Function Documentation
AddIOProc()
bool CCoreAudioDevice::AddIOProc (AudioDeviceIOProc ioProc, void * pCallbackData)
References GetError(), CLog::Log(), LOGERROR, m_DeviceId, m_IoProc, and Start().
Referenced by CAESinkDARWINOSX::Initialize().
Close()
void CCoreAudioDevice::Close ()
References GetBufferSize(), m_BufferSizeRestore, m_DeviceId, m_IoProc, m_MixerRestore, m_ObjectListenerProc, m_SampleRateRestore, RemoveIOProc(), CCoreAudioHardware::SetAutoHogMode(), SetBufferSize(), SetHogStatus(), SetMixingSupport(), SetNominalSampleRate(), and Stop().
Referenced by CAESinkDARWINOSX::Deinitialize(), and ~CCoreAudioDevice().
defaultOutputDeviceChanged()
OSStatus CCoreAudioDevice::defaultOutputDeviceChanged (AudioObjectID inObjectID, UInt32 inNumberAddresses, const AudioObjectPropertyAddress inAddresses[], void * inClientData) static protected
References m_callbackSuppressTimer, and m_defaultOutputDeviceChangedCB.
Referenced by RegisterDefaultOutputDeviceChangedCB().
GetBufferSize()
UInt32 CCoreAudioDevice::GetBufferSize ()
References GetError(), CLog::Log(), LOGERROR, and m_DeviceId.
Referenced by Close(), CAESinkDARWINOSX::Initialize(), Open(), and SetBufferSize().
GetCurrentDataSourceName()
std::string CCoreAudioDevice::GetCurrentDataSourceName () const
References GetDataSource(), and GetDataSourceName().
Referenced by AEDeviceEnumerationOSX::getExtraDisplayNameForStream().
GetDataSource()
bool CCoreAudioDevice::GetDataSource (UInt32 & dataSourceId) const
References m_DeviceId.
Referenced by GetCurrentDataSourceName().
GetDataSourceName()
std::string CCoreAudioDevice::GetDataSourceName (UInt32 dataSourceId) const
References CDarwinUtils::CFStringRefToUTF8String(), and m_DeviceId.
Referenced by GetCurrentDataSourceName(), and AEDeviceEnumerationOSX::GetDeviceInfoList().
GetDataSources()
bool CCoreAudioDevice::GetDataSources (CoreAudioDataSourceList * pList) const
References m_DeviceId.
Referenced by AEDeviceEnumerationOSX::GetDeviceInfoList().
GetHogStatus()
pid_t CCoreAudioDevice::GetHogStatus ()
References m_DeviceId.
Referenced by SetHogStatus().
GetId()
AudioDeviceID CCoreAudioDevice::GetId () const inline
References m_DeviceId.
GetMixingSupport()
bool CCoreAudioDevice::GetMixingSupport ()
References Boolean, GetError(), CLog::Log(), LOGDEBUG, LOGERROR, and m_DeviceId.
Referenced by SetMixingSupport().
GetName()
std::string CCoreAudioDevice::GetName () const
References CDarwinUtils::CFStringRefToUTF8String(), GetError(), CLog::Log(), LOGERROR, m_DeviceId, and name.
Referenced by AEDeviceEnumerationOSX::Enumerate(), CCoreAudioHardware::FindAudioDevice(), AEDeviceEnumerationOSX::isDigitalDevice(), and CCoreAudioHardware::ResetAudioDevices().
GetNominalSampleRate()
Float64 CCoreAudioDevice::GetNominalSampleRate ()
References GetError(), CLog::Log(), LOGERROR, and m_DeviceId.
Referenced by SetNominalSampleRate().
GetNumChannelsOfStream()
UInt32 CCoreAudioDevice::GetNumChannelsOfStream (UInt32 streamIdx) const
References GetError(), CLog::Log(), LOGERROR, and m_DeviceId.
Referenced by AEDeviceEnumerationOSX::Enumerate(), AEDeviceEnumerationOSX::getChannelInfoForStream(), and AEDeviceEnumerationOSX::getExtraDisplayNameForStream().
GetNumLatencyFrames()
UInt32 CCoreAudioDevice::GetNumLatencyFrames ()
References m_DeviceId.
Referenced by CAESinkDARWINOSX::Initialize().
GetPreferredChannelLayout()
bool CCoreAudioDevice::GetPreferredChannelLayout (CCoreAudioChannelLayout & layout) const
References CCoreAudioChannelLayout::CopyLayout(), GetError(), CLog::Log(), LOGERROR, and m_DeviceId.
Referenced by AEDeviceEnumerationOSX::GetAEChannelMap().
GetPreferredChannelLayoutForStereo()
bool CCoreAudioDevice::GetPreferredChannelLayoutForStereo (CCoreAudioChannelLayout & layout) const
References CCoreAudioChannelLayout::CopyLayoutForStereo(), GetError(), CLog::Log(), LOGERROR, and m_DeviceId.
Referenced by AEDeviceEnumerationOSX::GetAEChannelMap().
GetStreams()
bool CCoreAudioDevice::GetStreams (AudioStreamIdList * pList)
References m_DeviceId.
Referenced by AEDeviceEnumerationOSX::Enumerate(), and CCoreAudioHardware::ResetAudioDevices().
GetTotalOutputChannels()
UInt32 CCoreAudioDevice::GetTotalOutputChannels () const
References GetError(), CLog::Log(), LOGERROR, and m_DeviceId.
Referenced by CCoreAudioHardware::GetOutputDevices().
GetTransportType()
UInt32 CCoreAudioDevice::GetTransportType () const
References m_DeviceId.
Referenced by AEDeviceEnumerationOSX::Enumerate(), and IsDigital().
IsDigital()
bool CCoreAudioDevice::IsDigital () const
References GetTransportType(), and m_DeviceId.
Referenced by AEDeviceEnumerationOSX::isDigitalDevice().
IsRunning()
bool CCoreAudioDevice::IsRunning ()
References m_DeviceId.
Open()
bool CCoreAudioDevice::Open (AudioDeviceID deviceId)
References GetBufferSize(), m_BufferSizeRestore, and m_DeviceId.
Referenced by CCoreAudioHardware::FindAudioDevice(), and CAESinkDARWINOSX::Initialize().
RegisterDefaultOutputDeviceChangedCB()
void CCoreAudioDevice::RegisterDefaultOutputDeviceChangedCB (bool bRegister, AudioObjectPropertyListenerProc callback, void * ref) static
References defaultOutputDeviceChanged(), CLog::Log(), LOGERROR, and m_defaultOutputDeviceChangedCB.
Referenced by CAESinkDARWINOSX::CAESinkDARWINOSX(), and CAESinkDARWINOSX::~CAESinkDARWINOSX().
RegisterDeviceChangedCB()
void CCoreAudioDevice::RegisterDeviceChangedCB (bool bRegister, AudioObjectPropertyListenerProc callback, void * ref) static
References CLog::Log(), and LOGERROR.
Referenced by CAESinkDARWINOSX::CAESinkDARWINOSX(), and CAESinkDARWINOSX::~CAESinkDARWINOSX().
RemoveIOProc()
bool CCoreAudioDevice::RemoveIOProc ()
References GetError(), CLog::Log(), LOGERROR, m_DeviceId, m_IoProc, and Stop().
Referenced by Close(), and CAESinkDARWINOSX::Deinitialize().
RemoveObjectListenerProc()
void CCoreAudioDevice::RemoveObjectListenerProc (AudioObjectPropertyListenerProc callback, void * pClientData)
References GetError(), CLog::Log(), LOGERROR, m_DeviceId, and m_ObjectListenerProc.
SetBufferSize()
bool CCoreAudioDevice::SetBufferSize (UInt32 size)
References GetBufferSize(), GetError(), CLog::Log(), LOGERROR, and m_DeviceId.
Referenced by Close().
SetCurrentVolume()
bool CCoreAudioDevice::SetCurrentVolume (Float32 vol)
References GetError(), CLog::Log(), LOGERROR, and m_DeviceId.
SetDataSource()
bool CCoreAudioDevice::SetDataSource (UInt32 & dataSourceId)
References m_DeviceId.
Referenced by CAESinkDARWINOSX::Initialize().
SetHogStatus()
bool CCoreAudioDevice::SetHogStatus (bool hog)
References GetError(), GetHogStatus(), CLog::Log(), LOGERROR, m_DeviceId, and m_HogPid.
Referenced by Close(), and CAESinkDARWINOSX::SetHogMode().
SetMixingSupport()
bool CCoreAudioDevice::SetMixingSupport (UInt32 mix)
References GetError(), GetMixingSupport(), CLog::Log(), LOGERROR, m_DeviceId, and m_MixerRestore.
Referenced by Close(), and CAESinkDARWINOSX::SetHogMode().
SetNominalSampleRate()
bool CCoreAudioDevice::SetNominalSampleRate (Float64 sampleRate)
References GetError(), GetNominalSampleRate(), CLog::Log(), LOGERROR, m_DeviceId, and m_SampleRateRestore.
Referenced by Close().
SetObjectListenerProc()
bool CCoreAudioDevice::SetObjectListenerProc (AudioObjectPropertyListenerProc callback, void * pClientData)
References GetError(), CLog::Log(), LOGERROR, m_DeviceId, and m_ObjectListenerProc.
Start()
void CCoreAudioDevice::Start ()
References GetError(), CLog::Log(), LOGERROR, m_DeviceId, m_IoProc, and m_Started.
Referenced by AddIOProc(), and CAESinkDARWINOSX::Initialize().
Stop()
void CCoreAudioDevice::Stop ()
References GetError(), CLog::Log(), LOGERROR, m_DeviceId, m_IoProc, and m_Started.
Referenced by Close(), CAESinkDARWINOSX::Deinitialize(), and RemoveIOProc().
SuppressDefaultOutputDeviceCB()
static void CCoreAudioDevice::SuppressDefaultOutputDeviceCB (unsigned int suppressTimeMs) inline static
References m_callbackSuppressTimer.
Referenced by CCoreAudioStream::SetPhysicalFormat(), and CCoreAudioStream::SetVirtualFormat().
Member Data Documentation
m_BufferSizeRestore
unsigned int CCoreAudioDevice::m_BufferSizeRestore = 0 protected
Referenced by Close(), and Open().
m_callbackSuppressTimer
XbmcThreads::EndTime CCoreAudioDevice::m_callbackSuppressTimer static protected
Referenced by defaultOutputDeviceChanged(), and SuppressDefaultOutputDeviceCB().
m_defaultOutputDeviceChangedCB
AudioObjectPropertyListenerProc CCoreAudioDevice::m_defaultOutputDeviceChangedCB = NULL static protected
Referenced by defaultOutputDeviceChanged(), and RegisterDefaultOutputDeviceChangedCB().
m_DeviceId
AudioDeviceID CCoreAudioDevice::m_DeviceId = 0 protected
Referenced by AddIOProc(), Close(), GetBufferSize(), GetDataSource(), GetDataSourceName(), GetDataSources(), GetHogStatus(), GetId(), GetMixingSupport(), GetName(), GetNominalSampleRate(), GetNumChannelsOfStream(), GetNumLatencyFrames(), GetPreferredChannelLayout(), GetPreferredChannelLayoutForStereo(), GetStreams(), GetTotalOutputChannels(), GetTransportType(), IsDigital(), IsRunning(), Open(), RemoveIOProc(), RemoveObjectListenerProc(), SetBufferSize(), SetCurrentVolume(), SetDataSource(), SetHogStatus(), SetMixingSupport(), SetNominalSampleRate(), SetObjectListenerProc(), Start(), and Stop().
m_frameSize
unsigned int CCoreAudioDevice::m_frameSize = 0 protected
m_HogPid
pid_t CCoreAudioDevice::m_HogPid = -1 protected
Referenced by SetHogStatus().
m_IoProc
AudioDeviceIOProc CCoreAudioDevice::m_IoProc = nullptr protected
Referenced by AddIOProc(), Close(), RemoveIOProc(), Start(), and Stop().
m_MixerRestore
int CCoreAudioDevice::m_MixerRestore = -1 protected
Referenced by Close(), and SetMixingSupport().
m_ObjectListenerProc
AudioObjectPropertyListenerProc CCoreAudioDevice::m_ObjectListenerProc = nullptr protected
Referenced by Close(), RemoveObjectListenerProc(), and SetObjectListenerProc().
m_OutputBufferIndex
unsigned int CCoreAudioDevice::m_OutputBufferIndex = 0 protected
m_SampleRateRestore
Float64 CCoreAudioDevice::m_SampleRateRestore = 0.0 protected
Referenced by Close(), and SetNominalSampleRate().
m_Started
bool CCoreAudioDevice::m_Started = false protected
Referenced by Start(), and Stop().
The documentation for this class was generated from the following files:
CoreAudioDevice.h
CoreAudioDevice.cpp