Kodi Documentation: CALSADeviceMonitor Class Reference
CALSADeviceMonitor Class Reference
#include <ALSADeviceMonitor.h>
Public Member Functions
CALSADeviceMonitor ()
~CALSADeviceMonitor ()
void Start ()
void Stop ()
Public Member Functions inherited from IPlatformService
virtual ~IPlatformService ()=default
Static Private Member Functions
static void FDEventCallback (int id, int fd, short revents, void *data)
Private Attributes
int m_fdMonitorId = 0
struct udev * m_udev
struct udev_monitor * m_udevMonitor
Constructor & Destructor Documentation
CALSADeviceMonitor()
CALSADeviceMonitor::CALSADeviceMonitor ()
~CALSADeviceMonitor()
CALSADeviceMonitor::~CALSADeviceMonitor ()
References Stop().
Member Function Documentation
FDEventCallback()
void CALSADeviceMonitor::FDEventCallback (int id, int fd, short revents, void * data) static private
References data(), IAE::DeviceChange(), CServiceBroker::GetActiveAE(), CLog::Log(), and LOGDEBUG.
Referenced by Start().
Start()
void CALSADeviceMonitor::Start ()
References CFDEventMonitor::AddFD(), err(), FDEventCallback(), CServiceBroker::GetPlatform(), CPlatform::GetService(), CLog::Log(), LOGERROR, LOGWARNING, m_fdMonitorId, m_udev, and m_udevMonitor.
Referenced by CAESinkALSA::EnumerateDevicesEx().
Stop()
void CALSADeviceMonitor::Stop ()
References CServiceBroker::GetPlatform(), CPlatform::GetService(), m_fdMonitorId, m_udev, m_udevMonitor, and CFDEventMonitor::RemoveFD().
Referenced by CAESinkALSA::Cleanup(), and ~CALSADeviceMonitor().
Member Data Documentation
m_fdMonitorId
int CALSADeviceMonitor::m_fdMonitorId = 0 private
Referenced by Start(), and Stop().
m_udev
struct udev* CALSADeviceMonitor::m_udev private
Referenced by Start(), and Stop().
m_udevMonitor
struct udev_monitor* CALSADeviceMonitor::m_udevMonitor private
Referenced by Start(), and Stop().
The documentation for this class was generated from the following files:
ALSADeviceMonitor.h
ALSADeviceMonitor.cpp