Kodi Documentation: Shaders::GL::BaseYUV2RGBGLSLShader Class Reference
Shaders::GL::BaseYUV2RGBGLSLShader Class Reference
#include <YUV2RGBShaderGL.h>
Public Member Functions
BaseYUV2RGBGLSLShader (bool rect, EShaderFormat format, bool stretch, AVColorPrimaries dst, AVColorPrimaries src, bool toneMap, ETONEMAPMETHOD toneMapMethod, std::shared_ptr< GLSLOutput > output)
~BaseYUV2RGBGLSLShader () override
void SetField (int field)
void SetWidth (int w)
void SetHeight (int h)
void SetColParams (AVColorSpace colSpace, int bits, bool limited, int textureBits)
void SetBlack (float black)
void SetContrast (float contrast)
void SetNonLinStretch (float stretch)
void SetDisplayMetadata (bool hasDisplayMetadata, const AVMasteringDisplayMetadata &displayMetadata, bool hasLightMetadata, AVContentLightMetadata lightMetadata)
void SetToneMapParam (ETONEMAPMETHOD method, float param)
void SetConvertFullColorRange (bool convertFullRange)
GLint GetVertexLoc ()
GLint GetYcoordLoc ()
GLint GetUcoordLoc ()
GLint GetVcoordLoc ()
void SetMatrices (const GLfloat *p, const GLfloat *m)
void SetAlpha (GLfloat alpha)
Public Member Functions inherited from Shaders::CGLSLShaderProgram
CGLSLShaderProgram ()
CGLSLShaderProgram (const std::string &vert, const std::string &frag)
~CGLSLShaderProgram () override
bool Enable () override
void Disable () override
bool CompileAndLink () override
Public Member Functions inherited from Shaders::CShaderProgram
CShaderProgram ()=default
virtual ~CShaderProgram ()
bool OK () const
CVertexShader * VertexShader ()
CPixelShader * PixelShader ()
virtual GLuint ProgramHandle ()
Protected Member Functions
void OnCompiledAndLinked () override
bool OnEnabled () override
void OnDisabled () override
void Free ()
Protected Member Functions inherited from Shaders::CGLSLShaderProgram
void Free ()
Protected Attributes
bool m_convertFullRange
EShaderFormat m_format
int m_width
int m_height
int m_field
bool m_hasDisplayMetadata = false
AVMasteringDisplayMetadata m_displayMetadata
bool m_hasLightMetadata = false
AVContentLightMetadata m_lightMetadata
bool m_toneMapping = false
ETONEMAPMETHOD m_toneMappingMethod = VS_TONEMAPMETHOD_OFF
float m_toneMappingParam = 1.0
bool m_colorConversion {false}
float m_black
float m_contrast
float m_stretch
const GLfloat * m_proj = nullptr
const GLfloat * m_model = nullptr
GLfloat m_alpha = 1.0f
std::string m_defines
std::shared_ptr< Shaders::GLSLOutput > m_glslOutput
CConvertMatrix m_convMatrix
GLint m_hYTex = -1
GLint m_hUTex = -1
GLint m_hVTex = -1
GLint m_hYuvMat = -1
GLint m_hStretch = -1
GLint m_hStep = -1
GLint m_hGammaSrc = -1
GLint m_hGammaDstInv = -1
GLint m_hPrimMat = -1
GLint m_hToneP1 = -1
GLint m_hCoefsDst = -1
GLint m_hLuminance = -1
GLint m_hVertex = -1
GLint m_hYcoord = -1
GLint m_hUcoord = -1
GLint m_hVcoord = -1
GLint m_hProj = -1
GLint m_hModel = -1
GLint m_hAlpha = -1
Protected Attributes inherited from Shaders::CGLSLShaderProgram
GLint m_lastProgram
bool m_validated = false
Protected Attributes inherited from Shaders::CShaderProgram
CVertexShader * m_pVP = nullptr
CPixelShader * m_pFP = nullptr
GLuint m_shaderProgram = 0
bool m_ok = false
Constructor & Destructor Documentation
BaseYUV2RGBGLSLShader()
BaseYUV2RGBGLSLShader::BaseYUV2RGBGLSLShader (bool rect, EShaderFormat format, bool stretch, AVColorPrimaries dst, AVColorPrimaries src, bool toneMap, ETONEMAPMETHOD toneMapMethod, std::shared_ptr< GLSLOutput > output)
References CServiceBroker::GetSettingsComponent(), Shaders::CShader::LoadSource(), CLog::Log(), LOGDEBUG, LOGERROR, m_black, m_colorConversion, m_contrast, m_convMatrix, m_defines, m_field, m_format, m_glslOutput, m_height, m_stretch, m_toneMapping, m_toneMappingMethod, m_width, CConvertMatrix::SetDestinationColorPrimaries(), CConvertMatrix::SetSourceColorPrimaries(), SHADER_NV12, SHADER_UYVY, SHADER_YUY2, SHADER_YV12, SHADER_YV12_10, SHADER_YV12_12, SHADER_YV12_14, SHADER_YV12_16, SHADER_YV12_9, Shaders::CShaderProgram::VertexShader(), VS_TONEMAPMETHOD_ACES, VS_TONEMAPMETHOD_HABLE, and VS_TONEMAPMETHOD_REINHARD.
~BaseYUV2RGBGLSLShader()
BaseYUV2RGBGLSLShader::~BaseYUV2RGBGLSLShader () override
References Free(), and m_glslOutput.
Member Function Documentation
Free()
void BaseYUV2RGBGLSLShader::Free () protected
References m_glslOutput.
Referenced by ~BaseYUV2RGBGLSLShader().
GetUcoordLoc()
GLint Shaders::GL::BaseYUV2RGBGLSLShader::GetUcoordLoc () inline
References m_hUcoord.
Referenced by CLinuxRendererGL::RenderSinglePass(), and CLinuxRendererGL::RenderToFBO().
GetVcoordLoc()
GLint Shaders::GL::BaseYUV2RGBGLSLShader::GetVcoordLoc () inline
References m_hVcoord.
Referenced by CLinuxRendererGL::RenderSinglePass(), and CLinuxRendererGL::RenderToFBO().
GetVertexLoc()
GLint Shaders::GL::BaseYUV2RGBGLSLShader::GetVertexLoc () inline
References m_hVertex.
Referenced by CLinuxRendererGL::RenderSinglePass(), and CLinuxRendererGL::RenderToFBO().
GetYcoordLoc()
GLint Shaders::GL::BaseYUV2RGBGLSLShader::GetYcoordLoc () inline
References m_hYcoord.
Referenced by CLinuxRendererGL::RenderSinglePass(), and CLinuxRendererGL::RenderToFBO().
OnCompiledAndLinked()
void BaseYUV2RGBGLSLShader::OnCompiledAndLinked () override protected virtual
Reimplemented from Shaders::CShaderProgram.
Reimplemented in Shaders::GL::YUV2RGBFilterShader4.
References m_glslOutput, m_hAlpha, m_hCoefsDst, m_hGammaDstInv, m_hGammaSrc, m_hLuminance, m_hModel, m_hPrimMat, m_hProj, m_hStep, m_hStretch, m_hToneP1, m_hUcoord, m_hUTex, m_hVcoord, m_hVertex, m_hVTex, m_hYcoord, m_hYTex, m_hYuvMat, Shaders::CShaderProgram::ProgramHandle(), and VerifyGLState.
Referenced by Shaders::GL::YUV2RGBFilterShader4::OnCompiledAndLinked().
OnDisabled()
void BaseYUV2RGBGLSLShader::OnDisabled () override protected virtual
Reimplemented from Shaders::CShaderProgram.
References m_glslOutput.
OnEnabled()
bool BaseYUV2RGBGLSLShader::OnEnabled () override protected virtual
Reimplemented from Shaders::CShaderProgram.
Reimplemented in Shaders::GL::YUV2RGBFilterShader4.
References CConvertMatrix::GetGammaDst(), CConvertMatrix::GetGammaSrc(), CToneMappers::GetLuminanceValue(), CConvertMatrix::GetPrimMat(), CConvertMatrix::GetRGBYuvCoefs(), CConvertMatrix::GetYuvMat(), m_alpha, m_black, m_colorConversion, m_contrast, m_convertFullRange, m_convMatrix, m_displayMetadata, m_glslOutput, m_hAlpha, m_hasDisplayMetadata, m_hasLightMetadata, m_hCoefsDst, m_height, m_hGammaDstInv, m_hGammaSrc, m_hLuminance, m_hModel, m_hPrimMat, m_hProj, m_hStep, m_hStretch, m_hToneP1, m_hUTex, m_hVTex, m_hYTex, m_hYuvMat, m_lightMetadata, m_model, m_proj, m_stretch, m_toneMapping, m_toneMappingMethod, m_toneMappingParam, m_width, CConvertMatrix::SetDestinationBlack(), CConvertMatrix::SetDestinationContrast(), CConvertMatrix::SetDestinationLimitedRange(), CMatrix< Order >::ToRaw(), VerifyGLState, VS_TONEMAPMETHOD_ACES, VS_TONEMAPMETHOD_HABLE, and VS_TONEMAPMETHOD_REINHARD.
Referenced by Shaders::GL::YUV2RGBFilterShader4::OnEnabled().
SetAlpha()
void Shaders::GL::BaseYUV2RGBGLSLShader::SetAlpha (GLfloat alpha) inline
References m_alpha.
Referenced by CLinuxRendererGL::RenderUpdate().
SetBlack()
void Shaders::GL::BaseYUV2RGBGLSLShader::SetBlack (float black) inline
References m_black.
Referenced by CLinuxRendererGL::RenderSinglePass(), and CLinuxRendererGL::RenderToFBO().
SetColParams()
void BaseYUV2RGBGLSLShader::SetColParams (AVColorSpace colSpace, int bits, bool limited, int textureBits)
References m_convMatrix, m_height, m_width, CConvertMatrix::SetSourceBitDepth(), CConvertMatrix::SetSourceColorSpace(), CConvertMatrix::SetSourceLimitedRange(), and CConvertMatrix::SetSourceTextureBitDepth().
Referenced by CLinuxRendererGL::RenderSinglePass(), and CLinuxRendererGL::RenderToFBO().
SetContrast()
void Shaders::GL::BaseYUV2RGBGLSLShader::SetContrast (float contrast) inline
References m_contrast.
Referenced by CLinuxRendererGL::RenderSinglePass(), and CLinuxRendererGL::RenderToFBO().
SetConvertFullColorRange()
void Shaders::GL::BaseYUV2RGBGLSLShader::SetConvertFullColorRange (bool convertFullRange) inline
References m_convertFullRange.
Referenced by CLinuxRendererGL::LoadShaders().
SetDisplayMetadata()
void BaseYUV2RGBGLSLShader::SetDisplayMetadata (bool hasDisplayMetadata, const AVMasteringDisplayMetadata & displayMetadata, bool hasLightMetadata, AVContentLightMetadata lightMetadata)
References m_displayMetadata, m_hasDisplayMetadata, m_hasLightMetadata, and m_lightMetadata.
Referenced by CLinuxRendererGL::RenderSinglePass(), and CLinuxRendererGL::RenderToFBO().
SetField()
void Shaders::GL::BaseYUV2RGBGLSLShader::SetField (int field) inline
References m_field.
Referenced by CLinuxRendererGL::RenderSinglePass(), and CLinuxRendererGL::RenderToFBO().
SetHeight()
void Shaders::GL::BaseYUV2RGBGLSLShader::SetHeight (int h) inline
References m_height.
Referenced by CLinuxRendererGL::RenderSinglePass(), and CLinuxRendererGL::RenderToFBO().
SetMatrices()
void Shaders::GL::BaseYUV2RGBGLSLShader::SetMatrices (const GLfloat * p, const GLfloat * m) inline
References m_model, and m_proj.
Referenced by CLinuxRendererGL::RenderSinglePass(), and CLinuxRendererGL::RenderToFBO().
SetNonLinStretch()
void Shaders::GL::BaseYUV2RGBGLSLShader::SetNonLinStretch (float stretch) inline
References m_stretch.
Referenced by CLinuxRendererGL::RenderSinglePass(), and CLinuxRendererGL::RenderToFBO().
SetToneMapParam()
void BaseYUV2RGBGLSLShader::SetToneMapParam (ETONEMAPMETHOD method, float param)
References m_toneMappingMethod, and m_toneMappingParam.
Referenced by CLinuxRendererGL::RenderSinglePass(), and CLinuxRendererGL::RenderToFBO().
SetWidth()
void Shaders::GL::BaseYUV2RGBGLSLShader::SetWidth (int w) inline
References m_width.
Referenced by CLinuxRendererGL::RenderSinglePass(), and CLinuxRendererGL::RenderToFBO().
Member Data Documentation
m_alpha
GLfloat Shaders::GL::BaseYUV2RGBGLSLShader::m_alpha = 1.0f protected
Referenced by OnEnabled(), and SetAlpha().
m_black
float Shaders::GL::BaseYUV2RGBGLSLShader::m_black protected
Referenced by BaseYUV2RGBGLSLShader(), OnEnabled(), and SetBlack().
m_colorConversion
bool Shaders::GL::BaseYUV2RGBGLSLShader::m_colorConversion {false} protected
Referenced by BaseYUV2RGBGLSLShader(), and OnEnabled().
m_contrast
float Shaders::GL::BaseYUV2RGBGLSLShader::m_contrast protected
Referenced by BaseYUV2RGBGLSLShader(), OnEnabled(), and SetContrast().
m_convertFullRange
bool Shaders::GL::BaseYUV2RGBGLSLShader::m_convertFullRange protected
Referenced by OnEnabled(), and SetConvertFullColorRange().
m_convMatrix
CConvertMatrix Shaders::GL::BaseYUV2RGBGLSLShader::m_convMatrix protected
Referenced by BaseYUV2RGBGLSLShader(), OnEnabled(), and SetColParams().
m_defines
std::string Shaders::GL::BaseYUV2RGBGLSLShader::m_defines protected
Referenced by BaseYUV2RGBGLSLShader(), Shaders::GL::YUV2RGBFilterShader4::YUV2RGBFilterShader4(), and Shaders::GL::YUV2RGBProgressiveShader::YUV2RGBProgressiveShader().
m_displayMetadata
AVMasteringDisplayMetadata Shaders::GL::BaseYUV2RGBGLSLShader::m_displayMetadata protected
Referenced by OnEnabled(), and SetDisplayMetadata().
m_field
int Shaders::GL::BaseYUV2RGBGLSLShader::m_field protected
Referenced by BaseYUV2RGBGLSLShader(), and SetField().
m_format
EShaderFormat Shaders::GL::BaseYUV2RGBGLSLShader::m_format protected
Referenced by BaseYUV2RGBGLSLShader().
m_glslOutput
std::shared_ptr<Shaders::GLSLOutput> Shaders::GL::BaseYUV2RGBGLSLShader::m_glslOutput protected
Referenced by BaseYUV2RGBGLSLShader(), Free(), OnCompiledAndLinked(), OnDisabled(), OnEnabled(), and ~BaseYUV2RGBGLSLShader().
m_hAlpha
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hAlpha = -1 protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hasDisplayMetadata
bool Shaders::GL::BaseYUV2RGBGLSLShader::m_hasDisplayMetadata = false protected
Referenced by OnEnabled(), and SetDisplayMetadata().
m_hasLightMetadata
bool Shaders::GL::BaseYUV2RGBGLSLShader::m_hasLightMetadata = false protected
Referenced by OnEnabled(), and SetDisplayMetadata().
m_hCoefsDst
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hCoefsDst = -1 protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_height
int Shaders::GL::BaseYUV2RGBGLSLShader::m_height protected
Referenced by BaseYUV2RGBGLSLShader(), OnEnabled(), SetColParams(), and SetHeight().
m_hGammaDstInv
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hGammaDstInv = -1 protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hGammaSrc
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hGammaSrc = -1 protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hLuminance
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hLuminance = -1 protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hModel
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hModel = -1 protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hPrimMat
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hPrimMat = -1 protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hProj
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hProj = -1 protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hStep
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hStep = -1 protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hStretch
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hStretch = -1 protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hToneP1
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hToneP1 = -1 protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hUcoord
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hUcoord = -1 protected
Referenced by GetUcoordLoc(), and OnCompiledAndLinked().
m_hUTex
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hUTex = -1 protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hVcoord
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hVcoord = -1 protected
Referenced by GetVcoordLoc(), and OnCompiledAndLinked().
m_hVertex
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hVertex = -1 protected
Referenced by GetVertexLoc(), and OnCompiledAndLinked().
m_hVTex
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hVTex = -1 protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hYcoord
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hYcoord = -1 protected
Referenced by GetYcoordLoc(), and OnCompiledAndLinked().
m_hYTex
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hYTex = -1 protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_hYuvMat
GLint Shaders::GL::BaseYUV2RGBGLSLShader::m_hYuvMat = -1 protected
Referenced by OnCompiledAndLinked(), and OnEnabled().
m_lightMetadata
AVContentLightMetadata Shaders::GL::BaseYUV2RGBGLSLShader::m_lightMetadata protected
Referenced by OnEnabled(), and SetDisplayMetadata().
m_model
const GLfloat* Shaders::GL::BaseYUV2RGBGLSLShader::m_model = nullptr protected
Referenced by OnEnabled(), and SetMatrices().
m_proj
const GLfloat* Shaders::GL::BaseYUV2RGBGLSLShader::m_proj = nullptr protected
Referenced by OnEnabled(), and SetMatrices().
m_stretch
float Shaders::GL::BaseYUV2RGBGLSLShader::m_stretch protected
Referenced by BaseYUV2RGBGLSLShader(), OnEnabled(), and SetNonLinStretch().
m_toneMapping
bool Shaders::GL::BaseYUV2RGBGLSLShader::m_toneMapping = false protected
Referenced by BaseYUV2RGBGLSLShader(), and OnEnabled().
m_toneMappingMethod
ETONEMAPMETHOD Shaders::GL::BaseYUV2RGBGLSLShader::m_toneMappingMethod = VS_TONEMAPMETHOD_OFF protected
Referenced by BaseYUV2RGBGLSLShader(), OnEnabled(), and SetToneMapParam().
m_toneMappingParam
float Shaders::GL::BaseYUV2RGBGLSLShader::m_toneMappingParam = 1.0 protected
Referenced by OnEnabled(), and SetToneMapParam().
m_width
int Shaders::GL::BaseYUV2RGBGLSLShader::m_width protected
Referenced by BaseYUV2RGBGLSLShader(), OnEnabled(), SetColParams(), and SetWidth().
The documentation for this class was generated from the following files:
YUV2RGBShaderGL.h
YUV2RGBShaderGL.cpp