Kodi Documentation: CVideoPlayerSubtitle Class Reference
CVideoPlayerSubtitle Class Reference
#include <VideoPlayerSubtitle.h>
Public Member Functions
CVideoPlayerSubtitle (CDVDOverlayContainer *pOverlayContainer, CProcessInfo &processInfo)
~CVideoPlayerSubtitle () override
void Process (double pts, double offset)
void Flush ()
void FindSubtitles (const char *strFilename)
int GetSubtitleCount ()
void UpdateOverlayInfo (const std::shared_ptr< CDVDInputStreamNavigator > &pStream, int iAction)
bool AcceptsData () const override
void SendMessage (std::shared_ptr< CDVDMsg > pMsg, int priority=0) override
void FlushMessages () override
bool OpenStream (CDVDStreamInfo hints) override
bool OpenStream (CDVDStreamInfo &hints, std::string &filename)
void CloseStream (bool bWaitForBuffers) override
bool IsInited () const override
bool IsStalled () const override
Public Member Functions inherited from IDVDStreamPlayer
IDVDStreamPlayer (CProcessInfo &processInfo)
virtual ~IDVDStreamPlayer ()=default
Private Attributes
CDVDOverlayContainer * m_pOverlayContainer
std::unique_ptr< CDVDSubtitleParser > m_pSubtitleFileParser
std::unique_ptr< CDVDOverlayCodec > m_pOverlayCodec
CDVDDemuxSPU m_dvdspus
CDVDStreamInfo m_streaminfo
double m_lastPts
CCriticalSection m_section
Additional Inherited Members
Public Types inherited from IDVDStreamPlayer
enum ESyncState { SYNC_STARTING , SYNC_WAITSYNC , SYNC_INSYNC }
Protected Attributes inherited from IDVDStreamPlayer
CProcessInfo & m_processInfo
Constructor & Destructor Documentation
CVideoPlayerSubtitle()
CVideoPlayerSubtitle::CVideoPlayerSubtitle (CDVDOverlayContainer * pOverlayContainer, CProcessInfo & processInfo)
References DVD_NOPTS_VALUE, m_lastPts, and m_pOverlayContainer.
~CVideoPlayerSubtitle()
CVideoPlayerSubtitle::~CVideoPlayerSubtitle () override
References CloseStream().
Member Function Documentation
AcceptsData()
bool CVideoPlayerSubtitle::AcceptsData () const override virtual
Implements IDVDStreamPlayer.
References CDVDOverlayContainer::GetSize(), and m_pOverlayContainer.
Referenced by CVideoPlayer::ReadPacket().
CloseStream()
void CVideoPlayerSubtitle::CloseStream (bool bWaitForBuffers) override virtual
Implements IDVDStreamPlayer.
References CDVDOverlayContainer::Clear(), CDVDDemuxSPU::FlushCurrentPacket(), m_dvdspus, m_pOverlayCodec, m_pOverlayContainer, m_pSubtitleFileParser, and m_section.
Referenced by OpenStream(), and ~CVideoPlayerSubtitle().
FindSubtitles()
void CVideoPlayerSubtitle::FindSubtitles (const char * strFilename)
Flush()
void CVideoPlayerSubtitle::Flush ()
References CDVDMsg::GENERAL_FLUSH, and SendMessage().
Referenced by CVideoPlayer::FlushBuffers().
FlushMessages()
void CVideoPlayerSubtitle::FlushMessages () inline override virtual
Implements IDVDStreamPlayer.
GetSubtitleCount()
int CVideoPlayerSubtitle::GetSubtitleCount ()
IsInited()
bool CVideoPlayerSubtitle::IsInited () const inline override virtual
Implements IDVDStreamPlayer.
IsStalled()
bool CVideoPlayerSubtitle::IsStalled () const inline override virtual
Implements IDVDStreamPlayer.
References CDVDOverlayContainer::GetSize(), and m_pOverlayContainer.
OpenStream() [1/2]
bool CVideoPlayerSubtitle::OpenStream (CDVDStreamInfo & hints, std::string & filename)
References CloseStream(), CDVDStreamInfo::codec, CDVDFactoryCodec::CreateOverlayCodec(), CDVDFactorySubtitle::CreateParser(), CLog::Log(), LOGDEBUG, LOGERROR, m_pOverlayCodec, m_pSubtitleFileParser, m_section, and m_streaminfo.
OpenStream() [2/2]
bool CVideoPlayerSubtitle::OpenStream (CDVDStreamInfo hints) inline override virtual
Implements IDVDStreamPlayer.
References CDVDStreamInfo::filename, and OpenStream().
Referenced by OpenStream().
Process()
void CVideoPlayerSubtitle::Process (double pts, double offset)
References CDVDOverlayContainer::Clear(), DVD_NOPTS_VALUE, DVD_SEC_TO_TIME(), CDVDOverlayContainer::GetSize(), m_lastPts, m_pOverlayContainer, m_pSubtitleFileParser, m_section, and CDVDOverlayContainer::ProcessAndAddOverlayIfValid().
Referenced by CVideoPlayer::Process().
SendMessage()
void CVideoPlayerSubtitle::SendMessage (std::shared_ptr< CDVDMsg > pMsg, int priority = 0) override virtual
Implements IDVDStreamPlayer.
References CDVDDemuxSPU::AddData(), CDVDStreamInfo::codec, color, CDVDMsg::DEMUXER_PACKET, DVD_NOPTS_VALUE, CDVDOverlayContainer::Flush(), CDVDMsg::GENERAL_FLUSH, CDVDMsg::GENERAL_RESET, DEMUX_PACKET::iSize, CLog::Log(), LOGDEBUG, CDVDDemuxSPU::m_bHasClut, CDVDDemuxSPU::m_clut, m_dvdspus, m_lastPts, m_pOverlayCodec, m_pOverlayContainer, m_pSubtitleFileParser, m_section, m_streaminfo, OC_OVERLAY, DEMUX_PACKET::pData, CDVDOverlayContainer::ProcessAndAddOverlayIfValid(), DEMUX_PACKET::pts, CDVDDemuxSPU::Reset(), CDVDMsg::SUBTITLE_CLUTCHANGE, and t.
Referenced by Flush(), CVideoPlayer::OnDiscNavResult(), and CVideoPlayer::ProcessSubData().
UpdateOverlayInfo()
void CVideoPlayerSubtitle::UpdateOverlayInfo (const std::shared_ptr< CDVDInputStreamNavigator > & pStream, int iAction) inline
References m_dvdspus, m_pOverlayContainer, and CDVDOverlayContainer::UpdateOverlayInfo().
Referenced by CVideoPlayer::OnAction(), CVideoPlayer::OnDiscNavResult(), and CVideoPlayer::ProcessSubData().
Member Data Documentation
m_dvdspus
CDVDDemuxSPU CVideoPlayerSubtitle::m_dvdspus private
Referenced by CloseStream(), SendMessage(), and UpdateOverlayInfo().
m_lastPts
double CVideoPlayerSubtitle::m_lastPts private
Referenced by CVideoPlayerSubtitle(), Process(), and SendMessage().
m_pOverlayCodec
std::unique_ptr<CDVDOverlayCodec> CVideoPlayerSubtitle::m_pOverlayCodec private
Referenced by CloseStream(), OpenStream(), and SendMessage().
m_pOverlayContainer
CDVDOverlayContainer* CVideoPlayerSubtitle::m_pOverlayContainer private
Referenced by AcceptsData(), CloseStream(), CVideoPlayerSubtitle(), IsStalled(), Process(), SendMessage(), and UpdateOverlayInfo().
m_pSubtitleFileParser
std::unique_ptr<CDVDSubtitleParser> CVideoPlayerSubtitle::m_pSubtitleFileParser private
Referenced by CloseStream(), OpenStream(), Process(), and SendMessage().
m_section
CCriticalSection CVideoPlayerSubtitle::m_section private
Referenced by CloseStream(), OpenStream(), Process(), and SendMessage().
m_streaminfo
CDVDStreamInfo CVideoPlayerSubtitle::m_streaminfo private
Referenced by OpenStream(), and SendMessage().
The documentation for this class was generated from the following files:
VideoPlayerSubtitle.h
VideoPlayerSubtitle.cpp