Kodi Documentation: anonymous_namespace{SettingConditions.cpp} Namespace Reference
anonymous_namespace{SettingConditions.cpp} Namespace Reference
Functions
bool AddonHasSettings (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool CheckMasterLock (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool HasPeripherals (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool HasPeripheralLibraries (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool HasRumbleFeature (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool HasRumbleController (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool HasPowerOffFeature (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool HasSystemSdrPeakLuminance (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool SupportsVideoSuperResolution (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool SupportsDolbyVision (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool SupportsScreenMove (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool IsHDRDisplay (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool IsMasterUser (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool HasSubtitlesFontExtensions (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool ProfileCanWriteDatabase (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool ProfileCanWriteSources (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool ProfileHasAddons (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool ProfileHasDatabase (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool ProfileHasSources (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool ProfileHasAddonManagerLocked (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool ProfileHasFilesLocked (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool ProfileHasMusicLocked (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool ProfileHasPicturesLocked (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool ProfileHasProgramsLocked (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool ProfileHasSettingsLocked (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool ProfileHasVideosLocked (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool ProfileLockMode (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool GreaterThan (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool GreaterThanOrEqual (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool LessThan (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
bool LessThanOrEqual (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
Function Documentation
AddonHasSettings()
bool anonymous_namespace{SettingConditions.cpp}::AddonHasSettings (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References ADDON::CHOICE_YES, CServiceBroker::GetAddonMgr(), and ADDON::SKIN.
CheckMasterLock()
bool anonymous_namespace{SettingConditions.cpp}::CheckMasterLock (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References KODI::UTILS::StringUtils::EqualsNoCase(), g_passwordManager, CGUIPassword::IsMasterLockUnlocked(), and value.
GreaterThan()
bool anonymous_namespace{SettingConditions.cpp}::GreaterThan (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References KODI::UTILS::StringUtils::IsInteger(), and value.
GreaterThanOrEqual()
bool anonymous_namespace{SettingConditions.cpp}::GreaterThanOrEqual (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References KODI::UTILS::StringUtils::IsInteger(), and value.
HasPeripheralLibraries()
bool anonymous_namespace{SettingConditions.cpp}::HasPeripheralLibraries (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CServiceBroker::GetAddonMgr(), ADDON::CAddonMgr::HasInstalledAddons(), and ADDON::PERIPHERALDLL.
HasPeripherals()
bool anonymous_namespace{SettingConditions.cpp}::HasPeripherals (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References PERIPHERALS::CPeripherals::GetNumberOfPeripherals(), and CServiceBroker::GetPeripherals().
HasPowerOffFeature()
bool anonymous_namespace{SettingConditions.cpp}::HasPowerOffFeature (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References PERIPHERALS::FEATURE_POWER_OFF, CServiceBroker::GetPeripherals(), and PERIPHERALS::CPeripherals::SupportsFeature().
HasRumbleController()
bool anonymous_namespace{SettingConditions.cpp}::HasRumbleController (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References PERIPHERALS::FEATURE_RUMBLE, CServiceBroker::GetPeripherals(), and PERIPHERALS::CPeripherals::HasPeripheralWithFeature().
HasRumbleFeature()
bool anonymous_namespace{SettingConditions.cpp}::HasRumbleFeature (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References PERIPHERALS::FEATURE_RUMBLE, CServiceBroker::GetPeripherals(), and PERIPHERALS::CPeripherals::SupportsFeature().
HasSubtitlesFontExtensions()
bool anonymous_namespace{SettingConditions.cpp}::HasSubtitlesFontExtensions (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References KODI::UTILS::FONT::IsSupportedFontExtension().
HasSystemSdrPeakLuminance()
bool anonymous_namespace{SettingConditions.cpp}::HasSystemSdrPeakLuminance (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CServiceBroker::GetWinSystem(), and CWinSystemBase::HasSystemSdrPeakLuminance().
IsHDRDisplay()
bool anonymous_namespace{SettingConditions.cpp}::IsHDRDisplay (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CServiceBroker::GetWinSystem(), and CWinSystemBase::IsHDRDisplay().
IsMasterUser()
bool anonymous_namespace{SettingConditions.cpp}::IsMasterUser (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CGUIPassword::bMasterUser, and g_passwordManager.
LessThan()
bool anonymous_namespace{SettingConditions.cpp}::LessThan (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References KODI::UTILS::StringUtils::IsInteger(), and value.
LessThanOrEqual()
bool anonymous_namespace{SettingConditions.cpp}::LessThanOrEqual (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References KODI::UTILS::StringUtils::IsInteger(), and value.
ProfileCanWriteDatabase()
bool anonymous_namespace{SettingConditions.cpp}::ProfileCanWriteDatabase (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CProfile::canWriteDatabases(), and CSettingConditions::GetCurrentProfile().
ProfileCanWriteSources()
bool anonymous_namespace{SettingConditions.cpp}::ProfileCanWriteSources (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CProfile::canWriteSources(), and CSettingConditions::GetCurrentProfile().
ProfileHasAddonManagerLocked()
bool anonymous_namespace{SettingConditions.cpp}::ProfileHasAddonManagerLocked (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CProfile::addonmanagerLocked(), and CSettingConditions::GetCurrentProfile().
ProfileHasAddons()
bool anonymous_namespace{SettingConditions.cpp}::ProfileHasAddons (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CSettingConditions::GetCurrentProfile(), and CProfile::hasAddons().
ProfileHasDatabase()
bool anonymous_namespace{SettingConditions.cpp}::ProfileHasDatabase (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CSettingConditions::GetCurrentProfile(), and CProfile::hasDatabases().
ProfileHasFilesLocked()
bool anonymous_namespace{SettingConditions.cpp}::ProfileHasFilesLocked (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CProfile::filesLocked(), and CSettingConditions::GetCurrentProfile().
ProfileHasMusicLocked()
bool anonymous_namespace{SettingConditions.cpp}::ProfileHasMusicLocked (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CSettingConditions::GetCurrentProfile(), and CProfile::musicLocked().
ProfileHasPicturesLocked()
bool anonymous_namespace{SettingConditions.cpp}::ProfileHasPicturesLocked (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CSettingConditions::GetCurrentProfile(), and CProfile::picturesLocked().
ProfileHasProgramsLocked()
bool anonymous_namespace{SettingConditions.cpp}::ProfileHasProgramsLocked (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CSettingConditions::GetCurrentProfile(), and CProfile::programsLocked().
ProfileHasSettingsLocked()
bool anonymous_namespace{SettingConditions.cpp}::ProfileHasSettingsLocked (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References LOCK_LEVEL::ADVANCED, LOCK_LEVEL::ALL, KODI::UTILS::StringUtils::EqualsNoCase(), LOCK_LEVEL::EXPERT, CSettingConditions::GetCurrentProfile(), LOCK_LEVEL::NONE, CProfile::settingsLockLevel(), LOCK_LEVEL::STANDARD, and value.
ProfileHasSources()
bool anonymous_namespace{SettingConditions.cpp}::ProfileHasSources (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CSettingConditions::GetCurrentProfile(), and CProfile::hasSources().
ProfileHasVideosLocked()
bool anonymous_namespace{SettingConditions.cpp}::ProfileHasVideosLocked (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CSettingConditions::GetCurrentProfile(), and CProfile::videoLocked().
ProfileLockMode()
bool anonymous_namespace{SettingConditions.cpp}::ProfileLockMode (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CSettingConditions::GetCurrentProfile(), CProfile::getLockMode(), and value.
SupportsDolbyVision()
bool anonymous_namespace{SettingConditions.cpp}::SupportsDolbyVision (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CWinSystemBase::GetDisplayHDRCapabilities(), CServiceBroker::GetWinSystem(), and CHDRCapabilities::SupportsDolbyVision().
SupportsScreenMove()
bool anonymous_namespace{SettingConditions.cpp}::SupportsScreenMove (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CServiceBroker::GetWinSystem(), and CWinSystemBase::SupportsScreenMove().
SupportsVideoSuperResolution()
bool anonymous_namespace{SettingConditions.cpp}::SupportsVideoSuperResolution (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References CServiceBroker::GetWinSystem(), and CWinSystemBase::SupportsVideoSuperResolution().