Kodi Documentation: CConvolutionShaderSeparable Class Reference
CConvolutionShaderSeparable Class Reference
#include <WinVideoFilter.h>
Public Member Functions
CConvolutionShaderSeparable ()=default
~CConvolutionShaderSeparable ()=default
bool Create (ESCALINGMETHOD method, const std::shared_ptr< COutputShader > &pOutputShader=nullptr) override
void Render (CD3DTexture &sourceTexture, CD3DTexture &target, CRect sourceRect, CRect destRect, bool useLimitRange) override
Public Member Functions inherited from CConvolutionShader
virtual ~CConvolutionShader ()=default
Protected Member Functions
bool ChooseIntermediateD3DFormat ()
bool CreateIntermediateRenderTarget (unsigned int width, unsigned int height)
bool ClearIntermediateRenderTarget ()
void PrepareParameters (unsigned int sourceWidth, unsigned int sourceHeight, unsigned int destWidth, unsigned int destHeight, CRect sourceRect, CRect destRect)
void SetShaderParameters (CD3DTexture &sourceTexture, float *texSteps, int texStepsCount, bool useLimitRange) override
void SetStepParams (unsigned iPass) override
Protected Member Functions inherited from CConvolutionShader
CConvolutionShader ()=default
virtual bool ChooseKernelD3DFormat ()
virtual bool CreateHQKernel (ESCALINGMETHOD method)
Protected Member Functions inherited from CWinShader
CWinShader ()=default
virtual ~CWinShader ()=default
virtual bool CreateVertexBuffer (unsigned int vertCount, unsigned int vertSize)
virtual bool LockVertexBuffer (void **data)
virtual bool UnlockVertexBuffer ()
virtual bool LoadEffect (const std::string &filename, DefinesMap *defines)
virtual bool Execute (const std::vector< CD3DTexture * > &targets, unsigned int vertexIndexStep)
virtual bool CreateInputLayout (D3D11_INPUT_ELEMENT_DESC *layout, unsigned numElements)
Private Attributes
CD3DTexture m_IntermediateTarget
DXGI_FORMAT m_IntermediateFormat = DXGI_FORMAT_UNKNOWN
unsigned int m_sourceWidth = 0
unsigned int m_sourceHeight = 0
unsigned int m_destWidth = 0
unsigned int m_destHeight = 0
CRect m_sourceRect = {}
CRect m_destRect = {}
Additional Inherited Members
Protected Attributes inherited from CConvolutionShader
bool m_floattex = false
bool m_rgba = false
DXGI_FORMAT m_KernelFormat = DXGI_FORMAT_UNKNOWN
CD3DTexture m_HQKernelTexture
std::shared_ptr< COutputShader > m_pOutShader = nullptr
Protected Attributes inherited from CWinShader
CD3DEffect m_effect
CD3DTexture * m_target = nullptr
Constructor & Destructor Documentation
CConvolutionShaderSeparable()
CConvolutionShaderSeparable::CConvolutionShaderSeparable () explicit default
~CConvolutionShaderSeparable()
CConvolutionShaderSeparable::~CConvolutionShaderSeparable () default
Member Function Documentation
ChooseIntermediateD3DFormat()
bool CConvolutionShaderSeparable::ChooseIntermediateD3DFormat () protected
References DX::DXGIFormatToString(), LOGDEBUG, LOGINFO, m_IntermediateFormat, and usage.
Referenced by Create().
ClearIntermediateRenderTarget()
bool CConvolutionShaderSeparable::ClearIntermediateRenderTarget () protected
References color, DX::DeviceResources::Get(), CD3DTexture::GetRenderTarget(), and m_IntermediateTarget.
Referenced by PrepareParameters().
Create()
bool CConvolutionShaderSeparable::Create (ESCALINGMETHOD method, const std::shared_ptr< COutputShader > & pOutputShader = nullptr) override virtual
Implements CConvolutionShader.
References ChooseIntermediateD3DFormat(), CConvolutionShader::ChooseKernelD3DFormat(), CConvolutionShader::CreateHQKernel(), CWinShader::CreateInputLayout(), CWinShader::CreateVertexBuffer(), CWinShader::LoadEffect(), LOGERROR, CConvolutionShader::m_floattex, CConvolutionShader::m_pOutShader, CConvolutionShader::m_rgba, VS_SCALINGMETHOD_CUBIC_MITCHELL, VS_SCALINGMETHOD_LANCZOS2, VS_SCALINGMETHOD_LANCZOS3, VS_SCALINGMETHOD_LANCZOS3_FAST, VS_SCALINGMETHOD_SPLINE36, and VS_SCALINGMETHOD_SPLINE36_FAST.
CreateIntermediateRenderTarget()
bool CConvolutionShaderSeparable::CreateIntermediateRenderTarget (unsigned int width, unsigned int height) protected
References CD3DTexture::Create(), CD3DTexture::Get(), LOGERROR, m_IntermediateFormat, m_IntermediateTarget, and CD3DTexture::Release().
Referenced by Render().
PrepareParameters()
void CConvolutionShaderSeparable::PrepareParameters (unsigned int sourceWidth, unsigned int sourceHeight, unsigned int destWidth, unsigned int destHeight, CRect sourceRect, CRect destRect) protected
References ClearIntermediateRenderTarget(), CWIN32Util::CropSource(), CWinShader::LockVertexBuffer(), m_destHeight, m_destRect, m_destWidth, m_sourceHeight, m_sourceRect, m_sourceWidth, CConvolutionShader::Vertex::tu, CConvolutionShader::Vertex::tv, CWinShader::UnlockVertexBuffer(), CConvolutionShader::Vertex::x, CRectGen< T >::x1, CRectGen< T >::x2, CConvolutionShader::Vertex::y, CRectGen< T >::y1, CRectGen< T >::y2, and CConvolutionShader::Vertex::z.
Referenced by Render().
Render()
void CConvolutionShaderSeparable::Render (CD3DTexture & sourceTexture, CD3DTexture & target, CRect sourceRect, CRect destRect, bool useLimitRange) override virtual
Implements CConvolutionShader.
References CreateIntermediateRenderTarget(), CWinShader::Execute(), CD3DTexture::GetHeight(), CD3DTexture::GetWidth(), m_destWidth, m_IntermediateTarget, m_sourceHeight, PrepareParameters(), and SetShaderParameters().
SetShaderParameters()
void CConvolutionShaderSeparable::SetShaderParameters (CD3DTexture & sourceTexture, float * texSteps, int texStepsCount, bool useLimitRange) override protected virtual
Implements CConvolutionShader.
References CD3DTexture::GetHeight(), CD3DTexture::GetWidth(), CWinShader::m_effect, CConvolutionShader::m_HQKernelTexture, CConvolutionShader::m_pOutShader, CD3DEffect::SetFloatArray(), CD3DEffect::SetTechnique(), and CD3DEffect::SetTexture().
Referenced by Render().
SetStepParams()
void CConvolutionShaderSeparable::SetStepParams (unsigned iPass) override protected virtual
Reimplemented from CWinShader.
References DX::DeviceResources::Get(), CD3DTexture::GetHeight(), CD3DTexture::GetWidth(), CServiceBroker::GetWinSystem(), CWinShader::m_effect, m_IntermediateTarget, CWinShader::m_target, CD3DEffect::SetFloatArray(), and CD3DEffect::SetTexture().
Member Data Documentation
m_destHeight
unsigned int CConvolutionShaderSeparable::m_destHeight = 0 private
Referenced by PrepareParameters().
m_destRect
CRect CConvolutionShaderSeparable::m_destRect = {} private
Referenced by PrepareParameters().
m_destWidth
unsigned int CConvolutionShaderSeparable::m_destWidth = 0 private
Referenced by PrepareParameters(), and Render().
m_IntermediateFormat
DXGI_FORMAT CConvolutionShaderSeparable::m_IntermediateFormat = DXGI_FORMAT_UNKNOWN private
Referenced by ChooseIntermediateD3DFormat(), and CreateIntermediateRenderTarget().
m_IntermediateTarget
CD3DTexture CConvolutionShaderSeparable::m_IntermediateTarget private
Referenced by ClearIntermediateRenderTarget(), CreateIntermediateRenderTarget(), Render(), and SetStepParams().
m_sourceHeight
unsigned int CConvolutionShaderSeparable::m_sourceHeight = 0 private
Referenced by PrepareParameters(), and Render().
m_sourceRect
CRect CConvolutionShaderSeparable::m_sourceRect = {} private
Referenced by PrepareParameters().
m_sourceWidth
unsigned int CConvolutionShaderSeparable::m_sourceWidth = 0 private
Referenced by PrepareParameters().
The documentation for this class was generated from the following files:
WinVideoFilter.h
WinVideoFilter.cpp