Kodi Documentation: KODI::WINDOWING::GBM::CDRMAtomic::CDRMAtomicRequest Class Reference
KODI::WINDOWING::GBM::CDRMAtomic::CDRMAtomicRequest Class Reference
Classes
struct DrmModeAtomicReqDeleter
Public Member Functions
CDRMAtomicRequest ()
~CDRMAtomicRequest ()=default
CDRMAtomicRequest (const CDRMAtomicRequest &right)=delete
drmModeAtomicReqPtr Get () const
bool AddProperty (CDRMObject *object, const char *name, uint64_t value)
void LogAtomicRequest ()
Static Public Member Functions
static void LogAtomicDiff (CDRMAtomicRequest *current, CDRMAtomicRequest *old)
Static Private Member Functions
static void LogAtomicRequest (uint8_t logLevel, std::map< CDRMObject *, std::map< uint32_t, uint64_t > > &atomicRequestItems)
Private Attributes
std::map< CDRMObject *, std::map< uint32_t, uint64_t > > m_atomicRequestItems
std::unique_ptr< drmModeAtomicReq, DrmModeAtomicReqDeleter > m_atomicRequest
Constructor & Destructor Documentation
CDRMAtomicRequest() [1/2]
CDRMAtomic::CDRMAtomicRequest::CDRMAtomicRequest ()
~CDRMAtomicRequest()
KODI::WINDOWING::GBM::CDRMAtomic::CDRMAtomicRequest::~CDRMAtomicRequest () default
CDRMAtomicRequest() [2/2]
KODI::WINDOWING::GBM::CDRMAtomic::CDRMAtomicRequest::CDRMAtomicRequest (const CDRMAtomicRequest & right) delete
Member Function Documentation
AddProperty()
bool CDRMAtomic::CDRMAtomicRequest::AddProperty (CDRMObject * object, const char * name, uint64_t value)
References KODI::WINDOWING::GBM::CDRMObject::GetId(), name, and value.
Referenced by KODI::WINDOWING::GBM::CDRMAtomic::AddProperty().
Get()
drmModeAtomicReqPtr KODI::WINDOWING::GBM::CDRMAtomic::CDRMAtomicRequest::Get () const inline
References m_atomicRequest.
Referenced by KODI::WINDOWING::GBM::CDRMAtomic::DrmAtomicCommit().
LogAtomicDiff()
void CDRMAtomic::CDRMAtomicRequest::LogAtomicDiff (CDRMAtomicRequest * current, CDRMAtomicRequest * old) static
References CLog::Log(), LOGDEBUG, LOGERROR, and m_atomicRequestItems.
Referenced by KODI::WINDOWING::GBM::CDRMAtomic::DrmAtomicCommit().
LogAtomicRequest() [1/2]
void CDRMAtomic::CDRMAtomicRequest::LogAtomicRequest ()
References CLog::Log(), and LOGDEBUG.
Referenced by KODI::WINDOWING::GBM::CDRMAtomic::DrmAtomicCommit().
LogAtomicRequest() [2/2]
void CDRMAtomic::CDRMAtomicRequest::LogAtomicRequest (uint8_t logLevel, std::map< CDRMObject *, std::map< uint32_t, uint64_t > > & atomicRequestItems) static private
References CLog::Log().
Member Data Documentation
m_atomicRequest
std::unique_ptr<drmModeAtomicReq, DrmModeAtomicReqDeleter> KODI::WINDOWING::GBM::CDRMAtomic::CDRMAtomicRequest::m_atomicRequest private
Referenced by Get().
m_atomicRequestItems
std::map<CDRMObject*, std::map<uint32_t, uint64_t> > KODI::WINDOWING::GBM::CDRMAtomic::CDRMAtomicRequest::m_atomicRequestItems private
Referenced by LogAtomicDiff().
The documentation for this class was generated from the following files:
DRMAtomic.h
DRMAtomic.cpp