Kodi Documentation: WSDiscovery::CWSDiscoveryPosix Class Reference
WSDiscovery::CWSDiscoveryPosix Class Reference
#include <SMBWSDiscovery.h>
Public Member Functions
CWSDiscoveryPosix ()
~CWSDiscoveryPosix () override
bool StartServices () override
bool StopServices () override
bool IsRunning () override
bool GetServerList (CFileItemList &items)
long long GetInstanceID () const
void SetItems (std::vector< WSDiscovery::wsd_req_info > entries)
bool GetCached (const std::string &strHostName, std::string &strIpAddress)
Public Member Functions inherited from WSDiscovery::IWSDiscovery
virtual ~IWSDiscovery ()=default
Static Public Member Functions
static bool IsInitialized ()
Static Public Member Functions inherited from WSDiscovery::IWSDiscovery
static std::unique_ptr< IWSDiscovery > GetInstance ()
Private Attributes
CCriticalSection m_critWSD
long long wsd_instance_id
std::unique_ptr< WSDiscovery::CWSDiscoveryListenerUDP > m_WSDListenerUDP
std::vector< WSDiscovery::wsd_req_info > m_vecWSDInfo
Static Private Attributes
static std::atomic< bool > m_isInitialized {false}
Constructor & Destructor Documentation
CWSDiscoveryPosix()
WSDiscovery::CWSDiscoveryPosix::CWSDiscoveryPosix ()
References m_isInitialized, m_WSDListenerUDP, and wsd_instance_id.
~CWSDiscoveryPosix()
WSDiscovery::CWSDiscoveryPosix::~CWSDiscoveryPosix () override
References StopServices().
Member Function Documentation
GetCached()
bool WSDiscovery::CWSDiscoveryPosix::GetCached (const std::string & strHostName, std::string & strIpAddress)
References CLog::Log(), LOGDEBUG, LOGWSDISCOVERY, m_critWSD, and m_vecWSDInfo.
Referenced by CDNSNameCache::GetCached().
GetInstanceID()
long long WSDiscovery::CWSDiscoveryPosix::GetInstanceID () const inline
References wsd_instance_id.
Referenced by WSDiscovery::CWSDiscoveryListenerUDP::buildSoapMessage().
GetServerList()
bool WSDiscovery::CWSDiscoveryPosix::GetServerList (CFileItemList & items)
References CFileItemList::Add(), m_critWSD, and m_vecWSDInfo.
Referenced by XFILE::CSMBDirectory::GetDirectory().
IsInitialized()
static bool WSDiscovery::CWSDiscoveryPosix::IsInitialized () inline static
References m_isInitialized.
Referenced by CDNSNameCache::GetCached().
IsRunning()
bool WSDiscovery::CWSDiscoveryPosix::IsRunning () override virtual
Implements WSDiscovery::IWSDiscovery.
References m_WSDListenerUDP.
SetItems()
void WSDiscovery::CWSDiscoveryPosix::SetItems (std::vector< WSDiscovery::wsd_req_info > entries)
References m_critWSD, and m_vecWSDInfo.
Referenced by WSDiscovery::CWSDiscoveryListenerUDP::ParseBuffer(), and WSDiscovery::CWSDiscoveryListenerUDP::Start().
StartServices()
bool WSDiscovery::CWSDiscoveryPosix::StartServices () override virtual
Implements WSDiscovery::IWSDiscovery.
References m_WSDListenerUDP.
StopServices()
bool WSDiscovery::CWSDiscoveryPosix::StopServices () override virtual
Implements WSDiscovery::IWSDiscovery.
References m_WSDListenerUDP.
Referenced by ~CWSDiscoveryPosix().
Member Data Documentation
m_critWSD
CCriticalSection WSDiscovery::CWSDiscoveryPosix::m_critWSD private
Referenced by GetCached(), GetServerList(), and SetItems().
m_isInitialized
std::atomic< bool > WSDiscovery::CWSDiscoveryPosix::m_isInitialized {false} static private
Referenced by CWSDiscoveryPosix(), and IsInitialized().
m_vecWSDInfo
std::vector<WSDiscovery::wsd_req_info> WSDiscovery::CWSDiscoveryPosix::m_vecWSDInfo private
Referenced by GetCached(), GetServerList(), and SetItems().
m_WSDListenerUDP
std::unique_ptr<WSDiscovery::CWSDiscoveryListenerUDP> WSDiscovery::CWSDiscoveryPosix::m_WSDListenerUDP private
Referenced by CWSDiscoveryPosix(), IsRunning(), StartServices(), and StopServices().
wsd_instance_id
long long WSDiscovery::CWSDiscoveryPosix::wsd_instance_id private
Referenced by CWSDiscoveryPosix(), and GetInstanceID().
The documentation for this class was generated from the following files:
SMBWSDiscovery.h
SMBWSDiscovery.cpp