Kodi Documentation: TestDateTimeSpan.cpp File Reference
TestDateTimeSpan.cpp File Reference
#include "XBDateTime.h"
#include <gtest/gtest.h>
Classes
class TestDateTimeSpan
Functions
TEST_F (TestDateTimeSpan, Operators)
TEST_F (TestDateTimeSpan, SetDateTimeSpan)
TEST_F (TestDateTimeSpan, SetFromPeriod)
TEST_F (TestDateTimeSpan, SetFromTimeString)
Function Documentation
TEST_F() [1/4]
TEST_F (TestDateTimeSpan , Operators)
References EXPECT_TRUE().
TEST_F() [2/4]
TEST_F (TestDateTimeSpan , SetDateTimeSpan)
References EXPECT_EQ(), CDateTimeSpan::GetDays(), CDateTimeSpan::GetHours(), CDateTimeSpan::GetMinutes(), CDateTimeSpan::GetSeconds(), CDateTimeSpan::GetSecondsTotal(), and CDateTimeSpan::SetDateTimeSpan().
TEST_F() [3/4]
TEST_F (TestDateTimeSpan , SetFromPeriod)
References EXPECT_EQ(), CDateTimeSpan::GetDays(), and CDateTimeSpan::SetFromPeriod().
TEST_F() [4/4]
TEST_F (TestDateTimeSpan , SetFromTimeString)
References EXPECT_EQ(), CDateTimeSpan::GetHours(), CDateTimeSpan::GetMinutes(), and CDateTimeSpan::SetFromTimeString().