Kodi Documentation: CFrameBufferObject Class Reference
CFrameBufferObject Class Reference
#include <FrameBufferObject.h>
Public Member Functions
CFrameBufferObject ()
bool IsSupported ()
bool IsValid () const
bool IsBound () const
bool Initialize ()
void Cleanup ()
void SetFiltering (GLenum target, GLenum mode)
bool CreateAndBindToTexture (GLenum target, int width, int height, GLenum format, GLenum type=GL_UNSIGNED_BYTE, GLenum filter=GL_LINEAR, GLenum clampmode=GL_CLAMP_TO_EDGE)
GLuint Texture () const
bool BeginRender ()
void EndRender () const
Private Attributes
GLuint m_fbo = 0
bool m_valid
bool m_bound
bool m_supported
GLuint m_texid = 0
Constructor & Destructor Documentation
CFrameBufferObject()
CFrameBufferObject::CFrameBufferObject ()
References m_bound, m_supported, and m_valid.
Member Function Documentation
BeginRender()
bool CFrameBufferObject::BeginRender ()
References IsBound(), IsValid(), and m_fbo.
Cleanup()
void CFrameBufferObject::Cleanup ()
References IsValid(), m_bound, m_fbo, m_texid, and m_valid.
Referenced by Initialize().
CreateAndBindToTexture()
bool CFrameBufferObject::CreateAndBindToTexture (GLenum target, int width, int height, GLenum format, GLenum type = GL_UNSIGNED_BYTE, GLenum filter = GL_LINEAR, GLenum clampmode = GL_CLAMP_TO_EDGE)
References IsValid(), m_bound, m_fbo, m_texid, and VerifyGLState.
EndRender()
void CFrameBufferObject::EndRender () const
References IsValid().
Initialize()
bool CFrameBufferObject::Initialize ()
References Cleanup(), IsSupported(), m_fbo, m_valid, and VerifyGLState.
IsBound()
bool CFrameBufferObject::IsBound () const inline
References m_bound.
Referenced by BeginRender().
IsSupported()
bool CFrameBufferObject::IsSupported ()
References CServiceBroker::GetRenderSystem(), and m_supported.
Referenced by Initialize().
IsValid()
bool CFrameBufferObject::IsValid () const inline
References m_valid.
Referenced by BeginRender(), Cleanup(), CreateAndBindToTexture(), and EndRender().
SetFiltering()
void CFrameBufferObject::SetFiltering (GLenum target, GLenum mode)
References m_texid.
Texture()
GLuint CFrameBufferObject::Texture () const inline
References m_texid.
Member Data Documentation
m_bound
bool CFrameBufferObject::m_bound private
Referenced by CFrameBufferObject(), Cleanup(), CreateAndBindToTexture(), and IsBound().
m_fbo
GLuint CFrameBufferObject::m_fbo = 0 private
Referenced by BeginRender(), Cleanup(), CreateAndBindToTexture(), and Initialize().
m_supported
bool CFrameBufferObject::m_supported private
Referenced by CFrameBufferObject(), and IsSupported().
m_texid
GLuint CFrameBufferObject::m_texid = 0 private
Referenced by Cleanup(), CreateAndBindToTexture(), SetFiltering(), and Texture().
m_valid
bool CFrameBufferObject::m_valid private
Referenced by CFrameBufferObject(), Cleanup(), Initialize(), and IsValid().
The documentation for this class was generated from the following files:
FrameBufferObject.h
FrameBufferObject.cpp