Kodi Documentation: KODI::VIDEO::CVideoGeneratedImageFileLoader Class Reference
KODI::VIDEO::CVideoGeneratedImageFileLoader Class Reference
Generates a texture for a thumbnail of a video file, for a specific chapter or from a frame approx 1/3 into the video.
#include <VideoGeneratedImageFileLoader.h>
Public Member Functions
bool CanLoad (const std::string &specialType) const override
std::unique_ptr< CTexture > Load (const IMAGE_FILES::CImageFileURL &imageFile) const override
Public Member Functions inherited from IMAGE_FILES::ISpecialImageFileLoader
virtual ~ISpecialImageFileLoader ()=default
Detailed Description
Generates a texture for a thumbnail of a video file, for a specific chapter or from a frame approx 1/3 into the video.
Member Function Documentation
CanLoad()
bool KODI::VIDEO::CVideoGeneratedImageFileLoader::CanLoad (const std::string & specialType) const override virtual
Implements IMAGE_FILES::ISpecialImageFileLoader.
Load()
std::unique_ptr< CTexture > KODI::VIDEO::CVideoGeneratedImageFileLoader::Load (const IMAGE_FILES::CImageFileURL & imageFile) const override virtual
Implements IMAGE_FILES::ISpecialImageFileLoader.
References CDVDFileInfo::ExtractThumbToTexture(), IMAGE_FILES::CImageFileURL::GetOption(), CServiceBroker::GetSettingsComponent(), IMAGE_FILES::CImageFileURL::GetTargetFile(), URIUtils::IsInRAR(), and CSettings::SETTING_MYVIDEOS_EXTRACTTHUMB.
The documentation for this class was generated from the following files:
VideoGeneratedImageFileLoader.h
VideoGeneratedImageFileLoader.cpp