Kodi Documentation: PredicateAudioFilter Class Reference
PredicateAudioFilter Class Reference
Public Member Functions
PredicateAudioFilter (int audioStream, bool preferStereo)
bool operator() (const SelectionStream &lh, const SelectionStream &rh)
Private Attributes
int currentAudioStream
bool preferStereo
Constructor & Destructor Documentation
PredicateAudioFilter()
PredicateAudioFilter::PredicateAudioFilter (int audioStream, bool preferStereo) inline explicit
Member Function Documentation
operator()()
bool PredicateAudioFilter::operator() (const SelectionStream & lh, const SelectionStream & rh) inline
References SelectionStream::channels, SelectionStream::codec, CLangCodeExpander::CompareISO639Codes(), currentAudioStream, FLAG_DEFAULT, FLAG_HEARING_IMPAIRED, FLAG_ORIGINAL, FLAG_VISUAL_IMPAIRED, SelectionStream::flags, g_LangCodeExpander, g_langInfo, StreamUtils::GetCodecPriority(), CServiceBroker::GetSettingsComponent(), SelectionStream::language, PREDICATE_RETURN, preferStereo, CSettings::SETTING_ACCESSIBILITY_AUDIOHEARING, CSettings::SETTING_ACCESSIBILITY_AUDIOVISUAL, CSettings::SETTING_LOCALE_AUDIOLANGUAGE, CSettings::SETTING_VIDEOPLAYER_PREFERDEFAULTFLAG, and SelectionStream::type_index.
Member Data Documentation
currentAudioStream
int PredicateAudioFilter::currentAudioStream private
Referenced by operator()().
preferStereo
bool PredicateAudioFilter::preferStereo private
Referenced by operator()().
The documentation for this class was generated from the following file:
VideoPlayer.cpp