Kodi Documentation: CMediaSourceSettings Class Reference
CMediaSourceSettings Class Reference
#include <MediaSourceSettings.h>
Public Member Functions
void OnSettingsLoaded () override
Settings have been loaded.
void OnSettingsUnloaded () override
Setting values have been unloaded.
bool Load ()
bool Load (const std::string &file)
bool Save ()
bool Save (const std::string &file) const
void Clear ()
std::vector< CMediaSource > * GetSources (const std::string &type)
const std::string & GetDefaultSource (const std::string &type) const
void SetDefaultSource (const std::string &type, const std::string &source)
bool UpdateSource (const std::string &strType, const std::string &strOldName, const std::string &strUpdateChild, const std::string &strUpdateValue)
bool DeleteSource (const std::string &strType, const std::string &strName, const std::string &strPath, bool virtualSource=false)
bool AddShare (const std::string &type, const CMediaSource &share)
bool UpdateShare (const std::string &type, const std::string &oldName, const CMediaSource &share)
Public Member Functions inherited from ISettingsHandler
virtual ~ISettingsHandler ()=default
virtual bool OnSettingsLoading ()
Settings loading has been initiated.
virtual bool OnSettingsSaving () const
Settings saving has been initiated.
virtual void OnSettingsSaved () const
Settings have been saved.
virtual void OnSettingsCleared ()
Settings have been cleared.
Static Public Member Functions
static CMediaSourceSettings & GetInstance ()
static std::string GetSourcesFile ()
Protected Member Functions
CMediaSourceSettings ()
CMediaSourceSettings (const CMediaSourceSettings &)=delete
CMediaSourceSettings & operator= (CMediaSourceSettings const &)=delete
~CMediaSourceSettings () override
Private Member Functions
bool GetSource (const std::string &category, const tinyxml2::XMLNode *source, CMediaSource &share)
void GetSources (const tinyxml2::XMLNode *rootElement, const std::string &tagName, std::vector< CMediaSource > &items, std::string &defaultString)
bool SetSources (tinyxml2::XMLNode *rootNode, const char *section, const std::vector< CMediaSource > &shares, const std::string &defaultPath) const
Private Attributes
std::vector< CMediaSource > m_programSources
std::vector< CMediaSource > m_pictureSources
std::vector< CMediaSource > m_fileSources
std::vector< CMediaSource > m_musicSources
std::vector< CMediaSource > m_videoSources
std::vector< CMediaSource > m_gameSources
std::string m_defaultProgramSource
std::string m_defaultMusicSource
std::string m_defaultPictureSource
std::string m_defaultFileSource
Constructor & Destructor Documentation
CMediaSourceSettings() [1/2]
CMediaSourceSettings::CMediaSourceSettings () protected
References Clear().
CMediaSourceSettings() [2/2]
CMediaSourceSettings::CMediaSourceSettings (const CMediaSourceSettings &) protected delete
~CMediaSourceSettings()
CMediaSourceSettings::~CMediaSourceSettings () override protected default
Member Function Documentation
AddShare()
bool CMediaSourceSettings::AddShare (const std::string & type, const CMediaSource & share)
References GetSources(), CLog::Log(), LOGDEBUG, LOGERROR, CMediaSource::m_ignore, Save(), CMediaSource::strPath, and CUtil::TranslateSpecialSource().
Referenced by CMediaManager::AddAutoSource(), CMediaManager::LoadAddonSources(), TestHTTPDirectory::SetupMediaSources(), TestWebServer::SetupMediaSources(), and CGUIDialogMediaSource::ShowAndAddMediaSource().
Clear()
void CMediaSourceSettings::Clear ()
References m_fileSources, m_gameSources, m_musicSources, m_pictureSources, m_programSources, and m_videoSources.
Referenced by CMediaSourceSettings(), Load(), OnSettingsUnloaded(), TestHTTPDirectory::TearDownMediaSources(), TestWebServer::TearDownMediaSources(), and TEST().
DeleteSource()
bool CMediaSourceSettings::DeleteSource (const std::string & strType, const std::string & strName, const std::string & strPath, bool virtualSource = false)
References GetSources(), CLog::Log(), LOGDEBUG, and Save().
Referenced by CGUIDialogContextMenu::OnContextButton(), CGUIDialogFileBrowser::OnPopupMenu(), and CMediaManager::RemoveAutoSource().
GetDefaultSource()
const std::string & CMediaSourceSettings::GetDefaultSource (const std::string & type) const
References m_defaultFileSource, m_defaultMusicSource, m_defaultPictureSource, and m_defaultProgramSource.
Referenced by CGUIDialogContextMenu::GetDefaultShareNameByType(), and CGUIWindowPrograms::OnMessage().
GetInstance()
CMediaSourceSettings & CMediaSourceSettings::GetInstance () static
Referenced by CMediaManager::AddAutoSource(), CGUIViewState::AddLiveTVSources(), CGUIViewStateWindowMusicNav::AddOnlineShares(), CGUIDialogVideoManagerExtras::AddVideoExtra(), CGUIDialogVideoManagerVersions::AddVideoVersionFilePicker(), CGUIDialogSubtitleSettings::BrowseForSubtitle(), XBMCAddon::xbmcgui::Dialog::browseMultiple(), XBMCAddon::xbmcgui::Dialog::browseSingle(), CGUIWindowFileManager::CalculateFolderSize(), CHTTPVfsHandler::CHTTPVfsHandler(), CVideoDatabase::CleanDatabase(), CVideoDatabase::CleanMediaType(), CGUIDialogContextMenu::GetDefaultShareNameByType(), XFILE::CSourcesDirectory::GetDirectory(), KODI::GAME::CGUIWindowGames::GetDirectory(), CGUIWindowMusicBase::GetDirectory(), CGUIWindowPictures::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), CVideoDatabase::GetEpisodesByName(), CVideoDatabase::GetEpisodesByPlot(), CVideoDatabase::GetEpisodesByWhere(), CVideoDatabase::GetMatchingMusicVideo(), CVideoDatabase::GetMovieActorsByName(), CVideoDatabase::GetMovieCountriesByName(), CVideoDatabase::GetMovieDirectorsByName(), CVideoDatabase::GetMovieGenresByName(), CVideoDatabase::GetMoviesByName(), CVideoDatabase::GetMoviesByPlot(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideoAlbumsByName(), CVideoDatabase::GetMusicVideoAlbumsNav(), CVideoDatabase::GetMusicVideoArtistsByName(), CVideoDatabase::GetMusicVideoDirectorsByName(), CVideoDatabase::GetMusicVideoGenresByName(), CVideoDatabase::GetMusicVideosByAlbum(), CVideoDatabase::GetMusicVideosByName(), CVideoDatabase::GetMusicVideosByWhere(), CVideoDatabase::GetNavCommon(), CGUIControlButtonSetting::GetPath(), CVideoDatabase::GetPeopleNav(), JSONRPC::CFileOperations::GetRootDirectory(), CVideoDatabase::GetSeasonsByWhere(), CGUIDialogContextMenu::GetShare(), KODI::GAME::CGUIViewStateWindowGames::GetSources(), CGUIViewStateWindowPictures::GetSources(), CGUIViewStateWindowPrograms::GetSources(), CVideoDatabase::GetTvShowGenresByName(), CVideoDatabase::GetTvShowsActorsByName(), CVideoDatabase::GetTvShowsByName(), CVideoDatabase::GetTvShowsByWhere(), CVideoDatabase::GetTvShowsDirectorsByName(), CGUIDialogMediaSource::GetUniqueMediaSourceName(), ADDON::Interface_GUIDialogFileBrowser::GetVECShares(), CVideoDatabase::GetYearsNav(), CSettings::InitializeISettingsHandlers(), CGUIWindowAddonBrowser::InstallFromZip(), CGUIPassword::IsItemUnlocked(), CGUIPassword::IsMediaFileUnlocked(), CGUIPassword::IsMediaPathUnlocked(), CMediaManager::LoadAddonSources(), CGUIPassword::LockSource(), CGUIPassword::LockSources(), CGUIDialogVideoInfo::ManageVideoItemArtwork(), CMusicDatabase::MigrateSources(), CGUIDialogFileBrowser::OnAddMediaSource(), CGUIDialogSmartPlaylistRule::OnBrowse(), CGUIWindowFileManager::OnClick(), CGUIDialogContextMenu::OnContextButton(), CGUIDialogFileBrowser::OnEditMediaSource(), CGUIDialogMusicInfo::OnGetArt(), CGUIDialogSongInfo::OnGetArt(), KODI::CDRIP::CCDDARipper::OnJobComplete(), KODI::GAME::CGUIWindowGames::OnMessage(), CGUIWindowPictures::OnMessage(), CGUIWindowPrograms::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIDialogFileBrowser::OnPopupMenu(), CGUIWindowFileManager::OnPopupMenu(), CGUIWindowVideoPlaylist::OnPrepareFileItems(), CWakeOnAccess::QueueMACDiscoveryForAllRemotes(), CFileUtils::RemoteAccessAllowed(), CMediaManager::RemoveAutoSource(), CGUIPassword::RemoveSourceLocks(), CGUIDialogContextMenu::SetDefault(), CGUIWindowFileManager::SetInitialPath(), TestHTTPDirectory::SetupMediaSources(), TestWebServer::SetupMediaSources(), CGUIDialogMediaSource::ShowAndAddMediaSource(), CGUIDialogMediaSource::ShowAndEditMediaSource(), CGUIDialogMediaSource::ShowAndEditMediaSource(), TestHTTPDirectory::TearDownMediaSources(), TestWebServer::TearDownMediaSources(), TEST(), TEST(), CSettings::UninitializeISettingsHandlers(), and CMusicDatabase::UpdateSources().
GetSource()
bool CMediaSourceSettings::GetSource (const std::string & category, const tinyxml2::XMLNode * source, CMediaSource & share) private
References URIUtils::AddSlashAtEnd(), CMediaSource::FromNameAndPaths(), XMLUtils::GetBoolean(), CURL::IsLocal(), CURL::IsProtocol(), URIUtils::IsStack(), LOCK_STATE_LOCKED, CLog::Log(), LOGERROR, CMediaSource::m_allowSharing, CMediaSource::m_iBadPwdCount, CMediaSource::m_iHasLock, CMediaSource::m_iLockMode, CMediaSource::m_strLockCode, CMediaSource::m_strThumbnailImage, name, and CUtil::TranslateSpecialSource().
Referenced by GetSources().
GetSources() [1/2]
std::vector< CMediaSource > * CMediaSourceSettings::GetSources (const std::string & type)
References m_fileSources, m_gameSources, m_musicSources, m_pictureSources, m_programSources, and m_videoSources.
Referenced by CGUIViewState::AddLiveTVSources(), CGUIViewStateWindowMusicNav::AddOnlineShares(), AddShare(), CGUIDialogVideoManagerExtras::AddVideoExtra(), CGUIDialogVideoManagerVersions::AddVideoVersionFilePicker(), XBMCAddon::xbmcgui::Dialog::browseMultiple(), XBMCAddon::xbmcgui::Dialog::browseSingle(), CHTTPVfsHandler::CHTTPVfsHandler(), DeleteSource(), CGUIDialogContextMenu::GetDefaultShareNameByType(), XFILE::CSourcesDirectory::GetDirectory(), KODI::GAME::CGUIWindowGames::GetDirectory(), CGUIWindowMusicBase::GetDirectory(), CGUIWindowPictures::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), CVideoDatabase::GetEpisodesByName(), CVideoDatabase::GetEpisodesByPlot(), CVideoDatabase::GetEpisodesByWhere(), CVideoDatabase::GetMatchingMusicVideo(), CVideoDatabase::GetMovieActorsByName(), CVideoDatabase::GetMovieCountriesByName(), CVideoDatabase::GetMovieDirectorsByName(), CVideoDatabase::GetMovieGenresByName(), CVideoDatabase::GetMoviesByName(), CVideoDatabase::GetMoviesByPlot(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideoAlbumsByName(), CVideoDatabase::GetMusicVideoAlbumsNav(), CVideoDatabase::GetMusicVideoArtistsByName(), CVideoDatabase::GetMusicVideoDirectorsByName(), CVideoDatabase::GetMusicVideoGenresByName(), CVideoDatabase::GetMusicVideosByAlbum(), CVideoDatabase::GetMusicVideosByName(), CVideoDatabase::GetMusicVideosByWhere(), CVideoDatabase::GetNavCommon(), CGUIControlButtonSetting::GetPath(), CVideoDatabase::GetPeopleNav(), JSONRPC::CFileOperations::GetRootDirectory(), CVideoDatabase::GetSeasonsByWhere(), CGUIDialogContextMenu::GetShare(), KODI::GAME::CGUIViewStateWindowGames::GetSources(), CGUIViewStateWindowPictures::GetSources(), CGUIViewStateWindowPrograms::GetSources(), CVideoDatabase::GetTvShowGenresByName(), CVideoDatabase::GetTvShowsActorsByName(), CVideoDatabase::GetTvShowsByName(), CVideoDatabase::GetTvShowsByWhere(), CVideoDatabase::GetTvShowsDirectorsByName(), CGUIDialogMediaSource::GetUniqueMediaSourceName(), ADDON::Interface_GUIDialogFileBrowser::GetVECShares(), CVideoDatabase::GetYearsNav(), CGUIWindowAddonBrowser::InstallFromZip(), CGUIPassword::IsMediaFileUnlocked(), CGUIPassword::IsMediaPathUnlocked(), Load(), CGUIPassword::LockSource(), CGUIPassword::LockSources(), CGUIDialogVideoInfo::ManageVideoItemArtwork(), CGUIDialogSmartPlaylistRule::OnBrowse(), KODI::CDRIP::CCDDARipper::OnJobComplete(), CGUIWindowVideoNav::OnMessage(), CGUIWindowVideoPlaylist::OnPrepareFileItems(), CWakeOnAccess::QueueMACDiscoveryForAllRemotes(), CFileUtils::RemoteAccessAllowed(), CGUIPassword::RemoveSourceLocks(), CGUIDialogMediaSource::ShowAndEditMediaSource(), TEST(), TEST(), UpdateShare(), and UpdateSource().
GetSources() [2/2]
void CMediaSourceSettings::GetSources (const tinyxml2::XMLNode * rootElement, const std::string & tagName, std::vector< CMediaSource > & items, std::string & defaultString) private
References GetSource(), CLog::Log(), LOGDEBUG, LOGERROR, text, value, and XML_SOURCE.
GetSourcesFile()
std::string CMediaSourceSettings::GetSourcesFile () static
References URIUtils::AddFileToFolder(), CServiceBroker::GetSettingsComponent(), and SOURCES_FILE.
Referenced by Load(), and Save().
Load() [1/2]
bool CMediaSourceSettings::Load ()
References GetSourcesFile(), and Load().
Referenced by Load(), OnSettingsLoaded(), TEST(), and TEST().
Load() [2/2]
bool CMediaSourceSettings::Load (const std::string & file)
References Clear(), CFileUtils::Exists(), GetSources(), CXBMCTinyXML2::LoadFile(), CLog::Log(), LOGERROR, LOGINFO, m_defaultFileSource, m_defaultMusicSource, m_defaultPictureSource, m_defaultProgramSource, m_fileSources, m_gameSources, m_musicSources, m_pictureSources, m_programSources, m_videoSources, and XML_SOURCES.
OnSettingsLoaded()
void CMediaSourceSettings::OnSettingsLoaded () override virtual
Settings have been loaded.
This callback can be used to trigger loading other settings.
Reimplemented from ISettingsHandler.
References Load().
OnSettingsUnloaded()
void CMediaSourceSettings::OnSettingsUnloaded () override virtual
Setting values have been unloaded.
This callback can be used to trigger uninitializing any state variables (e.g. before re-loading the settings).
Reimplemented from ISettingsHandler.
References Clear().
operator=()
CMediaSourceSettings & CMediaSourceSettings::operator= (CMediaSourceSettings const &) protected delete
Save() [1/2]
bool CMediaSourceSettings::Save ()
References GetSourcesFile(), and Save().
Referenced by AddShare(), DeleteSource(), CGUIPassword::IsItemUnlocked(), CGUIDialogContextMenu::OnContextButton(), CGUIPassword::RemoveSourceLocks(), Save(), CGUIDialogContextMenu::SetDefault(), TEST(), and UpdateShare().
Save() [2/2]
bool CMediaSourceSettings::Save (const std::string & file) const
References CWakeOnAccess::GetInstance(), m_defaultFileSource, m_defaultMusicSource, m_defaultPictureSource, m_defaultProgramSource, m_fileSources, m_gameSources, m_musicSources, m_pictureSources, m_programSources, m_videoSources, CWakeOnAccess::QueueMACDiscoveryForAllRemotes(), CXBMCTinyXML2::SaveFile(), SetSources(), and XML_SOURCES.
SetDefaultSource()
void CMediaSourceSettings::SetDefaultSource (const std::string & type, const std::string & source)
References m_defaultFileSource, m_defaultMusicSource, m_defaultPictureSource, and m_defaultProgramSource.
Referenced by CGUIDialogContextMenu::SetDefault().
SetSources()
bool CMediaSourceSettings::SetSources (tinyxml2::XMLNode * rootNode, const char * section, const std::vector< CMediaSource > & shares, const std::string & defaultPath) const private
References CMediaSource::m_allowSharing, CMediaSource::m_iBadPwdCount, CMediaSource::m_ignore, CMediaSource::m_iHasLock, CMediaSource::m_iLockMode, CMediaSource::m_strLockCode, CMediaSource::m_strThumbnailImage, root, XMLUtils::SetBoolean(), XMLUtils::SetInt(), XMLUtils::SetPath(), XMLUtils::SetString(), CMediaSource::strName, CMediaSource::vecPaths, and XML_SOURCE.
Referenced by Save().
UpdateShare()
bool CMediaSourceSettings::UpdateShare (const std::string & type, const std::string & oldName, const CMediaSource & share)
References GetSources(), Save(), CMediaSource::strName, CMediaSource::strPath, and CMediaSource::vecPaths.
Referenced by CGUIDialogMediaSource::ShowAndEditMediaSource().
UpdateSource()
bool CMediaSourceSettings::UpdateSource (const std::string & strType, const std::string & strOldName, const std::string & strUpdateChild, const std::string & strUpdateValue)
References GetSources().
Referenced by CGUIPassword::IsItemUnlocked(), CGUIDialogContextMenu::OnContextButton(), and CGUIPassword::RemoveSourceLocks().
Member Data Documentation
m_defaultFileSource
std::string CMediaSourceSettings::m_defaultFileSource private
Referenced by GetDefaultSource(), Load(), Save(), and SetDefaultSource().
m_defaultMusicSource
std::string CMediaSourceSettings::m_defaultMusicSource private
Referenced by GetDefaultSource(), Load(), Save(), and SetDefaultSource().
m_defaultPictureSource
std::string CMediaSourceSettings::m_defaultPictureSource private
Referenced by GetDefaultSource(), Load(), Save(), and SetDefaultSource().
m_defaultProgramSource
std::string CMediaSourceSettings::m_defaultProgramSource private
Referenced by GetDefaultSource(), Load(), Save(), and SetDefaultSource().
m_fileSources
std::vector<CMediaSource> CMediaSourceSettings::m_fileSources private
Referenced by Clear(), GetSources(), Load(), and Save().
m_gameSources
std::vector<CMediaSource> CMediaSourceSettings::m_gameSources private
Referenced by Clear(), GetSources(), Load(), and Save().
m_musicSources
std::vector<CMediaSource> CMediaSourceSettings::m_musicSources private
Referenced by Clear(), GetSources(), Load(), and Save().
m_pictureSources
std::vector<CMediaSource> CMediaSourceSettings::m_pictureSources private
Referenced by Clear(), GetSources(), Load(), and Save().
m_programSources
std::vector<CMediaSource> CMediaSourceSettings::m_programSources private
Referenced by Clear(), GetSources(), Load(), and Save().
m_videoSources
std::vector<CMediaSource> CMediaSourceSettings::m_videoSources private
Referenced by Clear(), GetSources(), Load(), and Save().
The documentation for this class was generated from the following files:
MediaSourceSettings.h
MediaSourceSettings.cpp