Kodi Documentation: FAVOURITES_UTILS Namespace Reference
FAVOURITES_UTILS Namespace Reference
Namespaces
namespace anonymous_namespace{FavouritesUtils.cpp}
Functions
bool ChooseAndSetNewName (CFileItem &item)
bool ChooseAndSetNewThumbnail (CFileItem &item)
bool MoveItem (CFileItemList &items, const std::shared_ptr< CFileItem > &item, int amount)
bool RemoveItem (CFileItemList &items, const std::shared_ptr< CFileItem > &item)
bool ShouldEnableMoveItems ()
bool ExecuteAction (const CExecString &execString)
bool ExecuteAction (const CFavouritesURL &favURL)
Function Documentation
ChooseAndSetNewName()
bool FAVOURITES_UTILS::ChooseAndSetNewName (CFileItem & item)
References g_localizeStrings, CLocalizeStrings::Get(), CGUIListItem::GetLabel(), label, CFileItem::SetLabel(), and CGUIKeyboardFactory::ShowAndGetInput().
Referenced by CONTEXTMENU::CRenameFavourite::DoExecute().
ChooseAndSetNewThumbnail()
bool FAVOURITES_UTILS::ChooseAndSetNewThumbnail (CFileItem & item)
References CFileItemList::Add(), g_localizeStrings, CLocalizeStrings::Get(), CGUIListItem::GetArt(), CMediaManager::GetLocalDrives(), CServiceBroker::GetMediaManager(), CGUIListItem::HasArt(), none, CGUIListItem::SetArt(), and CGUIDialogFileBrowser::ShowAndGetImage().
Referenced by CONTEXTMENU::CChooseThumbnailForFavourite::DoExecute().
ExecuteAction() [1/2]
bool FAVOURITES_UTILS::ExecuteAction (const CExecString & execString)
References ExecuteAction(), and CExecString::GetExecString().
Referenced by CONTEXTMENU::CFavouritesTargetBrowse::Execute(), CONTEXTMENU::CFavouritesTargetResume::Execute(), CONTEXTMENU::CFavouritesTargetPlay::Execute(), ExecuteAction(), ExecuteAction(), CGUIWindowFavourites::OnAction(), anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor::OnPlayPartSelected(), anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor::OnPlaySelected(), anonymous_namespace{GUIWindowFavourites.cpp}::CVideoPlayActionProcessor::OnPlaySelected(), anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor::OnQueueSelected(), anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor::OnResumeSelected(), anonymous_namespace{GUIWindowFavourites.cpp}::CVideoPlayActionProcessor::OnResumeSelected(), and CGUIWindowFavourites::OnSelect().
ExecuteAction() [2/2]
bool FAVOURITES_UTILS::ExecuteAction (const CFavouritesURL & favURL)
References ExecuteAction(), CFavouritesURL::GetExecString(), and CFavouritesURL::IsValid().
MoveItem()
bool FAVOURITES_UTILS::MoveItem (CFileItemList & items, const std::shared_ptr< CFileItem > & item, int amount)
References CFileItemList::Add(), CFileItemList::AddFront(), CFileItemList::Remove(), CFileItemList::Size(), and CFileItemList::Swap().
Referenced by CONTEXTMENU::CMoveUpFavourite::DoExecute(), CONTEXTMENU::CMoveDownFavourite::DoExecute(), and CGUIWindowFavourites::MoveItem().
RemoveItem()
bool FAVOURITES_UTILS::RemoveItem (CFileItemList & items, const std::shared_ptr< CFileItem > & item)
References CFileItemList::Remove(), and CFileItemList::Size().
Referenced by CONTEXTMENU::CRemoveFavourite::DoExecute(), and CGUIWindowFavourites::RemoveItem().
ShouldEnableMoveItems()
bool FAVOURITES_UTILS::ShouldEnableMoveItems ()
References CServiceBroker::GetFavouritesService(), CServiceBroker::GetGUI(), CGUIViewState::GetSortMethod(), CGUIMediaWindow::GetViewState(), CGUIComponent::GetWindowManager(), CGUIWindow::IsActive(), SortDescription::sortBy, SortByUserPreference, and WINDOW_FAVOURITES.
Referenced by CONTEXTMENU::CMoveUpFavourite::IsVisible(), CONTEXTMENU::CMoveDownFavourite::IsVisible(), and CGUIWindowFavourites::OnAction().