Kodi Documentation: PVR::CPVREpg Class Reference
PVR::CPVREpg Class Reference
#include <Epg.h>
Public Member Functions
CPVREpg (int iEpgID, const std::string &strName, const std::string &strScraperName, const std::shared_ptr< CPVREpgDatabase > &database)
Create a new EPG instance.
CPVREpg (int iEpgID, const std::string &strName, const std::string &strScraperName, const std::shared_ptr< CPVREpgChannelData > &channelData, const std::shared_ptr< CPVREpgDatabase > &database)
Create a new EPG instance.
virtual ~CPVREpg ()
Destroy this EPG instance.
std::shared_ptr< CPVREpgChannelData > GetChannelData () const
Get data for the channel associated with this EPG.
void SetChannelData (const std::shared_ptr< CPVREpgChannelData > &data)
Set data for the channel associated with this EPG.
int ChannelID () const
The id of the channel associated with this EPG.
const std::string & ScraperName () const
Get the name of the scraper to use for this table.
bool UpdatePending () const
Returns if there is a manual update pending for this EPG.
void ForceUpdate ()
Clear the current tags and schedule manual update.
const std::string & Name () const
Get the name of this table.
int EpgID () const
Get the database ID of this table.
void Cleanup (const CDateTime &time)
Remove all entries from this EPG that finished before the given time.
void Clear ()
Remove all entries from this EPG.
std::shared_ptr< CPVREpgInfoTag > GetTagNow () const
Get the event that is occurring now.
std::shared_ptr< CPVREpgInfoTag > GetTagNext () const
Get the event that will occur next.
std::shared_ptr< CPVREpgInfoTag > GetTagPrevious () const
Get the event that occurred previously.
std::shared_ptr< CPVREpgInfoTag > GetTagBetween (const CDateTime &beginTime, const CDateTime &endTime, bool bUpdateFromClient=false)
Get the event that occurs between the given begin and end time.
std::shared_ptr< CPVREpgInfoTag > GetTagByBroadcastId (unsigned int iUniqueBroadcastId) const
Get the event matching the given unique broadcast id.
std::shared_ptr< CPVREpgInfoTag > GetTagByDatabaseId (int iDatabaseId) const
Get the event matching the given database id.
bool UpdateEntry (const EPG_TAG *data, int iClientId)
Update an entry in this EPG.
bool UpdateEntry (const std::shared_ptr< CPVREpgInfoTag > &tag, EPG_EVENT_STATE newState)
Update an entry in this EPG.
bool Update (time_t start, time_t end, int iUpdateTime, int iPastDays, const std::shared_ptr< CPVREpgDatabase > &database, bool bForceUpdate=false)
Update the EPG from 'start' till 'end'.
std::vector< std::shared_ptr< CPVREpgInfoTag > > GetTags () const
Get all EPG tags.
std::vector< std::shared_ptr< CPVREpgInfoTag > > GetTimeline (const CDateTime &timelineStart, const CDateTime &timelineEnd, const CDateTime &minEventEnd, const CDateTime &maxEventStart) const
Get all EPG tags for the given time frame, including "gap" tags.
bool QueuePersistQuery (const std::shared_ptr< CPVREpgDatabase > &database)
Write the query to persist data into given database's queue.
bool QueueDeleteQueries (const std::shared_ptr< CPVREpgDatabase > &database)
Write the delete queries into the given database's queue.
std::pair< CDateTime, CDateTime > GetFirstAndLastUncommitedEPGDate () const
Get the start and end time of the last not yet commited entry in this table.
bool CheckPlayingEvent ()
Notify observers when the currently active tag changed.
bool NeedsSave () const
Check whether this EPG has unsaved data.
bool IsValid () const
Check whether this EPG is valid.
CEventStream< PVREvent > & Events ()
Query the events available for CEventStream.
void Lock ()
Lock the instance. No other thread gets access to this EPG until Unlock was called.
void Unlock ()
Unlock the instance. Other threads may get access to this EPG again.
void RemovedFromContainer ()
Called to inform the EPG that it has been removed from the EPG container.
int CleanupCachedImages (const std::shared_ptr< const CPVREpgDatabase > &database)
Erase stale texture db entries and image files.
Static Public Member Functions
static const std::string & ConvertGenreIdToString (int iID, int iSubID)
Convert a genre id and subid to a human readable name.
Private Member Functions
CPVREpg ()=delete
CPVREpg (const CPVREpg &)=delete
CPVREpg & operator= (const CPVREpg &)=delete
bool UpdateFromScraper (time_t start, time_t end, bool bForceUpdate)
Update the EPG from a scraper set in the channel tag.
bool UpdateEntries (const CPVREpg &epg)
Update the contents of this table with the contents provided in "epg".
void Cleanup (int iPastDays)
Remove all entries from this EPG that finished before the given amount of days.
Private Attributes
bool m_bChanged = false
std::atomic< bool > m_bUpdatePending = {false}
int m_iEpgID = 0
std::string m_strName
std::string m_strScraperName
CDateTime m_lastScanTime
CCriticalSection m_critSection
bool m_bUpdateLastScanTime = false
std::shared_ptr< CPVREpgChannelData > m_channelData
CPVREpgTagsContainer m_tags
CEventSource< PVREvent > m_events
Friends
class CPVREpgDatabase
Constructor & Destructor Documentation
CPVREpg() [1/4]
CPVREpg::CPVREpg (int iEpgID, const std::string & strName, const std::string & strScraperName, const std::shared_ptr< CPVREpgDatabase > & database)
Create a new EPG instance.
Parameters
iEpgID The ID of this table or <= 0 to create a new ID.
strName The name of this table.
strScraperName The name of the scraper to use.
database The EPG database
CPVREpg() [2/4]
CPVREpg::CPVREpg (int iEpgID, const std::string & strName, const std::string & strScraperName, const std::shared_ptr< CPVREpgChannelData > & channelData, const std::shared_ptr< CPVREpgDatabase > & database)
Create a new EPG instance.
Parameters
iEpgID The ID of this table or <= 0 to create a new ID.
strName The name of this table.
strScraperName The name of the scraper to use.
channelData The channel data.
database The EPG database
~CPVREpg()
CPVREpg::~CPVREpg () virtual
Destroy this EPG instance.
References Clear().
CPVREpg() [3/4]
PVR::CPVREpg::CPVREpg () private delete
CPVREpg() [4/4]
PVR::CPVREpg::CPVREpg (const CPVREpg &) private delete
Member Function Documentation
ChannelID()
int CPVREpg::ChannelID () const
The id of the channel associated with this EPG.
Returns
The channel id or -1 if no channel is associated
References m_channelData, and m_critSection.
CheckPlayingEvent()
bool CPVREpg::CheckPlayingEvent ()
Notify observers when the currently active tag changed.
Returns
True if the playing tag has changed, false otherwise.
References PVR::EpgActiveItem, m_critSection, m_events, m_tags, CEventSource< Event >::Publish(), and PVR::CPVREpgTagsContainer::UpdateActiveTag().
Cleanup() [1/2]
void CPVREpg::Cleanup (const CDateTime & time)
Remove all entries from this EPG that finished before the given time.
Parameters
time Delete entries with an end time before this time in UTC.
References PVR::CPVREpgTagsContainer::Cleanup(), m_critSection, and m_tags.
Referenced by Cleanup(), and Update().
Cleanup() [2/2]
void CPVREpg::Cleanup (int iPastDays) private
Remove all entries from this EPG that finished before the given amount of days.
Parameters
iPastDays Delete entries with an end time before the given amount of days from now on.
References Cleanup(), and CDateTime::GetUTCDateTime().
CleanupCachedImages()
int CPVREpg::CleanupCachedImages (const std::shared_ptr< const CPVREpgDatabase > & database)
Erase stale texture db entries and image files.
Parameters
database The EPG database
Returns
number of cleaned up images.
References PVR::CPVRCachedImages::Cleanup(), EpgID(), PVR::CPVREpgInfoTag::IMAGE_OWNER_PATTERN, and owner.
Clear()
void CPVREpg::Clear ()
Remove all entries from this EPG.
References PVR::CPVREpgTagsContainer::Clear(), m_critSection, and m_tags.
Referenced by QueueDeleteQueries(), and ~CPVREpg().
ConvertGenreIdToString()
const std::string & CPVREpg::ConvertGenreIdToString (int iID, int iSubID) static
Convert a genre id and subid to a human readable name.
Parameters
iID The genre ID.
iSubID The genre sub ID.
Returns
A human readable name.
References EPG_EVENT_CONTENTMASK_ARTSCULTURE, EPG_EVENT_CONTENTMASK_CHILDRENYOUTH, EPG_EVENT_CONTENTMASK_EDUCATIONALSCIENCE, EPG_EVENT_CONTENTMASK_LEISUREHOBBIES, EPG_EVENT_CONTENTMASK_MOVIEDRAMA, EPG_EVENT_CONTENTMASK_MUSICBALLETDANCE, EPG_EVENT_CONTENTMASK_NEWSCURRENTAFFAIRS, EPG_EVENT_CONTENTMASK_SHOW, EPG_EVENT_CONTENTMASK_SOCIALPOLITICALECONOMICS, EPG_EVENT_CONTENTMASK_SPECIAL, EPG_EVENT_CONTENTMASK_SPORTS, EPG_EVENT_CONTENTMASK_USERDEFINED, g_localizeStrings, and CLocalizeStrings::Get().
Referenced by PVR::CPVREpgInfoTag::Genre(), PVR::CPVRRecording::SetGenre(), and PVR::CPVRRecording::Update().
EpgID()
int CPVREpg::EpgID () const
Get the database ID of this table.
Returns
The database ID of this table.
References m_critSection, and m_iEpgID.
Referenced by CleanupCachedImages(), and PVR::CPVREpgDatabase::Persist().
Events()
CEventStream< PVREvent > & PVR::CPVREpg::Events () inline
Query the events available for CEventStream.
References m_events.
ForceUpdate()
void CPVREpg::ForceUpdate ()
Clear the current tags and schedule manual update.
References PVR::EpgUpdatePending, m_bUpdatePending, m_events, and CEventSource< Event >::Publish().
GetChannelData()
std::shared_ptr< CPVREpgChannelData > CPVREpg::GetChannelData () const
Get data for the channel associated with this EPG.
Returns
The data.
References m_channelData, and m_critSection.
GetFirstAndLastUncommitedEPGDate()
std::pair< CDateTime, CDateTime > CPVREpg::GetFirstAndLastUncommitedEPGDate () const
Get the start and end time of the last not yet commited entry in this table.
Returns
The times; first: start time, second: end time.
References PVR::CPVREpgTagsContainer::GetFirstAndLastUncommitedEPGDate(), m_critSection, and m_tags.
GetTagBetween()
std::shared_ptr< CPVREpgInfoTag > CPVREpg::GetTagBetween (const CDateTime & beginTime, const CDateTime & endTime, bool bUpdateFromClient = false)
Get the event that occurs between the given begin and end time.
Parameters
beginTime Minimum start time in UTC of the event.
endTime Maximum end time in UTC of the event.
bUpdateFromClient if true, try to fetch the event from the client if not found locally.
Returns
The found tag or NULL if it wasn't found.
References CDateTime::GetAsTime(), PVR::CPVREpgTagsContainer::GetTagBetween(), m_channelData, m_critSection, m_iEpgID, m_strName, m_strScraperName, m_tags, and PVR::CPVREpgTagsContainer::UpdateEntry().
GetTagByBroadcastId()
std::shared_ptr< CPVREpgInfoTag > CPVREpg::GetTagByBroadcastId (unsigned int iUniqueBroadcastId) const
Get the event matching the given unique broadcast id.
Parameters
iUniqueBroadcastId The uid to look up
Returns
The matching event or NULL if it wasn't found.
References PVR::CPVREpgTagsContainer::GetTag(), m_critSection, and m_tags.
GetTagByDatabaseId()
std::shared_ptr< CPVREpgInfoTag > CPVREpg::GetTagByDatabaseId (int iDatabaseId) const
Get the event matching the given database id.
Parameters
iDatabaseId The id to look up
Returns
The matching event or NULL if it wasn't found.
References PVR::CPVREpgTagsContainer::GetTagByDatabaseID(), m_critSection, and m_tags.
GetTagNext()
std::shared_ptr< CPVREpgInfoTag > CPVREpg::GetTagNext () const
Get the event that will occur next.
Returns
The next event or NULL if it wasn't found.
References PVR::CPVREpgTagsContainer::GetNextStartingTag(), m_critSection, and m_tags.
GetTagNow()
std::shared_ptr< CPVREpgInfoTag > CPVREpg::GetTagNow () const
Get the event that is occurring now.
Returns
The current event or NULL if it wasn't found.
References PVR::CPVREpgTagsContainer::GetActiveTag(), m_critSection, and m_tags.
GetTagPrevious()
std::shared_ptr< CPVREpgInfoTag > CPVREpg::GetTagPrevious () const
Get the event that occurred previously.
Returns
The previous event or NULL if it wasn't found.
References PVR::CPVREpgTagsContainer::GetLastEndedTag(), m_critSection, and m_tags.
GetTags()
std::vector< std::shared_ptr< CPVREpgInfoTag > > CPVREpg::GetTags () const
Get all EPG tags.
Returns
The tags.
References PVR::CPVREpgTagsContainer::GetAllTags(), m_critSection, and m_tags.
GetTimeline()
std::vector< std::shared_ptr< CPVREpgInfoTag > > CPVREpg::GetTimeline (const CDateTime & timelineStart, const CDateTime & timelineEnd, const CDateTime & minEventEnd, const CDateTime & maxEventStart) const
Get all EPG tags for the given time frame, including "gap" tags.
Parameters
timelineStart Start of time line
timelineEnd End of time line
minEventEnd The minimum end time of the events to return
maxEventStart The maximum start time of the events to return
Returns
The matching tags.
References PVR::CPVREpgTagsContainer::GetTimeline(), m_critSection, and m_tags.
IsValid()
bool CPVREpg::IsValid () const
Check whether this EPG is valid.
Returns
True if this EPG is valid and can be updated, false otherwise.
References m_channelData, m_critSection, PVR_CHANNEL_INVALID_UID, PVR::PVR_CLIENT_INVALID_UID, and ScraperName().
Lock()
void PVR::CPVREpg::Lock () inline
Lock the instance. No other thread gets access to this EPG until Unlock was called.
References m_critSection.
Name()
const std::string & CPVREpg::Name () const
Get the name of this table.
Returns
The name of this table.
References m_critSection, and m_strName.
Referenced by PVR::CPVREpgDatabase::Persist(), and Update().
NeedsSave()
bool CPVREpg::NeedsSave () const
Check whether this EPG has unsaved data.
Returns
True if this EPG contains unsaved data, false otherwise.
References m_bChanged, m_bUpdateLastScanTime, m_critSection, m_tags, and PVR::CPVREpgTagsContainer::NeedsSave().
operator=()
CPVREpg & PVR::CPVREpg::operator= (const CPVREpg &) private delete
QueueDeleteQueries()
bool CPVREpg::QueueDeleteQueries (const std::shared_ptr< CPVREpgDatabase > & database)
Write the delete queries into the given database's queue.
Parameters
database The database.
Returns
True on success, false otherwise.
References Clear(), LOGERROR, m_critSection, m_tags, and PVR::CPVREpgTagsContainer::QueueDelete().
QueuePersistQuery()
bool CPVREpg::QueuePersistQuery (const std::shared_ptr< CPVREpgDatabase > & database)
Write the query to persist data into given database's queue.
Parameters
database The database.
Returns
True on success, false otherwise.
References LOGERROR, m_bChanged, m_bUpdateLastScanTime, m_iEpgID, m_lastScanTime, m_tags, PVR::CPVREpgTagsContainer::NeedsSave(), PVR::CPVREpgTagsContainer::QueuePersistQuery(), and PVR::CPVREpgTagsContainer::SetEpgID().
RemovedFromContainer()
void CPVREpg::RemovedFromContainer ()
Called to inform the EPG that it has been removed from the EPG container.
References PVR::EpgDeleted, m_events, and CEventSource< Event >::Publish().
ScraperName()
const std::string & CPVREpg::ScraperName () const
Get the name of the scraper to use for this table.
Returns
The name of the scraper to use for this table.
References m_critSection, and m_strScraperName.
Referenced by IsValid(), and PVR::CPVREpgDatabase::Persist().
SetChannelData()
void CPVREpg::SetChannelData (const std::shared_ptr< CPVREpgChannelData > & data)
Set data for the channel associated with this EPG.
Parameters
data The data.
References data(), m_channelData, m_critSection, m_tags, and PVR::CPVREpgTagsContainer::SetChannelData().
Unlock()
void PVR::CPVREpg::Unlock () inline
Unlock the instance. Other threads may get access to this EPG again.
References m_critSection.
Update()
bool CPVREpg::Update (time_t start, time_t end, int iUpdateTime, int iPastDays, const std::shared_ptr< CPVREpgDatabase > & database, bool bForceUpdate = false)
Update the EPG from 'start' till 'end'.
Parameters
start The start time.
end The end time.
iUpdateTime Update the table after the given amount of time has passed.
iPastDays Amount of past days from now on, for which past entries are to be kept.
database If given, the database to store the data.
bForceUpdate Force update from client even if it's not the time to
Returns
True if the update was successful, false otherwise.
Todo:
why the channelid check?
References Cleanup(), end(), CDateTime::GetAsTime(), CServiceBroker::GetSettingsComponent(), CDateTime::GetUTCDateTime(), PVR::CPVREpgTagsContainer::IsEmpty(), CDateTime::IsValid(), LOGERROR, m_bUpdateLastScanTime, m_bUpdatePending, m_channelData, m_critSection, m_iEpgID, m_lastScanTime, m_strName, m_strScraperName, m_tags, Name(), CDateTime::SetFromUTCDateTime(), and UpdateEntries().
UpdateEntries()
bool CPVREpg::UpdateEntries (const CPVREpg & epg) private
Update the contents of this table with the contents provided in "epg".
Parameters
epg The updated contents.
Returns
True if the update was successful, false otherwise.
References PVR::Epg, CDateTime::GetUTCDateTime(), m_bUpdateLastScanTime, m_critSection, m_events, m_lastScanTime, m_tags, CEventSource< Event >::Publish(), and PVR::CPVREpgTagsContainer::UpdateEntries().
Referenced by Update().
UpdateEntry() [1/2]
bool CPVREpg::UpdateEntry (const EPG_TAG * data, int iClientId)
Update an entry in this EPG.
Parameters
data The tag to update.
iClientId The id of the pvr client this event belongs to.
Returns
True if it was updated successfully, false otherwise.
References data(), m_channelData, m_iEpgID, m_tags, and PVR::CPVREpgTagsContainer::UpdateEntry().
Referenced by PVR::CPVRClient::cb_transfer_epg_entry().
UpdateEntry() [2/2]
bool CPVREpg::UpdateEntry (const std::shared_ptr< CPVREpgInfoTag > & tag, EPG_EVENT_STATE newState)
Update an entry in this EPG.
Parameters
tag The tag to update.
newState the new state of the event.
Returns
True if it was updated successfully, false otherwise.
References PVR::CPVREpgTagsContainer::DeleteEntry(), EPG_EVENT_CREATED, EPG_EVENT_DELETED, EPG_EVENT_UPDATED, PVR::EpgItemUpdate, PVR::CPVREpgTagsContainer::GetTag(), CDateTime::GetUTCDateTime(), LOGERROR, m_critSection, m_events, m_tags, CEventSource< Event >::Publish(), and PVR::CPVREpgTagsContainer::UpdateEntry().
UpdateFromScraper()
bool CPVREpg::UpdateFromScraper (time_t start, time_t end, bool bForceUpdate) private
Update the EPG from a scraper set in the channel tag.
Todo:
not implemented yet for non-pvr EPGs
Parameters
start Get entries with a start date after this time.
end Get entries with an end date before this time.
bForceUpdate Force update from client even if it's not the time to
Returns
True if the update was successful, false otherwise.
Todo:
Add Support for Web EPG Scrapers here
References end(), PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), LOGDEBUG, LOGEPG, LOGERROR, m_channelData, m_strName, m_strScraperName, and PVR_ERROR_NO_ERROR.
UpdatePending()
bool CPVREpg::UpdatePending () const
Returns if there is a manual update pending for this EPG.
Returns
True if there is a manual update pending, false otherwise
References m_bUpdatePending.
Friends And Related Symbol Documentation
CPVREpgDatabase
friend class CPVREpgDatabase friend
Member Data Documentation
m_bChanged
bool PVR::CPVREpg::m_bChanged = false private
true if anything changed that needs to be persisted, false otherwise
Referenced by NeedsSave(), and QueuePersistQuery().
m_bUpdateLastScanTime
bool PVR::CPVREpg::m_bUpdateLastScanTime = false private
Referenced by NeedsSave(), QueuePersistQuery(), Update(), and UpdateEntries().
m_bUpdatePending
std::atomic<bool> PVR::CPVREpg::m_bUpdatePending = {false} private
true if manual update is pending
Referenced by ForceUpdate(), Update(), and UpdatePending().
m_channelData
std::shared_ptr<CPVREpgChannelData> PVR::CPVREpg::m_channelData private
Referenced by ChannelID(), GetChannelData(), GetTagBetween(), IsValid(), SetChannelData(), Update(), UpdateEntry(), and UpdateFromScraper().
m_critSection
CCriticalSection PVR::CPVREpg::m_critSection mutable private
critical section for changes in this table
Referenced by ChannelID(), CheckPlayingEvent(), Cleanup(), Clear(), EpgID(), GetChannelData(), GetFirstAndLastUncommitedEPGDate(), GetTagBetween(), GetTagByBroadcastId(), GetTagByDatabaseId(), GetTagNext(), GetTagNow(), GetTagPrevious(), GetTags(), GetTimeline(), IsValid(), Lock(), Name(), NeedsSave(), QueueDeleteQueries(), ScraperName(), SetChannelData(), Unlock(), Update(), UpdateEntries(), and UpdateEntry().
m_events
CEventSource<PVREvent> PVR::CPVREpg::m_events private
Referenced by CheckPlayingEvent(), Events(), ForceUpdate(), RemovedFromContainer(), UpdateEntries(), and UpdateEntry().
m_iEpgID
int PVR::CPVREpg::m_iEpgID = 0 private
the database ID of this table
Referenced by EpgID(), GetTagBetween(), QueuePersistQuery(), Update(), and UpdateEntry().
m_lastScanTime
CDateTime PVR::CPVREpg::m_lastScanTime private
the last time the EPG has been updated
Referenced by QueuePersistQuery(), Update(), and UpdateEntries().
m_strName
std::string PVR::CPVREpg::m_strName private
the name of this table
Referenced by GetTagBetween(), Name(), Update(), and UpdateFromScraper().
m_strScraperName
std::string PVR::CPVREpg::m_strScraperName private
the name of the scraper to use
Referenced by GetTagBetween(), ScraperName(), Update(), and UpdateFromScraper().
m_tags
CPVREpgTagsContainer PVR::CPVREpg::m_tags private
Referenced by CheckPlayingEvent(), Cleanup(), Clear(), GetFirstAndLastUncommitedEPGDate(), GetTagBetween(), GetTagByBroadcastId(), GetTagByDatabaseId(), GetTagNext(), GetTagNow(), GetTagPrevious(), GetTags(), GetTimeline(), NeedsSave(), QueueDeleteQueries(), QueuePersistQuery(), SetChannelData(), Update(), UpdateEntries(), UpdateEntry(), and UpdateEntry().
The documentation for this class was generated from the following files:
pvr/epg/Epg.h
Epg.cpp