Kodi Documentation: CWinEventsTVOS Class Reference
CWinEventsTVOS Class Reference
#include <WinEventsTVOS.h>
Public Member Functions
CWinEventsTVOS ()
~CWinEventsTVOS ()
void MessagePush (XBMC_Event *newEvent)
size_t GetQueueSize ()
bool MessagePump ()
Public Member Functions inherited from IWinEvents
virtual ~IWinEvents ()=default
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Private Attributes
CCriticalSection m_eventsCond
std::list< XBMC_Event > m_events
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
virtual void Process ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CWinEventsTVOS()
CWinEventsTVOS::CWinEventsTVOS ()
References CThread::Create(), CLog::Log(), and LOGDEBUG.
~CWinEventsTVOS()
CWinEventsTVOS::~CWinEventsTVOS ()
References CThread::m_bStop, and CThread::StopThread().
Member Function Documentation
GetQueueSize()
size_t CWinEventsTVOS::GetQueueSize ()
References events, and g_inputCond.
Referenced by CWinSystemTVOS::GetQueueSize(), and MessagePump().
MessagePump()
bool CWinEventsTVOS::MessagePump () virtual
Implements IWinEvents.
References events, g_inputCond, CServiceBroker::GetAppPort(), and GetQueueSize().
MessagePush()
void CWinEventsTVOS::MessagePush (XBMC_Event * newEvent)
References m_events, and m_eventsCond.
Referenced by CWinSystemTVOS::MessagePush().
Member Data Documentation
m_events
std::list<XBMC_Event> CWinEventsTVOS::m_events private
Referenced by MessagePush().
m_eventsCond
CCriticalSection CWinEventsTVOS::m_eventsCond private
Referenced by MessagePush().
The documentation for this class was generated from the following files:
WinEventsTVOS.h
WinEventsTVOS.mm