Kodi Documentation: WSDiscovery::IWSDiscovery Class Reference
WSDiscovery::IWSDiscovery Class Reference abstract
#include <IWSDiscovery.h>
Public Member Functions
virtual ~IWSDiscovery ()=default
virtual bool StartServices ()=0
virtual bool StopServices ()=0
virtual bool IsRunning ()=0
Static Public Member Functions
static std::unique_ptr< IWSDiscovery > GetInstance ()
Constructor & Destructor Documentation
~IWSDiscovery()
virtual WSDiscovery::IWSDiscovery::~IWSDiscovery () virtual default
Member Function Documentation
GetInstance()
std::unique_ptr< IWSDiscovery > WSDiscovery::IWSDiscovery::GetInstance () static
Referenced by CServiceManager::InitStageTwo().
IsRunning()
virtual bool WSDiscovery::IWSDiscovery::IsRunning () pure virtual
Implemented in WSDiscovery::CWSDiscoveryPosix, and WSDiscovery::CWSDiscoveryWindows.
Referenced by CNetworkServices::IsWSDiscoveryRunning().
StartServices()
virtual bool WSDiscovery::IWSDiscovery::StartServices () pure virtual
Implemented in WSDiscovery::CWSDiscoveryPosix, and WSDiscovery::CWSDiscoveryWindows.
Referenced by CNetworkServices::StartWSDiscovery().
StopServices()
virtual bool WSDiscovery::IWSDiscovery::StopServices () pure virtual
Implemented in WSDiscovery::CWSDiscoveryPosix, and WSDiscovery::CWSDiscoveryWindows.
Referenced by CNetworkServices::StopWSDiscovery().
The documentation for this class was generated from the following files:
IWSDiscovery.h
SMBWSDiscovery.cpp
WSDiscoveryWin32.cpp