Kodi Documentation: XBTFReader.cpp File Reference
XBTFReader.cpp File Reference
#include <inttypes.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include "XBTFReader.h"
#include "guilib/XBTF.h"
#include "utils/EndianSwap.h"
Functions
static bool ReadString (FILE *file, char *str, size_t max_length)
static bool ReadChar (FILE *file, char &value)
static bool ReadUInt32 (FILE *file, uint32_t &value)
static bool ReadUInt64 (FILE *file, uint64_t &value)
Function Documentation
ReadChar()
static bool ReadChar (FILE * file, char & value) static
References value.
Referenced by CXBTFReader::Open().
ReadString()
static bool ReadString (FILE * file, char * str, size_t max_length) static
Referenced by CXBTFReader::Open(), and ADDON::Interface_Filesystem::read_file_string().
ReadUInt32()
static bool ReadUInt32 (FILE * file, uint32_t & value) static
References Endian_SwapLE32, and value.
Referenced by CXBTFReader::Open().
ReadUInt64()
static bool ReadUInt64 (FILE * file, uint64_t & value) static
References Endian_SwapLE64, and value.
Referenced by CXBTFReader::Open().