Kodi Documentation: kodi::addon::PVRTypeStringValue Class Reference
kodi::addon::PVRTypeStringValue Class Reference
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 1. General » class PVRTypeStringValue
#include <General.h>
Public Member Functions
PVRTypeStringValue ()=default
Default class constructor.
PVRTypeStringValue (const std::string &value, const std::string &description)
Class constructor with integrated value set.
void SetValue (const std::string &value)
To set with the identification value.
std::string GetValue () const
To get with the identification value.
void SetDescription (const std::string &description)
To set with the description text of the value.
std::string GetDescription () const
To get with the description text of the value.
Public Member Functions inherited from kodi::addon::DynamicCStructHdl< PVRTypeStringValue, PVR_ATTRIBUTE_STRING_VALUE >
DynamicCStructHdl ()
DynamicCStructHdl (const DynamicCStructHdl &cppClass)
DynamicCStructHdl (const PVR_ATTRIBUTE_STRING_VALUE *cStructure)
DynamicCStructHdl (PVR_ATTRIBUTE_STRING_VALUE *cStructure)
const DynamicCStructHdl & operator= (const DynamicCStructHdl &right)
const DynamicCStructHdl & operator= (const PVR_ATTRIBUTE_STRING_VALUE &right)
virtual ~DynamicCStructHdl ()
operator PVR_ATTRIBUTE_STRING_VALUE * ()
operator const PVR_ATTRIBUTE_STRING_VALUE * () const
const PVR_ATTRIBUTE_STRING_VALUE * GetCStructure () const
PVR_ATTRIBUTE_STRING_VALUE * release ()
Static Public Member Functions
static PVR_ATTRIBUTE_STRING_VALUE * AllocAndCopyData (const std::vector< PVRTypeStringValue > &source)
static PVR_ATTRIBUTE_STRING_VALUE * AllocAndCopyData (const PVR_ATTRIBUTE_STRING_VALUE *source, unsigned int size)
static void AllocResources (const PVR_ATTRIBUTE_STRING_VALUE *source, PVR_ATTRIBUTE_STRING_VALUE *target)
static void FreeResources (PVR_ATTRIBUTE_STRING_VALUE *target)
static void FreeResources (PVR_ATTRIBUTE_STRING_VALUE *values, unsigned int size)
static void ReallocAndCopyData (PVR_ATTRIBUTE_STRING_VALUE **source, unsigned int *size, const std::vector< PVRTypeStringValue > &values)
Private Member Functions
PVRTypeStringValue (const PVR_ATTRIBUTE_STRING_VALUE *data)
PVRTypeStringValue (PVR_ATTRIBUTE_STRING_VALUE *data)
Friends
class CInstancePVRClient
Additional Inherited Members
Protected Attributes inherited from kodi::addon::DynamicCStructHdl< PVRTypeStringValue, PVR_ATTRIBUTE_STRING_VALUE >
PVR_ATTRIBUTE_STRING_VALUE * m_cStructure
Constructor & Destructor Documentation
PVRTypeStringValue() [1/2]
kodi::addon::PVRTypeStringValue::PVRTypeStringValue (const PVR_ATTRIBUTE_STRING_VALUE * data) inline private
PVRTypeStringValue() [2/2]
kodi::addon::PVRTypeStringValue::PVRTypeStringValue (PVR_ATTRIBUTE_STRING_VALUE * data) inline private
Member Function Documentation
AllocAndCopyData() [1/2]
static PVR_ATTRIBUTE_STRING_VALUE * kodi::addon::PVRTypeStringValue::AllocAndCopyData (const PVR_ATTRIBUTE_STRING_VALUE * source, unsigned int size) inline static
References AllocResources(), and values.
AllocAndCopyData() [2/2]
static PVR_ATTRIBUTE_STRING_VALUE * kodi::addon::PVRTypeStringValue::AllocAndCopyData (const std::vector< PVRTypeStringValue > & source) inline static
References AllocResources(), kodi::addon::DynamicCStructHdl< PVRTypeStringValue, PVR_ATTRIBUTE_STRING_VALUE >::GetCStructure(), and values.
Referenced by kodi::addon::PVRStringSettingDefinition::AllocResources(), and ReallocAndCopyData().
AllocResources()
static void kodi::addon::PVRTypeStringValue::AllocResources (const PVR_ATTRIBUTE_STRING_VALUE * source, PVR_ATTRIBUTE_STRING_VALUE * target) inline static
References kodi::addon::AllocAndCopyString(), PVR_ATTRIBUTE_STRING_VALUE::strDescription, and PVR_ATTRIBUTE_STRING_VALUE::strValue.
Referenced by AllocAndCopyData(), and AllocAndCopyData().
FreeResources() [1/2]
static void kodi::addon::PVRTypeStringValue::FreeResources (PVR_ATTRIBUTE_STRING_VALUE * target) inline static
References kodi::addon::FreeString(), PVR_ATTRIBUTE_STRING_VALUE::strDescription, and PVR_ATTRIBUTE_STRING_VALUE::strValue.
Referenced by FreeResources(), kodi::addon::PVRStringSettingDefinition::FreeResources(), and ReallocAndCopyData().
FreeResources() [2/2]
static void kodi::addon::PVRTypeStringValue::FreeResources (PVR_ATTRIBUTE_STRING_VALUE * values, unsigned int size) inline static
References FreeResources(), and values.
ReallocAndCopyData()
static void kodi::addon::PVRTypeStringValue::ReallocAndCopyData (PVR_ATTRIBUTE_STRING_VALUE ** source, unsigned int * size, const std::vector< PVRTypeStringValue > & values) inline static
References AllocAndCopyData(), FreeResources(), and values.
Referenced by kodi::addon::PVRStringSettingDefinition::SetValues().
Friends And Related Symbol Documentation
CInstancePVRClient
friend class CInstancePVRClient friend
The documentation for this class was generated from the following file:
kodi-dev-kit/include/kodi/addon-instance/pvr/General.h