Kodi Documentation: CRefreshInfoJob Class Reference
CRefreshInfoJob Class Reference
Public Member Functions
CRefreshInfoJob (CGUIDialogProgress *progressDialog)
~CRefreshInfoJob (void) override=default
bool DoWork () override
Main workhorse function of CJob instances.
Public Member Functions inherited from CProgressJob
~CProgressJob () override
const char * GetType () const override
Function that returns the type of job.
bool operator== (const CJob *job) const override
bool ShouldCancel (unsigned int progress, unsigned int total) const override
Function for longer jobs to report progress and check whether they have been cancelled.
bool DoModal ()
Executes the job showing a modal progress dialog.
void SetProgressIndicators (CGUIDialogProgressBarHandle *progressBar, CGUIDialogProgress *progressDialog, bool updateProgress=true, bool updateInformation=true)
Sets the given progress indicators to be used during execution of the job.
bool HasProgressIndicator () const
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Protected Member Functions inherited from CProgressJob
CProgressJob ()
CProgressJob (CGUIDialogProgressBarHandle *progressBar)
bool IsModal () const
Whether the job is being run modally or in the background.
CGUIDialogProgressBarHandle * GetProgressBar () const
Returns the progress bar indicating the progress of the job.
void SetProgressBar (CGUIDialogProgressBarHandle *progress)
Sets the progress bar indicating the progress of the job.
CGUIDialogProgress * GetProgressDialog () const
Returns the progress dialog indicating the progress of the job.
void SetProgressDialog (CGUIDialogProgress *progressDialog)
Sets the progress bar indicating the progress of the job.
bool GetAutoClose ()
Whether to automatically close the progress indicator in MarkFinished().
void SetAutoClose (bool autoClose)
Set whether to automatically close the progress indicator in MarkFinished().
bool GetUpdateProgress ()
Whether to update the progress bar or not.
void SetUpdateProgress (bool updateProgress)
Set whether to update the progress bar or not.
bool GetUpdateInformation ()
Whether to update the progress information or not.
void SetUpdateInformation (bool updateInformation)
Set whether to update the progress information or not.
void ShowProgressDialog () const
Makes sure that the modal dialog is being shown.
void SetTitle (const std::string &title)
Sets the given title as the title of the progress bar.
void SetText (const std::string &text)
Sets the given text as the description of the progress bar.
void SetProgress (float percentage) const
Sets the progress of the progress bar to the given value in percentage.
void SetProgress (int currentStep, int totalSteps) const
Sets the progress of the progress bar to the given value.
void MarkFinished ()
Marks the progress as finished by setting it to 100%.
bool IsCancelled () const
Checks if the progress dialog has been cancelled.
Constructor & Destructor Documentation
CRefreshInfoJob()
CRefreshInfoJob::CRefreshInfoJob (CGUIDialogProgress * progressDialog) inline
References CProgressJob::SetAutoClose(), and CProgressJob::SetProgressIndicators().
~CRefreshInfoJob()
CRefreshInfoJob::~CRefreshInfoJob (void) override default
Member Function Documentation
DoWork()
bool CRefreshInfoJob::DoWork () inline override virtual
Main workhorse function of CJob instances.
All CJob subclasses must implement this function, performing all processing. Once this function is complete, the OnJobComplete() callback is called, and the job is then destroyed.
See also
CJobManager, IJobCallback::OnJobComplete()
Implements CJob.
References CMusicDatabase::ClearAlbumLastScrapedTime(), CMusicDatabase::ClearArtistLastScrapedTime(), CDatabase::Close(), CONTENT_ALBUMS, CONTENT_ARTISTS, MUSIC_UTILS::FillArtTypesList(), CGUIDialogMusicInfo::GetAlbum(), CGUIDialogMusicInfo::GetArtist(), CGUIDialogMusicInfo::GetCurrentListItem(), CServiceBroker::GetGUI(), CProgressJob::GetProgressDialog(), CMusicDatabase::GetScraper(), CGUIComponent::GetWindowManager(), CAlbum::idAlbum, CArtist::idArtist, CInfoScanner::INFO_ADDED, CGUIDialogProgress::IsCanceled(), CGUIDialogMusicInfo::IsCancelled(), CMusicThumbLoader::LoadItem(), CProgressJob::MarkFinished(), MediaTypeArtist, CMusicDatabase::Open(), CGUIDialogMusicInfo::SetArtTypeList(), CGUIDialogMusicInfo::SetDiscography(), CMusicDatabase::SetPropertiesFromAlbum(), CMusicDatabase::SetPropertiesFromArtist(), CGUIDialogMusicInfo::SetScrapedInfo(), CGUIDialogMusicInfo::SetSongs(), CAlbum::songs, MUSIC_INFO::CMusicInfoScanner::UpdateAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::UpdateArtistInfo(), and WINDOW_DIALOG_MUSIC_INFO.
The documentation for this class was generated from the following file:
GUIDialogMusicInfo.cpp