Kodi Documentation: PVR::CPVRStringSettingDefinition Class Reference
PVR::CPVRStringSettingDefinition Class Reference
#include <PVRStringSettingDefinition.h>
Public Member Functions
CPVRStringSettingDefinition ()=default
CPVRStringSettingDefinition (const PVR_STRING_SETTING_DEFINITION &def)
virtual ~CPVRStringSettingDefinition ()=default
bool operator== (const CPVRStringSettingDefinition &right) const
bool operator!= (const CPVRStringSettingDefinition &right) const
const std::vector< SettingStringValue > & GetValues () const
const std::string & GetDefaultValue () const
bool IsAllowEmptyValue () const
Private Attributes
CPVRStringSettingValues m_values
bool m_allowEmptyValue {true}
Constructor & Destructor Documentation
CPVRStringSettingDefinition() [1/2]
PVR::CPVRStringSettingDefinition::CPVRStringSettingDefinition () default
CPVRStringSettingDefinition() [2/2]
PVR::CPVRStringSettingDefinition::CPVRStringSettingDefinition (const PVR_STRING_SETTING_DEFINITION & def) explicit
~CPVRStringSettingDefinition()
virtual PVR::CPVRStringSettingDefinition::~CPVRStringSettingDefinition () virtual default
Member Function Documentation
GetDefaultValue()
const std::string & PVR::CPVRStringSettingDefinition::GetDefaultValue () const inline
References PVR::CPVRStringSettingValues::GetDefaultValue(), and m_values.
Referenced by PVR::CPVRTimerSettingDefinition::GetDefaultValue().
GetValues()
const std::vector< SettingStringValue > & PVR::CPVRStringSettingDefinition::GetValues () const inline
References PVR::CPVRStringSettingValues::GetValues(), and m_values.
IsAllowEmptyValue()
bool PVR::CPVRStringSettingDefinition::IsAllowEmptyValue () const inline
References m_allowEmptyValue.
operator!=()
bool PVR::CPVRStringSettingDefinition::operator!= (const CPVRStringSettingDefinition & right) const
References right.
operator==()
bool PVR::CPVRStringSettingDefinition::operator== (const CPVRStringSettingDefinition & right) const
References m_allowEmptyValue, m_values, PVR::CPVRStringSettingValues::m_values, and right.
Member Data Documentation
m_allowEmptyValue
bool PVR::CPVRStringSettingDefinition::m_allowEmptyValue {true} private
Referenced by IsAllowEmptyValue(), and operator==().
m_values
CPVRStringSettingValues PVR::CPVRStringSettingDefinition::m_values private
Referenced by GetDefaultValue(), GetValues(), and operator==().
The documentation for this class was generated from the following files:
PVRStringSettingDefinition.h
PVRStringSettingDefinition.cpp