Kodi Documentation: class PVRDescrambleInfo
class PVRDescrambleInfo
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 2. Channel
Data structure for descrample info
Information data to give via this to Kodi.
Modules
Value Help
Classes
class kodi::addon::PVRDescrambleInfo
Macros
#define PVR_DESCRAMBLE_INFO_NOT_AVAILABLE -1
Special class PVRDescrambleInfo value to indicate that a struct member's value is not available.
Functions
void kodi::addon::PVRDescrambleInfo::SetPID (int pid)
optional
Packet identifier.
int kodi::addon::PVRDescrambleInfo::GetPID () const
To get with SetPID changed values.
void kodi::addon::PVRDescrambleInfo::SetCAID (int iCaid)
optional
Conditional access identifier.
int kodi::addon::PVRDescrambleInfo::GetCAID () const
To get with SetCAID changed values.
void kodi::addon::PVRDescrambleInfo::SetProviderID (int provid)
optional
Provider-ID.
int kodi::addon::PVRDescrambleInfo::GetProviderID () const
To get with SetProviderID changed values.
void kodi::addon::PVRDescrambleInfo::SetECMTime (int ecmTime)
optional
ECM time.
int kodi::addon::PVRDescrambleInfo::GetECMTime () const
To get with SetECMTime changed values.
void kodi::addon::PVRDescrambleInfo::SetHops (int hops)
optional
Hops.
int kodi::addon::PVRDescrambleInfo::GetHops () const
To get with SetHops changed values.
void kodi::addon::PVRDescrambleInfo::SetCardSystem (const std::string &cardSystem)
optional
Empty string if not available.
std::string kodi::addon::PVRDescrambleInfo::GetCardSystem () const
To get with SetCardSystem changed values.
void kodi::addon::PVRDescrambleInfo::SetReader (const std::string &reader)
optional
Empty string if not available.
std::string kodi::addon::PVRDescrambleInfo::GetReader () const
To get with SetReader changed values.
void kodi::addon::PVRDescrambleInfo::SetFrom (const std::string &from)
optional
Empty string if not available.
std::string kodi::addon::PVRDescrambleInfo::GetFrom () const
To get with SetFrom changed values.
void kodi::addon::PVRDescrambleInfo::SetProtocol (const std::string &protocol)
optional
Empty string if not available.
std::string kodi::addon::PVRDescrambleInfo::GetProtocol () const
To get with SetProtocol changed values.
Detailed Description
Data structure for descrample info
Information data to give via this to Kodi.
As description see also here https://en.wikipedia.org/wiki/Conditional_access.
Used on kodi::addon::CInstancePVRClient::GetDescrambleInfo().
The following table contains values that can be set with class PVRDescrambleInfo :
Name Type Set call Get call Usage
Packet identifier int SetPID GetPID optional
Conditional access identifier int SetCAID GetCAID optional
Provider-ID int SetProviderID GetProviderID optional
ECM time int SetECMTime GetECMTime optional
Hops int SetHops GetHops optional
Descramble card system std::string SetHops GetHops optional
Reader std::string SetReader GetReader optional
From std::string SetFrom GetFrom optional
Protocol std::string SetProtocol GetProtocol optional
Macro Definition Documentation
PVR_DESCRAMBLE_INFO_NOT_AVAILABLE
#define PVR_DESCRAMBLE_INFO_NOT_AVAILABLE -1
Special class PVRDescrambleInfo value to indicate that a struct member's value is not available.
Function Documentation
GetCAID()
int kodi::addon::PVRDescrambleInfo::GetCAID () const inline
To get with SetCAID changed values.
References PVR_DESCRAMBLE_INFO::iCaid, and kodi::addon::DynamicCStructHdl< PVRDescrambleInfo, PVR_DESCRAMBLE_INFO >::m_cStructure.
GetCardSystem()
std::string kodi::addon::PVRDescrambleInfo::GetCardSystem () const inline
To get with SetCardSystem changed values.
References kodi::addon::DynamicCStructHdl< PVRDescrambleInfo, PVR_DESCRAMBLE_INFO >::m_cStructure, and PVR_DESCRAMBLE_INFO::strCardSystem.
GetECMTime()
int kodi::addon::PVRDescrambleInfo::GetECMTime () const inline
To get with SetECMTime changed values.
References PVR_DESCRAMBLE_INFO::iEcmTime, and kodi::addon::DynamicCStructHdl< PVRDescrambleInfo, PVR_DESCRAMBLE_INFO >::m_cStructure.
GetFrom()
std::string kodi::addon::PVRDescrambleInfo::GetFrom () const inline
To get with SetFrom changed values.
References kodi::addon::DynamicCStructHdl< PVRDescrambleInfo, PVR_DESCRAMBLE_INFO >::m_cStructure, and PVR_DESCRAMBLE_INFO::strFrom.
GetHops()
int kodi::addon::PVRDescrambleInfo::GetHops () const inline
To get with SetHops changed values.
References PVR_DESCRAMBLE_INFO::iHops, and kodi::addon::DynamicCStructHdl< PVRDescrambleInfo, PVR_DESCRAMBLE_INFO >::m_cStructure.
GetPID()
int kodi::addon::PVRDescrambleInfo::GetPID () const inline
To get with SetPID changed values.
References PVR_DESCRAMBLE_INFO::iPid, and kodi::addon::DynamicCStructHdl< PVRDescrambleInfo, PVR_DESCRAMBLE_INFO >::m_cStructure.
GetProtocol()
std::string kodi::addon::PVRDescrambleInfo::GetProtocol () const inline
To get with SetProtocol changed values.
References kodi::addon::DynamicCStructHdl< PVRDescrambleInfo, PVR_DESCRAMBLE_INFO >::m_cStructure, and PVR_DESCRAMBLE_INFO::strProtocol.
GetProviderID()
int kodi::addon::PVRDescrambleInfo::GetProviderID () const inline
To get with SetProviderID changed values.
References PVR_DESCRAMBLE_INFO::iProvid, and kodi::addon::DynamicCStructHdl< PVRDescrambleInfo, PVR_DESCRAMBLE_INFO >::m_cStructure.
GetReader()
std::string kodi::addon::PVRDescrambleInfo::GetReader () const inline
To get with SetReader changed values.
References kodi::addon::DynamicCStructHdl< PVRDescrambleInfo, PVR_DESCRAMBLE_INFO >::m_cStructure, and PVR_DESCRAMBLE_INFO::strReader.
SetCAID()
void kodi::addon::PVRDescrambleInfo::SetCAID (int iCaid) inline
optional
Conditional access identifier.
Conditional access (abbreviated CA) or conditional access system (abbreviated CAS) is the protection of content by requiring certain criteria to be met before granting access to the content.
Available CA system ID's listed here https://www.dvbservices.com/identifiers/ca_system_id.
PVR_DESCRAMBLE_INFO_NOT_AVAILABLE if not available.
References PVR_DESCRAMBLE_INFO::iCaid, and kodi::addon::DynamicCStructHdl< PVRDescrambleInfo, PVR_DESCRAMBLE_INFO >::m_cStructure.
SetCardSystem()
void kodi::addon::PVRDescrambleInfo::SetCardSystem (const std::string & cardSystem) inline
optional
Empty string if not available.
References kodi::addon::DynamicCStructHdl< PVRDescrambleInfo, PVR_DESCRAMBLE_INFO >::m_cStructure, kodi::addon::ReallocAndCopyString(), and PVR_DESCRAMBLE_INFO::strCardSystem.
SetECMTime()
void kodi::addon::PVRDescrambleInfo::SetECMTime (int ecmTime) inline
optional
ECM time.
Is PVR_DESCRAMBLE_INFO_NOT_AVAILABLE as default, if not available.
References PVR_DESCRAMBLE_INFO::iEcmTime, and kodi::addon::DynamicCStructHdl< PVRDescrambleInfo, PVR_DESCRAMBLE_INFO >::m_cStructure.
SetFrom()
void kodi::addon::PVRDescrambleInfo::SetFrom (const std::string & from) inline
optional
Empty string if not available.
References kodi::addon::DynamicCStructHdl< PVRDescrambleInfo, PVR_DESCRAMBLE_INFO >::m_cStructure, kodi::addon::ReallocAndCopyString(), and PVR_DESCRAMBLE_INFO::strFrom.
SetHops()
void kodi::addon::PVRDescrambleInfo::SetHops (int hops) inline
optional
Hops.
Is PVR_DESCRAMBLE_INFO_NOT_AVAILABLE as default, if not available.
References PVR_DESCRAMBLE_INFO::iHops, and kodi::addon::DynamicCStructHdl< PVRDescrambleInfo, PVR_DESCRAMBLE_INFO >::m_cStructure.
SetPID()
void kodi::addon::PVRDescrambleInfo::SetPID (int pid) inline
optional
Packet identifier.
Each table or elementary stream in a transport stream is identified by a 13-bit packet identifier (PID).
Is PVR_DESCRAMBLE_INFO_NOT_AVAILABLE as default, if not available
References PVR_DESCRAMBLE_INFO::iPid, and kodi::addon::DynamicCStructHdl< PVRDescrambleInfo, PVR_DESCRAMBLE_INFO >::m_cStructure.
SetProtocol()
void kodi::addon::PVRDescrambleInfo::SetProtocol (const std::string & protocol) inline
optional
Empty string if not available.
References kodi::addon::DynamicCStructHdl< PVRDescrambleInfo, PVR_DESCRAMBLE_INFO >::m_cStructure, kodi::addon::ReallocAndCopyString(), and PVR_DESCRAMBLE_INFO::strProtocol.
SetProviderID()
void kodi::addon::PVRDescrambleInfo::SetProviderID (int provid) inline
optional
Provider-ID.
Is PVR_DESCRAMBLE_INFO_NOT_AVAILABLE as default, if not available.
References PVR_DESCRAMBLE_INFO::iProvid, and kodi::addon::DynamicCStructHdl< PVRDescrambleInfo, PVR_DESCRAMBLE_INFO >::m_cStructure.
SetReader()
void kodi::addon::PVRDescrambleInfo::SetReader (const std::string & reader) inline
optional
Empty string if not available.
References kodi::addon::DynamicCStructHdl< PVRDescrambleInfo, PVR_DESCRAMBLE_INFO >::m_cStructure, kodi::addon::ReallocAndCopyString(), and PVR_DESCRAMBLE_INFO::strReader.