Kodi Documentation: CNetworkBase Class Reference
CNetworkBase Class Reference abstract
#include <Network.h>
Public Types
enum EMESSAGE { SERVICES_UP , SERVICES_DOWN }
Public Member Functions
CNetworkBase ()
virtual ~CNetworkBase ()
CNetworkServices & GetServices ()
virtual bool GetHostName (std::string &hostname)
virtual std::vector< CNetworkInterface * > & GetInterfaceList (void)=0
virtual CNetworkInterface * GetFirstConnectedInterface (void)
bool HasInterfaceForIP (unsigned long address)
bool IsAvailable (void)
bool IsConnected (void)
bool WakeOnLan (const char *mac)
bool PingHost (unsigned long host, unsigned short port, unsigned int timeout_ms=2000, bool readability_check=false)
virtual bool PingHost (unsigned long host, unsigned int timeout_ms=2000)=0
virtual std::vector< std::string > GetNameServers (void)=0
void NetworkMessage (EMESSAGE message, int param)
bool IsLocalHost (const std::string &hostname)
void WaitForNet ()
Static Public Member Functions
static std::unique_ptr< CNetworkBase > GetNetwork ()
static int ParseHex (char *str, unsigned char *addr)
static std::string GetIpStr (const sockaddr *sa)
IPv6/IPv4 compatible conversion of host IP address.
static std::string GetMaskByPrefixLength (uint8_t prefixLength)
convert prefix length of IPv4 address to IP mask representation
Public Attributes
std::unique_ptr< CNetworkServices > m_services
Member Enumeration Documentation
EMESSAGE
enum CNetworkBase::EMESSAGE
Enumerator
SERVICES_UP
SERVICES_DOWN
Constructor & Destructor Documentation
CNetworkBase()
CNetworkBase::CNetworkBase ()
References CServiceBroker::GetAppMessenger(), SERVICES_UP, and TMSG_NETWORKMESSAGE.
~CNetworkBase()
CNetworkBase::~CNetworkBase () virtual
References CServiceBroker::GetAppMessenger(), SERVICES_DOWN, and TMSG_NETWORKMESSAGE.
Member Function Documentation
GetFirstConnectedInterface()
CNetworkInterface * CNetworkBase::GetFirstConnectedInterface (void) virtual
Reimplemented in CNetworkAndroid, CNetworkIOS, CNetworkPosix, and CNetworkWin10.
References GetInterfaceList().
Referenced by UPNP::CUPnP::CUPnP(), ADDON::Interface_Network::get_ip_address(), CNetworkPosix::GetFirstConnectedInterface(), CNetworkWin10::GetFirstConnectedInterface(), CSysInfoJob::GetGatewayAddress(), XBMCAddon::xbmc::getIPAddress(), CSysInfoJob::GetIPAddress(), CSysInfoJob::GetMACAddress(), UPNP::CUPnPRenderer::GetMetadata(), CSysInfoJob::GetNetMask(), CSysInfoJob::GetNetworkLinkState(), CAirTunesServer::Initialize(), IsConnected(), URIUtils::IsHostOnLAN(), CNetworkServices::StartAirPlayServer(), and CAirTunesServer::StartServer().
GetHostName()
bool CNetworkBase::GetHostName (std::string & hostname) virtual
Reimplemented in CNetworkAndroid.
References g_charsetConverter.
Referenced by CSysInfo::GetDeviceName(), and IsLocalHost().
GetInterfaceList()
virtual std::vector< CNetworkInterface * > & CNetworkBase::GetInterfaceList (void) pure virtual
Implemented in CNetworkAndroid, CNetworkIOS, CNetworkPosix, CNetworkWin10, and CNetworkWin32.
Referenced by CMACDiscoveryJob::DoWork(), GetFirstConnectedInterface(), HasInterfaceForIP(), IsAvailable(), and IsLocalHost().
GetIpStr()
std::string CNetworkBase::GetIpStr (const sockaddr * sa) static
IPv6/IPv4 compatible conversion of host IP address.
Parameters
struct sockaddr
Returns
Function converts binary structure sockaddr to std::string. It can read sockaddr_in and sockaddr_in6, cast as (sockaddr*). IPv4 address is returned in the format x.x.x.x (where x is 0-255), IPv6 address is returned in it's canonised form. On error (or no IPv6/v4 valid input) empty string is returned.
Referenced by CNetworkInterfaceWin10::GetCurrentDefaultGateway(), CNetworkInterfaceWin32::GetCurrentDefaultGateway(), CNetworkInterfaceWin10::GetCurrentIPAddress(), CNetworkInterfaceWin32::GetCurrentIPAddress(), GetMaskByPrefixLength(), CNetworkWin32::GetNameServers(), and CDNSNameCache::Lookup().
GetMaskByPrefixLength()
std::string CNetworkBase::GetMaskByPrefixLength (uint8_t prefixLength) static
convert prefix length of IPv4 address to IP mask representation
Parameters
prefix length
Returns
References GetIpStr().
Referenced by CNetworkInterfaceWin10::GetCurrentNetmask(), and CNetworkInterfaceWin32::GetCurrentNetmask().
GetNameServers()
virtual std::vector< std::string > CNetworkBase::GetNameServers (void) pure virtual
Implemented in CNetworkAndroid, CNetworkIOS, CNetworkMacOS, CNetworkFreebsd, CNetworkLinux, CNetworkWin10, and CNetworkWin32.
Referenced by CSysInfoJob::GetDNSServers().
GetNetwork()
std::unique_ptr< CNetworkBase > CNetworkBase::GetNetwork () static
Referenced by CServiceBroker::GetNetwork(), CServiceManager::InitForTesting(), and CServiceManager::InitStageOne().
GetServices()
CNetworkServices & CNetworkBase::GetServices () inline
References m_services.
Referenced by XBMCAddon::xbmc::startServer().
HasInterfaceForIP()
bool CNetworkBase::HasInterfaceForIP (unsigned long address)
References CNetworkInterface::GetCurrentIPAddress(), CNetworkInterface::GetCurrentNetmask(), GetInterfaceList(), and CNetworkInterface::IsConnected().
Referenced by URIUtils::IsHostOnLAN(), and NetworkStartWaiter::SuccessWaiting().
IsAvailable()
bool CNetworkBase::IsAvailable (void)
References GetInterfaceList().
Referenced by CRssReader::Process(), and WaitForNet().
IsConnected()
bool CNetworkBase::IsConnected (void)
References GetFirstConnectedInterface().
Referenced by WaitForNet().
IsLocalHost()
bool CNetworkBase::IsLocalHost (const std::string & hostname)
References CNetworkInterface::GetCurrentIPAddress(), GetHostName(), and GetInterfaceList().
Referenced by PVR::CPVRGUIActionsPowerManagement::EventOccursOnLocalBackend(), ADDON::Interface_Network::is_local_host(), and CURL::IsLocalHost().
NetworkMessage()
void CNetworkBase::NetworkMessage (EMESSAGE message, int param)
References CLog::Log(), LOGDEBUG, m_services, SERVICES_DOWN, and SERVICES_UP.
Referenced by CProfileManager::FinalizeLoadProfile(), CProfileManager::LogOff(), and CProfileManager::PrepareLoadProfile().
ParseHex()
int CNetworkBase::ParseHex (char * str, unsigned char * addr) static
Referenced by CNetworkInterfaceLinux::GetCurrentDefaultGateway().
PingHost() [1/2]
virtual bool CNetworkBase::PingHost (unsigned long host, unsigned int timeout_ms = 2000) pure virtual
Implemented in CNetworkIOS, CNetworkMacOS, CNetworkFreebsd, CNetworkLinux, CNetworkWin10, CNetworkWin32, CNetworkAndroid, CNetworkWin32, and CNetworkAndroid.
PingHost() [2/2]
bool CNetworkBase::PingHost (unsigned long host, unsigned short port, unsigned int timeout_ms = 2000, bool readability_check = false)
References closesocket, ConnectHostPort(), INVALID_SOCKET, CLog::Log(), LOGERROR, PingHost(), void(), WSAGetLastError, and CWIN32Util::WUSysMsg().
Referenced by PingResponseWaiter::Ping(), and PingHost().
WaitForNet()
void CNetworkBase::WaitForNet ()
References CServiceBroker::GetSettingsComponent(), IsAvailable(), IsConnected(), CLog::Log(), LOGINFO, CSettings::SETTING_POWERMANAGEMENT_WAITFORNETWORK, and KODI::TIME::Sleep().
Referenced by CPowerManager::OnWake().
WakeOnLan()
bool CNetworkBase::WakeOnLan (const char * mac)
References closesocket, in_ether(), CLog::Log(), LOGERROR, LOGINFO, SOCKET_ERROR, and value.
Referenced by ADDON::Interface_Network::wake_on_lan(), and WakeOnLAN().
Member Data Documentation
m_services
std::unique_ptr<CNetworkServices> CNetworkBase::m_services
Referenced by GetServices(), and NetworkMessage().
The documentation for this class was generated from the following files:
network/Network.h
network/Network.cpp
NetworkAndroid.cpp
NetworkIOS.mm
NetworkMacOS.mm
NetworkFreebsd.cpp
NetworkLinux.cpp
NetworkWin10.cpp
NetworkWin32.cpp