Kodi Documentation: CTVOSTopShelf Class Reference
CTVOSTopShelf Class Reference
#include <TVOSTopShelf.h>
Public Member Functions
void RunTopShelf ()
void SetTopShelfItems (CFileItemList &items, TVOSTopShelfItemsCategory category)
void HandleTopShelfUrl (const std::string &url, const bool run)
Static Public Member Functions
static CTVOSTopShelf & GetInstance ()
Private Member Functions
CTVOSTopShelf ()=default
~CTVOSTopShelf ()=default
Static Private Attributes
static std::string m_url
static bool m_handleUrl
Constructor & Destructor Documentation
CTVOSTopShelf()
CTVOSTopShelf::CTVOSTopShelf () private default
~CTVOSTopShelf()
CTVOSTopShelf::~CTVOSTopShelf () private default
Member Function Documentation
GetInstance()
CTVOSTopShelf & CTVOSTopShelf::GetInstance () static
Referenced by CRecentlyAddedJob::UpdateVideo().
HandleTopShelfUrl()
void CTVOSTopShelf::HandleTopShelfUrl (const std::string & url, const bool run)
References m_handleUrl, and m_url.
RunTopShelf()
void CTVOSTopShelf::RunTopShelf ()
@Todo handle tvcontentitem.displayurl. Should show topshelf item video info
References Base64::Decode(), CServiceBroker::GetAppMessenger(), m_handleUrl, m_url, and TMSG_EXECUTE_BUILT_IN.
SetTopShelfItems()
void CTVOSTopShelf::SetTopShelfItems (CFileItemList & items, TVOSTopShelfItemsCategory category)
References URIUtils::AddFileToFolder(), XFILE::CFile::Copy(), Base64::Encode(), XFILE::CFile::Exists(), g_localizeStrings, CFileItemList::Get(), CLocalizeStrings::Get(), URIUtils::GetFileName(), CDarwinEmbedUtils::IsIosSandboxed(), CVideoThumbLoader::LoadItem(), CLog::Log(), LOGDEBUG, MaxItems, MOVIES, CVideoDatabase::Open(), CFileItemList::Size(), and TV_SHOWS.
Referenced by CRecentlyAddedJob::UpdateVideo().
Member Data Documentation
m_handleUrl
bool CTVOSTopShelf::m_handleUrl static private
Referenced by HandleTopShelfUrl(), and RunTopShelf().
m_url
std::string CTVOSTopShelf::m_url static private
Referenced by HandleTopShelfUrl(), and RunTopShelf().
The documentation for this class was generated from the following files:
TVOSTopShelf.h
TVOSTopShelf.mm