Kodi Documentation: MUSIC_UTILS::CSetArtJob Class Reference
MUSIC_UTILS::CSetArtJob Class Reference
Public Member Functions
CSetArtJob (const CFileItemPtr &item, const std::string &type, const std::string &newArt)
~CSetArtJob (void) override=default
bool HasSongExtraArtChanged (const CFileItemPtr &pSongItem, const std::string &type, const int itemID, CMusicDatabase &db)
bool DoWork (void) override
Main workhorse function of CJob instances.
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
virtual const char * GetType () const
Function that returns the type of job.
virtual bool operator== (const CJob *job) const
virtual bool ShouldCancel (unsigned int progress, unsigned int total) const
Function for longer jobs to report progress and check whether they have been cancelled.
Private Attributes
CFileItemPtr pItem
std::string m_artType
std::string m_newArt
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Constructor & Destructor Documentation
CSetArtJob()
MUSIC_UTILS::CSetArtJob::CSetArtJob (const CFileItemPtr & item, const std::string & type, const std::string & newArt) inline
~CSetArtJob()
MUSIC_UTILS::CSetArtJob::~CSetArtJob (void) override default
Member Function Documentation
DoWork()
bool MUSIC_UTILS::CSetArtJob::DoWork (void) inline override virtual
Main workhorse function of CJob instances.
All CJob subclasses must implement this function, performing all processing. Once this function is complete, the OnJobComplete() callback is called, and the job is then destroyed.
See also
CJobManager, IJobCallback::OnJobComplete()
Implements CJob.
References CDatabase::Close(), g_application, CServiceBroker::GetAppComponents(), KODI::PLAYLIST::CPlayListPlayer::GetPlaylist(), CServiceBroker::GetPlaylistPlayer(), HasSongExtraArtChanged(), m_artType, m_newArt, CMusicDatabase::Open(), pItem, playlist, CMusicDatabase::RemoveArtForItem(), CFileItemList::RemoveDiscCache(), CMusicDatabase::SetArtForItem(), CMusicDatabase::SetItemUpdated(), and WINDOW_MUSIC_PLAYLIST.
HasSongExtraArtChanged()
bool MUSIC_UTILS::CSetArtJob::HasSongExtraArtChanged (const CFileItemPtr & pSongItem, const std::string & type, const int itemID, CMusicDatabase & db) inline
References CMusicDatabase::IsSongAlbumArtist(), CMusicDatabase::IsSongArtist(), MediaTypeAlbum, and MediaTypeArtist.
Referenced by DoWork().
Member Data Documentation
m_artType
std::string MUSIC_UTILS::CSetArtJob::m_artType private
Referenced by DoWork().
m_newArt
std::string MUSIC_UTILS::CSetArtJob::m_newArt private
Referenced by DoWork().
pItem
CFileItemPtr MUSIC_UTILS::CSetArtJob::pItem private
Referenced by DoWork().
The documentation for this class was generated from the following file:
MusicUtils.cpp