Kodi Documentation: KODI::KEYMAP::CButtonTranslator Class Reference
KODI::KEYMAP::CButtonTranslator Class Reference
Singleton class to map from buttons to actions.
#include <ButtonTranslator.h>
Classes
struct CButtonAction
Public Member Functions
CButtonTranslator ()=default
CButtonTranslator (const CButtonTranslator &)=delete
CButtonTranslator const & operator= (CButtonTranslator const &)=delete
virtual ~CButtonTranslator ()=default
bool AddDevice (const std::string &strDevice)
bool RemoveDevice (const std::string &strDevice)
bool Load ()
loads Keymap.xml
void Clear ()
clears the maps
bool HasLongpressMapping (int window, const CKey &key)
Finds out if a longpress mapping exists for this key.
CAction GetAction (int window, const CKey &key, bool fallback=true)
Obtain the action configured for a given window and key.
void RegisterMapper (const std::string &device, IKeyMapper *mapper)
void UnregisterMapper (const IKeyMapper *mapper)
Static Public Member Functions
static uint32_t TranslateString (const std::string &strMap, const std::string &strButton)
Private Types
typedef std::multimap< uint32_t, CButtonAction > buttonMap
Private Member Functions
unsigned int GetActionCode (int window, const CKey &key, std::string &strAction) const
void MapWindowActions (const tinyxml2::XMLNode *pWindow, int wWindowID)
void MapAction (uint32_t buttonCode, const std::string &szAction, buttonMap &map)
bool LoadKeymap (const std::string &keymapPath)
bool HasLongpressMapping_Internal (int window, const CKey &key)
Private Attributes
std::map< int, buttonMap > m_translatorMap
std::set< std::string > m_deviceList
std::map< std::string, IKeyMapper * > m_buttonMappers
Friends
class EVENTCLIENT::CEventButtonState
Detailed Description
Singleton class to map from buttons to actions.
Warning: not threadsafe!
Member Typedef Documentation
buttonMap
typedef std::multimap<uint32_t, CButtonAction> KODI::KEYMAP::CButtonTranslator::buttonMap private
Constructor & Destructor Documentation
CButtonTranslator() [1/2]
KODI::KEYMAP::CButtonTranslator::CButtonTranslator () default
CButtonTranslator() [2/2]
KODI::KEYMAP::CButtonTranslator::CButtonTranslator (const CButtonTranslator &) delete
~CButtonTranslator()
virtual KODI::KEYMAP::CButtonTranslator::~CButtonTranslator () virtual default
Member Function Documentation
AddDevice()
bool CButtonTranslator::AddDevice (const std::string & strDevice)
References Load(), and m_deviceList.
Clear()
void CButtonTranslator::Clear ()
clears the maps
References m_buttonMappers, and m_translatorMap.
Referenced by Load().
GetAction()
CAction CButtonTranslator::GetAction (int window, const CKey & key, bool fallback = true)
Obtain the action configured for a given window and key.
Parameters
window the window id
key the key to query the action for
fallback if no action is directly configured for the given window, obtain the action from fallback window, if exists or from global config as last resort
Returns
the action matching the key
References ACTION_NONE, GetActionCode(), CWindowTranslator::GetFallbackWindow(), and CWindowTranslator::GetVirtualWindow().
GetActionCode()
unsigned int CButtonTranslator::GetActionCode (int window, const CKey & key, std::string & strAction) const private
References ACTION_NONE, CKey::GetButtonCode(), KEY_VKEY, CLog::Log(), LOGDEBUG, m_translatorMap, and CKey::MODIFIER_LONG.
Referenced by GetAction().
HasLongpressMapping()
bool CButtonTranslator::HasLongpressMapping (int window, const CKey & key)
Finds out if a longpress mapping exists for this key.
Parameters
window id of the current window
key to search a mapping for
Returns
true if a longpress mapping exists
References CWindowTranslator::GetVirtualWindow(), and HasLongpressMapping_Internal().
HasLongpressMapping_Internal()
bool CButtonTranslator::HasLongpressMapping_Internal (int window, const CKey & key) private
References ACTION_NOOP, CKey::GetButtonCode(), CWindowTranslator::GetFallbackWindow(), HasLongpressMapping_Internal(), KEY_VKEY, m_translatorMap, and CKey::MODIFIER_LONG.
Referenced by HasLongpressMapping(), and HasLongpressMapping_Internal().
Load()
bool CButtonTranslator::Load ()
loads Keymap.xml
References Clear(), XFILE::DIR_FLAG_DEFAULTS, XFILE::CDirectory::Exists(), XFILE::CDirectory::GetDirectory(), LoadKeymap(), CLog::Log(), LOGERROR, m_deviceList, CFileItemList::Size(), CFileItemList::Sort(), SortByFile, SortOrderAscending, and success.
Referenced by AddDevice(), and RemoveDevice().
LoadKeymap()
bool CButtonTranslator::LoadKeymap (const std::string & keymapPath) private
References CXBMCTinyXML2::LoadFile(), CLog::Log(), LOGERROR, LOGINFO, MapWindowActions(), CWindowTranslator::TranslateWindow(), and WINDOW_INVALID.
Referenced by Load().
MapAction()
void CButtonTranslator::MapAction (uint32_t buttonCode, const std::string & szAction, buttonMap & map) private
References ACTION_NONE, KODI::KEYMAP::CButtonTranslator::CButtonAction::id, KODI::KEYMAP::CButtonTranslator::CButtonAction::strID, and KODI::ACTION::CActionTranslator::TranslateString().
Referenced by MapWindowActions().
MapWindowActions()
void CButtonTranslator::MapWindowActions (const tinyxml2::XMLNode * pWindow, int wWindowID) private
References m_buttonMappers, m_translatorMap, MapAction(), KODI::KEYMAP::IKeyMapper::MapActions(), KODI::KEYMAP::CAppTranslator::TranslateAppCommand(), KODI::KEYMAP::CKeyboardTranslator::TranslateButton(), CMouseTranslator::TranslateCommand(), KODI::KEYMAP::CGamepadTranslator::TranslateString(), KODI::KEYMAP::CIRTranslator::TranslateString(), KODI::KEYMAP::CIRTranslator::TranslateUniversalRemoteString(), types, and WINDOW_INVALID.
Referenced by LoadKeymap().
operator=()
CButtonTranslator const & KODI::KEYMAP::CButtonTranslator::operator= (CButtonTranslator const &) delete
RegisterMapper()
void CButtonTranslator::RegisterMapper (const std::string & device, IKeyMapper * mapper)
References m_buttonMappers.
RemoveDevice()
bool CButtonTranslator::RemoveDevice (const std::string & strDevice)
References Load(), and m_deviceList.
TranslateString()
uint32_t CButtonTranslator::TranslateString (const std::string & strMap, const std::string & strButton) static
References KODI::KEYMAP::CKeyboardTranslator::TranslateString(), KODI::KEYMAP::CGamepadTranslator::TranslateString(), KODI::KEYMAP::CIRTranslator::TranslateString(), and KODI::KEYMAP::CIRTranslator::TranslateUniversalRemoteString().
Referenced by JSONRPC::CInputOperations::ButtonEvent(), and EVENTCLIENT::CEventButtonState::Load().
UnregisterMapper()
void CButtonTranslator::UnregisterMapper (const IKeyMapper * mapper)
References m_buttonMappers.
Friends And Related Symbol Documentation
EVENTCLIENT::CEventButtonState
friend class EVENTCLIENT::CEventButtonState friend
Member Data Documentation
m_buttonMappers
std::map<std::string, IKeyMapper*> KODI::KEYMAP::CButtonTranslator::m_buttonMappers private
Referenced by Clear(), MapWindowActions(), RegisterMapper(), and UnregisterMapper().
m_deviceList
std::set<std::string> KODI::KEYMAP::CButtonTranslator::m_deviceList private
Referenced by AddDevice(), Load(), and RemoveDevice().
m_translatorMap
std::map<int, buttonMap> KODI::KEYMAP::CButtonTranslator::m_translatorMap private
Referenced by Clear(), GetActionCode(), HasLongpressMapping_Internal(), and MapWindowActions().
The documentation for this class was generated from the following files:
ButtonTranslator.h
ButtonTranslator.cpp