Kodi Documentation: ISlideShowDelegate Class Reference
ISlideShowDelegate Class Reference abstract
#include <ISlideShowDelegate.h>
Public Member Functions
ISlideShowDelegate ()=default
virtual ~ISlideShowDelegate ()=default
virtual void Add (const CFileItem *picture)=0
virtual bool IsPlaying () const =0
virtual void Select (const std::string &picture)=0
virtual void GetSlideShowContents (CFileItemList &list)=0
virtual std::shared_ptr< const CFileItem > GetCurrentSlide ()=0
virtual void StartSlideShow ()=0
virtual void PlayPicture ()=0
virtual bool InSlideShow () const =0
virtual int NumSlides () const =0
virtual int CurrentSlide () const =0
virtual bool IsPaused () const =0
virtual bool IsShuffled () const =0
virtual void Reset ()=0
virtual void Shuffle ()=0
virtual int GetDirection () const =0
virtual void RunSlideShow (const std::string &strPath, bool bRecursive=false, bool bRandom=false, bool bNotRandom=false, const std::string &beginSlidePath="", bool startSlideShow=true, SortBy method=SortByLabel, SortOrder order=SortOrderAscending, SortAttribute sortAttributes=SortAttributeNone, const std::string &strExtensions="")=0
virtual void AddFromPath (const std::string &strPath, bool bRecursive, SortBy method=SortByLabel, SortOrder order=SortOrderAscending, SortAttribute sortAttributes=SortAttributeNone, const std::string &strExtensions="")=0
Constructor & Destructor Documentation
ISlideShowDelegate()
ISlideShowDelegate::ISlideShowDelegate () default
~ISlideShowDelegate()
virtual ISlideShowDelegate::~ISlideShowDelegate () virtual default
Member Function Documentation
Add()
virtual void ISlideShowDelegate::Add (const CFileItem * picture) pure virtual
Implemented in CGUIWindowSlideShow, and CSlideShowDelegator.
Referenced by CSlideShowDelegator::Add().
AddFromPath()
virtual void ISlideShowDelegate::AddFromPath (const std::string & strPath, bool bRecursive, SortBy method = SortByLabel, SortOrder order = SortOrderAscending, SortAttribute sortAttributes = SortAttributeNone, const std::string & strExtensions = "") pure virtual
Todo:
refactor to use an options struct. Methods with so many arguments are a sign of a bad design...
Implemented in CGUIWindowSlideShow, and CSlideShowDelegator.
Referenced by CSlideShowDelegator::AddFromPath().
CurrentSlide()
virtual int ISlideShowDelegate::CurrentSlide () const pure virtual
Implemented in CGUIWindowSlideShow, and CSlideShowDelegator.
Referenced by CSlideShowDelegator::CurrentSlide().
GetCurrentSlide()
virtual std::shared_ptr< const CFileItem > ISlideShowDelegate::GetCurrentSlide () pure virtual
Implemented in CGUIWindowSlideShow, and CSlideShowDelegator.
Referenced by CSlideShowDelegator::GetCurrentSlide().
GetDirection()
virtual int ISlideShowDelegate::GetDirection () const pure virtual
Implemented in CGUIWindowSlideShow, and CSlideShowDelegator.
Referenced by CSlideShowDelegator::GetDirection().
GetSlideShowContents()
virtual void ISlideShowDelegate::GetSlideShowContents (CFileItemList & list) pure virtual
Implemented in CGUIWindowSlideShow, and CSlideShowDelegator.
Referenced by CSlideShowDelegator::GetSlideShowContents().
InSlideShow()
virtual bool ISlideShowDelegate::InSlideShow () const pure virtual
Implemented in CGUIWindowSlideShow, and CSlideShowDelegator.
Referenced by CSlideShowDelegator::InSlideShow().
IsPaused()
virtual bool ISlideShowDelegate::IsPaused () const pure virtual
Implemented in CGUIWindowSlideShow, and CSlideShowDelegator.
Referenced by CSlideShowDelegator::IsPaused().
IsPlaying()
virtual bool ISlideShowDelegate::IsPlaying () const pure virtual
Implemented in CGUIWindowSlideShow, and CSlideShowDelegator.
Referenced by CSlideShowDelegator::IsPlaying().
IsShuffled()
virtual bool ISlideShowDelegate::IsShuffled () const pure virtual
Implemented in CGUIWindowSlideShow, and CSlideShowDelegator.
Referenced by CSlideShowDelegator::IsShuffled().
NumSlides()
virtual int ISlideShowDelegate::NumSlides () const pure virtual
Implemented in CGUIWindowSlideShow, and CSlideShowDelegator.
Referenced by CSlideShowDelegator::NumSlides().
PlayPicture()
virtual void ISlideShowDelegate::PlayPicture () pure virtual
Implemented in CGUIWindowSlideShow, and CSlideShowDelegator.
Referenced by CSlideShowDelegator::PlayPicture().
Reset()
virtual void ISlideShowDelegate::Reset () pure virtual
Implemented in CGUIWindowSlideShow, and CSlideShowDelegator.
Referenced by CSlideShowDelegator::Reset().
RunSlideShow()
virtual void ISlideShowDelegate::RunSlideShow (const std::string & strPath, bool bRecursive = false, bool bRandom = false, bool bNotRandom = false, const std::string & beginSlidePath = "", bool startSlideShow = true, SortBy method = SortByLabel, SortOrder order = SortOrderAscending, SortAttribute sortAttributes = SortAttributeNone, const std::string & strExtensions = "") pure virtual
Todo:
refactor to use an options struct. Methods with so many arguments are a sign of a bad design...
Implemented in CGUIWindowSlideShow, and CSlideShowDelegator.
Referenced by CSlideShowDelegator::RunSlideShow().
Select()
virtual void ISlideShowDelegate::Select (const std::string & picture) pure virtual
Implemented in CGUIWindowSlideShow, and CSlideShowDelegator.
Referenced by CSlideShowDelegator::Select().
Shuffle()
virtual void ISlideShowDelegate::Shuffle () pure virtual
Implemented in CGUIWindowSlideShow, and CSlideShowDelegator.
Referenced by CSlideShowDelegator::Shuffle().
StartSlideShow()
virtual void ISlideShowDelegate::StartSlideShow () pure virtual
Implemented in CGUIWindowSlideShow, and CSlideShowDelegator.
Referenced by CSlideShowDelegator::StartSlideShow().
The documentation for this class was generated from the following file:
ISlideShowDelegate.h