Kodi Documentation: KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase Class Reference
KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase Class Reference abstract
#include <VideoSelectActionProcessor.h>
Public Member Functions
CVideoSelectActionProcessorBase (const std::shared_ptr< CFileItem > &item)
~CVideoSelectActionProcessorBase () override=default
Public Member Functions inherited from KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase
CVideoPlayActionProcessorBase (const std::shared_ptr< CFileItem > &item)
virtual ~CVideoPlayActionProcessorBase ()=default
bool ProcessDefaultAction ()
bool ProcessAction (Action action)
bool UserCancelled () const
Static Public Member Functions
static Action GetDefaultSelectAction ()
Static Public Member Functions inherited from KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase
static Action ChoosePlayOrResume (const CFileItem &item)
Protected Member Functions
Action GetDefaultAction () override
bool Process (Action action) override
virtual bool OnPlayPartSelected (unsigned int part)=0
virtual bool OnQueueSelected ()=0
virtual bool OnInfoSelected ()=0
virtual bool OnChooseSelected ()=0
Protected Member Functions inherited from KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase
virtual bool OnResumeSelected ()=0
virtual bool OnPlaySelected ()=0
Private Member Functions
CVideoSelectActionProcessorBase ()=delete
unsigned int ChooseStackItemPartNumber () const
Additional Inherited Members
Protected Attributes inherited from KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase
std::shared_ptr< CFileItem > m_item
bool m_userCancelled {false}
Constructor & Destructor Documentation
CVideoSelectActionProcessorBase() [1/2]
KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::CVideoSelectActionProcessorBase (const std::shared_ptr< CFileItem > & item) inline explicit
~CVideoSelectActionProcessorBase()
KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::~CVideoSelectActionProcessorBase () override default
CVideoSelectActionProcessorBase() [2/2]
KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::CVideoSelectActionProcessorBase () private delete
Member Function Documentation
ChooseStackItemPartNumber()
unsigned int KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::ChooseStackItemPartNumber () const private
References XFILE::DIR_FLAG_DEFAULTS, g_localizeStrings, CLocalizeStrings::Get(), XFILE::CDirectory::GetDirectory(), CServiceBroker::GetGUI(), CGUIDialogSelect::GetSelectedItem(), CGUIComponent::GetWindowManager(), CGUIDialogBoxBase::IsConfirmed(), KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::m_item, CGUIDialog::Open(), CGUIDialogSelect::Reset(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetItems(), CFileItemList::Size(), and WINDOW_DIALOG_SELECT.
Referenced by Process().
GetDefaultAction()
Action KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::GetDefaultAction () override protected virtual
Reimplemented from KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase.
References GetDefaultSelectAction().
Referenced by Process().
GetDefaultSelectAction()
Action KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::GetDefaultSelectAction () static
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_MYVIDEOS_SELECTACTION.
Referenced by GetDefaultAction(), and CGUIWindowVideoBase::OnSelect().
OnChooseSelected()
virtual bool KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::OnChooseSelected () protected pure virtual
Implemented in anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor, anonymous_namespace{DirectoryProvider.cpp}::CVideoSelectActionProcessor, anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor, CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::CVideoSelectActionProcessor, and anonymous_namespace{GUIWindowVideoBase.cpp}::CVideoSelectActionProcessor.
Referenced by Process().
OnInfoSelected()
virtual bool KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::OnInfoSelected () protected pure virtual
Implemented in anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor, anonymous_namespace{DirectoryProvider.cpp}::CVideoSelectActionProcessor, anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor, CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::CVideoSelectActionProcessor, and anonymous_namespace{GUIWindowVideoBase.cpp}::CVideoSelectActionProcessor.
Referenced by Process().
OnPlayPartSelected()
virtual bool KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::OnPlayPartSelected (unsigned int part) protected pure virtual
Implemented in anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor, anonymous_namespace{DirectoryProvider.cpp}::CVideoSelectActionProcessor, anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor, CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::CVideoSelectActionProcessor, and anonymous_namespace{GUIWindowVideoBase.cpp}::CVideoSelectActionProcessor.
Referenced by Process().
OnQueueSelected()
virtual bool KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::OnQueueSelected () protected pure virtual
Implemented in anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor, anonymous_namespace{DirectoryProvider.cpp}::CVideoSelectActionProcessor, anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor, CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::CVideoSelectActionProcessor, and anonymous_namespace{GUIWindowVideoBase.cpp}::CVideoSelectActionProcessor.
Referenced by Process().
Process()
bool KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase::Process (Action action) override protected virtual
Reimplemented from KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase.
References KODI::VIDEO::GUILIB::ACTION_CHOOSE, KODI::VIDEO::GUILIB::ACTION_INFO, KODI::VIDEO::GUILIB::ACTION_PLAYPART, KODI::VIDEO::GUILIB::ACTION_QUEUE, ChooseStackItemPartNumber(), KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::GetDefaultAction(), GetDefaultAction(), KODI::VIDEO::UTILS::HasItemVideoDbInformation(), KODI::VIDEO::IsVideoDb(), KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::m_item, OnChooseSelected(), OnInfoSelected(), OnPlayPartSelected(), OnQueueSelected(), KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase::Process(), and Process().
Referenced by Process().
The documentation for this class was generated from the following files:
VideoSelectActionProcessor.h
VideoSelectActionProcessor.cpp