Kodi Documentation: CGUIMessage Class Reference
CGUIMessage Class Reference final
Guilib classes » Window Reference » Windows and Messages
#include <GUIMessage.h>
Public Member Functions
CGUIMessage (int dwMsg, int senderID, int controlID, int64_t param1=0, int64_t param2=0)
CGUIMessage (int msg, int senderID, int controlID, int64_t param1, int64_t param2, CFileItemList *item)
CGUIMessage (int msg, int senderID, int controlID, int64_t param1, int64_t param2, const std::shared_ptr< CGUIListItem > &item)
CGUIMessage (const CGUIMessage &msg)
~CGUIMessage (void)
CGUIMessage & operator= (const CGUIMessage &msg)
int GetControlId () const
int GetMessage () const
void * GetPointer () const
std::shared_ptr< CGUIListItem > GetItem () const
int GetParam1 () const
int64_t GetParam1AsI64 () const
int GetParam2 () const
int64_t GetParam2AsI64 () const
int GetSenderId () const
void SetParam1 (int64_t param1)
void SetParam2 (int64_t param2)
void SetPointer (void *pointer)
void SetLabel (const std::string &strLabel)
void SetLabel (int iString)
const std::string & GetLabel () const
void SetStringParam (const std::string &strParam)
void SetStringParams (const std::vector< std::string > &params)
const std::string & GetStringParam (size_t param=0) const
size_t GetNumStringParams () const
void SetItem (std::shared_ptr< CGUIListItem > item)
Private Attributes
std::string m_strLabel
std::vector< std::string > m_params
int m_senderID
int m_controlID
int m_message
void * m_pointer
int64_t m_param1
int64_t m_param2
std::shared_ptr< CGUIListItem > m_item
Static Private Attributes
static std::string empty_string
Constructor & Destructor Documentation
CGUIMessage() [1/4]
CGUIMessage::CGUIMessage (int dwMsg, int senderID, int controlID, int64_t param1 = 0, int64_t param2 = 0)
References m_controlID, m_message, m_param1, m_param2, m_pointer, and m_senderID.
CGUIMessage() [2/4]
CGUIMessage::CGUIMessage (int msg, int senderID, int controlID, int64_t param1, int64_t param2, CFileItemList * item)
References m_controlID, m_message, m_param1, m_param2, m_pointer, and m_senderID.
CGUIMessage() [3/4]
CGUIMessage::CGUIMessage (int msg, int senderID, int controlID, int64_t param1, int64_t param2, const std::shared_ptr< CGUIListItem > & item)
References m_controlID, m_message, m_param1, m_param2, m_pointer, and m_senderID.
CGUIMessage() [4/4]
CGUIMessage::CGUIMessage (const CGUIMessage & msg) default
~CGUIMessage()
CGUIMessage::~CGUIMessage (void) default
Member Function Documentation
GetControlId()
int CGUIMessage::GetControlId () const
References m_controlID.
Referenced by CGUIControl::OnMessage(), ADDON::CGUIAddonWindow::OnMessage(), CGUIDialogColorPicker::OnMessage(), CGUIDialogFileBrowser::OnMessage(), CGUIDialogMediaSource::OnMessage(), CGUIDialogSeekBar::OnMessage(), CGUIDialogSelect::OnMessage(), CGUIDialogSmartPlaylistEditor::OnMessage(), KODI::GAME::CGUIAgentWindow::OnMessage(), KODI::GAME::CGUIControllerWindow::OnMessage(), KODI::GAME::CDialogGameSaves::OnMessage(), KODI::GAME::CDialogGameVideoSelect::OnMessage(), KODI::GAME::CDialogGameVolume::OnMessage(), KODI::GAME::CDialogInGameSaves::OnMessage(), KODI::GAME::CGUIPortWindow::OnMessage(), CGUIBaseContainer::OnMessage(), CGUIButtonControl::OnMessage(), CGUIControlGroup::OnMessage(), CGUIControlGroupList::OnMessage(), CGUIEditControl::OnMessage(), CGUIFadeLabelControl::OnMessage(), CGUILabelControl::OnMessage(), CGUIListContainer::OnMessage(), CGUIPanelContainer::OnMessage(), CGUISliderControl::OnMessage(), CGUISpinControl::OnMessage(), CGUITextBox::OnMessage(), CGUIWindow::OnMessage(), CGUIWrappingListContainer::OnMessage(), XBMCAddon::xbmcgui::WindowXML::OnMessage(), PERIPHERALS::CGUIDialogPeripherals::OnMessage(), PVR::CGUIEPGGridContainer::OnMessage(), CGUIDialogSettingsBase::OnMessage(), CGUIDialogVideoBookmarks::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIWindowLoginScreen::OnMessage(), CGUIControlGroup::SendControlMessage(), and CGUIWindowManager::SendMessage().
GetItem()
std::shared_ptr< CGUIListItem > CGUIMessage::GetItem () const
References m_item.
Referenced by CApplication::OnMessage(), CGUIDialogKeyboardGeneric::OnMessage(), CGUIWindowEventLog::OnMessage(), KODI::GAME::CDialogInGameSaves::OnMessage(), KODI::PLAYLIST::CPlayListPlayer::OnMessage(), CGUIDialogVideoInfo::OnMessage(), and CGUIMediaWindow::OnMessage().
GetLabel()
const std::string & CGUIMessage::GetLabel () const
References m_strLabel.
Referenced by CGUIMediaWindow::Filter(), ADDON::Interface_GUIControlFadeLabel::get_label(), PVR::CGUIDialogPVRGuideSearch::GetEditValue(), XBMCAddon::xbmcgui::ControlEdit::getText(), PVR::CGUIDialogPVRChannelManager::OnClickButtonEditName(), CGUIWindow::OnEditChanged(), CGUIDialogKeyboardGeneric::OnMessage(), CGUIDialogNumeric::OnMessage(), CGUIButtonControl::OnMessage(), CGUIEditControl::OnMessage(), CGUIFadeLabelControl::OnMessage(), CGUIImage::OnMessage(), CGUILabelControl::OnMessage(), CGUISpinControl::OnMessage(), CGUITextBox::OnMessage(), and CGUIWindowMusicNav::OnMessage().
GetMessage()
int CGUIMessage::GetMessage () const
References m_message.
Referenced by CGUIControl::OnMessage(), XBMCAddon::xbmcgui::Window::OnMessage(), CGUIDialogAddonInfo::OnMessage(), CGUIDialogAddonSettings::OnMessage(), CGUIWindowAddonBrowser::OnMessage(), ADDON::CGUIAddonWindow::OnMessage(), CApplication::OnMessage(), KODI::RETRO::CGameWindowFullScreen::OnMessage(), CGUIDialogBoxBase::OnMessage(), CGUIDialogButtonMenu::OnMessage(), CGUIDialogColorPicker::OnMessage(), CGUIDialogContextMenu::OnMessage(), CGUIDialogExtendedProgressBar::OnMessage(), CGUIDialogFileBrowser::OnMessage(), CGUIDialogGamepad::OnMessage(), CGUIDialogKaiToast::OnMessage(), CGUIDialogKeyboardGeneric::OnMessage(), CGUIDialogMediaFilter::OnMessage(), CGUIDialogMediaSource::OnMessage(), CGUIDialogNumeric::OnMessage(), CGUIDialogOK::OnMessage(), CGUIDialogPlayEject::OnMessage(), CGUIDialogProgress::OnMessage(), CGUIDialogSeekBar::OnMessage(), CGUIDialogSelect::OnMessage(), CGUIDialogSlider::OnMessage(), CGUIDialogSmartPlaylistEditor::OnMessage(), CGUIDialogSmartPlaylistRule::OnMessage(), CGUIDialogSubMenu::OnMessage(), CGUIDialogTextViewer::OnMessage(), CGUIDialogVolumeBar::OnMessage(), CGUIDialogYesNo::OnMessage(), CGUIWindowEventLog::OnMessage(), CGUIWindowFavourites::OnMessage(), KODI::GAME::CGUIAgentWindow::OnMessage(), KODI::GAME::CGUIControllerWindow::OnMessage(), KODI::GAME::CDialogGameAdvancedSettings::OnMessage(), KODI::GAME::CDialogGameSaves::OnMessage(), KODI::GAME::CDialogGameVideoSelect::OnMessage(), KODI::GAME::CDialogGameVolume::OnMessage(), KODI::GAME::CDialogInGameSaves::OnMessage(), KODI::GAME::CGUIPortWindow::OnMessage(), KODI::GAME::CGUIWindowGames::OnMessage(), CGUIBaseContainer::OnMessage(), CGUIButtonControl::OnMessage(), CGUIControlGroup::OnMessage(), CGUIControlGroupList::OnMessage(), CGUIDialog::OnMessage(), CGUIEditControl::OnMessage(), CGUIFadeLabelControl::OnMessage(), GUIFontManager::OnMessage(), CGUIImage::OnMessage(), CGUILabelControl::OnMessage(), CGUIListContainer::OnMessage(), CGUIMultiImage::OnMessage(), CGUIPanelContainer::OnMessage(), CGUIProgressControl::OnMessage(), GUIScrollBarControl::OnMessage(), CGUISliderControl::OnMessage(), CGUISpinControl::OnMessage(), CGUITextBox::OnMessage(), CGUIVisualisationControl::OnMessage(), CGUIWindow::OnMessage(), CGUIWrappingListContainer::OnMessage(), CStereoscopicsManager::OnMessage(), XBMCAddon::xbmcgui::WindowDialog::OnMessage(), XBMCAddon::xbmcgui::WindowXML::OnMessage(), XBMCAddon::xbmcgui::WindowXMLDialog::OnMessage(), CGUIDialogMusicInfo::OnMessage(), CGUIDialogMusicOSD::OnMessage(), CGUIDialogSongInfo::OnMessage(), CGUIDialogVisualisationPresetList::OnMessage(), CGUIWindowMusicBase::OnMessage(), CGUIWindowMusicNav::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowMusicPlaylistEditor::OnMessage(), CGUIWindowVisualisation::OnMessage(), CGUIDialogNetworkSetup::OnMessage(), PERIPHERALS::CGUIDialogPeripherals::OnMessage(), PERIPHERALS::CGUIDialogPeripheralSettings::OnMessage(), CGUIWindowPictures::OnMessage(), CGUIWindowSlideShow::OnMessage(), KODI::PLAYLIST::CPlayListPlayer::OnMessage(), CGUIWindowSettingsProfile::OnMessage(), CGUIWindowPrograms::OnMessage(), PVR::CGUIDialogPVRChannelManager::OnMessage(), PVR::CGUIDialogPVRChannelsOSD::OnMessage(), PVR::CGUIDialogPVRGroupManager::OnMessage(), PVR::CGUIDialogPVRGuideInfo::OnMessage(), PVR::CGUIDialogPVRGuideSearch::OnMessage(), PVR::CGUIDialogPVRRadioRDSInfo::OnMessage(), PVR::CGUIDialogPVRRecordingInfo::OnMessage(), PVR::CGUIEPGGridContainer::OnMessage(), PVR::CGUIWindowPVRBase::OnMessage(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CGUIWindowPVRGuideBase::OnMessage(), PVR::CGUIWindowPVRProvidersBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), PVR::CGUIWindowPVRSearchBase::OnMessage(), PVR::CGUIWindowPVRTimersBase::OnMessage(), CGUIDialogLibExportSettings::OnMessage(), CGUIDialogSettingsBase::OnMessage(), CGUIWindowSettingsCategory::OnMessage(), CGUIWindowSettingsScreenCalibration::OnMessage(), CGUIDialogSubtitles::OnMessage(), CGUIDialogSubtitleSettings::OnMessage(), CGUIDialogTeletext::OnMessage(), CGUIDialogVideoBookmarks::OnMessage(), CGUIDialogVideoInfo::OnMessage(), CGUIDialogVideoManager::OnMessage(), CGUIDialogVideoManagerExtras::OnMessage(), CGUIDialogVideoManagerVersions::OnMessage(), CGUIDialogVideoOSD::OnMessage(), CGUIWindowFullScreen::OnMessage(), CGUIWindowVideoBase::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), CGUIWindowWeather::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIWindowDebugInfo::OnMessage(), CGUIWindowFileManager::OnMessage(), CGUIWindowHome::OnMessage(), CGUIWindowLoginScreen::OnMessage(), CGUIWindowScreensaver::OnMessage(), CGUIWindowSystemInfo::OnMessage(), and CGUIWindowManager::SendMessage().
GetNumStringParams()
size_t CGUIMessage::GetNumStringParams () const
References m_params.
Referenced by CGUIWindowAddonBrowser::OnMessage(), CApplication::OnMessage(), CGUIWindowMusicPlaylistEditor::OnMessage(), CGUIWindowVideoNav::OnMessage(), and CGUIMediaWindow::OnMessage().
GetParam1()
int CGUIMessage::GetParam1 () const
References m_param1.
Referenced by PVR::CGUIDialogPVRGroupManager::ActionButtonChannelGroups(), PVR::CGUIDialogPVRGroupManager::ActionButtonGroupMembers(), PVR::CGUIDialogPVRGroupManager::ActionButtonUngroupedChannels(), CGUIWindow::ControlGroupHasFocus(), CGUIWindowMusicPlaylistEditor::GetCurrentPlaylistItem(), PVR::CGUIPVRChannelGroupsSelector::GetSelectedChannelGroup(), CGUIDialogMediaSource::GetSelectedItem(), CGUIDialogSmartPlaylistEditor::GetSelectedItem(), XBMCAddon::xbmcgui::ControlList::getSelectedItem(), CGUIWindowSettingsProfile::GetSelectedItem(), CGUIViewControl::GetSelectedItem(), CGUIWindowFileManager::GetSelectedItem(), XBMCAddon::xbmcgui::ControlList::getSelectedPosition(), PVR::CGUIDialogPVRGuideSearch::GetSpinValue(), PVR::CGUIDialogPVRGuideSearch::IsRadioSelected(), PVR::CGUIDialogPVRChannelManager::OnClickButtonRadioActive(), PVR::CGUIDialogPVRChannelManager::OnClickButtonRadioParentalLocked(), PVR::CGUIDialogPVRChannelManager::OnClickButtonUseEPG(), PVR::CGUIDialogPVRChannelManager::OnClickListChannels(), XBMCAddon::xbmcgui::Window::OnMessage(), CGUIDialogAddonInfo::OnMessage(), CGUIDialogAddonSettings::OnMessage(), CGUIWindowAddonBrowser::OnMessage(), ADDON::CGUIAddonWindow::OnMessage(), CApplication::OnMessage(), CGUIDialogColorPicker::OnMessage(), CGUIDialogFileBrowser::OnMessage(), CGUIDialogKeyboardGeneric::OnMessage(), CGUIDialogMediaSource::OnMessage(), CGUIDialogNumeric::OnMessage(), CGUIDialogSelect::OnMessage(), CGUIDialogSmartPlaylistEditor::OnMessage(), CGUIDialogSmartPlaylistRule::OnMessage(), CGUIDialogTextViewer::OnMessage(), CGUIDialogYesNo::OnMessage(), CGUIWindowEventLog::OnMessage(), KODI::GAME::CGUIAgentWindow::OnMessage(), KODI::GAME::CDialogGameSaves::OnMessage(), KODI::GAME::CDialogGameVideoSelect::OnMessage(), KODI::GAME::CGUIPortWindow::OnMessage(), KODI::GAME::CGUIWindowGames::OnMessage(), CGUIBaseContainer::OnMessage(), CGUIControlGroup::OnMessage(), CGUIControlGroupList::OnMessage(), CGUIEditControl::OnMessage(), GUIFontManager::OnMessage(), CGUIProgressControl::OnMessage(), GUIScrollBarControl::OnMessage(), CGUISliderControl::OnMessage(), CGUISpinControl::OnMessage(), CGUITextBox::OnMessage(), CGUIWindow::OnMessage(), CGUIWrappingListContainer::OnMessage(), XBMCAddon::xbmcgui::WindowXML::OnMessage(), CGUIDialogMusicInfo::OnMessage(), CGUIDialogSongInfo::OnMessage(), CGUIWindowMusicBase::OnMessage(), CGUIWindowMusicNav::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowMusicPlaylistEditor::OnMessage(), CGUIWindowVisualisation::OnMessage(), CGUIWindowPictures::OnMessage(), CGUIWindowSlideShow::OnMessage(), KODI::PLAYLIST::CPlayListPlayer::OnMessage(), CGUIWindowSettingsProfile::OnMessage(), CGUIWindowPrograms::OnMessage(), PVR::CGUIDialogPVRChannelsOSD::OnMessage(), PVR::CGUIEPGGridContainer::OnMessage(), PVR::CGUIWindowPVRBase::OnMessage(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CGUIWindowPVRGuideBase::OnMessage(), PVR::CGUIWindowPVRProvidersBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), PVR::CGUIWindowPVRSearchBase::OnMessage(), PVR::CGUIWindowPVRTimersBase::OnMessage(), CGUIDialogSettingsBase::OnMessage(), CGUIWindowSettingsCategory::OnMessage(), CGUIWindowSettingsScreenCalibration::OnMessage(), CGUIDialogSubtitles::OnMessage(), CGUIDialogTeletext::OnMessage(), CGUIDialogVideoBookmarks::OnMessage(), CGUIDialogVideoInfo::OnMessage(), CGUIDialogVideoManager::OnMessage(), CGUIWindowFullScreen::OnMessage(), CGUIWindowVideoBase::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), CGUIWindowWeather::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIWindowFileManager::OnMessage(), CGUIWindowHome::OnMessage(), CGUIWindowLoginScreen::OnMessage(), CGUIDialogNetworkSetup::OnProtocolChange(), CGUIDialogAddonInfo::OnToggleAutoUpdates(), anonymous_namespace{ContextMenus.cpp}::SelectNextItem(), and CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::SelectNextItem().
GetParam1AsI64()
int64_t CGUIMessage::GetParam1AsI64 () const
References m_param1.
Referenced by CApplication::OnMessage().
GetParam2()
int CGUIMessage::GetParam2 () const
References m_param2.
Referenced by CGUIDialogKeyboardGeneric::OnMessage(), CGUIBaseContainer::OnMessage(), CGUIEditControl::OnMessage(), GUIScrollBarControl::OnMessage(), CGUISpinControl::OnMessage(), CGUIWindow::OnMessage(), CGUIDialogSettingsBase::OnMessage(), CGUIWindowSettingsCategory::OnMessage(), CGUIMediaWindow::OnMessage(), and CGUIWindowHome::OnMessage().
GetParam2AsI64()
int64_t CGUIMessage::GetParam2AsI64 () const
References m_param2.
Referenced by CApplication::OnMessage().
GetPointer()
void * CGUIMessage::GetPointer () const
References m_pointer.
Referenced by CInertialScrollingHandler::CheckForInertialScrolling(), KODI::GUILIB::GUIINFO::CVisualisationGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CVisualisationGUIInfo::GetLabel(), CGUIDialogVisualisationPresetList::OnInitWindow(), CGUIBaseContainer::OnMessage(), CGUISpinControl::OnMessage(), CGUIWindow::OnMessage(), and CGenericTouchActionHandler::QuerySupportedGestures().
GetSenderId()
int CGUIMessage::GetSenderId () const
References m_senderID.
Referenced by PVR::CGUIDialogPVRGroupManager::ActionButtonChannelGroups(), PVR::CGUIDialogPVRGroupManager::ActionButtonDeleteGroup(), PVR::CGUIDialogPVRGroupManager::ActionButtonGroupMembers(), PVR::CGUIDialogPVRGroupManager::ActionButtonHideGroup(), PVR::CGUIDialogPVRGroupManager::ActionButtonNewGroup(), PVR::CGUIDialogPVRGroupManager::ActionButtonOk(), PVR::CGUIDialogPVRGroupManager::ActionButtonRecreateThumbnail(), PVR::CGUIDialogPVRGroupManager::ActionButtonRenameGroup(), PVR::CGUIDialogPVRGroupManager::ActionButtonToggleRadioTV(), PVR::CGUIDialogPVRGroupManager::ActionButtonUngroupedChannels(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonAddTimer(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonFind(), PVR::CGUIDialogPVRRecordingInfo::OnClickButtonFind(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonOK(), PVR::CGUIDialogPVRRecordingInfo::OnClickButtonOK(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonPlay(), PVR::CGUIDialogPVRRecordingInfo::OnClickButtonPlay(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonRecord(), PVR::CGUIDialogPVRGuideInfo::OnClickButtonSetReminder(), XBMCAddon::xbmcgui::Window::OnMessage(), CGUIDialogAddonInfo::OnMessage(), CGUIDialogAddonSettings::OnMessage(), CGUIWindowAddonBrowser::OnMessage(), ADDON::CGUIAddonWindow::OnMessage(), CApplication::OnMessage(), KODI::RETRO::CGameWindowFullScreen::OnMessage(), CGUIDialogColorPicker::OnMessage(), CGUIDialogContextMenu::OnMessage(), CGUIDialogFileBrowser::OnMessage(), CGUIDialogKeyboardGeneric::OnMessage(), CGUIDialogMediaFilter::OnMessage(), CGUIDialogMediaSource::OnMessage(), CGUIDialogNumeric::OnMessage(), CGUIDialogOK::OnMessage(), CGUIDialogPlayEject::OnMessage(), CGUIDialogProgress::OnMessage(), CGUIDialogSeekBar::OnMessage(), CGUIDialogSelect::OnMessage(), CGUIDialogSlider::OnMessage(), CGUIDialogSmartPlaylistEditor::OnMessage(), CGUIDialogSmartPlaylistRule::OnMessage(), CGUIDialogYesNo::OnMessage(), CGUIWindowEventLog::OnMessage(), KODI::GAME::CGUIAgentWindow::OnMessage(), KODI::GAME::CGUIControllerWindow::OnMessage(), KODI::GAME::CDialogGameSaves::OnMessage(), KODI::GAME::CDialogGameVideoSelect::OnMessage(), KODI::GAME::CGUIPortWindow::OnMessage(), KODI::GAME::CGUIWindowGames::OnMessage(), CGUIBaseContainer::OnMessage(), CGUIControlGroup::OnMessage(), CGUIControlGroupList::OnMessage(), CGUITextBox::OnMessage(), CGUIWindow::OnMessage(), CGUIWrappingListContainer::OnMessage(), XBMCAddon::xbmcgui::WindowXML::OnMessage(), CGUIDialogMusicInfo::OnMessage(), CGUIDialogMusicOSD::OnMessage(), CGUIDialogSongInfo::OnMessage(), CGUIWindowMusicBase::OnMessage(), CGUIWindowMusicNav::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowMusicPlaylistEditor::OnMessage(), CGUIDialogNetworkSetup::OnMessage(), PERIPHERALS::CGUIDialogPeripheralSettings::OnMessage(), CGUIWindowPictures::OnMessage(), CGUIWindowSettingsProfile::OnMessage(), CGUIWindowPrograms::OnMessage(), PVR::CGUIDialogPVRGuideSearch::OnMessage(), PVR::CGUIDialogPVRRadioRDSInfo::OnMessage(), PVR::CGUIEPGGridContainer::OnMessage(), PVR::CGUIWindowPVRBase::OnMessage(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CGUIWindowPVRGuideBase::OnMessage(), PVR::CGUIWindowPVRProvidersBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), PVR::CGUIWindowPVRSearchBase::OnMessage(), PVR::CGUIWindowPVRTimersBase::OnMessage(), CGUIDialogLibExportSettings::OnMessage(), CGUIDialogSettingsBase::OnMessage(), CGUIWindowSettingsScreenCalibration::OnMessage(), CGUIDialogSubtitles::OnMessage(), CGUIDialogVideoBookmarks::OnMessage(), CGUIDialogVideoInfo::OnMessage(), CGUIDialogVideoManager::OnMessage(), CGUIDialogVideoManagerExtras::OnMessage(), CGUIDialogVideoManagerVersions::OnMessage(), CGUIWindowFullScreen::OnMessage(), CGUIWindowVideoBase::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), CGUIWindowWeather::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIWindowFileManager::OnMessage(), CGUIWindowHome::OnMessage(), CGUIWindowLoginScreen::OnMessage(), PVR::CGUIDialogPVRChannelManager::OnMessageClick(), and CGUIWindowManager::SendMessage().
GetStringParam()
const std::string & CGUIMessage::GetStringParam (size_t param = 0) const
References empty_string, and m_params.
Referenced by CGUIDialogAddonSettings::OnMessage(), CGUIWindowAddonBrowser::OnMessage(), CApplication::OnMessage(), CGUIDialogFileBrowser::OnMessage(), CGUIDialogKeyboardGeneric::OnMessage(), CGUIDialogSmartPlaylistEditor::OnMessage(), KODI::GAME::CGUIControllerWindow::OnMessage(), KODI::GAME::CDialogInGameSaves::OnMessage(), KODI::GAME::CGUIWindowGames::OnMessage(), CGUIWindowMusicBase::OnMessage(), CGUIWindowMusicNav::OnMessage(), CGUIWindowMusicPlaylistEditor::OnMessage(), CGUIWindowPictures::OnMessage(), CGUIWindowSlideShow::OnMessage(), CGUIWindowPrograms::OnMessage(), PVR::CGUIWindowPVRChannelsBase::OnMessage(), PVR::CGUIWindowPVRGuideBase::OnMessage(), PVR::CGUIWindowPVRSearchBase::OnMessage(), CGUIWindowSettingsCategory::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIMediaWindow::OnMessage(), and CGUIWindowFileManager::OnMessage().
operator=()
CGUIMessage & CGUIMessage::operator= (const CGUIMessage & msg) default
SetItem()
void CGUIMessage::SetItem (std::shared_ptr< CGUIListItem > item)
References m_item.
Referenced by KODI::RETRO::CGUIGameMessenger::RefreshSavestates().
SetLabel() [1/2]
void CGUIMessage::SetLabel (const std::string & strLabel)
References m_strLabel.
Referenced by ADDON::Interface_GUIControlFadeLabel::add_label(), XBMCAddon::xbmcgui::ControlFadeLabel::addLabel(), XBMCAddon::xbmcgui::ControlEdit::Create(), XBMCAddon::xbmcgui::ControlTextBox::Create(), KODI::GAME::CGUIFeatureButton::DoPrompt(), CGUIWindowFullScreen::FrameMove(), KODI::GAME::CDialogGameSaves::HandleCaption(), KODI::GAME::CDialogGameSaves::HandleGameClient(), KODI::GAME::CDialogGameVideoSelect::OnDescriptionChange(), KODI::GAME::CGUIControllerList::OnFocus(), KODI::GAME::CDialogGameOSDHelp::OnInitWindow(), KODI::GAME::CDialogGameSaves::OnInitWindow(), CGUIDialogKeyboardGeneric::OnMessage(), CGUIEditControl::OnMessage(), CGUIImage::OnMessage(), CGUISpinControl::OnMessage(), CSpeechRecognitionListener::OnResults(), JSONRPC::CInputOperations::SendText(), ADDON::Interface_GUIWindow::set_control_label(), ADDON::Interface_GUIControlLabel::set_label(), ADDON::Interface_GUIControlSettingsSlider::set_text(), ADDON::Interface_GUIControlSpin::set_text(), ADDON::Interface_GUIControlTextBox::set_text(), CGUIDialogKeyboardGeneric::SetControlLabel(), CGUIDialogKeyboardGeneric::SetEditText(), CGUIDialogTextViewer::SetHeading(), CGUIDialogNumeric::SetHeading(), XBMCAddon::xbmcgui::ControlLabel::setLabel(), XBMCAddon::xbmcgui::ControlEdit::setLabel(), CGUIDialogTextViewer::SetText(), XBMCAddon::xbmcgui::ControlEdit::setText(), XBMCAddon::xbmcgui::ControlTextBox::setText(), and CGUIViewControl::UpdateViewAsControl().
SetLabel() [2/2]
void CGUIMessage::SetLabel (int iString)
References g_localizeStrings, CLocalizeStrings::Get(), and m_strLabel.
SetParam1()
void CGUIMessage::SetParam1 (int64_t param1)
References m_param1.
Referenced by CGUIKeyboardFactory::keyTypedCB(), CGUIBaseContainer::OnMessage(), CGUIButtonControl::OnMessage(), CGUIControlGroup::OnMessage(), CGUISpinControl::OnMessage(), CGUIWrappingListContainer::OnMessage(), PVR::CGUIWindowPVRGuideBase::OnMessage(), JSONRPC::CInputOperations::SendText(), ADDON::Interface_Base::UpdateSettingInActiveDialog(), and XBMCAddon::xbmcaddon::Addon::UpdateSettingInActiveDialog().
SetParam2()
void CGUIMessage::SetParam2 (int64_t param2)
References m_param2.
Referenced by CGUISpinControl::OnMessage(), and Update().
SetPointer()
void CGUIMessage::SetPointer (void * pointer)
References m_pointer.
Referenced by CInertialScrollingHandler::CheckForInertialScrolling(), XBMCAddon::xbmcgui::Window::doAddControl(), XBMCAddon::xbmcgui::Window::doRemoveControl(), CGUIVisualisationControl::OnMessage(), CGUIWindow::OnMessage(), CGenericTouchActionHandler::QuerySupportedGestures(), XBMCAddon::xbmcgui::ControlList::sendLabelBind(), and CGUIViewControl::UpdateViewAsControl().
SetStringParam()
void CGUIMessage::SetStringParam (const std::string & strParam)
References m_params.
Referenced by CGUISourcesAnnouncementHandler::Announce(), CZeroconfBrowserAvahi::browseCallback(), CZeroconfBrowserAvahi::clientCallback(), CONTEXTMENU::CMusicBrowse::Execute(), CONTEXTMENU::CVideoBrowse::Execute(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::ExecuteAction(), FAVOURITES_UTILS::anonymous_namespace{FavouritesUtils.cpp}::ExecuteAction(), anonymous_namespace{DirectoryProvider.cpp}::ExecuteAction(), CGUIAction::ExecuteActions(), CInputCodingTableBasePY::GetWordListPage(), CGUIKeyboardFactory::keyTypedCB(), CGUIMediaWindow::OnAction(), OnDirectoryScanned(), KODI::VIDEO::OnDirectoryScanned(), KODI::GAME::CGUIAgentControllerList::OnEvent(), KODI::GAME::CGUIControllerList::OnEvent(), KODI::GAME::CGUIActivePortList::OnEvent(), KODI::GAME::CGUIPortList::OnEvent(), ADDON::CAddonInstaller::OnJobProgress(), KODI::GAME::CGUIWindowGames::OnMessage(), CGUIWindowMusicNav::OnMessage(), CGUIWindowPictures::OnMessage(), CGUIWindowPrograms::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIWindowFileManager::OnMessage(), CGUIDialog::Open_Internal(), CGUIDialogVideoInfo::Play(), Refresh(), KODI::RETRO::CGUIGameMessenger::RefreshSavestates(), CGUISliderControl::SendClick(), Show(), and Update().
SetStringParams()
void CGUIMessage::SetStringParams (const std::vector< std::string > & params)
References m_params.
Referenced by Slideshow(), JSONRPC::CPlayerOperations::StartSlideshow(), ADDON::Interface_Base::UpdateSettingInActiveDialog(), and XBMCAddon::xbmcaddon::Addon::UpdateSettingInActiveDialog().
Member Data Documentation
empty_string
std::string CGUIMessage::empty_string static private
Referenced by GetStringParam().
m_controlID
int CGUIMessage::m_controlID private
Referenced by CGUIMessage(), CGUIMessage(), CGUIMessage(), and GetControlId().
m_item
std::shared_ptr<CGUIListItem> CGUIMessage::m_item private
Referenced by GetItem(), and SetItem().
m_message
int CGUIMessage::m_message private
Referenced by CGUIMessage(), CGUIMessage(), CGUIMessage(), and GetMessage().
m_param1
int64_t CGUIMessage::m_param1 private
Referenced by CGUIMessage(), CGUIMessage(), CGUIMessage(), GetParam1(), GetParam1AsI64(), and SetParam1().
m_param2
int64_t CGUIMessage::m_param2 private
Referenced by CGUIMessage(), CGUIMessage(), CGUIMessage(), GetParam2(), GetParam2AsI64(), and SetParam2().
m_params
std::vector<std::string> CGUIMessage::m_params private
Referenced by GetNumStringParams(), GetStringParam(), SetStringParam(), and SetStringParams().
m_pointer
void* CGUIMessage::m_pointer private
Referenced by CGUIMessage(), CGUIMessage(), CGUIMessage(), GetPointer(), and SetPointer().
m_senderID
int CGUIMessage::m_senderID private
Referenced by CGUIMessage(), CGUIMessage(), CGUIMessage(), and GetSenderId().
m_strLabel
std::string CGUIMessage::m_strLabel private
Referenced by GetLabel(), SetLabel(), and SetLabel().
The documentation for this class was generated from the following files:
GUIMessage.h
GUIMessage.cpp