Kodi Documentation: KODI::RETRO::CSavestateDatabase Class Reference
KODI::RETRO::CSavestateDatabase Class Reference
#include <SavestateDatabase.h>
Public Member Functions
CSavestateDatabase ()
virtual ~CSavestateDatabase ()=default
bool AddSavestate (const std::string &savestatePath, const std::string &gamePath, const ISavestate &save)
bool GetSavestate (const std::string &savestatePath, ISavestate &save)
bool GetSavestatesNav (CFileItemList &items, const std::string &gamePath, const std::string &gameClient="")
std::unique_ptr< ISavestate > RenameSavestate (const std::string &savestatePath, const std::string &label)
bool DeleteSavestate (const std::string &savestatePath)
bool ClearSavestatesOfGame (const std::string &gamePath, const std::string &gameClient="")
Static Public Member Functions
static std::unique_ptr< ISavestate > AllocateSavestate ()
static void GetSavestateItem (const ISavestate &savestate, const std::string &savestatePath, CFileItem &item)
static std::string MakeSavestatePath (const std::string &gamePath, const CDateTime &creationTime)
static std::string MakeThumbnailPath (const std::string &savestatePath)
Static Private Member Functions
static std::string MakePath (const std::string &gamePath)
static bool CreateFolderIfNotExists (const std::string &path)
Constructor & Destructor Documentation
CSavestateDatabase()
CSavestateDatabase::CSavestateDatabase () default
~CSavestateDatabase()
virtual KODI::RETRO::CSavestateDatabase::~CSavestateDatabase () virtual default
Member Function Documentation
AddSavestate()
bool CSavestateDatabase::AddSavestate (const std::string & savestatePath, const std::string & gamePath, const ISavestate & save)
References KODI::RETRO::ISavestate::Created(), data(), CLog::Log(), LOGDEBUG, LOGERROR, MakeSavestatePath(), KODI::RETRO::ISavestate::Serialize(), and XFILE::CFile::Write().
Referenced by RenameSavestate().
AllocateSavestate()
std::unique_ptr< ISavestate > CSavestateDatabase::AllocateSavestate () static
References savestate.
Referenced by KODI::RETRO::CReversiblePlayback::CommitSavestate(), KODI::GAME::CGameUtils::FillInGameClient(), GetSavestatesNav(), KODI::RETRO::CReversiblePlayback::LoadSavestate(), KODI::RETRO::CRPRenderManager::LoadVideoFrameSync(), KODI::GAME::CDialogInGameSaves::OnNewSave(), KODI::GAME::CDialogInGameSaves::OnOverwrite(), KODI::GAME::CDialogInGameSaves::OnRename(), KODI::GAME::CDialogGameSaves::OnRename(), KODI::RETRO::CRetroPlayer::OpenFile(), RenameSavestate(), and KODI::GAME::CDialogInGameSaves::TranslateMessageItem().
ClearSavestatesOfGame()
bool CSavestateDatabase::ClearSavestatesOfGame (const std::string & gamePath, const std::string & gameClient = "")
Todo:
CreateFolderIfNotExists()
bool CSavestateDatabase::CreateFolderIfNotExists (const std::string & path) static private
References XFILE::CDirectory::Create(), XFILE::CDirectory::Exists(), CLog::Log(), and LOGERROR.
Referenced by MakePath().
DeleteSavestate()
bool CSavestateDatabase::DeleteSavestate (const std::string & savestatePath)
References XFILE::CFile::Delete(), CLog::Log(), LOGERROR, and MakeThumbnailPath().
Referenced by KODI::GAME::CDialogInGameSaves::OnDelete(), and KODI::GAME::CDialogGameSaves::OnDelete().
GetSavestate()
bool CSavestateDatabase::GetSavestate (const std::string & savestatePath, ISavestate & save)
References KODI::RETRO::ISavestate::Deserialize(), XFILE::CFile::GetLength(), int64_t(), CLog::Log(), LOGDEBUG, LOGERROR, XFILE::CFile::Open(), XFILE::CFile::Read(), and XFILE::READ_TRUNCATED.
Referenced by KODI::GAME::CGameUtils::FillInGameClient(), GetSavestatesNav(), KODI::RETRO::CRPRenderManager::LoadVideoFrameSync(), KODI::GAME::CDialogInGameSaves::OnRename(), KODI::GAME::CDialogGameSaves::OnRename(), KODI::RETRO::CRetroPlayer::OpenFile(), RenameSavestate(), and KODI::GAME::CDialogInGameSaves::TranslateMessageItem().
GetSavestateItem()
void CSavestateDatabase::GetSavestateItem (const ISavestate & savestate, const std::string & savestatePath, CFileItem & item) static
References KODI::RETRO::AUTO, CDateTime::FromUTCDateTime(), g_localizeStrings, CLocalizeStrings::Get(), CDateTime::GetAsLocalizedDateTime(), label, CFileItem::m_dateTime, MakeThumbnailPath(), savestate, SAVESTATE_CAPTION, SAVESTATE_GAME_CLIENT, SAVESTATE_LABEL, CGUIListItem::SetArt(), CFileItem::SetLabel(), CGUIListItem::SetLabel2(), CFileItem::SetPath(), and CGUIListItem::SetProperty().
Referenced by GetSavestatesNav(), KODI::GAME::CDialogInGameSaves::OnNewSave(), KODI::GAME::CDialogInGameSaves::OnOverwrite(), KODI::GAME::CDialogInGameSaves::OnRename(), KODI::GAME::CDialogGameSaves::OnRename(), KODI::RETRO::CGUIGameMessenger::RefreshSavestates(), and KODI::GAME::CDialogInGameSaves::TranslateMessageItem().
GetSavestatesNav()
bool CSavestateDatabase::GetSavestatesNav (CFileItemList & items, const std::string & gamePath, const std::string & gameClient = "")
References AllocateSavestate(), XFILE::CDirectory::GetDirectory(), GetSavestate(), GetSavestateItem(), MakePath(), XFILE::CDirectory::CHints::mask, CFileItemList::Remove(), savestate, and CFileItemList::Size().
Referenced by KODI::GAME::CDialogInGameSaves::InitSavedGames(), and KODI::GAME::CDialogGameSaves::Open().
MakePath()
std::string CSavestateDatabase::MakePath (const std::string & gamePath) static private
References URIUtils::AddFileToFolder(), CreateFolderIfNotExists(), and URIUtils::GetFileName().
Referenced by GetSavestatesNav(), and MakeSavestatePath().
MakeSavestatePath()
std::string CSavestateDatabase::MakeSavestatePath (const std::string & gamePath, const CDateTime & creationTime) static
References URIUtils::AddFileToFolder(), CDateTime::GetAsSaveString(), and MakePath().
Referenced by AddSavestate(), and KODI::RETRO::CReversiblePlayback::CreateSavestate().
MakeThumbnailPath()
std::string CSavestateDatabase::MakeThumbnailPath (const std::string & savestatePath) static
References URIUtils::ReplaceExtension().
Referenced by KODI::RETRO::CReversiblePlayback::CommitSavestate(), DeleteSavestate(), and GetSavestateItem().
RenameSavestate()
std::unique_ptr< ISavestate > CSavestateDatabase::RenameSavestate (const std::string & savestatePath, const std::string & label)
References AddSavestate(), AllocateSavestate(), GetSavestate(), label, and savestate.
Referenced by KODI::GAME::CDialogInGameSaves::OnRename(), and KODI::GAME::CDialogGameSaves::OnRename().
The documentation for this class was generated from the following files:
SavestateDatabase.h
SavestateDatabase.cpp