Kodi Documentation: KODI::KEYMAP::CGamepadTranslator Class Reference
KODI::KEYMAP::CGamepadTranslator Class Reference
Gamepad translator, only used by EventClient.
#include <GamepadTranslator.h>
Static Public Member Functions
static uint32_t TranslateString (std::string strButton)
Detailed Description
Gamepad translator, only used by EventClient.
The legacy gamepad translator uses an original Xbox controller (the one with white and black buttons) for mapping.
Member Function Documentation
TranslateString()
uint32_t CGamepadTranslator::TranslateString (std::string strButton) static
References KEY_BUTTON_A, KEY_BUTTON_B, KEY_BUTTON_BACK, KEY_BUTTON_BLACK, KEY_BUTTON_DPAD_DOWN, KEY_BUTTON_DPAD_LEFT, KEY_BUTTON_DPAD_RIGHT, KEY_BUTTON_DPAD_UP, KEY_BUTTON_LEFT_ANALOG_TRIGGER, KEY_BUTTON_LEFT_THUMB_BUTTON, KEY_BUTTON_LEFT_THUMB_STICK, KEY_BUTTON_LEFT_THUMB_STICK_DOWN, KEY_BUTTON_LEFT_THUMB_STICK_LEFT, KEY_BUTTON_LEFT_THUMB_STICK_RIGHT, KEY_BUTTON_LEFT_THUMB_STICK_UP, KEY_BUTTON_LEFT_TRIGGER, KEY_BUTTON_RIGHT_ANALOG_TRIGGER, KEY_BUTTON_RIGHT_THUMB_BUTTON, KEY_BUTTON_RIGHT_THUMB_STICK, KEY_BUTTON_RIGHT_THUMB_STICK_DOWN, KEY_BUTTON_RIGHT_THUMB_STICK_LEFT, KEY_BUTTON_RIGHT_THUMB_STICK_RIGHT, KEY_BUTTON_RIGHT_THUMB_STICK_UP, KEY_BUTTON_RIGHT_TRIGGER, KEY_BUTTON_START, KEY_BUTTON_WHITE, KEY_BUTTON_X, KEY_BUTTON_Y, CLog::Log(), and LOGERROR.
Referenced by KODI::KEYMAP::CButtonTranslator::MapWindowActions(), and KODI::KEYMAP::CButtonTranslator::TranslateString().
The documentation for this class was generated from the following files:
GamepadTranslator.h
GamepadTranslator.cpp