Kodi Documentation: android_main.cpp File Reference
android_main.cpp File Reference
#include "EventLoop.h"
#include "XBMCApp.h"
#include "platform/android/activity/JNIMainActivity.h"
#include "platform/android/activity/JNIXBMCAudioManagerOnAudioFocusChangeListener.h"
#include "platform/android/activity/JNIXBMCBroadcastReceiver.h"
#include "platform/android/activity/JNIXBMCConnectivityManagerNetworkCallback.h"
#include "platform/android/activity/JNIXBMCDisplayManagerDisplayListener.h"
#include "platform/android/activity/JNIXBMCFile.h"
#include "platform/android/activity/JNIXBMCJsonHandler.h"
#include "platform/android/activity/JNIXBMCMainView.h"
#include "platform/android/activity/JNIXBMCMediaSession.h"
#include "platform/android/activity/JNIXBMCNsdManagerDiscoveryListener.h"
#include "platform/android/activity/JNIXBMCNsdManagerRegistrationListener.h"
#include "platform/android/activity/JNIXBMCNsdManagerResolveListener.h"
#include "platform/android/activity/JNIXBMCSpeechRecognitionListener.h"
#include "platform/android/activity/JNIXBMCSurfaceTextureOnFrameAvailableListener.h"
#include "platform/android/activity/JNIXBMCTextureCache.h"
#include "platform/android/activity/JNIXBMCURIUtils.h"
#include "platform/android/activity/JNIXBMCVideoView.h"
#include <stdint.h>
#include <stdio.h>
#include <thread>
#include <unistd.h>
Classes
class anonymous_namespace{android_main.cpp}::LogRedirector
Namespaces
namespace anonymous_namespace{android_main.cpp}
Functions
void android_main (struct android_app *state)
JNIEXPORT jint JNI_OnLoad (JavaVM *vm, void *reserved)
Variables
LogRedirector anonymous_namespace{android_main.cpp}::g_LogRedirector
Function Documentation
android_main()
void android_main (struct android_app * state) extern
References CXBMCApp::android_printf(), CXBMCApp::Create(), CXBMCApp::Destroy(), CXBMCApp::isValid(), CXBMCApp::Quit(), and CEventLoop::run().
JNI_OnLoad()
JNIEXPORT jint JNI_OnLoad (JavaVM * vm, void * reserved)
References jni::CJNIMainActivity::RegisterNatives(), jni::CJNIXBMCAudioManagerOnAudioFocusChangeListener::RegisterNatives(), jni::CJNIXBMCBroadcastReceiver::RegisterNatives(), jni::CJNIXBMCConnectivityManagerNetworkCallback::RegisterNatives(), jni::CJNIXBMCDisplayManagerDisplayListener::RegisterNatives(), jni::CJNIXBMCFile::RegisterNatives(), jni::CJNIXBMCJsonHandler::RegisterNatives(), jni::CJNIXBMCMainView::RegisterNatives(), jni::CJNIXBMCMediaSession::RegisterNatives(), jni::CJNIXBMCNsdManagerDiscoveryListener::RegisterNatives(), jni::CJNIXBMCNsdManagerRegistrationListener::RegisterNatives(), jni::CJNIXBMCNsdManagerResolveListener::RegisterNatives(), jni::CJNIXBMCSpeechRecognitionListener::RegisterNatives(), jni::CJNIXBMCSurfaceTextureOnFrameAvailableListener::RegisterNatives(), jni::CJNIXBMCTextureCache::RegisterNatives(), jni::CJNIXBMCURIUtils::RegisterNatives(), and jni::CJNIXBMCVideoView::RegisterNatives().