Kodi Documentation: CAESpinLock Class Reference
CAESpinLock Class Reference
#include <AEUtil.h>
Public Member Functions
CAESpinLock (CAESpinSection &section)
bool retry ()
Private Attributes
CAESpinSection & m_section
unsigned int m_begin
Constructor & Destructor Documentation
CAESpinLock()
CAESpinLock::CAESpinLock (CAESpinSection & section) inline explicit
Member Function Documentation
retry()
bool CAESpinLock::retry () inline
References m_begin, CAESpinSection::m_enter, CAESpinSection::m_leave, and m_section.
Referenced by CAAudioUnitSink::getDelay(), CAESinkDARWINOSX::GetDelay(), and CAAudioUnitSink::updatedelay().
Member Data Documentation
m_begin
unsigned int CAESpinLock::m_begin private
Referenced by retry().
m_section
CAESpinSection& CAESpinLock::m_section private
Referenced by retry().
The documentation for this class was generated from the following file:
AEUtil.h