Kodi Documentation: CLinuxStorageProvider Class Reference
CLinuxStorageProvider Class Reference
#include <LinuxStorageProvider.h>
Public Member Functions
CLinuxStorageProvider ()
~CLinuxStorageProvider () override
void Initialize () override
void Stop () override
void GetLocalDrives (std::vector< CMediaSource > &localDrives) override
void GetRemovableDrives (std::vector< CMediaSource > &removableDrives) override
bool Eject (const std::string &mountpath) override
std::vector< std::string > GetDiskUsage () override
bool PumpDriveChangeEvents (IStorageEventsCallback *callback) override
Public Member Functions inherited from IStorageProvider
virtual ~IStorageProvider ()=default
virtual std::string GetFirstOpticalDeviceFileName ()
Private Attributes
IStorageProvider * m_instance
Additional Inherited Members
Static Public Member Functions inherited from IStorageProvider
static std::unique_ptr< IStorageProvider > CreateInstance ()
Called by media manager to create platform storage provider.
Constructor & Destructor Documentation
CLinuxStorageProvider()
CLinuxStorageProvider::CLinuxStorageProvider ()
References CUDisksProvider::HasUDisks(), CUDisks2Provider::HasUDisks2(), and m_instance.
~CLinuxStorageProvider()
CLinuxStorageProvider::~CLinuxStorageProvider () override
References m_instance.
Member Function Documentation
Eject()
bool CLinuxStorageProvider::Eject (const std::string & mountpath) override virtual
Implements IStorageProvider.
References IStorageProvider::Eject(), and m_instance.
GetDiskUsage()
std::vector< std::string > CLinuxStorageProvider::GetDiskUsage (void) override virtual
Implements IStorageProvider.
References IStorageProvider::GetDiskUsage(), and m_instance.
GetLocalDrives()
void CLinuxStorageProvider::GetLocalDrives (std::vector< CMediaSource > & localDrives) override virtual
Implements IStorageProvider.
References g_localizeStrings, CLocalizeStrings::Get(), IStorageProvider::GetLocalDrives(), CMediaSource::m_iDriveType, CMediaSource::m_ignore, m_instance, CMediaSource::SOURCE_TYPE_LOCAL, CMediaSource::strName, and CMediaSource::strPath.
GetRemovableDrives()
void CLinuxStorageProvider::GetRemovableDrives (std::vector< CMediaSource > & removableDrives) override virtual
Implements IStorageProvider.
References IStorageProvider::GetRemovableDrives(), and m_instance.
Initialize()
void CLinuxStorageProvider::Initialize () override virtual
Implements IStorageProvider.
References IStorageProvider::Initialize(), and m_instance.
PumpDriveChangeEvents()
bool CLinuxStorageProvider::PumpDriveChangeEvents (IStorageEventsCallback * callback) override virtual
Implements IStorageProvider.
References m_instance, and IStorageProvider::PumpDriveChangeEvents().
Stop()
void CLinuxStorageProvider::Stop () override virtual
Implements IStorageProvider.
References m_instance, and IStorageProvider::Stop().
Member Data Documentation
m_instance
IStorageProvider* CLinuxStorageProvider::m_instance private
Referenced by CLinuxStorageProvider(), Eject(), GetDiskUsage(), GetLocalDrives(), GetRemovableDrives(), Initialize(), PumpDriveChangeEvents(), Stop(), and ~CLinuxStorageProvider().
The documentation for this class was generated from the following files:
LinuxStorageProvider.h
LinuxStorageProvider.cpp