Kodi Documentation: PVR::CPVREventLogJob Class Reference
PVR::CPVREventLogJob Class Reference
#include <PVREventLogJob.h>
Classes
struct Event
Public Member Functions
CPVREventLogJob ()=default
CPVREventLogJob (bool bNotifyUser, EventLevel eLevel, const std::string &label, const std::string &msg, const std::string &icon)
~CPVREventLogJob () override=default
const char * GetType () const override
Function that returns the type of job.
void AddEvent (bool bNotifyUser, EventLevel eLevel, const std::string &label, const std::string &msg, const std::string &icon)
bool DoWork () override
Main workhorse function of CJob instances.
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
virtual bool operator== (const CJob *job) const
virtual bool ShouldCancel (unsigned int progress, unsigned int total) const
Function for longer jobs to report progress and check whether they have been cancelled.
Private Attributes
std::vector< Event > m_events
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Constructor & Destructor Documentation
CPVREventLogJob() [1/2]
PVR::CPVREventLogJob::CPVREventLogJob () default
CPVREventLogJob() [2/2]
PVR::CPVREventLogJob::CPVREventLogJob (bool bNotifyUser, EventLevel eLevel, const std::string & label, const std::string & msg, const std::string & icon)
References AddEvent(), and label.
~CPVREventLogJob()
PVR::CPVREventLogJob::~CPVREventLogJob () override default
Member Function Documentation
AddEvent()
void PVR::CPVREventLogJob::AddEvent (bool bNotifyUser, EventLevel eLevel, const std::string & label, const std::string & msg, const std::string & icon)
References label, and m_events.
Referenced by anonymous_namespace{PVRGUIActionsTimers.cpp}::AddEventLogEntry(), CPVREventLogJob(), PVR::CPVRGUIActionsRecordings::ProcessDeleteAfterWatch(), and PVR::CPVRTimers::UpdateEntries().
DoWork()
bool PVR::CPVREventLogJob::DoWork () override virtual
Main workhorse function of CJob instances.
All CJob subclasses must implement this function, performing all processing. Once this function is complete, the OnJobComplete() callback is called, and the job is then destroyed.
See also
CJobManager, IJobCallback::OnJobComplete()
Implements CJob.
References CGUIDialogKaiToast::Error, Error, CServiceBroker::GetEventLog(), CGUIDialogKaiToast::Info, m_events, and CGUIDialogKaiToast::QueueNotification().
GetType()
const char * PVR::CPVREventLogJob::GetType () const inline override virtual
Function that returns the type of job.
CJob subclasses may optionally implement this function to specify the type of job. This is useful for the CJobManager::AddLIFOJob() routine, which preempts similar jobs with the new job.
Returns
a unique character string describing the job.
See also
CJobManager
Reimplemented from CJob.
Member Data Documentation
m_events
std::vector<Event> PVR::CPVREventLogJob::m_events private
Referenced by AddEvent(), and DoWork().
The documentation for this class was generated from the following files:
PVREventLogJob.h
PVREventLogJob.cpp