Kodi Documentation: PVR::CPVRChannelNumber Class Reference
PVR::CPVRChannelNumber Class Reference
#include <PVRChannelNumber.h>
Public Member Functions
CPVRChannelNumber ()=default
constexpr CPVRChannelNumber (unsigned int iChannelNumber, unsigned int iSubChannelNumber)
constexpr bool operator== (const CPVRChannelNumber &right) const
constexpr bool operator!= (const CPVRChannelNumber &right) const
constexpr bool operator< (const CPVRChannelNumber &right) const
constexpr bool IsValid () const
Check whether this channel number is valid (main channel number > 0).
constexpr unsigned int GetChannelNumber () const
Set the primary channel number.
constexpr unsigned int GetSubChannelNumber () const
Set the sub channel number.
std::string FormattedChannelNumber () const
Get a string representation for the channel number.
std::string SortableChannelNumber () const
Get a string representation for the channel number that can be used for SortItems.
Static Public Attributes
static const char SEPARATOR = '.'
The character used to separate channel and subchannel number.
Private Member Functions
std::string ToString (char separator) const
Private Attributes
unsigned int m_iChannelNumber = 0
unsigned int m_iSubChannelNumber = 0
Constructor & Destructor Documentation
CPVRChannelNumber() [1/2]
PVR::CPVRChannelNumber::CPVRChannelNumber () default
CPVRChannelNumber() [2/2]
constexpr PVR::CPVRChannelNumber::CPVRChannelNumber (unsigned int iChannelNumber, unsigned int iSubChannelNumber) inline constexpr
Member Function Documentation
FormattedChannelNumber()
std::string CPVRChannelNumber::FormattedChannelNumber () const
Get a string representation for the channel number.
Returns
The formatted string in the form <channel>SEPARATOR<subchannel>.
References SEPARATOR, and ToString().
Referenced by PVR::CPVRChannelGroup::GetChannelNumbers(), and PVR::CPVRChannel::SetChannelName().
GetChannelNumber()
constexpr unsigned int PVR::CPVRChannelNumber::GetChannelNumber () const inline constexpr
Set the primary channel number.
Returns
The channel number.
References m_iChannelNumber.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonChannel::CAddonChannel(), PVR::CPVRChannelSwitchingInputHandler::OnInputDone(), PVR::CPVRChannelGroup::Renumber(), PVR::CPVRChannelGroupMember::Serialize(), and anonymous_namespace{PVRGUIActionsChannels.cpp}::TriggerChannelSwitchAction().
GetSubChannelNumber()
constexpr unsigned int PVR::CPVRChannelNumber::GetSubChannelNumber () const inline constexpr
Set the sub channel number.
Returns
The sub channel number (ATSC).
References m_iSubChannelNumber.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonChannel::CAddonChannel(), PVR::CPVRChannelGroupMember::Serialize(), and anonymous_namespace{PVRGUIActionsChannels.cpp}::TriggerChannelSwitchAction().
IsValid()
constexpr bool PVR::CPVRChannelNumber::IsValid () const inline constexpr
Check whether this channel number is valid (main channel number > 0).
Returns
True if valid, false otherwise..
References m_iChannelNumber.
Referenced by PVR::CPVRChannelNumberInputHandler::CheckInputAndExecuteAction(), PVR::CGUIDialogPVRChannelsOSD::OnInputDone(), PVR::CGUIWindowPVRChannelsBase::OnInputDone(), PVR::CGUIWindowPVRGuideBase::OnInputDone(), PVR::CPVRChannelGroup::Renumber(), and PVR::CPVRChannelSwitchingInputHandler::SwitchToChannel().
operator!=()
constexpr bool PVR::CPVRChannelNumber::operator!= (const CPVRChannelNumber & right) const inline constexpr
References right.
operator<()
constexpr bool PVR::CPVRChannelNumber::operator< (const CPVRChannelNumber & right) const inline constexpr
References m_iChannelNumber, m_iSubChannelNumber, and right.
operator==()
constexpr bool PVR::CPVRChannelNumber::operator== (const CPVRChannelNumber & right) const inline constexpr
References m_iChannelNumber, m_iSubChannelNumber, and right.
SortableChannelNumber()
std::string CPVRChannelNumber::SortableChannelNumber () const
Get a string representation for the channel number that can be used for SortItems.
Returns
The sortable string in the form <channel> <subchannel>.
References ToString().
Referenced by PVR::CPVRChannelGroupMember::ToSortable().
ToString()
std::string CPVRChannelNumber::ToString (char separator) const private
References m_iChannelNumber, and m_iSubChannelNumber.
Referenced by FormattedChannelNumber(), and SortableChannelNumber().
Member Data Documentation
m_iChannelNumber
unsigned int PVR::CPVRChannelNumber::m_iChannelNumber = 0 private
Referenced by GetChannelNumber(), IsValid(), operator<(), operator==(), and ToString().
m_iSubChannelNumber
unsigned int PVR::CPVRChannelNumber::m_iSubChannelNumber = 0 private
Referenced by GetSubChannelNumber(), operator<(), operator==(), and ToString().
SEPARATOR
const char CPVRChannelNumber::SEPARATOR = '.' static
The character used to separate channel and subchannel number.
Referenced by PVR::CPVRChannelNumberInputHandler::AppendChannelNumberCharacter(), FormattedChannelNumber(), PVR::CPVRChannelNumberInputHandler::GetChannelNumber(), PVR::CGUIDialogPVRChannelsOSD::OnAction(), PVR::CPVRGUIActionListener::OnAction(), PVR::CGUIWindowPVRChannelsBase::OnAction(), and PVR::CGUIWindowPVRGuideBase::OnAction().
The documentation for this class was generated from the following files:
PVRChannelNumber.h
PVRChannelNumber.cpp