Kodi Documentation: CVideoSyncOsx Class Reference
CVideoSyncOsx Class Reference
#include <VideoSyncOsx.h>
Public Member Functions
CVideoSyncOsx (CVideoReferenceClock *clock)
bool Setup () override
void Run (CEvent &stopEvent) override
void Cleanup () override
float GetFps () override
void RefreshChanged () override
void OnLostDisplay () override
void OnResetDisplay () override
void VblankHandler (int64_t nowtime, uint32_t timebase)
Public Member Functions inherited from CVideoSync
CVideoSync (CVideoReferenceClock *clock)
virtual ~CVideoSync ()=default
Private Member Functions
virtual bool InitDisplayLink ()
virtual void DeinitDisplayLink ()
Private Member Functions inherited from IDispResource
virtual ~IDispResource ()=default
virtual void OnAppFocusChange (bool focus)
Private Attributes
int64_t m_LastVBlankTime
volatile bool m_displayLost = false
volatile bool m_displayReset = false
CEvent m_lostEvent
Additional Inherited Members
Protected Attributes inherited from CVideoSync
float m_fps
CVideoReferenceClock * m_refClock
Constructor & Destructor Documentation
CVideoSyncOsx()
CVideoSyncOsx::CVideoSyncOsx (CVideoReferenceClock * clock) inline
Member Function Documentation
Cleanup()
void CVideoSyncOsx::Cleanup () override virtual
Implements CVideoSync.
References CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, m_LastVBlankTime, m_lostEvent, CEvent::Set(), and CWinSystemBase::Unregister().
DeinitDisplayLink()
void CVideoSyncOsx::DeinitDisplayLink () private virtual
References Cocoa_CVDisplayLinkRelease().
Referenced by Run().
GetFps()
float CVideoSyncOsx::GetFps () override virtual
Implements CVideoSync.
References CGraphicContext::GetFPS(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, and CVideoSync::m_fps.
InitDisplayLink()
bool CVideoSyncOsx::InitDisplayLink () private virtual
References Cocoa_CVDisplayLinkCreate(), DisplayLinkCallBack(), CLog::Log(), and LOGDEBUG.
Referenced by Run().
OnLostDisplay()
void CVideoSyncOsx::OnLostDisplay () override virtual
Reimplemented from IDispResource.
References m_displayLost, m_lostEvent, and CEvent::Wait().
OnResetDisplay()
void CVideoSyncOsx::OnResetDisplay () override virtual
Reimplemented from IDispResource.
References m_displayReset.
RefreshChanged()
void CVideoSyncOsx::RefreshChanged () override virtual
Reimplemented from CVideoSync.
References m_displayReset.
Run()
void CVideoSyncOsx::Run (CEvent & stopEvent) override virtual
Implements CVideoSync.
References DeinitDisplayLink(), InitDisplayLink(), m_displayLost, m_displayReset, m_lostEvent, CEvent::Set(), and CEvent::Signaled().
Setup()
bool CVideoSyncOsx::Setup () override virtual
Implements CVideoSync.
References CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, m_displayLost, m_displayReset, m_LastVBlankTime, m_lostEvent, CWinSystemBase::Register(), and CEvent::Reset().
VblankHandler()
void CVideoSyncOsx::VblankHandler (int64_t nowtime, uint32_t timebase)
References CurrentHostCounter(), int64_t(), CVideoSync::m_fps, m_LastVBlankTime, CVideoSync::m_refClock, MathUtils::round_int(), and CVideoReferenceClock::UpdateClock().
Referenced by DisplayLinkCallBack().
Member Data Documentation
m_displayLost
volatile bool CVideoSyncOsx::m_displayLost = false private
Referenced by OnLostDisplay(), Run(), and Setup().
m_displayReset
volatile bool CVideoSyncOsx::m_displayReset = false private
Referenced by OnResetDisplay(), RefreshChanged(), Run(), and Setup().
m_LastVBlankTime
int64_t CVideoSyncOsx::m_LastVBlankTime private
Initial value:
=
      0
Referenced by Cleanup(), Setup(), and VblankHandler().
m_lostEvent
CEvent CVideoSyncOsx::m_lostEvent private
Referenced by Cleanup(), OnLostDisplay(), Run(), and Setup().
The documentation for this class was generated from the following files:
VideoSyncOsx.h
VideoSyncOsx.mm