Kodi Documentation: TestPlayListFactory.cpp File Reference
TestPlayListFactory.cpp File Reference
#include "URL.h"
#include "playlists/PlayList.h"
#include "playlists/PlayListFactory.h"
#include "playlists/PlayListXSPF.h"
#include "test/TestUtils.h"
#include <gtest/gtest.h>
Functions
TEST (TestPlayListFactory, XSPF)
Function Documentation
TEST()
TEST (TestPlayListFactory , XSPF)
References KODI::PLAYLIST::CPlayListFactory::Create(), EXPECT_NE(), EXPECT_TRUE(), KODI::PLAYLIST::CPlayListFactory::IsPlaylist(), playlist, and XBMC_REF_FILE_PATH.