Kodi Documentation: KODI::WINDOWING::WAYLAND::IWindowDecorationHandler Class Reference
KODI::WINDOWING::WAYLAND::IWindowDecorationHandler Class Reference abstract
#include <WindowDecorationHandler.h>
Public Member Functions
virtual void OnWindowMove (wayland::seat_t const &seat, std::uint32_t serial)=0
virtual void OnWindowResize (wayland::seat_t const &seat, std::uint32_t serial, wayland::shell_surface_resize edge)=0
virtual void OnWindowShowContextMenu (wayland::seat_t const &seat, std::uint32_t serial, CPointInt position)=0
virtual void OnWindowMinimize ()=0
virtual void OnWindowMaximize ()=0
virtual void OnWindowClose ()=0
virtual ~IWindowDecorationHandler ()=default
Detailed Description
Handler for reacting to events originating in window decorations, such as moving the window by clicking and dragging
Constructor & Destructor Documentation
~IWindowDecorationHandler()
virtual KODI::WINDOWING::WAYLAND::IWindowDecorationHandler::~IWindowDecorationHandler () virtual default
Member Function Documentation
OnWindowClose()
virtual void KODI::WINDOWING::WAYLAND::IWindowDecorationHandler::OnWindowClose () pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CWinSystemWayland.
Referenced by KODI::WINDOWING::WAYLAND::CWindowDecorator::ResetButtons().
OnWindowMaximize()
virtual void KODI::WINDOWING::WAYLAND::IWindowDecorationHandler::OnWindowMaximize () pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CWinSystemWayland.
Referenced by KODI::WINDOWING::WAYLAND::CWindowDecorator::ResetButtons().
OnWindowMinimize()
virtual void KODI::WINDOWING::WAYLAND::IWindowDecorationHandler::OnWindowMinimize () pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CWinSystemWayland.
Referenced by KODI::WINDOWING::WAYLAND::CWindowDecorator::ResetButtons().
OnWindowMove()
virtual void KODI::WINDOWING::WAYLAND::IWindowDecorationHandler::OnWindowMove (wayland::seat_t const & seat, std::uint32_t serial) pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CWinSystemWayland.
Referenced by KODI::WINDOWING::WAYLAND::CWindowDecorator::HandleSeatClick().
OnWindowResize()
virtual void KODI::WINDOWING::WAYLAND::IWindowDecorationHandler::OnWindowResize (wayland::seat_t const & seat, std::uint32_t serial, wayland::shell_surface_resize edge) pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CWinSystemWayland.
Referenced by KODI::WINDOWING::WAYLAND::CWindowDecorator::HandleSeatClick().
OnWindowShowContextMenu()
virtual void KODI::WINDOWING::WAYLAND::IWindowDecorationHandler::OnWindowShowContextMenu (wayland::seat_t const & seat, std::uint32_t serial, CPointInt position) pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CWinSystemWayland.
Referenced by KODI::WINDOWING::WAYLAND::CWindowDecorator::HandleSeatClick().
The documentation for this class was generated from the following file:
WindowDecorationHandler.h