Kodi Documentation: PERIPHERALS::CEventPollHandle Class Reference
PERIPHERALS::CEventPollHandle Class Reference
Handle returned by the event scanner to control scan timing.
#include <EventPollHandle.h>
Public Member Functions
CEventPollHandle (IEventPollCallback &callback)
Create an active polling handle.
~CEventPollHandle ()
Handle is automatically released when this class is destructed.
void Activate ()
Activate handle.
void Deactivate ()
Deactivate handle.
void HandleEvents (bool bWait)
Trigger a scan for events.
Private Attributes
IEventPollCallback & m_callback
Detailed Description
Handle returned by the event scanner to control scan timing.
When held, this allows one to control the timing of when events are handled.
Constructor & Destructor Documentation
CEventPollHandle()
CEventPollHandle::CEventPollHandle (IEventPollCallback & callback)
Create an active polling handle.
~CEventPollHandle()
CEventPollHandle::~CEventPollHandle (void)
Handle is automatically released when this class is destructed.
References m_callback, and PERIPHERALS::IEventPollCallback::Release().
Member Function Documentation
Activate()
void CEventPollHandle::Activate ()
Activate handle.
References PERIPHERALS::IEventPollCallback::Activate(), and m_callback.
Deactivate()
void CEventPollHandle::Deactivate ()
Deactivate handle.
References PERIPHERALS::IEventPollCallback::Deactivate(), and m_callback.
HandleEvents()
void CEventPollHandle::HandleEvents (bool bWait)
Trigger a scan for events.
Parameters
bWait If true, this blocks until all events are handled
References PERIPHERALS::IEventPollCallback::HandleEvents(), and m_callback.
Member Data Documentation
m_callback
IEventPollCallback& PERIPHERALS::CEventPollHandle::m_callback private
Referenced by Activate(), Deactivate(), HandleEvents(), and ~CEventPollHandle().
The documentation for this class was generated from the following files:
EventPollHandle.h
EventPollHandle.cpp