Kodi Documentation: PVR::CPVRGUIActionsParentalControl Class Reference
PVR::CPVRGUIActionsParentalControl Class Reference
#include <PVRGUIActionsParentalControl.h>
Public Member Functions
CPVRGUIActionsParentalControl ()
~CPVRGUIActionsParentalControl () override=default
ParentalCheckResult CheckParentalLock (const std::shared_ptr< const CPVRChannel > &channel) const
Check if channel is parental locked. Ask for PIN if necessary.
ParentalCheckResult CheckParentalPIN () const
Open Numeric dialog to check for parental PIN.
Public Member Functions inherited from PVR::IPVRComponent
virtual ~IPVRComponent ()=default
Private Member Functions
CPVRGUIActionsParentalControl (const CPVRGUIActionsParentalControl &)=delete
CPVRGUIActionsParentalControl const & operator= (CPVRGUIActionsParentalControl const &)=delete
Private Attributes
CPVRSettings m_settings
Constructor & Destructor Documentation
CPVRGUIActionsParentalControl() [1/2]
CPVRGUIActionsParentalControl::CPVRGUIActionsParentalControl ()
References CSettings::SETTING_PVRPARENTAL_ENABLED, and CSettings::SETTING_PVRPARENTAL_PIN.
~CPVRGUIActionsParentalControl()
PVR::CPVRGUIActionsParentalControl::~CPVRGUIActionsParentalControl () override default
CPVRGUIActionsParentalControl() [2/2]
PVR::CPVRGUIActionsParentalControl::CPVRGUIActionsParentalControl (const CPVRGUIActionsParentalControl &) private delete
Member Function Documentation
CheckParentalLock()
ParentalCheckResult CPVRGUIActionsParentalControl::CheckParentalLock (const std::shared_ptr< const CPVRChannel > & channel) const
Check if channel is parental locked. Ask for PIN if necessary.
Parameters
channel The channel to do the check for.
Returns
the result of the check (success, failed, or canceled by user).
References CheckParentalPIN(), PVR::FAILED, CServiceBroker::GetPVRManager(), LOGERROR, and PVR::SUCCESS.
CheckParentalPIN()
ParentalCheckResult CPVRGUIActionsParentalControl::CheckParentalPIN () const
Open Numeric dialog to check for parental PIN.
Returns
the result of the check (success, failed, or canceled by user).
References PVR::CANCELED, FAILED, PVR::FAILED, g_localizeStrings, CLocalizeStrings::Get(), PVR::CPVRSettings::GetBoolValue(), CServiceBroker::GetPVRManager(), PVR::CPVRSettings::GetStringValue(), m_settings, PVR::CPVRManager::RestartParentalTimer(), CSettings::SETTING_PVRPARENTAL_ENABLED, CSettings::SETTING_PVRPARENTAL_PIN, CGUIDialogNumeric::ShowAndVerifyInput(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), SUCCESS, and PVR::SUCCESS.
Referenced by CheckParentalLock().
operator=()
CPVRGUIActionsParentalControl const & PVR::CPVRGUIActionsParentalControl::operator= (CPVRGUIActionsParentalControl const &) private delete
Member Data Documentation
m_settings
CPVRSettings PVR::CPVRGUIActionsParentalControl::m_settings private
Referenced by CheckParentalPIN().
The documentation for this class was generated from the following files:
PVRGUIActionsParentalControl.h
PVRGUIActionsParentalControl.cpp