Kodi Documentation: AsyncHelpers.h File Reference
AsyncHelpers.h File Reference
#include <ppl.h>
#include <ppltasks.h>
#include <sdkddkver.h>
#include <winrt/windows.foundation.h>
Namespaces
namespace winrt
Functions
bool is_sta ()
void Wait (const winrt::IAsyncAction &asyncOp)
template<typename TResult , typename TProgress >
TResult Wait (const winrt::IAsyncOperationWithProgress< TResult, TProgress > &asyncOp)
template<typename TResult >
TResult Wait (const winrt::IAsyncOperation< TResult > &asyncOp)
template<typename TResult >
TResult Wait (const Concurrency::task< TResult > &asyncOp)
Function Documentation
is_sta()
bool is_sta () inline
Referenced by Wait(), Wait(), Wait(), and Wait().
Wait() [1/4]
template<typename TResult > TResult Wait (const Concurrency::task< TResult > & asyncOp) inline
References is_sta().
Wait() [2/4]
void Wait (const winrt::IAsyncAction & asyncOp) inline
References is_sta().
Referenced by CWinSystemWin10::ChangeResolution(), XFILE::CWinLibraryDirectory::Create(), XFILE::CWinLibraryFile::Delete(), Exec(), CWinSystemWin10::GetClipboardText(), CWinSystemWin10::GetConnectedDisplays(), XFILE::CWinLibraryDirectory::GetDirectory(), XFILE::CWinLibraryFile::GetFile(), XFILE::CWinLibraryDirectory::GetFolder(), CStorageProvider::GetRemovableDrives(), CAESinkFactoryWin::GetRendererDetailsWinRT(), CVideoPlayer::HandleMessages(), XFILE::CWinLibraryFile::OpenIntenal(), CVideoPlayerAudio::Process(), CVideoPlayerVideo::Process(), XFILE::CWinLibraryFile::Read(), XFILE::CWinLibraryDirectory::Remove(), XFILE::CWinLibraryFile::Rename(), XFILE::CWinLibraryDirectory::StatDirectory(), CWIN32Util::ToggleWindowsHDR(), and XFILE::CWinLibraryFile::Write().
Wait() [3/4]
template<typename TResult > TResult Wait (const winrt::IAsyncOperation< TResult > & asyncOp) inline
References is_sta().
Wait() [4/4]
template<typename TResult , typename TProgress > TResult Wait (const winrt::IAsyncOperationWithProgress< TResult, TProgress > & asyncOp) inline
References is_sta().