Kodi Documentation: PredicateSubtitlePriority Class Reference
PredicateSubtitlePriority Class Reference
The class' operator() decides if the given (subtitle) SelectionStream lh is 'better than' the given (subtitle) SelectionStream rh. If lh is 'better than' rh the return value is true, false otherwise.
Public Member Functions
PredicateSubtitlePriority (const std::string &lang, int stream, bool ison)
bool relevant (const SelectionStream &ss) const
bool operator() (const SelectionStream &lh, const SelectionStream &rh) const
Private Attributes
std::string audiolang
bool original
bool subson
PredicateSubtitleFilter filter
int subStream
Detailed Description
The class' operator() decides if the given (subtitle) SelectionStream lh is 'better than' the given (subtitle) SelectionStream rh. If lh is 'better than' rh the return value is true, false otherwise.
A subtitle lh is 'better than' a subtitle rh (in evaluation order) if
lh was previously selected, or
lh is an external sub and rh not, or
lh is a forced sub and ("original stream's language" was selected or subtitles are off) and audio stream language matches sub language and rh not, or
lh is a default sub and ("original stream's language" was selected or subtitles are off) and audio stream language matches sub language and rh not, or
lh is a sub where audio stream language matches sub language and (original stream's language" was selected or subtitles are off) and rh not, or - lh is a forced sub and a default sub ("original stream's language" was selected or subtitles are off) - lh is an external sub and its language matches the preferred subtitle's language (unequal to "original stream's language") and rh not, or - lh is language matches the preferred subtitle's language (unequal to "original stream's language") and rh not, or
lh is a default sub and rh not
Constructor & Destructor Documentation
PredicateSubtitlePriority()
PredicateSubtitlePriority::PredicateSubtitlePriority (const std::string & lang, int stream, bool ison) inline explicit
Member Function Documentation
operator()()
bool PredicateSubtitlePriority::operator() (const SelectionStream & lh, const SelectionStream & rh) const inline
References audiolang, CLangCodeExpander::CompareISO639Codes(), FLAG_DEFAULT, FLAG_FORCED, FLAG_HEARING_IMPAIRED, SelectionStream::flags, g_LangCodeExpander, g_langInfo, CServiceBroker::GetSettingsComponent(), SelectionStream::language, original, PREDICATE_RETURN, relevant(), CSettings::SETTING_ACCESSIBILITY_SUBHEARING, SelectionStream::source, STREAM_SOURCE_DEMUX_SUB, STREAM_SOURCE_MASK, STREAM_SOURCE_TEXT, subson, subStream, and SelectionStream::type_index.
relevant()
bool PredicateSubtitlePriority::relevant (const SelectionStream & ss) const inline
References filter.
Referenced by CVideoPlayer::OpenDefaultStreams(), and operator()().
Member Data Documentation
audiolang
std::string PredicateSubtitlePriority::audiolang private
Referenced by operator()().
filter
PredicateSubtitleFilter PredicateSubtitlePriority::filter private
Referenced by relevant().
original
bool PredicateSubtitlePriority::original private
Referenced by operator()().
subson
bool PredicateSubtitlePriority::subson private
Referenced by operator()().
subStream
int PredicateSubtitlePriority::subStream private
Referenced by operator()().
The documentation for this class was generated from the following file:
VideoPlayer.cpp