Kodi Documentation: KODI::PLAYLIST::CSmartPlaylistRule Class Reference
KODI::PLAYLIST::CSmartPlaylistRule Class Reference
#include <SmartPlayList.h>
Public Member Functions
CSmartPlaylistRule ()
~CSmartPlaylistRule () override=default
std::string GetLocalizedRule () const
FIELD_TYPE GetFieldType (int field) const override
Public Member Functions inherited from CDatabaseQueryRule
CDatabaseQueryRule ()
virtual ~CDatabaseQueryRule ()=default
virtual bool Load (const TiXmlNode *node, const std::string &encoding="UTF-8")
virtual bool Load (const CVariant &obj)
virtual bool Save (TiXmlNode *parent) const
virtual bool Save (CVariant &obj) const
std::string GetParameter () const
void SetParameter (const std::string &value)
void SetParameter (const std::vector< std::string > &values)
virtual std::string GetWhereClause (const CDatabase &db, const std::string &strType) const
Static Public Member Functions
static SortBy TranslateOrder (const char *order)
static std::string TranslateOrder (SortBy order)
static Field TranslateGroup (const char *group)
static std::string TranslateGroup (Field group)
static std::string GetLocalizedField (int field)
static std::string GetLocalizedGroup (Field group)
static bool CanGroupMix (Field group)
static std::vector< Field > GetFields (const std::string &type)
static std::vector< SortBy > GetOrders (const std::string &type)
static std::vector< Field > GetGroups (const std::string &type)
static bool IsFieldBrowseable (int field)
static bool Validate (const std::string &input, void *data)
static bool ValidateRating (const std::string &input, void *data)
static bool ValidateMyRating (const std::string &input, void *data)
Static Public Member Functions inherited from CDatabaseQueryRule
static std::string GetLocalizedOperator (SEARCH_OPERATOR oper)
static void GetAvailableOperators (std::vector< std::string > &operatorList)
Protected Member Functions
std::string GetField (int field, const std::string &type) const override
int TranslateField (const char *field) const override
std::string TranslateField (int field) const override
std::string FormatParameter (const std::string &negate, const std::string &oper, const CDatabase &db, const std::string &type) const override
std::string FormatWhereClause (const std::string &negate, const std::string &oper, const std::string &param, const CDatabase &db, const std::string &type) const override
SEARCH_OPERATOR GetOperator (const std::string &type) const override
std::string GetBooleanQuery (const std::string &negate, const std::string &strType) const override
Protected Member Functions inherited from CDatabaseQueryRule
std::string ValidateParameter (const std::string &parameter) const
virtual std::string GetOperatorString (SEARCH_OPERATOR op) const
Private Member Functions
std::string GetVideoResolutionQuery (const std::string &parameter) const
std::string FormatYearQuery (const std::string &field, const std::string &param, const std::string &parameter) const
Static Private Member Functions
static std::string FormatLinkQuery (const char *field, const char *table, const MediaType &mediaType, const std::string &mediaField, const std::string &parameter)
Additional Inherited Members
Public Types inherited from CDatabaseQueryRule
enum SEARCH_OPERATOR {
OPERATOR_START = 0 , OPERATOR_CONTAINS , OPERATOR_DOES_NOT_CONTAIN , OPERATOR_EQUALS ,
OPERATOR_DOES_NOT_EQUAL , OPERATOR_STARTS_WITH , OPERATOR_ENDS_WITH , OPERATOR_GREATER_THAN ,
OPERATOR_LESS_THAN , OPERATOR_AFTER , OPERATOR_BEFORE , OPERATOR_IN_THE_LAST ,
OPERATOR_NOT_IN_THE_LAST , OPERATOR_TRUE , OPERATOR_FALSE , OPERATOR_BETWEEN ,
OPERATOR_END
}
enum FIELD_TYPE {
TEXT_FIELD = 0 , REAL_FIELD , NUMERIC_FIELD , DATE_FIELD ,
PLAYLIST_FIELD , SECONDS_FIELD , BOOLEAN_FIELD , TEXTIN_FIELD
}
Public Attributes inherited from CDatabaseQueryRule
int m_field
SEARCH_OPERATOR m_operator
std::vector< std::string > m_parameter
Static Protected Member Functions inherited from CDatabaseQueryRule
static SEARCH_OPERATOR TranslateOperator (const char *oper)
static std::string TranslateOperator (SEARCH_OPERATOR oper)
Constructor & Destructor Documentation
CSmartPlaylistRule()
KODI::PLAYLIST::CSmartPlaylistRule::CSmartPlaylistRule () default
~CSmartPlaylistRule()
KODI::PLAYLIST::CSmartPlaylistRule::~CSmartPlaylistRule () override default
Member Function Documentation
CanGroupMix()
bool KODI::PLAYLIST::CSmartPlaylistRule::CanGroupMix (Field group) static
References KODI::PLAYLIST::group::field, and KODI::PLAYLIST::groups.
Referenced by CGUIDialogSmartPlaylistEditor::OnGroupBy(), and CGUIDialogSmartPlaylistEditor::UpdateButtons().
FormatLinkQuery()
std::string KODI::PLAYLIST::CSmartPlaylistRule::FormatLinkQuery (const char * field, const char * table, const MediaType & mediaType, const std::string & mediaField, const std::string & parameter) static private
References table.
Referenced by FormatWhereClause().
FormatParameter()
std::string KODI::PLAYLIST::CSmartPlaylistRule::FormatParameter (const std::string & negate, const std::string & oper, const CDatabase & db, const std::string & type) const override protected virtual
Reimplemented from CDatabaseQueryRule.
References FieldAlbumDuration, FieldTime, CDatabaseQueryRule::FormatParameter(), CDatabaseQueryRule::m_field, and CDatabase::PrepareSQL().
Referenced by FormatWhereClause().
FormatWhereClause()
std::string KODI::PLAYLIST::CSmartPlaylistRule::FormatWhereClause (const std::string & negate, const std::string & oper, const std::string & param, const CDatabase & db, const std::string & type) const override protected virtual
Reimplemented from CDatabaseQueryRule.
References CStreamDetail::AUDIO, FieldActor, FieldAlbumArtist, FieldArtist, FieldAudioChannels, FieldAudioCodec, FieldAudioCount, FieldAudioLanguage, FieldCountry, FieldDateAdded, FieldDirector, FieldDiscTitle, FieldGenre, FieldHdrType, FieldId, FieldLastPlayed, FieldMPAA, FieldNumberOfEpisodes, FieldNumberOfWatchedEpisodes, FieldOrigYear, FieldPath, FieldPlaycount, FieldRole, FieldSource, FieldStudio, FieldSubtitleCount, FieldSubtitleLanguage, FieldTag, FieldVideoAspectRatio, FieldVideoCodec, FieldVideoResolution, FieldWriter, FieldYear, FormatLinkQuery(), FormatParameter(), CDatabaseQueryRule::FormatWhereClause(), FormatYearQuery(), GetField(), CServiceBroker::GetSettingsComponent(), GetVideoResolutionQuery(), CDatabaseQueryRule::m_field, CDatabaseQueryRule::m_operator, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeTvShow, CDatabaseQueryRule::OPERATOR_BEFORE, CDatabaseQueryRule::OPERATOR_DOES_NOT_EQUAL, CDatabaseQueryRule::OPERATOR_EQUALS, CDatabaseQueryRule::OPERATOR_LESS_THAN, CDatabaseQueryRule::OPERATOR_NOT_IN_THE_LAST, CDatabase::PrepareSQL(), CSettings::SETTING_MUSICLIBRARY_USEORIGINALDATE, CStreamDetail::SUBTITLE, and table.
FormatYearQuery()
std::string KODI::PLAYLIST::CSmartPlaylistRule::FormatYearQuery (const std::string & field, const std::string & param, const std::string & parameter) const private
References CDatabaseQueryRule::m_operator, CDatabaseQueryRule::OPERATOR_DOES_NOT_EQUAL, CDatabaseQueryRule::OPERATOR_EQUALS, and CDatabaseQueryRule::OPERATOR_LESS_THAN.
Referenced by FormatWhereClause().
GetBooleanQuery()
std::string KODI::PLAYLIST::CSmartPlaylistRule::GetBooleanQuery (const std::string & negate, const std::string & strType) const override protected virtual
Reimplemented from CDatabaseQueryRule.
References FieldCompilation, FieldId, FieldInProgress, FieldIsBoxset, FieldTrailer, GetField(), and CDatabaseQueryRule::m_field.
GetField()
std::string KODI::PLAYLIST::CSmartPlaylistRule::GetField (int field, const std::string & type) const override protected virtual
Implements CDatabaseQueryRule.
References DatabaseQueryPartWhere, FieldMax, FieldUnknown, CMediaTypes::FromString(), and DatabaseUtils::GetField().
Referenced by FormatWhereClause(), and GetBooleanQuery().
GetFields()
std::vector< Field > KODI::PLAYLIST::CSmartPlaylistRule::GetFields (const std::string & type) static
References FieldActor, FieldAirDate, FieldAlbum, FieldAlbumArtist, FieldAlbumDuration, FieldAlbumStatus, FieldAlbumType, FieldArtist, FieldArtistType, FieldAudioChannels, FieldAudioCodec, FieldAudioCount, FieldAudioLanguage, FieldBandFormed, FieldBiography, FieldBorn, FieldBPM, FieldComment, FieldCompilation, FieldCountry, FieldDateAdded, FieldDateModified, FieldDateNew, FieldDied, FieldDirector, FieldDisambiguation, FieldDisbanded, FieldDiscTitle, FieldEpisodeNumber, FieldFilename, FieldGender, FieldGenre, FieldHdrType, FieldInProgress, FieldInstruments, FieldIsBoxset, FieldLastPlayed, FieldMoods, FieldMPAA, FieldMusicBitRate, FieldMusicLabel, FieldNoOfChannels, FieldNumberOfEpisodes, FieldNumberOfWatchedEpisodes, FieldOriginalTitle, FieldOrigYear, FieldPath, FieldPlaycount, FieldPlaylist, FieldPlot, FieldPlotOutline, FieldRating, FieldReview, FieldRole, KODI::PLAYLIST::fields, FieldSampleRate, FieldSeason, FieldSet, FieldSource, FieldStudio, FieldStyles, FieldSubtitleCount, FieldSubtitleLanguage, FieldTag, FieldTagline, FieldThemes, FieldTime, FieldTitle, FieldTop250, FieldTotalDiscs, FieldTrackNumber, FieldTrailer, FieldTvShowStatus, FieldTvShowTitle, FieldUserRating, FieldVideoAspectRatio, FieldVideoCodec, FieldVideoResolution, FieldVirtualFolder, FieldVotes, FieldWriter, FieldYear, CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_MUSICLIBRARY_USEORIGINALDATE.
Referenced by KODI::PLAYLIST::CSmartPlaylist::GetAvailableFields(), CGUIDialogSmartPlaylistRule::OnField(), and CGUIDialogSmartPlaylistRule::UpdateButtons().
GetFieldType()
CDatabaseQueryRule::FIELD_TYPE KODI::PLAYLIST::CSmartPlaylistRule::GetFieldType (int field) const override virtual
Implements CDatabaseQueryRule.
References f, KODI::PLAYLIST::fields, and CDatabaseQueryRule::TEXT_FIELD.
Referenced by CGUIDialogSmartPlaylistRule::GetValidOperators(), and CGUIDialogSmartPlaylistRule::UpdateButtons().
GetGroups()
std::vector< Field > KODI::PLAYLIST::CSmartPlaylistRule::GetGroups (const std::string & type) static
References FieldActor, FieldAlbum, FieldArtist, FieldCountry, FieldDirector, FieldGenre, FieldNone, FieldOrigYear, FieldSet, FieldStudio, FieldTag, FieldUnknown, FieldWriter, FieldYear, CServiceBroker::GetSettingsComponent(), KODI::PLAYLIST::groups, and CSettings::SETTING_MUSICLIBRARY_USEORIGINALDATE.
Referenced by CGUIDialogSmartPlaylistEditor::OnGroupBy(), CGUIDialogSmartPlaylistEditor::OnType(), and CGUIDialogSmartPlaylistEditor::UpdateButtons().
GetLocalizedField()
std::string KODI::PLAYLIST::CSmartPlaylistRule::GetLocalizedField (int field) static
References f, KODI::PLAYLIST::fields, g_localizeStrings, and CLocalizeStrings::Get().
Referenced by GetLocalizedRule(), CGUIDialogSmartPlaylistRule::OnField(), and CGUIDialogSmartPlaylistRule::UpdateButtons().
GetLocalizedGroup()
std::string KODI::PLAYLIST::CSmartPlaylistRule::GetLocalizedGroup (Field group) static
References KODI::PLAYLIST::group::field, g_localizeStrings, CLocalizeStrings::Get(), and KODI::PLAYLIST::groups.
Referenced by CGUIDialogSmartPlaylistEditor::OnGroupBy(), and CGUIDialogSmartPlaylistEditor::UpdateButtons().
GetLocalizedRule()
std::string KODI::PLAYLIST::CSmartPlaylistRule::GetLocalizedRule () const
References GetLocalizedField(), CDatabaseQueryRule::GetLocalizedOperator(), CDatabaseQueryRule::GetParameter(), CDatabaseQueryRule::m_field, and CDatabaseQueryRule::m_operator.
GetOperator()
CDatabaseQueryRule::SEARCH_OPERATOR KODI::PLAYLIST::CSmartPlaylistRule::GetOperator (const std::string & type) const override protected virtual
Todo:
SMARTPLAYLISTS do we really need this, or should we just make this field the premiered date and request a date?
Reimplemented from CDatabaseQueryRule.
References FieldYear, CDatabaseQueryRule::GetOperator(), CDatabaseQueryRule::m_field, CDatabaseQueryRule::OPERATOR_CONTAINS, CDatabaseQueryRule::OPERATOR_DOES_NOT_CONTAIN, CDatabaseQueryRule::OPERATOR_DOES_NOT_EQUAL, and CDatabaseQueryRule::OPERATOR_EQUALS.
GetOrders()
std::vector< SortBy > KODI::PLAYLIST::CSmartPlaylistRule::GetOrders (const std::string & type) static
References CServiceBroker::GetSettingsComponent(), CSettings::SETTING_MUSICLIBRARY_USEORIGINALDATE, SortByAlbum, SortByAlbumType, SortByArtist, SortByBPM, SortByCountry, SortByDateAdded, SortByEpisodeNumber, SortByFile, SortByGenre, SortByLastPlayed, SortByMPAA, SortByNone, SortByNumberOfEpisodes, SortByNumberOfWatchedEpisodes, SortByOrigDate, SortByOriginalTitle, SortByPath, SortByPlaycount, SortByRandom, SortByRating, SortBySeason, SortBySortTitle, SortByStudio, SortByTime, SortByTitle, SortByTop250, SortByTotalDiscs, SortByTrackNumber, SortByTvShowStatus, SortByTvShowTitle, SortByUserRating, SortByVotes, and SortByYear.
Referenced by CGUIDialogSmartPlaylistEditor::OnOrder().
GetVideoResolutionQuery()
std::string KODI::PLAYLIST::CSmartPlaylistRule::GetVideoResolutionQuery (const std::string & parameter) const private
References CDatabaseQueryRule::m_operator, max, min, CDatabaseQueryRule::OPERATOR_DOES_NOT_EQUAL, CDatabaseQueryRule::OPERATOR_EQUALS, CDatabaseQueryRule::OPERATOR_GREATER_THAN, and CDatabaseQueryRule::OPERATOR_LESS_THAN.
Referenced by FormatWhereClause().
IsFieldBrowseable()
bool KODI::PLAYLIST::CSmartPlaylistRule::IsFieldBrowseable (int field) static
References f, and KODI::PLAYLIST::fields.
Referenced by CGUIDialogSmartPlaylistRule::UpdateButtons().
TranslateField() [1/2]
int KODI::PLAYLIST::CSmartPlaylistRule::TranslateField (const char * field) const override protected virtual
Implements CDatabaseQueryRule.
References f, KODI::PLAYLIST::group::field, FieldNone, and KODI::PLAYLIST::fields.
TranslateField() [2/2]
std::string KODI::PLAYLIST::CSmartPlaylistRule::TranslateField (int field) const override protected virtual
Implements CDatabaseQueryRule.
References f, and KODI::PLAYLIST::fields.
TranslateGroup() [1/2]
Field KODI::PLAYLIST::CSmartPlaylistRule::TranslateGroup (const char * group) static
References FieldUnknown, KODI::PLAYLIST::groups, and KODI::PLAYLIST::group::name.
Referenced by CGUIDialogSmartPlaylistEditor::OnGroupBy(), CGUIDialogSmartPlaylistEditor::OnType(), and CGUIDialogSmartPlaylistEditor::UpdateButtons().
TranslateGroup() [2/2]
std::string KODI::PLAYLIST::CSmartPlaylistRule::TranslateGroup (Field group) static
References KODI::PLAYLIST::group::field, and KODI::PLAYLIST::groups.
TranslateOrder() [1/2]
SortBy KODI::PLAYLIST::CSmartPlaylistRule::TranslateOrder (const char * order) static
References SortUtils::SortMethodFromString().
Referenced by KODI::PLAYLIST::CSmartPlaylist::Load(), KODI::PLAYLIST::CSmartPlaylist::LoadFromXML(), KODI::PLAYLIST::CSmartPlaylist::Save(), and KODI::PLAYLIST::CSmartPlaylist::Save().
TranslateOrder() [2/2]
std::string KODI::PLAYLIST::CSmartPlaylistRule::TranslateOrder (SortBy order) static
References SortUtils::SortMethodToString().
Validate()
bool KODI::PLAYLIST::CSmartPlaylistRule::Validate (const std::string & input, void * data) static
References data(), KODI::PLAYLIST::fields, CDatabaseQueryRule::m_field, RULE_VALUE_SEPARATOR, and values.
Referenced by CGUIDialogSmartPlaylistRule::OnInitWindow().
ValidateMyRating()
bool KODI::PLAYLIST::CSmartPlaylistRule::ValidateMyRating (const std::string & input, void * data) static
References data(), and StringValidation::IsPositiveInteger().
ValidateRating()
bool KODI::PLAYLIST::CSmartPlaylistRule::ValidateRating (const std::string & input, void * data) static
References end().
The documentation for this class was generated from the following files:
SmartPlayList.h
SmartPlayList.cpp