Kodi Documentation: KODI::UTILS::GUILIB::CGUIContentUtils Class Reference
KODI::UTILS::GUILIB::CGUIContentUtils Class Reference
#include <GUIContentUtils.h>
Static Public Member Functions
static bool HasInfoForItem (const CFileItem &item)
Check whether an information dialog is available for the given item.
static bool ShowInfoForItem (const CFileItem &item)
Show an information dialog for the given item.
Member Function Documentation
HasInfoForItem()
bool CGUIContentUtils::HasInfoForItem (const CFileItem & item) static
Check whether an information dialog is available for the given item.
Parameters
item The item to process
Returns
True if an information dialog is available, false otherwise
References PVR::CPVRManager::Get(), CServiceBroker::GetPVRManager(), CFileItem::GetVideoInfoTag(), CFileItem::HasAddonInfo(), PVR::CPVRGUIActionsUtils::HasInfoForItem(), CFileItem::HasMusicInfoTag(), CFileItem::HasPVRRecordingInfoTag(), CFileItem::HasVideoInfoTag(), CVideoInfoTag::m_type, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeSeason, MediaTypeTvShow, MediaTypeVideo, and MediaTypeVideoCollection.
Referenced by CONTEXTMENU::CFavouritesTargetInfo::IsVisible(), and ShowInfoForItem().
ShowInfoForItem()
bool CGUIContentUtils::ShowInfoForItem (const CFileItem & item) static
Show an information dialog for the given item.
Parameters
item The item to process
Returns
True if an information dialog was displayed, false otherwise
References PVR::CPVRManager::Get(), CServiceBroker::GetPVRManager(), CFileItem::HasAddonInfo(), HasInfoForItem(), CFileItem::HasMusicInfoTag(), CFileItem::HasVideoInfoTag(), CGUIDialogMusicInfo::ShowFor(), CGUIDialogVideoInfo::ShowFor(), and CGUIDialogAddonInfo::ShowForItem().
Referenced by CONTEXTMENU::CFavouritesTargetInfo::Execute(), CGUIWindowFavourites::OnAction(), CDirectoryProvider::OnInfo(), and anonymous_namespace{GUIWindowFavourites.cpp}::CVideoSelectActionProcessor::OnInfoSelected().
The documentation for this class was generated from the following files:
GUIContentUtils.h
GUIContentUtils.cpp