Kodi Documentation: CHTTPPythonWsgiInvoker Class Reference
CHTTPPythonWsgiInvoker Class Reference
#include <HTTPPythonWsgiInvoker.h>
Public Member Functions
CHTTPPythonWsgiInvoker (ILanguageInvocationHandler *invocationHandler, HTTPPythonRequest *request)
~CHTTPPythonWsgiInvoker () override
HTTPPythonRequest * GetRequest () override
Public Member Functions inherited from CHTTPPythonInvoker
~CHTTPPythonInvoker () override
Public Member Functions inherited from CPythonInvoker
CPythonInvoker (ILanguageInvocationHandler *invocationHandler)
~CPythonInvoker () override
bool Execute (const std::string &script, const std::vector< std::string > &arguments=std::vector< std::string >()) override
bool IsStopping () const override
Public Member Functions inherited from ILanguageInvoker
ILanguageInvoker (ILanguageInvocationHandler *invocationHandler)
virtual ~ILanguageInvoker ()
virtual bool Stop (bool abort=false)
void SetId (int id)
int GetId () const
const ADDON::AddonPtr & GetAddon () const
void SetAddon (const ADDON::AddonPtr &addon)
InvokerState GetState () const
bool IsActive () const
bool IsRunning () const
void Reset ()
Static Public Member Functions
static void GlobalInitializeModules (void)
Protected Member Functions
void executeScript (FILE *fp, const std::string &script, PyObject *moduleDict) override
const char * getInitializationScript () const override
Protected Member Functions inherited from CHTTPPythonInvoker
CHTTPPythonInvoker (ILanguageInvocationHandler *invocationHandler, HTTPPythonRequest *request)
void onAbort () override
void onError (const std::string &exceptionType="", const std::string &exceptionValue="", const std::string &exceptionTraceback="") override
Protected Member Functions inherited from CPythonInvoker
bool execute (const std::string &script, const std::vector< std::string > &arguments) override
bool stop (bool abort) override
void onExecutionDone () override
void onExecutionFailed () override
virtual void onInitialization ()
virtual void onPythonModuleInitialization (void *moduleDict)
virtual void onDeinitialization ()
virtual void onSuccess ()
Protected Member Functions inherited from ILanguageInvoker
virtual void AbortNotification ()
virtual void pulseGlobalEvent ()
virtual bool onExecutionInitialized ()
virtual void onExecutionFinalized ()
void setState (InvokerState state)
Static Private Member Functions
static std::map< std::string, std::string > createCgiEnvironment (const HTTPPythonRequest *httpRequest, const ADDON::AddonPtr &addon)
static void addWsgiEnvironment (HTTPPythonRequest *request, void *environment)
Private Attributes
XBMCAddon::xbmcwsgi::WsgiResponse * m_wsgiResponse
Additional Inherited Members
Public Types inherited from CPythonInvoker
typedef std::unique_ptr< PyObject, PyObjectDeleter > PyObjectPtr
Protected Attributes inherited from CHTTPPythonInvoker
HTTPPythonRequest * m_request
bool m_internalError = false
Protected Attributes inherited from CPythonInvoker
std::string m_sourceFile
CCriticalSection m_critical
Protected Attributes inherited from ILanguageInvoker
ADDON::AddonPtr m_addon
Constructor & Destructor Documentation
CHTTPPythonWsgiInvoker()
CHTTPPythonWsgiInvoker::CHTTPPythonWsgiInvoker (ILanguageInvocationHandler * invocationHandler, HTTPPythonRequest * request)
~CHTTPPythonWsgiInvoker()
CHTTPPythonWsgiInvoker::~CHTTPPythonWsgiInvoker () override
References m_wsgiResponse.
Member Function Documentation
addWsgiEnvironment()
void CHTTPPythonWsgiInvoker::addWsgiEnvironment (HTTPPythonRequest * request, void * environment) static private
References PythonBindings::makePythonInstance(), PythonBindings::prepareForReturn(), and XBMCAddon::xbmcwsgi::WsgiErrorStream::SetRequest().
Referenced by executeScript().
createCgiEnvironment()
std::map< std::string, std::string > CHTTPPythonWsgiInvoker::createCgiEnvironment (const HTTPPythonRequest * httpRequest, const ADDON::AddonPtr & addon) static private
References GET, HEAD, HTTPPythonRequest::headerValues, HTTPPythonRequest::hostname, HTTPPythonRequest::method, HTTPPythonRequest::path, HTTPPythonRequest::port, POST, HTTPPythonRequest::url, and HTTPPythonRequest::version.
Referenced by executeScript().
executeScript()
void CHTTPPythonWsgiInvoker::executeScript (FILE * fp, const std::string & script, PyObject * moduleDict) override protected virtual
Reimplemented from CPythonInvoker.
References addWsgiEnvironment(), XBMCAddon::xbmcwsgi::WsgiResponse::Append(), createCgiEnvironment(), ADDON::CWebinterface::EntryPoint(), URIUtils::GetFileName(), CLog::GetLogger(), CServiceBroker::GetLogging(), ADDON::CWebinterface::GetType(), ILanguageInvoker::m_addon, CHTTPPythonInvoker::m_request, m_wsgiResponse, PythonBindings::makePythonInstance(), PythonBindings::PyXBMCGetUnicodeString(), URIUtils::RemoveExtension(), ADDON::WEB_INTERFACE, and ADDON::WebinterfaceTypeWsgi.
getInitializationScript()
const char * CHTTPPythonWsgiInvoker::getInitializationScript () const override protected virtual
Implements CPythonInvoker.
References RUNSCRIPT.
GetRequest()
HTTPPythonRequest * CHTTPPythonWsgiInvoker::GetRequest () override virtual
Implements CHTTPPythonInvoker.
References XBMCAddon::xbmcwsgi::WsgiResponse::Finalize(), CHTTPPythonInvoker::m_internalError, CHTTPPythonInvoker::m_request, and m_wsgiResponse.
GlobalInitializeModules()
void CHTTPPythonWsgiInvoker::GlobalInitializeModules (void) static
References CLog::Log(), and LOGWARNING.
Referenced by XBPython::OnScriptInitialized().
Member Data Documentation
m_wsgiResponse
XBMCAddon::xbmcwsgi::WsgiResponse* CHTTPPythonWsgiInvoker::m_wsgiResponse private
Referenced by executeScript(), GetRequest(), and ~CHTTPPythonWsgiInvoker().
The documentation for this class was generated from the following files:
HTTPPythonWsgiInvoker.h
HTTPPythonWsgiInvoker.cpp