Kodi Documentation: KODI::MOUSE::IMouseInputHandler Class Reference
KODI::MOUSE::IMouseInputHandler Class Reference abstract
Input » Mouse
Interface for handling mouse events.
#include <IMouseInputHandler.h>
Public Member Functions
virtual ~IMouseInputHandler (void)=default
virtual std::string ControllerID (void) const =0
The controller profile for this mouse input handler.
virtual bool OnMotion (const PointerName &relpointer, int dx, int dy)=0
A relative pointer has moved.
virtual bool OnButtonPress (const ButtonName &button)=0
A mouse button has been pressed.
virtual void OnButtonRelease (const ButtonName &button)=0
A mouse button has been released.
virtual void OnInputFrame ()=0
Called at the end of the frame that provided input.
Detailed Description
Interface for handling mouse events.
Constructor & Destructor Documentation
~IMouseInputHandler()
virtual KODI::MOUSE::IMouseInputHandler::~IMouseInputHandler (void) virtual default
Member Function Documentation
ControllerID()
virtual std::string KODI::MOUSE::IMouseInputHandler::ControllerID (void) const pure virtual
The controller profile for this mouse input handler.
Returns
The ID of the add-on extending kodi.game.controller
Implemented in KODI::GAME::CGameClientMouse, and KODI::GAME::CAgentMouse.
Referenced by KODI::MOUSE::CDefaultMouseHandling::Load(), and PERIPHERALS::CAddonInputHandling::Load().
OnButtonPress()
virtual bool KODI::MOUSE::IMouseInputHandler::OnButtonPress (const ButtonName & button) pure virtual
A mouse button has been pressed.
Parameters
button The name of the feature being pressed
Returns
True if the event was handled, otherwise false
Implemented in KODI::GAME::CAgentMouse, and KODI::GAME::CGameClientMouse.
Referenced by KODI::MOUSE::CMouseInputHandling::OnButtonPress().
OnButtonRelease()
virtual void KODI::MOUSE::IMouseInputHandler::OnButtonRelease (const ButtonName & button) pure virtual
A mouse button has been released.
Parameters
button The name of the feature being released
Implemented in KODI::GAME::CAgentMouse, and KODI::GAME::CGameClientMouse.
Referenced by KODI::MOUSE::CMouseInputHandling::OnButtonRelease().
OnInputFrame()
virtual void KODI::MOUSE::IMouseInputHandler::OnInputFrame () pure virtual
Called at the end of the frame that provided input.
This can be as a result of a pointer update, a button press, or a button release. All three events will result in a call to OnInputFrame().
Implemented in KODI::GAME::CGameClientMouse, and KODI::GAME::CAgentMouse.
Referenced by KODI::MOUSE::CMouseInputHandling::OnButtonPress(), KODI::MOUSE::CMouseInputHandling::OnButtonRelease(), and KODI::MOUSE::CMouseInputHandling::OnPosition().
OnMotion()
virtual bool KODI::MOUSE::IMouseInputHandler::OnMotion (const PointerName & relpointer, int dx, int dy) pure virtual
A relative pointer has moved.
Parameters
relpointer The name of the relative pointer being moved
dx The relative x coordinate of motion
dy The relative y coordinate of motion
The mouse uses a left-handed (graphics) cartesian coordinate system. Positive X is right, positive Y is down.
Returns
True if the event was handled, otherwise false
Implemented in KODI::GAME::CAgentMouse, and KODI::GAME::CGameClientMouse.
Referenced by KODI::MOUSE::CMouseInputHandling::OnPosition().
The documentation for this class was generated from the following file:
IMouseInputHandler.h