Kodi Documentation: CApplicationSkinHandling Class Reference
CApplicationSkinHandling Class Reference
Class handling application support for skin management.
#include <ApplicationSkinHandling.h>
Public Member Functions
CApplicationSkinHandling (IMsgTargetCallback *msgCb, IWindowManagerCallback *wCb, bool &bInitializing)
void UnloadSkin ()
bool OnSettingChanged (const CSetting &setting)
void ReloadSkin (bool confirm=false)
Public Member Functions inherited from IApplicationComponent
virtual ~IApplicationComponent ()=default
Protected Member Functions
bool LoadSkin (const std::string &skinID)
bool LoadCustomWindows ()
void ProcessSkin () const
Called by the application main/render thread for processing operations belonging to the skin.
Protected Attributes
bool m_saveSkinOnUnloading = true
bool m_confirmSkinChange = true
bool m_ignoreSkinSettingChanges = false
IMsgTargetCallback * m_msgCb
IWindowManagerCallback * m_wCb
bool & m_bInitializing
Friends
class CApplication
Detailed Description
Class handling application support for skin management.
Constructor & Destructor Documentation
CApplicationSkinHandling()
CApplicationSkinHandling::CApplicationSkinHandling (IMsgTargetCallback * msgCb, IWindowManagerCallback * wCb, bool & bInitializing)
Member Function Documentation
LoadCustomWindows()
bool CApplicationSkinHandling::LoadCustomWindows () protected
References CGUIWindowManager::AddCustomWindow(), XFILE::DIR_FLAG_NO_FILE_DIRS, g_SkinInfo, XFILE::CDirectory::GetDirectory(), URIUtils::GetFileName(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CGUIWindow::KEEP_IN_MEMORY, CGUIWindow::LOAD_ON_GUI_INIT, CXBMCTinyXML::LoadFile(), CLog::Log(), LOGERROR, LOGINFO, MODAL, MODELESS, CGUIWindow::SetCustom(), CGUIWindow::SetLoadType(), WINDOW_HOME, and WINDOW_INVALID.
Referenced by LoadSkin().
LoadSkin()
bool CApplicationSkinHandling::LoadSkin (const std::string & skinID) protected
References CGUIWindowManager::ActivateWindow(), CGUIWindowManager::Add(), URIUtils::AddFileToFolder(), URIUtils::AddSlashAtEnd(), ADDON::CHOICE_YES, XFILE::CDirectoryCache::ClearSubPaths(), CGUIAudioManager::Enable(), end(), g_directoryCache, g_fontManager, g_localizeStrings, g_SkinInfo, CServiceBroker::GetAddonMgr(), CServiceBroker::GetAppComponents(), CGUIComponent::GetAudioManager(), CGUIComponent::GetColorManager(), CGUIControlGroup::GetFocusedControlID(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetGUI(), CSkinSettings::GetInstance(), CServiceBroker::GetPlaylistPlayer(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetTextureCache(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), GUI_MSG_SETFOCUS, CGUIWindow::HasSaveLastControl(), CGUIWindowManager::Initialize(), CApplicationPlayer::IsPausedPlayback(), CGUIAudioManager::Load(), CGUIColorManager::Load(), LoadCustomWindows(), CLocalizeStrings::LoadSkinStrings(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_msgCb, m_wCb, CSkinSettings::MigrateSettings(), NONE, CGUIWindow::OnMessage(), CGraphicContext::SetMediaDir(), CSettings::SETTING_LOCALE_LANGUAGE, CSettings::SETTING_LOOKANDFEEL_FONT, CSettings::SETTING_LOOKANDFEEL_SKINCOLORS, ADDON::SKIN, UnloadSkin(), VIDEO, WINDOW_FULLSCREEN_GAME, WINDOW_FULLSCREEN_VIDEO, WINDOW_HOME, and WINDOW_INVALID.
Referenced by ReloadSkin().
OnSettingChanged()
bool CApplicationSkinHandling::OnSettingChanged (const CSetting & setting)
References g_SkinInfo, CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), ISetting::GetId(), CServiceBroker::GetSettingsComponent(), GetValue(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_WINDOW_RESIZE, CSetting::IsDefault(), m_confirmSkinChange, m_ignoreSkinSettingChanges, URIUtils::RemoveExtension(), CSettingString::Reset(), CSettings::SETTING_LOOKANDFEEL_FONT, CSettings::SETTING_LOOKANDFEEL_SKIN, CSettings::SETTING_LOOKANDFEEL_SKINCOLORS, CSettings::SETTING_LOOKANDFEEL_SKINTHEME, CSettings::SETTING_LOOKANDFEEL_SKINZOOM, and TMSG_EXECUTE_BUILT_IN.
ProcessSkin()
void CApplicationSkinHandling::ProcessSkin () const protected
Called by the application main/render thread for processing operations belonging to the skin.
References g_SkinInfo.
ReloadSkin()
void CApplicationSkinHandling::ReloadSkin (bool confirm = false)
References CGUIWindowManager::ActivateWindow(), CGUIDialogKaiToast::Error, g_localizeStrings, g_SkinInfo, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), GUI_MSG_LOAD_SKIN, LoadSkin(), CLog::Log(), LOGFATAL, m_bInitializing, m_confirmSkinChange, CGUIDialogKaiToast::QueueNotification(), CGUIWindowManager::SendMessage(), CSettings::SETTING_LOOKANDFEEL_SKIN, KODI::MESSAGING::HELPERS::ShowYesNoDialogText(), and WINDOW_STARTUP_ANIM.
Referenced by KODI::WINDOWING::X11::CWinSystemX11GLContext::FinishWindowResize(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::FinishWindowResize(), ReloadSkin(), KODI::WINDOWING::X11::CWinSystemX11GLContext::ResizeWindow(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::ResizeWindow(), KODI::WINDOWING::X11::CWinSystemX11GLContext::SetFullScreen(), and KODI::WINDOWING::X11::CWinSystemX11GLESContext::SetFullScreen().
UnloadSkin()
void CApplicationSkinHandling::UnloadSkin ()
References CGUITextureManager::Cleanup(), CGUILargeTextureManager::CleanupUnusedImages(), CGUIInfoManager::Clear(), CGUIColorManager::Clear(), CGUIWindowManager::Delete(), CGUIAudioManager::Enable(), g_fontManager, g_SkinInfo, CGUIComponent::GetAudioManager(), CGUIComponent::GetColorManager(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CGUIComponent::GetLargeTextureManager(), CServiceBroker::GetTextureCache(), CGUIComponent::GetTextureManager(), CGUIComponent::GetWindowManager(), CLog::Log(), LOGINFO, m_saveSkinOnUnloading, and WINDOW_DIALOG_FULLSCREEN_INFO.
Referenced by LoadSkin(), KODI::WINDOWING::X11::CWinSystemX11GLContext::RefreshGLContext(), and UnloadSkin().
Friends And Related Symbol Documentation
CApplication
friend class CApplication friend
Member Data Documentation
m_bInitializing
bool& CApplicationSkinHandling::m_bInitializing protected
Referenced by ReloadSkin().
m_confirmSkinChange
bool CApplicationSkinHandling::m_confirmSkinChange = true protected
Referenced by OnSettingChanged(), and ReloadSkin().
m_ignoreSkinSettingChanges
bool CApplicationSkinHandling::m_ignoreSkinSettingChanges = false protected
Referenced by OnSettingChanged().
m_msgCb
IMsgTargetCallback* CApplicationSkinHandling::m_msgCb protected
Referenced by LoadSkin().
m_saveSkinOnUnloading
bool CApplicationSkinHandling::m_saveSkinOnUnloading = true protected
Referenced by UnloadSkin().
m_wCb
IWindowManagerCallback* CApplicationSkinHandling::m_wCb protected
Referenced by LoadSkin().
The documentation for this class was generated from the following files:
ApplicationSkinHandling.h
ApplicationSkinHandling.cpp