Kodi Documentation: ADDON::Interface_Network Struct Reference
ADDON::Interface_Network Struct Reference
Global general Add-on to Kodi callback functions.
#include <Network.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static bool wake_on_lan (void *kodiBase, const char *mac)
callback functions from add-on to kodi
static char * get_ip_address (void *kodiBase)
static char * get_hostname (void *kodiBase)
static char * get_user_agent (void *kodiBase)
static bool is_local_host (void *kodiBase, const char *hostname)
static bool is_host_on_lan (void *kodiBase, const char *hostname, bool offLineCheck)
static char * dns_lookup (void *kodiBase, const char *url, bool *ret)
static char * url_encode (void *kodiBase, const char *url)
Detailed Description
Global general Add-on to Kodi callback functions.
To hold network functions not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/Network.h"
Member Function Documentation
DeInit()
void ADDON::Interface_Network::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_Addon::kodi_network, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_Base::DeInitInterface().
dns_lookup()
char * ADDON::Interface_Network::dns_lookup (void * kodiBase, const char * url, bool * ret) static
References CLog::Log(), LOGERROR, and CDNSNameCache::Lookup().
Referenced by Init().
get_hostname()
char * ADDON::Interface_Network::get_hostname (void * kodiBase) static
References CServiceBroker::GetNetwork(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_ip_address()
char * ADDON::Interface_Network::get_ip_address (void * kodiBase) static
References CNetworkInterface::GetCurrentIPAddress(), CNetworkBase::GetFirstConnectedInterface(), CServiceBroker::GetNetwork(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_user_agent()
char * ADDON::Interface_Network::get_user_agent (void * kodiBase) static
References CSysInfo::GetUserAgent(), CLog::Log(), and LOGERROR.
Referenced by Init().
Init()
void ADDON::Interface_Network::Init (AddonGlobalInterface * addonInterface) static
References dns_lookup(), AddonToKodiFuncTable_kodi_network::dns_lookup, get_hostname(), AddonToKodiFuncTable_kodi_network::get_hostname, get_ip_address(), AddonToKodiFuncTable_kodi_network::get_ip_address, get_user_agent(), AddonToKodiFuncTable_kodi_network::get_user_agent, is_host_on_lan(), AddonToKodiFuncTable_kodi_network::is_host_on_lan, is_local_host(), AddonToKodiFuncTable_kodi_network::is_local_host, AddonToKodiFuncTable_Addon::kodi_network, AddonGlobalInterface::toKodi, url_encode(), AddonToKodiFuncTable_kodi_network::url_encode, wake_on_lan(), and AddonToKodiFuncTable_kodi_network::wake_on_lan.
Referenced by ADDON::Interface_Base::InitInterface().
is_host_on_lan()
bool ADDON::Interface_Network::is_host_on_lan (void * kodiBase, const char * hostname, bool offLineCheck) static
TODO change to use the LanCheckMode enum class on the API signature
References ANY_PRIVATE_SUBNET, URIUtils::IsHostOnLAN(), CLog::Log(), LOGERROR, and ONLY_LOCAL_SUBNET.
Referenced by Init().
is_local_host()
bool ADDON::Interface_Network::is_local_host (void * kodiBase, const char * hostname) static
References CServiceBroker::GetNetwork(), CNetworkBase::IsLocalHost(), CLog::Log(), and LOGERROR.
Referenced by Init().
url_encode()
char * ADDON::Interface_Network::url_encode (void * kodiBase, const char * url) static
References CLog::Log(), and LOGERROR.
Referenced by Init().
wake_on_lan()
bool ADDON::Interface_Network::wake_on_lan (void * kodiBase, const char * mac) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References CServiceBroker::GetNetwork(), CLog::Log(), LOGERROR, and CNetworkBase::WakeOnLan().
Referenced by Init().
The documentation for this struct was generated from the following files:
addons/interfaces/Network.h
addons/interfaces/Network.cpp