Kodi Documentation: AESinkAUDIOTRACK.cpp File Reference
AESinkAUDIOTRACK.cpp File Reference
#include "AESinkAUDIOTRACK.h"
#include "ServiceBroker.h"
#include "cores/AudioEngine/AESinkFactory.h"
#include "cores/AudioEngine/Utils/AEUtil.h"
#include "settings/AdvancedSettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "utils/StringUtils.h"
#include "utils/TimeUtils.h"
#include "utils/log.h"
#include "platform/android/activity/XBMCApp.h"
#include <numeric>
#include <androidjni/AudioFormat.h>
#include <androidjni/AudioManager.h>
#include <androidjni/AudioTrack.h>
#include <androidjni/Build.h>
#include <unistd.h>
Functions
static int AEStreamFormatToATFormat (const CAEStreamInfo::DataType &dt)
static AEChannel AUDIOTRACKChannelToAEChannel (int atChannel)
static CAEChannelInfo AUDIOTRACKChannelMaskToAEChannelMap (int atMask)
static int AEChannelMapToAUDIOTRACKChannelMask (CAEChannelInfo info)
Variables
const unsigned int MAX_RAW_AUDIO_BUFFER_HD = 61440
const unsigned int MAX_RAW_AUDIO_BUFFER = 16384
const unsigned int MOVING_AVERAGE_MAX_MEMBERS = 3
const uint64_t UINT64_LOWER_BYTES = 0x00000000FFFFFFFF
const uint64_t UINT64_UPPER_BYTES = 0xFFFFFFFF00000000
static const AEChannel KnownChannels []
Function Documentation
AEChannelMapToAUDIOTRACKChannelMask()
static int AEChannelMapToAUDIOTRACKChannelMask (CAEChannelInfo info) static
References KnownChannels.
Referenced by CAESinkAUDIOTRACK::Initialize(), and CAESinkAUDIOTRACK::UpdateAvailablePassthroughCapabilities().
AEStreamFormatToATFormat()
static int AEStreamFormatToATFormat (const CAEStreamInfo::DataType & dt) static
References CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, and CAEStreamInfo::STREAM_TYPE_TRUEHD.
Referenced by CAESinkAUDIOTRACK::Initialize().
AUDIOTRACKChannelMaskToAEChannelMap()
static CAEChannelInfo AUDIOTRACKChannelMaskToAEChannelMap (int atMask) static
References AUDIOTRACKChannelToAEChannel().
Referenced by CAESinkAUDIOTRACK::Initialize().
AUDIOTRACKChannelToAEChannel()
static AEChannel AUDIOTRACKChannelToAEChannel (int atChannel) static
References AE_CH_BC, AE_CH_BL, AE_CH_BR, AE_CH_FC, AE_CH_FL, AE_CH_FLOC, AE_CH_FR, AE_CH_FROC, AE_CH_LFE, AE_CH_SL, AE_CH_SR, and AE_CH_UNKNOWN1.
Referenced by AUDIOTRACKChannelMaskToAEChannelMap().
Variable Documentation
KnownChannels
const AEChannel KnownChannels[] static
Initial value:
= {AE_CH_FL, AE_CH_FR,   AE_CH_FC,   AE_CH_LFE,
                                          AE_CH_SL, AE_CH_SR,   AE_CH_BL,   AE_CH_BR,
                                          AE_CH_BC, AE_CH_BLOC, AE_CH_BROC, AE_CH_NULL}
Referenced by AEChannelMapToAUDIOTRACKChannelMask(), CDVDAudioCodecAndroidMediaCodec::GetChannelMap(), and CAESinkAUDIOTRACK::UpdateAvailablePCMCapabilities().
MAX_RAW_AUDIO_BUFFER
const unsigned int MAX_RAW_AUDIO_BUFFER = 16384
Referenced by CAESinkAUDIOTRACK::Initialize().
MAX_RAW_AUDIO_BUFFER_HD
const unsigned int MAX_RAW_AUDIO_BUFFER_HD = 61440
Referenced by CAESinkAUDIOTRACK::Initialize().
MOVING_AVERAGE_MAX_MEMBERS
const unsigned int MOVING_AVERAGE_MAX_MEMBERS = 3
Referenced by CAESinkAUDIOTRACK::GetMovingAverageDelay().
UINT64_LOWER_BYTES
const uint64_t UINT64_LOWER_BYTES = 0x00000000FFFFFFFF
Referenced by CAESinkAUDIOTRACK::GetDelay().
UINT64_UPPER_BYTES
const uint64_t UINT64_UPPER_BYTES = 0xFFFFFFFF00000000
Referenced by CAESinkAUDIOTRACK::GetDelay().