Kodi Documentation: JSONRPC::CJSONRPCUtils Class Reference
JSONRPC::CJSONRPCUtils Class Reference
#include <JSONRPCUtils.h>
Static Public Member Functions
static void NotifyItemUpdated ()
static void NotifyItemUpdated (const std::shared_ptr< CFileItem > &item)
static void NotifyItemUpdated (const CVideoInfoTag &info, const std::map< std::string, std::string > &artwork)
Member Function Documentation
NotifyItemUpdated() [1/3]
void CJSONRPCUtils::NotifyItemUpdated () static
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, and GUI_MSG_UPDATE.
Referenced by JSONRPC::CVideoLibrary::RemoveVideo(), JSONRPC::CAudioLibrary::SetAlbumDetails(), JSONRPC::CAudioLibrary::SetArtistDetails(), JSONRPC::CVideoLibrary::SetEpisodeDetails(), JSONRPC::CFileOperations::SetFileDetails(), JSONRPC::CVideoLibrary::SetMovieDetails(), JSONRPC::CVideoLibrary::SetMovieSetDetails(), JSONRPC::CVideoLibrary::SetMusicVideoDetails(), JSONRPC::CVideoLibrary::SetSeasonDetails(), JSONRPC::CAudioLibrary::SetSongDetails(), and JSONRPC::CVideoLibrary::SetTVShowDetails().
NotifyItemUpdated() [2/3]
void CJSONRPCUtils::NotifyItemUpdated (const CVideoInfoTag & info, const std::map< std::string, std::string > & artwork) static
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, and GUI_MSG_UPDATE_ITEM.
NotifyItemUpdated() [3/3]
void CJSONRPCUtils::NotifyItemUpdated (const std::shared_ptr< CFileItem > & item) static
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, and GUI_MSG_UPDATE_ITEM.
The documentation for this class was generated from the following files:
JSONRPCUtils.h
JSONRPC.cpp