Kodi Documentation: CTimeUtils Class Reference
CTimeUtils Class Reference
#include <TimeUtils.h>
Static Public Member Functions
static void UpdateFrameTime (bool flip)
Update the time frame.
static unsigned int GetFrameTime ()
Returns the frame time in MS.
static CDateTime GetLocalTime (time_t time)
static std::string WithoutSeconds (const std::string &hhmmss)
Returns a time string without seconds, i.e: HH:MM.
Static Private Attributes
static unsigned int frameTime = 0
Member Function Documentation
GetFrameTime()
unsigned int CTimeUtils::GetFrameTime () static
Returns the frame time in MS.
Note
Not threadsafe
References frameTime.
Referenced by CInertialScrollingHandler::CheckForInertialScrolling(), CGUILargeTextureManager::CLargeTexture::DecrRef(), CGUILargeTextureManager::CLargeTexture::DeleteIfRequired(), CGUIDialogKaiToast::DoWork(), CGUIDialogKaiToast::FrameMove(), CApplication::FrameMove(), CInfoLoader::GetInfo(), CScrollInfo::GetPixelsPerFrame(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetSystemHeatInfo(), KODI::UTILS::MOVING_SPEED::CMovingSpeed::GetUpdatedDistance(), CMouseStat::HandleEvent(), CMouseStat::IsActive(), CGUIBaseContainer::OnAction(), UPNP::CUPnPPlayerController::OnGetPositionInfoResult(), CInfoLoader::OnJobComplete(), CGUIDialogExtendedProgressBar::OnMessage(), CInertialScrollingHandler::ProcessInertialScroll(), CInfoLoader::Refresh(), CGUIDialog::ResetAutoClose(), CGUIDialogKaiToast::ResetTimer(), CMouseStat::SetActive(), CApplication::Stop(), CInertialScrollingHandler::PanPoint::TimeElapsed(), CStaticListProvider::Update(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::UpdateFPS(), UPNP::CUPnPPlayerController::UpdatePositionInfo(), and CGUIDialog::UpdateVisibility().
GetLocalTime()
CDateTime CTimeUtils::GetLocalTime (time_t time) static
UpdateFrameTime()
void CTimeUtils::UpdateFrameTime (bool flip) static
Update the time frame.
Note
Not threadsafe
References frameTime, CGraphicContext::GetFPS(), CWinSystemBase::GetGfxContext(), and CServiceBroker::GetWinSystem().
Referenced by CApplication::Render().
WithoutSeconds()
std::string CTimeUtils::WithoutSeconds (const std::string & hhmmss) static
Returns a time string without seconds, i.e: HH:MM.
Parameters
hhmmss Time string in the format HH:MM:SS
Referenced by CSettingTime::SetTime().
Member Data Documentation
frameTime
unsigned int CTimeUtils::frameTime = 0 static private
Referenced by GetFrameTime(), and UpdateFrameTime().
The documentation for this class was generated from the following files:
utils/TimeUtils.h
utils/TimeUtils.cpp