Kodi Documentation: CPictureFolderImageFileLoader Class Reference
CPictureFolderImageFileLoader Class Reference
Generates a thumbnail for a folder in the picture browser, tile 4 images inside the folder.
#include <PictureFolderImageFileLoader.h>
Public Member Functions
CPictureFolderImageFileLoader ()=default
~CPictureFolderImageFileLoader () override=default
bool CanLoad (const std::string &specialType) const override
std::unique_ptr< CTexture > Load (const IMAGE_FILES::CImageFileURL &imageFile) const override
Public Member Functions inherited from IMAGE_FILES::ISpecialImageFileLoader
virtual ~ISpecialImageFileLoader ()=default
Detailed Description
Generates a thumbnail for a folder in the picture browser, tile 4 images inside the folder.
Constructor & Destructor Documentation
CPictureFolderImageFileLoader()
CPictureFolderImageFileLoader::CPictureFolderImageFileLoader () default
~CPictureFolderImageFileLoader()
CPictureFolderImageFileLoader::~CPictureFolderImageFileLoader () override default
Member Function Documentation
CanLoad()
bool CPictureFolderImageFileLoader::CanLoad (const std::string & specialType) const override virtual
Implements IMAGE_FILES::ISpecialImageFileLoader.
Load()
std::unique_ptr< CTexture > CPictureFolderImageFileLoader::Load (const IMAGE_FILES::CImageFileURL & imageFile) const override virtual
Implements IMAGE_FILES::ISpecialImageFileLoader.
References CPicture::CreateTiledThumb(), XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::CDirectory::GetDirectory(), CServiceBroker::GetFileExtensionProvider(), CFileExtensionProvider::GetPictureExtensions(), IMAGE_FILES::CImageFileURL::GetTargetFile(), CFileItemList::IsEmpty(), KODI::PLAYLIST::IsPlayList(), CFileItemList::Randomize(), CFileItemList::Remove(), and CFileItemList::Size().
The documentation for this class was generated from the following files:
PictureFolderImageFileLoader.h
PictureFolderImageFileLoader.cpp