Kodi Documentation: UpdateAddons Class Reference
UpdateAddons Class Reference
Private Member Functions
void Run () override
Additional Inherited Members
Public Member Functions inherited from IRunnable
virtual void Cancel ()
virtual ~IRunnable ()=default
Member Function Documentation
Run()
void UpdateAddons::Run () inline override private virtual
Implements IRunnable.
References CServiceBroker::GetAddonMgr(), ADDON::CAddonMgr::GetAvailableUpdates(), ADDON::CAddonInstaller::GetInstance(), and ADDON::CAddonInstaller::InstallOrUpdate().
The documentation for this class was generated from the following file:
GUIWindowAddonBrowser.cpp