Kodi Documentation: PVR::CONTEXTMENUITEM::PVRClientMenuHook Class Reference
PVR::CONTEXTMENUITEM::PVRClientMenuHook Class Reference
Public Member Functions
PVRClientMenuHook (const CPVRClientMenuHook &hook)
std::string GetLabel (const CFileItem &item) const override
bool IsVisible (const CFileItem &item) const override
bool Execute (const CFileItemPtr &item) const override
const CPVRClientMenuHook & GetHook () const
Public Member Functions inherited from IContextMenuItem
virtual ~IContextMenuItem ()=default
virtual bool IsGroup () const
virtual bool HasParent () const
Private Attributes
const CPVRClientMenuHook m_hook
Constructor & Destructor Documentation
PVRClientMenuHook()
PVR::CONTEXTMENUITEM::PVRClientMenuHook::PVRClientMenuHook (const CPVRClientMenuHook & hook) inline explicit
Member Function Documentation
Execute()
bool PVR::CONTEXTMENUITEM::PVRClientMenuHook::Execute (const CFileItemPtr & item) const override virtual
Implements IContextMenuItem.
References PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), m_hook, and PVR_ERROR_NO_ERROR.
GetHook()
const CPVRClientMenuHook & PVR::CONTEXTMENUITEM::PVRClientMenuHook::GetHook () const inline
References m_hook.
Referenced by PVR::CPVRContextMenuManager::RemoveMenuHook().
GetLabel()
std::string PVR::CONTEXTMENUITEM::PVRClientMenuHook::GetLabel (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References PVR::CPVRClientMenuHook::GetLabel(), and m_hook.
IsVisible()
bool PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References PVR::CPVRClientMenuHook::GetAddonId(), PVR::CPVRManager::GetClient(), CFileItem::GetPath(), CServiceBroker::GetPVRManager(), PVR::CPVRClientMenuHook::IsAllHook(), PVR::CPVRClientMenuHook::IsChannelHook(), CFileItem::IsDeletedPVRRecording(), PVR::CPVRClientMenuHook::IsDeletedRecordingHook(), CFileItem::IsEPG(), PVR::CPVRClientMenuHook::IsEpgHook(), CFileItem::IsPVRChannel(), CFileItem::IsPVRTimer(), PVR::CPVRClientMenuHook::IsRecordingHook(), PVR::CPVRClientMenuHook::IsTimerHook(), CFileItem::IsUsablePVRRecording(), CGUIListItem::m_bIsFolder, m_hook, PVR::CPVRTimersPath::PATH_ADDTIMER, and URIUtils::PathEquals().
Member Data Documentation
m_hook
const CPVRClientMenuHook PVR::CONTEXTMENUITEM::PVRClientMenuHook::m_hook private
Referenced by Execute(), GetHook(), GetLabel(), and IsVisible().
The documentation for this class was generated from the following file:
PVRContextMenus.cpp