Kodi Documentation: class PVRTimerType
class PVRTimerType
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 6. Timer
PVR add-on timer type
To define the content of kodi::addon::CInstancePVRClient::GetTimerTypes() given groups.
Classes
class kodi::addon::PVRTimerType
Functions
void kodi::addon::PVRTimerType::SetId (unsigned int id)
required
This type's identifier. Ids must be > PVR_TIMER_TYPE_NONE.
unsigned int kodi::addon::PVRTimerType::GetId () const
To get with SetAttributes changed values.
void kodi::addon::PVRTimerType::SetAttributes (uint64_t attributes)
required
Defines the attributes for this type (PVR_TIMER_TYPE_* constants).
uint64_t kodi::addon::PVRTimerType::GetAttributes () const
To get with SetAttributes changed values.
void kodi::addon::PVRTimerType::SetDescription (const std::string &description)
optional
A short localized string describing the purpose of the type. (e.g. "Any time at this channel if title matches").
std::string kodi::addon::PVRTimerType::GetDescription () const
To get with SetDescription changed values.
void kodi::addon::PVRTimerType::SetPriorities (const std::vector< PVRTypeIntValue > &priorities, int prioritiesDefault=-1)
optional
Priority value definitions.
std::vector< PVRTypeIntValue > kodi::addon::PVRTimerType::GetPriorities () const
To get with SetPriorities changed values.
void kodi::addon::PVRTimerType::SetPrioritiesDefault (int prioritiesDefault)
optional
The default value for PVRTimer::SetPriority().
int kodi::addon::PVRTimerType::GetPrioritiesDefault () const
To get with SetPrioritiesDefault changed values.
void kodi::addon::PVRTimerType::SetLifetimes (const std::vector< PVRTypeIntValue > &lifetimes, int lifetimesDefault=-1)
optional
Lifetime value definitions.
std::vector< PVRTypeIntValue > kodi::addon::PVRTimerType::GetLifetimes () const
To get with SetLifetimes changed values.
void kodi::addon::PVRTimerType::SetLifetimesDefault (int lifetimesDefault)
optional
The default value for SetLifetimes().
int kodi::addon::PVRTimerType::GetLifetimesDefault () const
To get with SetLifetimesDefault changed values.
void kodi::addon::PVRTimerType::SetPreventDuplicateEpisodes (const std::vector< PVRTypeIntValue > &preventDuplicateEpisodes, int preventDuplicateEpisodesDefault=-1)
optional
Prevent duplicate episodes value definitions.
std::vector< PVRTypeIntValue > kodi::addon::PVRTimerType::GetPreventDuplicateEpisodes () const
To get with SetPreventDuplicateEpisodes changed values.
void kodi::addon::PVRTimerType::SetPreventDuplicateEpisodesDefault (int preventDuplicateEpisodesDefault)
optional
The default value for PVRTimer::SetPreventDuplicateEpisodes().
int kodi::addon::PVRTimerType::GetPreventDuplicateEpisodesDefault () const
To get with SetPreventDuplicateEpisodesDefault changed values.
void kodi::addon::PVRTimerType::SetRecordingGroups (const std::vector< PVRTypeIntValue > &recordingGroup, int recordingGroupDefault=-1)
optional
Array containing the possible values of PVRTimer::SetRecordingGroup()
std::vector< PVRTypeIntValue > kodi::addon::PVRTimerType::GetRecordingGroups () const
To get with SetRecordingGroups changed values.
void kodi::addon::PVRTimerType::SetRecordingGroupDefault (int recordingGroupDefault)
optional
The default value for PVRTimer::SetRecordingGroup().
int kodi::addon::PVRTimerType::GetRecordingGroupDefault () const
To get with SetRecordingGroupDefault changed values.
void kodi::addon::PVRTimerType::SetMaxRecordings (const std::vector< PVRTypeIntValue > &maxRecordings, int maxRecordingsDefault=-1)
optional
Array containing the possible values of PVRTimer::SetMaxRecordings().
std::vector< PVRTypeIntValue > kodi::addon::PVRTimerType::GetMaxRecordings () const
To get with SetMaxRecordings changed values.
void kodi::addon::PVRTimerType::SetMaxRecordingsDefault (int maxRecordingsDefault)
optional
The default value for SetMaxRecordings().
int kodi::addon::PVRTimerType::GetMaxRecordingsDefault () const
To get with SetMaxRecordingsDefault changed values.
void kodi::addon::PVRTimerType::SetCustomSettingDefinitions (const std::vector< PVRSettingDefinition > &defs)
optional
Array containing the possible custom integer setting definitions.
std::vector< PVRSettingDefinition > kodi::addon::PVRTimerType::GetCustomSettingDefinitions () const
To get with SetCustomSettingDefinitions changed values.
Detailed Description
PVR add-on timer type
To define the content of kodi::addon::CInstancePVRClient::GetTimerTypes() given groups.
@ingroup cpp_kodi_addon_pvr_Defs_Timer_PVRTimerType
The following table contains values that can be set with class PVRTimerType :
Name Type Set call Get call Usage
Identifier unsigned int SetId GetId required to set
Attributes unsigned int SetAttributes GetAttributes required to set
Description std::string SetDescription GetDescription optional
Priority selection PVRTypeIntValue SetPriorities GetPriorities optional
Priority default selection int SetPrioritiesDefault GetPrioritiesDefault optional
Lifetime selection PVRTypeIntValue SetLifetimes GetLifetimes optional
Lifetime default selection int SetLifetimesDefault GetLifetimesDefault optional
Prevent duplicate episodes selection PVRTypeIntValue SetPreventDuplicateEpisodes GetPreventDuplicateEpisodes optional
Prevent duplicate episodes default int SetPreventDuplicateEpisodesDefault GetPreventDuplicateEpisodesDefault optional
Recording group selection PVRTypeIntValue SetRecordingGroups GetRecordingGroups optional
Recording group default int SetRecordingGroupDefault GetRecordingGroupDefault optional
Max recordings selection PVRTypeIntValue SetMaxRecordings GetMaxRecordings optional
Max recordings default int SetMaxRecordingsDefault GetMaxRecordingsDefault optional
Custom setting definitions PVRSettingDefinition SetCustomSettingDefinitions GetCustomSettingDefinitions optional
Function Documentation
GetAttributes()
uint64_t kodi::addon::PVRTimerType::GetAttributes () const inline
To get with SetAttributes changed values.
References PVR_TIMER_TYPE::iAttributes, and kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure.
GetCustomSettingDefinitions()
std::vector< PVRSettingDefinition > kodi::addon::PVRTimerType::GetCustomSettingDefinitions () const inline
To get with SetCustomSettingDefinitions changed values.
References PVR_TIMER_TYPE::customSettingDefs, PVR_TIMER_TYPE::iCustomSettingDefsSize, and kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure.
GetDescription()
std::string kodi::addon::PVRTimerType::GetDescription () const inline
To get with SetDescription changed values.
References kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure, and PVR_TIMER_TYPE::strDescription.
GetId()
unsigned int kodi::addon::PVRTimerType::GetId () const inline
To get with SetAttributes changed values.
References PVR_TIMER_TYPE::iId, and kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure.
GetLifetimes()
std::vector< PVRTypeIntValue > kodi::addon::PVRTimerType::GetLifetimes () const inline
To get with SetLifetimes changed values.
References PVR_TIMER_TYPE::iLifetimesSize, PVR_ATTRIBUTE_INT_VALUE::iValue, PVR_TIMER_TYPE::lifetimes, kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure, and PVR_ATTRIBUTE_INT_VALUE::strDescription.
GetLifetimesDefault()
int kodi::addon::PVRTimerType::GetLifetimesDefault () const inline
To get with SetLifetimesDefault changed values.
References PVR_TIMER_TYPE::iLifetimesDefault, and kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure.
GetMaxRecordings()
std::vector< PVRTypeIntValue > kodi::addon::PVRTimerType::GetMaxRecordings () const inline
To get with SetMaxRecordings changed values.
References PVR_TIMER_TYPE::iMaxRecordingsSize, PVR_ATTRIBUTE_INT_VALUE::iValue, kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure, PVR_TIMER_TYPE::maxRecordings, and PVR_ATTRIBUTE_INT_VALUE::strDescription.
GetMaxRecordingsDefault()
int kodi::addon::PVRTimerType::GetMaxRecordingsDefault () const inline
To get with SetMaxRecordingsDefault changed values.
References PVR_TIMER_TYPE::iMaxRecordingsDefault, and kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure.
GetPreventDuplicateEpisodes()
std::vector< PVRTypeIntValue > kodi::addon::PVRTimerType::GetPreventDuplicateEpisodes () const inline
To get with SetPreventDuplicateEpisodes changed values.
References PVR_TIMER_TYPE::iPreventDuplicateEpisodesSize, PVR_ATTRIBUTE_INT_VALUE::iValue, kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure, PVR_TIMER_TYPE::preventDuplicateEpisodes, and PVR_ATTRIBUTE_INT_VALUE::strDescription.
GetPreventDuplicateEpisodesDefault()
int kodi::addon::PVRTimerType::GetPreventDuplicateEpisodesDefault () const inline
To get with SetPreventDuplicateEpisodesDefault changed values.
References PVR_TIMER_TYPE::iPreventDuplicateEpisodesDefault, and kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure.
GetPriorities()
std::vector< PVRTypeIntValue > kodi::addon::PVRTimerType::GetPriorities () const inline
To get with SetPriorities changed values.
References PVR_TIMER_TYPE::iPrioritiesSize, PVR_ATTRIBUTE_INT_VALUE::iValue, kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure, PVR_TIMER_TYPE::priorities, and PVR_ATTRIBUTE_INT_VALUE::strDescription.
GetPrioritiesDefault()
int kodi::addon::PVRTimerType::GetPrioritiesDefault () const inline
To get with SetPrioritiesDefault changed values.
References PVR_TIMER_TYPE::iPrioritiesDefault, and kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure.
GetRecordingGroupDefault()
int kodi::addon::PVRTimerType::GetRecordingGroupDefault () const inline
To get with SetRecordingGroupDefault changed values.
References PVR_TIMER_TYPE::iRecordingGroupDefault, and kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure.
GetRecordingGroups()
std::vector< PVRTypeIntValue > kodi::addon::PVRTimerType::GetRecordingGroups () const inline
To get with SetRecordingGroups changed values.
References PVR_TIMER_TYPE::iRecordingGroupSize, PVR_ATTRIBUTE_INT_VALUE::iValue, kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure, PVR_TIMER_TYPE::recordingGroup, and PVR_ATTRIBUTE_INT_VALUE::strDescription.
SetAttributes()
void kodi::addon::PVRTimerType::SetAttributes (uint64_t attributes) inline
required
Defines the attributes for this type (PVR_TIMER_TYPE_* constants).
To defines the attributes for a type. These values are bit fields that can be used together.
Example:
kodi::addon::PVRTimerType tag;
tag.SetAttributes(PVR_TIMER_TYPE_IS_MANUAL | PVR_TIMER_TYPE_IS_REPEATING);
References PVR_TIMER_TYPE::iAttributes, and kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure.
SetCustomSettingDefinitions()
void kodi::addon::PVRTimerType::SetCustomSettingDefinitions (const std::vector< PVRSettingDefinition > & defs) inline
optional
Array containing the possible custom integer setting definitions.
Parameters
[in] defs List of integer setting definitions.
@ingroup cpp_kodi_addon_pvr_Defs_General_PVRIntSettingDefinition
The following table contains values that can be set with cpp_kodi_addon_pvr_Defs_General_PVRIntSettingDefinition :
Name Type Set call Get call Usage
Values PVRTypeIntValue SetValues GetValues optional
Default value int SetDefaultValue GetDefaultValue optional
Min value int SetMinValue GetMinValue optional
Step int SetStep GetStep optional
Max value int SetMaxValue GetMaxValue optional
References PVR_TIMER_TYPE::customSettingDefs, PVR_TIMER_TYPE::iCustomSettingDefsSize, kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure, and kodi::addon::PVRSettingDefinition::ReallocAndCopyData().
SetDescription()
void kodi::addon::PVRTimerType::SetDescription (const std::string & description) inline
optional
A short localized string describing the purpose of the type. (e.g. "Any time at this channel if title matches").
If left blank, Kodi will generate a description based on the attributes REPEATING and MANUAL. (e.g. "Repeating EPG-based.")
References kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure, kodi::addon::ReallocAndCopyString(), and PVR_TIMER_TYPE::strDescription.
SetId()
void kodi::addon::PVRTimerType::SetId (unsigned int id) inline
required
This type's identifier. Ids must be > PVR_TIMER_TYPE_NONE.
References id, PVR_TIMER_TYPE::iId, and kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure.
SetLifetimes()
void kodi::addon::PVRTimerType::SetLifetimes (const std::vector< PVRTypeIntValue > & lifetimes, int lifetimesDefault = -1) inline
optional
Lifetime value definitions.
Array containing the possible values for PVRTimer::SetLifetime().
Parameters
[in] lifetimes List of lifetimes values
[in] lifetimesDefault [opt] The default value in list, can also be set by SetLifetimesDefault()
The following table contains values that can be set with class PVRTypeIntValue :
Name Type Set call Get call
Value int SetValue GetValue
Description std::string SetDescription GetDescription
Remarks
Further can there be used his class constructor to set values.
References PVR_TIMER_TYPE::iLifetimesDefault, PVR_TIMER_TYPE::iLifetimesSize, PVR_TIMER_TYPE::lifetimes, kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure, and kodi::addon::PVRTypeIntValue::ReallocAndCopyData().
SetLifetimesDefault()
void kodi::addon::PVRTimerType::SetLifetimesDefault (int lifetimesDefault) inline
optional
The default value for SetLifetimes().
Note
Must be filled if SetLifetimes contain values and not defined there on second function value.
References PVR_TIMER_TYPE::iLifetimesDefault, and kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure.
SetMaxRecordings()
void kodi::addon::PVRTimerType::SetMaxRecordings (const std::vector< PVRTypeIntValue > & maxRecordings, int maxRecordingsDefault = -1) inline
optional
Array containing the possible values of PVRTimer::SetMaxRecordings().
Parameters
[in] maxRecordings List of max recordings values
[in] maxRecordingsDefault [opt] The default value in list, can also be set by SetMaxRecordingsDefault()
The following table contains values that can be set with class PVRTypeIntValue :
Name Type Set call Get call
Value int SetValue GetValue
Description std::string SetDescription GetDescription
Remarks
Further can there be used his class constructor to set values.
References PVR_TIMER_TYPE::iMaxRecordingsDefault, PVR_TIMER_TYPE::iMaxRecordingsSize, kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure, PVR_TIMER_TYPE::maxRecordings, and kodi::addon::PVRTypeIntValue::ReallocAndCopyData().
SetMaxRecordingsDefault()
void kodi::addon::PVRTimerType::SetMaxRecordingsDefault (int maxRecordingsDefault) inline
optional
The default value for SetMaxRecordings().
Can be set with here if on SetMaxRecordings not given as second value.
References PVR_TIMER_TYPE::iMaxRecordingsDefault, and kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure.
SetPreventDuplicateEpisodes()
void kodi::addon::PVRTimerType::SetPreventDuplicateEpisodes (const std::vector< PVRTypeIntValue > & preventDuplicateEpisodes, int preventDuplicateEpisodesDefault = -1) inline
optional
Prevent duplicate episodes value definitions.
Array containing the possible values for PVRTimer::SetPreventDuplicateEpisodes().
Note
Must be filled if PVRTimer::SetPreventDuplicateEpisodes() is not empty.
Parameters
[in] preventDuplicateEpisodes List of duplicate episodes values
[in] preventDuplicateEpisodesDefault [opt] The default value in list, can also be set by SetPreventDuplicateEpisodesDefault()
The following table contains values that can be set with class PVRTypeIntValue :
Name Type Set call Get call
Value int SetValue GetValue
Description std::string SetDescription GetDescription
Remarks
Further can there be used his class constructor to set values.
References PVR_TIMER_TYPE::iPreventDuplicateEpisodesDefault, PVR_TIMER_TYPE::iPreventDuplicateEpisodesSize, kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure, PVR_TIMER_TYPE::preventDuplicateEpisodes, and kodi::addon::PVRTypeIntValue::ReallocAndCopyData().
SetPreventDuplicateEpisodesDefault()
void kodi::addon::PVRTimerType::SetPreventDuplicateEpisodesDefault (int preventDuplicateEpisodesDefault) inline
optional
The default value for PVRTimer::SetPreventDuplicateEpisodes().
Note
Must be filled if SetPreventDuplicateEpisodes contain values and not defined there on second function value.
References PVR_TIMER_TYPE::iPreventDuplicateEpisodesDefault, and kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure.
SetPriorities()
void kodi::addon::PVRTimerType::SetPriorities (const std::vector< PVRTypeIntValue > & priorities, int prioritiesDefault = -1) inline
optional
Priority value definitions.
Array containing the possible values for PVRTimer::SetPriority().
Parameters
[in] priorities List of priority values
[in] prioritiesDefault [opt] The default value in list, can also be set by SetPrioritiesDefault()
The following table contains values that can be set with class PVRTypeIntValue :
Name Type Set call Get call
Value int SetValue GetValue
Description std::string SetDescription GetDescription
Remarks
Further can there be used his class constructor to set values.
References PVR_TIMER_TYPE::iPrioritiesDefault, PVR_TIMER_TYPE::iPrioritiesSize, kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure, PVR_TIMER_TYPE::priorities, and kodi::addon::PVRTypeIntValue::ReallocAndCopyData().
SetPrioritiesDefault()
void kodi::addon::PVRTimerType::SetPrioritiesDefault (int prioritiesDefault) inline
optional
The default value for PVRTimer::SetPriority().
Note
Must be filled if SetPriorities contain values and not defined there on second function value.
References PVR_TIMER_TYPE::iPrioritiesDefault, and kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure.
SetRecordingGroupDefault()
void kodi::addon::PVRTimerType::SetRecordingGroupDefault (int recordingGroupDefault) inline
optional
The default value for PVRTimer::SetRecordingGroup().
Note
Must be filled if SetRecordingGroups contain values and not defined there on second function value.
References PVR_TIMER_TYPE::iRecordingGroupDefault, and kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure.
SetRecordingGroups()
void kodi::addon::PVRTimerType::SetRecordingGroups (const std::vector< PVRTypeIntValue > & recordingGroup, int recordingGroupDefault = -1) inline
optional
Array containing the possible values of PVRTimer::SetRecordingGroup()
Parameters
[in] recordingGroup List of recording group values
[in] recordingGroupDefault [opt] The default value in list, can also be set by SetRecordingGroupDefault()
The following table contains values that can be set with class PVRTypeIntValue :
Name Type Set call Get call
Value int SetValue GetValue
Description std::string SetDescription GetDescription
Remarks
Further can there be used his class constructor to set values.
References PVR_TIMER_TYPE::iRecordingGroupDefault, PVR_TIMER_TYPE::iRecordingGroupSize, kodi::addon::DynamicCStructHdl< PVRTimerType, PVR_TIMER_TYPE >::m_cStructure, kodi::addon::PVRTypeIntValue::ReallocAndCopyData(), and PVR_TIMER_TYPE::recordingGroup.