Kodi Documentation: ReplayGain.cpp File Reference
ReplayGain.cpp File Reference
#include "ReplayGain.h"
#include "utils/StringUtils.h"
#include <stdlib.h>
Functions
static bool TypeIsValid (ReplayGain::Type aType)
static int index (ReplayGain::Type aType)
Function Documentation
index()
static int index (ReplayGain::Type aType) static
Referenced by XBMCAddon::xbmc::PlayList::add(), JSONRPC::CPlaylistOperations::Add(), MUSIC_INFO::CMusicInfoTag::AddArtistRole(), CDVDAudioCodecAndroidMediaCodec::AddData(), JSONRPC::CJSONServiceDescription::AddEnum(), CGUIDialogVideoInfo::AddItemsToTag(), JSONRPC::CJSONServiceDescription::addMethod(), kodi::addon::CInstancePeripheral::ADDON_GetJoystickInfo(), kodi::addon::CInstancePeripheral::ADDON_PowerOffJoystick(), kodi::addon::CInstanceGame::ADDON_SetCheat(), OVERLAY::CRenderer::AddOverlay(), JSONRPC::CJSONServiceDescription::addReferenceTypeDefinition(), CGUIDialogSettingsBase::AddSetting(), CMusicDatabase::AddSongGenres(), CVideoPlayer::AddSubtitleFile(), CRendererBase::AddVideoPicture(), CRendererDRMPRIME::AddVideoPicture(), CRendererDRMPRIMEGLES::AddVideoPicture(), CRendererMediaCodec::AddVideoPicture(), CRendererMediaCodecSurface::AddVideoPicture(), CLinuxRendererGL::AddVideoPicture(), CLinuxRendererGLES::AddVideoPicture(), CWinRenderer::AddVideoPicture(), CRenderManager::AddVideoPicture(), CRendererVAAPIGLES::AfterRenderHook(), MUSIC_INFO::CMusicInfoTag::AppendAlbumArtist(), MUSIC_INFO::CMusicInfoTag::AppendArtist(), MUSIC_INFO::CMusicInfoTag::AppendGenre(), UPNP::BuildObject(), KODI::GAME::CGUIControllerButton::CGUIControllerButton(), CGUIControlSpinExSetting::CGUIControlSpinExSetting(), KODI::GAME::CGUIFeatureButton::CGUIFeatureButton(), CLinuxRendererGL::CheckVideoParameters(), CHTTPVfsHandler::CHTTPVfsHandler(), kodi::tools::StringUtils::CompareNoCase(), KODI::UTILS::StringUtils::CompareNoCase(), CSettingPath::copy(), CHttpResponse::Create(), KODI::GAME::CGUIFeatureFactory::CreateButton(), CLinuxRendererGL::CreateNV12Texture(), CLinuxRendererGLES::CreateNV12Texture(), CRendererBase::CreateRenderBuffer(), CGUIFontTTFDX::CreateStaticIndexBuffer(), CGUIFontTTFGL::CreateStaticVertexBuffers(), CGUIFontTTFGLES::CreateStaticVertexBuffers(), CLinuxRendererGL::CreateTexture(), CLinuxRendererGLES::CreateTexture(), CRendererMediaCodec::CreateTexture(), CRendererVAAPIGL::CreateTexture(), CRendererVAAPIGLES::CreateTexture(), CRendererVDPAU::CreateTexture(), CRendererVTB::CreateTexture(), CRendererVDPAU::CreateVDPAUTexture(), CRendererVDPAU::CreateVDPAUTexture420(), CLinuxRendererGL::CreateYUV422PackedTexture(), CLinuxRendererGL::CreateYV12Texture(), CLinuxRendererGLES::CreateYV12Texture(), CWebSocketFrame::CWebSocketFrame(), CWebSocketFrame::CWebSocketFrame(), KODI::WINDOWING::WAYLAND::CXkbcommonKeymap::CXkbcommonKeymap(), Base64::Decode(), CTeletextDecoder::DecodePage(), CLinuxRendererGL::DeleteNV12Texture(), CLinuxRendererGLES::DeleteNV12Texture(), CProfileManager::DeleteProfile(), CRendererBase::DeleteRenderBuffer(), CLinuxRendererGL::DeleteTexture(), CLinuxRendererGLES::DeleteTexture(), CRendererMediaCodec::DeleteTexture(), CRendererVAAPIGL::DeleteTexture(), CRendererVAAPIGLES::DeleteTexture(), CRendererVDPAU::DeleteTexture(), CRendererVTB::DeleteTexture(), CRendererVDPAU::DeleteVDPAUTexture(), CRendererVDPAU::DeleteVDPAUTexture420(), CLinuxRendererGL::DeleteYUV422PackedTexture(), CLinuxRendererGL::DeleteYV12Texture(), CLinuxRendererGLES::DeleteYV12Texture(), CVideoThumbLoader::DetectAndAddMissingItemData(), CTeletextDecoder::DoFlashing(), CTeletextDecoder::DoRenderPage(), dbiplus::MysqlDataset::dropIndex(), dbiplus::SqliteDataset::dropIndex(), CPythonInvoker::execute(), CCueDocument::ExtractTimeFromIndex(), JSONRPC::CAddonsOperations::FillDetails(), JSONRPC::CFileItemHandler::FillFileItemList(), CGUIControlSpinExSetting::FillFloatSettingControl(), CSettingList::fromValues(), dbiplus::Dataset::fv(), CHttpRanges::Get(), CSelectionStreams::Get(), CSelectionStreams::Get(), ReplayGain::Get(), dbiplus::Dataset::get_field_value(), JSONRPC::CAddonsOperations::GetAddons(), PERIPHERALS::CPeripheralBusAddon::GetAddonWithButtonMap(), JSONRPC::CAudioLibrary::GetAlbums(), CFavouritesService::GetAll(), CAction::GetAmount(), CApplicationPlayer::GetAudioStreamInfo(), CVideoPlayer::GetAudioStreamInfo(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetBool(), CScraperParser::GetBufferParams(), JSONRPC::CPVROperations::GetChannelGroups(), JSONRPC::CPVROperations::GetClients(), KODI::UTILS::GetCollationWeight(), CFanart::GetColor(), CTeletextDecoder::GetColorRGB(), CDVDAudioCodecAndroidMediaCodec::GetData(), DatabaseUtils::GetDatabaseResults(), CGUIEditControl::GetDescriptionByIndex(), KODI::UTILS::FONT::anonymous_namespace{FontUtils.cpp}::GetFamilyNameFromSfnt(), DatabaseUtils::GetField(), PERIPHERALS::CPeripheral::GetIcon(), CFanart::GetImageURL(), CGUIDialogMediaFilter::GetItems(), PERIPHERALS::CPeripheralAddon::GetJoystickProperties(), XBMCAddon::xbmcgui::ControlList::getListItem(), KODI::WINDOWING::GBM::CDRMConnector::GetModeForIndex(), CDVDVideoCodecAndroidMediaCodec::GetOutputPicture(), UPNP::CUPnPServer::GetParentFolder(), PERIPHERALS::CPeripheralAddon::GetPeripheral(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetPlaylistInfo(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetPlaylistInfo(), CFanart::GetPreviewURL(), CProfileManager::GetProfile(), CProfileManager::GetProfile(), JSONRPC::CProfilesOperations::GetProfiles(), JSONRPC::CApplicationOperations::GetProperties(), JSONRPC::CGUIOperations::GetProperties(), JSONRPC::CPlayerOperations::GetProperties(), JSONRPC::CPlaylistOperations::GetProperties(), JSONRPC::CPVROperations::GetProperties(), JSONRPC::CSystemOperations::GetProperties(), JSONRPC::CPlayerOperations::GetPropertyValue(), JSONRPC::CAudioLibrary::GetRecentlyAddedAlbums(), JSONRPC::CAudioLibrary::GetRecentlyPlayedAlbums(), JSONRPC::CJSONServiceDescription::getReferencedTypes(), CDisplaySettings::GetResolutionInfo(), CDisplaySettings::GetResolutionInfo(), CRenderBuffer::GetResource(), CRendererDXVA::CRenderBufferImpl::GetResource(), CVideoDatabase::GetSeasonInfo(), CGUIDialogColorPicker::GetSelectedItem(), CGUIControlGroupList::GetSelectedItem(), CGUIWindowSlideShow::GetSlideShowContents(), JSONRPC::CAudioLibrary::GetSongs(), CDVDDemuxVobsub::GetStream(), CApplicationPlayer::GetSubtitleStreamInfo(), CVideoPlayer::GetSubtitleStreamInfo(), HttpParser::getValue(), CWIN32Util::GetVideoDriverInfo(), CWIN32Util::GetVideoDriverInfoDX(), GroupUtils::Group(), JSONRPC::CJSONRPC::Initialize(), AE::SINK::CAESinkPipewire::Initialize(), PERIPHERALS::CAndroidJoystickState::Initialize(), PVR::CGUIDialogPVRTimerSettings::InitializeChannelsList(), PERIPHERALS::CPeripheralBusAddon::InitializeProperties(), CColorManager::Load3dLut(), JSONRPC::CProfilesOperations::LoadProfile(), LoadProfile(), CProfileManager::LoadProfile(), PERIPHERALS::CPeripheralBusAndroid::LogInputDevice(), CGUIDialogVideoInfo::ManageVideoItemArtwork(), CRendererDRMPRIME::NeedBuffer(), CRendererDRMPRIMEGLES::NeedBuffer(), CRendererVAAPIGLES::NeedBuffer(), CGUIWindowVideoNav::OnClick(), PVR::CGUIDialogPVRChannelManager::OnClickButtonNewChannel(), KODI::GAME::CDialogGameSaves::OnContextMenu(), CGUIMediaWindow::OnFilterItems(), KODI::GAME::CDialogGameStretchMode::OnItemFocus(), KODI::GAME::CDialogGameVideoFilter::OnItemFocus(), KODI::GAME::CDialogGameVideoRotation::OnItemFocus(), KODI::GAME::CDialogInGameSaves::OnItemFocus(), CAndroidKey::onKeyboardEvent(), KODI::GAME::CDialogInGameSaves::OnMenuAction(), KODI::VIDEO::CVideoInfoScanner::OnProcessSeriesFolder(), CGenericTouchPinchDetector::OnTouchDown(), CGenericTouchRotateDetector::OnTouchDown(), CGenericTouchSwipeDetector::OnTouchDown(), CGenericTouchPinchDetector::OnTouchMove(), CGenericTouchRotateDetector::OnTouchMove(), CGenericTouchSwipeDetector::OnTouchMove(), CGenericTouchPinchDetector::OnTouchUp(), CGenericTouchRotateDetector::OnTouchUp(), CGenericTouchSwipeDetector::OnTouchUp(), CGenericTouchRotateDetector::OnTouchUpdate(), CGenericTouchSwipeDetector::OnTouchUpdate(), CDVDInputStreamStack::Open(), JSONRPC::CPlayerOperations::Open(), CVideoPlayer::OpenStream(), CArchive::operator>>(), CArchive::operator>>(), XFILE::CVirtualDirectory::operator[](), XFILE::CVirtualDirectory::operator[](), CMatrix< Order >::operator[](), CMatrix< Order >::operator[](), JSONRPC::JsonRpcMethod::Parse(), ReplayGain::ParseGain(), ReplayGain::ParsePeak(), UPNP::PopulateObjectFromTag(), UPNP::PopulateObjectFromTag(), UPNP::PopulateTagFromObject(), PERIPHERALS::CPeripheralAddon::PowerOffJoystick(), JSONRPC::CJSONServiceDescription::Print(), CGUIControlGroupList::Process(), JSONRPC::CTCPServer::CWebSocketClient::PushBuffer(), CRenderBuffer::QueueCopyFromGPU(), CRendererDRMPRIME::ReleaseBuffer(), CRendererDRMPRIMEGLES::ReleaseBuffer(), CRendererVAAPIGLES::ReleaseBuffer(), CHttpRanges::Remove(), XBMCAddon::xbmcgui::ControlList::removeItem(), CGUIDialogVideoInfo::RemoveItemsFromTag(), CRendererBase::Render(), CRendererDRMPRIMEGLES::Render(), CLinuxRendererGLES::Render(), CLinuxRendererGL::RenderCapture(), CLinuxRendererGLES::RenderCapture(), CRendererMediaCodec::RenderHook(), CLinuxRendererGL::RenderProgressiveWeave(), CLinuxRendererGL::RenderRGB(), CLinuxRendererGLES::RenderSinglePass(), CLinuxRendererGL::RenderSinglePass(), CLinuxRendererGLES::RenderToFBO(), CLinuxRendererGL::RenderToFBO(), CRendererDRMPRIME::RenderUpdate(), CRendererDRMPRIMEGLES::RenderUpdate(), CRendererMediaCodecSurface::RenderUpdate(), CLinuxRendererGL::RenderUpdate(), CLinuxRendererGLES::RenderUpdate(), CWinRenderer::RenderUpdate(), kodi::tools::StringUtils::Replace(), KODI::UTILS::StringUtils::Replace(), kodi::tools::StringUtils::Replace(), KODI::UTILS::StringUtils::Replace(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::ReplaceSpecialKeywordReferences(), JSONRPC::CJSONUtils::SchemaValueTypeToString(), JSONRPC::CTCPServer::CWebSocketClient::Send(), ReplayGain::Set(), JSONRPC::CPlayerOperations::SetAudioStream(), kodi::addon::PeripheralEvent::SetDriverIndex(), CDateTime::SetFromRFC1123DateTime(), ReplayGain::SetGain(), kodi::addon::Peripheral::SetIndex(), ReplayGain::SetPeak(), kodi::addon::PeripheralEvent::SetPeripheralIndex(), CFanart::SetPrimaryFanart(), CGUIDialogSelect::SetSelected(), JSONRPC::CPlayerOperations::SetSubtitle(), CDisplaySettings::SettingOptionsModesFiller(), CSettingList::SetValue(), JSONRPC::CPlayerOperations::SetVideoStream(), CFileItemList::Sort(), CSelectionStreams::Source(), CFileItemList::StackFolders(), CLegacyPathTranslation::TranslatePath(), PERIPHERALS::CPeripheralAddon::UnregisterRemovedDevices(), CGUIControlListSetting::Update(), CSelectionStreams::Update(), CSettingInt::UpdateDynamicOptions(), CSettingString::UpdateDynamicOptions(), KODI::VIDEO::IVideoItemArtworkHandler::UpdateRemoteArt(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::UpdateRemoteArt(), UPNP::CUPnPRenderer::UpdateState(), CLinuxRendererGL::UploadTexture(), CLinuxRendererGLES::UploadTexture(), CRendererMediaCodec::UploadTexture(), CRendererVAAPIGL::UploadTexture(), CRendererVAAPIGLES::UploadTexture(), CRendererVDPAU::UploadTexture(), CRendererVTB::UploadTexture(), CRendererVDPAU::UploadVDPAUTexture(), CRendererVDPAU::UploadVDPAUTexture420(), kodi::tools::StringUtils::UTF8ToUnicode(), KODI::UTILS::UTF8ToUnicode(), CLinuxRendererGL::ValidateRenderer(), CSettingUtils::ValuesToList(), dbiplus::SqliteDatabase::vprepare(), and CWebSocketMessage::~CWebSocketMessage().
TypeIsValid()
static bool TypeIsValid (ReplayGain::Type aType) static
References ReplayGain::NONE, and ReplayGain::TRACK.
Referenced by ReplayGain::Get(), ReplayGain::ParseGain(), ReplayGain::ParsePeak(), ReplayGain::Set(), ReplayGain::SetGain(), and ReplayGain::SetPeak().