Kodi Documentation: anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread Class Reference
anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread Class Reference
Public Member Functions
CWinEventsWaylandThread (wayland::display_t &display)
~CWinEventsWaylandThread () override
void Stop ()
void RoundtripQueue (wayland::event_queue_t const &queue)
wayland::display_t & GetDisplay ()
Private Member Functions
void InterruptPoll ()
void Process () override
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Private Attributes
wayland::display_t & m_display
CFileHandle m_pipeRead
CFileHandle m_pipeWrite
CCriticalSection m_roundtripQueueMutex
std::atomic< wayland::event_queue_t * > m_roundtripQueue {nullptr}
CEvent m_roundtripQueueEvent
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Additional Inherited Members
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Detailed Description
Thread for processing Wayland events
While not strictly needed, reading from the Wayland display file descriptor and dispatching the resulting events is done in an extra thread here. Sometime in the future, MessagePump() might be gone and then the transition will be easier since this extra thread is already here.
Constructor & Destructor Documentation
CWinEventsWaylandThread()
anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread::CWinEventsWaylandThread (wayland::display_t & display) inline
References KODI::UTILS::CScopeGuard< Handle, invalid, Deleter >::attach().
~CWinEventsWaylandThread()
anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread::~CWinEventsWaylandThread () inline override
Member Function Documentation
GetDisplay()
wayland::display_t & anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread::GetDisplay () inline
InterruptPoll()
void anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread::InterruptPoll () inline private
Process()
void anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread::Process (void) inline override private virtual
Reimplemented from CThread.
References CLog::Log(), LOGDEBUG, LOGFATAL, and CEvent::Set().
RoundtripQueue()
void anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread::RoundtripQueue (wayland::event_queue_t const & queue) inline
References CEvent::Reset(), and CEvent::Wait().
Stop()
void anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread::Stop () inline
References CLog::Log(), and LOGDEBUG.
Member Data Documentation
m_display
wayland::display_t& anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread::m_display private
m_pipeRead
CFileHandle anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread::m_pipeRead private
m_pipeWrite
CFileHandle anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread::m_pipeWrite private
m_roundtripQueue
std::atomic<wayland::event_queue_t*> anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread::m_roundtripQueue {nullptr} private
m_roundtripQueueEvent
CEvent anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread::m_roundtripQueueEvent private
m_roundtripQueueMutex
CCriticalSection anonymous_namespace{WinEventsWayland.cpp}::CWinEventsWaylandThread::m_roundtripQueueMutex private
The documentation for this class was generated from the following file:
WinEventsWayland.cpp