Kodi Documentation: CPlatformPosix Class Reference
CPlatformPosix Class Reference
#include <PlatformPosix.h>
Public Member Functions
bool InitStageOne () override
Called at an early stage of application startup.
Public Member Functions inherited from CPlatform
CPlatform ()=default
C'tor.
virtual ~CPlatform ()=default
D'tor.
virtual bool InitStageTwo ()
Called at a middle stage of application startup.
virtual bool InitStageThree ()
Called at a late stage of application startup.
virtual void DeinitStageOne ()
Called at a late stage of application shutdown.
virtual void DeinitStageTwo ()
Called at a middle stage of application shutdown.
virtual void DeinitStageThree ()
Called at an early stage of application shutdown.
virtual bool IsConfigureAddonsAtStartupEnabled ()
Flag whether disabled add-ons - installed via packagemanager or manually - should be offered for configuration and activation on kodi startup for this platform.
virtual bool SupportsUserInstalledBinaryAddons ()
Flag whether this platform supports user installation of binary add-ons.
virtual void PlatformSyslog ()
Print platform specific info to log.
template<class T >
std::shared_ptr< T > GetService ()
Get a platform service instance.
Public Member Functions inherited from CComponentContainer< IPlatformService >
std::shared_ptr< T > GetComponent ()
Obtain a component.
std::shared_ptr< const T > GetComponent () const
Obtain a component.
std::size_t size () const
Returns number of registered components.
Static Public Member Functions
static bool TestQuitFlag ()
static void RequestQuit ()
Static Public Member Functions inherited from CPlatform
static CPlatform * CreateInstance ()
Creates the Platform object.
Static Private Attributes
static std::atomic_flag ms_signalFlag
Additional Inherited Members
Protected Member Functions inherited from CComponentContainer< IPlatformService >
void RegisterComponent (const std::shared_ptr< IPlatformService > &component)
Register a new component instance.
void DeregisterComponent (const std::type_info &typeInfo)
Deregister a component.
Member Function Documentation
InitStageOne()
bool CPlatformPosix::InitStageOne () override virtual
Called at an early stage of application startup.
This method can be used to do platform specific environment preparation or initialisation (like setting environment variables for example)
Reimplemented from CPlatform.
Reimplemented in CPlatformWebOS.
References CPlatform::InitStageOne(), ms_signalFlag, and CSpecialProtocol::SetEnvHomePath().
Referenced by CPlatformAndroid::InitStageOne(), CPlatformDarwin::InitStageOne(), CPlatformFreebsd::InitStageOne(), and CPlatformLinux::InitStageOne().
RequestQuit()
void CPlatformPosix::RequestQuit () static
References ms_signalFlag.
Referenced by anonymous_namespace{main.cpp}::XBMC_POSIX_HandleSignal().
TestQuitFlag()
bool CPlatformPosix::TestQuitFlag () static
References ms_signalFlag.
Referenced by CApplication::ProcessSlow().
Member Data Documentation
ms_signalFlag
std::atomic_flag CPlatformPosix::ms_signalFlag static private
Referenced by InitStageOne(), RequestQuit(), and TestQuitFlag().
The documentation for this class was generated from the following files:
PlatformPosix.h
PlatformPosix.cpp