Kodi Documentation: CBlurayStateSerializer Class Reference
CBlurayStateSerializer Class Reference
Auxiliar class to serialize/deserialize the Bluray state (into/from XML)
#include <BlurayStateSerializer.h>
Public Member Functions
CBlurayStateSerializer ()=default
Default constructor.
~CBlurayStateSerializer ()=default
Default destructor.
bool XMLToBlurayState (BlurayState &state, const std::string &xmlstate)
Provided the state in xml format, fills a BlurayState struct representing the Bluray state and returns the success status of the operation.
bool BlurayStateToXML (std::string &xmlstate, const BlurayState &state)
Provided the BlurayState struct of the current playing dvd, serializes the struct to XML.
Detailed Description
Auxiliar class to serialize/deserialize the Bluray state (into/from XML)
Constructor & Destructor Documentation
CBlurayStateSerializer()
CBlurayStateSerializer::CBlurayStateSerializer () default
Default constructor.
~CBlurayStateSerializer()
CBlurayStateSerializer::~CBlurayStateSerializer () default
Default destructor.
Member Function Documentation
BlurayStateToXML()
bool CBlurayStateSerializer::BlurayStateToXML (std::string & xmlstate, const BlurayState & state)
Provided the BlurayState struct of the current playing dvd, serializes the struct to XML.
Parameters
[in,out] xmlstate a string describing the Bluray state (XML)
state the Bluray state struct
Returns
true if it was possible to serialize the struct into XML, false otherwise
References BlurayState::playlistId.
Referenced by CDVDInputStreamBluray::GetState().
XMLToBlurayState()
bool CBlurayStateSerializer::XMLToBlurayState (BlurayState & state, const std::string & xmlstate)
Provided the state in xml format, fills a BlurayState struct representing the Bluray state and returns the success status of the operation.
Parameters
[in,out] state the Bluray state struct to be filled
xmlstate a string describing the Bluray state (XML)
Returns
true if it was possible to fill the state struct based on the XML content, false otherwise
References LOGERROR, LOGWARNING, CXBMCTinyXML2::Parse(), and BlurayState::playlistId.
Referenced by CDVDInputStreamBluray::SetState().
The documentation for this class was generated from the following files:
BlurayStateSerializer.h
BlurayStateSerializer.cpp