Kodi Documentation: kodi::addon::CInstanceInputStream Class Reference
kodi::addon::CInstanceInputStream Class Reference abstract
#include <Inputstream.h>
Public Member Functions
CInstanceInputStream (const IInstanceInfo &instance)
Inputstream class constructor used to support multiple instance types.
~CInstanceInputStream () override=default
Destructor.
virtual void GetCapabilities (kodi::addon::InputstreamCapabilities &capabilities)=0
Get the list of features that this add-on provides.
virtual bool Open (const kodi::addon::InputstreamProperty &props)=0
Open a stream.
virtual void Close ()=0
Close an open stream.
virtual bool IsRealTimeStream ()
Check for real-time streaming.
virtual int ReadStream (uint8_t *buffer, unsigned int bufferSize)
Read from an open stream.
virtual int64_t SeekStream (int64_t position, int whence=SEEK_SET)
Seek in a stream.
virtual int64_t PositionStream ()
The position in the stream that's currently being read.
virtual int64_t LengthStream ()
The Total length of the stream that's currently being read.
virtual int GetBlockSize ()
Obtain the chunk size to use when reading streams.
virtual bool GetStreamIds (std::vector< unsigned int > &ids)
Get IDs of available streams.
virtual bool GetStream (int streamid, kodi::addon::InputstreamInfo &stream)
Function for giving detailed stream information.
virtual void EnableStream (int streamid, bool enable)
Enable or disable a stream.
virtual bool OpenStream (int streamid)
Opens a stream for playback.
virtual void DemuxReset ()
Reset the demultiplexer in the add-on.
virtual void DemuxAbort ()
Abort the demultiplexer thread in the add-on.
virtual void DemuxFlush ()
Flush all data that's currently in the demultiplexer buffer in the add-on.
virtual DEMUX_PACKET * DemuxRead ()
Read the next packet from the demultiplexer, if there is one.
virtual bool DemuxSeekTime (double time, bool backwards, double &startpts)
Notify the InputStream addon/demuxer that Kodi wishes to seek the stream by time.
virtual void DemuxSetSpeed (int speed)
Notify the InputStream addon/demuxer that Kodi wishes to change playback speed.
virtual void SetVideoResolution (unsigned int width, unsigned int height)
Notify current screen resolution.
virtual void SetVideoResolution (unsigned int width, unsigned int height, unsigned int maxWidth, unsigned int maxHeight)
Notify current screen resolution and max screen resolution allowed.
DEMUX_PACKET * AllocateDemuxPacket (int dataSize)
Allocate a demux packet. Free with FreeDemuxPacket.
DEMUX_PACKET * AllocateEncryptedDemuxPacket (int dataSize, unsigned int encryptedSubsampleCount)
Allocate a encrypted demux packet. Free with FreeDemuxPacket.
void FreeDemuxPacket (DEMUX_PACKET *packet)
Free a packet that was allocated with AllocateDemuxPacket.
virtual int GetTotalTime ()
Totel time in ms.
virtual int GetTime ()
Playing time in ms.
virtual bool GetTimes (InputstreamTimes &times)
Get current timing values in PTS scale.
virtual bool PosTime (int ms)
Positions inputstream to playing time given in ms.
virtual int GetChapter ()
Return currently selected chapter.
virtual int GetChapterCount ()
Return number of available chapters.
virtual const char * GetChapterName (int ch)
Return name of chapter.
virtual int64_t GetChapterPos (int ch)
Return position if chapter # ch in milliseconds.
virtual bool SeekChapter (int ch)
Seek to the beginning of chapter # ch.
Public Member Functions inherited from kodi::addon::IAddonInstance
IAddonInstance (const kodi::addon::IInstanceInfo &instance)
virtual ~IAddonInstance ()=default
virtual ADDON_STATUS CreateInstance (const kodi::addon::IInstanceInfo &instance, KODI_ADDON_INSTANCE_HDL &hdl)
std::string GetInstanceAPIVersion () const
virtual ADDON_STATUS SetInstanceSetting (const std::string &settingName, const kodi::addon::CSettingValue &settingValue)
bool IsInstanceSettingUsingDefault (const std::string &settingName)
std::string GetInstanceUserPath (const std::string &append="")
bool CheckInstanceSettingString (const std::string &settingName, std::string &settingValue)
std::string GetInstanceSettingString (const std::string &settingName, const std::string &defaultValue="")
void SetInstanceSettingString (const std::string &settingName, const std::string &settingValue)
bool CheckInstanceSettingInt (const std::string &settingName, int &settingValue)
int GetInstanceSettingInt (const std::string &settingName, int defaultValue=0)
void SetInstanceSettingInt (const std::string &settingName, int settingValue)
bool CheckInstanceSettingBoolean (const std::string &settingName, bool &settingValue)
bool GetInstanceSettingBoolean (const std::string &settingName, bool defaultValue=false)
void SetInstanceSettingBoolean (const std::string &settingName, bool settingValue)
bool CheckInstanceSettingFloat (const std::string &settingName, float &settingValue)
float GetInstanceSettingFloat (const std::string &settingName, float defaultValue=0.0f)
void SetInstanceSettingFloat (const std::string &settingName, float settingValue)
template<typename enumType >
bool CheckInstanceSettingEnum (const std::string &settingName, enumType &settingValue)
template<typename enumType >
enumType GetInstanceSettingEnum (const std::string &settingName, enumType defaultValue=static_cast< enumType >(0))
template<typename enumType >
void SetInstanceSettingEnum (const std::string &settingName, enumType settingValue)
Private Member Functions
void SetAddonStruct (KODI_ADDON_INSTANCE_STRUCT *instance)
Static Private Member Functions
static int compareVersion (const int v1[3], const int v2[3])
static bool ADDON_Open (const AddonInstance_InputStream *instance, INPUTSTREAM_PROPERTY *props)
static void ADDON_Close (const AddonInstance_InputStream *instance)
static void ADDON_GetCapabilities (const AddonInstance_InputStream *instance, INPUTSTREAM_CAPABILITIES *capabilities)
static bool ADDON_GetStreamIds (const AddonInstance_InputStream *instance, struct INPUTSTREAM_IDS *ids)
static bool ADDON_GetStream (const AddonInstance_InputStream *instance, int streamid, struct INPUTSTREAM_INFO *info, KODI_HANDLE *demuxStream, KODI_HANDLE(*transfer_stream)(KODI_HANDLE handle, int streamId, struct INPUTSTREAM_INFO *stream))
static void ADDON_EnableStream (const AddonInstance_InputStream *instance, int streamid, bool enable)
static bool ADDON_OpenStream (const AddonInstance_InputStream *instance, int streamid)
static void ADDON_DemuxReset (const AddonInstance_InputStream *instance)
static void ADDON_DemuxAbort (const AddonInstance_InputStream *instance)
static void ADDON_DemuxFlush (const AddonInstance_InputStream *instance)
static DEMUX_PACKET * ADDON_DemuxRead (const AddonInstance_InputStream *instance)
static bool ADDON_DemuxSeekTime (const AddonInstance_InputStream *instance, double time, bool backwards, double *startpts)
static void ADDON_DemuxSetSpeed (const AddonInstance_InputStream *instance, int speed)
static void ADDON_SetVideoResolution (const AddonInstance_InputStream *instance, unsigned int width, unsigned int height, unsigned int maxWidth, unsigned int maxHeight)
static int ADDON_GetTotalTime (const AddonInstance_InputStream *instance)
static int ADDON_GetTime (const AddonInstance_InputStream *instance)
static bool ADDON_GetTimes (const AddonInstance_InputStream *instance, INPUTSTREAM_TIMES *times)
static bool ADDON_PosTime (const AddonInstance_InputStream *instance, int ms)
static int ADDON_GetChapter (const AddonInstance_InputStream *instance)
static int ADDON_GetChapterCount (const AddonInstance_InputStream *instance)
static const char * ADDON_GetChapterName (const AddonInstance_InputStream *instance, int ch)
static int64_t ADDON_GetChapterPos (const AddonInstance_InputStream *instance, int ch)
static bool ADDON_SeekChapter (const AddonInstance_InputStream *instance, int ch)
static int ADDON_ReadStream (const AddonInstance_InputStream *instance, uint8_t *buffer, unsigned int bufferSize)
static int64_t ADDON_SeekStream (const AddonInstance_InputStream *instance, int64_t position, int whence)
static int64_t ADDON_PositionStream (const AddonInstance_InputStream *instance)
static int64_t ADDON_LengthStream (const AddonInstance_InputStream *instance)
static int ADDON_GetBlockSize (const AddonInstance_InputStream *instance)
static bool ADDON_IsRealTimeStream (const AddonInstance_InputStream *instance)
Private Attributes
AddonInstance_InputStream * m_instanceData
Member Function Documentation
ADDON_Close()
static void kodi::addon::CInstanceInputStream::ADDON_Close (const AddonInstance_InputStream * instance) inline static private
References Close().
ADDON_DemuxAbort()
static void kodi::addon::CInstanceInputStream::ADDON_DemuxAbort (const AddonInstance_InputStream * instance) inline static private
ADDON_DemuxFlush()
static void kodi::addon::CInstanceInputStream::ADDON_DemuxFlush (const AddonInstance_InputStream * instance) inline static private
ADDON_DemuxRead()
static DEMUX_PACKET * kodi::addon::CInstanceInputStream::ADDON_DemuxRead (const AddonInstance_InputStream * instance) inline static private
ADDON_DemuxReset()
static void kodi::addon::CInstanceInputStream::ADDON_DemuxReset (const AddonInstance_InputStream * instance) inline static private
ADDON_DemuxSeekTime()
static bool kodi::addon::CInstanceInputStream::ADDON_DemuxSeekTime (const AddonInstance_InputStream * instance, double time, bool backwards, double * startpts) inline static private
ADDON_DemuxSetSpeed()
static void kodi::addon::CInstanceInputStream::ADDON_DemuxSetSpeed (const AddonInstance_InputStream * instance, int speed) inline static private
ADDON_EnableStream()
static void kodi::addon::CInstanceInputStream::ADDON_EnableStream (const AddonInstance_InputStream * instance, int streamid, bool enable) inline static private
ADDON_GetBlockSize()
static int kodi::addon::CInstanceInputStream::ADDON_GetBlockSize (const AddonInstance_InputStream * instance) inline static private
ADDON_GetCapabilities()
static void kodi::addon::CInstanceInputStream::ADDON_GetCapabilities (const AddonInstance_InputStream * instance, INPUTSTREAM_CAPABILITIES * capabilities) inline static private
ADDON_GetChapter()
static int kodi::addon::CInstanceInputStream::ADDON_GetChapter (const AddonInstance_InputStream * instance) inline static private
ADDON_GetChapterCount()
static int kodi::addon::CInstanceInputStream::ADDON_GetChapterCount (const AddonInstance_InputStream * instance) inline static private
ADDON_GetChapterName()
static const char * kodi::addon::CInstanceInputStream::ADDON_GetChapterName (const AddonInstance_InputStream * instance, int ch) inline static private
ADDON_GetChapterPos()
static int64_t kodi::addon::CInstanceInputStream::ADDON_GetChapterPos (const AddonInstance_InputStream * instance, int ch) inline static private
ADDON_GetStream()
static bool kodi::addon::CInstanceInputStream::ADDON_GetStream (const AddonInstance_InputStream * instance, int streamid, struct INPUTSTREAM_INFO * info, KODI_HANDLE * demuxStream, KODI_HANDLE(*)(KODI_HANDLE handle, int streamId, struct INPUTSTREAM_INFO *stream) transfer_stream) inline static private
ADDON_GetStreamIds()
static bool kodi::addon::CInstanceInputStream::ADDON_GetStreamIds (const AddonInstance_InputStream * instance, struct INPUTSTREAM_IDS * ids) inline static private
References INPUTSTREAM_MAX_STREAM_COUNT, INPUTSTREAM_IDS::m_streamCount, and INPUTSTREAM_IDS::m_streamIds.
ADDON_GetTime()
static int kodi::addon::CInstanceInputStream::ADDON_GetTime (const AddonInstance_InputStream * instance) inline static private
ADDON_GetTimes()
static bool kodi::addon::CInstanceInputStream::ADDON_GetTimes (const AddonInstance_InputStream * instance, INPUTSTREAM_TIMES * times) inline static private
ADDON_GetTotalTime()
static int kodi::addon::CInstanceInputStream::ADDON_GetTotalTime (const AddonInstance_InputStream * instance) inline static private
ADDON_IsRealTimeStream()
static bool kodi::addon::CInstanceInputStream::ADDON_IsRealTimeStream (const AddonInstance_InputStream * instance) inline static private
ADDON_LengthStream()
static int64_t kodi::addon::CInstanceInputStream::ADDON_LengthStream (const AddonInstance_InputStream * instance) inline static private
ADDON_Open()
static bool kodi::addon::CInstanceInputStream::ADDON_Open (const AddonInstance_InputStream * instance, INPUTSTREAM_PROPERTY * props) inline static private
ADDON_OpenStream()
static bool kodi::addon::CInstanceInputStream::ADDON_OpenStream (const AddonInstance_InputStream * instance, int streamid) inline static private
ADDON_PositionStream()
static int64_t kodi::addon::CInstanceInputStream::ADDON_PositionStream (const AddonInstance_InputStream * instance) inline static private
ADDON_PosTime()
static bool kodi::addon::CInstanceInputStream::ADDON_PosTime (const AddonInstance_InputStream * instance, int ms) inline static private
ADDON_ReadStream()
static int kodi::addon::CInstanceInputStream::ADDON_ReadStream (const AddonInstance_InputStream * instance, uint8_t * buffer, unsigned int bufferSize) inline static private
ADDON_SeekChapter()
static bool kodi::addon::CInstanceInputStream::ADDON_SeekChapter (const AddonInstance_InputStream * instance, int ch) inline static private
ADDON_SeekStream()
static int64_t kodi::addon::CInstanceInputStream::ADDON_SeekStream (const AddonInstance_InputStream * instance, int64_t position, int whence) inline static private
ADDON_SetVideoResolution()
static void kodi::addon::CInstanceInputStream::ADDON_SetVideoResolution (const AddonInstance_InputStream * instance, unsigned int width, unsigned int height, unsigned int maxWidth, unsigned int maxHeight) inline static private
compareVersion()
static int kodi::addon::CInstanceInputStream::compareVersion (const int v1[3], const int v2[3]) inline static private
SetAddonStruct()
void kodi::addon::CInstanceInputStream::SetAddonStruct (KODI_ADDON_INSTANCE_STRUCT * instance) inline private
References KodiToAddonFuncTable_InputStream::addonInstance, KodiToAddonFuncTable_InputStream::demux_read(), KodiToAddonFuncTable_InputStream::get_chapter_name(), KODI_ADDON_INSTANCE_STRUCT::hdl, KODI_ADDON_INSTANCE_STRUCT::inputstream, and AddonInstance_InputStream::toAddon.
Member Data Documentation
m_instanceData
AddonInstance_InputStream* kodi::addon::CInstanceInputStream::m_instanceData private
The documentation for this class was generated from the following file:
addon-instance/inputstream.h