Kodi Documentation: CVideoLibraryResetResumePointJob Class Reference
CVideoLibraryResetResumePointJob Class Reference
Video library job implementation for resetting a resume point.
#include <VideoLibraryResetResumePointJob.h>
Public Member Functions
CVideoLibraryResetResumePointJob (const std::shared_ptr< CFileItem > &item)
Creates a new job for resetting a given item's resume point.
~CVideoLibraryResetResumePointJob () override=default
const char * GetType () const override
Function that returns the type of job.
bool operator== (const CJob *job) const override
Public Member Functions inherited from CVideoLibraryJob
~CVideoLibraryJob () override
virtual bool CanBeCancelled () const
Whether the job can be cancelled or not.
virtual bool Cancel ()
Tries to cancel the running job.
bool DoWork () override
Main workhorse function of CJob instances.
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
virtual bool ShouldCancel (unsigned int progress, unsigned int total) const
Function for longer jobs to report progress and check whether they have been cancelled.
Protected Member Functions
bool Work (CVideoDatabase &db) override
Worker method to be implemented by an actual implementation.
Protected Member Functions inherited from CVideoLibraryJob
CVideoLibraryJob ()
Private Attributes
std::shared_ptr< CFileItem > m_item
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Detailed Description
Video library job implementation for resetting a resume point.
Constructor & Destructor Documentation
CVideoLibraryResetResumePointJob()
CVideoLibraryResetResumePointJob::CVideoLibraryResetResumePointJob (const std::shared_ptr< CFileItem > & item)
Creates a new job for resetting a given item's resume point.
Parameters
[in] item Item for that the resume point shall be reset.
~CVideoLibraryResetResumePointJob()
CVideoLibraryResetResumePointJob::~CVideoLibraryResetResumePointJob () override default
Member Function Documentation
GetType()
const char * CVideoLibraryResetResumePointJob::GetType () const inline override virtual
Function that returns the type of job.
CJob subclasses may optionally implement this function to specify the type of job. This is useful for the CJobManager::AddLIFOJob() routine, which preempts similar jobs with the new job.
Returns
a unique character string describing the job.
See also
CJobManager
Reimplemented from CVideoLibraryJob.
Referenced by operator==().
operator==()
bool CVideoLibraryResetResumePointJob::operator== (const CJob * job) const override virtual
Reimplemented from CVideoLibraryJob.
References CJob::GetType(), GetType(), and m_item.
Work()
bool CVideoLibraryResetResumePointJob::Work (CVideoDatabase & db) override protected virtual
Worker method to be implemented by an actual implementation.
Parameters
[in] db Already open video database to be used for interaction
Returns
True if the process succeeded, false otherwise
Implements CVideoLibraryJob.
References CFileItemList::Add(), CDatabase::BeginTransaction(), CDatabase::Close(), CVideoDatabase::CommitTransaction(), CVideoDatabase::DeleteResumeBookMark(), XFILE::DIR_FLAG_NO_FILE_INFO, CServiceBroker::GetPVRManager(), CUtil::GetRecursiveListing(), CServiceBroker::GetSettingsComponent(), URIUtils::IsUPnP(), m_item, PVR::CPVRManager::Recordings(), and UPNP::CUPnP::SaveFileState().
Member Data Documentation
m_item
std::shared_ptr<CFileItem> CVideoLibraryResetResumePointJob::m_item private
Referenced by operator==(), and Work().
The documentation for this class was generated from the following files:
VideoLibraryResetResumePointJob.h
VideoLibraryResetResumePointJob.cpp