Kodi Documentation: CStereoscopicsManager Class Reference
CStereoscopicsManager Class Reference
#include <StereoscopicsManager.h>
Public Member Functions
CStereoscopicsManager ()
~CStereoscopicsManager (void) override
void Initialize ()
RENDER_STEREO_MODE GetStereoMode (void) const
std::string DetectStereoModeByString (const std::string &needle) const
std::string GetLabelForStereoMode (const RENDER_STEREO_MODE &mode) const
void SetStereoMode (const RENDER_STEREO_MODE &mode)
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
void OnStreamChange ()
bool OnMessage (CGUIMessage &message) override
bool OnAction (const CAction &action)
Handle 3D specific cActions.
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Public Member Functions inherited from IMsgTargetCallback
virtual ~IMsgTargetCallback ()=default
Static Public Member Functions
static const char * ConvertGuiStereoModeToString (const RENDER_STEREO_MODE &mode)
static CAction ConvertActionCommandToAction (const std::string &command, const std::string &parameter)
Converts a stereoscopics related action/command from Builtins and JsonRPC into the according cAction ID.
static std::string NormalizeStereoMode (const std::string &mode)
Private Member Functions
RENDER_STEREO_MODE GetNextSupportedStereoMode (const RENDER_STEREO_MODE &currentMode, int step=1) const
RENDER_STEREO_MODE GetStereoModeByUserChoice () const
RENDER_STEREO_MODE GetStereoModeOfPlayingVideo (void) const
RENDER_STEREO_MODE GetPreferredPlaybackMode (void) const
std::string GetVideoStereoMode () const
bool IsVideoStereoscopic () const
void SetStereoModeByUser (const RENDER_STEREO_MODE &mode)
void ApplyStereoMode (const RENDER_STEREO_MODE &mode, bool notify=true)
void OnPlaybackStopped (void)
Static Private Member Functions
static int ConvertStringToGuiStereoMode (const std::string &mode)
will convert a string representation into a GUI stereo mode
static int ConvertVideoToGuiStereoMode (const std::string &mode)
Private Attributes
std::shared_ptr< CSettings > m_settings
RENDER_STEREO_MODE m_stereoModeSetByUser
RENDER_STEREO_MODE m_lastStereoModeSetByUser
Constructor & Destructor Documentation
CStereoscopicsManager()
CStereoscopicsManager::CStereoscopicsManager ()
Todo:
Move this to Initialize() to avoid potential problems in ctor
References m_lastStereoModeSetByUser, m_settings, m_stereoModeSetByUser, RENDER_STEREO_MODE_UNDEFINED, and CSettings::SETTING_VIDEOSCREEN_STEREOSCOPICMODE.
~CStereoscopicsManager()
CStereoscopicsManager::~CStereoscopicsManager (void) override
References m_settings.
Member Function Documentation
ApplyStereoMode()
void CStereoscopicsManager::ApplyStereoMode (const RENDER_STEREO_MODE & mode, bool notify = true) private
References ConvertGuiStereoModeToString(), g_localizeStrings, CLocalizeStrings::Get(), CWinSystemBase::GetGfxContext(), GetLabelForStereoMode(), CGraphicContext::GetStereoMode(), CServiceBroker::GetWinSystem(), CGUIDialogKaiToast::Info, CLog::Log(), LOGDEBUG, CGUIDialogKaiToast::QueueNotification(), and CGraphicContext::SetStereoMode().
Referenced by OnSettingChanged().
ConvertActionCommandToAction()
CAction CStereoscopicsManager::ConvertActionCommandToAction (const std::string & command, const std::string & parameter) static
Converts a stereoscopics related action/command from Builtins and JsonRPC into the according cAction ID.
Parameters
command The command/action
parameter The parameter of the command
Returns
The integer of the according cAction or -1 if not valid
References ACTION_NONE, ACTION_STEREOMODE_NEXT, ACTION_STEREOMODE_PREVIOUS, ACTION_STEREOMODE_SELECT, ACTION_STEREOMODE_SET, ACTION_STEREOMODE_TOGGLE, ACTION_STEREOMODE_TOMONO, and ConvertStringToGuiStereoMode().
Referenced by anonymous_namespace{GUIBuiltins.cpp}::SetStereoMode(), and JSONRPC::CGUIOperations::SetStereoscopicMode().
ConvertGuiStereoModeToString()
const char * CStereoscopicsManager::ConvertGuiStereoModeToString (const RENDER_STEREO_MODE & mode) static
References name, StereoModeMap::name, and StringToGuiModeMap.
Referenced by ApplyStereoMode(), CVideoThumbLoader::DetectAndAddMissingItemData(), JSONRPC::CGUIOperations::GetStereoModeObjectFromGuiMode(), GetStereoModeOfPlayingVideo(), NormalizeStereoMode(), and OnSettingChanged().
ConvertStringToGuiStereoMode()
int CStereoscopicsManager::ConvertStringToGuiStereoMode (const std::string & mode) static private
will convert a string representation into a GUI stereo mode
Parameters
mode The string to convert
Returns
-1 if not found, otherwise the according int of the RENDER_STEREO_MODE enum
References ConvertVideoToGuiStereoMode(), StereoModeMap::mode, name, and StringToGuiModeMap.
Referenced by ConvertActionCommandToAction(), NormalizeStereoMode(), and OnAction().
ConvertVideoToGuiStereoMode()
int CStereoscopicsManager::ConvertVideoToGuiStereoMode (const std::string & mode) static private
References StereoModeMap::mode, name, and VideoModeToGuiModeMap.
Referenced by ConvertStringToGuiStereoMode(), and GetStereoModeOfPlayingVideo().
DetectStereoModeByString()
std::string CStereoscopicsManager::DetectStereoModeByString (const std::string & needle) const
References CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGERROR, CRegExp::RegComp(), and CRegExp::RegFind().
Referenced by CVideoThumbLoader::DetectAndAddMissingItemData(), and CVideoPlayer::OpenVideoStream().
GetLabelForStereoMode()
std::string CStereoscopicsManager::GetLabelForStereoMode (const RENDER_STEREO_MODE & mode) const
References g_localizeStrings, CLocalizeStrings::Get(), RENDER_STEREO_MODE_ANAGLYPH_YELLOW_BLUE, RENDER_STEREO_MODE_AUTO, RENDER_STEREO_MODE_CHECKERBOARD, RENDER_STEREO_MODE_HARDWAREBASED, RENDER_STEREO_MODE_INTERLACED, and RENDER_STEREO_MODE_MONO.
Referenced by ApplyStereoMode(), GetStereoModeByUserChoice(), JSONRPC::CGUIOperations::GetStereoModeObjectFromGuiMode(), OnStreamChange(), CDisplaySettings::SettingOptionsPreferredStereoscopicViewModesFiller(), and CDisplaySettings::SettingOptionsStereoscopicModesFiller().
GetNextSupportedStereoMode()
RENDER_STEREO_MODE CStereoscopicsManager::GetNextSupportedStereoMode (const RENDER_STEREO_MODE & currentMode, int step = 1) const private
References CServiceBroker::GetRenderSystem(), RENDER_STEREO_MODE_COUNT, and CRenderSystemBase::SupportsStereo().
Referenced by OnAction().
GetPreferredPlaybackMode()
RENDER_STEREO_MODE CStereoscopicsManager::GetPreferredPlaybackMode (void) const private
References m_settings, and CSettings::SETTING_VIDEOSCREEN_PREFEREDSTEREOSCOPICMODE.
Referenced by OnAction(), and OnStreamChange().
GetStereoMode()
RENDER_STEREO_MODE CStereoscopicsManager::GetStereoMode (void) const
References m_settings, and CSettings::SETTING_VIDEOSCREEN_STEREOSCOPICMODE.
Referenced by JSONRPC::CGUIOperations::GetPropertyValue(), GetStereoModeByUserChoice(), OnAction(), OnPlaybackStopped(), OnSettingChanged(), OnStreamChange(), and SetStereoMode().
GetStereoModeByUserChoice()
RENDER_STEREO_MODE CStereoscopicsManager::GetStereoModeByUserChoice () const private
References CGUIDialogSelect::Add(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), GetLabelForStereoMode(), CServiceBroker::GetRenderSystem(), CGUIDialogSelect::GetSelectedItem(), GetStereoMode(), GetStereoModeOfPlayingVideo(), CGUIComponent::GetWindowManager(), CGUIDialogBoxBase::IsConfirmed(), label, CGUIDialog::Open(), RENDER_STEREO_MODE_AUTO, RENDER_STEREO_MODE_COUNT, RENDER_STEREO_MODE_OFF, CGUIDialogSelect::Reset(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetSelected(), CRenderSystemBase::SupportsStereo(), and WINDOW_DIALOG_SELECT.
Referenced by OnAction(), and OnStreamChange().
GetStereoModeOfPlayingVideo()
RENDER_STEREO_MODE CStereoscopicsManager::GetStereoModeOfPlayingVideo (void) const private
References ConvertGuiStereoModeToString(), ConvertVideoToGuiStereoMode(), GetVideoStereoMode(), CLog::Log(), LOGDEBUG, and RENDER_STEREO_MODE_OFF.
Referenced by GetStereoModeByUserChoice(), OnStreamChange(), and SetStereoMode().
GetVideoStereoMode()
std::string CStereoscopicsManager::GetVideoStereoMode () const private
References CServiceBroker::GetAppComponents(), CServiceBroker::GetDataCacheCore(), and CDataCacheCore::GetVideoStereoMode().
Referenced by GetStereoModeOfPlayingVideo(), and IsVideoStereoscopic().
Initialize()
void CStereoscopicsManager::Initialize ()
References RENDER_STEREO_MODE_OFF, and SetStereoMode().
Referenced by CProfileManager::FinalizeLoadProfile().
IsVideoStereoscopic()
bool CStereoscopicsManager::IsVideoStereoscopic () const private
References GetVideoStereoMode().
Referenced by OnStreamChange().
NormalizeStereoMode()
std::string CStereoscopicsManager::NormalizeStereoMode (const std::string & mode) static
References ConvertGuiStereoModeToString(), and ConvertStringToGuiStereoMode().
Referenced by CVideoThumbLoader::DetectAndAddMissingItemData(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetBool(), and KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel().
OnAction()
bool CStereoscopicsManager::OnAction (const CAction & action)
Handle 3D specific cActions.
Parameters
action The action to process
Returns
True if action could be handled, false otherwise.
References ACTION_STEREOMODE_NEXT, ACTION_STEREOMODE_PREVIOUS, ACTION_STEREOMODE_SELECT, ACTION_STEREOMODE_SET, ACTION_STEREOMODE_TOGGLE, ACTION_STEREOMODE_TOMONO, ConvertStringToGuiStereoMode(), GetNextSupportedStereoMode(), GetPreferredPlaybackMode(), GetStereoMode(), GetStereoModeByUserChoice(), m_lastStereoModeSetByUser, m_stereoModeSetByUser, RENDER_STEREO_MODE_COUNT, RENDER_STEREO_MODE_MONO, RENDER_STEREO_MODE_OFF, RENDER_STEREO_MODE_UNDEFINED, and SetStereoModeByUser().
OnMessage()
bool CStereoscopicsManager::OnMessage (CGUIMessage & message) override virtual
Implements IMsgTargetCallback.
References CGUIMessage::GetMessage(), GUI_MSG_PLAYBACK_STOPPED, GUI_MSG_PLAYLISTPLAYER_STOPPED, and OnPlaybackStopped().
OnPlaybackStopped()
void CStereoscopicsManager::OnPlaybackStopped (void) private
References GetStereoMode(), m_lastStereoModeSetByUser, m_settings, m_stereoModeSetByUser, RENDER_STEREO_MODE_OFF, RENDER_STEREO_MODE_UNDEFINED, SetStereoMode(), and CSettings::SETTING_VIDEOPLAYER_QUITSTEREOMODEONSTOP.
Referenced by OnMessage().
OnSettingChanged()
void CStereoscopicsManager::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References ApplyStereoMode(), ConvertGuiStereoModeToString(), GetStereoMode(), CLog::Log(), LOGDEBUG, and CSettings::SETTING_VIDEOSCREEN_STEREOSCOPICMODE.
OnStreamChange()
void CStereoscopicsManager::OnStreamChange ()
References CGUIDialogSelect::Add(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetGUI(), GetLabelForStereoMode(), GetPreferredPlaybackMode(), CServiceBroker::GetRenderSystem(), CGUIDialogSelect::GetSelectedItem(), GetStereoMode(), GetStereoModeByUserChoice(), GetStereoModeOfPlayingVideo(), CGUIComponent::GetWindowManager(), CGUIDialogBoxBase::IsConfirmed(), IsVideoStereoscopic(), m_settings, m_stereoModeSetByUser, CGUIDialog::Open(), RENDER_STEREO_MODE_AUTO, RENDER_STEREO_MODE_MONO, RENDER_STEREO_MODE_OFF, RENDER_STEREO_MODE_UNDEFINED, CGUIDialogSelect::Reset(), CGUIDialogBoxBase::SetHeading(), SetStereoMode(), SetStereoModeByUser(), CSettings::SETTING_VIDEOPLAYER_QUITSTEREOMODEONSTOP, CSettings::SETTING_VIDEOPLAYER_STEREOSCOPICPLAYBACKMODE, STEREOSCOPIC_PLAYBACK_MODE_ASK, STEREOSCOPIC_PLAYBACK_MODE_IGNORE, STEREOSCOPIC_PLAYBACK_MODE_PREFERRED, CRenderSystemBase::SupportsStereo(), TMSG_MEDIA_PAUSE, TMSG_MEDIA_UNPAUSE, and WINDOW_DIALOG_SELECT.
Referenced by CApplicationPlayerCallback::OnAVChange().
SetStereoMode()
void CStereoscopicsManager::SetStereoMode (const RENDER_STEREO_MODE & mode)
References CServiceBroker::GetRenderSystem(), GetStereoMode(), GetStereoModeOfPlayingVideo(), m_settings, RENDER_STEREO_MODE_AUTO, RENDER_STEREO_MODE_OFF, and CSettings::SETTING_VIDEOSCREEN_STEREOSCOPICMODE.
Referenced by Initialize(), OnPlaybackStopped(), OnStreamChange(), and SetStereoModeByUser().
SetStereoModeByUser()
void CStereoscopicsManager::SetStereoModeByUser (const RENDER_STEREO_MODE & mode) private
References m_lastStereoModeSetByUser, m_stereoModeSetByUser, and SetStereoMode().
Referenced by OnAction(), and OnStreamChange().
Member Data Documentation
m_lastStereoModeSetByUser
RENDER_STEREO_MODE CStereoscopicsManager::m_lastStereoModeSetByUser private
Referenced by CStereoscopicsManager(), OnAction(), OnPlaybackStopped(), and SetStereoModeByUser().
m_settings
std::shared_ptr<CSettings> CStereoscopicsManager::m_settings private
Referenced by CStereoscopicsManager(), GetPreferredPlaybackMode(), GetStereoMode(), OnPlaybackStopped(), OnStreamChange(), SetStereoMode(), and ~CStereoscopicsManager().
m_stereoModeSetByUser
RENDER_STEREO_MODE CStereoscopicsManager::m_stereoModeSetByUser private
Referenced by CStereoscopicsManager(), OnAction(), OnPlaybackStopped(), OnStreamChange(), and SetStereoModeByUser().
The documentation for this class was generated from the following files:
StereoscopicsManager.h
StereoscopicsManager.cpp