Kodi Documentation: CFavouritesService Class Reference
CFavouritesService Class Reference
#include <FavouritesService.h>
Classes
struct FavouritesUpdated
Public Member Functions
CFavouritesService (std::string userDataFolder)
virtual ~CFavouritesService ()=default
void ReInit (std::string userDataFolder)
bool IsFavourited (const CFileItem &item, int contextWindow) const
std::shared_ptr< CFileItem > GetFavourite (const CFileItem &item, int contextWindow) const
std::shared_ptr< CFileItem > ResolveFavourite (const CFileItem &favItem) const
int Size () const
void GetAll (CFileItemList &items) const
bool AddOrRemove (const CFileItem &item, int contextWindow)
bool Save (const CFileItemList &items)
void RefreshFavourites ()
Refresh favourites for directory providers, e.g. the GUI needs to be updated.
CEventStream< FavouritesUpdated > & Events ()
Private Member Functions
CFavouritesService ()=delete
CFavouritesService (const CFavouritesService &)=delete
CFavouritesService & operator= (const CFavouritesService &)=delete
CFavouritesService (CFavouritesService &&)=delete
CFavouritesService & operator= (CFavouritesService &&)=delete
void OnUpdated ()
bool Persist ()
Private Attributes
std::string m_userDataFolder
CFileItemList m_favourites
std::unordered_map< std::string, std::shared_ptr< CFileItem > > m_targets
CEventSource< FavouritesUpdated > m_events
CCriticalSection m_criticalSection
Constructor & Destructor Documentation
CFavouritesService() [1/4]
CFavouritesService::CFavouritesService (std::string userDataFolder) explicit
References ReInit().
~CFavouritesService()
virtual CFavouritesService::~CFavouritesService () virtual default
CFavouritesService() [2/4]
CFavouritesService::CFavouritesService () private delete
CFavouritesService() [3/4]
CFavouritesService::CFavouritesService (const CFavouritesService &) private delete
CFavouritesService() [4/4]
CFavouritesService::CFavouritesService (CFavouritesService &&) private delete
Member Function Documentation
AddOrRemove()
bool CFavouritesService::AddOrRemove (const CFileItem & item, int contextWindow)
References CFileItemList::Add(), GetFavourite(), CGUIListItem::GetLabel(), CFileItem::GetPath(), ContentUtils::GetPreferredArtImage(), CUtil::GetTitleFromPath(), CFavouritesURL::GetURL(), CGUIListItem::m_bIsFolder, m_criticalSection, m_favourites, m_targets, OnUpdated(), Persist(), and CFileItemList::Remove().
Referenced by CONTEXTMENU::CAddRemoveFavourite::Execute(), and CGUIWindowFileManager::OnPopupMenu().
Events()
CEventStream< FavouritesUpdated > & CFavouritesService::Events () inline
References m_events.
Referenced by CGUIWindowFavourites::CGUIWindowFavourites(), CDirectoryProvider::Reset(), CDirectoryProvider::UpdateURL(), and CGUIWindowFavourites::~CGUIWindowFavourites().
GetAll()
void CFavouritesService::GetAll (CFileItemList & items) const
References CFileItemList::Add(), CFileItemList::Clear(), CFileItemList::Copy(), g_passwordManager, CFavouritesURL::GetActionLabel(), CFavouritesURL::GetProviderLabel(), index(), CGUIPassword::IsMasterLockUnlocked(), m_criticalSection, and m_favourites.
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonUnInstallJob::ClearFavourites(), CONTEXTMENU::CFavouriteContextMenuAction::Execute(), XFILE::CFavouritesDirectory::GetDirectory(), and JSONRPC::CFavouritesOperations::GetFavourites().
GetFavourite()
std::shared_ptr< CFileItem > CFavouritesService::GetFavourite (const CFileItem & item, int contextWindow) const
References CFavouritesURL::ACTIVATE_WINDOW, CFileItem::GetPath(), URIUtils::IsMusicDb(), URIUtils::IsVideoDb(), m_criticalSection, m_favourites, and ResolveFavourite().
Referenced by AddOrRemove(), and IsFavourited().
IsFavourited()
bool CFavouritesService::IsFavourited (const CFileItem & item, int contextWindow) const
References GetFavourite().
OnUpdated()
void CFavouritesService::OnUpdated () private
References m_events.
Referenced by AddOrRemove(), and Save().
operator=() [1/2]
CFavouritesService & CFavouritesService::operator= (CFavouritesService &&) private delete
operator=() [2/2]
CFavouritesService & CFavouritesService::operator= (const CFavouritesService &) private delete
Persist()
bool CFavouritesService::Persist () private
References URIUtils::AddFileToFolder(), CFavouritesURL::GetExecString(), m_favourites, m_userDataFolder, and CXBMCTinyXML2::SaveFile().
Referenced by AddOrRemove(), and Save().
RefreshFavourites()
void CFavouritesService::RefreshFavourites ()
Refresh favourites for directory providers, e.g. the GUI needs to be updated.
References m_events.
Referenced by CGUIPassword::IsItemUnlocked(), MasterMode(), CGUIDialogContextMenu::OnContextButton(), and CGUIDialogLockSettings::ShowAndGetLock().
ReInit()
void CFavouritesService::ReInit (std::string userDataFolder)
For profiles
References URIUtils::AddFileToFolder(), CFileItemList::Clear(), CFileUtils::Exists(), CLog::Log(), LOGDEBUG, m_criticalSection, m_favourites, m_targets, m_userDataFolder, and CFileItemList::SetContent().
Referenced by CFavouritesService(), and CProfileManager::FinalizeLoadProfile().
ResolveFavourite()
std::shared_ptr< CFileItem > CFavouritesService::ResolveFavourite (const CFileItem & favItem) const
References CFileItem::GetPath(), CFileItem::IsFavourite(), m_criticalSection, m_targets, and CWindowTranslator::TranslateWindow().
Referenced by GetFavourite(), CGUIWindowFavourites::OnAction(), CDirectoryProvider::OnClick(), CDirectoryProvider::OnInfo(), CDirectoryProvider::OnPlay(), CGUIWindowFavourites::OnSelect(), and anonymous_namespace{ContextMenus.cpp}::ResolveFavouriteItem().
Save()
bool CFavouritesService::Save (const CFileItemList & items)
References CFileItemList::Clear(), CFileItemList::Copy(), m_criticalSection, m_favourites, m_targets, OnUpdated(), and Persist().
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonUnInstallJob::ClearFavourites(), and CONTEXTMENU::CFavouriteContextMenuAction::Execute().
Size()
int CFavouritesService::Size () const
References m_criticalSection, m_favourites, and CFileItemList::Size().
Member Data Documentation
m_criticalSection
CCriticalSection CFavouritesService::m_criticalSection mutable private
Referenced by AddOrRemove(), GetAll(), GetFavourite(), ReInit(), ResolveFavourite(), Save(), and Size().
m_events
CEventSource<FavouritesUpdated> CFavouritesService::m_events private
Referenced by Events(), OnUpdated(), and RefreshFavourites().
m_favourites
CFileItemList CFavouritesService::m_favourites private
Referenced by AddOrRemove(), GetAll(), GetFavourite(), Persist(), ReInit(), Save(), and Size().
m_targets
std::unordered_map<std::string, std::shared_ptr<CFileItem> > CFavouritesService::m_targets mutable private
Referenced by AddOrRemove(), ReInit(), ResolveFavourite(), and Save().
m_userDataFolder
std::string CFavouritesService::m_userDataFolder private
Referenced by Persist(), and ReInit().
The documentation for this class was generated from the following files:
FavouritesService.h
FavouritesService.cpp