Kodi Documentation: CAndroidTouch Class Reference
CAndroidTouch Class Reference
#include <AndroidTouch.h>
Public Member Functions
CAndroidTouch ()
virtual ~CAndroidTouch ()
bool onTouchEvent (AInputEvent *event)
Protected Member Functions
virtual void setDPI (uint32_t dpi)
Private Attributes
uint32_t m_dpi = 160
Constructor & Destructor Documentation
CAndroidTouch()
CAndroidTouch::CAndroidTouch ()
References CGenericTouchActionHandler::GetInstance(), CGenericTouchInputHandler::GetInstance(), and ITouchInputHandling::RegisterHandler().
~CAndroidTouch()
CAndroidTouch::~CAndroidTouch () virtual
References CGenericTouchInputHandler::GetInstance(), and ITouchInputHandling::UnregisterHandler().
Member Function Documentation
onTouchEvent()
bool CAndroidTouch::onTouchEvent (AInputEvent * event)
References CXBMCApp::android_printf(), CGenericTouchActionHandler::GetInstance(), CGenericTouchInputHandler::GetInstance(), CGenericTouchInputHandler::HandleTouchInput(), int64_t(), CGenericTouchInputHandler::MAX_POINTERS, CGenericTouchActionHandler::QuerySupportedGestures(), TouchInputAbort, TouchInputDown, TouchInputMove, TouchInputUp, and CGenericTouchInputHandler::UpdateTouchPointer().
Referenced by CEventLoop::processInput().
setDPI()
void CAndroidTouch::setDPI (uint32_t dpi) protected virtual
Reimplemented in IInputHandler.
References CGenericTouchInputHandler::GetInstance(), m_dpi, and ITouchInputHandler::SetScreenDPI().
Referenced by IInputHandler::setDPI().
Member Data Documentation
m_dpi
uint32_t CAndroidTouch::m_dpi = 160 private
Referenced by setDPI().
The documentation for this class was generated from the following files:
AndroidTouch.h
AndroidTouch.cpp