Kodi Documentation: CSettingsValueXmlSerializer Class Reference
CSettingsValueXmlSerializer Class Reference
#include <SettingsValueXmlSerializer.h>
Public Member Functions
CSettingsValueXmlSerializer ()=default
~CSettingsValueXmlSerializer ()=default
std::string SerializeValues (const CSettingsManager *settingsManager) const override
Public Member Functions inherited from ISettingsValueSerializer
virtual ~ISettingsValueSerializer ()=default
Private Member Functions
void SerializeSection (TiXmlNode *parent, const std::shared_ptr< CSettingSection > &section) const
void SerializeCategory (TiXmlNode *parent, const std::shared_ptr< CSettingCategory > &category) const
void SerializeGroup (TiXmlNode *parent, const std::shared_ptr< CSettingGroup > &group) const
void SerializeSetting (TiXmlNode *parent, const std::shared_ptr< CSetting > &setting) const
Constructor & Destructor Documentation
CSettingsValueXmlSerializer()
CSettingsValueXmlSerializer::CSettingsValueXmlSerializer () default
~CSettingsValueXmlSerializer()
CSettingsValueXmlSerializer::~CSettingsValueXmlSerializer () default
Member Function Documentation
SerializeCategory()
void CSettingsValueXmlSerializer::SerializeCategory (TiXmlNode * parent, const std::shared_ptr< CSettingCategory > & category) const private
References SerializeGroup().
Referenced by SerializeSection().
SerializeGroup()
void CSettingsValueXmlSerializer::SerializeGroup (TiXmlNode * parent, const std::shared_ptr< CSettingGroup > & group) const private
References SerializeSetting().
Referenced by SerializeCategory().
SerializeSection()
void CSettingsValueXmlSerializer::SerializeSection (TiXmlNode * parent, const std::shared_ptr< CSettingSection > & section) const private
References SerializeCategory().
Referenced by SerializeValues().
SerializeSetting()
void CSettingsValueXmlSerializer::SerializeSetting (TiXmlNode * parent, const std::shared_ptr< CSetting > & setting) const private
References Action, CLog::Log(), LOGWARNING, SETTING_XML_ATTR_ID, SETTING_XML_ELM_DEFAULT, SETTING_XML_ELM_SETTING, and value.
Referenced by SerializeGroup().
SerializeValues()
std::string CSettingsValueXmlSerializer::SerializeValues (const CSettingsManager * settingsManager) const override virtual
Implements ISettingsValueSerializer.
References CSettingsManager::GetSections(), CSettingsManager::GetVersion(), SerializeSection(), SETTING_XML_ROOT_VERSION, and SETTINGS_XML_ROOT.
The documentation for this class was generated from the following files:
SettingsValueXmlSerializer.h
SettingsValueXmlSerializer.cpp