Kodi Documentation: ADDON::CSkinSettingUpdateHandler Class Reference
ADDON::CSkinSettingUpdateHandler Class Reference
Public Member Functions
CSkinSettingUpdateHandler (CAddon &addon)
~CSkinSettingUpdateHandler () override=default
void OnTimeout () override
void TriggerSave ()
Private Attributes
CAddon & m_addon
CTimer m_timer
Additional Inherited Members
Private Member Functions inherited from ITimerCallback
virtual ~ITimerCallback ()=default
Constructor & Destructor Documentation
CSkinSettingUpdateHandler()
ADDON::CSkinSettingUpdateHandler::CSkinSettingUpdateHandler (CAddon & addon) inline
~CSkinSettingUpdateHandler()
ADDON::CSkinSettingUpdateHandler::~CSkinSettingUpdateHandler () override default
Member Function Documentation
OnTimeout()
void ADDON::CSkinSettingUpdateHandler::OnTimeout () override virtual
Implements ITimerCallback.
References m_addon, and ADDON::CAddon::SaveSettings().
TriggerSave()
void ADDON::CSkinSettingUpdateHandler::TriggerSave ()
References CTimer::IsRunning(), m_timer, CTimer::Restart(), and CTimer::Start().
Member Data Documentation
m_addon
CAddon& ADDON::CSkinSettingUpdateHandler::m_addon private
Referenced by OnTimeout().
m_timer
CTimer ADDON::CSkinSettingUpdateHandler::m_timer private
Referenced by TriggerSave().
The documentation for this class was generated from the following file:
Skin.cpp