Kodi Documentation: KODI::GUILIB::GUIINFO::CLibraryGUIInfo Class Reference
KODI::GUILIB::GUIINFO::CLibraryGUIInfo Class Reference
#include <LibraryGUIInfo.h>
Public Member Functions
CLibraryGUIInfo ()
~CLibraryGUIInfo () override=default
bool InitCurrentItem (CFileItem *item) override
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
bool GetLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) const override
Get a GUIInfoManager label string.
bool GetInt (int &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const override
Get a GUIInfoManager integer value.
bool GetBool (bool &value, const CGUIListItem *item, int contextWindow, const CGUIInfo &info) const override
Get a GUIInfoManager bool value.
bool GetLibraryBool (int condition) const
void SetLibraryBool (int condition, bool value)
void ResetLibraryBools ()
Public Member Functions inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
CGUIInfoProvider ()=default
~CGUIInfoProvider () override=default
bool GetFallbackLabel (std::string &value, const CFileItem *item, int contextWindow, const CGUIInfo &info, std::string *fallback) override
Get a GUIInfoManager label fallback string. Will be called if none of the registered provider's GetLabel() implementation has returned success.
void UpdateAVInfo (const AudioStreamInfo &audioInfo, const VideoStreamInfo &videoInfo, const SubtitleStreamInfo &subtitleInfo) override
Set new audio/video stream info data.
Public Member Functions inherited from KODI::GUILIB::GUIINFO::IGUIInfoProvider
virtual ~IGUIInfoProvider ()=default
Private Attributes
int m_libraryHasMusic
int m_libraryHasMovies
int m_libraryHasTVShows
int m_libraryHasMusicVideos
int m_libraryHasMovieSets
int m_libraryHasSingles
int m_libraryHasCompilations
int m_libraryHasBoxsets
std::vector< std::pair< std::string, int > > m_libraryRoleCounts
Additional Inherited Members
Protected Attributes inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
VideoStreamInfo m_videoInfo
AudioStreamInfo m_audioInfo
SubtitleStreamInfo m_subtitleInfo
Constructor & Destructor Documentation
CLibraryGUIInfo()
CLibraryGUIInfo::CLibraryGUIInfo ()
References ResetLibraryBools().
~CLibraryGUIInfo()
KODI::GUILIB::GUIINFO::CLibraryGUIInfo::~CLibraryGUIInfo () override default
Member Function Documentation
GetBool()
bool CLibraryGUIInfo::GetBool (bool & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const override virtual
Get a GUIInfoManager bool value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References URIUtils::AddFileToFolder(), CDatabase::Close(), XFILE::DIR_FLAG_NO_FILE_DIRS, CFileUtils::Exists(), CMusicDatabase::GetArtistCountForRole(), GetBool(), CMusicDatabase::GetBoxsetsCount(), CMusicDatabase::GetCompilationAlbumsCount(), XFILE::CDirectory::GetDirectory(), CURL::GetFileName(), CURL::GetHostName(), CMusicLibraryQueue::GetInstance(), CVideoLibraryQueue::GetInstance(), CServiceBroker::GetSettingsComponent(), CMusicDatabase::GetSinglesCount(), CMusicDatabase::GetSongsCount(), CVideoDatabase::HasContent(), CVideoDatabase::HasSets(), CMusicLibraryQueue::IsScanningLibrary(), CVideoLibraryQueue::IsScanningLibrary(), LIBRARY_HAS_BOXSETS, LIBRARY_HAS_COMPILATIONS, LIBRARY_HAS_MOVIE_SETS, LIBRARY_HAS_MOVIES, LIBRARY_HAS_MUSIC, LIBRARY_HAS_MUSICVIDEOS, LIBRARY_HAS_NODE, LIBRARY_HAS_ROLE, LIBRARY_HAS_SINGLES, LIBRARY_HAS_TVSHOWS, LIBRARY_HAS_VIDEO, LIBRARY_IS_SCANNING, LIBRARY_IS_SCANNING_MUSIC, LIBRARY_IS_SCANNING_VIDEO, m_libraryHasBoxsets, m_libraryHasCompilations, m_libraryHasMovies, m_libraryHasMovieSets, m_libraryHasMusic, m_libraryHasMusicVideos, m_libraryHasSingles, m_libraryHasTVShows, m_libraryRoleCounts, MOVIES, MUSICVIDEOS, CMusicDatabase::Open(), CVideoDatabase::Open(), CFileItemList::Size(), TVSHOWS, and value.
Referenced by GetBool(), and GetLibraryBool().
GetInt()
bool CLibraryGUIInfo::GetInt (int & value, const CGUIListItem * item, int contextWindow, const CGUIInfo & info) const override virtual
Get a GUIInfoManager integer value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
GetLabel()
bool CLibraryGUIInfo::GetLabel (std::string & value, const CFileItem * item, int contextWindow, const CGUIInfo & info, std::string * fallback) const override virtual
Get a GUIInfoManager label string.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
fallback A fallback value. Can be nullptr.
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
GetLibraryBool()
bool CLibraryGUIInfo::GetLibraryBool (int condition) const
References GetBool(), and value.
InitCurrentItem()
bool CLibraryGUIInfo::InitCurrentItem (CFileItem * item) override virtual
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
Parameters
item The new item.
Returns
True if the item was inited by the provider, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
ResetLibraryBools()
void CLibraryGUIInfo::ResetLibraryBools ()
References m_libraryHasBoxsets, m_libraryHasCompilations, m_libraryHasMovies, m_libraryHasMovieSets, m_libraryHasMusic, m_libraryHasMusicVideos, m_libraryHasSingles, m_libraryHasTVShows, and m_libraryRoleCounts.
Referenced by CLibraryGUIInfo(), CMusicDatabase::ImportFromXML(), CProfileManager::LoadProfile(), CGUIWindowMusicBase::OnRemoveSource(), MUSIC_INFO::CMusicInfoScanner::Process(), and KODI::VIDEO::CVideoInfoScanner::Process().
SetLibraryBool()
void CLibraryGUIInfo::SetLibraryBool (int condition, bool value)
References LIBRARY_HAS_BOXSETS, LIBRARY_HAS_COMPILATIONS, LIBRARY_HAS_MOVIE_SETS, LIBRARY_HAS_MOVIES, LIBRARY_HAS_MUSIC, LIBRARY_HAS_MUSICVIDEOS, LIBRARY_HAS_SINGLES, LIBRARY_HAS_TVSHOWS, m_libraryHasBoxsets, m_libraryHasCompilations, m_libraryHasMovies, m_libraryHasMovieSets, m_libraryHasMusic, m_libraryHasMusicVideos, m_libraryHasSingles, m_libraryHasTVShows, and value.
Referenced by CMusicDatabase::CommitTransaction(), and CVideoDatabase::CommitTransaction().
Member Data Documentation
m_libraryHasBoxsets
int KODI::GUILIB::GUIINFO::CLibraryGUIInfo::m_libraryHasBoxsets mutable private
Referenced by GetBool(), ResetLibraryBools(), and SetLibraryBool().
m_libraryHasCompilations
int KODI::GUILIB::GUIINFO::CLibraryGUIInfo::m_libraryHasCompilations mutable private
Referenced by GetBool(), ResetLibraryBools(), and SetLibraryBool().
m_libraryHasMovies
int KODI::GUILIB::GUIINFO::CLibraryGUIInfo::m_libraryHasMovies mutable private
Referenced by GetBool(), ResetLibraryBools(), and SetLibraryBool().
m_libraryHasMovieSets
int KODI::GUILIB::GUIINFO::CLibraryGUIInfo::m_libraryHasMovieSets mutable private
Referenced by GetBool(), ResetLibraryBools(), and SetLibraryBool().
m_libraryHasMusic
int KODI::GUILIB::GUIINFO::CLibraryGUIInfo::m_libraryHasMusic mutable private
Referenced by GetBool(), ResetLibraryBools(), and SetLibraryBool().
m_libraryHasMusicVideos
int KODI::GUILIB::GUIINFO::CLibraryGUIInfo::m_libraryHasMusicVideos mutable private
Referenced by GetBool(), ResetLibraryBools(), and SetLibraryBool().
m_libraryHasSingles
int KODI::GUILIB::GUIINFO::CLibraryGUIInfo::m_libraryHasSingles mutable private
Referenced by GetBool(), ResetLibraryBools(), and SetLibraryBool().
m_libraryHasTVShows
int KODI::GUILIB::GUIINFO::CLibraryGUIInfo::m_libraryHasTVShows mutable private
Referenced by GetBool(), ResetLibraryBools(), and SetLibraryBool().
m_libraryRoleCounts
std::vector<std::pair<std::string, int> > KODI::GUILIB::GUIINFO::CLibraryGUIInfo::m_libraryRoleCounts mutable private
Referenced by GetBool(), and ResetLibraryBools().
The documentation for this class was generated from the following files:
LibraryGUIInfo.h
LibraryGUIInfo.cpp