Kodi Documentation: CMediaCodecVideoBuffer Class Reference
CMediaCodecVideoBuffer Class Reference
#include <DVDVideoCodecAndroidMediaCodec.h>
Public Member Functions
CMediaCodecVideoBuffer (int id)
~CMediaCodecVideoBuffer () override=default
void Set (int internalId, int textureId, std::shared_ptr< CJNISurfaceTexture > surfaceTexture, std::shared_ptr< CDVDMediaCodecOnFrameAvailable > frameAvailable, std::shared_ptr< jni::CJNIXBMCVideoView > videoView)
bool WaitForFrame (int millis)
void ReleaseOutputBuffer (bool render, int64_t displayTime, CMediaCodecVideoBufferPool *pool=nullptr)
int GetBufferId () const
int GetTextureId () const
void GetTransformMatrix (float *textureMatrix)
void UpdateTexImage ()
void RenderUpdate (const CRect &DestRect, int64_t displayTime)
bool HasSurfaceTexture () const
Public Member Functions inherited from CVideoBuffer
CVideoBuffer ()=delete
virtual ~CVideoBuffer ()=default
void Acquire ()
void Acquire (std::shared_ptr< IVideoBufferPool > pool)
void Release ()
int GetId () const
virtual AVPixelFormat GetFormat ()
virtual uint8_t * GetMemPtr ()
virtual void GetPlanes (uint8_t *(&planes)[YuvImage::MAX_PLANES])
virtual void GetStrides (int(&strides)[YuvImage::MAX_PLANES])
virtual void SetPixelFormat (const AVPixelFormat pixFormat)
virtual void SetDimensions (int width, int height, const int(&strides)[YuvImage::MAX_PLANES])
virtual void SetDimensions (int width, int height, const int(&strides)[YuvImage::MAX_PLANES], const int(&planeOffsets)[YuvImage::MAX_PLANES])
Private Attributes
int m_bufferId = -1
unsigned int m_textureId = 0
std::shared_ptr< CJNISurfaceTexture > m_surfacetexture
std::shared_ptr< CDVDMediaCodecOnFrameAvailable > m_frameready
std::shared_ptr< jni::CJNIXBMCVideoView > m_videoview
Additional Inherited Members
Static Public Member Functions inherited from CVideoBuffer
static bool CopyPicture (YuvImage *pDst, YuvImage *pSrc)
static bool CopyNV12Picture (YuvImage *pDst, YuvImage *pSrc)
static bool CopyYUV422PackedPicture (YuvImage *pDst, YuvImage *pSrc)
Protected Member Functions inherited from CVideoBuffer
CVideoBuffer (int id)
Protected Attributes inherited from CVideoBuffer
AVPixelFormat m_pixFormat = AV_PIX_FMT_NONE
std::atomic_int m_refCount
int m_id
std::shared_ptr< IVideoBufferPool > m_pool
Constructor & Destructor Documentation
CMediaCodecVideoBuffer()
CMediaCodecVideoBuffer::CMediaCodecVideoBuffer (int id) inline
~CMediaCodecVideoBuffer()
CMediaCodecVideoBuffer::~CMediaCodecVideoBuffer () override default
Member Function Documentation
GetBufferId()
int CMediaCodecVideoBuffer::GetBufferId () const
References m_bufferId.
Referenced by CDVDVideoCodecAndroidMediaCodec::GetPicture().
GetTextureId()
int CMediaCodecVideoBuffer::GetTextureId () const
References m_textureId.
Referenced by CRendererMediaCodec::AddVideoPicture().
GetTransformMatrix()
void CMediaCodecVideoBuffer::GetTransformMatrix (float * textureMatrix)
References m_surfacetexture.
Referenced by CRendererMediaCodec::ReleaseBuffer().
HasSurfaceTexture()
bool CMediaCodecVideoBuffer::HasSurfaceTexture () const inline
References bool(), and m_surfacetexture.
ReleaseOutputBuffer()
void CMediaCodecVideoBuffer::ReleaseOutputBuffer (bool render, int64_t displayTime, CMediaCodecVideoBufferPool * pool = nullptr)
References CLog::CanLogComponent(), CurrentHostCounter(), CServiceBroker::GetLogging(), int64_t(), CLog::Log(), LOGDEBUG, LOGERROR, LOGVIDEO, m_bufferId, m_frameready, and CVideoBuffer::m_pool.
Referenced by CRendererMediaCodec::AddVideoPicture(), CRendererMediaCodecSurface::ReleaseVideoBuffer(), and RenderUpdate().
RenderUpdate()
void CMediaCodecVideoBuffer::RenderUpdate (const CRect & DestRect, int64_t displayTime)
References CXBMCApp::Get(), CRectGen< T >::Height(), CLog::Log(), LOGDEBUG, LOGVIDEO, m_videoview, CXBMCApp::MapRenderToDroid(), ReleaseOutputBuffer(), CRectGen< T >::Width(), CRectGen< T >::x1, and CRectGen< T >::y1.
Referenced by CRendererMediaCodecSurface::ReleaseVideoBuffer().
Set()
void CMediaCodecVideoBuffer::Set (int internalId, int textureId, std::shared_ptr< CJNISurfaceTexture > surfaceTexture, std::shared_ptr< CDVDMediaCodecOnFrameAvailable > frameAvailable, std::shared_ptr< jni::CJNIXBMCVideoView > videoView)
References m_bufferId, m_frameready, m_surfacetexture, m_textureId, and m_videoview.
UpdateTexImage()
void CMediaCodecVideoBuffer::UpdateTexImage ()
References CLog::Log(), LOGERROR, m_surfacetexture, and WaitForFrame().
Referenced by CRendererMediaCodec::ReleaseBuffer().
WaitForFrame()
bool CMediaCodecVideoBuffer::WaitForFrame (int millis)
References m_frameready.
Referenced by UpdateTexImage().
Member Data Documentation
m_bufferId
int CMediaCodecVideoBuffer::m_bufferId = -1 private
Referenced by GetBufferId(), ReleaseOutputBuffer(), and Set().
m_frameready
std::shared_ptr<CDVDMediaCodecOnFrameAvailable> CMediaCodecVideoBuffer::m_frameready private
Referenced by ReleaseOutputBuffer(), Set(), and WaitForFrame().
m_surfacetexture
std::shared_ptr<CJNISurfaceTexture> CMediaCodecVideoBuffer::m_surfacetexture private
Referenced by GetTransformMatrix(), HasSurfaceTexture(), Set(), and UpdateTexImage().
m_textureId
unsigned int CMediaCodecVideoBuffer::m_textureId = 0 private
Referenced by GetTextureId(), and Set().
m_videoview
std::shared_ptr<jni::CJNIXBMCVideoView> CMediaCodecVideoBuffer::m_videoview private
Referenced by RenderUpdate(), and Set().
The documentation for this class was generated from the following files:
DVDVideoCodecAndroidMediaCodec.h
DVDVideoCodecAndroidMediaCodec.cpp