Kodi Documentation: CTextureCacheJob Class Reference
CTextureCacheJob Class Reference
Guilib classes » Graphics and Screen » Textures and Fonts
Job class for caching textures.
#include <TextureCacheJob.h>
Public Member Functions
CTextureCacheJob (const std::string &url, const std::string &oldHash="")
~CTextureCacheJob () override
const char * GetType () const override
Function that returns the type of job.
bool operator== (const CJob *job) const override
bool DoWork () override
Main workhorse function of CJob instances.
bool CacheTexture (std::unique_ptr< CTexture > *texture=nullptr)
retrieve a hash for the given image Combines the size, ctime and mtime of the image file into a "unique" hash
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
virtual bool ShouldCancel (unsigned int progress, unsigned int total) const
Function for longer jobs to report progress and check whether they have been cancelled.
Static Public Member Functions
static bool ResizeTexture (const std::string &url, unsigned int height, unsigned int width, CPictureScalingAlgorithm::Algorithm scalingAlgorithm, uint8_t *&result, size_t &result_size)
Public Attributes
std::string m_url
std::string m_oldHash
CTextureDetails m_details
Static Private Member Functions
static std::string GetImageHash (const std::string &url)
retrieve a hash for the given image Combines the size, ctime and mtime of the image file into a "unique" hash
static std::unique_ptr< CTexture > LoadImage (const IMAGE_FILES::CImageFileURL &imageURL)
Load an image at a given target size and orientation.
Private Attributes
std::string m_cachePath
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Detailed Description
Job class for caching textures.
Handles loading and caching of textures.
Constructor & Destructor Documentation
CTextureCacheJob()
CTextureCacheJob::CTextureCacheJob (const std::string & url, const std::string & oldHash = "")
~CTextureCacheJob()
CTextureCacheJob::~CTextureCacheJob () override default
Member Function Documentation
CacheTexture()
bool CTextureCacheJob::CacheTexture (std::unique_ptr< CTexture > * texture = nullptr)
retrieve a hash for the given image Combines the size, ctime and mtime of the image file into a "unique" hash
Parameters
url location of the image
Returns
a hash string for this image
References CPicture::CacheTexture(), CTextureDetails::file, CTextureCache::GetCachedPath(), GetImageHash(), IMAGE_FILES::CImageFileURL::GetTargetFile(), CTextureDetails::hash, CTextureDetails::hashRevalidated, CTextureDetails::height, LoadImage(), CLog::Log(), LOGDEBUG, m_cachePath, m_details, m_oldHash, m_url, CTextureDetails::updateable, and CTextureDetails::width.
Referenced by CTextureCache::CacheImage(), and DoWork().
DoWork()
bool CTextureCacheJob::DoWork () override virtual
Main workhorse function of CJob instances.
All CJob subclasses must implement this function, performing all processing. Once this function is complete, the OnJobComplete() callback is called, and the job is then destroyed.
See also
CJobManager, IJobCallback::OnJobComplete()
Implements CJob.
References CacheTexture(), CServiceBroker::GetTextureCache(), m_url, and CJob::ShouldCancel().
GetImageHash()
std::string CTextureCacheJob::GetImageHash (const std::string & url) static private
retrieve a hash for the given image Combines the size, ctime and mtime of the image file into a "unique" hash
Parameters
url location of the image
Returns
a hash string for this image
References __stat64, int64_t(), URIUtils::IsProtocol(), CLog::Log(), LOGDEBUG, and XFILE::CFile::Stat().
Referenced by CacheTexture().
GetType()
const char * CTextureCacheJob::GetType () const inline override virtual
Function that returns the type of job.
CJob subclasses may optionally implement this function to specify the type of job. This is useful for the CJobManager::AddLIFOJob() routine, which preempts similar jobs with the new job.
Returns
a unique character string describing the job.
See also
CJobManager
Reimplemented from CJob.
References kJobTypeCacheImage.
Referenced by operator==().
LoadImage()
std::unique_ptr< CTexture > CTextureCacheJob::LoadImage (const IMAGE_FILES::CImageFileURL & imageURL) static private
Load an image at a given target size and orientation.
Doesn't necessarily load the image at the desired size - the loader may decide to load it slightly larger or smaller than the desired size for speed reasons.
Parameters
image the URL of the image file.
Returns
a pointer to a CTexture object, NULL if failed.
References IMAGE_FILES::CImageFileURL::flipped, IMAGE_FILES::CImageFileURL::GetTargetFile(), IMAGE_FILES::CImageFileURL::IsSpecialImage(), IMAGE_FILES::CSpecialImageLoaderFactory::Load(), and CTexture::LoadFromFile().
Referenced by CacheTexture(), and ResizeTexture().
operator==()
bool CTextureCacheJob::operator== (const CJob * job) const override virtual
Reimplemented from CJob.
References CJob::GetType(), GetType(), and m_cachePath.
ResizeTexture()
bool CTextureCacheJob::ResizeTexture (const std::string & url, unsigned int height, unsigned int width, CPictureScalingAlgorithm::Algorithm scalingAlgorithm, uint8_t *& result, size_t & result_size) static
References IMAGE_FILES::CImageFileURL::GetTargetFile(), LoadImage(), CPicture::ResizeTexture(), and success.
Referenced by CHTTPImageTransformationHandler::HandleRequest().
Member Data Documentation
m_cachePath
std::string CTextureCacheJob::m_cachePath private
Referenced by CacheTexture(), and operator==().
m_details
CTextureDetails CTextureCacheJob::m_details
Referenced by CTextureCache::CacheImage(), CacheTexture(), and CTextureCache::OnCachingComplete().
m_oldHash
std::string CTextureCacheJob::m_oldHash
Referenced by CacheTexture().
m_url
std::string CTextureCacheJob::m_url
Referenced by CacheTexture(), DoWork(), and CTextureCache::OnCachingComplete().
The documentation for this class was generated from the following files:
TextureCacheJob.h
TextureCacheJob.cpp