Kodi Documentation: CDVDOverlayCodecText Class Reference
CDVDOverlayCodecText Class Reference
#include <DVDOverlayCodecText.h>
Public Member Functions
CDVDOverlayCodecText ()
~CDVDOverlayCodecText () override=default
bool Open (CDVDStreamInfo &hints, CDVDCodecOptions &options) override
OverlayMessage Decode (DemuxPacket *pPacket) override
void Reset () override
void Flush () override
std::shared_ptr< CDVDOverlay > GetOverlay () override
void PostProcess (std::string &text) override
Post processing of subtitle, will be called before processing AddSubtitle method.
Public Member Functions inherited from CDVDOverlayCodec
CDVDOverlayCodec (const char *name)
virtual ~CDVDOverlayCodec ()=default
const std::string & GetName () const
Private Attributes
std::shared_ptr< CDVDOverlay > m_pOverlay
CDVDStreamInfo m_hints
int m_prevSubId {-1}
bool m_changePrevStopTime {false}
AVCodecID m_codecId {AV_CODEC_ID_NONE}
Additional Inherited Members
Static Protected Member Functions inherited from CDVDOverlayCodec
static void GetAbsoluteTimes (double &starttime, double &stoptime, DemuxPacket *pkt)
Private Member Functions inherited from CSubtitlesAdapter
CSubtitlesAdapter ()
virtual ~CSubtitlesAdapter ()
bool Initialize ()
Initialize the subtitles adapter.
int AddSubtitle (std::string &text, double startTime, double stopTime)
Add a subtitle.
int AddSubtitle (std::string &text, double startTime, double stopTime, KODI::SUBTITLES::STYLE::subtitleOpts *opts)
Add a subtitle with supplementary options.
void AppendToSubtitle (int subtitleId, const char *text)
Append text to the specified subtitle ID.
int DeleteSubtitles (int nSubtitles, int threshold)
Delete old subtitles only if the total number of subtitles added reaches the threshold.
void ChangeSubtitleStopTime (int subtitleId, double stopTime)
Change the stop time of a subtitle ID with the specified time.
void FlushSubtitles ()
std::shared_ptr< CDVDOverlay > CreateOverlay ()
Constructor & Destructor Documentation
CDVDOverlayCodecText()
CDVDOverlayCodecText::CDVDOverlayCodecText ()
~CDVDOverlayCodecText()
CDVDOverlayCodecText::~CDVDOverlayCodecText () override default
Member Function Documentation
Decode()
OverlayMessage CDVDOverlayCodecText::Decode (DemuxPacket * pPacket) override virtual
Implements CDVDOverlayCodec.
References CSubtitlesAdapter::AddSubtitle(), CSubtitlesAdapter::ChangeSubtitleStopTime(), CDVDSubtitleTagSami::CloseTag(), CDVDSubtitleTagSami::ConvertLine(), data(), end(), CDVDOverlayCodec::GetAbsoluteTimes(), CDVDSubtitleTagSami::Init(), DEMUX_PACKET::iSize, CLog::Log(), LOGERROR, m_changePrevStopTime, m_codecId, m_pOverlay, m_prevSubId, OC_DONE, OC_ERROR, OC_OVERLAY, DEMUX_PACKET::pData, and text.
Flush()
void CDVDOverlayCodecText::Flush () override virtual
Implements CDVDOverlayCodec.
References CSubtitlesAdapter::FlushSubtitles(), and m_pOverlay.
Referenced by Reset().
GetOverlay()
std::shared_ptr< CDVDOverlay > CDVDOverlayCodecText::GetOverlay () override virtual
Implements CDVDOverlayCodec.
References CSubtitlesAdapter::CreateOverlay(), and m_pOverlay.
Open()
bool CDVDOverlayCodecText::Open (CDVDStreamInfo & hints, CDVDCodecOptions & options) override virtual
Implements CDVDOverlayCodec.
References CDVDStreamInfo::codec, CSubtitlesAdapter::Initialize(), m_codecId, and m_pOverlay.
PostProcess()
void CDVDOverlayCodecText::PostProcess (std::string & text) override virtual
Post processing of subtitle, will be called before processing AddSubtitle method.
Parameters
text The subtitle text
Reimplemented from CSubtitlesAdapter.
References CSubtitlesAdapter::PostProcess(), and text.
Reset()
void CDVDOverlayCodecText::Reset () override virtual
Implements CDVDOverlayCodec.
References Flush().
Member Data Documentation
m_changePrevStopTime
bool CDVDOverlayCodecText::m_changePrevStopTime {false} private
Referenced by Decode().
m_codecId
AVCodecID CDVDOverlayCodecText::m_codecId {AV_CODEC_ID_NONE} private
Referenced by Decode(), and Open().
m_hints
CDVDStreamInfo CDVDOverlayCodecText::m_hints private
m_pOverlay
std::shared_ptr<CDVDOverlay> CDVDOverlayCodecText::m_pOverlay private
Referenced by Decode(), Flush(), GetOverlay(), and Open().
m_prevSubId
int CDVDOverlayCodecText::m_prevSubId {-1} private
Referenced by Decode().
The documentation for this class was generated from the following files:
DVDOverlayCodecText.h
DVDOverlayCodecText.cpp