Kodi Documentation: TestRingBuffer.cpp File Reference
TestRingBuffer.cpp File Reference
#include "utils/RingBuffer.h"
#include <gtest/gtest.h>
Functions
TEST (TestRingBuffer, General)
Function Documentation
TEST()
TEST (TestRingBuffer , General)
References CRingBuffer::Clear(), CRingBuffer::Create(), data(), EXPECT_EQ(), EXPECT_TRUE(), CRingBuffer::getBuffer(), CRingBuffer::getSize(), CRingBuffer::ReadData(), and CRingBuffer::WriteData().