Kodi Documentation: CInertialScrollingHandler Class Reference
CInertialScrollingHandler Class Reference
#include <InertialScrollingHandler.h>
Classes
struct PanPoint
Public Member Functions
CInertialScrollingHandler ()
bool IsScrolling ()
Private Member Functions
bool CheckForInertialScrolling (const CAction *action)
bool ProcessInertialScroll (float frameTime)
Private Attributes
bool m_bScrolling = false
bool m_bAborting = false
CVector m_iFlickVelocity
std::deque< PanPoint > m_panPoints
CPoint m_iLastGesturePoint
CVector m_inertialDeacceleration
unsigned int m_inertialStartTime = 0
float m_timeToZero = 0.0f
Friends
class CApplication
Constructor & Destructor Documentation
CInertialScrollingHandler()
CInertialScrollingHandler::CInertialScrollingHandler ()
Member Function Documentation
CheckForInertialScrolling()
bool CInertialScrollingHandler::CheckForInertialScrolling (const CAction * action) private
References ACTION_GESTURE_ABORT, ACTION_GESTURE_BEGIN, ACTION_GESTURE_END, ACTION_GESTURE_PAN, ACTION_MOUSE_LEFT_CLICK, EVENT_RESULT_PAN_HORIZONTAL, EVENT_RESULT_PAN_VERTICAL, CServiceBroker::GetAppComponents(), CTimeUtils::GetFrameTime(), CServiceBroker::GetGUI(), CGenericTouchInputHandler::GetInstance(), CGUIMessage::GetPointer(), ITouchInputHandler::GetScreenDPI(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), GUI_MSG_EXCLUSIVE_MOUSE, GUI_MSG_GESTURE_NOTIFY, m_bAborting, m_bScrolling, m_iFlickVelocity, m_iLastGesturePoint, m_inertialDeacceleration, m_inertialStartTime, m_panPoints, m_timeToZero, MAXIMUM_DELAY_FOR_INERTIA, MAXIMUM_SPEED_FOR_REDUCTION, MINIMUM_SPEED_FOR_INERTIA, CApplicationPowerHandling::ResetScreenSaver(), CGUIWindowManager::SendMessage(), SendMessage(), CGUIMessage::SetPointer(), TIME_TO_ZERO_SPEED, CPointGen< T >::x, CVector::x, CPointGen< T >::y, and CVector::y.
IsScrolling()
bool CInertialScrollingHandler::IsScrolling () inline
References m_bScrolling.
ProcessInertialScroll()
bool CInertialScrollingHandler::ProcessInertialScroll (float frameTime) private
References ACTION_GESTURE_END, ACTION_GESTURE_PAN, g_application, CTimeUtils::GetFrameTime(), m_bAborting, m_bScrolling, m_iFlickVelocity, m_iLastGesturePoint, m_inertialDeacceleration, m_inertialStartTime, m_timeToZero, CPointGen< T >::x, CVector::x, CPointGen< T >::y, and CVector::y.
Friends And Related Symbol Documentation
CApplication
friend class CApplication friend
Member Data Documentation
m_bAborting
bool CInertialScrollingHandler::m_bAborting = false private
Referenced by CheckForInertialScrolling(), and ProcessInertialScroll().
m_bScrolling
bool CInertialScrollingHandler::m_bScrolling = false private
Referenced by CheckForInertialScrolling(), IsScrolling(), and ProcessInertialScroll().
m_iFlickVelocity
CVector CInertialScrollingHandler::m_iFlickVelocity private
Referenced by CheckForInertialScrolling(), and ProcessInertialScroll().
m_iLastGesturePoint
CPoint CInertialScrollingHandler::m_iLastGesturePoint private
Referenced by CheckForInertialScrolling(), and ProcessInertialScroll().
m_inertialDeacceleration
CVector CInertialScrollingHandler::m_inertialDeacceleration private
Referenced by CheckForInertialScrolling(), and ProcessInertialScroll().
m_inertialStartTime
unsigned int CInertialScrollingHandler::m_inertialStartTime = 0 private
Referenced by CheckForInertialScrolling(), and ProcessInertialScroll().
m_panPoints
std::deque<PanPoint> CInertialScrollingHandler::m_panPoints private
Referenced by CheckForInertialScrolling().
m_timeToZero
float CInertialScrollingHandler::m_timeToZero = 0.0f private
Referenced by CheckForInertialScrolling(), and ProcessInertialScroll().
The documentation for this class was generated from the following files:
InertialScrollingHandler.h
InertialScrollingHandler.cpp