Kodi Documentation: MUSIC_INFO::CMusicInfoTag Class Reference
MUSIC_INFO::CMusicInfoTag Class Reference final
#include <MusicInfoTag.h>
Public Member Functions
CMusicInfoTag (void)
bool operator!= (const CMusicInfoTag &tag) const
bool Loaded () const
const std::string & GetTitle () const
const std::string & GetURL () const
const std::vector< std::string > & GetArtist () const
const std::string & GetArtistSort () const
const std::string GetArtistString () const
const std::string & GetComposerSort () const
const std::string & GetAlbum () const
int GetAlbumId () const
const std::vector< std::string > & GetAlbumArtist () const
const std::string GetAlbumArtistString () const
const std::string & GetAlbumArtistSort () const
const std::vector< std::string > & GetGenre () const
int GetTrackNumber () const
int GetDiscNumber () const
int GetTrackAndDiscNumber () const
int GetTotalDiscs () const
int GetDuration () const
int GetYear () const
const std::string & GetReleaseDate () const
const std::string GetReleaseYear () const
const std::string & GetOriginalDate () const
const std::string GetOriginalYear () const
int GetDatabaseId () const
const std::string & GetType () const
const std::string & GetDiscSubtitle () const
int GetBPM () const
std::string GetYearString () const
const std::string & GetMusicBrainzTrackID () const
const std::vector< std::string > & GetMusicBrainzArtistID () const
const std::vector< std::string > & GetMusicBrainzArtistHints () const
const std::string & GetMusicBrainzAlbumID () const
const std::string & GetMusicBrainzReleaseGroupID () const
const std::vector< std::string > & GetMusicBrainzAlbumArtistID () const
const std::vector< std::string > & GetMusicBrainzAlbumArtistHints () const
const std::string & GetMusicBrainzReleaseType () const
const std::string & GetComment () const
const std::string & GetMood () const
const std::string & GetRecordLabel () const
const std::string & GetLyrics () const
const std::string & GetCueSheet () const
const CDateTime & GetLastPlayed () const
const CDateTime & GetDateAdded () const
bool GetCompilation () const
bool GetBoxset () const
float GetRating () const
int GetUserrating () const
int GetVotes () const
int GetListeners () const
int GetPlayCount () const
int GetBitRate () const
int GetNoOfChannels () const
int GetSampleRate () const
const std::string & GetAlbumReleaseStatus () const
const std::string & GetStationName () const
const std::string & GetStationArt () const
const std::string & GetSongVideoURL () const
const EmbeddedArtInfo & GetCoverArtInfo () const
const ReplayGain & GetReplayGain () const
CAlbum::ReleaseType GetAlbumReleaseType () const
void SetURL (const std::string &strURL)
void SetTitle (const std::string &strTitle)
void SetArtist (const std::string &strArtist)
void SetArtist (const std::vector< std::string > &artists, bool FillDesc=false)
void SetArtistDesc (const std::string &strArtistDesc)
void SetArtistSort (const std::string &strArtistsort)
void SetComposerSort (const std::string &strComposerSort)
void SetAlbum (const std::string &strAlbum)
void SetAlbumId (const int iAlbumId)
void SetAlbumArtist (const std::string &strAlbumArtist)
void SetAlbumArtist (const std::vector< std::string > &albumArtists, bool FillDesc=false)
void SetAlbumArtistDesc (const std::string &strAlbumArtistDesc)
void SetAlbumArtistSort (const std::string &strAlbumArtistSort)
void SetGenre (const std::string &strGenre, bool bTrim=false)
void SetGenre (const std::vector< std::string > &genres, bool bTrim=false)
void SetYear (int year)
void SetOriginalDate (const std::string &strOriginalDate)
void SetReleaseDate (const std::string &strReleaseDate)
void SetDatabaseId (int id, const std::string &type)
void SetTrackNumber (int iTrack)
void SetDiscNumber (int iDiscNumber)
void SetTrackAndDiscNumber (int iTrackAndDisc)
void SetDuration (int iSec)
void SetLoaded (bool bOnOff=true)
void SetArtist (const CArtist &artist)
void SetAlbum (const CAlbum &album)
void SetSong (const CSong &song)
void SetMusicBrainzTrackID (const std::string &strTrackID)
void SetMusicBrainzArtistID (const std::vector< std::string > &musicBrainzArtistId)
void SetMusicBrainzArtistHints (const std::vector< std::string > &musicBrainzArtistHints)
void SetMusicBrainzAlbumID (const std::string &strAlbumID)
void SetMusicBrainzAlbumArtistID (const std::vector< std::string > &musicBrainzAlbumArtistId)
void SetMusicBrainzAlbumArtistHints (const std::vector< std::string > &musicBrainzAlbumArtistHints)
void SetMusicBrainzReleaseGroupID (const std::string &strReleaseGroupID)
void SetMusicBrainzReleaseType (const std::string &ReleaseType)
void SetComment (const std::string &comment)
void SetMood (const std::string &mood)
void SetRecordLabel (const std::string &publisher)
void SetLyrics (const std::string &lyrics)
void SetCueSheet (const std::string &cueSheet)
void SetRating (float rating)
void SetUserrating (int rating)
void SetVotes (int votes)
void SetListeners (int listeners)
void SetPlayCount (int playcount)
void SetLastPlayed (const std::string &strLastPlayed)
void SetLastPlayed (const CDateTime &strLastPlayed)
void SetDateAdded (const std::string &strDateAdded)
void SetDateAdded (const CDateTime &dateAdded)
void SetDateUpdated (const std::string &strDateUpdated)
void SetDateUpdated (const CDateTime &dateUpdated)
void SetDateNew (const std::string &strDateNew)
void SetDateNew (const CDateTime &dateNew)
void SetCompilation (bool compilation)
void SetBoxset (bool boxset)
void SetCoverArtInfo (size_t size, const std::string &mimeType)
void SetReplayGain (const ReplayGain &aGain)
void SetAlbumReleaseType (CAlbum::ReleaseType releaseType)
void SetType (const MediaType &mediaType)
void SetDiscSubtitle (const std::string &strDiscSubtitle)
void SetTotalDiscs (int iDiscTotal)
void SetBPM (int iBPM)
void SetBitRate (int bitrate)
void SetNoOfChannels (int channels)
void SetSampleRate (int samplerate)
void SetAlbumReleaseStatus (const std::string &strReleaseStatus)
void SetStationName (const std::string &strStationName)
void SetStationArt (const std::string &strStationArt)
void SetSongVideoURL (const std::string &songVideoURL)
void AppendArtist (const std::string &artist)
Append a unique artist to the artist list Checks if we have this artist already added, and if not adds it to the songs artist list.
void AppendAlbumArtist (const std::string &albumArtist)
Append a unique album artist to the artist list Checks if we have this album artist already added, and if not adds it to the songs album artist list.
void AppendGenre (const std::string &genre)
Append a unique genre to the genre list Checks if we have this genre already added, and if not adds it to the songs genre list.
void AddOriginalDate (const std::string &strDateYear)
void AddReleaseDate (const std::string &strDateYear, bool isMonth=false)
void AddArtistRole (const std::string &Role, const std::string &strArtist)
void AddArtistRole (const std::string &Role, const std::vector< std::string > &artists)
void AppendArtistRole (const CMusicRole &ArtistRole)
const std::string GetArtistStringForRole (const std::string &strRole) const
const std::string GetContributorsText () const
const std::string GetContributorsAndRolesText () const
const VECMUSICROLES & GetContributors () const
void SetContributors (const VECMUSICROLES &contributors)
bool HasContributors () const
void Archive (CArchive &ar) override
void Serialize (CVariant &ar) const override
void ToSortable (SortItem &sortable, Field field) const override
void Clear ()
Protected Member Functions
std::string Trim (const std::string &value) const
Trim whitespace off the given string.
Protected Member Functions inherited from IArchivable
virtual ~IArchivable ()=default
Protected Member Functions inherited from ISerializable
~ISerializable ()=default
Protected Member Functions inherited from ISortable
~ISortable ()=default
Protected Attributes
std::string m_strURL
std::string m_strTitle
std::vector< std::string > m_artist
std::string m_strArtistSort
std::string m_strArtistDesc
std::string m_strComposerSort
std::string m_strAlbum
std::vector< std::string > m_albumArtist
std::string m_strAlbumArtistDesc
std::string m_strAlbumArtistSort
std::vector< std::string > m_genre
std::string m_strMusicBrainzTrackID
std::vector< std::string > m_musicBrainzArtistID
std::vector< std::string > m_musicBrainzArtistHints
std::string m_strMusicBrainzAlbumID
std::vector< std::string > m_musicBrainzAlbumArtistID
std::vector< std::string > m_musicBrainzAlbumArtistHints
std::string m_strMusicBrainzReleaseGroupID
std::string m_strMusicBrainzReleaseType
VECMUSICROLES m_musicRoles
std::string m_strComment
std::string m_strMood
std::string m_strRecordLabel
std::string m_strLyrics
std::string m_cuesheet
std::string m_strDiscSubtitle
std::string m_strReleaseDate
std::string m_strOriginalDate
CDateTime m_lastPlayed
CDateTime m_dateNew
CDateTime m_dateAdded
CDateTime m_dateUpdated
bool m_bCompilation
int m_iDuration
int m_iTrack
int m_iDbId
MediaType m_type
item type "music", "song", "album", "artist"
bool m_bLoaded
float m_Rating
int m_Userrating
int m_Votes
int m_listeners
int m_iTimesPlayed
int m_iAlbumId
int m_iDiscTotal
bool m_bBoxset
int m_iBPM
CAlbum::ReleaseType m_albumReleaseType
std::string m_strReleaseStatus
int m_samplerate
int m_channels
int m_bitrate
std::string m_stationName
std::string m_stationArt
std::string m_songVideoURL
EmbeddedArtInfo m_coverArt
art information
ReplayGain m_replayGain
ReplayGain information.
Constructor & Destructor Documentation
CMusicInfoTag()
CMusicInfoTag::CMusicInfoTag (void)
References Clear().
Member Function Documentation
AddArtistRole() [1/2]
void CMusicInfoTag::AddArtistRole (const std::string & Role, const std::string & strArtist)
References AddArtistRole(), and CServiceBroker::GetSettingsComponent().
Referenced by AddArtistRole().
AddArtistRole() [2/2]
void CMusicInfoTag::AddArtistRole (const std::string & Role, const std::vector< std::string > & artists)
References index(), m_musicRoles, and Trim().
AddOriginalDate()
void CMusicInfoTag::AddOriginalDate (const std::string & strDateYear)
References m_strOriginalDate.
AddReleaseDate()
void CMusicInfoTag::AddReleaseDate (const std::string & strDateYear, bool isMonth = false)
References GetReleaseYear(), and m_strReleaseDate.
AppendAlbumArtist()
void CMusicInfoTag::AppendAlbumArtist (const std::string & albumArtist)
Append a unique album artist to the artist list Checks if we have this album artist already added, and if not adds it to the songs album artist list.
Parameters
albumArtist album artist to add.
References index(), and m_albumArtist.
AppendArtist()
void CMusicInfoTag::AppendArtist (const std::string & artist)
Append a unique artist to the artist list Checks if we have this artist already added, and if not adds it to the songs artist list.
Parameters
value artist to add.
References index(), and m_artist.
AppendArtistRole()
void CMusicInfoTag::AppendArtistRole (const CMusicRole & ArtistRole)
References m_musicRoles.
Referenced by CMusicDatabase::GetRecentlyAddedAlbumSongs(), CMusicDatabase::GetRecentlyPlayedAlbumSongs(), and CMusicDatabase::GetSongsFullByWhere().
AppendGenre()
void CMusicInfoTag::AppendGenre (const std::string & genre)
Append a unique genre to the genre list Checks if we have this genre already added, and if not adds it to the songs genre list.
Parameters
genre genre to add.
References index(), and m_genre.
Archive()
void CMusicInfoTag::Archive (CArchive & ar) override virtual
Implements IArchivable.
References CArchive::IsStoring(), m_albumArtist, m_albumReleaseType, m_artist, m_bBoxset, m_bCompilation, m_bitrate, m_bLoaded, m_channels, m_coverArt, m_cuesheet, m_dateAdded, m_genre, m_iAlbumId, m_iBPM, m_iDbId, m_iDiscTotal, m_iDuration, m_iTimesPlayed, m_iTrack, m_lastPlayed, m_listeners, m_musicBrainzAlbumArtistID, m_musicBrainzArtistID, m_musicRoles, m_Rating, m_samplerate, m_songVideoURL, m_strAlbum, m_strAlbumArtistDesc, m_strArtistDesc, m_strArtistSort, m_strComment, m_strDiscSubtitle, m_strLyrics, m_strMood, m_strMusicBrainzAlbumID, m_strMusicBrainzReleaseGroupID, m_strMusicBrainzReleaseType, m_strMusicBrainzTrackID, m_strOriginalDate, m_strRecordLabel, m_strReleaseDate, m_strReleaseStatus, m_strTitle, m_strURL, m_type, m_Userrating, and m_Votes.
Clear()
void CMusicInfoTag::Clear ()
References CAlbum::Album, EmbeddedArtInfo::Clear(), m_albumArtist, m_albumReleaseType, m_artist, m_bBoxset, m_bCompilation, m_bitrate, m_bLoaded, m_channels, m_coverArt, m_cuesheet, m_dateAdded, m_dateNew, m_dateUpdated, m_genre, m_iAlbumId, m_iBPM, m_iDbId, m_iDiscTotal, m_iDuration, m_iTimesPlayed, m_iTrack, m_lastPlayed, m_listeners, m_musicBrainzAlbumArtistID, m_musicBrainzArtistID, m_musicRoles, m_Rating, m_replayGain, m_samplerate, m_songVideoURL, m_stationArt, m_stationName, m_strAlbum, m_strArtistSort, m_strComment, m_strComposerSort, m_strDiscSubtitle, m_strMood, m_strMusicBrainzAlbumID, m_strMusicBrainzReleaseGroupID, m_strMusicBrainzReleaseType, m_strMusicBrainzTrackID, m_strOriginalDate, m_strRecordLabel, m_strReleaseDate, m_strReleaseStatus, m_strTitle, m_strURL, m_type, m_Userrating, m_Votes, and CDateTime::Reset().
Referenced by CMusicInfoTag(), SetAlbum(), and SetSong().
GetAlbum()
const std::string & CMusicInfoTag::GetAlbum () const
References m_strAlbum.
Referenced by CMusicDatabase::AddAudioBook(), CAlbum::CAlbum(), XBMCAddon::xbmc::InfoTagMusic::getAlbum(), KODI::CDRIP::CCDDARipper::GetAlbumDirName(), CLabelFormatter::GetMaskContent(), CMusicDatabase::SetPropertiesForFileItem(), and KODI::CDRIP::CCDDARipJob::SetupEncoder().
GetAlbumArtist()
const std::vector< std::string > & CMusicInfoTag::GetAlbumArtist () const
References m_albumArtist.
Referenced by KODI::CDRIP::CCDDARipJob::SetupEncoder().
GetAlbumArtistSort()
const std::string & CMusicInfoTag::GetAlbumArtistSort () const
References m_strAlbumArtistSort.
GetAlbumArtistString()
const std::string CMusicInfoTag::GetAlbumArtistString () const
References CServiceBroker::GetSettingsComponent(), m_albumArtist, and m_strAlbumArtistDesc.
Referenced by XBMCAddon::xbmc::InfoTagMusic::getAlbumArtist(), KODI::CDRIP::CCDDARipper::GetAlbumDirName(), and Serialize().
GetAlbumId()
int CMusicInfoTag::GetAlbumId () const
References m_iAlbumId.
Referenced by CVideoThumbLoader::FillLibraryArt(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), and CMusicDatabase::SetPropertiesForFileItem().
GetAlbumReleaseStatus()
const std::string & CMusicInfoTag::GetAlbumReleaseStatus () const
References m_strReleaseStatus.
GetAlbumReleaseType()
CAlbum::ReleaseType CMusicInfoTag::GetAlbumReleaseType () const
References m_albumReleaseType.
GetArtist()
const std::vector< std::string > & CMusicInfoTag::GetArtist () const
References m_artist.
Referenced by CMusicDatabase::AddAudioBook(), and KODI::CDRIP::CCDDARipJob::SetupEncoder().
GetArtistSort()
const std::string & CMusicInfoTag::GetArtistSort () const
References m_strArtistSort.
Referenced by Serialize().
GetArtistString()
const std::string CMusicInfoTag::GetArtistString () const
References CServiceBroker::GetSettingsComponent(), m_artist, and m_strArtistDesc.
Referenced by KODI::CDRIP::CCDDARipJob::DoWork(), KODI::CDRIP::CCDDARipper::GetAlbumDirName(), XBMCAddon::xbmc::InfoTagMusic::getArtist(), CLabelFormatter::GetMaskContent(), Serialize(), and CMusicDatabase::SetPropertiesForFileItem().
GetArtistStringForRole()
const std::string CMusicInfoTag::GetArtistStringForRole (const std::string & strRole) const
References CServiceBroker::GetSettingsComponent(), and m_musicRoles.
Referenced by KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), and Serialize().
GetBitRate()
int CMusicInfoTag::GetBitRate () const
References m_bitrate.
GetBoxset()
bool CMusicInfoTag::GetBoxset () const
References m_bBoxset.
GetBPM()
int CMusicInfoTag::GetBPM () const
References m_iBPM.
Referenced by CLabelFormatter::GetMaskContent().
GetComment()
const std::string & CMusicInfoTag::GetComment () const
References m_strComment.
Referenced by XBMCAddon::xbmc::InfoTagMusic::getComment().
GetCompilation()
bool CMusicInfoTag::GetCompilation () const
References m_bCompilation.
GetComposerSort()
const std::string & CMusicInfoTag::GetComposerSort () const
References m_strComposerSort.
GetContributors()
const VECMUSICROLES & CMusicInfoTag::GetContributors () const
References m_musicRoles.
GetContributorsAndRolesText()
const std::string CMusicInfoTag::GetContributorsAndRolesText () const
References m_musicRoles.
GetContributorsText()
const std::string CMusicInfoTag::GetContributorsText () const
References m_musicRoles.
GetCoverArtInfo()
const EmbeddedArtInfo & CMusicInfoTag::GetCoverArtInfo () const
References m_coverArt.
Referenced by CMusicThumbLoader::LoadItemLookup().
GetCueSheet()
const std::string & CMusicInfoTag::GetCueSheet () const
References m_cuesheet.
GetDatabaseId()
int CMusicInfoTag::GetDatabaseId () const
References m_iDbId.
Referenced by CSaveFileState::DoWork(), XBMCAddon::xbmc::InfoTagMusic::getDbId(), CFileItem::IsSamePath(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), and CGUIDialogMusicInfo::ShowFor().
GetDateAdded()
const CDateTime & CMusicInfoTag::GetDateAdded () const
References m_dateAdded.
Referenced by CLabelFormatter::GetMaskContent().
GetDiscNumber()
int CMusicInfoTag::GetDiscNumber () const
References m_iTrack.
Referenced by XBMCAddon::xbmc::InfoTagMusic::getDisc(), CLabelFormatter::GetMaskContent(), and Serialize().
GetDiscSubtitle()
const std::string & CMusicInfoTag::GetDiscSubtitle () const
References m_strDiscSubtitle.
GetDuration()
int CMusicInfoTag::GetDuration () const
References m_iDuration.
Referenced by XBMCAddon::xbmc::InfoTagMusic::getDuration(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), CLabelFormatter::GetMaskContent(), and CGUIWindowMusicPlayList::OnItemLoaded().
GetGenre()
const std::vector< std::string > & CMusicInfoTag::GetGenre () const
References m_genre.
Referenced by KODI::CDRIP::CCDDARipper::GetAlbumDirName(), XBMCAddon::xbmc::InfoTagMusic::getGenre(), XBMCAddon::xbmc::InfoTagMusic::getGenres(), CLabelFormatter::GetMaskContent(), KODI::CDRIP::CCDDARipJob::SetupEncoder(), and TEST_F().
GetLastPlayed()
const CDateTime & CMusicInfoTag::GetLastPlayed () const
References m_lastPlayed.
Referenced by XBMCAddon::xbmc::InfoTagMusic::getLastPlayed(), XBMCAddon::xbmc::InfoTagMusic::getLastPlayedAsW3C(), and CLabelFormatter::GetMaskContent().
GetListeners()
int CMusicInfoTag::GetListeners () const
References m_listeners.
Referenced by XBMCAddon::xbmc::InfoTagMusic::getListeners(), and CLabelFormatter::GetMaskContent().
GetLyrics()
const std::string & CMusicInfoTag::GetLyrics () const
References m_strLyrics.
Referenced by XBMCAddon::xbmc::InfoTagMusic::getLyrics().
GetMood()
const std::string & CMusicInfoTag::GetMood () const
References m_strMood.
GetMusicBrainzAlbumArtistHints()
const std::vector< std::string > & CMusicInfoTag::GetMusicBrainzAlbumArtistHints () const
References m_musicBrainzAlbumArtistHints.
GetMusicBrainzAlbumArtistID()
const std::vector< std::string > & CMusicInfoTag::GetMusicBrainzAlbumArtistID () const
References m_musicBrainzAlbumArtistID.
Referenced by XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzAlbumArtistID().
GetMusicBrainzAlbumID()
const std::string & CMusicInfoTag::GetMusicBrainzAlbumID () const
References m_strMusicBrainzAlbumID.
Referenced by XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzAlbumID().
GetMusicBrainzArtistHints()
const std::vector< std::string > & CMusicInfoTag::GetMusicBrainzArtistHints () const
References m_musicBrainzArtistHints.
GetMusicBrainzArtistID()
const std::vector< std::string > & CMusicInfoTag::GetMusicBrainzArtistID () const
References m_musicBrainzArtistID.
Referenced by XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzArtistID().
GetMusicBrainzReleaseGroupID()
const std::string & MUSIC_INFO::CMusicInfoTag::GetMusicBrainzReleaseGroupID () const
Referenced by XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzReleaseGroupID().
GetMusicBrainzReleaseType()
const std::string & CMusicInfoTag::GetMusicBrainzReleaseType () const
References m_strMusicBrainzReleaseType.
GetMusicBrainzTrackID()
const std::string & CMusicInfoTag::GetMusicBrainzTrackID () const
References m_strMusicBrainzTrackID.
Referenced by XBMCAddon::xbmc::InfoTagMusic::getMusicBrainzTrackID().
GetNoOfChannels()
int CMusicInfoTag::GetNoOfChannels () const
References m_channels.
GetOriginalDate()
const std::string & CMusicInfoTag::GetOriginalDate () const
References m_strOriginalDate.
Referenced by CLabelFormatter::GetMaskContent().
GetOriginalYear()
const std::string MUSIC_INFO::CMusicInfoTag::GetOriginalYear () const
Referenced by GetYearString().
GetPlayCount()
int CMusicInfoTag::GetPlayCount () const
References m_iTimesPlayed.
Referenced by CLabelFormatter::GetMaskContent(), and XBMCAddon::xbmc::InfoTagMusic::getPlayCount().
GetRating()
float CMusicInfoTag::GetRating () const
References m_Rating.
Referenced by CLabelFormatter::GetMaskContent(), and XBMCAddon::xbmc::InfoTagMusic::getRating().
GetRecordLabel()
const std::string & CMusicInfoTag::GetRecordLabel () const
References m_strRecordLabel.
GetReleaseDate()
const std::string & CMusicInfoTag::GetReleaseDate () const
References m_strReleaseDate.
Referenced by XBMCAddon::xbmc::InfoTagMusic::getReleaseDate().
GetReleaseYear()
const std::string MUSIC_INFO::CMusicInfoTag::GetReleaseYear () const
Referenced by AddReleaseDate(), and GetYearString().
GetReplayGain()
const ReplayGain & CMusicInfoTag::GetReplayGain () const
References m_replayGain.
Referenced by CAudioDecoder::Create(), and CAudioDecoder::GetReplayGain().
GetSampleRate()
int CMusicInfoTag::GetSampleRate () const
References m_samplerate.
GetSongVideoURL()
const std::string & CMusicInfoTag::GetSongVideoURL () const
References m_songVideoURL.
Referenced by XBMCAddon::xbmc::InfoTagMusic::getSongVideoURL().
GetStationArt()
const std::string & CMusicInfoTag::GetStationArt () const
References m_stationArt.
Referenced by CFileItem::SetFromMusicInfoTag().
GetStationName()
const std::string & CMusicInfoTag::GetStationName () const
References m_stationName.
GetTitle()
const std::string & CMusicInfoTag::GetTitle () const
References m_strTitle.
Referenced by CFileItem::CFileItem(), CSong::CSong(), KODI::CDRIP::CCDDARipJob::DoWork(), CLabelFormatter::GetMaskContent(), XBMCAddon::xbmc::InfoTagMusic::getTitle(), CGUIVisualisationControl::Process(), CFileItem::SetFromMusicInfoTag(), KODI::CDRIP::CCDDARipJob::SetupEncoder(), and anonymous_namespace{MusicUtils.cpp}::ShowToastNotification().
GetTotalDiscs()
int CMusicInfoTag::GetTotalDiscs () const
References m_iDiscTotal.
Referenced by KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetBool(), and CLabelFormatter::GetMaskContent().
GetTrackAndDiscNumber()
int CMusicInfoTag::GetTrackAndDiscNumber () const
References m_iTrack.
GetTrackNumber()
int CMusicInfoTag::GetTrackNumber () const
References m_iTrack.
Referenced by CLabelFormatter::GetMaskContent(), XBMCAddon::xbmc::InfoTagMusic::getTrack(), CFileItem::LoadMusicTag(), and Serialize().
GetType()
const std::string & CMusicInfoTag::GetType () const
References m_type.
Referenced by CGUIDialogMusicInfo::AddItemPathToFileBrowserSources(), CSaveFileState::DoWork(), XBMCAddon::xbmc::InfoTagMusic::getMediaType(), CFileItem::IsSamePath(), CONTEXTMENU::CMusicInfo::IsVisible(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), CMusicThumbLoader::LoadItemCached(), CMusicThumbLoader::LoadItemLookup(), CGUIDialogMusicInfo::ShowFor(), and anonymous_namespace{MusicUtils.cpp}::ShowToastNotification().
GetURL()
const std::string & CMusicInfoTag::GetURL () const
References m_strURL.
Referenced by CGUIDialogMusicInfo::AddItemPathToFileBrowserSources(), CFileItem::CFileItem(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), CMime::GetMimeType(), UPNP::GetMimeType(), XBMCAddon::xbmc::InfoTagMusic::getURL(), CFileItem::IsSamePath(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), CExecString::Parse(), and CFileItem::SetFromMusicInfoTag().
GetUserrating()
int CMusicInfoTag::GetUserrating () const
References m_Userrating.
Referenced by CLabelFormatter::GetMaskContent(), and XBMCAddon::xbmc::InfoTagMusic::getUserRating().
GetVotes()
int CMusicInfoTag::GetVotes () const
References m_Votes.
GetYear()
int CMusicInfoTag::GetYear () const
References GetYearString().
Referenced by XBMCAddon::xbmc::InfoTagMusic::getYear(), Serialize(), and ToSortable().
GetYearString()
std::string CMusicInfoTag::GetYearString () const
References GetOriginalYear(), GetReleaseYear(), CServiceBroker::GetSettingsComponent(), CSettings::SETTING_MUSICLIBRARY_USEORIGINALDATE, and value.
Referenced by KODI::CDRIP::CCDDARipper::GetAlbumDirName(), CLabelFormatter::GetMaskContent(), GetYear(), and KODI::CDRIP::CCDDARipJob::SetupEncoder().
HasContributors()
bool MUSIC_INFO::CMusicInfoTag::HasContributors () const inline
References m_musicRoles.
Loaded()
bool CMusicInfoTag::Loaded () const
References m_bLoaded.
Referenced by XFILE::CMusicFileDirectory::GetDirectory(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), CFileItem::LoadMusicTag(), and CGUIWindowMusicPlayList::OnItemLoaded().
operator!=()
bool CMusicInfoTag::operator!= (const CMusicInfoTag & tag) const
References m_albumArtist, m_albumReleaseType, m_artist, m_bCompilation, m_iDuration, m_iTrack, m_strAlbum, m_strDiscSubtitle, m_strTitle, and m_strURL.
Serialize()
void CMusicInfoTag::Serialize (CVariant & ar) const override virtual
Implements ISerializable.
References GetAlbumArtistString(), GetArtistSort(), GetArtistString(), GetArtistStringForRole(), CDateTime::GetAsDBDateTime(), GetDiscNumber(), CServiceBroker::GetSettingsComponent(), GetTrackNumber(), GetYear(), CDateTime::IsValid(), m_albumArtist, m_albumReleaseType, m_artist, m_bBoxset, m_bCompilation, m_bitrate, m_bLoaded, m_channels, m_dateAdded, m_dateNew, m_dateUpdated, m_genre, m_iAlbumId, m_iBPM, m_iDiscTotal, m_iDuration, m_iTimesPlayed, m_lastPlayed, m_musicBrainzAlbumArtistID, m_musicBrainzArtistID, m_musicRoles, m_Rating, m_samplerate, m_songVideoURL, m_strAlbum, m_strAlbumArtistSort, m_strComment, m_strDiscSubtitle, m_strLyrics, m_strMood, m_strMusicBrainzAlbumID, m_strMusicBrainzReleaseGroupID, m_strMusicBrainzTrackID, m_strOriginalDate, m_strRecordLabel, m_strReleaseDate, m_strReleaseStatus, m_strTitle, m_strURL, m_type, m_Userrating, m_Votes, MediaTypeAlbum, MediaTypeArtist, MediaTypeSong, CVariant::push_back(), CAlbum::ReleaseTypeToString(), value, and CVariant::VariantTypeArray.
SetAlbum() [1/2]
void CMusicInfoTag::SetAlbum (const CAlbum & album)
References CAlbum::bBoxedSet, CAlbum::bCompilation, Clear(), CAlbum::dateAdded, CAlbum::dateNew, CAlbum::dateUpdated, CAlbum::fRating, CAlbum::genre, CAlbum::GetAlbumArtist(), CAlbum::GetAlbumArtistSort(), CAlbum::GetAlbumArtistString(), CAlbum::GetMusicBrainzAlbumArtistID(), CServiceBroker::GetSettingsComponent(), CAlbum::iAlbumDuration, CAlbum::idAlbum, CAlbum::iTimesPlayed, CAlbum::iTotalDiscs, CAlbum::iUserrating, CAlbum::iVotes, CAlbum::lastPlayed, MediaTypeAlbum, CAlbum::moods, CAlbum::releaseType, SetAlbum(), SetAlbumArtist(), SetAlbumArtistDesc(), SetAlbumArtistSort(), SetAlbumId(), SetAlbumReleaseStatus(), SetAlbumReleaseType(), SetArtist(), SetArtistDesc(), SetArtistSort(), SetBoxset(), SetCompilation(), SetDatabaseId(), SetDateAdded(), SetDateNew(), SetDateUpdated(), SetDuration(), SetGenre(), SetLastPlayed(), SetLoaded(), SetMood(), SetMusicBrainzAlbumArtistID(), SetMusicBrainzAlbumID(), SetMusicBrainzArtistID(), SetMusicBrainzReleaseGroupID(), SetMusicBrainzReleaseType(), SetOriginalDate(), SetPlayCount(), SetRating(), SetRecordLabel(), SetReleaseDate(), SetTitle(), SetTotalDiscs(), SetUserrating(), SetVotes(), CAlbum::strAlbum, CAlbum::strLabel, CAlbum::strMusicBrainzAlbumID, CAlbum::strOrigReleaseDate, CAlbum::strReleaseDate, CAlbum::strReleaseGroupMBID, CAlbum::strReleaseStatus, and CAlbum::strType.
SetAlbum() [2/2]
void CMusicInfoTag::SetAlbum (const std::string & strAlbum)
References m_strAlbum, and Trim().
Referenced by CDVDRadioRDSData::DecodeRTPlus(), CMusicDatabase::GetFileItemFromDataset(), CVideoPlayerAudioID3::ProcessID3v1(), CVideoPlayerAudioID3::ProcessID3v2(), CAirTunesServer::RefreshMetadata(), SetAlbum(), XBMCAddon::xbmc::InfoTagMusic::setAlbumRaw(), CFileItem::SetFromAlbum(), SetSong(), and TEST().
SetAlbumArtist() [1/2]
void CMusicInfoTag::SetAlbumArtist (const std::string & strAlbumArtist)
References CServiceBroker::GetSettingsComponent(), m_albumArtist, m_strAlbumArtistDesc, SetAlbumArtist(), and SetAlbumArtistDesc().
Referenced by CMusicDatabase::GetArtistsByAlbum(), CMusicDatabase::GetFileItemFromDataset(), SetAlbum(), SetAlbumArtist(), XBMCAddon::xbmc::InfoTagMusic::setAlbumArtistRaw(), SetArtist(), and SetSong().
SetAlbumArtist() [2/2]
void CMusicInfoTag::SetAlbumArtist (const std::vector< std::string > & albumArtists, bool FillDesc = false)
References CServiceBroker::GetSettingsComponent(), m_albumArtist, m_strAlbumArtistDesc, and SetAlbumArtistDesc().
SetAlbumArtistDesc()
void CMusicInfoTag::SetAlbumArtistDesc (const std::string & strAlbumArtistDesc)
References m_strAlbumArtistDesc.
Referenced by SetAlbum(), SetAlbumArtist(), and SetAlbumArtist().
SetAlbumArtistSort()
void CMusicInfoTag::SetAlbumArtistSort (const std::string & strAlbumArtistSort)
References m_strAlbumArtistSort.
Referenced by SetAlbum(), SetArtist(), and SetSong().
SetAlbumId()
void CMusicInfoTag::SetAlbumId (const int iAlbumId)
References m_iAlbumId.
Referenced by CDVDRadioRDSData::DecodeRTPlus(), CMusicDatabase::GetFileItemFromDataset(), JSONRPC::CAudioLibrary::GetSongs(), SetAlbum(), and SetSong().
SetAlbumReleaseStatus()
void CMusicInfoTag::SetAlbumReleaseStatus (const std::string & strReleaseStatus)
References m_strReleaseStatus.
Referenced by SetAlbum().
SetAlbumReleaseType()
void CMusicInfoTag::SetAlbumReleaseType (CAlbum::ReleaseType releaseType)
References m_albumReleaseType.
Referenced by CMusicDatabase::GetFileItemFromDataset(), and SetAlbum().
SetArtist() [1/3]
void CMusicInfoTag::SetArtist (const CArtist & artist)
References CArtist::dateAdded, CArtist::dateNew, CArtist::dateUpdated, CArtist::genre, CServiceBroker::GetSettingsComponent(), CArtist::idArtist, MediaTypeArtist, CArtist::moods, SetAlbumArtist(), SetAlbumArtistSort(), SetArtist(), SetArtistSort(), SetDatabaseId(), SetDateAdded(), SetDateNew(), SetDateUpdated(), SetGenre(), SetLoaded(), SetMood(), SetMusicBrainzAlbumArtistID(), SetMusicBrainzArtistID(), CArtist::strArtist, CArtist::strMusicBrainzArtistID, and CArtist::strSortName.
SetArtist() [2/3]
void CMusicInfoTag::SetArtist (const std::string & strArtist)
References CServiceBroker::GetSettingsComponent(), m_artist, m_strArtistDesc, SetArtist(), and SetArtistDesc().
Referenced by CFileItem::CFileItem(), CDVDRadioRDSData::DecodeRTPlus(), CMusicDatabase::GetFileItemFromArtistCredits(), CVideoPlayerAudioID3::ProcessID3v1(), CVideoPlayerAudioID3::ProcessID3v2(), SetAlbum(), SetArtist(), SetArtist(), XBMCAddon::xbmc::InfoTagMusic::setArtistRaw(), and SetSong().
SetArtist() [3/3]
void CMusicInfoTag::SetArtist (const std::vector< std::string > & artists, bool FillDesc = false)
References CServiceBroker::GetSettingsComponent(), m_artist, m_strArtistDesc, and SetArtistDesc().
SetArtistDesc()
void CMusicInfoTag::SetArtistDesc (const std::string & strArtistDesc)
References m_strArtistDesc.
Referenced by CMusicDatabase::GetFileItemFromDataset(), SetAlbum(), SetArtist(), SetArtist(), and SetSong().
SetArtistSort()
void CMusicInfoTag::SetArtistSort (const std::string & strArtistsort)
References m_strArtistSort.
Referenced by CMusicDatabase::GetFileItemFromDataset(), SetAlbum(), SetArtist(), and SetSong().
SetBitRate()
void CMusicInfoTag::SetBitRate (int bitrate)
References m_bitrate.
Referenced by CMusicDatabase::GetFileItemFromDataset(), and SetSong().
SetBoxset()
void CMusicInfoTag::SetBoxset (bool boxset)
References m_bBoxset.
Referenced by CMusicDatabase::GetFileItemFromDataset(), and SetAlbum().
SetBPM()
void CMusicInfoTag::SetBPM (int iBPM)
References m_iBPM.
Referenced by CMusicDatabase::GetFileItemFromDataset(), and SetSong().
SetComment()
void CMusicInfoTag::SetComment (const std::string & comment)
References m_strComment.
Referenced by CMusicDatabase::GetFileItemFromDataset(), CVideoPlayerAudioID3::ProcessID3v1(), CVideoPlayerAudioID3::ProcessID3v2(), XBMCAddon::xbmc::InfoTagMusic::setCommentRaw(), and SetSong().
SetCompilation()
void CMusicInfoTag::SetCompilation (bool compilation)
References m_bCompilation.
Referenced by CMusicDatabase::GetFileItemFromDataset(), SetAlbum(), and SetSong().
SetComposerSort()
void CMusicInfoTag::SetComposerSort (const std::string & strComposerSort)
References m_strComposerSort.
SetContributors()
void CMusicInfoTag::SetContributors (const VECMUSICROLES & contributors)
References m_musicRoles.
Referenced by SetSong().
SetCoverArtInfo()
void CMusicInfoTag::SetCoverArtInfo (size_t size, const std::string & mimeType)
References m_coverArt, and EmbeddedArtInfo::Set().
Referenced by SetSong().
SetCueSheet()
void CMusicInfoTag::SetCueSheet (const std::string & cueSheet)
References m_cuesheet.
Referenced by SetSong().
SetDatabaseId()
void CMusicInfoTag::SetDatabaseId (int id, const std::string & type)
References id, m_iDbId, and m_type.
Referenced by JSONRPC::CAudioLibrary::GetAlbums(), CMusicDatabase::GetFileItemFromDataset(), JSONRPC::CAudioLibrary::GetSongs(), SetAlbum(), SetArtist(), XBMCAddon::xbmc::InfoTagMusic::setDbIdRaw(), SetSong(), and CGUIDialogMusicInfo::ShowFor().
SetDateAdded() [1/2]
void CMusicInfoTag::SetDateAdded (const CDateTime & dateAdded)
References m_dateAdded.
SetDateAdded() [2/2]
void CMusicInfoTag::SetDateAdded (const std::string & strDateAdded)
References m_dateAdded, and CDateTime::SetFromDBDateTime().
Referenced by CMusicDatabase::GetFileItemFromDataset(), SetAlbum(), SetArtist(), and SetSong().
SetDateNew() [1/2]
void MUSIC_INFO::CMusicInfoTag::SetDateNew (const CDateTime & dateNew)
SetDateNew() [2/2]
void MUSIC_INFO::CMusicInfoTag::SetDateNew (const std::string & strDateNew)
References CDateTime::SetFromDBDateTime().
Referenced by CMusicDatabase::GetFileItemFromDataset(), SetAlbum(), SetArtist(), and SetSong().
SetDateUpdated() [1/2]
void MUSIC_INFO::CMusicInfoTag::SetDateUpdated (const CDateTime & dateUpdated)
SetDateUpdated() [2/2]
void MUSIC_INFO::CMusicInfoTag::SetDateUpdated (const std::string & strDateUpdated)
References CDateTime::SetFromDBDateTime().
Referenced by CMusicDatabase::GetFileItemFromDataset(), SetAlbum(), SetArtist(), and SetSong().
SetDiscNumber()
void CMusicInfoTag::SetDiscNumber (int iDiscNumber)
References m_iTrack.
Referenced by XBMCAddon::xbmc::InfoTagMusic::setDiscRaw().
SetDiscSubtitle()
void CMusicInfoTag::SetDiscSubtitle (const std::string & strDiscSubtitle)
References m_strDiscSubtitle.
Referenced by CMusicDatabase::GetFileItemFromDataset(), and SetSong().
SetDuration()
void CMusicInfoTag::SetDuration (int iSec)
References m_iDuration.
Referenced by CFileItem::FillMusicInfoTag(), CMusicDatabase::GetFileItemFromDataset(), SetAlbum(), XBMCAddon::xbmc::InfoTagMusic::setDurationRaw(), and SetSong().
SetGenre() [1/2]
void CMusicInfoTag::SetGenre (const std::string & strGenre, bool bTrim = false)
References CServiceBroker::GetSettingsComponent(), m_genre, and SetGenre().
Referenced by CFileItem::CFileItem(), CFileItem::FillMusicInfoTag(), CMusicDatabase::GetFileItemFromDataset(), CVideoPlayerAudioID3::ProcessID3v1(), CVideoPlayerAudioID3::ProcessID3v2(), SetAlbum(), SetArtist(), SetGenre(), XBMCAddon::xbmc::InfoTagMusic::setGenresRaw(), and SetSong().
SetGenre() [2/2]
void CMusicInfoTag::SetGenre (const std::vector< std::string > & genres, bool bTrim = false)
References m_genre.
SetLastPlayed() [1/2]
void CMusicInfoTag::SetLastPlayed (const CDateTime & strLastPlayed)
References m_lastPlayed.
SetLastPlayed() [2/2]
void CMusicInfoTag::SetLastPlayed (const std::string & strLastPlayed)
References m_lastPlayed, and CDateTime::SetFromDBDateTime().
Referenced by CMusicDatabase::GetFileItemFromDataset(), SetAlbum(), XBMCAddon::xbmc::InfoTagMusic::setLastPlayedRaw(), and SetSong().
SetListeners()
void CMusicInfoTag::SetListeners (int listeners)
References m_listeners.
Referenced by XBMCAddon::xbmc::InfoTagMusic::setListenersRaw().
SetLoaded()
void CMusicInfoTag::SetLoaded (bool bOnOff = true)
References m_bLoaded.
Referenced by CFileItem::FillMusicInfoTag(), CMusicDatabase::GetFileItemFromDataset(), KODI::ADDONS::CAudioDecoder::GetTrackCount(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::InitCurrentItem(), CFileItem::LoadMusicTag(), SetAlbum(), SetArtist(), and SetSong().
SetLyrics()
void CMusicInfoTag::SetLyrics (const std::string & lyrics)
References m_strLyrics.
Referenced by MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), and XBMCAddon::xbmc::InfoTagMusic::setLyricsRaw().
SetMood()
void CMusicInfoTag::SetMood (const std::string & mood)
References m_strMood.
Referenced by CMusicDatabase::GetFileItemFromDataset(), SetAlbum(), SetArtist(), and SetSong().
SetMusicBrainzAlbumArtistHints()
void CMusicInfoTag::SetMusicBrainzAlbumArtistHints (const std::vector< std::string > & musicBrainzAlbumArtistHints)
References m_musicBrainzAlbumArtistHints.
SetMusicBrainzAlbumArtistID()
void CMusicInfoTag::SetMusicBrainzAlbumArtistID (const std::vector< std::string > & musicBrainzAlbumArtistId)
References m_musicBrainzAlbumArtistID.
Referenced by CMusicDatabase::GetArtistsByAlbum(), SetAlbum(), SetArtist(), and XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumArtistIDRaw().
SetMusicBrainzAlbumID()
void CMusicInfoTag::SetMusicBrainzAlbumID (const std::string & strAlbumID)
References m_strMusicBrainzAlbumID.
Referenced by SetAlbum(), and XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzAlbumIDRaw().
SetMusicBrainzArtistHints()
void CMusicInfoTag::SetMusicBrainzArtistHints (const std::vector< std::string > & musicBrainzArtistHints)
References m_musicBrainzArtistHints.
SetMusicBrainzArtistID()
void CMusicInfoTag::SetMusicBrainzArtistID (const std::vector< std::string > & musicBrainzArtistId)
References m_musicBrainzArtistID.
Referenced by CMusicDatabase::GetFileItemFromArtistCredits(), SetAlbum(), SetArtist(), XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzArtistIDRaw(), and SetSong().
SetMusicBrainzReleaseGroupID()
void MUSIC_INFO::CMusicInfoTag::SetMusicBrainzReleaseGroupID (const std::string & strReleaseGroupID)
Referenced by SetAlbum(), and XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzReleaseGroupIDRaw().
SetMusicBrainzReleaseType()
void CMusicInfoTag::SetMusicBrainzReleaseType (const std::string & ReleaseType)
References m_strMusicBrainzReleaseType.
Referenced by SetAlbum().
SetMusicBrainzTrackID()
void CMusicInfoTag::SetMusicBrainzTrackID (const std::string & strTrackID)
References m_strMusicBrainzTrackID.
Referenced by CMusicDatabase::GetFileItemFromDataset(), XBMCAddon::xbmc::InfoTagMusic::setMusicBrainzTrackIDRaw(), and SetSong().
SetNoOfChannels()
void CMusicInfoTag::SetNoOfChannels (int channels)
References m_channels.
Referenced by CMusicDatabase::GetFileItemFromDataset(), and SetSong().
SetOriginalDate()
void CMusicInfoTag::SetOriginalDate (const std::string & strOriginalDate)
References m_strOriginalDate.
Referenced by CMusicDatabase::GetFileItemFromDataset(), SetAlbum(), and SetSong().
SetPlayCount()
void CMusicInfoTag::SetPlayCount (int playcount)
References m_iTimesPlayed.
Referenced by AudioClassifyTest::AudioClassifyTest(), CMusicDatabase::GetFileItemFromDataset(), SetAlbum(), XBMCAddon::xbmc::InfoTagMusic::setPlayCountRaw(), SetSong(), and VideoClassifyTest::VideoClassifyTest().
SetRating()
void CMusicInfoTag::SetRating (float rating)
References m_Rating.
Referenced by CMusicDatabase::GetFileItemFromDataset(), SetAlbum(), XBMCAddon::xbmc::InfoTagMusic::setRatingRaw(), and SetSong().
SetRecordLabel()
void CMusicInfoTag::SetRecordLabel (const std::string & publisher)
References m_strRecordLabel.
Referenced by SetAlbum().
SetReleaseDate()
void CMusicInfoTag::SetReleaseDate (const std::string & strReleaseDate)
References m_strReleaseDate.
Referenced by CMusicDatabase::GetFileItemFromDataset(), SetAlbum(), XBMCAddon::xbmc::InfoTagMusic::setReleaseDateRaw(), SetSong(), and SetYear().
SetReplayGain()
void CMusicInfoTag::SetReplayGain (const ReplayGain & aGain)
References m_replayGain.
Referenced by CAudioDecoder::Create(), and CMusicDatabase::GetFileItemFromDataset().
SetSampleRate()
void CMusicInfoTag::SetSampleRate (int samplerate)
References m_samplerate.
Referenced by CMusicDatabase::GetFileItemFromDataset(), and SetSong().
SetSong()
void CMusicInfoTag::SetSong (const CSong & song)
References ReplayGain::ALBUM, CSong::bCompilation, Clear(), CSong::dateAdded, CSong::dateNew, CSong::dateUpdated, CSong::embeddedArt, CSong::genre, ReplayGain::Get(), CSong::GetAlbumArtist(), CSong::GetAlbumArtistSort(), CSong::GetArtist(), CSong::GetArtistSort(), CSong::GetArtistString(), CSong::GetContributors(), CSong::GetMusicBrainzArtistID(), CSong::HasArtistCredits(), CSong::iBitRate, CSong::iBPM, CSong::iChannels, CSong::idAlbum, CSong::idSong, CSong::iDuration, CSong::iSampleRate, CSong::iTimesPlayed, CSong::iTrack, CSong::lastPlayed, EmbeddedArtInfo::m_mime, m_replayGain, EmbeddedArtInfo::m_size, MediaTypeSong, CSong::rating, CSong::replayGain, ReplayGain::Set(), SetAlbum(), SetAlbumArtist(), SetAlbumArtistSort(), SetAlbumId(), SetArtist(), SetArtistDesc(), SetArtistSort(), SetBitRate(), SetBPM(), SetComment(), SetCompilation(), SetContributors(), SetCoverArtInfo(), SetCueSheet(), SetDatabaseId(), SetDateAdded(), SetDateNew(), SetDateUpdated(), SetDiscSubtitle(), SetDuration(), SetGenre(), SetLastPlayed(), SetLoaded(), SetMood(), SetMusicBrainzArtistID(), SetMusicBrainzTrackID(), SetNoOfChannels(), SetOriginalDate(), SetPlayCount(), SetRating(), SetReleaseDate(), SetSampleRate(), SetSongVideoURL(), SetTitle(), SetTrackAndDiscNumber(), SetURL(), SetUserrating(), SetVotes(), CSong::songVideoURL, CSong::strAlbum, CSong::strComment, CSong::strCueSheet, CSong::strDiscSubtitle, CSong::strFileName, CSong::strMood, CSong::strMusicBrainzTrackID, CSong::strOrigReleaseDate, CSong::strReleaseDate, CSong::strTitle, ReplayGain::TRACK, CSong::userrating, ReplayGain::Info::Valid(), and CSong::votes.
Referenced by MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), CFileItem::LoadMusicTag(), and CFileItem::SetFromSong().
SetSongVideoURL()
void CMusicInfoTag::SetSongVideoURL (const std::string & songVideoURL)
References m_songVideoURL.
Referenced by CMusicDatabase::GetFileItemFromDataset(), SetSong(), and XBMCAddon::xbmc::InfoTagMusic::setSongVideoURLRaw().
SetStationArt()
void CMusicInfoTag::SetStationArt (const std::string & strStationArt)
References m_stationArt.
SetStationName()
void CMusicInfoTag::SetStationName (const std::string & strStationName)
References m_stationName.
SetTitle()
void CMusicInfoTag::SetTitle (const std::string & strTitle)
References m_strTitle, and Trim().
Referenced by CDVDRadioRDSData::DecodeRTPlus(), CFileItem::FillMusicInfoTag(), CMusicDatabase::GetFileItemFromDataset(), KODI::ADDONS::CAudioDecoder::GetTrackCount(), CFileItem::LoadMusicTag(), CVideoPlayerAudioID3::ProcessID3v1(), CVideoPlayerAudioID3::ProcessID3v2(), SetAlbum(), SetSong(), and XBMCAddon::xbmc::InfoTagMusic::setTitleRaw().
SetTotalDiscs()
void CMusicInfoTag::SetTotalDiscs (int iDiscTotal)
References m_iDiscTotal.
Referenced by CMusicDatabase::GetFileItemFromDataset(), and SetAlbum().
SetTrackAndDiscNumber()
void CMusicInfoTag::SetTrackAndDiscNumber (int iTrackAndDisc)
References m_iTrack.
Referenced by CMusicDatabase::GetFileItemFromDataset(), and SetSong().
SetTrackNumber()
void CMusicInfoTag::SetTrackNumber (int iTrack)
References m_iTrack.
Referenced by XFILE::CMusicFileDirectory::GetDirectory(), CVideoPlayerAudioID3::ProcessID3v1(), CVideoPlayerAudioID3::ProcessID3v2(), and XBMCAddon::xbmc::InfoTagMusic::setTrackRaw().
SetType()
void CMusicInfoTag::SetType (const MediaType & mediaType)
References m_type.
Referenced by XBMCAddon::xbmc::InfoTagMusic::setMediaTypeRaw().
SetURL()
void CMusicInfoTag::SetURL (const std::string & strURL)
References m_strURL.
Referenced by CFileItem::FillMusicInfoTag(), CMusicDatabase::GetFileItemFromDataset(), SetSong(), and XBMCAddon::xbmc::InfoTagMusic::setURLRaw().
SetUserrating()
void CMusicInfoTag::SetUserrating (int rating)
References m_Userrating.
Referenced by CMusicDatabase::GetFileItemFromDataset(), SetAlbum(), SetSong(), and XBMCAddon::xbmc::InfoTagMusic::setUserRatingRaw().
SetVotes()
void CMusicInfoTag::SetVotes (int votes)
References m_Votes.
Referenced by CMusicDatabase::GetFileItemFromDataset(), SetAlbum(), and SetSong().
SetYear()
void CMusicInfoTag::SetYear (int year)
References m_strReleaseDate, and SetReleaseDate().
Referenced by CVideoPlayerAudioID3::ProcessID3v1(), CVideoPlayerAudioID3::ProcessID3v2(), and XBMCAddon::xbmc::InfoTagMusic::setYearRaw().
ToSortable()
void CMusicInfoTag::ToSortable (SortItem & sortable, Field field) const override virtual
Implements ISortable.
References FieldAlbum, FieldAlbumArtist, FieldArtist, FieldArtistSort, FieldBPM, FieldComment, FieldDateAdded, FieldGenre, FieldId, FieldLastPlayed, FieldListeners, FieldMoods, FieldOrigDate, FieldPlaycount, FieldRating, FieldTime, FieldTitle, FieldTotalDiscs, FieldTrackNumber, FieldUserRating, FieldVotes, FieldYear, CDateTime::GetAsDBDateTime(), GetYear(), int64_t(), CDateTime::IsValid(), m_dateAdded, m_genre, m_iBPM, m_iDbId, m_iDiscTotal, m_iDuration, m_iTimesPlayed, m_iTrack, m_lastPlayed, m_listeners, m_Rating, m_strAlbum, m_strAlbumArtistDesc, m_strArtistDesc, m_strArtistSort, m_strComment, m_strMood, m_strOriginalDate, m_strTitle, m_Userrating, and m_Votes.
Referenced by CFileItem::ToSortable().
Trim()
std::string CMusicInfoTag::Trim (const std::string & value) const protected
Trim whitespace off the given string.
Parameters
value string to trim
Returns
trimmed value, with spaces removed from left and right, as well as carriage returns from the right.
References value.
Referenced by AddArtistRole(), SetAlbum(), and SetTitle().
Member Data Documentation
m_albumArtist
std::vector<std::string> MUSIC_INFO::CMusicInfoTag::m_albumArtist protected
Referenced by AppendAlbumArtist(), Archive(), Clear(), GetAlbumArtist(), GetAlbumArtistString(), operator!=(), Serialize(), SetAlbumArtist(), and SetAlbumArtist().
m_albumReleaseType
CAlbum::ReleaseType MUSIC_INFO::CMusicInfoTag::m_albumReleaseType protected
Referenced by Archive(), Clear(), GetAlbumReleaseType(), operator!=(), Serialize(), and SetAlbumReleaseType().
m_artist
std::vector<std::string> MUSIC_INFO::CMusicInfoTag::m_artist protected
Referenced by AppendArtist(), Archive(), Clear(), GetArtist(), GetArtistString(), operator!=(), Serialize(), SetArtist(), and SetArtist().
m_bBoxset
bool MUSIC_INFO::CMusicInfoTag::m_bBoxset protected
Referenced by Archive(), Clear(), GetBoxset(), Serialize(), and SetBoxset().
m_bCompilation
bool MUSIC_INFO::CMusicInfoTag::m_bCompilation protected
Referenced by Archive(), Clear(), GetCompilation(), operator!=(), Serialize(), and SetCompilation().
m_bitrate
int MUSIC_INFO::CMusicInfoTag::m_bitrate protected
Referenced by Archive(), Clear(), GetBitRate(), Serialize(), and SetBitRate().
m_bLoaded
bool MUSIC_INFO::CMusicInfoTag::m_bLoaded protected
Referenced by Archive(), Clear(), Loaded(), Serialize(), and SetLoaded().
m_channels
int MUSIC_INFO::CMusicInfoTag::m_channels protected
Referenced by Archive(), Clear(), GetNoOfChannels(), Serialize(), and SetNoOfChannels().
m_coverArt
EmbeddedArtInfo MUSIC_INFO::CMusicInfoTag::m_coverArt protected
art information
Referenced by Archive(), Clear(), GetCoverArtInfo(), and SetCoverArtInfo().
m_cuesheet
std::string MUSIC_INFO::CMusicInfoTag::m_cuesheet protected
Referenced by Archive(), Clear(), GetCueSheet(), and SetCueSheet().
m_dateAdded
CDateTime MUSIC_INFO::CMusicInfoTag::m_dateAdded protected
Referenced by Archive(), Clear(), GetDateAdded(), Serialize(), SetDateAdded(), SetDateAdded(), and ToSortable().
m_dateNew
CDateTime MUSIC_INFO::CMusicInfoTag::m_dateNew protected
Referenced by Clear(), and Serialize().
m_dateUpdated
CDateTime MUSIC_INFO::CMusicInfoTag::m_dateUpdated protected
Referenced by Clear(), and Serialize().
m_genre
std::vector<std::string> MUSIC_INFO::CMusicInfoTag::m_genre protected
Referenced by AppendGenre(), Archive(), Clear(), GetGenre(), Serialize(), SetGenre(), SetGenre(), and ToSortable().
m_iAlbumId
int MUSIC_INFO::CMusicInfoTag::m_iAlbumId protected
Referenced by Archive(), Clear(), GetAlbumId(), Serialize(), and SetAlbumId().
m_iBPM
int MUSIC_INFO::CMusicInfoTag::m_iBPM protected
Referenced by Archive(), Clear(), GetBPM(), Serialize(), SetBPM(), and ToSortable().
m_iDbId
int MUSIC_INFO::CMusicInfoTag::m_iDbId protected
Referenced by Archive(), Clear(), GetDatabaseId(), SetDatabaseId(), and ToSortable().
m_iDiscTotal
int MUSIC_INFO::CMusicInfoTag::m_iDiscTotal protected
Referenced by Archive(), Clear(), GetTotalDiscs(), Serialize(), SetTotalDiscs(), and ToSortable().
m_iDuration
int MUSIC_INFO::CMusicInfoTag::m_iDuration protected
Referenced by Archive(), Clear(), GetDuration(), operator!=(), Serialize(), SetDuration(), and ToSortable().
m_iTimesPlayed
int MUSIC_INFO::CMusicInfoTag::m_iTimesPlayed protected
Referenced by Archive(), Clear(), GetPlayCount(), Serialize(), SetPlayCount(), and ToSortable().
m_iTrack
int MUSIC_INFO::CMusicInfoTag::m_iTrack protected
Referenced by Archive(), Clear(), GetDiscNumber(), GetTrackAndDiscNumber(), GetTrackNumber(), operator!=(), SetDiscNumber(), SetTrackAndDiscNumber(), SetTrackNumber(), and ToSortable().
m_lastPlayed
CDateTime MUSIC_INFO::CMusicInfoTag::m_lastPlayed protected
Referenced by Archive(), Clear(), GetLastPlayed(), Serialize(), SetLastPlayed(), SetLastPlayed(), and ToSortable().
m_listeners
int MUSIC_INFO::CMusicInfoTag::m_listeners protected
Referenced by Archive(), Clear(), GetListeners(), SetListeners(), and ToSortable().
m_musicBrainzAlbumArtistHints
std::vector<std::string> MUSIC_INFO::CMusicInfoTag::m_musicBrainzAlbumArtistHints protected
Referenced by GetMusicBrainzAlbumArtistHints(), and SetMusicBrainzAlbumArtistHints().
m_musicBrainzAlbumArtistID
std::vector<std::string> MUSIC_INFO::CMusicInfoTag::m_musicBrainzAlbumArtistID protected
Referenced by Archive(), Clear(), GetMusicBrainzAlbumArtistID(), Serialize(), and SetMusicBrainzAlbumArtistID().
m_musicBrainzArtistHints
std::vector<std::string> MUSIC_INFO::CMusicInfoTag::m_musicBrainzArtistHints protected
Referenced by GetMusicBrainzArtistHints(), and SetMusicBrainzArtistHints().
m_musicBrainzArtistID
std::vector<std::string> MUSIC_INFO::CMusicInfoTag::m_musicBrainzArtistID protected
Referenced by Archive(), Clear(), GetMusicBrainzArtistID(), Serialize(), and SetMusicBrainzArtistID().
m_musicRoles
VECMUSICROLES MUSIC_INFO::CMusicInfoTag::m_musicRoles protected
Referenced by AddArtistRole(), AppendArtistRole(), Archive(), Clear(), GetArtistStringForRole(), GetContributors(), GetContributorsAndRolesText(), GetContributorsText(), HasContributors(), Serialize(), and SetContributors().
m_Rating
float MUSIC_INFO::CMusicInfoTag::m_Rating protected
Referenced by Archive(), Clear(), GetRating(), Serialize(), SetRating(), and ToSortable().
m_replayGain
ReplayGain MUSIC_INFO::CMusicInfoTag::m_replayGain protected
ReplayGain information.
Referenced by Clear(), GetReplayGain(), SetReplayGain(), and SetSong().
m_samplerate
int MUSIC_INFO::CMusicInfoTag::m_samplerate protected
Referenced by Archive(), Clear(), GetSampleRate(), Serialize(), and SetSampleRate().
m_songVideoURL
std::string MUSIC_INFO::CMusicInfoTag::m_songVideoURL protected
Referenced by Archive(), Clear(), GetSongVideoURL(), Serialize(), and SetSongVideoURL().
m_stationArt
std::string MUSIC_INFO::CMusicInfoTag::m_stationArt protected
Referenced by Clear(), GetStationArt(), and SetStationArt().
m_stationName
std::string MUSIC_INFO::CMusicInfoTag::m_stationName protected
Referenced by Clear(), GetStationName(), and SetStationName().
m_strAlbum
std::string MUSIC_INFO::CMusicInfoTag::m_strAlbum protected
Referenced by Archive(), Clear(), GetAlbum(), operator!=(), Serialize(), SetAlbum(), and ToSortable().
m_strAlbumArtistDesc
std::string MUSIC_INFO::CMusicInfoTag::m_strAlbumArtistDesc protected
Referenced by Archive(), GetAlbumArtistString(), SetAlbumArtist(), SetAlbumArtist(), SetAlbumArtistDesc(), and ToSortable().
m_strAlbumArtistSort
std::string MUSIC_INFO::CMusicInfoTag::m_strAlbumArtistSort protected
Referenced by GetAlbumArtistSort(), Serialize(), and SetAlbumArtistSort().
m_strArtistDesc
std::string MUSIC_INFO::CMusicInfoTag::m_strArtistDesc protected
Referenced by Archive(), GetArtistString(), SetArtist(), SetArtist(), SetArtistDesc(), and ToSortable().
m_strArtistSort
std::string MUSIC_INFO::CMusicInfoTag::m_strArtistSort protected
Referenced by Archive(), Clear(), GetArtistSort(), SetArtistSort(), and ToSortable().
m_strComment
std::string MUSIC_INFO::CMusicInfoTag::m_strComment protected
Referenced by Archive(), Clear(), GetComment(), Serialize(), SetComment(), and ToSortable().
m_strComposerSort
std::string MUSIC_INFO::CMusicInfoTag::m_strComposerSort protected
Referenced by Clear(), GetComposerSort(), and SetComposerSort().
m_strDiscSubtitle
std::string MUSIC_INFO::CMusicInfoTag::m_strDiscSubtitle protected
Referenced by Archive(), Clear(), GetDiscSubtitle(), operator!=(), Serialize(), and SetDiscSubtitle().
m_strLyrics
std::string MUSIC_INFO::CMusicInfoTag::m_strLyrics protected
Referenced by Archive(), GetLyrics(), Serialize(), and SetLyrics().
m_strMood
std::string MUSIC_INFO::CMusicInfoTag::m_strMood protected
Referenced by Archive(), Clear(), GetMood(), Serialize(), SetMood(), and ToSortable().
m_strMusicBrainzAlbumID
std::string MUSIC_INFO::CMusicInfoTag::m_strMusicBrainzAlbumID protected
Referenced by Archive(), Clear(), GetMusicBrainzAlbumID(), Serialize(), and SetMusicBrainzAlbumID().
m_strMusicBrainzReleaseGroupID
std::string MUSIC_INFO::CMusicInfoTag::m_strMusicBrainzReleaseGroupID protected
Referenced by Archive(), Clear(), and Serialize().
m_strMusicBrainzReleaseType
std::string MUSIC_INFO::CMusicInfoTag::m_strMusicBrainzReleaseType protected
Referenced by Archive(), Clear(), GetMusicBrainzReleaseType(), and SetMusicBrainzReleaseType().
m_strMusicBrainzTrackID
std::string MUSIC_INFO::CMusicInfoTag::m_strMusicBrainzTrackID protected
Referenced by Archive(), Clear(), GetMusicBrainzTrackID(), Serialize(), and SetMusicBrainzTrackID().
m_strOriginalDate
std::string MUSIC_INFO::CMusicInfoTag::m_strOriginalDate protected
Referenced by AddOriginalDate(), Archive(), Clear(), GetOriginalDate(), Serialize(), SetOriginalDate(), and ToSortable().
m_strRecordLabel
std::string MUSIC_INFO::CMusicInfoTag::m_strRecordLabel protected
Referenced by Archive(), Clear(), GetRecordLabel(), Serialize(), and SetRecordLabel().
m_strReleaseDate
std::string MUSIC_INFO::CMusicInfoTag::m_strReleaseDate protected
Referenced by AddReleaseDate(), Archive(), Clear(), GetReleaseDate(), Serialize(), SetReleaseDate(), and SetYear().
m_strReleaseStatus
std::string MUSIC_INFO::CMusicInfoTag::m_strReleaseStatus protected
Referenced by Archive(), Clear(), GetAlbumReleaseStatus(), Serialize(), and SetAlbumReleaseStatus().
m_strTitle
std::string MUSIC_INFO::CMusicInfoTag::m_strTitle protected
Referenced by Archive(), Clear(), GetTitle(), operator!=(), Serialize(), SetTitle(), XBMCAddon::xbmcgui::ListItem::setTitleRaw(), and ToSortable().
m_strURL
std::string MUSIC_INFO::CMusicInfoTag::m_strURL protected
Referenced by Archive(), Clear(), GetURL(), operator!=(), Serialize(), and SetURL().
m_type
MediaType MUSIC_INFO::CMusicInfoTag::m_type protected
item type "music", "song", "album", "artist"
Referenced by Archive(), Clear(), GetType(), Serialize(), SetDatabaseId(), and SetType().
m_Userrating
int MUSIC_INFO::CMusicInfoTag::m_Userrating protected
Referenced by Archive(), Clear(), GetUserrating(), Serialize(), SetUserrating(), and ToSortable().
m_Votes
int MUSIC_INFO::CMusicInfoTag::m_Votes protected
Referenced by Archive(), Clear(), GetVotes(), Serialize(), SetVotes(), and ToSortable().
The documentation for this class was generated from the following files:
MusicInfoTag.h
MusicInfoTag.cpp