Kodi Documentation: ActiveAE::CSyncError Class Reference
ActiveAE::CSyncError Class Reference
#include <ActiveAEStream.h>
Public Member Functions
CSyncError ()
void Add (double error)
void Flush (std::chrono::milliseconds interval=std::chrono::milliseconds(100))
void SetErrorInterval (std::chrono::milliseconds interval=std::chrono::milliseconds(100))
bool Get (double &error, std::chrono::milliseconds interval=std::chrono::milliseconds(100))
double GetLastError (unsigned int &time)
void Correction (double correction)
Protected Member Functions
double Get () const
Protected Attributes
double m_buffer
double m_lastError
int m_count
XbmcThreads::EndTime m_timer
Constructor & Destructor Documentation
CSyncError()
ActiveAE::CSyncError::CSyncError () inline
References Flush().
Member Function Documentation
Add()
void ActiveAE::CSyncError::Add (double error) inline
References m_buffer, and m_count.
Correction()
void ActiveAE::CSyncError::Correction (double correction) inline
References m_lastError.
Referenced by ActiveAE::CActiveAE::SyncStream().
Flush()
void ActiveAE::CSyncError::Flush (std::chrono::milliseconds interval = std::chrono::milliseconds(100)) inline
References m_buffer, m_count, m_lastError, and m_timer.
Referenced by CSyncError(), Get(), ActiveAE::CActiveAE::SFlushStream(), and ActiveAE::CActiveAE::SyncStream().
Get() [1/2]
double ActiveAE::CSyncError::Get () const inline protected
References m_buffer, and m_count.
Referenced by Get().
Get() [2/2]
bool ActiveAE::CSyncError::Get (double & error, std::chrono::milliseconds interval = std::chrono::milliseconds(100)) inline
References Flush(), Get(), m_lastError, and m_timer.
Referenced by ActiveAE::CActiveAE::SyncStream().
GetLastError()
double ActiveAE::CSyncError::GetLastError (unsigned int & time) inline
References m_lastError, and m_timer.
Referenced by ActiveAE::CEngineStats::UpdateStream().
SetErrorInterval()
void ActiveAE::CSyncError::SetErrorInterval (std::chrono::milliseconds interval = std::chrono::milliseconds(100)) inline
References m_buffer, m_count, and m_timer.
Referenced by ActiveAE::CActiveAE::SyncStream().
Member Data Documentation
m_buffer
double ActiveAE::CSyncError::m_buffer protected
Referenced by Add(), Flush(), Get(), and SetErrorInterval().
m_count
int ActiveAE::CSyncError::m_count protected
Referenced by Add(), Flush(), Get(), and SetErrorInterval().
m_lastError
double ActiveAE::CSyncError::m_lastError protected
Referenced by Correction(), Flush(), Get(), and GetLastError().
m_timer
XbmcThreads::EndTime ActiveAE::CSyncError::m_timer protected
Referenced by Flush(), Get(), GetLastError(), and SetErrorInterval().
The documentation for this class was generated from the following file:
ActiveAEStream.h