Kodi Documentation: PVR::CPVRRecording Class Reference
PVR::CPVRRecording Class Reference final
#include <PVRRecording.h>
Public Member Functions
CPVRRecording ()
CPVRRecording (const PVR_RECORDING &recording, unsigned int iClientId)
bool operator== (const CPVRRecording &right) const
bool operator!= (const CPVRRecording &right) const
void Serialize (CVariant &value) const override
void ToSortable (SortItem &sortable, Field field) const override
void Reset ()
Reset this tag to it's initial state.
bool Delete ()
Delete this recording on the client (if supported).
bool Undelete ()
Undelete this recording on the client (if supported).
bool Rename (const std::string &strNewName)
Rename this recording on the client (if supported).
bool SetPlayCount (int count) override
Set this recording's play count. The value will be transferred to the backend if it supports server-side play counts.
bool IncrementPlayCount () override
Increment this recording's play count. The value will be transferred to the backend if it supports server-side play counts.
bool SetLocalPlayCount (int count)
Set this recording's play count without transferring the value to the backend, even if it supports server-side play counts.
int GetLocalPlayCount () const
Get this recording's local play count. The value will not be obtained from the backend, even if it supports server-side play counts.
bool SetResumePoint (const CBookmark &resumePoint) override
Set this recording's resume point. The value will be transferred to the backend if it supports server-side resume points.
bool SetResumePoint (double timeInSeconds, double totalTimeInSeconds, const std::string &playerState="") override
Set this recording's resume point. The value will be transferred to the backend if it supports server-side resume points.
CBookmark GetResumePoint () const override
Get this recording's resume point. The value will be obtained from the backend if it supports server-side resume points.
bool UpdateRecordingSize ()
Update this recording's size. The value will be obtained from the backend if it supports server-side size retrieval.
CBookmark GetLocalResumePoint () const
Get this recording's local resume point. The value will not be obtained from the backend even if it supports server-side resume points.
std::vector< EDL::Edit > GetEdl () const
Retrieve the edit decision list (EDL) of a recording on the backend.
void UpdateMetadata (CVideoDatabase &db, const CPVRClient &client)
Get metadata like the resume point and play count from the database if the client doesn't handle it itself.
void DeleteMetadata (CVideoDatabase &db)
Delete metadata like the resume point and play count from the database.
void Update (const CPVRRecording &tag, const CPVRClient &client)
Update this tag with the contents of the given tag.
const CDateTime & RecordingTimeAsUTC () const
Retrieve the recording start as UTC time.
const CDateTime & RecordingTimeAsLocalTime () const
Retrieve the recording start as local time.
CDateTime EndTimeAsUTC () const
Retrieve the recording end as UTC time.
CDateTime EndTimeAsLocalTime () const
Retrieve the recording end as local time.
bool HasExpirationTime () const
Check whether this recording has an expiration time.
CDateTime ExpirationTimeAsLocalTime () const
Retrieve the recording expiration time as local time.
bool WillBeExpiredWithNewLifetime (int iLifetime) const
Check whether this recording will immediately expire if the given lifetime value would be set.
bool IsDeleted () const
If deleted but can be undeleted it is true.
bool IsRadio () const
Check whether this is a tv or radio recording.
unsigned int BroadcastUid () const
std::shared_ptr< CPVRChannel > Channel () const
int ChannelUid () const
Get the uid of the channel on which this recording is/was running.
int ClientID () const
the identifier of the client that serves this recording
const std::string & ClientRecordingID () const
Get the recording ID as upplied by the client.
unsigned int RecordingID () const
Get the recording ID as upplied by the client.
void SetRecordingID (unsigned int recordingId)
Set the recording ID.
const std::string & Directory () const
Get the directory for this recording.
int Priority () const
Get the priority for this recording.
int LifeTime () const
Get the lifetime for this recording.
void SetLifeTime (int lifeTime)
Set the lifetime for this recording.
const std::string & ChannelName () const
Get the channel name for this recording.
const std::string & ClientIconPath () const
Return the icon path as given by the client.
const std::string & ClientThumbnailPath () const
Return the thumbnail path as given by the client.
const std::string & ClientFanartPath () const
Return the fanart path as given by the client.
const std::string & ClientParentalRatingIconPath () const
Return the parental rating icon path as given by the client.
const std::string & IconPath () const
Return the icon path used by Kodi.
const std::string & ThumbnailPath () const
Return the thumnail path used by Kodi.
const std::string & FanartPath () const
Return the fanart path used by Kodi.
const std::string & EpisodeName () const
Retrieve the recording Episode Name.
bool IsInProgress () const
check whether this recording is currently in progress
std::shared_ptr< CPVRTimerInfoTag > GetRecordingTimer () const
return the timer for an in-progress recording, if any
void SetGenre (int iGenreType, int iGenreSubType, const std::string &strGenre)
set the genre for this recording.
int GenreType () const
Get the genre type ID of this recording.
int GenreSubType () const
Get the genre subtype ID of this recording.
const std::vector< std::string > & Genre () const
Get the genre as human readable string.
const std::string GetGenresLabel () const
Get the genre(s) of this recording as formatted string.
CDateTime FirstAired () const
Get the first air date of this recording.
int GetYear () const override
Get the premiere year of this recording.
void SetYear (int year) override
Set the premiere year of this recording.
bool HasYear () const override
Check if the premiere year of this recording is valid.
bool IsNew () const
Check whether this recording will be flagged as new.
bool IsPremiere () const
Check whether this recording will be flagged as a premiere.
bool IsFinale () const
Check whether this recording will be flagged as a finale.
bool IsLive () const
Check whether this recording will be flagged as live.
unsigned int Flags () const
Return the flags (PVR_RECORDING_FLAG_*) of this recording as a bitfield.
int64_t GetSizeInBytes () const
Return the size of this recording in bytes.
void SetDirty (bool bDirty)
Mark a recording as dirty/clean.
bool IsDirty () const
Return whether the recording is marked dirty.
int ClientProviderUid () const
Get the uid of the provider on the client which this recording is from.
std::string ProviderName () const
Get the client provider name for this recording.
std::shared_ptr< CPVRProvider > GetDefaultProvider () const
Get the default provider of this recording. The default provider represents the PVR add-on itself.
bool HasClientProvider () const
Whether or not this recording has a provider set by the client.
std::shared_ptr< CPVRProvider > GetProvider () const
Get the provider of this recording. This may be the default provider or a custom provider set by the client. If HasClientProvider() returns true the provider will be custom from the client, otherwise the default provider.
unsigned int GetParentalRating () const
Get the parental rating of this recording.
const std::string & GetParentalRatingCode () const
Get the parental rating code of this recording.
const std::string & GetParentalRatingIcon () const
Get the parental rating icon path of this recording.
const std::string & GetParentalRatingSource () const
Get the parental rating source of this recording.
int EpisodePart () const
Get the episode part number of this recording.
const std::string & TitleExtraInfo () const
Get the title extra information of this recording.
Public Member Functions inherited from CVideoInfoTag
CVideoInfoTag ()
virtual ~CVideoInfoTag ()=default
void Reset ()
bool Load (const TiXmlElement *element, bool append=false, bool prioritise=false)
bool Save (TiXmlNode *node, const std::string &tag, bool savePathInfo=true, const TiXmlElement *additionalNode=NULL)
void Merge (CVideoInfoTag &other)
void Archive (CArchive &ar) override
void Serialize (CVariant &value) const override
void ToSortable (SortItem &sortable, Field field) const override
const CRating GetRating (std::string type="") const
const std::string & GetDefaultRating () const
const std::string GetUniqueID (std::string type="") const
const std::map< std::string, std::string > & GetUniqueIDs () const
const std::string & GetDefaultUniqueID () const
bool HasUniqueID () const
bool HasPremiered () const
const CDateTime & GetPremiered () const
const CDateTime & GetFirstAired () const
const std::string GetCast (bool bIncludeRole=false) const
bool HasStreamDetails () const
bool IsEmpty () const
const std::string & GetPath () const
void SetDuration (int duration)
set the duration in seconds
unsigned int GetDuration () const
retrieve the duration in seconds. Prefers the duration from stream details if available.
unsigned int GetStaticDuration () const
retrieve the duration in seconds. Ignores the duration from stream details even if available.
void SetBasePath (std::string basePath)
void SetDirector (std::vector< std::string > director)
void SetWritingCredits (std::vector< std::string > writingCredits)
void SetGenre (std::vector< std::string > genre)
void SetCountry (std::vector< std::string > country)
void SetTagLine (std::string tagLine)
void SetPlotOutline (std::string plotOutline)
void SetTrailer (std::string trailer)
void SetPlot (std::string plot)
std::string const & GetTitle () const
void SetTitle (std::string title)
void SetSortTitle (std::string sortTitle)
void SetPictureURL (CScraperUrl &pictureURL)
void SetRating (float rating, int votes, const std::string &type="", bool def=false)
void SetRating (CRating rating, const std::string &type="", bool def=false)
void SetRating (float rating, const std::string &type="", bool def=false)
void RemoveRating (const std::string &type)
void SetRatings (RatingMap ratings, const std::string &defaultRating="")
void SetVotes (int votes, const std::string &type="")
void SetUniqueIDs (std::map< std::string, std::string > uniqueIDs)
void SetPremiered (const CDateTime &premiered)
void SetPremieredFromDBDate (const std::string &premieredString)
void SetArtist (std::vector< std::string > artist)
void SetSet (std::string set)
void SetSetOverview (std::string setOverview)
void SetTags (std::vector< std::string > tags)
void SetFile (std::string file)
void SetPath (std::string path)
void SetMPAARating (std::string mpaaRating)
void SetFileNameAndPath (std::string fileNameAndPath)
void SetOriginalTitle (std::string originalTitle)
void SetEpisodeGuide (std::string episodeGuide)
void SetStatus (std::string status)
void SetProductionCode (std::string productionCode)
void SetShowTitle (std::string showTitle)
void SetStudio (std::vector< std::string > studio)
void SetAlbum (std::string album)
void SetShowLink (std::vector< std::string > showLink)
void SetUniqueID (const std::string &uniqueid, const std::string &type="", bool def=false)
void RemoveUniqueID (const std::string &type)
void SetNamedSeasons (std::map< int, std::string > namedSeasons)
void SetUserrating (int userrating)
virtual int GetPlayCount () const
Get this videos's play count.
virtual void ResetPlayCount ()
Reset playcount.
virtual bool IsPlayCountSet () const
Check if the playcount is set.
const CAssetInfo & GetAssetInfo () const
Get the video's asset info.
CAssetInfo & GetAssetInfo ()
bool HasVideoVersions () const
Whether the item has multiple video versions.
void SetHasVideoVersions (bool hasVersions)
Set whether this video has video versions.
bool HasVideoExtras () const
Whether the item has video extras.
void SetHasVideoExtras (bool hasExtras)
Set whether this video has video extras.
bool IsDefaultVideoVersion () const
Whether the item is the default video version.
void SetIsDefaultVideoVersion (bool isDefaultVideoVersion)
Set whether the item is the default version.
bool GetUpdateSetOverview () const
Get whether the Set Overview should be updated. If an NFO contains a <name> but no <overview> then this allows the current Overview to be kept. Otherwise it is overwritten. Default is true - so if updated by a scraper the Overview will be overwritten.
Static Public Member Functions
static std::string GetTitleFromURL (const std::string &url)
Retrieve the recording title from the URL path.
Static Public Member Functions inherited from CVideoInfoTag
static unsigned int GetDurationFromMinuteString (const std::string &runtime)
get the duration in seconds from a minute string
Static Public Attributes
static const std::string IMAGE_OWNER_PATTERN = "pvrrecording"
Private Member Functions
CPVRRecording (const CPVRRecording &tag)=delete
CPVRRecording & operator= (const CPVRRecording &other)=delete
void UpdatePath ()
Private Attributes
int m_iClientId
std::string m_strRecordingId
std::string m_strChannelName
int m_iPriority
int m_iLifetime
std::string m_strDirectory
unsigned int m_iRecordingId
CPVRCachedImage m_iconPath
CPVRCachedImage m_thumbnailPath
CPVRCachedImage m_fanartPath
CDateTime m_recordingTime
bool m_bGotMetaData
bool m_bIsDeleted
bool m_bInProgress
unsigned int m_iEpgEventId
int m_iChannelUid
bool m_bRadio
int m_iGenreType = 0
int m_iGenreSubType = 0
XbmcThreads::EndTime m_resumePointRefetchTimeout
unsigned int m_iFlags = 0
XbmcThreads::EndTime m_recordingSizeRefetchTimeout
int64_t m_sizeInBytes = 0
bool m_bDirty = false
std::string m_strProviderName
int m_iClientProviderUid
unsigned int m_parentalRating {0}
std::string m_parentalRatingCode
CPVRCachedImage m_parentalRatingIcon
std::string m_parentalRatingSource
int m_episodePartNumber {PVR_RECORDING_INVALID_SERIES_EPISODE}
std::string m_titleExtraInfo
CCriticalSection m_critSection
Additional Inherited Members
Public Types inherited from CVideoInfoTag
typedef std::vector< SActorInfo >::const_iterator iCast
Public Attributes inherited from CVideoInfoTag
std::string m_basePath
int m_parentPathID
std::vector< std::string > m_director
std::vector< std::string > m_writingCredits
std::vector< std::string > m_genre
std::vector< std::string > m_country
std::string m_strTagLine
std::string m_strPlotOutline
std::string m_strTrailer
std::string m_strPlot
CScraperUrl m_strPictureURL
std::string m_strTitle
std::string m_strSortTitle
std::vector< std::string > m_artist
std::vector< SActorInfo > m_cast
SetInfo m_set
Assigned movie set.
std::vector< std::string > m_tags
std::string m_strFile
std::string m_strPath
std::string m_strMPAARating
std::string m_strFileNameAndPath
std::string m_strOriginalTitle
std::string m_strEpisodeGuide
CDateTime m_premiered
bool m_bHasPremiered
std::string m_strStatus
std::string m_strProductionCode
CDateTime m_firstAired
std::string m_strShowTitle
std::vector< std::string > m_studio
std::string m_strAlbum
CDateTime m_lastPlayed
std::vector< std::string > m_showLink
std::map< int, std::string > m_namedSeasons
int m_iTop250
int m_year
int m_iSeason
int m_iEpisode
int m_iIdUniqueID
int m_iDbId
int m_iFileId
int m_iSpecialSortSeason
int m_iSpecialSortEpisode
int m_iTrack
RatingMap m_ratings
int m_iIdRating
int m_iUserRating
CBookmark m_EpBookmark
int m_iBookmarkId
int m_iIdShow
int m_iIdSeason
CFanart m_fanart
CStreamDetails m_streamDetails
CDateTime m_dateAdded
MediaType m_type
int m_relevance
int m_parsedDetails
std::vector< EmbeddedArtInfo > m_coverArt
art information
unsigned int m_duration
duration in seconds
Protected Member Functions inherited from IArchivable
virtual ~IArchivable ()=default
Protected Member Functions inherited from ISerializable
~ISerializable ()=default
Protected Member Functions inherited from ISortable
~ISortable ()=default
Constructor & Destructor Documentation
CPVRRecording() [1/3]
CPVRRecording::CPVRRecording ()
References Reset().
CPVRRecording() [2/3]
CPVRRecording::CPVRRecording (const PVR_RECORDING & recording, unsigned int iClientId)
References PVR_RECORDING::bIsDeleted, Channel(), PVR_RECORDING::channelType, PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), CServiceBroker::GetSettingsComponent(), PVR_RECORDING::iChannelUid, PVR_RECORDING::iClientProviderUid, PVR_RECORDING::iDuration, PVR_RECORDING::iEpgEventId, PVR_RECORDING::iEpisodeNumber, PVR_RECORDING::iEpisodePartNumber, PVR_RECORDING::iFlags, PVR_RECORDING::iGenreSubType, PVR_RECORDING::iGenreType, PVR_RECORDING::iLastPlayedPosition, PVR_RECORDING::iLifetime, PVR_RECORDING::iParentalRating, PVR_RECORDING::iPlayCount, PVR_RECORDING::iPriority, PVR_RECORDING::iSeriesNumber, PVR_RECORDING::iYear, CLog::Log(), LOGWARNING, m_bIsDeleted, m_bRadio, m_episodePartNumber, CVideoInfoTag::m_firstAired, m_iChannelUid, m_iClientId, m_iClientProviderUid, m_iEpgEventId, CVideoInfoTag::m_iEpisode, m_iFlags, m_iLifetime, m_iPriority, CVideoInfoTag::m_iSeason, m_parentalRating, m_parentalRatingCode, m_parentalRatingSource, m_recordingTime, m_sizeInBytes, m_strChannelName, m_strDirectory, CVideoInfoTag::m_strPlot, CVideoInfoTag::m_strPlotOutline, m_strProviderName, m_strRecordingId, CVideoInfoTag::m_strShowTitle, CVideoInfoTag::m_strTitle, m_titleExtraInfo, PVR_RECORDING_CHANNEL_TYPE_RADIO, PVR_RECORDING_CHANNEL_TYPE_UNKNOWN, PVR_RECORDING::recordingTime, Reset(), CVideoInfoTag::SetDuration(), CDateTime::SetFromW3CDateTime(), SetGenre(), CVideoInfoTag::SetPlayCount(), CVideoInfoTag::SetResumePoint(), SetYear(), PVR_RECORDING::sizeInBytes, PVR_RECORDING::strChannelName, PVR_RECORDING::strDirectory, PVR_RECORDING::strEpisodeName, PVR_RECORDING::strFirstAired, PVR_RECORDING::strGenreDescription, PVR_RECORDING::strParentalRatingCode, PVR_RECORDING::strParentalRatingSource, PVR_RECORDING::strPlot, PVR_RECORDING::strPlotOutline, PVR_RECORDING::strProviderName, PVR_RECORDING::strRecordingId, PVR_RECORDING::strTitle, PVR_RECORDING::strTitleExtraInfo, and UpdatePath().
CPVRRecording() [3/3]
PVR::CPVRRecording::CPVRRecording (const CPVRRecording & tag) private delete
Member Function Documentation
BroadcastUid()
unsigned int PVR::CPVRRecording::BroadcastUid () const inline
Returns
Broadcast id of the EPG event associated with this recording or EPG_TAG_INVALID_UID
References m_iEpgEventId.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording(), and GetRecordingTimer().
Channel()
std::shared_ptr< CPVRChannel > CPVRRecording::Channel () const
Returns
Get the channel on which this recording is/was running
Note
Only works if the recording has a channel uid provided by the add-on
References PVR::CPVRManager::ChannelGroups(), CServiceBroker::GetPVRManager(), m_iChannelUid, m_iClientId, and PVR_CHANNEL_INVALID_UID.
Referenced by CPVRRecording().
ChannelName()
const std::string & PVR::CPVRRecording::ChannelName () const inline
Get the channel name for this recording.
Returns
the channel name
References m_strChannelName.
ChannelUid()
int CPVRRecording::ChannelUid () const
Get the uid of the channel on which this recording is/was running.
Returns
the uid of the channel or PVR_CHANNEL_INVALID_UID
References m_iChannelUid.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording(), and GetRecordingTimer().
ClientFanartPath()
const std::string & PVR::CPVRRecording::ClientFanartPath () const inline
Return the fanart path as given by the client.
Returns
The path.
References PVR::CPVRCachedImage::GetClientImage(), and m_fanartPath.
Referenced by Serialize().
ClientIconPath()
const std::string & PVR::CPVRRecording::ClientIconPath () const inline
Return the icon path as given by the client.
Returns
The path.
References PVR::CPVRCachedImage::GetClientImage(), and m_iconPath.
Referenced by Serialize().
ClientID()
int CPVRRecording::ClientID () const
the identifier of the client that serves this recording
Returns
the client identifier
References m_iClientId.
Referenced by GetRecordingTimer().
ClientParentalRatingIconPath()
const std::string & PVR::CPVRRecording::ClientParentalRatingIconPath () const inline
Return the parental rating icon path as given by the client.
Returns
The path.
References PVR::CPVRCachedImage::GetClientImage(), and m_parentalRatingIcon.
Referenced by Serialize().
ClientProviderUid()
int CPVRRecording::ClientProviderUid () const
Get the uid of the provider on the client which this recording is from.
Returns
the client uid of the provider or PVR_PROVIDER_INVALID_UID
References m_critSection, and m_iClientProviderUid.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording().
ClientRecordingID()
const std::string & PVR::CPVRRecording::ClientRecordingID () const inline
Get the recording ID as upplied by the client.
Returns
the recording identifier
References m_strRecordingId.
ClientThumbnailPath()
const std::string & PVR::CPVRRecording::ClientThumbnailPath () const inline
Return the thumbnail path as given by the client.
Returns
The path.
References PVR::CPVRCachedImage::GetClientImage(), and m_thumbnailPath.
Referenced by Serialize().
Delete()
bool CPVRRecording::Delete ()
Delete this recording on the client (if supported).
Returns
True if it was deleted successfully, false otherwise.
References PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), m_iClientId, and PVR_ERROR_NO_ERROR.
DeleteMetadata()
void CPVRRecording::DeleteMetadata (CVideoDatabase & db)
Delete metadata like the resume point and play count from the database.
Parameters
db The database to delete the data from.
References CVideoDatabase::EraseAllForFile(), and CVideoInfoTag::m_strFileNameAndPath.
Directory()
const std::string & PVR::CPVRRecording::Directory () const inline
Get the directory for this recording.
Returns
the directory
References m_strDirectory.
EndTimeAsLocalTime()
CDateTime CPVRRecording::EndTimeAsLocalTime () const
Retrieve the recording end as local time.
Returns
the recording end time
References EndTimeAsUTC(), and CDateTime::SetFromUTCDateTime().
Referenced by ExpirationTimeAsLocalTime().
EndTimeAsUTC()
CDateTime CPVRRecording::EndTimeAsUTC () const
Retrieve the recording end as UTC time.
Returns
the recording end time
References CVideoInfoTag::GetDuration(), and m_recordingTime.
Referenced by EndTimeAsLocalTime(), GetRecordingTimer(), Serialize(), and WillBeExpiredWithNewLifetime().
EpisodeName()
const std::string & PVR::CPVRRecording::EpisodeName () const inline
Retrieve the recording Episode Name.
Note
Returns an empty string if no Episode Name was provided by the PVR client
References CVideoInfoTag::m_strShowTitle.
EpisodePart()
int CPVRRecording::EpisodePart () const
Get the episode part number of this recording.
Returns
The episode part number.
References m_critSection, and m_episodePartNumber.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording().
ExpirationTimeAsLocalTime()
CDateTime CPVRRecording::ExpirationTimeAsLocalTime () const
Retrieve the recording expiration time as local time.
Returns
the recording expiration time
References EndTimeAsLocalTime(), and m_iLifetime.
FanartPath()
const std::string & PVR::CPVRRecording::FanartPath () const inline
Return the fanart path used by Kodi.
Returns
The path.
References PVR::CPVRCachedImage::GetLocalImage(), and m_fanartPath.
FirstAired()
CDateTime CPVRRecording::FirstAired () const
Get the first air date of this recording.
Returns
The first air date.
References CVideoInfoTag::m_firstAired.
Flags()
unsigned int PVR::CPVRRecording::Flags () const inline
Return the flags (PVR_RECORDING_FLAG_*) of this recording as a bitfield.
Returns
the flags.
References m_iFlags.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording().
Genre()
const std::vector< std::string > & PVR::CPVRRecording::Genre () const inline
Get the genre as human readable string.
Returns
The genre.
References CVideoInfoTag::m_genre.
GenreSubType()
int PVR::CPVRRecording::GenreSubType () const inline
Get the genre subtype ID of this recording.
Returns
The genre subtype ID.
References m_iGenreSubType.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording().
GenreType()
int PVR::CPVRRecording::GenreType () const inline
Get the genre type ID of this recording.
Returns
The genre type ID.
References m_iGenreType.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording().
GetDefaultProvider()
std::shared_ptr< CPVRProvider > CPVRRecording::GetDefaultProvider () const
Get the default provider of this recording. The default provider represents the PVR add-on itself.
Returns
The default provider of this recording
References CServiceBroker::GetPVRManager(), m_iClientId, PVR::CPVRManager::Providers(), and PVR_PROVIDER_INVALID_UID.
Referenced by GetProvider().
GetEdl()
std::vector< EDL::Edit > CPVRRecording::GetEdl () const
Retrieve the edit decision list (EDL) of a recording on the backend.
Returns
The edit decision list (empty on error)
References PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), and m_iClientId.
GetGenresLabel()
const std::string CPVRRecording::GetGenresLabel () const
Get the genre(s) of this recording as formatted string.
Returns
The genres label.
References CServiceBroker::GetSettingsComponent(), and CVideoInfoTag::m_genre.
GetLocalPlayCount()
int PVR::CPVRRecording::GetLocalPlayCount () const inline
Get this recording's local play count. The value will not be obtained from the backend, even if it supports server-side play counts.
Returns
the play count.
References CVideoInfoTag::GetPlayCount().
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording().
GetLocalResumePoint()
CBookmark PVR::CPVRRecording::GetLocalResumePoint () const inline
Get this recording's local resume point. The value will not be obtained from the backend even if it supports server-side resume points.
Returns
the resume point.
References CVideoInfoTag::GetResumePoint().
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording().
GetParentalRating()
unsigned int CPVRRecording::GetParentalRating () const
Get the parental rating of this recording.
Returns
The parental rating.
References m_critSection, and m_parentalRating.
GetParentalRatingCode()
const std::string & CPVRRecording::GetParentalRatingCode () const
Get the parental rating code of this recording.
Returns
The parental rating code.
References m_critSection, and m_parentalRatingCode.
GetParentalRatingIcon()
const std::string & CPVRRecording::GetParentalRatingIcon () const
Get the parental rating icon path of this recording.
Returns
The parental rating icon path.
References PVR::CPVRCachedImage::GetLocalImage(), m_critSection, and m_parentalRatingIcon.
GetParentalRatingSource()
const std::string & CPVRRecording::GetParentalRatingSource () const
Get the parental rating source of this recording.
Returns
The parental rating source.
References m_critSection, and m_parentalRatingSource.
GetProvider()
std::shared_ptr< CPVRProvider > CPVRRecording::GetProvider () const
Get the provider of this recording. This may be the default provider or a custom provider set by the client. If HasClientProvider() returns true the provider will be custom from the client, otherwise the default provider.
Returns
The provider of this recording
References GetDefaultProvider(), CServiceBroker::GetPVRManager(), m_iClientId, m_iClientProviderUid, and PVR::CPVRManager::Providers().
GetRecordingTimer()
std::shared_ptr< CPVRTimerInfoTag > CPVRRecording::GetRecordingTimer () const
return the timer for an in-progress recording, if any
Returns
the timer if the recording is in progress, nullptr otherwise
References BroadcastUid(), ChannelUid(), ClientID(), EndTimeAsUTC(), EPG_TAG_INVALID_UID, CServiceBroker::GetPVRManager(), RecordingTimeAsUTC(), and PVR::CPVRManager::Timers().
Referenced by IsInProgress().
GetResumePoint()
CBookmark CPVRRecording::GetResumePoint () const override virtual
Get this recording's resume point. The value will be obtained from the backend if it supports server-side resume points.
Returns
the resume point.
Reimplemented from CVideoInfoTag.
References PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), CVideoInfoTag::GetResumePoint(), CVideoInfoTag::m_duration, m_iClientId, m_resumePointRefetchTimeout, CBookmark::timeInSeconds, and CBookmark::totalTimeInSeconds.
GetSizeInBytes()
int64_t CPVRRecording::GetSizeInBytes () const
Return the size of this recording in bytes.
Returns
the size in bytes.
References m_critSection, and m_sizeInBytes.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording().
GetTitleFromURL()
std::string CPVRRecording::GetTitleFromURL (const std::string & url) static
Retrieve the recording title from the URL path.
Parameters
url the URL for the recording
Returns
Title of the recording
References PVR::CPVRRecordingsPath::GetTitle().
Referenced by CFileItem::GetMovieName().
GetYear()
int CPVRRecording::GetYear () const override virtual
Get the premiere year of this recording.
Returns
The premiere year
Reimplemented from CVideoInfoTag.
References CDateTime::GetYear(), CDateTime::IsValid(), and CVideoInfoTag::m_premiered.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording(), and UpdatePath().
HasClientProvider()
bool CPVRRecording::HasClientProvider () const
Whether or not this recording has a provider set by the client.
Returns
True if a provider was set by the client, false otherwise.
References m_critSection, m_iClientProviderUid, and PVR_PROVIDER_INVALID_UID.
HasExpirationTime()
bool PVR::CPVRRecording::HasExpirationTime () const inline
Check whether this recording has an expiration time.
Returns
True if the recording has an expiration time, false otherwise
References m_iLifetime.
HasYear()
bool CPVRRecording::HasYear () const override virtual
Check if the premiere year of this recording is valid.
Returns
True if the recording has as valid premiere date, false otherwise
Reimplemented from CVideoInfoTag.
References CDateTime::IsValid(), and CVideoInfoTag::m_premiered.
IconPath()
const std::string & PVR::CPVRRecording::IconPath () const inline
Return the icon path used by Kodi.
Returns
The path.
References PVR::CPVRCachedImage::GetLocalImage(), and m_iconPath.
IncrementPlayCount()
bool CPVRRecording::IncrementPlayCount () override virtual
Increment this recording's play count. The value will be transferred to the backend if it supports server-side play counts.
Returns
True if play count was increased successfully, false otherwise.
Reimplemented from CVideoInfoTag.
References PVR::CPVRManager::GetClient(), CVideoInfoTag::GetPlayCount(), CServiceBroker::GetPVRManager(), CVideoInfoTag::IncrementPlayCount(), m_iClientId, and PVR_ERROR_NO_ERROR.
IsDeleted()
bool PVR::CPVRRecording::IsDeleted () const inline
If deleted but can be undeleted it is true.
References m_bIsDeleted.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording().
IsDirty()
bool PVR::CPVRRecording::IsDirty () const inline
Return whether the recording is marked dirty.
Returns
true if dirty, false otherwise.
References m_bDirty.
IsFinale()
bool CPVRRecording::IsFinale () const
Check whether this recording will be flagged as a finale.
Returns
True if this recording will be flagged as a finale, false otherwise
References m_iFlags, and PVR_RECORDING_FLAG_IS_FINALE.
IsInProgress()
bool CPVRRecording::IsInProgress () const
check whether this recording is currently in progress
Returns
true if the recording is in progress, false otherwise
References GetRecordingTimer(), and m_bInProgress.
IsLive()
bool CPVRRecording::IsLive () const
Check whether this recording will be flagged as live.
Returns
True if this recording will be flagged as live, false otherwise
References m_iFlags, and PVR_RECORDING_FLAG_IS_LIVE.
IsNew()
bool CPVRRecording::IsNew () const
Check whether this recording will be flagged as new.
Returns
True if this recording will be flagged as new, false otherwise
References m_iFlags, and PVR_RECORDING_FLAG_IS_NEW.
IsPremiere()
bool CPVRRecording::IsPremiere () const
Check whether this recording will be flagged as a premiere.
Returns
True if this recording will be flagged as a premiere, false otherwise
References m_iFlags, and PVR_RECORDING_FLAG_IS_PREMIERE.
IsRadio()
bool PVR::CPVRRecording::IsRadio () const inline
Check whether this is a tv or radio recording.
Returns
true if this is a radio recording, false if this is a tv recording
References m_bRadio.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording().
LifeTime()
int PVR::CPVRRecording::LifeTime () const inline
Get the lifetime for this recording.
Returns
the lifetime
References m_iLifetime.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording().
operator!=()
bool CPVRRecording::operator!= (const CPVRRecording & right) const
References right.
operator=()
CPVRRecording & PVR::CPVRRecording::operator= (const CPVRRecording & other) private delete
operator==()
bool CPVRRecording::operator== (const CPVRRecording & right) const
References CVideoInfoTag::GetDuration(), CVideoInfoTag::GetPremiered(), m_bIsDeleted, m_bRadio, m_critSection, m_episodePartNumber, m_fanartPath, CVideoInfoTag::m_firstAired, CVideoInfoTag::m_genre, m_iChannelUid, m_iClientId, m_iClientProviderUid, m_iconPath, m_iEpgEventId, CVideoInfoTag::m_iEpisode, m_iFlags, m_iGenreSubType, m_iGenreType, m_iLifetime, m_iPriority, m_iRecordingId, CVideoInfoTag::m_iSeason, m_parentalRating, m_parentalRatingCode, m_parentalRatingIcon, m_parentalRatingSource, m_recordingTime, m_sizeInBytes, m_strChannelName, m_strDirectory, CVideoInfoTag::m_strFileNameAndPath, CVideoInfoTag::m_strPlot, CVideoInfoTag::m_strPlotOutline, m_strProviderName, m_strRecordingId, CVideoInfoTag::m_strShowTitle, CVideoInfoTag::m_strTitle, m_thumbnailPath, m_titleExtraInfo, and right.
Priority()
int PVR::CPVRRecording::Priority () const inline
Get the priority for this recording.
Returns
the priority
References m_iPriority.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording().
ProviderName()
std::string CPVRRecording::ProviderName () const
Get the client provider name for this recording.
Returns
m_strProviderName The name for this recording provider
References m_critSection, and m_strProviderName.
RecordingID()
unsigned int PVR::CPVRRecording::RecordingID () const inline
Get the recording ID as upplied by the client.
Returns
the recording identifier
References m_iRecordingId.
RecordingTimeAsLocalTime()
const CDateTime & CPVRRecording::RecordingTimeAsLocalTime () const
Retrieve the recording start as local time.
Returns
the recording start time
References m_recordingTime, and CDateTime::SetFromUTCDateTime().
RecordingTimeAsUTC()
const CDateTime & PVR::CPVRRecording::RecordingTimeAsUTC () const inline
Retrieve the recording start as UTC time.
Returns
the recording start time
References m_recordingTime.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording(), and GetRecordingTimer().
Rename()
bool CPVRRecording::Rename (const std::string & strNewName)
Rename this recording on the client (if supported).
Parameters
strNewName The new name.
Returns
True if it was renamed successfully, false otherwise.
References PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), m_iClientId, CVideoInfoTag::m_strTitle, and PVR_ERROR_NO_ERROR.
Reset()
void CPVRRecording::Reset ()
Reset this tag to it's initial state.
References EPG_TAG_INVALID_UID, m_bGotMetaData, m_bInProgress, m_bIsDeleted, m_bRadio, m_critSection, m_episodePartNumber, m_iChannelUid, m_iClientId, m_iClientProviderUid, m_iEpgEventId, CVideoInfoTag::m_iEpisode, m_iFlags, m_iLifetime, m_iPriority, m_iRecordingId, CVideoInfoTag::m_iSeason, m_parentalRating, m_parentalRatingCode, m_parentalRatingSource, m_recordingTime, m_sizeInBytes, m_strChannelName, m_strDirectory, CVideoInfoTag::m_strFileNameAndPath, m_strProviderName, m_strRecordingId, m_titleExtraInfo, PVR_CHANNEL_INVALID_UID, PVR::PVR_CLIENT_INVALID_UID, PVR_PROVIDER_INVALID_UID, PVR_RECORDING_FLAG_UNDEFINED, PVR_RECORDING_INVALID_SERIES_EPISODE, CVideoInfoTag::Reset(), and CDateTime::Reset().
Referenced by CPVRRecording(), and CPVRRecording().
Serialize()
void CPVRRecording::Serialize (CVariant & value) const override virtual
Implements ISerializable.
References ClientFanartPath(), ClientIconPath(), ClientParentalRatingIconPath(), ClientThumbnailPath(), EndTimeAsUTC(), CDateTime::GetAsDBDateTime(), CDateTime::IsValid(), m_bIsDeleted, m_bRadio, m_episodePartNumber, CVideoInfoTag::m_genre, m_iChannelUid, m_iClientId, m_iEpgEventId, m_iLifetime, m_iRecordingId, m_parentalRating, m_parentalRatingCode, m_parentalRatingSource, m_recordingTime, m_strChannelName, m_strDirectory, m_titleExtraInfo, CVideoInfoTag::Serialize(), value, and CVariant::VariantTypeObject.
SetDirty()
void PVR::CPVRRecording::SetDirty (bool bDirty) inline
Mark a recording as dirty/clean.
Parameters
bDirty true to mark as dirty, false to mark as clean.
References m_bDirty.
SetGenre()
void CPVRRecording::SetGenre (int iGenreType, int iGenreSubType, const std::string & strGenre)
set the genre for this recording.
Parameters
iGenreType The genre type ID. If set to EPG_GENRE_USE_STRING, set genre to the value provided with strGenre. Otherwise, compile the genre string from the values given by iGenreType and iGenreSubType
iGenreSubType The genre subtype ID
strGenre The genre
References PVR::CPVREpg::ConvertGenreIdToString(), EPG_GENRE_USE_STRING, CServiceBroker::GetSettingsComponent(), CVideoInfoTag::m_genre, m_iGenreSubType, and m_iGenreType.
Referenced by CPVRRecording().
SetLifeTime()
void PVR::CPVRRecording::SetLifeTime (int lifeTime) inline
Set the lifetime for this recording.
Parameters
lifeTime The lifetime
References m_iLifetime.
SetLocalPlayCount()
bool PVR::CPVRRecording::SetLocalPlayCount (int count) inline
Set this recording's play count without transferring the value to the backend, even if it supports server-side play counts.
Parameters
count play count.
Returns
True if play count was set successfully, false otherwise.
References CVideoInfoTag::SetPlayCount().
SetPlayCount()
bool CPVRRecording::SetPlayCount (int count) override virtual
Set this recording's play count. The value will be transferred to the backend if it supports server-side play counts.
Parameters
count play count.
Returns
True if play count was set successfully, false otherwise.
Reimplemented from CVideoInfoTag.
References PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), m_iClientId, PVR_ERROR_NO_ERROR, and CVideoInfoTag::SetPlayCount().
SetRecordingID()
void PVR::CPVRRecording::SetRecordingID (unsigned int recordingId) inline
Set the recording ID.
Parameters
recordingId The new identifier
References m_iRecordingId.
SetResumePoint() [1/2]
bool CPVRRecording::SetResumePoint (const CBookmark & resumePoint) override virtual
Set this recording's resume point. The value will be transferred to the backend if it supports server-side resume points.
Parameters
resumePoint resume point.
Returns
True if resume point was set successfully, false otherwise.
Reimplemented from CVideoInfoTag.
References PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), m_iClientId, PVR_ERROR_NO_ERROR, CVideoInfoTag::SetResumePoint(), and CBookmark::timeInSeconds.
SetResumePoint() [2/2]
bool CPVRRecording::SetResumePoint (double timeInSeconds, double totalTimeInSeconds, const std::string & playerState = "") override virtual
Set this recording's resume point. The value will be transferred to the backend if it supports server-side resume points.
Parameters
timeInSeconds the time of the resume point
totalTimeInSeconds the total time of the video
playerState the player state
Returns
True if resume point was set successfully, false otherwise.
Reimplemented from CVideoInfoTag.
References PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), m_iClientId, PVR_ERROR_NO_ERROR, and CVideoInfoTag::SetResumePoint().
SetYear()
void CPVRRecording::SetYear (int year) override virtual
Set the premiere year of this recording.
Parameters
year The premiere year
Reimplemented from CVideoInfoTag.
References CVideoInfoTag::m_premiered.
Referenced by CPVRRecording().
ThumbnailPath()
const std::string & PVR::CPVRRecording::ThumbnailPath () const inline
Return the thumnail path used by Kodi.
Returns
The path.
References PVR::CPVRCachedImage::GetLocalImage(), and m_thumbnailPath.
TitleExtraInfo()
const std::string & CPVRRecording::TitleExtraInfo () const
Get the title extra information of this recording.
Returns
The title extra info.
References m_critSection, and m_titleExtraInfo.
ToSortable()
void CPVRRecording::ToSortable (SortItem & sortable, Field field) const override virtual
Implements ISortable.
References FieldProvider, FieldSize, m_critSection, m_iClientId, m_iClientProviderUid, m_sizeInBytes, and CVideoInfoTag::ToSortable().
Undelete()
bool CPVRRecording::Undelete ()
Undelete this recording on the client (if supported).
Returns
True if it was undeleted successfully, false otherwise.
References PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), m_iClientId, and PVR_ERROR_NO_ERROR.
Update()
void CPVRRecording::Update (const CPVRRecording & tag, const CPVRClient & client)
Update this tag with the contents of the given tag.
Parameters
tag The new tag info.
client The client this recording belongs to.
References PVR::CPVREpg::ConvertGenreIdToString(), EPG_GENRE_USE_STRING, g_localizeStrings, CLocalizeStrings::Get(), PVR::CPVRClient::GetClientCapabilities(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGWARNING, m_bIsDeleted, m_bRadio, m_critSection, m_episodePartNumber, m_fanartPath, CVideoInfoTag::m_firstAired, CVideoInfoTag::m_genre, m_iChannelUid, m_iClientId, m_iClientProviderUid, m_iconPath, m_iEpgEventId, CVideoInfoTag::m_iEpisode, m_iFlags, m_iGenreSubType, m_iGenreType, m_iLifetime, m_iPriority, CVideoInfoTag::m_iSeason, m_parentalRating, m_parentalRatingCode, m_parentalRatingIcon, m_parentalRatingSource, m_recordingTime, m_sizeInBytes, m_strChannelName, m_strDirectory, CVideoInfoTag::m_strPlot, CVideoInfoTag::m_strPlotOutline, m_strProviderName, m_strRecordingId, CVideoInfoTag::m_strShowTitle, CVideoInfoTag::m_strTitle, m_thumbnailPath, m_titleExtraInfo, CVideoInfoTag::SetDuration(), CVideoInfoTag::SetPlayCount(), CVideoInfoTag::SetPremiered(), CVideoInfoTag::SetResumePoint(), PVR::CPVRClientCapabilities::SupportsRecordingsLastPlayedPosition(), PVR::CPVRClientCapabilities::SupportsRecordingsPlayCount(), and UpdatePath().
UpdateMetadata()
void CPVRRecording::UpdateMetadata (CVideoDatabase & db, const CPVRClient & client)
Get metadata like the resume point and play count from the database if the client doesn't handle it itself.
Parameters
db The database to read the data from.
client The client this recording belongs to.
References PVR::CPVRClient::GetClientCapabilities(), CVideoDatabase::GetLastPlayed(), CVideoDatabase::GetPlayCount(), CVideoDatabase::GetResumeBookMark(), CVideoDatabase::GetStreamDetails(), CDatabase::IsOpen(), m_bGotMetaData, CVideoInfoTag::m_lastPlayed, CVideoInfoTag::m_streamDetails, CVideoInfoTag::m_strFileNameAndPath, CVideoInfoTag::SetPlayCount(), CVideoInfoTag::SetResumePoint(), PVR::CPVRClientCapabilities::SupportsRecordingsLastPlayedPosition(), and PVR::CPVRClientCapabilities::SupportsRecordingsPlayCount().
UpdatePath()
void CPVRRecording::UpdatePath () private
References GetYear(), m_bIsDeleted, m_bRadio, CVideoInfoTag::m_iEpisode, CVideoInfoTag::m_iSeason, m_recordingTime, m_strChannelName, m_strDirectory, CVideoInfoTag::m_strFileNameAndPath, m_strRecordingId, CVideoInfoTag::m_strShowTitle, and CVideoInfoTag::m_strTitle.
Referenced by CPVRRecording(), and Update().
UpdateRecordingSize()
bool CPVRRecording::UpdateRecordingSize ()
Update this recording's size. The value will be obtained from the backend if it supports server-side size retrieval.
Returns
true if the the updated value is different, false otherwise.
References PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), int64_t(), m_critSection, m_iClientId, m_recordingSizeRefetchTimeout, and m_sizeInBytes.
WillBeExpiredWithNewLifetime()
bool CPVRRecording::WillBeExpiredWithNewLifetime (int iLifetime) const
Check whether this recording will immediately expire if the given lifetime value would be set.
Parameters
iLifetime The lifetime value to check
Returns
True if the recording would immediately expire, false otherwiese
References EndTimeAsUTC(), and CDateTime::GetUTCDateTime().
Member Data Documentation
IMAGE_OWNER_PATTERN
const std::string CPVRRecording::IMAGE_OWNER_PATTERN = "pvrrecording" static
Referenced by PVR::CPVRRecordings::CleanupCachedImages().
m_bDirty
bool PVR::CPVRRecording::m_bDirty = false private
Referenced by IsDirty(), and SetDirty().
m_bGotMetaData
bool PVR::CPVRRecording::m_bGotMetaData private
Referenced by Reset(), and UpdateMetadata().
m_bInProgress
bool PVR::CPVRRecording::m_bInProgress mutable private
set if recording might be in progress
Referenced by IsInProgress(), and Reset().
m_bIsDeleted
bool PVR::CPVRRecording::m_bIsDeleted private
set if entry is a deleted recording which can be undelete
Referenced by CPVRRecording(), IsDeleted(), operator==(), Reset(), Serialize(), Update(), and UpdatePath().
m_bRadio
bool PVR::CPVRRecording::m_bRadio private
radio or tv recording
Referenced by CPVRRecording(), IsRadio(), operator==(), Reset(), Serialize(), Update(), and UpdatePath().
m_critSection
CCriticalSection PVR::CPVRRecording::m_critSection mutable private
Referenced by ClientProviderUid(), EpisodePart(), GetParentalRating(), GetParentalRatingCode(), GetParentalRatingIcon(), GetParentalRatingSource(), GetSizeInBytes(), HasClientProvider(), operator==(), ProviderName(), Reset(), TitleExtraInfo(), ToSortable(), Update(), and UpdateRecordingSize().
m_episodePartNumber
int PVR::CPVRRecording::m_episodePartNumber {PVR_RECORDING_INVALID_SERIES_EPISODE} private
episode part number
Referenced by CPVRRecording(), EpisodePart(), operator==(), Reset(), Serialize(), and Update().
m_fanartPath
CPVRCachedImage PVR::CPVRRecording::m_fanartPath private
fanart path
Referenced by ClientFanartPath(), FanartPath(), operator==(), and Update().
m_iChannelUid
int PVR::CPVRRecording::m_iChannelUid private
channel uid associated with this recording
Referenced by Channel(), ChannelUid(), CPVRRecording(), operator==(), Reset(), Serialize(), and Update().
m_iClientId
int PVR::CPVRRecording::m_iClientId private
ID of the backend
Referenced by Channel(), ClientID(), CPVRRecording(), Delete(), GetDefaultProvider(), GetEdl(), GetProvider(), GetResumePoint(), IncrementPlayCount(), operator==(), Rename(), Reset(), Serialize(), SetPlayCount(), SetResumePoint(), SetResumePoint(), ToSortable(), Undelete(), Update(), and UpdateRecordingSize().
m_iClientProviderUid
int PVR::CPVRRecording::m_iClientProviderUid private
Initial value:
=
      PVR_PROVIDER_INVALID_UID
provider uid associated with this recording on the client
Referenced by ClientProviderUid(), CPVRRecording(), GetProvider(), HasClientProvider(), operator==(), Reset(), ToSortable(), and Update().
m_iconPath
CPVRCachedImage PVR::CPVRRecording::m_iconPath private
icon path
Referenced by ClientIconPath(), IconPath(), operator==(), and Update().
m_iEpgEventId
unsigned int PVR::CPVRRecording::m_iEpgEventId private
epg broadcast id associated with this recording
Referenced by BroadcastUid(), CPVRRecording(), operator==(), Reset(), Serialize(), and Update().
m_iFlags
unsigned int PVR::CPVRRecording::m_iFlags = 0 private
the flags applicable to this recording
Referenced by CPVRRecording(), Flags(), IsFinale(), IsLive(), IsNew(), IsPremiere(), operator==(), Reset(), and Update().
m_iGenreSubType
int PVR::CPVRRecording::m_iGenreSubType = 0 private
genre subtype
Referenced by GenreSubType(), operator==(), SetGenre(), and Update().
m_iGenreType
int PVR::CPVRRecording::m_iGenreType = 0 private
genre type
Referenced by GenreType(), operator==(), SetGenre(), and Update().
m_iLifetime
int PVR::CPVRRecording::m_iLifetime private
lifetime of this recording
Referenced by CPVRRecording(), ExpirationTimeAsLocalTime(), HasExpirationTime(), LifeTime(), operator==(), Reset(), Serialize(), SetLifeTime(), and Update().
m_iPriority
int PVR::CPVRRecording::m_iPriority private
priority of this recording
Referenced by CPVRRecording(), operator==(), Priority(), Reset(), and Update().
m_iRecordingId
unsigned int PVR::CPVRRecording::m_iRecordingId private
id that won't change while xbmc is running
Referenced by operator==(), RecordingID(), Reset(), Serialize(), and SetRecordingID().
m_parentalRating
unsigned int PVR::CPVRRecording::m_parentalRating {0} private
parental rating
Referenced by CPVRRecording(), GetParentalRating(), operator==(), Reset(), Serialize(), and Update().
m_parentalRatingCode
std::string PVR::CPVRRecording::m_parentalRatingCode private
Parental rating code
Referenced by CPVRRecording(), GetParentalRatingCode(), operator==(), Reset(), Serialize(), and Update().
m_parentalRatingIcon
CPVRCachedImage PVR::CPVRRecording::m_parentalRatingIcon private
parental rating icon path
Referenced by ClientParentalRatingIconPath(), GetParentalRatingIcon(), operator==(), and Update().
m_parentalRatingSource
std::string PVR::CPVRRecording::m_parentalRatingSource private
parental rating source
Referenced by CPVRRecording(), GetParentalRatingSource(), operator==(), Reset(), Serialize(), and Update().
m_recordingSizeRefetchTimeout
XbmcThreads::EndTime PVR::CPVRRecording::m_recordingSizeRefetchTimeout mutable private
Referenced by UpdateRecordingSize().
m_recordingTime
CDateTime PVR::CPVRRecording::m_recordingTime private
start time of the recording
Referenced by CPVRRecording(), EndTimeAsUTC(), operator==(), RecordingTimeAsLocalTime(), RecordingTimeAsUTC(), Reset(), Serialize(), Update(), and UpdatePath().
m_resumePointRefetchTimeout
XbmcThreads::EndTime PVR::CPVRRecording::m_resumePointRefetchTimeout mutable private
Referenced by GetResumePoint().
m_sizeInBytes
int64_t PVR::CPVRRecording::m_sizeInBytes = 0 private
the size of the recording in bytes
Referenced by CPVRRecording(), GetSizeInBytes(), operator==(), Reset(), ToSortable(), Update(), and UpdateRecordingSize().
m_strChannelName
std::string PVR::CPVRRecording::m_strChannelName private
name of the channel this was recorded from
Referenced by ChannelName(), CPVRRecording(), operator==(), Reset(), Serialize(), Update(), and UpdatePath().
m_strDirectory
std::string PVR::CPVRRecording::m_strDirectory private
directory of this recording on the client
Referenced by CPVRRecording(), Directory(), operator==(), Reset(), Serialize(), Update(), and UpdatePath().
m_strProviderName
std::string PVR::CPVRRecording::m_strProviderName private
name of the provider this recording is from
Referenced by CPVRRecording(), operator==(), ProviderName(), Reset(), and Update().
m_strRecordingId
std::string PVR::CPVRRecording::m_strRecordingId private
unique ID of the recording on the client
Referenced by ClientRecordingID(), CPVRRecording(), operator==(), Reset(), Update(), and UpdatePath().
m_thumbnailPath
CPVRCachedImage PVR::CPVRRecording::m_thumbnailPath private
thumbnail path
Referenced by ClientThumbnailPath(), operator==(), ThumbnailPath(), and Update().
m_titleExtraInfo
std::string PVR::CPVRRecording::m_titleExtraInfo private
title extra info
Referenced by CPVRRecording(), operator==(), Reset(), Serialize(), TitleExtraInfo(), and Update().
The documentation for this class was generated from the following files:
PVRRecording.h
PVRRecording.cpp