Kodi Documentation: CInfoLoader Class Reference
CInfoLoader Class Reference abstract
#include <InfoLoader.h>
Public Member Functions
CInfoLoader (unsigned int timeToRefresh=5 *60 *1000)
~CInfoLoader () override
std::string GetInfo (int info)
void Refresh ()
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
Public Member Functions inherited from IJobCallback
virtual ~IJobCallback ()=default
Destructor for job call back objects.
virtual void OnJobAbort (unsigned int jobID, CJob *job)
An optional callback function used when a job will be aborted.
virtual void OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob *job)
An optional callback function that a job may call while processing.
Protected Member Functions
virtual CJob * GetJob () const =0
virtual std::string TranslateInfo (int info) const
virtual std::string BusyInfo (int info) const
Private Attributes
unsigned int m_refreshTime
unsigned int m_timeToRefresh
bool m_busy
Constructor & Destructor Documentation
CInfoLoader()
CInfoLoader::CInfoLoader (unsigned int timeToRefresh = 5 * 60 * 1000) explicit
References m_busy, m_refreshTime, and m_timeToRefresh.
~CInfoLoader()
CInfoLoader::~CInfoLoader () override default
Member Function Documentation
BusyInfo()
std::string CInfoLoader::BusyInfo (int info) const protected virtual
Reimplemented in CWeatherManager.
References g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CWeatherManager::BusyInfo(), and GetInfo().
GetInfo()
std::string CInfoLoader::GetInfo (int info)
References BusyInfo(), CTimeUtils::GetFrameTime(), GetJob(), CServiceBroker::GetJobManager(), m_busy, m_refreshTime, and TranslateInfo().
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CWeatherGUIInfo::GetLabel(), CWeatherManager::IsFetched(), and CWeatherManager::OnJobComplete().
GetJob()
virtual CJob * CInfoLoader::GetJob () const protected pure virtual
Implemented in CSysInfo, and CWeatherManager.
Referenced by GetInfo().
OnJobComplete()
void CInfoLoader::OnJobComplete (unsigned int jobID, bool success, CJob * job) override virtual
The callback used when a job completes.
OnJobComplete is called at the completion of the job's DoWork() function, and is used to return information to the caller on the result of the job. On returning form this function the CJobManager will destroy this job.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
success the result from the DoWork call
job the job that has been processed. The job will be destroyed after this function returns
See also
CJobManager and CJob
Implements IJobCallback.
Reimplemented in CSysInfo, and CWeatherManager.
References CTimeUtils::GetFrameTime(), m_busy, m_refreshTime, and m_timeToRefresh.
Referenced by CSysInfo::OnJobComplete(), and CWeatherManager::OnJobComplete().
Refresh()
void CInfoLoader::Refresh ()
References CTimeUtils::GetFrameTime(), and m_refreshTime.
Referenced by CProfileManager::FinalizeLoadProfile(), CApplication::Initialize(), CGUIWindowWeather::OnMessage(), CWeatherManager::OnSettingAction(), CWeatherManager::OnSettingChanged(), CPowerManager::OnWake(), CLangInfo::SetLanguage(), CGUIWindowWeather::SetLocation(), CLangInfo::SetSpeedUnit(), CLangInfo::SetTemperatureUnit(), and CGUIWindowWeather::UpdateLocations().
TranslateInfo()
std::string CInfoLoader::TranslateInfo (int info) const protected virtual
Reimplemented in CSysInfo, and CWeatherManager.
Referenced by GetInfo().
Member Data Documentation
m_busy
bool CInfoLoader::m_busy private
Referenced by CInfoLoader(), GetInfo(), and OnJobComplete().
m_refreshTime
unsigned int CInfoLoader::m_refreshTime private
Referenced by CInfoLoader(), GetInfo(), OnJobComplete(), and Refresh().
m_timeToRefresh
unsigned int CInfoLoader::m_timeToRefresh private
Referenced by CInfoLoader(), and OnJobComplete().
The documentation for this class was generated from the following files:
InfoLoader.h
InfoLoader.cpp