Kodi Documentation: TestMediaSourceSettings.cpp File Reference
TestMediaSourceSettings.cpp File Reference
#include "MediaSource.h"
#include "filesystem/File.h"
#include "settings/MediaSourceSettings.h"
#include "test/TestUtils.h"
#include "utils/XBMCTinyXML2.h"
#include "utils/XMLUtils.h"
#include <gtest/gtest.h>
Functions
TEST (TestMediaSourceSettings, LoadString)
TEST (TestMediaSourceSettings, SaveString)
TEST (TestMediaSourceSettings, GetSource)
TEST (TestMediaSourceSettings, SetSources)
Function Documentation
TEST() [1/4]
TEST (TestMediaSourceSettings , GetSource)
TEST() [2/4]
TEST (TestMediaSourceSettings , LoadString)
References EXPECT_EQ(), EXPECT_TRUE(), CMediaSourceSettings::GetInstance(), CMediaSourceSettings::GetSources(), CMediaSourceSettings::Load(), and XBMC_REF_FILE_PATH.
TEST() [3/4]
TEST (TestMediaSourceSettings , SaveString)
References CMediaSourceSettings::Clear(), EXPECT_EQ(), EXPECT_TRUE(), CMediaSourceSettings::GetInstance(), CMediaSourceSettings::GetSources(), CMediaSourceSettings::Load(), CMediaSourceSettings::Save(), XBMC_CREATETEMPFILE, XBMC_REF_FILE_PATH, XBMC_TEMPFILEPATH, and xmlfile.
TEST() [4/4]
TEST (TestMediaSourceSettings , SetSources)