Kodi Documentation: CRenderManager Class Reference
CRenderManager Class Reference
#include <RenderManager.h>
Classes
struct CClockSync
struct SPresent
Public Member Functions
CRenderManager (CDVDClock &clock, IRenderMsg *player)
virtual ~CRenderManager ()
void GetVideoRect (CRect &source, CRect &dest, CRect &view) const
float GetAspectRatio () const
unsigned int GetOrientation () const
void FrameMove ()
void FrameWait (std::chrono::milliseconds duration)
void Render (bool clear, DWORD flags=0, DWORD alpha=255, bool gui=true)
bool IsVideoLayer ()
RESOLUTION GetResolution ()
void UpdateResolution ()
void TriggerUpdateResolution (float fps, int width, int height, std::string &stereomode)
void SetViewMode (int iViewMode)
void PreInit ()
void UnInit ()
bool Flush (bool wait, bool saveBuffers)
bool IsConfigured () const
void ToggleDebug ()
void ToggleDebugVideo ()
void SetSubtitleVerticalPosition (const int value, bool save)
Set the subtitle vertical position, it depends on current screen resolution.
unsigned int AllocRenderCapture ()
void ReleaseRenderCapture (unsigned int captureId)
void StartRenderCapture (unsigned int captureId, unsigned int width, unsigned int height, int flags)
bool RenderCaptureGetPixels (unsigned int captureId, unsigned int millis, uint8_t *buffer, unsigned int size)
bool Supports (ERENDERFEATURE feature) const
bool Supports (ESCALINGMETHOD method) const
int GetSkippedFrames ()
bool Configure (const VideoPicture &picture, float fps, unsigned int orientation, int buffers=0)
bool AddVideoPicture (const VideoPicture &picture, volatile std::atomic_bool &bStop, EINTERLACEMETHOD deintMethod, bool wait)
void AddOverlay (std::shared_ptr< CDVDOverlay > o, double pts)
void ShowVideo (bool enable)
int WaitForBuffer (volatile std::atomic_bool &bStop, std::chrono::milliseconds timeout=std::chrono::milliseconds(100))
bool GetStats (int &lateframes, double &pts, int &queued, int &discard)
void DiscardBuffer ()
void SetDelay (int delay)
int GetDelay ()
void SetVideoSettings (const CVideoSettings &settings)
Protected Types
enum EPRESENTSTEP {
PRESENT_IDLE = 0 , PRESENT_FLIP , PRESENT_FRAME , PRESENT_FRAME2 ,
PRESENT_READY
}
enum EPRESENTMETHOD { PRESENT_METHOD_SINGLE = 0 , PRESENT_METHOD_BLEND , PRESENT_METHOD_BOB }
enum ERENDERSTATE { STATE_UNCONFIGURED = 0 , STATE_CONFIGURING , STATE_CONFIGURED }
Protected Member Functions
void PresentSingle (bool clear, DWORD flags, DWORD alpha)
void PresentFields (bool clear, DWORD flags, DWORD alpha)
void PresentBlend (bool clear, DWORD flags, DWORD alpha)
void PrepareNextRender ()
bool IsPresenting ()
bool IsGuiLayer ()
bool Configure ()
void CreateRenderer ()
void DeleteRenderer ()
void ManageCaptures ()
void UpdateLatencyTweak ()
void CheckEnableClockSync ()
void RenderCapture (CRenderCapture *capture)
void RemoveCaptures ()
Protected Attributes
CBaseRenderer * m_pRenderer = nullptr
OVERLAY::CRenderer m_overlays
CDebugRenderer m_debugRenderer
CCriticalSection m_statelock
CCriticalSection m_presentlock
CCriticalSection m_datalock
bool m_bTriggerUpdateResolution = false
bool m_bRenderGUI = true
bool m_renderedOverlay = false
bool m_renderDebug = false
bool m_renderDebugVideo = false
XbmcThreads::EndTime m_debugTimer
std::atomic_bool m_showVideo = {false}
ERENDERSTATE m_renderState = STATE_UNCONFIGURED
CEvent m_stateEvent
double m_latencyTweak = 0.0
double m_displayLatency = 0.0
Display latency updated in PrepareNextRender in DVD clock units, includes m_latencyTweak.
std::atomic_int m_videoDelay = {}
int m_QueueSize = 2
int m_QueueSkip = 0
struct CRenderManager::SPresent m_Queue [NUM_BUFFERS]
std::deque< int > m_free
std::deque< int > m_queued
std::deque< int > m_discard
std::unique_ptr< VideoPicture > m_pConfigPicture
unsigned int m_width = 0
unsigned int m_height = 0
unsigned int m_dwidth = 0
unsigned int m_dheight = 0
float m_fps = 0.0
unsigned int m_orientation = 0
int m_NumberBuffers = 0
std::string m_stereomode
int m_lateframes = -1
double m_presentpts = 0.0
EPRESENTSTEP m_presentstep = PRESENT_IDLE
XbmcThreads::EndTime m_presentTimer
bool m_forceNext = false
int m_presentsource = 0
int m_presentsourcePast = -1
XbmcThreads::ConditionVariable m_presentevent
CEvent m_flushEvent
CEvent m_initEvent
CDVDClock & m_dvdClock
IRenderMsg * m_playerPort
CClockSync m_clockSync
CCriticalSection m_captCritSect
std::map< unsigned int, CRenderCapture * > m_captures
unsigned int m_captureWaitCounter = 0
bool m_hasCaptures = false
Static Protected Attributes
static unsigned int m_nextCaptureId = 0
Member Enumeration Documentation
EPRESENTMETHOD
enum CRenderManager::EPRESENTMETHOD protected
Enumerator
PRESENT_METHOD_SINGLE
PRESENT_METHOD_BLEND
PRESENT_METHOD_BOB
EPRESENTSTEP
enum CRenderManager::EPRESENTSTEP protected
Enumerator
PRESENT_IDLE
PRESENT_FLIP
PRESENT_FRAME
PRESENT_FRAME2
PRESENT_READY
ERENDERSTATE
enum CRenderManager::ERENDERSTATE protected
Enumerator
STATE_UNCONFIGURED
STATE_CONFIGURING
STATE_CONFIGURED
Constructor & Destructor Documentation
CRenderManager()
CRenderManager::CRenderManager (CDVDClock & clock, IRenderMsg * player)
~CRenderManager()
CRenderManager::~CRenderManager () virtual
References m_pRenderer.
Member Function Documentation
AddOverlay()
void CRenderManager::AddOverlay (std::shared_ptr< CDVDOverlay > o, double pts)
References OVERLAY::CRenderer::AddOverlay(), m_datalock, m_free, m_overlays, and m_presentlock.
Referenced by CVideoPlayerVideo::ProcessOverlays().
AddVideoPicture()
bool CRenderManager::AddVideoPicture (const VideoPicture & picture, volatile std::atomic_bool & bStop, EINTERLACEMETHOD deintMethod, bool wait)
References CBaseRenderer::AddVideoPicture(), DVP_FLAG_INTERLACED, DVP_FLAG_TOP_FIELD_FIRST, FS_BOT, FS_NONE, FS_TOP, VideoPicture::iFlags, index(), CLog::Log(), LOGWARNING, m_datalock, m_discard, m_forceNext, m_free, m_playerPort, m_pRenderer, m_presentevent, m_presentlock, m_presentstep, m_Queue, m_queued, XbmcThreads::ConditionVariable::notifyAll(), PRESENT_IDLE, PRESENT_METHOD_BLEND, PRESENT_METHOD_BOB, PRESENT_METHOD_SINGLE, PRESENT_READY, CRenderManager::SPresent::presentfield, CRenderManager::SPresent::presentmethod, VideoPicture::pts, CRenderManager::SPresent::pts, IRenderMsg::UpdateRenderBuffers(), VS_INTERLACEMETHOD_NONE, VS_INTERLACEMETHOD_RENDER_BLEND, VS_INTERLACEMETHOD_RENDER_BOB, XbmcThreads::ConditionVariable::wait(), and CBaseRenderer::WantsDoublePass().
Referenced by CVideoPlayerVideo::OutputPicture().
AllocRenderCapture()
unsigned int CRenderManager::AllocRenderCapture ()
References CBaseRenderer::GetRenderCapture(), m_captures, m_nextCaptureId, and m_pRenderer.
Referenced by CVideoPlayer::RenderCaptureAlloc().
CheckEnableClockSync()
void CRenderManager::CheckEnableClockSync () protected
References CDVDClock::GetClockInfo(), CGraphicContext::GetFPS(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), m_clockSync, m_dvdClock, CRenderManager::CClockSync::m_enabled, m_fps, m_playerPort, CDVDClock::SetVsyncAdjust(), and IRenderMsg::UpdateClockSync().
Referenced by FrameMove().
Configure() [1/2]
bool CRenderManager::Configure () protected
References CBaseRenderer::Configure(), CreateRenderer(), DeleteRenderer(), DVD_NOPTS_VALUE, CBaseRenderer::GetRenderInfo(), IRenderMsg::GetVideoSettings(), CBaseRenderer::IsGuiLayer(), CLog::Log(), LOGDEBUG, LOGWARNING, m_bRenderGUI, m_bTriggerUpdateResolution, m_clockSync, m_datalock, m_discard, m_dvdClock, m_fps, m_free, m_lateframes, m_NumberBuffers, m_orientation, m_overlays, m_pConfigPicture, m_playerPort, m_pRenderer, m_presentevent, m_presentlock, m_presentpts, m_presentsource, m_presentsourcePast, m_presentstep, m_queued, m_QueueSize, m_renderDebug, m_renderedOverlay, m_renderState, m_stateEvent, m_statelock, m_stereomode, CRenderInfo::max_buffer_size, XbmcThreads::ConditionVariable::notifyAll(), PRESENT_IDLE, OVERLAY::CRenderer::Reset(), CRenderManager::CClockSync::Reset(), CEvent::Set(), CBaseRenderer::SetBufferSize(), OVERLAY::CRenderer::SetStereoMode(), CBaseRenderer::SetVideoSettings(), CDVDClock::SetVsyncAdjust(), STATE_CONFIGURED, STATE_UNCONFIGURED, CBaseRenderer::Update(), IRenderMsg::UpdateGuiRender(), IRenderMsg::UpdateRenderInfo(), IRenderMsg::UpdateVideoRender(), and IRenderMsg::VideoParamsChange().
Referenced by FrameMove().
Configure() [2/2]
bool CRenderManager::Configure (const VideoPicture & picture, float fps, unsigned int orientation, int buffers = 0)
References CBaseRenderer::ConfigChanged(), VideoPicture::iDisplayHeight, VideoPicture::iDisplayWidth, VideoPicture::iHeight, VideoPicture::iWidth, CLog::Log(), LOGDEBUG, LOGWARNING, m_bRenderGUI, m_clockSync, m_dheight, m_dvdClock, m_dwidth, m_forceNext, m_fps, m_height, m_NumberBuffers, m_orientation, m_pConfigPicture, m_pRenderer, m_presentevent, m_presentlock, m_presentstep, m_renderState, m_stateEvent, m_statelock, m_stereomode, m_width, XbmcThreads::ConditionVariable::notifyAll(), PRESENT_IDLE, PRESENT_READY, CRenderManager::CClockSync::Reset(), CEvent::Reset(), CDVDClock::SetVsyncAdjust(), STATE_CONFIGURED, STATE_CONFIGURING, VideoPicture::stereoMode, XbmcThreads::ConditionVariable::wait(), and CEvent::Wait().
Referenced by CVideoPlayerVideo::OutputPicture().
CreateRenderer()
void CRenderManager::CreateRenderer () protected
References VIDEOPLAYER::CRendererFactory::CreateRenderer(), VIDEOPLAYER::CRendererFactory::GetRenderers(), m_pConfigPicture, and m_pRenderer.
Referenced by Configure(), and PreInit().
DeleteRenderer()
void CRenderManager::DeleteRenderer () protected
References CLog::Log(), LOGDEBUG, and m_pRenderer.
Referenced by Configure(), and UnInit().
DiscardBuffer()
void CRenderManager::DiscardBuffer ()
Video player call this on flush in oder to discard any queued frames
References m_discard, m_presentevent, m_presentlock, m_presentstep, m_queued, XbmcThreads::ConditionVariable::notifyAll(), PRESENT_IDLE, and PRESENT_READY.
Referenced by CVideoPlayerVideo::Process(), CVideoPlayerVideo::ProcessDecoderOutput(), ShowVideo(), and WaitForBuffer().
Flush()
bool CRenderManager::Flush (bool wait, bool saveBuffers)
References CDebugRenderer::Flush(), OVERLAY::CRenderer::Flush(), CBaseRenderer::Flush(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, LOGERROR, m_datalock, m_debugRenderer, m_discard, m_flushEvent, m_free, m_overlays, m_pRenderer, m_presentlock, m_presentsource, m_presentsourcePast, m_presentstep, m_queued, m_QueueSize, m_statelock, PRESENT_IDLE, CEvent::Reset(), CEvent::Set(), TMSG_RENDERER_FLUSH, and CEvent::Wait().
Referenced by CVideoPlayer::FlushRenderer(), CVideoPlayer::HandleMessages(), and CVideoPlayer::OnExit().
FrameMove()
void CRenderManager::FrameMove ()
References CheckEnableClockSync(), Configure(), FrameWait(), IsGuiLayer(), m_bRenderGUI, m_discard, m_free, m_overlays, m_playerPort, m_pRenderer, m_presentevent, m_presentlock, m_presentstep, m_presentTimer, m_queued, m_renderState, m_statelock, ManageCaptures(), CBaseRenderer::NeedBuffer(), XbmcThreads::ConditionVariable::notifyAll(), PrepareNextRender(), PRESENT_FLIP, PRESENT_FRAME, PRESENT_IDLE, PRESENT_READY, OVERLAY::CRenderer::Release(), CBaseRenderer::ReleaseBuffer(), STATE_CONFIGURING, STATE_UNCONFIGURED, IRenderMsg::UpdateGuiRender(), UpdateLatencyTweak(), IRenderMsg::UpdateRenderBuffers(), and UpdateResolution().
Referenced by CVideoPlayer::FrameMove().
FrameWait()
void CRenderManager::FrameWait (std::chrono::milliseconds duration)
References m_presentevent, m_presentlock, m_presentstep, PRESENT_IDLE, and XbmcThreads::ConditionVariable::wait().
Referenced by FrameMove().
GetAspectRatio()
float CRenderManager::GetAspectRatio () const
References CBaseRenderer::GetAspectRatio(), m_pRenderer, and m_statelock.
Referenced by CVideoPlayer::GetRenderAspectRatio().
GetDelay()
int CRenderManager::GetDelay () inline
References m_videoDelay.
Referenced by CVideoPlayer::GetAVDelay(), and CVideoPlayerVideo::ProcessDecoderOutput().
GetOrientation()
unsigned int CRenderManager::GetOrientation () const
References CBaseRenderer::GetOrientation(), m_pRenderer, and m_statelock.
Referenced by CVideoPlayer::GetOrientation().
GetResolution()
RESOLUTION CRenderManager::GetResolution ()
References ADJUST_REFRESHRATE_OFF, CResolutionUtils::ChooseBestResolution(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetSettingsComponent(), CGraphicContext::GetVideoResolution(), CServiceBroker::GetWinSystem(), m_fps, m_height, m_renderState, m_statelock, m_stereomode, m_width, CSettings::SETTING_VIDEOPLAYER_ADJUSTREFRESHRATE, and STATE_UNCONFIGURED.
GetSkippedFrames()
int CRenderManager::GetSkippedFrames () inline
References m_QueueSkip.
Referenced by CVideoPlayerVideo::GetPlayerInfo().
GetStats()
bool CRenderManager::GetStats (int & lateframes, double & pts, int & queued, int & discard)
Can be called by player for lateness detection. This is done best by looking at the end of the queue.
References m_discard, m_lateframes, m_presentlock, m_presentpts, and m_queued.
Referenced by CVideoPlayerVideo::CalcDropRequirement(), CVideoPlayerVideo::GetCurrentPts(), and CVideoPlayerVideo::OutputPicture().
GetVideoRect()
void CRenderManager::GetVideoRect (CRect & source, CRect & dest, CRect & view) const
References CBaseRenderer::GetVideoRect(), m_pRenderer, and m_statelock.
Referenced by CVideoPlayer::GetRects(), CVideoPlayer::GetVideoStreamInfo(), and CVideoPlayer::OnAction().
IsConfigured()
bool CRenderManager::IsConfigured () const
References m_renderState, m_statelock, and STATE_CONFIGURED.
Referenced by IsPresenting(), and CVideoPlayer::IsRenderingVideo().
IsGuiLayer()
bool CRenderManager::IsGuiLayer () protected
References OVERLAY::CRenderer::HasOverlay(), CBaseRenderer::IsGuiLayer(), IsPresenting(), m_debugTimer, m_overlays, m_pRenderer, m_presentsource, m_renderDebug, m_renderedOverlay, and m_statelock.
Referenced by FrameMove().
IsPresenting()
bool CRenderManager::IsPresenting () protected
References IsConfigured(), m_presentlock, and m_presentTimer.
Referenced by IsGuiLayer().
IsVideoLayer()
bool CRenderManager::IsVideoLayer ()
References CBaseRenderer::IsGuiLayer(), m_pRenderer, and m_statelock.
ManageCaptures()
void CRenderManager::ManageCaptures () protected
References CAPTUREFLAG_CONTINUOUS, CAPTUREFLAG_IMMEDIATELY, CAPTURESTATE_DONE, CAPTURESTATE_FAILED, CAPTURESTATE_NEEDSDELETE, CAPTURESTATE_NEEDSREADOUT, CAPTURESTATE_NEEDSRENDER, CRenderCapture::GetEvent(), CRenderCapture::GetFlags(), CRenderCapture::GetState(), CRenderCapture::IsAsync(), m_captCritSect, m_captures, m_hasCaptures, CRenderCapture::ReadOut(), RenderCapture(), CEvent::Set(), CRenderCapture::SetState(), and CRenderCapture::SetUserState().
Referenced by FrameMove().
PreInit()
void CRenderManager::PreInit ()
References CreateRenderer(), CServiceBroker::GetAppMessenger(), CLog::Log(), LOGERROR, m_bRenderGUI, m_initEvent, m_pRenderer, m_presentstep, m_QueueSize, m_QueueSkip, m_renderState, m_statelock, PRESENT_IDLE, CEvent::Reset(), CEvent::Set(), STATE_UNCONFIGURED, TMSG_RENDERER_PREINIT, UpdateLatencyTweak(), and CEvent::Wait().
Referenced by CVideoPlayer::OpenFile().
PrepareNextRender()
void CRenderManager::PrepareNextRender () protected
References DVD_MSEC_TO_TIME(), DVD_TIME_BASE, err(), CDVDClock::GetClock(), CDVDClock::GetClockSpeed(), CGraphicContext::GetFPS(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGAVTIMING, LOGDEBUG, LOGERROR, m_clockSync, m_discard, m_displayLatency, m_dvdClock, CRenderManager::CClockSync::m_enabled, CRenderManager::CClockSync::m_errCount, CRenderManager::CClockSync::m_error, m_forceNext, m_fps, m_free, m_lateframes, m_latencyTweak, m_playerPort, m_presentevent, m_presentpts, m_presentsource, m_presentsourcePast, m_presentstep, m_Queue, m_queued, m_QueueSkip, m_showVideo, CRenderManager::CClockSync::m_syncOffset, m_videoDelay, XbmcThreads::ConditionVariable::notifyAll(), PRESENT_FLIP, PRESENT_IDLE, CRenderManager::SPresent::pts, CDVDClock::SetVsyncAdjust(), and IRenderMsg::UpdateRenderBuffers().
Referenced by FrameMove().
PresentBlend()
void CRenderManager::PresentBlend (bool clear, DWORD flags, DWORD alpha) protected
References FS_BOT, m_pRenderer, m_presentsource, m_presentsourcePast, m_Queue, CRenderManager::SPresent::presentfield, RENDER_FLAG_BOT, RENDER_FLAG_NOOSD, RENDER_FLAG_TOP, and CBaseRenderer::RenderUpdate().
Referenced by Render().
PresentFields()
void CRenderManager::PresentFields (bool clear, DWORD flags, DWORD alpha) protected
References FS_BOT, FS_TOP, m_pRenderer, m_presentsource, m_presentsourcePast, m_presentstep, m_Queue, PRESENT_FRAME, CRenderManager::SPresent::presentfield, RENDER_FLAG_BOT, RENDER_FLAG_FIELD0, RENDER_FLAG_FIELD1, RENDER_FLAG_TOP, and CBaseRenderer::RenderUpdate().
Referenced by Render().
PresentSingle()
void CRenderManager::PresentSingle (bool clear, DWORD flags, DWORD alpha) protected
References FS_BOT, FS_TOP, m_pRenderer, m_presentsource, m_presentsourcePast, m_Queue, CRenderManager::SPresent::presentfield, RENDER_FLAG_BOT, RENDER_FLAG_TOP, and CBaseRenderer::RenderUpdate().
Referenced by Render().
ReleaseRenderCapture()
void CRenderManager::ReleaseRenderCapture (unsigned int captureId)
References CAPTURESTATE_NEEDSDELETE, m_captCritSect, and m_captures.
Referenced by CVideoPlayer::RenderCaptureRelease().
RemoveCaptures()
void CRenderManager::RemoveCaptures () protected
References m_captCritSect, m_captures, m_captureWaitCounter, and KODI::TIME::Sleep().
Referenced by UnInit().
Render()
void CRenderManager::Render (bool clear, DWORD flags = 0, DWORD alpha = 255, bool gui = true)
References DVD_TIME_TO_MSEC(), CDVDClock::GetClockInfo(), CWinSystemBase::GetDebugInfo(), CBaseRenderer::GetDebugInfo(), IRenderMsg::GetDebugInfo(), CBaseRenderer::GetVideoRect(), CServiceBroker::GetWinSystem(), OVERLAY::CRenderer::HasOverlay(), CBaseRenderer::IsGuiLayer(), m_clockSync, m_debugRenderer, m_debugTimer, m_displayLatency, m_dvdClock, m_overlays, m_playerPort, m_pRenderer, m_presentevent, m_presentlock, m_presentsource, m_presentstep, m_Queue, m_queued, m_renderDebug, m_renderDebugVideo, m_renderedOverlay, m_renderState, m_statelock, CRenderManager::CClockSync::m_syncOffset, XbmcThreads::ConditionVariable::notifyAll(), PRESENT_FRAME, PRESENT_FRAME2, PRESENT_IDLE, PRESENT_METHOD_BLEND, PRESENT_METHOD_BOB, PRESENT_READY, PresentBlend(), PresentFields(), CRenderManager::SPresent::presentmethod, PresentSingle(), CDebugRenderer::Render(), OVERLAY::CRenderer::Render(), CDebugRenderer::SetInfo(), OVERLAY::CRenderer::SetVideoRect(), STATE_CONFIGURED, and CBaseRenderer::Update().
Referenced by CVideoPlayer::Render().
RenderCapture()
void CRenderManager::RenderCapture (CRenderCapture * capture) protected
References CAPTURESTATE_FAILED, m_pRenderer, m_presentsource, CBaseRenderer::RenderCapture(), and CRenderCapture::SetState().
Referenced by ManageCaptures(), and StartRenderCapture().
RenderCaptureGetPixels()
bool CRenderManager::RenderCaptureGetPixels (unsigned int captureId, unsigned int millis, uint8_t * buffer, unsigned int size)
References CAPTURESTATE_DONE, m_captCritSect, m_captures, and m_captureWaitCounter.
Referenced by CVideoPlayer::RenderCaptureGetPixels().
SetDelay()
void CRenderManager::SetDelay (int delay) inline
References m_videoDelay.
Referenced by CVideoPlayer::SetAVDelay(), and CVideoPlayer::SetVideoSettings().
SetSubtitleVerticalPosition()
void CRenderManager::SetSubtitleVerticalPosition (const int value, bool save)
Set the subtitle vertical position, it depends on current screen resolution.
Parameters
value The subtitle position in pixels
save If true, the value will be saved to resolution info
References m_overlays, OVERLAY::CRenderer::SetSubtitleVerticalPosition(), and value.
Referenced by CVideoPlayer::SetSubtitleVerticalPosition(), and CVideoPlayer::SetVideoSettings().
SetVideoSettings()
void CRenderManager::SetVideoSettings (const CVideoSettings & settings)
References m_pRenderer, m_statelock, and CBaseRenderer::SetVideoSettings().
Referenced by CVideoPlayer::SetRenderViewMode(), and CVideoPlayer::SetVideoSettings().
SetViewMode()
void CRenderManager::SetViewMode (int iViewMode)
References m_playerPort, m_pRenderer, m_statelock, CBaseRenderer::SetViewMode(), and IRenderMsg::VideoParamsChange().
Referenced by CVideoPlayer::SetRenderViewMode().
ShowVideo()
void CRenderManager::ShowVideo (bool enable)
References DiscardBuffer(), and m_showVideo.
Referenced by CVideoPlayerVideo::OpenStream(), and CVideoPlayerVideo::Process().
StartRenderCapture()
void CRenderManager::StartRenderCapture (unsigned int captureId, unsigned int width, unsigned int height, int flags)
References CAPTUREFLAG_IMMEDIATELY, CAPTURESTATE_NEEDSRENDER, CAPTURESTATE_WORKING, CServiceBroker::GetAppMessenger(), CRenderCapture::GetEvent(), CRenderCapture::GetState(), CLog::Log(), LOGERROR, m_captCritSect, m_captures, m_hasCaptures, RenderCapture(), CEvent::Reset(), CEvent::Set(), CRenderCapture::SetFlags(), CRenderCapture::SetHeight(), CRenderCapture::SetState(), CRenderCapture::SetUserState(), and CRenderCapture::SetWidth().
Referenced by CVideoPlayer::RenderCapture().
Supports() [1/2]
bool CRenderManager::Supports (ERENDERFEATURE feature) const
References m_pRenderer, m_statelock, and CBaseRenderer::Supports().
Referenced by CVideoPlayerVideo::Process(), CVideoPlayer::Supports(), and CVideoPlayer::Supports().
Supports() [2/2]
bool CRenderManager::Supports (ESCALINGMETHOD method) const
References m_pRenderer, m_statelock, and CBaseRenderer::Supports().
ToggleDebug()
void CRenderManager::ToggleDebug ()
References CDebugRenderer::Dispose(), CDebugRenderer::Initialize(), m_debugRenderer, m_debugTimer, m_renderDebug, and m_renderDebugVideo.
Referenced by CVideoPlayer::OnAction().
ToggleDebugVideo()
void CRenderManager::ToggleDebugVideo ()
References CDebugRenderer::Dispose(), CDebugRenderer::Initialize(), m_debugRenderer, m_debugTimer, m_renderDebug, and m_renderDebugVideo.
Referenced by CVideoPlayer::OnAction().
TriggerUpdateResolution()
void CRenderManager::TriggerUpdateResolution (float fps, int width, int height, std::string & stereomode)
References m_bTriggerUpdateResolution, m_fps, m_height, m_stereomode, and m_width.
Referenced by CVideoPlayer::OpenVideoStream(), and CVideoPlayer::TriggerUpdateResolution().
UnInit()
void CRenderManager::UnInit ()
References DeleteRenderer(), CDebugRenderer::Dispose(), CServiceBroker::GetAppMessenger(), CLog::Log(), LOGERROR, m_bRenderGUI, m_debugRenderer, m_height, m_initEvent, m_overlays, m_renderState, m_statelock, m_width, RemoveCaptures(), CEvent::Reset(), CEvent::Set(), STATE_UNCONFIGURED, TMSG_RENDERER_UNINIT, OVERLAY::CRenderer::UnInit(), and CEvent::Wait().
Referenced by CVideoPlayer::CloseFile().
UpdateLatencyTweak()
void CRenderManager::UpdateLatencyTweak () protected
References CGraphicContext::GetFPS(), CWinSystemBase::GetGfxContext(), CWinSystemBase::GetOSHDRStatus(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), HDR_ON, m_latencyTweak, and RES_WINDOW.
Referenced by FrameMove(), PreInit(), and UpdateResolution().
UpdateResolution()
void CRenderManager::UpdateResolution ()
References ADJUST_REFRESHRATE_OFF, CResolutionUtils::ChooseBestResolution(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), m_bTriggerUpdateResolution, m_fps, m_height, m_playerPort, m_pRenderer, m_stereomode, m_width, CSettings::SETTING_VIDEOPLAYER_ADJUSTREFRESHRATE, CGraphicContext::SetVideoResolution(), CBaseRenderer::Update(), UpdateLatencyTweak(), and IRenderMsg::VideoParamsChange().
Referenced by FrameMove().
WaitForBuffer()
int CRenderManager::WaitForBuffer (volatile std::atomic_bool & bStop, std::chrono::milliseconds timeout = std::chrono::milliseconds(100))
If player uses buffering it has to wait for a buffer before it calls AddVideoPicture and AddOverlay. It waits for max 50 ms before it returns -1 in case no buffer is available. Player may call this in a loop and decides by itself when it wants to drop a frame.
References DiscardBuffer(), g_application, CDVDClock::GetClock(), m_bRenderGUI, m_discard, m_dvdClock, m_free, m_overlays, m_presentevent, m_presentlock, m_Queue, m_queued, CRenderManager::SPresent::pts, OVERLAY::CRenderer::Release(), and XbmcThreads::ConditionVariable::wait().
Referenced by CVideoPlayerVideo::OutputPicture().
Member Data Documentation
m_bRenderGUI
bool CRenderManager::m_bRenderGUI = true protected
Referenced by Configure(), Configure(), FrameMove(), PreInit(), UnInit(), and WaitForBuffer().
m_bTriggerUpdateResolution
bool CRenderManager::m_bTriggerUpdateResolution = false protected
Referenced by Configure(), TriggerUpdateResolution(), and UpdateResolution().
m_captCritSect
CCriticalSection CRenderManager::m_captCritSect protected
Referenced by ManageCaptures(), ReleaseRenderCapture(), RemoveCaptures(), RenderCaptureGetPixels(), and StartRenderCapture().
m_captures
std::map<unsigned int, CRenderCapture*> CRenderManager::m_captures protected
Referenced by AllocRenderCapture(), ManageCaptures(), ReleaseRenderCapture(), RemoveCaptures(), RenderCaptureGetPixels(), and StartRenderCapture().
m_captureWaitCounter
unsigned int CRenderManager::m_captureWaitCounter = 0 protected
Referenced by RemoveCaptures(), and RenderCaptureGetPixels().
m_clockSync
CClockSync CRenderManager::m_clockSync protected
Referenced by CheckEnableClockSync(), Configure(), Configure(), PrepareNextRender(), and Render().
m_datalock
CCriticalSection CRenderManager::m_datalock protected
Referenced by AddOverlay(), AddVideoPicture(), Configure(), and Flush().
m_debugRenderer
CDebugRenderer CRenderManager::m_debugRenderer protected
Referenced by Flush(), Render(), ToggleDebug(), ToggleDebugVideo(), and UnInit().
m_debugTimer
XbmcThreads::EndTime CRenderManager::m_debugTimer protected
Referenced by IsGuiLayer(), Render(), ToggleDebug(), and ToggleDebugVideo().
m_dheight
unsigned int CRenderManager::m_dheight = 0 protected
Referenced by Configure().
m_discard
std::deque<int> CRenderManager::m_discard protected
Referenced by AddVideoPicture(), Configure(), DiscardBuffer(), Flush(), FrameMove(), GetStats(), PrepareNextRender(), and WaitForBuffer().
m_displayLatency
double CRenderManager::m_displayLatency = 0.0 protected
Display latency updated in PrepareNextRender in DVD clock units, includes m_latencyTweak.
Referenced by PrepareNextRender(), and Render().
m_dvdClock
CDVDClock& CRenderManager::m_dvdClock protected
Referenced by CheckEnableClockSync(), Configure(), Configure(), PrepareNextRender(), Render(), and WaitForBuffer().
m_dwidth
unsigned int CRenderManager::m_dwidth = 0 protected
Referenced by Configure().
m_flushEvent
CEvent CRenderManager::m_flushEvent protected
Referenced by Flush().
m_forceNext
bool CRenderManager::m_forceNext = false protected
Referenced by AddVideoPicture(), Configure(), and PrepareNextRender().
m_fps
float CRenderManager::m_fps = 0.0 protected
Referenced by CheckEnableClockSync(), Configure(), Configure(), GetResolution(), PrepareNextRender(), TriggerUpdateResolution(), and UpdateResolution().
m_free
std::deque<int> CRenderManager::m_free protected
Referenced by AddOverlay(), AddVideoPicture(), Configure(), Flush(), FrameMove(), PrepareNextRender(), and WaitForBuffer().
m_hasCaptures
bool CRenderManager::m_hasCaptures = false protected
Referenced by ManageCaptures(), and StartRenderCapture().
m_height
unsigned int CRenderManager::m_height = 0 protected
Referenced by Configure(), GetResolution(), TriggerUpdateResolution(), UnInit(), and UpdateResolution().
m_initEvent
CEvent CRenderManager::m_initEvent protected
Referenced by PreInit(), and UnInit().
m_lateframes
int CRenderManager::m_lateframes = -1 protected
Referenced by Configure(), GetStats(), and PrepareNextRender().
m_latencyTweak
double CRenderManager::m_latencyTweak = 0.0 protected
Display latency tweak value from AdvancedSettings for the current refresh rate in milliseconds
Referenced by PrepareNextRender(), and UpdateLatencyTweak().
m_nextCaptureId
unsigned int CRenderManager::m_nextCaptureId = 0 static protected
Referenced by AllocRenderCapture().
m_NumberBuffers
int CRenderManager::m_NumberBuffers = 0 protected
Referenced by Configure(), and Configure().
m_orientation
unsigned int CRenderManager::m_orientation = 0 protected
Referenced by Configure(), and Configure().
m_overlays
OVERLAY::CRenderer CRenderManager::m_overlays protected
Referenced by AddOverlay(), Configure(), Flush(), FrameMove(), IsGuiLayer(), Render(), SetSubtitleVerticalPosition(), UnInit(), and WaitForBuffer().
m_pConfigPicture
std::unique_ptr<VideoPicture> CRenderManager::m_pConfigPicture protected
Referenced by Configure(), Configure(), and CreateRenderer().
m_playerPort
IRenderMsg* CRenderManager::m_playerPort protected
Referenced by AddVideoPicture(), CheckEnableClockSync(), Configure(), FrameMove(), PrepareNextRender(), Render(), SetViewMode(), and UpdateResolution().
m_pRenderer
CBaseRenderer* CRenderManager::m_pRenderer = nullptr protected
Referenced by AddVideoPicture(), AllocRenderCapture(), Configure(), Configure(), CreateRenderer(), DeleteRenderer(), Flush(), FrameMove(), GetAspectRatio(), GetOrientation(), GetVideoRect(), IsGuiLayer(), IsVideoLayer(), PreInit(), PresentBlend(), PresentFields(), PresentSingle(), Render(), RenderCapture(), SetVideoSettings(), SetViewMode(), Supports(), Supports(), UpdateResolution(), and ~CRenderManager().
m_presentevent
XbmcThreads::ConditionVariable CRenderManager::m_presentevent protected
Referenced by AddVideoPicture(), Configure(), Configure(), DiscardBuffer(), FrameMove(), FrameWait(), PrepareNextRender(), Render(), and WaitForBuffer().
m_presentlock
CCriticalSection CRenderManager::m_presentlock protected
Referenced by AddOverlay(), AddVideoPicture(), Configure(), Configure(), DiscardBuffer(), Flush(), FrameMove(), FrameWait(), GetStats(), IsPresenting(), Render(), and WaitForBuffer().
m_presentpts
double CRenderManager::m_presentpts = 0.0 protected
Referenced by Configure(), GetStats(), and PrepareNextRender().
m_presentsource
int CRenderManager::m_presentsource = 0 protected
Referenced by Configure(), Flush(), IsGuiLayer(), PrepareNextRender(), PresentBlend(), PresentFields(), PresentSingle(), Render(), and RenderCapture().
m_presentsourcePast
int CRenderManager::m_presentsourcePast = -1 protected
Referenced by Configure(), Flush(), PrepareNextRender(), PresentBlend(), PresentFields(), and PresentSingle().
m_presentstep
EPRESENTSTEP CRenderManager::m_presentstep = PRESENT_IDLE protected
Referenced by AddVideoPicture(), Configure(), Configure(), DiscardBuffer(), Flush(), FrameMove(), FrameWait(), PreInit(), PrepareNextRender(), PresentFields(), and Render().
m_presentTimer
XbmcThreads::EndTime CRenderManager::m_presentTimer protected
Referenced by FrameMove(), and IsPresenting().
m_Queue
struct CRenderManager::SPresent CRenderManager::m_Queue[NUM_BUFFERS] protected
Referenced by AddVideoPicture(), PrepareNextRender(), PresentBlend(), PresentFields(), PresentSingle(), Render(), and WaitForBuffer().
m_queued
std::deque<int> CRenderManager::m_queued protected
Referenced by AddVideoPicture(), Configure(), DiscardBuffer(), Flush(), FrameMove(), GetStats(), PrepareNextRender(), Render(), and WaitForBuffer().
m_QueueSize
int CRenderManager::m_QueueSize = 2 protected
Referenced by Configure(), Flush(), and PreInit().
m_QueueSkip
int CRenderManager::m_QueueSkip = 0 protected
Referenced by GetSkippedFrames(), PreInit(), and PrepareNextRender().
m_renderDebug
bool CRenderManager::m_renderDebug = false protected
Referenced by Configure(), IsGuiLayer(), Render(), ToggleDebug(), and ToggleDebugVideo().
m_renderDebugVideo
bool CRenderManager::m_renderDebugVideo = false protected
Referenced by Render(), ToggleDebug(), and ToggleDebugVideo().
m_renderedOverlay
bool CRenderManager::m_renderedOverlay = false protected
Referenced by Configure(), IsGuiLayer(), and Render().
m_renderState
ERENDERSTATE CRenderManager::m_renderState = STATE_UNCONFIGURED protected
Referenced by Configure(), Configure(), FrameMove(), GetResolution(), IsConfigured(), PreInit(), Render(), and UnInit().
m_showVideo
std::atomic_bool CRenderManager::m_showVideo = {false} protected
Referenced by PrepareNextRender(), and ShowVideo().
m_stateEvent
CEvent CRenderManager::m_stateEvent protected
Referenced by Configure(), and Configure().
m_statelock
CCriticalSection CRenderManager::m_statelock mutable protected
Referenced by Configure(), Configure(), Flush(), FrameMove(), GetAspectRatio(), GetOrientation(), GetResolution(), GetVideoRect(), IsConfigured(), IsGuiLayer(), IsVideoLayer(), PreInit(), Render(), SetVideoSettings(), SetViewMode(), Supports(), Supports(), and UnInit().
m_stereomode
std::string CRenderManager::m_stereomode protected
Referenced by Configure(), Configure(), GetResolution(), TriggerUpdateResolution(), and UpdateResolution().
m_videoDelay
std::atomic_int CRenderManager::m_videoDelay = {} protected
Referenced by GetDelay(), PrepareNextRender(), and SetDelay().
m_width
unsigned int CRenderManager::m_width = 0 protected
Referenced by Configure(), GetResolution(), TriggerUpdateResolution(), UnInit(), and UpdateResolution().
The documentation for this class was generated from the following files:
RenderManager.h
RenderManager.cpp