Kodi Documentation: TestGPUInfo.cpp File Reference
TestGPUInfo.cpp File Reference
#include "ServiceBroker.h"
#include "settings/AdvancedSettings.h"
#include "settings/SettingsComponent.h"
#include "utils/GpuInfo.h"
#include <memory>
#include <gtest/gtest.h>
Classes
class TestGPUInfo
Functions
EXPECT_NE (gpuInfo, nullptr)
EXPECT_TRUE (success)
EXPECT_TRUE (t.IsValid())
EXPECT_EQ (t.ToCelsius(), 50)
Variables
std::unique_ptr< CGPUInfo > gpuInfo = CGPUInfo::GetGPUInfo()
CTemperature t
bool success = gpuInfo->GetTemperature(t)
Function Documentation
EXPECT_EQ()
EXPECT_EQ (t. ToCelsius(), 50)
EXPECT_NE()
EXPECT_NE (gpuInfo , nullptr)
Referenced by anonymous_namespace{TestDefaultKeyboardTranslator.cpp}::GetController(), anonymous_namespace{TestDefaultMouseTranslator.cpp}::GetController(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
EXPECT_TRUE() [1/2]
EXPECT_TRUE (success)
EXPECT_TRUE() [2/2]
EXPECT_TRUE (t. IsValid())
Variable Documentation
gpuInfo
std::unique_ptr<CGPUInfo> gpuInfo = CGPUInfo::GetGPUInfo()
success
bool success = gpuInfo->GetTemperature(t)
Referenced by CZeroconfBrowserAvahi::browseCallback(), CTextureCache::CacheImage(), CPicture::CacheTexture(), Cocoa_GetVolumeNameFromMountPoint(), KODI::RETRO::CReversiblePlayback::CommitSavestate(), anonymous_namespace{OSXStorageProvider.cpp}::DAOperationContext::Completed(), anonymous_namespace{OSXStorageProvider.cpp}::DAOperationContext::CompletionCallback(), VAAPI::CDecoder::ConfigVAAPI(), VDPAU::CDecoder::ConfigVDPAU(), XFILE::CNFSDirectory::Create(), XFILE::CSMBDirectory::Create(), CPicture::CreateTiledThumb(), XFILE::CWinLibraryFile::Delete(), anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncDeleteRecording::DoRun(), CThumbnailWriter::DoWork(), CFileOperationJob::DoWork(), ActiveAE::CActiveAEStream::Drain(), ActiveAE::CActiveAE::DrainSink(), COSXStorageProvider::Eject(), XFILE::CPluginDirectory::EndOfDirectory(), JSONRPC::CAudioLibrary::FillFileItemList(), JSONRPC::CVideoLibrary::FillFileItemList(), CVideoInfoDownloader::FindMovie(), ActiveAE::CActiveAE::FlushEngine(), ActiveAE::CActiveAE::FlushStream(), ActiveAE::CActiveAE::FreeStream(), XFILE::CPluginDirectory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), KODI::GUILIB::GUIINFO::CAddonsGUIInfo::GetLabel(), XFILE::CPluginDirectory::GetPluginResult(), CVideoDatabase::GetSortedVideos(), JSONRPC::CPlaylistOperations::HandleItemsParameter(), KODI::CDRIP::CEncoderFFmpeg::Init(), PERIPHERALS::CAndroidJoystickState::InitializeButtonMap(), ActiveAE::CActiveAE::InitSink(), KODI::KEYMAP::CButtonTranslator::Load(), KODI::KEYMAP::CIRTranslator::Load(), CSettingsBase::LoadHiddenValuesFromXml(), ActiveAE::CActiveAE::MakeStream(), VDPAU::CVdpauTexture::Map(), PERIPHERALS::CAndroidJoystickState::MapDpad(), CTextureCache::OnCachingComplete(), CRendererBase::OnCMSConfigChanged(), CJobManager::OnJobComplete(), KODI::CDRIP::CCDDARipper::OnJobComplete(), CDirectoryProvider::OnJobComplete(), CMusicLibraryQueue::OnJobComplete(), PingResponseWaiter::OnJobComplete(), CWakeOnAccess::OnJobComplete(), CTextureCache::OnJobComplete(), CSysInfo::OnJobComplete(), CGUIDialogSubtitles::OnJobComplete(), CVideoLibraryQueue::OnJobComplete(), CWeatherManager::OnJobComplete(), CGUIWindowFileManager::OnJobComplete(), ActiveAE::CActiveAE::OnLostDisplay(), CDVDVideoCodecAndroidMediaCodec::Open(), PVR::CPVRChannelGroups::PersistAll(), CJobWorker::Process(), PERIPHERALS::CAndroidJoystickState::ProcessEvent(), CXRandR::Query(), CPowerManager::Reboot(), KODI::WINDOWING::X11::CWinSystemX11GLContext::RefreshGLContext(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::RefreshGLContext(), VAAPI::CDecoder::Release(), VDPAU::CDecoder::Release(), XFILE::CMultiPathDirectory::Remove(), XFILE::CPosixDirectory::RemoveRecursive(), XFILE::CWin32Directory::RemoveRecursive(), CFileUtils::RenameFile(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::ReportInstallError(), VAAPI::CDecoder::Reset(), VDPAU::CDecoder::Reset(), PVR::CPVRChannelGroups::ResetGroupPositions(), CPicture::ResizeTexture(), CTextureCacheJob::ResizeTexture(), ActiveAE::CActiveAE::Resume(), ADDON::CAddon::SaveSettings(), ADDON::CAddonDll::SaveSettings(), JSONRPC::CAddonsOperations::SetAddonEnabled(), XFILE::CPluginDirectory::SetResolvedUrl(), ActiveAE::CActiveAE::Start(), CAirTunesServer::StartServer(), CApplication::Stop(), ActiveAE::CActiveAE::UnconfigureSink(), CDatabaseManager::UpdateVersion(), CGUIWindowScreensaverDim::UpdateVisibility(), and CAESinkPULSE::WaitForOperation().
t
CTemperature t