Kodi Documentation: CVideoTagLoaderPlugin Class Reference
CVideoTagLoaderPlugin Class Reference
Video tag loader from plugin source.
#include <VideoTagLoaderPlugin.h>
Public Member Functions
CVideoTagLoaderPlugin (const CFileItem &item, bool forceRefresh)
~CVideoTagLoaderPlugin () override=default
bool HasInfo () const override
Returns whether or not read has info.
CInfoScanner::INFO_TYPE Load (CVideoInfoTag &tag, bool prioritise, std::vector< EmbeddedArt > *=nullptr) override
Load "tag" from plugin.
std::unique_ptr< std::map< std::string, std::string > > & GetArt ()
Public Member Functions inherited from KODI::VIDEO::IVideoInfoTagLoader
IVideoInfoTagLoader (const CFileItem &item, ADDON::ScraperPtr info, bool lookInFolder)
Constructor.
virtual ~IVideoInfoTagLoader ()=default
const CScraperUrl & ScraperUrl () const
Returns url associated with obtained URL (NFO_URL et al).
const ADDON::ScraperPtr GetAddonInfo () const
Returns current scaper info.
Protected Attributes
std::unique_ptr< CVideoInfoTag > m_tag
std::unique_ptr< std::map< std::string, std::string > > m_art
bool m_force_refresh
Protected Attributes inherited from KODI::VIDEO::IVideoInfoTagLoader
const CFileItem & m_item
Reference to item to load for.
ADDON::ScraperPtr m_info
Scraper info.
CScraperUrl m_url
URL for scraper.
Detailed Description
Video tag loader from plugin source.
Constructor & Destructor Documentation
CVideoTagLoaderPlugin()
CVideoTagLoaderPlugin::CVideoTagLoaderPlugin (const CFileItem & item, bool forceRefresh)
References CGUIListItem::GetArt(), CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), m_art, KODI::VIDEO::IVideoInfoTagLoader::m_item, and m_tag.
~CVideoTagLoaderPlugin()
CVideoTagLoaderPlugin::~CVideoTagLoaderPlugin () override default
Member Function Documentation
GetArt()
std::unique_ptr< std::map< std::string, std::string > > & CVideoTagLoaderPlugin::GetArt () inline
References m_art.
Referenced by CVideoLibraryRefreshingJob::Work().
HasInfo()
bool CVideoTagLoaderPlugin::HasInfo () const override virtual
Returns whether or not read has info.
Implements KODI::VIDEO::IVideoInfoTagLoader.
References m_force_refresh, and m_tag.
Referenced by KODI::VIDEO::CVideoInfoTagLoaderFactory::CreateLoader().
Load()
CInfoScanner::INFO_TYPE CVideoTagLoaderPlugin::Load (CVideoInfoTag & tag, bool prioritise, std::vector< EmbeddedArt > * = nullptr) override virtual
Load "tag" from plugin.
Parameters
tag Tag to load info into
Implements KODI::VIDEO::IVideoInfoTagLoader.
References CInfoScanner::ERROR_NFO, CInfoScanner::FULL_NFO, XFILE::CPluginDirectory::GetDirectory(), CFileItem::GetPath(), CFileItemList::IsEmpty(), m_art, m_force_refresh, KODI::VIDEO::IVideoInfoTagLoader::m_item, m_tag, CInfoScanner::NO_NFO, and CURL::SetOption().
Member Data Documentation
m_art
std::unique_ptr<std::map<std::string, std::string> > CVideoTagLoaderPlugin::m_art protected
Referenced by CVideoTagLoaderPlugin(), GetArt(), and Load().
m_force_refresh
bool CVideoTagLoaderPlugin::m_force_refresh protected
Referenced by HasInfo(), and Load().
m_tag
std::unique_ptr<CVideoInfoTag> CVideoTagLoaderPlugin::m_tag protected
Referenced by CVideoTagLoaderPlugin(), HasInfo(), and Load().
The documentation for this class was generated from the following files:
VideoTagLoaderPlugin.h
VideoTagLoaderPlugin.cpp