Kodi Documentation: CGUIEditControl Class Reference
CGUIEditControl Class Reference
Guilib classes » Window Reference » Controls
#include <GUIEditControl.h>
Public Types
enum INPUT_TYPE {
INPUT_TYPE_READONLY = -1 , INPUT_TYPE_TEXT = 0 , INPUT_TYPE_NUMBER , INPUT_TYPE_SECONDS ,
INPUT_TYPE_TIME , INPUT_TYPE_DATE , INPUT_TYPE_IPADDRESS , INPUT_TYPE_PASSWORD ,
INPUT_TYPE_PASSWORD_MD5 , INPUT_TYPE_SEARCH , INPUT_TYPE_FILTER , INPUT_TYPE_PASSWORD_NUMBER_VERIFY_NEW
}
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Public Member Functions
CGUIEditControl (int parentID, int controlID, float posX, float posY, float width, float height, const CTextureInfo &textureFocus, const CTextureInfo &textureNoFocus, const CLabelInfo &labelInfo, const std::string &text)
CGUIEditControl (const CGUIButtonControl &button)
CGUIEditControl (const CGUIEditControl &button)
~CGUIEditControl (void) override
CGUIEditControl * Clone () const override
bool OnMessage (CGUIMessage &message) override
bool OnAction (const CAction &action) override
void OnClick () override
void SetLabel (const std::string &text) override
void SetLabel2 (const std::string &text) override
void SetHint (const KODI::GUILIB::GUIINFO::CGUIInfoLabel &hint)
std::string GetLabel2 () const override
unsigned int GetCursorPosition () const
void SetCursorPosition (unsigned int iPosition)
void SetInputType (INPUT_TYPE type, const CVariant &heading)
void SetTextChangeActions (const CGUIAction &textChangeActions)
bool HasTextChangeActions () const
virtual bool HasInvalidInput () const
virtual void SetInputValidation (StringValidation::Validator inputValidator, void *data=NULL)
Public Member Functions inherited from CGUIButtonControl
CGUIButtonControl (int parentID, int controlID, float posX, float posY, float width, float height, const CTextureInfo &textureFocus, const CTextureInfo &textureNoFocus, const CLabelInfo &label, bool wrapMultiline=false)
CGUIButtonControl (const CGUIButtonControl &control)
~CGUIButtonControl () override=default
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
void AllocResources () override
void FreeResources (bool immediately=false) override
void DynamicResourceAlloc (bool bOnOff) override
void SetInvalid () override
void SetPosition (float posX, float posY) override
void SetClickActions (const CGUIAction &clickActions)
const CGUIAction & GetClickActions () const
void SetFocusActions (const CGUIAction &focusActions)
void SetUnFocusActions (const CGUIAction &unfocusActions)
const CLabelInfo & GetLabelInfo () const
virtual std::string GetLabel () const
void SetSelected (bool bSelected)
std::string GetDescription () const override
float GetWidth () const override
virtual void SetMinWidth (float minWidth)
void SetAlpha (unsigned char alpha)
void PythonSetLabel (const std::string &strFont, const std::string &strText, KODI::UTILS::COLOR::Color textColor, KODI::UTILS::COLOR::Color shadowColor, KODI::UTILS::COLOR::Color focusedColor)
void PythonSetDisabledColor (KODI::UTILS::COLOR::Color disabledColor)
bool HasClickActions () const
bool UpdateColors (const CGUIListItem *item) override
CRect CalcRenderRegion () const override
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
virtual void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions)
virtual void DoRender ()
virtual void RenderEx ()
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
React to a mouse event.
virtual void UnfocusFromPoint (const CPoint &point)
Unfocus the control if the given point on screen is not within it's boundary.
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
virtual void SetID (int id)
int GetParentID () const
virtual bool HasFocus () const
virtual bool IsDynamicallyAllocated ()
virtual bool CanFocus () const
virtual bool IsVisible () const
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetHeight () const
virtual void AssignDepth ()
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetInitialVisibility ()
virtual void SetEnabled (bool bEnable)
virtual void SetPulseOnSelect (bool pulse)
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
virtual void QueueAnimation (ANIMATION_TYPE anim)
virtual bool IsAnimating (ANIMATION_TYPE anim)
virtual bool HasAnimation (ANIMATION_TYPE anim)
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void ResetAnimation (ANIMATION_TYPE type)
virtual void ResetAnimations ()
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsGroup () const
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
virtual void SaveStates (std::vector< CControlState > &states)
virtual CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr)
void SetControlStats (GUICONTROLSTATS *controlStats)
virtual void UpdateControlStats ()
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Protected Member Functions
void SetFocus (bool focus) override
void ProcessText (unsigned int currentTime) override
void RenderText () override
CGUILabel::COLOR GetTextColor () const override
std::wstring GetDisplayedText () const
std::string GetDescriptionByIndex (int index) const override
bool SetStyledText (const std::wstring &text)
void RecalcRightLabelPosition ()
Recalculate the text offset position for the right label by updating m_textOffset and validate the cursor position.
void ValidateCursor ()
void UpdateText (bool sendUpdate=true)
void OnPasteClipboard ()
void OnSMSCharacter (unsigned int key)
void DefaultConstructor ()
virtual bool ValidateInput (const std::wstring &data) const
void ValidateInput ()
bool ClearMD5 ()
Clear out the current text input if it's an MD5 password.
void ComposingCursorAppendChar (std::uint32_t deadUnicodeKey)
Append a given char to the composing cursor.
void ResetCursor ()
Reset the cursor aspect to normal input (i.e. not composing a key)
void CancelKeyComposition (std::uint32_t deadUnicodeKey)
Cancel the key composition.
bool IsComposingKey () const
Check if the control is composing a key.
Protected Member Functions inherited from CGUIButtonControl
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
void OnFocus () override
void OnUnFocus () override
void SetMaxWidth (float labelMaxWidth)
Set the maximum width for the left label.
Protected Member Functions inherited from CGUIControl
virtual CPoint GetPosition () const
Return the coordinates of the top left of the control, in the control's parent coordinates.
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool Animate (unsigned int currentTime)
virtual bool CheckAnimation (ANIMATION_TYPE animType)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Attributes
std::wstring m_text2
std::string m_text
KODI::GUILIB::GUIINFO::CGUIInfoLabel m_hintInfo
float m_textOffset
CRect m_clipRect
clipping rect for the second label
unsigned int m_cursorPos
bool m_cursorBlinkEnabled {true}
unsigned int m_cursorBlink
std::vector< std::uint32_t > m_cursorChars {'|'}
std::vector< std::uint32_t > m_cursorCharsBuffer {}
std::string m_inputHeading
INPUT_TYPE m_inputType
bool m_isMD5
CGUIAction m_textChangeActions
bool m_invalidInput
StringValidation::Validator m_inputValidator
void * m_inputValidatorData
unsigned int m_smsKeyIndex
unsigned int m_smsLastKey
CStopWatch m_smsTimer
std::wstring m_edit
int m_editOffset
int m_editLength
Protected Attributes inherited from CGUIButtonControl
std::unique_ptr< CGUITexture > m_imgFocus
std::unique_ptr< CGUITexture > m_imgNoFocus
unsigned int m_focusCounter
unsigned char m_alpha
float m_minWidth
float m_maxWidth
float m_labelMaxWidth {0}
KODI::GUILIB::GUIINFO::CGUIInfoLabel m_info
KODI::GUILIB::GUIINFO::CGUIInfoLabel m_info2
CGUILabel m_label
CGUILabel m_label2
CGUIAction m_clickActions
CGUIAction m_focusActions
CGUIAction m_unfocusActions
bool m_bSelected
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Additional Inherited Members
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Member Enumeration Documentation
INPUT_TYPE
enum CGUIEditControl::INPUT_TYPE
Enumerator
INPUT_TYPE_READONLY
INPUT_TYPE_TEXT
INPUT_TYPE_NUMBER
INPUT_TYPE_SECONDS
INPUT_TYPE_TIME
INPUT_TYPE_DATE
INPUT_TYPE_IPADDRESS
INPUT_TYPE_PASSWORD
INPUT_TYPE_PASSWORD_MD5
INPUT_TYPE_SEARCH
INPUT_TYPE_FILTER
INPUT_TYPE_PASSWORD_NUMBER_VERIFY_NEW
Constructor & Destructor Documentation
CGUIEditControl() [1/3]
CGUIEditControl::CGUIEditControl (int parentID, int controlID, float posX, float posY, float width, float height, const CTextureInfo & textureFocus, const CTextureInfo & textureNoFocus, const CLabelInfo & labelInfo, const std::string & text)
References DefaultConstructor(), CLabelInfo::font, CGUILabel::GetLabelInfo(), CGUIFont::GetTextHeight(), LOGWARNING, CGUIControl::m_height, CGUIButtonControl::m_label, SetLabel(), and text.
CGUIEditControl() [2/3]
CGUIEditControl::CGUIEditControl (const CGUIButtonControl & button) explicit
References DefaultConstructor().
CGUIEditControl() [3/3]
CGUIEditControl::CGUIEditControl (const CGUIEditControl & button) explicit
References DefaultConstructor().
~CGUIEditControl()
CGUIEditControl::~CGUIEditControl (void) override default
Member Function Documentation
CancelKeyComposition()
void CGUIEditControl::CancelKeyComposition (std::uint32_t deadUnicodeKey) protected
Cancel the key composition.
Parameters
deadUnicodeKey - the unicode key that ended/cancelled the composing sequence
References ClearMD5(), m_cursorCharsBuffer, m_cursorPos, m_edit, m_text2, ResetCursor(), UpdateText(), and XBMCK_BACKSPACE.
Referenced by OnAction().
ClearMD5()
bool CGUIEditControl::ClearMD5 () protected
Clear out the current text input if it's an MD5 password.
Returns
true if the password is cleared, false otherwise.
References INPUT_TYPE_PASSWORD_MD5, INPUT_TYPE_PASSWORD_NUMBER_VERIFY_NEW, m_cursorPos, m_inputType, m_isMD5, and m_text2.
Referenced by CancelKeyComposition(), OnAction(), and OnClick().
Clone()
CGUIEditControl * CGUIEditControl::Clone (void) const inline override virtual
Reimplemented from CGUIButtonControl.
ComposingCursorAppendChar()
void CGUIEditControl::ComposingCursorAppendChar (std::uint32_t deadUnicodeKey) protected
Append a given char to the composing cursor.
Parameters
deadUnicodeKey - the unicode key that started the composing sequence
References INPUT_TYPE_PASSWORD, INPUT_TYPE_PASSWORD_MD5, INPUT_TYPE_PASSWORD_NUMBER_VERIFY_NEW, IsComposingKey(), m_cursorBlinkEnabled, m_cursorChars, m_cursorCharsBuffer, and m_inputType.
Referenced by OnAction().
DefaultConstructor()
void CGUIEditControl::DefaultConstructor () protected
References CGUIControl::ControlType, g_localizeStrings, CLocalizeStrings::Get(), CGUILabel::GetLabelInfo(), CGUIControl::GUICONTROL_EDIT, INPUT_TYPE_TEXT, m_cursorBlink, m_cursorPos, m_editLength, m_editOffset, m_inputHeading, m_inputType, m_inputValidator, m_inputValidatorData, m_invalidInput, m_isMD5, CGUIButtonControl::m_label2, m_smsKeyIndex, m_smsLastKey, m_textOffset, and CLabelInfo::offsetX.
Referenced by CGUIEditControl(), CGUIEditControl(), and CGUIEditControl().
GetCursorPosition()
unsigned int CGUIEditControl::GetCursorPosition () const
References m_cursorPos.
Referenced by ADDON::Interface_GUIControlEdit::get_cursor_position().
GetDescriptionByIndex()
std::string CGUIEditControl::GetDescriptionByIndex (int index) const override protected virtual
Reimplemented from CGUIControl.
References CGUIButtonControl::GetDescription(), GetLabel2(), and index().
GetDisplayedText()
std::wstring CGUIEditControl::GetDisplayedText () const protected
References INPUT_TYPE_PASSWORD, INPUT_TYPE_PASSWORD_MD5, INPUT_TYPE_PASSWORD_NUMBER_VERIFY_NEW, CStopWatch::IsRunning(), m_cursorPos, m_edit, m_editOffset, m_inputType, m_smsTimer, m_text2, and text.
Referenced by ProcessText(), and RecalcRightLabelPosition().
GetLabel2()
std::string CGUIEditControl::GetLabel2 () const override virtual
Reimplemented from CGUIButtonControl.
References g_charsetConverter, INPUT_TYPE_PASSWORD_MD5, m_inputType, m_isMD5, m_text2, and text.
Referenced by ADDON::Interface_GUIControlEdit::get_text(), GetDescriptionByIndex(), CGUIControlEditSetting::OnClick(), OnMessage(), and ValidateInput().
GetTextColor()
CGUILabel::COLOR CGUIEditControl::GetTextColor () const override protected virtual
Reimplemented from CGUIButtonControl.
References color, CGUILabel::COLOR_DISABLED, CGUILabel::COLOR_INVALID, CGUIButtonControl::GetTextColor(), and HasInvalidInput().
Referenced by ProcessText().
HasInvalidInput()
virtual bool CGUIEditControl::HasInvalidInput () const inline virtual
References m_invalidInput.
Referenced by GetTextColor().
HasTextChangeActions()
bool CGUIEditControl::HasTextChangeActions () const inline
References CGUIAction::HasActionsMeetingCondition(), and m_textChangeActions.
IsComposingKey()
bool CGUIEditControl::IsComposingKey () const protected
Check if the control is composing a key.
Returns
true if a key is being composed, false otherwise
References m_cursorBlinkEnabled.
Referenced by ComposingCursorAppendChar().
OnAction()
bool CGUIEditControl::OnAction (const CAction & action) override virtual
Reimplemented from CGUIButtonControl.
References ACTION_BACKSPACE, ACTION_CURSOR_LEFT, ACTION_CURSOR_RIGHT, ACTION_INPUT_TEXT, ACTION_KEYBOARD_COMPOSING_KEY, ACTION_KEYBOARD_COMPOSING_KEY_CANCELLED, ACTION_KEYBOARD_COMPOSING_KEY_FINISHED, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_PASTE, CancelKeyComposition(), ClearMD5(), ComposingCursorAppendChar(), g_charsetConverter, CGUIControl::GetID(), CGUIControl::GetParentID(), INPUT_TYPE_READONLY, KEY_UNICODE, KEY_VKEY, m_cursorPos, m_edit, m_inputType, m_text2, CGUIButtonControl::OnAction(), OnPasteClipboard(), OnSMSCharacter(), REMOTE_0, REMOTE_9, ResetCursor(), SEND_CLICK_MESSAGE, UpdateText(), ValidateCursor(), XBMCVK_BACK, XBMCVK_DELETE, XBMCVK_END, XBMCVK_ESCAPE, XBMCVK_HOME, XBMCVK_LEFT, XBMCVK_NUMPADENTER, XBMCVK_RETURN, and XBMCVK_RIGHT.
OnClick()
void CGUIEditControl::OnClick () override virtual
Todo:
Ideally we'd send this to the keyboard and tell the keyboard we have this type of input
Reimplemented from CGUIButtonControl.
References ClearMD5(), g_charsetConverter, g_localizeStrings, CLocalizeStrings::Get(), CDateTime::GetAsDBDate(), CDateTime::GetAsLocalizedTime(), CDateTime::GetAsSystemTime(), CGUIControl::GetParentID(), INPUT_TYPE_DATE, INPUT_TYPE_FILTER, INPUT_TYPE_IPADDRESS, INPUT_TYPE_NUMBER, INPUT_TYPE_PASSWORD, INPUT_TYPE_PASSWORD_MD5, INPUT_TYPE_PASSWORD_NUMBER_VERIFY_NEW, INPUT_TYPE_READONLY, INPUT_TYPE_SEARCH, INPUT_TYPE_SECONDS, INPUT_TYPE_TEXT, INPUT_TYPE_TIME, m_cursorPos, m_edit, m_inputHeading, m_inputType, m_text2, CDateTime::SetFromDBDate(), CDateTime::SetFromDBTime(), CGUIDialogNumeric::ShowAndGetDate(), CGUIKeyboardFactory::ShowAndGetFilter(), CGUIKeyboardFactory::ShowAndGetInput(), CGUIDialogNumeric::ShowAndGetIPAddress(), CGUIDialogNumeric::ShowAndGetNumber(), CGUIDialogNumeric::ShowAndGetSeconds(), CGUIDialogNumeric::ShowAndGetTime(), CGUIDialogNumeric::ShowAndVerifyNewPassword(), UpdateText(), and WINDOW_DIALOG_KEYBOARD.
OnMessage()
bool CGUIEditControl::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIButtonControl.
References CGUIMessage::GetControlId(), CGUIControl::GetID(), CGUIMessage::GetLabel(), GetLabel2(), CGUIMessage::GetMessage(), CGUIMessage::GetParam1(), CGUIMessage::GetParam2(), GUI_MSG_ITEM_SELECTED, GUI_MSG_SET_TEXT, GUI_MSG_SET_TYPE, CGUIControl::HasFocus(), CGUIButtonControl::OnMessage(), SetInputType(), CGUIMessage::SetLabel(), SetLabel2(), and UpdateText().
OnPasteClipboard()
void CGUIEditControl::OnPasteClipboard () protected
References g_charsetConverter, CWinSystemBase::GetClipboardText(), CServiceBroker::GetWinSystem(), m_cursorPos, m_text2, and UpdateText().
Referenced by OnAction().
OnSMSCharacter()
void CGUIEditControl::OnSMSCharacter (unsigned int key) protected
References CStopWatch::GetElapsedMilliseconds(), CStopWatch::IsRunning(), m_cursorPos, m_smsKeyIndex, m_smsLastKey, m_smsTimer, m_text2, CStopWatch::StartZero(), and UpdateText().
Referenced by OnAction().
ProcessText()
void CGUIEditControl::ProcessText (unsigned int currentTime) override protected virtual
Reimplemented from CGUIButtonControl.
References CLabelInfo::align, GetDisplayedText(), CStopWatch::GetElapsedMilliseconds(), CWinSystemBase::GetGfxContext(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), CGUILabel::GetLabelInfo(), CGUIControl::GetParentID(), GetTextColor(), CGUILabel::GetTextWidth(), CServiceBroker::GetWinSystem(), CGUIControl::HasFocus(), CRectGen< T >::Height(), INPUT_TYPE_READONLY, CStopWatch::IsRunning(), CGUIControl::m_bInvalidated, m_clipRect, CGUIControl::m_height, m_hintInfo, CGUIButtonControl::m_info, m_inputType, CGUIButtonControl::m_label, CGUIButtonControl::m_label2, CGUIControl::m_parentID, CGUIControl::m_posX, CGUIControl::m_posY, m_smsTimer, m_textOffset, CGUIControl::m_width, CGUIControl::MarkDirtyRegion(), CLabelInfo::offsetX, CGUILabel::OVER_FLOW_CLIP, CGUILabel::OVER_FLOW_TRUNCATE_LEFT, CGUILabel::Process(), RecalcRightLabelPosition(), CGraphicContext::RestoreClipRegion(), CGUILabel::SetAlign(), CGUILabel::SetColor(), CGUILabel::SetMaxRect(), CGUILabel::SetOverflow(), CGUILabel::SetScrolling(), SetStyledText(), CGUILabel::SetText(), CGUILabel::SetTextW(), text, UpdateText(), CRectGen< T >::Width(), WINDOW_DIALOG_KEYBOARD, CRectGen< T >::x1, CRectGen< T >::x2, XBFONT_CENTER_X, XBFONT_CENTER_Y, XBFONT_RIGHT, CRectGen< T >::y1, and CRectGen< T >::y2.
RecalcRightLabelPosition()
void CGUIEditControl::RecalcRightLabelPosition () protected
Recalculate the text offset position for the right label by updating m_textOffset and validate the cursor position.
References CGUILabel::CalcTextWidth(), GetDisplayedText(), CGUILabel::GetLabelInfo(), CGUILabel::GetMaxWidth(), CGUILabel::GetTextWidth(), m_cursorPos, CGUIButtonControl::m_label, CGUIButtonControl::m_label2, m_textOffset, CGUIControl::m_width, CLabelInfo::offsetX, text, and ValidateCursor().
Referenced by ProcessText().
RenderText()
void CGUIEditControl::RenderText () override protected virtual
Reimplemented from CGUIButtonControl.
References CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), CRectGen< T >::Height(), m_clipRect, CGUIButtonControl::m_label, CGUIButtonControl::m_label2, CGUILabel::Render(), RENDER_ORDER_FRONT_TO_BACK, CGraphicContext::RestoreClipRegion(), CRectGen< T >::Width(), CRectGen< T >::x1, and CRectGen< T >::y1.
ResetCursor()
void CGUIEditControl::ResetCursor () protected
Reset the cursor aspect to normal input (i.e. not composing a key)
References m_cursorBlinkEnabled, m_cursorChars, and m_cursorCharsBuffer.
Referenced by CancelKeyComposition(), and OnAction().
SetCursorPosition()
void CGUIEditControl::SetCursorPosition (unsigned int iPosition)
References m_cursorPos.
Referenced by ADDON::Interface_GUIControlEdit::set_cursor_position().
SetFocus()
void CGUIEditControl::SetFocus (bool focus) override protected virtual
Reimplemented from CGUIControl.
References m_smsTimer, CGUIControl::SetFocus(), CGUIButtonControl::SetInvalid(), and CStopWatch::Stop().
SetHint()
void CGUIEditControl::SetHint (const KODI::GUILIB::GUIINFO::CGUIInfoLabel & hint)
References m_hintInfo.
SetInputType()
void CGUIEditControl::SetInputType (CGUIEditControl::INPUT_TYPE type, const CVariant & heading)
Todo:
Verify the current input string?
References CVariant::asInteger(), CVariant::asString(), g_localizeStrings, CLocalizeStrings::Get(), CVariant::isInteger(), CVariant::isString(), m_inputHeading, and m_inputType.
Referenced by CGUIControlEditSetting::CGUIControlEditSetting(), OnMessage(), and ADDON::Interface_GUIControlEdit::set_input_type().
SetInputValidation()
void CGUIEditControl::SetInputValidation (StringValidation::Validator inputValidator, void * data = NULL) virtual
References data(), m_inputValidator, m_inputValidatorData, and ValidateInput().
Referenced by CGUIControlEditSetting::CGUIControlEditSetting(), and CGUIDialogSmartPlaylistRule::OnInitWindow().
SetLabel()
void CGUIEditControl::SetLabel (const std::string & text) override virtual
Reimplemented from CGUIButtonControl.
References CGUIButtonControl::SetInvalid(), CGUIButtonControl::SetLabel(), and text.
Referenced by CGUIEditControl(), and ADDON::Interface_GUIControlEdit::set_label().
SetLabel2()
void CGUIEditControl::SetLabel2 (const std::string & text) override virtual
Reimplemented from CGUIButtonControl.
References g_charsetConverter, INPUT_TYPE_PASSWORD_MD5, INPUT_TYPE_PASSWORD_NUMBER_VERIFY_NEW, m_cursorPos, m_edit, m_inputType, m_isMD5, m_text2, CGUIButtonControl::SetInvalid(), text, and ValidateInput().
Referenced by OnMessage(), ADDON::Interface_GUIControlEdit::set_text(), and CGUIControlEditSetting::Update().
SetStyledText()
bool CGUIEditControl::SetStyledText (const std::wstring & text) protected
References CLabelInfo::disabledColor, CLabelInfo::font, FONT_STYLE_MASK, FONT_STYLE_NORMAL, CGUILabel::GetLabelInfo(), CGUIFont::GetStyle(), m_cursorBlink, m_cursorBlinkEnabled, m_cursorChars, m_cursorPos, m_edit, m_editLength, m_editOffset, CGUIButtonControl::m_label, CGUIButtonControl::m_label2, CLabelInfo::selectedColor, CGUILabel::SetStyledText(), text, and CLabelInfo::textColor.
Referenced by ProcessText().
SetTextChangeActions()
void CGUIEditControl::SetTextChangeActions (const CGUIAction & textChangeActions) inline
References m_textChangeActions.
UpdateText()
void CGUIEditControl::UpdateText (bool sendUpdate = true) protected
References CGUIAction::ExecuteActions(), CGUIControl::GetID(), CGUIControl::GetParentID(), m_smsTimer, m_textChangeActions, SEND_CLICK_MESSAGE, CGUIButtonControl::SetInvalid(), CStopWatch::Stop(), and ValidateInput().
Referenced by CancelKeyComposition(), OnAction(), OnClick(), OnMessage(), OnPasteClipboard(), OnSMSCharacter(), and ProcessText().
ValidateCursor()
void CGUIEditControl::ValidateCursor () protected
References m_cursorPos, and m_text2.
Referenced by OnAction(), and RecalcRightLabelPosition().
ValidateInput() [1/2]
void CGUIEditControl::ValidateInput () protected
References CGUIControl::GetID(), GUI_MSG_VALIDITY_CHANGED, m_invalidInput, m_text2, CGUIControl::SendWindowMessage(), CGUIButtonControl::SetInvalid(), and ValidateInput().
Referenced by SetInputValidation(), SetLabel2(), UpdateText(), and ValidateInput().
ValidateInput() [2/2]
bool CGUIEditControl::ValidateInput (const std::wstring & data) const protected virtual
References GetLabel2(), m_inputValidator, and m_inputValidatorData.
Member Data Documentation
m_clipRect
CRect CGUIEditControl::m_clipRect protected
clipping rect for the second label
Referenced by ProcessText(), and RenderText().
m_cursorBlink
unsigned int CGUIEditControl::m_cursorBlink protected
Referenced by DefaultConstructor(), and SetStyledText().
m_cursorBlinkEnabled
bool CGUIEditControl::m_cursorBlinkEnabled {true} protected
Referenced by ComposingCursorAppendChar(), IsComposingKey(), ResetCursor(), and SetStyledText().
m_cursorChars
std::vector<std::uint32_t> CGUIEditControl::m_cursorChars {'|'} protected
Referenced by ComposingCursorAppendChar(), ResetCursor(), and SetStyledText().
m_cursorCharsBuffer
std::vector<std::uint32_t> CGUIEditControl::m_cursorCharsBuffer {} protected
Referenced by CancelKeyComposition(), ComposingCursorAppendChar(), and ResetCursor().
m_cursorPos
unsigned int CGUIEditControl::m_cursorPos protected
Referenced by CancelKeyComposition(), ClearMD5(), DefaultConstructor(), GetCursorPosition(), GetDisplayedText(), OnAction(), OnClick(), OnPasteClipboard(), OnSMSCharacter(), RecalcRightLabelPosition(), SetCursorPosition(), SetLabel2(), SetStyledText(), and ValidateCursor().
m_edit
std::wstring CGUIEditControl::m_edit protected
Referenced by CancelKeyComposition(), GetDisplayedText(), OnAction(), OnClick(), SetLabel2(), and SetStyledText().
m_editLength
int CGUIEditControl::m_editLength protected
Referenced by DefaultConstructor(), and SetStyledText().
m_editOffset
int CGUIEditControl::m_editOffset protected
Referenced by DefaultConstructor(), GetDisplayedText(), and SetStyledText().
m_hintInfo
KODI::GUILIB::GUIINFO::CGUIInfoLabel CGUIEditControl::m_hintInfo protected
Referenced by ProcessText(), and SetHint().
m_inputHeading
std::string CGUIEditControl::m_inputHeading protected
Referenced by DefaultConstructor(), OnClick(), and SetInputType().
m_inputType
INPUT_TYPE CGUIEditControl::m_inputType protected
Referenced by ClearMD5(), ComposingCursorAppendChar(), DefaultConstructor(), GetDisplayedText(), GetLabel2(), OnAction(), OnClick(), ProcessText(), SetInputType(), and SetLabel2().
m_inputValidator
StringValidation::Validator CGUIEditControl::m_inputValidator protected
Referenced by DefaultConstructor(), SetInputValidation(), and ValidateInput().
m_inputValidatorData
void* CGUIEditControl::m_inputValidatorData protected
Referenced by DefaultConstructor(), SetInputValidation(), and ValidateInput().
m_invalidInput
bool CGUIEditControl::m_invalidInput protected
Referenced by DefaultConstructor(), HasInvalidInput(), and ValidateInput().
m_isMD5
bool CGUIEditControl::m_isMD5 protected
Referenced by ClearMD5(), DefaultConstructor(), GetLabel2(), and SetLabel2().
m_smsKeyIndex
unsigned int CGUIEditControl::m_smsKeyIndex protected
Referenced by DefaultConstructor(), and OnSMSCharacter().
m_smsLastKey
unsigned int CGUIEditControl::m_smsLastKey protected
Referenced by DefaultConstructor(), and OnSMSCharacter().
m_smsTimer
CStopWatch CGUIEditControl::m_smsTimer protected
Referenced by GetDisplayedText(), OnSMSCharacter(), ProcessText(), SetFocus(), and UpdateText().
m_text
std::string CGUIEditControl::m_text protected
m_text2
std::wstring CGUIEditControl::m_text2 protected
Referenced by CancelKeyComposition(), ClearMD5(), GetDisplayedText(), GetLabel2(), OnAction(), OnClick(), OnPasteClipboard(), OnSMSCharacter(), SetLabel2(), ValidateCursor(), and ValidateInput().
m_textChangeActions
CGUIAction CGUIEditControl::m_textChangeActions protected
Referenced by HasTextChangeActions(), SetTextChangeActions(), and UpdateText().
m_textOffset
float CGUIEditControl::m_textOffset protected
Referenced by DefaultConstructor(), ProcessText(), and RecalcRightLabelPosition().
The documentation for this class was generated from the following files:
GUIEditControl.h
GUIEditControl.cpp