Kodi Documentation: CVideoBuffer Class Reference
CVideoBuffer Class Reference
#include <VideoBuffer.h>
Public Member Functions
CVideoBuffer ()=delete
virtual ~CVideoBuffer ()=default
void Acquire ()
void Acquire (std::shared_ptr< IVideoBufferPool > pool)
void Release ()
int GetId () const
virtual AVPixelFormat GetFormat ()
virtual uint8_t * GetMemPtr ()
virtual void GetPlanes (uint8_t *(&planes)[YuvImage::MAX_PLANES])
virtual void GetStrides (int(&strides)[YuvImage::MAX_PLANES])
virtual void SetPixelFormat (const AVPixelFormat pixFormat)
virtual void SetDimensions (int width, int height, const int(&strides)[YuvImage::MAX_PLANES])
virtual void SetDimensions (int width, int height, const int(&strides)[YuvImage::MAX_PLANES], const int(&planeOffsets)[YuvImage::MAX_PLANES])
Static Public Member Functions
static bool CopyPicture (YuvImage *pDst, YuvImage *pSrc)
static bool CopyNV12Picture (YuvImage *pDst, YuvImage *pSrc)
static bool CopyYUV422PackedPicture (YuvImage *pDst, YuvImage *pSrc)
Protected Member Functions
CVideoBuffer (int id)
Protected Attributes
AVPixelFormat m_pixFormat = AV_PIX_FMT_NONE
std::atomic_int m_refCount
int m_id
std::shared_ptr< IVideoBufferPool > m_pool
Constructor & Destructor Documentation
CVideoBuffer() [1/2]
CVideoBuffer::CVideoBuffer () delete
~CVideoBuffer()
virtual CVideoBuffer::~CVideoBuffer () virtual default
Reimplemented in DXVA::CVideoBuffer.
CVideoBuffer() [2/2]
CVideoBuffer::CVideoBuffer (int id) explicit protected
References id, m_id, and m_refCount.
Member Function Documentation
Acquire() [1/2]
void CVideoBuffer::Acquire ()
References m_refCount.
Referenced by CVideoLayerBridgeDRMPRIME::Acquire(), CRendererDRMPRIME::AddVideoPicture(), CRendererDRMPRIMEGLES::AddVideoPicture(), CRendererMediaCodec::AddVideoPicture(), CRendererMediaCodecSurface::AddVideoPicture(), CLinuxRendererGL::AddVideoPicture(), CLinuxRendererGLES::AddVideoPicture(), CRenderBuffer::AppendPicture(), VideoPicture::CopyRef(), CVideoBufferPoolSysMem::Get(), CVideoBufferPoolDRMPRIMEFFmpeg::Get(), CVideoBufferPoolDMA::Get(), CVideoBufferPoolFFmpeg::Get(), VAAPI::CVaapiBufferPool::Get(), VDPAU::CVdpauBufferPool::Get(), VTB::CVideoBufferPoolVTB::Get(), VTB::CDecoder::GetPicture(), VAAPI::CVaapi1Texture::Map(), VAAPI::CVaapi2Texture::Map(), CDRMPRIMETexture::Map(), and VDPAU::CVdpauTexture::Map().
Acquire() [2/2]
void CVideoBuffer::Acquire (std::shared_ptr< IVideoBufferPool > pool)
References m_pool, and m_refCount.
CopyNV12Picture()
bool CVideoBuffer::CopyNV12Picture (YuvImage * pDst, YuvImage * pSrc) static
References YuvImage::height, YuvImage::plane, YuvImage::stride, and YuvImage::width.
Referenced by CLinuxRendererGL::UploadTexture(), and CRendererVAAPIGL::UploadTexture().
CopyPicture()
bool CVideoBuffer::CopyPicture (YuvImage * pDst, YuvImage * pSrc) static
References YuvImage::bpp, YuvImage::cshift_x, YuvImage::cshift_y, YuvImage::height, YuvImage::plane, YuvImage::stride, and YuvImage::width.
Referenced by CLinuxRendererGL::UploadTexture().
CopyYUV422PackedPicture()
bool CVideoBuffer::CopyYUV422PackedPicture (YuvImage * pDst, YuvImage * pSrc) static
References YuvImage::height, YuvImage::plane, YuvImage::stride, and YuvImage::width.
Referenced by CLinuxRendererGL::UploadTexture().
GetFormat()
AVPixelFormat CVideoBuffer::GetFormat () virtual
Reimplemented in CStarfishVideoBuffer.
References m_pixFormat.
Referenced by CRendererDRMPRIME::ConfigChanged(), CRendererDRMPRIMEGLES::ConfigChanged(), CRendererStarfish::ConfigChanged(), CLinuxRendererGL::ConfigChanged(), CLinuxRendererGLES::ConfigChanged(), CWinRenderer::ConfigChanged(), CRendererDRMPRIME::Configure(), CRendererDRMPRIMEGLES::Configure(), CRendererStarfish::Configure(), CLinuxRendererGL::Configure(), CLinuxRendererGLES::Configure(), CWinRenderer::Configure(), CRendererDXVA::Configure(), CRendererShaders::Configure(), CRendererSoftware::Configure(), CRendererBase::GetDXGIFormat(), CRendererDXVA::GetWeight(), CRendererShaders::GetWeight(), CRendererSoftware::GetWeight(), and CDVDVideoPPFFmpeg::Process().
GetId()
int CVideoBuffer::GetId () const inline
References m_id.
GetMemPtr()
virtual uint8_t * CVideoBuffer::GetMemPtr () inline virtual
Reimplemented in CVideoBufferSysMem, and CVideoBufferDMA.
Referenced by CAddonVideoCodec::GetFrameBuffer().
GetPlanes()
virtual void CVideoBuffer::GetPlanes (uint8_t *(&) planes[YuvImage::MAX_PLANES]) inline virtual
Reimplemented in CVideoBufferSysMem, CVideoBufferDMA, CVideoBufferFFmpeg, and VAAPI::CVaapiRenderPicture.
Referenced by CDVDFileInfo::ExtractThumbToTexture(), CDVDVideoPPFFmpeg::Process(), CLinuxRendererGL::UploadTexture(), and CLinuxRendererGLES::UploadTexture().
GetStrides()
virtual void CVideoBuffer::GetStrides (int(&) strides[YuvImage::MAX_PLANES]) inline virtual
Reimplemented in CVideoBufferSysMem, CVideoBufferDMA, CVideoBufferFFmpeg, and VAAPI::CVaapiRenderPicture.
Referenced by CDVDFileInfo::ExtractThumbToTexture(), CDVDVideoPPFFmpeg::Process(), CLinuxRendererGL::UploadTexture(), and CLinuxRendererGLES::UploadTexture().
Release()
void CVideoBuffer::Release ()
References m_id, m_pool, and m_refCount.
Referenced by CRendererDRMPRIME::AddVideoPicture(), CRendererDRMPRIMEGLES::AddVideoPicture(), CLinuxRendererGL::AddVideoPicture(), CLinuxRendererGLES::AddVideoPicture(), DXVA::CDecoder::Close(), CVideoPlayerVideo::CloseStream(), VideoPicture::CopyRef(), DXVA::CDecoder::Decode(), VAAPI::CDecoder::Decode(), VDPAU::CDecoder::Decode(), VTB::CDecoder::Decode(), VAAPI::COutput::Flush(), VDPAU::COutput::Flush(), CDVDVideoCodecAndroidMediaCodec::GetOutputPicture(), DXVA::CDecoder::GetPicture(), VAAPI::CDecoder::GetPicture(), VDPAU::CDecoder::GetPicture(), VTB::CDecoder::GetPicture(), CAddonVideoCodec::GetPicture(), CDVDVideoCodecDRMPRIME::GetPicture(), VDPAU::CVdpauTexture::Map(), CVideoPlayerVideo::Process(), CDVDVideoPPFFmpeg::Process(), VAAPI::COutput::ProcessPicture(), VAAPI::CDecoder::Release(), CRendererDRMPRIME::ReleaseBuffer(), CRendererDRMPRIMEGLES::ReleaseBuffer(), CRendererMediaCodec::ReleaseBuffer(), CRendererVTB::ReleaseBuffer(), CLinuxRendererGL::ReleaseBuffer(), CLinuxRendererGLES::ReleaseBuffer(), anonymous_namespace{DVDVideoCodecDRMPRIME.cpp}::ReleaseBuffer(), CRenderBuffer::ReleasePicture(), CRendererMediaCodecSurface::ReleaseVideoBuffer(), VideoPicture::Reset(), CAddonVideoCodec::Reset(), DXVA::CDecoder::Reset(), VAAPI::CDecoder::Reset(), VDPAU::CDecoder::Reset(), VideoPicture::SetParams(), CDVDVideoCodecFFmpeg::SetPictureParams(), CDRMPRIMETexture::Unmap(), VDPAU::CVdpauTexture::Unmap(), VAAPI::CVaapi1Texture::Unmap(), VAAPI::CVaapi2Texture::Unmap(), VTB::CDecoder::~CDecoder(), and VideoPicture::~VideoPicture().
SetDimensions() [1/2]
virtual void CVideoBuffer::SetDimensions (int width, int height, const int(&) strides[YuvImage::MAX_PLANES]) inline virtual
Reimplemented in CVideoBufferSysMem, and CVideoBufferDMA.
Referenced by CAddonVideoCodec::GetPicture(), and CDVDVideoPPFFmpeg::Process().
SetDimensions() [2/2]
virtual void CVideoBuffer::SetDimensions (int width, int height, const int(&) strides[YuvImage::MAX_PLANES], const int(&) planeOffsets[YuvImage::MAX_PLANES]) inline virtual
Reimplemented in CVideoBufferSysMem, and CVideoBufferDMA.
SetPixelFormat()
virtual void CVideoBuffer::SetPixelFormat (const AVPixelFormat pixFormat) inline virtual
Reimplemented in CVideoBufferSysMem.
Referenced by CAddonVideoCodec::GetPicture().
Member Data Documentation
m_id
int CVideoBuffer::m_id protected
Referenced by CVideoBufferDMA::Alloc(), CVideoBuffer(), CVideoBufferDMA::Export(), GetId(), Release(), and CVideoBufferDMA::SetDimensions().
m_pixFormat
AVPixelFormat CVideoBuffer::m_pixFormat = AV_PIX_FMT_NONE protected
Referenced by DXVA::CVideoBuffer::CVideoBuffer(), CVideoBufferDRMPRIME::CVideoBufferDRMPRIME(), CVideoBufferSysMem::CVideoBufferSysMem(), GetFormat(), CVideoBufferSysMem::SetDimensions(), CVideoBufferSysMem::SetPixelFormat(), and CVideoBufferFFmpeg::SetRef().
m_pool
std::shared_ptr<IVideoBufferPool> CVideoBuffer::m_pool protected
Referenced by Acquire(), Release(), and CMediaCodecVideoBuffer::ReleaseOutputBuffer().
m_refCount
std::atomic_int CVideoBuffer::m_refCount protected
Referenced by Acquire(), Acquire(), CVideoBuffer(), and Release().
The documentation for this class was generated from the following files:
VideoBuffer.h
VideoBuffer.cpp