Kodi Documentation: TestJobManager.cpp File Reference
TestJobManager.cpp File Reference
#include "ServiceBroker.h"
#include "test/MtTestUtils.h"
#include "utils/Job.h"
#include "utils/JobManager.h"
#include "utils/XTimeUtils.h"
#include <atomic>
#include <mutex>
#include <gtest/gtest.h>
Classes
struct Flags
class DummyJob
class ReallyDumbJob
class TestJobManager
struct anonymous_namespace{TestJobManager.cpp}::JobControlPackage
class anonymous_namespace{TestJobManager.cpp}::BroadcastingJob
Namespaces
namespace anonymous_namespace{TestJobManager.cpp}
Functions
TEST_F (TestJobManager, AddJob)
TEST_F (TestJobManager, CancelJob)
BroadcastingJob * anonymous_namespace{TestJobManager.cpp}::WaitForJobToStartProcessing (CJob::PRIORITY priority, JobControlPackage &package)
TEST_F (TestJobManager, PauseLowPriorityJob)
TEST_F (TestJobManager, IsProcessing)
Function Documentation
TEST_F() [1/4]
TEST_F (TestJobManager , AddJob)
References Flags::finished, CServiceBroker::GetJobManager(), and ConditionPoll::poll().
TEST_F() [2/4]
TEST_F (TestJobManager , CancelJob)
References EXPECT_TRUE(), Flags::finished, CServiceBroker::GetJobManager(), id, Flags::lingerAtWork, ConditionPoll::poll(), Flags::started, and Flags::wasCanceled.
TEST_F() [3/4]
TEST_F (TestJobManager , IsProcessing)
References EXPECT_EQ(), CServiceBroker::GetJobManager(), CJob::PRIORITY_LOW_PAUSABLE, and anonymous_namespace{TestJobManager.cpp}::WaitForJobToStartProcessing().
TEST_F() [4/4]
TEST_F (TestJobManager , PauseLowPriorityJob)
References EXPECT_TRUE(), CServiceBroker::GetJobManager(), CJob::PRIORITY_LOW_PAUSABLE, and anonymous_namespace{TestJobManager.cpp}::WaitForJobToStartProcessing().