Kodi Documentation: CWebServer Class Reference
CWebServer Class Reference
#include <WebServer.h>
Classes
struct ConnectionHandler
Public Member Functions
CWebServer ()
virtual ~CWebServer ()=default
bool Start (uint16_t port, const std::string &username, const std::string &password)
bool Stop ()
bool IsStarted ()
void SetCredentials (const std::string &username, const std::string &password)
void RegisterRequestHandler (IHTTPRequestHandler *handler)
void UnregisterRequestHandler (IHTTPRequestHandler *handler)
Static Public Member Functions
static bool WebServerSupportsSSL ()
Protected Types
typedef struct CWebServer::ConnectionHandler ConnectionHandler
Protected Member Functions
virtual void LogRequest (const char *uri) const
virtual MHD_RESULT HandlePartialRequest (struct MHD_Connection *connection, ConnectionHandler *connectionHandler, const HTTPRequest &request, const char *upload_data, size_t *upload_data_size, void **con_cls)
virtual MHD_RESULT HandleRequest (const std::shared_ptr< IHTTPRequestHandler > &handler)
virtual MHD_RESULT FinalizeRequest (const std::shared_ptr< IHTTPRequestHandler > &handler, int responseStatus, struct MHD_Response *response)
Private Member Functions
struct MHD_Daemon * StartMHD (unsigned int flags, int port)
std::shared_ptr< IHTTPRequestHandler > FindRequestHandler (const HTTPRequest &request) const
MHD_RESULT AskForAuthentication (const HTTPRequest &request) const
bool IsAuthenticated (const HTTPRequest &request) const
bool IsRequestCacheable (const HTTPRequest &request) const
bool IsRequestRanged (const HTTPRequest &request, const CDateTime &lastModified) const
void SetupPostDataProcessing (const HTTPRequest &request, ConnectionHandler *connectionHandler, std::shared_ptr< IHTTPRequestHandler > handler, void **con_cls) const
bool ProcessPostData (const HTTPRequest &request, ConnectionHandler *connectionHandler, const char *upload_data, size_t *upload_data_size, void **con_cls) const
void FinalizePostDataProcessing (ConnectionHandler *connectionHandler) const
MHD_RESULT CreateMemoryDownloadResponse (const std::shared_ptr< IHTTPRequestHandler > &handler, struct MHD_Response *&response) const
MHD_RESULT CreateRangedMemoryDownloadResponse (const std::shared_ptr< IHTTPRequestHandler > &handler, struct MHD_Response *&response) const
MHD_RESULT CreateRedirect (struct MHD_Connection *connection, const std::string &strURL, struct MHD_Response *&response) const
MHD_RESULT CreateFileDownloadResponse (const std::shared_ptr< IHTTPRequestHandler > &handler, struct MHD_Response *&response) const
MHD_RESULT CreateErrorResponse (struct MHD_Connection *connection, int responseType, HTTPMethod method, struct MHD_Response *&response) const
MHD_RESULT CreateMemoryDownloadResponse (struct MHD_Connection *connection, const void *data, size_t size, bool free, bool copy, struct MHD_Response *&response) const
MHD_RESULT SendResponse (const HTTPRequest &request, int responseStatus, MHD_Response *response) const
MHD_RESULT SendErrorResponse (const HTTPRequest &request, int errorType, HTTPMethod method) const
MHD_RESULT AddHeader (struct MHD_Response *response, const std::string &name, const std::string &value) const
void LogRequest (const HTTPRequest &request) const
void LogResponse (const HTTPRequest &request, int responseStatus) const
bool LoadCert (std::string &skey, std::string &scert)
Static Private Member Functions
static std::string CreateMimeTypeFromExtension (const char *ext)
static void * UriRequestLogger (void *cls, const char *uri)
static ssize_t ContentReaderCallback (void *cls, uint64_t pos, char *buf, size_t max)
static void ContentReaderFreeCallback (void *cls)
static MHD_RESULT AnswerToConnection (void *cls, struct MHD_Connection *connection, const char *url, const char *method, const char *version, const char *upload_data, size_t *upload_data_size, void **con_cls)
static MHD_RESULT HandlePostField (void *cls, enum MHD_ValueKind kind, const char *key, const char *filename, const char *content_type, const char *transfer_encoding, const char *data, uint64_t off, size_t size)
static Logger GetLogger ()
Private Attributes
uint16_t m_port = 0
struct MHD_Daemon * m_daemon_ip6 = nullptr
struct MHD_Daemon * m_daemon_ip4 = nullptr
bool m_running = false
size_t m_thread_stacksize = 0
bool m_authenticationRequired = false
std::string m_authenticationUsername
std::string m_authenticationPassword
std::string m_key
std::string m_cert
CCriticalSection m_critSection
std::vector< IHTTPRequestHandler * > m_requestHandlers
Logger m_logger
Member Typedef Documentation
ConnectionHandler
typedef struct CWebServer::ConnectionHandler CWebServer::ConnectionHandler protected
Constructor & Destructor Documentation
CWebServer()
CWebServer::CWebServer ()
References m_logger, and m_thread_stacksize.
~CWebServer()
virtual CWebServer::~CWebServer () virtual default
Member Function Documentation
AddHeader()
MHD_RESULT CWebServer::AddHeader (struct MHD_Response * response, const std::string & name, const std::string & value) const private
References CServiceBroker::GetLogging(), LOGWEBSERVER, m_logger, name, and value.
Referenced by AskForAuthentication(), CreateRedirect(), and FinalizeRequest().
AnswerToConnection()
MHD_RESULT CWebServer::AnswerToConnection (void * cls, struct MHD_Connection * connection, const char * url, const char * method, const char * version, const char * upload_data, size_t * upload_data_size, void ** con_cls) static private
References CWebServer::ConnectionHandler::fullUri, GetHTTPMethod(), GetLogger(), HandlePartialRequest(), CWebServer::ConnectionHandler::isNew, and LogRequest().
Referenced by StartMHD().
AskForAuthentication()
MHD_RESULT CWebServer::AskForAuthentication (const HTTPRequest & request) const private
References AddHeader(), HTTPRequest::connection, create_response(), CCompileInfo::GetAppName(), LogResponse(), and m_logger.
Referenced by HandlePartialRequest().
ContentReaderCallback()
ssize_t CWebServer::ContentReaderCallback (void * cls, uint64_t pos, char * buf, size_t max) static private
References HttpFileDownloadContext::boundary, HttpFileDownloadContext::boundaryWithHeader, HttpFileDownloadContext::boundaryWritten, CLog::CanLogComponent(), end(), HttpFileDownloadContext::file, CHttpRanges::GetFirst(), CHttpRange::GetFirstPosition(), CHttpRange::GetLastPosition(), GetLogger(), CServiceBroker::GetLogging(), HEADER_NEWLINE, CHttpRanges::IsEmpty(), LOGWEBSERVER, max, HttpFileDownloadContext::rangeCountTotal, HttpFileDownloadContext::ranges, CHttpRanges::Remove(), CHttpRanges::Size(), and HttpFileDownloadContext::writePosition.
Referenced by CreateFileDownloadResponse().
ContentReaderFreeCallback()
void CWebServer::ContentReaderFreeCallback (void * cls) static private
References CLog::CanLogComponent(), GetLogger(), CServiceBroker::GetLogging(), and LOGWEBSERVER.
Referenced by CreateFileDownloadResponse().
CreateErrorResponse()
MHD_RESULT CWebServer::CreateErrorResponse (struct MHD_Connection * connection, int responseType, HTTPMethod method, struct MHD_Response *& response) const private
References create_response(), m_logger, NOT_SUPPORTED, and PAGE_FILE_NOT_FOUND.
Referenced by HandleRequest(), and SendErrorResponse().
CreateFileDownloadResponse()
MHD_RESULT CWebServer::CreateFileDownloadResponse (const std::shared_ptr< IHTTPRequestHandler > & handler, struct MHD_Response *& response) const private
References CFileUtils::CheckFileAccessAllowed(), HTTPRequest::connection, ContentReaderCallback(), ContentReaderFreeCallback(), HTTPResponseDetails::contentType, CreateMimeTypeFromExtension(), HttpRangeUtils::GenerateContentRangeHeaderValue(), URIUtils::GetExtension(), HTTPRequestHandlerUtils::GetRequestedRanges(), HEADER_NEWLINE, CHttpRanges::IsEmpty(), m_logger, HTTPRequest::method, HTTPRequest::pathUrl, HTTPRequest::ranges, XFILE::READ_NO_CACHE, and SendErrorResponse().
Referenced by HandleRequest().
CreateMemoryDownloadResponse() [1/2]
MHD_RESULT CWebServer::CreateMemoryDownloadResponse (const std::shared_ptr< IHTTPRequestHandler > & handler, struct MHD_Response *& response) const private
References HTTPRequest::connection, CreateMemoryDownloadResponse(), CreateRangedMemoryDownloadResponse(), CHttpResponseRange::GetData(), CHttpRange::GetFirstPosition(), CHttpRange::GetLastPosition(), CHttpRange::GetLength(), HTTPMemoryDownloadFreeCopy, HTTPMemoryDownloadFreeNoCopy, HTTPMemoryDownloadNoFreeCopy, HTTPMemoryDownloadNoFreeNoCopy, CHttpRanges::IsEmpty(), CHttpResponseRange::IsValid(), m_logger, HTTPRequest::method, HTTPRequest::ranges, SendErrorResponse(), CHttpRanges::Size(), and HTTPResponseDetails::type.
Referenced by CreateMemoryDownloadResponse(), CreateRangedMemoryDownloadResponse(), and HandleRequest().
CreateMemoryDownloadResponse() [2/2]
MHD_RESULT CWebServer::CreateMemoryDownloadResponse (struct MHD_Connection * connection, const void * data, size_t size, bool free, bool copy, struct MHD_Response *& response) const private
References copy(), create_response(), data(), and m_logger.
CreateMimeTypeFromExtension()
std::string CWebServer::CreateMimeTypeFromExtension (const char * ext) static private
References CMime::GetMimeType().
Referenced by CreateFileDownloadResponse().
CreateRangedMemoryDownloadResponse()
MHD_RESULT CWebServer::CreateRangedMemoryDownloadResponse (const std::shared_ptr< IHTTPRequestHandler > & handler, struct MHD_Response *& response) const private
References HTTPRequest::connection, CreateMemoryDownloadResponse(), HttpRangeUtils::GenerateContentRangeHeaderValue(), HEADER_NEWLINE, HTTPMemoryDownloadFreeCopy, HTTPMemoryDownloadFreeNoCopy, HTTPResponseDetails::totalLength, and HTTPResponseDetails::type.
Referenced by CreateMemoryDownloadResponse().
CreateRedirect()
MHD_RESULT CWebServer::CreateRedirect (struct MHD_Connection * connection, const std::string & strURL, struct MHD_Response *& response) const private
References AddHeader(), create_response(), and m_logger.
Referenced by HandleRequest().
FinalizePostDataProcessing()
void CWebServer::FinalizePostDataProcessing (ConnectionHandler * connectionHandler) const private
References CWebServer::ConnectionHandler::postprocessor.
Referenced by HandlePartialRequest().
FinalizeRequest()
MHD_RESULT CWebServer::FinalizeRequest (const std::shared_ptr< IHTTPRequestHandler > & handler, int responseStatus, struct MHD_Response * response) protected virtual
References AddHeader(), HTTPResponseDetails::contentType, CDateTime::GetAsRFC1123DateTime(), CDateTime::GetCurrentDateTime(), CDateTimeSpan::GetSecondsTotal(), HEADER_VALUE_NO_CACHE, HTTPResponseDetails::headers, CDateTime::IsValid(), and SendResponse().
Referenced by HandlePartialRequest(), and HandleRequest().
FindRequestHandler()
std::shared_ptr< IHTTPRequestHandler > CWebServer::FindRequestHandler (const HTTPRequest & request) const private
References m_requestHandlers.
Referenced by HandlePartialRequest().
GetLogger()
Logger CWebServer::GetLogger () static private
References CLog::GetLogger(), and CServiceBroker::GetLogging().
Referenced by AnswerToConnection(), ContentReaderCallback(), ContentReaderFreeCallback(), HandlePostField(), and UriRequestLogger().
HandlePartialRequest()
MHD_RESULT CWebServer::HandlePartialRequest (struct MHD_Connection * connection, ConnectionHandler * connectionHandler, const HTTPRequest & request, const char * upload_data, size_t * upload_data_size, void ** con_cls) protected virtual
References AskForAuthentication(), create_response(), FinalizePostDataProcessing(), FinalizeRequest(), FindRequestHandler(), GET, CDateTime::GetAsUTCDateTime(), HTTPRequestHandlerUtils::GetRequestHeaderValue(), HandleRequest(), HEAD, IsAuthenticated(), IsRequestCacheable(), IsRequestRanged(), CDateTime::IsValid(), m_logger, HTTPRequest::method, HTTPRequest::pathUrl, POST, ProcessPostData(), SendErrorResponse(), CDateTime::SetFromRFC1123DateTime(), and SetupPostDataProcessing().
Referenced by AnswerToConnection().
HandlePostField()
MHD_RESULT CWebServer::HandlePostField (void * cls, enum MHD_ValueKind kind, const char * key, const char * filename, const char * content_type, const char * transfer_encoding, const char * data, uint64_t off, size_t size) static private
References data(), GetLogger(), and CWebServer::ConnectionHandler::requestHandler.
Referenced by SetupPostDataProcessing().
HandleRequest()
MHD_RESULT CWebServer::HandleRequest (const std::shared_ptr< IHTTPRequestHandler > & handler) protected virtual
References HTTPRequest::connection, CreateErrorResponse(), CreateFileDownloadResponse(), CreateMemoryDownloadResponse(), CreateRedirect(), FinalizeRequest(), HTTPError, HTTPFileDownload, HTTPMemoryDownloadFreeCopy, HTTPMemoryDownloadFreeNoCopy, HTTPMemoryDownloadNoFreeCopy, HTTPMemoryDownloadNoFreeNoCopy, HTTPNone, HTTPRedirect, m_logger, HTTPRequest::method, HTTPRequest::pathUrl, SendErrorResponse(), HTTPResponseDetails::status, and HTTPResponseDetails::type.
Referenced by HandlePartialRequest().
IsAuthenticated()
bool CWebServer::IsAuthenticated (const HTTPRequest & request) const private
References HTTPRequest::connection, m_authenticationPassword, m_authenticationRequired, m_authenticationUsername, and m_critSection.
Referenced by HandlePartialRequest().
IsRequestCacheable()
bool CWebServer::IsRequestCacheable (const HTTPRequest & request) const private
References HTTPRequest::connection, HTTPRequestHandlerUtils::GetRequestHeaderValue(), and HEADER_VALUE_NO_CACHE.
Referenced by HandlePartialRequest().
IsRequestRanged()
bool CWebServer::IsRequestRanged (const HTTPRequest & request, const CDateTime & lastModified) const private
References CHttpRanges::Clear(), HTTPRequest::connection, CDateTime::GetAsUTCDateTime(), HTTPRequestHandlerUtils::GetRequestHeaderValue(), CHttpRanges::IsEmpty(), CDateTime::IsValid(), CHttpRanges::Parse(), and CDateTime::SetFromRFC1123DateTime().
Referenced by HandlePartialRequest().
IsStarted()
bool CWebServer::IsStarted ()
References m_running.
Referenced by TestHTTPDirectory::TearDown(), and TestWebServer::TearDown().
LoadCert()
bool CWebServer::LoadCert (std::string & skey, std::string & scert) private
References XFILE::CFile::Close(), and m_logger.
Referenced by StartMHD().
LogRequest() [1/2]
void CWebServer::LogRequest (const char * uri) const protected virtual
References m_logger.
Referenced by AnswerToConnection(), and UriRequestLogger().
LogRequest() [2/2]
void CWebServer::LogRequest (const HTTPRequest & request) const private
References HTTPRequest::connection, GetHTTPMethod(), CServiceBroker::GetLogging(), HTTPRequestHandlerUtils::GetRequestHeaderValues(), LOGWEBSERVER, m_logger, HTTPRequest::method, HTTPRequest::pathUrlFull, values, and HTTPRequest::version.
LogResponse()
void CWebServer::LogResponse (const HTTPRequest & request, int responseStatus) const private
References HTTPRequest::connection, CServiceBroker::GetLogging(), HTTPRequestHandlerUtils::GetRequestHeaderValues(), LOGWEBSERVER, m_logger, HTTPRequest::pathUrlFull, and HTTPRequest::version.
Referenced by AskForAuthentication(), and SendResponse().
ProcessPostData()
bool CWebServer::ProcessPostData (const HTTPRequest & request, ConnectionHandler * connectionHandler, const char * upload_data, size_t * upload_data_size, void ** con_cls) const private
References CWebServer::ConnectionHandler::errorStatus, m_logger, HTTPRequest::pathUrl, CWebServer::ConnectionHandler::postprocessor, and CWebServer::ConnectionHandler::requestHandler.
Referenced by HandlePartialRequest().
RegisterRequestHandler()
void CWebServer::RegisterRequestHandler (IHTTPRequestHandler * handler)
References m_requestHandlers.
Referenced by TestHTTPDirectory::SetUp(), and TestWebServer::SetUp().
SendErrorResponse()
MHD_RESULT CWebServer::SendErrorResponse (const HTTPRequest & request, int errorType, HTTPMethod method) const private
References HTTPRequest::connection, CreateErrorResponse(), and SendResponse().
Referenced by CreateFileDownloadResponse(), CreateMemoryDownloadResponse(), HandlePartialRequest(), and HandleRequest().
SendResponse()
MHD_RESULT CWebServer::SendResponse (const HTTPRequest & request, int responseStatus, MHD_Response * response) const private
References HTTPRequest::connection, and LogResponse().
Referenced by FinalizeRequest(), and SendErrorResponse().
SetCredentials()
void CWebServer::SetCredentials (const std::string & username, const std::string & password)
References m_authenticationPassword, m_authenticationRequired, m_authenticationUsername, and m_critSection.
Referenced by Start().
SetupPostDataProcessing()
void CWebServer::SetupPostDataProcessing (const HTTPRequest & request, ConnectionHandler * connectionHandler, std::shared_ptr< IHTTPRequestHandler > handler, void ** con_cls) const private
References HTTPRequest::connection, CWebServer::ConnectionHandler::errorStatus, HTTPRequestHandlerUtils::GetRequestHeaderValue(), HandlePostField(), m_logger, MAX_POST_BUFFER_SIZE, HTTPRequest::pathUrl, CWebServer::ConnectionHandler::postprocessor, and CWebServer::ConnectionHandler::requestHandler.
Referenced by HandlePartialRequest().
Start()
bool CWebServer::Start (uint16_t port, const std::string & username, const std::string & password)
References closesocket, CLog::GetLogger(), CServiceBroker::GetLogging(), m_daemon_ip4, m_daemon_ip6, m_logger, m_port, m_running, SetCredentials(), and StartMHD().
Referenced by TestHTTPDirectory::SetUp(), and TestWebServer::SetUp().
StartMHD()
struct MHD_Daemon * CWebServer::StartMHD (unsigned int flags, int port) private
References AnswerToConnection(), CServiceBroker::GetSettingsComponent(), LoadCert(), logFromMHD(), m_cert, m_key, m_thread_stacksize, panicHandlerForMHD(), CSettings::SETTING_SERVICES_WEBSERVERSSL, and UriRequestLogger().
Referenced by Start().
Stop()
bool CWebServer::Stop ()
References m_daemon_ip4, m_daemon_ip6, m_logger, m_port, and m_running.
Referenced by TestHTTPDirectory::TearDown(), and TestWebServer::TearDown().
UnregisterRequestHandler()
void CWebServer::UnregisterRequestHandler (IHTTPRequestHandler * handler)
References m_requestHandlers.
Referenced by TestHTTPDirectory::TearDown(), and TestWebServer::TearDown().
UriRequestLogger()
void * CWebServer::UriRequestLogger (void * cls, const char * uri) static private
References GetLogger(), and LogRequest().
Referenced by StartMHD().
WebServerSupportsSSL()
bool CWebServer::WebServerSupportsSSL () static
Referenced by CSettingConditions::Initialize().
Member Data Documentation
m_authenticationPassword
std::string CWebServer::m_authenticationPassword private
Referenced by IsAuthenticated(), and SetCredentials().
m_authenticationRequired
bool CWebServer::m_authenticationRequired = false private
Referenced by IsAuthenticated(), and SetCredentials().
m_authenticationUsername
std::string CWebServer::m_authenticationUsername private
Referenced by IsAuthenticated(), and SetCredentials().
m_cert
std::string CWebServer::m_cert private
Referenced by StartMHD().
m_critSection
CCriticalSection CWebServer::m_critSection mutable private
Referenced by IsAuthenticated(), and SetCredentials().
m_daemon_ip4
struct MHD_Daemon* CWebServer::m_daemon_ip4 = nullptr private
Referenced by Start(), and Stop().
m_daemon_ip6
struct MHD_Daemon* CWebServer::m_daemon_ip6 = nullptr private
Referenced by Start(), and Stop().
m_key
std::string CWebServer::m_key private
Referenced by StartMHD().
m_logger
Logger CWebServer::m_logger private
Referenced by AddHeader(), AskForAuthentication(), CreateErrorResponse(), CreateFileDownloadResponse(), CreateMemoryDownloadResponse(), CreateMemoryDownloadResponse(), CreateRedirect(), CWebServer(), HandlePartialRequest(), HandleRequest(), LoadCert(), LogRequest(), LogRequest(), LogResponse(), ProcessPostData(), SetupPostDataProcessing(), Start(), and Stop().
m_port
uint16_t CWebServer::m_port = 0 private
Referenced by Start(), and Stop().
m_requestHandlers
std::vector<IHTTPRequestHandler *> CWebServer::m_requestHandlers private
Referenced by FindRequestHandler(), RegisterRequestHandler(), and UnregisterRequestHandler().
m_running
bool CWebServer::m_running = false private
Referenced by IsStarted(), Start(), and Stop().
m_thread_stacksize
size_t CWebServer::m_thread_stacksize = 0 private
Referenced by CWebServer(), and StartMHD().
The documentation for this class was generated from the following files:
WebServer.h
WebServer.cpp