Kodi Documentation: kodi::addon Namespace Reference
kodi::addon Namespace Reference
Classes
class AudioDecoderInfoTag
class AudioEncoderInfoTag
class CAddonBase
class CInstanceAudioDecoder
class CInstanceAudioEncoder
class CInstanceGame
class CInstanceImageDecoder
class CInstanceInputStream
class CInstancePeripheral
class CInstancePVRClient
class CInstanceScreensaver
class CInstanceVFS
class CInstanceVideoCodec
class CInstanceVisualization
struct CPrivateBase
Internal used structure to have stored C API data above and available for everything below.
class CSettingValue
class CStructHdl
struct DriverPrimitive
class DynamicCStructHdl
class GameControllerLayout
class IAddonInstance
class IInstanceInfo
class ImageDecoderInfoTag
class InputstreamCapabilities
class InputstreamContentlightMetadata
class InputstreamInfo
class InputstreamMasteringMetadata
class InputstreamProperty
class InputstreamTimes
class Joystick
class JoystickFeature
class Peripheral
class PeripheralCapabilities
class PeripheralEvent
class PeripheralVector
class PVRCapabilities
class PVRChannel
class PVRChannelGroup
class PVRChannelGroupMember
class PVRChannelGroupMembersResultSet
class PVRChannelGroupsResultSet
class PVRChannelsResultSet
class PVRCodec
class PVRDescrambleInfo
class PVREDLEntry
class PVREPGTag
class PVREPGTagsResultSet
class PVRIntSettingDefinition
class PVRMenuhook
class PVRProvider
class PVRProvidersResultSet
class PVRRecording
class PVRRecordingsResultSet
class PVRSettingDefinition
class PVRSettingKeyValuePair
class PVRSignalStatus
class PVRStreamProperties
class PVRStreamProperty
class PVRStreamTimes
class PVRStringSettingDefinition
class PVRTimer
class PVRTimersResultSet
class PVRTimerType
class PVRTypeIntValue
class PVRTypeStringValue
class StreamCryptoSession
class VFSUrl
class VideoCodecInitdata
class VisualizationTrack
Typedefs
typedef PeripheralVector< Peripheral, PERIPHERAL_INFO > Peripherals
typedef PeripheralVector< PeripheralEvent, PERIPHERAL_EVENT > PeripheralEvents
typedef PeripheralVector< Joystick, JOYSTICK_INFO > Joysticks
typedef PeripheralVector< DriverPrimitive, JOYSTICK_DRIVER_PRIMITIVE > DriverPrimitives
typedef PeripheralVector< JoystickFeature, JOYSTICK_FEATURE > JoystickFeatures
using VFSFileHandle = VFS_FILE_HANDLE
VFS add-on file handle
This used to handle opened files of addon with related memory pointer about class or structure and to have on further file control functions available.
Functions
char * AllocAndCopyString (const char *source)
Internally used helper to dynamically allocate and fill a char array.
void FreeString (const char *str)
Internally used helper to delete a string that was allocated via AllocAndCopyString.
void ReallocAndCopyString (const char **stringToRealloc, const char *stringToCopy)
Internally used helper to dynamically reallocate and fill a char array.
template<typename CPP_CLASS , typename C_STRUCT >
static C_STRUCT ** AllocAndCopyPointerArray (std::vector< CPP_CLASS > &sourceVector, unsigned int &targetArraySize)
Internally used helper to convert c-struct data contained in a vector to an array of c-struct pointers.
template<typename CPP_CLASS , typename C_STRUCT >
static void FreeDynamicPointerArray (C_STRUCT **targetArray, unsigned int targetArraySize)
Internally used helper to free an array of of c-struct pointers.
template<typename CPP_CLASS , typename C_STRUCT >
static void FreeStaticPointerArray (C_STRUCT **targetArray, unsigned int targetArraySize)
Internally used helper to free an array of of c-struct pointers.
std::string ATTR_DLL_LOCAL GetAddonPath (const std::string &append="")
To get the addon system installation folder.
std::string ATTR_DLL_LOCAL GetLibPath (const std::string &append="")
This function gives OS associated executable binary path of the addon.
std::string ATTR_DLL_LOCAL GetUserPath (const std::string &append="")
To get the user-related folder of the addon.
std::string ATTR_DLL_LOCAL GetTempPath (const std::string &append="")
To get a temporary path for the addon.
std::string ATTR_DLL_LOCAL GetLocalizedString (uint32_t labelId, const std::string &defaultStr="")
Returns an addon's localized 'unicode string'.
bool ATTR_DLL_LOCAL OpenSettings ()
Opens this Add-Ons settings dialog.
bool ATTR_DLL_LOCAL IsSettingUsingDefault (const std::string &settingName)
Check the given setting name is set to default value.
bool ATTR_DLL_LOCAL CheckSettingString (const std::string &settingName, std::string &settingValue)
Check and get a string setting value.
std::string ATTR_DLL_LOCAL GetSettingString (const std::string &settingName, const std::string &defaultValue="")
Get string setting value.
void ATTR_DLL_LOCAL SetSettingString (const std::string &settingName, const std::string &settingValue)
Set string setting of addon.
bool ATTR_DLL_LOCAL CheckSettingInt (const std::string &settingName, int &settingValue)
Check and get a integer setting value.
int ATTR_DLL_LOCAL GetSettingInt (const std::string &settingName, int defaultValue=0)
Get integer setting value.
void ATTR_DLL_LOCAL SetSettingInt (const std::string &settingName, int settingValue)
Set integer setting of addon.
bool ATTR_DLL_LOCAL CheckSettingBoolean (const std::string &settingName, bool &settingValue)
Check and get a boolean setting value.
bool ATTR_DLL_LOCAL GetSettingBoolean (const std::string &settingName, bool defaultValue=false)
Get boolean setting value.
void ATTR_DLL_LOCAL SetSettingBoolean (const std::string &settingName, bool settingValue)
Set boolean setting of addon.
bool ATTR_DLL_LOCAL CheckSettingFloat (const std::string &settingName, float &settingValue)
Check and get a floating point setting value.
float ATTR_DLL_LOCAL GetSettingFloat (const std::string &settingName, float defaultValue=0.0f)
Get floating point setting value.
void ATTR_DLL_LOCAL SetSettingFloat (const std::string &settingName, float settingValue)
Set floating point setting of addon.
template<typename enumType >
bool ATTR_DLL_LOCAL CheckSettingEnum (const std::string &settingName, enumType &settingValue)
Check and get a enum setting value.
template<typename enumType >
enumType ATTR_DLL_LOCAL GetSettingEnum (const std::string &settingName, enumType defaultValue=static_cast< enumType >(0))
Get enum setting value.
template<typename enumType >
void ATTR_DLL_LOCAL SetSettingEnum (const std::string &settingName, enumType settingValue)
Set enum setting of addon.
std::string ATTR_DLL_LOCAL GetAddonInfo (const std::string &id)
Returns the value of an addon property as a string.
void * GetInterface (const std::string &name, const std::string &version)
Returns a function table to a named interface.
std::string ATTR_DLL_LOCAL GetKodiTypeVersion (int type)
To get used version inside Kodi itself about asked type.
std::string ATTR_DLL_LOCAL TranslateAddonStatus (ADDON_STATUS status)
Get to related ADDON_STATUS a human readable text.
const char * GetTypeVersion (int type)
const char * GetTypeMinVersion (int type)
const char * GetTypeName (int type)
int GetTypeId (const char *name)
Typedef Documentation
DriverPrimitives
typedef PeripheralVector<DriverPrimitive, JOYSTICK_DRIVER_PRIMITIVE> kodi::addon::DriverPrimitives
JoystickFeatures
typedef PeripheralVector<JoystickFeature, JOYSTICK_FEATURE> kodi::addon::JoystickFeatures
Joysticks
typedef PeripheralVector<Joystick, JOYSTICK_INFO> kodi::addon::Joysticks
PeripheralEvents
typedef PeripheralVector<PeripheralEvent, PERIPHERAL_EVENT> kodi::addon::PeripheralEvents
Peripherals
typedef PeripheralVector<Peripheral, PERIPHERAL_INFO> kodi::addon::Peripherals
Function Documentation
AllocAndCopyPointerArray()
template<typename CPP_CLASS , typename C_STRUCT > static C_STRUCT ** kodi::addon::AllocAndCopyPointerArray (std::vector< CPP_CLASS > & sourceVector, unsigned int & targetArraySize) inline static
Internally used helper to convert c-struct data contained in a vector to an array of c-struct pointers.
AllocAndCopyString()
char * kodi::addon::AllocAndCopyString (const char * source) inline
Internally used helper to dynamically allocate and fill a char array.
Referenced by kodi::addon::CInstancePVRClient::ADDON_GetBackendHostname(), kodi::addon::CInstancePVRClient::ADDON_GetBackendName(), kodi::addon::CInstancePVRClient::ADDON_GetBackendVersion(), kodi::addon::CInstancePVRClient::ADDON_GetConnectionString(), kodi::addon::PVREPGTag::AllocResources(), kodi::addon::PVRTypeIntValue::AllocResources(), kodi::addon::PVRTypeStringValue::AllocResources(), kodi::addon::PVRChannel::AllocResources(), kodi::addon::PVRChannelGroup::AllocResources(), kodi::addon::PVRChannelGroupMember::AllocResources(), kodi::addon::PVRDescrambleInfo::AllocResources(), kodi::addon::PVRStreamProperty::AllocResources(), kodi::addon::PVRProvider::AllocResources(), kodi::addon::PVRRecording::AllocResources(), kodi::addon::PVRSettingDefinition::AllocResources(), kodi::addon::PVRSettingKeyValuePair::AllocResources(), kodi::addon::PVRSignalStatus::AllocResources(), kodi::addon::PVRStringSettingDefinition::AllocResources(), kodi::addon::PVRTimer::AllocResources(), kodi::addon::PVRTimerType::AllocResources(), and ReallocAndCopyString().
FreeDynamicPointerArray()
template<typename CPP_CLASS , typename C_STRUCT > static void kodi::addon::FreeDynamicPointerArray (C_STRUCT ** targetArray, unsigned int targetArraySize) inline static
Internally used helper to free an array of of c-struct pointers.
FreeStaticPointerArray()
template<typename CPP_CLASS , typename C_STRUCT > static void kodi::addon::FreeStaticPointerArray (C_STRUCT ** targetArray, unsigned int targetArraySize) inline static
Internally used helper to free an array of of c-struct pointers.
FreeString()
void kodi::addon::FreeString (const char * str) inline
Internally used helper to delete a string that was allocated via AllocAndCopyString.
Referenced by kodi::addon::CInstancePVRClient::ADDON_FreeString(), kodi::addon::PVREPGTag::FreeResources(), kodi::addon::PVRTypeIntValue::FreeResources(), kodi::addon::PVRTypeStringValue::FreeResources(), kodi::addon::PVRChannel::FreeResources(), kodi::addon::PVRChannelGroup::FreeResources(), kodi::addon::PVRChannelGroupMember::FreeResources(), kodi::addon::PVRDescrambleInfo::FreeResources(), kodi::addon::PVRStreamProperty::FreeResources(), kodi::addon::PVRProvider::FreeResources(), kodi::addon::PVRRecording::FreeResources(), kodi::addon::PVRSettingDefinition::FreeResources(), kodi::addon::PVRSettingKeyValuePair::FreeResources(), kodi::addon::PVRSignalStatus::FreeResources(), kodi::addon::PVRStringSettingDefinition::FreeResources(), kodi::addon::PVRTimer::FreeResources(), kodi::addon::PVRTimerType::FreeResources(), and ReallocAndCopyString().
GetTypeId()
int kodi::addon::GetTypeId (const char * name) inline
Function used internally on add-on and in Kodi itself to get id number about given type name.
Parameters
[in] name The type name string to ask
Returns
Id number of the asked instance type
Warning
String must be lower case here!
References ADDON_GLOBAL_AUDIOENGINE, ADDON_GLOBAL_FILESYSTEM, ADDON_GLOBAL_GENERAL, ADDON_GLOBAL_GUI, ADDON_GLOBAL_MAIN, ADDON_GLOBAL_NETWORK, ADDON_GLOBAL_TOOLS, ADDON_INSTANCE_AUDIODECODER, ADDON_INSTANCE_AUDIOENCODER, ADDON_INSTANCE_GAME, ADDON_INSTANCE_IMAGEDECODER, ADDON_INSTANCE_INPUTSTREAM, ADDON_INSTANCE_PERIPHERAL, ADDON_INSTANCE_PVR, ADDON_INSTANCE_SCREENSAVER, ADDON_INSTANCE_VFS, ADDON_INSTANCE_VIDEOCODEC, ADDON_INSTANCE_VISUALIZATION, and name.
GetTypeMinVersion()
const char * kodi::addon::GetTypeMinVersion (int type) inline
This is used from Kodi to get the minimum supported version of add-on parts. It is compiled in add-on and also in Kodi itself, with this can be Kodi compare the version from him with them on add-on.
Parameters
[in] type The with 'enum ADDON_TYPE' type to ask
Returns
version The minimum version of asked type
References ADDON_GLOBAL_AUDIOENGINE, ADDON_GLOBAL_FILESYSTEM, ADDON_GLOBAL_GENERAL, ADDON_GLOBAL_GUI, ADDON_GLOBAL_MAIN, ADDON_GLOBAL_NETWORK, ADDON_GLOBAL_TOOLS, ADDON_GLOBAL_VERSION_AUDIOENGINE_MIN, ADDON_GLOBAL_VERSION_FILESYSTEM_MIN, ADDON_GLOBAL_VERSION_GENERAL_MIN, ADDON_GLOBAL_VERSION_GUI_MIN, ADDON_GLOBAL_VERSION_MAIN_MIN, ADDON_GLOBAL_VERSION_NETWORK_MIN, ADDON_GLOBAL_VERSION_TOOLS_MIN, ADDON_INSTANCE_AUDIODECODER, ADDON_INSTANCE_AUDIOENCODER, ADDON_INSTANCE_GAME, ADDON_INSTANCE_IMAGEDECODER, ADDON_INSTANCE_INPUTSTREAM, ADDON_INSTANCE_PERIPHERAL, ADDON_INSTANCE_PVR, ADDON_INSTANCE_SCREENSAVER, ADDON_INSTANCE_VERSION_AUDIODECODER_MIN, ADDON_INSTANCE_VERSION_AUDIOENCODER_MIN, ADDON_INSTANCE_VERSION_GAME_MIN, ADDON_INSTANCE_VERSION_IMAGEDECODER_MIN, ADDON_INSTANCE_VERSION_INPUTSTREAM_MIN, ADDON_INSTANCE_VERSION_PERIPHERAL_MIN, ADDON_INSTANCE_VERSION_PVR_MIN, ADDON_INSTANCE_VERSION_SCREENSAVER_MIN, ADDON_INSTANCE_VERSION_VFS_MIN, ADDON_INSTANCE_VERSION_VIDEOCODEC_MIN, ADDON_INSTANCE_VERSION_VISUALIZATION_MIN, ADDON_INSTANCE_VFS, ADDON_INSTANCE_VIDEOCODEC, and ADDON_INSTANCE_VISUALIZATION.
Referenced by ADDON::CAddonDll::CheckAPIVersion().
GetTypeName()
const char * kodi::addon::GetTypeName (int type) inline
Function used internally on add-on and in Kodi itself to get name about given type.
Parameters
[in] type The with 'enum ADDON_TYPE' defined type to ask
Returns
Name of the asked instance type
References ADDON_GLOBAL_AUDIOENGINE, ADDON_GLOBAL_FILESYSTEM, ADDON_GLOBAL_GENERAL, ADDON_GLOBAL_GUI, ADDON_GLOBAL_MAIN, ADDON_GLOBAL_NETWORK, ADDON_GLOBAL_TOOLS, ADDON_INSTANCE_AUDIODECODER, ADDON_INSTANCE_AUDIOENCODER, ADDON_INSTANCE_GAME, ADDON_INSTANCE_IMAGEDECODER, ADDON_INSTANCE_INPUTSTREAM, ADDON_INSTANCE_PERIPHERAL, ADDON_INSTANCE_PVR, ADDON_INSTANCE_SCREENSAVER, ADDON_INSTANCE_VIDEOCODEC, and ADDON_INSTANCE_VISUALIZATION.
Referenced by ADDON::CAddonDll::CheckAPIVersion().
GetTypeVersion()
const char * kodi::addon::GetTypeVersion (int type) inline
This is used from Kodi to get the active version of add-on parts. It is compiled in add-on and also in Kodi itself, with this can be Kodi compare the version from him with them on add-on.
Parameters
[in] type The with 'enum ADDON_TYPE' type to ask
Returns
version The current version of asked type
References ADDON_GLOBAL_AUDIOENGINE, ADDON_GLOBAL_FILESYSTEM, ADDON_GLOBAL_GENERAL, ADDON_GLOBAL_GUI, ADDON_GLOBAL_MAIN, ADDON_GLOBAL_NETWORK, ADDON_GLOBAL_TOOLS, ADDON_GLOBAL_VERSION_AUDIOENGINE, ADDON_GLOBAL_VERSION_FILESYSTEM, ADDON_GLOBAL_VERSION_GENERAL, ADDON_GLOBAL_VERSION_GUI, ADDON_GLOBAL_VERSION_MAIN, ADDON_GLOBAL_VERSION_NETWORK, ADDON_GLOBAL_VERSION_TOOLS, ADDON_INSTANCE_AUDIODECODER, ADDON_INSTANCE_AUDIOENCODER, ADDON_INSTANCE_GAME, ADDON_INSTANCE_IMAGEDECODER, ADDON_INSTANCE_INPUTSTREAM, ADDON_INSTANCE_PERIPHERAL, ADDON_INSTANCE_PVR, ADDON_INSTANCE_SCREENSAVER, ADDON_INSTANCE_VERSION_AUDIODECODER, ADDON_INSTANCE_VERSION_AUDIOENCODER, ADDON_INSTANCE_VERSION_GAME, ADDON_INSTANCE_VERSION_IMAGEDECODER, ADDON_INSTANCE_VERSION_INPUTSTREAM, ADDON_INSTANCE_VERSION_PERIPHERAL, ADDON_INSTANCE_VERSION_PVR, ADDON_INSTANCE_VERSION_SCREENSAVER, ADDON_INSTANCE_VERSION_VFS, ADDON_INSTANCE_VERSION_VIDEOCODEC, ADDON_INSTANCE_VERSION_VISUALIZATION, ADDON_INSTANCE_VFS, ADDON_INSTANCE_VIDEOCODEC, and ADDON_INSTANCE_VISUALIZATION.
Referenced by KODI::GAME::CGameClientStruct::CGameClientStruct(), ADDON::CAddonDll::CheckAPIVersion(), ADDON::Interface_Base::get_type_version(), and ADDON::IAddonInstanceHandler::IAddonInstanceHandler().
ReallocAndCopyString()
void kodi::addon::ReallocAndCopyString (const char ** stringToRealloc, const char * stringToCopy) inline
Internally used helper to dynamically reallocate and fill a char array.
References AllocAndCopyString(), and FreeString().
Referenced by kodi::addon::PVRSignalStatus::SetAdapterName(), kodi::addon::PVRSignalStatus::SetAdapterStatus(), kodi::addon::PVRDescrambleInfo::SetCardSystem(), kodi::addon::PVREPGTag::SetCast(), kodi::addon::PVRChannel::SetChannelName(), kodi::addon::PVRRecording::SetChannelName(), kodi::addon::PVRProvider::SetCountries(), kodi::addon::PVRStringSettingDefinition::SetDefaultValue(), kodi::addon::PVRTypeIntValue::SetDescription(), kodi::addon::PVRTypeStringValue::SetDescription(), kodi::addon::PVRTimerType::SetDescription(), kodi::addon::PVREPGTag::SetDirector(), kodi::addon::PVRRecording::SetDirectory(), kodi::addon::PVRTimer::SetDirectory(), kodi::addon::PVRTimer::SetEPGSearchString(), kodi::addon::PVREPGTag::SetEpisodeName(), kodi::addon::PVRRecording::SetEpisodeName(), kodi::addon::PVRRecording::SetFanartPath(), kodi::addon::PVREPGTag::SetFirstAired(), kodi::addon::PVRRecording::SetFirstAired(), kodi::addon::PVRDescrambleInfo::SetFrom(), kodi::addon::PVREPGTag::SetGenreDescription(), kodi::addon::PVRRecording::SetGenreDescription(), kodi::addon::PVRChannelGroup::SetGroupName(), kodi::addon::PVRChannelGroupMember::SetGroupName(), kodi::addon::PVRChannel::SetIconPath(), kodi::addon::PVREPGTag::SetIconPath(), kodi::addon::PVRProvider::SetIconPath(), kodi::addon::PVRRecording::SetIconPath(), kodi::addon::PVREPGTag::SetIMDBNumber(), kodi::addon::PVRProvider::SetLanguages(), kodi::addon::PVRChannel::SetMimeType(), kodi::addon::PVRSignalStatus::SetMuxName(), kodi::addon::PVRSettingDefinition::SetName(), kodi::addon::PVRStreamProperty::SetName(), kodi::addon::PVRProvider::SetName(), kodi::addon::PVREPGTag::SetOriginalTitle(), kodi::addon::PVREPGTag::SetParentalRatingCode(), kodi::addon::PVRRecording::SetParentalRatingCode(), kodi::addon::PVREPGTag::SetParentalRatingIcon(), kodi::addon::PVRRecording::SetParentalRatingIcon(), kodi::addon::PVREPGTag::SetParentalRatingSource(), kodi::addon::PVRRecording::SetParentalRatingSource(), kodi::addon::PVREPGTag::SetPlot(), kodi::addon::PVRRecording::SetPlot(), kodi::addon::PVREPGTag::SetPlotOutline(), kodi::addon::PVRRecording::SetPlotOutline(), kodi::addon::PVRDescrambleInfo::SetProtocol(), kodi::addon::PVRSignalStatus::SetProviderName(), kodi::addon::PVRRecording::SetProviderName(), kodi::addon::PVRDescrambleInfo::SetReader(), kodi::addon::PVRRecording::SetRecordingId(), kodi::addon::PVREPGTag::SetSeriesLink(), kodi::addon::PVRTimer::SetSeriesLink(), kodi::addon::PVRSignalStatus::SetServiceName(), kodi::addon::PVRSettingKeyValuePair::SetStringValue(), kodi::addon::PVRTimer::SetSummary(), kodi::addon::PVRRecording::SetThumbnailPath(), kodi::addon::PVREPGTag::SetTitle(), kodi::addon::PVRRecording::SetTitle(), kodi::addon::PVRTimer::SetTitle(), kodi::addon::PVREPGTag::SetTitleExtraInfo(), kodi::addon::PVRRecording::SetTitleExtraInfo(), kodi::addon::PVRTypeStringValue::SetValue(), kodi::addon::PVRStreamProperty::SetValue(), kodi::addon::PVRStringSettingDefinition::SetValues(), and kodi::addon::PVREPGTag::SetWriter().