Kodi Documentation: CSpeechRecognitionListener Class Reference
CSpeechRecognitionListener Class Reference
Public Member Functions
CSpeechRecognitionListener (int dialogId)
void OnReadyForSpeech () override
void OnError (int recognitionError) override
void OnResults (const std::vector< std::string > &results) override
Public Member Functions inherited from speech::ISpeechRecognitionListener
virtual ~ISpeechRecognitionListener ()=default
Private Attributes
const int m_dialogId {0}
Constructor & Destructor Documentation
CSpeechRecognitionListener()
CSpeechRecognitionListener::CSpeechRecognitionListener (int dialogId) inline
Member Function Documentation
OnError()
void CSpeechRecognitionListener::OnError (int recognitionError) inline override virtual
Implements speech::ISpeechRecognitionListener.
References CGUIDialogKaiToast::Error, g_localizeStrings, CLocalizeStrings::Get(), speech::RecognitionError::INSUFFICIENT_PERMISSIONS, speech::RecognitionError::NO_MATCH, CGUIDialogKaiToast::QueueNotification(), and speech::RecognitionError::SERVICE_NOT_AVAILABLE.
OnReadyForSpeech()
void CSpeechRecognitionListener::OnReadyForSpeech () inline override virtual
Reimplemented from speech::ISpeechRecognitionListener.
References g_localizeStrings, CLocalizeStrings::Get(), CGUIDialogKaiToast::Info, and CGUIDialogKaiToast::QueueNotification().
OnResults()
void CSpeechRecognitionListener::OnResults (const std::vector< std::string > & results) inline override virtual
Implements speech::ISpeechRecognitionListener.
References CTL_EDIT, CServiceBroker::GetAppMessenger(), GUI_MSG_SET_TEXT, m_dialogId, and CGUIMessage::SetLabel().
Member Data Documentation
m_dialogId
const int CSpeechRecognitionListener::m_dialogId {0} private
Referenced by OnResults().
The documentation for this class was generated from the following file:
GUIDialogKeyboardGeneric.cpp