Kodi Documentation: PlayerOperations.cpp File Reference
PlayerOperations.cpp File Reference
#include "PlayerOperations.h"
#include "AudioLibrary.h"
#include "FileItem.h"
#include "FileItemList.h"
#include "GUIInfoManager.h"
#include "GUIUserMessages.h"
#include "PartyModeManager.h"
#include "PlayListPlayer.h"
#include "SeekHandler.h"
#include "ServiceBroker.h"
#include "Util.h"
#include "VideoLibrary.h"
#include "application/Application.h"
#include "application/ApplicationComponents.h"
#include "application/ApplicationPlayer.h"
#include "application/ApplicationPowerHandling.h"
#include "cores/playercorefactory/PlayerCoreFactory.h"
#include "guilib/GUIComponent.h"
#include "guilib/GUIWindowManager.h"
#include "input/actions/Action.h"
#include "input/actions/ActionIDs.h"
#include "interfaces/builtins/Builtins.h"
#include "messaging/ApplicationMessenger.h"
#include "music/MusicDatabase.h"
#include "music/MusicFileItemClassify.h"
#include "pictures/SlideShowDelegator.h"
#include "pvr/PVRManager.h"
#include "pvr/PVRPlaybackState.h"
#include "pvr/channels/PVRChannel.h"
#include "pvr/channels/PVRChannelGroupMember.h"
#include "pvr/channels/PVRChannelGroupsContainer.h"
#include "pvr/epg/EpgContainer.h"
#include "pvr/epg/EpgInfoTag.h"
#include "pvr/guilib/PVRGUIActionsChannels.h"
#include "pvr/guilib/PVRGUIActionsPlayback.h"
#include "pvr/recordings/PVRRecordings.h"
#include "settings/AdvancedSettings.h"
#include "settings/DisplaySettings.h"
#include "settings/MediaSettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "utils/MathUtils.h"
#include "utils/PlayerUtils.h"
#include "utils/URIUtils.h"
#include "utils/Variant.h"
#include "video/VideoDatabase.h"
#include <map>
#include <tuple>
Namespaces
namespace anonymous_namespace{PlayerOperations.cpp}
Functions
void anonymous_namespace{PlayerOperations.cpp}::AppendAudioStreamFlagsAsBooleans (CVariant &list, StreamFlags flags)
void anonymous_namespace{PlayerOperations.cpp}::AppendSubtitleStreamFlagsAsBooleans (CVariant &list, StreamFlags flags)
std::string GetStringFromViewMode (ViewMode viewMode)
void GetNewValueForViewModeParameter (const CVariant &parameter, float stepSize, float minValue, float maxValue, float &result)
Variables
std::map< std::string, ViewMode > viewModes
Function Documentation
GetNewValueForViewModeParameter()
void GetNewValueForViewModeParameter (const CVariant & parameter, float stepSize, float minValue, float maxValue, float & result)
References CVariant::asDouble(), CVariant::isDouble(), and CVariant::isString().
Referenced by JSONRPC::CPlayerOperations::SetViewMode().
GetStringFromViewMode()
std::string GetStringFromViewMode (ViewMode viewMode)
References value, and viewModes.
Referenced by JSONRPC::CPlayerOperations::GetViewMode().
Variable Documentation
viewModes
std::map<std::string, ViewMode> viewModes
Initial value:
=
{
  {"normal", ViewModeNormal},
  {"zoom", ViewModeZoom},
  {"stretch4x3", ViewModeStretch4x3},
  {"widezoom", ViewModeWideZoom, },
  {"stretch16x9", ViewModeStretch16x9},
  {"original", ViewModeOriginal},
  {"stretch16x9nonlin", ViewModeStretch16x9Nonlin},
  {"zoom120width", ViewModeZoom120Width},
  {"zoom110width", ViewModeZoom110Width}
}
Referenced by CViewModeSettings::GetNextQuickCycleViewMode(), GetStringFromViewMode(), CViewModeSettings::GetViewModeStringIndex(), JSONRPC::CPlayerOperations::SetViewMode(), and CViewModeSettings::ViewModesFiller().