Kodi Documentation: CJobQueue Class Reference
CJobQueue Class Reference
Asynchronous jobs
Job Queue class to handle a queue of unique jobs to be processed sequentially.
#include <JobManager.h>
Classes
class CJobPointer
Public Member Functions
CJobQueue (bool lifo=false, unsigned int jobsAtOnce=1, CJob::PRIORITY priority=CJob::PRIORITY_LOW)
CJobQueue constructor.
~CJobQueue () override
CJobQueue destructor Cancels any in-process jobs, and destroys the job queue.
bool AddJob (CJob *job)
Add a job to the queue On completion of the job, destruction of the job queue or in case the job could not be added successfully, the CJob object will be destroyed.
template<typename F >
void Submit (F &&f)
Add a function f to this job queue.
void CancelJob (const CJob *job)
Cancel a job in the queue Cancels a job in the queue. Any job currently being processed may complete after this call has completed, but OnJobComplete will not be performed. If the job is only queued then it will be removed from the queue and deleted.
void CancelJobs ()
Cancel all jobs in the queue Removes all jobs from the queue. Any job currently being processed may complete after this call has completed, but OnJobComplete will not be performed.
bool IsProcessing () const
Check whether the queue is processing a job.
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
void OnJobAbort (unsigned int jobID, CJob *job) override
The callback used when a job will be aborted.
Public Member Functions inherited from IJobCallback
virtual ~IJobCallback ()=default
Destructor for job call back objects.
virtual void OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob *job)
An optional callback function that a job may call while processing.
Protected Member Functions
bool QueueEmpty () const
Returns if we still have jobs waiting to be processed NOTE: This function does not take into account the jobs that are currently processing.
Private Types
typedef std::deque< CJobPointer > Queue
typedef std::vector< CJobPointer > Processing
Private Member Functions
void OnJobNotify (CJob *job)
void QueueNextJob ()
Private Attributes
Queue m_jobQueue
Processing m_processing
unsigned int m_jobsAtOnce
CJob::PRIORITY m_priority
CCriticalSection m_section
bool m_lifo
Detailed Description
Job Queue class to handle a queue of unique jobs to be processed sequentially.
Holds a queue of jobs to be processed sequentially, either first in,first out or last in, first out. Jobs are unique, so queueing multiple copies of the same job (based on the CJob::operator==) will not add additional jobs.
Classes should subclass this class and override OnJobCallback should they require information from the job.
See also
CJob and IJobCallback
Member Typedef Documentation
Processing
typedef std::vector<CJobPointer> CJobQueue::Processing private
Queue
typedef std::deque<CJobPointer> CJobQueue::Queue private
Constructor & Destructor Documentation
CJobQueue()
CJobQueue::CJobQueue (bool lifo = false, unsigned int jobsAtOnce = 1, CJob::PRIORITY priority = CJob::PRIORITY_LOW)
CJobQueue constructor.
Parameters
lifo whether the queue should be processed last in first out or first in first out. Defaults to false (first in first out)
jobsAtOnce number of jobs at once to process. Defaults to 1.
priority priority of this queue.
See also
CJob
~CJobQueue()
CJobQueue::~CJobQueue () override
CJobQueue destructor Cancels any in-process jobs, and destroys the job queue.
See also
CJob
References CancelJobs().
Member Function Documentation
AddJob()
bool CJobQueue::AddJob (CJob * job)
Add a job to the queue On completion of the job, destruction of the job queue or in case the job could not be added successfully, the CJob object will be destroyed.
Parameters
job a pointer to the job to add. The job should be subclassed from CJob.
Returns
True if the job was added successfully, false otherwise. In case of failure, the passed CJob object will be deleted before returning from this method.
See also
CJob
References m_jobQueue, m_lifo, m_processing, m_section, and QueueNextJob().
Referenced by CMusicLibraryQueue::AddJob(), CVideoLibraryQueue::AddJob(), CTextureCache::BackgroundCacheImage(), CGUIDialogSubtitles::Download(), CTextureCache::IncrementUseCount(), CGUIWindowFileManager::OnCopy(), CGUIWindowFileManager::OnDelete(), CGUIWindowFileManager::OnMove(), KODI::CDRIP::CCDDARipper::RipCD(), KODI::CDRIP::CCDDARipper::RipTrack(), CGUIDialogSubtitles::Search(), and Submit().
CancelJob()
void CJobQueue::CancelJob (const CJob * job)
Cancel a job in the queue Cancels a job in the queue. Any job currently being processed may complete after this call has completed, but OnJobComplete will not be performed. If the job is only queued then it will be removed from the queue and deleted.
Parameters
job a pointer to the job to cancel. The job should be subclassed from CJob.
See also
CJob
References m_jobQueue, m_processing, and m_section.
Referenced by CMusicLibraryQueue::CancelJob(), and CVideoLibraryQueue::CancelJob().
CancelJobs()
void CJobQueue::CancelJobs ()
Cancel all jobs in the queue Removes all jobs from the queue. Any job currently being processed may complete after this call has completed, but OnJobComplete will not be performed.
See also
CJob
References m_jobQueue, m_processing, and m_section.
Referenced by CMusicLibraryQueue::CancelAllJobs(), CVideoLibraryQueue::CancelAllJobs(), CTextureCache::Deinitialize(), CGUIWindowMusicBase::OnContextButton(), KODI::CDRIP::CCDDARipper::OnJobComplete(), CGUIDialogSubtitles::~CGUIDialogSubtitles(), and ~CJobQueue().
IsProcessing()
bool CJobQueue::IsProcessing () const
Check whether the queue is processing a job.
References CServiceBroker::GetJobManager(), m_jobQueue, and m_processing.
Referenced by CMusicLibraryQueue::IsRunning(), and CVideoLibraryQueue::IsRunning().
OnJobAbort()
void CJobQueue::OnJobAbort (unsigned int jobID, CJob * job) override virtual
The callback used when a job will be aborted.
CJobQueue implementation will cleanup the internal processing queue and then queue the next job at the job manager, if any.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
job the job that has been aborted.
See also
CJobManager, IJobCallback and CJob
Reimplemented from IJobCallback.
References OnJobNotify().
OnJobComplete()
void CJobQueue::OnJobComplete (unsigned int jobID, bool success, CJob * job) override virtual
The callback used when a job completes.
CJobQueue implementation will cleanup the internal processing queue and then queue the next job at the job manager, if any.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
success the result from the DoWork call
job the job that has been processed.
See also
CJobManager, IJobCallback and CJob
Implements IJobCallback.
Reimplemented in CMusicLibraryQueue, CTextureCache, and CVideoLibraryQueue.
References OnJobNotify().
Referenced by KODI::CDRIP::CCDDARipper::OnJobComplete(), CMusicLibraryQueue::OnJobComplete(), CTextureCache::OnJobComplete(), CGUIDialogSubtitles::OnJobComplete(), CVideoLibraryQueue::OnJobComplete(), and CGUIWindowFileManager::OnJobComplete().
OnJobNotify()
void CJobQueue::OnJobNotify (CJob * job) private
References m_processing, m_section, and QueueNextJob().
Referenced by OnJobAbort(), and OnJobComplete().
QueueEmpty()
bool CJobQueue::QueueEmpty () const protected
Returns if we still have jobs waiting to be processed NOTE: This function does not take into account the jobs that are currently processing.
References m_jobQueue, and m_section.
Referenced by KODI::CDRIP::CCDDARipper::OnJobComplete(), CMusicLibraryQueue::OnJobComplete(), and CVideoLibraryQueue::OnJobComplete().
QueueNextJob()
void CJobQueue::QueueNextJob () private
References CServiceBroker::GetJobManager(), CJobQueue::CJobPointer::m_id, CJobQueue::CJobPointer::m_job, m_jobQueue, m_jobsAtOnce, m_priority, m_processing, and m_section.
Referenced by AddJob(), and OnJobNotify().
Submit()
template<typename F > void CJobQueue::Submit (F && f) inline
Add a function f to this job queue.
References AddJob(), and f.
Referenced by CEventSource< Event >::Publish().
Member Data Documentation
m_jobQueue
Queue CJobQueue::m_jobQueue private
Referenced by AddJob(), CancelJob(), CancelJobs(), IsProcessing(), QueueEmpty(), and QueueNextJob().
m_jobsAtOnce
unsigned int CJobQueue::m_jobsAtOnce private
Referenced by QueueNextJob().
m_lifo
bool CJobQueue::m_lifo private
Referenced by AddJob().
m_priority
CJob::PRIORITY CJobQueue::m_priority private
Referenced by QueueNextJob().
m_processing
Processing CJobQueue::m_processing private
Referenced by AddJob(), CancelJob(), CancelJobs(), IsProcessing(), OnJobNotify(), and QueueNextJob().
m_section
CCriticalSection CJobQueue::m_section mutable private
Referenced by AddJob(), CancelJob(), CancelJobs(), OnJobNotify(), QueueEmpty(), and QueueNextJob().
The documentation for this class was generated from the following files:
JobManager.h
JobManager.cpp