Kodi Documentation: ADDON::CAddonInfoBuilderFromDB Class Reference
ADDON::CAddonInfoBuilderFromDB Class Reference
#include <AddonInfoBuilder.h>
Public Member Functions
CAddonInfoBuilderFromDB ()
void SetId (std::string id)
void SetName (std::string name)
void SetLicense (std::string license)
void SetSummary (std::string summary)
void SetDescription (std::string description)
void SetDisclaimer (std::string disclaimer)
void SetAuthor (std::string author)
void SetSource (std::string source)
void SetWebsite (std::string website)
void SetForum (std::string forum)
void SetEMail (std::string email)
void SetIcon (std::string icon)
void SetArt (const std::string &type, std::string value)
void SetArt (std::map< std::string, std::string > art)
void SetScreenshots (std::vector< std::string > screenshots)
void SetChangelog (std::string changelog)
void SetLifecycleState (AddonLifecycleState state, std::string description)
void SetPath (std::string path)
void SetLibName (std::string libname)
void SetVersion (CAddonVersion version)
void SetDependencies (std::vector< DependencyInfo > dependencies)
void SetExtrainfo (InfoMap extrainfo)
void SetInstallDate (const CDateTime &installDate)
void SetLastUpdated (const CDateTime &lastUpdated)
void SetLastUsed (const CDateTime &lastUsed)
void SetOrigin (std::string origin)
void SetPackageSize (uint64_t size)
void SetExtensions (CAddonType addonType)
const AddonInfoPtr & get ()
Private Attributes
AddonInfoPtr m_addonInfo
Constructor & Destructor Documentation
CAddonInfoBuilderFromDB()
ADDON::CAddonInfoBuilderFromDB::CAddonInfoBuilderFromDB ()
Member Function Documentation
get()
const AddonInfoPtr & ADDON::CAddonInfoBuilderFromDB::get () inline
References m_addonInfo.
Referenced by AddonDatabaseTest::CreateAddon(), ADDON::CAddonDatabase::FindByAddonId(), ADDON::CAddonDatabase::GetAddon(), ADDON::CAddonDatabase::GetRepositoryContent(), TEST_F(), TEST_F(), and TEST_F().
SetArt() [1/2]
void ADDON::CAddonInfoBuilderFromDB::SetArt (const std::string & type, std::string value)
References m_addonInfo, and value.
Referenced by ADDON::CAddonDatabaseSerializer::DeserializeMetadata().
SetArt() [2/2]
void ADDON::CAddonInfoBuilderFromDB::SetArt (std::map< std::string, std::string > art)
References m_addonInfo.
SetAuthor()
void ADDON::CAddonInfoBuilderFromDB::SetAuthor (std::string author)
References m_addonInfo.
Referenced by ADDON::CAddonDatabaseSerializer::DeserializeMetadata(), and TEST_F().
SetChangelog()
void ADDON::CAddonInfoBuilderFromDB::SetChangelog (std::string changelog)
References m_addonInfo.
Referenced by ADDON::CAddonDatabase::FindByAddonId().
SetDependencies()
void ADDON::CAddonInfoBuilderFromDB::SetDependencies (std::vector< DependencyInfo > dependencies)
References m_addonInfo.
Referenced by ADDON::CAddonDatabaseSerializer::DeserializeMetadata(), and TEST_F().
SetDescription()
void ADDON::CAddonInfoBuilderFromDB::SetDescription (std::string description)
References m_addonInfo.
Referenced by ADDON::CAddonDatabase::FindByAddonId(), ADDON::CAddonDatabase::GetAddon(), ADDON::CAddonDatabase::GetRepositoryContent(), and TEST_F().
SetDisclaimer()
void ADDON::CAddonInfoBuilderFromDB::SetDisclaimer (std::string disclaimer)
References m_addonInfo.
Referenced by ADDON::CAddonDatabaseSerializer::DeserializeMetadata(), and TEST_F().
SetEMail()
void ADDON::CAddonInfoBuilderFromDB::SetEMail (std::string email)
References m_addonInfo.
Referenced by TEST_F().
SetExtensions()
void ADDON::CAddonInfoBuilderFromDB::SetExtensions (CAddonType addonType)
References ADDON::SExtValue::asString(), ADDON::SExtValue::empty(), ADDON::CAddonExtensions::GetValue(), m_addonInfo, ADDON::CAddonType::m_type, and ADDON::CAddonType::SetProvides().
Referenced by ADDON::CAddonDatabaseSerializer::DeserializeMetadata(), TEST_F(), TEST_F(), and TEST_F().
SetExtrainfo()
void ADDON::CAddonInfoBuilderFromDB::SetExtrainfo (InfoMap extrainfo)
References m_addonInfo.
Referenced by ADDON::CAddonDatabaseSerializer::DeserializeMetadata(), and TEST_F().
SetForum()
void ADDON::CAddonInfoBuilderFromDB::SetForum (std::string forum)
References m_addonInfo.
Referenced by TEST_F().
SetIcon()
void ADDON::CAddonInfoBuilderFromDB::SetIcon (std::string icon)
References m_addonInfo.
Referenced by ADDON::CAddonDatabaseSerializer::DeserializeMetadata().
SetId()
void ADDON::CAddonInfoBuilderFromDB::SetId (std::string id)
References m_addonInfo.
Referenced by AddonDatabaseTest::CreateAddon(), ADDON::CAddonDatabase::FindByAddonId(), ADDON::CAddonDatabase::GetAddon(), ADDON::CAddonDatabase::GetRepositoryContent(), TEST_F(), TEST_F(), and TEST_F().
SetInstallDate()
void ADDON::CAddonInfoBuilderFromDB::SetInstallDate (const CDateTime & installDate)
References m_addonInfo.
SetLastUpdated()
void ADDON::CAddonInfoBuilderFromDB::SetLastUpdated (const CDateTime & lastUpdated)
References m_addonInfo.
SetLastUsed()
void ADDON::CAddonInfoBuilderFromDB::SetLastUsed (const CDateTime & lastUsed)
References m_addonInfo.
SetLibName()
void ADDON::CAddonInfoBuilderFromDB::SetLibName (std::string libname)
References m_addonInfo.
SetLicense()
void ADDON::CAddonInfoBuilderFromDB::SetLicense (std::string license)
References m_addonInfo.
Referenced by TEST_F().
SetLifecycleState()
void ADDON::CAddonInfoBuilderFromDB::SetLifecycleState (AddonLifecycleState state, std::string description)
References m_addonInfo.
Referenced by ADDON::CAddonDatabaseSerializer::DeserializeMetadata().
SetName()
void ADDON::CAddonInfoBuilderFromDB::SetName (std::string name)
References m_addonInfo, and name.
Referenced by ADDON::CAddonDatabase::FindByAddonId(), ADDON::CAddonDatabase::GetAddon(), ADDON::CAddonDatabase::GetRepositoryContent(), and TEST_F().
SetOrigin()
void ADDON::CAddonInfoBuilderFromDB::SetOrigin (std::string origin)
References m_addonInfo.
Referenced by ADDON::CAddonDatabase::FindByAddonId(), ADDON::CAddonDatabase::GetAddon(), and ADDON::CAddonDatabase::GetRepositoryContent().
SetPackageSize()
void ADDON::CAddonInfoBuilderFromDB::SetPackageSize (uint64_t size)
References m_addonInfo.
Referenced by ADDON::CAddonDatabaseSerializer::DeserializeMetadata().
SetPath()
void ADDON::CAddonInfoBuilderFromDB::SetPath (std::string path)
References m_addonInfo.
Referenced by ADDON::CAddonDatabaseSerializer::DeserializeMetadata().
SetScreenshots()
void ADDON::CAddonInfoBuilderFromDB::SetScreenshots (std::vector< std::string > screenshots)
References m_addonInfo.
Referenced by ADDON::CAddonDatabaseSerializer::DeserializeMetadata().
SetSource()
void ADDON::CAddonInfoBuilderFromDB::SetSource (std::string source)
References m_addonInfo.
Referenced by TEST_F().
SetSummary()
void ADDON::CAddonInfoBuilderFromDB::SetSummary (std::string summary)
References m_addonInfo.
Referenced by ADDON::CAddonDatabase::FindByAddonId(), ADDON::CAddonDatabase::GetAddon(), ADDON::CAddonDatabase::GetRepositoryContent(), and TEST_F().
SetVersion()
void ADDON::CAddonInfoBuilderFromDB::SetVersion (CAddonVersion version)
References m_addonInfo.
Referenced by AddonDatabaseTest::CreateAddon(), ADDON::CAddonDatabase::FindByAddonId(), ADDON::CAddonDatabase::GetAddon(), ADDON::CAddonDatabase::GetRepositoryContent(), and TEST_F().
SetWebsite()
void ADDON::CAddonInfoBuilderFromDB::SetWebsite (std::string website)
References m_addonInfo.
Referenced by TEST_F().
Member Data Documentation
m_addonInfo
AddonInfoPtr ADDON::CAddonInfoBuilderFromDB::m_addonInfo private
Referenced by get(), SetArt(), SetArt(), SetAuthor(), SetChangelog(), SetDependencies(), SetDescription(), SetDisclaimer(), SetEMail(), SetExtensions(), SetExtrainfo(), SetForum(), SetIcon(), SetId(), SetInstallDate(), SetLastUpdated(), SetLastUsed(), SetLibName(), SetLicense(), SetLifecycleState(), SetName(), SetOrigin(), SetPackageSize(), SetPath(), SetScreenshots(), SetSource(), SetSummary(), SetVersion(), and SetWebsite().
The documentation for this class was generated from the following files:
AddonInfoBuilder.h
AddonInfoBuilder.cpp