Kodi Documentation: ActiveAE::CActiveAESink Class Reference
ActiveAE::CActiveAESink Class Reference
#include <ActiveAESink.h>
Public Member Functions
CActiveAESink (CEvent *inMsgEvent)
~CActiveAESink ()
void EnumerateSinkList (bool force, std::string driver)
void EnumerateOutputDevices (AEDeviceList &devices, bool passthrough)
std::string ValidateOuputDevice (const std::string &device, bool passthrough) const
void Start ()
void Dispose ()
AEDeviceType GetDeviceType (const std::string &device)
bool HasPassthroughDevice ()
bool SupportsFormat (const std::string &device, AEAudioFormat &format)
bool DeviceExist (std::string driver, const std::string &device)
bool NeedIecPack () const
Public Attributes
CSinkControlProtocol m_controlPort
CSinkDataProtocol m_dataPort
Protected Types
enum { CHECK_SWAP , NEED_CONVERT , NEED_BYTESWAP , SKIP_SWAP }
Protected Member Functions
void Process () override
void StateMachine (int signal, Protocol *port, Message *msg)
void PrintSinks (std::string &driver)
void GetDeviceFriendlyName (const std::string &device)
void OpenSink ()
void ReturnBuffers ()
void SetSilenceTimer ()
bool NeedIECPacking ()
unsigned int OutputSamples (CSampleBuffer *samples)
void SwapInit (CSampleBuffer *samples)
void GenerateNoise ()
Protected Attributes
CEvent m_outMsgEvent
CEvent * m_inMsgEvent
int m_state
bool m_bStateMachineSelfTrigger
std::chrono::milliseconds m_extTimeout
std::chrono::minutes m_silenceTimeOut {std::chrono::minutes::zero()}
bool m_extError
std::chrono::milliseconds m_extSilenceTimeout
bool m_extAppFocused
bool m_extStreaming
XbmcThreads::EndTime m_extSilenceTimer
CSampleBuffer m_sampleOfSilence
enum ActiveAE::CActiveAESink:: { ... } m_swapState
std::string m_deviceFriendlyName
std::string m_device
std::vector< AE::AESinkInfo > m_sinkInfoList
std::unique_ptr< IAESink > m_sink
AEAudioFormat m_sinkFormat
AEAudioFormat m_requestedFormat
CEngineStats * m_stats
float m_volume
int m_sinkLatency
std::unique_ptr< CAEBitstreamPacker > m_packer
bool m_needIecPack {false}
bool m_streamNoise
Additional Inherited Members
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
CHECK_SWAP
NEED_CONVERT
NEED_BYTESWAP
SKIP_SWAP
Constructor & Destructor Documentation
CActiveAESink()
CActiveAESink::CActiveAESink (CEvent * inMsgEvent) explicit
References m_inMsgEvent, m_stats, m_streamNoise, and m_volume.
~CActiveAESink()
CActiveAESink::~CActiveAESink () default
Member Function Documentation
DeviceExist()
bool CActiveAESink::DeviceExist (std::string driver, const std::string & device)
References m_sink, and m_sinkInfoList.
Referenced by ActiveAE::CActiveAE::StateMachine().
Dispose()
void CActiveAESink::Dispose ()
References AE::CAESinkFactory::Cleanup(), CThread::m_bStop, m_controlPort, m_dataPort, m_outMsgEvent, m_packer, m_sampleOfSilence, m_sink, ActiveAE::CSampleBuffer::pkt, Actor::Protocol::Purge(), CEvent::Set(), and CThread::StopThread().
Referenced by ActiveAE::CActiveAE::Dispose().
EnumerateOutputDevices()
void CActiveAESink::EnumerateOutputDevices (AEDeviceList & devices, bool passthrough)
References AE_DEVTYPE_PCM, EnumerateSinkList(), AE::AESinkInfo::m_deviceInfoList, CAEDeviceInfo::m_deviceType, CAEDeviceInfo::m_displayName, CAEDeviceInfo::m_displayNameExtra, CAEDeviceInfo::m_onlyPassthrough, CAEDeviceInfo::m_onlyPCM, m_sinkInfoList, AE::AESinkInfo::m_sinkName, and CAEDeviceInfo::ToDeviceString().
Referenced by ActiveAE::CActiveAE::EnumerateOutputDevices().
EnumerateSinkList()
void CActiveAESink::EnumerateSinkList (bool force, std::string driver)
References AE::CAESinkFactory::EnumerateEx(), AE::CAESinkFactory::HasSinks(), CLog::Log(), LOGINFO, m_sinkInfoList, PrintSinks(), and CThread::Sleep().
Referenced by EnumerateOutputDevices(), and ActiveAE::CActiveAE::StateMachine().
GenerateNoise()
void CActiveAESink::GenerateNoise () protected
References AE_QUALITY_UNKNOWN, ActiveAE::AERESAMPLEFACTORY_QUICK_RESAMPLE, KODI::MEMORY::AlignedFree(), KODI::MEMORY::AlignedMalloc(), SampleConfig::bits_per_sample, SampleConfig::channel_layout, SampleConfig::channels, ActiveAE::CAEResampleFactory::Create(), CAEUtil::DataFormatToDitherBits(), CAEUtil::DataFormatToUsedBits(), SampleConfig::dither_bits, SampleConfig::fmt, log(), AEAudioFormat::m_dataFormat, m_sampleOfSilence, m_sinkFormat, m_streamNoise, PI, ActiveAE::CSampleBuffer::pkt, and SampleConfig::sample_rate.
Referenced by OpenSink(), and StateMachine().
GetDeviceFriendlyName()
void CActiveAESink::GetDeviceFriendlyName (const std::string & device) protected
References m_deviceFriendlyName, AE::AESinkInfo::m_deviceInfoList, CAEDeviceInfo::m_deviceName, CAEDeviceInfo::m_displayName, and m_sinkInfoList.
Referenced by OpenSink().
GetDeviceType()
AEDeviceType CActiveAESink::GetDeviceType (const std::string & device)
References AE_DEVTYPE_PCM, CAEDeviceInfo::m_deviceType, m_sinkInfoList, AE::AESinkDevice::name, and AE::CAESinkFactory::ParseDevice().
Referenced by ActiveAE::CActiveAE::ApplySettingsToFormat(), ActiveAE::CActiveAE::HasHDAudioChannelCount(), ActiveAE::CActiveAE::HasStereoAudioChannelCount(), ActiveAE::CActiveAE::IsSettingVisible(), ActiveAE::CActiveAE::LoadSettings(), and ActiveAE::CActiveAE::StateMachine().
HasPassthroughDevice()
bool CActiveAESink::HasPassthroughDevice ()
References AE_DEVTYPE_PCM, and m_sinkInfoList.
Referenced by ActiveAE::CActiveAE::IsSettingVisible(), and ActiveAE::CActiveAE::LoadSettings().
NeedIecPack()
bool ActiveAE::CActiveAESink::NeedIecPack () const inline
References m_needIecPack.
Referenced by ActiveAE::CActiveAE::InitSink().
NeedIECPacking()
bool CActiveAESink::NeedIECPacking () protected
References AE::AESinkDevice::driver, m_device, m_sinkInfoList, CAEDeviceInfo::m_wantsIECPassthrough, AE::AESinkDevice::name, and AE::CAESinkFactory::ParseDevice().
Referenced by OpenSink().
OpenSink()
void CActiveAESink::OpenSink () protected
References AE_FMT_RAW, AE_FMT_S16BE, AE_FMT_S16LE, AE_FMT_S16NE, AE_FMT_S32BE, AE_FMT_S32LE, AE_FMT_S32NE, SampleConfig::bits_per_sample, SampleConfig::channel_layout, SampleConfig::channels, CHECK_SWAP, CAEChannelInfo::Count(), AE::CAESinkFactory::Create(), CAEUtil::DataFormatToDitherBits(), CAEUtil::DataFormatToStr(), CAEUtil::DataFormatToUsedBits(), SampleConfig::dither_bits, AE::AESinkDevice::driver, SampleConfig::fmt, GenerateNoise(), CAEUtil::GetAVChannelLayout(), CAEUtil::GetAVSampleFormat(), GetDeviceFriendlyName(), CAEStreamInfo::GetDuration(), CAEBitstreamPacker::GetOutputChannelMap(), CAEBitstreamPacker::GetOutputRate(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, AEAudioFormat::m_channelLayout, AEAudioFormat::m_dataFormat, m_device, m_deviceFriendlyName, m_extError, AEAudioFormat::m_frames, AEAudioFormat::m_frameSize, m_needIecPack, m_packer, m_requestedFormat, m_sampleOfSilence, AEAudioFormat::m_sampleRate, m_sink, m_sinkFormat, m_sinkInfoList, AEAudioFormat::m_streamInfo, m_swapState, m_volume, AE::AESinkDevice::name, NeedIECPacking(), AE::CAESinkFactory::ParseDevice(), ActiveAE::CSampleBuffer::pkt, and SampleConfig::sample_rate.
Referenced by StateMachine().
OutputSamples()
unsigned int CActiveAESink::OutputSamples (CSampleBuffer * samples) protected
References AE_FMT_RAW, CHECK_SWAP, AEDelayStatus::delay, Endian_Swap16_buf(), CLog::Log(), LOGERROR, AEAudioFormat::m_dataFormat, m_extError, m_extStreaming, AEAudioFormat::m_frames, AEAudioFormat::m_frameSize, m_needIecPack, m_packer, m_requestedFormat, AEAudioFormat::m_sampleRate, m_sink, m_sinkFormat, m_stats, AEAudioFormat::m_streamInfo, m_swapState, NEED_BYTESWAP, ActiveAE::CSampleBuffer::pkt, ActiveAE::CSampleBuffer::pool, AEDelayStatus::SetDelay(), SKIP_SWAP, CThread::Sleep(), SwapInit(), and ActiveAE::CEngineStats::UpdateSinkDelay().
Referenced by StateMachine().
PrintSinks()
void CActiveAESink::PrintSinks (std::string & driver) protected
References CLog::Log(), LOGINFO, and m_sinkInfoList.
Referenced by EnumerateSinkList().
Process()
void CActiveAESink::Process (void) override protected virtual
Reimplemented from CThread.
References Actor::Protocol::GetMessage(), m_bStateMachineSelfTrigger, CThread::m_bStop, m_controlPort, m_dataPort, m_extAppFocused, m_extTimeout, m_outMsgEvent, m_state, Actor::Protocol::ReceiveOutMessage(), Actor::Message::Release(), S_TOP_UNCONFIGURED, Actor::Message::signal, StateMachine(), ActiveAE::CSinkControlProtocol::TIMEOUT, and CEvent::Wait().
ReturnBuffers()
void CActiveAESink::ReturnBuffers () protected
References Actor::Message::data, m_dataPort, Actor::Protocol::ReceiveOutMessage(), Actor::Message::Release(), Actor::Message::Reply(), ActiveAE::CSinkDataProtocol::RETURNSAMPLE, ActiveAE::CSinkDataProtocol::SAMPLE, and Actor::Message::signal.
Referenced by StateMachine().
SetSilenceTimer()
void CActiveAESink::SetSilenceTimer () protected
References m_extAppFocused, m_extSilenceTimeout, m_extSilenceTimer, m_extStreaming, and m_silenceTimeOut.
Referenced by StateMachine().
Start()
void CActiveAESink::Start ()
References ABOVE_NORMAL, CThread::Create(), CThread::IsRunning(), and CThread::SetPriority().
Referenced by ActiveAE::CActiveAE::Process().
StateMachine()
void CActiveAESink::StateMachine (int signal, Protocol * port, Message * msg) protected
Todo:
use max raw packet size, for now use max size of an IEC packed packet maxIECPpacket > maxRawPacket for raw packets frameSize is set to 1
References ActiveAE::CSinkControlProtocol::ACC, ActiveAE::CSinkDataProtocol::ACC, AE_FMT_RAW, ActiveAE::CSinkControlProtocol::APPFOCUSED, ActiveAE::SinkReply::cacheTotal, ActiveAE::CSinkControlProtocol::CONFIGURE, Actor::Message::data, data(), ActiveAE::CSinkDataProtocol::DRAIN, ActiveAE::CSinkControlProtocol::ERR, ActiveAE::CSinkControlProtocol::FLUSH, ActiveAE::SinkReply::format, GenerateNoise(), ActiveAE::SinkReply::hasVolume, int64_t(), ActiveAE::SinkReply::latency, CLog::Log(), LOGERROR, LOGWARNING, m_bStateMachineSelfTrigger, m_controlPort, AEAudioFormat::m_dataFormat, m_dataPort, m_device, m_extAppFocused, m_extError, m_extSilenceTimeout, m_extSilenceTimer, m_extStreaming, m_extTimeout, AEAudioFormat::m_frames, m_requestedFormat, m_sampleOfSilence, m_silenceTimeOut, m_sink, m_sinkFormat, m_sinkLatency, m_state, m_stats, m_streamNoise, m_volume, OpenSink(), OutputSamples(), ActiveAE::CSampleBuffer::pkt, Actor::Protocol::portName, Actor::Message::Reply(), ReturnBuffers(), ActiveAE::CSinkDataProtocol::RETURNSAMPLE, S_TOP, S_TOP_CONFIGURED, S_TOP_CONFIGURED_IDLE, S_TOP_CONFIGURED_PLAY, S_TOP_CONFIGURED_SILENCE, S_TOP_CONFIGURED_SUSPEND, S_TOP_UNCONFIGURED, ActiveAE::CSinkDataProtocol::SAMPLE, ActiveAE::CSinkControlProtocol::SETNOISETYPE, ActiveAE::CSinkControlProtocol::SETSILENCETIMEOUT, SetSilenceTimer(), SINK_parentStates, CThread::Sleep(), ActiveAE::CSinkControlProtocol::STREAMING, ActiveAE::CSinkControlProtocol::TIMEOUT, ActiveAE::CSinkControlProtocol::UNCONFIGURE, and ActiveAE::CSinkControlProtocol::VOLUME.
Referenced by Process().
SupportsFormat()
bool CActiveAESink::SupportsFormat (const std::string & device, AEAudioFormat & format)
References AE_FMT_RAW, AE::AESinkDevice::driver, m_sinkInfoList, AE::AESinkDevice::name, AE::CAESinkFactory::ParseDevice(), CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, and CAEStreamInfo::STREAM_TYPE_TRUEHD.
Referenced by ActiveAE::CActiveAE::IsSettingVisible(), and ActiveAE::CActiveAE::SupportsRaw().
SwapInit()
void CActiveAESink::SwapInit (CSampleBuffer * samples) protected
References AE_FMT_RAW, AE_FMT_S16NE, AEAudioFormat::m_dataFormat, m_requestedFormat, m_sinkFormat, m_swapState, NEED_BYTESWAP, CAEUtil::S16NeedsByteSwap(), and SKIP_SWAP.
Referenced by OutputSamples().
ValidateOuputDevice()
std::string CActiveAESink::ValidateOuputDevice (const std::string & device, bool passthrough) const
References AE_DEVTYPE_PCM, AE::AESinkDevice::driver, AE::AESinkDevice::friendlyName, m_sinkInfoList, AE::AESinkDevice::name, and AE::CAESinkFactory::ParseDevice().
Referenced by ActiveAE::CActiveAE::ValidateOutputDevices().
Member Data Documentation
m_bStateMachineSelfTrigger
bool ActiveAE::CActiveAESink::m_bStateMachineSelfTrigger protected
Referenced by Process(), and StateMachine().
m_controlPort
CSinkControlProtocol ActiveAE::CActiveAESink::m_controlPort
Referenced by ActiveAE::CActiveAE::Configure(), Dispose(), ActiveAE::CActiveAE::FlushEngine(), ActiveAE::CActiveAE::InitSink(), Process(), ActiveAE::CActiveAE::StateMachine(), StateMachine(), and ActiveAE::CActiveAE::UnconfigureSink().
m_dataPort
CSinkDataProtocol ActiveAE::CActiveAESink::m_dataPort
Referenced by Dispose(), ActiveAE::CActiveAE::DrainSink(), ActiveAE::CActiveAE::Process(), Process(), ReturnBuffers(), ActiveAE::CActiveAE::RunStages(), ActiveAE::CActiveAE::StateMachine(), and StateMachine().
m_device
std::string ActiveAE::CActiveAESink::m_device protected
Referenced by NeedIECPacking(), OpenSink(), and StateMachine().
m_deviceFriendlyName
std::string ActiveAE::CActiveAESink::m_deviceFriendlyName protected
Referenced by GetDeviceFriendlyName(), and OpenSink().
m_extAppFocused
bool ActiveAE::CActiveAESink::m_extAppFocused protected
Referenced by Process(), SetSilenceTimer(), and StateMachine().
m_extError
bool ActiveAE::CActiveAESink::m_extError protected
Referenced by OpenSink(), OutputSamples(), and StateMachine().
m_extSilenceTimeout
std::chrono::milliseconds ActiveAE::CActiveAESink::m_extSilenceTimeout protected
Referenced by SetSilenceTimer(), and StateMachine().
m_extSilenceTimer
XbmcThreads::EndTime ActiveAE::CActiveAESink::m_extSilenceTimer protected
Referenced by SetSilenceTimer(), and StateMachine().
m_extStreaming
bool ActiveAE::CActiveAESink::m_extStreaming protected
Referenced by OutputSamples(), SetSilenceTimer(), and StateMachine().
m_extTimeout
std::chrono::milliseconds ActiveAE::CActiveAESink::m_extTimeout protected
Referenced by Process(), and StateMachine().
m_inMsgEvent
CEvent* ActiveAE::CActiveAESink::m_inMsgEvent protected
Referenced by CActiveAESink().
m_needIecPack
bool ActiveAE::CActiveAESink::m_needIecPack {false} protected
Referenced by NeedIecPack(), OpenSink(), and OutputSamples().
m_outMsgEvent
CEvent ActiveAE::CActiveAESink::m_outMsgEvent protected
Referenced by Dispose(), and Process().
m_packer
std::unique_ptr<CAEBitstreamPacker> ActiveAE::CActiveAESink::m_packer protected
Referenced by Dispose(), OpenSink(), and OutputSamples().
m_requestedFormat
AEAudioFormat ActiveAE::CActiveAESink::m_requestedFormat protected
Referenced by OpenSink(), OutputSamples(), StateMachine(), and SwapInit().
m_sampleOfSilence
CSampleBuffer ActiveAE::CActiveAESink::m_sampleOfSilence protected
Referenced by Dispose(), GenerateNoise(), OpenSink(), and StateMachine().
m_silenceTimeOut
std::chrono::minutes ActiveAE::CActiveAESink::m_silenceTimeOut {std::chrono::minutes::zero()} protected
Referenced by SetSilenceTimer(), and StateMachine().
m_sink
std::unique_ptr<IAESink> ActiveAE::CActiveAESink::m_sink protected
Referenced by DeviceExist(), Dispose(), OpenSink(), OutputSamples(), and StateMachine().
m_sinkFormat
AEAudioFormat ActiveAE::CActiveAESink::m_sinkFormat protected
Referenced by GenerateNoise(), OpenSink(), OutputSamples(), StateMachine(), and SwapInit().
m_sinkInfoList
std::vector<AE::AESinkInfo> ActiveAE::CActiveAESink::m_sinkInfoList protected
Referenced by DeviceExist(), EnumerateOutputDevices(), EnumerateSinkList(), GetDeviceFriendlyName(), GetDeviceType(), HasPassthroughDevice(), NeedIECPacking(), OpenSink(), PrintSinks(), SupportsFormat(), and ValidateOuputDevice().
m_sinkLatency
int ActiveAE::CActiveAESink::m_sinkLatency protected
Referenced by StateMachine().
m_state
int ActiveAE::CActiveAESink::m_state protected
Referenced by Process(), and StateMachine().
m_stats
CEngineStats* ActiveAE::CActiveAESink::m_stats protected
Referenced by CActiveAESink(), OutputSamples(), and StateMachine().
m_streamNoise
bool ActiveAE::CActiveAESink::m_streamNoise protected
Referenced by CActiveAESink(), GenerateNoise(), and StateMachine().
[]
enum { ... } ActiveAE::CActiveAESink::m_swapState
Referenced by OpenSink(), OutputSamples(), and SwapInit().
m_volume
float ActiveAE::CActiveAESink::m_volume protected
Referenced by CActiveAESink(), OpenSink(), and StateMachine().
The documentation for this class was generated from the following files:
ActiveAESink.h
ActiveAESink.cpp