Kodi Documentation: cc_decoder.c File Reference
cc_decoder.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "cc_decoder.h"
Enumerations
enum cc_charset { CCSET_BASIC_AMERICAN = 0 , CCSET_SPECIAL_AMERICAN , CCSET_EXTENDED_SPANISH_FRENCH_MISC , CCSET_EXTENDED_PORTUGUESE_GERMAN_DANISH }
Functions
static cc_buffer_t * active_ccbuffer (cc_decoder_t *dec)
const char * get_char_override (uint8_t charset, uint8_t c)
static int parity (uint8_t byte)
static void build_parity_table (void)
static int good_parity (uint16_t data)
static void ccbuf_add_char (cc_buffer_t *buf, uint8_t c, uint8_t charset)
static void ccbuf_set_cursor (cc_buffer_t *buf, int row, int column, int underline, int italics, int color)
static void ccbuf_apply_attribute (cc_buffer_t *buf, cc_attribute_t *attr)
static void ccbuf_tab (cc_buffer_t *buf, int tabsize)
static void ccrow_der (cc_row_t *row, int pos)
static void ccmem_clear (cc_memory_t *buf)
static void ccmem_init (cc_memory_t *buf)
static void ccmem_exit (cc_memory_t *buf)
static void cea608_process_style_modifiers (cc_decoder_t *dec)
void ccmem_tobuf (cc_decoder_t *dec)
static void cc_set_channel (cc_decoder_t *dec, int channel)
static void cc_hide_displayed (cc_decoder_t *dec)
static void cc_swap_buffers (cc_decoder_t *dec)
static void cc_roll_up (cc_decoder_t *dec)
static void cc_decode_standard_char (cc_decoder_t *dec, uint8_t c1, uint8_t c2)
static void cc_decode_PAC (cc_decoder_t *dec, int channel, uint8_t c1, uint8_t c2)
static void cc_decode_ext_attribute (cc_decoder_t *dec, int channel)
static void cc_decode_special_char (cc_decoder_t *dec, int channel, uint8_t charset, uint8_t c2)
static void cc_decode_midrow_attr (cc_decoder_t *dec, int channel, uint8_t c2)
static void cc_decode_misc_control_code (cc_decoder_t *dec, int channel, uint8_t c2)
static void cc_decode_tab (cc_decoder_t *dec, int channel, uint8_t c2)
static void cc_decode_EIA608 (cc_decoder_t *dec, uint16_t data)
void decode_cc (cc_decoder_t *dec, const uint8_t *buffer, uint32_t buf_len)
cc_decoder_t * cc_decoder_open ()
void cc_decoder_close (cc_decoder_t *dec)
void cc_decoder_init (void)
Variables
static int rowdata [] = {10, -1, 0, 1, 2, 3, 11, 12, 13, 14, 4, 5, 6, 7, 8, 9}
static int parity_table [256]
Enumeration Type Documentation
cc_charset
enum cc_charset
Enumerator
CCSET_BASIC_AMERICAN
CCSET_SPECIAL_AMERICAN
CCSET_EXTENDED_SPANISH_FRENCH_MISC
CCSET_EXTENDED_PORTUGUESE_GERMAN_DANISH
Function Documentation
active_ccbuffer()
static cc_buffer_t * active_ccbuffer (cc_decoder_t * dec) static
References cc_decoder_s::active, cc_memory_s::channel, and cc_memory_s::channel_no.
Referenced by cc_decode_midrow_attr(), cc_decode_misc_control_code(), cc_decode_PAC(), cc_decode_special_char(), cc_decode_standard_char(), cc_decode_tab(), and cc_roll_up().
build_parity_table()
static void build_parity_table (void) static
References parity(), and parity_table.
Referenced by cc_decoder_init().
cc_decode_EIA608()
static void cc_decode_EIA608 (cc_decoder_t * dec, uint16_t data) static
References cc_decode_ext_attribute(), cc_decode_midrow_attr(), cc_decode_misc_control_code(), cc_decode_PAC(), cc_decode_special_char(), cc_decode_standard_char(), cc_decode_tab(), CC_NOTSET, CC_ROLLUP, ccmem_tobuf(), CCSET_EXTENDED_PORTUGUESE_GERMAN_DANISH, CCSET_EXTENDED_SPANISH_FRENCH_MISC, CCSET_SPECIAL_AMERICAN, data(), cc_decoder_s::lastcode, and cc_decoder_s::style.
Referenced by decode_cc().
cc_decode_ext_attribute()
static void cc_decode_ext_attribute (cc_decoder_t * dec, int channel) static
References cc_set_channel().
Referenced by cc_decode_EIA608().
cc_decode_midrow_attr()
static void cc_decode_midrow_attr (cc_decoder_t * dec, int channel, uint8_t c2) static
References active_ccbuffer(), cc_attribute_s::background, BLACK, cc_set_channel(), ccbuf_apply_attribute(), cc_attribute_s::foreground, cc_attribute_s::italic, cc_attribute_s::underline, and WHITE.
Referenced by cc_decode_EIA608().
cc_decode_misc_control_code()
static void cc_decode_misc_control_code (cc_decoder_t * dec, int channel, uint8_t c2) static
References cc_decoder_s::active, active_ccbuffer(), cc_hide_displayed(), CC_PAINTON, CC_POPON, cc_roll_up(), CC_ROLLUP, cc_set_channel(), cc_swap_buffers(), ccmem_clear(), ccmem_tobuf(), ccrow_der(), cc_decoder_s::off_buf, cc_decoder_s::on_buf, cc_row_s::pos, cc_decoder_s::rollup_rows, cc_buffer_s::rowpos, cc_buffer_s::rows, and cc_decoder_s::style.
Referenced by cc_decode_EIA608().
cc_decode_PAC()
static void cc_decode_PAC (cc_decoder_t * dec, int channel, uint8_t c1, uint8_t c2) static
References active_ccbuffer(), cc_set_channel(), ccbuf_set_cursor(), color, rowdata, and WHITE.
Referenced by cc_decode_EIA608().
cc_decode_special_char()
static void cc_decode_special_char (cc_decoder_t * dec, int channel, uint8_t charset, uint8_t c2) static
References active_ccbuffer(), cc_set_channel(), and ccbuf_add_char().
Referenced by cc_decode_EIA608().
cc_decode_standard_char()
static void cc_decode_standard_char (cc_decoder_t * dec, uint8_t c1, uint8_t c2) static
References active_ccbuffer(), ccbuf_add_char(), and CCSET_BASIC_AMERICAN.
Referenced by cc_decode_EIA608().
cc_decode_tab()
static void cc_decode_tab (cc_decoder_t * dec, int channel, uint8_t c2) static
References active_ccbuffer(), cc_set_channel(), and ccbuf_tab().
Referenced by cc_decode_EIA608().
cc_decoder_close()
void cc_decoder_close (cc_decoder_t * dec)
References cc_decoder_s::buffer, and ccmem_exit().
Referenced by CDecoderCC708::~CDecoderCC708().
cc_decoder_init()
void cc_decoder_init (void)
References build_parity_table().
Referenced by CDecoderCC708::CDecoderCC708().
cc_decoder_open()
cc_decoder_t * cc_decoder_open ()
References cc_decoder_s::active, cc_decoder_s::buffer, ccmem_init(), cc_decoder_s::lastcode, cc_decoder_s::off_buf, and cc_decoder_s::on_buf.
Referenced by CDecoderCC708::Init().
cc_hide_displayed()
static void cc_hide_displayed (cc_decoder_t * dec) static
References cc_decoder_s::callback, CC_COLUMNS, CC_ROWS, cc_decoder_s::text, and cc_decoder_s::userdata.
Referenced by cc_decode_misc_control_code(), and cc_swap_buffers().
cc_roll_up()
static void cc_roll_up (cc_decoder_t * dec) static
References active_ccbuffer(), cc_char_cell_s::c, CC_COLUMNS, cc_row_s::cells, cc_row_s::pos, cc_decoder_s::rollup_rows, cc_buffer_s::rowpos, and cc_buffer_s::rows.
Referenced by cc_decode_misc_control_code().
cc_set_channel()
static void cc_set_channel (cc_decoder_t * dec, int channel) static
References cc_decoder_s::active.
Referenced by cc_decode_ext_attribute(), cc_decode_midrow_attr(), cc_decode_misc_control_code(), cc_decode_PAC(), cc_decode_special_char(), and cc_decode_tab().
cc_swap_buffers()
static void cc_swap_buffers (cc_decoder_t * dec) static
References cc_hide_displayed(), cc_decoder_s::off_buf, and cc_decoder_s::on_buf.
Referenced by cc_decode_misc_control_code().
ccbuf_add_char()
static void ccbuf_add_char (cc_buffer_t * buf, uint8_t c, uint8_t charset) static
References cc_row_s::attr_chg, cc_char_cell_s::attributes, cc_char_cell_s::c, CC_COLUMNS, cc_row_s::cells, cc_char_cell_s::charset, cc_char_cell_s::midrow_attr, cc_row_s::num_chars, cc_row_s::pac_attr, cc_row_s::pac_attr_chg, cc_row_s::pos, cc_buffer_s::rowpos, and cc_buffer_s::rows.
Referenced by cc_decode_special_char(), cc_decode_standard_char(), and ccbuf_apply_attribute().
ccbuf_apply_attribute()
static void ccbuf_apply_attribute (cc_buffer_t * buf, cc_attribute_t * attr) static
References cc_row_s::attr_chg, cc_char_cell_s::attributes, ccbuf_add_char(), CCSET_BASIC_AMERICAN, cc_row_s::cells, cc_row_s::pos, cc_buffer_s::rowpos, and cc_buffer_s::rows.
Referenced by cc_decode_midrow_attr().
ccbuf_set_cursor()
static void ccbuf_set_cursor (cc_buffer_t * buf, int row, int column, int underline, int italics, int color) static
References cc_row_s::attr_chg, cc_attribute_s::background, BLACK, color, cc_attribute_s::foreground, cc_attribute_s::italic, cc_row_s::pac_attr, cc_row_s::pac_attr_chg, cc_row_s::pos, cc_buffer_s::rowpos, cc_buffer_s::rows, and cc_attribute_s::underline.
Referenced by cc_decode_PAC().
ccbuf_tab()
static void ccbuf_tab (cc_buffer_t * buf, int tabsize) static
References CC_COLUMNS, cc_row_s::pos, cc_buffer_s::rowpos, and cc_buffer_s::rows.
Referenced by cc_decode_tab().
ccmem_clear()
static void ccmem_clear (cc_memory_t * buf) static
References CC_ROWS, ccrow_der(), cc_memory_s::channel, and cc_buffer_s::rows.
Referenced by cc_decode_misc_control_code(), and ccmem_init().
ccmem_exit()
static void ccmem_exit (cc_memory_t * buf) static
Referenced by cc_decoder_close().
ccmem_init()
static void ccmem_init (cc_memory_t * buf) static
References ccmem_clear().
Referenced by cc_decoder_open().
ccmem_tobuf()
void ccmem_tobuf (cc_decoder_t * dec)
References cc_char_cell_s::c, cc_decoder_s::callback, CC_COLUMNS, CC_ROWS, cea608_process_style_modifiers(), cc_row_s::cells, cc_memory_s::channel, cc_memory_s::channel_no, cc_char_cell_s::charset, f, get_char_override(), cc_decoder_s::on_buf, cc_buffer_s::rows, cc_decoder_s::text, cc_decoder_s::textlen, and cc_decoder_s::userdata.
Referenced by cc_decode_EIA608(), and cc_decode_misc_control_code().
ccrow_der()
static void ccrow_der (cc_row_t * row, int pos) static
References cc_char_cell_s::c, CC_COLUMNS, and cc_row_s::cells.
Referenced by cc_decode_misc_control_code(), and ccmem_clear().
cea608_process_style_modifiers()
static void cea608_process_style_modifiers (cc_decoder_t * dec) static
References cc_char_cell_s::attributes, BLACK, CC_COLUMNS, cc_row_s::cells, cc_memory_s::channel, cc_memory_s::channel_no, cc_attribute_s::foreground, cc_attribute_s::italic, cc_decoder_s::on_buf, cc_row_s::pos, cc_buffer_s::rowpos, cc_buffer_s::rows, cc_decoder_s::textattr, cc_attribute_s::underline, and WHITE.
Referenced by ccmem_tobuf().
decode_cc()
void decode_cc (cc_decoder_t * dec, const uint8_t * buffer, uint32_t buf_len)
References cc_decode_EIA608(), and good_parity().
Referenced by decode_708().
get_char_override()
const char * get_char_override (uint8_t charset, uint8_t c)
References CCSET_BASIC_AMERICAN, CCSET_EXTENDED_PORTUGUESE_GERMAN_DANISH, CCSET_EXTENDED_SPANISH_FRENCH_MISC, and CCSET_SPECIAL_AMERICAN.
Referenced by ccmem_tobuf().
good_parity()
static int good_parity (uint16_t data) static
References data(), and parity_table.
Referenced by decode_cc().
parity()
static int parity (uint8_t byte) static
Referenced by build_parity_table().
Variable Documentation
parity_table
int parity_table[256] static
Referenced by build_parity_table(), and good_parity().
rowdata
int rowdata[] = {10, -1, 0, 1, 2, 3, 11, 12, 13, 14, 4, 5, 6, 7, 8, 9} static
Referenced by cc_decode_PAC().