Kodi Documentation: KODI::GAME::CGUIGameControllerProvider Class Reference
KODI::GAME::CGUIGameControllerProvider Class Reference
Games
Controller list provider for the IAgentList control in the Player Viewer (GameAgents) window.
#include <GUIGameControllerProvider.h>
Public Member Functions
CGUIGameControllerProvider (unsigned int portCount, int portIndex, const std::string &peripheralLocation, uint32_t alignment, int parentID)
Construct a game controller provider for the player's controller list in the Player Viewer dialog.
CGUIGameControllerProvider (const CGUIGameControllerProvider &other)
~CGUIGameControllerProvider () override
std::unique_ptr< IListProvider > Clone () override
Create an instance of the derived class. Allows for polymorphic copies.
bool Update (bool forceRefresh) override
Update the list content.
void Fetch (std::vector< std::shared_ptr< CGUIListItem > > &items) override
Fetch the current list of items.
bool OnClick (const std::shared_ptr< CGUIListItem > &item) override
Click event on an item.
bool OnInfo (const std::shared_ptr< CGUIListItem > &item) override
Open the info dialog for an item provided by this IListProvider.
bool OnContextMenu (const std::shared_ptr< CGUIListItem > &item) override
Open the context menu for an item provided by this IListProvider.
void SetDefaultItem (int item, bool always) override
Set the default item to focus. For backwards compatibility.
int GetDefaultItem () const override
The default item to focus.
bool AlwaysFocusDefaultItem () const override
Whether to always focus the default item.
ControllerPtr GetControllerProfile () const
void SetControllerProfile (ControllerPtr controllerProfile)
unsigned int GetPortCount () const
void SetPortCount (unsigned int portCount)
int GetPortIndex () const
void SetPortIndex (int portIndex)
const std::string & GetPeripheralLocation () const
void SetPeripheralLocation (const std::string &peripheralLocation)
Public Member Functions inherited from IListProvider
IListProvider (int parentID)
IListProvider (const IListProvider &other)=default
virtual ~IListProvider ()=default
virtual bool IsUpdating () const
Check whether the list provider is updating content.
virtual void Reset ()
Reset the current list of items. Derived classes may choose to ignore this.
virtual void FreeResources (bool immediately)
Free all GUI resources allocated by the items.
virtual bool OnPlay (const std::shared_ptr< CGUIListItem > &item)
Play event on an item.
Private Member Functions
void InitializeItems ()
void UpdateItems ()
Private Attributes
ControllerPtr m_controllerProfile
unsigned int m_portCount {0}
int m_portIndex {-1}
std::string m_peripheralLocation
const uint32_t m_alignment
std::vector< std::shared_ptr< CGUIListItem > > m_items
bool m_bDirty {true}
Additional Inherited Members
Static Public Member Functions inherited from IListProvider
static std::unique_ptr< IListProvider > Create (const TiXmlNode *parent, int parentID)
Factory to create list providers.
static std::unique_ptr< IListProvider > CreateSingle (const TiXmlNode *content, int parentID)
Factory to create list providers. Cannot create a multi-provider.
Protected Attributes inherited from IListProvider
int m_parentID
Detailed Description
Controller list provider for the IAgentList control in the Player Viewer (GameAgents) window.
This list provider populates a game controller list with items that show which emulator port a player's controller is connected to. Most items are empty to pad the controller to its correct position in the list.
The number of list items is determined by MAX_PORT_COUNT, plus an item for the "disconnected" icon. The list items are updated when the port count or port index changes.
An alignment can be specified to align the available ports to the left or right side of the list.
Constructor & Destructor Documentation
CGUIGameControllerProvider() [1/2]
CGUIGameControllerProvider::CGUIGameControllerProvider (unsigned int portCount, int portIndex, const std::string & peripheralLocation, uint32_t alignment, int parentID)
Construct a game controller provider for the player's controller list in the Player Viewer dialog.
Parameters
portCount The number of open ports for the emulator
portIndex The index of the port the controller is connected to
peripheralLocation The location of the underlying peripheral providing input
alignment The alignment of the list items (XBFONT_LEFT or XBFONT_RIGHT)
parentID The ID of the parent window
References InitializeItems().
CGUIGameControllerProvider() [2/2]
CGUIGameControllerProvider::CGUIGameControllerProvider (const CGUIGameControllerProvider & other) explicit
References InitializeItems().
~CGUIGameControllerProvider()
CGUIGameControllerProvider::~CGUIGameControllerProvider () override default
Member Function Documentation
AlwaysFocusDefaultItem()
bool KODI::GAME::CGUIGameControllerProvider::AlwaysFocusDefaultItem () const inline override virtual
Whether to always focus the default item.
Returns
true if the default item should always be the one to receive focus.
See also
GetDefaultItem, SetDefaultItem
Reimplemented from IListProvider.
Clone()
std::unique_ptr< IListProvider > CGUIGameControllerProvider::Clone () override virtual
Create an instance of the derived class. Allows for polymorphic copies.
Implements IListProvider.
Fetch()
void CGUIGameControllerProvider::Fetch (std::vector< std::shared_ptr< CGUIListItem > > & items) override virtual
Fetch the current list of items.
Parameters
items [out] the list to be filled.
Implements IListProvider.
References m_items.
GetControllerProfile()
ControllerPtr KODI::GAME::CGUIGameControllerProvider::GetControllerProfile () const inline
References m_controllerProfile.
Referenced by KODI::GAME::CGUIGameControllerList::UpdateInfo().
GetDefaultItem()
int KODI::GAME::CGUIGameControllerProvider::GetDefaultItem () const inline override virtual
The default item to focus.
Returns
the item to focus by default. -1 for none.
See also
SetDefaultItem, AlwaysFocusDefaultItem
Reimplemented from IListProvider.
GetPeripheralLocation()
const std::string & KODI::GAME::CGUIGameControllerProvider::GetPeripheralLocation () const inline
References m_peripheralLocation.
Referenced by KODI::GAME::CGUIGameControllerList::UpdateInfo().
GetPortCount()
unsigned int KODI::GAME::CGUIGameControllerProvider::GetPortCount () const inline
References m_portCount.
Referenced by KODI::GAME::CGUIGameControllerList::UpdateInfo().
GetPortIndex()
int KODI::GAME::CGUIGameControllerProvider::GetPortIndex () const inline
References m_portIndex.
Referenced by KODI::GAME::CGUIGameControllerList::UpdateInfo().
InitializeItems()
void CGUIGameControllerProvider::InitializeItems () private
References m_items, and UpdateItems().
Referenced by CGUIGameControllerProvider(), and CGUIGameControllerProvider().
OnClick()
bool KODI::GAME::CGUIGameControllerProvider::OnClick (const std::shared_ptr< CGUIListItem > & item) inline override virtual
Click event on an item.
Parameters
item the item that was clicked.
Returns
true if the click was handled, false otherwise.
Implements IListProvider.
OnContextMenu()
bool KODI::GAME::CGUIGameControllerProvider::OnContextMenu (const std::shared_ptr< CGUIListItem > & item) inline override virtual
Open the context menu for an item provided by this IListProvider.
Parameters
item the item that was clicked.
Returns
true if the click was handled, false otherwise.
Implements IListProvider.
OnInfo()
bool KODI::GAME::CGUIGameControllerProvider::OnInfo (const std::shared_ptr< CGUIListItem > & item) inline override virtual
Open the info dialog for an item provided by this IListProvider.
Parameters
item the item that was clicked.
Returns
true if the dialog was shown, false otherwise.
Implements IListProvider.
SetControllerProfile()
void CGUIGameControllerProvider::SetControllerProfile (ControllerPtr controllerProfile)
References m_controllerProfile, and UpdateItems().
Referenced by KODI::GAME::CGUIGameControllerList::UpdateInfo().
SetDefaultItem()
void KODI::GAME::CGUIGameControllerProvider::SetDefaultItem (int item, bool always) inline override virtual
Set the default item to focus. For backwards compatibility.
Parameters
item the item to focus.
always whether this item should always be used on first focus.
See also
GetDefaultItem, AlwaysFocusDefaultItem
Reimplemented from IListProvider.
SetPeripheralLocation()
void CGUIGameControllerProvider::SetPeripheralLocation (const std::string & peripheralLocation)
References m_peripheralLocation, and UpdateItems().
Referenced by KODI::GAME::CGUIGameControllerList::UpdateInfo().
SetPortCount()
void CGUIGameControllerProvider::SetPortCount (unsigned int portCount)
References m_portCount, and UpdateItems().
Referenced by KODI::GAME::CGUIGameControllerList::UpdateInfo().
SetPortIndex()
void CGUIGameControllerProvider::SetPortIndex (int portIndex)
References m_portIndex, and UpdateItems().
Referenced by KODI::GAME::CGUIGameControllerList::UpdateInfo().
Update()
bool CGUIGameControllerProvider::Update (bool forceRefresh) override virtual
Update the list content.
Returns
true if the content has changed, false otherwise.
Implements IListProvider.
References m_bDirty.
UpdateItems()
void CGUIGameControllerProvider::UpdateItems () private
References m_alignment, m_bDirty, m_controllerProfile, m_items, m_peripheralLocation, m_portCount, m_portIndex, MAX_PORT_COUNT, and XBFONT_RIGHT.
Referenced by InitializeItems(), SetControllerProfile(), SetPeripheralLocation(), SetPortCount(), and SetPortIndex().
Member Data Documentation
m_alignment
const uint32_t KODI::GAME::CGUIGameControllerProvider::m_alignment private
Referenced by UpdateItems().
m_bDirty
bool KODI::GAME::CGUIGameControllerProvider::m_bDirty {true} private
Referenced by Update(), and UpdateItems().
m_controllerProfile
ControllerPtr KODI::GAME::CGUIGameControllerProvider::m_controllerProfile private
Referenced by GetControllerProfile(), SetControllerProfile(), and UpdateItems().
m_items
std::vector<std::shared_ptr<CGUIListItem> > KODI::GAME::CGUIGameControllerProvider::m_items private
Referenced by Fetch(), InitializeItems(), and UpdateItems().
m_peripheralLocation
std::string KODI::GAME::CGUIGameControllerProvider::m_peripheralLocation private
Referenced by GetPeripheralLocation(), SetPeripheralLocation(), and UpdateItems().
m_portCount
unsigned int KODI::GAME::CGUIGameControllerProvider::m_portCount {0} private
Referenced by GetPortCount(), SetPortCount(), and UpdateItems().
m_portIndex
int KODI::GAME::CGUIGameControllerProvider::m_portIndex {-1} private
Referenced by GetPortIndex(), SetPortIndex(), and UpdateItems().
The documentation for this class was generated from the following files:
GUIGameControllerProvider.h
GUIGameControllerProvider.cpp