Kodi Documentation: CRendererSoftware Class Reference
CRendererSoftware Class Reference
#include <RendererSoftware.h>
Classes
class CRenderBufferImpl
Public Member Functions
~CRendererSoftware ()
bool Configure (const VideoPicture &picture, float fps, unsigned orientation) override
bool Supports (ESCALINGMETHOD method) const override
Public Member Functions inherited from CRendererBase
virtual ~CRendererBase ()
virtual CRenderInfo GetRenderInfo ()
virtual bool Configure (const VideoPicture &picture, float fps, unsigned int orientation)
virtual bool Supports (ERENDERFEATURE feature) const
virtual bool WantsDoublePass ()
virtual bool NeedBuffer (int idx)
void AddVideoPicture (const VideoPicture &picture, int index)
void Render (int index, int index2, CD3DTexture &target, const CRect &sourceRect, const CRect &destRect, const CRect &viewRect, unsigned flags)
void Render (CD3DTexture &target, const CRect &sourceRect, const CRect &destRect, const CRect &viewRect, unsigned flags=0)
void ManageTextures ()
int NextBuffer () const
void ReleaseBuffer (int idx)
bool Flush (bool saveBuffers)
void SetBufferSize (int numBuffers)
DEBUG_INFO_VIDEO GetDebugInfo (int idx)
Static Public Member Functions
static CRendererBase * Create (CVideoSettings &videoSettings)
static void GetWeight (std::map< RenderMethod, int > &weights, const VideoPicture &picture)
Static Public Member Functions inherited from CRendererBase
static DXGI_FORMAT GetDXGIFormat (const VideoPicture &picture)
static DXGI_FORMAT GetDXGIFormat (CVideoBuffer *videoBuffer)
static AVPixelFormat GetAVFormat (DXGI_FORMAT dxgi_format)
static DXGI_HDR_METADATA_HDR10 GetDXGIHDR10MetaData (CRenderBuffer *rb)
Protected Member Functions
CRendererSoftware (CVideoSettings &videoSettings)
CRenderBuffer * CreateBuffer () override
void RenderImpl (CD3DTexture &target, CRect &sourceRect, CPoint(&destPoints)[4], uint32_t flags) override
void FinalOutput (CD3DTexture &source, CD3DTexture &target, const CRect &src, const CPoint(&destPoints)[4]) override
Protected Member Functions inherited from CRendererBase
CRendererBase (CVideoSettings &videoSettings)
bool CreateIntermediateTarget (unsigned int width, unsigned int height, bool dynamic=false, DXGI_FORMAT format=DXGI_FORMAT_UNKNOWN)
void OnCMSConfigChanged (AVColorPrimaries srcPrimaries)
void ReorderDrawPoints (const CRect &destRect, CPoint(&rotatedPoints)[4]) const
bool CreateRenderBuffer (int index)
void DeleteRenderBuffer (int index)
void ProcessHDR (CRenderBuffer *rb)
bool ActualRenderAsHDR ()
Call after rendering has started to find out if the output is configured as SDR or HDR.
virtual void UpdateVideoFilters ()
virtual void CheckVideoParameters ()
virtual void OnViewSizeChanged ()
virtual void OnOutputReset ()
virtual std::string GetRenderMethodDebugInfo () const
Private Attributes
SwsContext * m_sw_scale_ctx = nullptr
SwsFilter * m_srcFilter = nullptr
bool m_restoreMultithreadProtectedOff = false
Additional Inherited Members
Static Protected Member Functions inherited from CRendererBase
static bool IntendToRenderAsHDR (const VideoPicture &picture)
Call before rendering begins to find out if rendering will be attempted as SDR or HDR.
Protected Attributes inherited from CRendererBase
bool m_toneMapping = false
bool m_useDithering = false
bool m_cmsOn = false
bool m_lutIsLoading = false
bool m_useHLGtoPQ = false
ETONEMAPMETHOD m_toneMapMethod = VS_TONEMAPMETHOD_OFF
int m_iBufferIndex = 0
int m_iNumBuffers = 0
int m_iBuffersRequired = 0
int m_ditherDepth = 0
int m_cmsToken = -1
int m_lutSize = 0
unsigned m_sourceWidth = 0
unsigned m_sourceHeight = 0
unsigned m_viewWidth = 0
unsigned m_viewHeight = 0
unsigned m_renderOrientation = 0
float m_fps = 0.0f
uint64_t m_frameIdx = 0
AVPixelFormat m_format = AV_PIX_FMT_NONE
CD3DTexture m_IntermediateTarget
std::shared_ptr< COutputShader > m_outputShader
std::unique_ptr< CColorManager > m_colorManager
Microsoft::WRL::ComPtr< ID3D11ShaderResourceView > m_pLUTView
CVideoSettings & m_videoSettings
std::map< int, CRenderBuffer * > m_renderBuffers
DXGI_HDR_METADATA_HDR10 m_lastHdr10 = {}
HDR_TYPE m_HdrType = HDR_TYPE::HDR_INVALID
bool m_AutoSwitchHDR = false
bool m_initialHdrEnabled = false
std::string m_renderMethodName
Constructor & Destructor Documentation
~CRendererSoftware()
CRendererSoftware::~CRendererSoftware ()
References DX::DeviceResources::Get(), m_restoreMultithreadProtectedOff, m_srcFilter, and m_sw_scale_ctx.
CRendererSoftware()
CRendererSoftware::CRendererSoftware (CVideoSettings & videoSettings) explicit protected
References CRendererBase::m_renderMethodName.
Member Function Documentation
Configure()
bool CRendererSoftware::Configure (const VideoPicture & picture, float fps, unsigned orientation) override
References CRendererBase::CreateIntermediateTarget(), DX::DeviceResources::Get(), CRendererBase::GetAVFormat(), CRendererBase::GetDXGIFormat(), CVideoBuffer::GetFormat(), CRendererBase::m_format, m_restoreMultithreadProtectedOff, CRendererBase::m_sourceHeight, CRendererBase::m_sourceWidth, and VideoPicture::videoBuffer.
Create()
CRendererBase * CRendererSoftware::Create (CVideoSettings & videoSettings) static
CreateBuffer()
CRenderBuffer * CRendererSoftware::CreateBuffer () override protected virtual
Implements CRendererBase.
References CRendererBase::m_format, CRendererBase::m_sourceHeight, and CRendererBase::m_sourceWidth.
FinalOutput()
void CRendererSoftware::FinalOutput (CD3DTexture & source, CD3DTexture & target, const CRect & src, const CPoint(&) destPoints[4]) override protected virtual
Reimplemented from CRendererBase.
References CVideoSettings::m_Brightness, CVideoSettings::m_Contrast, CRendererBase::m_outputShader, and CRendererBase::m_videoSettings.
GetWeight()
void CRendererSoftware::GetWeight (std::map< RenderMethod, int > & weights, const VideoPicture & picture) static
References CRendererBase::GetAVFormat(), CRendererBase::GetDXGIFormat(), CVideoBuffer::GetFormat(), RENDER_SW, and VideoPicture::videoBuffer.
RenderImpl()
void CRendererSoftware::RenderImpl (CD3DTexture & target, CRect & sourceRect, CPoint(&) destPoints[4], uint32_t flags) override protected virtual
Implements CRendererBase.
References CRenderBuffer::av_format, CRenderBuffer::color_space, CRenderBuffer::full_range, CRenderBuffer::GetDataPlanes(), CD3DTexture::GetFormat(), CRenderBuffer::GetHeight(), CD3DTexture::GetHeight(), CRenderBuffer::GetWidth(), CD3DTexture::LockRect(), LOGERROR, CRendererBase::m_iBufferIndex, CRendererBase::m_outputShader, CRendererBase::m_renderBuffers, m_srcFilter, m_sw_scale_ctx, YuvImage::MAX_PLANES, CRendererBase::ReorderDrawPoints(), and CD3DTexture::UnlockRect().
Supports()
bool CRendererSoftware::Supports (ESCALINGMETHOD method) const override virtual
Implements CRendererBase.
References VS_SCALINGMETHOD_AUTO, and VS_SCALINGMETHOD_LINEAR.
Member Data Documentation
m_restoreMultithreadProtectedOff
bool CRendererSoftware::m_restoreMultithreadProtectedOff = false private
Referenced by Configure(), and ~CRendererSoftware().
m_srcFilter
SwsFilter* CRendererSoftware::m_srcFilter = nullptr private
Referenced by RenderImpl(), and ~CRendererSoftware().
m_sw_scale_ctx
SwsContext* CRendererSoftware::m_sw_scale_ctx = nullptr private
Referenced by RenderImpl(), and ~CRendererSoftware().
The documentation for this class was generated from the following files:
RendererSoftware.h
RendererSoftware.cpp