Kodi Documentation: CProcessInfo Class Reference
CProcessInfo Class Reference
#include <ProcessInfo.h>
Public Member Functions
virtual ~CProcessInfo ()=default
void SetDataCache (CDataCacheCore *cache)
void ResetVideoCodecInfo ()
void SetVideoDecoderName (const std::string &name, bool isHw)
std::string GetVideoDecoderName ()
bool IsVideoHwDecoder ()
void SetVideoDeintMethod (const std::string &method)
std::string GetVideoDeintMethod ()
void SetVideoPixelFormat (const std::string &pixFormat)
std::string GetVideoPixelFormat ()
void SetVideoStereoMode (const std::string &mode)
std::string GetVideoStereoMode ()
void SetVideoDimensions (int width, int height)
void GetVideoDimensions (int &width, int &height)
void SetVideoFps (float fps)
float GetVideoFps ()
void SetVideoDAR (float dar)
float GetVideoDAR ()
void SetVideoInterlaced (bool interlaced)
bool GetVideoInterlaced ()
virtual EINTERLACEMETHOD GetFallbackDeintMethod ()
virtual void SetSwDeinterlacingMethods ()
void UpdateDeinterlacingMethods (std::list< EINTERLACEMETHOD > &methods)
bool Supports (EINTERLACEMETHOD method) const
void SetDeinterlacingMethodDefault (EINTERLACEMETHOD method)
EINTERLACEMETHOD GetDeinterlacingMethodDefault () const
CVideoBufferManager & GetVideoBufferManager ()
std::vector< AVPixelFormat > GetPixFormats ()
void SetPixFormats (std::vector< AVPixelFormat > &formats)
void ResetAudioCodecInfo ()
void SetAudioDecoderName (const std::string &name)
std::string GetAudioDecoderName ()
void SetAudioChannels (const std::string &channels)
std::string GetAudioChannels ()
void SetAudioSampleRate (int sampleRate)
int GetAudioSampleRate ()
void SetAudioBitsPerSample (int bitsPerSample)
int GetAudioBitsPerSample ()
virtual bool AllowDTSHDDecode ()
virtual bool WantsRawPassthrough ()
void SetRenderClockSync (bool enabled)
bool IsRenderClockSync ()
void UpdateRenderInfo (CRenderInfo &info)
void UpdateRenderBuffers (int queued, int discard, int free)
void GetRenderBuffers (int &queued, int &discard, int &free)
virtual std::vector< AVPixelFormat > GetRenderFormats ()
void SeekFinished (int64_t offset)
Notifies that a seek operation has finished.
void SetStateSeeking (bool active)
bool IsSeeking ()
void SetStateRealtime (bool state)
bool IsRealtimeStream ()
void SetSpeed (float speed)
void SetNewSpeed (float speed)
float GetNewSpeed ()
void SetFrameAdvance (bool fa)
bool IsFrameAdvance ()
void SetTempo (float tempo)
void SetNewTempo (float tempo)
float GetNewTempo ()
bool IsTempoAllowed (float tempo)
virtual float MinTempoPlatform ()
virtual float MaxTempoPlatform ()
void SetLevelVQ (int level)
int GetLevelVQ ()
void SetGuiRender (bool gui)
bool GetGuiRender ()
void SetVideoRender (bool video)
bool GetVideoRender ()
unsigned int GetMaxPassthroughOffSyncDuration () const
void SetPlayTimes (time_t start, int64_t current, int64_t min, int64_t max)
int64_t GetMaxTime ()
CVideoSettings GetVideoSettings ()
void SetVideoSettings (CVideoSettings &settings)
CVideoSettingsLocked & GetVideoSettingsLocked ()
Static Public Member Functions
static CProcessInfo * CreateInstance ()
static void RegisterProcessControl (const std::string &id, CreateProcessControl createFunc)
Protected Member Functions
CProcessInfo ()
Protected Attributes
CDataCacheCore * m_dataCache = nullptr
bool m_videoIsHWDecoder
std::string m_videoDecoderName
std::string m_videoDeintMethod
std::string m_videoPixelFormat
std::string m_videoStereoMode
int m_videoWidth
int m_videoHeight
float m_videoFPS
float m_videoDAR
bool m_videoIsInterlaced
std::list< EINTERLACEMETHOD > m_deintMethods
EINTERLACEMETHOD m_deintMethodDefault
CCriticalSection m_videoCodecSection
CVideoBufferManager m_videoBufferManager
std::vector< AVPixelFormat > m_pixFormats
std::string m_audioDecoderName
std::string m_audioChannels
int m_audioSampleRate
int m_audioBitsPerSample
CCriticalSection m_audioCodecSection
CCriticalSection m_renderSection
bool m_isClockSync
CRenderInfo m_renderInfo
int m_renderBufQueued = 0
int m_renderBufFree = 0
int m_renderBufDiscard = 0
CCriticalSection m_stateSection
bool m_stateSeeking
std::atomic_int m_levelVQ
std::atomic_bool m_renderGuiLayer
std::atomic_bool m_renderVideoLayer
float m_tempo
float m_newTempo
float m_speed
float m_newSpeed
bool m_frameAdvance
time_t m_startTime
int64_t m_time
int64_t m_timeMax
int64_t m_timeMin
bool m_realTimeStream
CCriticalSection m_settingsSection
CVideoSettings m_videoSettings
std::unique_ptr< CVideoSettingsLocked > m_videoSettingsLocked
Static Protected Attributes
static std::map< std::string, CreateProcessControl > m_processControls
Constructor & Destructor Documentation
~CProcessInfo()
virtual CProcessInfo::~CProcessInfo () virtual default
CProcessInfo()
CProcessInfo::CProcessInfo () protected
References m_settingsSection, m_videoSettings, and m_videoSettingsLocked.
Referenced by CreateInstance().
Member Function Documentation
AllowDTSHDDecode()
bool CProcessInfo::AllowDTSHDDecode () virtual
Referenced by CVideoPlayerAudio::OpenStream(), and CVideoPlayerAudio::SwitchCodecIfNeeded().
CreateInstance()
CProcessInfo * CProcessInfo::CreateInstance () static
References CProcessInfo(), createSection, and m_processControls.
Referenced by CVideoPlayer::CVideoPlayer(), CDVDFileInfo::ExtractThumbToTexture(), and PAPlayer::PAPlayer().
GetAudioBitsPerSample()
int CProcessInfo::GetAudioBitsPerSample ()
References m_audioBitsPerSample, and m_audioCodecSection.
GetAudioChannels()
std::string CProcessInfo::GetAudioChannels ()
References m_audioChannels, and m_audioCodecSection.
GetAudioDecoderName()
std::string CProcessInfo::GetAudioDecoderName ()
References m_audioCodecSection, and m_audioDecoderName.
GetAudioSampleRate()
int CProcessInfo::GetAudioSampleRate ()
References m_audioCodecSection, and m_audioSampleRate.
GetDeinterlacingMethodDefault()
EINTERLACEMETHOD CProcessInfo::GetDeinterlacingMethodDefault () const
References m_deintMethodDefault, and m_videoCodecSection.
Referenced by CVideoPlayerVideo::OutputPicture().
GetFallbackDeintMethod()
EINTERLACEMETHOD CProcessInfo::GetFallbackDeintMethod () virtual
Reimplemented in VIDEOPLAYER::CProcessInfoAndroid, VIDEOPLAYER::CProcessInfoGBM, VIDEOPLAYER::CProcessInfoWin, and VIDEOPLAYER::CProcessInfoWin10.
References VS_INTERLACEMETHOD_DEINTERLACE.
Referenced by VIDEOPLAYER::CProcessInfoGBM::GetFallbackDeintMethod(), and CDVDVideoCodecFFmpeg::SetFilters().
GetGuiRender()
bool CProcessInfo::GetGuiRender ()
References m_renderGuiLayer, and m_stateSection.
GetLevelVQ()
int CProcessInfo::GetLevelVQ ()
References m_levelVQ.
Referenced by CVideoPlayerVideo::GetPlayerInfo().
GetMaxPassthroughOffSyncDuration()
unsigned int CProcessInfo::GetMaxPassthroughOffSyncDuration () const
References CServiceBroker::GetSettingsComponent().
Referenced by CVideoPlayerAudio::CVideoPlayerAudio().
GetMaxTime()
int64_t CProcessInfo::GetMaxTime ()
References m_stateSection, and m_timeMax.
GetNewSpeed()
float CProcessInfo::GetNewSpeed ()
References m_newSpeed, and m_stateSection.
GetNewTempo()
float CProcessInfo::GetNewTempo ()
References m_newTempo, and m_stateSection.
GetPixFormats()
std::vector< AVPixelFormat > CProcessInfo::GetPixFormats ()
References GetRenderFormats(), m_pixFormats, and m_videoCodecSection.
Referenced by CDVDVideoCodecFFmpeg::Open().
GetRenderBuffers()
void CProcessInfo::GetRenderBuffers (int & queued, int & discard, int & free)
References m_renderBufDiscard, m_renderBufFree, m_renderBufQueued, and m_renderSection.
Referenced by DXVA::CDecoder::GetPicture().
GetRenderFormats()
std::vector< AVPixelFormat > CProcessInfo::GetRenderFormats () virtual
Reimplemented in VIDEOPLAYER::CProcessInfoOSX, VIDEOPLAYER::CProcessInfoWayland, VIDEOPLAYER::CProcessInfoWin, VIDEOPLAYER::CProcessInfoWin10, and VIDEOPLAYER::CProcessInfoX11.
References formats.
Referenced by GetPixFormats().
GetVideoBufferManager()
CVideoBufferManager & CProcessInfo::GetVideoBufferManager ()
References m_videoBufferManager.
Referenced by CDVDVideoCodecDRMPRIME::GetBuffer(), CAddonVideoCodec::GetFrameBuffer(), CVideoPlayerVideo::OpenStream(), and CDVDVideoPPFFmpeg::Process().
GetVideoDAR()
float CProcessInfo::GetVideoDAR ()
References m_videoCodecSection, and m_videoDAR.
GetVideoDecoderName()
std::string CProcessInfo::GetVideoDecoderName ()
References m_videoCodecSection, and m_videoDecoderName.
GetVideoDeintMethod()
std::string CProcessInfo::GetVideoDeintMethod ()
References m_videoCodecSection, and m_videoDeintMethod.
GetVideoDimensions()
void CProcessInfo::GetVideoDimensions (int & width, int & height)
References m_videoCodecSection, m_videoHeight, and m_videoWidth.
GetVideoFps()
float CProcessInfo::GetVideoFps ()
References m_videoCodecSection, and m_videoFPS.
GetVideoInterlaced()
bool CProcessInfo::GetVideoInterlaced ()
References m_videoCodecSection, and m_videoIsInterlaced.
Referenced by CDVDVideoCodecFFmpeg::GetPicture(), and CVideoPlayerVideo::OutputPicture().
GetVideoPixelFormat()
std::string CProcessInfo::GetVideoPixelFormat ()
References m_videoCodecSection, and m_videoPixelFormat.
GetVideoRender()
bool CProcessInfo::GetVideoRender ()
References m_renderVideoLayer, and m_stateSection.
GetVideoSettings()
CVideoSettings CProcessInfo::GetVideoSettings ()
References m_settingsSection, and m_videoSettings.
Referenced by VDPAU::CMixer::CheckFeatures(), VAAPI::COutput::InitCycle(), VDPAU::CMixer::InitCycle(), CVideoPlayerVideo::OutputPicture(), CVideoPlayerVideo::ProcessDecoderOutput(), CVideoPlayerAudio::ProcessDecoderOutput(), VDPAU::CMixer::SetColor(), VDPAU::CMixer::SetDeinterlacing(), CDVDVideoCodecFFmpeg::SetFilters(), VDPAU::CMixer::SetNoiseReduction(), CDVDVideoCodecFFmpeg::SetPictureParams(), and VDPAU::CMixer::SetSharpness().
GetVideoSettingsLocked()
CVideoSettingsLocked & CProcessInfo::GetVideoSettingsLocked ()
References m_settingsSection, and m_videoSettingsLocked.
GetVideoStereoMode()
std::string CProcessInfo::GetVideoStereoMode ()
References m_videoCodecSection, and m_videoStereoMode.
Referenced by CVideoPlayerVideo::OutputPicture().
IsFrameAdvance()
bool CProcessInfo::IsFrameAdvance ()
References m_frameAdvance, and m_stateSection.
Referenced by CVideoPlayerVideo::Process().
IsRealtimeStream()
bool CProcessInfo::IsRealtimeStream ()
References m_realTimeStream, and m_stateSection.
Referenced by VTB::CDecoder::Create(), CVideoPlayerAudio::OpenStream(), CVideoPlayerAudio::OpenStream(), CVideoPlayerAudio::ProcessDecoderOutput(), and CVideoPlayerAudio::SwitchCodecIfNeeded().
IsRenderClockSync()
bool CProcessInfo::IsRenderClockSync ()
References m_isClockSync, and m_renderSection.
IsSeeking()
bool CProcessInfo::IsSeeking ()
References m_stateSection, and m_stateSeeking.
IsTempoAllowed()
bool CProcessInfo::IsTempoAllowed (float tempo)
References CServiceBroker::GetSettingsComponent(), MaxTempoPlatform(), and MinTempoPlatform().
Referenced by CVideoPlayerAudio::Process().
IsVideoHwDecoder()
bool CProcessInfo::IsVideoHwDecoder ()
References m_videoCodecSection, and m_videoIsHWDecoder.
Referenced by CVideoPlayerVideo::OpenStream().
MaxTempoPlatform()
float CProcessInfo::MaxTempoPlatform () virtual
Referenced by IsTempoAllowed().
MinTempoPlatform()
float CProcessInfo::MinTempoPlatform () virtual
Referenced by IsTempoAllowed().
RegisterProcessControl()
void CProcessInfo::RegisterProcessControl (const std::string & id, CreateProcessControl createFunc) static
References createSection, id, and m_processControls.
Referenced by VIDEOPLAYER::CProcessInfoAndroid::Register(), VIDEOPLAYER::CProcessInfoGBM::Register(), VIDEOPLAYER::CProcessInfoIOS::Register(), VIDEOPLAYER::CProcessInfoOSX::Register(), VIDEOPLAYER::CProcessInfoWayland::Register(), VIDEOPLAYER::CProcessInfoWin::Register(), VIDEOPLAYER::CProcessInfoWin10::Register(), and VIDEOPLAYER::CProcessInfoX11::Register().
ResetAudioCodecInfo()
void CProcessInfo::ResetAudioCodecInfo ()
References m_audioBitsPerSample, m_audioChannels, m_audioCodecSection, m_audioDecoderName, m_audioSampleRate, m_dataCache, CDataCacheCore::SetAudioBitsPerSample(), CDataCacheCore::SetAudioChannels(), CDataCacheCore::SetAudioDecoderName(), and CDataCacheCore::SetAudioSampleRate().
Referenced by CVideoPlayerAudio::OpenStream().
ResetVideoCodecInfo()
void CProcessInfo::ResetVideoCodecInfo ()
References m_dataCache, m_deintMethodDefault, m_deintMethods, m_stateSeeking, m_videoCodecSection, m_videoDAR, m_videoDecoderName, m_videoDeintMethod, m_videoFPS, m_videoHeight, m_videoIsHWDecoder, m_videoIsInterlaced, m_videoPixelFormat, m_videoStereoMode, m_videoWidth, CDataCacheCore::SetStateSeeking(), CDataCacheCore::SetVideoDAR(), CDataCacheCore::SetVideoDecoderName(), CDataCacheCore::SetVideoDeintMethod(), CDataCacheCore::SetVideoDimensions(), CDataCacheCore::SetVideoFps(), CDataCacheCore::SetVideoPixelFormat(), CDataCacheCore::SetVideoStereoMode(), and VS_INTERLACEMETHOD_NONE.
Referenced by CVideoPlayerVideo::OpenStream(), and SetDataCache().
SeekFinished()
void CProcessInfo::SeekFinished (int64_t offset)
Notifies that a seek operation has finished.
Parameters
offset - the seek offset
References m_dataCache, m_stateSection, and CDataCacheCore::SeekFinished().
SetAudioBitsPerSample()
void CProcessInfo::SetAudioBitsPerSample (int bitsPerSample)
References m_audioBitsPerSample, m_audioCodecSection, m_dataCache, and CDataCacheCore::SetAudioBitsPerSample().
Referenced by CVideoPlayerAudio::ProcessDecoderOutput().
SetAudioChannels()
void CProcessInfo::SetAudioChannels (const std::string & channels)
References m_audioChannels, m_audioCodecSection, m_dataCache, and CDataCacheCore::SetAudioChannels().
Referenced by CVideoPlayerAudio::ProcessDecoderOutput().
SetAudioDecoderName()
void CProcessInfo::SetAudioDecoderName (const std::string & name)
References m_audioCodecSection, m_audioDecoderName, m_dataCache, name, and CDataCacheCore::SetAudioDecoderName().
Referenced by CVideoPlayerAudio::ProcessDecoderOutput().
SetAudioSampleRate()
void CProcessInfo::SetAudioSampleRate (int sampleRate)
References m_audioCodecSection, m_audioSampleRate, m_dataCache, and CDataCacheCore::SetAudioSampleRate().
Referenced by CVideoPlayerAudio::ProcessDecoderOutput().
SetDataCache()
void CProcessInfo::SetDataCache (CDataCacheCore * cache)
References m_dataCache, m_renderGuiLayer, m_renderVideoLayer, ResetVideoCodecInfo(), CDataCacheCore::SetGuiRender(), and CDataCacheCore::SetVideoRender().
SetDeinterlacingMethodDefault()
void CProcessInfo::SetDeinterlacingMethodDefault (EINTERLACEMETHOD method)
References m_deintMethodDefault, and m_videoCodecSection.
Referenced by VAAPI::COutput::Init(), VDPAU::CMixer::Init(), DXVA::CDecoder::Open(), and SetSwDeinterlacingMethods().
SetFrameAdvance()
void CProcessInfo::SetFrameAdvance (bool fa)
References m_dataCache, m_frameAdvance, m_stateSection, and CDataCacheCore::SetFrameAdvance().
SetGuiRender()
void CProcessInfo::SetGuiRender (bool gui)
References m_dataCache, m_renderGuiLayer, m_stateSection, and CDataCacheCore::SetGuiRender().
SetLevelVQ()
void CProcessInfo::SetLevelVQ (int level)
References m_levelVQ.
Referenced by CVideoPlayerVideo::FlushMessages(), CVideoPlayerVideo::GetMessage(), CVideoPlayerVideo::OpenStream(), CVideoPlayerVideo::SendMessage(), and CVideoPlayerVideo::SendMessageBack().
SetNewSpeed()
void CProcessInfo::SetNewSpeed (float speed)
References m_dataCache, m_newSpeed, m_stateSection, m_tempo, and CDataCacheCore::SetSpeed().
SetNewTempo()
void CProcessInfo::SetNewTempo (float tempo)
References m_dataCache, m_newTempo, m_speed, m_stateSection, and CDataCacheCore::SetSpeed().
SetPixFormats()
void CProcessInfo::SetPixFormats (std::vector< AVPixelFormat > & formats)
References formats, m_pixFormats, and m_videoCodecSection.
SetPlayTimes()
void CProcessInfo::SetPlayTimes (time_t start, int64_t current, int64_t min, int64_t max)
References m_dataCache, m_startTime, m_stateSection, m_time, m_timeMax, m_timeMin, max, min, and CDataCacheCore::SetPlayTimes().
SetRenderClockSync()
void CProcessInfo::SetRenderClockSync (bool enabled)
References m_dataCache, m_isClockSync, m_renderSection, and CDataCacheCore::SetRenderClockSync().
SetSpeed()
void CProcessInfo::SetSpeed (float speed)
References m_dataCache, m_newSpeed, m_newTempo, m_speed, m_stateSection, and CDataCacheCore::SetSpeed().
SetStateRealtime()
void CProcessInfo::SetStateRealtime (bool state)
References m_realTimeStream, and m_renderSection.
SetStateSeeking()
void CProcessInfo::SetStateSeeking (bool active)
References m_dataCache, m_renderSection, m_stateSeeking, and CDataCacheCore::SetStateSeeking().
SetSwDeinterlacingMethods()
void CProcessInfo::SetSwDeinterlacingMethods () virtual
Reimplemented in VIDEOPLAYER::CProcessInfoIOS, VIDEOPLAYER::CProcessInfoOSX, VIDEOPLAYER::CProcessInfoWayland, and VIDEOPLAYER::CProcessInfoX11.
References SetDeinterlacingMethodDefault(), UpdateDeinterlacingMethods(), VS_INTERLACEMETHOD_DEINTERLACE, VS_INTERLACEMETHOD_DEINTERLACE_HALF, and VS_INTERLACEMETHOD_NONE.
Referenced by CDVDVideoCodecFFmpeg::GetFormat(), CDVDVideoCodecFFmpeg::Open(), VIDEOPLAYER::CProcessInfoIOS::SetSwDeinterlacingMethods(), VIDEOPLAYER::CProcessInfoOSX::SetSwDeinterlacingMethods(), VIDEOPLAYER::CProcessInfoWayland::SetSwDeinterlacingMethods(), and VIDEOPLAYER::CProcessInfoX11::SetSwDeinterlacingMethods().
SetTempo()
void CProcessInfo::SetTempo (float tempo)
References m_dataCache, m_newSpeed, m_newTempo, m_stateSection, m_tempo, and CDataCacheCore::SetSpeed().
SetVideoDAR()
void CProcessInfo::SetVideoDAR (float dar)
References m_dataCache, m_videoCodecSection, m_videoDAR, and CDataCacheCore::SetVideoDAR().
Referenced by CDVDVideoCodecAndroidMediaCodec::AddData(), CAddonVideoCodec::CopyToInitData(), CDVDVideoCodecFFmpeg::GetPictureCommon(), CDVDVideoCodecAndroidMediaCodec::Open(), CDVDVideoCodecDRMPRIME::Open(), CDVDVideoCodecStarfish::OpenInternal(), and CDVDVideoCodecDRMPRIME::SetPictureParams().
SetVideoDecoderName()
void CProcessInfo::SetVideoDecoderName (const std::string & name, bool isHw)
References m_dataCache, m_videoCodecSection, m_videoDecoderName, m_videoIsHWDecoder, name, and CDataCacheCore::SetVideoDecoderName().
Referenced by CAddonVideoCodec::Open(), CDVDVideoCodecAndroidMediaCodec::Open(), CDVDVideoCodecStarfish::OpenInternal(), CDVDVideoCodecFFmpeg::UpdateName(), and CDVDVideoCodecDRMPRIME::UpdateProcessInfo().
SetVideoDeintMethod()
void CProcessInfo::SetVideoDeintMethod (const std::string & method)
References m_dataCache, m_videoCodecSection, m_videoDeintMethod, and CDataCacheCore::SetVideoDeintMethod().
Referenced by CDVDVideoCodecFFmpeg::FilterOpen(), VAAPI::CSkipPostproc::Init(), VAAPI::CFFmpegPostproc::Init(), VAAPI::COutput::InitCycle(), VTB::CDecoder::Open(), CDVDVideoCodecAndroidMediaCodec::Open(), CDVDVideoCodecDRMPRIME::Open(), CDVDVideoCodecStarfish::OpenInternal(), VDPAU::CMixer::SetDeinterlacing(), and VAAPI::CVppPostproc::UpdateDeintMethod().
SetVideoDimensions()
void CProcessInfo::SetVideoDimensions (int width, int height)
References m_dataCache, m_videoCodecSection, m_videoHeight, m_videoWidth, and CDataCacheCore::SetVideoDimensions().
Referenced by CAddonVideoCodec::CopyToInitData(), CDVDVideoCodecFFmpeg::GetFormat(), CAddonVideoCodec::GetPicture(), CDVDVideoCodecAndroidMediaCodec::Open(), CDVDVideoCodecFFmpeg::Open(), CDVDVideoCodecStarfish::OpenInternal(), and CDVDVideoCodecDRMPRIME::UpdateProcessInfo().
SetVideoFps()
void CProcessInfo::SetVideoFps (float fps)
References m_dataCache, m_videoCodecSection, m_videoFPS, and CDataCacheCore::SetVideoFps().
Referenced by CVideoPlayerVideo::CalcFrameRate(), CAddonVideoCodec::CopyToInitData(), CVideoPlayerVideo::OpenStream(), CDVDVideoCodecAndroidMediaCodec::UpdateFpsDuration(), and CDVDVideoCodecStarfish::UpdateFpsDuration().
SetVideoInterlaced()
void CProcessInfo::SetVideoInterlaced (bool interlaced)
References m_dataCache, m_videoCodecSection, m_videoIsInterlaced, and CDataCacheCore::SetVideoInterlaced().
Referenced by CDVDVideoCodecFFmpeg::GetPicture(), and CDVDVideoCodecFFmpeg::Open().
SetVideoPixelFormat()
void CProcessInfo::SetVideoPixelFormat (const std::string & pixFormat)
References m_dataCache, m_videoCodecSection, m_videoPixelFormat, and CDataCacheCore::SetVideoPixelFormat().
Referenced by CDVDVideoCodecFFmpeg::GetFormat(), CDVDVideoCodecAndroidMediaCodec::Open(), CDVDVideoCodecFFmpeg::Open(), CDVDVideoCodecStarfish::OpenInternal(), and CDVDVideoCodecDRMPRIME::UpdateProcessInfo().
SetVideoRender()
void CProcessInfo::SetVideoRender (bool video)
References m_dataCache, m_renderVideoLayer, m_stateSection, and CDataCacheCore::SetVideoRender().
SetVideoSettings()
void CProcessInfo::SetVideoSettings (CVideoSettings & settings)
References m_settingsSection, and m_videoSettings.
SetVideoStereoMode()
void CProcessInfo::SetVideoStereoMode (const std::string & mode)
References m_dataCache, m_videoCodecSection, m_videoStereoMode, and CDataCacheCore::SetVideoStereoMode().
Referenced by CVideoPlayerVideo::OutputPicture().
Supports()
bool CProcessInfo::Supports (EINTERLACEMETHOD method) const
References m_deintMethods, and m_videoCodecSection.
Referenced by VAAPI::COutput::InitCycle(), VDPAU::CMixer::InitCycle(), CVideoPlayerVideo::OutputPicture(), VDPAU::CMixer::SetDeinterlacing(), CDVDVideoCodecFFmpeg::SetFilters(), UpdateDeinterlacingMethods(), and UpdateRenderInfo().
UpdateDeinterlacingMethods()
void CProcessInfo::UpdateDeinterlacingMethods (std::list< EINTERLACEMETHOD > & methods)
References m_deintMethods, CRenderInfo::m_deintMethods, m_renderInfo, m_videoCodecSection, Supports(), and VS_INTERLACEMETHOD_NONE.
Referenced by VAAPI::COutput::Init(), VDPAU::CMixer::Init(), DXVA::CDecoder::Open(), VTB::CDecoder::Open(), SetSwDeinterlacingMethods(), VIDEOPLAYER::CProcessInfoIOS::SetSwDeinterlacingMethods(), VIDEOPLAYER::CProcessInfoOSX::SetSwDeinterlacingMethods(), VIDEOPLAYER::CProcessInfoWayland::SetSwDeinterlacingMethods(), and VIDEOPLAYER::CProcessInfoX11::SetSwDeinterlacingMethods().
UpdateRenderBuffers()
void CProcessInfo::UpdateRenderBuffers (int queued, int discard, int free)
References m_renderBufDiscard, m_renderBufFree, m_renderBufQueued, and m_renderSection.
UpdateRenderInfo()
void CProcessInfo::UpdateRenderInfo (CRenderInfo & info)
References m_deintMethods, CRenderInfo::m_deintMethods, m_renderInfo, m_renderSection, and Supports().
WantsRawPassthrough()
virtual bool CProcessInfo::WantsRawPassthrough () inline virtual
Reimplemented in VIDEOPLAYER::CProcessInfoAndroid.
Referenced by CDVDAudioCodecPassthrough::CDVDAudioCodecPassthrough().
Member Data Documentation
m_audioBitsPerSample
int CProcessInfo::m_audioBitsPerSample protected
Referenced by GetAudioBitsPerSample(), ResetAudioCodecInfo(), and SetAudioBitsPerSample().
m_audioChannels
std::string CProcessInfo::m_audioChannels protected
Referenced by GetAudioChannels(), ResetAudioCodecInfo(), and SetAudioChannels().
m_audioCodecSection
CCriticalSection CProcessInfo::m_audioCodecSection protected
Referenced by GetAudioBitsPerSample(), GetAudioChannels(), GetAudioDecoderName(), GetAudioSampleRate(), ResetAudioCodecInfo(), SetAudioBitsPerSample(), SetAudioChannels(), SetAudioDecoderName(), and SetAudioSampleRate().
m_audioDecoderName
std::string CProcessInfo::m_audioDecoderName protected
Referenced by GetAudioDecoderName(), ResetAudioCodecInfo(), and SetAudioDecoderName().
m_audioSampleRate
int CProcessInfo::m_audioSampleRate protected
Referenced by GetAudioSampleRate(), ResetAudioCodecInfo(), and SetAudioSampleRate().
m_dataCache
CDataCacheCore* CProcessInfo::m_dataCache = nullptr protected
Referenced by ResetAudioCodecInfo(), ResetVideoCodecInfo(), SeekFinished(), SetAudioBitsPerSample(), SetAudioChannels(), SetAudioDecoderName(), SetAudioSampleRate(), SetDataCache(), SetFrameAdvance(), SetGuiRender(), SetNewSpeed(), SetNewTempo(), SetPlayTimes(), SetRenderClockSync(), SetSpeed(), SetStateSeeking(), SetTempo(), SetVideoDAR(), SetVideoDecoderName(), SetVideoDeintMethod(), SetVideoDimensions(), SetVideoFps(), SetVideoInterlaced(), SetVideoPixelFormat(), SetVideoRender(), and SetVideoStereoMode().
m_deintMethodDefault
EINTERLACEMETHOD CProcessInfo::m_deintMethodDefault protected
Referenced by GetDeinterlacingMethodDefault(), ResetVideoCodecInfo(), and SetDeinterlacingMethodDefault().
m_deintMethods
std::list<EINTERLACEMETHOD> CProcessInfo::m_deintMethods protected
Referenced by ResetVideoCodecInfo(), VIDEOPLAYER::CProcessInfoIOS::SetSwDeinterlacingMethods(), VIDEOPLAYER::CProcessInfoOSX::SetSwDeinterlacingMethods(), VIDEOPLAYER::CProcessInfoWayland::SetSwDeinterlacingMethods(), VIDEOPLAYER::CProcessInfoX11::SetSwDeinterlacingMethods(), Supports(), UpdateDeinterlacingMethods(), and UpdateRenderInfo().
m_frameAdvance
bool CProcessInfo::m_frameAdvance protected
Referenced by IsFrameAdvance(), and SetFrameAdvance().
m_isClockSync
bool CProcessInfo::m_isClockSync protected
Referenced by IsRenderClockSync(), and SetRenderClockSync().
m_levelVQ
std::atomic_int CProcessInfo::m_levelVQ protected
Referenced by GetLevelVQ(), and SetLevelVQ().
m_newSpeed
float CProcessInfo::m_newSpeed protected
Referenced by GetNewSpeed(), SetNewSpeed(), SetSpeed(), and SetTempo().
m_newTempo
float CProcessInfo::m_newTempo protected
Referenced by GetNewTempo(), SetNewTempo(), SetSpeed(), and SetTempo().
m_pixFormats
std::vector<AVPixelFormat> CProcessInfo::m_pixFormats protected
Referenced by GetPixFormats(), and SetPixFormats().
m_processControls
std::map< std::string, CreateProcessControl > CProcessInfo::m_processControls static protected
Referenced by CreateInstance(), and RegisterProcessControl().
m_realTimeStream
bool CProcessInfo::m_realTimeStream protected
Referenced by IsRealtimeStream(), and SetStateRealtime().
m_renderBufDiscard
int CProcessInfo::m_renderBufDiscard = 0 protected
Referenced by GetRenderBuffers(), and UpdateRenderBuffers().
m_renderBufFree
int CProcessInfo::m_renderBufFree = 0 protected
Referenced by GetRenderBuffers(), and UpdateRenderBuffers().
m_renderBufQueued
int CProcessInfo::m_renderBufQueued = 0 protected
Referenced by GetRenderBuffers(), and UpdateRenderBuffers().
m_renderGuiLayer
std::atomic_bool CProcessInfo::m_renderGuiLayer protected
Referenced by GetGuiRender(), SetDataCache(), and SetGuiRender().
m_renderInfo
CRenderInfo CProcessInfo::m_renderInfo protected
Referenced by UpdateDeinterlacingMethods(), and UpdateRenderInfo().
m_renderSection
CCriticalSection CProcessInfo::m_renderSection protected
Referenced by GetRenderBuffers(), IsRenderClockSync(), SetRenderClockSync(), SetStateRealtime(), SetStateSeeking(), UpdateRenderBuffers(), and UpdateRenderInfo().
m_renderVideoLayer
std::atomic_bool CProcessInfo::m_renderVideoLayer protected
Referenced by GetVideoRender(), SetDataCache(), and SetVideoRender().
m_settingsSection
CCriticalSection CProcessInfo::m_settingsSection protected
Referenced by CProcessInfo(), GetVideoSettings(), GetVideoSettingsLocked(), and SetVideoSettings().
m_speed
float CProcessInfo::m_speed protected
Referenced by SetNewTempo(), and SetSpeed().
m_startTime
time_t CProcessInfo::m_startTime protected
Referenced by SetPlayTimes().
m_stateSection
CCriticalSection CProcessInfo::m_stateSection protected
Referenced by GetGuiRender(), GetMaxTime(), GetNewSpeed(), GetNewTempo(), GetVideoRender(), IsFrameAdvance(), IsRealtimeStream(), IsSeeking(), SeekFinished(), SetFrameAdvance(), SetGuiRender(), SetNewSpeed(), SetNewTempo(), SetPlayTimes(), SetSpeed(), SetTempo(), and SetVideoRender().
m_stateSeeking
bool CProcessInfo::m_stateSeeking protected
Referenced by IsSeeking(), ResetVideoCodecInfo(), and SetStateSeeking().
m_tempo
float CProcessInfo::m_tempo protected
Referenced by SetNewSpeed(), and SetTempo().
m_time
int64_t CProcessInfo::m_time protected
Referenced by SetPlayTimes().
m_timeMax
int64_t CProcessInfo::m_timeMax protected
Referenced by GetMaxTime(), and SetPlayTimes().
m_timeMin
int64_t CProcessInfo::m_timeMin protected
Referenced by SetPlayTimes().
m_videoBufferManager
CVideoBufferManager CProcessInfo::m_videoBufferManager protected
Referenced by VIDEOPLAYER::CProcessInfoGBM::CProcessInfoGBM(), VIDEOPLAYER::CProcessInfoWayland::CProcessInfoWayland(), and GetVideoBufferManager().
m_videoCodecSection
CCriticalSection CProcessInfo::m_videoCodecSection mutable protected
Referenced by GetDeinterlacingMethodDefault(), GetPixFormats(), GetVideoDAR(), GetVideoDecoderName(), GetVideoDeintMethod(), GetVideoDimensions(), GetVideoFps(), GetVideoInterlaced(), GetVideoPixelFormat(), GetVideoStereoMode(), IsVideoHwDecoder(), ResetVideoCodecInfo(), SetDeinterlacingMethodDefault(), SetPixFormats(), VIDEOPLAYER::CProcessInfoIOS::SetSwDeinterlacingMethods(), VIDEOPLAYER::CProcessInfoOSX::SetSwDeinterlacingMethods(), VIDEOPLAYER::CProcessInfoWayland::SetSwDeinterlacingMethods(), VIDEOPLAYER::CProcessInfoX11::SetSwDeinterlacingMethods(), SetVideoDAR(), SetVideoDecoderName(), SetVideoDeintMethod(), SetVideoDimensions(), SetVideoFps(), SetVideoInterlaced(), SetVideoPixelFormat(), SetVideoStereoMode(), Supports(), and UpdateDeinterlacingMethods().
m_videoDAR
float CProcessInfo::m_videoDAR protected
Referenced by GetVideoDAR(), ResetVideoCodecInfo(), and SetVideoDAR().
m_videoDecoderName
std::string CProcessInfo::m_videoDecoderName protected
Referenced by GetVideoDecoderName(), ResetVideoCodecInfo(), and SetVideoDecoderName().
m_videoDeintMethod
std::string CProcessInfo::m_videoDeintMethod protected
Referenced by GetVideoDeintMethod(), ResetVideoCodecInfo(), and SetVideoDeintMethod().
m_videoFPS
float CProcessInfo::m_videoFPS protected
Referenced by GetVideoFps(), ResetVideoCodecInfo(), and SetVideoFps().
m_videoHeight
int CProcessInfo::m_videoHeight protected
Referenced by GetVideoDimensions(), ResetVideoCodecInfo(), and SetVideoDimensions().
m_videoIsHWDecoder
bool CProcessInfo::m_videoIsHWDecoder protected
Referenced by IsVideoHwDecoder(), ResetVideoCodecInfo(), and SetVideoDecoderName().
m_videoIsInterlaced
bool CProcessInfo::m_videoIsInterlaced protected
Referenced by GetVideoInterlaced(), ResetVideoCodecInfo(), and SetVideoInterlaced().
m_videoPixelFormat
std::string CProcessInfo::m_videoPixelFormat protected
Referenced by GetVideoPixelFormat(), ResetVideoCodecInfo(), and SetVideoPixelFormat().
m_videoSettings
CVideoSettings CProcessInfo::m_videoSettings protected
Referenced by CProcessInfo(), GetVideoSettings(), and SetVideoSettings().
m_videoSettingsLocked
std::unique_ptr<CVideoSettingsLocked> CProcessInfo::m_videoSettingsLocked protected
Referenced by CProcessInfo(), and GetVideoSettingsLocked().
m_videoStereoMode
std::string CProcessInfo::m_videoStereoMode protected
Referenced by GetVideoStereoMode(), ResetVideoCodecInfo(), and SetVideoStereoMode().
m_videoWidth
int CProcessInfo::m_videoWidth protected
Referenced by GetVideoDimensions(), ResetVideoCodecInfo(), and SetVideoDimensions().
The documentation for this class was generated from the following files:
ProcessInfo.h
ProcessInfo.cpp