Kodi Documentation: ADDON::Interface_GUIControlRadioButton Struct Reference
ADDON::Interface_GUIControlRadioButton Struct Reference
Global gui Add-on to Kodi callback functions.
#include <RadioButton.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static void set_visible (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible)
callback functions from add-on to kodi
static void set_enabled (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool enabled)
static void set_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char *label)
static char * get_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
static void set_selected (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool selected)
static bool is_selected (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle)
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold general gui functions and initialize also all other gui related types not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/controls/RadioButton.h"
Member Function Documentation
DeInit()
void ADDON::Interface_GUIControlRadioButton::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::control_radio_button, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::DeInit().
get_label()
char * ADDON::Interface_GUIControlRadioButton::get_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References CGUIButtonControl::GetLabel(), ADDON::CAddon::ID(), CLog::Log(), and LOGERROR.
Referenced by Init().
Init()
void ADDON::Interface_GUIControlRadioButton::Init (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::control_radio_button, get_label(), AddonToKodiFuncTable_kodi_gui_control_radio_button::get_label, is_selected(), AddonToKodiFuncTable_kodi_gui_control_radio_button::is_selected, AddonToKodiFuncTable_Addon::kodi_gui, set_enabled(), AddonToKodiFuncTable_kodi_gui_control_radio_button::set_enabled, set_label(), AddonToKodiFuncTable_kodi_gui_control_radio_button::set_label, set_selected(), AddonToKodiFuncTable_kodi_gui_control_radio_button::set_selected, set_visible(), AddonToKodiFuncTable_kodi_gui_control_radio_button::set_visible, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_GUIGeneral::Init().
is_selected()
bool ADDON::Interface_GUIControlRadioButton::is_selected (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle) static
References ADDON::CAddon::ID(), CGUIRadioButtonControl::IsSelected(), CLog::Log(), and LOGERROR.
Referenced by Init().
set_enabled()
void ADDON::Interface_GUIControlRadioButton::set_enabled (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool enabled) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIControl::SetEnabled().
Referenced by Init().
set_label()
void ADDON::Interface_GUIControlRadioButton::set_label (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, const char * label) static
References ADDON::CAddon::ID(), label, CLog::Log(), LOGERROR, and CGUIButtonControl::SetLabel().
Referenced by Init().
set_selected()
void ADDON::Interface_GUIControlRadioButton::set_selected (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool selected) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIButtonControl::SetSelected().
Referenced by Init().
set_visible()
void ADDON::Interface_GUIControlRadioButton::set_visible (KODI_HANDLE kodiBase, KODI_GUI_CONTROL_HANDLE handle, bool visible) static
callback functions from add-on to kodi
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIControl::SetVisible().
Referenced by Init().
The documentation for this struct was generated from the following files:
interfaces/gui/controls/RadioButton.h
RadioButton.cpp