Kodi Documentation: SkinBuiltins.cpp File Reference
SkinBuiltins.cpp File Reference
#include "SkinBuiltins.h"
#include "MediaSource.h"
#include "ServiceBroker.h"
#include "URL.h"
#include "Util.h"
#include "addons/addoninfo/AddonInfo.h"
#include "addons/addoninfo/AddonType.h"
#include "addons/gui/GUIWindowAddonBrowser.h"
#include "application/ApplicationComponents.h"
#include "application/ApplicationSkinHandling.h"
#include "dialogs/GUIDialogColorPicker.h"
#include "dialogs/GUIDialogFileBrowser.h"
#include "dialogs/GUIDialogNumeric.h"
#include "dialogs/GUIDialogSelect.h"
#include "guilib/GUIComponent.h"
#include "guilib/GUIKeyboardFactory.h"
#include "guilib/GUIWindowManager.h"
#include "guilib/LocalizeStrings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "settings/SkinSettings.h"
#include "storage/MediaManager.h"
#include "utils/StringUtils.h"
#include "utils/URIUtils.h"
Functions
static int ReloadSkin (const std::vector< std::string > &params)
Reload current skin.
static int UnloadSkin (const std::vector< std::string > &params)
Unload current skin.
static int ToggleSetting (const std::vector< std::string > &params)
Toggle a skin bool setting.
static int SetAddon (const std::vector< std::string > &params)
Set an add-on type skin setting.
static int SelectBool (const std::vector< std::string > &params)
Select and set a skin bool setting.
static int SetBool (const std::vector< std::string > &params)
Set a skin bool setting.
static int SetNumeric (const std::vector< std::string > &params)
Set a numeric skin setting.
static int SetPath (const std::vector< std::string > &params)
Set a path skin setting.
static int SetFile (const std::vector< std::string > &params)
Set a skin file setting.
static int SetImage (const std::vector< std::string > &params)
Set a skin image setting.
static int SetColor (const std::vector< std::string > &params)
Set a skin color setting.
static int SetString (const std::vector< std::string > &params)
Set a string skin setting.
static int SetTheme (const std::vector< std::string > &params)
Select skin theme.
static int SkinReset (const std::vector< std::string > &params)
Reset a skin setting.
static int SkinResetAll (const std::vector< std::string > &params)
Reset all skin settings.
static int SkinDebug (const std::vector< std::string > &params)
Toggle skin debug.
static int SkinTimerStart (const std::vector< std::string > &params)
Starts a given skin timer.
static int SkinTimerStop (const std::vector< std::string > &params)
Stops a given skin timer.
Function Documentation
ReloadSkin()
static int ReloadSkin (const std::vector< std::string > & params) static
Reload current skin.
Parameters
params The parameters.
params[0] = "confirm" to show a confirmation dialog (optional).
References KODI::UTILS::StringUtils::EqualsNoCase(), CServiceBroker::GetAppComponents(), and CApplicationSkinHandling::ReloadSkin().
Referenced by CSkinBuiltins::GetOperations().
SelectBool()
static int SelectBool (const std::vector< std::string > & params) static
Select and set a skin bool setting.
Parameters
params The parameters.
params[0] = Number of a localized string to display as a header in a select dialog
params[1,...] = one or more number|skinbool-setting pairs where number is index of a localized string used as label
and skinbool-setting is a string of the skinbool setting name. The pairs are added to the select dialog list.
If the users confirms a (single) selection label in the select dialog, the paired skinbool is set to true and all others
in the list are set to false. Multi-select is not available.
References CGUIDialogSelect::Add(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CSkinSettings::GetInstance(), CGUIDialogSelect::GetSelectedItem(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), CGUIDialogBoxBase::IsConfirmed(), label, CGUIDialog::Open(), CGUIDialogSelect::Reset(), CSkinSettings::SetBool(), CGUIDialogBoxBase::SetHeading(), KODI::UTILS::StringUtils::Split(), CSkinSettings::TranslateBool(), values, and WINDOW_DIALOG_SELECT.
Referenced by CSkinBuiltins::GetOperations().
SetAddon()
static int SetAddon (const std::vector< std::string > & params) static
Set an add-on type skin setting.
Parameters
params The parameters.
params[0] = Skin setting to store result in. params[1,...] = Add-on types to allow selecting.
References CSkinSettings::GetInstance(), CServiceBroker::GetSettingsComponent(), CGUIWindowAddonBrowser::SelectAddonID(), CSkinSettings::SetString(), CSkinSettings::TranslateString(), ADDON::CAddonInfo::TranslateType(), and ADDON::types.
Referenced by CSkinBuiltins::GetOperations().
SetBool()
static int SetBool (const std::vector< std::string > & params) static
Set a skin bool setting.
Parameters
params The parameters.
params[0] = Name of skin setting. params[1] = Value to set ("false", or "true") (optional).
References KODI::UTILS::StringUtils::EqualsNoCase(), CSkinSettings::GetInstance(), CServiceBroker::GetSettingsComponent(), CSkinSettings::SetBool(), and CSkinSettings::TranslateBool().
Referenced by CSkinBuiltins::GetOperations(), and XBMCHelper::OnSettingChanging().
SetColor()
static int SetColor (const std::vector< std::string > & params) static
Set a skin color setting.
Parameters
params The parameters.
params[0] = Name of skin setting. params[1] = Dialog header text. params[2] = Hex value of the preselected color (optional). params[3] = XML file containing color definitions (optional).
References g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CSkinSettings::GetInstance(), CGUIDialogColorPicker::GetSelectedColor(), CSkinSettings::GetString(), CGUIComponent::GetWindowManager(), CGUIDialogBoxBase::IsConfirmed(), CGUIDialogColorPicker::LoadColors(), CGUIDialog::Open(), CGUIDialogColorPicker::Reset(), CGUIDialogBoxBase::SetHeading(), CGUIDialogColorPicker::SetSelectedColor(), CSkinSettings::SetString(), CSkinSettings::TranslateString(), value, and WINDOW_DIALOG_COLOR_PICKER.
Referenced by CSkinBuiltins::GetOperations().
SetFile()
static int SetFile (const std::vector< std::string > & params) static
Set a skin file setting.
Parameters
params The parameters.
params[0] = Name of skin setting. params[1] = File mask or add-on type (optional). params[2] = Extra URL to allow selection from or content type if mask is an addon-on type (optional).
References URIUtils::AddSlashAtEnd(), ADDON::content, g_localizeStrings, CURL::Get(), CLocalizeStrings::Get(), URIUtils::GetFileName(), CSkinSettings::GetInstance(), CMediaManager::GetLocalDrives(), CUtil::GetMatchingSource(), CServiceBroker::GetMediaManager(), CSkinSettings::GetString(), CURL::SetFileName(), CURL::SetHostName(), CURL::SetPassword(), CURL::SetProtocol(), CSkinSettings::SetString(), CGUIDialogFileBrowser::ShowAndGetFile(), KODI::UTILS::StringUtils::StartsWithNoCase(), CMediaSource::strName, CMediaSource::strPath, KODI::UTILS::StringUtils::ToLower(), CSkinSettings::TranslateString(), ADDON::CAddonInfo::TranslateType(), and value.
Referenced by CSkinBuiltins::GetOperations().
SetImage()
static int SetImage (const std::vector< std::string > & params) static
Set a skin image setting.
Parameters
params The parameters.
params[0] = Name of skin setting. params[1] = Extra URL to allow selection from (optional).
References URIUtils::AddSlashAtEnd(), g_localizeStrings, CLocalizeStrings::Get(), CSkinSettings::GetInstance(), CMediaManager::GetLocalDrives(), CUtil::GetMatchingSource(), CServiceBroker::GetMediaManager(), CSkinSettings::GetString(), CSkinSettings::SetString(), CGUIDialogFileBrowser::ShowAndGetImage(), CMediaSource::strName, CMediaSource::strPath, CSkinSettings::TranslateString(), and value.
Referenced by CSkinBuiltins::GetOperations().
SetNumeric()
static int SetNumeric (const std::vector< std::string > & params) static
Set a numeric skin setting.
Parameters
params The parameters.
params[0] = Name of skin setting.
References g_localizeStrings, CLocalizeStrings::Get(), CSkinSettings::GetInstance(), CSkinSettings::GetString(), CSkinSettings::SetString(), CGUIDialogNumeric::ShowAndGetNumber(), CSkinSettings::TranslateString(), and value.
Referenced by CSkinBuiltins::GetOperations().
SetPath()
static int SetPath (const std::vector< std::string > & params) static
Set a path skin setting.
Parameters
params The parameters.
params[0] = Name of skin setting. params[1] = Extra URL to allow selection from (optional).
References URIUtils::AddSlashAtEnd(), g_localizeStrings, CLocalizeStrings::Get(), CSkinSettings::GetInstance(), CMediaManager::GetLocalDrives(), CUtil::GetMatchingSource(), CServiceBroker::GetMediaManager(), CMediaManager::GetNetworkLocations(), CServiceBroker::GetSettingsComponent(), CSkinSettings::GetString(), CSkinSettings::SetString(), CGUIDialogFileBrowser::ShowAndGetDirectory(), CMediaSource::strName, CMediaSource::strPath, CSkinSettings::TranslateString(), and value.
Referenced by CVideoDatabase::GetItemsForPath(), and CSkinBuiltins::GetOperations().
SetString()
static int SetString (const std::vector< std::string > & params) static
Set a string skin setting.
Parameters
params The parameters.
params[0] = Name of skin setting. params[1] = Value of skin setting (optional).
References g_localizeStrings, CLocalizeStrings::Get(), CSkinSettings::GetInstance(), CServiceBroker::GetSettingsComponent(), CSkinSettings::GetString(), CSkinSettings::SetString(), CGUIKeyboardFactory::ShowAndGetInput(), CSkinSettings::TranslateString(), and value.
Referenced by CSkinBuiltins::GetOperations(), and CDisplaySettings::OnSettingChanging().
SetTheme()
static int SetTheme (const std::vector< std::string > & params) static
Select skin theme.
Parameters
params The parameters.
params[0] = 0 or 1 to increase theme, -1 to decrease.
References KODI::UTILS::StringUtils::EqualsNoCase(), CServiceBroker::GetSettingsComponent(), CUtil::GetSkinThemes(), URIUtils::RemoveExtension(), and CSettings::SETTING_LOOKANDFEEL_SKINTHEME.
Referenced by CSkinBuiltins::GetOperations().
SkinDebug()
static int SkinDebug (const std::vector< std::string > & params) static
Toggle skin debug.
Parameters
params (ignored)
References g_SkinInfo.
Referenced by CSkinBuiltins::GetOperations().
SkinReset()
static int SkinReset (const std::vector< std::string > & params) static
Reset a skin setting.
Parameters
params The parameters.
params[0] = Name of setting to reset.
References CSkinSettings::GetInstance(), CServiceBroker::GetSettingsComponent(), and CSkinSettings::Reset().
Referenced by CSkinBuiltins::GetOperations().
SkinResetAll()
static int SkinResetAll (const std::vector< std::string > & params) static
Reset all skin settings.
Parameters
params (ignored)
References CSkinSettings::GetInstance(), CServiceBroker::GetSettingsComponent(), and CSkinSettings::Reset().
Referenced by CSkinBuiltins::GetOperations().
SkinTimerStart()
static int SkinTimerStart (const std::vector< std::string > & params) static
Starts a given skin timer.
Parameters
params The parameters.
params[0] = Name of the timer.
Returns
-1 in case of error, 0 in case of success
References g_SkinInfo.
Referenced by CSkinBuiltins::GetOperations().
SkinTimerStop()
static int SkinTimerStop (const std::vector< std::string > & params) static
Stops a given skin timer.
Parameters
params The parameters.
params[0] = Name of the timer.
Returns
-1 in case of error, 0 in case of success
References g_SkinInfo.
Referenced by CSkinBuiltins::GetOperations().
ToggleSetting()
static int ToggleSetting (const std::vector< std::string > & params) static
Toggle a skin bool setting.
Parameters
params The parameters.
params[0] = Skin setting to toggle.
References CSkinSettings::GetInstance(), CServiceBroker::GetSettingsComponent(), CSkinSettings::SetBool(), and CSkinSettings::TranslateBool().
Referenced by CSkinBuiltins::GetOperations().
UnloadSkin()
static int UnloadSkin (const std::vector< std::string > & params) static
Unload current skin.
Parameters
params (ignored)
References CServiceBroker::GetAppComponents(), and CApplicationSkinHandling::UnloadSkin().
Referenced by CSkinBuiltins::GetOperations().