Kodi Documentation: CAESinkALSA Class Reference
CAESinkALSA Class Reference
#include <AESinkALSA.h>
Classes
struct ALSAConfig
Public Member Functions
const char * GetName () override
CAESinkALSA ()
~CAESinkALSA () override
bool Initialize (AEAudioFormat &format, std::string &device) override
void Deinitialize () override
virtual void Stop ()
void GetDelay (AEDelayStatus &status) override
Return a timestamped status structure with delay and sink info.
double GetCacheTotal () override
unsigned int AddPackets (uint8_t **data, unsigned int frames, unsigned int offset) override
Adds packets to be sent out, this routine MUST block or sleep.
void Drain () override
Public Member Functions inherited from IAESink
IAESink ()=default
virtual ~IAESink ()=default
virtual double GetLatency ()
virtual void AddPause (unsigned int millis)
instruct the sink to add a pause
virtual bool HasVolume ()
virtual void SetVolume (float volume)
Static Public Member Functions
static void Register ()
static std::unique_ptr< IAESink > Create (std::string &device, AEAudioFormat &desiredFormat)
static void EnumerateDevicesEx (AEDeviceInfoList &list, bool force=false)
static void Cleanup ()
Private Member Functions
CAEChannelInfo GetChannelLayoutRaw (const AEAudioFormat &format)
CAEChannelInfo GetChannelLayoutLegacy (const AEAudioFormat &format, unsigned int minChannels, unsigned int maxChannels)
CAEChannelInfo GetChannelLayout (const AEAudioFormat &format, unsigned int channels)
snd_pcm_chmap_t * SelectALSAChannelMap (const CAEChannelInfo &info)
void GetAESParams (const AEAudioFormat &format, std::string &params)
void HandleError (const char *name, int err)
bool InitializeHW (const ALSAConfig &inconfig, ALSAConfig &outconfig)
bool InitializeSW (const ALSAConfig &inconfig)
Static Private Member Functions
static AEChannel ALSAChannelToAEChannel (unsigned int alsaChannel)
static unsigned int AEChannelToALSAChannel (AEChannel aeChannel)
static CAEChannelInfo ALSAchmapToAEChannelMap (snd_pcm_chmap_t *alsaMap)
static snd_pcm_chmap_t * AEChannelMapToALSAchmap (const CAEChannelInfo &info)
static snd_pcm_chmap_t * CopyALSAchmap (snd_pcm_chmap_t *alsaMap)
static std::string ALSAchmapToString (snd_pcm_chmap_t *alsaMap)
static CAEChannelInfo GetAlternateLayoutForm (const CAEChannelInfo &info)
static snd_pcm_format_t AEFormatToALSAFormat (const enum AEDataFormat format)
static void AppendParams (std::string &device, const std::string &params)
static bool TryDevice (const std::string &name, snd_pcm_t **pcmp, snd_config_t *lconf)
static bool TryDeviceWithParams (const std::string &name, const std::string &params, snd_pcm_t **pcmp, snd_config_t *lconf)
static bool OpenPCMDevice (const std::string &name, const std::string &params, int channels, snd_pcm_t **pcmp, snd_config_t *lconf)
static AEDeviceType AEDeviceTypeFromName (const std::string &name)
static std::string GetParamFromName (const std::string &name, const std::string &param)
static void EnumerateDevice (AEDeviceInfoList &list, const std::string &device, const std::string &description, snd_config_t *config)
static bool SoundDeviceExists (const std::string &device)
static bool GetELD (snd_hctl_t *hctl, int device, CAEDeviceInfo &info, bool &badHDMI)
static void sndLibErrorHandler (const char *file, int line, const char *function, int err, const char *fmt,...)
Private Attributes
std::string m_initDevice
AEAudioFormat m_initFormat
AEAudioFormat m_format
unsigned int m_bufferSize = 0
double m_formatSampleRateMul = 0.0
bool m_passthrough = false
std::string m_device
snd_pcm_t * m_pcm
int m_timeout = 0
bool m_fragmented = false
unsigned int m_originalPeriodSize = AE_MIN_PERIODSIZE
Constructor & Destructor Documentation
CAESinkALSA()
CAESinkALSA::CAESinkALSA ()
~CAESinkALSA()
CAESinkALSA::~CAESinkALSA () override
References Deinitialize().
Member Function Documentation
AddPackets()
unsigned int CAESinkALSA::AddPackets (uint8_t ** data, unsigned int frames, unsigned int offset) override virtual
Adds packets to be sent out, this routine MUST block or sleep.
Parameters
data array of pointers to planes holding audio data
frames number of audio frames in data
offset offset in frames where audio data starts
Returns
number of frames consumed by the sink
Implements IAESink.
References data(), HandleError(), int64_t(), CLog::Log(), LOGERROR, m_format, m_fragmented, AEAudioFormat::m_frameSize, m_originalPeriodSize, and m_pcm.
AEChannelMapToALSAchmap()
snd_pcm_chmap_t * CAESinkALSA::AEChannelMapToALSAchmap (const CAEChannelInfo & info) static private
References AEChannelToALSAChannel(), and CAEChannelInfo::Count().
Referenced by SelectALSAChannelMap().
AEChannelToALSAChannel()
unsigned int CAESinkALSA::AEChannelToALSAChannel (AEChannel aeChannel) static private
References AE_CH_BC, AE_CH_BL, AE_CH_BLOC, AE_CH_BR, AE_CH_BROC, AE_CH_FC, AE_CH_FL, AE_CH_FLOC, AE_CH_FR, AE_CH_FROC, AE_CH_LFE, AE_CH_SL, AE_CH_SR, AE_CH_TBC, AE_CH_TBL, AE_CH_TBR, AE_CH_TC, AE_CH_TFC, AE_CH_TFL, and AE_CH_TFR.
Referenced by AEChannelMapToALSAchmap().
AEDeviceTypeFromName()
AEDeviceType CAESinkALSA::AEDeviceTypeFromName (const std::string & name) static private
References AE_DEVTYPE_HDMI, AE_DEVTYPE_IEC958, AE_DEVTYPE_PCM, and name.
Referenced by EnumerateDevice(), and Initialize().
AEFormatToALSAFormat()
snd_pcm_format_t CAESinkALSA::AEFormatToALSAFormat (const enum AEDataFormat format) static private
References AE_FMT_FLOAT, AE_FMT_RAW, AE_FMT_S16BE, AE_FMT_S16LE, AE_FMT_S16NE, AE_FMT_S24NE3, AE_FMT_S24NE4, AE_FMT_S32NE, and AE_FMT_U8.
Referenced by EnumerateDevice(), and InitializeHW().
ALSAChannelToAEChannel()
AEChannel CAESinkALSA::ALSAChannelToAEChannel (unsigned int alsaChannel) static private
References AE_CH_BC, AE_CH_BL, AE_CH_BLOC, AE_CH_BR, AE_CH_BROC, AE_CH_FC, AE_CH_FL, AE_CH_FLOC, AE_CH_FR, AE_CH_FROC, AE_CH_LFE, AE_CH_SL, AE_CH_SR, AE_CH_TBC, AE_CH_TBL, AE_CH_TBR, AE_CH_TC, AE_CH_TFC, AE_CH_TFL, AE_CH_TFR, and AE_CH_UNKNOWN1.
Referenced by ALSAchmapToAEChannelMap().
ALSAchmapToAEChannelMap()
CAEChannelInfo CAESinkALSA::ALSAchmapToAEChannelMap (snd_pcm_chmap_t * alsaMap) static private
References ALSAChannelToAEChannel().
Referenced by EnumerateDevice(), GetChannelLayout(), and SelectALSAChannelMap().
ALSAchmapToString()
std::string CAESinkALSA::ALSAchmapToString (snd_pcm_chmap_t * alsaMap) static private
Bug:
ALSA bug - buffer overflow by a factor of 2 is possible http://mailman.alsa-project.org/pipermail/alsa-devel/2014-December/085815.html
References err().
Referenced by GetChannelLayout(), and SelectALSAChannelMap().
AppendParams()
void CAESinkALSA::AppendParams (std::string & device, const std::string & params) static private
Referenced by TryDeviceWithParams().
Cleanup()
void CAESinkALSA::Cleanup () static
References CALSAHControlMonitor::Clear(), CServiceBroker::GetPlatform(), CPlatform::GetService(), and CALSADeviceMonitor::Stop().
Referenced by Register().
CopyALSAchmap()
snd_pcm_chmap_t * CAESinkALSA::CopyALSAchmap (snd_pcm_chmap_t * alsaMap) static private
Referenced by SelectALSAChannelMap().
Create()
std::unique_ptr< IAESink > CAESinkALSA::Create (std::string & device, AEAudioFormat & desiredFormat) static
Referenced by Register().
Deinitialize()
void CAESinkALSA::Deinitialize () override virtual
Implements IAESink.
References m_pcm, and Stop().
Referenced by ~CAESinkALSA().
Drain()
void CAESinkALSA::Drain () override virtual
Reimplemented from IAESink.
References m_pcm.
EnumerateDevice()
void CAESinkALSA::EnumerateDevice (AEDeviceInfoList & list, const std::string & device, const std::string & description, snd_config_t * config) static private
References CALSAHControlMonitor::Add(), CAEChannelInfo::AddMissingChannels(), AE_DEVTYPE_HDMI, AE_DEVTYPE_IEC958, AE_DEVTYPE_PCM, AE_FMT_INVALID, AE_FMT_MAX, AE_FMT_RAW, AEDeviceTypeFromName(), AEFormatToALSAFormat(), ALSA_MAX_CHANNELS, ALSAchmapToAEChannelMap(), ALSASampleRateList, EnumerateDevice(), err(), GetELD(), CServiceBroker::GetPlatform(), CPlatform::GetService(), LegacyALSAChannelMap, CLog::Log(), LOGDEBUG, LOGINFO, CAEChannelInfo::m_channels, CAEDeviceInfo::m_deviceName, OpenPCMDevice(), CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, and CAEStreamInfo::STREAM_TYPE_TRUEHD.
Referenced by EnumerateDevice(), and EnumerateDevicesEx().
EnumerateDevicesEx()
void CAESinkALSA::EnumerateDevicesEx (AEDeviceInfoList & list, bool force = false) static
References CALSAHControlMonitor::Clear(), EnumerateDevice(), GetParamFromName(), CServiceBroker::GetPlatform(), CPlatform::GetService(), CLog::Log(), LOGINFO, name, sndLibErrorHandler(), and CALSADeviceMonitor::Start().
Referenced by Register().
GetAESParams()
void CAESinkALSA::GetAESParams (const AEAudioFormat & format, std::string & params) private
References m_passthrough.
Referenced by Initialize().
GetAlternateLayoutForm()
CAEChannelInfo CAESinkALSA::GetAlternateLayoutForm (const CAEChannelInfo & info) static private
References AE_CH_BL, AE_CH_BLOC, AE_CH_BR, AE_CH_BROC, AE_CH_SL, AE_CH_SR, and CAEChannelInfo::ReplaceChannel().
Referenced by GetChannelLayout(), and SelectALSAChannelMap().
GetCacheTotal()
double CAESinkALSA::GetCacheTotal () override virtual
Implements IAESink.
References m_bufferSize, and m_formatSampleRateMul.
GetChannelLayout()
CAEChannelInfo CAESinkALSA::GetChannelLayout (const AEAudioFormat & format, unsigned int channels) inline private
References AE_CH_UNKNOWN1, AE_FMT_RAW, ALSAchmapToAEChannelMap(), ALSAchmapToString(), CAEChannelInfo::Count(), GetAlternateLayoutForm(), GetChannelLayoutLegacy(), GetChannelLayoutRaw(), CLog::Log(), LOGDEBUG, and m_pcm.
Referenced by Initialize().
GetChannelLayoutLegacy()
CAEChannelInfo CAESinkALSA::GetChannelLayoutLegacy (const AEAudioFormat & format, unsigned int minChannels, unsigned int maxChannels) inline private
References AE_CH_BL, AE_CH_SL, AE_FMT_RAW, channelMap, GetChannelLayoutRaw(), LegacyALSAChannelMap, and LegacyALSAChannelMap51Wide.
Referenced by GetChannelLayout(), and Initialize().
GetChannelLayoutRaw()
CAEChannelInfo CAESinkALSA::GetChannelLayoutRaw (const AEAudioFormat & format) inline private
References ALSAChannelMapPassthrough, CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, and CAEStreamInfo::STREAM_TYPE_TRUEHD.
Referenced by GetChannelLayout(), and GetChannelLayoutLegacy().
GetDelay()
void CAESinkALSA::GetDelay (AEDelayStatus & status) override virtual
Return a timestamped status structure with delay and sink info.
Parameters
status structure filled with sink status
Implements IAESink.
References m_formatSampleRateMul, m_pcm, and AEDelayStatus::SetDelay().
GetELD()
bool CAESinkALSA::GetELD (snd_hctl_t * hctl, int device, CAEDeviceInfo & info, bool & badHDMI) static private
References AE_DEVTYPE_HDMI, id, and CAEELDParser::Parse().
Referenced by EnumerateDevice().
GetName()
const char * CAESinkALSA::GetName () inline override virtual
Implements IAESink.
GetParamFromName()
std::string CAESinkALSA::GetParamFromName (const std::string & name, const std::string & param) static private
References name.
Referenced by EnumerateDevicesEx().
HandleError()
void CAESinkALSA::HandleError (const char * name, int err) private
References err(), CLog::Log(), LOGERROR, LOGINFO, m_pcm, name, and KODI::TIME::Sleep().
Referenced by AddPackets().
Initialize()
bool CAESinkALSA::Initialize (AEAudioFormat & format, std::string & device) override virtual
Implements IAESink.
References AE_DEVTYPE_HDMI, AE_DEVTYPE_IEC958, AE_FMT_RAW, AE_FMT_S16NE, AEDeviceTypeFromName(), CAESinkALSA::ALSAConfig::channels, CAEChannelInfo::Count(), CAESinkALSA::ALSAConfig::format, CAESinkALSA::ALSAConfig::frameSize, GetAESParams(), GetChannelLayout(), GetChannelLayoutLegacy(), InitializeHW(), InitializeSW(), CLog::Log(), LOGERROR, LOGINFO, m_device, m_format, m_formatSampleRateMul, m_initDevice, m_initFormat, m_passthrough, m_pcm, AEAudioFormat::m_sampleRate, OpenPCMDevice(), CAESinkALSA::ALSAConfig::periodSize, CAESinkALSA::ALSAConfig::sampleRate, and SelectALSAChannelMap().
InitializeHW()
bool CAESinkALSA::InitializeHW (const ALSAConfig & inconfig, ALSAConfig & outconfig) private
References AE_FMT_FLOAT, AE_FMT_INVALID, AE_FMT_MAX, AE_FMT_RAW, AE_FMT_S16BE, AE_FMT_S16LE, AE_FMT_S24NE4, AE_FMT_S24NE4MSB, AE_MIN_PERIODSIZE, AEFormatToALSAFormat(), CAESinkALSA::ALSAConfig::channels, CAEUtil::DataFormatToBits(), CAEUtil::DataFormatToStr(), CAESinkALSA::ALSAConfig::format, CAESinkALSA::ALSAConfig::frameSize, CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, LOGWARNING, m_bufferSize, m_fragmented, m_originalPeriodSize, m_passthrough, m_pcm, m_timeout, CAESinkALSA::ALSAConfig::periodSize, and CAESinkALSA::ALSAConfig::sampleRate.
Referenced by Initialize().
InitializeSW()
bool CAESinkALSA::InitializeSW (const ALSAConfig & inconfig) private
References CLog::Log(), LOGERROR, m_pcm, and CAESinkALSA::ALSAConfig::periodSize.
Referenced by Initialize().
OpenPCMDevice()
bool CAESinkALSA::OpenPCMDevice (const std::string & name, const std::string & params, int channels, snd_pcm_t ** pcmp, snd_config_t * lconf) static private
References name, and TryDeviceWithParams().
Referenced by EnumerateDevice(), and Initialize().
Register()
void CAESinkALSA::Register () static
References Cleanup(), AE::AESinkRegEntry::cleanupFunc, Create(), AE::AESinkRegEntry::createFunc, EnumerateDevicesEx(), AE::AESinkRegEntry::enumerateFunc, AE::CAESinkFactory::RegisterSink(), and AE::AESinkRegEntry::sinkName.
SelectALSAChannelMap()
snd_pcm_chmap_t * CAESinkALSA::SelectALSAChannelMap (const CAEChannelInfo & info) private
References AEChannelMapToALSAchmap(), ALSAchmapToAEChannelMap(), ALSAchmapToString(), CAEChannelInfo::BestMatch(), CAEChannelInfo::ContainsChannels(), CopyALSAchmap(), CAEChannelInfo::Count(), GetAlternateLayoutForm(), CServiceBroker::GetLogging(), CLog::Log(), LOGAUDIO, LOGDEBUG, and m_pcm.
Referenced by Initialize().
sndLibErrorHandler()
void CAESinkALSA::sndLibErrorHandler (const char * file, int line, const char * function, int err, const char * fmt, ...) static private
References err(), CServiceBroker::GetLogging(), CLog::Log(), LOGAUDIO, and LOGINFO.
Referenced by EnumerateDevicesEx().
SoundDeviceExists()
static bool CAESinkALSA::SoundDeviceExists (const std::string & device) static private
Stop()
void CAESinkALSA::Stop () virtual
References m_pcm.
Referenced by Deinitialize().
TryDevice()
bool CAESinkALSA::TryDevice (const std::string & name, snd_pcm_t ** pcmp, snd_config_t * lconf) static private
References ALSA_OPTIONS, err(), CLog::Log(), LOGINFO, and name.
Referenced by TryDeviceWithParams().
TryDeviceWithParams()
bool CAESinkALSA::TryDeviceWithParams (const std::string & name, const std::string & params, snd_pcm_t ** pcmp, snd_config_t * lconf) static private
References AppendParams(), name, and TryDevice().
Referenced by OpenPCMDevice().
Member Data Documentation
m_bufferSize
unsigned int CAESinkALSA::m_bufferSize = 0 private
Referenced by GetCacheTotal(), and InitializeHW().
m_device
std::string CAESinkALSA::m_device private
Referenced by Initialize().
m_format
AEAudioFormat CAESinkALSA::m_format private
Referenced by AddPackets(), and Initialize().
m_formatSampleRateMul
double CAESinkALSA::m_formatSampleRateMul = 0.0 private
Referenced by GetCacheTotal(), GetDelay(), and Initialize().
m_fragmented
bool CAESinkALSA::m_fragmented = false private
Referenced by AddPackets(), and InitializeHW().
m_initDevice
std::string CAESinkALSA::m_initDevice private
Referenced by Initialize().
m_initFormat
AEAudioFormat CAESinkALSA::m_initFormat private
Referenced by Initialize().
m_originalPeriodSize
unsigned int CAESinkALSA::m_originalPeriodSize = AE_MIN_PERIODSIZE private
Referenced by AddPackets(), and InitializeHW().
m_passthrough
bool CAESinkALSA::m_passthrough = false private
Referenced by GetAESParams(), Initialize(), and InitializeHW().
m_pcm
snd_pcm_t* CAESinkALSA::m_pcm private
Referenced by AddPackets(), Deinitialize(), Drain(), GetChannelLayout(), GetDelay(), HandleError(), Initialize(), InitializeHW(), InitializeSW(), SelectALSAChannelMap(), and Stop().
m_timeout
int CAESinkALSA::m_timeout = 0 private
Referenced by InitializeHW().
The documentation for this class was generated from the following files:
AESinkALSA.h
AESinkALSA.cpp