Kodi Documentation: ADDON::CRepositoryUpdater Class Reference
ADDON::CRepositoryUpdater Class Reference
#include <RepositoryUpdater.h>
Classes
struct RepositoryUpdated
Public Types
enum class UpdateScheduleType { First , Regular }
Public Member Functions
CRepositoryUpdater (CAddonMgr &addonMgr)
~CRepositoryUpdater () override
void Start ()
void CheckForUpdates (const ADDON::RepositoryPtr &repo, bool showProgress=false)
bool CheckForUpdates (bool showProgress=false)
void Await ()
void ScheduleUpdate (UpdateScheduleType scheduleType)
CDateTime LastUpdated () const
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
CEventStream< RepositoryUpdated > & Events ()
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Private Member Functions
CRepositoryUpdater (const CRepositoryUpdater &)=delete
CRepositoryUpdater (CRepositoryUpdater &&)=delete
CRepositoryUpdater & operator= (const CRepositoryUpdater &)=delete
CRepositoryUpdater & operator= (CRepositoryUpdater &&)=delete
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
void OnTimeout () override
void OnEvent (const ADDON::AddonEvent &event)
CDateTime ClosestNextCheck () const
Private Member Functions inherited from ITimerCallback
virtual ~ITimerCallback ()=default
Private Member Functions inherited from IJobCallback
virtual ~IJobCallback ()=default
Destructor for job call back objects.
virtual void OnJobAbort (unsigned int jobID, CJob *job)
An optional callback function used when a job will be aborted.
virtual void OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob *job)
An optional callback function that a job may call while processing.
Private Attributes
CCriticalSection m_criticalSection
CTimer m_timer
CEvent m_doneEvent
std::vector< CRepositoryUpdateJob * > m_jobs
CAddonMgr & m_addonMgr
CEventSource< RepositoryUpdated > m_events
Member Enumeration Documentation
UpdateScheduleType
enum class ADDON::CRepositoryUpdater::UpdateScheduleType strong
Enumerator
First
Update should be scheduled as the first update after application start or setting change.
Regular
Update should be scheduled as a regular update during application runtime.
Constructor & Destructor Documentation
CRepositoryUpdater() [1/3]
ADDON::CRepositoryUpdater::CRepositoryUpdater (CAddonMgr & addonMgr) explicit
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_ADDONS_AUTOUPDATES.
~CRepositoryUpdater()
ADDON::CRepositoryUpdater::~CRepositoryUpdater () override
References ADDON::CAddonMgr::Events(), CServiceBroker::GetSettingsComponent(), and m_addonMgr.
CRepositoryUpdater() [2/3]
ADDON::CRepositoryUpdater::CRepositoryUpdater (const CRepositoryUpdater &) private delete
CRepositoryUpdater() [3/3]
ADDON::CRepositoryUpdater::CRepositoryUpdater (CRepositoryUpdater &&) private delete
Member Function Documentation
Await()
void ADDON::CRepositoryUpdater::Await ()
Wait for any pending/in-progress updates to complete.
References m_doneEvent, and CEvent::Wait().
Referenced by ADDON::CAddonRepos::LoadAddonsFromDatabase().
CheckForUpdates() [1/2]
bool ADDON::CRepositoryUpdater::CheckForUpdates (bool showProgress = false)
Check all repositories for updates.
References addons, CheckForUpdates(), ADDON::CAddonMgr::GetAddons(), m_addonMgr, m_criticalSection, and ADDON::REPOSITORY.
CheckForUpdates() [2/2]
void ADDON::CRepositoryUpdater::CheckForUpdates (const ADDON::RepositoryPtr & repo, bool showProgress = false)
Check a single repository for updates.
References CServiceBroker::GetJobManager(), m_criticalSection, m_doneEvent, m_jobs, CJob::PRIORITY_LOW, CEvent::Reset(), and ADDON::SetProgressIndicator().
Referenced by CheckForUpdates(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), CONTEXTMENU::CCheckForUpdates::Execute(), ADDON::CAddonRepos::LoadAddonsFromDatabase(), CGUIWindowAddonBrowser::OnMessage(), OnTimeout(), and UpdateRepos().
ClosestNextCheck()
CDateTime ADDON::CRepositoryUpdater::ClosestNextCheck () const private
References ADDON::CAddonMgr::GetAddons(), m_addonMgr, ADDON::CAddonDatabase::Open(), and ADDON::REPOSITORY.
Referenced by ScheduleUpdate().
Events()
CEventStream< RepositoryUpdated > & ADDON::CRepositoryUpdater::Events () inline
References m_events.
Referenced by KODI::GAME::CGUIControllerWindow::OnDeinitWindow(), KODI::GAME::CGUIControllerWindow::OnInitWindow(), CGUIWindowAddonBrowser::OnMessage(), CDirectoryProvider::Reset(), and CDirectoryProvider::UpdateURL().
LastUpdated()
CDateTime ADDON::CRepositoryUpdater::LastUpdated () const
Returns the time of the last check (oldest). Invalid time if never checked.
References ADDON::CAddonMgr::GetAddons(), m_addonMgr, ADDON::CAddonDatabase::Open(), and ADDON::REPOSITORY.
Referenced by CGUIWindowAddonBrowser::SetProperties().
OnEvent()
void ADDON::CRepositoryUpdater::OnEvent (const ADDON::AddonEvent & event) private
References ADDON::AddonEvent::addonId, First, ADDON::CAddonMgr::HasType(), m_addonMgr, ADDON::REPOSITORY, and ScheduleUpdate().
Referenced by Start().
OnJobComplete()
void ADDON::CRepositoryUpdater::OnJobComplete (unsigned int jobID, bool success, CJob * job) override private virtual
The callback used when a job completes.
OnJobComplete is called at the completion of the job's DoWork() function, and is used to return information to the caller on the result of the job. On returning form this function the CJobManager will destroy this job.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
success the result from the DoWork call
job the job that has been processed. The job will be destroyed after this function returns
See also
CJobManager and CJob
Implements IJobCallback.
References ADDON::AUTO_UPDATES_NOTIFY, ADDON::AUTO_UPDATES_ON, ADDON::CAddonMgr::CheckAndInstallAddonUpdates(), g_localizeStrings, CLocalizeStrings::Get(), ADDON::CAddonSystemSettings::GetAddonAutoUpdateMode(), ADDON::CAddonMgr::GetAvailableUpdates(), CServiceBroker::GetEventLog(), ADDON::CAddonSystemSettings::GetInstance(), CLog::Log(), LOGDEBUG, m_addonMgr, m_criticalSection, m_doneEvent, m_events, m_jobs, CGUIDialogKaiToast::QueueNotification(), Regular, ScheduleUpdate(), CEvent::Set(), and TOAST_DISPLAY_TIME.
OnSettingChanged()
void ADDON::CRepositoryUpdater::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References First, ScheduleUpdate(), and CSettings::SETTING_ADDONS_AUTOUPDATES.
OnTimeout()
void ADDON::CRepositoryUpdater::OnTimeout () override private virtual
Implements ITimerCallback.
References CheckForUpdates(), CServiceBroker::GetGUI(), CLog::Log(), LOGDEBUG, m_timer, min, CTimer::RestartAsync(), WINDOW_FULLSCREEN_GAME, WINDOW_FULLSCREEN_VIDEO, and WINDOW_SLIDESHOW.
operator=() [1/2]
CRepositoryUpdater & ADDON::CRepositoryUpdater::operator= (const CRepositoryUpdater &) private delete
operator=() [2/2]
CRepositoryUpdater & ADDON::CRepositoryUpdater::operator= (CRepositoryUpdater &&) private delete
ScheduleUpdate()
void ADDON::CRepositoryUpdater::ScheduleUpdate (UpdateScheduleType scheduleType)
Schedule an automatic update to run based on settings and previous update times. May be called when there are external changes this updater must know about. Any previously scheduled update will be cancelled.
References ADDON::AUTO_UPDATES_NEVER, ClosestNextCheck(), CDateTime::GetCurrentDateTime(), ADDON::CAddonSystemSettings::GetInstance(), ADDON::CAddonMgr::HasAddons(), CLog::Log(), LOGDEBUG, LOGERROR, m_addonMgr, m_criticalSection, m_timer, Regular, ADDON::REPOSITORY, CTimer::Start(), and CTimer::Stop().
Referenced by OnEvent(), OnJobComplete(), OnSettingChanged(), and Start().
Start()
void ADDON::CRepositoryUpdater::Start ()
References ADDON::CAddonMgr::Events(), First, m_addonMgr, OnEvent(), and ScheduleUpdate().
Referenced by CApplication::Initialize().
Member Data Documentation
m_addonMgr
CAddonMgr& ADDON::CRepositoryUpdater::m_addonMgr private
Referenced by CheckForUpdates(), ClosestNextCheck(), LastUpdated(), OnEvent(), OnJobComplete(), ScheduleUpdate(), Start(), and ~CRepositoryUpdater().
m_criticalSection
CCriticalSection ADDON::CRepositoryUpdater::m_criticalSection private
Referenced by CheckForUpdates(), CheckForUpdates(), OnJobComplete(), and ScheduleUpdate().
m_doneEvent
CEvent ADDON::CRepositoryUpdater::m_doneEvent private
Referenced by Await(), CheckForUpdates(), and OnJobComplete().
m_events
CEventSource<RepositoryUpdated> ADDON::CRepositoryUpdater::m_events private
Referenced by Events(), and OnJobComplete().
m_jobs
std::vector<CRepositoryUpdateJob*> ADDON::CRepositoryUpdater::m_jobs private
Referenced by CheckForUpdates(), and OnJobComplete().
m_timer
CTimer ADDON::CRepositoryUpdater::m_timer private
Referenced by OnTimeout(), and ScheduleUpdate().
The documentation for this class was generated from the following files:
RepositoryUpdater.h
RepositoryUpdater.cpp