Kodi Documentation: CONTEXTMENU::CMoveDownFavourite Class Reference
CONTEXTMENU::CMoveDownFavourite Class Reference
#include <ContextMenus.h>
Public Member Functions
CMoveDownFavourite ()
bool IsVisible (const CFileItem &item) const override
Public Member Functions inherited from CONTEXTMENU::CFavouriteContextMenuAction
CFavouriteContextMenuAction (uint32_t label)
bool Execute (const std::shared_ptr< CFileItem > &item) const override
Public Member Functions inherited from CStaticContextMenuAction
CStaticContextMenuAction (uint32_t label)
std::string GetLabel (const CFileItem &item) const final
bool IsGroup () const final
Public Member Functions inherited from IContextMenuItem
virtual ~IContextMenuItem ()=default
virtual bool HasParent () const
Protected Member Functions
bool DoExecute (CFileItemList &items, const std::shared_ptr< CFileItem > &item) const override
Protected Member Functions inherited from CONTEXTMENU::CFavouriteContextMenuAction
~CFavouriteContextMenuAction () override=default
Constructor & Destructor Documentation
CMoveDownFavourite()
CONTEXTMENU::CMoveDownFavourite::CMoveDownFavourite () inline
Member Function Documentation
DoExecute()
bool CMoveDownFavourite::DoExecute (CFileItemList & items, const std::shared_ptr< CFileItem > & item) const override protected virtual
Implements CONTEXTMENU::CFavouriteContextMenuAction.
References FAVOURITES_UTILS::MoveItem().
IsVisible()
bool CMoveDownFavourite::IsVisible (const CFileItem & item) const override virtual
Reimplemented from CONTEXTMENU::CFavouriteContextMenuAction.
References CONTEXTMENU::CFavouriteContextMenuAction::IsVisible(), and FAVOURITES_UTILS::ShouldEnableMoveItems().
The documentation for this class was generated from the following files:
favourites/ContextMenus.h
favourites/ContextMenus.cpp