Kodi Documentation: AEDeviceEnumerationOSX Class Reference
AEDeviceEnumerationOSX Class Reference
#include <AEDeviceEnumerationOSX.h>
Classes
struct caStreamInfo
Public Member Functions
AEDeviceEnumerationOSX (AudioDeviceID deviceID)
C'tor - initialises the Enumerator and calls Enumerate.
~AEDeviceEnumerationOSX ()=default
CADeviceList GetDeviceInfoList () const
Gets the device list which was enumerated by the last call to Enumerate (which is also called in c'tor).
bool Enumerate ()
Fetches all metadata from the CoreAudio device which is needed to generate a proper DeviceList for AE This method is always called from C'tor but can be called multiple times if the streams of a device changed. This fills m_caStreamInfos. After this call - GetDeviceInfoList will reflect the Enumerated metadata.
unsigned int GetNumPlanes () const
Returns the number of Planes for a device. This will be 1 for non-planar devices and > 1 for planar devices.
bool IsPlanar () const
Checks if the m_deviceID belongs to a planar or non-planar device.
bool FindSuitableFormatForStream (UInt32 &streamIdx, const AEAudioFormat &format, bool virt, AudioStreamBasicDescription &outputFormat, AudioStreamID &outputStream) const
Tries to find a suitable CoreAudio format which matches the given AEAudioFormat as close as possible.
const std::string & GetMasterDeviceName () const
Returns the device name which belongs to m_deviceID without any stream/source suffixes.
void GetAEChannelMap (CAEChannelInfo &channelMap, unsigned int channelsPerFrame) const
Tries to return a proper channelmap from CA in a format AE understands.
float ScoreFormat (const AudioStreamBasicDescription &formatDesc, const AEAudioFormat &format) const
Scores a format based on:
Private Member Functions
bool isDigitalDevice () const
Checks if this is a digital device based on CA transportType or name.
void hasPassthroughOrDigitalFormats (const StreamFormatList &formatList, bool &hasPassthroughFormats, bool &hasDigitalFormat) const
Checks if there are passthrough formats or digital formats (the latter are passthrough formats with dedicated format config like AC3/DTS)
enum AEDeviceType getDeviceType (bool hasPassthroughFormats, bool isDigital, UInt32 numChannels, UInt32 transportType) const
Gets the AE devicetype for this device based the given criteria.
void fillStreamList ()
Fetches all ca streams from the ca device and fills m_channelsPerStream and m_streams.
float scoreSampleRate (Float64 destinationRate, unsigned int sourceRate) const
Scores a samplerate based on:
bool hasSampleRate (const AESampleRateList &list, const unsigned int samplerate) const
bool hasDataFormat (const AEDataFormatList &list, const enum AEDataFormat format) const
bool hasDataType (const AEDataTypeList &list, CAEStreamInfo::DataType type) const
AEDataFormatList caFormatToAE (const AudioStreamBasicDescription &formatDesc, bool isDigital) const
Converts a CA format description to a list of AEFormat descriptions (as one format can result in more then 1 AE format - e.x. AC3 ca format results in AC3 and DTS AE format.
AEDataTypeList caFormatToAEType (const AudioStreamBasicDescription &formatDesc, bool isDigital) const
enum AEChannel caChannelToAEChannel (const AudioChannelLabel &CAChannelLabel) const
Convert a CA channel label to an AE channel.
AEDataFormatList getFormatListForStream (UInt32 streamIdx) const
Returns all AE formats for the CA stream at the given index.
AEDataTypeList getTypeListForStream (UInt32 streamIdx) const
CAEChannelInfo getChannelInfoForStream (UInt32 streamIdx) const
Returns the AE channelinfo/channel map for the CA stream at the given index.
AESampleRateList getSampleRateListForStream (UInt32 streamIdx) const
Returns the AE samplerates for the CA stream at the given index.
std::string getDeviceNameForStream (UInt32 streamIdx) const
Returns the AE device name for the CA stream at the given index.
std::string getExtraDisplayNameForStream (UInt32 streamIdx) const
Returns the extra displayname shown to the User in addition to getDisplayNameForStream for the CA stream at the given index
Private Attributes
AudioDeviceID m_deviceID
bool m_isPlanar = false
std::string m_deviceName
std::vector< caStreamInfo > m_caStreamInfos
CCoreAudioDevice m_caDevice
Constructor & Destructor Documentation
AEDeviceEnumerationOSX()
AEDeviceEnumerationOSX::AEDeviceEnumerationOSX (AudioDeviceID deviceID)
C'tor - initialises the Enumerator and calls Enumerate.
Parameters
deviceID - the CoreAudio Device ID which will be the base of the enumerated device list
References Enumerate().
~AEDeviceEnumerationOSX()
AEDeviceEnumerationOSX::~AEDeviceEnumerationOSX () default
Member Function Documentation
caChannelToAEChannel()
enum AEChannel AEDeviceEnumerationOSX::caChannelToAEChannel (const AudioChannelLabel & CAChannelLabel) const private
Convert a CA channel label to an AE channel.
Parameters
CAChannelLabel - the CA channel label to be converted
Returns
the corresponding AEChannel
References AE_CH_BL, AE_CH_BLOC, AE_CH_BR, AE_CH_BROC, AE_CH_FC, AE_CH_FL, AE_CH_FLOC, AE_CH_FR, AE_CH_FROC, AE_CH_LFE, AE_CH_MAX, AE_CH_NULL, AE_CH_SL, AE_CH_SR, AE_CH_TBC, AE_CH_TBL, AE_CH_TBR, AE_CH_TC, AE_CH_TFC, AE_CH_TFL, AE_CH_TFR, and AE_CH_UNKNOWN1.
Referenced by GetAEChannelMap().
caFormatToAE()
AEDataFormatList AEDeviceEnumerationOSX::caFormatToAE (const AudioStreamBasicDescription & formatDesc, bool isDigital) const private
Converts a CA format description to a list of AEFormat descriptions (as one format can result in more then 1 AE format - e.x. AC3 ca format results in AC3 and DTS AE format.
Parameters
formatDesc [in] - The CA format description to be converted
isDigital [in] - Flag indicating if the parent stream of formatDesc is digital (for allowing bitstreaming without dedicated AC3 format in CA)
Returns
The list of converted AE formats.
References AE_FMT_FLOAT, AE_FMT_S16BE, AE_FMT_S16LE, AE_FMT_S16NE, AE_FMT_S24BE3, AE_FMT_S24LE3, AE_FMT_S24NE3, AE_FMT_S32BE, AE_FMT_S32LE, and AE_FMT_S32NE.
Referenced by getFormatListForStream().
caFormatToAEType()
AEDataTypeList AEDeviceEnumerationOSX::caFormatToAEType (const AudioStreamBasicDescription & formatDesc, bool isDigital) const private
References CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, and CAEStreamInfo::STREAM_TYPE_EAC3.
Referenced by getTypeListForStream().
Enumerate()
bool AEDeviceEnumerationOSX::Enumerate ()
Fetches all metadata from the CoreAudio device which is needed to generate a proper DeviceList for AE This method is always called from C'tor but can be called multiple times if the streams of a device changed. This fills m_caStreamInfos. After this call - GetDeviceInfoList will reflect the Enumerated metadata.
Returns
false when streamlist couldn't be fetched from device - else true
References CCoreAudioStream::GetAvailablePhysicalFormats(), CCoreAudioStream::GetAvailableVirtualFormats(), getDeviceType(), CCoreAudioDevice::GetName(), CCoreAudioDevice::GetNumChannelsOfStream(), CCoreAudioDevice::GetStreams(), CCoreAudioDevice::GetTransportType(), hasPassthroughOrDigitalFormats(), isDigitalDevice(), m_caDevice, m_caStreamInfos, m_deviceName, m_isPlanar, and AEDeviceEnumerationOSX::caStreamInfo::streamID.
Referenced by AEDeviceEnumerationOSX().
fillStreamList()
void AEDeviceEnumerationOSX::fillStreamList () private
Fetches all ca streams from the ca device and fills m_channelsPerStream and m_streams.
FindSuitableFormatForStream()
bool AEDeviceEnumerationOSX::FindSuitableFormatForStream (UInt32 & streamIdx, const AEAudioFormat & format, bool virt, AudioStreamBasicDescription & outputFormat, AudioStreamID & outputStream) const
Tries to find a suitable CoreAudio format which matches the given AEAudioFormat as close as possible.
Parameters
streamIdx [in/out] - if streamIdx != INT_MAX only formats of the given streamIdx are checked if streamIdx == INT_MAX - formats of all streams in the device are considered On success this parameter returns the selected streamIdx.
format [in] - the requested AE format which should be matched to the stream formats of CA
outputFormat [out] - the found CA format which matches best to the requested AE format
outputStream [out] - the coreaudio streamid which contains the coreaudio format returned in outputFormat
Returns
true if a matching corea audio format was found - else false
References CAEUtil::DataFormatToStr(), formats, CLog::Log(), LOGDEBUG, m_caStreamInfos, m_isPlanar, ScoreFormat(), and StreamDescriptionToString().
Referenced by CAESinkDARWINOSX::Initialize().
GetAEChannelMap()
void AEDeviceEnumerationOSX::GetAEChannelMap (CAEChannelInfo & channelMap, unsigned int channelsPerFrame) const
Tries to return a proper channelmap from CA in a format AE understands.
Parameters
channelMap [in/out] - returns the found channelmap in AE format if initialised with a map the number of channels is used to determine if stereo or multichannel map should be fetched
channelsPerFrame [int] - the number of channels which should be mapped (also decides if stereo or multichannel map is fetched similar to channelMap param)
References CA_MAX_CHANNELS, CAChannelMap, caChannelToAEChannel(), CCoreAudioChannelLayout::ChannelLayoutToString(), channelMap, CCoreAudioDevice::GetPreferredChannelLayout(), CCoreAudioDevice::GetPreferredChannelLayoutForStereo(), CLog::Log(), LOGDEBUG, and m_caDevice.
Referenced by getChannelInfoForStream(), and CAESinkDARWINOSX::Initialize().
getChannelInfoForStream()
CAEChannelInfo AEDeviceEnumerationOSX::getChannelInfoForStream (UInt32 streamIdx) const private
Returns the AE channelinfo/channel map for the CA stream at the given index.
Parameters
streamIdx [in] - index into m_caStreamInfos
Returns
- the of AE channel info for that stream.
References GetAEChannelMap(), CCoreAudioDevice::GetNumChannelsOfStream(), GetNumPlanes(), m_caDevice, m_caStreamInfos, and m_isPlanar.
Referenced by GetDeviceInfoList().
GetDeviceInfoList()
CADeviceList AEDeviceEnumerationOSX::GetDeviceInfoList () const
Gets the device list which was enumerated by the last call to Enumerate (which is also called in c'tor).
Returns
Returns the device list.
References CADeviceInstance::audioDeviceId, getChannelInfoForStream(), CCoreAudioDevice::GetDataSourceName(), CCoreAudioDevice::GetDataSources(), getDeviceNameForStream(), getExtraDisplayNameForStream(), getFormatListForStream(), getSampleRateListForStream(), getTypeListForStream(), m_caDevice, m_caStreamInfos, CAEDeviceInfo::m_channels, CAEDeviceInfo::m_dataFormats, m_deviceID, m_deviceName, CAEDeviceInfo::m_deviceName, CAEDeviceInfo::m_deviceType, CAEDeviceInfo::m_displayName, CAEDeviceInfo::m_displayNameExtra, m_isPlanar, CAEDeviceInfo::m_sampleRates, CAEDeviceInfo::m_streamTypes, CAEDeviceInfo::m_wantsIECPassthrough, CADeviceInstance::sourceId, and CADeviceInstance::streamIndex.
Referenced by EnumerateDevices().
getDeviceNameForStream()
std::string AEDeviceEnumerationOSX::getDeviceNameForStream (UInt32 streamIdx) const private
Returns the AE device name for the CA stream at the given index.
Parameters
streamIdx [in] - index into m_caStreamInfos
Returns
- The devicename for that stream
References m_deviceID, m_deviceName, and m_isPlanar.
Referenced by GetDeviceInfoList().
getDeviceType()
enum AEDeviceType AEDeviceEnumerationOSX::getDeviceType (bool hasPassthroughFormats, bool isDigital, UInt32 numChannels, UInt32 transportType) const private
Gets the AE devicetype for this device based the given criteria.
Parameters
hasPassthroughFormats [in] - flag indicating that the device has passthrough formats
isDigital [in] - flag indicating that the device is digital
numChannels [in] - the number of channels of the device
transportType [in] - the transportType of the device
Returns
the AE devicetype
References AE_DEVTYPE_DP, AE_DEVTYPE_HDMI, AE_DEVTYPE_IEC958, AE_DEVTYPE_PCM, and m_deviceName.
Referenced by Enumerate().
getExtraDisplayNameForStream()
std::string AEDeviceEnumerationOSX::getExtraDisplayNameForStream (UInt32 streamIdx) const private
Returns the extra displayname shown to the User in addition to getDisplayNameForStream for the CA stream at the given index
Parameters
streamIdx [in] - index into m_caStreamInfos
Returns
- The extra displayname for that stream (might be empty)
References CCoreAudioDevice::GetCurrentDataSourceName(), CCoreAudioDevice::GetNumChannelsOfStream(), CCoreAudioStream::GetStartingChannelInDevice(), CLog::Log(), LOGINFO, m_caDevice, m_caStreamInfos, and m_isPlanar.
Referenced by GetDeviceInfoList().
getFormatListForStream()
AEDataFormatList AEDeviceEnumerationOSX::getFormatListForStream (UInt32 streamIdx) const private
Returns all AE formats for the CA stream at the given index.
Parameters
streamIdx [in] - index into m_caStreamInfos
Returns
- the list of AE formats in that stream.
References caFormatToAE(), hasDataFormat(), and m_caStreamInfos.
Referenced by GetDeviceInfoList().
GetMasterDeviceName()
const std::string & AEDeviceEnumerationOSX::GetMasterDeviceName () const inline
Returns the device name which belongs to m_deviceID without any stream/source suffixes.
Returns
the CA device name
References m_deviceName.
Referenced by EnumerateDevices().
GetNumPlanes()
unsigned int AEDeviceEnumerationOSX::GetNumPlanes () const
Returns the number of Planes for a device. This will be 1 for non-planar devices and > 1 for planar devices.
Returns
Number of planes for this device.
References m_caStreamInfos, and m_isPlanar.
Referenced by getChannelInfoForStream(), and CAESinkDARWINOSX::Initialize().
getSampleRateListForStream()
AESampleRateList AEDeviceEnumerationOSX::getSampleRateListForStream (UInt32 streamIdx) const private
Returns the AE samplerates for the CA stream at the given index.
Parameters
streamIdx [in] - index into m_caStreamInfos
Returns
- the list of AE samplerates for that stream.
References hasSampleRate(), CLog::Log(), LOGINFO, and m_caStreamInfos.
Referenced by GetDeviceInfoList().
getTypeListForStream()
AEDataTypeList AEDeviceEnumerationOSX::getTypeListForStream (UInt32 streamIdx) const private
References caFormatToAEType(), hasDataType(), and m_caStreamInfos.
Referenced by GetDeviceInfoList().
hasDataFormat()
bool AEDeviceEnumerationOSX::hasDataFormat (const AEDataFormatList & list, const enum AEDataFormat format) const private
Referenced by getFormatListForStream().
hasDataType()
bool AEDeviceEnumerationOSX::hasDataType (const AEDataTypeList & list, CAEStreamInfo::DataType type) const private
Referenced by getTypeListForStream().
hasPassthroughOrDigitalFormats()
void AEDeviceEnumerationOSX::hasPassthroughOrDigitalFormats (const StreamFormatList & formatList, bool & hasPassthroughFormats, bool & hasDigitalFormat) const private
Checks if there are passthrough formats or digital formats (the latter are passthrough formats with dedicated format config like AC3/DTS)
Parameters
formatList [in] - the format list to be evaluated
hasPassthroughFormats [out] - true if there were passthrough formats in the list
hasDigitalFormat [out] - true if there were dedicated passthrough formats in the list
Referenced by Enumerate().
hasSampleRate()
bool AEDeviceEnumerationOSX::hasSampleRate (const AESampleRateList & list, const unsigned int samplerate) const private
Referenced by getSampleRateListForStream().
isDigitalDevice()
bool AEDeviceEnumerationOSX::isDigitalDevice () const private
Checks if this is a digital device based on CA transportType or name.
Returns
- true if this is a digital device - else false.
References CCoreAudioDevice::GetName(), CCoreAudioDevice::IsDigital(), and m_caDevice.
Referenced by Enumerate().
IsPlanar()
bool AEDeviceEnumerationOSX::IsPlanar () const inline
Checks if the m_deviceID belongs to a planar or non-planar device.
Returns
true if m_deviceID belongs to a planar device - else false.
References m_isPlanar.
Referenced by CAESinkDARWINOSX::Initialize().
ScoreFormat()
float AEDeviceEnumerationOSX::ScoreFormat (const AudioStreamBasicDescription & formatDesc, const AEAudioFormat & format) const
Scores a format based on:
Matching passthrough characteristics (i.e. passthrough flag)
Matching sample rate.
Matching bits per channel (or higher).
Matching number of channels (or higher).
Parameters
formatDesc [in] - The CA FormatDescription which should be scored
format [in] - the AE format which should be matched as good as possible
Returns
- the score of formatDesc - higher scores indicate better matching to "format" (scores > 10000 indicate passthrough formats)
References AE_FMT_FLOAT, AE_FMT_FLOATP, CAEUtil::DataFormatToBits(), scoreSampleRate(), and CAEStreamInfo::STREAM_TYPE_NULL.
Referenced by findMatchingFormat(), and FindSuitableFormatForStream().
scoreSampleRate()
float AEDeviceEnumerationOSX::scoreSampleRate (Float64 destinationRate, unsigned int sourceRate) const private
Scores a samplerate based on:
Prefer exact match
Prefer exact multiple of source samplerate and prefer the lowest
Parameters
destinationRate [in] - the destination samplerate to score
sourceRate [in] - the sourceRate of the audio format - this is the samplerate the score is based on
Returns
the score
Referenced by ScoreFormat().
Member Data Documentation
m_caDevice
CCoreAudioDevice AEDeviceEnumerationOSX::m_caDevice private
Referenced by Enumerate(), GetAEChannelMap(), getChannelInfoForStream(), GetDeviceInfoList(), getExtraDisplayNameForStream(), and isDigitalDevice().
m_caStreamInfos
std::vector<caStreamInfo> AEDeviceEnumerationOSX::m_caStreamInfos private
Referenced by Enumerate(), FindSuitableFormatForStream(), getChannelInfoForStream(), GetDeviceInfoList(), getExtraDisplayNameForStream(), getFormatListForStream(), GetNumPlanes(), getSampleRateListForStream(), and getTypeListForStream().
m_deviceID
AudioDeviceID AEDeviceEnumerationOSX::m_deviceID private
Referenced by GetDeviceInfoList(), and getDeviceNameForStream().
m_deviceName
std::string AEDeviceEnumerationOSX::m_deviceName private
Referenced by Enumerate(), GetDeviceInfoList(), getDeviceNameForStream(), getDeviceType(), and GetMasterDeviceName().
m_isPlanar
bool AEDeviceEnumerationOSX::m_isPlanar = false private
Referenced by Enumerate(), FindSuitableFormatForStream(), getChannelInfoForStream(), GetDeviceInfoList(), getDeviceNameForStream(), getExtraDisplayNameForStream(), GetNumPlanes(), and IsPlanar().
The documentation for this class was generated from the following files:
AEDeviceEnumerationOSX.h
AEDeviceEnumerationOSX.cpp