Kodi Documentation: CD3DVertexShader Class Reference
CD3DVertexShader Class Reference
#include <D3DResource.h>
Public Member Functions
CD3DVertexShader ()
~CD3DVertexShader ()
bool Create (const std::wstring &vertexFile, D3D11_INPUT_ELEMENT_DESC *vertexLayout, unsigned int vertexLayoutSize)
bool Create (const void *code, size_t codeLength, D3D11_INPUT_ELEMENT_DESC *vertexLayout, unsigned int vertexLayoutSize)
void ReleaseShader ()
void BindShader ()
void UnbindShader ()
void Release ()
bool IsInited ()
void OnDestroyDevice (bool fatal) override
void OnCreateDevice () override
Public Member Functions inherited from ID3DResource
virtual ~ID3DResource ()
Private Member Functions
bool CreateInternal ()
Private Attributes
bool m_inited
unsigned int m_vertexLayoutSize
D3D11_INPUT_ELEMENT_DESC * m_vertexLayout
Microsoft::WRL::ComPtr< ID3DBlob > m_VSBuffer
Microsoft::WRL::ComPtr< ID3D11VertexShader > m_VS
Microsoft::WRL::ComPtr< ID3D11InputLayout > m_inputLayout
Additional Inherited Members
Protected Member Functions inherited from ID3DResource
void Register ()
void Unregister ()
Protected Attributes inherited from ID3DResource
bool m_bRegistered = false
Constructor & Destructor Documentation
CD3DVertexShader()
CD3DVertexShader::CD3DVertexShader ()
References m_inited, m_inputLayout, m_vertexLayout, m_vertexLayoutSize, m_VS, and m_VSBuffer.
~CD3DVertexShader()
CD3DVertexShader::~CD3DVertexShader ()
References Release().
Member Function Documentation
BindShader()
void CD3DVertexShader::BindShader ()
References DX::DeviceResources::Get(), m_inited, m_inputLayout, and m_VS.
Referenced by CGUIShaderDX::ApplyStateBlock().
Create() [1/2]
bool CD3DVertexShader::Create (const std::wstring & vertexFile, D3D11_INPUT_ELEMENT_DESC * vertexLayout, unsigned int vertexLayoutSize)
References CreateInternal(), FAILED, DX::DeviceResources::Get(), LOGERROR, m_inited, m_vertexLayout, m_vertexLayoutSize, m_VSBuffer, ID3DResource::Register(), and ReleaseShader().
Referenced by CGUIShaderDX::Initialize().
Create() [2/2]
bool CD3DVertexShader::Create (const void * code, size_t codeLength, D3D11_INPUT_ELEMENT_DESC * vertexLayout, unsigned int vertexLayoutSize)
References CreateInternal(), FAILED, DX::DeviceResources::Get(), LOGERROR, m_inited, m_vertexLayout, m_vertexLayoutSize, m_VSBuffer, ID3DResource::Register(), and ReleaseShader().
CreateInternal()
bool CD3DVertexShader::CreateInternal () private
References FAILED, DX::DeviceResources::Get(), LOGDEBUG, LOGERROR, m_inputLayout, m_vertexLayout, m_vertexLayoutSize, m_VS, and m_VSBuffer.
Referenced by Create(), Create(), and OnCreateDevice().
IsInited()
bool CD3DVertexShader::IsInited () inline
References m_inited.
OnCreateDevice()
void CD3DVertexShader::OnCreateDevice (void) override virtual
Implements ID3DResource.
References CreateInternal(), m_inited, m_VS, and m_VSBuffer.
OnDestroyDevice()
void CD3DVertexShader::OnDestroyDevice (bool fatal) override virtual
Implements ID3DResource.
References ReleaseShader().
Release()
void CD3DVertexShader::Release ()
References m_vertexLayout, m_VSBuffer, ReleaseShader(), and ID3DResource::Unregister().
Referenced by CGUIShaderDX::Initialize(), and ~CD3DVertexShader().
ReleaseShader()
void CD3DVertexShader::ReleaseShader ()
References m_inited, m_inputLayout, m_VS, and UnbindShader().
Referenced by Create(), Create(), OnDestroyDevice(), and Release().
UnbindShader()
void CD3DVertexShader::UnbindShader ()
References DX::DeviceResources::Get(), and m_inited.
Referenced by ReleaseShader().
Member Data Documentation
m_inited
bool CD3DVertexShader::m_inited private
Referenced by BindShader(), CD3DVertexShader(), Create(), Create(), IsInited(), OnCreateDevice(), ReleaseShader(), and UnbindShader().
m_inputLayout
Microsoft::WRL::ComPtr<ID3D11InputLayout> CD3DVertexShader::m_inputLayout private
Referenced by BindShader(), CD3DVertexShader(), CreateInternal(), and ReleaseShader().
m_vertexLayout
D3D11_INPUT_ELEMENT_DESC* CD3DVertexShader::m_vertexLayout private
Referenced by CD3DVertexShader(), Create(), Create(), CreateInternal(), and Release().
m_vertexLayoutSize
unsigned int CD3DVertexShader::m_vertexLayoutSize private
Referenced by CD3DVertexShader(), Create(), Create(), and CreateInternal().
m_VS
Microsoft::WRL::ComPtr<ID3D11VertexShader> CD3DVertexShader::m_VS private
Referenced by BindShader(), CD3DVertexShader(), CreateInternal(), OnCreateDevice(), and ReleaseShader().
m_VSBuffer
Microsoft::WRL::ComPtr<ID3DBlob> CD3DVertexShader::m_VSBuffer private
Referenced by CD3DVertexShader(), Create(), Create(), CreateInternal(), OnCreateDevice(), and Release().
The documentation for this class was generated from the following files:
D3DResource.h
D3DResource.cpp