Kodi Documentation: KODI::WINDOWING::WAYLAND::CXkbcommonKeymap Class Reference
KODI::WINDOWING::WAYLAND::CXkbcommonKeymap Class Reference
#include <XkbcommonKeymap.h>
Classes
struct ModifierMapping
struct XkbComposeStateDeleter
struct XkbComposeTableDeleter
struct XkbKeymapDeleter
struct XkbStateDeleter
Public Member Functions
CXkbcommonKeymap (std::unique_ptr< xkb_keymap, XkbKeymapDeleter > keymap, std::unique_ptr< xkb_compose_table, XkbComposeTableDeleter > composeTable)
xkb_keysym_t KeysymForKeycode (xkb_keycode_t code) const
void UpdateMask (xkb_mod_mask_t depressed, xkb_mod_mask_t latched, xkb_mod_mask_t locked, xkb_mod_mask_t group)
xkb_mod_mask_t CurrentModifiers () const
XBMCKey XBMCKeyForKeycode (xkb_keycode_t code) const
XBMCMod ActiveXBMCModifiers () const
std::uint32_t UnicodeCodepointForKeycode (xkb_keycode_t code) const
bool ShouldKeycodeRepeat (xkb_keycode_t code) const
bool SupportsKeyComposition () const
KeyComposerStatus KeyComposerFeed (xkb_keycode_t code)
void KeyComposerFlush ()
Static Public Member Functions
static XBMCKey XBMCKeyForKeysym (xkb_keysym_t sym)
Static Private Member Functions
static std::unique_ptr< xkb_state, XkbStateDeleter > CreateXkbStateFromKeymap (xkb_keymap *keymap)
static std::unique_ptr< xkb_compose_state, XkbComposeStateDeleter > CreateXkbComposedStateStateFromTable (xkb_compose_table *composeTable)
Private Attributes
std::unique_ptr< xkb_keymap, XkbKeymapDeleter > m_keymap
std::unique_ptr< xkb_state, XkbStateDeleter > m_state
std::unique_ptr< xkb_compose_state, XkbComposeStateDeleter > m_composeState
std::vector< ModifierMapping > m_modifierMappings
Constructor & Destructor Documentation
CXkbcommonKeymap()
CXkbcommonKeymap::CXkbcommonKeymap (std::unique_ptr< xkb_keymap, XkbKeymapDeleter > keymap, std::unique_ptr< xkb_compose_table, XkbComposeTableDeleter > composeTable) explicit
Construct for known xkb_keymap
References CreateXkbComposedStateStateFromTable(), index(), m_composeState, m_keymap, m_modifierMappings, and table.
Member Function Documentation
ActiveXBMCModifiers()
XBMCMod CXkbcommonKeymap::ActiveXBMCModifiers () const
CurrentModifiers with XBMC flags
References CurrentModifiers(), m_modifierMappings, and XBMCKMOD_NONE.
CreateXkbComposedStateStateFromTable()
std::unique_ptr< xkb_compose_state, CXkbcommonKeymap::XkbComposeStateDeleter > CXkbcommonKeymap::CreateXkbComposedStateStateFromTable (xkb_compose_table * composeTable) static private
Referenced by CXkbcommonKeymap().
CreateXkbStateFromKeymap()
std::unique_ptr< xkb_state, CXkbcommonKeymap::XkbStateDeleter > CXkbcommonKeymap::CreateXkbStateFromKeymap (xkb_keymap * keymap) static private
CurrentModifiers()
xkb_mod_mask_t CXkbcommonKeymap::CurrentModifiers () const
Gets the currently depressed, latched and locked modifiers for the keyboard
References m_state.
Referenced by ActiveXBMCModifiers().
KeyComposerFeed()
KeyComposerStatus CXkbcommonKeymap::KeyComposerFeed (xkb_keycode_t code)
Feed a given keycode to the key composer
Parameters
code - the keycode
Returns
the status of the operation (both the state and the equivalent unicode dead key char resulting from the dead key press)
References KODI::WINDOWING::WAYLAND::CANCELLED, KODI::WINDOWING::WAYLAND::COMPOSING, KODI::WINDOWING::WAYLAND::FINISHED, KODI::WINDOWING::WAYLAND::KeyComposerStatus::keysym, m_composeState, m_state, and KODI::WINDOWING::WAYLAND::KeyComposerStatus::state.
KeyComposerFlush()
void CXkbcommonKeymap::KeyComposerFlush ()
Reset the composer state
References m_composeState.
KeysymForKeycode()
xkb_keysym_t CXkbcommonKeymap::KeysymForKeycode (xkb_keycode_t code) const
Get xkb keysym for keycode - only a single keysym is supported
References m_state.
Referenced by XBMCKeyForKeycode().
ShouldKeycodeRepeat()
bool CXkbcommonKeymap::ShouldKeycodeRepeat (xkb_keycode_t code) const
Check whether a given keycode should have key repeat
References m_keymap.
SupportsKeyComposition()
bool CXkbcommonKeymap::SupportsKeyComposition () const
Check if the system supports key composition
Returns
true if composition is supported, false otherwise
References m_composeState.
Referenced by UnicodeCodepointForKeycode().
UnicodeCodepointForKeycode()
std::uint32_t CXkbcommonKeymap::UnicodeCodepointForKeycode (xkb_keycode_t code) const
Get Unicode codepoint/UTF32 code for provided keycode
References m_composeState, m_state, SupportsKeyComposition(), and XBMCK_UNKNOWN.
UpdateMask()
void CXkbcommonKeymap::UpdateMask (xkb_mod_mask_t depressed, xkb_mod_mask_t latched, xkb_mod_mask_t locked, xkb_mod_mask_t group)
Updates the currently depressed, latched, locked and group modifiers for a keyboard being tracked.
This function must be called whenever modifiers change, or the state will be wrong and keysym translation will be off.
References depressed, and m_state.
XBMCKeyForKeycode()
XBMCKey CXkbcommonKeymap::XBMCKeyForKeycode (xkb_keycode_t code) const
Get XBMCKey for provided keycode
References KeysymForKeycode(), and XBMCKeyForKeysym().
XBMCKeyForKeysym()
XBMCKey CXkbcommonKeymap::XBMCKeyForKeysym (xkb_keysym_t sym) static
References XBMCK_UNKNOWN.
Referenced by XBMCKeyForKeycode().
Member Data Documentation
m_composeState
std::unique_ptr<xkb_compose_state, XkbComposeStateDeleter> KODI::WINDOWING::WAYLAND::CXkbcommonKeymap::m_composeState private
Referenced by CXkbcommonKeymap(), KeyComposerFeed(), KeyComposerFlush(), SupportsKeyComposition(), and UnicodeCodepointForKeycode().
m_keymap
std::unique_ptr<xkb_keymap, XkbKeymapDeleter> KODI::WINDOWING::WAYLAND::CXkbcommonKeymap::m_keymap private
Referenced by CXkbcommonKeymap(), and ShouldKeycodeRepeat().
m_modifierMappings
std::vector<ModifierMapping> KODI::WINDOWING::WAYLAND::CXkbcommonKeymap::m_modifierMappings private
Referenced by ActiveXBMCModifiers(), and CXkbcommonKeymap().
m_state
std::unique_ptr<xkb_state, XkbStateDeleter> KODI::WINDOWING::WAYLAND::CXkbcommonKeymap::m_state private
Referenced by CurrentModifiers(), KeyComposerFeed(), KeysymForKeycode(), UnicodeCodepointForKeycode(), and UpdateMask().
The documentation for this class was generated from the following files:
XkbcommonKeymap.h
XkbcommonKeymap.cpp