Kodi Documentation: CGUIFontTTFDX Class Reference
CGUIFontTTFDX Class Reference
Guilib classes » Graphics and Screen » Textures and Fonts
#include <GUIFontTTFDX.h>
Public Member Functions
CGUIFontTTFDX (const std::string &fontIdent)
virtual ~CGUIFontTTFDX (void)
bool FirstBegin () override
void LastEnd () override
CVertexBuffer CreateVertexBuffer (const std::vector< SVertex > &vertices) const override
void DestroyVertexBuffer (CVertexBuffer &bufferHandle) const override
void OnDestroyDevice (bool fatal) override
void OnCreateDevice () override
Public Member Functions inherited from CGUIFontTTF
virtual ~CGUIFontTTF ()
void Clear ()
bool Load (const std::string &strFilename, float height=20.0f, float aspect=1.0f, float lineSpacing=1.0f, bool border=false)
void Begin ()
void End ()
const std::string & GetFontIdent () const
Public Member Functions inherited from ID3DResource
virtual ~ID3DResource ()
Static Public Member Functions
static void CreateStaticIndexBuffer (void)
static void DestroyStaticIndexBuffer (void)
Static Public Member Functions inherited from CGUIFontTTF
static CGUIFontTTF * CreateGUIFontTTF (const std::string &fontIdent)
Protected Member Functions
std::unique_ptr< CTexture > ReallocTexture (unsigned int &newHeight) override
bool CopyCharToTexture (FT_BitmapGlyph bitGlyph, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2) override
void DeleteHardwareTexture () override
Protected Member Functions inherited from CGUIFontTTF
CGUIFontTTF (const std::string &fontIdent)
void AddReference ()
void RemoveReference ()
std::vector< Glyph > GetHarfBuzzShapedGlyphs (const vecText &text)
float GetTextWidthInternal (const vecText &text)
float GetTextWidthInternal (const vecText &text, const std::vector< Glyph > &glyph)
float GetCharWidthInternal (character_t ch)
float GetTextHeight (float lineSpacing, int numLines) const
float GetTextBaseLine () const
float GetLineHeight (float lineSpacing) const
float GetFontHeight () const
void DrawTextInternal (CGraphicContext &context, float x, float y, const std::vector< KODI::UTILS::COLOR::Color > &colors, const vecText &text, uint32_t alignment, float maxPixelWidth, bool scrolling, float dx=0.0f, float dy=0.0f)
Character * GetCharacter (character_t letter, FT_UInt glyphIndex)
bool CacheCharacter (FT_UInt glyphIndex, uint32_t style, Character *ch)
void RenderCharacter (CGraphicContext &context, float posX, float posY, const Character *ch, KODI::UTILS::COLOR::Color color, bool roundX, std::vector< SVertex > &vertices)
void ClearCharacterCache ()
void SetGlyphStrength (FT_GlyphSlot slot, int glyphStrength)
unsigned int GetTextureLineHeight () const
the height of each line in the texture. Accounts for spacing between lines to avoid characters overlapping.
unsigned int GetMaxFontHeight () const
Protected Member Functions inherited from ID3DResource
void Register ()
void Unregister ()
Private Member Functions
bool UpdateDynamicVertexBuffer (const SVertex *pSysMem, unsigned int count)
Static Private Member Functions
static void AddReference (CGUIFontTTFDX *font, CD3DBuffer *pBuffer)
static void ClearReference (CGUIFontTTFDX *font, CD3DBuffer *pBuffer)
Private Attributes
unsigned m_vertexWidth {0}
std::unique_ptr< CD3DTexture > m_speedupTexture
Microsoft::WRL::ComPtr< ID3D11Buffer > m_vertexBuffer
std::list< CD3DBuffer * > m_buffers
Static Private Attributes
static bool m_staticIndexBufferCreated = false
static Microsoft::WRL::ComPtr< ID3D11Buffer > m_staticIndexBuffer = nullptr
Additional Inherited Members
Static Protected Member Functions inherited from CGUIFontTTF
static void ObliqueGlyph (FT_GlyphSlot slot)
Protected Attributes inherited from CGUIFontTTF
float m_height {0.0f}
std::unique_ptr< CTexture > m_texture
unsigned int m_textureWidth {0}
unsigned int m_textureHeight {0}
int m_posX {0}
int m_posY {0}
KODI::UTILS::COLOR::Color m_color {KODI::UTILS::COLOR::NONE}
std::vector< Character > m_char
Character * m_charquick [LOOKUPTABLE_SIZE] {nullptr}
bool m_ellipseCached {false}
float m_ellipsesWidth {0.0f}
unsigned int m_cellBaseLine {0}
unsigned int m_cellHeight {0}
unsigned int m_maxFontHeight {0}
unsigned int m_nestedBeginCount {0}
FT_Face m_face {nullptr}
FT_Stroker m_stroker {nullptr}
hb_font_t * m_hbFont {nullptr}
float m_originX {0.0f}
float m_originY {0.0f}
unsigned int m_nTexture {0}
std::vector< CTranslatedVertices > m_vertexTrans
std::vector< SVertex > m_vertex
float m_textureScaleX {0.0f}
float m_textureScaleY {0.0f}
const std::string m_fontIdent
std::vector< uint8_t > m_fontFileInMemory
CGUIFontCache< CGUIFontCacheStaticPosition, CGUIFontCacheStaticValue > m_staticCache
CGUIFontCache< CGUIFontCacheDynamicPosition, CGUIFontCacheDynamicValue > m_dynamicCache
CRenderSystemBase * m_renderSystem
Protected Attributes inherited from ID3DResource
bool m_bRegistered = false
Constructor & Destructor Documentation
CGUIFontTTFDX()
CGUIFontTTFDX::CGUIFontTTFDX (const std::string & fontIdent) explicit
~CGUIFontTTFDX()
CGUIFontTTFDX::~CGUIFontTTFDX (void) virtual
References m_buffers, m_staticIndexBuffer, m_staticIndexBufferCreated, m_vertexBuffer, and m_vertexWidth.
Member Function Documentation
AddReference()
void CGUIFontTTFDX::AddReference (CGUIFontTTFDX * font, CD3DBuffer * pBuffer) static private
References m_buffers.
ClearReference()
void CGUIFontTTFDX::ClearReference (CGUIFontTTFDX * font, CD3DBuffer * pBuffer) static private
References m_buffers.
Referenced by DestroyVertexBuffer().
CopyCharToTexture()
bool CGUIFontTTFDX::CopyCharToTexture (FT_BitmapGlyph bitGlyph, unsigned int x1, unsigned int y1, unsigned int x2, unsigned int y2) override protected virtual
Implements CGUIFontTTF.
References DX::DeviceResources::Get(), and m_speedupTexture.
CreateStaticIndexBuffer()
void CGUIFontTTFDX::CreateStaticIndexBuffer (void) static
References DX::DeviceResources::Get(), index(), m_staticIndexBuffer, and m_staticIndexBufferCreated.
Referenced by LastEnd().
CreateVertexBuffer()
CVertexBuffer CGUIFontTTFDX::CreateVertexBuffer (const std::vector< SVertex > & vertices) const override virtual
Reimplemented from CGUIFontTTF.
References CGUIFontTTF::AddReference(), and LOGERROR.
DeleteHardwareTexture()
void CGUIFontTTFDX::DeleteHardwareTexture () override protected virtual
Implements CGUIFontTTF.
DestroyStaticIndexBuffer()
static void CGUIFontTTFDX::DestroyStaticIndexBuffer (void) static
DestroyVertexBuffer()
void CGUIFontTTFDX::DestroyVertexBuffer (CVertexBuffer & bufferHandle) const override virtual
Reimplemented from CGUIFontTTF.
References ClearReference().
FirstBegin()
bool CGUIFontTTFDX::FirstBegin () override virtual
Implements CGUIFontTTF.
References CGUIShaderDX::Begin(), DX::DeviceResources::Get(), and SHADER_METHOD_RENDER_FONT.
LastEnd()
void CGUIFontTTFDX::LastEnd () override virtual
Implements CGUIFontTTF.
References CreateStaticIndexBuffer(), CGUIShaderDX::DrawIndexed(), DX::DeviceResources::Get(), CD3DBuffer::Get(), CWinSystemBase::GetGfxContext(), CGraphicContext::GetScissors(), CGUIShaderDX::GetView(), CServiceBroker::GetWinSystem(), CRectGen< T >::Intersect(), CRectGen< T >::IsEmpty(), m_speedupTexture, m_staticIndexBuffer, CGUIFontTTF::m_vertex, m_vertexBuffer, CGUIFontTTF::m_vertexTrans, CGUIShaderDX::RestoreBuffers(), CGUIShaderDX::SetShaderViews(), CGUIShaderDX::SetView(), CGraphicContext::StereoCorrection(), and UpdateDynamicVertexBuffer().
OnCreateDevice()
void CGUIFontTTFDX::OnCreateDevice (void) override virtual
Implements ID3DResource.
OnDestroyDevice()
void CGUIFontTTFDX::OnDestroyDevice (bool fatal) override virtual
Implements ID3DResource.
References m_staticIndexBuffer, m_staticIndexBufferCreated, m_vertexBuffer, and m_vertexWidth.
ReallocTexture()
std::unique_ptr< CTexture > CGUIFontTTFDX::ReallocTexture (unsigned int & newHeight) override protected virtual
Implements CGUIFontTTF.
References CGUIFontCache< Position, Value >::Flush(), DX::DeviceResources::Get(), CGUIFontTTF::m_dynamicCache, m_speedupTexture, CGUIFontTTF::m_staticCache, CGUIFontTTF::m_texture, CGUIFontTTF::m_textureHeight, CGUIFontTTF::m_textureScaleY, CGUIFontTTF::m_textureWidth, and XB_FMT_A8.
UpdateDynamicVertexBuffer()
bool CGUIFontTTFDX::UpdateDynamicVertexBuffer (const SVertex * pSysMem, unsigned int count) private
References FAILED, DX::DeviceResources::Get(), LOGERROR, m_vertexBuffer, and m_vertexWidth.
Referenced by LastEnd().
Member Data Documentation
m_buffers
std::list<CD3DBuffer*> CGUIFontTTFDX::m_buffers private
Referenced by AddReference(), ClearReference(), and ~CGUIFontTTFDX().
m_speedupTexture
std::unique_ptr<CD3DTexture> CGUIFontTTFDX::m_speedupTexture private
Referenced by CopyCharToTexture(), LastEnd(), and ReallocTexture().
m_staticIndexBuffer
ComPtr< ID3D11Buffer > CGUIFontTTFDX::m_staticIndexBuffer = nullptr static private
Referenced by CreateStaticIndexBuffer(), LastEnd(), OnDestroyDevice(), and ~CGUIFontTTFDX().
m_staticIndexBufferCreated
bool CGUIFontTTFDX::m_staticIndexBufferCreated = false static private
Referenced by CreateStaticIndexBuffer(), OnDestroyDevice(), and ~CGUIFontTTFDX().
m_vertexBuffer
Microsoft::WRL::ComPtr<ID3D11Buffer> CGUIFontTTFDX::m_vertexBuffer private
Referenced by LastEnd(), OnDestroyDevice(), UpdateDynamicVertexBuffer(), and ~CGUIFontTTFDX().
m_vertexWidth
unsigned CGUIFontTTFDX::m_vertexWidth {0} private
Referenced by OnDestroyDevice(), UpdateDynamicVertexBuffer(), and ~CGUIFontTTFDX().
The documentation for this class was generated from the following files:
GUIFontTTFDX.h
GUIFontTTFDX.cpp