Kodi Documentation: CScraperUrl Class Reference
CScraperUrl Class Reference
#include <ScraperUrl.h>
Classes
struct SUrlEntry
Public Types
enum class UrlType { General = 1 , Season = 2 }
Public Member Functions
CScraperUrl ()
CScraperUrl (const std::string &strUrl)
CScraperUrl (const TiXmlElement *element)
~CScraperUrl ()
void Clear ()
bool HasData () const
const std::string & GetData () const
void SetData (std::string data)
const std::string & GetTitle () const
void SetTitle (std::string title)
const std::string & GetId () const
void SetId (std::string id)
double GetRelevance () const
void SetRelevance (double relevance)
bool HasUrls () const
const std::vector< SUrlEntry > & GetUrls () const
void SetUrls (std::vector< SUrlEntry > urls)
void AppendUrl (SUrlEntry url)
const SUrlEntry GetFirstUrlByType (const std::string &type="") const
const SUrlEntry GetSeasonUrl (int season, const std::string &type="") const
unsigned int GetMaxSeasonUrl () const
std::string GetFirstThumbUrl () const
void GetThumbUrls (std::vector< std::string > &thumbs, const std::string &type="", int season=-1, bool unique=false) const
fetch the full URLs (including referrer) of thumbs
bool Parse ()
bool ParseFromData (const std::string &data)
bool ParseAndAppendUrl (const TiXmlElement *element)
bool ParseAndAppendUrlsFromEpisodeGuide (const std::string &episodeGuide)
void AddParsedUrl (const std::string &url, const std::string &aspect="", const std::string &preview="", const std::string &referrer="", const std::string &cache="", bool post=false, bool isgz=false, int season=-1)
Static Public Member Functions
static std::string GetThumbUrl (const CScraperUrl::SUrlEntry &entry)
fetch the full URL (including referrer) of a thumb
static bool Get (const SUrlEntry &scrURL, std::string &strHTML, XFILE::CCurlFile &http, const std::string &cacheContext)
Public Attributes
std::string m_data
Private Attributes
std::string m_title
std::string m_id
double m_relevance
std::vector< SUrlEntry > m_urls
bool m_parsed
Member Enumeration Documentation
UrlType
enum class CScraperUrl::UrlType strong
Enumerator
General
Season
Constructor & Destructor Documentation
CScraperUrl() [1/3]
CScraperUrl::CScraperUrl ()
CScraperUrl() [2/3]
CScraperUrl::CScraperUrl (const std::string & strUrl) explicit
References ParseFromData().
CScraperUrl() [3/3]
CScraperUrl::CScraperUrl (const TiXmlElement * element) explicit
References ParseAndAppendUrl().
~CScraperUrl()
CScraperUrl::~CScraperUrl () default
Member Function Documentation
AddParsedUrl()
void CScraperUrl::AddParsedUrl (const std::string & url, const std::string & aspect = "", const std::string & preview = "", const std::string & referrer = "", const std::string & cache = "", bool post = false, bool isgz = false, int season = -1)
References CScraperUrl::SUrlEntry::m_aspect, CScraperUrl::SUrlEntry::m_cache, m_data, CScraperUrl::SUrlEntry::m_isgz, m_parsed, CScraperUrl::SUrlEntry::m_post, CScraperUrl::SUrlEntry::m_preview, CScraperUrl::SUrlEntry::m_season, CScraperUrl::SUrlEntry::m_spoof, CScraperUrl::SUrlEntry::m_type, m_urls, Season, and text.
Referenced by XBMCAddon::xbmc::InfoTagVideo::addAvailableArtworkRaw(), ADDON::DetailsFromFileItem< CArtist >(), CArtist::Load(), and ADDON::ParseThumbs().
AppendUrl()
void CScraperUrl::AppendUrl (SUrlEntry url) inline
References m_urls.
Referenced by ADDON::FromFileItem< CMusicAlbumInfo >(), ADDON::FromFileItem< CMusicArtistInfo >(), ADDON::FromFileItem< CScraperUrl >(), ADDON::CScraper::GetEpisodeList(), and ADDON::CScraper::NfoUrl().
Clear()
void CScraperUrl::Clear ()
References m_data, m_parsed, m_relevance, and m_urls.
Referenced by CNfoFile::Close(), CAlbum::Reset(), CArtist::Reset(), CVideoInfoTag::Reset(), and CVideoLibraryRefreshingJob::Work().
Get()
bool CScraperUrl::Get (const SUrlEntry & scrURL, std::string & strHTML, XFILE::CCurlFile & http, const std::string & cacheContext) static
References URIUtils::AddFileToFolder(), CCharsetDetection::ConvertHtmlToUtf8(), CCharsetDetection::ConvertPlainTextToUtf8(), XFILE::CFile::Exists(), XFILE::FILE_PROPERTY_CONTENT_CHARSET, XFILE::FILE_PROPERTY_MIME_TYPE, CMime::FileTypeGZip, CMime::FileTypeHtml, CMime::FileTypePlainText, CMime::FileTypeUnknown, CMime::FileTypeXml, CMime::FileTypeZip, g_charsetConverter, CURL::Get(), XFILE::CCurlFile::Get(), CMime::GetFileTypeFromContent(), CMime::GetFileTypeFromMime(), CURL::GetOptions(), XFILE::CCurlFile::GetProperty(), CServiceBroker::GetSettingsComponent(), CXBMCTinyXML::GetUsedCharset(), CLog::Log(), LOGDEBUG, LOGWARNING, CScraperUrl::SUrlEntry::m_cache, CScraperUrl::SUrlEntry::m_isgz, CScraperUrl::SUrlEntry::m_post, CScraperUrl::SUrlEntry::m_spoof, CScraperUrl::SUrlEntry::m_url, CXBMCTinyXML::Parse(), XFILE::CCurlFile::Post(), CURL::SetOptions(), XFILE::CCurlFile::SetReferer(), and XFILE::CZipFile::UnpackFromMemory().
Referenced by ADDON::CScraper::InternalRun().
GetData()
const std::string & CScraperUrl::GetData () const inline
References m_data.
Referenced by CVideoInfoTag::Archive(), ADDON::CScraper::FindAlbum(), ADDON::CScraper::FindArtist(), CAlbum::Load(), CArtist::Load(), CVideoInfoTag::ParseNative(), CVideoInfoTag::Save(), CAlbum::Save(), CArtist::Save(), CMusicDatabase::UpdateAlbum(), and CMusicDatabase::UpdateArtist().
GetFirstThumbUrl()
std::string CScraperUrl::GetFirstThumbUrl () const
References GetThumbUrl(), and m_urls.
Referenced by MUSIC_INFO::CMusicInfoScanner::DownloadAlbumInfo(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), ADDON::CScraper::FindMovie(), ADDON::CScraper::GetAlbumDetails(), ADDON::CScraper::GetArtistDetails(), ADDON::CScraper::GetEpisodeList(), XBMCAddon::xbmc::InfoTagVideo::getPictureURL(), ADDON::CScraper::GetVideoDetails(), CVideoInfoDownloader::Process(), MUSIC_INFO::CMusicInfoScanner::ResolveMusicBrainz(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), XBMCAddon::xbmc::Actor::ToActorInfo(), and CVideoLibraryRefreshingJob::Work().
GetFirstUrlByType()
const CScraperUrl::SUrlEntry CScraperUrl::GetFirstUrlByType (const std::string & type = "") const
References m_urls.
Referenced by MUSIC_INFO::CMusicInfoScanner::AddAlbumArtwork(), MUSIC_INFO::CMusicInfoScanner::AddArtistArtwork(), TEST(), XBMCAddon::xbmc::Actor::ToActorInfo(), MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseAlbumInfo(), and MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseArtistInfo().
GetId()
const std::string & CScraperUrl::GetId () const inline
References m_id.
Referenced by ADDON::CScraper::GetVideoDetails().
GetMaxSeasonUrl()
unsigned int CScraperUrl::GetMaxSeasonUrl () const
References m_urls, and Season.
GetRelevance()
double CScraperUrl::GetRelevance () const inline
References m_relevance.
Referenced by ADDON::RelevanceSortFunction().
GetSeasonUrl()
const CScraperUrl::SUrlEntry CScraperUrl::GetSeasonUrl (int season, const std::string & type = "") const
References m_urls.
GetThumbUrl()
std::string CScraperUrl::GetThumbUrl (const CScraperUrl::SUrlEntry & entry) static
fetch the full URL (including referrer) of a thumb
Parameters
URL entry to use to create the full URL
Returns
the full URL, including referrer
References CScraperUrl::SUrlEntry::m_spoof, and CScraperUrl::SUrlEntry::m_url.
Referenced by MUSIC_INFO::CMusicInfoScanner::AddAlbumArtwork(), MUSIC_INFO::CMusicInfoScanner::AddArtistArtwork(), MUSIC_INFO::CMusicInfoScanner::AddRemoteArtwork(), KODI::VIDEO::CVideoInfoScanner::FetchActorThumbs(), GetFirstThumbUrl(), KODI::VIDEO::CVideoInfoScanner::GetImage(), KODI::VIDEO::CVideoInfoScanner::GetSeasonThumbs(), GetThumbUrls(), XBMCAddon::xbmcgui::ListItem::setCast(), CGUIDialogVideoInfo::SetMovie(), XBMCAddon::xbmc::Actor::ToActorInfo(), MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseAlbumInfo(), and MUSIC_INFO::CMusicInfoScanner::UpdateDatabaseArtistInfo().
GetThumbUrls()
void CScraperUrl::GetThumbUrls (std::vector< std::string > & thumbs, const std::string & type = "", int season = -1, bool unique = false) const
fetch the full URLs (including referrer) of thumbs
Parameters
thumbs [out] vector of thumb URLs to fill
type the type of thumb URLs to fetch, if empty (the default) picks any
season number of season that we want thumbs for, -1 indicates no season (the default)
unique avoid adding duplicate URLs when adding to a thumbs vector with existing items
References General, GetThumbUrl(), m_urls, and Season.
Referenced by KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkMovieSetHandler::GetRemoteArt(), and CGUIDialogMusicInfo::OnGetArt().
GetTitle()
const std::string & CScraperUrl::GetTitle () const inline
References m_title.
Referenced by ADDON::CScraper::FindMovie(), KODI::VIDEO::CVideoInfoScanner::GetDetails(), and CVideoLibraryRefreshingJob::Work().
GetUrls()
const std::vector< SUrlEntry > & CScraperUrl::GetUrls () const inline
References m_urls.
Referenced by MUSIC_INFO::CMusicInfoScanner::AddRemoteArtwork(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), CMusicDatabase::GetAvailableArtForItem(), CMusicDatabase::GetAvailableArtTypesForItem(), anonymous_namespace{VideoDatabase.cpp}::GetMovieSetAvailableArt(), anonymous_namespace{VideoDatabase.cpp}::GetMovieSetAvailableArtTypes(), anonymous_namespace{VideoDatabase.cpp}::GetSeasonAvailableArt(), anonymous_namespace{VideoDatabase.cpp}::GetSeasonAvailableArtTypes(), KODI::VIDEO::CVideoInfoScanner::GetSeasonThumbs(), ADDON::CScraper::InternalRun(), CAlbum::Load(), CArtist::Load(), and CVideoInfoTag::ParseNative().
HasData()
bool CScraperUrl::HasData () const inline
References m_data.
Referenced by CVideoInfoTag::Merge(), CVideoInfoTag::Save(), CAlbum::Save(), and CArtist::Save().
HasUrls()
bool CScraperUrl::HasUrls () const inline
References m_urls.
Referenced by MUSIC_INFO::CMusicInfoScanner::AddAlbumArtwork(), MUSIC_INFO::CMusicInfoScanner::AddArtistArtwork(), CNfoFile::Create(), ADDON::CScraper::FindAlbum(), ADDON::CScraper::FindArtist(), ADDON::CScraper::GetArtistDetails(), ADDON::CScraper::GetEpisodeList(), CVideoInfoDownloader::Process(), MUSIC_INFO::CMusicInfoScanner::ResolveMusicBrainz(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), CNfoFile::Scrape(), and CVideoLibraryRefreshingJob::Work().
Parse()
bool CScraperUrl::Parse ()
References m_data, m_parsed, and ParseFromData().
Referenced by KODI::VIDEO::CVideoInfoScanner::GetArtwork(), anonymous_namespace{VideoDatabase.cpp}::GetMovieSetAvailableArt(), anonymous_namespace{VideoDatabase.cpp}::GetMovieSetAvailableArtTypes(), XBMCAddon::xbmc::InfoTagVideo::getPictureURL(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkMovieSetHandler::GetRemoteArt(), anonymous_namespace{VideoDatabase.cpp}::GetSeasonAvailableArt(), anonymous_namespace{VideoDatabase.cpp}::GetSeasonAvailableArtTypes(), and CVideoInfoTag::ParseNative().
ParseAndAppendUrl()
bool CScraperUrl::ParseAndAppendUrl (const TiXmlElement * element)
References XMLUtils::GetAttribute(), CScraperUrl::SUrlEntry::m_aspect, CScraperUrl::SUrlEntry::m_cache, m_data, CScraperUrl::SUrlEntry::m_isgz, m_parsed, CScraperUrl::SUrlEntry::m_post, CScraperUrl::SUrlEntry::m_preview, CScraperUrl::SUrlEntry::m_season, CScraperUrl::SUrlEntry::m_spoof, CScraperUrl::SUrlEntry::m_type, m_urls, and Season.
Referenced by CScraperUrl(), ADDON::CScraper::FindAlbum(), ADDON::CScraper::FindArtist(), ADDON::CScraper::FindMovie(), ADDON::CScraper::GetEpisodeList(), CAlbum::Load(), CArtist::Load(), ADDON::CScraper::NfoUrl(), ParseAndAppendUrlsFromEpisodeGuide(), ParseFromData(), CVideoInfoTag::ParseNative(), ADDON::CScraper::ResolveIDToUrl(), and ADDON::CScraper::Run().
ParseAndAppendUrlsFromEpisodeGuide()
bool CScraperUrl::ParseAndAppendUrlsFromEpisodeGuide (const std::string & episodeGuide)
References m_data, m_parsed, CXBMCTinyXML::Parse(), and ParseAndAppendUrl().
Referenced by KODI::VIDEO::CVideoInfoScanner::OnProcessSeriesFolder().
ParseFromData()
bool CScraperUrl::ParseFromData (const std::string & data)
References data(), m_data, m_parsed, m_urls, CXBMCTinyXML::Parse(), and ParseAndAppendUrl().
Referenced by CScraperUrl(), ADDON::CScraper::FindAlbum(), ADDON::CScraper::FindArtist(), ADDON::CScraper::FindMovie(), CMusicDatabase::GetAlbumFromDataset(), CMusicDatabase::GetArtistFromDataset(), Parse(), ADDON::CScraper::ResolveIDToUrl(), and TEST().
SetData()
void CScraperUrl::SetData (std::string data)
References data(), m_data, and m_parsed.
Referenced by CVideoInfoTag::Archive(), CAlbum::Load(), CArtist::Load(), and CVideoInfoTag::ParseNative().
SetId()
void CScraperUrl::SetId (std::string id) inline
References m_id.
Referenced by ADDON::CScraper::FindMovie(), ADDON::CScraper::GetEpisodeList(), ADDON::CScraper::NfoUrl(), and ADDON::CScraper::ResolveIDToUrl().
SetRelevance()
void CScraperUrl::SetRelevance (double relevance) inline
References m_relevance.
Referenced by ADDON::CScraper::FindMovie(), and ADDON::FromFileItem< CScraperUrl >().
SetTitle()
void CScraperUrl::SetTitle (std::string title) inline
References m_title.
Referenced by ADDON::CScraper::FindMovie(), ADDON::FromFileItem< CScraperUrl >(), ADDON::CScraper::GetEpisodeList(), and CVideoTagLoaderFFmpeg::LoadMKV().
SetUrls()
void CScraperUrl::SetUrls (std::vector< SUrlEntry > urls) inline
References m_urls.
Referenced by CAlbum::Load(), CArtist::Load(), and CVideoInfoTag::ParseNative().
Member Data Documentation
m_data
std::string CScraperUrl::m_data
Referenced by AddParsedUrl(), Clear(), GetData(), HasData(), Parse(), ParseAndAppendUrl(), ParseAndAppendUrlsFromEpisodeGuide(), ParseFromData(), and SetData().
m_id
std::string CScraperUrl::m_id private
Referenced by GetId(), and SetId().
m_parsed
bool CScraperUrl::m_parsed private
Referenced by AddParsedUrl(), Clear(), Parse(), ParseAndAppendUrl(), ParseAndAppendUrlsFromEpisodeGuide(), ParseFromData(), and SetData().
m_relevance
double CScraperUrl::m_relevance private
Referenced by Clear(), GetRelevance(), and SetRelevance().
m_title
std::string CScraperUrl::m_title private
Referenced by GetTitle(), and SetTitle().
m_urls
std::vector<SUrlEntry> CScraperUrl::m_urls private
Referenced by AddParsedUrl(), AppendUrl(), Clear(), GetFirstThumbUrl(), GetFirstUrlByType(), GetMaxSeasonUrl(), GetSeasonUrl(), GetThumbUrls(), GetUrls(), HasUrls(), ParseAndAppendUrl(), ParseFromData(), and SetUrls().
The documentation for this class was generated from the following files:
ScraperUrl.h
ScraperUrl.cpp