Kodi Documentation: CCoreAudioStream Class Reference
CCoreAudioStream Class Reference
#include <CoreAudioStream.h>
Public Member Functions
CCoreAudioStream ()
virtual ~CCoreAudioStream ()
bool Open (AudioStreamID streamId)
void Close (bool restore=true)
AudioStreamID GetId () const
UInt32 GetDirection ()
UInt32 GetNumLatencyFrames ()
bool GetVirtualFormat (AudioStreamBasicDescription *pDesc)
bool GetPhysicalFormat (AudioStreamBasicDescription *pDesc)
bool SetVirtualFormat (AudioStreamBasicDescription *pDesc)
bool SetPhysicalFormat (AudioStreamBasicDescription *pDesc)
bool GetAvailableVirtualFormats (StreamFormatList *pList)
bool GetAvailablePhysicalFormats (StreamFormatList *pList)
Static Public Member Functions
static UInt32 GetTerminalType (AudioStreamID id)
static bool GetAvailableVirtualFormats (AudioStreamID id, StreamFormatList *pList)
static bool GetAvailablePhysicalFormats (AudioStreamID id, StreamFormatList *pList)
static bool IsDigitalOutput (AudioStreamID id)
static bool GetStartingChannelInDevice (AudioStreamID id, UInt32 &startingChannel)
Static Protected Member Functions
static OSStatus HardwareStreamListener (AudioObjectID inObjectID, UInt32 inNumberAddresses, const AudioObjectPropertyAddress inAddresses[], void *inClientData)
Protected Attributes
CEvent m_virtual_format_event
CEvent m_physical_format_event
AudioStreamID m_StreamId = 0
AudioStreamBasicDescription m_OriginalVirtualFormat
AudioStreamBasicDescription m_OriginalPhysicalFormat
Constructor & Destructor Documentation
CCoreAudioStream()
CCoreAudioStream::CCoreAudioStream ()
References m_OriginalPhysicalFormat, and m_OriginalVirtualFormat.
~CCoreAudioStream()
CCoreAudioStream::~CCoreAudioStream () virtual
References Close().
Member Function Documentation
Close()
void CCoreAudioStream::Close (bool restore = true)
Todo:
Should it even be possible to change both the physical and virtual formats, since the devices do it themselves?
References HardwareStreamListener(), CLog::Log(), LOGDEBUG, m_OriginalPhysicalFormat, m_OriginalVirtualFormat, m_StreamId, SetPhysicalFormat(), SetVirtualFormat(), and StreamDescriptionToString().
Referenced by CAESinkDARWINOSX::Deinitialize(), and CCoreAudioHardware::ResetStream().
GetAvailablePhysicalFormats() [1/2]
bool CCoreAudioStream::GetAvailablePhysicalFormats (AudioStreamID id, StreamFormatList * pList) static
GetAvailablePhysicalFormats() [2/2]
bool CCoreAudioStream::GetAvailablePhysicalFormats (StreamFormatList * pList)
References GetAvailablePhysicalFormats(), and m_StreamId.
Referenced by AEDeviceEnumerationOSX::Enumerate(), GetAvailablePhysicalFormats(), and CCoreAudioHardware::ResetStream().
GetAvailableVirtualFormats() [1/2]
bool CCoreAudioStream::GetAvailableVirtualFormats (AudioStreamID id, StreamFormatList * pList) static
GetAvailableVirtualFormats() [2/2]
bool CCoreAudioStream::GetAvailableVirtualFormats (StreamFormatList * pList)
References GetAvailableVirtualFormats(), and m_StreamId.
Referenced by AEDeviceEnumerationOSX::Enumerate(), and GetAvailableVirtualFormats().
GetDirection()
UInt32 CCoreAudioStream::GetDirection ()
References m_StreamId.
GetId()
AudioStreamID CCoreAudioStream::GetId () const inline
References m_StreamId.
GetNumLatencyFrames()
UInt32 CCoreAudioStream::GetNumLatencyFrames ()
References m_StreamId.
Referenced by CAESinkDARWINOSX::Initialize().
GetPhysicalFormat()
bool CCoreAudioStream::GetPhysicalFormat (AudioStreamBasicDescription * pDesc)
References m_StreamId.
Referenced by CAESinkDARWINOSX::Initialize(), CCoreAudioHardware::ResetStream(), and SetPhysicalFormat().
GetStartingChannelInDevice()
bool CCoreAudioStream::GetStartingChannelInDevice (AudioStreamID id, UInt32 & startingChannel) static
Referenced by AEDeviceEnumerationOSX::getExtraDisplayNameForStream().
GetTerminalType()
UInt32 CCoreAudioStream::GetTerminalType (AudioStreamID id) static
Referenced by IsDigitalOutput().
GetVirtualFormat()
bool CCoreAudioStream::GetVirtualFormat (AudioStreamBasicDescription * pDesc)
References m_StreamId.
Referenced by CAESinkDARWINOSX::Initialize(), and SetVirtualFormat().
HardwareStreamListener()
OSStatus CCoreAudioStream::HardwareStreamListener (AudioObjectID inObjectID, UInt32 inNumberAddresses, const AudioObjectPropertyAddress inAddresses[], void * inClientData) static protected
References CLog::Log(), LOGINFO, m_physical_format_event, m_StreamId, m_virtual_format_event, CEvent::Set(), and StreamDescriptionToString().
Referenced by Close(), and Open().
IsDigitalOutput()
bool CCoreAudioStream::IsDigitalOutput (AudioStreamID id) static
References GetTerminalType().
Open()
bool CCoreAudioStream::Open (AudioStreamID streamId)
References HardwareStreamListener(), CLog::Log(), LOGDEBUG, LOGERROR, and m_StreamId.
Referenced by CAESinkDARWINOSX::Initialize(), and CCoreAudioHardware::ResetStream().
SetPhysicalFormat()
bool CCoreAudioStream::SetPhysicalFormat (AudioStreamBasicDescription * pDesc)
References GetError(), GetPhysicalFormat(), CLog::Log(), LOGDEBUG, LOGERROR, m_OriginalPhysicalFormat, m_physical_format_event, m_StreamId, CEvent::Reset(), StreamDescriptionToString(), CCoreAudioDevice::SuppressDefaultOutputDeviceCB(), and CEvent::Wait().
Referenced by Close(), CAESinkDARWINOSX::Initialize(), and CCoreAudioHardware::ResetStream().
SetVirtualFormat()
bool CCoreAudioStream::SetVirtualFormat (AudioStreamBasicDescription * pDesc)
References GetError(), GetVirtualFormat(), CLog::Log(), LOGDEBUG, LOGERROR, m_OriginalVirtualFormat, m_StreamId, m_virtual_format_event, CEvent::Reset(), StreamDescriptionToString(), CCoreAudioDevice::SuppressDefaultOutputDeviceCB(), and CEvent::Wait().
Referenced by Close(), and CAESinkDARWINOSX::Initialize().
Member Data Documentation
m_OriginalPhysicalFormat
AudioStreamBasicDescription CCoreAudioStream::m_OriginalPhysicalFormat protected
Referenced by CCoreAudioStream(), Close(), and SetPhysicalFormat().
m_OriginalVirtualFormat
AudioStreamBasicDescription CCoreAudioStream::m_OriginalVirtualFormat protected
Referenced by CCoreAudioStream(), Close(), and SetVirtualFormat().
m_physical_format_event
CEvent CCoreAudioStream::m_physical_format_event protected
Referenced by HardwareStreamListener(), and SetPhysicalFormat().
m_StreamId
AudioStreamID CCoreAudioStream::m_StreamId = 0 protected
Referenced by Close(), GetAvailablePhysicalFormats(), GetAvailableVirtualFormats(), GetDirection(), GetId(), GetNumLatencyFrames(), GetPhysicalFormat(), GetVirtualFormat(), HardwareStreamListener(), Open(), SetPhysicalFormat(), and SetVirtualFormat().
m_virtual_format_event
CEvent CCoreAudioStream::m_virtual_format_event protected
Referenced by HardwareStreamListener(), and SetVirtualFormat().
The documentation for this class was generated from the following files:
CoreAudioStream.h
CoreAudioStream.cpp