Kodi Documentation: KODI::GAME::CGameClientTopology Class Reference
KODI::GAME::CGameClientTopology Class Reference
Games
#include <GameClientTopology.h>
Public Member Functions
CGameClientTopology ()=default
CGameClientTopology (GameClientPortVec ports, int playerLimit)
void Clear ()
int GetPlayerLimit () const
const CControllerTree & GetControllerTree () const
CControllerTree & GetControllerTree ()
Static Public Member Functions
static std::string MakeAddress (const std::string &baseAddress, const std::string &nodeId)
static std::pair< std::string, std::string > SplitAddress (const std::string &nodeAddress)
Static Private Member Functions
static CControllerTree GetControllerTree (const GameClientPortVec &ports)
static CPortNode GetPortNode (const GameClientPortPtr &port, const std::string &controllerAddress)
static CControllerNode GetControllerNode (const GameClientDevicePtr &device, const std::string &portAddress)
Private Attributes
GameClientPortVec m_ports
int m_playerLimit = -1
CControllerTree m_controllers
Constructor & Destructor Documentation
CGameClientTopology() [1/2]
KODI::GAME::CGameClientTopology::CGameClientTopology () default
CGameClientTopology() [2/2]
CGameClientTopology::CGameClientTopology (GameClientPortVec ports, int playerLimit)
Member Function Documentation
Clear()
void CGameClientTopology::Clear ()
References KODI::GAME::CControllerHub::Clear(), m_controllers, and m_ports.
GetControllerNode()
CControllerNode CGameClientTopology::GetControllerNode (const GameClientDevicePtr & device, const std::string & portAddress) static private
References GetPortNode(), MakeAddress(), KODI::GAME::CControllerNode::SetController(), KODI::GAME::CControllerNode::SetControllerAddress(), KODI::GAME::CControllerNode::SetHub(), KODI::GAME::CControllerNode::SetPortAddress(), and KODI::GAME::CControllerHub::SetPorts().
Referenced by GetPortNode().
GetControllerTree() [1/3]
CControllerTree & KODI::GAME::CGameClientTopology::GetControllerTree () inline
References m_controllers.
GetControllerTree() [2/3]
const CControllerTree & KODI::GAME::CGameClientTopology::GetControllerTree () const inline
References m_controllers.
Referenced by TEST().
GetControllerTree() [3/3]
CControllerTree CGameClientTopology::GetControllerTree (const GameClientPortVec & ports) static private
References GetPortNode(), and KODI::GAME::CControllerHub::SetPorts().
GetPlayerLimit()
int KODI::GAME::CGameClientTopology::GetPlayerLimit () const inline
References m_playerLimit.
Referenced by TEST().
GetPortNode()
CPortNode CGameClientTopology::GetPortNode (const GameClientPortPtr & port, const std::string & controllerAddress) static private
References GetControllerNode(), MakeAddress(), KODI::GAME::CPortNode::SetAddress(), KODI::GAME::CPortNode::SetCompatibleControllers(), KODI::GAME::CPortNode::SetConnected(), KODI::GAME::CPortNode::SetForceConnected(), KODI::GAME::CPortNode::SetPortID(), and KODI::GAME::CPortNode::SetPortType().
Referenced by GetControllerNode(), and GetControllerTree().
MakeAddress()
std::string CGameClientTopology::MakeAddress (const std::string & baseAddress, const std::string & nodeId) static
References CONTROLLER_ADDRESS_SEPARATOR, and ROOT_PORT_ADDRESS.
Referenced by KODI::GAME::CGameClientJoystick::GetControllerAddress(), GetControllerNode(), GetPortNode(), TEST(), TEST(), and TEST().
SplitAddress()
std::pair< std::string, std::string > CGameClientTopology::SplitAddress (const std::string & nodeAddress) static
References CONTROLLER_ADDRESS_SEPARATOR.
Referenced by KODI::GAME::CGUIGameController::SetControllerAddress(), TEST(), TEST(), TEST(), and KODI::GAME::CGUIGameController::UpdateInfo().
Member Data Documentation
m_controllers
CControllerTree KODI::GAME::CGameClientTopology::m_controllers private
Referenced by Clear(), GetControllerTree(), and GetControllerTree().
m_playerLimit
int KODI::GAME::CGameClientTopology::m_playerLimit = -1 private
Referenced by GetPlayerLimit().
m_ports
GameClientPortVec KODI::GAME::CGameClientTopology::m_ports private
Referenced by Clear().
The documentation for this class was generated from the following files:
GameClientTopology.h
GameClientTopology.cpp