Kodi Documentation: ADDON::Interface_Base Struct Reference
ADDON::Interface_Base Struct Reference
Global general Add-on to Kodi callback functions.
#include <AddonBase.h>
Static Public Member Functions
static bool InitInterface (CAddonDll *addon, AddonGlobalInterface &addonInterface, KODI_ADDON_INSTANCE_STRUCT *firstKodiInstance)
static void DeInitInterface (AddonGlobalInterface &addonInterface)
static void RegisterInterface (ADDON_GET_INTERFACE_FN fn)
static bool UpdateSettingInActiveDialog (CAddonDll *addon, AddonInstanceId instanceId, const char *id, const std::string &value)
static void addon_log_msg (const KODI_ADDON_BACKEND_HDL hdl, const int addonLogLevel, const char *strMessage)
callback functions from add-on to kodi
static char * get_type_version (const KODI_ADDON_BACKEND_HDL hdl, int type)
static char * get_addon_path (const KODI_ADDON_BACKEND_HDL hdl)
static char * get_lib_path (const KODI_ADDON_BACKEND_HDL hdl)
static char * get_user_path (const KODI_ADDON_BACKEND_HDL hdl)
static char * get_temp_path (const KODI_ADDON_BACKEND_HDL hdl)
static char * get_localized_string (const KODI_ADDON_BACKEND_HDL hdl, long label_id)
static char * get_addon_info (const KODI_ADDON_BACKEND_HDL hdl, const char *id)
static bool open_settings_dialog (const KODI_ADDON_BACKEND_HDL hdl)
static bool is_setting_using_default (const KODI_ADDON_BACKEND_HDL hdl, const char *id)
static bool get_setting_bool (const KODI_ADDON_BACKEND_HDL hdl, const char *id, bool *value)
static bool get_setting_int (const KODI_ADDON_BACKEND_HDL hdl, const char *id, int *value)
static bool get_setting_float (const KODI_ADDON_BACKEND_HDL hdl, const char *id, float *value)
static bool get_setting_string (const KODI_ADDON_BACKEND_HDL hdl, const char *id, char **value)
static bool set_setting_bool (const KODI_ADDON_BACKEND_HDL hdl, const char *id, bool value)
static bool set_setting_int (const KODI_ADDON_BACKEND_HDL hdl, const char *id, int value)
static bool set_setting_float (const KODI_ADDON_BACKEND_HDL hdl, const char *id, float value)
static bool set_setting_string (const KODI_ADDON_BACKEND_HDL hdl, const char *id, const char *value)
static void free_string (const KODI_ADDON_BACKEND_HDL hdl, char *str)
static void free_string_array (const KODI_ADDON_BACKEND_HDL hdl, char **arr, int numElements)
static void * get_interface (const KODI_ADDON_BACKEND_HDL hdl, const char *name, const char *version)
Static Public Attributes
static std::vector< ADDON_GET_INTERFACE_FN > s_registeredInterfaces
Detailed Description
Global general Add-on to Kodi callback functions.
To hold general functions not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/General.h"
Member Function Documentation
addon_log_msg()
void ADDON::Interface_Base::addon_log_msg (const KODI_ADDON_BACKEND_HDL hdl, const int addonLogLevel, const char * strMessage) static
callback functions from add-on to kodi
Addon to Kodi basic callbacks below.
Note
To add a new function use the "_" style to directly identify an add-on callback function. Everything with CamelCase is only to be used in Kodi.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
The amount of functions here are hold so minimal as possible. Only parts where needed on nearly every add-on (e.g. addon_log_msg) are to add there.
More specific parts like e.g. to open files should be added to a separate part.
References ADDON_LOG_DEBUG, ADDON_LOG_ERROR, ADDON_LOG_FATAL, ADDON_LOG_INFO, ADDON_LOG_WARNING, ADDON::CAddon::ID(), CLog::Log(), LOGDEBUG, LOGERROR, LOGFATAL, LOGINFO, LOGNONE, and LOGWARNING.
Referenced by InitInterface().
DeInitInterface()
void ADDON::Interface_Base::DeInitInterface (AddonGlobalInterface & addonInterface) static
References ADDON::Interface_AudioEngine::DeInit(), ADDON::Interface_Filesystem::DeInit(), ADDON::Interface_General::DeInit(), ADDON::Interface_GUIGeneral::DeInit(), ADDON::Interface_Network::DeInit(), AddonToKodiFuncTable_Addon::kodi_addon, AddonGlobalInterface::toAddon, and AddonGlobalInterface::toKodi.
Referenced by ADDON::CAddonDll::Destroy().
free_string()
void ADDON::Interface_Base::free_string (const KODI_ADDON_BACKEND_HDL hdl, char * str) static
Referenced by InitInterface().
free_string_array()
void ADDON::Interface_Base::free_string_array (const KODI_ADDON_BACKEND_HDL hdl, char ** arr, int numElements) static
Referenced by InitInterface().
get_addon_info()
char * ADDON::Interface_Base::get_addon_info (const KODI_ADDON_BACKEND_HDL hdl, const char * id) static
References ADDON::CAddonVersion::asString(), ADDON::CAddon::Author(), ADDON::CAddon::ChangeLog(), ADDON::CAddon::Description(), ADDON::CAddon::Disclaimer(), ADDON::CAddon::FanArt(), ADDON::CAddon::Icon(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, ADDON::CAddon::Name(), ADDON::CAddon::Path(), ADDON::CAddon::Profile(), ADDON::CAddon::Summary(), ADDON::CAddonInfo::TranslateType(), ADDON::CAddon::Type(), and ADDON::CAddon::Version().
Referenced by InitInterface().
get_addon_path()
char * ADDON::Interface_Base::get_addon_path (const KODI_ADDON_BACKEND_HDL hdl) static
References CLog::Log(), LOGERROR, ADDON::CAddon::Path(), and CSpecialProtocol::TranslatePath().
Referenced by InitInterface().
get_interface()
void * ADDON::Interface_Base::get_interface (const KODI_ADDON_BACKEND_HDL hdl, const char * name, const char * version) static
References name, and s_registeredInterfaces.
Referenced by InitInterface().
get_lib_path()
char * ADDON::Interface_Base::get_lib_path (const KODI_ADDON_BACKEND_HDL hdl) static
References ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CSpecialProtocol::TranslatePath().
Referenced by InitInterface().
get_localized_string()
char * ADDON::Interface_Base::get_localized_string (const KODI_ADDON_BACKEND_HDL hdl, long label_id) static
References g_application, g_localizeStrings, CLocalizeStrings::Get(), CLocalizeStrings::GetAddonString(), ADDON::CAddon::ID(), label, CLog::Log(), and LOGERROR.
Referenced by InitInterface().
get_setting_bool()
bool ADDON::Interface_Base::get_setting_bool (const KODI_ADDON_BACKEND_HDL hdl, const char * id, bool * value) static
References Boolean, ADDON::CAddon::GetSettings(), ADDON::CAddon::HasSettings(), CLog::Log(), LOGERROR, ADDON::CAddon::Name(), and value.
Referenced by InitInterface().
get_setting_float()
bool ADDON::Interface_Base::get_setting_float (const KODI_ADDON_BACKEND_HDL hdl, const char * id, float * value) static
References ADDON::CAddon::GetSettings(), ADDON::CAddon::HasSettings(), CLog::Log(), LOGERROR, ADDON::CAddon::Name(), Number, and value.
Referenced by InitInterface().
get_setting_int()
bool ADDON::Interface_Base::get_setting_int (const KODI_ADDON_BACKEND_HDL hdl, const char * id, int * value) static
References ADDON::CAddon::GetSettings(), ADDON::CAddon::HasSettings(), Integer, CLog::Log(), LOGERROR, ADDON::CAddon::Name(), Number, and value.
Referenced by InitInterface().
get_setting_string()
bool ADDON::Interface_Base::get_setting_string (const KODI_ADDON_BACKEND_HDL hdl, const char * id, char ** value) static
References ADDON::CAddon::GetSettings(), GetValue(), ADDON::CAddon::HasSettings(), CLog::Log(), LOGERROR, ADDON::CAddon::Name(), String, and value.
Referenced by InitInterface().
get_temp_path()
char * ADDON::Interface_Base::get_temp_path (const KODI_ADDON_BACKEND_HDL hdl) static
References URIUtils::AddFileToFolder(), XFILE::CDirectory::Create(), CServiceBroker::GetAddonMgr(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CSpecialProtocol::TranslatePath().
Referenced by InitInterface().
get_type_version()
char * ADDON::Interface_Base::get_type_version (const KODI_ADDON_BACKEND_HDL hdl, int type) static
References kodi::addon::GetTypeVersion().
Referenced by InitInterface().
get_user_path()
char * ADDON::Interface_Base::get_user_path (const KODI_ADDON_BACKEND_HDL hdl) static
References CLog::Log(), LOGERROR, ADDON::CAddon::Profile(), and CSpecialProtocol::TranslatePath().
Referenced by InitInterface().
InitInterface()
bool ADDON::Interface_Base::InitInterface (CAddonDll * addon, AddonGlobalInterface & addonInterface, KODI_ADDON_INSTANCE_STRUCT * firstKodiInstance) static
References addon_log_msg(), AddonToKodiFuncTable_Addon::addon_log_msg, AddonGlobalInterface::addonBase, AddonGlobalInterface::firstKodiInstance, free_string(), AddonToKodiFuncTable_Addon::free_string, free_string_array(), AddonToKodiFuncTable_Addon::free_string_array, get_addon_info(), AddonToKodiFuncTable_kodi_addon::get_addon_info, get_addon_path(), AddonToKodiFuncTable_kodi_addon::get_addon_path, get_interface(), AddonToKodiFuncTable_kodi_addon::get_interface, get_lib_path(), AddonToKodiFuncTable_kodi_addon::get_lib_path, get_localized_string(), AddonToKodiFuncTable_kodi_addon::get_localized_string, get_setting_bool(), AddonToKodiFuncTable_kodi_addon::get_setting_bool, get_setting_float(), AddonToKodiFuncTable_kodi_addon::get_setting_float, get_setting_int(), AddonToKodiFuncTable_kodi_addon::get_setting_int, get_setting_string(), AddonToKodiFuncTable_kodi_addon::get_setting_string, get_temp_path(), AddonToKodiFuncTable_kodi_addon::get_temp_path, get_type_version(), AddonToKodiFuncTable_kodi_addon::get_type_version, get_user_path(), AddonToKodiFuncTable_kodi_addon::get_user_path, AddonGlobalInterface::globalSingleInstance, ADDON::Interface_AudioEngine::Init(), ADDON::Interface_Filesystem::Init(), ADDON::Interface_General::Init(), ADDON::Interface_GUIGeneral::Init(), ADDON::Interface_Network::Init(), is_setting_using_default(), AddonToKodiFuncTable_kodi_addon::is_setting_using_default, AddonToKodiFuncTable_Addon::kodi_addon, AddonToKodiFuncTable_Addon::kodiBase, open_settings_dialog(), AddonToKodiFuncTable_kodi_addon::open_settings_dialog, set_setting_bool(), AddonToKodiFuncTable_kodi_addon::set_setting_bool, set_setting_float(), AddonToKodiFuncTable_kodi_addon::set_setting_float, set_setting_int(), AddonToKodiFuncTable_kodi_addon::set_setting_int, set_setting_string(), AddonToKodiFuncTable_kodi_addon::set_setting_string, AddonGlobalInterface::toAddon, and AddonGlobalInterface::toKodi.
Referenced by ADDON::CAddonDll::Create().
is_setting_using_default()
bool ADDON::Interface_Base::is_setting_using_default (const KODI_ADDON_BACKEND_HDL hdl, const char * id) static
References ADDON::CAddon::GetSettings(), ADDON::CAddon::HasSettings(), CLog::Log(), LOGERROR, and ADDON::CAddon::Name().
Referenced by InitInterface().
open_settings_dialog()
bool ADDON::Interface_Base::open_settings_dialog (const KODI_ADDON_BACKEND_HDL hdl) static
References ADDON::CHOICE_YES, CServiceBroker::GetAddonMgr(), ADDON::CAddon::ID(), CLog::Log(), LOGERROR, and CGUIDialogAddonSettings::ShowForAddon().
Referenced by InitInterface().
RegisterInterface()
void ADDON::Interface_Base::RegisterInterface (ADDON_GET_INTERFACE_FN fn) static
References s_registeredInterfaces.
Referenced by ADDON::Interface_Android::Register().
set_setting_bool()
bool ADDON::Interface_Base::set_setting_bool (const KODI_ADDON_BACKEND_HDL hdl, const char * id, bool value) static
References ADDON::ADDON_SETTINGS_ID, CLog::Log(), LOGERROR, ADDON::CAddonDll::SaveSettings(), ADDON::CAddon::UpdateSettingBool(), UpdateSettingInActiveDialog(), and value.
Referenced by InitInterface().
set_setting_float()
bool ADDON::Interface_Base::set_setting_float (const KODI_ADDON_BACKEND_HDL hdl, const char * id, float value) static
References ADDON::ADDON_SETTINGS_ID, CLog::Log(), LOGERROR, ADDON::CAddonDll::SaveSettings(), UpdateSettingInActiveDialog(), ADDON::CAddon::UpdateSettingNumber(), and value.
Referenced by InitInterface().
set_setting_int()
bool ADDON::Interface_Base::set_setting_int (const KODI_ADDON_BACKEND_HDL hdl, const char * id, int value) static
References ADDON::ADDON_SETTINGS_ID, CLog::Log(), LOGERROR, ADDON::CAddonDll::SaveSettings(), UpdateSettingInActiveDialog(), ADDON::CAddon::UpdateSettingInt(), and value.
Referenced by InitInterface().
set_setting_string()
bool ADDON::Interface_Base::set_setting_string (const KODI_ADDON_BACKEND_HDL hdl, const char * id, const char * value) static
References ADDON::ADDON_SETTINGS_ID, CLog::Log(), LOGERROR, ADDON::CAddonDll::SaveSettings(), UpdateSettingInActiveDialog(), ADDON::CAddon::UpdateSettingString(), and value.
Referenced by InitInterface().
UpdateSettingInActiveDialog()
bool ADDON::Interface_Base::UpdateSettingInActiveDialog (CAddonDll * addon, AddonInstanceId instanceId, const char * id, const std::string & value) static
References CGUIDialogAddonSettings::GetCurrentAddonID(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_SETTING_UPDATED, ADDON::CAddon::ID(), CGUIMessage::SetParam1(), CGUIMessage::SetStringParams(), value, and WINDOW_DIALOG_ADDON_SETTINGS.
Referenced by ADDON::IAddonInstanceHandler::set_instance_setting_bool(), ADDON::IAddonInstanceHandler::set_instance_setting_float(), ADDON::IAddonInstanceHandler::set_instance_setting_int(), ADDON::IAddonInstanceHandler::set_instance_setting_string(), set_setting_bool(), set_setting_float(), set_setting_int(), and set_setting_string().
Member Data Documentation
s_registeredInterfaces
std::vector< ADDON_GET_INTERFACE_FN > ADDON::Interface_Base::s_registeredInterfaces static
Referenced by get_interface(), and RegisterInterface().
The documentation for this struct was generated from the following files:
interfaces/AddonBase.h
AddonBase.cpp