Kodi Documentation: CGUIDialogCache Class Reference
CGUIDialogCache Class Reference
#include <GUIDialogCache.h>
Public Member Functions
CGUIDialogCache (std::chrono::milliseconds delay=std::chrono::milliseconds(100), const std::string &strHeader="", const std::string &strMsg="")
~CGUIDialogCache () override
void SetHeader (const std::string &strHeader)
void SetHeader (int nHeader)
void SetMessage (const std::string &strMessage)
bool IsCanceled () const
void ShowProgressBar (bool bOnOff)
void SetPercentage (int iPercentage)
void Close (bool bForceClose=false)
void Process () override
bool OnFileCallback (void *pContext, int ipercent, float avgSpeed) override
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Public Member Functions inherited from XFILE::IFileCallback
virtual ~IFileCallback ()=default
Protected Member Functions
void OpenDialog ()
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes
XbmcThreads::EndTime m_endtime
CGUIDialogProgress * m_pDlg
std::string m_strHeader
std::string m_strLinePrev
std::string m_strLinePrev2
bool bSentCancel
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Constructor & Destructor Documentation
CGUIDialogCache()
CGUIDialogCache::CGUIDialogCache (std::chrono::milliseconds delay = std::chrono::milliseconds(100), const std::string & strHeader = "", const std::string & strMsg = "")
References bSentCancel, CThread::Create(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CGUIDialog::IsDialogRunning(), m_endtime, m_pDlg, OpenDialog(), and WINDOW_DIALOG_PROGRESS.
~CGUIDialogCache()
CGUIDialogCache::~CGUIDialogCache () override
References CGUIWindow::Close(), CGUIDialog::IsDialogRunning(), and m_pDlg.
Member Function Documentation
Close()
void CGUIDialogCache::Close (bool bForceClose = false)
References bSentCancel, CServiceBroker::GetAppMessenger(), CGUIDialog::IsDialogRunning(), CThread::m_bStop, m_pDlg, and TMSG_GUI_WINDOW_CLOSE.
Referenced by CApplication::PlayMedia().
IsCanceled()
bool CGUIDialogCache::IsCanceled () const
References CGUIDialogProgress::IsCanceled(), CGUIDialog::IsDialogRunning(), and m_pDlg.
Referenced by OnFileCallback(), and CApplication::PlayMedia().
OnFileCallback()
bool CGUIDialogCache::OnFileCallback (void * pContext, int ipercent, float avgSpeed) override virtual
Implements XFILE::IFileCallback.
References IsCanceled(), m_pDlg, CGUIDialogProgress::SetPercentage(), and CGUIDialogProgress::ShowProgressBar().
OpenDialog()
void CGUIDialogCache::OpenDialog () protected
References bSentCancel, m_pDlg, m_strHeader, m_strLinePrev, CGUIDialogProgress::Open(), CGUIDialogBoxBase::SetHeading(), and CGUIDialogBoxBase::SetLine().
Referenced by CGUIDialogCache(), and Process().
Process()
void CGUIDialogCache::Process (void) override virtual
Reimplemented from CThread.
References bSentCancel, CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), CGUIDialogProgress::IsCanceled(), CGUIDialog::IsDialogRunning(), CLog::Log(), LOGERROR, CThread::m_bStop, m_endtime, m_pDlg, OpenDialog(), CGUIDialogProgress::Progress(), CThread::Sleep(), and WINDOW_DIALOG_YES_NO.
SetHeader() [1/2]
void CGUIDialogCache::SetHeader (const std::string & strHeader)
References m_strHeader.
Referenced by SetHeader().
SetHeader() [2/2]
void CGUIDialogCache::SetHeader (int nHeader)
References g_localizeStrings, CLocalizeStrings::Get(), and SetHeader().
SetMessage()
void CGUIDialogCache::SetMessage (const std::string & strMessage)
References m_pDlg, m_strLinePrev, m_strLinePrev2, and CGUIDialogBoxBase::SetLine().
SetPercentage()
void CGUIDialogCache::SetPercentage (int iPercentage)
References m_pDlg, and CGUIDialogProgress::SetPercentage().
ShowProgressBar()
void CGUIDialogCache::ShowProgressBar (bool bOnOff)
References m_pDlg, and CGUIDialogProgress::ShowProgressBar().
Member Data Documentation
bSentCancel
bool CGUIDialogCache::bSentCancel protected
Referenced by CGUIDialogCache(), Close(), OpenDialog(), and Process().
m_endtime
XbmcThreads::EndTime CGUIDialogCache::m_endtime protected
Referenced by CGUIDialogCache(), and Process().
m_pDlg
CGUIDialogProgress* CGUIDialogCache::m_pDlg protected
Referenced by CGUIDialogCache(), Close(), IsCanceled(), OnFileCallback(), OpenDialog(), Process(), SetMessage(), SetPercentage(), ShowProgressBar(), and ~CGUIDialogCache().
m_strHeader
std::string CGUIDialogCache::m_strHeader protected
Referenced by OpenDialog(), and SetHeader().
m_strLinePrev
std::string CGUIDialogCache::m_strLinePrev protected
Referenced by OpenDialog(), and SetMessage().
m_strLinePrev2
std::string CGUIDialogCache::m_strLinePrev2 protected
Referenced by SetMessage().
The documentation for this class was generated from the following files:
GUIDialogCache.h
GUIDialogCache.cpp