Kodi Documentation: CTextureDatabase Class Reference
CTextureDatabase Class Reference
#include <TextureDatabase.h>
Public Member Functions
CTextureDatabase ()
~CTextureDatabase () override
bool Open () override
bool GetCachedTexture (const std::string &originalURL, CTextureDetails &details)
bool AddCachedTexture (const std::string &originalURL, const CTextureDetails &details)
bool SetCachedTextureValid (const std::string &originalURL, bool updateable)
bool ClearCachedTexture (const std::string &originalURL, std::string &cacheFile)
bool ClearCachedTexture (int textureID, std::string &cacheFile)
bool IncrementUseCount (const CTextureDetails &details)
bool InvalidateCachedTexture (const std::string &originalURL)
Invalidate a previously cached texture Invalidates the texture hash, and sets the texture update time to the current time so that next texture load it will be re-cached.
std::string GetTextureForPath (const std::string &url, const std::string &type)
Get a texture associated with the given path Used for retrieval of previously discovered images to save stat() on the filesystem all the time.
void SetTextureForPath (const std::string &url, const std::string &type, const std::string &texture)
Set a texture associated with the given path Used for setting of previously discovered images to save stat() on the filesystem all the time. Should be used to set the actual image path, not the cached image path (the image will be cached at load time.)
void ClearTextureForPath (const std::string &url, const std::string &type)
Clear a texture associated with the given path.
bool GetTextures (CVariant &items, const Filter &filter)
std::vector< std::string > GetOldestCachedImages (unsigned int maxImages) const
Get a list of the oldest cached images eligible for cleaning.
bool SetKeepCachedImages (const std::vector< std::string > &imagesToKeep)
Set a list of images to be kept. Used to clean the image cache.
CDatabaseQueryRule * CreateRule () const override
CDatabaseQueryRuleCombination * CreateCombination () const override
Public Member Functions inherited from CDatabase
CDatabase ()
virtual ~CDatabase (void)
bool IsOpen ()
virtual void Close ()
bool Compress (bool bForce=true)
void Interrupt ()
bool Open (const DatabaseSettings &db)
void BeginTransaction ()
virtual bool CommitTransaction ()
void RollbackTransaction ()
void CopyDB (const std::string &latestDb)
void DropAnalytics ()
std::string PrepareSQL (std::string strStmt,...) const
std::string GetSingleValue (const std::string &strTable, const std::string &strColumn, const std::string &strWhereClause=std::string(), const std::string &strOrderBy=std::string()) const
Get a single value from a table.
std::string GetSingleValue (const std::string &query) const
std::string GetSingleValue (const std::string &query, const std::unique_ptr< dbiplus::Dataset > &ds) const
Get a single value from a query on a dataset.
int GetSingleValueInt (const std::string &strTable, const std::string &strColumn, const std::string &strWhereClause=std::string(), const std::string &strOrderBy=std::string()) const
Get a single integer value from a table.
int GetSingleValueInt (const std::string &query) const
int GetSingleValueInt (const std::string &query, const std::unique_ptr< dbiplus::Dataset > &ds) const
Get a single integer value from a query on a dataset.
bool DeleteValues (const std::string &strTable, const Filter &filter=Filter())
Delete values from a table.
bool ExecuteQuery (const std::string &strQuery)
Execute a query that does not return any result. Note that if BeginMultipleExecute() has been called, the query will be queued until CommitMultipleExecute() is called.
bool ResultQuery (const std::string &strQuery) const
Execute a query that returns a result.
bool BeginMultipleExecute ()
Start a multiple execution queue. Any ExecuteQuery() function following this call will be queued rather than executed until CommitMultipleExecute() is performed. NOTE: Queries that rely on any queued execute query will not function as expected during this period!
bool CommitMultipleExecute ()
Commit the multiple execution queue to the database. Queries are performed within a transaction, and the transaction is rolled back should any one query fail.
bool QueueInsertQuery (const std::string &strQuery)
Put an INSERT or REPLACE query in the queue.
bool CommitInsertQueries ()
Commit all queries in the queue.
size_t GetInsertQueriesCount ()
Get the number of INSERT queries in the queue.
bool QueueDeleteQuery (const std::string &strQuery)
Put a DELETE query in the queue.
bool CommitDeleteQueries ()
Commit all queued DELETE queries.
size_t GetDeleteQueriesCount ()
Get the number of DELETE queries in the queue.
virtual bool GetFilter (CDbUrl &dbUrl, Filter &filter, SortDescription &sorting)
virtual bool BuildSQL (const std::string &strBaseDir, const std::string &strQuery, Filter &filter, std::string &strSQL, CDbUrl &dbUrl)
virtual bool BuildSQL (const std::string &strBaseDir, const std::string &strQuery, Filter &filter, std::string &strSQL, CDbUrl &dbUrl, SortDescription &sorting)
bool Connect (const std::string &dbName, const DatabaseSettings &db, bool create)
Public Member Functions inherited from IDatabaseQueryRuleFactory
virtual ~IDatabaseQueryRuleFactory ()=default
Protected Member Functions
unsigned int GetURLHash (const std::string &url) const
retrieve a hash for the given url Computes a hash of the current url to use for lookups in the database
void CreateTables () override
void CreateAnalytics () override
void UpdateTables (int version) override
int GetSchemaVersion () const override
const char * GetBaseDBName () const override
Protected Member Functions inherited from CDatabase
void Split (const std::string &strFileNameAndPath, std::string &strPath, std::string &strFileName)
bool CreateDatabase ()
Create database tables and analytics as needed. Calls CreateTables() and CreateAnalytics() on child classes.
virtual int GetMinSchemaVersion () const
int GetDBVersion ()
bool BuildSQL (const std::string &strQuery, const Filter &filter, std::string &strSQL) const
Additional Inherited Members
Protected Attributes inherited from CDatabase
bool m_sqlite
whether we use sqlite (defaults to true)
std::unique_ptr< dbiplus::Database > m_pDB
std::unique_ptr< dbiplus::Dataset > m_pDS
std::unique_ptr< dbiplus::Dataset > m_pDS2
const CProfileManager & m_profileManager
Constructor & Destructor Documentation
CTextureDatabase()
CTextureDatabase::CTextureDatabase () default
~CTextureDatabase()
CTextureDatabase::~CTextureDatabase () override default
Member Function Documentation
AddCachedTexture()
bool CTextureDatabase::AddCachedTexture (const std::string & originalURL, const CTextureDetails & details)
References CDatabase::BeginTransaction(), CDatabase::CommitTransaction(), CTextureDetails::file, CDateTime::GetAsDBDateTime(), CDateTime::GetCurrentDateTime(), CTextureDetails::hash, CTextureDetails::height, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), CDatabase::RollbackTransaction(), CTextureDetails::updateable, and CTextureDetails::width.
Referenced by CTextureCache::AddCachedTexture().
ClearCachedTexture() [1/2]
bool CTextureDatabase::ClearCachedTexture (const std::string & originalURL, std::string & cacheFile)
References ClearCachedTexture(), CDatabase::GetSingleValue(), and CDatabase::PrepareSQL().
Referenced by ClearCachedTexture(), CTextureCache::ClearCachedTexture(), and CTextureCache::ClearCachedTexture().
ClearCachedTexture() [2/2]
bool CTextureDatabase::ClearCachedTexture (int textureID, std::string & cacheFile)
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
ClearTextureForPath()
void CTextureDatabase::ClearTextureForPath (const std::string & url, const std::string & type)
Clear a texture associated with the given path.
Parameters
url path that was used to find the texture
type type of image to associate
texture URL of the texture to associate with the path
See also
GetTextureForPath, SetTextureForPath
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by PVR::CPVRCachedImages::Cleanup(), PVR::CPVRThumbLoader::ClearCachedImage(), and CPictureThumbLoader::LoadItemCached().
CreateAnalytics()
void CTextureDatabase::CreateAnalytics () override protected virtual
Todo:
Should the path index be a covering index? (we need only retrieve texture)
Implements CDatabase.
References CLog::Log(), LOGINFO, and CDatabase::m_pDS.
CreateCombination()
CDatabaseQueryRuleCombination * CTextureDatabase::CreateCombination () const override virtual
Implements IDatabaseQueryRuleFactory.
CreateRule()
CDatabaseQueryRule * CTextureDatabase::CreateRule () const override virtual
Implements IDatabaseQueryRuleFactory.
CreateTables()
void CTextureDatabase::CreateTables () override protected virtual
Implements CDatabase.
References CLog::Log(), LOGINFO, and CDatabase::m_pDS.
GetBaseDBName()
const char * CTextureDatabase::GetBaseDBName () const inline override protected virtual
Implements CDatabase.
GetCachedTexture()
bool CTextureDatabase::GetCachedTexture (const std::string & originalURL, CTextureDetails & details)
References CTextureDetails::file, CDateTime::GetCurrentDateTime(), CTextureDetails::hash, CTextureDetails::height, CTextureDetails::id, CDateTime::IsValid(), CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), CDateTime::SetFromDBDateTime(), and CTextureDetails::width.
Referenced by CTextureCache::GetCachedTexture().
GetOldestCachedImages()
std::vector< std::string > CTextureDatabase::GetOldestCachedImages (unsigned int maxImages) const
Get a list of the oldest cached images eligible for cleaning.
Parameters
maxImages the maximum number of images to return
Returns
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
GetSchemaVersion()
int CTextureDatabase::GetSchemaVersion () const inline override protected virtual
Implements CDatabase.
GetTextureForPath()
std::string CTextureDatabase::GetTextureForPath (const std::string & url, const std::string & type)
Get a texture associated with the given path Used for retrieval of previously discovered images to save stat() on the filesystem all the time.
Parameters
url path that may be associated with a texture
type type of image to look for
Returns
URL of the texture associated with the given path
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CThumbLoader::GetCachedImage().
GetTextures()
bool CTextureDatabase::GetTextures (CVariant & items, const Filter & filter)
References CDatabase::BuildSQL(), CDatabase::Filter::fields, CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, CDatabase::PrepareSQL(), CVariant::push_back(), CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
Referenced by PVR::CPVRCachedImages::Cleanup(), and JSONRPC::CTextureOperations::GetTextures().
GetURLHash()
unsigned int CTextureDatabase::GetURLHash (const std::string & url) const protected
retrieve a hash for the given url Computes a hash of the current url to use for lookups in the database
Parameters
url url to hash
Returns
a hash for this url
IncrementUseCount()
bool CTextureDatabase::IncrementUseCount (const CTextureDetails & details)
References CDatabase::ExecuteQuery(), CTextureDetails::height, CTextureDetails::id, CDatabase::PrepareSQL(), and CTextureDetails::width.
Referenced by CTextureUseCountJob::DoWork().
InvalidateCachedTexture()
bool CTextureDatabase::InvalidateCachedTexture (const std::string & originalURL)
Invalidate a previously cached texture Invalidates the texture hash, and sets the texture update time to the current time so that next texture load it will be re-cached.
Parameters
url texture path
References CDatabase::ExecuteQuery(), CDateTime::GetCurrentDateTime(), and CDatabase::PrepareSQL().
Referenced by ADDON::CRepositoryUpdateJob::DoWork(), and CVideoLibraryRefreshingJob::Work().
Open()
bool CTextureDatabase::Open () override virtual
Reimplemented from CDatabase.
References CDatabase::Open().
Referenced by PVR::CPVRCachedImages::Cleanup(), PVR::CPVRThumbLoader::ClearCachedImage(), ADDON::CRepositoryUpdateJob::DoWork(), CTextureUseCountJob::DoWork(), CThumbLoader::GetCachedImage(), JSONRPC::CTextureOperations::GetTextures(), CTextureCache::Initialize(), CPictureThumbLoader::LoadItemCached(), CGUIDialogContextMenu::OnContextButton(), CThumbLoader::OnLoaderStart(), CPictureThumbLoader::ProcessFoldersAndArchives(), CThumbLoader::SetCachedImage(), and CVideoLibraryRefreshingJob::Work().
SetCachedTextureValid()
bool CTextureDatabase::SetCachedTextureValid (const std::string & originalURL, bool updateable)
References CDatabase::ExecuteQuery(), CDateTime::GetAsDBDateTime(), CDateTime::GetCurrentDateTime(), and CDatabase::PrepareSQL().
Referenced by CTextureCache::SetCachedTextureValid().
SetKeepCachedImages()
bool CTextureDatabase::SetKeepCachedImages (const std::vector< std::string > & imagesToKeep)
Set a list of images to be kept. Used to clean the image cache.
Parameters
imagesToKeep
Returns
References CDatabase::ExecuteQuery(), and CDatabase::PrepareSQL().
SetTextureForPath()
void CTextureDatabase::SetTextureForPath (const std::string & url, const std::string & type, const std::string & texture)
Set a texture associated with the given path Used for setting of previously discovered images to save stat() on the filesystem all the time. Should be used to set the actual image path, not the cached image path (the image will be cached at load time.)
Parameters
url path that was used to find the texture
type type of image to associate
texture URL of the texture to associate with the path
References CLog::Log(), LOGERROR, CDatabase::m_pDB, CDatabase::m_pDS, and CDatabase::PrepareSQL().
Referenced by CGUIDialogContextMenu::OnContextButton(), CPictureThumbLoader::ProcessFoldersAndArchives(), and CThumbLoader::SetCachedImage().
UpdateTables()
void CTextureDatabase::UpdateTables (int version) override protected virtual
Reimplemented from CDatabase.
References CURL::GetHostName(), CDatabase::m_pDS, CDatabase::m_pDS2, and CDatabase::PrepareSQL().
The documentation for this class was generated from the following files:
TextureDatabase.h
TextureDatabase.cpp