Kodi Documentation: CONTEXTMENU::CFavouriteContextMenuAction Class Reference
CONTEXTMENU::CFavouriteContextMenuAction Class Reference abstract
#include <ContextMenus.h>
Public Member Functions
CFavouriteContextMenuAction (uint32_t label)
bool IsVisible (const CFileItem &item) const override
bool Execute (const std::shared_ptr< CFileItem > &item) const override
Public Member Functions inherited from CStaticContextMenuAction
CStaticContextMenuAction (uint32_t label)
std::string GetLabel (const CFileItem &item) const final
bool IsGroup () const final
Public Member Functions inherited from IContextMenuItem
virtual ~IContextMenuItem ()=default
virtual bool HasParent () const
Protected Member Functions
~CFavouriteContextMenuAction () override=default
virtual bool DoExecute (CFileItemList &items, const std::shared_ptr< CFileItem > &item) const =0
Constructor & Destructor Documentation
CFavouriteContextMenuAction()
CONTEXTMENU::CFavouriteContextMenuAction::CFavouriteContextMenuAction (uint32_t label) inline explicit
~CFavouriteContextMenuAction()
CONTEXTMENU::CFavouriteContextMenuAction::~CFavouriteContextMenuAction () override protected default
Member Function Documentation
DoExecute()
virtual bool CONTEXTMENU::CFavouriteContextMenuAction::DoExecute (CFileItemList & items, const std::shared_ptr< CFileItem > & item) const protected pure virtual
Implemented in CONTEXTMENU::CMoveUpFavourite, CONTEXTMENU::CMoveDownFavourite, CONTEXTMENU::CRemoveFavourite, CONTEXTMENU::CRenameFavourite, and CONTEXTMENU::CChooseThumbnailForFavourite.
Referenced by Execute().
Execute()
bool CFavouriteContextMenuAction::Execute (const std::shared_ptr< CFileItem > & item) const override virtual
Implements IContextMenuItem.
References CFileItemList::cbegin(), CFileItemList::cend(), DoExecute(), CFavouritesService::GetAll(), CServiceBroker::GetFavouritesService(), and CFavouritesService::Save().
IsVisible()
bool CFavouriteContextMenuAction::IsVisible (const CFileItem & item) const override virtual
Implements IContextMenuItem.
Reimplemented in CONTEXTMENU::CMoveUpFavourite, and CONTEXTMENU::CMoveDownFavourite.
References CFileItem::GetPath(), and URIUtils::IsProtocol().
Referenced by CONTEXTMENU::CMoveUpFavourite::IsVisible(), and CONTEXTMENU::CMoveDownFavourite::IsVisible().
The documentation for this class was generated from the following files:
favourites/ContextMenus.h
favourites/ContextMenus.cpp