Kodi Documentation: PVR::CPVRClientUID Class Reference
PVR::CPVRClientUID Class Reference final
#include <PVRClientUID.h>
Public Member Functions
CPVRClientUID (const std::string &addonID, ADDON::AddonInstanceId instanceID)
virtual ~CPVRClientUID ()=default
int GetUID () const
Return the numeric UID.
int GetLegacyUID () const
Return the numeric legacy UID (compatibility/migration purposes only).
Private Member Functions
CPVRClientUID ()=delete
Private Attributes
std::string m_addonID
ADDON::AddonInstanceId m_instanceID {ADDON::ADDON_SINGLETON_INSTANCE_ID}
bool m_uidCreated {false}
int m_uid {0}
Constructor & Destructor Documentation
CPVRClientUID() [1/2]
PVR::CPVRClientUID::CPVRClientUID (const std::string & addonID, ADDON::AddonInstanceId instanceID) inline
~CPVRClientUID()
virtual PVR::CPVRClientUID::~CPVRClientUID () virtual default
CPVRClientUID() [2/2]
PVR::CPVRClientUID::CPVRClientUID () private delete
Member Function Documentation
GetLegacyUID()
int CPVRClientUID::GetLegacyUID () const
Return the numeric legacy UID (compatibility/migration purposes only).
Returns
The numeric legacy UID.
References ADDON::ADDON_FIRST_INSTANCE_ID, m_addonID, and m_instanceID.
Referenced by PVR::CPVRDatabase::FixupClientIDs().
GetUID()
int CPVRClientUID::GetUID () const
Return the numeric UID.
Returns
The numeric UID, or PVR_CLIENT_INVALID_UID on error.
References PVR::CPVRDatabase::GetClientID(), LOGERROR, m_addonID, m_instanceID, m_uid, m_uidCreated, PVR::CPVRDatabase::Open(), and PVR::PVR_CLIENT_INVALID_UID.
Referenced by PVR::CPVRClients::GetCallableClients(), PVR::CPVRChannelGroups::GetChannelGroupMemberByPath(), PVR::CPVRClients::GetClientProviderInfos(), and PVR::CPVRClients::UpdateClients().
Member Data Documentation
m_addonID
std::string PVR::CPVRClientUID::m_addonID private
Referenced by GetLegacyUID(), and GetUID().
m_instanceID
ADDON::AddonInstanceId PVR::CPVRClientUID::m_instanceID {ADDON::ADDON_SINGLETON_INSTANCE_ID} private
Referenced by GetLegacyUID(), and GetUID().
m_uid
int PVR::CPVRClientUID::m_uid {0} mutable private
Referenced by GetUID().
m_uidCreated
bool PVR::CPVRClientUID::m_uidCreated {false} mutable private
Referenced by GetUID().
The documentation for this class was generated from the following files:
PVRClientUID.h
PVRClientUID.cpp