Kodi Documentation: TestUtil.cpp File Reference
TestUtil.cpp File Reference
#include "Util.h"
#include <gtest/gtest.h>
Classes
struct TestUtilCleanStringData
class TestUtilCleanString
struct TestUtilSplitParamsData
class TestUtilSplitParams
Functions
TEST (TestUtil, GetQualifiedFilename)
TEST (TestUtil, MakeLegalPath)
TEST (TestUtil, MakeShortenPath)
TEST (TestUtil, ValidatePath)
std::ostream & operator<< (std::ostream &os, const TestUtilCleanStringData &rhs)
TEST_P (TestUtilCleanString, GetFilenameIdentifier)
TEST_P (TestUtilCleanString, CleanString)
INSTANTIATE_TEST_SUITE_P (URL, TestUtilCleanString, ValuesIn(values))
std::ostream & operator<< (std::ostream &os, const TestUtilSplitParamsData &rhs)
TEST_P (TestUtilSplitParams, SplitParams)
Variables
const TestUtilCleanStringData values []
Function Documentation
INSTANTIATE_TEST_SUITE_P()
INSTANTIATE_TEST_SUITE_P (URL , TestUtilCleanString , ValuesIn(values))
operator<<() [1/2]
std::ostream & operator<< (std::ostream & os, const TestUtilCleanStringData & rhs)
References TestUtilCleanStringData::expTitle, TestUtilCleanStringData::expTitleYear, TestUtilCleanStringData::expYear, TestUtilCleanStringData::first, and TestUtilCleanStringData::input.
operator<<() [2/2]
std::ostream & operator<< (std::ostream & os, const TestUtilSplitParamsData & rhs)
References TestUtilSplitParamsData::expectedResult, and TestUtilSplitParamsData::input.
TEST() [1/4]
TEST (TestUtil , GetQualifiedFilename)
References EXPECT_EQ(), and CUtil::GetQualifiedFilename().
TEST() [2/4]
TEST (TestUtil , MakeLegalPath)
References EXPECT_EQ(), and CUtil::MakeLegalPath().
TEST() [3/4]
TEST (TestUtil , MakeShortenPath)
References EXPECT_EQ(), and CUtil::MakeShortenPath().
TEST() [4/4]
TEST (TestUtil , ValidatePath)
References EXPECT_EQ(), and CUtil::ValidatePath().
TEST_P() [1/3]
TEST_P (TestUtilCleanString , CleanString)
References CUtil::CleanString(), and EXPECT_EQ().
TEST_P() [2/3]
TEST_P (TestUtilCleanString , GetFilenameIdentifier)
References EXPECT_EQ(), and CUtil::GetFilenameIdentifier().
TEST_P() [3/3]
TEST_P (TestUtilSplitParams , SplitParams)
References EXPECT_EQ(), and CUtil::SplitParams().
Variable Documentation
values
const TestUtilCleanStringData values[]
Initial value:
= {
    {"Some.BDRemux.mkv", true, "Some", "Some", ""},
    {"SomeMovie.2018.UHD.BluRay.2160p.HEVC.TrueHD.Atmos.7.1-BeyondHD", true, "SomeMovie",
     "SomeMovie (2018)", "2018"},
    {"SOME_UHD_HDR10+_DV_2022_remux_dub atmos_soundmovie", true, "SOME", "SOME (2022)", "2022"},
    {"Some Movie.Some Story.2013.BDRemux.1080p", true, "Some Movie.Some Story",
     "Some Movie.Some Story (2013)", "2013"},
    {"Movie.Some.Story.2017.2160p.BDRemux.IMAX.HDR.DV.IVA(ENG.RUS).ExKinoRay", true,
     "Movie Some Story", "Movie Some Story (2017)", "2017"},
    {"Some.Movie.1954.BDRip.1080p.mkv", true, "Some Movie", "Some Movie (1954)", "1954"},
    {"Some «Movie».2021.WEB-DL.2160p.HDR.mkv", true, "Some «Movie»", "Some «Movie» (2021)", "2021"},
    {"Some Movie (2013).mp4", true, "Some Movie", "Some Movie (2013)", "2013"},
    {"Some Movie (2013) [imdbid-tt123].mp4", true, "Some Movie", "Some Movie (2013)", "2013",
     "imdb", "tt123"},
    {"Some Movie (2013) {tmdb-123}.mp4", true, "Some Movie", "Some Movie (2013)", "2013", "tmdb",
     "123"},
    {"Some Movie (2013) {tmdb=123}.mp4", true, "Some Movie", "Some Movie (2013)", "2013", "tmdb",
     "123"},
    {"Some (Director Cut).BDRemux.mkv", true, "Some (Director Cut)", "Some (Director Cut)", ""}}