Kodi Documentation: PVR::CPVRPlaybackState Class Reference
PVR::CPVRPlaybackState Class Reference
#include <PVRPlaybackState.h>
Classes
class CLastWatchedUpdateTimer
Public Member Functions
CPVRPlaybackState ()
ctor.
virtual ~CPVRPlaybackState ()
dtor.
void Clear ()
clear instances, keep stored UIDs.
void ReInit ()
re-init using stored UIDs.
void OnPlaybackStarted (const CFileItem &item)
Inform that playback of an item just started.
bool OnPlaybackStopped (const CFileItem &item)
Inform that playback of an item was stopped due to user interaction.
bool OnPlaybackEnded (const CFileItem &item)
Inform that playback of an item has stopped without user interaction.
void StartPlayback (std::unique_ptr< CFileItem > &item, ContentUtils::PlayMode mode, PVR_SOURCE source) const
Start playback of the given item.
bool IsPlaying () const
Check if a TV channel, radio channel or recording is playing.
bool IsPlayingTV () const
Check if a TV channel is playing.
bool IsPlayingRadio () const
Check if a radio channel is playing.
bool IsPlayingEncryptedChannel () const
Check if a an encrypted TV or radio channel is playing.
bool IsPlayingRecording () const
Check if a recording is playing.
bool IsPlayingEpgTag () const
Check if an epg tag is playing.
bool IsPlayingChannel (int iClientID, int iUniqueChannelID) const
Check whether playing channel matches given uids.
bool IsPlayingChannel (const std::shared_ptr< const CPVRChannel > &channel) const
Check if the given channel is playing.
bool IsPlayingRecording (const std::shared_ptr< const CPVRRecording > &recording) const
Check if the given recording is playing.
bool IsPlayingEpgTag (const std::shared_ptr< const CPVREpgInfoTag > &epgTag) const
Check if the given epg tag is playing.
std::shared_ptr< CPVRChannel > GetPlayingChannel () const
Return the channel that is currently playing.
std::shared_ptr< CPVRChannelGroupMember > GetPlayingChannelGroupMember () const
Return the channel group member that is currently playing.
std::shared_ptr< CPVRRecording > GetPlayingRecording () const
Return the recording that is currently playing.
std::shared_ptr< CPVREpgInfoTag > GetPlayingEpgTag () const
Return the epg tag that is currently playing.
int GetPlayingChannelUniqueID () const
Return playing channel unique identifier.
std::string GetPlayingClientName () const
Get the name of the playing client, if there is one.
int GetPlayingClientID () const
Get the ID of the playing client, if there is one.
bool IsRecording () const
Check whether there are active recordings.
bool IsRecordingOnPlayingChannel () const
Check whether there is an active recording on the currenlyt playing channel.
bool IsPlayingActiveRecording () const
Check if an active recording is playing.
bool CanRecordOnPlayingChannel () const
Check whether the currently playing channel can be recorded.
void SetActiveChannelGroup (const std::shared_ptr< CPVRChannelGroup > &group)
Set the active channel group.
std::shared_ptr< CPVRChannelGroup > GetActiveChannelGroup (bool bRadio) const
Get the active channel group.
std::shared_ptr< CPVRChannelGroupMember > GetLastPlayedChannelGroupMember (bool bRadio) const
Get the last played channel group member.
std::shared_ptr< CPVRChannelGroupMember > GetPreviousToLastPlayedChannelGroupMember (bool bRadio) const
Get the channel group member that was played before the last played member.
CDateTime GetPlaybackTime (int iClientID, int iUniqueChannelID) const
Get current playback time for the given channel, taking timeshifting and playing epg tags into account.
CDateTime GetChannelPlaybackTime (int iClientID, int iUniqueChannelID) const
Get current playback time for the given channel, taking timeshifting into account.
Private Member Functions
void ClearData ()
std::unique_ptr< CFileItem > GetNextAutoplayItem (const CFileItem &item)
Return the next item to play automatically, if any.
void SetActiveChannelGroup (const std::shared_ptr< CPVRChannelGroupMember > &channel)
Set the active group to the group of the supplied channel group member.
void UpdateLastWatched (const std::shared_ptr< CPVRChannelGroupMember > &channel, const CDateTime &time)
Updates the last watched timestamps of the channel and group which are currently playing.
Private Attributes
CCriticalSection m_critSection
std::shared_ptr< CPVRChannelGroupMember > m_playingChannel
std::shared_ptr< CPVRRecording > m_playingRecording
std::shared_ptr< CPVREpgInfoTag > m_playingEpgTag
std::shared_ptr< CPVRChannelGroupMember > m_lastPlayedChannelTV
std::shared_ptr< CPVRChannelGroupMember > m_lastPlayedChannelRadio
std::shared_ptr< CPVRChannelGroupMember > m_previousToLastPlayedChannelTV
std::shared_ptr< CPVRChannelGroupMember > m_previousToLastPlayedChannelRadio
std::string m_strPlayingClientName
int m_playingGroupId = -1
int m_playingClientId = PVR_CLIENT_INVALID_UID
int m_playingChannelUniqueId = -1
std::string m_strPlayingRecordingUniqueId
int m_playingEpgTagChannelUniqueId = -1
unsigned int m_playingEpgTagUniqueId = 0
std::shared_ptr< CPVRChannelGroup > m_activeGroupTV
std::shared_ptr< CPVRChannelGroup > m_activeGroupRadio
std::unique_ptr< CLastWatchedUpdateTimer > m_lastWatchedUpdateTimer
Constructor & Destructor Documentation
CPVRPlaybackState()
CPVRPlaybackState::CPVRPlaybackState () default
ctor.
~CPVRPlaybackState()
CPVRPlaybackState::~CPVRPlaybackState () virtual default
dtor.
Member Function Documentation
CanRecordOnPlayingChannel()
bool CPVRPlaybackState::CanRecordOnPlayingChannel () const
Check whether the currently playing channel can be recorded.
Returns
True if there is a playing channel that can be recorded, false otherwise.
References GetPlayingChannel().
Clear()
void CPVRPlaybackState::Clear ()
clear instances, keep stored UIDs.
References m_activeGroupRadio, m_activeGroupTV, m_critSection, m_lastPlayedChannelRadio, m_lastPlayedChannelTV, m_lastWatchedUpdateTimer, m_playingChannel, m_playingEpgTag, m_playingRecording, m_previousToLastPlayedChannelRadio, and m_previousToLastPlayedChannelTV.
Referenced by ReInit().
ClearData()
void CPVRPlaybackState::ClearData () private
References m_playingChannelUniqueId, m_playingClientId, m_playingEpgTagChannelUniqueId, m_playingEpgTagUniqueId, m_playingGroupId, m_strPlayingClientName, m_strPlayingRecordingUniqueId, and PVR::PVR_CLIENT_INVALID_UID.
Referenced by OnPlaybackStarted(), and OnPlaybackStopped().
GetActiveChannelGroup()
std::shared_ptr< CPVRChannelGroup > CPVRPlaybackState::GetActiveChannelGroup (bool bRadio) const
Get the active channel group.
Parameters
bRadio True to get the active radio group, false to get the active TV group.
Returns
The current group or the group containing all channels if it's not set.
References m_activeGroupRadio, and m_activeGroupTV.
GetChannelPlaybackTime()
CDateTime CPVRPlaybackState::GetChannelPlaybackTime (int iClientID, int iUniqueChannelID) const
Get current playback time for the given channel, taking timeshifting into account.
Parameters
iClientID The client id.
iUniqueChannelID The channel uid.
Returns
The playback time or 'now' if not playing.
References CServiceBroker::GetDataCacheCore(), CDataCacheCore::GetStartTime(), CDateTime::GetUTCDateTime(), and IsPlayingChannel().
Referenced by GetPlaybackTime().
GetLastPlayedChannelGroupMember()
std::shared_ptr< CPVRChannelGroupMember > CPVRPlaybackState::GetLastPlayedChannelGroupMember (bool bRadio) const
Get the last played channel group member.
Parameters
bRadio True to get the radio group member, false to get the TV group member.
Returns
The last played group member or nullptr if it's not available.
References m_critSection, m_lastPlayedChannelRadio, and m_lastPlayedChannelTV.
GetNextAutoplayItem()
std::unique_ptr< CFileItem > CPVRPlaybackState::GetNextAutoplayItem (const CFileItem & item) private
Return the next item to play automatically, if any.
Parameters
item The item which just finished playback.
Returns
The item to play next, if any, nullptr otherwise.
References CVariant::asBoolean(), PVR::CPVRManager::EpgContainer(), PVR::CPVREpgContainer::GetByChannelUid(), CFileItem::GetEPGInfoTag(), CGUIListItem::GetProperty(), CServiceBroker::GetPVRManager(), CFileItem::HasEPGInfoTag(), m_critSection, m_playingClientId, m_playingEpgTag, m_playingEpgTagChannelUniqueId, m_playingEpgTagUniqueId, and tags.
Referenced by OnPlaybackEnded().
GetPlaybackTime()
CDateTime CPVRPlaybackState::GetPlaybackTime (int iClientID, int iUniqueChannelID) const
Get current playback time for the given channel, taking timeshifting and playing epg tags into account.
Parameters
iClientID The client id.
iUniqueChannelID The channel uid.
Returns
The playback time or 'now' if not playing.
References GetChannelPlaybackTime(), CServiceBroker::GetDataCacheCore(), and GetPlayingEpgTag().
GetPlayingChannel()
std::shared_ptr< CPVRChannel > CPVRPlaybackState::GetPlayingChannel () const
Return the channel that is currently playing.
Returns
The channel or nullptr if none is playing.
References m_critSection, and m_playingChannel.
Referenced by CanRecordOnPlayingChannel(), IsPlayingChannel(), and IsRecordingOnPlayingChannel().
GetPlayingChannelGroupMember()
std::shared_ptr< CPVRChannelGroupMember > CPVRPlaybackState::GetPlayingChannelGroupMember () const
Return the channel group member that is currently playing.
Returns
The channel group member or nullptr if none is playing.
References m_critSection, and m_playingChannel.
GetPlayingChannelUniqueID()
int CPVRPlaybackState::GetPlayingChannelUniqueID () const
Return playing channel unique identifier.
Returns
The channel id or -1 if not present
References m_critSection, and m_playingChannelUniqueId.
GetPlayingClientID()
int CPVRPlaybackState::GetPlayingClientID () const
Get the ID of the playing client, if there is one.
Returns
The ID or PVR_CLIENT_INVALID_UID if no client is playing.
References m_critSection, and m_playingClientId.
GetPlayingClientName()
std::string CPVRPlaybackState::GetPlayingClientName () const
Get the name of the playing client, if there is one.
Returns
The name of the client or an empty string if nothing is playing.
References m_critSection, and m_strPlayingClientName.
GetPlayingEpgTag()
std::shared_ptr< CPVREpgInfoTag > CPVRPlaybackState::GetPlayingEpgTag () const
Return the epg tag that is currently playing.
Returns
The tag or nullptr if none is playing.
References m_critSection, and m_playingEpgTag.
Referenced by GetPlaybackTime(), and IsPlayingEpgTag().
GetPlayingRecording()
std::shared_ptr< CPVRRecording > CPVRPlaybackState::GetPlayingRecording () const
Return the recording that is currently playing.
Returns
The recording or nullptr if none is playing.
References m_critSection, and m_playingRecording.
Referenced by IsPlayingActiveRecording(), and IsPlayingRecording().
GetPreviousToLastPlayedChannelGroupMember()
std::shared_ptr< CPVRChannelGroupMember > CPVRPlaybackState::GetPreviousToLastPlayedChannelGroupMember (bool bRadio) const
Get the channel group member that was played before the last played member.
Parameters
bRadio True to get the radio group member, false to get the TV group member.
Returns
The previous played group member or nullptr if it's not available.
References m_critSection, m_previousToLastPlayedChannelRadio, and m_previousToLastPlayedChannelTV.
IsPlaying()
bool CPVRPlaybackState::IsPlaying () const
Check if a TV channel, radio channel or recording is playing.
Returns
True if it's playing, false otherwise.
References m_critSection, m_playingChannel, m_playingEpgTag, and m_playingRecording.
IsPlayingActiveRecording()
bool CPVRPlaybackState::IsPlayingActiveRecording () const
Check if an active recording is playing.
Returns
True if an in-progress (active) recording is playing, false otherwise.
References GetPlayingRecording().
IsPlayingChannel() [1/2]
bool CPVRPlaybackState::IsPlayingChannel (const std::shared_ptr< const CPVRChannel > & channel) const
Check if the given channel is playing.
Parameters
channel The channel to check.
Returns
True if it's playing, false otherwise.
References GetPlayingChannel().
IsPlayingChannel() [2/2]
bool CPVRPlaybackState::IsPlayingChannel (int iClientID, int iUniqueChannelID) const
Check whether playing channel matches given uids.
Parameters
iClientID The client id.
iUniqueChannelID The channel uid.
Returns
True on match, false if there is no match or no channel is playing.
References m_critSection, m_playingChannelUniqueId, and m_playingClientId.
Referenced by GetChannelPlaybackTime().
IsPlayingEncryptedChannel()
bool CPVRPlaybackState::IsPlayingEncryptedChannel () const
Check if a an encrypted TV or radio channel is playing.
Returns
True if it's playing, false otherwise.
References m_critSection, and m_playingChannel.
IsPlayingEpgTag() [1/2]
bool CPVRPlaybackState::IsPlayingEpgTag () const
Check if an epg tag is playing.
Returns
True if it's playing, false otherwise.
References m_critSection, and m_playingEpgTag.
IsPlayingEpgTag() [2/2]
bool CPVRPlaybackState::IsPlayingEpgTag (const std::shared_ptr< const CPVREpgInfoTag > & epgTag) const
Check if the given epg tag is playing.
Parameters
epgTag The tag to check.
Returns
True if it's playing, false otherwise.
References GetPlayingEpgTag().
IsPlayingRadio()
bool CPVRPlaybackState::IsPlayingRadio () const
Check if a radio channel is playing.
Returns
True if it's playing, false otherwise.
References m_critSection, and m_playingChannel.
IsPlayingRecording() [1/2]
bool CPVRPlaybackState::IsPlayingRecording () const
Check if a recording is playing.
Returns
True if it's playing, false otherwise.
References m_critSection, and m_playingRecording.
IsPlayingRecording() [2/2]
bool CPVRPlaybackState::IsPlayingRecording (const std::shared_ptr< const CPVRRecording > & recording) const
Check if the given recording is playing.
Parameters
recording The recording to check.
Returns
True if it's playing, false otherwise.
References GetPlayingRecording().
IsPlayingTV()
bool CPVRPlaybackState::IsPlayingTV () const
Check if a TV channel is playing.
Returns
True if it's playing, false otherwise.
References m_critSection, and m_playingChannel.
IsRecording()
bool CPVRPlaybackState::IsRecording () const
Check whether there are active recordings.
Returns
True if there are active recordings, false otherwise.
References CServiceBroker::GetPVRManager(), and PVR::CPVRManager::Timers().
IsRecordingOnPlayingChannel()
bool CPVRPlaybackState::IsRecordingOnPlayingChannel () const
Check whether there is an active recording on the currenlyt playing channel.
Returns
True if there is a playing channel and there is an active recording on that channel, false otherwise.
References GetPlayingChannel(), CServiceBroker::GetPVRManager(), and PVR::CPVRManager::Timers().
OnPlaybackEnded()
bool CPVRPlaybackState::OnPlaybackEnded (const CFileItem & item)
Inform that playback of an item has stopped without user interaction.
Parameters
item The item that ended to play.
Returns
True, if the state has changed, false otherwise
References ContentUtils::CHECK_AUTO_PLAY_NEXT_ITEM, GetNextAutoplayItem(), OnPlaybackStopped(), and StartPlayback().
OnPlaybackStarted()
void CPVRPlaybackState::OnPlaybackStarted (const CFileItem & item)
Inform that playback of an item just started.
Parameters
item The item that started to play.
References ClearData(), PVR::CPVRManager::GetClient(), CFileItem::GetEPGInfoTag(), CFileItem::GetPVRChannelGroupMemberInfoTag(), CServiceBroker::GetPVRManager(), CFileItem::GetPVRRecordingInfoTag(), CServiceBroker::GetSettingsComponent(), CDateTime::GetUTCDateTime(), CFileItem::HasEPGInfoTag(), CFileItem::HasPVRChannelGroupMemberInfoTag(), CFileItem::HasPVRChannelInfoTag(), CFileItem::HasPVRRecordingInfoTag(), LOGERROR, LOGPVR, m_critSection, m_lastPlayedChannelRadio, m_lastPlayedChannelTV, m_lastWatchedUpdateTimer, m_playingChannel, m_playingChannelUniqueId, m_playingClientId, m_playingEpgTag, m_playingEpgTagChannelUniqueId, m_playingEpgTagUniqueId, m_playingGroupId, m_playingRecording, m_previousToLastPlayedChannelRadio, m_previousToLastPlayedChannelTV, m_strPlayingClientName, m_strPlayingRecordingUniqueId, PVR::PVR_CLIENT_INVALID_UID, SetActiveChannelGroup(), CSettings::SETTING_PVRPLAYBACK_DELAYMARKLASTWATCHED, and UpdateLastWatched().
OnPlaybackStopped()
bool CPVRPlaybackState::OnPlaybackStopped (const CFileItem & item)
Inform that playback of an item was stopped due to user interaction.
Parameters
item The item that stopped to play.
Returns
True, if the state has changed, false otherwise
References ClearData(), CFileItem::GetEPGInfoTag(), CFileItem::GetPVRChannelGroupMemberInfoTag(), CFileItem::GetPVRRecordingInfoTag(), CDateTime::GetUTCDateTime(), CFileItem::HasEPGInfoTag(), CFileItem::HasPVRChannelGroupMemberInfoTag(), CFileItem::HasPVRChannelInfoTag(), CFileItem::HasPVRRecordingInfoTag(), LOGERROR, LOGPVR, m_critSection, m_lastWatchedUpdateTimer, m_playingChannel, m_playingChannelUniqueId, m_playingClientId, m_playingEpgTag, m_playingEpgTagChannelUniqueId, m_playingEpgTagUniqueId, m_playingRecording, m_strPlayingRecordingUniqueId, and UpdateLastWatched().
Referenced by OnPlaybackEnded().
ReInit()
void CPVRPlaybackState::ReInit ()
re-init using stored UIDs.
References PVR::CPVRManager::ChannelGroups(), Clear(), PVR::CPVRManager::EpgContainer(), PVR::CPVREpgContainer::GetByChannelUid(), CServiceBroker::GetPVRManager(), LOGERROR, LOGPVR, m_activeGroupRadio, m_activeGroupTV, m_critSection, m_lastPlayedChannelRadio, m_lastPlayedChannelTV, m_playingChannel, m_playingChannelUniqueId, m_playingClientId, m_playingEpgTag, m_playingEpgTagChannelUniqueId, m_playingEpgTagUniqueId, m_playingGroupId, m_playingRecording, m_previousToLastPlayedChannelRadio, m_previousToLastPlayedChannelTV, m_strPlayingRecordingUniqueId, PVR::PVR_CLIENT_INVALID_UID, and PVR::CPVRManager::Recordings().
SetActiveChannelGroup() [1/2]
void CPVRPlaybackState::SetActiveChannelGroup (const std::shared_ptr< CPVRChannelGroup > & group)
Set the active channel group.
Parameters
group The new group.
References LOGERROR, LOGPVR, m_activeGroupRadio, and m_activeGroupTV.
Referenced by OnPlaybackStarted(), and SetActiveChannelGroup().
SetActiveChannelGroup() [2/2]
void CPVRPlaybackState::SetActiveChannelGroup (const std::shared_ptr< CPVRChannelGroupMember > & channel) private
Set the active group to the group of the supplied channel group member.
Parameters
channel The channel group member
References PVR::CPVRManager::ChannelGroups(), CServiceBroker::GetPVRManager(), and SetActiveChannelGroup().
StartPlayback()
void CPVRPlaybackState::StartPlayback (std::unique_ptr< CFileItem > & item, ContentUtils::PlayMode mode, PVR_SOURCE source) const
Start playback of the given item.
Parameters
item containing a channel, a recording or an epg tag.
mode playback mode.
References ContentUtils::CHECK_AUTO_PLAY_NEXT_ITEM, CServiceBroker::GetAppMessenger(), PVR::CPVRManager::GetClient(), CServiceBroker::GetPVRManager(), CServiceBroker::GetSettingsComponent(), PVR::CPVRStreamProperties::GetStreamMimeType(), PVR::CPVRStreamProperties::GetStreamURL(), PVR::CPVRStreamProperties::LivePlaybackAsEPG(), LOGERROR, LOGPVR, ContentUtils::PLAY_FROM_HERE, PVR_ERROR_NO_ERROR, CSettings::SETTING_PVRPLAYBACK_AUTOPLAYNEXTPROGRAMME, TMSG_MEDIA_PLAY, and PVR::CPVRClient::ToString().
Referenced by OnPlaybackEnded().
UpdateLastWatched()
void CPVRPlaybackState::UpdateLastWatched (const std::shared_ptr< CPVRChannelGroupMember > & channel, const CDateTime & time) private
Updates the last watched timestamps of the channel and group which are currently playing.
Parameters
channel The channel which is updated
time The last watched time to set
References PVR::CPVRManager::ChannelGroups(), and CServiceBroker::GetPVRManager().
Referenced by OnPlaybackStarted(), OnPlaybackStopped(), and PVR::CPVRPlaybackState::CLastWatchedUpdateTimer::OnTimeout().
Member Data Documentation
m_activeGroupRadio
std::shared_ptr<CPVRChannelGroup> PVR::CPVRPlaybackState::m_activeGroupRadio private
Referenced by Clear(), GetActiveChannelGroup(), ReInit(), and SetActiveChannelGroup().
m_activeGroupTV
std::shared_ptr<CPVRChannelGroup> PVR::CPVRPlaybackState::m_activeGroupTV private
Referenced by Clear(), GetActiveChannelGroup(), ReInit(), and SetActiveChannelGroup().
m_critSection
CCriticalSection PVR::CPVRPlaybackState::m_critSection mutable private
Referenced by Clear(), GetLastPlayedChannelGroupMember(), GetNextAutoplayItem(), GetPlayingChannel(), GetPlayingChannelGroupMember(), GetPlayingChannelUniqueID(), GetPlayingClientID(), GetPlayingClientName(), GetPlayingEpgTag(), GetPlayingRecording(), GetPreviousToLastPlayedChannelGroupMember(), IsPlaying(), IsPlayingChannel(), IsPlayingEncryptedChannel(), IsPlayingEpgTag(), IsPlayingRadio(), IsPlayingRecording(), IsPlayingTV(), OnPlaybackStarted(), OnPlaybackStopped(), and ReInit().
m_lastPlayedChannelRadio
std::shared_ptr<CPVRChannelGroupMember> PVR::CPVRPlaybackState::m_lastPlayedChannelRadio private
Referenced by Clear(), GetLastPlayedChannelGroupMember(), OnPlaybackStarted(), and ReInit().
m_lastPlayedChannelTV
std::shared_ptr<CPVRChannelGroupMember> PVR::CPVRPlaybackState::m_lastPlayedChannelTV private
Referenced by Clear(), GetLastPlayedChannelGroupMember(), OnPlaybackStarted(), and ReInit().
m_lastWatchedUpdateTimer
std::unique_ptr<CLastWatchedUpdateTimer> PVR::CPVRPlaybackState::m_lastWatchedUpdateTimer private
Referenced by Clear(), OnPlaybackStarted(), and OnPlaybackStopped().
m_playingChannel
std::shared_ptr<CPVRChannelGroupMember> PVR::CPVRPlaybackState::m_playingChannel private
Referenced by Clear(), GetPlayingChannel(), GetPlayingChannelGroupMember(), IsPlaying(), IsPlayingEncryptedChannel(), IsPlayingRadio(), IsPlayingTV(), OnPlaybackStarted(), OnPlaybackStopped(), and ReInit().
m_playingChannelUniqueId
int PVR::CPVRPlaybackState::m_playingChannelUniqueId = -1 private
Referenced by ClearData(), GetPlayingChannelUniqueID(), IsPlayingChannel(), OnPlaybackStarted(), OnPlaybackStopped(), and ReInit().
m_playingClientId
int PVR::CPVRPlaybackState::m_playingClientId = PVR_CLIENT_INVALID_UID private
Referenced by ClearData(), GetNextAutoplayItem(), GetPlayingClientID(), IsPlayingChannel(), OnPlaybackStarted(), OnPlaybackStopped(), and ReInit().
m_playingEpgTag
std::shared_ptr<CPVREpgInfoTag> PVR::CPVRPlaybackState::m_playingEpgTag private
Referenced by Clear(), GetNextAutoplayItem(), GetPlayingEpgTag(), IsPlaying(), IsPlayingEpgTag(), OnPlaybackStarted(), OnPlaybackStopped(), and ReInit().
m_playingEpgTagChannelUniqueId
int PVR::CPVRPlaybackState::m_playingEpgTagChannelUniqueId = -1 private
Referenced by ClearData(), GetNextAutoplayItem(), OnPlaybackStarted(), OnPlaybackStopped(), and ReInit().
m_playingEpgTagUniqueId
unsigned int PVR::CPVRPlaybackState::m_playingEpgTagUniqueId = 0 private
Referenced by ClearData(), GetNextAutoplayItem(), OnPlaybackStarted(), OnPlaybackStopped(), and ReInit().
m_playingGroupId
int PVR::CPVRPlaybackState::m_playingGroupId = -1 private
Referenced by ClearData(), OnPlaybackStarted(), and ReInit().
m_playingRecording
std::shared_ptr<CPVRRecording> PVR::CPVRPlaybackState::m_playingRecording private
Referenced by Clear(), GetPlayingRecording(), IsPlaying(), IsPlayingRecording(), OnPlaybackStarted(), OnPlaybackStopped(), and ReInit().
m_previousToLastPlayedChannelRadio
std::shared_ptr<CPVRChannelGroupMember> PVR::CPVRPlaybackState::m_previousToLastPlayedChannelRadio private
Referenced by Clear(), GetPreviousToLastPlayedChannelGroupMember(), OnPlaybackStarted(), and ReInit().
m_previousToLastPlayedChannelTV
std::shared_ptr<CPVRChannelGroupMember> PVR::CPVRPlaybackState::m_previousToLastPlayedChannelTV private
Referenced by Clear(), GetPreviousToLastPlayedChannelGroupMember(), OnPlaybackStarted(), and ReInit().
m_strPlayingClientName
std::string PVR::CPVRPlaybackState::m_strPlayingClientName private
Referenced by ClearData(), GetPlayingClientName(), and OnPlaybackStarted().
m_strPlayingRecordingUniqueId
std::string PVR::CPVRPlaybackState::m_strPlayingRecordingUniqueId private
Referenced by ClearData(), OnPlaybackStarted(), OnPlaybackStopped(), and ReInit().
The documentation for this class was generated from the following files:
PVRPlaybackState.h
PVRPlaybackState.cpp