Kodi Documentation: CBackgroundInfoLoader Class Reference
CBackgroundInfoLoader Class Reference
#include <BackgroundInfoLoader.h>
Public Member Functions
CBackgroundInfoLoader ()
~CBackgroundInfoLoader () override
void Load (CFileItemList &items)
bool IsLoading ()
void Run () override
void SetObserver (IBackgroundLoaderObserver *pObserver)
void SetProgressCallback (IProgressCallback *pCallback)
virtual bool LoadItem (CFileItem *pItem)
virtual bool LoadItemCached (CFileItem *pItem)
virtual bool LoadItemLookup (CFileItem *pItem)
void StopThread ()
void StopAsync ()
Public Member Functions inherited from IRunnable
virtual void Cancel ()
virtual ~IRunnable ()=default
Protected Member Functions
virtual void OnLoaderStart ()
virtual void OnLoaderFinish ()
Protected Attributes
CFileItemList * m_pVecItems {nullptr}
std::vector< CFileItemPtr > m_vecItems
CCriticalSection m_lock
volatile bool m_bIsLoading {false}
volatile bool m_bStop {true}
CThread * m_thread {nullptr}
IBackgroundLoaderObserver * m_pObserver {nullptr}
IProgressCallback * m_pProgressCallback {nullptr}
Private Member Functions
void Reset ()
Constructor & Destructor Documentation
CBackgroundInfoLoader()
CBackgroundInfoLoader::CBackgroundInfoLoader () default
~CBackgroundInfoLoader()
CBackgroundInfoLoader::~CBackgroundInfoLoader () override
References StopThread().
Member Function Documentation
IsLoading()
bool CBackgroundInfoLoader::IsLoading ()
References m_bIsLoading.
Referenced by CGUIDialogVideoManagerVersions::AddVideoVersion(), KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideo(), CGUIDialogVideoManagerVersions::ChooseVideoAndConvertToVideoVersion(), PVR::CGUIDialogPVRGroupManager::Clear(), CGUIWindowPictures::GetContextButtons(), CGUIWindowVideoNav::GetDirectory(), CGUIWindowVideoBase::GetGroupedItems(), CGUIWindowMusicPlayList::MoveItem(), CGUIWindowAddonBrowser::OnMessage(), CGUIDialogFileBrowser::OnMessage(), CGUIWindowMusicBase::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowMusicPlaylistEditor::OnMessage(), CGUIWindowPictures::OnMessage(), CGUIWindowPrograms::OnMessage(), CGUIWindowVideoBase::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIWindowMusicPlayList::OnMove(), CGUIWindowVideoBase::OnPlayMedia(), CGUIWindowPictures::OnPrepareFileItems(), CGUIWindowPictures::OnRegenerateThumbs(), CGUIWindowMusicBase::OnRetrieveMusicInfo(), CGUIDialogFileBrowser::Update(), CGUIWindowAddonBrowser::Update(), CGUIWindowMusicNav::Update(), CGUIWindowMusicPlayList::Update(), CGUIWindowMusicPlaylistEditor::Update(), CGUIWindowPictures::Update(), CGUIWindowPrograms::Update(), CGUIWindowVideoBase::Update(), and CGUIWindowMusicPlaylistEditor::UpdatePlaylist().
Load()
void CBackgroundInfoLoader::Load (CFileItemList & items)
References BELOW_NORMAL, CThread::Create(), CFileItemList::IsEmpty(), m_bIsLoading, m_bStop, m_lock, m_pVecItems, m_thread, m_vecItems, CThread::SetPriority(), CFileItemList::Size(), and StopThread().
Referenced by CGUIDialogVideoManagerVersions::AddVideoVersion(), KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideo(), CGUIDialogVideoManagerVersions::ChooseVideoAndConvertToVideoVersion(), CGUIWindowVideoBase::GetGroupedItems(), CGUIWindowMusicPlayList::MoveItem(), CGUIWindowMusicPlayList::OnMove(), CGUIWindowVideoBase::OnPlayMedia(), CGUIWindowPictures::OnPrepareFileItems(), PVR::CGUIWindowPVRRecordingsBase::OnPrepareFileItems(), CGUIWindowPictures::OnRegenerateThumbs(), CGUIWindowMusicBase::OnRetrieveMusicInfo(), PVR::CGUIDialogPVRGroupManager::Update(), CGUIDialogFileBrowser::Update(), CGUIWindowAddonBrowser::Update(), CGUIWindowMusicNav::Update(), CGUIWindowMusicPlayList::Update(), CGUIWindowMusicPlaylistEditor::Update(), CGUIWindowPictures::Update(), CGUIWindowPrograms::Update(), CGUIWindowVideoBase::Update(), and CGUIWindowMusicPlaylistEditor::UpdatePlaylist().
LoadItem()
virtual bool CBackgroundInfoLoader::LoadItem (CFileItem * pItem) inline virtual
Reimplemented in PVR::CPVRThumbLoader, MUSIC_INFO::CMusicInfoLoader, CMusicThumbLoader, CPictureInfoLoader, CPictureThumbLoader, CProgramThumbLoader, and CVideoThumbLoader.
LoadItemCached()
virtual bool CBackgroundInfoLoader::LoadItemCached (CFileItem * pItem) inline virtual
Reimplemented in PVR::CPVRThumbLoader, MUSIC_INFO::CMusicInfoLoader, CMusicThumbLoader, CPictureInfoLoader, CPictureThumbLoader, CProgramThumbLoader, and CVideoThumbLoader.
Referenced by Run().
LoadItemLookup()
virtual bool CBackgroundInfoLoader::LoadItemLookup (CFileItem * pItem) inline virtual
Reimplemented in PVR::CPVRThumbLoader, MUSIC_INFO::CMusicInfoLoader, CMusicThumbLoader, CPictureInfoLoader, CPictureThumbLoader, CProgramThumbLoader, and CVideoThumbLoader.
Referenced by Run().
OnLoaderFinish()
virtual void CBackgroundInfoLoader::OnLoaderFinish () inline protected virtual
Reimplemented in MUSIC_INFO::CMusicInfoLoader, CMusicThumbLoader, CPictureInfoLoader, CPictureThumbLoader, PVR::CPVRThumbLoader, CThumbLoader, and CVideoThumbLoader.
Referenced by Run().
OnLoaderStart()
virtual void CBackgroundInfoLoader::OnLoaderStart () inline protected virtual
Reimplemented in MUSIC_INFO::CMusicInfoLoader, CMusicThumbLoader, CPictureInfoLoader, CThumbLoader, and CVideoThumbLoader.
Referenced by Run().
Reset()
void CBackgroundInfoLoader::Reset () private
References m_bIsLoading, m_pVecItems, and m_vecItems.
Referenced by Run(), and StopThread().
Run()
void CBackgroundInfoLoader::Run () override virtual
Implements IRunnable.
References IProgressCallback::Abort(), LoadItemCached(), LoadItemLookup(), CLog::Log(), LOGERROR, m_bStop, m_pObserver, m_pProgressCallback, m_vecItems, IBackgroundLoaderObserver::OnItemLoaded(), OnLoaderFinish(), OnLoaderStart(), and Reset().
SetObserver()
void CBackgroundInfoLoader::SetObserver (IBackgroundLoaderObserver * pObserver)
References m_pObserver.
Referenced by CGUIDialogFileBrowser::CGUIDialogFileBrowser(), CGUIWindowMusicBase::CGUIWindowMusicBase(), CGUIWindowMusicPlayList::CGUIWindowMusicPlayList(), CGUIWindowMusicPlaylistEditor::CGUIWindowMusicPlaylistEditor(), CGUIWindowPictures::CGUIWindowPictures(), CGUIWindowPrograms::CGUIWindowPrograms(), CGUIWindowVideoBase::CGUIWindowVideoBase(), and CGUIWindowVideoNav::CGUIWindowVideoNav().
SetProgressCallback()
void CBackgroundInfoLoader::SetProgressCallback (IProgressCallback * pCallback)
References m_pProgressCallback.
Referenced by CGUIWindowPictures::OnPrepareFileItems(), and CGUIWindowMusicBase::OnRetrieveMusicInfo().
StopAsync()
void CBackgroundInfoLoader::StopAsync ()
References m_bStop.
Referenced by CGUIWindowVideoBase::OnPlayMedia(), and StopThread().
StopThread()
void CBackgroundInfoLoader::StopThread ()
References m_thread, Reset(), StopAsync(), and CThread::StopThread().
Referenced by CGUIDialogVideoManagerVersions::AddVideoVersion(), KODI::VIDEO::GUILIB::anonymous_namespace{VideoVersionHelper.cpp}::CVideoChooser::ChooseVideo(), CGUIDialogVideoManagerVersions::ChooseVideoAndConvertToVideoVersion(), PVR::CGUIDialogPVRGroupManager::Clear(), CGUIWindowVideoNav::GetDirectory(), CGUIWindowVideoBase::GetGroupedItems(), Load(), CGUIWindowMusicPlayList::MoveItem(), CGUIWindowAddonBrowser::OnMessage(), CGUIDialogFileBrowser::OnMessage(), CGUIWindowMusicBase::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowMusicPlaylistEditor::OnMessage(), CGUIWindowPictures::OnMessage(), CGUIWindowPrograms::OnMessage(), CGUIWindowVideoBase::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIWindowMusicPlayList::OnMove(), CGUIDialogFileBrowser::Update(), CGUIWindowAddonBrowser::Update(), CGUIWindowMusicNav::Update(), CGUIWindowMusicPlayList::Update(), CGUIWindowMusicPlaylistEditor::Update(), CGUIWindowPictures::Update(), CGUIWindowPrograms::Update(), PVR::CGUIWindowPVRRecordingsBase::Update(), CGUIWindowVideoBase::Update(), CGUIWindowMusicPlaylistEditor::UpdatePlaylist(), ~CBackgroundInfoLoader(), MUSIC_INFO::CMusicInfoLoader::~CMusicInfoLoader(), CPictureInfoLoader::~CPictureInfoLoader(), CPictureThumbLoader::~CPictureThumbLoader(), and CVideoThumbLoader::~CVideoThumbLoader().
Member Data Documentation
m_bIsLoading
volatile bool CBackgroundInfoLoader::m_bIsLoading {false} protected
Referenced by IsLoading(), Load(), and Reset().
m_bStop
volatile bool CBackgroundInfoLoader::m_bStop {true} protected
Referenced by Load(), MUSIC_INFO::CMusicInfoLoader::OnLoaderFinish(), CPictureInfoLoader::OnLoaderFinish(), Run(), and StopAsync().
m_lock
CCriticalSection CBackgroundInfoLoader::m_lock protected
Referenced by Load().
m_pObserver
IBackgroundLoaderObserver* CBackgroundInfoLoader::m_pObserver {nullptr} protected
Referenced by Run(), and SetObserver().
m_pProgressCallback
IProgressCallback* CBackgroundInfoLoader::m_pProgressCallback {nullptr} protected
Referenced by MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), CPictureInfoLoader::LoadItemLookup(), MUSIC_INFO::CMusicInfoLoader::OnLoaderStart(), CPictureInfoLoader::OnLoaderStart(), Run(), and SetProgressCallback().
m_pVecItems
CFileItemList* CBackgroundInfoLoader::m_pVecItems {nullptr} protected
Referenced by Load(), MUSIC_INFO::CMusicInfoLoader::OnLoaderFinish(), CPictureInfoLoader::OnLoaderFinish(), MUSIC_INFO::CMusicInfoLoader::OnLoaderStart(), CPictureInfoLoader::OnLoaderStart(), and Reset().
m_thread
CThread* CBackgroundInfoLoader::m_thread {nullptr} protected
Referenced by Load(), and StopThread().
m_vecItems
std::vector<CFileItemPtr> CBackgroundInfoLoader::m_vecItems protected
Referenced by Load(), Reset(), and Run().
The documentation for this class was generated from the following files:
BackgroundInfoLoader.h
BackgroundInfoLoader.cpp