Kodi Documentation: CLirc Class Reference
CLirc Class Reference
#include <LIRC.h>
Public Member Functions
CLirc ()
~CLirc () override
void Start ()
Protected Member Functions
void Process () override
void ProcessCode (char *buf)
bool CheckDaemon ()
Protected Attributes
int m_fd = -1
std::chrono::time_point< std::chrono::steady_clock > m_firstClickTime
CCriticalSection m_critSection
std::unique_ptr< KODI::KEYMAP::CIRTranslator > m_irTranslator
int m_profileId
Additional Inherited Members
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CLirc()
CLirc::CLirc ()
~CLirc()
CLirc::~CLirc () override
References m_critSection, m_fd, SHUT_RDWR, shutdown(), and CThread::StopThread().
Member Function Documentation
CheckDaemon()
bool CLirc::CheckDaemon () protected
Referenced by Process().
Process()
void CLirc::Process (void) override protected virtual
Reimplemented from CThread.
References CheckDaemon(), CServiceBroker::GetSettingsComponent(), CThread::m_bStop, m_critSection, m_fd, m_irTranslator, m_profileId, ProcessCode(), and CThread::Sleep().
ProcessCode()
void CLirc::ProcessCode (char * buf) protected
References XBMC_ButtonEvent::button, end(), CServiceBroker::GetAppPort(), CServiceBroker::GetSettingsComponent(), XBMC_ButtonEvent::holdtime, XBMC_Event::keybutton, CLog::Log(), LOGDEBUG, LOGERROR, m_firstClickTime, m_irTranslator, XBMC_Event::type, and XBMC_BUTTON.
Referenced by Process().
Start()
void CLirc::Start ()
References CThread::Create(), LOWEST, and CThread::SetPriority().
Member Data Documentation
m_critSection
CCriticalSection CLirc::m_critSection protected
Referenced by Process(), and ~CLirc().
m_fd
int CLirc::m_fd = -1 protected
Referenced by Process(), and ~CLirc().
m_firstClickTime
std::chrono::time_point<std::chrono::steady_clock> CLirc::m_firstClickTime protected
Referenced by ProcessCode().
m_irTranslator
std::unique_ptr<KODI::KEYMAP::CIRTranslator> CLirc::m_irTranslator protected
Referenced by Process(), and ProcessCode().
m_profileId
int CLirc::m_profileId protected
Referenced by Process().
The documentation for this class was generated from the following files:
LIRC.h
LIRC.cpp