Kodi Documentation: KODI::GAME::CDialogGameOSDHelp Class Reference
KODI::GAME::CDialogGameOSDHelp Class Reference
#include <DialogGameOSDHelp.h>
Public Member Functions
CDialogGameOSDHelp (CDialogGameOSD &dialog)
void OnInitWindow ()
bool IsVisible ()
Private Member Functions
bool IsVisible (int windowId)
Private Attributes
CDialogGameOSD & m_dialog
Static Private Attributes
static const int CONTROL_ID_HELP_TEXT = 1101
Constructor & Destructor Documentation
CDialogGameOSDHelp()
CDialogGameOSDHelp::CDialogGameOSDHelp (CDialogGameOSD & dialog)
Member Function Documentation
IsVisible() [1/2]
bool CDialogGameOSDHelp::IsVisible ()
References CONTROL_ID_HELP_TEXT, and IsVisible().
Referenced by IsVisible().
IsVisible() [2/2]
bool CDialogGameOSDHelp::IsVisible (int windowId) private
References CGUIControlLookup::GetControl(), CGUIControl::IsVisible(), and m_dialog.
OnInitWindow()
void CDialogGameOSDHelp::OnInitWindow ()
References CONTROL_ID_HELP_TEXT, g_localizeStrings, CLocalizeStrings::Get(), GUI_MSG_LABEL_SET, m_dialog, CGUIDialog::OnMessage(), CGUIMessage::SetLabel(), and WINDOW_DIALOG_GAME_OSD.
Member Data Documentation
CONTROL_ID_HELP_TEXT
const int CDialogGameOSDHelp::CONTROL_ID_HELP_TEXT = 1101 static private
Referenced by IsVisible(), and OnInitWindow().
m_dialog
CDialogGameOSD& KODI::GAME::CDialogGameOSDHelp::m_dialog private
Referenced by IsVisible(), and OnInitWindow().
The documentation for this class was generated from the following files:
DialogGameOSDHelp.h
DialogGameOSDHelp.cpp