Kodi Documentation: HttpRangeUtils Class Reference
HttpRangeUtils Class Reference
#include <HttpRangeUtils.h>
Static Public Member Functions
static std::string GenerateContentRangeHeaderValue (const CHttpRange *range)
Generates a valid Content-Range HTTP header value for the given HTTP range definition.
static std::string GenerateContentRangeHeaderValue (uint64_t start, uint64_t end, uint64_t total)
Generates a valid Content-Range HTTP header value for the given HTTP range properties.
Member Function Documentation
GenerateContentRangeHeaderValue() [1/2]
std::string HttpRangeUtils::GenerateContentRangeHeaderValue (const CHttpRange * range) static
Generates a valid Content-Range HTTP header value for the given HTTP range definition.
Parameters
range HTTP range definition used to generate the Content-Range HTTP header
Returns
Content-Range HTTP header value
References CONTENT_RANGE_FORMAT_TOTAL, CHttpRange::GetFirstPosition(), CHttpRange::GetLastPosition(), and CHttpRange::GetLength().
Referenced by TestWebServer::CheckRangesTestFileResponse(), CWebServer::CreateFileDownloadResponse(), and CWebServer::CreateRangedMemoryDownloadResponse().
GenerateContentRangeHeaderValue() [2/2]
std::string HttpRangeUtils::GenerateContentRangeHeaderValue (uint64_t start, uint64_t end, uint64_t total) static
Generates a valid Content-Range HTTP header value for the given HTTP range properties.
Parameters
start Start position of the HTTP range
end Last/End position of the HTTP range
total Total length of original content (not just the range)
Returns
Content-Range HTTP header value
References CONTENT_RANGE_FORMAT_TOTAL, CONTENT_RANGE_FORMAT_TOTAL_UNKNOWN, and end().
The documentation for this class was generated from the following files:
HttpRangeUtils.h
HttpRangeUtils.cpp