Kodi Documentation: KODI::PLAYLIST::CSmartPlaylistFileItemListModifier Class Reference
KODI::PLAYLIST::CSmartPlaylistFileItemListModifier Class Reference
#include <SmartPlaylistFileItemListModifier.h>
Public Member Functions
CSmartPlaylistFileItemListModifier ()=default
~CSmartPlaylistFileItemListModifier () override=default
bool CanModify (const CFileItemList &items) const override
bool Modify (CFileItemList &items) const override
Public Member Functions inherited from IFileItemListModifier
IFileItemListModifier ()=default
virtual ~IFileItemListModifier ()=default
Static Private Member Functions
static std::string GetUrlOption (const std::string &path, const std::string &option)
Constructor & Destructor Documentation
CSmartPlaylistFileItemListModifier()
KODI::PLAYLIST::CSmartPlaylistFileItemListModifier::CSmartPlaylistFileItemListModifier () default
~CSmartPlaylistFileItemListModifier()
KODI::PLAYLIST::CSmartPlaylistFileItemListModifier::~CSmartPlaylistFileItemListModifier () override default
Member Function Documentation
CanModify()
bool KODI::PLAYLIST::CSmartPlaylistFileItemListModifier::CanModify (const CFileItemList & items) const override virtual
Implements IFileItemListModifier.
References CFileItem::GetPath(), GetUrlOption(), and URL_OPTION_XSP.
GetUrlOption()
std::string KODI::PLAYLIST::CSmartPlaylistFileItemListModifier::GetUrlOption (const std::string & path, const std::string & option) static private
References CURL::GetOption().
Referenced by CanModify(), and Modify().
Modify()
bool KODI::PLAYLIST::CSmartPlaylistFileItemListModifier::Modify (CFileItemList & items) const override virtual
Implements IFileItemListModifier.
References KODI::PLAYLIST::CSmartPlaylist::GetOrder(), KODI::PLAYLIST::CSmartPlaylist::GetOrderDirection(), CFileItem::GetPath(), GetUrlOption(), CGUIListItem::HasProperty(), KODI::PLAYLIST::CSmartPlaylist::LoadFromJson(), PROPERTY_SORT_ASCENDING, PROPERTY_SORT_ORDER, CGUIListItem::SetProperty(), SortOrderAscending, and URL_OPTION_XSP.
The documentation for this class was generated from the following files:
SmartPlaylistFileItemListModifier.h
SmartPlaylistFileItemListModifier.cpp