Kodi Documentation: CRendererDRMPRIMEGLES Class Reference
CRendererDRMPRIMEGLES Class Reference
#include <RendererDRMPRIMEGLES.h>
Classes
struct BUFFER
Public Member Functions
CRendererDRMPRIMEGLES ()=default
~CRendererDRMPRIMEGLES () override
bool Configure (const VideoPicture &picture, float fps, unsigned int orientation) override
bool IsConfigured () override
void AddVideoPicture (const VideoPicture &picture, int index) override
void UnInit () override
bool Flush (bool saveBuffers) override
void ReleaseBuffer (int idx) override
bool NeedBuffer (int idx) override
CRenderInfo GetRenderInfo () override
void Update () override
void RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha) override
bool RenderCapture (int index, CRenderCapture *capture) override
bool ConfigChanged (const VideoPicture &picture) override
bool SupportsMultiPassRendering () override
bool Supports (ERENDERFEATURE feature) const override
bool Supports (ESCALINGMETHOD method) const override
Public Member Functions inherited from CBaseRenderer
CBaseRenderer ()
virtual ~CBaseRenderer ()
virtual bool IsPictureHW (const VideoPicture &picture)
virtual void SetBufferSize (int numBuffers)
virtual bool IsGuiLayer ()
virtual bool WantsDoublePass ()
void SetViewMode (int viewMode)
void GetVideoRect (CRect &source, CRect &dest, CRect &view) const
Get video rectangle and view window.
float GetAspectRatio () const
unsigned int GetOrientation () const
void SetVideoSettings (const CVideoSettings &settings)
virtual DEBUG_INFO_VIDEO GetDebugInfo (int idx)
virtual CRenderCapture * GetRenderCapture ()
Static Public Member Functions
static CBaseRenderer * Create (CVideoBuffer *buffer)
static void Register ()
Static Public Member Functions inherited from CBaseRenderer
static void SettingOptionsRenderMethodsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
Private Member Functions
void DrawBlackBars ()
void Render (unsigned int flags, int index)
Private Attributes
bool m_configured = false
float m_clearColour {0.0f}
struct CRendererDRMPRIMEGLES::BUFFER m_buffers [NUM_BUFFERS]
Additional Inherited Members
Protected Member Functions inherited from CBaseRenderer
void CalcDestRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift, CRect &destRect)
void CalcNormalRenderRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift)
void CalculateFrameAspectRatio (unsigned int desired_width, unsigned int desired_height)
virtual void ManageRenderArea ()
virtual void ReorderDrawPoints ()
virtual EShaderFormat GetShaderFormat ()
void MarkDirty ()
void EnableAlwaysClip ()
void saveRotatedCoords ()
void syncDestRectToRotatedPoints ()
void restoreRotatedCoords ()
Protected Attributes inherited from CBaseRenderer
unsigned int m_sourceWidth = 720
unsigned int m_sourceHeight = 480
float m_sourceFrameRatio = 1.0f
float m_fps = 0.0f
unsigned int m_renderOrientation = 0
CPoint m_rotatedDestCoords [4]
CPoint m_savedRotatedDestCoords [4]
CRect m_destRect
CRect m_sourceRect
CRect m_viewRect
unsigned m_iFlags = 0
AVPixelFormat m_format = AV_PIX_FMT_NONE
CVideoSettings m_videoSettings
Constructor & Destructor Documentation
CRendererDRMPRIMEGLES()
CRendererDRMPRIMEGLES::CRendererDRMPRIMEGLES () default
Referenced by Create().
~CRendererDRMPRIMEGLES()
CRendererDRMPRIMEGLES::~CRendererDRMPRIMEGLES () override
References Flush().
Member Function Documentation
AddVideoPicture()
void CRendererDRMPRIMEGLES::AddVideoPicture (const VideoPicture & picture, int index) override virtual
Implements CBaseRenderer.
References CVideoBuffer::Acquire(), CRendererDRMPRIMEGLES::BUFFER::fence, index(), LOGERROR, m_buffers, CVideoBuffer::Release(), CRendererDRMPRIMEGLES::BUFFER::texture, CDRMPRIMETexture::Unmap(), VideoPicture::videoBuffer, and CRendererDRMPRIMEGLES::BUFFER::videoBuffer.
ConfigChanged()
bool CRendererDRMPRIMEGLES::ConfigChanged (const VideoPicture & picture) override virtual
Implements CBaseRenderer.
References CVideoBuffer::GetFormat(), CBaseRenderer::m_format, and VideoPicture::videoBuffer.
Configure()
bool CRendererDRMPRIMEGLES::Configure (const VideoPicture & picture, float fps, unsigned int orientation) override virtual
Implements CBaseRenderer.
References CBaseRenderer::CalculateFrameAspectRatio(), VideoPicture::chroma_position, VideoPicture::color_primaries, VideoPicture::color_space, Flush(), KODI::WINDOWING::LINUX::CWinSystemEGL::GetEGLDisplay(), GetFlagsChromaPosition(), GetFlagsColorMatrix(), GetFlagsColorPrimaries(), GetFlagsStereoMode(), CVideoBuffer::GetFormat(), CServiceBroker::GetWinSystem(), VideoPicture::iDisplayHeight, VideoPicture::iDisplayWidth, VideoPicture::iHeight, VideoPicture::iWidth, m_buffers, m_clearColour, m_configured, CBaseRenderer::m_format, CBaseRenderer::m_iFlags, CBaseRenderer::m_renderOrientation, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, CBaseRenderer::m_videoSettings, CVideoSettings::m_ViewMode, CBaseRenderer::ManageRenderArea(), CBaseRenderer::SetViewMode(), VideoPicture::stereoMode, and VideoPicture::videoBuffer.
Create()
CBaseRenderer * CRendererDRMPRIMEGLES::Create (CVideoBuffer * buffer) static
References CRendererDRMPRIMEGLES(), CVideoBufferDRMPRIME::GetDescriptor(), and CServiceBroker::GetWinSystem().
Referenced by Register().
DrawBlackBars()
void CRendererDRMPRIMEGLES::DrawBlackBars () private
References CRenderSystemGLES::DisableGUIShader(), CRenderSystemGLES::EnableGUIShader(), CServiceBroker::GetRenderSystem(), CServiceBroker::GetWinSystem(), CRenderSystemGLES::GUIShaderGetDepth(), CRenderSystemGLES::GUIShaderGetPos(), CRenderSystemGLES::GUIShaderGetUniCol(), m_clearColour, CBaseRenderer::m_destRect, SM_DEFAULT, and CRectGen< T >::SubtractRect().
Referenced by RenderUpdate().
Flush()
bool CRendererDRMPRIMEGLES::Flush (bool saveBuffers) override virtual
Reimplemented from CBaseRenderer.
References NUM_BUFFERS, and ReleaseBuffer().
Referenced by Configure(), and ~CRendererDRMPRIMEGLES().
GetRenderInfo()
CRenderInfo CRendererDRMPRIMEGLES::GetRenderInfo () override virtual
Reimplemented from CBaseRenderer.
References CRenderInfo::max_buffer_size, and NUM_BUFFERS.
IsConfigured()
bool CRendererDRMPRIMEGLES::IsConfigured () inline override virtual
Implements CBaseRenderer.
References m_configured.
NeedBuffer()
bool CRendererDRMPRIMEGLES::NeedBuffer (int idx) override virtual
Reimplemented from CBaseRenderer.
References CRendererDRMPRIMEGLES::BUFFER::fence, index(), and m_buffers.
Register()
void CRendererDRMPRIMEGLES::Register () static
References Create(), and VIDEOPLAYER::CRendererFactory::RegisterRenderer().
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::InitWindowSystem(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::InitWindowSystem().
ReleaseBuffer()
void CRendererDRMPRIMEGLES::ReleaseBuffer (int idx) override virtual
Reimplemented from CBaseRenderer.
References CRendererDRMPRIMEGLES::BUFFER::fence, index(), m_buffers, CVideoBuffer::Release(), CRendererDRMPRIMEGLES::BUFFER::texture, CDRMPRIMETexture::Unmap(), and CRendererDRMPRIMEGLES::BUFFER::videoBuffer.
Referenced by Flush().
Render()
void CRendererDRMPRIMEGLES::Render (unsigned int flags, int index) private
References CRenderSystemGLES::DisableGUIShader(), CRenderSystemGLES::EnableGUIShader(), CRendererDRMPRIMEGLES::BUFFER::fence, CServiceBroker::GetRenderSystem(), CDRMPRIMETexture::GetTexture(), CRenderSystemGLES::GUIShaderGetCoord0(), CRenderSystemGLES::GUIShaderGetDepth(), CRenderSystemGLES::GUIShaderGetPos(), index(), m_buffers, CBaseRenderer::m_rotatedDestCoords, CDRMPRIMETexture::Map(), SM_TEXTURE_RGBA_OES, CRendererDRMPRIMEGLES::BUFFER::texture, CRendererDRMPRIMEGLES::BUFFER::videoBuffer, CPointGen< T >::x, and CPointGen< T >::y.
Referenced by RenderUpdate().
RenderCapture()
bool CRendererDRMPRIMEGLES::RenderCapture (int index, CRenderCapture * capture) override virtual
Implements CBaseRenderer.
References CRenderCapture::BeginRender(), and CRenderCapture::EndRender().
RenderUpdate()
void CRendererDRMPRIMEGLES::RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha) override virtual
Implements CBaseRenderer.
References DrawBlackBars(), index(), m_clearColour, m_configured, CBaseRenderer::ManageRenderArea(), Render(), and VerifyGLState.
Supports() [1/2]
bool CRendererDRMPRIMEGLES::Supports (ERENDERFEATURE feature) const override virtual
Reimplemented from CBaseRenderer.
References RENDERFEATURE_PIXEL_RATIO, RENDERFEATURE_ROTATION, RENDERFEATURE_STRETCH, RENDERFEATURE_VERTICAL_SHIFT, and RENDERFEATURE_ZOOM.
Supports() [2/2]
bool CRendererDRMPRIMEGLES::Supports (ESCALINGMETHOD method) const override virtual
Implements CBaseRenderer.
References VS_SCALINGMETHOD_LINEAR.
SupportsMultiPassRendering()
bool CRendererDRMPRIMEGLES::SupportsMultiPassRendering () inline override virtual
Implements CBaseRenderer.
UnInit()
void CRendererDRMPRIMEGLES::UnInit () inline override virtual
Implements CBaseRenderer.
Update()
void CRendererDRMPRIMEGLES::Update () override virtual
Implements CBaseRenderer.
References m_configured, and CBaseRenderer::ManageRenderArea().
Member Data Documentation
m_buffers
struct CRendererDRMPRIMEGLES::BUFFER CRendererDRMPRIMEGLES::m_buffers[NUM_BUFFERS] private
Referenced by AddVideoPicture(), Configure(), NeedBuffer(), ReleaseBuffer(), and Render().
m_clearColour
float CRendererDRMPRIMEGLES::m_clearColour {0.0f} private
Referenced by Configure(), DrawBlackBars(), and RenderUpdate().
m_configured
bool CRendererDRMPRIMEGLES::m_configured = false private
Referenced by Configure(), IsConfigured(), RenderUpdate(), and Update().
The documentation for this class was generated from the following files:
RendererDRMPRIMEGLES.h
RendererDRMPRIMEGLES.cpp