Kodi Documentation: class PVRSignalStatus
class PVRSignalStatus
C++ » Interface - kodi::addon » Addon type instances » PVR » Definitions, structures and enumerators » 2. Channel
PVR Signal status information
This class gives current status information from stream to Kodi.
Modules
Value Help
Classes
class kodi::addon::PVRSignalStatus
Functions
void kodi::addon::PVRSignalStatus::SetAdapterName (const std::string &adapterName)
optional
Name of the adapter that's being used.
std::string kodi::addon::PVRSignalStatus::GetAdapterName () const
To get with SetAdapterName changed values.
void kodi::addon::PVRSignalStatus::SetAdapterStatus (const std::string &adapterStatus)
optional
Status of the adapter that's being used.
std::string kodi::addon::PVRSignalStatus::GetAdapterStatus () const
To get with SetAdapterStatus changed values.
void kodi::addon::PVRSignalStatus::SetServiceName (const std::string &serviceName)
optional
Name of the current service.
std::string kodi::addon::PVRSignalStatus::GetServiceName () const
To get with SetServiceName changed values.
void kodi::addon::PVRSignalStatus::SetProviderName (const std::string &providerName)
optional
Name of the current service's provider.
std::string kodi::addon::PVRSignalStatus::GetProviderName () const
To get with SetProviderName changed values.
void kodi::addon::PVRSignalStatus::SetMuxName (const std::string &muxName)
optional
Name of the current mux.
std::string kodi::addon::PVRSignalStatus::GetMuxName () const
To get with SetMuxName changed values.
void kodi::addon::PVRSignalStatus::SetSNR (int snr)
optional
Signal/noise ratio.
int kodi::addon::PVRSignalStatus::GetSNR () const
To get with SetSNR changed values.
void kodi::addon::PVRSignalStatus::SetSignal (int signal)
optional
Signal strength.
int kodi::addon::PVRSignalStatus::GetSignal () const
To get with SetSignal changed values.
void kodi::addon::PVRSignalStatus::SetBER (long ber)
optional
Bit error rate.
long kodi::addon::PVRSignalStatus::GetBER () const
To get with SetBER changed values.
void kodi::addon::PVRSignalStatus::SetUNC (long unc)
optional
Uncorrected blocks:
long kodi::addon::PVRSignalStatus::GetUNC () const
To get with SetBER changed values.
Detailed Description
PVR Signal status information
This class gives current status information from stream to Kodi.
Used to get information for user by call of kodi::addon::CInstancePVRClient::GetSignalStatus() to see current quality and source.
The following table contains values that can be set with class PVRSignalStatus :
Name Type Set call Get call Usage
Adapter name std::string SetAdapterName GetAdapterName optional
Adapter status std::string SetAdapterStatus GetAdapterStatus optional
Service name std::string SetServiceName GetServiceName optional
Provider name std::string SetProviderName GetProviderName optional
Mux name std::string SetMuxName GetMuxName optional
Signal/noise ratio int SetSNR GetSNR optional
Signal strength int SetSignal GetSignal optional
Bit error rate long SetBER GetBER optional
Uncorrected blocks long SetUNC GetUNC optional
Function Documentation
GetAdapterName()
std::string kodi::addon::PVRSignalStatus::GetAdapterName () const inline
To get with SetAdapterName changed values.
References kodi::addon::DynamicCStructHdl< PVRSignalStatus, PVR_SIGNAL_STATUS >::m_cStructure, and PVR_SIGNAL_STATUS::strAdapterName.
GetAdapterStatus()
std::string kodi::addon::PVRSignalStatus::GetAdapterStatus () const inline
To get with SetAdapterStatus changed values.
References kodi::addon::DynamicCStructHdl< PVRSignalStatus, PVR_SIGNAL_STATUS >::m_cStructure, and PVR_SIGNAL_STATUS::strAdapterStatus.
GetBER()
long kodi::addon::PVRSignalStatus::GetBER () const inline
To get with SetBER changed values.
References PVR_SIGNAL_STATUS::iBER, and kodi::addon::DynamicCStructHdl< PVRSignalStatus, PVR_SIGNAL_STATUS >::m_cStructure.
GetMuxName()
std::string kodi::addon::PVRSignalStatus::GetMuxName () const inline
To get with SetMuxName changed values.
References kodi::addon::DynamicCStructHdl< PVRSignalStatus, PVR_SIGNAL_STATUS >::m_cStructure, and PVR_SIGNAL_STATUS::strMuxName.
GetProviderName()
std::string kodi::addon::PVRSignalStatus::GetProviderName () const inline
To get with SetProviderName changed values.
References kodi::addon::DynamicCStructHdl< PVRSignalStatus, PVR_SIGNAL_STATUS >::m_cStructure, and PVR_SIGNAL_STATUS::strProviderName.
GetServiceName()
std::string kodi::addon::PVRSignalStatus::GetServiceName () const inline
To get with SetServiceName changed values.
References kodi::addon::DynamicCStructHdl< PVRSignalStatus, PVR_SIGNAL_STATUS >::m_cStructure, and PVR_SIGNAL_STATUS::strServiceName.
GetSignal()
int kodi::addon::PVRSignalStatus::GetSignal () const inline
To get with SetSignal changed values.
References PVR_SIGNAL_STATUS::iSignal, and kodi::addon::DynamicCStructHdl< PVRSignalStatus, PVR_SIGNAL_STATUS >::m_cStructure.
GetSNR()
int kodi::addon::PVRSignalStatus::GetSNR () const inline
To get with SetSNR changed values.
References PVR_SIGNAL_STATUS::iSNR, and kodi::addon::DynamicCStructHdl< PVRSignalStatus, PVR_SIGNAL_STATUS >::m_cStructure.
GetUNC()
long kodi::addon::PVRSignalStatus::GetUNC () const inline
To get with SetBER changed values.
References PVR_SIGNAL_STATUS::iUNC, and kodi::addon::DynamicCStructHdl< PVRSignalStatus, PVR_SIGNAL_STATUS >::m_cStructure.
SetAdapterName()
void kodi::addon::PVRSignalStatus::SetAdapterName (const std::string & adapterName) inline
optional
Name of the adapter that's being used.
References kodi::addon::DynamicCStructHdl< PVRSignalStatus, PVR_SIGNAL_STATUS >::m_cStructure, kodi::addon::ReallocAndCopyString(), and PVR_SIGNAL_STATUS::strAdapterName.
SetAdapterStatus()
void kodi::addon::PVRSignalStatus::SetAdapterStatus (const std::string & adapterStatus) inline
optional
Status of the adapter that's being used.
References kodi::addon::DynamicCStructHdl< PVRSignalStatus, PVR_SIGNAL_STATUS >::m_cStructure, kodi::addon::ReallocAndCopyString(), and PVR_SIGNAL_STATUS::strAdapterStatus.
SetBER()
void kodi::addon::PVRSignalStatus::SetBER (long ber) inline
optional
Bit error rate.
References PVR_SIGNAL_STATUS::iBER, and kodi::addon::DynamicCStructHdl< PVRSignalStatus, PVR_SIGNAL_STATUS >::m_cStructure.
SetMuxName()
void kodi::addon::PVRSignalStatus::SetMuxName (const std::string & muxName) inline
optional
Name of the current mux.
References kodi::addon::DynamicCStructHdl< PVRSignalStatus, PVR_SIGNAL_STATUS >::m_cStructure, kodi::addon::ReallocAndCopyString(), and PVR_SIGNAL_STATUS::strMuxName.
SetProviderName()
void kodi::addon::PVRSignalStatus::SetProviderName (const std::string & providerName) inline
optional
Name of the current service's provider.
References kodi::addon::DynamicCStructHdl< PVRSignalStatus, PVR_SIGNAL_STATUS >::m_cStructure, kodi::addon::ReallocAndCopyString(), and PVR_SIGNAL_STATUS::strProviderName.
SetServiceName()
void kodi::addon::PVRSignalStatus::SetServiceName (const std::string & serviceName) inline
optional
Name of the current service.
References kodi::addon::DynamicCStructHdl< PVRSignalStatus, PVR_SIGNAL_STATUS >::m_cStructure, kodi::addon::ReallocAndCopyString(), and PVR_SIGNAL_STATUS::strServiceName.
SetSignal()
void kodi::addon::PVRSignalStatus::SetSignal (int signal) inline
optional
Signal strength.
Note
100% is 0xFFFF 65535
References PVR_SIGNAL_STATUS::iSignal, and kodi::addon::DynamicCStructHdl< PVRSignalStatus, PVR_SIGNAL_STATUS >::m_cStructure.
SetSNR()
void kodi::addon::PVRSignalStatus::SetSNR (int snr) inline
optional
Signal/noise ratio.
Note
100% is 0xFFFF 65535
References PVR_SIGNAL_STATUS::iSNR, and kodi::addon::DynamicCStructHdl< PVRSignalStatus, PVR_SIGNAL_STATUS >::m_cStructure.
SetUNC()
void kodi::addon::PVRSignalStatus::SetUNC (long unc) inline
optional
Uncorrected blocks:
References PVR_SIGNAL_STATUS::iUNC, and kodi::addon::DynamicCStructHdl< PVRSignalStatus, PVR_SIGNAL_STATUS >::m_cStructure.