Kodi Documentation: CZeroconf Class Reference
CZeroconf Class Reference abstract
#include <Zeroconf.h>
Classes
class CPublish
struct PublishInfo
Public Member Functions
bool PublishService (const std::string &fcr_identifier, const std::string &fcr_type, const std::string &fcr_name, unsigned int f_port, std::vector< std::pair< std::string, std::string > > txt)
bool ForceReAnnounceService (const std::string &fcr_identifier)
bool RemoveService (const std::string &fcr_identifier)
bool HasService (const std::string &fcr_identifier) const
returns true if fcr_identifier exists
bool Start ()
void Stop ()
virtual void ProcessResults ()
bool IsStarted ()
Static Public Member Functions
static CZeroconf * GetInstance ()
static void ReleaseInstance ()
static bool IsInstantiated ()
Protected Member Functions
virtual bool doPublishService (const std::string &fcr_identifier, const std::string &fcr_type, const std::string &fcr_name, unsigned int f_port, const std::vector< std::pair< std::string, std::string > > &txt)=0
virtual bool doForceReAnnounceService (const std::string &fcr_identifier)=0
virtual bool doRemoveService (const std::string &fcr_ident)=0
virtual void doStop ()=0
virtual bool IsZCdaemonRunning ()
CZeroconf ()
CZeroconf (const CZeroconf &)
virtual ~CZeroconf ()
Private Types
typedef std::map< std::string, PublishInfo > tServiceMap
Private Attributes
CCriticalSection * mp_crit_sec
tServiceMap m_service_map
bool m_started = false
Static Private Attributes
static CZeroconf * smp_instance = 0
Detailed Description
this class provides support for zeroconf while the different zeroconf implementations have asynchronous APIs this class hides it and provides only few ways to interact with the services. If more control is needed, feel free to add it. The main purpose currently is to provide an easy way to publish services in the different StartXXX/StopXXX methods in CApplication
Todo:
Make me safe for use in static initialization. CritSec is a static member :/ use e.g. loki's singleton implementation to make do it properly
Member Typedef Documentation
tServiceMap
typedef std::map<std::string, PublishInfo> CZeroconf::tServiceMap private
Constructor & Destructor Documentation
CZeroconf() [1/2]
CZeroconf::CZeroconf () protected
CZeroconf() [2/2]
CZeroconf::CZeroconf (const CZeroconf &) protected
~CZeroconf()
CZeroconf::~CZeroconf () protected virtual
References mp_crit_sec.
Member Function Documentation
doForceReAnnounceService()
virtual bool CZeroconf::doForceReAnnounceService (const std::string & fcr_identifier) protected pure virtual
Implemented in CZeroconfDummy, CZeroconfMDNS, CZeroconfAndroid, CZeroconfDarwin, and CZeroconfAvahi.
Referenced by ForceReAnnounceService().
doPublishService()
virtual bool CZeroconf::doPublishService (const std::string & fcr_identifier, const std::string & fcr_type, const std::string & fcr_name, unsigned int f_port, const std::vector< std::pair< std::string, std::string > > & txt) protected pure virtual
Implemented in CZeroconfDummy, CZeroconfMDNS, CZeroconfAndroid, CZeroconfDarwin, and CZeroconfAvahi.
Referenced by CZeroconf::CPublish::DoWork().
doRemoveService()
virtual bool CZeroconf::doRemoveService (const std::string & fcr_ident) protected pure virtual
Implemented in CZeroconfMDNS, CZeroconfDummy, CZeroconfAndroid, CZeroconfDarwin, and CZeroconfAvahi.
Referenced by RemoveService().
doStop()
virtual void CZeroconf::doStop () protected pure virtual
Implemented in CZeroconfMDNS, CZeroconfDummy, CZeroconfAndroid, CZeroconfDarwin, and CZeroconfAvahi.
Referenced by Stop().
ForceReAnnounceService()
bool CZeroconf::ForceReAnnounceService (const std::string & fcr_identifier)
References doForceReAnnounceService(), HasService(), and m_started.
Referenced by handleZeroconfAnnouncement().
GetInstance()
CZeroconf * CZeroconf::GetInstance () static
References smp_instance.
Referenced by CZeroconf::CPublish::DoWork(), handleZeroconfAnnouncement(), CNetworkServices::IsZeroconfRunning(), EVENTSERVER::CEventServer::Run(), CNetworkServices::StartAirPlayServer(), CNetworkServices::StartJSONRPCServer(), CAirTunesServer::StartServer(), CNetworkServices::StartWebserver(), CNetworkServices::StartZeroconf(), CNetworkServices::StopAirPlayServer(), CNetworkServices::StopJSONRPCServer(), CAirTunesServer::StopServer(), EVENTSERVER::CEventServer::StopServer(), CNetworkServices::StopWebserver(), CNetworkServices::StopZeroconf(), and CWinEventsWin32::WndProc().
HasService()
bool CZeroconf::HasService (const std::string & fcr_identifier) const
returns true if fcr_identifier exists
References m_service_map.
Referenced by ForceReAnnounceService().
IsInstantiated()
static bool CZeroconf::IsInstantiated () inline static
References smp_instance.
IsStarted()
bool CZeroconf::IsStarted () inline
References m_started.
Referenced by CNetworkServices::IsZeroconfRunning().
IsZCdaemonRunning()
virtual bool CZeroconf::IsZCdaemonRunning () inline protected virtual
Reimplemented in CZeroconfMDNS.
Referenced by Start().
ProcessResults()
virtual void CZeroconf::ProcessResults () inline virtual
Reimplemented in CZeroconfMDNS.
Referenced by CWinEventsWin32::WndProc().
PublishService()
bool CZeroconf::PublishService (const std::string & fcr_identifier, const std::string & fcr_type, const std::string & fcr_name, unsigned int f_port, std::vector< std::pair< std::string, std::string > > txt)
References CServiceBroker::GetJobManager(), m_service_map, m_started, and mp_crit_sec.
Referenced by EVENTSERVER::CEventServer::Run(), CNetworkServices::StartAirPlayServer(), CNetworkServices::StartJSONRPCServer(), CAirTunesServer::StartServer(), and CNetworkServices::StartWebserver().
ReleaseInstance()
void CZeroconf::ReleaseInstance () static
References smp_instance.
RemoveService()
bool CZeroconf::RemoveService (const std::string & fcr_identifier)
removes the specified service returns false if fcr_identifier does not exist
References doRemoveService(), m_service_map, m_started, and mp_crit_sec.
Referenced by CNetworkServices::StopAirPlayServer(), CNetworkServices::StopJSONRPCServer(), CAirTunesServer::StopServer(), EVENTSERVER::CEventServer::StopServer(), and CNetworkServices::StopWebserver().
Start()
bool CZeroconf::Start ()
References CServiceBroker::GetJobManager(), CServiceBroker::GetSettingsComponent(), IsZCdaemonRunning(), m_service_map, m_started, mp_crit_sec, CSettings::SETTING_SERVICES_AIRPLAY, and CSettings::SETTING_SERVICES_ZEROCONF.
Referenced by CNetworkServices::StartZeroconf().
Stop()
void CZeroconf::Stop ()
References doStop(), m_started, and mp_crit_sec.
Referenced by CNetworkServices::StopZeroconf().
Member Data Documentation
m_service_map
tServiceMap CZeroconf::m_service_map private
Referenced by HasService(), PublishService(), RemoveService(), and Start().
m_started
bool CZeroconf::m_started = false private
Referenced by ForceReAnnounceService(), IsStarted(), PublishService(), RemoveService(), Start(), and Stop().
mp_crit_sec
CCriticalSection* CZeroconf::mp_crit_sec private
Referenced by PublishService(), RemoveService(), Start(), Stop(), and ~CZeroconf().
smp_instance
CZeroconf * CZeroconf::smp_instance = 0 static private
Referenced by GetInstance(), IsInstantiated(), and ReleaseInstance().
The documentation for this class was generated from the following files:
Zeroconf.h
Zeroconf.cpp