Kodi Documentation: JSONRPC::CTextureOperations Class Reference
JSONRPC::CTextureOperations Class Reference
#include <TextureOperations.h>
Static Public Member Functions
static JSONRPC_STATUS GetTextures (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS RemoveTexture (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
Member Function Documentation
GetTextures()
JSONRPC_STATUS CTextureOperations::GetTextures (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CDatabase::Filter::AppendWhere(), CVariant::asString(), CVariant::begin_array(), CVariant::begin_map(), CVariant::empty(), CVariant::end_array(), CVariant::end_map(), CVariant::erase(), fields, CTextureDatabase::GetTextures(), CDatabaseQueryRuleCombination::GetWhereClause(), JSONRPC::InternalError, JSONRPC::InvalidParams, CVariant::isArray(), CVariant::isMember(), CVariant::isObject(), CDatabaseQueryRuleCombination::Load(), JSONRPC::OK, CTextureDatabase::Open(), CVariant::push_back(), IMAGE_FILES::URLFromFile(), CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
RemoveTexture()
JSONRPC_STATUS CTextureOperations::RemoveTexture (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CServiceBroker::GetTextureCache(), and JSONRPC::InvalidParams.
The documentation for this class was generated from the following files:
TextureOperations.h
TextureOperations.cpp