Kodi Documentation: PVR::CPVRItem Class Reference
PVR::CPVRItem Class Reference
#include <PVRItem.h>
Public Member Functions
CPVRItem (const std::shared_ptr< CFileItem > &item)
CPVRItem (const CFileItem *item)
CPVRItem (const CFileItem &item)
std::shared_ptr< CPVREpgInfoTag > GetEpgInfoTag () const
std::shared_ptr< CPVREpgInfoTag > GetNextEpgInfoTag () const
std::shared_ptr< CPVRChannel > GetChannel () const
std::shared_ptr< CPVRTimerInfoTag > GetTimerInfoTag () const
std::shared_ptr< CPVRRecording > GetRecording () const
bool IsRadio () const
Private Attributes
const CFileItem * m_item
Constructor & Destructor Documentation
CPVRItem() [1/3]
PVR::CPVRItem::CPVRItem (const std::shared_ptr< CFileItem > & item) inline explicit
CPVRItem() [2/3]
PVR::CPVRItem::CPVRItem (const CFileItem * item) inline explicit
CPVRItem() [3/3]
PVR::CPVRItem::CPVRItem (const CFileItem & item) inline explicit
Member Function Documentation
GetChannel()
std::shared_ptr< CPVRChannel > PVR::CPVRItem::GetChannel () const
References PVR::CPVRManager::ChannelGroups(), CFileItem::GetDynPath(), CFileItem::GetEPGInfoTag(), CFileItem::GetPVRChannelInfoTag(), CServiceBroker::GetPVRManager(), CFileItem::GetPVRRecordingInfoTag(), CFileItem::GetPVRTimerInfoTag(), CFileItem::IsEPG(), URIUtils::IsPVR(), CFileItem::IsPVRChannel(), CFileItem::IsPVRRecording(), CFileItem::IsPVRTimer(), LOGERROR, and m_item.
Referenced by PVR::CPVRGUIInfo::GetListItemAndPlayerBool(), PVR::CPVRGUIInfo::GetListItemAndPlayerLabel(), and PVR::CGUIWindowPVRGuideBase::OnMessage().
GetEpgInfoTag()
std::shared_ptr< CPVREpgInfoTag > PVR::CPVRItem::GetEpgInfoTag () const
References CFileItem::GetDynPath(), CFileItem::GetEPGInfoTag(), CFileItem::GetPVRChannelInfoTag(), CFileItem::GetPVRTimerInfoTag(), CFileItem::IsEPG(), URIUtils::IsPVR(), CFileItem::IsPVRChannel(), CFileItem::IsPVRTimer(), LOGERROR, and m_item.
Referenced by PVR::CPVRGUIActionsTimers::AddReminder(), PVR::CPVRGUIActionsTimers::AddTimer(), PVR::CPVRGUIInfo::GetFallbackLabel(), PVR::CPVRGUIInfo::GetListItemAndPlayerBool(), PVR::CPVRGUIInfo::GetListItemAndPlayerInt(), PVR::CPVRGUIInfo::GetListItemAndPlayerLabel(), PVR::CPVRGUIInfo::GetPVRInt(), and PVR::CPVRGUIInfo::GetPVRLabel().
GetNextEpgInfoTag()
std::shared_ptr< CPVREpgInfoTag > PVR::CPVRItem::GetNextEpgInfoTag () const
References PVR::CPVRManager::ChannelGroups(), CFileItem::GetDynPath(), CFileItem::GetEPGInfoTag(), CFileItem::GetPVRChannelInfoTag(), CServiceBroker::GetPVRManager(), CFileItem::GetPVRTimerInfoTag(), CFileItem::IsEPG(), URIUtils::IsPVR(), CFileItem::IsPVRChannel(), CFileItem::IsPVRTimer(), LOGERROR, and m_item.
Referenced by PVR::CPVRGUIInfo::GetListItemAndPlayerLabel().
GetRecording()
std::shared_ptr< CPVRRecording > PVR::CPVRItem::GetRecording () const
References CFileItem::GetDynPath(), CFileItem::GetEPGInfoTag(), CServiceBroker::GetPVRManager(), CFileItem::GetPVRRecordingInfoTag(), CFileItem::IsEPG(), URIUtils::IsPVR(), CFileItem::IsPVRRecording(), LOGERROR, m_item, and PVR::CPVRManager::Recordings().
Referenced by PVR::CPVRGUIActionsRecordings::EditRecording(), and PVR::CGUIDialogPVRGuideInfo::OnClickButtonPlay().
GetTimerInfoTag()
std::shared_ptr< CPVRTimerInfoTag > PVR::CPVRItem::GetTimerInfoTag () const
References CFileItem::GetDynPath(), CFileItem::GetEPGInfoTag(), CFileItem::GetPVRChannelInfoTag(), CServiceBroker::GetPVRManager(), CFileItem::GetPVRTimerInfoTag(), CFileItem::IsEPG(), URIUtils::IsPVR(), CFileItem::IsPVRChannel(), CFileItem::IsPVRTimer(), LOGERROR, m_item, and PVR::CPVRManager::Timers().
Referenced by PVR::CPVRGUIActionsTimers::DeleteTimer(), and PVR::CPVRGUIInfo::GetListItemAndPlayerBool().
IsRadio()
bool PVR::CPVRItem::IsRadio () const
References CFileItem::GetDynPath(), CFileItem::GetEPGInfoTag(), CFileItem::GetPVRChannelInfoTag(), CFileItem::GetPVRRecordingInfoTag(), CFileItem::GetPVRTimerInfoTag(), CFileItem::IsEPG(), URIUtils::IsPVR(), CFileItem::IsPVRChannel(), CFileItem::IsPVRRecording(), CFileItem::IsPVRTimer(), LOGERROR, and m_item.
Member Data Documentation
m_item
const CFileItem* PVR::CPVRItem::m_item private
Referenced by GetChannel(), GetEpgInfoTag(), GetNextEpgInfoTag(), GetRecording(), GetTimerInfoTag(), and IsRadio().
The documentation for this class was generated from the following files:
PVRItem.h
PVRItem.cpp