Kodi Documentation: CRenderSystemBase Class Reference
CRenderSystemBase Class Reference abstract
#include <RenderSystem.h>
Public Member Functions
CRenderSystemBase ()
virtual ~CRenderSystemBase ()
virtual bool InitRenderSystem ()=0
virtual bool DestroyRenderSystem ()=0
virtual bool ResetRenderSystem (int width, int height)=0
virtual bool BeginRender ()=0
virtual bool EndRender ()=0
virtual void PresentRender (bool rendered, bool videoLayer)=0
virtual void InvalidateColorBuffer ()
virtual bool ClearBuffers (KODI::UTILS::COLOR::Color color)=0
virtual bool IsExtSupported (const char *extension) const =0
virtual void SetViewPort (const CRect &viewPort)=0
virtual void GetViewPort (CRect &viewPort)=0
virtual void RestoreViewPort ()
virtual bool ScissorsCanEffectClipping ()
virtual CRect ClipRectToScissorRect (const CRect &rect)
virtual void SetScissors (const CRect &rect)=0
virtual void ResetScissors ()=0
virtual void SetDepthCulling (DEPTH_CULLING culling)
virtual void CaptureStateBlock ()=0
virtual void ApplyStateBlock ()=0
virtual void SetCameraPosition (const CPoint &camera, int screenWidth, int screenHeight, float stereoFactor=0.f)=0
virtual void SetStereoMode (RENDER_STEREO_MODE mode, RENDER_STEREO_VIEW view)
virtual void Project (float &x, float &y, float &z)
virtual std::string GetShaderPath (const std::string &filename)
void GetRenderVersion (unsigned int &major, unsigned int &minor) const
const std::string & GetRenderVendor () const
const std::string & GetRenderRenderer () const
const std::string & GetRenderVersionString () const
virtual bool SupportsNPOT (bool dxt) const
virtual bool SupportsStereo (RENDER_STEREO_MODE mode) const
unsigned int GetMaxTextureSize () const
unsigned int GetMinDXTPitch () const
virtual void ShowSplash (const std::string &message)
Protected Attributes
bool m_bRenderCreated
bool m_bVSync
unsigned int m_maxTextureSize
unsigned int m_minDXTPitch
std::string m_RenderRenderer
std::string m_RenderVendor
std::string m_RenderVersion
int m_RenderVersionMinor
int m_RenderVersionMajor
RENDER_STEREO_VIEW m_stereoView = RENDER_STEREO_VIEW_OFF
RENDER_STEREO_MODE m_stereoMode = RENDER_STEREO_MODE_OFF
bool m_limitedColorRange = false
bool m_transferPQ {false}
std::unique_ptr< CGUIImage > m_splashImage
std::unique_ptr< CGUITextLayout > m_splashMessageLayout
Constructor & Destructor Documentation
CRenderSystemBase()
CRenderSystemBase::CRenderSystemBase ()
References m_bRenderCreated, m_bVSync, m_maxTextureSize, m_minDXTPitch, m_RenderVersionMajor, and m_RenderVersionMinor.
~CRenderSystemBase()
CRenderSystemBase::~CRenderSystemBase () virtual default
Member Function Documentation
ApplyStateBlock()
virtual void CRenderSystemBase::ApplyStateBlock () pure virtual
Implemented in CRenderSystemDX, CRenderSystemGL, and CRenderSystemGLES.
Referenced by KODI::RETRO::CRenderContext::ApplyStateBlock(), and CGraphicContext::ApplyStateBlock().
BeginRender()
virtual bool CRenderSystemBase::BeginRender () pure virtual
Implemented in CRenderSystemDX, CRenderSystemGL, CRenderSystemGLES, CWinSystemIOS, and CWinSystemTVOS.
Referenced by ShowSplash().
CaptureStateBlock()
virtual void CRenderSystemBase::CaptureStateBlock () pure virtual
Implemented in CRenderSystemDX, CRenderSystemGL, and CRenderSystemGLES.
Referenced by CGraphicContext::CaptureStateBlock().
ClearBuffers()
virtual bool CRenderSystemBase::ClearBuffers (KODI::UTILS::COLOR::Color color) pure virtual
Implemented in CRenderSystemDX, CRenderSystemGL, and CRenderSystemGLES.
ClipRectToScissorRect()
virtual CRect CRenderSystemBase::ClipRectToScissorRect (const CRect & rect) inline virtual
Reimplemented in CRenderSystemDX, CRenderSystemGL, and CRenderSystemGLES.
DestroyRenderSystem()
virtual bool CRenderSystemBase::DestroyRenderSystem () pure virtual
Implemented in CRenderSystemDX, CRenderSystemGL, CRenderSystemGLES, CWinSystemWin10DX, and CWinSystemWin32DX.
Referenced by CApplication::Cleanup().
EndRender()
virtual bool CRenderSystemBase::EndRender () pure virtual
Implemented in CRenderSystemDX, CRenderSystemGL, CRenderSystemGLES, CWinSystemIOS, and CWinSystemTVOS.
Referenced by CApplication::Render(), and ShowSplash().
GetMaxTextureSize()
unsigned int CRenderSystemBase::GetMaxTextureSize () const inline
References m_maxTextureSize.
Referenced by CGUIFontTTF::CacheCharacter(), CGUIWindowSlideShow::GetCheckedSize(), CGUIFontTTF::Load(), CTexture::LoadFromFileInMem(), CTexture::LoadFromFileInternal(), CGLTexture::LoadToGPU(), CGLESTexture::LoadToGPU(), and CBackgroundPicLoader::Process().
GetMinDXTPitch()
unsigned int CRenderSystemBase::GetMinDXTPitch () const inline
References m_minDXTPitch.
GetRenderRenderer()
const std::string & CRenderSystemBase::GetRenderRenderer () const inline
References m_RenderRenderer.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), and CSysInfoJob::GetVideoEncoder().
GetRenderVendor()
const std::string & CRenderSystemBase::GetRenderVendor () const inline
References m_RenderVendor.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), VDPAU::CDecoder::Open(), and VDPAU::CDecoder::Register().
GetRenderVersion()
void CRenderSystemBase::GetRenderVersion (unsigned int & major, unsigned int & minor) const
References m_RenderVersionMajor, and m_RenderVersionMinor.
Referenced by CRenderCaptureGL::BeginRender(), CGLESTexture::CGLESTexture(), CGLTexture::CGLTexture(), CGUIFontTTFGL::FirstBegin(), CLinuxRendererGL::GetInternalFormat(), LogGraphicsInfo(), CLinuxRendererGL::Supports(), CLinuxRendererGLES::Supports(), and CLinuxRendererGL::UpdateVideoFilter().
GetRenderVersionString()
const std::string & CRenderSystemBase::GetRenderVersionString () const inline
References m_RenderVersion.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel().
GetShaderPath()
virtual std::string CRenderSystemBase::GetShaderPath (const std::string & filename) inline virtual
Reimplemented in CRenderSystemGL, and CRenderSystemGLES.
Referenced by Shaders::CShader::AppendSource(), Shaders::CShader::InsertSource(), and Shaders::CShader::LoadSource().
GetViewPort()
virtual void CRenderSystemBase::GetViewPort (CRect & viewPort) pure virtual
Implemented in CRenderSystemDX, CRenderSystemGL, and CRenderSystemGLES.
Referenced by KODI::RETRO::CRenderContext::GetViewPort(), CGLShader::OnEnabled(), and CGLESShader::OnEnabled().
InitRenderSystem()
virtual bool CRenderSystemBase::InitRenderSystem () pure virtual
Implemented in CRenderSystemDX, CRenderSystemGL, and CRenderSystemGLES.
InvalidateColorBuffer()
virtual void CRenderSystemBase::InvalidateColorBuffer () inline virtual
Reimplemented in CRenderSystemGL, and CRenderSystemGLES.
Referenced by CGraphicContext::Clear().
IsExtSupported()
virtual bool CRenderSystemBase::IsExtSupported (const char * extension) const pure virtual
Implemented in CRenderSystemDX, CRenderSystemGL, CRenderSystemGLES, CWinSystemIOS, CWinSystemTVOS, KODI::WINDOWING::X11::CWinSystemX11GLContext, and KODI::WINDOWING::X11::CWinSystemX11GLESContext.
Referenced by CLinuxRendererGL::Configure(), Shaders::GL::ConvolutionFilterShader::ConvolutionFilterShader(), and KODI::RETRO::CRenderContext::IsExtSupported().
PresentRender()
virtual void CRenderSystemBase::PresentRender (bool rendered, bool videoLayer) pure virtual
Implemented in CRenderSystemDX, CRenderSystemGL, CRenderSystemGLES, KODI::WINDOWING::GBM::CWinSystemGbmGLContext, and KODI::WINDOWING::GBM::CWinSystemGbmGLESContext.
Referenced by CGraphicContext::Flip().
Project()
virtual void CRenderSystemBase::Project (float & x, float & y, float & z) inline virtual
Project (x,y,z) 3d scene coordinates to (x,y) 2d screen coordinates
Reimplemented in CRenderSystemDX, CRenderSystemGL, and CRenderSystemGLES.
Referenced by CGraphicContext::GenerateAABB().
ResetRenderSystem()
virtual bool CRenderSystemBase::ResetRenderSystem (int width, int height) pure virtual
Implemented in CRenderSystemDX, CRenderSystemGL, and CRenderSystemGLES.
ResetScissors()
virtual void CRenderSystemBase::ResetScissors () pure virtual
Implemented in CRenderSystemDX, CRenderSystemGL, and CRenderSystemGLES.
RestoreViewPort()
virtual void CRenderSystemBase::RestoreViewPort () inline virtual
Reimplemented in CRenderSystemDX.
ScissorsCanEffectClipping()
virtual bool CRenderSystemBase::ScissorsCanEffectClipping () inline virtual
Reimplemented in CRenderSystemDX, CRenderSystemGL, and CRenderSystemGLES.
Referenced by CGUIFontTTF::DrawTextInternal(), and CGUIFontTTF::RenderCharacter().
SetCameraPosition()
virtual void CRenderSystemBase::SetCameraPosition (const CPoint & camera, int screenWidth, int screenHeight, float stereoFactor = 0.f) pure virtual
Implemented in CRenderSystemGL, CRenderSystemGLES, and CRenderSystemDX.
Referenced by CGraphicContext::UpdateCameraPosition().
SetDepthCulling()
virtual void CRenderSystemBase::SetDepthCulling (DEPTH_CULLING culling) inline virtual
Reimplemented in CRenderSystemGL, and CRenderSystemGLES.
Referenced by CGraphicContext::SetRenderOrder().
SetScissors()
virtual void CRenderSystemBase::SetScissors (const CRect & rect) pure virtual
Implemented in CRenderSystemDX, CRenderSystemGL, and CRenderSystemGLES.
Referenced by CGraphicContext::ResetScissors(), KODI::RETRO::CRenderContext::SetScissors(), CGraphicContext::SetScissors(), and CGraphicContext::SetStereoView().
SetStereoMode()
virtual void CRenderSystemBase::SetStereoMode (RENDER_STEREO_MODE mode, RENDER_STEREO_VIEW view) inline virtual
Reimplemented in CRenderSystemDX, and CRenderSystemGL.
References m_stereoMode, and m_stereoView.
Referenced by CRenderSystemDX::SetStereoMode(), CRenderSystemGL::SetStereoMode(), and CGraphicContext::SetStereoView().
SetViewPort()
virtual void CRenderSystemBase::SetViewPort (const CRect & viewPort) pure virtual
Implemented in CRenderSystemDX, CRenderSystemGL, and CRenderSystemGLES.
Referenced by CGraphicContext::RestoreViewPort(), CGraphicContext::SetStereoView(), KODI::RETRO::CRenderContext::SetViewPort(), and CGraphicContext::SetViewPort().
ShowSplash()
void CRenderSystemBase::ShowSplash (const std::string & message) virtual
Reimplemented in CWinSystemWin10DX.
References CAspectRatio::AR_SCALE, BeginRender(), CGraphicContext::Clear(), EndRender(), CGraphicContext::Flip(), FONT_STYLE_NORMAL, g_fontManager, CWinSystemBase::GetGfxContext(), CGraphicContext::GetHeight(), CGraphicContext::GetResInfo(), CServiceBroker::GetSettingsComponent(), CUtil::GetSplashPath(), CGraphicContext::GetWidth(), CServiceBroker::GetWinSystem(), m_splashImage, m_splashMessageLayout, CGraphicContext::SetRenderingResolution(), and XBFONT_CENTER_X.
Referenced by CApplication::CreateGUI(), CApplication::Initialize(), and CWinSystemWin10DX::ShowSplash().
SupportsNPOT()
bool CRenderSystemBase::SupportsNPOT (bool dxt) const virtual
Reimplemented in CRenderSystemDX, and CRenderSystemGL.
SupportsStereo()
bool CRenderSystemBase::SupportsStereo (RENDER_STEREO_MODE mode) const virtual
Reimplemented in CRenderSystemDX, CRenderSystemGL, and CRenderSystemGLES.
References RENDER_STEREO_MODE_MONO, RENDER_STEREO_MODE_OFF, RENDER_STEREO_MODE_SPLIT_HORIZONTAL, and RENDER_STEREO_MODE_SPLIT_VERTICAL.
Referenced by CStereoscopicsManager::GetNextSupportedStereoMode(), CStereoscopicsManager::GetStereoModeByUserChoice(), JSONRPC::CGUIOperations::GetStereoscopicModes(), CStereoscopicsManager::OnStreamChange(), CDisplaySettings::SettingOptionsPreferredStereoscopicViewModesFiller(), CDisplaySettings::SettingOptionsStereoscopicModesFiller(), CRenderSystemDX::SupportsStereo(), CRenderSystemGL::SupportsStereo(), and CRenderSystemGLES::SupportsStereo().
Member Data Documentation
m_bRenderCreated
bool CRenderSystemBase::m_bRenderCreated protected
Referenced by CRenderSystemDX::ApplyStateBlock(), CRenderSystemGL::ApplyStateBlock(), CRenderSystemGLES::ApplyStateBlock(), CRenderSystemDX::BeginRender(), CRenderSystemGL::BeginRender(), CRenderSystemGLES::BeginRender(), CRenderSystemDX::CaptureStateBlock(), CRenderSystemGL::CaptureStateBlock(), CRenderSystemGLES::CaptureStateBlock(), CRenderSystemDX::ClearBuffers(), CRenderSystemGL::ClearBuffers(), CRenderSystemGLES::ClearBuffers(), CRenderSystemDX::ClipRectToScissorRect(), CRenderSystemBase(), CRenderSystemGL::DestroyRenderSystem(), CRenderSystemGLES::DestroyRenderSystem(), CRenderSystemDX::EndRender(), CRenderSystemGL::EndRender(), CRenderSystemGLES::EndRender(), CRenderSystemDX::FlushGPU(), CRenderSystemDX::GetViewPort(), CRenderSystemGL::GetViewPort(), CRenderSystemGLES::GetViewPort(), CRenderSystemDX::InitRenderSystem(), CRenderSystemGL::InitRenderSystem(), CRenderSystemGLES::InitRenderSystem(), CRenderSystemGL::InvalidateColorBuffer(), CRenderSystemGLES::InvalidateColorBuffer(), CRenderSystemDX::OnResize(), CRenderSystemDX::PresentRender(), CRenderSystemGL::PresentRender(), CRenderSystemGLES::PresentRender(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::PresentRender(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::PresentRender(), CRenderSystemDX::Project(), CRenderSystemGL::ResetRenderSystem(), CRenderSystemDX::ResetScissors(), CRenderSystemDX::RestoreViewPort(), CRenderSystemDX::ScissorsCanEffectClipping(), CRenderSystemDX::SetAlphaBlendEnable(), CRenderSystemGL::SetCameraPosition(), CRenderSystemGLES::SetCameraPosition(), CRenderSystemDX::SetCameraPosition(), CRenderSystemDX::SetScissors(), CRenderSystemGL::SetScissors(), CRenderSystemGLES::SetScissors(), CRenderSystemDX::SetStereoMode(), CRenderSystemDX::SetViewPort(), CRenderSystemGL::SetViewPort(), CRenderSystemGLES::SetViewPort(), CRenderSystemGL::SetVSync(), and CRenderSystemGLES::SetVSync().
m_bVSync
bool CRenderSystemBase::m_bVSync protected
Referenced by CRenderSystemBase(), CRenderSystemDX::CRenderSystemDX(), CRenderSystemDX::InitRenderSystem(), CRenderSystemGL::InitRenderSystem(), CWinSystemOSXGL::ResizeWindow(), CWinSystemOSXGL::SetFullScreen(), and CRenderSystemGL::SetVSync().
m_limitedColorRange
bool CRenderSystemBase::m_limitedColorRange = false protected
Referenced by CRenderSystemDX::BeginRender(), CRenderSystemGL::BeginRender(), CRenderSystemGLES::BeginRender(), CRenderSystemGL::InitialiseShaders(), and CRenderSystemGLES::InitialiseShaders().
m_maxTextureSize
unsigned int CRenderSystemBase::m_maxTextureSize protected
Referenced by CRenderSystemGL::CalculateMaxTexturesize(), CRenderSystemGLES::CalculateMaxTexturesize(), CRenderSystemDX::CheckDeviceCaps(), CRenderSystemBase(), GetMaxTextureSize(), CRenderSystemGL::InitRenderSystem(), and CRenderSystemGLES::InitRenderSystem().
m_minDXTPitch
unsigned int CRenderSystemBase::m_minDXTPitch protected
Referenced by CRenderSystemBase(), and GetMinDXTPitch().
m_RenderRenderer
std::string CRenderSystemBase::m_RenderRenderer protected
Referenced by GetRenderRenderer(), CRenderSystemDX::InitRenderSystem(), CRenderSystemGL::InitRenderSystem(), and CRenderSystemGLES::InitRenderSystem().
m_RenderVendor
std::string CRenderSystemBase::m_RenderVendor protected
Referenced by GetRenderVendor(), CRenderSystemGL::InitRenderSystem(), and CRenderSystemGLES::InitRenderSystem().
m_RenderVersion
std::string CRenderSystemBase::m_RenderVersion protected
Referenced by GetRenderVersionString(), CRenderSystemDX::InitRenderSystem(), CRenderSystemGL::InitRenderSystem(), and CRenderSystemGLES::InitRenderSystem().
m_RenderVersionMajor
int CRenderSystemBase::m_RenderVersionMajor protected
Referenced by CRenderSystemBase(), GetRenderVersion(), CRenderSystemGLES::GetShaderPath(), CRenderSystemGL::InitRenderSystem(), CRenderSystemGLES::InitRenderSystem(), CRenderSystemGL::IsExtSupported(), and CRenderSystemGL::ResetRenderSystem().
m_RenderVersionMinor
int CRenderSystemBase::m_RenderVersionMinor protected
Referenced by CRenderSystemBase(), GetRenderVersion(), CRenderSystemGLES::GetShaderPath(), CRenderSystemGL::InitRenderSystem(), CRenderSystemGLES::InitRenderSystem(), CRenderSystemGL::IsExtSupported(), and CRenderSystemGL::ResetRenderSystem().
m_splashImage
std::unique_ptr<CGUIImage> CRenderSystemBase::m_splashImage protected
Referenced by ShowSplash().
m_splashMessageLayout
std::unique_ptr<CGUITextLayout> CRenderSystemBase::m_splashMessageLayout protected
Referenced by ShowSplash().
m_stereoMode
RENDER_STEREO_MODE CRenderSystemBase::m_stereoMode = RENDER_STEREO_MODE_OFF protected
Referenced by CRenderSystemDX::ClearBuffers(), CRenderSystemGL::ClearBuffers(), CRenderSystemGL::InvalidateColorBuffer(), CRenderSystemDX::PresentRender(), SetStereoMode(), CRenderSystemDX::SetStereoMode(), and CRenderSystemGL::SetStereoMode().
m_stereoView
RENDER_STEREO_VIEW CRenderSystemBase::m_stereoView = RENDER_STEREO_VIEW_OFF protected
Referenced by CRenderSystemDX::ClearBuffers(), CRenderSystemGL::ClearBuffers(), CRenderSystemDX::GetBackBuffer(), CRenderSystemGL::InvalidateColorBuffer(), SetStereoMode(), CRenderSystemDX::SetStereoMode(), and CRenderSystemGL::SetStereoMode().
m_transferPQ
bool CRenderSystemBase::m_transferPQ {false} protected
Referenced by CRenderSystemGLES::BeginRender(), and CRenderSystemGLES::InitialiseShaders().
The documentation for this class was generated from the following files:
RenderSystem.h
RenderSystem.cpp