Kodi Documentation: CPlayerSettings Class Reference
CPlayerSettings Class Reference
#include <PlayerSettings.h>
Static Public Member Functions
static void SettingOptionsQueueTimeSizesFiller (const SettingConstPtr &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
static void SettingOptionsQueueDataSizesFiller (const SettingConstPtr &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
Additional Inherited Members
Public Member Functions inherited from ISubSettings
virtual ~ISubSettings ()=default
virtual bool Load (const TiXmlNode *settings)
Load settings from the given XML node.
virtual bool Save (TiXmlNode *settings) const
Save settings to the given XML node.
virtual void Clear ()
Clear any loaded setting values.
Member Function Documentation
SettingOptionsQueueDataSizesFiller()
void CPlayerSettings::SettingOptionsQueueDataSizesFiller (const SettingConstPtr & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CSettings::InitializeOptionFillers().
SettingOptionsQueueTimeSizesFiller()
void CPlayerSettings::SettingOptionsQueueTimeSizesFiller (const SettingConstPtr & setting, std::vector< IntegerSettingOption > & list, int & current, void * data) static
References g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CSettings::InitializeOptionFillers().
The documentation for this class was generated from the following files:
PlayerSettings.h
PlayerSettings.cpp