Kodi Documentation: CApplicationSettingsHandling Class Reference
CApplicationSettingsHandling Class Reference
Class handling application support for settings.
#include <ApplicationSettingsHandling.h>
Protected Member Functions
void RegisterSettings ()
void UnregisterSettings ()
bool Load (const TiXmlNode *settings) override
Load settings from the given XML node.
bool Save (TiXmlNode *settings) const override
Save settings to the given XML node.
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
void OnSettingAction (const std::shared_ptr< const CSetting > &setting) override
The given setting has been activated.
bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode) override
The given setting needs to be updated.
Additional Inherited Members
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Public Member Functions inherited from ISettingsHandler
virtual ~ISettingsHandler ()=default
virtual bool OnSettingsLoading ()
Settings loading has been initiated.
virtual void OnSettingsLoaded ()
Settings have been loaded.
virtual bool OnSettingsSaving () const
Settings saving has been initiated.
virtual void OnSettingsSaved () const
Settings have been saved.
virtual void OnSettingsUnloaded ()
Setting values have been unloaded.
virtual void OnSettingsCleared ()
Settings have been cleared.
Public Member Functions inherited from ISubSettings
virtual ~ISubSettings ()=default
virtual void Clear ()
Clear any loaded setting values.
Detailed Description
Class handling application support for settings.
Member Function Documentation
Load()
bool CApplicationSettingsHandling::Load (const TiXmlNode * settings) override protected virtual
Load settings from the given XML node.
Parameters
settings XML node containing setting values
Returns
True if loading the settings was successful, false otherwise.
Reimplemented from ISubSettings.
References CServiceBroker::GetAppComponents(), and CApplicationVolumeHandling::Load().
OnSettingAction()
void CApplicationSettingsHandling::OnSettingAction (const std::shared_ptr< const CSetting > & setting) override protected virtual
The given setting has been activated.
This callback is triggered whenever the given setting has been activated. This callback is only fired for CSettingAction settings.
Parameters
setting The setting which has been activated.
Reimplemented from ISettingCallback.
References CGUIWindowManager::ActivateWindow(), ADDON::AUDIOENCODER, ADDON::CHOICE_YES, CServiceBroker::GetAddonMgr(), CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), CSettings::SETTING_AUDIOCDS_ENCODER, CSettings::SETTING_AUDIOCDS_SETTINGS, CSettings::SETTING_LOOKANDFEEL_SKINSETTINGS, CSettings::SETTING_SOURCE_MUSIC, CSettings::SETTING_SOURCE_PICTURES, CSettings::SETTING_SOURCE_VIDEOS, CSettings::SETTING_VIDEOSCREEN_GUICALIBRATION, CGUIDialogAddonSettings::ShowForAddon(), WINDOW_MUSIC_NAV, WINDOW_PICTURES, WINDOW_SCREEN_CALIBRATION, WINDOW_SKIN_SETTINGS, and WINDOW_VIDEO_NAV.
OnSettingChanged()
void CApplicationSettingsHandling::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override protected virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), CWinSystemBase::GetGfxContext(), CGraphicContext::GetVideoResolution(), CServiceBroker::GetWinSystem(), CGraphicContext::IsFullScreenRoot(), CSettings::SETTING_AUDIOOUTPUT_PASSTHROUGH, CSettings::SETTING_VIDEOSCREEN_FAKEFULLSCREEN, CGraphicContext::SetVideoResolution(), and TMSG_MEDIA_RESTART.
OnSettingUpdate()
bool CApplicationSettingsHandling::OnSettingUpdate (const std::shared_ptr< CSetting > & setting, const char * oldSettingId, const TiXmlNode * oldSettingNode) override protected virtual
The given setting needs to be updated.
This callback is triggered when a setting needs to be updated because its value is outdated. This only happens when initially loading the value of a setting and will not be triggered afterwards.
Parameters
setting The setting which needs to be updated.
oldSettingId The id of the previous setting.
oldSettingNode The old setting node
Returns
True if the setting has been successfully updated otherwise false
Reimplemented from ISettingCallback.
References CSettings::SETTING_AUDIOOUTPUT_AUDIODEVICE.
RegisterSettings()
void CApplicationSettingsHandling::RegisterSettings () protected
References CSettingsManager::AddDynamicCondition(), CServiceBroker::GetAppComponents(), CServiceBroker::GetSettingsComponent(), CSettingsManager::RegisterCallback(), CSettingsManager::RegisterSettingsHandler(), CSettings::SETTING_AUDIOCDS_SETTINGS, CSettings::SETTING_AUDIOOUTPUT_PASSTHROUGH, CSettings::SETTING_AUDIOOUTPUT_VOLUMESTEPS, CSettings::SETTING_LOOKANDFEEL_FONT, CSettings::SETTING_LOOKANDFEEL_SKIN, CSettings::SETTING_LOOKANDFEEL_SKINCOLORS, CSettings::SETTING_LOOKANDFEEL_SKINSETTINGS, CSettings::SETTING_LOOKANDFEEL_SKINTHEME, CSettings::SETTING_LOOKANDFEEL_SKINZOOM, CSettings::SETTING_MUSICPLAYER_REPLAYGAINAVOIDCLIPPING, CSettings::SETTING_MUSICPLAYER_REPLAYGAINNOGAINPREAMP, CSettings::SETTING_MUSICPLAYER_REPLAYGAINPREAMP, CSettings::SETTING_MUSICPLAYER_REPLAYGAINTYPE, CSettings::SETTING_MUSICPLAYER_SEEKDELAY, CSettings::SETTING_MUSICPLAYER_SEEKSTEPS, CSettings::SETTING_SCRAPERS_MUSICVIDEOSDEFAULT, CSettings::SETTING_SCREENSAVER_MODE, CSettings::SETTING_SCREENSAVER_PREVIEW, CSettings::SETTING_SCREENSAVER_SETTINGS, CSettings::SETTING_SOURCE_MUSIC, CSettings::SETTING_SOURCE_PICTURES, CSettings::SETTING_SOURCE_VIDEOS, CSettings::SETTING_VIDEOPLAYER_SEEKDELAY, CSettings::SETTING_VIDEOPLAYER_SEEKSTEPS, CSettings::SETTING_VIDEOPLAYER_USEMEDIACODEC, CSettings::SETTING_VIDEOPLAYER_USEMEDIACODECSURFACE, CSettings::SETTING_VIDEOSCREEN_FAKEFULLSCREEN, CSettings::SETTING_VIDEOSCREEN_GUICALIBRATION, and CSettings::SETTING_VIDEOSCREEN_TESTPATTERN.
Referenced by CApplication::Create().
Save()
bool CApplicationSettingsHandling::Save (TiXmlNode * settings) const override protected virtual
Save settings to the given XML node.
Parameters
settings XML node in which the settings will be saved
Returns
True if saving the settings was successful, false otherwise.
Reimplemented from ISubSettings.
References CServiceBroker::GetAppComponents(), and CApplicationVolumeHandling::Save().
UnregisterSettings()
void CApplicationSettingsHandling::UnregisterSettings () protected
References CServiceBroker::GetAppComponents(), CServiceBroker::GetSettingsComponent(), CSettingsManager::RemoveDynamicCondition(), CSettingsManager::UnregisterCallback(), and CSettingsManager::UnregisterSettingsHandler().
Referenced by CApplication::Cleanup().
The documentation for this class was generated from the following files:
ApplicationSettingsHandling.h
ApplicationSettingsHandling.cpp