Kodi Documentation: CVideoSyncGbm Class Reference
CVideoSyncGbm Class Reference
#include <VideoSyncGbm.h>
Public Member Functions
CVideoSyncGbm (CVideoReferenceClock *clock)
CVideoSyncGbm ()=delete
~CVideoSyncGbm () override=default
bool Setup () override
void Run (CEvent &stopEvent) override
void Cleanup () override
float GetFps () override
void RefreshChanged () override
void OnResetDisplay () override
Public Member Functions inherited from CVideoSync
CVideoSync (CVideoReferenceClock *clock)
virtual ~CVideoSync ()=default
Private Attributes
int m_fd = -1
uint32_t m_crtcId = 0
uint64_t m_sequence = 0
uint64_t m_offset = 0
std::atomic< bool > m_abort {false}
CWinSystemBase * m_winSystem
Additional Inherited Members
Protected Attributes inherited from CVideoSync
float m_fps
CVideoReferenceClock * m_refClock
Private Member Functions inherited from IDispResource
virtual ~IDispResource ()=default
virtual void OnLostDisplay ()
virtual void OnAppFocusChange (bool focus)
Constructor & Destructor Documentation
CVideoSyncGbm() [1/2]
CVideoSyncGbm::CVideoSyncGbm (CVideoReferenceClock * clock) explicit
References m_winSystem.
CVideoSyncGbm() [2/2]
CVideoSyncGbm::CVideoSyncGbm () delete
~CVideoSyncGbm()
CVideoSyncGbm::~CVideoSyncGbm () override default
Member Function Documentation
Cleanup()
void CVideoSyncGbm::Cleanup () override virtual
Implements CVideoSync.
References CLog::Log(), LOGDEBUG, m_winSystem, and CWinSystemBase::Unregister().
GetFps()
float CVideoSyncGbm::GetFps () override virtual
Implements CVideoSync.
References CGraphicContext::GetFPS(), CWinSystemBase::GetGfxContext(), CLog::Log(), LOGDEBUG, CVideoSync::m_fps, and m_winSystem.
OnResetDisplay()
void CVideoSyncGbm::OnResetDisplay () override virtual
Reimplemented from IDispResource.
References m_abort.
RefreshChanged()
void CVideoSyncGbm::RefreshChanged () override virtual
Reimplemented from CVideoSync.
References CGraphicContext::GetFPS(), CWinSystemBase::GetGfxContext(), m_abort, CVideoSync::m_fps, and m_winSystem.
Run()
void CVideoSyncGbm::Run (CEvent & stopEvent) override virtual
Implements CVideoSync.
References ABOVE_NORMAL, CThread::GetCurrentThread(), CLog::Log(), LOGDEBUG, LOGWARNING, m_abort, m_crtcId, m_fd, m_offset, CVideoSync::m_refClock, m_sequence, CThread::SetPriority(), CEvent::Signaled(), and CVideoReferenceClock::UpdateClock().
Setup()
bool CVideoSyncGbm::Setup () override virtual
Implements CVideoSync.
References CurrentHostCounter(), CLog::Log(), LOGDEBUG, LOGINFO, LOGWARNING, m_abort, m_crtcId, m_fd, m_offset, m_sequence, m_winSystem, and CWinSystemBase::Register().
Member Data Documentation
m_abort
std::atomic<bool> CVideoSyncGbm::m_abort {false} private
Referenced by OnResetDisplay(), RefreshChanged(), Run(), and Setup().
m_crtcId
uint32_t CVideoSyncGbm::m_crtcId = 0 private
Referenced by Run(), and Setup().
m_fd
int CVideoSyncGbm::m_fd = -1 private
Referenced by Run(), and Setup().
m_offset
uint64_t CVideoSyncGbm::m_offset = 0 private
Referenced by Run(), and Setup().
m_sequence
uint64_t CVideoSyncGbm::m_sequence = 0 private
Referenced by Run(), and Setup().
m_winSystem
CWinSystemBase* CVideoSyncGbm::m_winSystem private
Referenced by Cleanup(), CVideoSyncGbm(), GetFps(), RefreshChanged(), and Setup().
The documentation for this class was generated from the following files:
VideoSyncGbm.h
VideoSyncGbm.cpp