Kodi Documentation: HttpParser Class Reference
HttpParser Class Reference
#include <HttpParser.h>
Public Types
enum status_t { Done , Error , Incomplete }
Public Member Functions
~HttpParser ()
status_t addBytes (const char *bytes, unsigned len)
const char * getMethod () const
const char * getUri () const
const char * getQueryString () const
const char * getBody () const
const char * getValue (const char *key) const
unsigned getContentLength () const
Private Types
enum State {
p_request_line =0 , p_request_line_cr =1 , p_request_line_crlf =2 , p_request_line_crlfcr =3 ,
p_key =4 , p_key_colon =5 , p_key_colon_sp =6 , p_value =7 ,
p_value_cr =8 , p_value_crlf =9 , p_value_crlfcr =10 , p_content =11 ,
p_error =12
}
typedef std::vector< unsigned > IntArray
Private Member Functions
void parseHeader ()
bool parseRequestLine ()
Private Attributes
std::string _data
unsigned _headerStart = 0
unsigned _parsedTo = 0
int _state = 0
unsigned _keyIndex = 0
unsigned _valueIndex = 0
unsigned _contentLength = 0
unsigned _contentStart = 0
unsigned _uriIndex = 0
IntArray _keys
status_t _status = Incomplete
Member Typedef Documentation
IntArray
typedef std::vector<unsigned> HttpParser::IntArray private
Member Enumeration Documentation
State
enum HttpParser::State private
Enumerator
p_request_line
p_request_line_cr
p_request_line_crlf
p_request_line_crlfcr
p_key
p_key_colon
p_key_colon_sp
p_value
p_value_cr
p_value_crlf
p_value_crlfcr
p_content
p_error
status_t
enum HttpParser::status_t
Enumerator
Done
Error
Incomplete
Constructor & Destructor Documentation
~HttpParser()
HttpParser::~HttpParser () default
Member Function Documentation
addBytes()
HttpParser::status_t HttpParser::addBytes (const char * bytes, unsigned len)
References _contentLength, _contentStart, _data, _state, _status, Done, Error, Incomplete, p_content, p_error, parseHeader(), and parseRequestLine().
Referenced by CWebSocketManager::Handle(), CWebSocketV13::Handshake(), CWebSocketV8::Handshake(), and TEST().
getBody()
const char * HttpParser::getBody () const
References _contentLength, _contentStart, and _data.
Referenced by TEST().
getContentLength()
unsigned HttpParser::getContentLength () const
References _contentLength.
Referenced by TEST().
getMethod()
const char * HttpParser::getMethod () const
References _data.
Referenced by CWebSocketV13::Handshake(), CWebSocketV8::Handshake(), and TEST().
getQueryString()
const char * HttpParser::getQueryString () const
References getUri().
Referenced by TEST().
getUri()
const char * HttpParser::getUri () const
References _data, and _uriIndex.
Referenced by getQueryString(), and TEST().
getValue()
const char * HttpParser::getValue (const char * key) const
References _data, _keys, and index().
Referenced by CWebSocketManager::Handle(), CWebSocketV13::Handshake(), CWebSocketV8::Handshake(), parseHeader(), and TEST().
parseHeader()
void HttpParser::parseHeader () private
References _contentLength, _contentStart, _data, _headerStart, _keyIndex, _keys, _parsedTo, _state, _valueIndex, Action, actions, ANY, CR, f, getValue(), LOWER, p_content, p_error, p_key, p_key_colon, p_key_colon_sp, p_request_line, p_request_line_cr, p_request_line_crlf, p_request_line_crlfcr, p_value, p_value_cr, p_value_crlf, and p_value_crlfcr.
Referenced by addBytes().
parseRequestLine()
bool HttpParser::parseRequestLine () private
References _data, and _uriIndex.
Referenced by addBytes().
Member Data Documentation
_contentLength
unsigned HttpParser::_contentLength = 0 private
Referenced by addBytes(), getBody(), getContentLength(), and parseHeader().
_contentStart
unsigned HttpParser::_contentStart = 0 private
Referenced by addBytes(), getBody(), and parseHeader().
_data
std::string HttpParser::_data private
Referenced by addBytes(), getBody(), getMethod(), getUri(), getValue(), parseHeader(), and parseRequestLine().
_headerStart
unsigned HttpParser::_headerStart = 0 private
Referenced by parseHeader().
_keyIndex
unsigned HttpParser::_keyIndex = 0 private
Referenced by parseHeader().
_keys
IntArray HttpParser::_keys private
Referenced by getValue(), and parseHeader().
_parsedTo
unsigned HttpParser::_parsedTo = 0 private
Referenced by parseHeader().
_state
int HttpParser::_state = 0 private
Referenced by addBytes(), and parseHeader().
_status
status_t HttpParser::_status = Incomplete private
Referenced by addBytes().
_uriIndex
unsigned HttpParser::_uriIndex = 0 private
Referenced by getUri(), and parseRequestLine().
_valueIndex
unsigned HttpParser::_valueIndex = 0 private
Referenced by parseHeader().
The documentation for this class was generated from the following files:
HttpParser.h
HttpParser.cpp