Kodi Documentation: CGUIFontCache< Position, Value > Class Template Reference
CGUIFontCache< Position, Value > Class Template Reference
#include <GUIFontCache.h>
Public Member Functions
CGUIFontCache (CGUIFontTTF &font)
~CGUIFontCache ()
Value & Lookup (const CGraphicContext &context, Position &pos, const std::vector< KODI::UTILS::COLOR::Color > &colors, const vecText &text, uint32_t alignment, float maxPixelWidth, bool scrolling, std::chrono::steady_clock::time_point now, bool &dirtyCache)
void Flush ()
Public Attributes
const CGUIFontTTF & m_font
Private Member Functions
CGUIFontCache (const CGUIFontCache< Position, Value > &)=delete
const CGUIFontCache< Position, Value > & operator= (const CGUIFontCache< Position, Value > &)=delete
Private Attributes
std::unique_ptr< CGUIFontCacheImpl< Position, Value > > m_impl
Constructor & Destructor Documentation
CGUIFontCache() [1/2]
template<class Position , class Value > CGUIFontCache< Position, Value >::CGUIFontCache (const CGUIFontCache< Position, Value > &) private delete
CGUIFontCache() [2/2]
template<class Position , class Value > template CGUIFontCache< Position, Value >::CGUIFontCache (CGUIFontTTF & font) explicit
~CGUIFontCache()
template<class Position , class Value > template CGUIFontCache< Position, Value >::~CGUIFontCache () default
Member Function Documentation
Flush()
template<class Position , class Value > template void CGUIFontCache< Position, Value >::Flush ()
Referenced by CGUIFontTTFDX::ReallocTexture(), CGUIFontTTFGL::ReallocTexture(), and CGUIFontTTFGLES::ReallocTexture().
Lookup()
template<class Position , class Value > template CGUIFontCacheDynamicValue & CGUIFontCache< Position, Value >::Lookup (const CGraphicContext & context, Position & pos, const std::vector< KODI::UTILS::COLOR::Color > & colors, const vecText & text, uint32_t alignment, float maxPixelWidth, bool scrolling, std::chrono::steady_clock::time_point now, bool & dirtyCache)
References text.
Referenced by CGUIFontTTF::DrawTextInternal().
operator=()
template<class Position , class Value > const CGUIFontCache< Position, Value > & CGUIFontCache< Position, Value >::operator= (const CGUIFontCache< Position, Value > &) private delete
Member Data Documentation
m_font
template<class Position , class Value > const CGUIFontTTF& CGUIFontCache< Position, Value >::m_font
m_impl
template<class Position , class Value > std::unique_ptr<CGUIFontCacheImpl<Position, Value> > CGUIFontCache< Position, Value >::m_impl private
The documentation for this class was generated from the following files:
GUIFontCache.h
GUIFontCache.cpp