Kodi Documentation: CAirPlayServer::CTCPClient Class Reference
CAirPlayServer::CTCPClient Class Reference
Public Member Functions
CTCPClient ()
~CTCPClient ()
CTCPClient (const CTCPClient &client)
CTCPClient & operator= (const CTCPClient &client)
void PushBuffer (CAirPlayServer *host, const char *buffer, int length, std::string &sessionId, std::map< std::string, int > &reverseSockets)
void ComposeReverseEvent (std::string &reverseHeader, std::string &reverseBody, int state)
void Disconnect ()
Public Attributes
int m_socket
struct sockaddr_storage m_cliaddr
socklen_t m_addrlen
CCriticalSection m_critSection
int m_sessionCounter
std::string m_sessionId
Private Member Functions
int ProcessRequest (std::string &responseHeader, std::string &response)
void ComposeAuthRequestAnswer (std::string &responseHeader, std::string &responseBody)
bool checkAuthorization (const std::string &authStr, const std::string &method, const std::string &uri)
void Copy (const CTCPClient &client)
Private Attributes
HttpParser * m_httpParser
bool m_bAuthenticated
int m_lastEvent
std::string m_authNonce
Constructor & Destructor Documentation
CTCPClient() [1/2]
CAirPlayServer::CTCPClient::CTCPClient ()
References EVENT_NONE, INVALID_SOCKET, m_addrlen, m_bAuthenticated, m_httpParser, m_lastEvent, and m_socket.
~CTCPClient()
CAirPlayServer::CTCPClient::~CTCPClient ()
CTCPClient() [2/2]
CAirPlayServer::CTCPClient::CTCPClient (const CTCPClient & client)
References Copy(), and m_httpParser.
Member Function Documentation
checkAuthorization()
bool CAirPlayServer::CTCPClient::checkAuthorization (const std::string & authStr, const std::string & method, const std::string & uri) private
References AUTH_REALM, calcResponse(), getFieldFromString(), CLog::Log(), LOGDEBUG, CAirPlayServer::m_password, and CAirPlayServer::ServerInstance.
ComposeAuthRequestAnswer()
void CAirPlayServer::CTCPClient::ComposeAuthRequestAnswer (std::string & responseHeader, std::string & responseBody) private
References AUTH_REQUIRED.
ComposeReverseEvent()
void CAirPlayServer::CTCPClient::ComposeReverseEvent (std::string & reverseHeader, std::string & reverseBody, int state)
References EVENT_INFO, EVENT_LOADING, EVENT_PAUSED, EVENT_PLAYING, EVENT_STOPPED, eventStrings, CLog::Log(), and LOGDEBUG.
Copy()
void CAirPlayServer::CTCPClient::Copy (const CTCPClient & client) private
References m_addrlen, m_authNonce, m_bAuthenticated, m_cliaddr, m_httpParser, m_sessionCounter, and m_socket.
Referenced by CTCPClient().
Disconnect()
void CAirPlayServer::CTCPClient::Disconnect ()
References INVALID_SOCKET, SHUT_RDWR, and shutdown().
operator=()
CAirPlayServer::CTCPClient & CAirPlayServer::CTCPClient::operator= (const CTCPClient & client)
ProcessRequest()
int CAirPlayServer::CTCPClient::ProcessRequest (std::string & responseHeader, std::string & response) private
References ACTION_STOP, ACTION_VOLUME_DOWN, ACTION_VOLUME_UP, CFileItemList::Add(), AIRPLAY_STATUS_METHOD_NOT_ALLOWED, AIRPLAY_STATUS_NEED_AUTH, AIRPLAY_STATUS_NO_RESPONSE_NEEDED, AIRPLAY_STATUS_NOT_FOUND, AIRPLAY_STATUS_NOT_IMPLEMENTED, AIRPLAY_STATUS_OK, AIRPLAY_STATUS_PRECONDITION_FAILED, AIRPLAY_STATUS_SWITCHING_PROTOCOLS, CAirPlayServer::AnnounceToClients(), CAirPlayServer::backupVolume(), ClearPhotoAssetCache(), XFILE::CFile::Close(), end(), EVENT_LOADING, EVENT_NONE, XFILE::CFile::Exists(), CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetNetwork(), CServiceBroker::GetSettingsComponent(), getStringFromPlist(), CApplicationVolumeHandling::GetVolumePercent(), int64_t(), CAirPlayServer::IsPlaying(), CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, CAirPlayServer::m_isPlaying, CAirPlayServer::m_usePassword, XFILE::CFile::OpenForWrite(), PLAYBACK_INFO, PLAYBACK_INFO_NOT_READY, SERVER_INFO, CAirPlayServer::ServerInstance, CGUIListItem::SetProperty(), CSettings::SETTING_SERVICES_AIRPLAYVOLUMECONTROL, TMSG_GUI_ACTION, TMSG_MEDIA_PAUSE, TMSG_MEDIA_PLAY, TMSG_MEDIA_STOP, TMSG_PICTURE_SHOW, TMSG_VOLUME_SHOW, WINDOW_SLIDESHOW, and XFILE::CFile::Write().
PushBuffer()
void CAirPlayServer::CTCPClient::PushBuffer (CAirPlayServer * host, const char * buffer, int length, std::string & sessionId, std::map< std::string, int > & reverseSockets)
References AIRPLAY_STATUS_METHOD_NOT_ALLOWED, AIRPLAY_STATUS_NEED_AUTH, AIRPLAY_STATUS_NO_RESPONSE_NEEDED, AIRPLAY_STATUS_NOT_FOUND, AIRPLAY_STATUS_NOT_IMPLEMENTED, AIRPLAY_STATUS_PRECONDITION_FAILED, AIRPLAY_STATUS_SWITCHING_PROTOCOLS, and HttpParser::Done.
Member Data Documentation
m_addrlen
socklen_t CAirPlayServer::CTCPClient::m_addrlen
Referenced by Copy(), CTCPClient(), and CAirPlayServer::Process().
m_authNonce
std::string CAirPlayServer::CTCPClient::m_authNonce private
Referenced by Copy().
m_bAuthenticated
bool CAirPlayServer::CTCPClient::m_bAuthenticated private
Referenced by Copy(), and CTCPClient().
m_cliaddr
struct sockaddr_storage CAirPlayServer::CTCPClient::m_cliaddr
Referenced by Copy(), and CAirPlayServer::Process().
m_critSection
CCriticalSection CAirPlayServer::CTCPClient::m_critSection
m_httpParser
HttpParser* CAirPlayServer::CTCPClient::m_httpParser private
Referenced by Copy(), CTCPClient(), and CTCPClient().
m_lastEvent
int CAirPlayServer::CTCPClient::m_lastEvent private
Referenced by CTCPClient().
m_sessionCounter
int CAirPlayServer::CTCPClient::m_sessionCounter
Referenced by Copy(), and CAirPlayServer::Process().
m_sessionId
std::string CAirPlayServer::CTCPClient::m_sessionId
m_socket
int CAirPlayServer::CTCPClient::m_socket
Referenced by Copy(), CTCPClient(), and CAirPlayServer::Process().
The documentation for this class was generated from the following files:
AirPlayServer.h
AirPlayServer.cpp