Kodi Documentation: dll.h File Reference
dll.h File Reference
#include "PlatformDefs.h"
Functions
HMODULE __stdcall dllLoadLibraryExtended (const char *file, const char *sourcedll)
HMODULE __stdcall dllLoadLibraryA (const char *file)
HMODULE __stdcall dllLoadLibraryExExtended (const char *lpLibFileName, HANDLE hFile, DWORD dwFlags, const char *sourcedll)
HMODULE __stdcall dllLoadLibraryExA (const char *lpLibFileName, HANDLE hFile, DWORD dwFlags)
int __stdcall dllFreeLibrary (HINSTANCE hLibModule)
HMODULE WINAPI dllGetModuleHandleA (const char *lpModuleName)
Function Documentation
dllFreeLibrary()
int __stdcall dllFreeLibrary (HINSTANCE hLibModule)
dllGetModuleHandleA()
HMODULE WINAPI dllGetModuleHandleA (const char * lpModuleName)
References LibraryLoader::GetHModule(), DllLoaderContainer::GetModule(), CLog::Log(), and LOGDEBUG.
dllLoadLibraryA()
HMODULE __stdcall dllLoadLibraryA (const char * file)
References dllLoadLibraryExtended().
Referenced by Win32DllLoader::OverrideImports().
dllLoadLibraryExA()
HMODULE __stdcall dllLoadLibraryExA (const char * lpLibFileName, HANDLE hFile, DWORD dwFlags)
References dllLoadLibraryExExtended().
dllLoadLibraryExExtended()
HMODULE __stdcall dllLoadLibraryExExtended (const char * lpLibFileName, HANDLE hFile, DWORD dwFlags, const char * sourcedll)
References dllLoadLibraryExtended(), DONT_RESOLVE_DLL_REFERENCES, LOAD_IGNORE_CODE_AUTHZ_LEVEL, LOAD_LIBRARY_AS_DATAFILE, LOAD_WITH_ALTERED_SEARCH_PATH, CLog::Log(), and LOGDEBUG.
Referenced by dllLoadLibraryExA().
dllLoadLibraryExtended()
HMODULE __stdcall dllLoadLibraryExtended (const char * file, const char * sourcedll)
References DEFAULT_DLLPATH, LibraryLoader::GetHModule(), getpath(), DllLoaderContainer::LoadModule(), CLog::Log(), LOGERROR, MAX_PATH, and PATH_SEPARATOR_CHAR.
Referenced by dllLoadLibraryA(), and dllLoadLibraryExExtended().