Kodi Documentation: KODI::JOYSTICK::CInputHandling Class Reference
KODI::JOYSTICK::CInputHandling Class Reference
Input » Joystick
Class to translate input from the driver into higher-level features.
#include <InputHandling.h>
Public Member Functions
CInputHandling (IInputHandler *handler, IButtonMap *buttonMap)
~CInputHandling () override
bool OnButtonMotion (unsigned int buttonIndex, bool bPressed) override
Handle button motion.
bool OnHatMotion (unsigned int hatIndex, HAT_STATE state) override
Handle hat motion.
bool OnAxisMotion (unsigned int axisIndex, float position, int center, unsigned int range) override
Handle axis motion.
void OnInputFrame () override
Handle buffered input motion for features that require multiple axes.
Public Member Functions inherited from KODI::JOYSTICK::IDriverHandler
virtual ~IDriverHandler ()=default
Private Member Functions
bool OnDigitalMotion (const CDriverPrimitive &source, bool bPressed)
bool OnAnalogMotion (const CDriverPrimitive &source, float magnitude)
CJoystickFeature * CreateFeature (const FeatureName &featureName)
Private Attributes
IInputHandler *const m_handler
IButtonMap *const m_buttonMap
std::map< FeatureName, FeaturePtr > m_features
Static Private Attributes
static CGUIDialogNewJoystick *const m_dialog = new CGUIDialogNewJoystick
Detailed Description
Class to translate input from the driver into higher-level features.
Raw driver input arrives for three elements: buttons, hats and axes. When driver input is handled by this class, it translates the raw driver elements into physical joystick features, such as buttons, analog sticks, etc.
A button map is used to translate driver primitives to controller features. The button map has been abstracted away behind the IButtonMap interface so that it can be provided by an add-on.
Constructor & Destructor Documentation
CInputHandling()
CInputHandling::CInputHandling (IInputHandler * handler, IButtonMap * buttonMap)
~CInputHandling()
CInputHandling::~CInputHandling () override default
Member Function Documentation
CreateFeature()
CJoystickFeature * CInputHandling::CreateFeature (const FeatureName & featureName) private
References KODI::JOYSTICK::ACCELEROMETER, KODI::JOYSTICK::ANALOG_STICK, KODI::JOYSTICK::IButtonMap::GetFeatureType(), m_buttonMap, m_handler, and KODI::JOYSTICK::SCALAR.
Referenced by OnAnalogMotion(), and OnDigitalMotion().
OnAnalogMotion()
bool CInputHandling::OnAnalogMotion (const CDriverPrimitive & source, float magnitude) private
References CreateFeature(), KODI::JOYSTICK::IButtonMap::GetFeature(), m_buttonMap, and m_features.
Referenced by OnAxisMotion().
OnAxisMotion()
bool CInputHandling::OnAxisMotion (unsigned int axisIndex, float position, int center, unsigned int range) override virtual
Handle axis motion.
If a joystick feature requires multiple axes (analog sticks, accelerometers), they can be buffered for later processing.
Parameters
axisIndex The index of the axis as reported by the driver
position The position of the axis in the closed interval [-1.0, 1.0]
center The center point of the axis (either -1, 0 or 1)
range The maximum distance the axis can move (either 1 or 2)
Returns
True if the motion was handled, false otherwise
Implements KODI::JOYSTICK::IDriverHandler.
References center, KODI::JOYSTICK::NEGATIVE, OnAnalogMotion(), and KODI::JOYSTICK::POSITIVE.
OnButtonMotion()
bool CInputHandling::OnButtonMotion (unsigned int buttonIndex, bool bPressed) override virtual
Handle button motion.
Parameters
buttonIndex The index of the button as reported by the driver
bPressed true for press motion, false for release motion
Returns
True if a press was handled, false otherwise
Implements KODI::JOYSTICK::IDriverHandler.
References KODI::JOYSTICK::BUTTON, and OnDigitalMotion().
OnDigitalMotion()
bool CInputHandling::OnDigitalMotion (const CDriverPrimitive & source, bool bPressed) private
References KODI::JOYSTICK::IButtonMap::ControllerID(), CreateFeature(), KODI::JOYSTICK::IButtonMap::GetFeature(), KODI::JOYSTICK::IButtonMap::IsEmpty(), CLog::Log(), LOGDEBUG, m_buttonMap, m_dialog, m_features, and KODI::JOYSTICK::CGUIDialogNewJoystick::ShowAsync().
Referenced by OnButtonMotion(), and OnHatMotion().
OnHatMotion()
bool CInputHandling::OnHatMotion (unsigned int hatIndex, HAT_STATE state) override virtual
Handle hat motion.
Parameters
hatIndex The index of the hat as reported by the driver
state The direction the hat is now being pressed
Returns
True if the new direction was handled, false otherwise
Implements KODI::JOYSTICK::IDriverHandler.
References OnDigitalMotion().
OnInputFrame()
void CInputHandling::OnInputFrame () override virtual
Handle buffered input motion for features that require multiple axes.
OnInputFrame() is called at the end of the frame when all axis motions have been reported. This has several uses, including:
Combining multiple axes into a single analog stick or accelerometer event
Imitating an analog feature with a digital button so that events can be dispatched every frame.
Implements KODI::JOYSTICK::IDriverHandler.
References m_features, m_handler, and KODI::JOYSTICK::IInputHandler::OnInputFrame().
Member Data Documentation
m_buttonMap
IButtonMap* const KODI::JOYSTICK::CInputHandling::m_buttonMap private
Referenced by CreateFeature(), OnAnalogMotion(), and OnDigitalMotion().
m_dialog
CGUIDialogNewJoystick *const CInputHandling::m_dialog = new CGUIDialogNewJoystick static private
Referenced by OnDigitalMotion().
m_features
std::map<FeatureName, FeaturePtr> KODI::JOYSTICK::CInputHandling::m_features private
Referenced by OnAnalogMotion(), OnDigitalMotion(), and OnInputFrame().
m_handler
IInputHandler* const KODI::JOYSTICK::CInputHandling::m_handler private
Referenced by CreateFeature(), and OnInputFrame().
The documentation for this class was generated from the following files:
InputHandling.h
InputHandling.cpp