Kodi Documentation: KODI::RETRO::CGUIRenderSettings Class Reference
KODI::RETRO::CGUIRenderSettings Class Reference
#include <GUIRenderSettings.h>
Public Member Functions
CGUIRenderSettings (CGUIGameControl &guiControl)
~CGUIRenderSettings () override=default
bool HasVideoFilter () const override
Returns true if this render target has a video filter set.
bool HasStretchMode () const override
Returns true if this render target has a stretch mode set.
bool HasRotation () const override
Returns true if this render target has a video rotation set.
bool HasPixels () const override
Returns true if this render target has a path to a savestate for showing pixel data.
CRenderSettings GetSettings () const override
Get the settings used to render this target.
CRect GetDimensions () const override
Get the dimensions of this target.
void Reset ()
void SetSettings (const CRenderSettings &settings)
void SetDimensions (const CRect &dimensions)
void SetVideoFilter (const std::string &videoFilter)
void SetStretchMode (STRETCHMODE stretchMode)
void SetRotationDegCCW (unsigned int rotationDegCCW)
void SetPixels (const std::string &pixelPath)
Public Member Functions inherited from KODI::RETRO::IGUIRenderSettings
virtual ~IGUIRenderSettings ()=default
Private Attributes
CGUIGameControl & m_guiControl
CRenderSettings m_renderSettings
CRect m_renderDimensions
CCriticalSection m_mutex
Constructor & Destructor Documentation
CGUIRenderSettings()
CGUIRenderSettings::CGUIRenderSettings (CGUIGameControl & guiControl)
~CGUIRenderSettings()
KODI::RETRO::CGUIRenderSettings::~CGUIRenderSettings () override default
Member Function Documentation
GetDimensions()
CRect CGUIRenderSettings::GetDimensions () const override virtual
Get the dimensions of this target.
Dimensions are ignored for fullscreen windows.
Returns
The destination dimensions, or unused for fullscreen window
Reimplemented from KODI::RETRO::IGUIRenderSettings.
References m_mutex, and m_renderDimensions.
GetSettings()
CRenderSettings CGUIRenderSettings::GetSettings () const override virtual
Get the settings used to render this target.
Returns
The render settings
Implements KODI::RETRO::IGUIRenderSettings.
References m_mutex, and m_renderSettings.
HasPixels()
bool CGUIRenderSettings::HasPixels () const override virtual
Returns true if this render target has a path to a savestate for showing pixel data.
Reimplemented from KODI::RETRO::IGUIRenderSettings.
References KODI::RETRO::CGUIGameControl::HasPixels(), and m_guiControl.
HasRotation()
bool CGUIRenderSettings::HasRotation () const override virtual
Returns true if this render target has a video rotation set.
Reimplemented from KODI::RETRO::IGUIRenderSettings.
References KODI::RETRO::CGUIGameControl::HasRotation(), and m_guiControl.
HasStretchMode()
bool CGUIRenderSettings::HasStretchMode () const override virtual
Returns true if this render target has a stretch mode set.
Reimplemented from KODI::RETRO::IGUIRenderSettings.
References KODI::RETRO::CGUIGameControl::HasStretchMode(), and m_guiControl.
HasVideoFilter()
bool CGUIRenderSettings::HasVideoFilter () const override virtual
Returns true if this render target has a video filter set.
Reimplemented from KODI::RETRO::IGUIRenderSettings.
References KODI::RETRO::CGUIGameControl::HasVideoFilter(), and m_guiControl.
Reset()
void CGUIRenderSettings::Reset ()
References m_mutex, m_renderSettings, and KODI::RETRO::CRenderSettings::Reset().
SetDimensions()
void CGUIRenderSettings::SetDimensions (const CRect & dimensions)
References m_mutex, and m_renderDimensions.
SetPixels()
void CGUIRenderSettings::SetPixels (const std::string & pixelPath)
References m_mutex, m_renderSettings, KODI::RETRO::CRenderVideoSettings::SetPixels(), and KODI::RETRO::CRenderSettings::VideoSettings().
SetRotationDegCCW()
void CGUIRenderSettings::SetRotationDegCCW (unsigned int rotationDegCCW)
References m_mutex, m_renderSettings, KODI::RETRO::CRenderVideoSettings::SetRenderRotation(), and KODI::RETRO::CRenderSettings::VideoSettings().
SetSettings()
void CGUIRenderSettings::SetSettings (const CRenderSettings & settings)
References m_mutex, and m_renderSettings.
SetStretchMode()
void CGUIRenderSettings::SetStretchMode (STRETCHMODE stretchMode)
References m_mutex, m_renderSettings, KODI::RETRO::CRenderVideoSettings::SetRenderStretchMode(), and KODI::RETRO::CRenderSettings::VideoSettings().
SetVideoFilter()
void CGUIRenderSettings::SetVideoFilter (const std::string & videoFilter)
References m_mutex, m_renderSettings, KODI::RETRO::CRenderVideoSettings::SetVideoFilter(), and KODI::RETRO::CRenderSettings::VideoSettings().
Member Data Documentation
m_guiControl
CGUIGameControl& KODI::RETRO::CGUIRenderSettings::m_guiControl private
Referenced by HasPixels(), HasRotation(), HasStretchMode(), and HasVideoFilter().
m_mutex
CCriticalSection KODI::RETRO::CGUIRenderSettings::m_mutex mutable private
Referenced by GetDimensions(), GetSettings(), Reset(), SetDimensions(), SetPixels(), SetRotationDegCCW(), SetSettings(), SetStretchMode(), and SetVideoFilter().
m_renderDimensions
CRect KODI::RETRO::CGUIRenderSettings::m_renderDimensions private
Referenced by GetDimensions(), and SetDimensions().
m_renderSettings
CRenderSettings KODI::RETRO::CGUIRenderSettings::m_renderSettings private
Referenced by GetSettings(), Reset(), SetPixels(), SetRotationDegCCW(), SetSettings(), SetStretchMode(), and SetVideoFilter().
The documentation for this class was generated from the following files:
GUIRenderSettings.h
GUIRenderSettings.cpp