Kodi Documentation: CApplicationPlayerCallback Class Reference
CApplicationPlayerCallback Class Reference
#include <ApplicationPlayerCallback.h>
Public Member Functions
CApplicationPlayerCallback ()
void OnPlayBackEnded () override
void OnPlayBackStarted (const CFileItem &file) override
void OnPlayerCloseFile (const CFileItem &file, const CBookmark &bookmark) override
void OnPlayBackPaused () override
void OnPlayBackResumed () override
void OnPlayBackStopped () override
void OnPlayBackError () override
void OnQueueNextItem () override
void OnPlayBackSeek (int64_t iTime, int64_t seekOffset) override
void OnPlayBackSeekChapter (int iChapter) override
void OnPlayBackSpeedChanged (int iSpeed) override
void OnAVChange () override
void OnAVStarted (const CFileItem &file) override
void RequestVideoSettings (const CFileItem &fileItem) override
void StoreVideoSettings (const CFileItem &fileItem, const CVideoSettings &vs) override
Public Member Functions inherited from IPlayerCallback
virtual ~IPlayerCallback ()=default
Constructor & Destructor Documentation
CApplicationPlayerCallback()
CApplicationPlayerCallback::CApplicationPlayerCallback ()
Member Function Documentation
OnAVChange()
void CApplicationPlayerCallback::OnAVChange () override virtual
Reimplemented from IPlayerCallback.
References CServiceBroker::GetGUI(), CGUIComponent::GetStereoscopicsManager(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYBACK_AVCHANGE, LOGDEBUG, and CStereoscopicsManager::OnStreamChange().
OnAVStarted()
void CApplicationPlayerCallback::OnAVStarted (const CFileItem & file) override virtual
Reimplemented from IPlayerCallback.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYBACK_AVSTARTED, and LOGDEBUG.
OnPlayBackEnded()
void CApplicationPlayerCallback::OnPlayBackEnded () override virtual
Implements IPlayerCallback.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYBACK_ENDED, and LOGDEBUG.
OnPlayBackError()
void CApplicationPlayerCallback::OnPlayBackError () override virtual
Implements IPlayerCallback.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYBACK_ERROR, and OnPlayBackStopped().
OnPlayBackPaused()
void CApplicationPlayerCallback::OnPlayBackPaused () override virtual
Reimplemented from IPlayerCallback.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CServiceBroker::GetXBPython(), GUI_MSG_PLAYBACK_PAUSED, and XBPython::OnPlayBackPaused().
OnPlayBackResumed()
void CApplicationPlayerCallback::OnPlayBackResumed () override virtual
Reimplemented from IPlayerCallback.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CServiceBroker::GetXBPython(), GUI_MSG_PLAYBACK_RESUMED, and XBPython::OnPlayBackResumed().
OnPlayBackSeek()
void CApplicationPlayerCallback::OnPlayBackSeek (int64_t iTime, int64_t seekOffset) override virtual
Reimplemented from IPlayerCallback.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CServiceBroker::GetXBPython(), GUI_MSG_PLAYBACK_SEEKED, and XBPython::OnPlayBackSeek().
OnPlayBackSeekChapter()
void CApplicationPlayerCallback::OnPlayBackSeekChapter (int iChapter) override virtual
Reimplemented from IPlayerCallback.
References CServiceBroker::GetXBPython(), and XBPython::OnPlayBackSeekChapter().
OnPlayBackSpeedChanged()
void CApplicationPlayerCallback::OnPlayBackSpeedChanged (int iSpeed) override virtual
Reimplemented from IPlayerCallback.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CServiceBroker::GetXBPython(), GUI_MSG_PLAYBACK_SPEED_CHANGED, and XBPython::OnPlayBackSpeedChanged().
OnPlayBackStarted()
void CApplicationPlayerCallback::OnPlayBackStarted (const CFileItem & file) override virtual
Implements IPlayerCallback.
References CServiceBroker::GetAppComponents(), CServiceBroker::GetGUI(), CServiceBroker::GetJobManager(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYBACK_STARTED, URIUtils::IsBluray(), KODI::NETWORK::IsInternetStream(), LOGDEBUG, and CApplicationPlayer::SetUpdateStreamDetails().
OnPlayBackStopped()
void CApplicationPlayerCallback::OnPlayBackStopped () override virtual
Implements IPlayerCallback.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_PLAYBACK_STOPPED, and LOGDEBUG.
Referenced by OnPlayBackError().
OnPlayerCloseFile()
void CApplicationPlayerCallback::OnPlayerCloseFile (const CFileItem & file, const CBookmark & bookmark) override virtual
Reimplemented from IPlayerCallback.
References CSaveFileState::DoWork(), CServiceBroker::GetAppComponents(), CServiceBroker::GetSettingsComponent(), CFileItem::GetVideoInfoTag(), KODI::MUSIC::IsAudio(), CVideoInfoTag::m_streamDetails, CBookmark::partNumber, CStreamDetails::SetVideoDuration(), CBookmark::timeInSeconds, and CBookmark::totalTimeInSeconds.
OnQueueNextItem()
void CApplicationPlayerCallback::OnQueueNextItem () override virtual
Implements IPlayerCallback.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CServiceBroker::GetXBPython(), GUI_MSG_QUEUE_NEXT_ITEM, LOGDEBUG, and XBPython::OnQueueNextItem().
RequestVideoSettings()
void CApplicationPlayerCallback::RequestVideoSettings (const CFileItem & fileItem) override virtual
Reimplemented from IPlayerCallback.
References CDatabase::Close(), CServiceBroker::GetAppComponents(), CMediaSettings::GetDefaultVideoSettings(), CMediaSettings::GetInstance(), CFileItem::GetPath(), CVideoDatabase::GetVideoSettings(), CLog::Log(), LOGDEBUG, CVideoDatabase::Open(), and CApplicationPlayer::SetVideoSettings().
StoreVideoSettings()
void CApplicationPlayerCallback::StoreVideoSettings (const CFileItem & fileItem, const CVideoSettings & vs) override virtual
Reimplemented from IPlayerCallback.
References CDatabase::Close(), CVideoDatabase::EraseVideoSettings(), CMediaSettings::GetInstance(), CVideoDatabase::Open(), and CVideoDatabase::SetVideoSettings().
The documentation for this class was generated from the following files:
ApplicationPlayerCallback.h
ApplicationPlayerCallback.cpp