Kodi Documentation: KODI::ART Namespace Reference
KODI::ART Namespace Reference
Functions
void FillInDefaultIcon (CFileItem &item)
Set default icon for item.
std::string GetFolderThumb (const CFileItem &item, const std::string &folderJPG="folder.jpg")
Get the folder image associated with item.
std::string GetLocalArt (const CFileItem &item, const std::string &artFile, bool useFolder=false)
Assemble the filename of a particular piece of local artwork for an item. No file existence check is typically performed.
std::string GetLocalArtBaseFilename (const CFileItem &item, bool &useFolder)
Assemble the base filename of local artwork for an item, accounting for archives, stacks and multi-paths, and BDMV/VIDEO_TS folders.
std::string GetLocalFanart (const CFileItem &item)
Get the local fanart for item if it exists.
std::string GetTBNFile (const CFileItem &item)
Get the .tbn file associated with an item.
Function Documentation
FillInDefaultIcon()
void KODI::ART::FillInDefaultIcon (CFileItem & item)
Set default icon for item.
References CGUIListItem::GetArt(), CFileItem::GetPath(), CGUIListItem::HasOverlay(), CGUIListItem::HasProperty(), CGUIListItem::ICON_OVERLAY_RAR, CGUIListItem::ICON_OVERLAY_ZIP, URIUtils::IsArchive(), KODI::MUSIC::IsAudio(), CFileItem::IsDeletedPVRRecording(), CFileItem::IsFavourite(), URIUtils::IsInRAR(), URIUtils::IsInZIP(), CFileItem::IsLiveTV(), CFileItem::IsParentFolder(), CFileItem::IsPicture(), KODI::PLAYLIST::IsPlayList(), CFileItem::IsPVRChannel(), URIUtils::IsPVRGuideItem(), CFileItem::IsPVRProvider(), URIUtils::IsPVRRadioChannel(), CFileItem::IsPVRTimer(), CFileItem::IsPythonScript(), KODI::PLAYLIST::IsSmartPlayList(), CFileItem::IsUsablePVRRecording(), KODI::VIDEO::IsVideo(), CGUIListItem::m_bIsFolder, CGUIListItem::SetArt(), and CGUIListItem::SetOverlayImage().
Referenced by CFileItem::CFileItem(), CFileItemList::FillInDefaultIcons(), XFILE::CZeroconfDirectory::GetDirectory(), GetDirectoryFromTxtRecords(), CPictureThumbLoader::LoadItemCached(), CPictureThumbLoader::ProcessFoldersAndArchives(), CGUIInfoManager::SetCurrentAlbumThumb(), CGUIInfoManager::SetCurrentItem(), CFileItem::SetFromMusicInfoTag(), CFileItem::SetFromVideoInfoTag(), and TEST_P().
GetFolderThumb()
std::string KODI::ART::GetFolderThumb (const CFileItem & item, const std::string & folderJPG = "folder.jpg")
Get the folder image associated with item.
Parameters
item Item to get folder image for
folderJPG Thumb file to use
Returns
Folder thumb file appropriate for item
References URIUtils::AddFileToFolder(), URIUtils::GetDirectory(), XFILE::CMultiPathDirectory::GetFirstPath(), CURL::GetHostName(), URIUtils::GetParentPath(), CFileItem::GetPath(), URIUtils::IsInRAR(), URIUtils::IsInZIP(), CFileItem::IsMultiPath(), CFileItem::IsPlugin(), and CFileItem::IsStack().
Referenced by CProgramThumbLoader::GetLocalThumb(), CFileItem::GetUserMusicThumb(), CGUIDialogContextMenu::OnContextButton(), and TEST_P().
GetLocalArt()
std::string KODI::ART::GetLocalArt (const CFileItem & item, const std::string & artFile, bool useFolder = false)
Assemble the filename of a particular piece of local artwork for an item. No file existence check is typically performed.
Parameters
artFile the art file to search for.
useFolder whether to look in the folder for the art file. Defaults to false.
Returns
the path to the local artwork.
See also
FindLocalArt
References URIUtils::AddFileToFolder(), GetLocalArtBaseFilename(), and URIUtils::ReplaceExtension().
Referenced by CVideoDatabase::ExportToXML(), CFileItem::FindLocalArt(), and TEST_P().
GetLocalArtBaseFilename()
std::string KODI::ART::GetLocalArtBaseFilename (const CFileItem & item, bool & useFolder)
Assemble the base filename of local artwork for an item, accounting for archives, stacks and multi-paths, and BDMV/VIDEO_TS folders.
Parameters
useFolder whether to look in the folder for the art file. Defaults to false.
Returns
the path to the base filename for artwork lookup.
See also
GetLocalArt
References URIUtils::AddFileToFolder(), URIUtils::GetDirectory(), CFileItem::GetDynPath(), URIUtils::GetFileName(), XFILE::CMultiPathDirectory::GetFirstPath(), CFileItem::GetLocalMetadataPath(), URIUtils::GetParentPath(), CFileItem::GetPath(), XFILE::CStackDirectory::GetStackedTitlePath(), CFileItem::IsFileFolder(), URIUtils::IsInRAR(), URIUtils::IsInZIP(), CFileItem::IsMultiPath(), CFileItem::IsOpticalMediaFile(), CFileItem::IsStack(), and CGUIListItem::m_bIsFolder.
Referenced by KODI::VIDEO::CVideoInfoScanner::GetArtwork(), GetLocalArt(), and TEST_P().
GetLocalFanart()
std::string KODI::ART::GetLocalFanart (const CFileItem & item)
Get the local fanart for item if it exists.
Returns
path to the local fanart for this item, or empty if none exists
See also
GetFolderThumb, GetTBNFile
References URIUtils::AddFileToFolder(), CFileItemList::Append(), XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::DIR_FLAG_NO_FILE_INFO, XFILE::DIR_FLAG_READ_CACHE, XFILE::CDirectory::GetDirectory(), URIUtils::GetDirectory(), CServiceBroker::GetFileExtensionProvider(), URIUtils::GetFileName(), XFILE::CStackDirectory::GetFirstStackedFile(), GetLocalFanart(), CFileItem::GetLocalMetadataPath(), URIUtils::GetParentPath(), CFileItem::GetPath(), CFileExtensionProvider::GetPictureExtensions(), CServiceBroker::GetSettingsComponent(), XFILE::CStackDirectory::GetStackedTitlePath(), GetTBNFile(), CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), CFileItem::IsAddonsPath(), URIUtils::IsBluray(), CFileItem::IsDVD(), URIUtils::IsFTP(), URIUtils::IsInRAR(), KODI::NETWORK::IsInternetStream(), URIUtils::IsInZIP(), CFileItem::IsLiveTV(), CFileItem::IsOpticalMediaFile(), CFileItem::IsPlugin(), CFileItem::IsStack(), URIUtils::IsUPnP(), KODI::VIDEO::IsVideoDb(), CGUIListItem::m_bIsFolder, CVideoInfoTag::m_strFileNameAndPath, CVideoInfoTag::m_strPath, URIUtils::RemoveExtension(), and URIUtils::ReplaceExtension().
Referenced by KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::GetLocalArt(), GetLocalFanart(), and TEST_P().
GetTBNFile()
std::string KODI::ART::GetTBNFile (const CFileItem & item)
Get the .tbn file associated with an item.
References URIUtils::AddFileToFolder(), XFILE::CFile::Exists(), CURL::Get(), URIUtils::GetDirectory(), CURL::GetFileName(), URIUtils::GetFileName(), XFILE::CStackDirectory::GetFirstStackedFile(), URIUtils::GetParentPath(), CFileItem::GetPath(), XFILE::CStackDirectory::GetStackedTitlePath(), GetTBNFile(), CFileItem::IsFileFolder(), URIUtils::IsInRAR(), URIUtils::IsInZIP(), CFileItem::IsStack(), CGUIListItem::m_bIsFolder, URIUtils::RemoveSlashAtEnd(), URIUtils::ReplaceExtension(), and CURL::SetFileName().
Referenced by CVideoDatabase::ExportToXML(), KODI::VIDEO::UTILS::FindTrailer(), GetLocalFanart(), CProgramThumbLoader::GetLocalThumb(), GetTBNFile(), CFileItem::GetUserMusicThumb(), TEST(), and TEST_P().