Kodi Documentation: CGUILabelControl Class Reference
CGUILabelControl Class Reference
Guilib classes » Window Reference » Controls
#include <GUILabelControl.h>
Public Member Functions
CGUILabelControl (int parentID, int controlID, float posX, float posY, float width, float height, const CLabelInfo &labelInfo, bool wrapMultiLine, bool bHasPath)
~CGUILabelControl (void) override
CGUILabelControl * Clone () const override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
void UpdateInfo (const CGUIListItem *item=NULL) override
bool CanFocus () const override
bool OnMessage (CGUIMessage &message) override
std::string GetDescription () const override
float GetWidth () const override
void SetWidth (float width) override
CRect CalcRenderRegion () const override
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
const CLabelInfo & GetLabelInfo () const
void SetLabel (const std::string &strLabel)
void ShowCursor (bool bShow=true)
void SetCursorPos (int iPos)
int GetCursorPos () const
void SetInfo (const KODI::GUILIB::GUIINFO::CGUIInfoLabel &labelInfo)
void SetWidthControl (float minWidth, bool bScroll)
void SetAlignment (uint32_t align)
void SetHighlight (unsigned int start, unsigned int end)
void SetSelection (unsigned int start, unsigned int end)
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
virtual void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions)
virtual void DoRender ()
virtual void RenderEx ()
bool HasProcessed () const
Returns whether or not we have processed.
virtual bool OnAction (const CAction &action)
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
React to a mouse event.
virtual EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
Perform a mouse action.
virtual void UnfocusFromPoint (const CPoint &point)
Unfocus the control if the given point on screen is not within it's boundary.
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
virtual void SetID (int id)
int GetParentID () const
virtual bool HasFocus () const
virtual void AllocResources ()
virtual void FreeResources (bool immediately=false)
virtual void DynamicResourceAlloc (bool bOnOff)
virtual bool IsDynamicallyAllocated ()
virtual bool IsVisible () const
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetHeight () const
virtual void AssignDepth ()
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetInitialVisibility ()
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
virtual void QueueAnimation (ANIMATION_TYPE anim)
virtual bool IsAnimating (ANIMATION_TYPE anim)
virtual bool HasAnimation (ANIMATION_TYPE anim)
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void ResetAnimation (ANIMATION_TYPE type)
virtual void ResetAnimations ()
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsGroup () const
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
virtual void SaveStates (std::vector< CControlState > &states)
virtual CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr)
void SetControlStats (GUICONTROLSTATS *controlStats)
virtual void UpdateControlStats ()
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Protected Member Functions
bool UpdateColors (const CGUIListItem *item) override
std::string ShortenPath (const std::string &path)
float GetMaxWidth () const
Return the maximum width of this label control.
Protected Member Functions inherited from CGUIControl
virtual CPoint GetPosition () const
Return the coordinates of the top left of the control, in the control's parent coordinates.
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool Animate (unsigned int currentTime)
virtual bool CheckAnimation (ANIMATION_TYPE animType)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Attributes
CGUILabel m_label
bool m_bHasPath
bool m_bShowCursor
int m_iCursorPos
unsigned int m_dwCounter
float m_minWidth
KODI::GUILIB::GUIINFO::CGUIInfoLabel m_infoLabel
unsigned int m_startHighlight
unsigned int m_endHighlight
unsigned int m_startSelection
unsigned int m_endSelection
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Additional Inherited Members
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Constructor & Destructor Documentation
CGUILabelControl()
CGUILabelControl::CGUILabelControl (int parentID, int controlID, float posX, float posY, float width, float height, const CLabelInfo & labelInfo, bool wrapMultiLine, bool bHasPath)
References CGUIControl::ControlType, CGUIControl::GUICONTROL_LABEL, m_bHasPath, m_bShowCursor, m_dwCounter, m_endHighlight, m_endSelection, m_iCursorPos, m_label, m_minWidth, m_startHighlight, m_startSelection, and CGUILabel::SetScrollLoopCount().
~CGUILabelControl()
CGUILabelControl::~CGUILabelControl (void) override default
Member Function Documentation
CalcRenderRegion()
CRect CGUILabelControl::CalcRenderRegion () const override virtual
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
Reimplemented from CGUIControl.
References CGUILabel::GetRenderRect(), and m_label.
CanFocus()
bool CGUILabelControl::CanFocus () const override virtual
Reimplemented from CGUIControl.
Clone()
CGUILabelControl * CGUILabelControl::Clone (void) const inline override virtual
Implements CGUIControl.
GetCursorPos()
int CGUILabelControl::GetCursorPos () const inline
References m_iCursorPos.
GetDescription()
std::string CGUILabelControl::GetDescription (void) const override virtual
Reimplemented from CGUIControl.
References KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), m_infoLabel, and CGUIControl::m_parentID.
Referenced by ADDON::Interface_GUIControlLabel::get_label().
GetLabelInfo()
const CLabelInfo & CGUILabelControl::GetLabelInfo () const inline
References CGUILabel::GetLabelInfo(), and m_label.
Referenced by CGUIDialogKeyboardGeneric::OnInitWindow().
GetMaxWidth()
float CGUILabelControl::GetMaxWidth () const inline protected
Return the maximum width of this label control.
Returns
Return the width of the control if available, else the width of the current text.
References CGUILabel::GetTextWidth(), m_label, and CGUIControl::m_width.
Referenced by GetWidth(), Process(), and UpdateInfo().
GetWidth()
float CGUILabelControl::GetWidth () const override virtual
Reimplemented from CGUIControl.
References CLAMP, GetMaxWidth(), CGUILabel::GetTextWidth(), m_label, m_minWidth, and CGUIControl::m_width.
Referenced by CGUIDialogKeyboardGeneric::OnInitWindow(), and CGUIDialog::OnWindowLoaded().
OnMessage()
bool CGUILabelControl::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIControl.
References CGUIMessage::GetControlId(), CGUIControl::GetID(), CGUIMessage::GetLabel(), CGUIMessage::GetMessage(), GUI_MSG_LABEL_SET, GUI_MSG_REFRESH_TIMER, GUI_MSG_WINDOW_RESIZE, CGUIControl::IsVisible(), m_label, CGUIControl::OnMessage(), CGUILabel::SetInvalid(), SetLabel(), and UpdateInfo().
Process()
void CGUILabelControl::Process (unsigned int currentTime, CDirtyRegionList & dirtyregions) override virtual
Reimplemented from CGUIControl.
References CGUILabel::COLOR_DISABLED, CGUILabel::COLOR_TEXT, GetMaxWidth(), CGUIControl::IsDisabled(), CGUIControl::m_height, m_label, CGUIControl::m_posX, CGUIControl::m_posY, CGUIControl::MarkDirtyRegion(), CGUILabel::Process(), CGUIControl::Process(), CGUILabel::SetColor(), and CGUILabel::SetMaxRect().
Render()
void CGUILabelControl::Render () override virtual
Reimplemented from CGUIControl.
References CServiceBroker::GetWinSystem(), m_label, CGUIControl::Render(), CGUILabel::Render(), and RENDER_ORDER_FRONT_TO_BACK.
SetAlignment()
void CGUILabelControl::SetAlignment (uint32_t align)
References CLabelInfo::align, CGUILabel::GetLabelInfo(), m_label, and CGUIControl::MarkDirtyRegion().
SetCursorPos()
void CGUILabelControl::SetCursorPos (int iPos)
References g_charsetConverter, KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), label, m_iCursorPos, m_infoLabel, CGUIControl::m_parentID, and CGUIControl::MarkDirtyRegion().
SetHighlight()
void CGUILabelControl::SetHighlight (unsigned int start, unsigned int end)
References end(), m_endHighlight, and m_startHighlight.
Referenced by CGUIDialogNumeric::FrameMove().
SetInfo()
void CGUILabelControl::SetInfo (const KODI::GUILIB::GUIINFO::CGUIInfoLabel & labelInfo)
References m_infoLabel.
SetLabel()
void CGUILabelControl::SetLabel (const std::string & strLabel)
References KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), CGUIControl::GetParentID(), m_iCursorPos, m_infoLabel, CGUIControl::SetInvalid(), and KODI::GUILIB::GUIINFO::CGUIInfoLabel::SetLabel().
Referenced by KODI::GAME::CGUIFeatureGroupTitle::CGUIFeatureGroupTitle(), CGUIDialogNumeric::FrameMove(), and OnMessage().
SetSelection()
void CGUILabelControl::SetSelection (unsigned int start, unsigned int end)
References end(), m_endSelection, and m_startSelection.
SetWidth()
void CGUILabelControl::SetWidth (float width) override virtual
Reimplemented from CGUIControl.
References CGUIControl::m_height, m_label, CGUIControl::m_posX, CGUIControl::m_posY, CGUIControl::m_width, CGUILabel::SetMaxRect(), and CGUIControl::SetWidth().
Referenced by CGUIDialog::OnWindowLoaded().
SetWidthControl()
void CGUILabelControl::SetWidthControl (float minWidth, bool bScroll)
References m_label, m_minWidth, CGUIControl::MarkDirtyRegion(), and CGUILabel::SetScrolling().
ShortenPath()
std::string CGUILabelControl::ShortenPath (const std::string & path) protected
References CGUILabel::GetTextWidth(), m_label, CGUIControl::m_width, CGUIControl::MarkDirtyRegion(), and CGUILabel::SetText().
Referenced by UpdateInfo().
ShowCursor()
void CGUILabelControl::ShowCursor (bool bShow = true)
References m_bShowCursor.
UpdateColors()
bool CGUILabelControl::UpdateColors (const CGUIListItem * item) override protected virtual
Reimplemented from CGUIControl.
References m_label, CGUILabel::UpdateColors(), and CGUIControl::UpdateColors().
UpdateInfo()
void CGUILabelControl::UpdateInfo (const CGUIListItem * item = NULL) override virtual
Reimplemented from CGUIControl.
References CLabelInfo::disabledColor, CLabelInfo::font, FONT_STYLE_MASK, FONT_STYLE_NORMAL, g_charsetConverter, KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), CGUILabel::GetLabelInfo(), GetMaxWidth(), CGUIFont::GetStyle(), label, m_bHasPath, m_bShowCursor, m_dwCounter, m_endHighlight, m_endSelection, CGUIControl::m_height, m_iCursorPos, m_infoLabel, m_label, CGUIControl::m_parentID, CGUIControl::m_posX, CGUIControl::m_posY, m_startHighlight, m_startSelection, CGUIControl::MarkDirtyRegion(), CLabelInfo::selectedColor, CGUILabel::SetMaxRect(), CGUILabel::SetStyledText(), CGUILabel::SetText(), ShortenPath(), text, and CLabelInfo::textColor.
Referenced by OnMessage().
Member Data Documentation
m_bHasPath
bool CGUILabelControl::m_bHasPath protected
Referenced by CGUILabelControl(), and UpdateInfo().
m_bShowCursor
bool CGUILabelControl::m_bShowCursor protected
Referenced by CGUILabelControl(), ShowCursor(), and UpdateInfo().
m_dwCounter
unsigned int CGUILabelControl::m_dwCounter protected
Referenced by CGUILabelControl(), and UpdateInfo().
m_endHighlight
unsigned int CGUILabelControl::m_endHighlight protected
Referenced by CGUILabelControl(), SetHighlight(), and UpdateInfo().
m_endSelection
unsigned int CGUILabelControl::m_endSelection protected
Referenced by CGUILabelControl(), SetSelection(), and UpdateInfo().
m_iCursorPos
int CGUILabelControl::m_iCursorPos protected
Referenced by CGUILabelControl(), GetCursorPos(), SetCursorPos(), SetLabel(), and UpdateInfo().
m_infoLabel
KODI::GUILIB::GUIINFO::CGUIInfoLabel CGUILabelControl::m_infoLabel protected
Referenced by GetDescription(), SetCursorPos(), SetInfo(), SetLabel(), and UpdateInfo().
m_label
CGUILabel CGUILabelControl::m_label protected
Referenced by CalcRenderRegion(), CGUILabelControl(), GetLabelInfo(), GetMaxWidth(), GetWidth(), OnMessage(), Process(), Render(), SetAlignment(), SetWidth(), SetWidthControl(), ShortenPath(), UpdateColors(), and UpdateInfo().
m_minWidth
float CGUILabelControl::m_minWidth protected
Referenced by CGUILabelControl(), GetWidth(), and SetWidthControl().
m_startHighlight
unsigned int CGUILabelControl::m_startHighlight protected
Referenced by CGUILabelControl(), SetHighlight(), and UpdateInfo().
m_startSelection
unsigned int CGUILabelControl::m_startSelection protected
Referenced by CGUILabelControl(), SetSelection(), and UpdateInfo().
The documentation for this class was generated from the following files:
GUILabelControl.h
GUILabelControl.cpp