Kodi Documentation: CSettingsComponent Class Reference
CSettingsComponent Class Reference
#include <SettingsComponent.h>
Public Member Functions
CSettingsComponent ()
virtual ~CSettingsComponent ()
void Initialize ()
Initialize all subcomponents with system default values (loaded from code, system settings files, ...).
bool Load ()
Initialize all subcomponents with user values (loaded from user settings files, according to active profile).
void Deinitialize ()
Deinitialize all subcomponents.
std::shared_ptr< CSettings > GetSettings ()
Get access to the settings subcomponent.
std::shared_ptr< CAdvancedSettings > GetAdvancedSettings ()
Get access to the advanced settings subcomponent.
std::shared_ptr< KODI::SUBTITLES::CSubtitlesSettings > GetSubtitlesSettings ()
Get access to the subtitles settings subcomponent.
std::shared_ptr< CProfileManager > GetProfileManager ()
Get access to the profiles manager subcomponent.
Private Types
enum class State { DEINITED , INITED , LOADED }
Private Member Functions
bool InitDirectoriesLinux (bool bPlatformDirectories)
bool InitDirectoriesOSX (bool bPlatformDirectories)
bool InitDirectoriesWin32 (bool bPlatformDirectories)
void CreateUserDirs () const
Private Attributes
State m_state = State::DEINITED
std::shared_ptr< CSettings > m_settings
std::shared_ptr< CAdvancedSettings > m_advancedSettings
std::shared_ptr< KODI::SUBTITLES::CSubtitlesSettings > m_subtitlesSettings
std::shared_ptr< CProfileManager > m_profileManager
Member Enumeration Documentation
State
enum class CSettingsComponent::State strong private
Enumerator
DEINITED
INITED
LOADED
Constructor & Destructor Documentation
CSettingsComponent()
CSettingsComponent::CSettingsComponent ()
~CSettingsComponent()
CSettingsComponent::~CSettingsComponent () virtual
Member Function Documentation
CreateUserDirs()
void CSettingsComponent::CreateUserDirs () const private
References XFILE::CDirectory::Create(), XFILE::CDirectory::Exists(), CLog::Log(), LOGWARNING, XFILE::CDirectory::RemoveRecursive(), and CSpecialProtocol::TranslatePath().
Referenced by InitDirectoriesLinux(), InitDirectoriesOSX(), and InitDirectoriesWin32().
Deinitialize()
void CSettingsComponent::Deinitialize ()
Deinitialize all subcomponents.
References DEINITED, INITED, LOADED, m_advancedSettings, m_profileManager, m_settings, m_state, m_subtitlesSettings, URIUtils::UnregisterAdvancedSettings(), XFILE::IDirectory::UnregisterProfileManager(), and CSpecialProtocol::UnregisterProfileManager().
GetAdvancedSettings()
std::shared_ptr< CAdvancedSettings > CSettingsComponent::GetAdvancedSettings ()
Get access to the advanced settings subcomponent.
Returns
the advanced settings subcomponent.
References m_advancedSettings.
GetProfileManager()
std::shared_ptr< CProfileManager > CSettingsComponent::GetProfileManager ()
Get access to the profiles manager subcomponent.
Returns
the profiles manager subcomponent.
References m_profileManager.
GetSettings()
std::shared_ptr< CSettings > CSettingsComponent::GetSettings ()
Get access to the settings subcomponent.
Returns
the settings subcomponent.
References m_settings.
GetSubtitlesSettings()
std::shared_ptr< KODI::SUBTITLES::CSubtitlesSettings > CSettingsComponent::GetSubtitlesSettings ()
Get access to the subtitles settings subcomponent.
Returns
the subtiltles settings subcomponent.
References m_subtitlesSettings.
InitDirectoriesLinux()
bool CSettingsComponent::InitDirectoriesLinux (bool bPlatformDirectories) private
References URIUtils::AddFileToFolder(), URIUtils::AddSlashAtEnd(), CreateUserDirs(), XFILE::CDirectory::Exists(), CCompileInfo::GetAppName(), CUtil::GetHomePath(), CSpecialProtocol::SetHomePath(), CSpecialProtocol::SetLogPath(), CSpecialProtocol::SetMasterProfilePath(), CSpecialProtocol::SetTempPath(), CSpecialProtocol::SetXBMCAltBinAddonPath(), CSpecialProtocol::SetXBMCBinAddonPath(), CSpecialProtocol::SetXBMCBinPath(), and CSpecialProtocol::SetXBMCPath().
Referenced by Initialize().
InitDirectoriesOSX()
bool CSettingsComponent::InitDirectoriesOSX (bool bPlatformDirectories) private
References URIUtils::AddFileToFolder(), URIUtils::AddSlashAtEnd(), XFILE::CDirectory::Create(), CreateUserDirs(), CCompileInfo::GetAppName(), CDarwinEmbedUtils::GetAppRootFolder(), CUtil::GetFrameworksPath(), CUtil::GetHomePath(), CSpecialProtocol::SetHomePath(), CSpecialProtocol::SetLogPath(), CSpecialProtocol::SetMasterProfilePath(), CSpecialProtocol::SetTempPath(), CSpecialProtocol::SetXBMCAltBinAddonPath(), CSpecialProtocol::SetXBMCBinAddonPath(), CSpecialProtocol::SetXBMCBinPath(), CSpecialProtocol::SetXBMCFrameworksPath(), and CSpecialProtocol::SetXBMCPath().
Referenced by Initialize().
InitDirectoriesWin32()
bool CSettingsComponent::InitDirectoriesWin32 (bool bPlatformDirectories) private
References URIUtils::AddFileToFolder(), CreateUserDirs(), CUtil::GetHomePath(), CWIN32Util::GetProfilePath(), CEnvironment::setenv(), CSpecialProtocol::SetHomePath(), CSpecialProtocol::SetLogPath(), CSpecialProtocol::SetMasterProfilePath(), CSpecialProtocol::SetTempPath(), CSpecialProtocol::SetXBMCBinAddonPath(), CSpecialProtocol::SetXBMCBinPath(), CSpecialProtocol::SetXBMCPath(), and CSpecialProtocol::TranslatePath().
Referenced by Initialize().
Initialize()
void CSettingsComponent::Initialize ()
Initialize all subcomponents with system default values (loaded from code, system settings files, ...).
References DEINITED, CServiceBroker::GetAppParams(), InitDirectoriesLinux(), InitDirectoriesOSX(), InitDirectoriesWin32(), INITED, m_advancedSettings, m_profileManager, m_settings, m_state, and URIUtils::RegisterAdvancedSettings().
Load()
bool CSettingsComponent::Load ()
Initialize all subcomponents with user values (loaded from user settings files, according to active profile).
Returns
true on success, false otherwise.
References INITED, LOADED, CLog::Log(), LOGFATAL, m_profileManager, m_settings, m_state, XFILE::IDirectory::RegisterProfileManager(), and CSpecialProtocol::RegisterProfileManager().
Member Data Documentation
m_advancedSettings
std::shared_ptr<CAdvancedSettings> CSettingsComponent::m_advancedSettings private
Referenced by Deinitialize(), GetAdvancedSettings(), and Initialize().
m_profileManager
std::shared_ptr<CProfileManager> CSettingsComponent::m_profileManager private
Referenced by Deinitialize(), GetProfileManager(), Initialize(), and Load().
m_settings
std::shared_ptr<CSettings> CSettingsComponent::m_settings private
Referenced by Deinitialize(), GetSettings(), Initialize(), and Load().
m_state
State CSettingsComponent::m_state = State::DEINITED private
Referenced by Deinitialize(), Initialize(), and Load().
m_subtitlesSettings
std::shared_ptr<KODI::SUBTITLES::CSubtitlesSettings> CSettingsComponent::m_subtitlesSettings private
Referenced by Deinitialize(), and GetSubtitlesSettings().
The documentation for this class was generated from the following files:
SettingsComponent.h
SettingsComponent.cpp