Kodi Documentation: KODI::RETRO::CGUIRenderFullScreen Class Reference
KODI::RETRO::CGUIRenderFullScreen Class Reference
#include <GUIRenderTarget.h>
Public Member Functions
CGUIRenderFullScreen (IRenderManager *renderManager, CGameWindowFullScreen &window)
~CGUIRenderFullScreen () override=default
void Render () override
Draw the frame to the rendering area.
void RenderEx () override
Draw the frame to the rendering area differently somehow.
void ClearBackground () override
Clear the background of the rendering area.
Public Member Functions inherited from KODI::RETRO::CGUIRenderTarget
CGUIRenderTarget (IRenderManager *renderManager)
virtual ~CGUIRenderTarget ()=default
virtual bool IsDirty ()
Check of the rendering area is dirty.
Private Attributes
CGameWindowFullScreen & m_window
Additional Inherited Members
Protected Attributes inherited from KODI::RETRO::CGUIRenderTarget
IRenderManager *const m_renderManager
Constructor & Destructor Documentation
CGUIRenderFullScreen()
CGUIRenderFullScreen::CGUIRenderFullScreen (IRenderManager * renderManager, CGameWindowFullScreen & window)
~CGUIRenderFullScreen()
KODI::RETRO::CGUIRenderFullScreen::~CGUIRenderFullScreen () override default
Member Function Documentation
ClearBackground()
void CGUIRenderFullScreen::ClearBackground () override virtual
Clear the background of the rendering area.
Reimplemented from KODI::RETRO::CGUIRenderTarget.
References KODI::RETRO::IRenderManager::ClearBackground(), and KODI::RETRO::CGUIRenderTarget::m_renderManager.
Render()
void CGUIRenderFullScreen::Render () override virtual
Draw the frame to the rendering area.
Implements KODI::RETRO::CGUIRenderTarget.
References CGUIWindow::GetCoordsRes(), KODI::RETRO::CGUIRenderTarget::m_renderManager, m_window, and KODI::RETRO::IRenderManager::RenderWindow().
RenderEx()
void CGUIRenderFullScreen::RenderEx () override virtual
Draw the frame to the rendering area differently somehow.
Todo:
Implements KODI::RETRO::CGUIRenderTarget.
Member Data Documentation
m_window
CGameWindowFullScreen& KODI::RETRO::CGUIRenderFullScreen::m_window private
Referenced by Render().
The documentation for this class was generated from the following files:
GUIRenderTarget.h
GUIRenderTarget.cpp