Kodi Documentation: CDVDMessageQueue Class Reference
CDVDMessageQueue Class Reference
#include <DVDMessageQueue.h>
Public Member Functions
CDVDMessageQueue (const std::string &owner)
virtual ~CDVDMessageQueue ()
void Init ()
void Flush (CDVDMsg::Message message=CDVDMsg::DEMUXER_PACKET)
void Abort ()
void End ()
MsgQueueReturnCode Put (const std::shared_ptr< CDVDMsg > &pMsg, int priority=0)
MsgQueueReturnCode PutBack (const std::shared_ptr< CDVDMsg > &pMsg, int priority=0)
MsgQueueReturnCode Get (std::shared_ptr< CDVDMsg > &pMsg, std::chrono::milliseconds timeout, int &priority)
MsgQueueReturnCode Get (std::shared_ptr< CDVDMsg > &pMsg, std::chrono::milliseconds timeout)
int GetDataSize () const
double GetTimeSize () const
unsigned GetPacketCount (CDVDMsg::Message type)
bool ReceivedAbortRequest ()
void WaitUntilEmpty ()
bool IsFull () const
int GetLevel () const
void SetMaxDataSize (int iMaxDataSize)
void SetMaxTimeSize (double sec)
int GetMaxDataSize () const
double GetMaxTimeSize () const
bool IsInited () const
bool IsDataBased () const
Private Member Functions
MsgQueueReturnCode Put (const std::shared_ptr< CDVDMsg > &pMsg, int priority, bool front)
void UpdateTimeFront ()
void UpdateTimeBack ()
Private Attributes
CEvent m_hEvent
CCriticalSection m_section
std::atomic< bool > m_bAbortRequest = false
bool m_bInitialized
bool m_drain = false
int m_iDataSize
double m_TimeFront
double m_TimeBack
double m_TimeSize
int m_iMaxDataSize
std::string m_owner
std::list< DVDMessageListItem > m_messages
std::list< DVDMessageListItem > m_prioMessages
Constructor & Destructor Documentation
CDVDMessageQueue()
CDVDMessageQueue::CDVDMessageQueue (const std::string & owner) explicit
References DVD_NOPTS_VALUE, m_bInitialized, m_iDataSize, m_iMaxDataSize, m_TimeBack, m_TimeFront, and m_TimeSize.
~CDVDMessageQueue()
CDVDMessageQueue::~CDVDMessageQueue () virtual
References Flush(), and CDVDMsg::NONE.
Member Function Documentation
Abort()
void CDVDMessageQueue::Abort ()
References m_bAbortRequest, m_hEvent, m_section, and CEvent::Set().
Referenced by CVideoPlayerAudio::CloseStream(), CVideoPlayerAudioID3::CloseStream(), CDVDRadioRDSData::CloseStream(), CDVDTeletextData::CloseStream(), and CVideoPlayerVideo::CloseStream().
End()
void CDVDMessageQueue::End ()
References Flush(), m_bAbortRequest, m_bInitialized, m_iDataSize, m_section, and CDVDMsg::NONE.
Referenced by CVideoPlayerAudio::CloseStream(), CVideoPlayerAudioID3::CloseStream(), CDVDRadioRDSData::CloseStream(), CDVDTeletextData::CloseStream(), CVideoPlayerVideo::CloseStream(), and CVideoPlayer::OnExit().
Flush()
void CDVDMessageQueue::Flush (CDVDMsg::Message message = CDVDMsg::DEMUXER_PACKET)
References CDVDMsg::DEMUXER_PACKET, DVD_NOPTS_VALUE, m_iDataSize, m_messages, m_prioMessages, m_section, m_TimeBack, m_TimeFront, DVDMessageListItem::message, and CDVDMsg::NONE.
Referenced by End(), CVideoPlayerAudioID3::Flush(), CDVDRadioRDSData::Flush(), CDVDTeletextData::Flush(), CVideoPlayerAudio::Flush(), CVideoPlayer::FlushBuffers(), CVideoPlayerAudio::FlushMessages(), CVideoPlayerAudioID3::FlushMessages(), CDVDRadioRDSData::FlushMessages(), CDVDTeletextData::FlushMessages(), CVideoPlayerVideo::FlushMessages(), and ~CDVDMessageQueue().
Get() [1/2]
MsgQueueReturnCode CDVDMessageQueue::Get (std::shared_ptr< CDVDMsg > & pMsg, std::chrono::milliseconds timeout) inline
References Get().
Get() [2/2]
MsgQueueReturnCode CDVDMessageQueue::Get (std::shared_ptr< CDVDMsg > & pMsg, std::chrono::milliseconds timeout, int & priority)
msg, message type from DVDMessage.h timeout, timeout in msec priority, minimum priority to get, outputs returned packets priority
References CDVDMsg::DEMUXER_PACKET, DEMUX_PACKET::iSize, CLog::Log(), LOGFATAL, m_bAbortRequest, m_bInitialized, m_drain, m_hEvent, m_iDataSize, m_messages, m_owner, m_prioMessages, m_section, DVDMessageListItem::message, MSGQ_ABORT, MSGQ_NOT_INITIALIZED, MSGQ_OK, MSGQ_TIMEOUT, DVDMessageListItem::priority, CEvent::Reset(), UpdateTimeBack(), and CEvent::Wait().
Referenced by Get(), CVideoPlayerVideo::GetMessage(), CVideoPlayer::HandleMessages(), CVideoPlayerAudio::Process(), CVideoPlayerAudioID3::Process(), CDVDRadioRDSData::Process(), and CDVDTeletextData::Process().
GetDataSize()
int CDVDMessageQueue::GetDataSize () const inline
References m_iDataSize.
Referenced by CVideoPlayerAudio::HasData(), CVideoPlayerVideo::HasData(), and CVideoPlayerVideo::Process().
GetLevel()
int CDVDMessageQueue::GetLevel () const
References DVD_TIME_BASE, IsDataBased(), CLog::Log(), LOGDEBUG, m_iDataSize, m_iMaxDataSize, m_section, m_TimeBack, m_TimeFront, and m_TimeSize.
Referenced by CVideoPlayerVideo::FlushMessages(), CVideoPlayerAudio::GetLevel(), CVideoPlayerVideo::GetMessage(), IsFull(), CVideoPlayerAudio::Process(), CVideoPlayerVideo::SendMessage(), CVideoPlayerVideo::SendMessageBack(), and CVideoPlayerAudio::UpdatePlayerInfo().
GetMaxDataSize()
int CDVDMessageQueue::GetMaxDataSize () const inline
References m_iMaxDataSize.
GetMaxTimeSize()
double CDVDMessageQueue::GetMaxTimeSize () const inline
References m_TimeSize.
GetPacketCount()
unsigned CDVDMessageQueue::GetPacketCount (CDVDMsg::Message type)
References m_bInitialized, m_messages, m_prioMessages, and m_section.
Referenced by CVideoPlayerVideo::GetOutputDelay(), CVideoPlayer::HandleMessages(), CVideoPlayerVideo::OpenStream(), and CVideoPlayerAudio::OpenStream().
GetTimeSize()
double CDVDMessageQueue::GetTimeSize () const
References DVD_TIME_BASE, IsDataBased(), m_section, m_TimeBack, and m_TimeFront.
Referenced by CVideoPlayerVideo::GetPlayerInfo(), and CVideoPlayerAudio::UpdatePlayerInfo().
Init()
void CDVDMessageQueue::Init ()
References DVD_NOPTS_VALUE, m_bAbortRequest, m_bInitialized, m_drain, m_iDataSize, m_TimeBack, and m_TimeFront.
Referenced by CVideoPlayer::OpenFile(), CVideoPlayerVideo::OpenStream(), CVideoPlayerAudio::OpenStream(), CVideoPlayerAudioID3::OpenStream(), CDVDRadioRDSData::OpenStream(), and CDVDTeletextData::OpenStream().
IsDataBased()
bool CDVDMessageQueue::IsDataBased () const
References DVD_NOPTS_VALUE, m_TimeBack, and m_TimeFront.
Referenced by GetLevel(), and GetTimeSize().
IsFull()
bool CDVDMessageQueue::IsFull () const inline
References GetLevel().
Referenced by CVideoPlayerAudio::AcceptsData(), CVideoPlayerAudioID3::AcceptsData(), CDVDRadioRDSData::AcceptsData(), CDVDTeletextData::AcceptsData(), and CVideoPlayerVideo::AcceptsData().
IsInited()
bool CDVDMessageQueue::IsInited () const inline
References m_bInitialized.
Referenced by CVideoPlayerAudioID3::Flush(), CDVDRadioRDSData::Flush(), CDVDTeletextData::Flush(), CVideoPlayerAudio::IsInited(), CVideoPlayerVideo::IsInited(), CVideoPlayerVideo::OpenStream(), CVideoPlayerAudio::OpenStream(), CVideoPlayerAudioID3::SendMessage(), CDVDRadioRDSData::SendMessage(), CDVDTeletextData::SendMessage(), CVideoPlayerVideo::SetSpeed(), CVideoPlayerAudio::SetSpeed(), and CVideoPlayer::SynchronizeDemuxer().
Put() [1/2]
MsgQueueReturnCode CDVDMessageQueue::Put (const std::shared_ptr< CDVDMsg > & pMsg, int priority, bool front) private
References CDVDMsg::DEMUXER_PACKET, DVD_NOPTS_VALUE, DEMUX_PACKET::iSize, CLog::Log(), LOGFATAL, LOGWARNING, m_bInitialized, m_hEvent, m_iDataSize, m_messages, m_owner, m_prioMessages, m_section, m_TimeBack, m_TimeFront, MSGQ_INVALID_MSG, MSGQ_NOT_INITIALIZED, MSGQ_OK, CEvent::Set(), UpdateTimeBack(), and UpdateTimeFront().
Put() [2/2]
MsgQueueReturnCode CDVDMessageQueue::Put (const std::shared_ptr< CDVDMsg > & pMsg, int priority = 0)
References Put().
Referenced by CVideoPlayer::AddSubtitle(), CVideoPlayer::CheckAutoSceneSkip(), CVideoPlayerAudioID3::Flush(), CDVDRadioRDSData::Flush(), CDVDTeletextData::Flush(), CVideoPlayerAudio::Flush(), CVideoPlayer::FrameAdvance(), CVideoPlayer::HandleMessages(), CVideoPlayer::HandlePlaySpeed(), CVideoPlayer::OnAction(), CVideoPlayer::OnDiscNavResult(), CVideoPlayer::OpenFile(), CVideoPlayerVideo::OpenStream(), CVideoPlayerAudio::OpenStream(), CVideoPlayerAudio::OpenStream(), CVideoPlayerVideo::OutputPicture(), CVideoPlayerAudio::Process(), CVideoPlayerVideo::Process(), CVideoPlayerVideo::ProcessDecoderOutput(), CVideoPlayerAudio::ProcessDecoderOutput(), Put(), PutBack(), CVideoPlayer::Seek(), CVideoPlayer::SeekChapter(), CVideoPlayer::SeekScene(), CVideoPlayer::SeekTime(), CVideoPlayer::SeekTimeRelative(), CVideoPlayerAudio::SendMessage(), CVideoPlayerAudioID3::SendMessage(), CDVDRadioRDSData::SendMessage(), CDVDTeletextData::SendMessage(), CVideoPlayerVideo::SendMessage(), CVideoPlayer::SetAudioStream(), CVideoPlayer::SetPlayerState(), CVideoPlayer::SetPlaySpeed(), CVideoPlayer::SetProgram(), CVideoPlayerAudio::SetSpeed(), CVideoPlayer::SetSubtitle(), CVideoPlayer::SetSubtitleVisible(), CVideoPlayer::SetTempo(), CVideoPlayer::SetUpdateStreamDetails(), CVideoPlayer::SetVideoStream(), CVideoPlayer::SynchronizeDemuxer(), CVideoPlayer::VideoParamsChange(), and WaitUntilEmpty().
PutBack()
MsgQueueReturnCode CDVDMessageQueue::PutBack (const std::shared_ptr< CDVDMsg > & pMsg, int priority = 0)
References Put().
Referenced by CVideoPlayerAudio::Process(), and CVideoPlayerVideo::SendMessageBack().
ReceivedAbortRequest()
bool CDVDMessageQueue::ReceivedAbortRequest () inline
References m_bAbortRequest.
Referenced by CVideoPlayerAudio::Process(), CVideoPlayerAudioID3::Process(), CDVDRadioRDSData::Process(), CDVDTeletextData::Process(), and CVideoPlayerVideo::Process().
SetMaxDataSize()
void CDVDMessageQueue::SetMaxDataSize (int iMaxDataSize) inline
References m_iMaxDataSize.
Referenced by CDVDRadioRDSData::CDVDRadioRDSData(), CDVDTeletextData::CDVDTeletextData(), CVideoPlayerAudio::CVideoPlayerAudio(), and CVideoPlayerVideo::CVideoPlayerVideo().
SetMaxTimeSize()
void CDVDMessageQueue::SetMaxTimeSize (double sec) inline
References m_TimeSize.
Referenced by CVideoPlayerAudio::CVideoPlayerAudio(), and CVideoPlayerVideo::CVideoPlayerVideo().
UpdateTimeBack()
void CDVDMessageQueue::UpdateTimeBack () private
References CDVDMsg::DEMUXER_PACKET, DEMUX_PACKET::dts, DVD_NOPTS_VALUE, m_messages, m_TimeBack, m_TimeFront, and DEMUX_PACKET::pts.
Referenced by Get(), and Put().
UpdateTimeFront()
void CDVDMessageQueue::UpdateTimeFront () private
References CDVDMsg::DEMUXER_PACKET, DEMUX_PACKET::dts, DVD_NOPTS_VALUE, m_messages, m_TimeBack, m_TimeFront, and DEMUX_PACKET::pts.
Referenced by Put().
WaitUntilEmpty()
void CDVDMessageQueue::WaitUntilEmpty ()
References CLog::Log(), LOGINFO, m_bAbortRequest, m_drain, m_owner, m_section, Put(), and SYNCSOURCE_ANY.
Referenced by CVideoPlayerAudio::CloseStream(), CVideoPlayerVideo::CloseStream(), CVideoPlayerAudioID3::WaitForBuffers(), CDVDRadioRDSData::WaitForBuffers(), and CDVDTeletextData::WaitForBuffers().
Member Data Documentation
m_bAbortRequest
std::atomic<bool> CDVDMessageQueue::m_bAbortRequest = false private
Referenced by Abort(), End(), Get(), Init(), ReceivedAbortRequest(), and WaitUntilEmpty().
m_bInitialized
bool CDVDMessageQueue::m_bInitialized private
Referenced by CDVDMessageQueue(), End(), Get(), GetPacketCount(), Init(), IsInited(), and Put().
m_drain
bool CDVDMessageQueue::m_drain = false private
Referenced by Get(), Init(), and WaitUntilEmpty().
m_hEvent
CEvent CDVDMessageQueue::m_hEvent private
Referenced by Abort(), Get(), and Put().
m_iDataSize
int CDVDMessageQueue::m_iDataSize private
Referenced by CDVDMessageQueue(), End(), Flush(), Get(), GetDataSize(), GetLevel(), Init(), and Put().
m_iMaxDataSize
int CDVDMessageQueue::m_iMaxDataSize private
Referenced by CDVDMessageQueue(), GetLevel(), GetMaxDataSize(), and SetMaxDataSize().
m_messages
std::list<DVDMessageListItem> CDVDMessageQueue::m_messages private
Referenced by Flush(), Get(), GetPacketCount(), Put(), UpdateTimeBack(), and UpdateTimeFront().
m_owner
std::string CDVDMessageQueue::m_owner private
Referenced by Get(), Put(), and WaitUntilEmpty().
m_prioMessages
std::list<DVDMessageListItem> CDVDMessageQueue::m_prioMessages private
Referenced by Flush(), Get(), GetPacketCount(), and Put().
m_section
CCriticalSection CDVDMessageQueue::m_section mutable private
Referenced by Abort(), End(), Flush(), Get(), GetLevel(), GetPacketCount(), GetTimeSize(), Put(), and WaitUntilEmpty().
m_TimeBack
double CDVDMessageQueue::m_TimeBack private
Referenced by CDVDMessageQueue(), Flush(), GetLevel(), GetTimeSize(), Init(), IsDataBased(), Put(), UpdateTimeBack(), and UpdateTimeFront().
m_TimeFront
double CDVDMessageQueue::m_TimeFront private
Referenced by CDVDMessageQueue(), Flush(), GetLevel(), GetTimeSize(), Init(), IsDataBased(), Put(), UpdateTimeBack(), and UpdateTimeFront().
m_TimeSize
double CDVDMessageQueue::m_TimeSize private
Referenced by CDVDMessageQueue(), GetLevel(), GetMaxTimeSize(), and SetMaxTimeSize().
The documentation for this class was generated from the following files:
DVDMessageQueue.h
DVDMessageQueue.cpp