Kodi Documentation: DRMPRIME Namespace Reference
DRMPRIME Namespace Reference
Enumerations
enum hdmi_metadata_type { HDMI_STATIC_METADATA_TYPE1 = 0 }
enum hdmi_eotf { HDMI_EOTF_TRADITIONAL_GAMMA_SDR , HDMI_EOTF_TRADITIONAL_GAMMA_HDR , HDMI_EOTF_SMPTE_ST2084 , HDMI_EOTF_BT_2100_HLG }
Functions
KODI::UTILS::Colorimetry GetColorimetry (const VideoPicture &picture)
std::string GetColorEncoding (const VideoPicture &picture)
std::string GetColorRange (const VideoPicture &picture)
KODI::UTILS::Eotf GetEOTF (const VideoPicture &picture)
const AVMasteringDisplayMetadata * GetMasteringDisplayMetadata (const VideoPicture &picture)
const AVContentLightMetadata * GetContentLightMetadata (const VideoPicture &picture)
Enumeration Type Documentation
hdmi_eotf
enum DRMPRIME::hdmi_eotf
Enumerator
HDMI_EOTF_TRADITIONAL_GAMMA_SDR
HDMI_EOTF_TRADITIONAL_GAMMA_HDR
HDMI_EOTF_SMPTE_ST2084
HDMI_EOTF_BT_2100_HLG
hdmi_metadata_type
enum DRMPRIME::hdmi_metadata_type
Enumerator
HDMI_STATIC_METADATA_TYPE1
Function Documentation
GetColorEncoding()
std::string DRMPRIME::GetColorEncoding (const VideoPicture & picture)
References VideoPicture::color_space, VideoPicture::iHeight, and VideoPicture::iWidth.
Referenced by CVideoLayerBridgeDRMPRIME::Configure().
GetColorimetry()
KODI::UTILS::Colorimetry DRMPRIME::GetColorimetry (const VideoPicture & picture)
References KODI::UTILS::BT2020_CYCC, KODI::UTILS::BT2020_YCC, VideoPicture::color_space, and KODI::UTILS::DEFAULT.
Referenced by KODI::WINDOWING::GBM::CWinSystemGbm::SetHDR().
GetColorRange()
std::string DRMPRIME::GetColorRange (const VideoPicture & picture)
References VideoPicture::color_range.
Referenced by CVideoLayerBridgeDRMPRIME::Configure().
GetContentLightMetadata()
const AVContentLightMetadata * DRMPRIME::GetContentLightMetadata (const VideoPicture & picture)
References VideoPicture::hasLightMetadata, and VideoPicture::lightMetadata.
Referenced by KODI::WINDOWING::GBM::CWinSystemGbm::SetHDR().
GetEOTF()
KODI::UTILS::Eotf DRMPRIME::GetEOTF (const VideoPicture & picture)
References VideoPicture::color_transfer, KODI::UTILS::HLG, KODI::UTILS::PQ, and KODI::UTILS::TRADITIONAL_SDR.
Referenced by KODI::WINDOWING::GBM::CWinSystemGbm::SetHDR().
GetMasteringDisplayMetadata()
const AVMasteringDisplayMetadata * DRMPRIME::GetMasteringDisplayMetadata (const VideoPicture & picture)
References VideoPicture::displayMetadata, and VideoPicture::hasDisplayMetadata.
Referenced by KODI::WINDOWING::GBM::CWinSystemGbm::SetHDR().