Kodi Documentation: CONTEXTMENU::CEjectDrive Struct Reference
CONTEXTMENU::CEjectDrive Struct Reference
#include <ContextMenus.h>
Public Member Functions
CEjectDrive ()
bool IsVisible (const CFileItem &item) const override
bool Execute (const std::shared_ptr< CFileItem > &item) const override
Public Member Functions inherited from CStaticContextMenuAction
CStaticContextMenuAction (uint32_t label)
std::string GetLabel (const CFileItem &item) const final
bool IsGroup () const final
Public Member Functions inherited from IContextMenuItem
virtual ~IContextMenuItem ()=default
virtual bool HasParent () const
Constructor & Destructor Documentation
CEjectDrive()
CONTEXTMENU::CEjectDrive::CEjectDrive () inline
Member Function Documentation
Execute()
bool CONTEXTMENU::CEjectDrive::Execute (const std::shared_ptr< CFileItem > & item) const override virtual
Implements IContextMenuItem.
References CMediaManager::Eject(), and CServiceBroker::GetMediaManager().
IsVisible()
bool CONTEXTMENU::CEjectDrive::IsVisible (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References KODI::MUSIC::IsCDDA(), CFileItem::IsDVD(), and CFileItem::IsRemovable().
The documentation for this struct was generated from the following files:
ContextMenus.h
ContextMenus.cpp