Kodi Documentation: PVR::CPVRChannelGroupFactory Class Reference
PVR::CPVRChannelGroupFactory Class Reference
#include <PVRChannelGroupFactory.h>
Public Member Functions
CPVRChannelGroupFactory ()=default
virtual ~CPVRChannelGroupFactory ()=default
std::shared_ptr< CPVRChannelGroup > CreateAllChannelsGroup (bool isRadio)
Create an all channels group instance.
std::shared_ptr< CPVRChannelGroup > CreateClientGroup (const PVR_CHANNEL_GROUP &groupData, int clientID, const std::shared_ptr< const CPVRChannelGroup > &allChannels)
Create an instance for a group provided by a PVR client add-on.
std::shared_ptr< CPVRChannelGroup > CreateUserGroup (bool isRadio, const std::string &name, const std::shared_ptr< const CPVRChannelGroup > &allChannels)
Create an instance for a group created by the user.
std::shared_ptr< CPVRChannelGroup > CreateGroup (int groupType, const CPVRChannelsPath &groupPath, const std::shared_ptr< const CPVRChannelGroup > &allChannels)
Create a channel group matching the given type.
int GetGroupTypePriority (const std::shared_ptr< const CPVRChannelGroup > &group) const
Get the priority (e.g. for sorting groups) for the type of the given group. Lower number means higer priority.
std::vector< std::shared_ptr< CPVRChannelGroup > > CreateMissingGroups (const std::shared_ptr< CPVRChannelGroup > &allChannelsGroup, const std::vector< std::shared_ptr< CPVRChannelGroup > > &allChannelGroups)
Create any missing channel groups (e.g. after an update of groups/members/clients).
Constructor & Destructor Documentation
CPVRChannelGroupFactory()
PVR::CPVRChannelGroupFactory::CPVRChannelGroupFactory () default
~CPVRChannelGroupFactory()
virtual PVR::CPVRChannelGroupFactory::~CPVRChannelGroupFactory () virtual default
Member Function Documentation
CreateAllChannelsGroup()
std::shared_ptr< CPVRChannelGroup > CPVRChannelGroupFactory::CreateAllChannelsGroup (bool isRadio)
Create an all channels group instance.
Parameters
isRadio Whether Radio or TV.
Returns
The new group.
CreateClientGroup()
std::shared_ptr< CPVRChannelGroup > CPVRChannelGroupFactory::CreateClientGroup (const PVR_CHANNEL_GROUP & groupData, int clientID, const std::shared_ptr< const CPVRChannelGroup > & allChannels)
Create an instance for a group provided by a PVR client add-on.
Parameters
groupData The group data.
clientID The id of the client that provided the group.
allChannels The all channels group.
Returns
The new group.
CreateGroup()
std::shared_ptr< CPVRChannelGroup > CPVRChannelGroupFactory::CreateGroup (int groupType, const CPVRChannelsPath & groupPath, const std::shared_ptr< const CPVRChannelGroup > & allChannels)
Create a channel group matching the given type.
Parameters
groupType The type of the group.
groupPath The path of the group.
allChannels The all channels group.
Returns
The new group.
References PVR::CPVRChannelsPath::GetGroupName(), LOGERROR, LOGPVR, PVR::PVR_GROUP_TYPE_CLIENT, PVR::PVR_GROUP_TYPE_SYSTEM_ALL_CHANNELS_ALL_CLIENTS, PVR::PVR_GROUP_TYPE_SYSTEM_ALL_CHANNELS_SINGLE_CLIENT, PVR::PVR_GROUP_TYPE_SYSTEM_MERGED_BY_NAME, and PVR::PVR_GROUP_TYPE_USER.
CreateMissingGroups()
std::vector< std::shared_ptr< CPVRChannelGroup > > CPVRChannelGroupFactory::CreateMissingGroups (const std::shared_ptr< CPVRChannelGroup > & allChannelsGroup, const std::vector< std::shared_ptr< CPVRChannelGroup > > & allChannelGroups)
Create any missing channel groups (e.g. after an update of groups/members/clients).
Parameters
allChannelsGroup The all channels group.
allChannelGroups All channel groups.
Returns
The newly created groups, if any.
References PVR::CPVRChannelGroupAllChannelsSingleClient::CreateMissingGroups(), and PVR::CPVRChannelGroupMergedByName::CreateMissingGroups().
CreateUserGroup()
std::shared_ptr< CPVRChannelGroup > CPVRChannelGroupFactory::CreateUserGroup (bool isRadio, const std::string & name, const std::shared_ptr< const CPVRChannelGroup > & allChannels)
Create an instance for a group created by the user.
Parameters
isRadio Whether Radio or TV.
name The name for the group.
allChannels The all channels group.
Returns
The new group.
References name, and PVR::PVR_GROUP_CLIENT_ID_LOCAL.
GetGroupTypePriority()
int CPVRChannelGroupFactory::GetGroupTypePriority (const std::shared_ptr< const CPVRChannelGroup > & group) const
Get the priority (e.g. for sorting groups) for the type of the given group. Lower number means higer priority.
Parameters
group The group.
Returns
The group's type priority.
References LOGPVR, LOGWARNING, PVR::PVR_GROUP_TYPE_CLIENT, PVR::PVR_GROUP_TYPE_SYSTEM_ALL_CHANNELS_ALL_CLIENTS, PVR::PVR_GROUP_TYPE_SYSTEM_ALL_CHANNELS_SINGLE_CLIENT, PVR::PVR_GROUP_TYPE_SYSTEM_MERGED_BY_NAME, and PVR::PVR_GROUP_TYPE_USER.
The documentation for this class was generated from the following files:
PVRChannelGroupFactory.h
PVRChannelGroupFactory.cpp