Kodi Documentation: CVideoTagLoaderNFO Class Reference
CVideoTagLoaderNFO Class Reference
Video tag loader using nfo files.
#include <VideoTagLoaderNFO.h>
Public Member Functions
CVideoTagLoaderNFO (const CFileItem &item, ADDON::ScraperPtr info, bool lookInFolder)
~CVideoTagLoaderNFO () override=default
bool HasInfo () const override
Returns whether or not read has info.
CInfoScanner::INFO_TYPE Load (CVideoInfoTag &tag, bool prioritise, std::vector< EmbeddedArt > *=nullptr) override
Load "tag" from nfo file.
Public Member Functions inherited from KODI::VIDEO::IVideoInfoTagLoader
IVideoInfoTagLoader (const CFileItem &item, ADDON::ScraperPtr info, bool lookInFolder)
Constructor.
virtual ~IVideoInfoTagLoader ()=default
const CScraperUrl & ScraperUrl () const
Returns url associated with obtained URL (NFO_URL et al).
const ADDON::ScraperPtr GetAddonInfo () const
Returns current scaper info.
Protected Member Functions
std::string FindNFO (const CFileItem &item, bool movieFolder) const
Find nfo file for item.
Protected Attributes
std::string m_path
Path to nfo file.
Protected Attributes inherited from KODI::VIDEO::IVideoInfoTagLoader
const CFileItem & m_item
Reference to item to load for.
ADDON::ScraperPtr m_info
Scraper info.
CScraperUrl m_url
URL for scraper.
Detailed Description
Video tag loader using nfo files.
Constructor & Destructor Documentation
CVideoTagLoaderNFO()
CVideoTagLoaderNFO::CVideoTagLoaderNFO (const CFileItem & item, ADDON::ScraperPtr info, bool lookInFolder)
References URIUtils::AddFileToFolder(), CONTENT_TVSHOWS, FindNFO(), CFileItem::GetPath(), CGUIListItem::m_bIsFolder, KODI::VIDEO::IVideoInfoTagLoader::m_info, KODI::VIDEO::IVideoInfoTagLoader::m_item, and m_path.
~CVideoTagLoaderNFO()
CVideoTagLoaderNFO::~CVideoTagLoaderNFO () override default
Member Function Documentation
FindNFO()
std::string CVideoTagLoaderNFO::FindNFO (const CFileItem & item, bool movieFolder) const protected
Find nfo file for item.
Parameters
item The item to find NFO file for
movieFolder If true, look for movie.nfo
References URIUtils::AddFileToFolder(), XFILE::DIR_FLAG_DEFAULTS, CFileUtils::Exists(), FindNFO(), XFILE::CDirectory::GetDirectory(), URIUtils::GetDirectory(), URIUtils::GetFileName(), XFILE::CStackDirectory::GetFirstStackedFile(), CURL::GetHostName(), CFileItem::GetLocalMetadataPath(), CFileItem::GetPath(), XFILE::CStackDirectory::GetStackedTitlePath(), URIUtils::HasExtension(), URIUtils::IsInRAR(), CFileItem::IsOpticalMediaFile(), CFileItem::IsStack(), CGUIListItem::m_bIsFolder, URIUtils::RemoveSlashAtEnd(), URIUtils::ReplaceExtension(), CFileItem::SetPath(), and CFileItemList::Size().
Referenced by CVideoTagLoaderNFO(), and FindNFO().
HasInfo()
bool CVideoTagLoaderNFO::HasInfo () const override virtual
Returns whether or not read has info.
Implements KODI::VIDEO::IVideoInfoTagLoader.
References CFileUtils::Exists(), and m_path.
Referenced by KODI::VIDEO::CVideoInfoTagLoaderFactory::CreateLoader().
Load()
CInfoScanner::INFO_TYPE CVideoTagLoaderNFO::Load (CVideoInfoTag & tag, bool prioritise, std::vector< EmbeddedArt > * = nullptr) override virtual
Load "tag" from nfo file.
tag Tag to load info into
Implements KODI::VIDEO::IVideoInfoTagLoader.
References CInfoScanner::COMBINED_NFO, CONTENT_TVSHOWS, CNfoFile::Create(), CInfoScanner::FULL_NFO, CNfoFile::GetDetails(), CFileItem::GetPath(), CNfoFile::GetScraperInfo(), CFileItem::GetVideoInfoTag(), CLog::Log(), LOGDEBUG, CGUIListItem::m_bIsFolder, CVideoInfoTag::m_iEpisode, KODI::VIDEO::IVideoInfoTagLoader::m_info, KODI::VIDEO::IVideoInfoTagLoader::m_item, m_path, KODI::VIDEO::IVideoInfoTagLoader::m_url, CInfoScanner::NO_NFO, CInfoScanner::OVERRIDE_NFO, CNfoFile::ScraperUrl(), and CInfoScanner::URL_NFO.
Member Data Documentation
m_path
std::string CVideoTagLoaderNFO::m_path protected
Path to nfo file.
Referenced by CVideoTagLoaderNFO(), HasInfo(), and Load().
The documentation for this class was generated from the following files:
VideoTagLoaderNFO.h
VideoTagLoaderNFO.cpp