Kodi Documentation: anonymous_namespace{ZeroconfDirectory.cpp} Namespace Reference
anonymous_namespace{ZeroconfDirectory.cpp} Namespace Reference
Functions
std::string GetHumanReadableProtocol (std::string const &fcr_service_type)
bool GetXBMCProtocol (std::string const &fcr_service_type, std::string &fr_protocol)
Function Documentation
GetHumanReadableProtocol()
std::string anonymous_namespace{ZeroconfDirectory.cpp}::GetHumanReadableProtocol (std::string const & fcr_service_type)
References GetHumanReadableProtocol().
Referenced by GetHumanReadableProtocol().
GetXBMCProtocol()
bool anonymous_namespace{ZeroconfDirectory.cpp}::GetXBMCProtocol (std::string const & fcr_service_type, std::string & fr_protocol)
References GetXBMCProtocol().
Referenced by GetXBMCProtocol().