Kodi Documentation: CAlarmClock Class Reference
CAlarmClock Class Reference
#include <AlarmClock.h>
Public Member Functions
CAlarmClock ()
~CAlarmClock () override
void Start (const std::string &strName, float n_secs, const std::string &strCommand, bool bSilent=false, bool bLoop=false)
bool IsRunning () const
bool HasAlarm (const std::string &strName)
double GetRemaining (const std::string &strName)
void Stop (const std::string &strName, bool bSilent=false)
void Process () override
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Private Attributes
std::map< std::string, SAlarmClockEvent > m_event
CCriticalSection m_events
bool m_bIsRunning = false
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CAlarmClock()
CAlarmClock::CAlarmClock ()
~CAlarmClock()
CAlarmClock::~CAlarmClock () override default
Member Function Documentation
GetRemaining()
double CAlarmClock::GetRemaining (const std::string & strName) inline
References m_event.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), and TEST().
HasAlarm()
bool CAlarmClock::HasAlarm (const std::string & strName) inline
References m_event.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), CApplicationPowerHandling::ResetShutdownTimers(), and TEST().
IsRunning()
bool CAlarmClock::IsRunning () const inline
References m_bIsRunning.
Referenced by anonymous_namespace{GUIBuiltins.cpp}::AlarmClock(), and TEST().
Process()
void CAlarmClock::Process (void) override virtual
Reimplemented from CThread.
References CThread::m_bStop, m_event, m_events, CThread::Sleep(), and Stop().
Start()
void CAlarmClock::Start (const std::string & strName, float n_secs, const std::string & strCommand, bool bSilent = false, bool bLoop = false)
References CThread::Create(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetEventLog(), CLog::Log(), LOGDEBUG, m_bIsRunning, m_event, m_events, SAlarmClockEvent::m_fSecs, Stop(), and CThread::StopThread().
Referenced by anonymous_namespace{GUIBuiltins.cpp}::AlarmClock(), TEST(), and CApplicationPowerHandling::WakeUpScreenSaver().
Stop()
void CAlarmClock::Stop (const std::string & strName, bool bSilent = false)
References g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetEventLog(), m_event, m_events, and TMSG_EXECUTE_BUILT_IN.
Referenced by CApplicationPowerHandling::ActivateScreenSaver(), anonymous_namespace{GUIBuiltins.cpp}::AlarmClock(), anonymous_namespace{GUIBuiltins.cpp}::CancelAlarm(), Process(), CApplicationPowerHandling::ResetShutdownTimers(), Start(), and TEST().
Member Data Documentation
m_bIsRunning
bool CAlarmClock::m_bIsRunning = false private
Referenced by IsRunning(), and Start().
m_event
std::map<std::string,SAlarmClockEvent> CAlarmClock::m_event private
Referenced by GetRemaining(), HasAlarm(), Process(), Start(), and Stop().
m_events
CCriticalSection CAlarmClock::m_events private
Referenced by Process(), Start(), and Stop().
The documentation for this class was generated from the following files:
AlarmClock.h
AlarmClock.cpp