Kodi Documentation: UPNP::CMediaBrowser Class Reference
UPNP::CMediaBrowser Class Reference
Public Member Functions
CMediaBrowser (PLT_CtrlPointReference &ctrlPoint)
bool OnMSAdded (PLT_DeviceDataReference &device) override
void OnMSRemoved (PLT_DeviceDataReference &device) override
void OnContainerChanged (PLT_DeviceDataReference &device, const char *item_id, const char *update_id) override
bool MarkWatched (const CFileItem &item, const bool watched)
bool SaveFileState (const CFileItem &item, const CBookmark &bookmark, const bool updatePlayCount)
bool UpdateItem (const std::string &path, const CFileItem &item)
bool InvokeUpdateObject (const char *id, const std::set< std::pair< NPT_String, NPT_String > > &values)
Private Attributes
Logger m_logger
Constructor & Destructor Documentation
CMediaBrowser()
UPNP::CMediaBrowser::CMediaBrowser (PLT_CtrlPointReference & ctrlPoint) inline explicit
Member Function Documentation
InvokeUpdateObject()
bool UPNP::CMediaBrowser::InvokeUpdateObject (const char * id, const std::set< std::pair< NPT_String, NPT_String > > & values) inline
References CURL::GetFileName(), CURL::GetHostName(), m_logger, value, and values.
Referenced by MarkWatched(), SaveFileState(), and UpdateItem().
MarkWatched()
bool UPNP::CMediaBrowser::MarkWatched (const CFileItem & item, const bool watched) inline
References CFileItem::GetPath(), InvokeUpdateObject(), m_logger, SaveFileState(), CGUIListItem::SetProperty(), and values.
Referenced by UPNP::CUPnP::MarkWatched().
OnContainerChanged()
void UPNP::CMediaBrowser::OnContainerChanged (PLT_DeviceDataReference & device, const char * item_id, const char * update_id) inline override
References URIUtils::AddSlashAtEnd(), CServiceBroker::GetAnnouncementManager(), id, m_logger, and ANNOUNCEMENT::Sources.
OnMSAdded()
bool UPNP::CMediaBrowser::OnMSAdded (PLT_DeviceDataReference & device) inline override
References CServiceBroker::GetAnnouncementManager(), and ANNOUNCEMENT::Sources.
OnMSRemoved()
void UPNP::CMediaBrowser::OnMSRemoved (PLT_DeviceDataReference & device) inline override
References CServiceBroker::GetAnnouncementManager(), and ANNOUNCEMENT::Sources.
SaveFileState()
bool UPNP::CMediaBrowser::SaveFileState (const CFileItem & item, const CBookmark & bookmark, const bool updatePlayCount) inline
References CVariant::asString(), CGUIListItem::GetProperty(), CVideoInfoTag::GetResumePoint(), CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), InvokeUpdateObject(), m_logger, CBookmark::playerState, CBookmark::timeInSeconds, and values.
Referenced by MarkWatched(), and UPNP::CUPnP::SaveFileState().
UpdateItem()
bool UPNP::CMediaBrowser::UpdateItem (const std::string & path, const CFileItem & item) inline
References CDateTime::GetAsW3CDateTime(), CDateTime::GetCurrentDateTime(), CVideoInfoTag::GetPlayCount(), CVideoInfoTag::GetResumePoint(), CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), InvokeUpdateObject(), CDateTime::IsValid(), CVideoInfoTag::m_lastPlayed, CBookmark::timeInSeconds, and values.
Referenced by UPNP::CUPnP::UpdateItem().
Member Data Documentation
m_logger
Logger UPNP::CMediaBrowser::m_logger private
Referenced by InvokeUpdateObject(), MarkWatched(), OnContainerChanged(), and SaveFileState().
The documentation for this class was generated from the following file:
UPnP.cpp