Kodi Documentation: anonymous_namespace{PVRGUIActionsTimers.cpp} Namespace Reference
anonymous_namespace{PVRGUIActionsTimers.cpp} Namespace Reference
Classes
class AsyncUpdateTimer
class InstantRecordingActionSelector
Enumerations
enum PVRRECORD_INSTANTRECORDACTION {
NONE = -1 , RECORD_CURRENT_SHOW = 0 , RECORD_INSTANTRECORDTIME = 1 , ASK = 2 ,
RECORD_30_MINUTES = 3 , RECORD_60_MINUTES = 4 , RECORD_120_MINUTES = 5 , RECORD_NEXT_SHOW = 6
}
Functions
std::string GetAnnouncerText (const std::shared_ptr< const CPVRTimerInfoTag > &timer, int idEpg, int idNoEpg)
void AddEventLogEntry (const std::shared_ptr< const CPVRTimerInfoTag > &timer, int idEpg, int idNoEpg)
Enumeration Type Documentation
PVRRECORD_INSTANTRECORDACTION
enum anonymous_namespace{PVRGUIActionsTimers.cpp}::PVRRECORD_INSTANTRECORDACTION private
Enumerator
NONE
RECORD_CURRENT_SHOW
RECORD_INSTANTRECORDTIME
ASK
RECORD_30_MINUTES
RECORD_60_MINUTES
RECORD_120_MINUTES
RECORD_NEXT_SHOW
Function Documentation
AddEventLogEntry()
void anonymous_namespace{PVRGUIActionsTimers.cpp}::AddEventLogEntry (const std::shared_ptr< const CPVRTimerInfoTag > & timer, int idEpg, int idNoEpg) private
References PVR::CPVREventLogJob::AddEvent(), g_sysinfo, GetAnnouncerText(), CSysInfo::GetAppName(), PVR::CPVRManager::GetClient(), CServiceBroker::GetJobManager(), CServiceBroker::GetPVRManager(), Information, and name.
Referenced by PVR::CPVRGUIActionsTimers::AnnounceReminder().
GetAnnouncerText()
std::string anonymous_namespace{PVRGUIActionsTimers.cpp}::GetAnnouncerText (const std::shared_ptr< const CPVRTimerInfoTag > & timer, int idEpg, int idNoEpg) private
References g_localizeStrings, CLocalizeStrings::Get(), and text.
Referenced by AddEventLogEntry(), and PVR::CPVRGUIActionsTimers::AnnounceReminder().