Kodi Documentation: jni::CJNIXBMCNsdManagerDiscoveryListener Class Reference
jni::CJNIXBMCNsdManagerDiscoveryListener Class Reference abstract
#include <JNIXBMCNsdManagerDiscoveryListener.h>
Public Member Functions
CJNIXBMCNsdManagerDiscoveryListener ()
CJNIXBMCNsdManagerDiscoveryListener (const CJNIXBMCNsdManagerDiscoveryListener &other)
CJNIXBMCNsdManagerDiscoveryListener (const jni::jhobject &object)
~CJNIXBMCNsdManagerDiscoveryListener () override
void onDiscoveryStarted (const std::string &serviceType) override=0
void onDiscoveryStopped (const std::string &serviceType) override=0
void onServiceFound (const CJNINsdServiceInfo &serviceInfo) override=0
void onServiceLost (const CJNINsdServiceInfo &serviceInfo) override=0
void onStartDiscoveryFailed (const std::string &serviceType, int errorCode) override=0
void onStopDiscoveryFailed (const std::string &serviceType, int errorCode) override=0
Static Public Member Functions
static void RegisterNatives (JNIEnv *env)
Static Protected Member Functions
static void _onDiscoveryStarted (JNIEnv *env, jobject thiz, jstring serviceType)
static void _onDiscoveryStopped (JNIEnv *env, jobject thiz, jstring serviceType)
static void _onServiceFound (JNIEnv *env, jobject thiz, jobject serviceInfo)
static void _onServiceLost (JNIEnv *env, jobject thiz, jobject serviceInfo)
static void _onStartDiscoveryFailed (JNIEnv *env, jobject thiz, jstring serviceType, jint errorCode)
static void _onStopDiscoveryFailed (JNIEnv *env, jobject thiz, jstring serviceType, jint errorCode)
Constructor & Destructor Documentation
CJNIXBMCNsdManagerDiscoveryListener() [1/3]
CJNIXBMCNsdManagerDiscoveryListener::CJNIXBMCNsdManagerDiscoveryListener ()
References s_className.
CJNIXBMCNsdManagerDiscoveryListener() [2/3]
CJNIXBMCNsdManagerDiscoveryListener::CJNIXBMCNsdManagerDiscoveryListener (const CJNIXBMCNsdManagerDiscoveryListener & other)
CJNIXBMCNsdManagerDiscoveryListener() [3/3]
jni::CJNIXBMCNsdManagerDiscoveryListener::CJNIXBMCNsdManagerDiscoveryListener (const jni::jhobject & object) inline explicit
~CJNIXBMCNsdManagerDiscoveryListener()
CJNIXBMCNsdManagerDiscoveryListener::~CJNIXBMCNsdManagerDiscoveryListener () override
Member Function Documentation
_onDiscoveryStarted()
void CJNIXBMCNsdManagerDiscoveryListener::_onDiscoveryStarted (JNIEnv * env, jobject thiz, jstring serviceType) static protected
References CLog::Log(), LOGDEBUG, and void().
Referenced by RegisterNatives().
_onDiscoveryStopped()
void CJNIXBMCNsdManagerDiscoveryListener::_onDiscoveryStopped (JNIEnv * env, jobject thiz, jstring serviceType) static protected
References CLog::Log(), LOGDEBUG, and void().
Referenced by RegisterNatives().
_onServiceFound()
void CJNIXBMCNsdManagerDiscoveryListener::_onServiceFound (JNIEnv * env, jobject thiz, jobject serviceInfo) static protected
References onServiceFound().
Referenced by RegisterNatives().
_onServiceLost()
void CJNIXBMCNsdManagerDiscoveryListener::_onServiceLost (JNIEnv * env, jobject thiz, jobject serviceInfo) static protected
References onServiceLost().
Referenced by RegisterNatives().
_onStartDiscoveryFailed()
void CJNIXBMCNsdManagerDiscoveryListener::_onStartDiscoveryFailed (JNIEnv * env, jobject thiz, jstring serviceType, jint errorCode) static protected
References onStartDiscoveryFailed(), and void().
Referenced by RegisterNatives().
_onStopDiscoveryFailed()
void CJNIXBMCNsdManagerDiscoveryListener::_onStopDiscoveryFailed (JNIEnv * env, jobject thiz, jstring serviceType, jint errorCode) static protected
References onStopDiscoveryFailed(), and void().
Referenced by RegisterNatives().
onDiscoveryStarted()
void jni::CJNIXBMCNsdManagerDiscoveryListener::onDiscoveryStarted (const std::string & serviceType) override pure virtual
Implemented in CZeroconfBrowserAndroidDiscover.
onDiscoveryStopped()
void jni::CJNIXBMCNsdManagerDiscoveryListener::onDiscoveryStopped (const std::string & serviceType) override pure virtual
Implemented in CZeroconfBrowserAndroidDiscover.
onServiceFound()
void jni::CJNIXBMCNsdManagerDiscoveryListener::onServiceFound (const CJNINsdServiceInfo & serviceInfo) override pure virtual
Referenced by _onServiceFound().
onServiceLost()
void jni::CJNIXBMCNsdManagerDiscoveryListener::onServiceLost (const CJNINsdServiceInfo & serviceInfo) override pure virtual
Referenced by _onServiceLost().
onStartDiscoveryFailed()
void jni::CJNIXBMCNsdManagerDiscoveryListener::onStartDiscoveryFailed (const std::string & serviceType, int errorCode) override pure virtual
Implemented in CZeroconfBrowserAndroidDiscover.
Referenced by _onStartDiscoveryFailed().
onStopDiscoveryFailed()
void jni::CJNIXBMCNsdManagerDiscoveryListener::onStopDiscoveryFailed (const std::string & serviceType, int errorCode) override pure virtual
Implemented in CZeroconfBrowserAndroidDiscover.
Referenced by _onStopDiscoveryFailed().
RegisterNatives()
void CJNIXBMCNsdManagerDiscoveryListener::RegisterNatives (JNIEnv * env) static
References _onDiscoveryStarted(), _onDiscoveryStopped(), _onServiceFound(), _onServiceLost(), _onStartDiscoveryFailed(), _onStopDiscoveryFailed(), and s_className.
Referenced by JNI_OnLoad().
The documentation for this class was generated from the following files:
JNIXBMCNsdManagerDiscoveryListener.h
JNIXBMCNsdManagerDiscoveryListener.cpp