Kodi Documentation: CDVDFactoryInputStream Class Reference
CDVDFactoryInputStream Class Reference
#include <DVDFactoryInputStream.h>
Static Public Member Functions
static std::shared_ptr< CDVDInputStream > CreateInputStream (IVideoPlayer *pPlayer, const CFileItem &fileitem, bool scanforextaudio=false)
static std::shared_ptr< CDVDInputStream > CreateInputStream (IVideoPlayer *pPlayer, const CFileItem &fileitem, const std::vector< std::string > &filenames)
Member Function Documentation
CreateInputStream() [1/2]
std::shared_ptr< CDVDInputStream > CDVDFactoryInputStream::CreateInputStream (IVideoPlayer * pPlayer, const CFileItem & fileitem, bool scanforextaudio = false) static
References URIUtils::AddFileToFolder(), CVariant::asString(), XFILE::CCurlFile::Close(), CFileItem::ContentLookup(), CreateInputStream(), CFileUtils::Exists(), CURL::Get(), ADDON::CAddonMgr::GetAddonInfos(), CServiceBroker::GetAddonMgr(), CFileItem::GetDynPath(), CFileItem::GetDynURL(), CServiceBroker::GetMediaManager(), CFileItem::GetMimeType(), CURL::GetPassWord(), CFileItem::GetPath(), CGUIListItem::GetProperty(), CURL::GetProtocolOptions(), XFILE::CCurlFile::GetURL(), CURL::GetUserName(), CFileItem::IsDiscImage(), KODI::NETWORK::IsInternetStream(), URIUtils::IsProtocol(), URIUtils::IsPVRChannel(), URIUtils::IsPVRRecording(), CFileItem::IsType(), XFILE::CRedirectException::m_pNewFileImp, XFILE::CCurlFile::Open(), XFILE::READ_BITRATE, XFILE::READ_CHUNKED, XFILE::READ_TRUNCATED, CUtil::ScanForExternalAudio(), CFileItem::SetDynPath(), CURL::SetFileName(), CURL::SetHostName(), CURL::SetPassword(), CURL::SetProtocolOptions(), CURL::SetUserName(), STREAM_PROPERTY_INPUTSTREAM, STREAM_PROPERTY_INPUTSTREAM_INSTANCE_ID, STREAM_PROPERTY_VALUE_INPUTSTREAMFFMPEG, CInputStreamAddon::Supports(), and CMediaManager::TranslateDevicePath().
Referenced by CVideoPlayer::AddSubtitleFile(), CreateInputStream(), CDVDFileInfo::ExtractThumbToTexture(), CDVDFileInfo::GetFileDuration(), CDVDFileInfo::GetFileStreamDetails(), VideoPlayerCodec::Init(), CInputStreamMultiSource::Open(), CDVDDemuxVobsub::Open(), CDVDSubtitleStream::Open(), and CVideoPlayer::OpenInputStream().
CreateInputStream() [2/2]
std::shared_ptr< CDVDInputStream > CDVDFactoryInputStream::CreateInputStream (IVideoPlayer * pPlayer, const CFileItem & fileitem, const std::vector< std::string > & filenames) static
The documentation for this class was generated from the following files:
DVDFactoryInputStream.h
DVDFactoryInputStream.cpp