Kodi Documentation: anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncDeleteRecording Class Reference
anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncDeleteRecording Class Reference
Public Member Functions
AsyncDeleteRecording (bool bWatchedOnly=false)
Public Member Functions inherited from anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncRecordingAction
bool Execute (const CFileItem &item)
Private Member Functions
bool DoRun (const std::shared_ptr< CFileItem > &item) override
Private Attributes
bool m_bWatchedOnly = false
Additional Inherited Members
Protected Member Functions inherited from anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncRecordingAction
AsyncRecordingAction ()=default
Constructor & Destructor Documentation
AsyncDeleteRecording()
anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncDeleteRecording::AsyncDeleteRecording (bool bWatchedOnly = false) inline explicit
Member Function Documentation
DoRun()
bool anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncDeleteRecording::DoRun (const std::shared_ptr< CFileItem > & item) inline override private virtual
Implements anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncRecordingAction.
References CFileItemList::Add(), CFileItemList::cbegin(), CFileItemList::cend(), XFILE::DIR_FLAG_NO_FILE_INFO, CServiceBroker::GetPVRManager(), CUtil::GetRecursiveListing(), PVR::CPVRManager::Recordings(), and success.
Member Data Documentation
m_bWatchedOnly
bool anonymous_namespace{PVRGUIActionsRecordings.cpp}::AsyncDeleteRecording::m_bWatchedOnly = false private
The documentation for this class was generated from the following file:
PVRGUIActionsRecordings.cpp