Kodi Documentation: FFmpegImage.cpp File Reference
FFmpegImage.cpp File Reference
#include "FFmpegImage.h"
#include "cores/FFmpeg.h"
#include "guilib/Texture.h"
#include "settings/AdvancedSettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "utils/log.h"
#include <algorithm>
#include <libavformat/avformat.h>
#include <libavutil/imgutils.h>
#include <libavcodec/avcodec.h>
#include <libavutil/avutil.h>
#include <libswscale/swscale.h>
#include <libavutil/pixdesc.h>
Classes
struct ThumbDataManagement
Functions
static size_t Clamp (int64_t newPosition, size_t bufferSize)
static int mem_file_read (void *h, uint8_t *buf, int size)
static int64_t mem_file_seek (void *h, int64_t pos, int whence)
Function Documentation
Clamp()
static size_t Clamp (int64_t newPosition, size_t bufferSize) inline static
References int64_t().
Referenced by mem_file_seek().
mem_file_read()
static int mem_file_read (void * h, uint8_t * buf, int size) static
References MemBuffer::data, int64_t(), MemBuffer::pos, and MemBuffer::size.
Referenced by CFFmpegImage::Initialize().
mem_file_seek()
static int64_t mem_file_seek (void * h, int64_t pos, int whence) static
References Clamp(), int64_t(), LOGERROR, MemBuffer::pos, and MemBuffer::size.
Referenced by CFFmpegImage::Initialize().