Kodi Documentation: KODI::GAME::CControllerHub Class Reference
KODI::GAME::CControllerHub Class Reference
Games
A branch in the controller tree.
#include <ControllerHub.h>
Public Member Functions
CControllerHub ()=default
CControllerHub (const CControllerHub &other)
CControllerHub (CControllerHub &&other)=default
CControllerHub & operator= (const CControllerHub &rhs)
CControllerHub & operator= (CControllerHub &&rhs) noexcept
~CControllerHub ()
void Clear ()
bool HasPorts () const
PortVec & GetPorts ()
const PortVec & GetPorts () const
void SetPorts (PortVec ports)
bool IsControllerAccepted (const std::string &controllerId) const
bool IsControllerAccepted (const std::string &portAddress, const std::string &controllerId) const
ControllerVector GetControllers () const
void GetControllers (ControllerVector &controllers) const
const CPortNode & GetPort (const std::string &address) const
void GetInputPorts (std::vector< std::string > &inputPorts) const
Get a list of ports that accept player input.
Static Private Member Functions
static const CPortNode & GetPortInternal (const PortVec &ports, const std::string &address)
Private Attributes
PortVec m_ports
Detailed Description
A branch in the controller tree.
Constructor & Destructor Documentation
CControllerHub() [1/3]
KODI::GAME::CControllerHub::CControllerHub () default
CControllerHub() [2/3]
KODI::GAME::CControllerHub::CControllerHub (const CControllerHub & other) inline
CControllerHub() [3/3]
KODI::GAME::CControllerHub::CControllerHub (CControllerHub && other) default
~CControllerHub()
CControllerHub::~CControllerHub () default
Member Function Documentation
Clear()
void CControllerHub::Clear ()
References m_ports.
Referenced by KODI::GAME::CGameClientTopology::Clear(), KODI::GAME::CPortManager::Clear(), and KODI::GAME::CPortManager::Deinitialize().
GetControllers() [1/2]
ControllerVector CControllerHub::GetControllers () const
References GetControllers().
Referenced by GetControllers().
GetControllers() [2/2]
void CControllerHub::GetControllers (ControllerVector & controllers) const
References m_ports, and node.
GetInputPorts()
void CControllerHub::GetInputPorts (std::vector< std::string > & inputPorts) const
Get a list of ports that accept player input.
Parameters
[out] inputPorts The list of input ports
References KODI::GAME::CPortNode::GetInputPorts(), and m_ports.
Referenced by KODI::GAME::CAgentInput::GetGameInputPorts().
GetPort()
const CPortNode & CControllerHub::GetPort (const std::string & address) const
References GetPortInternal(), and m_ports.
Referenced by KODI::GAME::CGameClientInput::ConnectController().
GetPortInternal()
const CPortNode & CControllerHub::GetPortInternal (const PortVec & ports, const std::string & address) static private
References KODI::GAME::CPortNode::GetAddress(), and GetPortInternal().
Referenced by GetPort(), and GetPortInternal().
GetPorts() [1/2]
PortVec & KODI::GAME::CControllerHub::GetPorts () inline
References m_ports.
Referenced by KODI::GAME::CGameClientInput::ActivateControllers(), KODI::GAME::CControllerGrid::AddController(), KODI::GAME::CGUIPortList::AddItems(), KODI::GAME::CGameClientInput::CloseJoysticks(), KODI::GAME::CPortManager::ConnectController(), KODI::GAME::CPortManager::ConnectController(), KODI::GAME::CGameClientInput::ConnectController(), KODI::GAME::CPortManager::DeserializeController(), KODI::GAME::CPortManager::HasState(), KODI::GAME::CPortManager::LoadXML(), KODI::GAME::CAgentInput::ProcessKeyboard(), KODI::GAME::CAgentInput::ProcessMouse(), KODI::GAME::CGUIActivePortList::Refresh(), KODI::GAME::CGUIPortList::Refresh(), KODI::GAME::CGameClientInput::ResetPorts(), KODI::GAME::CPortManager::SaveXMLAsync(), KODI::GAME::CPortManager::SerializeController(), KODI::GAME::CControllerGrid::SetControllerTree(), KODI::GAME::CGameClientInput::SupportsKeyboard(), KODI::GAME::CGameClientInput::SupportsMouse(), and TEST().
GetPorts() [2/2]
const PortVec & KODI::GAME::CControllerHub::GetPorts () const inline
References m_ports.
HasPorts()
bool KODI::GAME::CControllerHub::HasPorts () const inline
References m_ports.
IsControllerAccepted() [1/2]
bool CControllerHub::IsControllerAccepted (const std::string & controllerId) const
References m_ports.
Referenced by KODI::GAME::CGUIControllerList::RefreshControllers().
IsControllerAccepted() [2/2]
bool CControllerHub::IsControllerAccepted (const std::string & portAddress, const std::string & controllerId) const
References m_ports.
operator=() [1/2]
CControllerHub & CControllerHub::operator= (CControllerHub && rhs) noexcept
operator=() [2/2]
CControllerHub & CControllerHub::operator= (const CControllerHub & rhs)
References m_ports.
SetPorts()
void CControllerHub::SetPorts (PortVec ports)
References m_ports.
Referenced by KODI::GAME::CGameClientTopology::GetControllerNode(), and KODI::GAME::CGameClientTopology::GetControllerTree().
Member Data Documentation
m_ports
PortVec KODI::GAME::CControllerHub::m_ports private
Referenced by Clear(), GetControllers(), GetInputPorts(), GetPort(), GetPorts(), GetPorts(), HasPorts(), IsControllerAccepted(), IsControllerAccepted(), operator=(), and SetPorts().
The documentation for this class was generated from the following files:
ControllerHub.h
ControllerHub.cpp