Kodi Documentation: XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeTop100 Class Reference
XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeTop100 Class Reference
#include <DirectoryNodeTop100.h>
Public Member Functions
CDirectoryNodeTop100 (const std::string &strName, CDirectoryNode *pParent)
Public Member Functions inherited from XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode
virtual ~CDirectoryNode ()
NODE_TYPE GetType () const
bool GetChilds (CFileItemList &items)
CDirectoryNode * GetParent () const
virtual bool CanCache () const
std::string BuildPath () const
Protected Member Functions
NODE_TYPE GetChildType () const override
bool GetContent (CFileItemList &items) const override
std::string GetLocalizedName () const override
Protected Member Functions inherited from XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode
CDirectoryNode (NODE_TYPE Type, const std::string &strName, CDirectoryNode *pParent)
void AddOptions (const std::string &options)
void CollectQueryParams (CQueryParams &params) const
const std::string & GetName () const
int GetID () const
void RemoveParent ()
Additional Inherited Members
Static Public Member Functions inherited from XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode
static CDirectoryNode * ParseURL (const std::string &strPath)
static void GetDatabaseInfo (const std::string &strPath, CQueryParams &params)
static bool GetNodeInfo (const std::string &strPath, NODE_TYPE &type, NODE_TYPE &childtype, CQueryParams &params)
Static Protected Member Functions inherited from XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode
static CDirectoryNode * CreateNode (NODE_TYPE Type, const std::string &strName, CDirectoryNode *pParent)
Constructor & Destructor Documentation
CDirectoryNodeTop100()
CDirectoryNodeTop100::CDirectoryNodeTop100 (const std::string & strName, CDirectoryNode * pParent)
Member Function Documentation
GetChildType()
NODE_TYPE CDirectoryNodeTop100::GetChildType () const override protected virtual
Reimplemented from XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode.
References XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::GetName(), node, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_NONE, and Top100Children.
GetContent()
bool CDirectoryNodeTop100::GetContent (CFileItemList & items) const override protected virtual
Reimplemented from XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode.
References CFileItemList::Add(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::BuildPath(), g_localizeStrings, CLocalizeStrings::Get(), node, and Top100Children.
GetLocalizedName()
std::string CDirectoryNodeTop100::GetLocalizedName () const override protected virtual
Reimplemented from XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode.
References g_localizeStrings, CLocalizeStrings::Get(), XFILE::MUSICDATABASEDIRECTORY::CDirectoryNode::GetName(), node, and Top100Children.
The documentation for this class was generated from the following files:
DirectoryNodeTop100.h
DirectoryNodeTop100.cpp