Kodi Documentation: KODI::PLAYLIST::CPlayList Class Reference
KODI::PLAYLIST::CPlayList Class Reference
#include <PlayList.h>
Public Member Functions
CPlayList (Id id=Id::TYPE_NONE)
virtual ~CPlayList (void)=default
virtual bool Load (const std::string &strFileName)
virtual bool LoadData (std::istream &stream)
virtual bool LoadData (const std::string &strData)
virtual void Save (const std::string &strFileName) const
void Add (const CPlayList &playlist)
void Add (const std::shared_ptr< CFileItem > &pItem)
void Add (const CFileItemList &items)
void Insert (const CPlayList &playlist, int iPosition=-1)
void Insert (const CFileItemList &items, int iPosition=-1)
void Insert (const std::shared_ptr< CFileItem > &item, int iPosition=-1)
int FindOrder (int iOrder) const
const std::string & GetName () const
void Remove (const std::string &strFileName)
void Remove (int position)
bool Swap (int position1, int position2)
bool Expand (int position)
void Clear ()
int size () const
int RemoveDVDItems ()
const std::shared_ptr< CFileItem > operator[] (int iItem) const
std::shared_ptr< CFileItem > operator[] (int iItem)
void Shuffle (int iPosition=0)
void UnShuffle ()
bool IsShuffled () const
void SetPlayed (bool bPlayed)
bool WasPlayed () const
void SetUnPlayable (int iItem)
int GetPlayable () const
void UpdateItem (const CFileItem *item)
const std::string & ResolveURL (const std::shared_ptr< CFileItem > &item) const
Protected Types
typedef std::vector< std::shared_ptr< CFileItem > >::iterator ivecItems
Protected Attributes
Id m_id
std::string m_strPlayListName
std::string m_strBasePath
int m_iPlayableItems
bool m_bShuffled
bool m_bWasPlayed
std::vector< std::shared_ptr< CFileItem > > m_vecItems
Private Member Functions
void Add (const std::shared_ptr< CFileItem > &item, int iPosition, int iOrderOffset)
void DecrementOrder (int iOrder)
void IncrementOrder (int iPosition, int iOrder)
void AnnounceRemove (int pos)
void AnnounceClear ()
void AnnounceAdd (const std::shared_ptr< CFileItem > &item, int pos)
Member Typedef Documentation
ivecItems
typedef std::vector<std::shared_ptr<CFileItem>>::iterator KODI::PLAYLIST::CPlayList::ivecItems protected
Constructor & Destructor Documentation
CPlayList()
KODI::PLAYLIST::CPlayList::CPlayList (Id id = Id::TYPE_NONE) explicit
References m_bShuffled, m_bWasPlayed, and m_iPlayableItems.
~CPlayList()
virtual KODI::PLAYLIST::CPlayList::~CPlayList (void) virtual default
Member Function Documentation
Add() [1/4]
void KODI::PLAYLIST::CPlayList::Add (const CFileItemList & items)
References Add(), and CFileItemList::Size().
Add() [2/4]
void KODI::PLAYLIST::CPlayList::Add (const CPlayList & playlist)
References Add(), and playlist.
Referenced by Add(), Add(), Add(), KODI::PLAYLIST::CPlayListPlayer::Add(), KODI::PLAYLIST::CPlayListPlayer::Add(), KODI::PLAYLIST::CPlayListPlayer::Add(), Insert(), Insert(), Insert(), KODI::PLAYLIST::CPlayListM3U::Load(), KODI::PLAYLIST::CPlayListURL::Load(), KODI::PLAYLIST::CPlayListXML::Load(), KODI::PLAYLIST::CPlayListXSPF::Load(), KODI::PLAYLIST::CPlayListASX::LoadAsxIniInfo(), KODI::PLAYLIST::CPlayListASX::LoadData(), KODI::PLAYLIST::CPlayListB4S::LoadData(), KODI::PLAYLIST::CPlayListRAM::LoadData(), KODI::PLAYLIST::CPlayListWPL::LoadData(), CPartyModeManager::MovePlaying(), CGUIWindowVideoBase::OnPlayMedia(), and CGUIWindowMusicBase::OnPlayMedia().
Add() [3/4]
void KODI::PLAYLIST::CPlayList::Add (const std::shared_ptr< CFileItem > & item, int iPosition, int iOrderOffset) private
References AnnounceAdd(), IncrementOrder(), m_iPlayableItems, m_vecItems, and size().
Add() [4/4]
void KODI::PLAYLIST::CPlayList::Add (const std::shared_ptr< CFileItem > & pItem)
References Add().
AnnounceAdd()
void KODI::PLAYLIST::CPlayList::AnnounceAdd (const std::shared_ptr< CFileItem > & item, int pos) private
References data(), CServiceBroker::GetAnnouncementManager(), m_id, ANNOUNCEMENT::Playlist, and KODI::PLAYLIST::TYPE_NONE.
Referenced by Add().
AnnounceClear()
void KODI::PLAYLIST::CPlayList::AnnounceClear () private
References data(), CServiceBroker::GetAnnouncementManager(), m_id, ANNOUNCEMENT::Playlist, and KODI::PLAYLIST::TYPE_NONE.
Referenced by Clear().
AnnounceRemove()
void KODI::PLAYLIST::CPlayList::AnnounceRemove (int pos) private
References data(), CServiceBroker::GetAnnouncementManager(), m_id, ANNOUNCEMENT::Playlist, and KODI::PLAYLIST::TYPE_NONE.
Referenced by Remove(), and Remove().
Clear()
void KODI::PLAYLIST::CPlayList::Clear ()
References AnnounceClear(), m_bWasPlayed, m_iPlayableItems, m_strPlayListName, and m_vecItems.
Referenced by XBMCAddon::xbmc::PlayList::clear(), KODI::PLAYLIST::CPlayListPlayer::Clear(), KODI::PLAYLIST::CPlayListPlayer::GetPlaylist(), Load(), KODI::PLAYLIST::CPlayListM3U::Load(), KODI::PLAYLIST::CPlayListPLS::Load(), KODI::PLAYLIST::CPlayListURL::Load(), KODI::PLAYLIST::CPlayListXML::Load(), KODI::PLAYLIST::CPlayListXSPF::Load(), and KODI::PLAYLIST::CPlayListPlayer::Play().
DecrementOrder()
void KODI::PLAYLIST::CPlayList::DecrementOrder (int iOrder) private
References m_vecItems, and size().
Referenced by Remove(), and Remove().
Expand()
bool KODI::PLAYLIST::CPlayList::Expand (int position)
References KODI::PLAYLIST::CPlayListFactory::Create(), Insert(), m_vecItems, playlist, and Remove().
FindOrder()
int KODI::PLAYLIST::CPlayList::FindOrder (int iOrder) const
References m_vecItems, and size().
Referenced by anonymous_namespace{MusicUtils.cpp}::AddItemToPlayListAndPlay(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::AddItemToPlayListAndPlay(), and CGUIMediaWindow::OnPlayAndQueueMedia().
GetName()
const std::string & KODI::PLAYLIST::CPlayList::GetName () const
References m_strPlayListName.
GetPlayable()
int KODI::PLAYLIST::CPlayList::GetPlayable () const inline
References m_iPlayableItems.
IncrementOrder()
void KODI::PLAYLIST::CPlayList::IncrementOrder (int iPosition, int iOrder) private
References m_vecItems.
Referenced by Add().
Insert() [1/3]
void KODI::PLAYLIST::CPlayList::Insert (const CFileItemList & items, int iPosition = -1)
References Add(), CFileItemList::Size(), and size().
Insert() [2/3]
void KODI::PLAYLIST::CPlayList::Insert (const CPlayList & playlist, int iPosition = -1)
References Add(), playlist, and size().
Referenced by XBMCAddon::xbmc::PlayList::add(), CPartyModeManager::AddUserSongs(), CPartyModeManager::AddUserSongs(), Expand(), KODI::PLAYLIST::CPlayListPlayer::Insert(), KODI::PLAYLIST::CPlayListPlayer::Insert(), and KODI::PLAYLIST::CPlayListPlayer::Insert().
Insert() [3/3]
void KODI::PLAYLIST::CPlayList::Insert (const std::shared_ptr< CFileItem > & item, int iPosition = -1)
References Add(), and size().
IsShuffled()
bool KODI::PLAYLIST::CPlayList::IsShuffled () const inline
References m_bShuffled.
Referenced by KODI::PLAYLIST::CPlayListPlayer::Add(), KODI::PLAYLIST::CPlayListPlayer::Add(), KODI::PLAYLIST::CPlayListPlayer::Add(), KODI::PLAYLIST::CPlayListPlayer::Insert(), KODI::PLAYLIST::CPlayListPlayer::Insert(), KODI::PLAYLIST::CPlayListPlayer::Insert(), KODI::PLAYLIST::CPlayListPlayer::IsShuffled(), and Swap().
Load()
bool KODI::PLAYLIST::CPlayList::Load (const std::string & strFileName) virtual
Reimplemented in KODI::PLAYLIST::CPlayListM3U, KODI::PLAYLIST::CPlayListPLS, KODI::PLAYLIST::CPlayListURL, KODI::PLAYLIST::CPlayListXML, and KODI::PLAYLIST::CPlayListXSPF.
References Clear(), URIUtils::GetDirectory(), LoadData(), CLog::Log(), LOGWARNING, and m_strBasePath.
Referenced by XBMCAddon::xbmc::PlayList::load().
LoadData() [1/2]
bool KODI::PLAYLIST::CPlayList::LoadData (const std::string & strData) virtual
LoadData() [2/2]
bool KODI::PLAYLIST::CPlayList::LoadData (std::istream & stream) virtual
Reimplemented in KODI::PLAYLIST::CPlayListASX, KODI::PLAYLIST::CPlayListB4S, KODI::PLAYLIST::CPlayListRAM, and KODI::PLAYLIST::CPlayListWPL.
References LoadData().
Referenced by Load(), and LoadData().
operator[]() [1/2]
std::shared_ptr< CFileItem > KODI::PLAYLIST::CPlayList::operator[] (int iItem)
References CLog::Log(), LOGERROR, m_vecItems, and size().
operator[]() [2/2]
const std::shared_ptr< CFileItem > KODI::PLAYLIST::CPlayList::operator[] (int iItem) const
References CLog::Log(), LOGERROR, m_vecItems, and size().
Remove() [1/2]
void KODI::PLAYLIST::CPlayList::Remove (const std::string & strFileName)
References AnnounceRemove(), DecrementOrder(), and m_vecItems.
Referenced by Expand(), CPartyModeManager::ReapSongs(), XBMCAddon::xbmc::PlayList::remove(), KODI::PLAYLIST::CPlayListPlayer::Remove(), and RemoveDVDItems().
Remove() [2/2]
void KODI::PLAYLIST::CPlayList::Remove (int position)
References AnnounceRemove(), DecrementOrder(), and m_vecItems.
RemoveDVDItems()
int KODI::PLAYLIST::CPlayList::RemoveDVDItems ()
References KODI::MUSIC::IsCDDA(), m_vecItems, and Remove().
Referenced by KODI::PLAYLIST::CPlayListPlayer::RemoveDVDItems().
ResolveURL()
const std::string & KODI::PLAYLIST::CPlayList::ResolveURL (const std::shared_ptr< CFileItem > & item) const
References KODI::MUSIC::IsMusicDb().
Referenced by KODI::PLAYLIST::CPlayListM3U::Save().
Save()
virtual void KODI::PLAYLIST::CPlayList::Save (const std::string & strFileName) const inline virtual
Reimplemented in KODI::PLAYLIST::CPlayListB4S, KODI::PLAYLIST::CPlayListM3U, KODI::PLAYLIST::CPlayListPLS, KODI::PLAYLIST::CPlayListWPL, and KODI::PLAYLIST::CPlayListXML.
SetPlayed()
void KODI::PLAYLIST::CPlayList::SetPlayed (bool bPlayed) inline
References m_bWasPlayed.
SetUnPlayable()
void KODI::PLAYLIST::CPlayList::SetUnPlayable (int iItem)
References CLog::Log(), LOGWARNING, m_iPlayableItems, m_vecItems, and size().
Shuffle()
void KODI::PLAYLIST::CPlayList::Shuffle (int iPosition = 0)
References CLog::Log(), LOGDEBUG, m_bShuffled, m_vecItems, KODI::UTILS::RandomShuffle(), and size().
Referenced by KODI::PLAYLIST::CPlayListPlayer::ReShuffle(), and XBMCAddon::xbmc::PlayList::shuffle().
size()
int KODI::PLAYLIST::CPlayList::size () const
References m_vecItems.
Referenced by Add(), KODI::PLAYLIST::CPlayListPlayer::Add(), KODI::PLAYLIST::CPlayListPlayer::Add(), KODI::PLAYLIST::CPlayListPlayer::Add(), CPartyModeManager::AddUserSongs(), AnnounceBridge(), DecrementOrder(), FindOrder(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::GetPlaylistLabel(), Insert(), Insert(), Insert(), KODI::PLAYLIST::CPlayListPlayer::Insert(), KODI::PLAYLIST::CPlayListPlayer::Insert(), KODI::PLAYLIST::CPlayListPlayer::Insert(), XBMCAddon::xbmc::PlayList::load(), KODI::PLAYLIST::CPlayListPLS::Load(), CPartyModeManager::MovePlaying(), CApplication::OnMessage(), operator[](), operator[](), SetUnPlayable(), Shuffle(), XBMCAddon::xbmc::PlayList::size(), and Swap().
Swap()
bool KODI::PLAYLIST::CPlayList::Swap (int position1, int position2)
References IsShuffled(), m_vecItems, and size().
Referenced by anonymous_namespace{MusicUtils.cpp}::AddItemToPlayListAndPlay(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::AddItemToPlayListAndPlay(), CGUIMediaWindow::OnPlayAndQueueMedia(), and KODI::PLAYLIST::CPlayListPlayer::Swap().
UnShuffle()
void KODI::PLAYLIST::CPlayList::UnShuffle ()
References m_bShuffled, m_vecItems, and KODI::PLAYLIST::SSortPlayListItem::PlaylistSort().
Referenced by XBMCAddon::xbmc::PlayList::unshuffle().
UpdateItem()
void KODI::PLAYLIST::CPlayList::UpdateItem (const CFileItem * item)
References m_vecItems, and CFileItem::SetPath().
WasPlayed()
bool KODI::PLAYLIST::CPlayList::WasPlayed () const inline
References m_bWasPlayed.
Member Data Documentation
m_bShuffled
bool KODI::PLAYLIST::CPlayList::m_bShuffled protected
Referenced by CPlayList(), IsShuffled(), Shuffle(), and UnShuffle().
m_bWasPlayed
bool KODI::PLAYLIST::CPlayList::m_bWasPlayed protected
Referenced by Clear(), CPlayList(), SetPlayed(), and WasPlayed().
m_id
Id KODI::PLAYLIST::CPlayList::m_id protected
Referenced by AnnounceAdd(), AnnounceClear(), and AnnounceRemove().
m_iPlayableItems
int KODI::PLAYLIST::CPlayList::m_iPlayableItems protected
Referenced by Add(), Clear(), CPlayList(), GetPlayable(), and SetUnPlayable().
m_strBasePath
std::string KODI::PLAYLIST::CPlayList::m_strBasePath protected
Referenced by Load(), KODI::PLAYLIST::CPlayListM3U::Load(), KODI::PLAYLIST::CPlayListPLS::Load(), KODI::PLAYLIST::CPlayListURL::Load(), KODI::PLAYLIST::CPlayListXML::Load(), KODI::PLAYLIST::CPlayListXSPF::Load(), KODI::PLAYLIST::CPlayListB4S::LoadData(), and KODI::PLAYLIST::CPlayListWPL::LoadData().
m_strPlayListName
std::string KODI::PLAYLIST::CPlayList::m_strPlayListName protected
Referenced by Clear(), GetName(), KODI::PLAYLIST::CPlayListM3U::Load(), KODI::PLAYLIST::CPlayListPLS::Load(), KODI::PLAYLIST::CPlayListURL::Load(), KODI::PLAYLIST::CPlayListXML::Load(), KODI::PLAYLIST::CPlayListXSPF::Load(), KODI::PLAYLIST::CPlayListB4S::LoadData(), KODI::PLAYLIST::CPlayListWPL::LoadData(), KODI::PLAYLIST::CPlayListB4S::Save(), KODI::PLAYLIST::CPlayListPLS::Save(), and KODI::PLAYLIST::CPlayListWPL::Save().
m_vecItems
std::vector<std::shared_ptr<CFileItem> > KODI::PLAYLIST::CPlayList::m_vecItems protected
Referenced by Add(), Clear(), DecrementOrder(), Expand(), FindOrder(), IncrementOrder(), KODI::PLAYLIST::CPlayListPLS::Load(), operator[](), operator[](), Remove(), Remove(), RemoveDVDItems(), KODI::PLAYLIST::CPlayListPLS::Resize(), KODI::PLAYLIST::CPlayListB4S::Save(), KODI::PLAYLIST::CPlayListM3U::Save(), KODI::PLAYLIST::CPlayListPLS::Save(), KODI::PLAYLIST::CPlayListWPL::Save(), KODI::PLAYLIST::CPlayListXML::Save(), SetUnPlayable(), Shuffle(), size(), Swap(), UnShuffle(), and UpdateItem().
The documentation for this class was generated from the following files:
playlists/PlayList.h
playlists/PlayList.cpp