Kodi Documentation: KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler Class Reference
KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler Class Reference
Public Member Functions
CVideoItemArtworkHandler (const std::shared_ptr< CFileItem > &item, const std::string &artType)
std::string GetCurrentArt () const override
std::string GetEmbeddedArt () const override
std::vector< std::string > GetRemoteArt () const override
std::string GetLocalArt () const override
std::string GetDefaultIcon () const override
void AddItemPathToFileBrowserSources (std::vector< CMediaSource > &sources) override
void PersistArt (const std::string &art) override
Public Member Functions inherited from KODI::VIDEO::IVideoItemArtworkHandler
virtual ~IVideoItemArtworkHandler ()=default
virtual bool SupportsFlippedArt () const
virtual std::string UpdateEmbeddedArt (const std::string &art)
virtual std::string UpdateRemoteArt (const std::vector< std::string > &art, int index)
Protected Member Functions
void AddItemPathStringToFileBrowserSources (std::vector< CMediaSource > &sources, const std::string &itemDir, const std::string &label)
Protected Attributes
const std::shared_ptr< CFileItem > m_item
const std::string m_artType
Constructor & Destructor Documentation
CVideoItemArtworkHandler()
KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::CVideoItemArtworkHandler (const std::shared_ptr< CFileItem > & item, const std::string & artType) inline explicit
Member Function Documentation
AddItemPathStringToFileBrowserSources()
void KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::AddItemPathStringToFileBrowserSources (std::vector< CMediaSource > & sources, const std::string & itemDir, const std::string & label) protected
References XFILE::CDirectory::Exists(), label, CMediaSource::strName, and CMediaSource::strPath.
AddItemPathToFileBrowserSources()
void KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::AddItemPathToFileBrowserSources (std::vector< CMediaSource > & sources) override virtual
Reimplemented from KODI::VIDEO::IVideoItemArtworkHandler.
Reimplemented in KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkMovieSetHandler.
References g_localizeStrings, CLocalizeStrings::Get(), URIUtils::GetParentPath(), and KODI::VIDEO::IsVideo().
GetCurrentArt()
std::string KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::GetCurrentArt () const override virtual
Implements KODI::VIDEO::IVideoItemArtworkHandler.
References LOGERROR.
GetDefaultIcon()
std::string KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::GetDefaultIcon () const override virtual
Implements KODI::VIDEO::IVideoItemArtworkHandler.
Reimplemented in KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkMovieSetHandler.
GetEmbeddedArt()
std::string KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::GetEmbeddedArt () const override virtual
Reimplemented from KODI::VIDEO::IVideoItemArtworkHandler.
References KODI::VIDEO::TAGS::CVideoTagExtractionHelper::ExtractEmbeddedArtFor(), and KODI::VIDEO::TAGS::CVideoTagExtractionHelper::IsExtractionSupportedFor().
GetLocalArt()
std::string KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::GetLocalArt () const override virtual
Reimplemented from KODI::VIDEO::IVideoItemArtworkHandler.
Reimplemented in KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkMovieSetHandler.
References CVideoThumbLoader::GetLocalArt().
GetRemoteArt()
std::vector< std::string > KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::GetRemoteArt () const override virtual
Reimplemented from KODI::VIDEO::IVideoItemArtworkHandler.
Reimplemented in KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkSeasonHandler, and KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkMovieSetHandler.
PersistArt()
void KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::PersistArt (const std::string & art) override virtual
Implements KODI::VIDEO::IVideoItemArtworkHandler.
References LOGERROR, CVideoDatabase::Open(), CVideoDatabase::SetArtForItem(), and CVideoDatabase::UpdateArtForItem().
Member Data Documentation
m_artType
const std::string KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::m_artType protected
m_item
const std::shared_ptr<CFileItem> KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::m_item protected
The documentation for this class was generated from the following file:
VideoItemArtworkHandler.cpp