Kodi Documentation: CAnimation Class Reference
CAnimation Class Reference
#include <VisibleEffect.h>
Public Member Functions
CAnimation ()
CAnimation (const CAnimation &src)
virtual ~CAnimation ()
CAnimation & operator= (const CAnimation &src)
void Create (const TiXmlElement *node, const CRect &rect, int context)
void Animate (unsigned int time, bool startAnim)
void ResetAnimation ()
void ApplyAnimation ()
void RenderAnimation (TransformMatrix &matrix)
void RenderAnimation (TransformMatrix &matrix, const CPoint &center)
void QueueAnimation (ANIMATION_PROCESS process)
bool IsReversible () const
ANIMATION_TYPE GetType () const
ANIMATION_STATE GetState () const
ANIMATION_PROCESS GetProcess () const
ANIMATION_PROCESS GetQueuedProcess () const
bool CheckCondition ()
void UpdateCondition (const CGUIListItem *item=NULL)
void SetInitialCondition ()
Static Public Member Functions
static CAnimation CreateFader (float start, float end, unsigned int delay, unsigned int length, ANIMATION_TYPE type=ANIM_TYPE_NONE)
Private Types
enum ANIM_REPEAT { ANIM_REPEAT_NONE = 0 , ANIM_REPEAT_PULSE , ANIM_REPEAT_LOOP }
Private Member Functions
void Calculate (const CPoint &point)
void AddEffect (const std::string &type, const TiXmlElement *node, const CRect &rect)
Private Attributes
ANIMATION_TYPE m_type
bool m_reversible
INFO::InfoPtr m_condition
ANIM_REPEAT m_repeatAnim
bool m_lastCondition
ANIMATION_PROCESS m_queuedProcess
ANIMATION_PROCESS m_currentProcess
ANIMATION_STATE m_currentState
unsigned int m_start
unsigned int m_length
unsigned int m_delay
unsigned int m_amount
std::vector< CAnimEffect * > m_effects
Member Enumeration Documentation
ANIM_REPEAT
enum CAnimation::ANIM_REPEAT private
Enumerator
ANIM_REPEAT_NONE
ANIM_REPEAT_PULSE
ANIM_REPEAT_LOOP
Constructor & Destructor Documentation
CAnimation() [1/2]
CAnimation::CAnimation ()
References ANIM_PROCESS_NONE, ANIM_REPEAT_NONE, ANIM_STATE_NONE, ANIM_TYPE_NONE, m_amount, m_currentProcess, m_currentState, m_delay, m_lastCondition, m_length, m_queuedProcess, m_repeatAnim, m_reversible, m_start, and m_type.
CAnimation() [2/2]
CAnimation::CAnimation (const CAnimation & src)
~CAnimation()
CAnimation::~CAnimation () virtual
References m_effects.
Member Function Documentation
AddEffect()
void CAnimation::AddEffect (const std::string & type, const TiXmlElement * node, const CRect & rect) private
References CAnimEffect::EFFECT_TYPE_FADE, CAnimEffect::EFFECT_TYPE_FADE_DIFFUSE, CAnimEffect::EFFECT_TYPE_ROTATE_X, CAnimEffect::EFFECT_TYPE_ROTATE_Y, CAnimEffect::EFFECT_TYPE_ROTATE_Z, m_effects, m_type, and node.
Referenced by Create().
Animate()
void CAnimation::Animate (unsigned int time, bool startAnim)
References ANIM_PROCESS_NONE, ANIM_PROCESS_NORMAL, ANIM_PROCESS_REVERSE, ANIM_REPEAT_LOOP, ANIM_REPEAT_PULSE, ANIM_STATE_APPLIED, ANIM_STATE_DELAYED, ANIM_STATE_IN_PROCESS, m_amount, m_currentProcess, m_currentState, m_delay, m_lastCondition, m_length, m_queuedProcess, m_repeatAnim, and m_start.
Referenced by CGUIControl::Animate(), CGUIFadeLabelControl::Process(), and CGUITextBox::Process().
ApplyAnimation()
void CAnimation::ApplyAnimation ()
References ANIM_PROCESS_NONE, ANIM_PROCESS_NORMAL, ANIM_PROCESS_REVERSE, ANIM_REPEAT_LOOP, ANIM_REPEAT_PULSE, ANIM_STATE_APPLIED, ANIM_STATE_IN_PROCESS, Calculate(), m_amount, m_currentProcess, m_currentState, m_length, m_queuedProcess, and m_repeatAnim.
Referenced by CGUIFadeLabelControl::CGUIFadeLabelControl(), CGUIFadeLabelControl::CGUIFadeLabelControl(), and SetInitialCondition().
Calculate()
void CAnimation::Calculate (const CPoint & point) private
References ANIM_PROCESS_NORMAL, ANIM_STATE_APPLIED, ANIM_STATE_NONE, CAnimEffect::ApplyState(), CAnimEffect::Calculate(), center, CAnimEffect::GetLength(), m_amount, m_currentProcess, m_delay, and m_effects.
Referenced by ApplyAnimation(), and RenderAnimation().
CheckCondition()
bool CAnimation::CheckCondition ()
References INFO::DEFAULT_CONTEXT, and m_condition.
Referenced by CGUIControl::GetAnimation().
Create()
void CAnimation::Create (const TiXmlElement * node, const CRect & rect, int context)
References AddEffect(), ANIM_REPEAT_LOOP, ANIM_REPEAT_PULSE, ANIM_TYPE_CONDITIONAL, ANIM_TYPE_FOCUS, ANIM_TYPE_HIDDEN, ANIM_TYPE_UNFOCUS, ANIM_TYPE_VISIBLE, ANIM_TYPE_WINDOW_CLOSE, ANIM_TYPE_WINDOW_OPEN, XMLUtils::GetAttribute(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CLog::Log(), LOGERROR, m_condition, m_delay, m_effects, m_length, m_repeatAnim, m_reversible, m_type, node, and CGUIInfoManager::Register().
Referenced by CGUIControlFactory::GetAnimations(), and CGUIWindow::Load().
CreateFader()
CAnimation CAnimation::CreateFader (float start, float end, unsigned int delay, unsigned int length, ANIMATION_TYPE type = ANIM_TYPE_NONE) static
References end(), m_delay, m_effects, m_length, and m_type.
Referenced by CGUIWindowScreensaverDim::CGUIWindowScreensaverDim(), CGUITextBox::SetAutoScrolling(), and CGUITextBox::SetAutoScrolling().
GetProcess()
ANIMATION_PROCESS CAnimation::GetProcess () const inline
References m_currentProcess.
Referenced by CGUIControl::Animate(), CGUIControl::IsAnimating(), CGUIFadeLabelControl::Process(), and CGUITextBox::Process().
GetQueuedProcess()
ANIMATION_PROCESS CAnimation::GetQueuedProcess () const inline
References m_queuedProcess.
Referenced by CGUIControl::IsAnimating().
GetState()
ANIMATION_STATE CAnimation::GetState () const inline
References m_currentState.
Referenced by CGUIControl::Animate(), CGUIFadeLabelControl::Process(), CGUITextBox::Process(), and CGUIControl::QueueAnimation().
GetType()
ANIMATION_TYPE CAnimation::GetType () const inline
References m_type.
Referenced by CGUIControl::Animate(), CGUIControl::FreeResources(), CGUIControl::GetAnimation(), CGUIControl::IsAnimating(), CGUIControl::SetInitialVisibility(), and CGUIControl::UpdateVisibility().
IsReversible()
bool CAnimation::IsReversible () const inline
References m_reversible.
Referenced by CGUIControl::QueueAnimation().
operator=()
CAnimation & CAnimation::operator= (const CAnimation & src)
References CAnimEffect::EFFECT_TYPE_FADE, CAnimEffect::EFFECT_TYPE_FADE_DIFFUSE, CAnimEffect::EFFECT_TYPE_ROTATE_X, CAnimEffect::EFFECT_TYPE_ROTATE_Y, CAnimEffect::EFFECT_TYPE_ROTATE_Z, CAnimEffect::EFFECT_TYPE_SLIDE, CAnimEffect::EFFECT_TYPE_ZOOM, m_amount, m_condition, m_currentProcess, m_currentState, m_delay, m_effects, m_lastCondition, m_length, m_queuedProcess, m_repeatAnim, m_reversible, m_start, and m_type.
QueueAnimation()
void CAnimation::QueueAnimation (ANIMATION_PROCESS process)
References m_queuedProcess.
Referenced by CGUIFadeLabelControl::Process(), CGUITextBox::Process(), CGUIControl::QueueAnimation(), and UpdateCondition().
RenderAnimation() [1/2]
void CAnimation::RenderAnimation (TransformMatrix & matrix) inline
References RenderAnimation().
Referenced by CGUIControl::Animate(), CGUIFadeLabelControl::Process(), CGUITextBox::Process(), and RenderAnimation().
RenderAnimation() [2/2]
void CAnimation::RenderAnimation (TransformMatrix & matrix, const CPoint & center)
References ANIM_PROCESS_NONE, ANIM_STATE_APPLIED, ANIM_STATE_NONE, Calculate(), center, m_currentProcess, m_currentState, m_effects, and m_queuedProcess.
ResetAnimation()
void CAnimation::ResetAnimation ()
References ANIM_PROCESS_NONE, ANIM_STATE_NONE, m_currentProcess, m_currentState, and m_queuedProcess.
Referenced by CGUIControl::FreeResources(), CGUIFadeLabelControl::Process(), CGUIControl::QueueAnimation(), CGUITextBox::ResetAutoScrolling(), SetInitialCondition(), CGUIControl::SetVisible(), and UpdateCondition().
SetInitialCondition()
void CAnimation::SetInitialCondition ()
References ApplyAnimation(), INFO::DEFAULT_CONTEXT, m_condition, m_lastCondition, and ResetAnimation().
Referenced by CGUIControl::SetInitialVisibility().
UpdateCondition()
void CAnimation::UpdateCondition (const CGUIListItem * item = NULL)
References ANIM_PROCESS_NORMAL, ANIM_PROCESS_REVERSE, INFO::DEFAULT_CONTEXT, m_condition, m_lastCondition, m_reversible, QueueAnimation(), and ResetAnimation().
Referenced by CGUIControl::UpdateVisibility().
Member Data Documentation
m_amount
unsigned int CAnimation::m_amount private
Referenced by Animate(), ApplyAnimation(), Calculate(), CAnimation(), and operator=().
m_condition
INFO::InfoPtr CAnimation::m_condition private
Referenced by CheckCondition(), Create(), operator=(), SetInitialCondition(), and UpdateCondition().
m_currentProcess
ANIMATION_PROCESS CAnimation::m_currentProcess private
Referenced by Animate(), ApplyAnimation(), Calculate(), CAnimation(), GetProcess(), operator=(), RenderAnimation(), and ResetAnimation().
m_currentState
ANIMATION_STATE CAnimation::m_currentState private
Referenced by Animate(), ApplyAnimation(), CAnimation(), GetState(), operator=(), RenderAnimation(), and ResetAnimation().
m_delay
unsigned int CAnimation::m_delay private
Referenced by Animate(), Calculate(), CAnimation(), Create(), CreateFader(), and operator=().
m_effects
std::vector<CAnimEffect *> CAnimation::m_effects private
Referenced by AddEffect(), Calculate(), Create(), CreateFader(), operator=(), RenderAnimation(), and ~CAnimation().
m_lastCondition
bool CAnimation::m_lastCondition private
Referenced by Animate(), CAnimation(), operator=(), SetInitialCondition(), and UpdateCondition().
m_length
unsigned int CAnimation::m_length private
Referenced by Animate(), ApplyAnimation(), CAnimation(), Create(), CreateFader(), and operator=().
m_queuedProcess
ANIMATION_PROCESS CAnimation::m_queuedProcess private
Referenced by Animate(), ApplyAnimation(), CAnimation(), GetQueuedProcess(), operator=(), QueueAnimation(), RenderAnimation(), and ResetAnimation().
m_repeatAnim
ANIM_REPEAT CAnimation::m_repeatAnim private
Referenced by Animate(), ApplyAnimation(), CAnimation(), Create(), and operator=().
m_reversible
bool CAnimation::m_reversible private
Referenced by CAnimation(), Create(), IsReversible(), operator=(), and UpdateCondition().
m_start
unsigned int CAnimation::m_start private
Referenced by Animate(), CAnimation(), and operator=().
m_type
ANIMATION_TYPE CAnimation::m_type private
Referenced by AddEffect(), CAnimation(), Create(), CreateFader(), GetType(), and operator=().
The documentation for this class was generated from the following files:
VisibleEffect.h
VisibleEffect.cpp