Kodi Documentation: CGUIControlButtonSetting Class Reference
CGUIControlButtonSetting Class Reference
#include <GUIControlSettings.h>
Public Member Functions
CGUIControlButtonSetting (CGUIButtonControl *pButton, int id, std::shared_ptr< CSetting > pSetting, ILocalizer *localizer)
~CGUIControlButtonSetting () override
CGUIControl * GetControl () override
bool OnClick () override
void Clear () override
Clears the attached control.
Public Member Functions inherited from CGUIControlBaseSetting
CGUIControlBaseSetting (int id, std::shared_ptr< CSetting > pSetting, ILocalizer *localizer)
~CGUIControlBaseSetting () override=default
int GetID () const
std::shared_ptr< CSetting > GetSetting ()
void SetDelayed ()
Specifies that this setting should update after a delay Useful for settings that have options to navigate through and may take a while, or require additional input to update once the final setting is chosen. Settings default to updating instantly.
bool IsDelayed () const
Returns whether this setting should have delayed update.
bool IsEnabled () const
Returns whether this setting is enabled or disabled This state is independent of the real enabled state of a setting control but represents the enabled state of the setting itself based on specific conditions.
bool IsValid () const
Returns whether the setting's value is valid or not.
void SetValid (bool valid)
void UpdateFromControl ()
void UpdateFromSetting (bool updateDisplayOnly=false)
Static Public Member Functions
static bool GetPath (const std::shared_ptr< CSettingPath > &pathSetting, ILocalizer *localizer)
Protected Member Functions
void Update (bool fromControl, bool updateDisplayOnly) override
void OnSliderChange (void *data, CGUISliderControl *slider) override
Callback function called whenever the user moves the slider.
Protected Member Functions inherited from CGUIControlBaseSetting
std::string Localize (std::uint32_t code) const override
Protected Member Functions inherited from ILocalizer
ILocalizer ()=default
virtual ~ILocalizer ()=default
Protected Member Functions inherited from ISliderCallback
virtual ~ISliderCallback ()=default
Private Attributes
CGUIButtonControl * m_pButton
Additional Inherited Members
Protected Attributes inherited from CGUIControlBaseSetting
int m_id
std::shared_ptr< CSetting > m_pSetting
ILocalizer * m_localizer
bool m_delayed = false
bool m_valid = true
Constructor & Destructor Documentation
CGUIControlButtonSetting()
CGUIControlButtonSetting::CGUIControlButtonSetting (CGUIButtonControl * pButton, int id, std::shared_ptr< CSetting > pSetting, ILocalizer * localizer)
References m_pButton, and CGUIControl::SetID().
~CGUIControlButtonSetting()
CGUIControlButtonSetting::~CGUIControlButtonSetting () override default
Member Function Documentation
Clear()
void CGUIControlButtonSetting::Clear () inline override virtual
Clears the attached control.
Implements CGUIControlBaseSetting.
References m_pButton.
GetControl()
CGUIControl * CGUIControlButtonSetting::GetControl () inline override virtual
Reimplemented from CGUIControlBaseSetting.
References m_pButton.
GetPath()
bool CGUIControlButtonSetting::GetPath (const std::shared_ptr< CSettingPath > & pathSetting, ILocalizer * localizer) static
References CServiceBroker::GetFileExtensionProvider(), CMediaSourceSettings::GetInstance(), CMediaManager::GetLocalDrives(), CServiceBroker::GetMediaManager(), CMediaManager::GetNetworkLocations(), CFileExtensionProvider::GetPictureExtensions(), CMediaSourceSettings::GetSources(), CGUIControlBaseSetting::Localize(), CGUIDialogFileBrowser::ShowAndGetDirectory(), and CGUIDialogFileBrowser::ShowAndGetFile().
Referenced by KODI::CDRIP::CCDDARipper::CreateAlbumDir(), OnClick(), and CScreenShot::TakeScreenshot().
OnClick()
bool CGUIControlButtonSetting::OnClick () override virtual
Reimplemented from CGUIControlBaseSetting.
References GetPath(), Integer, CGUIControlBaseSetting::IsValid(), List, CGUIControlBaseSetting::Localize(), CGUIControlBaseSetting::m_localizer, m_pButton, CGUIControlBaseSetting::m_pSetting, max, min, Number, CGUIWindowAddonBrowser::SelectAddonID(), CGUIControlBaseSetting::SetValid(), CGUIDialogNumeric::ShowAndGetDate(), CGUIDialogSlider::ShowAndGetInput(), CGUIDialogNumeric::ShowAndGetTime(), CGUIControlBaseSetting::UpdateFromSetting(), and value.
OnSliderChange()
void CGUIControlButtonSetting::OnSliderChange (void * data, CGUISliderControl * slider) override protected virtual
Callback function called whenever the user moves the slider.
Parameters
data pointer of callbackData
slider pointer to the slider control
Implements ISliderCallback.
References CGUISliderControl::GetFloatValue(), CGUISliderControl::GetIntValue(), CGUIControlSliderSetting::GetText(), Integer, CGUIControlBaseSetting::m_localizer, CGUIControlBaseSetting::m_pSetting, Number, and CGUISliderControl::SetTextValue().
Update()
void CGUIControlButtonSetting::Update (bool fromControl, bool updateDisplayOnly) override protected virtual
Reimplemented from CGUIControlBaseSetting.
References Action, ADDON::CHOICE_YES, g_localizeStrings, CLocalizeStrings::Get(), ADDON::CAddonMgr::GetAddon(), CServiceBroker::GetAddonMgr(), CGUIButtonControl::GetLabel2(), CGUIControlSliderSetting::GetText(), Integer, List, CGUIControlBaseSetting::m_localizer, m_pButton, CGUIControlBaseSetting::m_pSetting, CUtil::MakeShortenPath(), Number, CGUIButtonControl::SetLabel2(), String, and CGUIControlBaseSetting::Update().
Member Data Documentation
m_pButton
CGUIButtonControl* CGUIControlButtonSetting::m_pButton private
Referenced by CGUIControlButtonSetting(), Clear(), GetControl(), OnClick(), and Update().
The documentation for this class was generated from the following files:
GUIControlSettings.h
GUIControlSettings.cpp