Kodi Documentation: CAppInboundProtocol Class Reference
CAppInboundProtocol Class Reference
#include <AppInboundProtocol.h>
Public Member Functions
CAppInboundProtocol (CApplication &app)
bool OnEvent (const XBMC_Event &newEvent)
void SetRenderGUI (bool renderGUI)
void Close ()
Protected Member Functions
void HandleEvents ()
Protected Attributes
bool m_closed = false
CApplication & m_pApp
std::deque< XBMC_Event > m_portEvents
CCriticalSection m_portSection
Friends
class CApplication
Constructor & Destructor Documentation
CAppInboundProtocol()
CAppInboundProtocol::CAppInboundProtocol (CApplication & app)
Member Function Documentation
Close()
void CAppInboundProtocol::Close ()
References m_closed, and m_portSection.
HandleEvents()
void CAppInboundProtocol::HandleEvents () protected
References ACTION_MOUSE_MOVE, CGraphicContext::ApplyModeChange(), CGraphicContext::ApplyWindowResize(), CWinSystemBase::ForceFullScreen(), CServiceBroker::GetAppMessenger(), CComponentContainer< BaseType >::GetComponent(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetGUI(), CServiceBroker::GetInputManager(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetWinSystem(), CApplication::m_bStop, m_pApp, m_portEvents, m_portSection, CApplication::OnAction(), CWinSystemBase::OnChangeScreen(), CInputManager::OnEvent(), CWinSystemBase::OnMove(), RES_DESKTOP, CApplicationPowerHandling::ResetScreenSaver(), CSettings::SETTING_WINDOW_HEIGHT, CSettings::SETTING_WINDOW_WIDTH, TMSG_QUIT, XBMC_MODECHANGE, XBMC_QUIT, XBMC_SCREENCHANGE, XBMC_SETFOCUS, XBMC_USEREVENT, XBMC_VIDEOMOVE, and XBMC_VIDEORESIZE.
OnEvent()
bool CAppInboundProtocol::OnEvent (const XBMC_Event & newEvent)
References m_closed, m_portEvents, and m_portSection.
SetRenderGUI()
void CAppInboundProtocol::SetRenderGUI (bool renderGUI)
References CServiceBroker::GetAppComponents(), and CApplicationPowerHandling::SetRenderGUI().
Friends And Related Symbol Documentation
CApplication
friend class CApplication friend
Member Data Documentation
m_closed
bool CAppInboundProtocol::m_closed = false protected
Referenced by Close(), and OnEvent().
m_pApp
CApplication& CAppInboundProtocol::m_pApp protected
Referenced by HandleEvents().
m_portEvents
std::deque<XBMC_Event> CAppInboundProtocol::m_portEvents protected
Referenced by HandleEvents(), and OnEvent().
m_portSection
CCriticalSection CAppInboundProtocol::m_portSection protected
Referenced by Close(), HandleEvents(), and OnEvent().
The documentation for this class was generated from the following files:
AppInboundProtocol.h
AppInboundProtocol.cpp