Kodi Documentation: PVR::CPVRGUIActionsRecordings Class Reference
PVR::CPVRGUIActionsRecordings Class Reference
#include <PVRGUIActionsRecordings.h>
Public Member Functions
CPVRGUIActionsRecordings ()
~CPVRGUIActionsRecordings () override=default
bool ShowRecordingInfo (const CFileItem &item) const
Open a dialog with information for a given recording.
bool EditRecording (const CFileItem &item) const
Open the recording settings dialog to edit a recording.
bool CanEditRecording (const CFileItem &item) const
Check if any recording settings can be edited.
bool DeleteRecording (const CFileItem &item) const
Delete a recording, always showing a confirmation dialog.
bool DeleteWatchedRecordings (const CFileItem &item) const
Delete all watched recordings contained in the given folder, always showing a confirmation dialog.
bool DeleteAllRecordingsFromTrash () const
Delete all recordings from trash, always showing a confirmation dialog.
bool UndeleteRecording (const CFileItem &item) const
Undelete a recording.
bool IncrementPlayCount (const CFileItem &item) const
Increment the play count of a recording. Process "Delete after watching" action.
bool MarkWatched (const CFileItem &item, bool watched) const
Mark a recording watched or unwatched. Process "Delete after watching" action.
Public Member Functions inherited from PVR::IPVRComponent
virtual ~IPVRComponent ()=default
Private Member Functions
CPVRGUIActionsRecordings (const CPVRGUIActionsRecordings &)=delete
CPVRGUIActionsRecordings const & operator= (CPVRGUIActionsRecordings const &)=delete
bool ConfirmDeleteRecording (const CFileItem &item) const
Open a dialog to confirm to delete a recording.
bool ConfirmDeleteWatchedRecordings (const CFileItem &item) const
Open a dialog to confirm delete all watched recordings contained in the given folder.
bool ConfirmDeleteAllRecordingsFromTrash () const
Open a dialog to confirm to permanently remove all deleted recordings.
bool ShowRecordingSettings (const std::shared_ptr< CPVRRecording > &recording) const
Open the recording settings dialog.
bool ProcessDeleteAfterWatch (const CFileItem &item) const
Process action according to "Delete after watching" setting value.
Private Attributes
CPVRSettings m_settings
Constructor & Destructor Documentation
CPVRGUIActionsRecordings() [1/2]
CPVRGUIActionsRecordings::CPVRGUIActionsRecordings ()
References CSettings::SETTING_PVRRECORD_DELETEAFTERWATCH.
~CPVRGUIActionsRecordings()
PVR::CPVRGUIActionsRecordings::~CPVRGUIActionsRecordings () override default
CPVRGUIActionsRecordings() [2/2]
PVR::CPVRGUIActionsRecordings::CPVRGUIActionsRecordings (const CPVRGUIActionsRecordings &) private delete
Member Function Documentation
CanEditRecording()
bool CPVRGUIActionsRecordings::CanEditRecording (const CFileItem & item) const
Check if any recording settings can be edited.
Parameters
item containing the recording to edit.
Returns
true on success, false otherwise.
References PVR::CGUIDialogPVRRecordingSettings::CanEditRecording().
ConfirmDeleteAllRecordingsFromTrash()
bool CPVRGUIActionsRecordings::ConfirmDeleteAllRecordingsFromTrash () const private
Open a dialog to confirm to permanently remove all deleted recordings.
Returns
true, to proceed with delete, false otherwise.
References CGUIDialogYesNo::ShowAndGetInput().
Referenced by DeleteAllRecordingsFromTrash().
ConfirmDeleteRecording()
bool CPVRGUIActionsRecordings::ConfirmDeleteRecording (const CFileItem & item) const private
Open a dialog to confirm to delete a recording.
Parameters
item the recording to delete.
Returns
true, to proceed with delete, false otherwise.
References CGUIListItem::GetLabel(), CFileItem::GetPVRRecordingInfoTag(), CGUIListItem::m_bIsFolder, and CGUIDialogYesNo::ShowAndGetInput().
Referenced by DeleteRecording().
ConfirmDeleteWatchedRecordings()
bool CPVRGUIActionsRecordings::ConfirmDeleteWatchedRecordings (const CFileItem & item) const private
Open a dialog to confirm delete all watched recordings contained in the given folder.
Parameters
item containing a recording folder containing the items to delete.
Returns
true, to proceed with delete, false otherwise.
References CGUIListItem::GetLabel(), and CGUIDialogYesNo::ShowAndGetInput().
Referenced by DeleteWatchedRecordings().
DeleteAllRecordingsFromTrash()
bool CPVRGUIActionsRecordings::DeleteAllRecordingsFromTrash () const
Delete all recordings from trash, always showing a confirmation dialog.
Returns
true, if the recordings were permanently deleted successfully, false otherwise.
References ConfirmDeleteAllRecordingsFromTrash().
DeleteRecording()
bool CPVRGUIActionsRecordings::DeleteRecording (const CFileItem & item) const
Delete a recording, always showing a confirmation dialog.
Parameters
item containing a recording to delete.
Returns
true, if the recording was deleted successfully, false otherwise.
References ConfirmDeleteRecording(), CFileItem::IsParentFolder(), CFileItem::IsPVRRecording(), CGUIListItem::m_bIsFolder, and KODI::MESSAGING::HELPERS::ShowOKDialogText().
DeleteWatchedRecordings()
bool CPVRGUIActionsRecordings::DeleteWatchedRecordings (const CFileItem & item) const
Delete all watched recordings contained in the given folder, always showing a confirmation dialog.
Parameters
item containing a recording folder containing the items to delete.
Returns
true, if the recordings were deleted successfully, false otherwise.
References ConfirmDeleteWatchedRecordings(), CFileItem::IsParentFolder(), CGUIListItem::m_bIsFolder, and KODI::MESSAGING::HELPERS::ShowOKDialogText().
EditRecording()
bool CPVRGUIActionsRecordings::EditRecording (const CFileItem & item) const
Open the recording settings dialog to edit a recording.
Parameters
item containing the recording to edit.
Returns
true on success, false otherwise.
References CServiceBroker::GetPVRManager(), PVR::CPVRItem::GetRecording(), LOGERROR, and ShowRecordingSettings().
IncrementPlayCount()
bool CPVRGUIActionsRecordings::IncrementPlayCount (const CFileItem & item) const
Increment the play count of a recording. Process "Delete after watching" action.
Parameters
item containing a recording for which the play count shall be incremented.
Returns
true, if the recording's play count was incremented successfully, false otherwise.
References CFileItem::GetPVRRecordingInfoTag(), CFileItem::IsPVRRecording(), and ProcessDeleteAfterWatch().
MarkWatched()
bool CPVRGUIActionsRecordings::MarkWatched (const CFileItem & item, bool watched) const
Mark a recording watched or unwatched. Process "Delete after watching" action.
Parameters
item containing a recording to be marked watched or unwatched.
watched Whether to mark the recording watched or unwatched.
Returns
true, if the recording's watched state was changed successfully, false otherwise.
References CServiceBroker::GetPVRManager(), CFileItem::GetPVRRecordingInfoTag(), CFileItem::IsPVRRecording(), MarkWatched(), and ProcessDeleteAfterWatch().
Referenced by MarkWatched(), and CVideoLibraryMarkWatchedJob::Work().
operator=()
CPVRGUIActionsRecordings const & PVR::CPVRGUIActionsRecordings::operator= (CPVRGUIActionsRecordings const &) private delete
ProcessDeleteAfterWatch()
bool CPVRGUIActionsRecordings::ProcessDeleteAfterWatch (const CFileItem & item) const private
Process action according to "Delete after watching" setting value.
Parameters
item The watched recording.
Returns
true on success, false otherwise.
References PVR::CPVREventLogJob::AddEvent(), anonymous_namespace{PVRGUIActionsRecordings.cpp}::ASK, g_localizeStrings, CLocalizeStrings::Get(), PVR::CPVRSettings::GetIntValue(), CServiceBroker::GetJobManager(), CFileItem::GetPVRRecordingInfoTag(), Information, LOGERROR, m_settings, anonymous_namespace{PVRGUIActionsRecordings.cpp}::NO, CSettings::SETTING_PVRRECORD_DELETEAFTERWATCH, KODI::MESSAGING::HELPERS::ShowOKDialogText(), KODI::MESSAGING::HELPERS::ShowYesNoDialogLines(), and anonymous_namespace{PVRGUIActionsRecordings.cpp}::YES.
Referenced by IncrementPlayCount(), and MarkWatched().
ShowRecordingInfo()
bool CPVRGUIActionsRecordings::ShowRecordingInfo (const CFileItem & item) const
Open a dialog with information for a given recording.
Parameters
item containing a recording.
Returns
true on success, false otherwise.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CFileItem::IsPVRRecording(), LOGERROR, CGUIDialog::Open(), PVR::CGUIDialogPVRRecordingInfo::SetRecording(), and WINDOW_DIALOG_PVR_RECORDING_INFO.
ShowRecordingSettings()
bool CPVRGUIActionsRecordings::ShowRecordingSettings (const std::shared_ptr< CPVRRecording > & recording) const private
Open the recording settings dialog.
Parameters
recording containing the recording the settings shall be displayed for.
Returns
true, if the dialog was ended successfully, false otherwise.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CGUIDialogSettingsBase::IsConfirmed(), LOGERROR, CGUIDialog::Open(), PVR::CGUIDialogPVRRecordingSettings::SetRecording(), and WINDOW_DIALOG_PVR_RECORDING_SETTING.
Referenced by EditRecording().
UndeleteRecording()
bool CPVRGUIActionsRecordings::UndeleteRecording (const CFileItem & item) const
Undelete a recording.
Parameters
item containing a recording to undelete.
Returns
true, if the recording was undeleted successfully, false otherwise.
References CFileItem::IsDeletedPVRRecording(), and KODI::MESSAGING::HELPERS::ShowOKDialogText().
Member Data Documentation
m_settings
CPVRSettings PVR::CPVRGUIActionsRecordings::m_settings private
Referenced by ProcessDeleteAfterWatch().
The documentation for this class was generated from the following files:
PVRGUIActionsRecordings.h
PVRGUIActionsRecordings.cpp