Kodi Documentation: XFILE::CMultiPathFile Class Reference
XFILE::CMultiPathFile Class Reference
#include <MultiPathFile.h>
Public Member Functions
CMultiPathFile (void)
~CMultiPathFile (void) override
bool Open (const CURL &url) override
bool Exists (const CURL &url) override
int Stat (const CURL &url, struct __stat64 *buffer) override
Public Member Functions inherited from XFILE::COverrideFile
COverrideFile (bool writable)
~COverrideFile () override
bool Open (const CURL &url) override
bool Exists (const CURL &url) override
int Stat (const CURL &url, struct __stat64 *buffer) override
int Stat (struct __stat64 *buffer) override
bool OpenForWrite (const CURL &url, bool bOverWrite=false) override
bool Delete (const CURL &url) override
bool Rename (const CURL &url, const CURL &urlnew) override
ssize_t Read (void *lpBuf, size_t uiBufSize) override
ssize_t Write (const void *lpBuf, size_t uiBufSize) override
int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET) override
void Close () override
int64_t GetPosition () override
int64_t GetLength () override
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool ReOpen (const CURL &url)
virtual bool ReadString (char *szLine, int iLineLength)
virtual void Flush ()
virtual int Truncate (int64_t size)
virtual int GetChunkSize ()
virtual double GetDownloadSpeed ()
virtual bool SetHidden (const CURL &url, bool hidden)
virtual int IoControl (EIoControl request, void *param)
virtual const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
virtual const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
Protected Member Functions
std::string TranslatePath (const CURL &url) override
Additional Inherited Members
Protected Attributes inherited from XFILE::COverrideFile
CFile m_file
bool m_writable
Constructor & Destructor Documentation
CMultiPathFile()
CMultiPathFile::CMultiPathFile (void)
~CMultiPathFile()
CMultiPathFile::~CMultiPathFile (void) override default
Member Function Documentation
Exists()
bool CMultiPathFile::Exists (const CURL & url) override virtual
Implements XFILE::IFile.
References URIUtils::AddFileToFolder(), XFILE::CFile::Exists(), CURL::Get(), XFILE::CMultiPathDirectory::GetPaths(), and URIUtils::Split().
Open()
bool CMultiPathFile::Open (const CURL & url) override virtual
Implements XFILE::IFile.
References URIUtils::AddFileToFolder(), CURL::Get(), XFILE::CMultiPathDirectory::GetPaths(), XFILE::COverrideFile::m_file, XFILE::CFile::Open(), and URIUtils::Split().
Stat()
int CMultiPathFile::Stat (const CURL & url, struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about file specified by url. For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
url specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Implements XFILE::IFile.
References URIUtils::AddFileToFolder(), CURL::Get(), XFILE::CMultiPathDirectory::GetPaths(), URIUtils::Split(), and XFILE::CFile::Stat().
TranslatePath()
std::string CMultiPathFile::TranslatePath (const CURL & url) override protected virtual
Implements XFILE::COverrideFile.
References CURL::Get().
The documentation for this class was generated from the following files:
MultiPathFile.h
MultiPathFile.cpp