Kodi Documentation: CSettingInt Class Reference
CSettingInt Class Reference
Settings
Integer setting implementation.
#include <Setting.h>
Public Member Functions
CSettingInt (const std::string &id, CSettingsManager *settingsManager=nullptr)
CSettingInt (const std::string &id, const CSettingInt &setting)
CSettingInt (const std::string &id, int label, int value, CSettingsManager *settingsManager=nullptr)
CSettingInt (const std::string &id, int label, int value, int minimum, int step, int maximum, CSettingsManager *settingsManager=nullptr)
CSettingInt (const std::string &id, int label, int value, const TranslatableIntegerSettingOptions &options, CSettingsManager *settingsManager=nullptr)
~CSettingInt () override=default
std::shared_ptr< CSetting > Clone (const std::string &id) const override
void MergeDetails (const CSetting &other) override
bool Deserialize (const TiXmlNode *node, bool update=false) override
Deserializes the given XML node into the properties of the setting object.
bool FromString (const std::string &value) override
std::string ToString () const override
bool Equals (const std::string &value) const override
bool CheckValidity (const std::string &value) const override
virtual bool CheckValidity (int value) const
void Reset () override
int GetValue () const
bool SetValue (int value)
int GetDefault () const
void SetDefault (int value)
int GetMinimum () const
void SetMinimum (int minimum)
int GetStep () const
void SetStep (int step)
int GetMaximum () const
void SetMaximum (int maximum)
SettingOptionsType GetOptionsType () const
const TranslatableIntegerSettingOptions & GetTranslatableOptions () const
void SetTranslatableOptions (const TranslatableIntegerSettingOptions &options)
const IntegerSettingOptions & GetOptions () const
void SetOptions (const IntegerSettingOptions &options)
const std::string & GetOptionsFillerName () const
void SetOptionsFillerName (const std::string &optionsFillerName, void *data=nullptr)
void SetOptionsFiller (IntegerSettingOptionsFiller optionsFiller, void *data=nullptr)
const IntegerSettingOptions & GetDynamicOptions () const
IntegerSettingOptions UpdateDynamicOptions ()
SettingOptionsSort GetOptionsSort () const
void SetOptionsSort (SettingOptionsSort optionsSort)
Public Member Functions inherited from CTraitedSetting< int, SettingType::Integer >
SettingType GetType () const override
Public Member Functions inherited from CSetting
CSetting (const std::string &id, CSettingsManager *settingsManager=nullptr)
CSetting (const std::string &id, const CSetting &setting)
~CSetting () override=default
void MergeBasics (const CSetting &other)
bool IsEnabled () const
bool GetEnabled () const
void SetEnabled (bool enabled)
bool IsDefault () const
const std::string & GetParent () const
void SetParent (const std::string &parentSetting)
SettingLevel GetLevel () const
void SetLevel (SettingLevel level)
std::shared_ptr< const ISettingControl > GetControl () const
std::shared_ptr< ISettingControl > GetControl ()
void SetControl (std::shared_ptr< ISettingControl > control)
const SettingDependencies & GetDependencies () const
void SetDependencies (const SettingDependencies &dependencies)
const std::set< CSettingUpdate > & GetUpdates () const
void SetCallback (ISettingCallback *callback)
bool IsReference () const
const std::string & GetReferencedId () const
void SetReferencedId (const std::string &referencedId)
void MakeReference (const std::string &referencedId="")
bool GetVisible () const
bool IsVisible () const override
Whether the setting object is visible or hidden.
void OnSettingAction (const std::shared_ptr< const CSetting > &setting) override
The given setting has been activated.
Public Member Functions inherited from ISetting
ISetting (const std::string &id, CSettingsManager *settingsManager=nullptr)
Creates a new setting object with the given identifier.
virtual ~ISetting ()=default
const std::string & GetId () const
Gets the identifier of the setting object.
virtual void SetVisible (bool visible)
Sets the visibility state of the setting object.
int GetLabel () const
Gets the localizeable label ID of the setting group.
void SetLabel (int label)
Sets the localizeable label ID of the setting group.
int GetHelp () const
Gets the localizeable help ID of the setting group.
void SetHelp (int help)
Sets the localizeable help ID of the setting group.
virtual bool MeetsRequirements () const
Whether the setting object meets all necessary requirements.
virtual void CheckRequirements ()
Checks if the setting object meets all necessary requirements.
virtual void SetRequirementsMet (bool requirementsMet)
Sets whether the setting object meets all necessary requirements.
Private Member Functions
void copy (const CSettingInt &setting)
Static Private Member Functions
static bool fromString (const std::string &strValue, int &value)
Private Attributes
int m_value = DefaultValue
int m_default = DefaultValue
int m_min = DefaultMin
int m_step = DefaultStep
int m_max = DefaultMax
TranslatableIntegerSettingOptions m_translatableOptions
IntegerSettingOptions m_options
std::string m_optionsFillerName
IntegerSettingOptionsFiller m_optionsFiller = nullptr
void * m_optionsFillerData = nullptr
IntegerSettingOptions m_dynamicOptions
SettingOptionsSort m_optionsSort = SettingOptionsSort::NoSorting
Static Private Attributes
static constexpr Value DefaultValue = 0
static constexpr Value DefaultMin = DefaultValue
static constexpr Value DefaultStep = 1
static constexpr Value DefaultMax = DefaultValue
static Logger s_logger
Additional Inherited Members
Public Types inherited from CTraitedSetting< int, SettingType::Integer >
typedef int Value
Static Public Member Functions inherited from CTraitedSetting< int, SettingType::Integer >
static SettingType Type ()
Static Public Member Functions inherited from CSetting
static bool DeserializeIdentification (const TiXmlNode *node, std::string &identification, bool &isReference)
Deserializes the given XML node to retrieve a setting object's identifier and whether the setting is a reference to another setting or not.
Static Public Member Functions inherited from ISetting
static bool DeserializeIdentification (const TiXmlNode *node, std::string &identification)
Deserializes the given XML node to retrieve a setting object's identifier.
Protected Member Functions inherited from CTraitedSetting< int, SettingType::Integer >
CTraitedSetting (const std::string &id, CSettingsManager *settingsManager=nullptr)
CTraitedSetting (const std::string &id, const CTraitedSetting &setting)
~CTraitedSetting () override=default
Protected Member Functions inherited from CSetting
bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting is being changed.
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode) override
The given setting needs to be updated.
void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName) override
The given property of the given setting has changed.
void Copy (const CSetting &setting)
template<class TSetting >
std::shared_ptr< TSetting > shared_from_base ()
Protected Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
Static Protected Member Functions inherited from ISetting
static bool DeserializeIdentificationFromAttribute (const TiXmlNode *node, const std::string &attribute, std::string &identification)
Deserializes the given XML node to retrieve a setting object's identifier from the given attribute.
Protected Attributes inherited from CSetting
ISettingCallback * m_callback = nullptr
bool m_enabled = true
std::string m_parentSetting
SettingLevel m_level = SettingLevel::Standard
std::shared_ptr< ISettingControl > m_control
SettingDependencies m_dependencies
std::set< CSettingUpdate > m_updates
bool m_changed = false
CSharedSection m_critical
std::string m_referencedId
Protected Attributes inherited from ISetting
std::string m_id
CSettingsManager * m_settingsManager
Static Protected Attributes inherited from ISetting
static constexpr int DefaultLabel = -1
Detailed Description
Integer setting implementation.
See also
CSetting
Constructor & Destructor Documentation
CSettingInt() [1/5]
CSettingInt::CSettingInt (const std::string & id, CSettingsManager * settingsManager = nullptr)
CSettingInt() [2/5]
CSettingInt::CSettingInt (const std::string & id, const CSettingInt & setting)
References copy().
CSettingInt() [3/5]
CSettingInt::CSettingInt (const std::string & id, int label, int value, CSettingsManager * settingsManager = nullptr)
References label, and ISetting::SetLabel().
CSettingInt() [4/5]
CSettingInt::CSettingInt (const std::string & id, int label, int value, int minimum, int step, int maximum, CSettingsManager * settingsManager = nullptr)
References CLog::GetLogger(), CServiceBroker::GetLogging(), label, s_logger, and ISetting::SetLabel().
CSettingInt() [5/5]
CSettingInt::CSettingInt (const std::string & id, int label, int value, const TranslatableIntegerSettingOptions & options, CSettingsManager * settingsManager = nullptr)
References SetTranslatableOptions().
~CSettingInt()
CSettingInt::~CSettingInt () override default
Member Function Documentation
CheckValidity() [1/2]
bool CSettingInt::CheckValidity (const std::string & value) const override virtual
Implements CSetting.
References CheckValidity(), fromString(), and value.
Referenced by CheckValidity(), and SetValue().
CheckValidity() [2/2]
bool CSettingInt::CheckValidity (int value) const virtual
References CheckSettingOptionsValidity(), m_max, m_min, m_options, m_optionsFiller, m_optionsFillerName, m_translatableOptions, and value.
Clone()
SettingPtr CSettingInt::Clone (const std::string & id) const override virtual
Implements CSetting.
copy()
void CSettingInt::copy (const CSettingInt & setting) private
References CSetting::Copy(), CSetting::m_critical, m_default, m_dynamicOptions, m_max, m_min, m_options, m_optionsFiller, m_optionsFillerData, m_optionsFillerName, m_step, m_translatableOptions, and m_value.
Referenced by CSettingInt().
Deserialize()
bool CSettingInt::Deserialize (const TiXmlNode * node, bool update = false) override virtual
Deserializes the given XML node into the properties of the setting object.
If the update parameter is true, the checks for mandatory properties are skipped and values are only updated.
Parameters
node XML node containing the properties of the setting object
update Whether to perform checks for mandatory properties or not
Returns
True if deserialization was successful, false otherwise
Reimplemented from CSetting.
References CSetting::Deserialize(), DeserializeOptionsSort(), XMLUtils::GetInt(), CSettingsManager::GetSettingOptionsFiller(), label, TranslatableIntegerSettingOption::label, CSetting::m_critical, m_default, ISetting::m_id, m_max, m_min, m_options, m_optionsFiller, m_optionsFillerName, m_optionsSort, ISetting::m_settingsManager, m_step, m_translatableOptions, m_value, node, s_logger, SETTING_XML_ATTR_LABEL, SETTING_XML_ELM_CONSTRAINTS, SETTING_XML_ELM_DEFAULT, SETTING_XML_ELM_MAXIMUM, SETTING_XML_ELM_MINIMUM, SETTING_XML_ELM_OPTION, SETTING_XML_ELM_OPTIONS, SETTING_XML_ELM_STEP, value, and TranslatableIntegerSettingOption::value.
Equals()
bool CSettingInt::Equals (const std::string & value) const override virtual
Implements CSetting.
References fromString(), m_value, and value.
fromString()
bool CSettingInt::fromString (const std::string & strValue, int & value) static private
References end(), and value.
Referenced by CheckValidity(), Equals(), and FromString().
FromString()
bool CSettingInt::FromString (const std::string & value) override virtual
Implements CSetting.
References fromString(), SetValue(), and value.
GetDefault()
int CSettingInt::GetDefault () const inline
References m_default.
GetDynamicOptions()
const IntegerSettingOptions & CSettingInt::GetDynamicOptions () const inline
References m_dynamicOptions.
GetMaximum()
int CSettingInt::GetMaximum () const inline
References m_max.
GetMinimum()
int CSettingInt::GetMinimum () const inline
References m_min.
GetOptions()
const IntegerSettingOptions & CSettingInt::GetOptions () const inline
References m_options.
GetOptionsFillerName()
const std::string & CSettingInt::GetOptionsFillerName () const inline
References m_optionsFillerName.
GetOptionsSort()
SettingOptionsSort CSettingInt::GetOptionsSort () const inline
References m_optionsSort.
GetOptionsType()
SettingOptionsType CSettingInt::GetOptionsType () const
References Dynamic, CSetting::m_critical, m_options, m_optionsFiller, m_optionsFillerName, m_translatableOptions, Static, StaticTranslatable, and Unknown.
GetStep()
int CSettingInt::GetStep () const inline
References m_step.
GetTranslatableOptions()
const TranslatableIntegerSettingOptions & CSettingInt::GetTranslatableOptions () const inline
References m_translatableOptions.
GetValue()
int CSettingInt::GetValue () const inline
References CSetting::m_critical, and m_value.
Referenced by CApplicationVolumeHandling::OnSettingChanged().
MergeDetails()
void CSettingInt::MergeDetails (const CSetting & other) override virtual
Implements CSetting.
References CSetting::GetType(), Integer, m_default, m_dynamicOptions, m_max, m_min, m_options, m_optionsFiller, m_optionsFillerData, m_optionsFillerName, m_optionsSort, m_step, m_translatableOptions, m_value, and NoSorting.
Reset()
void CSettingInt::Reset () inline override virtual
Implements CSetting.
References m_default, and SetValue().
SetDefault()
void CSettingInt::SetDefault (int value)
References CSetting::m_changed, CSetting::m_critical, m_default, m_value, and value.
SetMaximum()
void CSettingInt::SetMaximum (int maximum) inline
References m_max.
SetMinimum()
void CSettingInt::SetMinimum (int minimum) inline
References m_min.
SetOptions()
void CSettingInt::SetOptions (const IntegerSettingOptions & options) inline
References m_options.
SetOptionsFiller()
void CSettingInt::SetOptionsFiller (IntegerSettingOptionsFiller optionsFiller, void * data = nullptr) inline
References data(), m_optionsFiller, and m_optionsFillerData.
SetOptionsFillerName()
void CSettingInt::SetOptionsFillerName (const std::string & optionsFillerName, void * data = nullptr) inline
References data(), m_optionsFillerData, and m_optionsFillerName.
SetOptionsSort()
void CSettingInt::SetOptionsSort (SettingOptionsSort optionsSort) inline
References m_optionsSort.
SetStep()
void CSettingInt::SetStep (int step) inline
References m_step.
SetTranslatableOptions()
void CSettingInt::SetTranslatableOptions (const TranslatableIntegerSettingOptions & options) inline
References m_translatableOptions.
Referenced by CSettingInt().
SetValue()
bool CSettingInt::SetValue (int value)
References CheckValidity(), CSetting::m_changed, CSetting::m_critical, m_default, m_value, CSetting::OnSettingChanged(), CSetting::OnSettingChanging(), and value.
Referenced by FromString(), Reset(), and UpdateDynamicOptions().
ToString()
std::string CSettingInt::ToString () const override virtual
Implements CSetting.
References m_value.
UpdateDynamicOptions()
IntegerSettingOptions CSettingInt::UpdateDynamicOptions ()
References CSettingsManager::GetSettingOptionsFiller(), index(), label, CSetting::m_critical, m_dynamicOptions, ISetting::m_id, m_optionsFiller, m_optionsFillerData, m_optionsFillerName, ISetting::m_settingsManager, m_value, CSetting::OnSettingPropertyChanged(), s_logger, and SetValue().
Member Data Documentation
DefaultMax
constexpr Value CSettingInt::DefaultMax = DefaultValue static constexpr private
DefaultMin
constexpr Value CSettingInt::DefaultMin = DefaultValue static constexpr private
DefaultStep
constexpr Value CSettingInt::DefaultStep = 1 static constexpr private
DefaultValue
constexpr Value CSettingInt::DefaultValue = 0 static constexpr private
m_default
int CSettingInt::m_default = DefaultValue private
Referenced by copy(), Deserialize(), GetDefault(), MergeDetails(), Reset(), SetDefault(), and SetValue().
m_dynamicOptions
IntegerSettingOptions CSettingInt::m_dynamicOptions private
Referenced by copy(), GetDynamicOptions(), MergeDetails(), and UpdateDynamicOptions().
m_max
int CSettingInt::m_max = DefaultMax private
Referenced by CheckValidity(), copy(), Deserialize(), GetMaximum(), MergeDetails(), and SetMaximum().
m_min
int CSettingInt::m_min = DefaultMin private
Referenced by CheckValidity(), copy(), Deserialize(), GetMinimum(), MergeDetails(), and SetMinimum().
m_options
IntegerSettingOptions CSettingInt::m_options private
Referenced by CheckValidity(), copy(), Deserialize(), GetOptions(), GetOptionsType(), MergeDetails(), and SetOptions().
m_optionsFiller
IntegerSettingOptionsFiller CSettingInt::m_optionsFiller = nullptr private
Referenced by CheckValidity(), copy(), Deserialize(), GetOptionsType(), MergeDetails(), SetOptionsFiller(), and UpdateDynamicOptions().
m_optionsFillerData
void* CSettingInt::m_optionsFillerData = nullptr private
Referenced by copy(), MergeDetails(), SetOptionsFiller(), SetOptionsFillerName(), and UpdateDynamicOptions().
m_optionsFillerName
std::string CSettingInt::m_optionsFillerName private
Referenced by CheckValidity(), copy(), Deserialize(), GetOptionsFillerName(), GetOptionsType(), MergeDetails(), SetOptionsFillerName(), and UpdateDynamicOptions().
m_optionsSort
SettingOptionsSort CSettingInt::m_optionsSort = SettingOptionsSort::NoSorting private
Referenced by Deserialize(), GetOptionsSort(), MergeDetails(), and SetOptionsSort().
m_step
int CSettingInt::m_step = DefaultStep private
Referenced by copy(), Deserialize(), GetStep(), MergeDetails(), and SetStep().
m_translatableOptions
TranslatableIntegerSettingOptions CSettingInt::m_translatableOptions private
Referenced by CheckValidity(), copy(), Deserialize(), GetOptionsType(), GetTranslatableOptions(), MergeDetails(), and SetTranslatableOptions().
m_value
int CSettingInt::m_value = DefaultValue private
Referenced by copy(), Deserialize(), Equals(), GetValue(), MergeDetails(), SetDefault(), SetValue(), ToString(), and UpdateDynamicOptions().
s_logger
Logger CSettingInt::s_logger static private
Referenced by CSettingInt(), Deserialize(), and UpdateDynamicOptions().
The documentation for this class was generated from the following files:
Setting.h
Setting.cpp