Kodi Documentation: KODI::WINDOWING::GBM::CWinSystemGbm Class Reference
KODI::WINDOWING::GBM::CWinSystemGbm Class Reference
#include <WinSystemGbm.h>
Public Member Functions
CWinSystemGbm ()
~CWinSystemGbm () override
const std::string GetName () override
bool InitWindowSystem () override
bool DestroyWindowSystem () override
bool ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override
bool SetFullScreen (bool fullScreen, RESOLUTION_INFO &res, bool blankOtherDisplays) override
bool DisplayHardwareScalingEnabled () override
void UpdateDisplayHardwareScaling (const RESOLUTION_INFO &resInfo) override
void FlipPage (bool rendered, bool videoLayer, bool async)
bool CanDoWindowed () override
void UpdateResolutions () override
bool UseLimitedColor () override
bool Hide () override
bool Show (bool raise=true) override
void Register (IDispResource *resource) override
void Unregister (IDispResource *resource) override
bool SetHDR (const VideoPicture *videoPicture) override
Set the HDR metadata. Passing nullptr as the parameter should disable HDR.
bool IsHDRDisplay () override
CHDRCapabilities GetDisplayHDRCapabilities () const override
std::shared_ptr< CVideoLayerBridge > GetVideoLayerBridge () const
void RegisterVideoLayerBridge (std::shared_ptr< CVideoLayerBridge > bridge)
CGBMUtils::CGBMDevice & GetGBMDevice () const
std::shared_ptr< CDRMUtils > GetDrm () const
std::vector< std::string > GetConnectedOutputs () override
Public Member Functions inherited from CWinSystemBase
CWinSystemBase ()
virtual ~CWinSystemBase ()
virtual CRenderSystemBase * GetRenderSystem ()
virtual bool CreateNewWindow (const std::string &name, bool fullScreen, RESOLUTION_INFO &res)=0
virtual bool DestroyWindow ()
virtual bool MoveWindow (int topLeft, int topRight)
virtual void FinishModeChange (RESOLUTION res)
virtual void FinishWindowResize (int newWidth, int newHeight)
virtual bool CenterWindow ()
virtual bool IsCreated ()
virtual void NotifyAppFocusChange (bool bGaining)
virtual void NotifyAppActiveChange (bool bActivated)
virtual void ShowOSMouse (bool show)
virtual bool HasCursor ()
virtual bool HasInertialGestures ()
virtual int NoOfBuffers ()
virtual void ForceFullScreen (const RESOLUTION_INFO &resInfo)
Forces the window to fullscreen provided the window resolution.
virtual float GetDisplayLatency ()
Get average display latency.
virtual float GetFrameLatencyAdjustment ()
Get time that should be subtracted from the display latency for this frame in milliseconds.
virtual bool Minimize ()
virtual bool Restore ()
virtual void OnMove (int x, int y)
virtual unsigned int GetScreenId (const std::string &screen)
Get the screen ID provided the screen name.
virtual void MoveToScreen (unsigned int screenIdx)
Window was requested to move to the given screen.
virtual void OnChangeScreen (unsigned int screenIdx)
Used to signal the windowing system about the change of the current screen.
KODI::WINDOWING::COSScreenSaverManager * GetOSScreenSaver ()
Get OS screen saver inhibit implementation if available.
unsigned int GetWidth ()
unsigned int GetHeight ()
bool IsFullScreen ()
virtual bool SupportsScreenMove ()
Check if the windowing system supports moving windows across screens.
void SetWindowResolution (int width, int height)
std::vector< RESOLUTION_WHR > ScreenResolutions (float refreshrate)
std::vector< REFRESHRATE > RefreshRates (int width, int height, uint32_t dwFlags)
REFRESHRATE DefaultRefreshRate (const std::vector< REFRESHRATE > &rates)
virtual bool HasCalibration (const RESOLUTION_INFO &resInfo)
virtual std::string GetClipboardText (void)
void RegisterRenderLoop (IRenderLoop *client)
void UnregisterRenderLoop (IRenderLoop *client)
void DriveRenderLoop ()
virtual bool MessagePump ()
virtual CGraphicContext & GetGfxContext () const
virtual void * GetHWContext ()
Get OS specific hardware context.
std::shared_ptr< CDPMSSupport > GetDPMSManager ()
virtual HDR_STATUS ToggleHDR ()
virtual HDR_STATUS GetOSHDRStatus ()
virtual float GetGuiSdrPeakLuminance () const
virtual bool HasSystemSdrPeakLuminance ()
virtual bool SupportsVideoSuperResolution ()
System supports Video Super Resolution HW upscaler i.e.: "NVIDIA RTX Video Super Resolution" or "Intel Video Super Resolution".
virtual DEBUG_INFO_RENDER GetDebugInfo ()
Gets debug info from video renderer for use in "Debug Info OSD" (Alt + O)
bool IsHDRDisplaySettingEnabled ()
Return true when HDR display is available and enabled in settings.
bool IsVideoSuperResolutionSettingEnabled ()
Return true when "Video Super Resolution" is supported and enabled in settings.
bool IsHighPrecisionProcessingSettingEnabled ()
Return true when setting "High Precision Processing" is enabled.
std::pair< bool, int > GetDitherSettings ()
Get dither settings.
virtual bool BindTextureUploadContext ()
Binds a shared context to the current thread, in order to upload textures asynchronously.
virtual bool UnbindTextureUploadContext ()
Unbinds the shared context.
virtual bool HasContext ()
Checks if a graphics context is already bound to the current thread.
Protected Member Functions
void OnLostDevice ()
std::unique_ptr< CVideoSync > GetVideoSync (CVideoReferenceClock *clock) override
Protected Member Functions inherited from CWinSystemBase
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, float refreshRate, uint32_t dwFlags)
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, int screenWidth, int screenHeight, float refreshRate, uint32_t dwFlags)
virtual std::unique_ptr< KODI::WINDOWING::IOSScreenSaver > GetOSScreenSaverImpl ()
Protected Attributes
std::shared_ptr< CDRMUtils > m_DRM
std::unique_ptr< CGBMUtils > m_GBM
std::shared_ptr< CVideoLayerBridge > m_videoLayerBridge
CCriticalSection m_resourceSection
std::vector< IDispResource * > m_resources
bool m_dispReset = false
XbmcThreads::EndTime m_dispResetTimer
std::unique_ptr< CLibInputHandler > m_libinput
Protected Attributes inherited from CWinSystemBase
int m_nWidth = 0
int m_nHeight = 0
int m_nTop = 0
int m_nLeft = 0
bool m_bWindowCreated = false
bool m_bFullScreen = false
bool m_bBlankOtherDisplay = false
float m_fRefreshRate = 0.0f
std::unique_ptr< KODI::WINDOWING::COSScreenSaverManager > m_screenSaverManager
CCriticalSection m_renderLoopSection
std::vector< IRenderLoop * > m_renderLoopClients
std::unique_ptr< IWinEvents > m_winEvents
std::unique_ptr< CGraphicContext > m_gfxContext
std::shared_ptr< CDPMSSupport > m_dpms
Private Attributes
uint32_t m_hdr_blob_id = 0
std::unique_ptr< UTILS::CDisplayInfo > m_info
Additional Inherited Members
Static Public Member Functions inherited from CWinSystemBase
static std::unique_ptr< CWinSystemBase > CreateWinSystem ()
Static Public Attributes inherited from CWinSystemBase
static const char * SETTING_WINSYSTEM_IS_HDR_DISPLAY = "winsystem.ishdrdisplay"
Constructor & Destructor Documentation
CWinSystemGbm()
CWinSystemGbm::CWinSystemGbm ()
References CWinSystemBase::m_dpms, and m_libinput.
~CWinSystemGbm()
CWinSystemGbm::~CWinSystemGbm () override default
Member Function Documentation
CanDoWindowed()
bool KODI::WINDOWING::GBM::CWinSystemGbm::CanDoWindowed () inline override virtual
Reimplemented from CWinSystemBase.
DestroyWindowSystem()
bool CWinSystemGbm::DestroyWindowSystem () override virtual
Reimplemented from CWinSystemBase.
Reimplemented in KODI::WINDOWING::GBM::CWinSystemGbmEGLContext.
References CLog::Log(), LOGDEBUG, and m_libinput.
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::DestroyWindowSystem().
DisplayHardwareScalingEnabled()
bool CWinSystemGbm::DisplayHardwareScalingEnabled () override virtual
Reimplemented from CWinSystemBase.
References m_DRM.
Referenced by UpdateDisplayHardwareScaling().
FlipPage()
void CWinSystemGbm::FlipPage (bool rendered, bool videoLayer, bool async)
References m_DRM, m_GBM, and m_videoLayerBridge.
Referenced by Hide(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::PresentRender(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::PresentRender(), and Show().
GetConnectedOutputs()
std::vector< std::string > CWinSystemGbm::GetConnectedOutputs () override virtual
Reimplemented from CWinSystemBase.
References m_DRM.
GetDisplayHDRCapabilities()
CHDRCapabilities CWinSystemGbm::GetDisplayHDRCapabilities () const override virtual
Reimplemented from CWinSystemBase.
References KODI::UTILS::HLG, m_info, KODI::UTILS::PQ, CHDRCapabilities::SetHDR10(), and CHDRCapabilities::SetHLG().
GetDrm()
std::shared_ptr< CDRMUtils > KODI::WINDOWING::GBM::CWinSystemGbm::GetDrm () const inline
References m_DRM.
Referenced by CDumbBufferObject::CDumbBufferObject(), CDVDVideoCodecDRMPRIME::Open(), CRendererDRMPRIME::Register(), and CRendererDRMPRIME::RenderUpdate().
GetGBMDevice()
CGBMUtils::CGBMDevice & KODI::WINDOWING::GBM::CWinSystemGbm::GetGBMDevice () const inline
References m_GBM.
GetName()
const std::string KODI::WINDOWING::GBM::CWinSystemGbm::GetName () inline override virtual
Reimplemented from CWinSystemBase.
GetVideoLayerBridge()
std::shared_ptr< CVideoLayerBridge > KODI::WINDOWING::GBM::CWinSystemGbm::GetVideoLayerBridge () const inline
References m_videoLayerBridge.
Referenced by CRendererDRMPRIME::RenderUpdate().
GetVideoSync()
std::unique_ptr< CVideoSync > CWinSystemGbm::GetVideoSync (CVideoReferenceClock * clock) override protected virtual
Reimplemented from CWinSystemBase.
Hide()
bool CWinSystemGbm::Hide () override virtual
Reimplemented from CWinSystemBase.
References FlipPage(), and m_DRM.
Referenced by CGBMDPMSSupport::EnablePowerSaving().
InitWindowSystem()
bool CWinSystemGbm::InitWindowSystem () override virtual
Reimplemented from CWinSystemBase.
Reimplemented in KODI::WINDOWING::GBM::CWinSystemGbmGLContext, and KODI::WINDOWING::GBM::CWinSystemGbmGLESContext.
References KODI::UTILS::CDisplayInfo::Create(), KODI::WINDOWING::GBM::CDRMConnector::GetEDID(), CServiceBroker::GetSettingsComponent(), CWinSystemBase::InitWindowSystem(), CLog::Log(), LOGDEBUG, LOGERROR, m_DRM, m_GBM, m_info, and CSettings::SETTING_VIDEOSCREEN_LIMITEDRANGE.
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::InitWindowSystemEGL().
IsHDRDisplay()
bool CWinSystemGbm::IsHDRDisplay () override virtual
Reimplemented from CWinSystemBase.
References m_DRM, and m_info.
OnLostDevice()
void CWinSystemGbm::OnLostDevice () protected
References CLog::Log(), LOGDEBUG, m_dispReset, m_resources, and m_resourceSection.
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::CreateNewWindow(), and SetFullScreen().
Register()
void CWinSystemGbm::Register (IDispResource * resource) override virtual
Implements CWinSystemBase.
References m_resources, and m_resourceSection.
RegisterVideoLayerBridge()
void KODI::WINDOWING::GBM::CWinSystemGbm::RegisterVideoLayerBridge (std::shared_ptr< CVideoLayerBridge > bridge) inline
References m_videoLayerBridge.
Referenced by CRendererDRMPRIME::RenderUpdate().
ResizeWindow()
bool CWinSystemGbm::ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override virtual
Implements CWinSystemBase.
SetFullScreen()
bool CWinSystemGbm::SetFullScreen (bool fullScreen, RESOLUTION_INFO & res, bool blankOtherDisplays) override virtual
Implements CWinSystemBase.
Reimplemented in KODI::WINDOWING::GBM::CWinSystemGbmGLContext, and KODI::WINDOWING::GBM::CWinSystemGbmGLESContext.
References CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGERROR, m_dispResetTimer, m_DRM, m_GBM, and OnLostDevice().
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmGLContext::SetFullScreen(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::SetFullScreen(), and UpdateDisplayHardwareScaling().
SetHDR()
bool CWinSystemGbm::SetHDR (const VideoPicture * videoPicture) override virtual
Set the HDR metadata. Passing nullptr as the parameter should disable HDR.
Reimplemented from CWinSystemBase.
References hdr_metadata_infoframe::display_primaries, hdr_metadata_infoframe::eotf, DRMPRIME::GetColorimetry(), DRMPRIME::GetContentLightMetadata(), DRMPRIME::GetEOTF(), DRMPRIME::GetMasteringDisplayMetadata(), CServiceBroker::GetSettingsComponent(), hdr_output_metadata::hdmi_metadata_type1, DRMPRIME::HDMI_STATIC_METADATA_TYPE1, CLog::Log(), LOGDEBUG, LOGVIDEO, m_DRM, m_hdr_blob_id, m_info, hdr_metadata_infoframe::max_cll, hdr_metadata_infoframe::max_display_mastering_luminance, hdr_metadata_infoframe::max_fall, hdr_metadata_infoframe::metadata_type, hdr_output_metadata::metadata_type, hdr_metadata_infoframe::min_display_mastering_luminance, CWinSystemBase::SETTING_WINSYSTEM_IS_HDR_DISPLAY, hdr_metadata_infoframe::white_point, hdr_metadata_infoframe::x, and hdr_metadata_infoframe::y.
Show()
bool CWinSystemGbm::Show (bool raise = true) override virtual
Reimplemented from CWinSystemBase.
References FlipPage(), and m_DRM.
Referenced by CGBMDPMSSupport::DisablePowerSaving().
Unregister()
void CWinSystemGbm::Unregister (IDispResource * resource) override virtual
Implements CWinSystemBase.
References m_resources, and m_resourceSection.
UpdateDisplayHardwareScaling()
void CWinSystemGbm::UpdateDisplayHardwareScaling (const RESOLUTION_INFO & resInfo) override virtual
Todo:
The PR that made the res struct constant was abandoned due to drama.
Reimplemented from CWinSystemBase.
References DisplayHardwareScalingEnabled(), and SetFullScreen().
UpdateResolutions()
void CWinSystemGbm::UpdateResolutions () override virtual
Reimplemented from CWinSystemBase.
References CDisplaySettings::AddResolutionInfo(), CDisplaySettings::ApplyCalibrations(), CDisplaySettings::ClearCustomResolutions(), D3DPRESENTFLAG_INTERLACED, RESOLUTION_INFO::dwFlags, RESOLUTION_INFO::fRefreshRate, CWinSystemBase::GetGfxContext(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), CServiceBroker::GetWinSystem(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iScreenHeight, RESOLUTION_INFO::iScreenWidth, RESOLUTION_INFO::iWidth, CLog::Log(), LOGINFO, m_DRM, RES_DESKTOP, and CGraphicContext::ResetOverscan().
UseLimitedColor()
bool CWinSystemGbm::UseLimitedColor () override virtual
Reimplemented from CWinSystemBase.
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_VIDEOSCREEN_LIMITEDRANGE.
Member Data Documentation
m_dispReset
bool KODI::WINDOWING::GBM::CWinSystemGbm::m_dispReset = false protected
Referenced by OnLostDevice(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::PresentRender(), and KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::PresentRender().
m_dispResetTimer
XbmcThreads::EndTime KODI::WINDOWING::GBM::CWinSystemGbm::m_dispResetTimer protected
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmGLContext::PresentRender(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::PresentRender(), and SetFullScreen().
m_DRM
std::shared_ptr<CDRMUtils> KODI::WINDOWING::GBM::CWinSystemGbm::m_DRM protected
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::CreateNewWindow(), DisplayHardwareScalingEnabled(), FlipPage(), GetConnectedOutputs(), GetDrm(), Hide(), InitWindowSystem(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::InitWindowSystem(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::InitWindowSystem(), KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::InitWindowSystemEGL(), IsHDRDisplay(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::PresentRender(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::PresentRender(), SetFullScreen(), SetHDR(), Show(), and UpdateResolutions().
m_GBM
std::unique_ptr<CGBMUtils> KODI::WINDOWING::GBM::CWinSystemGbm::m_GBM protected
Referenced by KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::CreateNewWindow(), FlipPage(), GetGBMDevice(), InitWindowSystem(), KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::InitWindowSystemEGL(), and SetFullScreen().
m_hdr_blob_id
uint32_t KODI::WINDOWING::GBM::CWinSystemGbm::m_hdr_blob_id = 0 private
Referenced by SetHDR().
m_info
std::unique_ptr<UTILS::CDisplayInfo> KODI::WINDOWING::GBM::CWinSystemGbm::m_info private
Referenced by GetDisplayHDRCapabilities(), InitWindowSystem(), IsHDRDisplay(), and SetHDR().
m_libinput
std::unique_ptr<CLibInputHandler> KODI::WINDOWING::GBM::CWinSystemGbm::m_libinput protected
Referenced by CWinSystemGbm(), and DestroyWindowSystem().
m_resources
std::vector<IDispResource*> KODI::WINDOWING::GBM::CWinSystemGbm::m_resources protected
Referenced by OnLostDevice(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::PresentRender(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::PresentRender(), Register(), and Unregister().
m_resourceSection
CCriticalSection KODI::WINDOWING::GBM::CWinSystemGbm::m_resourceSection protected
Referenced by OnLostDevice(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::PresentRender(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::PresentRender(), Register(), and Unregister().
m_videoLayerBridge
std::shared_ptr<CVideoLayerBridge> KODI::WINDOWING::GBM::CWinSystemGbm::m_videoLayerBridge protected
Referenced by FlipPage(), GetVideoLayerBridge(), and RegisterVideoLayerBridge().
The documentation for this class was generated from the following files:
WinSystemGbm.h
WinSystemGbm.cpp