Kodi Documentation: kodi::addon::CInstanceVisualization Class Reference
kodi::addon::CInstanceVisualization Class Reference
#include <Visualization.h>
Public Member Functions
CInstanceVisualization ()
Visualization class constructor.
CInstanceVisualization (const IInstanceInfo &instance)
Visualization class constructor used to support multiple instance types.
~CInstanceVisualization () override=default
Destructor.
virtual bool Start (int channels, int samplesPerSec, int bitsPerSample, const std::string &songName)
Used to notify the visualization that a new song has been started.
virtual void Stop ()
Used to inform the visualization that the rendering control was stopped.
virtual void AudioData (const float *audioData, size_t audioDataLength)
Pass audio data to the visualization.
virtual bool IsDirty ()
Used to inform Kodi that the rendered region is dirty and need an update.
virtual void Render ()
Used to indicate when the add-on should render.
virtual int GetSyncDelay ()
Used to get the number of buffers from the current visualization.
virtual bool GetPresets (std::vector< std::string > &presets)
Used to get a list of visualization presets the user can select. from.
virtual int GetActivePreset ()
Get the index of the current preset.
virtual bool IsLocked ()
Check if the add-on is locked to the current preset.
virtual bool PrevPreset ()
Load the previous visualization preset.
virtual bool NextPreset ()
Load the next visualization preset.
virtual bool LoadPreset (int select)
Load a visualization preset.
virtual bool RandomPreset ()
Switch to a new random preset.
virtual bool LockPreset (bool lockUnlock)
Lock the current visualization preset, preventing it from changing.
virtual bool RatePreset (bool plusMinus)
Used to increase/decrease the visualization preset rating.
virtual bool UpdateAlbumart (const std::string &albumart)
Inform the visualization of the current album art image.
virtual bool UpdateTrack (const kodi::addon::VisualizationTrack &track)
Inform the visualization of the current track's tag information.
void TransferPresets (const std::vector< std::string > &presets)
To transfer available presets on addon.
kodi::HardwareContext Device ()
Device that represents the display adapter.
int X ()
Returns the X position of the rendering window.
int Y ()
Returns the Y position of the rendering window.
int Width ()
Returns the width of the rendering window.
int Height ()
Returns the height of the rendering window.
float PixelRatio ()
Pixel aspect ratio (often abbreviated PAR) is a ratio that describes how the width of a pixel compares to the height of that pixel.
Public Member Functions inherited from kodi::addon::IAddonInstance
IAddonInstance (const kodi::addon::IInstanceInfo &instance)
virtual ~IAddonInstance ()=default
virtual ADDON_STATUS CreateInstance (const kodi::addon::IInstanceInfo &instance, KODI_ADDON_INSTANCE_HDL &hdl)
std::string GetInstanceAPIVersion () const
virtual ADDON_STATUS SetInstanceSetting (const std::string &settingName, const kodi::addon::CSettingValue &settingValue)
bool IsInstanceSettingUsingDefault (const std::string &settingName)
std::string GetInstanceUserPath (const std::string &append="")
bool CheckInstanceSettingString (const std::string &settingName, std::string &settingValue)
std::string GetInstanceSettingString (const std::string &settingName, const std::string &defaultValue="")
void SetInstanceSettingString (const std::string &settingName, const std::string &settingValue)
bool CheckInstanceSettingInt (const std::string &settingName, int &settingValue)
int GetInstanceSettingInt (const std::string &settingName, int defaultValue=0)
void SetInstanceSettingInt (const std::string &settingName, int settingValue)
bool CheckInstanceSettingBoolean (const std::string &settingName, bool &settingValue)
bool GetInstanceSettingBoolean (const std::string &settingName, bool defaultValue=false)
void SetInstanceSettingBoolean (const std::string &settingName, bool settingValue)
bool CheckInstanceSettingFloat (const std::string &settingName, float &settingValue)
float GetInstanceSettingFloat (const std::string &settingName, float defaultValue=0.0f)
void SetInstanceSettingFloat (const std::string &settingName, float settingValue)
template<typename enumType >
bool CheckInstanceSettingEnum (const std::string &settingName, enumType &settingValue)
template<typename enumType >
enumType GetInstanceSettingEnum (const std::string &settingName, enumType defaultValue=static_cast< enumType >(0))
template<typename enumType >
void SetInstanceSettingEnum (const std::string &settingName, enumType settingValue)
Private Member Functions
void SetAddonStruct (KODI_ADDON_INSTANCE_STRUCT *instance)
Static Private Member Functions
static bool ADDON_start (const KODI_ADDON_VISUALIZATION_HDL hdl, int channels, int samplesPerSec, int bitsPerSample, const char *songName)
static void ADDON_stop (const KODI_ADDON_VISUALIZATION_HDL hdl)
static void ADDON_audio_data (const KODI_ADDON_VISUALIZATION_HDL hdl, const float *audioData, size_t audioDataLength)
static bool ADDON_is_dirty (const KODI_ADDON_VISUALIZATION_HDL hdl)
static void ADDON_render (const KODI_ADDON_VISUALIZATION_HDL hdl)
static int ADDON_get_sync_delay (const KODI_ADDON_VISUALIZATION_HDL hdl)
static unsigned int ADDON_get_presets (const KODI_ADDON_VISUALIZATION_HDL hdl)
static int ADDON_get_active_preset (const KODI_ADDON_VISUALIZATION_HDL hdl)
static bool ADDON_prev_preset (const KODI_ADDON_VISUALIZATION_HDL hdl)
static bool ADDON_next_preset (const KODI_ADDON_VISUALIZATION_HDL hdl)
static bool ADDON_load_preset (const KODI_ADDON_VISUALIZATION_HDL hdl, int select)
static bool ADDON_random_preset (const KODI_ADDON_VISUALIZATION_HDL hdl)
static bool ADDON_lock_preset (const KODI_ADDON_VISUALIZATION_HDL hdl)
static bool ADDON_rate_preset (const KODI_ADDON_VISUALIZATION_HDL hdl, bool plus_minus)
static bool ADDON_is_locked (const KODI_ADDON_VISUALIZATION_HDL hdl)
static bool ADDON_update_albumart (const KODI_ADDON_VISUALIZATION_HDL hdl, const char *albumart)
static bool ADDON_update_track (const KODI_ADDON_VISUALIZATION_HDL hdl, const KODI_ADDON_VISUALIZATION_TRACK *track)
Private Attributes
std::shared_ptr< kodi::gui::IRenderHelper > m_renderHelper
bool m_presetLockedByUser = false
KODI_ADDON_INSTANCE_STRUCT * m_instanceData {nullptr}
KODI_ADDON_VISUALIZATION_PROPS m_props = {}
Member Function Documentation
ADDON_audio_data()
static void kodi::addon::CInstanceVisualization::ADDON_audio_data (const KODI_ADDON_VISUALIZATION_HDL hdl, const float * audioData, size_t audioDataLength) inline static private
ADDON_get_active_preset()
static int kodi::addon::CInstanceVisualization::ADDON_get_active_preset (const KODI_ADDON_VISUALIZATION_HDL hdl) inline static private
ADDON_get_presets()
static unsigned int kodi::addon::CInstanceVisualization::ADDON_get_presets (const KODI_ADDON_VISUALIZATION_HDL hdl) inline static private
References GetPresets(), KODI_ADDON_INSTANCE_STRUCT::info, KODI_ADDON_INSTANCE_INFO::kodi, m_instanceData, AddonInstance_Visualization::toKodi, AddonToKodiFuncTable_Visualization::transfer_preset, and KODI_ADDON_INSTANCE_STRUCT::visualization.
ADDON_get_sync_delay()
static int kodi::addon::CInstanceVisualization::ADDON_get_sync_delay (const KODI_ADDON_VISUALIZATION_HDL hdl) inline static private
ADDON_is_dirty()
static bool kodi::addon::CInstanceVisualization::ADDON_is_dirty (const KODI_ADDON_VISUALIZATION_HDL hdl) inline static private
ADDON_is_locked()
static bool kodi::addon::CInstanceVisualization::ADDON_is_locked (const KODI_ADDON_VISUALIZATION_HDL hdl) inline static private
ADDON_load_preset()
static bool kodi::addon::CInstanceVisualization::ADDON_load_preset (const KODI_ADDON_VISUALIZATION_HDL hdl, int select) inline static private
ADDON_lock_preset()
static bool kodi::addon::CInstanceVisualization::ADDON_lock_preset (const KODI_ADDON_VISUALIZATION_HDL hdl) inline static private
References LockPreset(), and m_presetLockedByUser.
ADDON_next_preset()
static bool kodi::addon::CInstanceVisualization::ADDON_next_preset (const KODI_ADDON_VISUALIZATION_HDL hdl) inline static private
ADDON_prev_preset()
static bool kodi::addon::CInstanceVisualization::ADDON_prev_preset (const KODI_ADDON_VISUALIZATION_HDL hdl) inline static private
ADDON_random_preset()
static bool kodi::addon::CInstanceVisualization::ADDON_random_preset (const KODI_ADDON_VISUALIZATION_HDL hdl) inline static private
ADDON_rate_preset()
static bool kodi::addon::CInstanceVisualization::ADDON_rate_preset (const KODI_ADDON_VISUALIZATION_HDL hdl, bool plus_minus) inline static private
ADDON_render()
static void kodi::addon::CInstanceVisualization::ADDON_render (const KODI_ADDON_VISUALIZATION_HDL hdl) inline static private
References m_renderHelper, and Render().
ADDON_start()
static bool kodi::addon::CInstanceVisualization::ADDON_start (const KODI_ADDON_VISUALIZATION_HDL hdl, int channels, int samplesPerSec, int bitsPerSample, const char * songName) inline static private
References kodi::gui::GetRenderHelper(), m_renderHelper, and Start().
ADDON_stop()
static void kodi::addon::CInstanceVisualization::ADDON_stop (const KODI_ADDON_VISUALIZATION_HDL hdl) inline static private
References m_renderHelper, and Stop().
ADDON_update_albumart()
static bool kodi::addon::CInstanceVisualization::ADDON_update_albumart (const KODI_ADDON_VISUALIZATION_HDL hdl, const char * albumart) inline static private
ADDON_update_track()
static bool kodi::addon::CInstanceVisualization::ADDON_update_track (const KODI_ADDON_VISUALIZATION_HDL hdl, const KODI_ADDON_VISUALIZATION_TRACK * track) inline static private
SetAddonStruct()
void kodi::addon::CInstanceVisualization::SetAddonStruct (KODI_ADDON_INSTANCE_STRUCT * instance) inline private
References KODI_ADDON_INSTANCE_STRUCT::hdl, KODI_ADDON_INSTANCE_STRUCT::info, and KODI_ADDON_INSTANCE_INFO::kodi.
Member Data Documentation
m_instanceData
KODI_ADDON_INSTANCE_STRUCT* kodi::addon::CInstanceVisualization::m_instanceData {nullptr} private
Referenced by ADDON_get_presets().
m_presetLockedByUser
bool kodi::addon::CInstanceVisualization::m_presetLockedByUser = false private
Referenced by ADDON_lock_preset().
m_props
KODI_ADDON_VISUALIZATION_PROPS kodi::addon::CInstanceVisualization::m_props = {} private
m_renderHelper
std::shared_ptr<kodi::gui::IRenderHelper> kodi::addon::CInstanceVisualization::m_renderHelper private
Referenced by ADDON_render(), ADDON_start(), and ADDON_stop().
The documentation for this class was generated from the following file:
kodi-dev-kit/include/kodi/addon-instance/Visualization.h