Kodi Documentation: ADDON::CScraperError Class Reference
ADDON::CScraperError Class Reference
#include <Scraper.h>
Public Member Functions
CScraperError ()=default
CScraperError (const std::string &sTitle, const std::string &sMessage)
bool FAborted () const
const std::string & Title () const
const std::string & Message () const
Private Attributes
bool m_fAborted = true
std::string m_sTitle
std::string m_sMessage
Constructor & Destructor Documentation
CScraperError() [1/2]
ADDON::CScraperError::CScraperError () default
CScraperError() [2/2]
ADDON::CScraperError::CScraperError (const std::string & sTitle, const std::string & sMessage) inline
Member Function Documentation
FAborted()
bool ADDON::CScraperError::FAborted () const inline
References m_fAborted.
Referenced by CVideoInfoDownloader::InternalFindMovie(), MUSIC_INFO::CMusicInfoScanner::ResolveMusicBrainz(), ADDON::CScraper::RunNoThrow(), and CNfoFile::Scrape().
Message()
const std::string & ADDON::CScraperError::Message () const inline
References m_sMessage.
Referenced by CVideoInfoDownloader::ShowErrorDialog().
Title()
const std::string & ADDON::CScraperError::Title () const inline
References m_sTitle.
Referenced by CVideoInfoDownloader::ShowErrorDialog().
Member Data Documentation
m_fAborted
bool ADDON::CScraperError::m_fAborted = true private
Referenced by FAborted().
m_sMessage
std::string ADDON::CScraperError::m_sMessage private
Referenced by Message().
m_sTitle
std::string ADDON::CScraperError::m_sTitle private
Referenced by Title().
The documentation for this class was generated from the following file:
Scraper.h