Kodi Documentation: CVideoLibraryCleaningJob Class Reference
CVideoLibraryCleaningJob Class Reference
Video library job implementation for cleaning the video library.
#include <VideoLibraryCleaningJob.h>
Public Member Functions
CVideoLibraryCleaningJob (const std::set< int > &paths=std::set< int >(), bool showDialog=false)
Creates a new video library cleaning job for the given paths.
CVideoLibraryCleaningJob (const std::set< int > &paths, CGUIDialogProgressBarHandle *progressBar)
Creates a new video library cleaning job for the given paths.
~CVideoLibraryCleaningJob () override
const char * GetType () const override
Function that returns the type of job.
bool operator== (const CJob *job) const override
Public Member Functions inherited from CVideoLibraryProgressJob
~CVideoLibraryProgressJob () override
bool DoWork () override
Main workhorse function of CJob instances.
const char * GetType () const override
Function that returns the type of job.
bool operator== (const CJob *job) const override
Public Member Functions inherited from CProgressJob
~CProgressJob () override
bool ShouldCancel (unsigned int progress, unsigned int total) const override
Function for longer jobs to report progress and check whether they have been cancelled.
bool DoModal ()
Executes the job showing a modal progress dialog.
void SetProgressIndicators (CGUIDialogProgressBarHandle *progressBar, CGUIDialogProgress *progressDialog, bool updateProgress=true, bool updateInformation=true)
Sets the given progress indicators to be used during execution of the job.
bool HasProgressIndicator () const
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
Public Member Functions inherited from CVideoLibraryJob
~CVideoLibraryJob () override
virtual bool CanBeCancelled () const
Whether the job can be cancelled or not.
virtual bool Cancel ()
Tries to cancel the running job.
Protected Member Functions
bool Work (CVideoDatabase &db) override
Worker method to be implemented by an actual implementation.
Protected Member Functions inherited from CVideoLibraryProgressJob
CVideoLibraryProgressJob (CGUIDialogProgressBarHandle *progressBar)
Protected Member Functions inherited from CProgressJob
CProgressJob ()
CProgressJob (CGUIDialogProgressBarHandle *progressBar)
bool IsModal () const
Whether the job is being run modally or in the background.
CGUIDialogProgressBarHandle * GetProgressBar () const
Returns the progress bar indicating the progress of the job.
void SetProgressBar (CGUIDialogProgressBarHandle *progress)
Sets the progress bar indicating the progress of the job.
CGUIDialogProgress * GetProgressDialog () const
Returns the progress dialog indicating the progress of the job.
void SetProgressDialog (CGUIDialogProgress *progressDialog)
Sets the progress bar indicating the progress of the job.
bool GetAutoClose ()
Whether to automatically close the progress indicator in MarkFinished().
void SetAutoClose (bool autoClose)
Set whether to automatically close the progress indicator in MarkFinished().
bool GetUpdateProgress ()
Whether to update the progress bar or not.
void SetUpdateProgress (bool updateProgress)
Set whether to update the progress bar or not.
bool GetUpdateInformation ()
Whether to update the progress information or not.
void SetUpdateInformation (bool updateInformation)
Set whether to update the progress information or not.
void ShowProgressDialog () const
Makes sure that the modal dialog is being shown.
void SetTitle (const std::string &title)
Sets the given title as the title of the progress bar.
void SetText (const std::string &text)
Sets the given text as the description of the progress bar.
void SetProgress (float percentage) const
Sets the progress of the progress bar to the given value in percentage.
void SetProgress (int currentStep, int totalSteps) const
Sets the progress of the progress bar to the given value.
void MarkFinished ()
Marks the progress as finished by setting it to 100%.
bool IsCancelled () const
Checks if the progress dialog has been cancelled.
Protected Member Functions inherited from CVideoLibraryJob
CVideoLibraryJob ()
Private Attributes
std::set< int > m_paths
bool m_showDialog
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Detailed Description
Video library job implementation for cleaning the video library.
Constructor & Destructor Documentation
CVideoLibraryCleaningJob() [1/2]
CVideoLibraryCleaningJob::CVideoLibraryCleaningJob (const std::set< int > & paths = std::set<int>(), bool showDialog = false)
Creates a new video library cleaning job for the given paths.
Parameters
[in] paths Set with database IDs of paths to be cleaned
[in] showDialog Whether to show a modal dialog or not
CVideoLibraryCleaningJob() [2/2]
CVideoLibraryCleaningJob::CVideoLibraryCleaningJob (const std::set< int > & paths, CGUIDialogProgressBarHandle * progressBar)
Creates a new video library cleaning job for the given paths.
Parameters
[in] paths Set with database IDs of paths to be cleaned
[in] progressBar Progress bar to be used to display the cleaning progress
~CVideoLibraryCleaningJob()
CVideoLibraryCleaningJob::~CVideoLibraryCleaningJob () override default
Member Function Documentation
GetType()
const char * CVideoLibraryCleaningJob::GetType () const inline override virtual
Function that returns the type of job.
CJob subclasses may optionally implement this function to specify the type of job. This is useful for the CJobManager::AddLIFOJob() routine, which preempts similar jobs with the new job.
Returns
a unique character string describing the job.
See also
CJobManager
Reimplemented from CProgressJob.
Referenced by operator==().
operator==()
bool CVideoLibraryCleaningJob::operator== (const CJob * job) const override virtual
Reimplemented from CProgressJob.
References CJob::GetType(), GetType(), m_paths, and m_showDialog.
Work()
bool CVideoLibraryCleaningJob::Work (CVideoDatabase & db) override protected virtual
Worker method to be implemented by an actual implementation.
Parameters
[in] db Already open video database to be used for interaction
Returns
True if the process succeeded, false otherwise
Implements CVideoLibraryJob.
References CVideoDatabase::CleanDatabase(), CProgressJob::GetProgressBar(), m_paths, and m_showDialog.
Member Data Documentation
m_paths
std::set<int> CVideoLibraryCleaningJob::m_paths private
Referenced by operator==(), and Work().
m_showDialog
bool CVideoLibraryCleaningJob::m_showDialog private
Referenced by operator==(), and Work().
The documentation for this class was generated from the following files:
VideoLibraryCleaningJob.h
VideoLibraryCleaningJob.cpp