Kodi Documentation: ProfileBuiltins.cpp File Reference
ProfileBuiltins.cpp File Reference
#include "ProfileBuiltins.h"
#include "GUIPassword.h"
#include "GUIUserMessages.h"
#include "ServiceBroker.h"
#include "Util.h"
#include "dialogs/GUIDialogKaiToast.h"
#include "favourites/FavouritesService.h"
#include "guilib/GUIComponent.h"
#include "guilib/GUIWindowManager.h"
#include "guilib/LocalizeStrings.h"
#include "messaging/ApplicationMessenger.h"
#include "profiles/ProfileManager.h"
#include "settings/SettingsComponent.h"
#include "utils/StringUtils.h"
Functions
static int LoadProfile (const std::vector< std::string > &params)
Load a profile.
static int LogOff (const std::vector< std::string > &params)
Log off currently signed in profile.
static int MasterMode (const std::vector< std::string > &params)
Toggle master mode.
Function Documentation
LoadProfile()
static int LoadProfile (const std::vector< std::string > & params) static
Load a profile.
Parameters
params The parameters.
params[0] = The profile name. params[1] = "prompt" to allow unlocking dialogs (optional)
References KODI::UTILS::StringUtils::EqualsNoCase(), g_passwordManager, CServiceBroker::GetAppMessenger(), CServiceBroker::GetSettingsComponent(), index(), CGUIPassword::IsProfileLockUnlocked(), LOCK_MODE_EVERYONE, and TMSG_LOADPROFILE.
Referenced by CProfileBuiltins::GetOperations().
LogOff()
static int LogOff (const std::vector< std::string > & params) static
Log off currently signed in profile.
Parameters
params (ignored)
References CServiceBroker::GetSettingsComponent().
Referenced by CProfileBuiltins::GetOperations().
MasterMode()
static int MasterMode (const std::vector< std::string > & params) static
Toggle master mode.
Parameters
params (ignored)
References CGUIPassword::bMasterUser, CUtil::DeleteVideoDatabaseDirectoryCache(), g_localizeStrings, g_passwordManager, CLocalizeStrings::Get(), CServiceBroker::GetFavouritesService(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE, CGUIPassword::IsMasterLockUnlocked(), CGUIPassword::LockSources(), CGUIDialogKaiToast::QueueNotification(), CFavouritesService::RefreshFavourites(), CGUIWindowManager::SendMessage(), and CGUIDialogKaiToast::Warning.
Referenced by CProfileBuiltins::GetOperations().