Kodi Documentation: CONTEXTMENU::CVideoRemoveResumePoint Struct Reference
CONTEXTMENU::CVideoRemoveResumePoint Struct Reference
#include <ContextMenus.h>
Public Member Functions
CVideoRemoveResumePoint ()
bool IsVisible (const CFileItem &item) const override
bool Execute (const std::shared_ptr< CFileItem > &item) const override
Public Member Functions inherited from CStaticContextMenuAction
CStaticContextMenuAction (uint32_t label)
std::string GetLabel (const CFileItem &item) const final
bool IsGroup () const final
Public Member Functions inherited from IContextMenuItem
virtual ~IContextMenuItem ()=default
virtual bool HasParent () const
Constructor & Destructor Documentation
CVideoRemoveResumePoint()
CONTEXTMENU::CVideoRemoveResumePoint::CVideoRemoveResumePoint () inline
Member Function Documentation
Execute()
bool CONTEXTMENU::CVideoRemoveResumePoint::Execute (const std::shared_ptr< CFileItem > & item) const override virtual
Implements IContextMenuItem.
References CVideoLibraryQueue::GetInstance(), and CVideoLibraryQueue::ResetResumePoint().
IsVisible()
bool CONTEXTMENU::CVideoRemoveResumePoint::IsVisible (const CFileItem & item) const override virtual
Implements IContextMenuItem.
References KODI::VIDEO::UTILS::GetItemResumeInformation(), CFileItem::GetItemToPlay(), CFileItem::IsDeleted(), KODI::VIDEO::UTILS::ResumeInformation::isResumable, and CGUIListItem::m_bIsFolder.
The documentation for this struct was generated from the following files:
video/ContextMenus.h
video/ContextMenus.cpp