Kodi Documentation: Setting.cpp File Reference
Setting.cpp File Reference
#include "Setting.h"
#include "ServiceBroker.h"
#include "SettingDefinitions.h"
#include "SettingsManager.h"
#include "utils/StringUtils.h"
#include "utils/XBMCTinyXML.h"
#include "utils/XMLUtils.h"
#include "utils/log.h"
#include <mutex>
#include <shared_mutex>
#include <sstream>
#include <utility>
Functions
template<typename TKey , typename TValue >
bool CheckSettingOptionsValidity (const TValue &value, const std::vector< std::pair< TKey, TValue > > &options)
template<typename TKey , typename TValue >
bool CheckSettingOptionsValidity (const TValue &value, const std::vector< TKey > &options)
bool DeserializeOptionsSort (const TiXmlElement *optionsElement, SettingOptionsSort &optionsSort)
Function Documentation
CheckSettingOptionsValidity() [1/2]
template<typename TKey , typename TValue > bool CheckSettingOptionsValidity (const TValue & value, const std::vector< std::pair< TKey, TValue > > & options)
References value.
Referenced by CSettingString::CheckValidity(), and CSettingInt::CheckValidity().
CheckSettingOptionsValidity() [2/2]
template<typename TKey , typename TValue > bool CheckSettingOptionsValidity (const TValue & value, const std::vector< TKey > & options)
References value.
DeserializeOptionsSort()
bool DeserializeOptionsSort (const TiXmlElement * optionsElement, SettingOptionsSort & optionsSort)
References Ascending, Descending, KODI::UTILS::StringUtils::EqualsNoCase(), and NoSorting.
Referenced by CSettingInt::Deserialize(), and CSettingString::Deserialize().