Kodi Documentation: CNetworkWin10 Class Reference
CNetworkWin10 Class Reference
#include <NetworkWin10.h>
Public Member Functions
CNetworkWin10 ()
virtual ~CNetworkWin10 (void)
std::vector< CNetworkInterface * > & GetInterfaceList (void) override
CNetworkInterface * GetFirstConnectedInterface () override
std::vector< std::string > GetNameServers (void) override
bool PingHost (unsigned long host, unsigned int timeout_ms=2000) override
Public Member Functions inherited from CNetworkBase
CNetworkBase ()
virtual ~CNetworkBase ()
CNetworkServices & GetServices ()
virtual bool GetHostName (std::string &hostname)
bool HasInterfaceForIP (unsigned long address)
bool IsAvailable (void)
bool IsConnected (void)
bool WakeOnLan (const char *mac)
bool PingHost (unsigned long host, unsigned short port, unsigned int timeout_ms=2000, bool readability_check=false)
void NetworkMessage (EMESSAGE message, int param)
bool IsLocalHost (const std::string &hostname)
void WaitForNet ()
Private Member Functions
int GetSocket ()
void queryInterfaceList ()
void CleanInterfaceList ()
Private Attributes
std::vector< CNetworkInterface * > m_interfaces
int m_sock
CCriticalSection m_critSection
std::vector< uint8_t > m_adapterAddresses
Friends
class CNetworkInterfaceWin10
Additional Inherited Members
Public Types inherited from CNetworkBase
enum EMESSAGE { SERVICES_UP , SERVICES_DOWN }
Static Public Member Functions inherited from CNetworkBase
static std::unique_ptr< CNetworkBase > GetNetwork ()
static int ParseHex (char *str, unsigned char *addr)
static std::string GetIpStr (const sockaddr *sa)
IPv6/IPv4 compatible conversion of host IP address.
static std::string GetMaskByPrefixLength (uint8_t prefixLength)
convert prefix length of IPv4 address to IP mask representation
Public Attributes inherited from CNetworkBase
std::unique_ptr< CNetworkServices > m_services
Constructor & Destructor Documentation
CNetworkWin10()
CNetworkWin10::CNetworkWin10 ()
References m_critSection, and queryInterfaceList().
~CNetworkWin10()
CNetworkWin10::~CNetworkWin10 (void) virtual
References CleanInterfaceList().
Member Function Documentation
CleanInterfaceList()
void CNetworkWin10::CleanInterfaceList () private
References m_interfaces.
Referenced by queryInterfaceList(), and ~CNetworkWin10().
GetFirstConnectedInterface()
CNetworkInterface * CNetworkWin10::GetFirstConnectedInterface (void) override virtual
Reimplemented from CNetworkBase.
References CNetworkBase::GetFirstConnectedInterface(), m_critSection, and m_interfaces.
GetInterfaceList()
std::vector< CNetworkInterface * > & CNetworkWin10::GetInterfaceList (void) override virtual
Implements CNetworkBase.
References m_critSection, and m_interfaces.
GetNameServers()
std::vector< std::string > CNetworkWin10::GetNameServers (void) override virtual
Implements CNetworkBase.
GetSocket()
int CNetworkWin10::GetSocket () inline private
References m_sock.
PingHost()
bool CNetworkWin10::PingHost (unsigned long host, unsigned int timeout_ms = 2000) override virtual
Implements CNetworkBase.
References GetLastError(), IP_REQ_TIMED_OUT, IP_SUCCESS, LOGERROR, SetLastError(), icmp_echo_reply::Status, and CWIN32Util::WUSysMsg().
queryInterfaceList()
void CNetworkWin10::queryInterfaceList () private
References CleanInterfaceList(), CNetworkInterfaceWin10, m_adapterAddresses, and m_interfaces.
Referenced by CNetworkWin10().
Friends And Related Symbol Documentation
CNetworkInterfaceWin10
friend class CNetworkInterfaceWin10 friend
Referenced by queryInterfaceList().
Member Data Documentation
m_adapterAddresses
std::vector<uint8_t> CNetworkWin10::m_adapterAddresses private
Referenced by queryInterfaceList().
m_critSection
CCriticalSection CNetworkWin10::m_critSection private
Referenced by CNetworkWin10(), GetFirstConnectedInterface(), and GetInterfaceList().
m_interfaces
std::vector<CNetworkInterface*> CNetworkWin10::m_interfaces private
Referenced by CleanInterfaceList(), GetFirstConnectedInterface(), GetInterfaceList(), and queryInterfaceList().
m_sock
int CNetworkWin10::m_sock private
Referenced by GetSocket().
The documentation for this class was generated from the following files:
NetworkWin10.h
NetworkWin10.cpp