Kodi Documentation: KODI::WINDOWING::WAYLAND::CSeat Class Reference
KODI::WINDOWING::WAYLAND::CSeat Class Reference
#include <Seat.h>
Public Member Functions
CSeat (std::uint32_t globalName, wayland::seat_t const &seat, CConnection &connection)
virtual ~CSeat () noexcept
void AddRawInputHandlerKeyboard (IRawInputHandlerKeyboard *rawKeyboardHandler)
void RemoveRawInputHandlerKeyboard (IRawInputHandlerKeyboard *rawKeyboardHandler)
void AddRawInputHandlerPointer (IRawInputHandlerPointer *rawPointerHandler)
void RemoveRawInputHandlerPointer (IRawInputHandlerPointer *rawPointerHandler)
void AddRawInputHandlerTouch (IRawInputHandlerTouch *rawTouchHandler)
void RemoveRawInputHandlerTouch (IRawInputHandlerTouch *rawTouchHandler)
std::uint32_t GetGlobalName () const
std::string const & GetName () const
bool HasPointerCapability () const
bool HasKeyboardCapability () const
bool HasTouchCapability () const
std::string GetSelectionText () const
wayland::seat_t const & GetWlSeat ()
virtual void SetCursor (std::uint32_t serial, wayland::surface_t const &surface, std::int32_t hotspotX, std::int32_t hotspotY)
Protected Member Functions
virtual void InstallKeyboardRepeatInfo ()
Private Member Functions
CSeat (CSeat const &other)=delete
CSeat & operator= (CSeat const &other)=delete
void HandleOnCapabilities (const wayland::seat_capability &caps)
void HandlePointerCapability ()
void HandleKeyboardCapability ()
void HandleTouchCapability ()
Private Attributes
std::uint32_t m_globalName
std::string m_name {"<unknown>"}
wayland::seat_t m_seat
wayland::pointer_t m_pointer
wayland::keyboard_t m_keyboard
wayland::touch_t m_touch
std::set< IRawInputHandlerKeyboard * > m_rawKeyboardHandlers
std::set< IRawInputHandlerPointer * > m_rawPointerHandlers
std::set< IRawInputHandlerTouch * > m_rawTouchHandlers
CSeatSelection m_selection
Detailed Description
Handle all events and requests related to one seat (including input and selection)
The primary purpose of this class is to act as entry point of Wayland events into the Kodi world and distribute them further as necessary. Input events are forwarded to (potentially multiple) handlers. As the Wayland protocol is not very specific on having multiple wl_seat/wl_pointer instances and how they interact, having one central instance and then handling everything in Kodi with multiple handlers is better than each handler having its own protocol object instance.
Constructor & Destructor Documentation
CSeat() [1/2]
CSeat::CSeat (std::uint32_t globalName, wayland::seat_t const & seat, CConnection & connection)
Construct seat handler
Parameters
globalName Wayland numeric global name of the seat
seat bound seat_t instance
connection connection for retrieving additional globals
References HandleOnCapabilities(), m_name, m_seat, and name.
~CSeat()
CSeat::~CSeat () virtual default noexcept
CSeat() [2/2]
KODI::WINDOWING::WAYLAND::CSeat::CSeat (CSeat const & other) private delete
Member Function Documentation
AddRawInputHandlerKeyboard()
void CSeat::AddRawInputHandlerKeyboard (IRawInputHandlerKeyboard * rawKeyboardHandler)
Referenced by KODI::WINDOWING::WAYLAND::CSeatInputProcessing::AddSeat().
AddRawInputHandlerPointer()
void CSeat::AddRawInputHandlerPointer (IRawInputHandlerPointer * rawPointerHandler)
References m_rawPointerHandlers.
Referenced by KODI::WINDOWING::WAYLAND::CSeatInputProcessing::AddSeat(), and KODI::WINDOWING::WAYLAND::CWindowDecorator::AddSeat().
AddRawInputHandlerTouch()
void CSeat::AddRawInputHandlerTouch (IRawInputHandlerTouch * rawTouchHandler)
References m_rawTouchHandlers.
Referenced by KODI::WINDOWING::WAYLAND::CSeatInputProcessing::AddSeat(), and KODI::WINDOWING::WAYLAND::CWindowDecorator::AddSeat().
GetGlobalName()
std::uint32_t KODI::WINDOWING::WAYLAND::CSeat::GetGlobalName () const inline
References m_globalName.
Referenced by KODI::WINDOWING::WAYLAND::CSeatInputProcessing::AddSeat(), KODI::WINDOWING::WAYLAND::CWindowDecorator::AddSeat(), KODI::WINDOWING::WAYLAND::CWindowDecorator::OnPointerButton(), KODI::WINDOWING::WAYLAND::CInputProcessorPointer::OnPointerEnter(), KODI::WINDOWING::WAYLAND::CWindowDecorator::OnPointerEnter(), KODI::WINDOWING::WAYLAND::CWindowDecorator::OnPointerLeave(), KODI::WINDOWING::WAYLAND::CWindowDecorator::OnPointerMotion(), KODI::WINDOWING::WAYLAND::CWindowDecorator::OnTouchDown(), KODI::WINDOWING::WAYLAND::CSeatInputProcessing::RemoveSeat(), and KODI::WINDOWING::WAYLAND::CWindowDecorator::RemoveSeat().
GetName()
std::string const & KODI::WINDOWING::WAYLAND::CSeat::GetName () const inline
References m_name.
Referenced by HandleOnCapabilities().
GetSelectionText()
std::string KODI::WINDOWING::WAYLAND::CSeat::GetSelectionText () const inline
References KODI::WINDOWING::WAYLAND::CSeatSelection::GetSelectionText(), and m_selection.
GetWlSeat()
wayland::seat_t const & KODI::WINDOWING::WAYLAND::CSeat::GetWlSeat () inline
Get the wl_seat underlying this seat
The wl_seat should only be used when strictly necessary, e.g. when starting a move operation with shell interfaces. It may not be used to derive further wl_pointer etc. instances.
References m_seat.
Referenced by KODI::WINDOWING::WAYLAND::CWindowDecorator::HandleSeatClick().
HandleKeyboardCapability()
void CSeat::HandleKeyboardCapability () private
References InstallKeyboardRepeatInfo(), m_keyboard, and m_rawKeyboardHandlers.
Referenced by HandleOnCapabilities().
HandleOnCapabilities()
void CSeat::HandleOnCapabilities (const wayland::seat_capability & caps) private
References GetName(), HandleKeyboardCapability(), HandlePointerCapability(), HandleTouchCapability(), m_keyboard, m_pointer, m_seat, and m_touch.
Referenced by CSeat().
HandlePointerCapability()
void CSeat::HandlePointerCapability () private
References m_pointer, m_rawPointerHandlers, and value.
Referenced by HandleOnCapabilities().
HandleTouchCapability()
void CSeat::HandleTouchCapability () private
References id, m_rawTouchHandlers, and m_touch.
Referenced by HandleOnCapabilities().
HasKeyboardCapability()
bool KODI::WINDOWING::WAYLAND::CSeat::HasKeyboardCapability () const inline
References m_keyboard.
HasPointerCapability()
bool KODI::WINDOWING::WAYLAND::CSeat::HasPointerCapability () const inline
References m_pointer.
HasTouchCapability()
bool KODI::WINDOWING::WAYLAND::CSeat::HasTouchCapability () const inline
References m_touch.
InstallKeyboardRepeatInfo()
void CSeat::InstallKeyboardRepeatInfo () protected virtual
Reimplemented in KODI::WINDOWING::WAYLAND::CSeatWebOS.
References m_keyboard, and m_rawKeyboardHandlers.
Referenced by HandleKeyboardCapability().
operator=()
CSeat & KODI::WINDOWING::WAYLAND::CSeat::operator= (CSeat const & other) private delete
RemoveRawInputHandlerKeyboard()
void CSeat::RemoveRawInputHandlerKeyboard (IRawInputHandlerKeyboard * rawKeyboardHandler)
References m_rawKeyboardHandlers.
Referenced by KODI::WINDOWING::WAYLAND::CSeatInputProcessing::RemoveSeat().
RemoveRawInputHandlerPointer()
void CSeat::RemoveRawInputHandlerPointer (IRawInputHandlerPointer * rawPointerHandler)
References m_rawPointerHandlers.
Referenced by KODI::WINDOWING::WAYLAND::CSeatInputProcessing::RemoveSeat(), and KODI::WINDOWING::WAYLAND::CWindowDecorator::RemoveSeat().
RemoveRawInputHandlerTouch()
void CSeat::RemoveRawInputHandlerTouch (IRawInputHandlerTouch * rawTouchHandler)
References m_rawTouchHandlers.
Referenced by KODI::WINDOWING::WAYLAND::CSeatInputProcessing::RemoveSeat(), and KODI::WINDOWING::WAYLAND::CWindowDecorator::RemoveSeat().
SetCursor()
void CSeat::SetCursor (std::uint32_t serial, wayland::surface_t const & surface, std::int32_t hotspotX, std::int32_t hotspotY) virtual
Set the cursor of the pointer of this seat
Parameters are identical wo wl_pointer.set_cursor(). If the seat does not currently have the pointer capability, this is a no-op.
Reimplemented in KODI::WINDOWING::WAYLAND::CSeatWebOS.
References m_pointer.
Referenced by KODI::WINDOWING::WAYLAND::CWindowDecorator::UpdateSeatCursor().
Member Data Documentation
m_globalName
std::uint32_t KODI::WINDOWING::WAYLAND::CSeat::m_globalName private
Referenced by GetGlobalName().
m_keyboard
wayland::keyboard_t KODI::WINDOWING::WAYLAND::CSeat::m_keyboard private
Referenced by HandleKeyboardCapability(), HandleOnCapabilities(), HasKeyboardCapability(), and InstallKeyboardRepeatInfo().
m_name
std::string KODI::WINDOWING::WAYLAND::CSeat::m_name {"<unknown>"} private
Referenced by CSeat(), and GetName().
m_pointer
wayland::pointer_t KODI::WINDOWING::WAYLAND::CSeat::m_pointer private
Referenced by HandleOnCapabilities(), HandlePointerCapability(), HasPointerCapability(), and SetCursor().
m_rawKeyboardHandlers
std::set<IRawInputHandlerKeyboard*> KODI::WINDOWING::WAYLAND::CSeat::m_rawKeyboardHandlers private
Referenced by HandleKeyboardCapability(), InstallKeyboardRepeatInfo(), and RemoveRawInputHandlerKeyboard().
m_rawPointerHandlers
std::set<IRawInputHandlerPointer*> KODI::WINDOWING::WAYLAND::CSeat::m_rawPointerHandlers private
Referenced by AddRawInputHandlerPointer(), HandlePointerCapability(), and RemoveRawInputHandlerPointer().
m_rawTouchHandlers
std::set<IRawInputHandlerTouch*> KODI::WINDOWING::WAYLAND::CSeat::m_rawTouchHandlers private
Referenced by AddRawInputHandlerTouch(), HandleTouchCapability(), and RemoveRawInputHandlerTouch().
m_seat
wayland::seat_t KODI::WINDOWING::WAYLAND::CSeat::m_seat private
Referenced by CSeat(), GetWlSeat(), and HandleOnCapabilities().
m_selection
CSeatSelection KODI::WINDOWING::WAYLAND::CSeat::m_selection private
Referenced by GetSelectionText().
m_touch
wayland::touch_t KODI::WINDOWING::WAYLAND::CSeat::m_touch private
Referenced by HandleOnCapabilities(), HandleTouchCapability(), and HasTouchCapability().
The documentation for this class was generated from the following files:
Seat.h
Seat.cpp