Kodi Documentation: KODI::KEYMAP::CKeymapHandler Class Reference
KODI::KEYMAP::CKeymapHandler Class Reference
#include <KeymapHandler.h>
Public Member Functions
CKeymapHandler (ACTION::IActionListener *actionHandler, const IKeymap *keymap)
~CKeymapHandler () override=default
bool HotkeysPressed (const std::set< std::string > &keyNames) const override
Get the pressed state of the given keys.
std::string GetLastPressed () const override
Get the key name of the last button pressed.
void OnPress (const std::string &keyName) override
Called when a key has emitted an action after bring pressed.
std::string ControllerID () const override
The add-on ID of the game controller associated with this input handler.
bool HasFeature (const JOYSTICK::FeatureName &feature) const override
Return true if the input handler accepts the given feature.
bool AcceptsInput (const JOYSTICK::FeatureName &feature) const override
Return true if the input handler is currently accepting input for the given feature.
bool OnButtonPress (const JOYSTICK::FeatureName &feature, bool bPressed) override
A digital button has been pressed or released.
void OnButtonHold (const JOYSTICK::FeatureName &feature, unsigned int holdTimeMs) override
A digital button has been pressed for more than one event frame.
bool OnButtonMotion (const JOYSTICK::FeatureName &feature, float magnitude, unsigned int motionTimeMs) override
An analog button (trigger or a pressure-sensitive button) has changed state.
bool OnAnalogStickMotion (const JOYSTICK::FeatureName &feature, float x, float y, unsigned int motionTimeMs) override
An analog stick has moved.
bool OnAccelerometerMotion (const JOYSTICK::FeatureName &feature, float x, float y, float z) override
An accelerometer's state has changed.
bool OnWheelMotion (const JOYSTICK::FeatureName &feature, float position, unsigned int motionTimeMs) override
A wheel has changed state.
bool OnThrottleMotion (const JOYSTICK::FeatureName &feature, float position, unsigned int motionTimeMs) override
A throttle has changed state.
void OnInputFrame () override
Called at the end of the frame that provided input.
Public Member Functions inherited from KODI::KEYMAP::IKeymapHandler
virtual ~IKeymapHandler ()=default
Public Member Functions inherited from KODI::JOYSTICK::IInputHandler
virtual ~IInputHandler ()=default
void SetInputReceiver (IInputReceiver *receiver)
void ResetInputReceiver (void)
IInputReceiver * InputReceiver (void)
Protected Attributes
std::unique_ptr< JOYSTICK::IButtonSequence > m_easterEgg
Private Member Functions
bool ActivateDirection (const JOYSTICK::FeatureName &feature, float magnitude, JOYSTICK::ANALOG_STICK_DIRECTION dir, unsigned int motionTimeMs)
void DeactivateDirection (const JOYSTICK::FeatureName &feature, JOYSTICK::ANALOG_STICK_DIRECTION dir)
bool ActivateDirection (const JOYSTICK::FeatureName &feature, float magnitude, JOYSTICK::WHEEL_DIRECTION dir, unsigned int motionTimeMs)
void DeactivateDirection (const JOYSTICK::FeatureName &feature, JOYSTICK::WHEEL_DIRECTION dir)
bool ActivateDirection (const JOYSTICK::FeatureName &feature, float magnitude, JOYSTICK::THROTTLE_DIRECTION dir, unsigned int motionTimeMs)
void DeactivateDirection (const JOYSTICK::FeatureName &feature, JOYSTICK::THROTTLE_DIRECTION dir)
IKeyHandler * GetKeyHandler (const std::string &keyName)
bool HasAction (const std::string &keyName) const
Private Attributes
ACTION::IActionListener *const m_actionHandler
const IKeymap *const m_keymap
std::map< std::string, std::unique_ptr< IKeyHandler > > m_keyHandlers
std::string m_lastPressed
Constructor & Destructor Documentation
CKeymapHandler()
CKeymapHandler::CKeymapHandler (ACTION::IActionListener * actionHandler, const IKeymap * keymap)
References ControllerID(), KODI::KEYMAP::IKeymap::Environment(), m_actionHandler, m_easterEgg, m_keymap, and KODI::KEYMAP::IKeymapEnvironment::UseEasterEgg().
~CKeymapHandler()
KODI::KEYMAP::CKeymapHandler::~CKeymapHandler () override default
Member Function Documentation
AcceptsInput()
bool CKeymapHandler::AcceptsInput (const JOYSTICK::FeatureName & feature) const override virtual
Return true if the input handler is currently accepting input for the given feature.
Parameters
feature A feature belonging to the controller specified by ControllerID()
Returns
True if the feature is currently accepting input, false otherwise
This does not prevent the input events from being called, but can return false to indicate that input wasn't handled for the specified feature.
Implements KODI::JOYSTICK::IInputHandler.
References KODI::JOYSTICK::CJoystickUtils::GetAnalogStickDirections(), HasAction(), and KODI::JOYSTICK::CJoystickUtils::MakeKeyName().
ActivateDirection() [1/3]
bool CKeymapHandler::ActivateDirection (const JOYSTICK::FeatureName & feature, float magnitude, JOYSTICK::ANALOG_STICK_DIRECTION dir, unsigned int motionTimeMs) private
References GetKeyHandler(), KODI::JOYSTICK::CJoystickUtils::MakeKeyName(), and KODI::KEYMAP::IKeyHandler::OnAnalogMotion().
Referenced by OnAnalogStickMotion(), OnThrottleMotion(), and OnWheelMotion().
ActivateDirection() [2/3]
bool CKeymapHandler::ActivateDirection (const JOYSTICK::FeatureName & feature, float magnitude, JOYSTICK::THROTTLE_DIRECTION dir, unsigned int motionTimeMs) private
References GetKeyHandler(), KODI::JOYSTICK::CJoystickUtils::MakeKeyName(), and KODI::KEYMAP::IKeyHandler::OnAnalogMotion().
ActivateDirection() [3/3]
bool CKeymapHandler::ActivateDirection (const JOYSTICK::FeatureName & feature, float magnitude, JOYSTICK::WHEEL_DIRECTION dir, unsigned int motionTimeMs) private
References GetKeyHandler(), KODI::JOYSTICK::CJoystickUtils::MakeKeyName(), and KODI::KEYMAP::IKeyHandler::OnAnalogMotion().
ControllerID()
std::string CKeymapHandler::ControllerID () const override virtual
The add-on ID of the game controller associated with this input handler.
Returns
The ID of the add-on extending kodi.game.controller
Implements KODI::JOYSTICK::IInputHandler.
References KODI::KEYMAP::IKeymap::ControllerID(), and m_keymap.
Referenced by CKeymapHandler().
DeactivateDirection() [1/3]
void CKeymapHandler::DeactivateDirection (const JOYSTICK::FeatureName & feature, JOYSTICK::ANALOG_STICK_DIRECTION dir) private
References GetKeyHandler(), KODI::JOYSTICK::CJoystickUtils::MakeKeyName(), and KODI::KEYMAP::IKeyHandler::OnAnalogMotion().
Referenced by OnAnalogStickMotion(), OnThrottleMotion(), and OnWheelMotion().
DeactivateDirection() [2/3]
void CKeymapHandler::DeactivateDirection (const JOYSTICK::FeatureName & feature, JOYSTICK::THROTTLE_DIRECTION dir) private
References GetKeyHandler(), KODI::JOYSTICK::CJoystickUtils::MakeKeyName(), and KODI::KEYMAP::IKeyHandler::OnAnalogMotion().
DeactivateDirection() [3/3]
void CKeymapHandler::DeactivateDirection (const JOYSTICK::FeatureName & feature, JOYSTICK::WHEEL_DIRECTION dir) private
References GetKeyHandler(), KODI::JOYSTICK::CJoystickUtils::MakeKeyName(), and KODI::KEYMAP::IKeyHandler::OnAnalogMotion().
GetKeyHandler()
IKeyHandler * CKeymapHandler::GetKeyHandler (const std::string & keyName) private
References m_actionHandler, m_keyHandlers, and m_keymap.
Referenced by ActivateDirection(), ActivateDirection(), ActivateDirection(), DeactivateDirection(), DeactivateDirection(), DeactivateDirection(), OnButtonHold(), OnButtonMotion(), and OnButtonPress().
GetLastPressed()
std::string KODI::KEYMAP::CKeymapHandler::GetLastPressed () const inline override virtual
Get the key name of the last button pressed.
Returns
The key name of the last-pressed button, or empty if no button is pressed
Implements KODI::KEYMAP::IKeymapHandler.
References m_lastPressed.
HasAction()
bool CKeymapHandler::HasAction (const std::string & keyName) const private
References actions, KODI::KEYMAP::KeymapActionGroup::actions, KODI::KEYMAP::IKeymap::GetActions(), HotkeysPressed(), and m_keymap.
Referenced by AcceptsInput().
HasFeature()
bool KODI::KEYMAP::CKeymapHandler::HasFeature (const JOYSTICK::FeatureName & feature) const inline override virtual
Return true if the input handler accepts the given feature.
Parameters
feature A feature belonging to the controller specified by ControllerID()
Returns
True if the feature is used for input, false otherwise
Implements KODI::JOYSTICK::IInputHandler.
HotkeysPressed()
bool CKeymapHandler::HotkeysPressed (const std::set< std::string > & keyNames) const override virtual
Get the pressed state of the given keys.
Parameters
keyNames The key names
Returns
True if all keys are pressed or no keys are given, false otherwise
Implements KODI::KEYMAP::IKeymapHandler.
References m_keyHandlers.
Referenced by HasAction().
OnAccelerometerMotion()
bool CKeymapHandler::OnAccelerometerMotion (const JOYSTICK::FeatureName & feature, float x, float y, float z) override virtual
An accelerometer's state has changed.
Parameters
feature The accelerometer being accelerated
x The x coordinate in the closed interval [-1, 1]
y The y coordinate in the closed interval [-1, 1]
z The z coordinate in the closed interval [-1, 1]
Returns
True if the event was handled otherwise false
Todo:
implement
Reimplemented from KODI::JOYSTICK::IInputHandler.
OnAnalogStickMotion()
bool CKeymapHandler::OnAnalogStickMotion (const JOYSTICK::FeatureName & feature, float x, float y, unsigned int motionTimeMs) override virtual
An analog stick has moved.
Parameters
feature The analog stick being moved
x The x coordinate in the closed interval [-1, 1]
y The y coordinate in the closed interval [-1, 1]
motionTimeMs The time elapsed since this analog stick was centered, or 0 if the analog stick is centered
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References ActivateDirection(), DeactivateDirection(), and KODI::JOYSTICK::CJoystickUtils::GetAnalogStickDirections().
OnButtonHold()
void CKeymapHandler::OnButtonHold (const JOYSTICK::FeatureName & feature, unsigned int holdTimeMs) override virtual
A digital button has been pressed for more than one event frame.
Parameters
feature The feature being held
holdTimeMs The time elapsed since the initial press (ms)
If OnButtonPress() returns true for the initial press, then this callback is invoked on subsequent frames until the button is released.
Implements KODI::JOYSTICK::IInputHandler.
References GetKeyHandler(), m_easterEgg, KODI::JOYSTICK::CJoystickUtils::MakeKeyName(), and KODI::KEYMAP::IKeyHandler::OnDigitalMotion().
OnButtonMotion()
bool CKeymapHandler::OnButtonMotion (const JOYSTICK::FeatureName & feature, float magnitude, unsigned int motionTimeMs) override virtual
An analog button (trigger or a pressure-sensitive button) has changed state.
Parameters
feature The feature changing state
magnitude The button pressure or trigger travel distance in the closed interval [0, 1]
motionTimeMs The time elapsed since the magnitude was 0
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References GetKeyHandler(), KODI::JOYSTICK::CJoystickUtils::MakeKeyName(), and KODI::KEYMAP::IKeyHandler::OnAnalogMotion().
OnButtonPress()
bool CKeymapHandler::OnButtonPress (const JOYSTICK::FeatureName & feature, bool bPressed) override virtual
A digital button has been pressed or released.
Parameters
feature The feature being pressed
bPressed True if pressed, false if released
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References GetKeyHandler(), m_easterEgg, KODI::JOYSTICK::CJoystickUtils::MakeKeyName(), and KODI::KEYMAP::IKeyHandler::OnDigitalMotion().
OnInputFrame()
void KODI::KEYMAP::CKeymapHandler::OnInputFrame () inline override virtual
Called at the end of the frame that provided input.
Implements KODI::JOYSTICK::IInputHandler.
OnPress()
void KODI::KEYMAP::CKeymapHandler::OnPress (const std::string & keyName) inline override virtual
Called when a key has emitted an action after bring pressed.
Parameters
keyName the key name that emitted the action
Implements KODI::KEYMAP::IKeymapHandler.
References m_lastPressed.
OnThrottleMotion()
bool CKeymapHandler::OnThrottleMotion (const JOYSTICK::FeatureName & feature, float position, unsigned int motionTimeMs) override virtual
A throttle has changed state.
Up is positive position, down is negative position.
Parameters
feature The wheel changing state
position The position in the closed interval [-1, 1]
motionTimeMs The time elapsed since the position was 0
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References ActivateDirection(), DeactivateDirection(), KODI::JOYSTICK::CJoystickUtils::GetThrottleDirections(), and KODI::JOYSTICK::CJoystickTranslator::PositionToThrottleDirection().
OnWheelMotion()
bool CKeymapHandler::OnWheelMotion (const JOYSTICK::FeatureName & feature, float position, unsigned int motionTimeMs) override virtual
A wheel has changed state.
Left is negative position, right is positive position
Parameters
feature The wheel changing state
position The position in the closed interval [-1, 1]
motionTimeMs The time elapsed since the position was 0
Returns
True if the event was handled otherwise false
Implements KODI::JOYSTICK::IInputHandler.
References ActivateDirection(), DeactivateDirection(), KODI::JOYSTICK::CJoystickUtils::GetWheelDirections(), and KODI::JOYSTICK::CJoystickTranslator::PositionToWheelDirection().
Member Data Documentation
m_actionHandler
ACTION::IActionListener* const KODI::KEYMAP::CKeymapHandler::m_actionHandler private
Referenced by CKeymapHandler(), and GetKeyHandler().
m_easterEgg
std::unique_ptr<JOYSTICK::IButtonSequence> KODI::KEYMAP::CKeymapHandler::m_easterEgg protected
Referenced by CKeymapHandler(), OnButtonHold(), and OnButtonPress().
m_keyHandlers
std::map<std::string, std::unique_ptr<IKeyHandler> > KODI::KEYMAP::CKeymapHandler::m_keyHandlers private
Referenced by GetKeyHandler(), and HotkeysPressed().
m_keymap
const IKeymap* const KODI::KEYMAP::CKeymapHandler::m_keymap private
Referenced by CKeymapHandler(), ControllerID(), GetKeyHandler(), and HasAction().
m_lastPressed
std::string KODI::KEYMAP::CKeymapHandler::m_lastPressed private
Referenced by GetLastPressed(), and OnPress().
The documentation for this class was generated from the following files:
KeymapHandler.h
KeymapHandler.cpp