Kodi Documentation: KODI::GAME::CGUIDialogButtonCapture Class Reference
KODI::GAME::CGUIDialogButtonCapture Class Reference abstract
Games
#include <GUIDialogButtonCapture.h>
Public Member Functions
CGUIDialogButtonCapture ()
~CGUIDialogButtonCapture () override=default
std::string ControllerID () const override
The add-on ID of the game controller associated with this button mapper.
bool NeedsCooldown () const override
Return true if the button mapper wants a cooldown between button mapping commands.
bool MapPrimitive (JOYSTICK::IButtonMap *buttonMap, KEYMAP::IKeymap *keymap, const JOYSTICK::CDriverPrimitive &primitive) override
Handle button/hat press or axis threshold.
void OnEventFrame (const JOYSTICK::IButtonMap *buttonMap, bool bMotion) override
Called once per event frame to notify the implementation of motion status.
void OnLateAxis (const JOYSTICK::IButtonMap *buttonMap, unsigned int axisIndex) override
Called when an axis has been detected after mapping began.
void Notify (const Observable &obs, const ObservableMessage msg) override
Process a message from an observable.
void Show ()
Show the dialog.
Public Member Functions inherited from KODI::JOYSTICK::IButtonMapper
IButtonMapper ()=default
virtual ~IButtonMapper ()=default
virtual bool AcceptsPrimitive (PRIMITIVE_TYPE type) const =0
Return true if the button mapper accepts primitives of the given type.
void SetButtonMapCallback (const std::string &deviceLocation, IButtonMapCallback *callback)
void ResetButtonMapCallbacks (void)
std::map< std::string, IButtonMapCallback * > & ButtonMapCallbacks (void)
Public Member Functions inherited from Observer
Observer ()=default
virtual ~Observer ()=default
Protected Member Functions
void Process () override
virtual std::string GetDialogText ()=0
virtual std::string GetDialogHeader ()=0
virtual bool MapPrimitiveInternal (JOYSTICK::IButtonMap *buttonMap, KEYMAP::IKeymap *keymap, const JOYSTICK::CDriverPrimitive &primitive)=0
virtual void OnClose (bool bAccepted)=0
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Protected Attributes
CEvent m_captureEvent
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Private Member Functions
void InstallHooks ()
void RemoveHooks ()
Additional Inherited Members
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Static Protected Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Constructor & Destructor Documentation
CGUIDialogButtonCapture()
CGUIDialogButtonCapture::CGUIDialogButtonCapture ()
~CGUIDialogButtonCapture()
KODI::GAME::CGUIDialogButtonCapture::~CGUIDialogButtonCapture () override default
Member Function Documentation
ControllerID()
std::string CGUIDialogButtonCapture::ControllerID () const override virtual
The add-on ID of the game controller associated with this button mapper.
Returns
The ID of the add-on extending kodi.game.controller
Implements KODI::JOYSTICK::IButtonMapper.
References DEFAULT_CONTROLLER_ID.
GetDialogHeader()
virtual std::string KODI::GAME::CGUIDialogButtonCapture::GetDialogHeader () protected pure virtual
Implemented in KODI::GAME::CGUIDialogAxisDetection, and KODI::GAME::CGUIDialogIgnoreInput.
Referenced by Show().
GetDialogText()
virtual std::string KODI::GAME::CGUIDialogButtonCapture::GetDialogText () protected pure virtual
Implemented in KODI::GAME::CGUIDialogAxisDetection, and KODI::GAME::CGUIDialogIgnoreInput.
Referenced by Process(), and Show().
InstallHooks()
void CGUIDialogButtonCapture::InstallHooks (void) private
References CServiceBroker::GetPeripherals(), PERIPHERALS::CPeripherals::RegisterJoystickButtonMapper(), and Observable::RegisterObserver().
Referenced by Show().
MapPrimitive()
bool CGUIDialogButtonCapture::MapPrimitive (JOYSTICK::IButtonMap * buttonMap, KEYMAP::IKeymap * keyMap, const JOYSTICK::CDriverPrimitive & primitive) override virtual
Handle button/hat press or axis threshold.
Parameters
buttonMap The button map being manipulated
keymap An interface capable of translating features to Kodi actions
primitive The driver primitive
Called in the same thread as IButtonMapper::OnFrame.
Returns
True if driver primitive was mapped to a feature
Implements KODI::JOYSTICK::IButtonMapper.
References ACTION_NAV_BACK, ACTION_PREVIOUS_MENU, ACTION_SELECT_ITEM, actions, KODI::KEYMAP::KeymapActionGroup::actions, KODI::KEYMAP::IKeymap::ControllerID(), KODI::JOYSTICK::IButtonMap::ControllerID(), KODI::KEYMAP::IKeymap::GetActions(), KODI::JOYSTICK::IButtonMap::GetFeature(), CThread::m_bStop, KODI::JOYSTICK::CJoystickUtils::MakeKeyName(), and MapPrimitiveInternal().
MapPrimitiveInternal()
virtual bool KODI::GAME::CGUIDialogButtonCapture::MapPrimitiveInternal (JOYSTICK::IButtonMap * buttonMap, KEYMAP::IKeymap * keymap, const JOYSTICK::CDriverPrimitive & primitive) protected pure virtual
Implemented in KODI::GAME::CGUIDialogAxisDetection, and KODI::GAME::CGUIDialogIgnoreInput.
Referenced by MapPrimitive().
NeedsCooldown()
bool KODI::GAME::CGUIDialogButtonCapture::NeedsCooldown () const inline override virtual
Return true if the button mapper wants a cooldown between button mapping commands.
Returns
True to only send button mapping commands that occur after a small timeout from the previous command.
Implements KODI::JOYSTICK::IButtonMapper.
Notify()
void CGUIDialogButtonCapture::Notify (const Observable & obs, const ObservableMessage msg) override virtual
Process a message from an observable.
Parameters
obs The observable that sends the message.
msg The message.
Implements Observer.
References CServiceBroker::GetPeripherals(), ObservableMessagePeripheralsChanged, PERIPHERALS::CPeripherals::RegisterJoystickButtonMapper(), and PERIPHERALS::CPeripherals::UnregisterJoystickButtonMapper().
OnClose()
virtual void KODI::GAME::CGUIDialogButtonCapture::OnClose (bool bAccepted) protected pure virtual
Implemented in KODI::GAME::CGUIDialogAxisDetection, and KODI::GAME::CGUIDialogIgnoreInput.
Referenced by Show().
OnEventFrame()
void KODI::GAME::CGUIDialogButtonCapture::OnEventFrame (const JOYSTICK::IButtonMap * buttonMap, bool bMotion) inline override virtual
Called once per event frame to notify the implementation of motion status.
Parameters
buttonMap The button map passed to MapPrimitive() (shall not be modified)
bMotion True if a previously-mapped axis is still in motion
This allows the implementer to wait for an axis to be centered before allowing it to be used as Kodi input.
If mapping finishes on an axis, then the axis will still be pressed and sending input every frame when the mapping ends. For example, when the right analog stick is the last feature to be mapped, it is still pressed when mapping ends and immediately sends Volume Down actions.
The fix is to allow implementers to wait until all axes are motionless before detaching themselves.
Called in the same thread as IButtonMapper::MapPrimitive.
Implements KODI::JOYSTICK::IButtonMapper.
OnLateAxis()
void KODI::GAME::CGUIDialogButtonCapture::OnLateAxis (const JOYSTICK::IButtonMap * buttonMap, unsigned int axisIndex) inline override virtual
Called when an axis has been detected after mapping began.
Parameters
axisIndex The index of the axis being discovered
Some joystick drivers don't report an initial value for analog axes.
Called in the same thread as IButtonMapper::MapPrimitive.
Implements KODI::JOYSTICK::IButtonMapper.
Process()
void CGUIDialogButtonCapture::Process (void) override protected virtual
Todo:
Move to rendering thread when there is a rendering thread
Reimplemented from CThread.
References GetDialogText(), CThread::m_bStop, m_captureEvent, KODI::MESSAGING::HELPERS::UpdateOKDialogText(), and CEvent::Wait().
RemoveHooks()
void CGUIDialogButtonCapture::RemoveHooks (void) private
References CServiceBroker::GetPeripherals(), PERIPHERALS::CPeripherals::UnregisterJoystickButtonMapper(), and Observable::UnregisterObserver().
Referenced by Show().
Show()
void CGUIDialogButtonCapture::Show ()
Show the dialog.
References CThread::Create(), GetDialogHeader(), GetDialogText(), InstallHooks(), CThread::IsRunning(), m_captureEvent, OnClose(), RemoveHooks(), CEvent::Set(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), and CThread::StopThread().
Referenced by KODI::GAME::CGUIConfigurationWizard::Process(), and KODI::GAME::CGUIControllerWindow::ShowButtonCaptureDialog().
Member Data Documentation
m_captureEvent
CEvent KODI::GAME::CGUIDialogButtonCapture::m_captureEvent protected
Referenced by KODI::GAME::CGUIDialogAxisDetection::AddAxis(), KODI::GAME::CGUIDialogIgnoreInput::MapPrimitiveInternal(), Process(), and Show().
The documentation for this class was generated from the following files:
GUIDialogButtonCapture.h
GUIDialogButtonCapture.cpp