Kodi Documentation: CCharArrayParser Class Reference
CCharArrayParser Class Reference
Wraps a char array, providing a set of methods for parsing data from it.
#include <CharArrayParser.h>
Public Member Functions
CCharArrayParser ()=default
~CCharArrayParser ()=default
void Reset ()
Sets the position and limit to zero.
void Reset (const char *data, int limit)
Updates the instance to wrap the specified data and resets the position to zero.
int CharsLeft ()
Return the number of chars yet to be read.
int GetPosition ()
Returns the current offset in the array.
bool SetPosition (int position)
Set the reading offset in the array.
bool SkipChars (int nChars)
Skip a specified number of chars.
uint8_t ReadNextUnsignedChar ()
Reads the next unsigned char (it is assumed that the caller has already checked the availability of the data for its length)
uint16_t ReadNextUnsignedShort ()
Reads the next two chars as unsigned short value (it is assumed that the caller has already checked the availability of the data for its length)
uint32_t ReadNextUnsignedInt ()
Reads the next four chars as unsigned int value (it is assumed that the caller has already checked the availability of the data for its length)
std::string ReadNextString (int length)
Reads the next string of specified length (it is assumed that the caller has already checked the availability of the data for its length)
bool ReadNextArray (int length, char *data)
Reads the next chars array of specified length (it is assumed that the caller has already checked the availability of the data for its length)
bool ReadNextLine (std::string &line)
Reads a line of text. A line is considered to be terminated by any one of a carriage return ('\r'), a line feed ('\n'), or a carriage return followed by a line feed ('\r\n'), this method discards leading UTF-8 byte order marks, if present.
const char * GetData ()
Get the current data.
Private Attributes
const char * m_data {nullptr}
int m_position {0}
int m_limit {0}
Detailed Description
Wraps a char array, providing a set of methods for parsing data from it.
Constructor & Destructor Documentation
CCharArrayParser()
CCharArrayParser::CCharArrayParser () default
~CCharArrayParser()
CCharArrayParser::~CCharArrayParser () default
Member Function Documentation
CharsLeft()
int CCharArrayParser::CharsLeft ()
Return the number of chars yet to be read.
References m_limit, and m_position.
Referenced by CDVDOverlayCodecTX3G::Decode(), CWebVTTISOHandler::DecodeStream(), and ReadNextLine().
GetData()
const char * CCharArrayParser::GetData () inline
Get the current data.
Returns
The char pointer to the current data
References m_data.
GetPosition()
int CCharArrayParser::GetPosition ()
Returns the current offset in the array.
References m_position.
Referenced by CDVDOverlayCodecTX3G::Decode().
ReadNextArray()
bool CCharArrayParser::ReadNextArray (int length, char * data)
Reads the next chars array of specified length (it is assumed that the caller has already checked the availability of the data for its length)
Parameters
length The length to be read
data[OUT] The data read
Returns
True if success, otherwise false
References data(), CLog::Log(), LOGERROR, m_data, m_limit, and m_position.
ReadNextLine()
bool CCharArrayParser::ReadNextLine (std::string & line)
Reads a line of text. A line is considered to be terminated by any one of a carriage return ('\r'), a line feed ('\n'), or a carriage return followed by a line feed ('\r\n'), this method discards leading UTF-8 byte order marks, if present.
Parameters
line [OUT] The line read without line-termination characters
Returns
True if read, otherwise false if the end of the data has already been reached
References CharsLeft(), CLog::Log(), LOGERROR, m_data, m_limit, and m_position.
Referenced by COverlayCodecWebVTT::Decode(), and CDVDSubtitleStream::ReadLine().
ReadNextString()
std::string CCharArrayParser::ReadNextString (int length)
Reads the next string of specified length (it is assumed that the caller has already checked the availability of the data for its length)
Parameters
length The length to be read
Returns
The string value
References CLog::Log(), LOGERROR, m_data, m_limit, and m_position.
Referenced by CWebVTTISOHandler::ParseVTTCueBox(), and CDVDSubtitleStream::Read().
ReadNextUnsignedChar()
uint8_t CCharArrayParser::ReadNextUnsignedChar ()
Reads the next unsigned char (it is assumed that the caller has already checked the availability of the data for its length)
Returns
The unsigned char value
References CLog::Log(), LOGERROR, m_data, m_limit, and m_position.
Referenced by CDVDOverlayCodecTX3G::Decode().
ReadNextUnsignedInt()
uint32_t CCharArrayParser::ReadNextUnsignedInt ()
Reads the next four chars as unsigned int value (it is assumed that the caller has already checked the availability of the data for its length)
Returns
The unsigned int value
References CLog::Log(), LOGERROR, m_data, m_limit, and m_position.
Referenced by CDVDOverlayCodecTX3G::Decode(), CWebVTTISOHandler::DecodeStream(), and CWebVTTISOHandler::ParseVTTCueBox().
ReadNextUnsignedShort()
uint16_t CCharArrayParser::ReadNextUnsignedShort ()
Reads the next two chars as unsigned short value (it is assumed that the caller has already checked the availability of the data for its length)
Returns
The unsigned short value
References CLog::Log(), LOGERROR, m_data, m_limit, and m_position.
Referenced by CDVDOverlayCodecTX3G::Decode().
Reset() [1/2]
void CCharArrayParser::Reset ()
Sets the position and limit to zero.
References m_limit, and m_position.
Referenced by CDVDOverlayCodecTX3G::Decode(), COverlayCodecWebVTT::Decode(), CWebVTTISOHandler::DecodeStream(), and CDVDSubtitleStream::Open().
Reset() [2/2]
void CCharArrayParser::Reset (const char * data, int limit)
Updates the instance to wrap the specified data and resets the position to zero.
Parameters
data The data
limit The limit of length of the data
References data(), m_data, m_limit, and m_position.
SetPosition()
bool CCharArrayParser::SetPosition (int position)
Set the reading offset in the array.
Parameters
position The new offset position
Returns
True if success, otherwise false
References CLog::Log(), LOGERROR, m_limit, and m_position.
Referenced by CDVDSubtitleStream::Seek(), and SkipChars().
SkipChars()
bool CCharArrayParser::SkipChars (int nChars)
Skip a specified number of chars.
Parameters
nChars The number of chars
Returns
True if success, otherwise false
References m_position, and SetPosition().
Referenced by CDVDOverlayCodecTX3G::Decode(), and CWebVTTISOHandler::DecodeStream().
Member Data Documentation
m_data
const char* CCharArrayParser::m_data {nullptr} private
Referenced by GetData(), ReadNextArray(), ReadNextLine(), ReadNextString(), ReadNextUnsignedChar(), ReadNextUnsignedInt(), ReadNextUnsignedShort(), and Reset().
m_limit
int CCharArrayParser::m_limit {0} private
Referenced by CharsLeft(), ReadNextArray(), ReadNextLine(), ReadNextString(), ReadNextUnsignedChar(), ReadNextUnsignedInt(), ReadNextUnsignedShort(), Reset(), Reset(), and SetPosition().
m_position
int CCharArrayParser::m_position {0} private
Referenced by CharsLeft(), GetPosition(), ReadNextArray(), ReadNextLine(), ReadNextString(), ReadNextUnsignedChar(), ReadNextUnsignedInt(), ReadNextUnsignedShort(), Reset(), Reset(), SetPosition(), and SkipChars().
The documentation for this class was generated from the following files:
CharArrayParser.h
CharArrayParser.cpp