Kodi Documentation: TestGameClientTopology.cpp File Reference
TestGameClientTopology.cpp File Reference
#include "addons/kodi-dev-kit/include/kodi/c-api/addon-instance/game.h"
#include "games/addons/input/GameClientPort.h"
#include "games/addons/input/GameClientTopology.h"
#include "games/controllers/ControllerIDs.h"
#include "games/controllers/types/ControllerTree.h"
#include <gtest/gtest.h>
Functions
TEST (TestGameClientTopology, Construtor)
TEST (TestGameClientTopology, MakeAddress)
TEST (TestGameClientTopology, SplitAddress)
TEST (TestGameClientTopology, TestKeyboard)
TEST (TestGameClientTopology, TestMouse)
Function Documentation
TEST() [1/5]
TEST (TestGameClientTopology , Construtor)
References EXPECT_EQ(), KODI::GAME::CGameClientTopology::GetControllerTree(), KODI::GAME::CGameClientTopology::GetPlayerLimit(), and KODI::GAME::CControllerHub::GetPorts().
TEST() [2/5]
TEST (TestGameClientTopology , MakeAddress)
References DEFAULT_CONTROLLER_ID, DEFAULT_PORT_ADDRESS, DEFAULT_PORT_ID, EXPECT_EQ(), KODI::GAME::CGameClientTopology::MakeAddress(), and ROOT_PORT_ADDRESS.
TEST() [3/5]
TEST (TestGameClientTopology , SplitAddress)
References DEFAULT_CONTROLLER_ID, DEFAULT_PORT_ADDRESS, DEFAULT_PORT_ID, EXPECT_EQ(), ROOT_PORT_ADDRESS, and KODI::GAME::CGameClientTopology::SplitAddress().
TEST() [4/5]
TEST (TestGameClientTopology , TestKeyboard)
References DEFAULT_KEYBOARD_ID, EXPECT_EQ(), KEYBOARD_PORT_ADDRESS, KEYBOARD_PORT_ID, KODI::GAME::CGameClientTopology::MakeAddress(), ROOT_PORT_ADDRESS, and KODI::GAME::CGameClientTopology::SplitAddress().
TEST() [5/5]
TEST (TestGameClientTopology , TestMouse)
References DEFAULT_MOUSE_ID, EXPECT_EQ(), KODI::GAME::CGameClientTopology::MakeAddress(), MOUSE_PORT_ADDRESS, MOUSE_PORT_ID, ROOT_PORT_ADDRESS, and KODI::GAME::CGameClientTopology::SplitAddress().