Kodi Documentation: KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler Class Reference
KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler Class Reference
Public Member Functions
CVideoItemArtworkFanartHandler (const std::shared_ptr< CFileItem > &item, const std::string &artType)
std::string GetCurrentArt () const override
std::vector< std::string > GetRemoteArt () const override
std::string GetLocalArt () const override
std::string GetDefaultIcon () const override
bool SupportsFlippedArt () const override
std::string UpdateEmbeddedArt (const std::string &art) override
std::string UpdateRemoteArt (const std::vector< std::string > &art, int index) override
Public Member Functions inherited from KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler
CVideoItemArtworkHandler (const std::shared_ptr< CFileItem > &item, const std::string &artType)
std::string GetCurrentArt () const override
std::string GetEmbeddedArt () const override
std::vector< std::string > GetRemoteArt () const override
std::string GetLocalArt () const override
std::string GetDefaultIcon () const override
void AddItemPathToFileBrowserSources (std::vector< CMediaSource > &sources) override
void PersistArt (const std::string &art) override
Public Member Functions inherited from KODI::VIDEO::IVideoItemArtworkHandler
virtual ~IVideoItemArtworkHandler ()=default
Additional Inherited Members
Protected Member Functions inherited from KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler
void AddItemPathStringToFileBrowserSources (std::vector< CMediaSource > &sources, const std::string &itemDir, const std::string &label)
Protected Attributes inherited from KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler
const std::shared_ptr< CFileItem > m_item
const std::string m_artType
Constructor & Destructor Documentation
CVideoItemArtworkFanartHandler()
KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::CVideoItemArtworkFanartHandler (const std::shared_ptr< CFileItem > & item, const std::string & artType) inline explicit
Member Function Documentation
GetCurrentArt()
std::string KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::GetCurrentArt () const override virtual
Implements KODI::VIDEO::IVideoItemArtworkHandler.
GetDefaultIcon()
std::string KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::GetDefaultIcon () const inline override virtual
Implements KODI::VIDEO::IVideoItemArtworkHandler.
GetLocalArt()
std::string KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::GetLocalArt () const override virtual
Reimplemented from KODI::VIDEO::IVideoItemArtworkHandler.
References KODI::ART::GetLocalFanart().
GetRemoteArt()
std::vector< std::string > KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::GetRemoteArt () const override virtual
Reimplemented from KODI::VIDEO::IVideoItemArtworkHandler.
References CFanart::GetNumFanarts(), CFanart::GetPreviewURL(), URIUtils::IsProtocol(), CVideoInfoTag::m_fanart, and IMAGE_FILES::URLFromFile().
SupportsFlippedArt()
bool KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::SupportsFlippedArt () const inline override virtual
Reimplemented from KODI::VIDEO::IVideoItemArtworkHandler.
UpdateEmbeddedArt()
std::string KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::UpdateEmbeddedArt (const std::string & art) override virtual
Reimplemented from KODI::VIDEO::IVideoItemArtworkHandler.
References CFanart::AddFanart(), CFanart::GetImageURL(), CFanart::GetNumFanarts(), URIUtils::IsProtocol(), LOGERROR, CVideoInfoTag::m_fanart, CVideoDatabase::Open(), CFanart::SetPrimaryFanart(), and CVideoDatabase::UpdateFanart().
UpdateRemoteArt()
std::string KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkFanartHandler::UpdateRemoteArt (const std::vector< std::string > & art, int index) override virtual
Reimplemented from KODI::VIDEO::IVideoItemArtworkHandler.
References CFanart::GetImageURL(), index(), LOGERROR, CVideoInfoTag::m_fanart, CVideoDatabase::Open(), CFanart::SetPrimaryFanart(), and CVideoDatabase::UpdateFanart().
The documentation for this class was generated from the following file:
VideoItemArtworkHandler.cpp