Kodi Documentation: CDVDDemuxVobsub Class Reference
CDVDDemuxVobsub Class Reference
#include <DVDDemuxVobsub.h>
Classes
class CStream
struct sorter
struct SState
struct STimestamp
Public Member Functions
CDVDDemuxVobsub ()
~CDVDDemuxVobsub () override
bool Open (const std::string &filename, int source, const std::string &subfilename)
bool Reset () override
void Flush () override
DemuxPacket * Read () override
bool SeekTime (double time, bool backwards, double *startpts=NULL) override
CDemuxStream * GetStream (int index) const override
std::vector< CDemuxStream * > GetStreams () const override
int GetNrOfStreams () const override
std::string GetFileName () override
void EnableStream (int id, bool enable) override
Public Member Functions inherited from CDVDDemux
CDVDDemux ()
virtual ~CDVDDemux ()=default
virtual void Abort ()
virtual bool SeekChapter (int chapter, double *startpts=NULL)
virtual int GetChapterCount ()
virtual int GetChapter ()
virtual void GetChapterName (std::string &strChapterName, int chapterIdx=-1)
virtual int64_t GetChapterPos (int chapterIdx=-1)
virtual void SetSpeed (int iSpeed)
virtual void FillBuffer (bool mode)
virtual int GetStreamLength ()
virtual CDemuxStream * GetStream (int64_t demuxerId, int iStreamId) const
virtual int GetPrograms (std::vector< ProgramInfo > &programs)
virtual void SetProgram (int progId)
int GetNrOfSubtitleStreams ()
virtual std::string GetStreamCodecName (int64_t demuxerId, int iStreamId)
virtual void EnableStream (int64_t demuxerId, int id, bool enable)
virtual void OpenStream (int64_t demuxerId, int id)
virtual void SetVideoResolution (unsigned int width, unsigned int height)
int64_t GetDemuxerId ()
Private Types
typedef struct CDVDDemuxVobsub::STimestamp STimestamp
typedef struct CDVDDemuxVobsub::SState SState
Private Member Functions
bool ParseLangIdx (SState &state, std::string &line)
bool ParseDelay (SState &state, std::string &line)
bool ParseId (SState &state, std::string &line)
bool ParseExtra (SState &state, const std::string &line)
bool ParseTimestamp (SState &state, std::string &line)
Private Attributes
std::string m_Filename
std::shared_ptr< CDVDInputStream > m_Input
std::unique_ptr< CDVDDemuxFFmpeg > m_Demuxer
std::vector< STimestamp > m_Timestamps
std::vector< STimestamp >::iterator m_Timestamp
std::vector< CStream * > m_Streams
int m_source = -1
Additional Inherited Members
Protected Member Functions inherited from CDVDDemux
virtual void OpenStream (int id)
virtual std::string GetStreamCodecName (int iStreamId)
int GetNrOfStreams (StreamType streamType)
Protected Attributes inherited from CDVDDemux
int64_t m_demuxerId
Member Typedef Documentation
SState
typedef struct CDVDDemuxVobsub::SState CDVDDemuxVobsub::SState private
STimestamp
typedef struct CDVDDemuxVobsub::STimestamp CDVDDemuxVobsub::STimestamp private
Constructor & Destructor Documentation
CDVDDemuxVobsub()
CDVDDemuxVobsub::CDVDDemuxVobsub () default
~CDVDDemuxVobsub()
CDVDDemuxVobsub::~CDVDDemuxVobsub () override
References m_Streams.
Member Function Documentation
EnableStream()
void CDVDDemuxVobsub::EnableStream (int id, bool enable) override virtual
Reimplemented from CDVDDemux.
References m_Streams.
Flush()
void CDVDDemuxVobsub::Flush () override virtual
Implements CDVDDemux.
References m_Demuxer.
Referenced by Reset().
GetFileName()
std::string CDVDDemuxVobsub::GetFileName () inline override virtual
Reimplemented from CDVDDemux.
References m_Filename.
GetNrOfStreams()
int CDVDDemuxVobsub::GetNrOfStreams () const inline override virtual
Implements CDVDDemux.
References m_Streams.
GetStream()
CDemuxStream * CDVDDemuxVobsub::GetStream (int index) const inline override virtual
Implements CDVDDemux.
References index(), and m_Streams.
GetStreams()
std::vector< CDemuxStream * > CDVDDemuxVobsub::GetStreams () const override virtual
Implements CDVDDemux.
References m_Streams.
Referenced by CDVDFileInfo::AddExternalSubtitleToDetails().
Open()
bool CDVDDemuxVobsub::Open (const std::string & filename, int source, const std::string & subfilename)
References CDVDStreamInfo::codec, CDVDFactoryInputStream::CreateInputStream(), data(), CDVDDemuxVobsub::SState::delay, CDVDDemuxVobsub::SState::extra, CDVDDemuxVobsub::SState::id, m_Demuxer, m_Filename, m_Input, m_source, m_Streams, m_Timestamp, m_Timestamps, ParseDelay(), ParseExtra(), ParseId(), ParseLangIdx(), ParseTimestamp(), CFileItem::SetContentLookup(), and CFileItem::SetMimeType().
Referenced by CDVDFileInfo::AddExternalSubtitleToDetails().
ParseDelay()
bool CDVDDemuxVobsub::ParseDelay (SState & state, std::string & line) private
References CDVDDemuxVobsub::SState::delay.
Referenced by Open().
ParseExtra()
bool CDVDDemuxVobsub::ParseExtra (SState & state, const std::string & line) private
References CDVDDemuxVobsub::SState::extra.
Referenced by Open().
ParseId()
bool CDVDDemuxVobsub::ParseId (SState & state, std::string & line) private
References CDVDDemuxVobsub::SState::id, CDVDDemux::m_demuxerId, m_source, and m_Streams.
Referenced by Open().
ParseLangIdx()
bool CDVDDemuxVobsub::ParseLangIdx (SState & state, std::string & line) private
Referenced by Open().
ParseTimestamp()
bool CDVDDemuxVobsub::ParseTimestamp (SState & state, std::string & line) private
References CDVDDemuxVobsub::SState::delay, DVD_SEC_TO_TIME(), CDVDDemuxVobsub::STimestamp::id, CDVDDemuxVobsub::SState::id, m_Timestamps, CDVDDemuxVobsub::STimestamp::pos, and CDVDDemuxVobsub::STimestamp::pts.
Referenced by Open().
Read()
DemuxPacket * CDVDDemuxVobsub::Read () override virtual
Implements CDVDDemux.
References DEMUX_PACKET::dts, DEMUX_PACKET::iStreamId, m_Demuxer, m_Streams, m_Timestamp, m_Timestamps, and DEMUX_PACKET::pts.
Reset()
bool CDVDDemuxVobsub::Reset () override virtual
Implements CDVDDemux.
References Flush().
SeekTime()
bool CDVDDemuxVobsub::SeekTime (double time, bool backwards, double * startpts = NULL) override virtual
Implements CDVDDemux.
References DVD_MSEC_TO_TIME(), m_Streams, m_Timestamp, and m_Timestamps.
Member Data Documentation
m_Demuxer
std::unique_ptr<CDVDDemuxFFmpeg> CDVDDemuxVobsub::m_Demuxer private
Referenced by Flush(), Open(), and Read().
m_Filename
std::string CDVDDemuxVobsub::m_Filename private
Referenced by GetFileName(), and Open().
m_Input
std::shared_ptr<CDVDInputStream> CDVDDemuxVobsub::m_Input private
Referenced by Open().
m_source
int CDVDDemuxVobsub::m_source = -1 private
Referenced by Open(), and ParseId().
m_Streams
std::vector<CStream*> CDVDDemuxVobsub::m_Streams private
Referenced by EnableStream(), GetNrOfStreams(), GetStream(), GetStreams(), Open(), ParseId(), Read(), SeekTime(), and ~CDVDDemuxVobsub().
m_Timestamp
std::vector<STimestamp>::iterator CDVDDemuxVobsub::m_Timestamp private
Referenced by Open(), Read(), and SeekTime().
m_Timestamps
std::vector<STimestamp> CDVDDemuxVobsub::m_Timestamps private
Referenced by Open(), ParseTimestamp(), Read(), and SeekTime().
The documentation for this class was generated from the following files:
DVDDemuxVobsub.h
DVDDemuxVobsub.cpp