Kodi Documentation: CUDisksProvider Class Reference
CUDisksProvider Class Reference
#include <UDisksProvider.h>
Public Member Functions
CUDisksProvider ()
~CUDisksProvider () override
void Initialize () override
void Stop () override
void GetLocalDrives (std::vector< CMediaSource > &localDrives) override
void GetRemovableDrives (std::vector< CMediaSource > &removableDrives) override
bool Eject (const std::string &mountpath) override
std::vector< std::string > GetDiskUsage () override
bool PumpDriveChangeEvents (IStorageEventsCallback *callback) override
Public Member Functions inherited from IStorageProvider
virtual ~IStorageProvider ()=default
virtual std::string GetFirstOpticalDeviceFileName ()
Static Public Member Functions
static bool HasUDisks ()
Static Public Member Functions inherited from IStorageProvider
static std::unique_ptr< IStorageProvider > CreateInstance ()
Called by media manager to create platform storage provider.
Private Types
typedef std::map< std::string, CUDiskDevice * > DeviceMap
typedef std::pair< std::string, CUDiskDevice * > DevicePair
Private Member Functions
void DeviceAdded (const char *object, IStorageEventsCallback *callback)
void DeviceRemoved (const char *object, IStorageEventsCallback *callback)
void DeviceChanged (const char *object, IStorageEventsCallback *callback)
std::vector< std::string > EnumerateDisks ()
void GetDisks (std::vector< CMediaSource > &devices, bool EnumerateRemovable)
Private Attributes
int m_DaemonVersion
DeviceMap m_AvailableDevices
CDBusConnection m_connection
Member Typedef Documentation
DeviceMap
typedef std::map<std::string, CUDiskDevice *> CUDisksProvider::DeviceMap private
DevicePair
typedef std::pair<std::string, CUDiskDevice *> CUDisksProvider::DevicePair private
Constructor & Destructor Documentation
CUDisksProvider()
CUDisksProvider::CUDisksProvider ()
Todo:
do not use dbus_connection_pop_message() that requires the use of a private connection
References CDBusConnection::Connect(), CDBusConnection::Destroy(), CDBusError::Log(), and m_connection.
~CUDisksProvider()
CUDisksProvider::~CUDisksProvider () override
References m_AvailableDevices.
Member Function Documentation
DeviceAdded()
void CUDisksProvider::DeviceAdded (const char * object, IStorageEventsCallback * callback) private
References CUDiskDevice::GetMountPoint(), CServiceBroker::GetSettingsComponent(), CUDiskDevice::IsApproved(), CUDiskDevice::IsMounted(), CUDiskDevice::IsOptical(), CLog::Log(), LOGDBUS, LOGDEBUG, LOGINFO, LOGWARNING, m_AvailableDevices, CUDiskDevice::Mount(), CUDiskDevice::ToStorageDevice(), and CUDiskDevice::ToString().
Referenced by DeviceChanged(), Initialize(), and PumpDriveChangeEvents().
DeviceChanged()
void CUDisksProvider::DeviceChanged (const char * object, IStorageEventsCallback * callback) private
References DeviceAdded(), CServiceBroker::GetSettingsComponent(), CUDiskDevice::IsMounted(), CUDiskDevice::IsOptical(), CLog::Log(), LOGDBUS, LOGDEBUG, LOGWARNING, m_AvailableDevices, CUDiskDevice::Mount(), CUDiskDevice::ToStorageDevice(), CUDiskDevice::ToString(), and CUDiskDevice::Update().
Referenced by PumpDriveChangeEvents().
DeviceRemoved()
void CUDisksProvider::DeviceRemoved (const char * object, IStorageEventsCallback * callback) private
References CUDiskDevice::IsMounted(), CLog::Log(), LOGDBUS, LOGDEBUG, m_AvailableDevices, and CUDiskDevice::ToStorageDevice().
Referenced by PumpDriveChangeEvents().
Eject()
bool CUDisksProvider::Eject (const std::string & mountpath) override virtual
Implements IStorageProvider.
References CUDiskDevice::GetMountPoint(), m_AvailableDevices, URIUtils::RemoveSlashAtEnd(), and CUDiskDevice::UnMount().
EnumerateDisks()
std::vector< std::string > CUDisksProvider::EnumerateDisks () private
References CDBusMessage::SendSystem().
Referenced by Initialize().
GetDisks()
void CUDisksProvider::GetDisks (std::vector< CMediaSource > & devices, bool EnumerateRemovable) private
References CUDiskDevice::IsApproved(), CUDiskDevice::IsSystemInternal(), m_AvailableDevices, and CUDiskDevice::ToMediaShare().
Referenced by GetLocalDrives(), and GetRemovableDrives().
GetDiskUsage()
std::vector< std::string > CUDisksProvider::GetDiskUsage (void) override virtual
Implements IStorageProvider.
References CPosixMountProvider::GetDiskUsage().
GetLocalDrives()
void CUDisksProvider::GetLocalDrives (std::vector< CMediaSource > & localDrives) inline override virtual
Implements IStorageProvider.
References GetDisks().
GetRemovableDrives()
void CUDisksProvider::GetRemovableDrives (std::vector< CMediaSource > & removableDrives) inline override virtual
Implements IStorageProvider.
References GetDisks().
HasUDisks()
bool CUDisksProvider::HasUDisks () static
References CDBusUtil::TryMethodCall().
Referenced by CLinuxStorageProvider::CLinuxStorageProvider().
Initialize()
void CUDisksProvider::Initialize () override virtual
Implements IStorageProvider.
References DeviceAdded(), EnumerateDisks(), CDBusUtil::GetVariant(), CLog::Log(), LOGDEBUG, and m_DaemonVersion.
PumpDriveChangeEvents()
bool CUDisksProvider::PumpDriveChangeEvents (IStorageEventsCallback * callback) override virtual
Implements IStorageProvider.
References DeviceAdded(), DeviceChanged(), DeviceRemoved(), and m_connection.
Stop()
void CUDisksProvider::Stop () inline override virtual
Implements IStorageProvider.
Member Data Documentation
m_AvailableDevices
DeviceMap CUDisksProvider::m_AvailableDevices private
Referenced by DeviceAdded(), DeviceChanged(), DeviceRemoved(), Eject(), GetDisks(), and ~CUDisksProvider().
m_connection
CDBusConnection CUDisksProvider::m_connection private
Referenced by CUDisksProvider(), and PumpDriveChangeEvents().
m_DaemonVersion
int CUDisksProvider::m_DaemonVersion private
Referenced by Initialize().
The documentation for this class was generated from the following files:
UDisksProvider.h
UDisksProvider.cpp