Kodi Documentation: XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTvShowsOverview Class Reference
XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTvShowsOverview Class Reference
#include <DirectoryNodeTvShowsOverview.h>
Public Member Functions
CDirectoryNodeTvShowsOverview (const std::string &strName, CDirectoryNode *pParent)
Public Member Functions inherited from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode
virtual ~CDirectoryNode ()
NODE_TYPE GetType () const
bool GetChilds (CFileItemList &items)
void CollectQueryParams (CQueryParams &params) const
CDirectoryNode * GetParent () const
std::string BuildPath () const
virtual bool CanCache () const
Protected Member Functions
NODE_TYPE GetChildType () const override
bool GetContent (CFileItemList &items) const override
std::string GetLocalizedName () const override
Protected Member Functions inherited from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode
CDirectoryNode (NODE_TYPE Type, const std::string &strName, CDirectoryNode *pParent)
void AddOptions (const std::string &options)
const std::string & GetName () const
int GetID () const
void RemoveParent ()
Additional Inherited Members
Static Public Member Functions inherited from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode
static CDirectoryNode * ParseURL (const std::string &strPath)
static void GetDatabaseInfo (const std::string &strPath, CQueryParams &params)
Static Protected Member Functions inherited from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode
static CDirectoryNode * CreateNode (NODE_TYPE Type, const std::string &strName, CDirectoryNode *pParent)
Constructor & Destructor Documentation
CDirectoryNodeTvShowsOverview()
CDirectoryNodeTvShowsOverview::CDirectoryNodeTvShowsOverview (const std::string & strName, CDirectoryNode * pParent)
Member Function Documentation
GetChildType()
NODE_TYPE CDirectoryNodeTvShowsOverview::GetChildType () const override protected virtual
Reimplemented from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode.
References XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetName(), node, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_EPISODES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_NONE, and TvShowChildren.
GetContent()
bool CDirectoryNodeTvShowsOverview::GetContent (CFileItemList & items) const override protected virtual
Reimplemented from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode.
References CFileItemList::Add(), CDbUrl::AppendPath(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::BuildPath(), CDbUrl::FromString(), g_localizeStrings, CLocalizeStrings::Get(), node, CDbUrl::ToString(), and TvShowChildren.
GetLocalizedName()
std::string CDirectoryNodeTvShowsOverview::GetLocalizedName () const override protected virtual
Reimplemented from XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode.
References g_localizeStrings, CLocalizeStrings::Get(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetName(), node, and TvShowChildren.
The documentation for this class was generated from the following files:
DirectoryNodeTvShowsOverview.h
DirectoryNodeTvShowsOverview.cpp