Kodi Documentation: ADDON::CAddonStatusHandler Class Reference
ADDON::CAddonStatusHandler Class Reference
#include <AddonStatusHandler.h>
Public Member Functions
CAddonStatusHandler (const std::string &addonID, AddonInstanceId instanceId, ADDON_STATUS status, bool sameThread=true)
~CAddonStatusHandler () override
void Process () override
void OnStartup () override
void OnExit () override
Private Attributes
const uint32_t m_instanceId
AddonPtr m_addon
ADDON_STATUS m_status = ADDON_STATUS_UNKNOWN
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Static Private Attributes
static CCriticalSection m_critSection
Additional Inherited Members
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Detailed Description
Class - CAddonStatusHandler Used to inform the user about occurred errors and changes inside Add-on's, and ask him what to do. It can executed in the same thread as the calling function or in a separate thread.
Constructor & Destructor Documentation
CAddonStatusHandler()
ADDON::CAddonStatusHandler::CAddonStatusHandler (const std::string & addonID, AddonInstanceId instanceId, ADDON_STATUS status, bool sameThread = true)
Todo:
The status handled CAddonStatusHandler by is related to the class, not the instance having CAddonMgr construct an instance makes no sense
References ADDON::CHOICE_YES, CThread::Create(), CServiceBroker::GetAddonMgr(), CLog::Log(), LOGINFO, m_addon, m_instanceId, m_status, and Process().
~CAddonStatusHandler()
ADDON::CAddonStatusHandler::~CAddonStatusHandler () override
References CThread::StopThread().
Member Function Documentation
OnExit()
void ADDON::CAddonStatusHandler::OnExit () override virtual
Reimplemented from CThread.
OnStartup()
void ADDON::CAddonStatusHandler::OnStartup () override virtual
Reimplemented from CThread.
References LOWEST, and CThread::SetPriority().
Process()
void ADDON::CAddonStatusHandler::Process (void) override virtual
Todo:
Doesn't dialogaddonsettings save these automatically? It should do this.
Reimplemented from CThread.
References ADDON_STATUS_NEED_RESTART, ADDON_STATUS_NEED_SETTINGS, CServiceBroker::GetAddonMgr(), ADDON::CAddonMgr::GetCallbackForType(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CGUIDialogBoxBase::IsConfirmed(), m_addon, m_critSection, m_instanceId, m_status, CGUIDialog::Open(), ADDON::IAddonMgrCallback::RequestRestart(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), CGUIDialogAddonSettings::ShowForAddon(), KODI::MESSAGING::HELPERS::ShowOKDialogLines(), ADDON::CAddonInfo::TranslateType(), and WINDOW_DIALOG_YES_NO.
Referenced by CAddonStatusHandler().
Member Data Documentation
m_addon
AddonPtr ADDON::CAddonStatusHandler::m_addon private
Referenced by CAddonStatusHandler(), and Process().
m_critSection
CCriticalSection ADDON::CAddonStatusHandler::m_critSection static private
Referenced by Process().
m_instanceId
const uint32_t ADDON::CAddonStatusHandler::m_instanceId private
Referenced by CAddonStatusHandler(), and Process().
m_status
ADDON_STATUS ADDON::CAddonStatusHandler::m_status = ADDON_STATUS_UNKNOWN private
Referenced by CAddonStatusHandler(), and Process().
The documentation for this class was generated from the following files:
AddonStatusHandler.h
AddonStatusHandler.cpp