Kodi Documentation: OVERLAY::COverlayImageDX Class Reference
OVERLAY::COverlayImageDX Class Reference
#include <OverlayRendererDX.h>
Public Member Functions
COverlayImageDX (const CDVDOverlayImage &o, CRect &rSource)
Create the overlay for rendering.
COverlayImageDX (const CDVDOverlaySpu &o)
virtual ~COverlayImageDX ()
void Load (const uint32_t *rgba, int width, int height, int stride)
void Render (SRenderState &state)
Public Member Functions inherited from OVERLAY::COverlay
COverlay ()
virtual ~COverlay ()
Public Attributes
CD3DTexture m_texture
CD3DBuffer m_vertex
bool m_pma {false}
Public Attributes inherited from OVERLAY::COverlay
enum OVERLAY::COverlay::EType m_type
enum OVERLAY::COverlay::EAlign m_align
enum OVERLAY::COverlay::EPosition m_pos
float m_x {0}
float m_y {0}
float m_width {1.0f}
float m_height {1.0f}
float m_source_width {0}
float m_source_height {0}
Additional Inherited Members
Public Types inherited from OVERLAY::COverlay
enum EType { TYPE_NONE , TYPE_TEXTURE }
enum EAlign { ALIGN_SCREEN , ALIGN_SCREEN_AR , ALIGN_VIDEO , ALIGN_SUBTITLE }
enum EPosition { POSITION_ABSOLUTE , POSITION_ABSOLUTE_SCREEN , POSITION_RELATIVE }
Static Public Member Functions inherited from OVERLAY::COverlay
static std::shared_ptr< COverlay > Create (const CDVDOverlayImage &o, CRect &rSource)
static std::shared_ptr< COverlay > Create (const CDVDOverlaySpu &o)
static std::shared_ptr< COverlay > Create (ASS_Image *images, float width, float height)
Protected Member Functions inherited from OVERLAY::COverlay
bool IsSquareResolution (float resRatio)
Given the resolution ratio determines if it is a 4/3 resolution.
Constructor & Destructor Documentation
COverlayImageDX() [1/2]
COverlayImageDX::COverlayImageDX (const CDVDOverlayImage & o, CRect & rSource) explicit
Create the overlay for rendering.
Parameters
o The overlay image
rSource The video source rect size
References OVERLAY::COverlay::ALIGN_SCREEN_AR, OVERLAY::COverlay::ALIGN_VIDEO, OVERLAY::convert_rgba(), CDVDOverlayImage::height, CRectGen< T >::Height(), OVERLAY::COverlay::IsSquareResolution(), CDVDOverlayImage::linesize, Load(), OVERLAY::COverlay::m_align, OVERLAY::COverlay::m_height, m_pma, OVERLAY::COverlay::m_pos, OVERLAY::COverlay::m_source_height, OVERLAY::COverlay::m_source_width, OVERLAY::COverlay::m_width, OVERLAY::COverlay::m_x, OVERLAY::COverlay::m_y, CDVDOverlayImage::palette, CDVDOverlayImage::pixels, OVERLAY::COverlay::POSITION_ABSOLUTE, OVERLAY::COverlay::POSITION_RELATIVE, CDVDOverlayImage::source_height, CDVDOverlayImage::source_width, USE_PREMULTIPLIED_ALPHA, CDVDOverlayImage::width, CRectGen< T >::Width(), CDVDOverlayImage::x, and CDVDOverlayImage::y.
COverlayImageDX() [2/2]
COverlayImageDX::COverlayImageDX (const CDVDOverlaySpu & o) explicit
References OVERLAY::COverlay::ALIGN_VIDEO, OVERLAY::convert_rgba(), CDVDOverlaySpu::height, Load(), OVERLAY::COverlay::m_align, OVERLAY::COverlay::m_height, OVERLAY::COverlay::m_pos, OVERLAY::COverlay::m_width, OVERLAY::COverlay::m_x, OVERLAY::COverlay::m_y, OVERLAY::COverlay::POSITION_ABSOLUTE, USE_PREMULTIPLIED_ALPHA, CDVDOverlaySpu::width, CDVDOverlaySpu::x, and CDVDOverlaySpu::y.
~COverlayImageDX()
COverlayImageDX::~COverlayImageDX () virtual
Member Function Documentation
Load()
void COverlayImageDX::Load (const uint32_t * rgba, int width, int height, int stride)
References CD3DBuffer::Create(), LoadTexture(), CLog::Log(), LOGERROR, m_texture, m_vertex, Vertex::pos, CD3DTexture::Release(), and Vertex::texCoord.
Referenced by COverlayImageDX(), and COverlayImageDX().
Render()
void COverlayImageDX::Render (SRenderState & state) virtual
Implements OVERLAY::COverlay.
References CGUIShaderDX::Begin(), CGUIShaderDX::Draw(), DX::DeviceResources::Get(), CD3DBuffer::Get(), CD3DTexture::GetAddressOfSRV(), CD3DBuffer::GetStride(), CServiceBroker::GetWinSystem(), CGUIShaderDX::GetWVP(), OVERLAY::SRenderState::height, CRectGen< T >::Height(), OVERLAY::COverlay::m_pos, m_texture, m_vertex, OVERLAY::COverlay::POSITION_RELATIVE, RENDER_STEREO_MODE_SPLIT_HORIZONTAL, RENDER_STEREO_MODE_SPLIT_VERTICAL, CGUIShaderDX::RestoreBuffers(), CGUIShaderDX::SetShaderViews(), CGUIShaderDX::SetWorld(), CGUIShaderDX::SetWVP(), SHADER_METHOD_RENDER_TEXTURE_NOBLEND, OVERLAY::SRenderState::width, CRectGen< T >::Width(), OVERLAY::SRenderState::x, and OVERLAY::SRenderState::y.
Member Data Documentation
m_pma
bool OVERLAY::COverlayImageDX::m_pma {false}
Referenced by COverlayImageDX().
m_texture
CD3DTexture OVERLAY::COverlayImageDX::m_texture
Referenced by Load(), and Render().
m_vertex
CD3DBuffer OVERLAY::COverlayImageDX::m_vertex
Referenced by Load(), and Render().
The documentation for this class was generated from the following files:
OverlayRendererDX.h
OverlayRendererDX.cpp