Kodi Documentation: CECBuiltins.cpp File Reference
CECBuiltins.cpp File Reference
#include "CECBuiltins.h"
#include "ServiceBroker.h"
#include "messaging/ApplicationMessenger.h"
Functions
static int ActivateSource (const std::vector< std::string > &params)
Wake up device through CEC.
static int Standby (const std::vector< std::string > &params)
Put device in standby through CEC.
static int ToggleState (const std::vector< std::string > &params)
Toggle device state through CEC.
Function Documentation
ActivateSource()
static int ActivateSource (const std::vector< std::string > & params) static
Wake up device through CEC.
Parameters
params (ignored)
References CServiceBroker::GetAppMessenger(), and TMSG_CECACTIVATESOURCE.
Referenced by CCECBuiltins::GetOperations().
Standby()
static int Standby (const std::vector< std::string > & params) static
Put device in standby through CEC.
Parameters
params (ignored)
References CServiceBroker::GetAppMessenger(), and TMSG_CECSTANDBY.
Referenced by CCECBuiltins::GetOperations().
ToggleState()
static int ToggleState (const std::vector< std::string > & params) static
Toggle device state through CEC.
Parameters
params (ignored)
References CServiceBroker::GetAppMessenger(), and TMSG_CECTOGGLESTATE.
Referenced by CCECBuiltins::GetOperations().