Kodi Documentation: CDarwinEmbedKeyboard Class Reference
CDarwinEmbedKeyboard Class Reference
#include <DarwinEmbedKeyboard.h>
Public Member Functions
CDarwinEmbedKeyboard ()
bool ShowAndGetInput (char_callback_t pCallback, const std::string &initialString, std::string &typedString, const std::string &heading, bool bHiddenInput) override
each native keyboard needs to implement this function with the following behaviour:
void Cancel () override
This call should cancel a currently shown keyboard dialog. The implementation should return false from the modal ShowAndGetInput once anyone calls this method.
void fireCallback (const std::string &str)
void invalidateCallback ()
bool SetTextToKeyboard (const std::string &text, bool closeKeyboard=false) override
Public Member Functions inherited from CGUIKeyboard
CGUIKeyboard ()
~CGUIKeyboard () override=default
virtual int GetWindowId () const
void OnTimeout () override
void startAutoCloseTimer (unsigned int autoCloseMs)
void resetAutoCloseTimer ()
Public Member Functions inherited from ITimerCallback
virtual ~ITimerCallback ()=default
Static Public Member Functions
static bool hasExternalKeyboard ()
Private Attributes
char_callback_t m_pCharCallback = nullptr
bool m_canceled = false
std::unique_ptr< CDarwinEmbedKeyboardImpl > m_impl
Constructor & Destructor Documentation
CDarwinEmbedKeyboard()
CDarwinEmbedKeyboard::CDarwinEmbedKeyboard ()
Member Function Documentation
Cancel()
void CDarwinEmbedKeyboard::Cancel () override virtual
This call should cancel a currently shown keyboard dialog. The implementation should return false from the modal ShowAndGetInput once anyone calls this method.
Implements CGUIKeyboard.
References m_canceled.
fireCallback()
void CDarwinEmbedKeyboard::fireCallback (const std::string & str)
References m_pCharCallback.
hasExternalKeyboard()
bool CDarwinEmbedKeyboard::hasExternalKeyboard () static
References IS_IN_HARDWARE_KEYBOARD_MODE_SELECTOR, CLog::Log(), LOGDEBUG, LOGERROR, and SHARED_INSTANCE_SELECTOR.
Referenced by CGUIKeyboardFactory::ShowAndGetInput().
invalidateCallback()
void CDarwinEmbedKeyboard::invalidateCallback ()
References m_pCharCallback.
SetTextToKeyboard()
bool CDarwinEmbedKeyboard::SetTextToKeyboard (const std::string & text, bool closeKeyboard = false) override virtual
Reimplemented from CGUIKeyboard.
References m_impl, and text.
Referenced by ShowAndGetInput().
ShowAndGetInput()
bool CDarwinEmbedKeyboard::ShowAndGetInput (char_callback_t pCallback, const std::string & initialString, std::string & typedString, const std::string & heading, bool bHiddenInput) override virtual
each native keyboard needs to implement this function with the following behaviour:
Parameters
pCallback implementation should call this on each keypress with the current whole string
initialString implementation should show that initialstring
typedstring returns the typed string after close if return is true
heading implementation should show a heading (e.x. "search for a movie")
bHiddenInput if true the implementation should obfuscate the user input (e.x. by printing "*" for each char)
Returns
- true if typedstring is valid and user has confirmed input - false if typedstring is undefined and user canceled the input
Implements CGUIKeyboard.
References CDarwinEmbedKeyboardImpl::g_pKeyboard, g_xbmcController, m_canceled, m_impl, m_pCharCallback, SetTextToKeyboard(), and sleep().
Member Data Documentation
m_canceled
bool CDarwinEmbedKeyboard::m_canceled = false private
Referenced by Cancel(), and ShowAndGetInput().
m_impl
std::unique_ptr<CDarwinEmbedKeyboardImpl> CDarwinEmbedKeyboard::m_impl private
Referenced by SetTextToKeyboard(), and ShowAndGetInput().
m_pCharCallback
char_callback_t CDarwinEmbedKeyboard::m_pCharCallback = nullptr private
Referenced by fireCallback(), invalidateCallback(), and ShowAndGetInput().
The documentation for this class was generated from the following files:
DarwinEmbedKeyboard.h
DarwinEmbedKeyboard.mm