Kodi Documentation: PVR::CONTEXTMENUITEM Namespace Reference
PVR::CONTEXTMENUITEM Namespace Reference
Classes
class PVRClientMenuHook
Functions
DECL_STATICCONTEXTMENUITEM (PlayEpgTag)
DECL_CONTEXTMENUITEM (PlayEpgTagFromHere)
DECL_STATICCONTEXTMENUITEM (PlayRecording)
DECL_CONTEXTMENUITEM (ShowInformation)
DECL_STATICCONTEXTMENUITEM (ShowChannelGuide)
DECL_STATICCONTEXTMENUITEM (FindSimilar)
DECL_STATICCONTEXTMENUITEM (StartRecording)
DECL_STATICCONTEXTMENUITEM (StopRecording)
DECL_STATICCONTEXTMENUITEM (AddTimerRule)
DECL_CONTEXTMENUITEM (EditTimerRule)
DECL_STATICCONTEXTMENUITEM (DeleteTimerRule)
DECL_CONTEXTMENUITEM (EditTimer)
DECL_CONTEXTMENUITEM (DeleteTimer)
DECL_STATICCONTEXTMENUITEM (EditRecording)
DECL_CONTEXTMENUITEM (DeleteRecording)
DECL_STATICCONTEXTMENUITEM (UndeleteRecording)
DECL_STATICCONTEXTMENUITEM (DeleteWatchedRecordings)
DECL_CONTEXTMENUITEM (ToggleTimerState)
DECL_STATICCONTEXTMENUITEM (AddReminder)
DECL_STATICCONTEXTMENUITEM (ExecuteSearch)
DECL_STATICCONTEXTMENUITEM (EditSearch)
DECL_STATICCONTEXTMENUITEM (RenameSearch)
DECL_STATICCONTEXTMENUITEM (ChooseIconForSearch)
DECL_STATICCONTEXTMENUITEM (DuplicateSearch)
DECL_STATICCONTEXTMENUITEM (DeleteSearch)
std::shared_ptr< CPVRTimerInfoTag > GetTimerInfoTagFromItem (const CFileItem &item)
Function Documentation
DECL_CONTEXTMENUITEM() [1/7]
PVR::CONTEXTMENUITEM::DECL_CONTEXTMENUITEM (DeleteRecording)
DECL_CONTEXTMENUITEM() [2/7]
PVR::CONTEXTMENUITEM::DECL_CONTEXTMENUITEM (DeleteTimer)
DECL_CONTEXTMENUITEM() [3/7]
PVR::CONTEXTMENUITEM::DECL_CONTEXTMENUITEM (EditTimer)
DECL_CONTEXTMENUITEM() [4/7]
PVR::CONTEXTMENUITEM::DECL_CONTEXTMENUITEM (EditTimerRule)
DECL_CONTEXTMENUITEM() [5/7]
PVR::CONTEXTMENUITEM::DECL_CONTEXTMENUITEM (PlayEpgTagFromHere)
DECL_CONTEXTMENUITEM() [6/7]
PVR::CONTEXTMENUITEM::DECL_CONTEXTMENUITEM (ShowInformation)
DECL_CONTEXTMENUITEM() [7/7]
PVR::CONTEXTMENUITEM::DECL_CONTEXTMENUITEM (ToggleTimerState)
DECL_STATICCONTEXTMENUITEM() [1/18]
PVR::CONTEXTMENUITEM::DECL_STATICCONTEXTMENUITEM (AddReminder)
DECL_STATICCONTEXTMENUITEM() [2/18]
PVR::CONTEXTMENUITEM::DECL_STATICCONTEXTMENUITEM (AddTimerRule)
DECL_STATICCONTEXTMENUITEM() [3/18]
PVR::CONTEXTMENUITEM::DECL_STATICCONTEXTMENUITEM (ChooseIconForSearch)
DECL_STATICCONTEXTMENUITEM() [4/18]
PVR::CONTEXTMENUITEM::DECL_STATICCONTEXTMENUITEM (DeleteSearch)
DECL_STATICCONTEXTMENUITEM() [5/18]
PVR::CONTEXTMENUITEM::DECL_STATICCONTEXTMENUITEM (DeleteTimerRule)
DECL_STATICCONTEXTMENUITEM() [6/18]
PVR::CONTEXTMENUITEM::DECL_STATICCONTEXTMENUITEM (DeleteWatchedRecordings)
DECL_STATICCONTEXTMENUITEM() [7/18]
PVR::CONTEXTMENUITEM::DECL_STATICCONTEXTMENUITEM (DuplicateSearch)
DECL_STATICCONTEXTMENUITEM() [8/18]
PVR::CONTEXTMENUITEM::DECL_STATICCONTEXTMENUITEM (EditRecording)
DECL_STATICCONTEXTMENUITEM() [9/18]
PVR::CONTEXTMENUITEM::DECL_STATICCONTEXTMENUITEM (EditSearch)
DECL_STATICCONTEXTMENUITEM() [10/18]
PVR::CONTEXTMENUITEM::DECL_STATICCONTEXTMENUITEM (ExecuteSearch)
DECL_STATICCONTEXTMENUITEM() [11/18]
PVR::CONTEXTMENUITEM::DECL_STATICCONTEXTMENUITEM (FindSimilar)
DECL_STATICCONTEXTMENUITEM() [12/18]
PVR::CONTEXTMENUITEM::DECL_STATICCONTEXTMENUITEM (PlayEpgTag)
DECL_STATICCONTEXTMENUITEM() [13/18]
PVR::CONTEXTMENUITEM::DECL_STATICCONTEXTMENUITEM (PlayRecording)
DECL_STATICCONTEXTMENUITEM() [14/18]
PVR::CONTEXTMENUITEM::DECL_STATICCONTEXTMENUITEM (RenameSearch)
DECL_STATICCONTEXTMENUITEM() [15/18]
PVR::CONTEXTMENUITEM::DECL_STATICCONTEXTMENUITEM (ShowChannelGuide)
DECL_STATICCONTEXTMENUITEM() [16/18]
PVR::CONTEXTMENUITEM::DECL_STATICCONTEXTMENUITEM (StartRecording)
DECL_STATICCONTEXTMENUITEM() [17/18]
PVR::CONTEXTMENUITEM::DECL_STATICCONTEXTMENUITEM (StopRecording)
DECL_STATICCONTEXTMENUITEM() [18/18]
PVR::CONTEXTMENUITEM::DECL_STATICCONTEXTMENUITEM (UndeleteRecording)
GetTimerInfoTagFromItem()
std::shared_ptr< CPVRTimerInfoTag > PVR::CONTEXTMENUITEM::GetTimerInfoTagFromItem (const CFileItem & item)
References CFileItem::GetEPGInfoTag(), CServiceBroker::GetPVRManager(), CFileItem::GetPVRTimerInfoTag(), and PVR::CPVRManager::Timers().