Kodi Documentation: CRendererMediaCodecSurface Class Reference
CRendererMediaCodecSurface Class Reference
#include <RendererMediaCodecSurface.h>
Classes
struct BUFFER
Public Member Functions
CRendererMediaCodecSurface ()
~CRendererMediaCodecSurface () override
bool RenderCapture (int index, CRenderCapture *capture) override
void AddVideoPicture (const VideoPicture &picture, int index) override
void ReleaseBuffer (int idx) override
bool Configure (const VideoPicture &picture, float fps, unsigned int orientation) override
bool IsConfigured () override
bool ConfigChanged (const VideoPicture &picture) override
CRenderInfo GetRenderInfo () override
void UnInit () override
void Update () override
void RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha) override
bool SupportsMultiPassRendering () override
bool IsGuiLayer () override
bool Supports (ESCALINGMETHOD method) const override
bool Supports (ERENDERFEATURE feature) const override
Public Member Functions inherited from CBaseRenderer
CBaseRenderer ()
virtual ~CBaseRenderer ()
virtual bool IsPictureHW (const VideoPicture &picture)
virtual bool Flush (bool saveBuffers)
virtual void SetBufferSize (int numBuffers)
virtual bool NeedBuffer (int idx)
virtual bool WantsDoublePass ()
void SetViewMode (int viewMode)
void GetVideoRect (CRect &source, CRect &dest, CRect &view) const
Get video rectangle and view window.
float GetAspectRatio () const
unsigned int GetOrientation () const
void SetVideoSettings (const CVideoSettings &settings)
virtual DEBUG_INFO_VIDEO GetDebugInfo (int idx)
virtual CRenderCapture * GetRenderCapture ()
Static Public Member Functions
static CBaseRenderer * Create (CVideoBuffer *buffer)
static bool Register ()
Static Public Member Functions inherited from CBaseRenderer
static void SettingOptionsRenderMethodsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< IntegerSettingOption > &list, int &current, void *data)
Protected Member Functions
void ReorderDrawPoints () override
Protected Member Functions inherited from CBaseRenderer
void CalcDestRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift, CRect &destRect)
void CalcNormalRenderRect (float offsetX, float offsetY, float width, float height, float inputFrameRatio, float zoomAmount, float verticalShift)
void CalculateFrameAspectRatio (unsigned int desired_width, unsigned int desired_height)
virtual void ManageRenderArea ()
virtual EShaderFormat GetShaderFormat ()
void MarkDirty ()
void EnableAlwaysClip ()
void saveRotatedCoords ()
void syncDestRectToRotatedPoints ()
void restoreRotatedCoords ()
Private Member Functions
void Reset ()
void ReleaseVideoBuffer (int idx, bool render)
Private Attributes
bool m_bConfigured = false
CRect m_surfDestRect
int m_lastIndex = -1
struct CRendererMediaCodecSurface::BUFFER m_buffers [4]
Additional Inherited Members
Protected Attributes inherited from CBaseRenderer
unsigned int m_sourceWidth = 720
unsigned int m_sourceHeight = 480
float m_sourceFrameRatio = 1.0f
float m_fps = 0.0f
unsigned int m_renderOrientation = 0
CPoint m_rotatedDestCoords [4]
CPoint m_savedRotatedDestCoords [4]
CRect m_destRect
CRect m_sourceRect
CRect m_viewRect
unsigned m_iFlags = 0
AVPixelFormat m_format = AV_PIX_FMT_NONE
CVideoSettings m_videoSettings
Constructor & Destructor Documentation
CRendererMediaCodecSurface()
CRendererMediaCodecSurface::CRendererMediaCodecSurface ()
References CLog::Log(), and LOGINFO.
Referenced by Create().
~CRendererMediaCodecSurface()
CRendererMediaCodecSurface::~CRendererMediaCodecSurface () override
References Reset().
Member Function Documentation
AddVideoPicture()
void CRendererMediaCodecSurface::AddVideoPicture (const VideoPicture & picture, int index) override virtual
Implements CBaseRenderer.
References CVideoBuffer::Acquire(), index(), m_buffers, ReleaseBuffer(), VideoPicture::videoBuffer, and CRendererMediaCodecSurface::BUFFER::videoBuffer.
ConfigChanged()
bool CRendererMediaCodecSurface::ConfigChanged (const VideoPicture & picture) inline override virtual
Implements CBaseRenderer.
Configure()
bool CRendererMediaCodecSurface::Configure (const VideoPicture & picture, float fps, unsigned int orientation) override virtual
Implements CBaseRenderer.
References CBaseRenderer::CalculateFrameAspectRatio(), VideoPicture::chroma_position, VideoPicture::color_primaries, VideoPicture::color_space, VideoPicture::color_transfer, GetFlagsChromaPosition(), GetFlagsColorMatrix(), GetFlagsColorPrimaries(), GetFlagsStereoMode(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), HDR_TYPE_DOLBYVISION, VideoPicture::hdrType, VideoPicture::iDisplayHeight, VideoPicture::iDisplayWidth, VideoPicture::iHeight, VideoPicture::iWidth, CLog::Log(), LOGINFO, CBaseRenderer::m_iFlags, CBaseRenderer::m_renderOrientation, CBaseRenderer::m_sourceHeight, CBaseRenderer::m_sourceWidth, CBaseRenderer::m_videoSettings, CVideoSettings::m_ViewMode, CGraphicContext::SetTransferPQ(), CBaseRenderer::SetViewMode(), and VideoPicture::stereoMode.
Create()
CBaseRenderer * CRendererMediaCodecSurface::Create (CVideoBuffer * buffer) static
References CRendererMediaCodecSurface().
Referenced by Register().
GetRenderInfo()
CRenderInfo CRendererMediaCodecSurface::GetRenderInfo () override virtual
Reimplemented from CBaseRenderer.
References CRenderInfo::max_buffer_size.
IsConfigured()
bool CRendererMediaCodecSurface::IsConfigured () inline override virtual
Implements CBaseRenderer.
References m_bConfigured.
IsGuiLayer()
bool CRendererMediaCodecSurface::IsGuiLayer () inline override virtual
Reimplemented from CBaseRenderer.
Register()
bool CRendererMediaCodecSurface::Register () static
References Create(), and VIDEOPLAYER::CRendererFactory::RegisterRenderer().
Referenced by CWinSystemAndroid::InitWindowSystem().
ReleaseBuffer()
void CRendererMediaCodecSurface::ReleaseBuffer (int idx) override virtual
Reimplemented from CBaseRenderer.
References ReleaseVideoBuffer().
Referenced by AddVideoPicture().
ReleaseVideoBuffer()
void CRendererMediaCodecSurface::ReleaseVideoBuffer (int idx, bool render) private
References CXBMCApp::Get(), m_bConfigured, m_buffers, m_surfDestRect, CVideoBuffer::Release(), CMediaCodecVideoBuffer::ReleaseOutputBuffer(), CMediaCodecVideoBuffer::RenderUpdate(), and CRendererMediaCodecSurface::BUFFER::videoBuffer.
Referenced by ReleaseBuffer(), RenderUpdate(), and Reset().
RenderCapture()
bool CRendererMediaCodecSurface::RenderCapture (int index, CRenderCapture * capture) override virtual
Implements CBaseRenderer.
References CRenderCapture::BeginRender(), and CRenderCapture::EndRender().
RenderUpdate()
void CRendererMediaCodecSurface::RenderUpdate (int index, int index2, bool clear, unsigned int flags, unsigned int alpha) override virtual
Implements CBaseRenderer.
References CONF_FLAGS_STEREO_MODE_MASK, CONF_FLAGS_STEREO_MODE_TAB, CWinSystemBase::GetGfxContext(), CGraphicContext::GetStereoMode(), CServiceBroker::GetWinSystem(), index(), m_bConfigured, CBaseRenderer::m_destRect, CBaseRenderer::m_iFlags, m_lastIndex, m_surfDestRect, CBaseRenderer::ManageRenderArea(), ReleaseVideoBuffer(), RENDER_STEREO_MODE_MONO, RENDER_STEREO_MODE_SPLIT_HORIZONTAL, RENDER_STEREO_MODE_SPLIT_VERTICAL, RENDER_STEREO_VIEW_LEFT, RENDER_STEREO_VIEW_OFF, CGraphicContext::SetStereoView(), CRectGen< T >::x2, and CRectGen< T >::y2.
ReorderDrawPoints()
void CRendererMediaCodecSurface::ReorderDrawPoints () override protected virtual
Reimplemented from CBaseRenderer.
References CRectGen< T >::Height(), CBaseRenderer::m_renderOrientation, m_surfDestRect, CBaseRenderer::ReorderDrawPoints(), CRectGen< T >::Width(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Reset()
void CRendererMediaCodecSurface::Reset () private
References CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), m_lastIndex, ReleaseVideoBuffer(), and CGraphicContext::SetTransferPQ().
Referenced by ~CRendererMediaCodecSurface().
Supports() [1/2]
bool CRendererMediaCodecSurface::Supports (ERENDERFEATURE feature) const override virtual
Reimplemented from CBaseRenderer.
References RENDERFEATURE_PIXEL_RATIO, RENDERFEATURE_ROTATION, RENDERFEATURE_STRETCH, RENDERFEATURE_VERTICAL_SHIFT, and RENDERFEATURE_ZOOM.
Supports() [2/2]
bool CRendererMediaCodecSurface::Supports (ESCALINGMETHOD method) const inline override virtual
Implements CBaseRenderer.
SupportsMultiPassRendering()
bool CRendererMediaCodecSurface::SupportsMultiPassRendering () inline override virtual
Implements CBaseRenderer.
UnInit()
void CRendererMediaCodecSurface::UnInit () inline override virtual
Implements CBaseRenderer.
Update()
void CRendererMediaCodecSurface::Update () inline override virtual
Implements CBaseRenderer.
Member Data Documentation
m_bConfigured
bool CRendererMediaCodecSurface::m_bConfigured = false private
Referenced by IsConfigured(), ReleaseVideoBuffer(), and RenderUpdate().
m_buffers
struct CRendererMediaCodecSurface::BUFFER CRendererMediaCodecSurface::m_buffers[4] private
Referenced by AddVideoPicture(), and ReleaseVideoBuffer().
m_lastIndex
int CRendererMediaCodecSurface::m_lastIndex = -1 private
Referenced by RenderUpdate(), and Reset().
m_surfDestRect
CRect CRendererMediaCodecSurface::m_surfDestRect private
Referenced by ReleaseVideoBuffer(), RenderUpdate(), and ReorderDrawPoints().
The documentation for this class was generated from the following files:
RendererMediaCodecSurface.h
RendererMediaCodecSurface.cpp