var _directory_node_album_recently_added_8h =
[
    [ "XFILE::MUSICDATABASEDIRECTORY::CDirectoryNodeAlbumRecentlyAdded", "d7/da1/class_x_f_i_l_e_1_1_m_u_s_i_c_d_a_t_a_b_a_s_e_d_i_r_e_c_t_o_r_y_1_1_c_directory_node_album_recently_added.html", "d7/da1/class_x_f_i_l_e_1_1_m_u_s_i_c_d_a_t_a_b_a_s_e_d_i_r_e_c_t_o_r_y_1_1_c_directory_node_album_recently_added" ]
];