Kodi Documentation: KODI::GAME::CGameClientMouse Class Reference
KODI::GAME::CGameClientMouse Class Reference
Games
Handles mouse events for games.
#include <GameClientMouse.h>
Public Member Functions
CGameClientMouse (CGameClient &gameClient, std::string controllerId, MOUSE::IMouseInputProvider *inputProvider)
Constructor registers for mouse events at CInputManager.
~CGameClientMouse () override
Destructor unregisters from mouse events from CInputManager.
std::string ControllerID () const override
The controller profile for this mouse input handler.
bool OnMotion (const std::string &relpointer, int dx, int dy) override
A relative pointer has moved.
bool OnButtonPress (const std::string &button) override
A mouse button has been pressed.
void OnButtonRelease (const std::string &button) override
A mouse button has been released.
void OnInputFrame () override
Called at the end of the frame that provided input.
const std::string & GetControllerID () const
const PERIPHERALS::PeripheralPtr & GetSource () const
float GetActivation () const
void SetSource (PERIPHERALS::PeripheralPtr sourcePeripheral)
void ClearSource ()
Public Member Functions inherited from KODI::MOUSE::IMouseInputHandler
virtual ~IMouseInputHandler (void)=default
Private Attributes
CGameClient & m_gameClient
const std::string m_controllerId
MOUSE::IMouseInputProvider *const m_inputProvider
PERIPHERALS::PeripheralPtr m_sourcePeripheral
std::unique_ptr< CControllerActivity > m_mouseActivity
Detailed Description
Handles mouse events for games.
Listens to mouse events and forwards them to the games (as game_input_event).
Constructor & Destructor Documentation
CGameClientMouse()
CGameClientMouse::CGameClientMouse (CGameClient & gameClient, std::string controllerId, MOUSE::IMouseInputProvider * inputProvider)
Constructor registers for mouse events at CInputManager.
Parameters
gameClient The game client implementation.
controllerId The controller profile used for input
dllStruct The emulator or game to which the events are sent.
inputProvider The interface providing us with mouse input.
References KODI::MOUSE::IMouseInputProvider::RegisterMouseHandler().
~CGameClientMouse()
CGameClientMouse::~CGameClientMouse () override
Destructor unregisters from mouse events from CInputManager.
References m_inputProvider, and KODI::MOUSE::IMouseInputProvider::UnregisterMouseHandler().
Member Function Documentation
ClearSource()
void CGameClientMouse::ClearSource ()
References m_sourcePeripheral.
ControllerID()
std::string CGameClientMouse::ControllerID () const override virtual
The controller profile for this mouse input handler.
Returns
The ID of the add-on extending kodi.game.controller
Implements KODI::MOUSE::IMouseInputHandler.
References m_controllerId.
Referenced by OnMotion().
GetActivation()
float CGameClientMouse::GetActivation () const
References m_mouseActivity.
GetControllerID()
const std::string & KODI::GAME::CGameClientMouse::GetControllerID () const inline
References m_controllerId.
GetSource()
const PERIPHERALS::PeripheralPtr & KODI::GAME::CGameClientMouse::GetSource () const inline
References m_sourcePeripheral.
OnButtonPress()
bool CGameClientMouse::OnButtonPress (const std::string & button) override virtual
A mouse button has been pressed.
Parameters
button The name of the feature being pressed
Returns
True if the event was handled, otherwise false
Implements KODI::MOUSE::IMouseInputHandler.
References KODI::GAME::CGameClientInput::AcceptsInput(), GAME_INPUT_EVENT_DIGITAL_BUTTON, GAME_PORT_MOUSE, KODI::GAME::CGameClient::Input(), KODI::GAME::CGameClientInput::InputEvent(), m_controllerId, m_gameClient, m_mouseActivity, MOUSE_PORT_ADDRESS, and game_input_event::type.
OnButtonRelease()
void CGameClientMouse::OnButtonRelease (const std::string & button) override virtual
A mouse button has been released.
Parameters
button The name of the feature being released
Implements KODI::MOUSE::IMouseInputHandler.
References GAME_INPUT_EVENT_DIGITAL_BUTTON, GAME_PORT_MOUSE, KODI::GAME::CGameClient::Input(), KODI::GAME::CGameClientInput::InputEvent(), m_controllerId, m_gameClient, m_mouseActivity, MOUSE_PORT_ADDRESS, and game_input_event::type.
OnInputFrame()
void CGameClientMouse::OnInputFrame () override virtual
Called at the end of the frame that provided input.
This can be as a result of a pointer update, a button press, or a button release. All three events will result in a call to OnInputFrame().
Implements KODI::MOUSE::IMouseInputHandler.
References m_mouseActivity.
OnMotion()
bool CGameClientMouse::OnMotion (const std::string & relpointer, int dx, int dy) override virtual
A relative pointer has moved.
Parameters
relpointer The name of the relative pointer being moved
dx The relative x coordinate of motion
dy The relative y coordinate of motion
The mouse uses a left-handed (graphics) cartesian coordinate system. Positive X is right, positive Y is down.
Returns
True if the event was handled, otherwise false
Todo:
Allow mouse motion to activate controller This will follow a larger refactoring of the mouse input system
Implements KODI::MOUSE::IMouseInputHandler.
References KODI::GAME::CGameClientInput::AcceptsInput(), ControllerID(), GAME_INPUT_EVENT_RELATIVE_POINTER, GAME_PORT_MOUSE, KODI::GAME::CGameClient::Input(), KODI::GAME::CGameClientInput::InputEvent(), m_controllerId, m_gameClient, MOUSE_PORT_ADDRESS, and game_input_event::type.
SetSource()
void CGameClientMouse::SetSource (PERIPHERALS::PeripheralPtr sourcePeripheral)
References m_sourcePeripheral.
Member Data Documentation
m_controllerId
const std::string KODI::GAME::CGameClientMouse::m_controllerId private
Referenced by ControllerID(), GetControllerID(), OnButtonPress(), OnButtonRelease(), and OnMotion().
m_gameClient
CGameClient& KODI::GAME::CGameClientMouse::m_gameClient private
Referenced by OnButtonPress(), OnButtonRelease(), and OnMotion().
m_inputProvider
MOUSE::IMouseInputProvider* const KODI::GAME::CGameClientMouse::m_inputProvider private
Referenced by ~CGameClientMouse().
m_mouseActivity
std::unique_ptr<CControllerActivity> KODI::GAME::CGameClientMouse::m_mouseActivity private
Referenced by GetActivation(), OnButtonPress(), OnButtonRelease(), and OnInputFrame().
m_sourcePeripheral
PERIPHERALS::PeripheralPtr KODI::GAME::CGameClientMouse::m_sourcePeripheral private
Referenced by ClearSource(), GetSource(), and SetSource().
The documentation for this class was generated from the following files:
GameClientMouse.h
GameClientMouse.cpp