Kodi Documentation: CMusicLibraryQueue Class Reference
CMusicLibraryQueue Class Reference
Queue for music library jobs.
#include <MusicLibraryQueue.h>
Public Member Functions
~CMusicLibraryQueue () override
void ExportLibrary (const CLibExportSettings &settings, bool showDialog=false)
Enqueue a music library export job.
void ImportLibrary (const std::string &xmlFile, bool showDialog=false)
Enqueue a music library import job.
void ScanLibrary (const std::string &strDirectory, int flags=0, bool showProgress=true)
Enqueue a music library update job, scanning tags embedded in music files and optionally scraping additional data.
void StartAlbumScan (const std::string &strDirectory, bool refresh=false)
Enqueue an album scraping job fetching additional album data.
void StartArtistScan (const std::string &strDirectory, bool refresh=false)
Enqueue an artist scraping job fetching additional artist data.
bool IsScanningLibrary () const
Check if a library scan or cleaning is in progress.
void StopLibraryScanning ()
Stop and dequeue all scanning jobs.
void CleanLibrary (bool showDialog=false)
Enqueue an asynchronous library cleaning job.
void AddJob (CMusicLibraryJob *job)
Adds the given job to the queue.
void CancelJob (CMusicLibraryJob *job)
Cancels the given job and removes it from the queue.
void CancelAllJobs ()
Cancels all running and queued jobs.
bool IsRunning () const
Whether any jobs are running or not.
Static Public Member Functions
static CMusicLibraryQueue & GetInstance ()
Gets the singleton instance of the music library queue.
Protected Member Functions
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
void Refresh ()
Notifies all to refresh the current listings.
Protected Member Functions inherited from CJobQueue
bool QueueEmpty () const
Returns if we still have jobs waiting to be processed NOTE: This function does not take into account the jobs that are currently processing.
CJobQueue (bool lifo=false, unsigned int jobsAtOnce=1, CJob::PRIORITY priority=CJob::PRIORITY_LOW)
CJobQueue constructor.
~CJobQueue () override
CJobQueue destructor Cancels any in-process jobs, and destroys the job queue.
bool AddJob (CJob *job)
Add a job to the queue On completion of the job, destruction of the job queue or in case the job could not be added successfully, the CJob object will be destroyed.
template<typename F >
void Submit (F &&f)
Add a function f to this job queue.
void CancelJob (const CJob *job)
Cancel a job in the queue Cancels a job in the queue. Any job currently being processed may complete after this call has completed, but OnJobComplete will not be performed. If the job is only queued then it will be removed from the queue and deleted.
void CancelJobs ()
Cancel all jobs in the queue Removes all jobs from the queue. Any job currently being processed may complete after this call has completed, but OnJobComplete will not be performed.
bool IsProcessing () const
Check whether the queue is processing a job.
void OnJobAbort (unsigned int jobID, CJob *job) override
The callback used when a job will be aborted.
Protected Member Functions inherited from IJobCallback
virtual ~IJobCallback ()=default
Destructor for job call back objects.
virtual void OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob *job)
An optional callback function that a job may call while processing.
Private Types
typedef std::set< CMusicLibraryJob * > MusicLibraryJobs
typedef std::map< std::string, MusicLibraryJobs > MusicLibraryJobMap
Private Member Functions
CMusicLibraryQueue ()
CMusicLibraryQueue (const CMusicLibraryQueue &)
CMusicLibraryQueue const & operator= (CMusicLibraryQueue const &)
Private Attributes
MusicLibraryJobMap m_jobs
CCriticalSection m_critical
bool m_modal = false
bool m_cleaning = false
Detailed Description
Queue for music library jobs.
The queue can only process a single job at any time and every job will be executed at the lowest priority.
Member Typedef Documentation
MusicLibraryJobMap
typedef std::map<std::string, MusicLibraryJobs> CMusicLibraryQueue::MusicLibraryJobMap private
MusicLibraryJobs
typedef std::set<CMusicLibraryJob*> CMusicLibraryQueue::MusicLibraryJobs private
Constructor & Destructor Documentation
~CMusicLibraryQueue()
CMusicLibraryQueue::~CMusicLibraryQueue () override
References m_critical, and m_jobs.
CMusicLibraryQueue() [1/2]
CMusicLibraryQueue::CMusicLibraryQueue () private
CMusicLibraryQueue() [2/2]
CMusicLibraryQueue::CMusicLibraryQueue (const CMusicLibraryQueue &) private
Member Function Documentation
AddJob()
void CMusicLibraryQueue::AddJob (CMusicLibraryJob * job)
Adds the given job to the queue.
Parameters
[in] job Music library job to be queued.
References CJobQueue::AddJob(), CMusicLibraryJob::GetType(), m_critical, and m_jobs.
Referenced by CleanLibrary(), ExportLibrary(), ImportLibrary(), ScanLibrary(), StartAlbumScan(), and StartArtistScan().
CancelAllJobs()
void CMusicLibraryQueue::CancelAllJobs ()
Cancels all running and queued jobs.
References CJobQueue::CancelJobs(), m_critical, and m_jobs.
Referenced by CApplication::Stop().
CancelJob()
void CMusicLibraryQueue::CancelJob (CMusicLibraryJob * job)
Cancels the given job and removes it from the queue.
Parameters
[in] job Music library job to be canceled and removed from the queue.
References CMusicLibraryJob::CanBeCancelled(), CMusicLibraryJob::Cancel(), CJobQueue::CancelJob(), CMusicLibraryJob::GetType(), m_critical, and m_jobs.
Referenced by StopLibraryScanning().
CleanLibrary()
void CMusicLibraryQueue::CleanLibrary (bool showDialog = false)
Enqueue an asynchronous library cleaning job.
Parameters
[in] showDialog Show a model progress dialog while cleaning. Default is false.
References AddJob(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CGUIDialogProgress::Open(), CGUIDialogBoxBase::SetHeading(), CGUIDialogProgress::SetPercentage(), CGUIDialogProgress::ShowProgressBar(), CGUIDialogProgress::Wait(), and WINDOW_DIALOG_PROGRESS.
Referenced by CleanLibrary(), CMediaSettings::OnSettingAction(), and MUSIC_INFO::CMusicInfoScanner::Process().
ExportLibrary()
void CMusicLibraryQueue::ExportLibrary (const CLibExportSettings & settings, bool showDialog = false)
Enqueue a music library export job.
Parameters
[in] settings Library export settings
[in] showDialog Show a progress dialog while (asynchronously) exporting, otherwise export in synchronous
References AddJob(), CMusicLibraryProgressJob::DoWork(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), m_modal, CGUIDialogProgress::Open(), Refresh(), CGUIDialogBoxBase::SetHeading(), CGUIDialogProgress::SetPercentage(), CGUIDialogBoxBase::SetText(), CGUIDialogProgress::ShowProgressBar(), CGUIDialogProgress::Wait(), and WINDOW_DIALOG_PROGRESS.
Referenced by ExportLibrary(), ExportLibrary2(), and CMediaSettings::OnSettingAction().
GetInstance()
CMusicLibraryQueue & CMusicLibraryQueue::GetInstance () static
Gets the singleton instance of the music library queue.
Referenced by AnnounceRemove(), AnnounceUpdate(), CApplicationPowerHandling::CheckShutdown(), CMusicDatabase::Clean(), CleanLibrary(), CGUIWindowMusicBase::DoScan(), ExportLibrary(), ExportLibrary2(), KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool(), CProfileManager::LogOff(), CGUIWindowMusicBase::OnAssignContent(), CGUIWindowMusicBase::OnBack(), CGUIWindowMusicBase::OnContextButton(), CGUIWindowMusicBase::OnInitWindow(), CGUIWindowMusicBase::OnItemInfoAll(), KODI::CDRIP::CCDDARipper::OnJobComplete(), CGUIWindowMusicNav::OnMessage(), CMediaSettings::OnSettingAction(), MUSIC_INFO::CMusicInfoScanner::Process(), JSONRPC::CAudioLibrary::RefreshAlbum(), JSONRPC::CAudioLibrary::RefreshArtist(), CGUIDialogMusicInfo::RefreshInfo(), CApplication::Stop(), CGUIWindowMusicBase::UpdateButtons(), CApplication::UpdateLibraries(), and UpdateLibrary().
ImportLibrary()
void CMusicLibraryQueue::ImportLibrary (const std::string & xmlFile, bool showDialog = false)
Enqueue a music library import job.
Parameters
[in] xmlFile xml file to import
[in] showDialog Show a progress dialog while (asynchronously) exporting, otherwise export in synchronous
References AddJob(), CMusicLibraryProgressJob::DoWork(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), m_modal, CGUIDialogProgress::Open(), Refresh(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), CGUIDialogProgress::SetPercentage(), CGUIDialogBoxBase::SetText(), CGUIDialogProgress::ShowProgressBar(), CGUIDialogProgress::Wait(), and WINDOW_DIALOG_PROGRESS.
Referenced by CMediaSettings::OnSettingAction().
IsRunning()
bool CMusicLibraryQueue::IsRunning () const
Whether any jobs are running or not.
References CJobQueue::IsProcessing(), and m_modal.
Referenced by CApplicationPowerHandling::CheckShutdown().
IsScanningLibrary()
bool CMusicLibraryQueue::IsScanningLibrary () const
Check if a library scan or cleaning is in progress.
Returns
True if a scan or clean is in progress, false otherwise
References m_cleaning, and m_jobs.
Referenced by KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool().
OnJobComplete()
void CMusicLibraryQueue::OnJobComplete (unsigned int jobID, bool success, CJob * job) override protected virtual
The callback used when a job completes.
CJobQueue implementation will cleanup the internal processing queue and then queue the next job at the job manager, if any.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
success the result from the DoWork call
job the job that has been processed.
See also
CJobManager, IJobCallback and CJob
Reimplemented from CJobQueue.
References CJob::GetType(), m_critical, m_jobs, CJobQueue::OnJobComplete(), CJobQueue::QueueEmpty(), Refresh(), and success.
operator=()
CMusicLibraryQueue const & CMusicLibraryQueue::operator= (CMusicLibraryQueue const &) private
Refresh()
void CMusicLibraryQueue::Refresh () protected
Notifies all to refresh the current listings.
References CUtil::DeleteMusicDatabaseDirectoryCache(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, and GUI_MSG_UPDATE.
Referenced by ExportLibrary(), ImportLibrary(), OnJobComplete(), and StopLibraryScanning().
ScanLibrary()
void CMusicLibraryQueue::ScanLibrary (const std::string & strDirectory, int flags = 0, bool showProgress = true)
Enqueue a music library update job, scanning tags embedded in music files and optionally scraping additional data.
Parameters
[in] strDirectory Directory to scan or "" (empty string) for a global scan.
[in] flags Flags for controlling the scanning process. See xbmc/music/infoscanner/MusicInfoScanner.h for possible values.
[in] showProgress Whether or not to show a progress dialog. Defaults to true
References AddJob(), CServiceBroker::GetSettingsComponent(), MUSIC_INFO::CMusicInfoScanner::SCAN_BACKGROUND, MUSIC_INFO::CMusicInfoScanner::SCAN_NORMAL, MUSIC_INFO::CMusicInfoScanner::SCAN_ONLINE, CSettings::SETTING_MUSICLIBRARY_BACKGROUNDUPDATE, and CSettings::SETTING_MUSICLIBRARY_DOWNLOADINFO.
Referenced by CGUIWindowMusicBase::DoScan(), CGUIWindowMusicBase::OnAssignContent(), CGUIWindowMusicBase::OnInitWindow(), KODI::CDRIP::CCDDARipper::OnJobComplete(), CGUIWindowMusicNav::OnMessage(), CApplication::UpdateLibraries(), and UpdateLibrary().
StartAlbumScan()
void CMusicLibraryQueue::StartAlbumScan (const std::string & strDirectory, bool refresh = false)
Enqueue an album scraping job fetching additional album data.
Parameters
[in] strDirectory Virtual path that identifies which albums to process or "" (empty string) for all albums
[in] refresh Whether or not to refresh data for albums that have previously been scraped
References AddJob(), MUSIC_INFO::CMusicInfoScanner::SCAN_ALBUMS, and MUSIC_INFO::CMusicInfoScanner::SCAN_RESCAN.
Referenced by CGUIWindowMusicBase::OnItemInfoAll(), and JSONRPC::CAudioLibrary::RefreshAlbum().
StartArtistScan()
void CMusicLibraryQueue::StartArtistScan (const std::string & strDirectory, bool refresh = false)
Enqueue an artist scraping job fetching additional artist data.
Parameters
[in] strDirectory Virtual path that identifies which artists to process or "" (empty string) for all artists
[in] refresh Whether or not to refresh data for artists that have previously been scraped
References AddJob(), MUSIC_INFO::CMusicInfoScanner::SCAN_ARTISTS, and MUSIC_INFO::CMusicInfoScanner::SCAN_RESCAN.
Referenced by CGUIWindowMusicBase::OnItemInfoAll(), and JSONRPC::CAudioLibrary::RefreshArtist().
StopLibraryScanning()
void CMusicLibraryQueue::StopLibraryScanning ()
Stop and dequeue all scanning jobs.
References CancelJob(), m_critical, m_jobs, and Refresh().
Referenced by CGUIWindowMusicBase::DoScan(), CProfileManager::LogOff(), CGUIWindowMusicNav::OnMessage(), and UpdateLibrary().
Member Data Documentation
m_cleaning
bool CMusicLibraryQueue::m_cleaning = false private
Referenced by IsScanningLibrary().
m_critical
CCriticalSection CMusicLibraryQueue::m_critical private
Referenced by AddJob(), CancelAllJobs(), CancelJob(), OnJobComplete(), StopLibraryScanning(), and ~CMusicLibraryQueue().
m_jobs
MusicLibraryJobMap CMusicLibraryQueue::m_jobs private
Referenced by AddJob(), CancelAllJobs(), CancelJob(), IsScanningLibrary(), OnJobComplete(), StopLibraryScanning(), and ~CMusicLibraryQueue().
m_modal
bool CMusicLibraryQueue::m_modal = false private
Referenced by ExportLibrary(), ImportLibrary(), and IsRunning().
The documentation for this class was generated from the following files:
MusicLibraryQueue.h
MusicLibraryQueue.cpp