Kodi Documentation: CAndroidMouse Class Reference
CAndroidMouse Class Reference
#include <AndroidMouse.h>
Public Member Functions
CAndroidMouse ()=default
virtual ~CAndroidMouse ()=default
bool onMouseEvent (AInputEvent *event)
Private Member Functions
void MouseMove (float x, float y)
void MouseButton (float x, float y, int32_t type, int32_t buttons)
void MouseWheel (float x, float y, float value)
Private Attributes
int32_t m_lastButtonState = 0
Constructor & Destructor Documentation
CAndroidMouse()
CAndroidMouse::CAndroidMouse () default
~CAndroidMouse()
virtual CAndroidMouse::~CAndroidMouse () virtual default
Member Function Documentation
MouseButton()
void CAndroidMouse::MouseButton (float x, float y, int32_t type, int32_t buttons) private
References CXBMCApp::android_printf(), XBMC_MouseButtonEvent::button, XBMC_Event::button, CServiceBroker::GetAppPort(), m_lastButtonState, XBMC_Event::type, XBMC_MouseButtonEvent::x, XBMC_BUTTON_LEFT, XBMC_BUTTON_MIDDLE, XBMC_BUTTON_RIGHT, XBMC_MOUSEBUTTONDOWN, XBMC_MOUSEBUTTONUP, and XBMC_MouseButtonEvent::y.
Referenced by onMouseEvent().
MouseMove()
void CAndroidMouse::MouseMove (float x, float y) private
References CXBMCApp::android_printf(), CServiceBroker::GetAppPort(), XBMC_Event::motion, XBMC_Event::type, XBMC_MouseMotionEvent::x, XBMC_MOUSEMOTION, and XBMC_MouseMotionEvent::y.
Referenced by onMouseEvent().
MouseWheel()
void CAndroidMouse::MouseWheel (float x, float y, float value) private
References CXBMCApp::android_printf(), XBMC_MouseButtonEvent::button, XBMC_Event::button, CServiceBroker::GetAppPort(), CServiceBroker::GetWinSystem(), XBMC_Event::type, value, XBMC_MouseButtonEvent::x, XBMC_BUTTON_WHEELDOWN, XBMC_BUTTON_WHEELUP, XBMC_MOUSEBUTTONDOWN, XBMC_MOUSEBUTTONUP, and XBMC_MouseButtonEvent::y.
Referenced by onMouseEvent().
onMouseEvent()
bool CAndroidMouse::onMouseEvent (AInputEvent * event)
References CXBMCApp::android_printf(), MouseButton(), MouseMove(), and MouseWheel().
Referenced by CEventLoop::processInput().
Member Data Documentation
m_lastButtonState
int32_t CAndroidMouse::m_lastButtonState = 0 private
Referenced by MouseButton().
The documentation for this class was generated from the following files:
AndroidMouse.h
AndroidMouse.cpp