Kodi Documentation: CLibInputTouch Class Reference
CLibInputTouch Class Reference
#include <LibInputTouch.h>
Public Member Functions
CLibInputTouch ()
void ProcessTouchDown (libinput_event_touch *e)
void ProcessTouchMotion (libinput_event_touch *e)
void ProcessTouchUp (libinput_event_touch *e)
void ProcessTouchCancel (libinput_event_touch *e)
void ProcessTouchFrame (libinput_event_touch *e)
Private Member Functions
void CheckSlot (int slot)
TouchInput GetEvent (int slot)
void SetEvent (int slot, TouchInput event)
void SetPosition (int slot, CPoint point)
int GetX (int slot)
int GetY (int slot)
Private Attributes
std::vector< std::pair< TouchInput, CPoint > > m_points {std::make_pair(TouchInputUnchanged, CPoint(0, 0))}
Constructor & Destructor Documentation
CLibInputTouch()
CLibInputTouch::CLibInputTouch ()
References CGenericTouchActionHandler::GetInstance(), CGenericTouchInputHandler::GetInstance(), m_points, and ITouchInputHandling::RegisterHandler().
Member Function Documentation
CheckSlot()
void CLibInputTouch::CheckSlot (int slot) private
References m_points, and TouchInputUnchanged.
Referenced by GetEvent(), SetEvent(), and SetPosition().
GetEvent()
TouchInput CLibInputTouch::GetEvent (int slot) private
References CheckSlot(), and m_points.
Referenced by ProcessTouchFrame(), and ProcessTouchMotion().
GetX()
int CLibInputTouch::GetX (int slot) inline private
References m_points.
Referenced by ProcessTouchCancel(), ProcessTouchFrame(), and ProcessTouchMotion().
GetY()
int CLibInputTouch::GetY (int slot) inline private
References m_points.
Referenced by ProcessTouchCancel(), ProcessTouchFrame(), and ProcessTouchMotion().
ProcessTouchCancel()
void CLibInputTouch::ProcessTouchCancel (libinput_event_touch * e)
References CGenericTouchInputHandler::GetInstance(), GetX(), GetY(), CGenericTouchInputHandler::HandleTouchInput(), CLog::Log(), LOGDEBUG, and TouchInputAbort.
ProcessTouchDown()
void CLibInputTouch::ProcessTouchDown (libinput_event_touch * e)
References GetPos(), CLog::Log(), LOGDEBUG, SetEvent(), SetPosition(), and TouchInputDown.
ProcessTouchFrame()
void CLibInputTouch::ProcessTouchFrame (libinput_event_touch * e)
References GetEvent(), CGenericTouchInputHandler::GetInstance(), GetX(), GetY(), CGenericTouchInputHandler::HandleTouchInput(), CLog::Log(), LOGDEBUG, m_points, SetEvent(), and TouchInputUnchanged.
ProcessTouchMotion()
void CLibInputTouch::ProcessTouchMotion (libinput_event_touch * e)
References GetEvent(), CGenericTouchInputHandler::GetInstance(), GetPos(), GetX(), GetY(), CLog::Log(), LOGDEBUG, SetEvent(), SetPosition(), TouchInputDown, TouchInputMove, and CGenericTouchInputHandler::UpdateTouchPointer().
ProcessTouchUp()
void CLibInputTouch::ProcessTouchUp (libinput_event_touch * e)
References CLog::Log(), LOGDEBUG, SetEvent(), and TouchInputUp.
SetEvent()
void CLibInputTouch::SetEvent (int slot, TouchInput event) private
References CheckSlot(), and m_points.
Referenced by ProcessTouchDown(), ProcessTouchFrame(), ProcessTouchMotion(), and ProcessTouchUp().
SetPosition()
void CLibInputTouch::SetPosition (int slot, CPoint point) private
References CheckSlot(), and m_points.
Referenced by ProcessTouchDown(), and ProcessTouchMotion().
Member Data Documentation
m_points
std::vector<std::pair<TouchInput, CPoint> > CLibInputTouch::m_points {std::make_pair(TouchInputUnchanged, CPoint(0, 0))} private
Referenced by CheckSlot(), CLibInputTouch(), GetEvent(), GetX(), GetY(), ProcessTouchFrame(), SetEvent(), and SetPosition().
The documentation for this class was generated from the following files:
linux/input/LibInputTouch.h
LibInputTouch.cpp