Kodi Documentation: JSONRPC::CFavouritesOperations Class Reference
JSONRPC::CFavouritesOperations Class Reference
#include <FavouritesOperations.h>
Static Public Member Functions
static JSONRPC_STATUS GetFavourites (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
static JSONRPC_STATUS AddFavourite (const std::string &method, ITransportLayer *transport, IClient *client, const CVariant &parameterObject, CVariant &result)
Static Public Member Functions inherited from JSONRPC::CJSONUtils
static void MillisecondsToTimeObject (int time, CVariant &result)
Additional Inherited Members
Static Protected Member Functions inherited from JSONRPC::CJSONUtils
static void HandleLimits (const CVariant &parameterObject, CVariant &result, int size, int &start, int &end)
static bool ParseSorting (const CVariant &parameterObject, SortBy &sortBy, SortOrder &sortOrder, SortAttribute &sortAttributes)
static void ParseLimits (const CVariant &parameterObject, int &limitStart, int &limitEnd)
static bool ParameterExists (const CVariant &parameterObject, const std::string &key, unsigned int position)
Checks if the given object contains a parameter.
static bool IsValueMember (const CVariant &value, const std::string &key)
Checks if the given object contains a value with the given key.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position)
Returns the json value of a parameter.
static CVariant GetParameter (const CVariant &parameterObject, const std::string &key, unsigned int position, const CVariant &fallback)
Returns the json value of a parameter or the given default value.
static std::string GetString (const CVariant &value, const char *defaultValue)
Returns the given json value as a string.
static TransportLayerCapability StringToTransportLayer (const std::string &transport)
Returns a TransportLayerCapability value of the given string representation.
static JSONSchemaType StringToSchemaValueType (const std::string &valueType)
Returns a JSONSchemaType value for the given string representation.
static std::string SchemaValueTypeToString (JSONSchemaType valueType)
Returns a string representation for the given JSONSchemaType.
static void SchemaValueTypeToJson (JSONSchemaType valueType, CVariant &jsonObject)
Converts the given json schema type into a json object.
static const char * ValueTypeToString (CVariant::VariantType valueType)
static bool IsParameterType (const CVariant &parameterObject, const char *key, unsigned int position, JSONSchemaType valueType)
Checks if the parameter with the given name or at the given position is of a certain type.
static bool IsType (const CVariant &value, JSONSchemaType valueType)
Checks if the given json value is of the given type.
static void SetDefaultValue (CVariant &value, JSONSchemaType valueType)
Sets the value of the given json value to the default value of the given type.
static bool HasType (JSONSchemaType typeObject, JSONSchemaType type)
static bool ParameterNotNull (const CVariant &parameterObject, const std::string &key)
static void CopyStringArray (const CVariant &jsonStringArray, std::vector< std::string > &stringArray)
Copies the values from the jsonStringArray to the stringArray. stringArray is cleared.
static void SetFromDBDate (const CVariant &jsonDate, CDateTime &date)
static void SetFromDBDateTime (const CVariant &jsonDate, CDateTime &date)
static bool GetXspFiltering (const std::string &type, const CVariant &filter, std::string &xsp)
Member Function Documentation
AddFavourite()
JSONRPC_STATUS CFavouritesOperations::AddFavourite (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References JSONRPC::ACK, CVariant::asString(), JSONRPC::FailedToExecute, CServiceBroker::GetFavouritesService(), JSONRPC::InvalidParams, URIUtils::IsAndroidApp(), URIUtils::IsScript(), JSONRPC::CJSONUtils::ParameterNotNull(), CGUIListItem::SetArt(), CFileItem::SetLabel(), CWindowTranslator::TranslateWindow(), and WINDOW_INVALID.
GetFavourites()
JSONRPC_STATUS CFavouritesOperations::GetFavourites (const std::string & method, ITransportLayer * transport, IClient * client, const CVariant & parameterObject, CVariant & result) static
References CFavouritesURL::ACTIVATE_WINDOW, CVariant::append(), CVariant::asString(), end(), CVariant::end_array(), fields, CFileItemList::Get(), CFavouritesURL::GetAction(), CFavouritesService::GetAll(), CServiceBroker::GetFavouritesService(), CFavouritesURL::GetTarget(), CFavouritesURL::GetWindowID(), JSONRPC::CJSONUtils::HandleLimits(), CVariant::isArray(), CVariant::isMember(), CVariant::isNull(), CFavouritesURL::IsValid(), JSONRPC::OK, CFavouritesURL::PLAY_MEDIA, CFavouritesURL::RUN_SCRIPT, CFileItemList::Size(), CFavouritesURL::START_ANDROID_ACTIVITY, and CWindowTranslator::TranslateWindow().
The documentation for this class was generated from the following files:
FavouritesOperations.h
FavouritesOperations.cpp