Kodi Documentation: CRenderSystemDX Class Reference
CRenderSystemDX Class Reference abstract
#include <RenderSystemDX.h>
Public Member Functions
CRenderSystemDX ()
virtual ~CRenderSystemDX ()
bool InitRenderSystem () override
bool DestroyRenderSystem () override
bool BeginRender () override
bool EndRender () override
void PresentRender (bool rendered, bool videoLayer) override
bool ClearBuffers (KODI::UTILS::COLOR::Color color) override
void SetViewPort (const CRect &viewPort) override
void GetViewPort (CRect &viewPort) override
void RestoreViewPort () override
CRect ClipRectToScissorRect (const CRect &rect) override
bool ScissorsCanEffectClipping () override
void SetScissors (const CRect &rect) override
void ResetScissors () override
void CaptureStateBlock () override
void ApplyStateBlock () override
void SetCameraPosition (const CPoint &camera, int screenWidth, int screenHeight, float stereoFactor=0.f) override
void SetStereoMode (RENDER_STEREO_MODE mode, RENDER_STEREO_VIEW view) override
bool SupportsStereo (RENDER_STEREO_MODE mode) const override
void Project (float &x, float &y, float &z) override
bool SupportsNPOT (bool dxt) const override
void OnDXDeviceLost () override
void OnDXDeviceRestored () override
CGUIShaderDX * GetGUIShader () const
bool IsFormatSupport (DXGI_FORMAT format, unsigned int usage) const
CRect GetBackBufferRect ()
CD3DTexture & GetBackBuffer ()
void FlushGPU () const
void RequestDecodingTime ()
void ReleaseDecodingTime ()
void SetAlphaBlendEnable (bool enable)
bool IsExtSupported (const char *extension) const override
bool ResetRenderSystem (int width, int height) override
Public Member Functions inherited from CRenderSystemBase
CRenderSystemBase ()
virtual ~CRenderSystemBase ()
virtual void InvalidateColorBuffer ()
virtual void SetDepthCulling (DEPTH_CULLING culling)
virtual std::string GetShaderPath (const std::string &filename)
void GetRenderVersion (unsigned int &major, unsigned int &minor) const
const std::string & GetRenderVendor () const
const std::string & GetRenderRenderer () const
const std::string & GetRenderVersionString () const
unsigned int GetMaxTextureSize () const
unsigned int GetMinDXTPitch () const
virtual void ShowSplash (const std::string &message)
Protected Member Functions
virtual void PresentRenderImpl (bool rendered)=0
bool CreateStates ()
bool InitGUIShader ()
void OnResize ()
void CheckInterlacedStereoView (void)
void CheckDeviceCaps ()
Protected Attributes
CCriticalSection m_resourceSection
CCriticalSection m_decoderSection
bool m_inScene { false }
True if we're in a BeginScene()/EndScene() block.
bool m_BlendEnabled { false }
bool m_ScissorsEnabled { false }
D3D11_VIEWPORT m_viewPort
CRect m_scissor
CGUIShaderDX * m_pGUIShader { nullptr }
Microsoft::WRL::ComPtr< ID3D11DepthStencilState > m_depthStencilState
Microsoft::WRL::ComPtr< ID3D11BlendState > m_BlendEnableState
Microsoft::WRL::ComPtr< ID3D11BlendState > m_BlendDisableState
Microsoft::WRL::ComPtr< ID3D11RasterizerState > m_RSScissorDisable
Microsoft::WRL::ComPtr< ID3D11RasterizerState > m_RSScissorEnable
CD3DTexture m_rightEyeTex
XbmcThreads::EndTime m_decodingTimer
XbmcThreads::ConditionVariable m_decodingEvent
std::shared_ptr< DX::DeviceResources > m_deviceResources
Protected Attributes inherited from CRenderSystemBase
bool m_bRenderCreated
bool m_bVSync
unsigned int m_maxTextureSize
unsigned int m_minDXTPitch
std::string m_RenderRenderer
std::string m_RenderVendor
std::string m_RenderVersion
int m_RenderVersionMinor
int m_RenderVersionMajor
RENDER_STEREO_VIEW m_stereoView = RENDER_STEREO_VIEW_OFF
RENDER_STEREO_MODE m_stereoMode = RENDER_STEREO_MODE_OFF
bool m_limitedColorRange = false
bool m_transferPQ {false}
std::unique_ptr< CGUIImage > m_splashImage
std::unique_ptr< CGUITextLayout > m_splashMessageLayout
Constructor & Destructor Documentation
CRenderSystemDX()
CRenderSystemDX::CRenderSystemDX ()
References CRenderSystemBase::m_bVSync, m_scissor, and m_viewPort.
~CRenderSystemDX()
CRenderSystemDX::~CRenderSystemDX () virtual default
Member Function Documentation
ApplyStateBlock()
void CRenderSystemDX::ApplyStateBlock () override virtual
Implements CRenderSystemBase.
References CGUIShaderDX::ApplyStateBlock(), m_BlendDisableState, m_BlendEnabled, m_BlendEnableState, CRenderSystemBase::m_bRenderCreated, m_depthStencilState, m_deviceResources, m_pGUIShader, m_RSScissorDisable, m_RSScissorEnable, and m_ScissorsEnabled.
BeginRender()
bool CRenderSystemDX::BeginRender () override virtual
Implements CRenderSystemBase.
References CServiceBroker::GetWinSystem(), CRenderSystemBase::m_bRenderCreated, m_deviceResources, m_inScene, CRenderSystemBase::m_limitedColorRange, and CWinSystemBase::UseLimitedColor().
CaptureStateBlock()
void CRenderSystemDX::CaptureStateBlock () override virtual
Implements CRenderSystemBase.
References CRenderSystemBase::m_bRenderCreated.
CheckDeviceCaps()
void CRenderSystemDX::CheckDeviceCaps () protected
References m_deviceResources, and CRenderSystemBase::m_maxTextureSize.
Referenced by InitRenderSystem().
CheckInterlacedStereoView()
void CRenderSystemDX::CheckInterlacedStereoView (void) protected
References CD3DTexture::Create(), CD3DTexture::Get(), CWinSystemBase::GetGfxContext(), CGraphicContext::GetStereoMode(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGERROR, m_deviceResources, m_rightEyeTex, CD3DTexture::Release(), RENDER_STEREO_MODE_CHECKERBOARD, RENDER_STEREO_MODE_INTERLACED, RENDER_STEREO_MODE_SPLIT_HORIZONTAL, and CGraphicContext::SetStereoMode().
Referenced by OnResize().
ClearBuffers()
bool CRenderSystemDX::ClearBuffers (KODI::UTILS::COLOR::Color color) override virtual
Implements CRenderSystemBase.
References color, CGUITextureD3D::DrawQuad(), CD3DTexture::GetRenderTarget(), m_BlendEnabled, CRenderSystemBase::m_bRenderCreated, m_deviceResources, m_rightEyeTex, m_scissor, m_ScissorsEnabled, CRenderSystemBase::m_stereoMode, CRenderSystemBase::m_stereoView, RENDER_STEREO_MODE_ANAGLYPH_GREEN_MAGENTA, RENDER_STEREO_MODE_ANAGLYPH_RED_CYAN, RENDER_STEREO_MODE_ANAGLYPH_YELLOW_BLUE, RENDER_STEREO_MODE_CHECKERBOARD, RENDER_STEREO_MODE_INTERLACED, RENDER_STEREO_MODE_MONO, RENDER_STEREO_MODE_OFF, RENDER_STEREO_VIEW_RIGHT, SetAlphaBlendEnable(), and CD3DHelper::XMStoreColor().
ClipRectToScissorRect()
CRect CRenderSystemDX::ClipRectToScissorRect (const CRect & rect) override virtual
Reimplemented from CRenderSystemBase.
References CGUIShaderDX::GetClipXFactor(), CGUIShaderDX::GetClipXOffset(), CGUIShaderDX::GetClipYFactor(), CGUIShaderDX::GetClipYOffset(), CRenderSystemBase::m_bRenderCreated, m_pGUIShader, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
CreateStates()
bool CRenderSystemDX::CreateStates () protected
References FAILED, m_BlendDisableState, m_BlendEnabled, m_BlendEnableState, m_depthStencilState, m_deviceResources, m_RSScissorDisable, and m_RSScissorEnable.
Referenced by InitRenderSystem().
DestroyRenderSystem()
bool CRenderSystemDX::DestroyRenderSystem () override virtual
Implements CRenderSystemBase.
Reimplemented in CWinSystemWin10DX, and CWinSystemWin32DX.
References CGUIShaderDX::End(), m_BlendDisableState, m_BlendEnableState, m_depthStencilState, m_pGUIShader, m_resourceSection, m_rightEyeTex, m_RSScissorDisable, m_RSScissorEnable, and CD3DTexture::Release().
Referenced by CWinSystemWin10DX::DestroyRenderSystem(), CWinSystemWin32DX::DestroyRenderSystem(), and OnDXDeviceLost().
EndRender()
bool CRenderSystemDX::EndRender () override virtual
Implements CRenderSystemBase.
References CRenderSystemBase::m_bRenderCreated, and m_inScene.
FlushGPU()
void CRenderSystemDX::FlushGPU () const
References CRenderSystemBase::m_bRenderCreated, and m_deviceResources.
GetBackBuffer()
CD3DTexture & CRenderSystemDX::GetBackBuffer ()
References CD3DTexture::Get(), m_deviceResources, m_rightEyeTex, CRenderSystemBase::m_stereoView, and RENDER_STEREO_VIEW_RIGHT.
Referenced by KODI::RETRO::CRPWinRenderer::RenderInternal().
GetBackBufferRect()
CRect CRenderSystemDX::GetBackBufferRect ()
References m_deviceResources.
GetGUIShader()
CGUIShaderDX * CRenderSystemDX::GetGUIShader () const inline
References m_pGUIShader.
Referenced by KODI::RETRO::CRenderContext::GetGUIShader().
GetViewPort()
void CRenderSystemDX::GetViewPort (CRect & viewPort) override virtual
Implements CRenderSystemBase.
References CRenderSystemBase::m_bRenderCreated, m_viewPort, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
InitGUIShader()
bool CRenderSystemDX::InitGUIShader () protected
References CGUIShaderDX::ApplyStateBlock(), CGUIShaderDX::Initialize(), LOGERROR, and m_pGUIShader.
Referenced by InitRenderSystem().
InitRenderSystem()
bool CRenderSystemDX::InitRenderSystem () override virtual
Implements CRenderSystemBase.
References CheckDeviceCaps(), CDVDFactoryCodec::ClearHWAccels(), VIDEOPLAYER::CRendererFactory::ClearRenderer(), CreateStates(), KODI::PLATFORM::WINDOWS::FromW(), InitGUIShader(), CRenderSystemBase::m_bRenderCreated, CRenderSystemBase::m_bVSync, m_deviceResources, CRenderSystemBase::m_RenderRenderer, CRenderSystemBase::m_RenderVersion, m_viewPort, KODI::RETRO::CRPProcessInfoWin::Register(), DXVA::CDecoder::Register(), VIDEOPLAYER::CProcessInfoWin::Register(), VIDEOPLAYER::CProcessInfoWin10::Register(), CWinRenderer::Register(), CGUITextureD3D::Register(), RestoreViewPort(), and SetCameraPosition().
Referenced by OnDXDeviceRestored().
IsExtSupported()
bool CRenderSystemDX::IsExtSupported (const char * extension) const inline override virtual
Implements CRenderSystemBase.
IsFormatSupport()
bool CRenderSystemDX::IsFormatSupport (DXGI_FORMAT format, unsigned int usage) const
References m_deviceResources, and usage.
OnDXDeviceLost()
void CRenderSystemDX::OnDXDeviceLost () override
References DestroyRenderSystem().
OnDXDeviceRestored()
void CRenderSystemDX::OnDXDeviceRestored () override
References InitRenderSystem().
OnResize()
void CRenderSystemDX::OnResize () protected
References CheckInterlacedStereoView(), CRenderSystemBase::m_bRenderCreated, m_deviceResources, and SetCameraPosition().
Referenced by CWinSystemWin10DX::ResizeWindow(), CWinSystemWin32DX::ResizeWindow(), CWinSystemWin10DX::SetFullScreen(), and CWinSystemWin32DX::SetFullScreen().
PresentRender()
void CRenderSystemDX::PresentRender (bool rendered, bool videoLayer) override virtual
Implements CRenderSystemBase.
References CD3DTexture::DrawQuad(), CRenderSystemBase::m_bRenderCreated, m_decoderSection, m_decodingEvent, m_decodingTimer, m_deviceResources, m_rightEyeTex, CRenderSystemBase::m_stereoMode, PresentRenderImpl(), CD3DHelper::PSClearShaderResources(), RENDER_STEREO_MODE_CHECKERBOARD, RENDER_STEREO_MODE_INTERLACED, SetAlphaBlendEnable(), SHADER_METHOD_RENDER_STEREO_CHECKERBOARD_RIGHT, SHADER_METHOD_RENDER_STEREO_INTERLACED_RIGHT, and XbmcThreads::ConditionVariable::wait().
PresentRenderImpl()
virtual void CRenderSystemDX::PresentRenderImpl (bool rendered) protected pure virtual
Implemented in CWinSystemWin10DX, and CWinSystemWin32DX.
Referenced by PresentRender().
Project()
void CRenderSystemDX::Project (float & x, float & y, float & z) override virtual
Project (x,y,z) 3d scene coordinates to (x,y) 2d screen coordinates
Reimplemented from CRenderSystemBase.
References CRenderSystemBase::m_bRenderCreated, m_pGUIShader, and CGUIShaderDX::Project().
ReleaseDecodingTime()
void CRenderSystemDX::ReleaseDecodingTime ()
References m_decoderSection, m_decodingEvent, m_decodingTimer, and XbmcThreads::ConditionVariable::notify().
RequestDecodingTime()
void CRenderSystemDX::RequestDecodingTime ()
References m_decoderSection, and m_decodingTimer.
ResetRenderSystem()
bool CRenderSystemDX::ResetRenderSystem (int width, int height) inline override virtual
Implements CRenderSystemBase.
ResetScissors()
void CRenderSystemDX::ResetScissors () override virtual
Implements CRenderSystemBase.
References CRenderSystemBase::m_bRenderCreated, m_deviceResources, m_RSScissorDisable, m_scissor, m_ScissorsEnabled, and CRectGen< T >::SetRect().
RestoreViewPort()
void CRenderSystemDX::RestoreViewPort () override virtual
Reimplemented from CRenderSystemBase.
References CRenderSystemBase::m_bRenderCreated, m_deviceResources, m_pGUIShader, m_viewPort, and CGUIShaderDX::SetViewPort().
Referenced by InitRenderSystem().
ScissorsCanEffectClipping()
bool CRenderSystemDX::ScissorsCanEffectClipping () override virtual
Reimplemented from CRenderSystemBase.
References CGUIShaderDX::HardwareClipIsPossible(), CRenderSystemBase::m_bRenderCreated, and m_pGUIShader.
SetAlphaBlendEnable()
void CRenderSystemDX::SetAlphaBlendEnable (bool enable)
References m_BlendDisableState, m_BlendEnabled, m_BlendEnableState, CRenderSystemBase::m_bRenderCreated, and m_deviceResources.
Referenced by ClearBuffers(), PresentRender(), and KODI::RETRO::CRPWinRenderer::RenderInternal().
SetCameraPosition()
void CRenderSystemDX::SetCameraPosition (const CPoint & camera, int screenWidth, int screenHeight, float stereoFactor = 0.f) override virtual
Implements CRenderSystemBase.
References CRenderSystemBase::m_bRenderCreated, m_pGUIShader, m_viewPort, CGUIShaderDX::SetProjection(), CGUIShaderDX::SetView(), CGUIShaderDX::SetWorld(), CPointGen< T >::x, and CPointGen< T >::y.
Referenced by InitRenderSystem(), and OnResize().
SetScissors()
void CRenderSystemDX::SetScissors (const CRect & rect) override virtual
Implements CRenderSystemBase.
References CRenderSystemBase::m_bRenderCreated, m_deviceResources, m_RSScissorEnable, m_scissor, m_ScissorsEnabled, MathUtils::round_int(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
SetStereoMode()
void CRenderSystemDX::SetStereoMode (RENDER_STEREO_MODE mode, RENDER_STEREO_VIEW view) override virtual
Reimplemented from CRenderSystemBase.
References CD3DTexture::GetAddressOfRTV(), m_BlendDisableState, m_BlendEnabled, m_BlendEnableState, CRenderSystemBase::m_bRenderCreated, m_deviceResources, m_rightEyeTex, CRenderSystemBase::m_stereoMode, CRenderSystemBase::m_stereoView, RENDER_STEREO_MODE_ANAGLYPH_GREEN_MAGENTA, RENDER_STEREO_MODE_ANAGLYPH_RED_CYAN, RENDER_STEREO_MODE_ANAGLYPH_YELLOW_BLUE, RENDER_STEREO_MODE_CHECKERBOARD, RENDER_STEREO_MODE_HARDWAREBASED, RENDER_STEREO_MODE_INTERLACED, RENDER_STEREO_VIEW_LEFT, RENDER_STEREO_VIEW_RIGHT, and CRenderSystemBase::SetStereoMode().
SetViewPort()
void CRenderSystemDX::SetViewPort (const CRect & viewPort) override virtual
Implements CRenderSystemBase.
References CRenderSystemBase::m_bRenderCreated, m_deviceResources, m_pGUIShader, m_viewPort, CGUIShaderDX::SetViewPort(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
SupportsNPOT()
bool CRenderSystemDX::SupportsNPOT (bool dxt) const override virtual
Reimplemented from CRenderSystemBase.
References m_deviceResources.
SupportsStereo()
bool CRenderSystemDX::SupportsStereo (RENDER_STEREO_MODE mode) const override virtual
Reimplemented from CRenderSystemBase.
References m_deviceResources, RENDER_STEREO_MODE_ANAGLYPH_GREEN_MAGENTA, RENDER_STEREO_MODE_ANAGLYPH_RED_CYAN, RENDER_STEREO_MODE_ANAGLYPH_YELLOW_BLUE, RENDER_STEREO_MODE_CHECKERBOARD, RENDER_STEREO_MODE_HARDWAREBASED, RENDER_STEREO_MODE_INTERLACED, and CRenderSystemBase::SupportsStereo().
Member Data Documentation
m_BlendDisableState
Microsoft::WRL::ComPtr<ID3D11BlendState> CRenderSystemDX::m_BlendDisableState protected
Referenced by ApplyStateBlock(), CreateStates(), DestroyRenderSystem(), SetAlphaBlendEnable(), and SetStereoMode().
m_BlendEnabled
bool CRenderSystemDX::m_BlendEnabled { false } protected
Referenced by ApplyStateBlock(), ClearBuffers(), CreateStates(), SetAlphaBlendEnable(), and SetStereoMode().
m_BlendEnableState
Microsoft::WRL::ComPtr<ID3D11BlendState> CRenderSystemDX::m_BlendEnableState protected
Referenced by ApplyStateBlock(), CreateStates(), DestroyRenderSystem(), SetAlphaBlendEnable(), and SetStereoMode().
m_decoderSection
CCriticalSection CRenderSystemDX::m_decoderSection protected
Referenced by PresentRender(), ReleaseDecodingTime(), and RequestDecodingTime().
m_decodingEvent
XbmcThreads::ConditionVariable CRenderSystemDX::m_decodingEvent protected
Referenced by PresentRender(), and ReleaseDecodingTime().
m_decodingTimer
XbmcThreads::EndTime CRenderSystemDX::m_decodingTimer protected
Referenced by PresentRender(), ReleaseDecodingTime(), and RequestDecodingTime().
m_depthStencilState
Microsoft::WRL::ComPtr<ID3D11DepthStencilState> CRenderSystemDX::m_depthStencilState protected
Referenced by ApplyStateBlock(), CreateStates(), and DestroyRenderSystem().
m_deviceResources
std::shared_ptr<DX::DeviceResources> CRenderSystemDX::m_deviceResources protected
Referenced by ApplyStateBlock(), BeginRender(), CWinSystemWin32DX::ChangeResolution(), CheckDeviceCaps(), CheckInterlacedStereoView(), ClearBuffers(), CWinSystemWin10DX::CreateBackBuffer(), CWinSystemWin32DX::CreateBackBuffer(), CWinSystemWin10DX::CreateNewWindow(), CWinSystemWin32DX::CreateNewWindow(), CreateStates(), CWinSystemWin10DX::DestroyRenderSystem(), CWinSystemWin32DX::DestroyRenderSystem(), CWinSystemWin10DX::DPIChanged(), CWinSystemWin32DX::DPIChanged(), FlushGPU(), GetBackBuffer(), GetBackBufferRect(), CWinSystemWin10DX::GetDebugInfo(), CWinSystemWin32DX::GetDebugInfo(), CWinSystemWin10DX::GetHWContext(), CWinSystemWin32DX::GetHWContext(), CWinSystemWin10DX::GetOutputSize(), InitRenderSystem(), IsFormatSupport(), CWinSystemWin10DX::IsHDROutput(), CWinSystemWin32DX::IsHDROutput(), CWinSystemWin10DX::IsStereoEnabled(), CWinSystemWin32DX::IsStereoEnabled(), CWinSystemWin10DX::IsTransferPQ(), CWinSystemWin32DX::IsTransferPQ(), CWinSystemWin10DX::OnMove(), CWinSystemWin32DX::OnMove(), OnResize(), CWinSystemWin10DX::OnResize(), CWinSystemWin32DX::OnResize(), CWinSystemWin32DX::OnScreenChange(), PresentRender(), CWinSystemWin10DX::PresentRenderImpl(), CWinSystemWin32DX::PresentRenderImpl(), CWinSystemWin10DX::Register(), CWinSystemWin32DX::Register(), CWinSystemWin10DX::ReleaseBackBuffer(), CWinSystemWin32DX::ReleaseBackBuffer(), ResetScissors(), CWinSystemWin10DX::ResizeDeviceBuffers(), CWinSystemWin32DX::ResizeDeviceBuffers(), RestoreViewPort(), SetAlphaBlendEnable(), CWinSystemWin10DX::SetDeviceFullScreen(), CWinSystemWin32DX::SetDeviceFullScreen(), CWinSystemWin10DX::SetHdrColorSpace(), CWinSystemWin32DX::SetHdrColorSpace(), CWinSystemWin10DX::SetHdrMetaData(), CWinSystemWin32DX::SetHdrMetaData(), SetScissors(), SetStereoMode(), SetViewPort(), CWinSystemWin32DX::SetWindow(), SupportsNPOT(), SupportsStereo(), CWinSystemWin32DX::SupportsVideoSuperResolution(), CWinSystemWin10DX::ToggleHDR(), CWinSystemWin32DX::ToggleHDR(), CWinSystemWin10DX::TrimDevice(), CWinSystemWin10DX::Unregister(), and CWinSystemWin32DX::Unregister().
m_inScene
bool CRenderSystemDX::m_inScene { false } protected
True if we're in a BeginScene()/EndScene() block.
Referenced by BeginRender(), and EndRender().
m_pGUIShader
CGUIShaderDX* CRenderSystemDX::m_pGUIShader { nullptr } protected
Referenced by ApplyStateBlock(), ClipRectToScissorRect(), DestroyRenderSystem(), GetGUIShader(), InitGUIShader(), Project(), RestoreViewPort(), ScissorsCanEffectClipping(), SetCameraPosition(), and SetViewPort().
m_resourceSection
CCriticalSection CRenderSystemDX::m_resourceSection protected
Referenced by DestroyRenderSystem().
m_rightEyeTex
CD3DTexture CRenderSystemDX::m_rightEyeTex protected
Referenced by CheckInterlacedStereoView(), ClearBuffers(), DestroyRenderSystem(), GetBackBuffer(), PresentRender(), and SetStereoMode().
m_RSScissorDisable
Microsoft::WRL::ComPtr<ID3D11RasterizerState> CRenderSystemDX::m_RSScissorDisable protected
Referenced by ApplyStateBlock(), CreateStates(), DestroyRenderSystem(), and ResetScissors().
m_RSScissorEnable
Microsoft::WRL::ComPtr<ID3D11RasterizerState> CRenderSystemDX::m_RSScissorEnable protected
Referenced by ApplyStateBlock(), CreateStates(), DestroyRenderSystem(), and SetScissors().
m_scissor
CRect CRenderSystemDX::m_scissor protected
Referenced by ClearBuffers(), CRenderSystemDX(), ResetScissors(), and SetScissors().
m_ScissorsEnabled
bool CRenderSystemDX::m_ScissorsEnabled { false } protected
Referenced by ApplyStateBlock(), ClearBuffers(), ResetScissors(), and SetScissors().
m_viewPort
D3D11_VIEWPORT CRenderSystemDX::m_viewPort protected
Referenced by CRenderSystemDX(), GetViewPort(), InitRenderSystem(), RestoreViewPort(), SetCameraPosition(), and SetViewPort().
The documentation for this class was generated from the following files:
RenderSystemDX.h
RenderSystemDX.cpp