Kodi Documentation: CMultiProvider Class Reference
CMultiProvider Class Reference
Listproviders
A listprovider that handles multiple individual providers.
#include <MultiProvider.h>
Public Member Functions
CMultiProvider (const TiXmlNode *first, int parentID)
CMultiProvider (const CMultiProvider &other)
std::unique_ptr< IListProvider > Clone () override
Create an instance of the derived class. Allows for polymorphic copies.
bool Update (bool forceRefresh) override
Update the list content.
void Fetch (std::vector< std::shared_ptr< CGUIListItem > > &items) override
Fetch the current list of items.
bool IsUpdating () const override
Check whether the list provider is updating content.
void Reset () override
Reset the current list of items. Derived classes may choose to ignore this.
bool OnClick (const std::shared_ptr< CGUIListItem > &item) override
Click event on an item.
bool OnInfo (const std::shared_ptr< CGUIListItem > &item) override
Open the info dialog for an item provided by this IListProvider.
bool OnContextMenu (const std::shared_ptr< CGUIListItem > &item) override
Open the context menu for an item provided by this IListProvider.
Public Member Functions inherited from IListProvider
IListProvider (int parentID)
IListProvider (const IListProvider &other)=default
virtual ~IListProvider ()=default
virtual void FreeResources (bool immediately)
Free all GUI resources allocated by the items.
virtual bool OnPlay (const std::shared_ptr< CGUIListItem > &item)
Play event on an item.
virtual void SetDefaultItem (int item, bool always)
Set the default item to focus. For backwards compatibility.
virtual int GetDefaultItem () const
The default item to focus.
virtual bool AlwaysFocusDefaultItem () const
Whether to always focus the default item.
Protected Types
typedef size_t item_key_type
Static Protected Member Functions
static item_key_type GetItemKey (std::shared_ptr< CGUIListItem > const &item)
Protected Attributes
std::vector< IListProviderPtr > m_providers
std::map< item_key_type, IListProvider * > m_itemMap
CCriticalSection m_section
Protected Attributes inherited from IListProvider
int m_parentID
Additional Inherited Members
Static Public Member Functions inherited from IListProvider
static std::unique_ptr< IListProvider > Create (const TiXmlNode *parent, int parentID)
Factory to create list providers.
static std::unique_ptr< IListProvider > CreateSingle (const TiXmlNode *content, int parentID)
Factory to create list providers. Cannot create a multi-provider.
Detailed Description
A listprovider that handles multiple individual providers.
Member Typedef Documentation
item_key_type
typedef size_t CMultiProvider::item_key_type protected
Constructor & Destructor Documentation
CMultiProvider() [1/2]
CMultiProvider::CMultiProvider (const TiXmlNode * first, int parentID)
References IListProvider::CreateSingle(), and m_providers.
CMultiProvider() [2/2]
CMultiProvider::CMultiProvider (const CMultiProvider & other) explicit
References IListProvider::Clone(), and m_providers.
Member Function Documentation
Clone()
std::unique_ptr< IListProvider > CMultiProvider::Clone () override virtual
Create an instance of the derived class. Allows for polymorphic copies.
Implements IListProvider.
Fetch()
void CMultiProvider::Fetch (std::vector< std::shared_ptr< CGUIListItem > > & items) override virtual
Fetch the current list of items.
Parameters
items [out] the list to be filled.
Implements IListProvider.
References GetItemKey(), m_itemMap, m_providers, and m_section.
GetItemKey()
CMultiProvider::item_key_type CMultiProvider::GetItemKey (std::shared_ptr< CGUIListItem > const & item) static protected
Referenced by Fetch(), OnClick(), OnContextMenu(), and OnInfo().
IsUpdating()
bool CMultiProvider::IsUpdating () const override virtual
Check whether the list provider is updating content.
Returns
true if in the processing of updating, false otherwise.
Reimplemented from IListProvider.
References m_providers.
OnClick()
bool CMultiProvider::OnClick (const std::shared_ptr< CGUIListItem > & item) override virtual
Click event on an item.
Parameters
item the item that was clicked.
Returns
true if the click was handled, false otherwise.
Implements IListProvider.
References GetItemKey(), m_itemMap, and m_section.
OnContextMenu()
bool CMultiProvider::OnContextMenu (const std::shared_ptr< CGUIListItem > & item) override virtual
Open the context menu for an item provided by this IListProvider.
Parameters
item the item that was clicked.
Returns
true if the click was handled, false otherwise.
Implements IListProvider.
References GetItemKey(), m_itemMap, and m_section.
OnInfo()
bool CMultiProvider::OnInfo (const std::shared_ptr< CGUIListItem > & item) override virtual
Open the info dialog for an item provided by this IListProvider.
Parameters
item the item that was clicked.
Returns
true if the dialog was shown, false otherwise.
Implements IListProvider.
References GetItemKey(), m_itemMap, and m_section.
Reset()
void CMultiProvider::Reset () override virtual
Reset the current list of items. Derived classes may choose to ignore this.
Reimplemented from IListProvider.
References m_itemMap, m_providers, and m_section.
Update()
bool CMultiProvider::Update (bool forceRefresh) override virtual
Update the list content.
Returns
true if the content has changed, false otherwise.
Implements IListProvider.
References m_providers.
Member Data Documentation
m_itemMap
std::map<item_key_type, IListProvider*> CMultiProvider::m_itemMap protected
Referenced by Fetch(), OnClick(), OnContextMenu(), OnInfo(), and Reset().
m_providers
std::vector<IListProviderPtr> CMultiProvider::m_providers protected
Referenced by CMultiProvider(), CMultiProvider(), Fetch(), IsUpdating(), Reset(), and Update().
m_section
CCriticalSection CMultiProvider::m_section protected
Referenced by Fetch(), OnClick(), OnContextMenu(), OnInfo(), and Reset().
The documentation for this class was generated from the following files:
MultiProvider.h
MultiProvider.cpp