Kodi Documentation: ADDON::CAddonDatabaseSerializer Class Reference
ADDON::CAddonDatabaseSerializer Class Reference
Addon content serializer/deserializer.
#include <AddonDatabase.h>
Static Public Member Functions
static std::string SerializeMetadata (const CAddonInfo &addon)
static void DeserializeMetadata (const std::string &document, CAddonInfoBuilderFromDB &builder)
Private Member Functions
CAddonDatabaseSerializer ()=delete
Static Private Member Functions
static CVariant SerializeExtensions (const CAddonExtensions &addonType)
static void DeserializeExtensions (const CVariant &document, CAddonExtensions &addonType)
Detailed Description
Addon content serializer/deserializer.
Used to save data from the add-on in the database using json format. The corresponding field in SQL is "addons" for "metadata".
Warning
Changes in the json format need a way to update the addon database for users, otherwise problems may occur when reading the old content.
Constructor & Destructor Documentation
CAddonDatabaseSerializer()
ADDON::CAddonDatabaseSerializer::CAddonDatabaseSerializer () private delete
Member Function Documentation
DeserializeExtensions()
void CAddonDatabaseSerializer::DeserializeExtensions (const CVariant & document, CAddonExtensions & addonType) static private
References ADDON::SExtValue::asString(), ADDON::content, DeserializeExtensions(), ADDON::CAddonExtensions::m_children, ADDON::CAddonExtensions::m_point, ADDON::CAddonExtensions::m_values, and value.
Referenced by DeserializeExtensions(), and DeserializeMetadata().
DeserializeMetadata()
void CAddonDatabaseSerializer::DeserializeMetadata (const std::string & document, CAddonInfoBuilderFromDB & builder) static
References DeserializeExtensions(), ADDON::CAddonExtensions::m_point, ADDON::CAddonType::m_type, CJSONVariantParser::Parse(), ADDON::CAddonInfoBuilderFromDB::SetArt(), ADDON::CAddonInfoBuilderFromDB::SetAuthor(), ADDON::CAddonInfoBuilderFromDB::SetDependencies(), ADDON::CAddonInfoBuilderFromDB::SetDisclaimer(), ADDON::CAddonInfoBuilderFromDB::SetExtensions(), ADDON::CAddonInfoBuilderFromDB::SetExtrainfo(), ADDON::CAddonInfoBuilderFromDB::SetIcon(), ADDON::CAddonInfoBuilderFromDB::SetLifecycleState(), ADDON::CAddonInfoBuilderFromDB::SetPackageSize(), ADDON::CAddonInfoBuilderFromDB::SetPath(), ADDON::CAddonInfoBuilderFromDB::SetScreenshots(), and ADDON::CAddonInfo::TranslateType().
Referenced by ADDON::CAddonDatabase::FindByAddonId(), ADDON::CAddonDatabase::GetAddon(), and ADDON::CAddonDatabase::GetRepositoryContent().
SerializeExtensions()
CVariant CAddonDatabaseSerializer::SerializeExtensions (const CAddonExtensions & addonType) static private
References ADDON::content, ADDON::CAddonExtensions::m_children, ADDON::CAddonExtensions::m_point, ADDON::CAddonExtensions::m_values, SerializeExtensions(), value, CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
Referenced by SerializeExtensions(), and SerializeMetadata().
SerializeMetadata()
std::string CAddonDatabaseSerializer::SerializeMetadata (const CAddonInfo & addon) static
References ADDON::CAddonInfo::Art(), ADDON::CAddonInfo::Author(), ADDON::CAddonInfo::Disclaimer(), ADDON::CAddonInfo::ExtraInfo(), ADDON::CAddonInfo::GetDependencies(), ADDON::CAddonInfo::Icon(), ADDON::CAddonInfo::LifecycleState(), ADDON::CAddonInfo::LifecycleStateDescription(), ADDON::CAddonInfo::MainType(), ADDON::CAddonInfo::PackageSize(), ADDON::CAddonInfo::Path(), push_back(), ADDON::CAddonInfo::Screenshots(), SerializeExtensions(), ADDON::CAddonInfo::Type(), CVariant::VariantTypeArray, CVariant::VariantTypeObject, and CJSONVariantWriter::Write().
Referenced by ADDON::CAddonDatabase::UpdateRepositoryContent().
The documentation for this class was generated from the following files:
AddonDatabase.h
AddonDatabase.cpp