Kodi Documentation: DatabaseUtils Class Reference
DatabaseUtils Class Reference
#include <DatabaseUtils.h>
Static Public Member Functions
static MediaType MediaTypeFromVideoContentType (VideoDbContentType videoContentType)
static std::string GetField (Field field, const MediaType &mediaType, DatabaseQueryPart queryPart)
static int GetField (Field field, const MediaType &mediaType)
static int GetFieldIndex (Field field, const MediaType &mediaType)
static bool GetSelectFields (const Fields &fields, const MediaType &mediaType, FieldList &selectFields)
static bool GetFieldValue (const dbiplus::field_value &fieldValue, CVariant &variantValue)
static bool GetDatabaseResults (const MediaType &mediaType, const FieldList &fields, const std::unique_ptr< dbiplus::Dataset > &dataset, DatabaseResults &results)
static std::string BuildLimitClause (int end, int start=0)
static std::string BuildLimitClauseOnly (int end, int start=0)
static size_t GetLimitCount (int end, int start)
Static Private Member Functions
static int GetField (Field field, const MediaType &mediaType, bool asIndex)
Member Function Documentation
BuildLimitClause()
std::string DatabaseUtils::BuildLimitClause (int end, int start = 0) static
References BuildLimitClauseOnly(), and end().
Referenced by CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhereJSON(), CMusicDatabase::GetDiscsByWhere(), CVideoDatabase::GetEpisodesByWhere(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideosByWhere(), CVideoDatabase::GetSeasonsByWhere(), CMusicDatabase::GetSongsByWhere(), CMusicDatabase::GetSongsByWhereJSON(), CVideoDatabase::GetTvShowsByWhere(), and TEST().
BuildLimitClauseOnly()
std::string DatabaseUtils::BuildLimitClauseOnly (int end, int start = 0) static
References end().
Referenced by BuildLimitClause(), CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetArtistsByWhere(), and CMusicDatabase::GetSongsFullByWhere().
GetDatabaseResults()
bool DatabaseUtils::GetDatabaseResults (const MediaType & mediaType, const FieldList & fields, const std::unique_ptr< dbiplus::Dataset > & dataset, DatabaseResults & results) static
References FieldAlbum, FieldArtist, FieldEpisodeNumber, FieldLabel, FieldMediaType, FieldRow, fields, FieldSeason, FieldTitle, FieldTrackNumber, FieldYear, GetFieldIndex(), GetFieldValue(), CDateTime::GetYear(), index(), CDateTime::IsValid(), label, CLog::Log(), LOGWARNING, MediaTypeAlbum, MediaTypeArtist, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeSong, MediaTypeTvShow, MediaTypeVideoCollection, dbiplus::result_set::record_header, dbiplus::result_set::records, CDateTime::SetFromDBDate(), and value.
Referenced by CMusicDatabase::GetAlbumsByWhere(), CMusicDatabase::GetArtistsByWhere(), CMusicDatabase::GetSongsFullByWhere(), and SortUtils::SortFromDataset().
GetField() [1/3]
int DatabaseUtils::GetField (Field field, const MediaType & mediaType) static
References FieldNone, GetField(), and MediaTypeNone.
GetField() [2/3]
int DatabaseUtils::GetField (Field field, const MediaType & mediaType, bool asIndex) static private
References CMusicDatabase::album_dateAdded, CMusicDatabase::album_dateModified, CMusicDatabase::album_dateNew, CMusicDatabase::album_dtLastPlayed, CMusicDatabase::album_fRating, CMusicDatabase::album_iAlbumDuration, CMusicDatabase::album_idAlbum, CMusicDatabase::album_iTimesPlayed, CMusicDatabase::album_iTotalDiscs, CMusicDatabase::album_iUserrating, CMusicDatabase::album_iVotes, CMusicDatabase::album_strAlbum, CMusicDatabase::album_strArtists, CMusicDatabase::album_strGenres, CMusicDatabase::album_strLabel, CMusicDatabase::album_strMoods, CMusicDatabase::album_strOrigReleaseDate, CMusicDatabase::album_strReleaseDate, CMusicDatabase::album_strReleaseStatus, CMusicDatabase::album_strReview, CMusicDatabase::album_strStyles, CMusicDatabase::album_strThemes, CMusicDatabase::album_strType, CMusicDatabase::artist_dateAdded, CMusicDatabase::artist_dateModified, CMusicDatabase::artist_dateNew, CMusicDatabase::artist_idArtist, CMusicDatabase::artist_strArtist, CMusicDatabase::artist_strBiography, CMusicDatabase::artist_strBorn, CMusicDatabase::artist_strDied, CMusicDatabase::artist_strDisambiguation, CMusicDatabase::artist_strDisbanded, CMusicDatabase::artist_strFormed, CMusicDatabase::artist_strGender, CMusicDatabase::artist_strGenres, CMusicDatabase::artist_strInstruments, CMusicDatabase::artist_strMoods, CMusicDatabase::artist_strSortName, CMusicDatabase::artist_strStyles, CMusicDatabase::artist_strType, FieldAirDate, FieldAlbum, FieldAlbumArtist, FieldAlbumDuration, FieldAlbumStatus, FieldAlbumType, FieldArtist, FieldArtistSort, FieldArtistType, FieldBandFormed, FieldBiography, FieldBorn, FieldBPM, FieldComment, FieldCountry, FieldDateAdded, FieldDateModified, FieldDateNew, FieldDied, FieldDirector, FieldDisambiguation, FieldDisbanded, FieldEndOffset, FieldEpisodeNumber, FieldEpisodeNumberSpecialSort, FieldFilename, FieldGender, FieldGenre, FieldId, FieldInstruments, FieldLastPlayed, FieldMoods, FieldMPAA, FieldMusicBitRate, FieldMusicLabel, FieldNone, FieldNoOfChannels, FieldNumberOfEpisodes, FieldNumberOfWatchedEpisodes, FieldOrigDate, FieldOriginalTitle, FieldOrigYear, FieldPath, FieldPlaycount, FieldPlot, FieldPlotOutline, FieldRating, FieldReview, FieldSampleRate, FieldSeason, FieldSeasonSpecialSort, FieldSet, FieldSortTitle, FieldStartOffset, FieldStudio, FieldStyles, FieldTagline, FieldThemes, FieldTime, FieldTitle, FieldTop250, FieldTotalDiscs, FieldTrackNumber, FieldTrailer, FieldTvShowStatus, FieldTvShowTitle, FieldUniqueId, FieldUserRating, FieldVotes, FieldWriter, FieldYear, index(), MediaTypeAlbum, MediaTypeArtist, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeNone, MediaTypeSong, MediaTypeTvShow, CMusicDatabase::song_comment, CMusicDatabase::song_dateAdded, CMusicDatabase::song_dateModified, CMusicDatabase::song_dateNew, CMusicDatabase::song_iBitRate, CMusicDatabase::song_iBPM, CMusicDatabase::song_iChannels, CMusicDatabase::song_idSong, CMusicDatabase::song_iDuration, CMusicDatabase::song_iEndOffset, CMusicDatabase::song_iSampleRate, CMusicDatabase::song_iStartOffset, CMusicDatabase::song_iTimesPlayed, CMusicDatabase::song_iTrack, CMusicDatabase::song_lastplayed, CMusicDatabase::song_mood, CMusicDatabase::song_rating, CMusicDatabase::song_strAlbum, CMusicDatabase::song_strArtists, CMusicDatabase::song_strFileName, CMusicDatabase::song_strGenres, CMusicDatabase::song_strPath, CMusicDatabase::song_strReleaseDate, CMusicDatabase::song_strTitle, CMusicDatabase::song_userrating, CMusicDatabase::song_votes, VIDEODB_DETAILS_EPISODE_DATEADDED, VIDEODB_DETAILS_EPISODE_FILE, VIDEODB_DETAILS_EPISODE_LASTPLAYED, VIDEODB_DETAILS_EPISODE_PATH, VIDEODB_DETAILS_EPISODE_PLAYCOUNT, VIDEODB_DETAILS_EPISODE_RATING, VIDEODB_DETAILS_EPISODE_TVSHOW_AIRED, VIDEODB_DETAILS_EPISODE_TVSHOW_MPAA, VIDEODB_DETAILS_EPISODE_TVSHOW_NAME, VIDEODB_DETAILS_EPISODE_TVSHOW_STUDIO, VIDEODB_DETAILS_EPISODE_USER_RATING, VIDEODB_DETAILS_EPISODE_VOTES, VIDEODB_DETAILS_MOVIE_DATEADDED, VIDEODB_DETAILS_MOVIE_FILE, VIDEODB_DETAILS_MOVIE_LASTPLAYED, VIDEODB_DETAILS_MOVIE_PATH, VIDEODB_DETAILS_MOVIE_PLAYCOUNT, VIDEODB_DETAILS_MOVIE_PREMIERED, VIDEODB_DETAILS_MOVIE_RATING, VIDEODB_DETAILS_MOVIE_SET_NAME, VIDEODB_DETAILS_MOVIE_USER_RATING, VIDEODB_DETAILS_MOVIE_VOTES, VIDEODB_DETAILS_MUSICVIDEO_DATEADDED, VIDEODB_DETAILS_MUSICVIDEO_FILE, VIDEODB_DETAILS_MUSICVIDEO_LASTPLAYED, VIDEODB_DETAILS_MUSICVIDEO_PATH, VIDEODB_DETAILS_MUSICVIDEO_PLAYCOUNT, VIDEODB_DETAILS_MUSICVIDEO_PREMIERED, VIDEODB_DETAILS_MUSICVIDEO_USER_RATING, VIDEODB_DETAILS_TVSHOW_DATEADDED, VIDEODB_DETAILS_TVSHOW_LASTPLAYED, VIDEODB_DETAILS_TVSHOW_NUM_EPISODES, VIDEODB_DETAILS_TVSHOW_NUM_SEASONS, VIDEODB_DETAILS_TVSHOW_NUM_WATCHED, VIDEODB_DETAILS_TVSHOW_PATH, VIDEODB_DETAILS_TVSHOW_RATING, VIDEODB_DETAILS_TVSHOW_USER_RATING, VIDEODB_DETAILS_TVSHOW_VOTES, VIDEODB_ID_COUNTRY, VIDEODB_ID_CREDITS, VIDEODB_ID_DIRECTOR, VIDEODB_ID_EPISODE_AIRED, VIDEODB_ID_EPISODE_CREDITS, VIDEODB_ID_EPISODE_DIRECTOR, VIDEODB_ID_EPISODE_EPISODE, VIDEODB_ID_EPISODE_IDENT_ID, VIDEODB_ID_EPISODE_PLOT, VIDEODB_ID_EPISODE_RUNTIME, VIDEODB_ID_EPISODE_SEASON, VIDEODB_ID_EPISODE_SORTEPISODE, VIDEODB_ID_EPISODE_SORTSEASON, VIDEODB_ID_EPISODE_TITLE, VIDEODB_ID_GENRE, VIDEODB_ID_MPAA, VIDEODB_ID_MUSICVIDEO_ALBUM, VIDEODB_ID_MUSICVIDEO_ARTIST, VIDEODB_ID_MUSICVIDEO_DIRECTOR, VIDEODB_ID_MUSICVIDEO_GENRE, VIDEODB_ID_MUSICVIDEO_PLOT, VIDEODB_ID_MUSICVIDEO_RUNTIME, VIDEODB_ID_MUSICVIDEO_STUDIOS, VIDEODB_ID_MUSICVIDEO_TITLE, VIDEODB_ID_MUSICVIDEO_TRACK, VIDEODB_ID_ORIGINALTITLE, VIDEODB_ID_PLOT, VIDEODB_ID_PLOTOUTLINE, VIDEODB_ID_RUNTIME, VIDEODB_ID_SORTTITLE, VIDEODB_ID_STUDIOS, VIDEODB_ID_TAGLINE, VIDEODB_ID_TITLE, VIDEODB_ID_TOP250, VIDEODB_ID_TRAILER, VIDEODB_ID_TV_GENRE, VIDEODB_ID_TV_MPAA, VIDEODB_ID_TV_ORIGINALTITLE, VIDEODB_ID_TV_PLOT, VIDEODB_ID_TV_PREMIERED, VIDEODB_ID_TV_SORTTITLE, VIDEODB_ID_TV_STATUS, VIDEODB_ID_TV_STUDIOS, and VIDEODB_ID_TV_TITLE.
GetField() [3/3]
std::string DatabaseUtils::GetField (Field field, const MediaType & mediaType, DatabaseQueryPart queryPart) static
References DatabaseQueryPartOrderBy, FieldAirDate, FieldAlbum, FieldAlbumArtist, FieldAlbumDuration, FieldAlbumStatus, FieldAlbumType, FieldArtist, FieldArtistSort, FieldArtistType, FieldBandFormed, FieldBiography, FieldBorn, FieldBPM, FieldComment, FieldCompilation, FieldCountry, FieldDateAdded, FieldDateModified, FieldDateNew, FieldDied, FieldDirector, FieldDisambiguation, FieldDisbanded, FieldDiscTitle, FieldEndOffset, FieldEpisodeNumber, FieldEpisodeNumberSpecialSort, FieldFilename, FieldGender, FieldGenre, FieldId, FieldInstruments, FieldLastPlayed, FieldMoods, FieldMPAA, FieldMusicBitRate, FieldMusicLabel, FieldNone, FieldNoOfChannels, FieldNumberOfEpisodes, FieldNumberOfWatchedEpisodes, FieldOrigDate, FieldOriginalTitle, FieldOrigYear, FieldPath, FieldPlaycount, FieldPlot, FieldPlotOutline, FieldRandom, FieldRating, FieldReview, FieldSampleRate, FieldSeason, FieldSeasonSpecialSort, FieldSet, FieldSortTitle, FieldStartOffset, FieldStudio, FieldStyles, FieldTagline, FieldThemes, FieldTime, FieldTitle, FieldTop250, FieldTotalDiscs, FieldTrackNumber, FieldTrailer, FieldTvShowStatus, FieldTvShowTitle, FieldUniqueId, FieldUserRating, FieldVotes, FieldWriter, FieldYear, MediaTypeAlbum, MediaTypeArtist, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeNone, MediaTypeSong, MediaTypeTvShow, VIDEODB_ID_COUNTRY, VIDEODB_ID_CREDITS, VIDEODB_ID_DIRECTOR, VIDEODB_ID_EPISODE_AIRED, VIDEODB_ID_EPISODE_CREDITS, VIDEODB_ID_EPISODE_DIRECTOR, VIDEODB_ID_EPISODE_EPISODE, VIDEODB_ID_EPISODE_IDENT_ID, VIDEODB_ID_EPISODE_PLOT, VIDEODB_ID_EPISODE_RUNTIME, VIDEODB_ID_EPISODE_SEASON, VIDEODB_ID_EPISODE_SORTEPISODE, VIDEODB_ID_EPISODE_SORTSEASON, VIDEODB_ID_EPISODE_TITLE, VIDEODB_ID_GENRE, VIDEODB_ID_MPAA, VIDEODB_ID_MUSICVIDEO_ALBUM, VIDEODB_ID_MUSICVIDEO_ARTIST, VIDEODB_ID_MUSICVIDEO_DIRECTOR, VIDEODB_ID_MUSICVIDEO_GENRE, VIDEODB_ID_MUSICVIDEO_PLOT, VIDEODB_ID_MUSICVIDEO_RUNTIME, VIDEODB_ID_MUSICVIDEO_STUDIOS, VIDEODB_ID_MUSICVIDEO_TITLE, VIDEODB_ID_MUSICVIDEO_TRACK, VIDEODB_ID_ORIGINALTITLE, VIDEODB_ID_PLOT, VIDEODB_ID_PLOTOUTLINE, VIDEODB_ID_RUNTIME, VIDEODB_ID_SORTTITLE, VIDEODB_ID_STUDIOS, VIDEODB_ID_TAGLINE, VIDEODB_ID_TITLE, VIDEODB_ID_TOP250, VIDEODB_ID_TRAILER, VIDEODB_ID_TV_GENRE, VIDEODB_ID_TV_MPAA, VIDEODB_ID_TV_ORIGINALTITLE, VIDEODB_ID_TV_PLOT, VIDEODB_ID_TV_PREMIERED, VIDEODB_ID_TV_SORTTITLE, VIDEODB_ID_TV_STATUS, VIDEODB_ID_TV_STUDIOS, and VIDEODB_ID_TV_TITLE.
Referenced by GetField(), KODI::PLAYLIST::CSmartPlaylistRule::GetField(), GetFieldIndex(), CMusicDatabase::GetOrderFilter(), CGUIDialogMediaFilter::GetRange(), GetSelectFields(), CVideoDatabase::SetSingleValue(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
GetFieldIndex()
int DatabaseUtils::GetFieldIndex (Field field, const MediaType & mediaType) static
References FieldNone, GetField(), and MediaTypeNone.
Referenced by GetDatabaseResults(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
GetFieldValue()
bool DatabaseUtils::GetFieldValue (const dbiplus::field_value & fieldValue, CVariant & variantValue) static
References CVariant::ConstNullVariant, dbiplus::ft_Boolean, dbiplus::ft_Char, dbiplus::ft_Double, dbiplus::ft_Float, dbiplus::ft_Int, dbiplus::ft_Int64, dbiplus::ft_LongDouble, dbiplus::ft_Object, dbiplus::ft_Short, dbiplus::ft_String, dbiplus::ft_UInt, dbiplus::ft_UShort, dbiplus::ft_WChar, dbiplus::ft_WideString, dbiplus::field_value::get_asBool(), dbiplus::field_value::get_asChar(), dbiplus::field_value::get_asDouble(), dbiplus::field_value::get_asFloat(), dbiplus::field_value::get_asInt(), dbiplus::field_value::get_asInt64(), dbiplus::field_value::get_asShort(), dbiplus::field_value::get_asString(), dbiplus::field_value::get_asUInt(), dbiplus::field_value::get_fType(), and dbiplus::field_value::get_isNull().
Referenced by GetDatabaseResults(), and TEST().
GetLimitCount()
size_t DatabaseUtils::GetLimitCount (int end, int start) static
References end().
Referenced by CMusicDatabase::GetAlbumsByWhereJSON(), CMusicDatabase::GetArtistsByWhereJSON(), and CMusicDatabase::GetSongsByWhereJSON().
GetSelectFields()
bool DatabaseUtils::GetSelectFields (const Fields & fields, const MediaType & mediaType, FieldList & selectFields) static
References DatabaseQueryPartSelect, FieldAlbum, FieldArtist, FieldEpisodeNumber, FieldLabel, fields, FieldSeason, FieldTitle, FieldTrackNumber, GetField(), CLog::Log(), LOGDEBUG, MediaTypeAlbum, MediaTypeArtist, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeNone, MediaTypeSong, MediaTypeTvShow, MediaTypeVideo, and MediaTypeVideoCollection.
Referenced by SortUtils::SortFromDataset(), and TEST().
MediaTypeFromVideoContentType()
MediaType DatabaseUtils::MediaTypeFromVideoContentType (VideoDbContentType videoContentType) static
References EPISODES, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeNone, MediaTypeTvShow, MediaTypeVideoCollection, MOVIE_SETS, MOVIES, MUSICVIDEOS, and TVSHOWS.
Referenced by CVideoDatabase::SetSingleValue().
The documentation for this class was generated from the following files:
DatabaseUtils.h
DatabaseUtils.cpp