Kodi Documentation: IMAGE_FILES::CSpecialImageLoaderFactory Class Reference
IMAGE_FILES::CSpecialImageLoaderFactory Class Reference
#include <SpecialImageLoaderFactory.h>
Public Member Functions
CSpecialImageLoaderFactory ()
std::unique_ptr< CTexture > Load (const CImageFileURL &imageFile) const
Private Attributes
std::array< std::unique_ptr< ISpecialImageFileLoader >, 5 > m_specialImageLoaders {}
Constructor & Destructor Documentation
CSpecialImageLoaderFactory()
CSpecialImageLoaderFactory::CSpecialImageLoaderFactory ()
References m_specialImageLoaders.
Member Function Documentation
Load()
std::unique_ptr< CTexture > CSpecialImageLoaderFactory::Load (const CImageFileURL & imageFile) const
References IMAGE_FILES::CImageFileURL::GetSpecialType(), IMAGE_FILES::CImageFileURL::IsSpecialImage(), and m_specialImageLoaders.
Referenced by CTextureCacheJob::LoadImage().
Member Data Documentation
m_specialImageLoaders
std::array<std::unique_ptr<ISpecialImageFileLoader>, 5> IMAGE_FILES::CSpecialImageLoaderFactory::m_specialImageLoaders {} private
Referenced by CSpecialImageLoaderFactory(), and Load().
The documentation for this class was generated from the following files:
SpecialImageLoaderFactory.h
SpecialImageLoaderFactory.cpp