Kodi Documentation: anonymous_namespace{FavouritesService.cpp} Namespace Reference
anonymous_namespace{FavouritesService.cpp} Namespace Reference
Functions
bool IsMediasourceOfFavItemUnlocked (const std::shared_ptr< CFileItem > &item)
bool LoadFromFile (const std::string &strPath, CFileItemList &items)
Function Documentation
IsMediasourceOfFavItemUnlocked()
bool anonymous_namespace{FavouritesService.cpp}::IsMediasourceOfFavItemUnlocked (const std::shared_ptr< CFileItem > & item)
References g_passwordManager, CFavouritesURL::GetAction(), CFileItem::GetPath(), CServiceBroker::GetSettingsComponent(), CFavouritesURL::GetTarget(), KODI::MUSIC::IsAudio(), CFavouritesURL::IsDir(), CGUIPassword::IsMediaFileUnlocked(), CFileItem::IsPicture(), CFavouritesURL::IsValid(), CLog::Log(), LOGERROR, CFavouritesURL::PLAY_MEDIA, and CFavouritesURL::SHOW_PICTURE.
LoadFromFile()
bool anonymous_namespace{FavouritesService.cpp}::LoadFromFile (const std::string & strPath, CFileItemList & items)
References CFileItemList::Add(), CFileItemList::Contains(), CFavouritesURL::GetURL(), CXBMCTinyXML2::LoadFile(), CLog::Log(), LOGERROR, name, and root.