Kodi Documentation: XBMCAddon::AddonClass::Ref< T > Class Template Reference
XBMCAddon::AddonClass::Ref< T > Class Template Reference
#include <AddonClass.h>
Public Member Functions
Ref ()
Ref (const T *_ac)
Ref (Ref< T > const &oref)
template<class O >
Ref (Ref< O > const &oref)
Ref< T > & operator= (Ref< T > const &oref)
T * operator-> () const
operator T* () const
T * get () const
T & getRef () const
~Ref ()
bool isNull () const
bool isNotNull () const
bool isSet () const
bool operator! () const
bool operator== (const AddonClass::Ref< T > &oref) const
bool operator< (const AddonClass::Ref< T > &oref) const
template<class O >
void reset (Ref< O > const &oref)
template<class O >
void reset (O *oref)
void reset ()
Private Attributes
T * ac
Detailed Description
template<class T>
class XBMCAddon::AddonClass::Ref< T >
This class is a smart pointer for a Referenced class.
Constructor & Destructor Documentation
Ref() [1/4]
template<class T > XBMCAddon::AddonClass::Ref< T >::Ref () inline
Ref() [2/4]
template<class T > XBMCAddon::AddonClass::Ref< T >::Ref (const T * _ac) inline
References XBMCAddon::AddonClass::Ref< T >::ac, and refcheck.
Ref() [3/4]
template<class T > XBMCAddon::AddonClass::Ref< T >::Ref (Ref< T > const & oref) inline
References XBMCAddon::AddonClass::Ref< T >::ac, and refcheck.
Ref() [4/4]
template<class T > template<class O > XBMCAddon::AddonClass::Ref< T >::Ref (Ref< O > const & oref) inline
References XBMCAddon::AddonClass::Ref< T >::ac, and refcheck.
~Ref()
template<class T > XBMCAddon::AddonClass::Ref< T >::~Ref () inline
References XBMCAddon::AddonClass::Ref< T >::ac, and refcheck.
Member Function Documentation
get()
template<class T > T * XBMCAddon::AddonClass::Ref< T >::get () const inline
References XBMCAddon::AddonClass::Ref< T >::ac, and refcheck.
Referenced by XBMCAddon::xbmcplugin::addDirectoryItem(), XBMCAddon::RetardedAsyncCallbackHandler::clearPendingCalls(), XBMCAddon::xbmcgui::Window::GetControlById(), XBMCAddon::xbmcgui::ControlList::getListItem(), getListOfAddonClassesAsString(), XBMCAddon::xbmcgui::ControlList::getSelectedItem(), XBMCAddon::xbmcgui::Dialog::info(), XBMCAddon::Python::PythonCallbackHandler::isStateOk(), XBMCAddon::RetardedAsyncCallbackHandler::makePendingCalls(), XBMCAddon::xbmcgui::Window::OnAction(), XBMCAddon::xbmcgui::WindowXML::OnAction(), XBMCAddon::xbmcgui::Window::OnMessage(), XBMCAddon::xbmcgui::WindowXML::OnMessage(), XBMCAddon::AddonClass::Ref< T >::operator=(), XBMCAddon::AddonClass::Ref< T >::reset(), and XBMCAddon::xbmcplugin::setResolvedUrl().
getRef()
template<class T > T & XBMCAddon::AddonClass::Ref< T >::getRef () const inline
References XBMCAddon::AddonClass::Ref< T >::ac, and refcheck.
isNotNull()
template<class T > bool XBMCAddon::AddonClass::Ref< T >::isNotNull () const inline
References XBMCAddon::AddonClass::Ref< T >::ac, and refcheck.
Referenced by PythonBindings::handleInterpRegistrationForClean(), XBMCAddon::Python::PythonCallbackHandler::isStateOk(), and XBMCAddon::xbmcgui::Window::OnMessage().
isNull()
template<class T > bool XBMCAddon::AddonClass::Ref< T >::isNull () const inline
References XBMCAddon::AddonClass::Ref< T >::ac, and refcheck.
Referenced by XBMCAddon::Python::PythonLanguageHook::GetIfExists(), and XBMCAddon::xbmcgui::ControlList::internAddListItem().
isSet()
template<class T > bool XBMCAddon::AddonClass::Ref< T >::isSet () const inline
References XBMCAddon::AddonClass::Ref< T >::ac, and refcheck.
Referenced by XBMCAddon::xbmc::Player::playStream().
operator T*()
template<class T > XBMCAddon::AddonClass::Ref< T >::operator T* () const inline
This operator doubles as the value in a boolean expression.
operator!()
template<class T > bool XBMCAddon::AddonClass::Ref< T >::operator! () const inline
References XBMCAddon::AddonClass::Ref< T >::ac, and refcheck.
operator->()
template<class T > T * XBMCAddon::AddonClass::Ref< T >::operator-> () const inline
References XBMCAddon::AddonClass::Ref< T >::ac, and refcheck.
operator<()
template<class T > bool XBMCAddon::AddonClass::Ref< T >::operator< (const AddonClass::Ref< T > & oref) const inline
References XBMCAddon::AddonClass::Ref< T >::ac, and refcheck.
operator=()
template<class T > Ref< T > & XBMCAddon::AddonClass::Ref< T >::operator= (Ref< T > const & oref) inline
operator= should work with either another smart pointer or a pointer since it will be able to convert a pointer to a smart pointer using one of the above constructors.
Note: There is a trick here. The temporary variable is necessary because otherwise the following code will fail:
Ref<T> ptr = new T; ptr = ptr;
What happens without the tmp is the dereference is called first so the object ends up deleted and then the reference happens on a deleted object. The order is reversed in the following.
Note: Operator= is ambiguous if you define both an operator=(Ref<T>&) and an operator=(T*). I'm opting for the route the boost took here figuring it has more history behind it.
References XBMCAddon::AddonClass::Ref< T >::ac, XBMCAddon::AddonClass::Ref< T >::get(), and refcheck.
operator==()
template<class T > bool XBMCAddon::AddonClass::Ref< T >::operator== (const AddonClass::Ref< T > & oref) const inline
References XBMCAddon::AddonClass::Ref< T >::ac, and refcheck.
reset() [1/3]
template<class T > void XBMCAddon::AddonClass::Ref< T >::reset () inline
References XBMCAddon::AddonClass::Ref< T >::ac, and refcheck.
reset() [2/3]
template<class T > template<class O > void XBMCAddon::AddonClass::Ref< T >::reset (O * oref) inline
References refcheck.
reset() [3/3]
template<class T > template<class O > void XBMCAddon::AddonClass::Ref< T >::reset (Ref< O > const & oref) inline
References XBMCAddon::AddonClass::Ref< T >::get(), and refcheck.
Member Data Documentation
ac
template<class T > T* XBMCAddon::AddonClass::Ref< T >::ac private
Referenced by XBMCAddon::AddonClass::Ref< T >::get(), XBMCAddon::AddonClass::Ref< T >::getRef(), XBMCAddon::AddonClass::Ref< T >::isNotNull(), XBMCAddon::AddonClass::Ref< T >::isNull(), XBMCAddon::AddonClass::Ref< T >::isSet(), XBMCAddon::AddonClass::Ref< P1 >::operator P1 *(), XBMCAddon::AddonClass::Ref< T >::operator!(), XBMCAddon::AddonClass::Ref< T >::operator->(), XBMCAddon::AddonClass::Ref< T >::operator<(), XBMCAddon::AddonClass::Ref< T >::operator=(), XBMCAddon::AddonClass::Ref< T >::operator==(), XBMCAddon::AddonClass::Ref< T >::Ref(), XBMCAddon::AddonClass::Ref< T >::Ref(), XBMCAddon::AddonClass::Ref< T >::Ref(), XBMCAddon::AddonClass::Ref< T >::reset(), and XBMCAddon::AddonClass::Ref< T >::~Ref().
The documentation for this class was generated from the following file:
AddonClass.h