Kodi Documentation: CUtf8Utils Class Reference
CUtf8Utils Class Reference
#include <Utf8Utils.h>
Public Types
enum utf8CheckResult { plainAscii = -1 , hiAscii = 0 , utf8string = 1 }
Static Public Member Functions
static utf8CheckResult checkStrForUtf8 (const std::string &str)
static bool isValidUtf8 (const std::string &str)
static size_t FindValidUtf8Char (const std::string &str, const size_t startPos=0)
static size_t RFindValidUtf8Char (const std::string &str, const size_t startPos)
static size_t SizeOfUtf8Char (const std::string &str, const size_t charStart=0)
Static Private Member Functions
static size_t SizeOfUtf8Char (const char *const str)
Member Enumeration Documentation
utf8CheckResult
enum CUtf8Utils::utf8CheckResult
Enumerator
plainAscii
hiAscii
utf8string
Member Function Documentation
checkStrForUtf8()
CUtf8Utils::utf8CheckResult CUtf8Utils::checkStrForUtf8 (const std::string & str) static
Check given string for valid UTF-8 sequences
Parameters
str string to check
Returns
result of check, "plainAscii" for empty string
References hiAscii, plainAscii, SizeOfUtf8Char(), and utf8string.
Referenced by isValidUtf8(), and CRegExp::requireUtf8().
FindValidUtf8Char()
size_t CUtf8Utils::FindValidUtf8Char (const std::string & str, const size_t startPos = 0) static
References SizeOfUtf8Char().
isValidUtf8()
static bool CUtf8Utils::isValidUtf8 (const std::string & str) inline static
References checkStrForUtf8(), and hiAscii.
Referenced by CCharsetDetection::checkConversion(), CDVDSubtitleStream::Open(), CXBMCTinyXML::Parse(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and CCharsetConverter::unknownToUTF8().
RFindValidUtf8Char()
size_t CUtf8Utils::RFindValidUtf8Char (const std::string & str, const size_t startPos) static
References SizeOfUtf8Char().
Referenced by CRegExp::PrivateRegFind().
SizeOfUtf8Char() [1/2]
size_t CUtf8Utils::SizeOfUtf8Char (const char *const str) inline static private
SizeOfUtf8Char() [2/2]
size_t CUtf8Utils::SizeOfUtf8Char (const std::string & str, const size_t charStart = 0) inline static
References SizeOfUtf8Char().
Referenced by checkStrForUtf8(), FindValidUtf8Char(), RFindValidUtf8Char(), and SizeOfUtf8Char().
The documentation for this class was generated from the following files:
Utf8Utils.h
Utf8Utils.cpp