Kodi Documentation: FFmpeg.cpp File Reference
FFmpeg.cpp File Reference
#include "cores/FFmpeg.h"
#include "ServiceBroker.h"
#include "settings/AdvancedSettings.h"
#include "settings/SettingsComponent.h"
#include "threads/CriticalSection.h"
#include "threads/Thread.h"
#include "utils/StringUtils.h"
#include "utils/log.h"
#include <libavcodec/bsf.h>
#include <map>
#include <mutex>
Namespaces
namespace FFMPEG_HELP_TOOLS
Functions
std::string FFMPEG_HELP_TOOLS::FFMpegErrorToString (int err)
void ff_flush_avutil_log_buffers (void)
void ff_avutil_log (void *ptr, int level, const char *format, va_list va)
FFmpegExtraData GetPacketExtradata (const AVPacket *pkt, const AVCodecParameters *codecPar)
Variables
static thread_local CFFmpegLog * CFFmpegLogTls
static CCriticalSection m_logSection
std::map< const CThread *, std::string > g_logbuffer
Function Documentation
ff_avutil_log()
void ff_avutil_log (void * ptr, int level, const char * format, va_list va)
References KODI::UTILS::StringUtils::Format(), KODI::UTILS::StringUtils::FormatV(), g_logbuffer, CThread::GetCurrentThread(), CServiceBroker::GetLogging(), CFFmpegLog::GetLogLevel(), CServiceBroker::GetSettingsComponent(), CLog::Log(), LOG_LEVEL_NORMAL, LOGDEBUG, LOGERROR, LOGFFMPEG, LOGINFO, and m_logSection.
Referenced by CApplication::Create().
ff_flush_avutil_log_buffers()
void ff_flush_avutil_log_buffers (void)
References g_logbuffer, and m_logSection.
Referenced by CDVDDemuxFFmpeg::~CDVDDemuxFFmpeg().
GetPacketExtradata()
FFmpegExtraData GetPacketExtradata (const AVPacket * pkt, const AVCodecParameters * codecPar)
References f, LOGDEBUG, and LOGERROR.
Referenced by CDVDDemuxFFmpeg::ParsePacket(), and CDVDDemuxClient::ParsePacket().
Variable Documentation
CFFmpegLogTls
thread_local CFFmpegLog* CFFmpegLogTls static
Referenced by CFFmpegLog::ClearLogLevel(), CFFmpegLog::GetLogLevel(), and CFFmpegLog::SetLogLevel().
g_logbuffer
std::map<const CThread*, std::string> g_logbuffer
Referenced by ff_avutil_log(), and ff_flush_avutil_log_buffers().
m_logSection
CCriticalSection m_logSection static
Referenced by ff_avutil_log(), and ff_flush_avutil_log_buffers().