Kodi Documentation: KODI::GAME::CGUIControllerList Class Reference
KODI::GAME::CGUIControllerList Class Reference
Games
#include <GUIControllerList.h>
Public Member Functions
CGUIControllerList (CGUIWindow *window, IFeatureList *featureList, GameClientPtr gameClient, std::string controllerId)
Create a GUI controller list.
~CGUIControllerList () override
bool Initialize () override
Initialize the resource.
void Deinitialize () override
Deinitialize the resource.
bool Refresh (const std::string &controllerId) override
Refresh the contents of the list.
void OnFocus (unsigned int controllerIndex) override
void OnSelect (unsigned int controllerIndex) override
The specified controller has been selected.
int GetFocusedController () const override
Get the index of the focused controller.
void ResetController () override
Reset the focused controller.
Public Member Functions inherited from KODI::GAME::IControllerList
virtual ~IControllerList ()=default
Private Member Functions
bool RefreshControllers (void)
void CleanupButtons (void)
void OnEvent (const ADDON::AddonEvent &event)
Private Attributes
CGUIWindow *const m_guiWindow
IFeatureList *const m_featureList
CGUIControlGroupList * m_controllerList = nullptr
CGUIButtonControl * m_controllerButton = nullptr
ControllerVector m_controllers
int m_focusedController = -1
GameClientPtr m_gameClient
std::string m_controllerId
Constructor & Destructor Documentation
CGUIControllerList()
CGUIControllerList::CGUIControllerList (CGUIWindow * window, IFeatureList * featureList, GameClientPtr gameClient, std::string controllerId)
Create a GUI controller list.
Parameters
window The GUI window handle
featureList The controller interface for the feature list
gameClient A gameclient used to filter controllers
controllerId A controller ID used to filter controllers (only the specified controller will be shown, or the default controller if the specified controller isn't installed)
References m_featureList.
~CGUIControllerList()
KODI::GAME::CGUIControllerList::~CGUIControllerList () inline override
References Deinitialize().
Member Function Documentation
CleanupButtons()
void CGUIControllerList::CleanupButtons (void) private
References CGUIControlGroupList::ClearAll(), and m_controllerList.
Referenced by Deinitialize(), and Refresh().
Deinitialize()
void CGUIControllerList::Deinitialize () override virtual
Deinitialize the resource.
Implements KODI::GAME::IControllerList.
References CleanupButtons(), ADDON::CAddonMgr::Events(), CServiceBroker::GetAddonMgr(), m_controllerButton, and m_controllerList.
Referenced by ~CGUIControllerList().
GetFocusedController()
int KODI::GAME::CGUIControllerList::GetFocusedController () const inline override virtual
Get the index of the focused controller.
Returns
The index of the focused controller, or -1 if no controller has been focused yet
Implements KODI::GAME::IControllerList.
References m_focusedController.
Initialize()
bool CGUIControllerList::Initialize () override virtual
Initialize the resource.
Returns
true if the resource is initialized and can be used false if the resource failed to initialize and must not be used
Implements KODI::GAME::IControllerList.
References CONTROL_CONTROLLER_BUTTON_TEMPLATE, CONTROL_CONTROLLER_LIST, ADDON::CAddonMgr::Events(), CServiceBroker::GetAddonMgr(), CGUIControlLookup::GetControl(), m_controllerButton, m_controllerList, m_guiWindow, OnEvent(), Refresh(), and CGUIControl::SetVisible().
OnEvent()
void CGUIControllerList::OnEvent (const ADDON::AddonEvent & event) private
References ADDON::AddonEvent::addonId, CONTROL_CONTROLLER_LIST, CServiceBroker::GetAppMessenger(), CGUIControl::GetID(), GUI_MSG_REFRESH_LIST, m_guiWindow, and CGUIMessage::SetStringParam().
Referenced by Initialize().
OnFocus()
void CGUIControllerList::OnFocus (unsigned int controllerIndex) override virtual
Todo:
Activate controller for all game controller controls
Implements KODI::GAME::IControllerList.
References KODI::GAME::CGUIGameController::ActivateController(), CONTROL_CONTROLLER_DESCRIPTION, CONTROL_GAME_CONTROLLER, CGUIControlLookup::GetControl(), CGUIControl::GetID(), GUI_MSG_LABEL_SET, KODI::GAME::IFeatureList::Load(), m_controllers, m_featureList, m_focusedController, m_guiWindow, CGUIWindow::OnMessage(), and CGUIMessage::SetLabel().
OnSelect()
void CGUIControllerList::OnSelect (unsigned int controllerIndex) override virtual
The specified controller has been selected.
Parameters
controllerIndex The index of the controller being selected
Implements KODI::GAME::IControllerList.
References m_featureList, and KODI::GAME::IFeatureList::OnSelect().
Refresh()
bool CGUIControllerList::Refresh (const std::string & controllerId) override virtual
Refresh the contents of the list.
Parameters
controllerId The controller to focus, or empty to leave focus unchanged
Returns
True if the list was changed
Implements KODI::GAME::IControllerList.
References CGUIControlGroupList::AddControl(), CleanupButtons(), CGUIControl::GetID(), GUI_MSG_SETFOCUS, m_controllerButton, m_controllerList, m_controllers, m_focusedController, m_guiWindow, MAX_CONTROLLER_COUNT, CGUIWindow::OnMessage(), and RefreshControllers().
Referenced by Initialize().
RefreshControllers()
bool CGUIControllerList::RefreshControllers (void) private
References KODI::GAME::CGameServices::GetControllers(), KODI::GAME::CGameServices::GetDefaultController(), CServiceBroker::GetGameServices(), KODI::GAME::CControllerHub::IsControllerAccepted(), m_controllerId, m_controllers, and m_gameClient.
Referenced by Refresh().
ResetController()
void CGUIControllerList::ResetController () override virtual
Reset the focused controller.
Todo:
Choose peripheral
Implements KODI::GAME::IControllerList.
References CServiceBroker::GetPeripherals(), m_controllers, m_focusedController, PERIPHERALS::CPeripherals::ResetButtonMaps(), and CGUIDialogYesNo::ShowAndGetInput().
Member Data Documentation
m_controllerButton
CGUIButtonControl* KODI::GAME::CGUIControllerList::m_controllerButton = nullptr private
Referenced by Deinitialize(), Initialize(), and Refresh().
m_controllerId
std::string KODI::GAME::CGUIControllerList::m_controllerId private
Referenced by RefreshControllers().
m_controllerList
CGUIControlGroupList* KODI::GAME::CGUIControllerList::m_controllerList = nullptr private
Referenced by CleanupButtons(), Deinitialize(), Initialize(), and Refresh().
m_controllers
ControllerVector KODI::GAME::CGUIControllerList::m_controllers private
Referenced by OnFocus(), Refresh(), RefreshControllers(), and ResetController().
m_featureList
IFeatureList* const KODI::GAME::CGUIControllerList::m_featureList private
Referenced by CGUIControllerList(), OnFocus(), and OnSelect().
m_focusedController
int KODI::GAME::CGUIControllerList::m_focusedController = -1 private
Referenced by GetFocusedController(), OnFocus(), Refresh(), and ResetController().
m_gameClient
GameClientPtr KODI::GAME::CGUIControllerList::m_gameClient private
Referenced by RefreshControllers().
m_guiWindow
CGUIWindow* const KODI::GAME::CGUIControllerList::m_guiWindow private
Referenced by Initialize(), OnEvent(), OnFocus(), and Refresh().
The documentation for this class was generated from the following files:
GUIControllerList.h
GUIControllerList.cpp