Kodi Documentation: CAESinkDirectSound Class Reference
CAESinkDirectSound Class Reference
#include <AESinkDirectSound.h>
Public Member Functions
virtual const char * GetName ()
CAESinkDirectSound ()
virtual ~CAESinkDirectSound ()
virtual bool Initialize (AEAudioFormat &format, std::string &device)
virtual void Deinitialize ()
virtual void Stop ()
virtual void Drain ()
virtual void GetDelay (AEDelayStatus &status)
Return a timestamped status structure with delay and sink info.
virtual double GetCacheTotal ()
virtual unsigned int AddPackets (uint8_t **data, unsigned int frames, unsigned int offset)
Adds packets to be sent out, this routine MUST block or sleep.
Public Member Functions inherited from IAESink
IAESink ()=default
virtual ~IAESink ()=default
virtual double GetLatency ()
virtual void AddPause (unsigned int millis)
instruct the sink to add a pause
virtual bool HasVolume ()
virtual void SetVolume (float volume)
Static Public Member Functions
static void Register ()
static std::unique_ptr< IAESink > Create (std::string &device, AEAudioFormat &desiredFormat)
static std::string GetDefaultDevice ()
static void EnumerateDevicesEx (AEDeviceInfoList &deviceInfoList, bool force=false)
Private Member Functions
void AEChannelsFromSpeakerMask (DWORD speakers)
DWORD SpeakerMaskFromAEChannels (const CAEChannelInfo &channels)
void CheckPlayStatus ()
bool UpdateCacheStatus ()
unsigned int GetSpace ()
const char * dserr2str (int err)
Private Attributes
Microsoft::WRL::ComPtr< IDirectSoundBuffer > m_pBuffer
Microsoft::WRL::ComPtr< IDirectSound > m_pDSound
AEAudioFormat m_format
enum AEDataFormat m_encodedFormat
CAEChannelInfo m_channelLayout
std::string m_device
unsigned int m_AvgBytesPerSec
unsigned int m_dwChunkSize
unsigned int m_dwFrameSize
unsigned int m_dwBufferLen
unsigned int m_BufferOffset
unsigned int m_CacheLen
unsigned int m_BufferTimeouts
bool m_running
bool m_initialized
bool m_isDirtyDS
CCriticalSection m_runLock
Constructor & Destructor Documentation
CAESinkDirectSound()
CAESinkDirectSound::CAESinkDirectSound ()
References m_channelLayout, and CAEChannelInfo::Reset().
~CAESinkDirectSound()
CAESinkDirectSound::~CAESinkDirectSound () virtual
References Deinitialize().
Member Function Documentation
AddPackets()
unsigned int CAESinkDirectSound::AddPackets (uint8_t ** data, unsigned int frames, unsigned int offset) virtual
Adds packets to be sent out, this routine MUST block or sleep.
Parameters
data array of pointers to planes holding audio data
frames number of audio frames in data
offset offset in frames where audio data starts
Returns
number of frames consumed by the sink
Implements IAESink.
References CheckPlayStatus(), data(), GetSpace(), LOGDEBUG, LOGERROR, m_AvgBytesPerSec, m_BufferOffset, m_CacheLen, m_dwBufferLen, m_dwChunkSize, m_dwFrameSize, m_format, AEAudioFormat::m_frameSize, m_initialized, m_isDirtyDS, m_pBuffer, and KODI::TIME::Sleep().
AEChannelsFromSpeakerMask()
void CAESinkDirectSound::AEChannelsFromSpeakerMask (DWORD speakers) private
References AEChannelNamesDS, DS_SPEAKER_COUNT, DSChannelOrder, m_channelLayout, and CAEChannelInfo::Reset().
Referenced by Initialize().
CheckPlayStatus()
void CAESinkDirectSound::CheckPlayStatus () private
References FAILED, CWIN32Util::FormatHRESULT(), LOGDEBUG, LOGERROR, m_CacheLen, and m_pBuffer.
Referenced by AddPackets().
Create()
std::unique_ptr< IAESink > CAESinkDirectSound::Create (std::string & device, AEAudioFormat & desiredFormat) static
Referenced by Register().
Deinitialize()
void CAESinkDirectSound::Deinitialize () virtual
Implements IAESink.
References LOGDEBUG, m_BufferOffset, m_CacheLen, m_dwBufferLen, m_dwChunkSize, m_initialized, m_pBuffer, and m_pDSound.
Referenced by ~CAESinkDirectSound().
Drain()
void CAESinkDirectSound::Drain () virtual
Reimplemented from IAESink.
References LOGERROR, m_BufferOffset, m_initialized, m_isDirtyDS, m_pBuffer, and UpdateCacheStatus().
dserr2str()
const char * CAESinkDirectSound::dserr2str (int err) private
EnumerateDevicesEx()
void CAESinkDirectSound::EnumerateDevicesEx (AEDeviceInfoList & deviceInfoList, bool force = false) static
References AE_DEVTYPE_PCM, AE_FMT_FLOAT, AE_FMT_RAW, winEndpointsToAEDeviceType::aeDeviceType, CLSID_MMDeviceEnumerator, DS_SPEAKER_COUNT, EXIT_ON_FAILURE, FAILED, CWIN32Util::FormatHRESULT(), KODI::PLATFORM::WINDOWS::FromW(), GetDefaultDevice(), IID_IAudioClient, IID_IMMDeviceEnumerator, layoutsByChCount, LOGERROR, CAEDeviceInfo::m_channels, CAEDeviceInfo::m_dataFormats, CAEDeviceInfo::m_deviceName, CAEDeviceInfo::m_deviceType, CAEDeviceInfo::m_displayName, CAEDeviceInfo::m_displayNameExtra, CAEDeviceInfo::m_sampleRates, CAEDeviceInfo::m_streamTypes, CAEDeviceInfo::m_wantsIECPassthrough, PKEY_AudioEndpoint_FormFactor, PKEY_AudioEndpoint_GUID, PKEY_AudioEngine_DeviceFormat, PKEY_Device_FriendlyName, CAEChannelInfo::Reset(), CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, winEndpoints, and winEndpointsToAEDeviceType::winEndpointType.
Referenced by Register().
GetCacheTotal()
double CAESinkDirectSound::GetCacheTotal () virtual
returns total cache capacity in seconds
Implements IAESink.
References m_AvgBytesPerSec, and m_dwBufferLen.
GetDefaultDevice()
std::string CAESinkDirectSound::GetDefaultDevice () static
References winEndpointsToAEDeviceType::aeDeviceType, CLSID_MMDeviceEnumerator, EXIT_ON_FAILURE, KODI::PLATFORM::WINDOWS::FromW(), IID_IMMDeviceEnumerator, PKEY_AudioEndpoint_FormFactor, PKEY_AudioEndpoint_GUID, and winEndpoints.
Referenced by EnumerateDevicesEx(), and Initialize().
GetDelay()
void CAESinkDirectSound::GetDelay (AEDelayStatus & status) virtual
Return a timestamped status structure with delay and sink info.
Parameters
status structure filled with sink status
returns current cached data duration in seconds
Implements IAESink.
References m_AvgBytesPerSec, m_CacheLen, m_initialized, m_isDirtyDS, AEDelayStatus::SetDelay(), and UpdateCacheStatus().
GetName()
virtual const char * CAESinkDirectSound::GetName () inline virtual
Implements IAESink.
GetSpace()
unsigned int CAESinkDirectSound::GetSpace () private
References m_CacheLen, m_dwBufferLen, m_dwChunkSize, m_isDirtyDS, m_runLock, and UpdateCacheStatus().
Referenced by AddPackets().
Initialize()
bool CAESinkDirectSound::Initialize (AEAudioFormat & format, std::string & device) virtual
Better position accuracy
Vista+ accurate position
Allows background playing
Implements IAESink.
References AE_FMT_FLOAT, AE_FMT_RAW, AE_FMT_S16NE, AEChannelsFromSpeakerMask(), CAEChannelInfo::Count(), CAEUtil::DataFormatToStr(), DSEnumCallback(), FAILED, CWIN32Util::FormatHRESULT(), KODI::PLATFORM::WINDOWS::FromW(), g_hWnd, GetDefaultDevice(), CAESinkFactoryWin::GetRendererDetails(), CLog::Log(), LOGDEBUG, LOGERROR, m_AvgBytesPerSec, m_BufferOffset, m_CacheLen, m_channelLayout, m_device, m_dwBufferLen, m_dwChunkSize, m_dwFrameSize, m_encodedFormat, m_format, m_initialized, m_isDirtyDS, m_pBuffer, m_pDSound, and SpeakerMaskFromAEChannels().
Register()
void CAESinkDirectSound::Register () static
References Create(), AE::AESinkRegEntry::createFunc, EnumerateDevicesEx(), AE::AESinkRegEntry::enumerateFunc, AE::CAESinkFactory::RegisterSink(), and AE::AESinkRegEntry::sinkName.
Referenced by CWinSystemWin32::CWinSystemWin32().
SpeakerMaskFromAEChannels()
DWORD CAESinkDirectSound::SpeakerMaskFromAEChannels (const CAEChannelInfo & channels) private
References AEChannelNamesDS, DS_SPEAKER_COUNT, and DSChannelOrder.
Referenced by Initialize().
Stop()
void CAESinkDirectSound::Stop () virtual
References m_pBuffer.
UpdateCacheStatus()
bool CAESinkDirectSound::UpdateCacheStatus () private
References CWIN32Util::FormatHRESULT(), CLog::Log(), LOGERROR, LOGWARNING, m_BufferOffset, m_BufferTimeouts, m_CacheLen, m_dwBufferLen, m_isDirtyDS, m_pBuffer, and m_runLock.
Referenced by Drain(), GetDelay(), and GetSpace().
Member Data Documentation
m_AvgBytesPerSec
unsigned int CAESinkDirectSound::m_AvgBytesPerSec private
Referenced by AddPackets(), GetCacheTotal(), GetDelay(), and Initialize().
m_BufferOffset
unsigned int CAESinkDirectSound::m_BufferOffset private
Referenced by AddPackets(), Deinitialize(), Drain(), Initialize(), and UpdateCacheStatus().
m_BufferTimeouts
unsigned int CAESinkDirectSound::m_BufferTimeouts private
Referenced by UpdateCacheStatus().
m_CacheLen
unsigned int CAESinkDirectSound::m_CacheLen private
Referenced by AddPackets(), CheckPlayStatus(), Deinitialize(), GetDelay(), GetSpace(), Initialize(), and UpdateCacheStatus().
m_channelLayout
CAEChannelInfo CAESinkDirectSound::m_channelLayout private
Referenced by AEChannelsFromSpeakerMask(), CAESinkDirectSound(), and Initialize().
m_device
std::string CAESinkDirectSound::m_device private
Referenced by Initialize().
m_dwBufferLen
unsigned int CAESinkDirectSound::m_dwBufferLen private
Referenced by AddPackets(), Deinitialize(), GetCacheTotal(), GetSpace(), Initialize(), and UpdateCacheStatus().
m_dwChunkSize
unsigned int CAESinkDirectSound::m_dwChunkSize private
Referenced by AddPackets(), Deinitialize(), GetSpace(), and Initialize().
m_dwFrameSize
unsigned int CAESinkDirectSound::m_dwFrameSize private
Referenced by AddPackets(), and Initialize().
m_encodedFormat
enum AEDataFormat CAESinkDirectSound::m_encodedFormat private
Referenced by Initialize().
m_format
AEAudioFormat CAESinkDirectSound::m_format private
Referenced by AddPackets(), and Initialize().
m_initialized
bool CAESinkDirectSound::m_initialized private
Referenced by AddPackets(), Deinitialize(), Drain(), GetDelay(), and Initialize().
m_isDirtyDS
bool CAESinkDirectSound::m_isDirtyDS private
Referenced by AddPackets(), Drain(), GetDelay(), GetSpace(), Initialize(), and UpdateCacheStatus().
m_pBuffer
Microsoft::WRL::ComPtr<IDirectSoundBuffer> CAESinkDirectSound::m_pBuffer private
Referenced by AddPackets(), CheckPlayStatus(), Deinitialize(), Drain(), Initialize(), Stop(), and UpdateCacheStatus().
m_pDSound
Microsoft::WRL::ComPtr<IDirectSound> CAESinkDirectSound::m_pDSound private
Referenced by Deinitialize(), and Initialize().
m_runLock
CCriticalSection CAESinkDirectSound::m_runLock private
Referenced by GetSpace(), and UpdateCacheStatus().
m_running
bool CAESinkDirectSound::m_running private
The documentation for this class was generated from the following files:
AESinkDirectSound.h
AESinkDirectSound.cpp