Kodi Documentation: CApplicationPlayer Class Reference
CApplicationPlayer Class Reference
#include <ApplicationPlayer.h>
Classes
struct SNextItem
Public Member Functions
CApplicationPlayer ()=default
void ClosePlayer ()
void ResetPlayer ()
std::string GetCurrentPlayer () const
float GetPlaySpeed () const
float GetPlayTempo () const
bool HasPlayer () const
bool OpenFile (const CFileItem &item, const CPlayerOptions &options, const CPlayerCoreFactory &factory, const std::string &playerName, IPlayerCallback &callback)
void OpenNext (const CPlayerCoreFactory &factory)
void SetPlaySpeed (float speed)
void SetTempo (float tempo)
void FrameAdvance (int frames)
void FrameMove ()
void Render (bool clear, uint32_t alpha=255, bool gui=true)
void FlushRenderer ()
void SetRenderViewMode (int mode, float zoom, float par, float shift, bool stretch)
float GetRenderAspectRatio () const
bool GetRects (CRect &source, CRect &dest, CRect &view) const
unsigned int GetOrientation () const
void TriggerUpdateResolution ()
bool IsRenderingVideo () const
bool IsRenderingGuiLayer () const
bool IsRenderingVideoLayer () const
bool Supports (EINTERLACEMETHOD method) const
EINTERLACEMETHOD GetDeinterlacingMethodDefault () const
bool Supports (ESCALINGMETHOD method) const
bool Supports (ERENDERFEATURE feature) const
unsigned int RenderCaptureAlloc ()
void RenderCapture (unsigned int captureId, unsigned int width, unsigned int height, int flags=0)
void RenderCaptureRelease (unsigned int captureId)
bool RenderCaptureGetPixels (unsigned int captureId, unsigned int millis, uint8_t *buffer, unsigned int size)
bool IsExternalPlaying () const
bool IsRemotePlaying () const
std::string GetName () const
Get the name of the player in use.
void AddSubtitle (const std::string &strSubPath)
bool CanPause () const
bool CanSeek () const
int GetAudioDelay () const
void GetAudioCapabilities (std::vector< IPlayerAudioCaps > &caps) const
int GetAudioStream ()
int GetAudioStreamCount () const
void GetAudioStreamInfo (int index, AudioStreamInfo &info) const
int GetCacheLevel () const
float GetCachePercentage () const
int GetChapterCount () const
int GetChapter () const
void GetChapterName (std::string &strChapterName, int chapterIdx=-1) const
int64_t GetChapterPos (int chapterIdx=-1) const
float GetPercentage () const
std::string GetPlayerState ()
KODI::PLAYLIST::Id GetPreferredPlaylist () const
int GetSubtitleDelay () const
int GetSubtitle ()
void GetSubtitleCapabilities (std::vector< IPlayerSubtitleCaps > &caps) const
int GetSubtitleCount () const
void GetSubtitleStreamInfo (int index, SubtitleStreamInfo &info) const
bool GetSubtitleVisible () const
bool HasTeletextCache () const
std::shared_ptr< TextCacheStruct_t > GetTeletextCache ()
int64_t GetTime () const
int64_t GetMinTime () const
int64_t GetMaxTime () const
time_t GetStartTime () const
int64_t GetTotalTime () const
int GetVideoStream ()
int GetVideoStreamCount () const
void GetVideoStreamInfo (int streamId, VideoStreamInfo &info) const
int GetPrograms (std::vector< ProgramInfo > &programs)
void SetProgram (int progId)
int GetProgramsCount () const
bool HasAudio () const
MenuType GetSupportedMenuType () const
Get the supported menu type.
bool HasVideo () const
bool HasGame () const
bool HasRDS () const
bool IsCaching () const
bool IsInMenu () const
bool IsPaused () const
bool IsPausedPlayback () const
bool IsPassthrough () const
bool IsPlaying () const
bool IsPlayingAudio () const
bool IsPlayingVideo () const
bool IsPlayingGame () const
bool IsPlayingRDS () const
void LoadPage (int p, int sp, unsigned char *buffer)
bool OnAction (const CAction &action)
void OnNothingToQueueNotify ()
void Pause ()
bool QueueNextFile (const CFileItem &file)
void Seek (bool bPlus=true, bool bLargeStep=false, bool bChapterOverride=false)
int SeekChapter (int iChapter)
void SeekPercentage (float fPercent=0)
bool SeekScene (Direction seekDirection)
void SeekTime (int64_t iTime=0)
void SeekTimeRelative (int64_t iTime=0)
void SetAudioStream (int iStream)
void SetAVDelay (float fValue=0.0f)
void SetDynamicRangeCompression (long drc)
void SetMute (bool bOnOff)
bool SetPlayerState (const std::string &state)
void SetSubtitle (int iStream)
void SetSubTitleDelay (float fValue=0.0f)
void SetSubtitleVisible (bool bVisible)
void SetSubtitleVerticalPosition (const int value, bool save)
Set the subtitle vertical position, it depends on current screen resolution.
void SetTime (int64_t time)
void SetTotalTime (int64_t time)
void SetVideoStream (int iStream)
void SetVolume (float volume)
void SetSpeed (float speed)
bool SupportsTempo () const
CVideoSettings GetVideoSettings () const
void SetVideoSettings (CVideoSettings &settings)
CSeekHandler & GetSeekHandler ()
const CSeekHandler & GetSeekHandler () const
void SetUpdateStreamDetails ()
bool HasGameAgent () const
Check if any players are playing a game.
Public Member Functions inherited from IApplicationComponent
virtual ~IApplicationComponent ()=default
Private Member Functions
std::shared_ptr< const IPlayer > GetInternal () const
std::shared_ptr< IPlayer > GetInternal ()
void CreatePlayer (const CPlayerCoreFactory &factory, const std::string &player, IPlayerCallback &callback)
void CloseFile (bool reopen=false)
Private Attributes
std::shared_ptr< IPlayer > m_pPlayer
CCriticalSection m_playerLock
CSeekHandler m_seekHandler
XbmcThreads::EndTime m_audioStreamUpdate
int m_iAudioStream
XbmcThreads::EndTime m_videoStreamUpdate
int m_iVideoStream
XbmcThreads::EndTime m_subtitleStreamUpdate
int m_iSubtitleStream
struct CApplicationPlayer::SNextItem m_nextItem
Constructor & Destructor Documentation
CApplicationPlayer()
CApplicationPlayer::CApplicationPlayer () default
Member Function Documentation
AddSubtitle()
void CApplicationPlayer::AddSubtitle (const std::string & strSubPath)
References GetInternal().
Referenced by CGUIDialogSubtitleSettings::OnSettingAction(), and CGUIDialogSubtitles::SetSubtitles().
CanPause()
bool CApplicationPlayer::CanPause () const
References GetInternal().
CanSeek()
bool CApplicationPlayer::CanSeek () const
References GetInternal().
CloseFile()
void CApplicationPlayer::CloseFile (bool reopen = false) private
References GetInternal().
Referenced by ClosePlayer(), and OpenFile().
ClosePlayer()
void CApplicationPlayer::ClosePlayer ()
References CloseFile(), GetInternal(), m_nextItem, CApplicationPlayer::SNextItem::pItem, and ResetPlayer().
Referenced by CGUIWindowSlideShow::OnAction(), and CGUIWindowSlideShow::Process().
CreatePlayer()
void CApplicationPlayer::CreatePlayer (const CPlayerCoreFactory & factory, const std::string & player, IPlayerCallback & callback) private
References CPlayerCoreFactory::CreatePlayer(), CDataCacheCore::GetInstance(), m_playerLock, m_pPlayer, and CDataCacheCore::Reset().
Referenced by OpenFile().
FlushRenderer()
void CApplicationPlayer::FlushRenderer ()
References GetInternal().
FrameAdvance()
void CApplicationPlayer::FrameAdvance (int frames)
References GetInternal().
FrameMove()
void CApplicationPlayer::FrameMove ()
References CServiceBroker::GetGUI(), CDataCacheCore::GetInstance(), GetInternal(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_STATE_CHANGED, and CGUIWindowManager::SendMessage().
GetAudioCapabilities()
void CApplicationPlayer::GetAudioCapabilities (std::vector< IPlayerAudioCaps > & caps) const
References GetInternal().
Referenced by KODI::VIDEO::GUILIB::OpenDialogSelectAudioStream().
GetAudioDelay()
int CApplicationPlayer::GetAudioDelay () const
References CServiceBroker::GetSettingsComponent(), GetVideoSettings(), and CVideoSettings::m_AudioDelay.
GetAudioStream()
int CApplicationPlayer::GetAudioStream ()
References GetInternal(), m_audioStreamUpdate, and m_iAudioStream.
Referenced by CGUIDialogAudioSettings::AddAudioStreams().
GetAudioStreamCount()
int CApplicationPlayer::GetAudioStreamCount () const
References GetInternal().
Referenced by CGUIDialogAudioSettings::AudioStreamsOptionFiller().
GetAudioStreamInfo()
void CApplicationPlayer::GetAudioStreamInfo (int index, AudioStreamInfo & info) const
References GetInternal(), and index().
Referenced by CGUIDialogSubtitles::Search().
GetCacheLevel()
int CApplicationPlayer::GetCacheLevel () const
References GetInternal().
GetCachePercentage()
float CApplicationPlayer::GetCachePercentage () const
References GetInternal().
GetChapter()
int CApplicationPlayer::GetChapter () const
References GetInternal().
GetChapterCount()
int CApplicationPlayer::GetChapterCount () const
References GetInternal().
GetChapterName()
void CApplicationPlayer::GetChapterName (std::string & strChapterName, int chapterIdx = -1) const
References GetInternal().
Referenced by CGUIDialogVideoBookmarks::OnRefreshList().
GetChapterPos()
int64_t CApplicationPlayer::GetChapterPos (int chapterIdx = -1) const
References GetInternal().
GetCurrentPlayer()
std::string CApplicationPlayer::GetCurrentPlayer () const
References GetInternal().
Referenced by CPowerManager::StorePlayerState().
GetDeinterlacingMethodDefault()
EINTERLACEMETHOD CApplicationPlayer::GetDeinterlacingMethodDefault () const
References GetInternal(), and VS_INTERLACEMETHOD_NONE.
GetInternal() [1/2]
std::shared_ptr< IPlayer > CApplicationPlayer::GetInternal () private
References m_playerLock, and m_pPlayer.
GetInternal() [2/2]
std::shared_ptr< const IPlayer > CApplicationPlayer::GetInternal () const private
References m_playerLock, and m_pPlayer.
Referenced by AddSubtitle(), CanPause(), CanSeek(), CloseFile(), ClosePlayer(), FlushRenderer(), FrameAdvance(), FrameMove(), GetAudioCapabilities(), GetAudioStream(), GetAudioStreamCount(), GetAudioStreamInfo(), GetCacheLevel(), GetCachePercentage(), GetChapter(), GetChapterCount(), GetChapterName(), GetChapterPos(), GetCurrentPlayer(), GetDeinterlacingMethodDefault(), GetMaxTime(), GetMinTime(), GetName(), GetOrientation(), GetPercentage(), GetPlayerState(), GetPlaySpeed(), GetPlayTempo(), GetPrograms(), GetProgramsCount(), GetRects(), GetRenderAspectRatio(), GetStartTime(), GetSubtitle(), GetSubtitleCapabilities(), GetSubtitleCount(), GetSubtitleStreamInfo(), GetSubtitleVisible(), GetSupportedMenuType(), GetTeletextCache(), GetTime(), GetTotalTime(), GetVideoSettings(), GetVideoStream(), GetVideoStreamCount(), GetVideoStreamInfo(), HasAudio(), HasGame(), HasGameAgent(), HasPlayer(), HasRDS(), HasTeletextCache(), HasVideo(), IsCaching(), IsExternalPlaying(), IsInMenu(), IsPassthrough(), IsPlaying(), IsRemotePlaying(), IsRenderingGuiLayer(), IsRenderingVideo(), IsRenderingVideoLayer(), LoadPage(), OnAction(), OnNothingToQueueNotify(), OpenFile(), Pause(), QueueNextFile(), Render(), RenderCapture(), RenderCaptureAlloc(), RenderCaptureGetPixels(), RenderCaptureRelease(), Seek(), SeekChapter(), SeekPercentage(), SeekScene(), SeekTime(), SeekTimeRelative(), SetAudioStream(), SetAVDelay(), SetDynamicRangeCompression(), SetMute(), SetPlayerState(), SetPlaySpeed(), SetProgram(), SetRenderViewMode(), SetSpeed(), SetSubtitle(), SetSubTitleDelay(), SetSubtitleVerticalPosition(), SetSubtitleVisible(), SetTempo(), SetTime(), SetTotalTime(), SetUpdateStreamDetails(), SetVideoSettings(), SetVideoStream(), SetVolume(), Supports(), Supports(), Supports(), SupportsTempo(), and TriggerUpdateResolution().
GetMaxTime()
int64_t CApplicationPlayer::GetMaxTime () const
References CDataCacheCore::GetInstance(), GetInternal(), and CDataCacheCore::GetMaxTime().
GetMinTime()
int64_t CApplicationPlayer::GetMinTime () const
References CDataCacheCore::GetInstance(), GetInternal(), and CDataCacheCore::GetMinTime().
GetName()
std::string CApplicationPlayer::GetName () const
Get the name of the player in use.
Returns
the player name if a player is active, otherwise it returns an empty string
References GetInternal().
Referenced by KODI::PLAYLIST::CPlayListPlayer::PlayNext().
GetOrientation()
unsigned int CApplicationPlayer::GetOrientation () const
References GetInternal().
GetPercentage()
float CApplicationPlayer::GetPercentage () const
References CDataCacheCore::GetInstance(), GetInternal(), and CDataCacheCore::GetPlayPercentage().
GetPlayerState()
std::string CApplicationPlayer::GetPlayerState ()
References GetInternal().
GetPlaySpeed()
float CApplicationPlayer::GetPlaySpeed () const
References CDataCacheCore::GetInstance(), GetInternal(), and CDataCacheCore::GetSpeed().
Referenced by IsPaused(), and IsPausedPlayback().
GetPlayTempo()
float CApplicationPlayer::GetPlayTempo () const
References CDataCacheCore::GetInstance(), GetInternal(), and CDataCacheCore::GetTempo().
GetPreferredPlaylist()
PLAYLIST::Id CApplicationPlayer::GetPreferredPlaylist () const
References IsPlayingAudio(), and IsPlayingVideo().
Referenced by JSONRPC::CPlayerOperations::GetPlaylist().
GetPrograms()
int CApplicationPlayer::GetPrograms (std::vector< ProgramInfo > & programs)
References GetInternal().
GetProgramsCount()
int CApplicationPlayer::GetProgramsCount () const
References GetInternal().
GetRects()
bool CApplicationPlayer::GetRects (CRect & source, CRect & dest, CRect & view) const
References GetInternal().
GetRenderAspectRatio()
float CApplicationPlayer::GetRenderAspectRatio () const
References GetInternal().
GetSeekHandler() [1/2]
CSeekHandler & CApplicationPlayer::GetSeekHandler ()
References m_seekHandler.
Referenced by CGUIDialogSeekBar::GetEpgEventProgress(), PVR::CPVRGUIInfo::GetTimeShiftSeekPercent(), and Seek().
GetSeekHandler() [2/2]
const CSeekHandler & CApplicationPlayer::GetSeekHandler () const
References m_seekHandler.
GetStartTime()
time_t CApplicationPlayer::GetStartTime () const
References CDataCacheCore::GetInstance(), GetInternal(), and CDataCacheCore::GetStartTime().
GetSubtitle()
int CApplicationPlayer::GetSubtitle ()
References GetInternal(), m_iSubtitleStream, and m_subtitleStreamUpdate.
Referenced by CGUIDialogSubtitleSettings::AddSubtitleStreams().
GetSubtitleCapabilities()
void CApplicationPlayer::GetSubtitleCapabilities (std::vector< IPlayerSubtitleCaps > & caps) const
References GetInternal().
Referenced by KODI::VIDEO::GUILIB::OpenDialogSelectSubtitleStream().
GetSubtitleCount()
int CApplicationPlayer::GetSubtitleCount () const
References GetInternal().
Referenced by CGUIDialogSubtitleSettings::SubtitleStreamsOptionFiller().
GetSubtitleDelay()
int CApplicationPlayer::GetSubtitleDelay () const
References CServiceBroker::GetSettingsComponent(), GetVideoSettings(), and CVideoSettings::m_SubtitleDelay.
GetSubtitleStreamInfo()
void CApplicationPlayer::GetSubtitleStreamInfo (int index, SubtitleStreamInfo & info) const
References GetInternal(), and index().
GetSubtitleVisible()
bool CApplicationPlayer::GetSubtitleVisible () const
References GetInternal().
GetSupportedMenuType()
MenuType CApplicationPlayer::GetSupportedMenuType () const
Get the supported menu type.
Returns
The supported menu type
References GetInternal(), and NONE.
GetTeletextCache()
std::shared_ptr< TextCacheStruct_t > CApplicationPlayer::GetTeletextCache ()
References GetInternal().
Referenced by CTeletextDecoder::InitDecoder().
GetTime()
int64_t CApplicationPlayer::GetTime () const
References CDataCacheCore::GetInstance(), GetInternal(), and CDataCacheCore::GetPlayTime().
Referenced by SeekTimeRelative(), and CSeekHandler::SetSeekSize().
GetTotalTime()
int64_t CApplicationPlayer::GetTotalTime () const
References CDataCacheCore::GetInstance(), GetInternal(), CDataCacheCore::GetMaxTime(), CDataCacheCore::GetMinTime(), and int64_t().
GetVideoSettings()
CVideoSettings CApplicationPlayer::GetVideoSettings () const
References GetInternal().
Referenced by GetAudioDelay(), GetSubtitleDelay(), and JSONRPC::CPlayerOperations::GetViewMode().
GetVideoStream()
int CApplicationPlayer::GetVideoStream ()
References GetInternal(), m_iVideoStream, and m_videoStreamUpdate.
Referenced by CGUIDialogVideoSettings::AddVideoStreams(), and JSONRPC::CPlayerOperations::GetPropertyValue().
GetVideoStreamCount()
int CApplicationPlayer::GetVideoStreamCount () const
References GetInternal().
Referenced by JSONRPC::CPlayerOperations::GetPropertyValue(), KODI::VIDEO::GUILIB::OpenDialogSelectVideoStream(), JSONRPC::CPlayerOperations::SetVideoStream(), and CGUIDialogVideoSettings::VideoStreamsOptionFiller().
GetVideoStreamInfo()
void CApplicationPlayer::GetVideoStreamInfo (int streamId, VideoStreamInfo & info) const
References GetInternal().
Referenced by CGUIInfoManager::UpdateAVInfo().
HasAudio()
bool CApplicationPlayer::HasAudio () const
References GetInternal().
Referenced by IsPlayingAudio().
HasGame()
bool CApplicationPlayer::HasGame () const
References GetInternal().
Referenced by IsPlayingGame().
HasGameAgent()
bool CApplicationPlayer::HasGameAgent () const
Check if any players are playing a game.
Returns
True if at least one player has an input device attached to the game, false otherwise
References GetInternal().
HasPlayer()
bool CApplicationPlayer::HasPlayer () const
References GetInternal().
HasRDS()
bool CApplicationPlayer::HasRDS () const
References GetInternal().
Referenced by IsPlayingRDS().
HasTeletextCache()
bool CApplicationPlayer::HasTeletextCache () const
References GetInternal().
HasVideo()
bool CApplicationPlayer::HasVideo () const
References GetInternal().
Referenced by IsPlayingAudio(), and IsPlayingVideo().
IsCaching()
bool CApplicationPlayer::IsCaching () const
References GetInternal().
IsExternalPlaying()
bool CApplicationPlayer::IsExternalPlaying () const
References GetInternal().
IsInMenu()
bool CApplicationPlayer::IsInMenu () const
References GetInternal().
IsPassthrough()
bool CApplicationPlayer::IsPassthrough () const
References GetInternal().
Referenced by CGUIDialogAudioSettings::IsPlayingPassthrough().
IsPaused()
bool CApplicationPlayer::IsPaused () const
References GetPlaySpeed().
IsPausedPlayback()
bool CApplicationPlayer::IsPausedPlayback () const
References GetPlaySpeed(), and IsPlaying().
Referenced by CApplicationSkinHandling::LoadSkin().
IsPlaying()
bool CApplicationPlayer::IsPlaying () const
References GetInternal().
Referenced by IsPausedPlayback(), IsPlayingAudio(), IsPlayingGame(), IsPlayingRDS(), IsPlayingVideo(), and KODI::VIDEO::UTILS::QueueItem().
IsPlayingAudio()
bool CApplicationPlayer::IsPlayingAudio () const
References HasAudio(), HasVideo(), and IsPlaying().
Referenced by GetPreferredPlaylist(), and SetPlaySpeed().
IsPlayingGame()
bool CApplicationPlayer::IsPlayingGame () const
References HasGame(), and IsPlaying().
IsPlayingRDS()
bool CApplicationPlayer::IsPlayingRDS () const
References HasRDS(), and IsPlaying().
Referenced by PVR::CPVRGUIInfo::GetRadioRDSBool().
IsPlayingVideo()
bool CApplicationPlayer::IsPlayingVideo () const
References HasVideo(), and IsPlaying().
Referenced by GetPreferredPlaylist(), CGUIWindowSettingsScreenCalibration::OnMessage(), and SetPlaySpeed().
IsRemotePlaying()
bool CApplicationPlayer::IsRemotePlaying () const
References GetInternal().
IsRenderingGuiLayer()
bool CApplicationPlayer::IsRenderingGuiLayer () const
References CServiceBroker::GetDataCacheCore(), CDataCacheCore::GetGuiRender(), and GetInternal().
IsRenderingVideo()
bool CApplicationPlayer::IsRenderingVideo () const
References GetInternal().
IsRenderingVideoLayer()
bool CApplicationPlayer::IsRenderingVideoLayer () const
References CServiceBroker::GetDataCacheCore(), GetInternal(), and CDataCacheCore::GetVideoRender().
LoadPage()
void CApplicationPlayer::LoadPage (int p, int sp, unsigned char * buffer)
References GetInternal().
Referenced by CTeletextDecoder::Decode_ADIP(), CTeletextDecoder::Decode_BTT(), CTeletextDecoder::DecodePage(), CTeletextDecoder::Eval_l25(), CTeletextDecoder::Eval_NumberedObject(), and CTeletextDecoder::RenderChar().
OnAction()
bool CApplicationPlayer::OnAction (const CAction & action)
References GetInternal().
OnNothingToQueueNotify()
void CApplicationPlayer::OnNothingToQueueNotify ()
References GetInternal().
OpenFile()
bool CApplicationPlayer::OpenFile (const CFileItem & item, const CPlayerOptions & options, const CPlayerCoreFactory & factory, const std::string & playerName, IPlayerCallback & callback)
References CApplicationPlayer::SNextItem::callback, CloseFile(), CreatePlayer(), CPlayerCoreFactory::GetDefaultPlayer(), GetInternal(), CFileItem::IsDiscImage(), m_audioStreamUpdate, m_nextItem, m_playerLock, m_pPlayer, m_subtitleStreamUpdate, m_videoStreamUpdate, CApplicationPlayer::SNextItem::options, CApplicationPlayer::SNextItem::pItem, and CApplicationPlayer::SNextItem::playerName.
Referenced by OpenNext().
OpenNext()
void CApplicationPlayer::OpenNext (const CPlayerCoreFactory & factory)
References CApplicationPlayer::SNextItem::callback, m_nextItem, OpenFile(), CApplicationPlayer::SNextItem::options, CApplicationPlayer::SNextItem::pItem, and CApplicationPlayer::SNextItem::playerName.
Pause()
void CApplicationPlayer::Pause ()
References GetInternal().
Referenced by CGUIDialogSubtitles::OnInitWindow(), and CGUIDialogSubtitles::OnMessage().
QueueNextFile()
bool CApplicationPlayer::QueueNextFile (const CFileItem & file)
References GetInternal().
Render()
void CApplicationPlayer::Render (bool clear, uint32_t alpha = 255, bool gui = true)
References GetInternal().
Referenced by CGUIWindowFullScreen::Render(), CGUIVideoControl::RenderEx(), CGUIWindowSlideShow::RenderEx(), and CGUIWindowFullScreen::RenderEx().
RenderCapture()
void CApplicationPlayer::RenderCapture (unsigned int captureId, unsigned int width, unsigned int height, int flags = 0)
References GetInternal().
RenderCaptureAlloc()
unsigned int CApplicationPlayer::RenderCaptureAlloc ()
References GetInternal().
RenderCaptureGetPixels()
bool CApplicationPlayer::RenderCaptureGetPixels (unsigned int captureId, unsigned int millis, uint8_t * buffer, unsigned int size)
References GetInternal().
Referenced by XBMCAddon::xbmc::RenderCapture::GetPixels().
RenderCaptureRelease()
void CApplicationPlayer::RenderCaptureRelease (unsigned int captureId)
References GetInternal().
Referenced by XBMCAddon::xbmc::RenderCapture::capture(), and XBMCAddon::xbmc::RenderCapture::~RenderCapture().
ResetPlayer()
void CApplicationPlayer::ResetPlayer ()
References m_playerLock, and m_pPlayer.
Referenced by ClosePlayer().
Seek()
void CApplicationPlayer::Seek (bool bPlus = true, bool bLargeStep = false, bool bChapterOverride = false)
References GetInternal().
SeekChapter()
int CApplicationPlayer::SeekChapter (int iChapter)
References GetInternal().
Referenced by CGUIWindowFullScreen::SeekChapter().
SeekPercentage()
void CApplicationPlayer::SeekPercentage (float fPercent = 0)
References GetInternal().
SeekScene()
bool CApplicationPlayer::SeekScene (Direction seekDirection)
References GetInternal().
SeekTime()
void CApplicationPlayer::SeekTime (int64_t iTime = 0)
References GetInternal().
Referenced by jni::CJNIXBMCMediaSession::OnSeekRequested().
SeekTimeRelative()
void CApplicationPlayer::SeekTimeRelative (int64_t iTime = 0)
References GetInternal(), GetTime(), and int64_t().
Referenced by CSeekHandler::FrameMove(), and CSeekHandler::SeekSeconds().
SetAudioStream()
void CApplicationPlayer::SetAudioStream (int iStream)
References GetInternal(), m_audioStreamUpdate, and m_iAudioStream.
SetAVDelay()
void CApplicationPlayer::SetAVDelay (float fValue = 0.0f)
References GetInternal().
Referenced by CPlayerController::OnSliderChange().
SetDynamicRangeCompression()
void CApplicationPlayer::SetDynamicRangeCompression (long drc)
References GetInternal().
SetMute()
void CApplicationPlayer::SetMute (bool bOnOff)
References GetInternal().
SetPlayerState()
bool CApplicationPlayer::SetPlayerState (const std::string & state)
References GetInternal().
SetPlaySpeed()
void CApplicationPlayer::SetPlaySpeed (float speed)
References GetInternal(), IsPlayingAudio(), IsPlayingVideo(), and SetSpeed().
Referenced by PlayerControl().
SetProgram()
void CApplicationPlayer::SetProgram (int progId)
References GetInternal().
SetRenderViewMode()
void CApplicationPlayer::SetRenderViewMode (int mode, float zoom, float par, float shift, bool stretch)
References GetInternal().
SetSpeed()
void CApplicationPlayer::SetSpeed (float speed)
References GetInternal().
Referenced by SetPlaySpeed().
SetSubtitle()
void CApplicationPlayer::SetSubtitle (int iStream)
References GetInternal(), m_iSubtitleStream, and m_subtitleStreamUpdate.
SetSubTitleDelay()
void CApplicationPlayer::SetSubTitleDelay (float fValue = 0.0f)
References GetInternal().
SetSubtitleVerticalPosition()
void CApplicationPlayer::SetSubtitleVerticalPosition (const int value, bool save)
Set the subtitle vertical position, it depends on current screen resolution.
Parameters
value The subtitle position in pixels
save If true, the value will be saved to resolution info
References GetInternal(), and value.
Referenced by OVERLAY::CRenderer::ResetSubtitlePosition().
SetSubtitleVisible()
void CApplicationPlayer::SetSubtitleVisible (bool bVisible)
References GetInternal().
SetTempo()
void CApplicationPlayer::SetTempo (float tempo)
References GetInternal().
Referenced by JSONRPC::CPlayerOperations::SetTempo().
SetTime()
void CApplicationPlayer::SetTime (int64_t time)
References GetInternal().
Referenced by CAirTunesServer::InformPlayerAboutPlayTimes().
SetTotalTime()
void CApplicationPlayer::SetTotalTime (int64_t time)
References GetInternal().
SetUpdateStreamDetails()
void CApplicationPlayer::SetUpdateStreamDetails ()
References GetInternal(), and CVideoPlayer::SetUpdateStreamDetails().
Referenced by CApplicationPlayerCallback::OnPlayBackStarted().
SetVideoSettings()
void CApplicationPlayer::SetVideoSettings (CVideoSettings & settings)
References GetInternal().
Referenced by CApplicationPlayerCallback::RequestVideoSettings().
SetVideoStream()
void CApplicationPlayer::SetVideoStream (int iStream)
References GetInternal(), m_iVideoStream, and m_videoStreamUpdate.
SetVolume()
void CApplicationPlayer::SetVolume (float volume)
References GetInternal().
Referenced by CApplicationVolumeHandling::VolumeChanged().
Supports() [1/3]
bool CApplicationPlayer::Supports (EINTERLACEMETHOD method) const
References GetInternal().
Supports() [2/3]
bool CApplicationPlayer::Supports (ERENDERFEATURE feature) const
References GetInternal().
Supports() [3/3]
bool CApplicationPlayer::Supports (ESCALINGMETHOD method) const
References GetInternal().
SupportsTempo()
bool CApplicationPlayer::SupportsTempo () const
References GetInternal().
TriggerUpdateResolution()
void CApplicationPlayer::TriggerUpdateResolution ()
References GetInternal().
Referenced by CGraphicContext::SetFullScreenVideo().
Member Data Documentation
m_audioStreamUpdate
XbmcThreads::EndTime CApplicationPlayer::m_audioStreamUpdate private
Referenced by GetAudioStream(), OpenFile(), and SetAudioStream().
m_iAudioStream
int CApplicationPlayer::m_iAudioStream private
Referenced by GetAudioStream(), and SetAudioStream().
m_iSubtitleStream
int CApplicationPlayer::m_iSubtitleStream private
Referenced by GetSubtitle(), and SetSubtitle().
m_iVideoStream
int CApplicationPlayer::m_iVideoStream private
Referenced by GetVideoStream(), and SetVideoStream().
m_nextItem
struct CApplicationPlayer::SNextItem CApplicationPlayer::m_nextItem private
Referenced by ClosePlayer(), OpenFile(), and OpenNext().
m_playerLock
CCriticalSection CApplicationPlayer::m_playerLock mutable private
Referenced by CreatePlayer(), GetInternal(), GetInternal(), OpenFile(), and ResetPlayer().
m_pPlayer
std::shared_ptr<IPlayer> CApplicationPlayer::m_pPlayer private
Referenced by CreatePlayer(), GetInternal(), GetInternal(), OpenFile(), and ResetPlayer().
m_seekHandler
CSeekHandler CApplicationPlayer::m_seekHandler private
Referenced by GetSeekHandler(), and GetSeekHandler().
m_subtitleStreamUpdate
XbmcThreads::EndTime CApplicationPlayer::m_subtitleStreamUpdate private
Referenced by GetSubtitle(), OpenFile(), and SetSubtitle().
m_videoStreamUpdate
XbmcThreads::EndTime CApplicationPlayer::m_videoStreamUpdate private
Referenced by GetVideoStream(), OpenFile(), and SetVideoStream().
The documentation for this class was generated from the following files:
ApplicationPlayer.h
ApplicationPlayer.cpp