Kodi Documentation: CGraphicContext Class Reference
CGraphicContext Class Reference
#include <GraphicContext.h>
Classes
class UITransform
Public Member Functions
CGraphicContext (void)
virtual ~CGraphicContext ()
float GetFPS () const
void SetFPS (float fps)
float GetDisplayLatency () const
bool IsFullScreenRoot () const
void ToggleFullScreen ()
void SetFullScreenVideo (bool bOnOff)
bool IsFullScreenVideo () const
bool IsValidResolution (RESOLUTION res)
void SetVideoResolution (RESOLUTION res, bool forceUpdate)
void ApplyModeChange (RESOLUTION res)
void ApplyWindowResize (int newWidth, int newHeight)
RESOLUTION GetVideoResolution () const
const RESOLUTION_INFO GetResInfo () const
const RESOLUTION_INFO GetResInfo (RESOLUTION res) const
void SetResInfo (RESOLUTION res, const RESOLUTION_INFO &info)
void Flip (bool rendered, bool videoLayer)
int GetWidth () const
int GetHeight () const
bool SetViewPort (float fx, float fy, float fwidth, float fheight, bool intersectPrevious=false)
void RestoreViewPort ()
void SetScissors (const CRect &rect)
void ResetScissors ()
const CRect & GetScissors () const
const CRect GetViewWindow () const
void SetViewWindow (float left, float top, float right, float bottom)
bool IsCalibrating () const
void SetCalibrating (bool bOnOff)
void ResetOverscan (RESOLUTION res, OVERSCAN &overscan)
void ResetOverscan (RESOLUTION_INFO &resinfo)
void ResetScreenParameters (RESOLUTION res)
void CaptureStateBlock ()
void ApplyStateBlock ()
void Clear ()
Invalidates color buffer, clears the depth buffer (if used). Will result in undefined color buffer values which will have to be repainted. Has to be called at the beginning of a frame.
void Clear (KODI::UTILS::COLOR::Color color)
Clears the depth buffer (if used) and the color buffer. Guaranties a defined color buffer value. Has to be called at the beginning of a frame.
void GetAllowedResolutions (std::vector< RESOLUTION > &res)
void SetRenderOrder (RENDER_ORDER renderOrder)
Sets the direction of the current rendering pass.
RENDER_ORDER GetRenderOrder ()
Returns the current render order mode.
void ResetDepth ()
Resets the z-depth. Layer 0 and 1 are reserved as presentation (video) layer.
uint32_t GetDepth (uint32_t addLayers=2)
Reserve layers for the caller to use.
void GetGUIScaling (const RESOLUTION_INFO &res, float &scaleX, float &scaleY, TransformMatrix *matrix=NULL)
void SetRenderingResolution (const RESOLUTION_INFO &res, bool needsScaling)
Sets scaling up for rendering.
void SetScalingResolution (const RESOLUTION_INFO &res, bool needsScaling)
Sets scaling up for skin loading etc.
float GetScalingPixelRatio () const
void InvertFinalCoords (float &x, float &y) const
float ScaleFinalXCoord (float x, float y) const
float ScaleFinalYCoord (float x, float y) const
float ScaleFinalZCoord (float x, float y) const
void ScaleFinalCoords (float &x, float &y, float &z) const
bool RectIsAngled (float x1, float y1, float x2, float y2) const
const TransformMatrix & GetGUIMatrix () const
float GetGUIScaleX () const
float GetGUIScaleY () const
KODI::UTILS::COLOR::Color MergeAlpha (KODI::UTILS::COLOR::Color color) const
KODI::UTILS::COLOR::Color MergeColor (KODI::UTILS::COLOR::Color color) const
void SetOrigin (float x, float y)
void RestoreOrigin ()
void SetCameraPosition (const CPoint &camera)
void SetStereoView (RENDER_STEREO_VIEW view)
RENDER_STEREO_VIEW GetStereoView ()
void SetStereoMode (RENDER_STEREO_MODE mode)
RENDER_STEREO_MODE GetStereoMode ()
void RestoreCameraPosition ()
void SetStereoFactor (float factor)
void RestoreStereoFactor ()
float GetTransformDepth (int32_t depthOffset=0)
Gets the depth information of the current transform matrix.
float GetNormalizedDepth (uint32_t depth)
Gets the (normalized) depth information.
bool SetClipRegion (float x, float y, float w, float h)
Set a region in which to clip all rendering Anything that is rendered after setting a clip region will be clipped so that no part renders outside of the clip region. Successive calls to SetClipRegion intersect the clip region, which means the clip region may eventually become an empty set. In this case SetClipRegion returns false to indicate that no rendering need be performed.
void RestoreClipRegion ()
void ClipRect (CRect &vertex, CRect &texture, CRect *diffuse=NULL)
CRect GetClipRegion ()
void AddGUITransform ()
TransformMatrix AddTransform (const TransformMatrix &matrix)
void SetTransform (const TransformMatrix &matrix)
void SetTransform (const TransformMatrix &matrix, float scaleX, float scaleY)
void RemoveTransform ()
CRect StereoCorrection (const CRect &rect) const
CPoint StereoCorrection (const CPoint &point) const
CRect GenerateAABB (const CRect &rect) const
const std::string & GetMediaDir () const
void SetMediaDir (const std::string &strMediaDir)
void SetTransferPQ (bool PQ)
bool IsTransferPQ () const
Protected Member Functions
void UpdateCameraPosition (const CPoint &camera, const float &factor)
void SetVideoResolutionInternal (RESOLUTION res, bool forceUpdate)
void ApplyVideoResolution (RESOLUTION res)
void UpdateInternalStateWithResolution (RESOLUTION res)
Protected Attributes
int m_iScreenHeight = 576
int m_iScreenWidth = 720
std::string m_strMediaDir
CRect m_videoRect
bool m_bFullScreenRoot = true
bool m_bFullScreenVideo = false
bool m_bCalibrating = false
RESOLUTION m_Resolution = RES_INVALID
float m_fFPSOverride = 0.0f
RESOLUTION_INFO m_windowResolution
std::stack< CPoint > m_cameras
std::stack< CPoint > m_origins
std::stack< CRect > m_clipRegions
std::stack< float > m_stereoFactors
std::stack< CRect > m_viewStack
CRect m_scissors
UITransform m_guiTransform
UITransform m_finalTransform
std::stack< UITransform > m_transforms
RENDER_STEREO_VIEW m_stereoView = RENDER_STEREO_VIEW_OFF
RENDER_STEREO_MODE m_stereoMode = RENDER_STEREO_MODE_OFF
RENDER_STEREO_MODE m_nextStereoMode = RENDER_STEREO_MODE_OFF
bool m_isTransferPQ {false}
RENDER_ORDER m_renderOrder {RENDER_ORDER_ALL_BACK_TO_FRONT}
uint32_t m_layer {2}
Constructor & Destructor Documentation
CGraphicContext()
CGraphicContext::CGraphicContext (void) default
~CGraphicContext()
CGraphicContext::~CGraphicContext () virtual default
Member Function Documentation
AddGUITransform()
void CGraphicContext::AddGUITransform ()
References m_finalTransform, m_guiTransform, and m_transforms.
Referenced by CGUIWindow::DoProcess(), CGUIWindowSettingsScreenCalibration::DoProcess(), and CGUIWindow::DoRender().
AddTransform()
TransformMatrix CGraphicContext::AddTransform (const TransformMatrix & matrix)
References m_finalTransform, m_transforms, and CGraphicContext::UITransform::matrix.
Referenced by CGUIControl::DoProcess(), CGUIFadeLabelControl::Process(), CGUITextBox::Process(), CGUITextLayout::Render(), CGUITextLayout::RenderScrolling(), and SetOrigin().
ApplyModeChange()
void CGraphicContext::ApplyModeChange (RESOLUTION res)
References ApplyVideoResolution(), CWinSystemBase::FinishModeChange(), and CServiceBroker::GetWinSystem().
Referenced by CAppInboundProtocol::HandleEvents().
ApplyStateBlock()
void CGraphicContext::ApplyStateBlock ()
References CRenderSystemBase::ApplyStateBlock(), and CServiceBroker::GetRenderSystem().
Referenced by CGUIRenderingControl::FreeResources(), CGUIRenderingControl::InitCallback(), CGUIWindowScreensaver::OnMessage(), and CGUIRenderingControl::Render().
ApplyVideoResolution()
void CGraphicContext::ApplyVideoResolution (RESOLUTION res) protected
References CServiceBroker::GetGUI(), CServiceBroker::GetInputManager(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_WINDOW_RESIZE, RESOLUTION_INFO::iHeight, IsValidResolution(), RESOLUTION_INFO::iWidth, LOGWARNING, m_bFullScreenRoot, m_iScreenHeight, m_iScreenWidth, m_scissors, RENDER_STEREO_VIEW_OFF, RES_DESKTOP, CGUIWindowManager::SendMessage(), CInputManager::SetMouseResolution(), CRectGen< T >::SetRect(), SetStereoView(), and UpdateInternalStateWithResolution().
Referenced by ApplyModeChange(), and ApplyWindowResize().
ApplyWindowResize()
void CGraphicContext::ApplyWindowResize (int newWidth, int newHeight)
References ApplyVideoResolution(), CWinSystemBase::FinishWindowResize(), CServiceBroker::GetWinSystem(), RES_WINDOW, and CWinSystemBase::SetWindowResolution().
Referenced by CAppInboundProtocol::HandleEvents().
CaptureStateBlock()
void CGraphicContext::CaptureStateBlock ()
References CRenderSystemBase::CaptureStateBlock(), and CServiceBroker::GetRenderSystem().
Referenced by CGUIVisualisationControl::DeInitVisualization(), CGUIRenderingControl::FreeResources(), CGUIRenderingControl::InitCallback(), CGUIVisualisationControl::InitVisualization(), CGUIWindowScreensaver::OnMessage(), CGUIVisualisationControl::Process(), CGUIRenderingControl::Render(), and CGUIWindowScreensaver::Render().
Clear() [1/2]
void CGraphicContext::Clear ()
Invalidates color buffer, clears the depth buffer (if used). Will result in undefined color buffer values which will have to be repainted. Has to be called at the beginning of a frame.
References CServiceBroker::GetRenderSystem(), and CRenderSystemBase::InvalidateColorBuffer().
Referenced by KODI::RETRO::CRenderContext::Clear(), CLinuxRendererGL::ClearBackBuffer(), CLinuxRendererGLES::ClearBackBuffer(), CGUIWindow::ClearBackground(), CGUIWindowFullScreen::ClearBackground(), CGUIVideoControl::Render(), CGUIWindowSlideShow::Render(), CWinRenderer::RenderUpdate(), KODI::WINDOWING::X11::CWinSystemX11GLContext::SetWindow(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::SetWindow(), and CRenderSystemBase::ShowSplash().
Clear() [2/2]
void CGraphicContext::Clear (KODI::UTILS::COLOR::Color color)
Clears the depth buffer (if used) and the color buffer. Guaranties a defined color buffer value. Has to be called at the beginning of a frame.
Parameters
color the specified color.
ClipRect()
void CGraphicContext::ClipRect (CRect & vertex, CRect & texture, CRect * diffuse = NULL)
References CRectGen< T >::Height(), CRectGen< T >::Intersect(), m_clipRegions, m_origins, CRectGen< T >::Width(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CGUITexture::Render(), and CGUIFontTTF::RenderCharacter().
Flip()
void CGraphicContext::Flip (bool rendered, bool videoLayer)
References CServiceBroker::GetGUI(), CServiceBroker::GetRenderSystem(), GetVideoResolution(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_RENDERER_RESET, m_nextStereoMode, m_stereoMode, CRenderSystemBase::PresentRender(), CGUIWindowManager::SendMessage(), and SetVideoResolution().
Referenced by CApplication::Render(), KODI::WINDOWING::X11::CWinSystemX11GLContext::SetWindow(), KODI::WINDOWING::X11::CWinSystemX11GLESContext::SetWindow(), and CRenderSystemBase::ShowSplash().
GenerateAABB()
CRect CGraphicContext::GenerateAABB (const CRect & rect) const
References CServiceBroker::GetRenderSystem(), CRenderSystemBase::Project(), ScaleFinalCoords(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CGUIControl::Process().
GetAllowedResolutions()
void CGraphicContext::GetAllowedResolutions (std::vector< RESOLUTION > & res)
References CDisplaySettings::GetInstance(), RES_CUSTOM, RES_DESKTOP, RES_WINDOW, and CDisplaySettings::ResolutionInfoSize().
Referenced by CResolutionUtils::FindResolutionFromWhitelist(), CResolutionUtils::GetMaxAllowedScreenResolution(), and CGUIWindowSettingsScreenCalibration::OnMessage().
GetClipRegion()
CRect CGraphicContext::GetClipRegion ()
References m_clipRegions, m_iScreenHeight, m_iScreenWidth, and m_origins.
Referenced by CGUIFontTTF::DrawTextInternal().
GetDepth()
uint32_t CGraphicContext::GetDepth (uint32_t addLayers = 2)
Reserve layers for the caller to use.
Parameters
addLayers number of layers needed
Returns
uint32_t returns the absolute layer hight
References m_layer.
Referenced by CGUIControl::AssignDepth(), and PVR::CGUIEPGGridContainer::AssignDepth().
GetDisplayLatency()
float CGraphicContext::GetDisplayLatency () const
References CWinSystemBase::GetDisplayLatency(), GetFPS(), CServiceBroker::GetWinSystem(), and CWinSystemBase::NoOfBuffers().
GetFPS()
float CGraphicContext::GetFPS () const
References GetResInfo(), m_Resolution, and RES_INVALID.
Referenced by CRenderManager::CheckEnableClockSync(), GetDisplayLatency(), CVideoSyncAndroid::GetFps(), CVideoSyncGbm::GetFps(), CVideoSyncIos::GetFps(), CVideoSyncOsx::GetFps(), CVideoSyncTVos::GetFps(), KODI::WINDOWING::X11::CVideoSyncGLX::GetFps(), KODI::WINDOWING::X11::CVideoSyncOML::GetFps(), CRenderManager::PrepareNextRender(), CGUIImage::ProcessFadingTransition(), CVideoSyncGbm::RefreshChanged(), CSlideShowPic::Rotate(), CSeekHandler::Seek(), CSlideShowPic::SetTexture_Internal(), CTimeUtils::UpdateFrameTime(), CRenderManager::UpdateLatencyTweak(), and CSlideShowPic::Zoom().
GetGUIMatrix()
const TransformMatrix & CGraphicContext::GetGUIMatrix () const
References m_finalTransform, and CGraphicContext::UITransform::matrix.
Referenced by CGUIShaderDX::ClipToScissorParams(), CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), CGUIFontCache< CGUIFontCacheStaticPosition, CGUIFontCacheStaticValue >::Lookup(), CGLShader::OnEnabled(), and CGLESShader::OnEnabled().
GetGUIScaleX()
float CGraphicContext::GetGUIScaleX () const
References m_finalTransform, and CGraphicContext::UITransform::scaleX.
Referenced by CGUIFont::DrawScrollingText(), CGUIFont::DrawText(), CGUIFont::GetCharWidth(), CGUIFont::GetTextWidth(), CTeletextDecoder::InitDecoder(), CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), CGUIFontCache< CGUIFontCacheStaticPosition, CGUIFontCacheStaticValue >::Lookup(), CGUIWindowDebugInfo::Process(), CGUIFontTTF::RenderCharacter(), and CGUIFont::UpdateScrollInfo().
GetGUIScaleY()
float CGraphicContext::GetGUIScaleY () const
References m_finalTransform, and CGraphicContext::UITransform::scaleY.
Referenced by CGUIFont::ClippedRegionIsEmpty(), CGUIFont::GetLineHeight(), CGUIFont::GetTextBaseLine(), CGUIFont::GetTextHeight(), CTeletextDecoder::InitDecoder(), CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), CGUIFontCache< CGUIFontCacheStaticPosition, CGUIFontCacheStaticValue >::Lookup(), CGUIWindowDebugInfo::Process(), and CGUIFontTTF::RenderCharacter().
GetGUIScaling()
void CGraphicContext::GetGUIScaling (const RESOLUTION_INFO & res, float & scaleX, float & scaleY, TransformMatrix * matrix = NULL)
References TransformMatrix::CreateScaler(), TransformMatrix::CreateTranslation(), GetResInfo(), CServiceBroker::GetSettingsComponent(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, m_Resolution, RES_INVALID, TransformMatrix::Reset(), and CSettings::SETTING_LOOKANDFEEL_SKINZOOM.
Referenced by GUIFontManager::RescaleFontSizeAndAspect(), and SetScalingResolution().
GetHeight()
int CGraphicContext::GetHeight () const
References m_iScreenHeight.
Referenced by CLinuxRendererGL::DrawBlackBars(), ADDON::Interface_GUIGeneral::get_screen_height(), EVENTCLIENT::CEventClient::GetMousePos(), KODI::RETRO::CRenderContext::GetScreenHeight(), XBMCAddon::xbmcgui::getScreenHeight(), CGUIRenderingControl::InitCallback(), CTeletextDecoder::InitDecoder(), CGUIWindowDebugInfo::Process(), VDPAU::CDecoder::SetWidthHeight(), and CRenderSystemBase::ShowSplash().
GetMediaDir()
const std::string & CGraphicContext::GetMediaDir () const
References m_strMediaDir.
Referenced by GUIFontManager::LoadTTF().
GetNormalizedDepth()
float CGraphicContext::GetNormalizedDepth (uint32_t depth)
Gets the (normalized) depth information.
Parameters
depth to be normalized
Returns
float normalized -1 to 1
References m_layer.
Referenced by CGUITexture::Render().
GetRenderOrder()
RENDER_ORDER CGraphicContext::GetRenderOrder () inline
Returns the current render order mode.
Returns
RENDER_ORDER returns the mode
References m_renderOrder.
Referenced by CGUIBaseContainer::Render(), CGUIBorderedImage::Render(), CGUIPanelContainer::Render(), CGUIWindowDebugInfo::Render(), CGUIWindowScreensaverDim::Render(), and CGUITexture::Render().
GetResInfo() [1/2]
const RESOLUTION_INFO CGraphicContext::GetResInfo () const
References GetResInfo(), and m_Resolution.
Referenced by CBaseRenderer::CalcDestRect(), OVERLAY::CRenderer::ConvertLibass(), CApplication::CreateGUI(), CResolutionUtils::FindResolutionFromOverride(), CResolutionUtils::FindResolutionFromWhitelist(), CGUIWindowFullScreen::FrameMove(), GetFPS(), GetGUIScaling(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), CResolutionUtils::GetMaxAllowedScreenResolution(), KODI::RETRO::CRenderContext::GetResInfo(), GetResInfo(), GetScalingPixelRatio(), ADDON::CSkinInfo::GetSkinPath(), CVideoPlayer::GetVideoResolution(), GetViewWindow(), CRendererDRMPRIME::ManageRenderArea(), CPlayerController::OnAction(), CResolutionUtils::PrintWhitelist(), CSlideShowPic::Process(), CGUIWindowSlideShow::Process(), OVERLAY::CRenderer::Render(), GUIFontManager::RescaleFontSizeAndAspect(), CGUIWindowSettingsScreenCalibration::ResetCalibration(), CGUIWindowSettingsScreenCalibration::ResetControls(), ResetOverscan(), OVERLAY::CRenderer::ResetSubtitlePosition(), CSlideShowPic::SetTexture_Internal(), CBaseRenderer::SetViewMode(), CRenderSystemBase::ShowSplash(), ADDON::CSkinInfo::Start(), StereoCorrection(), UpdateCameraPosition(), CGUIWindowSettingsScreenCalibration::UpdateFromControl(), and UpdateInternalStateWithResolution().
GetResInfo() [2/2]
const RESOLUTION_INFO CGraphicContext::GetResInfo (RESOLUTION res) const
References D3DPRESENTFLAG_MODE3DSBS, D3DPRESENTFLAG_MODE3DTB, RESOLUTION_INFO::fPixelRatio, CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), m_fFPSOverride, m_Resolution, m_stereoMode, RENDER_STEREO_MODE_SPLIT_HORIZONTAL, and RENDER_STEREO_MODE_SPLIT_VERTICAL.
GetScalingPixelRatio()
float CGraphicContext::GetScalingPixelRatio () const
References RESOLUTION_INFO::fPixelRatio, GetResInfo(), m_finalTransform, CGraphicContext::UITransform::scaleX, and CGraphicContext::UITransform::scaleY.
Referenced by CRotateEffect::ApplyEffect(), and CGUITexture::CalculateSize().
GetScissors()
const CRect & CGraphicContext::GetScissors () const
References m_scissors.
Referenced by CGUIControl::DoRender(), KODI::RETRO::CRenderContext::GetScissors(), CGUIFontTTFDX::LastEnd(), CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), CGUIVideoControl::Render(), and CGUIWindowSlideShow::Render().
GetStereoMode()
RENDER_STEREO_MODE CGraphicContext::GetStereoMode () inline
References m_stereoMode.
Referenced by CStereoscopicsManager::ApplyStereoMode(), CWinSystemWin10::ChangeResolution(), CRenderSystemDX::CheckInterlacedStereoView(), CWinSystemAndroid::CreateNewWindow(), CGUIControl::DoRender(), CDVDOverlayCodecFFmpeg::GetOverlay(), CRendererStarfish::ManageRenderArea(), CRendererMediaCodecSurface::RenderUpdate(), DX::DeviceResources::ResizeBuffers(), DX::DeviceResources::SetFullScreen(), CWinSystemWin10::SetFullScreen(), and CWinSystemWin32::SetFullScreen().
GetStereoView()
RENDER_STEREO_VIEW CGraphicContext::GetStereoView () inline
References m_stereoView.
Referenced by OVERLAY::GetStereoscopicDepth(), and CBaseRenderer::ManageRenderArea().
GetTransformDepth()
float CGraphicContext::GetTransformDepth (int32_t depthOffset = 0)
Gets the depth information of the current transform matrix.
Parameters
depthOffset adds an offset to the current depth
Returns
float normalized -1 to 1
References TransformMatrix::depth, m_finalTransform, m_layer, and CGraphicContext::UITransform::matrix.
Referenced by CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), and CGUITexture::Render().
GetVideoResolution()
RESOLUTION CGraphicContext::GetVideoResolution () const
References m_Resolution.
Referenced by CResolutionUtils::ChooseBestResolution(), CGUIWindowSettingsScreenCalibration::FindCurrentResolution(), Flip(), ADDON::Interface_GUIGeneral::get_video_resolution(), CRenderManager::GetResolution(), KODI::RETRO::CRenderContext::GetVideoResolution(), CWinSystemWin32::NotifyAppFocusChange(), CPlayerController::OnAction(), CApplication::OnApplicationMessage(), CGUIWindowSlideShow::OnMessage(), CGUIWindowSettingsScreenCalibration::OnMessage(), CApplicationSettingsHandling::OnSettingChanged(), CDisplaySettings::OnSettingChanging(), CGUIWindowSlideShow::Render(), and CGUIWindowSlideShow::Reset().
GetViewWindow()
const CRect CGraphicContext::GetViewWindow () const
References GetResInfo(), m_bCalibrating, m_bFullScreenVideo, m_videoRect, CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by KODI::RETRO::CRenderContext::GetViewWindow(), and CBaseRenderer::ManageRenderArea().
GetWidth()
int CGraphicContext::GetWidth () const
References m_iScreenWidth.
Referenced by CLinuxRendererGL::DrawBlackBars(), ADDON::Interface_GUIGeneral::get_screen_width(), EVENTCLIENT::CEventClient::GetMousePos(), KODI::RETRO::CRenderContext::GetScreenWidth(), XBMCAddon::xbmcgui::getScreenWidth(), CGUIRenderingControl::InitCallback(), CTeletextDecoder::InitDecoder(), CGUIWindowSlideShow::OnAction(), CGUIWindowDebugInfo::Process(), VDPAU::CDecoder::SetWidthHeight(), and CRenderSystemBase::ShowSplash().
InvertFinalCoords()
void CGraphicContext::InvertFinalCoords (float & x, float & y) const
References TransformMatrix::InverseTransformPosition(), m_finalTransform, and CGraphicContext::UITransform::matrix.
Referenced by CGUIWindow::OnMouseAction().
IsCalibrating()
bool CGraphicContext::IsCalibrating () const
References m_bCalibrating.
Referenced by KODI::RETRO::CRenderContext::IsCalibrating().
IsFullScreenRoot()
bool CGraphicContext::IsFullScreenRoot () const
References m_bFullScreenRoot.
Referenced by KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), CWinSystemIOS::Minimize(), CWinSystemTVOS::Minimize(), CApplicationSettingsHandling::OnSettingChanged(), and CVideoPlayer::OpenVideoStream().
IsFullScreenVideo()
bool CGraphicContext::IsFullScreenVideo () const
References m_bFullScreenVideo.
Referenced by KODI::RETRO::CRenderContext::IsFullScreenVideo(), and CApplication::IsPlayingFullScreenVideo().
IsTransferPQ()
bool CGraphicContext::IsTransferPQ () const inline
References m_isTransferPQ.
Referenced by CRenderSystemGLES::BeginRender().
IsValidResolution()
bool CGraphicContext::IsValidResolution (RESOLUTION res)
References CDisplaySettings::GetInstance(), and RES_WINDOW.
Referenced by ApplyVideoResolution(), and SetVideoResolutionInternal().
MergeAlpha()
Color CGraphicContext::MergeAlpha (KODI::UTILS::COLOR::Color color) const
References color, m_finalTransform, CGraphicContext::UITransform::matrix, and TransformMatrix::TransformAlpha().
Referenced by CGUIControl::DoRender(), KODI::RETRO::CRenderContext::MergeAlpha(), CGUIVideoControl::Render(), CGUIWindowSlideShow::Render(), and CGUIWindowScreensaverDim::Render().
MergeColor()
Color CGraphicContext::MergeColor (KODI::UTILS::COLOR::Color color) const
References color, m_finalTransform, CGraphicContext::UITransform::matrix, and TransformMatrix::TransformColor().
Referenced by CGUIFont::DrawScrollingText(), CGUIFont::DrawText(), and CGUITexture::Render().
RectIsAngled()
bool CGraphicContext::RectIsAngled (float x1, float y1, float x2, float y2) const
References m_finalTransform, CGraphicContext::UITransform::matrix, and TransformMatrix::TransformZCoord().
RemoveTransform()
void CGraphicContext::RemoveTransform ()
References m_finalTransform, and m_transforms.
Referenced by CGUIControl::DoProcess(), CGUIWindow::DoProcess(), CGUIWindowSettingsScreenCalibration::DoProcess(), CGUIControl::DoRender(), CGUIWindow::DoRender(), CGUIFadeLabelControl::Process(), CGUITextBox::Process(), KODI::RETRO::CRenderContext::RemoveTransform(), CGUIFadeLabelControl::Render(), CGUITextBox::Render(), CGUIVideoControl::Render(), CGUITextLayout::Render(), CGUITextLayout::RenderScrolling(), and RestoreOrigin().
ResetDepth()
void CGraphicContext::ResetDepth () inline
Resets the z-depth. Layer 0 and 1 are reserved as presentation (video) layer.
References m_layer.
Referenced by CGUIWindowManager::AfterRender().
ResetOverscan() [1/2]
void CGraphicContext::ResetOverscan (RESOLUTION res, OVERSCAN & overscan)
References OVERSCAN::bottom, GetResInfo(), OVERSCAN::left, OVERSCAN::right, and OVERSCAN::top.
Referenced by CWinSystemIOS::FillInVideoModes(), CWinSystemTVOS::FillInVideoModes(), ResetScreenParameters(), CWinSystemBase::SetWindowResolution(), KODI::WINDOWING::GBM::CWinSystemGbm::UpdateResolutions(), CWinSystemWin10::UpdateResolutions(), CWinSystemWin32::UpdateResolutions(), KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions(), and CWinSystemAndroid::UpdateResolutions().
ResetOverscan() [2/2]
void CGraphicContext::ResetOverscan (RESOLUTION_INFO & resinfo)
References OVERSCAN::bottom, RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, OVERSCAN::left, RESOLUTION_INFO::Overscan, OVERSCAN::right, and OVERSCAN::top.
ResetScissors()
void CGraphicContext::ResetScissors ()
References CServiceBroker::GetRenderSystem(), m_iScreenHeight, m_iScreenWidth, m_scissors, CRectGen< T >::SetRect(), CRenderSystemBase::SetScissors(), and StereoCorrection().
Referenced by CGUIWindowManager::Render().
ResetScreenParameters()
void CGraphicContext::ResetScreenParameters (RESOLUTION res)
References CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), RESOLUTION_INFO::iSubtitles, and ResetOverscan().
Referenced by CGUIWindowSettingsScreenCalibration::ResetCalibration().
RestoreCameraPosition()
void CGraphicContext::RestoreCameraPosition ()
References m_cameras, m_stereoFactors, and UpdateCameraPosition().
Referenced by CGUIControl::DoProcess(), and CGUIControl::DoRender().
RestoreClipRegion()
void CGraphicContext::RestoreClipRegion ()
References m_clipRegions.
Referenced by CGUIFont::DrawScrollingText(), CGUIFont::DrawText(), PVR::CGUIEPGGridContainer::HandleChannels(), PVR::CGUIEPGGridContainer::HandleProgrammeGrid(), PVR::CGUIEPGGridContainer::HandleRuler(), PVR::CGUIEPGGridContainer::HandleRulerDate(), CGUIMultiImage::Process(), CGUIEditControl::ProcessText(), CGUIBaseContainer::Render(), CGUIControlGroupList::Render(), CGUIPanelContainer::Render(), CGUIProgressControl::Render(), CGUITextBox::Render(), CGUITexture::Render(), PVR::CGUIEPGGridContainer::RenderProgressIndicator(), and CGUIEditControl::RenderText().
RestoreOrigin()
void CGraphicContext::RestoreOrigin ()
References m_origins, and RemoveTransform().
Referenced by CGUIControlGroup::Process(), CGUIControlGroupList::Process(), CGUIListGroup::Process(), PVR::CGUIEPGGridContainer::ProcessItem(), CGUIBaseContainer::ProcessItem(), CGUIControlGroup::Render(), CGUIControlGroupList::Render(), CGUIBaseContainer::RenderItem(), and PVR::CGUIEPGGridContainer::RenderItem().
RestoreStereoFactor()
void CGraphicContext::RestoreStereoFactor ()
References m_cameras, m_stereoFactors, and UpdateCameraPosition().
Referenced by CGUIControl::DoRender().
RestoreViewPort()
void CGraphicContext::RestoreViewPort ()
References CServiceBroker::GetRenderSystem(), m_cameras, m_stereoFactors, m_viewStack, CRenderSystemBase::SetViewPort(), StereoCorrection(), and UpdateCameraPosition().
Referenced by CGUIRenderingControl::Render().
ScaleFinalCoords()
void CGraphicContext::ScaleFinalCoords (float & x, float & y, float & z) const
References m_finalTransform, CGraphicContext::UITransform::matrix, and TransformMatrix::TransformPosition().
Referenced by GenerateAABB(), CGUIWindow::GetScaledBounds(), and SetViewPort().
ScaleFinalXCoord()
float CGraphicContext::ScaleFinalXCoord (float x, float y) const
References m_finalTransform, CGraphicContext::UITransform::matrix, and TransformMatrix::TransformXCoord().
Referenced by CGUIFontTTF::DrawTextInternal(), CGUIRenderingControl::InitCallback(), CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), CGUIFontTTF::RenderCharacter(), CGUIDialogTeletext::SetCoordinates(), and SetViewWindow().
ScaleFinalYCoord()
float CGraphicContext::ScaleFinalYCoord (float x, float y) const
References m_finalTransform, CGraphicContext::UITransform::matrix, and TransformMatrix::TransformYCoord().
Referenced by CGUIFontTTF::DrawTextInternal(), CGUIRenderingControl::InitCallback(), CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), CGUIFontTTF::RenderCharacter(), CGUIDialogTeletext::SetCoordinates(), and SetViewWindow().
ScaleFinalZCoord()
float CGraphicContext::ScaleFinalZCoord (float x, float y) const
References m_finalTransform, CGraphicContext::UITransform::matrix, and TransformMatrix::TransformZCoord().
Referenced by CGUIFontTTF::DrawTextInternal(), and CGUIFontTTF::RenderCharacter().
SetCalibrating()
void CGraphicContext::SetCalibrating (bool bOnOff)
References m_bCalibrating.
Referenced by CGUIWindowSettingsScreenCalibration::OnMessage().
SetCameraPosition()
void CGraphicContext::SetCameraPosition (const CPoint & camera)
References RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, m_cameras, m_iScreenHeight, m_iScreenWidth, m_origins, m_stereoFactors, m_windowResolution, UpdateCameraPosition(), CPointGen< T >::x, and CPointGen< T >::y.
Referenced by CGUIControl::DoProcess(), and CGUIControl::DoRender().
SetClipRegion()
bool CGraphicContext::SetClipRegion (float x, float y, float w, float h)
Set a region in which to clip all rendering Anything that is rendered after setting a clip region will be clipped so that no part renders outside of the clip region. Successive calls to SetClipRegion intersect the clip region, which means the clip region may eventually become an empty set. In this case SetClipRegion returns false to indicate that no rendering need be performed.
This call must be matched with a RestoreClipRegion call unless SetClipRegion returns false.
Usage should be of the form:
if (SetClipRegion(x, y, w, h)) { ... perform rendering ... RestoreClipRegion(); }
Parameters
x the left-most coordinate of the clip region
y the top-most coordinate of the clip region
w the width of the clip region
h the height of the clip region
Returns
true if the region is set and the result is non-empty. Returns false if the resulting region is empty.
See also
RestoreClipRegion
References CRectGen< T >::Intersect(), CRectGen< T >::IsEmpty(), m_clipRegions, and m_origins.
Referenced by CGUIFont::ClippedRegionIsEmpty(), PVR::CGUIEPGGridContainer::HandleChannels(), PVR::CGUIEPGGridContainer::HandleProgrammeGrid(), PVR::CGUIEPGGridContainer::HandleRuler(), PVR::CGUIEPGGridContainer::HandleRulerDate(), and CGUIProgressControl::Render().
SetFPS()
void CGraphicContext::SetFPS (float fps)
References m_fFPSOverride.
Referenced by KODI::WINDOWING::X11::CWinSystemX11::UpdateCrtc().
SetFullScreenVideo()
void CGraphicContext::SetFullScreenVideo (bool bOnOff)
References ADJUST_REFRESHRATE_ALWAYS, ADJUST_REFRESHRATE_ON_START, CServiceBroker::GetAppComponents(), CDisplaySettings::GetCurrentResolution(), CDisplaySettings::GetInstance(), CServiceBroker::GetSettingsComponent(), m_bFullScreenRoot, m_bFullScreenVideo, RES_DESKTOP, RES_WINDOW, CSettings::SETTING_VIDEOPLAYER_ADJUSTREFRESHRATE, SetVideoResolution(), and CApplicationPlayer::TriggerUpdateResolution().
Referenced by KODI::RETRO::CGameWindowFullScreen::OnDeinitWindow(), KODI::RETRO::CGameWindowFullScreen::OnInitWindow(), CGUIWindowFullScreen::OnMessage(), CApplication::PlaybackCleanup(), and KODI::RETRO::CRenderContext::SetFullScreenVideo().
SetMediaDir()
void CGraphicContext::SetMediaDir (const std::string & strMediaDir)
References CServiceBroker::GetGUI(), CGUIComponent::GetTextureManager(), m_strMediaDir, and CGUITextureManager::SetTexturePath().
Referenced by CApplicationSkinHandling::LoadSkin().
SetOrigin()
void CGraphicContext::SetOrigin (float x, float y)
References AddTransform(), TransformMatrix::CreateTranslation(), and m_origins.
Referenced by CGUIControlGroup::Process(), CGUIControlGroupList::Process(), CGUIListGroup::Process(), PVR::CGUIEPGGridContainer::ProcessItem(), CGUIBaseContainer::ProcessItem(), CGUIControlGroup::Render(), CGUIControlGroupList::Render(), CGUIBaseContainer::RenderItem(), and PVR::CGUIEPGGridContainer::RenderItem().
SetRenderingResolution()
void CGraphicContext::SetRenderingResolution (const RESOLUTION_INFO & res, bool needsScaling)
Sets scaling up for rendering.
References m_cameras, m_stereoFactors, SetScalingResolution(), and UpdateCameraPosition().
Referenced by CGUIWindow::DoProcess(), CGUIWindowSettingsScreenCalibration::DoProcess(), CGUIWindow::DoRender(), CGUIWindowDebugInfo::Process(), CGUIWindowManager::Render(), CGUIWindowSlideShow::Render(), CGUIWindowFullScreen::Render(), CGUIWindowDebugInfo::Render(), CGUIWindowSplash::Render(), CGUIWindowFullScreen::RenderEx(), KODI::RETRO::CRenderContext::SetRenderingResolution(), and CRenderSystemBase::ShowSplash().
SetRenderOrder()
void CGraphicContext::SetRenderOrder (RENDER_ORDER renderOrder)
Sets the direction of the current rendering pass.
Parameters
renderOrder direction of the pass
References DEPTH_CULLING_BACK_TO_FRONT, DEPTH_CULLING_FRONT_TO_BACK, DEPTH_CULLING_OFF, CServiceBroker::GetRenderSystem(), m_renderOrder, RENDER_ORDER_ALL_BACK_TO_FRONT, RENDER_ORDER_BACK_TO_FRONT, RENDER_ORDER_FRONT_TO_BACK, and CRenderSystemBase::SetDepthCulling().
Referenced by CGUIWindowDebugInfo::Render(), and CGUIWindowScreensaverDim::Render().
SetResInfo()
void CGraphicContext::SetResInfo (RESOLUTION res, const RESOLUTION_INFO & info)
References OVERSCAN::bottom, D3DPRESENTFLAG_MODE3DSBS, D3DPRESENTFLAG_MODE3DTB, RESOLUTION_INFO::dwFlags, RESOLUTION_INFO::fPixelRatio, CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), RESOLUTION_INFO::guiInsets, RESOLUTION_INFO::iSubtitles, RESOLUTION_INFO::Overscan, and OVERSCAN::right.
Referenced by OVERLAY::CRenderer::ConvertLibass(), and CGUIWindowSettingsScreenCalibration::UpdateFromControl().
SetScalingResolution()
void CGraphicContext::SetScalingResolution (const RESOLUTION_INFO & res, bool needsScaling)
Sets scaling up for skin loading etc.
References GetGUIScaling(), m_cameras, m_finalTransform, m_guiTransform, m_iScreenHeight, m_iScreenWidth, m_origins, m_Resolution, m_stereoFactors, m_windowResolution, CGraphicContext::UITransform::matrix, RES_INVALID, CGraphicContext::UITransform::Reset(), CGraphicContext::UITransform::scaleX, and CGraphicContext::UITransform::scaleY.
Referenced by CGUIWindow::GetScaledBounds(), CGUIWindow::Load(), CGUIWindow::OnMouseAction(), CGUIWindowDebugInfo::Process(), CGUIDialogTeletext::SetCoordinates(), SetRenderingResolution(), and CGUIDialogKeyboardGeneric::ShowWordList().
SetScissors()
void CGraphicContext::SetScissors (const CRect & rect)
References CServiceBroker::GetRenderSystem(), CRectGen< T >::Intersect(), m_iScreenHeight, m_iScreenWidth, m_scissors, CRenderSystemBase::SetScissors(), and StereoCorrection().
Referenced by CRendererHQ::FinalOutput(), CGUIWindowManager::Render(), CGUIVideoControl::Render(), and CGUIWindowSlideShow::Render().
SetStereoFactor()
void CGraphicContext::SetStereoFactor (float factor)
References m_cameras, m_stereoFactors, and UpdateCameraPosition().
Referenced by CGUIControl::DoRender().
SetStereoMode()
void CGraphicContext::SetStereoMode (RENDER_STEREO_MODE mode) inline
References m_nextStereoMode.
Referenced by CStereoscopicsManager::ApplyStereoMode(), CRenderSystemDX::CheckInterlacedStereoView(), and DX::DeviceResources::ResizeBuffers().
SetStereoView()
void CGraphicContext::SetStereoView (RENDER_STEREO_VIEW view)
References CServiceBroker::GetRenderSystem(), m_iScreenHeight, m_iScreenWidth, m_stereoMode, m_stereoView, m_viewStack, CRenderSystemBase::SetScissors(), CRenderSystemBase::SetStereoMode(), CRenderSystemBase::SetViewPort(), and StereoCorrection().
Referenced by ApplyVideoResolution(), CRendererStarfish::ManageRenderArea(), CApplication::Render(), CRendererMediaCodecSurface::RenderUpdate(), and SetVideoResolutionInternal().
SetTransferPQ()
void CGraphicContext::SetTransferPQ (bool PQ) inline
References m_isTransferPQ.
Referenced by CRendererMediaCodecSurface::Configure(), and CRendererMediaCodecSurface::Reset().
SetTransform() [1/2]
void CGraphicContext::SetTransform (const TransformMatrix & matrix)
References m_finalTransform, m_transforms, and CGraphicContext::UITransform::matrix.
Referenced by CGUIControl::DoRender(), CGUIFadeLabelControl::Render(), CGUITextBox::Render(), CGUIVideoControl::Render(), and KODI::RETRO::CRenderContext::SetTransform().
SetTransform() [2/2]
void CGraphicContext::SetTransform (const TransformMatrix & matrix, float scaleX, float scaleY)
References m_finalTransform, m_transforms, CGraphicContext::UITransform::matrix, CGraphicContext::UITransform::scaleX, and CGraphicContext::UITransform::scaleY.
SetVideoResolution()
void CGraphicContext::SetVideoResolution (RESOLUTION res, bool forceUpdate)
References CServiceBroker::GetAppMessenger(), SetVideoResolutionInternal(), and TMSG_SETVIDEORESOLUTION.
Referenced by Flip(), CApplication::InitWindow(), CGUIWindowSettingsScreenCalibration::OnAction(), CPlayerController::OnAction(), CApplication::OnApplicationMessage(), CGUIWindowSlideShow::OnMessage(), CGUIWindowSettingsScreenCalibration::OnMessage(), CApplicationSettingsHandling::OnSettingChanged(), CDisplaySettings::OnSettingChanging(), CVideoPlayer::OpenVideoStream(), KODI::WINDOWING::X11::CWinSystemX11::RecreateWindow(), SetFullScreenVideo(), and CRenderManager::UpdateResolution().
SetVideoResolutionInternal()
void CGraphicContext::SetVideoResolutionInternal (RESOLUTION res, bool forceUpdate) protected
References CServiceBroker::GetGUI(), CServiceBroker::GetInputManager(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), GUI_MSG_NOTIFY_ALL, GUI_MSG_WINDOW_RESIZE, RESOLUTION_INFO::iHeight, IsValidResolution(), RESOLUTION_INFO::iWidth, m_bFullScreenRoot, m_fFPSOverride, m_iScreenHeight, m_iScreenWidth, m_Resolution, m_scissors, RENDER_STEREO_VIEW_OFF, RES_DESKTOP, CWinSystemBase::ResizeWindow(), CGUIWindowManager::SendMessage(), CWinSystemBase::SetFullScreen(), CInputManager::SetMouseResolution(), CRectGen< T >::SetRect(), SetStereoView(), CSettings::SETTING_VIDEOSCREEN_BLANKDISPLAYS, and UpdateInternalStateWithResolution().
Referenced by SetVideoResolution().
SetViewPort()
bool CGraphicContext::SetViewPort (float fx, float fy, float fwidth, float fheight, bool intersectPrevious = false)
References CServiceBroker::GetRenderSystem(), m_cameras, m_iScreenHeight, m_iScreenWidth, m_stereoFactors, m_viewStack, ScaleFinalCoords(), CRenderSystemBase::SetViewPort(), StereoCorrection(), UpdateCameraPosition(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CGUIRenderingControl::Render(), and CGUIVisualisationControl::Render().
SetViewWindow()
void CGraphicContext::SetViewWindow (float left, float top, float right, float bottom)
References left, m_videoRect, right, ScaleFinalXCoord(), ScaleFinalYCoord(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CGUIVideoControl::Render(), CGUIWindowSlideShow::Render(), and KODI::RETRO::CRenderContext::SetViewWindow().
StereoCorrection() [1/2]
CPoint CGraphicContext::StereoCorrection (const CPoint & point) const
References GetResInfo(), m_stereoMode, m_stereoView, RENDER_STEREO_MODE_SPLIT_HORIZONTAL, RENDER_STEREO_MODE_SPLIT_VERTICAL, RENDER_STEREO_VIEW_RIGHT, CPointGen< T >::x, and CPointGen< T >::y.
StereoCorrection() [2/2]
CRect CGraphicContext::StereoCorrection (const CRect & rect) const
References CRectGen< T >::P1(), CRectGen< T >::P2(), and StereoCorrection().
Referenced by CRendererDXVA::ApplyTransforms(), CRendererHQ::FinalOutput(), CGUIFontTTFDX::LastEnd(), CGUIFontTTFGL::LastEnd(), CGUIFontTTFGLES::LastEnd(), ResetScissors(), RestoreViewPort(), SetScissors(), SetStereoView(), SetViewPort(), KODI::RETRO::CRenderContext::StereoCorrection(), and StereoCorrection().
ToggleFullScreen()
void CGraphicContext::ToggleFullScreen ()
References CDisplaySettings::GetCurrentResolution(), CDisplaySettings::GetInstance(), m_bFullScreenRoot, RES_DESKTOP, RES_WINDOW, and CDisplaySettings::SetCurrentResolution().
Referenced by CApplication::OnAction(), and CApplication::OnApplicationMessage().
UpdateCameraPosition()
void CGraphicContext::UpdateCameraPosition (const CPoint & camera, const float & factor) protected
References CServiceBroker::GetRenderSystem(), GetResInfo(), CServiceBroker::GetSettingsComponent(), RESOLUTION_INFO::iWidth, m_iScreenHeight, m_iScreenWidth, m_stereoMode, m_stereoView, RENDER_STEREO_MODE_MONO, RENDER_STEREO_MODE_OFF, RENDER_STEREO_VIEW_LEFT, RENDER_STEREO_VIEW_OFF, RES_DESKTOP, CRenderSystemBase::SetCameraPosition(), and CSettings::SETTING_LOOKANDFEEL_STEREOSTRENGTH.
Referenced by RestoreCameraPosition(), RestoreStereoFactor(), RestoreViewPort(), SetCameraPosition(), SetRenderingResolution(), SetStereoFactor(), and SetViewPort().
UpdateInternalStateWithResolution()
void CGraphicContext::UpdateInternalStateWithResolution (RESOLUTION res) protected
References GetResInfo(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, m_fFPSOverride, m_iScreenHeight, m_iScreenWidth, and m_Resolution.
Referenced by ApplyVideoResolution(), and SetVideoResolutionInternal().
Member Data Documentation
m_bCalibrating
bool CGraphicContext::m_bCalibrating = false protected
Referenced by GetViewWindow(), IsCalibrating(), and SetCalibrating().
m_bFullScreenRoot
bool CGraphicContext::m_bFullScreenRoot = true protected
Referenced by ApplyVideoResolution(), IsFullScreenRoot(), SetFullScreenVideo(), SetVideoResolutionInternal(), and ToggleFullScreen().
m_bFullScreenVideo
bool CGraphicContext::m_bFullScreenVideo = false protected
Referenced by GetViewWindow(), IsFullScreenVideo(), and SetFullScreenVideo().
m_cameras
std::stack<CPoint> CGraphicContext::m_cameras protected
Referenced by RestoreCameraPosition(), RestoreStereoFactor(), RestoreViewPort(), SetCameraPosition(), SetRenderingResolution(), SetScalingResolution(), SetStereoFactor(), and SetViewPort().
m_clipRegions
std::stack<CRect> CGraphicContext::m_clipRegions protected
Referenced by ClipRect(), GetClipRegion(), RestoreClipRegion(), and SetClipRegion().
m_fFPSOverride
float CGraphicContext::m_fFPSOverride = 0.0f protected
Referenced by GetResInfo(), SetFPS(), SetVideoResolutionInternal(), and UpdateInternalStateWithResolution().
m_finalTransform
UITransform CGraphicContext::m_finalTransform protected
Referenced by AddGUITransform(), AddTransform(), GetGUIMatrix(), GetGUIScaleX(), GetGUIScaleY(), GetScalingPixelRatio(), GetTransformDepth(), InvertFinalCoords(), MergeAlpha(), MergeColor(), RectIsAngled(), RemoveTransform(), ScaleFinalCoords(), ScaleFinalXCoord(), ScaleFinalYCoord(), ScaleFinalZCoord(), SetScalingResolution(), SetTransform(), and SetTransform().
m_guiTransform
UITransform CGraphicContext::m_guiTransform protected
Referenced by AddGUITransform(), and SetScalingResolution().
m_iScreenHeight
int CGraphicContext::m_iScreenHeight = 576 protected
Referenced by ApplyVideoResolution(), GetClipRegion(), GetHeight(), ResetScissors(), SetCameraPosition(), SetScalingResolution(), SetScissors(), SetStereoView(), SetVideoResolutionInternal(), SetViewPort(), UpdateCameraPosition(), and UpdateInternalStateWithResolution().
m_iScreenWidth
int CGraphicContext::m_iScreenWidth = 720 protected
Referenced by ApplyVideoResolution(), GetClipRegion(), GetWidth(), ResetScissors(), SetCameraPosition(), SetScalingResolution(), SetScissors(), SetStereoView(), SetVideoResolutionInternal(), SetViewPort(), UpdateCameraPosition(), and UpdateInternalStateWithResolution().
m_isTransferPQ
bool CGraphicContext::m_isTransferPQ {false} protected
Referenced by IsTransferPQ(), and SetTransferPQ().
m_layer
uint32_t CGraphicContext::m_layer {2} protected
Referenced by GetDepth(), GetNormalizedDepth(), GetTransformDepth(), and ResetDepth().
m_nextStereoMode
RENDER_STEREO_MODE CGraphicContext::m_nextStereoMode = RENDER_STEREO_MODE_OFF protected
Referenced by Flip(), and SetStereoMode().
m_origins
std::stack<CPoint> CGraphicContext::m_origins protected
Referenced by ClipRect(), GetClipRegion(), RestoreOrigin(), SetCameraPosition(), SetClipRegion(), SetOrigin(), and SetScalingResolution().
m_renderOrder
RENDER_ORDER CGraphicContext::m_renderOrder {RENDER_ORDER_ALL_BACK_TO_FRONT} protected
Referenced by GetRenderOrder(), and SetRenderOrder().
m_Resolution
RESOLUTION CGraphicContext::m_Resolution = RES_INVALID protected
Referenced by GetFPS(), GetGUIScaling(), GetResInfo(), GetResInfo(), GetVideoResolution(), SetScalingResolution(), SetVideoResolutionInternal(), and UpdateInternalStateWithResolution().
m_scissors
CRect CGraphicContext::m_scissors protected
Referenced by ApplyVideoResolution(), GetScissors(), ResetScissors(), SetScissors(), and SetVideoResolutionInternal().
m_stereoFactors
std::stack<float> CGraphicContext::m_stereoFactors protected
Referenced by RestoreCameraPosition(), RestoreStereoFactor(), RestoreViewPort(), SetCameraPosition(), SetRenderingResolution(), SetScalingResolution(), SetStereoFactor(), and SetViewPort().
m_stereoMode
RENDER_STEREO_MODE CGraphicContext::m_stereoMode = RENDER_STEREO_MODE_OFF protected
Referenced by Flip(), GetResInfo(), GetStereoMode(), SetStereoView(), StereoCorrection(), and UpdateCameraPosition().
m_stereoView
RENDER_STEREO_VIEW CGraphicContext::m_stereoView = RENDER_STEREO_VIEW_OFF protected
Referenced by GetStereoView(), SetStereoView(), StereoCorrection(), and UpdateCameraPosition().
m_strMediaDir
std::string CGraphicContext::m_strMediaDir protected
Referenced by GetMediaDir(), and SetMediaDir().
m_transforms
std::stack<UITransform> CGraphicContext::m_transforms protected
Referenced by AddGUITransform(), AddTransform(), RemoveTransform(), SetTransform(), and SetTransform().
m_videoRect
CRect CGraphicContext::m_videoRect protected
Referenced by GetViewWindow(), and SetViewWindow().
m_viewStack
std::stack<CRect> CGraphicContext::m_viewStack protected
Referenced by RestoreViewPort(), SetStereoView(), and SetViewPort().
m_windowResolution
RESOLUTION_INFO CGraphicContext::m_windowResolution protected
Referenced by SetCameraPosition(), and SetScalingResolution().
The documentation for this class was generated from the following files:
GraphicContext.h
GraphicContext.cpp