Kodi Documentation: KODI::WINDOWING::WAYLAND::CSeatInputProcessing Class Reference
KODI::WINDOWING::WAYLAND::CSeatInputProcessing Class Reference final
#include <SeatInputProcessing.h>
Classes
struct SeatState
Public Member Functions
CSeatInputProcessing (wayland::surface_t const &inputSurface, IInputHandler &handler)
void AddSeat (CSeat *seat)
void RemoveSeat (CSeat *seat)
void SetCoordinateScale (std::int32_t scale)
Public Member Functions inherited from KODI::WINDOWING::WAYLAND::IInputHandlerKeyboard
virtual ~IInputHandlerKeyboard ()=default
Private Member Functions
void OnPointerEnter (std::uint32_t seatGlobalName, std::uint32_t serial) override
void OnPointerLeave () override
void OnPointerEvent (XBMC_Event &event) override
void OnKeyboardEnter () override
void OnKeyboardLeave () override
void OnKeyboardEvent (XBMC_Event &event) override
Private Attributes
wayland::surface_t m_inputSurface
IInputHandler & m_handler
std::map< std::uint32_t, SeatState > m_seats
Additional Inherited Members
Protected Member Functions inherited from KODI::WINDOWING::WAYLAND::IInputHandlerPointer
~IInputHandlerPointer ()=default
Detailed Description
Receive events from all registered wl_seats and process them into Kodi events
Multi-seat support is not currently implemented completely, but each seat has separate state.
Constructor & Destructor Documentation
CSeatInputProcessing()
CSeatInputProcessing::CSeatInputProcessing (wayland::surface_t const & inputSurface, IInputHandler & handler)
Construct a seat input processor
Parameters
inputSurface Surface that events should be processed on (all other surfaces are ignored)
handler Mandatory handler for processed input events
Member Function Documentation
AddSeat()
void CSeatInputProcessing::AddSeat (CSeat * seat)
References KODI::WINDOWING::WAYLAND::CSeat::AddRawInputHandlerKeyboard(), KODI::WINDOWING::WAYLAND::CSeat::AddRawInputHandlerPointer(), KODI::WINDOWING::WAYLAND::CSeat::AddRawInputHandlerTouch(), KODI::WINDOWING::WAYLAND::CSeat::GetGlobalName(), m_inputSurface, and m_seats.
OnKeyboardEnter()
void CSeatInputProcessing::OnKeyboardEnter () override private virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IInputHandlerKeyboard.
References KODI::WINDOWING::WAYLAND::KEYBOARD, m_handler, and KODI::WINDOWING::WAYLAND::IInputHandler::OnEnter().
OnKeyboardEvent()
void CSeatInputProcessing::OnKeyboardEvent (XBMC_Event & event) override private virtual
Implements KODI::WINDOWING::WAYLAND::IInputHandlerKeyboard.
References KODI::WINDOWING::WAYLAND::KEYBOARD, m_handler, and KODI::WINDOWING::WAYLAND::IInputHandler::OnEvent().
OnKeyboardLeave()
void CSeatInputProcessing::OnKeyboardLeave () override private virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IInputHandlerKeyboard.
References KODI::WINDOWING::WAYLAND::KEYBOARD, m_handler, and KODI::WINDOWING::WAYLAND::IInputHandler::OnLeave().
OnPointerEnter()
void CSeatInputProcessing::OnPointerEnter (std::uint32_t seatGlobalName, std::uint32_t serial) override private virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IInputHandlerPointer.
References m_handler, KODI::WINDOWING::WAYLAND::IInputHandler::OnEnter(), KODI::WINDOWING::WAYLAND::IInputHandler::OnSetCursor(), and KODI::WINDOWING::WAYLAND::POINTER.
OnPointerEvent()
void CSeatInputProcessing::OnPointerEvent (XBMC_Event & event) override private virtual
Implements KODI::WINDOWING::WAYLAND::IInputHandlerPointer.
References m_handler, KODI::WINDOWING::WAYLAND::IInputHandler::OnEvent(), and KODI::WINDOWING::WAYLAND::POINTER.
OnPointerLeave()
void CSeatInputProcessing::OnPointerLeave () override private virtual
Reimplemented from KODI::WINDOWING::WAYLAND::IInputHandlerPointer.
References m_handler, KODI::WINDOWING::WAYLAND::IInputHandler::OnLeave(), and KODI::WINDOWING::WAYLAND::POINTER.
RemoveSeat()
void CSeatInputProcessing::RemoveSeat (CSeat * seat)
References KODI::WINDOWING::WAYLAND::CSeat::GetGlobalName(), m_seats, KODI::WINDOWING::WAYLAND::CSeat::RemoveRawInputHandlerKeyboard(), KODI::WINDOWING::WAYLAND::CSeat::RemoveRawInputHandlerPointer(), and KODI::WINDOWING::WAYLAND::CSeat::RemoveRawInputHandlerTouch().
SetCoordinateScale()
void CSeatInputProcessing::SetCoordinateScale (std::int32_t scale)
Set the scale the coordinates should be interpreted at
Wayland input events are always in surface coordinates, but Kodi only uses buffer coordinates internally. Use this function to set the scaling factor between the two and multiply the surface coordinates accordingly for Kodi events.
Parameters
scale new buffer-to-surface pixel ratio
References m_seats.
Member Data Documentation
m_handler
IInputHandler& KODI::WINDOWING::WAYLAND::CSeatInputProcessing::m_handler private
Referenced by OnKeyboardEnter(), OnKeyboardEvent(), OnKeyboardLeave(), OnPointerEnter(), OnPointerEvent(), and OnPointerLeave().
m_inputSurface
wayland::surface_t KODI::WINDOWING::WAYLAND::CSeatInputProcessing::m_inputSurface private
Referenced by AddSeat().
m_seats
std::map<std::uint32_t, SeatState> KODI::WINDOWING::WAYLAND::CSeatInputProcessing::m_seats private
Referenced by AddSeat(), RemoveSeat(), and SetCoordinateScale().
The documentation for this class was generated from the following files:
SeatInputProcessing.h
SeatInputProcessing.cpp