Kodi Documentation: PVR::CPVRGUIInfo Class Reference
PVR::CPVRGUIInfo Class Reference
#include <PVRGUIInfo.h>
Public Member Functions
CPVRGUIInfo ()
~CPVRGUIInfo () override=default
void Start ()
void Stop ()
void Notify (const PVREvent &event)
CEventStream callback for PVR events.
void Notify (const PVRChannelNumberInputChangedEvent &event)
CEventStream callback for channel number input changes.
void Notify (const PVRPreviewAndPlayerShowInfoChangedEvent &event)
CEventStream callback for channel preview and player show info changes.
bool InitCurrentItem (CFileItem *item) override
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
bool GetLabel (std::string &value, const CFileItem *item, int contextWindow, const KODI::GUILIB::GUIINFO::CGUIInfo &info, std::string *fallback) const override
Get a GUIInfoManager label string.
bool GetFallbackLabel (std::string &value, const CFileItem *item, int contextWindow, const KODI::GUILIB::GUIINFO::CGUIInfo &info, std::string *fallback) override
Get a GUIInfoManager label fallback string. Will be called if none of the registered provider's GetLabel() implementation has returned success.
bool GetInt (int &value, const CGUIListItem *item, int contextWindow, const KODI::GUILIB::GUIINFO::CGUIInfo &info) const override
Get a GUIInfoManager integer value.
bool GetBool (bool &value, const CGUIListItem *item, int contextWindow, const KODI::GUILIB::GUIINFO::CGUIInfo &info) const override
Get a GUIInfoManager bool value.
Public Member Functions inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
CGUIInfoProvider ()=default
~CGUIInfoProvider () override=default
void UpdateAVInfo (const AudioStreamInfo &audioInfo, const VideoStreamInfo &videoInfo, const SubtitleStreamInfo &subtitleInfo) override
Set new audio/video stream info data.
Public Member Functions inherited from KODI::GUILIB::GUIINFO::IGUIInfoProvider
virtual ~IGUIInfoProvider ()=default
Private Member Functions
void ResetProperties ()
void ClearQualityInfo (CPVRSignalStatus &qualityInfo)
void ClearDescrambleInfo (CPVRDescrambleInfo &descrambleInfo)
void Process () override
void UpdateTimersCache ()
void UpdateBackendCache ()
void UpdateQualityData ()
void UpdateDescrambleData ()
void UpdateMisc ()
void UpdateNextTimer ()
void UpdateTimeshiftData ()
void UpdateTimeshiftProgressData ()
void UpdateTimersToggle ()
bool GetListItemAndPlayerLabel (const CFileItem *item, const KODI::GUILIB::GUIINFO::CGUIInfo &info, std::string &strValue) const
bool GetPVRLabel (const CFileItem *item, const KODI::GUILIB::GUIINFO::CGUIInfo &info, std::string &strValue) const
bool GetRadioRDSLabel (const CFileItem *item, const KODI::GUILIB::GUIINFO::CGUIInfo &info, std::string &strValue) const
bool GetListItemAndPlayerInt (const CFileItem *item, const KODI::GUILIB::GUIINFO::CGUIInfo &info, int &iValue) const
bool GetPVRInt (const CFileItem *item, const KODI::GUILIB::GUIINFO::CGUIInfo &info, int &iValue) const
int GetTimeShiftSeekPercent () const
bool GetListItemAndPlayerBool (const CFileItem *item, const KODI::GUILIB::GUIINFO::CGUIInfo &info, bool &bValue) const
bool GetPVRBool (const CFileItem *item, const KODI::GUILIB::GUIINFO::CGUIInfo &info, bool &bValue) const
bool GetRadioRDSBool (const CFileItem *item, const KODI::GUILIB::GUIINFO::CGUIInfo &info, bool &bValue) const
void CharInfoBackendNumber (std::string &strValue) const
void CharInfoTotalDiskSpace (std::string &strValue) const
void CharInfoSignal (std::string &strValue) const
void CharInfoSNR (std::string &strValue) const
void CharInfoBER (std::string &strValue) const
void CharInfoUNC (std::string &strValue) const
void CharInfoFrontendName (std::string &strValue) const
void CharInfoFrontendStatus (std::string &strValue) const
void CharInfoClientName (std::string &strValue) const
void CharInfoInstanceName (std::string &strValue) const
void CharInfoBackendName (std::string &strValue) const
void CharInfoBackendVersion (std::string &strValue) const
void CharInfoBackendHost (std::string &strValue) const
void CharInfoBackendDiskspace (std::string &strValue) const
void CharInfoBackendProviders (std::string &strValue) const
void CharInfoBackendChannelGroups (std::string &strValue) const
void CharInfoBackendChannels (std::string &strValue) const
void CharInfoBackendTimers (std::string &strValue) const
void CharInfoBackendRecordings (std::string &strValue) const
void CharInfoBackendDeletedRecordings (std::string &strValue) const
void CharInfoPlayingClientName (std::string &strValue) const
void CharInfoEncryption (std::string &strValue) const
void CharInfoService (std::string &strValue) const
void CharInfoMux (std::string &strValue) const
void CharInfoProvider (std::string &strValue) const
Private Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Private Attributes
PVRGUIInfo data
CPVRGUIAnyTimerInfo m_anyTimersInfo
CPVRGUITVTimerInfo m_tvTimersInfo
CPVRGUIRadioTimerInfo m_radioTimersInfo
CPVRGUITimesInfo m_timesInfo
bool m_bHasTVRecordings
bool m_bHasRadioRecordings
unsigned int m_iCurrentActiveClient
std::string m_strPlayingClientName
std::string m_strClientName
std::string m_strInstanceName
std::string m_strBackendName
std::string m_strBackendVersion
std::string m_strBackendHost
std::string m_strBackendTimers
std::string m_strBackendRecordings
std::string m_strBackendDeletedRecordings
std::string m_strBackendProviders
std::string m_strBackendChannelGroups
std::string m_strBackendChannels
long long m_iBackendDiskTotal
long long m_iBackendDiskUsed
bool m_bIsPlayingTV
bool m_bIsPlayingRadio
bool m_bIsPlayingRecording
bool m_bIsPlayingEpgTag
bool m_bIsPlayingEncryptedStream
bool m_bHasTVChannels
bool m_bHasRadioChannels
bool m_bCanRecordPlayingChannel
bool m_bIsRecordingPlayingChannel
bool m_bIsPlayingActiveRecording
std::string m_strPlayingTVGroup
std::string m_strPlayingRadioGroup
CPVRSignalStatus m_qualityInfo
CPVRDescrambleInfo m_descrambleInfo
std::vector< SBackend > m_backendProperties
std::string m_channelNumberInput
bool m_previewAndPlayerShowInfo {false}
CCriticalSection m_critSection
std::atomic< bool > m_updateBackendCacheRequested
bool m_bRegistered
Private Attributes inherited from CThread
std::atomic< bool > m_bStop
Additional Inherited Members
Protected Attributes inherited from KODI::GUILIB::GUIINFO::CGUIInfoProvider
VideoStreamInfo m_videoInfo
AudioStreamInfo m_audioInfo
SubtitleStreamInfo m_subtitleInfo
Private Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Static Private Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Constructor & Destructor Documentation
CPVRGUIInfo()
CPVRGUIInfo::CPVRGUIInfo ()
References ResetProperties().
~CPVRGUIInfo()
PVR::CPVRGUIInfo::~CPVRGUIInfo () override default
Member Function Documentation
CharInfoBackendChannelGroups()
void CPVRGUIInfo::CharInfoBackendChannelGroups (std::string & strValue) const private
References m_strBackendChannelGroups, and m_updateBackendCacheRequested.
Referenced by GetPVRLabel().
CharInfoBackendChannels()
void CPVRGUIInfo::CharInfoBackendChannels (std::string & strValue) const private
References m_strBackendChannels, and m_updateBackendCacheRequested.
Referenced by GetPVRLabel().
CharInfoBackendDeletedRecordings()
void CPVRGUIInfo::CharInfoBackendDeletedRecordings (std::string & strValue) const private
References m_strBackendDeletedRecordings, and m_updateBackendCacheRequested.
Referenced by GetPVRLabel().
CharInfoBackendDiskspace()
void CPVRGUIInfo::CharInfoBackendDiskspace (std::string & strValue) const private
References g_localizeStrings, CLocalizeStrings::Get(), m_iBackendDiskTotal, m_iBackendDiskUsed, and m_updateBackendCacheRequested.
Referenced by GetPVRLabel().
CharInfoBackendHost()
void CPVRGUIInfo::CharInfoBackendHost (std::string & strValue) const private
References m_strBackendHost, and m_updateBackendCacheRequested.
Referenced by GetPVRLabel().
CharInfoBackendName()
void CPVRGUIInfo::CharInfoBackendName (std::string & strValue) const private
References m_strBackendName, and m_updateBackendCacheRequested.
Referenced by GetPVRLabel().
CharInfoBackendNumber()
void CPVRGUIInfo::CharInfoBackendNumber (std::string & strValue) const private
References g_localizeStrings, CLocalizeStrings::Get(), m_backendProperties, and m_iCurrentActiveClient.
Referenced by GetPVRLabel().
CharInfoBackendProviders()
void CPVRGUIInfo::CharInfoBackendProviders (std::string & strValue) const private
References m_strBackendProviders, and m_updateBackendCacheRequested.
Referenced by GetPVRLabel().
CharInfoBackendRecordings()
void CPVRGUIInfo::CharInfoBackendRecordings (std::string & strValue) const private
References m_strBackendRecordings, and m_updateBackendCacheRequested.
Referenced by GetPVRLabel().
CharInfoBackendTimers()
void CPVRGUIInfo::CharInfoBackendTimers (std::string & strValue) const private
References m_strBackendTimers, and m_updateBackendCacheRequested.
Referenced by GetPVRLabel().
CharInfoBackendVersion()
void CPVRGUIInfo::CharInfoBackendVersion (std::string & strValue) const private
References m_strBackendVersion, and m_updateBackendCacheRequested.
Referenced by GetPVRLabel().
CharInfoBER()
void CPVRGUIInfo::CharInfoBER (std::string & strValue) const private
References PVR::CPVRSignalStatus::BER(), and m_qualityInfo.
Referenced by GetPVRLabel().
CharInfoClientName()
void CPVRGUIInfo::CharInfoClientName (std::string & strValue) const private
References m_strClientName, and m_updateBackendCacheRequested.
Referenced by GetPVRLabel().
CharInfoEncryption()
void CPVRGUIInfo::CharInfoEncryption (std::string & strValue) const private
References PVR::CPVRDescrambleInfo::Caid(), PVR::CPVRChannel::GetEncryptionName(), CServiceBroker::GetPVRManager(), m_descrambleInfo, PVR::CPVRManager::PlaybackState(), and PVR_DESCRAMBLE_INFO_NOT_AVAILABLE.
Referenced by GetPVRLabel().
CharInfoFrontendName()
void CPVRGUIInfo::CharInfoFrontendName (std::string & strValue) const private
References PVR::CPVRSignalStatus::AdapterName(), g_localizeStrings, CLocalizeStrings::Get(), and m_qualityInfo.
Referenced by GetPVRLabel().
CharInfoFrontendStatus()
void CPVRGUIInfo::CharInfoFrontendStatus (std::string & strValue) const private
References PVR::CPVRSignalStatus::AdapterStatus(), g_localizeStrings, CLocalizeStrings::Get(), and m_qualityInfo.
Referenced by GetPVRLabel().
CharInfoInstanceName()
void CPVRGUIInfo::CharInfoInstanceName (std::string & strValue) const private
References m_strInstanceName, and m_updateBackendCacheRequested.
Referenced by GetPVRLabel().
CharInfoMux()
void CPVRGUIInfo::CharInfoMux (std::string & strValue) const private
References g_localizeStrings, CLocalizeStrings::Get(), m_qualityInfo, and PVR::CPVRSignalStatus::MuxName().
Referenced by GetPVRLabel().
CharInfoPlayingClientName()
void CPVRGUIInfo::CharInfoPlayingClientName (std::string & strValue) const private
References g_localizeStrings, CLocalizeStrings::Get(), and m_strPlayingClientName.
Referenced by GetPVRLabel().
CharInfoProvider()
void CPVRGUIInfo::CharInfoProvider (std::string & strValue) const private
References g_localizeStrings, CLocalizeStrings::Get(), m_qualityInfo, and PVR::CPVRSignalStatus::ProviderName().
Referenced by GetPVRLabel().
CharInfoService()
void CPVRGUIInfo::CharInfoService (std::string & strValue) const private
References g_localizeStrings, CLocalizeStrings::Get(), m_qualityInfo, and PVR::CPVRSignalStatus::ServiceName().
Referenced by GetPVRLabel().
CharInfoSignal()
void CPVRGUIInfo::CharInfoSignal (std::string & strValue) const private
References m_qualityInfo, and PVR::CPVRSignalStatus::Signal().
Referenced by GetPVRLabel().
CharInfoSNR()
void CPVRGUIInfo::CharInfoSNR (std::string & strValue) const private
References m_qualityInfo, and PVR::CPVRSignalStatus::SNR().
Referenced by GetPVRLabel().
CharInfoTotalDiskSpace()
void CPVRGUIInfo::CharInfoTotalDiskSpace (std::string & strValue) const private
References m_iBackendDiskTotal.
Referenced by GetPVRLabel().
CharInfoUNC()
void CPVRGUIInfo::CharInfoUNC (std::string & strValue) const private
References m_qualityInfo, and PVR::CPVRSignalStatus::UNC().
Referenced by GetPVRLabel().
ClearDescrambleInfo()
void CPVRGUIInfo::ClearDescrambleInfo (CPVRDescrambleInfo & descrambleInfo) private
Referenced by ResetProperties(), and UpdateDescrambleData().
ClearQualityInfo()
void CPVRGUIInfo::ClearQualityInfo (CPVRSignalStatus & qualityInfo) private
References g_localizeStrings, and CLocalizeStrings::Get().
Referenced by ResetProperties(), and UpdateQualityData().
GetBool()
bool CPVRGUIInfo::GetBool (bool & value, const CGUIListItem * item, int contextWindow, const KODI::GUILIB::GUIINFO::CGUIInfo & info) const override virtual
Get a GUIInfoManager bool value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References GetListItemAndPlayerBool(), GetPVRBool(), GetRadioRDSBool(), CGUIListItem::IsFileItem(), and value.
Referenced by UpdateQualityData().
GetFallbackLabel()
bool CPVRGUIInfo::GetFallbackLabel (std::string & value, const CFileItem * item, int contextWindow, const KODI::GUILIB::GUIINFO::CGUIInfo & info, std::string * fallback) override virtual
Get a GUIInfoManager label fallback string. Will be called if none of the registered provider's GetLabel() implementation has returned success.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
fallback A fallback value. Can be nullptr.
Returns
True if the value was filled successfully, false otherwise.
Reimplemented from KODI::GUILIB::GUIINFO::CGUIInfoProvider.
References PVR::CPVRManager::Get(), PVR::CPVRItem::GetEpgInfoTag(), CServiceBroker::GetPVRManager(), CFileItem::IsEPG(), CFileItem::IsPVRChannel(), CFileItem::IsPVRTimer(), MUSICPLAYER_TITLE, value, and VIDEOPLAYER_TITLE.
GetInt()
bool CPVRGUIInfo::GetInt (int & value, const CGUIListItem * item, int contextWindow, const KODI::GUILIB::GUIINFO::CGUIInfo & info) const override virtual
Get a GUIInfoManager integer value.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References GetListItemAndPlayerInt(), GetPVRInt(), CGUIListItem::IsFileItem(), and value.
GetLabel()
bool CPVRGUIInfo::GetLabel (std::string & value, const CFileItem * item, int contextWindow, const KODI::GUILIB::GUIINFO::CGUIInfo & info, std::string * fallback) const override virtual
Get a GUIInfoManager label string.
Parameters
value Will be filled with the requested value.
item The item to get the value for. Can be nullptr.
contextWindow The context window. Can be 0.
info The GUI info (label id + additional data).
fallback A fallback value. Can be nullptr.
Returns
True if the value was filled successfully, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References GetListItemAndPlayerLabel(), GetPVRLabel(), GetRadioRDSLabel(), and value.
GetListItemAndPlayerBool()
bool CPVRGUIInfo::GetListItemAndPlayerBool (const CFileItem * item, const KODI::GUILIB::GUIINFO::CGUIInfo & info, bool & bValue) const private
References PVR::CPVRManager::EpgContainer(), PVR::CPVRItem::GetChannel(), CFileItem::GetEPGInfoTag(), PVR::CPVRItem::GetEpgInfoTag(), CFileItem::GetPVRChannelInfoTag(), CServiceBroker::GetPVRManager(), CFileItem::GetPVRRecordingInfoTag(), CFileItem::GetPVRTimerInfoTag(), PVR::CPVREpgContainer::GetTagById(), PVR::CPVRItem::GetTimerInfoTag(), CFileItem::IsEPG(), CFileItem::IsPVRChannel(), CFileItem::IsPVRRecording(), CFileItem::IsPVRTimer(), LISTITEM_HAS_EPG, LISTITEM_HASARCHIVE, LISTITEM_HASRECORDING, LISTITEM_HASREMINDER, LISTITEM_HASREMINDERRULE, LISTITEM_HASTIMER, LISTITEM_HASTIMERSCHEDULE, LISTITEM_INPROGRESS, LISTITEM_IS_FINALE, LISTITEM_IS_LIVE, LISTITEM_IS_NEW, LISTITEM_IS_PREMIERE, LISTITEM_ISENCRYPTED, LISTITEM_ISPLAYABLE, LISTITEM_ISPLAYING, LISTITEM_ISRECORDING, LISTITEM_TIMERHASCONFLICT, LISTITEM_TIMERHASERROR, LISTITEM_TIMERISACTIVE, KODI::GUILIB::GUIINFO::CGUIInfoProvider::m_audioInfo, m_previewAndPlayerShowInfo, KODI::GUILIB::GUIINFO::CGUIInfoProvider::m_videoInfo, MUSICPLAYER_CONTENT, PVR::CPVRManager::PlaybackState(), PLAYER_IS_CHANNEL_PREVIEW_ACTIVE, PVR::CPVRManager::Recordings(), PVR::CPVRManager::Timers(), StreamInfo::valid, VIDEOPLAYER_CAN_RESUME_LIVE_TV, VIDEOPLAYER_CONTENT, VIDEOPLAYER_HAS_EPG, and VIDEOPLAYER_HAS_INFO.
Referenced by GetBool().
GetListItemAndPlayerInt()
bool CPVRGUIInfo::GetListItemAndPlayerInt (const CFileItem * item, const KODI::GUILIB::GUIINFO::CGUIInfo & info, int & iValue) const private
References PVR::CPVRItem::GetEpgInfoTag(), CFileItem::IsEPG(), CFileItem::IsPVRChannel(), and LISTITEM_PROGRESS.
Referenced by GetInt().
GetListItemAndPlayerLabel()
bool CPVRGUIInfo::GetListItemAndPlayerLabel (const CFileItem * item, const KODI::GUILIB::GUIINFO::CGUIInfo & info, std::string & strValue) const private
References PVR::CPVRManager::ChannelGroups(), PVR::CPVRChannelGroup::CLIENT, g_localizeStrings, PVR::CPVRManager::Get(), CLocalizeStrings::Get(), PVR::CPVRItem::GetChannel(), PVR::CPVRManager::GetClient(), PVR::CPVRItem::GetEpgInfoTag(), CFileItem::GetEPGSearchFilter(), CServiceBroker::GetGUI(), PVR::CPVRItem::GetNextEpgInfoTag(), CFileItem::GetPath(), CFileItem::GetPVRChannelGroupMemberInfoTag(), CServiceBroker::GetPVRManager(), CFileItem::GetPVRRecordingInfoTag(), CFileItem::GetPVRTimerInfoTag(), CFileItem::IsEPG(), CFileItem::IsPVRChannel(), CFileItem::IsPVRChannelGroup(), CFileItem::IsPVRTimer(), LISTITEM_CAST, LISTITEM_CHANNEL_LOGO, LISTITEM_CHANNEL_NAME, LISTITEM_CHANNEL_NUMBER, LISTITEM_COMMENT, LISTITEM_DATE, LISTITEM_DATE_ADDED, LISTITEM_DIRECTOR, LISTITEM_DURATION, LISTITEM_ENDDATE, LISTITEM_ENDTIME, LISTITEM_EPG_EVENT_ICON, LISTITEM_EPG_EVENT_TITLE, LISTITEM_EPISODE, LISTITEM_EPISODENAME, LISTITEM_EPISODEPART, LISTITEM_EXPIRATION_DATE, LISTITEM_EXPIRATION_TIME, LISTITEM_GENRE, LISTITEM_ICON, LISTITEM_IMDBNUMBER, LISTITEM_MEDIAPROVIDERS, LISTITEM_NEXT_DURATION, LISTITEM_NEXT_ENDDATE, LISTITEM_NEXT_ENDTIME, LISTITEM_NEXT_GENRE, LISTITEM_NEXT_PLOT, LISTITEM_NEXT_PLOT_OUTLINE, LISTITEM_NEXT_STARTDATE, LISTITEM_NEXT_STARTTIME, LISTITEM_NEXT_TITLE, LISTITEM_ORIGINALTITLE, LISTITEM_PARENTAL_RATING, LISTITEM_PARENTAL_RATING_CODE, LISTITEM_PARENTAL_RATING_ICON, LISTITEM_PARENTAL_RATING_SOURCE, LISTITEM_PLOT, LISTITEM_PLOT_OUTLINE, LISTITEM_PREMIERED, LISTITEM_PVR_CLIENT_NAME, LISTITEM_PVR_GROUP_ORIGIN, LISTITEM_PVR_INSTANCE_NAME, LISTITEM_RATING, LISTITEM_SEASON, LISTITEM_SIZE, LISTITEM_STARTDATE, LISTITEM_STARTTIME, LISTITEM_TIMERTYPE, LISTITEM_TITLE, LISTITEM_TITLE_EXTRAINFO, LISTITEM_WRITER, LISTITEM_YEAR, m_critSection, m_strPlayingRadioGroup, m_strPlayingTVGroup, MUSICPLAYER_CHANNEL_GROUP, MUSICPLAYER_CHANNEL_LOGO, MUSICPLAYER_CHANNEL_NAME, MUSICPLAYER_CHANNEL_NUMBER, MUSICPLAYER_MEDIAPROVIDERS, PLAYER_TITLE, PVR::CPVRManager::Providers(), CDateTime::SetFromUTCDateTime(), PVR::CPVRChannelGroup::SYSTEM, PVR::CPVRChannelGroup::USER, VIDEOPLAYER_CAST, VIDEOPLAYER_CHANNEL_GROUP, VIDEOPLAYER_CHANNEL_LOGO, VIDEOPLAYER_CHANNEL_NAME, VIDEOPLAYER_CHANNEL_NUMBER, VIDEOPLAYER_DIRECTOR, VIDEOPLAYER_ENDTIME, VIDEOPLAYER_EPISODE, VIDEOPLAYER_EPISODENAME, VIDEOPLAYER_EPISODEPART, VIDEOPLAYER_GENRE, VIDEOPLAYER_IMDBNUMBER, VIDEOPLAYER_MEDIAPROVIDERS, VIDEOPLAYER_NEXT_DURATION, VIDEOPLAYER_NEXT_ENDTIME, VIDEOPLAYER_NEXT_GENRE, VIDEOPLAYER_NEXT_PLOT, VIDEOPLAYER_NEXT_PLOT_OUTLINE, VIDEOPLAYER_NEXT_STARTTIME, VIDEOPLAYER_NEXT_TITLE, VIDEOPLAYER_ORIGINALTITLE, VIDEOPLAYER_PARENTAL_RATING, VIDEOPLAYER_PARENTAL_RATING_CODE, VIDEOPLAYER_PARENTAL_RATING_ICON, VIDEOPLAYER_PARENTAL_RATING_SOURCE, VIDEOPLAYER_PLOT, VIDEOPLAYER_PLOT_OUTLINE, VIDEOPLAYER_PREMIERED, VIDEOPLAYER_RATING, VIDEOPLAYER_SEASON, VIDEOPLAYER_STARTTIME, VIDEOPLAYER_TITLE_EXTRAINFO, VIDEOPLAYER_WRITER, VIDEOPLAYER_YEAR, and WINDOW_RADIO_TIMER_RULES.
Referenced by GetLabel().
GetPVRBool()
bool CPVRGUIInfo::GetPVRBool (const CFileItem * item, const KODI::GUILIB::GUIINFO::CGUIInfo & info, bool & bValue) const private
References PVR::CPVRGUITimerInfo::HasNonRecordingTimers(), PVR::CPVRGUITimerInfo::HasRecordingTimers(), PVR::CPVRGUITimerInfo::HasTimers(), PVR::CPVRGUITimesInfo::IsTimeshifting(), m_anyTimersInfo, m_bCanRecordPlayingChannel, m_bHasRadioChannels, m_bHasTVChannels, m_bIsPlayingActiveRecording, m_bIsPlayingEncryptedStream, m_bIsPlayingEpgTag, m_bIsPlayingRadio, m_bIsPlayingRecording, m_bIsPlayingTV, m_bIsRecordingPlayingChannel, m_critSection, m_radioTimersInfo, m_timesInfo, m_tvTimersInfo, PVR_ACTUAL_STREAM_ENCRYPTED, PVR_CAN_RECORD_PLAYING_CHANNEL, PVR_HAS_NONRECORDING_RADIO_TIMER, PVR_HAS_NONRECORDING_TIMER, PVR_HAS_NONRECORDING_TV_TIMER, PVR_HAS_RADIO_CHANNELS, PVR_HAS_RADIO_TIMER, PVR_HAS_TIMER, PVR_HAS_TV_CHANNELS, PVR_HAS_TV_TIMER, PVR_IS_PLAYING_ACTIVE_RECORDING, PVR_IS_PLAYING_EPGTAG, PVR_IS_PLAYING_RADIO, PVR_IS_PLAYING_RECORDING, PVR_IS_PLAYING_TV, PVR_IS_RECORDING, PVR_IS_RECORDING_PLAYING_CHANNEL, PVR_IS_RECORDING_RADIO, PVR_IS_RECORDING_TV, and PVR_IS_TIMESHIFTING.
Referenced by GetBool().
GetPVRInt()
bool CPVRGUIInfo::GetPVRInt (const CFileItem * item, const KODI::GUILIB::GUIINFO::CGUIInfo & info, int & iValue) const private
References PVR::CPVRManager::Clients(), PVR::CPVRGUITimesInfo::GetEpgEventDuration(), PVR::CPVRGUITimesInfo::GetEpgEventProgress(), PVR::CPVRItem::GetEpgInfoTag(), CServiceBroker::GetPVRManager(), PVR::CPVRGUITimesInfo::GetTimeshiftProgress(), PVR::CPVRGUITimesInfo::GetTimeshiftProgressBufferEnd(), PVR::CPVRGUITimesInfo::GetTimeshiftProgressBufferStart(), PVR::CPVRGUITimesInfo::GetTimeshiftProgressDuration(), PVR::CPVRGUITimesInfo::GetTimeshiftProgressEpgEnd(), PVR::CPVRGUITimesInfo::GetTimeshiftProgressEpgStart(), PVR::CPVRGUITimesInfo::GetTimeshiftProgressPlayPosition(), GetTimeShiftSeekPercent(), CFileItem::IsEPG(), CFileItem::IsPVRChannel(), m_critSection, m_iBackendDiskTotal, m_iBackendDiskUsed, m_qualityInfo, m_timesInfo, PVR_ACTUAL_STREAM_SIG_PROGR, PVR_ACTUAL_STREAM_SNR_PROGR, PVR_BACKEND_DISKSPACE_PROGR, PVR_CLIENT_COUNT, PVR_EPG_EVENT_DURATION, PVR_EPG_EVENT_PROGRESS, PVR_TIMESHIFT_PROGRESS, PVR_TIMESHIFT_PROGRESS_BUFFER_END, PVR_TIMESHIFT_PROGRESS_BUFFER_START, PVR_TIMESHIFT_PROGRESS_DURATION, PVR_TIMESHIFT_PROGRESS_EPG_END, PVR_TIMESHIFT_PROGRESS_EPG_START, PVR_TIMESHIFT_PROGRESS_PLAY_POS, PVR_TIMESHIFT_SEEKBAR, PVR::CPVRSignalStatus::Signal(), and PVR::CPVRSignalStatus::SNR().
Referenced by GetInt().
GetPVRLabel()
bool CPVRGUIInfo::GetPVRLabel (const CFileItem * item, const KODI::GUILIB::GUIINFO::CGUIInfo & info, std::string & strValue) const private
References CharInfoBackendChannelGroups(), CharInfoBackendChannels(), CharInfoBackendDeletedRecordings(), CharInfoBackendDiskspace(), CharInfoBackendHost(), CharInfoBackendName(), CharInfoBackendNumber(), CharInfoBackendProviders(), CharInfoBackendRecordings(), CharInfoBackendTimers(), CharInfoBackendVersion(), CharInfoBER(), CharInfoClientName(), CharInfoEncryption(), CharInfoFrontendName(), CharInfoFrontendStatus(), CharInfoInstanceName(), CharInfoMux(), CharInfoPlayingClientName(), CharInfoProvider(), CharInfoService(), CharInfoSignal(), CharInfoSNR(), CharInfoTotalDiskSpace(), CharInfoUNC(), PVR::CPVRGUITimerInfo::GetActiveTimerChannelIcon(), PVR::CPVRGUITimerInfo::GetActiveTimerChannelName(), PVR::CPVRGUITimerInfo::GetActiveTimerDateTime(), PVR::CPVRGUITimerInfo::GetActiveTimerTitle(), CServiceBroker::GetAppComponents(), PVR::CPVRGUITimesInfo::GetEpgEventDuration(), PVR::CPVRGUITimesInfo::GetEpgEventElapsedTime(), PVR::CPVRGUITimesInfo::GetEpgEventFinishTime(), PVR::CPVRGUITimesInfo::GetEpgEventRemainingTime(), PVR::CPVRGUITimesInfo::GetEpgEventSeekTime(), PVR::CPVRItem::GetEpgInfoTag(), PVR::CPVRGUITimerInfo::GetNextTimer(), PVR::CPVRGUITimerInfo::GetNextTimerChannelIcon(), PVR::CPVRGUITimerInfo::GetNextTimerChannelName(), PVR::CPVRGUITimerInfo::GetNextTimerDateTime(), PVR::CPVRGUITimerInfo::GetNextTimerTitle(), PVR::CPVRGUITimesInfo::GetTimeshiftEndTime(), PVR::CPVRGUITimesInfo::GetTimeshiftOffset(), PVR::CPVRGUITimesInfo::GetTimeshiftPlayTime(), PVR::CPVRGUITimesInfo::GetTimeshiftProgressDuration(), PVR::CPVRGUITimesInfo::GetTimeshiftProgressEndTime(), PVR::CPVRGUITimesInfo::GetTimeshiftProgressStartTime(), PVR::CPVRGUITimesInfo::GetTimeshiftStartTime(), CFileItem::IsEPG(), CFileItem::IsPVRChannel(), m_anyTimersInfo, m_channelNumberInput, m_critSection, m_radioTimersInfo, m_timesInfo, m_tvTimersInfo, PVR_ACTUAL_STREAM_BER, PVR_ACTUAL_STREAM_CLIENT, PVR_ACTUAL_STREAM_CRYPTION, PVR_ACTUAL_STREAM_DEVICE, PVR_ACTUAL_STREAM_MUX, PVR_ACTUAL_STREAM_PROVIDER, PVR_ACTUAL_STREAM_SERVICE, PVR_ACTUAL_STREAM_SIG, PVR_ACTUAL_STREAM_SNR, PVR_ACTUAL_STREAM_STATUS, PVR_ACTUAL_STREAM_UNC, PVR_BACKEND_CHANNEL_GROUPS, PVR_BACKEND_CHANNELS, PVR_BACKEND_DELETED_RECORDINGS, PVR_BACKEND_DISKSPACE, PVR_BACKEND_HOST, PVR_BACKEND_NAME, PVR_BACKEND_NUMBER, PVR_BACKEND_PROVIDERS, PVR_BACKEND_RECORDINGS, PVR_BACKEND_TIMERS, PVR_BACKEND_VERSION, PVR_CHANNEL_NUMBER_INPUT, PVR_CLIENT_NAME, PVR_EPG_EVENT_DURATION, PVR_EPG_EVENT_ELAPSED_TIME, PVR_EPG_EVENT_FINISH_TIME, PVR_EPG_EVENT_ICON, PVR_EPG_EVENT_REMAINING_TIME, PVR_EPG_EVENT_SEEK_TIME, PVR_INSTANCE_NAME, PVR_NEXT_RECORDING_CHAN_ICO, PVR_NEXT_RECORDING_CHANNEL, PVR_NEXT_RECORDING_DATETIME, PVR_NEXT_RECORDING_TITLE, PVR_NEXT_TIMER, PVR_NOW_RECORDING_CHAN_ICO, PVR_NOW_RECORDING_CHANNEL, PVR_NOW_RECORDING_DATETIME, PVR_NOW_RECORDING_TITLE, PVR_RADIO_NEXT_RECORDING_CHAN_ICO, PVR_RADIO_NEXT_RECORDING_CHANNEL, PVR_RADIO_NEXT_RECORDING_DATETIME, PVR_RADIO_NEXT_RECORDING_TITLE, PVR_RADIO_NOW_RECORDING_CHAN_ICO, PVR_RADIO_NOW_RECORDING_CHANNEL, PVR_RADIO_NOW_RECORDING_DATETIME, PVR_RADIO_NOW_RECORDING_TITLE, PVR_TIMESHIFT_END_TIME, PVR_TIMESHIFT_OFFSET, PVR_TIMESHIFT_PLAY_TIME, PVR_TIMESHIFT_PROGRESS_DURATION, PVR_TIMESHIFT_PROGRESS_END_TIME, PVR_TIMESHIFT_PROGRESS_START_TIME, PVR_TIMESHIFT_START_TIME, PVR_TOTAL_DISKSPACE, PVR_TV_NEXT_RECORDING_CHAN_ICO, PVR_TV_NEXT_RECORDING_CHANNEL, PVR_TV_NEXT_RECORDING_DATETIME, PVR_TV_NEXT_RECORDING_TITLE, PVR_TV_NOW_RECORDING_CHAN_ICO, PVR_TV_NOW_RECORDING_CHANNEL, PVR_TV_NOW_RECORDING_DATETIME, and PVR_TV_NOW_RECORDING_TITLE.
Referenced by GetLabel().
GetRadioRDSBool()
bool CPVRGUIInfo::GetRadioRDSBool (const CFileItem * item, const KODI::GUILIB::GUIINFO::CGUIInfo & info, bool & bValue) const private
References CServiceBroker::GetAppComponents(), CFileItem::GetPVRChannelInfoTag(), CFileItem::HasPVRChannelInfoTag(), CApplicationPlayer::IsPlayingRDS(), RDS_HAS_HOTLINE_DATA, RDS_HAS_RADIOTEXT, RDS_HAS_RADIOTEXT_PLUS, RDS_HAS_RDS, and RDS_HAS_STUDIO_DATA.
Referenced by GetBool().
GetRadioRDSLabel()
bool CPVRGUIInfo::GetRadioRDSLabel (const CFileItem * item, const KODI::GUILIB::GUIINFO::CGUIInfo & info, std::string & strValue) const private
References CFileItem::GetPVRChannelInfoTag(), CFileItem::HasPVRChannelInfoTag(), RDS_ALBUM, RDS_ALBUM_TRACKNUMBER, RDS_ARTIST, RDS_AUDIO_LANG, RDS_BAND, RDS_CHANNEL_COUNTRY, RDS_COMMENT, RDS_COMPOSER, RDS_CONDUCTOR, RDS_EMAIL_HOTLINE, RDS_EMAIL_STUDIO, RDS_GET_RADIO_STYLE, RDS_GET_RADIOTEXT_LINE, RDS_INFO_CINEMA, RDS_INFO_CINEMA_SIZE, RDS_INFO_HOROSCOPE, RDS_INFO_HOROSCOPE_SIZE, RDS_INFO_LOTTERY, RDS_INFO_LOTTERY_SIZE, RDS_INFO_NEWS, RDS_INFO_NEWS_LOCAL, RDS_INFO_OTHER, RDS_INFO_OTHER_SIZE, RDS_INFO_SPORT, RDS_INFO_SPORT_SIZE, RDS_INFO_STOCK, RDS_INFO_STOCK_SIZE, RDS_INFO_WEATHER, RDS_INFO_WEATHER_SIZE, RDS_PHONE_HOTLINE, RDS_PHONE_STUDIO, RDS_PROG_EDIT_STAFF, RDS_PROG_HOMEPAGE, RDS_PROG_HOST, RDS_PROG_NEXT, RDS_PROG_NOW, RDS_PROG_STATION, RDS_PROG_STYLE, RDS_SMS_STUDIO, and RDS_TITLE.
Referenced by GetLabel().
GetTimeShiftSeekPercent()
int CPVRGUIInfo::GetTimeShiftSeekPercent () const private
References CServiceBroker::GetAppComponents(), CApplicationPlayer::GetSeekHandler(), CSeekHandler::GetSeekSize(), PVR::CPVRGUITimesInfo::GetTimeshiftProgressDuration(), PVR::CPVRGUITimesInfo::GetTimeshiftProgressPlayPosition(), and m_timesInfo.
Referenced by GetPVRInt().
InitCurrentItem()
bool CPVRGUIInfo::InitCurrentItem (CFileItem * item) override virtual
Init a new current guiinfo manager item. Gets called whenever the active guiinfo manager item changes.
Parameters
item The new item.
Returns
True if the item was inited by the provider, false otherwise.
Implements KODI::GUILIB::GUIINFO::IGUIInfoProvider.
References PVR::CurrentItem, CServiceBroker::GetPVRManager(), and PVR::CPVRManager::PublishEvent().
Notify() [1/3]
void CPVRGUIInfo::Notify (const PVRChannelNumberInputChangedEvent & event)
CEventStream callback for channel number input changes.
Parameters
event The event.
References m_channelNumberInput, and m_critSection.
Notify() [2/3]
void CPVRGUIInfo::Notify (const PVREvent & event)
CEventStream callback for PVR events.
Parameters
event The event.
References PVR::Timers, PVR::TimersInvalidated, and UpdateTimersCache().
Referenced by Process().
Notify() [3/3]
void CPVRGUIInfo::Notify (const PVRPreviewAndPlayerShowInfoChangedEvent & event)
CEventStream callback for channel preview and player show info changes.
Parameters
event The event.
References m_critSection, and m_previewAndPlayerShowInfo.
Process()
void CPVRGUIInfo::Process (void) override private virtual
Reimplemented from CThread.
References PVR::CPVRGUIActionsChannels::Events(), g_application, CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CServiceBroker::GetPVRManager(), CServiceBroker::GetSettingsComponent(), m_bRegistered, CThread::m_bStop, m_updateBackendCacheRequested, Notify(), CGUIInfoManager::RegisterInfoProvider(), CThread::Sleep(), UpdateBackendCache(), UpdateDescrambleData(), UpdateMisc(), UpdateNextTimer(), UpdateQualityData(), UpdateTimersCache(), UpdateTimersToggle(), and UpdateTimeshiftData().
ResetProperties()
void CPVRGUIInfo::ResetProperties () private
References ClearDescrambleInfo(), ClearQualityInfo(), m_anyTimersInfo, m_bCanRecordPlayingChannel, m_bHasRadioChannels, m_bHasRadioRecordings, m_bHasTVChannels, m_bHasTVRecordings, m_bIsPlayingActiveRecording, m_bIsPlayingEncryptedStream, m_bIsPlayingEpgTag, m_bIsPlayingRadio, m_bIsPlayingRecording, m_bIsPlayingTV, m_bIsRecordingPlayingChannel, m_bRegistered, m_critSection, m_descrambleInfo, m_iBackendDiskTotal, m_iBackendDiskUsed, m_iCurrentActiveClient, m_qualityInfo, m_radioTimersInfo, m_strBackendChannelGroups, m_strBackendChannels, m_strBackendDeletedRecordings, m_strBackendHost, m_strBackendName, m_strBackendProviders, m_strBackendRecordings, m_strBackendTimers, m_strBackendVersion, m_strClientName, m_strInstanceName, m_strPlayingClientName, m_timesInfo, m_tvTimersInfo, m_updateBackendCacheRequested, PVR::CPVRGUITimesInfo::Reset(), and PVR::CPVRGUITimerInfo::ResetProperties().
Referenced by CPVRGUIInfo(), and Start().
Start()
void CPVRGUIInfo::Start ()
References BELOW_NORMAL, CThread::Create(), ResetProperties(), and CThread::SetPriority().
Stop()
void CPVRGUIInfo::Stop ()
References PVR::CPVRGUIActionsChannels::GetChannelNavigator(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CServiceBroker::GetPVRManager(), m_bRegistered, CThread::StopThread(), CGUIInfoManager::UnregisterInfoProvider(), and PVR::CPVRGUIChannelNavigator::Unsubscribe().
UpdateBackendCache()
void CPVRGUIInfo::UpdateBackendCache () private
References PVR::CPVRManager::Clients(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetPVRManager(), m_backendProperties, m_critSection, m_iBackendDiskTotal, m_iBackendDiskUsed, m_iCurrentActiveClient, m_strBackendChannelGroups, m_strBackendChannels, m_strBackendDeletedRecordings, m_strBackendHost, m_strBackendName, m_strBackendProviders, m_strBackendRecordings, m_strBackendTimers, m_strBackendVersion, m_strClientName, m_strInstanceName, and m_updateBackendCacheRequested.
Referenced by Process().
UpdateDescrambleData()
void CPVRGUIInfo::UpdateDescrambleData () private
References ClearDescrambleInfo(), PVR::CPVRManager::Clients(), CServiceBroker::GetPVRManager(), m_critSection, m_descrambleInfo, and PVR::CPVRManager::PlaybackState().
Referenced by Process().
UpdateMisc()
void CPVRGUIInfo::UpdateMisc () private
References PVR::CPVRManager::ChannelGroups(), CServiceBroker::GetPVRManager(), PVR::CPVRManager::IsStarted(), m_bCanRecordPlayingChannel, m_bHasRadioChannels, m_bHasRadioRecordings, m_bHasTVChannels, m_bHasTVRecordings, m_bIsPlayingActiveRecording, m_bIsPlayingEncryptedStream, m_bIsPlayingEpgTag, m_bIsPlayingRadio, m_bIsPlayingRecording, m_bIsPlayingTV, m_bIsRecordingPlayingChannel, m_critSection, m_strPlayingClientName, m_strPlayingRadioGroup, m_strPlayingTVGroup, PVR::CPVRManager::PlaybackState(), and PVR::CPVRManager::Recordings().
Referenced by Process().
UpdateNextTimer()
void CPVRGUIInfo::UpdateNextTimer () private
References m_anyTimersInfo, m_radioTimersInfo, m_tvTimersInfo, and PVR::CPVRGUITimerInfo::UpdateNextTimer().
Referenced by Process().
UpdateQualityData()
void CPVRGUIInfo::UpdateQualityData () private
References ClearQualityInfo(), PVR::CPVRManager::Clients(), GetBool(), CServiceBroker::GetPVRManager(), CServiceBroker::GetSettingsComponent(), m_critSection, m_qualityInfo, PVR::CPVRManager::PlaybackState(), and CSettings::SETTING_PVRPLAYBACK_SIGNALQUALITY.
Referenced by Process().
UpdateTimersCache()
void CPVRGUIInfo::UpdateTimersCache () private
References m_anyTimersInfo, m_radioTimersInfo, m_tvTimersInfo, and PVR::CPVRGUITimerInfo::UpdateTimersCache().
Referenced by Notify(), and Process().
UpdateTimersToggle()
void CPVRGUIInfo::UpdateTimersToggle () private
References m_anyTimersInfo, m_radioTimersInfo, m_tvTimersInfo, and PVR::CPVRGUITimerInfo::UpdateTimersToggle().
Referenced by Process().
UpdateTimeshiftData()
void CPVRGUIInfo::UpdateTimeshiftData () private
References m_timesInfo, and PVR::CPVRGUITimesInfo::Update().
Referenced by Process().
UpdateTimeshiftProgressData()
void PVR::CPVRGUIInfo::UpdateTimeshiftProgressData () private
Member Data Documentation
m_anyTimersInfo
CPVRGUIAnyTimerInfo PVR::CPVRGUIInfo::m_anyTimersInfo private
Referenced by GetPVRBool(), GetPVRLabel(), ResetProperties(), UpdateNextTimer(), UpdateTimersCache(), and UpdateTimersToggle().
m_backendProperties
std::vector<SBackend> PVR::CPVRGUIInfo::m_backendProperties private
Referenced by CharInfoBackendNumber(), and UpdateBackendCache().
m_bCanRecordPlayingChannel
bool PVR::CPVRGUIInfo::m_bCanRecordPlayingChannel private
Referenced by GetPVRBool(), ResetProperties(), and UpdateMisc().
m_bHasRadioChannels
bool PVR::CPVRGUIInfo::m_bHasRadioChannels private
Referenced by GetPVRBool(), ResetProperties(), and UpdateMisc().
m_bHasRadioRecordings
bool PVR::CPVRGUIInfo::m_bHasRadioRecordings private
Referenced by ResetProperties(), and UpdateMisc().
m_bHasTVChannels
bool PVR::CPVRGUIInfo::m_bHasTVChannels private
Referenced by GetPVRBool(), ResetProperties(), and UpdateMisc().
m_bHasTVRecordings
bool PVR::CPVRGUIInfo::m_bHasTVRecordings private
Referenced by ResetProperties(), and UpdateMisc().
m_bIsPlayingActiveRecording
bool PVR::CPVRGUIInfo::m_bIsPlayingActiveRecording private
Referenced by GetPVRBool(), ResetProperties(), and UpdateMisc().
m_bIsPlayingEncryptedStream
bool PVR::CPVRGUIInfo::m_bIsPlayingEncryptedStream private
Referenced by GetPVRBool(), ResetProperties(), and UpdateMisc().
m_bIsPlayingEpgTag
bool PVR::CPVRGUIInfo::m_bIsPlayingEpgTag private
Referenced by GetPVRBool(), ResetProperties(), and UpdateMisc().
m_bIsPlayingRadio
bool PVR::CPVRGUIInfo::m_bIsPlayingRadio private
Referenced by GetPVRBool(), ResetProperties(), and UpdateMisc().
m_bIsPlayingRecording
bool PVR::CPVRGUIInfo::m_bIsPlayingRecording private
Referenced by GetPVRBool(), ResetProperties(), and UpdateMisc().
m_bIsPlayingTV
bool PVR::CPVRGUIInfo::m_bIsPlayingTV private
Referenced by GetPVRBool(), ResetProperties(), and UpdateMisc().
m_bIsRecordingPlayingChannel
bool PVR::CPVRGUIInfo::m_bIsRecordingPlayingChannel private
Referenced by GetPVRBool(), ResetProperties(), and UpdateMisc().
m_bRegistered
bool PVR::CPVRGUIInfo::m_bRegistered private
Referenced by Process(), ResetProperties(), and Stop().
m_channelNumberInput
std::string PVR::CPVRGUIInfo::m_channelNumberInput private
Referenced by GetPVRLabel(), and Notify().
m_critSection
CCriticalSection PVR::CPVRGUIInfo::m_critSection mutable private
Referenced by GetListItemAndPlayerLabel(), GetPVRBool(), GetPVRInt(), GetPVRLabel(), Notify(), Notify(), ResetProperties(), UpdateBackendCache(), UpdateDescrambleData(), UpdateMisc(), and UpdateQualityData().
m_descrambleInfo
CPVRDescrambleInfo PVR::CPVRGUIInfo::m_descrambleInfo private
stream descramble information
Referenced by CharInfoEncryption(), ResetProperties(), and UpdateDescrambleData().
m_iBackendDiskTotal
long long PVR::CPVRGUIInfo::m_iBackendDiskTotal private
Referenced by CharInfoBackendDiskspace(), CharInfoTotalDiskSpace(), GetPVRInt(), ResetProperties(), and UpdateBackendCache().
m_iBackendDiskUsed
long long PVR::CPVRGUIInfo::m_iBackendDiskUsed private
Referenced by CharInfoBackendDiskspace(), GetPVRInt(), ResetProperties(), and UpdateBackendCache().
m_iCurrentActiveClient
unsigned int PVR::CPVRGUIInfo::m_iCurrentActiveClient private
Referenced by CharInfoBackendNumber(), ResetProperties(), and UpdateBackendCache().
m_previewAndPlayerShowInfo
bool PVR::CPVRGUIInfo::m_previewAndPlayerShowInfo {false} private
Referenced by GetListItemAndPlayerBool(), and Notify().
m_qualityInfo
CPVRSignalStatus PVR::CPVRGUIInfo::m_qualityInfo private
stream quality information
Referenced by CharInfoBER(), CharInfoFrontendName(), CharInfoFrontendStatus(), CharInfoMux(), CharInfoProvider(), CharInfoService(), CharInfoSignal(), CharInfoSNR(), CharInfoUNC(), GetPVRInt(), ResetProperties(), and UpdateQualityData().
m_radioTimersInfo
CPVRGUIRadioTimerInfo PVR::CPVRGUIInfo::m_radioTimersInfo private
Referenced by GetPVRBool(), GetPVRLabel(), ResetProperties(), UpdateNextTimer(), UpdateTimersCache(), and UpdateTimersToggle().
m_strBackendChannelGroups
std::string PVR::CPVRGUIInfo::m_strBackendChannelGroups private
Referenced by CharInfoBackendChannelGroups(), ResetProperties(), and UpdateBackendCache().
m_strBackendChannels
std::string PVR::CPVRGUIInfo::m_strBackendChannels private
Referenced by CharInfoBackendChannels(), ResetProperties(), and UpdateBackendCache().
m_strBackendDeletedRecordings
std::string PVR::CPVRGUIInfo::m_strBackendDeletedRecordings private
Referenced by CharInfoBackendDeletedRecordings(), ResetProperties(), and UpdateBackendCache().
m_strBackendHost
std::string PVR::CPVRGUIInfo::m_strBackendHost private
Referenced by CharInfoBackendHost(), ResetProperties(), and UpdateBackendCache().
m_strBackendName
std::string PVR::CPVRGUIInfo::m_strBackendName private
Referenced by CharInfoBackendName(), ResetProperties(), and UpdateBackendCache().
m_strBackendProviders
std::string PVR::CPVRGUIInfo::m_strBackendProviders private
Referenced by CharInfoBackendProviders(), ResetProperties(), and UpdateBackendCache().
m_strBackendRecordings
std::string PVR::CPVRGUIInfo::m_strBackendRecordings private
Referenced by CharInfoBackendRecordings(), ResetProperties(), and UpdateBackendCache().
m_strBackendTimers
std::string PVR::CPVRGUIInfo::m_strBackendTimers private
Referenced by CharInfoBackendTimers(), ResetProperties(), and UpdateBackendCache().
m_strBackendVersion
std::string PVR::CPVRGUIInfo::m_strBackendVersion private
Referenced by CharInfoBackendVersion(), ResetProperties(), and UpdateBackendCache().
m_strClientName
std::string PVR::CPVRGUIInfo::m_strClientName private
Referenced by CharInfoClientName(), ResetProperties(), and UpdateBackendCache().
m_strInstanceName
std::string PVR::CPVRGUIInfo::m_strInstanceName private
Referenced by CharInfoInstanceName(), ResetProperties(), and UpdateBackendCache().
m_strPlayingClientName
std::string PVR::CPVRGUIInfo::m_strPlayingClientName private
Referenced by CharInfoPlayingClientName(), ResetProperties(), and UpdateMisc().
m_strPlayingRadioGroup
std::string PVR::CPVRGUIInfo::m_strPlayingRadioGroup private
Referenced by GetListItemAndPlayerLabel(), and UpdateMisc().
m_strPlayingTVGroup
std::string PVR::CPVRGUIInfo::m_strPlayingTVGroup private
Referenced by GetListItemAndPlayerLabel(), and UpdateMisc().
m_timesInfo
CPVRGUITimesInfo PVR::CPVRGUIInfo::m_timesInfo private
Referenced by GetPVRBool(), GetPVRInt(), GetPVRLabel(), GetTimeShiftSeekPercent(), ResetProperties(), and UpdateTimeshiftData().
m_tvTimersInfo
CPVRGUITVTimerInfo PVR::CPVRGUIInfo::m_tvTimersInfo private
Referenced by GetPVRBool(), GetPVRLabel(), ResetProperties(), UpdateNextTimer(), UpdateTimersCache(), and UpdateTimersToggle().
m_updateBackendCacheRequested
std::atomic<bool> PVR::CPVRGUIInfo::m_updateBackendCacheRequested mutable private
The various backend-related fields will only be updated when this flag is set. This is done to limit the amount of unnecessary backend querying when we're not displaying any of the queried information.
Referenced by CharInfoBackendChannelGroups(), CharInfoBackendChannels(), CharInfoBackendDeletedRecordings(), CharInfoBackendDiskspace(), CharInfoBackendHost(), CharInfoBackendName(), CharInfoBackendProviders(), CharInfoBackendRecordings(), CharInfoBackendTimers(), CharInfoBackendVersion(), CharInfoClientName(), CharInfoInstanceName(), Process(), ResetProperties(), and UpdateBackendCache().
The documentation for this class was generated from the following files:
PVRGUIInfo.h
PVRGUIInfo.cpp