Kodi Documentation: CMusicThumbLoader Class Reference
CMusicThumbLoader Class Reference
#include <MusicThumbLoader.h>
Public Member Functions
CMusicThumbLoader ()
~CMusicThumbLoader () override
void OnLoaderStart () override
void OnLoaderFinish () override
bool LoadItem (CFileItem *pItem) override
bool LoadItemCached (CFileItem *pItem) override
bool LoadItemLookup (CFileItem *pItem) override
bool FillLibraryArt (CFileItem &item) override
Helper function to fill all the art for a music library item This fetches the original url for each type of art, and sets fallback thumb and fanart. For songs the art for the related album and artist(s) is also set, and for albums that of the related artist(s). Art type is named according to media type of the item, for example: artists may have "thumb", "fanart", "logo", "poster" etc., albums may have "thumb", "spine" etc. and "artist.thumb", "artist.fanart" etc., songs may have "thumb", "album.thumb", "artist.thumb", "artist.fanart", "artist.logo",... "artist1.thumb", "artist1.fanart",... "albumartist.thumb", "albumartist1.thumb" etc.
virtual bool FillThumb (CFileItem &item, bool folderThumbs=true)
Fill the thumb of a music file/folder item First uses a cached thumb from a previous run, then checks for a local thumb and caches it for the next run.
Public Member Functions inherited from CThumbLoader
CThumbLoader ()
~CThumbLoader () override
void OnLoaderStart () override
void OnLoaderFinish () override
virtual std::string GetCachedImage (const CFileItem &item, const std::string &type)
Checks whether the given item has an image listed in the texture database.
virtual void SetCachedImage (const CFileItem &item, const std::string &type, const std::string &image)
Associate an image with the given item in the texture database.
Public Member Functions inherited from CBackgroundInfoLoader
CBackgroundInfoLoader ()
~CBackgroundInfoLoader () override
void Load (CFileItemList &items)
bool IsLoading ()
void Run () override
void SetObserver (IBackgroundLoaderObserver *pObserver)
void SetProgressCallback (IProgressCallback *pCallback)
void StopThread ()
void StopAsync ()
Public Member Functions inherited from IRunnable
virtual void Cancel ()
virtual ~IRunnable ()=default
Protected Types
typedef std::map< int, std::map< std::string, std::string > > ArtCache
Protected Attributes
CMusicDatabase * m_musicDatabase
ArtCache m_albumArt
Protected Attributes inherited from CThumbLoader
CTextureDatabase * m_textureDatabase
Protected Attributes inherited from CBackgroundInfoLoader
CFileItemList * m_pVecItems {nullptr}
std::vector< CFileItemPtr > m_vecItems
CCriticalSection m_lock
volatile bool m_bIsLoading {false}
volatile bool m_bStop {true}
CThread * m_thread {nullptr}
IBackgroundLoaderObserver * m_pObserver {nullptr}
IProgressCallback * m_pProgressCallback {nullptr}
Additional Inherited Members
Member Typedef Documentation
ArtCache
typedef std::map<int, std::map<std::string, std::string> > CMusicThumbLoader::ArtCache protected
Constructor & Destructor Documentation
CMusicThumbLoader()
CMusicThumbLoader::CMusicThumbLoader ()
References m_musicDatabase.
~CMusicThumbLoader()
CMusicThumbLoader::~CMusicThumbLoader () override
References m_musicDatabase.
Member Function Documentation
FillLibraryArt()
bool CMusicThumbLoader::FillLibraryArt (CFileItem & item) override virtual
Helper function to fill all the art for a music library item This fetches the original url for each type of art, and sets fallback thumb and fanart. For songs the art for the related album and artist(s) is also set, and for albums that of the related artist(s). Art type is named according to media type of the item, for example: artists may have "thumb", "fanart", "logo", "poster" etc., albums may have "thumb", "spine" etc. and "artist.thumb", "artist.fanart" etc., songs may have "thumb", "album.thumb", "artist.thumb", "artist.fanart", "artist.logo",... "artist1.thumb", "artist1.fanart",... "albumartist.thumb", "albumartist1.thumb" etc.
Parameters
item a music CFileItem
Returns
true if we fill art, false if there is no art found
Reimplemented from CThumbLoader.
References CGUIListItem::AppendArt(), CAlbum::artistCredits, CSong::artistCredits, ArtForThumbLoader::artType, CDatabase::Close(), CMusicDatabase::GetArtForItem(), CMusicDatabase::GetArtistByName(), CFileItem::GetMusicInfoTag(), m_musicDatabase, ArtForThumbLoader::mediaType, MediaTypeAlbum, MediaTypeArtist, MediaTypeNone, MediaTypeSong, CMusicDatabase::Open(), ArtForThumbLoader::prefix, CGUIListItem::SetArtFallback(), CSong::SetArtistCredits(), CAlbum::SetArtistCredits(), CGUIListItem::SetProperty(), and ArtForThumbLoader::url.
Referenced by LoadItemCached().
FillThumb()
bool CMusicThumbLoader::FillThumb (CFileItem & item, bool folderThumbs = true) virtual
Fill the thumb of a music file/folder item First uses a cached thumb from a previous run, then checks for a local thumb and caches it for the next run.
Parameters
item the CFileItem object to fill
Returns
true if we fill the thumb, false otherwise
References CThumbLoader::GetCachedImage(), CFileItem::GetUserMusicThumb(), CGUIListItem::HasArt(), CGUIListItem::SetArt(), and CThumbLoader::SetCachedImage().
Referenced by CGUIWindowMusicBase::GetDirectory(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::InitCurrentItem(), and LoadItemLookup().
LoadItem()
bool CMusicThumbLoader::LoadItem (CFileItem * pItem) override virtual
Reimplemented from CBackgroundInfoLoader.
References LoadItemCached(), and LoadItemLookup().
Referenced by CGetInfoJob::DoWork(), CRefreshInfoJob::DoWork(), CGetSongInfoJob::DoWork(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetPlaylistInfo(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::InitCurrentItem(), MUSIC_INFO::CMusicInfoLoader::LoadItemCached(), CGUIDialogMusicInfo::SetDiscography(), CGUIDialogMusicInfo::SetSongs(), CApplication::UpdateCurrentPlayArt(), and CRecentlyAddedJob::UpdateMusic().
LoadItemCached()
bool CMusicThumbLoader::LoadItemCached (CFileItem * pItem) override virtual
Todo:
Remove as "fanart" is never been cached for music folders (only for
Reimplemented from CBackgroundInfoLoader.
References CVariant::asBoolean(), FillLibraryArt(), CThumbLoader::GetCachedImage(), CFileItem::GetMusicInfoTag(), CGUIListItem::GetProperty(), MUSIC_INFO::CMusicInfoTag::GetType(), CGUIListItem::HasArt(), CFileItem::HasMusicInfoTag(), CFileItem::HasVideoInfoTag(), CVideoThumbLoader::LoadItemCached(), CFileItem::m_bIsShareOrDrive, MediaTypeArtist, and CGUIListItem::SetArt().
Referenced by LoadItem().
LoadItemLookup()
bool CMusicThumbLoader::LoadItemLookup (CFileItem * pItem) override virtual
Reimplemented from CBackgroundInfoLoader.
References EmbeddedArtInfo::Empty(), FillThumb(), MUSIC_INFO::CMusicInfoTag::GetCoverArtInfo(), CFileItem::GetMusicInfoTag(), CFileItem::GetPath(), MUSIC_INFO::CMusicInfoTag::GetType(), CGUIListItem::HasArt(), CFileItem::HasMusicInfoTag(), CFileItem::HasVideoInfoTag(), CVideoThumbLoader::LoadItemLookup(), CFileItem::m_bIsShareOrDrive, MediaTypeArtist, CGUIListItem::SetArt(), and IMAGE_FILES::URLFromFile().
Referenced by LoadItem().
OnLoaderFinish()
void CMusicThumbLoader::OnLoaderFinish () override virtual
Reimplemented from CBackgroundInfoLoader.
References CDatabase::Close(), m_albumArt, m_musicDatabase, and CThumbLoader::OnLoaderFinish().
Referenced by MUSIC_INFO::CMusicInfoLoader::OnLoaderFinish().
OnLoaderStart()
void CMusicThumbLoader::OnLoaderStart () override virtual
Reimplemented from CBackgroundInfoLoader.
References m_albumArt, m_musicDatabase, CThumbLoader::OnLoaderStart(), and CMusicDatabase::Open().
Referenced by MUSIC_INFO::CMusicInfoLoader::OnLoaderStart(), and CRecentlyAddedJob::UpdateMusic().
Member Data Documentation
m_albumArt
ArtCache CMusicThumbLoader::m_albumArt protected
Referenced by OnLoaderFinish(), and OnLoaderStart().
m_musicDatabase
CMusicDatabase* CMusicThumbLoader::m_musicDatabase protected
Referenced by CMusicThumbLoader(), FillLibraryArt(), OnLoaderFinish(), OnLoaderStart(), and ~CMusicThumbLoader().
The documentation for this class was generated from the following files:
MusicThumbLoader.h
MusicThumbLoader.cpp