Kodi Documentation: CDVDRadioRDSData Class Reference
CDVDRadioRDSData Class Reference
#include <VideoPlayerRadioRDS.h>
Public Member Functions
CDVDRadioRDSData (CProcessInfo &processInfo)
— CDVDRadioRDSData ---------------------------------------------------------—
~CDVDRadioRDSData () override
bool CheckStream (const CDVDStreamInfo &hints)
bool OpenStream (CDVDStreamInfo hints) override
void CloseStream (bool bWaitForBuffers) override
void Flush ()
void WaitForBuffers ()
bool AcceptsData () const override
void SendMessage (std::shared_ptr< CDVDMsg > pMsg, int priority=0) override
void FlushMessages () override
bool IsInited () const override
bool IsStalled () const override
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Public Member Functions inherited from IDVDStreamPlayer
IDVDStreamPlayer (CProcessInfo &processInfo)
virtual ~IDVDStreamPlayer ()=default
Protected Member Functions
void OnExit () override
void Process () override
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Private Member Functions
void ResetRDSCache ()
void ProcessUECP (const unsigned char *Data, unsigned int Length)
unsigned int DecodePI (const uint8_t *msgElement)
unsigned int DecodePS (uint8_t *msgElement)
unsigned int DecodeDI (const uint8_t *msgElement)
unsigned int DecodeTA_TP (const uint8_t *msgElement)
unsigned int DecodeMS (const uint8_t *msgElement)
unsigned int DecodePTY (const uint8_t *msgElement)
unsigned int DecodePTYN (uint8_t *msgElement)
unsigned int DecodeRT (uint8_t *msgElement, unsigned int len)
unsigned int DecodeRTC (uint8_t *msgElement)
unsigned int DecodeODA (uint8_t *msgElement, unsigned int len)
unsigned int DecodeRTPlus (uint8_t *msgElement, unsigned int len)
unsigned int DecodeTMC (uint8_t *msgElement, unsigned int len)
unsigned int DecodeEPPTransmitterInfo (const uint8_t *msgElement)
unsigned int DecodeSlowLabelingCodes (const uint8_t *msgElement)
unsigned int DecodeDABDynLabelCmd (const uint8_t *msgElement, unsigned int len)
unsigned int DecodeDABDynLabelMsg (const uint8_t *msgElement, unsigned int len)
unsigned int DecodeAF (uint8_t *msgElement, unsigned int len)
unsigned int DecodeEonAF (uint8_t *msgElement, unsigned int len)
unsigned int DecodeTDC (uint8_t *msgElement, unsigned int len)
void SendTMCSignal (unsigned int flags, uint8_t *data)
void SetRadioStyle (const std::string &genre)
Private Attributes
std::shared_ptr< PVR::CPVRRadioRDSInfoTag > m_currentInfoTag
std::shared_ptr< PVR::CPVRChannel > m_currentChannel
bool m_currentFileUpdate
int m_speed
CCriticalSection m_critSection
CDVDMessageQueue m_messageQueue
uint8_t m_UECPData [UECP_SIZE_MAX+1]
unsigned int m_UECPDataIndex
bool m_UECPDataStart
bool m_UECPDatabStuff
bool m_UECPDataDeadBreak
bool m_RDS_IsRBDS
bool m_RDS_SlowLabelingCodesPresent
uint16_t m_PI_Current
unsigned int m_PI_CountryCode
unsigned int m_PI_ProgramType
unsigned int m_PI_ProgramReferenceNumber
unsigned int m_EPP_TM_INFO_ExtendedCountryCode
bool m_DI_IsStereo
bool m_DI_ArtificialHead
bool m_DI_Compressed
bool m_DI_DynamicPTY
bool m_TA_TP_TrafficAdvisory
float m_TA_TP_TrafficVolume
bool m_MS_SpeechActive
int m_PTY
char m_PTYN [9]
bool m_PTYN_Present
bool m_RT_NewItem
uint8_t m_RTPlus_WorkText [RT_MEL+1]
bool m_RTPlus_TToggle
int m_RTPlus_iDiffs
CStopWatch m_RTPlus_iTime
bool m_RTPlus_GenrePresent
char m_RTPlus_Temptext [RT_MEL]
bool m_RTPlus_Show
char m_RTPlus_Title [RT_MEL]
char m_RTPlus_Artist [RT_MEL]
int m_RTPlus_iToggle
unsigned int m_RTPlus_ItemToggle
time_t m_RTPlus_Starttime
CDateTime m_RTC_DateTime
From RDS transmitted date / time data.
uint8_t m_TMC_LastData [5]
Additional Inherited Members
Public Types inherited from IDVDStreamPlayer
enum ESyncState { SYNC_STARTING , SYNC_WAITSYNC , SYNC_INSYNC }
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Protected Attributes inherited from IDVDStreamPlayer
CProcessInfo & m_processInfo
Constructor & Destructor Documentation
CDVDRadioRDSData()
CDVDRadioRDSData::CDVDRadioRDSData (CProcessInfo & processInfo) explicit
— CDVDRadioRDSData ---------------------------------------------------------—
References CLog::Log(), LOGDEBUG, m_messageQueue, and CDVDMessageQueue::SetMaxDataSize().
~CDVDRadioRDSData()
CDVDRadioRDSData::~CDVDRadioRDSData () override
References CLog::Log(), LOGDEBUG, and CThread::StopThread().
Member Function Documentation
AcceptsData()
bool CDVDRadioRDSData::AcceptsData () const inline override virtual
Implements IDVDStreamPlayer.
References CDVDMessageQueue::IsFull(), and m_messageQueue.
CheckStream()
bool CDVDRadioRDSData::CheckStream (const CDVDStreamInfo & hints)
References STREAM_RADIO_RDS, and CDVDStreamInfo::type.
Referenced by CVideoPlayer::OpenRadioRDSStream().
CloseStream()
void CDVDRadioRDSData::CloseStream (bool bWaitForBuffers) override virtual
Implements IDVDStreamPlayer.
References CDVDMessageQueue::Abort(), CDVDMessageQueue::End(), CLog::Log(), LOGINFO, m_currentChannel, m_currentInfoTag, m_messageQueue, and CThread::StopThread().
Referenced by OpenStream().
DecodeAF()
unsigned int CDVDRadioRDSData::DecodeAF (uint8_t * msgElement, unsigned int len) inline private
unused processed here to have length of it
References m_UECPDataDeadBreak.
Referenced by ProcessUECP().
DecodeDABDynLabelCmd()
unsigned int CDVDRadioRDSData::DecodeDABDynLabelCmd (const uint8_t * msgElement, unsigned int len) inline private
currently unused need to be checked on DAB, processed here to have length of it
References m_UECPDataDeadBreak.
Referenced by ProcessUECP().
DecodeDABDynLabelMsg()
unsigned int CDVDRadioRDSData::DecodeDABDynLabelMsg (const uint8_t * msgElement, unsigned int len) inline private
currently unused need to be checked on DAB, processed here to have length of it
References m_UECPDataDeadBreak.
Referenced by ProcessUECP().
DecodeDI()
unsigned int CDVDRadioRDSData::DecodeDI (const uint8_t * msgElement) inline private
References CLog::Log(), LOGDEBUG, m_DI_ArtificialHead, m_DI_DynamicPTY, m_DI_IsStereo, and value.
Referenced by ProcessUECP().
DecodeEonAF()
unsigned int CDVDRadioRDSData::DecodeEonAF (uint8_t * msgElement, unsigned int len) inline private
unused processed here to have length of it
References m_UECPDataDeadBreak.
Referenced by ProcessUECP().
DecodeEPPTransmitterInfo()
unsigned int CDVDRadioRDSData::DecodeEPPTransmitterInfo (const uint8_t * msgElement) inline private
References CLog::Log(), LOGERROR, m_currentInfoTag, m_PI_CountryCode, m_RDS_IsRBDS, m_RDS_SlowLabelingCodesPresent, piCountryCodes_A, piCountryCodes_D, piCountryCodes_E, and piCountryCodes_F.
Referenced by ProcessUECP().
DecodeMS()
unsigned int CDVDRadioRDSData::DecodeMS (const uint8_t * msgElement) inline private
References CLog::Log(), LOGDEBUG, m_currentInfoTag, and m_MS_SpeechActive.
Referenced by ProcessUECP().
DecodeODA()
unsigned int CDVDRadioRDSData::DecodeODA (uint8_t * msgElement, unsigned int len) inline private
< RT+
< TMC Alert-C
References DecodeRTPlus(), CLog::Log(), LOGERROR, m_UECPDataDeadBreak, and SendTMCSignal().
Referenced by ProcessUECP().
DecodePI()
unsigned int CDVDRadioRDSData::DecodePI (const uint8_t * msgElement) inline private
References CLog::Log(), LOGINFO, m_PI_CountryCode, m_PI_Current, m_PI_ProgramReferenceNumber, and m_PI_ProgramType.
Referenced by ProcessUECP().
DecodePS()
unsigned int CDVDRadioRDSData::DecodePS (uint8_t * msgElement) inline private
< additional rds-character, see RBDS-Standard, Annex E
References m_currentInfoTag, sRDSAddChar, and text.
Referenced by ProcessUECP().
DecodePTY()
unsigned int CDVDRadioRDSData::DecodePTY (const uint8_t * msgElement) inline private
References g_localizeStrings, CLocalizeStrings::Get(), CGUIDialogKaiToast::Info, m_currentInfoTag, m_PTY, m_PTYN_Present, m_RDS_IsRBDS, m_RTPlus_GenrePresent, pty_skin_info::name, pty_skin_info_table, CGUIDialogKaiToast::QueueNotification(), RDS_PTY_ALARM, RDS_PTY_ALARM_TEST, SetRadioStyle(), TOAST_DISPLAY_TIME, and CGUIDialogKaiToast::Warning.
Referenced by ProcessUECP().
DecodePTYN()
unsigned int CDVDRadioRDSData::DecodePTYN (uint8_t * msgElement) inline private
References g_localizeStrings, CLocalizeStrings::Get(), m_PTY, m_PTYN, m_PTYN_Present, m_RDS_IsRBDS, m_RTPlus_GenrePresent, pty_skin_info::name, pty_skin_info_table, SetRadioStyle(), sRDSAddChar, and text.
Referenced by ProcessUECP().
DecodeRT()
unsigned int CDVDRadioRDSData::DecodeRT (uint8_t * msgElement, unsigned int len) inline private
byte 4 = RT-Status bitcodet (0=AB-flagcontrol, 1-4=Transmission-Number, 5+6=Buffer-Config, ignored, always 0x01 ?)
References CLog::Log(), LOGERROR, m_currentInfoTag, m_RTPlus_iToggle, m_RTPlus_WorkText, m_UECPDataDeadBreak, rds_entitychar(), RT_MEL, sRDSAddChar, UECP_ME_DATA, and UECP_ME_MEL.
Referenced by ProcessUECP().
DecodeRTC()
unsigned int CDVDRadioRDSData::DecodeRTC (uint8_t * msgElement) inline private
References data(), CServiceBroker::GetAnnouncementManager(), CDateTime::GetAsRFC1123DateTime(), CDateTime::IsValid(), CLog::Log(), LOGDEBUG, m_RTC_DateTime, ANNOUNCEMENT::PVR, CDateTime::SetDateTime(), UECP_CLOCK_CENTSEC, UECP_CLOCK_DAY, UECP_CLOCK_HOURS, UECP_CLOCK_LOCALOFFSET, UECP_CLOCK_MINUTES, UECP_CLOCK_MONTH, UECP_CLOCK_SECONDS, UECP_CLOCK_YEAR, and CVariant::VariantTypeObject.
Referenced by ProcessUECP().
DecodeRTPlus()
unsigned int CDVDRadioRDSData::DecodeRTPlus (uint8_t * msgElement, unsigned int len) inline private
Hack for error on BR Classic
Currently unused radiotext plus messages Must be check where present and if it is usable
Unused and not needed data information
< Must be rechecked under DAB
References g_application, g_charsetConverter, CStopWatch::GetElapsedSeconds(), CLog::Log(), LOGERROR, m_currentFileUpdate, m_currentInfoTag, m_RT_NewItem, m_RTPlus_Artist, m_RTPlus_GenrePresent, m_RTPlus_iDiffs, m_RTPlus_ItemToggle, m_RTPlus_iTime, m_RTPlus_iToggle, m_RTPlus_Show, m_RTPlus_Starttime, m_RTPlus_Temptext, m_RTPlus_Title, m_RTPlus_TToggle, m_RTPlus_WorkText, m_UECPDataDeadBreak, rds_entitychar(), RT_MEL, RTPLUS_APPOINTMENT, RTPLUS_CHAT, RTPLUS_CHAT_CENTER, RTPLUS_DUMMY_CLASS, RTPLUS_EMAIL_HOTLINE, RTPLUS_EMAIL_OTHER, RTPLUS_EMAIL_STUDIO, RTPLUS_GET_DATA, RTPLUS_IDENTIFIER, RTPLUS_INFO_ADVERTISEMENT, RTPLUS_INFO_ALARM, RTPLUS_INFO_CINEMA, RTPLUS_INFO_DAILY_DIVERSION, RTPLUS_INFO_DATE_TIME, RTPLUS_INFO_EVENT, RTPLUS_INFO_HEALTH, RTPLUS_INFO_HOROSCOPE, RTPLUS_INFO_LOTTERY, RTPLUS_INFO_NEWS, RTPLUS_INFO_NEWS_LOCAL, RTPLUS_INFO_OTHER, RTPLUS_INFO_SPORT, RTPLUS_INFO_STOCKMARKET, RTPLUS_INFO_STUPIDITY_MACHINE, RTPLUS_INFO_SZENE, RTPLUS_INFO_TRAFFIC, RTPLUS_INFO_URL, RTPLUS_INFO_WEATHER, RTPLUS_ITEM_ALBUM, RTPLUS_ITEM_ARTIST, RTPLUS_ITEM_BAND, RTPLUS_ITEM_COMMENT, RTPLUS_ITEM_COMPOSER, RTPLUS_ITEM_COMPOSITION, RTPLUS_ITEM_CONDUCTOR, RTPLUS_ITEM_GENRE, RTPLUS_ITEM_MOVEMENT, RTPLUS_ITEM_TITLE, RTPLUS_ITEM_TRACKNUMBER, RTPLUS_MMS_OTHER, RTPLUS_PHONE_HOTLINE, RTPLUS_PHONE_OTHER, RTPLUS_PHONE_STUDIO, RTPLUS_PLACE, RTPLUS_PROGRAMME_EDITORIAL_STAFF, RTPLUS_PROGRAMME_FREQUENCY, RTPLUS_PROGRAMME_HOMEPAGE, RTPLUS_PROGRAMME_HOST, RTPLUS_PROGRAMME_NEXT, RTPLUS_PROGRAMME_NOW, RTPLUS_PROGRAMME_PART, RTPLUS_PROGRAMME_SUBCHANNEL, RTPLUS_PURCHASE, RTPLUS_SMS_OTHER, RTPLUS_SMS_STUDIO, RTPLUS_STATIONNAME_LONG, RTPLUS_VOTE_CENTER, RTPLUS_VOTE_QUESTION, MUSIC_INFO::CMusicInfoTag::SetAlbum(), MUSIC_INFO::CMusicInfoTag::SetAlbumId(), MUSIC_INFO::CMusicInfoTag::SetArtist(), MUSIC_INFO::CMusicInfoTag::SetTitle(), and CStopWatch::StartZero().
Referenced by DecodeODA().
DecodeSlowLabelingCodes()
unsigned int CDVDRadioRDSData::DecodeSlowLabelingCodes (const uint8_t * msgElement) inline private
References CLog::Log(), LOGERROR, m_currentInfoTag, m_PI_CountryCode, m_RDS_SlowLabelingCodesPresent, piCountryCodes_A, piCountryCodes_D, piCountryCodes_E, piCountryCodes_F, piRDSLanguageCodes, VARCODE_EWS_CHANNEL_IDENT, VARCODE_LANGUAGE_CODES, VARCODE_OWN_BROADCASTER, VARCODE_PAGING_EXTCOUNTRYCODE, VARCODE_PAGING_IDENT, and VARCODE_TMC_IDENT.
Referenced by ProcessUECP().
DecodeTA_TP()
unsigned int CDVDRadioRDSData::DecodeTA_TP (const uint8_t * msgElement) inline private
References data(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetAppComponents(), CServiceBroker::GetSettingsComponent(), CApplicationVolumeHandling::GetVolumePercent(), m_TA_TP_TrafficAdvisory, m_TA_TP_TrafficVolume, ANNOUNCEMENT::PVR, CGUIDialogKaiToast::QueueNotification(), CApplicationVolumeHandling::SetVolume(), CVariant::VariantTypeObject, and CGUIDialogKaiToast::Warning.
Referenced by ProcessUECP().
DecodeTDC()
unsigned int CDVDRadioRDSData::DecodeTDC (uint8_t * msgElement, unsigned int len) inline private
unused processed here to have length of it
References m_UECPDataDeadBreak.
Referenced by ProcessUECP().
DecodeTMC()
unsigned int CDVDRadioRDSData::DecodeTMC (uint8_t * msgElement, unsigned int len) inline private
References m_UECPDataDeadBreak, and SendTMCSignal().
Referenced by ProcessUECP().
Flush()
void CDVDRadioRDSData::Flush ()
References CDVDMessageQueue::Flush(), CDVDMsg::GENERAL_FLUSH, CDVDMessageQueue::IsInited(), m_messageQueue, and CDVDMessageQueue::Put().
Referenced by CVideoPlayer::FlushBuffers(), and OpenStream().
FlushMessages()
void CDVDRadioRDSData::FlushMessages () inline override virtual
Implements IDVDStreamPlayer.
References CDVDMessageQueue::Flush(), and m_messageQueue.
IsInited()
bool CDVDRadioRDSData::IsInited () const inline override virtual
Implements IDVDStreamPlayer.
IsStalled()
bool CDVDRadioRDSData::IsStalled () const inline override virtual
Implements IDVDStreamPlayer.
OnExit()
void CDVDRadioRDSData::OnExit () override protected virtual
Reimplemented from CThread.
References CLog::Log(), and LOGINFO.
OpenStream()
bool CDVDRadioRDSData::OpenStream (CDVDStreamInfo hints) override virtual
Implements IDVDStreamPlayer.
References CloseStream(), CThread::Create(), Flush(), CDVDMessageQueue::Init(), CLog::Log(), LOGINFO, m_messageQueue, STREAM_RADIO_RDS, and CDVDStreamInfo::type.
Process()
void CDVDRadioRDSData::Process (void) override protected virtual
Reimplemented from CThread.
References CDVDMsg::DEMUXER_PACKET, DVD_PLAYSPEED_PAUSE, CDVDMsg::GENERAL_FLUSH, CDVDMsg::GENERAL_RESET, CDVDMessageQueue::Get(), DEMUX_PACKET::iSize, CLog::Log(), LOGERROR, LOGINFO, CThread::m_bStop, m_critSection, m_messageQueue, m_speed, MSGQ_IS_ERROR, MSGQ_TIMEOUT, DEMUX_PACKET::pData, CDVDMsg::PLAYER_SETSPEED, ProcessUECP(), CDVDMessageQueue::ReceivedAbortRequest(), and ResetRDSCache().
ProcessUECP()
void CDVDRadioRDSData::ProcessUECP (const unsigned char * Data, unsigned int Length) private
< Start
byte-stuffing reverse: 0xfd00->0xfd, 0xfd01->0xfe, 0xfd02->0xff
< stuffing found
< max. UECP data length, garbage ?
< End
crc16-check
< Current selected UECP message element (increased if more as one element is in frame)
< Program Identification
< Program Service name (PS)
< Decoder Identification and dynamic PTY indicator
< Traffic Announcement and Traffic Programme bits.
< Music/Speech switch
< Program Type
< Program Type Name
< RadioText
< Open Data Application
< Radio screen show (RaSS) (not present, before on SWR radio)
< Real time clock
< Traffic message channel
< EPP transmitter information
< Slow Labeling codes
< DAB: Dynamic Label command
< DAB: Dynamic Label message (DL)
< Alternative Frequencies list
< EON Alternative Frequencies list
< Transparent Data Channel
< Linkage information
< Emergency warning system
< Program Item Number
< In-house applications (Should be ignored)
< Free-format group (unused)
< ODA Configuration and Short Message Command (unused)
< Real time clock correction (unused)
< Real time clock on/off (unused)
References crc16_ccitt(), data(), DecodeAF(), DecodeDABDynLabelCmd(), DecodeDABDynLabelMsg(), DecodeDI(), DecodeEonAF(), DecodeEPPTransmitterInfo(), DecodeMS(), DecodeODA(), DecodePI(), DecodePS(), DecodePTY(), DecodePTYN(), DecodeRT(), DecodeRTC(), DecodeSlowLabelingCodes(), DecodeTA_TP(), DecodeTDC(), DecodeTMC(), g_application, CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), CLog::Log(), LOGERROR, CThread::m_bStop, m_currentFileUpdate, m_currentInfoTag, m_UECPData, m_UECPDatabStuff, m_UECPDataDeadBreak, m_UECPDataIndex, m_UECPDataStart, CGUIInfoManager::SetCurrentItem(), UECP_CLOCK_CT_ON_OFF, UECP_CLOCK_RTC, UECP_CLOCK_RTC_CORR, UECP_DAB_DYN_LABEL_CMD, UECP_DAB_DYN_LABEL_MSG, UECP_DATA_START, UECP_DATA_STOP, UECP_EPP_TM_INFO, UECP_LINKAGE_INFO, UECP_ME_MEC, UECP_ODA_CONF_SHORT_MSG_CMD, UECP_ODA_DATA, UECP_OTHER_RASS, UECP_RDS_AF, UECP_RDS_DI, UECP_RDS_EON_AF, UECP_RDS_MS, UECP_RDS_PI, UECP_RDS_PIN, UECP_RDS_PS, UECP_RDS_PTY, UECP_RDS_PTYN, UECP_RDS_RT, UECP_RDS_TA_TP, UECP_SIZE_MAX, UECP_SLOW_LABEL_CODES, UECP_TDC_EWS, UECP_TDC_FREE_FMT_GROUP, UECP_TDC_IH, UECP_TDC_TDC, and UECP_TDC_TMC.
Referenced by Process().
ResetRDSCache()
void CDVDRadioRDSData::ResetRDSCache () private
References g_application, CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE_RADIOTEXT, m_critSection, m_currentChannel, m_currentFileUpdate, m_currentInfoTag, m_DI_ArtificialHead, m_DI_Compressed, m_DI_DynamicPTY, m_DI_IsStereo, m_EPP_TM_INFO_ExtendedCountryCode, m_MS_SpeechActive, m_PI_CountryCode, m_PI_Current, m_PI_ProgramReferenceNumber, m_PI_ProgramType, m_PTY, m_PTYN, m_PTYN_Present, m_RDS_IsRBDS, m_RDS_SlowLabelingCodesPresent, m_RT_NewItem, m_RTPlus_Artist, m_RTPlus_GenrePresent, m_RTPlus_ItemToggle, m_RTPlus_iToggle, m_RTPlus_Show, m_RTPlus_Starttime, m_RTPlus_Title, m_RTPlus_TToggle, m_TA_TP_TrafficAdvisory, m_TA_TP_TrafficVolume, m_UECPDatabStuff, m_UECPDataIndex, and m_UECPDataStart.
Referenced by Process().
SendMessage()
void CDVDRadioRDSData::SendMessage (std::shared_ptr< CDVDMsg > pMsg, int priority = 0) inline override virtual
Implements IDVDStreamPlayer.
References CDVDMessageQueue::IsInited(), m_messageQueue, and CDVDMessageQueue::Put().
Referenced by CVideoPlayer::ProcessRadioRDSData().
SendTMCSignal()
void CDVDRadioRDSData::SendTMCSignal (unsigned int flags, uint8_t * data) private
References data(), CServiceBroker::GetAnnouncementManager(), m_currentChannel, m_PI_Current, m_TMC_LastData, ANNOUNCEMENT::PVR, and CVariant::VariantTypeObject.
Referenced by DecodeODA(), and DecodeTMC().
SetRadioStyle()
void CDVDRadioRDSData::SetRadioStyle (const std::string & genre) private
References g_application, CLog::Log(), LOGDEBUG, m_currentFileUpdate, and m_currentInfoTag.
Referenced by DecodePTY(), and DecodePTYN().
WaitForBuffers()
void CDVDRadioRDSData::WaitForBuffers () inline
References m_messageQueue, and CDVDMessageQueue::WaitUntilEmpty().
Member Data Documentation
m_critSection
CCriticalSection CDVDRadioRDSData::m_critSection private
Referenced by Process(), and ResetRDSCache().
m_currentChannel
std::shared_ptr<PVR::CPVRChannel> CDVDRadioRDSData::m_currentChannel private
Referenced by CloseStream(), ResetRDSCache(), and SendTMCSignal().
m_currentFileUpdate
bool CDVDRadioRDSData::m_currentFileUpdate private
Referenced by DecodeRTPlus(), ProcessUECP(), ResetRDSCache(), and SetRadioStyle().
m_currentInfoTag
std::shared_ptr<PVR::CPVRRadioRDSInfoTag> CDVDRadioRDSData::m_currentInfoTag private
Referenced by CloseStream(), DecodeEPPTransmitterInfo(), DecodeMS(), DecodePS(), DecodePTY(), DecodeRT(), DecodeRTPlus(), DecodeSlowLabelingCodes(), ProcessUECP(), ResetRDSCache(), and SetRadioStyle().
m_DI_ArtificialHead
bool CDVDRadioRDSData::m_DI_ArtificialHead private
Referenced by DecodeDI(), and ResetRDSCache().
m_DI_Compressed
bool CDVDRadioRDSData::m_DI_Compressed private
Referenced by ResetRDSCache().
m_DI_DynamicPTY
bool CDVDRadioRDSData::m_DI_DynamicPTY private
Referenced by DecodeDI(), and ResetRDSCache().
m_DI_IsStereo
bool CDVDRadioRDSData::m_DI_IsStereo private
Referenced by DecodeDI(), and ResetRDSCache().
m_EPP_TM_INFO_ExtendedCountryCode
unsigned int CDVDRadioRDSData::m_EPP_TM_INFO_ExtendedCountryCode private
Referenced by ResetRDSCache().
m_messageQueue
CDVDMessageQueue CDVDRadioRDSData::m_messageQueue private
Referenced by AcceptsData(), CDVDRadioRDSData(), CloseStream(), Flush(), FlushMessages(), OpenStream(), Process(), SendMessage(), and WaitForBuffers().
m_MS_SpeechActive
bool CDVDRadioRDSData::m_MS_SpeechActive private
Referenced by DecodeMS(), and ResetRDSCache().
m_PI_CountryCode
unsigned int CDVDRadioRDSData::m_PI_CountryCode private
Referenced by DecodeEPPTransmitterInfo(), DecodePI(), DecodeSlowLabelingCodes(), and ResetRDSCache().
m_PI_Current
uint16_t CDVDRadioRDSData::m_PI_Current private
Referenced by DecodePI(), ResetRDSCache(), and SendTMCSignal().
m_PI_ProgramReferenceNumber
unsigned int CDVDRadioRDSData::m_PI_ProgramReferenceNumber private
Referenced by DecodePI(), and ResetRDSCache().
m_PI_ProgramType
unsigned int CDVDRadioRDSData::m_PI_ProgramType private
Referenced by DecodePI(), and ResetRDSCache().
m_PTY
int CDVDRadioRDSData::m_PTY private
Referenced by DecodePTY(), DecodePTYN(), and ResetRDSCache().
m_PTYN
char CDVDRadioRDSData::m_PTYN[9] private
Referenced by DecodePTYN(), and ResetRDSCache().
m_PTYN_Present
bool CDVDRadioRDSData::m_PTYN_Present private
Referenced by DecodePTY(), DecodePTYN(), and ResetRDSCache().
m_RDS_IsRBDS
bool CDVDRadioRDSData::m_RDS_IsRBDS private
Referenced by DecodeEPPTransmitterInfo(), DecodePTY(), DecodePTYN(), and ResetRDSCache().
m_RDS_SlowLabelingCodesPresent
bool CDVDRadioRDSData::m_RDS_SlowLabelingCodesPresent private
Referenced by DecodeEPPTransmitterInfo(), DecodeSlowLabelingCodes(), and ResetRDSCache().
m_RT_NewItem
bool CDVDRadioRDSData::m_RT_NewItem private
Referenced by DecodeRTPlus(), and ResetRDSCache().
m_RTC_DateTime
CDateTime CDVDRadioRDSData::m_RTC_DateTime private
From RDS transmitted date / time data.
Referenced by DecodeRTC().
m_RTPlus_Artist
char CDVDRadioRDSData::m_RTPlus_Artist[RT_MEL] private
Referenced by DecodeRTPlus(), and ResetRDSCache().
m_RTPlus_GenrePresent
bool CDVDRadioRDSData::m_RTPlus_GenrePresent private
Referenced by DecodePTY(), DecodePTYN(), DecodeRTPlus(), and ResetRDSCache().
m_RTPlus_iDiffs
int CDVDRadioRDSData::m_RTPlus_iDiffs private
Referenced by DecodeRTPlus().
m_RTPlus_ItemToggle
unsigned int CDVDRadioRDSData::m_RTPlus_ItemToggle private
Referenced by DecodeRTPlus(), and ResetRDSCache().
m_RTPlus_iTime
CStopWatch CDVDRadioRDSData::m_RTPlus_iTime private
Referenced by DecodeRTPlus().
m_RTPlus_iToggle
int CDVDRadioRDSData::m_RTPlus_iToggle private
Referenced by DecodeRT(), DecodeRTPlus(), and ResetRDSCache().
m_RTPlus_Show
bool CDVDRadioRDSData::m_RTPlus_Show private
Referenced by DecodeRTPlus(), and ResetRDSCache().
m_RTPlus_Starttime
time_t CDVDRadioRDSData::m_RTPlus_Starttime private
Referenced by DecodeRTPlus(), and ResetRDSCache().
m_RTPlus_Temptext
char CDVDRadioRDSData::m_RTPlus_Temptext[RT_MEL] private
Referenced by DecodeRTPlus().
m_RTPlus_Title
char CDVDRadioRDSData::m_RTPlus_Title[RT_MEL] private
Referenced by DecodeRTPlus(), and ResetRDSCache().
m_RTPlus_TToggle
bool CDVDRadioRDSData::m_RTPlus_TToggle private
Referenced by DecodeRTPlus(), and ResetRDSCache().
m_RTPlus_WorkText
uint8_t CDVDRadioRDSData::m_RTPlus_WorkText[RT_MEL+1] private
Referenced by DecodeRT(), and DecodeRTPlus().
m_speed
int CDVDRadioRDSData::m_speed private
Referenced by Process().
m_TA_TP_TrafficAdvisory
bool CDVDRadioRDSData::m_TA_TP_TrafficAdvisory private
Referenced by DecodeTA_TP(), and ResetRDSCache().
m_TA_TP_TrafficVolume
float CDVDRadioRDSData::m_TA_TP_TrafficVolume private
Referenced by DecodeTA_TP(), and ResetRDSCache().
m_TMC_LastData
uint8_t CDVDRadioRDSData::m_TMC_LastData[5] private
Referenced by SendTMCSignal().
m_UECPData
uint8_t CDVDRadioRDSData::m_UECPData[UECP_SIZE_MAX+1] private
Referenced by ProcessUECP().
m_UECPDatabStuff
bool CDVDRadioRDSData::m_UECPDatabStuff private
Referenced by ProcessUECP(), and ResetRDSCache().
m_UECPDataDeadBreak
bool CDVDRadioRDSData::m_UECPDataDeadBreak private
Referenced by DecodeAF(), DecodeDABDynLabelCmd(), DecodeDABDynLabelMsg(), DecodeEonAF(), DecodeODA(), DecodeRT(), DecodeRTPlus(), DecodeTDC(), DecodeTMC(), and ProcessUECP().
m_UECPDataIndex
unsigned int CDVDRadioRDSData::m_UECPDataIndex private
Referenced by ProcessUECP(), and ResetRDSCache().
m_UECPDataStart
bool CDVDRadioRDSData::m_UECPDataStart private
Referenced by ProcessUECP(), and ResetRDSCache().
The documentation for this class was generated from the following files:
VideoPlayerRadioRDS.h
VideoPlayerRadioRDS.cpp