Kodi Documentation: KODI::VIDEO::TAGS::CVideoTagExtractionHelper Class Reference
KODI::VIDEO::TAGS::CVideoTagExtractionHelper Class Reference
#include <VideoTagExtractionHelper.h>
Static Public Member Functions
static bool IsExtractionSupportedFor (const CFileItem &item)
Check whether tag extraction is supported for the given item. This is no check whether the video denoted by the item actually contains any tags. There is also a Kodi setting for enabling video tag support that is taken into consideration by the implementation of this function.
static std::string ExtractEmbeddedArtFor (const CFileItem &item, const std::string &artType)
Try to extract embedded art of given type from the given item denoting a video file.
Member Function Documentation
ExtractEmbeddedArtFor()
std::string KODI::VIDEO::TAGS::CVideoTagExtractionHelper::ExtractEmbeddedArtFor (const CFileItem & item, const std::string & artType) static
Try to extract embedded art of given type from the given item denoting a video file.
Parameters
item [in] the item.
artType The type of the art to extract (e.g. "fanart").
Returns
The image URL of the embedded art if extraction was successful, false otherwise.
References CFileItem::GetDynPath(), CVideoTagLoaderFFmpeg::Load(), and IMAGE_FILES::URLFromFile().
Referenced by KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::GetEmbeddedArt().
IsExtractionSupportedFor()
bool KODI::VIDEO::TAGS::CVideoTagExtractionHelper::IsExtractionSupportedFor (const CFileItem & item) static
Check whether tag extraction is supported for the given item. This is no check whether the video denoted by the item actually contains any tags. There is also a Kodi setting for enabling video tag support that is taken into consideration by the implementation of this function.
Parameters
item [in] the item denoting a video file.
Returns
True if tag support is enabled and extraction is supported for the given file type.
References CFileItem::GetDynPath(), CServiceBroker::GetSettingsComponent(), URIUtils::HasExtension(), and CSettings::SETTING_MYVIDEOS_USETAGS.
Referenced by KODI::VIDEO::CVideoInfoTagLoaderFactory::CreateLoader(), and KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::GetEmbeddedArt().
The documentation for this class was generated from the following files:
VideoTagExtractionHelper.h
VideoTagExtractionHelper.cpp