Kodi Documentation: ADDON::Interface_GUIGeneral Struct Reference
ADDON::Interface_GUIGeneral Struct Reference
Global gui Add-on to Kodi callback functions.
#include <General.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static void lock ()
callback functions from add-on to kodi
static void unlock ()
static int get_screen_height (KODI_HANDLE kodiBase)
static int get_screen_width (KODI_HANDLE kodiBase)
static int get_video_resolution (KODI_HANDLE kodiBase)
static int get_current_window_dialog_id (KODI_HANDLE kodiBase)
static int get_current_window_id (KODI_HANDLE kodiBase)
static ADDON_HARDWARE_CONTEXT get_hw_context (KODI_HANDLE kodiBase)
static AdjustRefreshRateStatus get_adjust_refresh_rate_status (KODI_HANDLE kodiBase)
Static Private Attributes
static int m_iAddonGUILockRef = 0
Detailed Description
Global gui Add-on to Kodi callback functions.
To hold general gui functions and initialize also all other gui related types not related to a instance type and usable for every add-on type.
Related add-on header is "./xbmc/addons/kodi-dev-kit/include/kodi/gui/General.h"
Member Function Documentation
DeInit()
void ADDON::Interface_GUIGeneral::DeInit (AddonGlobalInterface * addonInterface) static
References ADDON::Interface_GUIControlButton::DeInit(), ADDON::Interface_GUIControlEdit::DeInit(), ADDON::Interface_GUIControlFadeLabel::DeInit(), ADDON::Interface_GUIControlImage::DeInit(), ADDON::Interface_GUIControlLabel::DeInit(), ADDON::Interface_GUIControlProgress::DeInit(), ADDON::Interface_GUIControlRadioButton::DeInit(), ADDON::Interface_GUIControlAddonRendering::DeInit(), ADDON::Interface_GUIControlSettingsSlider::DeInit(), ADDON::Interface_GUIControlSlider::DeInit(), ADDON::Interface_GUIControlSpin::DeInit(), ADDON::Interface_GUIControlTextBox::DeInit(), ADDON::Interface_GUIDialogContextMenu::DeInit(), ADDON::Interface_GUIDialogExtendedProgress::DeInit(), ADDON::Interface_GUIDialogFileBrowser::DeInit(), ADDON::Interface_GUIDialogKeyboard::DeInit(), ADDON::Interface_GUIDialogNumeric::DeInit(), ADDON::Interface_GUIDialogOK::DeInit(), ADDON::Interface_GUIDialogProgress::DeInit(), ADDON::Interface_GUIDialogSelect::DeInit(), ADDON::Interface_GUIDialogTextViewer::DeInit(), ADDON::Interface_GUIDialogYesNo::DeInit(), ADDON::Interface_GUIListItem::DeInit(), ADDON::Interface_GUIWindow::DeInit(), AddonToKodiFuncTable_kodi_gui::general, AddonToKodiFuncTable_Addon::kodi_gui, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_Base::DeInitInterface().
get_adjust_refresh_rate_status()
AdjustRefreshRateStatus ADDON::Interface_GUIGeneral::get_adjust_refresh_rate_status (KODI_HANDLE kodiBase) static
References ADJUST_REFRESHRATE_ALWAYS, ADJUST_REFRESHRATE_OFF, ADJUST_REFRESHRATE_ON_START, ADJUST_REFRESHRATE_ON_STARTSTOP, ADJUST_REFRESHRATE_STATUS_ALWAYS, ADJUST_REFRESHRATE_STATUS_OFF, ADJUST_REFRESHRATE_STATUS_ON_START, ADJUST_REFRESHRATE_STATUS_ON_STARTSTOP, CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGERROR, and CSettings::SETTING_VIDEOPLAYER_ADJUSTREFRESHRATE.
Referenced by Init().
get_current_window_dialog_id()
int ADDON::Interface_GUIGeneral::get_current_window_dialog_id (KODI_HANDLE kodiBase) static
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_current_window_id()
int ADDON::Interface_GUIGeneral::get_current_window_id (KODI_HANDLE kodiBase) static
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_hw_context()
ADDON_HARDWARE_CONTEXT ADDON::Interface_GUIGeneral::get_hw_context (KODI_HANDLE kodiBase) static
References CWinSystemBase::GetHWContext(), and CServiceBroker::GetWinSystem().
Referenced by Init().
get_screen_height()
int ADDON::Interface_GUIGeneral::get_screen_height (KODI_HANDLE kodiBase) static
References CWinSystemBase::GetGfxContext(), CGraphicContext::GetHeight(), CServiceBroker::GetWinSystem(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_screen_width()
int ADDON::Interface_GUIGeneral::get_screen_width (KODI_HANDLE kodiBase) static
References CWinSystemBase::GetGfxContext(), CGraphicContext::GetWidth(), CServiceBroker::GetWinSystem(), CLog::Log(), and LOGERROR.
Referenced by Init().
get_video_resolution()
int ADDON::Interface_GUIGeneral::get_video_resolution (KODI_HANDLE kodiBase) static
References CWinSystemBase::GetGfxContext(), CGraphicContext::GetVideoResolution(), CServiceBroker::GetWinSystem(), CLog::Log(), and LOGERROR.
Referenced by Init().
Init()
void ADDON::Interface_GUIGeneral::Init (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_kodi_gui::general, get_adjust_refresh_rate_status(), AddonToKodiFuncTable_kodi_gui_general::get_adjust_refresh_rate_status, get_current_window_dialog_id(), AddonToKodiFuncTable_kodi_gui_general::get_current_window_dialog_id, get_current_window_id(), AddonToKodiFuncTable_kodi_gui_general::get_current_window_id, get_hw_context(), AddonToKodiFuncTable_kodi_gui_general::get_hw_context, get_screen_height(), AddonToKodiFuncTable_kodi_gui_general::get_screen_height, get_screen_width(), AddonToKodiFuncTable_kodi_gui_general::get_screen_width, get_video_resolution(), AddonToKodiFuncTable_kodi_gui_general::get_video_resolution, ADDON::Interface_GUIControlButton::Init(), ADDON::Interface_GUIControlEdit::Init(), ADDON::Interface_GUIControlFadeLabel::Init(), ADDON::Interface_GUIControlImage::Init(), ADDON::Interface_GUIControlLabel::Init(), ADDON::Interface_GUIControlProgress::Init(), ADDON::Interface_GUIControlRadioButton::Init(), ADDON::Interface_GUIControlAddonRendering::Init(), ADDON::Interface_GUIControlSettingsSlider::Init(), ADDON::Interface_GUIControlSlider::Init(), ADDON::Interface_GUIControlSpin::Init(), ADDON::Interface_GUIControlTextBox::Init(), ADDON::Interface_GUIDialogContextMenu::Init(), ADDON::Interface_GUIDialogExtendedProgress::Init(), ADDON::Interface_GUIDialogFileBrowser::Init(), ADDON::Interface_GUIDialogKeyboard::Init(), ADDON::Interface_GUIDialogNumeric::Init(), ADDON::Interface_GUIDialogOK::Init(), ADDON::Interface_GUIDialogProgress::Init(), ADDON::Interface_GUIDialogSelect::Init(), ADDON::Interface_GUIDialogTextViewer::Init(), ADDON::Interface_GUIDialogYesNo::Init(), ADDON::Interface_GUIListItem::Init(), ADDON::Interface_GUIWindow::Init(), AddonToKodiFuncTable_Addon::kodi_gui, lock(), AddonToKodiFuncTable_kodi_gui_general::lock, AddonGlobalInterface::toKodi, unlock(), and AddonToKodiFuncTable_kodi_gui_general::unlock.
Referenced by ADDON::Interface_Base::InitInterface().
lock()
void ADDON::Interface_GUIGeneral::lock () static
callback functions from add-on to kodi
Note
For add of new functions use the "_" style to identify direct a add-on callback function. Everything with CamelCase is only for the usage in Kodi only.
The parameter kodiBase is used to become the pointer for a CAddonDll class.
References CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), and m_iAddonGUILockRef.
Referenced by ADDON::Interface_GUIWindow::add_list_item(), ADDON::Interface_GUIWindow::clear_item_list(), ADDON::Interface_GUIWindow::clear_properties(), ADDON::Interface_GUIWindow::clear_property(), ADDON::Interface_GUIWindow::close(), ADDON::Interface_GUIWindow::create(), ADDON::Interface_GUIControlAddonRendering::destroy(), ADDON::Interface_GUIWindow::destroy(), ADDON::Interface_GUIWindow::do_modal(), ADDON::Interface_GUIListItem::get_art(), ADDON::Interface_GUIWindow::get_current_container_id(), ADDON::Interface_GUIWindow::get_current_list_position(), ADDON::Interface_GUIWindow::get_focus_id(), ADDON::Interface_GUIListItem::get_label(), ADDON::Interface_GUIListItem::get_label2(), ADDON::Interface_GUIWindow::get_list_item(), ADDON::Interface_GUIWindow::get_list_size(), ADDON::Interface_GUIListItem::get_path(), ADDON::Interface_GUIListItem::get_property(), ADDON::Interface_GUIWindow::get_property(), ADDON::Interface_GUIWindow::get_property_bool(), ADDON::Interface_GUIWindow::get_property_double(), ADDON::Interface_GUIWindow::get_property_int(), ADDON::Interface_GUIWindow::GetNextAvailableWindowId(), Init(), ADDON::Interface_GUIListItem::is_selected(), ADDON::Interface_GUIWindow::mark_dirty_region(), ADDON::Interface_GUIWindow::remove_list_item(), ADDON::Interface_GUIWindow::remove_list_item_from_position(), ADDON::Interface_GUIListItem::select(), ADDON::Interface_GUIListItem::set_art(), ADDON::Interface_GUIControlAddonRendering::set_callbacks(), ADDON::Interface_GUIWindow::set_callbacks(), ADDON::Interface_GUIWindow::set_container_content(), ADDON::Interface_GUIWindow::set_container_property(), ADDON::Interface_GUIWindow::set_control_label(), ADDON::Interface_GUIWindow::set_control_selected(), ADDON::Interface_GUIWindow::set_control_visible(), ADDON::Interface_GUIWindow::set_current_list_position(), ADDON::Interface_GUIWindow::set_focus_id(), ADDON::Interface_GUIListItem::set_label(), ADDON::Interface_GUIListItem::set_label2(), ADDON::Interface_GUIListItem::set_path(), ADDON::Interface_GUIListItem::set_property(), ADDON::Interface_GUIWindow::set_property(), ADDON::Interface_GUIWindow::set_property_bool(), ADDON::Interface_GUIWindow::set_property_double(), ADDON::Interface_GUIWindow::set_property_int(), and ADDON::Interface_GUIWindow::show().
unlock()
void ADDON::Interface_GUIGeneral::unlock () static
References CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), and m_iAddonGUILockRef.
Referenced by ADDON::Interface_GUIWindow::add_list_item(), ADDON::Interface_GUIWindow::clear_item_list(), ADDON::Interface_GUIWindow::clear_properties(), ADDON::Interface_GUIWindow::clear_property(), ADDON::Interface_GUIWindow::close(), ADDON::Interface_GUIWindow::create(), ADDON::Interface_GUIControlAddonRendering::destroy(), ADDON::Interface_GUIWindow::destroy(), ADDON::Interface_GUIWindow::do_modal(), ADDON::Interface_GUIListItem::get_art(), ADDON::Interface_GUIWindow::get_current_container_id(), ADDON::Interface_GUIWindow::get_current_list_position(), ADDON::Interface_GUIWindow::get_focus_id(), ADDON::Interface_GUIListItem::get_label(), ADDON::Interface_GUIListItem::get_label2(), ADDON::Interface_GUIWindow::get_list_item(), ADDON::Interface_GUIWindow::get_list_size(), ADDON::Interface_GUIListItem::get_path(), ADDON::Interface_GUIListItem::get_property(), ADDON::Interface_GUIWindow::get_property(), ADDON::Interface_GUIWindow::get_property_bool(), ADDON::Interface_GUIWindow::get_property_double(), ADDON::Interface_GUIWindow::get_property_int(), ADDON::Interface_GUIWindow::GetNextAvailableWindowId(), Init(), ADDON::Interface_GUIListItem::is_selected(), ADDON::Interface_GUIWindow::mark_dirty_region(), ADDON::Interface_GUIWindow::remove_list_item(), ADDON::Interface_GUIWindow::remove_list_item_from_position(), ADDON::Interface_GUIListItem::select(), ADDON::Interface_GUIListItem::set_art(), ADDON::Interface_GUIControlAddonRendering::set_callbacks(), ADDON::Interface_GUIWindow::set_callbacks(), ADDON::Interface_GUIWindow::set_container_content(), ADDON::Interface_GUIWindow::set_container_property(), ADDON::Interface_GUIWindow::set_control_label(), ADDON::Interface_GUIWindow::set_control_selected(), ADDON::Interface_GUIWindow::set_control_visible(), ADDON::Interface_GUIWindow::set_current_list_position(), ADDON::Interface_GUIWindow::set_focus_id(), ADDON::Interface_GUIListItem::set_label(), ADDON::Interface_GUIListItem::set_label2(), ADDON::Interface_GUIListItem::set_path(), ADDON::Interface_GUIListItem::set_property(), ADDON::Interface_GUIWindow::set_property(), ADDON::Interface_GUIWindow::set_property_bool(), ADDON::Interface_GUIWindow::set_property_double(), ADDON::Interface_GUIWindow::set_property_int(), and ADDON::Interface_GUIWindow::show().
Member Data Documentation
m_iAddonGUILockRef
int ADDON::Interface_GUIGeneral::m_iAddonGUILockRef = 0 static private
Referenced by lock(), and unlock().
The documentation for this struct was generated from the following files:
interfaces/gui/General.h
gui/General.cpp