Kodi Documentation: LibraryLoader Class Reference
LibraryLoader Class Reference abstract
#include <LibraryLoader.h>
Public Member Functions
LibraryLoader (const std::string &libraryFile)
virtual ~LibraryLoader ()
virtual bool Load ()=0
virtual void Unload ()=0
virtual int ResolveExport (const char *symbol, void **ptr, bool logging=true)=0
virtual int ResolveOrdinal (unsigned long ordinal, void **ptr)
virtual bool IsSystemDll ()=0
virtual HMODULE GetHModule ()=0
virtual bool HasSymbols ()=0
const char * GetName () const
const char * GetFileName () const
const char * GetPath () const
int IncrRef ()
int DecrRef ()
int GetRef ()
Private Member Functions
LibraryLoader (const LibraryLoader &)
LibraryLoader & operator= (const LibraryLoader &)
Private Attributes
std::string m_fileName
std::string m_path
int m_iRefCount
Constructor & Destructor Documentation
LibraryLoader() [1/2]
LibraryLoader::LibraryLoader (const std::string & libraryFile) explicit
References m_fileName, m_iRefCount, and m_path.
~LibraryLoader()
LibraryLoader::~LibraryLoader () virtual default
LibraryLoader() [2/2]
LibraryLoader::LibraryLoader (const LibraryLoader &) private
Member Function Documentation
DecrRef()
int LibraryLoader::DecrRef ()
References m_iRefCount.
Referenced by DllLoaderContainer::ReleaseModule().
GetFileName()
const char * LibraryLoader::GetFileName () const
References m_fileName.
Referenced by Win32DllLoader::Load(), SoLoader::Load(), DllLoaderContainer::LoadModule(), and DllLoaderContainer::ReleaseModule().
GetHModule()
virtual HMODULE LibraryLoader::GetHModule () pure virtual
Implemented in Win32DllLoader, and SoLoader.
Referenced by dllGetModuleHandleA(), dllLoadLibraryExtended(), and Win32DllLoader::NeedsHooking().
GetName()
const char * LibraryLoader::GetName () const
References m_fileName.
Referenced by DllLoaderContainer::ReleaseModule(), Win32DllLoader::ResolveExport(), SoLoader::ResolveExport(), ResolveOrdinal(), Win32DllLoader::Unload(), SoLoader::Unload(), and DllLoaderContainer::UnRegisterDll().
GetPath()
const char * LibraryLoader::GetPath () const
References m_path.
GetRef()
int LibraryLoader::GetRef ()
HasSymbols()
virtual bool LibraryLoader::HasSymbols () pure virtual
Implemented in Win32DllLoader, and SoLoader.
Referenced by DllLoaderContainer::ReleaseModule().
IncrRef()
int LibraryLoader::IncrRef ()
References m_iRefCount.
Referenced by DllLoaderContainer::LoadModule().
IsSystemDll()
virtual bool LibraryLoader::IsSystemDll () pure virtual
Implemented in Win32DllLoader, and SoLoader.
Referenced by dllFreeLibrary(), DllLoaderContainer::LoadModule(), DllLoaderContainer::ReleaseModule(), and DllLoaderContainer::UnRegisterDll().
Load()
virtual bool LibraryLoader::Load () pure virtual
Implemented in Win32DllLoader, and SoLoader.
Referenced by DllLoaderContainer::LoadDll().
operator=()
LibraryLoader & LibraryLoader::operator= (const LibraryLoader &) private
ResolveExport()
virtual int LibraryLoader::ResolveExport (const char * symbol, void ** ptr, bool logging = true) pure virtual
Implemented in Win32DllLoader, and SoLoader.
ResolveOrdinal()
int LibraryLoader::ResolveOrdinal (unsigned long ordinal, void ** ptr) virtual
References GetName(), CLog::Log(), and LOGWARNING.
Unload()
virtual void LibraryLoader::Unload () pure virtual
Implemented in Win32DllLoader, and SoLoader.
Referenced by DllLoaderContainer::ReleaseModule().
Member Data Documentation
m_fileName
std::string LibraryLoader::m_fileName private
Referenced by GetFileName(), GetName(), and LibraryLoader().
m_iRefCount
int LibraryLoader::m_iRefCount private
Referenced by DecrRef(), IncrRef(), and LibraryLoader().
m_path
std::string LibraryLoader::m_path private
Referenced by GetPath(), and LibraryLoader().
The documentation for this class was generated from the following files:
LibraryLoader.h
LibraryLoader.cpp