Kodi Documentation: CGUISliderControl Class Reference
CGUISliderControl Class Reference
Guilib classes » Window Reference » Controls
#include <GUISliderControl.h>
Public Types
enum RangeSelector { RangeSelectorLower = 0 , RangeSelectorUpper = 1 }
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Public Member Functions
CGUISliderControl (int parentID, int controlID, float posX, float posY, float width, float height, const CTextureInfo &backGroundTexture, const CTextureInfo &backGroundTextureDisabled, const CTextureInfo &mibTexture, const CTextureInfo &nibTextureFocus, const CTextureInfo &nibTextureDisabled, int iType, ORIENTATION orientationconst)
~CGUISliderControl () override=default
CGUISliderControl * Clone () const override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
bool OnAction (const CAction &action) override
virtual bool IsActive () const
void AllocResources () override
void FreeResources (bool immediately=false) override
void DynamicResourceAlloc (bool bOnOff) override
void SetInvalid () override
virtual void SetRange (int iStart, int iEnd)
virtual void SetFloatRange (float fStart, float fEnd)
bool OnMessage (CGUIMessage &message) override
bool ProcessSelector (CGUITexture *background, CGUITexture *nib, unsigned int currentTime, float fScale, RangeSelector selector)
void SetRangeSelection (bool rangeSelection)
bool GetRangeSelection () const
void SetRangeSelector (RangeSelector selector)
void SwitchRangeSelector ()
void SetInfo (int iInfo)
void SetPercentage (float iPercent, RangeSelector selector=RangeSelectorLower, bool updateCurrent=false)
float GetPercentage (RangeSelector selector=RangeSelectorLower) const
void SetIntValue (int iValue, RangeSelector selector=RangeSelectorLower, bool updateCurrent=false)
int GetIntValue (RangeSelector selector=RangeSelectorLower) const
void SetFloatValue (float fValue, RangeSelector selector=RangeSelectorLower, bool updateCurrent=false)
float GetFloatValue (RangeSelector selector=RangeSelectorLower) const
void SetIntInterval (int iInterval)
void SetFloatInterval (float fInterval)
void SetType (int iType)
int GetType () const
std::string GetDescription () const override
void SetTextValue (const std::string &textValue)
void SetAction (const std::string &action)
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
virtual void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions)
virtual void DoRender ()
virtual void RenderEx ()
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
React to a mouse event.
virtual void UnfocusFromPoint (const CPoint &point)
Unfocus the control if the given point on screen is not within it's boundary.
virtual int GetID (void) const
virtual void SetID (int id)
int GetParentID () const
virtual bool HasFocus () const
virtual bool IsDynamicallyAllocated ()
virtual bool CanFocus () const
virtual bool IsVisible () const
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
virtual void AssignDepth ()
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetInitialVisibility ()
virtual void SetEnabled (bool bEnable)
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
virtual void QueueAnimation (ANIMATION_TYPE anim)
virtual bool IsAnimating (ANIMATION_TYPE anim)
virtual bool HasAnimation (ANIMATION_TYPE anim)
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void ResetAnimation (ANIMATION_TYPE type)
virtual void ResetAnimations ()
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsGroup () const
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
virtual void SaveStates (std::vector< CControlState > &states)
virtual CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr)
void SetControlStats (GUICONTROLSTATS *controlStats)
virtual void UpdateControlStats ()
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Protected Member Functions
CGUISliderControl (const CGUISliderControl &control)
bool HitTest (const CPoint &point) const override
Used to test whether the point is inside a control.
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
bool UpdateColors (const CGUIListItem *item) override
virtual void Move (int iNumSteps)
virtual void SetFromPosition (const CPoint &point, bool guessSelector=false)
float GetProportion (RangeSelector selector=RangeSelectorLower) const
Get the current position of the slider as a proportion.
void SendClick ()
Send a click message (and/or action) to the app in response to a slider move.
Protected Member Functions inherited from CGUIControl
virtual CPoint GetPosition () const
Return the coordinates of the top left of the control, in the control's parent coordinates.
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool Animate (unsigned int currentTime)
virtual bool CheckAnimation (ANIMATION_TYPE animType)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Attributes
std::unique_ptr< CGUITexture > m_guiBackground
std::unique_ptr< CGUITexture > m_guiBackgroundDisabled
std::unique_ptr< CGUITexture > m_guiSelectorLower
std::unique_ptr< CGUITexture > m_guiSelectorUpper
std::unique_ptr< CGUITexture > m_guiSelectorLowerFocus
std::unique_ptr< CGUITexture > m_guiSelectorUpperFocus
std::unique_ptr< CGUITexture > m_guiSelectorLowerDisabled
std::unique_ptr< CGUITexture > m_guiSelectorUpperDisabled
int m_iType
bool m_rangeSelection
RangeSelector m_currentSelector
std::array< float, 2 > m_percentValues
std::array< int, 2 > m_intValues
int m_iStart
int m_iInterval
int m_iEnd
std::array< float, 2 > m_floatValues
float m_fStart
float m_fInterval
float m_fEnd
int m_iInfoCode
std::string m_textValue
Allows overriding of the text value to be displayed (parent must update when the slider updates)
const SliderAction * m_action
Allows the skin to configure the action of a click on the slider.
bool m_dragging
Whether we're in a (mouse/touch) drag operation or not - some actions are sent only on release.
ORIENTATION m_orientation
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Additional Inherited Members
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Member Enumeration Documentation
RangeSelector
enum CGUISliderControl::RangeSelector
Enumerator
RangeSelectorLower
RangeSelectorUpper
Constructor & Destructor Documentation
CGUISliderControl() [1/2]
CGUISliderControl::CGUISliderControl (int parentID, int controlID, float posX, float posY, float width, float height, const CTextureInfo & backGroundTexture, const CTextureInfo & backGroundTextureDisabled, const CTextureInfo & mibTexture, const CTextureInfo & nibTextureFocus, const CTextureInfo & nibTextureDisabled, int iType, ORIENTATION orientationconst)
References CGUIControl::ControlType, CGUIControl::GUICONTROL_SLIDER, m_action, m_currentSelector, m_dragging, m_fEnd, m_fInterval, m_floatValues, m_fStart, m_iEnd, m_iInfoCode, m_iInterval, m_intValues, m_iStart, m_iType, m_orientation, m_percentValues, m_rangeSelection, and RangeSelectorLower.
~CGUISliderControl()
CGUISliderControl::~CGUISliderControl () override default
CGUISliderControl() [2/2]
CGUISliderControl::CGUISliderControl (const CGUISliderControl & control) protected
Member Function Documentation
AllocResources()
void CGUISliderControl::AllocResources () override virtual
Reimplemented from CGUIControl.
References CGUIControl::AllocResources(), m_guiBackground, m_guiBackgroundDisabled, m_guiSelectorLower, m_guiSelectorLowerDisabled, m_guiSelectorLowerFocus, m_guiSelectorUpper, m_guiSelectorUpperDisabled, and m_guiSelectorUpperFocus.
Referenced by CGUISettingsSliderControl::AllocResources().
Clone()
CGUISliderControl * CGUISliderControl::Clone (void) const inline override virtual
Implements CGUIControl.
DynamicResourceAlloc()
void CGUISliderControl::DynamicResourceAlloc (bool bOnOff) override virtual
Reimplemented from CGUIControl.
References CGUIControl::DynamicResourceAlloc(), m_guiBackground, m_guiBackgroundDisabled, m_guiSelectorLower, m_guiSelectorLowerDisabled, m_guiSelectorLowerFocus, m_guiSelectorUpper, m_guiSelectorUpperDisabled, and m_guiSelectorUpperFocus.
Referenced by CGUISettingsSliderControl::DynamicResourceAlloc().
FreeResources()
void CGUISliderControl::FreeResources (bool immediately = false) override virtual
Reimplemented from CGUIControl.
References CGUIControl::FreeResources(), m_guiBackground, m_guiBackgroundDisabled, m_guiSelectorLower, m_guiSelectorLowerDisabled, m_guiSelectorLowerFocus, m_guiSelectorUpper, m_guiSelectorUpperDisabled, and m_guiSelectorUpperFocus.
Referenced by CGUISettingsSliderControl::FreeResources().
GetDescription()
std::string CGUISliderControl::GetDescription (void) const override virtual
Reimplemented from CGUIControl.
References m_floatValues, m_intValues, m_iType, m_percentValues, m_rangeSelection, m_textValue, MathUtils::round_int(), SLIDER_CONTROL_TYPE_FLOAT, and SLIDER_CONTROL_TYPE_INT.
Referenced by ADDON::Interface_GUIControlSlider::get_description(), CGUISettingsSliderControl::GetDescription(), CGUIDialogSlider::OnMessage(), CGUISettingsSliderControl::ProcessText(), and CGUIDialogSlider::SetSlider().
GetFloatValue()
float CGUISliderControl::GetFloatValue (RangeSelector selector = RangeSelectorLower) const
References m_floatValues, m_intValues, m_iType, m_percentValues, SLIDER_CONTROL_TYPE_FLOAT, and SLIDER_CONTROL_TYPE_INT.
Referenced by ADDON::Interface_GUIControlSettingsSlider::get_float_value(), ADDON::Interface_GUIControlSlider::get_float_value(), GetProportion(), CGUIControlSliderSetting::OnClick(), CGUIControlRangeSetting::OnClick(), KODI::GAME::CDialogGameVolume::OnSliderChange(), CGUIControlButtonSetting::OnSliderChange(), CPlayerController::OnSliderChange(), CGUIControlSliderSetting::Update(), and CGUIControlRangeSetting::Update().
GetIntValue()
int CGUISliderControl::GetIntValue (RangeSelector selector = RangeSelectorLower) const
References m_floatValues, m_intValues, m_iType, m_percentValues, MathUtils::round_int(), SLIDER_CONTROL_TYPE_FLOAT, and SLIDER_CONTROL_TYPE_INT.
Referenced by ADDON::Interface_GUIControlSettingsSlider::get_int_value(), ADDON::Interface_GUIControlSlider::get_int_value(), GetProportion(), CGUIControlSliderSetting::OnClick(), CGUIControlRangeSetting::OnClick(), CGUIControlButtonSetting::OnSliderChange(), CGUIControlSliderSetting::Update(), and CGUIControlRangeSetting::Update().
GetPercentage()
float CGUISliderControl::GetPercentage (RangeSelector selector = RangeSelectorLower) const
References m_percentValues.
Referenced by ADDON::Interface_GUIControlSettingsSlider::get_percentage(), ADDON::Interface_GUIControlSlider::get_percentage(), GetProportion(), and SetFromPosition().
GetProportion()
float CGUISliderControl::GetProportion (RangeSelector selector = RangeSelectorLower) const protected
Get the current position of the slider as a proportion.
Returns
slider position in the range [0,1]
References GetFloatValue(), GetIntValue(), GetPercentage(), m_fEnd, m_fStart, m_iEnd, m_iStart, m_iType, SLIDER_CONTROL_TYPE_FLOAT, and SLIDER_CONTROL_TYPE_INT.
Referenced by ProcessSelector(), and SendClick().
GetRangeSelection()
bool CGUISliderControl::GetRangeSelection () const inline
References m_rangeSelection.
GetType()
int CGUISliderControl::GetType () const inline
References m_iType.
Referenced by CGUIControlRangeSetting::OnClick(), and CGUIControlRangeSetting::Update().
HitTest()
bool CGUISliderControl::HitTest (const CPoint & point) const override protected virtual
Used to test whether the point is inside a control.
Parameters
point location to test
Returns
true if the point is inside the bounds of this control.
See also
SetHitRect
Reimplemented from CGUIControl.
References m_guiBackground, m_guiSelectorLower, m_guiSelectorUpper, and m_rangeSelection.
IsActive()
virtual bool CGUISliderControl::IsActive () const inline virtual
Reimplemented in CGUISettingsSliderControl.
Referenced by OnAction(), Process(), and Render().
Move()
void CGUISliderControl::Move (int iNumSteps) protected virtual
References m_currentSelector, m_fEnd, m_fInterval, m_floatValues, m_fStart, m_iEnd, m_iInterval, m_intValues, m_iStart, m_iType, m_percentValues, SendClick(), SLIDER_CONTROL_TYPE_FLOAT, SLIDER_CONTROL_TYPE_INT, SLIDER_CONTROL_TYPE_PERCENTAGE, SwitchRangeSelector(), and value.
Referenced by OnAction(), and OnMouseEvent().
OnAction()
bool CGUISliderControl::OnAction (const CAction & action) override virtual
Reimplemented from CGUIControl.
References ACTION_MOVE_DOWN, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_MOVE_UP, ACTION_SELECT_ITEM, HORIZONTAL, IsActive(), m_orientation, m_rangeSelection, Move(), CGUIControl::OnAction(), SwitchRangeSelector(), and VERTICAL.
Referenced by CGUISettingsSliderControl::OnAction().
OnMessage()
bool CGUISliderControl::OnMessage (CGUIMessage & message) override virtual
Reimplemented from CGUIControl.
References CGUIMessage::GetControlId(), CGUIControl::GetID(), CGUIMessage::GetMessage(), CGUIMessage::GetParam1(), GUI_MSG_ITEM_SELECT, GUI_MSG_LABEL_RESET, CGUIControl::OnMessage(), RangeSelectorLower, RangeSelectorUpper, and SetPercentage().
OnMouseEvent()
EVENT_RESULT CGUISliderControl::OnMouseEvent (const CPoint & point, const KODI::MOUSE::CMouseEvent & event) override protected virtual
Perform a mouse action.
Mouse actions are sent from the window to all controls, and each control can react based on the event and location of the actions.
Parameters
point the location in transformed skin coordinates from the upper left corner of the parent control.
event the mouse event to perform
Returns
EVENT_RESULT corresponding to whether the control handles this event
See also
SendMouseEvent, HitTest, CanFocusFromPoint, CMouseEvent
Reimplemented from CGUIControl.
References ACTION_GESTURE_ABORT, ACTION_GESTURE_BEGIN, ACTION_GESTURE_END, ACTION_GESTURE_NOTIFY, ACTION_GESTURE_PAN, ACTION_MOUSE_DRAG, ACTION_MOUSE_DRAG_END, ACTION_MOUSE_LEFT_CLICK, ACTION_MOUSE_WHEEL_DOWN, ACTION_MOUSE_WHEEL_UP, DRAG, DRAG_END, EVENT_RESULT_HANDLED, EVENT_RESULT_PAN_HORIZONTAL_WITHOUT_INERTIA, EVENT_RESULT_UNHANDLED, CGUIControl::GetID(), CGUIControl::GetParentID(), GUI_MSG_EXCLUSIVE_MOUSE, m_dragging, m_guiBackground, KODI::MOUSE::CMouseEvent::m_id, KODI::MOUSE::CMouseEvent::m_state, Move(), CGUIControl::SendWindowMessage(), and SetFromPosition().
Referenced by CGUISettingsSliderControl::OnMouseEvent().
Process()
void CGUISliderControl::Process (unsigned int currentTime, CDirtyRegionList & dirtyregions) override virtual
Reimplemented from CGUIControl.
References INFO::DEFAULT_CONTEXT, SliderAction::fireOnDrag, CServiceBroker::GetGUI(), CGUITexture::GetTextureHeight(), CGUITexture::GetTextureWidth(), HORIZONTAL, SliderAction::infoCode, IsActive(), CGUIControl::IsDisabled(), m_action, CGUIControl::m_bHasFocus, m_currentSelector, m_dragging, m_guiBackground, m_guiBackgroundDisabled, m_guiSelectorLower, m_guiSelectorLowerDisabled, m_guiSelectorLowerFocus, m_guiSelectorUpper, m_guiSelectorUpperDisabled, m_guiSelectorUpperFocus, CGUIControl::m_height, m_iInfoCode, m_orientation, CGUIControl::m_posX, CGUIControl::m_posY, m_rangeSelection, CGUIControl::m_width, CGUIControl::MarkDirtyRegion(), CGUITexture::Process(), CGUIControl::Process(), ProcessSelector(), RangeSelectorLower, RangeSelectorUpper, CGUITexture::SetHeight(), SetIntValue(), CGUITexture::SetPosition(), and CGUITexture::SetWidth().
Referenced by CGUISettingsSliderControl::Process().
ProcessSelector()
bool CGUISliderControl::ProcessSelector (CGUITexture * background, CGUITexture * nib, unsigned int currentTime, float fScale, RangeSelector selector)
References CAspectRatio::align, CAspectRatio::AR_KEEP, ASPECT_ALIGN_LEFT, ASPECT_ALIGNY_CENTER, CGUITexture::GetHeight(), GetProportion(), CGUITexture::GetRenderRect(), CGUITexture::GetTextureHeight(), CGUITexture::GetTextureWidth(), CGUITexture::GetWidth(), CGUITexture::GetXPosition(), CGUITexture::GetYPosition(), CRectGen< T >::Height(), HORIZONTAL, CGUIControl::m_height, m_orientation, CGUIControl::m_width, CGUITexture::Process(), CGUITexture::SetAspectRatio(), CGUITexture::SetHeight(), CGUITexture::SetPosition(), CGUITexture::SetWidth(), and CRectGen< T >::Width().
Referenced by Process().
Render()
void CGUISliderControl::Render () override virtual
Reimplemented from CGUIControl.
References IsActive(), CGUIControl::IsDisabled(), CGUIControl::m_bHasFocus, m_currentSelector, m_guiBackground, m_guiBackgroundDisabled, m_guiSelectorLower, m_guiSelectorLowerDisabled, m_guiSelectorLowerFocus, m_guiSelectorUpper, m_guiSelectorUpperDisabled, m_guiSelectorUpperFocus, m_rangeSelection, RangeSelectorLower, RangeSelectorUpper, CGUIControl::Render(), and CGUITexture::Render().
Referenced by CGUISettingsSliderControl::Render().
SendClick()
void CGUISliderControl::SendClick () protected
Send a click message (and/or action) to the app in response to a slider move.
References SliderAction::fireOnDrag, SliderAction::formatString, CServiceBroker::GetGUI(), CGUIControl::GetID(), CGUIControl::GetParentID(), GetProportion(), CGUIComponent::GetWindowManager(), GUI_MSG_EXECUTE, m_action, CGUIControl::m_controlID, m_dragging, CGUIControl::m_parentID, MathUtils::round_int(), SEND_CLICK_MESSAGE, CGUIWindowManager::SendMessage(), and CGUIMessage::SetStringParam().
Referenced by Move(), and SetFromPosition().
SetAction()
void CGUISliderControl::SetAction (const std::string & action)
References actions, and m_action.
SetFloatInterval()
void CGUISliderControl::SetFloatInterval (float fInterval)
References m_fInterval, m_iInterval, m_iType, and SLIDER_CONTROL_TYPE_FLOAT.
Referenced by CGUIControlRangeSetting::CGUIControlRangeSetting(), CGUIControlSliderSetting::CGUIControlSliderSetting(), ADDON::Interface_GUIControlSettingsSlider::set_float_interval(), ADDON::Interface_GUIControlSlider::set_float_interval(), and CGUIDialogSlider::SetSlider().
SetFloatRange()
void CGUISliderControl::SetFloatRange (float fStart, float fEnd) virtual
References m_fEnd, m_floatValues, m_fStart, m_iType, SetRange(), and SLIDER_CONTROL_TYPE_INT.
Referenced by CGUIControlRangeSetting::CGUIControlRangeSetting(), CGUIControlSliderSetting::CGUIControlSliderSetting(), ADDON::Interface_GUIControlSettingsSlider::set_float_range(), ADDON::Interface_GUIControlSlider::set_float_range(), SetRange(), and CGUIDialogSlider::SetSlider().
SetFloatValue()
void CGUISliderControl::SetFloatValue (float fValue, RangeSelector selector = RangeSelectorLower, bool updateCurrent = false)
References m_currentSelector, m_fEnd, m_floatValues, m_fStart, m_iType, m_rangeSelection, RangeSelectorLower, RangeSelectorUpper, SetIntValue(), SetPercentage(), SLIDER_CONTROL_TYPE_FLOAT, and SLIDER_CONTROL_TYPE_INT.
Referenced by ADDON::Interface_GUIControlSettingsSlider::set_float_value(), ADDON::Interface_GUIControlSlider::set_float_value(), SetFromPosition(), SetIntValue(), CGUIDialogSlider::SetSlider(), CGUIControlSliderSetting::Update(), and CGUIControlRangeSetting::Update().
SetFromPosition()
void CGUISliderControl::SetFromPosition (const CPoint & point, bool guessSelector = false) protected virtual
References GetPercentage(), HORIZONTAL, m_currentSelector, m_fEnd, m_fInterval, m_fStart, m_guiBackground, m_iEnd, m_iStart, m_iType, m_orientation, m_rangeSelection, RangeSelectorLower, RangeSelectorUpper, MathUtils::RoundF(), SendClick(), SetFloatValue(), SetIntValue(), SetPercentage(), SLIDER_CONTROL_TYPE_FLOAT, SLIDER_CONTROL_TYPE_INT, SLIDER_CONTROL_TYPE_PERCENTAGE, CPointGen< T >::x, and CPointGen< T >::y.
Referenced by OnMouseEvent().
SetInfo()
void CGUISliderControl::SetInfo (int iInfo)
References m_iInfoCode.
SetIntInterval()
void CGUISliderControl::SetIntInterval (int iInterval)
References m_fInterval, m_iInterval, m_iType, and SLIDER_CONTROL_TYPE_FLOAT.
Referenced by CGUIControlRangeSetting::CGUIControlRangeSetting(), CGUIControlSliderSetting::CGUIControlSliderSetting(), ADDON::Interface_GUIControlSettingsSlider::set_int_interval(), and ADDON::Interface_GUIControlSlider::set_int_interval().
SetIntValue()
void CGUISliderControl::SetIntValue (int iValue, RangeSelector selector = RangeSelectorLower, bool updateCurrent = false)
References m_currentSelector, m_iEnd, m_intValues, m_iStart, m_iType, m_rangeSelection, RangeSelectorLower, RangeSelectorUpper, SetFloatValue(), SetPercentage(), SLIDER_CONTROL_TYPE_FLOAT, and SLIDER_CONTROL_TYPE_INT.
Referenced by Process(), ADDON::Interface_GUIControlSettingsSlider::set_int_value(), ADDON::Interface_GUIControlSlider::set_int_value(), SetFloatValue(), SetFromPosition(), CGUIControlSliderSetting::Update(), and CGUIControlRangeSetting::Update().
SetInvalid()
void CGUISliderControl::SetInvalid () override virtual
Reimplemented from CGUIControl.
References m_guiBackground, m_guiBackgroundDisabled, m_guiSelectorLower, m_guiSelectorLowerDisabled, m_guiSelectorLowerFocus, m_guiSelectorUpper, m_guiSelectorUpperDisabled, m_guiSelectorUpperFocus, and CGUIControl::SetInvalid().
Referenced by CGUISettingsSliderControl::SetHeight(), CGUISettingsSliderControl::SetInvalid(), CGUISettingsSliderControl::SetPosition(), SetRangeSelection(), SetRangeSelector(), and CGUISettingsSliderControl::SetWidth().
SetPercentage()
void CGUISliderControl::SetPercentage (float iPercent, RangeSelector selector = RangeSelectorLower, bool updateCurrent = false)
References m_currentSelector, m_percentValues, m_rangeSelection, CGUIControl::MarkDirtyRegion(), RangeSelectorLower, and RangeSelectorUpper.
Referenced by OnMessage(), ADDON::Interface_GUIControlSettingsSlider::set_percentage(), ADDON::Interface_GUIControlSlider::set_percentage(), SetFloatValue(), SetFromPosition(), and SetIntValue().
SetRange()
void CGUISliderControl::SetRange (int iStart, int iEnd) virtual
References m_iEnd, m_intValues, m_iStart, m_iType, SetFloatRange(), and SLIDER_CONTROL_TYPE_FLOAT.
Referenced by CGUIControlRangeSetting::CGUIControlRangeSetting(), CGUIControlSliderSetting::CGUIControlSliderSetting(), ADDON::Interface_GUIControlSettingsSlider::set_int_range(), ADDON::Interface_GUIControlSlider::set_int_range(), and SetFloatRange().
SetRangeSelection()
void CGUISliderControl::SetRangeSelection (bool rangeSelection)
References m_rangeSelection, RangeSelectorLower, SetInvalid(), and SetRangeSelector().
Referenced by CGUIControlRangeSetting::CGUIControlRangeSetting().
SetRangeSelector()
void CGUISliderControl::SetRangeSelector (RangeSelector selector)
References m_currentSelector, and SetInvalid().
Referenced by SetRangeSelection(), and SwitchRangeSelector().
SetTextValue()
void CGUISliderControl::SetTextValue (const std::string & textValue) inline
References m_textValue.
Referenced by CGUIControlButtonSetting::OnSliderChange(), CPlayerController::OnSliderChange(), CGUIControlSliderSetting::Update(), and CGUIControlRangeSetting::Update().
SetType()
void CGUISliderControl::SetType (int iType) inline
References m_iType.
Referenced by CGUIControlRangeSetting::CGUIControlRangeSetting(), CGUIControlSliderSetting::CGUIControlSliderSetting(), ADDON::Interface_GUIControlSettingsSlider::set_float_range(), ADDON::Interface_GUIControlSlider::set_float_range(), ADDON::Interface_GUIControlSettingsSlider::set_float_value(), ADDON::Interface_GUIControlSlider::set_float_value(), ADDON::Interface_GUIControlSettingsSlider::set_int_range(), ADDON::Interface_GUIControlSlider::set_int_range(), ADDON::Interface_GUIControlSettingsSlider::set_int_value(), ADDON::Interface_GUIControlSlider::set_int_value(), ADDON::Interface_GUIControlSettingsSlider::set_percentage(), ADDON::Interface_GUIControlSlider::set_percentage(), and CGUIDialogSlider::SetSlider().
SwitchRangeSelector()
void CGUISliderControl::SwitchRangeSelector ()
References m_currentSelector, RangeSelectorLower, RangeSelectorUpper, and SetRangeSelector().
Referenced by Move(), CGUISettingsSliderControl::OnAction(), and OnAction().
UpdateColors()
bool CGUISliderControl::UpdateColors (const CGUIListItem * item) override protected virtual
Reimplemented from CGUIControl.
References CGUIControl::m_diffuseColor, m_guiBackground, m_guiBackgroundDisabled, m_guiSelectorLower, m_guiSelectorLowerDisabled, m_guiSelectorLowerFocus, m_guiSelectorUpper, m_guiSelectorUpperDisabled, m_guiSelectorUpperFocus, and CGUIControl::UpdateColors().
Referenced by CGUISettingsSliderControl::UpdateColors().
Member Data Documentation
m_action
const SliderAction* CGUISliderControl::m_action protected
Allows the skin to configure the action of a click on the slider.
See also
SendClick
Referenced by CGUISliderControl(), Process(), SendClick(), and SetAction().
m_currentSelector
RangeSelector CGUISliderControl::m_currentSelector protected
Referenced by CGUISliderControl(), Move(), CGUISettingsSliderControl::OnAction(), Process(), Render(), SetFloatValue(), SetFromPosition(), SetIntValue(), SetPercentage(), SetRangeSelector(), and SwitchRangeSelector().
m_dragging
bool CGUISliderControl::m_dragging protected
Whether we're in a (mouse/touch) drag operation or not - some actions are sent only on release.
Referenced by CGUISliderControl(), OnMouseEvent(), Process(), and SendClick().
m_fEnd
float CGUISliderControl::m_fEnd protected
Referenced by CGUISliderControl(), GetProportion(), Move(), SetFloatRange(), SetFloatValue(), and SetFromPosition().
m_fInterval
float CGUISliderControl::m_fInterval protected
Referenced by CGUISliderControl(), Move(), SetFloatInterval(), SetFromPosition(), and SetIntInterval().
m_floatValues
std::array<float, 2> CGUISliderControl::m_floatValues protected
Referenced by CGUISliderControl(), GetDescription(), GetFloatValue(), GetIntValue(), Move(), SetFloatRange(), and SetFloatValue().
m_fStart
float CGUISliderControl::m_fStart protected
Referenced by CGUISliderControl(), GetProportion(), Move(), SetFloatRange(), SetFloatValue(), and SetFromPosition().
m_guiBackground
std::unique_ptr<CGUITexture> CGUISliderControl::m_guiBackground protected
Referenced by AllocResources(), DynamicResourceAlloc(), FreeResources(), HitTest(), OnMouseEvent(), Process(), Render(), SetFromPosition(), SetInvalid(), and UpdateColors().
m_guiBackgroundDisabled
std::unique_ptr<CGUITexture> CGUISliderControl::m_guiBackgroundDisabled protected
Referenced by AllocResources(), DynamicResourceAlloc(), FreeResources(), Process(), Render(), SetInvalid(), and UpdateColors().
m_guiSelectorLower
std::unique_ptr<CGUITexture> CGUISliderControl::m_guiSelectorLower protected
Referenced by AllocResources(), DynamicResourceAlloc(), FreeResources(), HitTest(), Process(), Render(), SetInvalid(), and UpdateColors().
m_guiSelectorLowerDisabled
std::unique_ptr<CGUITexture> CGUISliderControl::m_guiSelectorLowerDisabled protected
Referenced by AllocResources(), DynamicResourceAlloc(), FreeResources(), Process(), Render(), SetInvalid(), and UpdateColors().
m_guiSelectorLowerFocus
std::unique_ptr<CGUITexture> CGUISliderControl::m_guiSelectorLowerFocus protected
Referenced by AllocResources(), DynamicResourceAlloc(), FreeResources(), Process(), Render(), SetInvalid(), and UpdateColors().
m_guiSelectorUpper
std::unique_ptr<CGUITexture> CGUISliderControl::m_guiSelectorUpper protected
Referenced by AllocResources(), DynamicResourceAlloc(), FreeResources(), HitTest(), Process(), Render(), SetInvalid(), and UpdateColors().
m_guiSelectorUpperDisabled
std::unique_ptr<CGUITexture> CGUISliderControl::m_guiSelectorUpperDisabled protected
Referenced by AllocResources(), DynamicResourceAlloc(), FreeResources(), Process(), Render(), SetInvalid(), and UpdateColors().
m_guiSelectorUpperFocus
std::unique_ptr<CGUITexture> CGUISliderControl::m_guiSelectorUpperFocus protected
Referenced by AllocResources(), DynamicResourceAlloc(), FreeResources(), Process(), Render(), SetInvalid(), and UpdateColors().
m_iEnd
int CGUISliderControl::m_iEnd protected
Referenced by CGUISliderControl(), GetProportion(), Move(), SetFromPosition(), SetIntValue(), and SetRange().
m_iInfoCode
int CGUISliderControl::m_iInfoCode protected
Referenced by CGUISliderControl(), Process(), and SetInfo().
m_iInterval
int CGUISliderControl::m_iInterval protected
Referenced by CGUISliderControl(), Move(), SetFloatInterval(), and SetIntInterval().
m_intValues
std::array<int, 2> CGUISliderControl::m_intValues protected
Referenced by CGUISliderControl(), GetDescription(), GetFloatValue(), GetIntValue(), Move(), SetIntValue(), and SetRange().
m_iStart
int CGUISliderControl::m_iStart protected
Referenced by CGUISliderControl(), GetProportion(), Move(), SetFromPosition(), SetIntValue(), and SetRange().
m_iType
int CGUISliderControl::m_iType protected
Referenced by CGUISliderControl(), GetDescription(), GetFloatValue(), GetIntValue(), GetProportion(), GetType(), Move(), SetFloatInterval(), SetFloatRange(), SetFloatValue(), SetFromPosition(), SetIntInterval(), SetIntValue(), SetRange(), and SetType().
m_orientation
ORIENTATION CGUISliderControl::m_orientation protected
Referenced by CGUISliderControl(), OnAction(), Process(), ProcessSelector(), and SetFromPosition().
m_percentValues
std::array<float, 2> CGUISliderControl::m_percentValues protected
Referenced by CGUISliderControl(), GetDescription(), GetFloatValue(), GetIntValue(), GetPercentage(), Move(), and SetPercentage().
m_rangeSelection
bool CGUISliderControl::m_rangeSelection protected
Referenced by CGUISliderControl(), GetDescription(), GetRangeSelection(), HitTest(), CGUISettingsSliderControl::OnAction(), OnAction(), Process(), Render(), SetFloatValue(), SetFromPosition(), SetIntValue(), SetPercentage(), and SetRangeSelection().
m_textValue
std::string CGUISliderControl::m_textValue protected
Allows overriding of the text value to be displayed (parent must update when the slider updates)
Referenced by GetDescription(), and SetTextValue().
The documentation for this class was generated from the following files:
GUISliderControl.h
GUISliderControl.cpp