Kodi Documentation: CGUIDialogVideoManagerVersions Class Reference
CGUIDialogVideoManagerVersions Class Reference
#include <GUIDialogVideoManagerVersions.h>
Public Member Functions
CGUIDialogVideoManagerVersions ()
~CGUIDialogVideoManagerVersions () override=default
void SetVideoAsset (const std::shared_ptr< CFileItem > &item) override
Public Member Functions inherited from CGUIDialogVideoManager
CGUIDialogVideoManager (int windowId)
~CGUIDialogVideoManager () override=default
virtual void SetSelectedVideoAsset (const std::shared_ptr< CFileItem > &asset)
virtual bool HasUpdatedItems () const
Public Member Functions inherited from CGUIDialog
CGUIDialog (int id, const std::string &xmlFile, DialogModalityType modalityType=DialogModalityType::MODAL)
~CGUIDialog (void) override
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void Render () override
void Open (const std::string &param="")
void Open (bool bProcessRenderLoop, const std::string &param="")
bool OnBack (int actionID) override
bool IsDialogRunning () const override
bool IsDialog () const override
bool IsModalDialog () const override
virtual DialogModalityType GetModalityType () const
void SetAutoClose (unsigned int timeoutMs)
void ResetAutoClose (void)
void CancelAutoClose (void)
bool IsAutoClosed (void) const
void SetSound (bool OnOff)
bool IsSoundEnabled () const override
Public Member Functions inherited from CGUIWindow
CGUIWindow (int id, const std::string &xmlFile)
~CGUIWindow (void) override
bool Initialize ()
bool Load (const std::string &strFileName, bool bContainsPath=false)
void CenterWindow ()
void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void DoRender () override
Main render function, called every frame. Window classes should override this only if they need to alter how something is rendered. General updating on a per-frame basis should be handled in FrameMove instead, as DoRender is not necessarily re-entrant.
void AfterRender ()
Do any post render activities. Check if window closing animation is finished and finalize window closing.
virtual void FrameMove ()
Main update function, called every frame prior to rendering Any window that requires updating on a frame by frame basis (such as to maintain timers and the like) should override this function.
void Close (bool forceClose=false, int nextWindowID=0, bool enableSound=true, bool bWait=true)
bool OnAction (const CAction &action) override
virtual bool OnInfo (int actionID)
virtual void ClearBackground ()
Clear the background (if necessary) prior to rendering the window.
bool OnMove (int fromControl, int moveAction)
bool OnMessage (CGUIMessage &message) override
bool ControlGroupHasFocus (int groupID, int controlID)
void SetID (int id) override
virtual bool HasID (int controlID) const
const std::vector< int > & GetIDRange () const
int GetPreviousWindow ()
CRect GetScaledBounds () const
void ClearAll () override
virtual void AllocResources (bool forceLoad=false)
void FreeResources (bool forceUnLoad=false) override
void DynamicResourceAlloc (bool bOnOff) override
virtual bool IsMediaWindow () const
virtual bool HasListItems () const
virtual CFileItemPtr GetCurrentListItem (int offset=0)
virtual int GetViewContainerID () const
virtual int GetViewCount () const
virtual bool CanBeActivated () const
virtual bool IsActive () const
void SetCoordsRes (const RESOLUTION_INFO &res)
const RESOLUTION_INFO & GetCoordsRes () const
void SetLoadType (LOAD_TYPE loadType)
LOAD_TYPE GetLoadType ()
int GetRenderOrder ()
void SetInitialVisibility () override
bool IsVisible () const override
virtual bool HasVisibleControls ()
bool IsAnimating (ANIMATION_TYPE animType) override
bool IsCustom () const
Return if the window is a custom window.
void SetCustom (bool custom)
Mark this window as custom window.
void DisableAnimations ()
virtual void ResetControlStates ()
void UpdateControlStats () override
void SetRunActionsManually ()
void RunLoadActions () const
void RunUnloadActions () const
void SetProperty (const std::string &key, const CVariant &value)
Set a property Sets the value of a property referenced by a key.
CVariant GetProperty (const std::string &key) const
Retrieve a property.
void ClearProperties ()
Clear a all the window's properties.
bool HasSaveLastControl () const
void AllocResources () override
Public Member Functions inherited from CGUIControlGroup
CGUIControlGroup ()
CGUIControlGroup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlGroup (const CGUIControlGroup &from)
~CGUIControlGroup (void) override
CGUIControlGroup * Clone () const override
void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions) override
void RenderEx () override
virtual bool SendControlMessage (CGUIMessage &message)
bool HasFocus () const override
bool CanFocus () const override
void AssignDepth () override
EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
React to a mouse event.
void UnfocusFromPoint (const CPoint &point) override
Unfocus the control if the given point on screen is not within it's boundary.
bool HasAnimation (ANIMATION_TYPE anim) override
void QueueAnimation (ANIMATION_TYPE anim) override
void ResetAnimation (ANIMATION_TYPE anim) override
void ResetAnimations () override
int GetFocusedControlID () const
CGUIControl * GetFocusedControl () const
virtual CGUIControl * GetFirstFocusableControl (int id)
virtual void AddControl (CGUIControl *control, int position=-1)
bool InsertControl (CGUIControl *control, const CGUIControl *insertPoint)
virtual bool RemoveControl (const CGUIControl *control)
void SetDefaultControl (int id, bool always)
void SetRenderFocusedLast (bool renderLast)
void SaveStates (std::vector< CControlState > &states) override
bool IsGroup () const override
Public Member Functions inherited from CGUIControlLookup
CGUIControlLookup ()=default
CGUIControlLookup (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControlLookup (const CGUIControlLookup &from)
~CGUIControlLookup (void) override=default
CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr) override
Public Member Functions inherited from CGUIControl
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
bool HasProcessed () const
Returns whether or not we have processed.
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual int GetID (void) const
int GetParentID () const
virtual bool IsDynamicallyAllocated ()
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescription () const
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
void SetControlStats (GUICONTROLSTATS *controlStats)
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Static Public Member Functions
static bool ProcessVideoVersion (VideoDbContentType itemType, int dbId)
static bool ManageVideoVersions (const std::shared_ptr< CFileItem > &item)
Open the Manage Versions dialog for a video.
Protected Member Functions
bool OnMessage (CGUIMessage &message) override
VideoAssetType GetVideoAssetType () override
int GetHeadingId () override
void Clear () override
void Refresh () override
void UpdateButtons () override
void Remove () override
Protected Member Functions inherited from CGUIDialogVideoManager
void OnInitWindow () override
Called on window open.
void OnDeinitWindow (int nextWindowID) override
bool OnAction (const CAction &action) override
virtual void UpdateAssetsList ()
virtual void Play ()
virtual void Rename ()
virtual void ChooseArt ()
void DisableRemove ()
void EnableRemove ()
void UpdateControls ()
void AppendItemFolderToFileBrowserSources (std::vector< CMediaSource > &sources)
void RefreshSelectedVideoAsset ()
Protected Member Functions inherited from CGUIDialog
bool Load (TiXmlElement *pRootElement) override
Loads the window from the given XML element.
void SetDefaults () override
void OnWindowLoaded () override
virtual void UpdateVisibility ()
virtual void Open_Internal (bool bProcessRenderLoop, const std::string &param="")
void ProcessRenderLoop (bool renderOnly=false)
Protected Member Functions inherited from CGUIWindow
EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event) override
Perform a mouse action.
virtual bool LoadXML (const std::string &strPath, const std::string &strLowerPath)
Load the window XML from the given path.
virtual std::unique_ptr< TiXmlElement > Prepare (const std::unique_ptr< TiXmlElement > &rootElement)
Prepare the XML for load.
bool NeedLoad () const
Check if window needs a (re)load. The window need to be (re)loaded when window is not loaded or include conditions values were changed.
virtual void OnWindowUnload ()
void Close_Internal (bool forceClose=false, int nextWindowID=0, bool enableSound=true)
EVENT_RESULT OnMouseAction (const CAction &action)
bool Animate (unsigned int currentTime) override
bool CheckAnimation (ANIMATION_TYPE animType) override
virtual void SaveControlStates ()
virtual void RestoreControlStates ()
void OnEditChanged (int id, std::string &text)
bool SendMessage (int message, int id, int param1=0, int param2=0)
void LoadControl (TiXmlElement *pControl, CGUIControlGroup *pGroup, const CRect &rect)
CPoint GetPosition () const override
Grabs the window's top,left position in skin coordinates The window origin may change based on <origin> tag conditions in the skin.
Protected Member Functions inherited from CGUIControlLookup
bool IsValidControl (const CGUIControl *control) const
Check whether a given control is valid Runs through controls and returns whether this control is valid. Only functional for controls with non-zero id.
std::pair< LookupMap::const_iterator, LookupMap::const_iterator > GetLookupControls (int controlId) const
void AddLookup (CGUIControl *control)
void RemoveLookup (CGUIControl *control)
void RemoveLookup ()
const LookupMap & GetLookup () const
void ClearLookup ()
Protected Member Functions inherited from CGUIControl
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Private Member Functions
void SetDefaultVideoVersion (const CFileItem &version)
bool AddVideoVersion ()
Prompt the user to select a file / movie to add as version.
void SetDefault ()
void UpdateDefaultVideoVersionSelection ()
bool AddVideoVersionFilePicker ()
Use a file picker to select a file to add as a new version of a movie.
bool AddSimilarMovieAsVersion (const std::shared_ptr< CFileItem > &itemMovie)
Convert the movie into a version.
Static Private Member Functions
static bool ChooseVideoAndConvertToVideoVersion (CFileItemList &items, VideoDbContentType itemType, const std::string &mediaType, int dbId, CVideoDatabase &videoDb, MediaRole role)
Ask the user to choose an item from the list of items, the version type of the item, and perform the version conversion according to the role parameter.
static bool GetSimilarMovies (const std::shared_ptr< CFileItem > &item, CFileItemList &list, CVideoDatabase &videoDb)
Populates a list of movies of the library that are similar to the item provided as parameter.
static bool GetAllOtherMovies (const std::shared_ptr< CFileItem > &item, CFileItemList &list, CVideoDatabase &videoDb)
Populates a list with all movies of the libray, excluding the item provided as parameter.
static bool PostProcessList (CFileItemList &list, int dbId)
Shared post processing of lists after extraction and before display.
Private Attributes
std::shared_ptr< CFileItem > m_defaultVideoVersion
Additional Inherited Members
Public Types inherited from CGUIWindow
enum LOAD_TYPE { LOAD_EVERY_TIME , LOAD_ON_GUI_INIT , KEEP_IN_MEMORY }
Public Types inherited from CGUIControl
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Protected Types inherited from CGUIControlGroup
typedef std::vector< CGUIControl * >::iterator iControls
typedef std::vector< CGUIControl * >::const_iterator ciControls
typedef std::vector< CGUIControl * >::reverse_iterator rControls
typedef std::vector< CGUIControl * >::const_reverse_iterator crControls
Protected Types inherited from CGUIControlLookup
typedef std::multimap< int, CGUIControl * > LookupMap
Static Protected Member Functions inherited from CGUIDialogVideoManager
static int ChooseVideoAsset (const std::shared_ptr< CFileItem > &item, VideoAssetType assetType, const std::string &defaultName)
Protected Attributes inherited from CGUIDialogVideoManager
CVideoDatabase m_database
std::shared_ptr< CFileItem > m_videoAsset
std::unique_ptr< CFileItemList > m_videoAssetsList
std::shared_ptr< CFileItem > m_selectedVideoAsset
bool m_hasUpdatedItems {false}
Protected Attributes inherited from CGUIDialog
bool m_wasRunning
true if we were running during the last DoProcess()
bool m_autoClosing
bool m_enableSound
unsigned int m_showStartTime
unsigned int m_showDuration
bool m_bAutoClosed
DialogModalityType m_modalityType
Protected Attributes inherited from CGUIWindow
std::vector< int > m_idRange
RESOLUTION_INFO m_coordsRes
bool m_needsScaling
bool m_windowLoaded
LOAD_TYPE m_loadType
bool m_dynamicResourceAlloc
bool m_closing
bool m_active
KODI::GUILIB::GUIINFO::CGUIInfoColor m_clearBackground
int m_renderOrder
std::vector< COrigin > m_origins
int m_lastControlID
std::vector< CControlState > m_controlStates
int m_previousWindow
bool m_animationsEnabled
CGUIAction m_loadActions
CGUIAction m_unloadActions
std::unique_ptr< TiXmlElement > m_windowXMLRootElement
window root xml definition after resolving any skin includes. Stored to avoid parsing the XML every time the window is loaded.
bool m_manualRunActions
int m_exclusiveMouseControl
id of child control that wishes to receive all mouse events
int m_menuControlID
int m_menuLastFocusedControlID
bool m_custom
Protected Attributes inherited from CGUIControlGroup
std::vector< CGUIControl * > m_children
int m_defaultControl
bool m_defaultAlways
int m_focusedControl
bool m_renderFocusedLast
Protected Attributes inherited from CGUIControl
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Static Protected Attributes inherited from CGUIControl
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Constructor & Destructor Documentation
CGUIDialogVideoManagerVersions()
CGUIDialogVideoManagerVersions::CGUIDialogVideoManagerVersions ()
~CGUIDialogVideoManagerVersions()
CGUIDialogVideoManagerVersions::~CGUIDialogVideoManagerVersions () override default
Member Function Documentation
AddSimilarMovieAsVersion()
bool CGUIDialogVideoManagerVersions::AddSimilarMovieAsVersion (const std::shared_ptr< CFileItem > & itemMovie) private
Convert the movie into a version.
Parameters
itemMovie Movie to convert
Returns
True for success, false otherwse
References CGUIDialogVideoManager::ChooseVideoAsset(), CVideoDatabase::ConvertVideoToVersion(), LOGERROR, CGUIDialogVideoManager::m_videoAsset, MOVIES, CVideoDatabase::Open(), CGUIDialogOK::ShowAndGetInput(), and VERSION.
Referenced by AddVideoVersion().
AddVideoVersion()
bool CGUIDialogVideoManagerVersions::AddVideoVersion () private
Prompt the user to select a file / movie to add as version.
Returns
true if a version was added, false otherwise.
References AddSimilarMovieAsVersion(), AddVideoVersionFilePicker(), ChooseVideoAndConvertToVideoVersion(), CGUIDialogYesNo::DIALOG_RESULT_CANCEL, CGUIDialogYesNo::DIALOG_RESULT_CUSTOM, CGUIDialogYesNo::DIALOG_RESULT_NO, CGUIDialogYesNo::DIALOG_RESULT_YES, GetAllOtherMovies(), CServiceBroker::GetGUI(), GetSimilarMovies(), CFileItem::GetVideoContentType(), CFileItem::GetVideoInfoTag(), CGUIComponent::GetWindowManager(), CBackgroundInfoLoader::IsLoading(), CBackgroundInfoLoader::Load(), LOGERROR, CGUIDialogVideoManager::m_videoAsset, CGUIDialogYesNo::NO_TIMEOUT, CVideoDatabase::Open(), Parent, CGUIDialogYesNo::ShowAndGetInput(), CFileItemList::Size(), CBackgroundInfoLoader::StopThread(), and WINDOW_DIALOG_SELECT.
Referenced by OnMessage().
AddVideoVersionFilePicker()
bool CGUIDialogVideoManagerVersions::AddVideoVersionFilePicker () private
Use a file picker to select a file to add as a new version of a movie.
Returns
True when a version was added, false otherwise
References CVideoDatabase::AddVideoAsset(), CGUIDialogVideoManager::AppendItemFolderToFileBrowserSources(), CGUIDialogVideoManager::ChooseVideoAsset(), CVideoDatabase::ConvertVideoToVersion(), EXTRA, g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetFileExtensionProvider(), CDVDFileInfo::GetFileStreamDetails(), CMediaSourceSettings::GetInstance(), CMediaManager::GetLocalDrives(), CServiceBroker::GetMediaManager(), CVideoDatabase::GetMovieTitle(), CMediaManager::GetNetworkLocations(), CServiceBroker::GetSettingsComponent(), CMediaSourceSettings::GetSources(), CVideoDatabase::GetVideoVersionInfo(), CVideoDatabase::GetVideoVersions(), CVideoDatabase::IsDefaultVideoVersion(), LOGDEBUG, LOGERROR, CGUIDialogVideoManager::m_database, CGUIDialogVideoManager::m_videoAsset, MediaTypeMovie, CSettings::SETTING_MYVIDEOS_EXTRACTFLAGS, CGUIDialogFileBrowser::ShowAndGetFile(), CGUIDialogYesNo::ShowAndGetInput(), CGUIDialogOK::ShowAndGetInput(), CFileItemList::Size(), and VERSION.
Referenced by AddVideoVersion().
ChooseVideoAndConvertToVideoVersion()
bool CGUIDialogVideoManagerVersions::ChooseVideoAndConvertToVideoVersion (CFileItemList & items, VideoDbContentType itemType, const std::string & mediaType, int dbId, CVideoDatabase & videoDb, MediaRole role) static private
Ask the user to choose an item from the list of items, the version type of the item, and perform the version conversion according to the role parameter.
Parameters
[in] items The items for the user to choose from
[in] itemType Type of the item being chosen
[in] mediaType ?
[in] dbId id of the video being added if role is NewVersion, id of the video being added to if role is Parent
[in] videoDb Database connection
[in] role NewVersion: dbId will be converted to a version of the movie chosen by the user from the whole libray. Parent: dbId will have another movie chosen by the user from the whole library as a new version.
Returns
True: success, a version was created and attached, false otherwise.
References CGUIDialogVideoManager::ChooseVideoAsset(), CVideoDatabase::ConvertVideoToVersion(), CServiceBroker::GetGUI(), CVideoDatabase::GetVideoVersions(), CGUIComponent::GetWindowManager(), CBackgroundInfoLoader::IsLoading(), CBackgroundInfoLoader::Load(), LOGERROR, NewVersion, Parent, CGUIDialogYesNo::ShowAndGetInput(), CGUIDialogOK::ShowAndGetInput(), CFileItemList::Size(), CBackgroundInfoLoader::StopThread(), VERSION, and WINDOW_DIALOG_SELECT.
Referenced by AddVideoVersion(), and ProcessVideoVersion().
Clear()
void CGUIDialogVideoManagerVersions::Clear () override protected virtual
Reimplemented from CGUIDialogVideoManager.
References CGUIDialogVideoManager::Clear(), and m_defaultVideoVersion.
GetAllOtherMovies()
bool CGUIDialogVideoManagerVersions::GetAllOtherMovies (const std::shared_ptr< CFileItem > & item, CFileItemList & list, CVideoDatabase & videoDb) static private
Populates a list with all movies of the libray, excluding the item provided as parameter.
Parameters
[in] item The item that will be excluded from the list
[out] list List to populate
[in] videoDb Database connection
Returns
True for success, false otherwise.
References CFileItemList::Clear(), CVideoDatabase::GetMoviesNav(), CServiceBroker::GetSettingsComponent(), CFileItem::GetVideoInfoTag(), CVideoInfoTag::m_iDbId, MOVIES, PostProcessList(), CSettings::SETTING_FILELISTS_IGNORETHEWHENSORTING, CFileItemList::Size(), CFileItemList::Sort(), SortAttributeIgnoreArticle, SortAttributeNone, SortByLabel, SortOrderAscending, and CMediaTypes::ToPlural().
Referenced by AddVideoVersion().
GetHeadingId()
int CGUIDialogVideoManagerVersions::GetHeadingId () inline override protected virtual
Implements CGUIDialogVideoManager.
GetSimilarMovies()
bool CGUIDialogVideoManagerVersions::GetSimilarMovies (const std::shared_ptr< CFileItem > & item, CFileItemList & list, CVideoDatabase & videoDb) static private
Populates a list of movies of the library that are similar to the item provided as parameter.
Parameters
[in] item The reference item
[out] list List to populate
[in] videoDb Database connection
Returns
True for success, false otherwise
References CFileItemList::Clear(), CVideoDatabase::GetSameVideoItems(), CFileItem::GetVideoInfoTag(), CVideoInfoTag::m_iDbId, PostProcessList(), and CFileItemList::Size().
Referenced by AddVideoVersion().
GetVideoAssetType()
VideoAssetType CGUIDialogVideoManagerVersions::GetVideoAssetType () override protected virtual
Implements CGUIDialogVideoManager.
References VERSION.
ManageVideoVersions()
bool CGUIDialogVideoManagerVersions::ManageVideoVersions (const std::shared_ptr< CFileItem > & item) static
Open the Manage Versions dialog for a video.
Parameters
item video to manage
Returns
true: the video or another item was modified, a containing list should be refreshed. false: no changes
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), LOGERROR, and WINDOW_DIALOG_MANAGE_VIDEO_VERSIONS.
Referenced by CGUIDialogVideoInfo::ManageVideoVersions(), and CGUIDialogVideoInfo::OnManageVideoVersions().
OnMessage()
bool CGUIDialogVideoManagerVersions::OnMessage (CGUIMessage & message) override protected virtual
Reimplemented from CGUIDialogVideoManager.
References AddVideoVersion(), CONTROL_BUTTON_ADD_VERSION, CONTROL_BUTTON_RENAME_VERSION, CONTROL_BUTTON_SET_DEFAULT, CGUIMessage::GetMessage(), CGUIMessage::GetSenderId(), GUI_MSG_CLICKED, CGUIDialogVideoManager::m_hasUpdatedItems, CGUIDialogVideoManager::OnMessage(), Refresh(), CGUIDialogVideoManager::Rename(), SetDefault(), and CGUIDialogVideoManager::UpdateControls().
PostProcessList()
bool CGUIDialogVideoManagerVersions::PostProcessList (CFileItemList & list, int dbId) static private
Shared post processing of lists after extraction and before display.
Parameters
[in,out] list the list of movies
[in] dbId item to remove from the list
Returns
True for success, false otherwise.
References CFileItem::GetVideoInfoTag(), CFileItemList::Remove(), and CFileItemList::Size().
Referenced by GetAllOtherMovies(), GetSimilarMovies(), and ProcessVideoVersion().
ProcessVideoVersion()
bool CGUIDialogVideoManagerVersions::ProcessVideoVersion (VideoDbContentType itemType, int dbId) static
References ChooseVideoAndConvertToVideoVersion(), g_localizeStrings, CLocalizeStrings::Get(), CVideoDatabase::GetDetailsByTypeAndId(), CVideoDatabase::GetFilePathById(), CVideoDatabase::GetSameVideoItems(), CVideoInfoTag::GetTitle(), CFileItem::GetVideoInfoTag(), LOGERROR, CVideoInfoTag::m_type, MOVIES, NewVersion, CVideoDatabase::Open(), PostProcessList(), CGUIDialogYesNo::ShowAndGetInput(), and CFileItemList::Size().
Referenced by KODI::VIDEO::CVideoInfoScanner::ProcessVideoVersion().
Refresh()
void CGUIDialogVideoManagerVersions::Refresh () override protected virtual
Reimplemented from CGUIDialogVideoManager.
References CVideoDatabase::GetDefaultVideoVersion(), CGUIDialogVideoManager::m_database, m_defaultVideoVersion, CGUIDialogVideoManager::m_videoAsset, CGUIDialogVideoManager::Refresh(), and UpdateDefaultVideoVersionSelection().
Referenced by OnMessage().
Remove()
void CGUIDialogVideoManagerVersions::Remove () override protected virtual
Reimplemented from CGUIDialogVideoManager.
References CVideoDatabase::IsDefaultVideoVersion(), CGUIDialogVideoManager::m_database, CGUIDialogVideoManager::m_selectedVideoAsset, CGUIDialogVideoManager::m_videoAsset, CGUIDialogVideoManager::Remove(), and CGUIDialogOK::ShowAndGetInput().
SetDefault()
void CGUIDialogVideoManagerVersions::SetDefault () private
References CVideoDatabase::GetDefaultVideoVersion(), CGUIDialogVideoManager::m_database, m_defaultVideoVersion, CGUIDialogVideoManager::m_selectedVideoAsset, CGUIDialogVideoManager::m_videoAsset, SetDefaultVideoVersion(), CGUIDialogVideoManager::UpdateControls(), and UpdateDefaultVideoVersionSelection().
Referenced by OnMessage().
SetDefaultVideoVersion()
void CGUIDialogVideoManagerVersions::SetDefaultVideoVersion (const CFileItem & version) private
References CVideoDatabase::GetDetailsByTypeAndId(), CServiceBroker::GetGUI(), CFileItem::GetPath(), CFileItem::GetVideoInfoTag(), CGUIComponent::GetWindowManager(), GUI_MSG_FLAG_FORCE_UPDATE, GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE_ITEM, CGUIDialogVideoManager::m_database, CVideoInfoTag::m_iDbId, CGUIDialogVideoManager::m_videoAsset, CGUIWindowManager::SendMessage(), and CVideoDatabase::SetDefaultVideoVersion().
Referenced by SetDefault().
SetVideoAsset()
void CGUIDialogVideoManagerVersions::SetVideoAsset (const std::shared_ptr< CFileItem > & item) override virtual
Reimplemented from CGUIDialogVideoManager.
References m_defaultVideoVersion, CGUIDialogVideoManager::SetSelectedVideoAsset(), and CGUIDialogVideoManager::SetVideoAsset().
UpdateButtons()
void CGUIDialogVideoManagerVersions::UpdateButtons () override protected virtual
Reimplemented from CGUIDialogVideoManager.
References CONTROL_BUTTON_ADD_VERSION, CONTROL_BUTTON_RENAME_VERSION, CONTROL_BUTTON_SET_DEFAULT, CONTROL_DISABLE, CONTROL_ENABLE, CGUIDialogVideoManager::DisableRemove(), CGUIDialogVideoManager::EnableRemove(), m_defaultVideoVersion, CGUIDialogVideoManager::m_selectedVideoAsset, CGUIDialogVideoManager::m_videoAssetsList, SET_CONTROL_FOCUS, and CGUIDialogVideoManager::UpdateButtons().
UpdateDefaultVideoVersionSelection()
void CGUIDialogVideoManagerVersions::UpdateDefaultVideoVersionSelection () private
References m_defaultVideoVersion, and CGUIDialogVideoManager::m_videoAssetsList.
Referenced by Refresh(), and SetDefault().
Member Data Documentation
m_defaultVideoVersion
std::shared_ptr<CFileItem> CGUIDialogVideoManagerVersions::m_defaultVideoVersion private
Referenced by Clear(), Refresh(), SetDefault(), SetVideoAsset(), UpdateButtons(), and UpdateDefaultVideoVersionSelection().
The documentation for this class was generated from the following files:
GUIDialogVideoManagerVersions.h
GUIDialogVideoManagerVersions.cpp