Kodi Documentation: anonymous_namespace{VideoDatabase.cpp} Namespace Reference
anonymous_namespace{VideoDatabase.cpp} Namespace Reference
Functions
std::vector< std::string > GetBasicItemAvailableArtTypes (int mediaId, VideoDbContentType dbType, CVideoDatabase &db)
std::vector< std::string > GetSeasonAvailableArtTypes (int mediaId, CVideoDatabase &db)
std::vector< std::string > GetMovieSetAvailableArtTypes (int mediaId, CVideoDatabase &db)
std::vector< CScraperUrl::SUrlEntry > GetBasicItemAvailableArt (int mediaId, VideoDbContentType dbType, const std::string &artType, CVideoDatabase &db)
std::vector< CScraperUrl::SUrlEntry > GetSeasonAvailableArt (int mediaId, const std::string &artType, CVideoDatabase &db)
std::vector< CScraperUrl::SUrlEntry > GetMovieSetAvailableArt (int mediaId, const std::string &artType, CVideoDatabase &db)
VideoDbContentType CovertMediaTypeToContentType (const MediaType &mediaType)
std::string RewriteVideoVersionURL (const std::string &baseDir, const CVideoInfoTag &movie)
Function Documentation
CovertMediaTypeToContentType()
VideoDbContentType anonymous_namespace{VideoDatabase.cpp}::CovertMediaTypeToContentType (const MediaType & mediaType)
References EPISODES, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeTvShow, MOVIES, MUSICVIDEOS, TVSHOWS, and UNKNOWN.
GetBasicItemAvailableArt()
std::vector< CScraperUrl::SUrlEntry > anonymous_namespace{VideoDatabase.cpp}::GetBasicItemAvailableArt (int mediaId, VideoDbContentType dbType, const std::string & artType, CVideoDatabase & db)
References CScraperUrl::General, CVideoDatabase::GetDetailsByTypeAndId(), CScraperUrl::SUrlEntry::m_aspect, CScraperUrl::SUrlEntry::m_preview, MediaTypeEpisode, and KODI::UTILS::StringUtils::StartsWith().
GetBasicItemAvailableArtTypes()
std::vector< std::string > anonymous_namespace{VideoDatabase.cpp}::GetBasicItemAvailableArtTypes (int mediaId, VideoDbContentType dbType, CVideoDatabase & db)
Todo:
artwork: fanart stored separately, doesn't need to be
References CScraperUrl::General, CVideoDatabase::GetDetailsByTypeAndId(), MediaTypeEpisode, and KODI::UTILS::StringUtils::StartsWith().
GetMovieSetAvailableArt()
std::vector< CScraperUrl::SUrlEntry > anonymous_namespace{VideoDatabase.cpp}::GetMovieSetAvailableArt (int mediaId, const std::string & artType, CVideoDatabase & db)
References KODI::UTILS::StringUtils::Format(), CVideoDatabase::GetMoviesNav(), CScraperUrl::GetUrls(), CVideoInfoTag::m_strPictureURL, CScraperUrl::Parse(), and KODI::UTILS::StringUtils::StartsWith().
GetMovieSetAvailableArtTypes()
std::vector< std::string > anonymous_namespace{VideoDatabase.cpp}::GetMovieSetAvailableArtTypes (int mediaId, CVideoDatabase & db)
References KODI::UTILS::StringUtils::Format(), CVideoDatabase::GetMoviesNav(), CScraperUrl::GetUrls(), CVideoInfoTag::m_strPictureURL, CScraperUrl::Parse(), and KODI::UTILS::StringUtils::StartsWith().
GetSeasonAvailableArt()
std::vector< CScraperUrl::SUrlEntry > anonymous_namespace{VideoDatabase.cpp}::GetSeasonAvailableArt (int mediaId, const std::string & artType, CVideoDatabase & db)
References CVideoDatabase::GetSeasonInfo(), CVideoDatabase::GetTvShowInfo(), CScraperUrl::GetUrls(), CVideoInfoTag::m_iIdShow, CVideoInfoTag::m_strPictureURL, CScraperUrl::Parse(), and CScraperUrl::Season.
GetSeasonAvailableArtTypes()
std::vector< std::string > anonymous_namespace{VideoDatabase.cpp}::GetSeasonAvailableArtTypes (int mediaId, CVideoDatabase & db)
References CVideoDatabase::GetSeasonInfo(), CVideoDatabase::GetTvShowInfo(), CScraperUrl::GetUrls(), CVideoInfoTag::m_iIdShow, CVideoInfoTag::m_strPictureURL, CScraperUrl::Parse(), and CScraperUrl::Season.
RewriteVideoVersionURL()
std::string anonymous_namespace{VideoDatabase.cpp}::RewriteVideoVersionURL (const std::string & baseDir, const CVideoInfoTag & movie)
References CDbUrl::AddOption(), CDbUrl::AppendPath(), CDbUrl::FromString(), CVideoInfoTag::GetAssetInfo(), CVideoInfoTag::CAssetInfo::GetId(), URIUtils::GetParentPath(), CVideoInfoTag::m_iDbId, and CDbUrl::ToString().