Kodi Documentation: CAESinkAUDIOTRACK Class Reference
CAESinkAUDIOTRACK Class Reference
#include <AESinkAUDIOTRACK.h>
Public Member Functions
const char * GetName () override
CAESinkAUDIOTRACK ()
~CAESinkAUDIOTRACK () override
bool Initialize (AEAudioFormat &format, std::string &device) override
void Deinitialize () override
bool IsInitialized ()
void GetDelay (AEDelayStatus &status) override
Return a timestamped status structure with delay and sink info.
double GetLatency () override
double GetCacheTotal () override
unsigned int AddPackets (uint8_t **data, unsigned int frames, unsigned int offset) override
Adds packets to be sent out, this routine MUST block or sleep.
void AddPause (unsigned int millis) override
instruct the sink to add a pause
void Drain () override
Public Member Functions inherited from IAESink
IAESink ()=default
virtual ~IAESink ()=default
virtual bool HasVolume ()
virtual void SetVolume (float volume)
Static Public Member Functions
static void EnumerateDevicesEx (AEDeviceInfoList &list, bool force=false)
static void Register ()
static std::unique_ptr< IAESink > Create (std::string &device, AEAudioFormat &desiredFormat)
Protected Member Functions
int AudioTrackWrite (char *audioData, int offsetInBytes, int sizeInBytes)
int AudioTrackWrite (char *audioData, int sizeInBytes, int64_t timestamp)
Static Protected Member Functions
static jni::CJNIAudioTrack * CreateAudioTrack (int stream, int sampleRate, int channelMask, int encoding, int bufferSize)
static bool IsSupported (int sampleRateInHz, int channelConfig, int audioFormat)
static bool VerifySinkConfiguration (int sampleRate, int channelMask, int encoding, bool isRaw=false)
static void UpdateAvailablePCMCapabilities ()
static void UpdateAvailablePassthroughCapabilities (bool isRaw=false)
Private Member Functions
double GetMovingAverageDelay (double newestdelay)
Private Attributes
jni::CJNIAudioTrack * m_at_jni
int m_jniAudioFormat
double m_duration_written
unsigned int m_min_buffer_size
uint64_t m_headPos
uint64_t m_headPosOld
uint32_t m_stuckCounter
uint64_t m_timestampPos = 0
std::deque< double > m_linearmovingaverage
AEAudioFormat m_format
int16_t * m_alignedS16
unsigned int m_sink_frameSize
unsigned int m_sink_sampleRate
bool m_passthrough
double m_audiotrackbuffer_sec
double m_audiotrackbuffer_sec_orig
int m_encoding
double m_pause_ms = 0.0
double m_delay = 0.0
double m_hw_delay = 0.0
CJNIAudioTimestamp m_timestamp
XbmcThreads::EndTime m_stampTimer
bool m_superviseAudioDelay = false
std::vector< float > m_floatbuf
std::vector< int16_t > m_shortbuf
std::vector< char > m_charbuf
Static Private Attributes
static CAEDeviceInfo m_info
static CAEDeviceInfo m_info_raw
static CAEDeviceInfo m_info_iec
static bool m_hasIEC = false
static std::set< unsigned int > m_sink_sampleRates
static bool m_sinkSupportsFloat = false
static bool m_sinkSupportsMultiChannelFloat = false
static bool m_passthrough_use_eac3 = false
Constructor & Destructor Documentation
CAESinkAUDIOTRACK()
CAESinkAUDIOTRACK::CAESinkAUDIOTRACK ()
References m_alignedS16, m_at_jni, m_audiotrackbuffer_sec, m_audiotrackbuffer_sec_orig, m_duration_written, m_encoding, m_headPos, m_headPosOld, m_min_buffer_size, m_passthrough, m_sink_frameSize, m_sink_sampleRate, m_stuckCounter, and m_timestampPos.
~CAESinkAUDIOTRACK()
CAESinkAUDIOTRACK::~CAESinkAUDIOTRACK () override
References Deinitialize().
Member Function Documentation
AddPackets()
unsigned int CAESinkAUDIOTRACK::AddPackets (uint8_t ** data, unsigned int frames, unsigned int offset) override virtual
Adds packets to be sent out, this routine MUST block or sleep.
Parameters
data array of pointers to planes holding audio data
frames number of audio frames in data
offset offset in frames where audio data starts
Returns
number of frames consumed by the sink
Implements IAESink.
References AudioTrackWrite(), CurrentHostCounter(), CurrentHostFrequency(), data(), CAEStreamInfo::GetDuration(), IsInitialized(), CLog::Log(), LOGDEBUG, LOGERROR, m_at_jni, m_audiotrackbuffer_sec_orig, m_duration_written, m_format, AEAudioFormat::m_frames, AEAudioFormat::m_frameSize, m_info, m_passthrough, m_pause_ms, AEAudioFormat::m_sampleRate, AEAudioFormat::m_streamInfo, m_stuckCounter, m_superviseAudioDelay, and CAEDeviceInfo::m_wantsIECPassthrough.
AddPause()
void CAESinkAUDIOTRACK::AddPause (unsigned int millis) override virtual
instruct the sink to add a pause
Parameters
millis ms to pause
Reimplemented from IAESink.
References m_at_jni, and m_pause_ms.
AudioTrackWrite() [1/2]
int CAESinkAUDIOTRACK::AudioTrackWrite (char * audioData, int offsetInBytes, int sizeInBytes) protected
References m_at_jni, m_charbuf, m_floatbuf, m_jniAudioFormat, and m_shortbuf.
Referenced by AddPackets().
AudioTrackWrite() [2/2]
int CAESinkAUDIOTRACK::AudioTrackWrite (char * audioData, int sizeInBytes, int64_t timestamp) protected
References m_at_jni.
Create()
std::unique_ptr< IAESink > CAESinkAUDIOTRACK::Create (std::string & device, AEAudioFormat & desiredFormat) static
Referenced by Register().
CreateAudioTrack()
jni::CJNIAudioTrack * CAESinkAUDIOTRACK::CreateAudioTrack (int stream, int sampleRate, int channelMask, int encoding, int bufferSize) static protected
References CLog::Log(), and LOGINFO.
Referenced by Initialize(), and VerifySinkConfiguration().
Deinitialize()
void CAESinkAUDIOTRACK::Deinitialize () override virtual
Implements IAESink.
References IsInitialized(), CLog::Log(), LOGDEBUG, m_at_jni, m_delay, m_duration_written, m_headPos, m_headPosOld, m_hw_delay, m_linearmovingaverage, m_stampTimer, and m_timestampPos.
Referenced by Initialize(), and ~CAESinkAUDIOTRACK().
Drain()
void CAESinkAUDIOTRACK::Drain () override virtual
Reimplemented from IAESink.
References IsInitialized(), CLog::Log(), LOGDEBUG, m_at_jni, m_duration_written, m_headPos, m_linearmovingaverage, m_pause_ms, m_stampTimer, m_stuckCounter, and m_timestampPos.
EnumerateDevicesEx()
void CAESinkAUDIOTRACK::EnumerateDevicesEx (AEDeviceInfoList & list, bool force = false) static
References AE_DEVTYPE_PCM, CAEDeviceInfo::m_channels, CAEDeviceInfo::m_dataFormats, CAEDeviceInfo::m_deviceName, CAEDeviceInfo::m_deviceType, CAEDeviceInfo::m_displayName, CAEDeviceInfo::m_displayNameExtra, m_hasIEC, m_info, m_info_iec, m_info_raw, CAEDeviceInfo::m_onlyPassthrough, CAEDeviceInfo::m_sampleRates, m_sink_sampleRates, CAEDeviceInfo::m_streamTypes, CAEChannelInfo::Reset(), UpdateAvailablePassthroughCapabilities(), and UpdateAvailablePCMCapabilities().
Referenced by Register().
GetCacheTotal()
double CAESinkAUDIOTRACK::GetCacheTotal () override virtual
Implements IAESink.
References m_audiotrackbuffer_sec.
GetDelay()
void CAESinkAUDIOTRACK::GetDelay (AEDelayStatus & status) override virtual
Return a timestamped status structure with delay and sink info.
Parameters
status structure filled with sink status
Implements IAESink.
References CLog::CanLogComponent(), CurrentHostCounter(), CServiceBroker::GetLogging(), GetMovingAverageDelay(), int64_t(), CLog::Log(), LOGAUDIO, LOGDEBUG, LOGINFO, m_at_jni, m_audiotrackbuffer_sec, m_delay, m_duration_written, m_headPos, m_headPosOld, m_hw_delay, m_pause_ms, m_sink_sampleRate, m_stampTimer, m_stuckCounter, m_timestamp, m_timestampPos, AEDelayStatus::SetDelay(), UINT64_LOWER_BYTES, and UINT64_UPPER_BYTES.
GetLatency()
double CAESinkAUDIOTRACK::GetLatency () override virtual
Reimplemented from IAESink.
GetMovingAverageDelay()
double CAESinkAUDIOTRACK::GetMovingAverageDelay (double newestdelay) private
References m_linearmovingaverage, and MOVING_AVERAGE_MAX_MEMBERS.
Referenced by GetDelay().
GetName()
const char * CAESinkAUDIOTRACK::GetName () inline override virtual
Implements IAESink.
Initialize()
bool CAESinkAUDIOTRACK::Initialize (AEAudioFormat & format, std::string & device) override virtual
Implements IAESink.
References AE_CH_LAYOUT_2_0, AE_CH_LAYOUT_7_1, AE_FMT_FLOAT, AE_FMT_RAW, AE_FMT_S16LE, AEChannelMapToAUDIOTRACKChannelMask(), AEStreamFormatToATFormat(), AUDIOTRACKChannelMaskToAEChannelMap(), CAEChannelInfo::Count(), CreateAudioTrack(), CAEUtil::DataFormatToBits(), CAEUtil::DataFormatToStr(), Deinitialize(), CAEStreamInfo::GetDuration(), CServiceBroker::GetSettingsComponent(), IsInitialized(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, LOGWARNING, m_at_jni, m_audiotrackbuffer_sec, m_audiotrackbuffer_sec_orig, AEAudioFormat::m_channelLayout, AEAudioFormat::m_dataFormat, m_encoding, m_format, AEAudioFormat::m_frames, AEAudioFormat::m_frameSize, CAEStreamInfo::m_frameSize, m_hasIEC, m_headPos, m_headPosOld, m_info, m_info_iec, m_info_raw, m_jniAudioFormat, m_linearmovingaverage, m_min_buffer_size, m_passthrough, m_passthrough_use_eac3, m_pause_ms, AEAudioFormat::m_sampleRate, CAEStreamInfo::m_sampleRate, m_sink_frameSize, m_sink_sampleRate, m_sink_sampleRates, m_sinkSupportsFloat, m_sinkSupportsMultiChannelFloat, AEAudioFormat::m_streamInfo, m_stuckCounter, m_superviseAudioDelay, m_timestampPos, CAEStreamInfo::m_type, CAEDeviceInfo::m_wantsIECPassthrough, MAX_RAW_AUDIO_BUFFER, MAX_RAW_AUDIO_BUFFER_HD, CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, CAEStreamInfo::STREAM_TYPE_TRUEHD, and CAEUtil::StreamTypeToStr().
IsInitialized()
bool CAESinkAUDIOTRACK::IsInitialized ()
References m_at_jni.
Referenced by AddPackets(), Deinitialize(), Drain(), and Initialize().
IsSupported()
bool CAESinkAUDIOTRACK::IsSupported (int sampleRateInHz, int channelConfig, int audioFormat) static protected
Referenced by UpdateAvailablePCMCapabilities().
Register()
void CAESinkAUDIOTRACK::Register () static
References Create(), AE::AESinkRegEntry::createFunc, EnumerateDevicesEx(), AE::AESinkRegEntry::enumerateFunc, AE::CAESinkFactory::RegisterSink(), and AE::AESinkRegEntry::sinkName.
Referenced by CXBMCApp::onStart().
UpdateAvailablePassthroughCapabilities()
void CAESinkAUDIOTRACK::UpdateAvailablePassthroughCapabilities (bool isRaw = false) static protected
References AE_CH_LAYOUT_7_1, AE_DEVTYPE_HDMI, AE_FMT_RAW, AEChannelMapToAUDIOTRACKChannelMask(), CLog::Log(), LOGDEBUG, CAEDeviceInfo::m_dataFormats, CAEDeviceInfo::m_deviceType, m_info, m_passthrough_use_eac3, m_sink_sampleRates, CAEDeviceInfo::m_streamTypes, CAEDeviceInfo::m_wantsIECPassthrough, CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, CAEStreamInfo::STREAM_TYPE_TRUEHD, and VerifySinkConfiguration().
Referenced by EnumerateDevicesEx().
UpdateAvailablePCMCapabilities()
void CAESinkAUDIOTRACK::UpdateAvailablePCMCapabilities () static protected
References AE_FMT_FLOAT, AE_FMT_S16LE, IsSupported(), KnownChannels, CLog::Log(), LOGDEBUG, LOGINFO, CAEDeviceInfo::m_channels, CAEDeviceInfo::m_dataFormats, m_info, CAEDeviceInfo::m_sampleRates, m_sink_sampleRates, m_sinkSupportsFloat, m_sinkSupportsMultiChannelFloat, and VerifySinkConfiguration().
Referenced by EnumerateDevicesEx().
VerifySinkConfiguration()
bool CAESinkAUDIOTRACK::VerifySinkConfiguration (int sampleRate, int channelMask, int encoding, bool isRaw = false) static protected
References CreateAudioTrack(), CLog::Log(), and LOGDEBUG.
Referenced by UpdateAvailablePassthroughCapabilities(), and UpdateAvailablePCMCapabilities().
Member Data Documentation
m_alignedS16
int16_t* CAESinkAUDIOTRACK::m_alignedS16 private
Referenced by CAESinkAUDIOTRACK().
m_at_jni
jni::CJNIAudioTrack* CAESinkAUDIOTRACK::m_at_jni private
Referenced by AddPackets(), AddPause(), AudioTrackWrite(), AudioTrackWrite(), CAESinkAUDIOTRACK(), Deinitialize(), Drain(), GetDelay(), Initialize(), and IsInitialized().
m_audiotrackbuffer_sec
double CAESinkAUDIOTRACK::m_audiotrackbuffer_sec private
Referenced by CAESinkAUDIOTRACK(), GetCacheTotal(), GetDelay(), and Initialize().
m_audiotrackbuffer_sec_orig
double CAESinkAUDIOTRACK::m_audiotrackbuffer_sec_orig private
Referenced by AddPackets(), CAESinkAUDIOTRACK(), and Initialize().
m_charbuf
std::vector<char> CAESinkAUDIOTRACK::m_charbuf private
Referenced by AudioTrackWrite().
m_delay
double CAESinkAUDIOTRACK::m_delay = 0.0 private
Referenced by Deinitialize(), and GetDelay().
m_duration_written
double CAESinkAUDIOTRACK::m_duration_written private
Referenced by AddPackets(), CAESinkAUDIOTRACK(), Deinitialize(), Drain(), and GetDelay().
m_encoding
int CAESinkAUDIOTRACK::m_encoding private
Referenced by CAESinkAUDIOTRACK(), and Initialize().
m_floatbuf
std::vector<float> CAESinkAUDIOTRACK::m_floatbuf private
Referenced by AudioTrackWrite().
m_format
AEAudioFormat CAESinkAUDIOTRACK::m_format private
Referenced by AddPackets(), and Initialize().
m_hasIEC
bool CAESinkAUDIOTRACK::m_hasIEC = false static private
Referenced by EnumerateDevicesEx(), and Initialize().
m_headPos
uint64_t CAESinkAUDIOTRACK::m_headPos private
Referenced by CAESinkAUDIOTRACK(), Deinitialize(), Drain(), GetDelay(), and Initialize().
m_headPosOld
uint64_t CAESinkAUDIOTRACK::m_headPosOld private
Referenced by CAESinkAUDIOTRACK(), Deinitialize(), GetDelay(), and Initialize().
m_hw_delay
double CAESinkAUDIOTRACK::m_hw_delay = 0.0 private
Referenced by Deinitialize(), and GetDelay().
m_info
CAEDeviceInfo CAESinkAUDIOTRACK::m_info static private
Referenced by AddPackets(), EnumerateDevicesEx(), Initialize(), UpdateAvailablePassthroughCapabilities(), and UpdateAvailablePCMCapabilities().
m_info_iec
CAEDeviceInfo CAESinkAUDIOTRACK::m_info_iec static private
Referenced by EnumerateDevicesEx(), and Initialize().
m_info_raw
CAEDeviceInfo CAESinkAUDIOTRACK::m_info_raw static private
Referenced by EnumerateDevicesEx(), and Initialize().
m_jniAudioFormat
int CAESinkAUDIOTRACK::m_jniAudioFormat private
Referenced by AudioTrackWrite(), and Initialize().
m_linearmovingaverage
std::deque<double> CAESinkAUDIOTRACK::m_linearmovingaverage private
Referenced by Deinitialize(), Drain(), GetMovingAverageDelay(), and Initialize().
m_min_buffer_size
unsigned int CAESinkAUDIOTRACK::m_min_buffer_size private
Referenced by CAESinkAUDIOTRACK(), and Initialize().
m_passthrough
bool CAESinkAUDIOTRACK::m_passthrough private
Referenced by AddPackets(), CAESinkAUDIOTRACK(), and Initialize().
m_passthrough_use_eac3
bool CAESinkAUDIOTRACK::m_passthrough_use_eac3 = false static private
Referenced by Initialize(), and UpdateAvailablePassthroughCapabilities().
m_pause_ms
double CAESinkAUDIOTRACK::m_pause_ms = 0.0 private
Referenced by AddPackets(), AddPause(), Drain(), GetDelay(), and Initialize().
m_shortbuf
std::vector<int16_t> CAESinkAUDIOTRACK::m_shortbuf private
Referenced by AudioTrackWrite().
m_sink_frameSize
unsigned int CAESinkAUDIOTRACK::m_sink_frameSize private
Referenced by CAESinkAUDIOTRACK(), and Initialize().
m_sink_sampleRate
unsigned int CAESinkAUDIOTRACK::m_sink_sampleRate private
Referenced by CAESinkAUDIOTRACK(), GetDelay(), and Initialize().
m_sink_sampleRates
std::set< unsigned int > CAESinkAUDIOTRACK::m_sink_sampleRates static private
Referenced by EnumerateDevicesEx(), Initialize(), UpdateAvailablePassthroughCapabilities(), and UpdateAvailablePCMCapabilities().
m_sinkSupportsFloat
bool CAESinkAUDIOTRACK::m_sinkSupportsFloat = false static private
Referenced by Initialize(), and UpdateAvailablePCMCapabilities().
m_sinkSupportsMultiChannelFloat
bool CAESinkAUDIOTRACK::m_sinkSupportsMultiChannelFloat = false static private
Referenced by Initialize(), and UpdateAvailablePCMCapabilities().
m_stampTimer
XbmcThreads::EndTime CAESinkAUDIOTRACK::m_stampTimer private
Referenced by Deinitialize(), Drain(), and GetDelay().
m_stuckCounter
uint32_t CAESinkAUDIOTRACK::m_stuckCounter private
Referenced by AddPackets(), CAESinkAUDIOTRACK(), Drain(), GetDelay(), and Initialize().
m_superviseAudioDelay
bool CAESinkAUDIOTRACK::m_superviseAudioDelay = false private
Referenced by AddPackets(), and Initialize().
m_timestamp
CJNIAudioTimestamp CAESinkAUDIOTRACK::m_timestamp private
Referenced by GetDelay().
m_timestampPos
uint64_t CAESinkAUDIOTRACK::m_timestampPos = 0 private
Referenced by CAESinkAUDIOTRACK(), Deinitialize(), Drain(), GetDelay(), and Initialize().
The documentation for this class was generated from the following files:
AESinkAUDIOTRACK.h
AESinkAUDIOTRACK.cpp