Kodi Documentation: XBMCAddon::xbmc::InfoTagVideo Class Reference
XBMCAddon::xbmc::InfoTagVideo Class Reference
Python » Library - xbmc » InfoTagVideo
#include <InfoTagVideo.h>
Public Member Functions
InfoTagVideo (const CVideoInfoTag *tag)
InfoTagVideo (CVideoInfoTag *tag, bool offscreen=false)
InfoTagVideo (...)
Function: xbmc.InfoTagVideo([offscreen])
Create a video info tag.
~InfoTagVideo () override
getDbId ()
Function: getDbId()
Get identification number of tag in database
getDirector ()
Function: getDirector()
Get film director who has made the film (if present).
getDirectors ()
Function: getDirectors()
Get a list of film directors who have made the film (if present).
getWritingCredits ()
Function: getWritingCredits()
Get the writing credits if present from video info tag.
getWriters ()
Function: getWriters()
Get the list of writers (if present) from video info tag.
getGenre ()
Function: getGenre()
To get the Video Genre if available.
getGenres ()
Function: getGenres()
Get the list of Video Genres if available.
getTagLine ()
Function: getTagLine()
Get video tag line if available.
getPlotOutline ()
Function: getPlotOutline()
Get the outline plot of the video if present.
getPlot ()
Function: getPlot()
Get the plot of the video if present.
getPictureURL ()
Function: getPictureURL()
Get a picture URL of the video to show as screenshot.
getTitle ()
Function: getTitle()
Get the video title.
getTVShowTitle ()
Function: getTVShowTitle()
Get the video TV show title.
getMediaType ()
Function: getMediaType()
Get the media type of the video.
getVotes ()
Function: getVotes()
Get the video votes if available from video info tag.
getVotesAsInt (type)
Function: getVotesAsInt([type])
Get the votes of the rating (if available) as an integer.
getCast ()
Function: getCast()
To get the cast of the video when available.
getActors ()
Function: getActors()
Get the cast of the video if available.
getFile ()
Function: getFile()
To get the video file name.
getPath ()
Function: getPath()
To get the path where the video is stored.
getFilenameAndPath ()
Function: getFilenameAndPath()
To get the full path with filename where the video is stored.
getIMDBNumber ()
Function: getIMDBNumber()
To get the IMDb number of the video (if present).
getSeason ()
Function: getSeason()
To get season number of a series
getEpisode ()
Function: getEpisode()
To get episode number of a series
getYear ()
Function: getYear()
Get production year of video if present.
getRating (type)
Function: getRating([type])
Get the video rating if present as float (double where supported).
getUserRating ()
Function: getUserRating()
Get the user rating if present as integer.
getPlayCount ()
Function: getPlayCount()
To get the number of plays of the video.
getLastPlayed ()
Function: getLastPlayed()
Get the last played date / time as string.
getLastPlayedAsW3C ()
Function: getLastPlayedAsW3C()
Get last played datetime as string in W3C format (YYYY-MM-DDThh:mm:ssTZD).
getOriginalTitle ()
Function: getOriginalTitle()
To get the original title of the video.
getPremiered ()
Function: getPremiered()
To get premiered date of the video, if available.
getPremieredAsW3C ()
Function: getPremieredAsW3C()
Get premiered date as string in W3C format (YYYY-MM-DD).
getFirstAired ()
Function: getFirstAired()
Returns first aired date as string from info tag.
getFirstAiredAsW3C ()
Function: getFirstAiredAsW3C()
Get first aired date as string in W3C format (YYYY-MM-DD).
getTrailer ()
Function: getTrailer()
To get the path where the trailer is stored.
getArtist ()
Function: getArtist()
To get the artist name (for musicvideos)
getAlbum ()
Function: getAlbum()
To get the album name (for musicvideos)
getTrack ()
Function: getTrack()
To get the track number (for musicvideos)
getDuration ()
Function: getDuration()
To get the duration
getResumeTime (...)
Function: getResumeTime())
Gets the resume time of the video item.
getResumeTimeTotal (...)
Function: getResumeTimeTotal())
Gets the total duration stored with the resume time of the video item.
getUniqueID (key)
Function: getUniqueID(key)
Get the unique ID of the given key. A unique ID is an identifier used by a (online) video database used to identify a video in its database.
setUniqueID (...)
Function: setUniqueID(uniqueid, [type], [isdefault])
Set the given unique ID. A unique ID is an identifier used by a (online) video database used to identify a video in its database.
setUniqueIDs (...)
Function: setUniqueIDs(values, defaultuniqueid)
Set the given unique IDs. A unique ID is an identifier used by a (online) video database used to identify a video in its database.
setDbId (...)
Function: setDbId(dbid)
Set the database identifier of the video item.
setYear (...)
Function: setYear(year)
Set the year of the video item.
setEpisode (...)
Function: setEpisode(episode)
Set the episode number of the episode.
setSeason (...)
Function: setSeason(season)
Set the season number of the video item.
setSortEpisode (...)
Function: setSortEpisode(sortepisode)
Set the episode sort number of the episode.
setSortSeason (...)
Function: setSortSeason(sortseason)
Set the season sort number of the season.
setEpisodeGuide (...)
Function: setEpisodeGuide(episodeguide)
Set the episode guide of the video item.
setTop250 (...)
Function: setTop250(top250)
Set the top 250 number of the video item.
setSetId (...)
Function: setSetId(setid)
Set the movie set identifier of the video item.
setTrackNumber (...)
Function: setTrackNumber(tracknumber)
Set the track number of the music video item.
setRating (...)
Function: setRating(rating, [votes], [type], [isdefault])
Set the rating of the video item.
setRatings (...)
Function: setRatings(ratings, [defaultrating])
Set the ratings of the video item.
setUserRating (...)
Function: setUserRating(userrating)
Set the user rating of the video item.
setPlaycount (...)
Function: setPlaycount(playcount)
Set the playcount of the video item.
setMpaa (...)
Function: setMpaa(mpaa)
Set the MPAA rating of the video item.
setPlot (...)
Function: setPlot(plot)
Set the plot of the video item.
setPlotOutline (...)
Function: setPlotOutline(plotoutline)
Set the plot outline of the video item.
setTitle (...)
Function: setTitle(title)
Set the title of the video item.
setOriginalTitle (...)
Function: setOriginalTitle(originaltitle)
Set the original title of the video item.
setSortTitle (...)
Function: setSortTitle(sorttitle)
Set the sort title of the video item.
setTagLine (...)
Function: setTagLine(tagline)
Set the tagline of the video item.
setTvShowTitle (...)
Function: setTvShowTitle(tvshowtitle)
Set the TV show title of the video item.
setTvShowStatus (...)
Function: setTvShowStatus(tvshowstatus)
Set the TV show status of the video item.
setGenres (...)
Function: setGenres(genre)
Set the genres of the video item.
setCountries (...)
Function: setCountries(countries)
Set the countries of the video item.
setDirectors (...)
Function: setDirectors(directors)
Set the directors of the video item.
setStudios (...)
Function: setStudios(studios)
Set the studios of the video item.
setWriters (...)
Function: setWriters(writers)
Set the writers of the video item.
setDuration (...)
Function: setDuration(duration)
Set the duration of the video item.
setPremiered (...)
Function: setPremiered(premiered)
Set the premiere date of the video item.
setSet (...)
Function: setSet(set)
Set the movie set (name) of the video item.
setSetOverview (...)
Function: setSetOverview(setoverview)
Set the movie set overview of the video item.
setTags (...)
Function: setTags(tags)
Set the tags of the video item.
setVideoAssetTitle (...)
Function: setVideoAssetTitle(videoAssetTitle)
Set the video asset title of the item.
setProductionCode (...)
Function: setProductionCode(const String& productioncode)
Set the production code of the video item.
setFirstAired (...)
Function: setFirstAired(firstaired)
Set the first aired date of the video item.
setLastPlayed (...)
Function: setLastPlayed(lastplayed)
Set the last played date of the video item.
setAlbum (...)
Function: setAlbum(album)
Set the album of the video item.
setVotes (...)
Function: setVotes(votes)
Set the number of votes of the video item.
setTrailer (...)
Function: setTrailer(trailer)
Set the trailer of the video item.
setPath (...)
Function: setPath(path)
Set the path of the video item.
setFilenameAndPath (...)
Function: setFilenameAndPath(filenameandpath)
Set the filename and path of the video item.
setIMDBNumber (...)
Function: setIMDBNumber(imdbnumber)
Set the IMDb number of the video item.
setDateAdded (...)
Function: setDateAdded(dateadded)
Set the date added of the video item.
setMediaType (...)
Function: setMediaType(mediatype)
Set the media type of the video item.
setShowLinks (...)
Function: setShowLinks(showlinks)
Set the TV show links of the movie.
setArtists (...)
Function: setArtists(artists)
Set the artists of the music video item.
setCast (...)
Function: setCast(actors)
Set the cast / actors of the video item.
setResumePoint (...)
Function: setResumePoint(time, [totaltime])
Set the resume point of the video item.
addSeason (...)
Function: addSeason(number, [name])
Add a season with name. It needs at least the season number.
addSeasons (...)
Function: addSeasons(namedseasons)
Add named seasons to the TV show.
addVideoStream (...)
Function: addVideoStream(stream)
Add a video stream to the video item.
addAudioStream (...)
Function: addAudioStream(stream)
Add an audio stream to the video item.
addSubtitleStream (...)
Function: addSubtitleStream(stream)
Add a subtitle stream to the video item.
addAvailableArtwork (...)
Function: addAvailableArtwork(images)
Add an image to available artworks (needed for video scrapers)
Public Member Functions inherited from XBMCAddon::AddonClass
AddonClass ()
virtual ~AddonClass ()
const char * GetClassname () const
LanguageHook * GetLanguageHook ()
bool isDeallocating ()
void Release () const
void Acquire () const
Static Public Member Functions
static void setDbIdRaw (CVideoInfoTag *infoTag, int dbId)
static void setUniqueIDRaw (CVideoInfoTag *infoTag, const String &uniqueID, const String &type="", bool isDefault=false)
static void setUniqueIDsRaw (CVideoInfoTag *infoTag, std::map< String, String > uniqueIDs, const String &defaultUniqueID="")
static void setYearRaw (CVideoInfoTag *infoTag, int year)
static void setEpisodeRaw (CVideoInfoTag *infoTag, int episode)
static void setSeasonRaw (CVideoInfoTag *infoTag, int season)
static void setSortEpisodeRaw (CVideoInfoTag *infoTag, int sortEpisode)
static void setSortSeasonRaw (CVideoInfoTag *infoTag, int sortSeason)
static void setEpisodeGuideRaw (CVideoInfoTag *infoTag, const String &episodeGuide)
static void setTop250Raw (CVideoInfoTag *infoTag, int top250)
static void setSetIdRaw (CVideoInfoTag *infoTag, int setId)
static void setTrackNumberRaw (CVideoInfoTag *infoTag, int trackNumber)
static void setRatingRaw (CVideoInfoTag *infoTag, float rating, int votes=0, const std::string &type="", bool isDefault=false)
static void setRatingsRaw (CVideoInfoTag *infoTag, const std::map< String, Tuple< float, int > > &ratings, const String &defaultRating="")
static void setUserRatingRaw (CVideoInfoTag *infoTag, int userRating)
static void setPlaycountRaw (CVideoInfoTag *infoTag, int playcount)
static void setMpaaRaw (CVideoInfoTag *infoTag, const String &mpaa)
static void setPlotRaw (CVideoInfoTag *infoTag, const String &plot)
static void setPlotOutlineRaw (CVideoInfoTag *infoTag, const String &plotOutline)
static void setTitleRaw (CVideoInfoTag *infoTag, const String &title)
static void setOriginalTitleRaw (CVideoInfoTag *infoTag, const String &originalTitle)
static void setSortTitleRaw (CVideoInfoTag *infoTag, const String &sortTitle)
static void setTagLineRaw (CVideoInfoTag *infoTag, const String &tagLine)
static void setTvShowTitleRaw (CVideoInfoTag *infoTag, const String &tvshowTitle)
static void setTvShowStatusRaw (CVideoInfoTag *infoTag, const String &tvshowStatus)
static void setGenresRaw (CVideoInfoTag *infoTag, std::vector< String > genre)
static void setCountriesRaw (CVideoInfoTag *infoTag, std::vector< String > countries)
static void setDirectorsRaw (CVideoInfoTag *infoTag, std::vector< String > directors)
static void setStudiosRaw (CVideoInfoTag *infoTag, std::vector< String > studios)
static void setWritersRaw (CVideoInfoTag *infoTag, std::vector< String > writers)
static void setDurationRaw (CVideoInfoTag *infoTag, int duration)
static void setPremieredRaw (CVideoInfoTag *infoTag, const String &premiered)
static void setSetRaw (CVideoInfoTag *infoTag, const String &set)
static void setSetOverviewRaw (CVideoInfoTag *infoTag, const String &setOverview)
static void setTagsRaw (CVideoInfoTag *infoTag, std::vector< String > tags)
static void setVideoAssetTitleRaw (CVideoInfoTag *infoTag, const String &videoAssetTitle)
static void setProductionCodeRaw (CVideoInfoTag *infoTag, const String &productionCode)
static void setFirstAiredRaw (CVideoInfoTag *infoTag, const String &firstAired)
static void setLastPlayedRaw (CVideoInfoTag *infoTag, const String &lastPlayed)
static void setAlbumRaw (CVideoInfoTag *infoTag, const String &album)
static void setVotesRaw (CVideoInfoTag *infoTag, int votes)
static void setTrailerRaw (CVideoInfoTag *infoTag, const String &trailer)
static void setPathRaw (CVideoInfoTag *infoTag, const String &path)
static void setFilenameAndPathRaw (CVideoInfoTag *infoTag, const String &filenameAndPath)
static void setIMDBNumberRaw (CVideoInfoTag *infoTag, const String &imdbNumber)
static void setDateAddedRaw (CVideoInfoTag *infoTag, const String &dateAdded)
static void setMediaTypeRaw (CVideoInfoTag *infoTag, const String &mediaType)
static void setShowLinksRaw (CVideoInfoTag *infoTag, std::vector< String > showLinks)
static void setArtistsRaw (CVideoInfoTag *infoTag, std::vector< String > artists)
static void setCastRaw (CVideoInfoTag *infoTag, std::vector< SActorInfo > cast)
static void setResumePointRaw (CVideoInfoTag *infoTag, double time, double totalTime=0.0)
static void addSeasonRaw (CVideoInfoTag *infoTag, int number, std::string name="")
static void addSeasonsRaw (CVideoInfoTag *infoTag, const std::vector< Tuple< int, std::string > > &namedSeasons)
static void addStreamRaw (CVideoInfoTag *infoTag, CStreamDetail *stream)
static void finalizeStreamsRaw (CVideoInfoTag *infoTag)
static void addAvailableArtworkRaw (CVideoInfoTag *infoTag, const std::string &url, const std::string &art_type="", const std::string &preview="", const std::string &referrer="", const std::string &cache="", bool post=false, bool isgz=false, int season=-1)
Static Public Member Functions inherited from XBMCAddon::AddonClass
static short getNumAddonClasses ()
Private Attributes
CVideoInfoTag * infoTag
bool offscreen
bool owned
Additional Inherited Members
Protected Member Functions inherited from XBMCAddon::AddonClass
virtual void deallocating ()
Static Protected Member Functions inherited from XBMCAddon::AddonClass
static short getNextClassIndex ()
Protected Attributes inherited from XBMCAddon::AddonClass
LanguageHook * languageHook
Member Function Documentation
addAvailableArtworkRaw()
void XBMCAddon::xbmc::InfoTagVideo::addAvailableArtworkRaw (CVideoInfoTag * infoTag, const std::string & url, const std::string & art_type = "", const std::string & preview = "", const std::string & referrer = "", const std::string & cache = "", bool post = false, bool isgz = false, int season = -1) static
References CScraperUrl::AddParsedUrl(), and CVideoInfoTag::m_strPictureURL.
Referenced by addAvailableArtwork(), and XBMCAddon::xbmcgui::ListItem::addAvailableArtwork().
addSeasonRaw()
void XBMCAddon::xbmc::InfoTagVideo::addSeasonRaw (CVideoInfoTag * infoTag, int number, std::string name = "") static
References CVideoInfoTag::m_namedSeasons, and name.
Referenced by addSeason(), and XBMCAddon::xbmcgui::ListItem::addSeason().
addSeasonsRaw()
void XBMCAddon::xbmc::InfoTagVideo::addSeasonsRaw (CVideoInfoTag * infoTag, const std::vector< Tuple< int, std::string > > & namedSeasons) static
Referenced by addSeasons().
addStreamRaw()
void XBMCAddon::xbmc::InfoTagVideo::addStreamRaw (CVideoInfoTag * infoTag, CStreamDetail * stream) static
References CStreamDetails::AddStream(), and CVideoInfoTag::m_streamDetails.
Referenced by addAudioStream(), XBMCAddon::xbmcgui::ListItem::addStreamInfo(), addSubtitleStream(), and addVideoStream().
finalizeStreamsRaw()
void XBMCAddon::xbmc::InfoTagVideo::finalizeStreamsRaw (CVideoInfoTag * infoTag) static
References CStreamDetails::DetermineBestStreams(), and CVideoInfoTag::m_streamDetails.
Referenced by XBMCAddon::xbmcgui::ListItem::addStreamInfo().
setAlbumRaw()
void XBMCAddon::xbmc::InfoTagVideo::setAlbumRaw (CVideoInfoTag * infoTag, const String & album) static
References CVideoInfoTag::SetAlbum().
Referenced by setAlbum().
setArtistsRaw()
void XBMCAddon::xbmc::InfoTagVideo::setArtistsRaw (CVideoInfoTag * infoTag, std::vector< String > artists) static
References CVideoInfoTag::m_artist.
Referenced by setArtists().
setCastRaw()
void XBMCAddon::xbmc::InfoTagVideo::setCastRaw (CVideoInfoTag * infoTag, std::vector< SActorInfo > cast) static
References CVideoInfoTag::m_cast.
Referenced by setCast(), and XBMCAddon::xbmcgui::ListItem::setCast().
setCountriesRaw()
void XBMCAddon::xbmc::InfoTagVideo::setCountriesRaw (CVideoInfoTag * infoTag, std::vector< String > countries) static
References CVideoInfoTag::SetCountry().
Referenced by setCountries().
setDateAddedRaw()
void XBMCAddon::xbmc::InfoTagVideo::setDateAddedRaw (CVideoInfoTag * infoTag, const String & dateAdded) static
References CVideoInfoTag::m_dateAdded, and CDateTime::SetFromDBDateTime().
Referenced by setDateAdded().
setDbIdRaw()
void XBMCAddon::xbmc::InfoTagVideo::setDbIdRaw (CVideoInfoTag * infoTag, int dbId) static
References infoTag, and CVideoInfoTag::m_iDbId.
Referenced by setDbId().
setDirectorsRaw()
void XBMCAddon::xbmc::InfoTagVideo::setDirectorsRaw (CVideoInfoTag * infoTag, std::vector< String > directors) static
References CVideoInfoTag::SetDirector().
Referenced by setDirectors().
setDurationRaw()
void XBMCAddon::xbmc::InfoTagVideo::setDurationRaw (CVideoInfoTag * infoTag, int duration) static
References CVideoInfoTag::SetDuration().
Referenced by setDuration().
setEpisodeGuideRaw()
void XBMCAddon::xbmc::InfoTagVideo::setEpisodeGuideRaw (CVideoInfoTag * infoTag, const String & episodeGuide) static
References infoTag, and CVideoInfoTag::SetEpisodeGuide().
Referenced by setEpisodeGuide().
setEpisodeRaw()
void XBMCAddon::xbmc::InfoTagVideo::setEpisodeRaw (CVideoInfoTag * infoTag, int episode) static
References infoTag, and CVideoInfoTag::m_iEpisode.
Referenced by setEpisode().
setFilenameAndPathRaw()
void XBMCAddon::xbmc::InfoTagVideo::setFilenameAndPathRaw (CVideoInfoTag * infoTag, const String & filenameAndPath) static
References CVideoInfoTag::SetFileNameAndPath().
Referenced by setFilenameAndPath().
setFirstAiredRaw()
void XBMCAddon::xbmc::InfoTagVideo::setFirstAiredRaw (CVideoInfoTag * infoTag, const String & firstAired) static
References CVideoInfoTag::m_firstAired, and CDateTime::SetFromDateString().
Referenced by setFirstAired().
setGenresRaw()
void XBMCAddon::xbmc::InfoTagVideo::setGenresRaw (CVideoInfoTag * infoTag, std::vector< String > genre) static
References CVideoInfoTag::SetGenre().
Referenced by setGenres().
setIMDBNumberRaw()
void XBMCAddon::xbmc::InfoTagVideo::setIMDBNumberRaw (CVideoInfoTag * infoTag, const String & imdbNumber) static
References CVideoInfoTag::SetUniqueID().
Referenced by setIMDBNumber().
setLastPlayedRaw()
void XBMCAddon::xbmc::InfoTagVideo::setLastPlayedRaw (CVideoInfoTag * infoTag, const String & lastPlayed) static
References CVideoInfoTag::m_lastPlayed, and CDateTime::SetFromDBDateTime().
Referenced by setLastPlayed().
setMediaTypeRaw()
void XBMCAddon::xbmc::InfoTagVideo::setMediaTypeRaw (CVideoInfoTag * infoTag, const String & mediaType) static
References CMediaTypes::IsValidMediaType(), and CVideoInfoTag::m_type.
Referenced by setMediaType().
setMpaaRaw()
void XBMCAddon::xbmc::InfoTagVideo::setMpaaRaw (CVideoInfoTag * infoTag, const String & mpaa) static
References CVideoInfoTag::SetMPAARating().
Referenced by setMpaa().
setOriginalTitleRaw()
void XBMCAddon::xbmc::InfoTagVideo::setOriginalTitleRaw (CVideoInfoTag * infoTag, const String & originalTitle) static
References CVideoInfoTag::SetOriginalTitle().
Referenced by setOriginalTitle().
setPathRaw()
void XBMCAddon::xbmc::InfoTagVideo::setPathRaw (CVideoInfoTag * infoTag, const String & path) static
References CVideoInfoTag::SetPath().
Referenced by setPath().
setPlaycountRaw()
void XBMCAddon::xbmc::InfoTagVideo::setPlaycountRaw (CVideoInfoTag * infoTag, int playcount) static
References CVideoInfoTag::SetPlayCount().
Referenced by setPlaycount().
setPlotOutlineRaw()
void XBMCAddon::xbmc::InfoTagVideo::setPlotOutlineRaw (CVideoInfoTag * infoTag, const String & plotOutline) static
References CVideoInfoTag::SetPlotOutline().
Referenced by setPlotOutline().
setPlotRaw()
void XBMCAddon::xbmc::InfoTagVideo::setPlotRaw (CVideoInfoTag * infoTag, const String & plot) static
References CVideoInfoTag::SetPlot().
Referenced by setPlot().
setPremieredRaw()
void XBMCAddon::xbmc::InfoTagVideo::setPremieredRaw (CVideoInfoTag * infoTag, const String & premiered) static
References CDateTime::SetFromDateString(), and CVideoInfoTag::SetPremiered().
Referenced by setPremiered().
setProductionCodeRaw()
void XBMCAddon::xbmc::InfoTagVideo::setProductionCodeRaw (CVideoInfoTag * infoTag, const String & productionCode) static
References CVideoInfoTag::SetProductionCode().
Referenced by setProductionCode().
setRatingRaw()
void XBMCAddon::xbmc::InfoTagVideo::setRatingRaw (CVideoInfoTag * infoTag, float rating, int votes = 0, const std::string & type = "", bool isDefault = false) static
References infoTag, and CVideoInfoTag::SetRating().
Referenced by setRating(), and XBMCAddon::xbmcgui::ListItem::setRating().
setRatingsRaw()
void XBMCAddon::xbmc::InfoTagVideo::setRatingsRaw (CVideoInfoTag * infoTag, const std::map< String, Tuple< float, int > > & ratings, const String & defaultRating = "") static
Referenced by setRatings().
setResumePointRaw()
void XBMCAddon::xbmc::InfoTagVideo::setResumePointRaw (CVideoInfoTag * infoTag, double time, double totalTime = 0.0) static
References CVideoInfoTag::GetResumePoint(), CVideoInfoTag::SetResumePoint(), and CBookmark::timeInSeconds.
Referenced by XBMCAddon::xbmcgui::ListItem::setProperty(), and setResumePoint().
setSeasonRaw()
void XBMCAddon::xbmc::InfoTagVideo::setSeasonRaw (CVideoInfoTag * infoTag, int season) static
References infoTag, and CVideoInfoTag::m_iSeason.
Referenced by setSeason().
setSetIdRaw()
void XBMCAddon::xbmc::InfoTagVideo::setSetIdRaw (CVideoInfoTag * infoTag, int setId) static
References CVideoInfoTag::SetInfo::id, infoTag, and CVideoInfoTag::m_set.
Referenced by setSetId().
setSetOverviewRaw()
void XBMCAddon::xbmc::InfoTagVideo::setSetOverviewRaw (CVideoInfoTag * infoTag, const String & setOverview) static
References CVideoInfoTag::SetSetOverview().
Referenced by setSetOverview().
setSetRaw()
void XBMCAddon::xbmc::InfoTagVideo::setSetRaw (CVideoInfoTag * infoTag, const String & set) static
References CVideoInfoTag::SetSet().
Referenced by setSet().
setShowLinksRaw()
void XBMCAddon::xbmc::InfoTagVideo::setShowLinksRaw (CVideoInfoTag * infoTag, std::vector< String > showLinks) static
References CVideoInfoTag::SetShowLink().
Referenced by setShowLinks().
setSortEpisodeRaw()
void XBMCAddon::xbmc::InfoTagVideo::setSortEpisodeRaw (CVideoInfoTag * infoTag, int sortEpisode) static
References infoTag, and CVideoInfoTag::m_iSpecialSortEpisode.
Referenced by setSortEpisode().
setSortSeasonRaw()
void XBMCAddon::xbmc::InfoTagVideo::setSortSeasonRaw (CVideoInfoTag * infoTag, int sortSeason) static
References infoTag, and CVideoInfoTag::m_iSpecialSortSeason.
Referenced by setSortSeason().
setSortTitleRaw()
void XBMCAddon::xbmc::InfoTagVideo::setSortTitleRaw (CVideoInfoTag * infoTag, const String & sortTitle) static
References CVideoInfoTag::SetSortTitle().
Referenced by setSortTitle().
setStudiosRaw()
void XBMCAddon::xbmc::InfoTagVideo::setStudiosRaw (CVideoInfoTag * infoTag, std::vector< String > studios) static
References CVideoInfoTag::SetStudio().
Referenced by setStudios().
setTagLineRaw()
void XBMCAddon::xbmc::InfoTagVideo::setTagLineRaw (CVideoInfoTag * infoTag, const String & tagLine) static
References CVideoInfoTag::SetTagLine().
Referenced by setTagLine().
setTagsRaw()
void XBMCAddon::xbmc::InfoTagVideo::setTagsRaw (CVideoInfoTag * infoTag, std::vector< String > tags) static
References CVideoInfoTag::SetTags(), and tags.
Referenced by setTags().
setTitleRaw()
void XBMCAddon::xbmc::InfoTagVideo::setTitleRaw (CVideoInfoTag * infoTag, const String & title) static
References CVideoInfoTag::SetTitle().
Referenced by setTitle().
setTop250Raw()
void XBMCAddon::xbmc::InfoTagVideo::setTop250Raw (CVideoInfoTag * infoTag, int top250) static
References infoTag, and CVideoInfoTag::m_iTop250.
Referenced by setTop250().
setTrackNumberRaw()
void XBMCAddon::xbmc::InfoTagVideo::setTrackNumberRaw (CVideoInfoTag * infoTag, int trackNumber) static
References infoTag, and CVideoInfoTag::m_iTrack.
Referenced by setTrackNumber().
setTrailerRaw()
void XBMCAddon::xbmc::InfoTagVideo::setTrailerRaw (CVideoInfoTag * infoTag, const String & trailer) static
References CVideoInfoTag::SetTrailer().
Referenced by setTrailer().
setTvShowStatusRaw()
void XBMCAddon::xbmc::InfoTagVideo::setTvShowStatusRaw (CVideoInfoTag * infoTag, const String & tvshowStatus) static
References CVideoInfoTag::SetStatus().
Referenced by setTvShowStatus().
setTvShowTitleRaw()
void XBMCAddon::xbmc::InfoTagVideo::setTvShowTitleRaw (CVideoInfoTag * infoTag, const String & tvshowTitle) static
References CVideoInfoTag::SetShowTitle().
Referenced by setTvShowTitle().
setUniqueIDRaw()
void XBMCAddon::xbmc::InfoTagVideo::setUniqueIDRaw (CVideoInfoTag * infoTag, const String & uniqueID, const String & type = "", bool isDefault = false) static
References infoTag, and CVideoInfoTag::SetUniqueID().
Referenced by setUniqueID().
setUniqueIDsRaw()
void XBMCAddon::xbmc::InfoTagVideo::setUniqueIDsRaw (CVideoInfoTag * infoTag, std::map< String, String > uniqueIDs, const String & defaultUniqueID = "") static
References infoTag, CVideoInfoTag::SetUniqueID(), and CVideoInfoTag::SetUniqueIDs().
Referenced by setUniqueIDs(), and XBMCAddon::xbmcgui::ListItem::setUniqueIDs().
setUserRatingRaw()
void XBMCAddon::xbmc::InfoTagVideo::setUserRatingRaw (CVideoInfoTag * infoTag, int userRating) static
References CVideoInfoTag::m_iUserRating.
Referenced by setUserRating().
setVideoAssetTitleRaw()
void XBMCAddon::xbmc::InfoTagVideo::setVideoAssetTitleRaw (CVideoInfoTag * infoTag, const String & videoAssetTitle) static
References CVideoInfoTag::GetAssetInfo(), and CVideoInfoTag::CAssetInfo::SetTitle().
Referenced by setVideoAssetTitle().
setVotesRaw()
void XBMCAddon::xbmc::InfoTagVideo::setVotesRaw (CVideoInfoTag * infoTag, int votes) static
References CVideoInfoTag::SetVotes().
Referenced by setVotes().
setWritersRaw()
void XBMCAddon::xbmc::InfoTagVideo::setWritersRaw (CVideoInfoTag * infoTag, std::vector< String > writers) static
References CVideoInfoTag::SetWritingCredits().
Referenced by setWriters().
setYearRaw()
void XBMCAddon::xbmc::InfoTagVideo::setYearRaw (CVideoInfoTag * infoTag, int year) static
References infoTag, and CVideoInfoTag::SetYear().
Referenced by setYear().
The documentation for this class was generated from the following files:
InfoTagVideo.h
InfoTagVideo.cpp