Kodi Documentation: KODI::GUILIB::GUIINFO::anonymous_namespace{GUIInfoHelper.cpp} Namespace Reference
KODI::GUILIB::GUIINFO::anonymous_namespace{GUIInfoHelper.cpp} Namespace Reference
Functions
bool CheckWindowCondition (CGUIWindow *window, int condition)
CGUIWindow * GetWindowWithCondition (int contextWindow, int condition)
Function Documentation
CheckWindowCondition()
bool KODI::GUILIB::GUIINFO::anonymous_namespace{GUIInfoHelper.cpp}::CheckWindowCondition (CGUIWindow * window, int condition)
References CheckWindowCondition(), CGUIWindow::HasListItems(), CGUIWindow::IsMediaWindow(), KODI::GUILIB::GUIINFO::WINDOW_CONDITION_HAS_LIST_ITEMS, and KODI::GUILIB::GUIINFO::WINDOW_CONDITION_IS_MEDIA_WINDOW.
Referenced by CheckWindowCondition(), and GetWindowWithCondition().
GetWindowWithCondition()
CGUIWindow * KODI::GUILIB::GUIINFO::anonymous_namespace{GUIInfoHelper.cpp}::GetWindowWithCondition (int contextWindow, int condition)
References CheckWindowCondition(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), and GetWindowWithCondition().
Referenced by GetWindowWithCondition().