Kodi Documentation: CZipManager Class Reference
CZipManager Class Reference
#include <ZipManager.h>
Public Member Functions
CZipManager ()
~CZipManager ()
bool GetZipList (const CURL &url, std::vector< SZipEntry > &items)
bool GetZipEntry (const CURL &url, SZipEntry &item)
bool ExtractArchive (const std::string &strArchive, const std::string &strPath)
bool ExtractArchive (const CURL &archive, const std::string &strPath)
void release (const std::string &strPath)
Static Public Member Functions
static void readHeader (const char *buffer, SZipEntry &info)
static void readCHeader (const char *buffer, SZipEntry &info)
Static Private Member Functions
template<typename T >
static T ReadUnaligned (const void *mem)
Private Attributes
std::map< std::string, std::vector< SZipEntry > > mZipMap
std::map< std::string, int64_t > mZipDate
Constructor & Destructor Documentation
CZipManager()
CZipManager::CZipManager () default
~CZipManager()
CZipManager::~CZipManager () default
Member Function Documentation
ExtractArchive() [1/2]
bool CZipManager::ExtractArchive (const CURL & archive, const std::string & strPath)
References XFILE::CFile::Copy(), URIUtils::CreateArchivePath(), and GetZipList().
ExtractArchive() [2/2]
bool CZipManager::ExtractArchive (const std::string & strArchive, const std::string & strPath)
References ExtractArchive().
Referenced by Extract(), and ExtractArchive().
GetZipEntry()
bool CZipManager::GetZipEntry (const CURL & url, SZipEntry & item)
References CURL::GetFileName(), CURL::GetHostName(), GetZipList(), and mZipMap.
Referenced by XFILE::CZipFile::Exists(), XFILE::CZipFile::Open(), and XFILE::CZipFile::Stat().
GetZipList()
bool CZipManager::GetZipList (const CURL & url, std::vector< SZipEntry > & items)
References __stat64, CHDR_SIZE, SZipEntry::clength, XFILE::CFile::Close(), ECDREC_SIZE, SZipEntry::eclength, Endian_SwapLE16, Endian_SwapLE32, SZipEntry::flags, SZipEntry::flength, g_charsetConverter, CURL::GetHostName(), XFILE::CFile::GetLength(), XFILE::CFile::GetPosition(), CURL::GetRedacted(), SZipEntry::header, int64_t(), LHDR_SIZE, CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, mZipDate, mZipMap, SZipEntry::name, XFILE::CFile::Open(), PATH_TRAVERSAL(), XFILE::CFile::Read(), readCHeader(), CRegExp::RegComp(), CRegExp::RegFind(), XFILE::CFile::Seek(), XFILE::CFile::Stat(), ZC_FLAG_EFS, ZIP_CENTRAL_HEADER, ZIP_DATA_RECORD_HEADER, ZIP_END_CENTRAL_HEADER, ZIP_LOCAL_HEADER, and ZIP_SPLIT_ARCHIVE_HEADER.
Referenced by XFILE::CZipDirectory::ContainsFiles(), ExtractArchive(), XFILE::CZipDirectory::GetDirectory(), and GetZipEntry().
readCHeader()
void CZipManager::readCHeader (const char * buffer, SZipEntry & info) static
References Endian_SwapLE16, and Endian_SwapLE32.
Referenced by GetZipList().
readHeader()
void CZipManager::readHeader (const char * buffer, SZipEntry & info) static
References Endian_SwapLE16, and Endian_SwapLE32.
Referenced by XFILE::CZipFile::UnpackFromMemory().
ReadUnaligned()
template<typename T > static T CZipManager::ReadUnaligned (const void * mem) inline static private
release()
void CZipManager::release (const std::string & strPath)
References CURL::GetHostName(), mZipDate, and mZipMap.
Referenced by CGUIWindowFileManager::GoParentFolder().
Member Data Documentation
mZipDate
std::map<std::string,int64_t> CZipManager::mZipDate private
Referenced by GetZipList(), and release().
mZipMap
std::map<std::string,std::vector<SZipEntry> > CZipManager::mZipMap private
Referenced by GetZipEntry(), GetZipList(), and release().
The documentation for this class was generated from the following files:
ZipManager.h
ZipManager.cpp