Kodi Documentation: PosixFile.cpp File Reference
PosixFile.cpp File Reference
#include "PosixFile.h"
#include "URL.h"
#include "filesystem/File.h"
#include "utils/AliasShortcutUtils.h"
#include "utils/log.h"
#include <algorithm>
#include <assert.h>
#include <errno.h>
#include <limits.h>
#include <string>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <sys/stat.h>
#include <unistd.h>
Functions
static std::string getFilename (const CURL &url)
Function Documentation
getFilename()
static std::string getFilename (const CURL & url) static
References CURL::GetFileName(), IsAliasShortcut(), and TranslateAliasShortcut().
Referenced by XFILE::CPosixFile::Delete(), XFILE::CPosixFile::Exists(), XFILE::CPosixFile::Open(), XFILE::CPosixFile::OpenForWrite(), XFILE::CPosixFile::Rename(), and XFILE::CPosixFile::Stat().