Kodi Documentation: CAESinkDARWINIOS Class Reference
CAESinkDARWINIOS Class Reference
#include <AESinkDARWINIOS.h>
Public Member Functions
const char * GetName () override
CAESinkDARWINIOS ()
~CAESinkDARWINIOS () override=default
bool Initialize (AEAudioFormat &format, std::string &device) override
void Deinitialize () override
void GetDelay (AEDelayStatus &status) override
Return a timestamped status structure with delay and sink info.
double GetCacheTotal () override
unsigned int AddPackets (uint8_t **data, unsigned int frames, unsigned int offset) override
Adds packets to be sent out, this routine MUST block or sleep.
void Drain () override
bool HasVolume () override
Public Member Functions inherited from IAESink
IAESink ()=default
virtual ~IAESink ()=default
virtual double GetLatency ()
virtual void AddPause (unsigned int millis)
instruct the sink to add a pause
virtual void SetVolume (float volume)
Static Public Member Functions
static void Register ()
static void EnumerateDevicesEx (AEDeviceInfoList &list, bool force)
static std::unique_ptr< IAESink > Create (std::string &device, AEAudioFormat &desiredFormat)
Private Attributes
CAEDeviceInfo m_info
AEAudioFormat m_format
CAAudioUnitSink * m_audioSink
Static Private Attributes
static AEDeviceInfoList m_devices
Constructor & Destructor Documentation
CAESinkDARWINIOS()
CAESinkDARWINIOS::CAESinkDARWINIOS ()
~CAESinkDARWINIOS()
CAESinkDARWINIOS::~CAESinkDARWINIOS () override default
Member Function Documentation
AddPackets()
unsigned int CAESinkDARWINIOS::AddPackets (uint8_t ** data, unsigned int frames, unsigned int offset) override virtual
Adds packets to be sent out, this routine MUST block or sleep.
Parameters
data array of pointers to planes holding audio data
frames number of audio frames in data
offset offset in frames where audio data starts
Returns
number of frames consumed by the sink
Implements IAESink.
References AE_FMT_FLOAT, data(), m_audioSink, AEAudioFormat::m_dataFormat, m_format, AEAudioFormat::m_frameSize, and CAAudioUnitSink::write().
Create()
std::unique_ptr< IAESink > CAESinkDARWINIOS::Create (std::string & device, AEAudioFormat & desiredFormat) static
Referenced by Register().
Deinitialize()
void CAESinkDARWINIOS::Deinitialize () override virtual
Implements IAESink.
References m_audioSink.
Drain()
void CAESinkDARWINIOS::Drain () override virtual
Reimplemented from IAESink.
References CAAudioUnitSink::drain(), and m_audioSink.
EnumerateDevicesEx()
void CAESinkDARWINIOS::EnumerateDevicesEx (AEDeviceInfoList & list, bool force) static
References EnumerateDevices(), and m_devices.
Referenced by Register().
GetCacheTotal()
double CAESinkDARWINIOS::GetCacheTotal () override virtual
Implements IAESink.
References CAAudioUnitSink::cacheSize(), and m_audioSink.
GetDelay()
void CAESinkDARWINIOS::GetDelay (AEDelayStatus & status) override virtual
Return a timestamped status structure with delay and sink info.
Parameters
status structure filled with sink status
Implements IAESink.
References CAAudioUnitSink::getDelay(), m_audioSink, and AEDelayStatus::SetDelay().
GetName()
const char * CAESinkDARWINIOS::GetName () inline override virtual
Implements IAESink.
HasVolume()
bool CAESinkDARWINIOS::HasVolume () override virtual
Reimplemented from IAESink.
Initialize()
bool CAESinkDARWINIOS::Initialize (AEAudioFormat & format, std::string & device) override virtual
Implements IAESink.
References AE_FMT_FLOAT, AE_FMT_RAW, AE_FMT_S16LE, CAAudioUnitSink::chunkSize(), CAEChannelInfo::Count(), CAEUtil::DataFormatToBits(), CAAudioUnitSink::getCoreAudioRealisedSampleRate(), CAAudioUnitSink::getRealisedSampleRate(), m_audioSink, CAEDeviceInfo::m_channels, m_devices, m_format, m_info, CAAudioUnitSink::open(), and CAAudioUnitSink::play().
Register()
void CAESinkDARWINIOS::Register () static
References Create(), AE::AESinkRegEntry::createFunc, EnumerateDevicesEx(), AE::AESinkRegEntry::enumerateFunc, AE::CAESinkFactory::RegisterSink(), and AE::AESinkRegEntry::sinkName.
Referenced by CWinSystemIOS::CWinSystemIOS().
Member Data Documentation
m_audioSink
CAAudioUnitSink* CAESinkDARWINIOS::m_audioSink private
Referenced by AddPackets(), Deinitialize(), Drain(), GetCacheTotal(), GetDelay(), and Initialize().
m_devices
AEDeviceInfoList CAESinkDARWINIOS::m_devices static private
Referenced by EnumerateDevicesEx(), and Initialize().
m_format
AEAudioFormat CAESinkDARWINIOS::m_format private
Referenced by AddPackets(), and Initialize().
m_info
CAEDeviceInfo CAESinkDARWINIOS::m_info private
Referenced by Initialize().
The documentation for this class was generated from the following files:
AESinkDARWINIOS.h
AESinkDARWINIOS.mm