Kodi Documentation: PVR::CPVREpgTagsContainer Class Reference
PVR::CPVREpgTagsContainer Class Reference
#include <EpgTagsContainer.h>
Public Member Functions
CPVREpgTagsContainer ()=delete
CPVREpgTagsContainer (int iEpgID, const std::shared_ptr< CPVREpgChannelData > &channelData, const std::shared_ptr< CPVREpgDatabase > &database)
virtual ~CPVREpgTagsContainer ()
void SetEpgID (int iEpgID)
Set the EPG id for this EPG.
void SetChannelData (const std::shared_ptr< CPVREpgChannelData > &data)
Set the channel data for this EPG.
bool UpdateEntry (const std::shared_ptr< CPVREpgInfoTag > &tag)
Update an entry.
bool DeleteEntry (const std::shared_ptr< CPVREpgInfoTag > &tag)
Delete an entry.
bool UpdateEntries (const CPVREpgTagsContainer &tags)
Update all entries with the provided tags.
void Clear ()
Release all entries.
void Cleanup (const CDateTime &time)
Remove all entries which were finished before the given time.
bool IsEmpty () const
Check whether this container is empty.
std::shared_ptr< CPVREpgInfoTag > GetTag (const CDateTime &startTime) const
Get an EPG tag given its start time.
std::shared_ptr< CPVREpgInfoTag > GetTag (unsigned int iUniqueBroadcastID) const
Get an EPG tag given its unique broadcast ID.
std::shared_ptr< CPVREpgInfoTag > GetTagByDatabaseID (int iDatabaseID) const
Get an EPG tag given its database ID.
std::shared_ptr< CPVREpgInfoTag > GetTagBetween (const CDateTime &start, const CDateTime &end) const
Get the event that occurs between the given begin and end time.
bool UpdateActiveTag ()
Update the currently active event.
std::shared_ptr< CPVREpgInfoTag > GetActiveTag () const
Get the event that is occurring now.
std::shared_ptr< CPVREpgInfoTag > GetNextStartingTag () const
Get the event that will occur next.
std::shared_ptr< CPVREpgInfoTag > GetLastEndedTag () const
Get the event that occurred previously.
std::vector< std::shared_ptr< CPVREpgInfoTag > > GetTimeline (const CDateTime &timelineStart, const CDateTime &timelineEnd, const CDateTime &minEventEnd, const CDateTime &maxEventStart) const
Get all EPG tags for the given time frame, including "gap" tags.
std::vector< std::shared_ptr< CPVREpgInfoTag > > GetAllTags () const
Get all EPG tags.
std::pair< CDateTime, CDateTime > GetFirstAndLastUncommitedEPGDate () const
Get the start and end time of the last not yet commited entry in this EPG.
bool NeedsSave () const
Check whether this container has unsaved data.
void QueuePersistQuery ()
Write the query to persist data into database's queue.
void QueueDelete ()
Queue the deletion of this container from its database.
Private Member Functions
std::vector< std::shared_ptr< CPVREpgInfoTag > > CreateEntries (const std::vector< std::shared_ptr< CPVREpgInfoTag > > &tags) const
Complete the instance data for the given tags.
std::shared_ptr< CPVREpgInfoTag > CreateEntry (const std::shared_ptr< CPVREpgInfoTag > &tag) const
Complete the instance data for the given tag.
std::shared_ptr< CPVREpgInfoTag > CreateGapTag (const CDateTime &start, const CDateTime &end) const
Create a "gap" tag.
void MergeTags (const CDateTime &minEventEnd, const CDateTime &maxEventStart, std::vector< std::shared_ptr< CPVREpgInfoTag > > &tags) const
Merge m_changedTags tags into given tags, resolving conflicts.
void FixOverlappingEvents (std::vector< std::shared_ptr< CPVREpgInfoTag > > &tags) const
Fix overlapping events.
void FixOverlappingEvents (std::map< CDateTime, std::shared_ptr< CPVREpgInfoTag > > &tags) const
Private Attributes
int m_iEpgID = 0
std::shared_ptr< CPVREpgChannelData > m_channelData
const std::shared_ptr< CPVREpgDatabase > m_database
const std::unique_ptr< CPVREpgTagsCache > m_tagsCache
std::map< CDateTime, std::shared_ptr< CPVREpgInfoTag > > m_changedTags
std::map< CDateTime, std::shared_ptr< CPVREpgInfoTag > > m_deletedTags
Constructor & Destructor Documentation
CPVREpgTagsContainer() [1/2]
PVR::CPVREpgTagsContainer::CPVREpgTagsContainer () delete
CPVREpgTagsContainer() [2/2]
CPVREpgTagsContainer::CPVREpgTagsContainer (int iEpgID, const std::shared_ptr< CPVREpgChannelData > & channelData, const std::shared_ptr< CPVREpgDatabase > & database)
~CPVREpgTagsContainer()
CPVREpgTagsContainer::~CPVREpgTagsContainer () virtual default
Member Function Documentation
Cleanup()
void CPVREpgTagsContainer::Cleanup (const CDateTime & time)
Remove all entries which were finished before the given time.
Parameters
time Delete entries with an end time before this time.
References m_changedTags, m_database, m_deletedTags, m_iEpgID, and m_tagsCache.
Referenced by PVR::CPVREpg::Cleanup().
Clear()
void CPVREpgTagsContainer::Clear ()
Release all entries.
References m_changedTags, and m_tagsCache.
Referenced by PVR::CPVREpg::Clear(), QueueDelete(), and QueuePersistQuery().
CreateEntries()
std::vector< std::shared_ptr< CPVREpgInfoTag > > CPVREpgTagsContainer::CreateEntries (const std::vector< std::shared_ptr< CPVREpgInfoTag > > & tags) const private
Complete the instance data for the given tags.
Parameters
tags The tags to complete.
Returns
The completed tags.
References m_channelData, and tags.
Referenced by GetAllTags(), GetTagBetween(), and GetTimeline().
CreateEntry()
std::shared_ptr< CPVREpgInfoTag > CPVREpgTagsContainer::CreateEntry (const std::shared_ptr< CPVREpgInfoTag > & tag) const private
Complete the instance data for the given tag.
Parameters
tags The tag to complete.
Returns
The completed tag.
References m_channelData.
Referenced by GetTag(), GetTag(), and GetTagByDatabaseID().
CreateGapTag()
std::shared_ptr< CPVREpgInfoTag > CPVREpgTagsContainer::CreateGapTag (const CDateTime & start, const CDateTime & end) const private
Create a "gap" tag.
Parameters
start The start time of the gap.
end The end time of the gap.
Returns
The tag.
References end(), m_channelData, and m_iEpgID.
Referenced by GetTimeline().
DeleteEntry()
bool CPVREpgTagsContainer::DeleteEntry (const std::shared_ptr< CPVREpgInfoTag > & tag)
Delete an entry.
Parameters
tag The tag to delete.
Returns
True if it was deleted successfully, false otherwise.
References m_changedTags, m_deletedTags, and m_tagsCache.
Referenced by PVR::CPVREpg::UpdateEntry().
FixOverlappingEvents() [1/2]
void CPVREpgTagsContainer::FixOverlappingEvents (std::map< CDateTime, std::shared_ptr< CPVREpgInfoTag > > & tags) const private
References m_tagsCache, and tags.
FixOverlappingEvents() [2/2]
void CPVREpgTagsContainer::FixOverlappingEvents (std::vector< std::shared_ptr< CPVREpgInfoTag > > & tags) const private
Fix overlapping events.
Parameters
tags The events to check/fix.
References m_tagsCache, and tags.
Referenced by GetAllTags(), MergeTags(), and QueuePersistQuery().
GetActiveTag()
std::shared_ptr< CPVREpgInfoTag > CPVREpgTagsContainer::GetActiveTag () const
Get the event that is occurring now.
Returns
The tag or nullptr if no tag was found.
References m_tagsCache.
Referenced by PVR::CPVREpg::GetTagNow().
GetAllTags()
std::vector< std::shared_ptr< CPVREpgInfoTag > > CPVREpgTagsContainer::GetAllTags () const
Get all EPG tags.
Returns
The tags.
References CreateEntries(), FixOverlappingEvents(), m_changedTags, m_database, m_iEpgID, and tags.
Referenced by PVR::CPVREpg::GetTags().
GetFirstAndLastUncommitedEPGDate()
std::pair< CDateTime, CDateTime > CPVREpgTagsContainer::GetFirstAndLastUncommitedEPGDate () const
Get the start and end time of the last not yet commited entry in this EPG.
Returns
The times; first: start time, second: end time.
References m_changedTags.
Referenced by PVR::CPVREpg::GetFirstAndLastUncommitedEPGDate().
GetLastEndedTag()
std::shared_ptr< CPVREpgInfoTag > CPVREpgTagsContainer::GetLastEndedTag () const
Get the event that occurred previously.
Returns
The tag or nullptr if no tag was found.
References m_tagsCache.
Referenced by PVR::CPVREpg::GetTagPrevious().
GetNextStartingTag()
std::shared_ptr< CPVREpgInfoTag > CPVREpgTagsContainer::GetNextStartingTag () const
Get the event that will occur next.
Returns
The tag or nullptr if no tag was found.
References m_tagsCache.
Referenced by PVR::CPVREpg::GetTagNext().
GetTag() [1/2]
std::shared_ptr< CPVREpgInfoTag > CPVREpgTagsContainer::GetTag (const CDateTime & startTime) const
Get an EPG tag given its start time.
Parameters
startTime The start time
Returns
The tag or nullptr if no tag was found.
References CreateEntry(), m_changedTags, m_database, and m_iEpgID.
Referenced by PVR::CPVREpg::GetTagByBroadcastId(), UpdateEntry(), and PVR::CPVREpg::UpdateEntry().
GetTag() [2/2]
std::shared_ptr< CPVREpgInfoTag > CPVREpgTagsContainer::GetTag (unsigned int iUniqueBroadcastID) const
Get an EPG tag given its unique broadcast ID.
Parameters
iUniqueBroadcastID The ID.
Returns
The tag or nullptr if no tag was found.
References CreateEntry(), EPG_TAG_INVALID_UID, m_changedTags, m_database, and m_iEpgID.
GetTagBetween()
std::shared_ptr< CPVREpgInfoTag > CPVREpgTagsContainer::GetTagBetween (const CDateTime & start, const CDateTime & end) const
Get the event that occurs between the given begin and end time.
Parameters
start The start of the time interval.
end The end of the time interval.
Returns
The tag or nullptr if no tag was found.
References CreateEntries(), end(), LOGWARNING, m_changedTags, m_database, m_iEpgID, and tags.
Referenced by PVR::CPVREpg::GetTagBetween().
GetTagByDatabaseID()
std::shared_ptr< CPVREpgInfoTag > CPVREpgTagsContainer::GetTagByDatabaseID (int iDatabaseID) const
Get an EPG tag given its database ID.
Parameters
iDatabaseID The ID.
Returns
The tag or nullptr if no tag was found.
References CreateEntry(), m_changedTags, m_database, and m_iEpgID.
Referenced by PVR::CPVREpg::GetTagByDatabaseId().
GetTimeline()
std::vector< std::shared_ptr< CPVREpgInfoTag > > CPVREpgTagsContainer::GetTimeline (const CDateTime & timelineStart, const CDateTime & timelineEnd, const CDateTime & minEventEnd, const CDateTime & maxEventStart) const
Get all EPG tags for the given time frame, including "gap" tags.
Parameters
timelineStart Start of time line
timelineEnd End of time line
minEventEnd The minimum end time of the events to return
maxEventStart The maximum start time of the events to return
Returns
The matching tags.
References CreateEntries(), CreateGapTag(), CDateTime::IsValid(), m_changedTags, m_database, m_iEpgID, MergeTags(), and tags.
Referenced by PVR::CPVREpg::GetTimeline().
IsEmpty()
bool CPVREpgTagsContainer::IsEmpty () const
Check whether this container is empty.
Returns
True if the container does not contain any entries, false otherwise.
References m_changedTags, m_database, and m_iEpgID.
Referenced by PVR::CPVREpg::Update().
MergeTags()
void CPVREpgTagsContainer::MergeTags (const CDateTime & minEventEnd, const CDateTime & maxEventStart, std::vector< std::shared_ptr< CPVREpgInfoTag > > & tags) const private
Merge m_changedTags tags into given tags, resolving conflicts.
Parameters
minEventEnd The minimum end time of the events to return
maxEventStart The maximum start time of the events to return
tags The merged tags.
References FixOverlappingEvents(), m_changedTags, and tags.
Referenced by GetTimeline().
NeedsSave()
bool CPVREpgTagsContainer::NeedsSave () const
Check whether this container has unsaved data.
Returns
True if this container contains unsaved data, false otherwise.
References m_changedTags, and m_deletedTags.
Referenced by PVR::CPVREpg::NeedsSave(), and PVR::CPVREpg::QueuePersistQuery().
QueueDelete()
void CPVREpgTagsContainer::QueueDelete ()
Queue the deletion of this container from its database.
References Clear(), m_database, and m_iEpgID.
Referenced by PVR::CPVREpg::QueueDeleteQueries().
QueuePersistQuery()
void CPVREpgTagsContainer::QueuePersistQuery ()
Write the query to persist data into database's queue.
References Clear(), FixOverlappingEvents(), LOGDEBUG, LOGEPG, m_changedTags, m_database, m_deletedTags, and m_iEpgID.
Referenced by PVR::CPVREpg::QueuePersistQuery().
SetChannelData()
void CPVREpgTagsContainer::SetChannelData (const std::shared_ptr< CPVREpgChannelData > & data)
Set the channel data for this EPG.
Parameters
data The channel data.
References data(), m_changedTags, m_channelData, and m_tagsCache.
Referenced by PVR::CPVREpg::SetChannelData().
SetEpgID()
void CPVREpgTagsContainer::SetEpgID (int iEpgID)
Set the EPG id for this EPG.
Parameters
iEpgID The ID.
References m_changedTags, and m_iEpgID.
Referenced by PVR::CPVREpg::QueuePersistQuery().
UpdateActiveTag()
bool CPVREpgTagsContainer::UpdateActiveTag ()
Update the currently active event.
Returns
True if the active event was updated, false otherwise.
References m_tagsCache.
Referenced by PVR::CPVREpg::CheckPlayingEvent().
UpdateEntries()
bool CPVREpgTagsContainer::UpdateEntries (const CPVREpgTagsContainer & tags)
Update all entries with the provided tags.
Parameters
tags The updated tags.
Returns
True if the update was successful, false otherwise.
References m_changedTags, m_channelData, m_database, m_iEpgID, m_tagsCache, t, tags, and UpdateEntry().
Referenced by PVR::CPVREpg::UpdateEntries().
UpdateEntry()
bool CPVREpgTagsContainer::UpdateEntry (const std::shared_ptr< CPVREpgInfoTag > & tag)
Update an entry.
Parameters
tag The tag to update.
Returns
True if it was updated successfully, false otherwise.
References GetTag(), m_changedTags, m_channelData, m_iEpgID, and m_tagsCache.
Referenced by PVR::CPVREpg::GetTagBetween(), UpdateEntries(), PVR::CPVREpg::UpdateEntry(), and PVR::CPVREpg::UpdateEntry().
Member Data Documentation
m_changedTags
std::map<CDateTime, std::shared_ptr<CPVREpgInfoTag> > PVR::CPVREpgTagsContainer::m_changedTags private
Referenced by Cleanup(), Clear(), DeleteEntry(), GetAllTags(), GetFirstAndLastUncommitedEPGDate(), GetTag(), GetTag(), GetTagBetween(), GetTagByDatabaseID(), GetTimeline(), IsEmpty(), MergeTags(), NeedsSave(), QueuePersistQuery(), SetChannelData(), SetEpgID(), UpdateEntries(), and UpdateEntry().
m_channelData
std::shared_ptr<CPVREpgChannelData> PVR::CPVREpgTagsContainer::m_channelData private
Referenced by CreateEntries(), CreateEntry(), CreateGapTag(), SetChannelData(), UpdateEntries(), and UpdateEntry().
m_database
const std::shared_ptr<CPVREpgDatabase> PVR::CPVREpgTagsContainer::m_database private
Referenced by Cleanup(), GetAllTags(), GetTag(), GetTag(), GetTagBetween(), GetTagByDatabaseID(), GetTimeline(), IsEmpty(), QueueDelete(), QueuePersistQuery(), and UpdateEntries().
m_deletedTags
std::map<CDateTime, std::shared_ptr<CPVREpgInfoTag> > PVR::CPVREpgTagsContainer::m_deletedTags private
Referenced by Cleanup(), DeleteEntry(), NeedsSave(), and QueuePersistQuery().
m_iEpgID
int PVR::CPVREpgTagsContainer::m_iEpgID = 0 private
Referenced by Cleanup(), CreateGapTag(), GetAllTags(), GetTag(), GetTag(), GetTagBetween(), GetTagByDatabaseID(), GetTimeline(), IsEmpty(), QueueDelete(), QueuePersistQuery(), SetEpgID(), UpdateEntries(), and UpdateEntry().
m_tagsCache
const std::unique_ptr<CPVREpgTagsCache> PVR::CPVREpgTagsContainer::m_tagsCache private
Referenced by Cleanup(), Clear(), DeleteEntry(), FixOverlappingEvents(), FixOverlappingEvents(), GetActiveTag(), GetLastEndedTag(), GetNextStartingTag(), SetChannelData(), UpdateActiveTag(), UpdateEntries(), and UpdateEntry().
The documentation for this class was generated from the following files:
EpgTagsContainer.h
EpgTagsContainer.cpp