Kodi Documentation: OVERLAY::COverlayGlyphGL Class Reference
OVERLAY::COverlayGlyphGL Class Reference
#include <OverlayRendererGL.h>
Classes
struct VERTEX
Public Member Functions
COverlayGlyphGL (ASS_Image *images, float width, float height)
~COverlayGlyphGL () override
void Render (SRenderState &state) override
Public Member Functions inherited from OVERLAY::COverlay
COverlay ()
virtual ~COverlay ()
Public Attributes
std::vector< VERTEX > m_vertex
GLuint m_texture = 0
float m_u
float m_v
Public Attributes inherited from OVERLAY::COverlay
enum OVERLAY::COverlay::EType m_type
enum OVERLAY::COverlay::EAlign m_align
enum OVERLAY::COverlay::EPosition m_pos
float m_x {0}
float m_y {0}
float m_width {1.0f}
float m_height {1.0f}
float m_source_width {0}
float m_source_height {0}
Additional Inherited Members
Public Types inherited from OVERLAY::COverlay
enum EType { TYPE_NONE , TYPE_TEXTURE }
enum EAlign { ALIGN_SCREEN , ALIGN_SCREEN_AR , ALIGN_VIDEO , ALIGN_SUBTITLE }
enum EPosition { POSITION_ABSOLUTE , POSITION_ABSOLUTE_SCREEN , POSITION_RELATIVE }
Static Public Member Functions inherited from OVERLAY::COverlay
static std::shared_ptr< COverlay > Create (const CDVDOverlayImage &o, CRect &rSource)
static std::shared_ptr< COverlay > Create (const CDVDOverlaySpu &o)
static std::shared_ptr< COverlay > Create (ASS_Image *images, float width, float height)
Protected Member Functions inherited from OVERLAY::COverlay
bool IsSquareResolution (float resRatio)
Given the resolution ratio determines if it is a 4/3 resolution.
Constructor & Destructor Documentation
COverlayGlyphGL()
COverlayGlyphGL::COverlayGlyphGL (ASS_Image * images, float width, float height)
References OVERLAY::COverlayGlyphGL::VERTEX::a, OVERLAY::SQuad::a, OVERLAY::COverlay::ALIGN_SCREEN, OVERLAY::COverlayGlyphGL::VERTEX::b, OVERLAY::SQuad::b, OVERLAY::convert_quad(), OVERLAY::COverlayGlyphGL::VERTEX::g, OVERLAY::SQuad::g, OVERLAY::SQuad::h, LoadTexture(), OVERLAY::COverlay::m_align, OVERLAY::COverlay::m_height, OVERLAY::COverlay::m_pos, m_texture, m_u, m_v, m_vertex, OVERLAY::COverlay::m_width, OVERLAY::COverlay::m_x, OVERLAY::COverlay::m_y, OVERLAY::COverlay::POSITION_RELATIVE, OVERLAY::SQuads::quad, OVERLAY::COverlayGlyphGL::VERTEX::r, OVERLAY::SQuad::r, OVERLAY::SQuads::size_x, OVERLAY::SQuads::size_y, OVERLAY::SQuads::texture, OVERLAY::COverlayGlyphGL::VERTEX::u, OVERLAY::SQuad::u, OVERLAY::COverlayGlyphGL::VERTEX::v, OVERLAY::SQuad::v, OVERLAY::SQuad::w, OVERLAY::COverlayGlyphGL::VERTEX::x, OVERLAY::SQuad::x, OVERLAY::COverlayGlyphGL::VERTEX::y, OVERLAY::SQuad::y, and OVERLAY::COverlayGlyphGL::VERTEX::z.
~COverlayGlyphGL()
COverlayGlyphGL::~COverlayGlyphGL () override
References m_texture.
Member Function Documentation
Render()
void COverlayGlyphGL::Render (SRenderState & state) override virtual
Implements OVERLAY::COverlay.
References CRenderSystemGL::DisableShader(), CRenderSystemGL::EnableShader(), CMatrixGLStack::Get(), CServiceBroker::GetRenderSystem(), glMatrixModview, glMatrixProject, OVERLAY::SRenderState::height, CMatrixGLStack::Load(), m_texture, m_vertex, CMatrixGL::MultMatrixf(), CMatrixGLStack::PopLoad(), CMatrixGLStack::Push(), CMatrixGL::Scalef(), CRenderSystemGL::ShaderGetCol(), CRenderSystemGL::ShaderGetCoord0(), CRenderSystemGL::ShaderGetDepth(), CRenderSystemGL::ShaderGetMatrix(), CRenderSystemGL::ShaderGetPos(), SM_FONTS, CMatrixGL::Translatef(), OVERLAY::SRenderState::width, OVERLAY::SRenderState::x, and OVERLAY::SRenderState::y.
Member Data Documentation
m_texture
GLuint OVERLAY::COverlayGlyphGL::m_texture = 0
Referenced by COverlayGlyphGL(), Render(), and ~COverlayGlyphGL().
m_u
float OVERLAY::COverlayGlyphGL::m_u
Referenced by COverlayGlyphGL().
m_v
float OVERLAY::COverlayGlyphGL::m_v
Referenced by COverlayGlyphGL().
m_vertex
std::vector<VERTEX> OVERLAY::COverlayGlyphGL::m_vertex
Referenced by COverlayGlyphGL(), and Render().
The documentation for this class was generated from the following files:
OverlayRendererGL.h
OverlayRendererGL.cpp