Kodi Documentation: CSettingsManager Class Reference
CSettingsManager Class Reference
Settings
Settings manager responsible for initializing, loading and handling all settings.
#include <SettingsManager.h>
Classes
struct Setting
struct SettingOptionsFiller
Public Member Functions
CSettingsManager ()
Creates a new (uninitialized) settings manager.
~CSettingsManager () override
std::shared_ptr< CSetting > CreateSetting (const std::string &settingType, const std::string &settingId, CSettingsManager *settingsManager=nullptr) const override
Creates a new setting of the given custom setting type.
std::shared_ptr< ISettingControl > CreateControl (const std::string &controlType) const override
Creates a new setting control of the given custom setting control type.
uint32_t GetVersion () const
uint32_t GetMinimumSupportedVersion () const
uint32_t ParseVersion (const TiXmlElement *root) const
Try to get the version of the setting definitions/values represented by the given XML element.
bool Initialize (const TiXmlElement *root)
Initializes the settings manager using the setting definitions represented by the given XML element.
bool Load (const TiXmlElement *root, bool &updated, bool triggerEvents=true, std::map< std::string, std::shared_ptr< CSetting > > *loadedSettings=nullptr)
Loads setting values from the given XML element.
bool Save (const ISettingsValueSerializer *serializer, std::string &serializedValues) const
Saves the setting values using the given serializer.
void Unload ()
Unloads the previously loaded setting values.
void Clear ()
Clears the complete settings manager.
bool LoadSetting (const TiXmlNode *node, const std::string &settingId)
Loads the setting being represented by the given XML node with the given identifier.
bool LoadSetting (const TiXmlNode *node, const std::string &settingId, bool &updated)
Loads the setting being represented by the given XML node with the given identifier.
void SetInitialized ()
Tells the settings system that the initialization is complete.
bool IsInitialized () const
Returns whether the settings system has been initialized or not.
void SetLoaded ()
Tells the settings system that all setting values have been loaded.
bool IsLoaded () const
Returns whether the settings system has been loaded or not.
void AddSection (const std::shared_ptr< CSettingSection > &section)
Adds the given section, its categories, groups and settings.
bool AddSetting (const std::shared_ptr< CSetting > &setting, const std::shared_ptr< CSettingSection > &section, const std::shared_ptr< CSettingCategory > &category, const std::shared_ptr< CSettingGroup > &group)
Adds the given setting to the given group in the given category in the given section;.
void RegisterCallback (ISettingCallback *callback, const std::set< std::string > &settingList)
Registers the given ISettingCallback implementation to be triggered for the given list of settings.
void UnregisterCallback (ISettingCallback *callback)
Unregisters the given ISettingCallback implementation.
void RegisterSettingType (const std::string &settingType, ISettingCreator *settingCreator)
Registers a custom setting type and its ISettingCreator implementation.
void RegisterSettingControl (const std::string &controlType, ISettingControlCreator *settingControlCreator)
Registers a custom setting control type and its ISettingControlCreator implementation.
void RegisterSettingsHandler (ISettingsHandler *settingsHandler, bool bFront=false)
Registers the given ISettingsHandler implementation.
void UnregisterSettingsHandler (ISettingsHandler *settingsHandler)
Unregisters the given ISettingsHandler implementation.
void RegisterSettingOptionsFiller (const std::string &identifier, IntegerSettingOptionsFiller optionsFiller)
Registers the given integer setting options filler under the given identifier.
void RegisterSettingOptionsFiller (const std::string &identifier, StringSettingOptionsFiller optionsFiller)
Registers the given string setting options filler under the given identifier.
void UnregisterSettingOptionsFiller (const std::string &identifier)
Unregisters the setting options filler registered under the given identifier.
void * GetSettingOptionsFiller (const std::shared_ptr< const CSetting > &setting)
Gets the implementation of the setting options filler used by the given setting.
bool HasSettings () const
Checks whether any settings have been initialized.
std::shared_ptr< CSetting > GetSetting (const std::string &id) const
Gets the setting with the given identifier.
std::vector< std::shared_ptr< CSettingSection > > GetSections () const
Gets the full list of setting sections.
std::shared_ptr< CSettingSection > GetSection (std::string section) const
Gets the setting section with the given identifier.
SettingDependencyMap GetDependencies (const std::string &id) const
Gets a map of settings (and their dependencies) which depend on the setting with the given identifier.
SettingDependencyMap GetDependencies (const std::shared_ptr< const CSetting > &setting) const
Gets a map of settings (and their dependencies) which depend on the given setting.
bool GetBool (const std::string &id) const
Gets the boolean value of the setting with the given identifier.
int GetInt (const std::string &id) const
Gets the integer value of the setting with the given identifier.
double GetNumber (const std::string &id) const
Gets the real number value of the setting with the given identifier.
std::string GetString (const std::string &id) const
Gets the string value of the setting with the given identifier.
std::vector< std::shared_ptr< CSetting > > GetList (const std::string &id) const
Gets the values of the list setting with the given identifier.
bool SetBool (const std::string &id, bool value)
Sets the boolean value of the setting with the given identifier.
bool ToggleBool (const std::string &id)
Toggles the boolean value of the setting with the given identifier.
bool SetInt (const std::string &id, int value)
Sets the integer value of the setting with the given identifier.
bool SetNumber (const std::string &id, double value)
Sets the real number value of the setting with the given identifier.
bool SetString (const std::string &id, const std::string &value)
Sets the string value of the setting with the given identifier.
bool SetList (const std::string &id, const std::vector< std::shared_ptr< CSetting > > &value)
Sets the values of the list setting with the given identifier.
bool SetDefault (const std::string &id)
Sets the value of the setting to its default.
void SetDefaults ()
Sets the value of all settings to their default.
const CSettingConditionsManager & GetConditions () const
Gets the setting conditions manager used by the settings manager.
void AddCondition (const std::string &condition)
Adds the given static condition.
void AddDynamicCondition (const std::string &identifier, SettingConditionCheck condition, void *data=nullptr)
Adds the given dynamic condition.
void RemoveDynamicCondition (const std::string &identifier)
Removes the given dynamic condition.
Public Member Functions inherited from ISettingCreator
virtual ~ISettingCreator ()=default
Public Member Functions inherited from ISettingControlCreator
virtual ~ISettingControlCreator ()=default
Static Public Attributes
static const uint32_t Version = 2
static const uint32_t MinimumSupportedVersion = 0
Private Types
enum class SettingOptionsFillerType { Unknown = 0 , Integer , String }
using CallbackSet = std::set< ISettingCallback * >
using SettingMap = std::map< std::string, Setting >
using SettingSectionMap = std::map< std::string, std::shared_ptr< CSettingSection > >
using SettingCreatorMap = std::map< std::string, ISettingCreator * >
using SettingControlCreatorMap = std::map< std::string, ISettingControlCreator * >
using SettingsHandlers = std::vector< ISettingsHandler * >
using SettingOptionsFillerMap = std::map< std::string, SettingOptionsFiller >
Private Member Functions
bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting is being changed.
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
void OnSettingAction (const std::shared_ptr< const CSetting > &setting) override
The given setting has been activated.
bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode) override
The given setting needs to be updated.
void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName) override
The given property of the given setting has changed.
bool OnSettingsLoading () override
Settings loading has been initiated.
void OnSettingsLoaded () override
Settings have been loaded.
void OnSettingsUnloaded () override
Setting values have been unloaded.
bool OnSettingsSaving () const override
Settings saving has been initiated.
void OnSettingsSaved () const override
Settings have been saved.
void OnSettingsCleared () override
Settings have been cleared.
bool Serialize (TiXmlNode *parent) const
bool Deserialize (const TiXmlNode *node, bool &updated, std::map< std::string, std::shared_ptr< CSetting > > *loadedSettings=nullptr)
bool LoadSetting (const TiXmlNode *node, const std::shared_ptr< CSetting > &setting, bool &updated)
bool UpdateSetting (const TiXmlNode *node, const std::shared_ptr< CSetting > &setting, const CSettingUpdate &update)
void UpdateSettingByDependency (const std::string &settingId, const CSettingDependency &dependency)
void UpdateSettingByDependency (const std::string &settingId, SettingDependencyType dependencyType)
void AddSetting (const std::shared_ptr< CSetting > &setting)
void ResolveReferenceSettings (const std::shared_ptr< CSettingSection > &section)
void CleanupIncompleteSettings ()
void RegisterSettingOptionsFiller (const std::string &identifier, void *filler, SettingOptionsFillerType type)
void RefreshVisibilityAndEnableStatus (const std::shared_ptr< const CSetting > &setting)
Refresh the visibility and enable status of a given setting.
void ResolveSettingDependencies (const std::shared_ptr< CSetting > &setting)
void ResolveSettingDependencies (const Setting &setting)
SettingMap::const_iterator FindSetting (std::string settingId) const
SettingMap::iterator FindSetting (std::string settingId)
std::pair< SettingMap::iterator, bool > InsertSetting (std::string settingId, const Setting &setting)
Private Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
Private Member Functions inherited from ISettingsHandler
virtual ~ISettingsHandler ()=default
Private Attributes
bool m_initialized = false
bool m_loaded = false
SettingMap m_settings
SettingSectionMap m_sections
SettingCreatorMap m_settingCreators
SettingControlCreatorMap m_settingControlCreators
SettingsHandlers m_settingsHandlers
CSettingConditionsManager m_conditions
SettingOptionsFillerMap m_optionsFillers
CSharedSection m_critical
CSharedSection m_settingsCritical
Logger m_logger
Detailed Description
Settings manager responsible for initializing, loading and handling all settings.
Member Typedef Documentation
CallbackSet
using CSettingsManager::CallbackSet = std::set<ISettingCallback *> private
SettingControlCreatorMap
using CSettingsManager::SettingControlCreatorMap = std::map<std::string, ISettingControlCreator*> private
SettingCreatorMap
using CSettingsManager::SettingCreatorMap = std::map<std::string, ISettingCreator*> private
SettingMap
using CSettingsManager::SettingMap = std::map<std::string, Setting> private
SettingOptionsFillerMap
using CSettingsManager::SettingOptionsFillerMap = std::map<std::string, SettingOptionsFiller> private
SettingSectionMap
using CSettingsManager::SettingSectionMap = std::map<std::string, std::shared_ptr<CSettingSection> > private
SettingsHandlers
using CSettingsManager::SettingsHandlers = std::vector<ISettingsHandler*> private
Member Enumeration Documentation
SettingOptionsFillerType
enum class CSettingsManager::SettingOptionsFillerType strong private
Enumerator
Unknown
Integer
String
Constructor & Destructor Documentation
CSettingsManager()
CSettingsManager::CSettingsManager ()
Creates a new (uninitialized) settings manager.
~CSettingsManager()
CSettingsManager::~CSettingsManager () override
References Clear(), m_settingControlCreators, m_settingCreators, and m_settingsHandlers.
Member Function Documentation
AddCondition()
void CSettingsManager::AddCondition (const std::string & condition)
Adds the given static condition.
A static condition is just a string. If a static condition is evaluated, the result depends on whether the condition's value is defined or not.
Parameters
condition Static condition string/value
References CSettingConditionsManager::AddCondition(), m_conditions, and m_critical.
Referenced by ADDON::CAddonSettings::InitializeConditions(), and CSettings::InitializeConditions().
AddDynamicCondition()
void CSettingsManager::AddDynamicCondition (const std::string & identifier, SettingConditionCheck condition, void * data = nullptr)
Adds the given dynamic condition.
A dynamic condition has an identifier and an implementation which is triggered when the condition is evaluated.
Parameters
identifier Identifier of the dynamic condition
condition Implementation of the dynamic condition
data Opaque data pointer, will be passed back to SettingConditionCheck function
References CSettingConditionsManager::AddDynamicCondition(), data(), m_conditions, and m_critical.
Referenced by PVR::CGUIDialogPVRTimerSettings::AddCondition(), ADDON::CAddonSettings::InitializeConditions(), CSettings::InitializeConditions(), CGUIDialogAudioSettings::InitializeSettings(), and CApplicationSettingsHandling::RegisterSettings().
AddSection()
void CSettingsManager::AddSection (const std::shared_ptr< CSettingSection > & section)
Adds the given section, its categories, groups and settings.
This is possible before and after the setting definitions have been initialized.
References AddSetting(), CleanupIncompleteSettings(), m_critical, m_initialized, m_sections, m_settingsCritical, ResolveReferenceSettings(), and ResolveSettingDependencies().
Referenced by AddSetting(), Initialize(), ADDON::CAddonSettings::InitializeFromOldSettingDefinitions(), and CGUIDialogSettingsManualBase::SetupView().
AddSetting() [1/2]
void CSettingsManager::AddSetting (const std::shared_ptr< CSetting > & setting) private
References FindSetting(), InsertSetting(), and m_settings.
AddSetting() [2/2]
bool CSettingsManager::AddSetting (const std::shared_ptr< CSetting > & setting, const std::shared_ptr< CSettingSection > & section, const std::shared_ptr< CSettingCategory > & category, const std::shared_ptr< CSettingGroup > & group)
Adds the given setting to the given group in the given category in the given section;.
If the given section has not been added yet, it is added. If the given category has not been added to the given section yet, it is added. If the given group has not been added to the given category yet, it is added. If the given setting has not been added to the given group yet, it is added.
This is possible before and after the setting definitions have been initialized.
Parameters
setting New setting to be added
section Section the new setting should be added to
category Category the new setting should be added to
group Group the new setting should be added to
Returns
True if the setting has been added, false otherwise
References AddSection(), AddSetting(), CleanupIncompleteSettings(), FindSetting(), GetSection(), m_critical, m_initialized, m_settings, m_settingsCritical, and ResolveSettingDependencies().
Referenced by AddSection(), AddSetting(), and anonymous_namespace{AddonSettings.cpp}::AddSettingWithoutDefinition().
CleanupIncompleteSettings()
void CSettingsManager::CleanupIncompleteSettings () private
References m_logger, and m_settings.
Referenced by AddSection(), AddSetting(), and SetInitialized().
Clear()
void CSettingsManager::Clear ()
Clears the complete settings manager.
This removes all initialized settings, groups, categories and sections and returns to the uninitialized state. Any registered callbacks or implementations stay registered.
References m_critical, m_initialized, m_sections, m_settings, OnSettingsCleared(), and Unload().
Referenced by CSettings::Clear(), CGUIDialogSettingsManualBase::InitializeSettings(), CSettingsBase::Uninitialize(), CGUIDialogSettingsManualBase::~CGUIDialogSettingsManualBase(), and ~CSettingsManager().
CreateControl()
std::shared_ptr< ISettingControl > CSettingsManager::CreateControl (const std::string & controlType) const override virtual
Creates a new setting control of the given custom setting control type.
Parameters
controlType string representation of the setting control type
Returns
A new setting control object of the given (custom) setting control type or nullptr if the setting control type is unknown
Implements ISettingControlCreator.
References m_critical, and m_settingControlCreators.
Referenced by CSetting::Copy(), CGUIDialogSettingsManagerBase::CreateControl(), CSetting::Deserialize(), and CSettingGroup::Deserialize().
CreateSetting()
SettingPtr CSettingsManager::CreateSetting (const std::string & settingType, const std::string & settingId, CSettingsManager * settingsManager = nullptr) const override virtual
Creates a new setting of the given custom setting type.
Parameters
settingType string representation of the setting type
settingId Identifier of the setting to be created
settingsManager Reference to the settings manager
Returns
A new setting object of the given (custom) setting type or nullptr if the setting type is unknown
Implements ISettingCreator.
References CreateSetting(), m_critical, and m_settingCreators.
Referenced by CreateSetting(), and CSettingGroup::Deserialize().
Deserialize()
bool CSettingsManager::Deserialize (const TiXmlNode * node, bool & updated, std::map< std::string, std::shared_ptr< CSetting > > * loadedSettings = nullptr) private
References LoadSetting(), m_settings, m_settingsCritical, and node.
Referenced by Load().
FindSetting() [1/2]
CSettingsManager::SettingMap::iterator CSettingsManager::FindSetting (std::string settingId) private
References m_settings.
FindSetting() [2/2]
CSettingsManager::SettingMap::const_iterator CSettingsManager::FindSetting (std::string settingId) const private
References m_settings.
Referenced by AddSetting(), AddSetting(), GetDependencies(), GetSetting(), OnSettingAction(), OnSettingChanged(), OnSettingChanging(), OnSettingPropertyChanged(), OnSettingUpdate(), RegisterCallback(), ResolveReferenceSettings(), ResolveSettingDependencies(), ResolveSettingDependencies(), and UpdateSettingByDependency().
GetBool()
bool CSettingsManager::GetBool (const std::string & id) const
Gets the boolean value of the setting with the given identifier.
Parameters
id Setting identifier
Returns
Boolean value of the setting with the given identifier
References Boolean, GetSetting(), and m_settingsCritical.
Referenced by CSettingsBase::GetBool().
GetConditions()
const CSettingConditionsManager & CSettingsManager::GetConditions () const inline
Gets the setting conditions manager used by the settings manager.
Returns
Setting conditions manager used by the settings manager.
References m_conditions.
Referenced by CSettingCategoryAccessCondition::Check(), CSettingConditionItem::Check(), CSettingDependencyCondition::Check(), and CSettingRequirementCondition::Check().
GetDependencies() [1/2]
SettingDependencyMap CSettingsManager::GetDependencies (const std::shared_ptr< const CSetting > & setting) const
Gets a map of settings (and their dependencies) which depend on the given setting.
It is important to note that the returned dependencies are not the dependencies of the given setting but the settings (and their dependencies) which depend on the given setting.
Parameters
setting Setting object
Returns
Map of settings (and their dependencies) which depend on the given setting
GetDependencies() [2/2]
SettingDependencyMap CSettingsManager::GetDependencies (const std::string & id) const
Gets a map of settings (and their dependencies) which depend on the setting with the given identifier.
It is important to note that the returned dependencies are not the dependencies of the setting with the given identifier but the settings (and their dependencies) which depend on the setting with the given identifier.
Parameters
id Setting identifier
Returns
Map of settings (and their dependencies) which depend on the setting with the given identifier
References FindSetting(), m_settings, and m_settingsCritical.
Referenced by OnSettingChanged().
GetInt()
int CSettingsManager::GetInt (const std::string & id) const
Gets the integer value of the setting with the given identifier.
Parameters
id Setting identifier
Returns
Integer value of the setting with the given identifier
References GetSetting(), Integer, and m_settingsCritical.
Referenced by CSettingsBase::GetInt().
GetList()
std::vector< std::shared_ptr< CSetting > > CSettingsManager::GetList (const std::string & id) const
Gets the values of the list setting with the given identifier.
Parameters
id Setting identifier
Returns
List of values of the setting with the given identifier
References GetSetting(), List, and m_settingsCritical.
GetMinimumSupportedVersion()
uint32_t CSettingsManager::GetMinimumSupportedVersion () const inline
References MinimumSupportedVersion.
GetNumber()
double CSettingsManager::GetNumber (const std::string & id) const
Gets the real number value of the setting with the given identifier.
Parameters
id Setting identifier
Returns
Real number value of the setting with the given identifier
References GetSetting(), m_settingsCritical, and Number.
Referenced by CSettingsBase::GetNumber().
GetSection()
SettingSectionPtr CSettingsManager::GetSection (std::string section) const
Gets the setting section with the given identifier.
Parameters
section Setting section identifier
Returns
Setting section with the given identifier or nullptr if the identifier is unknown
References m_critical, m_logger, and m_sections.
Referenced by AddSetting(), and CSettingsBase::GetSection().
GetSections()
SettingSectionList CSettingsManager::GetSections () const
Gets the full list of setting sections.
Returns
List of setting sections
References m_critical, and m_sections.
Referenced by anonymous_namespace{AddonSettings.cpp}::AddSettingWithoutDefinition(), CSettingsBase::GetSections(), CSettingsValueFlatJsonSerializer::SerializeValues(), and CSettingsValueXmlSerializer::SerializeValues().
GetSetting()
SettingPtr CSettingsManager::GetSetting (const std::string & id) const
Gets the setting with the given identifier.
Parameters
id Setting identifier
Returns
Setting object with the given identifier or nullptr if the identifier is unknown
References FindSetting(), GetSetting(), m_logger, m_settings, and m_settingsCritical.
Referenced by CSettingConditionItem::Check(), CSettingDependencyCondition::Check(), GetBool(), GetInt(), GetList(), CSettingsBase::GetList(), GetNumber(), GetSetting(), CSettingsBase::GetSetting(), CGUIDialogSettingsManagerBase::GetSetting(), GetString(), CSettings::InitializeDefaults(), CSetting::IsEnabled(), LoadSetting(), CGUIDialogAddonSettings::OnMessage(), SetBool(), SetDefault(), SetInt(), CSettingsBase::SetList(), SetList(), SetNumber(), SetString(), and ToggleBool().
GetSettingOptionsFiller()
void * CSettingsManager::GetSettingOptionsFiller (const std::shared_ptr< const CSetting > & setting)
Gets the implementation of the setting options filler used by the given setting.
Parameters
setting Setting object
Returns
Implementation of the setting options filler (either IntegerSettingOptionsFiller or StringSettingOptionsFiller)
References Integer, Integer, m_critical, m_optionsFillers, String, and String.
Referenced by CSettingInt::Deserialize(), CSettingString::Deserialize(), CSettingInt::UpdateDynamicOptions(), and CSettingString::UpdateDynamicOptions().
GetString()
std::string CSettingsManager::GetString (const std::string & id) const
Gets the string value of the setting with the given identifier.
Parameters
id Setting identifier
Returns
String value of the setting with the given identifier
References GetSetting(), m_settingsCritical, and String.
Referenced by CSettingsBase::GetString().
GetVersion()
uint32_t CSettingsManager::GetVersion () const inline
References Version.
Referenced by CSettingsValueXmlSerializer::SerializeValues().
HasSettings()
bool CSettingsManager::HasSettings () const
Checks whether any settings have been initialized.
Returns
True if at least one setting has been initialized, false otherwise
References m_settings.
Referenced by ADDON::CAddonSettings::HasSettings().
Initialize()
bool CSettingsManager::Initialize (const TiXmlElement * root)
Initializes the settings manager using the setting definitions represented by the given XML element.
Parameters
root XML element representing setting definitions
Returns
True if the XML element was successfully deserialized into setting definitions, false otherwise
References AddSection(), ISetting::DeserializeIdentification(), m_critical, m_initialized, m_logger, m_sections, m_settingsCritical, MinimumSupportedVersion, ParseVersion(), root, SETTING_XML_ELM_SECTION, SETTING_XML_ROOT, SETTING_XML_ROOT_VERSION, and Version.
Referenced by AdvancedSettingsResetBase::AdvancedSettingsResetBase(), anonymous_namespace{TestArtUtils.cpp}::AdvancedSettingsResetBase::AdvancedSettingsResetBase(), and CSettingsBase::InitializeDefinitionsFromXml().
InsertSetting()
std::pair< CSettingsManager::SettingMap::iterator, bool > CSettingsManager::InsertSetting (std::string settingId, const Setting & setting) private
References m_settings.
Referenced by AddSetting(), and RegisterCallback().
IsInitialized()
bool CSettingsManager::IsInitialized () const inline
Returns whether the settings system has been initialized or not.
References m_initialized.
Referenced by CSettingsBase::IsInitialized().
IsLoaded()
bool CSettingsManager::IsLoaded () const inline
Returns whether the settings system has been loaded or not.
References m_loaded.
Referenced by CSettingsBase::IsLoaded().
Load()
bool CSettingsManager::Load (const TiXmlElement * root, bool & updated, bool triggerEvents = true, std::map< std::string, std::shared_ptr< CSetting > > * loadedSettings = nullptr)
Loads setting values from the given XML element.
Parameters
root XML element containing setting values
updated Whether some settings were automatically updated
triggerEvents Whether to trigger ISettingCallback methods
loadedSettings A list to fill with all the successfully loaded settings
Returns
True if the setting values were successfully loaded, false otherwise
References Deserialize(), m_critical, m_loaded, m_logger, m_settingsCritical, MinimumSupportedVersion, OnSettingsLoaded(), OnSettingsLoading(), ParseVersion(), root, SETTING_XML_ROOT_VERSION, and Version.
Referenced by CSettingsBase::LoadHiddenValuesFromXml(), CSettingsBase::LoadValuesFromXml(), and CSettingsBase::LoadValuesFromXml().
LoadSetting() [1/3]
bool CSettingsManager::LoadSetting (const TiXmlNode * node, const std::shared_ptr< CSetting > & setting, bool & updated) private
References Action, m_logger, node, ParseSettingIdentifier(), SETTING_XML_ATTR_ID, SETTING_XML_ELM_DEFAULT, SETTING_XML_ELM_SETTING, and UpdateSetting().
LoadSetting() [2/3]
bool CSettingsManager::LoadSetting (const TiXmlNode * node, const std::string & settingId)
Loads the setting being represented by the given XML node with the given identifier.
Parameters
node XML node representing the setting to load
settingId Setting identifier
Returns
True if the setting was successfully loaded from the given XML node, false otherwise
References LoadSetting(), and node.
Referenced by Deserialize(), LoadSetting(), CSettings::LoadSetting(), and LoadSetting().
LoadSetting() [3/3]
bool CSettingsManager::LoadSetting (const TiXmlNode * node, const std::string & settingId, bool & updated)
Loads the setting being represented by the given XML node with the given identifier.
Parameters
node XML node representing the setting to load
settingId Setting identifier
updated Set to true if the setting's value was updated
Returns
True if the setting was successfully loaded from the given XML node, false otherwise
References GetSetting(), LoadSetting(), and node.
OnSettingAction()
void CSettingsManager::OnSettingAction (const std::shared_ptr< const CSetting > & setting) override private virtual
The given setting has been activated.
This callback is triggered whenever the given setting has been activated. This callback is only fired for CSettingAction settings.
Parameters
setting The setting which has been activated.
Reimplemented from ISettingCallback.
References CSettingsManager::Setting::callbacks, FindSetting(), m_loaded, m_settings, and m_settingsCritical.
Referenced by CGUIDialogAddonSettings::OnSettingAction().
OnSettingChanged()
void CSettingsManager::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override private virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References CSettingsManager::Setting::callbacks, FindSetting(), GetDependencies(), m_loaded, m_settings, m_settingsCritical, and UpdateSettingByDependency().
OnSettingChanging()
bool CSettingsManager::OnSettingChanging (const std::shared_ptr< const CSetting > & setting) override private virtual
The value of the given setting is being changed.
This callback is triggered whenever the value of a setting is being changed. The given CSetting already contains the new value and the handler of the callback has the possibility to allow or revert changing the value of the setting. In case of a revert OnSettingChanging() is called again to inform all listeners that the value change has been reverted.
Parameters
setting The setting whose value is being changed (already containing the changed value)
Returns
True if the new value is acceptable otherwise false
Reimplemented from ISettingCallback.
References CSettingsManager::Setting::callbacks, FindSetting(), m_loaded, m_settings, m_settingsCritical, CSettingsManager::Setting::references, and CSettingsManager::Setting::setting.
OnSettingPropertyChanged()
void CSettingsManager::OnSettingPropertyChanged (const std::shared_ptr< const CSetting > & setting, const char * propertyName) override private virtual
The given property of the given setting has changed.
This callback is triggered when a property (e.g. enabled or the list of dynamic options) has changed.
Parameters
setting The setting which has a changed property
propertyName The string representation of the changed property
Reimplemented from ISettingCallback.
References CSettingsManager::Setting::callbacks, Enable, FindSetting(), m_loaded, m_settings, m_settingsCritical, Unknown, UpdateSettingByDependency(), and Visible.
Referenced by RefreshVisibilityAndEnableStatus(), and UpdateSettingByDependency().
OnSettingsCleared()
void CSettingsManager::OnSettingsCleared () override private virtual
Settings have been cleared.
This callback can be used to trigger clearing any state variables.
Reimplemented from ISettingsHandler.
References m_critical, and m_settingsHandlers.
Referenced by Clear().
OnSettingsLoaded()
void CSettingsManager::OnSettingsLoaded () override private virtual
Settings have been loaded.
This callback can be used to trigger loading other settings.
Reimplemented from ISettingsHandler.
References m_critical, and m_settingsHandlers.
Referenced by Load().
OnSettingsLoading()
bool CSettingsManager::OnSettingsLoading () override private virtual
Settings loading has been initiated.
Returns
True if the settings should be loaded, false if the loading should be aborted.
Reimplemented from ISettingsHandler.
References m_critical, and m_settingsHandlers.
Referenced by Load().
OnSettingsSaved()
void CSettingsManager::OnSettingsSaved () const override private virtual
Settings have been saved.
This callback can be used to trigger saving other settings.
Reimplemented from ISettingsHandler.
References m_critical, and m_settingsHandlers.
Referenced by Save().
OnSettingsSaving()
bool CSettingsManager::OnSettingsSaving () const override private virtual
Settings saving has been initiated.
Returns
True if the settings should be saved, false if the saving should be aborted.
Reimplemented from ISettingsHandler.
References m_critical, and m_settingsHandlers.
Referenced by Save().
OnSettingsUnloaded()
void CSettingsManager::OnSettingsUnloaded () override private virtual
Setting values have been unloaded.
This callback can be used to trigger uninitializing any state variables (e.g. before re-loading the settings).
Reimplemented from ISettingsHandler.
References m_critical, and m_settingsHandlers.
Referenced by Unload().
OnSettingUpdate()
bool CSettingsManager::OnSettingUpdate (const std::shared_ptr< CSetting > & setting, const char * oldSettingId, const TiXmlNode * oldSettingNode) override private virtual
The given setting needs to be updated.
This callback is triggered when a setting needs to be updated because its value is outdated. This only happens when initially loading the value of a setting and will not be triggered afterwards.
Parameters
setting The setting which needs to be updated.
oldSettingId The id of the previous setting.
oldSettingNode The old setting node
Returns
True if the setting has been successfully updated otherwise false
Reimplemented from ISettingCallback.
References CSettingsManager::Setting::callbacks, FindSetting(), m_settings, and m_settingsCritical.
Referenced by UpdateSetting().
ParseVersion()
uint32_t CSettingsManager::ParseVersion (const TiXmlElement * root) const
Try to get the version of the setting definitions/values represented by the given XML element.
Parameters
root XML element representing setting definitions/values
Returns
Version of the setting definitions/values or 0 if no version has been specified
References root, and SETTING_XML_ROOT_VERSION.
Referenced by Initialize(), Load(), and ADDON::CAddonSettings::ParseSettingVersion().
RefreshVisibilityAndEnableStatus()
void CSettingsManager::RefreshVisibilityAndEnableStatus (const std::shared_ptr< const CSetting > & setting) private
Refresh the visibility and enable status of a given setting.
A setting might have its visibility/enable status bound to complex conditions and, at the same time, depend on other settings. When those settings change, the visibility/enable status need to be refreshed (i.e. the complex condition must be re-evaluated)
Parameters
setting Setting object
References Enable, OnSettingPropertyChanged(), and Visible.
Referenced by UpdateSettingByDependency().
RegisterCallback()
void CSettingsManager::RegisterCallback (ISettingCallback * callback, const std::set< std::string > & settingList)
Registers the given ISettingCallback implementation to be triggered for the given list of settings.
Parameters
settingsHandler ISettingsHandler implementation
settingList List of settings to trigger the given ISettingCallback implementation
References FindSetting(), InsertSetting(), m_initialized, m_settings, and m_settingsCritical.
Referenced by CGUIDialogSettingsManagerBase::CreateSettings(), CAdvancedSettings::Initialize(), CSettings::InitializeISettingCallbacks(), CSettingsBase::RegisterCallback(), and CApplicationSettingsHandling::RegisterSettings().
RegisterSettingControl()
void CSettingsManager::RegisterSettingControl (const std::string & controlType, ISettingControlCreator * settingControlCreator)
Registers a custom setting control type and its ISettingControlCreator implementation.
When a setting control definition for a registered custom setting control type is found its ISettingControlCreator implementation is called to create and deserialize the setting control definition.
Parameters
controlType String representation of the custom setting control type
settingControlCreator ISettingControlCreator implementation
References m_critical, and m_settingControlCreators.
Referenced by ADDON::CAddonSettings::InitializeControls(), and CSettings::InitializeControls().
RegisterSettingOptionsFiller() [1/3]
void CSettingsManager::RegisterSettingOptionsFiller (const std::string & identifier, IntegerSettingOptionsFiller optionsFiller)
Registers the given integer setting options filler under the given identifier.
Parameters
identifier Setting options filler identifier
optionsFiller Integer setting options filler implementation
References Integer, and RegisterSettingOptionsFiller().
Referenced by CSettings::InitializeOptionFillers(), RegisterSettingOptionsFiller(), and RegisterSettingOptionsFiller().
RegisterSettingOptionsFiller() [2/3]
void CSettingsManager::RegisterSettingOptionsFiller (const std::string & identifier, StringSettingOptionsFiller optionsFiller)
Registers the given string setting options filler under the given identifier.
Parameters
identifier Setting options filler identifier
optionsFiller String setting options filler implementation
References RegisterSettingOptionsFiller(), and String.
RegisterSettingOptionsFiller() [3/3]
void CSettingsManager::RegisterSettingOptionsFiller (const std::string & identifier, void * filler, SettingOptionsFillerType type) private
References m_critical, and m_optionsFillers.
RegisterSettingsHandler()
void CSettingsManager::RegisterSettingsHandler (ISettingsHandler * settingsHandler, bool bFront = false)
Registers the given ISettingsHandler implementation.
Parameters
settingsHandler ISettingsHandler implementation
bFront If True, insert the handler in front of other registered handlers, insert at the end otherwise.
References m_critical, and m_settingsHandlers.
Referenced by CAdvancedSettings::Initialize(), CSettings::InitializeISettingsHandlers(), and CApplicationSettingsHandling::RegisterSettings().
RegisterSettingType()
void CSettingsManager::RegisterSettingType (const std::string & settingType, ISettingCreator * settingCreator)
Registers a custom setting type and its ISettingCreator implementation.
When a setting definition for a registered custom setting type is found its ISettingCreator implementation is called to create and deserialize the setting definition.
Parameters
settingType String representation of the custom setting type
settingCreator ISettingCreator implementation
References m_critical, and m_settingCreators.
Referenced by ADDON::CAddonSettings::InitializeSettingTypes(), and CSettings::InitializeSettingTypes().
RemoveDynamicCondition()
void CSettingsManager::RemoveDynamicCondition (const std::string & identifier)
Removes the given dynamic condition.
Parameters
identifier Identifier of the dynamic condition
References m_conditions, m_critical, and CSettingConditionsManager::RemoveDynamicCondition().
Referenced by CApplicationSettingsHandling::UnregisterSettings().
ResolveReferenceSettings()
void CSettingsManager::ResolveReferenceSettings (const std::shared_ptr< CSettingSection > & section) private
References FindSetting(), m_logger, and m_settings.
Referenced by AddSection(), and SetInitialized().
ResolveSettingDependencies() [1/2]
void CSettingsManager::ResolveSettingDependencies (const Setting & setting) private
References FindSetting(), m_settings, and CSettingsManager::Setting::setting.
ResolveSettingDependencies() [2/2]
void CSettingsManager::ResolveSettingDependencies (const std::shared_ptr< CSetting > & setting) private
References FindSetting(), and ResolveSettingDependencies().
Referenced by AddSection(), AddSetting(), ResolveSettingDependencies(), and SetInitialized().
Save()
bool CSettingsManager::Save (const ISettingsValueSerializer * serializer, std::string & serializedValues) const
Saves the setting values using the given serializer.
Parameters
serializer Settings value serializer to use
Returns
True if the setting values were successfully serialized, false otherwise
References m_critical, m_initialized, m_settingsCritical, OnSettingsSaved(), OnSettingsSaving(), and ISettingsValueSerializer::SerializeValues().
Referenced by CSettingsBase::SaveValuesToXml().
Serialize()
bool CSettingsManager::Serialize (TiXmlNode * parent) const private
References Action, m_logger, m_settings, m_settingsCritical, SETTING_XML_ATTR_ID, SETTING_XML_ELM_DEFAULT, SETTING_XML_ELM_SETTING, and value.
SetBool()
bool CSettingsManager::SetBool (const std::string & id, bool value)
Sets the boolean value of the setting with the given identifier.
Parameters
id Setting identifier
value Boolean value to set
Returns
True if setting the value was successful, false otherwise
References Boolean, GetSetting(), m_settingsCritical, and value.
Referenced by CGUIDialogAudioSettings::FrameMove(), CGUIDialogContentSettings::OnSettingChanged(), CGUIDialogVideoSettings::OnSettingChanged(), CSettingsBase::SetBool(), and ToggleBool().
SetDefault()
bool CSettingsManager::SetDefault (const std::string & id)
Sets the value of the setting to its default.
Parameters
id Setting identifier
Returns
True if setting the value to its default was successful, false otherwise
References GetSetting(), and m_settingsCritical.
Referenced by CSettingsBase::SetDefault().
SetDefaults()
void CSettingsManager::SetDefaults ()
Sets the value of all settings to their default.
References m_settings, and m_settingsCritical.
Referenced by CSettingsBase::SetDefaults().
SetInitialized()
void CSettingsManager::SetInitialized ()
Tells the settings system that the initialization is complete.
Setting values can only be loaded after a complete and successful initialization of the settings system.
References CleanupIncompleteSettings(), m_initialized, m_sections, m_settings, m_settingsCritical, ResolveReferenceSettings(), and ResolveSettingDependencies().
Referenced by CSettingsBase::Initialize(), CSettings::Initialize(), ADDON::CAddonSettings::Initialize(), and CGUIDialogSettingsManualBase::SetupView().
SetInt()
bool CSettingsManager::SetInt (const std::string & id, int value)
Sets the integer value of the setting with the given identifier.
Parameters
id Setting identifier
value Integer value to set
Returns
True if setting the value was successful, false otherwise
References GetSetting(), Integer, m_settingsCritical, and value.
Referenced by CGUIDialogVideoSettings::OnSettingChanged(), and CSettingsBase::SetInt().
SetList()
bool CSettingsManager::SetList (const std::string & id, const std::vector< std::shared_ptr< CSetting > > & value)
Sets the values of the list setting with the given identifier.
Parameters
id Setting identifier
value Values to set
Returns
True if setting the values was successful, false otherwise
References GetSetting(), List, m_settingsCritical, and value.
SetLoaded()
void CSettingsManager::SetLoaded () inline
Tells the settings system that all setting values have been loaded.
This manual trigger is necessary to enable the ISettingCallback methods being executed.
References m_loaded.
Referenced by CSettingsBase::SetLoaded(), and CGUIDialogSettingsManualBase::SetupView().
SetNumber()
bool CSettingsManager::SetNumber (const std::string & id, double value)
Sets the real number value of the setting with the given identifier.
Parameters
id Setting identifier
value Real number value to set
Returns
True if setting the value was successful, false otherwise
References GetSetting(), m_settingsCritical, Number, and value.
Referenced by CGUIDialogAudioSettings::FrameMove(), CGUIDialogSubtitleSettings::FrameMove(), CGUIDialogVideoSettings::OnSettingChanged(), and CSettingsBase::SetNumber().
SetString()
bool CSettingsManager::SetString (const std::string & id, const std::string & value)
Sets the string value of the setting with the given identifier.
Parameters
id Setting identifier
value String value to set
Returns
True if setting the value was successful, false otherwise
References GetSetting(), m_settingsCritical, String, and value.
Referenced by CSettingsBase::SetString().
ToggleBool()
bool CSettingsManager::ToggleBool (const std::string & id)
Toggles the boolean value of the setting with the given identifier.
Parameters
id Setting identifier
Returns
True if toggling the boolean value was successful, false otherwise
References Boolean, GetSetting(), GetValue(), m_settingsCritical, and SetBool().
Referenced by CSettingsBase::ToggleBool().
Unload()
void CSettingsManager::Unload ()
Unloads the previously loaded setting values.
The values of all the settings are reset to their default values.
References m_loaded, m_settings, m_settingsCritical, and OnSettingsUnloaded().
Referenced by Clear(), and CSettingsBase::Unload().
UnregisterCallback()
void CSettingsManager::UnregisterCallback (ISettingCallback * callback)
Unregisters the given ISettingCallback implementation.
Parameters
callback ISettingCallback implementation
References m_settings, and m_settingsCritical.
Referenced by CGUIDialogSettingsManagerBase::FreeSettingsControls(), CAdvancedSettings::Uninitialize(), CSettings::UninitializeISettingCallbacks(), CSettingsBase::UnregisterCallback(), and CApplicationSettingsHandling::UnregisterSettings().
UnregisterSettingOptionsFiller()
void CSettingsManager::UnregisterSettingOptionsFiller (const std::string & identifier)
Unregisters the setting options filler registered under the given identifier.
Parameters
identifier Setting options filler identifier
References m_critical, and m_optionsFillers.
Referenced by CAdvancedSettings::Uninitialize(), and CSettings::UninitializeOptionFillers().
UnregisterSettingsHandler()
void CSettingsManager::UnregisterSettingsHandler (ISettingsHandler * settingsHandler)
Unregisters the given ISettingsHandler implementation.
Parameters
settingsHandler ISettingsHandler implementation
References m_critical, and m_settingsHandlers.
Referenced by CAdvancedSettings::Uninitialize(), CSettings::UninitializeISettingsHandlers(), and CApplicationSettingsHandling::UnregisterSettings().
UpdateSetting()
bool CSettingsManager::UpdateSetting (const TiXmlNode * node, const std::shared_ptr< CSetting > & setting, const CSettingUpdate & update) private
References CSettingUpdate::GetType(), CSettingUpdate::GetValue(), m_logger, node, OnSettingUpdate(), ParseSettingIdentifier(), Rename, and Unknown.
Referenced by LoadSetting().
UpdateSettingByDependency() [1/2]
void CSettingsManager::UpdateSettingByDependency (const std::string & settingId, const CSettingDependency & dependency) private
References CSettingDependency::GetType(), and UpdateSettingByDependency().
Referenced by OnSettingChanged(), OnSettingPropertyChanged(), and UpdateSettingByDependency().
UpdateSettingByDependency() [2/2]
void CSettingsManager::UpdateSettingByDependency (const std::string & settingId, SettingDependencyType dependencyType) private
References Dynamic, Enable, FindSetting(), Integer, m_settings, OnSettingPropertyChanged(), RefreshVisibilityAndEnableStatus(), String, Unknown, Update, and Visible.
Member Data Documentation
m_conditions
CSettingConditionsManager CSettingsManager::m_conditions private
Referenced by AddCondition(), AddDynamicCondition(), GetConditions(), and RemoveDynamicCondition().
m_critical
CSharedSection CSettingsManager::m_critical mutable private
Referenced by AddCondition(), AddDynamicCondition(), AddSection(), AddSetting(), Clear(), CreateControl(), CreateSetting(), GetSection(), GetSections(), GetSettingOptionsFiller(), Initialize(), Load(), OnSettingsCleared(), OnSettingsLoaded(), OnSettingsLoading(), OnSettingsSaved(), OnSettingsSaving(), OnSettingsUnloaded(), RegisterSettingControl(), RegisterSettingOptionsFiller(), RegisterSettingsHandler(), RegisterSettingType(), RemoveDynamicCondition(), Save(), UnregisterSettingOptionsFiller(), and UnregisterSettingsHandler().
m_initialized
bool CSettingsManager::m_initialized = false private
Referenced by AddSection(), AddSetting(), Clear(), Initialize(), IsInitialized(), RegisterCallback(), Save(), and SetInitialized().
m_loaded
bool CSettingsManager::m_loaded = false private
Referenced by IsLoaded(), Load(), OnSettingAction(), OnSettingChanged(), OnSettingChanging(), OnSettingPropertyChanged(), SetLoaded(), and Unload().
m_logger
Logger CSettingsManager::m_logger private
Referenced by CleanupIncompleteSettings(), GetSection(), GetSetting(), Initialize(), Load(), LoadSetting(), ResolveReferenceSettings(), Serialize(), and UpdateSetting().
m_optionsFillers
SettingOptionsFillerMap CSettingsManager::m_optionsFillers private
Referenced by GetSettingOptionsFiller(), RegisterSettingOptionsFiller(), and UnregisterSettingOptionsFiller().
m_sections
SettingSectionMap CSettingsManager::m_sections private
Referenced by AddSection(), Clear(), GetSection(), GetSections(), Initialize(), and SetInitialized().
m_settingControlCreators
SettingControlCreatorMap CSettingsManager::m_settingControlCreators private
Referenced by CreateControl(), RegisterSettingControl(), and ~CSettingsManager().
m_settingCreators
SettingCreatorMap CSettingsManager::m_settingCreators private
Referenced by CreateSetting(), RegisterSettingType(), and ~CSettingsManager().
m_settings
SettingMap CSettingsManager::m_settings private
Referenced by AddSetting(), AddSetting(), CleanupIncompleteSettings(), Clear(), Deserialize(), FindSetting(), FindSetting(), GetDependencies(), GetSetting(), HasSettings(), InsertSetting(), OnSettingAction(), OnSettingChanged(), OnSettingChanging(), OnSettingPropertyChanged(), OnSettingUpdate(), RegisterCallback(), ResolveReferenceSettings(), ResolveSettingDependencies(), Serialize(), SetDefaults(), SetInitialized(), Unload(), UnregisterCallback(), and UpdateSettingByDependency().
m_settingsCritical
CSharedSection CSettingsManager::m_settingsCritical mutable private
Referenced by AddSection(), AddSetting(), Deserialize(), GetBool(), GetDependencies(), GetInt(), GetList(), GetNumber(), GetSetting(), GetString(), Initialize(), Load(), OnSettingAction(), OnSettingChanged(), OnSettingChanging(), OnSettingPropertyChanged(), OnSettingUpdate(), RegisterCallback(), Save(), Serialize(), SetBool(), SetDefault(), SetDefaults(), SetInitialized(), SetInt(), SetList(), SetNumber(), SetString(), ToggleBool(), Unload(), and UnregisterCallback().
m_settingsHandlers
SettingsHandlers CSettingsManager::m_settingsHandlers private
Referenced by OnSettingsCleared(), OnSettingsLoaded(), OnSettingsLoading(), OnSettingsSaved(), OnSettingsSaving(), OnSettingsUnloaded(), RegisterSettingsHandler(), UnregisterSettingsHandler(), and ~CSettingsManager().
MinimumSupportedVersion
const uint32_t CSettingsManager::MinimumSupportedVersion = 0 static
Referenced by GetMinimumSupportedVersion(), Initialize(), and Load().
Version
const uint32_t CSettingsManager::Version = 2 static
Referenced by GetVersion(), Initialize(), and Load().
The documentation for this class was generated from the following files:
SettingsManager.h
SettingsManager.cpp