Kodi Documentation: KODI::UTILS::POSIX::CSharedMemory Class Reference
KODI::UTILS::POSIX::CSharedMemory Class Reference
#include <SharedMemory.h>
Public Member Functions
CSharedMemory (std::size_t size)
std::size_t Size () const
void * Data () const
int Fd () const
Private Member Functions
CSharedMemory (CSharedMemory const &other)=delete
CSharedMemory & operator= (CSharedMemory const &other)=delete
CFileHandle Open ()
CFileHandle OpenMemfd ()
CFileHandle OpenShm ()
Private Attributes
std::size_t m_size
CFileHandle m_fd
CMmap m_mmap
Detailed Description
Get a chunk of shared memory of specified size
The shared memory is automatically allocated, truncated to the correct size and memory-mapped.
Constructor & Destructor Documentation
CSharedMemory() [1/2]
CSharedMemory::CSharedMemory (std::size_t size) explicit
CSharedMemory() [2/2]
KODI::UTILS::POSIX::CSharedMemory::CSharedMemory (CSharedMemory const & other) private delete
Member Function Documentation
Data()
void * KODI::UTILS::POSIX::CSharedMemory::Data () const inline
References KODI::UTILS::POSIX::CMmap::Data(), and m_mmap.
Fd()
int KODI::UTILS::POSIX::CSharedMemory::Fd () const inline
References m_fd.
Open()
CFileHandle CSharedMemory::Open () private
References CLog::Log(), LOGDEBUG, m_size, OpenMemfd(), and OpenShm().
OpenMemfd()
CFileHandle CSharedMemory::OpenMemfd () private
Referenced by Open().
OpenShm()
CFileHandle CSharedMemory::OpenShm () private
Referenced by Open().
operator=()
CSharedMemory & KODI::UTILS::POSIX::CSharedMemory::operator= (CSharedMemory const & other) private delete
Size()
std::size_t KODI::UTILS::POSIX::CSharedMemory::Size () const inline
References m_size.
Member Data Documentation
m_fd
CFileHandle KODI::UTILS::POSIX::CSharedMemory::m_fd private
Referenced by Fd().
m_mmap
CMmap KODI::UTILS::POSIX::CSharedMemory::m_mmap private
Referenced by Data().
m_size
std::size_t KODI::UTILS::POSIX::CSharedMemory::m_size private
Referenced by Open(), and Size().
The documentation for this class was generated from the following files:
SharedMemory.h
SharedMemory.cpp