Kodi Documentation: KODI::PLAYLIST::CSmartPlaylistRuleCombination Class Reference
KODI::PLAYLIST::CSmartPlaylistRuleCombination Class Reference
#include <SmartPlayList.h>
Public Member Functions
CSmartPlaylistRuleCombination ()=default
~CSmartPlaylistRuleCombination () override=default
std::string GetWhereClause (const CDatabase &db, const std::string &strType, std::set< std::string > &referencedPlaylists) const
void GetVirtualFolders (const std::string &strType, std::vector< std::string > &virtualFolders) const
void AddRule (const CSmartPlaylistRule &rule)
Public Member Functions inherited from CDatabaseQueryRuleCombination
virtual ~CDatabaseQueryRuleCombination ()=default
void clear ()
virtual bool Load (const TiXmlNode *node, const std::string &encoding="UTF-8")
virtual bool Load (const CVariant &obj, const IDatabaseQueryRuleFactory *factory)
virtual bool Save (TiXmlNode *parent) const
virtual bool Save (CVariant &obj) const
std::string GetWhereClause (const CDatabase &db, const std::string &strType) const
std::string TranslateCombinationType () const
Combination GetType () const
void SetType (Combination combination)
bool empty () const
Additional Inherited Members
Public Types inherited from CDatabaseQueryRuleCombination
enum Combination { CombinationOr = 0 , CombinationAnd }
Protected Attributes inherited from CDatabaseQueryRuleCombination
Combination m_type = CombinationAnd
CDatabaseQueryRuleCombinations m_combinations
CDatabaseQueryRules m_rules
Constructor & Destructor Documentation
CSmartPlaylistRuleCombination()
KODI::PLAYLIST::CSmartPlaylistRuleCombination::CSmartPlaylistRuleCombination () default
~CSmartPlaylistRuleCombination()
KODI::PLAYLIST::CSmartPlaylistRuleCombination::~CSmartPlaylistRuleCombination () override default
Member Function Documentation
AddRule()
void KODI::PLAYLIST::CSmartPlaylistRuleCombination::AddRule (const CSmartPlaylistRule & rule)
References CDatabaseQueryRuleCombination::m_rules.
Referenced by CGUIDialogMediaFilter::AddRule(), KODI::PLAYLIST::CSmartPlaylist::LoadFromXML(), and CGUIDialogSmartPlaylistEditor::OnRuleAdd().
GetVirtualFolders()
void KODI::PLAYLIST::CSmartPlaylistRuleCombination::GetVirtualFolders (const std::string & strType, std::vector< std::string > & virtualFolders) const
References KODI::PLAYLIST::CSmartPlaylist::CheckTypeCompatibility(), FieldPlaylist, FieldVirtualFolder, XFILE::CSmartPlaylistDirectory::GetPlaylistByName(), CDatabaseQueryRuleCombination::m_combinations, CDatabaseQueryRuleCombination::m_rules, CDatabaseQueryRule::OPERATOR_EQUALS, and playlist.
Referenced by KODI::PLAYLIST::CSmartPlaylist::GetVirtualFolders().
GetWhereClause()
std::string KODI::PLAYLIST::CSmartPlaylistRuleCombination::GetWhereClause (const CDatabase & db, const std::string & strType, std::set< std::string > & referencedPlaylists) const
References CDatabaseQueryRuleCombination::CombinationAnd, FieldPlaylist, FieldVirtualFolder, XFILE::CSmartPlaylistDirectory::GetPlaylistByName(), CDatabaseQueryRuleCombination::m_combinations, CDatabaseQueryRuleCombination::m_rules, CDatabaseQueryRuleCombination::m_type, CDatabaseQueryRule::OPERATOR_DOES_NOT_EQUAL, and playlist.
Referenced by KODI::PLAYLIST::CSmartPlaylist::GetWhereClause().
The documentation for this class was generated from the following files:
SmartPlayList.h
SmartPlayList.cpp