Kodi Documentation: CAESinkOSS Class Reference
CAESinkOSS Class Reference
#include <AESinkOSS.h>
Public Member Functions
const char * GetName () override
CAESinkOSS ()
~CAESinkOSS () override
bool Initialize (AEAudioFormat &format, std::string &device) override
void Deinitialize () override
virtual void Stop ()
void GetDelay (AEDelayStatus &status) override
Return a timestamped status structure with delay and sink info.
double GetCacheTotal () override
unsigned int AddPackets (uint8_t **data, unsigned int frames, unsigned int offset) override
Adds packets to be sent out, this routine MUST block or sleep.
void Drain () override
Public Member Functions inherited from IAESink
IAESink ()=default
virtual ~IAESink ()=default
virtual double GetLatency ()
virtual void AddPause (unsigned int millis)
instruct the sink to add a pause
virtual bool HasVolume ()
virtual void SetVolume (float volume)
Static Public Member Functions
static void Register ()
static std::unique_ptr< IAESink > Create (std::string &device, AEAudioFormat &desiredFormat)
static void EnumerateDevicesEx (AEDeviceInfoList &list, bool force=false)
Private Member Functions
CAEChannelInfo GetChannelLayout (const AEAudioFormat &format)
std::string GetDeviceUse (const AEAudioFormat &format, const std::string &device)
Private Attributes
int m_fd
std::string m_device
AEAudioFormat m_initFormat
AEAudioFormat m_format
Constructor & Destructor Documentation
CAESinkOSS()
CAESinkOSS::CAESinkOSS ()
References m_fd.
~CAESinkOSS()
CAESinkOSS::~CAESinkOSS () override
References Deinitialize().
Member Function Documentation
AddPackets()
unsigned int CAESinkOSS::AddPackets (uint8_t ** data, unsigned int frames, unsigned int offset) override virtual
Adds packets to be sent out, this routine MUST block or sleep.
Parameters
data array of pointers to planes holding audio data
frames number of audio frames in data
offset offset in frames where audio data starts
Returns
number of frames consumed by the sink
Implements IAESink.
References data(), CLog::Log(), LOGERROR, m_fd, m_format, and AEAudioFormat::m_frameSize.
Create()
std::unique_ptr< IAESink > CAESinkOSS::Create (std::string & device, AEAudioFormat & desiredFormat) static
Referenced by Register().
Deinitialize()
void CAESinkOSS::Deinitialize () override virtual
Implements IAESink.
References m_fd, and Stop().
Referenced by ~CAESinkOSS().
Drain()
void CAESinkOSS::Drain () override virtual
Reimplemented from IAESink.
References CLog::Log(), LOGERROR, and m_fd.
EnumerateDevicesEx()
void CAESinkOSS::EnumerateDevicesEx (AEDeviceInfoList & list, bool force = false) static
References AE_CH_NULL, AE_DEVTYPE_HDMI, AE_DEVTYPE_IEC958, AE_DEVTYPE_PCM, AE_FMT_RAW, AE_FMT_S16LE, AE_FMT_S16NE, AE_FMT_S32LE, AE_FMT_S32NE, CLog::Log(), LOGINFO, CAEDeviceInfo::m_deviceName, OSSChannelMap, CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, and CAEStreamInfo::STREAM_TYPE_TRUEHD.
Referenced by Register().
GetCacheTotal()
double CAESinkOSS::GetCacheTotal () inline override virtual
Implements IAESink.
GetChannelLayout()
CAEChannelInfo CAESinkOSS::GetChannelLayout (const AEAudioFormat & format) inline private
References AE_FMT_RAW, OSSChannelMap, CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, CAEStreamInfo::STREAM_TYPE_DTSHD_MA, CAEStreamInfo::STREAM_TYPE_EAC3, and CAEStreamInfo::STREAM_TYPE_TRUEHD.
Referenced by Initialize().
GetDelay()
void CAESinkOSS::GetDelay (AEDelayStatus & status) override virtual
Return a timestamped status structure with delay and sink info.
Parameters
status structure filled with sink status
Implements IAESink.
References m_fd, m_format, AEAudioFormat::m_frameSize, AEAudioFormat::m_sampleRate, and AEDelayStatus::SetDelay().
GetDeviceUse()
std::string CAESinkOSS::GetDeviceUse (const AEAudioFormat & format, const std::string & device) private
Referenced by Initialize().
GetName()
const char * CAESinkOSS::GetName () inline override virtual
Implements IAESink.
Initialize()
bool CAESinkOSS::Initialize (AEAudioFormat & format, std::string & device) override virtual
Implements IAESink.
References AE_CH_BL, AE_CH_BR, AE_CH_FC, AE_CH_FL, AE_CH_FR, AE_CH_LFE, AE_CH_SL, AE_CH_SR, AE_FMT_FLOAT, AE_FMT_RAW, AE_FMT_S16BE, AE_FMT_S16LE, AE_FMT_S16NE, AE_FMT_S32BE, AE_FMT_S32LE, AE_FMT_S32NE, AE_FMT_U8, CAEUtil::DataFormatToBits(), CAEUtil::DataFormatToStr(), GetChannelLayout(), GetDeviceUse(), CLog::Log(), LOGERROR, LOGINFO, LOGWARNING, AEAudioFormat::m_channelLayout, m_device, m_fd, m_format, m_initFormat, and OSS_FRAMES.
Register()
void CAESinkOSS::Register () static
References Create(), AE::AESinkRegEntry::createFunc, EnumerateDevicesEx(), AE::AESinkRegEntry::enumerateFunc, AE::CAESinkFactory::RegisterSink(), and AE::AESinkRegEntry::sinkName.
Stop()
void CAESinkOSS::Stop () virtual
References m_fd.
Referenced by Deinitialize().
Member Data Documentation
m_device
std::string CAESinkOSS::m_device private
Referenced by Initialize().
m_fd
int CAESinkOSS::m_fd private
Referenced by AddPackets(), CAESinkOSS(), Deinitialize(), Drain(), GetDelay(), Initialize(), and Stop().
m_format
AEAudioFormat CAESinkOSS::m_format private
Referenced by AddPackets(), GetDelay(), and Initialize().
m_initFormat
AEAudioFormat CAESinkOSS::m_initFormat private
Referenced by Initialize().
The documentation for this class was generated from the following files:
AESinkOSS.h
AESinkOSS.cpp