Kodi Documentation: KODI::RETRO::CRPBaseRenderer Class Reference
KODI::RETRO::CRPBaseRenderer Class Reference abstract
#include <RPBaseRenderer.h>
Public Member Functions
CRPBaseRenderer (const CRenderSettings &renderSettings, CRenderContext &context, std::shared_ptr< IRenderBufferPool > bufferPool)
virtual ~CRPBaseRenderer ()
IRenderBufferPool * GetBufferPool ()
Get the buffer pool used by this renderer.
bool Configure (AVPixelFormat format)
void FrameMove ()
void PreRender (bool clear)
Performs whatever necessary before rendering the frame.
void SetBuffer (IRenderBuffer *buffer)
void RenderFrame (bool clear, uint8_t alpha)
virtual bool Supports (RENDERFEATURE feature) const =0
bool IsCompatible (const CRenderVideoSettings &settings) const
virtual SCALINGMETHOD GetDefaultScalingMethod () const =0
virtual void Flush ()
const CRenderSettings & GetRenderSettings () const
void SetScalingMethod (SCALINGMETHOD method)
void SetStretchMode (STRETCHMODE stretchMode)
void SetRenderRotation (unsigned int rotationDegCCW)
void SetPixels (const std::string &pixelPath)
bool IsVisible () const
IRenderBuffer * GetRenderBuffer () const
Protected Member Functions
virtual bool ConfigureInternal ()
virtual void RenderInternal (bool clear, uint8_t alpha)=0
virtual void FlushInternal ()
Protected Attributes
CRenderContext & m_context
std::shared_ptr< IRenderBufferPool > m_bufferPool
bool m_bConfigured = false
AVPixelFormat m_format = AV_PIX_FMT_NONE
CRenderSettings m_renderSettings
IRenderBuffer * m_renderBuffer = nullptr
CRect m_sourceRect
std::array< CPoint, 4 > m_rotatedDestCoords {}
Private Member Functions
virtual void ManageRenderArea (const IRenderBuffer &renderBuffer)
Calculate driven dimensions.
void PostRender ()
Performs whatever necessary after a frame has been rendered.
void MarkDirty ()
void GetScreenDimensions (float &screenWidth, float &screenHeight, float &screenPixelRatio)
Private Attributes
uint64_t m_renderFrameCount = 0
uint64_t m_lastRender = 0
Constructor & Destructor Documentation
CRPBaseRenderer()
CRPBaseRenderer::CRPBaseRenderer (const CRenderSettings & renderSettings, CRenderContext & context, std::shared_ptr< IRenderBufferPool > bufferPool)
References m_bufferPool.
~CRPBaseRenderer()
CRPBaseRenderer::~CRPBaseRenderer () virtual
References m_bufferPool, and SetBuffer().
Member Function Documentation
Configure()
bool CRPBaseRenderer::Configure (AVPixelFormat format)
References ConfigureInternal(), CLog::Log(), LOGDEBUG, LOGERROR, m_bConfigured, m_bufferPool, and m_format.
ConfigureInternal()
virtual bool KODI::RETRO::CRPBaseRenderer::ConfigureInternal () inline protected virtual
Reimplemented in KODI::RETRO::CRPWinRenderer.
Referenced by Configure().
Flush()
void CRPBaseRenderer::Flush () virtual
References FlushInternal(), and SetBuffer().
FlushInternal()
virtual void KODI::RETRO::CRPBaseRenderer::FlushInternal () inline protected virtual
Reimplemented in KODI::RETRO::CRPRendererOpenGL, and KODI::RETRO::CRPRendererOpenGLES.
Referenced by Flush().
FrameMove()
void CRPBaseRenderer::FrameMove ()
References m_renderFrameCount.
GetBufferPool()
IRenderBufferPool * KODI::RETRO::CRPBaseRenderer::GetBufferPool () inline
Get the buffer pool used by this renderer.
References m_bufferPool.
GetDefaultScalingMethod()
virtual SCALINGMETHOD KODI::RETRO::CRPBaseRenderer::GetDefaultScalingMethod () const pure virtual
Implemented in KODI::RETRO::CRPRendererGuiTexture, KODI::RETRO::CRPRendererOpenGL, KODI::RETRO::CRPRendererOpenGLES, and KODI::RETRO::CRPWinRenderer.
GetRenderBuffer()
IRenderBuffer * CRPBaseRenderer::GetRenderBuffer () const
References KODI::RETRO::IRenderBuffer::Acquire(), and m_renderBuffer.
GetRenderSettings()
const CRenderSettings & KODI::RETRO::CRPBaseRenderer::GetRenderSettings () const inline
References m_renderSettings.
Referenced by KODI::RETRO::CRPRendererOpenGL::Render(), KODI::RETRO::CRPRendererOpenGLES::Render(), and KODI::RETRO::CRPRendererDMA::Render().
GetScreenDimensions()
void CRPBaseRenderer::GetScreenDimensions (float & screenWidth, float & screenHeight, float & screenPixelRatio) private
References RESOLUTION_INFO::fPixelRatio, KODI::RETRO::CRenderContext::GetResInfo(), and m_context.
Referenced by ManageRenderArea().
IsCompatible()
bool CRPBaseRenderer::IsCompatible (const CRenderVideoSettings & settings) const
References m_bufferPool.
IsVisible()
bool CRPBaseRenderer::IsVisible () const
References m_lastRender, m_renderFrameCount, and VISIBLE_DURATION_FRAME_COUNT.
ManageRenderArea()
void CRPBaseRenderer::ManageRenderArea (const IRenderBuffer & renderBuffer) private virtual
Calculate driven dimensions.
@Todo screenPixelRatio unused - Possibly due to display integer scaling according to Garbear
References KODI::RETRO::CRenderUtils::CalcNormalRenderRect(), KODI::RETRO::CRenderUtils::CalculateStretchMode(), KODI::RETRO::CRenderUtils::ClipRect(), KODI::RETRO::CRenderUtils::CropSource(), KODI::RETRO::CRenderContext::DisplayHardwareScalingEnabled(), KODI::RETRO::IRenderBuffer::GetHeight(), KODI::RETRO::CRenderVideoSettings::GetRenderRotation(), KODI::RETRO::CRenderVideoSettings::GetRenderStretchMode(), KODI::RETRO::IRenderBuffer::GetRotation(), KODI::RETRO::CRenderVideoSettings::GetScalingMethod(), GetScreenDimensions(), KODI::RETRO::CRenderContext::GetViewWindow(), KODI::RETRO::IRenderBuffer::GetWidth(), CRectGen< T >::Height(), KODI::RETRO::CRenderContext::IsCalibrating(), KODI::RETRO::CRenderContext::IsFullScreenVideo(), m_context, m_renderSettings, m_rotatedDestCoords, m_sourceRect, KODI::RETRO::NEAREST, KODI::RETRO::Original, KODI::RETRO::CRenderUtils::ReorderDrawPoints(), KODI::RETRO::CRenderSettings::VideoSettings(), CRectGen< T >::Width(), CRectGen< T >::x1, CRectGen< T >::x2, CRectGen< T >::y1, CRectGen< T >::y2, and KODI::RETRO::Zoom.
Referenced by RenderFrame().
MarkDirty()
void CRPBaseRenderer::MarkDirty () private
PostRender()
void CRPBaseRenderer::PostRender () private
Performs whatever necessary after a frame has been rendered.
References KODI::RETRO::CRenderContext::ApplyStateBlock(), and m_context.
Referenced by RenderFrame().
PreRender()
void CRPBaseRenderer::PreRender (bool clear)
Performs whatever necessary before rendering the frame.
References KODI::UTILS::COLOR::BLACK, KODI::RETRO::CRenderContext::Clear(), KODI::UTILS::COLOR::LIMITED_BLACK, m_bConfigured, m_context, and KODI::RETRO::CRenderContext::UseLimitedColor().
RenderFrame()
void CRPBaseRenderer::RenderFrame (bool clear, uint8_t alpha)
References m_bConfigured, m_lastRender, m_renderBuffer, m_renderFrameCount, ManageRenderArea(), PostRender(), RenderInternal(), and KODI::RETRO::IRenderBuffer::SetRendered().
RenderInternal()
virtual void KODI::RETRO::CRPBaseRenderer::RenderInternal (bool clear, uint8_t alpha) protected pure virtual
Implemented in KODI::RETRO::CRPRendererGuiTexture, KODI::RETRO::CRPRendererOpenGL, KODI::RETRO::CRPRendererOpenGLES, and KODI::RETRO::CRPWinRenderer.
Referenced by RenderFrame().
SetBuffer()
void CRPBaseRenderer::SetBuffer (IRenderBuffer * buffer)
References KODI::RETRO::IRenderBuffer::Acquire(), m_renderBuffer, and KODI::RETRO::IRenderBuffer::Release().
Referenced by Flush(), and ~CRPBaseRenderer().
SetPixels()
void CRPBaseRenderer::SetPixels (const std::string & pixelPath)
References m_renderSettings, KODI::RETRO::CRenderVideoSettings::SetPixels(), and KODI::RETRO::CRenderSettings::VideoSettings().
SetRenderRotation()
void CRPBaseRenderer::SetRenderRotation (unsigned int rotationDegCCW)
References m_renderSettings, KODI::RETRO::CRenderVideoSettings::SetRenderRotation(), and KODI::RETRO::CRenderSettings::VideoSettings().
SetScalingMethod()
void CRPBaseRenderer::SetScalingMethod (SCALINGMETHOD method)
References m_renderSettings, KODI::RETRO::CRenderVideoSettings::SetScalingMethod(), and KODI::RETRO::CRenderSettings::VideoSettings().
SetStretchMode()
void CRPBaseRenderer::SetStretchMode (STRETCHMODE stretchMode)
References m_renderSettings, KODI::RETRO::CRenderVideoSettings::SetRenderStretchMode(), and KODI::RETRO::CRenderSettings::VideoSettings().
Supports()
virtual bool KODI::RETRO::CRPBaseRenderer::Supports (RENDERFEATURE feature) const pure virtual
Implemented in KODI::RETRO::CRPRendererGuiTexture, KODI::RETRO::CRPRendererOpenGL, KODI::RETRO::CRPRendererOpenGLES, and KODI::RETRO::CRPWinRenderer.
Member Data Documentation
m_bConfigured
bool KODI::RETRO::CRPBaseRenderer::m_bConfigured = false protected
Referenced by Configure(), KODI::RETRO::CRPRendererOpenGL::FlushInternal(), KODI::RETRO::CRPRendererOpenGLES::FlushInternal(), PreRender(), and RenderFrame().
m_bufferPool
std::shared_ptr<IRenderBufferPool> KODI::RETRO::CRPBaseRenderer::m_bufferPool protected
Referenced by Configure(), KODI::RETRO::CRPWinRenderer::ConfigureInternal(), CRPBaseRenderer(), GetBufferPool(), IsCompatible(), KODI::RETRO::CRPWinRenderer::Render(), and ~CRPBaseRenderer().
m_context
CRenderContext& KODI::RETRO::CRPBaseRenderer::m_context protected
Referenced by KODI::RETRO::CRPWinRenderer::ConfigureInternal(), KODI::RETRO::CRPRendererOpenGL::CRPRendererOpenGL(), KODI::RETRO::CRPRendererOpenGL::DrawBlackBars(), KODI::RETRO::CRPRendererOpenGLES::DrawBlackBars(), GetScreenDimensions(), ManageRenderArea(), PostRender(), PreRender(), KODI::RETRO::CRPWinRenderer::Render(), KODI::RETRO::CRPRendererOpenGL::Render(), KODI::RETRO::CRPRendererOpenGLES::Render(), KODI::RETRO::CRPRendererDMA::Render(), KODI::RETRO::CRPRendererGuiTexture::RenderInternal(), and KODI::RETRO::CRPWinRenderer::RenderInternal().
m_format
AVPixelFormat KODI::RETRO::CRPBaseRenderer::m_format = AV_PIX_FMT_NONE protected
Referenced by Configure().
m_lastRender
uint64_t KODI::RETRO::CRPBaseRenderer::m_lastRender = 0 private
Referenced by IsVisible(), and RenderFrame().
m_renderBuffer
IRenderBuffer* KODI::RETRO::CRPBaseRenderer::m_renderBuffer = nullptr protected
Referenced by GetRenderBuffer(), KODI::RETRO::CRPWinRenderer::Render(), KODI::RETRO::CRPRendererOpenGL::Render(), KODI::RETRO::CRPRendererOpenGLES::Render(), KODI::RETRO::CRPRendererDMA::Render(), RenderFrame(), KODI::RETRO::CRPRendererGuiTexture::RenderInternal(), and SetBuffer().
m_renderFrameCount
uint64_t KODI::RETRO::CRPBaseRenderer::m_renderFrameCount = 0 private
Referenced by FrameMove(), IsVisible(), and RenderFrame().
m_renderSettings
CRenderSettings KODI::RETRO::CRPBaseRenderer::m_renderSettings protected
Referenced by GetRenderSettings(), ManageRenderArea(), KODI::RETRO::CRPWinRenderer::Render(), SetPixels(), SetRenderRotation(), SetScalingMethod(), and SetStretchMode().
m_rotatedDestCoords
std::array<CPoint, 4> KODI::RETRO::CRPBaseRenderer::m_rotatedDestCoords {} protected
Referenced by KODI::RETRO::CRPRendererOpenGL::DrawBlackBars(), KODI::RETRO::CRPRendererOpenGLES::DrawBlackBars(), ManageRenderArea(), KODI::RETRO::CRPWinRenderer::Render(), KODI::RETRO::CRPRendererOpenGL::Render(), KODI::RETRO::CRPRendererOpenGLES::Render(), KODI::RETRO::CRPRendererDMA::Render(), and KODI::RETRO::CRPRendererGuiTexture::RenderInternal().
m_sourceRect
CRect KODI::RETRO::CRPBaseRenderer::m_sourceRect protected
Referenced by ManageRenderArea(), KODI::RETRO::CRPWinRenderer::Render(), KODI::RETRO::CRPRendererOpenGL::Render(), KODI::RETRO::CRPRendererOpenGLES::Render(), KODI::RETRO::CRPRendererDMA::Render(), and KODI::RETRO::CRPRendererGuiTexture::RenderInternal().
The documentation for this class was generated from the following files:
RPBaseRenderer.h
RPBaseRenderer.cpp