Kodi Documentation: KODI::KEYBOARD::IKeyboardInputHandler Class Reference
KODI::KEYBOARD::IKeyboardInputHandler Class Reference abstract
Input » Keyboard
Interface for handling input events for keyboards.
#include <IKeyboardInputHandler.h>
Public Member Functions
virtual ~IKeyboardInputHandler ()=default
virtual std::string ControllerID () const =0
The add-on ID of the keyboard's controller profile.
virtual bool HasKey (const KeyName &key) const =0
Return true if the input handler accepts the given key.
virtual bool OnKeyPress (const KeyName &key, Modifier mod, uint32_t unicode)=0
A key has been pressed.
virtual void OnKeyRelease (const KeyName &key, Modifier mod, uint32_t unicode)=0
A key has been released.
Detailed Description
Interface for handling input events for keyboards.
Input events are an abstraction over driver events. Keys are identified by the name defined in the keyboard's controller profile.
Constructor & Destructor Documentation
~IKeyboardInputHandler()
virtual KODI::KEYBOARD::IKeyboardInputHandler::~IKeyboardInputHandler () virtual default
Member Function Documentation
ControllerID()
virtual std::string KODI::KEYBOARD::IKeyboardInputHandler::ControllerID () const pure virtual
The add-on ID of the keyboard's controller profile.
Returns
The ID of the controller profile add-on
Implemented in KODI::GAME::CGameClientKeyboard, and KODI::GAME::CAgentKeyboard.
Referenced by KODI::KEYBOARD::CDefaultKeyboardHandling::Load(), and PERIPHERALS::CAddonInputHandling::Load().
HasKey()
virtual bool KODI::KEYBOARD::IKeyboardInputHandler::HasKey (const KeyName & key) const pure virtual
Return true if the input handler accepts the given key.
Parameters
key A key belonging to the controller specified by ControllerID()
Returns
True if the key is used for input, false otherwise
Implemented in KODI::GAME::CGameClientKeyboard, and KODI::GAME::CAgentKeyboard.
OnKeyPress()
virtual bool KODI::KEYBOARD::IKeyboardInputHandler::OnKeyPress (const KeyName & key, Modifier mod, uint32_t unicode) pure virtual
A key has been pressed.
Parameters
key A key belonging to the controller specified by ControllerID()
mod A combination of modifiers
unicode The unicode value associated with the key, or 0 if unknown
Returns
True if the event was handled, false otherwise
Implemented in KODI::GAME::CGameClientKeyboard, and KODI::GAME::CAgentKeyboard.
Referenced by KODI::KEYBOARD::CKeyboardInputHandling::OnKeyPress().
OnKeyRelease()
virtual void KODI::KEYBOARD::IKeyboardInputHandler::OnKeyRelease (const KeyName & key, Modifier mod, uint32_t unicode) pure virtual
A key has been released.
Parameters
key A key belonging to the controller specified by ControllerID()
mod A combination of modifiers
unicode The unicode value associated with the key, or 0 if unknown
Implemented in KODI::GAME::CGameClientKeyboard, and KODI::GAME::CAgentKeyboard.
Referenced by KODI::KEYBOARD::CKeyboardInputHandling::OnKeyRelease().
The documentation for this class was generated from the following file:
IKeyboardInputHandler.h