Kodi Documentation: CDateTime Class Reference
CDateTime Class Reference final
DateTime class, which uses FileTime as it's base.
#include <XBDateTime.h>
Public Types
enum class ReturnFormat : bool { CHOICE_YES = true , CHOICE_NO = false }
Public Member Functions
CDateTime ()
CDateTime (const CDateTime &time)
CDateTime & operator= (const CDateTime &)=default
CDateTime (const KODI::TIME::SystemTime &time)
CDateTime (const KODI::TIME::FileTime &time)
CDateTime (const time_t &time)
CDateTime (const tm &time)
CDateTime (int year, int month, int day, int hour, int minute, int second)
const CDateTime & operator= (const KODI::TIME::SystemTime &right)
const CDateTime & operator= (const KODI::TIME::FileTime &right)
const CDateTime & operator= (const time_t &right)
const CDateTime & operator= (const tm &right)
bool operator> (const CDateTime &right) const
bool operator>= (const CDateTime &right) const
bool operator< (const CDateTime &right) const
bool operator<= (const CDateTime &right) const
bool operator== (const CDateTime &right) const
bool operator!= (const CDateTime &right) const
bool operator> (const KODI::TIME::FileTime &right) const
bool operator>= (const KODI::TIME::FileTime &right) const
bool operator< (const KODI::TIME::FileTime &right) const
bool operator<= (const KODI::TIME::FileTime &right) const
bool operator== (const KODI::TIME::FileTime &right) const
bool operator!= (const KODI::TIME::FileTime &right) const
bool operator> (const KODI::TIME::SystemTime &right) const
bool operator>= (const KODI::TIME::SystemTime &right) const
bool operator< (const KODI::TIME::SystemTime &right) const
bool operator<= (const KODI::TIME::SystemTime &right) const
bool operator== (const KODI::TIME::SystemTime &right) const
bool operator!= (const KODI::TIME::SystemTime &right) const
bool operator> (const time_t &right) const
bool operator>= (const time_t &right) const
bool operator< (const time_t &right) const
bool operator<= (const time_t &right) const
bool operator== (const time_t &right) const
bool operator!= (const time_t &right) const
bool operator> (const tm &right) const
bool operator>= (const tm &right) const
bool operator< (const tm &right) const
bool operator<= (const tm &right) const
bool operator== (const tm &right) const
bool operator!= (const tm &right) const
CDateTime operator+ (const CDateTimeSpan &right) const
CDateTime operator- (const CDateTimeSpan &right) const
const CDateTime & operator+= (const CDateTimeSpan &right)
const CDateTime & operator-= (const CDateTimeSpan &right)
CDateTimeSpan operator- (const CDateTime &right) const
operator KODI::TIME::FileTime () const
void Archive (CArchive &ar) override
void Reset ()
int GetDay () const
int GetMonth () const
int GetYear () const
int GetHour () const
int GetMinute () const
int GetSecond () const
int GetDayOfWeek () const
int GetMinuteOfDay () const
bool SetDateTime (int year, int month, int day, int hour, int minute, int second)
bool SetDate (int year, int month, int day)
bool SetTime (int hour, int minute, int second)
bool SetFromDateString (const std::string &date)
bool SetFromDBDate (const std::string &date)
bool SetFromDBTime (const std::string &time)
bool SetFromW3CDate (const std::string &date)
bool SetFromW3CDateTime (const std::string &date, bool ignoreTimezone=false)
bool SetFromUTCDateTime (const CDateTime &dateTime)
bool SetFromUTCDateTime (const time_t &dateTime)
bool SetFromRFC1123DateTime (const std::string &dateTime)
bool SetFromDBDateTime (const std::string &dateTime)
set from a database datetime format YYYY-MM-DD HH:MM:SS
void GetAsSystemTime (KODI::TIME::SystemTime &time) const
void GetAsTime (time_t &time) const
void GetAsTm (tm &time) const
void GetAsTimeStamp (KODI::TIME::FileTime &time) const
CDateTime GetAsUTCDateTime () const
std::string GetAsSaveString () const
std::string GetAsDBDateTime () const
std::string GetAsDBDate () const
std::string GetAsDBTime () const
std::string GetAsLocalizedDate (bool longDate=false) const
std::string GetAsLocalizedDate (const std::string &strFormat) const
std::string GetAsLocalizedDate (const std::string &strFormat, ReturnFormat returnFormat) const
std::string GetAsLocalizedTime (const std::string &format, bool withSeconds=true) const
std::string GetAsLocalizedDateTime (bool longDate=false, bool withSeconds=true) const
std::string GetAsLocalizedTime (TIME_FORMAT format, bool withSeconds=false) const
std::string GetAsRFC1123DateTime () const
std::string GetAsW3CDate () const
std::string GetAsW3CDateTime (bool asUtc=false) const
void SetValid (bool yesNo)
bool IsValid () const
Static Public Member Functions
static CDateTime GetCurrentDateTime ()
static CDateTime GetUTCDateTime ()
static int MonthStringToMonthNum (const std::string &month)
static CDateTime FromDBDateTime (const std::string &dateTime)
static CDateTime FromDateString (const std::string &date)
static CDateTime FromDBDate (const std::string &date)
static CDateTime FromDBTime (const std::string &time)
static CDateTime FromW3CDate (const std::string &date)
static CDateTime FromW3CDateTime (const std::string &date, bool ignoreTimezone=false)
static CDateTime FromUTCDateTime (const CDateTime &dateTime)
static CDateTime FromUTCDateTime (const time_t &dateTime)
static CDateTime FromRFC1123DateTime (const std::string &dateTime)
static void ResetTimezoneBias (void)
static CDateTimeSpan GetTimezoneBias (void)
Private Types
enum _STATE { invalid =0 , valid }
typedef enum CDateTime::_STATE STATE
Private Member Functions
bool ToFileTime (const KODI::TIME::SystemTime &time, KODI::TIME::FileTime &fileTime) const
bool ToFileTime (const time_t &time, KODI::TIME::FileTime &fileTime) const
bool ToFileTime (const tm &time, KODI::TIME::FileTime &fileTime) const
void ToLargeInt (LARGE_INTEGER &time) const
void FromLargeInt (const LARGE_INTEGER &time)
Private Attributes
KODI::TIME::FileTime m_time
STATE m_state
Additional Inherited Members
Protected Member Functions inherited from IArchivable
virtual ~IArchivable ()=default
Detailed Description
DateTime class, which uses FileTime as it's base.
Member Typedef Documentation
STATE
typedef enum CDateTime::_STATE CDateTime::STATE private
Member Enumeration Documentation
_STATE
enum CDateTime::_STATE private
Enumerator
invalid
valid
ReturnFormat
enum class CDateTime::ReturnFormat : bool strong
Enumerator
CHOICE_YES
CHOICE_NO
Constructor & Destructor Documentation
CDateTime() [1/7]
CDateTime::CDateTime ()
References Reset().
Referenced by GetCurrentDateTime().
CDateTime() [2/7]
CDateTime::CDateTime (const CDateTime & time)
References m_state.
CDateTime() [3/7]
CDateTime::CDateTime (const KODI::TIME::SystemTime & time) explicit
References invalid, m_state, m_time, ToFileTime(), and valid.
CDateTime() [4/7]
CDateTime::CDateTime (const KODI::TIME::FileTime & time) explicit
References SetValid().
CDateTime() [5/7]
CDateTime::CDateTime (const time_t & time) explicit
References invalid, m_state, m_time, ToFileTime(), and valid.
CDateTime() [6/7]
CDateTime::CDateTime (const tm & time) explicit
References invalid, m_state, m_time, ToFileTime(), and valid.
CDateTime() [7/7]
CDateTime::CDateTime (int year, int month, int day, int hour, int minute, int second)
References day, and SetDateTime().
Member Function Documentation
Archive()
void CDateTime::Archive (CArchive & ar) override virtual
Implements IArchivable.
References GetAsSystemTime(), CArchive::IsStoring(), m_state, m_time, Reset(), ToFileTime(), and valid.
FromDateString()
CDateTime CDateTime::FromDateString (const std::string & date) static
References SetFromDateString().
FromDBDate()
CDateTime CDateTime::FromDBDate (const std::string & date) static
References SetFromDBDate().
Referenced by CSettingDate::CheckValidity(), and CSettingDate::GetDate().
FromDBDateTime()
CDateTime CDateTime::FromDBDateTime (const std::string & dateTime) static
References SetFromDBDateTime().
Referenced by PVR::CPVREpgDatabase::CreateEpgSearchFilter(), PVR::CPVRDatabase::Get(), PVR::CPVRDatabase::GetDateTimeFirstChannelsAdded(), ADDON::CAddonDatabase::GetInstallData(), and PVR::CPVRDatabase::GetTimers().
FromDBTime()
CDateTime CDateTime::FromDBTime (const std::string & time) static
References SetFromDBTime().
Referenced by CSettingTime::CheckValidity(), and CSettingTime::GetTime().
FromLargeInt()
void CDateTime::FromLargeInt (const LARGE_INTEGER & time) private
References KODI::TIME::FileTime::highDateTime, KODI::TIME::FileTime::lowDateTime, and m_time.
Referenced by operator+=(), and operator-=().
FromRFC1123DateTime()
CDateTime CDateTime::FromRFC1123DateTime (const std::string & dateTime) static
References SetFromRFC1123DateTime().
FromUTCDateTime() [1/2]
CDateTime CDateTime::FromUTCDateTime (const CDateTime & dateTime) static
References SetFromUTCDateTime().
Referenced by KODI::RETRO::CSavestateDatabase::GetSavestateItem().
FromUTCDateTime() [2/2]
CDateTime CDateTime::FromUTCDateTime (const time_t & dateTime) static
References SetFromUTCDateTime().
FromW3CDate()
CDateTime CDateTime::FromW3CDate (const std::string & date) static
References SetFromW3CDate().
FromW3CDateTime()
CDateTime CDateTime::FromW3CDateTime (const std::string & date, bool ignoreTimezone = false) static
References SetFromW3CDateTime().
GetAsDBDate()
std::string CDateTime::GetAsDBDate () const
References KODI::TIME::SystemTime::day, GetAsSystemTime(), KODI::TIME::SystemTime::month, and KODI::TIME::SystemTime::year.
Referenced by CDatabaseQueryRule::FormatParameter(), CVideoDatabase::GetMatchingTvShow(), CGUIEditControl::OnClick(), CGUIDialogMediaFilter::OnSettingChanged(), PVR::CPVRChannel::Serialize(), PVR::CPVREpgInfoTag::Serialize(), PVR::CPVRTimerInfoTag::Serialize(), CVideoInfoTag::Serialize(), CSettingDate::SetDate(), XMLUtils::SetDate(), XMLUtils::SetDate(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMusicVideo(), TEST_F(), TEST_F(), CVideoInfoTag::ToSortable(), PVR::CGUIDialogPVRGuideSearch::Update(), and CVideoDatabase::UpdateDetailsForMovie().
GetAsDBDateTime()
std::string CDateTime::GetAsDBDateTime () const
References KODI::TIME::SystemTime::day, GetAsSystemTime(), KODI::TIME::SystemTime::hour, KODI::TIME::SystemTime::minute, KODI::TIME::SystemTime::month, KODI::TIME::SystemTime::second, and KODI::TIME::SystemTime::year.
Referenced by CMusicDatabase::AddAudioBook(), CTextureDatabase::AddCachedTexture(), CVideoDatabase::AddFile(), ADDON::CAddonDatabase::AddInstalledAddon(), CVideoDatabase::AddPath(), CMusicDatabase::AddSong(), CVideoInfoTag::Archive(), PVR::CPVREpgDatabase::GetEpgTagByMaxEndTime(), PVR::CPVREpgDatabase::GetEpgTagByMinStartTime(), PVR::CPVREpgDatabase::GetEpgTagsByMinEndMaxStartTime(), PVR::CPVREpgDatabase::GetEpgTagsByMinStartMaxEndTime(), CMusicDatabase::GetMediaDateFromFile(), CMusicDatabase::IncrementPlayCount(), PVR::CPVREpgInfoTag::Path(), PVR::CPVRDatabase::Persist(), PVR::CPVRDatabase::Persist(), PVR::CPVREpgDatabase::Persist(), PVR::CPVRDatabase::Persist(), PVR::CPVREpgDatabase::QueuePersistLastEpgScanTimeQuery(), MUSIC_INFO::CMusicInfoTag::Serialize(), CFileItem::Serialize(), CSong::Serialize(), PVR::CPVREpgInfoTag::Serialize(), PVR::CPVRRecording::Serialize(), PVR::CPVRTimerInfoTag::Serialize(), CVideoInfoTag::Serialize(), CMusicDatabase::SetArtistLinksUpdated(), CTextureDatabase::SetCachedTextureValid(), XMLUtils::SetDateTime(), XMLUtils::SetDateTime(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), ADDON::CAddonDatabase::SetLastUpdated(), ADDON::CAddonDatabase::SetLastUsed(), CMusicDatabase::SetLibraryLastCleaned(), CMusicDatabase::SetLibraryLastUpdated(), ADDON::CAddonDatabase::SetRepoUpdateData(), ADDON::CAddonDatabase::SyncInstalled(), TEST_F(), CFileItem::ToSortable(), MUSIC_INFO::CMusicInfoTag::ToSortable(), CPictureInfoTag::ToSortable(), PVR::CPVRChannel::ToSortable(), CVideoInfoTag::ToSortable(), CMusicDatabase::UpdateAlbum(), CMusicDatabase::UpdateArtist(), CVideoDatabase::UpdateFileDateAdded(), PVR::CPVREpgDatabase::UpdateSavedSearchLastExecuted(), CMusicDatabase::UpdateSong(), and CMusicDatabase::UpdateTables().
GetAsDBTime()
std::string CDateTime::GetAsDBTime () const
References GetAsSystemTime(), KODI::TIME::SystemTime::hour, KODI::TIME::SystemTime::minute, and KODI::TIME::SystemTime::second.
Referenced by TEST_F(), and TEST_F().
GetAsLocalizedDate() [1/3]
std::string CDateTime::GetAsLocalizedDate (bool longDate = false) const
References g_langInfo, and GetAsLocalizedDate().
Referenced by PVR::CGUIDialogPVRTimerSettings::DaysFiller(), KODI::VIDEO::CVideoInfoScanner::EnumerateEpisodeItem(), GetAsLocalizedDate(), GetAsLocalizedDate(), anonymous_namespace{PVRGUIInfo.cpp}::GetAsLocalizedDateString(), GetAsLocalizedDateTime(), anonymous_namespace{LangInfo.cpp}::GetDateStringWithFormat(), XBMCAddon::xbmc::InfoTagVideo::getFirstAired(), CPictureInfoTag::GetInfo(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), XBMCAddon::xbmc::InfoTagMusic::getLastPlayed(), CLabelFormatter::GetMaskContent(), CGUIInfoManager::GetMultiInfoItemLabel(), XBMCAddon::xbmc::InfoTagVideo::getPremiered(), XBMCAddon::xbmc::getRegion(), PVR::CGUIEPGGridContainerModel::Initialize(), KODI::UTILS::StringUtils::ISODateToLocalizedDate(), KODI::VIDEO::CVideoInfoScanner::ProcessItemByVideoInfoTag(), CProfile::setDate(), TEST_F(), and CGUIControlRangeSetting::Update().
GetAsLocalizedDate() [2/3]
std::string CDateTime::GetAsLocalizedDate (const std::string & strFormat) const
References CHOICE_NO, and GetAsLocalizedDate().
GetAsLocalizedDate() [3/3]
std::string CDateTime::GetAsLocalizedDate (const std::string & strFormat, ReturnFormat returnFormat) const
References CHOICE_YES, KODI::TIME::SystemTime::day, KODI::TIME::SystemTime::dayOfWeek, g_localizeStrings, CLocalizeStrings::Get(), GetAsSystemTime(), KODI::TIME::SystemTime::month, and KODI::TIME::SystemTime::year.
GetAsLocalizedDateTime()
std::string CDateTime::GetAsLocalizedDateTime (bool longDate = false, bool withSeconds = true) const
References GetAsLocalizedDate(), and GetAsLocalizedTime().
Referenced by anonymous_namespace{PVRGUIInfo.cpp}::GetAsLocalizedDateTimeString(), CPictureInfoTag::GetInfo(), XBMCAddon::xbmc::InfoTagVideo::getLastPlayed(), CLabelFormatter::GetMaskContent(), CGUIInfoManager::GetMultiInfoItemLabel(), KODI::RETRO::CSavestateDatabase::GetSavestateItem(), KODI::ADDONS::CImageDecoder::LoadInfoTag(), and TEST_F().
GetAsLocalizedTime() [1/2]
std::string CDateTime::GetAsLocalizedTime (const std::string & format, bool withSeconds = true) const
References g_langInfo, GetAsSystemTime(), KODI::TIME::SystemTime::hour, MeridiemSymbolAM, MeridiemSymbolPM, CLangInfo::MeridiemSymbolToString(), KODI::TIME::SystemTime::minute, and KODI::TIME::SystemTime::second.
Referenced by GetAsLocalizedDateTime(), GetAsLocalizedTime(), anonymous_namespace{PVRGUIInfo.cpp}::GetAsLocalizedTimeString(), PVR::CPVRGUITimesInfo::GetEpgEventFinishTime(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), CLabelFormatter::GetMaskContent(), CGUIInfoManager::GetMultiInfoItemLabel(), PVR::CGUIEPGGridContainerModel::Initialize(), CGUIEditControl::OnClick(), PVR::CGUIDialogPVRTimerSettings::OnSettingAction(), CProfile::setDate(), PVR::CGUIDialogPVRTimerSettings::SetTimer(), TEST_F(), PVR::CGUIDialogPVRGuideSearch::Update(), CGUIControlRangeSetting::Update(), and PVR::CPVRTimerInfoTag::UpdateSummary().
GetAsLocalizedTime() [2/2]
std::string CDateTime::GetAsLocalizedTime (TIME_FORMAT format, bool withSeconds = false) const
References g_langInfo, GetAsLocalizedTime(), TIME_FORMAT_GUESS, TIME_FORMAT_H, TIME_FORMAT_H_MM_SS, TIME_FORMAT_H_MM_SS_XX, TIME_FORMAT_HH, TIME_FORMAT_HH_MM, TIME_FORMAT_HH_MM_SS, TIME_FORMAT_HH_MM_SS_XX, TIME_FORMAT_HH_MM_XX, TIME_FORMAT_HH_SS, TIME_FORMAT_M, TIME_FORMAT_MM, TIME_FORMAT_MM_SS, TIME_FORMAT_SS, and TIME_FORMAT_XX.
GetAsRFC1123DateTime()
std::string CDateTime::GetAsRFC1123DateTime () const
References DAY_NAMES, GetAsUTCDateTime(), CLog::Log(), LOGWARNING, and MONTH_NAMES.
Referenced by TestWebServer::CheckHtmlTestFileResponse(), TestWebServer::CheckRangesTestFileResponse(), TestWebServer::CheckRangesTestFileResponse(), CDVDRadioRDSData::DecodeRTC(), CWebServer::FinalizeRequest(), CFileItem::Serialize(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
GetAsSaveString()
std::string CDateTime::GetAsSaveString () const
References KODI::TIME::SystemTime::day, GetAsSystemTime(), KODI::TIME::SystemTime::hour, KODI::TIME::SystemTime::minute, KODI::TIME::SystemTime::month, KODI::TIME::SystemTime::second, and KODI::TIME::SystemTime::year.
Referenced by PVR::CPVRRecordingsPath::CPVRRecordingsPath(), KODI::RETRO::CSavestateDatabase::MakeSavestatePath(), and TEST_F().
GetAsSystemTime()
void CDateTime::GetAsSystemTime (KODI::TIME::SystemTime & time) const
References m_time.
Referenced by Archive(), GetAsDBDate(), GetAsDBDateTime(), GetAsDBTime(), GetAsLocalizedDate(), GetAsLocalizedTime(), GetAsSaveString(), GetAsTm(), GetAsW3CDate(), GetAsW3CDateTime(), GetDay(), GetDayOfWeek(), GetHour(), GetMinute(), GetMinuteOfDay(), GetMonth(), GetSecond(), GetYear(), CGUIEditControl::OnClick(), PVR::CGUIDialogPVRTimerSettings::OnSettingAction(), PVR::CGUIWindowPVRGuideBase::OpenDateSelectionDialog(), CGUIDialogNumeric::SetMode(), ADDON::Interface_GUIDialogNumeric::show_and_get_date(), ADDON::Interface_GUIDialogNumeric::show_and_get_time(), TEST_F(), and TEST_F().
GetAsTime()
void CDateTime::GetAsTime (time_t & time) const
References KODI::TIME::FileTime::highDateTime, KODI::TIME::FileTime::lowDateTime, m_time, and UNIX_BASE_TIME.
Referenced by anonymous_namespace{PVRClient.cpp}::CAddonRecording::CAddonRecording(), anonymous_namespace{PVRClient.cpp}::CAddonTimer::CAddonTimer(), ADDON::CFileItemListToVFSDirEntries(), PVR::CPVREpgContainer::CheckPlayingEvents(), PVR::CPVRTimerInfoTag::ConvertLocalTimeToUTC(), PVR::CPVRTimerInfoTag::ConvertUTCToLocalTime(), PVR::CPVREpgContainer::CreateChannelEpg(), PVR::CPVREpgDatabase::DeleteEpgTags(), PVR::CGUIDialogPVRTimerSettings::GetDateAsIndex(), PVR::CPVREpgInfoTag::GetDuration(), PVR::CPVRTimerInfoTag::GetDuration(), PVR::CPVRTimerInfoTag::GetEpgInfoTag(), PVR::CPVREpgDatabase::GetEpgTagByMaxEndTime(), PVR::CPVREpgDatabase::GetEpgTagByMinStartTime(), PVR::CPVREpgDatabase::GetEpgTags(), PVR::CPVREpgDatabase::GetEpgTagsByMinEndMaxStartTime(), PVR::CPVREpgDatabase::GetEpgTagsByMinStartMaxEndTime(), PVR::CPVREpgDatabase::GetMaxEndTime(), PVR::CPVREpgDatabase::GetMinStartTime(), PVR::CPVREpg::GetTagBetween(), PVR::CPVREpgContainer::Process(), PVR::CPVREpgInfoTag::Progress(), PVR::CPVREpgInfoTag::ProgressPercentage(), PVR::CPVREpgDatabase::QueueDeleteEpgTagsByMinEndMaxStartTimeQuery(), PVR::CPVREpgContainer::RemoveOldEntries(), PVR::CPVRManager::SetWakeupCommand(), TEST_F(), TEST_F(), PVR::CPVREpg::Update(), and PVR::CPVREpgContainer::UpdateEPG().
GetAsTimeStamp()
void CDateTime::GetAsTimeStamp (KODI::TIME::FileTime & time) const
References KODI::TIME::LocalFileTimeToFileTime(), and m_time.
Referenced by TEST_F(), and TEST_F().
GetAsTm()
void CDateTime::GetAsTm (tm & time) const
References KODI::TIME::SystemTime::day, KODI::TIME::SystemTime::dayOfWeek, GetAsSystemTime(), KODI::TIME::SystemTime::hour, KODI::TIME::SystemTime::minute, KODI::TIME::SystemTime::month, KODI::TIME::SystemTime::second, and KODI::TIME::SystemTime::year.
Referenced by ADDON::Interface_GUIDialogNumeric::show_and_get_date(), ADDON::Interface_GUIDialogNumeric::show_and_get_time(), TEST_F(), and TEST_F().
GetAsUTCDateTime()
CDateTime CDateTime::GetAsUTCDateTime () const
References GetTimezoneBias(), and m_time.
Referenced by PVR::CPVRGUIActionsPowerManagement::CanSystemPowerdown(), PVR::CPVREpgContainer::CheckPlayingEvents(), PVR::CPVREpgContainer::CreateChannelEpg(), GetAsRFC1123DateTime(), GetAsW3CDateTime(), PVR::CPVRTimers::GetNextEventTime(), PVR::CPVRTimerRuleMatcher::GetNextTimerStart(), CWebServer::HandlePartialRequest(), CWebServer::IsRequestRanged(), PVR::CPVREpgContainer::Process(), PVR::CPVREpgInfoTag::Progress(), PVR::CPVREpgInfoTag::ProgressPercentage(), PVR::CGUIDialogPVRGuideSearch::ReadDateTime(), PVR::CPVREpgContainer::RemoveOldEntries(), TEST_F(), and PVR::CPVREpgContainer::UpdateEPG().
GetAsW3CDate()
std::string CDateTime::GetAsW3CDate () const
References KODI::TIME::SystemTime::day, GetAsSystemTime(), KODI::TIME::SystemTime::month, and KODI::TIME::SystemTime::year.
Referenced by UPNP::BuildObject(), anonymous_namespace{PVRClient.cpp}::CAddonEpgTag::GetFirstAired(), XBMCAddon::xbmc::InfoTagVideo::getFirstAiredAsW3C(), XBMCAddon::xbmc::InfoTagVideo::getPremieredAsW3C(), UPNP::PopulateObjectFromTag(), and TEST_F().
GetAsW3CDateTime()
std::string CDateTime::GetAsW3CDateTime (bool asUtc = false) const
References KODI::TIME::SystemTime::day, GetAsSystemTime(), GetAsUTCDateTime(), CDateTimeSpan::GetHours(), CDateTimeSpan::GetMinutes(), CDateTimeSpan::GetSecondsTotal(), GetTimezoneBias(), KODI::TIME::SystemTime::hour, KODI::TIME::SystemTime::minute, KODI::TIME::SystemTime::month, KODI::TIME::SystemTime::second, and KODI::TIME::SystemTime::year.
Referenced by XBMCAddon::xbmc::InfoTagMusic::getLastPlayedAsW3C(), XBMCAddon::xbmc::InfoTagVideo::getLastPlayedAsW3C(), KODI::RETRO::CSavestateFlatBuffer::SetCreated(), TEST_F(), and UPNP::CMediaBrowser::UpdateItem().
GetCurrentDateTime()
CDateTime CDateTime::GetCurrentDateTime () static
References CDateTime(), and KODI::TIME::GetLocalTime().
Referenced by CMusicDatabase::AddAudioBook(), CTextureDatabase::AddCachedTexture(), ADDON::CAddonDatabase::AddInstalledAddon(), AddMatchingUPnPServers(), PVR::CPVREpgContainer::CheckPlayingEvents(), ADDON::CScraper::ClearCache(), PVR::CPVREpgContainer::CreateChannelEpg(), PVR::CGUIDialogPVRTimerSettings::DaysFiller(), ADDON::CRepositoryUpdateJob::DoWork(), CMusicDatabase::ExportToXML(), CVideoDatabase::ExportToXML(), CWebServer::FinalizeRequest(), CWakeOnAccess::FindOrTouchHostEntry(), CDatabaseQueryRule::FormatParameter(), KODI::CDRIP::CCDDARipper::GetAlbumDirName(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), CTextureDatabase::GetCachedTexture(), CVideoDatabase::GetDateAdded(), XFILE::CRSSDirectory::GetDirectory(), PVR::CPVRGUITimesInfo::GetEpgEventFinishTime(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), CMusicDatabase::GetMediaDateFromFile(), XFILE::GetRecentlyUpdatedAddons(), XBMCAddon::xbmc::getRegion(), GetUTCDateTime(), CHTTPPythonHandler::HandleRequest(), CMusicDatabase::IncrementPlayCount(), PVR::CGUIDialogPVRTimerSettings::InitializeTypesList(), CTextureDatabase::InvalidateCachedTexture(), PVR::CPVREpgInfoTag::IsRecordable(), LookupUPnPHost(), PERIPHERALS::CPeripheralJoystick::OnAxisMotion(), PERIPHERALS::CPeripheralJoystick::OnButtonMotion(), PERIPHERALS::CPeripheralMouse::OnButtonPress(), PERIPHERALS::CPeripheralJoystick::OnHatMotion(), PVR::CGUIDialogPVRGuideInfo::OnInitWindow(), PERIPHERALS::CPeripheralKeyboard::OnKeyPress(), PERIPHERALS::CPeripheralMouse::OnPosition(), PVR::CPVREpgContainer::Process(), PVR::CPVREpgInfoTag::Progress(), PVR::CPVREpgInfoTag::ProgressPercentage(), PVR::CPVREpgContainer::RemoveOldEntries(), ADDON::CRepositoryUpdater::ScheduleUpdate(), ADDON::CAddonMgr::SetAddonOrigin(), CTextureDatabase::SetCachedTextureValid(), CProfile::setDate(), CWeatherJob::SetFromProperties(), CVideoDatabase::SetPlayCount(), CLangInfo::SettingOptionsLongDateFormatsFiller(), CLangInfo::SettingOptionsShortDateFormatsFiller(), CLangInfo::SettingOptionsTimeFormatsFiller(), ADDON::CAddonDatabase::SyncInstalled(), TEST_F(), CWakeOnAccess::TouchHostEntry(), PVR::CPVREpgContainer::UpdateEPG(), UPNP::CMediaBrowser::UpdateItem(), CVideoDatabase::UpdateLastPlayed(), ADDON::CAddonMgr::UpdateLastUsed(), CMusicDatabase::UpdateSong(), and CMusicDatabase::UpdateTables().
GetDay()
int CDateTime::GetDay () const
References KODI::TIME::SystemTime::day, and GetAsSystemTime().
Referenced by PVR::CGUIDialogPVRTimerSettings::DaysFiller(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), PVR::CGUIDialogPVRTimerSettings::GetDateAsIndex(), PVR::CPVRTimers::GetNextEventTime(), PVR::CPVRTimerRuleMatcher::GetNextTimerStart(), PVR::CGUIEPGGridContainerModel::Initialize(), PVR::CPVRTimerRuleMatcher::MatchStart(), PVR::CGUIDialogPVRGuideSearch::ReadDateTime(), PVR::CGUIDialogPVRTimerSettings::SetDateFromIndex(), XBMCAddon::xbmc::InfoTagPicture::setDateTimeTakenRaw(), PVR::CGUIDialogPVRTimerSettings::SetTimeFromSystemTime(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
GetDayOfWeek()
int CDateTime::GetDayOfWeek () const
References KODI::TIME::SystemTime::dayOfWeek, and GetAsSystemTime().
Referenced by PVR::CPVRTimerRuleMatcher::GetNextTimerStart(), and PVR::CPVRTimerRuleMatcher::MatchDayOfWeek().
GetHour()
int CDateTime::GetHour () const
References GetAsSystemTime(), and KODI::TIME::SystemTime::hour.
Referenced by PVR::CPVRTimers::GetNextEventTime(), PVR::CPVRTimerRuleMatcher::GetNextTimerStart(), PVR::CGUIEPGGridContainerModel::Initialize(), PVR::CPVRTimerRuleMatcher::MatchEnd(), PVR::CPVRTimerRuleMatcher::MatchStart(), PVR::CGUIDialogPVRTimerSettings::SetDateFromIndex(), XBMCAddon::xbmc::InfoTagPicture::setDateTimeTakenRaw(), PVR::CGUIDialogPVRTimerSettings::SetTimeFromSystemTime(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
GetMinute()
int CDateTime::GetMinute () const
References GetAsSystemTime(), and KODI::TIME::SystemTime::minute.
Referenced by PVR::CPVRTimers::GetNextEventTime(), PVR::CPVRTimerRuleMatcher::GetNextTimerStart(), PVR::CGUIEPGGridContainerModel::Initialize(), PVR::CPVRTimerRuleMatcher::MatchEnd(), PVR::CPVRTimerRuleMatcher::MatchStart(), PVR::CGUIDialogPVRTimerSettings::SetDateFromIndex(), XBMCAddon::xbmc::InfoTagPicture::setDateTimeTakenRaw(), PVR::CGUIDialogPVRTimerSettings::SetTimeFromSystemTime(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
GetMinuteOfDay()
int CDateTime::GetMinuteOfDay () const
References GetAsSystemTime(), KODI::TIME::SystemTime::hour, and KODI::TIME::SystemTime::minute.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool().
GetMonth()
int CDateTime::GetMonth () const
References GetAsSystemTime(), and KODI::TIME::SystemTime::month.
Referenced by PVR::CGUIDialogPVRTimerSettings::DaysFiller(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), PVR::CGUIDialogPVRTimerSettings::GetDateAsIndex(), PVR::CPVRTimers::GetNextEventTime(), PVR::CPVRTimerRuleMatcher::GetNextTimerStart(), PVR::CGUIEPGGridContainerModel::Initialize(), PVR::CPVRTimerRuleMatcher::MatchStart(), PVR::CGUIDialogPVRGuideSearch::ReadDateTime(), PVR::CGUIDialogPVRTimerSettings::SetDateFromIndex(), XBMCAddon::xbmc::InfoTagPicture::setDateTimeTakenRaw(), PVR::CGUIDialogPVRTimerSettings::SetTimeFromSystemTime(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
GetSecond()
int CDateTime::GetSecond () const
References GetAsSystemTime(), and KODI::TIME::SystemTime::second.
Referenced by PVR::CPVRTimers::GetNextEventTime(), PVR::CGUIDialogPVRTimerSettings::SetDateFromIndex(), XBMCAddon::xbmc::InfoTagPicture::setDateTimeTakenRaw(), PVR::CGUIDialogPVRTimerSettings::SetTimeFromSystemTime(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
GetTimezoneBias()
CDateTimeSpan CDateTime::GetTimezoneBias (void) static
References bGotTimezoneBias, KODI::TIME::TimeZoneInformation::bias, KODI::TIME::TimeZoneInformation::daylightBias, KODI::TIME::GetTimeZoneInformation(), KODI::TIME::KODI_TIME_ZONE_ID_DAYLIGHT, KODI::TIME::KODI_TIME_ZONE_ID_STANDARD, KODI::TIME::KODI_TIME_ZONE_ID_UNKNOWN, and KODI::TIME::TimeZoneInformation::standardBias.
Referenced by GetAsUTCDateTime(), GetAsW3CDateTime(), GetUTCDateTime(), SetFromUTCDateTime(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
GetUTCDateTime()
CDateTime CDateTime::GetUTCDateTime () static
References GetCurrentDateTime(), and GetTimezoneBias().
Referenced by PVR::CPVRTimers::AddLocalTimer(), PVR::CPVRGUIActionsTimers::AddTimer(), PVR::CPVRGUIActionsTimers::AnnounceReminder(), PVR::CPVRGUIActionsPowerManagement::CanSystemPowerdown(), PVR::CPVREpg::Cleanup(), PVR::CPVRTimerInfoTag::CPVRTimerInfoTag(), PVR::CPVRTimerInfoTag::CreateFromDate(), KODI::RETRO::CReversiblePlayback::CreateSavestate(), PVR::CPVREpgSearch::Execute(), PVR::CPVRPlaybackState::GetChannelPlaybackTime(), PVR::CPVRClient::GetChannels(), PVR::CGUIEPGGridContainer::GetCurrentTimePositionOnPage(), PVR::CPVRTimers::GetNextEventTime(), PVR::CGUIEPGGridContainerModel::GetNowBlock(), PVR::CGUIEPGGridContainer::GoToNow(), PVR::CGUIEPGGridContainerModel::Initialize(), PVR::CPVRGUIActionsPowerManagement::IsNextEventWithinBackendIdleTime(), anonymous_namespace{Epg.cpp}::IsTagExpired(), PVR::CPVREpgSearchFilter::MatchStartAndEndTimes(), PVR::CGUIWindowPVRGuideBase::OnMessage(), KODI::GAME::CDialogInGameSaves::OnNewSave(), KODI::GAME::CDialogInGameSaves::OnOverwrite(), PVR::CPVRPlaybackState::OnPlaybackStarted(), PVR::CPVRPlaybackState::OnPlaybackStopped(), PVR::CGUIWindowPVRGuideBase::RefreshTimelineItems(), PVR::CPVREpgContainer::RemoveOldEntries(), CMusicDatabase::SetArtistLinksUpdated(), CMusicDatabase::SetLibraryLastCleaned(), CMusicDatabase::SetLibraryLastUpdated(), TEST_F(), PVR::CGUIDialogPVRGuideSearch::Update(), PVR::CPVREpg::Update(), CMusicDatabase::UpdateAlbum(), CMusicDatabase::UpdateArtist(), PVR::CPVREpg::UpdateEntries(), PVR::CPVRTimers::UpdateEntries(), PVR::CPVREpg::UpdateEntry(), PVR::CPVREpgContainer::UpdateEPG(), PVR::CPVRChannelGroup::UpdateFromClient(), CMusicDatabase::UpdateTables(), and PVR::CPVRRecording::WillBeExpiredWithNewLifetime().
GetYear()
int CDateTime::GetYear () const
References GetAsSystemTime(), and KODI::TIME::SystemTime::year.
Referenced by PVR::CGUIDialogPVRTimerSettings::DaysFiller(), DatabaseUtils::GetDatabaseResults(), PVR::CGUIDialogPVRTimerSettings::GetDateAsIndex(), PVR::CPVRTimers::GetNextEventTime(), PVR::CPVRTimerRuleMatcher::GetNextTimerStart(), CVideoInfoTag::GetYear(), PVR::CPVRRecording::GetYear(), PVR::CGUIEPGGridContainerModel::Initialize(), PVR::CPVRTimerRuleMatcher::MatchStart(), PVR::CGUIDialogPVRGuideSearch::ReadDateTime(), PVR::CGUIDialogPVRTimerSettings::SetDateFromIndex(), XBMCAddon::xbmc::InfoTagPicture::setDateTimeTakenRaw(), PVR::CGUIDialogPVRTimerSettings::SetTimeFromSystemTime(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
IsValid()
bool CDateTime::IsValid () const
References m_state, and valid.
Referenced by CVideoDatabase::AddFile(), PVR::CPVRTimers::AddLocalTimer(), CVideoDatabase::AddPath(), CMusicDatabase::AddSong(), PVR::CPVRGUIActionsTimers::AddTimer(), KODI::VIDEO::CVideoInfoScanner::AddVideo(), UPNP::BuildObject(), CFileItem::CFileItem(), CSettingDate::CheckValidity(), CSettingTime::CheckValidity(), CDVDRadioRDSData::DecodeRTC(), CSaveFileState::DoWork(), CWebServer::FinalizeRequest(), KODI::VIDEO::CVideoInfoScanner::GetAirDateFromRegExp(), anonymous_namespace{PVRGUIInfo.cpp}::GetAsLocalizedDateString(), anonymous_namespace{PVRGUIInfo.cpp}::GetAsLocalizedDateTimeString(), anonymous_namespace{PVRGUIInfo.cpp}::GetAsLocalizedTimeString(), CTextureDatabase::GetCachedTexture(), DatabaseUtils::GetDatabaseResults(), CVideoDatabase::GetDateAdded(), CVideoDatabase::GetDetailsForTvShow(), PVR::CPVREpgDatabase::GetEpgTags(), CVideoDatabase::GetFileInfo(), PVR::CPVREpgContainer::GetFirstAndLastEPGDate(), CPictureInfoTag::GetInfo(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), CHTTPFileHandler::GetLastModifiedDate(), CHTTPImageTransformationHandler::GetLastModifiedDate(), CHTTPPythonHandler::GetLastModifiedDate(), TestWebServer::GetLastModifiedOfTestFile(), CLabelFormatter::GetMaskContent(), CMusicDatabase::GetMediaDateFromFile(), CGUIInfoManager::GetMultiInfoItemLabel(), PVR::CPVRTimers::GetNextEventTime(), PVR::CPVRGUIDirectory::GetRecordingsDirectoryInfo(), PVR::CPVREpgTagsContainer::GetTimeline(), CVideoInfoTag::GetYear(), PVR::CPVRRecording::GetYear(), GroupUtils::Group(), CWebServer::HandlePartialRequest(), CHTTPPythonHandler::HandleRequest(), CVideoInfoTag::HasYear(), PVR::CPVRRecording::HasYear(), CWebServer::IsRequestRanged(), PVR::CPVREpgSearchFilter::MatchStartAndEndTimes(), CVideoInfoTag::Merge(), XFILE::CDAVDirectory::ParseResponse(), PVR::CPVRDatabase::Persist(), PVR::CPVREpgDatabase::Persist(), UPNP::PopulateTagFromObject(), PVR::CPVREpgTagsCache::Refresh(), PVR::CGUIWindowPVRGuideBase::RefreshTimelineItems(), MUSIC_INFO::CMusicInfoTag::Serialize(), CFileItem::Serialize(), CSong::Serialize(), PVR::CPVRChannel::Serialize(), PVR::CPVREpgInfoTag::Serialize(), PVR::CPVRRecording::Serialize(), PVR::CPVRTimerInfoTag::Serialize(), CVideoInfoTag::Serialize(), XMLUtils::SetDate(), XMLUtils::SetDate(), XMLUtils::SetDateTime(), XMLUtils::SetDateTime(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), CVideoDatabase::SetDetailsForMusicVideo(), CHTTPFileHandler::SetFile(), JSONRPC::CFileOperations::SetFileDetails(), SetFromW3CDate(), SetFromW3CDateTime(), CGUIDialogNumeric::SetMode(), CVideoDatabase::SetPlayCount(), CVideoInfoTag::SetPremiered(), PVR::CPVRManager::SetWakeupCommand(), CFileItem::ToSortable(), MUSIC_INFO::CMusicInfoTag::ToSortable(), CPictureInfoTag::ToSortable(), PVR::CPVRChannel::ToSortable(), CVideoInfoTag::ToSortable(), PVR::CGUIDialogPVRGuideSearch::Update(), PVR::CPVREpg::Update(), CVideoDatabase::UpdateDetailsForMovie(), PVR::CPVRTimers::UpdateEntries(), UPNP::CMediaBrowser::UpdateItem(), CMusicDatabase::UpdateSong(), and CVideoLibraryMarkWatchedJob::Work().
MonthStringToMonthNum()
int CDateTime::MonthStringToMonthNum (const std::string & month) static
Referenced by XFILE::CHTTPDirectory::GetDirectory(), and TEST_F().
operator KODI::TIME::FileTime()
CDateTime::operator KODI::TIME::FileTime () const
operator!=() [1/5]
bool CDateTime::operator!= (const CDateTime & right) const
References operator==(), and right.
operator!=() [2/5]
bool CDateTime::operator!= (const KODI::TIME::FileTime & right) const
References operator==(), and right.
operator!=() [3/5]
bool CDateTime::operator!= (const KODI::TIME::SystemTime & right) const
References operator==(), and right.
operator!=() [4/5]
bool CDateTime::operator!= (const time_t & right) const
References operator==(), and right.
operator!=() [5/5]
bool CDateTime::operator!= (const tm & right) const
References operator==(), and right.
operator+()
CDateTime CDateTime::operator+ (const CDateTimeSpan & right) const
References left, _LARGE_INTEGER::QuadPart, and right.
operator+=()
const CDateTime & CDateTime::operator+= (const CDateTimeSpan & right)
References FromLargeInt(), _LARGE_INTEGER::QuadPart, right, and ToLargeInt().
operator-() [1/2]
CDateTimeSpan CDateTime::operator- (const CDateTime & right) const
References left, _LARGE_INTEGER::QuadPart, right, and ToLargeInt().
operator-() [2/2]
CDateTime CDateTime::operator- (const CDateTimeSpan & right) const
References left, _LARGE_INTEGER::QuadPart, and right.
operator-=()
const CDateTime & CDateTime::operator-= (const CDateTimeSpan & right)
References FromLargeInt(), _LARGE_INTEGER::QuadPart, right, and ToLargeInt().
operator<() [1/5]
bool CDateTime::operator< (const CDateTime & right) const
References operator<(), and right.
Referenced by operator<(), operator<(), operator<(), operator<(), operator<=(), operator<=(), operator<=(), operator<=(), and operator<=().
operator<() [2/5]
bool CDateTime::operator< (const KODI::TIME::FileTime & right) const
References KODI::TIME::CompareFileTime(), m_time, and right.
operator<() [3/5]
bool CDateTime::operator< (const KODI::TIME::SystemTime & right) const
References operator<(), right, and ToFileTime().
operator<() [4/5]
bool CDateTime::operator< (const time_t & right) const
References operator<(), right, and ToFileTime().
operator<() [5/5]
bool CDateTime::operator< (const tm & right) const
References operator<(), right, and ToFileTime().
operator<=() [1/5]
bool CDateTime::operator<= (const CDateTime & right) const
References operator<(), operator==(), and right.
operator<=() [2/5]
bool CDateTime::operator<= (const KODI::TIME::FileTime & right) const
References operator<(), operator==(), and right.
operator<=() [3/5]
bool CDateTime::operator<= (const KODI::TIME::SystemTime & right) const
References operator<(), operator==(), and right.
operator<=() [4/5]
bool CDateTime::operator<= (const time_t & right) const
References operator<(), operator==(), and right.
operator<=() [5/5]
bool CDateTime::operator<= (const tm & right) const
References operator<(), operator==(), and right.
operator=() [1/5]
CDateTime & CDateTime::operator= (const CDateTime &) default
operator=() [2/5]
const CDateTime & CDateTime::operator= (const KODI::TIME::FileTime & right)
References m_time, right, and SetValid().
operator=() [3/5]
const CDateTime & CDateTime::operator= (const KODI::TIME::SystemTime & right)
References invalid, m_state, m_time, right, ToFileTime(), and valid.
operator=() [4/5]
const CDateTime & CDateTime::operator= (const time_t & right)
References invalid, m_state, m_time, right, ToFileTime(), and valid.
operator=() [5/5]
const CDateTime & CDateTime::operator= (const tm & right)
References invalid, m_state, m_time, right, ToFileTime(), and valid.
operator==() [1/5]
bool CDateTime::operator== (const CDateTime & right) const
References operator==(), and right.
Referenced by operator!=(), operator!=(), operator!=(), operator!=(), operator!=(), operator<=(), operator<=(), operator<=(), operator<=(), operator<=(), operator==(), operator==(), operator==(), operator==(), operator>=(), operator>=(), operator>=(), operator>=(), and operator>=().
operator==() [2/5]
bool CDateTime::operator== (const KODI::TIME::FileTime & right) const
References KODI::TIME::CompareFileTime(), m_time, and right.
operator==() [3/5]
bool CDateTime::operator== (const KODI::TIME::SystemTime & right) const
References operator==(), right, and ToFileTime().
operator==() [4/5]
bool CDateTime::operator== (const time_t & right) const
References operator==(), right, and ToFileTime().
operator==() [5/5]
bool CDateTime::operator== (const tm & right) const
References operator==(), right, and ToFileTime().
operator>() [1/5]
bool CDateTime::operator> (const CDateTime & right) const
References operator>(), and right.
Referenced by operator>(), operator>(), operator>(), operator>(), operator>=(), operator>=(), operator>=(), operator>=(), and operator>=().
operator>() [2/5]
bool CDateTime::operator> (const KODI::TIME::FileTime & right) const
References KODI::TIME::CompareFileTime(), m_time, and right.
operator>() [3/5]
bool CDateTime::operator> (const KODI::TIME::SystemTime & right) const
References operator>(), right, and ToFileTime().
operator>() [4/5]
bool CDateTime::operator> (const time_t & right) const
References operator>(), right, and ToFileTime().
operator>() [5/5]
bool CDateTime::operator> (const tm & right) const
References operator>(), right, and ToFileTime().
operator>=() [1/5]
bool CDateTime::operator>= (const CDateTime & right) const
References operator==(), operator>(), and right.
operator>=() [2/5]
bool CDateTime::operator>= (const KODI::TIME::FileTime & right) const
References operator==(), operator>(), and right.
operator>=() [3/5]
bool CDateTime::operator>= (const KODI::TIME::SystemTime & right) const
References operator==(), operator>(), and right.
operator>=() [4/5]
bool CDateTime::operator>= (const time_t & right) const
References operator==(), operator>(), and right.
operator>=() [5/5]
bool CDateTime::operator>= (const tm & right) const
References operator==(), operator>(), and right.
Reset()
void CDateTime::Reset ()
References SetDateTime(), and SetValid().
Referenced by Archive(), CAlbum::CAlbum(), CDateTime(), CSong::Clear(), MUSIC_INFO::CMusicInfoTag::Clear(), CFileItem::Reset(), CAlbum::Reset(), CArtist::Reset(), CPictureInfoTag::Reset(), PVR::CPVREpgTagsCache::Reset(), PVR::CPVRRecording::Reset(), CVideoInfoTag::Reset(), JSONRPC::CFileOperations::SetFileDetails(), JSONRPC::CJSONUtils::SetFromDBDate(), JSONRPC::CJSONUtils::SetFromDBDateTime(), and TEST_F().
ResetTimezoneBias()
void CDateTime::ResetTimezoneBias (void) static
References bGotTimezoneBias.
Referenced by PVR::CPVRGUIActionsDatabase::ResetDatabase().
SetDate()
bool CDateTime::SetDate (int year, int month, int day)
References day, and SetDateTime().
Referenced by KODI::VIDEO::CVideoInfoScanner::GetAirDateFromRegExp(), ADDON::CScraper::GetEpisodeList(), SetFromDBDate(), TEST(), TEST(), and TEST_F().
SetDateTime()
bool CDateTime::SetDateTime (int year, int month, int day, int hour, int minute, int second)
References day, KODI::TIME::SystemTime::day, KODI::TIME::SystemTime::hour, invalid, m_state, m_time, KODI::TIME::SystemTime::minute, KODI::TIME::SystemTime::month, KODI::TIME::SystemTime::second, ToFileTime(), valid, and KODI::TIME::SystemTime::year.
Referenced by CDateTime(), CPictureInfoTag::ConvertDateTime(), CDVDRadioRDSData::DecodeRTC(), PVR::CPVRTimers::GetNextEventTime(), PVR::CGUIDialogPVRGuideSearch::ReadDateTime(), Reset(), SetDate(), PVR::CGUIDialogPVRTimerSettings::SetDateFromIndex(), SetFromDateString(), SetFromDBDateTime(), SetFromRFC1123DateTime(), SetTime(), PVR::CGUIDialogPVRTimerSettings::SetTimeFromSystemTime(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
SetFromDateString()
bool CDateTime::SetFromDateString (const std::string & date)
Todo:
STRING_CLEANUP
References SetDateTime(), SetFromDBDate(), and SetValid().
Referenced by FromDateString(), CVideoDatabase::GetYearsNav(), ParseItemZink(), XBMCAddon::xbmc::InfoTagVideo::setFirstAiredRaw(), XBMCAddon::xbmc::InfoTagVideo::setPremieredRaw(), and TEST_F().
SetFromDBDate()
bool CDateTime::SetFromDBDate (const std::string & date)
References day, and SetDate().
Referenced by FromDBDate(), DatabaseUtils::GetDatabaseResults(), XMLUtils::GetDate(), XMLUtils::GetDate(), KODI::UTILS::StringUtils::ISODateToLocalizedDate(), CGUIEditControl::OnClick(), PVR::CGUIDialogPVRGuideSearch::ReadDateTime(), SetFromDateString(), JSONRPC::CJSONUtils::SetFromDBDate(), CGUIDialogNumeric::SetMode(), CVideoInfoTag::SetPremieredFromDBDate(), and TEST_F().
SetFromDBDateTime()
bool CDateTime::SetFromDBDateTime (const std::string & dateTime)
set from a database datetime format YYYY-MM-DD HH:MM:SS
See also
GetAsDBDateTime()
References day, min, and SetDateTime().
Referenced by CVideoInfoTag::Archive(), FromDBDateTime(), CTextureDatabase::GetCachedTexture(), XMLUtils::GetDateTime(), XMLUtils::GetDateTime(), CVideoDatabase::GetDetailsForEpisode(), CVideoDatabase::GetDetailsForMovie(), CVideoDatabase::GetDetailsForMusicVideo(), CVideoDatabase::GetDetailsForTvShow(), CVideoDatabase::GetFileInfo(), PVR::CPVREpgDatabase::GetLastEpgScanTime(), CVideoDatabase::GetLastPlayed(), CMusicDatabase::GetSongFromDataset(), CAlbum::SetDateAdded(), CArtist::SetDateAdded(), MUSIC_INFO::CMusicInfoTag::SetDateAdded(), XBMCAddon::xbmc::InfoTagVideo::setDateAddedRaw(), CAlbum::SetDateNew(), CArtist::SetDateNew(), MUSIC_INFO::CMusicInfoTag::SetDateNew(), CAlbum::SetDateUpdated(), CArtist::SetDateUpdated(), MUSIC_INFO::CMusicInfoTag::SetDateUpdated(), CVideoDatabase::SetDetailsForEpisode(), CVideoDatabase::SetDetailsForMovie(), JSONRPC::CJSONUtils::SetFromDBDateTime(), CAlbum::SetLastPlayed(), MUSIC_INFO::CMusicInfoTag::SetLastPlayed(), XBMCAddon::xbmc::InfoTagVideo::setLastPlayedRaw(), JSONRPC::CAudioLibrary::SetSongDetails(), TEST_F(), TEST_F(), and TEST_F().
SetFromDBTime()
bool CDateTime::SetFromDBTime (const std::string & time)
References SetTime().
Referenced by PVR::CPVRGUIActionsPowerManagement::CanSystemPowerdown(), FromDBTime(), PVR::CPVRTimers::GetNextEventTime(), CGUIEditControl::OnClick(), and CGUIDialogNumeric::SetMode().
SetFromRFC1123DateTime()
bool CDateTime::SetFromRFC1123DateTime (const std::string & dateTime)
References day, index(), min, MONTH_NAMES, and SetDateTime().
Referenced by FromRFC1123DateTime(), CWebServer::HandlePartialRequest(), CWebServer::IsRequestRanged(), and TEST_F().
SetFromUTCDateTime() [1/2]
bool CDateTime::SetFromUTCDateTime (const CDateTime & dateTime)
References GetTimezoneBias(), m_state, m_time, and valid.
Referenced by CFileItem::CFileItem(), PVR::CPVREpgInfoTag::EndAsLocalTime(), PVR::CPVRRecording::EndTimeAsLocalTime(), FromUTCDateTime(), FromUTCDateTime(), PVR::CPVRGUIInfo::GetListItemAndPlayerLabel(), PVR::CGUIEPGGridContainerModel::Initialize(), KODI::ADDONS::CImageDecoder::LoadInfoTag(), PVR::CPVRRecording::RecordingTimeAsLocalTime(), SetFromUTCDateTime(), SetFromW3CDateTime(), PVR::CPVREpgInfoTag::StartAsLocalTime(), TEST_F(), PVR::CPVRGUITimesInfo::TimeToTimeString(), PVR::CGUIDialogPVRGuideSearch::Update(), and PVR::CPVREpg::Update().
SetFromUTCDateTime() [2/2]
bool CDateTime::SetFromUTCDateTime (const time_t & dateTime)
References SetFromUTCDateTime().
SetFromW3CDate()
bool CDateTime::SetFromW3CDate (const std::string & date)
References day, and IsValid().
Referenced by PVR::CPVREpgInfoTag::CPVREpgInfoTag(), PVR::CPVREpgDatabase::CreateEpgTag(), FromW3CDate(), UPNP::PopulateTagFromObject(), and TEST_F().
SetFromW3CDateTime()
bool CDateTime::SetFromW3CDateTime (const std::string & date, bool ignoreTimezone = false)
References day, CDateTimeSpan::GetSecondsTotal(), IsValid(), min, CDateTimeSpan::SetFromTimeString(), and SetFromUTCDateTime().
Referenced by PVR::CPVRRecording::CPVRRecording(), KODI::RETRO::CSavestateFlatBuffer::Created(), FromW3CDateTime(), UPNP::CUPnPServer::OnUpdateObject(), UPNP::PopulateTagFromObject(), XBMCAddon::xbmc::InfoTagPicture::setDateTimeTakenRaw(), and TEST_F().
SetTime()
bool CDateTime::SetTime (int hour, int minute, int second)
References SetDateTime().
Referenced by SetFromDBTime(), and TEST_F().
SetValid()
void CDateTime::SetValid (bool yesNo)
References invalid, m_state, and valid.
Referenced by CDateTime(), KODI::VIDEO::CVideoInfoScanner::EnumerateEpisodeItem(), ADDON::CScraper::GetEpisodeList(), PVR::CPVREpgDatabase::GetLastEpgScanTime(), operator=(), PVR::PVREpgSearchData::Reset(), PVR::CPVREpgSearchFilter::Reset(), Reset(), and SetFromDateString().
ToFileTime() [1/3]
bool CDateTime::ToFileTime (const KODI::TIME::SystemTime & time, KODI::TIME::FileTime & fileTime) const private
References KODI::TIME::FileTime::highDateTime, KODI::TIME::FileTime::lowDateTime, and KODI::TIME::SystemTimeToFileTime().
Referenced by Archive(), CDateTime(), CDateTime(), CDateTime(), operator<(), operator<(), operator<(), operator=(), operator=(), operator=(), operator==(), operator==(), operator==(), operator>(), operator>(), operator>(), and SetDateTime().
ToFileTime() [2/3]
bool CDateTime::ToFileTime (const time_t & time, KODI::TIME::FileTime & fileTime) const private
References KODI::TIME::FileTime::highDateTime, and KODI::TIME::FileTime::lowDateTime.
ToFileTime() [3/3]
bool CDateTime::ToFileTime (const tm & time, KODI::TIME::FileTime & fileTime) const private
References KODI::TIME::SystemTime::day, KODI::TIME::SystemTime::dayOfWeek, KODI::TIME::SystemTime::hour, KODI::TIME::SystemTime::minute, KODI::TIME::SystemTime::month, KODI::TIME::SystemTime::second, and KODI::TIME::SystemTime::year.
ToLargeInt()
void CDateTime::ToLargeInt (LARGE_INTEGER & time) const private
References KODI::TIME::FileTime::highDateTime, KODI::TIME::FileTime::lowDateTime, and m_time.
Referenced by operator+=(), operator-(), and operator-=().
Member Data Documentation
m_state
STATE CDateTime::m_state private
Referenced by Archive(), CDateTime(), CDateTime(), CDateTime(), CDateTime(), IsValid(), operator=(), operator=(), operator=(), PVR::CPVRTimerInfoTag::operator==(), SetDateTime(), SetFromUTCDateTime(), SetValid(), and PVR::CPVRTimerInfoTag::UpdateEntry().
m_time
KODI::TIME::FileTime CDateTime::m_time private
Referenced by Archive(), CDateTime(), CDateTime(), CDateTime(), FromLargeInt(), GetAsSystemTime(), GetAsTime(), GetAsTimeStamp(), GetAsUTCDateTime(), operator<(), operator=(), operator=(), operator=(), operator=(), operator==(), operator>(), SetDateTime(), SetFromUTCDateTime(), and ToLargeInt().
The documentation for this class was generated from the following files:
XBDateTime.h
XBDateTime.cpp