Kodi Documentation: DVDInputStreamBluray.cpp File Reference
DVDInputStreamBluray.cpp File Reference
#include "DVDInputStreamBluray.h"
#include "DVDCodecs/Overlay/DVDOverlay.h"
#include "DVDCodecs/Overlay/DVDOverlayImage.h"
#include "IVideoPlayer.h"
#include "LangInfo.h"
#include "ServiceBroker.h"
#include "URL.h"
#include "filesystem/BlurayCallback.h"
#include "filesystem/Directory.h"
#include "filesystem/SpecialProtocol.h"
#include "guilib/LocalizeStrings.h"
#include "settings/DiscSettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "utils/Geometry.h"
#include "utils/LangCodeExpander.h"
#include "utils/StringUtils.h"
#include "utils/URIUtils.h"
#include "utils/XTimeUtils.h"
#include "utils/log.h"
#include "video/VideoFileItemClassify.h"
#include <functional>
#include <limits>
#include <memory>
#include <libbluray/bluray.h>
#include <libbluray/log_control.h>
Macros
#define LIBBLURAY_BYTESEEK 0
Functions
static int read_blocks (void *handle, void *buf, int lba, int num_blocks)
static void bluray_overlay_cb (void *this_gen, const BD_OVERLAY *ov)
static uint8_t clamp (double v)
static uint32_t build_rgba (const BD_PG_PALETTE_ENTRY &e)
static bool find_stream (int pid, BLURAY_STREAM_INFO *info, int count, std::string &language)
Macro Definition Documentation
LIBBLURAY_BYTESEEK
#define LIBBLURAY_BYTESEEK 0
Function Documentation
bluray_overlay_cb()
static void bluray_overlay_cb (void * this_gen, const BD_OVERLAY * ov) static
Referenced by CDVDInputStreamBluray::Open().
build_rgba()
static uint32_t build_rgba (const BD_PG_PALETTE_ENTRY & e) static
References clamp, PIXEL_ASHIFT, PIXEL_BSHIFT, PIXEL_GSHIFT, and PIXEL_RSHIFT.
Referenced by CDVDInputStreamBluray::OverlayCallback().
clamp()
static uint8_t clamp (double v) static
find_stream()
static bool find_stream (int pid, BLURAY_STREAM_INFO * info, int count, std::string & language) static
Referenced by CDVDInputStreamBluray::GetStreamInfo().
read_blocks()
static int read_blocks (void * handle, void * buf, int lba, int num_blocks) static
References int64_t(), CDVDInputStreamFile::Read(), and CDVDInputStreamFile::Seek().
Referenced by CDVDInputStreamBluray::Open().