Kodi Documentation: PERIPHERALS::PeripheralTypeTranslator Class Reference
PERIPHERALS::PeripheralTypeTranslator Class Reference
#include <PeripheralTypes.h>
Static Public Member Functions
static const char * TypeToString (const PeripheralType type)
static PeripheralType GetTypeFromString (const std::string &strType)
static const char * BusTypeToString (const PeripheralBusType type)
static PeripheralBusType GetBusTypeFromString (const std::string &strType)
static const char * FeatureToString (const PeripheralFeature type)
static PeripheralFeature GetFeatureTypeFromString (const std::string &strType)
static int HexStringToInt (const char *strHex)
static void FormatHexString (int iVal, std::string &strHexString)
Member Function Documentation
BusTypeToString()
static const char * PERIPHERALS::PeripheralTypeTranslator::BusTypeToString (const PeripheralBusType type) inline static
References PERIPHERALS::PERIPHERAL_BUS_ADDON, PERIPHERALS::PERIPHERAL_BUS_APPLICATION, PERIPHERALS::PERIPHERAL_BUS_CEC, PERIPHERALS::PERIPHERAL_BUS_PCI, and PERIPHERALS::PERIPHERAL_BUS_USB.
Referenced by PERIPHERALS::CPeripheral::CPeripheral(), PERIPHERALS::CPeripherals::GetByPath(), PERIPHERALS::CPeripheralAddon::GetDirectory(), PERIPHERALS::CPeripheralBus::GetDirectory(), PERIPHERALS::CPeripherals::GetDirectory(), PERIPHERALS::CPeripheral::Initialise(), PERIPHERALS::CPeripheralBus::Register(), and PERIPHERALS::CPeripheralAddon::Register().
FeatureToString()
static const char * PERIPHERALS::PeripheralTypeTranslator::FeatureToString (const PeripheralFeature type) inline static
References PERIPHERALS::FEATURE_BLUETOOTH, PERIPHERALS::FEATURE_CEC, PERIPHERALS::FEATURE_DISK, PERIPHERALS::FEATURE_HID, PERIPHERALS::FEATURE_IMON, PERIPHERALS::FEATURE_JOYSTICK, PERIPHERALS::FEATURE_KEYBOARD, PERIPHERALS::FEATURE_MOUSE, PERIPHERALS::FEATURE_NIC, PERIPHERALS::FEATURE_NYXBOARD, PERIPHERALS::FEATURE_POWER_OFF, PERIPHERALS::FEATURE_RUMBLE, PERIPHERALS::FEATURE_TUNER, and PERIPHERALS::FEATURE_UNKNOWN.
Referenced by PERIPHERALS::CPeripherals::TestFeature().
FormatHexString()
static void PERIPHERALS::PeripheralTypeTranslator::FormatHexString (int iVal, std::string & strHexString) inline static
Referenced by PERIPHERALS::CPeripheral::CPeripheral(), and PERIPHERALS::CPeripherals::GetMappingForDevice().
GetBusTypeFromString()
static PeripheralBusType PERIPHERALS::PeripheralTypeTranslator::GetBusTypeFromString (const std::string & strType) inline static
References PERIPHERALS::PERIPHERAL_BUS_ADDON, PERIPHERALS::PERIPHERAL_BUS_APPLICATION, PERIPHERALS::PERIPHERAL_BUS_CEC, PERIPHERALS::PERIPHERAL_BUS_PCI, PERIPHERALS::PERIPHERAL_BUS_UNKNOWN, and PERIPHERALS::PERIPHERAL_BUS_USB.
Referenced by PERIPHERALS::CPeripherals::LoadMappings().
GetFeatureTypeFromString()
static PeripheralFeature PERIPHERALS::PeripheralTypeTranslator::GetFeatureTypeFromString (const std::string & strType) inline static
References PERIPHERALS::FEATURE_BLUETOOTH, PERIPHERALS::FEATURE_CEC, PERIPHERALS::FEATURE_DISK, PERIPHERALS::FEATURE_HID, PERIPHERALS::FEATURE_IMON, PERIPHERALS::FEATURE_JOYSTICK, PERIPHERALS::FEATURE_KEYBOARD, PERIPHERALS::FEATURE_MOUSE, PERIPHERALS::FEATURE_NYXBOARD, PERIPHERALS::FEATURE_POWER_OFF, PERIPHERALS::FEATURE_RUMBLE, PERIPHERALS::FEATURE_TUNER, and PERIPHERALS::FEATURE_UNKNOWN.
GetTypeFromString()
static PeripheralType PERIPHERALS::PeripheralTypeTranslator::GetTypeFromString (const std::string & strType) inline static
References PERIPHERALS::PERIPHERAL_BLUETOOTH, PERIPHERALS::PERIPHERAL_CEC, PERIPHERALS::PERIPHERAL_DISK, PERIPHERALS::PERIPHERAL_HID, PERIPHERALS::PERIPHERAL_IMON, PERIPHERALS::PERIPHERAL_JOYSTICK, PERIPHERALS::PERIPHERAL_KEYBOARD, PERIPHERALS::PERIPHERAL_MOUSE, PERIPHERALS::PERIPHERAL_NIC, PERIPHERALS::PERIPHERAL_NYXBOARD, PERIPHERALS::PERIPHERAL_TUNER, and PERIPHERALS::PERIPHERAL_UNKNOWN.
Referenced by PERIPHERALS::CPeripherals::LoadMappings().
HexStringToInt()
static int PERIPHERALS::PeripheralTypeTranslator::HexStringToInt (const char * strHex) inline static
Referenced by PERIPHERALS::CPeripherals::LoadMappings().
TypeToString()
static const char * PERIPHERALS::PeripheralTypeTranslator::TypeToString (const PeripheralType type) inline static
References PERIPHERALS::PERIPHERAL_BLUETOOTH, PERIPHERALS::PERIPHERAL_CEC, PERIPHERALS::PERIPHERAL_DISK, PERIPHERALS::PERIPHERAL_HID, PERIPHERALS::PERIPHERAL_IMON, PERIPHERALS::PERIPHERAL_JOYSTICK, PERIPHERALS::PERIPHERAL_KEYBOARD, PERIPHERALS::PERIPHERAL_MOUSE, PERIPHERALS::PERIPHERAL_NIC, PERIPHERALS::PERIPHERAL_NYXBOARD, and PERIPHERALS::PERIPHERAL_TUNER.
Referenced by PERIPHERALS::CPeripheralAddon::GetDirectory(), PERIPHERALS::CPeripheralBus::GetDirectory(), PERIPHERALS::CPeripherals::GetMappingForDevice(), PERIPHERALS::CPeripheralBusAndroid::InitializeProperties(), PERIPHERALS::CPeripheralBusGCController::InitializeProperties(), PERIPHERALS::CPeripheralBusApplication::PerformDeviceScan(), PERIPHERALS::CPeripheralBus::Register(), PERIPHERALS::CPeripheralAddon::Register(), PERIPHERALS::CPeripheralBus::UnregisterRemovedDevices(), and PERIPHERALS::CPeripheralAddon::UnregisterRemovedDevices().
The documentation for this class was generated from the following file:
PeripheralTypes.h