Kodi Documentation: CMatrix< Order > Class Template Reference
CMatrix< Order > Class Template Reference
#include <ConversionMatrix.h>
Public Member Functions
CMatrix ()=default
CMatrix (const CMatrix< Order - 1 > &other)
CMatrix (const std::array< std::array< float, Order >, Order > &other)
CMatrix (const std::array< std::array< float, Order - 1 >, Order - 1 > &other)
virtual ~CMatrix ()=default
virtual CMatrix operator* (const std::array< std::array< float, Order >, Order > &other)
CMatrix operator* (const CMatrix &other)
CMatrix & operator*= (const CMatrix &other)
CMatrix & operator= (const std::array< std::array< float, Order - 1 >, Order - 1 > &other)
bool operator== (const CMatrix< Order > &other) const
std::array< float, Order > & operator[] (int index)
const std::array< float, Order > & operator[] (int index) const
std::array< std::array< float, Order >, Order > & Get ()
const std::array< std::array< float, Order >, Order > & Get () const
CMatrix & Invert ()
float * ToRaw ()
Protected Member Functions
std::array< std::array< float, Order >, Order > Invert (std::array< std::array< float, Order >, Order > &other) const
Protected Attributes
std::array< std::array< float, Order >, Order > m_mat {{}}
Constructor & Destructor Documentation
CMatrix() [1/4]
template<uint8_t Order> CMatrix< Order >::CMatrix () default
CMatrix() [2/4]
template<uint8_t Order> CMatrix< Order >::CMatrix (const CMatrix< Order - 1 > & other) explicit
References CMatrix< Order >::Get().
CMatrix() [3/4]
template<uint8_t Order> CMatrix< Order >::CMatrix (const std::array< std::array< float, Order >, Order > & other) inline explicit
CMatrix() [4/4]
template<uint8_t Order> CMatrix< Order >::CMatrix (const std::array< std::array< float, Order - 1 >, Order - 1 > & other) explicit
~CMatrix()
template<uint8_t Order> virtual CMatrix< Order >::~CMatrix () virtual default
Member Function Documentation
Get() [1/2]
template<uint8_t Order> std::array< std::array< float, Order >, Order > & CMatrix< Order >::Get ()
Referenced by CMatrix< Order >::CMatrix().
Get() [2/2]
template<uint8_t Order> const std::array< std::array< float, Order >, Order > & CMatrix< Order >::Get () const
Invert() [1/2]
template<uint8_t Order> CMatrix< Order > & CMatrix< Order >::Invert ()
References CMatrix< Order >::m_mat.
Invert() [2/2]
template<uint8_t Order> std::array< std::array< float, Order >, Order > CMatrix< Order >::Invert (std::array< std::array< float, Order >, Order > & other) const protected
operator*() [1/2]
template<uint8_t Order> CMatrix< Order > CMatrix< Order >::operator* (const CMatrix< Order > & other)
References CMatrix< Order >::m_mat.
operator*() [2/2]
template<uint8_t Order> CMatrix< Order > CMatrix< Order >::operator* (const std::array< std::array< float, Order >, Order > & other) virtual
References CMatrix< Order >::m_mat.
operator*=()
template<uint8_t Order> CMatrix< Order > & CMatrix< Order >::operator*= (const CMatrix< Order > & other)
References CMatrix< Order >::m_mat.
operator=()
template<uint8_t Order> CMatrix< Order > & CMatrix< Order >::operator= (const std::array< std::array< float, Order - 1 >, Order - 1 > & other)
operator==()
template<uint8_t Order> bool CMatrix< Order >::operator== (const CMatrix< Order > & other) const inline
References CMatrix< Order >::m_mat.
operator[]() [1/2]
template<uint8_t Order> std::array< float, Order > & CMatrix< Order >::operator[] (int index) inline
References index(), and CMatrix< Order >::m_mat.
operator[]() [2/2]
template<uint8_t Order> const std::array< float, Order > & CMatrix< Order >::operator[] (int index) const inline
References index(), and CMatrix< Order >::m_mat.
ToRaw()
template<uint8_t Order> float * CMatrix< Order >::ToRaw () inline
References CMatrix< Order >::m_mat.
Referenced by Shaders::GL::BaseYUV2RGBGLSLShader::OnEnabled(), Shaders::GLES::BaseYUV2RGBGLSLShader::OnEnabled(), and CYUV2RGBShader::SetShaderParameters().
Member Data Documentation
m_mat
template<uint8_t Order> std::array<std::array<float, Order>, Order> CMatrix< Order >::m_mat {{}} protected
Referenced by CMatrix< Order >::Invert(), CMatrix< Order >::operator*(), CGlMatrix::operator*(), CMatrix< Order >::operator*(), CMatrix< Order >::operator*=(), CMatrix< Order >::operator==(), CMatrix< Order >::operator[](), CMatrix< Order >::operator[](), and CMatrix< Order >::ToRaw().
The documentation for this class was generated from the following files:
ConversionMatrix.h
ConversionMatrix.cpp