Kodi Documentation: CHttpResponse Class Reference
CHttpResponse Class Reference
#include <HttpResponse.h>
Public Member Functions
CHttpResponse (HTTP::Method method, HTTP::StatusCode status, HTTP::Version version=HTTP::Version1_1)
void AddHeader (const std::string &field, const std::string &value)
void SetContent (const char *data, unsigned int length)
std::string Create ()
Static Private Member Functions
static std::map< HTTP::StatusCode, std::string > createStatusCodes ()
Private Attributes
HTTP::Method m_method
HTTP::StatusCode m_status
HTTP::Version m_version
std::vector< std::pair< std::string, std::string > > m_headers
const char * m_content
unsigned int m_contentLength
std::string m_buffer
Static Private Attributes
static std::map< HTTP::StatusCode, std::string > m_statusCodeText = CHttpResponse::createStatusCodes()
Constructor & Destructor Documentation
CHttpResponse()
CHttpResponse::CHttpResponse (HTTP::Method method, HTTP::StatusCode status, HTTP::Version version = HTTP::Version1_1)
References m_content, m_contentLength, m_method, m_status, and m_version.
Member Function Documentation
AddHeader()
void CHttpResponse::AddHeader (const std::string & field, const std::string & value)
References m_headers, and value.
Referenced by CWebSocketManager::Handle(), CWebSocketV13::Handshake(), CWebSocketV8::Handshake(), and TEST().
Create()
std::string CHttpResponse::Create ()
References HEADER_CONTENT_LENGTH, index(), LINEBREAK, m_buffer, m_content, m_contentLength, m_headers, m_status, m_statusCodeText, m_version, SEPARATOR, SPACE, HTTP::Version1_0, and HTTP::Version1_1.
Referenced by CWebSocketManager::Handle(), CWebSocketV13::Handshake(), CWebSocketV8::Handshake(), and TEST().
createStatusCodes()
std::map< HTTP::StatusCode, std::string > CHttpResponse::createStatusCodes () static private
References HTTP::Accepted, HTTP::BadGateway, HTTP::BadRequest, HTTP::BandwidthLimitExceeded, HTTP::Conflict, HTTP::ConnectionTimedOut, HTTP::Continue, HTTP::Created, HTTP::ExpectationFailed, HTTP::FailedDependency, HTTP::Forbidden, HTTP::Found, HTTP::GatewayTimeout, HTTP::Gone, HTTP::HTTPVersionNotSupported, HTTP::ImATeapot, HTTP::InsufficientStorage, HTTP::InternalServerError, HTTP::LengthRequired, HTTP::Locked, HTTP::MethodNotAllowed, HTTP::MovedPermanently, HTTP::MultipleChoices, HTTP::MultiStatus, HTTP::NoContent, HTTP::NonAuthoritativeInformation, HTTP::NotAcceptable, HTTP::NotExtended, HTTP::NotFound, HTTP::NotImplemented, HTTP::NotModified, HTTP::OK, HTTP::PartialContent, HTTP::PaymentRequired, HTTP::PreconditionFailed, HTTP::Processing, HTTP::ProxyAuthenticationRequired, HTTP::RequestedRangeNotSatisfiable, HTTP::RequestEntityTooLarge, HTTP::RequestTimeout, HTTP::RequestURITooLong, HTTP::ResetContent, HTTP::SeeOther, HTTP::ServiceUnavailable, HTTP::SwitchingProtocols, HTTP::TemporaryRedirect, HTTP::TooManyConnections, HTTP::Unauthorized, HTTP::UnorderedCollection, HTTP::UnprocessableEntity, HTTP::UnsupportedMediaType, HTTP::UpgradeRequired, HTTP::UseProxy, and HTTP::VariantAlsoNegotiates.
SetContent()
void CHttpResponse::SetContent (const char * data, unsigned int length)
References data(), m_content, and m_contentLength.
Referenced by TEST().
Member Data Documentation
m_buffer
std::string CHttpResponse::m_buffer private
Referenced by Create().
m_content
const char* CHttpResponse::m_content private
Referenced by CHttpResponse(), Create(), and SetContent().
m_contentLength
unsigned int CHttpResponse::m_contentLength private
Referenced by CHttpResponse(), Create(), and SetContent().
m_headers
std::vector< std::pair<std::string, std::string> > CHttpResponse::m_headers private
Referenced by AddHeader(), and Create().
m_method
HTTP::Method CHttpResponse::m_method private
Referenced by CHttpResponse().
m_status
HTTP::StatusCode CHttpResponse::m_status private
Referenced by CHttpResponse(), and Create().
m_statusCodeText
std::map< HTTP::StatusCode, std::string > CHttpResponse::m_statusCodeText = CHttpResponse::createStatusCodes() static private
Referenced by Create().
m_version
HTTP::Version CHttpResponse::m_version private
Referenced by CHttpResponse(), and Create().
The documentation for this class was generated from the following files:
HttpResponse.h
HttpResponse.cpp