Kodi Documentation: TestURIUtils.cpp File Reference
TestURIUtils.cpp File Reference
#include "ServiceBroker.h"
#include "URL.h"
#include "filesystem/MultiPathDirectory.h"
#include "settings/AdvancedSettings.h"
#include "settings/SettingsComponent.h"
#include "utils/URIUtils.h"
#include <utility>
#include <gtest/gtest.h>
Classes
class TestURIUtils
Functions
TEST_F (TestURIUtils, PathHasParent)
TEST_F (TestURIUtils, GetDirectory)
TEST_F (TestURIUtils, GetExtension)
TEST_F (TestURIUtils, HasExtension)
TEST_F (TestURIUtils, GetFileName)
TEST_F (TestURIUtils, RemoveExtension)
TEST_F (TestURIUtils, ReplaceExtension)
TEST_F (TestURIUtils, Split)
TEST_F (TestURIUtils, SplitPath)
TEST_F (TestURIUtils, SplitPathLocal)
TEST_F (TestURIUtils, GetCommonPath)
TEST_F (TestURIUtils, GetParentPath)
TEST_F (TestURIUtils, SubstitutePath)
TEST_F (TestURIUtils, IsAddonsPath)
TEST_F (TestURIUtils, IsSourcesPath)
TEST_F (TestURIUtils, IsCDDA)
TEST_F (TestURIUtils, IsDOSPath)
TEST_F (TestURIUtils, IsDVD)
TEST_F (TestURIUtils, IsFTP)
TEST_F (TestURIUtils, IsHD)
TEST_F (TestURIUtils, IsInArchive)
TEST_F (TestURIUtils, IsInRAR)
TEST_F (TestURIUtils, IsInternetStream)
TEST_F (TestURIUtils, IsInZIP)
TEST_F (TestURIUtils, IsISO9660)
TEST_F (TestURIUtils, IsLiveTV)
TEST_F (TestURIUtils, IsPVRRadioChannel)
TEST_F (TestURIUtils, IsMultiPath)
TEST_F (TestURIUtils, IsMusicDb)
TEST_F (TestURIUtils, IsNfs)
TEST_F (TestURIUtils, IsOnDVD)
TEST_F (TestURIUtils, IsOnLAN)
TEST_F (TestURIUtils, IsPlugin)
TEST_F (TestURIUtils, IsScript)
TEST_F (TestURIUtils, IsRAR)
TEST_F (TestURIUtils, IsRemote)
TEST_F (TestURIUtils, IsSmb)
TEST_F (TestURIUtils, IsSpecial)
TEST_F (TestURIUtils, IsStack)
TEST_F (TestURIUtils, IsUPnP)
TEST_F (TestURIUtils, IsURL)
TEST_F (TestURIUtils, IsVideoDb)
TEST_F (TestURIUtils, IsZIP)
TEST_F (TestURIUtils, IsBluray)
TEST_F (TestURIUtils, AddSlashAtEnd)
TEST_F (TestURIUtils, HasSlashAtEnd)
TEST_F (TestURIUtils, RemoveSlashAtEnd)
TEST_F (TestURIUtils, CreateArchivePath)
TEST_F (TestURIUtils, AddFileToFolder)
TEST_F (TestURIUtils, HasParentInHostname)
TEST_F (TestURIUtils, HasEncodedHostname)
TEST_F (TestURIUtils, HasEncodedFilename)
TEST_F (TestURIUtils, GetRealPath)
TEST_F (TestURIUtils, UpdateUrlEncoding)
Function Documentation
TEST_F() [1/54]
TEST_F (TestURIUtils , AddFileToFolder)
References URIUtils::AddFileToFolder().
TEST_F() [2/54]
TEST_F (TestURIUtils , AddSlashAtEnd)
References URIUtils::AddSlashAtEnd().
TEST_F() [3/54]
TEST_F (TestURIUtils , CreateArchivePath)
References URIUtils::CreateArchivePath(), and CURL::Get().
TEST_F() [4/54]
TEST_F (TestURIUtils , GetCommonPath)
References URIUtils::GetCommonPath().
TEST_F() [5/54]
TEST_F (TestURIUtils , GetDirectory)
References URIUtils::GetDirectory().
TEST_F() [6/54]
TEST_F (TestURIUtils , GetExtension)
References URIUtils::GetExtension().
TEST_F() [7/54]
TEST_F (TestURIUtils , GetFileName)
References URIUtils::GetFileName().
TEST_F() [8/54]
TEST_F (TestURIUtils , GetParentPath)
References EXPECT_TRUE(), and URIUtils::GetParentPath().
TEST_F() [9/54]
TEST_F (TestURIUtils , GetRealPath)
References URIUtils::GetRealPath().
TEST_F() [10/54]
TEST_F (TestURIUtils , HasEncodedFilename)
References EXPECT_TRUE(), and URIUtils::HasEncodedFilename().
TEST_F() [11/54]
TEST_F (TestURIUtils , HasEncodedHostname)
References EXPECT_TRUE(), and URIUtils::HasEncodedHostname().
TEST_F() [12/54]
TEST_F (TestURIUtils , HasExtension)
References EXPECT_TRUE(), and URIUtils::HasExtension().
TEST_F() [13/54]
TEST_F (TestURIUtils , HasParentInHostname)
References EXPECT_TRUE(), and URIUtils::HasParentInHostname().
TEST_F() [14/54]
TEST_F (TestURIUtils , HasSlashAtEnd)
References EXPECT_TRUE(), and URIUtils::HasSlashAtEnd().
TEST_F() [15/54]
TEST_F (TestURIUtils , IsAddonsPath)
References EXPECT_TRUE(), and URIUtils::IsAddonsPath().
TEST_F() [16/54]
TEST_F (TestURIUtils , IsBluray)
References EXPECT_TRUE(), and URIUtils::IsBluray().
TEST_F() [17/54]
TEST_F (TestURIUtils , IsCDDA)
References EXPECT_TRUE(), and URIUtils::IsCDDA().
TEST_F() [18/54]
TEST_F (TestURIUtils , IsDOSPath)
References EXPECT_TRUE(), and URIUtils::IsDOSPath().
TEST_F() [19/54]
TEST_F (TestURIUtils , IsDVD)
References EXPECT_TRUE(), and URIUtils::IsDVD().
TEST_F() [20/54]
TEST_F (TestURIUtils , IsFTP)
References EXPECT_TRUE(), and URIUtils::IsFTP().
TEST_F() [21/54]
TEST_F (TestURIUtils , IsHD)
References EXPECT_TRUE(), and URIUtils::IsHD().
TEST_F() [22/54]
TEST_F (TestURIUtils , IsInArchive)
References EXPECT_TRUE(), and URIUtils::IsInArchive().
TEST_F() [23/54]
TEST_F (TestURIUtils , IsInRAR)
References EXPECT_TRUE(), and URIUtils::IsInRAR().
TEST_F() [24/54]
TEST_F (TestURIUtils , IsInternetStream)
References EXPECT_TRUE(), and URIUtils::IsInternetStream().
TEST_F() [25/54]
TEST_F (TestURIUtils , IsInZIP)
References EXPECT_TRUE(), and URIUtils::IsInZIP().
TEST_F() [26/54]
TEST_F (TestURIUtils , IsISO9660)
References EXPECT_TRUE(), and URIUtils::IsISO9660().
TEST_F() [27/54]
TEST_F (TestURIUtils , IsLiveTV)
References EXPECT_TRUE(), and URIUtils::IsLiveTV().
TEST_F() [28/54]
TEST_F (TestURIUtils , IsMultiPath)
References EXPECT_TRUE(), and URIUtils::IsMultiPath().
TEST_F() [29/54]
TEST_F (TestURIUtils , IsMusicDb)
References EXPECT_TRUE(), and URIUtils::IsMusicDb().
TEST_F() [30/54]
TEST_F (TestURIUtils , IsNfs)
References EXPECT_TRUE(), and URIUtils::IsNfs().
TEST_F() [31/54]
TEST_F (TestURIUtils , IsOnDVD)
References EXPECT_TRUE(), and URIUtils::IsOnDVD().
TEST_F() [32/54]
TEST_F (TestURIUtils , IsOnLAN)
References XFILE::CMultiPathDirectory::ConstructMultiPath(), EXPECT_TRUE(), and URIUtils::IsOnLAN().
TEST_F() [33/54]
TEST_F (TestURIUtils , IsPlugin)
References EXPECT_TRUE(), and URIUtils::IsPlugin().
TEST_F() [34/54]
TEST_F (TestURIUtils , IsPVRRadioChannel)
References EXPECT_TRUE(), and URIUtils::IsPVRRadioChannel().
TEST_F() [35/54]
TEST_F (TestURIUtils , IsRAR)
References EXPECT_TRUE(), and URIUtils::IsRAR().
TEST_F() [36/54]
TEST_F (TestURIUtils , IsRemote)
References EXPECT_TRUE(), and URIUtils::IsRemote().
TEST_F() [37/54]
TEST_F (TestURIUtils , IsScript)
References EXPECT_TRUE(), and URIUtils::IsScript().
TEST_F() [38/54]
TEST_F (TestURIUtils , IsSmb)
References EXPECT_TRUE(), and URIUtils::IsSmb().
TEST_F() [39/54]
TEST_F (TestURIUtils , IsSourcesPath)
References EXPECT_TRUE(), and URIUtils::IsSourcesPath().
TEST_F() [40/54]
TEST_F (TestURIUtils , IsSpecial)
References EXPECT_TRUE(), and URIUtils::IsSpecial().
TEST_F() [41/54]
TEST_F (TestURIUtils , IsStack)
References EXPECT_TRUE(), and URIUtils::IsStack().
TEST_F() [42/54]
TEST_F (TestURIUtils , IsUPnP)
References EXPECT_TRUE(), and URIUtils::IsUPnP().
TEST_F() [43/54]
TEST_F (TestURIUtils , IsURL)
References EXPECT_TRUE(), and URIUtils::IsURL().
TEST_F() [44/54]
TEST_F (TestURIUtils , IsVideoDb)
References EXPECT_TRUE(), and URIUtils::IsVideoDb().
TEST_F() [45/54]
TEST_F (TestURIUtils , IsZIP)
References EXPECT_TRUE(), and URIUtils::IsZIP().
TEST_F() [46/54]
TEST_F (TestURIUtils , PathHasParent)
References EXPECT_TRUE(), and URIUtils::PathHasParent().
TEST_F() [47/54]
TEST_F (TestURIUtils , RemoveExtension)
References URIUtils::RemoveExtension().
TEST_F() [48/54]
TEST_F (TestURIUtils , RemoveSlashAtEnd)
References URIUtils::RemoveSlashAtEnd().
TEST_F() [49/54]
TEST_F (TestURIUtils , ReplaceExtension)
References URIUtils::ReplaceExtension().
TEST_F() [50/54]
TEST_F (TestURIUtils , Split)
References URIUtils::Split().
TEST_F() [51/54]
TEST_F (TestURIUtils , SplitPath)
References URIUtils::SplitPath().
TEST_F() [52/54]
TEST_F (TestURIUtils , SplitPathLocal)
References URIUtils::SplitPath().
TEST_F() [53/54]
TEST_F (TestURIUtils , SubstitutePath)
References CServiceBroker::GetSettingsComponent(), and URIUtils::SubstitutePath().
TEST_F() [54/54]
TEST_F (TestURIUtils , UpdateUrlEncoding)
References EXPECT_TRUE(), and URIUtils::UpdateUrlEncoding().