Kodi Documentation: CDVDVideoCodecFFmpeg Class Reference
CDVDVideoCodecFFmpeg Class Reference
#include <DVDVideoCodecFFmpeg.h>
Classes
struct CDropControl
Public Member Functions
CDVDVideoCodecFFmpeg (CProcessInfo &processInfo)
~CDVDVideoCodecFFmpeg () override
bool Open (CDVDStreamInfo &hints, CDVDCodecOptions &options) override
bool AddData (const DemuxPacket &packet) override
void Reset () override
void Reopen () override
CDVDVideoCodec::VCReturn GetPicture (VideoPicture *pVideoPicture) override
const char * GetName () override
unsigned GetConvergeCount () override
unsigned GetAllowedReferences () override
bool GetCodecStats (double &pts, int &droppedFrames, int &skippedPics) override
void SetCodecControl (int flags) override
IHardwareDecoder * GetHWAccel () override
bool GetPictureCommon (VideoPicture *pVideoPicture) override
Public Member Functions inherited from CDVDVideoCodec
CDVDVideoCodec (CProcessInfo &processInfo)
virtual ~CDVDVideoCodec ()=default
virtual bool Reconfigure (CDVDStreamInfo &hints)
virtual void SetSpeed (int iSpeed)
Public Member Functions inherited from ICallbackHWAccel
virtual ~ICallbackHWAccel ()=default
Protected Member Functions
void Dispose ()
int FilterOpen (const std::string &filters, bool scale)
void FilterClose ()
CDVDVideoCodec::VCReturn FilterProcess (AVFrame *frame)
void SetFilters ()
void UpdateName ()
bool SetPictureParams (VideoPicture *pVideoPicture)
bool HasHardware ()
void SetHardware (IHardwareDecoder *hardware)
Static Protected Member Functions
static enum AVPixelFormat GetFormat (struct AVCodecContext *avctx, const AVPixelFormat *fmt)
Protected Attributes
AVFrame * m_pFrame = nullptr
AVFrame * m_pDecodedFrame = nullptr
AVCodecContext * m_pCodecContext = nullptr
std::shared_ptr< CVideoBufferPoolFFmpeg > m_videoBufferPool
std::string m_filters
std::string m_filters_next
AVFilterGraph * m_pFilterGraph = nullptr
AVFilterContext * m_pFilterIn = nullptr
AVFilterContext * m_pFilterOut = nullptr
AVFrame * m_pFilterFrame = nullptr
bool m_filterEof = false
bool m_eof = false
CDVDVideoPPFFmpeg m_postProc
int m_iPictureWidth = 0
int m_iPictureHeight = 0
int m_iScreenWidth = 0
int m_iScreenHeight = 0
int m_iOrientation = 0
std::string m_name
int m_decoderState
IHardwareDecoder * m_pHardware = nullptr
int m_iLastKeyframe = 0
double m_dts = DVD_NOPTS_VALUE
bool m_started = false
bool m_startedInput = false
std::vector< AVPixelFormat > m_formats
double m_decoderPts = DVD_NOPTS_VALUE
int m_skippedDeint = 0
int m_droppedFrames = 0
bool m_requestSkipDeint = false
int m_codecControlFlags = 0
bool m_interlaced = false
double m_DAR = 1.0
CDVDStreamInfo m_hints
CDVDCodecOptions m_options
struct CDVDVideoCodecFFmpeg::CDropControl m_dropCtrl
Protected Attributes inherited from CDVDVideoCodec
CProcessInfo & m_processInfo
Additional Inherited Members
Public Types inherited from CDVDVideoCodec
enum VCReturn {
VC_NONE = 0 , VC_ERROR , VC_FATAL , VC_BUFFER ,
VC_PICTURE , VC_FLUSHED , VC_NOBUFFER , VC_REOPEN ,
VC_EOF
}
Constructor & Destructor Documentation
CDVDVideoCodecFFmpeg()
CDVDVideoCodecFFmpeg::CDVDVideoCodecFFmpeg (CProcessInfo & processInfo) explicit
References m_decoderState, and STATE_NONE.
~CDVDVideoCodecFFmpeg()
CDVDVideoCodecFFmpeg::~CDVDVideoCodecFFmpeg () override
References Dispose().
Member Function Documentation
AddData()
bool CDVDVideoCodecFFmpeg::AddData (const DemuxPacket & packet) override virtual
add data, decoder has to consume the entire packet returns true if the packet was consumed or if resubmitting it is useless
Todo:
: properly handle avpkt side_data. this works around our improper use of the side_data
Implements CDVDVideoCodec.
References IHardwareDecoder::Check(), DEMUX_PACKET::dts, DVD_NOPTS_VALUE, DVD_TIME_BASE, int64_t(), DEMUX_PACKET::iSideDataElems, DEMUX_PACKET::iSize, CLog::Log(), LOGERROR, m_dts, m_eof, m_iLastKeyframe, m_pCodecContext, m_pHardware, m_started, m_startedInput, DEMUX_PACKET::pData, DEMUX_PACKET::pSideData, DEMUX_PACKET::pts, pts_dtoi(), DEMUX_PACKET::recoveryPoint, Reset(), and CDVDVideoCodec::VC_NOBUFFER.
Dispose()
void CDVDVideoCodecFFmpeg::Dispose () protected
References FilterClose(), m_pCodecContext, m_pDecodedFrame, m_pFilterFrame, m_pFrame, m_pHardware, and IDVDResourceCounted< T >::Release().
Referenced by Reopen(), and ~CDVDVideoCodecFFmpeg().
FilterClose()
void CDVDVideoCodecFFmpeg::FilterClose () protected
References CLog::Log(), LOGDEBUG, LOGVIDEO, m_pFilterGraph, m_pFilterIn, and m_pFilterOut.
Referenced by Dispose(), FilterOpen(), GetPicture(), and Reset().
FilterOpen()
int CDVDVideoCodecFFmpeg::FilterOpen (const std::string & filters, bool scale) protected
References FilterClose(), CServiceBroker::GetLogging(), CLog::Log(), LOGDEBUG, LOGERROR, LOGVIDEO, LOGWARNING, m_filterEof, m_filters, m_formats, m_pCodecContext, m_pFilterGraph, m_pFilterIn, m_pFilterOut, m_pHardware, CDVDVideoCodec::m_processInfo, and CProcessInfo::SetVideoDeintMethod().
Referenced by GetPicture().
FilterProcess()
CDVDVideoCodec::VCReturn CDVDVideoCodecFFmpeg::FilterProcess (AVFrame * frame) protected
References DVD_CODEC_CTRL_DRAIN, CLog::Log(), LOGERROR, m_codecControlFlags, m_filterEof, m_pFilterFrame, m_pFilterIn, m_pFilterOut, m_pFrame, CDVDVideoCodec::VC_BUFFER, CDVDVideoCodec::VC_ERROR, and CDVDVideoCodec::VC_PICTURE.
Referenced by GetPicture().
GetAllowedReferences()
unsigned CDVDVideoCodecFFmpeg::GetAllowedReferences () override virtual
Number of references to old pictures that are allowed to be retained when calling decode on the next demux packet
Reimplemented from CDVDVideoCodec.
References IHardwareDecoder::GetAllowedReferences(), and m_pHardware.
GetCodecStats()
bool CDVDVideoCodecFFmpeg::GetCodecStats (double & pts, int & droppedFrames, int & skippedPics) override virtual
For calculation of dropping requirements player asks for some information.
pts : right after decoder, used to detect gaps (dropped frames in decoder)
droppedFrames : indicates if decoder has dropped a frame -1 means that decoder has no info on this.
skippedPics : indicates if postproc has skipped a already decoded picture -1 means that decoder has no info on this.
If codec does not implement this method, pts of decoded frame at input video player is used. In case decoder does post-proc and de-interlacing there may be quite some frames queued up between exit decoder and entry player.
Reimplemented from CDVDVideoCodec.
References DVD_NOPTS_VALUE, m_decoderPts, m_droppedFrames, m_dts, and m_skippedDeint.
GetConvergeCount()
unsigned CDVDVideoCodecFFmpeg::GetConvergeCount () override virtual
How many packets should player remember, so codec can recover should something cause it to flush outside of players control
Reimplemented from CDVDVideoCodec.
References m_iLastKeyframe.
GetFormat()
enum AVPixelFormat CDVDVideoCodecFFmpeg::GetFormat (struct AVCodecContext * avctx, const AVPixelFormat * fmt) static protected
References CDVDFactoryCodec::CreateVideoCodecHWAccel(), CDVDFactoryCodec::GetHWAccels(), HasHardware(), m_decoderState, m_hints, m_pCodecContext, CDVDVideoCodec::m_processInfo, IHardwareDecoder::Open(), IDVDResourceCounted< T >::Release(), SetHardware(), CProcessInfo::SetSwDeinterlacingMethods(), CProcessInfo::SetVideoDimensions(), CProcessInfo::SetVideoPixelFormat(), STATE_HW_FAILED, and STATE_HW_SINGLE.
Referenced by Open().
GetHWAccel()
IHardwareDecoder * CDVDVideoCodecFFmpeg::GetHWAccel () override virtual
Implements ICallbackHWAccel.
References m_pHardware.
GetName()
const char * CDVDVideoCodecFFmpeg::GetName () inline override virtual
should return codecs name
Implements CDVDVideoCodec.
References m_name.
GetPicture()
CDVDVideoCodec::VCReturn CDVDVideoCodecFFmpeg::GetPicture (VideoPicture * pVideoPicture) override virtual
GetPicture controls decoding. Player calls it on every cycle it can signal a picture, request a buffer, or return none, if nothing applies the data is valid until the next GetPicture return VC_PICTURE
Implements CDVDVideoCodec.
References IHardwareDecoder::Decode(), DVD_CODEC_CTRL_DRAIN, FilterClose(), FilterOpen(), FilterProcess(), IHardwareDecoder::GetPicture(), CProcessInfo::GetVideoInterlaced(), int64_t(), CLog::Log(), LOGDEBUG, LOGERROR, m_codecControlFlags, m_decoderState, CDVDVideoCodecFFmpeg::CDropControl::m_diffPTS, m_dropCtrl, m_droppedFrames, m_eof, m_filterEof, m_filters, m_filters_next, m_formats, m_iLastKeyframe, m_interlaced, CDVDVideoCodecFFmpeg::CDropControl::m_lastPTS, m_pCodecContext, m_pDecodedFrame, m_pFilterGraph, m_pFilterIn, m_pFrame, m_pHardware, CDVDVideoCodec::m_processInfo, m_started, m_startedInput, CDVDVideoCodecFFmpeg::CDropControl::m_state, CDVDVideoCodecFFmpeg::CDropControl::Process(), Reset(), IHardwareDecoder::SetCodecControl(), SetFilters(), SetPictureParams(), CProcessInfo::SetVideoInterlaced(), STATE_HW_FAILED, CDVDVideoCodecFFmpeg::CDropControl::VALID, CDVDVideoCodec::VC_BUFFER, CDVDVideoCodec::VC_EOF, CDVDVideoCodec::VC_ERROR, CDVDVideoCodec::VC_FATAL, CDVDVideoCodec::VC_FLUSHED, CDVDVideoCodec::VC_NONE, CDVDVideoCodec::VC_PICTURE, and CDVDVideoCodec::VC_REOPEN.
GetPictureCommon()
bool CDVDVideoCodecFFmpeg::GetPictureCommon (VideoPicture * pVideoPicture) override virtual
Todo:
: ffmpeg doesn't seem like they know how they want to handle this.
Implements ICallbackHWAccel.
References VideoPicture::chroma_position, VideoPicture::color_primaries, VideoPicture::color_range, VideoPicture::color_space, VideoPicture::color_transfer, VideoPicture::colorBits, CDVDStreamInfo::colorPrimaries, CDVDStreamInfo::colorRange, CDVDStreamInfo::colorSpace, CDVDStreamInfo::colorTransferCharacteristic, CDVDStreamInfo::contentLightMetadata, VideoPicture::displayMetadata, VideoPicture::dts, DVD_CODEC_CTRL_DROP, DVD_CODEC_CTRL_SKIPDEINT, DVD_NOPTS_VALUE, DVD_TIME_BASE, DVP_FLAG_DROPPED, DVP_FLAG_INTERLACED, DVP_FLAG_TOP_FIELD_FIRST, VideoPicture::hasDisplayMetadata, VideoPicture::hasLightMetadata, VideoPicture::hdrType, CDVDStreamInfo::hdrType, VideoPicture::iDisplayHeight, VideoPicture::iDisplayWidth, VideoPicture::iFlags, VideoPicture::iHeight, int64_t(), VideoPicture::iRepeatPicture, VideoPicture::iWidth, VideoPicture::lightMetadata, m_codecControlFlags, m_DAR, m_decoderPts, m_dts, m_hints, VideoPicture::m_originalColorPrimaries, m_pCodecContext, m_pFrame, CDVDVideoCodec::m_processInfo, m_requestSkipDeint, m_skippedDeint, CDVDStreamInfo::masteringMetadata, VideoPicture::pict_type, VideoPicture::pixelFormat, VideoPicture::pts, VideoPicture::qp_table, VideoPicture::qscale_type, VideoPicture::qstride, RINT, CProcessInfo::SetVideoDAR(), and VideoPicture::stereoMode.
Referenced by SetPictureParams().
HasHardware()
bool CDVDVideoCodecFFmpeg::HasHardware () inline protected
References m_pHardware.
Referenced by GetFormat().
Open()
bool CDVDVideoCodecFFmpeg::Open (CDVDStreamInfo & hints, CDVDCodecOptions & options) override virtual
Open the decoder, returns true on success Decoders not capable of running multiple instances should return false in case there is already a instance open
Todo:
allow per video setting?
Implements CDVDVideoCodec.
References CDVDStreamInfo::bitdepth, CDVDStreamInfo::bitsperpixel, CDVDStreamInfo::codec, CODEC_FORCE_SOFTWARE, CDVDStreamInfo::codec_tag, CDVDStreamInfo::codecOptions, CDVDStreamInfo::cryptoSession, CDVDStreamInfo::extradata, CServiceBroker::GetCPUInfo(), FFmpegExtraData::GetData(), GetFormat(), CProcessInfo::GetPixFormats(), CServiceBroker::GetSettingsComponent(), FFmpegExtraData::GetSize(), CDVDStreamInfo::height, CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_decoderState, m_dropCtrl, m_eof, m_formats, m_hints, m_iOrientation, m_options, m_pCodecContext, m_pDecodedFrame, m_pFilterFrame, m_pFrame, CDVDVideoCodec::m_processInfo, CDVDStreamInfo::orientation, CDVDVideoCodecFFmpeg::CDropControl::Reset(), CProcessInfo::SetSwDeinterlacingMethods(), CProcessInfo::SetVideoDimensions(), CProcessInfo::SetVideoInterlaced(), CProcessInfo::SetVideoPixelFormat(), STATE_HW_FAILED, STATE_HW_SINGLE, STATE_NONE, STATE_SW_MULTI, STATE_SW_SINGLE, UpdateName(), and CDVDStreamInfo::width.
Referenced by Reopen().
Reopen()
void CDVDVideoCodecFFmpeg::Reopen () override virtual
Re-open the decoder. Decoder request to re-open
Reimplemented from CDVDVideoCodec.
References Dispose(), m_hints, m_options, and Open().
Reset()
void CDVDVideoCodecFFmpeg::Reset () override virtual
Reset the decoder. Should be the same as calling Dispose and Open after each other
Implements CDVDVideoCodec.
References DVD_NOPTS_VALUE, FilterClose(), m_decoderPts, m_dropCtrl, m_droppedFrames, m_eof, m_filters, m_iLastKeyframe, m_interlaced, m_pCodecContext, m_pFrame, m_pHardware, m_skippedDeint, m_started, m_startedInput, IHardwareDecoder::Reset(), and CDVDVideoCodecFFmpeg::CDropControl::Reset().
Referenced by AddData(), CDVDVideoCodecFFmpeg::CDropControl::CDropControl(), GetPicture(), and CDVDVideoCodecFFmpeg::CDropControl::Process().
SetCodecControl()
void CDVDVideoCodecFFmpeg::SetCodecControl (int flags) override virtual
Codec can be informed by player with the following flags:
DVD_CODEC_CTRL_NO_POSTPROC : if speed is not normal the codec can switch off postprocessing and de-interlacing
DVD_CODEC_CTRL_HURRY : codecs may do postprocessing and de-interlacing. If video buffers in RenderManager are about to run dry, this is signaled to codec. Codec can wait for post-proc to be finished instead of returning empty and getting another packet.
DVD_CODEC_CTRL_DRAIN : instruct decoder to deliver last pictures without requesting new packets
DVD_CODEC_CTRL_DROP : this packet is going to be dropped. decoder is free to use it for decoding
Reimplemented from CDVDVideoCodec.
References IHardwareDecoder::CanSkipDeint(), DVD_CODEC_CTRL_DROP_ANY, m_codecControlFlags, m_pCodecContext, m_pHardware, m_requestSkipDeint, and IHardwareDecoder::SetCodecControl().
SetFilters()
void CDVDVideoCodecFFmpeg::SetFilters () protected
References DVD_CODEC_CTRL_ROTATE, FILTER_DEINTERLACE_ANY, FILTER_DEINTERLACE_BWDIF, FILTER_DEINTERLACE_FLAGGED, FILTER_DEINTERLACE_HALFED, FILTER_ROTATE, CProcessInfo::GetFallbackDeintMethod(), CProcessInfo::GetVideoSettings(), m_codecControlFlags, m_filters_next, m_interlaced, CVideoSettings::m_InterlaceMethod, m_iOrientation, CDVDVideoCodec::m_processInfo, CProcessInfo::Supports(), VS_INTERLACEMETHOD_DEINTERLACE, VS_INTERLACEMETHOD_DEINTERLACE_HALF, and VS_INTERLACEMETHOD_NONE.
Referenced by GetPicture().
SetHardware()
void CDVDVideoCodecFFmpeg::SetHardware (IHardwareDecoder * hardware) protected
References m_pHardware, IDVDResourceCounted< T >::Release(), and UpdateName().
Referenced by GetFormat().
SetPictureParams()
bool CDVDVideoCodecFFmpeg::SetPictureParams (VideoPicture * pVideoPicture) protected
References DVP_FLAG_DROPPED, GetPictureCommon(), CServiceBroker::GetSettingsComponent(), CProcessInfo::GetVideoSettings(), VideoPicture::iFlags, m_pFrame, m_postProc, CVideoSettings::m_PostProcess, CDVDVideoCodec::m_processInfo, m_videoBufferPool, CDVDVideoPPFFmpeg::Process(), CVideoBuffer::Release(), CVideoBufferFFmpeg::SetRef(), CDVDVideoPPFFmpeg::SetType(), and VideoPicture::videoBuffer.
Referenced by GetPicture().
UpdateName()
void CDVDVideoCodecFFmpeg::UpdateName () protected
References CLog::Log(), LOGDEBUG, m_name, m_pCodecContext, m_pHardware, CDVDVideoCodec::m_processInfo, IHardwareDecoder::Name(), and CProcessInfo::SetVideoDecoderName().
Referenced by Open(), and SetHardware().
Member Data Documentation
m_codecControlFlags
int CDVDVideoCodecFFmpeg::m_codecControlFlags = 0 protected
Referenced by FilterProcess(), GetPicture(), GetPictureCommon(), SetCodecControl(), and SetFilters().
m_DAR
double CDVDVideoCodecFFmpeg::m_DAR = 1.0 protected
Referenced by GetPictureCommon().
m_decoderPts
double CDVDVideoCodecFFmpeg::m_decoderPts = DVD_NOPTS_VALUE protected
Referenced by GetCodecStats(), GetPictureCommon(), and Reset().
m_decoderState
int CDVDVideoCodecFFmpeg::m_decoderState protected
Referenced by CDVDVideoCodecFFmpeg(), GetFormat(), GetPicture(), and Open().
m_dropCtrl
struct CDVDVideoCodecFFmpeg::CDropControl CDVDVideoCodecFFmpeg::m_dropCtrl protected
Referenced by GetPicture(), Open(), and Reset().
m_droppedFrames
int CDVDVideoCodecFFmpeg::m_droppedFrames = 0 protected
Referenced by GetCodecStats(), GetPicture(), and Reset().
m_dts
double CDVDVideoCodecFFmpeg::m_dts = DVD_NOPTS_VALUE protected
Referenced by AddData(), GetCodecStats(), and GetPictureCommon().
m_eof
bool CDVDVideoCodecFFmpeg::m_eof = false protected
Referenced by AddData(), GetPicture(), Open(), and Reset().
m_filterEof
bool CDVDVideoCodecFFmpeg::m_filterEof = false protected
Referenced by FilterOpen(), FilterProcess(), and GetPicture().
m_filters
std::string CDVDVideoCodecFFmpeg::m_filters protected
Referenced by FilterOpen(), GetPicture(), and Reset().
m_filters_next
std::string CDVDVideoCodecFFmpeg::m_filters_next protected
Referenced by GetPicture(), and SetFilters().
m_formats
std::vector<AVPixelFormat> CDVDVideoCodecFFmpeg::m_formats protected
Referenced by FilterOpen(), GetPicture(), and Open().
m_hints
CDVDStreamInfo CDVDVideoCodecFFmpeg::m_hints protected
Referenced by GetFormat(), GetPictureCommon(), Open(), and Reopen().
m_iLastKeyframe
int CDVDVideoCodecFFmpeg::m_iLastKeyframe = 0 protected
Referenced by AddData(), GetConvergeCount(), GetPicture(), and Reset().
m_interlaced
bool CDVDVideoCodecFFmpeg::m_interlaced = false protected
Referenced by GetPicture(), Reset(), and SetFilters().
m_iOrientation
int CDVDVideoCodecFFmpeg::m_iOrientation = 0 protected
Referenced by Open(), and SetFilters().
m_iPictureHeight
int CDVDVideoCodecFFmpeg::m_iPictureHeight = 0 protected
m_iPictureWidth
int CDVDVideoCodecFFmpeg::m_iPictureWidth = 0 protected
m_iScreenHeight
int CDVDVideoCodecFFmpeg::m_iScreenHeight = 0 protected
m_iScreenWidth
int CDVDVideoCodecFFmpeg::m_iScreenWidth = 0 protected
m_name
std::string CDVDVideoCodecFFmpeg::m_name protected
Referenced by GetName(), and UpdateName().
m_options
CDVDCodecOptions CDVDVideoCodecFFmpeg::m_options protected
Referenced by Open(), and Reopen().
m_pCodecContext
AVCodecContext* CDVDVideoCodecFFmpeg::m_pCodecContext = nullptr protected
Referenced by AddData(), Dispose(), FilterOpen(), GetFormat(), GetPicture(), GetPictureCommon(), Open(), Reset(), SetCodecControl(), and UpdateName().
m_pDecodedFrame
AVFrame* CDVDVideoCodecFFmpeg::m_pDecodedFrame = nullptr protected
Referenced by Dispose(), GetPicture(), and Open().
m_pFilterFrame
AVFrame* CDVDVideoCodecFFmpeg::m_pFilterFrame = nullptr protected
Referenced by Dispose(), FilterProcess(), and Open().
m_pFilterGraph
AVFilterGraph* CDVDVideoCodecFFmpeg::m_pFilterGraph = nullptr protected
Referenced by FilterClose(), FilterOpen(), and GetPicture().
m_pFilterIn
AVFilterContext* CDVDVideoCodecFFmpeg::m_pFilterIn = nullptr protected
Referenced by FilterClose(), FilterOpen(), FilterProcess(), and GetPicture().
m_pFilterOut
AVFilterContext* CDVDVideoCodecFFmpeg::m_pFilterOut = nullptr protected
Referenced by FilterClose(), FilterOpen(), and FilterProcess().
m_pFrame
AVFrame* CDVDVideoCodecFFmpeg::m_pFrame = nullptr protected
Referenced by Dispose(), FilterProcess(), GetPicture(), GetPictureCommon(), Open(), Reset(), and SetPictureParams().
m_pHardware
IHardwareDecoder* CDVDVideoCodecFFmpeg::m_pHardware = nullptr protected
Referenced by AddData(), Dispose(), FilterOpen(), GetAllowedReferences(), GetHWAccel(), GetPicture(), HasHardware(), Reset(), SetCodecControl(), SetHardware(), and UpdateName().
m_postProc
CDVDVideoPPFFmpeg CDVDVideoCodecFFmpeg::m_postProc protected
Referenced by SetPictureParams().
m_requestSkipDeint
bool CDVDVideoCodecFFmpeg::m_requestSkipDeint = false protected
Referenced by GetPictureCommon(), and SetCodecControl().
m_skippedDeint
int CDVDVideoCodecFFmpeg::m_skippedDeint = 0 protected
Referenced by GetCodecStats(), GetPictureCommon(), and Reset().
m_started
bool CDVDVideoCodecFFmpeg::m_started = false protected
Referenced by AddData(), GetPicture(), and Reset().
m_startedInput
bool CDVDVideoCodecFFmpeg::m_startedInput = false protected
Referenced by AddData(), GetPicture(), and Reset().
m_videoBufferPool
std::shared_ptr<CVideoBufferPoolFFmpeg> CDVDVideoCodecFFmpeg::m_videoBufferPool protected
Referenced by SetPictureParams().
The documentation for this class was generated from the following files:
DVDVideoCodecFFmpeg.h
DVDVideoCodecFFmpeg.cpp