Kodi Documentation: CDirectoryProvider Class Reference
CDirectoryProvider Class Reference
#include <DirectoryProvider.h>
Public Types
enum UpdateState { OK , INVALIDATED , DONE }
enum class BrowseMode { NEVER , AUTO , ALWAYS }
Public Member Functions
CDirectoryProvider (const TiXmlElement *element, int parentID)
CDirectoryProvider (const CDirectoryProvider &other)
~CDirectoryProvider () override
std::unique_ptr< IListProvider > Clone () override
Create an instance of the derived class. Allows for polymorphic copies.
bool Update (bool forceRefresh) override
Update the list content.
void Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data) override
void Fetch (std::vector< std::shared_ptr< CGUIListItem > > &items) override
Fetch the current list of items.
void Reset () override
Reset the current list of items. Derived classes may choose to ignore this.
bool OnClick (const std::shared_ptr< CGUIListItem > &item) override
Click event on an item.
bool OnPlay (const std::shared_ptr< CGUIListItem > &item) override
Play event on an item.
bool OnInfo (const std::shared_ptr< CFileItem > &item)
bool OnContextMenu (const std::shared_ptr< CFileItem > &item)
bool OnInfo (const std::shared_ptr< CGUIListItem > &item) override
Open the info dialog for an item provided by this IListProvider.
bool OnContextMenu (const std::shared_ptr< CGUIListItem > &item) override
Open the context menu for an item provided by this IListProvider.
bool IsUpdating () const override
Check whether the list provider is updating content.
void FreeResources (bool immediately) override
Free all GUI resources allocated by the items.
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
Public Member Functions inherited from IListProvider
IListProvider (int parentID)
IListProvider (const IListProvider &other)=default
virtual ~IListProvider ()=default
virtual void SetDefaultItem (int item, bool always)
Set the default item to focus. For backwards compatibility.
virtual int GetDefaultItem () const
The default item to focus.
virtual bool AlwaysFocusDefaultItem () const
Whether to always focus the default item.
Public Member Functions inherited from IJobCallback
virtual ~IJobCallback ()=default
Destructor for job call back objects.
virtual void OnJobAbort (unsigned int jobID, CJob *job)
An optional callback function used when a job will be aborted.
virtual void OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob *job)
An optional callback function that a job may call while processing.
Public Member Functions inherited from ANNOUNCEMENT::IAnnouncer
IAnnouncer ()=default
virtual ~IAnnouncer ()=default
Private Member Functions
bool UpdateURL ()
bool UpdateLimit ()
bool UpdateSort ()
bool UpdateBrowse ()
void OnAddonEvent (const ADDON::AddonEvent &event)
void OnAddonRepositoryEvent (const ADDON::CRepositoryUpdater::RepositoryUpdated &event)
void OnPVRManagerEvent (const PVR::PVREvent &event)
void OnFavouritesEvent (const CFavouritesService::FavouritesUpdated &event)
std::string GetTarget (const CFileItem &item) const
Private Attributes
UpdateState m_updateState = OK
unsigned int m_jobID = 0
KODI::GUILIB::GUIINFO::CGUIInfoLabel m_url
KODI::GUILIB::GUIINFO::CGUIInfoLabel m_target
KODI::GUILIB::GUIINFO::CGUIInfoLabel m_sortMethod
KODI::GUILIB::GUIINFO::CGUIInfoLabel m_sortOrder
KODI::GUILIB::GUIINFO::CGUIInfoLabel m_limit
KODI::GUILIB::GUIINFO::CGUIInfoLabel m_browse
std::string m_currentUrl
std::string m_currentTarget
node.target property on the list as a whole
SortDescription m_currentSort
unsigned int m_currentLimit {0}
BrowseMode m_currentBrowse {BrowseMode::AUTO}
std::vector< CGUIStaticItemPtr > m_items
std::vector< InfoTagType > m_itemTypes
CCriticalSection m_section
CCriticalSection m_subscriptionSection
bool m_isSubscribed {false}
Additional Inherited Members
Static Public Member Functions inherited from IListProvider
static std::unique_ptr< IListProvider > Create (const TiXmlNode *parent, int parentID)
Factory to create list providers.
static std::unique_ptr< IListProvider > CreateSingle (const TiXmlNode *content, int parentID)
Factory to create list providers. Cannot create a multi-provider.
Protected Attributes inherited from IListProvider
int m_parentID
Member Enumeration Documentation
BrowseMode
enum class CDirectoryProvider::BrowseMode strong
Enumerator
NEVER
AUTO
ALWAYS
UpdateState
enum CDirectoryProvider::UpdateState
Enumerator
OK
INVALIDATED
DONE
Constructor & Destructor Documentation
CDirectoryProvider() [1/2]
CDirectoryProvider::CDirectoryProvider (const TiXmlElement * element, int parentID)
References m_browse, m_limit, m_sortMethod, m_sortOrder, m_target, m_url, and KODI::GUILIB::GUIINFO::CGUIInfoLabel::SetLabel().
CDirectoryProvider() [2/2]
CDirectoryProvider::CDirectoryProvider (const CDirectoryProvider & other) explicit
~CDirectoryProvider()
CDirectoryProvider::~CDirectoryProvider () override
References Reset().
Member Function Documentation
Announce()
void CDirectoryProvider::Announce (ANNOUNCEMENT::AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data) override virtual
Implements ANNOUNCEMENT::IAnnouncer.
References AUDIO, ANNOUNCEMENT::AudioLibrary, data(), INVALIDATED, m_currentSort, m_itemTypes, m_section, m_updateState, ANNOUNCEMENT::Player, SortDescription::sortBy, SortByDateAdded, SortByLastPlayed, SortByLastUsed, SortByNone, SortByPlaycount, VIDEO, and ANNOUNCEMENT::VideoLibrary.
Clone()
std::unique_ptr< IListProvider > CDirectoryProvider::Clone () override virtual
Create an instance of the derived class. Allows for polymorphic copies.
Implements IListProvider.
Fetch()
void CDirectoryProvider::Fetch (std::vector< std::shared_ptr< CGUIListItem > > & items) override virtual
Fetch the current list of items.
Parameters
items [out] the list to be filled.
Implements IListProvider.
References m_items, and m_section.
FreeResources()
void CDirectoryProvider::FreeResources (bool immediately) override virtual
Free all GUI resources allocated by the items.
Parameters
immediately true to free resources immediately, free resources async later otherwise.
Reimplemented from IListProvider.
References m_items, and m_section.
GetTarget()
std::string CDirectoryProvider::GetTarget (const CFileItem & item) const private
References CVariant::asString(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), CGUIListItem::GetProperty(), m_currentTarget, IListProvider::m_parentID, m_section, and m_target.
Referenced by OnClick(), OnContextMenu(), OnJobComplete(), and OnPlay().
IsUpdating()
bool CDirectoryProvider::IsUpdating () const override virtual
Check whether the list provider is updating content.
Returns
true if in the processing of updating, false otherwise.
Reimplemented from IListProvider.
References DONE, INVALIDATED, m_jobID, m_section, and m_updateState.
OnAddonEvent()
void CDirectoryProvider::OnAddonEvent (const ADDON::AddonEvent & event) private
References INVALIDATED, URIUtils::IsProtocol(), m_currentUrl, m_section, and m_updateState.
Referenced by UpdateURL().
OnAddonRepositoryEvent()
void CDirectoryProvider::OnAddonRepositoryEvent (const ADDON::CRepositoryUpdater::RepositoryUpdated & event) private
References INVALIDATED, URIUtils::IsProtocol(), m_currentUrl, m_section, and m_updateState.
Referenced by UpdateURL().
OnClick()
bool CDirectoryProvider::OnClick (const std::shared_ptr< CGUIListItem > & item) override virtual
Click event on an item.
Parameters
item the item that was clicked.
Returns
true if the click was handled, false otherwise.
Implements IListProvider.
References CServiceBroker::GetFavouritesService(), CExecString::GetFunction(), GetTarget(), CFavouritesService::ResolveFavourite(), and CFileItem::SetPath().
OnContextMenu() [1/2]
bool CDirectoryProvider::OnContextMenu (const std::shared_ptr< CFileItem > & item)
References GetTarget(), CContextMenuManager::MAIN, and CONTEXTMENU::ShowFor().
Referenced by OnContextMenu().
OnContextMenu() [2/2]
bool CDirectoryProvider::OnContextMenu (const std::shared_ptr< CGUIListItem > & item) override virtual
Open the context menu for an item provided by this IListProvider.
Parameters
item the item that was clicked.
Returns
true if the click was handled, false otherwise.
Implements IListProvider.
References OnContextMenu().
OnFavouritesEvent()
void CDirectoryProvider::OnFavouritesEvent (const CFavouritesService::FavouritesUpdated & event) private
References INVALIDATED, URIUtils::IsProtocol(), m_currentUrl, m_section, and m_updateState.
Referenced by UpdateURL().
OnInfo() [1/2]
bool CDirectoryProvider::OnInfo (const std::shared_ptr< CFileItem > & item)
References CServiceBroker::GetFavouritesService(), CFavouritesService::ResolveFavourite(), and KODI::UTILS::GUILIB::CGUIContentUtils::ShowInfoForItem().
Referenced by OnInfo().
OnInfo() [2/2]
bool CDirectoryProvider::OnInfo (const std::shared_ptr< CGUIListItem > & item) override virtual
Open the info dialog for an item provided by this IListProvider.
Parameters
item the item that was clicked.
Returns
true if the dialog was shown, false otherwise.
Implements IListProvider.
References OnInfo().
OnJobComplete()
void CDirectoryProvider::OnJobComplete (unsigned int jobID, bool success, CJob * job) override virtual
The callback used when a job completes.
OnJobComplete is called at the completion of the job's DoWork() function, and is used to return information to the caller on the result of the job. On returning form this function the CJobManager will destroy this job.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
success the result from the DoWork call
job the job that has been processed. The job will be destroyed after this function returns
See also
CJobManager and CJob
Implements IJobCallback.
References DONE, GetTarget(), m_currentTarget, m_items, m_itemTypes, m_jobID, m_section, m_updateState, OK, and success.
OnPlay()
bool CDirectoryProvider::OnPlay (const std::shared_ptr< CGUIListItem > & item) override virtual
Play event on an item.
Parameters
item the item to play.
Returns
true if the event was handled, false otherwise.
Reimplemented from IListProvider.
References CServiceBroker::GetFavouritesService(), GetTarget(), CPlayerUtils::IsItemPlayable(), KODI::VIDEO::UTILS::IsItemPlayable(), and CFavouritesService::ResolveFavourite().
OnPVRManagerEvent()
void CDirectoryProvider::OnPVRManagerEvent (const PVR::PVREvent & event) private
References PVR::ChannelGroupsInvalidated, PVR::ClientsInvalidated, PVR::ClientsPrioritiesInvalidated, INVALIDATED, URIUtils::IsProtocol(), m_currentUrl, m_section, m_updateState, PVR::ManagerError, PVR::ManagerInterrupted, PVR::ManagerStarted, PVR::ManagerStopped, PVR::RecordingsInvalidated, PVR::SavedSearchesInvalidated, and PVR::TimersInvalidated.
Referenced by UpdateURL().
Reset()
void CDirectoryProvider::Reset () override virtual
Reset the current list of items. Derived classes may choose to ignore this.
Reimplemented from IListProvider.
References AUTO, ADDON::CAddonMgr::Events(), ADDON::CRepositoryUpdater::Events(), CFavouritesService::Events(), PVR::CPVRManager::Events(), CServiceBroker::GetAddonMgr(), CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetFavouritesService(), CServiceBroker::GetJobManager(), CServiceBroker::GetPVRManager(), CServiceBroker::GetRepositoryUpdater(), m_currentBrowse, m_currentLimit, m_currentSort, m_currentTarget, m_currentUrl, m_isSubscribed, m_items, m_itemTypes, m_jobID, m_section, m_subscriptionSection, m_updateState, OK, SortDescription::sortBy, SortByNone, SortDescription::sortOrder, SortOrderAscending, and CEventStream< Event >::Unsubscribe().
Referenced by ~CDirectoryProvider().
Update()
bool CDirectoryProvider::Update (bool forceRefresh) override virtual
Update the list content.
Returns
true if the content has changed, false otherwise.
Todo:
Also returned changed if properties are changed (if so, need to update scroll to letter).
Implements IListProvider.
References DONE, CServiceBroker::GetJobManager(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), INVALIDATED, CLog::Log(), LOGDEBUG, m_currentBrowse, m_currentLimit, m_currentSort, m_currentUrl, m_items, m_jobID, IListProvider::m_parentID, m_section, m_target, m_updateState, OK, UpdateBrowse(), UpdateLimit(), UpdateSort(), and UpdateURL().
UpdateBrowse()
bool CDirectoryProvider::UpdateBrowse () private
References ALWAYS, AUTO, KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), m_browse, m_currentBrowse, IListProvider::m_parentID, m_section, NEVER, and value.
Referenced by Update().
UpdateLimit()
bool CDirectoryProvider::UpdateLimit () private
References KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetIntValue(), m_currentLimit, m_limit, IListProvider::m_parentID, m_section, and value.
Referenced by Update().
UpdateSort()
bool CDirectoryProvider::UpdateSort () private
References KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), CServiceBroker::GetSettingsComponent(), m_currentSort, IListProvider::m_parentID, m_section, m_sortMethod, m_sortOrder, CSettings::SETTING_FILELISTS_IGNORETHEWHENSORTING, SortAttributeIgnoreArticle, SortAttributeIgnoreFolders, SortDescription::sortAttributes, SortDescription::sortBy, SortUtils::SortMethodFromString(), SortDescription::sortOrder, SortOrderAscending, SortUtils::SortOrderFromString(), and SortOrderNone.
Referenced by Update().
UpdateURL()
bool CDirectoryProvider::UpdateURL () private
References ANNOUNCEMENT::AudioLibrary, ADDON::CAddonMgr::Events(), ADDON::CRepositoryUpdater::Events(), CFavouritesService::Events(), PVR::CPVRManager::Events(), CServiceBroker::GetAddonMgr(), CServiceBroker::GetAnnouncementManager(), CServiceBroker::GetFavouritesService(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), CServiceBroker::GetPVRManager(), CServiceBroker::GetRepositoryUpdater(), ANNOUNCEMENT::GUI, m_currentUrl, m_isSubscribed, IListProvider::m_parentID, m_section, m_subscriptionSection, m_url, OnAddonEvent(), OnAddonRepositoryEvent(), OnFavouritesEvent(), OnPVRManagerEvent(), ANNOUNCEMENT::Player, CEventStream< Event >::Subscribe(), value, and ANNOUNCEMENT::VideoLibrary.
Referenced by Update().
Member Data Documentation
m_browse
KODI::GUILIB::GUIINFO::CGUIInfoLabel CDirectoryProvider::m_browse private
Referenced by CDirectoryProvider(), and UpdateBrowse().
m_currentBrowse
BrowseMode CDirectoryProvider::m_currentBrowse {BrowseMode::AUTO} private
Referenced by Reset(), Update(), and UpdateBrowse().
m_currentLimit
unsigned int CDirectoryProvider::m_currentLimit {0} private
Referenced by Reset(), Update(), and UpdateLimit().
m_currentSort
SortDescription CDirectoryProvider::m_currentSort private
Referenced by Announce(), Reset(), Update(), and UpdateSort().
m_currentTarget
std::string CDirectoryProvider::m_currentTarget private
node.target property on the list as a whole
Referenced by GetTarget(), OnJobComplete(), and Reset().
m_currentUrl
std::string CDirectoryProvider::m_currentUrl private
Referenced by OnAddonEvent(), OnAddonRepositoryEvent(), OnFavouritesEvent(), OnPVRManagerEvent(), Reset(), Update(), and UpdateURL().
m_isSubscribed
bool CDirectoryProvider::m_isSubscribed {false} private
Referenced by Reset(), and UpdateURL().
m_items
std::vector<CGUIStaticItemPtr> CDirectoryProvider::m_items private
Referenced by Fetch(), FreeResources(), OnJobComplete(), Reset(), and Update().
m_itemTypes
std::vector<InfoTagType> CDirectoryProvider::m_itemTypes private
Referenced by Announce(), OnJobComplete(), and Reset().
m_jobID
unsigned int CDirectoryProvider::m_jobID = 0 private
Referenced by IsUpdating(), OnJobComplete(), Reset(), and Update().
m_limit
KODI::GUILIB::GUIINFO::CGUIInfoLabel CDirectoryProvider::m_limit private
Referenced by CDirectoryProvider(), and UpdateLimit().
m_section
CCriticalSection CDirectoryProvider::m_section mutable private
Referenced by Announce(), Fetch(), FreeResources(), GetTarget(), IsUpdating(), OnAddonEvent(), OnAddonRepositoryEvent(), OnFavouritesEvent(), OnJobComplete(), OnPVRManagerEvent(), Reset(), Update(), UpdateBrowse(), UpdateLimit(), UpdateSort(), and UpdateURL().
m_sortMethod
KODI::GUILIB::GUIINFO::CGUIInfoLabel CDirectoryProvider::m_sortMethod private
Referenced by CDirectoryProvider(), and UpdateSort().
m_sortOrder
KODI::GUILIB::GUIINFO::CGUIInfoLabel CDirectoryProvider::m_sortOrder private
Referenced by CDirectoryProvider(), and UpdateSort().
m_subscriptionSection
CCriticalSection CDirectoryProvider::m_subscriptionSection private
Referenced by Reset(), and UpdateURL().
m_target
KODI::GUILIB::GUIINFO::CGUIInfoLabel CDirectoryProvider::m_target private
Referenced by CDirectoryProvider(), GetTarget(), and Update().
m_updateState
UpdateState CDirectoryProvider::m_updateState = OK private
Referenced by Announce(), IsUpdating(), OnAddonEvent(), OnAddonRepositoryEvent(), OnFavouritesEvent(), OnJobComplete(), OnPVRManagerEvent(), Reset(), and Update().
m_url
KODI::GUILIB::GUIINFO::CGUIInfoLabel CDirectoryProvider::m_url private
Referenced by CDirectoryProvider(), and UpdateURL().
The documentation for this class was generated from the following files:
DirectoryProvider.h
DirectoryProvider.cpp