Kodi Documentation: ANNOUNCEMENT::CAnnouncementManager Class Reference
ANNOUNCEMENT::CAnnouncementManager Class Reference
#include <AnnouncementManager.h>
Classes
struct CAnnounceData
Public Member Functions
CAnnouncementManager ()
~CAnnouncementManager () override
void Start ()
void Deinitialize ()
void AddAnnouncer (IAnnouncer *listener)
void AddAnnouncer (IAnnouncer *listener, int flagMask)
void RemoveAnnouncer (IAnnouncer *listener)
void Announce (AnnouncementFlag flag, const std::string &message)
void Announce (AnnouncementFlag flag, const std::string &message, const CVariant &data)
void Announce (AnnouncementFlag flag, const std::string &message, const std::shared_ptr< const CFileItem > &item)
void Announce (AnnouncementFlag flag, const std::string &message, const std::shared_ptr< const CFileItem > &item, const CVariant &data)
void Announce (AnnouncementFlag flag, const std::string &sender, const std::string &message)
void Announce (AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data)
void Announce (AnnouncementFlag flag, const std::string &sender, const std::string &message, const std::shared_ptr< const CFileItem > &item, const CVariant &data)
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Static Public Attributes
static const std::string ANNOUNCEMENT_SENDER = "xbmc"
Protected Member Functions
void Process () override
void DoAnnounce (AnnouncementFlag flag, const std::string &sender, const std::string &message, const std::shared_ptr< CFileItem > &item, const CVariant &data)
void DoAnnounce (AnnouncementFlag flag, const std::string &sender, const std::string &message, const CVariant &data)
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Protected Attributes
std::list< CAnnounceData > m_announcementQueue
CEvent m_queueEvent
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Private Member Functions
CAnnouncementManager (const CAnnouncementManager &)=delete
CAnnouncementManager const & operator= (CAnnouncementManager const &)=delete
Private Attributes
CCriticalSection m_announcersCritSection
CCriticalSection m_queueCritSection
std::unordered_map< IAnnouncer *, int > m_announcers
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Constructor & Destructor Documentation
CAnnouncementManager() [1/2]
CAnnouncementManager::CAnnouncementManager ()
~CAnnouncementManager()
CAnnouncementManager::~CAnnouncementManager () override
References Deinitialize().
CAnnouncementManager() [2/2]
ANNOUNCEMENT::CAnnouncementManager::CAnnouncementManager (const CAnnouncementManager &) private delete
Member Function Documentation
AddAnnouncer() [1/2]
void CAnnouncementManager::AddAnnouncer (IAnnouncer * listener)
References AddAnnouncer(), ANNOUNCEMENT::ANNOUNCE_ALL, and listener.
Referenced by AddAnnouncer().
AddAnnouncer() [2/2]
void CAnnouncementManager::AddAnnouncer (IAnnouncer * listener, int flagMask)
References listener, m_announcers, and m_announcersCritSection.
Announce() [1/7]
void CAnnouncementManager::Announce (AnnouncementFlag flag, const std::string & message)
References Announce(), ANNOUNCEMENT_SENDER, and data().
Referenced by Announce(), Announce(), Announce(), Announce(), Announce(), and Announce().
Announce() [2/7]
void CAnnouncementManager::Announce (AnnouncementFlag flag, const std::string & message, const CVariant & data)
References Announce(), ANNOUNCEMENT_SENDER, and data().
Announce() [3/7]
void CAnnouncementManager::Announce (AnnouncementFlag flag, const std::string & message, const std::shared_ptr< const CFileItem > & item)
References Announce(), ANNOUNCEMENT_SENDER, and data().
Announce() [4/7]
void CAnnouncementManager::Announce (AnnouncementFlag flag, const std::string & message, const std::shared_ptr< const CFileItem > & item, const CVariant & data)
References Announce(), ANNOUNCEMENT_SENDER, and data().
Announce() [5/7]
void CAnnouncementManager::Announce (AnnouncementFlag flag, const std::string & sender, const std::string & message)
References Announce(), and data().
Announce() [6/7]
void CAnnouncementManager::Announce (AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data)
References Announce(), and data().
Announce() [7/7]
void CAnnouncementManager::Announce (AnnouncementFlag flag, const std::string & sender, const std::string & message, const std::shared_ptr< const CFileItem > & item, const CVariant & data)
References ANNOUNCEMENT::CAnnouncementManager::CAnnounceData::data, data(), ANNOUNCEMENT::CAnnouncementManager::CAnnounceData::flag, ANNOUNCEMENT::CAnnouncementManager::CAnnounceData::item, m_announcementQueue, m_queueCritSection, m_queueEvent, ANNOUNCEMENT::CAnnouncementManager::CAnnounceData::message, ANNOUNCEMENT::CAnnouncementManager::CAnnounceData::sender, and CEvent::Set().
Deinitialize()
void CAnnouncementManager::Deinitialize ()
References m_announcers, m_announcersCritSection, CThread::m_bStop, m_queueEvent, CEvent::Set(), and CThread::StopThread().
Referenced by ~CAnnouncementManager().
DoAnnounce() [1/2]
void CAnnouncementManager::DoAnnounce (AnnouncementFlag flag, const std::string & sender, const std::string & message, const CVariant & data) protected
References data(), CLog::Log(), LOGANNOUNCE, LOGDEBUG, m_announcers, and m_announcersCritSection.
DoAnnounce() [2/2]
void CAnnouncementManager::DoAnnounce (AnnouncementFlag flag, const std::string & sender, const std::string & message, const std::shared_ptr< CFileItem > & item, const CVariant & data) protected
Todo:
Can be removed once this is properly handled when starting playback of a file
Todo:
Can be removed once this is properly handled when starting playback of a file
Todo:
Can be removed once this is properly handled when starting playback of a file
Todo:
Can be removed once this is properly handled when starting playback of a file
References CDatabase::Close(), data(), DoAnnounce(), EPISODES, CMusicDatabase::GetSongByFileName(), id, CVariant::isNull(), CVideoDatabase::LoadVideoInfo(), LOOKUP_PROPERTY, MediaTypeSong, MOVIES, MUSICVIDEOS, CMusicDatabase::Open(), CVideoDatabase::Open(), CVariant::VariantTypeObject, CVideoDatabase::VideoContentTypeToString(), and VideoDbDetailsNone.
Referenced by DoAnnounce(), and Process().
operator=()
CAnnouncementManager const & ANNOUNCEMENT::CAnnouncementManager::operator= (CAnnouncementManager const &) private delete
Process()
void CAnnouncementManager::Process (void) override protected virtual
Reimplemented from CThread.
References DoAnnounce(), LOWEST, m_announcementQueue, CThread::m_bStop, m_queueCritSection, m_queueEvent, CThread::SetPriority(), and CEvent::Wait().
RemoveAnnouncer()
void CAnnouncementManager::RemoveAnnouncer (IAnnouncer * listener)
References listener, m_announcers, and m_announcersCritSection.
Start()
void CAnnouncementManager::Start ()
References CThread::Create().
Member Data Documentation
ANNOUNCEMENT_SENDER
const std::string CAnnouncementManager::ANNOUNCEMENT_SENDER = "xbmc" static
Referenced by CAirPlayServer::Announce(), CAirTunesServer::Announce(), UPNP::CUPnPRenderer::Announce(), UPNP::CUPnPServer::Announce(), PERIPHERALS::CPeripherals::Announce(), CXBMCApp::Announce(), CHotKeyController::Announce(), Announce(), Announce(), Announce(), and Announce().
m_announcementQueue
std::list<CAnnounceData> ANNOUNCEMENT::CAnnouncementManager::m_announcementQueue protected
Referenced by Announce(), and Process().
m_announcers
std::unordered_map<IAnnouncer*, int> ANNOUNCEMENT::CAnnouncementManager::m_announcers private
Referenced by AddAnnouncer(), Deinitialize(), DoAnnounce(), and RemoveAnnouncer().
m_announcersCritSection
CCriticalSection ANNOUNCEMENT::CAnnouncementManager::m_announcersCritSection private
Referenced by AddAnnouncer(), Deinitialize(), DoAnnounce(), and RemoveAnnouncer().
m_queueCritSection
CCriticalSection ANNOUNCEMENT::CAnnouncementManager::m_queueCritSection private
Referenced by Announce(), and Process().
m_queueEvent
CEvent ANNOUNCEMENT::CAnnouncementManager::m_queueEvent protected
Referenced by Announce(), Deinitialize(), and Process().
The documentation for this class was generated from the following files:
AnnouncementManager.h
AnnouncementManager.cpp