Kodi Documentation: CFileItem Class Reference
CFileItem Class Reference
Represents a file on a share.
#include <FileItem.h>
Public Member Functions
CFileItem (void)
CFileItem (const CFileItem &item)
CFileItem (const CGUIListItem &item)
CFileItem (const std::string &strLabel)
CFileItem (const char *strLabel)
CFileItem (const CURL &path, bool bIsFolder)
CFileItem (const std::string &strPath, bool bIsFolder)
CFileItem (const CSong &song)
CFileItem (const CSong &song, const MUSIC_INFO::CMusicInfoTag &music)
CFileItem (const CURL &path, const CAlbum &album)
CFileItem (const std::string &path, const CAlbum &album)
CFileItem (const CArtist &artist)
CFileItem (const CGenre &genre)
CFileItem (const MUSIC_INFO::CMusicInfoTag &music)
CFileItem (const CVideoInfoTag &movie)
CFileItem (const std::shared_ptr< PVR::CPVREpgInfoTag > &tag)
CFileItem (const std::shared_ptr< PVR::CPVREpgSearchFilter > &filter)
CFileItem (const std::shared_ptr< PVR::CPVRChannelGroupMember > &channelGroupMember)
CFileItem (const std::shared_ptr< PVR::CPVRRecording > &record)
CFileItem (const std::shared_ptr< PVR::CPVRTimerInfoTag > &timer)
CFileItem (const std::string &path, const std::shared_ptr< PVR::CPVRProvider > &provider)
CFileItem (const CMediaSource &share)
CFileItem (std::shared_ptr< const ADDON::IAddon > addonInfo)
CFileItem (const EventPtr &eventLogEntry)
~CFileItem (void) override
CGUIListItem * Clone () const override
const CURL GetURL () const
void SetURL (const CURL &url)
bool IsURL (const CURL &url) const
const std::string & GetPath () const
void SetPath (const std::string &path)
bool IsPath (const std::string &path, bool ignoreURLOptions=false) const
const CURL GetDynURL () const
void SetDynURL (const CURL &url)
const std::string & GetDynPath () const
void SetDynPath (const std::string &path)
std::string GetBlurayPath () const
void Reset ()
reset class to it's default values as per construction. Free's all allocated memory.
CFileItem & operator= (const CFileItem &item)
void Archive (CArchive &ar) override
void Serialize (CVariant &value) const override
void ToSortable (SortItem &sortable, Field field) const override
void ToSortable (SortItem &sortable, const Fields &fields) const
bool IsFileItem () const override
bool Exists (bool bUseCache=true) const
bool IsPicture () const
Check whether an item is a picture item. Note that this returns true for anything with a picture info tag, so that may include eg. folders.
bool IsDeleted () const
Check whether an item is 'deleted' (for example, a trashed pvr recording).
bool IsGame () const
bool IsLibraryFolder () const
bool IsPythonScript () const
bool IsPlugin () const
bool IsScript () const
bool IsAddonsPath () const
bool IsSourcesPath () const
bool IsNFO () const
bool IsDiscImage () const
bool IsOpticalMediaFile () const
bool IsBluray () const
bool IsRAR () const
bool IsAPK () const
bool IsZIP () const
bool IsCBZ () const
bool IsCBR () const
bool IsISO9660 () const
bool IsDVD () const
bool IsOnDVD () const
bool IsHD () const
bool IsNfs () const
bool IsSmb () const
bool IsURL () const
bool IsStack () const
bool IsFavourite () const
bool IsMultiPath () const
bool IsEPG () const
bool IsPVRChannel () const
bool IsPVRChannelGroup () const
bool IsPVRRecording () const
bool IsUsablePVRRecording () const
bool IsDeletedPVRRecording () const
bool IsInProgressPVRRecording () const
bool IsPVRTimer () const
bool IsPVRProvider () const
bool IsType (const char *ext) const
bool IsVirtualDirectoryRoot () const
bool IsReadOnly () const
bool CanQueue () const
void SetCanQueue (bool bYesNo)
bool IsParentFolder () const
bool IsFileFolder (EFileFolderType types=EFILEFOLDER_MASK_ALL) const
bool IsRemovable () const
bool IsPVR () const
bool IsLiveTV () const
bool IsRSS () const
bool IsAndroidApp () const
bool HasVideoVersions () const
bool HasVideoExtras () const
void RemoveExtension ()
void CleanString ()
void SetFileSizeLabel ()
void SetLabel (const std::string &strLabel) override
VideoDbContentType GetVideoContentType () const
bool IsLabelPreformatted () const
void SetLabelPreformatted (bool bYesNo)
bool SortsOnTop () const
bool SortsOnBottom () const
void SetSpecialSort (SortSpecial sort)
bool HasMusicInfoTag () const
MUSIC_INFO::CMusicInfoTag * GetMusicInfoTag ()
const MUSIC_INFO::CMusicInfoTag * GetMusicInfoTag () const
bool HasVideoInfoTag () const
CVideoInfoTag * GetVideoInfoTag ()
const CVideoInfoTag * GetVideoInfoTag () const
bool HasEPGInfoTag () const
const std::shared_ptr< PVR::CPVREpgInfoTag > GetEPGInfoTag () const
bool HasEPGSearchFilter () const
const std::shared_ptr< PVR::CPVREpgSearchFilter > GetEPGSearchFilter () const
bool HasPVRChannelGroupMemberInfoTag () const
const std::shared_ptr< PVR::CPVRChannelGroupMember > GetPVRChannelGroupMemberInfoTag () const
bool HasPVRChannelInfoTag () const
const std::shared_ptr< PVR::CPVRChannel > GetPVRChannelInfoTag () const
bool HasPVRRecordingInfoTag () const
const std::shared_ptr< PVR::CPVRRecording > GetPVRRecordingInfoTag () const
bool HasPVRTimerInfoTag () const
const std::shared_ptr< PVR::CPVRTimerInfoTag > GetPVRTimerInfoTag () const
bool HasPVRProviderInfoTag () const
const std::shared_ptr< PVR::CPVRProvider > GetPVRProviderInfoTag () const
CFileItem GetItemToPlay () const
return the item to play. will be almost 'this', but can be different (e.g. "Play recording" from PVR EPG grid window)
bool IsResumePointSet () const
Test if this item has a valid resume point set.
double GetCurrentResumeTime () const
Return the current resume time.
bool GetCurrentResumeTimeAndPartNumber (int64_t &startOffset, int &partNumber) const
Return the current resume time and part.
bool IsResumable () const
Test if this item type can be resumed.
int64_t GetStartOffset () const
Get the offset where start the playback.
void SetStartOffset (const int64_t offset)
Set the offset where start the playback.
int64_t GetEndOffset () const
Get the end offset.
void SetEndOffset (const int64_t offset)
Set the end offset.
bool HasPictureInfoTag () const
const CPictureInfoTag * GetPictureInfoTag () const
bool HasAddonInfo () const
const std::shared_ptr< const ADDON::IAddon > GetAddonInfo () const
bool HasGameInfoTag () const
KODI::GAME::CGameInfoTag * GetGameInfoTag ()
const KODI::GAME::CGameInfoTag * GetGameInfoTag () const
CPictureInfoTag * GetPictureInfoTag ()
std::string FindLocalArt (const std::string &artFile, bool useFolder) const
Assemble the filename of a particular piece of local artwork for an item, and check for file existence.
bool SkipLocalArt () const
Whether or not to skip searching for local art.
std::string GetThumbHideIfUnwatched (const CFileItem *item) const
Get the thumb for the item, but hide it to prevent spoilers if the user has set 'Show information for unwatched items' appropriately.
std::string GetMovieName (bool bUseFolderNames=false) const
std::string GetBaseMoviePath (bool useFolderNames) const
Find the base movie path (i.e. the item the user expects us to use to lookup the movie) For folder items, with "use foldernames for lookups" it returns the folder. Regardless of settings, for VIDEO_TS/BDMV it returns the parent of the VIDEO_TS/BDMV folder (if present)
std::string GetUserMusicThumb (bool alwaysCheckRemote=false, bool fallbackToFolder=false) const
std::string GetLocalMetadataPath () const
Get the path where we expect local metadata to reside. For a folder, this is just the existing path (eg tvshow folder) For a file, this is the parent path, with exceptions made for VIDEO_TS and BDMV files.
bool LoadMusicTag ()
bool LoadGameTag ()
bool LoadDetails ()
Load detailed data for an item constructed with only a path and a folder flag Fills item's video info tag, sets item properties.
const std::string & GetMimeType () const
void SetMimeType (const std::string &mimetype)
void FillInMimeType (bool lookup=true)
Resolve the MIME type based on file extension or a web lookup If m_mimetype is already set (non-empty), this function has no effect. For http:// and shout:// streams, this will query the stream (blocking operation). Set lookup=false to skip any internet lookups and always return immediately.
bool ContentLookup ()
Some sources do not support HTTP HEAD request to determine i.e. mime type.
void SetMimeTypeForInternetFile ()
(Re)set the mime-type for internet files if allowed (m_doContentLookup) Some sources do not support HTTP HEAD request to determine i.e. mime type
void SetContentLookup (bool enable)
Lookup via HTTP HEAD request might not be needed, use this setter to disable ContentLookup.
void SetExtraInfo (const std::string &info)
const std::string & GetExtraInfo () const
void UpdateInfo (const CFileItem &item, bool replaceLabels=true)
Update an item with information from another item We take metadata information from the given item and supplement the current item with that info. If tags exist in the new item we use the entire tag information. Properties are appended, and labels, thumbnail and icon are updated if non-empty in the given item.
void MergeInfo (const CFileItem &item)
Merge an item with information from another item We take metadata/art information from the given item and supplement the current item with that info. If tags exist in the new item we only merge the missing tag information. Properties are appended, and labels are updated if non-empty in the given item.
bool IsSamePath (const CFileItem *item) const
bool IsAlbum () const
void SetFromVideoInfoTag (const CVideoInfoTag &video)
Sets details using the information from the CVideoInfoTag object Sets the videoinfotag and uses its information to set the label and path.
void SetFromMusicInfoTag (const MUSIC_INFO::CMusicInfoTag &music)
Sets details using the information from the CMusicInfoTag object Sets the musicinfotag and uses its information to set the label and path.
void SetFromAlbum (const CAlbum &album)
Sets details using the information from the CAlbum object Sets the album in the music info tag and uses its information to set the label and album-specific properties.
void SetFromSong (const CSong &song)
Sets details using the information from the CSong object Sets the song in the music info tag and uses its information to set the label, path, song-specific properties and artwork.
void SetCueDocument (const CCueDocumentPtr &cuePtr)
void LoadEmbeddedCue ()
bool HasCueDocument () const
bool LoadTracksFromCueDocument (CFileItemList &scannedItems)
Public Member Functions inherited from CGUIListItem
CGUIListItem (void)
CGUIListItem (const CGUIListItem &item)
CGUIListItem (const std::string &strLabel)
virtual ~CGUIListItem (void)
CGUIListItem & operator= (const CGUIListItem &item)
const std::string & GetLabel () const
void SetLabel2 (const std::string &strLabel)
const std::string & GetLabel2 () const
void SetOverlayImage (GUIIconOverlay icon)
std::string GetOverlayImage () const
void SetArt (const std::string &type, const std::string &url)
Set a particular art type for an item.
void SetArt (const ArtMap &art)
set artwork for an item
void AppendArt (const ArtMap &art, const std::string &prefix="")
append artwork to an item
void SetArtFallback (const std::string &from, const std::string &to)
set a fallback image for art
void ClearArt ()
clear art on an item
std::string GetArt (const std::string &type) const
Get a particular art type for an item.
const ArtMap & GetArt () const
get artwork for an item Retrieves artwork in a type:url map
bool HasArt (const std::string &type) const
Check whether an item has a particular piece of art Equivalent to !GetArt(type).empty()
void SetSortLabel (const std::string &label)
void SetSortLabel (const std::wstring &label)
const std::wstring & GetSortLabel () const
void Select (bool bOnOff)
bool IsSelected () const
bool HasOverlay () const
void SetLayout (std::unique_ptr< CGUIListItemLayout > layout)
CGUIListItemLayout * GetLayout ()
void SetFocusedLayout (std::unique_ptr< CGUIListItemLayout > layout)
CGUIListItemLayout * GetFocusedLayout ()
void FreeIcons ()
void FreeMemory (bool immediately=false)
void SetInvalid ()
void SetProperty (const std::string &strKey, const CVariant &value)
void IncrementProperty (const std::string &strKey, int nVal)
void IncrementProperty (const std::string &strKey, int64_t nVal)
void IncrementProperty (const std::string &strKey, double dVal)
void ClearProperties ()
void AppendProperties (const CGUIListItem &item)
Append the properties of one CGUIListItem to another. Any existing properties in the current item will be overridden if they are set in the passed in item.
void Archive (CArchive &ar)
void Serialize (CVariant &value)
bool HasProperty (const std::string &strKey) const
bool HasProperties () const
void ClearProperty (const std::string &strKey)
const CVariant & GetProperty (const std::string &strKey) const
void SetCurrentItem (unsigned int position)
Set the current item number within it's container Our container classes will set this member with the items position in the container starting at 1.
unsigned int GetCurrentItem () const
Get the current item number within it's container Retrieve the items position in a container, this is useful to show for example numbering in front of entities in an arbitrary list of entities, like songs of a playlist.
Public Attributes
bool m_bIsShareOrDrive
is this a root share/drive
int m_iDriveType
If m_bIsShareOrDrive is true, use to get the share type. Types see: CMediaSource::m_iDriveType.
CDateTime m_dateTime
file creation date & time
int64_t m_dwSize
file size (0 for folders)
std::string m_strDVDLabel
std::string m_strTitle
int m_iprogramCount
int m_idepth
int m_lStartPartNumber
LockType m_iLockMode
std::string m_strLockCode
int m_iHasLock
int m_iBadPwdCount
Public Attributes inherited from CGUIListItem
bool m_bIsFolder
is item a folder or a file
Private Member Functions
void Initialize ()
initialize all members of this class (not CGUIListItem members) to default values. Called from constructors, and from Reset()
void UpdateMimeType (bool lookup=true)
Recalculate item's MIME type if it is not set or is set to "application/octet-stream". Resolve the MIME type based on file extension or a web lookup.
CBookmark GetResumePoint () const
Return the current resume point for this item.
void FillMusicInfoTag (const std::shared_ptr< const PVR::CPVREpgInfoTag > &tag)
Fill item's music tag from given epg tag.
Private Attributes
std::string m_strPath
complete path to item
std::string m_strDynPath
SortSpecial m_specialSort
bool m_bIsParentFolder
bool m_bCanQueue
bool m_bLabelPreformatted
std::string m_mimetype
std::string m_extrainfo
bool m_doContentLookup
MUSIC_INFO::CMusicInfoTag * m_musicInfoTag
CVideoInfoTag * m_videoInfoTag
std::shared_ptr< PVR::CPVREpgInfoTag > m_epgInfoTag
std::shared_ptr< PVR::CPVREpgSearchFilter > m_epgSearchFilter
std::shared_ptr< PVR::CPVRRecording > m_pvrRecordingInfoTag
std::shared_ptr< PVR::CPVRTimerInfoTag > m_pvrTimerInfoTag
std::shared_ptr< PVR::CPVRChannelGroupMember > m_pvrChannelGroupMemberInfoTag
std::shared_ptr< PVR::CPVRProvider > m_pvrProviderInfoTag
CPictureInfoTag * m_pictureInfoTag
std::shared_ptr< const ADDON::IAddon > m_addonInfo
KODI::GAME::CGameInfoTag * m_gameInfoTag
EventPtr m_eventLogEntry
bool m_bIsAlbum
int64_t m_lStartOffset
int64_t m_lEndOffset
CCueDocumentPtr m_cueDocument
Additional Inherited Members
Public Types inherited from CGUIListItem
enum GUIIconOverlay {
ICON_OVERLAY_NONE = 0 , ICON_OVERLAY_RAR , ICON_OVERLAY_ZIP , ICON_OVERLAY_LOCKED ,
ICON_OVERLAY_UNWATCHED , ICON_OVERLAY_WATCHED , ICON_OVERLAY_HD
}
typedef std::map< std::string, std::string > ArtMap
Protected Types inherited from CGUIListItem
typedef std::map< std::string, CVariant, icompare > PropertyMap
Protected Member Functions inherited from IArchivable
virtual ~IArchivable ()=default
Protected Member Functions inherited from ISerializable
~ISerializable ()=default
Protected Member Functions inherited from ISortable
~ISortable ()=default
Protected Attributes inherited from CGUIListItem
std::string m_strLabel2
GUIIconOverlay m_overlayIcon
std::unique_ptr< CGUIListItemLayout > m_layout
std::unique_ptr< CGUIListItemLayout > m_focusedLayout
bool m_bSelected
unsigned int m_currentItem
PropertyMap m_mapProperties
Detailed Description
Represents a file on a share.
See also
CFileItemList
Constructor & Destructor Documentation
CFileItem() [1/24]
CFileItem::CFileItem (void)
References Initialize().
Referenced by Clone(), CFileItemList::Copy(), GetItemToPlay(), and IsBluray().
CFileItem() [2/24]
CFileItem::CFileItem (const CFileItem & item)
CFileItem() [3/24]
CFileItem::CFileItem (const CGUIListItem & item) explicit
References FillInMimeType(), and Initialize().
CFileItem() [4/24]
CFileItem::CFileItem (const std::string & strLabel) explicit
References Initialize(), and SetLabel().
CFileItem() [5/24]
CFileItem::CFileItem (const char * strLabel) explicit
References Initialize(), and SetLabel().
CFileItem() [6/24]
CFileItem::CFileItem (const CURL & path, bool bIsFolder)
References URIUtils::AddSlashAtEnd(), FillInMimeType(), CURL::Get(), Initialize(), IsFileFolder(), CGUIListItem::m_bIsFolder, and m_strPath.
CFileItem() [7/24]
CFileItem::CFileItem (const std::string & strPath, bool bIsFolder)
References URIUtils::AddSlashAtEnd(), FillInMimeType(), Initialize(), IsFileFolder(), CGUIListItem::m_bIsFolder, and m_strPath.
CFileItem() [8/24]
CFileItem::CFileItem (const CSong & song) explicit
References Initialize(), and SetFromSong().
CFileItem() [9/24]
CFileItem::CFileItem (const CSong & song, const MUSIC_INFO::CMusicInfoTag & music)
References GetMusicInfoTag(), Initialize(), and SetFromSong().
CFileItem() [10/24]
CFileItem::CFileItem (const CURL & path, const CAlbum & album)
References URIUtils::AddSlashAtEnd(), CURL::Get(), Initialize(), m_strPath, and SetFromAlbum().
CFileItem() [11/24]
CFileItem::CFileItem (const std::string & path, const CAlbum & album)
References URIUtils::AddSlashAtEnd(), Initialize(), m_strPath, and SetFromAlbum().
CFileItem() [12/24]
CFileItem::CFileItem (const CArtist & artist) explicit
References URIUtils::AddSlashAtEnd(), FillInMimeType(), GetMusicInfoTag(), Initialize(), CGUIListItem::m_bIsFolder, m_strPath, MUSIC_INFO::CMusicInfoTag::SetArtist(), SetLabel(), and CArtist::strArtist.
CFileItem() [13/24]
CFileItem::CFileItem (const CGenre & genre) explicit
References URIUtils::AddSlashAtEnd(), FillInMimeType(), GetMusicInfoTag(), Initialize(), CGUIListItem::m_bIsFolder, m_strPath, MUSIC_INFO::CMusicInfoTag::SetGenre(), SetLabel(), and CGenre::strGenre.
CFileItem() [14/24]
CFileItem::CFileItem (const MUSIC_INFO::CMusicInfoTag & music) explicit
References KODI::ART::FillInDefaultIcon(), FillInMimeType(), GetMusicInfoTag(), MUSIC_INFO::CMusicInfoTag::GetTitle(), MUSIC_INFO::CMusicInfoTag::GetURL(), URIUtils::HasSlashAtEnd(), Initialize(), CGUIListItem::m_bIsFolder, m_strPath, and SetLabel().
CFileItem() [15/24]
CFileItem::CFileItem (const CVideoInfoTag & movie) explicit
References Initialize(), and SetFromVideoInfoTag().
CFileItem() [16/24]
CFileItem::CFileItem (const std::shared_ptr< PVR::CPVREpgInfoTag > & tag) explicit
References FillInMimeType(), FillMusicInfoTag(), CServiceBroker::GetPVRManager(), HasMusicInfoTag(), Initialize(), m_bCanQueue, CGUIListItem::m_bIsFolder, m_dateTime, m_epgInfoTag, m_strPath, CGUIListItem::SetArt(), SetLabel(), and CGUIListItem::SetProperty().
CFileItem() [17/24]
CFileItem::CFileItem (const std::shared_ptr< PVR::CPVREpgSearchFilter > & filter) explicit
References FillInMimeType(), Initialize(), CDateTime::IsValid(), m_bCanQueue, CGUIListItem::m_bIsFolder, m_dateTime, m_epgSearchFilter, m_strPath, CGUIListItem::SetArt(), CDateTime::SetFromUTCDateTime(), SetLabel(), and CGUIListItem::SetProperty().
CFileItem() [18/24]
CFileItem::CFileItem (const std::shared_ptr< PVR::CPVRChannelGroupMember > & channelGroupMember) explicit
References FillInMimeType(), FillMusicInfoTag(), HasMusicInfoTag(), Initialize(), m_bCanQueue, CGUIListItem::m_bIsFolder, m_pvrChannelGroupMemberInfoTag, m_strPath, CGUIListItem::SetArt(), SetLabel(), and CGUIListItem::SetProperty().
CFileItem() [19/24]
CFileItem::CFileItem (const std::shared_ptr< PVR::CPVRRecording > & record) explicit
References FillInMimeType(), Initialize(), m_bCanQueue, CGUIListItem::m_bIsFolder, m_dateTime, m_dwSize, m_pvrRecordingInfoTag, m_strPath, CGUIListItem::SetArt(), SetLabel(), and CGUIListItem::SetProperty().
CFileItem() [20/24]
CFileItem::CFileItem (const std::shared_ptr< PVR::CPVRTimerInfoTag > & timer) explicit
References FillInMimeType(), Initialize(), m_bCanQueue, CGUIListItem::m_bIsFolder, m_dateTime, m_pvrTimerInfoTag, m_strPath, CGUIListItem::SetArt(), SetLabel(), and CGUIListItem::SetProperty().
CFileItem() [21/24]
CFileItem::CFileItem (const std::string & path, const std::shared_ptr< PVR::CPVRProvider > & provider) explicit
References FillInMimeType(), Initialize(), m_bCanQueue, CGUIListItem::m_bIsFolder, m_pvrProviderInfoTag, m_strPath, CGUIListItem::SetArt(), SetLabel(), and CGUIListItem::SetProperty().
CFileItem() [22/24]
CFileItem::CFileItem (const CMediaSource & share) explicit
References URIUtils::AddSlashAtEnd(), FillInMimeType(), GetVideoInfoTag(), Initialize(), IsDVD(), IsRSS(), label, CGUIListItem::m_bIsFolder, m_bIsShareOrDrive, m_iBadPwdCount, CMediaSource::m_iBadPwdCount, m_iDriveType, CMediaSource::m_iDriveType, m_iHasLock, CMediaSource::m_iHasLock, m_iLockMode, CMediaSource::m_iLockMode, CVideoInfoTag::m_strFileNameAndPath, m_strLockCode, CMediaSource::m_strLockCode, m_strPath, CMediaSource::m_strThumbnailImage, CGUIListItem::SetArt(), SetLabel(), SetLabelPreformatted(), CMediaSource::strDiskUniqueId, CMediaSource::strName, CMediaSource::strPath, and CMediaSource::strStatus.
CFileItem() [23/24]
CFileItem::CFileItem (std::shared_ptr< const ADDON::IAddon > addonInfo) explicit
References Initialize().
CFileItem() [24/24]
CFileItem::CFileItem (const EventPtr & eventLogEntry) explicit
References Initialize(), m_dateTime, m_eventLogEntry, CGUIListItem::SetArt(), and SetLabel().
~CFileItem()
CFileItem::~CFileItem (void) override
References m_gameInfoTag, m_musicInfoTag, m_pictureInfoTag, and m_videoInfoTag.
Member Function Documentation
Archive()
void CFileItem::Archive (CArchive & ar) override virtual
Implements IArchivable.
Reimplemented in CFileItemList.
References CGUIListItem::Archive(), GetGameInfoTag(), GetMusicInfoTag(), GetPictureInfoTag(), GetVideoInfoTag(), CArchive::IsStoring(), m_bCanQueue, m_bIsParentFolder, m_bIsShareOrDrive, m_bLabelPreformatted, m_dateTime, m_doContentLookup, m_dwSize, m_extrainfo, m_gameInfoTag, m_iBadPwdCount, m_idepth, m_iDriveType, m_iLockMode, m_iprogramCount, m_lEndOffset, m_lStartOffset, m_lStartPartNumber, m_mimetype, m_musicInfoTag, m_pictureInfoTag, m_specialSort, m_strDVDLabel, m_strLockCode, m_strPath, m_strTitle, m_videoInfoTag, and CGUIListItem::SetInvalid().
Referenced by CFileItemList::Archive().
CanQueue()
bool CFileItem::CanQueue () const
References m_bCanQueue.
Referenced by anonymous_namespace{ContextMenus.cpp}::CanQueue(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::CanQueue(), MUSIC_UTILS::IsItemPlayable(), and KODI::VIDEO::UTILS::IsItemPlayable().
CleanString()
void CFileItem::CleanString ()
References CUtil::CleanString(), CGUIListItem::GetLabel(), IsLiveTV(), and SetLabel().
Clone()
CGUIListItem * CFileItem::Clone () const inline override virtual
Reimplemented from CGUIListItem.
Reimplemented in CGUIStaticItem.
References CFileItem().
ContentLookup()
bool CFileItem::ContentLookup () inline
Some sources do not support HTTP HEAD request to determine i.e. mime type.
Returns
false if HEAD requests have to be avoided
References m_doContentLookup.
Referenced by CDVDFactoryInputStream::CreateInputStream(), and CDVDInputStream::Open().
Exists()
bool CFileItem::Exists (bool bUseCache = true) const
References Exists(), XFILE::CFile::Exists(), XFILE::CDirectory::Exists(), XFILE::CMultiPathDirectory::GetFirstPath(), XFILE::CStackDirectory::GetFirstStackedFile(), GetVideoInfoTag(), HasVideoInfoTag(), KODI::NETWORK::IsInternetStream(), URIUtils::IsMultiPath(), IsParentFolder(), IsPath(), IsPlugin(), IsPVR(), URIUtils::IsStack(), IsVirtualDirectoryRoot(), CGUIListItem::m_bIsFolder, CVideoInfoTag::m_strFileNameAndPath, and m_strPath.
Referenced by Exists(), and CVideoDatabase::ExportToXML().
FillInMimeType()
void CFileItem::FillInMimeType (bool lookup = true)
Resolve the MIME type based on file extension or a web lookup If m_mimetype is already set (non-empty), this function has no effect. For http:// and shout:// streams, this will query the stream (blocking operation). Set lookup=false to skip any internet lookups and always return immediately.
Todo:
adapt this to use CMime::GetMimeType()
References GetDynPath(), GetDynURL(), XFILE::CCurlFile::GetMimeType(), CMime::GetMimeType(), GetPVRChannelInfoTag(), HasPVRChannelInfoTag(), CGUIListItem::m_bIsFolder, m_mimetype, m_strDynPath, and m_strPath.
Referenced by CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CGUIMultiImage::CMultiImageJob::DoWork(), CApplication::PlayFile(), SetFromAlbum(), SetFromMusicInfoTag(), SetFromSong(), SetFromVideoInfoTag(), SetMimeTypeForInternetFile(), and UpdateMimeType().
FillMusicInfoTag()
void CFileItem::FillMusicInfoTag (const std::shared_ptr< const PVR::CPVREpgInfoTag > & tag) private
Fill item's music tag from given epg tag.
References GetMusicInfoTag(), CServiceBroker::GetPVRManager(), MUSIC_INFO::CMusicInfoTag::SetDuration(), MUSIC_INFO::CMusicInfoTag::SetGenre(), MUSIC_INFO::CMusicInfoTag::SetLoaded(), MUSIC_INFO::CMusicInfoTag::SetTitle(), and MUSIC_INFO::CMusicInfoTag::SetURL().
Referenced by CFileItem(), and CFileItem().
FindLocalArt()
std::string CFileItem::FindLocalArt (const std::string & artFile, bool useFolder) const
Assemble the filename of a particular piece of local artwork for an item, and check for file existence.
Parameters
artFile the art file to search for.
useFolder whether to look in the folder for the art file. Defaults to false.
Returns
the path to the local artwork if it exists, empty otherwise.
See also
GetLocalArt
References XFILE::CFile::Exists(), KODI::ART::GetLocalArt(), IsFileFolder(), CGUIListItem::m_bIsFolder, and SkipLocalArt().
Referenced by CVideoThumbLoader::GetLocalArt().
GetAddonInfo()
const std::shared_ptr< const ADDON::IAddon > CFileItem::GetAddonInfo () const inline
References m_addonInfo.
Referenced by KODI::GAME::CGameUtils::FillInGameClient(), KODI::GUILIB::GUIINFO::CAddonsGUIInfo::GetBool(), CGUIWindowAddonBrowser::GetDirectory(), KODI::GUILIB::GUIINFO::CAddonsGUIInfo::GetLabel(), CLabelFormatter::GetMaskContent(), IsGame(), CONTEXTMENU::CAddonSettings::IsVisible(), CONTEXTMENU::CCheckForUpdates::IsVisible(), CONTEXTMENU::CEnableAddon::IsVisible(), CONTEXTMENU::CDisableAddon::IsVisible(), and ToSortable().
GetBaseMoviePath()
std::string CFileItem::GetBaseMoviePath (bool useFolderNames) const
Find the base movie path (i.e. the item the user expects us to use to lookup the movie) For folder items, with "use foldernames for lookups" it returns the folder. Regardless of settings, for VIDEO_TS/BDMV it returns the parent of the VIDEO_TS/BDMV folder (if present)
Parameters
useFolderNames whether we're using foldernames for lookups
Returns
the base movie folder
References XFILE::CMultiPathDirectory::GetFirstPath(), CURL::GetHostName(), GetLocalMetadataPath(), URIUtils::GetParentPath(), GetVideoInfoTag(), HasVideoInfoTag(), CMediaTypes::IsContainer(), URIUtils::IsInArchive(), IsMultiPath(), IsOpticalMediaFile(), CGUIListItem::m_bIsFolder, m_strPath, and CUtil::RemoveTrailingDiscNumberSegmentFromPath().
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), KODI::VIDEO::CVideoInfoScanner::EnumerateEpisodeItem(), GetMovieName(), and TEST_P().
GetBlurayPath()
std::string CFileItem::GetBlurayPath () const
References CURL::Get(), GetDynPath(), CURL::GetHostName(), and CURL::IsProtocol().
Referenced by GetLocalMetadataPath(), and CGUIDialogSimpleMenu::ShowPlaySelection().
GetCurrentResumeTime()
double CFileItem::GetCurrentResumeTime () const
Return the current resume time.
Returns
The time in seconds from the start to resume playing from.
References GetResumePoint().
Referenced by CApplication::PlayFile().
GetCurrentResumeTimeAndPartNumber()
bool CFileItem::GetCurrentResumeTimeAndPartNumber (int64_t & startOffset, int & partNumber) const
Return the current resume time and part.
Parameters
startOffset will be filled with the resume time offset in seconds if item has a resume point set, is unchanged otherwise
partNumber will be filled with the part number if item has a resume point set, is unchanged otherwise
Returns
True if the item has a resume point set, false otherwise.
References GetResumePoint(), CBookmark::IsSet(), CBookmark::partNumber, and CBookmark::timeInSeconds.
Referenced by anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation().
GetDynPath()
const std::string & CFileItem::GetDynPath () const
References m_strDynPath, and m_strPath.
Referenced by CMusicDatabase::AddAudioBook(), CVideoPlayer::AddSubtitleFile(), CDVDFileInfo::CanExtract(), XFILE::CDirectoryFactory::Create(), KODI::PLAYLIST::CPlayListFactory::Create(), CDVDFactoryInputStream::CreateInputStream(), CSaveFileState::DoWork(), KODI::VIDEO::TAGS::CVideoTagExtractionHelper::ExtractEmbeddedArtFor(), FillInMimeType(), ADDON::FromFileItem< CMusicAlbumInfo >(), ADDON::FromFileItem< CMusicArtistInfo >(), ADDON::FromFileItem< CScraperUrl >(), GetBlurayPath(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), PVR::CPVRItem::GetChannel(), PVR::CPVRItem::GetEpgInfoTag(), CDVDInputStream::GetFileName(), CDVDFileInfo::GetFileStreamDetails(), KODI::ART::GetLocalArtBaseFilename(), CMime::GetMimeType(), PVR::CPVRItem::GetNextEpgInfoTag(), anonymous_namespace{PluginDirectory.cpp}::GetOriginalPluginPath(), CGUIWindowSlideShow::GetPicturePath(), CVideoDatabase::GetPlayCount(), CPlayerCoreFactory::GetPlayers(), CPlayerSelectionRule::GetPlayers(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::GetPlayers(), PVR::CPVRItem::GetRecording(), CApplicationStackHelper::GetRegisteredStack(), CApplicationStackHelper::GetRegisteredStackPartNumber(), CApplicationStackHelper::GetRegisteredStackPartStartTimeMs(), CApplicationStackHelper::GetRegisteredStackTotalTimeMs(), XFILE::CPluginDirectory::GetResolvedPluginResult(), CMusicDatabase::GetResumeBookmarkForAudioBook(), KODI::VIDEO::UTILS::GetStackPartResumeInformation(), PVR::CPVRItem::GetTimerInfoTag(), KODI::VIDEO::UTILS::HasItemVideoDbInformation(), URIUtils::HasPluginPath(), CApplicationStackHelper::HasRegisteredStack(), CApplicationStackHelper::InitializeStack(), CApplicationStackHelper::InitializeStackStartPartAndOffset(), KODI::VIDEO::IsBDFile(), KODI::VIDEO::IsBlurayPlaylist(), IsDiscImage(), KODI::VIDEO::IsDVDFile(), KODI::VIDEO::TAGS::CVideoTagExtractionHelper::IsExtractionSupportedFor(), KODI::NETWORK::IsInternetStream(), KODI::PLAYLIST::CPlayListFactory::IsPlaylist(), PVR::CPVRItem::IsRadio(), IsSamePath(), IsStack(), KODI::NETWORK::IsStreamedFilesystem(), MergeInfo(), ADDON::CScraper::NfoUrl(), CGUIWindowVideoBase::OnItemInfo(), CDVDInputStreamBluray::Open(), CDVDInputStreamFFmpeg::Open(), CDVDInputStreamFile::Open(), CDVDInputStreamNavigator::Open(), CDVDInputStreamStack::Open(), CInputStreamAddon::Open(), CVideoPlayer::OpenInputStream(), CApplication::PlayStack(), CDVDFileInfo::ProcessExternalSubtitles(), CEdl::ReadEditDecisionLists(), CEdl::ReadPvr(), XFILE::CDVDDirectory::Resolve(), XFILE::CISO9660Directory::Resolve(), ADDON::CScraper::ResolveIDToUrl(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), CUtil::ScanForExternalSubtitles(), CVideoDatabase::SetPlayCount(), CApplicationStackHelper::SetRegisteredStack(), CApplicationStackHelper::SetRegisteredStackPartNumber(), CApplicationStackHelper::SetRegisteredStackPartStartTimeMs(), CApplicationStackHelper::SetRegisteredStackTotalTimeMs(), CMusicDatabase::SetResumeBookmarkForAudioBook(), CGUIDialogSimpleMenu::ShowPlaySelection(), CGUIDialogSimpleMenu::ShowPlaySelection(), CInputStreamAddon::Supports(), and UpdateInfo().
GetDynURL()
const CURL CFileItem::GetDynURL () const
References m_strDynPath, and m_strPath.
Referenced by CDVDFactoryInputStream::CreateInputStream(), FillInMimeType(), and CDVDInputStream::GetURL().
GetEndOffset()
int64_t CFileItem::GetEndOffset () const inline
Get the end offset.
Returns
The offset value as ms.
References m_lEndOffset.
Referenced by XFILE::CFileDirectoryFactory::Create(), CSong::CSong(), CGUIMediaWindow::GetDirectoryHistoryString(), and CApplicationStackHelper::GetStackPartEndTimeMs().
GetEPGInfoTag()
const std::shared_ptr< PVR::CPVREpgInfoTag > CFileItem::GetEPGInfoTag () const inline
References m_epgInfoTag.
Referenced by PVR::CPVRItem::GetChannel(), PVR::CPVRManager::GetClient(), PVR::CPVREdl::GetEdits(), PVR::CPVRItem::GetEpgInfoTag(), PVR::CPVRGUIInfo::GetListItemAndPlayerBool(), PVR::CPVRPlaybackState::GetNextAutoplayItem(), PVR::CPVRItem::GetNextEpgInfoTag(), PVR::CPVRItem::GetRecording(), PVR::CPVRItem::GetTimerInfoTag(), PVR::CONTEXTMENUITEM::GetTimerInfoTagFromItem(), PVR::CPVRGUIActionsTimers::GetTimerRule(), PVR::CPVRItem::IsRadio(), PVR::CPVRPlaybackState::OnPlaybackStarted(), and PVR::CPVRPlaybackState::OnPlaybackStopped().
GetEPGSearchFilter()
const std::shared_ptr< PVR::CPVREpgSearchFilter > CFileItem::GetEPGSearchFilter () const inline
References m_epgSearchFilter.
Referenced by PVR::CPVRGUIActionsEPG::ChooseIconForSavedSearch(), PVR::CPVRGUIActionsEPG::DeleteSavedSearch(), PVR::CPVRGUIActionsEPG::DuplicateSavedSearch(), PVR::CPVRGUIActionsEPG::EditSavedSearch(), PVR::CPVRGUIActionsEPG::ExecuteSavedSearch(), PVR::CPVRGUIInfo::GetListItemAndPlayerLabel(), PVR::CGUIWindowPVRSearchBase::OpenDialogSearch(), PVR::CPVRGUIActionsEPG::RenameSavedSearch(), and PVR::CGUIWindowPVRSearchBase::SetItemToSearch().
GetExtraInfo()
const std::string & CFileItem::GetExtraInfo () const inline
References m_extrainfo.
GetGameInfoTag() [1/2]
CGameInfoTag * CFileItem::GetGameInfoTag ()
References m_gameInfoTag.
Referenced by Archive(), AudioClassifyTest::AudioClassifyTest(), KODI::GAME::CGameUtils::FillInGameClient(), CGUIInfoManager::GetCurrentGameTag(), KODI::GUILIB::GUIINFO::CGamesGUIInfo::InitCurrentItem(), LoadGameTag(), MergeInfo(), KODI::RETRO::CRetroPlayer::OpenFile(), RunAddon(), ToSortable(), UpdateInfo(), and VideoClassifyTest::VideoClassifyTest().
GetGameInfoTag() [2/2]
const KODI::GAME::CGameInfoTag * CFileItem::GetGameInfoTag () const inline
References m_gameInfoTag.
GetItemToPlay()
CFileItem CFileItem::GetItemToPlay () const
return the item to play. will be almost 'this', but can be different (e.g. "Play recording" from PVR EPG grid window)
Returns
the item to play
References CFileItem(), PVR::CPVRManager::Get(), CServiceBroker::GetPVRManager(), and HasEPGInfoTag().
Referenced by CONTEXTMENU::CVideoResume::GetLabel(), CONTEXTMENU::CVideoPlay::GetLabel(), CPlayerUtils::IsItemPlayable(), CONTEXTMENU::CVideoRemoveResumePoint::IsVisible(), and CONTEXTMENU::CVideoResume::IsVisible().
GetLocalMetadataPath()
std::string CFileItem::GetLocalMetadataPath () const
Get the path where we expect local metadata to reside. For a folder, this is just the existing path (eg tvshow folder) For a file, this is the parent path, with exceptions made for VIDEO_TS and BDMV files.
Three cases are handled:
/foo/bar/movie_name/file_name -> /foo/bar/movie_name/ /foo/bar/movie_name/VIDEO_TS/file_name -> /foo/bar/movie_name/ /foo/bar/movie_name/BDMV/file_name -> /foo/bar/movie_name/
See also
URIUtils::GetParentPath
References GetBlurayPath(), URIUtils::GetFileName(), URIUtils::GetParentPath(), IsFileFolder(), CGUIListItem::m_bIsFolder, m_strPath, and URIUtils::RemoveSlashAtEnd().
Referenced by KODI::VIDEO::CVideoInfoScanner::EnumerateEpisodeItem(), CVideoTagLoaderNFO::FindNFO(), GetBaseMoviePath(), KODI::ART::GetLocalArtBaseFilename(), KODI::ART::GetLocalFanart(), and CUtil::GetVideoBasePathAndFileName().
GetMimeType()
const std::string & CFileItem::GetMimeType () const inline
References m_mimetype.
Referenced by XFILE::CDirectoryFactory::Create(), KODI::PLAYLIST::CPlayListFactory::Create(), CDVDFactoryInputStream::CreateInputStream(), CGUIMultiImage::CMultiImageJob::DoWork(), UPNP::GetMimeType(), CPlayerSelectionRule::GetPlayers(), UPNP::GetResource(), KODI::MUSIC::IsAudio(), MUSIC_UTILS::IsItemPlayable(), KODI::VIDEO::UTILS::IsItemPlayable(), KODI::PLAYLIST::CPlayListFactory::IsPlaylist(), KODI::VIDEO::IsVideo(), CDVDInputStream::Open(), CDVDInputStreamFile::Open(), CInputStreamAddon::Open(), and CApplication::PlayFile().
GetMovieName()
std::string CFileItem::GetMovieName (bool bUseFolderNames = false) const
References GetBaseMoviePath(), URIUtils::GetFileName(), CGUIListItem::GetLabel(), XFILE::CStackDirectory::GetStackedTitlePath(), PVR::CPVRRecording::GetTitleFromURL(), GetVideoInfoTag(), HasVideoInfoTag(), IsLabelPreformatted(), IsPlugin(), URIUtils::IsPVRRecording(), URIUtils::IsStack(), m_pvrRecordingInfoTag, m_strPath, m_strTitle, CVideoInfoTag::m_strTitle, and URIUtils::RemoveSlashAtEnd().
Referenced by XBMCAddon::xbmc::getCleanMovieTitle(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo(), and KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow().
GetMusicInfoTag() [1/2]
MUSIC_INFO::CMusicInfoTag * CFileItem::GetMusicInfoTag ()
References m_musicInfoTag.
Referenced by CMusicDatabase::AddAudioBook(), CGUIDialogMusicInfo::AddItemPathToFileBrowserSources(), Archive(), AudioClassifyTest::AudioClassifyTest(), UPNP::BuildObject(), CAlbum::CAlbum(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CSong::CSong(), CSaveFileState::DoWork(), MUSIC_INFO::CMusicInfoScanner::FileItemsToAlbums(), MUSIC_UTILS::FillArtTypesList(), CMusicThumbLoader::FillLibraryArt(), CVideoThumbLoader::FillLibraryArt(), FillMusicInfoTag(), JSONRPC::CAudioLibrary::GetAlbums(), CMusicDatabase::GetArtistsByAlbum(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetBool(), CGUIInfoManager::GetCurrentSongTag(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetFallbackLabel(), CMusicDatabase::GetFileItemFromArtistCredits(), CMusicDatabase::GetFileItemFromDataset(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), CLabelFormatter::GetMaskContent(), CMime::GetMimeType(), UPNP::GetMimeType(), CMusicDatabase::GetRecentlyAddedAlbumSongs(), CMusicDatabase::GetRecentlyPlayedAlbumSongs(), JSONRPC::CAudioLibrary::GetSongs(), CMusicDatabase::GetSongsFullByWhere(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::InitCurrentItem(), IsSamePath(), CONTEXTMENU::CMusicInfo::IsVisible(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), LoadEmbeddedCue(), CMusicThumbLoader::LoadItemCached(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), CMusicThumbLoader::LoadItemLookup(), LoadMusicTag(), CCueDocument::LoadTracks(), MergeInfo(), CGUIInfoManager::OnApplicationMessage(), CGUIWindowMusicPlayList::OnItemLoaded(), CExecString::Parse(), KODI::CDRIP::CCDDARipper::RipTrack(), SetFromAlbum(), SetFromMusicInfoTag(), SetFromSong(), CMusicDatabase::SetPropertiesForFileItem(), CGUIDialogMusicInfo::ShowFor(), anonymous_namespace{MusicUtils.cpp}::ShowToastNotification(), TEST(), ToSortable(), UpdateInfo(), and VideoClassifyTest::VideoClassifyTest().
GetMusicInfoTag() [2/2]
const MUSIC_INFO::CMusicInfoTag * CFileItem::GetMusicInfoTag () const inline
References m_musicInfoTag.
GetPath()
const std::string & CFileItem::GetPath () const inline
References m_strPath.
Referenced by PVR::CGUIWindowPVRTimersBase::ActionShowTimer(), JSONRPC::CPlaylistOperations::Add(), CVideoDatabase::AddFile(), CGUIDialogMusicInfo::AddItemPathToFileBrowserSources(), CFavouritesService::AddOrRemove(), CMusicFileItemListModifier::AddQueuingFolder(), CVideoFileItemListModifier::AddQueuingFolder(), KODI::VIDEO::CVideoInfoScanner::AddVideo(), CVideoDatabase::AddVideoAsset(), CFileItemList::AlwaysCache(), CGUIWindowVideoNav::ApplyWatchedFilter(), CFileItemList::Assign(), CGUIViewStateWindowVideoNav::AutoPlayNextItem(), UPNP::BuildObject(), UPNP::CUPnPServer::BuildResponse(), CDVDFileInfo::CanExtract(), KODI::PLAYLIST::CSmartPlaylistFileItemListModifier::CanModify(), CExecString::CExecString(), CGUIViewStateAddonBrowser::CGUIViewStateAddonBrowser(), CGUIViewStateEventLog::CGUIViewStateEventLog(), CGUIViewStateFavourites::CGUIViewStateFavourites(), CGUIViewStateFromItems::CGUIViewStateFromItems(), CGUIViewStateLibrary::CGUIViewStateLibrary(), CGUIViewStateMusicDatabase::CGUIViewStateMusicDatabase(), CGUIViewStateMusicPlaylist::CGUIViewStateMusicPlaylist(), CGUIViewStateMusicSearch::CGUIViewStateMusicSearch(), CGUIViewStateMusicSmartPlaylist::CGUIViewStateMusicSmartPlaylist(), CGUIViewStateVideoEpisodes::CGUIViewStateVideoEpisodes(), CGUIViewStateVideoMovies::CGUIViewStateVideoMovies(), CGUIViewStateVideoMusicVideos::CGUIViewStateVideoMusicVideos(), CGUIViewStateVideoPlaylist::CGUIViewStateVideoPlaylist(), CGUIViewStateVideoTVShows::CGUIViewStateVideoTVShows(), KODI::GAME::CGUIViewStateWindowGames::CGUIViewStateWindowGames(), CGUIViewStateWindowMusicNav::CGUIViewStateWindowMusicNav(), CGUIViewStateWindowMusicPlaylist::CGUIViewStateWindowMusicPlaylist(), CGUIViewStateWindowPictures::CGUIViewStateWindowPictures(), CGUIViewStateWindowPrograms::CGUIViewStateWindowPrograms(), PVR::CGUIViewStateWindowPVRProviders::CGUIViewStateWindowPVRProviders(), PVR::CGUIViewStateWindowPVRRecordings::CGUIViewStateWindowPVRRecordings(), PVR::CGUIViewStateWindowPVRSearch::CGUIViewStateWindowPVRSearch(), CGUIViewStateWindowVideoNav::CGUIViewStateWindowVideoNav(), CGUIViewStateWindowVideoPlaylist::CGUIViewStateWindowVideoPlaylist(), CInputStreamPVRBase::CInputStreamPVRBase(), PVR::CPVRThumbLoader::ClearCachedImage(), PVR::CGUIDialogPVRGroupManager::ClearGroupThumbnails(), CInputStreamPVRChannel::ClosePVRStream(), CInputStreamPVRRecording::ClosePVRStream(), XFILE::CStackDirectory::ConstructStackPath(), XFILE::CFileDirectoryFactory::Create(), PVR::CPVRThumbLoader::CreateChannelGroupThumb(), CDVDFactoryInputStream::CreateInputStream(), MUSIC_INFO::CMusicInfoTagLoaderFactory::CreateLoader(), CSong::CSong(), CVideoTagLoaderFFmpeg::CVideoTagLoaderFFmpeg(), CVideoTagLoaderNFO::CVideoTagLoaderNFO(), CVideoDatabase::DeleteResumeBookMark(), CVideoThumbLoader::DetectAndAddMissingItemData(), CFileOperationJob::DoProcess(), MUSIC_INFO::CMusicInfoScanner::DoScan(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), CGUIMultiImage::CMultiImageJob::DoWork(), CSaveFileState::DoWork(), KODI::VIDEO::CVideoInfoScanner::EnumerateEpisodeItem(), KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder(), CVideoDatabase::EraseVideoSettings(), PVR::CGUIWindowPVRSearchBase::ExecuteSearch(), CApplication::ExecuteXBMCAction(), XFILE::CUPnPFile::Exists(), CVideoDatabase::ExportToXML(), CDVDFileInfo::ExtractThumbToTexture(), KODI::VIDEO::CVideoInfoScanner::FetchActorThumbs(), JSONRPC::CFileOperations::FillFileItemList(), KODI::ART::FillInDefaultIcon(), KODI::GAME::CGameUtils::FillInGameClient(), PVR::CPVRThumbLoader::FillThumb(), CVideoThumbLoader::FillThumb(), ADDON::CAddonMgr::FindAddons(), CVideoTagLoaderNFO::FindNFO(), KODI::VIDEO::UTILS::FindTrailer(), CGUIDialogFileBrowser::FrameMove(), CGUIDialogPictureInfo::FrameMove(), CGUIMediaWindow::GetAdvanceFilteredItems(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), CThumbLoader::GetCachedImage(), PVR::CPVRManager::GetClient(), CGUIWindowPictures::GetContextButtons(), CGUIWindowPrograms::GetContextButtons(), PVR::CGUIWindowPVRSearchBase::GetContextButtons(), CGUIWindowVideoNav::GetContextButtons(), XFILE::CDAVDirectory::GetDirectory(), XFILE::CLibraryDirectory::GetDirectory(), JSONRPC::CFileOperations::GetDirectory(), CGUIMediaWindow::GetDirectory(), CGUIWindowEventLog::GetDirectory(), KODI::GAME::CGUIWindowGames::GetDirectory(), CGUIWindowMusicBase::GetDirectory(), CGUIWindowMusicNav::GetDirectory(), CGUIWindowPictures::GetDirectory(), CGUIWindowVideoBase::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), CGUIWindowFileManager::GetDirectoryHistoryString(), CGUIMediaWindow::GetDirectoryHistoryString(), PVR::CGUIWindowPVRChannelsBase::GetDirectoryPath(), PVR::CGUIWindowPVRTVProviders::GetDirectoryPath(), PVR::CGUIWindowPVRRadioProviders::GetDirectoryPath(), PVR::CGUIWindowPVRRecordingsBase::GetDirectoryPath(), PVR::CGUIWindowPVRTVSearch::GetDirectoryPath(), PVR::CGUIWindowPVRRadioSearch::GetDirectoryPath(), PVR::CGUIWindowPVRTVTimerRules::GetDirectoryPath(), PVR::CGUIWindowPVRRadioTimerRules::GetDirectoryPath(), PVR::CGUIWindowPVRTVTimers::GetDirectoryPath(), PVR::CGUIWindowPVRRadioTimers::GetDirectoryPath(), CFileItemList::GetDiscFileCache(), CVideoThumbLoader::GetEmbeddedThumbURL(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetFallbackLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetFallbackLabel(), CFavouritesService::GetFavourite(), CVideoDatabase::GetFileId(), CGUIMediaWindow::GetFilteredItems(), CGUIWindowVideoNav::GetFirstUnwatchedItemIndex(), anonymous_namespace{VideoUtils.cpp}::GetFolderItemResumeInformation(), KODI::ART::GetFolderThumb(), CGUIWindowVideoBase::GetGroupedItems(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), PVR::CPVRGUIInfo::GetListItemAndPlayerLabel(), CVideoThumbLoader::GetLocalArt(), KODI::ART::GetLocalArtBaseFilename(), KODI::ART::GetLocalFanart(), CLabelFormatter::GetMaskContent(), UPNP::GetMimeType(), CGUIInfoManager::GetMultiInfoItemLabel(), anonymous_namespace{MusicUtils.cpp}::GetMusicDbItemPath(), anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), KODI::VIDEO::UTILS::GetOpticalMediaPath(), anonymous_namespace{PluginDirectory.cpp}::GetOriginalPluginPath(), XFILE::CSmartPlaylistDirectory::GetPlaylistByName(), XFILE::CPluginDirectory::GetPluginResult(), PVR::CPVRGUIDirectory::GetRecordingsDirectoryInfo(), XFILE::CPluginDirectory::GetResolvedPluginResult(), UPNP::GetResource(), PVR::CGUIWindowPVRRecordingsBase::GetRootPath(), CGUIWindowVideoBase::GetScraperForItem(), CGUIWindowVideoNav::GetSettingSelectFirstUnwatchedItem(), CGUIDialogContextMenu::GetShare(), KODI::ART::GetTBNFile(), KODI::CDRIP::CCDDARipper::GetTrackName(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::GetVideoDbItemPath(), CGUIViewState::GetViewState(), CGUIMediaWindow::GoParentFolder(), KODI::VIDEO::UTILS::HasItemVideoDbInformation(), URIUtils::HasPluginPath(), PVR::CGUIViewStateWindowPVRRecordings::HideParentDirItems(), PVR::CGUIViewStateWindowPVRTimers::HideParentDirItems(), PVR::CGUIViewStateWindowPVRSearch::HideParentDirItems(), PVR::CGUIViewStateWindowPVRProviders::HideParentDirItems(), CVideoDatabase::ImportFromXML(), CMusicDatabase::IncrementPlayCount(), KODI::GUILIB::GUIINFO::CGamesGUIInfo::InitCurrentItem(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::InitCurrentItem(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::InitCurrentItem(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::InitCurrentItem(), PERIPHERALS::CGUIDialogPeripheralSettings::InitializeSettings(), KODI::MUSIC::IsAudio(), KODI::MUSIC::IsCDDA(), KODI::MUSIC::IsCUESheet(), KODI::VIDEO::IsDiscStub(), MUSIC_UTILS::IsItemPlayable(), KODI::VIDEO::UTILS::IsItemPlayable(), KODI::MUSIC::IsLyrics(), anonymous_namespace{FavouritesService.cpp}::IsMediasourceOfFavItemUnlocked(), KODI::MUSIC::IsMusicDb(), MUSIC_UTILS::anonymous_namespace{MusicUtils.cpp}::IsNonExistingUserPartyModePlaylist(), KODI::VIDEO::UTILS::anonymous_namespace{VideoGUIUtils.cpp}::IsNonExistingUserPartyModePlaylist(), KODI::VIDEO::IsProtectedBlurayDisc(), KODI::NETWORK::IsRemote(), IsSamePath(), CGUIMediaWindow::IsSameStartFolder(), KODI::PLAYLIST::IsSmartPlayList(), KODI::VIDEO::IsSubtitle(), KODI::VIDEO::IsVideo(), KODI::VIDEO::IsVideoAssetFile(), KODI::VIDEO::IsVideoDb(), KODI::VIDEO::IsVideoExtrasFolder(), CONTEXTMENU::CAddRemoveFavourite::IsVisible(), CONTEXTMENU::CFavouriteContextMenuAction::IsVisible(), PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible(), CONTEXTMENU::CVideoMarkWatched::IsVisible(), CONTEXTMENU::CVideoMarkUnWatched::IsVisible(), XBMCAddon::xbmcvfs::listdir(), XBMCAddon::xbmc::PlayList::load(), CVideoTagLoaderNFO::Load(), CVideoTagLoaderPlugin::Load(), CFileItemList::Load(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), PVR::anonymous_namespace{PVRGUIActionsUtils.cpp}::LoadChannelItem(), LoadDetails(), LoadEmbeddedCue(), PVR::CPVRGUIActionsUtils::LoadItem(), MUSIC_INFO::CMusicInfoLoader::LoadItemCached(), CPictureInfoLoader::LoadItemCached(), CPictureThumbLoader::LoadItemCached(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), CMusicThumbLoader::LoadItemLookup(), CPictureInfoLoader::LoadItemLookup(), CVideoThumbLoader::LoadItemLookup(), PVR::anonymous_namespace{PVRGUIActionsUtils.cpp}::LoadRecordingFileOrFolderItem(), CCueDocument::LoadTracks(), CGUIWindowVideoBase::LoadVideoInfo(), CGUIWindowMusicNav::ManageInfoProvider(), UPNP::CMediaBrowser::MarkWatched(), KODI::PLAYLIST::CSmartPlaylistFileItemListModifier::Modify(), CGUIDialogFileBrowser::OnAction(), PVR::CGUIWindowPVRProvidersBase::OnAction(), PVR::CGUIWindowPVRRecordingsBase::OnAction(), PVR::CGUIWindowPVRSearchBase::OnAction(), PVR::CGUIWindowPVRTimersBase::OnAction(), CGUIDialogFileBrowser::OnAddNetworkLocation(), CGUIMediaWindow::OnBack(), UPNP::CUPnPServer::OnBrowseDirectChildren(), CGUIMediaWindow::OnClick(), KODI::GAME::CGUIWindowGames::OnContextButton(), CGUIWindowMusicBase::OnContextButton(), CGUIWindowMusicNav::OnContextButton(), CGUIWindowPictures::OnContextButton(), CGUIWindowVideoBase::OnContextButton(), KODI::GAME::CGUIAgentControllerList::OnControllerSelect(), PVR::CGUIWindowPVRRecordingsBase::OnDeinitWindow(), KODI::GAME::CDialogInGameSaves::OnDelete(), KODI::GAME::CDialogGameSaves::OnDelete(), CGUIMediaWindow::OnFilterItems(), CGUIDialogMusicInfo::OnGetArt(), CGUIMediaWindow::OnInitWindow(), CGUIWindowVideoBase::OnItemInfo(), CGUIWindowMusicPlayList::OnItemLoaded(), KODI::GAME::CDialogInGameSaves::OnLoad(), MUSIC_INFO::CMusicInfoLoader::OnLoaderStart(), CPictureInfoLoader::OnLoaderStart(), CGUIDialogFileBrowser::OnMessage(), KODI::GAME::CGUIWindowGames::OnMessage(), CGUIWindowMusicBase::OnMessage(), CGUIWindowMusicNav::OnMessage(), CGUIWindowMusicPlaylistEditor::OnMessage(), CGUIWindowPictures::OnMessage(), CGUIWindowPrograms::OnMessage(), PVR::CGUIWindowPVRProvidersBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), PVR::CGUIWindowPVRSearchBase::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIWindowFileManager::OnMessage(), CGUIWindowFileManager::OnNewFolder(), CXBMCApp::onNewIntent(), KODI::GAME::CDialogInGameSaves::OnOverwrite(), CGUIMediaWindow::OnPlayAndQueueMedia(), CGUIWindowMusicPlayList::OnPlayMedia(), CGUIDialogFileBrowser::OnPopupMenu(), CGUIWindowPictures::OnPrepareFileItems(), PVR::CGUIWindowPVRTimersBase::OnPrepareFileItems(), CGUIWindowVideoPlaylist::OnPrepareFileItems(), KODI::GAME::CDialogInGameSaves::OnRename(), KODI::GAME::CDialogGameSaves::OnRename(), PERIPHERALS::CGUIDialogPeripheralSettings::OnResetSettings(), CGUIWindowMusicBase::OnRetrieveMusicInfo(), CGUIWindowMusicBase::OnScan(), CGUIDialogVideoInfo::OnSearchItemFound(), CGUIWindowVideoBase::OnSearchItemFound(), CGUIDialogAddonInfo::OnSelectVersion(), PERIPHERALS::CGUIDialogPeripheralSettings::OnSettingChanged(), CGUIWindowPictures::OnSlideShow(), CGUIWindowPictures::OnSlideShowRecursive(), CGUIWindowFileManager::OnStart(), CDVDInputStreamBluray::Open(), XFILE::CUPnPFile::Open(), JSONRPC::CPlayerOperations::Open(), PVR::CGUIWindowPVRSearchBase::OpenDialogSearch(), KODI::RETRO::CRetroPlayer::OpenFile(), CVideoPlayer::OpenInputStream(), CInputStreamPVRChannel::OpenPVRStream(), CInputStreamPVRRecording::OpenPVRStream(), CDVDInputStreamBluray::OpenStream(), CVideoPlayer::OpenVideoStream(), CFileOperationJob::operator==(), CExecString::Parse(), ParseItem(), CApplication::PlayFile(), CApplication::PlayMedia(), PVR::CPVRGUIActionsPlayback::PlayMedia(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), PVR::CPVRGUIActionsPlayback::PlayRecording(), CMediaManager::playStubFile(), CPictureThumbLoader::ProcessFoldersAndArchives(), KODI::VIDEO::CVideoInfoScanner::ProcessItemByVideoInfoTag(), CInputStreamPVRBase::ProvidesStreamForMetaDataExtraction(), CGUIMediaWindow::Refresh(), CFileItemList::Remove(), CFileItemList::RemoveDiscCache(), CApplicationPlayerCallback::RequestVideoSettings(), CFavouritesService::ResolveFavourite(), CCueDocument::ResolvePath(), CGUIMediaWindow::RestoreSelectedItemFromHistory(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), MUSIC_INFO::CMusicInfoScanner::RetrieveMusicInfo(), KODI::VIDEO::CVideoInfoScanner::RetrieveVideoInfo(), KODI::CDRIP::CCDDARipper::RipTrack(), RunPlugin(), PERIPHERALS::CGUIDialogPeripheralSettings::Save(), CFileItemList::Save(), CGUIWindowMusicPlayList::SavePlayList(), CGUIMediaWindow::SaveSelectedItemInHistory(), CGUIViewStateAddonBrowser::SaveViewState(), CGUIViewStateEventLog::SaveViewState(), CGUIViewStateFavourites::SaveViewState(), KODI::GAME::CGUIViewStateWindowGames::SaveViewState(), CGUIViewStateMusicSearch::SaveViewState(), CGUIViewStateMusicDatabase::SaveViewState(), CGUIViewStateMusicSmartPlaylist::SaveViewState(), CGUIViewStateMusicPlaylist::SaveViewState(), CGUIViewStateWindowMusicNav::SaveViewState(), CGUIViewStateWindowMusicPlaylist::SaveViewState(), CGUIViewStateWindowPictures::SaveViewState(), CGUIViewStateWindowPrograms::SaveViewState(), PVR::CGUIViewStateWindowPVRRecordings::SaveViewState(), PVR::CGUIViewStateWindowPVRSearch::SaveViewState(), PVR::CGUIViewStateWindowPVRProviders::SaveViewState(), CGUIViewStateVideoPlaylist::SaveViewState(), CGUIViewStateWindowVideoNav::SaveViewState(), CGUIViewStateWindowVideoPlaylist::SaveViewState(), CGUIViewStateVideoMovies::SaveViewState(), CGUIViewStateVideoMusicVideos::SaveViewState(), CGUIViewStateVideoTVShows::SaveViewState(), CGUIViewStateVideoEpisodes::SaveViewState(), CGUIViewStateFromItems::SaveViewState(), CGUIViewStateLibrary::SaveViewState(), CThumbLoader::SetCachedImage(), KODI::GUILIB::GUIINFO::CPicturesGUIInfo::SetCurrentSlide(), CGUIDialogVideoManagerVersions::SetDefaultVideoVersion(), SetFromMusicInfoTag(), CGUIWindowFileManager::SetInitialPath(), KODI::GAME::CGUIDialogSelectGameClient::ShowAndGetGameClient(), CGUIDialogMusicInfo::ShowFor(), CGUIWindowFileManager::ShowShareErrorMessage(), CGUIMediaWindow::ShowShareErrorMessage(), CGUIWindowVideoBase::StackingAvailable(), XFILE::CUPnPFile::Stat(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), CFilesystemInstaller::UnpackArchive(), CGUIDialogFileBrowser::Update(), CGUIMediaWindow::Update(), PVR::CGUIWindowPVRBase::Update(), PVR::CGUIWindowPVRRecordingsBase::Update(), PVR::CGUIWindowPVRSearchBase::Update(), PVR::CGUIWindowPVRTimersBase::Update(), CGUIWindowFileManager::Update(), CGUIWindowAddonBrowser::UpdateButtons(), CGUIWindowMusicNav::UpdateButtons(), CGUIWindowPictures::UpdateButtons(), PVR::CGUIWindowPVRChannelsBase::UpdateButtons(), PVR::CGUIWindowPVRProvidersBase::UpdateButtons(), PVR::CGUIWindowPVRRecordingsBase::UpdateButtons(), PVR::CGUIWindowPVRSearchBase::UpdateButtons(), CGUIWindowVideoNav::UpdateButtons(), CVideoDatabase::UpdateFanart(), CGUIMediaWindow::UpdateFileList(), CGUIMediaWindow::UpdateFilterPath(), CGUIBaseContainer::UpdateListProvider(), PERIPHERALS::CGUIDialogPeripherals::UpdatePeripheralsSync(), and CGUIMediaWindow::WaitForNetwork().
GetPictureInfoTag() [1/2]
CPictureInfoTag * CFileItem::GetPictureInfoTag ()
References m_pictureInfoTag.
GetPictureInfoTag() [2/2]
const CPictureInfoTag * CFileItem::GetPictureInfoTag () const inline
References m_pictureInfoTag.
Referenced by JSONRPC::CPlaylistOperations::Add(), Archive(), AudioClassifyTest::AudioClassifyTest(), KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetLabel(), CLabelFormatter::GetMaskContent(), CPictureInfoLoader::LoadItemCached(), CPictureInfoLoader::LoadItemLookup(), MergeInfo(), KODI::GUILIB::GUIINFO::CPicturesGUIInfo::SetCurrentSlide(), ToSortable(), UpdateInfo(), and VideoClassifyTest::VideoClassifyTest().
GetPVRChannelGroupMemberInfoTag()
const std::shared_ptr< PVR::CPVRChannelGroupMember > CFileItem::GetPVRChannelGroupMemberInfoTag () const inline
References m_pvrChannelGroupMemberInfoTag.
Referenced by PVR::CGUIDialogPVRGroupManager::ClearGroupThumbnails(), PVR::CPVRGUIActionsChannels::GetChannelGroupMember(), PVR::CPVRGUIInfo::GetListItemAndPlayerLabel(), PVR::CPVRGUIActionsChannels::HideChannel(), MergeInfo(), PVR::CPVRPlaybackState::OnPlaybackStarted(), PVR::CPVRPlaybackState::OnPlaybackStopped(), ToSortable(), and UpdateInfo().
GetPVRChannelInfoTag()
const std::shared_ptr< PVR::CPVRChannel > CFileItem::GetPVRChannelInfoTag () const
References m_pvrChannelGroupMemberInfoTag.
Referenced by FillInMimeType(), PVR::CPVRItem::GetChannel(), PVR::CPVRManager::GetClient(), PVR::CPVRItem::GetEpgInfoTag(), PVR::CPVRGUIInfo::GetListItemAndPlayerBool(), PVR::CPVRItem::GetNextEpgInfoTag(), PVR::CPVRGUIInfo::GetRadioRDSBool(), PVR::CPVRGUIInfo::GetRadioRDSLabel(), PVR::CPVRItem::GetTimerInfoTag(), PVR::CPVRItem::IsRadio(), CInputStreamPVRChannel::OpenPVRStream(), and ToSortable().
GetPVRProviderInfoTag()
const std::shared_ptr< PVR::CPVRProvider > CFileItem::GetPVRProviderInfoTag () const inline
References m_pvrProviderInfoTag.
Referenced by ToSortable().
GetPVRRecordingInfoTag()
const std::shared_ptr< PVR::CPVRRecording > CFileItem::GetPVRRecordingInfoTag () const inline
References m_pvrRecordingInfoTag.
Referenced by PVR::CGUIDialogPVRRecordingSettings::CanEditRecording(), PVR::CPVRGUIActionsRecordings::ConfirmDeleteRecording(), PVR::CPVRItem::GetChannel(), PVR::CPVRManager::GetClient(), PVR::CPVREdl::GetEdits(), PVR::CPVRGUIInfo::GetListItemAndPlayerBool(), PVR::CPVRGUIInfo::GetListItemAndPlayerLabel(), PVR::CPVRItem::GetRecording(), PVR::CPVRGUIActionsRecordings::IncrementPlayCount(), IsDeleted(), PVR::CPVRItem::IsRadio(), PVR::CPVRGUIActionsRecordings::MarkWatched(), PVR::CPVRPlaybackState::OnPlaybackStarted(), PVR::CPVRPlaybackState::OnPlaybackStopped(), CInputStreamPVRRecording::OpenPVRStream(), PlayerControl(), PVR::CPVRGUIActionsRecordings::ProcessDeleteAfterWatch(), and PVR::CGUIWindowPVRSearchBase::SetItemToSearch().
GetPVRTimerInfoTag()
const std::shared_ptr< PVR::CPVRTimerInfoTag > CFileItem::GetPVRTimerInfoTag () const inline
References m_pvrTimerInfoTag.
Referenced by PVR::CPVRItem::GetChannel(), PVR::CPVRManager::GetClient(), PVR::CPVRItem::GetEpgInfoTag(), PVR::CPVRGUIInfo::GetListItemAndPlayerBool(), PVR::CPVRGUIInfo::GetListItemAndPlayerLabel(), PVR::CPVRItem::GetNextEpgInfoTag(), PVR::CPVRItem::GetTimerInfoTag(), PVR::CONTEXTMENUITEM::GetTimerInfoTagFromItem(), PVR::CPVRGUIActionsTimers::GetTimerRule(), PVR::CPVRItem::IsRadio(), and PVR::CPVRGUIActionsTimers::ToggleTimerState().
GetResumePoint()
CBookmark CFileItem::GetResumePoint () const private
Return the current resume point for this item.
Returns
The resume point.
References CVideoInfoTag::GetResumePoint(), GetVideoInfoTag(), and HasVideoInfoTag().
Referenced by GetCurrentResumeTime(), GetCurrentResumeTimeAndPartNumber(), and IsResumePointSet().
GetStartOffset()
int64_t CFileItem::GetStartOffset () const inline
Get the offset where start the playback.
Returns
The offset value as ms. Can return also special value -1, see define STARTOFFSET_RESUME.
References m_lStartOffset.
Referenced by CSong::CSong(), CSaveFileState::DoWork(), CGUIMediaWindow::GetDirectoryHistoryString(), CMusicDatabase::GetFileItemFromDataset(), XFILE::CPluginDirectory::GetResolvedPluginResult(), CApplicationStackHelper::InitializeStackStartPartAndOffset(), CDVDInputStreamBluray::Open(), CApplication::PlayFile(), PVR::CPVRGUIActionsPlayback::PlayMedia(), PVR::CPVRGUIActionsPlayback::PlayRecording(), and CGUIMediaWindow::UpdateFileList().
GetThumbHideIfUnwatched()
std::string CFileItem::GetThumbHideIfUnwatched (const CFileItem * item) const
Get the thumb for the item, but hide it to prevent spoilers if the user has set 'Show information for unwatched items' appropriately.
Parameters
item the item to get the thumb image for.
Returns
fanart or spoiler overlay if item is an unwatched episode, thumb art otherwise.
References CSettingUtils::FindIntInList(), CGUIListItem::GetArt(), CVideoInfoTag::GetPlayCount(), CServiceBroker::GetSettingsComponent(), GetVideoInfoTag(), CGUIListItem::HasArt(), HasVideoInfoTag(), CVideoInfoTag::m_type, MediaTypeEpisode, CSettings::SETTING_VIDEOLIBRARY_SHOWUNWATCHEDPLOTS, and CSettings::VIDEOLIBRARY_THUMB_SHOW_UNWATCHED_EPISODE.
Referenced by CGUIInfoManager::GetMultiInfoItemLabel().
GetURL()
const CURL CFileItem::GetURL () const
References m_strPath.
Referenced by UPNP::BuildObject(), XFILE::CFileDirectoryFactory::Create(), CFileOperationJob::DoProcessFolder(), CGUIDialogSubtitles::Download(), ADDON::CScraper::GetEpisodeList(), UPNP::GetProtocolInfo(), CGUIViewState::GetViewState(), CApplication::PlayMedia(), CPictureThumbLoader::ProcessFoldersAndArchives(), XFILE::CUPnPDirectory::Resolve(), and CInputStreamAddon::Supports().
GetUserMusicThumb()
std::string CFileItem::GetUserMusicThumb (bool alwaysCheckRemote = false, bool fallbackToFolder = false) const
References XFILE::CFile::Exists(), URIUtils::GetDirectory(), KODI::ART::GetFolderThumb(), CServiceBroker::GetSettingsComponent(), KODI::ART::GetTBNFile(), GetUserMusicThumb(), IsAddonsPath(), IsFileFolder(), URIUtils::IsFTP(), KODI::NETWORK::IsInternetStream(), IsLibraryFolder(), KODI::MUSIC::IsMusicDb(), IsParentFolder(), IsPlugin(), KODI::NETWORK::IsRemote(), URIUtils::IsUPnP(), CGUIListItem::m_bIsFolder, m_bIsShareOrDrive, m_strPath, name, CSettings::SETTING_MUSICFILES_FINDREMOTETHUMBS, and CSettings::SETTING_MUSICLIBRARY_MUSICTHUMBS.
Referenced by MUSIC_INFO::CMusicInfoScanner::AddAlbumArtwork(), MUSIC_INFO::CMusicInfoScanner::AddArtistArtwork(), CSong::CSong(), CMusicThumbLoader::FillThumb(), MUSIC_INFO::CMusicInfoScanner::FindArtForAlbums(), GetUserMusicThumb(), CGUIDialogMusicInfo::OnGetArt(), and CGUIDialogSongInfo::OnGetArt().
GetVideoContentType()
VideoDbContentType CFileItem::GetVideoContentType () const
References EPISODES, XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetMovieId(), XFILE::CVideoDatabaseDirectory::GetQueryParams(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetSetId(), GetVideoInfoTag(), HasVideoInfoTag(), m_strPath, MediaTypeAlbum, MediaTypeEpisode, MediaTypeMusicVideo, MediaTypeTvShow, MOVIE_SETS, MOVIES, MUSICALBUMS, MUSICVIDEOS, and TVSHOWS.
Referenced by CGUIDialogVideoManagerVersions::AddVideoVersion(), CVideoDatabase::DeleteResumeBookMark(), CSaveFileState::DoWork(), CGUIDialogSubtitles::FillServices(), CVideoDatabase::GetSameVideoItems(), CGUIDialogVideoInfo::OnSearchItemFound(), and CGUIWindowVideoBase::UpdateVideoVersionItemsLabel().
GetVideoInfoTag() [1/2]
CVideoInfoTag * CFileItem::GetVideoInfoTag ()
References m_pvrRecordingInfoTag, and m_videoInfoTag.
Referenced by CVideoDatabase::AddFile(), CGUIDialogVideoInfo::AddItemsToTag(), CVideoFileItemListModifier::AddQueuingFolder(), KODI::VIDEO::CVideoInfoScanner::AddVideo(), CVideoDatabase::AddVideoAsset(), CGUIDialogVideoManagerVersions::AddVideoVersion(), Archive(), AudioClassifyTest::AudioClassifyTest(), UPNP::BuildObject(), CFileItem(), CVideoTagLoaderPlugin::CVideoTagLoaderPlugin(), CVideoDatabase::DeleteResumeBookMark(), ADDON::DetailsFromFileItem< CVideoInfoTag >(), CVideoThumbLoader::DetectAndAddMissingItemData(), CGUIDialogVideoInfo::DoSearch(), CSaveFileState::DoWork(), CVideoDatabase::DumpToDummyFiles(), Exists(), CVideoThumbLoader::FillLibraryArt(), CVideoThumbLoader::FillThumb(), ContentUtils::GeneratePlayableTrailerItem(), CGUIDialogVideoManagerVersions::GetAllOtherMovies(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), GetBaseMoviePath(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetBool(), CGUIInfoManager::GetCurrentMovieTag(), KODI::VIDEO::CVideoInfoScanner::GetDetails(), CVideoDatabase::GetDetailsByTypeAndId(), CGUIWindowVideoNav::GetDirectory(), CVideoThumbLoader::GetEmbeddedThumbURL(), ADDON::CScraper::GetEpisodeList(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetFallbackLabel(), CVideoDatabase::GetFileId(), CDVDFileInfo::GetFileStreamDetails(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetInt(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), KODI::ART::GetLocalFanart(), CLabelFormatter::GetMaskContent(), CMime::GetMimeType(), UPNP::GetMimeType(), GetMovieName(), CGUIDialogVideoInfo::GetMoviesForSet(), anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), CPlayerSelectionRule::GetPlayers(), ContentUtils::GetPreferredArtImage(), GetResumePoint(), CVideoDatabase::GetSameVideoItems(), CGUIWindowVideoBase::GetScraperForItem(), CGUIDialogVideoInfo::GetSetForMovie(), CVideoDatabase::GetSetInfo(), CGUIDialogVideoManagerVersions::GetSimilarMovies(), CVideoDatabase::GetStreamDetails(), GetThumbHideIfUnwatched(), CUtil::GetVideoBasePathAndFileName(), GetVideoContentType(), CVideoDatabase::GetVideoVersions(), KODI::UTILS::GUILIB::CGUIContentUtils::HasInfoForItem(), anonymous_namespace{ContentUtils.cpp}::HasPreferredArtType(), HasVideoExtras(), HasVideoVersions(), CVideoDatabase::ImportFromXML(), KODI::VIDEO::UTILS::IsAutoPlayNextItem(), KODI::VIDEO::IsDiscStub(), IsResumable(), IsSamePath(), CONTEXTMENU::CVideoInfo::IsVisible(), CONTEXTMENU::CVideoMarkWatched::IsVisible(), CONTEXTMENU::CVideoMarkUnWatched::IsVisible(), CGUIDialogVideoInfo::LinkMovieToTvShow(), CVideoTagLoaderNFO::Load(), CVideoThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemLookup(), MergeInfo(), CGUIInfoManager::OnApplicationMessage(), CGUIWindowVideoBase::OnItemInfo(), CGUIWindowVideoNav::OnMessage(), CXBMCApp::onNewIntent(), CApplicationPlayerCallback::OnPlayerCloseFile(), KODI::VIDEO::CVideoInfoScanner::OnProcessSeriesFolder(), CGUIDialogVideoInfo::OnSearch(), CGUIDialogVideoInfo::OnSearchItemFound(), UPNP::CUPnPServer::OnUpdateObject(), CExecString::Parse(), ParseItem(), ParseItemBoxee(), ParseItemItunes(), ParseItemMRSS(), ParseItemVoddler(), ParseItemZink(), CApplication::PlayFile(), CGUIDialogVideoManagerVersions::PostProcessList(), CDVDFileInfo::ProcessExternalSubtitles(), KODI::VIDEO::CVideoInfoScanner::ProcessItemByVideoInfoTag(), CGUIDialogVideoManagerVersions::ProcessVideoVersion(), CGUIDialogVideoInfo::RemoveItemsFromTag(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), UPNP::CMediaBrowser::SaveFileState(), CGUIDialogVideoManagerVersions::SetDefaultVideoVersion(), CGUIDialogVideoInfo::SetMovie(), CGUIDialogVideoInfo::SetMovieSet(), CVideoDatabase::SetPlayCount(), KODI::VIDEO::anonymous_namespace{VideoGeneratedImageFileLoader.cpp}::SetupRarOptions(), StubDefinition::StubDefinition(), TEST_P(), ToSortable(), CVideoDatabase::UpdateFanart(), CVideoPlayer::UpdateFileItemStreamDetails(), UpdateInfo(), UPNP::CMediaBrowser::UpdateItem(), and VideoClassifyTest::VideoClassifyTest().
GetVideoInfoTag() [2/2]
const CVideoInfoTag * CFileItem::GetVideoInfoTag () const
References m_pvrRecordingInfoTag, and m_videoInfoTag.
HasAddonInfo()
bool CFileItem::HasAddonInfo () const inline
References m_addonInfo.
Referenced by KODI::GAME::CGameUtils::FillInGameClient(), CLabelFormatter::GetMaskContent(), KODI::UTILS::GUILIB::CGUIContentUtils::HasInfoForItem(), IsGame(), CONTEXTMENU::CAddonInfo::IsVisible(), CONTEXTMENU::CAddonSettings::IsVisible(), CONTEXTMENU::CCheckForUpdates::IsVisible(), CONTEXTMENU::CEnableAddon::IsVisible(), CONTEXTMENU::CDisableAddon::IsVisible(), CGUIWindowVideoBase::OnItemInfo(), KODI::UTILS::GUILIB::CGUIContentUtils::ShowInfoForItem(), and ToSortable().
HasCueDocument()
bool CFileItem::HasCueDocument () const
References m_cueDocument.
HasEPGInfoTag()
bool CFileItem::HasEPGInfoTag () const inline
References m_epgInfoTag.
Referenced by PVR::CPVRManager::GetClient(), PVR::CPVREdl::GetEdits(), GetItemToPlay(), PVR::CPVRPlaybackState::GetNextAutoplayItem(), PVR::CPVRGUIActionsTimers::GetTimerRule(), IsEPG(), IsPicture(), MergeInfo(), PVR::CPVRPlaybackState::OnPlaybackStarted(), PVR::CPVRGUIActionsChannels::OnPlaybackStopped(), PVR::CPVRPlaybackState::OnPlaybackStopped(), PVR::CPVRGUIActionsTimers::ToggleTimer(), and UpdateInfo().
HasEPGSearchFilter()
bool CFileItem::HasEPGSearchFilter () const inline
References m_epgSearchFilter.
Referenced by PVR::CPVRGUIActionsUtils::HasInfoForItem(), IsPicture(), MergeInfo(), PVR::CPVRGUIActionsUtils::OnInfo(), PVR::CGUIWindowPVRSearchBase::SetItemToSearch(), and UpdateInfo().
HasGameInfoTag()
bool CFileItem::HasGameInfoTag () const inline
References m_gameInfoTag.
Referenced by CGUIInfoManager::GetCurrentGameTag(), KODI::MUSIC::IsAudio(), IsGame(), IsPicture(), KODI::VIDEO::IsVideo(), LoadGameTag(), MergeInfo(), ToSortable(), and UpdateInfo().
HasMusicInfoTag()
bool CFileItem::HasMusicInfoTag () const inline
References m_musicInfoTag.
Referenced by CGUIDialogMusicInfo::AddItemPathToFileBrowserSources(), UPNP::BuildObject(), CFileItem(), CFileItem(), XFILE::CFileDirectoryFactory::Create(), JSONRPC::CFileOperations::FillFileItemList(), CVideoThumbLoader::FillLibraryArt(), CGUIInfoManager::GetCurrentSongTag(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), CMime::GetMimeType(), UPNP::GetMimeType(), KODI::UTILS::GUILIB::CGUIContentUtils::HasInfoForItem(), KODI::MUSIC::IsAudio(), MUSIC_UTILS::IsAutoPlayNextItem(), IsGame(), MUSIC_UTILS::IsItemPlayable(), IsPicture(), IsSamePath(), KODI::VIDEO::IsVideo(), CONTEXTMENU::CMusicInfo::IsVisible(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), CMusicThumbLoader::LoadItemCached(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), CMusicThumbLoader::LoadItemLookup(), LoadMusicTag(), MergeInfo(), CGUIWindowFullScreen::OnAction(), CGUIInfoManager::OnApplicationMessage(), CGUIWindowMusicPlayList::OnItemLoaded(), CExecString::Parse(), CMusicDatabase::SetPropertiesForFileItem(), CGUIDialogMusicInfo::ShowFor(), CGUIDialogSongInfo::ShowFor(), KODI::UTILS::GUILIB::CGUIContentUtils::ShowInfoForItem(), anonymous_namespace{MusicUtils.cpp}::ShowToastNotification(), ToSortable(), and UpdateInfo().
HasPictureInfoTag()
bool CFileItem::HasPictureInfoTag () const inline
References m_pictureInfoTag.
Referenced by KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetLabel(), KODI::MUSIC::IsAudio(), IsGame(), IsPicture(), KODI::VIDEO::IsVideo(), CPictureInfoLoader::LoadItemCached(), CPictureInfoLoader::LoadItemLookup(), MergeInfo(), KODI::GUILIB::GUIINFO::CPicturesGUIInfo::SetCurrentSlide(), ToSortable(), and UpdateInfo().
HasPVRChannelGroupMemberInfoTag()
bool CFileItem::HasPVRChannelGroupMemberInfoTag () const inline
References m_pvrChannelGroupMemberInfoTag.
Referenced by IsPicture(), MergeInfo(), PVR::CPVRPlaybackState::OnPlaybackStarted(), PVR::CPVRPlaybackState::OnPlaybackStopped(), ToSortable(), and UpdateInfo().
HasPVRChannelInfoTag()
bool CFileItem::HasPVRChannelInfoTag () const
References m_pvrChannelGroupMemberInfoTag.
Referenced by FillInMimeType(), PVR::CPVRManager::GetClient(), PVR::CPVRGUIInfo::GetRadioRDSBool(), PVR::CPVRGUIInfo::GetRadioRDSLabel(), PVR::CPVRGUIActionsUtils::HasInfoForItem(), IsPicture(), IsPVRChannel(), PVR::anonymous_namespace{PVRGUIActionsUtils.cpp}::LoadChannelItem(), CGUIWindowFullScreen::OnAction(), PVR::CPVRGUIActionsUtils::OnInfo(), PVR::CPVRPlaybackState::OnPlaybackStarted(), PVR::CPVRGUIActionsChannels::OnPlaybackStopped(), PVR::CPVRPlaybackState::OnPlaybackStopped(), CApplication::PlayFile(), PVR::CPVRGUIActionsPlayback::PlayMedia(), and ToSortable().
HasPVRProviderInfoTag()
bool CFileItem::HasPVRProviderInfoTag () const inline
References m_pvrProviderInfoTag.
Referenced by IsPicture(), IsPVRProvider(), MergeInfo(), ToSortable(), and UpdateInfo().
HasPVRRecordingInfoTag()
bool CFileItem::HasPVRRecordingInfoTag () const inline
References m_pvrRecordingInfoTag.
Referenced by PVR::CGUIDialogPVRRecordingSettings::CanEditRecording(), PVR::CPVRManager::GetClient(), PVR::CPVREdl::GetEdits(), KODI::UTILS::GUILIB::CGUIContentUtils::HasInfoForItem(), PVR::CPVRGUIActionsUtils::HasInfoForItem(), IsDeleted(), IsPicture(), IsPVRRecording(), PVR::anonymous_namespace{PVRGUIActionsUtils.cpp}::LoadRecordingFileOrFolderItem(), PVR::CPVRGUIActionsUtils::OnInfo(), PVR::CPVRPlaybackState::OnPlaybackStarted(), PVR::CPVRPlaybackState::OnPlaybackStopped(), PlayerControl(), and PVR::CPVRGUIActionsPlayback::PlayMedia().
HasPVRTimerInfoTag()
bool CFileItem::HasPVRTimerInfoTag () const inline
References m_pvrTimerInfoTag.
Referenced by PVR::CPVRManager::GetClient(), PVR::CPVRGUIActionsTimers::GetTimerRule(), PVR::CPVRGUIActionsUtils::HasInfoForItem(), IsPicture(), IsPVRTimer(), MergeInfo(), PVR::CPVRGUIActionsUtils::OnInfo(), PVR::CPVRGUIActionsTimers::ToggleTimerState(), and UpdateInfo().
HasVideoExtras()
bool CFileItem::HasVideoExtras () const
References GetVideoInfoTag(), CVideoInfoTag::HasVideoExtras(), and HasVideoInfoTag().
HasVideoInfoTag()
bool CFileItem::HasVideoInfoTag () const
References m_pvrRecordingInfoTag, and m_videoInfoTag.
Referenced by CVideoDatabase::AddFile(), UPNP::BuildObject(), CVideoTagLoaderPlugin::CVideoTagLoaderPlugin(), ADDON::DetailsFromFileItem< CVideoInfoTag >(), CVideoThumbLoader::DetectAndAddMissingItemData(), CSaveFileState::DoWork(), Exists(), CVideoThumbLoader::FillThumb(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), GetBaseMoviePath(), CGUIInfoManager::GetCurrentMovieTag(), CGUIWindowVideoNav::GetDirectory(), CVideoThumbLoader::GetEmbeddedThumbURL(), CVideoDatabase::GetFileId(), CDVDFileInfo::GetFileStreamDetails(), KODI::GUILIB::GUIINFO::CMusicGUIInfo::GetLabel(), KODI::ART::GetLocalFanart(), CMime::GetMimeType(), UPNP::GetMimeType(), GetMovieName(), CGUIDialogVideoInfo::GetMoviesForSet(), anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), CPlayerSelectionRule::GetPlayers(), GetResumePoint(), CGUIWindowVideoBase::GetScraperForItem(), CGUIDialogVideoInfo::GetSetForMovie(), CVideoDatabase::GetSetInfo(), CVideoDatabase::GetStreamDetails(), GetThumbHideIfUnwatched(), CUtil::GetVideoBasePathAndFileName(), GetVideoContentType(), KODI::UTILS::GUILIB::CGUIContentUtils::HasInfoForItem(), anonymous_namespace{ContentUtils.cpp}::HasPreferredArtType(), HasVideoExtras(), HasVideoVersions(), KODI::MUSIC::IsAudio(), KODI::VIDEO::UTILS::IsAutoPlayNextItem(), KODI::VIDEO::IsDiscStub(), IsGame(), KODI::VIDEO::UTILS::IsItemPlayable(), IsPicture(), IsResumable(), IsSamePath(), KODI::VIDEO::IsVideo(), CONTEXTMENU::CVideoInfo::IsVisible(), CONTEXTMENU::CVideoMarkWatched::IsVisible(), CONTEXTMENU::CVideoMarkUnWatched::IsVisible(), LoadDetails(), CMusicThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemCached(), CMusicThumbLoader::LoadItemLookup(), CVideoThumbLoader::LoadItemLookup(), MergeInfo(), CGUIWindowFullScreen::OnAction(), CGUIInfoManager::OnApplicationMessage(), CGUIWindowVideoBase::OnItemInfo(), CExecString::Parse(), ParseItem(), CApplication::PlayFile(), KODI::VIDEO::CVideoInfoScanner::ProcessItemByVideoInfoTag(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), UPNP::CMediaBrowser::SaveFileState(), CGUIDialogVideoInfo::SetMovie(), CGUIDialogVideoInfo::SetMovieSet(), CVideoDatabase::SetPlayCount(), KODI::VIDEO::anonymous_namespace{VideoGeneratedImageFileLoader.cpp}::SetupRarOptions(), KODI::UTILS::GUILIB::CGUIContentUtils::ShowInfoForItem(), ToSortable(), CVideoDatabase::UpdateFanart(), UpdateInfo(), and UPNP::CMediaBrowser::UpdateItem().
HasVideoVersions()
bool CFileItem::HasVideoVersions () const
References GetVideoInfoTag(), HasVideoInfoTag(), and CVideoInfoTag::HasVideoVersions().
Referenced by KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetLabel(), IsSamePath(), CONTEXTMENU::CVideoChooseVersion::IsVisible(), CONTEXTMENU::CVideoPlayVersionUsing::IsVisible(), and CONTEXTMENU::CVideoPlayUsing::IsVisible().
Initialize()
void CFileItem::Initialize () private
initialize all members of this class (not CGUIListItem members) to default values. Called from constructors, and from Reset()
See also
Reset, CGUIListItem
References LOCK_MODE_EVERYONE, LOCK_STATE_NO_LOCK, m_bCanQueue, m_bIsAlbum, m_bIsParentFolder, m_bIsShareOrDrive, m_bLabelPreformatted, m_doContentLookup, m_dwSize, m_gameInfoTag, m_iBadPwdCount, m_idepth, m_iDriveType, m_iHasLock, m_iLockMode, m_iprogramCount, m_lEndOffset, m_lStartOffset, m_lStartPartNumber, m_musicInfoTag, m_pictureInfoTag, m_specialSort, m_videoInfoTag, SortSpecialNone, and CMediaSource::SOURCE_TYPE_UNKNOWN.
Referenced by CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), and Reset().
IsAddonsPath()
bool CFileItem::IsAddonsPath () const
References URIUtils::IsAddonsPath(), and m_strPath.
Referenced by CGUIWindowMusicNav::GetDirectory(), KODI::ART::GetLocalFanart(), CProgramThumbLoader::GetLocalThumb(), GetUserMusicThumb(), CGUIViewState::GetViewState(), MUSIC_UTILS::IsItemPlayable(), KODI::VIDEO::UTILS::IsItemPlayable(), CExecString::Parse(), SkipLocalArt(), CGUIWindowVideoBase::StackingAvailable(), CGUIWindowMusicNav::UpdateButtons(), and CGUIWindowVideoNav::UpdateButtons().
IsAlbum()
bool CFileItem::IsAlbum () const
References m_bIsAlbum.
IsAndroidApp()
bool CFileItem::IsAndroidApp () const
References URIUtils::IsAndroidApp(), and m_strPath.
Referenced by CExecString::Parse().
IsAPK()
bool CFileItem::IsAPK () const
References URIUtils::IsAPK(), and m_strPath.
Referenced by IsFileFolder().
IsBluray()
bool CFileItem::IsBluray () const
References CFileItem(), KODI::VIDEO::UTILS::GetOpticalMediaPath(), URIUtils::IsBluray(), and m_strPath.
Referenced by CUtil::GetDVDDriveIcon().
IsCBR()
bool CFileItem::IsCBR () const
References URIUtils::HasExtension(), and m_strPath.
Referenced by KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetLabel(), CPictureInfoLoader::LoadItemCached(), CPictureThumbLoader::LoadItemCached(), CPictureInfoLoader::LoadItemLookup(), and CPictureThumbLoader::ProcessFoldersAndArchives().
IsCBZ()
bool CFileItem::IsCBZ () const
References URIUtils::HasExtension(), and m_strPath.
Referenced by KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetLabel(), CPictureInfoLoader::LoadItemCached(), CPictureThumbLoader::LoadItemCached(), CPictureInfoLoader::LoadItemLookup(), and CPictureThumbLoader::ProcessFoldersAndArchives().
IsDeleted()
bool CFileItem::IsDeleted () const
Check whether an item is 'deleted' (for example, a trashed pvr recording).
Returns
true if item is 'deleted', false otherwise.
References GetPVRRecordingInfoTag(), and HasPVRRecordingInfoTag().
Referenced by anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), KODI::VIDEO::UTILS::IsItemPlayable(), CONTEXTMENU::CVideoRemoveResumePoint::IsVisible(), CONTEXTMENU::CVideoMarkWatched::IsVisible(), CONTEXTMENU::CVideoMarkUnWatched::IsVisible(), and CONTEXTMENU::CVideoResume::IsVisible().
IsDeletedPVRRecording()
bool CFileItem::IsDeletedPVRRecording () const
References m_pvrRecordingInfoTag.
Referenced by KODI::ART::FillInDefaultIcon(), PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible(), and PVR::CPVRGUIActionsRecordings::UndeleteRecording().
IsDiscImage()
bool CFileItem::IsDiscImage () const
References GetDynPath(), and URIUtils::IsDiscImage().
Referenced by CDVDFileInfo::CanExtract(), XFILE::CFileDirectoryFactory::Create(), CDVDFactoryInputStream::CreateInputStream(), XFILE::CDirectory::FilterFileDirectories(), CPlayerSelectionRule::GetPlayers(), IsFileFolder(), CDVDInputStreamBluray::Open(), CDVDInputStreamNavigator::Open(), CApplicationPlayer::OpenFile(), CApplication::PlayFile(), and CGUIDialogSimpleMenu::ShowPlaySelection().
IsDVD()
bool CFileItem::IsDVD () const
References URIUtils::IsDVD(), m_iDriveType, m_strPath, and CMediaSource::SOURCE_TYPE_OPTICAL_DISC.
Referenced by CDVDFileInfo::CanExtract(), CFileItem(), KODI::VIDEO::UTILS::FindTrailer(), KODI::ART::GetLocalFanart(), anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), CPlayerSelectionRule::GetPlayers(), CGUIDialogContextMenu::GetShare(), KODI::VIDEO::UTILS::IsItemPlayable(), CONTEXTMENU::CEjectDisk::IsVisible(), CONTEXTMENU::CEjectDrive::IsVisible(), and SkipLocalArt().
IsEPG()
bool CFileItem::IsEPG () const
References HasEPGInfoTag().
Referenced by CFileItemList::AlwaysCache(), PVR::CPVRItem::GetChannel(), PVR::CPVRItem::GetEpgInfoTag(), PVR::CPVRGUIInfo::GetFallbackLabel(), PVR::CPVRGUIInfo::GetListItemAndPlayerBool(), PVR::CPVRGUIInfo::GetListItemAndPlayerInt(), PVR::CPVRGUIInfo::GetListItemAndPlayerLabel(), PVR::CPVRItem::GetNextEpgInfoTag(), PVR::CPVRGUIInfo::GetPVRInt(), PVR::CPVRGUIInfo::GetPVRLabel(), PVR::CPVRItem::GetRecording(), PVR::CPVRItem::GetTimerInfoTag(), KODI::VIDEO::UTILS::IsItemPlayable(), PVR::CPVRItem::IsRadio(), and PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible().
IsFavourite()
bool CFileItem::IsFavourite () const
References URIUtils::IsFavourite(), and m_strPath.
Referenced by KODI::ART::FillInDefaultIcon(), anonymous_namespace{ContextMenus.cpp}::IsActivateWindowFavourite(), anonymous_namespace{ContextMenus.cpp}::IsPlayMediaFavourite(), CExecString::Parse(), CFavouritesService::ResolveFavourite(), and ToSortable().
IsFileFolder()
bool CFileItem::IsFileFolder (EFileFolderType types = EFILEFOLDER_MASK_ALL) const
References EFILEFOLDER_TYPE_ALWAYS, EFILEFOLDER_TYPE_ONBROWSE, EFILEFOLDER_TYPE_ONCLICK, CServiceBroker::GetFileExtensionProvider(), CServiceBroker::GetSettingsComponent(), CServiceBroker::IsAddonInterfaceUp(), IsAPK(), KODI::MUSIC::IsAudioBook(), IsDiscImage(), KODI::NETWORK::IsInternetStream(), KODI::PLAYLIST::IsPlayList(), IsRAR(), IsRSS(), KODI::PLAYLIST::IsSmartPlayList(), IsType(), IsZIP(), m_strPath, and types.
Referenced by CFileItem(), CFileItem(), FindLocalArt(), CVideoThumbLoader::GetLocalArt(), KODI::ART::GetLocalArtBaseFilename(), GetLocalMetadataPath(), CLabelFormatter::GetMaskContent(), KODI::ART::GetTBNFile(), GetUserMusicThumb(), CONTEXTMENU::CMusicBrowse::IsVisible(), and CONTEXTMENU::CVideoBrowse::IsVisible().
IsFileItem()
bool CFileItem::IsFileItem () const inline override virtual
Reimplemented from CGUIListItem.
IsGame()
bool CFileItem::IsGame () const
References GetAddonInfo(), HasAddonInfo(), KODI::GAME::CGameUtils::HasGameExtension(), HasGameInfoTag(), HasMusicInfoTag(), HasPictureInfoTag(), HasVideoInfoTag(), IsPVR(), KODI::GAME::CGameUtils::IsStandaloneGame(), and m_strPath.
Referenced by CApplication::ExecuteXBMCAction(), CPlayerCoreFactory::GetPlayers(), CPlayerSelectionRule::GetPlayers(), KODI::GUILIB::GUIINFO::CGamesGUIInfo::InitCurrentItem(), and CGUIWindowFileManager::OnStart().
IsHD()
bool CFileItem::IsHD () const
References URIUtils::IsHD(), and m_strPath.
Referenced by KODI::CDRIP::CCDDARipper::CreateAlbumDir(), and CGUIWindowMusicBase::OnMessage().
IsInProgressPVRRecording()
bool CFileItem::IsInProgressPVRRecording () const
References m_pvrRecordingInfoTag.
Referenced by CSaveFileState::DoWork().
IsISO9660()
bool CFileItem::IsISO9660 () const
References URIUtils::IsISO9660(), and m_strPath.
IsLabelPreformatted()
bool CFileItem::IsLabelPreformatted () const inline
References m_bLabelPreformatted.
Referenced by GetMovieName().
IsLibraryFolder()
bool CFileItem::IsLibraryFolder () const
References CGUIListItem::GetProperty(), CGUIListItem::HasProperty(), URIUtils::IsLibraryFolder(), and m_strPath.
Referenced by CGUIWindowVideoNav::ApplyWatchedFilter(), CGUIViewStateMusicSmartPlaylist::CGUIViewStateMusicSmartPlaylist(), CGUIViewStateVideoEpisodes::CGUIViewStateVideoEpisodes(), CGUIViewStateVideoMovies::CGUIViewStateVideoMovies(), CGUIViewStateVideoMusicVideos::CGUIViewStateVideoMusicVideos(), CGUIViewStateVideoTVShows::CGUIViewStateVideoTVShows(), CGUIWindowMusicNav::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), GetUserMusicThumb(), CGUIViewState::GetViewState(), CGUIWindowVideoPlaylist::OnPrepareFileItems(), SkipLocalArt(), and CFileItemList::Stack().
IsLiveTV()
bool CFileItem::IsLiveTV () const
References URIUtils::IsLiveTV(), and m_strPath.
Referenced by CleanString(), CSaveFileState::DoWork(), KODI::ART::FillInDefaultIcon(), KODI::VIDEO::UTILS::FindTrailer(), CONTEXTMENU::CVideoPlay::GetLabel(), KODI::ART::GetLocalFanart(), anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), CGUIWindowVideoBase::GetScraperForItem(), KODI::VIDEO::UTILS::IsItemPlayable(), CONTEXTMENU::CVideoPlayUsing::IsVisible(), CUtil::ScanForExternalAudio(), SkipLocalArt(), and CFileItemList::Stack().
IsMultiPath()
bool CFileItem::IsMultiPath () const
References URIUtils::IsMultiPath(), and m_strPath.
Referenced by GetBaseMoviePath(), KODI::ART::GetFolderThumb(), KODI::ART::GetLocalArtBaseFilename(), CGUIDialogFileBrowser::OnMessage(), CGUIMediaWindow::OnMessage(), and CPictureThumbLoader::ProcessFoldersAndArchives().
IsNFO()
bool CFileItem::IsNFO () const
References URIUtils::HasExtension(), and m_strPath.
Referenced by anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), MUSIC_INFO::CMusicInfoLoader::LoadAdditionalTagInfo(), MUSIC_INFO::CMusicInfoLoader::LoadItemCached(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMovie(), and KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForMusicVideo().
IsNfs()
bool CFileItem::IsNfs () const
References URIUtils::IsNfs(), and m_strPath.
IsOnDVD()
bool CFileItem::IsOnDVD () const
References URIUtils::IsOnDVD(), m_iDriveType, m_strPath, and CMediaSource::SOURCE_TYPE_OPTICAL_DISC.
Referenced by CFileItemList::GetDiscFileCache(), CPlayerSelectionRule::GetPlayers(), and IsRemovable().
IsOpticalMediaFile()
bool CFileItem::IsOpticalMediaFile () const
Referenced by KODI::VIDEO::CVideoInfoScanner::EnumerateEpisodeItem(), CVideoDatabase::ExportToXML(), CVideoTagLoaderNFO::FindNFO(), GetBaseMoviePath(), CVideoThumbLoader::GetLocalArt(), KODI::ART::GetLocalArtBaseFilename(), KODI::ART::GetLocalFanart(), and CUtil::GetVideoBasePathAndFileName().
IsParentFolder()
bool CFileItem::IsParentFolder () const
References m_bIsParentFolder.
Referenced by CMusicFileItemListModifier::AddQueuingFolder(), PVR::CPVRGUIActionsRecordings::DeleteRecording(), PVR::CPVRGUIActionsRecordings::DeleteWatchedRecordings(), Exists(), KODI::ART::FillInDefaultIcon(), CGUIInfoManager::GetItemBool(), CFileItemList::GetObjectCount(), GetUserMusicThumb(), MUSIC_UTILS::IsItemPlayable(), CPlayerUtils::IsItemPlayable(), KODI::VIDEO::UTILS::IsItemPlayable(), IsReadOnly(), CONTEXTMENU::CAddRemoveFavourite::IsVisible(), CONTEXTMENU::CVideoMarkWatched::IsVisible(), CONTEXTMENU::CVideoMarkUnWatched::IsVisible(), CPictureThumbLoader::LoadItemCached(), CProgramThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemLookup(), CGUIWindowVideoNav::OnDeleteItem(), CGUIWindowVideoBase::OnItemInfo(), CPictureThumbLoader::ProcessFoldersAndArchives(), CGUIDialogMusicInfo::ShowFor(), and SkipLocalArt().
IsPath()
bool CFileItem::IsPath (const std::string & path, bool ignoreURLOptions = false) const
References m_strPath, and URIUtils::PathEquals().
Referenced by Exists(), KODI::GUILIB::GUIINFO::CPlayerGUIInfo::GetBool(), CGUIWindowMusicNav::GetContextButtons(), CGUIWindowVideoNav::GetContextButtons(), IsURL(), CONTEXTMENU::CAddRemoveFavourite::IsVisible(), CGUIWindowVideoBase::OnDeleteItem(), CGUIWindowVideoNav::OnDeleteItem(), CGUIWindowPictures::OnInitWindow(), CGUIWindowVideoBase::OnItemInfo(), CGUIWindowMusicBase::OnMessage(), CGUIWindowVideoBase::OnMessage(), CPictureThumbLoader::ProcessFoldersAndArchives(), CGUIMediaWindow::Update(), CGUIWindowMusicNav::UpdateButtons(), and CGUIWindowVideoNav::UpdateButtons().
IsPicture()
bool CFileItem::IsPicture () const
Check whether an item is a picture item. Note that this returns true for anything with a picture info tag, so that may include eg. folders.
Returns
true if item is picture, false otherwise.
References HasEPGInfoTag(), HasEPGSearchFilter(), HasGameInfoTag(), HasMusicInfoTag(), HasPictureInfoTag(), HasPVRChannelGroupMemberInfoTag(), HasPVRChannelInfoTag(), HasPVRProviderInfoTag(), HasPVRRecordingInfoTag(), HasPVRTimerInfoTag(), HasVideoInfoTag(), CUtil::IsPicture(), m_mimetype, and m_strPath.
Referenced by UPNP::BuildObject(), CGUIMultiImage::CMultiImageJob::DoWork(), KODI::ART::FillInDefaultIcon(), KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetLabel(), UPNP::GetMimeType(), anonymous_namespace{FavouritesService.cpp}::IsMediasourceOfFavItemUnlocked(), CGUIMultiImage::LoadDirectory(), CPictureInfoLoader::LoadItemCached(), CPictureThumbLoader::LoadItemCached(), CPictureInfoLoader::LoadItemLookup(), CGUIWindowFileManager::OnStart(), and CExecString::Parse().
IsPlugin()
bool CFileItem::IsPlugin () const
References URIUtils::IsPlugin(), and m_strPath.
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), KODI::VIDEO::CVideoInfoScanner::CanFastHash(), CGUIViewStateFromItems::CGUIViewStateFromItems(), KODI::VIDEO::CVideoInfoTagLoaderFactory::CreateLoader(), KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder(), Exists(), KODI::VIDEO::UTILS::FindTrailer(), CGUIWindowPictures::GetContextButtons(), KODI::GAME::CGUIWindowGames::GetDirectory(), CGUIWindowMusicNav::GetDirectory(), CGUIWindowPictures::GetDirectory(), KODI::ART::GetFolderThumb(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::ART::GetLocalFanart(), GetMovieName(), CVideoDatabase::GetPlayCounts(), CGUIWindowVideoBase::GetScraperForItem(), GetUserMusicThumb(), MUSIC_UTILS::IsItemPlayable(), CPlayerUtils::IsItemPlayable(), KODI::VIDEO::UTILS::IsItemPlayable(), CONTEXTMENU::CVideoMarkWatched::IsVisible(), CONTEXTMENU::CVideoMarkUnWatched::IsVisible(), CGUIWindowVideoBase::LoadVideoInfo(), CGUIMediaWindow::OnClick(), KODI::GAME::CGUIWindowGames::OnClickMsg(), CGUIWindowVideoBase::OnItemInfo(), CGUIWindowMusicBase::OnItemInfo(), CGUIWindowPrograms::OnItemInfo(), CGUIWindowPictures::OnItemInfo(), KODI::GAME::CGUIWindowGames::OnItemInfo(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), CPictureThumbLoader::ProcessFoldersAndArchives(), KODI::VIDEO::CVideoInfoScanner::ProcessItemByVideoInfoTag(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForEpisodes(), KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(), SkipLocalArt(), CGUIWindowVideoBase::StackingAvailable(), CGUIWindowMusicNav::UpdateButtons(), and CGUIWindowVideoNav::UpdateButtons().
IsPVR()
bool CFileItem::IsPVR () const
References URIUtils::IsPVR(), and m_strPath.
Referenced by Exists(), IsGame(), MUSIC_UTILS::IsItemPlayable(), KODI::VIDEO::IsVideo(), CApplication::PlayMedia(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), CUtil::ScanForExternalAudio(), and CUtil::ScanForExternalSubtitles().
IsPVRChannel()
bool CFileItem::IsPVRChannel () const
References HasPVRChannelInfoTag().
Referenced by KODI::ART::FillInDefaultIcon(), PVR::CPVRItem::GetChannel(), PVR::CPVRItem::GetEpgInfoTag(), PVR::CPVRGUIInfo::GetFallbackLabel(), PVR::CPVRGUIInfo::GetListItemAndPlayerBool(), PVR::CPVRGUIInfo::GetListItemAndPlayerInt(), PVR::CPVRGUIInfo::GetListItemAndPlayerLabel(), PVR::CPVRItem::GetNextEpgInfoTag(), PVR::CPVRGUIInfo::GetPVRInt(), PVR::CPVRGUIInfo::GetPVRLabel(), PVR::CPVRItem::GetTimerInfoTag(), PVR::CPVRItem::IsRadio(), PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible(), and CApplication::OnAction().
IsPVRChannelGroup()
bool CFileItem::IsPVRChannelGroup () const
References URIUtils::IsPVRChannelGroup(), and m_strPath.
Referenced by PVR::CPVRThumbLoader::FillThumb(), and PVR::CPVRGUIInfo::GetListItemAndPlayerLabel().
IsPVRProvider()
bool CFileItem::IsPVRProvider () const
References HasPVRProviderInfoTag().
Referenced by KODI::ART::FillInDefaultIcon().
IsPVRRecording()
bool CFileItem::IsPVRRecording () const
References HasPVRRecordingInfoTag().
Referenced by PVR::CPVRGUIActionsRecordings::DeleteRecording(), CSaveFileState::DoWork(), PVR::CPVRItem::GetChannel(), PVR::CPVRGUIInfo::GetListItemAndPlayerBool(), PVR::CPVRItem::GetRecording(), PVR::CPVRGUIActionsRecordings::IncrementPlayCount(), PVR::CPVRItem::IsRadio(), CONTEXTMENU::CVideoInfo::IsVisible(), PVR::CPVRGUIActionsRecordings::MarkWatched(), PVR::CPVRGUIActionsRecordings::ShowRecordingInfo(), and SkipLocalArt().
IsPVRTimer()
bool CFileItem::IsPVRTimer () const
References HasPVRTimerInfoTag().
Referenced by KODI::ART::FillInDefaultIcon(), PVR::CPVRItem::GetChannel(), PVR::CPVRItem::GetEpgInfoTag(), PVR::CPVRGUIInfo::GetFallbackLabel(), PVR::CPVRGUIInfo::GetListItemAndPlayerBool(), PVR::CPVRGUIInfo::GetListItemAndPlayerLabel(), PVR::CPVRItem::GetNextEpgInfoTag(), PVR::CPVRItem::GetTimerInfoTag(), PVR::CPVRItem::IsRadio(), and PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible().
IsPythonScript()
bool CFileItem::IsPythonScript () const
References URIUtils::HasExtension(), and m_strPath.
Referenced by CApplication::ExecuteXBMCAction(), KODI::ART::FillInDefaultIcon(), and CGUIWindowFileManager::OnStart().
IsRAR()
bool CFileItem::IsRAR () const
References URIUtils::IsRAR(), and m_strPath.
Referenced by KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetLabel(), IsFileFolder(), CPictureInfoLoader::LoadItemCached(), CPictureThumbLoader::LoadItemCached(), CPictureInfoLoader::LoadItemLookup(), and CFileItemList::StackFiles().
IsReadOnly()
bool CFileItem::IsReadOnly () const
References IsParentFolder(), m_bIsShareOrDrive, m_strPath, and CUtil::SupportsWriteFileOperations().
IsRemovable()
bool CFileItem::IsRemovable () const
References KODI::MUSIC::IsCDDA(), IsOnDVD(), m_iDriveType, and CMediaSource::SOURCE_TYPE_REMOVABLE.
Referenced by CONTEXTMENU::CEjectDisk::IsVisible(), CONTEXTMENU::CEjectDrive::IsVisible(), CGUIDialogFileBrowser::OnMessage(), and CGUIMediaWindow::OnMessage().
IsResumable()
bool CFileItem::IsResumable () const
Test if this item type can be resumed.
Returns
True if this item is a folder and has at least one child with a partway resume bookmark or at least one unwatched child or if it is not a folder, if it has a partway resume bookmark, false otherwise.
References CVariant::asInteger(), CGUIListItem::GetProperty(), CVideoInfoTag::GetResumePoint(), GetVideoInfoTag(), CGUIListItem::HasProperty(), HasVideoInfoTag(), int64_t(), CBookmark::IsPartWay(), and CGUIListItem::m_bIsFolder.
Referenced by KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetBool(), anonymous_namespace{VideoUtils.cpp}::GetFolderItemResumeInformation(), and CDVDInputStreamBluray::Open().
IsResumePointSet()
bool CFileItem::IsResumePointSet () const
Test if this item has a valid resume point set.
Returns
True if this item has a resume point and it is set, false otherwise.
References GetResumePoint(), and CBookmark::IsSet().
Referenced by CApplication::PlayFile().
IsRSS()
bool CFileItem::IsRSS () const
References URIUtils::HasExtension(), m_mimetype, and m_strPath.
Referenced by CFileItem(), XFILE::CFileDirectoryFactory::Create(), CGUIWindowVideoBase::GetScraperForItem(), IsFileFolder(), and CGUIWindowVideoBase::StackingAvailable().
IsSamePath()
bool CFileItem::IsSamePath (const CFileItem * item) const
References MUSIC_INFO::CMusicInfoTag::GetDatabaseId(), GetDynPath(), GetMusicInfoTag(), GetPath(), CGUIListItem::GetProperty(), MUSIC_INFO::CMusicInfoTag::GetType(), MUSIC_INFO::CMusicInfoTag::GetURL(), GetVideoInfoTag(), HasMusicInfoTag(), CGUIListItem::HasProperty(), HasVideoInfoTag(), HasVideoVersions(), KODI::MUSIC::IsMusicDb(), IsSamePath(), CVideoInfoTag::m_iFileId, m_musicInfoTag, CVideoInfoTag::m_strFileNameAndPath, m_strPath, and CGUIListItem::SetProperty().
Referenced by IsSamePath().
IsScript()
bool CFileItem::IsScript () const
References URIUtils::IsScript(), and m_strPath.
Referenced by MUSIC_UTILS::IsItemPlayable(), KODI::VIDEO::UTILS::IsItemPlayable(), CGUIWindowVideoBase::OnItemInfo(), CExecString::Parse(), CGUIWindowMusicNav::UpdateButtons(), and CGUIWindowVideoNav::UpdateButtons().
IsSmb()
bool CFileItem::IsSmb () const
References URIUtils::IsSmb(), and m_strPath.
Referenced by KODI::CDRIP::CCDDARipper::CreateAlbumDir(), and CGUIWindowVideoBase::OnSearchItemFound().
IsSourcesPath()
bool CFileItem::IsSourcesPath () const
References URIUtils::IsSourcesPath(), and m_strPath.
Referenced by KODI::GAME::CGUIWindowGames::GetContextButtons(), CGUIWindowMusicNav::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::GAME::CGUIWindowGames::OnContextButton(), CGUIMediaWindow::OnMessage(), CGUIWindowVideoPlaylist::OnPrepareFileItems(), and CFileItemList::Stack().
IsStack()
bool CFileItem::IsStack () const
References GetDynPath(), and URIUtils::IsStack().
Referenced by CVideoTagLoaderFFmpeg::CVideoTagLoaderFFmpeg(), CVideoTagLoaderNFO::FindNFO(), KODI::VIDEO::UTILS::FindTrailer(), CGUIWindowVideoBase::GetDirectory(), KODI::ART::GetFolderThumb(), KODI::ART::GetLocalArtBaseFilename(), KODI::ART::GetLocalFanart(), KODI::VIDEO::UTILS::GetStackPartResumeInformation(), KODI::ART::GetTBNFile(), CApplicationStackHelper::InitializeStack(), and CApplication::PlayFile().
IsType()
bool CFileItem::IsType (const char * ext) const
References URIUtils::HasExtension(), m_strDynPath, and m_strPath.
Referenced by KODI::PLAYLIST::CPlayListFactory::Create(), CDVDFactoryInputStream::CreateInputStream(), anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), CVideoTagLoaderFFmpeg::HasInfo(), KODI::MUSIC::IsAudioBook(), IsFileFolder(), KODI::PLAYLIST::CPlayListFactory::IsPlaylist(), CVideoTagLoaderFFmpeg::Load(), and CGUIWindowFileManager::OnStart().
IsURL() [1/2]
bool CFileItem::IsURL () const
References URIUtils::IsURL(), and m_strPath.
IsURL() [2/2]
bool CFileItem::IsURL (const CURL & url) const
References CURL::Get(), and IsPath().
Referenced by XFILE::CDAVDirectory::GetDirectory().
IsUsablePVRRecording()
bool CFileItem::IsUsablePVRRecording () const
References m_pvrRecordingInfoTag.
Referenced by KODI::ART::FillInDefaultIcon(), PVR::CONTEXTMENUITEM::PVRClientMenuHook::IsVisible(), CONTEXTMENU::CVideoPlayAndQueue::IsVisible(), and PVR::CGUIWindowPVRSearchBase::SetItemToSearch().
IsVirtualDirectoryRoot()
bool CFileItem::IsVirtualDirectoryRoot () const
References CGUIListItem::m_bIsFolder, and m_strPath.
Referenced by KODI::GAME::CGUIViewStateWindowGames::CGUIViewStateWindowGames(), CGUIViewStateWindowMusicNav::CGUIViewStateWindowMusicNav(), CGUIViewStateWindowPictures::CGUIViewStateWindowPictures(), CGUIViewStateWindowVideoNav::CGUIViewStateWindowVideoNav(), Exists(), CGUIDialogFileBrowser::FrameMove(), KODI::GAME::CGUIWindowGames::GetContextButtons(), CGUIWindowPictures::GetContextButtons(), CGUIWindowPrograms::GetContextButtons(), CGUIWindowVideoNav::GetContextButtons(), KODI::GAME::CGUIWindowGames::GetDirectory(), CGUIWindowMusicNav::GetDirectory(), CGUIWindowPictures::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), CGUIMediaWindow::GoParentFolder(), CGUIDialogFileBrowser::OnBack(), CGUIMediaWindow::OnBack(), KODI::GAME::CGUIWindowGames::OnContextButton(), CGUIDialogFileBrowser::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIWindowVideoPlaylist::OnPrepareFileItems(), CGUIWindowMusicNav::OnSearchUpdate(), CGUIWindowMusicPlaylistEditor::OnSourcesContext(), CGUIWindowMusicNav::PlayItem(), CGUIWindowMusicPlaylistEditor::PlayItem(), CFileItemList::Stack(), and CGUIWindowMusicBase::UpdateButtons().
IsZIP()
bool CFileItem::IsZIP () const
References URIUtils::IsZIP(), and m_strPath.
Referenced by KODI::GUILIB::GUIINFO::CPicturesGUIInfo::GetLabel(), IsFileFolder(), CPictureInfoLoader::LoadItemCached(), CPictureThumbLoader::LoadItemCached(), and CPictureInfoLoader::LoadItemLookup().
LoadDetails()
bool CFileItem::LoadDetails ()
Load detailed data for an item constructed with only a path and a folder flag Fills item's video info tag, sets item properties.
Returns
true on success, false otherwise.
Todo:
add support for other types on demand.
References XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetDatabaseInfo(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetMovieId(), CVideoDatabase::GetMovieInfo(), CVideoDatabase::GetMusicVideoInfo(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetMVideoId(), GetPath(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetVideoVersionId(), HasVideoInfoTag(), LOGERROR, and CVideoDatabase::Open().
Referenced by anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia().
LoadEmbeddedCue()
void CFileItem::LoadEmbeddedCue ()
References GetMusicInfoTag(), GetPath(), and SetCueDocument().
LoadGameTag()
bool CFileItem::LoadGameTag ()
Todo:
References GetGameInfoTag(), HasGameInfoTag(), KODI::GAME::CGameInfoTag::IsLoaded(), m_gameInfoTag, and KODI::GAME::CGameInfoTag::SetLoaded().
Referenced by KODI::GUILIB::GUIINFO::CGamesGUIInfo::InitCurrentItem().
LoadMusicTag()
bool CFileItem::LoadMusicTag ()
References CDatabase::Close(), MUSIC_INFO::CMusicInfoTagLoaderFactory::CreateLoader(), CLabelFormatter::FillMusicTag(), g_localizeStrings, CLocalizeStrings::Get(), URIUtils::GetFileName(), GetMusicInfoTag(), CServiceBroker::GetSettingsComponent(), CMusicDatabase::GetSongByFileName(), MUSIC_INFO::CMusicInfoTag::GetTrackNumber(), HasMusicInfoTag(), KODI::MUSIC::IsAudio(), KODI::MUSIC::IsCDDA(), MUSIC_INFO::CMusicInfoTag::Loaded(), CLog::Log(), LOGDEBUG, m_musicInfoTag, m_strPath, CMusicDatabase::Open(), URIUtils::RemoveExtension(), MUSIC_INFO::CMusicInfoTag::SetLoaded(), MUSIC_INFO::CMusicInfoTag::SetSong(), and MUSIC_INFO::CMusicInfoTag::SetTitle().
Referenced by KODI::GUILIB::GUIINFO::CMusicGUIInfo::InitCurrentItem(), and CGUIDialogSongInfo::ShowFor().
LoadTracksFromCueDocument()
bool CFileItem::LoadTracksFromCueDocument (CFileItemList & scannedItems)
References m_cueDocument.
MergeInfo()
void CFileItem::MergeInfo (const CFileItem & item)
Merge an item with information from another item We take metadata/art information from the given item and supplement the current item with that info. If tags exist in the new item we only merge the missing tag information. Properties are appended, and labels are updated if non-empty in the given item.
References CGUIListItem::AppendArt(), CGUIListItem::AppendProperties(), CGUIListItem::GetArt(), GetDynPath(), GetGameInfoTag(), CGUIListItem::GetLabel(), CGUIListItem::GetLabel2(), GetMusicInfoTag(), GetPictureInfoTag(), GetPVRChannelGroupMemberInfoTag(), GetVideoInfoTag(), HasEPGInfoTag(), HasEPGSearchFilter(), HasGameInfoTag(), HasMusicInfoTag(), HasPictureInfoTag(), HasPVRChannelGroupMemberInfoTag(), HasPVRProviderInfoTag(), HasPVRTimerInfoTag(), HasVideoInfoTag(), CGUIListItem::ICON_OVERLAY_UNWATCHED, CGUIListItem::ICON_OVERLAY_WATCHED, m_doContentLookup, m_epgInfoTag, m_epgSearchFilter, m_mimetype, m_pvrChannelGroupMemberInfoTag, m_pvrProviderInfoTag, m_pvrRecordingInfoTag, m_pvrTimerInfoTag, m_videoInfoTag, CVideoInfoTag::Merge(), CGUIListItem::SetArt(), SetContentLookup(), SetDynPath(), CGUIListItem::SetInvalid(), SetLabel(), CGUIListItem::SetLabel2(), SetMimeType(), CGUIListItem::SetOverlayImage(), and UpdateMimeType().
Referenced by XFILE::CPluginDirectory::GetPluginResult().
operator=()
CFileItem & CFileItem::operator= (const CFileItem & item)
References CGUIListItem::FreeMemory(), m_addonInfo, m_bCanQueue, m_bIsAlbum, m_bIsParentFolder, m_bIsShareOrDrive, m_bLabelPreformatted, m_dateTime, m_doContentLookup, m_dwSize, m_epgInfoTag, m_epgSearchFilter, m_eventLogEntry, m_extrainfo, m_gameInfoTag, m_iBadPwdCount, m_idepth, m_iDriveType, m_iHasLock, m_iLockMode, m_iprogramCount, m_lEndOffset, m_lStartOffset, m_lStartPartNumber, m_mimetype, m_musicInfoTag, m_pictureInfoTag, m_pvrChannelGroupMemberInfoTag, m_pvrProviderInfoTag, m_pvrRecordingInfoTag, m_pvrTimerInfoTag, m_specialSort, m_strDVDLabel, m_strDynPath, m_strLockCode, m_strPath, m_strTitle, m_videoInfoTag, and CGUIListItem::operator=().
RemoveExtension()
void CFileItem::RemoveExtension ()
References CGUIListItem::GetLabel(), CGUIListItem::m_bIsFolder, URIUtils::RemoveExtension(), and SetLabel().
Referenced by CLabelFormatter::FormatLabel(), CFileItemList::RemoveExtensions(), and CGUIDialogVisualisationPresetList::SetVisualisation().
Reset()
void CFileItem::Reset ()
reset class to it's default values as per construction. Free's all allocated memory.
See also
Initialize
References CGUIListItem::ClearProperties(), CGUIListItem::FreeIcons(), CGUIListItem::ICON_OVERLAY_NONE, Initialize(), CGUIListItem::m_bIsFolder, CGUIListItem::m_bSelected, m_dateTime, m_epgInfoTag, m_epgSearchFilter, m_eventLogEntry, m_extrainfo, m_gameInfoTag, m_mimetype, m_musicInfoTag, CGUIListItem::m_overlayIcon, m_pictureInfoTag, m_pvrChannelGroupMemberInfoTag, m_pvrProviderInfoTag, m_pvrRecordingInfoTag, m_pvrTimerInfoTag, m_strDVDLabel, m_strDynPath, CGUIListItem::m_strLabel2, m_strLockCode, m_strPath, m_strTitle, m_videoInfoTag, CDateTime::Reset(), CGUIListItem::SetInvalid(), and SetLabel().
Referenced by CGUIInfoManager::ResetCurrentItem().
Serialize()
void CFileItem::Serialize (CVariant & value) const override virtual
Implements ISerializable.
References CDateTime::GetAsDBDateTime(), CDateTime::GetAsRFC1123DateTime(), CDateTime::IsValid(), m_dateTime, m_dwSize, m_extrainfo, m_gameInfoTag, CGUIListItem::m_mapProperties, m_mimetype, m_musicInfoTag, m_pictureInfoTag, m_strDVDLabel, m_strPath, m_strTitle, m_videoInfoTag, and value.
SetCanQueue()
void CFileItem::SetCanQueue (bool bYesNo)
References m_bCanQueue.
SetContentLookup()
void CFileItem::SetContentLookup (bool enable) inline
Lookup via HTTP HEAD request might not be needed, use this setter to disable ContentLookup.
References m_doContentLookup.
Referenced by XFILE::CPluginDirectory::GetPluginResult(), MergeInfo(), CDVDDemuxVobsub::Open(), CDVDSubtitleStream::Open(), and UpdateInfo().
SetCueDocument()
void CFileItem::SetCueDocument (const CCueDocumentPtr & cuePtr)
References m_cueDocument.
Referenced by LoadEmbeddedCue().
SetDynPath()
void CFileItem::SetDynPath (const std::string & path)
References m_strDynPath.
Referenced by CDVDFactoryInputStream::CreateInputStream(), CVideoDatabase::FillMovieItem(), CMusicDatabase::GetFileItemFromDataset(), XFILE::CPluginDirectory::GetPluginResult(), UPNP::GetResource(), MergeInfo(), XFILE::CDVDDirectory::Resolve(), XFILE::CISO9660Directory::Resolve(), SetFromMusicInfoTag(), CGUIDialogSimpleMenu::ShowPlaySelection(), CGUIDialogSimpleMenu::ShowPlaySelection(), and UpdateInfo().
SetDynURL()
void CFileItem::SetDynURL (const CURL & url)
References CURL::Get(), and m_strDynPath.
SetEndOffset()
void CFileItem::SetEndOffset (const int64_t offset) inline
Set the end offset.
Parameters
offset Set the offset as ms.
References m_lEndOffset.
Referenced by CMusicDatabase::GetFileItemFromDataset(), and CApplicationStackHelper::InitializeStackStartPartAndOffset().
SetExtraInfo()
void CFileItem::SetExtraInfo (const std::string & info) inline
References m_extrainfo.
SetFileSizeLabel()
void CFileItem::SetFileSizeLabel ()
References CGUIListItem::m_bIsFolder, m_dwSize, and CGUIListItem::SetLabel2().
SetFromAlbum()
void CFileItem::SetFromAlbum (const CAlbum & album)
Sets details using the information from the CAlbum object Sets the album in the music info tag and uses its information to set the label and album-specific properties.
Parameters
album album details to use and set
References CAlbum::art, FillInMimeType(), CAlbum::GetAlbumArtistString(), GetMusicInfoTag(), m_bIsAlbum, CGUIListItem::m_bIsFolder, CGUIListItem::m_strLabel2, MUSIC_INFO::CMusicInfoTag::SetAlbum(), CGUIListItem::SetArt(), SetLabel(), CMusicDatabase::SetPropertiesFromAlbum(), and CAlbum::strAlbum.
Referenced by CFileItem(), and CFileItem().
SetFromMusicInfoTag()
void CFileItem::SetFromMusicInfoTag (const MUSIC_INFO::CMusicInfoTag & music)
Sets details using the information from the CMusicInfoTag object Sets the musicinfotag and uses its information to set the label and path.
Parameters
music music details to use and set
References KODI::ART::FillInDefaultIcon(), FillInMimeType(), CGUIListItem::GetArt(), CGUIListItem::GetLabel(), GetMusicInfoTag(), GetPath(), MUSIC_INFO::CMusicInfoTag::GetStationArt(), MUSIC_INFO::CMusicInfoTag::GetTitle(), MUSIC_INFO::CMusicInfoTag::GetURL(), label, m_strDynPath, CGUIListItem::SetArt(), SetDynPath(), SetLabel(), and SetPath().
Referenced by CGUIInfoManager::SetCurrentSongTag(), and CGUIDialogMusicInfo::ShowFor().
SetFromSong()
void CFileItem::SetFromSong (const CSong & song)
Sets details using the information from the CSong object Sets the song in the music info tag and uses its information to set the label, path, song-specific properties and artwork.
Parameters
song song details to use and set
References FillInMimeType(), URIUtils::GetExtension(), GetMusicInfoTag(), CSong::idSong, CSong::iEndOffset, CSong::iStartOffset, m_lEndOffset, m_lStartOffset, m_lStartPartNumber, m_strPath, CGUIListItem::SetArt(), SetLabel(), CGUIListItem::SetProperty(), MUSIC_INFO::CMusicInfoTag::SetSong(), CSong::strFileName, CSong::strThumb, and CSong::strTitle.
Referenced by CFileItem(), and CFileItem().
SetFromVideoInfoTag()
void CFileItem::SetFromVideoInfoTag (const CVideoInfoTag & video)
Sets details using the information from the CVideoInfoTag object Sets the videoinfotag and uses its information to set the label and path.
Parameters
video video details to use and set
References URIUtils::AddSlashAtEnd(), KODI::ART::FillInDefaultIcon(), FillInMimeType(), CGUIListItem::m_bIsFolder, CVideoInfoTag::m_iSeason, CVideoInfoTag::m_strFileNameAndPath, m_strPath, CVideoInfoTag::m_strPath, CVideoInfoTag::m_strTitle, m_videoInfoTag, SetLabel(), and CGUIListItem::SetProperty().
Referenced by CFileItem(), CVideoDatabase::FillMovieItem(), CVideoDatabase::GetDefaultVideoVersion(), CVideoDatabase::GetDetailsByTypeAndId(), CVideoDatabase::GetMusicVideoAlbumsNav(), UPNP::CUPnPServer::OnUpdateObject(), and CGUIInfoManager::SetCurrentVideoTag().
SetLabel()
void CFileItem::SetLabel (const std::string & strLabel) override virtual
Reimplemented from CGUIListItem.
References CGUIListItem::m_bIsFolder, m_bIsParentFolder, m_specialSort, CGUIListItem::SetLabel(), SetLabelPreformatted(), and SortSpecialOnTop.
Referenced by JSONRPC::CFavouritesOperations::AddFavourite(), CFileItemList::Assign(), XFILE::Browse(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CGUIStaticItem::CGUIStaticItem(), FAVOURITES_UTILS::ChooseAndSetNewName(), CleanString(), XFILE::CFileDirectoryFactory::Create(), CGUIDialogVideoInfo::DoSearch(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), CDirectoryJob::DoWork(), CVideoDatabase::ExportActorThumbs(), CLabelFormatter::FormatLabel(), XFILE::CAddonsDirectory::GenerateAddonListing(), XFILE::GenerateCategoryListing(), CVideoDatabase::GetDefaultVideoVersion(), XFILE::CDAVDirectory::GetDirectory(), XFILE::CLibraryDirectory::GetDirectory(), XFILE::CMusicDatabaseDirectory::GetDirectory(), XFILE::CMusicSearchDirectory::GetDirectory(), XFILE::CVideoDatabaseDirectory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), KODI::GAME::CGUIWindowGames::GetDirectory(), CGUIWindowMusicBase::GetDirectory(), CGUIWindowPictures::GetDirectory(), CGUIWindowVideoNav::GetDirectory(), CMusicDatabase::GetFileItemFromDataset(), CVideoDatabase::GetMusicVideoAlbumsNav(), KODI::RETRO::CSavestateDatabase::GetSavestateItem(), XFILE::CAddonsDirectory::GetScriptsAndPlugins(), KODI::CDRIP::CCDDARipper::GetTrackName(), MergeInfo(), CGUIWindowMusicPlayList::OnItemLoaded(), CGUIWindowVideoPlaylist::OnPrepareFileItems(), ParseItem(), XFILE::CDAVDirectory::ParseResponse(), RemoveExtension(), XFILE::Repos(), Reset(), XFILE::RootDirectory(), SetFromAlbum(), SetFromMusicInfoTag(), SetFromSong(), SetFromVideoInfoTag(), CGUIDialogAddonSettings::ShowForMultipleInstances(), TEST_P(), CGUIMediaWindow::Update(), UpdateInfo(), CGUIStaticItem::UpdateProperties(), CGUIWindowVideoBase::UpdateVideoVersionItemsLabel(), and XFILE::UserInstalledAddons().
SetLabelPreformatted()
void CFileItem::SetLabelPreformatted (bool bYesNo) inline
References m_bLabelPreformatted.
Referenced by CFileItem(), XFILE::CFileDirectoryFactory::Create(), PVR::CPVRGUIDirectory::GetRecordingsDirectoryInfo(), and SetLabel().
SetMimeType()
void CFileItem::SetMimeType (const std::string & mimetype) inline
References m_mimetype.
Referenced by CAirTunesServer::AudioOutputFunctions::audio_init(), AudioClassifyTest::AudioClassifyTest(), XFILE::CPluginDirectory::GetPluginResult(), UPNP::GetResource(), VideoPlayerCodec::Init(), MergeInfo(), CDVDInputStreamNavigator::Open(), CDVDDemuxVobsub::Open(), ParseItem(), ParseItemBoxee(), PlayListClassifyTest::PlayListClassifyTest(), SetMimeTypeForInternetFile(), UpdateInfo(), and VideoClassifyTest::VideoClassifyTest().
SetMimeTypeForInternetFile()
void CFileItem::SetMimeTypeForInternetFile ()
(Re)set the mime-type for internet files if allowed (m_doContentLookup) Some sources do not support HTTP HEAD request to determine i.e. mime type
References FillInMimeType(), KODI::NETWORK::IsInternetStream(), m_doContentLookup, and SetMimeType().
Referenced by CDVDFileInfo::ExtractThumbToTexture(), CDVDFileInfo::GetFileStreamDetails(), VideoPlayerCodec::Init(), CInputStreamMultiSource::Open(), CVideoPlayer::OpenFile(), and CVideoPlayer::Process().
SetPath()
void CFileItem::SetPath (const std::string & path) inline
References m_strPath.
Referenced by CFileItemList::Assign(), CAirTunesServer::AudioOutputFunctions::audio_init(), XFILE::Browse(), CGUIMediaWindow::CGUIMediaWindow(), CGUIWindowFileManager::CGUIWindowFileManager(), CGUIWindowMusicNav::CGUIWindowMusicNav(), ADDON::CVFSEntry::ContainsFiles(), XFILE::CFileDirectoryFactory::Create(), KODI::VIDEO::CVideoInfoScanner::DoScan(), CSaveFileState::DoWork(), CVideoDatabase::ExportToXML(), CVideoDatabase::FillMovieItem(), CVideoTagLoaderNFO::FindNFO(), CGUIMediaWindow::GetAdvanceFilteredItems(), XFILE::CAddonsDirectory::GetDirectory(), XFILE::CDAVDirectory::GetDirectory(), XFILE::CLibraryDirectory::GetDirectory(), XFILE::CMusicDatabaseDirectory::GetDirectory(), XFILE::CResourceDirectory::GetDirectory(), XFILE::CRSSDirectory::GetDirectory(), XFILE::CSpecialProtocolDirectory::GetDirectory(), XFILE::CVideoDatabaseDirectory::GetDirectory(), XFILE::CVirtualDirectory::GetDirectory(), XFILE::CDirectory::GetDirectory(), XFILE::CSmartPlaylistDirectory::GetDirectory(), JSONRPC::CFileOperations::GetDirectory(), CGUIWindowMusicPlaylistEditor::GetDirectory(), CMusicDatabase::GetFileItemFromDataset(), URIUtils::GetParentPath(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::GetPlayers(), JSONRPC::CFileOperations::GetRootDirectory(), KODI::RETRO::CSavestateDatabase::GetSavestateItem(), XFILE::CAddonsDirectory::GetSearchResults(), CGUIWindowMusicNav::GetSongsFromPlayList(), CURL::GetWithoutUserDetails(), CVideoDatabase::ImportFromXML(), PVR::CGUIWindowPVRBase::InitChannelGroup(), XBMCAddon::xbmc::PlayList::load(), UPNP::CUPnPServer::OnBrowseDirectChildren(), CDirectoryProvider::OnClick(), PVR::CGUIWindowPVRRecordingsBase::OnDeinitWindow(), CGUIWindowVideoBase::OnItemInfo(), MUSIC_INFO::CMusicInfoLoader::OnLoaderStart(), CPictureInfoLoader::OnLoaderStart(), CGUIDialogFileBrowser::OnMessage(), CGUIWindowMusicNav::OnMessage(), CGUIWindowMusicPlayList::OnMessage(), CGUIWindowMusicPlaylistEditor::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIWindowVideoPlaylist::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIWindowFileManager::OnMessage(), CXBMCApp::onNewIntent(), KODI::VIDEO::CVideoInfoScanner::OnProcessSeriesFolder(), UPNP::CUPnPServer::OnSearchContainer(), UPNP::CUPnPServer::OnUpdateObject(), ParseItem(), XFILE::CDAVDirectory::ParseResponse(), RunPlugin(), SetFromMusicInfoTag(), CGUIWindowFileManager::SetInitialPath(), CVideoDatabase::SetPlayCount(), KODI::VIDEO::anonymous_namespace{VideoGeneratedImageFileLoader.cpp}::SetupRarOptions(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_P(), TEST_P(), CGUIDialogFileBrowser::Update(), CGUIWindowFileManager::Update(), KODI::PLAYLIST::CPlayList::UpdateItem(), and CVideoLibraryRefreshingJob::Work().
SetSpecialSort()
void CFileItem::SetSpecialSort (SortSpecial sort) inline
References m_specialSort.
SetStartOffset()
void CFileItem::SetStartOffset (const int64_t offset) inline
Set the offset where start the playback.
Parameters
offset Set the offset value as ms, or the special value STARTOFFSET_RESUME.
References m_lStartOffset.
Referenced by CMusicDatabase::GetFileItemFromDataset(), XFILE::CPluginDirectory::GetPluginResult(), CApplication::OnAction(), CApplication::PlayFile(), anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia(), CApplication::PlayStack(), CApplication::SeekTime(), CGUIInfoManager::SetCurrentSongTag(), and CGUIInfoManager::SetCurrentVideoTag().
SetURL()
void CFileItem::SetURL (const CURL & url)
Todo:
Ideally this (and SetPath) would not be available outside of construction for CFileItem objects, or at least restricted to essentially be equivalent to construction. This would require re-formulating a bunch of CFileItem construction, and also allowing CFileItemList to have its own (public) SetURL() function, so for now we give direct access.
References CURL::Get(), and m_strPath.
Referenced by XFILE::CFileDirectoryFactory::Create(), XFILE::CMusicSearchDirectory::GetDirectory(), XFILE::CResourceDirectory::GetDirectory(), XFILE::CSpecialProtocolDirectory::GetDirectory(), and XFILE::CDirectory::GetDirectory().
SkipLocalArt()
bool CFileItem::SkipLocalArt () const
Whether or not to skip searching for local art.
Returns
true if local art should be skipped for this item, false otherwise.
See also
GetLocalArt, FindLocalArt
References CServiceBroker::GetSettingsComponent(), IsAddonsPath(), IsDVD(), URIUtils::IsFTP(), KODI::NETWORK::IsInternetStream(), IsLibraryFolder(), IsLiveTV(), IsParentFolder(), IsPlugin(), IsPVRRecording(), URIUtils::IsUPnP(), m_bIsShareOrDrive, and m_strPath.
Referenced by FindLocalArt(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), and CVideoThumbLoader::GetLocalArt().
SortsOnBottom()
bool CFileItem::SortsOnBottom () const inline
References m_specialSort, and SortSpecialOnBottom.
SortsOnTop()
bool CFileItem::SortsOnTop () const inline
References m_specialSort, and SortSpecialOnTop.
ToSortable() [1/2]
void CFileItem::ToSortable (SortItem & sortable, const Fields & fields) const
References FieldFolder, FieldLabel, KODI::PLAYLIST::fields, FieldSortSpecial, CGUIListItem::GetLabel(), CGUIListItem::m_bIsFolder, m_specialSort, and ToSortable().
ToSortable() [2/2]
void CFileItem::ToSortable (SortItem & sortable, Field field) const override virtual
Implements ISortable.
References CVariant::asString(), FieldBitrate, FieldDate, FieldDriveType, FieldEndOffset, FieldInstallDate, FieldLastUpdated, FieldLastUsed, FieldPath, FieldProgramCount, FieldSize, FieldStartOffset, FieldTitle, FieldUserPreference, GetAddonInfo(), CDateTime::GetAsDBDateTime(), GetGameInfoTag(), GetMusicInfoTag(), GetPictureInfoTag(), CGUIListItem::GetProperty(), GetPVRChannelGroupMemberInfoTag(), GetPVRChannelInfoTag(), GetPVRProviderInfoTag(), GetVideoInfoTag(), HasAddonInfo(), HasGameInfoTag(), HasMusicInfoTag(), HasPictureInfoTag(), HasPVRChannelGroupMemberInfoTag(), HasPVRChannelInfoTag(), HasPVRProviderInfoTag(), HasVideoInfoTag(), IsFavourite(), CDateTime::IsValid(), m_dateTime, m_dwSize, m_eventLogEntry, m_iDriveType, m_iprogramCount, m_lEndOffset, m_lStartOffset, m_strPath, m_strTitle, KODI::GAME::CGameInfoTag::ToSortable(), MUSIC_INFO::CMusicInfoTag::ToSortable(), CPictureInfoTag::ToSortable(), and CVideoInfoTag::ToSortable().
Referenced by ToSortable().
UpdateInfo()
void CFileItem::UpdateInfo (const CFileItem & item, bool replaceLabels = true)
Update an item with information from another item We take metadata information from the given item and supplement the current item with that info. If tags exist in the new item we use the entire tag information. Properties are appended, and labels, thumbnail and icon are updated if non-empty in the given item.
Parameters
item the item used to supplement information
replaceLabels whether to replace labels (defaults to true)
Todo:
premiered info is normally stored in m_dateTime by the db
References CGUIListItem::AppendProperties(), CGUIListItem::GetArt(), GetDynPath(), GetGameInfoTag(), CGUIListItem::GetLabel(), CGUIListItem::GetLabel2(), GetMusicInfoTag(), GetPictureInfoTag(), GetPVRChannelGroupMemberInfoTag(), GetVideoInfoTag(), HasEPGInfoTag(), HasEPGSearchFilter(), HasGameInfoTag(), HasMusicInfoTag(), HasPictureInfoTag(), HasPVRChannelGroupMemberInfoTag(), HasPVRProviderInfoTag(), HasPVRTimerInfoTag(), HasVideoInfoTag(), CGUIListItem::ICON_OVERLAY_UNWATCHED, CGUIListItem::ICON_OVERLAY_WATCHED, m_doContentLookup, m_epgInfoTag, m_epgSearchFilter, m_mimetype, m_pvrChannelGroupMemberInfoTag, m_pvrProviderInfoTag, m_pvrRecordingInfoTag, m_pvrTimerInfoTag, m_videoInfoTag, CGUIListItem::SetArt(), SetContentLookup(), SetDynPath(), CGUIListItem::SetInvalid(), SetLabel(), CGUIListItem::SetLabel2(), SetMimeType(), CGUIListItem::SetOverlayImage(), and UpdateMimeType().
Referenced by XFILE::CPluginDirectory::GetPluginResult(), CApplication::OnApplicationMessage(), and CGUIInfoManager::UpdateCurrentItem().
UpdateMimeType()
void CFileItem::UpdateMimeType (bool lookup = true) private
Recalculate item's MIME type if it is not set or is set to "application/octet-stream". Resolve the MIME type based on file extension or a web lookup.
See also
FillInMimeType
Todo:
application/octet-stream might actually have been set by a web lookup. Currently we cannot distinguish between set as fallback only (see FillInMimeType) or as an actual value.
References FillInMimeType(), and m_mimetype.
Referenced by MergeInfo(), and UpdateInfo().
Member Data Documentation
m_addonInfo
std::shared_ptr<const ADDON::IAddon> CFileItem::m_addonInfo private
Referenced by GetAddonInfo(), HasAddonInfo(), and operator=().
m_bCanQueue
bool CFileItem::m_bCanQueue private
Referenced by Archive(), CanQueue(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), Initialize(), operator=(), and SetCanQueue().
m_bIsAlbum
bool CFileItem::m_bIsAlbum private
Referenced by Initialize(), IsAlbum(), operator=(), and SetFromAlbum().
m_bIsParentFolder
bool CFileItem::m_bIsParentFolder private
Referenced by Archive(), Initialize(), IsParentFolder(), operator=(), and SetLabel().
m_bIsShareOrDrive
bool CFileItem::m_bIsShareOrDrive
is this a root share/drive
Referenced by Archive(), CFileItem(), CGUIWindowFileManager::GetDirectoryHistoryString(), CGUIMediaWindow::GetDirectoryHistoryString(), GetUserMusicThumb(), Initialize(), IsReadOnly(), CMusicThumbLoader::LoadItemCached(), CPictureThumbLoader::LoadItemCached(), CVideoThumbLoader::LoadItemCached(), CMusicThumbLoader::LoadItemLookup(), CVideoThumbLoader::LoadItemLookup(), CGUIWindowVideoBase::OnItemInfo(), operator=(), CPictureThumbLoader::ProcessFoldersAndArchives(), CGUIMediaWindow::ShowShareErrorMessage(), and SkipLocalArt().
m_bLabelPreformatted
bool CFileItem::m_bLabelPreformatted private
Referenced by Archive(), Initialize(), IsLabelPreformatted(), operator=(), and SetLabelPreformatted().
m_cueDocument
CCueDocumentPtr CFileItem::m_cueDocument private
Referenced by HasCueDocument(), LoadTracksFromCueDocument(), and SetCueDocument().
m_dateTime
CDateTime CFileItem::m_dateTime
file creation date & time
Referenced by Archive(), UPNP::BuildObject(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), ADDON::CFileItemListToVFSDirEntries(), CVideoDatabase::GetDetailsForTvShow(), CLabelFormatter::GetMaskContent(), CGUIInfoManager::GetMultiInfoItemLabel(), PVR::CPVRGUIDirectory::GetRecordingsDirectoryInfo(), KODI::RETRO::CSavestateDatabase::GetSavestateItem(), CPictureInfoLoader::LoadItemCached(), MUSIC_INFO::CMusicInfoLoader::LoadItemLookup(), operator=(), ParseItemRSS(), XFILE::CDAVDirectory::ParseResponse(), Reset(), Serialize(), and ToSortable().
m_doContentLookup
bool CFileItem::m_doContentLookup private
Referenced by Archive(), ContentLookup(), Initialize(), MergeInfo(), operator=(), SetContentLookup(), SetMimeTypeForInternetFile(), and UpdateInfo().
m_dwSize
int64_t CFileItem::m_dwSize
file size (0 for folders)
Referenced by Archive(), UPNP::BuildObject(), CGUIWindowFileManager::CalculateFolderSize(), CFileItem(), ADDON::CFileItemListToVFSDirEntries(), dll_findfirst64i32(), dll_findnext64i32(), ADDON::CAddonInstaller::EnumeratePackageFolder(), XFILE::CMusicDatabaseDirectory::GetDirectory(), XFILE::CVideoDatabaseDirectory::GetDirectory(), CLabelFormatter::GetMaskContent(), CGUIInfoManager::GetMultiInfoItemLabel(), Initialize(), operator=(), ParseItem(), XFILE::CDAVDirectory::ParseResponse(), ADDON::CAddonInstaller::PrunePackageCache(), Serialize(), SetFileSizeLabel(), and ToSortable().
m_epgInfoTag
std::shared_ptr<PVR::CPVREpgInfoTag> CFileItem::m_epgInfoTag private
Referenced by CFileItem(), GetEPGInfoTag(), HasEPGInfoTag(), MergeInfo(), operator=(), Reset(), and UpdateInfo().
m_epgSearchFilter
std::shared_ptr<PVR::CPVREpgSearchFilter> CFileItem::m_epgSearchFilter private
Referenced by CFileItem(), GetEPGSearchFilter(), HasEPGSearchFilter(), MergeInfo(), operator=(), Reset(), and UpdateInfo().
m_eventLogEntry
EventPtr CFileItem::m_eventLogEntry private
Referenced by CFileItem(), operator=(), Reset(), and ToSortable().
m_extrainfo
std::string CFileItem::m_extrainfo private
Referenced by Archive(), GetExtraInfo(), operator=(), Reset(), Serialize(), and SetExtraInfo().
m_gameInfoTag
KODI::GAME::CGameInfoTag* CFileItem::m_gameInfoTag private
Referenced by Archive(), GetGameInfoTag(), GetGameInfoTag(), HasGameInfoTag(), Initialize(), LoadGameTag(), operator=(), Reset(), Serialize(), and ~CFileItem().
m_iBadPwdCount
int CFileItem::m_iBadPwdCount
Referenced by Archive(), CFileItem(), Initialize(), and operator=().
m_idepth
int CFileItem::m_idepth
Referenced by Archive(), XFILE::CFileDirectoryFactory::Create(), MUSIC_INFO::CMusicInfoScanner::DownloadArtistInfo(), Initialize(), and operator=().
m_iDriveType
int CFileItem::m_iDriveType
If m_bIsShareOrDrive is true, use to get the share type. Types see: CMediaSource::m_iDriveType.
Referenced by Archive(), CFileItem(), CGUIWindowFileManager::GetDirectoryHistoryString(), CGUIMediaWindow::GetDirectoryHistoryString(), Initialize(), IsDVD(), IsOnDVD(), IsRemovable(), operator=(), CGUIWindowFileManager::ShowShareErrorMessage(), CGUIMediaWindow::ShowShareErrorMessage(), and ToSortable().
m_iHasLock
int CFileItem::m_iHasLock
Referenced by CFileItem(), Initialize(), and operator=().
m_iLockMode
LockType CFileItem::m_iLockMode
Referenced by Archive(), CFileItem(), Initialize(), and operator=().
m_iprogramCount
int CFileItem::m_iprogramCount
Referenced by Archive(), CGUIStaticItem::CGUIStaticItem(), XFILE::CSmartPlaylistDirectory::GetDirectory(), CLabelFormatter::GetMaskContent(), CGUIInfoManager::GetMultiInfoItemLabel(), Initialize(), CGUIWindowMusicPlayList::OnItemLoaded(), operator=(), and ToSortable().
m_lEndOffset
int64_t CFileItem::m_lEndOffset private
Referenced by Archive(), GetEndOffset(), Initialize(), operator=(), SetEndOffset(), SetFromSong(), and ToSortable().
m_lStartOffset
int64_t CFileItem::m_lStartOffset private
Referenced by Archive(), GetStartOffset(), Initialize(), operator=(), SetFromSong(), SetStartOffset(), and ToSortable().
m_lStartPartNumber
int CFileItem::m_lStartPartNumber
Referenced by Archive(), Initialize(), CApplicationStackHelper::InitializeStackStartPartAndOffset(), operator=(), and SetFromSong().
m_mimetype
std::string CFileItem::m_mimetype private
Referenced by Archive(), FillInMimeType(), GetMimeType(), IsPicture(), IsRSS(), MergeInfo(), operator=(), Reset(), Serialize(), SetMimeType(), UpdateInfo(), and UpdateMimeType().
m_musicInfoTag
MUSIC_INFO::CMusicInfoTag* CFileItem::m_musicInfoTag private
Referenced by Archive(), GetMusicInfoTag(), GetMusicInfoTag(), HasMusicInfoTag(), Initialize(), IsSamePath(), LoadMusicTag(), operator=(), Reset(), Serialize(), and ~CFileItem().
m_pictureInfoTag
CPictureInfoTag* CFileItem::m_pictureInfoTag private
Referenced by Archive(), GetPictureInfoTag(), GetPictureInfoTag(), HasPictureInfoTag(), Initialize(), operator=(), Reset(), Serialize(), and ~CFileItem().
m_pvrChannelGroupMemberInfoTag
std::shared_ptr<PVR::CPVRChannelGroupMember> CFileItem::m_pvrChannelGroupMemberInfoTag private
Referenced by CFileItem(), GetPVRChannelGroupMemberInfoTag(), GetPVRChannelInfoTag(), HasPVRChannelGroupMemberInfoTag(), HasPVRChannelInfoTag(), MergeInfo(), operator=(), Reset(), and UpdateInfo().
m_pvrProviderInfoTag
std::shared_ptr<PVR::CPVRProvider> CFileItem::m_pvrProviderInfoTag private
Referenced by CFileItem(), GetPVRProviderInfoTag(), HasPVRProviderInfoTag(), MergeInfo(), operator=(), Reset(), and UpdateInfo().
m_pvrRecordingInfoTag
std::shared_ptr<PVR::CPVRRecording> CFileItem::m_pvrRecordingInfoTag private
Referenced by CFileItem(), GetMovieName(), GetPVRRecordingInfoTag(), GetVideoInfoTag(), GetVideoInfoTag(), HasPVRRecordingInfoTag(), HasVideoInfoTag(), IsDeletedPVRRecording(), IsInProgressPVRRecording(), IsUsablePVRRecording(), MergeInfo(), operator=(), Reset(), and UpdateInfo().
m_pvrTimerInfoTag
std::shared_ptr<PVR::CPVRTimerInfoTag> CFileItem::m_pvrTimerInfoTag private
Referenced by CFileItem(), GetPVRTimerInfoTag(), HasPVRTimerInfoTag(), MergeInfo(), operator=(), Reset(), and UpdateInfo().
m_specialSort
SortSpecial CFileItem::m_specialSort private
Referenced by Archive(), Initialize(), operator=(), SetLabel(), SetSpecialSort(), SortsOnBottom(), SortsOnTop(), and ToSortable().
m_strDVDLabel
std::string CFileItem::m_strDVDLabel
Referenced by Archive(), URIUtils::GetParentPath(), operator=(), Reset(), and Serialize().
m_strDynPath
std::string CFileItem::m_strDynPath private
Referenced by FillInMimeType(), GetDynPath(), GetDynURL(), IsType(), operator=(), Reset(), SetDynPath(), SetDynURL(), and SetFromMusicInfoTag().
m_strLockCode
std::string CFileItem::m_strLockCode
Referenced by Archive(), CFileItem(), operator=(), and Reset().
m_strPath
std::string CFileItem::m_strPath private
complete path to item
Referenced by Archive(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), CFileItem(), Exists(), FillInMimeType(), GetBaseMoviePath(), GetDynPath(), GetDynURL(), GetLocalMetadataPath(), GetMovieName(), GetPath(), GetURL(), GetUserMusicThumb(), GetVideoContentType(), IsAddonsPath(), IsAndroidApp(), IsAPK(), IsBluray(), IsCBR(), IsCBZ(), IsDVD(), IsFavourite(), IsFileFolder(), IsGame(), IsHD(), IsISO9660(), IsLibraryFolder(), IsLiveTV(), IsMultiPath(), IsNFO(), IsNfs(), IsOnDVD(), IsPath(), IsPicture(), IsPlugin(), IsPVR(), IsPVRChannelGroup(), IsPythonScript(), IsRAR(), IsReadOnly(), IsRSS(), IsSamePath(), IsScript(), IsSmb(), IsSourcesPath(), IsType(), IsURL(), IsVirtualDirectoryRoot(), IsZIP(), LoadMusicTag(), operator=(), Reset(), Serialize(), SetFromSong(), SetFromVideoInfoTag(), SetPath(), SetURL(), SkipLocalArt(), and ToSortable().
m_strTitle
std::string CFileItem::m_strTitle
Referenced by Archive(), CVideoDatabase::GetDefaultVideoVersion(), JSONRPC::CVideoLibrary::GetGenres(), CLabelFormatter::GetMaskContent(), GetMovieName(), JSONRPC::CVideoLibrary::GetTags(), CUtil::GetTitleFromPath(), operator=(), ParseItem(), ParseItemMRSS(), ParseItemRSS(), Reset(), Serialize(), and ToSortable().
m_videoInfoTag
CVideoInfoTag* CFileItem::m_videoInfoTag private
Referenced by Archive(), GetVideoInfoTag(), GetVideoInfoTag(), HasVideoInfoTag(), Initialize(), MergeInfo(), operator=(), Reset(), Serialize(), SetFromVideoInfoTag(), UpdateInfo(), and ~CFileItem().
The documentation for this class was generated from the following files:
FileItem.h
FileItem.cpp