Kodi Documentation: TestArchive.cpp File Reference
TestArchive.cpp File Reference
#include "filesystem/File.h"
#include "test/TestUtils.h"
#include "utils/Archive.h"
#include "utils/Variant.h"
#include "utils/XTimeUtils.h"
#include <gtest/gtest.h>
Classes
class TestArchive
Functions
TEST_F (TestArchive, IsStoring)
TEST_F (TestArchive, IsLoading)
TEST_F (TestArchive, FloatArchive)
TEST_F (TestArchive, DoubleArchive)
TEST_F (TestArchive, IntegerArchive)
TEST_F (TestArchive, UnsignedIntegerArchive)
TEST_F (TestArchive, Int64tArchive)
TEST_F (TestArchive, UInt64tArchive)
TEST_F (TestArchive, BoolArchive)
TEST_F (TestArchive, CharArchive)
TEST_F (TestArchive, WStringArchive)
TEST_F (TestArchive, StringArchive)
TEST_F (TestArchive, SystemTimeArchive)
TEST_F (TestArchive, CVariantArchive)
TEST_F (TestArchive, CVariantArchiveString)
TEST_F (TestArchive, StringVectorArchive)
TEST_F (TestArchive, IntegerVectorArchive)
TEST_F (TestArchive, MultiTypeArchive)
Function Documentation
TEST_F() [1/18]
TEST_F (TestArchive , BoolArchive)
References ASSERT_NE(), CArchive::Close(), EXPECT_EQ(), CArchive::load, and CArchive::store.
TEST_F() [2/18]
TEST_F (TestArchive , CharArchive)
References ASSERT_NE(), CArchive::Close(), EXPECT_EQ(), CArchive::load, and CArchive::store.
TEST_F() [3/18]
TEST_F (TestArchive , CVariantArchive)
References CVariant::asInteger(), ASSERT_NE(), CArchive::Close(), EXPECT_EQ(), EXPECT_TRUE(), CVariant::isInteger(), CArchive::load, and CArchive::store.
TEST_F() [4/18]
TEST_F (TestArchive , CVariantArchiveString)
References ASSERT_NE(), CVariant::asString(), CArchive::Close(), EXPECT_TRUE(), CVariant::isString(), CArchive::load, and CArchive::store.
TEST_F() [5/18]
TEST_F (TestArchive , DoubleArchive)
References ASSERT_NE(), CArchive::Close(), EXPECT_EQ(), CArchive::load, and CArchive::store.
TEST_F() [6/18]
TEST_F (TestArchive , FloatArchive)
References ASSERT_NE(), CArchive::Close(), EXPECT_EQ(), CArchive::load, and CArchive::store.
TEST_F() [7/18]
TEST_F (TestArchive , Int64tArchive)
References ASSERT_NE(), CArchive::Close(), EXPECT_EQ(), int64_t(), CArchive::load, and CArchive::store.
TEST_F() [8/18]
TEST_F (TestArchive , IntegerArchive)
References ASSERT_NE(), CArchive::Close(), EXPECT_EQ(), CArchive::load, and CArchive::store.
TEST_F() [9/18]
TEST_F (TestArchive , IntegerVectorArchive)
References ASSERT_NE(), CArchive::Close(), EXPECT_EQ(), CArchive::load, and CArchive::store.
TEST_F() [10/18]
TEST_F (TestArchive , IsLoading)
References ASSERT_NE(), CArchive::Close(), EXPECT_TRUE(), CArchive::IsLoading(), CArchive::IsStoring(), and CArchive::load.
TEST_F() [11/18]
TEST_F (TestArchive , IsStoring)
References ASSERT_NE(), CArchive::Close(), EXPECT_TRUE(), CArchive::IsLoading(), CArchive::IsStoring(), and CArchive::store.
TEST_F() [12/18]
TEST_F (TestArchive , MultiTypeArchive)
References ASSERT_NE(), CArchive::Close(), EXPECT_EQ(), EXPECT_TRUE(), int64_t(), CVariant::isInteger(), CArchive::IsLoading(), CArchive::IsStoring(), CArchive::load, CVariant::push_back(), and CArchive::store.
TEST_F() [13/18]
TEST_F (TestArchive , StringArchive)
References ASSERT_NE(), CArchive::Close(), CArchive::load, and CArchive::store.
TEST_F() [14/18]
TEST_F (TestArchive , StringVectorArchive)
References ASSERT_NE(), CArchive::Close(), CArchive::load, and CArchive::store.
TEST_F() [15/18]
TEST_F (TestArchive , SystemTimeArchive)
References ASSERT_NE(), CArchive::Close(), EXPECT_TRUE(), CArchive::load, and CArchive::store.
TEST_F() [16/18]
TEST_F (TestArchive , UInt64tArchive)
References ASSERT_NE(), CArchive::Close(), EXPECT_EQ(), CArchive::load, and CArchive::store.
TEST_F() [17/18]
TEST_F (TestArchive , UnsignedIntegerArchive)
References ASSERT_NE(), CArchive::Close(), EXPECT_EQ(), CArchive::load, and CArchive::store.
TEST_F() [18/18]
TEST_F (TestArchive , WStringArchive)
References ASSERT_NE(), CArchive::Close(), CArchive::load, and CArchive::store.