Kodi Documentation: CWindowTranslator Class Reference
CWindowTranslator Class Reference
#include <WindowTranslator.h>
Classes
struct WindowIDCompare
struct WindowMapItem
struct WindowNameCompare
Static Public Member Functions
static void GetWindows (std::vector< std::string > &windowList)
Get a list of all known window names.
static int TranslateWindow (const std::string &window)
Translate between a window name and its ID.
static std::string TranslateWindow (int windowId)
Translate between a window id and it's name.
static int GetFallbackWindow (int windowId)
Get the window ID that should be used as fallback for keymap input.
static int GetVirtualWindow (int windowId)
Get the special window ID if conditions met.
Private Types
using WindowMapByName = std::set< WindowMapItem, WindowNameCompare >
using WindowMapByID = std::set< WindowMapItem, WindowIDCompare >
Static Private Member Functions
static WindowMapByID CreateWindowMappingByID ()
Static Private Attributes
static const WindowMapByName WindowMappingByName
Member Typedef Documentation
WindowMapByID
using CWindowTranslator::WindowMapByID = std::set<WindowMapItem, WindowIDCompare> private
WindowMapByName
using CWindowTranslator::WindowMapByName = std::set<WindowMapItem, WindowNameCompare> private
Member Function Documentation
CreateWindowMappingByID()
CWindowTranslator::WindowMapByID CWindowTranslator::CreateWindowMappingByID () static private
References WindowMappingByName.
Referenced by TranslateWindow().
GetFallbackWindow()
int CWindowTranslator::GetFallbackWindow (int windowId) static
Get the window ID that should be used as fallback for keymap input.
Returns
The fallback window, or -1 for no fallback window
References WINDOW_ADDON_END, and WINDOW_ADDON_START.
Referenced by KODI::KEYMAP::CButtonTranslator::GetAction(), KODI::KEYMAP::CKeymapEnvironment::GetFallthrough(), KODI::KEYMAP::CButtonTranslator::HasLongpressMapping_Internal(), KODI::KEYMAP::CCustomControllerTranslator::TranslateCustomControllerString(), and KODI::KEYMAP::CTouchTranslator::TranslateTouchAction().
GetVirtualWindow()
int CWindowTranslator::GetVirtualWindow (int windowId) static
Get the special window ID if conditions met.
Returns
The special window ID or the given window ID
References g_application, PVR::CPVRManager::Get(), CServiceBroker::GetAppComponents(), CServiceBroker::GetPVRManager(), WINDOW_FULLSCREEN_LIVETV, WINDOW_FULLSCREEN_LIVETV_INPUT, WINDOW_FULLSCREEN_LIVETV_PREVIEW, WINDOW_FULLSCREEN_RADIO, WINDOW_FULLSCREEN_RADIO_INPUT, WINDOW_FULLSCREEN_RADIO_PREVIEW, WINDOW_FULLSCREEN_VIDEO, WINDOW_VIDEO_MENU, WINDOW_VIDEO_TIME_SEEK, and WINDOW_VISUALISATION.
Referenced by KODI::KEYMAP::CButtonTranslator::GetAction(), KODI::KEYMAP::CWindowKeymap::GetActions(), KODI::KEYMAP::CButtonTranslator::HasLongpressMapping(), KODI::KEYMAP::CCustomControllerTranslator::TranslateCustomControllerString(), KODI::KEYMAP::CTouchTranslator::TranslateTouchAction(), and TranslateWindow().
GetWindows()
void CWindowTranslator::GetWindows (std::vector< std::string > & windowList) static
Get a list of all known window names.
References WindowMappingByName.
Referenced by JSONRPC::CJSONRPC::Initialize().
TranslateWindow() [1/2]
int CWindowTranslator::TranslateWindow (const std::string & window) static
Translate between a window name and its ID.
Parameters
window The name of the window
Returns
ID of the window, or WINDOW_INVALID if not found
References CLog::Log(), LOGERROR, WINDOW_HOME, WINDOW_INVALID, and WindowMappingByName.
Referenced by anonymous_namespace{GUIBuiltins.cpp}::Action(), anonymous_namespace{GUIBuiltins.cpp}::ActivateAndFocus(), JSONRPC::CGUIOperations::ActivateWindow(), anonymous_namespace{GUIBuiltins.cpp}::ActivateWindow(), JSONRPC::CFavouritesOperations::AddFavourite(), anonymous_namespace{GUIBuiltins.cpp}::ClearProperty(), anonymous_namespace{GUIBuiltins.cpp}::CloseDialog(), XBMCAddon::xbmc::executebuiltin(), JSONRPC::CFavouritesOperations::GetFavourites(), anonymous_namespace{PVRGUIDirectory.cpp}::GetRootDirectory(), CONTEXTMENU::anonymous_namespace{ContextMenus.cpp}::GetTargetWindowID(), CGUIAudioManager::Load(), CGUIWindow::Load(), KODI::KEYMAP::CButtonTranslator::LoadKeymap(), CFavouritesURL::Parse(), CGUIWindowDebugInfo::Process(), CFavouritesService::ResolveFavourite(), SendClick(), SendMessage(), anonymous_namespace{GUIBuiltins.cpp}::SetProperty(), and CGUIInfoManager::TranslateSingleString().
TranslateWindow() [2/2]
std::string CWindowTranslator::TranslateWindow (int windowId) static
Translate between a window id and it's name.
Parameters
window id of the window
Returns
name of the window, or an empty string if not found
References CreateWindowMappingByID(), and GetVirtualWindow().
Member Data Documentation
WindowMappingByName
const CWindowTranslator::WindowMapByName CWindowTranslator::WindowMappingByName static private
Referenced by CreateWindowMappingByID(), GetWindows(), and TranslateWindow().
The documentation for this class was generated from the following files:
WindowTranslator.h
WindowTranslator.cpp