Kodi Documentation: EndianSwap.h File Reference
EndianSwap.h File Reference
Macros
#define Endian_SwapLE16(X) (X)
#define Endian_SwapLE32(X) (X)
#define Endian_SwapLE64(X) (X)
#define Endian_SwapBE16(X) Endian_Swap16(X)
#define Endian_SwapBE32(X) Endian_Swap32(X)
#define Endian_SwapBE64(X) Endian_Swap64(X)
Functions
static __inline__ uint16_t Endian_Swap16 (uint16_t x)
static __inline__ uint32_t Endian_Swap32 (uint32_t x)
static __inline__ uint64_t Endian_Swap64 (uint64_t x)
void Endian_Swap16_buf (uint16_t *dst, uint16_t *src, int w)
Macro Definition Documentation
Endian_SwapBE16
#define Endian_SwapBE16 (X) Endian_Swap16(X)
Endian_SwapBE32
#define Endian_SwapBE32 (X) Endian_Swap32(X)
Endian_SwapBE64
#define Endian_SwapBE64 (X) Endian_Swap64(X)
Endian_SwapLE16
#define Endian_SwapLE16 (X) (X)
Endian_SwapLE32
#define Endian_SwapLE32 (X) (X)
Endian_SwapLE64
#define Endian_SwapLE64 (X) (X)
Function Documentation
Endian_Swap16()
static __inline__ uint16_t Endian_Swap16 (uint16_t x) static
Referenced by Endian_Swap16_buf(), and TEST().
Endian_Swap16_buf()
void Endian_Swap16_buf (uint16_t * dst, uint16_t * src, int w)
References Endian_Swap16().
Referenced by ActiveAE::CActiveAESink::OutputSamples().
Endian_Swap32()
static __inline__ uint32_t Endian_Swap32 (uint32_t x) static
Referenced by Endian_Swap64(), and TEST().
Endian_Swap64()
static __inline__ uint64_t Endian_Swap64 (uint64_t x) static
References Endian_Swap32().
Referenced by TEST().