Kodi Documentation: CLibInputSettings Class Reference
CLibInputSettings Class Reference
#include <LibInputSettings.h>
Public Member Functions
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
CLibInputSettings (CLibInputHandler *handler)
~CLibInputSettings () override
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Public Member Functions inherited from ISettingsHandler
virtual ~ISettingsHandler ()=default
virtual bool OnSettingsLoading ()
Settings loading has been initiated.
virtual void OnSettingsLoaded ()
Settings have been loaded.
virtual bool OnSettingsSaving () const
Settings saving has been initiated.
virtual void OnSettingsSaved () const
Settings have been saved.
virtual void OnSettingsUnloaded ()
Setting values have been unloaded.
virtual void OnSettingsCleared ()
Settings have been cleared.
Static Public Member Functions
static void SettingOptionsKeyboardLayoutsFiller (const std::shared_ptr< const CSetting > &setting, std::vector< StringSettingOption > &list, std::string &current, void *data)
Static Public Attributes
static const std::string SETTING_INPUT_LIBINPUTKEYBOARDLAYOUT = "input.libinputkeyboardlayout"
Private Attributes
CLibInputHandler * m_libInputHandler {nullptr}
Constructor & Destructor Documentation
CLibInputSettings()
CLibInputSettings::CLibInputSettings (CLibInputHandler * handler)
References CServiceBroker::GetSettingsComponent(), layouts, CXBMCTinyXML2::LoadFile(), CLog::Log(), LOGERROR, LOGWARNING, SETTING_INPUT_LIBINPUTKEYBOARDLAYOUT, and SettingOptionsKeyboardLayoutsFiller().
~CLibInputSettings()
CLibInputSettings::~CLibInputSettings () override
References CServiceBroker::GetSettingsComponent().
Member Function Documentation
OnSettingChanged()
void CLibInputSettings::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References m_libInputHandler, CLibInputHandler::SetKeymap(), and SETTING_INPUT_LIBINPUTKEYBOARDLAYOUT.
SettingOptionsKeyboardLayoutsFiller()
void CLibInputSettings::SettingOptionsKeyboardLayoutsFiller (const std::shared_ptr< const CSetting > & setting, std::vector< StringSettingOption > & list, std::string & current, void * data) static
References layouts.
Referenced by CLibInputSettings().
Member Data Documentation
m_libInputHandler
CLibInputHandler* CLibInputSettings::m_libInputHandler {nullptr} private
Referenced by OnSettingChanged().
SETTING_INPUT_LIBINPUTKEYBOARDLAYOUT
const std::string CLibInputSettings::SETTING_INPUT_LIBINPUTKEYBOARDLAYOUT = "input.libinputkeyboardlayout" static
Referenced by CLibInputSettings(), and OnSettingChanged().
The documentation for this class was generated from the following files:
linux/input/LibInputSettings.h
LibInputSettings.cpp