Kodi Documentation: CWinShader Class Reference
CWinShader Class Reference
#include <WinVideoFilter.h>
Protected Member Functions
CWinShader ()=default
virtual ~CWinShader ()=default
virtual bool CreateVertexBuffer (unsigned int vertCount, unsigned int vertSize)
virtual bool LockVertexBuffer (void **data)
virtual bool UnlockVertexBuffer ()
virtual bool LoadEffect (const std::string &filename, DefinesMap *defines)
virtual bool Execute (const std::vector< CD3DTexture * > &targets, unsigned int vertexIndexStep)
virtual void SetStepParams (unsigned stepIndex)
virtual bool CreateInputLayout (D3D11_INPUT_ELEMENT_DESC *layout, unsigned numElements)
Protected Attributes
CD3DEffect m_effect
CD3DTexture * m_target = nullptr
Private Member Functions
void SetTarget (CD3DTexture *target)
Private Attributes
CD3DBuffer m_vb
CD3DBuffer m_ib
unsigned int m_vbsize = 0
unsigned int m_vertsize = 0
Microsoft::WRL::ComPtr< ID3D11InputLayout > m_inputLayout = nullptr
Constructor & Destructor Documentation
CWinShader()
CWinShader::CWinShader () protected default
~CWinShader()
virtual CWinShader::~CWinShader () protected virtual default
Member Function Documentation
CreateInputLayout()
bool CWinShader::CreateInputLayout (D3D11_INPUT_ELEMENT_DESC * layout, unsigned numElements) protected virtual
References FAILED, DX::DeviceResources::Get(), CD3DEffect::Get(), LOGERROR, m_effect, and m_inputLayout.
Referenced by CYUV2RGBShader::Create(), COutputShader::Create(), CConvolutionShader1Pass::Create(), CConvolutionShaderSeparable::Create(), and KODI::RETRO::CRPWinOutputShader::Create().
CreateVertexBuffer()
bool CWinShader::CreateVertexBuffer (unsigned int vertCount, unsigned int vertSize) protected virtual
References CD3DBuffer::Create(), m_ib, m_vb, m_vbsize, and m_vertsize.
Referenced by CYUV2RGBShader::Create(), COutputShader::Create(), CConvolutionShader1Pass::Create(), CConvolutionShaderSeparable::Create(), and KODI::RETRO::CRPWinOutputShader::Create().
Execute()
bool CWinShader::Execute (const std::vector< CD3DTexture * > & targets, unsigned int vertexIndexStep) protected virtual
References CD3DEffect::Begin(), CD3DEffect::BeginPass(), CD3DEffect::End(), CD3DEffect::EndPass(), DX::DeviceResources::Get(), CD3DBuffer::Get(), CD3DBuffer::GetFormat(), CD3DBuffer::GetStride(), LOGERROR, m_effect, m_ib, m_inputLayout, m_vb, CD3DHelper::PSClearShaderResources(), SetStepParams(), and SetTarget().
Referenced by CConvolutionShader1Pass::Render(), CConvolutionShaderSeparable::Render(), COutputShader::Render(), KODI::RETRO::CRPWinOutputShader::Render(), and CYUV2RGBShader::Render().
LoadEffect()
bool CWinShader::LoadEffect (const std::string & filename, DefinesMap * defines) protected virtual
References CD3DEffect::Create(), LOGDEBUG, LOGERROR, and m_effect.
Referenced by CYUV2RGBShader::Create(), COutputShader::Create(), CConvolutionShader1Pass::Create(), CConvolutionShaderSeparable::Create(), and KODI::RETRO::CRPWinOutputShader::Create().
LockVertexBuffer()
bool CWinShader::LockVertexBuffer (void ** data) protected virtual
References data(), LOGERROR, m_vb, and CD3DBuffer::Map().
Referenced by CYUV2RGBShader::PrepareParameters(), CConvolutionShader1Pass::PrepareParameters(), CConvolutionShaderSeparable::PrepareParameters(), KODI::RETRO::CRPWinOutputShader::PrepareParameters(), and COutputShader::PrepareParameters().
SetStepParams()
virtual void CWinShader::SetStepParams (unsigned stepIndex) inline protected virtual
Reimplemented in CConvolutionShaderSeparable.
Referenced by Execute().
SetTarget()
void CWinShader::SetTarget (CD3DTexture * target) private
References DX::DeviceResources::Get(), CD3DTexture::GetAddressOfRTV(), and m_target.
Referenced by Execute().
UnlockVertexBuffer()
bool CWinShader::UnlockVertexBuffer () protected virtual
References LOGERROR, m_vb, and CD3DBuffer::Unmap().
Referenced by CYUV2RGBShader::PrepareParameters(), CConvolutionShader1Pass::PrepareParameters(), CConvolutionShaderSeparable::PrepareParameters(), KODI::RETRO::CRPWinOutputShader::PrepareParameters(), and COutputShader::PrepareParameters().
Member Data Documentation
m_effect
CD3DEffect CWinShader::m_effect protected
Referenced by CTestShader::Create(), CreateInputLayout(), Execute(), LoadEffect(), CConvolutionShader1Pass::SetShaderParameters(), CConvolutionShaderSeparable::SetShaderParameters(), KODI::RETRO::CRPWinOutputShader::SetShaderParameters(), COutputShader::SetShaderParameters(), CYUV2RGBShader::SetShaderParameters(), and CConvolutionShaderSeparable::SetStepParams().
m_ib
CD3DBuffer CWinShader::m_ib private
Referenced by CreateVertexBuffer(), and Execute().
m_inputLayout
Microsoft::WRL::ComPtr<ID3D11InputLayout> CWinShader::m_inputLayout = nullptr private
Referenced by CreateInputLayout(), and Execute().
m_target
CD3DTexture* CWinShader::m_target = nullptr protected
Referenced by CConvolutionShaderSeparable::SetStepParams(), and SetTarget().
m_vb
CD3DBuffer CWinShader::m_vb private
Referenced by CreateVertexBuffer(), Execute(), LockVertexBuffer(), and UnlockVertexBuffer().
m_vbsize
unsigned int CWinShader::m_vbsize = 0 private
Referenced by CreateVertexBuffer().
m_vertsize
unsigned int CWinShader::m_vertsize = 0 private
Referenced by CreateVertexBuffer().
The documentation for this class was generated from the following files:
WinVideoFilter.h
WinVideoFilter.cpp