Kodi Documentation: CXBMCTinyXML2 Class Reference
CXBMCTinyXML2 Class Reference
#include <XBMCTinyXML2.h>
Public Member Functions
CXBMCTinyXML2 ()=default
bool LoadFile (const std::string &filename)
bool LoadFile (FILE *file)
bool SaveFile (const std::string &filename) const
bool Parse (std::string_view inputdata)
bool Parse (std::string &&inputdata)
Private Member Functions
bool ParseHelper (size_t pos, std::string &&inputdata)
Constructor & Destructor Documentation
CXBMCTinyXML2()
CXBMCTinyXML2::CXBMCTinyXML2 () default
Member Function Documentation
LoadFile() [1/2]
bool CXBMCTinyXML2::LoadFile (const std::string & filename)
References Error, and Parse().
Referenced by CLibInputSettings::CLibInputSettings(), ADDON::CAddonInfoBuilder::Generate(), XFILE::CRSSDirectory::GetDirectory(), CDecoderFilterManager::Load(), CPasswordManager::Load(), CRssManager::Load(), CUPnPSettings::Load(), CMediaSourceSettings::Load(), KODI::KEYBOARD::CKeyboardLayoutManager::Load(), KODI::PLAYLIST::CPlayListXML::Load(), KODI::PLAYLIST::CPlayListXSPF::Load(), CXRandR::LoadCustomModeLinesToAllOutputs(), anonymous_namespace{FavouritesService.cpp}::LoadFromFile(), CWakeOnAccess::LoadFromXML(), KODI::KEYMAP::CIRTranslator::LoadIRMap(), KODI::KEYMAP::CButtonTranslator::LoadKeymap(), KODI::GAME::CController::LoadLayout(), PERIPHERALS::CPeripherals::LoadMappings(), PERIPHERALS::CPeripheral::LoadPersistedSettings(), CMediaManager::LoadSources(), CSkinTimerManager::LoadTimers(), KODI::GAME::CPortManager::LoadXML(), CMediaManager::playStubFile(), CXRandR::Query(), CEdl::ReadBeyondTV(), TEST(), TEST(), and TEST().
LoadFile() [2/2]
bool CXBMCTinyXML2::LoadFile (FILE * file)
References BUFFER_SIZE, data(), and Parse().
Parse() [1/2]
bool CXBMCTinyXML2::Parse (std::string && inputdata)
References ParseHelper().
Parse() [2/2]
bool CXBMCTinyXML2::Parse (std::string_view inputdata)
References ParseHelper().
Referenced by ADDON::CAddonMgr::AddonsFromRepoXML(), XFILE::CDAVFile::Execute(), XFILE::CDAVDirectory::GetDirectory(), KODI::PLAYLIST::CPlayListASX::LoadData(), KODI::PLAYLIST::CPlayListB4S::LoadData(), KODI::PLAYLIST::CPlayListWPL::LoadData(), LoadFile(), LoadFile(), CRssReader::Parse(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), CFanart::Unpack(), CBlurayStateSerializer::XMLToBlurayState(), and CDVDStateSerializer::XMLToDVDState().
ParseHelper()
bool CXBMCTinyXML2::ParseHelper (size_t pos, std::string && inputdata) private
References CRegExp::asciiOnly, MAX_ENTITY_LENGTH, and CRegExp::RegFind().
Referenced by Parse(), and Parse().
SaveFile()
bool CXBMCTinyXML2::SaveFile (const std::string & filename) const
Referenced by CFavouritesService::Persist(), PERIPHERALS::CPeripheral::PersistSettings(), CDecoderFilterManager::Save(), CPasswordManager::Save(), CUPnPSettings::Save(), CMediaSourceSettings::Save(), CMediaManager::SaveSources(), CWakeOnAccess::SaveToXML(), and KODI::GAME::CPortManager::SaveXMLAsync().
The documentation for this class was generated from the following files:
XBMCTinyXML2.h
XBMCTinyXML2.cpp