Kodi Documentation: CProgressJob Class Reference
CProgressJob Class Reference
Basic implementation of a CJob with a progress bar to indicate the progress of the job being processed.
#include <ProgressJob.h>
Public Member Functions
~CProgressJob () override
const char * GetType () const override
Function that returns the type of job.
bool operator== (const CJob *job) const override
bool ShouldCancel (unsigned int progress, unsigned int total) const override
Function for longer jobs to report progress and check whether they have been cancelled.
bool DoModal ()
Executes the job showing a modal progress dialog.
void SetProgressIndicators (CGUIDialogProgressBarHandle *progressBar, CGUIDialogProgress *progressDialog, bool updateProgress=true, bool updateInformation=true)
Sets the given progress indicators to be used during execution of the job.
bool HasProgressIndicator () const
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
virtual bool DoWork ()=0
Main workhorse function of CJob instances.
Protected Member Functions
CProgressJob ()
CProgressJob (CGUIDialogProgressBarHandle *progressBar)
bool IsModal () const
Whether the job is being run modally or in the background.
CGUIDialogProgressBarHandle * GetProgressBar () const
Returns the progress bar indicating the progress of the job.
void SetProgressBar (CGUIDialogProgressBarHandle *progress)
Sets the progress bar indicating the progress of the job.
CGUIDialogProgress * GetProgressDialog () const
Returns the progress dialog indicating the progress of the job.
void SetProgressDialog (CGUIDialogProgress *progressDialog)
Sets the progress bar indicating the progress of the job.
bool GetAutoClose ()
Whether to automatically close the progress indicator in MarkFinished().
void SetAutoClose (bool autoClose)
Set whether to automatically close the progress indicator in MarkFinished().
bool GetUpdateProgress ()
Whether to update the progress bar or not.
void SetUpdateProgress (bool updateProgress)
Set whether to update the progress bar or not.
bool GetUpdateInformation ()
Whether to update the progress information or not.
void SetUpdateInformation (bool updateInformation)
Set whether to update the progress information or not.
void ShowProgressDialog () const
Makes sure that the modal dialog is being shown.
void SetTitle (const std::string &title)
Sets the given title as the title of the progress bar.
void SetText (const std::string &text)
Sets the given text as the description of the progress bar.
void SetProgress (float percentage) const
Sets the progress of the progress bar to the given value in percentage.
void SetProgress (int currentStep, int totalSteps) const
Sets the progress of the progress bar to the given value.
void MarkFinished ()
Marks the progress as finished by setting it to 100%.
bool IsCancelled () const
Checks if the progress dialog has been cancelled.
Private Attributes
bool m_modal = false
bool m_autoClose = true
bool m_updateProgress = true
bool m_updateInformation = true
CGUIDialogProgressBarHandle * m_progress
CGUIDialogProgress * m_progressDialog
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Detailed Description
Basic implementation of a CJob with a progress bar to indicate the progress of the job being processed.
Constructor & Destructor Documentation
~CProgressJob()
CProgressJob::~CProgressJob () override
References m_progress, m_progressDialog, and MarkFinished().
CProgressJob() [1/2]
CProgressJob::CProgressJob () protected
CProgressJob() [2/2]
CProgressJob::CProgressJob (CGUIDialogProgressBarHandle * progressBar) explicit protected
Member Function Documentation
DoModal()
bool CProgressJob::DoModal ()
Executes the job showing a modal progress dialog.
References CJob::DoWork(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), m_modal, m_progress, m_progressDialog, MarkFinished(), and WINDOW_DIALOG_PROGRESS.
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::Install(), and CVideoLibraryQueue::RefreshItemModal().
GetAutoClose()
bool CProgressJob::GetAutoClose () inline protected
Whether to automatically close the progress indicator in MarkFinished().
References m_autoClose.
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoFileOperation().
GetProgressBar()
CGUIDialogProgressBarHandle * CProgressJob::GetProgressBar () const inline protected
Returns the progress bar indicating the progress of the job.
References m_progress.
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoFileOperation(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::Install(), and CVideoLibraryCleaningJob::Work().
GetProgressDialog()
CGUIDialogProgress * CProgressJob::GetProgressDialog () const inline protected
Returns the progress dialog indicating the progress of the job.
References m_progressDialog.
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoFileOperation(), CRefreshInfoJob::DoWork(), CFileOperationJob::DoWork(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::Install(), CMusicLibraryCleaningJob::Work(), CMusicLibraryExportJob::Work(), CMusicLibraryImportJob::Work(), and CVideoLibraryRefreshingJob::Work().
GetType()
const char * CProgressJob::GetType () const inline override virtual
Function that returns the type of job.
CJob subclasses may optionally implement this function to specify the type of job. This is useful for the CJobManager::AddLIFOJob() routine, which preempts similar jobs with the new job.
Returns
a unique character string describing the job.
See also
CJobManager
Reimplemented from CJob.
Reimplemented in CVideoLibraryCleaningJob, CVideoLibraryProgressJob, and CVideoLibraryRefreshingJob.
GetUpdateInformation()
bool CProgressJob::GetUpdateInformation () inline protected
Whether to update the progress information or not.
References m_updateInformation.
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoFileOperation().
GetUpdateProgress()
bool CProgressJob::GetUpdateProgress () inline protected
Whether to update the progress bar or not.
References m_updateProgress.
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoFileOperation().
HasProgressIndicator()
bool CProgressJob::HasProgressIndicator () const
References m_progress, and m_progressDialog.
IsCancelled()
bool CProgressJob::IsCancelled () const protected
Checks if the progress dialog has been cancelled.
References CGUIDialogProgress::IsCanceled(), and m_progressDialog.
Referenced by ShouldCancel(), and CVideoLibraryRefreshingJob::Work().
IsModal()
bool CProgressJob::IsModal () const inline protected
Whether the job is being run modally or in the background.
References m_modal.
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::Install(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::ReportInstallError(), ShowProgressDialog(), and CVideoLibraryRefreshingJob::Work().
MarkFinished()
void CProgressJob::MarkFinished () protected
Marks the progress as finished by setting it to 100%.
References CGUIWindow::Close(), m_autoClose, m_progress, m_progressDialog, m_updateProgress, and CGUIDialogProgressBarHandle::MarkFinished().
Referenced by DoModal(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), ADDON::CRepositoryUpdateJob::DoWork(), CRefreshInfoJob::DoWork(), CMusicLibraryProgressJob::DoWork(), CFileOperationJob::DoWork(), CVideoLibraryProgressJob::DoWork(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::ReportInstallError(), CVideoLibraryRefreshingJob::Work(), and ~CProgressJob().
operator==()
bool CProgressJob::operator== (const CJob * job) const inline override virtual
Reimplemented from CJob.
Reimplemented in CVideoLibraryCleaningJob, CVideoLibraryProgressJob, and CVideoLibraryRefreshingJob.
SetAutoClose()
void CProgressJob::SetAutoClose (bool autoClose) inline protected
Set whether to automatically close the progress indicator in MarkFinished().
References m_autoClose.
Referenced by CMusicLibraryCleaningJob::CMusicLibraryCleaningJob(), CMusicLibraryExportJob::CMusicLibraryExportJob(), CMusicLibraryImportJob::CMusicLibraryImportJob(), CRefreshInfoJob::CRefreshInfoJob(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoFileOperation(), and SetProgressIndicators().
SetProgress() [1/2]
void CProgressJob::SetProgress (float percentage) const protected
Sets the progress of the progress bar to the given value in percentage.
Parameters
[in] percentage Percentage to be set as the current progress
References CGUIDialogProgress::GetPercentage(), m_progress, m_progressDialog, m_updateProgress, CGUIDialogProgress::Progress(), CGUIDialogProgressBarHandle::SetPercentage(), CGUIDialogProgress::SetPercentage(), and ShowProgressDialog().
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::Install(), SetProgress(), ShouldCancel(), and CVideoLibraryRefreshingJob::Work().
SetProgress() [2/2]
void CProgressJob::SetProgress (int currentStep, int totalSteps) const protected
Sets the progress of the progress bar to the given value.
Parameters
[in] currentStep Current step being processed
[in] totalSteps Total steps to be processed
References m_progress, m_progressDialog, m_updateProgress, SetProgress(), and CGUIDialogProgressBarHandle::SetProgress().
SetProgressBar()
void CProgressJob::SetProgressBar (CGUIDialogProgressBarHandle * progress) inline protected
Sets the progress bar indicating the progress of the job.
References m_progress.
Referenced by CFileOperationJob::DoWork(), and SetProgressIndicators().
SetProgressDialog()
void CProgressJob::SetProgressDialog (CGUIDialogProgress * progressDialog) inline protected
Sets the progress bar indicating the progress of the job.
References m_progressDialog.
Referenced by SetProgressIndicators().
SetProgressIndicators()
void CProgressJob::SetProgressIndicators (CGUIDialogProgressBarHandle * progressBar, CGUIDialogProgress * progressDialog, bool updateProgress = true, bool updateInformation = true)
Sets the given progress indicators to be used during execution of the job.
This automatically disables auto-closing the given progress indicators once the job has been finished.
Parameters
progressBar Progress bar handle to be used.
progressDialog Progress dialog to be used.
updateProgress (optional) Whether to show progress updates.
updateInformation (optional) Whether to show progress information.
References SetAutoClose(), SetProgressBar(), SetProgressDialog(), SetUpdateInformation(), and SetUpdateProgress().
Referenced by CMusicLibraryCleaningJob::CMusicLibraryCleaningJob(), CMusicLibraryExportJob::CMusicLibraryExportJob(), CMusicLibraryImportJob::CMusicLibraryImportJob(), CRefreshInfoJob::CRefreshInfoJob(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoFileOperation(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::Install(), and ADDON::SetProgressIndicator().
SetText()
void CProgressJob::SetText (const std::string & text) protected
Sets the given text as the description of the progress bar.
Parameters
[in] text Text to be set
References CGUIDialogBoxBase::HasHeading(), CGUIDialogBoxBase::HasText(), m_progress, m_progressDialog, m_updateInformation, CGUIDialogBoxBase::SetText(), CGUIDialogProgressBarHandle::SetText(), ShowProgressDialog(), and text.
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DownloadPackage(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), CFileOperationJob::CFileOperation::ExecuteOperation(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::Install(), and CVideoLibraryRefreshingJob::Work().
SetTitle()
void CProgressJob::SetTitle (const std::string & title) protected
Sets the given title as the title of the progress bar.
Parameters
[in] title Title to be set
References CGUIDialogBoxBase::HasHeading(), CGUIDialogBoxBase::HasText(), m_progress, m_progressDialog, m_updateInformation, CGUIDialogBoxBase::SetHeading(), CGUIDialogProgressBarHandle::SetTitle(), and ShowProgressDialog().
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoWork(), and CVideoLibraryRefreshingJob::Work().
SetUpdateInformation()
void CProgressJob::SetUpdateInformation (bool updateInformation) inline protected
Set whether to update the progress information or not.
References m_updateInformation.
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DoFileOperation(), and SetProgressIndicators().
SetUpdateProgress()
void CProgressJob::SetUpdateProgress (bool updateProgress) inline protected
Set whether to update the progress bar or not.
References m_updateProgress.
Referenced by SetProgressIndicators().
ShouldCancel()
bool CProgressJob::ShouldCancel (unsigned int progress, unsigned int total) const override virtual
Function for longer jobs to report progress and check whether they have been cancelled.
Jobs that contain loops that may take time should check this routine each iteration of the loop, both to (optionally) report progress, and to check for cancellation.
Parameters
progress the amount of the job performed, out of total.
total the total amount of processing to be performed
Returns
if true, the job has been asked to cancel.
See also
IJobCallback::OnJobProgress()
Reimplemented from CJob.
References IsCancelled(), SetProgress(), and CJob::ShouldCancel().
Referenced by anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::DownloadPackage(), CFileOperationJob::CFileOperation::ExecuteOperation(), and anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::Install().
ShowProgressDialog()
void CProgressJob::ShowProgressDialog () const protected
Makes sure that the modal dialog is being shown.
References CGUIDialog::IsDialogRunning(), IsModal(), m_progressDialog, CGUIDialogProgress::Open(), and CGUIDialogProgress::ShowProgressBar().
Referenced by SetProgress(), SetText(), and SetTitle().
Member Data Documentation
m_autoClose
bool CProgressJob::m_autoClose = true private
Referenced by GetAutoClose(), MarkFinished(), and SetAutoClose().
m_modal
bool CProgressJob::m_modal = false private
Referenced by DoModal(), and IsModal().
m_progress
CGUIDialogProgressBarHandle* CProgressJob::m_progress mutable private
Referenced by DoModal(), GetProgressBar(), HasProgressIndicator(), MarkFinished(), SetProgress(), SetProgress(), SetProgressBar(), SetText(), SetTitle(), and ~CProgressJob().
m_progressDialog
CGUIDialogProgress* CProgressJob::m_progressDialog mutable private
Referenced by DoModal(), GetProgressDialog(), HasProgressIndicator(), IsCancelled(), MarkFinished(), SetProgress(), SetProgress(), SetProgressDialog(), SetText(), SetTitle(), ShowProgressDialog(), and ~CProgressJob().
m_updateInformation
bool CProgressJob::m_updateInformation = true private
Referenced by GetUpdateInformation(), SetText(), SetTitle(), and SetUpdateInformation().
m_updateProgress
bool CProgressJob::m_updateProgress = true private
Referenced by GetUpdateProgress(), MarkFinished(), SetProgress(), SetProgress(), and SetUpdateProgress().
The documentation for this class was generated from the following files:
ProgressJob.h
ProgressJob.cpp