Kodi Documentation: CSkinSettings Class Reference
CSkinSettings Class Reference
#include <SkinSettings.h>
Public Member Functions
bool Load (const TiXmlNode *settings) override
Load settings from the given XML node.
bool Save (TiXmlNode *settings) const override
Save settings to the given XML node.
void Clear () override
Clear any loaded setting values.
void MigrateSettings (const std::shared_ptr< ADDON::CSkinInfo > &skin)
int TranslateString (const std::string &setting)
const std::string & GetString (int setting) const
void SetString (int setting, const std::string &label)
int TranslateBool (const std::string &setting)
bool GetBool (int setting) const
void SetBool (int setting, bool set)
int GetInt (int setting) const
Get the skin setting value as an integer value.
std::set< ADDON::CSkinSettingPtr > GetSettings () const
ADDON::CSkinSettingPtr GetSetting (const std::string &settingId)
std::shared_ptr< const ADDON::CSkinSetting > GetSetting (const std::string &settingId) const
void Reset (const std::string &setting)
void Reset ()
Public Member Functions inherited from ISubSettings
virtual ~ISubSettings ()=default
Static Public Member Functions
static CSkinSettings & GetInstance ()
Protected Member Functions
CSkinSettings ()
CSkinSettings (const CSkinSettings &)=delete
CSkinSettings & operator= (CSkinSettings const &)=delete
~CSkinSettings () override
Private Attributes
CCriticalSection m_critical
std::set< ADDON::CSkinSettingPtr > m_settings
Constructor & Destructor Documentation
CSkinSettings() [1/2]
CSkinSettings::CSkinSettings () protected
References Clear().
CSkinSettings() [2/2]
CSkinSettings::CSkinSettings (const CSkinSettings &) protected delete
~CSkinSettings()
CSkinSettings::~CSkinSettings () override protected default
Member Function Documentation
Clear()
void CSkinSettings::Clear () override virtual
Clear any loaded setting values.
Reimplemented from ISubSettings.
References m_critical, and m_settings.
Referenced by CSkinSettings().
GetBool()
bool CSkinSettings::GetBool (int setting) const
References g_SkinInfo.
Referenced by KODI::GUILIB::GUIINFO::CSkinGUIInfo::GetBool(), and KODI::GUILIB::GUIINFO::CSkinGUIInfo::GetLabel().
GetInstance()
CSkinSettings & CSkinSettings::GetInstance () static
Referenced by KODI::GUILIB::GUIINFO::CSkinGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CSkinGUIInfo::GetInt(), KODI::GUILIB::GUIINFO::CSkinGUIInfo::GetLabel(), JSONRPC::CSettingsOperations::GetSkinSettings(), JSONRPC::CSettingsOperations::GetSkinSettingValue(), CSettings::InitializeISubSettings(), CApplicationSkinHandling::LoadSkin(), SelectBool(), SetAddon(), SetBool(), SetColor(), SetFile(), SetImage(), SetNumeric(), SetPath(), JSONRPC::CSettingsOperations::SetSkinSettingValue(), SetString(), SkinReset(), SkinResetAll(), ToggleSetting(), CGUIInfoManager::TranslateSingleString(), and CSettings::UninitializeISubSettings().
GetInt()
int CSkinSettings::GetInt (int setting) const
Get the skin setting value as an integer value.
Parameters
setting - the setting id
Returns
the setting value as an integer, -1 if no conversion is possible
References g_SkinInfo.
Referenced by KODI::GUILIB::GUIINFO::CSkinGUIInfo::GetInt().
GetSetting() [1/2]
ADDON::CSkinSettingPtr CSkinSettings::GetSetting (const std::string & settingId)
References g_SkinInfo.
Referenced by JSONRPC::CSettingsOperations::GetSkinSettingValue(), and JSONRPC::CSettingsOperations::SetSkinSettingValue().
GetSetting() [2/2]
std::shared_ptr< const ADDON::CSkinSetting > CSkinSettings::GetSetting (const std::string & settingId) const
References g_SkinInfo.
GetSettings()
std::set< ADDON::CSkinSettingPtr > CSkinSettings::GetSettings () const
References g_SkinInfo.
Referenced by JSONRPC::CSettingsOperations::GetSkinSettings().
GetString()
const std::string & CSkinSettings::GetString (int setting) const
References g_SkinInfo.
Referenced by KODI::GUILIB::GUIINFO::CSkinGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CSkinGUIInfo::GetLabel(), SetColor(), SetFile(), SetImage(), SetNumeric(), SetPath(), and SetString().
Load()
bool CSkinSettings::Load (const TiXmlNode * settings) override virtual
Load settings from the given XML node.
Parameters
settings XML node containing setting values
Returns
True if loading the settings was successful, false otherwise.
Reimplemented from ISubSettings.
References CLog::Log(), LOGDEBUG, m_critical, m_settings, ADDON::CSkinInfo::ParseSettings(), and XML_SKINSETTINGS.
MigrateSettings()
void CSkinSettings::MigrateSettings (const std::shared_ptr< ADDON::CSkinInfo > & skin)
References CServiceBroker::GetSettingsComponent(), m_critical, and m_settings.
Referenced by CApplicationSkinHandling::LoadSkin().
operator=()
CSkinSettings & CSkinSettings::operator= (CSkinSettings const &) protected delete
Reset() [1/2]
void CSkinSettings::Reset ()
References g_SkinInfo, CServiceBroker::GetGUI(), KODI::GUILIB::GUIINFO::CGUIInfoProviders::GetGUIControlsInfoProvider(), CGUIComponent::GetInfoManager(), CGUIInfoManager::GetInfoProviders(), CGUIInfoManager::ResetCache(), and KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::ResetContainerMovingCache().
Reset() [2/2]
void CSkinSettings::Reset (const std::string & setting)
References g_SkinInfo.
Referenced by SkinReset(), and SkinResetAll().
Save()
bool CSkinSettings::Save (TiXmlNode * settings) const override virtual
Save settings to the given XML node.
Parameters
settings XML node in which the settings will be saved
Returns
True if saving the settings was successful, false otherwise.
Reimplemented from ISubSettings.
SetBool()
void CSkinSettings::SetBool (int setting, bool set)
References g_SkinInfo.
Referenced by SelectBool(), SetBool(), and ToggleSetting().
SetString()
void CSkinSettings::SetString (int setting, const std::string & label)
References g_SkinInfo, and label.
Referenced by SetAddon(), SetColor(), SetFile(), SetImage(), SetNumeric(), SetPath(), and SetString().
TranslateBool()
int CSkinSettings::TranslateBool (const std::string & setting)
References g_SkinInfo.
Referenced by SelectBool(), SetBool(), and ToggleSetting().
TranslateString()
int CSkinSettings::TranslateString (const std::string & setting)
References g_SkinInfo, and TranslateString().
Referenced by SetAddon(), SetColor(), SetFile(), SetImage(), SetNumeric(), SetPath(), SetString(), and TranslateString().
Member Data Documentation
m_critical
CCriticalSection CSkinSettings::m_critical private
Referenced by Clear(), Load(), and MigrateSettings().
m_settings
std::set<ADDON::CSkinSettingPtr> CSkinSettings::m_settings private
Referenced by Clear(), Load(), and MigrateSettings().
The documentation for this class was generated from the following files:
SkinSettings.h
SkinSettings.cpp