Kodi Documentation: CCocoaPowerSyscall Class Reference
CCocoaPowerSyscall Class Reference
#include <CocoaPowerSyscall.h>
Public Member Functions
CCocoaPowerSyscall ()
~CCocoaPowerSyscall () override
bool Powerdown () override
bool Suspend () override
bool Hibernate () override
bool Reboot () override
bool CanPowerdown () override
bool CanSuspend () override
bool CanHibernate () override
bool CanReboot () override
bool HasBattery ()
int BatteryLevel () override
bool PumpPowerEvents (IPowerEventsCallback *callback) override
Pump power related events back to xbmc.
Public Member Functions inherited from CPowerSyscallWithoutEvents
CPowerSyscallWithoutEvents ()
bool Suspend () override
bool Hibernate () override
bool PumpPowerEvents (IPowerEventsCallback *callback) override
Pump power related events back to xbmc.
Public Member Functions inherited from CAbstractPowerSyscall
int CountPowerFeatures () override
Public Member Functions inherited from IPowerSyscall
virtual ~IPowerSyscall ()=default
Static Public Member Functions
static IPowerSyscall * CreateInstance ()
static void Register ()
Static Public Member Functions inherited from IPowerSyscall
static IPowerSyscall * CreateInstance ()
Called by power manager to create platform power system adapter.
static void RegisterPowerSyscall (CreatePowerSyscallFunc createFunc)
Private Member Functions
void CreateOSPowerCallBacks (void)
void DeleteOSPowerCallBacks (void)
Static Private Member Functions
static void OSPowerCallBack (void *refcon, io_service_t service, natural_t msg_type, void *msg_arg)
static void OSPowerSourceCallBack (void *refcon)
Private Attributes
bool m_OnResume
bool m_OnSuspend
bool m_OnBattery
int m_HasBattery
int m_BatteryPercent
bool m_SentBatteryMessage
io_connect_t m_root_port
io_object_t m_notifier_object
IONotificationPortRef m_notify_port
CFRunLoopSourceRef m_power_source = NULL
Additional Inherited Members
Static Public Attributes inherited from IPowerSyscall
static const int MAX_COUNT_POWER_FEATURES = 4
Constructor & Destructor Documentation
CCocoaPowerSyscall()
CCocoaPowerSyscall::CCocoaPowerSyscall ()
References CreateOSPowerCallBacks(), m_BatteryPercent, m_HasBattery, m_OnBattery, m_OnResume, m_OnSuspend, and m_SentBatteryMessage.
Referenced by CreateInstance().
~CCocoaPowerSyscall()
CCocoaPowerSyscall::~CCocoaPowerSyscall () override
References DeleteOSPowerCallBacks(), and HasBattery().
Member Function Documentation
BatteryLevel()
int CCocoaPowerSyscall::BatteryLevel (void) override virtual
Implements IPowerSyscall.
CanHibernate()
bool CCocoaPowerSyscall::CanHibernate (void) override virtual
Implements IPowerSyscall.
CanPowerdown()
bool CCocoaPowerSyscall::CanPowerdown (void) override virtual
Implements IPowerSyscall.
CanReboot()
bool CCocoaPowerSyscall::CanReboot (void) override virtual
Implements IPowerSyscall.
CanSuspend()
bool CCocoaPowerSyscall::CanSuspend (void) override virtual
Implements IPowerSyscall.
CreateInstance()
IPowerSyscall * CCocoaPowerSyscall::CreateInstance () static
References CCocoaPowerSyscall().
Referenced by Register().
CreateOSPowerCallBacks()
void CCocoaPowerSyscall::CreateOSPowerCallBacks (void) private
References CLog::Log(), LOGERROR, m_HasBattery, m_notifier_object, m_notify_port, m_power_source, m_root_port, OSPowerCallBack(), and OSPowerSourceCallBack().
Referenced by CCocoaPowerSyscall().
DeleteOSPowerCallBacks()
void CCocoaPowerSyscall::DeleteOSPowerCallBacks (void) private
References m_HasBattery, m_notifier_object, m_notify_port, m_power_source, and m_root_port.
Referenced by ~CCocoaPowerSyscall().
HasBattery()
bool CCocoaPowerSyscall::HasBattery (void)
References m_HasBattery.
Referenced by ~CCocoaPowerSyscall().
Hibernate()
bool CCocoaPowerSyscall::Hibernate (void) override virtual
Implements IPowerSyscall.
References CLog::Log(), LOGDEBUG, and Suspend().
OSPowerCallBack()
void CCocoaPowerSyscall::OSPowerCallBack (void * refcon, io_service_t service, natural_t msg_type, void * msg_arg) static private
Todo:
implement
Todo:
implement
References CServiceBroker::GetPowerManager(), m_OnResume, m_OnSuspend, m_root_port, and CPowerManager::ProcessEvents().
Referenced by CreateOSPowerCallBacks().
OSPowerSourceCallBack()
void CCocoaPowerSyscall::OSPowerSourceCallBack (void * refcon) static private
References m_BatteryPercent, m_OnBattery, m_SentBatteryMessage, and stringsAreEqual().
Referenced by CreateOSPowerCallBacks().
Powerdown()
bool CCocoaPowerSyscall::Powerdown (void) override virtual
Implements IPowerSyscall.
References CLog::Log(), LOGDEBUG, LOGINFO, and SendAppleEventToSystemProcess().
PumpPowerEvents()
bool CCocoaPowerSyscall::PumpPowerEvents (IPowerEventsCallback * callback) override virtual
Pump power related events back to xbmc.
PumpPowerEvents is called from Application Thread and the platform implementation may signal power related events back to xbmc through the callback.
return true if an event occurred and false if not.
Parameters
callback the callback to signal to
Implements IPowerSyscall.
References m_BatteryPercent, m_HasBattery, m_OnBattery, m_OnResume, m_OnSuspend, and m_SentBatteryMessage.
Reboot()
bool CCocoaPowerSyscall::Reboot (void) override virtual
Implements IPowerSyscall.
References CLog::Log(), LOGDEBUG, LOGINFO, and SendAppleEventToSystemProcess().
Register()
void CCocoaPowerSyscall::Register () static
References CreateInstance(), and IPowerSyscall::RegisterPowerSyscall().
Referenced by CWinSystemOSX::CWinSystemOSX(), and CPlatformDarwinOSX::InitStageOne().
Suspend()
bool CCocoaPowerSyscall::Suspend (void) override virtual
Implements IPowerSyscall.
References CLog::Log(), LOGDEBUG, LOGINFO, m_OnSuspend, and SendAppleEventToSystemProcess().
Referenced by Hibernate().
Member Data Documentation
m_BatteryPercent
int CCocoaPowerSyscall::m_BatteryPercent private
Referenced by CCocoaPowerSyscall(), OSPowerSourceCallBack(), and PumpPowerEvents().
m_HasBattery
int CCocoaPowerSyscall::m_HasBattery private
Referenced by CCocoaPowerSyscall(), CreateOSPowerCallBacks(), DeleteOSPowerCallBacks(), HasBattery(), and PumpPowerEvents().
m_notifier_object
io_object_t CCocoaPowerSyscall::m_notifier_object private
Referenced by CreateOSPowerCallBacks(), and DeleteOSPowerCallBacks().
m_notify_port
IONotificationPortRef CCocoaPowerSyscall::m_notify_port private
Referenced by CreateOSPowerCallBacks(), and DeleteOSPowerCallBacks().
m_OnBattery
bool CCocoaPowerSyscall::m_OnBattery private
Referenced by CCocoaPowerSyscall(), OSPowerSourceCallBack(), and PumpPowerEvents().
m_OnResume
bool CCocoaPowerSyscall::m_OnResume private
Referenced by CCocoaPowerSyscall(), OSPowerCallBack(), and PumpPowerEvents().
m_OnSuspend
bool CCocoaPowerSyscall::m_OnSuspend private
Referenced by CCocoaPowerSyscall(), OSPowerCallBack(), PumpPowerEvents(), and Suspend().
m_power_source
CFRunLoopSourceRef CCocoaPowerSyscall::m_power_source = NULL private
Referenced by CreateOSPowerCallBacks(), and DeleteOSPowerCallBacks().
m_root_port
io_connect_t CCocoaPowerSyscall::m_root_port private
Referenced by CreateOSPowerCallBacks(), DeleteOSPowerCallBacks(), and OSPowerCallBack().
m_SentBatteryMessage
bool CCocoaPowerSyscall::m_SentBatteryMessage private
Referenced by CCocoaPowerSyscall(), OSPowerSourceCallBack(), and PumpPowerEvents().
The documentation for this class was generated from the following files:
CocoaPowerSyscall.h
CocoaPowerSyscall.cpp