Kodi Documentation: CUPowerSyscall Class Reference
CUPowerSyscall Class Reference
#include <UPowerSyscall.h>
Public Member Functions
CUPowerSyscall ()
bool Powerdown () override
bool Suspend () override
bool Hibernate () override
bool Reboot () override
bool CanPowerdown () override
bool CanSuspend () override
bool CanHibernate () override
bool CanReboot () override
int BatteryLevel () override
bool PumpPowerEvents (IPowerEventsCallback *callback) override
Pump power related events back to xbmc.
Public Member Functions inherited from CAbstractPowerSyscall
int CountPowerFeatures () override
Public Member Functions inherited from IPowerSyscall
virtual ~IPowerSyscall ()=default
Static Public Member Functions
static bool HasUPower ()
Static Public Member Functions inherited from IPowerSyscall
static IPowerSyscall * CreateInstance ()
Called by power manager to create platform power system adapter.
static void RegisterPowerSyscall (CreatePowerSyscallFunc createFunc)
Protected Member Functions
void UpdateCapabilities ()
Protected Attributes
bool m_CanPowerdown
bool m_CanSuspend
bool m_CanHibernate
bool m_CanReboot
Private Member Functions
void EnumeratePowerSources ()
Private Attributes
std::list< CUPowerSource > m_powerSources
CDBusConnection m_connection
bool m_lowBattery
Additional Inherited Members
Static Public Attributes inherited from IPowerSyscall
static const int MAX_COUNT_POWER_FEATURES = 4
Constructor & Destructor Documentation
CUPowerSyscall()
CUPowerSyscall::CUPowerSyscall ()
Todo:
do not use dbus_connection_pop_message() that requires the use of a private connection
References CDBusConnection::Connect(), CDBusConnection::Destroy(), EnumeratePowerSources(), CLog::Log(), CDBusError::Log(), LOGINFO, m_CanPowerdown, m_CanReboot, m_connection, m_lowBattery, and UpdateCapabilities().
Member Function Documentation
BatteryLevel()
int CUPowerSyscall::BatteryLevel (void) override virtual
Implements IPowerSyscall.
References m_powerSources.
CanHibernate()
bool CUPowerSyscall::CanHibernate (void) override virtual
Implements IPowerSyscall.
References m_CanHibernate.
CanPowerdown()
bool CUPowerSyscall::CanPowerdown (void) override virtual
Implements IPowerSyscall.
References m_CanPowerdown.
CanReboot()
bool CUPowerSyscall::CanReboot (void) override virtual
Implements IPowerSyscall.
References m_CanReboot.
CanSuspend()
bool CUPowerSyscall::CanSuspend (void) override virtual
Implements IPowerSyscall.
References m_CanSuspend.
EnumeratePowerSources()
void CUPowerSyscall::EnumeratePowerSources () private
References m_powerSources, and CDBusMessage::SendSystem().
Referenced by CUPowerSyscall().
HasUPower()
bool CUPowerSyscall::HasUPower () static
References CDBusUtil::TryMethodCall().
Referenced by CLinuxPowerSyscall::CreateInstance(), and CConsoleUPowerSyscall::HasConsoleKitAndUPower().
Hibernate()
bool CUPowerSyscall::Hibernate (void) override virtual
Implements IPowerSyscall.
References CDBusMessage::SendAsyncSystem().
Powerdown()
bool CUPowerSyscall::Powerdown (void) override virtual
Implements IPowerSyscall.
PumpPowerEvents()
bool CUPowerSyscall::PumpPowerEvents (IPowerEventsCallback * callback) override virtual
Pump power related events back to xbmc.
PumpPowerEvents is called from Application Thread and the platform implementation may signal power related events back to xbmc through the callback.
return true if an event occurred and false if not.
Parameters
callback the callback to signal to
Implements IPowerSyscall.
References CLog::Log(), LOGDEBUG, m_connection, m_lowBattery, and UpdateCapabilities().
Reboot()
bool CUPowerSyscall::Reboot (void) override virtual
Implements IPowerSyscall.
Suspend()
bool CUPowerSyscall::Suspend (void) override virtual
Implements IPowerSyscall.
References CDBusMessage::SendAsyncSystem().
UpdateCapabilities()
void CUPowerSyscall::UpdateCapabilities () protected
References CVariant::asBoolean(), CDBusUtil::GetVariant(), m_CanHibernate, and m_CanSuspend.
Referenced by CUPowerSyscall(), and PumpPowerEvents().
Member Data Documentation
m_CanHibernate
bool CUPowerSyscall::m_CanHibernate protected
Referenced by CanHibernate(), and UpdateCapabilities().
m_CanPowerdown
bool CUPowerSyscall::m_CanPowerdown protected
Referenced by CanPowerdown(), CConsoleUPowerSyscall::CConsoleUPowerSyscall(), and CUPowerSyscall().
m_CanReboot
bool CUPowerSyscall::m_CanReboot protected
Referenced by CanReboot(), CConsoleUPowerSyscall::CConsoleUPowerSyscall(), and CUPowerSyscall().
m_CanSuspend
bool CUPowerSyscall::m_CanSuspend protected
Referenced by CanSuspend(), and UpdateCapabilities().
m_connection
CDBusConnection CUPowerSyscall::m_connection private
Referenced by CUPowerSyscall(), and PumpPowerEvents().
m_lowBattery
bool CUPowerSyscall::m_lowBattery private
Referenced by CUPowerSyscall(), and PumpPowerEvents().
m_powerSources
std::list<CUPowerSource> CUPowerSyscall::m_powerSources private
Referenced by BatteryLevel(), and EnumeratePowerSources().
The documentation for this class was generated from the following files:
UPowerSyscall.h
UPowerSyscall.cpp