Kodi Documentation: CDVDDemuxUtils Class Reference
CDVDDemuxUtils Class Reference
#include <DVDDemuxUtils.h>
Static Public Member Functions
static void FreeDemuxPacket (DemuxPacket *pPacket)
static DemuxPacket * AllocateDemuxPacket (int iDataSize=0)
static DemuxPacket * AllocateDemuxPacket (unsigned int iDataSize, unsigned int encryptedSubsampleCount)
static void StoreSideData (DemuxPacket *pkt, AVPacket *src)
Member Function Documentation
AllocateDemuxPacket() [1/2]
DemuxPacket * CDVDDemuxUtils::AllocateDemuxPacket (int iDataSize = 0) static
Required number of additionally allocated bytes at the end of the input bitstream for decoding. this is mainly needed because some optimized bitstream readers read 32 or 64 bit at once and could read over the end
Note, if the first 23 bits of the additional bytes are not 0 then damaged MPEG bitstreams could cause overread and segfault
References KODI::MEMORY::AlignedMalloc(), FreeDemuxPacket(), and DEMUX_PACKET::pData.
Referenced by AllocateDemuxPacket(), CInputStreamAddon::cb_allocate_demux_packet(), PVR::CPVRClient::cb_allocate_demux_packet(), CInputStreamAddon::cb_allocate_encrypted_demux_packet(), CDVDDemuxCC::Decode(), CDVDDemuxBXA::Read(), CDVDDemuxCDDA::Read(), CDVDDemuxClient::Read(), and CDVDDemuxFFmpeg::ReadInternal().
AllocateDemuxPacket() [2/2]
DemuxPacket * CDVDDemuxUtils::AllocateDemuxPacket (unsigned int iDataSize, unsigned int encryptedSubsampleCount) static
References AllocateDemuxPacket(), and DEMUX_PACKET::cryptoInfo.
FreeDemuxPacket()
void CDVDDemuxUtils::FreeDemuxPacket (DemuxPacket * pPacket) static
Todo:
: properly handle avpkt side_data. this works around our improper use of the side_data
References KODI::MEMORY::AlignedFree(), DEMUX_PACKET::cryptoInfo, DEMUX_PACKET::iSideDataElems, CLog::Log(), LOGERROR, DEMUX_PACKET::pData, and DEMUX_PACKET::pSideData.
Referenced by AllocateDemuxPacket(), CInputStreamAddon::cb_free_demux_packet(), PVR::CPVRClient::cb_free_demux_packet(), CDVDFileInfo::ExtractThumbToTexture(), CVideoPlayer::Process(), CVideoPlayer::ProcessPacket(), CDVDDemuxClient::Read(), CDVDDemuxFFmpeg::ReadInternal(), VideoPlayerCodec::ReadPCM(), VideoPlayerCodec::ReadRaw(), CDVDDemuxFFmpeg::SeekTime(), and CDVDMsgDemuxerPacket::~CDVDMsgDemuxerPacket().
StoreSideData()
void CDVDDemuxUtils::StoreSideData (DemuxPacket * pkt, AVPacket * src) static
Todo:
: properly handle avpkt side_data. this works around our improper use of the side_data
References DEMUX_PACKET::iSideDataElems, CLog::Log(), LOGERROR, and DEMUX_PACKET::pSideData.
Referenced by CDVDDemuxFFmpeg::ReadInternal().
The documentation for this class was generated from the following files:
DVDDemuxUtils.h
DVDDemuxUtils.cpp