Kodi Documentation: PVR::CPVRGUIChannelIconUpdater Class Reference
PVR::CPVRGUIChannelIconUpdater Class Reference
#include <PVRGUIChannelIconUpdater.h>
Public Member Functions
CPVRGUIChannelIconUpdater (const std::vector< std::shared_ptr< CPVRChannelGroup > > &groups, bool bUpdateDb)
ctor.
CPVRGUIChannelIconUpdater ()=delete
CPVRGUIChannelIconUpdater (const CPVRGUIChannelIconUpdater &)=delete
CPVRGUIChannelIconUpdater & operator= (const CPVRGUIChannelIconUpdater &)=delete
virtual ~CPVRGUIChannelIconUpdater ()=default
void SearchAndUpdateMissingChannelIcons () const
Search and update missing channel icons.
Private Attributes
const std::vector< std::shared_ptr< CPVRChannelGroup > > m_groups
const bool m_bUpdateDb = false
Constructor & Destructor Documentation
CPVRGUIChannelIconUpdater() [1/3]
PVR::CPVRGUIChannelIconUpdater::CPVRGUIChannelIconUpdater (const std::vector< std::shared_ptr< CPVRChannelGroup > > & groups, bool bUpdateDb) inline
ctor.
Parameters
groups The channel groups for which the channel icons shall be updated.
bUpdateDb If true, persist the changed values in the PVR database.
CPVRGUIChannelIconUpdater() [2/3]
PVR::CPVRGUIChannelIconUpdater::CPVRGUIChannelIconUpdater () delete
CPVRGUIChannelIconUpdater() [3/3]
PVR::CPVRGUIChannelIconUpdater::CPVRGUIChannelIconUpdater (const CPVRGUIChannelIconUpdater &) delete
~CPVRGUIChannelIconUpdater()
virtual PVR::CPVRGUIChannelIconUpdater::~CPVRGUIChannelIconUpdater () virtual default
Member Function Documentation
operator=()
CPVRGUIChannelIconUpdater & PVR::CPVRGUIChannelIconUpdater::operator= (const CPVRGUIChannelIconUpdater &) delete
SearchAndUpdateMissingChannelIcons()
void CPVRGUIChannelIconUpdater::SearchAndUpdateMissingChannelIcons () const
Search and update missing channel icons.
References XFILE::DIR_FLAG_DEFAULTS, CFileUtils::Exists(), g_localizeStrings, CLocalizeStrings::Get(), XFILE::CDirectory::GetDirectory(), URIUtils::GetFileName(), CServiceBroker::GetSettingsComponent(), CFileItemList::IsEmpty(), CLog::Log(), LOGINFO, m_bUpdateDb, m_groups, CUtil::MakeLegalFileName(), URIUtils::RemoveExtension(), and CSettings::SETTING_PVRMENU_ICONPATH.
Referenced by PVR::CPVRManager::TriggerSearchMissingChannelIcons().
Member Data Documentation
m_bUpdateDb
const bool PVR::CPVRGUIChannelIconUpdater::m_bUpdateDb = false private
Referenced by SearchAndUpdateMissingChannelIcons().
m_groups
const std::vector<std::shared_ptr<CPVRChannelGroup> > PVR::CPVRGUIChannelIconUpdater::m_groups private
Referenced by SearchAndUpdateMissingChannelIcons().
The documentation for this class was generated from the following files:
PVRGUIChannelIconUpdater.h
PVRGUIChannelIconUpdater.cpp