Kodi Documentation: CDiscDriveHandlerPosix Class Reference
CDiscDriveHandlerPosix Class Reference
#include <DiscDriveHandlerPosix.h>
Public Member Functions
CDiscDriveHandlerPosix ()=default
Posix DiscDriveHandler constructor.
~CDiscDriveHandlerPosix () override=default
Posix DiscDriveHandler default destructor.
DriveState GetDriveState (const std::string &devicePath) override
Get the optical drive state provided its device path.
TrayState GetTrayState (const std::string &devicePath) override
Get the optical drive tray state provided the drive device path.
void EjectDriveTray (const std::string &devicePath) override
Eject the provided drive device.
void CloseDriveTray (const std::string &devicePath) override
Close the provided drive device.
void ToggleDriveTray (const std::string &devicePath) override
Toggle the state of a given drive device.
Additional Inherited Members
Static Public Member Functions inherited from IDiscDriveHandler
static std::shared_ptr< IDiscDriveHandler > CreateInstance ()
Called to create platform-specific disc drive handler.
Protected Member Functions inherited from IDiscDriveHandler
virtual ~IDiscDriveHandler ()=default
IDiscDriveHandler ()=default
Constructor & Destructor Documentation
CDiscDriveHandlerPosix()
CDiscDriveHandlerPosix::CDiscDriveHandlerPosix () default
Posix DiscDriveHandler constructor.
~CDiscDriveHandlerPosix()
CDiscDriveHandlerPosix::~CDiscDriveHandlerPosix () override default
Posix DiscDriveHandler default destructor.
Member Function Documentation
CloseDriveTray()
void CDiscDriveHandlerPosix::CloseDriveTray (const std::string & devicePath) override virtual
Close the provided drive device.
Note
Some drives support closing appart from opening/eject
Parameters
devicePath the path for the device drive (e.g. /dev/sr0)
Implements IDiscDriveHandler.
References MEDIA_DETECT::CLibcdio::GetInstance(), and LOGERROR.
Referenced by ToggleDriveTray().
EjectDriveTray()
void CDiscDriveHandlerPosix::EjectDriveTray (const std::string & devicePath) override virtual
Eject the provided drive device.
Parameters
devicePath the path for the device drive (e.g. /dev/sr0)
Implements IDiscDriveHandler.
References MEDIA_DETECT::CLibcdio::GetInstance(), and LOGERROR.
Referenced by ToggleDriveTray().
GetDriveState()
DriveState CDiscDriveHandlerPosix::GetDriveState (const std::string & devicePath) override virtual
Get the optical drive state provided its device path.
Parameters
devicePath the path for the device drive (e.g. /dev/sr0)
Returns
The drive state
Implements IDiscDriveHandler.
References CLOSED_MEDIA_UNDEFINED, MEDIA_DETECT::CLibcdio::GetInstance(), LOGERROR, LOGWARNING, NOT_READY, and OPEN.
Referenced by ToggleDriveTray().
GetTrayState()
TrayState CDiscDriveHandlerPosix::GetTrayState (const std::string & devicePath) override virtual
Get the optical drive tray state provided the drive device path.
Parameters
devicePath the path for the device drive (e.g. /dev/sr0)
Returns
The drive state
Implements IDiscDriveHandler.
References CLOSED_MEDIA_PRESENT, CLOSED_NO_MEDIA, MEDIA_DETECT::CLibcdio::GetInstance(), LOGERROR, and UNDEFINED.
ToggleDriveTray()
void CDiscDriveHandlerPosix::ToggleDriveTray (const std::string & devicePath) override virtual
Toggle the state of a given drive device.
Will internally call EjectDriveTray or CloseDriveTray depending on the internal state of the drive (i.e. if open -> CloseDriveTray / if closed -> EjectDriveTray)
Parameters
devicePath the path for the device drive (e.g. /dev/sr0)
Implements IDiscDriveHandler.
References CloseDriveTray(), EjectDriveTray(), GetDriveState(), and OPEN.
The documentation for this class was generated from the following files:
DiscDriveHandlerPosix.h
DiscDriveHandlerPosix.cpp