Kodi Documentation: CGUIViewStateVideoMovies Class Reference
CGUIViewStateVideoMovies Class Reference
#include <GUIViewStateVideo.h>
Public Member Functions
CGUIViewStateVideoMovies (const CFileItemList &items)
Public Member Functions inherited from CGUIViewStateWindowVideo
CGUIViewStateWindowVideo (const CFileItemList &items)
Public Member Functions inherited from CGUIViewState
virtual ~CGUIViewState ()
void SetViewAsControl (int viewAsControl)
void SaveViewAsControl (int viewAsControl)
int GetViewAsControl () const
bool ChooseSortMethod ()
SortDescription SetNextSortMethod (int direction=1)
void SetCurrentSortMethod (int method)
SortDescription GetSortMethod () const
bool HasMultipleSortMethods () const
int GetSortMethodLabel () const
int GetSortOrderLabel () const
void GetSortMethodLabelMasks (LABEL_MASKS &masks) const
std::vector< SortDescription > GetSortDescriptions () const
SortOrder SetNextSortOrder ()
SortOrder GetSortOrder () const
virtual bool HideExtensions ()
virtual bool HideParentDirItems ()
virtual bool DisableAddSourceButtons ()
const std::string & GetPlaylistDirectory ()
void SetPlaylistDirectory (const std::string &strDirectory)
bool IsCurrentPlaylistDirectory (const std::string &strDirectory)
Protected Member Functions
void SaveViewState () override
Protected Member Functions inherited from CGUIViewStateWindowVideo
std::vector< CMediaSource > & GetSources () override
std::string GetLockType () override
KODI::PLAYLIST::Id GetPlaylist () const override
std::string GetExtensions () override
bool AutoPlayNextItem () override
Protected Member Functions inherited from CGUIViewState
CGUIViewState (const CFileItemList &items)
virtual void SaveViewToDb (const std::string &path, int windowID, CViewState *viewState=NULL)
void LoadViewState (const std::string &path, int windowID)
void AddLiveTVSources ()
void AddPlaylistOrder (const CFileItemList &items, const LABEL_MASKS &label_masks)
Add the sort order defined in a smartplaylist Defaults to SORT_METHOD_PLAYLIST_ORDER if no order is defined.
void AddSortMethod (SortBy sortBy, int buttonLabel, const LABEL_MASKS &labelMasks, SortAttribute sortAttributes=SortAttributeNone, SortOrder sortOrder=SortOrderNone)
void AddSortMethod (SortBy sortBy, SortAttribute sortAttributes, int buttonLabel, const LABEL_MASKS &labelMasks, SortOrder sortOrder=SortOrderNone)
void AddSortMethod (SortDescription sortDescription, int buttonLabel, const LABEL_MASKS &labelMasks)
void SetSortMethod (SortBy sortBy, SortOrder sortOrder=SortOrderNone)
void SetSortMethod (SortDescription sortDescription)
void SetSortOrder (SortOrder sortOrder)
bool AutoPlayNextVideoItem () const
Additional Inherited Members
Static Public Member Functions inherited from CGUIViewState
static CGUIViewState * GetViewState (int windowId, const CFileItemList &items)
Protected Attributes inherited from CGUIViewState
const CFileItemList & m_items
int m_currentViewAsControl
KODI::PLAYLIST::Id m_playlist
std::vector< GUIViewSortDetails > m_sortMethods
int m_currentSortMethod
Static Protected Attributes inherited from CGUIViewState
static std::vector< CMediaSource > m_sources
static std::string m_strPlaylistDirectory
Constructor & Destructor Documentation
CGUIViewStateVideoMovies()
CGUIViewStateVideoMovies::CGUIViewStateVideoMovies (const CFileItemList & items) explicit
References CGUIViewState::AddPlaylistOrder(), CGUIViewState::AddSortMethod(), CViewStateSettings::Get(), CViewStateSettings::GetInstance(), CFileItem::GetPath(), CServiceBroker::GetSettingsComponent(), CFileItem::IsLibraryFolder(), KODI::PLAYLIST::IsSmartPlayList(), CGUIViewState::LoadViewState(), CViewState::m_sortDescription, CViewState::m_viewMode, CGUIViewState::SetSortMethod(), CGUIViewState::SetSortOrder(), CSettings::SETTING_FILELISTS_IGNORETHEWHENSORTING, CGUIViewState::SetViewAsControl(), SortAttributeIgnoreArticle, SortAttributeNone, SortByDateAdded, SortByMPAA, SortByOriginalTitle, SortByPlaycount, SortByRating, SortBySortTitle, SortByTime, SortByUserRating, SortByYear, SortDescription::sortOrder, and WINDOW_VIDEO_NAV.
Member Function Documentation
SaveViewState()
void CGUIViewStateVideoMovies::SaveViewState () override protected virtual
Implements CGUIViewState.
References CViewStateSettings::Get(), CViewStateSettings::GetInstance(), CFileItem::GetPath(), CGUIViewState::m_items, CGUIViewState::SaveViewToDb(), and WINDOW_VIDEO_NAV.
The documentation for this class was generated from the following files:
GUIViewStateVideo.h
GUIViewStateVideo.cpp