Kodi Documentation: KODI::KEYMAP::CTouchTranslator Class Reference
KODI::KEYMAP::CTouchTranslator Class Reference
#include <TouchTranslator.h>
Classes
struct CTouchAction
Public Member Functions
CTouchTranslator ()=default
void MapActions (int windowID, const tinyxml2::XMLNode *bDevice) override
void Clear () override
bool TranslateTouchAction (int window, int touchAction, int touchPointers, int &action, std::string &actionString)
Public Member Functions inherited from KODI::KEYMAP::IKeyMapper
virtual ~IKeyMapper ()=default
Private Types
using TouchActionKey = unsigned int
using TouchActionMap = std::map< TouchActionKey, CTouchAction >
using WindowID = int
using TouchMap = std::map< WindowID, TouchActionMap >
Private Member Functions
bool TranslateAction (int window, unsigned int touchCommand, int touchPointers, unsigned int &actionId, std::string &actionString)
unsigned int GetActionID (WindowID window, TouchActionKey touchActionKey, std::string &actionString)
Static Private Member Functions
static unsigned int TranslateTouchCommand (const tinyxml2::XMLElement *pButton, CTouchAction &action)
static unsigned int GetTouchActionKey (unsigned int touchCommandId, int touchPointers)
Private Attributes
TouchMap m_touchMap
Member Typedef Documentation
TouchActionKey
using KODI::KEYMAP::CTouchTranslator::TouchActionKey = unsigned int private
TouchActionMap
using KODI::KEYMAP::CTouchTranslator::TouchActionMap = std::map<TouchActionKey, CTouchAction> private
TouchMap
using KODI::KEYMAP::CTouchTranslator::TouchMap = std::map<WindowID, TouchActionMap> private
WindowID
using KODI::KEYMAP::CTouchTranslator::WindowID = int private
Constructor & Destructor Documentation
CTouchTranslator()
KODI::KEYMAP::CTouchTranslator::CTouchTranslator () default
Member Function Documentation
Clear()
void CTouchTranslator::Clear () override virtual
Implements KODI::KEYMAP::IKeyMapper.
References m_touchMap.
GetActionID()
unsigned int CTouchTranslator::GetActionID (WindowID window, TouchActionKey touchActionKey, std::string & actionString) private
References ACTION_NONE, and m_touchMap.
Referenced by TranslateAction().
GetTouchActionKey()
unsigned int CTouchTranslator::GetTouchActionKey (unsigned int touchCommandId, int touchPointers) static private
Referenced by TranslateAction(), and TranslateTouchCommand().
MapActions()
void CTouchTranslator::MapActions (int windowID, const tinyxml2::XMLNode * bDevice) override virtual
Implements KODI::KEYMAP::IKeyMapper.
References ACTION_NONE, m_touchMap, and TranslateTouchCommand().
TranslateAction()
bool CTouchTranslator::TranslateAction (int window, unsigned int touchCommand, int touchPointers, unsigned int & actionId, std::string & actionString) private
References ACTION_NONE, GetActionID(), and GetTouchActionKey().
Referenced by TranslateTouchAction().
TranslateTouchAction()
bool CTouchTranslator::TranslateTouchAction (int window, int touchAction, int touchPointers, int & action, std::string & actionString)
References ACTION_NONE, CWindowTranslator::GetFallbackWindow(), CWindowTranslator::GetVirtualWindow(), and TranslateAction().
TranslateTouchCommand()
unsigned int CTouchTranslator::TranslateTouchCommand (const tinyxml2::XMLElement * pButton, CTouchAction & action) static private
References ACTION_NONE, GetTouchActionKey(), CLog::Log(), LOGERROR, TOUCH_COMMAND_NONE, TouchCommands, and KODI::ACTION::CActionTranslator::TranslateString().
Referenced by MapActions().
Member Data Documentation
m_touchMap
TouchMap KODI::KEYMAP::CTouchTranslator::m_touchMap private
Referenced by Clear(), GetActionID(), and MapActions().
The documentation for this class was generated from the following files:
TouchTranslator.h
TouchTranslator.cpp