Kodi Documentation: memcpy_sse2.h File Reference
memcpy_sse2.h File Reference
Functions
void * memcpy_aligned (void *dst, const void *src, size_t size, uint8_t bpp=0)
void copy_plane (uint8_t *const src, const int srcStride, int height, int width, uint8_t *const dst, const int dstStride, uint8_t bpp=0)
void convert_yuv420_nv12_chrome (uint8_t *const *src, const int *srcStride, int height, int width, uint8_t *const dst, const int dstStride)
void convert_yuv420_p01x_chrome (uint8_t *const *src, const int *srcStride, int height, int width, uint8_t *const dst, const int dstStride, uint8_t bpp)
void convert_yuv420_nv12 (uint8_t *const src[], const int srcStride[], int height, int width, uint8_t *const dst[], const int dstStride[])
void convert_yuv420_p01x (uint8_t *const src[], const int srcStride[], int height, int width, uint8_t *const dst[], const int dstStride[], uint8_t bpp)
Function Documentation
convert_yuv420_nv12()
void convert_yuv420_nv12 (uint8_t *const src[], const int srcStride[], int height, int width, uint8_t *const dst[], const int dstStride[]) inline
References convert_yuv420_nv12_chrome(), and copy_plane().
convert_yuv420_nv12_chrome()
void convert_yuv420_nv12_chrome (uint8_t *const * src, const int * srcStride, int height, int width, uint8_t *const dst, const int dstStride) inline
Referenced by convert_yuv420_nv12(), and CRendererDXVA::CRenderBufferImpl::UploadToTexture().
convert_yuv420_p01x()
void convert_yuv420_p01x (uint8_t *const src[], const int srcStride[], int height, int width, uint8_t *const dst[], const int dstStride[], uint8_t bpp) inline
References convert_yuv420_p01x_chrome(), and copy_plane().
convert_yuv420_p01x_chrome()
void convert_yuv420_p01x_chrome (uint8_t *const * src, const int * srcStride, int height, int width, uint8_t *const dst, const int dstStride, uint8_t bpp) inline
Referenced by convert_yuv420_p01x(), and CRendererDXVA::CRenderBufferImpl::UploadToTexture().
copy_plane()
void copy_plane (uint8_t *const src, const int srcStride, int height, int width, uint8_t *const dst, const int dstStride, uint8_t bpp = 0) inline
References memcpy_aligned().
Referenced by convert_yuv420_nv12(), convert_yuv420_p01x(), and CRendererDXVA::CRenderBufferImpl::UploadToTexture().
memcpy_aligned()
void * memcpy_aligned (void * dst, const void * src, size_t size, uint8_t bpp = 0) inline
References end().
Referenced by copy_plane().