Kodi Documentation: CJSONVariantParserHandler Class Reference
CJSONVariantParserHandler Class Reference
Public Member Functions
CJSONVariantParserHandler (CVariant &parsedObject)
bool Null ()
bool Bool (bool b)
bool Int (int i)
bool Uint (unsigned u)
bool Int64 (int64_t i)
bool Uint64 (uint64_t u)
bool Double (double d)
bool RawNumber (const char *str, rapidjson::SizeType length, bool copy)
bool String (const char *str, rapidjson::SizeType length, bool copy)
bool StartObject ()
bool Key (const char *str, rapidjson::SizeType length, bool copy)
bool EndObject (rapidjson::SizeType memberCount)
bool StartArray ()
bool EndArray (rapidjson::SizeType elementCount)
Private Types
enum class PARSE_STATUS { Variable , Array , Object }
Private Member Functions
template<typename... TArgs>
bool Primitive (TArgs... args)
void PushObject (CVariant variant)
void PopObject ()
Private Attributes
CVariant & m_parsedObject
std::vector< CVariant * > m_parse
std::string m_key
CVariant m_root
PARSE_STATUS m_status = PARSE_STATUS::Variable
Member Enumeration Documentation
PARSE_STATUS
enum class CJSONVariantParserHandler::PARSE_STATUS strong private
Enumerator
Variable
Array
Object
Constructor & Destructor Documentation
CJSONVariantParserHandler()
CJSONVariantParserHandler::CJSONVariantParserHandler (CVariant & parsedObject) explicit
Member Function Documentation
Bool()
bool CJSONVariantParserHandler::Bool (bool b)
References Primitive().
Double()
bool CJSONVariantParserHandler::Double (double d)
References Primitive().
EndArray()
bool CJSONVariantParserHandler::EndArray (rapidjson::SizeType elementCount)
References PopObject().
EndObject()
bool CJSONVariantParserHandler::EndObject (rapidjson::SizeType memberCount)
References PopObject().
Int()
bool CJSONVariantParserHandler::Int (int i)
References Primitive().
Int64()
bool CJSONVariantParserHandler::Int64 (int64_t i)
References Primitive().
Key()
bool CJSONVariantParserHandler::Key (const char * str, rapidjson::SizeType length, bool copy)
References m_key.
Null()
bool CJSONVariantParserHandler::Null ()
References CVariant::ConstNullVariant, PopObject(), and PushObject().
PopObject()
void CJSONVariantParserHandler::PopObject () private
References Array, m_parse, m_parsedObject, m_status, Object, and Variable.
Referenced by EndArray(), EndObject(), Null(), and Primitive().
Primitive()
template<typename... TArgs> bool CJSONVariantParserHandler::Primitive (TArgs... args) inline private
References PopObject(), and PushObject().
Referenced by Bool(), Double(), Int(), Int64(), RawNumber(), String(), Uint(), and Uint64().
PushObject()
void CJSONVariantParserHandler::PushObject (CVariant variant) private
References Array, m_key, m_parse, m_root, m_status, Object, CVariant::push_back(), CVariant::size(), Variable, CVariant::VariantTypeArray, and CVariant::VariantTypeObject.
Referenced by Null(), Primitive(), StartArray(), and StartObject().
RawNumber()
bool CJSONVariantParserHandler::RawNumber (const char * str, rapidjson::SizeType length, bool copy)
References Primitive().
StartArray()
bool CJSONVariantParserHandler::StartArray ()
References PushObject(), and CVariant::VariantTypeArray.
StartObject()
bool CJSONVariantParserHandler::StartObject ()
References PushObject(), and CVariant::VariantTypeObject.
String()
bool CJSONVariantParserHandler::String (const char * str, rapidjson::SizeType length, bool copy)
References Primitive().
Uint()
bool CJSONVariantParserHandler::Uint (unsigned u)
References Primitive().
Uint64()
bool CJSONVariantParserHandler::Uint64 (uint64_t u)
References Primitive().
Member Data Documentation
m_key
std::string CJSONVariantParserHandler::m_key private
Referenced by Key(), and PushObject().
m_parse
std::vector<CVariant *> CJSONVariantParserHandler::m_parse private
Referenced by PopObject(), and PushObject().
m_parsedObject
CVariant& CJSONVariantParserHandler::m_parsedObject private
Referenced by PopObject().
m_root
CVariant CJSONVariantParserHandler::m_root private
Referenced by PushObject().
m_status
PARSE_STATUS CJSONVariantParserHandler::m_status = PARSE_STATUS::Variable private
Referenced by PopObject(), and PushObject().
The documentation for this class was generated from the following file:
JSONVariantParser.cpp