Kodi Documentation: KODI::RETRO::CGUIPlaybackControl Class Reference
KODI::RETRO::CGUIPlaybackControl Class Reference
Class to control playback by monitoring OSD status.
#include <GUIPlaybackControl.h>
Public Member Functions
CGUIPlaybackControl (IPlaybackCallback &callback)
~CGUIPlaybackControl () override
void FrameMove () override
Called every frame.
Public Member Functions inherited from KODI::RETRO::IPlaybackControl
virtual ~IPlaybackControl ()=default
Private Types
enum class GuiState { UNKNOWN , FULLSCREEN , MENU_PAUSED , MENU_PLAYING }
Private Member Functions
GuiState NextState (bool bFullscreen, bool bInMenu, bool bInBackground)
Static Private Member Functions
static double GetTargetSpeed (GuiState state)
static bool AcceptsInput (GuiState state)
Private Attributes
IPlaybackCallback & m_callback
GuiState m_state = GuiState::UNKNOWN
double m_previousSpeed = 0.0
Detailed Description
Class to control playback by monitoring OSD status.
Member Enumeration Documentation
GuiState
enum class KODI::RETRO::CGUIPlaybackControl::GuiState strong private
Enumerator
UNKNOWN
FULLSCREEN
MENU_PAUSED
MENU_PLAYING
Constructor & Destructor Documentation
CGUIPlaybackControl()
CGUIPlaybackControl::CGUIPlaybackControl (IPlaybackCallback & callback)
~CGUIPlaybackControl()
CGUIPlaybackControl::~CGUIPlaybackControl () override default
Member Function Documentation
AcceptsInput()
bool CGUIPlaybackControl::AcceptsInput (GuiState state) static private
References FULLSCREEN.
Referenced by FrameMove().
FrameMove()
void CGUIPlaybackControl::FrameMove () override virtual
Called every frame.
Implements KODI::RETRO::IPlaybackControl.
References AcceptsInput(), KODI::RETRO::IPlaybackCallback::EnableInput(), CServiceBroker::GetGUI(), GetTargetSpeed(), CGUIComponent::GetWindowManager(), m_callback, m_previousSpeed, m_state, NextState(), KODI::GAME::CDialogGameOSD::PlayInBackground(), KODI::RETRO::IPlaybackCallback::SetPlaybackSpeed(), and WINDOW_FULLSCREEN_GAME.
GetTargetSpeed()
double CGUIPlaybackControl::GetTargetSpeed (GuiState state) static private
References FULLSCREEN, MENU_PAUSED, and MENU_PLAYING.
Referenced by FrameMove().
NextState()
CGUIPlaybackControl::GuiState CGUIPlaybackControl::NextState (bool bFullscreen, bool bInMenu, bool bInBackground) private
References FULLSCREEN, m_state, MENU_PAUSED, MENU_PLAYING, and UNKNOWN.
Referenced by FrameMove().
Member Data Documentation
m_callback
IPlaybackCallback& KODI::RETRO::CGUIPlaybackControl::m_callback private
Referenced by FrameMove().
m_previousSpeed
double KODI::RETRO::CGUIPlaybackControl::m_previousSpeed = 0.0 private
Referenced by FrameMove().
m_state
GuiState KODI::RETRO::CGUIPlaybackControl::m_state = GuiState::UNKNOWN private
Referenced by FrameMove(), and NextState().
The documentation for this class was generated from the following files:
GUIPlaybackControl.h
GUIPlaybackControl.cpp