Kodi Documentation: CEGLImage Class Reference
CEGLImage Class Reference
#include <EGLImage.h>
Classes
struct EglAttrs
struct EglPlane
Public Member Functions
CEGLImage (EGLDisplay display)
CEGLImage (CEGLImage const &other)=delete
CEGLImage & operator= (CEGLImage const &other)=delete
bool CreateImage (EglAttrs imageAttrs)
void UploadImage (GLenum textureTarget)
void DestroyImage ()
Static Public Attributes
static const int MAX_NUM_PLANES {3}
Private Attributes
EGLDisplay m_display {nullptr}
EGLImageKHR m_image {nullptr}
PFNEGLCREATEIMAGEKHRPROC m_eglCreateImageKHR {nullptr}
PFNEGLDESTROYIMAGEKHRPROC m_eglDestroyImageKHR {nullptr}
PFNGLEGLIMAGETARGETTEXTURE2DOESPROC m_glEGLImageTargetTexture2DOES {nullptr}
Constructor & Destructor Documentation
CEGLImage() [1/2]
CEGLImage::CEGLImage (EGLDisplay display) explicit
CEGLImage() [2/2]
CEGLImage::CEGLImage (CEGLImage const & other) delete
Member Function Documentation
CreateImage()
bool CEGLImage::CreateImage (EglAttrs imageAttrs)
References CEGLAttributes< AttributeCount >::Add(), CEGLImage::EglAttrs::colorRange, CEGLImage::EglAttrs::colorSpace, CEGLImage::EglAttrs::format, DRMHELPERS::FourCCToString(), CEGLAttributes< AttributeCount >::Get(), CServiceBroker::GetLogging(), CEGLImage::EglAttrs::height, CLog::Log(), LOGDEBUG, LOGERROR, LOGVIDEO, m_display, m_eglCreateImageKHR, m_image, MAX_NUM_PLANES, CEGLImage::EglAttrs::planes, CEGLAttributes< AttributeCount >::Size(), and CEGLImage::EglAttrs::width.
DestroyImage()
void CEGLImage::DestroyImage ()
References m_display, m_eglDestroyImageKHR, and m_image.
operator=()
CEGLImage & CEGLImage::operator= (CEGLImage const & other) delete
UploadImage()
void CEGLImage::UploadImage (GLenum textureTarget)
References m_glEGLImageTargetTexture2DOES, and m_image.
Member Data Documentation
m_display
EGLDisplay CEGLImage::m_display {nullptr} private
Referenced by CreateImage(), and DestroyImage().
m_eglCreateImageKHR
PFNEGLCREATEIMAGEKHRPROC CEGLImage::m_eglCreateImageKHR {nullptr} private
Referenced by CreateImage().
m_eglDestroyImageKHR
PFNEGLDESTROYIMAGEKHRPROC CEGLImage::m_eglDestroyImageKHR {nullptr} private
Referenced by DestroyImage().
m_glEGLImageTargetTexture2DOES
PFNGLEGLIMAGETARGETTEXTURE2DOESPROC CEGLImage::m_glEGLImageTargetTexture2DOES {nullptr} private
Referenced by UploadImage().
m_image
EGLImageKHR CEGLImage::m_image {nullptr} private
Referenced by CreateImage(), DestroyImage(), and UploadImage().
MAX_NUM_PLANES
const int CEGLImage::MAX_NUM_PLANES {3} static
Referenced by CreateImage().
The documentation for this class was generated from the following files:
EGLImage.h
EGLImage.cpp