Kodi Documentation: anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob Class Reference
anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob Class Reference
Public Member Functions
CAddonInstallJob (const ADDON::AddonPtr &addon, const ADDON::RepositoryPtr &repo, AutoUpdateJob isAutoUpdate)
bool DoWork () override
Main workhorse function of CJob instances.
const char * GetType () const override
Returns the current processing type in the installation job.
void SetDependsInstall (DependencyJob dependsInstall)
void SetAllowCheckForUpdates (AllowCheckForUpdates allowCheckForUpdates)
Public Member Functions inherited from CFileOperationJob
CFileOperationJob ()
CFileOperationJob (FileAction action, CFileItemList &items, const std::string &strDestFile, bool displayProgress=false, int errorHeading=0, int errorLine=0)
bool DoWork () override
Main workhorse function of CJob instances.
const char * GetType () const override
Function that returns the type of job.
bool operator== (const CJob *job) const override
void SetFileOperation (FileAction action, const CFileItemList &items, const std::string &strDestFile)
const std::string & GetAverageSpeed () const
const std::string & GetCurrentOperation () const
const std::string & GetCurrentFile () const
const CFileItemList & GetItems () const
FileAction GetAction () const
int GetHeading () const
int GetLine () const
Public Member Functions inherited from CProgressJob
~CProgressJob () override
const char * GetType () const override
Function that returns the type of job.
bool operator== (const CJob *job) const override
bool ShouldCancel (unsigned int progress, unsigned int total) const override
Function for longer jobs to report progress and check whether they have been cancelled.
bool DoModal ()
Executes the job showing a modal progress dialog.
void SetProgressIndicators (CGUIDialogProgressBarHandle *progressBar, CGUIDialogProgress *progressDialog, bool updateProgress=true, bool updateInformation=true)
Sets the given progress indicators to be used during execution of the job.
bool HasProgressIndicator () const
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
Static Public Member Functions
static bool GetAddon (const std::string &addonID, ADDON::RepositoryPtr &repo, ADDON::AddonPtr &addon)
Find the add-on and its repository for the given add-on ID.
Static Public Member Functions inherited from CFileOperationJob
static std::string GetActionString (FileAction action)
Static Public Attributes
static constexpr const char * TYPE_DOWNLOAD = "DOWNLOAD"
static constexpr const char * TYPE_INSTALL = "INSTALL"
Private Member Functions
void OnPreInstall ()
void OnPostInstall ()
bool Install (const std::string &installFrom, const ADDON::RepositoryPtr &repo=ADDON::RepositoryPtr())
bool DownloadPackage (const std::string &path, const std::string &dest)
bool DoFileOperation (FileAction action, CFileItemList &items, const std::string &file, bool useSameJob=true)
void ReportInstallError (const std::string &addonID, const std::string &fileName, const std::string &message="")
Queue a notification for addon installation/update failure.
Private Attributes
ADDON::AddonPtr m_addon
ADDON::RepositoryPtr m_repo
bool m_isUpdate
AutoUpdateJob m_isAutoUpdate
DependencyJob m_dependsInstall = DependencyJob::CHOICE_NO
AllowCheckForUpdates m_allowCheckForUpdates = AllowCheckForUpdates::CHOICE_YES
const char * m_currentType = TYPE_DOWNLOAD
Additional Inherited Members
Public Types inherited from CFileOperationJob
enum FileAction {
ActionCopy = 1 , ActionMove , ActionDelete , ActionReplace ,
ActionCreateFolder , ActionDeleteFolder
}
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Protected Member Functions inherited from CProgressJob
CProgressJob ()
CProgressJob (CGUIDialogProgressBarHandle *progressBar)
bool IsModal () const
Whether the job is being run modally or in the background.
CGUIDialogProgressBarHandle * GetProgressBar () const
Returns the progress bar indicating the progress of the job.
void SetProgressBar (CGUIDialogProgressBarHandle *progress)
Sets the progress bar indicating the progress of the job.
CGUIDialogProgress * GetProgressDialog () const
Returns the progress dialog indicating the progress of the job.
void SetProgressDialog (CGUIDialogProgress *progressDialog)
Sets the progress bar indicating the progress of the job.
bool GetAutoClose ()
Whether to automatically close the progress indicator in MarkFinished().
void SetAutoClose (bool autoClose)
Set whether to automatically close the progress indicator in MarkFinished().
bool GetUpdateProgress ()
Whether to update the progress bar or not.
void SetUpdateProgress (bool updateProgress)
Set whether to update the progress bar or not.
bool GetUpdateInformation ()
Whether to update the progress information or not.
void SetUpdateInformation (bool updateInformation)
Set whether to update the progress information or not.
void ShowProgressDialog () const
Makes sure that the modal dialog is being shown.
void SetTitle (const std::string &title)
Sets the given title as the title of the progress bar.
void SetText (const std::string &text)
Sets the given text as the description of the progress bar.
void SetProgress (float percentage) const
Sets the progress of the progress bar to the given value in percentage.
void SetProgress (int currentStep, int totalSteps) const
Sets the progress of the progress bar to the given value.
void MarkFinished ()
Marks the progress as finished by setting it to 100%.
bool IsCancelled () const
Checks if the progress dialog has been cancelled.
Constructor & Destructor Documentation
CAddonInstallJob()
CAddonInstallJob::CAddonInstallJob (const ADDON::AddonPtr & addon, const ADDON::RepositoryPtr & repo, AutoUpdateJob isAutoUpdate)
References ADDON::CAddonMgr::GetAddon(), CServiceBroker::GetAddonMgr(), and m_isUpdate.
Member Function Documentation
DoFileOperation()
bool CAddonInstallJob::DoFileOperation (FileAction action, CFileItemList & items, const std::string & file, bool useSameJob = true) private
References CFileOperationJob::DoWork(), CProgressJob::GetAutoClose(), CProgressJob::GetProgressBar(), CProgressJob::GetProgressDialog(), CProgressJob::GetUpdateInformation(), CProgressJob::GetUpdateProgress(), CProgressJob::SetAutoClose(), CFileOperationJob::SetFileOperation(), CProgressJob::SetProgressIndicators(), and CProgressJob::SetUpdateInformation().
Referenced by DownloadPackage().
DownloadPackage()
bool CAddonInstallJob::DownloadPackage (const std::string & path, const std::string & dest) private
References CFileOperationJob::ActionReplace, CFileItemList::Add(), DoFileOperation(), g_localizeStrings, CLocalizeStrings::Get(), CGUIListItem::Select(), CProgressJob::SetText(), and CProgressJob::ShouldCancel().
DoWork()
bool CAddonInstallJob::DoWork () override virtual
Main workhorse function of CJob instances.
All CJob subclasses must implement this function, performing all processing. Once this function is complete, the OnJobComplete() callback is called, and the job is then destroyed.
See also
CJobManager, IJobCallback::OnJobComplete()
Todo:
fix design flaw in file copying: We use CFileOperationJob to download the package from the internet
Implements CJob.
References URIUtils::AddFileToFolder(), ADDON::CAddonDatabase::AddPackage(), ADDON::CAddonMgr::AddUpdateRuleToList(), ADDON::CRepositoryUpdater::CheckForUpdates(), URIUtils::CreateArchivePath(), CURL, XFILE::CFile::Delete(), ADDON::CRepository::ResolveResult::digest, XFILE::DIR_FLAG_DEFAULTS, ADDON::CAddonMgr::DisableAddon(), KODI::UTILITY::TypedDigest::Empty(), XFILE::CFile::Exists(), g_localizeStrings, CLocalizeStrings::Get(), ADDON::CAddonMgr::GetAddon(), CServiceBroker::GetAddonMgr(), ADDON::CAddonMgr::GetCompatibleVersions(), XFILE::CDirectory::GetDirectory(), CServiceBroker::GetEventLog(), CUtil::GetFileDigest(), URIUtils::GetFileName(), ADDON::CAddonInstaller::GetInstance(), ADDON::CAddonDatabase::GetPackageHash(), CFileItem::GetPath(), CServiceBroker::GetRepositoryUpdater(), CServiceBroker::GetSettingsComponent(), URIUtils::HasSlashAtEnd(), Install(), CProgressJob::IsModal(), ADDON::CAddonMgr::LoadAddonDescription(), CLocalizeStrings::LoadAddonStrings(), ADDON::CRepository::ResolveResult::location, CLog::Log(), LOGDEBUG, LOGERROR, m_addon, m_allowCheckForUpdates, CGUIListItem::m_bIsFolder, m_currentType, m_dependsInstall, m_isAutoUpdate, m_isUpdate, m_repo, CProgressJob::MarkFinished(), ADDON::OnPostInstall(), ADDON::OnPreInstall(), ADDON::CAddonDatabase::Open(), ADDON::ORIGIN_SYSTEM, ADDON::CAddonDatabase::RemovePackage(), ADDON::CAddonMgr::RemoveUpdateRuleFromList(), ReportInstallError(), ADDON::CAddonMgr::SetAddonOrigin(), CProgressJob::SetProgress(), CProgressJob::SetText(), CSettings::SETTING_ADDONS_NOTIFICATIONS, CSettings::SETTING_LOCALE_LANGUAGE, CProgressJob::SetTitle(), CFileItemList::Size(), URIUtils::Split(), text, KODI::UTILITY::TypedDigest::type, TYPE_DOWNLOAD, TYPE_INSTALL, and KODI::UTILITY::TypedDigest::value.
GetAddon()
bool CAddonInstallJob::GetAddon (const std::string & addonID, ADDON::RepositoryPtr & repo, ADDON::AddonPtr & addon) static
Find the add-on and its repository for the given add-on ID.
Parameters
addonID ID of the add-on to find
[out] repo the repository to use
[out] addon Add-on with the given add-on ID
Returns
True if the add-on and its repository were found, false otherwise.
References GetAddon(), and CServiceBroker::GetAddonMgr().
Referenced by GetAddon(), ADDON::CAddonInstaller::InstallAddons(), and ADDON::CAddonInstaller::InstallOrUpdate().
GetType()
const char * anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::GetType () const inline override virtual
Returns the current processing type in the installation job.
Returns
The current processing type as string, can be TYPE_DOWNLOAD or TYPE_INSTALL
Reimplemented from CJob.
Install()
bool CAddonInstallJob::Install (const std::string & installFrom, const ADDON::RepositoryPtr & repo = ADDON::RepositoryPtr()) private
References ADDON::CAddonVersion::asString(), CProgressJob::DoModal(), ADDON::CAddonRepos::FindDependency(), g_localizeStrings, CLocalizeStrings::Get(), ADDON::CAddonMgr::GetAddon(), CServiceBroker::GetAddonMgr(), ADDON::CAddonInstaller::GetInstance(), CProgressJob::GetProgressBar(), CProgressJob::GetProgressDialog(), CFilesystemInstaller::InstallToFilesystem(), CProgressJob::IsModal(), ADDON::CAddonRepos::IsValid(), CLog::Log(), LOGERROR, m_addon, ReportInstallError(), SetDependsInstall(), CProgressJob::SetProgress(), CProgressJob::SetProgressIndicators(), CProgressJob::SetText(), CProgressJob::ShouldCancel(), and KODI::TIME::Sleep().
Referenced by DoWork().
OnPostInstall()
void anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::OnPostInstall () private
OnPreInstall()
void anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::OnPreInstall () private
ReportInstallError()
void CAddonInstallJob::ReportInstallError (const std::string & addonID, const std::string & fileName, const std::string & message = "") private
Queue a notification for addon installation/update failure.
Parameters
addonID - addon id
fileName - filename which is shown in case the addon id is unknown
message - error message to be displayed
References Error, ADDON::CAddonMgr::FindInstallableById(), g_localizeStrings, CLocalizeStrings::Get(), ADDON::CAddonMgr::GetAddon(), CServiceBroker::GetAddonMgr(), CServiceBroker::GetEventLog(), CProgressJob::IsModal(), m_addon, CProgressJob::MarkFinished(), KODI::MESSAGING::HELPERS::ShowOKDialogText(), and success.
Referenced by DoWork(), and Install().
SetAllowCheckForUpdates()
void anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::SetAllowCheckForUpdates (AllowCheckForUpdates allowCheckForUpdates) inline
SetDependsInstall()
void anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::SetDependsInstall (DependencyJob dependsInstall) inline
Referenced by Install().
Member Data Documentation
m_addon
ADDON::AddonPtr anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::m_addon private
Referenced by DoWork(), Install(), and ReportInstallError().
m_allowCheckForUpdates
AllowCheckForUpdates anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::m_allowCheckForUpdates = AllowCheckForUpdates::CHOICE_YES private
Referenced by DoWork().
m_currentType
const char* anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::m_currentType = TYPE_DOWNLOAD private
Referenced by DoWork().
m_dependsInstall
DependencyJob anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::m_dependsInstall = DependencyJob::CHOICE_NO private
Referenced by DoWork().
m_isAutoUpdate
AutoUpdateJob anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::m_isAutoUpdate private
Referenced by DoWork().
m_isUpdate
bool anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::m_isUpdate private
Referenced by CAddonInstallJob(), and DoWork().
m_repo
ADDON::RepositoryPtr anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::m_repo private
Referenced by DoWork().
TYPE_DOWNLOAD
constexpr const char* anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::TYPE_DOWNLOAD = "DOWNLOAD" static constexpr
Referenced by DoWork().
TYPE_INSTALL
constexpr const char* anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::TYPE_INSTALL = "INSTALL" static constexpr
Referenced by DoWork(), and ADDON::CAddonInstaller::OnJobProgress().
The documentation for this class was generated from the following file:
AddonInstaller.cpp