Kodi Documentation: XBMCAddon::xbmcvfs Namespace Reference
XBMCAddon::xbmcvfs Namespace Reference
Classes
class File
class Stat
Functions
bool copy (const String &strSource, const String &strDestination)
bool deleteFile (const String &strSource)
bool rename (const String &file, const String &newFile)
bool exists (const String &path)
String makeLegalFilename (const String &filename)
String translatePath (const String &path)
String validatePath (const String &path)
bool mkdir (const String &path)
bool mkdirs (const String &path)
bool rmdir (const String &path, bool force)
Tuple< std::vector< String >, std::vector< String > > listdir (const String &path)
Function Documentation
copy()
bool XBMCAddon::xbmcvfs::copy (const String & strSource, const String & strDestination)
References XFILE::CFile::Copy().
deleteFile()
bool XBMCAddon::xbmcvfs::deleteFile (const String & strSource)
References XFILE::CFile::Delete().
exists()
bool XBMCAddon::xbmcvfs::exists (const String & path)
References XFILE::CFile::Exists(), XFILE::CDirectory::Exists(), and URIUtils::HasSlashAtEnd().
listdir()
Tuple< std::vector< String >, std::vector< String > > XBMCAddon::xbmcvfs::listdir (const String & path)
References XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::CDirectory::GetDirectory(), URIUtils::GetFileName(), CURL::GetHostName(), CFileItem::GetPath(), URIUtils::HasSlashAtEnd(), URIUtils::RemoveSlashAtEnd(), and CFileItemList::Size().
makeLegalFilename()
String XBMCAddon::xbmcvfs::makeLegalFilename (const String & filename)
References CUtil::MakeLegalPath(), and XBMC_TRACE.
mkdir()
bool XBMCAddon::xbmcvfs::mkdir (const String & path)
References XFILE::CDirectory::Create().
mkdirs()
bool XBMCAddon::xbmcvfs::mkdirs (const String & path)
References CUtil::CreateDirectoryEx().
rename()
bool XBMCAddon::xbmcvfs::rename (const String & file, const String & newFile)
References XFILE::CFile::Rename().
rmdir()
bool XBMCAddon::xbmcvfs::rmdir (const String & path, bool force)
References CFileUtils::DeleteItem(), and XFILE::CDirectory::Remove().
translatePath()
String XBMCAddon::xbmcvfs::translatePath (const String & path)
References CSpecialProtocol::TranslatePath(), and XBMC_TRACE.
validatePath()
String XBMCAddon::xbmcvfs::validatePath (const String & path)
References CUtil::ValidatePath(), and XBMC_TRACE.