Kodi Documentation: AESinkDARWINTVOS.mm File Reference
AESinkDARWINTVOS.mm File Reference
#include "AESinkDARWINTVOS.h"
#include "ServiceBroker.h"
#include "cores/AudioEngine/AESinkFactory.h"
#include "cores/AudioEngine/Sinks/darwin/CoreAudioHelpers.h"
#include "cores/AudioEngine/Utils/AERingBuffer.h"
#include "cores/AudioEngine/Utils/AEUtil.h"
#include "threads/Condition.h"
#include "threads/SystemClock.h"
#include "utils/StringUtils.h"
#include "utils/log.h"
#include "windowing/WinSystem.h"
#include "platform/darwin/DarwinUtils.h"
#include <mutex>
#include <sstream>
import <AVFoundation/AVAudioSession.h>
#include <AudioToolbox/AudioToolbox.h>
#include <unistd.h>
Classes
class CAAudioUnitSink
Enumerations
enum CAChannelIndex { CAChannel_PCM_6CHAN = 0 , CAChannel_PCM_8CHAN = 1 , CAChannel_PCM_DD5_1 = 2 }
Functions
static std::string getAudioRoute ()
static void dumpAVAudioSessionProperties ()
static bool deactivateAudioSession (int count)
static void setAVAudioSessionProperties (NSTimeInterval bufferseconds, double samplerate, int channels)
void LogLevel (unsigned int got, unsigned int wanted)
static void EnumerateDevices (AEDeviceInfoList &list)
Variables
static enum AEChannel CAChannelMap [3][9]
CCriticalSection mutex
XbmcThreads::ConditionVariable condVar
Enumeration Type Documentation
CAChannelIndex
enum CAChannelIndex
Enumerator
CAChannel_PCM_6CHAN
CAChannel_PCM_8CHAN
CAChannel_PCM_DD5_1
Function Documentation
deactivateAudioSession()
static bool deactivateAudioSession (int count) static
References deactivateAudioSession(), err(), CLog::Log(), and LOGWARNING.
Referenced by deactivateAudioSession(), and setAVAudioSessionProperties().
dumpAVAudioSessionProperties()
static void dumpAVAudioSessionProperties () static
References getAudioRoute(), CLog::Log(), and LOGINFO.
EnumerateDevices()
static void EnumerateDevices (AEDeviceInfoList & list) static
References AE_CH_LAYOUT_5_1, AE_CH_LAYOUT_7_1, AE_DEVTYPE_HDMI, AE_FMT_FLOAT, AE_FMT_RAW, AE_FMT_S16LE, CLog::Log(), LOGDEBUG, CAEDeviceInfo::m_channels, CAEDeviceInfo::m_dataFormats, CAEDeviceInfo::m_deviceName, CAEDeviceInfo::m_deviceType, CAEDeviceInfo::m_displayName, CAEDeviceInfo::m_displayNameExtra, CAEDeviceInfo::m_sampleRates, CAEDeviceInfo::m_streamTypes, CAEDeviceInfo::m_wantsIECPassthrough, CAEStreamInfo::STREAM_TYPE_AC3, CAEStreamInfo::STREAM_TYPE_DTS_1024, CAEStreamInfo::STREAM_TYPE_DTS_2048, CAEStreamInfo::STREAM_TYPE_DTS_512, CAEStreamInfo::STREAM_TYPE_DTSHD_CORE, and CAEStreamInfo::STREAM_TYPE_EAC3.
getAudioRoute()
static std::string getAudioRoute () static
Referenced by dumpAVAudioSessionProperties(), and CAESinkDARWINTVOS::Initialize().
LogLevel()
void LogLevel (unsigned int got, unsigned int wanted) inline
References CLog::Log(), and LOGWARNING.
Referenced by CAAudioUnitSink::renderCallback().
setAVAudioSessionProperties()
static void setAVAudioSessionProperties (NSTimeInterval bufferseconds, double samplerate, int channels) static
References deactivateAudioSession(), err(), CLog::Log(), and LOGWARNING.
Variable Documentation
CAChannelMap
enum AEChannel CAChannelMap[3][9] static
Initial value:
= {
    {AE_CH_FL, AE_CH_FR, AE_CH_LFE, AE_CH_FC, AE_CH_BL, AE_CH_BR, AE_CH_NULL},
    {AE_CH_FL, AE_CH_FR, AE_CH_LFE, AE_CH_FC, AE_CH_SL, AE_CH_SR, AE_CH_BL, AE_CH_BR, AE_CH_NULL},
    {AE_CH_FL, AE_CH_FC, AE_CH_FR, AE_CH_BL, AE_CH_BR, AE_CH_LFE, AE_CH_NULL},
}
condVar
XbmcThreads::ConditionVariable condVar
Referenced by CAAudioUnitSink::drain(), CAAudioUnitSink::renderCallback(), CAAudioUnitSink::write(), and CAAudioUnitSink::write().
mutex
CCriticalSection mutex
Referenced by CAAudioUnitSink::drain(), CAAudioUnitSink::write(), and CAAudioUnitSink::write().