Kodi Documentation: CNativeWindow Class Reference
CNativeWindow Class Reference
#include <XBMCApp.h>
Public Member Functions
~CNativeWindow ()
bool SetBuffersGeometry (int width, int height, int format)
int32_t GetWidth () const
int32_t GetHeight () const
Static Public Member Functions
static std::shared_ptr< CNativeWindow > CreateFromSurface (CJNISurfaceHolder holder)
Private Member Functions
CNativeWindow (ANativeWindow *window)
CNativeWindow ()=delete
CNativeWindow (const CNativeWindow &)=delete
CNativeWindow & operator= (const CNativeWindow &)=delete
Private Attributes
ANativeWindow * m_window {nullptr}
Friends
class CWinSystemAndroidGLESContext
Constructor & Destructor Documentation
~CNativeWindow()
CNativeWindow::~CNativeWindow ()
References m_window.
CNativeWindow() [1/3]
CNativeWindow::CNativeWindow (ANativeWindow * window) explicit private
CNativeWindow() [2/3]
CNativeWindow::CNativeWindow () private delete
Referenced by CreateFromSurface().
CNativeWindow() [3/3]
CNativeWindow::CNativeWindow (const CNativeWindow &) private delete
Member Function Documentation
CreateFromSurface()
std::shared_ptr< CNativeWindow > CNativeWindow::CreateFromSurface (CJNISurfaceHolder holder) static
References CNativeWindow().
Referenced by CXBMCApp::surfaceCreated().
GetHeight()
int32_t CNativeWindow::GetHeight () const
References m_window.
GetWidth()
int32_t CNativeWindow::GetWidth () const
References m_window.
operator=()
CNativeWindow & CNativeWindow::operator= (const CNativeWindow &) private delete
SetBuffersGeometry()
bool CNativeWindow::SetBuffersGeometry (int width, int height, int format)
References m_window.
Friends And Related Symbol Documentation
CWinSystemAndroidGLESContext
friend class CWinSystemAndroidGLESContext friend
Member Data Documentation
m_window
ANativeWindow* CNativeWindow::m_window {nullptr} private
Referenced by GetHeight(), GetWidth(), SetBuffersGeometry(), and ~CNativeWindow().
The documentation for this class was generated from the following files:
XBMCApp.h
XBMCApp.cpp