Kodi Documentation: CGUIStaticItem Class Reference
CGUIStaticItem Class Reference
Guilib classes » Lists | Guilib classes » Items
wrapper class for a static item in a list container
#include <GUIStaticItem.h>
Public Member Functions
CGUIStaticItem (const TiXmlElement *element, int contextWindow)
constructor Construct an item based on an XML description: <label>$INFO[MusicPlayer.Artist]</label> <label2>$INFO[MusicPlayer.Album]</label2> <thumb>bar.png</thumb> <icon>foo.jpg</icon> <onclick>ActivateWindow(Home)</onclick>
CGUIStaticItem (const CFileItem &item)
CGUIStaticItem (const CGUIStaticItem &other)
~CGUIStaticItem () override=default
CGUIListItem * Clone () const override
void UpdateProperties (int contextWindow)
update any infolabels in the items properties Runs through all the items properties, updating any that should be periodically recomputed
bool UpdateVisibility (int contextWindow)
update visibility of this item
bool IsVisible () const
whether this item is visible or not
void SetVisibleCondition (const std::string &condition, int context)
set a visible condition for this item.
const CGUIAction & GetClickActions () const
Public Member Functions inherited from CFileItem
CFileItem (void)
CFileItem (const CFileItem &item)
CFileItem (const CGUIListItem &item)
CFileItem (const std::string &strLabel)
CFileItem (const char *strLabel)
CFileItem (const CURL &path, bool bIsFolder)
CFileItem (const std::string &strPath, bool bIsFolder)
CFileItem (const CSong &song)
CFileItem (const CSong &song, const MUSIC_INFO::CMusicInfoTag &music)
CFileItem (const CURL &path, const CAlbum &album)
CFileItem (const std::string &path, const CAlbum &album)
CFileItem (const CArtist &artist)
CFileItem (const CGenre &genre)
CFileItem (const MUSIC_INFO::CMusicInfoTag &music)
CFileItem (const CVideoInfoTag &movie)
CFileItem (const std::shared_ptr< PVR::CPVREpgInfoTag > &tag)
CFileItem (const std::shared_ptr< PVR::CPVREpgSearchFilter > &filter)
CFileItem (const std::shared_ptr< PVR::CPVRChannelGroupMember > &channelGroupMember)
CFileItem (const std::shared_ptr< PVR::CPVRRecording > &record)
CFileItem (const std::shared_ptr< PVR::CPVRTimerInfoTag > &timer)
CFileItem (const std::string &path, const std::shared_ptr< PVR::CPVRProvider > &provider)
CFileItem (const CMediaSource &share)
CFileItem (std::shared_ptr< const ADDON::IAddon > addonInfo)
CFileItem (const EventPtr &eventLogEntry)
~CFileItem (void) override
const CURL GetURL () const
void SetURL (const CURL &url)
bool IsURL (const CURL &url) const
const std::string & GetPath () const
void SetPath (const std::string &path)
bool IsPath (const std::string &path, bool ignoreURLOptions=false) const
const CURL GetDynURL () const
void SetDynURL (const CURL &url)
const std::string & GetDynPath () const
void SetDynPath (const std::string &path)
std::string GetBlurayPath () const
void Reset ()
reset class to it's default values as per construction. Free's all allocated memory.
CFileItem & operator= (const CFileItem &item)
void Archive (CArchive &ar) override
void Serialize (CVariant &value) const override
void ToSortable (SortItem &sortable, Field field) const override
void ToSortable (SortItem &sortable, const Fields &fields) const
bool IsFileItem () const override
bool Exists (bool bUseCache=true) const
bool IsPicture () const
Check whether an item is a picture item. Note that this returns true for anything with a picture info tag, so that may include eg. folders.
bool IsDeleted () const
Check whether an item is 'deleted' (for example, a trashed pvr recording).
bool IsGame () const
bool IsLibraryFolder () const
bool IsPythonScript () const
bool IsPlugin () const
bool IsScript () const
bool IsAddonsPath () const
bool IsSourcesPath () const
bool IsNFO () const
bool IsDiscImage () const
bool IsOpticalMediaFile () const
bool IsBluray () const
bool IsRAR () const
bool IsAPK () const
bool IsZIP () const
bool IsCBZ () const
bool IsCBR () const
bool IsISO9660 () const
bool IsDVD () const
bool IsOnDVD () const
bool IsHD () const
bool IsNfs () const
bool IsSmb () const
bool IsURL () const
bool IsStack () const
bool IsFavourite () const
bool IsMultiPath () const
bool IsEPG () const
bool IsPVRChannel () const
bool IsPVRChannelGroup () const
bool IsPVRRecording () const
bool IsUsablePVRRecording () const
bool IsDeletedPVRRecording () const
bool IsInProgressPVRRecording () const
bool IsPVRTimer () const
bool IsPVRProvider () const
bool IsType (const char *ext) const
bool IsVirtualDirectoryRoot () const
bool IsReadOnly () const
bool CanQueue () const
void SetCanQueue (bool bYesNo)
bool IsParentFolder () const
bool IsFileFolder (EFileFolderType types=EFILEFOLDER_MASK_ALL) const
bool IsRemovable () const
bool IsPVR () const
bool IsLiveTV () const
bool IsRSS () const
bool IsAndroidApp () const
bool HasVideoVersions () const
bool HasVideoExtras () const
void RemoveExtension ()
void CleanString ()
void SetFileSizeLabel ()
void SetLabel (const std::string &strLabel) override
VideoDbContentType GetVideoContentType () const
bool IsLabelPreformatted () const
void SetLabelPreformatted (bool bYesNo)
bool SortsOnTop () const
bool SortsOnBottom () const
void SetSpecialSort (SortSpecial sort)
bool HasMusicInfoTag () const
MUSIC_INFO::CMusicInfoTag * GetMusicInfoTag ()
const MUSIC_INFO::CMusicInfoTag * GetMusicInfoTag () const
bool HasVideoInfoTag () const
CVideoInfoTag * GetVideoInfoTag ()
const CVideoInfoTag * GetVideoInfoTag () const
bool HasEPGInfoTag () const
const std::shared_ptr< PVR::CPVREpgInfoTag > GetEPGInfoTag () const
bool HasEPGSearchFilter () const
const std::shared_ptr< PVR::CPVREpgSearchFilter > GetEPGSearchFilter () const
bool HasPVRChannelGroupMemberInfoTag () const
const std::shared_ptr< PVR::CPVRChannelGroupMember > GetPVRChannelGroupMemberInfoTag () const
bool HasPVRChannelInfoTag () const
const std::shared_ptr< PVR::CPVRChannel > GetPVRChannelInfoTag () const
bool HasPVRRecordingInfoTag () const
const std::shared_ptr< PVR::CPVRRecording > GetPVRRecordingInfoTag () const
bool HasPVRTimerInfoTag () const
const std::shared_ptr< PVR::CPVRTimerInfoTag > GetPVRTimerInfoTag () const
bool HasPVRProviderInfoTag () const
const std::shared_ptr< PVR::CPVRProvider > GetPVRProviderInfoTag () const
CFileItem GetItemToPlay () const
return the item to play. will be almost 'this', but can be different (e.g. "Play recording" from PVR EPG grid window)
bool IsResumePointSet () const
Test if this item has a valid resume point set.
double GetCurrentResumeTime () const
Return the current resume time.
bool GetCurrentResumeTimeAndPartNumber (int64_t &startOffset, int &partNumber) const
Return the current resume time and part.
bool IsResumable () const
Test if this item type can be resumed.
int64_t GetStartOffset () const
Get the offset where start the playback.
void SetStartOffset (const int64_t offset)
Set the offset where start the playback.
int64_t GetEndOffset () const
Get the end offset.
void SetEndOffset (const int64_t offset)
Set the end offset.
bool HasPictureInfoTag () const
const CPictureInfoTag * GetPictureInfoTag () const
bool HasAddonInfo () const
const std::shared_ptr< const ADDON::IAddon > GetAddonInfo () const
bool HasGameInfoTag () const
KODI::GAME::CGameInfoTag * GetGameInfoTag ()
const KODI::GAME::CGameInfoTag * GetGameInfoTag () const
CPictureInfoTag * GetPictureInfoTag ()
std::string FindLocalArt (const std::string &artFile, bool useFolder) const
Assemble the filename of a particular piece of local artwork for an item, and check for file existence.
bool SkipLocalArt () const
Whether or not to skip searching for local art.
std::string GetThumbHideIfUnwatched (const CFileItem *item) const
Get the thumb for the item, but hide it to prevent spoilers if the user has set 'Show information for unwatched items' appropriately.
std::string GetMovieName (bool bUseFolderNames=false) const
std::string GetBaseMoviePath (bool useFolderNames) const
Find the base movie path (i.e. the item the user expects us to use to lookup the movie) For folder items, with "use foldernames for lookups" it returns the folder. Regardless of settings, for VIDEO_TS/BDMV it returns the parent of the VIDEO_TS/BDMV folder (if present)
std::string GetUserMusicThumb (bool alwaysCheckRemote=false, bool fallbackToFolder=false) const
std::string GetLocalMetadataPath () const
Get the path where we expect local metadata to reside. For a folder, this is just the existing path (eg tvshow folder) For a file, this is the parent path, with exceptions made for VIDEO_TS and BDMV files.
bool LoadMusicTag ()
bool LoadGameTag ()
bool LoadDetails ()
Load detailed data for an item constructed with only a path and a folder flag Fills item's video info tag, sets item properties.
const std::string & GetMimeType () const
void SetMimeType (const std::string &mimetype)
void FillInMimeType (bool lookup=true)
Resolve the MIME type based on file extension or a web lookup If m_mimetype is already set (non-empty), this function has no effect. For http:// and shout:// streams, this will query the stream (blocking operation). Set lookup=false to skip any internet lookups and always return immediately.
bool ContentLookup ()
Some sources do not support HTTP HEAD request to determine i.e. mime type.
void SetMimeTypeForInternetFile ()
(Re)set the mime-type for internet files if allowed (m_doContentLookup) Some sources do not support HTTP HEAD request to determine i.e. mime type
void SetContentLookup (bool enable)
Lookup via HTTP HEAD request might not be needed, use this setter to disable ContentLookup.
void SetExtraInfo (const std::string &info)
const std::string & GetExtraInfo () const
void UpdateInfo (const CFileItem &item, bool replaceLabels=true)
Update an item with information from another item We take metadata information from the given item and supplement the current item with that info. If tags exist in the new item we use the entire tag information. Properties are appended, and labels, thumbnail and icon are updated if non-empty in the given item.
void MergeInfo (const CFileItem &item)
Merge an item with information from another item We take metadata/art information from the given item and supplement the current item with that info. If tags exist in the new item we only merge the missing tag information. Properties are appended, and labels are updated if non-empty in the given item.
bool IsSamePath (const CFileItem *item) const
bool IsAlbum () const
void SetFromVideoInfoTag (const CVideoInfoTag &video)
Sets details using the information from the CVideoInfoTag object Sets the videoinfotag and uses its information to set the label and path.
void SetFromMusicInfoTag (const MUSIC_INFO::CMusicInfoTag &music)
Sets details using the information from the CMusicInfoTag object Sets the musicinfotag and uses its information to set the label and path.
void SetFromAlbum (const CAlbum &album)
Sets details using the information from the CAlbum object Sets the album in the music info tag and uses its information to set the label and album-specific properties.
void SetFromSong (const CSong &song)
Sets details using the information from the CSong object Sets the song in the music info tag and uses its information to set the label, path, song-specific properties and artwork.
void SetCueDocument (const CCueDocumentPtr &cuePtr)
void LoadEmbeddedCue ()
bool HasCueDocument () const
bool LoadTracksFromCueDocument (CFileItemList &scannedItems)
Public Member Functions inherited from CGUIListItem
CGUIListItem (void)
CGUIListItem (const CGUIListItem &item)
CGUIListItem (const std::string &strLabel)
virtual ~CGUIListItem (void)
CGUIListItem & operator= (const CGUIListItem &item)
const std::string & GetLabel () const
void SetLabel2 (const std::string &strLabel)
const std::string & GetLabel2 () const
void SetOverlayImage (GUIIconOverlay icon)
std::string GetOverlayImage () const
void SetArt (const std::string &type, const std::string &url)
Set a particular art type for an item.
void SetArt (const ArtMap &art)
set artwork for an item
void AppendArt (const ArtMap &art, const std::string &prefix="")
append artwork to an item
void SetArtFallback (const std::string &from, const std::string &to)
set a fallback image for art
void ClearArt ()
clear art on an item
std::string GetArt (const std::string &type) const
Get a particular art type for an item.
const ArtMap & GetArt () const
get artwork for an item Retrieves artwork in a type:url map
bool HasArt (const std::string &type) const
Check whether an item has a particular piece of art Equivalent to !GetArt(type).empty()
void SetSortLabel (const std::string &label)
void SetSortLabel (const std::wstring &label)
const std::wstring & GetSortLabel () const
void Select (bool bOnOff)
bool IsSelected () const
bool HasOverlay () const
void SetLayout (std::unique_ptr< CGUIListItemLayout > layout)
CGUIListItemLayout * GetLayout ()
void SetFocusedLayout (std::unique_ptr< CGUIListItemLayout > layout)
CGUIListItemLayout * GetFocusedLayout ()
void FreeIcons ()
void FreeMemory (bool immediately=false)
void SetInvalid ()
void SetProperty (const std::string &strKey, const CVariant &value)
void IncrementProperty (const std::string &strKey, int nVal)
void IncrementProperty (const std::string &strKey, int64_t nVal)
void IncrementProperty (const std::string &strKey, double dVal)
void ClearProperties ()
void AppendProperties (const CGUIListItem &item)
Append the properties of one CGUIListItem to another. Any existing properties in the current item will be overridden if they are set in the passed in item.
void Archive (CArchive &ar)
void Serialize (CVariant &value)
bool HasProperty (const std::string &strKey) const
bool HasProperties () const
void ClearProperty (const std::string &strKey)
const CVariant & GetProperty (const std::string &strKey) const
void SetCurrentItem (unsigned int position)
Set the current item number within it's container Our container classes will set this member with the items position in the container starting at 1.
unsigned int GetCurrentItem () const
Get the current item number within it's container Retrieve the items position in a container, this is useful to show for example numbering in front of entities in an arbitrary list of entities, like songs of a playlist.
Private Types
typedef std::vector< std::pair< KODI::GUILIB::GUIINFO::CGUIInfoLabel, std::string > > InfoVector
Private Attributes
InfoVector m_info
INFO::InfoPtr m_visCondition
bool m_visState
CGUIAction m_clickActions
Additional Inherited Members
Public Types inherited from CGUIListItem
enum GUIIconOverlay {
ICON_OVERLAY_NONE = 0 , ICON_OVERLAY_RAR , ICON_OVERLAY_ZIP , ICON_OVERLAY_LOCKED ,
ICON_OVERLAY_UNWATCHED , ICON_OVERLAY_WATCHED , ICON_OVERLAY_HD
}
typedef std::map< std::string, std::string > ArtMap
Public Attributes inherited from CFileItem
bool m_bIsShareOrDrive
is this a root share/drive
int m_iDriveType
If m_bIsShareOrDrive is true, use to get the share type. Types see: CMediaSource::m_iDriveType.
CDateTime m_dateTime
file creation date & time
int64_t m_dwSize
file size (0 for folders)
std::string m_strDVDLabel
std::string m_strTitle
int m_iprogramCount
int m_idepth
int m_lStartPartNumber
LockType m_iLockMode
std::string m_strLockCode
int m_iHasLock
int m_iBadPwdCount
Public Attributes inherited from CGUIListItem
bool m_bIsFolder
is item a folder or a file
Protected Types inherited from CGUIListItem
typedef std::map< std::string, CVariant, icompare > PropertyMap
Protected Member Functions inherited from IArchivable
virtual ~IArchivable ()=default
Protected Member Functions inherited from ISerializable
~ISerializable ()=default
Protected Member Functions inherited from ISortable
~ISortable ()=default
Protected Attributes inherited from CGUIListItem
std::string m_strLabel2
GUIIconOverlay m_overlayIcon
std::unique_ptr< CGUIListItemLayout > m_layout
std::unique_ptr< CGUIListItemLayout > m_focusedLayout
bool m_bSelected
unsigned int m_currentItem
PropertyMap m_mapProperties
Detailed Description
wrapper class for a static item in a list container
,
A wrapper class for the items in a container specified via the <content> flag. Handles constructing items from XML and updating item labels, icons and properties.
See also
CFileItem, CGUIBaseContainer
Member Typedef Documentation
InfoVector
typedef std::vector< std::pair<KODI::GUILIB::GUIINFO::CGUIInfoLabel, std::string> > CGUIStaticItem::InfoVector private
Constructor & Destructor Documentation
CGUIStaticItem() [1/3]
CGUIStaticItem::CGUIStaticItem (const TiXmlElement * element, int contextWindow)
constructor Construct an item based on an XML description: <label>$INFO[MusicPlayer.Artist]</label> <label2>$INFO[MusicPlayer.Album]</label2> <thumb>bar.png</thumb> <icon>foo.jpg</icon> <onclick>ActivateWindow(Home)</onclick>
Parameters
element XML element to construct from
contextWindow window context to use for any info labels
References CGUIControlFactory::GetActions(), XMLUtils::GetAttribute(), CGUIControlFactory::GetConditionalVisibility(), CGUIControlFactory::GetInfoLabel(), CGUIControlFactory::GetInfoLabelFromElement(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::GetLabel(), KODI::GUILIB::GUIINFO::CGUIInfoLabel::IsConstant(), label, m_clickActions, m_info, CFileItem::m_iprogramCount, m_visState, name, CGUIListItem::SetArt(), CFileItem::SetLabel(), CGUIListItem::SetLabel2(), CGUIListItem::SetProperty(), and SetVisibleCondition().
CGUIStaticItem() [2/3]
CGUIStaticItem::CGUIStaticItem (const CFileItem & item) explicit
References m_visState.
CGUIStaticItem() [3/3]
CGUIStaticItem::CGUIStaticItem (const CGUIStaticItem & other) explicit
~CGUIStaticItem()
CGUIStaticItem::~CGUIStaticItem () override default
Member Function Documentation
Clone()
CGUIListItem * CGUIStaticItem::Clone () const inline override virtual
Reimplemented from CFileItem.
GetClickActions()
const CGUIAction & CGUIStaticItem::GetClickActions () const inline
References m_clickActions.
Referenced by CStaticListProvider::OnClick().
IsVisible()
bool CGUIStaticItem::IsVisible () const
whether this item is visible or not
References m_visCondition, and m_visState.
SetVisibleCondition()
void CGUIStaticItem::SetVisibleCondition (const std::string & condition, int context)
set a visible condition for this item.
Parameters
condition the condition to use.
context the context for the condition (typically a window id).
References CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), m_visCondition, m_visState, and CGUIInfoManager::Register().
Referenced by CGUIStaticItem().
UpdateProperties()
void CGUIStaticItem::UpdateProperties (int contextWindow)
update any infolabels in the items properties Runs through all the items properties, updating any that should be periodically recomputed
Parameters
contextWindow window context to use for any info labels
References m_info, name, CGUIListItem::SetArt(), CFileItem::SetLabel(), CGUIListItem::SetLabel2(), CGUIListItem::SetProperty(), and value.
UpdateVisibility()
bool CGUIStaticItem::UpdateVisibility (int contextWindow)
update visibility of this item
Parameters
contextWindow window context to use for any info labels
Returns
true if visible state has changed, false otherwise
References m_visCondition, and m_visState.
Member Data Documentation
m_clickActions
CGUIAction CGUIStaticItem::m_clickActions private
Referenced by CGUIStaticItem(), and GetClickActions().
m_info
InfoVector CGUIStaticItem::m_info private
Referenced by CGUIStaticItem(), and UpdateProperties().
m_visCondition
INFO::InfoPtr CGUIStaticItem::m_visCondition private
Referenced by IsVisible(), SetVisibleCondition(), and UpdateVisibility().
m_visState
bool CGUIStaticItem::m_visState private
Referenced by CGUIStaticItem(), CGUIStaticItem(), IsVisible(), SetVisibleCondition(), and UpdateVisibility().
The documentation for this class was generated from the following files:
GUIStaticItem.h
GUIStaticItem.cpp