Kodi Documentation: CPicture Class Reference
CPicture Class Reference
#include <Picture.h>
Static Public Member Functions
static bool GetThumbnailFromSurface (const unsigned char *buffer, int width, int height, int stride, const std::string &thumbFile, uint8_t *&result, size_t &result_size)
static bool CreateThumbnailFromSurface (const unsigned char *buffer, int width, int height, int stride, const std::string &thumbFile)
static std::unique_ptr< CTexture > CreateTiledThumb (const std::vector< std::string > &files)
static bool ResizeTexture (const std::string &image, CTexture *texture, uint32_t &dest_width, uint32_t &dest_height, uint8_t *&result, size_t &result_size, CPictureScalingAlgorithm::Algorithm scalingAlgorithm=CPictureScalingAlgorithm::NoAlgorithm)
static bool ResizeTexture (const std::string &image, uint8_t *pixels, uint32_t width, uint32_t height, uint32_t pitch, uint32_t &dest_width, uint32_t &dest_height, uint8_t *&result, size_t &result_size, CPictureScalingAlgorithm::Algorithm scalingAlgorithm=CPictureScalingAlgorithm::NoAlgorithm)
static bool CacheTexture (CTexture *texture, uint32_t &dest_width, uint32_t &dest_height, const std::string &dest, CPictureScalingAlgorithm::Algorithm scalingAlgorithm=CPictureScalingAlgorithm::NoAlgorithm)
Cache a texture, resizing, rotating and flipping as needed, and saving as a JPG or PNG.
static bool CacheTexture (uint8_t *pixels, uint32_t width, uint32_t height, uint32_t pitch, int orientation, uint32_t &dest_width, uint32_t &dest_height, const std::string &dest, CPictureScalingAlgorithm::Algorithm scalingAlgorithm=CPictureScalingAlgorithm::NoAlgorithm)
static void GetScale (unsigned int width, unsigned int height, unsigned int &out_width, unsigned int &out_height)
static bool ScaleImage (uint8_t *in_pixels, unsigned int in_width, unsigned int in_height, unsigned int in_pitch, AVPixelFormat in_format, uint8_t *out_pixels, unsigned int out_width, unsigned int out_height, unsigned int out_pitch, AVPixelFormat out_format, CPictureScalingAlgorithm::Algorithm scalingAlgorithm=CPictureScalingAlgorithm::NoAlgorithm)
Static Private Member Functions
static bool OrientateImage (std::unique_ptr< uint32_t[]> &pixels, unsigned int &width, unsigned int &height, int orientation, unsigned int &stridePixels)
static bool FlipHorizontal (std::unique_ptr< uint32_t[]> &pixels, const unsigned int &width, const unsigned int &height, const unsigned int &stridePixels)
static bool FlipVertical (std::unique_ptr< uint32_t[]> &pixels, const unsigned int &width, const unsigned int &height, const unsigned int &stridePixels)
static bool Rotate90CCW (std::unique_ptr< uint32_t[]> &pixels, unsigned int &width, unsigned int &height, unsigned int &stridePixels)
static bool Rotate270CCW (std::unique_ptr< uint32_t[]> &pixels, unsigned int &width, unsigned int &height, unsigned int &stridePixels)
static bool Rotate180CCW (std::unique_ptr< uint32_t[]> &pixels, const unsigned int &width, const unsigned int &height, const unsigned int &stridePixels)
static bool Transpose (std::unique_ptr< uint32_t[]> &pixels, unsigned int &width, unsigned int &height, unsigned int &width_aligned)
static bool TransposeOffAxis (std::unique_ptr< uint32_t[]> &pixels, unsigned int &width, unsigned int &height, unsigned int &stridePixels)
Member Function Documentation
CacheTexture() [1/2]
bool CPicture::CacheTexture (CTexture * texture, uint32_t & dest_width, uint32_t & dest_height, const std::string & dest, CPictureScalingAlgorithm::Algorithm scalingAlgorithm = CPictureScalingAlgorithm::NoAlgorithm) static
Cache a texture, resizing, rotating and flipping as needed, and saving as a JPG or PNG.
Parameters
texture a pointer to a CTexture
dest_width [in/out] maximum width in pixels of cached version - replaced with actual cached width
dest_height [in/out] maximum height in pixels of cached version - replaced with actual cached height
dest the output cache file
Returns
true if successful, false otherwise
References CacheTexture(), CTextureBase::GetHeight(), CTextureBase::GetOrientation(), CTextureBase::GetPitch(), CTextureBase::GetPixels(), and CTextureBase::GetWidth().
Referenced by CacheTexture(), and CTextureCacheJob::CacheTexture().
CacheTexture() [2/2]
bool CPicture::CacheTexture (uint8_t * pixels, uint32_t width, uint32_t height, uint32_t pitch, int orientation, uint32_t & dest_width, uint32_t & dest_height, const std::string & dest, CPictureScalingAlgorithm::Algorithm scalingAlgorithm = CPictureScalingAlgorithm::NoAlgorithm) static
References CreateThumbnailFromSurface(), GetScale(), CServiceBroker::GetSettingsComponent(), CPictureScalingAlgorithm::NoAlgorithm, OrientateImage(), ScaleImage(), and success.
CreateThumbnailFromSurface()
bool CPicture::CreateThumbnailFromSurface (const unsigned char * buffer, int width, int height, int stride, const std::string & thumbFile) static
References ImageFactory::CreateLoader(), IImage::CreateThumbnailFromSurface(), CLog::Log(), LOGDEBUG, LOGERROR, XFILE::CFile::OpenForWrite(), IImage::ReleaseThumbnailBuffer(), and XB_FMT_A8R8G8B8.
Referenced by CGUIDialogVideoBookmarks::AddBookmark(), CacheTexture(), CThumbnailWriter::DoWork(), KODI::RETRO::CRPRenderManager::SaveThumbnail(), and CScreenShot::TakeScreenshot().
CreateTiledThumb()
std::unique_ptr< CTexture > CPicture::CreateTiledThumb (const std::vector< std::string > & files) static
References CTexture::CreateTexture(), GetScale(), CServiceBroker::GetSettingsComponent(), CTexture::LoadFromFile(), OrientateImage(), ScaleImage(), success, and XB_FMT_A8R8G8B8.
Referenced by CPictureFolderImageFileLoader::Load(), and PVR::CPVRChannelGroupImageFileLoader::Load().
FlipHorizontal()
bool CPicture::FlipHorizontal (std::unique_ptr< uint32_t[]> & pixels, const unsigned int & width, const unsigned int & height, const unsigned int & stridePixels) static private
Referenced by OrientateImage().
FlipVertical()
bool CPicture::FlipVertical (std::unique_ptr< uint32_t[]> & pixels, const unsigned int & width, const unsigned int & height, const unsigned int & stridePixels) static private
Referenced by OrientateImage().
GetScale()
void CPicture::GetScale (unsigned int width, unsigned int height, unsigned int & out_width, unsigned int & out_height) static
Referenced by CacheTexture(), CreateTiledThumb(), ResizeTexture(), and KODI::RETRO::CRPRenderManager::SaveThumbnail().
GetThumbnailFromSurface()
bool CPicture::GetThumbnailFromSurface (const unsigned char * buffer, int width, int height, int stride, const std::string & thumbFile, uint8_t *& result, size_t & result_size) static
References ImageFactory::CreateLoader(), IImage::CreateThumbnailFromSurface(), IImage::ReleaseThumbnailBuffer(), and XB_FMT_A8R8G8B8.
Referenced by ResizeTexture().
OrientateImage()
bool CPicture::OrientateImage (std::unique_ptr< uint32_t[]> & pixels, unsigned int & width, unsigned int & height, int orientation, unsigned int & stridePixels) static private
References FlipHorizontal(), FlipVertical(), CLog::Log(), LOGERROR, Rotate180CCW(), Rotate270CCW(), Rotate90CCW(), Transpose(), and TransposeOffAxis().
Referenced by CacheTexture(), and CreateTiledThumb().
ResizeTexture() [1/2]
bool CPicture::ResizeTexture (const std::string & image, CTexture * texture, uint32_t & dest_width, uint32_t & dest_height, uint8_t *& result, size_t & result_size, CPictureScalingAlgorithm::Algorithm scalingAlgorithm = CPictureScalingAlgorithm::NoAlgorithm) static
References CTextureBase::GetHeight(), CTextureBase::GetPitch(), CTextureBase::GetPixels(), CTextureBase::GetWidth(), and ResizeTexture().
Referenced by ResizeTexture(), and CTextureCacheJob::ResizeTexture().
ResizeTexture() [2/2]
bool CPicture::ResizeTexture (const std::string & image, uint8_t * pixels, uint32_t width, uint32_t height, uint32_t pitch, uint32_t & dest_width, uint32_t & dest_height, uint8_t *& result, size_t & result_size, CPictureScalingAlgorithm::Algorithm scalingAlgorithm = CPictureScalingAlgorithm::NoAlgorithm) static
References GetScale(), GetThumbnailFromSurface(), ScaleImage(), and success.
Rotate180CCW()
bool CPicture::Rotate180CCW (std::unique_ptr< uint32_t[]> & pixels, const unsigned int & width, const unsigned int & height, const unsigned int & stridePixels) static private
Referenced by OrientateImage().
Rotate270CCW()
bool CPicture::Rotate270CCW (std::unique_ptr< uint32_t[]> & pixels, unsigned int & width, unsigned int & height, unsigned int & stridePixels) static private
Referenced by OrientateImage().
Rotate90CCW()
bool CPicture::Rotate90CCW (std::unique_ptr< uint32_t[]> & pixels, unsigned int & width, unsigned int & height, unsigned int & stridePixels) static private
Referenced by OrientateImage().
ScaleImage()
bool CPicture::ScaleImage (uint8_t * in_pixels, unsigned int in_width, unsigned int in_height, unsigned int in_pitch, AVPixelFormat in_format, uint8_t * out_pixels, unsigned int out_width, unsigned int out_height, unsigned int out_pitch, AVPixelFormat out_format, CPictureScalingAlgorithm::Algorithm scalingAlgorithm = CPictureScalingAlgorithm::NoAlgorithm) static
References CPictureScalingAlgorithm::ToSwscale().
Referenced by CacheTexture(), CreateTiledThumb(), ResizeTexture(), and KODI::RETRO::CRPRenderManager::SaveThumbnail().
Transpose()
bool CPicture::Transpose (std::unique_ptr< uint32_t[]> & pixels, unsigned int & width, unsigned int & height, unsigned int & width_aligned) static private
Referenced by OrientateImage().
TransposeOffAxis()
bool CPicture::TransposeOffAxis (std::unique_ptr< uint32_t[]> & pixels, unsigned int & width, unsigned int & height, unsigned int & stridePixels) static private
Referenced by OrientateImage().
The documentation for this class was generated from the following files:
Picture.h
Picture.cpp