Kodi Documentation: CVideoThumbLoader Class Reference
CVideoThumbLoader Class Reference
#include <VideoThumbLoader.h>
Public Member Functions
CVideoThumbLoader ()
~CVideoThumbLoader () override
void OnLoaderStart () override
void OnLoaderFinish () override
bool LoadItem (CFileItem *pItem) override
bool LoadItemCached (CFileItem *pItem) override
bool LoadItemLookup (CFileItem *pItem) override
virtual bool FillThumb (CFileItem &item)
Fill the thumb of a video item First uses a cached thumb from a previous run, then checks for a local thumb and caches it for the next run.
bool FillLibraryArt (CFileItem &item) override
helper function to fill the art for a video library item
Public Member Functions inherited from CThumbLoader
CThumbLoader ()
~CThumbLoader () override
virtual std::string GetCachedImage (const CFileItem &item, const std::string &type)
Checks whether the given item has an image listed in the texture database.
virtual void SetCachedImage (const CFileItem &item, const std::string &type, const std::string &image)
Associate an image with the given item in the texture database.
Public Member Functions inherited from CBackgroundInfoLoader
CBackgroundInfoLoader ()
~CBackgroundInfoLoader () override
void Load (CFileItemList &items)
bool IsLoading ()
void Run () override
void SetObserver (IBackgroundLoaderObserver *pObserver)
void SetProgressCallback (IProgressCallback *pCallback)
void StopThread ()
void StopAsync ()
Public Member Functions inherited from IRunnable
virtual void Cancel ()
virtual ~IRunnable ()=default
Static Public Member Functions
static std::string GetLocalArt (const CFileItem &item, const std::string &type, bool checkFolder=false)
Find a particular art type for a given item, optionally checking at the folder level.
static std::vector< std::string > GetArtTypes (const std::string &type)
return the available art types for a given media type
static bool IsValidArtType (const std::string &potentialArtType)
static bool IsArtTypeInWhitelist (const std::string &artType, const std::vector< std::string > &whitelist, bool exact)
static std::string GetEmbeddedThumbURL (const CFileItem &item)
helper function to retrieve a thumb URL for embedded video thumbs
Protected Member Functions
void DetectAndAddMissingItemData (CFileItem &item)
Tries to detect missing data/info from a file and adds those.
const ArtMap & GetArtFromCache (const std::string &mediaType, const int id)
Protected Attributes
CVideoDatabase * m_videoDatabase
ArtCache m_artCache
Protected Attributes inherited from CThumbLoader
CTextureDatabase * m_textureDatabase
Protected Attributes inherited from CBackgroundInfoLoader
CFileItemList * m_pVecItems {nullptr}
std::vector< CFileItemPtr > m_vecItems
CCriticalSection m_lock
volatile bool m_bIsLoading {false}
volatile bool m_bStop {true}
CThread * m_thread {nullptr}
IBackgroundLoaderObserver * m_pObserver {nullptr}
IProgressCallback * m_pProgressCallback {nullptr}
Constructor & Destructor Documentation
CVideoThumbLoader()
CVideoThumbLoader::CVideoThumbLoader ()
References m_videoDatabase.
~CVideoThumbLoader()
CVideoThumbLoader::~CVideoThumbLoader () override
References m_videoDatabase, and CBackgroundInfoLoader::StopThread().
Member Function Documentation
DetectAndAddMissingItemData()
void CVideoThumbLoader::DetectAndAddMissingItemData (CFileItem & item) protected
Tries to detect missing data/info from a file and adds those.
Parameters
item The CFileItem to process
Returns
void
Todo:
in case of too many false positives due to using the full path, extract the filename only using string utils
References CDatabase::Close(), CStereoscopicsManager::ConvertGuiStereoModeToString(), CStereoscopicsManager::DetectStereoModeByString(), CStreamDetails::GetAudioChannels(), CStreamDetails::GetAudioCodec(), CStreamDetails::GetAudioLanguage(), CStreamDetails::GetAudioStreamCount(), CServiceBroker::GetGUI(), CFileItem::GetPath(), CVideoInfoTag::GetPath(), CStreamDetails::GetStereoMode(), CGUIComponent::GetStereoscopicsManager(), CStreamDetails::GetSubtitleLanguage(), CStreamDetails::GetSubtitleStreamCount(), CFileItem::GetVideoInfoTag(), CVideoDatabase::GetVideoSettings(), CFileItem::HasVideoInfoTag(), index(), CGUIListItem::m_bIsFolder, CVideoSettings::m_StereoMode, CVideoInfoTag::m_streamDetails, m_videoDatabase, CStereoscopicsManager::NormalizeStereoMode(), CVideoDatabase::Open(), RENDER_STEREO_MODE_OFF, CGUIListItem::SetProperty(), and VIDEODB_PATH_VERSION_ID_ALL.
Referenced by LoadItemLookup().
FillLibraryArt()
bool CVideoThumbLoader::FillLibraryArt (CFileItem & item) override virtual
helper function to fill the art for a video library item
Parameters
item a video CFileItem
Returns
true if we fill art, false otherwise
Todo:
Is m_artist set other than musicvideo? Remove this fallback if not.
Reimplemented from CThumbLoader.
References CGUIListItem::AppendArt(), CVariant::asBoolean(), CDatabase::Close(), MUSIC_INFO::CMusicInfoTag::GetAlbumId(), CGUIListItem::GetArt(), CVideoDatabase::GetArtForAsset(), CVideoDatabase::GetArtForItem(), CMusicDatabase::GetArtForItem(), GetArtFromCache(), CMusicDatabase::GetArtist(), CMusicDatabase::GetArtistByName(), CVideoInfoTag::GetAssetInfo(), CGUIListItem::GetLabel(), CMusicDatabase::GetMatchingMusicVideoAlbum(), CFileItem::GetMusicInfoTag(), CGUIListItem::GetProperty(), CServiceBroker::GetSettingsComponent(), CVideoInfoTag::CAssetInfo::GetType(), CFileItem::GetVideoInfoTag(), CGUIListItem::HasArt(), CFileItem::HasMusicInfoTag(), m_videoDatabase, MediaTypeAlbum, MediaTypeArtist, MediaTypeEpisode, MediaTypeMovie, MediaTypeSeason, MediaTypeTvShow, MediaTypeVideoCollection, NONE, CMusicDatabase::Open(), CVideoDatabase::Open(), PARENT, CGUIListItem::SetArt(), CGUIListItem::SetArtFallback(), CGUIListItem::SetProperty(), CArtist::strBiography, and VERSION.
Referenced by LoadItemCached(), and UPNP::CUPnPServer::OnUpdateObject().
FillThumb()
bool CVideoThumbLoader::FillThumb (CFileItem & item) virtual
Fill the thumb of a video item First uses a cached thumb from a previous run, then checks for a local thumb and caches it for the next run.
Parameters
item the CFileItem object to fill
Returns
true if we fill the thumb, false otherwise
References CThumbLoader::GetCachedImage(), GetLocalArt(), CFileItem::GetPath(), CFileItem::GetVideoInfoTag(), CGUIListItem::HasArt(), CFileItem::HasVideoInfoTag(), CVideoInfoTag::m_coverArt, CGUIListItem::SetArt(), CThumbLoader::SetCachedImage(), and IMAGE_FILES::URLFromFile().
Referenced by KODI::GUILIB::GUIINFO::CVideoGUIInfo::InitCurrentItem().
GetArtFromCache()
const ArtMap & CVideoThumbLoader::GetArtFromCache (const std::string & mediaType, const int id) protected
References CVideoDatabase::GetArtForItem(), m_artCache, and m_videoDatabase.
Referenced by FillLibraryArt().
GetArtTypes()
std::vector< std::string > CVideoThumbLoader::GetArtTypes (const std::string & type) static
return the available art types for a given media type
Parameters
type the type of media.
Returns
a vector of art types.
See also
GetLocalArt
References CServiceBroker::GetSettingsComponent(), CSettings::SETTING_VIDEOLIBRARY_ARTWORK_LEVEL, CSettings::VIDEOLIBRARY_ARTWORK_LEVEL_CUSTOM, and CSettings::VIDEOLIBRARY_ARTWORK_LEVEL_NONE.
Referenced by anonymous_namespace{GUIDialogVideoInfo.cpp}::AddHardCodedAndExtendedArtTypes(), KODI::VIDEO::CVideoInfoScanner::AddVideo(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), CVideoDatabase::GetUsedImages(), CVideoDatabase::ImportFromXML(), LoadItemCached(), LoadItemLookup(), and KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForEpisodes().
GetEmbeddedThumbURL()
std::string CVideoThumbLoader::GetEmbeddedThumbURL (const CFileItem & item) static
helper function to retrieve a thumb URL for embedded video thumbs
Parameters
item a video CFileItem.
Returns
a URL for the embedded thumb.
References XFILE::CStackDirectory::GetFirstStackedFile(), CFileItem::GetPath(), CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), URIUtils::IsStack(), CVideoInfoTag::m_strFileNameAndPath, and IMAGE_FILES::URLFromFile().
Referenced by KODI::VIDEO::CVideoInfoScanner::GetArtwork(), and LoadItemLookup().
GetLocalArt()
std::string CVideoThumbLoader::GetLocalArt (const CFileItem & item, const std::string & type, bool checkFolder = false) static
Find a particular art type for a given item, optionally checking at the folder level.
Parameters
item the CFileItem to search.
type the type of art to look for.
checkFolder whether to also check the folder level for files. Defaults to false.
Returns
the art file (if found), else empty.
References XFILE::CACHE_BUFFER_MODE_ALL, XFILE::DIR_FLAG_NO_FILE_DIRS, XFILE::DIR_FLAG_NO_FILE_INFO, XFILE::DIR_FLAG_READ_CACHE, CFileItem::FindLocalArt(), XFILE::CDirectory::GetDirectory(), CFileItem::GetPath(), CServiceBroker::GetSettingsComponent(), CFileItem::IsFileFolder(), CFileItem::IsOpticalMediaFile(), KODI::NETWORK::IsStreamedFilesystem(), CGUIListItem::m_bIsFolder, CSettings::SETTING_FILECACHE_BUFFERMODE, and CFileItem::SkipLocalArt().
Referenced by FillThumb(), KODI::VIDEO::anonymous_namespace{VideoItemArtworkHandler.cpp}::CVideoItemArtworkHandler::GetLocalArt(), CVideoDatabase::ImportFromXML(), and LoadItemLookup().
IsArtTypeInWhitelist()
bool CVideoThumbLoader::IsArtTypeInWhitelist (const std::string & artType, const std::vector< std::string > & whitelist, bool exact) static
Referenced by KODI::VIDEO::CVideoInfoScanner::AddLocalItemArtwork(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), and KODI::VIDEO::CVideoInfoScanner::GetSeasonThumbs().
IsValidArtType()
bool CVideoThumbLoader::IsValidArtType (const std::string & potentialArtType) static
Referenced by KODI::VIDEO::CVideoInfoScanner::AddLocalItemArtwork().
LoadItem()
bool CVideoThumbLoader::LoadItem (CFileItem * pItem) override virtual
Look for a thumbnail for pItem. If one does not exist, look for an autogenerated thumbnail. If that does not exist, attempt to autogenerate one. Finally, check for the existence of fanart and set properties accordingly.
Returns
: true if pItem has been modified
Reimplemented from CBackgroundInfoLoader.
References LoadItemCached(), and LoadItemLookup().
Referenced by KODI::GUILIB::GUIINFO::CVideoGUIInfo::GetPlaylistInfo(), KODI::GUILIB::GUIINFO::CVideoGUIInfo::InitCurrentItem(), CPictureThumbLoader::LoadItemCached(), CGUIDialogVideoInfo::OnSearch(), CGUIDialogVideoManager::Refresh(), CGUIDialogVideoInfo::SetMovie(), CTVOSTopShelf::SetTopShelfItems(), and CRecentlyAddedJob::UpdateVideo().
LoadItemCached()
bool CVideoThumbLoader::LoadItemCached (CFileItem * pItem) override virtual
Reimplemented from CBackgroundInfoLoader.
References CGUIListItem::AppendArt(), CVariant::asBoolean(), CDatabase::Close(), FillLibraryArt(), CGUIListItem::GetArt(), GetArtTypes(), CThumbLoader::GetCachedImage(), CGUIListItem::GetProperty(), CVideoDatabase::GetStreamDetails(), CFileItem::GetVideoInfoTag(), CVideoInfoTag::HasStreamDetails(), CFileItem::HasVideoInfoTag(), CFileItem::IsParentFolder(), CGUIListItem::m_bIsFolder, CFileItem::m_bIsShareOrDrive, CVideoInfoTag::m_iFileId, CVideoInfoTag::m_type, m_videoDatabase, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeTvShow, MediaTypeVideoVersion, CVideoDatabase::Open(), and CGUIListItem::SetInvalid().
Referenced by LoadItem(), and CMusicThumbLoader::LoadItemCached().
LoadItemLookup()
bool CVideoThumbLoader::LoadItemLookup (CFileItem * pItem) override virtual
Reimplemented from CBackgroundInfoLoader.
References CGUIListItem::AppendArt(), CVariant::asBoolean(), CDatabase::BeginTransaction(), CDVDFileInfo::CanExtract(), CDatabase::Close(), CVideoDatabase::CommitTransaction(), DetectAndAddMissingItemData(), CGUIListItem::GetArt(), GetArtTypes(), GetEmbeddedThumbURL(), CDVDFileInfo::GetFileStreamDetails(), GetLocalArt(), CFileItem::GetPath(), CGUIListItem::GetProperty(), CServiceBroker::GetSettingsComponent(), CServiceBroker::GetTextureCache(), CFileItem::GetVideoInfoTag(), CGUIListItem::HasArt(), CVideoInfoTag::HasStreamDetails(), CFileItem::HasVideoInfoTag(), CFileItem::IsParentFolder(), LOGDEBUG, CGUIListItem::m_bIsFolder, CFileItem::m_bIsShareOrDrive, CVideoInfoTag::m_coverArt, CVideoInfoTag::m_iDbId, CVideoInfoTag::m_type, m_videoDatabase, MediaTypeEpisode, MediaTypeMovie, MediaTypeMusicVideo, MediaTypeTvShow, MediaTypeVideoVersion, CVideoDatabase::Open(), CGUIListItem::SetArt(), CVideoDatabase::SetArtForItem(), CThumbLoader::SetCachedImage(), CVideoDatabase::SetDetailsForItem(), CVideoDatabase::SetStreamDetailsForFile(), CVideoDatabase::SetStreamDetailsForFileId(), CSettings::SETTING_MYVIDEOS_EXTRACTFLAGS, CSettings::SETTING_MYVIDEOS_EXTRACTTHUMB, CSettings::SETTING_VIDEOLIBRARY_ARTWORK_LEVEL, IMAGE_FILES::URLFromFile(), and CSettings::VIDEOLIBRARY_ARTWORK_LEVEL_NONE.
Referenced by LoadItem(), and CMusicThumbLoader::LoadItemLookup().
OnLoaderFinish()
void CVideoThumbLoader::OnLoaderFinish () override virtual
Reimplemented from CThumbLoader.
References CDatabase::Close(), m_artCache, m_videoDatabase, and CThumbLoader::OnLoaderFinish().
OnLoaderStart()
void CVideoThumbLoader::OnLoaderStart () override virtual
Reimplemented from CThumbLoader.
References m_artCache, m_videoDatabase, CThumbLoader::OnLoaderStart(), and CVideoDatabase::Open().
Referenced by CRecentlyAddedJob::UpdateVideo().
Member Data Documentation
m_artCache
ArtCache CVideoThumbLoader::m_artCache protected
Referenced by GetArtFromCache(), OnLoaderFinish(), and OnLoaderStart().
m_videoDatabase
CVideoDatabase* CVideoThumbLoader::m_videoDatabase protected
Referenced by CVideoThumbLoader(), DetectAndAddMissingItemData(), FillLibraryArt(), GetArtFromCache(), LoadItemCached(), LoadItemLookup(), OnLoaderFinish(), OnLoaderStart(), and ~CVideoThumbLoader().
The documentation for this class was generated from the following files:
VideoThumbLoader.h
VideoThumbLoader.cpp