Kodi Documentation: CDVDVideoCodecAndroidMediaCodec Class Reference
CDVDVideoCodecAndroidMediaCodec Class Reference
#include <DVDVideoCodecAndroidMediaCodec.h>
Public Member Functions
CDVDVideoCodecAndroidMediaCodec (CProcessInfo &processInfo, bool surface_render=false)
~CDVDVideoCodecAndroidMediaCodec () override
bool Open (CDVDStreamInfo &hints, CDVDCodecOptions &options) override
bool AddData (const DemuxPacket &packet) override
void Reset () override
bool Reconfigure (CDVDStreamInfo &hints) override
VCReturn GetPicture (VideoPicture *pVideoPicture) override
const char * GetName () override
void SetCodecControl (int flags) override
unsigned GetAllowedReferences () override
void surfaceChanged (CJNISurfaceHolder holder, int format, int width, int height) override
void surfaceCreated (CJNISurfaceHolder holder) override
void surfaceDestroyed (CJNISurfaceHolder holder) override
Public Member Functions inherited from CDVDVideoCodec
CDVDVideoCodec (CProcessInfo &processInfo)
virtual ~CDVDVideoCodec ()=default
virtual void SetSpeed (int iSpeed)
virtual unsigned GetConvergeCount ()
virtual bool GetCodecStats (double &pts, int &droppedFrames, int &skippedPics)
virtual void Reopen ()
Static Public Member Functions
static std::unique_ptr< CDVDVideoCodec > Create (CProcessInfo &processInfo)
static bool Register ()
Protected Member Functions
void Dispose ()
void FlushInternal (void)
void SignalEndOfStream ()
void InjectExtraData (CJNIMediaFormat &mediaformat)
std::vector< uint8_t > GetHDRStaticMetadata ()
bool ConfigureMediaCodec (void)
int GetOutputPicture (void)
void ConfigureOutputFormat (CJNIMediaFormat &mediaformat)
void UpdateFpsDuration ()
void InitSurfaceTexture (void)
void ReleaseSurfaceTexture (void)
Static Protected Member Functions
static void CallbackInitSurfaceTexture (void *)
Protected Attributes
CDVDStreamInfo m_hints
std::string m_mime
std::string m_codecname
std::string m_formatname
bool m_opened = false
bool m_needSecureDecoder = false
int m_codecControlFlags
int m_state
std::shared_ptr< jni::CJNIXBMCVideoView > m_jnivideoview
CJNISurface m_jnivideosurface
unsigned int m_textureId = 0
std::shared_ptr< CJNIMediaCodec > m_codec
CJNIMediaCrypto * m_crypto = nullptr
std::shared_ptr< CJNISurfaceTexture > m_surfaceTexture
std::shared_ptr< CDVDMediaCodecOnFrameAvailable > m_frameAvailable
amc_demux m_demux_pkt
std::shared_ptr< CMediaCodecVideoBufferPool > m_videoBufferPool
uint32_t m_OutputDuration = 0
uint32_t m_fpsDuration = 0
int64_t m_lastPTS = -1
int64_t m_invalidPTSValue = 0
double m_dtsShift = DVD_NOPTS_VALUE
std::unique_ptr< CBitstreamConverter > m_bitstream
VideoPicture m_videobuffer
int m_indexInputBuffer
bool m_render_surface
mpeg2_sequence * m_mpeg2_sequence = nullptr
int m_src_offset [4]
int m_src_stride [4]
bool m_useDTSforPTS = false
Protected Attributes inherited from CDVDVideoCodec
CProcessInfo & m_processInfo
Static Protected Attributes
static std::atomic< bool > m_InstanceGuard
Additional Inherited Members
Public Types inherited from CDVDVideoCodec
enum VCReturn {
VC_NONE = 0 , VC_ERROR , VC_FATAL , VC_BUFFER ,
VC_PICTURE , VC_FLUSHED , VC_NOBUFFER , VC_REOPEN ,
VC_EOF
}
Constructor & Destructor Documentation
CDVDVideoCodecAndroidMediaCodec()
CDVDVideoCodecAndroidMediaCodec::CDVDVideoCodecAndroidMediaCodec (CProcessInfo & processInfo, bool surface_render = false)
References m_videobuffer, and VideoPicture::Reset().
~CDVDVideoCodecAndroidMediaCodec()
CDVDVideoCodecAndroidMediaCodec::~CDVDVideoCodecAndroidMediaCodec () override
References Dispose(), m_crypto, and m_mpeg2_sequence.
Member Function Documentation
AddData()
bool CDVDVideoCodecAndroidMediaCodec::AddData (const DemuxPacket & packet) override virtual
add data, decoder has to consume the entire packet returns true if the packet was consumed or if resubmitting it is useless
Implements CDVDVideoCodec.
References CDVDStreamInfo::aspect, DEMUX_CRYPTO_INFO::cipherBytes, DEMUX_CRYPTO_INFO::clearBytes, CDVDStreamInfo::codec, DEMUX_CRYPTO_INFO::cryptBlocks, DEMUX_PACKET::cryptoInfo, DEMUX_PACKET::dts, DVD_NOPTS_VALUE, mpeg2_sequence::fps_rate, mpeg2_sequence::fps_scale, CDVDStreamInfo::fpsrate, CDVDStreamInfo::fpsscale, CServiceBroker::GetLogging(), CDVDStreamInfo::height, mpeg2_sequence::height, int64_t(), DEMUX_PACKET::iSize, DEMUX_CRYPTO_INFO::iv, DEMUX_CRYPTO_INFO::kid, CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, LOGVIDEO, m_bitstream, m_codec, m_crypto, m_dtsShift, m_hints, m_indexInputBuffer, m_invalidPTSValue, m_mpeg2_sequence, m_opened, CDVDVideoCodec::m_processInfo, m_state, m_useDTSforPTS, MEDIACODEC_STATE_ENDOFSTREAM, MEDIACODEC_STATE_ERROR, MEDIACODEC_STATE_FLUSHED, MEDIACODEC_STATE_RUNNING, MEDIACODEC_STATE_STOPPED, DEMUX_CRYPTO_INFO::mode, CBitstreamConverter::mpeg2_sequence_header(), DEMUX_CRYPTO_INFO::numSubSamples, DEMUX_PACKET::pData, DEMUX_PACKET::pts, CDVDStreamInfo::ptsinvalid, mpeg2_sequence::ratio, Reset(), CProcessInfo::SetVideoDAR(), DEMUX_CRYPTO_INFO::skipBlocks, UpdateFpsDuration(), CDVDStreamInfo::width, and mpeg2_sequence::width.
CallbackInitSurfaceTexture()
void CDVDVideoCodecAndroidMediaCodec::CallbackInitSurfaceTexture (void * userdata) static protected
References InitSurfaceTexture().
Referenced by InitSurfaceTexture().
ConfigureMediaCodec()
bool CDVDVideoCodecAndroidMediaCodec::ConfigureMediaCodec (void) protected
References CDVDStreamInfo::colorPrimaries, CDVDStreamInfo::colorRange, CDVDStreamInfo::colorTransferCharacteristic, ConfigureOutputFormat(), Dispose(), GetHDRStaticMetadata(), CDVDStreamInfo::height, InitSurfaceTexture(), InjectExtraData(), CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, m_codec, m_crypto, m_formatname, m_hints, m_jnivideosurface, m_jnivideoview, m_mime, m_needSecureDecoder, m_render_surface, m_state, MEDIACODEC_STATE_CONFIGURED, MEDIACODEC_STATE_FLUSHED, CDVDStreamInfo::orientation, and CDVDStreamInfo::width.
Referenced by Open(), Reset(), and surfaceCreated().
ConfigureOutputFormat()
void CDVDVideoCodecAndroidMediaCodec::ConfigureOutputFormat (CJNIMediaFormat & mediaformat) protected
References CDVDStreamInfo::aspect, VideoPicture::color_primaries, VideoPicture::color_space, VideoPicture::color_transfer, CDVDStreamInfo::colorPrimaries, CDVDStreamInfo::colorSpace, CDVDStreamInfo::colorTransferCharacteristic, CDVDStreamInfo::forced_aspect, CServiceBroker::GetLogging(), VideoPicture::hdrType, CDVDStreamInfo::hdrType, VideoPicture::iDisplayHeight, VideoPicture::iDisplayWidth, VideoPicture::iHeight, VideoPicture::iWidth, CLog::Log(), LOGDEBUG, LOGVIDEO, m_hints, m_render_surface, and m_videobuffer.
Referenced by ConfigureMediaCodec(), and GetOutputPicture().
Create()
std::unique_ptr< CDVDVideoCodec > CDVDVideoCodecAndroidMediaCodec::Create (CProcessInfo & processInfo) static
Referenced by Register().
Dispose()
void CDVDVideoCodecAndroidMediaCodec::Dispose () protected
References FlushInternal(), VideoPicture::iFlags, CLog::Log(), LOGDEBUG, m_bitstream, m_codec, m_InstanceGuard, m_jnivideoview, m_opened, m_render_surface, m_state, m_videobuffer, m_videoBufferPool, MEDIACODEC_STATE_STOPPED, and ReleaseSurfaceTexture().
Referenced by ConfigureMediaCodec(), and ~CDVDVideoCodecAndroidMediaCodec().
FlushInternal()
void CDVDVideoCodecAndroidMediaCodec::FlushInternal (void) protected
References DVD_NOPTS_VALUE, m_dtsShift, m_lastPTS, m_OutputDuration, and SignalEndOfStream().
Referenced by Dispose().
GetAllowedReferences()
unsigned CDVDVideoCodecAndroidMediaCodec::GetAllowedReferences () override virtual
Number of references to old pictures that are allowed to be retained when calling decode on the next demux packet
Reimplemented from CDVDVideoCodec.
GetHDRStaticMetadata()
std::vector< uint8_t > CDVDVideoCodecAndroidMediaCodec::GetHDRStaticMetadata () protected
References CDVDStreamInfo::contentLightMetadata, data(), m_hints, and CDVDStreamInfo::masteringMetadata.
Referenced by ConfigureMediaCodec().
GetName()
const char * CDVDVideoCodecAndroidMediaCodec::GetName () inline override virtual
should return codecs name
Implements CDVDVideoCodec.
References m_formatname.
GetOutputPicture()
int CDVDVideoCodecAndroidMediaCodec::GetOutputPicture (void) protected
References ConfigureOutputFormat(), VideoPicture::dts, DVD_CODEC_CTRL_DROP, DVD_NOPTS_VALUE, index(), int64_t(), CLog::Log(), LOGDEBUG, LOGERROR, m_codec, m_codecControlFlags, m_dtsShift, m_frameAvailable, m_jnivideoview, m_lastPTS, m_OutputDuration, m_state, m_surfaceTexture, m_textureId, m_videobuffer, m_videoBufferPool, MEDIACODEC_STATE_WAIT_ENDOFSTREAM, VideoPicture::pts, CVideoBuffer::Release(), and VideoPicture::videoBuffer.
Referenced by GetPicture().
GetPicture()
CDVDVideoCodec::VCReturn CDVDVideoCodecAndroidMediaCodec::GetPicture (VideoPicture * pVideoPicture) override virtual
GetPicture controls decoding. Player calls it on every cycle it can signal a picture, request a buffer, or return none, if nothing applies the data is valid until the next GetPicture return VC_PICTURE
Implements CDVDVideoCodec.
References DVD_CODEC_CTRL_DRAIN, CMediaCodecVideoBuffer::GetBufferId(), GetOutputPicture(), CLog::Log(), LOGDEBUG, LOGERROR, LOGVIDEO, m_codec, m_codecControlFlags, m_fpsDuration, m_indexInputBuffer, m_opened, m_OutputDuration, m_state, m_videobuffer, MEDIACODEC_STATE_ENDOFSTREAM, MEDIACODEC_STATE_ERROR, MEDIACODEC_STATE_FLUSHED, MEDIACODEC_STATE_RUNNING, MEDIACODEC_STATE_WAIT_ENDOFSTREAM, VideoPicture::pts, VideoPicture::SetParams(), SignalEndOfStream(), CDVDVideoCodec::VC_BUFFER, CDVDVideoCodec::VC_EOF, CDVDVideoCodec::VC_NONE, CDVDVideoCodec::VC_PICTURE, and VideoPicture::videoBuffer.
InitSurfaceTexture()
void CDVDVideoCodecAndroidMediaCodec::InitSurfaceTexture (void) protected
References KODI::MESSAGING::ThreadMessageCallback::callback, CallbackInitSurfaceTexture(), CServiceBroker::GetAppMessenger(), m_frameAvailable, m_jnivideosurface, m_render_surface, m_surfaceTexture, m_textureId, TMSG_CALLBACK, and KODI::MESSAGING::ThreadMessageCallback::userptr.
Referenced by CallbackInitSurfaceTexture(), and ConfigureMediaCodec().
InjectExtraData()
void CDVDVideoCodecAndroidMediaCodec::InjectExtraData (CJNIMediaFormat & mediaformat) protected
References CDVDStreamInfo::extradata, FFmpegExtraData::GetData(), FFmpegExtraData::GetSize(), CLog::Log(), LOGDEBUG, m_bitstream, and m_hints.
Referenced by ConfigureMediaCodec(), and Reset().
Open()
bool CDVDVideoCodecAndroidMediaCodec::Open (CDVDStreamInfo & hints, CDVDCodecOptions & options) override virtual
Open the decoder, returns true on success Decoders not capable of running multiple instances should return false in case there is already a instance open
Implements CDVDVideoCodec.
References CDVDStreamInfo::aspect, CDVDStreamInfo::codec, CDVDStreamInfo::codec_tag, ConfigureMediaCodec(), jni::CJNIXBMCVideoView::createVideoView(), CRYPTO_SESSION_SYSTEM_CLEARKEY, CRYPTO_SESSION_SYSTEM_PLAYREADY, CRYPTO_SESSION_SYSTEM_WIDEVINE, CRYPTO_SESSION_SYSTEM_WISEPLAY, CDVDStreamInfo::cryptoSession, CDVDStreamInfo::dovi, DVD_NOPTS_VALUE, CDVDStreamInfo::extradata, CSettingUtils::FindIntInList(), DemuxCryptoSession::FLAG_SECURE_DECODER, mpeg2_sequence::fps_rate, mpeg2_sequence::fps_scale, CDVDStreamInfo::fpsrate, CDVDStreamInfo::fpsscale, FFmpegExtraData::GetData(), CServiceBroker::GetDecoderFilterManager(), CAndroidUtils::GetDolbyVisionCapabilities(), CServiceBroker::GetSettingsComponent(), FFmpegExtraData::GetSize(), HDR_TYPE_DOLBYVISION, CDVDStreamInfo::hdrType, CDVDStreamInfo::height, mpeg2_sequence::height, VideoPicture::iDisplayHeight, VideoPicture::iDisplayWidth, VideoPicture::iHeight, CDecoderFilterManager::isValid(), VideoPicture::iWidth, CDVDStreamInfo::level, CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_bitstream, m_codec, m_codecControlFlags, m_codecname, m_crypto, m_dtsShift, m_formatname, m_hints, m_indexInputBuffer, m_InstanceGuard, m_invalidPTSValue, m_jnivideoview, m_mime, m_mpeg2_sequence, m_needSecureDecoder, m_opened, CDVDVideoCodec::m_processInfo, m_render_surface, m_state, m_useDTSforPTS, m_videobuffer, m_videoBufferPool, MEDIACODEC_STATE_UNINITIALIZED, CDVDStreamInfo::profile, CDVDStreamInfo::ptsinvalid, mpeg2_sequence::ratio, VideoPicture::Reset(), CSettings::SETTING_VIDEOPLAYER_ALLOWEDHDRFORMATS, CSettings::SETTING_VIDEOPLAYER_CONVERTDOVI, CSettings::SETTING_VIDEOPLAYER_USEMEDIACODEC, CSettings::SETTING_VIDEOPLAYER_USEMEDIACODECSURFACE, CProcessInfo::SetVideoDAR(), CProcessInfo::SetVideoDecoderName(), CProcessInfo::SetVideoDeintMethod(), CProcessInfo::SetVideoDimensions(), CProcessInfo::SetVideoPixelFormat(), success, types, UpdateFpsDuration(), CSettings::VIDEOPLAYER_ALLOWED_HDR_TYPE_DOLBY_VISION, CSettings::VIDEOPLAYER_ALLOWED_HDR_TYPE_HDR10PLUS, CDVDStreamInfo::width, and mpeg2_sequence::width.
Reconfigure()
bool CDVDVideoCodecAndroidMediaCodec::Reconfigure (CDVDStreamInfo & hints) override virtual
Reconfigure the decoder, returns true on success Decoders not capable of running multiple instances may be capable of reconfiguring the running instance. If Reconfigure returns false, player will close / open the decoder
Reimplemented from CDVDVideoCodec.
References CDVDStreamInfo::COMPARE_ALL, CDVDStreamInfo::COMPARE_EXTRADATA, CDVDStreamInfo::COMPARE_ID, CDVDStreamInfo::Equal(), CLog::Log(), LOGDEBUG, and m_hints.
Register()
bool CDVDVideoCodecAndroidMediaCodec::Register () static
References Create(), and CDVDFactoryCodec::RegisterHWVideoCodec().
Referenced by CWinSystemAndroid::InitWindowSystem().
ReleaseSurfaceTexture()
void CDVDVideoCodecAndroidMediaCodec::ReleaseSurfaceTexture (void) protected
References m_frameAvailable, m_jnivideosurface, m_render_surface, m_surfaceTexture, and m_textureId.
Referenced by Dispose().
Reset()
void CDVDVideoCodecAndroidMediaCodec::Reset () override virtual
Reset the decoder. Should be the same as calling Dispose and Open after each other
Implements CDVDVideoCodec.
References ConfigureMediaCodec(), DVD_NOPTS_VALUE, InjectExtraData(), CLog::Log(), LOGDEBUG, LOGERROR, m_bitstream, m_codec, m_dtsShift, m_indexInputBuffer, m_opened, m_state, m_videobuffer, MEDIACODEC_STATE_ERROR, MEDIACODEC_STATE_FLUSHED, and VideoPicture::pts.
Referenced by AddData().
SetCodecControl()
void CDVDVideoCodecAndroidMediaCodec::SetCodecControl (int flags) override virtual
Codec can be informed by player with the following flags:
DVD_CODEC_CTRL_NO_POSTPROC : if speed is not normal the codec can switch off postprocessing and de-interlacing
DVD_CODEC_CTRL_HURRY : codecs may do postprocessing and de-interlacing. If video buffers in RenderManager are about to run dry, this is signaled to codec. Codec can wait for post-proc to be finished instead of returning empty and getting another packet.
DVD_CODEC_CTRL_DRAIN : instruct decoder to deliver last pictures without requesting new packets
DVD_CODEC_CTRL_DROP : this packet is going to be dropped. decoder is free to use it for decoding
Reimplemented from CDVDVideoCodec.
References CLog::Log(), LOGDEBUG, LOGVIDEO, and m_codecControlFlags.
SignalEndOfStream()
void CDVDVideoCodecAndroidMediaCodec::SignalEndOfStream () protected
References CLog::Log(), LOGDEBUG, LOGERROR, LOGWARNING, m_codec, m_indexInputBuffer, m_state, m_videoBufferPool, and MEDIACODEC_STATE_RUNNING.
Referenced by FlushInternal(), and GetPicture().
surfaceChanged()
void CDVDVideoCodecAndroidMediaCodec::surfaceChanged (CJNISurfaceHolder holder, int format, int width, int height) override
surfaceCreated()
void CDVDVideoCodecAndroidMediaCodec::surfaceCreated (CJNISurfaceHolder holder) override
References ConfigureMediaCodec(), m_state, and MEDIACODEC_STATE_STOPPED.
surfaceDestroyed()
void CDVDVideoCodecAndroidMediaCodec::surfaceDestroyed (CJNISurfaceHolder holder) override
References m_codec, m_jnivideosurface, m_state, MEDIACODEC_STATE_STOPPED, and MEDIACODEC_STATE_UNINITIALIZED.
UpdateFpsDuration()
void CDVDVideoCodecAndroidMediaCodec::UpdateFpsDuration () protected
References DVD_TIME_BASE, CDVDStreamInfo::fpsrate, CDVDStreamInfo::fpsscale, CLog::Log(), LOGDEBUG, m_fpsDuration, m_hints, CDVDVideoCodec::m_processInfo, and CProcessInfo::SetVideoFps().
Referenced by AddData(), and Open().
Member Data Documentation
m_bitstream
std::unique_ptr<CBitstreamConverter> CDVDVideoCodecAndroidMediaCodec::m_bitstream protected
Referenced by AddData(), Dispose(), InjectExtraData(), Open(), and Reset().
m_codec
std::shared_ptr<CJNIMediaCodec> CDVDVideoCodecAndroidMediaCodec::m_codec protected
Referenced by AddData(), ConfigureMediaCodec(), Dispose(), GetOutputPicture(), GetPicture(), Open(), Reset(), SignalEndOfStream(), and surfaceDestroyed().
m_codecControlFlags
int CDVDVideoCodecAndroidMediaCodec::m_codecControlFlags protected
Referenced by GetOutputPicture(), GetPicture(), Open(), and SetCodecControl().
m_codecname
std::string CDVDVideoCodecAndroidMediaCodec::m_codecname protected
Referenced by Open().
m_crypto
CJNIMediaCrypto* CDVDVideoCodecAndroidMediaCodec::m_crypto = nullptr protected
Referenced by AddData(), ConfigureMediaCodec(), Open(), and ~CDVDVideoCodecAndroidMediaCodec().
m_demux_pkt
amc_demux CDVDVideoCodecAndroidMediaCodec::m_demux_pkt protected
m_dtsShift
double CDVDVideoCodecAndroidMediaCodec::m_dtsShift = DVD_NOPTS_VALUE protected
Referenced by AddData(), FlushInternal(), GetOutputPicture(), Open(), and Reset().
m_formatname
std::string CDVDVideoCodecAndroidMediaCodec::m_formatname protected
Referenced by ConfigureMediaCodec(), GetName(), and Open().
m_fpsDuration
uint32_t CDVDVideoCodecAndroidMediaCodec::m_fpsDuration = 0 protected
Referenced by GetPicture(), and UpdateFpsDuration().
m_frameAvailable
std::shared_ptr<CDVDMediaCodecOnFrameAvailable> CDVDVideoCodecAndroidMediaCodec::m_frameAvailable protected
Referenced by GetOutputPicture(), InitSurfaceTexture(), and ReleaseSurfaceTexture().
m_hints
CDVDStreamInfo CDVDVideoCodecAndroidMediaCodec::m_hints protected
Referenced by AddData(), ConfigureMediaCodec(), ConfigureOutputFormat(), GetHDRStaticMetadata(), InjectExtraData(), Open(), Reconfigure(), and UpdateFpsDuration().
m_indexInputBuffer
int CDVDVideoCodecAndroidMediaCodec::m_indexInputBuffer protected
Referenced by AddData(), GetPicture(), Open(), Reset(), and SignalEndOfStream().
m_InstanceGuard
std::atomic< bool > CDVDVideoCodecAndroidMediaCodec::m_InstanceGuard static protected
Referenced by Dispose(), and Open().
m_invalidPTSValue
int64_t CDVDVideoCodecAndroidMediaCodec::m_invalidPTSValue = 0 protected
Referenced by AddData(), and Open().
m_jnivideosurface
CJNISurface CDVDVideoCodecAndroidMediaCodec::m_jnivideosurface protected
Referenced by ConfigureMediaCodec(), InitSurfaceTexture(), ReleaseSurfaceTexture(), and surfaceDestroyed().
m_jnivideoview
std::shared_ptr<jni::CJNIXBMCVideoView> CDVDVideoCodecAndroidMediaCodec::m_jnivideoview protected
Referenced by ConfigureMediaCodec(), Dispose(), GetOutputPicture(), and Open().
m_lastPTS
int64_t CDVDVideoCodecAndroidMediaCodec::m_lastPTS = -1 protected
Referenced by FlushInternal(), and GetOutputPicture().
m_mime
std::string CDVDVideoCodecAndroidMediaCodec::m_mime protected
Referenced by ConfigureMediaCodec(), and Open().
m_mpeg2_sequence
mpeg2_sequence* CDVDVideoCodecAndroidMediaCodec::m_mpeg2_sequence = nullptr protected
Referenced by AddData(), Open(), and ~CDVDVideoCodecAndroidMediaCodec().
m_needSecureDecoder
bool CDVDVideoCodecAndroidMediaCodec::m_needSecureDecoder = false protected
Referenced by ConfigureMediaCodec(), and Open().
m_opened
bool CDVDVideoCodecAndroidMediaCodec::m_opened = false protected
Referenced by AddData(), Dispose(), GetPicture(), Open(), and Reset().
m_OutputDuration
uint32_t CDVDVideoCodecAndroidMediaCodec::m_OutputDuration = 0 protected
Referenced by FlushInternal(), GetOutputPicture(), and GetPicture().
m_render_surface
bool CDVDVideoCodecAndroidMediaCodec::m_render_surface protected
Referenced by ConfigureMediaCodec(), ConfigureOutputFormat(), Dispose(), InitSurfaceTexture(), Open(), and ReleaseSurfaceTexture().
m_src_offset
int CDVDVideoCodecAndroidMediaCodec::m_src_offset[4] protected
m_src_stride
int CDVDVideoCodecAndroidMediaCodec::m_src_stride[4] protected
m_state
int CDVDVideoCodecAndroidMediaCodec::m_state protected
Referenced by AddData(), ConfigureMediaCodec(), Dispose(), GetOutputPicture(), GetPicture(), Open(), Reset(), SignalEndOfStream(), surfaceCreated(), and surfaceDestroyed().
m_surfaceTexture
std::shared_ptr<CJNISurfaceTexture> CDVDVideoCodecAndroidMediaCodec::m_surfaceTexture protected
Referenced by GetOutputPicture(), InitSurfaceTexture(), and ReleaseSurfaceTexture().
m_textureId
unsigned int CDVDVideoCodecAndroidMediaCodec::m_textureId = 0 protected
Referenced by GetOutputPicture(), InitSurfaceTexture(), and ReleaseSurfaceTexture().
m_useDTSforPTS
bool CDVDVideoCodecAndroidMediaCodec::m_useDTSforPTS = false protected
Referenced by AddData(), and Open().
m_videobuffer
VideoPicture CDVDVideoCodecAndroidMediaCodec::m_videobuffer protected
Referenced by CDVDVideoCodecAndroidMediaCodec(), ConfigureOutputFormat(), Dispose(), GetOutputPicture(), GetPicture(), Open(), and Reset().
m_videoBufferPool
std::shared_ptr<CMediaCodecVideoBufferPool> CDVDVideoCodecAndroidMediaCodec::m_videoBufferPool protected
Referenced by Dispose(), GetOutputPicture(), Open(), and SignalEndOfStream().
The documentation for this class was generated from the following files:
DVDVideoCodecAndroidMediaCodec.h
DVDVideoCodecAndroidMediaCodec.cpp