Kodi Documentation: CTextureMap Class Reference
CTextureMap Class Reference
Guilib classes » Graphics and Screen » Textures and Fonts
#include <TextureManager.h>
Public Member Functions
CTextureMap ()
CTextureMap (const std::string &textureName, int width, int height, int loops)
virtual ~CTextureMap ()
void Add (std::unique_ptr< CTexture > texture, int delay)
bool Release ()
const std::string & GetName () const
const CTextureArray & GetTexture ()
void Dump () const
uint32_t GetMemoryUsage () const
void Flush ()
bool IsEmpty () const
void SetHeight (int height)
void SetWidth (int height)
Protected Member Functions
void FreeTexture ()
Protected Attributes
CTextureArray m_texture
std::string m_textureName
unsigned int m_referenceCount
uint32_t m_memUsage
Constructor & Destructor Documentation
CTextureMap() [1/2]
CTextureMap::CTextureMap ()
References m_memUsage, and m_referenceCount.
CTextureMap() [2/2]
CTextureMap::CTextureMap (const std::string & textureName, int width, int height, int loops)
References m_memUsage, and m_referenceCount.
~CTextureMap()
CTextureMap::~CTextureMap () virtual
References FreeTexture().
Member Function Documentation
Add()
void CTextureMap::Add (std::unique_ptr< CTexture > texture, int delay)
References CTextureArray::Add(), m_memUsage, and m_texture.
Referenced by CGUITextureManager::Load().
Dump()
void CTextureMap::Dump () const
References CLog::Log(), LOGDEBUG, m_referenceCount, m_texture, m_textureName, and CTextureArray::m_textures.
Referenced by CGUITextureManager::Dump().
Flush()
void CTextureMap::Flush ()
References FreeTexture(), and m_referenceCount.
Referenced by CGUITextureManager::Flush().
FreeTexture()
void CTextureMap::FreeTexture () protected
References CTextureArray::Free(), and m_texture.
Referenced by Flush(), and ~CTextureMap().
GetMemoryUsage()
unsigned int CTextureMap::GetMemoryUsage () const
References m_memUsage.
Referenced by CGUITextureManager::GetMemoryUsage(), and CGUITextureManager::Load().
GetName()
const std::string & CTextureMap::GetName () const
References m_textureName.
Referenced by CGUITextureManager::Cleanup(), CGUITextureManager::HasTexture(), CGUITextureManager::Load(), and CGUITextureManager::ReleaseTexture().
GetTexture()
const CTextureArray & CTextureMap::GetTexture ()
References m_referenceCount, and m_texture.
Referenced by CGUITextureManager::Load().
IsEmpty()
bool CTextureMap::IsEmpty () const
References m_texture, and CTextureArray::m_textures.
Referenced by CGUITextureManager::Dump(), and CGUITextureManager::Flush().
Release()
bool CTextureMap::Release ()
References m_referenceCount, m_texture, and CTextureArray::m_textures.
Referenced by CGUITextureManager::ReleaseTexture().
SetHeight()
void CTextureMap::SetHeight (int height)
References CTextureArray::m_height, and m_texture.
Referenced by CGUITextureManager::Load().
SetWidth()
void CTextureMap::SetWidth (int height)
References m_texture, and CTextureArray::m_width.
Referenced by CGUITextureManager::Load().
Member Data Documentation
m_memUsage
uint32_t CTextureMap::m_memUsage protected
Referenced by Add(), CTextureMap(), CTextureMap(), and GetMemoryUsage().
m_referenceCount
unsigned int CTextureMap::m_referenceCount protected
Referenced by CTextureMap(), CTextureMap(), Dump(), Flush(), GetTexture(), and Release().
m_texture
CTextureArray CTextureMap::m_texture protected
Referenced by Add(), Dump(), FreeTexture(), GetTexture(), IsEmpty(), Release(), SetHeight(), and SetWidth().
m_textureName
std::string CTextureMap::m_textureName protected
Referenced by Dump(), and GetName().
The documentation for this class was generated from the following files:
TextureManager.h
TextureManager.cpp