Kodi Documentation: EmbeddedArtInfo Class Reference
EmbeddedArtInfo Class Reference
#include <EmbeddedArt.h>
Public Member Functions
EmbeddedArtInfo ()=default
EmbeddedArtInfo (size_t size, const std::string &mime, const std::string &type="")
virtual ~EmbeddedArtInfo ()=default
void Archive (CArchive &ar) override
void Set (size_t size, const std::string &mime, const std::string &type="")
void Clear ()
bool Empty () const
bool Matches (const EmbeddedArtInfo &right) const
void SetType (const std::string &type)
Public Attributes
size_t m_size = 0
std::string m_mime
std::string m_type
Additional Inherited Members
Protected Member Functions inherited from IArchivable
virtual ~IArchivable ()=default
Constructor & Destructor Documentation
EmbeddedArtInfo() [1/2]
EmbeddedArtInfo::EmbeddedArtInfo () default
EmbeddedArtInfo() [2/2]
EmbeddedArtInfo::EmbeddedArtInfo (size_t size, const std::string & mime, const std::string & type = "")
References Set().
~EmbeddedArtInfo()
virtual EmbeddedArtInfo::~EmbeddedArtInfo () virtual default
Member Function Documentation
Archive()
void EmbeddedArtInfo::Archive (CArchive & ar) override virtual
Implements IArchivable.
References CArchive::IsStoring(), m_mime, m_size, and m_type.
Clear()
void EmbeddedArtInfo::Clear ()
References m_mime, and m_size.
Referenced by CSong::Clear(), and MUSIC_INFO::CMusicInfoTag::Clear().
Empty()
bool EmbeddedArtInfo::Empty () const
References m_size.
Referenced by KODI::VIDEO::anonymous_namespace{VideoEmbeddedImageFileLoader.cpp}::GetEmbeddedThumb(), anonymous_namespace{MusicEmbeddedImageFileLoader.cpp}::GetEmbeddedThumb(), CSong::HasArt(), and CMusicThumbLoader::LoadItemLookup().
Matches()
bool EmbeddedArtInfo::Matches (const EmbeddedArtInfo & right) const
References m_mime, m_size, m_type, and right.
Referenced by CSong::ArtMatches().
Set()
void EmbeddedArtInfo::Set (size_t size, const std::string & mime, const std::string & type = "")
References m_mime, m_size, and m_type.
Referenced by EmbeddedArtInfo(), EmbeddedArt::Set(), and MUSIC_INFO::CMusicInfoTag::SetCoverArtInfo().
SetType()
void EmbeddedArtInfo::SetType (const std::string & type) inline
References m_type.
Member Data Documentation
m_mime
std::string EmbeddedArtInfo::m_mime
Referenced by Archive(), Clear(), MUSIC_INFO::CMusicEmbeddedImageFileLoader::Load(), KODI::VIDEO::CVideoEmbeddedImageFileLoader::Load(), Matches(), Set(), and MUSIC_INFO::CMusicInfoTag::SetSong().
m_size
size_t EmbeddedArtInfo::m_size = 0
Referenced by Archive(), Clear(), Empty(), MUSIC_INFO::CMusicEmbeddedImageFileLoader::Load(), KODI::VIDEO::CVideoEmbeddedImageFileLoader::Load(), Matches(), Set(), and MUSIC_INFO::CMusicInfoTag::SetSong().
m_type
std::string EmbeddedArtInfo::m_type
Referenced by Archive(), Matches(), Set(), and SetType().
The documentation for this class was generated from the following files:
EmbeddedArt.h
EmbeddedArt.cpp