Kodi Documentation: XFILE::CPipeFile Class Reference
XFILE::CPipeFile Class Reference
#include <PipeFile.h>
Public Member Functions
CPipeFile ()
~CPipeFile () override
int64_t GetPosition () override
int64_t GetLength () override
virtual void SetLength (int64_t len)
bool Open (const CURL &url) override
bool Exists (const CURL &url) override
int Stat (const CURL &url, struct __stat64 *buffer) override
int Stat (struct __stat64 *buffer) override
ssize_t Read (void *lpBuf, size_t uiBufSize) override
ssize_t Write (const void *lpBuf, size_t uiBufSize) override
int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET) override
void Close () override
void Flush () override
virtual int64_t GetAvailableRead ()
bool OpenForWrite (const CURL &url, bool bOverWrite=false) override
bool Delete (const CURL &url) override
bool Rename (const CURL &url, const CURL &urlnew) override
int IoControl (EIoControl request, void *param) override
std::string GetName () const
void OnPipeOverFlow () override
void OnPipeUnderFlow () override
void AddListener (IPipeListener *l)
void RemoveListener (IPipeListener *l)
void SetEof ()
bool IsEof ()
bool IsEmpty ()
bool IsClosed ()
void SetOpenThreshold (int threshold)
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool ReOpen (const CURL &url)
virtual bool ReadString (char *szLine, int iLineLength)
virtual int Truncate (int64_t size)
virtual int GetChunkSize ()
virtual double GetDownloadSpeed ()
virtual bool SetHidden (const CURL &url, bool hidden)
virtual const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
virtual const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
Public Member Functions inherited from XFILE::IPipeListener
virtual ~IPipeListener ()=default
Protected Attributes
int64_t m_pos = 0
int64_t m_length = -1
XFILE::Pipe * m_pipe
CCriticalSection m_lock
std::vector< XFILE::IPipeListener * > m_listeners
Constructor & Destructor Documentation
CPipeFile()
CPipeFile::CPipeFile ()
~CPipeFile()
CPipeFile::~CPipeFile () override
References Close().
Member Function Documentation
AddListener()
void CPipeFile::AddListener (IPipeListener * l)
References m_listeners, and m_lock.
Close()
void CPipeFile::Close () override virtual
Implements XFILE::IFile.
References XFILE::PipesManager::ClosePipe(), XFILE::PipesManager::GetInstance(), m_pipe, and XFILE::Pipe::RemoveListener().
Referenced by CAirTunesServer::AudioOutputFunctions::audio_destroy(), and ~CPipeFile().
Delete()
bool CPipeFile::Delete (const CURL & url) override virtual
Reimplemented from XFILE::IFile.
Exists()
bool CPipeFile::Exists (const CURL & url) override virtual
Implements XFILE::IFile.
References XFILE::PipesManager::Exists(), CURL::Get(), XFILE::PipesManager::GetInstance(), and name.
Flush()
void CPipeFile::Flush () override virtual
Reimplemented from XFILE::IFile.
References XFILE::Pipe::Flush(), and m_pipe.
GetAvailableRead()
int64_t CPipeFile::GetAvailableRead () virtual
References XFILE::Pipe::GetAvailableRead(), and m_pipe.
GetLength()
int64_t CPipeFile::GetLength () override virtual
Implements XFILE::IFile.
References m_length.
GetName()
std::string CPipeFile::GetName () const
References XFILE::Pipe::GetName(), and m_pipe.
Referenced by CAirTunesServer::AudioOutputFunctions::audio_init().
GetPosition()
int64_t CPipeFile::GetPosition () override virtual
Implements XFILE::IFile.
References m_pos.
IoControl()
int CPipeFile::IoControl (EIoControl request, void * param) override virtual
Reimplemented from XFILE::IFile.
IsClosed()
bool CPipeFile::IsClosed ()
References m_pipe.
IsEmpty()
bool CPipeFile::IsEmpty ()
References XFILE::Pipe::IsEmpty(), and m_pipe.
IsEof()
bool CPipeFile::IsEof ()
References XFILE::Pipe::IsEof(), and m_pipe.
OnPipeOverFlow()
void CPipeFile::OnPipeOverFlow () override virtual
Implements XFILE::IPipeListener.
References m_listeners, m_lock, and OnPipeOverFlow().
Referenced by OnPipeOverFlow().
OnPipeUnderFlow()
void CPipeFile::OnPipeUnderFlow () override virtual
Implements XFILE::IPipeListener.
References m_listeners, and OnPipeUnderFlow().
Referenced by OnPipeUnderFlow().
Open()
bool CPipeFile::Open (const CURL & url) override virtual
Implements XFILE::IFile.
References XFILE::Pipe::AddListener(), CURL::Get(), XFILE::PipesManager::GetInstance(), m_pipe, name, and XFILE::PipesManager::OpenPipe().
OpenForWrite()
bool CPipeFile::OpenForWrite (const CURL & url, bool bOverWrite = false) override virtual
Reimplemented from XFILE::IFile.
References XFILE::Pipe::AddListener(), XFILE::PipesManager::CreatePipe(), CURL::Get(), XFILE::PipesManager::GetInstance(), m_pipe, and name.
Referenced by CAirTunesServer::AudioOutputFunctions::audio_init().
Read()
ssize_t CPipeFile::Read (void * bufPtr, size_t bufSize) override virtual
Attempt to read bufSize bytes from currently opened file into buffer bufPtr.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully read bytes if any bytes were read and stored in buffer, zero if no bytes are available to read (end of file was reached) or undetectable error occur, -1 in case of any explicit error
Implements XFILE::IFile.
References m_pipe, XFILE::Pipe::Read(), and SSIZE_MAX.
RemoveListener()
void CPipeFile::RemoveListener (IPipeListener * l)
References m_listeners, and m_lock.
Rename()
bool CPipeFile::Rename (const CURL & url, const CURL & urlnew) override virtual
Reimplemented from XFILE::IFile.
Seek()
int64_t CPipeFile::Seek (int64_t iFilePosition, int iWhence = SEEK_SET) override virtual
Implements XFILE::IFile.
SetEof()
void CPipeFile::SetEof ()
References m_pipe, and XFILE::Pipe::SetEof().
Referenced by CAirTunesServer::AudioOutputFunctions::audio_destroy().
SetLength()
void CPipeFile::SetLength (int64_t len) virtual
References m_length.
SetOpenThreshold()
void CPipeFile::SetOpenThreshold (int threshold)
References m_pipe, and XFILE::Pipe::SetOpenThreshold().
Referenced by CAirTunesServer::AudioOutputFunctions::audio_init().
Stat() [1/2]
int CPipeFile::Stat (const CURL & url, struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about file specified by url. For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
url specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Implements XFILE::IFile.
Stat() [2/2]
int CPipeFile::Stat (struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about currently open file For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Reimplemented from XFILE::IFile.
References m_length.
Write()
ssize_t CPipeFile::Write (const void * bufPtr, size_t bufSize) override virtual
Attempt to write bufSize bytes from buffer bufPtr into currently opened file.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully written bytes if any bytes were written, zero if no bytes were written and no detectable error occur, -1 in case of any explicit error
Reimplemented from XFILE::IFile.
References m_pipe, and XFILE::Pipe::Write().
Referenced by CAirTunesServer::AudioOutputFunctions::audio_init(), and CAirTunesServer::AudioOutputFunctions::audio_process().
Member Data Documentation
m_length
int64_t XFILE::CPipeFile::m_length = -1 protected
Referenced by GetLength(), SetLength(), and Stat().
m_listeners
std::vector<XFILE::IPipeListener *> XFILE::CPipeFile::m_listeners protected
Referenced by AddListener(), OnPipeOverFlow(), OnPipeUnderFlow(), and RemoveListener().
m_lock
CCriticalSection XFILE::CPipeFile::m_lock protected
Referenced by AddListener(), OnPipeOverFlow(), and RemoveListener().
m_pipe
XFILE::Pipe* XFILE::CPipeFile::m_pipe protected
Referenced by Close(), Flush(), GetAvailableRead(), GetName(), IsClosed(), IsEmpty(), IsEof(), Open(), OpenForWrite(), Read(), SetEof(), SetOpenThreshold(), and Write().
m_pos
int64_t XFILE::CPipeFile::m_pos = 0 protected
Referenced by GetPosition().
The documentation for this class was generated from the following files:
PipeFile.h
PipeFile.cpp