Kodi Documentation: VAAPI::CFFmpegPostproc Class Reference
VAAPI::CFFmpegPostproc Class Reference
#include <VAAPI.h>
Public Member Functions
CFFmpegPostproc ()
~CFFmpegPostproc () override
bool PreInit (CVaapiConfig &config, SDiMethods *methods=NULL) override
bool Init (EINTERLACEMETHOD method) override
bool AddPicture (CVaapiDecodedPicture &inPic) override
bool Filter (CVaapiProcessedPicture &outPic) override
void ClearRef (CVaapiProcessedPicture &pic) override
void Flush () override
bool UpdateDeintMethod (EINTERLACEMETHOD method) override
bool DoesSync () override
bool UseVideoSurface () override
void Discard (COutput *output, ReadyToDispose cb) override
Public Member Functions inherited from VAAPI::CPostproc
virtual ~CPostproc ()=default
virtual bool WantsPic ()
Protected Member Functions
bool CheckSuccess (VAStatus status, const std::string &function)
void Close ()
Protected Attributes
DllLibSSE4 m_dllSSE4
uint8_t * m_cache
AVFilterGraph * m_pFilterGraph
AVFilterContext * m_pFilterIn
AVFilterContext * m_pFilterOut
AVFrame * m_pFilterFrameIn
AVFrame * m_pFilterFrameOut
EINTERLACEMETHOD m_diMethod
VideoPicture m_DVDPic
double m_frametime
double m_lastOutPts
ReadyToDispose m_cbDispose = nullptr
COutput * m_pOut
int m_refsToPics = 0
Protected Attributes inherited from VAAPI::CPostproc
CVaapiConfig m_config
int m_step
Detailed Description
ffmpeg filter
Constructor & Destructor Documentation
CFFmpegPostproc()
CFFmpegPostproc::CFFmpegPostproc ()
References DVD_NOPTS_VALUE, m_cache, m_DVDPic, m_frametime, m_lastOutPts, m_pFilterFrameIn, m_pFilterFrameOut, m_pFilterGraph, and VideoPicture::pts.
~CFFmpegPostproc()
CFFmpegPostproc::~CFFmpegPostproc () override
References KODI::MEMORY::AlignedFree(), Close(), m_cache, m_dllSSE4, m_pFilterFrameIn, m_pFilterFrameOut, and DllDynamic::Unload().
Member Function Documentation
AddPicture()
bool CFFmpegPostproc::AddPicture (CVaapiDecodedPicture & inPic) override virtual
Implements VAAPI::CPostproc.
References CheckSuccess(), VAAPI::CVideoSurfaces::ClearRender(), DllLibSSE4Interface::copy_frame(), VAAPI::CVaapiConfig::dpy, DVD_NOPTS_VALUE, DVD_TIME_BASE, VAAPI::CVaapiDecodedPicture::DVDPic, DVP_FLAG_INTERLACED, DVP_FLAG_TOP_FIELD_FIRST, VideoPicture::iFlags, CLog::Log(), LOGERROR, m_cache, VAAPI::CPostproc::m_config, m_diMethod, m_dllSSE4, m_DVDPic, m_frametime, m_pFilterFrameIn, m_pFilterFrameOut, m_pFilterIn, VAAPI::CPostproc::m_step, VideoPicture::pts, VideoPicture::SetParams(), VAAPI::CVaapiDecodedPicture::videoSurface, VAAPI::CVaapiConfig::videoSurfaces, VAAPI::CVaapiConfig::vidHeight, VAAPI::CVaapiConfig::vidWidth, VS_INTERLACEMETHOD_DEINTERLACE, VS_INTERLACEMETHOD_NONE, and VS_INTERLACEMETHOD_RENDER_BOB.
CheckSuccess()
bool CFFmpegPostproc::CheckSuccess (VAStatus status, const std::string & function) protected
References CLog::Log(), and LOGERROR.
Referenced by AddPicture(), and PreInit().
ClearRef()
void CFFmpegPostproc::ClearRef (CVaapiProcessedPicture & pic) override virtual
Implements VAAPI::CPostproc.
References VAAPI::CVaapiProcessedPicture::frame, m_cbDispose, m_pOut, and m_refsToPics.
Close()
void CFFmpegPostproc::Close () protected
References m_pFilterGraph.
Referenced by Flush(), and ~CFFmpegPostproc().
Discard()
void CFFmpegPostproc::Discard (COutput * output, ReadyToDispose cb) override virtual
Reimplemented from VAAPI::CPostproc.
References m_cbDispose, m_pOut, and m_refsToPics.
DoesSync()
bool CFFmpegPostproc::DoesSync () override virtual
Implements VAAPI::CPostproc.
Filter()
bool CFFmpegPostproc::Filter (CVaapiProcessedPicture & outPic) override virtual
Implements VAAPI::CPostproc.
References DVD_NOPTS_VALUE, DVD_TIME_BASE, VAAPI::CVaapiProcessedPicture::DVDPic, DVP_FLAG_INTERLACED, DVP_FLAG_REPEAT_TOP_FIELD, DVP_FLAG_TOP_FIELD_FIRST, VAAPI::CVaapiProcessedPicture::frame, VideoPicture::iFlags, int64_t(), CLog::Log(), LOGERROR, m_diMethod, m_DVDPic, m_frametime, m_lastOutPts, m_pFilterFrameOut, m_pFilterOut, m_refsToPics, VAAPI::CPostproc::m_step, VideoPicture::pts, VideoPicture::SetParams(), VAAPI::CVaapiProcessedPicture::source, VS_INTERLACEMETHOD_DEINTERLACE, VS_INTERLACEMETHOD_NONE, and VS_INTERLACEMETHOD_RENDER_BOB.
Flush()
void CFFmpegPostproc::Flush () override virtual
Implements VAAPI::CPostproc.
References Close(), DVD_NOPTS_VALUE, Init(), m_diMethod, m_DVDPic, m_frametime, m_lastOutPts, and VideoPicture::pts.
Init()
bool CFFmpegPostproc::Init (EINTERLACEMETHOD method) override virtual
Implements VAAPI::CPostproc.
References VAAPI::CVaapiConfig::aspect, CLog::Log(), LOGDEBUG, LOGERROR, LOGVIDEO, VAAPI::CPostproc::m_config, m_diMethod, m_pFilterFrameIn, m_pFilterFrameOut, m_pFilterGraph, m_pFilterIn, m_pFilterOut, VAAPI::CVaapiConfig::processInfo, CProcessInfo::SetVideoDeintMethod(), VAAPI::CVaapiConfig::vidHeight, VAAPI::CVaapiConfig::vidWidth, VS_INTERLACEMETHOD_DEINTERLACE, VS_INTERLACEMETHOD_NONE, and VS_INTERLACEMETHOD_RENDER_BOB.
Referenced by Flush().
PreInit()
bool CFFmpegPostproc::PreInit (CVaapiConfig & config, SDiMethods * methods = NULL) override virtual
Implements VAAPI::CPostproc.
References KODI::MEMORY::AlignedMalloc(), CACHED_BUFFER_SIZE, CheckSuccess(), VAAPI::SDiMethods::diMethods, VAAPI::CVaapiConfig::dpy, VAAPI::CVideoSurfaces::GetAtIndex(), DllDynamic::Load(), CLog::Log(), LOGERROR, LOGINFO, LOGWARNING, m_cache, VAAPI::CPostproc::m_config, m_dllSSE4, VAAPI::SDiMethods::numDiMethods, VAAPI::CVaapiConfig::videoSurfaces, VAAPI::CVaapiConfig::vidHeight, VAAPI::CVaapiConfig::vidWidth, VS_INTERLACEMETHOD_DEINTERLACE, and VS_INTERLACEMETHOD_RENDER_BOB.
UpdateDeintMethod()
bool CFFmpegPostproc::UpdateDeintMethod (EINTERLACEMETHOD method) override virtual
Todo:
switching between certain methods could be done without deinit/init
Implements VAAPI::CPostproc.
References m_diMethod.
UseVideoSurface()
bool CFFmpegPostproc::UseVideoSurface () override virtual
Implements VAAPI::CPostproc.
Member Data Documentation
m_cache
uint8_t* VAAPI::CFFmpegPostproc::m_cache protected
Referenced by AddPicture(), CFFmpegPostproc(), PreInit(), and ~CFFmpegPostproc().
m_cbDispose
ReadyToDispose VAAPI::CFFmpegPostproc::m_cbDispose = nullptr protected
Referenced by ClearRef(), and Discard().
m_diMethod
EINTERLACEMETHOD VAAPI::CFFmpegPostproc::m_diMethod protected
Referenced by AddPicture(), Filter(), Flush(), Init(), and UpdateDeintMethod().
m_dllSSE4
DllLibSSE4 VAAPI::CFFmpegPostproc::m_dllSSE4 protected
Referenced by AddPicture(), PreInit(), and ~CFFmpegPostproc().
m_DVDPic
VideoPicture VAAPI::CFFmpegPostproc::m_DVDPic protected
Referenced by AddPicture(), CFFmpegPostproc(), Filter(), and Flush().
m_frametime
double VAAPI::CFFmpegPostproc::m_frametime protected
Referenced by AddPicture(), CFFmpegPostproc(), Filter(), and Flush().
m_lastOutPts
double VAAPI::CFFmpegPostproc::m_lastOutPts protected
Referenced by CFFmpegPostproc(), Filter(), and Flush().
m_pFilterFrameIn
AVFrame* VAAPI::CFFmpegPostproc::m_pFilterFrameIn protected
Referenced by AddPicture(), CFFmpegPostproc(), Init(), and ~CFFmpegPostproc().
m_pFilterFrameOut
AVFrame* VAAPI::CFFmpegPostproc::m_pFilterFrameOut protected
Referenced by AddPicture(), CFFmpegPostproc(), Filter(), Init(), and ~CFFmpegPostproc().
m_pFilterGraph
AVFilterGraph* VAAPI::CFFmpegPostproc::m_pFilterGraph protected
Referenced by CFFmpegPostproc(), Close(), and Init().
m_pFilterIn
AVFilterContext* VAAPI::CFFmpegPostproc::m_pFilterIn protected
Referenced by AddPicture(), and Init().
m_pFilterOut
AVFilterContext* VAAPI::CFFmpegPostproc::m_pFilterOut protected
Referenced by Filter(), and Init().
m_pOut
COutput* VAAPI::CFFmpegPostproc::m_pOut protected
Referenced by ClearRef(), and Discard().
m_refsToPics
int VAAPI::CFFmpegPostproc::m_refsToPics = 0 protected
Referenced by ClearRef(), Discard(), and Filter().
The documentation for this class was generated from the following files:
VAAPI.h
VAAPI.cpp