Kodi Documentation: KODI::GAME::CGameClientInGameSaves Class Reference
KODI::GAME::CGameClientInGameSaves Class Reference
Games
This class implements in-game saves.
#include <GameClientInGameSaves.h>
Public Member Functions
CGameClientInGameSaves (CGameClient *addon, const AddonInstance_Game *dllStruct)
Constructor.
void Load ()
Load in-game data.
void Save ()
Save in-game data.
Private Member Functions
std::string GetPath (GAME_MEMORY memoryType)
void Load (GAME_MEMORY memoryType)
void Save (GAME_MEMORY memoryType)
Private Attributes
const CGameClient *const m_gameClient
const AddonInstance_Game *const m_dllStruct
Detailed Description
This class implements in-game saves.
Some games do not implement state persistence on their own, but rely on the frontend for saving their current memory state to disk. This is mostly the case for emulators for SRAM (battery backed up ram on cartridges) or memory cards.
Differences to save states:
Works only for supported games (e.g. emulated games with SRAM support)
Often works emulator independent (and can be used to start a game with one emulator and continue with another)
Visible in-game (e.g. in-game save game selection menus)
Constructor & Destructor Documentation
CGameClientInGameSaves()
CGameClientInGameSaves::CGameClientInGameSaves (CGameClient * addon, const AddonInstance_Game * dllStruct)
Constructor.
Parameters
addon The game client implementation.
dllStruct The emulator or game for which the in-game saves are processed.
References m_dllStruct, and m_gameClient.
Member Function Documentation
GetPath()
std::string CGameClientInGameSaves::GetPath (GAME_MEMORY memoryType) private
References URIUtils::AddFileToFolder(), XFILE::CDirectory::Create(), XFILE::CDirectory::Exists(), GAME_MEMORY_RTC, GAME_MEMORY_SAVE_RAM, URIUtils::GetFileName(), KODI::GAME::CGameClient::GetGamePath(), CServiceBroker::GetGameServices(), KODI::GAME::CGameServices::GetSavestatesFolder(), ADDON::CAddon::ID(), INGAME_SAVES_DIRECTORY, INGAME_SAVES_EXTENSION_RTC, INGAME_SAVES_EXTENSION_SAVE_RAM, and m_gameClient.
Referenced by Load(), and Save().
Load() [1/2]
void CGameClientInGameSaves::Load ()
Load in-game data.
References GAME_MEMORY_RTC, GAME_MEMORY_SAVE_RAM, and Load().
Referenced by Load().
Load() [2/2]
void CGameClientInGameSaves::Load (GAME_MEMORY memoryType) private
References XFILE::CFile::Exists(), GetPath(), ADDON::CAddon::ID(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_dllStruct, m_gameClient, XFILE::CFile::Read(), AddonInstance_Game::toAddon, and KODI::GAME::CGameClientTranslator::ToString().
Save() [1/2]
void CGameClientInGameSaves::Save ()
Save in-game data.
References GAME_MEMORY_RTC, GAME_MEMORY_SAVE_RAM, and Save().
Referenced by Save().
Save() [2/2]
void CGameClientInGameSaves::Save (GAME_MEMORY memoryType) private
References GetPath(), ADDON::CAddon::ID(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_dllStruct, m_gameClient, AddonInstance_Game::toAddon, KODI::GAME::CGameClientTranslator::ToString(), and XFILE::CFile::Write().
Member Data Documentation
m_dllStruct
const AddonInstance_Game* const KODI::GAME::CGameClientInGameSaves::m_dllStruct private
Referenced by CGameClientInGameSaves(), Load(), and Save().
m_gameClient
const CGameClient* const KODI::GAME::CGameClientInGameSaves::m_gameClient private
Referenced by CGameClientInGameSaves(), GetPath(), Load(), and Save().
The documentation for this class was generated from the following files:
GameClientInGameSaves.h
GameClientInGameSaves.cpp