Kodi Documentation: anonymous_namespace{PVRGUIInfo.cpp} Namespace Reference
anonymous_namespace{PVRGUIInfo.cpp} Namespace Reference
Functions
std::string GetAsLocalizedDateString (const CDateTime &datetime, bool bLongDate)
std::string GetAsLocalizedTimeString (const CDateTime &datetime)
std::string GetAsLocalizedDateTimeString (const CDateTime &datetime)
Function Documentation
GetAsLocalizedDateString()
std::string anonymous_namespace{PVRGUIInfo.cpp}::GetAsLocalizedDateString (const CDateTime & datetime, bool bLongDate)
References CDateTime::GetAsLocalizedDate(), GetAsLocalizedDateString(), and CDateTime::IsValid().
Referenced by GetAsLocalizedDateString().
GetAsLocalizedDateTimeString()
std::string anonymous_namespace{PVRGUIInfo.cpp}::GetAsLocalizedDateTimeString (const CDateTime & datetime)
References CDateTime::GetAsLocalizedDateTime(), GetAsLocalizedDateTimeString(), and CDateTime::IsValid().
Referenced by GetAsLocalizedDateTimeString().
GetAsLocalizedTimeString()
std::string anonymous_namespace{PVRGUIInfo.cpp}::GetAsLocalizedTimeString (const CDateTime & datetime)
References CDateTime::GetAsLocalizedTime(), GetAsLocalizedTimeString(), and CDateTime::IsValid().
Referenced by GetAsLocalizedTimeString().