Kodi Documentation: CProgramThumbLoader Class Reference
CProgramThumbLoader Class Reference
#include <ThumbLoader.h>
Public Member Functions
CProgramThumbLoader ()
~CProgramThumbLoader () override
bool LoadItem (CFileItem *pItem) override
bool LoadItemCached (CFileItem *pItem) override
bool LoadItemLookup (CFileItem *pItem) override
virtual bool FillThumb (CFileItem &item)
Fill the thumb of a programs item First uses a cached thumb from a previous run, then checks for a local thumb and caches it for the next run.
Public Member Functions inherited from CThumbLoader
CThumbLoader ()
~CThumbLoader () override
void OnLoaderStart () override
void OnLoaderFinish () override
virtual bool FillLibraryArt (CFileItem &item)
helper function to fill the art for a library item
virtual std::string GetCachedImage (const CFileItem &item, const std::string &type)
Checks whether the given item has an image listed in the texture database.
virtual void SetCachedImage (const CFileItem &item, const std::string &type, const std::string &image)
Associate an image with the given item in the texture database.
Public Member Functions inherited from CBackgroundInfoLoader
CBackgroundInfoLoader ()
~CBackgroundInfoLoader () override
void Load (CFileItemList &items)
bool IsLoading ()
void Run () override
void SetObserver (IBackgroundLoaderObserver *pObserver)
void SetProgressCallback (IProgressCallback *pCallback)
void StopThread ()
void StopAsync ()
Public Member Functions inherited from IRunnable
virtual void Cancel ()
virtual ~IRunnable ()=default
Static Public Member Functions
static std::string GetLocalThumb (const CFileItem &item)
Get a local thumb for a programs item Shortcuts are checked, then we check for a file or folder thumb.
Additional Inherited Members
Protected Attributes inherited from CThumbLoader
CTextureDatabase * m_textureDatabase
Protected Attributes inherited from CBackgroundInfoLoader
CFileItemList * m_pVecItems {nullptr}
std::vector< CFileItemPtr > m_vecItems
CCriticalSection m_lock
volatile bool m_bIsLoading {false}
volatile bool m_bStop {true}
CThread * m_thread {nullptr}
IBackgroundLoaderObserver * m_pObserver {nullptr}
IProgressCallback * m_pProgressCallback {nullptr}
Constructor & Destructor Documentation
CProgramThumbLoader()
CProgramThumbLoader::CProgramThumbLoader () default
~CProgramThumbLoader()
CProgramThumbLoader::~CProgramThumbLoader () override default
Member Function Documentation
FillThumb()
bool CProgramThumbLoader::FillThumb (CFileItem & item) virtual
Fill the thumb of a programs item First uses a cached thumb from a previous run, then checks for a local thumb and caches it for the next run.
Parameters
item the CFileItem object to fill
Returns
true if we fill the thumb, false otherwise
See also
GetLocalThumb
References CGUIListItem::GetArt(), CThumbLoader::GetCachedImage(), GetLocalThumb(), CServiceBroker::GetTextureCache(), CGUIListItem::SetArt(), and CThumbLoader::SetCachedImage().
Referenced by LoadItemCached().
GetLocalThumb()
std::string CProgramThumbLoader::GetLocalThumb (const CFileItem & item) static
Get a local thumb for a programs item Shortcuts are checked, then we check for a file or folder thumb.
Parameters
item the CFileItem object to check
Returns
the local thumb (if it exists)
See also
FillThumb
References CFileUtils::Exists(), KODI::ART::GetFolderThumb(), KODI::ART::GetTBNFile(), CFileItem::IsAddonsPath(), and CGUIListItem::m_bIsFolder.
Referenced by FillThumb().
LoadItem()
bool CProgramThumbLoader::LoadItem (CFileItem * pItem) override virtual
Reimplemented from CBackgroundInfoLoader.
References LoadItemCached(), and LoadItemLookup().
LoadItemCached()
bool CProgramThumbLoader::LoadItemCached (CFileItem * pItem) override virtual
Reimplemented from CBackgroundInfoLoader.
References FillThumb(), and CFileItem::IsParentFolder().
Referenced by LoadItem().
LoadItemLookup()
bool CProgramThumbLoader::LoadItemLookup (CFileItem * pItem) override virtual
Reimplemented from CBackgroundInfoLoader.
Referenced by LoadItem().
The documentation for this class was generated from the following files:
ThumbLoader.h
ThumbLoader.cpp