Kodi Documentation: PictureBuiltins.cpp File Reference
PictureBuiltins.cpp File Reference
#include "PictureBuiltins.h"
#include "GUIUserMessages.h"
#include "ServiceBroker.h"
#include "guilib/GUIComponent.h"
#include "guilib/GUIWindowManager.h"
#include "utils/StringUtils.h"
Functions
static int Show (const std::vector< std::string > &params)
Show a picture.
template<bool Recursive>
static int Slideshow (const std::vector< std::string > &params)
Start a slideshow.
Function Documentation
Show()
static int Show (const std::vector< std::string > & params) static
Show a picture.
Parameters
params The parameters.
params[0] = URL of picture.
References CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_SHOW_PICTURE, CGUIWindow::OnMessage(), CGUIMessage::SetStringParam(), and WINDOW_SLIDESHOW.
Referenced by ADDON::Interface_GUIWindow::close(), ADDON::Interface_GUIWindow::do_modal(), CPictureBuiltins::GetOperations(), and ADDON::Interface_GUIWindow::show().
Slideshow()
template<bool Recursive> static int Slideshow (const std::vector< std::string > & params) static
Start a slideshow.
Parameters
params The parameters.
params[0] = Path to run slideshow for. params[1,..] = "recursive" to run a recursive slideshow. params[1,...] = "random" to randomize slideshow. params[1,...] = "notrandom" to not randomize slideshow. params[1,...] = "pause" to start slideshow paused. params[1,...] = "beginslide=<number>" to start at a given slide.
Set the template parameter Recursive to true to run a recursive slideshow.
References KODI::UTILS::StringUtils::EqualsNoCase(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_START_SLIDESHOW, CGUIWindow::OnMessage(), CGUIMessage::SetStringParams(), KODI::UTILS::StringUtils::StartsWithNoCase(), and WINDOW_SLIDESHOW.