Kodi Documentation: PVR::CPVREpgSearchFilter Class Reference
PVR::CPVREpgSearchFilter Class Reference
#include <EpgSearchFilter.h>
Public Member Functions
CPVREpgSearchFilter ()=delete
CPVREpgSearchFilter (bool bRadio)
ctor.
void Reset ()
Clear this filter.
std::string GetPath () const
Return the path for this filter.
bool FilterEntry (const std::shared_ptr< const CPVREpgInfoTag > &tag) const
Check if a tag will be filtered or not.
bool IsRadio () const
Get the type of channels to search.
const std::string & GetSearchTerm () const
void SetSearchTerm (const std::string &strSearchTerm)
void SetSearchPhrase (const std::string &strSearchPhrase)
bool IsCaseSensitive () const
void SetCaseSensitive (bool bIsCaseSensitive)
bool ShouldSearchInDescription () const
void SetSearchInDescription (bool bSearchInDescription)
int GetGenreType () const
void SetGenreType (int iGenreType)
int GetMinimumDuration () const
void SetMinimumDuration (int iMinimumDuration)
int GetMaximumDuration () const
void SetMaximumDuration (int iMaximumDuration)
bool ShouldIgnoreFinishedBroadcasts () const
void SetIgnoreFinishedBroadcasts (bool bIgnoreFinishedBroadcasts)
bool ShouldIgnoreFutureBroadcasts () const
void SetIgnoreFutureBroadcasts (bool bIgnoreFutureBroadcasts)
const CDateTime & GetStartDateTime () const
void SetStartDateTime (const CDateTime &startDateTime)
bool IsStartAnyTime () const
void SetStartAnyTime (bool startAnyTime)
const CDateTime & GetEndDateTime () const
void SetEndDateTime (const CDateTime &endDateTime)
bool IsEndAnyTime () const
void SetEndAnyTime (bool endAnyTime)
bool ShouldIncludeUnknownGenres () const
void SetIncludeUnknownGenres (bool bIncludeUnknownGenres)
bool ShouldRemoveDuplicates () const
void SetRemoveDuplicates (bool bRemoveDuplicates)
int GetClientID () const
void SetClientID (int iClientID)
int GetChannelGroupID () const
void SetChannelGroupID (int iChannelGroupID)
int GetChannelUID () const
void SetChannelUID (int iChannelUID)
bool IsFreeToAirOnly () const
void SetFreeToAirOnly (bool bFreeToAirOnly)
bool ShouldIgnorePresentTimers () const
void SetIgnorePresentTimers (bool bIgnorePresentTimers)
bool ShouldIgnorePresentRecordings () const
void SetIgnorePresentRecordings (bool bIgnorePresentRecordings)
int GetDatabaseId () const
void SetDatabaseId (int iDatabaseId)
const std::string & GetTitle () const
void SetTitle (const std::string &title)
const std::string & GetIconPath () const
void SetIconPath (const std::string &iconPath)
const CDateTime & GetLastExecutedDateTime () const
void SetLastExecutedDateTime (const CDateTime &lastExecutedDateTime)
const PVREpgSearchData & GetEpgSearchData () const
void SetEpgSearchDataFiltered ()
bool IsChanged () const
void SetChanged (bool bChanged)
Static Public Member Functions
static void RemoveDuplicates (std::vector< std::shared_ptr< CPVREpgInfoTag > > &results)
remove duplicates from a list of epg tags.
Private Member Functions
bool MatchGenre (const std::shared_ptr< const CPVREpgInfoTag > &tag) const
bool MatchDuration (const std::shared_ptr< const CPVREpgInfoTag > &tag) const
bool MatchStartAndEndTimes (const std::shared_ptr< const CPVREpgInfoTag > &tag) const
bool MatchSearchTerm (const std::shared_ptr< const CPVREpgInfoTag > &tag) const
bool MatchChannel (const std::shared_ptr< const CPVREpgInfoTag > &tag) const
bool MatchChannelGroup (const std::shared_ptr< const CPVREpgInfoTag > &tag) const
bool MatchFreeToAir (const std::shared_ptr< const CPVREpgInfoTag > &tag) const
bool MatchTimers (const std::shared_ptr< const CPVREpgInfoTag > &tag) const
bool MatchRecordings (const std::shared_ptr< const CPVREpgInfoTag > &tag) const
Private Attributes
bool m_bChanged = false
PVREpgSearchData m_searchData
bool m_bEpgSearchDataFiltered = false
bool m_bIsCaseSensitive
int m_iMinimumDuration
int m_iMaximumDuration
bool m_bRemoveDuplicates
bool m_bIsRadio
int m_iClientID = PVR_CLIENT_INVALID_UID
int m_iChannelGroupID {-1}
int m_iChannelUID = -1
bool m_bFreeToAirOnly
bool m_bIgnorePresentTimers
bool m_bIgnorePresentRecordings
int m_iDatabaseId {PVR_EPG_SEARCH_INVALID_DATABASE_ID}
std::string m_title
std::string m_iconPath
CDateTime m_lastExecutedDateTime
Constructor & Destructor Documentation
CPVREpgSearchFilter() [1/2]
PVR::CPVREpgSearchFilter::CPVREpgSearchFilter () delete
CPVREpgSearchFilter() [2/2]
CPVREpgSearchFilter::CPVREpgSearchFilter (bool bRadio) explicit
ctor.
Parameters
bRadio the type of channels to search - if true, 'radio'. 'tv', otherwise.
References Reset().
Member Function Documentation
FilterEntry()
bool CPVREpgSearchFilter::FilterEntry (const std::shared_ptr< const CPVREpgInfoTag > & tag) const
Check if a tag will be filtered or not.
Parameters
tag The tag to check.
Returns
True if this tag matches the filter, false if not.
References MatchChannel(), MatchChannelGroup(), MatchDuration(), MatchFreeToAir(), MatchGenre(), MatchRecordings(), MatchSearchTerm(), MatchStartAndEndTimes(), and MatchTimers().
GetChannelGroupID()
int PVR::CPVREpgSearchFilter::GetChannelGroupID () const inline
References m_iChannelGroupID.
Referenced by PVR::CPVREpgDatabase::Persist().
GetChannelUID()
int PVR::CPVREpgSearchFilter::GetChannelUID () const inline
References m_iChannelUID.
Referenced by PVR::CPVREpgDatabase::Persist().
GetClientID()
int PVR::CPVREpgSearchFilter::GetClientID () const inline
References m_iClientID.
Referenced by PVR::CPVREpgDatabase::Persist().
GetDatabaseId()
int PVR::CPVREpgSearchFilter::GetDatabaseId () const inline
References m_iDatabaseId.
Referenced by PVR::CPVREpgDatabase::Delete(), PVR::CPVREpgDatabase::Persist(), and PVR::CPVREpgDatabase::UpdateSavedSearchLastExecuted().
GetEndDateTime()
const CDateTime & PVR::CPVREpgSearchFilter::GetEndDateTime () const inline
References PVR::PVREpgSearchData::m_endDateTime, and m_searchData.
Referenced by PVR::CPVREpgDatabase::Persist().
GetEpgSearchData()
const PVREpgSearchData & PVR::CPVREpgSearchFilter::GetEpgSearchData () const inline
References m_searchData.
Referenced by PVR::CPVREpgSearch::Execute().
GetGenreType()
int PVR::CPVREpgSearchFilter::GetGenreType () const inline
References PVR::PVREpgSearchData::m_iGenreType, and m_searchData.
Referenced by PVR::CPVREpgDatabase::Persist().
GetIconPath()
const std::string & PVR::CPVREpgSearchFilter::GetIconPath () const inline
References m_iconPath.
Referenced by PVR::CPVREpgDatabase::Persist().
GetLastExecutedDateTime()
const CDateTime & PVR::CPVREpgSearchFilter::GetLastExecutedDateTime () const inline
References m_lastExecutedDateTime.
Referenced by PVR::CPVREpgDatabase::Persist(), and PVR::CPVREpgDatabase::UpdateSavedSearchLastExecuted().
GetMaximumDuration()
int PVR::CPVREpgSearchFilter::GetMaximumDuration () const inline
References m_iMaximumDuration.
Referenced by PVR::CPVREpgDatabase::Persist().
GetMinimumDuration()
int PVR::CPVREpgSearchFilter::GetMinimumDuration () const inline
References m_iMinimumDuration.
Referenced by PVR::CPVREpgDatabase::Persist().
GetPath()
std::string CPVREpgSearchFilter::GetPath () const
Return the path for this filter.
Returns
the path.
References PVR::CPVREpgSearchPath::GetPath().
GetSearchTerm()
const std::string & PVR::CPVREpgSearchFilter::GetSearchTerm () const inline
References m_searchData, and PVR::PVREpgSearchData::m_strSearchTerm.
Referenced by PVR::CPVREpgDatabase::Persist().
GetStartDateTime()
const CDateTime & PVR::CPVREpgSearchFilter::GetStartDateTime () const inline
References m_searchData, and PVR::PVREpgSearchData::m_startDateTime.
Referenced by PVR::CPVREpgDatabase::Persist().
GetTitle()
const std::string & PVR::CPVREpgSearchFilter::GetTitle () const inline
References m_title.
Referenced by PVR::CPVREpgDatabase::Delete(), and PVR::CPVREpgDatabase::Persist().
IsCaseSensitive()
bool PVR::CPVREpgSearchFilter::IsCaseSensitive () const inline
References m_bIsCaseSensitive.
Referenced by PVR::CPVREpgDatabase::Persist().
IsChanged()
bool PVR::CPVREpgSearchFilter::IsChanged () const inline
References m_bChanged.
IsEndAnyTime()
bool PVR::CPVREpgSearchFilter::IsEndAnyTime () const inline
References PVR::PVREpgSearchData::m_endAnyTime, and m_searchData.
Referenced by PVR::CPVREpgDatabase::Persist().
IsFreeToAirOnly()
bool PVR::CPVREpgSearchFilter::IsFreeToAirOnly () const inline
References m_bFreeToAirOnly.
Referenced by PVR::CPVREpgDatabase::Persist().
IsRadio()
bool PVR::CPVREpgSearchFilter::IsRadio () const inline
Get the type of channels to search.
Returns
true, if 'radio'. false, otherwise.
References m_bIsRadio.
Referenced by PVR::CPVREpgDatabase::Persist().
IsStartAnyTime()
bool PVR::CPVREpgSearchFilter::IsStartAnyTime () const inline
References m_searchData, and PVR::PVREpgSearchData::m_startAnyTime.
Referenced by PVR::CPVREpgDatabase::Persist().
MatchChannel()
bool CPVREpgSearchFilter::MatchChannel (const std::shared_ptr< const CPVREpgInfoTag > & tag) const private
References PVR::CPVRManager::Clients(), CServiceBroker::GetPVRManager(), m_bIsRadio, m_iChannelUID, m_iClientID, and PVR::PVR_CLIENT_INVALID_UID.
Referenced by FilterEntry().
MatchChannelGroup()
bool CPVREpgSearchFilter::MatchChannelGroup (const std::shared_ptr< const CPVREpgInfoTag > & tag) const private
References PVR::CPVRManager::ChannelGroups(), CServiceBroker::GetPVRManager(), m_bIsRadio, and m_iChannelGroupID.
Referenced by FilterEntry().
MatchDuration()
bool CPVREpgSearchFilter::MatchDuration (const std::shared_ptr< const CPVREpgInfoTag > & tag) const private
References PVR::EPG_SEARCH_UNSET, m_iMaximumDuration, and m_iMinimumDuration.
Referenced by FilterEntry().
MatchFreeToAir()
bool CPVREpgSearchFilter::MatchFreeToAir (const std::shared_ptr< const CPVREpgInfoTag > & tag) const private
References PVR::CPVRManager::ChannelGroups(), CServiceBroker::GetPVRManager(), and m_bFreeToAirOnly.
Referenced by FilterEntry().
MatchGenre()
bool CPVREpgSearchFilter::MatchGenre (const std::shared_ptr< const CPVREpgInfoTag > & tag) const private
References EPG_EVENT_CONTENTMASK_MOVIEDRAMA, EPG_EVENT_CONTENTMASK_USERDEFINED, PVR::EPG_SEARCH_UNSET, m_bEpgSearchDataFiltered, PVR::PVREpgSearchData::m_bIncludeUnknownGenres, PVR::PVREpgSearchData::m_iGenreType, and m_searchData.
Referenced by FilterEntry().
MatchRecordings()
bool CPVREpgSearchFilter::MatchRecordings (const std::shared_ptr< const CPVREpgInfoTag > & tag) const private
References CServiceBroker::GetPVRManager(), and m_bIgnorePresentRecordings.
Referenced by FilterEntry().
MatchSearchTerm()
bool CPVREpgSearchFilter::MatchSearchTerm (const std::shared_ptr< const CPVREpgInfoTag > & tag) const private
References CServiceBroker::GetPVRManager(), PVR::CPVRManager::IsParentalLocked(), m_bEpgSearchDataFiltered, m_bIsCaseSensitive, PVR::PVREpgSearchData::m_bSearchInDescription, m_searchData, PVR::PVREpgSearchData::m_strSearchTerm, CTextSearch::Search(), and SEARCH_DEFAULT_OR.
Referenced by FilterEntry().
MatchStartAndEndTimes()
bool CPVREpgSearchFilter::MatchStartAndEndTimes (const std::shared_ptr< const CPVREpgInfoTag > & tag) const private
References CDateTime::GetUTCDateTime(), CDateTime::IsValid(), m_bEpgSearchDataFiltered, PVR::PVREpgSearchData::m_bIgnoreFinishedBroadcasts, PVR::PVREpgSearchData::m_bIgnoreFutureBroadcasts, PVR::PVREpgSearchData::m_endDateTime, m_searchData, and PVR::PVREpgSearchData::m_startDateTime.
Referenced by FilterEntry().
MatchTimers()
bool CPVREpgSearchFilter::MatchTimers (const std::shared_ptr< const CPVREpgInfoTag > & tag) const private
References CServiceBroker::GetPVRManager(), m_bIgnorePresentTimers, and PVR::Timers.
Referenced by FilterEntry().
RemoveDuplicates()
void CPVREpgSearchFilter::RemoveDuplicates (std::vector< std::shared_ptr< CPVREpgInfoTag > > & results) static
remove duplicates from a list of epg tags.
Parameters
results The list of epg tags.
Referenced by PVR::CPVREpgSearch::Execute().
Reset()
void CPVREpgSearchFilter::Reset ()
Clear this filter.
References PVR::EPG_SEARCH_UNSET, m_bEpgSearchDataFiltered, m_bFreeToAirOnly, m_bIgnorePresentRecordings, m_bIgnorePresentTimers, m_bIsCaseSensitive, m_bRemoveDuplicates, m_iChannelGroupID, m_iChannelUID, m_iClientID, m_iDatabaseId, m_iMaximumDuration, m_iMinimumDuration, m_lastExecutedDateTime, m_searchData, m_title, PVR::PVR_CLIENT_INVALID_UID, PVR::PVREpgSearchData::Reset(), and CDateTime::SetValid().
Referenced by CPVREpgSearchFilter().
SetCaseSensitive()
void CPVREpgSearchFilter::SetCaseSensitive (bool bIsCaseSensitive)
References m_bChanged, and m_bIsCaseSensitive.
SetChanged()
void PVR::CPVREpgSearchFilter::SetChanged (bool bChanged) inline
References m_bChanged.
Referenced by PVR::CPVREpgDatabase::Persist().
SetChannelGroupID()
void CPVREpgSearchFilter::SetChannelGroupID (int iChannelGroupID)
References m_bChanged, and m_iChannelGroupID.
SetChannelUID()
void CPVREpgSearchFilter::SetChannelUID (int iChannelUID)
References m_bChanged, and m_iChannelUID.
SetClientID()
void CPVREpgSearchFilter::SetClientID (int iClientID)
References m_bChanged, and m_iClientID.
SetDatabaseId()
void CPVREpgSearchFilter::SetDatabaseId (int iDatabaseId)
References m_bChanged, and m_iDatabaseId.
Referenced by PVR::CPVREpgDatabase::Persist().
SetEndAnyTime()
void CPVREpgSearchFilter::SetEndAnyTime (bool endAnyTime)
References m_bChanged, PVR::PVREpgSearchData::m_endAnyTime, and m_searchData.
SetEndDateTime()
void CPVREpgSearchFilter::SetEndDateTime (const CDateTime & endDateTime)
References m_bChanged, PVR::PVREpgSearchData::m_endDateTime, and m_searchData.
SetEpgSearchDataFiltered()
void PVR::CPVREpgSearchFilter::SetEpgSearchDataFiltered () inline
References m_bEpgSearchDataFiltered.
Referenced by PVR::CPVREpgSearch::Execute().
SetFreeToAirOnly()
void CPVREpgSearchFilter::SetFreeToAirOnly (bool bFreeToAirOnly)
References m_bChanged, and m_bFreeToAirOnly.
SetGenreType()
void CPVREpgSearchFilter::SetGenreType (int iGenreType)
References m_bChanged, PVR::PVREpgSearchData::m_iGenreType, and m_searchData.
SetIconPath()
void CPVREpgSearchFilter::SetIconPath (const std::string & iconPath)
References m_bChanged, and m_iconPath.
SetIgnoreFinishedBroadcasts()
void CPVREpgSearchFilter::SetIgnoreFinishedBroadcasts (bool bIgnoreFinishedBroadcasts)
References m_bChanged, PVR::PVREpgSearchData::m_bIgnoreFinishedBroadcasts, and m_searchData.
SetIgnoreFutureBroadcasts()
void CPVREpgSearchFilter::SetIgnoreFutureBroadcasts (bool bIgnoreFutureBroadcasts)
References m_bChanged, PVR::PVREpgSearchData::m_bIgnoreFutureBroadcasts, and m_searchData.
SetIgnorePresentRecordings()
void CPVREpgSearchFilter::SetIgnorePresentRecordings (bool bIgnorePresentRecordings)
References m_bChanged, and m_bIgnorePresentRecordings.
SetIgnorePresentTimers()
void CPVREpgSearchFilter::SetIgnorePresentTimers (bool bIgnorePresentTimers)
References m_bChanged, and m_bIgnorePresentTimers.
SetIncludeUnknownGenres()
void CPVREpgSearchFilter::SetIncludeUnknownGenres (bool bIncludeUnknownGenres)
References m_bChanged, PVR::PVREpgSearchData::m_bIncludeUnknownGenres, and m_searchData.
SetLastExecutedDateTime()
void CPVREpgSearchFilter::SetLastExecutedDateTime (const CDateTime & lastExecutedDateTime)
References m_lastExecutedDateTime.
Referenced by PVR::CPVREpgSearch::Execute().
SetMaximumDuration()
void CPVREpgSearchFilter::SetMaximumDuration (int iMaximumDuration)
References m_bChanged, and m_iMaximumDuration.
SetMinimumDuration()
void CPVREpgSearchFilter::SetMinimumDuration (int iMinimumDuration)
References m_bChanged, and m_iMinimumDuration.
SetRemoveDuplicates()
void CPVREpgSearchFilter::SetRemoveDuplicates (bool bRemoveDuplicates)
References m_bChanged, and m_bRemoveDuplicates.
SetSearchInDescription()
void CPVREpgSearchFilter::SetSearchInDescription (bool bSearchInDescription)
References m_bChanged, PVR::PVREpgSearchData::m_bSearchInDescription, and m_searchData.
SetSearchPhrase()
void CPVREpgSearchFilter::SetSearchPhrase (const std::string & strSearchPhrase)
References SetSearchTerm().
SetSearchTerm()
void CPVREpgSearchFilter::SetSearchTerm (const std::string & strSearchTerm)
References m_bChanged, m_searchData, and PVR::PVREpgSearchData::m_strSearchTerm.
Referenced by SetSearchPhrase().
SetStartAnyTime()
void CPVREpgSearchFilter::SetStartAnyTime (bool startAnyTime)
References m_bChanged, m_searchData, and PVR::PVREpgSearchData::m_startAnyTime.
SetStartDateTime()
void CPVREpgSearchFilter::SetStartDateTime (const CDateTime & startDateTime)
References m_bChanged, m_searchData, and PVR::PVREpgSearchData::m_startDateTime.
SetTitle()
void CPVREpgSearchFilter::SetTitle (const std::string & title)
References m_bChanged, and m_title.
ShouldIgnoreFinishedBroadcasts()
bool PVR::CPVREpgSearchFilter::ShouldIgnoreFinishedBroadcasts () const inline
References PVR::PVREpgSearchData::m_bIgnoreFinishedBroadcasts, and m_searchData.
Referenced by PVR::CPVREpgDatabase::Persist().
ShouldIgnoreFutureBroadcasts()
bool PVR::CPVREpgSearchFilter::ShouldIgnoreFutureBroadcasts () const inline
References PVR::PVREpgSearchData::m_bIgnoreFutureBroadcasts, and m_searchData.
Referenced by PVR::CPVREpgDatabase::Persist().
ShouldIgnorePresentRecordings()
bool PVR::CPVREpgSearchFilter::ShouldIgnorePresentRecordings () const inline
References m_bIgnorePresentRecordings.
Referenced by PVR::CPVREpgDatabase::Persist().
ShouldIgnorePresentTimers()
bool PVR::CPVREpgSearchFilter::ShouldIgnorePresentTimers () const inline
References m_bIgnorePresentTimers.
Referenced by PVR::CPVREpgDatabase::Persist().
ShouldIncludeUnknownGenres()
bool PVR::CPVREpgSearchFilter::ShouldIncludeUnknownGenres () const inline
References PVR::PVREpgSearchData::m_bIncludeUnknownGenres, and m_searchData.
Referenced by PVR::CPVREpgDatabase::Persist().
ShouldRemoveDuplicates()
bool PVR::CPVREpgSearchFilter::ShouldRemoveDuplicates () const inline
References m_bRemoveDuplicates.
Referenced by PVR::CPVREpgSearch::Execute(), and PVR::CPVREpgDatabase::Persist().
ShouldSearchInDescription()
bool PVR::CPVREpgSearchFilter::ShouldSearchInDescription () const inline
References PVR::PVREpgSearchData::m_bSearchInDescription, and m_searchData.
Referenced by PVR::CPVREpgDatabase::Persist().
Member Data Documentation
m_bChanged
bool PVR::CPVREpgSearchFilter::m_bChanged = false private
Referenced by IsChanged(), SetCaseSensitive(), SetChanged(), SetChannelGroupID(), SetChannelUID(), SetClientID(), SetDatabaseId(), SetEndAnyTime(), SetEndDateTime(), SetFreeToAirOnly(), SetGenreType(), SetIconPath(), SetIgnoreFinishedBroadcasts(), SetIgnoreFutureBroadcasts(), SetIgnorePresentRecordings(), SetIgnorePresentTimers(), SetIncludeUnknownGenres(), SetMaximumDuration(), SetMinimumDuration(), SetRemoveDuplicates(), SetSearchInDescription(), SetSearchTerm(), SetStartAnyTime(), SetStartDateTime(), and SetTitle().
m_bEpgSearchDataFiltered
bool PVR::CPVREpgSearchFilter::m_bEpgSearchDataFiltered = false private
Referenced by MatchGenre(), MatchSearchTerm(), MatchStartAndEndTimes(), Reset(), and SetEpgSearchDataFiltered().
m_bFreeToAirOnly
bool PVR::CPVREpgSearchFilter::m_bFreeToAirOnly private
Include free to air channels only
Referenced by IsFreeToAirOnly(), MatchFreeToAir(), Reset(), and SetFreeToAirOnly().
m_bIgnorePresentRecordings
bool PVR::CPVREpgSearchFilter::m_bIgnorePresentRecordings private
True to ignore currently active recordings, false if not
Referenced by MatchRecordings(), Reset(), SetIgnorePresentRecordings(), and ShouldIgnorePresentRecordings().
m_bIgnorePresentTimers
bool PVR::CPVREpgSearchFilter::m_bIgnorePresentTimers private
True to ignore currently present timers, false if not
Referenced by MatchTimers(), Reset(), SetIgnorePresentTimers(), and ShouldIgnorePresentTimers().
m_bIsCaseSensitive
bool PVR::CPVREpgSearchFilter::m_bIsCaseSensitive private
Do a case sensitive search
Referenced by IsCaseSensitive(), MatchSearchTerm(), Reset(), and SetCaseSensitive().
m_bIsRadio
bool PVR::CPVREpgSearchFilter::m_bIsRadio private
True to filter radio channels only, false to tv only
Referenced by IsRadio(), MatchChannel(), and MatchChannelGroup().
m_bRemoveDuplicates
bool PVR::CPVREpgSearchFilter::m_bRemoveDuplicates private
True to remove duplicate events, false if not
Referenced by Reset(), SetRemoveDuplicates(), and ShouldRemoveDuplicates().
m_iChannelGroupID
int PVR::CPVREpgSearchFilter::m_iChannelGroupID {-1} private
The channel group id
Referenced by GetChannelGroupID(), MatchChannelGroup(), Reset(), and SetChannelGroupID().
m_iChannelUID
int PVR::CPVREpgSearchFilter::m_iChannelUID = -1 private
The channel uid
Referenced by GetChannelUID(), MatchChannel(), Reset(), and SetChannelUID().
m_iClientID
int PVR::CPVREpgSearchFilter::m_iClientID = PVR_CLIENT_INVALID_UID private
The client id
Referenced by GetClientID(), MatchChannel(), Reset(), and SetClientID().
m_iconPath
std::string PVR::CPVREpgSearchFilter::m_iconPath private
Referenced by GetIconPath(), and SetIconPath().
m_iDatabaseId
int PVR::CPVREpgSearchFilter::m_iDatabaseId {PVR_EPG_SEARCH_INVALID_DATABASE_ID} private
Referenced by GetDatabaseId(), Reset(), and SetDatabaseId().
m_iMaximumDuration
int PVR::CPVREpgSearchFilter::m_iMaximumDuration private
The maximum duration for an entry
Referenced by GetMaximumDuration(), MatchDuration(), Reset(), and SetMaximumDuration().
m_iMinimumDuration
int PVR::CPVREpgSearchFilter::m_iMinimumDuration private
The minimum duration for an entry
Referenced by GetMinimumDuration(), MatchDuration(), Reset(), and SetMinimumDuration().
m_lastExecutedDateTime
CDateTime PVR::CPVREpgSearchFilter::m_lastExecutedDateTime private
Referenced by GetLastExecutedDateTime(), Reset(), and SetLastExecutedDateTime().
m_searchData
PVREpgSearchData PVR::CPVREpgSearchFilter::m_searchData private
Referenced by GetEndDateTime(), GetEpgSearchData(), GetGenreType(), GetSearchTerm(), GetStartDateTime(), IsEndAnyTime(), IsStartAnyTime(), MatchGenre(), MatchSearchTerm(), MatchStartAndEndTimes(), Reset(), SetEndAnyTime(), SetEndDateTime(), SetGenreType(), SetIgnoreFinishedBroadcasts(), SetIgnoreFutureBroadcasts(), SetIncludeUnknownGenres(), SetSearchInDescription(), SetSearchTerm(), SetStartAnyTime(), SetStartDateTime(), ShouldIgnoreFinishedBroadcasts(), ShouldIgnoreFutureBroadcasts(), ShouldIncludeUnknownGenres(), and ShouldSearchInDescription().
m_title
std::string PVR::CPVREpgSearchFilter::m_title private
Referenced by GetTitle(), Reset(), and SetTitle().
The documentation for this class was generated from the following files:
EpgSearchFilter.h
EpgSearchFilter.cpp