Kodi Documentation: anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor Class Reference
anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor Class Reference
Public Member Functions
CVideoSelectActionProcessor (CGUIWindowPVRRecordingsBase &window, const std::shared_ptr< CFileItem > &item, int itemIndex)
Public Member Functions inherited from KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase
CVideoSelectActionProcessorBase (const std::shared_ptr< CFileItem > &item)
~CVideoSelectActionProcessorBase () override=default
Public Member Functions inherited from KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase
CVideoPlayActionProcessorBase (const std::shared_ptr< CFileItem > &item)
virtual ~CVideoPlayActionProcessorBase ()=default
bool ProcessDefaultAction ()
bool ProcessAction (Action action)
bool UserCancelled () const
Protected Member Functions
bool OnPlayPartSelected (unsigned int part) override
bool OnResumeSelected () override
bool OnPlaySelected () override
bool OnQueueSelected () override
bool OnInfoSelected () override
bool OnChooseSelected () override
Protected Member Functions inherited from KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase
Action GetDefaultAction () override
bool Process (Action action) override
Private Attributes
CGUIWindowPVRRecordingsBase & m_window
const int m_itemIndex {-1}
Additional Inherited Members
Static Public Member Functions inherited from KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase
static Action GetDefaultSelectAction ()
Static Public Member Functions inherited from KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase
static Action ChoosePlayOrResume (const CFileItem &item)
Protected Attributes inherited from KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase
std::shared_ptr< CFileItem > m_item
bool m_userCancelled {false}
Constructor & Destructor Documentation
CVideoSelectActionProcessor()
anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor::CVideoSelectActionProcessor (CGUIWindowPVRRecordingsBase & window, const std::shared_ptr< CFileItem > & item, int itemIndex) inline
Member Function Documentation
OnChooseSelected()
bool anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor::OnChooseSelected () inline override protected virtual
Implements KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase.
OnInfoSelected()
bool anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor::OnInfoSelected () inline override protected virtual
Implements KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase.
References PVR::CPVRManager::Get(), and CServiceBroker::GetPVRManager().
OnPlayPartSelected()
bool anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor::OnPlayPartSelected (unsigned int part) inline override protected virtual
Todo:
pvr recordings do not support video stacking (yet).
Implements KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase.
OnPlaySelected()
bool anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor::OnPlaySelected () inline override protected virtual
Implements KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase.
References PVR::CPVRManager::Get(), and CServiceBroker::GetPVRManager().
OnQueueSelected()
bool anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor::OnQueueSelected () inline override protected virtual
Implements KODI::VIDEO::GUILIB::CVideoSelectActionProcessorBase.
References KODI::VIDEO::UTILS::QueueItem().
OnResumeSelected()
bool anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor::OnResumeSelected () inline override protected virtual
Implements KODI::VIDEO::GUILIB::CVideoPlayActionProcessorBase.
References PVR::CPVRManager::Get(), and CServiceBroker::GetPVRManager().
Member Data Documentation
m_itemIndex
const int anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor::m_itemIndex {-1} private
m_window
CGUIWindowPVRRecordingsBase& anonymous_namespace{GUIWindowPVRRecordings.cpp}::CVideoSelectActionProcessor::m_window private
The documentation for this class was generated from the following file:
GUIWindowPVRRecordings.cpp