Kodi Documentation: COSXStorageProvider Class Reference
COSXStorageProvider Class Reference
#include <OSXStorageProvider.h>
Public Member Functions
COSXStorageProvider ()
~COSXStorageProvider () override=default
void Initialize () override
void Stop () override
void GetLocalDrives (std::vector< CMediaSource > &localDrives) override
void GetRemovableDrives (std::vector< CMediaSource > &removableDrives) override
std::vector< std::string > GetDiskUsage () override
bool Eject (const std::string &mountpath) override
bool PumpDriveChangeEvents (IStorageEventsCallback *callback) override
Public Member Functions inherited from IStorageProvider
virtual ~IStorageProvider ()=default
virtual std::string GetFirstOpticalDeviceFileName ()
Static Public Member Functions
static void VolumeMountNotification (const char *label, const char *mountpoint)
static void VolumeUnmountNotification (const char *label, const char *mountpoint)
Static Public Member Functions inherited from IStorageProvider
static std::unique_ptr< IStorageProvider > CreateInstance ()
Called by media manager to create platform storage provider.
Static Private Attributes
static std::vector< std::pair< std::string, std::string > > m_mountsToNotify
static std::vector< std::pair< std::string, std::string > > m_unmountsToNotify
Constructor & Destructor Documentation
COSXStorageProvider()
COSXStorageProvider::COSXStorageProvider ()
References PumpDriveChangeEvents().
~COSXStorageProvider()
COSXStorageProvider::~COSXStorageProvider () override default
Member Function Documentation
Eject()
bool COSXStorageProvider::Eject (const std::string & mountpath) override virtual
Implements IStorageProvider.
References anonymous_namespace{OSXStorageProvider.cpp}::DAOperationContext::CompletionCallback(), and success.
GetDiskUsage()
std::vector< std::string > COSXStorageProvider::GetDiskUsage (void) override virtual
Implements IStorageProvider.
GetLocalDrives()
void COSXStorageProvider::GetLocalDrives (std::vector< CMediaSource > & localDrives) override virtual
Implements IStorageProvider.
References Cocoa_GetVolumeNameFromMountPoint(), g_localizeStrings, CLocalizeStrings::Get(), CMediaSource::m_ignore, session, CMediaSource::strName, and CMediaSource::strPath.
GetRemovableDrives()
void COSXStorageProvider::GetRemovableDrives (std::vector< CMediaSource > & removableDrives) override virtual
Implements IStorageProvider.
References Cocoa_GetVolumeNameFromMountPoint(), CMediaSource::m_iDriveType, CMediaSource::m_ignore, session, CMediaSource::SOURCE_TYPE_OPTICAL_DISC, CMediaSource::SOURCE_TYPE_REMOVABLE, CMediaSource::strName, and CMediaSource::strPath.
Initialize()
void COSXStorageProvider::Initialize () inline override virtual
Implements IStorageProvider.
PumpDriveChangeEvents()
bool COSXStorageProvider::PumpDriveChangeEvents (IStorageEventsCallback * callback) override virtual
Implements IStorageProvider.
Referenced by COSXStorageProvider().
Stop()
void COSXStorageProvider::Stop () inline override virtual
Implements IStorageProvider.
VolumeMountNotification()
void COSXStorageProvider::VolumeMountNotification (const char * label, const char * mountpoint) static
References label.
VolumeUnmountNotification()
void COSXStorageProvider::VolumeUnmountNotification (const char * label, const char * mountpoint) static
References label.
Member Data Documentation
m_mountsToNotify
std::vector< std::pair< std::string, std::string > > COSXStorageProvider::m_mountsToNotify static private
m_unmountsToNotify
std::vector< std::pair< std::string, std::string > > COSXStorageProvider::m_unmountsToNotify static private
The documentation for this class was generated from the following files:
OSXStorageProvider.h
OSXStorageProvider.cpp