Kodi Documentation: CSysInfo Class Reference
CSysInfo Class Reference
#include <SystemInfo.h>
Public Types
enum WindowsVersion {
WindowsVersionUnknown = -1 , WindowsVersionWin8_1 , WindowsVersionWin10 , WindowsVersionWin10_1607 ,
WindowsVersionWin10_1703 , WindowsVersionWin10_1709 , WindowsVersionWin10_1803 , WindowsVersionWin10_1809 ,
WindowsVersionWin10_1903 , WindowsVersionWin10_1909 , WindowsVersionWin10_2004 , WindowsVersionWin10_20H2 ,
WindowsVersionWin10_21H1 , WindowsVersionWin10_21H2 , WindowsVersionWin10_22H2 , WindowsVersionWin10_Future ,
WindowsVersionWin11_21H2 , WindowsVersionWin11_22H2 , WindowsVersionWin11_Future , WindowsVersionFuture = 100
}
enum WindowsDeviceFamily {
Mobile = 1 , Desktop = 2 , IoT = 3 , Xbox = 4 ,
Surface = 5 , Other = 100
}
Public Member Functions
CSysInfo (void)
~CSysInfo () override
bool Load (const TiXmlNode *settings) override
Load settings from the given XML node.
bool Save (TiXmlNode *settings) const override
Save settings to the given XML node.
bool HasInternet ()
bool IsAeroDisabled ()
bool GetDiskSpace (std::string drive, int &iTotal, int &iTotalFree, int &iTotalUsed, int &iPercentFree, int &iPercentUsed)
std::string GetHddSpaceInfo (int &percent, int drive, bool shortText=false)
std::string GetHddSpaceInfo (int drive, bool shortText=false)
int GetTotalUptime () const
void SetTotalUptime (int uptime)
std::string GetPrivacyPolicy ()
Public Member Functions inherited from CInfoLoader
CInfoLoader (unsigned int timeToRefresh=5 *60 *1000)
~CInfoLoader () override
std::string GetInfo (int info)
void Refresh ()
Public Member Functions inherited from IJobCallback
virtual ~IJobCallback ()=default
Destructor for job call back objects.
virtual void OnJobAbort (unsigned int jobID, CJob *job)
An optional callback function used when a job will be aborted.
virtual void OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob *job)
An optional callback function that a job may call while processing.
Public Member Functions inherited from ISubSettings
virtual ~ISubSettings ()=default
virtual void Clear ()
Clear any loaded setting values.
Static Public Member Functions
static const std::string & GetAppName (void)
static std::string GetKernelName (bool emptyIfUnknown=false)
static std::string GetKernelVersionFull (void)
static std::string GetKernelVersion (void)
static std::string GetOsName (bool emptyIfUnknown=false)
static std::string GetOsVersion (void)
static std::string GetOsPrettyNameWithVersion (void)
static std::string GetUserAgent ()
static std::string GetDeviceName ()
static std::string GetVersion ()
static std::string GetVersionShort ()
static std::string GetVersionCode ()
static std::string GetVersionGit ()
static std::string GetBuildDate ()
static bool IsWindowsVersion (WindowsVersion ver)
static bool IsWindowsVersionAtLeast (WindowsVersion ver)
static WindowsVersion GetWindowsVersion ()
static int GetKernelBitness (void)
static int GetXbmcBitness (void)
static const std::string & GetKernelCpuFamily (void)
static std::string GetManufacturerName (void)
static std::string GetModelName (void)
static std::string GetBuildTargetPlatformName (void)
static std::string GetBuildTargetPlatformVersion (void)
static std::string GetBuildTargetPlatformVersionDecoded (void)
static std::string GetBuildTargetCpuFamily (void)
static std::string GetUsedCompilerNameAndVer (void)
static WindowsDeviceFamily GetWindowsDeviceFamily ()
Public Attributes
char MD5_Sign [32+1]
Protected Member Functions
CJob * GetJob () const override
std::string TranslateInfo (int info) const override
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
Protected Member Functions inherited from CInfoLoader
virtual std::string BusyInfo (int info) const
Private Member Functions
void Reset ()
Private Attributes
CSysData m_info
std::string m_privacyPolicy
int m_iSystemTimeTotalUp
Static Private Attributes
static WindowsVersion m_WinVer = WindowsVersionUnknown
Member Enumeration Documentation
WindowsDeviceFamily
enum CSysInfo::WindowsDeviceFamily
Enumerator
Mobile
Desktop
IoT
Xbox
Surface
Other
WindowsVersion
enum CSysInfo::WindowsVersion
Enumerator
WindowsVersionUnknown
WindowsVersionWin8_1
WindowsVersionWin10
WindowsVersionWin10_1607
WindowsVersionWin10_1703
WindowsVersionWin10_1709
WindowsVersionWin10_1803
WindowsVersionWin10_1809
WindowsVersionWin10_1903
WindowsVersionWin10_1909
WindowsVersionWin10_2004
WindowsVersionWin10_20H2
WindowsVersionWin10_21H1
WindowsVersionWin10_21H2
WindowsVersionWin10_22H2
WindowsVersionWin10_Future
WindowsVersionWin11_21H2
WindowsVersionWin11_22H2
WindowsVersionWin11_Future
WindowsVersionFuture
Constructor & Destructor Documentation
CSysInfo()
CSysInfo::CSysInfo (void)
References m_iSystemTimeTotalUp, and MD5_Sign.
~CSysInfo()
CSysInfo::~CSysInfo () override default
Member Function Documentation
GetAppName()
const std::string & CSysInfo::GetAppName (void) static
References CCompileInfo::GetAppName().
Referenced by anonymous_namespace{PVRGUIActionsTimers.cpp}::AddEventLogEntry(), CAppParamParser::DisplayHelp(), CAppParamParser::DisplayVersion(), GetUserAgent(), KODI::CDRIP::CEncoderFFmpeg::Init(), CApplication::Initialize(), CApplication::InitWindow(), CGUIWindowSystemInfo::OnMessage(), CFavouritesURL::Parse(), CApplication::PrintStartupLog(), KODI::CDRIP::CCDDARipJob::SetupEncoder(), and TEST_F().
GetBuildDate()
std::string CSysInfo::GetBuildDate () static
References CCompileInfo::GetBuildDate().
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), CGUIWindowSystemInfo::OnMessage(), and CApplication::PrintStartupLog().
GetBuildTargetCpuFamily()
std::string CSysInfo::GetBuildTargetCpuFamily (void) static
Referenced by GetUserAgent(), CApplication::PrintStartupLog(), TEST_F(), TEST_F(), and TEST_F().
GetBuildTargetPlatformName()
std::string CSysInfo::GetBuildTargetPlatformName (void) static
Referenced by CApplication::PrintStartupLog(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
GetBuildTargetPlatformVersion()
std::string CSysInfo::GetBuildTargetPlatformVersion (void) static
References XSTR_MACRO.
Referenced by GetBuildTargetPlatformVersionDecoded(), CApplication::PrintStartupLog(), TEST_F(), TEST_F(), and TEST_F().
GetBuildTargetPlatformVersionDecoded()
std::string CSysInfo::GetBuildTargetPlatformVersionDecoded (void) static
References GetBuildTargetPlatformVersion(), and XSTR_MACRO.
Referenced by CApplication::PrintStartupLog(), TEST_F(), and TEST_F().
GetDeviceName()
std::string CSysInfo::GetDeviceName () static
References CCompileInfo::GetAppName(), CNetworkBase::GetHostName(), CServiceBroker::GetNetwork(), CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_SERVICES_DEVICENAME.
Referenced by UPNP::CUPnP::CreateRenderer(), UPNP::CUPnP::CreateServer(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), EVENTSERVER::CEventServer::Run(), CNetworkServices::StartAirPlayServer(), CNetworkServices::StartJSONRPCServer(), CAirTunesServer::StartServer(), and CNetworkServices::StartWebserver().
GetDiskSpace()
bool CSysInfo::GetDiskSpace (std::string drive, int & iTotal, int & iTotalFree, int & iTotalUsed, int & iPercentFree, int & iPercentUsed)
References KODI::PLATFORM::FILESYSTEM::space_info::capacity, KODI::PLATFORM::FILESYSTEM::space_info::free, MB, and KODI::PLATFORM::WINDOWS::ToW().
Referenced by GetHddSpaceInfo(), and TEST_F().
GetHddSpaceInfo() [1/2]
std::string CSysInfo::GetHddSpaceInfo (int & percent, int drive, bool shortText = false)
References g_localizeStrings, g_sysinfo, CLocalizeStrings::Get(), GetDiskSpace(), SYSTEM_FREE_SPACE, SYSTEM_FREE_SPACE_PERCENT, SYSTEM_TOTAL_SPACE, SYSTEM_USED_SPACE, and SYSTEM_USED_SPACE_PERCENT.
Referenced by GetHddSpaceInfo(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetInt(), and KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel().
GetHddSpaceInfo() [2/2]
std::string CSysInfo::GetHddSpaceInfo (int drive, bool shortText = false)
References GetHddSpaceInfo().
GetJob()
CJob * CSysInfo::GetJob () const override protected virtual
Implements CInfoLoader.
GetKernelBitness()
int CSysInfo::GetKernelBitness (void) static
References GetCurrentProcess().
Referenced by CWinSystemWin32DX::InitHooks(), CApplication::PrintStartupLog(), TEST_F(), TEST_F(), and TEST_F().
GetKernelCpuFamily()
const std::string & CSysInfo::GetKernelCpuFamily (void) static
Referenced by CApplication::PrintStartupLog(), TEST_F(), TEST_F(), and TEST_F().
GetKernelName()
std::string CSysInfo::GetKernelName (bool emptyIfUnknown = false) static
References g_charsetConverter.
Referenced by CSysInfoJob::DoWork(), GetOsName(), GetOsPrettyNameWithVersion(), GetUserAgent(), CApplication::PrintStartupLog(), TEST_F(), and TEST_F().
GetKernelVersion()
std::string CSysInfo::GetKernelVersion (void) static
References GetKernelVersionFull().
Referenced by GetOsVersion(), GetUserAgent(), TEST_F(), and TEST_F().
GetKernelVersionFull()
std::string CSysInfo::GetKernelVersionFull (void) static
References end(), REG_CURRENT_VERSION, and wcstoull.
Referenced by CSysInfoJob::DoWork(), GetKernelVersion(), CApplication::PrintStartupLog(), TEST_F(), and TEST_F().
GetManufacturerName()
std::string CSysInfo::GetManufacturerName (void) static
References g_charsetConverter, CServiceBroker::GetCPUInfo(), and CDarwinUtils::GetManufacturer().
Referenced by CApplication::PrintStartupLog(), TEST_F(), and TEST_F().
GetModelName()
std::string CSysInfo::GetModelName (void) static
References g_charsetConverter, CServiceBroker::GetCPUInfo(), and CDarwinUtils::getIosPlatformString().
Referenced by GetUserAgent(), CApplication::PrintStartupLog(), TEST_F(), and TEST_F().
GetOsName()
std::string CSysInfo::GetOsName (bool emptyIfUnknown = false) static
References GetKernelName().
Referenced by GetOsPrettyNameWithVersion(), GetUserAgent(), TEST_F(), and TEST_F().
GetOsPrettyNameWithVersion()
std::string CSysInfo::GetOsPrettyNameWithVersion (void) static
References GetKernelName(), GetOsName(), GetOsVersion(), CDarwinUtils::GetOSVersionString(), GetWindowsVersion(), WindowsVersionFuture, WindowsVersionWin10, WindowsVersionWin10_1607, WindowsVersionWin10_1709, WindowsVersionWin10_1803, WindowsVersionWin10_1809, WindowsVersionWin10_1903, WindowsVersionWin10_1909, WindowsVersionWin10_2004, WindowsVersionWin10_20H2, WindowsVersionWin10_21H1, WindowsVersionWin10_21H2, WindowsVersionWin10_22H2, WindowsVersionWin10_Future, WindowsVersionWin11_21H2, WindowsVersionWin11_22H2, WindowsVersionWin11_Future, and WindowsVersionWin8_1.
Referenced by CSysInfoJob::DoWork(), CApplication::PrintStartupLog(), TEST_F(), and TEST_F().
GetOsVersion()
std::string CSysInfo::GetOsVersion (void) static
References GetKernelVersion(), and CDarwinUtils::GetVersionString().
Referenced by GetOsPrettyNameWithVersion(), GetUserAgent(), TEST_F(), TEST_F(), and TEST_F().
GetPrivacyPolicy()
std::string CSysInfo::GetPrivacyPolicy ()
References g_localizeStrings, CLocalizeStrings::Get(), and m_privacyPolicy.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel().
GetTotalUptime()
int CSysInfo::GetTotalUptime () const inline
References m_iSystemTimeTotalUp.
Referenced by CSysInfoJob::GetSystemUpTime(), and CApplication::Stop().
GetUsedCompilerNameAndVer()
std::string CSysInfo::GetUsedCompilerNameAndVer (void) static
References XSTR_MACRO.
Referenced by CApplication::PrintStartupLog(), TEST_F(), and TEST_F().
GetUserAgent()
std::string CSysInfo::GetUserAgent () static
References GetAppName(), GetBuildTargetCpuFamily(), GetCurrentProcess(), GetKernelName(), GetKernelVersion(), GetModelName(), GetOsName(), GetOsVersion(), GetVersion(), GetVersionShort(), and GetXbmcBitness().
Referenced by ADDON::Interface_Network::get_user_agent(), XBMCAddon::xbmc::getUserAgent(), CAdvancedSettings::Initialize(), TEST_F(), and TEST_F().
GetVersion()
std::string CSysInfo::GetVersion () static
References CCompileInfo::GetSCMID(), CCompileInfo::GetVersionCode(), and GetVersionShort().
Referenced by UPNP::CUPnP::CreateRenderer(), UPNP::CUPnP::CreateServer(), CAppParamParser::DisplayVersion(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), GetUserAgent(), CGUIWindowSystemInfo::OnMessage(), CApplication::PrintStartupLog(), and CDDB::Xcddb::queryCDinfo().
GetVersionCode()
std::string CSysInfo::GetVersionCode () static
References CCompileInfo::GetVersionCode().
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel().
GetVersionGit()
std::string CSysInfo::GetVersionGit () static
References CCompileInfo::GetSCMID().
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel().
GetVersionShort()
std::string CSysInfo::GetVersionShort () static
References CCompileInfo::GetMajor(), CCompileInfo::GetMinor(), and CCompileInfo::GetSuffix().
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetLabel(), GetUserAgent(), and GetVersion().
GetWindowsDeviceFamily()
CSysInfo::WindowsDeviceFamily CSysInfo::GetWindowsDeviceFamily () static
References Desktop, IoT, Mobile, Other, Surface, and Xbox.
Referenced by CWinSystemWin10::CanDoWindowed(), DX::DeviceResources::CheckDXVA2SharedDecoderSurfaces(), DX::DeviceResources::CheckNV12SharedTexturesSupport(), CAESinkWASAPI::EnumerateDevicesEx(), DX::DeviceResources::GetAdapterDesc(), CWIN32Util::GetWindowsHDRStatus(), CWinEventsWin10::InitEventHandlers(), DX::DeviceResources::IsGCNOrOlder(), CWinEventsWin10::OnBackRequested(), DXVA::CDecoder::Open(), KODI::PLATFORM::WINDOWS10::App::Run(), and DX::DeviceResources::ToggleHDR().
GetWindowsVersion()
CSysInfo::WindowsVersion CSysInfo::GetWindowsVersion () static
References m_WinVer, WindowsVersionFuture, WindowsVersionUnknown, WindowsVersionWin10, WindowsVersionWin10_1607, WindowsVersionWin10_1703, WindowsVersionWin10_1709, WindowsVersionWin10_1803, WindowsVersionWin10_1809, WindowsVersionWin10_1903, WindowsVersionWin10_1909, WindowsVersionWin10_2004, WindowsVersionWin10_20H2, WindowsVersionWin10_21H1, WindowsVersionWin10_21H2, WindowsVersionWin10_22H2, WindowsVersionWin10_Future, WindowsVersionWin11_21H2, WindowsVersionWin11_22H2, WindowsVersionWin11_Future, and WindowsVersionWin8_1.
Referenced by GetOsPrettyNameWithVersion(), IsWindowsVersion(), IsWindowsVersionAtLeast(), CWIN32Util::SetThreadName(), and TEST_F().
GetXbmcBitness()
int CSysInfo::GetXbmcBitness (void) static
Referenced by GetUserAgent(), CApplication::PrintStartupLog(), TEST_F(), TEST_F(), and TEST_F().
HasInternet()
bool CSysInfo::HasInternet ()
References CSysData::CONNECTED, CSysInfoJob::GetInternetState(), CSysData::internetState, m_info, and CSysData::UNKNOWN.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool().
IsAeroDisabled()
bool CSysInfo::IsAeroDisabled ()
Referenced by CSettings::InitializeDefaults(), CWIN32Util::PlatformSyslog(), and TEST_F().
IsWindowsVersion()
bool CSysInfo::IsWindowsVersion (WindowsVersion ver) static
References GetWindowsVersion(), and WindowsVersionUnknown.
Referenced by TEST_F(), and TEST_F().
IsWindowsVersionAtLeast()
bool CSysInfo::IsWindowsVersionAtLeast (WindowsVersion ver) static
References GetWindowsVersion(), and WindowsVersionUnknown.
Referenced by DX::DeviceResources::CheckDXVA2SharedDecoderSurfaces(), DXVA::CContext::CreateContext(), DX::DeviceResources::CreateDeviceResources(), CWinSystemWin32DX::DPIChanged(), CAESinkXAudio::EnumerateDevicesEx(), CWIN32Util::GetWindowsHDRStatus(), CAESinkWASAPI::InitializeExclusive(), CAESinkXAudio::InitializeInternal(), DX::DeviceResources::ResizeBuffers(), and TEST_F().
Load()
bool CSysInfo::Load (const TiXmlNode * settings) override virtual
Load settings from the given XML node.
Parameters
settings XML node containing setting values
Returns
True if loading the settings was successful, false otherwise.
Reimplemented from ISubSettings.
References XMLUtils::GetInt(), and m_iSystemTimeTotalUp.
OnJobComplete()
void CSysInfo::OnJobComplete (unsigned int jobID, bool success, CJob * job) override protected virtual
The callback used when a job completes.
OnJobComplete is called at the completion of the job's DoWork() function, and is used to return information to the caller on the result of the job. On returning form this function the CJobManager will destroy this job.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
success the result from the DoWork call
job the job that has been processed. The job will be destroyed after this function returns
See also
CJobManager and CJob
Reimplemented from CInfoLoader.
References m_info, CInfoLoader::OnJobComplete(), and success.
Reset()
void CSysInfo::Reset () private
References m_info, and CSysData::Reset().
Save()
bool CSysInfo::Save (TiXmlNode * settings) const override virtual
Save settings to the given XML node.
Parameters
settings XML node in which the settings will be saved
Returns
True if saving the settings was successful, false otherwise.
Reimplemented from ISubSettings.
References m_iSystemTimeTotalUp, and XMLUtils::SetInt().
SetTotalUptime()
void CSysInfo::SetTotalUptime (int uptime) inline
References m_iSystemTimeTotalUp.
Referenced by CApplication::Stop().
TranslateInfo()
std::string CSysInfo::TranslateInfo (int info) const override protected virtual
Reimplemented from CInfoLoader.
References CSysData::batteryLevel, CSysData::CONNECTED, CSysData::cpuFrequency, CSysData::dnsServers, g_localizeStrings, CSysData::gatewayAddress, CLocalizeStrings::Get(), CSysData::internetState, CSysData::ipAddress, m_info, CSysData::macAddress, CSysData::netMask, NETWORK_DNS1_ADDRESS, NETWORK_DNS2_ADDRESS, NETWORK_GATEWAY_ADDRESS, NETWORK_IP_ADDRESS, NETWORK_LINK_STATE, NETWORK_MAC_ADDRESS, NETWORK_SUBNET_MASK, CSysData::networkLinkState, CSysData::osVersionInfo, SYSTEM_BATTERY_LEVEL, SYSTEM_CPUFREQUENCY, SYSTEM_INTERNET_STATE, SYSTEM_OS_VERSION_INFO, SYSTEM_TOTALUPTIME, SYSTEM_UPTIME, SYSTEM_VIDEO_ENCODER_INFO, CSysData::systemTotalUptime, CSysData::systemUptime, and CSysData::videoEncoder.
Member Data Documentation
m_info
CSysData CSysInfo::m_info private
Referenced by HasInternet(), OnJobComplete(), Reset(), and TranslateInfo().
m_iSystemTimeTotalUp
int CSysInfo::m_iSystemTimeTotalUp private
Referenced by CSysInfo(), GetTotalUptime(), Load(), Save(), and SetTotalUptime().
m_privacyPolicy
std::string CSysInfo::m_privacyPolicy private
Referenced by GetPrivacyPolicy().
m_WinVer
CSysInfo::WindowsVersion CSysInfo::m_WinVer = WindowsVersionUnknown static private
Referenced by GetWindowsVersion().
MD5_Sign
char CSysInfo::MD5_Sign[32+1]
Referenced by CSysInfo().
The documentation for this class was generated from the following files:
SystemInfo.h
SystemInfo.cpp