Kodi Documentation: KODI::CDRIP::CEncoder Class Reference
KODI::CDRIP::CEncoder Class Reference
#include <Encoder.h>
Public Member Functions
CEncoder ()
virtual ~CEncoder ()
bool EncoderInit (const std::string &strFile, int iInChannels, int iInRate, int iInBits)
ssize_t EncoderEncode (uint8_t *pbtStream, size_t nNumBytesRead)
bool EncoderClose ()
void SetComment (const std::string &str)
void SetArtist (const std::string &str)
void SetTitle (const std::string &str)
void SetAlbum (const std::string &str)
void SetAlbumArtist (const std::string &str)
void SetGenre (const std::string &str)
void SetTrack (const std::string &str)
void SetTrackLength (int length)
void SetYear (const std::string &str)
Public Member Functions inherited from KODI::CDRIP::IEncoder
virtual ~IEncoder ()=default
virtual bool Init ()=0
virtual ssize_t Encode (uint8_t *pbtStream, size_t nNumBytesRead)=0
virtual bool Close ()=0
Protected Member Functions
virtual ssize_t Write (const uint8_t *pBuffer, size_t iBytes)
virtual ssize_t Seek (ssize_t iFilePosition, int iWhence)
Private Member Functions
bool FileCreate (const std::string &filename)
bool FileClose ()
ssize_t FileWrite (const uint8_t *pBuffer, size_t iBytes)
ssize_t FlushStream ()
Private Attributes
std::unique_ptr< XFILE::CFile > m_file
uint8_t m_btWriteBuffer [WRITEBUFFER_SIZE]
size_t m_dwWriteBufferPointer {0}
Additional Inherited Members
Public Attributes inherited from KODI::CDRIP::IEncoder
std::string m_strComment
std::string m_strArtist
std::string m_strAlbumArtist
std::string m_strTitle
std::string m_strAlbum
std::string m_strGenre
std::string m_strTrack
std::string m_strYear
std::string m_strFile
int m_iTrackLength = 0
int m_iInChannels = 0
int m_iInSampleRate = 0
int m_iInBitsPerSample = 0
Constructor & Destructor Documentation
CEncoder()
CEncoder::CEncoder () default
~CEncoder()
CEncoder::~CEncoder () virtual
References FileClose().
Member Function Documentation
EncoderClose()
bool CEncoder::EncoderClose ()
References KODI::CDRIP::IEncoder::Close(), FileClose(), and FlushStream().
EncoderEncode()
ssize_t CEncoder::EncoderEncode (uint8_t * pbtStream, size_t nNumBytesRead)
References KODI::CDRIP::IEncoder::Encode(), CLog::Log(), and LOGERROR.
EncoderInit()
bool CEncoder::EncoderInit (const std::string & strFile, int iInChannels, int iInRate, int iInBits)
References FileCreate(), KODI::CDRIP::IEncoder::Init(), CLog::Log(), LOGERROR, m_dwWriteBufferPointer, KODI::CDRIP::IEncoder::m_iInBitsPerSample, KODI::CDRIP::IEncoder::m_iInChannels, KODI::CDRIP::IEncoder::m_iInSampleRate, and KODI::CDRIP::IEncoder::m_strFile.
FileClose()
bool CEncoder::FileClose () private
References m_file.
Referenced by EncoderClose(), and ~CEncoder().
FileCreate()
bool CEncoder::FileCreate (const std::string & filename) private
References m_file.
Referenced by EncoderInit().
FileWrite()
ssize_t CEncoder::FileWrite (const uint8_t * pBuffer, size_t iBytes) private
References m_file.
Referenced by FlushStream(), and Write().
FlushStream()
ssize_t CEncoder::FlushStream () private
References FileWrite(), m_btWriteBuffer, and m_dwWriteBufferPointer.
Referenced by EncoderClose(), and Seek().
Seek()
ssize_t CEncoder::Seek (ssize_t iFilePosition, int iWhence) protected virtual
Reimplemented in KODI::CDRIP::CEncoderAddon.
References FlushStream(), and m_file.
Referenced by KODI::CDRIP::CEncoderFFmpeg::avio_seek_callback(), and KODI::CDRIP::CEncoderAddon::Seek().
SetAlbum()
void KODI::CDRIP::CEncoder::SetAlbum (const std::string & str) inline
References KODI::CDRIP::IEncoder::m_strAlbum.
SetAlbumArtist()
void KODI::CDRIP::CEncoder::SetAlbumArtist (const std::string & str) inline
References KODI::CDRIP::IEncoder::m_strAlbumArtist.
SetArtist()
void KODI::CDRIP::CEncoder::SetArtist (const std::string & str) inline
References KODI::CDRIP::IEncoder::m_strArtist.
SetComment()
void KODI::CDRIP::CEncoder::SetComment (const std::string & str) inline
References KODI::CDRIP::IEncoder::m_strComment.
SetGenre()
void KODI::CDRIP::CEncoder::SetGenre (const std::string & str) inline
References KODI::CDRIP::IEncoder::m_strGenre.
SetTitle()
void KODI::CDRIP::CEncoder::SetTitle (const std::string & str) inline
References KODI::CDRIP::IEncoder::m_strTitle.
SetTrack()
void KODI::CDRIP::CEncoder::SetTrack (const std::string & str) inline
References KODI::CDRIP::IEncoder::m_strTrack.
SetTrackLength()
void KODI::CDRIP::CEncoder::SetTrackLength (int length) inline
References KODI::CDRIP::IEncoder::m_iTrackLength.
SetYear()
void KODI::CDRIP::CEncoder::SetYear (const std::string & str) inline
References KODI::CDRIP::IEncoder::m_strYear.
Write()
ssize_t CEncoder::Write (const uint8_t * pBuffer, size_t iBytes) protected virtual
Reimplemented in KODI::CDRIP::CEncoderAddon.
References FileWrite(), m_btWriteBuffer, m_dwWriteBufferPointer, and KODI::CDRIP::WRITEBUFFER_SIZE.
Referenced by KODI::CDRIP::CEncoderFFmpeg::avio_write_callback(), and KODI::CDRIP::CEncoderAddon::Write().
Member Data Documentation
m_btWriteBuffer
uint8_t KODI::CDRIP::CEncoder::m_btWriteBuffer[WRITEBUFFER_SIZE] private
Referenced by FlushStream(), and Write().
m_dwWriteBufferPointer
size_t KODI::CDRIP::CEncoder::m_dwWriteBufferPointer {0} private
Referenced by EncoderInit(), FlushStream(), and Write().
m_file
std::unique_ptr<XFILE::CFile> KODI::CDRIP::CEncoder::m_file private
Referenced by FileClose(), FileCreate(), FileWrite(), and Seek().
The documentation for this class was generated from the following files:
Encoder.h
Encoder.cpp