Kodi Documentation: CWinRtUtil Class Reference
CWinRtUtil Class Reference
#include <WinRtUtil.h>
Static Public Member Functions
static HDR_STATUS GetWindowsHDRStatus ()
static HDR_STATUS GetWindowsHDRStatusUWP ()
Private Member Functions
CWinRtUtil ()=default
~CWinRtUtil ()=default
Constructor & Destructor Documentation
CWinRtUtil()
CWinRtUtil::CWinRtUtil () private default
~CWinRtUtil()
CWinRtUtil::~CWinRtUtil () private default
Member Function Documentation
GetWindowsHDRStatus()
HDR_STATUS CWinRtUtil::GetWindowsHDRStatus () static
References FAILED, CWIN32Util::FormatHRESULT(), g_hWnd, GetLastError(), HDR_OFF, HDR_ON, HDR_UNKNOWN, HDR_UNSUPPORTED, LogAdvancedColorInfo(), and LOGERROR.
Referenced by CWIN32Util::GetWindowsHDRStatus().
GetWindowsHDRStatusUWP()
HDR_STATUS CWinRtUtil::GetWindowsHDRStatusUWP () static
References HDR_OFF, HDR_ON, HDR_UNKNOWN, HDR_UNSUPPORTED, and LOGERROR.
Referenced by CWIN32Util::GetWindowsHDRStatus().
The documentation for this class was generated from the following files:
WinRtUtil.h
WinRtUtil.cpp