Kodi Documentation: CZeroconfAvahi Class Reference
CZeroconfAvahi Class Reference
#include <ZeroconfAvahi.h>
Classes
struct ServiceInfo
helper to store information on howto create an avahi-group to publish
Public Member Functions
CZeroconfAvahi ()
~CZeroconfAvahi () override
Public Member Functions inherited from CZeroconf
bool PublishService (const std::string &fcr_identifier, const std::string &fcr_type, const std::string &fcr_name, unsigned int f_port, std::vector< std::pair< std::string, std::string > > txt)
bool ForceReAnnounceService (const std::string &fcr_identifier)
bool RemoveService (const std::string &fcr_identifier)
bool HasService (const std::string &fcr_identifier) const
returns true if fcr_identifier exists
bool Start ()
void Stop ()
virtual void ProcessResults ()
bool IsStarted ()
Protected Member Functions
bool doPublishService (const std::string &fcr_identifier, const std::string &fcr_type, const std::string &fcr_name, unsigned int f_port, const std::vector< std::pair< std::string, std::string > > &txt) override
bool doForceReAnnounceService (const std::string &fcr_identifier) override
bool doRemoveService (const std::string &fcr_ident) override
void doStop () override
Protected Member Functions inherited from CZeroconf
virtual bool IsZCdaemonRunning ()
CZeroconf ()
CZeroconf (const CZeroconf &)
virtual ~CZeroconf ()
Private Types
typedef std::map< std::string, std::shared_ptr< ServiceInfo > > tServiceMap
Private Member Functions
bool createClient ()
void updateServices (AvahiClient *fp_client)
void addService (const tServiceMap::mapped_type &fp_service_info, AvahiClient *fp_client)
Static Private Member Functions
static void clientCallback (AvahiClient *fp_client, AvahiClientState f_state, void *)
this is where the client calls us if state changes
static void groupCallback (AvahiEntryGroup *fp_group, AvahiEntryGroupState f_state, void *)
here we get notified of group changes
static void shutdownCallback (AvahiTimeout *fp_e, void *)
Private Attributes
AvahiClient * mp_client = 0
AvahiThreadedPoll * mp_poll = 0
tServiceMap m_services
bool m_shutdown = false
pthread_t m_thread_id = 0
Additional Inherited Members
Static Public Member Functions inherited from CZeroconf
static CZeroconf * GetInstance ()
static void ReleaseInstance ()
static bool IsInstantiated ()
Member Typedef Documentation
tServiceMap
typedef std::map<std::string, std::shared_ptr<ServiceInfo> > CZeroconfAvahi::tServiceMap private
Constructor & Destructor Documentation
CZeroconfAvahi()
CZeroconfAvahi::CZeroconfAvahi ()
Todo:
throw exception?
References createClient(), CLog::Log(), LOGERROR, and mp_poll.
~CZeroconfAvahi()
CZeroconfAvahi::~CZeroconfAvahi () override
Todo:
does tv survive the thread?
References CLog::Log(), LOGDEBUG, m_shutdown, m_thread_id, mp_client, mp_poll, and shutdownCallback().
Member Function Documentation
addService()
void CZeroconfAvahi::addService (const tServiceMap::mapped_type & fp_service_info, AvahiClient * fp_client) private
Todo:
what now? reset the group? free it?
References addService(), groupCallback(), CLog::Log(), LOGDEBUG, LOGERROR, and LOGINFO.
Referenced by addService(), doPublishService(), groupCallback(), and updateServices().
clientCallback()
void CZeroconfAvahi::clientCallback (AvahiClient * fp_client, AvahiClientState f_state, void * fp_data) static private
this is where the client calls us if state changes
References createClient(), CLog::Log(), LOGDEBUG, LOGINFO, m_services, m_shutdown, m_thread_id, mp_client, mp_poll, and updateServices().
Referenced by createClient().
createClient()
bool CZeroconfAvahi::createClient () private
creates the avahi client;
Returns
true on success
References clientCallback(), CLog::Log(), LOGERROR, mp_client, and mp_poll.
Referenced by clientCallback(), and CZeroconfAvahi().
doForceReAnnounceService()
bool CZeroconfAvahi::doForceReAnnounceService (const std::string & fcr_identifier) override protected virtual
Implements CZeroconf.
References m_services, and mp_poll.
doPublishService()
bool CZeroconfAvahi::doPublishService (const std::string & fcr_identifier, const std::string & fcr_type, const std::string & fcr_name, unsigned int f_port, const std::vector< std::pair< std::string, std::string > > & txt) override protected virtual
Implements CZeroconf.
References addService(), CLog::Log(), LOGDEBUG, m_services, mp_client, and mp_poll.
doRemoveService()
bool CZeroconfAvahi::doRemoveService (const std::string & fcr_ident) override protected virtual
Implements CZeroconf.
References CLog::Log(), LOGDEBUG, m_services, and mp_poll.
doStop()
void CZeroconfAvahi::doStop () override protected virtual
Implements CZeroconf.
References m_services, and mp_poll.
groupCallback()
void CZeroconfAvahi::groupCallback (AvahiEntryGroup * fp_group, AvahiEntryGroupState f_state, void * fp_data) static private
here we get notified of group changes
References addService(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_services, m_shutdown, m_thread_id, mp_client, and mp_poll.
Referenced by addService().
shutdownCallback()
void CZeroconfAvahi::shutdownCallback (AvahiTimeout * fp_e, void * fp_data) static private
References m_shutdown, and mp_poll.
Referenced by ~CZeroconfAvahi().
updateServices()
void CZeroconfAvahi::updateServices (AvahiClient * fp_client) private
References addService(), and m_services.
Referenced by clientCallback().
Member Data Documentation
m_services
tServiceMap CZeroconfAvahi::m_services private
Referenced by clientCallback(), doForceReAnnounceService(), doPublishService(), doRemoveService(), doStop(), groupCallback(), and updateServices().
m_shutdown
bool CZeroconfAvahi::m_shutdown = false private
Referenced by clientCallback(), groupCallback(), shutdownCallback(), and ~CZeroconfAvahi().
m_thread_id
pthread_t CZeroconfAvahi::m_thread_id = 0 private
Referenced by clientCallback(), groupCallback(), and ~CZeroconfAvahi().
mp_client
AvahiClient* CZeroconfAvahi::mp_client = 0 private
Referenced by clientCallback(), createClient(), doPublishService(), groupCallback(), and ~CZeroconfAvahi().
mp_poll
AvahiThreadedPoll* CZeroconfAvahi::mp_poll = 0 private
Referenced by clientCallback(), createClient(), CZeroconfAvahi(), doForceReAnnounceService(), doPublishService(), doRemoveService(), doStop(), groupCallback(), shutdownCallback(), and ~CZeroconfAvahi().
The documentation for this class was generated from the following files:
ZeroconfAvahi.h
ZeroconfAvahi.cpp