Kodi Documentation: jni::CJNIXBMCMainView Class Reference
jni::CJNIXBMCMainView Class Reference
#include <JNIXBMCMainView.h>
Public Member Functions
CJNIXBMCMainView (CJNISurfaceHolderCallback *callback)
~CJNIXBMCMainView () override=default
void surfaceChanged (CJNISurfaceHolder holder, int format, int width, int height) override
void surfaceCreated (CJNISurfaceHolder holder) override
void surfaceDestroyed (CJNISurfaceHolder holder) override
void attach (const jobject &thiz)
bool waitForSurface (unsigned int millis)
bool isActive ()
CJNISurface getSurface ()
bool isCreated () const
Static Public Member Functions
static void RegisterNatives (JNIEnv *env)
Static Protected Member Functions
static void _attach (JNIEnv *env, jobject thiz)
static void _surfaceChanged (JNIEnv *env, jobject thiz, jobject holder, jint format, jint width, jint height)
static void _surfaceCreated (JNIEnv *env, jobject thiz, jobject holder)
static void _surfaceDestroyed (JNIEnv *env, jobject thiz, jobject holder)
Protected Attributes
CJNISurfaceHolderCallback * m_callback
Static Protected Attributes
static CJNIXBMCMainView * m_instance = nullptr
static CEvent m_surfaceCreated
Constructor & Destructor Documentation
CJNIXBMCMainView()
CJNIXBMCMainView::CJNIXBMCMainView (CJNISurfaceHolderCallback * callback)
References m_instance.
~CJNIXBMCMainView()
jni::CJNIXBMCMainView::~CJNIXBMCMainView () override default
Member Function Documentation
_attach()
void CJNIXBMCMainView::_attach (JNIEnv * env, jobject thiz) static protected
References attach(), m_instance, and void().
Referenced by RegisterNatives().
_surfaceChanged()
void CJNIXBMCMainView::_surfaceChanged (JNIEnv * env, jobject thiz, jobject holder, jint format, jint width, jint height) static protected
References m_instance, surfaceChanged(), and void().
Referenced by RegisterNatives().
_surfaceCreated()
void CJNIXBMCMainView::_surfaceCreated (JNIEnv * env, jobject thiz, jobject holder) static protected
References m_instance, surfaceCreated(), and void().
Referenced by RegisterNatives().
_surfaceDestroyed()
void CJNIXBMCMainView::_surfaceDestroyed (JNIEnv * env, jobject thiz, jobject holder) static protected
References m_instance, surfaceDestroyed(), and void().
Referenced by RegisterNatives().
attach()
void CJNIXBMCMainView::attach (const jobject & thiz)
Referenced by _attach().
getSurface()
CJNISurface jni::CJNIXBMCMainView::getSurface ()
isActive()
bool jni::CJNIXBMCMainView::isActive () inline
References m_surfaceCreated, and CEvent::Signaled().
isCreated()
bool CJNIXBMCMainView::isCreated () const
RegisterNatives()
void CJNIXBMCMainView::RegisterNatives (JNIEnv * env) static
References _attach(), _surfaceChanged(), _surfaceCreated(), _surfaceDestroyed(), RegisterNatives(), and s_className.
Referenced by JNI_OnLoad(), and RegisterNatives().
surfaceChanged()
void CJNIXBMCMainView::surfaceChanged (CJNISurfaceHolder holder, int format, int width, int height) override
References m_callback.
Referenced by _surfaceChanged().
surfaceCreated()
void CJNIXBMCMainView::surfaceCreated (CJNISurfaceHolder holder) override
References m_callback, m_surfaceCreated, and CEvent::Set().
Referenced by _surfaceCreated().
surfaceDestroyed()
void CJNIXBMCMainView::surfaceDestroyed (CJNISurfaceHolder holder) override
References m_callback, m_surfaceCreated, and CEvent::Reset().
Referenced by _surfaceDestroyed().
waitForSurface()
bool CJNIXBMCMainView::waitForSurface (unsigned int millis)
References m_surfaceCreated, and CEvent::Wait().
Member Data Documentation
m_callback
CJNISurfaceHolderCallback* jni::CJNIXBMCMainView::m_callback protected
Referenced by surfaceChanged(), surfaceCreated(), and surfaceDestroyed().
m_instance
CJNIXBMCMainView * CJNIXBMCMainView::m_instance = nullptr static protected
Referenced by _attach(), _surfaceChanged(), _surfaceCreated(), _surfaceDestroyed(), and CJNIXBMCMainView().
m_surfaceCreated
CEvent CJNIXBMCMainView::m_surfaceCreated static protected
Referenced by isActive(), surfaceCreated(), surfaceDestroyed(), and waitForSurface().
The documentation for this class was generated from the following files:
JNIXBMCMainView.h
JNIXBMCMainView.cpp