Kodi Documentation: CUDevProvider Class Reference
CUDevProvider Class Reference
#include <UDevProvider.h>
Public Member Functions
CUDevProvider ()
~CUDevProvider () override=default
void Initialize () override
void Stop () override
void GetLocalDrives (std::vector< CMediaSource > &localDrives) override
void GetRemovableDrives (std::vector< CMediaSource > &removableDrives) override
bool Eject (const std::string &mountpath) override
std::vector< std::string > GetDiskUsage () override
bool PumpDriveChangeEvents (IStorageEventsCallback *callback) override
Public Member Functions inherited from IStorageProvider
virtual ~IStorageProvider ()=default
virtual std::string GetFirstOpticalDeviceFileName ()
Private Member Functions
void GetDisks (std::vector< CMediaSource > &devices, bool removable)
Private Attributes
struct udev * m_udev
struct udev_monitor * m_udevMon
Additional Inherited Members
Static Public Member Functions inherited from IStorageProvider
static std::unique_ptr< IStorageProvider > CreateInstance ()
Called by media manager to create platform storage provider.
Constructor & Destructor Documentation
CUDevProvider()
CUDevProvider::CUDevProvider ()
References m_udev, and m_udevMon.
~CUDevProvider()
CUDevProvider::~CUDevProvider () override default
Member Function Documentation
Eject()
bool CUDevProvider::Eject (const std::string & mountpath) override virtual
Implements IStorageProvider.
GetDisks()
void CUDevProvider::GetDisks (std::vector< CMediaSource > & devices, bool removable) private
References URIUtils::GetFileName(), label, CMediaSource::m_iDriveType, CMediaSource::m_ignore, m_udev, name, CMediaSource::SOURCE_TYPE_LOCAL, CMediaSource::SOURCE_TYPE_OPTICAL_DISC, CMediaSource::SOURCE_TYPE_REMOVABLE, CMediaSource::strName, and CMediaSource::strPath.
Referenced by GetLocalDrives(), and GetRemovableDrives().
GetDiskUsage()
std::vector< std::string > CUDevProvider::GetDiskUsage (void) override virtual
Implements IStorageProvider.
References CPosixMountProvider::GetDiskUsage().
GetLocalDrives()
void CUDevProvider::GetLocalDrives (std::vector< CMediaSource > & localDrives) override virtual
Implements IStorageProvider.
References GetDisks().
GetRemovableDrives()
void CUDevProvider::GetRemovableDrives (std::vector< CMediaSource > & removableDrives) override virtual
Implements IStorageProvider.
References GetDisks().
Initialize()
void CUDevProvider::Initialize () override virtual
Implements IStorageProvider.
References CLog::Log(), LOGDEBUG, LOGERROR, m_udev, m_udevMon, and PumpDriveChangeEvents().
PumpDriveChangeEvents()
bool CUDevProvider::PumpDriveChangeEvents (IStorageEventsCallback * callback) override virtual
Implements IStorageProvider.
References URIUtils::GetFileName(), MEDIA_DETECT::STORAGE::StorageDevice::label, CLog::Log(), LOGINFO, m_udevMon, MEDIA_DETECT::STORAGE::OPTICAL, MEDIA_DETECT::STORAGE::StorageDevice::path, MEDIA_DETECT::STORAGE::StorageDevice::type, and MEDIA_DETECT::STORAGE::UNKNOWN.
Referenced by Initialize().
Stop()
void CUDevProvider::Stop () override virtual
Implements IStorageProvider.
References m_udev, and m_udevMon.
Member Data Documentation
m_udev
struct udev* CUDevProvider::m_udev private
Referenced by CUDevProvider(), GetDisks(), Initialize(), and Stop().
m_udevMon
struct udev_monitor* CUDevProvider::m_udevMon private
Referenced by CUDevProvider(), Initialize(), PumpDriveChangeEvents(), and Stop().
The documentation for this class was generated from the following files:
UDevProvider.h
UDevProvider.cpp