Kodi Documentation: CProfile Class Reference
CProfile Class Reference
#include <Profile.h>
Classes
class CLock
Class for handling lock status.
Public Member Functions
CProfile (const std::string &directory="", const std::string &name="", const int id=-1)
~CProfile (void)
void Load (const TiXmlNode *node, int nextIdProfile)
void Save (TiXmlNode *root) const
const std::string & getDate () const
int getId () const
const std::string & getName () const
const std::string & getDirectory () const
const std::string & getThumb () const
const std::string & getLockCode () const
LockType getLockMode () const
bool hasDatabases () const
bool canWriteDatabases () const
bool hasSources () const
bool canWriteSources () const
bool hasAddons () const
LOCK_LEVEL::SETTINGS_LOCK settingsLockLevel () const
Returns which settings levels are locked for the current profile.
bool addonmanagerLocked () const
bool musicLocked () const
bool videoLocked () const
bool picturesLocked () const
bool filesLocked () const
bool programsLocked () const
bool gamesLocked () const
const CLock & GetLocks () const
void setName (const std::string &name)
void setDirectory (const std::string &directory)
void setDate (const std::string &strDate)
void setDate ()
void setThumb (const std::string &thumb)
void setDatabases (bool bHas)
void setWriteDatabases (bool bCan)
void setSources (bool bHas)
void setWriteSources (bool bCan)
void SetLocks (const CLock &locks)
Private Attributes
std::string m_directory
int m_id
std::string m_name
std::string m_date
std::string m_thumb
bool m_bDatabases
bool m_bCanWrite
bool m_bSources
bool m_bCanWriteSources
bool m_bAddons
CLock m_locks
Constructor & Destructor Documentation
CProfile()
CProfile::CProfile (const std::string & directory = "", const std::string & name = "", const int id = -1)
References id, m_bAddons, m_bCanWrite, m_bCanWriteSources, m_bDatabases, m_bSources, and m_id.
~CProfile()
CProfile::~CProfile (void) default
Member Function Documentation
addonmanagerLocked()
bool CProfile::addonmanagerLocked () const inline
References CProfile::CLock::addonManager, and m_locks.
Referenced by anonymous_namespace{SettingConditions.cpp}::ProfileHasAddonManagerLocked().
canWriteDatabases()
bool CProfile::canWriteDatabases () const inline
References m_bCanWrite.
Referenced by anonymous_namespace{SettingConditions.cpp}::ProfileCanWriteDatabase(), and CGUIDialogProfileSettings::ShowForProfile().
canWriteSources()
bool CProfile::canWriteSources () const inline
References m_bCanWriteSources.
Referenced by anonymous_namespace{SettingConditions.cpp}::ProfileCanWriteSources(), and CGUIDialogProfileSettings::ShowForProfile().
filesLocked()
bool CProfile::filesLocked () const inline
References CProfile::CLock::files, and m_locks.
Referenced by anonymous_namespace{SettingConditions.cpp}::ProfileHasFilesLocked().
gamesLocked()
bool CProfile::gamesLocked () const inline
References CProfile::CLock::games, and m_locks.
getDate()
const std::string & CProfile::getDate () const inline
References m_date.
Referenced by CGUIPassword::IsProfileLockUnlocked(), CGUIWindowSettingsProfile::LoadList(), and CGUIWindowLoginScreen::Update().
getDirectory()
const std::string & CProfile::getDirectory () const inline
References m_directory.
Referenced by CProfileManager::DeleteProfile(), CProfileManager::GetUserDataFolder(), and CGUIDialogProfileSettings::ShowForProfile().
getId()
int CProfile::getId () const inline
References m_id.
Referenced by CProfileManager::AddProfile(), and CProfileManager::GetCurrentProfileId().
getLockCode()
const std::string & CProfile::getLockCode () const inline
References CProfile::CLock::code, and m_locks.
Referenced by CGUIPassword::IsProfileLockUnlocked(), and JSONRPC::CProfilesOperations::LoadProfile().
getLockMode()
LockType CProfile::getLockMode () const inline
References m_locks, and CProfile::CLock::mode.
Referenced by CGUIWindowSettingsProfile::GetAutoLoginProfileChoice(), JSONRPC::CProfilesOperations::GetCurrentProfile(), XFILE::CSourcesDirectory::GetDirectory(), CVideoDatabase::GetEpisodesByName(), CVideoDatabase::GetEpisodesByPlot(), CVideoDatabase::GetEpisodesByWhere(), CVideoDatabase::GetMatchingMusicVideo(), CVideoDatabase::GetMovieActorsByName(), CVideoDatabase::GetMovieCountriesByName(), CVideoDatabase::GetMovieDirectorsByName(), CVideoDatabase::GetMovieGenresByName(), CVideoDatabase::GetMoviesByName(), CVideoDatabase::GetMoviesByPlot(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideoAlbumsByName(), CVideoDatabase::GetMusicVideoArtistsByName(), CVideoDatabase::GetMusicVideoDirectorsByName(), CVideoDatabase::GetMusicVideoGenresByName(), CVideoDatabase::GetMusicVideosByAlbum(), CVideoDatabase::GetMusicVideosByName(), CVideoDatabase::GetMusicVideosByWhere(), CVideoDatabase::GetNavCommon(), CVideoDatabase::GetPeopleNav(), JSONRPC::CProfilesOperations::GetProfiles(), CVideoDatabase::GetSeasonsByWhere(), CVideoDatabase::GetTvShowGenresByName(), CVideoDatabase::GetTvShowsActorsByName(), CVideoDatabase::GetTvShowsByName(), CVideoDatabase::GetTvShowsByWhere(), CVideoDatabase::GetTvShowsDirectorsByName(), CVideoDatabase::GetYearsNav(), CGUIPassword::IsProfileLockUnlocked(), CGUIWindowSettingsProfile::LoadList(), JSONRPC::CProfilesOperations::LoadProfile(), and anonymous_namespace{SettingConditions.cpp}::ProfileLockMode().
GetLocks()
const CLock & CProfile::GetLocks () const inline
References m_locks.
Referenced by CGUIPassword::SetMasterLockMode(), and CGUIDialogProfileSettings::ShowForProfile().
getName()
const std::string & CProfile::getName () const inline
References m_name.
Referenced by CProfileManager::DeleteProfile(), CGUIWindowSettingsProfile::GetAutoLoginProfileChoice(), JSONRPC::CProfilesOperations::GetCurrentProfile(), CProfileManager::GetProfileName(), JSONRPC::CProfilesOperations::GetProfiles(), CGUIWindowSettingsProfile::LoadList(), CGUIDialogProfileSettings::ShowForProfile(), and CGUIWindowLoginScreen::Update().
getThumb()
const std::string & CProfile::getThumb () const inline
References m_thumb.
Referenced by CGUIWindowSettingsProfile::GetAutoLoginProfileChoice(), JSONRPC::CProfilesOperations::GetCurrentProfile(), JSONRPC::CProfilesOperations::GetProfiles(), CGUIWindowSettingsProfile::LoadList(), CGUIDialogProfileSettings::ShowForProfile(), and CGUIWindowLoginScreen::Update().
hasAddons()
bool CProfile::hasAddons () const inline
References m_bAddons.
Referenced by anonymous_namespace{SettingConditions.cpp}::ProfileHasAddons().
hasDatabases()
bool CProfile::hasDatabases () const inline
References m_bDatabases.
Referenced by anonymous_namespace{SettingConditions.cpp}::ProfileHasDatabase(), and CGUIDialogProfileSettings::ShowForProfile().
hasSources()
bool CProfile::hasSources () const inline
References m_bSources.
Referenced by anonymous_namespace{SettingConditions.cpp}::ProfileHasSources(), and CGUIDialogProfileSettings::ShowForProfile().
Load()
void CProfile::Load (const TiXmlNode * node, int nextIdProfile)
References CProfile::CLock::addonManager, CProfile::CLock::code, CProfile::CLock::files, CProfile::CLock::games, XMLUtils::GetBoolean(), XMLUtils::GetInt(), XMLUtils::GetPath(), XMLUtils::GetString(), LOCK_MODE_EVERYONE, LOCK_MODE_QWERTY, m_bCanWrite, m_bCanWriteSources, m_bDatabases, m_bSources, m_date, m_directory, m_id, m_locks, m_name, m_thumb, CProfile::CLock::mode, CProfile::CLock::music, node, CProfile::CLock::pictures, CProfile::CLock::programs, CProfile::CLock::settings, and CProfile::CLock::video.
Referenced by CProfileManager::Load().
musicLocked()
bool CProfile::musicLocked () const inline
References m_locks, and CProfile::CLock::music.
Referenced by anonymous_namespace{SettingConditions.cpp}::ProfileHasMusicLocked().
picturesLocked()
bool CProfile::picturesLocked () const inline
References m_locks, and CProfile::CLock::pictures.
Referenced by anonymous_namespace{SettingConditions.cpp}::ProfileHasPicturesLocked().
programsLocked()
bool CProfile::programsLocked () const inline
References m_locks, and CProfile::CLock::programs.
Referenced by anonymous_namespace{SettingConditions.cpp}::ProfileHasProgramsLocked().
Save()
void CProfile::Save (TiXmlNode * root) const
References CProfile::CLock::addonManager, CProfile::CLock::code, CProfile::CLock::files, CProfile::CLock::games, m_bCanWrite, m_bCanWriteSources, m_bDatabases, m_bSources, m_date, m_directory, m_id, m_locks, m_name, m_thumb, CProfile::CLock::mode, CProfile::CLock::music, node, CProfile::CLock::pictures, CProfile::CLock::programs, root, XMLUtils::SetBoolean(), XMLUtils::SetInt(), XMLUtils::SetPath(), XMLUtils::SetString(), CProfile::CLock::settings, and CProfile::CLock::video.
setDatabases()
void CProfile::setDatabases (bool bHas) inline
References m_bDatabases.
Referenced by CGUIDialogProfileSettings::ShowForProfile().
setDate() [1/2]
void CProfile::setDate ()
References CDateTime::GetAsLocalizedDate(), CDateTime::GetAsLocalizedTime(), CDateTime::GetCurrentDateTime(), setDate(), and TIME_FORMAT_GUESS.
Referenced by setDate().
setDate() [2/2]
void CProfile::setDate (const std::string & strDate) inline
References m_date.
setDirectory()
void CProfile::setDirectory (const std::string & directory) inline
References m_directory.
Referenced by CGUIDialogProfileSettings::ShowForProfile().
SetLocks()
void CProfile::SetLocks (const CLock & locks)
References m_locks, and CProfile::CLock::Validate().
Referenced by CGUIPassword::SetMasterLockMode(), and CGUIDialogProfileSettings::ShowForProfile().
setName()
void CProfile::setName (const std::string & name) inline
References m_name, and name.
Referenced by CGUIDialogProfileSettings::ShowForProfile().
setSources()
void CProfile::setSources (bool bHas) inline
References m_bSources.
Referenced by CGUIDialogProfileSettings::ShowForProfile().
setThumb()
void CProfile::setThumb (const std::string & thumb) inline
References m_thumb.
Referenced by CGUIDialogProfileSettings::ShowForProfile().
settingsLockLevel()
LOCK_LEVEL::SETTINGS_LOCK CProfile::settingsLockLevel () const inline
Returns which settings levels are locked for the current profile.
See also
LOCK_LEVEL::SETTINGS_LOCK
References m_locks, and CProfile::CLock::settings.
Referenced by anonymous_namespace{SettingConditions.cpp}::ProfileHasSettingsLocked().
setWriteDatabases()
void CProfile::setWriteDatabases (bool bCan) inline
References m_bCanWrite.
Referenced by CGUIDialogProfileSettings::ShowForProfile().
setWriteSources()
void CProfile::setWriteSources (bool bCan) inline
References m_bCanWriteSources.
Referenced by CGUIDialogProfileSettings::ShowForProfile().
videoLocked()
bool CProfile::videoLocked () const inline
References m_locks, and CProfile::CLock::video.
Referenced by anonymous_namespace{SettingConditions.cpp}::ProfileHasVideosLocked().
Member Data Documentation
m_bAddons
bool CProfile::m_bAddons private
Referenced by CProfile(), and hasAddons().
m_bCanWrite
bool CProfile::m_bCanWrite private
Referenced by canWriteDatabases(), CProfile(), Load(), Save(), and setWriteDatabases().
m_bCanWriteSources
bool CProfile::m_bCanWriteSources private
Referenced by canWriteSources(), CProfile(), Load(), Save(), and setWriteSources().
m_bDatabases
bool CProfile::m_bDatabases private
Referenced by CProfile(), hasDatabases(), Load(), Save(), and setDatabases().
m_bSources
bool CProfile::m_bSources private
Referenced by CProfile(), hasSources(), Load(), Save(), and setSources().
m_date
std::string CProfile::m_date private
Referenced by getDate(), Load(), Save(), and setDate().
m_directory
std::string CProfile::m_directory private
Referenced by getDirectory(), Load(), Save(), and setDirectory().
m_id
int CProfile::m_id private
Referenced by CProfile(), getId(), Load(), and Save().
m_locks
CLock CProfile::m_locks private
Referenced by addonmanagerLocked(), filesLocked(), gamesLocked(), getLockCode(), getLockMode(), GetLocks(), Load(), musicLocked(), picturesLocked(), programsLocked(), Save(), SetLocks(), settingsLockLevel(), and videoLocked().
m_name
std::string CProfile::m_name private
Referenced by getName(), Load(), Save(), and setName().
m_thumb
std::string CProfile::m_thumb private
Referenced by getThumb(), Load(), Save(), and setThumb().
The documentation for this class was generated from the following files:
Profile.h
Profile.cpp