Kodi Documentation: KODI::WINDOWING::GBM::CWinSystemGbmGLESContext Class Reference
KODI::WINDOWING::GBM::CWinSystemGbmGLESContext Class Reference
#include <WinSystemGbmGLESContext.h>
Public Member Functions
CWinSystemGbmGLESContext ()
~CWinSystemGbmGLESContext () override=default
CRenderSystemBase * GetRenderSystem () override
bool InitWindowSystem () override
bool SetFullScreen (bool fullScreen, RESOLUTION_INFO &res, bool blankOtherDisplays) override
void PresentRender (bool rendered, bool videoLayer) override
Public Member Functions inherited from KODI::WINDOWING::GBM::CWinSystemGbmEGLContext
~CWinSystemGbmEGLContext () override=default
bool DestroyWindowSystem () override
bool CreateNewWindow (const std::string &name, bool fullScreen, RESOLUTION_INFO &res) override
bool DestroyWindow () override
bool BindTextureUploadContext () override
Binds a shared context to the current thread, in order to upload textures asynchronously.
bool UnbindTextureUploadContext () override
Unbinds the shared context.
bool HasContext () override
Checks if a graphics context is already bound to the current thread.
Public Member Functions inherited from KODI::WINDOWING::LINUX::CWinSystemEGL
CWinSystemEGL (EGLenum platform, std::string const &platformExtension)
~CWinSystemEGL ()=default
EGLDisplay GetEGLDisplay () const
EGLSurface GetEGLSurface () const
EGLContext GetEGLContext () const
EGLConfig GetEGLConfig () const
Public Member Functions inherited from KODI::WINDOWING::GBM::CWinSystemGbm
CWinSystemGbm ()
~CWinSystemGbm () override
const std::string GetName () override
bool ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override
bool DisplayHardwareScalingEnabled () override
void UpdateDisplayHardwareScaling (const RESOLUTION_INFO &resInfo) override
void FlipPage (bool rendered, bool videoLayer, bool async)
bool CanDoWindowed () override
void UpdateResolutions () override
bool UseLimitedColor () override
bool Hide () override
bool Show (bool raise=true) override
void Register (IDispResource *resource) override
void Unregister (IDispResource *resource) override
bool SetHDR (const VideoPicture *videoPicture) override
Set the HDR metadata. Passing nullptr as the parameter should disable HDR.
bool IsHDRDisplay () override
CHDRCapabilities GetDisplayHDRCapabilities () const override
std::shared_ptr< CVideoLayerBridge > GetVideoLayerBridge () const
void RegisterVideoLayerBridge (std::shared_ptr< CVideoLayerBridge > bridge)
CGBMUtils::CGBMDevice & GetGBMDevice () const
std::shared_ptr< CDRMUtils > GetDrm () const
std::vector< std::string > GetConnectedOutputs () override
Public Member Functions inherited from CWinSystemBase
CWinSystemBase ()
virtual ~CWinSystemBase ()
virtual bool MoveWindow (int topLeft, int topRight)
virtual void FinishModeChange (RESOLUTION res)
virtual void FinishWindowResize (int newWidth, int newHeight)
virtual bool CenterWindow ()
virtual bool IsCreated ()
virtual void NotifyAppFocusChange (bool bGaining)
virtual void NotifyAppActiveChange (bool bActivated)
virtual void ShowOSMouse (bool show)
virtual bool HasCursor ()
virtual bool HasInertialGestures ()
virtual int NoOfBuffers ()
virtual void ForceFullScreen (const RESOLUTION_INFO &resInfo)
Forces the window to fullscreen provided the window resolution.
virtual float GetDisplayLatency ()
Get average display latency.
virtual float GetFrameLatencyAdjustment ()
Get time that should be subtracted from the display latency for this frame in milliseconds.
virtual bool Minimize ()
virtual bool Restore ()
virtual void OnMove (int x, int y)
virtual unsigned int GetScreenId (const std::string &screen)
Get the screen ID provided the screen name.
virtual void MoveToScreen (unsigned int screenIdx)
Window was requested to move to the given screen.
virtual void OnChangeScreen (unsigned int screenIdx)
Used to signal the windowing system about the change of the current screen.
KODI::WINDOWING::COSScreenSaverManager * GetOSScreenSaver ()
Get OS screen saver inhibit implementation if available.
unsigned int GetWidth ()
unsigned int GetHeight ()
bool IsFullScreen ()
virtual bool SupportsScreenMove ()
Check if the windowing system supports moving windows across screens.
void SetWindowResolution (int width, int height)
std::vector< RESOLUTION_WHR > ScreenResolutions (float refreshrate)
std::vector< REFRESHRATE > RefreshRates (int width, int height, uint32_t dwFlags)
REFRESHRATE DefaultRefreshRate (const std::vector< REFRESHRATE > &rates)
virtual bool HasCalibration (const RESOLUTION_INFO &resInfo)
virtual std::string GetClipboardText (void)
void RegisterRenderLoop (IRenderLoop *client)
void UnregisterRenderLoop (IRenderLoop *client)
void DriveRenderLoop ()
virtual bool MessagePump ()
virtual CGraphicContext & GetGfxContext () const
virtual void * GetHWContext ()
Get OS specific hardware context.
std::shared_ptr< CDPMSSupport > GetDPMSManager ()
virtual HDR_STATUS ToggleHDR ()
virtual HDR_STATUS GetOSHDRStatus ()
virtual float GetGuiSdrPeakLuminance () const
virtual bool HasSystemSdrPeakLuminance ()
virtual bool SupportsVideoSuperResolution ()
System supports Video Super Resolution HW upscaler i.e.: "NVIDIA RTX Video Super Resolution" or "Intel Video Super Resolution".
virtual DEBUG_INFO_RENDER GetDebugInfo ()
Gets debug info from video renderer for use in "Debug Info OSD" (Alt + O)
bool IsHDRDisplaySettingEnabled ()
Return true when HDR display is available and enabled in settings.
bool IsVideoSuperResolutionSettingEnabled ()
Return true when "Video Super Resolution" is supported and enabled in settings.
bool IsHighPrecisionProcessingSettingEnabled ()
Return true when setting "High Precision Processing" is enabled.
std::pair< bool, int > GetDitherSettings ()
Get dither settings.
Public Member Functions inherited from CRenderSystemGLES
CRenderSystemGLES ()
~CRenderSystemGLES () override=default
bool InitRenderSystem () override
bool DestroyRenderSystem () override
bool ResetRenderSystem (int width, int height) override
bool BeginRender () override
bool EndRender () override
void InvalidateColorBuffer () override
bool ClearBuffers (KODI::UTILS::COLOR::Color color) override
bool IsExtSupported (const char *extension) const override
void SetVSync (bool vsync)
void ResetVSync ()
void SetViewPort (const CRect &viewPort) override
void GetViewPort (CRect &viewPort) override
bool ScissorsCanEffectClipping () override
CRect ClipRectToScissorRect (const CRect &rect) override
void SetScissors (const CRect &rect) override
void ResetScissors () override
void SetDepthCulling (DEPTH_CULLING culling) override
void CaptureStateBlock () override
void ApplyStateBlock () override
void SetCameraPosition (const CPoint &camera, int screenWidth, int screenHeight, float stereoFactor=0.0f) override
bool SupportsStereo (RENDER_STEREO_MODE mode) const override
void Project (float &x, float &y, float &z) override
std::string GetShaderPath (const std::string &filename) override
void InitialiseShaders ()
void ReleaseShaders ()
void EnableGUIShader (ShaderMethodGLES method)
void DisableGUIShader ()
GLint GUIShaderGetPos ()
GLint GUIShaderGetCol ()
GLint GUIShaderGetCoord0 ()
GLint GUIShaderGetCoord1 ()
GLint GUIShaderGetUniCol ()
GLint GUIShaderGetCoord0Matrix ()
GLint GUIShaderGetField ()
GLint GUIShaderGetStep ()
GLint GUIShaderGetContrast ()
GLint GUIShaderGetBrightness ()
GLint GUIShaderGetModel ()
GLint GUIShaderGetMatrix ()
GLint GUIShaderGetClip ()
GLint GUIShaderGetCoordStep ()
GLint GUIShaderGetDepth ()
Public Member Functions inherited from CRenderSystemBase
CRenderSystemBase ()
virtual ~CRenderSystemBase ()
virtual void RestoreViewPort ()
virtual void SetStereoMode (RENDER_STEREO_MODE mode, RENDER_STEREO_VIEW view)
void GetRenderVersion (unsigned int &major, unsigned int &minor) const
const std::string & GetRenderVendor () const
const std::string & GetRenderRenderer () const
const std::string & GetRenderVersionString () const
virtual bool SupportsNPOT (bool dxt) const
unsigned int GetMaxTextureSize () const
unsigned int GetMinDXTPitch () const
virtual void ShowSplash (const std::string &message)
Static Public Member Functions
static void Register ()
static std::unique_ptr< CWinSystemBase > CreateWinSystem ()
Static Public Member Functions inherited from CWinSystemBase
static std::unique_ptr< CWinSystemBase > CreateWinSystem ()
Protected Member Functions
void SetVSyncImpl (bool enable) override
void PresentRenderImpl (bool rendered) override
bool CreateContext () override
Protected Member Functions inherited from KODI::WINDOWING::GBM::CWinSystemGbmEGLContext
CWinSystemGbmEGLContext (EGLenum platform, std::string const &platformExtension)
bool InitWindowSystemEGL (EGLint renderableType, EGLint apiType)
Protected Member Functions inherited from KODI::WINDOWING::GBM::CWinSystemGbm
void OnLostDevice ()
std::unique_ptr< CVideoSync > GetVideoSync (CVideoReferenceClock *clock) override
Protected Member Functions inherited from CWinSystemBase
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, float refreshRate, uint32_t dwFlags)
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, int screenWidth, int screenHeight, float refreshRate, uint32_t dwFlags)
virtual std::unique_ptr< KODI::WINDOWING::IOSScreenSaver > GetOSScreenSaverImpl ()
Protected Member Functions inherited from CRenderSystemGLES
void CalculateMaxTexturesize ()
Additional Inherited Members
Static Public Attributes inherited from CWinSystemBase
static const char * SETTING_WINSYSTEM_IS_HDR_DISPLAY = "winsystem.ishdrdisplay"
Protected Attributes inherited from KODI::WINDOWING::GBM::CWinSystemGbmEGLContext
std::unique_ptr< KODI::UTILS::EGL::CEGLFence > m_eglFence
std::unique_ptr< CVaapiProxy, delete_CVaapiProxy > m_vaapiProxy
Protected Attributes inherited from KODI::WINDOWING::LINUX::CWinSystemEGL
CEGLContextUtils m_eglContext
Protected Attributes inherited from KODI::WINDOWING::GBM::CWinSystemGbm
std::shared_ptr< CDRMUtils > m_DRM
std::unique_ptr< CGBMUtils > m_GBM
std::shared_ptr< CVideoLayerBridge > m_videoLayerBridge
CCriticalSection m_resourceSection
std::vector< IDispResource * > m_resources
bool m_dispReset = false
XbmcThreads::EndTime m_dispResetTimer
std::unique_ptr< CLibInputHandler > m_libinput
Protected Attributes inherited from CWinSystemBase
int m_nWidth = 0
int m_nHeight = 0
int m_nTop = 0
int m_nLeft = 0
bool m_bWindowCreated = false
bool m_bFullScreen = false
bool m_bBlankOtherDisplay = false
float m_fRefreshRate = 0.0f
std::unique_ptr< KODI::WINDOWING::COSScreenSaverManager > m_screenSaverManager
CCriticalSection m_renderLoopSection
std::vector< IRenderLoop * > m_renderLoopClients
std::unique_ptr< IWinEvents > m_winEvents
std::unique_ptr< CGraphicContext > m_gfxContext
std::shared_ptr< CDPMSSupport > m_dpms
Protected Attributes inherited from CRenderSystemGLES
bool m_bVsyncInit {false}
int m_width
int m_height
std::string m_RenderExtensions
std::map< ShaderMethodGLES, std::unique_ptr< CGLESShader > > m_pShader
ShaderMethodGLES m_method = ShaderMethodGLES::SM_DEFAULT
GLint m_viewPort [4]
Protected Attributes inherited from CRenderSystemBase
bool m_bRenderCreated
bool m_bVSync
unsigned int m_maxTextureSize
unsigned int m_minDXTPitch
std::string m_RenderRenderer
std::string m_RenderVendor
std::string m_RenderVersion
int m_RenderVersionMinor
int m_RenderVersionMajor
RENDER_STEREO_VIEW m_stereoView = RENDER_STEREO_VIEW_OFF
RENDER_STEREO_MODE m_stereoMode = RENDER_STEREO_MODE_OFF
bool m_limitedColorRange = false
bool m_transferPQ {false}
std::unique_ptr< CGUIImage > m_splashImage
std::unique_ptr< CGUITextLayout > m_splashMessageLayout
Constructor & Destructor Documentation
CWinSystemGbmGLESContext()
CWinSystemGbmGLESContext::CWinSystemGbmGLESContext ()
~CWinSystemGbmGLESContext()
KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::~CWinSystemGbmGLESContext () override default
Member Function Documentation
CreateContext()
bool CWinSystemGbmGLESContext::CreateContext () override protected virtual
Implements KODI::WINDOWING::GBM::CWinSystemGbmEGLContext.
References CEGLAttributesVec::Add(), CEGLContextUtils::CreateContext(), CLog::Log(), LOGERROR, and KODI::WINDOWING::LINUX::CWinSystemEGL::m_eglContext.
CreateWinSystem()
std::unique_ptr< CWinSystemBase > CWinSystemGbmGLESContext::CreateWinSystem () static
Referenced by Register().
GetRenderSystem()
CRenderSystemBase * KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::GetRenderSystem () inline override virtual
Reimplemented from CWinSystemBase.
InitWindowSystem()
bool CWinSystemGbmGLESContext::InitWindowSystem () override virtual
Reimplemented from KODI::WINDOWING::GBM::CWinSystemGbm.
References CBufferObjectFactory::ClearBufferObjects(), CDVDFactoryCodec::ClearHWAccels(), VIDEOPLAYER::CRendererFactory::ClearRenderer(), CEGLContextUtils::GetEGLDisplay(), KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::InitWindowSystemEGL(), KODI::WINDOWING::GBM::CWinSystemGbm::m_DRM, KODI::WINDOWING::LINUX::CWinSystemEGL::m_eglContext, KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::m_vaapiProxy, KODI::RETRO::CRPProcessInfoGbm::Register(), CDVDVideoCodecDRMPRIME::Register(), VIDEOPLAYER::CProcessInfoGBM::Register(), CRendererDRMPRIME::Register(), CRendererDRMPRIMEGLES::Register(), CLinuxRendererGLES::Register(), CScreenshotSurfaceGLES::Register(), CDMAHeapBufferObject::Register(), CDumbBufferObject::Register(), CGBMBufferObject::Register(), CUDMABufferObject::Register(), KODI::RETRO::CRPProcessInfo::RegisterRendererFactory(), KODI::WINDOWING::GBM::VaapiProxyConfig(), KODI::WINDOWING::GBM::VaapiProxyCreate(), and KODI::WINDOWING::GBM::VAAPIRegister().
PresentRender()
void CWinSystemGbmGLESContext::PresentRender (bool rendered, bool videoLayer) override virtual
Reimplemented from CRenderSystemGLES.
References KODI::WINDOWING::GBM::CWinSystemGbm::FlipPage(), CLog::Log(), CEGLUtils::Log(), LOGDEBUG, LOGERROR, CRenderSystemBase::m_bRenderCreated, KODI::WINDOWING::GBM::CWinSystemGbm::m_dispReset, KODI::WINDOWING::GBM::CWinSystemGbm::m_dispResetTimer, KODI::WINDOWING::GBM::CWinSystemGbm::m_DRM, KODI::WINDOWING::LINUX::CWinSystemEGL::m_eglContext, KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::m_eglFence, KODI::WINDOWING::GBM::CWinSystemGbm::m_resources, KODI::WINDOWING::GBM::CWinSystemGbm::m_resourceSection, KODI::TIME::Sleep(), and CEGLContextUtils::TrySwapBuffers().
PresentRenderImpl()
void KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::PresentRenderImpl (bool rendered) inline override protected virtual
Implements CRenderSystemGLES.
Register()
void CWinSystemGbmGLESContext::Register () static
References CreateWinSystem(), and KODI::WINDOWING::CWindowSystemFactory::RegisterWindowSystem().
Referenced by CPlatformFreebsd::InitStageOne(), and CPlatformLinux::InitStageOne().
SetFullScreen()
bool CWinSystemGbmGLESContext::SetFullScreen (bool fullScreen, RESOLUTION_INFO & res, bool blankOtherDisplays) override virtual
Reimplemented from KODI::WINDOWING::GBM::CWinSystemGbm.
References KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::CreateNewWindow(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, CLog::Log(), CEGLUtils::Log(), LOGDEBUG, LOGERROR, KODI::WINDOWING::LINUX::CWinSystemEGL::m_eglContext, CWinSystemBase::m_nHeight, CWinSystemBase::m_nWidth, CRenderSystemGLES::ResetRenderSystem(), KODI::WINDOWING::GBM::CWinSystemGbm::SetFullScreen(), and CEGLContextUtils::TrySwapBuffers().
SetVSyncImpl()
void KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::SetVSyncImpl (bool enable) inline override protected virtual
Implements CRenderSystemGLES.
The documentation for this class was generated from the following files:
WinSystemGbmGLESContext.h
WinSystemGbmGLESContext.cpp