Kodi Documentation: WinSystemOSX.mm File Reference
WinSystemOSX.mm File Reference
#include "WinSystemOSX.h"
#include "ServiceBroker.h"
#include "application/AppInboundProtocol.h"
#include "cores/AudioEngine/AESinkFactory.h"
#include "cores/AudioEngine/Sinks/AESinkDARWINOSX.h"
#include "cores/RetroPlayer/process/osx/RPProcessInfoOSX.h"
#include "cores/RetroPlayer/rendering/VideoRenderers/RPRendererOpenGL.h"
#include "cores/VideoPlayer/DVDCodecs/DVDFactoryCodec.h"
#include "cores/VideoPlayer/DVDCodecs/Video/VTB.h"
#include "cores/VideoPlayer/Process/osx/ProcessInfoOSX.h"
#include "cores/VideoPlayer/VideoRenderers/HwDecRender/RendererVTBGL.h"
#include "cores/VideoPlayer/VideoRenderers/RenderFactory.h"
#include "guilib/GUIWindowManager.h"
#include "messaging/ApplicationMessenger.h"
#include "rendering/gl/ScreenshotSurfaceGL.h"
#include "settings/DisplaySettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "threads/CriticalSection.h"
#include "utils/StringUtils.h"
#include "utils/log.h"
#include "windowing/osx/CocoaDPMSSupport.h"
#include "windowing/osx/OSScreenSaverOSX.h"
import "windowing/osx/OpenGL/OSXGLView.h"
import "windowing/osx/OpenGL/WindowControllerMacOS.h"
#include "windowing/osx/VideoSyncOsx.h"
#include "windowing/osx/WinEventsOSX.h"
#include "platform/darwin/osx/CocoaInterface.h"
#include "platform/darwin/osx/powermanagement/CocoaPowerSyscall.h"
#include <array>
#include <chrono>
#include <memory>
#include <mutex>
import <IOKit/graphics/IOGraphicsLib.h>
Namespaces
namespace anonymous_namespace{WinSystemOSX.mm}
Functions
size_t DisplayBitsPerPixelForMode (CGDisplayModeRef mode)
CGDirectDisplayID GetDisplayID (NSUInteger screen_index)
NSString * GetScreenName (NSUInteger screenIdx)
EdgeInsets GetScreenEdgeInsets (NSUInteger screenIdx)
NSString * screenNameForDisplay (NSUInteger screenIdx)
void CheckAndUpdateCurrentMonitor (NSUInteger screenNumber)
CGDirectDisplayID GetDisplayIDFromScreen (NSScreen *screen)
int GetDisplayIndex (CGDirectDisplayID display)
NSUInteger GetDisplayIndex (const std::string &dispName)
std::string ComputeVideoModeId (size_t resWidth, size_t resHeight, size_t pixelWidth, size_t pixelHeight, bool interlaced)
CFArrayRef CopyAllDisplayModes (CGDirectDisplayID display)
CGDisplayModeRef CreateModeById (const std::string &modeId, NSUInteger screenIdx)
CGDisplayModeRef CreateMode (size_t width, size_t height, double refreshrate, NSUInteger screenIdx)
CGDisplayModeRef BestMatchForMode (CGDirectDisplayID display, size_t bitsPerPixel, size_t width, size_t height)
void BlankOtherDisplays (NSUInteger screenBeingUsed)
void UnblankDisplay (NSUInteger screenToUnblank)
void UnblankDisplays (NSUInteger screenBeingUsed)
static void DisplayReconfigured (CGDirectDisplayID display, CGDisplayChangeSummaryFlags flags, void *userData)
Variables
constexpr int anonymous_namespace{WinSystemOSX.mm}::MAX_DISPLAYS = 32
constexpr const char * anonymous_namespace{WinSystemOSX.mm}::DEFAULT_SCREEN_NAME = "Default"
static std::array< NSWindowController *, MAX_DISPLAYS > blankingWindowControllers
Function Documentation
BestMatchForMode()
CGDisplayModeRef BestMatchForMode (CGDirectDisplayID display, size_t bitsPerPixel, size_t width, size_t height)
References CopyAllDisplayModes(), and DisplayBitsPerPixelForMode().
Referenced by CWinSystemOSX::SwitchToVideoMode().
BlankOtherDisplays()
void BlankOtherDisplays (NSUInteger screenBeingUsed)
References blankingWindowControllers.
Referenced by CWinSystemOSX::SetFullScreen().
CheckAndUpdateCurrentMonitor()
void CheckAndUpdateCurrentMonitor (NSUInteger screenNumber)
References CDisplaySettings::GetInstance(), CServiceBroker::GetSettingsComponent(), screenNameForDisplay(), CDisplaySettings::SetMonitor(), and CSettings::SETTING_VIDEOSCREEN_MONITOR.
Referenced by CWinSystemOSX::CreateNewWindow(), CWinSystemOSX::OnChangeScreen(), and CWinSystemOSX::OnMove().
ComputeVideoModeId()
std::string ComputeVideoModeId (size_t resWidth, size_t resHeight, size_t pixelWidth, size_t pixelHeight, bool interlaced)
References KODI::UTILS::StringUtils::Format().
Referenced by CreateModeById(), CWinSystemOSX::FillInVideoModes(), and CWinSystemOSX::UpdateResolutions().
CopyAllDisplayModes()
CFArrayRef CopyAllDisplayModes (CGDirectDisplayID display)
References LOGERROR, and value.
Referenced by BestMatchForMode(), CreateMode(), CreateModeById(), and CWinSystemOSX::FillInVideoModes().
CreateMode()
CGDisplayModeRef CreateMode (size_t width, size_t height, double refreshrate, NSUInteger screenIdx)
References CopyAllDisplayModes(), DisplayBitsPerPixelForMode(), GetDisplayID(), LOGDEBUG, and LOGERROR.
Referenced by CWinSystemOSX::SwitchToVideoMode().
CreateModeById()
CGDisplayModeRef CreateModeById (const std::string & modeId, NSUInteger screenIdx)
References ComputeVideoModeId(), CopyAllDisplayModes(), DisplayBitsPerPixelForMode(), GetDisplayID(), LOGDEBUG, and LOGERROR.
Referenced by CWinSystemOSX::SwitchToVideoMode().
DisplayBitsPerPixelForMode()
size_t DisplayBitsPerPixelForMode (CGDisplayModeRef mode)
Referenced by BestMatchForMode(), CreateMode(), CreateModeById(), and CWinSystemOSX::FillInVideoModes().
DisplayReconfigured()
static void DisplayReconfigured (CGDirectDisplayID display, CGDisplayChangeSummaryFlags flags, void * userData) static
References CWinSystemOSX::AnnounceOnLostDevice(), GetDisplayIDFromScreen(), CWinSystemOSX::HandleOnResetDevice(), CWinSystemOSX::HasValidResolution(), CLog::Log(), LOGDEBUG, CWinSystemOSX::StartLostDeviceTimer(), and CWinSystemOSX::StopLostDeviceTimer().
Referenced by CWinSystemOSX::DestroyWindowSystem(), and CWinSystemOSX::InitWindowSystem().
GetDisplayID()
CGDirectDisplayID GetDisplayID (NSUInteger screen_index)
References anonymous_namespace{WinSystemOSX.mm}::MAX_DISPLAYS.
Referenced by CreateMode(), CreateModeById(), CWinSystemOSX::FillInVideoModes(), GetScreenName(), CWinSystemOSX::GetScreenResolution(), screenNameForDisplay(), and CWinSystemOSX::SwitchToVideoMode().
GetDisplayIDFromScreen()
CGDirectDisplayID GetDisplayIDFromScreen (NSScreen * screen)
Referenced by DisplayReconfigured(), and CWinSystemOSX::OnChangeScreen().
GetDisplayIndex() [1/2]
int GetDisplayIndex (CGDirectDisplayID display)
References anonymous_namespace{WinSystemOSX.mm}::MAX_DISPLAYS.
Referenced by CWinSystemOSX::CreateNewWindow(), CWinSystemOSX::FillInVideoModes(), CWinSystemOSX::GetScreenId(), CWinSystemOSX::OnChangeScreen(), CWinSystemOSX::SetFullScreen(), CWinSystemOSX::SwitchToVideoMode(), and CWinSystemOSX::UpdateResolutions().
GetDisplayIndex() [2/2]
NSUInteger GetDisplayIndex (const std::string & dispName)
References name, and screenNameForDisplay().
GetScreenEdgeInsets()
EdgeInsets GetScreenEdgeInsets (NSUInteger screenIdx)
@TODO update code block once minimal SDK version is bumped to at least 12.0 (remove NSInvocation and selector)
Referenced by CWinSystemOSX::FillInVideoModes(), and CWinSystemOSX::UpdateResolutions().
GetScreenName()
NSString * GetScreenName (NSUInteger screenIdx)
TODO: Remove when 10.15 is the minimal target
References GetDisplayID().
Referenced by screenNameForDisplay().
screenNameForDisplay()
NSString * screenNameForDisplay (NSUInteger screenIdx)
References anonymous_namespace{WinSystemOSX.mm}::DEFAULT_SCREEN_NAME, GetDisplayID(), and GetScreenName().
Referenced by CheckAndUpdateCurrentMonitor(), CWinSystemOSX::FillInVideoModes(), CWinSystemOSX::GetConnectedOutputs(), GetDisplayIndex(), and CWinSystemOSX::UpdateResolutions().
UnblankDisplay()
void UnblankDisplay (NSUInteger screenToUnblank)
References blankingWindowControllers.
Referenced by CWinSystemOSX::OnChangeScreen(), and UnblankDisplays().
UnblankDisplays()
void UnblankDisplays (NSUInteger screenBeingUsed)
References blankingWindowControllers, and UnblankDisplay().
Referenced by CWinSystemOSX::DestroyWindowSystem(), and CWinSystemOSX::SetFullScreen().
Variable Documentation
blankingWindowControllers
std::array<NSWindowController*, MAX_DISPLAYS> blankingWindowControllers static
Referenced by BlankOtherDisplays(), UnblankDisplay(), and UnblankDisplays().