Kodi Documentation: CVideoLibraryQueue Class Reference
CVideoLibraryQueue Class Reference
Queue for video library jobs.
#include <VideoLibraryQueue.h>
Public Member Functions
~CVideoLibraryQueue () override
void ScanLibrary (const std::string &directory, bool scanAll=false, bool showProgress=true)
Enqueue a library scan job.
bool IsScanningLibrary () const
Check if a library scan is in progress.
void StopLibraryScanning ()
Stop and dequeue all scanning jobs.
bool CleanLibrary (const std::set< int > &paths=std::set< int >(), bool asynchronous=true, CGUIDialogProgressBarHandle *progressBar=NULL)
Enqueue a library cleaning job.
bool CleanLibraryModal (const std::set< int > &paths=std::set< int >())
Executes a library cleaning with a modal dialog.
void RefreshItem (std::shared_ptr< CFileItem > item, bool ignoreNfo=false, bool forceRefresh=true, bool refreshAll=false, const std::string &searchTitle="")
Enqueues a job to refresh the details of the given item.
bool RefreshItemModal (std::shared_ptr< CFileItem > item, bool forceRefresh=true, bool refreshAll=false)
Refreshes the details of the given item with a modal dialog.
void MarkAsWatched (const std::shared_ptr< CFileItem > &item, bool watched)
Queue a watched status update job.
void ResetResumePoint (const std::shared_ptr< CFileItem > &item)
Queue a reset resume point job.
void AddJob (CVideoLibraryJob *job)
Adds the given job to the queue.
void CancelJob (CVideoLibraryJob *job)
Cancels the given job and removes it from the queue.
void CancelAllJobs ()
Cancels all running and queued jobs.
bool IsRunning () const
Whether any jobs are running or not.
Static Public Member Functions
static CVideoLibraryQueue & GetInstance ()
Gets the singleton instance of the video library queue.
Protected Member Functions
void OnJobComplete (unsigned int jobID, bool success, CJob *job) override
The callback used when a job completes.
void Refresh ()
Notifies all to refresh the current listings.
Protected Member Functions inherited from CJobQueue
bool QueueEmpty () const
Returns if we still have jobs waiting to be processed NOTE: This function does not take into account the jobs that are currently processing.
CJobQueue (bool lifo=false, unsigned int jobsAtOnce=1, CJob::PRIORITY priority=CJob::PRIORITY_LOW)
CJobQueue constructor.
~CJobQueue () override
CJobQueue destructor Cancels any in-process jobs, and destroys the job queue.
bool AddJob (CJob *job)
Add a job to the queue On completion of the job, destruction of the job queue or in case the job could not be added successfully, the CJob object will be destroyed.
template<typename F >
void Submit (F &&f)
Add a function f to this job queue.
void CancelJob (const CJob *job)
Cancel a job in the queue Cancels a job in the queue. Any job currently being processed may complete after this call has completed, but OnJobComplete will not be performed. If the job is only queued then it will be removed from the queue and deleted.
void CancelJobs ()
Cancel all jobs in the queue Removes all jobs from the queue. Any job currently being processed may complete after this call has completed, but OnJobComplete will not be performed.
bool IsProcessing () const
Check whether the queue is processing a job.
void OnJobAbort (unsigned int jobID, CJob *job) override
The callback used when a job will be aborted.
Protected Member Functions inherited from IJobCallback
virtual ~IJobCallback ()=default
Destructor for job call back objects.
virtual void OnJobProgress (unsigned int jobID, unsigned int progress, unsigned int total, const CJob *job)
An optional callback function that a job may call while processing.
Private Types
typedef std::set< CVideoLibraryJob * > VideoLibraryJobs
typedef std::map< std::string, VideoLibraryJobs > VideoLibraryJobMap
Private Member Functions
CVideoLibraryQueue ()
CVideoLibraryQueue (const CVideoLibraryQueue &)=delete
CVideoLibraryQueue const & operator= (CVideoLibraryQueue const &)=delete
Private Attributes
VideoLibraryJobMap m_jobs
CCriticalSection m_critical
bool m_modal = false
bool m_cleaning = false
Detailed Description
Queue for video library jobs.
The queue can only process a single job at any time and every job will be executed at the lowest priority.
Member Typedef Documentation
VideoLibraryJobMap
typedef std::map<std::string, VideoLibraryJobs> CVideoLibraryQueue::VideoLibraryJobMap private
VideoLibraryJobs
typedef std::set<CVideoLibraryJob*> CVideoLibraryQueue::VideoLibraryJobs private
Constructor & Destructor Documentation
~CVideoLibraryQueue()
CVideoLibraryQueue::~CVideoLibraryQueue () override
References m_critical, and m_jobs.
CVideoLibraryQueue() [1/2]
CVideoLibraryQueue::CVideoLibraryQueue () private
CVideoLibraryQueue() [2/2]
CVideoLibraryQueue::CVideoLibraryQueue (const CVideoLibraryQueue &) private delete
Member Function Documentation
AddJob()
void CVideoLibraryQueue::AddJob (CVideoLibraryJob * job)
Adds the given job to the queue.
Parameters
[in] job Video library job to be queued.
References CJobQueue::AddJob(), CVideoLibraryJob::GetType(), m_critical, and m_jobs.
Referenced by CleanLibrary(), MarkAsWatched(), RefreshItem(), ResetResumePoint(), and ScanLibrary().
CancelAllJobs()
void CVideoLibraryQueue::CancelAllJobs ()
Cancels all running and queued jobs.
References CJobQueue::CancelJobs(), m_critical, and m_jobs.
Referenced by CProfileManager::LogOff(), and CApplication::Stop().
CancelJob()
void CVideoLibraryQueue::CancelJob (CVideoLibraryJob * job)
Cancels the given job and removes it from the queue.
Parameters
[in] job Video library job to be canceled and removed from the queue.
References CVideoLibraryJob::CanBeCancelled(), CVideoLibraryJob::Cancel(), CJobQueue::CancelJob(), CVideoLibraryJob::GetType(), m_critical, and m_jobs.
Referenced by StopLibraryScanning().
CleanLibrary()
bool CVideoLibraryQueue::CleanLibrary (const std::set< int > & paths = std::set<int>(), bool asynchronous = true, CGUIDialogProgressBarHandle * progressBar = NULL)
Enqueue a library cleaning job.
Parameters
[in] paths Set with database IDs of paths to be cleaned
[in] asynchronous Run the clean job asynchronously. Defaults to true
[in] progressBar Progress bar to update in GUI. Defaults to NULL (no progress bar to update)
Returns
True if the video library cleaning job has started, false otherwise
References AddJob(), CVideoLibraryProgressJob::DoWork(), IsRunning(), m_cleaning, m_modal, and Refresh().
Referenced by CleanLibrary().
CleanLibraryModal()
bool CVideoLibraryQueue::CleanLibraryModal (const std::set< int > & paths = std::set<int>())
Executes a library cleaning with a modal dialog.
Parameters
[in] paths Set with database IDs of paths to be cleaned
Returns
True if the video library cleaning job has started, false otherwise
References CVideoLibraryProgressJob::DoWork(), IsRunning(), m_cleaning, m_modal, and Refresh().
Referenced by CleanLibrary().
GetInstance()
CVideoLibraryQueue & CVideoLibraryQueue::GetInstance () static
Gets the singleton instance of the video library queue.
Referenced by CApplicationPowerHandling::CheckShutdown(), CleanLibrary(), CGUIDialogVideoInfo::DeleteVideoItemFromDatabase(), CONTEXTMENU::CVideoRemoveResumePoint::Execute(), CONTEXTMENU::CVideoMarkWatched::Execute(), CONTEXTMENU::CVideoMarkUnWatched::Execute(), KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool(), CGUIWindowVideoNav::GetContextButtons(), CProfileManager::LogOff(), PVR::CGUIWindowPVRRecordingsBase::OnAction(), CGUIWindowVideoNav::OnAction(), CGUIWindowVideoBase::OnAssignContent(), CGUIWindowVideoNav::OnClick(), CGUIWindowVideoNav::OnMessage(), CGUIWindowVideoBase::OnScan(), CMediaSettings::OnSettingAction(), JSONRPC::CVideoLibrary::RefreshEpisode(), JSONRPC::CVideoLibrary::RefreshMovie(), JSONRPC::CVideoLibrary::RefreshMusicVideo(), JSONRPC::CVideoLibrary::RefreshTVShow(), CVideoDatabase::SetPlayCount(), CGUIWindowVideoBase::ShowInfo(), CApplication::Stop(), CApplication::UpdateLibraries(), UpdateLibrary(), CGUIDialogVideoInfo::UpdateVideoItemSortTitle(), and CGUIDialogVideoInfo::UpdateVideoItemTitle().
IsRunning()
bool CVideoLibraryQueue::IsRunning () const
Whether any jobs are running or not.
References CJobQueue::IsProcessing(), and m_modal.
Referenced by CApplicationPowerHandling::CheckShutdown(), CleanLibrary(), CleanLibraryModal(), and RefreshItemModal().
IsScanningLibrary()
bool CVideoLibraryQueue::IsScanningLibrary () const
Check if a library scan is in progress.
Returns
True if a scan is in progress, false otherwise
References m_cleaning, and m_jobs.
Referenced by KODI::GUILIB::GUIINFO::CLibraryGUIInfo::GetBool(), and UpdateLibrary().
MarkAsWatched()
void CVideoLibraryQueue::MarkAsWatched (const std::shared_ptr< CFileItem > & item, bool watched)
Queue a watched status update job.
Parameters
[in] item Item to update watched status for
[in] watched New watched status
References AddJob().
Referenced by CONTEXTMENU::CVideoMarkWatched::Execute(), CONTEXTMENU::CVideoMarkUnWatched::Execute(), PVR::CGUIWindowPVRRecordingsBase::OnAction(), and CGUIWindowVideoNav::OnAction().
OnJobComplete()
void CVideoLibraryQueue::OnJobComplete (unsigned int jobID, bool success, CJob * job) override protected virtual
The callback used when a job completes.
CJobQueue implementation will cleanup the internal processing queue and then queue the next job at the job manager, if any.
Parameters
jobID the unique id of the job (as retrieved from CJobManager::AddJob)
success the result from the DoWork call
job the job that has been processed.
See also
CJobManager, IJobCallback and CJob
Reimplemented from CJobQueue.
References CJob::GetType(), m_critical, m_jobs, CJobQueue::OnJobComplete(), CJobQueue::QueueEmpty(), Refresh(), and success.
operator=()
CVideoLibraryQueue const & CVideoLibraryQueue::operator= (CVideoLibraryQueue const &) private delete
Refresh()
void CVideoLibraryQueue::Refresh () protected
Notifies all to refresh the current listings.
References CUtil::DeleteVideoDatabaseDirectoryCache(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, and GUI_MSG_UPDATE.
Referenced by CleanLibrary(), CleanLibraryModal(), OnJobComplete(), and StopLibraryScanning().
RefreshItem()
void CVideoLibraryQueue::RefreshItem (std::shared_ptr< CFileItem > item, bool ignoreNfo = false, bool forceRefresh = true, bool refreshAll = false, const std::string & searchTitle = "")
Enqueues a job to refresh the details of the given item.
Parameters
[in,out] item Video item to be refreshed
[in] ignoreNfo Whether or not to ignore local NFO files
[in] forceRefresh Whether to force a complete refresh (including NFO or internet lookup)
[in] refreshAll Whether to refresh all sub-items (in case of a tvshow)
[in] searchTitle Title to use for the search (instead of determining it from the item's filename/path)
References AddJob().
Referenced by JSONRPC::CVideoLibrary::RefreshEpisode(), JSONRPC::CVideoLibrary::RefreshMovie(), JSONRPC::CVideoLibrary::RefreshMusicVideo(), and JSONRPC::CVideoLibrary::RefreshTVShow().
RefreshItemModal()
bool CVideoLibraryQueue::RefreshItemModal (std::shared_ptr< CFileItem > item, bool forceRefresh = true, bool refreshAll = false)
Refreshes the details of the given item with a modal dialog.
Parameters
[in,out] item Video item to be refreshed
[in] forceRefresh Whether to force a complete refresh (including NFO or internet lookup)
[in] refreshAll Whether to refresh all sub-items (in case of a tvshow)
Returns
True if the item has been successfully refreshed, false otherwise.
References CProgressJob::DoModal(), IsRunning(), and m_modal.
ResetResumePoint()
void CVideoLibraryQueue::ResetResumePoint (const std::shared_ptr< CFileItem > & item)
Queue a reset resume point job.
Parameters
[in] item Item to reset the resume point for
References AddJob().
Referenced by CONTEXTMENU::CVideoRemoveResumePoint::Execute().
ScanLibrary()
void CVideoLibraryQueue::ScanLibrary (const std::string & directory, bool scanAll = false, bool showProgress = true)
Enqueue a library scan job.
Parameters
[in] directory Directory to scan
[in] scanAll Ignore exclude setting for items. Defaults to false
[in] showProgress Whether or not to show a progress dialog. Defaults to true
References AddJob().
Referenced by CGUIWindowVideoBase::OnAssignContent(), CGUIWindowVideoBase::OnScan(), CApplication::UpdateLibraries(), and UpdateLibrary().
StopLibraryScanning()
void CVideoLibraryQueue::StopLibraryScanning ()
Stop and dequeue all scanning jobs.
References CancelJob(), m_critical, m_jobs, and Refresh().
Referenced by CGUIWindowVideoNav::OnMessage(), and UpdateLibrary().
Member Data Documentation
m_cleaning
bool CVideoLibraryQueue::m_cleaning = false private
Referenced by CleanLibrary(), CleanLibraryModal(), and IsScanningLibrary().
m_critical
CCriticalSection CVideoLibraryQueue::m_critical private
Referenced by AddJob(), CancelAllJobs(), CancelJob(), OnJobComplete(), StopLibraryScanning(), and ~CVideoLibraryQueue().
m_jobs
VideoLibraryJobMap CVideoLibraryQueue::m_jobs private
Referenced by AddJob(), CancelAllJobs(), CancelJob(), IsScanningLibrary(), OnJobComplete(), StopLibraryScanning(), and ~CVideoLibraryQueue().
m_modal
bool CVideoLibraryQueue::m_modal = false private
Referenced by CleanLibrary(), CleanLibraryModal(), IsRunning(), and RefreshItemModal().
The documentation for this class was generated from the following files:
VideoLibraryQueue.h
VideoLibraryQueue.cpp