Kodi Documentation: XFILE::CXbtFile Class Reference
XFILE::CXbtFile Class Reference
#include <XbtFile.h>
Public Member Functions
CXbtFile ()
~CXbtFile () override
bool Open (const CURL &url) override
void Close () override
bool Exists (const CURL &url) override
int64_t GetPosition () override
int64_t GetLength () override
int Stat (struct __stat64 *buffer) override
int Stat (const CURL &url, struct __stat64 *buffer) override
ssize_t Read (void *lpBuf, size_t uiBufSize) override
int64_t Seek (int64_t iFilePosition, int iWhence=SEEK_SET) override
uint32_t GetImageWidth () const
uint32_t GetImageHeight () const
XB_FMT GetImageFormat () const
KD_TEX_FMT GetKDFormat () const
KD_TEX_FMT GetKDFormatType () const
KD_TEX_ALPHA GetKDAlpha () const
KD_TEX_SWIZ GetKDSwizzle () const
bool HasImageAlpha () const
Public Member Functions inherited from XFILE::IFile
IFile ()
virtual ~IFile ()
virtual bool OpenForWrite (const CURL &url, bool bOverWrite=false)
virtual bool ReOpen (const CURL &url)
virtual ssize_t Write (const void *bufPtr, size_t bufSize)
virtual bool ReadString (char *szLine, int iLineLength)
virtual void Flush ()
virtual int Truncate (int64_t size)
virtual int GetChunkSize ()
virtual double GetDownloadSpeed ()
virtual bool Delete (const CURL &url)
virtual bool Rename (const CURL &url, const CURL &urlnew)
virtual bool SetHidden (const CURL &url, bool hidden)
virtual int IoControl (EIoControl request, void *param)
virtual const std::string GetProperty (XFILE::FileProperty type, const std::string &name="") const
virtual const std::vector< std::string > GetPropertyValues (XFILE::FileProperty type, const std::string &name="") const
Private Member Functions
bool GetFirstFrame (CXBTFFrame &frame) const
Static Private Member Functions
static bool GetReader (const CURL &url, CXBTFReaderPtr &reader)
static bool GetReaderAndFile (const CURL &url, CXBTFReaderPtr &reader, CXBTFFile &file)
static bool GetFile (const CURL &url, CXBTFFile &file)
Private Attributes
CURL m_url
bool m_open = false
CXBTFReaderPtr m_xbtfReader
CXBTFFile m_xbtfFile
std::vector< uint64_t > m_frameStartPositions
size_t m_frameIndex = 0
uint64_t m_positionWithinFrame = 0
int64_t m_positionTotal = 0
std::vector< std::vector< uint8_t > > m_unpackedFrames
Constructor & Destructor Documentation
CXbtFile()
XFILE::CXbtFile::CXbtFile ()
~CXbtFile()
XFILE::CXbtFile::~CXbtFile () override
References Close().
Member Function Documentation
Close()
void XFILE::CXbtFile::Close () override virtual
Implements XFILE::IFile.
References m_frameIndex, m_frameStartPositions, m_open, m_positionTotal, m_positionWithinFrame, and m_unpackedFrames.
Referenced by Read(), Seek(), and ~CXbtFile().
Exists()
bool XFILE::CXbtFile::Exists (const CURL & url) override virtual
Implements XFILE::IFile.
References GetFile().
GetFile()
bool XFILE::CXbtFile::GetFile (const CURL & url, CXBTFFile & file) static private
References GetReaderAndFile().
Referenced by Exists().
GetFirstFrame()
bool XFILE::CXbtFile::GetFirstFrame (CXBTFFrame & frame) const private
References CXBTFFile::GetFrames(), m_open, and m_xbtfFile.
Referenced by GetImageFormat(), GetImageHeight(), GetImageWidth(), GetKDAlpha(), GetKDFormat(), GetKDFormatType(), GetKDSwizzle(), and HasImageAlpha().
GetImageFormat()
XB_FMT XFILE::CXbtFile::GetImageFormat () const
References GetFirstFrame(), CXBTFFrame::GetFormat(), and XB_FMT_UNKNOWN.
Referenced by CTexture::LoadFromFileInternal().
GetImageHeight()
uint32_t XFILE::CXbtFile::GetImageHeight () const
References GetFirstFrame(), and CXBTFFrame::GetHeight().
Referenced by CTexture::LoadFromFileInternal().
GetImageWidth()
uint32_t XFILE::CXbtFile::GetImageWidth () const
References GetFirstFrame(), and CXBTFFrame::GetWidth().
Referenced by CTexture::LoadFromFileInternal().
GetKDAlpha()
KD_TEX_ALPHA XFILE::CXbtFile::GetKDAlpha () const
References GetFirstFrame(), CXBTFFrame::GetKDAlpha(), and KD_TEX_ALPHA_OPAQUE.
Referenced by CTexture::LoadFromFileInternal().
GetKDFormat()
KD_TEX_FMT XFILE::CXbtFile::GetKDFormat () const
References GetFirstFrame(), CXBTFFrame::GetKDFormat(), and KD_TEX_FMT_UNKNOWN.
Referenced by CTexture::LoadFromFileInternal().
GetKDFormatType()
KD_TEX_FMT XFILE::CXbtFile::GetKDFormatType () const
References GetFirstFrame(), CXBTFFrame::GetKDFormatType(), and KD_TEX_FMT_UNKNOWN.
Referenced by CTexture::LoadFromFileInternal().
GetKDSwizzle()
KD_TEX_SWIZ XFILE::CXbtFile::GetKDSwizzle () const
References GetFirstFrame(), CXBTFFrame::GetKDSwizzle(), and KD_TEX_SWIZ_RGBA.
Referenced by CTexture::LoadFromFileInternal().
GetLength()
int64_t XFILE::CXbtFile::GetLength () override virtual
Implements XFILE::IFile.
References CXBTFFile::GetUnpackedSize(), m_open, and m_xbtfFile.
Referenced by Read(), and Seek().
GetPosition()
int64_t XFILE::CXbtFile::GetPosition () override virtual
Implements XFILE::IFile.
References m_open, and m_positionTotal.
GetReader()
bool XFILE::CXbtFile::GetReader (const CURL & url, CXBTFReaderPtr & reader) static private
References XFILE::CXbtManager::GetInstance(), XFILE::CXbtManager::GetReader(), and CURL::SetOptions().
Referenced by GetReaderAndFile().
GetReaderAndFile()
bool XFILE::CXbtFile::GetReaderAndFile (const CURL & url, CXBTFReaderPtr & reader, CXBTFFile & file) static private
References CURL::GetFileName(), GetReader(), and CURL::SetOptions().
Referenced by GetFile(), Open(), and Stat().
HasImageAlpha()
bool XFILE::CXbtFile::HasImageAlpha () const
References GetFirstFrame(), and CXBTFFrame::HasAlpha().
Referenced by CTexture::LoadFromFileInternal().
Open()
bool XFILE::CXbtFile::Open (const CURL & url) override virtual
Implements XFILE::IFile.
References CXBTFFile::GetFrames(), GetReaderAndFile(), m_frameIndex, m_frameStartPositions, m_open, m_positionTotal, m_positionWithinFrame, m_unpackedFrames, m_url, m_xbtfFile, m_xbtfReader, and CURL::SetOptions().
Referenced by CTexture::LoadFromFileInternal().
Read()
ssize_t XFILE::CXbtFile::Read (void * bufPtr, size_t bufSize) override virtual
Attempt to read bufSize bytes from currently opened file into buffer bufPtr.
Parameters
bufPtr pointer to buffer
bufSize size of the buffer
Returns
number of successfully read bytes if any bytes were read and stored in buffer, zero if no bytes are available to read (end of file was reached) or undetectable error occur, -1 in case of any explicit error
Implements XFILE::IFile.
References Close(), data(), CXBTFFile::GetFrames(), GetLength(), CXBTFFrame::GetUnpackedSize(), int64_t(), m_frameIndex, m_open, m_positionTotal, m_positionWithinFrame, m_unpackedFrames, m_xbtfFile, m_xbtfReader, SIZE_MAX, SSIZE_MAX, and CTextureBundleXBT::UnpackFrame().
Seek()
int64_t XFILE::CXbtFile::Seek (int64_t iFilePosition, int iWhence = SEEK_SET) override virtual
Implements XFILE::IFile.
References Close(), CXBTFFile::GetFrames(), GetLength(), CXBTFFrame::GetUnpackedSize(), int64_t(), m_frameIndex, m_open, m_positionTotal, m_positionWithinFrame, m_unpackedFrames, m_xbtfFile, m_xbtfReader, and CTextureBundleXBT::UnpackFrame().
Stat() [1/2]
int XFILE::CXbtFile::Stat (const CURL & url, struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about file specified by url. For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
url specifies requested file
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Implements XFILE::IFile.
References _S_IFDIR, XFILE::CFile::Exists(), CURL::GetFileName(), CURL::GetHostName(), GetReaderAndFile(), CXBTFFile::GetUnpackedSize(), and XFILE::CFile::Stat().
Stat() [2/2]
int XFILE::CXbtFile::Stat (struct __stat64 * buffer) override virtual
Fills struct __stat64 with information about currently open file For st_mode function will set correctly _S_IFDIR (directory) flag and may set _S_IREAD (read permission), _S_IWRITE (write permission) flags if such information is available. Function may set st_size (file size), st_atime, st_mtime, st_ctime (access, modification, creation times). Any other flags and members of __stat64 that didn't updated with actual file information will be set to zero (st_nlink can be set ether to 1 or zero).
Parameters
buffer pointer to __stat64 buffer to receive information about file
Returns
zero of success, -1 otherwise.
Reimplemented from XFILE::IFile.
References m_open, m_url, and Stat().
Referenced by Stat().
Member Data Documentation
m_frameIndex
size_t XFILE::CXbtFile::m_frameIndex = 0 private
Referenced by Close(), Open(), Read(), and Seek().
m_frameStartPositions
std::vector<uint64_t> XFILE::CXbtFile::m_frameStartPositions private
Referenced by Close(), and Open().
m_open
bool XFILE::CXbtFile::m_open = false private
Referenced by Close(), GetFirstFrame(), GetLength(), GetPosition(), Open(), Read(), Seek(), and Stat().
m_positionTotal
int64_t XFILE::CXbtFile::m_positionTotal = 0 private
Referenced by Close(), GetPosition(), Open(), Read(), and Seek().
m_positionWithinFrame
uint64_t XFILE::CXbtFile::m_positionWithinFrame = 0 private
Referenced by Close(), Open(), Read(), and Seek().
m_unpackedFrames
std::vector<std::vector<uint8_t> > XFILE::CXbtFile::m_unpackedFrames private
Referenced by Close(), Open(), Read(), and Seek().
m_url
CURL XFILE::CXbtFile::m_url private
Referenced by Open(), and Stat().
m_xbtfFile
CXBTFFile XFILE::CXbtFile::m_xbtfFile private
Referenced by GetFirstFrame(), GetLength(), Open(), Read(), and Seek().
m_xbtfReader
CXBTFReaderPtr XFILE::CXbtFile::m_xbtfReader private
Referenced by Open(), Read(), and Seek().
The documentation for this class was generated from the following files:
XbtFile.h
XbtFile.cpp