Kodi Documentation: TestHTTPDirectory Class Reference
TestHTTPDirectory Class Reference
Protected Member Functions
TestHTTPDirectory ()
~TestHTTPDirectory () override=default
void SetUp () override
void TearDown () override
void SetupMediaSources ()
void TearDownMediaSources ()
std::string GetUrl (const std::string &path)
std::string GetUrlOfTestFile (const std::string &testFile)
void CheckFileItemTypes (CFileItemList const &items)
void CheckFileItemLabels (CFileItemList const &items)
void CheckFileItemDateTimes (CFileItemList const &items)
void CheckFileItemSizes (CFileItemList const &items)
void CheckFileItems (CFileItemList const &items)
void CheckFileItemsAndMetadata (CFileItemList const &items)
Protected Attributes
CWebServer m_webServer
uint16_t m_webServerPort
std::string m_baseUrl
std::string const m_sourcePath
CHTTPVfsHandler m_vfsHandler
CHTTPDirectory m_httpDirectory
Constructor & Destructor Documentation
TestHTTPDirectory()
TestHTTPDirectory::TestHTTPDirectory () inline protected
References m_baseUrl, m_webServerPort, and WEBSERVER_HOST.
~TestHTTPDirectory()
TestHTTPDirectory::~TestHTTPDirectory () override protected default
Member Function Documentation
CheckFileItemDateTimes()
void TestHTTPDirectory::CheckFileItemDateTimes (CFileItemList const & items) inline protected
References CFileItemList::GetObjectCount(), SAMPLE_ITEM_1_DATETIME, SAMPLE_ITEM_2_DATETIME, SAMPLE_ITEM_3_DATETIME, SAMPLE_ITEM_4_DATETIME, SAMPLE_ITEM_5_DATETIME, SAMPLE_ITEM_6_DATETIME, and SAMPLE_ITEM_COUNT.
Referenced by CheckFileItemsAndMetadata().
CheckFileItemLabels()
void TestHTTPDirectory::CheckFileItemLabels (CFileItemList const & items) inline protected
References CFileItemList::GetObjectCount(), SAMPLE_ITEM_1_LABEL, SAMPLE_ITEM_2_LABEL, SAMPLE_ITEM_3_LABEL, SAMPLE_ITEM_4_LABEL, SAMPLE_ITEM_5_LABEL, SAMPLE_ITEM_6_LABEL, and SAMPLE_ITEM_COUNT.
Referenced by CheckFileItems().
CheckFileItems()
void TestHTTPDirectory::CheckFileItems (CFileItemList const & items) inline protected
References CheckFileItemLabels(), and CheckFileItemTypes().
Referenced by CheckFileItemsAndMetadata().
CheckFileItemsAndMetadata()
void TestHTTPDirectory::CheckFileItemsAndMetadata (CFileItemList const & items) inline protected
References CheckFileItemDateTimes(), CheckFileItems(), and CheckFileItemSizes().
CheckFileItemSizes()
void TestHTTPDirectory::CheckFileItemSizes (CFileItemList const & items) inline protected
References ASSERT_NE(), CFileItemList::GetObjectCount(), SAMPLE_ITEM_1_SIZE, SAMPLE_ITEM_2_SIZE, SAMPLE_ITEM_3_SIZE, SAMPLE_ITEM_4_SIZE, SAMPLE_ITEM_5_SIZE, SAMPLE_ITEM_6_SIZE, and SAMPLE_ITEM_COUNT.
Referenced by CheckFileItemsAndMetadata().
CheckFileItemTypes()
void TestHTTPDirectory::CheckFileItemTypes (CFileItemList const & items) inline protected
References CFileItemList::GetObjectCount(), and SAMPLE_ITEM_COUNT.
Referenced by CheckFileItems().
GetUrl()
std::string TestHTTPDirectory::GetUrl (const std::string & path) inline protected
References URIUtils::AddFileToFolder(), and m_baseUrl.
Referenced by GetUrlOfTestFile().
GetUrlOfTestFile()
std::string TestHTTPDirectory::GetUrlOfTestFile (const std::string & testFile) inline protected
References URIUtils::AddFileToFolder(), GetUrl(), and m_sourcePath.
SetUp()
void TestHTTPDirectory::SetUp () inline override protected
References m_vfsHandler, m_webServer, m_webServerPort, CWebServer::RegisterRequestHandler(), SetupMediaSources(), and CWebServer::Start().
SetupMediaSources()
void TestHTTPDirectory::SetupMediaSources () inline protected
References CMediaSourceSettings::AddShare(), CMediaSourceSettings::GetInstance(), LOCK_MODE_EVERYONE, CMediaSource::m_allowSharing, CMediaSource::m_iDriveType, CMediaSource::m_ignore, CMediaSource::m_iLockMode, m_sourcePath, CMediaSource::SOURCE_TYPE_LOCAL, CMediaSource::strName, CMediaSource::strPath, and CMediaSource::vecPaths.
Referenced by SetUp().
TearDown()
void TestHTTPDirectory::TearDown () inline override protected
References CWebServer::IsStarted(), m_vfsHandler, m_webServer, CWebServer::Stop(), TearDownMediaSources(), and CWebServer::UnregisterRequestHandler().
TearDownMediaSources()
void TestHTTPDirectory::TearDownMediaSources () inline protected
References CMediaSourceSettings::Clear(), and CMediaSourceSettings::GetInstance().
Referenced by TearDown().
Member Data Documentation
m_baseUrl
std::string TestHTTPDirectory::m_baseUrl protected
Referenced by GetUrl(), and TestHTTPDirectory().
m_httpDirectory
CHTTPDirectory TestHTTPDirectory::m_httpDirectory protected
m_sourcePath
std::string const TestHTTPDirectory::m_sourcePath protected
Referenced by GetUrlOfTestFile(), and SetupMediaSources().
m_vfsHandler
CHTTPVfsHandler TestHTTPDirectory::m_vfsHandler protected
Referenced by SetUp(), and TearDown().
m_webServer
CWebServer TestHTTPDirectory::m_webServer protected
Referenced by SetUp(), and TearDown().
m_webServerPort
uint16_t TestHTTPDirectory::m_webServerPort protected
Referenced by SetUp(), and TestHTTPDirectory().
The documentation for this class was generated from the following file:
TestHTTPDirectory.cpp