Kodi Documentation: CGUIAudioManager Class Reference
CGUIAudioManager Class Reference
#include <GUIAudioManager.h>
Classes
class CWindowSounds
struct IAESoundDeleter
Public Member Functions
CGUIAudioManager ()
~CGUIAudioManager () override
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode) override
The given setting needs to be updated.
void Initialize ()
void DeInitialize ()
bool Load ()
void UnLoad ()
void PlayActionSound (const CAction &action)
void PlayWindowSound (int id, WINDOW_SOUND event)
void PlayPythonSound (const std::string &strFileName, bool useCached=true)
void Enable (bool bEnable)
void SetVolume (float level)
void Stop ()
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingAction (const std::shared_ptr< const CSetting > &setting)
The given setting has been activated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Private Types
typedef std::map< const std::string, std::weak_ptr< IAESound > > soundCache
typedef std::map< int, std::shared_ptr< IAESound > > actionSoundMap
typedef std::map< int, CWindowSounds > windowSoundMap
typedef std::map< const std::string, std::shared_ptr< IAESound > > pythonSoundsMap
Private Member Functions
std::shared_ptr< IAESound > LoadSound (const std::string &filename)
std::shared_ptr< IAESound > LoadWindowSound (TiXmlNode *pWindowNode, const std::string &strIdentifier)
Private Attributes
std::shared_ptr< CSettings > m_settings
soundCache m_soundCache
actionSoundMap m_actionSoundMap
windowSoundMap m_windowSoundMap
pythonSoundsMap m_pythonSounds
std::string m_strMediaDir
bool m_bEnabled
CCriticalSection m_cs
Member Typedef Documentation
actionSoundMap
typedef std::map<int, std::shared_ptr<IAESound> > CGUIAudioManager::actionSoundMap private
pythonSoundsMap
typedef std::map<const std::string, std::shared_ptr<IAESound> > CGUIAudioManager::pythonSoundsMap private
soundCache
typedef std::map<const std::string, std::weak_ptr<IAESound> > CGUIAudioManager::soundCache private
windowSoundMap
typedef std::map<int, CWindowSounds> CGUIAudioManager::windowSoundMap private
Constructor & Destructor Documentation
CGUIAudioManager()
CGUIAudioManager::CGUIAudioManager ()
References m_bEnabled, m_settings, CSettings::SETTING_AUDIOOUTPUT_GUISOUNDVOLUME, and CSettings::SETTING_LOOKANDFEEL_SOUNDSKIN.
~CGUIAudioManager()
CGUIAudioManager::~CGUIAudioManager () override
References m_settings.
Member Function Documentation
DeInitialize()
void CGUIAudioManager::DeInitialize ()
References m_cs, and UnLoad().
Referenced by CApplication::Stop().
Enable()
void CGUIAudioManager::Enable (bool bEnable)
References CServiceBroker::GetSettingsComponent(), m_bEnabled, m_cs, and CSettings::SETTING_LOOKANDFEEL_SOUNDSKIN.
Referenced by XBMCAddon::xbmc::enableNavSounds(), CApplicationSkinHandling::LoadSkin(), CApplication::OnAction(), CApplication::PlaybackCleanup(), CApplication::PlayFile(), and CApplicationSkinHandling::UnloadSkin().
Initialize()
void CGUIAudioManager::Initialize ()
Load()
bool CGUIAudioManager::Load ()
References ACTION_NONE, URIUtils::AddFileToFolder(), CGUIAudioManager::CWindowSounds::deInitSound, Enable, GetSoundSkinPath(), CGUIAudioManager::CWindowSounds::initSound, CXBMCTinyXML::LoadFile(), LoadSound(), LoadWindowSound(), CLog::Log(), LOGINFO, m_actionSoundMap, m_cs, m_strMediaDir, m_windowSoundMap, KODI::ACTION::CActionTranslator::TranslateString(), CWindowTranslator::TranslateWindow(), and UnLoad().
Referenced by CApplicationSkinHandling::LoadSkin(), ADDON::CUISoundsResource::OnPostInstall(), and OnSettingChanged().
LoadSound()
std::shared_ptr< IAESound > CGUIAudioManager::LoadSound (const std::string & filename) private
References CServiceBroker::GetActiveAE(), m_cs, m_soundCache, and IAE::MakeSound().
Referenced by Load(), LoadWindowSound(), and PlayPythonSound().
LoadWindowSound()
std::shared_ptr< IAESound > CGUIAudioManager::LoadWindowSound (TiXmlNode * pWindowNode, const std::string & strIdentifier) private
References URIUtils::AddFileToFolder(), LoadSound(), and m_strMediaDir.
Referenced by Load().
OnSettingChanged()
void CGUIAudioManager::OnSettingChanged (const std::shared_ptr< const CSetting > & setting) override virtual
The value of the given setting has changed.
This callback is triggered whenever the value of a setting has been successfully changed (i.e. none of the OnSettingChanging() handlers) has reverted the change.
Parameters
setting The setting whose value has been changed
Reimplemented from ISettingCallback.
References Enable, Load(), and CSettings::SETTING_LOOKANDFEEL_SOUNDSKIN.
OnSettingUpdate()
bool CGUIAudioManager::OnSettingUpdate (const std::shared_ptr< CSetting > & setting, const char * oldSettingId, const TiXmlNode * oldSettingNode) override virtual
The given setting needs to be updated.
This callback is triggered when a setting needs to be updated because its value is outdated. This only happens when initially loading the value of a setting and will not be triggered afterwards.
Parameters
setting The setting which needs to be updated.
oldSettingId The id of the previous setting.
oldSettingNode The old setting node
Returns
True if the setting has been successfully updated otherwise false
Reimplemented from ISettingCallback.
References GetValue(), m_settings, CSettings::SETTING_AUDIOOUTPUT_GUISOUNDVOLUME, CSettings::SETTING_LOOKANDFEEL_SOUNDSKIN, and SetVolume().
PlayActionSound()
void CGUIAudioManager::PlayActionSound (const CAction & action)
References m_actionSoundMap, m_bEnabled, m_cs, m_settings, and CSettings::SETTING_AUDIOOUTPUT_GUISOUNDVOLUME.
Referenced by CInputManager::ExecuteInputAction(), EVENTSERVER::CEventServer::ExecuteNextAction(), and JSONRPC::CInputOperations::SendAction().
PlayPythonSound()
void CGUIAudioManager::PlayPythonSound (const std::string & strFileName, bool useCached = true)
References LoadSound(), m_bEnabled, m_cs, m_pythonSounds, m_settings, and CSettings::SETTING_AUDIOOUTPUT_GUISOUNDVOLUME.
Referenced by XBMCAddon::xbmc::playSFX().
PlayWindowSound()
void CGUIAudioManager::PlayWindowSound (int id, WINDOW_SOUND event)
References m_bEnabled, m_cs, m_settings, m_windowSoundMap, CSettings::SETTING_AUDIOOUTPUT_GUISOUNDVOLUME, SOUND_DEINIT, and SOUND_INIT.
Referenced by CGUIWindow::Close_Internal(), KODI::JOYSTICK::CJoystickEasterEgg::OnFinish(), and CGUIWindow::OnInitWindow().
SetVolume()
void CGUIAudioManager::SetVolume (float level)
References m_actionSoundMap, m_cs, m_pythonSounds, and m_windowSoundMap.
Referenced by OnSettingUpdate().
Stop()
void CGUIAudioManager::Stop ()
References m_cs, m_pythonSounds, and m_windowSoundMap.
Referenced by XBMCAddon::xbmc::stopSFX().
UnLoad()
void CGUIAudioManager::UnLoad ()
References m_actionSoundMap, m_pythonSounds, m_soundCache, and m_windowSoundMap.
Referenced by DeInitialize(), and Load().
Member Data Documentation
m_actionSoundMap
actionSoundMap CGUIAudioManager::m_actionSoundMap private
Referenced by Load(), PlayActionSound(), SetVolume(), and UnLoad().
m_bEnabled
bool CGUIAudioManager::m_bEnabled private
Referenced by CGUIAudioManager(), Enable(), PlayActionSound(), PlayPythonSound(), and PlayWindowSound().
m_cs
CCriticalSection CGUIAudioManager::m_cs private
Referenced by DeInitialize(), Enable(), Load(), LoadSound(), PlayActionSound(), PlayPythonSound(), PlayWindowSound(), SetVolume(), and Stop().
m_pythonSounds
pythonSoundsMap CGUIAudioManager::m_pythonSounds private
Referenced by PlayPythonSound(), SetVolume(), Stop(), and UnLoad().
m_settings
std::shared_ptr<CSettings> CGUIAudioManager::m_settings private
Referenced by CGUIAudioManager(), OnSettingUpdate(), PlayActionSound(), PlayPythonSound(), PlayWindowSound(), and ~CGUIAudioManager().
m_soundCache
soundCache CGUIAudioManager::m_soundCache private
Referenced by LoadSound(), and UnLoad().
m_strMediaDir
std::string CGUIAudioManager::m_strMediaDir private
Referenced by Load(), and LoadWindowSound().
m_windowSoundMap
windowSoundMap CGUIAudioManager::m_windowSoundMap private
Referenced by Load(), PlayWindowSound(), SetVolume(), Stop(), and UnLoad().
The documentation for this class was generated from the following files:
GUIAudioManager.h
GUIAudioManager.cpp