Kodi Documentation: CMusicDbUrl Class Reference
CMusicDbUrl Class Reference
#include <MusicDbUrl.h>
Public Member Functions
CMusicDbUrl ()
~CMusicDbUrl () override
Public Member Functions inherited from CDbUrl
CDbUrl ()
~CDbUrl () override
bool IsValid () const
void Reset ()
std::string ToString () const
bool FromString (const std::string &dbUrl)
const std::string & GetType () const
void AppendPath (const std::string &subPath)
void AddOption (const std::string &key, const char *value) override
void AddOption (const std::string &key, const std::string &value) override
void AddOption (const std::string &key, int value) override
void AddOption (const std::string &key, float value) override
void AddOption (const std::string &key, double value) override
void AddOption (const std::string &key, bool value) override
void AddOptions (const std::string &options) override
void RemoveOption (const std::string &key) override
bool GetOption (const std::string &key, CVariant &value) const
const UrlOptions & GetOptions () const
std::string GetOptionsString (bool withLeadingSeparator=false) const
bool HasOption (const std::string &key) const
Protected Member Functions
bool parse () override
bool validateOption (const std::string &key, const CVariant &value) override
Additional Inherited Members
Protected Attributes inherited from CDbUrl
CURL m_url
std::string m_type
Constructor & Destructor Documentation
CMusicDbUrl()
CMusicDbUrl::CMusicDbUrl ()
~CMusicDbUrl()
CMusicDbUrl::~CMusicDbUrl () override default
Member Function Documentation
parse()
bool CMusicDbUrl::parse () override protected virtual
Implements CDbUrl.
References CDbUrl::AddOption(), CDbUrl::AddOptions(), CURL::Get(), XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetAlbumId(), XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetArtistId(), XFILE::CMusicDatabaseDirectory::GetDirectoryNodeInfo(), CURL::GetFileName(), XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetGenreId(), CURL::GetOptions(), XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetSongId(), XFILE::MUSICDATABASEDIRECTORY::CQueryParams::GetYear(), CURL::IsProtocol(), CDbUrl::m_type, CDbUrl::m_url, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_ADDED, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_ADDED_SONGS, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_PLAYED, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_RECENTLY_PLAYED_SONGS, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_TOP100, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ALBUM_TOP100_SONGS, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ARTIST, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_DISC, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_GENRE, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_OVERVIEW, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ROLE, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_ROOT, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SINGLES, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SONG, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SONG_TOP100, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_SOURCE, XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_TOP100, and XFILE::MUSICDATABASEDIRECTORY::NODE_TYPE_YEAR.
validateOption()
bool CMusicDbUrl::validateOption (const std::string & key, const CVariant & value) override protected virtual
Reimplemented from CDbUrl.
References KODI::PLAYLIST::CSmartPlaylist::GetType(), KODI::PLAYLIST::CSmartPlaylist::LoadFromJson(), CDbUrl::m_type, CDbUrl::validateOption(), and value.
The documentation for this class was generated from the following files:
MusicDbUrl.h
MusicDbUrl.cpp