Kodi Documentation: AudioClassifyTest Struct Reference
AudioClassifyTest Struct Reference
Public Member Functions
AudioClassifyTest (const std::string &path, bool res=true, const std::string &mime="", int tag_type=0)
Public Attributes
CFileItem item
bool result
Constructor & Destructor Documentation
AudioClassifyTest()
AudioClassifyTest::AudioClassifyTest (const std::string & path, bool res = true, const std::string & mime = "", int tag_type = 0) inline
References CFileItem::GetGameInfoTag(), CFileItem::GetMusicInfoTag(), CFileItem::GetPictureInfoTag(), CFileItem::GetVideoInfoTag(), item, CVideoInfoTag::m_strFileNameAndPath, KODI::GAME::CGameInfoTag::SetGameClient(), CPictureInfoTag::SetInfo(), CFileItem::SetMimeType(), and MUSIC_INFO::CMusicInfoTag::SetPlayCount().
Member Data Documentation
item
CFileItem AudioClassifyTest::item
Referenced by AudioClassifyTest().
result
bool AudioClassifyTest::result
The documentation for this struct was generated from the following file:
TestMusicFileItemClassify.cpp