Kodi Documentation: KODI::RETRO::CRenderContext Class Reference
KODI::RETRO::CRenderContext Class Reference
#include <RenderContext.h>
Public Member Functions
CRenderContext (CRenderSystemBase *rendering, CWinSystemBase *windowing, CGraphicContext &graphicsContext, CDisplaySettings &displaySettings, CMediaSettings &mediaSettings, GAME::CGameServices &gameServices, CGUIComponent *guiComponent)
CRenderSystemBase * Rendering ()
CWinSystemBase * Windowing ()
CGraphicContext & GraphicsContext ()
CGUIComponent * GUI ()
void SetViewPort (const CRect &viewPort)
void GetViewPort (CRect &viewPort)
void SetScissors (const CRect &rect)
void ApplyStateBlock ()
bool IsExtSupported (const char *extension)
void EnableGUIShader (GL_SHADER_METHOD method)
void DisableGUIShader ()
int GUIShaderGetPos ()
int GUIShaderGetCoord0 ()
int GUIShaderGetUniCol ()
int GUIShaderGetDepth ()
CGUIShaderDX * GetGUIShader ()
bool UseLimitedColor ()
bool DisplayHardwareScalingEnabled ()
void UpdateDisplayHardwareScaling (const RESOLUTION_INFO &resInfo)
int GetScreenWidth ()
int GetScreenHeight ()
const CRect & GetScissors ()
CRect GetViewWindow ()
void SetViewWindow (float left, float top, float right, float bottom)
void SetFullScreenVideo (bool bOnOff)
bool IsFullScreenVideo ()
bool IsCalibrating ()
RESOLUTION GetVideoResolution ()
void Clear (UTILS::COLOR::Color color)
RESOLUTION_INFO GetResInfo ()
void SetRenderingResolution (const RESOLUTION_INFO &res, bool needsScaling)
UTILS::COLOR::Color MergeAlpha (UTILS::COLOR::Color color)
void SetTransform (const TransformMatrix &matrix, float scaleX, float scaleY)
void RemoveTransform ()
CRect StereoCorrection (const CRect &rect)
CCriticalSection & GraphicsMutex ()
RESOLUTION_INFO & GetResolutionInfo (RESOLUTION resolution)
::CGameSettings & GetGameSettings ()
::CGameSettings & GetDefaultGameSettings ()
void StartAgentInput (GAME::GameClientPtr gameClient)
void StopAgentInput ()
Private Attributes
CRenderSystemBase *const m_rendering
CWinSystemBase *const m_windowing
CGraphicContext & m_graphicsContext
CDisplaySettings & m_displaySettings
CMediaSettings & m_mediaSettings
GAME::CGameServices & m_gameServices
CGUIComponent *const m_guiComponent
Constructor & Destructor Documentation
CRenderContext()
CRenderContext::CRenderContext (CRenderSystemBase * rendering, CWinSystemBase * windowing, CGraphicContext & graphicsContext, CDisplaySettings & displaySettings, CMediaSettings & mediaSettings, GAME::CGameServices & gameServices, CGUIComponent * guiComponent)
Member Function Documentation
ApplyStateBlock()
void CRenderContext::ApplyStateBlock ()
References CRenderSystemBase::ApplyStateBlock(), and m_rendering.
Referenced by KODI::RETRO::CRPBaseRenderer::PostRender().
Clear()
void CRenderContext::Clear (UTILS::COLOR::Color color)
References CGraphicContext::Clear(), color, and m_graphicsContext.
Referenced by KODI::RETRO::CRPRenderManager::ClearBackground(), KODI::RETRO::CRPBaseRenderer::PreRender(), and KODI::RETRO::CRPRenderManager::RenderControl().
DisableGUIShader()
void CRenderContext::DisableGUIShader ()
References CRenderSystemGLES::DisableGUIShader(), CRenderSystemGL::DisableShader(), and m_rendering.
Referenced by KODI::RETRO::CRPRendererOpenGL::CRPRendererOpenGL(), KODI::RETRO::CRPRendererOpenGL::DrawBlackBars(), KODI::RETRO::CRPRendererOpenGLES::DrawBlackBars(), KODI::RETRO::CRPRendererOpenGL::Render(), KODI::RETRO::CRPRendererOpenGLES::Render(), KODI::RETRO::CRPRendererDMA::Render(), and KODI::RETRO::CRPRendererGuiTexture::RenderInternal().
DisplayHardwareScalingEnabled()
bool CRenderContext::DisplayHardwareScalingEnabled ()
References CWinSystemBase::DisplayHardwareScalingEnabled(), and m_windowing.
Referenced by KODI::RETRO::CRPBaseRenderer::ManageRenderArea(), and KODI::RETRO::CRPRenderManager::RenderWindow().
EnableGUIShader()
void CRenderContext::EnableGUIShader (GL_SHADER_METHOD method)
References CRenderSystemGLES::EnableGUIShader(), CRenderSystemGL::EnableShader(), and m_rendering.
Referenced by KODI::RETRO::CRPRendererOpenGL::CRPRendererOpenGL(), KODI::RETRO::CRPRendererOpenGL::DrawBlackBars(), KODI::RETRO::CRPRendererOpenGLES::DrawBlackBars(), KODI::RETRO::CRPRendererOpenGL::Render(), KODI::RETRO::CRPRendererOpenGLES::Render(), KODI::RETRO::CRPRendererDMA::Render(), and KODI::RETRO::CRPRendererGuiTexture::RenderInternal().
GetDefaultGameSettings()
CGameSettings & CRenderContext::GetDefaultGameSettings ()
References CMediaSettings::GetDefaultGameSettings(), and m_mediaSettings.
Referenced by KODI::RETRO::CGUIGameSettings::CGUIGameSettings().
GetGameSettings()
CGameSettings & CRenderContext::GetGameSettings ()
References CMediaSettings::GetCurrentGameSettings(), and m_mediaSettings.
GetGUIShader()
CGUIShaderDX * CRenderContext::GetGUIShader ()
References CRenderSystemDX::GetGUIShader(), and m_rendering.
Referenced by KODI::RETRO::CRPRendererGuiTexture::RenderInternal().
GetResInfo()
RESOLUTION_INFO CRenderContext::GetResInfo ()
References CGraphicContext::GetResInfo(), and m_graphicsContext.
Referenced by KODI::RETRO::CRPBaseRenderer::GetScreenDimensions(), and KODI::RETRO::CRPRenderManager::RenderWindow().
GetResolutionInfo()
RESOLUTION_INFO & CRenderContext::GetResolutionInfo (RESOLUTION resolution)
References CDisplaySettings::GetResolutionInfo(), and m_displaySettings.
GetScissors()
const CRect & CRenderContext::GetScissors ()
References CGraphicContext::GetScissors(), and m_graphicsContext.
Referenced by KODI::RETRO::CRPRenderManager::RenderControl().
GetScreenHeight()
int CRenderContext::GetScreenHeight ()
References CGraphicContext::GetHeight(), and m_graphicsContext.
Referenced by KODI::RETRO::CRPRendererOpenGL::DrawBlackBars(), and KODI::RETRO::CRPRendererOpenGLES::DrawBlackBars().
GetScreenWidth()
int CRenderContext::GetScreenWidth ()
References CGraphicContext::GetWidth(), and m_graphicsContext.
Referenced by KODI::RETRO::CRPRendererOpenGL::DrawBlackBars(), and KODI::RETRO::CRPRendererOpenGLES::DrawBlackBars().
GetVideoResolution()
RESOLUTION CRenderContext::GetVideoResolution ()
References CGraphicContext::GetVideoResolution(), and m_graphicsContext.
Referenced by KODI::RETRO::CRPRenderManager::RenderWindow().
GetViewPort()
void CRenderContext::GetViewPort (CRect & viewPort)
References CRenderSystemBase::GetViewPort(), and m_rendering.
Referenced by KODI::RETRO::CRPWinRenderer::Render().
GetViewWindow()
CRect CRenderContext::GetViewWindow ()
References CGraphicContext::GetViewWindow(), and m_graphicsContext.
Referenced by KODI::RETRO::CRPBaseRenderer::ManageRenderArea().
GraphicsContext()
CGraphicContext & KODI::RETRO::CRenderContext::GraphicsContext () inline
References m_graphicsContext.
GraphicsMutex()
CCriticalSection & CRenderContext::GraphicsMutex ()
References m_graphicsContext.
Referenced by KODI::RETRO::CRPRenderManager::RenderInternal().
GUI()
CGUIComponent * KODI::RETRO::CRenderContext::GUI () inline
References m_guiComponent.
GUIShaderGetCoord0()
int CRenderContext::GUIShaderGetCoord0 ()
References CRenderSystemGLES::GUIShaderGetCoord0(), m_rendering, and CRenderSystemGL::ShaderGetCoord0().
Referenced by KODI::RETRO::CRPRendererOpenGL::CRPRendererOpenGL(), KODI::RETRO::CRPRendererOpenGLES::Render(), KODI::RETRO::CRPRendererDMA::Render(), and KODI::RETRO::CRPRendererGuiTexture::RenderInternal().
GUIShaderGetDepth()
int CRenderContext::GUIShaderGetDepth ()
References CRenderSystemGLES::GUIShaderGetDepth(), m_rendering, and CRenderSystemGL::ShaderGetDepth().
Referenced by KODI::RETRO::CRPRendererOpenGLES::DrawBlackBars(), KODI::RETRO::CRPRendererOpenGL::Render(), KODI::RETRO::CRPRendererOpenGLES::Render(), KODI::RETRO::CRPRendererDMA::Render(), and KODI::RETRO::CRPRendererGuiTexture::RenderInternal().
GUIShaderGetPos()
int CRenderContext::GUIShaderGetPos ()
References CRenderSystemGLES::GUIShaderGetPos(), m_rendering, and CRenderSystemGL::ShaderGetPos().
Referenced by KODI::RETRO::CRPRendererOpenGL::CRPRendererOpenGL(), KODI::RETRO::CRPRendererOpenGLES::DrawBlackBars(), KODI::RETRO::CRPRendererOpenGLES::Render(), KODI::RETRO::CRPRendererDMA::Render(), and KODI::RETRO::CRPRendererGuiTexture::RenderInternal().
GUIShaderGetUniCol()
int CRenderContext::GUIShaderGetUniCol ()
References CRenderSystemGLES::GUIShaderGetUniCol(), m_rendering, and CRenderSystemGL::ShaderGetUniCol().
Referenced by KODI::RETRO::CRPRendererOpenGL::DrawBlackBars(), KODI::RETRO::CRPRendererOpenGLES::DrawBlackBars(), KODI::RETRO::CRPRendererOpenGL::Render(), KODI::RETRO::CRPRendererOpenGLES::Render(), KODI::RETRO::CRPRendererDMA::Render(), and KODI::RETRO::CRPRendererGuiTexture::RenderInternal().
IsCalibrating()
bool CRenderContext::IsCalibrating ()
References CGraphicContext::IsCalibrating(), and m_graphicsContext.
Referenced by KODI::RETRO::CRPBaseRenderer::ManageRenderArea().
IsExtSupported()
bool CRenderContext::IsExtSupported (const char * extension)
References CRenderSystemBase::IsExtSupported(), and m_rendering.
Referenced by KODI::RETRO::CRenderBufferPoolOpenGLES::ConfigureInternal(), and KODI::RETRO::CRenderBufferOpenGLES::UploadTexture().
IsFullScreenVideo()
bool CRenderContext::IsFullScreenVideo ()
References CGraphicContext::IsFullScreenVideo(), and m_graphicsContext.
Referenced by KODI::RETRO::CRPBaseRenderer::ManageRenderArea(), and KODI::RETRO::CRPRenderManager::RenderControl().
MergeAlpha()
UTILS::COLOR::Color CRenderContext::MergeAlpha (UTILS::COLOR::Color color)
References color, m_graphicsContext, and CGraphicContext::MergeAlpha().
Referenced by KODI::RETRO::CRPRenderManager::RenderControl().
RemoveTransform()
void CRenderContext::RemoveTransform ()
References m_graphicsContext, and CGraphicContext::RemoveTransform().
Referenced by KODI::RETRO::CRPRenderManager::RenderControl().
Rendering()
CRenderSystemBase * KODI::RETRO::CRenderContext::Rendering () inline
References m_rendering.
Referenced by KODI::RETRO::CRPWinRenderer::ConfigureInternal(), and KODI::RETRO::CRPWinRenderer::RenderInternal().
SetFullScreenVideo()
void CRenderContext::SetFullScreenVideo (bool bOnOff)
References m_graphicsContext, and CGraphicContext::SetFullScreenVideo().
Referenced by KODI::RETRO::CRPRenderManager::RenderControl().
SetRenderingResolution()
void CRenderContext::SetRenderingResolution (const RESOLUTION_INFO & res, bool needsScaling)
References m_graphicsContext, and CGraphicContext::SetRenderingResolution().
Referenced by KODI::RETRO::CRPRenderManager::RenderWindow().
SetScissors()
void CRenderContext::SetScissors (const CRect & rect)
References m_rendering, and CRenderSystemBase::SetScissors().
Referenced by KODI::RETRO::CRPRenderManager::RenderControl().
SetTransform()
void CRenderContext::SetTransform (const TransformMatrix & matrix, float scaleX, float scaleY)
References m_graphicsContext, and CGraphicContext::SetTransform().
Referenced by KODI::RETRO::CRPRenderManager::RenderControl().
SetViewPort()
void CRenderContext::SetViewPort (const CRect & viewPort)
References m_rendering, and CRenderSystemBase::SetViewPort().
SetViewWindow()
void CRenderContext::SetViewWindow (float left, float top, float right, float bottom)
References left, m_graphicsContext, right, and CGraphicContext::SetViewWindow().
Referenced by KODI::RETRO::CRPRenderManager::RenderControl().
StartAgentInput()
void CRenderContext::StartAgentInput (GAME::GameClientPtr gameClient)
References KODI::GAME::CGameServices::AgentInput(), m_gameServices, and KODI::GAME::CAgentInput::Start().
Referenced by KODI::RETRO::CRetroPlayerInput::StartAgentManager().
StereoCorrection()
CRect CRenderContext::StereoCorrection (const CRect & rect)
References m_graphicsContext, and CGraphicContext::StereoCorrection().
StopAgentInput()
void CRenderContext::StopAgentInput ()
References KODI::GAME::CGameServices::AgentInput(), m_gameServices, and KODI::GAME::CAgentInput::Stop().
Referenced by KODI::RETRO::CRetroPlayerInput::StopAgentManager().
UpdateDisplayHardwareScaling()
void CRenderContext::UpdateDisplayHardwareScaling (const RESOLUTION_INFO & resInfo)
References m_windowing, and CWinSystemBase::UpdateDisplayHardwareScaling().
Referenced by KODI::RETRO::CRPRenderManager::RenderWindow().
UseLimitedColor()
bool CRenderContext::UseLimitedColor ()
References m_windowing, and CWinSystemBase::UseLimitedColor().
Referenced by KODI::RETRO::CRPRendererOpenGL::CRPRendererOpenGL(), KODI::RETRO::CRPBaseRenderer::PreRender(), KODI::RETRO::CRPWinRenderer::Render(), and KODI::RETRO::CRPRendererGuiTexture::RenderInternal().
Windowing()
CWinSystemBase * KODI::RETRO::CRenderContext::Windowing () inline
References m_windowing.
Member Data Documentation
m_displaySettings
CDisplaySettings& KODI::RETRO::CRenderContext::m_displaySettings private
Referenced by GetResolutionInfo().
m_gameServices
GAME::CGameServices& KODI::RETRO::CRenderContext::m_gameServices private
Referenced by StartAgentInput(), and StopAgentInput().
m_graphicsContext
CGraphicContext& KODI::RETRO::CRenderContext::m_graphicsContext private
Referenced by Clear(), GetResInfo(), GetScissors(), GetScreenHeight(), GetScreenWidth(), GetVideoResolution(), GetViewWindow(), GraphicsContext(), GraphicsMutex(), IsCalibrating(), IsFullScreenVideo(), MergeAlpha(), RemoveTransform(), SetFullScreenVideo(), SetRenderingResolution(), SetTransform(), SetViewWindow(), and StereoCorrection().
m_guiComponent
CGUIComponent* const KODI::RETRO::CRenderContext::m_guiComponent private
Referenced by GUI().
m_mediaSettings
CMediaSettings& KODI::RETRO::CRenderContext::m_mediaSettings private
Referenced by GetDefaultGameSettings(), and GetGameSettings().
m_rendering
CRenderSystemBase* const KODI::RETRO::CRenderContext::m_rendering private
Referenced by ApplyStateBlock(), DisableGUIShader(), EnableGUIShader(), GetGUIShader(), GetViewPort(), GUIShaderGetCoord0(), GUIShaderGetDepth(), GUIShaderGetPos(), GUIShaderGetUniCol(), IsExtSupported(), Rendering(), SetScissors(), and SetViewPort().
m_windowing
CWinSystemBase* const KODI::RETRO::CRenderContext::m_windowing private
Referenced by DisplayHardwareScalingEnabled(), UpdateDisplayHardwareScaling(), UseLimitedColor(), and Windowing().
The documentation for this class was generated from the following files:
cores/RetroPlayer/rendering/RenderContext.h
RenderContext.cpp