Kodi Documentation: PVR::CPVRTimerSettingDefinition Class Reference
PVR::CPVRTimerSettingDefinition Class Reference
#include <PVRTimerSettingDefinition.h>
Public Member Functions
CPVRTimerSettingDefinition (int clientId, unsigned int timerTypeId, const PVR_SETTING_DEFINITION &def)
virtual ~CPVRTimerSettingDefinition ()=default
bool operator== (const CPVRTimerSettingDefinition &right) const
bool operator!= (const CPVRTimerSettingDefinition &right) const
int GetClientId () const
unsigned int GetTimerTypeId () const
unsigned int GetId () const
const std::string & GetName () const
PVR_SETTING_TYPE GetType () const
CVariant GetDefaultValue () const
bool IsIntDefinition () const
bool IsStringDefinition () const
const CPVRIntSettingDefinition & GetIntDefinition () const
const CPVRStringSettingDefinition & GetStringDefinition () const
bool IsReadonlyForTimerState (PVR_TIMER_STATE timerState) const
Static Public Member Functions
static std::vector< std::shared_ptr< const CPVRTimerSettingDefinition > > CreateSettingDefinitionsList (int clientId, unsigned int timerTypeId, struct PVR_SETTING_DEFINITION **defs, unsigned int settingDefsSize)
Private Attributes
int m_clientId {PVR_CLIENT_INVALID_UID}
unsigned int m_timerTypeId {PVR_TIMER_TYPE_NONE}
unsigned int m_id {0}
std::string m_name
PVR_SETTING_TYPE m_type {PVR_SETTING_TYPE::INTEGER}
uint64_t m_readonlyConditions {PVR_SETTING_READONLY_CONDITION_NONE}
CPVRIntSettingDefinition m_intDefinition
CPVRStringSettingDefinition m_stringDefinition
Constructor & Destructor Documentation
CPVRTimerSettingDefinition()
PVR::CPVRTimerSettingDefinition::CPVRTimerSettingDefinition (int clientId, unsigned int timerTypeId, const PVR_SETTING_DEFINITION & def)
References PVR_SETTING_DEFINITION::intSettingDefinition, m_intDefinition, m_stringDefinition, and PVR_SETTING_DEFINITION::stringSettingDefinition.
~CPVRTimerSettingDefinition()
virtual PVR::CPVRTimerSettingDefinition::~CPVRTimerSettingDefinition () virtual default
Member Function Documentation
CreateSettingDefinitionsList()
std::vector< std::shared_ptr< const CPVRTimerSettingDefinition > > PVR::CPVRTimerSettingDefinition::CreateSettingDefinitionsList (int clientId, unsigned int timerTypeId, struct PVR_SETTING_DEFINITION ** defs, unsigned int settingDefsSize) static
Referenced by PVR::CPVRTimerType::InitCustomSettingDefinitions().
GetClientId()
int PVR::CPVRTimerSettingDefinition::GetClientId () const inline
References m_clientId.
GetDefaultValue()
CVariant PVR::CPVRTimerSettingDefinition::GetDefaultValue () const
References PVR::CPVRIntSettingDefinition::GetDefaultValue(), PVR::CPVRStringSettingDefinition::GetDefaultValue(), GetIntDefinition(), GetStringDefinition(), GetType(), and LOGERROR.
GetId()
unsigned int PVR::CPVRTimerSettingDefinition::GetId () const inline
References m_id.
GetIntDefinition()
const CPVRIntSettingDefinition & PVR::CPVRTimerSettingDefinition::GetIntDefinition () const inline
References m_intDefinition.
Referenced by GetDefaultValue().
GetName()
const std::string & PVR::CPVRTimerSettingDefinition::GetName () const inline
References m_name.
GetStringDefinition()
const CPVRStringSettingDefinition & PVR::CPVRTimerSettingDefinition::GetStringDefinition () const inline
References m_stringDefinition.
Referenced by GetDefaultValue().
GetTimerTypeId()
unsigned int PVR::CPVRTimerSettingDefinition::GetTimerTypeId () const inline
References m_timerTypeId.
GetType()
PVR_SETTING_TYPE PVR::CPVRTimerSettingDefinition::GetType () const inline
References m_type.
Referenced by GetDefaultValue().
IsIntDefinition()
bool PVR::CPVRTimerSettingDefinition::IsIntDefinition () const inline
References m_type.
IsReadonlyForTimerState()
bool PVR::CPVRTimerSettingDefinition::IsReadonlyForTimerState (PVR_TIMER_STATE timerState) const
References LOGWARNING, m_readonlyConditions, PVR_SETTING_READONLY_CONDITION_TIMER_COMPLETED, PVR_SETTING_READONLY_CONDITION_TIMER_DISABLED, PVR_SETTING_READONLY_CONDITION_TIMER_RECORDING, PVR_SETTING_READONLY_CONDITION_TIMER_SCHEDULED, PVR_TIMER_STATE_ABORTED, PVR_TIMER_STATE_CANCELLED, PVR_TIMER_STATE_COMPLETED, PVR_TIMER_STATE_CONFLICT_NOK, PVR_TIMER_STATE_CONFLICT_OK, PVR_TIMER_STATE_DISABLED, PVR_TIMER_STATE_ERROR, PVR_TIMER_STATE_RECORDING, and PVR_TIMER_STATE_SCHEDULED.
IsStringDefinition()
bool PVR::CPVRTimerSettingDefinition::IsStringDefinition () const inline
References m_type.
operator!=()
bool PVR::CPVRTimerSettingDefinition::operator!= (const CPVRTimerSettingDefinition & right) const
References right.
operator==()
bool PVR::CPVRTimerSettingDefinition::operator== (const CPVRTimerSettingDefinition & right) const
References m_id, m_intDefinition, m_name, m_readonlyConditions, m_stringDefinition, m_type, and right.
Member Data Documentation
m_clientId
int PVR::CPVRTimerSettingDefinition::m_clientId {PVR_CLIENT_INVALID_UID} private
Referenced by GetClientId().
m_id
unsigned int PVR::CPVRTimerSettingDefinition::m_id {0} private
Referenced by GetId(), and operator==().
m_intDefinition
CPVRIntSettingDefinition PVR::CPVRTimerSettingDefinition::m_intDefinition private
Referenced by CPVRTimerSettingDefinition(), GetIntDefinition(), and operator==().
m_name
std::string PVR::CPVRTimerSettingDefinition::m_name private
Referenced by GetName(), and operator==().
m_readonlyConditions
uint64_t PVR::CPVRTimerSettingDefinition::m_readonlyConditions {PVR_SETTING_READONLY_CONDITION_NONE} private
Referenced by IsReadonlyForTimerState(), and operator==().
m_stringDefinition
CPVRStringSettingDefinition PVR::CPVRTimerSettingDefinition::m_stringDefinition private
Referenced by CPVRTimerSettingDefinition(), GetStringDefinition(), and operator==().
m_timerTypeId
unsigned int PVR::CPVRTimerSettingDefinition::m_timerTypeId {PVR_TIMER_TYPE_NONE} private
Referenced by GetTimerTypeId().
m_type
PVR_SETTING_TYPE PVR::CPVRTimerSettingDefinition::m_type {PVR_SETTING_TYPE::INTEGER} private
Referenced by GetType(), IsIntDefinition(), IsStringDefinition(), and operator==().
The documentation for this class was generated from the following files:
PVRTimerSettingDefinition.h
PVRTimerSettingDefinition.cpp