Kodi Documentation: KODI::GAME::CPortManager Class Reference
KODI::GAME::CPortManager Class Reference
Games
#include <PortManager.h>
Public Member Functions
CPortManager ()
~CPortManager ()
void Initialize (const std::string &profilePath)
void Deinitialize ()
void SetControllerTree (const CControllerTree &controllerTree)
void LoadXML ()
void SaveXMLAsync ()
void Clear ()
void ConnectController (const std::string &portAddress, bool connected, const std::string &controllerId="")
const CControllerTree & GetControllerTree () const
Static Private Member Functions
static void DeserializePorts (const tinyxml2::XMLElement *pElement, PortVec &ports)
static void DeserializePort (const tinyxml2::XMLElement *pElement, CPortNode &port)
static void DeserializeControllers (const tinyxml2::XMLElement *pElement, ControllerNodeVec &controllers)
static void DeserializeController (const tinyxml2::XMLElement *pElement, CControllerNode &controller)
static void SerializePorts (tinyxml2::XMLElement &node, const PortVec &ports)
static void SerializePort (tinyxml2::XMLElement &portNode, const CPortNode &port)
static void SerializeControllers (tinyxml2::XMLElement &portNode, const ControllerNodeVec &controllers)
static void SerializeController (tinyxml2::XMLElement &controllerNode, const CControllerNode &controller)
static bool ConnectController (const std::string &portAddress, bool connected, const std::string &controllerId, PortVec &ports)
static bool ConnectController (const std::string &portAddress, bool connected, const std::string &controllerId, CPortNode &port)
static bool ConnectController (const std::string &portAddress, bool connected, const std::string &controllerId, ControllerNodeVec &controllers)
static bool ConnectController (const std::string &portAddress, bool connected, const std::string &controllerId, CControllerNode &controller)
static bool HasState (const CPortNode &port)
static bool HasState (const CControllerNode &controller)
Private Attributes
CControllerTree m_controllerTree
std::string m_xmlPath
std::vector< std::future< void > > m_saveFutures
std::mutex m_saveMutex
Constructor & Destructor Documentation
CPortManager()
CPortManager::CPortManager () default
~CPortManager()
CPortManager::~CPortManager () default
Member Function Documentation
Clear()
void CPortManager::Clear ()
References KODI::GAME::CControllerHub::Clear(), m_controllerTree, and m_xmlPath.
ConnectController() [1/5]
bool CPortManager::ConnectController (const std::string & portAddress, bool connected, const std::string & controllerId, CControllerNode & controller) static private
References ConnectController(), KODI::GAME::CControllerNode::GetHub(), and KODI::GAME::CControllerHub::GetPorts().
ConnectController() [2/5]
bool CPortManager::ConnectController (const std::string & portAddress, bool connected, const std::string & controllerId, ControllerNodeVec & controllers) static private
References ConnectController().
ConnectController() [3/5]
bool CPortManager::ConnectController (const std::string & portAddress, bool connected, const std::string & controllerId, CPortNode & port) static private
References ConnectController(), KODI::GAME::CPortNode::GetAddress(), KODI::GAME::CPortNode::GetCompatibleControllers(), KODI::GAME::CPortNode::SetActiveController(), and KODI::GAME::CPortNode::SetConnected().
ConnectController() [4/5]
bool CPortManager::ConnectController (const std::string & portAddress, bool connected, const std::string & controllerId, PortVec & ports) static private
References ConnectController().
ConnectController() [5/5]
void CPortManager::ConnectController (const std::string & portAddress, bool connected, const std::string & controllerId = "")
References ConnectController(), KODI::GAME::CControllerHub::GetPorts(), and m_controllerTree.
Referenced by ConnectController(), ConnectController(), ConnectController(), ConnectController(), and ConnectController().
Deinitialize()
void CPortManager::Deinitialize ()
References KODI::GAME::CControllerHub::Clear(), m_controllerTree, m_saveFutures, and m_xmlPath.
DeserializeController()
void CPortManager::DeserializeController (const tinyxml2::XMLElement * pElement, CControllerNode & controller) static private
References DeserializePorts(), KODI::GAME::CControllerNode::GetHub(), and KODI::GAME::CControllerHub::GetPorts().
Referenced by DeserializeControllers().
DeserializeControllers()
void CPortManager::DeserializeControllers (const tinyxml2::XMLElement * pElement, ControllerNodeVec & controllers) static private
References DeserializeController(), XMLUtils::GetAttribute(), CLog::Log(), and LOGDEBUG.
Referenced by DeserializePort().
DeserializePort()
void CPortManager::DeserializePort (const tinyxml2::XMLElement * pElement, CPortNode & port) static private
References DeserializeControllers(), XMLUtils::GetAttribute(), KODI::GAME::CPortNode::GetCompatibleControllers(), KODI::GAME::CPortNode::SetActiveController(), and KODI::GAME::CPortNode::SetConnected().
Referenced by DeserializePorts().
DeserializePorts()
void CPortManager::DeserializePorts (const tinyxml2::XMLElement * pElement, PortVec & ports) static private
References DeserializePort(), XMLUtils::GetAttribute(), CLog::Log(), and LOGDEBUG.
Referenced by DeserializeController(), and LoadXML().
GetControllerTree()
const CControllerTree & KODI::GAME::CPortManager::GetControllerTree () const inline
References m_controllerTree.
HasState() [1/2]
bool CPortManager::HasState (const CControllerNode & controller) static private
References KODI::GAME::CControllerNode::GetHub(), KODI::GAME::CControllerHub::GetPorts(), and HasState().
HasState() [2/2]
bool CPortManager::HasState (const CPortNode & port) static private
Referenced by HasState(), and SerializeControllers().
Initialize()
void CPortManager::Initialize (const std::string & profilePath)
References URIUtils::AddFileToFolder(), and m_xmlPath.
LoadXML()
void CPortManager::LoadXML ()
References DeserializePorts(), CFileUtils::Exists(), KODI::GAME::CControllerHub::GetPorts(), CXBMCTinyXML2::LoadFile(), CLog::Log(), LOGDEBUG, LOGERROR, LOGINFO, m_controllerTree, and m_xmlPath.
SaveXMLAsync()
void CPortManager::SaveXMLAsync ()
References KODI::GAME::CControllerHub::GetPorts(), m_controllerTree, m_saveFutures, m_saveMutex, m_xmlPath, node, CXBMCTinyXML2::SaveFile(), and SerializePorts().
SerializeController()
void CPortManager::SerializeController (tinyxml2::XMLElement & controllerNode, const CControllerNode & controller) static private
References KODI::GAME::CControllerNode::GetController(), KODI::GAME::CControllerNode::GetHub(), KODI::GAME::CControllerHub::GetPorts(), and SerializePorts().
Referenced by SerializeControllers().
SerializeControllers()
void CPortManager::SerializeControllers (tinyxml2::XMLElement & portNode, const ControllerNodeVec & controllers) static private
References HasState(), and SerializeController().
Referenced by SerializePort().
SerializePort()
void CPortManager::SerializePort (tinyxml2::XMLElement & portNode, const CPortNode & port) static private
References KODI::GAME::CPortNode::GetActiveController(), KODI::GAME::CPortNode::GetAddress(), KODI::GAME::CPortNode::GetCompatibleControllers(), KODI::GAME::CControllerNode::GetController(), KODI::GAME::CPortNode::GetPortID(), KODI::GAME::CPortNode::IsConnected(), and SerializeControllers().
Referenced by SerializePorts().
SerializePorts()
void CPortManager::SerializePorts (tinyxml2::XMLElement & node, const PortVec & ports) static private
References node, and SerializePort().
Referenced by SaveXMLAsync(), and SerializeController().
SetControllerTree()
void CPortManager::SetControllerTree (const CControllerTree & controllerTree)
References m_controllerTree.
Member Data Documentation
m_controllerTree
CControllerTree KODI::GAME::CPortManager::m_controllerTree private
Referenced by Clear(), ConnectController(), Deinitialize(), GetControllerTree(), LoadXML(), SaveXMLAsync(), and SetControllerTree().
m_saveFutures
std::vector<std::future<void> > KODI::GAME::CPortManager::m_saveFutures private
Referenced by Deinitialize(), and SaveXMLAsync().
m_saveMutex
std::mutex KODI::GAME::CPortManager::m_saveMutex private
Referenced by SaveXMLAsync().
m_xmlPath
std::string KODI::GAME::CPortManager::m_xmlPath private
Referenced by Clear(), Deinitialize(), Initialize(), LoadXML(), and SaveXMLAsync().
The documentation for this class was generated from the following files:
PortManager.h
PortManager.cpp