Kodi Documentation: XFILE::CMultiPathDirectory Class Reference
XFILE::CMultiPathDirectory Class Reference
#include <MultiPathDirectory.h>
Public Member Functions
CMultiPathDirectory (void)
~CMultiPathDirectory (void) override
bool GetDirectory (const CURL &url, CFileItemList &items) override
Get the items of the directory strPath.
bool Exists (const CURL &url) override
Check for directory existence.
bool Remove (const CURL &url) override
Removes the directory.
Public Member Functions inherited from XFILE::IDirectory
IDirectory ()
virtual ~IDirectory (void)
virtual float GetProgress () const
Retrieve the progress of the current directory fetch (if possible).
virtual void CancelDirectory ()
Cancel the current directory fetch (if possible).
virtual bool Create (const CURL &url)
Create the directory.
virtual bool RemoveRecursive (const CURL &url)
Recursively removes the directory.
virtual bool IsAllowed (const CURL &url) const
Whether this file should be listed.
virtual bool AllowAll () const
Whether to allow all files/folders to be listed.
virtual DIR_CACHE_TYPE GetCacheType (const CURL &url) const
How this directory should be cached.
void SetMask (const std::string &strMask)
Set a mask of extensions for the files in the directory.
void SetFlags (int flags)
Set the flags for this directory handler.
bool ProcessRequirements ()
Process additional requirements before the directory fetch is performed. Some directory fetches may require authentication, keyboard input etc. The IDirectory subclass should call GetKeyboardInput, SetErrorDialog or RequireAuthentication and then return false from the GetDirectory method. CDirectory will then prompt for input from the user, before re-calling the GetDirectory method.
virtual bool Resolve (CFileItem &item) const
Resolves a given item to a playable item.
Static Public Member Functions
static std::string GetFirstPath (const std::string &strPath)
static bool SupportsWriteFileOperations (const std::string &strPath)
static bool GetPaths (const CURL &url, std::vector< std::string > &vecPaths)
static bool GetPaths (const std::string &path, std::vector< std::string > &paths)
static bool HasPath (const std::string &strPath, const std::string &strPathToFind)
static std::string ConstructMultiPath (const std::vector< std::string > &vecPaths)
static std::string ConstructMultiPath (const std::set< std::string > &setPaths)
Static Public Member Functions inherited from XFILE::IDirectory
static void RegisterProfileManager (const CProfileManager &profileManager)
static void UnregisterProfileManager ()
Private Member Functions
void MergeItems (CFileItemList &items)
std::string ConstructMultiPath (const CFileItemList &items, const std::vector< int > &stack)
Static Private Member Functions
static void AddToMultiPath (std::string &strMultiPath, const std::string &strPath)
Additional Inherited Members
Protected Member Functions inherited from XFILE::IDirectory
bool GetKeyboardInput (const CVariant &heading, std::string &input, bool hiddenInput=false)
Prompt the user for some keyboard input Call this method from the GetDirectory method to retrieve additional input from the user. If this function returns false then no input has been received, and the GetDirectory call should return false.
void SetErrorDialog (const CVariant &heading, const CVariant &line1, const CVariant &line2=0, const CVariant &line3=0)
Show an error dialog on failure of GetDirectory call Call this method from the GetDirectory method to set an error message to be shown to the user.
void RequireAuthentication (const CURL &url)
Prompt the user for authentication of a URL. Call this method from the GetDirectory method when authentication is required from the user, before returning false from the GetDirectory call. The user will be prompted for authentication, and GetDirectory will be re-called.
Protected Attributes inherited from XFILE::IDirectory
std::string m_strFileMask
Holds the file mask specified by SetMask()
int m_flags
Directory flags - see DIR_FLAG.
CVariant m_requirements
Static Protected Attributes inherited from XFILE::IDirectory
static const CProfileManager * m_profileManager = nullptr
Constructor & Destructor Documentation
CMultiPathDirectory()
CMultiPathDirectory::CMultiPathDirectory (void) default
~CMultiPathDirectory()
CMultiPathDirectory::~CMultiPathDirectory (void) override default
Member Function Documentation
AddToMultiPath()
void CMultiPathDirectory::AddToMultiPath (std::string & strMultiPath, const std::string & strPath) static private
References URIUtils::AddSlashAtEnd().
Referenced by ConstructMultiPath(), ConstructMultiPath(), and ConstructMultiPath().
ConstructMultiPath() [1/3]
std::string CMultiPathDirectory::ConstructMultiPath (const CFileItemList & items, const std::vector< int > & stack) private
References AddToMultiPath().
ConstructMultiPath() [2/3]
std::string CMultiPathDirectory::ConstructMultiPath (const std::set< std::string > & setPaths) static
References AddToMultiPath().
ConstructMultiPath() [3/3]
std::string CMultiPathDirectory::ConstructMultiPath (const std::vector< std::string > & vecPaths) static
References AddToMultiPath().
Referenced by CMediaSource::FromNameAndPaths(), GroupUtils::Group(), MergeItems(), CUtil::MusicPlaylistsLocation(), TEST_F(), and CUtil::VideoPlaylistsLocation().
Exists()
bool CMultiPathDirectory::Exists (const CURL & url) override virtual
Check for directory existence.
Parameters
url Directory to check.
Returns
Returns true, if directory exists
See also
CDirectoryFactory
Reimplemented from XFILE::IDirectory.
References XFILE::CDirectory::Exists(), GetPaths(), CURL::GetRedacted(), CLog::Log(), and LOGDEBUG.
GetDirectory()
bool CMultiPathDirectory::GetDirectory (const CURL & url, CFileItemList & items) override virtual
Get the items of the directory strPath.
Parameters
url Directory to read.
items Retrieves the directory entries.
Returns
Returns true, if successful.
See also
CDirectoryFactory
Implements XFILE::IDirectory.
References CFileItemList::Append(), CGUIWindow::Close(), XFILE::CDirectory::GetDirectory(), CServiceBroker::GetGUI(), GetPaths(), CURL::GetRedacted(), CGUIComponent::GetWindowManager(), CURL::GetWithoutUserDetails(), CLog::Log(), LOGDEBUG, LOGERROR, XFILE::IDirectory::m_flags, XFILE::IDirectory::m_strFileMask, MergeItems(), CGUIDialogProgress::Open(), CGUIDialogProgress::Progress(), CGUIDialogBoxBase::SetHeading(), CGUIDialogBoxBase::SetLine(), CGUIDialogProgress::SetProgressAdvance(), CGUIDialogProgress::SetProgressMax(), CGUIDialogProgress::ShowProgressBar(), and WINDOW_DIALOG_PROGRESS.
GetFirstPath()
std::string CMultiPathDirectory::GetFirstPath (const std::string & strPath) static
Referenced by CFileItem::Exists(), CFileItem::GetBaseMoviePath(), KODI::ART::GetFolderThumb(), KODI::ART::GetLocalArtBaseFilename(), CUtil::GetMatchingSource(), URIUtils::GetParentPath(), CVideoDatabase::GetScraperForPath(), CVideoDatabase::GetSourcePath(), URIUtils::IsOnLAN(), CGUIWindowVideoBase::LoadVideoInfo(), CUtil::MakeLegalPath(), and CPictureThumbLoader::ProcessFoldersAndArchives().
GetPaths() [1/2]
bool CMultiPathDirectory::GetPaths (const CURL & url, std::vector< std::string > & vecPaths) static
References CURL::Get(), and GetPaths().
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), Exists(), XFILE::CMultiPathFile::Exists(), GetDirectory(), CVideoDatabase::GetItemsForPath(), GetPaths(), CVideoDatabase::GetPlayCounts(), URIUtils::IsRemote(), XFILE::CMultiPathFile::Open(), Remove(), CVideoDatabase::RemoveContentForPath(), CFileUtils::RenameFile(), CVideoDatabase::SetScraperForPath(), KODI::VIDEO::CVideoInfoScanner::Start(), XFILE::CMultiPathFile::Stat(), SupportsWriteFileOperations(), and CVideoDatabase::UpdateTables().
GetPaths() [2/2]
bool CMultiPathDirectory::GetPaths (const std::string & path, std::vector< std::string > & paths) static
HasPath()
bool CMultiPathDirectory::HasPath (const std::string & strPath, const std::string & strPathToFind) static
References URIUtils::RemoveSlashAtEnd().
Referenced by CGUIDialogFileBrowser::OnMessage(), and CGUIMediaWindow::OnMessage().
MergeItems()
void CMultiPathDirectory::MergeItems (CFileItemList & items) private
References ConstructMultiPath(), end(), CFileItemList::Get(), CLog::Log(), LOGDEBUG, CFileItemList::Remove(), CFileItemList::Size(), CFileItemList::Sort(), SortByLabel, and SortOrderAscending.
Referenced by GetDirectory().
Remove()
bool CMultiPathDirectory::Remove (const CURL & url) override virtual
Removes the directory.
Parameters
url Directory to remove.
Returns
Returns false if not successful
Reimplemented from XFILE::IDirectory.
References GetPaths(), XFILE::CDirectory::Remove(), and success.
SupportsWriteFileOperations()
bool CMultiPathDirectory::SupportsWriteFileOperations (const std::string & strPath) static
References GetPaths(), and CUtil::SupportsWriteFileOperations().
Referenced by CUtil::SupportsWriteFileOperations().
The documentation for this class was generated from the following files:
MultiPathDirectory.h
MultiPathDirectory.cpp