Kodi Documentation: Visualization
Visualization
C++ » Interface - kodi::addon » Addon type instances
Class: kodi::addon::CInstanceVisualization
Visualization add-on instance
Music visualization, or music visualisation, is a feature in Kodi that generates animated imagery based on a piece of music. The imagery is usually generated and rendered in real time synchronized to the music.
Modules
Definitions, structures and enumerators
Visualization add-on instance definition values
All visualization functions associated data structures.
Information functions
To get info about the device, display and several other parts
These are functions to query any values or to transfer them to Kodi.
Functions
kodi::addon::CInstanceVisualization::CInstanceVisualization ()
Visualization class constructor.
kodi::addon::CInstanceVisualization::CInstanceVisualization (const IInstanceInfo &instance)
Visualization class constructor used to support multiple instance types.
kodi::addon::CInstanceVisualization::~CInstanceVisualization () override=default
Destructor.
virtual bool kodi::addon::CInstanceVisualization::Start (int channels, int samplesPerSec, int bitsPerSample, const std::string &songName)
Used to notify the visualization that a new song has been started.
virtual void kodi::addon::CInstanceVisualization::Stop ()
Used to inform the visualization that the rendering control was stopped.
virtual void kodi::addon::CInstanceVisualization::AudioData (const float *audioData, size_t audioDataLength)
Pass audio data to the visualization.
virtual bool kodi::addon::CInstanceVisualization::IsDirty ()
Used to inform Kodi that the rendered region is dirty and need an update.
virtual void kodi::addon::CInstanceVisualization::Render ()
Used to indicate when the add-on should render.
virtual int kodi::addon::CInstanceVisualization::GetSyncDelay ()
Used to get the number of buffers from the current visualization.
virtual bool kodi::addon::CInstanceVisualization::GetPresets (std::vector< std::string > &presets)
Used to get a list of visualization presets the user can select. from.
virtual int kodi::addon::CInstanceVisualization::GetActivePreset ()
Get the index of the current preset.
virtual bool kodi::addon::CInstanceVisualization::IsLocked ()
Check if the add-on is locked to the current preset.
virtual bool kodi::addon::CInstanceVisualization::PrevPreset ()
Load the previous visualization preset.
virtual bool kodi::addon::CInstanceVisualization::NextPreset ()
Load the next visualization preset.
virtual bool kodi::addon::CInstanceVisualization::LoadPreset (int select)
Load a visualization preset.
virtual bool kodi::addon::CInstanceVisualization::RandomPreset ()
Switch to a new random preset.
virtual bool kodi::addon::CInstanceVisualization::LockPreset (bool lockUnlock)
Lock the current visualization preset, preventing it from changing.
virtual bool kodi::addon::CInstanceVisualization::RatePreset (bool plusMinus)
Used to increase/decrease the visualization preset rating.
virtual bool kodi::addon::CInstanceVisualization::UpdateAlbumart (const std::string &albumart)
Inform the visualization of the current album art image.
virtual bool kodi::addon::CInstanceVisualization::UpdateTrack (const kodi::addon::VisualizationTrack &track)
Inform the visualization of the current track's tag information.
Detailed Description
Class: kodi::addon::CInstanceVisualization
Visualization add-on instance
Music visualization, or music visualisation, is a feature in Kodi that generates animated imagery based on a piece of music. The imagery is usually generated and rendered in real time synchronized to the music.
Visualization techniques range from simple ones (e.g., a simulation of an oscilloscope display) to elaborate ones, which often include a plurality of composited effects. The changes in the music's loudness and frequency spectrum are among the properties used as input to the visualization.
Include the header #include <kodi/addon-instance/Visualization.h> to use this class.
This interface allows the creation of visualizations for Kodi, based upon DirectX or/and OpenGL rendering with C++ code.
Additionally, there are several other functions available in which the child class can ask about the current hardware, including the device, display and several other parts.
Here's an example on addon.xml:
<?xml version="1.0" encoding="UTF-8"?>
<addon
  id="visualization.myspecialnamefor"
  version="1.0.0"
  name="My special visualization addon"
  provider-name="Your Name">
  <requires>@ADDON_DEPENDS@</requires>
  <extension
    point="xbmc.player.musicviz"
    library_@PLATFORM@="@LIBRARY_FILENAME@"/>
  <extension point="xbmc.addon.metadata">
    <summary lang="en_GB">My visualization addon addon</summary>
    <description lang="en_GB">My visualization addon description</description>
    <platform>@PLATFORM@</platform>
  </extension>
</addon>
Description to visualization related addon.xml values:
Name Description
point Addon type specification
At all addon types and for this kind always "xbmc.player.musicviz".
library_@PLATFORM@ Sets the used library name, which is automatically set by cmake at addon build.
Here is an example of the minimum required code to start a visualization:
#include <kodi/addon-instance/Visualization.h>
class CMyVisualization : public kodi::addon::CAddonBase,
                         public kodi::addon::CInstanceVisualization
{
public:
  CMyVisualization();
  bool Start(int channels, int samplesPerSec, int bitsPerSample, const std::string& songName) override;
  void AudioData(const float* audioData, size_t audioDataLength) override;
  void Render() override;
};
CMyVisualization::CMyVisualization()
{
  ...
}
bool CMyVisualization::Start(int channels, int samplesPerSec, int bitsPerSample, const std::string& songName)
{
  ...
  return true;
}
void CMyVisualization::AudioData(const float* audioData, size_t audioDataLength)
{
  ...
}
void CMyVisualization::Render()
{
  ...
}
ADDONCREATOR(CMyVisualization)
Here is another example where the visualization is used together with other instance types:
#include <kodi/addon-instance/Visualization.h>
class CMyVisualization : public kodi::addon::CInstanceVisualization
{
public:
  CMyVisualization(const kodi::addon::IInstanceInfo& instance);
  bool Start(int channels, int samplesPerSec, int bitsPerSample, const std::string& songName) override;
  void AudioData(const float* audioData, size_t audioDataLength) override;
  void Render() override;
};
CMyVisualization::CMyVisualization(const kodi::addon::IInstanceInfo& instance)
  : kodi::addon::CInstanceAudioDecoder(instance)
{
  ...
}
bool CMyVisualization::Start(int channels, int samplesPerSec, int bitsPerSample, const std::string& songName)
{
  ...
  return true;
}
void CMyVisualization::AudioData(const float* audioData, size_t audioDataLength)
{
  ...
}
void CMyVisualization::Render()
{
  ...
}
//----------------------------------------------------------------------
class CMyAddon : public kodi::addon::CAddonBase
{
public:
  CMyAddon() = default;
  ADDON_STATUS CreateInstance(const kodi::addon::IInstanceInfo& instance,
                              KODI_ADDON_INSTANCE_HDL& hdl) override;
};
// If you use only one instance in your add-on, can be instanceType and
// instanceID ignored
ADDON_STATUS CMyAddon::CreateInstance(const kodi::addon::IInstanceInfo& instance,
                                      KODI_ADDON_INSTANCE_HDL& hdl)
{
  if (instance.IsType(ADDON_INSTANCE_VISUALIZATION))
  {
    kodi::Log(ADDON_LOG_INFO, "Creating my visualization");
    hdl = new CMyVisualization(instance);
    return ADDON_STATUS_OK;
  }
  else if (...)
  {
    ...
  }
  return ADDON_STATUS_UNKNOWN;
}
ADDONCREATOR(CMyAddon)
The destruction of the example class CMyVisualization is called from Kodi's header. Manually deleting the add-on instance is not required.
Function Documentation
AudioData()
virtual void kodi::addon::CInstanceVisualization::AudioData (const float * audioData, size_t audioDataLength) inline virtual
Pass audio data to the visualization.
Parameters
[in] audioData The raw audio data
[in] audioDataLength Length of the audioData array
CInstanceVisualization() [1/2]
kodi::addon::CInstanceVisualization::CInstanceVisualization () inline
Visualization class constructor.
Used by an add-on that only supports visualizations.
CInstanceVisualization() [2/2]
kodi::addon::CInstanceVisualization::CInstanceVisualization (const IInstanceInfo & instance) inline explicit
Visualization class constructor used to support multiple instance types.
Parameters
[in] instance The instance value given to kodi::addon::CAddonBase::CreateInstance(...).
[in] kodiVersion [opt] Version used in Kodi for this instance, to allow compatibility to older Kodi versions.
Note
Recommended to set kodiVersion.
Here's example about the use of this:
class CMyVisualization : public kodi::addon::CInstanceAudioDecoder
{
public:
  CMyVisualization(const kodi::addon::IInstanceInfo& instance)
    : kodi::addon::CInstanceAudioDecoder(instance)
  {
     ...
  }
  ...
};
ADDON_STATUS CMyAddon::CreateInstance(const kodi::addon::IInstanceInfo& instance,
                                      KODI_ADDON_INSTANCE_HDL& hdl)
{
  kodi::Log(ADDON_LOG_INFO, "Creating my visualization");
  hdl = new CMyVisualization(instance);
  return ADDON_STATUS_OK;
}
GetActivePreset()
virtual int kodi::addon::CInstanceVisualization::GetActivePreset () inline virtual
Get the index of the current preset.
Returns
Index number of the current preset
GetPresets()
virtual bool kodi::addon::CInstanceVisualization::GetPresets (std::vector< std::string > & presets) inline virtual
Used to get a list of visualization presets the user can select. from.
Parameters
[out] presets The vector list containing the names of presets that the user can select
Returns
Return true if successful, or false if there are no presets to choose from
Referenced by kodi::addon::CInstanceVisualization::ADDON_get_presets().
GetSyncDelay()
virtual int kodi::addon::CInstanceVisualization::GetSyncDelay () inline virtual
Used to get the number of buffers from the current visualization.
Returns
The number of buffers to delay before calling AudioData()
Note
If this function is not implemented, it will default to 0.
IsDirty()
virtual bool kodi::addon::CInstanceVisualization::IsDirty () inline virtual
Used to inform Kodi that the rendered region is dirty and need an update.
Returns
True if dirty
IsLocked()
virtual bool kodi::addon::CInstanceVisualization::IsLocked () inline virtual
Check if the add-on is locked to the current preset.
Returns
True if locked to the current preset
LoadPreset()
virtual bool kodi::addon::CInstanceVisualization::LoadPreset (int select) inline virtual
Load a visualization preset.
This function is called after a new preset is selected.
Parameters
[in] select Preset index to use
Returns
Return true if the preset is loaded
LockPreset()
virtual bool kodi::addon::CInstanceVisualization::LockPreset (bool lockUnlock) inline virtual
Lock the current visualization preset, preventing it from changing.
Parameters
[in] lockUnlock If set to true, the preset should be locked
Returns
Return true if the current preset is locked
Referenced by kodi::addon::CInstanceVisualization::ADDON_lock_preset().
NextPreset()
virtual bool kodi::addon::CInstanceVisualization::NextPreset () inline virtual
Load the next visualization preset.
Returns
Return true if the next preset was loaded
PrevPreset()
virtual bool kodi::addon::CInstanceVisualization::PrevPreset () inline virtual
Load the previous visualization preset.
Returns
Return true if the previous preset was loaded
RandomPreset()
virtual bool kodi::addon::CInstanceVisualization::RandomPreset () inline virtual
Switch to a new random preset.
Returns
Return true if a random preset was loaded
RatePreset()
virtual bool kodi::addon::CInstanceVisualization::RatePreset (bool plusMinus) inline virtual
Used to increase/decrease the visualization preset rating.
Parameters
[in] plusMinus If set to true the rating is increased, otherwise decreased
Returns
Return true if the rating is modified
Render()
virtual void kodi::addon::CInstanceVisualization::Render () inline virtual
Used to indicate when the add-on should render.
Referenced by kodi::addon::CInstanceVisualization::ADDON_render().
Start()
virtual bool kodi::addon::CInstanceVisualization::Start (int channels, int samplesPerSec, int bitsPerSample, const std::string & songName) inline virtual
Used to notify the visualization that a new song has been started.
Parameters
[in] channels Number of channels in the stream
[in] samplesPerSec Samples per second of stream
[in] bitsPerSample Number of bits in one sample
[in] songName The name of the currently-playing song
Returns
true if start successful done
Referenced by kodi::addon::CInstanceVisualization::ADDON_start().
Stop()
virtual void kodi::addon::CInstanceVisualization::Stop () inline virtual
Used to inform the visualization that the rendering control was stopped.
Referenced by kodi::addon::CInstanceVisualization::ADDON_stop().
UpdateAlbumart()
virtual bool kodi::addon::CInstanceVisualization::UpdateAlbumart (const std::string & albumart) inline virtual
Inform the visualization of the current album art image.
Parameters
[in] albumart Path to the current album art image
Returns
Return true if the image is used
UpdateTrack()
virtual bool kodi::addon::CInstanceVisualization::UpdateTrack (const kodi::addon::VisualizationTrack & track) inline virtual
Inform the visualization of the current track's tag information.
Parameters
[in] track Visualization track information structure
Returns
Return true if the track information is used
The following table contains values that can be set with class VisualizationTrack :
Name Type Set call Get call
Title of the current song. std::string SetTitle GetTitle
Artist names, as a single string std::string SetArtist GetArtist
Album that the current song is from. std::string SetAlbum GetAlbum
Album artist names, as a single string std::string SetAlbumArtist GetAlbumArtist
The genre name from the music tag, if present std::string SetGenre GetGenre
Duration of the current song, in seconds int SetDuration GetDuration
Track number of the current song int SetTrack GetTrack
Disc number of the current song stored in the ID tag info int SetDisc GetDisc
Year that the current song was released int SetYear GetYear
Lyrics of the current song, if available std::string SetLyrics GetLyrics
The user-defined rating of the current song int SetRating GetRating
Comment of the current song stored in the ID tag info std::string SetComment GetComment
Example:
#include <kodi/addon-instance/Visualization.h>
class CMyVisualization : public kodi::addon::CInstanceVisualization
{
public:
  CMyVisualization(KODI_HANDLE instance, const std::string& version);
  ...
private:
  kodi::addon::VisualizationTrack m_runningTrack;
};
bool CMyVisualization::UpdateTrack(const kodi::addon::VisualizationTrack& track)
{
  m_runningTrack = track;
  return true;
}
~CInstanceVisualization()
kodi::addon::CInstanceVisualization::~CInstanceVisualization () override default
Destructor.