Kodi Documentation: CBitstreamReader Class Reference
CBitstreamReader Class Reference
#include <BitstreamReader.h>
Public Member Functions
CBitstreamReader (const uint8_t *buf, int len)
uint32_t ReadBits (int nbits)
void SkipBits (int nbits)
uint32_t GetBits (int nbits)
unsigned int Position ()
unsigned int AvailableBits ()
Private Attributes
const uint8_t * buffer
const uint8_t * start
int offbits = 0
int length
int oflow = 0
int m_posBits {0}
Constructor & Destructor Documentation
CBitstreamReader()
CBitstreamReader::CBitstreamReader (const uint8_t * buf, int len)
Member Function Documentation
AvailableBits()
unsigned int CBitstreamReader::AvailableBits () inline
References length, and m_posBits.
Referenced by CHevcSei::ParseSeiMessage(), and CHevcSei::ParseSeiRbspInternal().
GetBits()
uint32_t CBitstreamReader::GetBits (int nbits)
References buffer, length, offbits, oflow, and start.
Referenced by ReadBits().
Position()
unsigned int CBitstreamReader::Position () inline
References m_posBits.
Referenced by CHevcSei::ParseSeiMessage().
ReadBits()
uint32_t CBitstreamReader::ReadBits (int nbits)
References GetBits(), m_posBits, and offbits.
Referenced by CHevcSei::FindHdr10PlusSeiMessage(), CHevcSei::ParseSeiMessage(), and CVC1BitstreamParser::vc1_parse_frame().
SkipBits()
void CBitstreamReader::SkipBits (int nbits)
References length, m_posBits, offbits, oflow, and start.
Referenced by CHevcSei::ParseSeiMessage(), CHevcSei::ParseSeiRbspInternal(), and CVC1BitstreamParser::vc1_parse_frame().
Member Data Documentation
buffer
const uint8_t* CBitstreamReader::buffer private
Referenced by GetBits().
length
int CBitstreamReader::length private
Referenced by AvailableBits(), GetBits(), and SkipBits().
m_posBits
int CBitstreamReader::m_posBits {0} private
Referenced by AvailableBits(), Position(), ReadBits(), and SkipBits().
offbits
int CBitstreamReader::offbits = 0 private
Referenced by GetBits(), ReadBits(), and SkipBits().
oflow
int CBitstreamReader::oflow = 0 private
Referenced by GetBits(), and SkipBits().
start
const uint8_t * CBitstreamReader::start private
Referenced by GetBits(), and SkipBits().
The documentation for this class was generated from the following files:
BitstreamReader.h
BitstreamReader.cpp