Kodi Documentation: CAddonBuiltins Class Reference
CAddonBuiltins Class Reference
Class providing add-on related built-in commands.
#include <AddonBuiltins.h>
Public Member Functions
CBuiltins::CommandMap GetOperations () const
Returns the map of operations.
Detailed Description
Class providing add-on related built-in commands.
Member Function Documentation
GetOperations()
CBuiltins::CommandMap CAddonBuiltins::GetOperations () const
Returns the map of operations.
References AddonSettings(), EnableAddon(), InstallAddon(), InstallFromZip(), OpenDefaultSettings(), RunAddon(), RunPlugin(), RunScript(), SetDefaultAddon(), StopScript(), UpdateLocals(), and UpdateRepos().
The documentation for this class was generated from the following files:
AddonBuiltins.h
AddonBuiltins.cpp