Kodi Documentation: JSONVariantWriter.cpp File Reference
JSONVariantWriter.cpp File Reference
#include "JSONVariantWriter.h"
#include "utils/Variant.h"
#include <rapidjson/prettywriter.h>
#include <rapidjson/stringbuffer.h>
#include <rapidjson/writer.h>
Functions
template<class TWriter >
bool InternalWrite (TWriter &writer, const CVariant &value)
Function Documentation
InternalWrite()
template<class TWriter > bool InternalWrite (TWriter & writer, const CVariant & value)
References InternalWrite(), value, CVariant::VariantTypeArray, CVariant::VariantTypeBoolean, CVariant::VariantTypeConstNull, CVariant::VariantTypeDouble, CVariant::VariantTypeInteger, CVariant::VariantTypeNull, CVariant::VariantTypeObject, CVariant::VariantTypeString, and CVariant::VariantTypeUnsignedInteger.
Referenced by InternalWrite(), and CJSONVariantWriter::Write().