Kodi Documentation: GLUtils.cpp File Reference
GLUtils.cpp File Reference
#include "GLUtils.h"
#include "ServiceBroker.h"
#include "log.h"
#include "rendering/MatrixGL.h"
#include "rendering/RenderSystem.h"
#include "settings/AdvancedSettings.h"
#include "settings/SettingsComponent.h"
#include "utils/StringUtils.h"
#include <map>
#include <stdexcept>
#include <utility>
Namespaces
namespace anonymous_namespace{GLUtils.cpp}
Macros
#define X(VAL) std::make_pair(VAL, #VAL)
Functions
static void PrintMatrix (const GLfloat *matrix, const std::string &matrixName)
void _VerifyGLState (const char *szfile, const char *szfunction, int lineno)
void LogGraphicsInfo ()
Variables
std::map< GLenum, const char * > anonymous_namespace{GLUtils.cpp}::glErrors
std::map< GLenum, const char * > anonymous_namespace{GLUtils.cpp}::glErrorSource
std::map< GLenum, const char * > anonymous_namespace{GLUtils.cpp}::glErrorType
std::map< GLenum, const char * > anonymous_namespace{GLUtils.cpp}::glErrorSeverity
Macro Definition Documentation
X
#define X (VAL) std::make_pair(VAL, #VAL)
Function Documentation
_VerifyGLState()
void _VerifyGLState (const char * szfile, const char * szfunction, int lineno)
References err(), CMatrixGLStack::Get(), anonymous_namespace{GLUtils.cpp}::glErrors, glMatrixModview, glMatrixProject, CLog::Log(), LOGDEBUG, LOGERROR, and PrintMatrix().
LogGraphicsInfo()
void LogGraphicsInfo ()
References CServiceBroker::GetRenderSystem(), CRenderSystemBase::GetRenderVersion(), CLog::Log(), and LOGINFO.
Referenced by CRenderSystemGL::InitRenderSystem(), and CRenderSystemGLES::InitRenderSystem().
PrintMatrix()
static void PrintMatrix (const GLfloat * matrix, const std::string & matrixName) static
References CLog::Log(), and LOGDEBUG.
Referenced by _VerifyGLState().