Kodi Documentation: CVideoDbUrl Class Reference
CVideoDbUrl Class Reference
#include <VideoDbUrl.h>
Public Member Functions
CVideoDbUrl ()
~CVideoDbUrl () override
const std::string & GetItemType () const
Public Member Functions inherited from CDbUrl
CDbUrl ()
~CDbUrl () override
bool IsValid () const
void Reset ()
std::string ToString () const
bool FromString (const std::string &dbUrl)
const std::string & GetType () const
void AppendPath (const std::string &subPath)
void AddOption (const std::string &key, const char *value) override
void AddOption (const std::string &key, const std::string &value) override
void AddOption (const std::string &key, int value) override
void AddOption (const std::string &key, float value) override
void AddOption (const std::string &key, double value) override
void AddOption (const std::string &key, bool value) override
void AddOptions (const std::string &options) override
void RemoveOption (const std::string &key) override
bool GetOption (const std::string &key, CVariant &value) const
const UrlOptions & GetOptions () const
std::string GetOptionsString (bool withLeadingSeparator=false) const
bool HasOption (const std::string &key) const
Protected Member Functions
bool parse () override
bool validateOption (const std::string &key, const CVariant &value) override
Private Attributes
std::string m_itemType
Additional Inherited Members
Protected Attributes inherited from CDbUrl
CURL m_url
std::string m_type
Constructor & Destructor Documentation
CVideoDbUrl()
CVideoDbUrl::CVideoDbUrl ()
~CVideoDbUrl()
CVideoDbUrl::~CVideoDbUrl () override default
Member Function Documentation
GetItemType()
const std::string & CVideoDbUrl::GetItemType () const inline
References m_itemType.
Referenced by CGUIDialogVideoInfo::AddItemsToTag(), CVideoDatabase::GetEpisodesByWhere(), CVideoDatabase::GetItems(), CGUIDialogVideoInfo::ManageVideoItem(), and CGUIDialogVideoInfo::RemoveItemsFromTag().
parse()
bool CVideoDbUrl::parse () override protected virtual
Implements CDbUrl.
References CDbUrl::AddOption(), CDbUrl::AddOptions(), CURL::Get(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetActorId(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetAlbumId(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetCountryId(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetDirectorId(), XFILE::CVideoDatabaseDirectory::GetDirectoryChildType(), XFILE::CVideoDatabaseDirectory::GetDirectoryType(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetEpisodeId(), CURL::GetFileName(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetGenreId(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetMovieId(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetMVideoId(), CURL::GetOptions(), XFILE::CVideoDatabaseDirectory::GetQueryParams(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetSeason(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetSetId(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetStudioId(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetTvShowId(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetVideoVersionId(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetYear(), CURL::IsProtocol(), m_itemType, CDbUrl::m_type, CDbUrl::m_url, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_ACTOR, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_COUNTRY, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_DIRECTOR, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_EPISODES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_GENRE, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_INPROGRESS_TVSHOWS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MOVIES_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MUSICVIDEOS_ALBUM, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MUSICVIDEOS_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_EPISODES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_MOVIES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_MUSICVIDEOS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_ROOT, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_SEASONS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_SETS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_STUDIO, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TAGS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MOVIES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MUSICVIDEOS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_TVSHOWS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TVSHOWS_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_VIDEOVERSIONS, and XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_YEAR.
validateOption()
bool CVideoDbUrl::validateOption (const std::string & key, const CVariant & value) override protected virtual
Reimplemented from CDbUrl.
References KODI::PLAYLIST::CSmartPlaylist::GetType(), KODI::PLAYLIST::CSmartPlaylist::LoadFromJson(), m_itemType, CDbUrl::validateOption(), and value.
Member Data Documentation
m_itemType
std::string CVideoDbUrl::m_itemType private
Referenced by GetItemType(), parse(), and validateOption().
The documentation for this class was generated from the following files:
VideoDbUrl.h
VideoDbUrl.cpp