Kodi Documentation: TestXBMCTinyXML.cpp File Reference
TestXBMCTinyXML.cpp File Reference
#include "test/TestUtils.h"
#include "utils/StringUtils.h"
#include "utils/XBMCTinyXML.h"
#include <gtest/gtest.h>
Functions
TEST (TestXBMCTinyXML, ParseFromString)
TEST (TestXBMCTinyXML, ParseFromFileHandle)
Function Documentation
TEST() [1/2]
TEST (TestXBMCTinyXML , ParseFromFileHandle)
References ASSERT_NE(), EXPECT_TRUE(), f, fclose(), CXBMCTinyXML::LoadFile(), root, KODI::UTILS::StringUtils::Trim(), and XBMC_REF_FILE_PATH.
TEST() [2/2]
TEST (TestXBMCTinyXML , ParseFromString)
References data(), EXPECT_TRUE(), CXBMCTinyXML::Parse(), and root.