Kodi Documentation: CAESinkXAudio Class Reference
CAESinkXAudio Class Reference
#include <AESinkXAudio.h>
Classes
struct buffer_ctx
struct VoiceCallback
Public Member Functions
virtual const char * GetName ()
CAESinkXAudio ()
virtual ~CAESinkXAudio ()
bool Initialize (AEAudioFormat &format, std::string &device) override
void Deinitialize () override
void GetDelay (AEDelayStatus &status) override
Return a timestamped status structure with delay and sink info.
double GetCacheTotal () override
double GetLatency () override
unsigned int AddPackets (uint8_t **data, unsigned int frames, unsigned int offset) override
Adds packets to be sent out, this routine MUST block or sleep.
void Drain () override
Public Member Functions inherited from IAESink
IAESink ()=default
virtual ~IAESink ()=default
virtual void AddPause (unsigned int millis)
instruct the sink to add a pause
virtual bool HasVolume ()
virtual void SetVolume (float volume)
Static Public Member Functions
static void Register ()
static std::unique_ptr< IAESink > Create (std::string &device, AEAudioFormat &desiredFormat)
static void EnumerateDevicesEx (AEDeviceInfoList &deviceInfoList, bool force=false)
Private Member Functions
bool InitializeInternal (std::string deviceId, AEAudioFormat &format)
bool AddEndOfStreamPacket ()
Add a 1 frame long buffer with the end of stream flag to the voice.
XAUDIO2_BUFFER BuildXAudio2Buffer (uint8_t **data, unsigned int frames, unsigned int offset)
Create a XAUDIO2_BUFFER with a struct buffer_ctx in pContext member, which must be deleted either manually or by XAudio2 BufferEnd callbak to avoid memory leaks.
Private Attributes
Microsoft::WRL::ComPtr< IXAudio2 > m_xAudio2
IXAudio2MasteringVoice * m_masterVoice {nullptr}
IXAudio2SourceVoice * m_sourceVoice {nullptr}
VoiceCallback m_voiceCallback
AEAudioFormat m_format
uint64_t m_sinkFrames {0}
std::atomic< uint16_t > m_framesInBuffers {0}
double m_avgTimeWaiting {50.0}
bool m_running {false}
bool m_initialized {false}
bool m_isSuspended {false}
bool m_isDirty {false}
LARGE_INTEGER m_timerFreq {}
Constructor & Destructor Documentation
CAESinkXAudio()
CAESinkXAudio::CAESinkXAudio ()
References FAILED, LOGERROR, m_timerFreq, and m_xAudio2.
~CAESinkXAudio()
CAESinkXAudio::~CAESinkXAudio () virtual
References m_xAudio2.
Member Function Documentation
AddEndOfStreamPacket()
bool CAESinkXAudio::AddEndOfStreamPacket () private
Add a 1 frame long buffer with the end of stream flag to the voice.
Returns
true for success, false for failure
References BuildXAudio2Buffer(), LOGERROR, m_framesInBuffers, m_sinkFrames, and m_sourceVoice.
Referenced by Drain().
AddPackets()
unsigned int CAESinkXAudio::AddPackets (uint8_t ** data, unsigned int frames, unsigned int offset) override virtual
Adds packets to be sent out, this routine MUST block or sleep.
Parameters
data array of pointers to planes holding audio data
frames number of audio frames in data
offset offset in frames where audio data starts
Returns
number of frames consumed by the sink
Implements IAESink.
References BuildXAudio2Buffer(), data(), FAILED, CWIN32Util::FormatHRESULT(), LOGDEBUG, LOGERROR, m_avgTimeWaiting, m_format, AEAudioFormat::m_frames, m_framesInBuffers, m_initialized, m_isDirty, m_running, m_sinkFrames, m_sourceVoice, m_timerFreq, m_voiceCallback, CAESinkXAudio::VoiceCallback::mBufferEnd, and _LARGE_INTEGER::QuadPart.
BuildXAudio2Buffer()
XAUDIO2_BUFFER CAESinkXAudio::BuildXAudio2Buffer (uint8_t ** data, unsigned int frames, unsigned int offset) private
Create a XAUDIO2_BUFFER with a struct buffer_ctx in pContext member, which must be deleted either manually or by XAudio2 BufferEnd callbak to avoid memory leaks.
Parameters
data data of the frames to copy. if null, the new buffer will contain silence.
frames number of frames
offset offset from the start in the data buffer.
Returns
the new buffer
References CAESinkXAudio::buffer_ctx::data, data(), CAESinkXAudio::buffer_ctx::frames, CAEUtil::GenerateSilence(), AEAudioFormat::m_dataFormat, m_format, AEAudioFormat::m_frameSize, and CAESinkXAudio::buffer_ctx::sink.
Referenced by AddEndOfStreamPacket(), and AddPackets().
Create()
std::unique_ptr< IAESink > CAESinkXAudio::Create (std::string & device, AEAudioFormat & desiredFormat) static
References LOGERROR.
Referenced by Register().
Deinitialize()
void CAESinkXAudio::Deinitialize () override virtual
Implements IAESink.
References LOGERROR, m_framesInBuffers, m_initialized, m_isDirty, m_masterVoice, m_running, m_sinkFrames, m_sourceVoice, m_voiceCallback, CAESinkXAudio::VoiceCallback::mBufferEnd, and SafeDestroyVoice().
Drain()
void CAESinkXAudio::Drain () override virtual
Todo:
use FormatMessage for a human readable error message
Reimplemented from IAESink.
References AddEndOfStreamPacket(), GetLastError(), LOGERROR, m_format, m_framesInBuffers, m_running, AEAudioFormat::m_sampleRate, m_sinkFrames, m_sourceVoice, CAESinkXAudio::VoiceCallback::m_StreamEndEvent, and m_voiceCallback.
EnumerateDevicesEx()
void CAESinkXAudio::EnumerateDevicesEx (AEDeviceInfoList & deviceInfoList, bool force = false) static
References AE_FMT_FLOAT, AE_FMT_INVALID, AE_FMT_RAW, AE_FMT_S24BE4, AE_FMT_S24NE4MSB, AEChannelNames, CAEUtil::DataFormatToBits(), FAILED, CWIN32Util::FormatHRESULT(), CAESinkFactoryWin::GetRendererDetailsWinRT(), CSysInfo::IsWindowsVersionAtLeast(), LOGERROR, CAEDeviceInfo::m_channels, CAEDeviceInfo::m_dataFormats, CAEDeviceInfo::m_deviceName, CAEDeviceInfo::m_deviceType, CAEDeviceInfo::m_displayName, CAEDeviceInfo::m_displayNameExtra, CAEDeviceInfo::m_onlyPCM, CAEDeviceInfo::m_sampleRates, CAEDeviceInfo::m_streamTypes, CAEDeviceInfo::m_wantsIECPassthrough, CAEChannelInfo::Reset(), SafeDestroyVoice(), KODI::PLATFORM::WINDOWS::ToW(), WASAPI_SPEAKER_COUNT, WASAPIChannelOrder, WASAPISampleRateCount, WASAPISampleRates, and CSysInfo::WindowsVersionWin10.
Referenced by Register().
GetCacheTotal()
double CAESinkXAudio::GetCacheTotal () override virtual
Implements IAESink.
References m_format, AEAudioFormat::m_frames, m_initialized, and AEAudioFormat::m_sampleRate.
GetDelay()
void CAESinkXAudio::GetDelay (AEDelayStatus & status) override virtual
Return a timestamped status structure with delay and sink info.
Parameters
status structure filled with sink status
Implements IAESink.
References m_format, m_initialized, AEAudioFormat::m_sampleRate, m_sinkFrames, m_sourceVoice, and AEDelayStatus::SetDelay().
GetLatency()
double CAESinkXAudio::GetLatency () override virtual
Reimplemented from IAESink.
References m_format, m_initialized, AEAudioFormat::m_sampleRate, and m_xAudio2.
GetName()
virtual const char * CAESinkXAudio::GetName () inline virtual
Implements IAESink.
Initialize()
bool CAESinkXAudio::Initialize (AEAudioFormat & format, std::string & device) override virtual
Implements IAESink.
References CAEUtil::DataFormatToStr(), InitializeInternal(), LOGERROR, LOGINFO, m_initialized, and m_isDirty.
InitializeInternal()
bool CAESinkXAudio::InitializeInternal (std::string deviceId, AEAudioFormat & format) private
References AE_FMT_FLOAT, AE_FMT_INVALID, AE_FMT_MAX, AE_FMT_RAW, AE_FMT_S16NE, AE_FMT_S24NE3, AE_FMT_S24NE4MSB, AE_FMT_S32NE, CAESinkFactoryWin::AEChannelsFromSpeakerMask(), sampleFormat::bitsPerSample, CAESinkFactoryWin::BuildWaveFormatExtensible(), CAESinkFactoryWin::ChLayoutToChMask(), CAEChannelInfo::Count(), CAEUtil::DataFormatToStr(), FAILED, CWIN32Util::FormatHRESULT(), KODI::PLATFORM::WINDOWS::FromW(), CServiceBroker::GetLogging(), CSysInfo::IsWindowsVersionAtLeast(), layoutsList, CLog::Log(), LOGAUDIO, LOGDEBUG, LOGERROR, LOGINFO, m_format, m_masterVoice, m_sourceVoice, m_voiceCallback, m_xAudio2, SafeDestroyVoice(), sampleFormat::subFormat, sampleFormat::subFormatType, testFormats, KODI::PLATFORM::WINDOWS::ToW(), sampleFormat::validBitsPerSample, WASAPISampleRateCount, WASAPISampleRates, and CSysInfo::WindowsVersionWin10.
Referenced by Initialize().
Register()
void CAESinkXAudio::Register () static
References Create(), AE::AESinkRegEntry::createFunc, EnumerateDevicesEx(), AE::AESinkRegEntry::enumerateFunc, AE::CAESinkFactory::RegisterSink(), and AE::AESinkRegEntry::sinkName.
Referenced by CWinSystemWin10::CWinSystemWin10(), and CWinSystemWin32::CWinSystemWin32().
Member Data Documentation
m_avgTimeWaiting
double CAESinkXAudio::m_avgTimeWaiting {50.0} private
Referenced by AddPackets().
m_format
AEAudioFormat CAESinkXAudio::m_format private
Referenced by AddPackets(), BuildXAudio2Buffer(), Drain(), GetCacheTotal(), GetDelay(), GetLatency(), and InitializeInternal().
m_framesInBuffers
std::atomic<uint16_t> CAESinkXAudio::m_framesInBuffers {0} private
Referenced by AddEndOfStreamPacket(), AddPackets(), Deinitialize(), Drain(), and CAESinkXAudio::buffer_ctx::~buffer_ctx().
m_initialized
bool CAESinkXAudio::m_initialized {false} private
Referenced by AddPackets(), Deinitialize(), GetCacheTotal(), GetDelay(), GetLatency(), and Initialize().
m_isDirty
bool CAESinkXAudio::m_isDirty {false} private
Referenced by AddPackets(), Deinitialize(), and Initialize().
m_isSuspended
bool CAESinkXAudio::m_isSuspended {false} private
m_masterVoice
IXAudio2MasteringVoice* CAESinkXAudio::m_masterVoice {nullptr} private
Referenced by Deinitialize(), and InitializeInternal().
m_running
bool CAESinkXAudio::m_running {false} private
Referenced by AddPackets(), Deinitialize(), and Drain().
m_sinkFrames
uint64_t CAESinkXAudio::m_sinkFrames {0} private
Referenced by AddEndOfStreamPacket(), AddPackets(), Deinitialize(), Drain(), and GetDelay().
m_sourceVoice
IXAudio2SourceVoice* CAESinkXAudio::m_sourceVoice {nullptr} private
Referenced by AddEndOfStreamPacket(), AddPackets(), Deinitialize(), Drain(), GetDelay(), and InitializeInternal().
m_timerFreq
LARGE_INTEGER CAESinkXAudio::m_timerFreq {} private
Referenced by AddPackets(), and CAESinkXAudio().
m_voiceCallback
VoiceCallback CAESinkXAudio::m_voiceCallback private
Referenced by AddPackets(), Deinitialize(), Drain(), and InitializeInternal().
m_xAudio2
Microsoft::WRL::ComPtr<IXAudio2> CAESinkXAudio::m_xAudio2 private
Referenced by CAESinkXAudio(), GetLatency(), InitializeInternal(), and ~CAESinkXAudio().
The documentation for this class was generated from the following files:
AESinkXAudio.h
AESinkXAudio.cpp