Kodi Documentation: PVR::CPVRRecordingsPath Class Reference
PVR::CPVRRecordingsPath Class Reference
#include <PVRRecordingsPath.h>
Public Member Functions
CPVRRecordingsPath (const std::string &strPath)
CPVRRecordingsPath (bool bDeleted, bool bRadio)
CPVRRecordingsPath (bool bDeleted, bool bRadio, const std::string &strDirectory, const std::string &strTitle, int iSeason, int iEpisode, int iYear, const std::string &strSubtitle, const std::string &strChannelName, const CDateTime &recordingTime, const std::string &strId)
operator std::string () const
bool IsValid () const
const std::string & GetPath () const
bool IsRecordingsRoot () const
bool IsActive () const
bool IsDeleted () const
bool IsRadio () const
bool IsTV () const
std::string GetUnescapedDirectoryPath () const
std::string GetUnescapedSubDirectoryPath (const std::string &strPath) const
const std::string GetTitle () const
void AppendSegment (const std::string &strSegment)
Static Public Attributes
static const std::string PATH_RECORDINGS = "pvr://recordings/"
static const std::string PATH_ACTIVE_TV_RECORDINGS = "pvr://recordings/tv/active/"
static const std::string PATH_ACTIVE_RADIO_RECORDINGS
static const std::string PATH_DELETED_TV_RECORDINGS = "pvr://recordings/tv/deleted/"
static const std::string PATH_DELETED_RADIO_RECORDINGS
Private Member Functions
size_t GetDirectoryPathPosition () const
Static Private Member Functions
static std::string TrimSlashes (const std::string &strString)
Private Attributes
bool m_bValid
bool m_bRoot
bool m_bActive
bool m_bRadio
std::string m_directoryPath
std::string m_params
std::string m_path
Constructor & Destructor Documentation
CPVRRecordingsPath() [1/3]
CPVRRecordingsPath::CPVRRecordingsPath (const std::string & strPath) explicit
References GetDirectoryPathPosition(), m_bActive, m_bRadio, m_bRoot, m_bValid, m_directoryPath, m_params, m_path, URIUtils::SplitPath(), and TrimSlashes().
CPVRRecordingsPath() [2/3]
CPVRRecordingsPath::CPVRRecordingsPath (bool bDeleted, bool bRadio)
CPVRRecordingsPath() [3/3]
CPVRRecordingsPath::CPVRRecordingsPath (bool bDeleted, bool bRadio, const std::string & strDirectory, const std::string & strTitle, int iSeason, int iEpisode, int iYear, const std::string & strSubtitle, const std::string & strChannelName, const CDateTime & recordingTime, const std::string & strId)
References CDateTime::GetAsSaveString(), m_directoryPath, m_params, m_path, and TrimSlashes().
Member Function Documentation
AppendSegment()
void CPVRRecordingsPath::AppendSegment (const std::string & strSegment)
References m_bRoot, m_bValid, m_directoryPath, m_path, and TrimSlashes().
Referenced by anonymous_namespace{PVRGUIDirectory.cpp}::GetGetRecordingsSubDirectories().
GetDirectoryPathPosition()
size_t CPVRRecordingsPath::GetDirectoryPathPosition () const private
References m_bActive, m_bRadio, PATH_ACTIVE_RADIO_RECORDINGS, PATH_ACTIVE_TV_RECORDINGS, PATH_DELETED_RADIO_RECORDINGS, and PATH_DELETED_TV_RECORDINGS.
Referenced by CPVRRecordingsPath().
GetPath()
const std::string & PVR::CPVRRecordingsPath::GetPath () const inline
References m_path.
GetTitle()
const std::string CPVRRecordingsPath::GetTitle () const
References CRegExp::GetMatch(), m_bValid, m_path, CRegExp::RegComp(), and CRegExp::RegFind().
Referenced by PVR::CPVRRecording::GetTitleFromURL().
GetUnescapedDirectoryPath()
std::string CPVRRecordingsPath::GetUnescapedDirectoryPath () const
References m_directoryPath.
Referenced by PVR::CPVRGUIDirectory::GetRecordingsDirectory(), GetUnescapedSubDirectoryPath(), and PVR::CGUIWindowPVRRecordingsBase::UpdateButtons().
GetUnescapedSubDirectoryPath()
std::string CPVRRecordingsPath::GetUnescapedSubDirectoryPath (const std::string & strPath) const
References GetUnescapedDirectoryPath(), and TrimSlashes().
Referenced by anonymous_namespace{PVRGUIDirectory.cpp}::GetGetRecordingsSubDirectories().
IsActive()
bool PVR::CPVRRecordingsPath::IsActive () const inline
References m_bActive.
Referenced by IsDeleted().
IsDeleted()
bool PVR::CPVRRecordingsPath::IsDeleted () const inline
References IsActive().
Referenced by PVR::CPVRRecordings::GetByPath(), and PVR::CPVRGUIDirectory::GetRecordingsDirectory().
IsRadio()
bool PVR::CPVRRecordingsPath::IsRadio () const inline
References m_bRadio.
Referenced by PVR::CPVRRecordings::GetByPath(), anonymous_namespace{PVRGUIDirectory.cpp}::GetGetRecordingsSubDirectories(), PVR::CPVRGUIDirectory::GetRecordingsDirectory(), and IsTV().
IsRecordingsRoot()
bool PVR::CPVRRecordingsPath::IsRecordingsRoot () const inline
References m_bRoot.
Referenced by PVR::CGUIViewStateWindowPVRRecordings::HideParentDirItems(), PVR::CGUIWindowPVRRecordingsBase::OnAction(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), and PVR::CGUIWindowPVRRecordingsBase::Update().
IsTV()
bool PVR::CPVRRecordingsPath::IsTV () const inline
References IsRadio().
IsValid()
bool PVR::CPVRRecordingsPath::IsValid () const inline
References m_bValid.
Referenced by PVR::CPVRRecordings::GetByPath(), PVR::CPVRGUIDirectory::GetRecordingsDirectory(), PVR::CGUIWindowPVRRecordingsBase::OnAction(), PVR::CGUIWindowPVRRecordingsBase::OnMessage(), PVR::CGUIWindowPVRRecordingsBase::Update(), and PVR::CGUIWindowPVRRecordingsBase::UpdateButtons().
operator std::string()
PVR::CPVRRecordingsPath::operator std::string () const inline
References m_path.
TrimSlashes()
std::string CPVRRecordingsPath::TrimSlashes (const std::string & strString) static private
Referenced by AppendSegment(), CPVRRecordingsPath(), CPVRRecordingsPath(), and GetUnescapedSubDirectoryPath().
Member Data Documentation
m_bActive
bool PVR::CPVRRecordingsPath::m_bActive private
Referenced by CPVRRecordingsPath(), GetDirectoryPathPosition(), and IsActive().
m_bRadio
bool PVR::CPVRRecordingsPath::m_bRadio private
Referenced by CPVRRecordingsPath(), GetDirectoryPathPosition(), and IsRadio().
m_bRoot
bool PVR::CPVRRecordingsPath::m_bRoot private
Referenced by AppendSegment(), CPVRRecordingsPath(), and IsRecordingsRoot().
m_bValid
bool PVR::CPVRRecordingsPath::m_bValid private
Referenced by AppendSegment(), CPVRRecordingsPath(), GetTitle(), and IsValid().
m_directoryPath
std::string PVR::CPVRRecordingsPath::m_directoryPath private
Referenced by AppendSegment(), CPVRRecordingsPath(), CPVRRecordingsPath(), and GetUnescapedDirectoryPath().
m_params
std::string PVR::CPVRRecordingsPath::m_params private
Referenced by CPVRRecordingsPath(), and CPVRRecordingsPath().
m_path
std::string PVR::CPVRRecordingsPath::m_path private
Referenced by AppendSegment(), CPVRRecordingsPath(), CPVRRecordingsPath(), GetPath(), GetTitle(), and operator std::string().
PATH_ACTIVE_RADIO_RECORDINGS
const std::string CPVRRecordingsPath::PATH_ACTIVE_RADIO_RECORDINGS static
Initial value:
=
    "pvr://recordings/radio/active/"
Referenced by PVR::CGUIWindowPVRProvidersBase::ActivateRecordingsWindow(), GetDirectoryPathPosition(), anonymous_namespace{PVRGUIDirectory.cpp}::GetRootDirectory(), and CGUIDialogMediaSource::OnPathBrowse().
PATH_ACTIVE_TV_RECORDINGS
const std::string CPVRRecordingsPath::PATH_ACTIVE_TV_RECORDINGS = "pvr://recordings/tv/active/" static
Referenced by PVR::CGUIWindowPVRProvidersBase::ActivateRecordingsWindow(), GetDirectoryPathPosition(), anonymous_namespace{PVRGUIDirectory.cpp}::GetRootDirectory(), and CGUIDialogMediaSource::OnPathBrowse().
PATH_DELETED_RADIO_RECORDINGS
const std::string CPVRRecordingsPath::PATH_DELETED_RADIO_RECORDINGS static
Initial value:
=
    "pvr://recordings/radio/deleted/"
Referenced by GetDirectoryPathPosition(), and CGUIDialogMediaSource::OnPathBrowse().
PATH_DELETED_TV_RECORDINGS
const std::string CPVRRecordingsPath::PATH_DELETED_TV_RECORDINGS = "pvr://recordings/tv/deleted/" static
Referenced by GetDirectoryPathPosition(), and CGUIDialogMediaSource::OnPathBrowse().
PATH_RECORDINGS
const std::string CPVRRecordingsPath::PATH_RECORDINGS = "pvr://recordings/" static
Referenced by PVR::CPVRGUIActionsDatabase::ResetDatabase().
The documentation for this class was generated from the following files:
PVRRecordingsPath.h
PVRRecordingsPath.cpp