Kodi Documentation: CStopWatch Class Reference
CStopWatch Class Reference
#include <Stopwatch.h>
Public Member Functions
CStopWatch ()=default
~CStopWatch ()=default
bool IsRunning () const
Retrieve the running state of the stopwatch.
void StartZero ()
Record start time and change state to running.
void Start ()
Record start time and change state to running, only if the stopwatch is stopped.
void Stop ()
Record stop time and change state to not running.
void Reset ()
Set the start time such that time elapsed is now zero.
float GetElapsedSeconds () const
Retrieve time elapsed between the last call to Start(), StartZero() or Reset() and; if running, now; if stopped, the last call to Stop().
float GetElapsedMilliseconds () const
Retrieve time elapsed between the last call to Start(), StartZero() or Reset() and; if running, now; if stopped, the last call to Stop().
Private Attributes
std::chrono::time_point< std::chrono::steady_clock > m_startTick
std::chrono::time_point< std::chrono::steady_clock > m_stopTick
bool m_isRunning = false
Constructor & Destructor Documentation
CStopWatch()
CStopWatch::CStopWatch () default
~CStopWatch()
CStopWatch::~CStopWatch () default
Member Function Documentation
GetElapsedMilliseconds()
float CStopWatch::GetElapsedMilliseconds () const inline
Retrieve time elapsed between the last call to Start(), StartZero() or Reset() and; if running, now; if stopped, the last call to Stop().
Returns
Elapsed time, in milliseconds, as a float.
References m_isRunning, m_startTick, and m_stopTick.
Referenced by CGUIBaseContainer::DoProcess(), CSeekHandler::FrameMove(), CGUIWindowMusicNav::FrameMove(), CGUIBaseContainer::GetCondition(), CGUIBaseContainer::OnJumpLetter(), CGUIEditControl::OnSMSCharacter(), CApplication::Process(), CGUIMultiImage::Process(), CGUIEditControl::ProcessText(), TEST(), TEST(), TEST(), and CGUIBaseContainer::UpdateScrollOffset().
GetElapsedSeconds()
float CStopWatch::GetElapsedSeconds () const inline
Retrieve time elapsed between the last call to Start(), StartZero() or Reset() and; if running, now; if stopped, the last call to Stop().
Returns
Elapsed time, in seconds, as a float.
References m_isRunning, m_startTick, and m_stopTick.
Referenced by CApplication::CheckDelayedPlayerRestart(), CApplicationPowerHandling::CheckScreenSaverAndDPMS(), CApplicationPowerHandling::CheckShutdown(), XFILE::CFile::Copy(), CDVDRadioRDSData::DecodeRTPlus(), CGUIWindowVisualisation::FrameMove(), CApplication::FrameMove(), CNetworkWin32::GetInterfaceList(), CApplicationPowerHandling::GlobalIdleTime(), CApplicationPowerHandling::NavigationIdleTime(), TEST(), and TEST().
IsRunning()
bool CStopWatch::IsRunning () const inline
Retrieve the running state of the stopwatch.
Returns
True if stopwatch has been started but not stopped.
References m_isRunning.
Referenced by CApplicationPowerHandling::CheckScreenSaverAndDPMS(), CApplicationPowerHandling::CheckShutdown(), CGUIBaseContainer::DoProcess(), CGUIWindowMusicNav::FrameMove(), CGUIWindowVisualisation::FrameMove(), CGUIBaseContainer::GetCondition(), CGUIEditControl::GetDisplayedText(), CApplicationPowerHandling::GlobalIdleTime(), CApplicationPowerHandling::NavigationIdleTime(), CGUIWindowVisualisation::OnAction(), CGUIEditControl::OnSMSCharacter(), CGUIMultiImage::Process(), CGUIEditControl::ProcessText(), TEST(), TEST(), TEST(), and CGUIBaseContainer::UpdateScrollOffset().
Reset()
void CStopWatch::Reset () inline
Set the start time such that time elapsed is now zero.
References m_isRunning, m_startTick, and m_stopTick.
Referenced by CApplication::CheckDelayedPlayerRestart(), CApplication::Process(), CSkinTimer::Reset(), and TEST().
Start()
void CStopWatch::Start () inline
Record start time and change state to running, only if the stopwatch is stopped.
References m_isRunning, and StartZero().
Referenced by CGUIBaseContainer::OnMouseEvent(), CGUIBaseContainer::ScrollToOffset(), CSkinTimer::Start(), TEST(), TEST(), and TEST().
StartZero()
void CStopWatch::StartZero () inline
Record start time and change state to running.
References m_isRunning, and m_startTick.
Referenced by CGUIWindowLoginScreen::CGUIWindowLoginScreen(), CSeekHandler::ChangeTimeCode(), CApplicationPowerHandling::CheckShutdown(), XFILE::CFile::Copy(), CDVDRadioRDSData::DecodeRTPlus(), CApplication::DelayedPlayerRestart(), CGUIWindowVisualisation::FrameMove(), CApplication::FrameMove(), CApplicationPowerHandling::GlobalIdleTime(), CApplication::Initialize(), CApplicationPowerHandling::NavigationIdleTime(), CGUIWindowVisualisation::OnAction(), CGUIMultiImage::OnDirectoryLoaded(), CGUIBaseContainer::OnJumpLetter(), CGUIBaseContainer::OnMessage(), CGUIWindowMusicNav::OnMessage(), CGUIWindowVisualisation::OnMessage(), CGUIEditControl::OnSMSCharacter(), CGUIMultiImage::Process(), CNetworkWin32::queryInterfaceList(), CApplicationPowerHandling::ResetNavigationTimer(), CApplicationPowerHandling::ResetScreenSaver(), CApplicationPowerHandling::ResetScreenSaverTimer(), CApplicationPowerHandling::ResetShutdownTimers(), CApplicationPowerHandling::ResetSystemIdleTimer(), CGUIBaseContainer::ScrollToOffset(), CSeekHandler::Seek(), CSkinTimer::Start(), Start(), CWinIdleTimer::StartZero(), and TEST().
Stop()
void CStopWatch::Stop () inline
Record stop time and change state to not running.
References m_isRunning, and m_stopTick.
Referenced by CApplication::CheckDelayedPlayerRestart(), CApplicationPowerHandling::CheckShutdown(), CGUIBaseContainer::DoProcess(), CGUIWindowMusicNav::FrameMove(), CGUIWindowVisualisation::FrameMove(), CGUIBaseContainer::OnAction(), CGUIWindowVisualisation::OnAction(), CGUIWindowVisualisation::OnMessage(), CGUIBaseContainer::OnMouseEvent(), CGUIBaseContainer::ScrollToOffset(), CGUIEditControl::SetFocus(), CSkinTimer::Stop(), CApplicationPowerHandling::StopScreenSaverTimer(), CApplicationPowerHandling::StopShutdownTimer(), TEST(), CGUIBaseContainer::UpdateScrollOffset(), CGUIEditControl::UpdateText(), and CNetworkWin32::~CNetworkWin32().
Member Data Documentation
m_isRunning
bool CStopWatch::m_isRunning = false private
Referenced by GetElapsedMilliseconds(), GetElapsedSeconds(), IsRunning(), Reset(), Start(), StartZero(), and Stop().
m_startTick
std::chrono::time_point<std::chrono::steady_clock> CStopWatch::m_startTick private
Referenced by GetElapsedMilliseconds(), GetElapsedSeconds(), Reset(), and StartZero().
m_stopTick
std::chrono::time_point<std::chrono::steady_clock> CStopWatch::m_stopTick private
Referenced by GetElapsedMilliseconds(), GetElapsedSeconds(), Reset(), and Stop().
The documentation for this class was generated from the following file:
Stopwatch.h