var _p_v_r_g_u_i_actions_database_8cpp =
[
    [ "anonymous_namespace{PVRGUIActionsDatabase.cpp}::CPVRGUIDatabaseResetComponentsSelector", "de/dfa/classanonymous__namespace_02_p_v_r_g_u_i_actions_database_8cpp_03_1_1_c_p_v_r_g_u_i_database_reset_components_selector.html", "de/dfa/classanonymous__namespace_02_p_v_r_g_u_i_actions_database_8cpp_03_1_1_c_p_v_r_g_u_i_database_reset_components_selector" ]
];