Kodi Documentation: KODI::GAME::CControllerSelect Class Reference
KODI::GAME::CControllerSelect Class Reference
Games
#include <ControllerSelect.h>
Public Member Functions
CControllerSelect ()
~CControllerSelect () override
void Initialize (ControllerVector controllers, ControllerPtr defaultController, bool showDisconnect, const std::function< void(ControllerPtr)> &callback)
void Deinitialize ()
Public Member Functions inherited from CThread
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Protected Member Functions
void Process () override
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
Private Attributes
ControllerVector m_controllers
ControllerPtr m_defaultController
bool m_showDisconnect = true
std::function< void(ControllerPtr)> m_callback
Additional Inherited Members
Static Public Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CControllerSelect()
CControllerSelect::CControllerSelect ()
~CControllerSelect()
CControllerSelect::~CControllerSelect () override default
Member Function Documentation
Deinitialize()
void CControllerSelect::Deinitialize ()
References m_callback, m_controllers, m_defaultController, m_showDisconnect, and CThread::StopThread().
Referenced by Initialize().
Initialize()
void CControllerSelect::Initialize (ControllerVector controllers, ControllerPtr defaultController, bool showDisconnect, const std::function< void(ControllerPtr)> & callback)
References CThread::Create(), Deinitialize(), m_callback, m_controllers, m_defaultController, and m_showDisconnect.
Referenced by KODI::GAME::CGUIPortList::OnItemSelect().
Process()
void CControllerSelect::Process (void) override protected virtual
Reimplemented from CThread.
References CFileItemList::Add(), g_localizeStrings, CLocalizeStrings::Get(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CLog::Log(), LOGDEBUG, CThread::m_bStop, m_callback, m_controllers, m_defaultController, m_showDisconnect, CFileItemList::Size(), and WINDOW_DIALOG_SELECT.
Member Data Documentation
m_callback
std::function<void(ControllerPtr)> KODI::GAME::CControllerSelect::m_callback private
Referenced by Deinitialize(), Initialize(), and Process().
m_controllers
ControllerVector KODI::GAME::CControllerSelect::m_controllers private
Referenced by Deinitialize(), Initialize(), and Process().
m_defaultController
ControllerPtr KODI::GAME::CControllerSelect::m_defaultController private
Referenced by Deinitialize(), Initialize(), and Process().
m_showDisconnect
bool KODI::GAME::CControllerSelect::m_showDisconnect = true private
Referenced by Deinitialize(), Initialize(), and Process().
The documentation for this class was generated from the following files:
ControllerSelect.h
ControllerSelect.cpp