Kodi Documentation: ADDON::CAddonVersion Class Reference
ADDON::CAddonVersion Class Reference
#include <AddonVersion.h>
Public Member Functions
CAddonVersion (const char *version=nullptr)
CAddonVersion (const std::string &version)
CAddonVersion (const CAddonVersion &other)=default
CAddonVersion (CAddonVersion &&other)=default
CAddonVersion & operator= (const CAddonVersion &other)=default
CAddonVersion & operator= (CAddonVersion &&other)=default
virtual ~CAddonVersion ()=default
int Epoch () const
const std::string & Upstream () const
const std::string & Revision () const
bool operator< (const CAddonVersion &other) const
bool operator> (const CAddonVersion &other) const
bool operator<= (const CAddonVersion &other) const
bool operator>= (const CAddonVersion &other) const
bool operator== (const CAddonVersion &other) const
bool operator!= (const CAddonVersion &other) const
std::string asString () const
bool empty () const
Static Public Member Functions
static bool SplitFileName (std::string &ID, std::string &version, const std::string &filename)
Static Protected Member Functions
static int CompareComponent (const char *a, const char *b)
Protected Attributes
int mEpoch
std::string mUpstream
std::string mRevision
Constructor & Destructor Documentation
CAddonVersion() [1/4]
ADDON::CAddonVersion::CAddonVersion (const char * version = nullptr) explicit
CAddonVersion() [2/4]
ADDON::CAddonVersion::CAddonVersion (const std::string & version) explicit
CAddonVersion() [3/4]
ADDON::CAddonVersion::CAddonVersion (const CAddonVersion & other) default
CAddonVersion() [4/4]
ADDON::CAddonVersion::CAddonVersion (CAddonVersion && other) default
~CAddonVersion()
virtual ADDON::CAddonVersion::~CAddonVersion () virtual default
Member Function Documentation
asString()
std::string ADDON::CAddonVersion::asString () const
References mEpoch, mRevision, and mUpstream.
Referenced by ADDON::CAddonDll::CheckAPIVersion(), ADDON::CAddonInstaller::CheckDependencies(), KODI::RETRO::CReversiblePlayback::CommitSavestate(), ADDON::CRepository::CRepository(), ADDON::CAddonMgr::FindAddon(), ADDON::Interface_Base::get_addon_info(), ADDON::CAddonDatabase::GetAddon(), ADDON::CScraper::GetVideoDetails(), ADDON::CAddonInstaller::Install(), anonymous_namespace{AddonInstaller.cpp}::CAddonInstallJob::Install(), CPythonInvoker::onPythonModuleInitialization(), and ADDON::CAddonDatabase::SetRepoUpdateData().
CompareComponent()
int ADDON::CAddonVersion::CompareComponent (const char * a, const char * b) static protected
Compare two components of a Debian-style version. Return -1, 0, or 1 if a is less than, equal to, or greater than b, respectively.
Referenced by operator<(), and operator==().
empty()
bool ADDON::CAddonVersion::empty () const
References empty(), mEpoch, mRevision, and mUpstream.
Referenced by ADDON::CAddonDll::CheckAPIVersion(), ADDON::CRepository::CRepository(), empty(), and CGUIDialogAddonInfo::OnSelectVersion().
Epoch()
int ADDON::CAddonVersion::Epoch () const inline
References mEpoch.
operator!=()
bool ADDON::CAddonVersion::operator!= (const CAddonVersion & other) const
operator<()
bool ADDON::CAddonVersion::operator< (const CAddonVersion & other) const
References CompareComponent(), mEpoch, mRevision, and mUpstream.
operator<=()
bool ADDON::CAddonVersion::operator<= (const CAddonVersion & other) const
operator=() [1/2]
CAddonVersion & ADDON::CAddonVersion::operator= (CAddonVersion && other) default
operator=() [2/2]
CAddonVersion & ADDON::CAddonVersion::operator= (const CAddonVersion & other) default
operator==()
bool ADDON::CAddonVersion::operator== (const CAddonVersion & other) const
References CompareComponent(), mEpoch, mRevision, and mUpstream.
operator>()
bool ADDON::CAddonVersion::operator> (const CAddonVersion & other) const
operator>=()
bool ADDON::CAddonVersion::operator>= (const CAddonVersion & other) const
Revision()
const std::string & ADDON::CAddonVersion::Revision () const inline
References mRevision.
SplitFileName()
bool ADDON::CAddonVersion::SplitFileName (std::string & ID, std::string & version, const std::string & filename) static
References ID.
Referenced by ADDON::CAddonInstaller::EnumeratePackageFolder(), and CGUIDialogAddonInfo::OnSelectVersion().
Upstream()
const std::string & ADDON::CAddonVersion::Upstream () const inline
References mUpstream.
Member Data Documentation
mEpoch
int ADDON::CAddonVersion::mEpoch protected
Referenced by asString(), empty(), Epoch(), operator<(), and operator==().
mRevision
std::string ADDON::CAddonVersion::mRevision protected
Referenced by asString(), empty(), operator<(), operator==(), and Revision().
mUpstream
std::string ADDON::CAddonVersion::mUpstream protected
Referenced by asString(), empty(), operator<(), operator==(), and Upstream().
The documentation for this class was generated from the following files:
AddonVersion.h
AddonVersion.cpp