Kodi Documentation: TestCharsetConverter.cpp File Reference
TestCharsetConverter.cpp File Reference
#include "ServiceBroker.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "utils/CharsetConverter.h"
#include "utils/Utf8Utils.h"
#include <gtest/gtest.h>
Classes
class TestCharsetConverter
Functions
TEST_F (TestCharsetConverter, utf8ToW)
TEST_F (TestCharsetConverter, subtitleCharsetToUtf8)
TEST_F (TestCharsetConverter, utf8ToStringCharset_1)
TEST_F (TestCharsetConverter, utf8ToStringCharset_2)
TEST_F (TestCharsetConverter, utf8ToSystem)
TEST_F (TestCharsetConverter, utf8To_ASCII)
TEST_F (TestCharsetConverter, stringCharsetToUtf8)
TEST_F (TestCharsetConverter, isValidUtf8_1)
TEST_F (TestCharsetConverter, isValidUtf8_2)
TEST_F (TestCharsetConverter, isValidUtf8_3)
TEST_F (TestCharsetConverter, isValidUtf8_4)
TEST_F (TestCharsetConverter, wToUTF8)
TEST_F (TestCharsetConverter, utf8logicalToVisualBiDi)
TEST_F (TestCharsetConverter, getCharsetLabels)
TEST_F (TestCharsetConverter, getCharsetLabelByName)
TEST_F (TestCharsetConverter, getCharsetNameByLabel)
TEST_F (TestCharsetConverter, unknownToUTF8_1)
TEST_F (TestCharsetConverter, unknownToUTF8_2)
TEST_F (TestCharsetConverter, toW)
TEST_F (TestCharsetConverter, fromW)
Variables
static const char refutf16LE3 []
Function Documentation
TEST_F() [1/20]
TEST_F (TestCharsetConverter , fromW)
References g_charsetConverter.
TEST_F() [2/20]
TEST_F (TestCharsetConverter , getCharsetLabelByName)
References g_charsetConverter.
TEST_F() [3/20]
TEST_F (TestCharsetConverter , getCharsetLabels)
Todo:
Resolve correct input/output for this function
References g_charsetConverter.
TEST_F() [4/20]
TEST_F (TestCharsetConverter , getCharsetNameByLabel)
References g_charsetConverter.
TEST_F() [5/20]
TEST_F (TestCharsetConverter , isValidUtf8_1)
References EXPECT_TRUE(), g_charsetConverter, CUtf8Utils::isValidUtf8(), and refutf16LE3.
TEST_F() [6/20]
TEST_F (TestCharsetConverter , isValidUtf8_2)
References CUtf8Utils::isValidUtf8(), and refutf16LE3.
TEST_F() [7/20]
TEST_F (TestCharsetConverter , isValidUtf8_3)
References EXPECT_TRUE(), g_charsetConverter, CUtf8Utils::isValidUtf8(), and refutf16LE3.
TEST_F() [8/20]
TEST_F (TestCharsetConverter , isValidUtf8_4)
References CUtf8Utils::isValidUtf8(), and refutf16LE3.
TEST_F() [9/20]
TEST_F (TestCharsetConverter , stringCharsetToUtf8)
OSX has its own 'special' utf-8 charset which we use (see UTF8_SOURCE in CharsetConverter.cpp)
References g_charsetConverter, and refutf16LE3.
TEST_F() [10/20]
TEST_F (TestCharsetConverter , subtitleCharsetToUtf8)
References g_charsetConverter.
TEST_F() [11/20]
TEST_F (TestCharsetConverter , toW)
References g_charsetConverter.
TEST_F() [12/20]
TEST_F (TestCharsetConverter , unknownToUTF8_1)
References g_charsetConverter.
TEST_F() [13/20]
TEST_F (TestCharsetConverter , unknownToUTF8_2)
References g_charsetConverter.
TEST_F() [14/20]
TEST_F (TestCharsetConverter , utf8logicalToVisualBiDi)
References g_charsetConverter.
TEST_F() [15/20]
TEST_F (TestCharsetConverter , utf8To_ASCII)
References g_charsetConverter.
TEST_F() [16/20]
TEST_F (TestCharsetConverter , utf8ToStringCharset_1)
References g_charsetConverter.
TEST_F() [17/20]
TEST_F (TestCharsetConverter , utf8ToStringCharset_2)
References g_charsetConverter.
TEST_F() [18/20]
TEST_F (TestCharsetConverter , utf8ToSystem)
References g_charsetConverter.
TEST_F() [19/20]
TEST_F (TestCharsetConverter , utf8ToW)
References g_charsetConverter.
TEST_F() [20/20]
TEST_F (TestCharsetConverter , wToUTF8)
Todo:
Resolve correct input/output for this function
References g_charsetConverter.
Variable Documentation
refutf16LE3
const char refutf16LE3[] static
Initial value:
= "T\377E\377S\377T\377?\377S\377T\377"
                                  "R\377I\377N\377G\377#\377H\377A\377"
                                  "R\377S\377E\377T\377\064\377O\377\065"
                                  "\377T\377F\377\030\377"
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().