Kodi Documentation: KODI::RETRO::CReversiblePlayback Class Reference
KODI::RETRO::CReversiblePlayback Class Reference
#include <ReversiblePlayback.h>
Public Member Functions
CReversiblePlayback (GAME::CGameClient *gameClient, CRPRenderManager &renderManager, CCheevos *cheevos, CGUIGameMessenger &guiMessenger, double fps, size_t serializeSize)
~CReversiblePlayback () override
void Initialize () override
void Deinitialize () override
bool CanPause () const override
bool CanSeek () const override
unsigned int GetTimeMs () const override
unsigned int GetTotalTimeMs () const override
unsigned int GetCacheTimeMs () const override
void SeekTimeMs (unsigned int timeMs) override
double GetSpeed () const override
void SetSpeed (double speedFactor) override
void PauseAsync () override
std::string CreateSavestate (bool autosave, const std::string &savestatePath="") override
bool LoadSavestate (const std::string &savestatePath) override
void FrameEvent () override
The next frame is being shown.
void RewindEvent () override
The prior frame is being shown.
void Notify (const Observable &obs, const ObservableMessage msg) override
Process a message from an observable.
Public Member Functions inherited from KODI::RETRO::IPlayback
virtual ~IPlayback ()=default
Public Member Functions inherited from KODI::RETRO::IGameLoopCallback
virtual ~IGameLoopCallback ()=default
Public Member Functions inherited from Observer
Observer ()=default
virtual ~Observer ()=default
Private Member Functions
void AddFrame ()
void RewindFrames (uint64_t frames)
void AdvanceFrames (uint64_t frames)
void UpdatePlaybackStats ()
void UpdateMemoryStream ()
void CommitSavestate (bool autosave, const std::string &savePath, const CDateTime &nowUTC, uint64_t timestampFrames)
Private Attributes
GAME::CGameClient *const m_gameClient
CRPRenderManager & m_renderManager
CCheevos *const m_cheevos
CGUIGameMessenger & m_guiMessenger
CGameLoop m_gameLoop
std::unique_ptr< IMemoryStream > m_memoryStream
CCriticalSection m_mutex
std::unique_ptr< CSavestateDatabase > m_savestateDatabase
std::string m_autosavePath {}
std::vector< std::future< void > > m_savestateThreads
CCriticalSection m_savestateMutex
uint64_t m_totalFrameCount = 0
uint64_t m_pastFrameCount = 0
uint64_t m_futureFrameCount = 0
unsigned int m_playTimeMs = 0
unsigned int m_totalTimeMs = 0
unsigned int m_cacheTimeMs = 0
Constructor & Destructor Documentation
CReversiblePlayback()
CReversiblePlayback::CReversiblePlayback (GAME::CGameClient * gameClient, CRPRenderManager & renderManager, CCheevos * cheevos, CGUIGameMessenger & guiMessenger, double fps, size_t serializeSize)
References KODI::GAME::CGameServices::GameSettings(), CServiceBroker::GetGameServices(), Observable::RegisterObserver(), and UpdateMemoryStream().
~CReversiblePlayback()
CReversiblePlayback::~CReversiblePlayback () override
References Deinitialize(), KODI::GAME::CGameServices::GameSettings(), CServiceBroker::GetGameServices(), and Observable::UnregisterObserver().
Member Function Documentation
AddFrame()
void CReversiblePlayback::AddFrame () private
References m_gameClient, m_memoryStream, m_mutex, m_totalFrameCount, KODI::GAME::CGameClient::Serialize(), and UpdatePlaybackStats().
Referenced by FrameEvent().
AdvanceFrames()
void CReversiblePlayback::AdvanceFrames (uint64_t frames) private
References KODI::GAME::CGameClient::Deserialize(), m_gameClient, m_memoryStream, m_mutex, m_totalFrameCount, and UpdatePlaybackStats().
Referenced by SeekTimeMs().
CanPause()
bool KODI::RETRO::CReversiblePlayback::CanPause () const inline override virtual
Implements KODI::RETRO::IPlayback.
CanSeek()
bool KODI::RETRO::CReversiblePlayback::CanSeek () const inline override virtual
Implements KODI::RETRO::IPlayback.
CommitSavestate()
void CReversiblePlayback::CommitSavestate (bool autosave, const std::string & savePath, const CDateTime & nowUTC, uint64_t timestampFrames) private
Todo:
Accumulate playtime instead of deriving it
References KODI::RETRO::CSavestateDatabase::AllocateSavestate(), ADDON::CAddonVersion::asString(), KODI::RETRO::AUTO, XFILE::CFile::Exists(), URIUtils::GetFileName(), KODI::GAME::CGameClient::GetFrameRate(), KODI::GAME::CGameClient::GetGamePath(), KODI::RETRO::CCheevos::GetRichPresenceEvaluation(), ADDON::CAddon::ID(), m_cheevos, m_gameClient, m_guiMessenger, m_memoryStream, m_mutex, m_renderManager, m_savestateDatabase, m_savestateMutex, KODI::RETRO::CSavestateDatabase::MakeThumbnailPath(), KODI::RETRO::MANUAL, KODI::RETRO::CGUIGameMessenger::RefreshSavestates(), savestate, KODI::RETRO::CRPRenderManager::SaveThumbnail(), KODI::RETRO::CRPRenderManager::SaveVideoFrame(), KODI::GAME::CGameClient::Serialize(), KODI::GAME::CGameClient::SerializeSize(), success, and ADDON::CAddon::Version().
Referenced by CreateSavestate().
CreateSavestate()
std::string CReversiblePlayback::CreateSavestate (bool autosave, const std::string & savestatePath = "") override virtual
Todo:
Handle savestates for standalone game clients
Implements KODI::RETRO::IPlayback.
References KODI::RETRO::CRPRenderManager::CacheVideoFrame(), CommitSavestate(), KODI::GAME::CGameClient::GetGamePath(), CDateTime::GetUTCDateTime(), m_autosavePath, m_gameClient, m_renderManager, m_savestateMutex, m_savestateThreads, m_totalFrameCount, KODI::RETRO::CSavestateDatabase::MakeSavestatePath(), and KODI::GAME::CGameClient::SerializeSize().
Deinitialize()
void CReversiblePlayback::Deinitialize () override virtual
Implements KODI::RETRO::IPlayback.
References m_gameLoop, m_savestateThreads, and KODI::RETRO::CGameLoop::Stop().
Referenced by ~CReversiblePlayback().
FrameEvent()
void CReversiblePlayback::FrameEvent () override virtual
The next frame is being shown.
Implements KODI::RETRO::IGameLoopCallback.
References AddFrame(), m_gameClient, and KODI::GAME::CGameClient::RunFrame().
GetCacheTimeMs()
unsigned int KODI::RETRO::CReversiblePlayback::GetCacheTimeMs () const inline override virtual
Implements KODI::RETRO::IPlayback.
References m_cacheTimeMs.
GetSpeed()
double CReversiblePlayback::GetSpeed () const override virtual
Implements KODI::RETRO::IPlayback.
References KODI::RETRO::CGameLoop::GetSpeed(), and m_gameLoop.
GetTimeMs()
unsigned int KODI::RETRO::CReversiblePlayback::GetTimeMs () const inline override virtual
Implements KODI::RETRO::IPlayback.
References m_playTimeMs.
Referenced by SeekTimeMs().
GetTotalTimeMs()
unsigned int KODI::RETRO::CReversiblePlayback::GetTotalTimeMs () const inline override virtual
Implements KODI::RETRO::IPlayback.
References m_totalTimeMs.
Initialize()
void CReversiblePlayback::Initialize () override virtual
Implements KODI::RETRO::IPlayback.
References m_gameLoop, and KODI::RETRO::CGameLoop::Start().
LoadSavestate()
bool CReversiblePlayback::LoadSavestate (const std::string & savestatePath) override virtual
Implements KODI::RETRO::IPlayback.
References KODI::RETRO::CSavestateDatabase::AllocateSavestate(), KODI::RETRO::AUTO, KODI::GAME::CGameClient::Deserialize(), CLog::Log(), LOGERROR, m_autosavePath, m_cheevos, m_gameClient, m_memoryStream, m_mutex, m_savestateDatabase, m_totalFrameCount, KODI::RETRO::CCheevos::ResetRuntime(), savestate, and KODI::GAME::CGameClient::SerializeSize().
Notify()
void CReversiblePlayback::Notify (const Observable & obs, const ObservableMessage msg) override virtual
Process a message from an observable.
Parameters
obs The observable that sends the message.
msg The message.
Implements Observer.
References ObservableMessageSettingsChanged, and UpdateMemoryStream().
PauseAsync()
void CReversiblePlayback::PauseAsync () override virtual
Implements KODI::RETRO::IPlayback.
References m_gameLoop, and KODI::RETRO::CGameLoop::PauseAsync().
RewindEvent()
void CReversiblePlayback::RewindEvent () override virtual
The prior frame is being shown.
Implements KODI::RETRO::IGameLoopCallback.
References m_gameClient, RewindFrames(), and KODI::GAME::CGameClient::RunFrame().
RewindFrames()
void CReversiblePlayback::RewindFrames (uint64_t frames) private
References KODI::GAME::CGameClient::Deserialize(), m_gameClient, m_memoryStream, m_mutex, m_totalFrameCount, and UpdatePlaybackStats().
Referenced by RewindEvent(), and SeekTimeMs().
SeekTimeMs()
void CReversiblePlayback::SeekTimeMs (unsigned int timeMs) override virtual
Implements KODI::RETRO::IPlayback.
References AdvanceFrames(), KODI::RETRO::CGameLoop::FPS(), GetTimeMs(), m_futureFrameCount, m_gameLoop, m_pastFrameCount, RewindFrames(), MathUtils::round_int(), and KODI::RETRO::CGameLoop::SetSpeed().
SetSpeed()
void CReversiblePlayback::SetSpeed (double speedFactor) override virtual
Implements KODI::RETRO::IPlayback.
References m_gameLoop, REWIND_FACTOR, and KODI::RETRO::CGameLoop::SetSpeed().
UpdateMemoryStream()
void CReversiblePlayback::UpdateMemoryStream () private
References KODI::RETRO::CGameLoop::FPS(), KODI::GAME::CGameServices::GameSettings(), CServiceBroker::GetGameServices(), m_cacheTimeMs, m_futureFrameCount, m_gameClient, m_gameLoop, m_memoryStream, m_mutex, m_pastFrameCount, m_playTimeMs, m_totalTimeMs, KODI::GAME::CGameSettings::MaxRewindTimeSec(), KODI::GAME::CGameSettings::RewindEnabled(), MathUtils::round_int(), and KODI::GAME::CGameClient::SerializeSize().
Referenced by CReversiblePlayback(), and Notify().
UpdatePlaybackStats()
void CReversiblePlayback::UpdatePlaybackStats () private
References KODI::RETRO::CGameLoop::FPS(), m_cacheTimeMs, m_futureFrameCount, m_gameLoop, m_memoryStream, m_pastFrameCount, m_playTimeMs, m_totalTimeMs, and MathUtils::round_int().
Referenced by AddFrame(), AdvanceFrames(), and RewindFrames().
Member Data Documentation
m_autosavePath
std::string KODI::RETRO::CReversiblePlayback::m_autosavePath {} private
Referenced by CreateSavestate(), and LoadSavestate().
m_cacheTimeMs
unsigned int KODI::RETRO::CReversiblePlayback::m_cacheTimeMs = 0 private
Referenced by GetCacheTimeMs(), UpdateMemoryStream(), and UpdatePlaybackStats().
m_cheevos
CCheevos* const KODI::RETRO::CReversiblePlayback::m_cheevos private
Referenced by CommitSavestate(), and LoadSavestate().
m_futureFrameCount
uint64_t KODI::RETRO::CReversiblePlayback::m_futureFrameCount = 0 private
Referenced by SeekTimeMs(), UpdateMemoryStream(), and UpdatePlaybackStats().
m_gameClient
GAME::CGameClient* const KODI::RETRO::CReversiblePlayback::m_gameClient private
Referenced by AddFrame(), AdvanceFrames(), CommitSavestate(), CreateSavestate(), FrameEvent(), LoadSavestate(), RewindEvent(), RewindFrames(), and UpdateMemoryStream().
m_gameLoop
CGameLoop KODI::RETRO::CReversiblePlayback::m_gameLoop private
Referenced by Deinitialize(), GetSpeed(), Initialize(), PauseAsync(), SeekTimeMs(), SetSpeed(), UpdateMemoryStream(), and UpdatePlaybackStats().
m_guiMessenger
CGUIGameMessenger& KODI::RETRO::CReversiblePlayback::m_guiMessenger private
Referenced by CommitSavestate().
m_memoryStream
std::unique_ptr<IMemoryStream> KODI::RETRO::CReversiblePlayback::m_memoryStream private
Referenced by AddFrame(), AdvanceFrames(), CommitSavestate(), LoadSavestate(), RewindFrames(), UpdateMemoryStream(), and UpdatePlaybackStats().
m_mutex
CCriticalSection KODI::RETRO::CReversiblePlayback::m_mutex private
Referenced by AddFrame(), AdvanceFrames(), CommitSavestate(), LoadSavestate(), RewindFrames(), and UpdateMemoryStream().
m_pastFrameCount
uint64_t KODI::RETRO::CReversiblePlayback::m_pastFrameCount = 0 private
Referenced by SeekTimeMs(), UpdateMemoryStream(), and UpdatePlaybackStats().
m_playTimeMs
unsigned int KODI::RETRO::CReversiblePlayback::m_playTimeMs = 0 private
Referenced by GetTimeMs(), UpdateMemoryStream(), and UpdatePlaybackStats().
m_renderManager
CRPRenderManager& KODI::RETRO::CReversiblePlayback::m_renderManager private
Referenced by CommitSavestate(), and CreateSavestate().
m_savestateDatabase
std::unique_ptr<CSavestateDatabase> KODI::RETRO::CReversiblePlayback::m_savestateDatabase private
Referenced by CommitSavestate(), and LoadSavestate().
m_savestateMutex
CCriticalSection KODI::RETRO::CReversiblePlayback::m_savestateMutex private
Referenced by CommitSavestate(), and CreateSavestate().
m_savestateThreads
std::vector<std::future<void> > KODI::RETRO::CReversiblePlayback::m_savestateThreads private
Referenced by CreateSavestate(), and Deinitialize().
m_totalFrameCount
uint64_t KODI::RETRO::CReversiblePlayback::m_totalFrameCount = 0 private
Referenced by AddFrame(), AdvanceFrames(), CreateSavestate(), LoadSavestate(), and RewindFrames().
m_totalTimeMs
unsigned int KODI::RETRO::CReversiblePlayback::m_totalTimeMs = 0 private
Referenced by GetTotalTimeMs(), UpdateMemoryStream(), and UpdatePlaybackStats().
The documentation for this class was generated from the following files:
ReversiblePlayback.h
ReversiblePlayback.cpp