Kodi Documentation: CCPUInfoAndroid Class Reference
CCPUInfoAndroid Class Reference
#include <CPUInfoAndroid.h>
Public Member Functions
CCPUInfoAndroid ()
~CCPUInfoAndroid ()=default
bool SupportsCPUUsage () const override
int GetUsedPercentage () override
float GetCPUFrequency () override
Public Member Functions inherited from CCPUInfoPosix
virtual bool GetTemperature (CTemperature &temperature) override
Public Member Functions inherited from CCPUInfo
bool HasCoreId (int coreId) const
const CoreInfo GetCoreInfo (int coreId)
std::string GetCoresUsageString ()
unsigned int GetCPUFeatures () const
int GetCPUCount () const
const std::string & GetCPUModel () const
const std::string & GetCPUBogoMips () const
const std::string & GetCPUSoC () const
const std::string & GetCPUHardware () const
const std::string & GetCPURevision () const
const std::string & GetCPUSerial () const
Private Member Functions
int GetCPUCount ()
bool HasNeon ()
Private Attributes
std::unique_ptr< CPosixFile > m_posixFile
Additional Inherited Members
Static Public Member Functions inherited from CCPUInfo
static std::shared_ptr< CCPUInfo > GetCPUInfo ()
Public Attributes inherited from CCPUInfo
const unsigned int CPUID_INFOTYPE_MANUFACTURER = 0x00000000
const unsigned int CPUID_INFOTYPE_STANDARD = 0x00000001
const unsigned int CPUID_INFOTYPE_EXTENDED_IMPLEMENTED = 0x80000000
const unsigned int CPUID_INFOTYPE_EXTENDED = 0x80000001
const unsigned int CPUID_INFOTYPE_PROCESSOR_1 = 0x80000002
const unsigned int CPUID_INFOTYPE_PROCESSOR_2 = 0x80000003
const unsigned int CPUID_INFOTYPE_PROCESSOR_3 = 0x80000004
const unsigned int CPUID_00000001_ECX_SSE3 = (1 << 0)
const unsigned int CPUID_00000001_ECX_SSSE3 = (1 << 9)
const unsigned int CPUID_00000001_ECX_SSE4 = (1 << 19)
const unsigned int CPUID_00000001_ECX_SSE42 = (1 << 20)
const unsigned int CPUID_00000001_EDX_MMX = (1 << 23)
const unsigned int CPUID_00000001_EDX_SSE = (1 << 25)
const unsigned int CPUID_00000001_EDX_SSE2 = (1 << 26)
const unsigned int CPUID_80000001_EDX_MMX2 = (1 << 22)
const unsigned int CPUID_80000001_EDX_MMX = (1 << 23)
const unsigned int CPUID_80000001_EDX_3DNOWEXT = (1 << 30)
const unsigned int CPUID_80000001_EDX_3DNOW = (1U << 31)
const std::chrono::milliseconds MINIMUM_TIME_BETWEEN_READS {500}
Protected Member Functions inherited from CCPUInfoPosix
CCPUInfoPosix ()=default
virtual ~CCPUInfoPosix ()=default
bool CheckUserTemperatureCommand (CTemperature &temperature)
Protected Member Functions inherited from CCPUInfo
CCPUInfo ()=default
virtual ~CCPUInfo ()=default
Protected Attributes inherited from CCPUInfo
int m_lastUsedPercentage
XbmcThreads::EndTime m_nextUsedReadTime
std::string m_cpuVendor
std::string m_cpuModel
std::string m_cpuBogoMips
std::string m_cpuSoC
std::string m_cpuHardware
std::string m_cpuRevision
std::string m_cpuSerial
double m_usagePercent {0.0}
std::size_t m_activeTime {0}
std::size_t m_idleTime {0}
std::size_t m_totalTime {0}
int m_cpuCount
unsigned int m_cpuFeatures {0}
std::vector< CoreInfo > m_cores
Constructor & Destructor Documentation
CCPUInfoAndroid()
CCPUInfoAndroid::CCPUInfoAndroid ()
References CPU_FEATURE_NEON, GetCPUCount(), HasNeon(), CCPUInfo::m_cores, CCPUInfo::m_cpuBogoMips, CCPUInfo::m_cpuCount, CCPUInfo::m_cpuFeatures, CCPUInfo::m_cpuHardware, CCPUInfo::m_cpuModel, CCPUInfo::m_cpuRevision, CCPUInfo::m_cpuSerial, CCPUInfo::m_cpuVendor, CoreInfo::m_id, and m_posixFile.
~CCPUInfoAndroid()
CCPUInfoAndroid::~CCPUInfoAndroid () default
Member Function Documentation
GetCPUCount()
int CCPUInfoAndroid::GetCPUCount () private
Referenced by CCPUInfoAndroid().
GetCPUFrequency()
float CCPUInfoAndroid::GetCPUFrequency () override virtual
Implements CCPUInfo.
References m_posixFile.
GetUsedPercentage()
int CCPUInfoAndroid::GetUsedPercentage () inline override virtual
Implements CCPUInfo.
HasNeon()
bool CCPUInfoAndroid::HasNeon () private
Referenced by CCPUInfoAndroid().
SupportsCPUUsage()
bool CCPUInfoAndroid::SupportsCPUUsage () const inline override virtual
Reimplemented from CCPUInfo.
Member Data Documentation
m_posixFile
std::unique_ptr<CPosixFile> CCPUInfoAndroid::m_posixFile private
Referenced by CCPUInfoAndroid(), and GetCPUFrequency().
The documentation for this class was generated from the following files:
CPUInfoAndroid.h
CPUInfoAndroid.cpp