Kodi Documentation: KODI::WINDOWING::WAYLAND::CWinSystemWayland Class Reference
KODI::WINDOWING::WAYLAND::CWinSystemWayland Class Reference abstract
#include <WinSystemWayland.h>
Classes
struct Sizes
struct SizeUpdateInformation
struct SurfaceSubmission
Public Types
using PresentationFeedbackHandler = std::function< void(timespec, std::uint32_t, std::uint32_t, float, std::uint64_t)>
Public Member Functions
CWinSystemWayland ()
~CWinSystemWayland () noexcept override
const std::string GetName () override
bool InitWindowSystem () override
bool DestroyWindowSystem () override
bool CreateNewWindow (const std::string &name, bool fullScreen, RESOLUTION_INFO &res) override
bool DestroyWindow () override
bool ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override
bool SetFullScreen (bool fullScreen, RESOLUTION_INFO &res, bool blankOtherDisplays) override
void FinishModeChange (RESOLUTION res) override
void FinishWindowResize (int newWidth, int newHeight) override
bool UseLimitedColor () override
void UpdateResolutions () override
bool CanDoWindowed () override
bool Minimize () override
bool HasCursor () override
void ShowOSMouse (bool show) override
std::string GetClipboardText () override
float GetSyncOutputRefreshRate ()
float GetDisplayLatency () override
Get average display latency.
float GetFrameLatencyAdjustment () override
Get time that should be subtracted from the display latency for this frame in milliseconds.
std::unique_ptr< CVideoSync > GetVideoSync (CVideoReferenceClock *clock) override
void Register (IDispResource *resource) override
void Unregister (IDispResource *resource) override
CSignalRegistration RegisterOnPresentationFeedback (const PresentationFeedbackHandler &handler)
std::vector< std::string > GetConnectedOutputs () override
bool MessagePump () override
Public Member Functions inherited from CWinSystemBase
CWinSystemBase ()
virtual ~CWinSystemBase ()
virtual CRenderSystemBase * GetRenderSystem ()
virtual bool DisplayHardwareScalingEnabled ()
virtual void UpdateDisplayHardwareScaling (const RESOLUTION_INFO &resInfo)
virtual bool MoveWindow (int topLeft, int topRight)
virtual bool CenterWindow ()
virtual bool IsCreated ()
virtual void NotifyAppFocusChange (bool bGaining)
virtual void NotifyAppActiveChange (bool bActivated)
virtual bool HasInertialGestures ()
virtual int NoOfBuffers ()
virtual void ForceFullScreen (const RESOLUTION_INFO &resInfo)
Forces the window to fullscreen provided the window resolution.
virtual bool Restore ()
virtual bool Hide ()
virtual bool Show (bool raise=true)
virtual void OnMove (int x, int y)
virtual unsigned int GetScreenId (const std::string &screen)
Get the screen ID provided the screen name.
virtual void MoveToScreen (unsigned int screenIdx)
Window was requested to move to the given screen.
virtual void OnChangeScreen (unsigned int screenIdx)
Used to signal the windowing system about the change of the current screen.
KODI::WINDOWING::COSScreenSaverManager * GetOSScreenSaver ()
Get OS screen saver inhibit implementation if available.
unsigned int GetWidth ()
unsigned int GetHeight ()
bool IsFullScreen ()
virtual bool SupportsScreenMove ()
Check if the windowing system supports moving windows across screens.
void SetWindowResolution (int width, int height)
std::vector< RESOLUTION_WHR > ScreenResolutions (float refreshrate)
std::vector< REFRESHRATE > RefreshRates (int width, int height, uint32_t dwFlags)
REFRESHRATE DefaultRefreshRate (const std::vector< REFRESHRATE > &rates)
virtual bool HasCalibration (const RESOLUTION_INFO &resInfo)
void RegisterRenderLoop (IRenderLoop *client)
void UnregisterRenderLoop (IRenderLoop *client)
void DriveRenderLoop ()
virtual CGraphicContext & GetGfxContext () const
virtual void * GetHWContext ()
Get OS specific hardware context.
std::shared_ptr< CDPMSSupport > GetDPMSManager ()
virtual bool SetHDR (const VideoPicture *videoPicture)
Set the HDR metadata. Passing nullptr as the parameter should disable HDR.
virtual bool IsHDRDisplay ()
virtual HDR_STATUS ToggleHDR ()
virtual HDR_STATUS GetOSHDRStatus ()
virtual CHDRCapabilities GetDisplayHDRCapabilities () const
virtual float GetGuiSdrPeakLuminance () const
virtual bool HasSystemSdrPeakLuminance ()
virtual bool SupportsVideoSuperResolution ()
System supports Video Super Resolution HW upscaler i.e.: "NVIDIA RTX Video Super Resolution" or "Intel Video Super Resolution".
virtual DEBUG_INFO_RENDER GetDebugInfo ()
Gets debug info from video renderer for use in "Debug Info OSD" (Alt + O)
bool IsHDRDisplaySettingEnabled ()
Return true when HDR display is available and enabled in settings.
bool IsVideoSuperResolutionSettingEnabled ()
Return true when "Video Super Resolution" is supported and enabled in settings.
bool IsHighPrecisionProcessingSettingEnabled ()
Return true when setting "High Precision Processing" is enabled.
std::pair< bool, int > GetDitherSettings ()
Get dither settings.
virtual bool BindTextureUploadContext ()
Binds a shared context to the current thread, in order to upload textures asynchronously.
virtual bool UnbindTextureUploadContext ()
Unbinds the shared context.
virtual bool HasContext ()
Checks if a graphics context is already bound to the current thread.
Public Member Functions inherited from KODI::WINDOWING::WAYLAND::IInputHandler
virtual ~IInputHandler ()=default
Public Member Functions inherited from KODI::WINDOWING::WAYLAND::IWindowDecorationHandler
virtual ~IWindowDecorationHandler ()=default
Public Member Functions inherited from KODI::WINDOWING::WAYLAND::IShellSurfaceHandler
virtual ~IShellSurfaceHandler ()=default
Protected Member Functions
std::unique_ptr< KODI::WINDOWING::IOSScreenSaver > GetOSScreenSaverImpl () override
CSizeInt GetBufferSize () const
std::unique_ptr< CConnection > const & GetConnection ()
wayland::surface_t GetMainSurface ()
IShellSurface * GetShellSurface ()
void PrepareFramePresentation ()
void FinishFramePresentation ()
virtual void SetContextSize (CSizeInt size)=0
virtual IShellSurface * CreateShellSurface (const std::string &name)
void OnConfigure (std::uint32_t serial, CSizeInt size, IShellSurface::StateBitset state) override
void OnClose () override
virtual std::unique_ptr< CSeat > CreateSeat (std::uint32_t name, wayland::seat_t &seat)
Protected Member Functions inherited from CWinSystemBase
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, float refreshRate, uint32_t dwFlags)
void UpdateDesktopResolution (RESOLUTION_INFO &newRes, const std::string &output, int width, int height, int screenWidth, int screenHeight, float refreshRate, uint32_t dwFlags)
Private Member Functions
void OnEnter (InputType type) override
void OnLeave (InputType type) override
void OnEvent (InputType type, XBMC_Event &event) override
void OnSetCursor (std::uint32_t seatGlobalName, std::uint32_t serial) override
void OnWindowMove (const wayland::seat_t &seat, std::uint32_t serial) override
void OnWindowResize (const wayland::seat_t &seat, std::uint32_t serial, wayland::shell_surface_resize edge) override
void OnWindowShowContextMenu (const wayland::seat_t &seat, std::uint32_t serial, CPointInt position) override
void OnWindowClose () override
void OnWindowMaximize () override
void OnWindowMinimize () override
void OnSeatAdded (std::uint32_t name, wayland::proxy_t &&seat)
void OnSeatRemoved (std::uint32_t name)
void OnOutputAdded (std::uint32_t name, wayland::proxy_t &&output)
void OnOutputRemoved (std::uint32_t name)
void LoadDefaultCursor ()
void SendFocusChange (bool focus)
bool SetResolutionExternal (bool fullScreen, RESOLUTION_INFO const &res)
void SetResolutionInternal (CSizeInt size, int scale, IShellSurface::StateBitset state, bool sizeIncludesDecoration, bool mustAck=false, std::uint32_t configureSerial=0u)
Sizes CalculateSizes (CSizeInt size, int scale, IShellSurface::StateBitset state, bool sizeIncludesDecoration)
SizeUpdateInformation UpdateSizeVariables (CSizeInt size, int scale, IShellSurface::StateBitset state, bool sizeIncludesDecoration)
void ApplySizeUpdate (SizeUpdateInformation update)
void ApplyNextState ()
std::string UserFriendlyOutputName (std::shared_ptr< COutput > const &output)
std::shared_ptr< COutput > FindOutputByUserFriendlyName (std::string const &name)
std::shared_ptr< COutput > FindOutputByWaylandOutput (wayland::output_t const &output)
void OnOutputDone (std::uint32_t name)
void UpdateBufferScale ()
void ApplyBufferScale ()
void ApplyOpaqueRegion ()
void ApplyWindowGeometry ()
void UpdateTouchDpi ()
void ApplyShellSurfaceState (IShellSurface::StateBitset state)
void ProcessMessages ()
void AckConfigure (std::uint32_t serial)
timespec GetPresentationClockTime ()
Private Attributes
std::unique_ptr< CConnection > m_connection
std::unique_ptr< CRegistry > m_registry
std::unique_ptr< CRegistry > m_seatRegistry
wayland::compositor_t m_compositor
wayland::shm_t m_shm
wayland::presentation_t m_presentation
std::unique_ptr< IShellSurface > m_shellSurface
wayland::callback_t m_frameCallback
CEvent m_frameCallbackEvent
std::map< std::uint32_t, std::unique_ptr< CSeat > > m_seats
CCriticalSection m_seatsMutex
std::unique_ptr< CSeatInputProcessing > m_seatInputProcessing
std::map< std::uint32_t, std::shared_ptr< COutput > > m_outputs
std::map< std::uint32_t, std::shared_ptr< COutput > > m_outputsInPreparation
outputs that did not receive their done event yet
CCriticalSection m_outputsMutex
std::unique_ptr< CWindowDecorator > m_windowDecorator
bool m_osCursorVisible {true}
wayland::cursor_theme_t m_cursorTheme
wayland::buffer_t m_cursorBuffer
wayland::cursor_image_t m_cursorImage
wayland::surface_t m_cursorSurface
clockid_t m_presentationClock
std::list< SurfaceSubmission > m_surfaceSubmissions
CCriticalSection m_surfaceSubmissionsMutex
std::uint32_t m_syncOutputID
Protocol object ID of the sync output returned by wp_presentation.
std::atomic< float > m_syncOutputRefreshRate {0.0f}
Refresh rate of sync output returned by wp_presentation.
std::atomic< float > m_latencyMovingAverage
CSignalHandlerList< PresentationFeedbackHandler > m_presentationFeedbackHandlers
std::chrono::steady_clock::time_point m_frameStartTime {}
std::set< IDispResource * > m_dispResources
CCriticalSection m_dispResourcesMutex
wayland::surface_t m_surface
wayland::output_t m_lastSetOutput
std::set< std::shared_ptr< COutput > > m_surfaceOutputs
CCriticalSection m_surfaceOutputsMutex
CSizeInt m_surfaceSize
CSizeInt m_bufferSize
Size of the buffer that should back the surface (i.e. with scaling applied)
CSizeInt m_configuredSize
Size of the whole window including window decorations as given by configure.
int m_scale {1}
Scale in use for main surface buffer.
IShellSurface::StateBitset m_shellSurfaceState
Shell surface state last acked.
bool m_shellSurfaceInitializing {false}
Whether the shell surface is waiting for initial configure.
struct {
bool mustBeAcked {false}
std::uint32_t configureSerial {}
CSizeInt configuredSize
int scale {1}
IShellSurface::StateBitset shellSurfaceState
} m_next
bool m_waitingForApply {false}
Actor::Protocol m_protocol
Protocol for communicating events to the main thread.
bool m_firstSerialAcked {false}
std::uint32_t m_lastAckedSerial {0u}
bool m_isInitialSetFullScreen {true}
Whether this is the first call to SetFullScreen.
Static Private Attributes
static constexpr int LATENCY_MOVING_AVERAGE_SIZE {30}
Additional Inherited Members
Static Public Member Functions inherited from CWinSystemBase
static std::unique_ptr< CWinSystemBase > CreateWinSystem ()
Static Public Attributes inherited from CWinSystemBase
static const char * SETTING_WINSYSTEM_IS_HDR_DISPLAY = "winsystem.ishdrdisplay"
Protected Attributes inherited from CWinSystemBase
int m_nWidth = 0
int m_nHeight = 0
int m_nTop = 0
int m_nLeft = 0
bool m_bWindowCreated = false
bool m_bFullScreen = false
bool m_bBlankOtherDisplay = false
float m_fRefreshRate = 0.0f
std::unique_ptr< KODI::WINDOWING::COSScreenSaverManager > m_screenSaverManager
CCriticalSection m_renderLoopSection
std::vector< IRenderLoop * > m_renderLoopClients
std::unique_ptr< IWinEvents > m_winEvents
std::unique_ptr< CGraphicContext > m_gfxContext
std::shared_ptr< CDPMSSupport > m_dpms
Member Typedef Documentation
PresentationFeedbackHandler
using KODI::WINDOWING::WAYLAND::CWinSystemWayland::PresentationFeedbackHandler = std::function<void(timespec , std::uint32_t , std::uint32_t , float , std::uint64_t)>
Constructor & Destructor Documentation
CWinSystemWayland()
CWinSystemWayland::CWinSystemWayland ()
References CWinSystemBase::m_winEvents.
~CWinSystemWayland()
CWinSystemWayland::~CWinSystemWayland () override noexcept
References DestroyWindowSystem().
Member Function Documentation
AckConfigure()
void CWinSystemWayland::AckConfigure (std::uint32_t serial) private
References LOGDEBUG, m_firstSerialAcked, m_lastAckedSerial, and m_shellSurface.
Referenced by ApplyNextState(), and OnConfigure().
ApplyBufferScale()
void CWinSystemWayland::ApplyBufferScale () private
References LOGINFO, m_configuredSize, m_scale, m_seatInputProcessing, m_shellSurfaceState, m_surface, and m_windowDecorator.
Referenced by ApplySizeUpdate(), and CreateNewWindow().
ApplyNextState()
void CWinSystemWayland::ApplyNextState () private
References AckConfigure(), ApplyShellSurfaceState(), ApplySizeUpdate(), LOGDEBUG, m_next, KODI::WINDOWING::WAYLAND::IShellSurface::StateToString(), and UpdateSizeVariables().
Referenced by FinishModeChange(), FinishWindowResize(), and SetResolutionInternal().
ApplyOpaqueRegion()
void CWinSystemWayland::ApplyOpaqueRegion () private
References CSizeGen< T >::Height(), LOGDEBUG, m_compositor, m_surface, m_surfaceSize, and CSizeGen< T >::Width().
Referenced by ApplySizeUpdate(), and CreateNewWindow().
ApplyShellSurfaceState()
void CWinSystemWayland::ApplyShellSurfaceState (IShellSurface::StateBitset state) private
References m_configuredSize, m_scale, m_shellSurfaceState, and m_windowDecorator.
Referenced by ApplyNextState().
ApplySizeUpdate()
void CWinSystemWayland::ApplySizeUpdate (SizeUpdateInformation update) private
References ApplyBufferScale(), ApplyOpaqueRegion(), ApplyWindowGeometry(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::SizeUpdateInformation::bufferScaleChanged, KODI::WINDOWING::WAYLAND::CWinSystemWayland::SizeUpdateInformation::configuredSizeChanged, m_bufferSize, m_configuredSize, m_scale, m_shellSurfaceState, m_windowDecorator, SetContextSize(), and KODI::WINDOWING::WAYLAND::CWinSystemWayland::SizeUpdateInformation::surfaceSizeChanged.
Referenced by ApplyNextState(), and SetResolutionExternal().
ApplyWindowGeometry()
void CWinSystemWayland::ApplyWindowGeometry () private
References m_shellSurface, and m_windowDecorator.
Referenced by ApplySizeUpdate(), and CreateNewWindow().
CalculateSizes()
CWinSystemWayland::Sizes CWinSystemWayland::CalculateSizes (CSizeInt size, int scale, IShellSurface::StateBitset state, bool sizeIncludesDecoration) private
References KODI::WINDOWING::WAYLAND::CWinSystemWayland::Sizes::bufferSize, KODI::WINDOWING::WAYLAND::CWinSystemWayland::Sizes::configuredSize, LOGWARNING, m_windowDecorator, scale, and KODI::WINDOWING::WAYLAND::CWinSystemWayland::Sizes::surfaceSize.
Referenced by SetResolutionInternal(), and UpdateSizeVariables().
CanDoWindowed()
bool CWinSystemWayland::CanDoWindowed () override virtual
Reimplemented from CWinSystemBase.
CreateNewWindow()
bool CWinSystemWayland::CreateNewWindow (const std::string & name, bool fullScreen, RESOLUTION_INFO & res) override virtual
Implements CWinSystemBase.
Reimplemented in KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext, and KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS.
References _1, _2, ApplyBufferScale(), ApplyOpaqueRegion(), ApplyWindowGeometry(), RESOLUTION_INFO::bFullScreen, CreateShellSurface(), FindOutputByUserFriendlyName(), FindOutputByWaylandOutput(), RESOLUTION_INFO::fRefreshRate, CServiceBroker::GetSettingsComponent(), CSizeGen< T >::Height(), RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, CLog::Log(), LOGDEBUG, LOGINFO, LOGWARNING, m_bufferSize, m_compositor, m_configuredSize, m_connection, m_lastSetOutput, m_scale, m_seatInputProcessing, m_seatRegistry, m_seats, m_shellSurface, m_shellSurfaceInitializing, m_shellSurfaceState, m_surface, m_surfaceOutputs, m_surfaceOutputsMutex, m_windowDecorator, name, OnSeatAdded(), OnSeatRemoved(), KODI::WINDOWING::WAYLAND::CWinEventsWayland::SetDisplay(), CSettings::SETTING_VIDEOSCREEN_MONITOR, KODI::WINDOWING::WAYLAND::IShellSurface::STATE_ACTIVATED, KODI::WINDOWING::WAYLAND::IShellSurface::STATE_FULLSCREEN, RESOLUTION_INFO::strOutput, UpdateBufferScale(), CWinSystemBase::UpdateDesktopResolution(), UpdateSizeVariables(), UpdateTouchDpi(), UserFriendlyOutputName(), and CSizeGen< T >::Width().
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::CreateNewWindow(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::CreateNewWindow().
CreateSeat()
std::unique_ptr< CSeat > CWinSystemWayland::CreateSeat (std::uint32_t name, wayland::seat_t & seat) protected virtual
Reimplemented in KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS.
References m_connection, and name.
Referenced by OnSeatAdded().
CreateShellSurface()
IShellSurface * CWinSystemWayland::CreateShellSurface (const std::string & name) protected virtual
Reimplemented in KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS.
References CCompileInfo::GetAppName(), LOGWARNING, m_connection, m_surface, name, KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShell::TryCreate(), and KODI::WINDOWING::WAYLAND::CShellSurfaceXdgShellUnstableV6::TryCreate().
Referenced by CreateNewWindow().
DestroyWindow()
bool CWinSystemWayland::DestroyWindow () override virtual
Reimplemented from CWinSystemBase.
Reimplemented in KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext.
References m_lastSetOutput, m_seatRegistry, m_seats, m_shellSurface, m_surface, m_surfaceOutputs, m_surfaceSubmissions, m_windowDecorator, and KODI::WINDOWING::WAYLAND::CWinEventsWayland::SetDisplay().
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::DestroyWindow(), and DestroyWindowSystem().
DestroyWindowSystem()
bool CWinSystemWayland::DestroyWindowSystem () override virtual
Reimplemented from CWinSystemBase.
Reimplemented in KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext.
References DestroyWindow(), CWinSystemBase::DestroyWindowSystem(), CGenericTouchInputHandler::GetInstance(), m_connection, m_cursorBuffer, m_cursorImage, m_cursorSurface, m_cursorTheme, m_frameCallback, m_outputs, m_outputsInPreparation, m_registry, CWinSystemBase::m_screenSaverManager, m_seatInputProcessing, and ITouchInputHandling::UnregisterHandler().
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::DestroyWindowSystem(), and ~CWinSystemWayland().
FindOutputByUserFriendlyName()
std::shared_ptr< COutput > CWinSystemWayland::FindOutputByUserFriendlyName (std::string const & name) private
References m_outputs, m_outputsMutex, and name.
Referenced by CreateNewWindow(), ProcessMessages(), SetResolutionExternal(), and UpdateResolutions().
FindOutputByWaylandOutput()
std::shared_ptr< COutput > CWinSystemWayland::FindOutputByWaylandOutput (wayland::output_t const & output) private
References m_outputs, and m_outputsMutex.
Referenced by CreateNewWindow(), PrepareFramePresentation(), and UpdateResolutions().
FinishFramePresentation()
void CWinSystemWayland::FinishFramePresentation () protected
References m_frameStartTime, and ProcessMessages().
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::PresentFrame().
FinishModeChange()
void CWinSystemWayland::FinishModeChange (RESOLUTION res) override virtual
Reimplemented from CWinSystemBase.
References ApplyNextState(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), CWinSystemBase::m_bFullScreen, CWinSystemBase::m_fRefreshRate, and m_waitingForApply.
FinishWindowResize()
void CWinSystemWayland::FinishWindowResize (int newWidth, int newHeight) override virtual
Reimplemented from CWinSystemBase.
References ApplyNextState(), and m_waitingForApply.
GetBufferSize()
CSizeInt KODI::WINDOWING::WAYLAND::CWinSystemWayland::GetBufferSize () const inline protected
References m_bufferSize.
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::CreateNewWindow().
GetClipboardText()
std::string CWinSystemWayland::GetClipboardText (void) override virtual
Reimplemented from CWinSystemBase.
References m_seats, m_seatsMutex, and text.
GetConnectedOutputs()
std::vector< std::string > CWinSystemWayland::GetConnectedOutputs () override virtual
Reimplemented from CWinSystemBase.
References m_outputs, and m_outputsMutex.
GetConnection()
std::unique_ptr< CConnection > const & KODI::WINDOWING::WAYLAND::CWinSystemWayland::GetConnection () inline protected
References m_connection.
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::CreateSeat(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::CreateShellSurface(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::InitWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES::InitWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::InitWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::InitWindowSystemEGL(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::PresentFrame().
GetDisplayLatency()
float CWinSystemWayland::GetDisplayLatency () override virtual
Get average display latency.
The latency should be measured as the time between finishing the rendering of a frame, i.e. calling PresentRender, and the rendered content becoming visible on the screen.
Returns
average display latency in seconds, or negative value if unknown
Reimplemented from CWinSystemBase.
References CWinSystemBase::GetDisplayLatency(), m_latencyMovingAverage, and m_presentation.
GetFrameLatencyAdjustment()
float CWinSystemWayland::GetFrameLatencyAdjustment () override virtual
Get time that should be subtracted from the display latency for this frame in milliseconds.
Contrary to GetDisplayLatency, this value is calculated ad-hoc for the frame currently being rendered and not a value that is calculated/ averaged from past frames and their presentation times
Reimplemented from CWinSystemBase.
References m_frameStartTime.
GetMainSurface()
wayland::surface_t KODI::WINDOWING::WAYLAND::CWinSystemWayland::GetMainSurface () inline protected
References m_surface.
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::CreateNewWindow(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::CreateNewWindow(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::CreateShellSurface(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::PresentFrame().
GetName()
const std::string KODI::WINDOWING::WAYLAND::CWinSystemWayland::GetName () inline override virtual
Reimplemented from CWinSystemBase.
GetOSScreenSaverImpl()
std::unique_ptr< IOSScreenSaver > CWinSystemWayland::GetOSScreenSaverImpl () override protected virtual
Reimplemented from CWinSystemBase.
Reimplemented in KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS.
References KODI::WINDOWING::LINUX::COSScreenSaverFreedesktop::IsAvailable(), LOGINFO, m_connection, m_surface, and KODI::WINDOWING::WAYLAND::COSScreenSaverIdleInhibitUnstableV1::TryCreate().
GetPresentationClockTime()
timespec CWinSystemWayland::GetPresentationClockTime () private
References m_presentationClock.
Referenced by PrepareFramePresentation().
GetShellSurface()
IShellSurface * KODI::WINDOWING::WAYLAND::CWinSystemWayland::GetShellSurface () inline protected
References m_shellSurface.
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::OnAppLifecycleEvent().
GetSyncOutputRefreshRate()
float CWinSystemWayland::GetSyncOutputRefreshRate ()
References m_syncOutputRefreshRate.
Referenced by KODI::WINDOWING::WAYLAND::CVideoSyncWpPresentation::Setup().
GetVideoSync()
std::unique_ptr< CVideoSync > CWinSystemWayland::GetVideoSync (CVideoReferenceClock * clock) override virtual
Reimplemented from CWinSystemBase.
References LOGINFO, m_presentation, and m_surface.
HasCursor()
bool CWinSystemWayland::HasCursor () override virtual
Reimplemented from CWinSystemBase.
Reimplemented in KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS.
References m_seats, and m_seatsMutex.
InitWindowSystem()
bool CWinSystemWayland::InitWindowSystem () override virtual
Reimplemented from CWinSystemBase.
Reimplemented in KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL, KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES, and KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS.
References _1, _2, CServiceBroker::GetInputManager(), CGenericTouchActionHandler::GetInstance(), CGenericTouchInputHandler::GetInstance(), CServiceBroker::GetSettingsComponent(), CWinSystemBase::InitWindowSystem(), CLog::Log(), LOGDEBUG, LOGINFO, LOGWARNING, m_compositor, m_connection, m_outputs, m_presentation, m_presentationClock, m_registry, m_shm, OnOutputAdded(), OnOutputRemoved(), KODI::RETRO::CRPProcessInfoWayland::Register(), VIDEOPLAYER::CProcessInfoWayland::Register(), ITouchInputHandling::RegisterHandler(), CInputManager::SetMouseActive(), and CSettings::SETTING_VIDEOSCREEN_LIMITEDRANGE.
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::InitWindowSystem(), and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::InitWindowSystemEGL().
LoadDefaultCursor()
void CWinSystemWayland::LoadDefaultCursor () private
References KODI::WINDOWING::WAYLAND::CCursorUtil::LoadFromTheme(), CLog::Log(), LOGWARNING, m_compositor, m_cursorBuffer, m_cursorImage, m_cursorSurface, m_cursorTheme, and m_shm.
Referenced by OnSetCursor().
MessagePump()
bool CWinSystemWayland::MessagePump () override virtual
Reimplemented from CWinSystemBase.
References CWinSystemBase::m_winEvents.
Minimize()
bool CWinSystemWayland::Minimize () override virtual
Reimplemented from CWinSystemBase.
References m_shellSurface.
OnClose()
void CWinSystemWayland::OnClose () override protected virtual
Implements KODI::WINDOWING::WAYLAND::IShellSurfaceHandler.
References CServiceBroker::GetAppMessenger(), and TMSG_QUIT.
OnConfigure()
void CWinSystemWayland::OnConfigure (std::uint32_t serial, CSizeInt size, IShellSurface::StateBitset state) override protected virtual
Implements KODI::WINDOWING::WAYLAND::IShellSurfaceHandler.
Reimplemented in KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS.
References AckConfigure(), anonymous_namespace{WinSystemWayland.cpp}::WinSystemWaylandProtocol::CONFIGURE, LOGDEBUG, m_protocol, m_scale, m_shellSurfaceInitializing, m_shellSurfaceState, Actor::Protocol::SendOutMessage(), KODI::WINDOWING::WAYLAND::IShellSurface::StateToString(), and UpdateSizeVariables().
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::OnConfigure().
OnEnter()
void CWinSystemWayland::OnEnter (InputType type) override private virtual
Handle focus enter
Parameters
type input device type for which the surface has gained the focus
Reimplemented from KODI::WINDOWING::WAYLAND::IInputHandler.
References CServiceBroker::GetInputManager(), KODI::WINDOWING::WAYLAND::KEYBOARD, KODI::WINDOWING::WAYLAND::POINTER, SendFocusChange(), and CInputManager::SetMouseActive().
OnEvent()
void CWinSystemWayland::OnEvent (InputType type, XBMC_Event & event) override private virtual
Handle input event
Parameters
type input device type that caused the event
event XBMC event data
Reimplemented from KODI::WINDOWING::WAYLAND::IInputHandler.
References KODI::WINDOWING::WAYLAND::CWinEventsWayland::MessagePush().
OnLeave()
void CWinSystemWayland::OnLeave (InputType type) override private virtual
Handle focus leave
Parameters
type input device type for which the surface has lost the focus
Reimplemented from KODI::WINDOWING::WAYLAND::IInputHandler.
References CServiceBroker::GetInputManager(), KODI::WINDOWING::WAYLAND::KEYBOARD, KODI::WINDOWING::WAYLAND::POINTER, SendFocusChange(), and CInputManager::SetMouseActive().
OnOutputAdded()
void CWinSystemWayland::OnOutputAdded (std::uint32_t name, wayland::proxy_t && output) private
References m_outputsInPreparation, name, and OnOutputDone().
Referenced by InitWindowSystem().
OnOutputDone()
void CWinSystemWayland::OnOutputDone (std::uint32_t name) private
References m_outputs, m_outputsInPreparation, m_outputsMutex, m_protocol, name, anonymous_namespace{WinSystemWayland.cpp}::WinSystemWaylandProtocol::OUTPUT_HOTPLUG, Actor::Protocol::SendOutMessage(), and UpdateBufferScale().
Referenced by OnOutputAdded().
OnOutputRemoved()
void CWinSystemWayland::OnOutputRemoved (std::uint32_t name) private
References m_outputs, m_outputsInPreparation, m_outputsMutex, and name.
Referenced by InitWindowSystem().
OnSeatAdded()
void CWinSystemWayland::OnSeatAdded (std::uint32_t name, wayland::proxy_t && seat) private
References CreateSeat(), m_seatInputProcessing, m_seats, m_seatsMutex, m_windowDecorator, and name.
Referenced by CreateNewWindow().
OnSeatRemoved()
void CWinSystemWayland::OnSeatRemoved (std::uint32_t name) private
References m_seatInputProcessing, m_seats, m_seatsMutex, m_windowDecorator, and name.
Referenced by CreateNewWindow().
OnSetCursor()
void CWinSystemWayland::OnSetCursor (std::uint32_t seatGlobalName, std::uint32_t serial) override private virtual
Handle request for setting the cursor
When the client gains pointer focus for a surface, a cursor image must be attached to the pointer. Otherwise the previous pointer image would be used.
This request is sent in addition to OnEnter for InputType::POINTER.
Parameters
seatGlobalName numeric Wayland global name of the seat the event occurred on
pointer pointer instance that needs its cursor set
serial Wayland protocol message serial that must be sent back in set_cursor
Reimplemented from KODI::WINDOWING::WAYLAND::IInputHandler.
References LoadDefaultCursor(), m_cursorImage, m_cursorSurface, m_osCursorVisible, and m_seats.
OnWindowClose()
void CWinSystemWayland::OnWindowClose () override private virtual
Implements KODI::WINDOWING::WAYLAND::IWindowDecorationHandler.
References CServiceBroker::GetAppMessenger(), and TMSG_QUIT.
OnWindowMaximize()
void CWinSystemWayland::OnWindowMaximize () override private virtual
Implements KODI::WINDOWING::WAYLAND::IWindowDecorationHandler.
References m_shellSurface, m_shellSurfaceState, and KODI::WINDOWING::WAYLAND::IShellSurface::STATE_MAXIMIZED.
OnWindowMinimize()
void CWinSystemWayland::OnWindowMinimize () override private virtual
Implements KODI::WINDOWING::WAYLAND::IWindowDecorationHandler.
References m_shellSurface.
OnWindowMove()
void CWinSystemWayland::OnWindowMove (const wayland::seat_t & seat, std::uint32_t serial) override private virtual
Implements KODI::WINDOWING::WAYLAND::IWindowDecorationHandler.
References m_shellSurface.
OnWindowResize()
void CWinSystemWayland::OnWindowResize (const wayland::seat_t & seat, std::uint32_t serial, wayland::shell_surface_resize edge) override private virtual
Implements KODI::WINDOWING::WAYLAND::IWindowDecorationHandler.
References edge, and m_shellSurface.
OnWindowShowContextMenu()
void CWinSystemWayland::OnWindowShowContextMenu (const wayland::seat_t & seat, std::uint32_t serial, CPointInt position) override private virtual
Implements KODI::WINDOWING::WAYLAND::IWindowDecorationHandler.
References m_shellSurface.
PrepareFramePresentation()
void CWinSystemWayland::PrepareFramePresentation () protected
References FindOutputByWaylandOutput(), GetPresentationClockTime(), KODI::CSignalHandlerList< ManagedT >::Invoke(), LATENCY_MOVING_AVERAGE_SIZE, CLog::Log(), LOGAVTIMING, LOGDEBUG, LOGWARNING, m_frameCallback, m_frameCallbackEvent, m_latencyMovingAverage, m_presentation, m_presentationFeedbackHandlers, m_surface, m_surfaceSubmissions, m_surfaceSubmissionsMutex, m_syncOutputID, m_syncOutputRefreshRate, CEvent::Reset(), CEvent::Set(), KODI::LINUX::TimespecDifference(), and CEvent::Wait().
Referenced by KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::PresentFrame().
ProcessMessages()
void CWinSystemWayland::ProcessMessages () private
References anonymous_namespace{WinSystemWayland.cpp}::WinSystemWaylandProtocol::BUFFER_SCALE, anonymous_namespace{WinSystemWayland.cpp}::WinSystemWaylandProtocol::CONFIGURE, FindOutputByUserFriendlyName(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), LOGDEBUG, CWinSystemBase::m_bFullScreen, m_configuredSize, m_lastSetOutput, m_outputsMutex, m_protocol, m_scale, m_shellSurface, m_shellSurfaceState, m_surface, m_waitingForApply, anonymous_namespace{WinSystemWayland.cpp}::WinSystemWaylandProtocol::OUTPUT_HOTPLUG, Actor::Protocol::ReceiveOutMessage(), RES_DESKTOP, RES_WINDOW, SetResolutionInternal(), KODI::WINDOWING::WAYLAND::IShellSurface::STATE_FULLSCREEN, KODI::WINDOWING::WAYLAND::IShellSurface::StateToString(), and UpdateResolutions().
Referenced by FinishFramePresentation().
Register()
void CWinSystemWayland::Register (IDispResource * resource) override virtual
Implements CWinSystemBase.
References m_dispResources, and m_dispResourcesMutex.
RegisterOnPresentationFeedback()
KODI::CSignalRegistration CWinSystemWayland::RegisterOnPresentationFeedback (const PresentationFeedbackHandler & handler)
References m_presentationFeedbackHandlers, and KODI::CSignalHandlerList< ManagedT >::Register().
Referenced by KODI::WINDOWING::WAYLAND::CVideoSyncWpPresentation::Run().
ResizeWindow()
bool CWinSystemWayland::ResizeWindow (int newWidth, int newHeight, int newLeft, int newTop) override virtual
Implements CWinSystemBase.
References CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), RES_WINDOW, and SetResolutionExternal().
SendFocusChange()
void CWinSystemWayland::SendFocusChange (bool focus) private
References g_application, m_dispResources, and m_dispResourcesMutex.
Referenced by OnEnter(), and OnLeave().
SetContextSize()
virtual void KODI::WINDOWING::WAYLAND::CWinSystemWayland::SetContextSize (CSizeInt size) protected pure virtual
Implemented in KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext, KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL, and KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGLES.
Referenced by ApplySizeUpdate().
SetFullScreen()
bool CWinSystemWayland::SetFullScreen (bool fullScreen, RESOLUTION_INFO & res, bool blankOtherDisplays) override virtual
Implements CWinSystemBase.
References SetResolutionExternal().
SetResolutionExternal()
bool CWinSystemWayland::SetResolutionExternal (bool fullScreen, RESOLUTION_INFO const & res) private
Change resolution and window state on Kodi request
This function is used for updating resolution when Kodi initiates a resolution change, such as when changing between full screen and windowed mode or when selecting a different monitor or resolution in the settings.
Size updates originating from compositor events (such as configure or buffer scale changes) should not use this function, but SetResolutionInternal instead.
Parameters
fullScreen whether to go full screen or windowed
res resolution to set
Returns
whether the requested resolution was actually set - is false e.g. when already in full screen mode since the application cannot set the size then
References ApplySizeUpdate(), FindOutputByUserFriendlyName(), RESOLUTION_INFO::fRefreshRate, RESOLUTION_INFO::iHeight, RESOLUTION_INFO::iWidth, LOGDEBUG, LOGINFO, m_isInitialSetFullScreen, m_lastSetOutput, m_scale, m_shellSurface, m_shellSurfaceState, m_waitingForApply, KODI::WINDOWING::WAYLAND::IShellSurface::STATE_FULLSCREEN, KODI::WINDOWING::WAYLAND::IShellSurface::STATE_MAXIMIZED, RESOLUTION_INFO::strOutput, and UpdateSizeVariables().
Referenced by ResizeWindow(), and SetFullScreen().
SetResolutionInternal()
void CWinSystemWayland::SetResolutionInternal (CSizeInt size, int scale, IShellSurface::StateBitset state, bool sizeIncludesDecoration, bool mustAck = false, std::uint32_t configureSerial = 0u) private
Recalculate sizes from given parameters, apply them and update Kodi CDisplaySettings resolution if necessary
This function should be called when events internal to the windowing system such as a compositor configure lead to a size change.
Call only from main thread.
Parameters
size configured size, can be zero if compositor does not have a preference
scale new buffer scale
sizeIncludesDecoration whether size includes the size of the window decorations if present
References CDisplaySettings::AddResolutionInfo(), CDisplaySettings::ApplyCalibrations(), ApplyNextState(), CalculateSizes(), configureSerial, CDisplaySettings::GetInstance(), LOGDEBUG, CWinSystemBase::m_bFullScreen, m_bufferSize, CWinSystemBase::m_fRefreshRate, m_next, m_surfaceOutputs, m_surfaceOutputsMutex, m_waitingForApply, KODI::WINDOWING::WAYLAND::CWinEventsWayland::MessagePush(), RES_INVALID, RES_WINDOW, CDisplaySettings::ResolutionInfoSize(), scale, CWinSystemBase::SetWindowResolution(), KODI::WINDOWING::WAYLAND::IShellSurface::STATE_FULLSCREEN, KODI::WINDOWING::WAYLAND::IShellSurface::StateToString(), XBMC_Event::type, CWinSystemBase::UpdateDesktopResolution(), UserFriendlyOutputName(), XBMC_MODECHANGE, and XBMC_VIDEORESIZE.
Referenced by ProcessMessages().
ShowOSMouse()
void CWinSystemWayland::ShowOSMouse (bool show) override virtual
Reimplemented from CWinSystemBase.
References m_osCursorVisible.
Unregister()
void CWinSystemWayland::Unregister (IDispResource * resource) override virtual
Implements CWinSystemBase.
References m_dispResources, and m_dispResourcesMutex.
UpdateBufferScale()
void CWinSystemWayland::UpdateBufferScale () private
References anonymous_namespace{WinSystemWayland.cpp}::WinSystemWaylandProtocol::BUFFER_SCALE, m_protocol, m_surfaceOutputs, and Actor::Protocol::SendOutMessage().
Referenced by CreateNewWindow(), and OnOutputDone().
UpdateResolutions()
void CWinSystemWayland::UpdateResolutions () override virtual
Reimplemented from CWinSystemBase.
References CDisplaySettings::AddResolutionInfo(), CDisplaySettings::ApplyCalibrations(), CDisplaySettings::ClearCustomResolutions(), FindOutputByUserFriendlyName(), FindOutputByWaylandOutput(), CDisplaySettings::GetInstance(), CDisplaySettings::GetResolutionInfo(), CServiceBroker::GetSettingsComponent(), LOGINFO, m_lastSetOutput, m_outputs, m_outputsMutex, RES_DESKTOP, CSettings::SETTING_VIDEOSCREEN_MONITOR, CWinSystemBase::UpdateDesktopResolution(), CWinSystemBase::UpdateResolutions(), and UserFriendlyOutputName().
Referenced by ProcessMessages().
UpdateSizeVariables()
CWinSystemWayland::SizeUpdateInformation CWinSystemWayland::UpdateSizeVariables (CSizeInt size, int scale, IShellSurface::StateBitset state, bool sizeIncludesDecoration) private
Calculate internal resolution from surface size and set variables
Parameters
next surface size
scale new buffer scale
state window state to determine whether decorations are enabled at all
sizeIncludesDecoration if true, given size includes potential window decorations
Returns
whether main buffer (not surface) size changed
References CalculateSizes(), CSizeGen< T >::Height(), LOGDEBUG, LOGINFO, m_bufferSize, m_configuredSize, m_scale, m_surfaceSize, scale, KODI::WINDOWING::WAYLAND::IShellSurface::StateToString(), and CSizeGen< T >::Width().
Referenced by ApplyNextState(), CreateNewWindow(), OnConfigure(), and SetResolutionExternal().
UpdateTouchDpi()
void CWinSystemWayland::UpdateTouchDpi () private
References CGenericTouchInputHandler::GetInstance(), LOGDEBUG, m_surfaceOutputs, and ITouchInputHandler::SetScreenDPI().
Referenced by CreateNewWindow().
UseLimitedColor()
bool CWinSystemWayland::UseLimitedColor () override virtual
Reimplemented from CWinSystemBase.
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_VIDEOSCREEN_LIMITEDRANGE.
UserFriendlyOutputName()
std::string CWinSystemWayland::UserFriendlyOutputName (std::shared_ptr< COutput > const & output) private
References g_localizeStrings, and CLocalizeStrings::Get().
Referenced by CreateNewWindow(), SetResolutionInternal(), and UpdateResolutions().
Member Data Documentation
configuredSize
CSizeInt KODI::WINDOWING::WAYLAND::CWinSystemWayland::configuredSize
configureSerial
std::uint32_t KODI::WINDOWING::WAYLAND::CWinSystemWayland::configureSerial {}
Referenced by SetResolutionInternal().
LATENCY_MOVING_AVERAGE_SIZE
constexpr int KODI::WINDOWING::WAYLAND::CWinSystemWayland::LATENCY_MOVING_AVERAGE_SIZE {30} static constexpr private
Referenced by PrepareFramePresentation().
m_bufferSize
CSizeInt KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_bufferSize private
Size of the buffer that should back the surface (i.e. with scaling applied)
Referenced by ApplySizeUpdate(), CreateNewWindow(), GetBufferSize(), SetResolutionInternal(), and UpdateSizeVariables().
m_compositor
wayland::compositor_t KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_compositor private
Referenced by ApplyOpaqueRegion(), CreateNewWindow(), InitWindowSystem(), and LoadDefaultCursor().
m_configuredSize
CSizeInt KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_configuredSize private
Size of the whole window including window decorations as given by configure.
Referenced by ApplyBufferScale(), ApplyShellSurfaceState(), ApplySizeUpdate(), CreateNewWindow(), ProcessMessages(), and UpdateSizeVariables().
m_connection
std::unique_ptr<CConnection> KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_connection private
Referenced by CreateNewWindow(), CreateSeat(), CreateShellSurface(), DestroyWindowSystem(), GetConnection(), GetOSScreenSaverImpl(), and InitWindowSystem().
m_cursorBuffer
wayland::buffer_t KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_cursorBuffer private
Referenced by DestroyWindowSystem(), and LoadDefaultCursor().
m_cursorImage
wayland::cursor_image_t KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_cursorImage private
Referenced by DestroyWindowSystem(), LoadDefaultCursor(), and OnSetCursor().
m_cursorSurface
wayland::surface_t KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_cursorSurface private
Referenced by DestroyWindowSystem(), LoadDefaultCursor(), and OnSetCursor().
m_cursorTheme
wayland::cursor_theme_t KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_cursorTheme private
Referenced by DestroyWindowSystem(), and LoadDefaultCursor().
m_dispResources
std::set<IDispResource*> KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_dispResources private
Referenced by Register(), SendFocusChange(), and Unregister().
m_dispResourcesMutex
CCriticalSection KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_dispResourcesMutex private
Referenced by Register(), SendFocusChange(), and Unregister().
m_firstSerialAcked
bool KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_firstSerialAcked {false} private
Referenced by AckConfigure().
m_frameCallback
wayland::callback_t KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_frameCallback private
Referenced by DestroyWindowSystem(), and PrepareFramePresentation().
m_frameCallbackEvent
CEvent KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_frameCallbackEvent private
Referenced by PrepareFramePresentation().
m_frameStartTime
std::chrono::steady_clock::time_point KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_frameStartTime {} private
Referenced by FinishFramePresentation(), and GetFrameLatencyAdjustment().
m_isInitialSetFullScreen
bool KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_isInitialSetFullScreen {true} private
Whether this is the first call to SetFullScreen.
Referenced by SetResolutionExternal().
m_lastAckedSerial
std::uint32_t KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_lastAckedSerial {0u} private
Referenced by AckConfigure().
m_lastSetOutput
wayland::output_t KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_lastSetOutput private
Referenced by CreateNewWindow(), DestroyWindow(), ProcessMessages(), SetResolutionExternal(), and UpdateResolutions().
m_latencyMovingAverage
std::atomic<float> KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_latencyMovingAverage private
Referenced by GetDisplayLatency(), and PrepareFramePresentation().
[struct]
struct { ... } KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_next
Referenced by ApplyNextState(), and SetResolutionInternal().
m_osCursorVisible
bool KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_osCursorVisible {true} private
Referenced by OnSetCursor(), and ShowOSMouse().
m_outputs
std::map<std::uint32_t, std::shared_ptr<COutput> > KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_outputs private
Referenced by DestroyWindowSystem(), FindOutputByUserFriendlyName(), FindOutputByWaylandOutput(), GetConnectedOutputs(), InitWindowSystem(), OnOutputDone(), OnOutputRemoved(), and UpdateResolutions().
m_outputsInPreparation
std::map<std::uint32_t, std::shared_ptr<COutput> > KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_outputsInPreparation private
outputs that did not receive their done event yet
Referenced by DestroyWindowSystem(), OnOutputAdded(), OnOutputDone(), and OnOutputRemoved().
m_outputsMutex
CCriticalSection KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_outputsMutex private
Referenced by FindOutputByUserFriendlyName(), FindOutputByWaylandOutput(), GetConnectedOutputs(), OnOutputDone(), OnOutputRemoved(), ProcessMessages(), and UpdateResolutions().
m_presentation
wayland::presentation_t KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_presentation private
Referenced by GetDisplayLatency(), GetVideoSync(), InitWindowSystem(), and PrepareFramePresentation().
m_presentationClock
clockid_t KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_presentationClock private
Referenced by GetPresentationClockTime(), and InitWindowSystem().
m_presentationFeedbackHandlers
CSignalHandlerList<PresentationFeedbackHandler> KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_presentationFeedbackHandlers private
Referenced by PrepareFramePresentation(), and RegisterOnPresentationFeedback().
m_protocol
Actor::Protocol KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_protocol private
Protocol for communicating events to the main thread.
Referenced by OnConfigure(), OnOutputDone(), ProcessMessages(), and UpdateBufferScale().
m_registry
std::unique_ptr<CRegistry> KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_registry private
Referenced by DestroyWindowSystem(), and InitWindowSystem().
m_scale
int KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_scale {1} private
Scale in use for main surface buffer.
Referenced by ApplyBufferScale(), ApplyShellSurfaceState(), ApplySizeUpdate(), CreateNewWindow(), OnConfigure(), ProcessMessages(), SetResolutionExternal(), and UpdateSizeVariables().
m_seatInputProcessing
std::unique_ptr<CSeatInputProcessing> KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_seatInputProcessing private
Referenced by ApplyBufferScale(), CreateNewWindow(), DestroyWindowSystem(), OnSeatAdded(), and OnSeatRemoved().
m_seatRegistry
std::unique_ptr<CRegistry> KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_seatRegistry private
Registry used exclusively for wayland::seat_t
Use extra registry because seats can only be registered after the surface has been created
Referenced by CreateNewWindow(), and DestroyWindow().
m_seats
std::map<std::uint32_t, std::unique_ptr<CSeat> > KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_seats private
Referenced by CreateNewWindow(), DestroyWindow(), GetClipboardText(), HasCursor(), OnSeatAdded(), OnSeatRemoved(), and OnSetCursor().
m_seatsMutex
CCriticalSection KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_seatsMutex private
Referenced by GetClipboardText(), HasCursor(), OnSeatAdded(), and OnSeatRemoved().
m_shellSurface
std::unique_ptr<IShellSurface> KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_shellSurface private
Referenced by AckConfigure(), ApplyWindowGeometry(), CreateNewWindow(), DestroyWindow(), GetShellSurface(), Minimize(), OnWindowMaximize(), OnWindowMinimize(), OnWindowMove(), OnWindowResize(), OnWindowShowContextMenu(), ProcessMessages(), and SetResolutionExternal().
m_shellSurfaceInitializing
bool KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_shellSurfaceInitializing {false} private
Whether the shell surface is waiting for initial configure.
Referenced by CreateNewWindow(), and OnConfigure().
m_shellSurfaceState
IShellSurface::StateBitset KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_shellSurfaceState private
Shell surface state last acked.
Referenced by ApplyBufferScale(), ApplyShellSurfaceState(), ApplySizeUpdate(), CreateNewWindow(), OnConfigure(), OnWindowMaximize(), ProcessMessages(), and SetResolutionExternal().
m_shm
wayland::shm_t KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_shm private
Referenced by InitWindowSystem(), and LoadDefaultCursor().
m_surface
wayland::surface_t KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_surface private
Referenced by ApplyBufferScale(), ApplyOpaqueRegion(), CreateNewWindow(), CreateShellSurface(), DestroyWindow(), GetMainSurface(), GetOSScreenSaverImpl(), GetVideoSync(), PrepareFramePresentation(), and ProcessMessages().
m_surfaceOutputs
std::set<std::shared_ptr<COutput> > KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_surfaceOutputs private
Set of outputs that show some part of our main surface as indicated by compositor
Referenced by CreateNewWindow(), DestroyWindow(), SetResolutionInternal(), UpdateBufferScale(), and UpdateTouchDpi().
m_surfaceOutputsMutex
CCriticalSection KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_surfaceOutputsMutex private
Referenced by CreateNewWindow(), and SetResolutionInternal().
m_surfaceSize
CSizeInt KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_surfaceSize private
Size of our surface in "surface coordinates" (i.e. without scaling applied) and without window decorations
Referenced by ApplyOpaqueRegion(), and UpdateSizeVariables().
m_surfaceSubmissions
std::list<SurfaceSubmission> KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_surfaceSubmissions private
Referenced by DestroyWindow(), and PrepareFramePresentation().
m_surfaceSubmissionsMutex
CCriticalSection KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_surfaceSubmissionsMutex private
Referenced by PrepareFramePresentation().
m_syncOutputID
std::uint32_t KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_syncOutputID private
Protocol object ID of the sync output returned by wp_presentation.
Referenced by PrepareFramePresentation().
m_syncOutputRefreshRate
std::atomic<float> KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_syncOutputRefreshRate {0.0f} private
Refresh rate of sync output returned by wp_presentation.
Referenced by GetSyncOutputRefreshRate(), and PrepareFramePresentation().
m_waitingForApply
bool KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_waitingForApply {false} private
Referenced by FinishModeChange(), FinishWindowResize(), ProcessMessages(), SetResolutionExternal(), and SetResolutionInternal().
m_windowDecorator
std::unique_ptr<CWindowDecorator> KODI::WINDOWING::WAYLAND::CWinSystemWayland::m_windowDecorator private
Referenced by ApplyBufferScale(), ApplyShellSurfaceState(), ApplySizeUpdate(), ApplyWindowGeometry(), CalculateSizes(), CreateNewWindow(), DestroyWindow(), OnSeatAdded(), and OnSeatRemoved().
mustBeAcked
bool KODI::WINDOWING::WAYLAND::CWinSystemWayland::mustBeAcked {false}
scale
int KODI::WINDOWING::WAYLAND::CWinSystemWayland::scale {1}
Referenced by CalculateSizes(), SetResolutionInternal(), and UpdateSizeVariables().
shellSurfaceState
IShellSurface::StateBitset KODI::WINDOWING::WAYLAND::CWinSystemWayland::shellSurfaceState
The documentation for this class was generated from the following files:
WinSystemWayland.h
WinSystemWayland.cpp