Kodi Documentation: TestPlayListFileItemClassify.cpp File Reference
TestPlayListFileItemClassify.cpp File Reference
#include "FileItem.h"
#include "playlists/PlayListFileItemClassify.h"
#include "utils/Variant.h"
#include <array>
#include <gtest/gtest.h>
Classes
struct PlayListClassifyTest
class PlayListTest
Functions
TEST_P (PlayListTest, IsPlayList)
INSTANTIATE_TEST_SUITE_P (TestPlayListFileItemClassify, PlayListTest, testing::ValuesIn(playlist_tests))
TEST (TestPlayListFileItemClassify, IsSmartPlayList)
Variables
const auto playlist_tests
Function Documentation
INSTANTIATE_TEST_SUITE_P()
INSTANTIATE_TEST_SUITE_P (TestPlayListFileItemClassify , PlayListTest , testing::ValuesIn(playlist_tests))
TEST()
TEST (TestPlayListFileItemClassify , IsSmartPlayList)
References EXPECT_TRUE(), KODI::PLAYLIST::IsSmartPlayList(), and CGUIListItem::SetProperty().
TEST_P()
TEST_P (PlayListTest , IsPlayList)
References EXPECT_EQ(), and KODI::PLAYLIST::IsPlayList().
Variable Documentation
playlist_tests
const auto playlist_tests
Initial value:
= std::array{
    PlayListClassifyTest{"/home/user/video.avi", false},
    PlayListClassifyTest{"/home/user/video.avi", false, "video/avi"},
    PlayListClassifyTest{"https://some.where/foo.m3u8", false},
    PlayListClassifyTest{"https://some.where/something", true, "audio/x-pn-realaudio"},
    PlayListClassifyTest{"https://some.where/something", true, "playlist"},
    PlayListClassifyTest{"https://some.where/something", true, "audio/x-mpegurl"},
    PlayListClassifyTest{"/home/user/video.m3u", true},
    PlayListClassifyTest{"/home/user/video.m3u8", true},
    PlayListClassifyTest{"/home/user/video.b4s", true},
    PlayListClassifyTest{"/home/user/video.pls", true},
    PlayListClassifyTest{"/home/user/video.strm", true},
    PlayListClassifyTest{"/home/user/video.wpl", true},
    PlayListClassifyTest{"/home/user/video.asx", true},
    PlayListClassifyTest{"/home/user/video.ram", true},
    PlayListClassifyTest{"/home/user/video.url", true},
    PlayListClassifyTest{"/home/user/video.pxml", true},
    PlayListClassifyTest{"/home/user/video.xspf", true},
}