Kodi Documentation: anonymous_namespace{AddonSettings.cpp} Namespace Reference
anonymous_namespace{AddonSettings.cpp} Namespace Reference
Functions
bool InfoBool (const std::string &condition, const std::string &value, const SettingConstPtr &setting, void *data)
template<class TSetting >
SettingPtr InitializeFromOldSettingWithoutDefinition (ADDON::CAddonSettings &settings, const std::string &settingId, const typename TSetting::Value &defaultValue)
template<>
SettingPtr InitializeFromOldSettingWithoutDefinition< CSettingString > (ADDON::CAddonSettings &settings, const std::string &settingId, const typename CSettingString::Value &defaultValue)
template<class TSetting >
SettingPtr AddSettingWithoutDefinition (ADDON::CAddonSettings &settings, const std::string &settingId, typename TSetting::Value defaultValue, const Logger &logger)
Variables
constexpr auto OldSettingValuesSeparator = "|"
constexpr int UnknownSettingLabelIdStart = 100000
Function Documentation
AddSettingWithoutDefinition()
template<class TSetting > SettingPtr anonymous_namespace{AddonSettings.cpp}::AddSettingWithoutDefinition (ADDON::CAddonSettings & settings, const std::string & settingId, typename TSetting::Value defaultValue, const Logger & logger)
References CSettingsManager::AddSetting(), ADDON::CAddonSettings::GetAddonId(), CSettingsManager::GetSections(), CSettingsBase::GetSettingsManager(), ADDON::CAddonSettings::Initialize(), and CSettingsBase::IsInitialized().
InfoBool()
bool anonymous_namespace{AddonSettings.cpp}::InfoBool (const std::string & condition, const std::string & value, const SettingConstPtr & setting, void * data)
References INFO::DEFAULT_CONTEXT, CGUIInfoManager::EvaluateBool(), CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), and value.
InitializeFromOldSettingWithoutDefinition()
template<class TSetting > SettingPtr anonymous_namespace{AddonSettings.cpp}::InitializeFromOldSettingWithoutDefinition (ADDON::CAddonSettings & settings, const std::string & settingId, const typename TSetting::Value & defaultValue)
References CSettingsBase::GetSettingsManager(), and Internal.
InitializeFromOldSettingWithoutDefinition< CSettingString >()
template<> SettingPtr anonymous_namespace{AddonSettings.cpp}::InitializeFromOldSettingWithoutDefinition< CSettingString > (ADDON::CAddonSettings & settings, const std::string & settingId, const typename CSettingString::Value & defaultValue)
References CSettingsBase::GetSettingsManager(), and Internal.
Variable Documentation
OldSettingValuesSeparator
constexpr auto anonymous_namespace{AddonSettings.cpp}::OldSettingValuesSeparator = "|" constexpr
UnknownSettingLabelIdStart
constexpr int anonymous_namespace{AddonSettings.cpp}::UnknownSettingLabelIdStart = 100000 constexpr