Kodi Documentation: ApplicationBuiltins.cpp File Reference
ApplicationBuiltins.cpp File Reference
#include "ApplicationBuiltins.h"
#include "ServiceBroker.h"
#include "application/ApplicationComponents.h"
#include "application/ApplicationPowerHandling.h"
#include "application/ApplicationVolumeHandling.h"
#include "filesystem/ZipManager.h"
#include "input/actions/ActionIDs.h"
#include "interfaces/AnnouncementManager.h"
#include "messaging/ApplicationMessenger.h"
#include "network/Network.h"
#include "settings/AdvancedSettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "utils/JSONVariantParser.h"
#include "utils/StringUtils.h"
#include "utils/URIUtils.h"
#include "utils/Variant.h"
#include "utils/log.h"
#include <stdlib.h>
Functions
static int Extract (const std::vector< std::string > &params)
Extract an archive.
static int Mute (const std::vector< std::string > &params)
Mute volume.
static int NotifyAll (const std::vector< std::string > &params)
Notify all listeners on announcement bus.
static int SetVolume (const std::vector< std::string > &params)
Set volume.
static int ToggleDebug (const std::vector< std::string > &params)
Toggle debug info.
static int ToggleDPMS (const std::vector< std::string > &params)
Toggle DPMS state.
static int WakeOnLAN (const std::vector< std::string > &params)
Send a WOL packet to a given host.
Function Documentation
Extract()
static int Extract (const std::vector< std::string > & params) static
Extract an archive.
Parameters
params The parameters
params[0] = The archive URL. params[1] = Destination path (optional). If not given, extracts to folder with archive.
References URIUtils::AddSlashAtEnd(), CZipManager::ExtractArchive(), g_ZipManager, URIUtils::GetDirectory(), URIUtils::IsZIP(), CLog::Log(), and LOGERROR.
Referenced by CApplicationBuiltins::GetOperations().
Mute()
static int Mute (const std::vector< std::string > & params) static
Mute volume.
Parameters
params (ignored)
References CServiceBroker::GetAppComponents(), and CApplicationVolumeHandling::ToggleMute().
Referenced by CApplicationBuiltins::GetOperations().
NotifyAll()
static int NotifyAll (const std::vector< std::string > & params) static
Notify all listeners on announcement bus.
Parameters
params The parameters.
params[0] = sender. params[1] = data. params[2] = JSON with extra parameters (optional).
References data(), CServiceBroker::GetAnnouncementManager(), CLog::Log(), LOGERROR, ANNOUNCEMENT::Other, and CJSONVariantParser::Parse().
Referenced by CApplicationBuiltins::GetOperations().
SetVolume()
static int SetVolume (const std::vector< std::string > & params) static
Set volume.
Parameters
params the parameters.
params[0] = Volume level. params[1] = "showVolumeBar" to show volume bar (optional).
References ACTION_VOLUME_DOWN, ACTION_VOLUME_UP, KODI::UTILS::StringUtils::EqualsNoCase(), CServiceBroker::GetAppComponents(), CServiceBroker::GetAppMessenger(), CApplicationVolumeHandling::GetVolumePercent(), and TMSG_VOLUME_SHOW.
Referenced by ADDON::Interface_AudioEngine::aestream_set_volume(), and CApplicationBuiltins::GetOperations().
ToggleDebug()
static int ToggleDebug (const std::vector< std::string > & params) static
Toggle debug info.
Parameters
params (ignored)
References CServiceBroker::GetSettingsComponent(), and CSettings::SETTING_DEBUG_SHOWLOGINFO.
Referenced by CApplicationBuiltins::GetOperations().
ToggleDPMS()
static int ToggleDPMS (const std::vector< std::string > & params) static
Toggle DPMS state.
Parameters
params (ignored)
References CServiceBroker::GetAppComponents(), and CApplicationPowerHandling::ToggleDPMS().
Referenced by CApplicationBuiltins::GetOperations().
WakeOnLAN()
static int WakeOnLAN (const std::vector< std::string > & params) static
Send a WOL packet to a given host.
Parameters
params The parameters.
params[0] = The MAC of the host to wake.
References CServiceBroker::GetNetwork(), and CNetworkBase::WakeOnLan().
Referenced by CApplicationBuiltins::GetOperations().