Kodi Documentation: CGUIControl Class Reference
CGUIControl Class Reference abstract
Guilib classes » Window Reference » Controls
Base class for controls.
#include <GUIControl.h>
Public Types
enum GUICONTROLTYPES {
GUICONTROL_UNKNOWN , GUICONTAINER_EPGGRID , GUICONTAINER_FIXEDLIST , GUICONTAINER_LIST ,
GUICONTAINER_PANEL , GUICONTAINER_WRAPLIST , GUICONTROL_BORDEREDIMAGE , GUICONTROL_BUTTON ,
GUICONTROL_COLORBUTTON , GUICONTROL_EDIT , GUICONTROL_FADELABEL , GUICONTROL_GAME ,
GUICONTROL_GAMECONTROLLER , GUICONTROL_GAMECONTROLLERLIST , GUICONTROL_GROUP , GUICONTROL_GROUPLIST ,
GUICONTROL_IMAGE , GUICONTROL_LABEL , GUICONTROL_LISTGROUP , GUICONTROL_LISTLABEL ,
GUICONTROL_MOVER , GUICONTROL_MULTI_IMAGE , GUICONTROL_PROGRESS , GUICONTROL_RADIO ,
GUICONTROL_RANGES , GUICONTROL_RENDERADDON , GUICONTROL_RESIZE , GUICONTROL_RSS ,
GUICONTROL_SCROLLBAR , GUICONTROL_SETTINGS_SLIDER , GUICONTROL_SLIDER , GUICONTROL_SPIN ,
GUICONTROL_SPINEX , GUICONTROL_TEXTBOX , GUICONTROL_TOGGLEBUTTON , GUICONTROL_VIDEO ,
GUICONTROL_VISUALISATION
}
enum GUIVISIBLE { HIDDEN = 0 , DELAYED , VISIBLE }
enum GUISCROLLVALUE { FOCUS = 0 , NEVER , ALWAYS }
typedef std::map< int, CGUIAction > ActionMap
Set actions to perform on navigation.
Public Member Functions
CGUIControl ()
CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
CGUIControl (const CGUIControl &)
virtual ~CGUIControl (void)
virtual CGUIControl * Clone () const =0
virtual void DoProcess (unsigned int currentTime, CDirtyRegionList &dirtyregions)
virtual void Process (unsigned int currentTime, CDirtyRegionList &dirtyregions)
virtual void DoRender ()
virtual void Render ()
virtual void RenderEx ()
bool HasProcessed () const
Returns whether or not we have processed.
virtual bool OnAction (const CAction &action)
virtual void OnUp ()
virtual void OnDown ()
virtual void OnLeft ()
virtual void OnRight ()
virtual bool OnBack ()
virtual bool OnInfo ()
virtual void OnNextControl ()
virtual void OnPrevControl ()
virtual void OnFocus ()
virtual void OnUnFocus ()
virtual EVENT_RESULT SendMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
React to a mouse event.
virtual EVENT_RESULT OnMouseEvent (const CPoint &point, const KODI::MOUSE::CMouseEvent &event)
Perform a mouse action.
virtual void UnfocusFromPoint (const CPoint &point)
Unfocus the control if the given point on screen is not within it's boundary.
virtual bool HitTest (const CPoint &point) const
Used to test whether the point is inside a control.
virtual bool OnMessage (CGUIMessage &message)
virtual int GetID (void) const
virtual void SetID (int id)
int GetParentID () const
virtual bool HasFocus () const
virtual void AllocResources ()
virtual void FreeResources (bool immediately=false)
virtual void DynamicResourceAlloc (bool bOnOff)
virtual bool IsDynamicallyAllocated ()
virtual bool CanFocus () const
virtual bool IsVisible () const
bool IsVisibleFromSkin () const
virtual bool IsDisabled () const
virtual void SetPosition (float posX, float posY)
virtual void SetHitRect (const CRect &rect, const KODI::UTILS::COLOR::Color &color)
virtual void SetCamera (const CPoint &camera)
virtual void SetStereoFactor (const float &factor)
bool SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor &color)
CPoint GetRenderPosition () const
virtual float GetXPosition () const
virtual float GetYPosition () const
virtual float GetWidth () const
virtual float GetHeight () const
virtual void AssignDepth ()
void MarkDirtyRegion (const unsigned int dirtyState=DIRTY_STATE_CONTROL)
bool IsControlDirty () const
const CRect & GetRenderRegion () const
return the render region in screen coordinates of this control
virtual CRect CalcRenderRegion () const
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
void SetActions (const ActionMap &actions)
void SetAction (int actionID, const CGUIAction &action, bool replace=true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
CGUIAction GetAction (int actionID) const
Get an action the control can be perform.
bool Navigate (int direction) const
Start navigating in given direction.
virtual void SetFocus (bool focus)
virtual void SetWidth (float width)
virtual void SetHeight (float height)
virtual void SetVisible (bool bVisible, bool setVisState=false)
void SetVisibleCondition (const std::string &expression, const std::string &allowHiddenFocus="")
bool HasVisibleCondition () const
void SetEnableCondition (const std::string &expression)
virtual void UpdateVisibility (const CGUIListItem *item)
virtual void SetInitialVisibility ()
virtual void SetEnabled (bool bEnable)
virtual void SetInvalid ()
virtual void SetPulseOnSelect (bool pulse)
virtual std::string GetDescription () const
virtual std::string GetDescriptionByIndex (int index) const
void SetAnimations (const std::vector< CAnimation > &animations)
const std::vector< CAnimation > & GetAnimations () const
virtual void QueueAnimation (ANIMATION_TYPE anim)
virtual bool IsAnimating (ANIMATION_TYPE anim)
virtual bool HasAnimation (ANIMATION_TYPE anim)
CAnimation * GetAnimation (ANIMATION_TYPE type, bool checkConditions=true)
virtual void ResetAnimation (ANIMATION_TYPE type)
virtual void ResetAnimations ()
virtual void UpdateInfo (const CGUIListItem *item=NULL)
virtual void SetPushUpdates (bool pushUpdates)
virtual bool IsGroup () const
virtual bool IsContainer () const
virtual bool GetCondition (int condition, int data) const
void SetParentControl (CGUIControl *control)
CGUIControl * GetParentControl (void) const
virtual void SaveStates (std::vector< CControlState > &states)
virtual CGUIControl * GetControl (int id, std::vector< CGUIControl * > *idCollector=nullptr)
void SetControlStats (GUICONTROLSTATS *controlStats)
virtual void UpdateControlStats ()
GUICONTROLTYPES GetControlType () const
bool IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Protected Member Functions
virtual CPoint GetPosition () const
Return the coordinates of the top left of the control, in the control's parent coordinates.
virtual bool OnMouseOver (const CPoint &point)
Called when the mouse is over the control. Default implementation selects the control.
virtual bool CanFocusFromPoint (const CPoint &point) const
Test whether we can focus a control from a point on screen.
virtual bool UpdateColors (const CGUIListItem *item)
virtual bool Animate (unsigned int currentTime)
virtual bool CheckAnimation (ANIMATION_TYPE animType)
void UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState)
bool SendWindowMessage (CGUIMessage &message) const
Protected Attributes
ActionMap m_actions
float m_posX
float m_posY
float m_height
float m_width
CRect m_hitRect
KODI::UTILS::COLOR::Color m_hitColor = 0xffffffff
KODI::GUILIB::GUIINFO::CGUIInfoColor m_diffuseColor
int m_controlID
int m_parentID
bool m_bHasFocus
bool m_bInvalidated
bool m_bAllocated
bool m_pulseOnSelect
GUICONTROLTYPES ControlType
GUICONTROLSTATS * m_controlStats
CGUIControl * m_parentControl
INFO::InfoPtr m_visibleCondition
GUIVISIBLE m_visible
bool m_visibleFromSkinCondition
bool m_forceHidden
KODI::GUILIB::GUIINFO::CGUIInfoBool m_allowHiddenFocus
bool m_hasProcessed
INFO::InfoPtr m_enableCondition
bool m_enabled
bool m_pushedUpdates
std::vector< CAnimation > m_animations
CPoint m_camera
bool m_hasCamera
float m_stereo
TransformMatrix m_transform
TransformMatrix m_cachedTransform
bool m_isCulled {true}
unsigned int m_controlDirtyState
CRect m_renderRegion
Static Protected Attributes
static const unsigned int DIRTY_STATE_CONTROL = 1
static const unsigned int DIRTY_STATE_CHILD = 2
Detailed Description
Base class for controls.
Member Typedef Documentation
ActionMap
typedef std::map<int, CGUIAction> CGUIControl::ActionMap
Set actions to perform on navigation.
Parameters
actions ActionMap of actions
See also
SetNavigationAction
Member Enumeration Documentation
GUICONTROLTYPES
enum CGUIControl::GUICONTROLTYPES
Enumerator
GUICONTROL_UNKNOWN
GUICONTAINER_EPGGRID
GUICONTAINER_FIXEDLIST
GUICONTAINER_LIST
GUICONTAINER_PANEL
GUICONTAINER_WRAPLIST
GUICONTROL_BORDEREDIMAGE
GUICONTROL_BUTTON
GUICONTROL_COLORBUTTON
GUICONTROL_EDIT
GUICONTROL_FADELABEL
GUICONTROL_GAME
GUICONTROL_GAMECONTROLLER
GUICONTROL_GAMECONTROLLERLIST
GUICONTROL_GROUP
GUICONTROL_GROUPLIST
GUICONTROL_IMAGE
GUICONTROL_LABEL
GUICONTROL_LISTGROUP
GUICONTROL_LISTLABEL
GUICONTROL_MOVER
GUICONTROL_MULTI_IMAGE
GUICONTROL_PROGRESS
GUICONTROL_RADIO
GUICONTROL_RANGES
GUICONTROL_RENDERADDON
GUICONTROL_RESIZE
GUICONTROL_RSS
GUICONTROL_SCROLLBAR
GUICONTROL_SETTINGS_SLIDER
GUICONTROL_SLIDER
GUICONTROL_SPIN
GUICONTROL_SPINEX
GUICONTROL_TEXTBOX
GUICONTROL_TOGGLEBUTTON
GUICONTROL_VIDEO
GUICONTROL_VISUALISATION
GUISCROLLVALUE
enum CGUIControl::GUISCROLLVALUE
Enumerator
FOCUS
NEVER
ALWAYS
GUIVISIBLE
enum CGUIControl::GUIVISIBLE
Enumerator
HIDDEN
DELAYED
VISIBLE
Constructor & Destructor Documentation
CGUIControl() [1/3]
CGUIControl::CGUIControl ()
References ControlType, DIRTY_STATE_CONTROL, GUICONTROL_UNKNOWN, m_bAllocated, m_bHasFocus, m_bInvalidated, m_controlDirtyState, m_controlID, m_controlStats, m_enabled, m_forceHidden, m_hasCamera, m_hasProcessed, m_height, m_parentControl, m_parentID, m_posX, m_posY, m_pulseOnSelect, m_pushedUpdates, m_stereo, m_visible, m_visibleFromSkinCondition, m_width, and VISIBLE.
CGUIControl() [2/3]
CGUIControl::CGUIControl (int parentID, int controlID, float posX, float posY, float width, float height)
References ControlType, DIRTY_STATE_CONTROL, GUICONTROL_UNKNOWN, m_bAllocated, m_bHasFocus, m_bInvalidated, m_controlDirtyState, m_controlID, m_controlStats, m_enabled, m_forceHidden, m_hasCamera, m_hasProcessed, m_height, m_parentControl, m_parentID, m_posX, m_posY, m_pulseOnSelect, m_pushedUpdates, m_stereo, m_visible, m_visibleFromSkinCondition, m_width, and VISIBLE.
CGUIControl() [3/3]
CGUIControl::CGUIControl (const CGUIControl &) default
~CGUIControl()
CGUIControl::~CGUIControl (void) virtual default
Member Function Documentation
AllocResources()
void CGUIControl::AllocResources () virtual
Reimplemented in CGUIBaseContainer, CGUIBorderedImage, CGUIButtonControl, CGUIColorButtonControl, CGUIControlGroup, CGUIImage, CGUIMoverControl, CGUIMultiImage, CGUIProgressControl, CGUIRadioButtonControl, CGUIRangesControl, CGUIResizeControl, GUIScrollBarControl, CGUISettingsSliderControl, CGUISliderControl, CGUISpinControl, CGUISpinControlEx, CGUIToggleButtonControl, CGUIWindow, and PVR::CGUIEPGGridContainer.
References m_bAllocated, m_bInvalidated, and m_hasProcessed.
Referenced by CGUIDialogSettingsBase::AddSettingControl(), CGUIBaseContainer::AllocResources(), CGUIButtonControl::AllocResources(), CGUIControlGroup::AllocResources(), CGUIImage::AllocResources(), CGUIMoverControl::AllocResources(), CGUIMultiImage::AllocResources(), CGUIProgressControl::AllocResources(), CGUIRangesControl::AllocResources(), CGUIResizeControl::AllocResources(), GUIScrollBarControl::AllocResources(), CGUISliderControl::AllocResources(), CGUISpinControl::AllocResources(), PVR::CGUIEPGGridContainer::AllocResources(), ADDON::CGUIAddonWindow::AllocResources(), XBMCAddon::xbmcgui::WindowXMLInterceptor::AllocResources(), KODI::GAME::CGUIFeatureGroupTitle::CGUIFeatureGroupTitle(), XBMCAddon::xbmcgui::Window::doAddControl(), and CGUIWindow::OnMessage().
Animate()
bool CGUIControl::Animate (unsigned int currentTime) protected virtual
Reimplemented in CGUIWindow.
References ANIM_PROCESS_NONE, CAnimation::Animate(), center, DELAYED, GetHeight(), CAnimation::GetProcess(), CAnimation::GetState(), CAnimation::GetType(), GetWidth(), GetXPosition(), GetYPosition(), HasProcessed(), m_animations, m_transform, m_visible, CAnimation::RenderAnimation(), TransformMatrix::Reset(), and UpdateStates().
Referenced by CGUIWindow::Animate(), and DoProcess().
AssignDepth()
void CGUIControl::AssignDepth () virtual
Reimplemented in CGUIBaseContainer, CGUIControlGroup, CGUIFadeLabelControl, CGUITextBox, and PVR::CGUIEPGGridContainer.
References TransformMatrix::depth, CGraphicContext::GetDepth(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), and m_cachedTransform.
Referenced by CGUIControlGroup::AssignDepth(), CGUIFadeLabelControl::AssignDepth(), and CGUITextBox::AssignDepth().
CalcRenderRegion()
CRect CGUIControl::CalcRenderRegion () const virtual
calculate the render region in parentcontrol coordinates of this control Called during process to update m_renderRegion
Reimplemented in CGUIBorderedImage, CGUIButtonControl, CGUIImage, CGUILabelControl, CGUIListLabel, and CGUIRSSControl.
References GetHeight(), GetWidth(), GetXPosition(), GetYPosition(), CPointGen< T >::x, and CPointGen< T >::y.
Referenced by CGUIButtonControl::CalcRenderRegion(), CGUIImage::CalcRenderRegion(), CGUIRSSControl::CalcRenderRegion(), and Process().
CanFocus()
bool CGUIControl::CanFocus () const virtual
Reimplemented in KODI::RETRO::CGUIGameControl, CGUIBaseContainer, CGUIControlGroup, CGUIFadeLabelControl, CGUIImage, CGUILabelControl, CGUIListLabel, CGUIMoverControl, CGUIMultiImage, CGUIProgressControl, CGUIRangesControl, CGUIRenderingControl, CGUIResizeControl, CGUIRSSControl, CGUITextBox, CGUIVideoControl, and CGUIVisualisationControl.
References IsDisabled(), IsVisible(), and m_allowHiddenFocus.
Referenced by CGUIBaseContainer::CanFocus(), CGUIControlGroup::CanFocus(), CanFocusFromPoint(), CGUIWindow::DoProcess(), CGUIControlGroupList::GetFirstFocusableControl(), CGUIControlGroupList::GetLastFocusableControl(), OnMessage(), CGUIControlGroupList::OnMessage(), OnMouseOver(), CGUIControlGroup::SendMouseEvent(), CGUIControlGroupList::SendMouseEvent(), and CGUIBaseContainer::UpdateVisibility().
CanFocusFromPoint()
bool CGUIControl::CanFocusFromPoint (const CPoint & point) const protected virtual
Test whether we can focus a control from a point on screen.
Parameters
point the location in vanilla skin coordinates from the upper left corner of the parent control.
Returns
true if the control can be focused from this location
See also
UnfocusFromPoint, HitRect
Reimplemented in CGUIRenderingControl, CGUIVideoControl, and CGUIVisualisationControl.
References CanFocus(), and HitTest().
Referenced by SendMouseEvent().
CheckAnimation()
bool CGUIControl::CheckAnimation (ANIMATION_TYPE animType) protected virtual
Reimplemented in CGUIWindow.
References ANIM_PROCESS_NORMAL, ANIM_STATE_APPLIED, ANIM_TYPE_HIDDEN, ANIM_TYPE_VISIBLE, ANIM_TYPE_WINDOW_CLOSE, ANIM_TYPE_WINDOW_OPEN, HasProcessed(), IsAnimating(), IsVisible(), ResetAnimation(), and UpdateStates().
Referenced by QueueAnimation().
Clone()
virtual CGUIControl * CGUIControl::Clone () const pure virtual
Implemented in KODI::RETRO::CGUIGameControl, KODI::GAME::CGUIGameController, KODI::GAME::CGUIGameControllerList, CGUIBorderedImage, CGUIButtonControl, CGUIColorButtonControl, CGUIControlGroup, CGUIControlGroupList, CGUIEditControl, CGUIFadeLabelControl, CGUIFixedListContainer, CGUIImage, CGUILabelControl, CGUIListContainer, CGUIListGroup, CGUIListLabel, CGUIMoverControl, CGUIMultiImage, CGUIPanelContainer, CGUIProgressControl, CGUIRadioButtonControl, CGUIRangesControl, CGUIRenderingControl, CGUIResizeControl, CGUIRSSControl, GUIScrollBarControl, CGUISettingsSliderControl, CGUISliderControl, CGUISpinControl, CGUISpinControlEx, CGUITextBox, CGUIToggleButtonControl, CGUIVideoControl, CGUIVisualisationControl, CGUIWrappingListContainer, and PVR::CGUIEPGGridContainer.
DoProcess()
void CGUIControl::DoProcess (unsigned int currentTime, CDirtyRegionList & dirtyregions) virtual
Reimplemented in CGUIDialogBusy, CGUIDialogBusyNoCancel, KODI::GAME::CGUIGameController, KODI::GAME::CGUIControllerWindow, CGUIBaseContainer, CGUIDialog, CGUITextBox, CGUIWindow, CGUIDialogSettingsBase, and CGUIWindowSettingsScreenCalibration.
References CGraphicContext::AddTransform(), TransformMatrix::alpha, Animate(), DIRTY_STATE_CONTROL, CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), IsVisible(), m_bInvalidated, m_cachedTransform, m_camera, m_controlDirtyState, m_hasCamera, m_isCulled, m_renderRegion, m_transform, MarkDirtyRegion(), Process(), CGraphicContext::RemoveTransform(), CGraphicContext::RestoreCameraPosition(), CGraphicContext::SetCameraPosition(), CRectGen< T >::Union(), and UpdateControlStats().
Referenced by KODI::GAME::CGUIGameController::DoProcess(), CGUIBaseContainer::DoProcess(), CGUITextBox::DoProcess(), CGUIWindow::DoProcess(), CGUIWindowSettingsScreenCalibration::DoProcess(), CGUIListItemLayout::Process(), CGUIControlGroupList::Process(), CGUIListGroup::Process(), CGUIMultiImage::Process(), CGUISettingsSliderControl::Process(), CGUISpinControlEx::Process(), and CGUIToggleButtonControl::Process().
DoRender()
void CGUIControl::DoRender () virtual
Reimplemented in CGUIWindow, and CGUIWindowSettingsScreenCalibration.
References color, CGUITexture::DrawQuad(), CWinSystemBase::GetGfxContext(), CGraphicContext::GetScissors(), CGraphicContext::GetStereoMode(), CServiceBroker::GetWinSystem(), GUIPROFILER_RENDER_BEGIN, GUIPROFILER_RENDER_END, CRectGen< T >::Intersects(), IsControlRenderable(), IsVisible(), m_cachedTransform, m_camera, m_hasCamera, m_hitColor, m_hitRect, m_isCulled, m_renderRegion, m_stereo, CGraphicContext::MergeAlpha(), CGraphicContext::RemoveTransform(), Render(), RENDER_STEREO_MODE_MONO, RENDER_STEREO_MODE_OFF, CGraphicContext::RestoreCameraPosition(), CGraphicContext::RestoreStereoFactor(), CGraphicContext::SetCameraPosition(), CGraphicContext::SetStereoFactor(), and CGraphicContext::SetTransform().
Referenced by CGUIWindow::DoRender(), CGUIControlGroup::Render(), CGUIControlGroupList::Render(), and CGUIListItemLayout::Render().
DynamicResourceAlloc()
void CGUIControl::DynamicResourceAlloc (bool bOnOff) virtual
Reimplemented in CGUIBorderedImage, CGUIButtonControl, CGUIColorButtonControl, CGUIControlGroup, CGUIImage, CGUIMoverControl, CGUIMultiImage, CGUIProgressControl, CGUIRadioButtonControl, CGUIRangesControl, CGUIResizeControl, GUIScrollBarControl, CGUISettingsSliderControl, CGUISliderControl, CGUISpinControl, CGUISpinControlEx, CGUIToggleButtonControl, and CGUIWindow.
Referenced by CGUIButtonControl::DynamicResourceAlloc(), CGUIColorButtonControl::DynamicResourceAlloc(), CGUIImage::DynamicResourceAlloc(), CGUIMoverControl::DynamicResourceAlloc(), CGUIMultiImage::DynamicResourceAlloc(), CGUIProgressControl::DynamicResourceAlloc(), CGUIRadioButtonControl::DynamicResourceAlloc(), CGUIRangesControl::DynamicResourceAlloc(), CGUIResizeControl::DynamicResourceAlloc(), GUIScrollBarControl::DynamicResourceAlloc(), CGUISliderControl::DynamicResourceAlloc(), and CGUISpinControl::DynamicResourceAlloc().
FreeResources()
void CGUIControl::FreeResources (bool immediately = false) virtual
Reimplemented in CGUIRangesControl, CGUIWindow, CGUIWindowSettingsScreenCalibration, PVR::CGUIEPGGridContainer, CGUIBaseContainer, CGUIBorderedImage, CGUIButtonControl, CGUIColorButtonControl, CGUIControlGroup, CGUIImage, CGUIMoverControl, CGUIMultiImage, CGUIProgressControl, CGUIRadioButtonControl, CGUIRenderingControl, CGUIResizeControl, GUIScrollBarControl, CGUISettingsSliderControl, CGUISliderControl, CGUISpinControl, CGUISpinControlEx, CGUIToggleButtonControl, and CGUIVisualisationControl.
References ANIM_TYPE_CONDITIONAL, CAnimation::GetType(), m_animations, m_bAllocated, m_hasProcessed, and CAnimation::ResetAnimation().
Referenced by CGUIRangesControl::FreeResources(), XBMCAddon::xbmcgui::WindowXMLInterceptor::FreeResources(), PVR::CGUIEPGGridContainer::FreeResources(), CGUIBaseContainer::FreeResources(), CGUIButtonControl::FreeResources(), CGUIControlGroup::FreeResources(), CGUIImage::FreeResources(), CGUIMoverControl::FreeResources(), CGUIMultiImage::FreeResources(), CGUIProgressControl::FreeResources(), CGUIResizeControl::FreeResources(), GUIScrollBarControl::FreeResources(), CGUISliderControl::FreeResources(), CGUISpinControl::FreeResources(), CGUIVisualisationControl::FreeResources(), and CGUIWindow::OnMessage().
GetAction()
CGUIAction CGUIControl::GetAction (int actionID) const
Get an action the control can be perform.
Parameters
actionID The actionID to retrieve.
References m_actions.
Referenced by CGUIControlGroupList::AddControl(), XBMCAddon::xbmcgui::Window::GetControlById(), CGUIBaseContainer::OnDown(), CGUIPanelContainer::OnDown(), PVR::CGUIEPGGridContainer::OnDown(), OnInfo(), CGUIBaseContainer::OnLeft(), CGUIPanelContainer::OnLeft(), PVR::CGUIEPGGridContainer::OnLeft(), CGUIWindow::OnMove(), CGUIBaseContainer::OnRight(), CGUIPanelContainer::OnRight(), PVR::CGUIEPGGridContainer::OnRight(), CGUIBaseContainer::OnUp(), CGUIPanelContainer::OnUp(), PVR::CGUIEPGGridContainer::OnUp(), and PVR::CGUIWindowPVRGuideBase::ShouldNavigateToGridContainer().
GetAnimation()
CAnimation * CGUIControl::GetAnimation (ANIMATION_TYPE type, bool checkConditions = true)
References CAnimation::CheckCondition(), CAnimation::GetType(), and m_animations.
Referenced by HasAnimation(), QueueAnimation(), and SetVisible().
GetAnimations()
const std::vector< CAnimation > & CGUIControl::GetAnimations () const inline
References m_animations.
GetCondition()
virtual bool CGUIControl::GetCondition (int condition, int data) const inline virtual
Reimplemented in CGUIBaseContainer, CGUIControlGroupList, CGUIPanelContainer, and CGUITextBox.
Referenced by KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool().
GetControl()
CGUIControl * CGUIControl::GetControl (int id, std::vector< CGUIControl * > * idCollector = nullptr) virtual
Reimplemented in CGUIControlLookup.
References m_controlID.
Referenced by CGUIControlGroupList::OnMessage(), and CGUIDialogSettingsBase::UpdateSettings().
GetControlType()
GUICONTROLTYPES CGUIControl::GetControlType () const inline
References ControlType.
Referenced by CGUIListGroup::AddControl(), CGUIControlProfilerItem::CGUIControlProfilerItem(), KODI::GAME::CGUIControllerWindow::DoProcess(), CGUIDialogSettingsBase::DoProcess(), CGUIMediaWindow::Filter(), CGUIDialogButtonMenu::FrameMove(), ADDON::CGUIAddonWindow::GetAddonControl(), XBMCAddon::xbmcgui::Window::GetControlById(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), CInputManager::HandleKey(), CGUIDialogBoxBase::OnInitWindow(), CGUIMediaWindow::OnMessage(), CGUIDialogProgress::OnWindowLoaded(), CGUIWindowMusicNav::OnWindowLoaded(), CGUIWindowDebugInfo::Process(), CGUIWindowSlideShow::RenderErrorMessage(), CGUIListGroup::SelectItemFromPoint(), CGUIDialogSettingsBase::SetupControls(), and CGUIListGroup::UpdateInfo().
GetDescription()
virtual std::string CGUIControl::GetDescription (void) const inline virtual
Reimplemented in CGUIBaseContainer, CGUIButtonControl, CGUIColorButtonControl, CGUIFadeLabelControl, CGUIImage, CGUILabelControl, CGUIMultiImage, CGUIProgressControl, CGUIRadioButtonControl, GUIScrollBarControl, CGUISettingsSliderControl, CGUISliderControl, CGUISpinControl, CGUISpinControlEx, CGUITextBox, CGUIToggleButtonControl, and PVR::CGUIEPGGridContainer.
Referenced by CGUIControlProfilerItem::CGUIControlProfilerItem(), CGUIDialogButtonMenu::FrameMove(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), CGUIDialogKeyboardGeneric::OnClickButton(), and CGUIDialogNumeric::OnInitWindow().
GetDescriptionByIndex()
virtual std::string CGUIControl::GetDescriptionByIndex (int index) const inline virtual
Reimplemented in CGUIEditControl.
Referenced by KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel().
GetHeight()
float CGUIControl::GetHeight () const virtual
Reimplemented in CGUIDialogContextMenu, CGUIControlGroupList, CGUISettingsSliderControl, CGUISpinControlEx, and CGUITextBox.
References m_height.
Referenced by Animate(), CalcRenderRegion(), CGUIWindow::CenterWindow(), CGUIListGroup::EnlargeHeight(), XBMCAddon::xbmcgui::Window::GetControlById(), CGUIDialogContextMenu::GetHeight(), CGUIControlGroupList::GetHeight(), CGUISettingsSliderControl::GetHeight(), CGUISpinControlEx::GetHeight(), CGUIRenderingControl::InitCallback(), CGUIVisualisationControl::InitVisualization(), CGUIWindow::LoadControl(), CGUIWindowSplash::OnInitWindow(), CGUIWindowSettingsScreenCalibration::OnMessage(), CGUIWindowFileManager::OnPopupMenu(), CGUIDialogContextMenu::OnWindowLoaded(), CGUIDialogKeyboardGeneric::OnWindowLoaded(), CGUIDialogContextMenu::PositionAtCurrentFocus(), KODI::RETRO::CGameWindowFullScreen::Process(), CGUIWindowFullScreen::Process(), CGUISettingsSliderControl::Process(), CGUISpinControlEx::Process(), CGUIWindowScreensaverDim::Process(), CGUIWindowSlideShow::Process(), CGUISettingsSliderControl::ProcessText(), CGUIWindowScreensaverDim::Render(), CGUIWindowSplash::Render(), CGUIWindowSlideShow::RenderErrorMessage(), CGUISpinControlEx::RenderText(), CGUIWindowSettingsScreenCalibration::ResetControls(), CGUIControlGroupList::Size(), GUIScrollBarControl::UpdateBarSize(), and CGUIWindowSettingsScreenCalibration::UpdateFromControl().
GetID()
int CGUIControl::GetID (void) const virtual
Reimplemented in CGUIWindowSettingsCategory.
References m_controlID.
Referenced by ADDON::Interface_GUIControlFadeLabel::add_label(), CGUIControlGroupList::AddControl(), CGUIControlLookup::AddLookup(), CGUIWindowMusicNav::AddSearchFolder(), CGUIWindowManager::AddUniqueInstance(), KODI::GAME::CDialogGameVolume::Announce(), CGUIWindowHome::Announce(), CGUIControlProfilerItem::CGUIControlProfilerItem(), CGUIMediaWindow::CGUIMediaWindow(), CGUISpinControl::ChangePage(), CGUIDialogVideoInfo::ClearCastList(), CGUIWindowFileManager::ClearFileItems(), CGUIWindowSettingsProfile::ClearListItems(), CGUIWindowMusicPlaylistEditor::ClearPlaylist(), CGUIDialogSubtitles::ClearServices(), CGUIDialogSubtitles::ClearSubtitles(), CGUIWindow::Close_Internal(), CGUIWindow::ControlGroupHasFocus(), ADDON::Interface_GUIWindow::destroy(), ADDON::Interface_GUIWindow::do_modal(), CGUIDialogSettingsBase::DoProcess(), KODI::GAME::CGUIFeatureButton::DoPrompt(), PVR::CPVRGUIActionsEPG::EditSavedSearch(), CGUIListGroup::EnlargeHeight(), CGUIListGroup::EnlargeWidth(), PVR::CPVRGUIActionsEPG::ExecuteSavedSearch(), CGUIDialogSubtitles::FillServices(), CGUIMediaWindow::Filter(), PVR::CPVRGUIActionsEPG::FindSimilar(), CGUIMediaWindow::FormatAndSort(), CGUIWindowFullScreen::FrameMove(), ADDON::Interface_GUIControlFadeLabel::get_label(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), XBMCAddon::xbmcgui::Window::GetControlById(), CGUIWindowMusicPlaylistEditor::GetCurrentPlaylistItem(), CGUIMediaWindow::GetDirectory(), CGUIWindowMusicBase::GetDirectory(), PVR::CGUIWindowPVRGuideBase::GetDirectory(), PVR::CGUIDialogPVRGuideSearch::GetEditValue(), CGUIControlGroup::GetFirstFocusableControl(), CGUIControlGroup::GetFocusedControlID(), KODI::RETRO::CGameWindowFullScreenText::GetID(), CGUIWindowSettingsCategory::GetID(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), CGUIViewControl::GetNextViewMode(), PVR::CGUIPVRChannelGroupsSelector::GetSelectedChannelGroup(), CGUIDialogMediaSource::GetSelectedItem(), CGUIDialogSmartPlaylistEditor::GetSelectedItem(), CGUIWindowSettingsProfile::GetSelectedItem(), CGUIViewControl::GetSelectedItem(), CGUIWindowFileManager::GetSelectedItem(), PVR::CGUIDialogPVRGuideSearch::GetSpinValue(), CGUIViewControl::GetView(), CGUIViewControl::GetViewModeByID(), CGUIViewControl::GetViewModeNumber(), CGUIDialogKeyboardGeneric::GetWindowId(), CGUIDialogKeyboardTouch::GetWindowId(), KODI::GAME::CDialogGameSaves::HandleCaption(), KODI::GAME::CDialogGameSaves::HandleGameClient(), PVR::CGUIEPGGridContainer::HandleProgrammeGrid(), CGUIDialogMediaSource::HighlightItem(), CGUIDialogSmartPlaylistEditor::HighlightItem(), CGUIWindow::Initialize(), PVR::CGUIPVRChannelGroupsSelector::Initialize(), CGUIWindow::IsActive(), PVR::CGUIDialogPVRGuideSearch::IsRadioSelected(), CGUIControlLookup::IsValidControl(), CGUIWindow::Load(), CGUIMediaWindow::Load(), CGUIWindow::LoadControl(), CGUIWindowSettingsProfile::LoadList(), CGUIWindowMusicBase::LoadPlayList(), GUIScrollBarControl::Move(), CGUISpinControl::MoveDown(), CGUIControlGroupList::MoveTo(), CGUISpinControl::MoveUp(), Navigate(), KODI::GAME::CGUIAgentControllerList::Notify(), KODI::GAME::CGUIActivePortList::Notify(), PVR::CGUIDialogPVRChannelsOSD::Notify(), PVR::CGUIWindowPVRBase::NotifyEvent(), CGUIDialogKeyboardGeneric::OnAction(), CGUIEditControl::OnAction(), CGUIMoverControl::OnAction(), CGUIResizeControl::OnAction(), CGUISpinControl::OnAction(), CGUIWindow::OnAction(), CGUIMediaWindow::OnAction(), CGUIMediaWindow::OnCacheFileItems(), CGUIButtonControl::OnClick(), CGUIBaseContainer::OnClick(), PVR::CGUIEPGGridContainer::OnClick(), CGUIMediaWindow::OnClick(), PVR::CGUIDialogPVRChannelManager::OnClickButtonEditName(), PVR::CGUIDialogPVRChannelManager::OnClickButtonRadioActive(), PVR::CGUIDialogPVRChannelManager::OnClickButtonRadioParentalLocked(), PVR::CGUIDialogPVRChannelManager::OnClickButtonUseEPG(), CGUIWindowMusicBase::OnContextButton(), CGUIWindowVideoNav::OnContextButton(), KODI::GAME::CGUIPortList::OnControllerSelected(), XBMCAddon::xbmcgui::Window::OnDeinitWindow(), CGUIDialogMediaSource::OnDeinitWindow(), CGUIDialogTextViewer::OnDeinitWindow(), CGUIDialog::OnDeinitWindow(), CGUIDialogNetworkSetup::OnDeinitWindow(), CGUIDialogPictureInfo::OnDeinitWindow(), CGUIWindowMusicPlaylistEditor::OnDeletePlaylistItem(), KODI::GAME::CDialogGameVideoSelect::OnDescriptionChange(), CGUIBaseContainer::OnDown(), CGUIPanelContainer::OnDown(), PVR::CGUIEPGGridContainer::OnDown(), CGUIWindow::OnEditChanged(), KODI::GAME::CGUIAgentControllerList::OnEvent(), KODI::GAME::CGUIControllerList::OnEvent(), KODI::GAME::CGUIActivePortList::OnEvent(), KODI::GAME::CGUIPortList::OnEvent(), CGUIWindowFavourites::OnFavouritesEvent(), CGUIBaseContainer::OnFocus(), CGUIButtonControl::OnFocus(), KODI::GAME::CGUIControllerList::OnFocus(), OnInfo(), CGUIWindow::OnInitWindow(), CGUIDialogKeyboardGeneric::OnInitWindow(), KODI::GAME::CGUIControllerWindow::OnInitWindow(), KODI::GAME::CDialogGameSaves::OnInitWindow(), KODI::GAME::CDialogGameVideoSelect::OnInitWindow(), KODI::GAME::CGUIPortWindow::OnInitWindow(), CGUIDialogVideoManager::OnInitWindow(), CGUIMediaWindow::OnInitWindow(), CGUIWindowFileManager::OnJobComplete(), CGUIBaseContainer::OnLeft(), CGUIPanelContainer::OnLeft(), PVR::CGUIEPGGridContainer::OnLeft(), OnMessage(), CGUIDialogAddonInfo::OnMessage(), ADDON::CGUIAddonWindow::OnMessage(), CGUIDialogFileBrowser::OnMessage(), CGUIDialogKeyboardGeneric::OnMessage(), CGUIDialogSeekBar::OnMessage(), KODI::GAME::CDialogGameVolume::OnMessage(), KODI::GAME::CDialogInGameSaves::OnMessage(), CGUIBaseContainer::OnMessage(), CGUIButtonControl::OnMessage(), CGUIControlGroup::OnMessage(), CGUIControlGroupList::OnMessage(), CGUIEditControl::OnMessage(), CGUIFadeLabelControl::OnMessage(), CGUILabelControl::OnMessage(), CGUIListContainer::OnMessage(), CGUIPanelContainer::OnMessage(), CGUISliderControl::OnMessage(), CGUISpinControl::OnMessage(), CGUITextBox::OnMessage(), CGUIWindow::OnMessage(), CGUIWrappingListContainer::OnMessage(), CGUIDialogMusicInfo::OnMessage(), CGUIDialogSongInfo::OnMessage(), CGUIWindowMusicNav::OnMessage(), CGUIWindowSettingsProfile::OnMessage(), PVR::CGUIEPGGridContainer::OnMessage(), CGUIDialogSettingsBase::OnMessage(), CGUIWindowSettingsCategory::OnMessage(), CGUIDialogSubtitles::OnMessage(), CGUIDialogVideoInfo::OnMessage(), CGUIWindowVideoBase::OnMessage(), CGUIWindowVideoNav::OnMessage(), CGUIWindowWeather::OnMessage(), CGUIMediaWindow::OnMessage(), CGUIWindowFileManager::OnMessage(), CGUIWindowHome::OnMessage(), CGUIWindowLoginScreen::OnMessage(), CGUIBaseContainer::OnMouseEvent(), CGUIControlGroupList::OnMouseEvent(), CGUIMoverControl::OnMouseEvent(), CGUIResizeControl::OnMouseEvent(), GUIScrollBarControl::OnMouseEvent(), CGUISliderControl::OnMouseEvent(), CGUIVideoControl::OnMouseEvent(), PVR::CGUIEPGGridContainer::OnMouseEvent(), OnMouseOver(), CGUIWindow::OnMove(), CGUIWindowMusicPlaylistEditor::OnMovePlaylistItem(), CGUIWindowSettingsProfile::OnPopupMenu(), CGUIWindowFileManager::OnPopupMenu(), CGUIDialogNetworkSetup::OnProtocolChange(), CGUIWindowVideoBase::OnQueueItem(), CGUIWindowMusicBase::OnQueueItem(), CGUIWindowMusicBase::OnRemoveSource(), CGUIDialogKeyboardGeneric::OnReveal(), CGUIBaseContainer::OnRight(), CGUIPanelContainer::OnRight(), PVR::CGUIEPGGridContainer::OnRight(), CGUIWindowFavourites::OnSelect(), CGUIDialogMediaFilter::OnSettingChanged(), CGUIWindowPictures::OnSlideShow(), CGUIWindowPictures::OnSlideShowRecursive(), CGUIDialogAddonInfo::OnToggleAutoUpdates(), CGUIBaseContainer::OnUnFocus(), CGUIButtonControl::OnUnFocus(), CGUIBaseContainer::OnUp(), CGUIPanelContainer::OnUp(), PVR::CGUIEPGGridContainer::OnUp(), CGUIDialogKeyboardGeneric::OnVoiceRecognition(), CGUIDialogColorPicker::OnWindowLoaded(), CGUIDialogFileBrowser::OnWindowLoaded(), CGUIDialogKeyboardGeneric::OnWindowLoaded(), CGUIDialogSelect::OnWindowLoaded(), KODI::GAME::CGUIAgentControllerList::OnWindowLoaded(), KODI::GAME::CDialogGameSaves::OnWindowLoaded(), KODI::GAME::CDialogGameVideoSelect::OnWindowLoaded(), KODI::GAME::CGUIPortList::OnWindowLoaded(), PVR::CGUIDialogPVRChannelManager::OnWindowLoaded(), PVR::CGUIDialogPVRGroupManager::OnWindowLoaded(), PVR::CGUIDialogPVRItemsViewBase::OnWindowLoaded(), CGUIDialogVideoBookmarks::OnWindowLoaded(), CGUIWindowLoginScreen::OnWindowLoaded(), CGUISpinControl::PageDown(), CGUISpinControl::PageUp(), PVR::CPVRRefreshTimelineItemsThread::Process(), CGUIRSSControl::Process(), CGUITextBox::Process(), PVR::CGUIEPGGridContainer::Process(), CGUIDialogSubtitles::Process(), CGUIWindowDebugInfo::Process(), CGUIDialogVideoManager::Refresh(), KODI::GAME::CGUIActivePortList::Refresh(), CGUIMediaWindow::Refresh(), KODI::GAME::CGUIControllerList::Refresh(), KODI::GAME::CDialogGameVideoSelect::RefreshList(), CGUIControlLookup::RemoveLookup(), ADDON::Interface_GUIControlFadeLabel::reset(), ADDON::Interface_GUIControlSettingsSlider::reset(), ADDON::Interface_GUIControlSlider::reset(), ADDON::Interface_GUIControlSpin::reset(), ADDON::Interface_GUIControlTextBox::reset(), KODI::GAME::CGUIPortList::ResetPorts(), CGUIWindow::RestoreControlStates(), CGUIWindow::RunLoadActions(), CGUIWindow::RunUnloadActions(), CGUIBaseContainer::SaveStates(), CGUIControlGroup::SaveStates(), CGUIControlGroupList::ScrollPages(), PVR::CGUIPVRChannelGroupsSelector::SelectChannelGroup(), CGUISliderControl::SendClick(), CGUIWindowManager::SendMessage(), CGUIWindow::SendMessage(), JSONRPC::CInputOperations::SendText(), ADDON::Interface_GUIControlLabel::set_label(), ADDON::Interface_GUIControlSettingsSlider::set_text(), ADDON::Interface_GUIControlSpin::set_text(), ADDON::Interface_GUIControlTextBox::set_text(), CGUIBaseContainer::SetContainerMoving(), CGUIDialogKeyboardGeneric::SetControlLabel(), CGUIViewControl::SetCurrentView(), PVR::CGUIDialogPVRChannelManager::SetData(), CGUIDialogKeyboardGeneric::SetEditText(), GUIScrollBarControl::SetFromPosition(), CGUIDialogTextViewer::SetHeading(), CGUIDialogNumeric::SetHeading(), CGUIBaseContainer::SetPageControlRange(), CGUIWrappingListContainer::SetPageControlRange(), CGUIDialogTextViewer::SetText(), CGUIDialogContextMenu::SetupButtons(), CGUIMediaWindow::SetupShares(), XBMCAddon::xbmcgui::Window::setWindow(), PVR::CGUIWindowPVRGuideBase::ShouldNavigateToGridContainer(), ADDON::Interface_GUIWindow::show(), ADDON::CGUIAddonWindowDialog::Show_Internal(), CGUIDialogFileBrowser::ShowAndGetFile(), CGUIDialogFileBrowser::ShowAndGetFile(), CGUIDialogFileBrowser::ShowAndGetFileList(), CGUIDialogFileBrowser::ShowAndGetImage(), CGUIDialogFileBrowser::ShowAndGetSource(), CGUIMediaWindow::SortItems(), CGUIDialogMediaFilter::TriggerFilter(), UnfocusFromPoint(), CGUIDialogMusicInfo::Update(), CGUIDialogSongInfo::Update(), PVR::CGUIDialogPVRGroupManager::Update(), PVR::CGUIDialogPVRGuideSearch::Update(), CGUIDialogVideoInfo::Update(), CGUIMediaWindow::Update(), CGUIDialogKeyboardGeneric::UpdateButtons(), CGUIDialogMediaSource::UpdateButtons(), CGUIDialogSmartPlaylistEditor::UpdateButtons(), CGUIMediaWindow::UpdateButtons(), CGUIWindowAddonBrowser::UpdateButtons(), CGUIWindowEventLog::UpdateButtons(), CGUIWindowMusicNav::UpdateButtons(), CGUIWindowPictures::UpdateButtons(), PVR::CGUIWindowPVRRecordingsBase::UpdateButtons(), PVR::CGUIWindowPVRTimersBase::UpdateButtons(), CGUIWindowVideoNav::UpdateButtons(), CGUIViewControl::UpdateContents(), CGUIWindowFileManager::UpdateControl(), CGUIDialogAddonInfo::UpdateControls(), CGUITextBox::UpdatePageControl(), CGUIBaseContainer::UpdatePageControl(), CGUIWrappingListContainer::UpdatePageControl(), PERIPHERALS::CGUIDialogPeripherals::UpdatePeripheralsAsync(), CGUIDialogPictureInfo::UpdatePictureInfo(), CGUIWindowMusicPlaylistEditor::UpdatePlaylist(), CGUIDialogVideoManager::UpdateSelectedAsset(), CGUIDialogSettingsBase::UpdateSettingControl(), CGUIEditControl::UpdateText(), CGUIDialogTextViewer::UseMonoFont(), and CGUIEditControl::ValidateInput().
GetParentControl()
CGUIControl * CGUIControl::GetParentControl (void) const inline
References m_parentControl.
Referenced by CGUIControlProfilerItem::FindOrAddControl(), CGUIWindow::OnAction(), CGUIDialogKeyboardGeneric::OnWindowLoaded(), and PVR::CGUIWindowPVRGuideBase::ShouldNavigateToGridContainer().
GetParentID()
int CGUIControl::GetParentID (void) const
References m_parentID.
Referenced by ADDON::Interface_GUIControlFadeLabel::add_label(), CGUIFadeLabelControl::AddLabel(), CGUISpinControl::ChangePage(), CGUIListItemLayout::CreateListControlLayouts(), ADDON::Interface_GUIControlFadeLabel::get_label(), PVR::CGUIEPGGridContainer::HandleProgrammeGrid(), CGUIBaseContainer::LoadLayout(), PVR::CGUIEPGGridContainer::LoadLayout(), CGUIBaseContainer::LoadListProvider(), GUIScrollBarControl::Move(), CGUISpinControl::MoveDown(), CGUISpinControl::MoveUp(), Navigate(), CGUIEditControl::OnAction(), CGUIMoverControl::OnAction(), CGUIResizeControl::OnAction(), CGUISpinControl::OnAction(), CGUIButtonControl::OnClick(), CGUIEditControl::OnClick(), CGUIBaseContainer::OnClick(), PVR::CGUIEPGGridContainer::OnClick(), CGUIBaseContainer::OnFocus(), CGUIButtonControl::OnFocus(), OnInfo(), OnMessage(), CGUIControlGroup::OnMessage(), CGUITextBox::OnMessage(), CGUIBaseContainer::OnMouseEvent(), CGUIControlGroupList::OnMouseEvent(), CGUIMoverControl::OnMouseEvent(), CGUIResizeControl::OnMouseEvent(), GUIScrollBarControl::OnMouseEvent(), CGUISliderControl::OnMouseEvent(), CGUIVideoControl::OnMouseEvent(), PVR::CGUIEPGGridContainer::OnMouseEvent(), OnMouseOver(), CGUIWindow::OnMove(), CGUIBaseContainer::OnUnFocus(), CGUIButtonControl::OnUnFocus(), CGUISpinControl::PageDown(), CGUISpinControl::PageUp(), CGUIControlGroupList::Process(), CGUIRSSControl::Process(), CGUIEditControl::ProcessText(), ADDON::Interface_GUIControlFadeLabel::reset(), ADDON::Interface_GUIControlSettingsSlider::reset(), ADDON::Interface_GUIControlSlider::reset(), ADDON::Interface_GUIControlSpin::reset(), ADDON::Interface_GUIControlTextBox::reset(), CGUIWindow::RunLoadActions(), CGUIWindow::RunUnloadActions(), CGUISliderControl::SendClick(), SendWindowMessage(), ADDON::Interface_GUIControlLabel::set_label(), ADDON::Interface_GUIControlSettingsSlider::set_text(), ADDON::Interface_GUIControlSpin::set_text(), ADDON::Interface_GUIControlTextBox::set_text(), CGUIBaseContainer::SetAutoScrolling(), CGUITextBox::SetAutoScrolling(), CGUITextBox::SetAutoScrolling(), SetEnableCondition(), CGUIImage::SetFileName(), GUIScrollBarControl::SetFromPosition(), CGUIButtonControl::SetLabel(), CGUILabelControl::SetLabel(), CGUIButtonControl::SetLabel2(), CGUIRadioButtonControl::SetToggleSelect(), CGUIToggleButtonControl::SetToggleSelect(), SetVisibleCondition(), KODI::GAME::CGUIGameControllerList::UpdateInfo(), and CGUIEditControl::UpdateText().
GetPosition()
virtual CPoint CGUIControl::GetPosition () const inline protected virtual
Return the coordinates of the top left of the control, in the control's parent coordinates.
Returns
The top left coordinates of the control
Reimplemented in CGUIWindow.
References GetXPosition(), and GetYPosition().
Referenced by CGUIWindow::GetPosition(), GetRenderPosition(), CGUIControlGroup::Process(), CGUIControlGroup::Render(), CGUIControlGroup::SendMouseEvent(), and CGUIControlGroup::UnfocusFromPoint().
GetRenderPosition()
CPoint CGUIControl::GetRenderPosition () const
References GetPosition(), GetRenderPosition(), m_parentControl, m_transform, TransformMatrix::TransformPosition(), CPointGen< T >::x, and CPointGen< T >::y.
Referenced by GetRenderPosition(), CGUIWindow::OnMouseAction(), and CGUIDialogContextMenu::PositionAtCurrentFocus().
GetRenderRegion()
const CRect & CGUIControl::GetRenderRegion () const inline
return the render region in screen coordinates of this control
References m_renderRegion.
Referenced by CGUIListGroup::Process(), KODI::RETRO::CGUIRenderControl::Render(), CGUIVideoControl::Render(), and CGUIWindowSlideShow::Render().
GetWidth()
float CGUIControl::GetWidth () const virtual
Reimplemented in CGUIDialogContextMenu, CGUIButtonControl, CGUIControlGroupList, CGUILabelControl, CGUISettingsSliderControl, CGUISpinControl, and CGUISpinControlEx.
References m_width.
Referenced by Animate(), CalcRenderRegion(), CGUIWindow::CenterWindow(), CGUIListGroup::EnlargeWidth(), XBMCAddon::xbmcgui::Window::GetControlById(), CGUIDialogContextMenu::GetWidth(), CGUIControlGroupList::GetWidth(), CGUIRenderingControl::InitCallback(), CGUIVisualisationControl::InitVisualization(), CGUIWindow::LoadControl(), CGUIWindowSplash::OnInitWindow(), CGUIWindowSettingsScreenCalibration::OnMessage(), CGUIWindowFileManager::OnPopupMenu(), CGUIDialogContextMenu::OnWindowLoaded(), CGUIDialog::OnWindowLoaded(), CGUIDialogContextMenu::PositionAtCurrentFocus(), KODI::RETRO::CGameWindowFullScreen::Process(), CGUIWindowFullScreen::Process(), CGUIRSSControl::Process(), CGUIWindowScreensaverDim::Process(), CGUIWindowSlideShow::Process(), CGUIWindowScreensaverDim::Render(), CGUIWindowSplash::Render(), CGUIWindowSlideShow::RenderErrorMessage(), CGUIWindowSettingsScreenCalibration::ResetControls(), CGUIControlGroupList::Size(), GUIScrollBarControl::UpdateBarSize(), and CGUIWindowSettingsScreenCalibration::UpdateFromControl().
GetXPosition()
float CGUIControl::GetXPosition () const virtual
Reimplemented in CGUISettingsSliderControl, and CGUISpinControlEx.
References m_posX.
Referenced by Animate(), CalcRenderRegion(), XBMCAddon::xbmcgui::Window::GetControlById(), GetPosition(), CGUISettingsSliderControl::GetXPosition(), CGUISpinControlEx::GetXPosition(), CGUIRenderingControl::InitCallback(), CGUIVisualisationControl::InitVisualization(), CGUIWindow::LoadControl(), CGUIWindow::OnMouseAction(), CGUIWindowFileManager::OnPopupMenu(), CGUIDialogKeyboardGeneric::OnWindowLoaded(), CGUIDialog::OnWindowLoaded(), CGUISettingsSliderControl::Process(), CGUISpinControlEx::Process(), CGUIWindowDebugInfo::Process(), CGUISettingsSliderControl::ProcessText(), CGUISpinControlEx::RenderText(), CGUIColorButtonControl::SetColorDimensions(), CGUIColorButtonControl::SetHeight(), CGUIRadioButtonControl::SetHeight(), CGUIMoverControl::SetLocation(), CGUIRadioButtonControl::SetRadioDimensions(), CGUISpinControlEx::SetSpinPosition(), CGUIDialogContextMenu::SetupButtons(), CGUIColorButtonControl::SetWidth(), CGUIRadioButtonControl::SetWidth(), CGUIControlGroupList::Size(), and GUIScrollBarControl::UpdateBarSize().
GetYPosition()
float CGUIControl::GetYPosition () const virtual
Reimplemented in CGUISettingsSliderControl, and CGUISpinControlEx.
References m_posY.
Referenced by Animate(), CalcRenderRegion(), XBMCAddon::xbmcgui::Window::GetControlById(), GetPosition(), CGUISettingsSliderControl::GetYPosition(), CGUISpinControlEx::GetYPosition(), CGUIRenderingControl::InitCallback(), CGUIVisualisationControl::InitVisualization(), CGUIWindow::LoadControl(), CGUIWindow::OnMouseAction(), CGUIWindowFileManager::OnPopupMenu(), CGUIDialogKeyboardGeneric::OnWindowLoaded(), CGUISettingsSliderControl::Process(), CGUISpinControlEx::Process(), CGUIWindowDebugInfo::Process(), CGUISettingsSliderControl::ProcessText(), CGUISpinControlEx::RenderText(), CGUIColorButtonControl::SetColorDimensions(), CGUIColorButtonControl::SetHeight(), CGUIRadioButtonControl::SetHeight(), CGUIMoverControl::SetLocation(), CGUIRadioButtonControl::SetRadioDimensions(), CGUISpinControlEx::SetSpinPosition(), CGUIDialogContextMenu::SetupButtons(), CGUIColorButtonControl::SetWidth(), CGUIRadioButtonControl::SetWidth(), CGUIControlGroupList::Size(), and GUIScrollBarControl::UpdateBarSize().
HasAnimation()
bool CGUIControl::HasAnimation (ANIMATION_TYPE anim) virtual
Reimplemented in CGUIControlGroup.
References GetAnimation().
Referenced by CGUIControlGroup::HasAnimation().
HasFocus()
bool CGUIControl::HasFocus (void) const virtual
Reimplemented in CGUIControlGroup.
References m_bHasFocus.
Referenced by KODI::GAME::CGUIControllerWindow::DoProcess(), CGUIDialogSettingsBase::DoProcess(), KODI::GAME::CGUIFeatureButton::DoPrompt(), KODI::GAME::CDialogGameSaves::FrameMove(), CGUIButtonControl::GetTextColor(), CGUISpinControl::GetTextColor(), CGUIColorButtonControl::GetTextColor(), PVR::CGUIPVRChannelGroupsSelector::HasFocus(), Navigate(), OnAction(), CGUIBaseContainer::OnAction(), CGUIWindow::OnAction(), CGUIEditControl::OnMessage(), OnMouseOver(), CGUIButtonControl::Process(), CGUIControlGroupList::Process(), CGUIMoverControl::Process(), CGUIResizeControl::Process(), CGUISettingsSliderControl::Process(), CGUISpinControl::Process(), CGUISpinControlEx::Process(), CGUIToggleButtonControl::Process(), PVR::CGUIEPGGridContainer::ProcessItem(), CGUIBaseContainer::ProcessItem(), CGUISettingsSliderControl::ProcessText(), CGUIButtonControl::ProcessText(), CGUIEditControl::ProcessText(), CGUIToggleButtonControl::ProcessToggle(), CGUIControlGroupList::Render(), CGUIRadioButtonControl::Render(), CGUISpinControl::Render(), CGUISpinControlEx::RenderText(), CGUIViewControl::SetCurrentView(), CGUIBaseContainer::SetFocus(), PVR::CGUIEPGGridContainer::SetFocus(), and UnfocusFromPoint().
HasProcessed()
bool CGUIControl::HasProcessed () const inline
Returns whether or not we have processed.
References m_hasProcessed.
Referenced by Animate(), CheckAnimation(), CGUIWindow::CheckAnimation(), CGUIDialogProgress::Open(), CGUIWindowSlideShow::Process(), CGUIImage::UpdateInfo(), and CGUIDialog::UpdateVisibility().
HasVisibleCondition()
bool CGUIControl::HasVisibleCondition () const inline
References m_visibleCondition.
Referenced by CGUIViewControl::UpdateViewVisibility().
HitTest()
bool CGUIControl::HitTest (const CPoint & point) const virtual
Used to test whether the point is inside a control.
Parameters
point location to test
Returns
true if the point is inside the bounds of this control.
See also
SetHitRect
Reimplemented in CGUISettingsSliderControl, CGUISliderControl, CGUISpinControl, and CGUISpinControlEx.
References m_hitRect, and CRectGen< T >::PtInRect().
Referenced by CanFocusFromPoint(), CGUIRenderingControl::CanFocusFromPoint(), CGUIVideoControl::CanFocusFromPoint(), CGUIVisualisationControl::CanFocusFromPoint(), CGUISettingsSliderControl::HitTest(), CGUISpinControl::HitTest(), CGUISpinControlEx::HitTest(), CGUIControlGroup::SendMouseEvent(), CGUIControlGroupList::SendMouseEvent(), and UnfocusFromPoint().
IsAnimating()
bool CGUIControl::IsAnimating (ANIMATION_TYPE anim) virtual
Reimplemented in CGUIControlGroup, and CGUIWindow.
References ANIM_PROCESS_NORMAL, ANIM_PROCESS_REVERSE, CAnimation::GetProcess(), CAnimation::GetQueuedProcess(), CAnimation::GetType(), and m_animations.
Referenced by CheckAnimation(), CGUIControlGroup::IsAnimating(), SetVisible(), and CGUIImage::UpdateInfo().
IsContainer()
virtual bool CGUIControl::IsContainer () const inline virtual
Reimplemented in IGUIContainer.
Referenced by CGUIViewControl::AddView(), KODI::GUILIB::GUIINFO::GetActiveContainer(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetLabel(), CInputManager::HandleKey(), PVR::CGUIPVRChannelGroupsSelector::Initialize(), CGUIMediaWindow::Load(), ADDON::CGUIAddonWindow::OnMessage(), and XBMCAddon::xbmcgui::WindowXML::OnMessage().
IsControlDirty()
bool CGUIControl::IsControlDirty () const inline
References m_controlDirtyState.
Referenced by CGUIWindowManager::AfterRender(), and CGUIWindow::DoProcess().
IsControlRenderable()
bool CGUIControl::IsControlRenderable ()
Test whether the control is "drawable" (not a group or similar)
Returns
true if the control has textures/labels it wants to render
References ControlType, GUICONTAINER_EPGGRID, GUICONTAINER_FIXEDLIST, GUICONTAINER_LIST, GUICONTAINER_PANEL, GUICONTAINER_WRAPLIST, GUICONTROL_GROUP, GUICONTROL_GROUPLIST, and GUICONTROL_LISTGROUP.
Referenced by DoRender().
IsDisabled()
bool CGUIControl::IsDisabled () const virtual
References m_enabled.
Referenced by CanFocus(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), CGUIButtonControl::GetTextColor(), CGUISpinControl::GetTextColor(), CGUIColorButtonControl::GetTextColor(), CGUILabelControl::Process(), CGUIProgressControl::Process(), CGUISliderControl::Process(), CGUIToggleButtonControl::Process(), CGUIRangesControl::Process(), CGUISettingsSliderControl::ProcessText(), CGUIColorButtonControl::Render(), CGUIProgressControl::Render(), CGUIRadioButtonControl::Render(), CGUIRangesControl::Render(), CGUISliderControl::Render(), CGUISpinControl::Render(), CGUIControlSpinExSetting::Update(), CGUIControlListSetting::Update(), CGUIProgressControl::UpdateInfo(), and CGUIRangesControl::UpdateInfo().
IsDynamicallyAllocated()
virtual bool CGUIControl::IsDynamicallyAllocated () inline virtual
Reimplemented in CGUIImage, and CGUIMultiImage.
IsGroup()
virtual bool CGUIControl::IsGroup () const inline virtual
Reimplemented in CGUIControlGroup.
Referenced by CGUIListItemLayout::LoadControl(), and CGUIWindow::LoadControl().
IsVisible()
bool CGUIControl::IsVisible () const virtual
Reimplemented in GUIScrollBarControl, CGUISpinControl, and CGUIWindow.
References m_forceHidden, m_visible, and VISIBLE.
Referenced by CGUIImage::AllocateOnDemand(), CanFocus(), CGUIRenderingControl::CanFocusFromPoint(), CGUIVideoControl::CanFocusFromPoint(), CGUIVisualisationControl::CanFocusFromPoint(), CheckAnimation(), DoProcess(), CGUIBaseContainer::DoProcess(), CGUITextBox::DoProcess(), DoRender(), KODI::GUILIB::GUIINFO::CGUIControlsGUIInfo::GetBool(), CGUIControlLookup::GetControl(), CGUIControlGroupList::GetTotalSize(), CGUIControlGroup::HasAnimation(), CGUIControlGroup::IsAnimating(), GUIScrollBarControl::IsVisible(), CGUISpinControl::IsVisible(), XBMCAddon::xbmcgui::Control::isVisible(), KODI::GAME::CDialogGameOSDHelp::IsVisible(), CGUIBaseContainer::OnMessage(), CGUIControlGroup::OnMessage(), CGUIControlGroupList::OnMessage(), CGUILabelControl::OnMessage(), CGUIWrappingListContainer::OnMessage(), PVR::CGUIEPGGridContainer::OnMessage(), CGUIControlGroupList::OnMouseEvent(), CGUIControlGroupList::Process(), CGUIListGroup::Process(), CGUIToggleButtonControl::Process(), CGUIControlGroupList::Render(), CGUIImage::Render(), CGUIControlGroupList::SendMouseEvent(), CGUIControlGroupList::UnfocusFromPoint(), UpdateControlStats(), CGUIBaseContainer::UpdateVisibility(), CGUIMultiImage::UpdateVisibility(), CGUIRenderingControl::UpdateVisibility(), CGUITextBox::UpdateVisibility(), and CGUIVisualisationControl::UpdateVisibility().
IsVisibleFromSkin()
bool CGUIControl::IsVisibleFromSkin () const inline
References m_visibleFromSkinCondition.
Referenced by CGUIControlGroup::OnMessage(), UpdateControlStats(), CGUIImage::UpdateInfo(), and CGUIViewControl::UpdateViewVisibility().
MarkDirtyRegion()
void CGUIControl::MarkDirtyRegion (const unsigned int dirtyState = DIRTY_STATE_CONTROL)
References DIRTY_STATE_CHILD, DIRTY_STATE_CONTROL, m_controlDirtyState, m_isCulled, m_parentControl, and MarkDirtyRegion().
Referenced by CGUIWindowManager::AfterRender(), DoProcess(), CGUIWindowSettingsScreenCalibration::DoProcess(), ADDON::Interface_GUIWindow::mark_dirty_region(), CGUIWindowManager::MarkDirty(), MarkDirtyRegion(), CGUIDialogVolumeBar::OnAction(), CGUIRadioButtonControl::OnAction(), CGUIWindowSlideShow::OnAction(), CGUIDialogTeletext::OnAction(), CGUIDialogTeletext::OnBack(), CGUISpinControl::OnLeft(), CGUIWindowSlideShow::OnLoadPic(), CGUIWindow::OnMessage(), CGUIWindowDebugInfo::OnMessage(), CGUISpinControl::OnMouseOver(), CGUISpinControl::OnRight(), CGUIDialogSubtitles::OnSearchComplete(), KODI::RETRO::CGameWindowFullScreen::Process(), CGUIWindowFullScreen::Process(), KODI::RETRO::CGUIGameControl::Process(), CGUIBaseContainer::Process(), CGUIBorderedImage::Process(), CGUIButtonControl::Process(), CGUIControlGroupList::Process(), CGUIFadeLabelControl::Process(), CGUILabelControl::Process(), CGUIListLabel::Process(), CGUIMoverControl::Process(), CGUIMultiImage::Process(), CGUIProgressControl::Process(), CGUIRadioButtonControl::Process(), CGUIRenderingControl::Process(), CGUIResizeControl::Process(), CGUIRSSControl::Process(), GUIScrollBarControl::Process(), CGUISliderControl::Process(), CGUISpinControl::Process(), CGUITextBox::Process(), CGUIVideoControl::Process(), CGUIVisualisationControl::Process(), CGUIDialogTeletext::Process(), CGUIWindowDebugInfo::Process(), CGUIWindowPointer::Process(), CGUIWindowSlideShow::Process(), CGUIWindowScreensaver::Process(), CGUIRangesControl::Process(), CGUIImage::ProcessFadingTransition(), CGUIColorButtonControl::ProcessInfoText(), CGUIImage::ProcessInstantTransition(), CGUIImage::ProcessNoTransition(), CGUISettingsSliderControl::ProcessText(), CGUIButtonControl::ProcessText(), CGUIEditControl::ProcessText(), CGUIToggleButtonControl::ProcessToggle(), QueueAnimation(), CGUIDialogTeletext::Render(), ResetAnimation(), ResetAnimations(), CGUIControlGroupList::ScrollTo(), PVR::CGUIEPGGridContainer::ScrollToBlockOffset(), PVR::CGUIEPGGridContainer::ScrollToChannelOffset(), CGUIFixedListContainer::SelectItem(), CGUIFixedListContainer::SelectItemFromPoint(), CGUILabelControl::SetAlignment(), CGUIButtonControl::SetAlpha(), SetAnimations(), PVR::CGUIEPGGridContainer::SetBlock(), PVR::CGUIEPGGridContainer::SetChannel(), CGUIDialogTeletext::SetCoordinates(), CGUIBaseContainer::SetCursor(), CGUILabelControl::SetCursorPos(), SetHeight(), SetInitialVisibility(), CGUIButtonControl::SetMinWidth(), CGUIBaseContainer::SetOffset(), CGUISliderControl::SetPercentage(), CGUIDialogProgress::SetPercentage(), SetPosition(), CGUISpinControl::SetValue(), CGUISpinControl::SetValueFromLabel(), SetVisible(), SetWidth(), CGUILabelControl::SetWidthControl(), CGUILabelControl::ShortenPath(), CGUIWindowFullScreen::ToggleOSD(), CGUIImage::UpdateDiffuseColor(), CGUILabelControl::UpdateInfo(), CGUIBaseContainer::UpdateLayout(), CGUIBaseContainer::UpdateScrollOffset(), PVR::CGUIEPGGridContainer::UpdateScrollOffset(), and UpdateVisibility().
Navigate()
bool CGUIControl::Navigate (int direction) const
Start navigating in given direction.
References GetID(), GetParentID(), GUI_MSG_MOVE, HasFocus(), and SendWindowMessage().
Referenced by OnBack(), OnDown(), OnLeft(), OnNextControl(), OnPrevControl(), OnRight(), and OnUp().
OnAction()
bool CGUIControl::OnAction (const CAction & action) virtual
Reimplemented in CGUIDialogAddonInfo, CGUIDialogAddonSettings, ADDON::CGUIAddonWindow, KODI::RETRO::CGameWindowFullScreen, CGUIDialogContextMenu, CGUIDialogFileBrowser, CGUIDialogGamepad, CGUIDialogKeyboardGeneric, CGUIDialogNumeric, CGUIDialogPlayerProcessInfo, CGUIDialogSlider, CGUIDialogTextViewer, CGUIDialogVolumeBar, CGUIWindowFavourites, KODI::GAME::CDialogGameOSD, CGUIBaseContainer, CGUIButtonControl, CGUIColorButtonControl, CGUIControlGroup, CGUIControlGroupList, CGUIDialog, CGUIEditControl, CGUIFixedListContainer, CGUIImage, CGUIListContainer, CGUIMoverControl, CGUIMultiImage, CGUIPanelContainer, CGUIRadioButtonControl, CGUIResizeControl, GUIScrollBarControl, CGUISettingsSliderControl, CGUISliderControl, CGUISpinControl, CGUIToggleButtonControl, CGUIVisualisationControl, CGUIWindow, CGUIWrappingListContainer, XBMCAddon::xbmcgui::Interceptor< CGUIMediaWindow >, CGUIDialogMusicInfo, CGUIDialogMusicOSD, CGUIDialogSongInfo, CGUIWindowMusicBase, CGUIWindowMusicNav, CGUIWindowMusicPlayList, CGUIWindowMusicPlaylistEditor, CGUIWindowVisualisation, CGUIDialogPictureInfo, CGUIWindowSlideShow, PVR::CGUIDialogPVRChannelManager, PVR::CGUIDialogPVRChannelsOSD, PVR::CGUIDialogPVRGroupManager, PVR::CGUIDialogPVRItemsViewBase, PVR::CGUIEPGGridContainer, PVR::CGUIWindowPVRBase, PVR::CGUIWindowPVRChannelsBase, PVR::CGUIWindowPVRGuideBase, PVR::CGUIWindowPVRProvidersBase, PVR::CGUIWindowPVRRecordingsBase, PVR::CGUIWindowPVRSearchBase, PVR::CGUIWindowPVRTimersBase, CGUIDialogSettingsBase, CGUIWindowSettingsCategory, CGUIWindowSettingsScreenCalibration, CGUIDialogFullScreenInfo, CGUIDialogTeletext, CGUIDialogVideoBookmarks, CGUIDialogVideoInfo, CGUIDialogVideoManager, CGUIDialogVideoOSD, CGUIWindowFullScreen, CGUIWindowVideoBase, CGUIWindowVideoNav, CGUIWindowVideoPlaylist, CGUIMediaWindow, CGUIWindowFileManager, CGUIWindowHome, CGUIWindowLoginScreen, CGUIWindowScreensaver, CGUIWindowSplash, and CGUIWindowStartup.
References ACTION_MOVE_DOWN, ACTION_MOVE_LEFT, ACTION_MOVE_RIGHT, ACTION_MOVE_UP, ACTION_NAV_BACK, ACTION_NEXT_CONTROL, ACTION_PREV_CONTROL, ACTION_SHOW_INFO, HasFocus(), OnBack(), OnDown(), OnInfo(), OnLeft(), OnNextControl(), OnPrevControl(), OnRight(), and OnUp().
Referenced by CGUIDialogKeyboardGeneric::Backspace(), CGUIDialogKeyboardGeneric::MoveCursor(), CGUIDialogKeyboardGeneric::NormalCharacter(), CGUIDialogAddonSettings::OnAction(), CGUIDialogKeyboardGeneric::OnAction(), CGUIBaseContainer::OnAction(), CGUIButtonControl::OnAction(), CGUIMoverControl::OnAction(), CGUIResizeControl::OnAction(), GUIScrollBarControl::OnAction(), CGUISliderControl::OnAction(), CGUISpinControl::OnAction(), CGUIVisualisationControl::OnAction(), CGUIWindow::OnAction(), CGUIWindowVisualisation::OnAction(), PVR::CGUIEPGGridContainer::OnAction(), and CGUIWindowSettingsCategory::OnAction().
OnBack()
bool CGUIControl::OnBack () virtual
References ACTION_NAV_BACK, and Navigate().
Referenced by OnAction(), CGUIWindow::OnAction(), CGUIDialogColorPicker::OnBack(), CGUIDialogFileBrowser::OnBack(), CGUIDialogMediaSource::OnBack(), CGUIDialogSelect::OnBack(), CGUIDialogSmartPlaylistEditor::OnBack(), CGUIDialogSmartPlaylistRule::OnBack(), CGUIDialogYesNo::OnBack(), XBMCAddon::xbmcgui::Interceptor< P >::OnBack(), CGUIDialogSongInfo::OnBack(), CGUIWindowMusicBase::OnBack(), CGUIWindowMusicPlayList::OnBack(), CGUIWindowMusicPlaylistEditor::OnBack(), CGUIDialogNetworkSetup::OnBack(), CGUIDialogSettingsBase::OnBack(), CGUIWindowSettingsCategory::OnBack(), CGUIDialogCMSSettings::OnBack(), CGUIWindowVideoPlaylist::OnBack(), CGUIMediaWindow::OnBack(), and CGUIWindowFileManager::OnBack().
OnDown()
void CGUIControl::OnDown () virtual
Reimplemented in CGUIBaseContainer, CGUIMoverControl, CGUIPanelContainer, CGUIResizeControl, and PVR::CGUIEPGGridContainer.
References ACTION_MOVE_DOWN, and Navigate().
Referenced by OnAction(), CGUIBaseContainer::OnDown(), CGUIPanelContainer::OnDown(), and PVR::CGUIEPGGridContainer::OnDown().
OnFocus()
virtual void CGUIControl::OnFocus () inline virtual
Reimplemented in KODI::GAME::CDialogGameSaves, CGUIBaseContainer, CGUIButtonControl, and CGUIRSSControl.
Referenced by CGUIBaseContainer::OnFocus(), and UpdateStates().
OnInfo()
bool CGUIControl::OnInfo () virtual
References ACTION_SHOW_INFO, GetAction(), GetID(), and GetParentID().
Referenced by OnAction(), CGUIBaseContainer::OnAction(), and CGUIWindow::OnAction().
OnLeft()
void CGUIControl::OnLeft () virtual
Reimplemented in CGUIBaseContainer, CGUIMoverControl, CGUIPanelContainer, CGUIResizeControl, CGUISpinControl, and PVR::CGUIEPGGridContainer.
References ACTION_MOVE_LEFT, and Navigate().
Referenced by OnAction(), CGUIBaseContainer::OnLeft(), CGUIPanelContainer::OnLeft(), CGUISpinControl::OnLeft(), and PVR::CGUIEPGGridContainer::OnLeft().
OnMessage()
bool CGUIControl::OnMessage (CGUIMessage & message) virtual
Reimplemented in CGUIDialogAddonInfo, CGUIDialogAddonSettings, CGUIWindowAddonBrowser, ADDON::CGUIAddonWindow, KODI::RETRO::CGameWindowFullScreen, CGUIDialogBoxBase, CGUIDialogButtonMenu, CGUIDialogColorPicker, CGUIDialogContextMenu, CGUIDialogExtendedProgressBar, CGUIDialogFileBrowser, CGUIDialogGamepad, CGUIDialogKaiToast, CGUIDialogKeyboardGeneric, CGUIDialogMediaFilter, CGUIDialogMediaSource, CGUIDialogNumeric, CGUIDialogOK, CGUIDialogPlayEject, CGUIDialogProgress, CGUIDialogSeekBar, CGUIDialogSelect, CGUIDialogSlider, CGUIDialogSmartPlaylistEditor, CGUIDialogSmartPlaylistRule, CGUIDialogSubMenu, CGUIDialogTextViewer, CGUIDialogVolumeBar, CGUIDialogYesNo, CGUIWindowEventLog, CGUIWindowFavourites, KODI::GAME::CGUIAgentWindow, KODI::GAME::CGUIControllerWindow, KODI::GAME::CDialogGameAdvancedSettings, KODI::GAME::CDialogGameSaves, KODI::GAME::CDialogGameVideoSelect, KODI::GAME::CDialogGameVolume, KODI::GAME::CDialogInGameSaves, KODI::GAME::CGUIPortWindow, KODI::GAME::CGUIWindowGames, CGUIBaseContainer, CGUIButtonControl, CGUIColorButtonControl, CGUIControlGroup, CGUIControlGroupList, CGUIDialog, CGUIEditControl, CGUIFadeLabelControl, CGUIImage, CGUILabelControl, CGUIListContainer, CGUIMultiImage, CGUIPanelContainer, CGUIProgressControl, CGUIRadioButtonControl, GUIScrollBarControl, CGUISliderControl, CGUISpinControl, CGUITextBox, CGUIVisualisationControl, CGUIWindow, CGUIWrappingListContainer, XBMCAddon::xbmcgui::Interceptor< CGUIMediaWindow >, CGUIDialogMusicInfo, CGUIDialogMusicOSD, CGUIDialogSongInfo, CGUIDialogVisualisationPresetList, CGUIWindowMusicBase, CGUIWindowMusicNav, CGUIWindowMusicPlayList, CGUIWindowMusicPlaylistEditor, CGUIWindowVisualisation, CGUIDialogNetworkSetup, PERIPHERALS::CGUIDialogPeripherals, PERIPHERALS::CGUIDialogPeripheralSettings, CGUIWindowPictures, CGUIWindowSlideShow, CGUIWindowSettingsProfile, CGUIWindowPrograms, PVR::CGUIDialogPVRChannelManager, PVR::CGUIDialogPVRChannelsOSD, PVR::CGUIDialogPVRGroupManager, PVR::CGUIDialogPVRGuideInfo, PVR::CGUIDialogPVRGuideSearch, PVR::CGUIDialogPVRRadioRDSInfo, PVR::CGUIDialogPVRRecordingInfo, PVR::CGUIEPGGridContainer, PVR::CGUIWindowPVRBase, PVR::CGUIWindowPVRChannelsBase, PVR::CGUIWindowPVRGuideBase, PVR::CGUIWindowPVRProvidersBase, PVR::CGUIWindowPVRRecordingsBase, PVR::CGUIWindowPVRSearchBase, PVR::CGUIWindowPVRTimersBase, CGUIDialogLibExportSettings, CGUIDialogSettingsBase, CGUIWindowSettingsCategory, CGUIWindowSettingsScreenCalibration, CGUIDialogSubtitles, CGUIDialogSubtitleSettings, CGUIDialogTeletext, CGUIDialogVideoBookmarks, CGUIDialogVideoInfo, CGUIDialogVideoManager, CGUIDialogVideoManagerExtras, CGUIDialogVideoManagerVersions, CGUIDialogVideoOSD, CGUIWindowFullScreen, CGUIWindowVideoBase, CGUIWindowVideoNav, CGUIWindowVideoPlaylist, CGUIWindowWeather, CGUIMediaWindow, CGUIWindowDebugInfo, CGUIWindowFileManager, CGUIWindowHome, CGUIWindowLoginScreen, CGUIWindowScreensaver, and CGUIWindowSystemInfo.
References CanFocus(), CGUIMessage::GetControlId(), GetID(), CGUIMessage::GetMessage(), GetParentID(), GUI_MSG_DISABLED, GUI_MSG_ENABLED, GUI_MSG_FOCUSED, GUI_MSG_HIDDEN, GUI_MSG_LOSTFOCUS, GUI_MSG_SETFOCUS, GUI_MSG_VISIBLE, GUI_MSG_WINDOW_RESIZE, CLog::Log(), LOGERROR, m_parentControl, OnMessage(), SetEnabled(), SetFocus(), SetInvalid(), and SetVisible().
Referenced by XBMCAddon::xbmcgui::ControlFadeLabel::Create(), XBMCAddon::xbmcgui::ControlTextBox::Create(), PVR::CGUIPVRChannelGroupsSelector::GetSelectedChannelGroup(), XBMCAddon::xbmcgui::ControlList::getSelectedItem(), XBMCAddon::xbmcgui::ControlList::getSelectedPosition(), PVR::CGUIPVRChannelGroupsSelector::Initialize(), CGUIControlGroupList::MoveTo(), OnMessage(), CGUIDialogAddonSettings::OnMessage(), CGUIDialogKeyboardGeneric::OnMessage(), CGUIDialogMediaFilter::OnMessage(), CGUIBaseContainer::OnMessage(), CGUIButtonControl::OnMessage(), CGUIControlGroup::OnMessage(), CGUIFadeLabelControl::OnMessage(), CGUIImage::OnMessage(), CGUILabelControl::OnMessage(), CGUIMultiImage::OnMessage(), CGUIProgressControl::OnMessage(), GUIScrollBarControl::OnMessage(), CGUISliderControl::OnMessage(), CGUISpinControl::OnMessage(), CGUITextBox::OnMessage(), CGUIVisualisationControl::OnMessage(), CGUIWindow::OnMessage(), CGUIWindowVisualisation::OnMessage(), CGUIDialogNetworkSetup::OnMessage(), PERIPHERALS::CGUIDialogPeripheralSettings::OnMessage(), PVR::CGUIDialogPVRChannelsOSD::OnMessage(), PVR::CGUIEPGGridContainer::OnMessage(), CGUIDialogLibExportSettings::OnMessage(), CGUIWindowSettingsCategory::OnMessage(), CGUIDialogSubtitleSettings::OnMessage(), OnMouseOver(), CGUIControlGroupList::ScrollPages(), PVR::CGUIPVRChannelGroupsSelector::SelectChannelGroup(), CGUIControlGroup::SendControlMessage(), CGUIViewControl::SetCurrentView(), and UnfocusFromPoint().
OnMouseEvent()
virtual EVENT_RESULT CGUIControl::OnMouseEvent (const CPoint & point, const KODI::MOUSE::CMouseEvent & event) inline virtual
Perform a mouse action.
Mouse actions are sent from the window to all controls, and each control can react based on the event and location of the actions.
Parameters
point the location in transformed skin coordinates from the upper left corner of the parent control.
event the mouse event to perform
Returns
EVENT_RESULT corresponding to whether the control handles this event
See also
SendMouseEvent, HitTest, CanFocusFromPoint, CMouseEvent
Reimplemented in CGUIBaseContainer, CGUIButtonControl, CGUIControlGroupList, CGUIMoverControl, CGUIResizeControl, GUIScrollBarControl, CGUISettingsSliderControl, CGUISliderControl, CGUISpinControl, CGUIVideoControl, CGUIWindow, CGUIWindowVisualisation, CGUIWindowSlideShow, PVR::CGUIEPGGridContainer, CGUIDialogVideoOSD, and CGUIWindowFullScreen.
References EVENT_RESULT_UNHANDLED.
Referenced by CGUIWindow::OnMouseAction(), CGUIDialogVideoOSD::OnMouseEvent(), SendMouseEvent(), and CGUIControlGroup::SendMouseEvent().
OnMouseOver()
bool CGUIControl::OnMouseOver (const CPoint & point) protected virtual
Called when the mouse is over the control. Default implementation selects the control.
Parameters
point location of the mouse in transformed skin coordinates
Returns
true if handled, false otherwise.
Reimplemented in CGUIBaseContainer, CGUISpinControl, and PVR::CGUIEPGGridContainer.
References CanFocus(), GetID(), CServiceBroker::GetInputManager(), GetParentID(), GUI_MSG_SETFOCUS, HasFocus(), MOUSE_STATE_DRAG, MOUSE_STATE_FOCUS, OnMessage(), and CInputManager::SetMouseState().
Referenced by CGUIBaseContainer::OnMouseOver(), CGUISpinControl::OnMouseOver(), PVR::CGUIEPGGridContainer::OnMouseOver(), and SendMouseEvent().
OnNextControl()
void CGUIControl::OnNextControl () virtual
References ACTION_NEXT_CONTROL, and Navigate().
Referenced by OnAction().
OnPrevControl()
void CGUIControl::OnPrevControl () virtual
References ACTION_PREV_CONTROL, and Navigate().
Referenced by OnAction().
OnRight()
void CGUIControl::OnRight () virtual
Reimplemented in CGUIBaseContainer, CGUIMoverControl, CGUIPanelContainer, CGUIResizeControl, CGUISpinControl, and PVR::CGUIEPGGridContainer.
References ACTION_MOVE_RIGHT, and Navigate().
Referenced by OnAction(), CGUIBaseContainer::OnRight(), CGUIPanelContainer::OnRight(), CGUISpinControl::OnRight(), and PVR::CGUIEPGGridContainer::OnRight().
OnUnFocus()
virtual void CGUIControl::OnUnFocus (void) inline virtual
Reimplemented in KODI::GAME::CGUIFeatureButton, CGUIBaseContainer, CGUIButtonControl, CGUIRSSControl, and CGUISettingsSliderControl.
Referenced by CGUIBaseContainer::OnUnFocus(), and UpdateStates().
OnUp()
void CGUIControl::OnUp () virtual
Reimplemented in CGUIBaseContainer, CGUIMoverControl, CGUIPanelContainer, CGUIResizeControl, and PVR::CGUIEPGGridContainer.
References ACTION_MOVE_UP, and Navigate().
Referenced by OnAction(), CGUIBaseContainer::OnUp(), CGUIPanelContainer::OnUp(), and PVR::CGUIEPGGridContainer::OnUp().
Process()
void CGUIControl::Process (unsigned int currentTime, CDirtyRegionList & dirtyregions) virtual
Reimplemented in KODI::RETRO::CGameWindowFullScreen, CGUIWindowFullScreen, KODI::RETRO::CGUIGameControl, CGUIDialogBoxBase, CGUIDialogExtendedProgressBar, CGUIDialogKeyboardTouch, CGUIDialogProgress, CGUIBaseContainer, CGUIBorderedImage, CGUIButtonControl, CGUIColorButtonControl, CGUIControlGroup, CGUIControlGroupList, CGUIFadeLabelControl, CGUIImage, CGUILabelControl, CGUIListGroup, CGUIListLabel, CGUIMoverControl, CGUIMultiImage, CGUIPanelContainer, CGUIProgressControl, CGUIRadioButtonControl, CGUIRenderingControl, CGUIResizeControl, CGUIRSSControl, GUIScrollBarControl, CGUISettingsSliderControl, CGUISliderControl, CGUISpinControl, CGUISpinControlEx, CGUITextBox, CGUIToggleButtonControl, CGUIVideoControl, CGUIVisualisationControl, PVR::CGUIEPGGridContainer, CGUIDialogSubtitles, CGUIDialogTeletext, CGUIWindowDebugInfo, CGUIWindowPointer, CGUIWindowScreensaverDim, CGUIWindowSlideShow, CGUIWindowScreensaver, and CGUIRangesControl.
References CalcRenderRegion(), CGraphicContext::GenerateAABB(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), m_hasProcessed, and m_renderRegion.
Referenced by DoProcess(), KODI::RETRO::CGameWindowFullScreen::Process(), CGUIWindowFullScreen::Process(), KODI::RETRO::CGUIGameControl::Process(), CGUIDialogBoxBase::Process(), CGUIDialogExtendedProgressBar::Process(), CGUIBaseContainer::Process(), CGUIButtonControl::Process(), CGUIControlGroup::Process(), CGUIControlGroupList::Process(), CGUIFadeLabelControl::Process(), CGUIImage::Process(), CGUILabelControl::Process(), CGUIListGroup::Process(), CGUIListLabel::Process(), CGUIMoverControl::Process(), CGUIMultiImage::Process(), CGUIPanelContainer::Process(), CGUIProgressControl::Process(), CGUIRenderingControl::Process(), CGUIResizeControl::Process(), CGUIRSSControl::Process(), GUIScrollBarControl::Process(), CGUISliderControl::Process(), CGUISpinControl::Process(), CGUITextBox::Process(), CGUIToggleButtonControl::Process(), CGUIVideoControl::Process(), CGUIVisualisationControl::Process(), XBMCAddon::xbmcgui::WindowXMLInterceptor::Process(), PVR::CGUIEPGGridContainer::Process(), CGUIDialogSubtitles::Process(), CGUIDialogTeletext::Process(), CGUIWindowPointer::Process(), CGUIWindowScreensaverDim::Process(), CGUIWindowSlideShow::Process(), CGUIWindowScreensaver::Process(), and CGUIRangesControl::Process().
QueueAnimation()
void CGUIControl::QueueAnimation (ANIMATION_TYPE anim) virtual
Reimplemented in CGUIControlGroup.
References ANIM_PROCESS_NORMAL, ANIM_PROCESS_REVERSE, ANIM_STATE_APPLIED, ANIM_STATE_DELAYED, ANIM_STATE_IN_PROCESS, CheckAnimation(), GetAnimation(), CAnimation::GetState(), CAnimation::IsReversible(), MarkDirtyRegion(), CAnimation::QueueAnimation(), CAnimation::ResetAnimation(), and UpdateStates().
Referenced by CGUIControlGroup::QueueAnimation(), SetFocus(), and UpdateVisibility().
Render()
virtual void CGUIControl::Render () inline virtual
Reimplemented in ADDON::CGUIAddonWindow, KODI::RETRO::CGUIGameControl, KODI::RETRO::CGameWindowFullScreen, CGUIDialogBusy, CGUIDialogBusyNoCancel, CGUIBaseContainer, CGUIBorderedImage, CGUIButtonControl, CGUIColorButtonControl, CGUIControlGroup, CGUIControlGroupList, CGUIDialog, CGUIFadeLabelControl, CGUIImage, CGUILabelControl, CGUIListLabel, CGUIMoverControl, CGUIMultiImage, CGUIPanelContainer, CGUIProgressControl, CGUIRadioButtonControl, CGUIRangesControl, CGUIRenderingControl, CGUIResizeControl, CGUIRSSControl, GUIScrollBarControl, CGUISettingsSliderControl, CGUISliderControl, CGUISpinControl, CGUISpinControlEx, CGUITextBox, CGUIToggleButtonControl, CGUIVideoControl, CGUIVisualisationControl, CGUIWindowSlideShow, PVR::CGUIEPGGridContainer, CGUIDialogTeletext, CGUIWindowFullScreen, CGUIWindowDebugInfo, CGUIWindowScreensaver, CGUIWindowScreensaverDim, and CGUIWindowSplash.
Referenced by DoRender(), ADDON::CGUIAddonWindow::Render(), KODI::RETRO::CGUIGameControl::Render(), KODI::RETRO::CGameWindowFullScreen::Render(), CGUIBaseContainer::Render(), CGUIButtonControl::Render(), CGUIControlGroup::Render(), CGUIControlGroupList::Render(), CGUIDialog::Render(), CGUIFadeLabelControl::Render(), CGUIImage::Render(), CGUILabelControl::Render(), CGUIListLabel::Render(), CGUIMoverControl::Render(), CGUIMultiImage::Render(), CGUIPanelContainer::Render(), CGUIProgressControl::Render(), CGUIRangesControl::Render(), CGUIRenderingControl::Render(), CGUIResizeControl::Render(), CGUIRSSControl::Render(), GUIScrollBarControl::Render(), CGUISliderControl::Render(), CGUISpinControl::Render(), CGUITextBox::Render(), CGUIToggleButtonControl::Render(), CGUIVideoControl::Render(), CGUIVisualisationControl::Render(), CGUIWindowSlideShow::Render(), PVR::CGUIEPGGridContainer::Render(), and CGUIWindowFullScreen::Render().
RenderEx()
virtual void CGUIControl::RenderEx () inline virtual
Reimplemented in KODI::RETRO::CGUIGameControl, KODI::RETRO::CGameWindowFullScreen, CGUIControlGroup, CGUIVideoControl, CGUIWindowSlideShow, and CGUIWindowFullScreen.
Referenced by KODI::RETRO::CGUIGameControl::RenderEx(), KODI::RETRO::CGameWindowFullScreen::RenderEx(), CGUIControlGroup::RenderEx(), CGUIVideoControl::RenderEx(), CGUIWindowSlideShow::RenderEx(), and CGUIWindowFullScreen::RenderEx().
ResetAnimation()
void CGUIControl::ResetAnimation (ANIMATION_TYPE type) virtual
Reimplemented in CGUIControlGroup, and CGUIListGroup.
References m_animations, and MarkDirtyRegion().
Referenced by CheckAnimation(), CGUIControlGroup::ResetAnimation(), CGUIListGroup::ResetAnimation(), and ResetAnimations().
ResetAnimations()
void CGUIControl::ResetAnimations () virtual
Reimplemented in CGUIControlGroup.
References m_animations, MarkDirtyRegion(), and ResetAnimation().
Referenced by CGUIControlGroup::ResetAnimations().
SaveStates()
void CGUIControl::SaveStates (std::vector< CControlState > & states) virtual
Reimplemented in CGUIBaseContainer, and CGUIControlGroup.
SendMouseEvent()
EVENT_RESULT CGUIControl::SendMouseEvent (const CPoint & point, const KODI::MOUSE::CMouseEvent & event) virtual
React to a mouse event.
Mouse events are sent from the window to all controls, and each control can react based on the event and location of the event.
Parameters
point the location in transformed skin coordinates from the upper left corner of the parent control.
event the mouse event to perform
Returns
EVENT_RESULT corresponding to whether the control handles this event
See also
HitTest, CanFocusFromPoint, CMouseEvent, EVENT_RESULT
Reimplemented in CGUIControlGroup, and CGUIControlGroupList.
References ACTION_MOUSE_MOVE, CanFocusFromPoint(), EVENT_RESULT_HANDLED, EVENT_RESULT_UNHANDLED, TransformMatrix::InverseTransformPosition(), KODI::MOUSE::CMouseEvent::m_id, m_transform, OnMouseEvent(), OnMouseOver(), CPointGen< T >::x, and CPointGen< T >::y.
Referenced by CGUIControlGroup::SendMouseEvent(), and CGUIControlGroupList::SendMouseEvent().
SendWindowMessage()
bool CGUIControl::SendWindowMessage (CGUIMessage & message) const protected
References CServiceBroker::GetGUI(), GetParentID(), CGUIComponent::GetWindowManager(), CGUIWindow::OnMessage(), and CGUIWindowManager::SendMessage().
Referenced by CGUISpinControl::ChangePage(), GUIScrollBarControl::Move(), CGUISpinControl::MoveDown(), CGUISpinControl::MoveUp(), Navigate(), CGUIMoverControl::OnAction(), CGUIResizeControl::OnAction(), CGUISpinControl::OnAction(), CGUIButtonControl::OnClick(), CGUIBaseContainer::OnClick(), PVR::CGUIEPGGridContainer::OnClick(), CGUIBaseContainer::OnMouseEvent(), CGUIControlGroupList::OnMouseEvent(), CGUIMoverControl::OnMouseEvent(), CGUIResizeControl::OnMouseEvent(), GUIScrollBarControl::OnMouseEvent(), CGUISliderControl::OnMouseEvent(), PVR::CGUIEPGGridContainer::OnMouseEvent(), CGUISpinControl::PageDown(), CGUISpinControl::PageUp(), CGUIControlGroupList::Process(), CGUITextBox::Process(), PVR::CGUIEPGGridContainer::Process(), GUIScrollBarControl::SetFromPosition(), CGUIBaseContainer::SetPageControlRange(), CGUIWrappingListContainer::SetPageControlRange(), CGUITextBox::UpdatePageControl(), CGUIBaseContainer::UpdatePageControl(), CGUIWrappingListContainer::UpdatePageControl(), and CGUIEditControl::ValidateInput().
SetAction()
void CGUIControl::SetAction (int actionID, const CGUIAction & action, bool replace = true)
Set actions to perform on navigation Navigations are set if replace is true or if there is no previously set action.
Parameters
actionID id of the navigation action
action CGUIAction to set
replace Actions are set only if replace is true or there is no previously set action. Defaults to true
See also
SetNavigationActions
References m_actions.
Referenced by CGUIControlGroupList::AddControl(), XBMCAddon::xbmcgui::Control::controlDown(), XBMCAddon::xbmcgui::Control::controlLeft(), XBMCAddon::xbmcgui::Control::controlRight(), XBMCAddon::xbmcgui::Control::controlUp(), XBMCAddon::xbmcgui::Window::doAddControl(), and XBMCAddon::xbmcgui::Control::setNavigation().
SetActions()
void CGUIControl::SetActions (const ActionMap & actions)
References actions, and m_actions.
Referenced by CGUIControlFactory::Create().
SetAnimations()
void CGUIControl::SetAnimations (const std::vector< CAnimation > & animations)
References m_animations, and MarkDirtyRegion().
Referenced by CGUIControlFactory::Create(), and XBMCAddon::xbmcgui::Control::setAnimations().
SetCamera()
void CGUIControl::SetCamera (const CPoint & camera) virtual
References m_camera, and m_hasCamera.
Referenced by CGUIControlFactory::Create().
SetColorDiffuse()
bool CGUIControl::SetColorDiffuse (const KODI::GUILIB::GUIINFO::CGUIInfoColor & color)
References color, and m_diffuseColor.
Referenced by CGUIControlFactory::Create(), CGUIMultiImage::Process(), ADDON::Interface_GUIControlImage::set_color_diffuse(), KODI::GAME::CGUIGameController::SetActivation(), CGUISettingsSliderControl::UpdateColors(), CGUISpinControlEx::UpdateColors(), and CGUIToggleButtonControl::UpdateColors().
SetControlStats()
void CGUIControl::SetControlStats (GUICONTROLSTATS * controlStats) inline
References m_controlStats.
Referenced by CGUIControlGroup::AddControl().
SetEnableCondition()
void CGUIControl::SetEnableCondition (const std::string & expression)
References CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), GetParentID(), m_enableCondition, m_enabled, and CGUIInfoManager::Register().
Referenced by CGUIControlFactory::Create(), and XBMCAddon::xbmcgui::Control::setEnableCondition().
SetEnabled()
void CGUIControl::SetEnabled (bool bEnable) virtual
Reimplemented in CGUISettingsSliderControl, and CGUISpinControlEx.
References m_enabled, and SetInvalid().
Referenced by OnMessage(), CGUISettingsSliderControl::Process(), CGUISpinControlEx::Process(), CGUIToggleButtonControl::Process(), CGUIWindowSettingsScreenCalibration::ResetControls(), ADDON::Interface_GUIControlButton::set_enabled(), ADDON::Interface_GUIControlEdit::set_enabled(), ADDON::Interface_GUIControlRadioButton::set_enabled(), ADDON::Interface_GUIControlSlider::set_enabled(), XBMCAddon::xbmcgui::Control::setEnabled(), CGUISettingsSliderControl::SetEnabled(), CGUISpinControlEx::SetEnabled(), CGUIControlBaseSetting::Update(), and CGUIControlListSetting::Update().
SetFocus()
void CGUIControl::SetFocus (bool focus) virtual
Reimplemented in CGUIBaseContainer, CGUIEditControl, CGUIListLabel, and PVR::CGUIEPGGridContainer.
References ANIM_TYPE_FOCUS, ANIM_TYPE_UNFOCUS, m_bHasFocus, and QueueAnimation().
Referenced by KODI::GAME::CGUIControllerWindow::DoProcess(), CGUIDialogSettingsBase::DoProcess(), CGUIWindowSettingsScreenCalibration::NextControl(), OnMessage(), CGUIControlGroup::OnMessage(), CGUISettingsSliderControl::Process(), CGUISpinControlEx::Process(), CGUIToggleButtonControl::Process(), CGUIBaseContainer::SetFocus(), CGUIEditControl::SetFocus(), CGUIListLabel::SetFocus(), PVR::CGUIEPGGridContainer::SetFocus(), CGUIListGroup::SetFocusedItem(), and UnfocusFromPoint().
SetHeight()
void CGUIControl::SetHeight (float height) virtual
Reimplemented in KODI::RETRO::CGUIGameControl, CGUIColorButtonControl, CGUIImage, CGUIRadioButtonControl, CGUISettingsSliderControl, CGUISpinControlEx, and CGUIToggleButtonControl.
References m_height, m_hitRect, MarkDirtyRegion(), SetInvalid(), CRectGen< T >::y1, and CRectGen< T >::y2.
Referenced by CGUIMoverControl::AllocResources(), CGUIListGroup::EnlargeHeight(), CGUIListItemLayout::LoadLayout(), CGUIWindowSettingsScreenCalibration::ResetControls(), CGUIResizeControl::Resize(), XBMCAddon::xbmcgui::Control::setHeight(), KODI::RETRO::CGUIGameControl::SetHeight(), CGUIColorButtonControl::SetHeight(), CGUIImage::SetHeight(), CGUIRadioButtonControl::SetHeight(), CGUISettingsSliderControl::SetHeight(), CGUISpinControlEx::SetHeight(), CGUIToggleButtonControl::SetHeight(), and CGUIDialogContextMenu::SetupButtons().
SetHitRect()
void CGUIControl::SetHitRect (const CRect & rect, const KODI::UTILS::COLOR::Color & color) virtual
References color, m_hitColor, and m_hitRect.
Referenced by CGUIControlFactory::Create(), and CGUIButtonControl::ProcessText().
SetID()
virtual void CGUIControl::SetID (int id) inline virtual
Reimplemented in CGUIWindow.
References id, and m_controlID.
Referenced by CGUIDialogSettingsBase::AddSettingControl(), CGUIControlButtonSetting::CGUIControlButtonSetting(), CGUIControlColorButtonSetting::CGUIControlColorButtonSetting(), CGUIControlEditSetting::CGUIControlEditSetting(), CGUIControlGroupTitleSetting::CGUIControlGroupTitleSetting(), CGUIControlLabelSetting::CGUIControlLabelSetting(), KODI::GAME::CGUIControllerButton::CGUIControllerButton(), CGUIControlListSetting::CGUIControlListSetting(), CGUIControlRadioButtonSetting::CGUIControlRadioButtonSetting(), CGUIControlRangeSetting::CGUIControlRangeSetting(), CGUIControlSeparatorSetting::CGUIControlSeparatorSetting(), CGUIControlSliderSetting::CGUIControlSliderSetting(), CGUIControlSpinExSetting::CGUIControlSpinExSetting(), KODI::GAME::CGUIFeatureButton::CGUIFeatureButton(), KODI::GAME::CGUIFeatureGroupTitle::CGUIFeatureGroupTitle(), KODI::GAME::CGUIFeatureSeparator::CGUIFeatureSeparator(), CGUIWindow::SetID(), CGUIDialogContextMenu::SetupButtons(), and CGUIDialogSettingsBase::SetupControls().
SetInitialVisibility()
void CGUIControl::SetInitialVisibility () virtual
Reimplemented in CGUIControlGroup, and CGUIWindow.
References ANIM_TYPE_CONDITIONAL, INFO::DEFAULT_CONTEXT, DELAYED, CAnimation::GetType(), HIDDEN, m_allowHiddenFocus, m_animations, m_enableCondition, m_enabled, m_visible, m_visibleCondition, m_visibleFromSkinCondition, MarkDirtyRegion(), CAnimation::SetInitialCondition(), KODI::GUILIB::GUIINFO::CGUIInfoBool::Update(), UpdateColors(), and VISIBLE.
Referenced by CGUIControlGroup::SetInitialVisibility().
SetInvalid()
virtual void CGUIControl::SetInvalid () inline virtual
Reimplemented in CGUIButtonControl, CGUIColorButtonControl, CGUIControlGroupList, CGUIImage, CGUIListGroup, CGUIListLabel, CGUIMoverControl, CGUIMultiImage, CGUIProgressControl, CGUIRadioButtonControl, CGUIRangesControl, CGUIResizeControl, GUIScrollBarControl, CGUISettingsSliderControl, CGUISliderControl, CGUISpinControl, CGUISpinControlEx, CGUIToggleButtonControl, PVR::CGUIDialogPVRChannelsOSD, PVR::CGUIWindowPVRBase, and PVR::CGUIWindowPVRGuideBase.
References m_bInvalidated.
Referenced by CGUIControlGroup::AddControl(), CGUIControlGroup::ClearAll(), OnMessage(), CGUIBaseContainer::OnMessage(), CGUITextBox::OnMessage(), CGUIDialogSubtitles::OnSearchComplete(), CGUIControlGroup::RemoveControl(), CGUIDialogProgress::Reset(), CGUIDialogProgress::SetCanCancel(), CGUIDialogBoxBase::SetChoice(), SetEnabled(), CGUIBaseContainer::SetFocus(), PVR::CGUIEPGGridContainer::SetFocus(), CGUIDialogBoxBase::SetHeading(), SetHeight(), CGUIButtonControl::SetInvalid(), CGUIControlGroupList::SetInvalid(), CGUIImage::SetInvalid(), CGUIListGroup::SetInvalid(), CGUIListLabel::SetInvalid(), CGUIMoverControl::SetInvalid(), CGUIMultiImage::SetInvalid(), CGUIProgressControl::SetInvalid(), CGUIRangesControl::SetInvalid(), CGUIResizeControl::SetInvalid(), GUIScrollBarControl::SetInvalid(), CGUISliderControl::SetInvalid(), CGUISpinControl::SetInvalid(), PVR::CGUIDialogPVRChannelsOSD::SetInvalid(), PVR::CGUIWindowPVRBase::SetInvalid(), PVR::CGUIWindowPVRGuideBase::SetInvalid(), CGUILabelControl::SetLabel(), CGUITextBox::SetMinHeight(), SetPosition(), CGUIDialogBoxBase::SetText(), SetVisible(), SetWidth(), CGUIDialogProgress::ShowChoice(), CGUIDialogProgress::ShowProgressBar(), CGUITextBox::UpdateInfo(), PVR::CGUIEPGGridContainer::UpdateItems(), CGUIBaseContainer::UpdateListProvider(), and CGUIDialogSubtitles::UpdateStatus().
SetParentControl()
void CGUIControl::SetParentControl (CGUIControl * control) inline
References m_parentControl.
Referenced by CGUIControlGroup::AddControl(), CGUIListItemLayout::CGUIListItemLayout(), and CGUIListItemLayout::SetParentControl().
SetPosition()
void CGUIControl::SetPosition (float posX, float posY) virtual
Reimplemented in CGUIRangesControl, KODI::RETRO::CGUIGameControl, CGUIDialogContextMenu, CGUIButtonControl, CGUIColorButtonControl, CGUIImage, CGUIMoverControl, CGUIProgressControl, CGUIRadioButtonControl, CGUIResizeControl, CGUISettingsSliderControl, CGUISpinControl, CGUISpinControlEx, and CGUIToggleButtonControl.
References m_hitRect, m_posX, m_posY, MarkDirtyRegion(), and SetInvalid().
Referenced by CGUIControlGroupList::AddControl(), CGUISettingsSliderControl::Process(), CGUIWindowPointer::Process(), XBMCAddon::xbmcgui::Control::setPosition(), CGUIRangesControl::SetPosition(), KODI::RETRO::CGUIGameControl::SetPosition(), CGUIDialogContextMenu::SetPosition(), CGUIButtonControl::SetPosition(), CGUIImage::SetPosition(), CGUIMoverControl::SetPosition(), CGUIProgressControl::SetPosition(), CGUIResizeControl::SetPosition(), CGUISpinControl::SetPosition(), and CGUIWindowSettingsScreenCalibration::UpdateFromControl().
SetPulseOnSelect()
virtual void CGUIControl::SetPulseOnSelect (bool pulse) inline virtual
References m_pulseOnSelect.
Referenced by CGUIControlFactory::Create(), CGUISettingsSliderControl::Process(), CGUISpinControlEx::Process(), and CGUIToggleButtonControl::Process().
SetPushUpdates()
virtual void CGUIControl::SetPushUpdates (bool pushUpdates) inline virtual
References m_pushedUpdates.
Referenced by CGUIControlGroup::AddControl(), and CGUIListItemLayout::CGUIListItemLayout().
SetStereoFactor()
void CGUIControl::SetStereoFactor (const float & factor) virtual
References m_stereo.
Referenced by CGUIControlFactory::Create().
SetVisible()
void CGUIControl::SetVisible (bool bVisible, bool setVisState = false) virtual
Todo:
currently we only update m_visible from GUI_MSG_VISIBLE (SET_CONTROL_VISIBLE) otherwise we just set m_forceHidden
References ANIM_TYPE_VISIBLE, INFO::DEFAULT_CONTEXT, GetAnimation(), HIDDEN, IsAnimating(), m_forceHidden, m_visible, m_visibleCondition, MarkDirtyRegion(), CAnimation::ResetAnimation(), SetInvalid(), and VISIBLE.
Referenced by CGUIDialogSettingsBase::AddSettingControl(), KODI::GAME::CGUIControllerButton::CGUIControllerButton(), KODI::GAME::CGUIFeatureButton::CGUIFeatureButton(), KODI::GAME::CGUIFeatureGroupTitle::CGUIFeatureGroupTitle(), KODI::GAME::CGUIFeatureSeparator::CGUIFeatureSeparator(), XBMCAddon::xbmcgui::ControlLabel::Create(), XBMCAddon::xbmcgui::ControlEdit::Create(), XBMCAddon::xbmcgui::ControlList::Create(), XBMCAddon::xbmcgui::ControlFadeLabel::Create(), XBMCAddon::xbmcgui::ControlTextBox::Create(), XBMCAddon::xbmcgui::ControlImage::Create(), XBMCAddon::xbmcgui::ControlProgress::Create(), XBMCAddon::xbmcgui::ControlButton::Create(), XBMCAddon::xbmcgui::ControlGroup::Create(), XBMCAddon::xbmcgui::ControlRadioButton::Create(), CGUIListGroup::EnlargeHeight(), CGUIListGroup::EnlargeWidth(), KODI::GAME::CGUIControllerList::Initialize(), KODI::GAME::CGUIFeatureList::Initialize(), CGUIWindowSettingsScreenCalibration::NextControl(), OnMessage(), CGUIWindowPointer::OnWindowLoaded(), CGUIToggleButtonControl::Process(), ADDON::Interface_GUIControlButton::set_visible(), ADDON::Interface_GUIControlEdit::set_visible(), ADDON::Interface_GUIControlFadeLabel::set_visible(), ADDON::Interface_GUIControlImage::set_visible(), ADDON::Interface_GUIControlLabel::set_visible(), ADDON::Interface_GUIControlProgress::set_visible(), ADDON::Interface_GUIControlRadioButton::set_visible(), ADDON::Interface_GUIControlSettingsSlider::set_visible(), ADDON::Interface_GUIControlSlider::set_visible(), ADDON::Interface_GUIControlSpin::set_visible(), ADDON::Interface_GUIControlTextBox::set_visible(), CGUIViewControl::SetCurrentView(), CGUIWindowPointer::SetPointer(), CGUIDialogContextMenu::SetupButtons(), CGUIDialogSettingsBase::SetupControls(), XBMCAddon::xbmcgui::Control::setVisible(), CGUIControlBaseSetting::Update(), PVR::CGUIWindowPVRChannelsBase::UpdateButtons(), and PVR::CGUIWindowPVRRecordingsBase::UpdateButtons().
SetVisibleCondition()
void CGUIControl::SetVisibleCondition (const std::string & expression, const std::string & allowHiddenFocus = "")
References CServiceBroker::GetGUI(), CGUIComponent::GetInfoManager(), GetParentID(), HIDDEN, m_allowHiddenFocus, m_visible, m_visibleCondition, KODI::GUILIB::GUIINFO::CGUIInfoBool::Parse(), CGUIInfoManager::Register(), and VISIBLE.
Referenced by CGUIControlFactory::Create(), CGUIListItemLayout::CreateListControlLayouts(), and XBMCAddon::xbmcgui::Control::setVisibleCondition().
SetWidth()
void CGUIControl::SetWidth (float width) virtual
Reimplemented in KODI::RETRO::CGUIGameControl, CGUIColorButtonControl, CGUIImage, CGUILabelControl, CGUIListLabel, CGUIRadioButtonControl, CGUISettingsSliderControl, CGUISpinControlEx, and CGUIToggleButtonControl.
References m_hitRect, m_width, MarkDirtyRegion(), SetInvalid(), CRectGen< T >::x1, and CRectGen< T >::x2.
Referenced by CGUIDialogSettingsBase::AddSettingControl(), CGUIMoverControl::AllocResources(), CGUIListGroup::EnlargeWidth(), CGUIListItemLayout::LoadLayout(), CGUIMoverControl::Process(), CGUIResizeControl::Process(), CGUIWindowSettingsScreenCalibration::ResetControls(), CGUIResizeControl::Resize(), CGUIDialogContextMenu::SetupButtons(), XBMCAddon::xbmcgui::Control::setWidth(), KODI::RETRO::CGUIGameControl::SetWidth(), CGUIColorButtonControl::SetWidth(), CGUIImage::SetWidth(), CGUILabelControl::SetWidth(), CGUIListLabel::SetWidth(), CGUIRadioButtonControl::SetWidth(), CGUISettingsSliderControl::SetWidth(), CGUISpinControlEx::SetWidth(), and CGUIToggleButtonControl::SetWidth().
UnfocusFromPoint()
void CGUIControl::UnfocusFromPoint (const CPoint & point) virtual
Unfocus the control if the given point on screen is not within it's boundary.
Parameters
point the location in transformed skin coordinates from the upper left corner of the parent control.
See also
CanFocusFromPoint
Reimplemented in CGUIControlGroup, and CGUIControlGroupList.
References GetID(), GUI_MSG_LOSTFOCUS, HasFocus(), HitTest(), TransformMatrix::InverseTransformPosition(), m_parentControl, m_transform, OnMessage(), SetFocus(), CPointGen< T >::x, and CPointGen< T >::y.
Referenced by CGUIControlGroup::UnfocusFromPoint(), and CGUIControlGroupList::UnfocusFromPoint().
UpdateColors()
bool CGUIControl::UpdateColors (const CGUIListItem * item) protected virtual
Reimplemented in CGUIButtonControl, CGUIColorButtonControl, CGUIFadeLabelControl, CGUILabelControl, CGUIListLabel, CGUIMoverControl, CGUIProgressControl, CGUIRadioButtonControl, CGUIRangesControl, CGUIResizeControl, CGUIRSSControl, GUIScrollBarControl, CGUISettingsSliderControl, CGUISliderControl, CGUISpinControl, CGUISpinControlEx, CGUITextBox, and CGUIToggleButtonControl.
References m_diffuseColor, and KODI::GUILIB::GUIINFO::CGUIInfoColor::Update().
Referenced by SetInitialVisibility(), CGUIButtonControl::UpdateColors(), CGUIFadeLabelControl::UpdateColors(), CGUILabelControl::UpdateColors(), CGUIListLabel::UpdateColors(), CGUIMoverControl::UpdateColors(), CGUIProgressControl::UpdateColors(), CGUIRangesControl::UpdateColors(), CGUIResizeControl::UpdateColors(), CGUIRSSControl::UpdateColors(), GUIScrollBarControl::UpdateColors(), CGUISliderControl::UpdateColors(), CGUISpinControl::UpdateColors(), CGUITextBox::UpdateColors(), and UpdateVisibility().
UpdateControlStats()
void CGUIControl::UpdateControlStats () virtual
Reimplemented in CGUIWindow.
References IsVisible(), IsVisibleFromSkin(), m_controlStats, GUICONTROLSTATS::nCountTotal, and GUICONTROLSTATS::nCountVisible.
Referenced by DoProcess().
UpdateInfo()
virtual void CGUIControl::UpdateInfo (const CGUIListItem * item = NULL) inline virtual
Reimplemented in KODI::GAME::CGUIGameControllerList, CGUIListGroup, CGUIImage, CGUILabelControl, CGUIListLabel, CGUIMultiImage, CGUIProgressControl, CGUITextBox, KODI::RETRO::CGUIGameControl, KODI::GAME::CGUIGameController, and CGUIRangesControl.
Referenced by KODI::GAME::CGUIGameControllerList::UpdateInfo(), and UpdateVisibility().
UpdateStates()
void CGUIControl::UpdateStates (ANIMATION_TYPE type, ANIMATION_PROCESS currentProcess, ANIMATION_STATE currentState) protected
References ANIM_PROCESS_NORMAL, ANIM_PROCESS_REVERSE, ANIM_STATE_APPLIED, ANIM_STATE_DELAYED, ANIM_TYPE_FOCUS, ANIM_TYPE_HIDDEN, ANIM_TYPE_UNFOCUS, ANIM_TYPE_VISIBLE, ANIM_TYPE_WINDOW_OPEN, DELAYED, HIDDEN, m_visible, m_visibleFromSkinCondition, OnFocus(), OnUnFocus(), and VISIBLE.
Referenced by Animate(), CheckAnimation(), and QueueAnimation().
UpdateVisibility()
void CGUIControl::UpdateVisibility (const CGUIListItem * item) virtual
Reimplemented in CGUIBaseContainer, CGUIImage, CGUIListGroup, CGUIMultiImage, CGUIRenderingControl, CGUITextBox, and CGUIVisualisationControl.
References ANIM_TYPE_CONDITIONAL, ANIM_TYPE_HIDDEN, ANIM_TYPE_VISIBLE, INFO::DEFAULT_CONTEXT, CAnimation::GetType(), m_allowHiddenFocus, m_animations, m_enableCondition, m_enabled, m_pushedUpdates, m_visibleCondition, m_visibleFromSkinCondition, MarkDirtyRegion(), QueueAnimation(), KODI::GUILIB::GUIINFO::CGUIInfoBool::Update(), UpdateColors(), CAnimation::UpdateCondition(), and UpdateInfo().
Referenced by CGUIWindow::CheckAnimation(), CGUIControlGroupList::Process(), CGUIListGroup::Process(), CGUIViewControl::UpdateViewVisibility(), CGUIBaseContainer::UpdateVisibility(), CGUIImage::UpdateVisibility(), CGUIListGroup::UpdateVisibility(), CGUIMultiImage::UpdateVisibility(), CGUIRenderingControl::UpdateVisibility(), CGUITextBox::UpdateVisibility(), and CGUIVisualisationControl::UpdateVisibility().
Member Data Documentation
ControlType
GUICONTROLTYPES CGUIControl::ControlType protected
Referenced by CGUIBorderedImage::CGUIBorderedImage(), CGUIBorderedImage::CGUIBorderedImage(), CGUIButtonControl::CGUIButtonControl(), CGUIColorButtonControl::CGUIColorButtonControl(), CGUIControl(), CGUIControl(), CGUIControlGroup::CGUIControlGroup(), CGUIControlGroupList::CGUIControlGroupList(), PVR::CGUIEPGGridContainer::CGUIEPGGridContainer(), CGUIFadeLabelControl::CGUIFadeLabelControl(), CGUIFadeLabelControl::CGUIFadeLabelControl(), CGUIFixedListContainer::CGUIFixedListContainer(), KODI::RETRO::CGUIGameControl::CGUIGameControl(), KODI::GAME::CGUIGameController::CGUIGameController(), KODI::GAME::CGUIGameController::CGUIGameController(), KODI::GAME::CGUIGameControllerList::CGUIGameControllerList(), KODI::GAME::CGUIGameControllerList::CGUIGameControllerList(), CGUIImage::CGUIImage(), CGUIImage::CGUIImage(), CGUILabelControl::CGUILabelControl(), CGUIListContainer::CGUIListContainer(), CGUIListContainer::CGUIListContainer(), CGUIListGroup::CGUIListGroup(), CGUIListGroup::CGUIListGroup(), CGUIListLabel::CGUIListLabel(), CGUIMoverControl::CGUIMoverControl(), CGUIMultiImage::CGUIMultiImage(), CGUIMultiImage::CGUIMultiImage(), CGUIPanelContainer::CGUIPanelContainer(), CGUIProgressControl::CGUIProgressControl(), CGUIRadioButtonControl::CGUIRadioButtonControl(), CGUIRangesControl::CGUIRangesControl(), CGUIRenderingControl::CGUIRenderingControl(), CGUIRenderingControl::CGUIRenderingControl(), CGUIResizeControl::CGUIResizeControl(), CGUIRSSControl::CGUIRSSControl(), CGUIRSSControl::CGUIRSSControl(), CGUISettingsSliderControl::CGUISettingsSliderControl(), CGUISliderControl::CGUISliderControl(), CGUISpinControl::CGUISpinControl(), CGUISpinControlEx::CGUISpinControlEx(), CGUITextBox::CGUITextBox(), CGUITextBox::CGUITextBox(), CGUIToggleButtonControl::CGUIToggleButtonControl(), CGUIVideoControl::CGUIVideoControl(), CGUIVisualisationControl::CGUIVisualisationControl(), CGUIVisualisationControl::CGUIVisualisationControl(), CGUIWrappingListContainer::CGUIWrappingListContainer(), CGUIEditControl::DefaultConstructor(), GetControlType(), GUIScrollBarControl::GUIScrollBarControl(), and IsControlRenderable().
DIRTY_STATE_CHILD
const unsigned int CGUIControl::DIRTY_STATE_CHILD = 2 static protected
Referenced by MarkDirtyRegion(), and CGUIWindow::OnMessage().
DIRTY_STATE_CONTROL
const unsigned int CGUIControl::DIRTY_STATE_CONTROL = 1 static protected
Referenced by CGUIControl(), CGUIControl(), DoProcess(), and MarkDirtyRegion().
m_actions
ActionMap CGUIControl::m_actions protected
Referenced by GetAction(), SetAction(), and SetActions().
m_allowHiddenFocus
KODI::GUILIB::GUIINFO::CGUIInfoBool CGUIControl::m_allowHiddenFocus protected
Referenced by CanFocus(), SetInitialVisibility(), SetVisibleCondition(), and UpdateVisibility().
m_animations
std::vector<CAnimation> CGUIControl::m_animations protected
Referenced by Animate(), CGUIWindowScreensaverDim::CGUIWindowScreensaverDim(), FreeResources(), GetAnimation(), GetAnimations(), IsAnimating(), CGUIWindow::Load(), ResetAnimation(), ResetAnimations(), SetAnimations(), CGUIWindow::SetDefaults(), SetInitialVisibility(), and UpdateVisibility().
m_bAllocated
bool CGUIControl::m_bAllocated protected
Referenced by AllocResources(), CGUIWindow::AllocResources(), CGUIControl(), CGUIControl(), CGUIWindow::CheckAnimation(), CGUIWindow::DoRender(), CGUIWindow::FreeResources(), FreeResources(), CGUIImage::FreeResourcesButNotAnims(), CGUIWindow::OnMessage(), and CGUIMultiImage::UpdateVisibility().
m_bHasFocus
bool CGUIControl::m_bHasFocus protected
Referenced by CGUIControl(), CGUIControl(), CGUIListGroup::GetFocusedItem(), HasFocus(), CGUIPanelContainer::Process(), CGUISliderControl::Process(), CGUIPanelContainer::Render(), GUIScrollBarControl::Render(), CGUISliderControl::Render(), and SetFocus().
m_bInvalidated
bool CGUIControl::m_bInvalidated protected
Referenced by AllocResources(), CGUIBaseContainer::CGUIBaseContainer(), CGUIControl(), CGUIControl(), DoProcess(), CGUIDialogBoxBase::Process(), CGUIDialogProgress::Process(), CGUIBaseContainer::Process(), CGUIButtonControl::Process(), CGUIMoverControl::Process(), CGUIPanelContainer::Process(), CGUIResizeControl::Process(), GUIScrollBarControl::Process(), CGUISettingsSliderControl::Process(), CGUISpinControlEx::Process(), CGUIVisualisationControl::Process(), PVR::CGUIEPGGridContainer::Process(), CGUIDialogSubtitles::Process(), PVR::CGUIEPGGridContainer::ProcessItem(), CGUIBaseContainer::ProcessItem(), CGUIEditControl::ProcessText(), SetInvalid(), CGUIListGroup::SetInvalid(), and CGUIListLabel::UpdateInfo().
m_cachedTransform
TransformMatrix CGUIControl::m_cachedTransform protected
Referenced by AssignDepth(), CGUIFadeLabelControl::AssignDepth(), CGUITextBox::AssignDepth(), DoProcess(), and DoRender().
m_camera
CPoint CGUIControl::m_camera protected
Referenced by DoProcess(), DoRender(), CGUIWindow::Load(), and SetCamera().
m_controlDirtyState
unsigned int CGUIControl::m_controlDirtyState protected
Referenced by CGUIControl(), CGUIControl(), DoProcess(), IsControlDirty(), and MarkDirtyRegion().
m_controlID
int CGUIControl::m_controlID protected
Referenced by CGUIControl(), CGUIControl(), CGUIVisualisationControl::DeInitVisualization(), GetControl(), GetID(), CGUISliderControl::SendClick(), and SetID().
m_controlStats
GUICONTROLSTATS* CGUIControl::m_controlStats protected
Referenced by CGUIControlGroup::AddControl(), KODI::RETRO::CGameWindowFullScreen::CGameWindowFullScreen(), CGUIControl(), CGUIControl(), CGUIWindowFullScreen::CGUIWindowFullScreen(), KODI::RETRO::CGameWindowFullScreen::HasVisibleControls(), CGUIWindowFullScreen::HasVisibleControls(), KODI::RETRO::CGameWindowFullScreen::Process(), CGUIWindowFullScreen::Process(), SetControlStats(), UpdateControlStats(), KODI::RETRO::CGameWindowFullScreen::~CGameWindowFullScreen(), and CGUIWindowFullScreen::~CGUIWindowFullScreen().
m_diffuseColor
KODI::GUILIB::GUIINFO::CGUIInfoColor CGUIControl::m_diffuseColor protected
Referenced by CGUIBorderedImage::Process(), CGUIMultiImage::Process(), PVR::CGUIEPGGridContainer::RenderProgressIndicator(), SetColorDiffuse(), UpdateColors(), CGUIButtonControl::UpdateColors(), CGUIColorButtonControl::UpdateColors(), CGUIMoverControl::UpdateColors(), CGUIProgressControl::UpdateColors(), CGUIRadioButtonControl::UpdateColors(), CGUIRangesControl::UpdateColors(), CGUIResizeControl::UpdateColors(), GUIScrollBarControl::UpdateColors(), CGUISettingsSliderControl::UpdateColors(), CGUISliderControl::UpdateColors(), CGUISpinControl::UpdateColors(), CGUISpinControlEx::UpdateColors(), CGUIToggleButtonControl::UpdateColors(), and CGUIImage::UpdateDiffuseColor().
m_enableCondition
INFO::InfoPtr CGUIControl::m_enableCondition protected
Referenced by SetEnableCondition(), SetInitialVisibility(), and UpdateVisibility().
m_enabled
bool CGUIControl::m_enabled protected
Referenced by CGUIControl(), CGUIControl(), IsDisabled(), CGUIMoverControl::Move(), CGUISettingsSliderControl::Process(), CGUISpinControlEx::Process(), SetEnableCondition(), SetEnabled(), SetInitialVisibility(), and UpdateVisibility().
m_forceHidden
bool CGUIControl::m_forceHidden protected
Referenced by CGUIControl(), CGUIControl(), IsVisible(), and SetVisible().
m_hasCamera
bool CGUIControl::m_hasCamera protected
Referenced by CGUIControl(), CGUIControl(), DoProcess(), DoRender(), CGUIWindow::Load(), SetCamera(), and CGUIWindow::SetDefaults().
m_hasProcessed
bool CGUIControl::m_hasProcessed protected
Referenced by AllocResources(), CGUIControl(), CGUIControl(), FreeResources(), CGUIImage::FreeResourcesButNotAnims(), HasProcessed(), CGUIWindow::OnInitWindow(), and Process().
m_height
float CGUIControl::m_height protected
Referenced by CGUIButtonControl::AllocResources(), CGUIMoverControl::AllocResources(), CGUIResizeControl::AllocResources(), CGUISpinControlEx::AllocResources(), CGUIPanelContainer::CalculateLayout(), CGUIControl(), CGUIControl(), CGUIEditControl::CGUIEditControl(), KODI::RETRO::CGUIGameControl::CGUIGameControl(), CGUIListContainer::CGUIListContainer(), GetHeight(), CGUIControlGroupList::GetHeight(), CGUIWindow::GetScaledBounds(), PVR::CGUIEPGGridContainer::HandleChannels(), PVR::CGUIEPGGridContainer::HandleProgrammeGrid(), PVR::CGUIEPGGridContainer::HandleRuler(), CGUIWindow::LoadControl(), CGUIBaseContainer::LoadLayout(), PVR::CGUIEPGGridContainer::LoadLayout(), CGUIBaseContainer::Process(), CGUIButtonControl::Process(), CGUILabelControl::Process(), CGUIMoverControl::Process(), CGUIMultiImage::Process(), CGUIPanelContainer::Process(), CGUIResizeControl::Process(), CGUISettingsSliderControl::Process(), CGUISliderControl::Process(), CGUIColorButtonControl::ProcessInfoText(), CGUISliderControl::ProcessSelector(), CGUIButtonControl::ProcessText(), CGUIEditControl::ProcessText(), CGUIToggleButtonControl::ProcessToggle(), CGUIBaseContainer::Render(), CGUIControlGroupList::Render(), CGUIFadeLabelControl::Render(), CGUIPanelContainer::Render(), CGUIRenderingControl::Render(), CGUISpinControl::Render(), CGUIVideoControl::Render(), CGUIVisualisationControl::Render(), CGUIResizeControl::Resize(), CGUIWindow::SetDefaults(), SetHeight(), KODI::RETRO::CGUIGameControl::SetPosition(), CGUIColorButtonControl::SetPosition(), CGUIRadioButtonControl::SetPosition(), CGUIRangesControl::SetRanges(), KODI::RETRO::CGUIGameControl::SetWidth(), CGUILabelControl::SetWidth(), CGUIListLabel::SetWidth(), CGUIBaseContainer::Size(), CGUIControlGroupList::Size(), CGUILabelControl::UpdateInfo(), CGUITextBox::UpdateInfo(), CGUIRangesControl::UpdateLayout(), PVR::CGUIEPGGridContainer::UpdateLayout(), and CGUIProgressControl::UpdateLayout().
m_hitColor
KODI::UTILS::COLOR::Color CGUIControl::m_hitColor = 0xffffffff protected
Referenced by DoRender(), CGUIButtonControl::ProcessText(), and SetHitRect().
m_hitRect
CRect CGUIControl::m_hitRect protected
Referenced by DoRender(), HitTest(), CGUIWindow::Load(), CGUISpinControl::Render(), CGUIWindow::SetDefaults(), SetHeight(), SetHitRect(), SetPosition(), and SetWidth().
m_isCulled
bool CGUIControl::m_isCulled {true} protected
Referenced by DoProcess(), DoRender(), and MarkDirtyRegion().
m_parentControl
CGUIControl* CGUIControl::m_parentControl protected
Referenced by CGUIControlLookup::AddLookup(), CGUIControl(), CGUIControl(), GetParentControl(), GetRenderPosition(), MarkDirtyRegion(), OnMessage(), CGUIControlGroup::OnMessage(), CGUIControlLookup::RemoveLookup(), CGUIControlLookup::RemoveLookup(), SetParentControl(), and UnfocusFromPoint().
m_parentID
int CGUIControl::m_parentID protected
Referenced by CGUIControl(), CGUIControl(), CGUIListLabel::CGUIListLabel(), CGUIButtonControl::GetDescription(), CGUIFadeLabelControl::GetDescription(), CGUILabelControl::GetDescription(), CGUIFadeLabelControl::GetLabel(), CGUIButtonControl::GetLabel2(), GetParentID(), PVR::CGUIEPGGridContainer::ProcessItem(), CGUIBaseContainer::ProcessItem(), CGUIButtonControl::ProcessText(), CGUIEditControl::ProcessText(), CGUIBaseContainer::RenderItem(), PVR::CGUIEPGGridContainer::RenderItem(), CGUISliderControl::SendClick(), CGUILabelControl::SetCursorPos(), CGUIImage::UpdateInfo(), CGUILabelControl::UpdateInfo(), CGUIListLabel::UpdateInfo(), CGUIMultiImage::UpdateInfo(), CGUIProgressControl::UpdateInfo(), CGUITextBox::UpdateInfo(), and CGUIRangesControl::UpdateInfo().
m_posX
float CGUIControl::m_posX protected
Referenced by CGUIColorButtonControl::AllocResources(), CGUIRadioButtonControl::AllocResources(), CGUISpinControl::AllocResources(), CGUIRSSControl::CalcRenderRegion(), CGUIWindow::CenterWindow(), CGUIControl(), CGUIControl(), KODI::RETRO::CGUIGameControl::CGUIGameControl(), GetXPosition(), PVR::CGUIEPGGridContainer::HandleChannels(), PVR::CGUIEPGGridContainer::HandleProgrammeGrid(), PVR::CGUIEPGGridContainer::HandleRuler(), PVR::CGUIEPGGridContainer::HandleRulerDate(), CGUIWindow::Load(), CGUIBaseContainer::OnMouseEvent(), CGUIBaseContainer::OnMouseOver(), CGUIDialogContextMenu::OnWindowLoaded(), CGUIBaseContainer::Process(), CGUIControlGroupList::Process(), CGUILabelControl::Process(), CGUIListGroup::Process(), CGUIMultiImage::Process(), CGUIPanelContainer::Process(), CGUISliderControl::Process(), CGUISpinControl::Process(), CGUISettingsSliderControl::ProcessText(), CGUIButtonControl::ProcessText(), CGUIEditControl::ProcessText(), CGUIToggleButtonControl::ProcessToggle(), CGUIBaseContainer::Render(), CGUIControlGroupList::Render(), CGUIFadeLabelControl::Render(), CGUIPanelContainer::Render(), CGUIRenderingControl::Render(), CGUIRSSControl::Render(), CGUISpinControl::Render(), CGUITextBox::Render(), CGUIVideoControl::Render(), CGUIVisualisationControl::Render(), CGUIControlGroupList::SendMouseEvent(), CGUIWindow::SetDefaults(), KODI::RETRO::CGUIGameControl::SetHeight(), SetPosition(), CGUIColorButtonControl::SetPosition(), CGUIRadioButtonControl::SetPosition(), CGUISpinControl::SetPosition(), CGUIRangesControl::SetRanges(), KODI::RETRO::CGUIGameControl::SetWidth(), CGUILabelControl::SetWidth(), CGUIListLabel::SetWidth(), CGUIControlGroupList::UnfocusFromPoint(), CGUILabelControl::UpdateInfo(), and PVR::CGUIEPGGridContainer::UpdateLayout().
m_posY
float CGUIControl::m_posY protected
Referenced by CGUIColorButtonControl::AllocResources(), CGUIRadioButtonControl::AllocResources(), CGUISpinControl::AllocResources(), CGUIRSSControl::CalcRenderRegion(), CGUIWindow::CenterWindow(), CGUIControl(), CGUIControl(), KODI::RETRO::CGUIGameControl::CGUIGameControl(), GetYPosition(), PVR::CGUIEPGGridContainer::HandleChannels(), PVR::CGUIEPGGridContainer::HandleProgrammeGrid(), PVR::CGUIEPGGridContainer::HandleRuler(), PVR::CGUIEPGGridContainer::HandleRulerDate(), CGUIWindow::Load(), CGUIBaseContainer::OnMouseEvent(), CGUIBaseContainer::OnMouseOver(), CGUIDialogContextMenu::OnWindowLoaded(), CGUIBaseContainer::Process(), CGUIControlGroupList::Process(), CGUILabelControl::Process(), CGUIListGroup::Process(), CGUIMultiImage::Process(), CGUIPanelContainer::Process(), CGUISliderControl::Process(), CGUISpinControl::Process(), CGUIColorButtonControl::ProcessInfoText(), CGUIButtonControl::ProcessText(), CGUIEditControl::ProcessText(), CGUIToggleButtonControl::ProcessToggle(), CGUIBaseContainer::Render(), CGUIControlGroupList::Render(), CGUIFadeLabelControl::Render(), CGUIPanelContainer::Render(), CGUIRenderingControl::Render(), CGUIRSSControl::Render(), CGUISpinControl::Render(), CGUITextBox::Render(), CGUIVideoControl::Render(), CGUIVisualisationControl::Render(), CGUIControlGroupList::SendMouseEvent(), CGUIWindow::SetDefaults(), KODI::RETRO::CGUIGameControl::SetHeight(), SetPosition(), CGUIColorButtonControl::SetPosition(), CGUIRadioButtonControl::SetPosition(), CGUISpinControl::SetPosition(), CGUIRangesControl::SetRanges(), KODI::RETRO::CGUIGameControl::SetWidth(), CGUILabelControl::SetWidth(), CGUIListLabel::SetWidth(), CGUIControlGroupList::UnfocusFromPoint(), CGUILabelControl::UpdateInfo(), and PVR::CGUIEPGGridContainer::UpdateLayout().
m_pulseOnSelect
bool CGUIControl::m_pulseOnSelect protected
Referenced by CGUIControl(), CGUIControl(), CGUIButtonControl::Process(), CGUISettingsSliderControl::Process(), CGUISpinControlEx::Process(), CGUIToggleButtonControl::Process(), and SetPulseOnSelect().
m_pushedUpdates
bool CGUIControl::m_pushedUpdates protected
Referenced by CGUIControlGroup::AddControl(), CGUIControl(), CGUIControl(), SetPushUpdates(), and UpdateVisibility().
m_renderRegion
CRect CGUIControl::m_renderRegion protected
Referenced by DoProcess(), CGUIDialogBusy::DoProcess(), CGUIDialogBusyNoCancel::DoProcess(), CGUIDialog::DoProcess(), DoRender(), GetRenderRegion(), KODI::RETRO::CGameWindowFullScreen::Process(), CGUIWindowFullScreen::Process(), Process(), CGUIControlGroup::Process(), CGUIListGroup::Process(), CGUIDialogTeletext::Process(), CGUIWindowDebugInfo::Process(), CGUIWindowScreensaverDim::Process(), CGUIWindowSlideShow::Process(), CGUIWindowScreensaver::Process(), CGUIWindowDebugInfo::Render(), and CGUIWindowScreensaver::Render().
m_stereo
float CGUIControl::m_stereo protected
Referenced by CGUIControl(), CGUIControl(), DoRender(), CGUIWindow::Load(), CGUIWindow::SetDefaults(), and SetStereoFactor().
m_transform
TransformMatrix CGUIControl::m_transform protected
Referenced by Animate(), CGUIWindow::Animate(), DoProcess(), GetRenderPosition(), CGUIListGroup::SelectItemFromPoint(), SendMouseEvent(), CGUIControlGroup::SendMouseEvent(), CGUIControlGroupList::SendMouseEvent(), UnfocusFromPoint(), CGUIControlGroup::UnfocusFromPoint(), and CGUIControlGroupList::UnfocusFromPoint().
m_visible
GUIVISIBLE CGUIControl::m_visible protected
Referenced by CGUIImage::AllocateOnDemand(), Animate(), CGUIControl(), CGUIControl(), IsVisible(), SetInitialVisibility(), SetVisible(), SetVisibleCondition(), UpdateStates(), and CGUIMultiImage::UpdateVisibility().
m_visibleCondition
INFO::InfoPtr CGUIControl::m_visibleCondition protected
Referenced by CGUIWindow::ClearAll(), HasVisibleCondition(), CGUIWindow::Load(), SetInitialVisibility(), SetVisible(), SetVisibleCondition(), CGUIDialog::UpdateVisibility(), and UpdateVisibility().
m_visibleFromSkinCondition
bool CGUIControl::m_visibleFromSkinCondition protected
Referenced by CGUIControl(), CGUIControl(), IsVisibleFromSkin(), SetInitialVisibility(), UpdateStates(), and UpdateVisibility().
m_width
float CGUIControl::m_width protected
Referenced by CGUIButtonControl::AllocResources(), CGUIMoverControl::AllocResources(), CGUIResizeControl::AllocResources(), CGUIRSSControl::CalcRenderRegion(), CGUIPanelContainer::CalculateLayout(), CGUIControl(), CGUIControl(), KODI::RETRO::CGUIGameControl::CGUIGameControl(), CGUILabelControl::GetMaxWidth(), CGUIWindow::GetScaledBounds(), GetWidth(), CGUIButtonControl::GetWidth(), CGUIControlGroupList::GetWidth(), CGUILabelControl::GetWidth(), PVR::CGUIEPGGridContainer::HandleChannels(), PVR::CGUIEPGGridContainer::HandleProgrammeGrid(), PVR::CGUIEPGGridContainer::HandleRuler(), CGUIWindow::LoadControl(), CGUIBaseContainer::LoadLayout(), PVR::CGUIEPGGridContainer::LoadLayout(), CGUIBaseContainer::Process(), CGUIFadeLabelControl::Process(), CGUIMoverControl::Process(), CGUIMultiImage::Process(), CGUIPanelContainer::Process(), CGUIResizeControl::Process(), CGUISettingsSliderControl::Process(), CGUISliderControl::Process(), CGUISliderControl::ProcessSelector(), CGUIButtonControl::ProcessText(), CGUIEditControl::ProcessText(), CGUIEditControl::RecalcRightLabelPosition(), CGUIBaseContainer::Render(), CGUIControlGroupList::Render(), CGUIFadeLabelControl::Render(), CGUIPanelContainer::Render(), CGUIRenderingControl::Render(), CGUIRSSControl::Render(), CGUITextBox::Render(), CGUIVideoControl::Render(), CGUIVisualisationControl::Render(), CGUIResizeControl::Resize(), CGUIWindow::SetDefaults(), KODI::RETRO::CGUIGameControl::SetHeight(), KODI::RETRO::CGUIGameControl::SetPosition(), CGUIColorButtonControl::SetPosition(), CGUIRadioButtonControl::SetPosition(), CGUIRangesControl::SetRanges(), SetWidth(), CGUILabelControl::SetWidth(), CGUIListLabel::SetWidth(), CGUILabelControl::ShortenPath(), CGUIBaseContainer::Size(), CGUIControlGroupList::Size(), CGUITextBox::UpdateInfo(), CGUIRangesControl::UpdateLayout(), PVR::CGUIEPGGridContainer::UpdateLayout(), and CGUIProgressControl::UpdateLayout().
The documentation for this class was generated from the following files:
GUIControl.h
GUIControl.cpp