Kodi Documentation: PVR::CPVRGUIActionsUtils Class Reference
PVR::CPVRGUIActionsUtils Class Reference
#include <PVRGUIActionsUtils.h>
Public Member Functions
CPVRGUIActionsUtils ()=default
~CPVRGUIActionsUtils () override=default
bool HasInfoForItem (const CFileItem &item) const
Check whether OnInfo supports the given item.
bool OnInfo (const CFileItem &item)
Process info action for the given item.
std::shared_ptr< CFileItem > LoadItem (const CFileItem &item)
Load item details (create recording info tag etc.).
Public Member Functions inherited from PVR::IPVRComponent
virtual ~IPVRComponent ()=default
Private Member Functions
CPVRGUIActionsUtils (const CPVRGUIActionsUtils &)=delete
CPVRGUIActionsUtils const & operator= (CPVRGUIActionsUtils const &)=delete
Constructor & Destructor Documentation
CPVRGUIActionsUtils() [1/2]
PVR::CPVRGUIActionsUtils::CPVRGUIActionsUtils () default
~CPVRGUIActionsUtils()
PVR::CPVRGUIActionsUtils::~CPVRGUIActionsUtils () override default
CPVRGUIActionsUtils() [2/2]
PVR::CPVRGUIActionsUtils::CPVRGUIActionsUtils (const CPVRGUIActionsUtils &) private delete
Member Function Documentation
HasInfoForItem()
bool PVR::CPVRGUIActionsUtils::HasInfoForItem (const CFileItem & item) const
Check whether OnInfo supports the given item.
Parameters
item The item.
Returns
True if supported, false otherwise.
References CFileItem::HasEPGSearchFilter(), CFileItem::HasPVRChannelInfoTag(), CFileItem::HasPVRRecordingInfoTag(), and CFileItem::HasPVRTimerInfoTag().
Referenced by KODI::UTILS::GUILIB::CGUIContentUtils::HasInfoForItem().
LoadItem()
std::shared_ptr< CFileItem > PVR::CPVRGUIActionsUtils::LoadItem (const CFileItem & item)
Load item details (create recording info tag etc.).
Parameters
item The item.
Returns
Loaded item on success, nullptr otherwise.
References CFileItem::GetPath(), LOGPVR, and LOGWARNING.
OnInfo()
bool PVR::CPVRGUIActionsUtils::OnInfo (const CFileItem & item)
Process info action for the given item.
Parameters
item The item.
Returns
True on success, false otherwise.
References PVR::CPVRManager::Get(), CServiceBroker::GetPVRManager(), CFileItem::HasEPGSearchFilter(), CFileItem::HasPVRChannelInfoTag(), CFileItem::HasPVRRecordingInfoTag(), and CFileItem::HasPVRTimerInfoTag().
operator=()
CPVRGUIActionsUtils const & PVR::CPVRGUIActionsUtils::operator= (CPVRGUIActionsUtils const &) private delete
The documentation for this class was generated from the following files:
PVRGUIActionsUtils.h
PVRGUIActionsUtils.cpp