Kodi Documentation: CScreenshotSurfaceGL Class Reference
CScreenshotSurfaceGL Class Reference
#include <ScreenshotSurfaceGL.h>
Public Member Functions
bool Capture () override
Public Member Functions inherited from IScreenshotSurface
virtual ~IScreenshotSurface ()=default
virtual void CaptureVideo (bool blendToBuffer)
int GetWidth () const
int GetHeight () const
int GetStride () const
unsigned char * GetBuffer () const
void ReleaseBuffer ()
Static Public Member Functions
static void Register ()
static std::unique_ptr< IScreenshotSurface > CreateSurface ()
Additional Inherited Members
Protected Attributes inherited from IScreenshotSurface
int m_width {0}
int m_height {0}
int m_stride {0}
unsigned char * m_buffer {nullptr}
Member Function Documentation
Capture()
bool CScreenshotSurfaceGL::Capture () override virtual
Reimplemented from IScreenshotSurface.
References CWinSystemBase::GetGfxContext(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), CServiceBroker::GetWinSystem(), IScreenshotSurface::m_buffer, IScreenshotSurface::m_height, IScreenshotSurface::m_stride, IScreenshotSurface::m_width, and CGUIWindowManager::Render().
CreateSurface()
std::unique_ptr< IScreenshotSurface > CScreenshotSurfaceGL::CreateSurface () static
Referenced by Register().
Register()
void CScreenshotSurfaceGL::Register () static
References CreateSurface(), and CScreenShot::Register().
Referenced by CWinSystemOSX::CreateNewWindow(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::InitWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContextGL::InitWindowSystem(), and KODI::WINDOWING::X11::CWinSystemX11GLContext::RefreshGLContext().
The documentation for this class was generated from the following files:
ScreenshotSurfaceGL.h
ScreenshotSurfaceGL.cpp