Kodi Documentation: CBuiltins Class Reference
CBuiltins Class Reference
#include <Builtins.h>
Classes
struct BUILT_IN
Struct representing a command from handler classes.
Public Types
typedef std::map< std::string, CBuiltins::BUILT_IN > CommandMap
A map of commands.
Public Member Functions
bool HasCommand (const std::string &execString)
bool IsSystemPowerdownCommand (const std::string &execString)
void GetHelp (std::string &help)
int Execute (const std::string &execString)
Static Public Member Functions
static CBuiltins & GetInstance ()
Protected Member Functions
CBuiltins ()
CBuiltins (const CBuiltins &)=delete
const CBuiltins & operator= (const CBuiltins &)=delete
virtual ~CBuiltins ()
Private Member Functions
template<class T >
void RegisterCommands ()
Convenience template used to register commands from providers.
Private Attributes
CommandMap m_command
Map of registered commands.
Member Typedef Documentation
CommandMap
typedef std::map<std::string,CBuiltins::BUILT_IN> CBuiltins::CommandMap
A map of commands.
Constructor & Destructor Documentation
CBuiltins() [1/2]
CBuiltins::CBuiltins () protected
CBuiltins() [2/2]
CBuiltins::CBuiltins (const CBuiltins &) protected delete
~CBuiltins()
CBuiltins::~CBuiltins () protected virtual default
Member Function Documentation
Execute()
int CBuiltins::Execute (const std::string & execString)
References CInputManager::ExecuteBuiltin(), CExecString::GetFunction(), CServiceBroker::GetInputManager(), CExecString::GetParams(), CExecString::IsValid(), CLog::Log(), LOGERROR, and m_command.
Referenced by JSONRPC::CSystemOperations::EjectOpticalDrive(), EVENTSERVER::CEventServer::ExecuteNextAction(), CApplication::ExecuteXBMCAction(), CApplication::OnAction(), CGUIWindowLoginScreen::OnAction(), CApplication::OnApplicationMessage(), CGUIDialogAddonInfo::OnSelect(), CMediaSettings::OnSettingAction(), CRssManager::OnSettingAction(), JSONRPC::CPlayerOperations::PlayPause(), RunAddon(), JSONRPC::CPlayerOperations::Seek(), and JSONRPC::CPlayerOperations::SetSpeed().
GetHelp()
void CBuiltins::GetHelp (std::string & help)
References m_command.
GetInstance()
CBuiltins & CBuiltins::GetInstance () static
Referenced by JSONRPC::CSystemOperations::EjectOpticalDrive(), EVENTSERVER::CEventServer::ExecuteNextAction(), CApplication::ExecuteXBMCAction(), CApplication::OnAction(), CGUIWindowLoginScreen::OnAction(), CApplication::OnApplicationMessage(), CGUIDialogAddonInfo::OnSelect(), CMediaSettings::OnSettingAction(), CRssManager::OnSettingAction(), JSONRPC::CPlayerOperations::PlayPause(), RunAddon(), JSONRPC::CPlayerOperations::Seek(), JSONRPC::CPlayerOperations::SetSpeed(), and KODI::ACTION::CActionTranslator::TranslateString().
HasCommand()
bool CBuiltins::HasCommand (const std::string & execString)
References CExecString::GetFunction(), CServiceBroker::GetInputManager(), CExecString::GetParams(), CExecString::IsValid(), and m_command.
IsSystemPowerdownCommand()
bool CBuiltins::IsSystemPowerdownCommand (const std::string & execString)
References CExecString::GetFunction(), CServiceBroker::GetSettingsComponent(), CExecString::IsValid(), POWERSTATE_HIBERNATE, POWERSTATE_SHUTDOWN, POWERSTATE_SUSPEND, and CSettings::SETTING_POWERMANAGEMENT_SHUTDOWNSTATE.
operator=()
const CBuiltins & CBuiltins::operator= (const CBuiltins &) protected delete
RegisterCommands()
template<class T > void CBuiltins::RegisterCommands () inline private
Convenience template used to register commands from providers.
References m_command, and t.
Member Data Documentation
m_command
CommandMap CBuiltins::m_command private
Map of registered commands.
Referenced by Execute(), GetHelp(), HasCommand(), and RegisterCommands().
The documentation for this class was generated from the following files:
Builtins.h
Builtins.cpp