Kodi Documentation: CDVDCodecUtils Class Reference
CDVDCodecUtils Class Reference
#include <DVDCodecUtils.h>
Static Public Member Functions
static bool IsVP3CompatibleWidth (int width)
static double NormalizeFrameduration (double frameduration, bool *match=nullptr)
Member Function Documentation
IsVP3CompatibleWidth()
bool CDVDCodecUtils::IsVP3CompatibleWidth (int width) static
Referenced by HasVP3WidthBug(), and VDPAU::CDecoder::Open().
NormalizeFrameduration()
double CDVDCodecUtils::NormalizeFrameduration (double frameduration, bool * match = nullptr) static
References DVD_MSEC_TO_TIME(), and DVD_TIME_BASE.
Referenced by CPtsTracker::CalcFrameDuration(), CVideoPlayerVideo::OpenStream(), and CVideoPlayer::OpenVideoStream().
The documentation for this class was generated from the following files:
DVDCodecUtils.h
DVDCodecUtils.cpp