Kodi Documentation: XHandle.cpp File Reference
XHandle.cpp File Reference
#include "XHandle.h"
#include "utils/log.h"
#include <cassert>
#include <mutex>
Functions
HANDLE WINAPI GetCurrentProcess (void)
bool CloseHandle (HANDLE hObject)
Function Documentation
CloseHandle()
bool CloseHandle (HANDLE hObject)
References INVALID_HANDLE_VALUE, CXHandle::m_internalLock, and CXHandle::m_nRefCount.
Referenced by XFILE::CWin32File::Close(), XFILE::CCircularCache::Close(), CAESinkWASAPI::Deinitialize(), CWin32StorageProvider::Eject(), CWin32StorageProvider::GetDrivesDevInstByDiskNumber(), CWIN32Util::GetDriveStatus(), CAESinkWASAPI::Initialize(), CWHelper::OnExit(), CWin32PowerStateWorker::PowerManagement(), XFILE::CWin32File::Stat(), CWIN32Util::ToggleTray(), WinMain(), win32_exception::write_minidump(), win32_exception::write_stacktrace(), DXVA::CVideoBufferShared::~CVideoBufferShared(), CWHelper::~CWHelper(), XFILE::CWin32File::~CWin32File(), and CAESinkXAudio::VoiceCallback::~VoiceCallback().
GetCurrentProcess()
HANDLE WINAPI GetCurrentProcess (void)
Referenced by DXVA::CContext::CreateContext(), DXVA::CContext::DestroyContext(), CSysInfo::GetKernelBitness(), CSysInfo::GetUserAgent(), CWin32PowerStateWorker::PowerManagement(), win32_exception::write_minidump(), and win32_exception::write_stacktrace().