Kodi Documentation: CInputStreamAddon Class Reference
CInputStreamAddon Class Reference
Input stream class.
#include <InputStreamAddon.h>
Public Member Functions
CInputStreamAddon (const ADDON::AddonInfoPtr &addonInfo, IVideoPlayer *player, const CFileItem &fileitem, const std::string &instanceId)
~CInputStreamAddon () override
bool Open () override
void Close () override
int Read (uint8_t *buf, int buf_size) override
int64_t Seek (int64_t offset, int whence) override
int64_t GetLength () override
int GetBlockSize () override
bool IsEOF () override
bool CanSeek () override
bool CanPause () override
CDVDInputStream::IDisplayTime * GetIDisplayTime () override
int GetTotalTime () override
int GetTime () override
CDVDInputStream::ITimes * GetITimes () override
bool GetTimes (Times &times) override
CDVDInputStream::IPosTime * GetIPosTime () override
bool PosTime (int ms) override
CDVDInputStream::IDemux * GetIDemux () override
bool OpenDemux () override
DemuxPacket * ReadDemux () override
CDemuxStream * GetStream (int streamId) const override
std::vector< CDemuxStream * > GetStreams () const override
void EnableStream (int streamId, bool enable) override
bool OpenStream (int streamid) override
int GetNrOfStreams () const override
void SetSpeed (int speed) override
bool SeekTime (double time, bool backward=false, double *startpts=nullptr) override
void AbortDemux () override
void FlushDemux () override
void SetVideoResolution (unsigned int width, unsigned int height, unsigned int maxWidth, unsigned int maxHeight) override
bool IsRealtime () override
CDVDInputStream::IChapter * GetIChapter () override
int GetChapter () override
int GetChapterCount () override
void GetChapterName (std::string &name, int ch=-1) override
int64_t GetChapterPos (int ch=-1) override
bool SeekChapter (int ch) override
Public Member Functions inherited from ADDON::IAddonInstanceHandler
IAddonInstanceHandler (ADDON_TYPE type, const AddonInfoPtr &addonInfo, AddonInstanceId instanceId=ADDON_INSTANCE_ID_UNUSED, KODI_HANDLE parentInstance=nullptr, const std::string &uniqueWorkID="")
Class constructor for handling add-on instance processes, allowing an add-on to handle multiple work simultaneously and independently.
virtual ~IAddonInstanceHandler ()
ADDON_TYPE UsedType () const
AddonInstanceId InstanceId () const
const std::string & UniqueWorkID ()
std::string ID () const
AddonInstanceId InstanceID () const
std::string Name () const
std::string Author () const
std::string Icon () const
std::string Path () const
std::string Profile () const
CAddonVersion Version () const
ADDON_STATUS CreateInstance ()
void DestroyInstance ()
const AddonDllPtr & Addon () const
AddonInfoPtr GetAddonInfo () const
virtual void OnPreInstall ()
virtual void OnPostInstall (bool update, bool modal)
virtual void OnPreUnInstall ()
virtual void OnPostUnInstall ()
Public Member Functions inherited from CDVDInputStream
CDVDInputStream (DVDStreamType m_streamType, const CFileItem &fileitem)
virtual ~CDVDInputStream ()
virtual std::string & GetContent ()
virtual std::string GetFileName ()
virtual CURL GetURL ()
virtual ENextStream NextStream ()
virtual void Abort ()
virtual void SetReadRate (uint32_t rate)
Indicate expected read rate in bytes per second. This could be used to throttle caching rate. Should be seen as only a hint.
virtual bool GetCacheStatus (XFILE::SCacheStatus *status)
Get the cache status.
bool IsStreamType (DVDStreamType type) const
virtual BitstreamStats GetBitstreamStats () const
bool ContentLookup ()
void SetRealtime (bool realtime)
const CVariant & GetProperty (const std::string &key)
Public Member Functions inherited from CDVDInputStream::IDisplayTime
virtual ~IDisplayTime ()=default
Public Member Functions inherited from CDVDInputStream::ITimes
virtual ~ITimes ()=default
Public Member Functions inherited from CDVDInputStream::IPosTime
virtual ~IPosTime ()=default
Public Member Functions inherited from CDVDInputStream::IDemux
virtual ~IDemux ()=default
virtual void FillBuffer (bool mode)
Public Member Functions inherited from CDVDInputStream::IChapter
virtual ~IChapter ()=default
Static Public Member Functions
static bool Supports (const ADDON::AddonInfoPtr &addonInfo, const CFileItem &fileitem)
Static Protected Member Functions
static int ConvertVideoCodecProfile (STREAMCODEC_PROFILE profile)
static int ConvertAudioCodecProfile (STREAMCODEC_PROFILE profile)
Protected Attributes
IVideoPlayer * m_player
Protected Attributes inherited from ADDON::IAddonInstanceHandler
KODI_ADDON_INSTANCE_INFO m_info {}
KODI_ADDON_INSTANCE_STRUCT m_ifc {}
Protected Attributes inherited from CDVDInputStream
DVDStreamType m_streamType
BitstreamStats m_stats
std::string m_content
CFileItem m_item
bool m_contentLookup
bool m_realtime
Private Member Functions
void DetectScreenResolution ()
Static Private Member Functions
static DEMUX_PACKET * cb_allocate_demux_packet (void *kodiInstance, int iDataSize=0)
Allocate a demux packet. Free with FreeDemuxPacket.
static DEMUX_PACKET * cb_allocate_encrypted_demux_packet (void *kodiInstance, unsigned int dataSize, unsigned int encryptedSubsampleCount)
Allocate an encrypted demux packet. Free with FreeDemuxPacket.
static void cb_free_demux_packet (void *kodiInstance, DEMUX_PACKET *pPacket)
Free a packet that was allocated with AllocateDemuxPacket.
static KODI_HANDLE cb_get_stream_transfer (KODI_HANDLE handle, int streamId, INPUTSTREAM_INFO *stream)
Callback used by GetStream to get the data.
Private Attributes
unsigned int m_currentVideoWidth {0}
unsigned int m_currentVideoHeight {0}
std::vector< std::string > m_fileItemProps
INPUTSTREAM_CAPABILITIES m_caps
int m_streamCount = 0
std::shared_ptr< CInputStreamProvider > m_subAddonProvider
std::vector< std::unique_ptr< CDemuxStream > > m_streams
Additional Inherited Members
Public Types inherited from CDVDInputStream
enum ENextStream { NEXTSTREAM_NONE , NEXTSTREAM_OPEN , NEXTSTREAM_RETRY }
Detailed Description
Input stream class.
Constructor & Destructor Documentation
CInputStreamAddon()
CInputStreamAddon::CInputStreamAddon (const ADDON::AddonInfoPtr & addonInfo, IVideoPlayer * player, const CFileItem & fileitem, const std::string & instanceId)
References m_caps, m_fileItemProps, and name.
~CInputStreamAddon()
CInputStreamAddon::~CInputStreamAddon () override
References Close().
Member Function Documentation
AbortDemux()
void CInputStreamAddon::AbortDemux () override virtual
Implements CDVDInputStream::IDemux.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
CanPause()
bool CInputStreamAddon::CanPause () override virtual
Todo:
drop this
Reimplemented from CDVDInputStream.
References INPUTSTREAM_SUPPORTS_PAUSE, m_caps, and INPUTSTREAM_CAPABILITIES::m_mask.
CanSeek()
bool CInputStreamAddon::CanSeek () override virtual
Reimplemented from CDVDInputStream.
References INPUTSTREAM_SUPPORTS_SEEK, m_caps, and INPUTSTREAM_CAPABILITIES::m_mask.
cb_allocate_demux_packet()
DEMUX_PACKET * CInputStreamAddon::cb_allocate_demux_packet (void * kodiInstance, int data_size = 0) static private
Allocate a demux packet. Free with FreeDemuxPacket.
Callbacks from add-on to kodi
Parameters
kodiInstance A pointer to the add-on.
iDataSize The size of the data that will go into the packet
Returns
The allocated packet.
Callbacks from add-on to kodi
References CDVDDemuxUtils::AllocateDemuxPacket().
Referenced by Open().
cb_allocate_encrypted_demux_packet()
DEMUX_PACKET * CInputStreamAddon::cb_allocate_encrypted_demux_packet (void * kodiInstance, unsigned int dataSize, unsigned int encryptedSubsampleCount) static private
Allocate an encrypted demux packet. Free with FreeDemuxPacket.
Parameters
kodiInstance A pointer to the add-on.
dataSize The size of the data that will go into the packet
encryptedSubsampleCount The number of subsample description blocks to allocate
Returns
The allocated packet.
References CDVDDemuxUtils::AllocateDemuxPacket().
Referenced by Open().
cb_free_demux_packet()
void CInputStreamAddon::cb_free_demux_packet (void * kodiInstance, DEMUX_PACKET * pPacket) static private
Free a packet that was allocated with AllocateDemuxPacket.
Parameters
kodiInstance A pointer to the add-on.
pPacket The packet to free.
References CDVDDemuxUtils::FreeDemuxPacket().
Referenced by Open().
cb_get_stream_transfer()
KODI_HANDLE CInputStreamAddon::cb_get_stream_transfer (KODI_HANDLE handle, int streamId, INPUTSTREAM_INFO * stream) static private
Callback used by GetStream to get the data.
Used as callback to prevent memleaks as the temporary stack memory on addon can be used to give data to Kodi.
Parameters
[in] handle Pointer to identify this class
[in] streamId The related stream Identifier
[in] stream "C" structure with stream information
Returns
The created demux stream packet
Added on API version 2.0.8
Added on API version 2.0.9
References ADDON_INSTANCE_VERSION_INPUTSTREAM_XML_ID, CDemuxStream::codec, CDemuxStream::codec_fourcc, CDemuxStream::codecName, CDemuxStreamVideo::colorPrimaries, CDemuxStreamVideo::colorRange, CDemuxStreamVideo::colorSpace, CDemuxStreamVideo::colorTransferCharacteristic, CDemuxStreamVideo::contentLightMetaData, ConvertAudioCodecProfile(), ConvertVideoCodecProfile(), CRYPTO_SESSION_SYSTEM_CLEARKEY, CRYPTO_SESSION_SYSTEM_NONE, CRYPTO_SESSION_SYSTEM_PLAYREADY, CRYPTO_SESSION_SYSTEM_WIDEVINE, CRYPTO_SESSION_SYSTEM_WISEPLAY, CDemuxStream::cryptoSession, CDemuxStream::externalInterfaces, CDemuxStream::extraData, CDemuxStreamVideo::fAspect, STREAM_CRYPTO_SESSION::flags, CDemuxStream::flags, ADDON::IAddonInstanceHandler::GetAddonInfo(), CDemuxStreamVideo::iBitRate, CDemuxStreamAudio::iBitRate, CDemuxStreamAudio::iBitsPerSample, CDemuxStreamAudio::iBlockAlign, CDemuxStreamAudio::iChannels, CDemuxStreamVideo::iFpsRate, CDemuxStreamVideo::iFpsScale, CDemuxStreamVideo::iHeight, INPUTSTREAM_FEATURE_DECODE, INPUTSTREAM_TYPE_AUDIO, INPUTSTREAM_TYPE_ID3, INPUTSTREAM_TYPE_RDS, INPUTSTREAM_TYPE_SUBTITLE, INPUTSTREAM_TYPE_TELETEXT, INPUTSTREAM_TYPE_VIDEO, CDemuxStreamAudio::iSampleRate, CDemuxStreamVideo::iWidth, STREAM_CRYPTO_SESSION::keySystem, CDemuxStream::language, INPUTSTREAM_MASTERING_METADATA::luminance_max, INPUTSTREAM_MASTERING_METADATA::luminance_min, INPUTSTREAM_INFO::m_Aspect, INPUTSTREAM_INFO::m_BitRate, INPUTSTREAM_INFO::m_BitsPerSample, INPUTSTREAM_INFO::m_BlockAlign, INPUTSTREAM_INFO::m_Channels, INPUTSTREAM_INFO::m_codecFourCC, INPUTSTREAM_INFO::m_codecInternalName, INPUTSTREAM_INFO::m_codecName, INPUTSTREAM_INFO::m_codecProfile, INPUTSTREAM_INFO::m_colorPrimaries, INPUTSTREAM_INFO::m_colorRange, INPUTSTREAM_INFO::m_colorSpace, INPUTSTREAM_INFO::m_colorTransferCharacteristic, INPUTSTREAM_INFO::m_contentLightMetadata, INPUTSTREAM_INFO::m_cryptoSession, INPUTSTREAM_INFO::m_ExtraData, INPUTSTREAM_INFO::m_ExtraSize, INPUTSTREAM_INFO::m_features, INPUTSTREAM_INFO::m_flags, INPUTSTREAM_INFO::m_FpsRate, INPUTSTREAM_INFO::m_FpsScale, INPUTSTREAM_INFO::m_Height, INPUTSTREAM_INFO::m_language, INPUTSTREAM_INFO::m_masteringMetadata, INPUTSTREAM_INFO::m_name, INPUTSTREAM_INFO::m_SampleRate, m_streams, INPUTSTREAM_INFO::m_streamType, m_subAddonProvider, INPUTSTREAM_INFO::m_Width, CDemuxStreamVideo::masteringMetaData, INPUTSTREAM_CONTENTLIGHT_METADATA::max_cll, INPUTSTREAM_CONTENTLIGHT_METADATA::max_fall, CDemuxStream::name, INPUTSTREAM_MASTERING_METADATA::primary_b_chromaticity_x, INPUTSTREAM_MASTERING_METADATA::primary_b_chromaticity_y, INPUTSTREAM_MASTERING_METADATA::primary_g_chromaticity_x, INPUTSTREAM_MASTERING_METADATA::primary_g_chromaticity_y, INPUTSTREAM_MASTERING_METADATA::primary_r_chromaticity_x, INPUTSTREAM_MASTERING_METADATA::primary_r_chromaticity_y, CDemuxStream::profile, STREAM_CRYPTO_SESSION::sessionId, STREAM_CRYPTO_KEY_SYSTEM_COUNT, STREAM_CRYPTO_KEY_SYSTEM_NONE, CDemuxStream::uniqueId, INPUTSTREAM_MASTERING_METADATA::white_point_chromaticity_x, and INPUTSTREAM_MASTERING_METADATA::white_point_chromaticity_y.
Referenced by GetStream().
Close()
void CInputStreamAddon::Close () override virtual
Reimplemented from CDVDInputStream.
References ADDON::IAddonInstanceHandler::DestroyInstance(), KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, AddonInstance_InputStream::props, AddonInstance_InputStream::toAddon, and AddonInstance_InputStream::toKodi.
Referenced by ~CInputStreamAddon().
ConvertAudioCodecProfile()
int CInputStreamAddon::ConvertAudioCodecProfile (STREAMCODEC_PROFILE profile) static protected
Todo:
: with ffmpeg >= 6.1 set the appropriate profile
Todo:
: with ffmpeg >= 6.1 set the appropriate profile
Todo:
: with ffmpeg >= 6.1 set the appropriate profile
References AACCodecProfileELD, AACCodecProfileHE, AACCodecProfileHEV2, AACCodecProfileLD, AACCodecProfileLOW, AACCodecProfileLTP, AACCodecProfileMAIN, AACCodecProfileSSR, DDPlusCodecProfileAtmos, DTSCodecProfile, DTSCodecProfile9624, DTSCodecProfileES, DTSCodecProfileHDExpress, DTSCodecProfileHDHRA, DTSCodecProfileHDMA, DTSCodecProfileHDMAIMAX, DTSCodecProfileHDMAX, MPEG2AACCodecProfileHE, and MPEG2AACCodecProfileLOW.
Referenced by cb_get_stream_transfer().
ConvertVideoCodecProfile()
int CInputStreamAddon::ConvertVideoCodecProfile (STREAMCODEC_PROFILE profile) static protected
References AV1CodecProfileHigh, AV1CodecProfileMain, AV1CodecProfileProfessional, H264CodecProfileBaseline, H264CodecProfileExtended, H264CodecProfileHigh, H264CodecProfileHigh10, H264CodecProfileHigh422, H264CodecProfileHigh444Predictive, H264CodecProfileMain, VP9CodecProfile0, VP9CodecProfile1, VP9CodecProfile2, and VP9CodecProfile3.
Referenced by cb_get_stream_transfer().
DetectScreenResolution()
void CInputStreamAddon::DetectScreenResolution () private
References CResolutionUtils::GetMaxAllowedScreenResolution(), IVideoPlayer::GetVideoResolution(), m_currentVideoHeight, m_currentVideoWidth, m_player, and SetVideoResolution().
Referenced by GetITimes(), and Open().
EnableStream()
void CInputStreamAddon::EnableStream (int streamId, bool enable) override virtual
Reimplemented from CDVDInputStream::IDemux.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
FlushDemux()
void CInputStreamAddon::FlushDemux () override virtual
Implements CDVDInputStream::IDemux.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
Referenced by SeekTime().
GetBlockSize()
int CInputStreamAddon::GetBlockSize () override virtual
Reimplemented from CDVDInputStream.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
GetChapter()
int CInputStreamAddon::GetChapter () override virtual
Implements CDVDInputStream::IChapter.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
GetChapterCount()
int CInputStreamAddon::GetChapterCount () override virtual
Implements CDVDInputStream::IChapter.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
GetChapterName()
void CInputStreamAddon::GetChapterName (std::string & name, int ch = -1) override virtual
Implements CDVDInputStream::IChapter.
References KodiToAddonFuncTable_InputStream::get_chapter_name(), KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, name, and AddonInstance_InputStream::toAddon.
GetChapterPos()
int64_t CInputStreamAddon::GetChapterPos (int ch = -1) override virtual
Implements CDVDInputStream::IChapter.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
GetIChapter()
CDVDInputStream::IChapter * CInputStreamAddon::GetIChapter () override virtual
Reimplemented from CDVDInputStream.
References INPUTSTREAM_SUPPORTS_ICHAPTER, m_caps, and INPUTSTREAM_CAPABILITIES::m_mask.
GetIDemux()
CDVDInputStream::IDemux * CInputStreamAddon::GetIDemux () override virtual
Reimplemented from CDVDInputStream.
References INPUTSTREAM_SUPPORTS_IDEMUX, m_caps, and INPUTSTREAM_CAPABILITIES::m_mask.
GetIDisplayTime()
CDVDInputStream::IDisplayTime * CInputStreamAddon::GetIDisplayTime () override virtual
Reimplemented from CDVDInputStream.
References INPUTSTREAM_SUPPORTS_IDISPLAYTIME, m_caps, and INPUTSTREAM_CAPABILITIES::m_mask.
GetIPosTime()
CDVDInputStream::IPosTime * CInputStreamAddon::GetIPosTime () override virtual
Reimplemented from CDVDInputStream.
References INPUTSTREAM_SUPPORTS_IPOSTIME, m_caps, and INPUTSTREAM_CAPABILITIES::m_mask.
GetITimes()
CDVDInputStream::ITimes * CInputStreamAddon::GetITimes () override virtual
Reimplemented from CDVDInputStream.
References DetectScreenResolution(), INPUTSTREAM_SUPPORTS_ITIME, m_caps, and INPUTSTREAM_CAPABILITIES::m_mask.
GetLength()
int64_t CInputStreamAddon::GetLength () override virtual
Implements CDVDInputStream.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
GetNrOfStreams()
int CInputStreamAddon::GetNrOfStreams () const override virtual
Implements CDVDInputStream::IDemux.
References m_streamCount.
GetStream()
CDemuxStream * CInputStreamAddon::GetStream (int streamId) const override virtual
Implements CDVDInputStream::IDemux.
References cb_get_stream_transfer(), KODI_ADDON_INSTANCE_STRUCT::inputstream, INPUTSTREAM_TYPE_NONE, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
Referenced by GetStreams().
GetStreams()
std::vector< CDemuxStream * > CInputStreamAddon::GetStreams () const override virtual
Implements CDVDInputStream::IDemux.
References GetStream(), KODI_ADDON_INSTANCE_STRUCT::inputstream, INPUTSTREAM_MAX_STREAM_COUNT, ADDON::IAddonInstanceHandler::m_ifc, INPUTSTREAM_IDS::m_streamCount, INPUTSTREAM_IDS::m_streamIds, and AddonInstance_InputStream::toAddon.
GetTime()
int CInputStreamAddon::GetTime () override virtual
Implements CDVDInputStream::IDisplayTime.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
GetTimes()
bool CInputStreamAddon::GetTimes (Times & times) override virtual
Implements CDVDInputStream::ITimes.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, INPUTSTREAM_TIMES::ptsBegin, CDVDInputStream::ITimes::Times::ptsBegin, INPUTSTREAM_TIMES::ptsEnd, CDVDInputStream::ITimes::Times::ptsEnd, INPUTSTREAM_TIMES::ptsStart, CDVDInputStream::ITimes::Times::ptsStart, INPUTSTREAM_TIMES::startTime, CDVDInputStream::ITimes::Times::startTime, and AddonInstance_InputStream::toAddon.
GetTotalTime()
int CInputStreamAddon::GetTotalTime () override virtual
Implements CDVDInputStream::IDisplayTime.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
IsEOF()
bool CInputStreamAddon::IsEOF () override virtual
Implements CDVDInputStream.
IsRealtime()
bool CInputStreamAddon::IsRealtime () override virtual
Reimplemented from CDVDInputStream.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
Open()
bool CInputStreamAddon::Open () override virtual
Reimplemented from CDVDInputStream.
References ADDON::IAddonInstanceHandler::Addon(), ADDON_STATUS_OK, KodiToAddonFuncTable_InputStream::addonInstance, AddonToKodiFuncTable_InputStream::allocate_demux_packet, AddonToKodiFuncTable_InputStream::allocate_encrypted_demux_packet, CVariant::asString(), cb_allocate_demux_packet(), cb_allocate_encrypted_demux_packet(), cb_free_demux_packet(), ADDON::IAddonInstanceHandler::CreateInstance(), DetectScreenResolution(), AddonToKodiFuncTable_InputStream::free_demux_packet, ADDON::IAddonInstanceHandler::GetAddonInfo(), URIUtils::GetDirectory(), CFileItem::GetDynPath(), CFileItem::GetMimeType(), CGUIListItem::GetProperty(), KODI_ADDON_INSTANCE_STRUCT::inputstream, CVariant::isNull(), AddonToKodiFuncTable_InputStream::kodiInstance, CLog::Log(), LOGERROR, m_caps, m_fileItemProps, ADDON::IAddonInstanceHandler::m_ifc, CDVDInputStream::m_item, INPUTSTREAM_PROPERTY::m_libFolder, INPUTSTREAM_PROPERTY::m_ListItemProperties, INPUTSTREAM_PROPERTY::m_mimeType, INPUTSTREAM_PROPERTY::m_nCountInfoValues, INPUTSTREAM_PROPERTY::m_profileFolder, INPUTSTREAM_PROPERTY::LISTITEMPROPERTY::m_strKey, INPUTSTREAM_PROPERTY::m_strURL, INPUTSTREAM_PROPERTY::LISTITEMPROPERTY::m_strValue, m_subAddonProvider, ADDON::IAddonInstanceHandler::Path(), ADDON::IAddonInstanceHandler::Profile(), AddonInstance_InputStream::props, STREAM_MAX_PROPERTY_COUNT, AddonInstance_InputStream::toAddon, AddonInstance_InputStream::toKodi, and CSpecialProtocol::TranslatePath().
OpenDemux()
bool CInputStreamAddon::OpenDemux () override virtual
Implements CDVDInputStream::IDemux.
References INPUTSTREAM_SUPPORTS_IDEMUX, m_caps, and INPUTSTREAM_CAPABILITIES::m_mask.
OpenStream()
bool CInputStreamAddon::OpenStream (int streamid) override virtual
Reimplemented from CDVDInputStream::IDemux.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
PosTime()
bool CInputStreamAddon::PosTime (int ms) override virtual
Implements CDVDInputStream::IPosTime.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
Referenced by SeekTime().
Read()
int CInputStreamAddon::Read (uint8_t * buf, int buf_size) override virtual
Implements CDVDInputStream.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
ReadDemux()
DemuxPacket * CInputStreamAddon::ReadDemux () override virtual
Implements CDVDInputStream::IDemux.
References KodiToAddonFuncTable_InputStream::demux_read(), KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
Seek()
int64_t CInputStreamAddon::Seek (int64_t offset, int whence) override virtual
Implements CDVDInputStream.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
SeekChapter()
bool CInputStreamAddon::SeekChapter (int ch) override virtual
Implements CDVDInputStream::IChapter.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
SeekTime()
bool CInputStreamAddon::SeekTime (double time, bool backward = false, double * startpts = nullptr) override virtual
Implements CDVDInputStream::IDemux.
References DVD_NOPTS_VALUE, FlushDemux(), KODI_ADDON_INSTANCE_STRUCT::inputstream, INPUTSTREAM_SUPPORTS_IPOSTIME, m_caps, ADDON::IAddonInstanceHandler::m_ifc, INPUTSTREAM_CAPABILITIES::m_mask, PosTime(), and AddonInstance_InputStream::toAddon.
SetSpeed()
void CInputStreamAddon::SetSpeed (int speed) override virtual
Implements CDVDInputStream::IDemux.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
SetVideoResolution()
void CInputStreamAddon::SetVideoResolution (unsigned int width, unsigned int height, unsigned int maxWidth, unsigned int maxHeight) override virtual
Reimplemented from CDVDInputStream::IDemux.
References KODI_ADDON_INSTANCE_STRUCT::inputstream, ADDON::IAddonInstanceHandler::m_ifc, and AddonInstance_InputStream::toAddon.
Referenced by DetectScreenResolution().
Supports()
bool CInputStreamAddon::Supports (const ADDON::AddonInfoPtr & addonInfo, const CFileItem & fileitem) static
Todo:
Error for users to show deprecation, can be removed in Kodi 20
References CVariant::asString(), CFileItem::GetDynPath(), CURL::GetFileType(), CGUIListItem::GetProperty(), CURL::GetProtocol(), CFileItem::GetURL(), CVariant::isNull(), CLog::Log(), LOGERROR, STREAM_PROPERTY_INPUTSTREAM, and value.
Referenced by CDVDFactoryInputStream::CreateInputStream().
Member Data Documentation
m_caps
INPUTSTREAM_CAPABILITIES CInputStreamAddon::m_caps private
Referenced by CanPause(), CanSeek(), CInputStreamAddon(), GetIChapter(), GetIDemux(), GetIDisplayTime(), GetIPosTime(), GetITimes(), Open(), OpenDemux(), and SeekTime().
m_currentVideoHeight
unsigned int CInputStreamAddon::m_currentVideoHeight {0} private
Referenced by DetectScreenResolution().
m_currentVideoWidth
unsigned int CInputStreamAddon::m_currentVideoWidth {0} private
Referenced by DetectScreenResolution().
m_fileItemProps
std::vector<std::string> CInputStreamAddon::m_fileItemProps private
Referenced by CInputStreamAddon(), and Open().
m_player
IVideoPlayer* CInputStreamAddon::m_player protected
Referenced by DetectScreenResolution().
m_streamCount
int CInputStreamAddon::m_streamCount = 0 private
Referenced by GetNrOfStreams().
m_streams
std::vector<std::unique_ptr<CDemuxStream> > CInputStreamAddon::m_streams private
This class takes ownership of the CDemuxStreams created in cb_get_stream_transfer by storing them in this vector
Referenced by cb_get_stream_transfer().
m_subAddonProvider
std::shared_ptr<CInputStreamProvider> CInputStreamAddon::m_subAddonProvider private
Referenced by cb_get_stream_transfer(), and Open().
The documentation for this class was generated from the following files:
InputStreamAddon.h
InputStreamAddon.cpp