Kodi Documentation: XFILE::VIDEODATABASEDIRECTORY::CQueryParams Class Reference
XFILE::VIDEODATABASEDIRECTORY::CQueryParams Class Reference
#include <QueryParams.h>
Public Member Functions
CQueryParams ()
long GetContentType () const
long GetMovieId () const
long GetYear () const
long GetGenreId () const
long GetCountryId () const
long GetActorId () const
long GetAlbumId () const
long GetDirectorId () const
long GetTvShowId () const
long GetSeason () const
long GetEpisodeId () const
long GetStudioId () const
long GetMVideoId () const
long GetSetId () const
long GetTagId () const
long GetVideoVersionId () const
Protected Member Functions
void SetQueryParam (NODE_TYPE NodeType, const std::string &strNodeName)
Private Attributes
long m_idContent
long m_idMovie
long m_idGenre
long m_idCountry
long m_idYear
long m_idActor
long m_idDirector
long m_idShow
long m_idSeason
long m_idEpisode
long m_idStudio
long m_idMVideo
long m_idAlbum
long m_idSet
long m_idTag
long m_idVideoVersion {-1}
Friends
class CDirectoryNode
Constructor & Destructor Documentation
CQueryParams()
CQueryParams::CQueryParams ()
References m_idActor, m_idAlbum, m_idContent, m_idCountry, m_idDirector, m_idEpisode, m_idGenre, m_idMovie, m_idMVideo, m_idSeason, m_idSet, m_idShow, m_idStudio, m_idTag, m_idYear, and UNKNOWN.
Member Function Documentation
GetActorId()
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetActorId () const inline
References m_idActor.
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMusicVideos::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeEpisodes::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows::GetContent(), and CVideoDbUrl::parse().
GetAlbumId()
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetAlbumId () const inline
References m_idAlbum.
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMusicVideos::GetContent(), and CVideoDbUrl::parse().
GetContentType()
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetContentType () const inline
References m_idContent.
Referenced by CGUIViewStateWindowVideoNav::AutoPlayNextItem(), anonymous_namespace{VideoDatabaseDirectory.cpp}::GetChildContentType(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped::GetChildType(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped::GetContent(), and XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeGrouped::GetContentType().
GetCountryId()
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetCountryId () const inline
References m_idCountry.
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMovies::GetContent(), XFILE::CVideoDatabaseDirectory::GetLabel(), and CVideoDbUrl::parse().
GetDirectorId()
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetDirectorId () const inline
References m_idDirector.
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMusicVideos::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeEpisodes::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows::GetContent(), and CVideoDbUrl::parse().
GetEpisodeId()
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetEpisodeId () const inline
References m_idEpisode.
Referenced by UPNP::CUPnPServer::Build(), CGUIDialogVideoInfo::CanDeleteVideoItem(), anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), UPNP::CUPnPServer::OnUpdateObject(), and CVideoDbUrl::parse().
GetGenreId()
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetGenreId () const inline
References m_idGenre.
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMusicVideos::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeEpisodes::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows::GetContent(), XFILE::CVideoDatabaseDirectory::GetLabel(), and CVideoDbUrl::parse().
GetMovieId()
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetMovieId () const inline
References m_idMovie.
Referenced by UPNP::CUPnPServer::Build(), CGUIDialogVideoInfo::CanDeleteVideoItem(), anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), CFileItem::GetVideoContentType(), CFileItem::LoadDetails(), UPNP::CUPnPServer::OnUpdateObject(), and CVideoDbUrl::parse().
GetMVideoId()
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetMVideoId () const inline
References m_idMVideo.
Referenced by UPNP::CUPnPServer::Build(), CGUIDialogVideoInfo::CanDeleteVideoItem(), CGUIViewStateWindowMusicNav::CGUIViewStateWindowMusicNav(), anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation(), CFileItem::LoadDetails(), UPNP::CUPnPServer::OnUpdateObject(), and CVideoDbUrl::parse().
GetSeason()
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetSeason () const inline
References m_idSeason.
Referenced by UPNP::CUPnPServer::Build(), CGUIDialogVideoInfo::CanDeleteVideoItem(), CGUIViewStateWindowVideoNav::CGUIViewStateWindowVideoNav(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeEpisodes::GetContent(), CGUIWindowVideoNav::GetDirectory(), anonymous_namespace{VideoUtils.cpp}::GetFolderItemResumeInformation(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetSeasonTitle(), and CVideoDbUrl::parse().
GetSetId()
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetSetId () const inline
References m_idSet.
Referenced by CGUIDialogVideoInfo::CanDeleteVideoItem(), CGUIViewStateWindowVideoNav::CGUIViewStateWindowVideoNav(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMovies::GetContent(), CGUIWindowVideoNav::GetDirectory(), anonymous_namespace{VideoUtils.cpp}::GetFolderItemResumeInformation(), CGUIWindowVideoBase::GetGroupedItems(), XFILE::CVideoDatabaseDirectory::GetLabel(), CFileItem::GetVideoContentType(), CGUIWindowVideoNav::OnDeleteItem(), CVideoDbUrl::parse(), and CGUIViewStateWindowVideoNav::SaveViewState().
GetStudioId()
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetStudioId () const inline
References m_idStudio.
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMusicVideos::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows::GetContent(), and CVideoDbUrl::parse().
GetTagId()
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetTagId () const inline
References m_idTag.
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMusicVideos::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows::GetContent(), and XFILE::CVideoDatabaseDirectory::GetLabel().
GetTvShowId()
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetTvShowId () const inline
References m_idShow.
Referenced by UPNP::CUPnPServer::Build(), CGUIDialogVideoInfo::CanDeleteVideoItem(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeEpisodes::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetContent(), CGUIWindowVideoNav::GetDirectory(), anonymous_namespace{VideoUtils.cpp}::GetFolderItemResumeInformation(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetSeasonTitle(), and CVideoDbUrl::parse().
GetVideoVersionId()
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetVideoVersionId () const inline
References m_idVideoVersion.
Referenced by UPNP::CUPnPServer::Build(), CGUIDialogVideoInfo::CanDeleteVideoItem(), CGUIWindowVideoBase::GetGroupedItems(), XFILE::CVideoDatabaseDirectory::GetLabel(), CFileItem::LoadDetails(), and CVideoDbUrl::parse().
GetYear()
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetYear () const inline
References m_idYear.
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMusicVideos::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeEpisodes::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeSeasons::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleMovies::GetContent(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNodeTitleTvShows::GetContent(), XFILE::CVideoDatabaseDirectory::GetLabel(), and CVideoDbUrl::parse().
SetQueryParam()
void CQueryParams::SetQueryParam (NODE_TYPE NodeType, const std::string & strNodeName) protected
References m_idActor, m_idAlbum, m_idContent, m_idCountry, m_idDirector, m_idEpisode, m_idGenre, m_idMovie, m_idMVideo, m_idSeason, m_idSet, m_idShow, m_idStudio, m_idTag, m_idVideoVersion, m_idYear, MOVIES, MUSICVIDEOS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_ACTOR, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_COUNTRY, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_DIRECTOR, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_EPISODES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_GENRE, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_INPROGRESS_TVSHOWS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_MUSICVIDEOS_ALBUM, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_OVERVIEW, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_EPISODES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_MOVIES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_RECENTLY_ADDED_MUSICVIDEOS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_SEASONS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_SETS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_STUDIO, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TAGS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MOVIES, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_MUSICVIDEOS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_TITLE_TVSHOWS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_VIDEOVERSIONS, XFILE::VIDEODATABASEDIRECTORY::NODE_TYPE_YEAR, and TVSHOWS.
Referenced by XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::CollectQueryParams().
Friends And Related Symbol Documentation
CDirectoryNode
friend class CDirectoryNode friend
Member Data Documentation
m_idActor
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::m_idActor private
Referenced by CQueryParams(), GetActorId(), and SetQueryParam().
m_idAlbum
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::m_idAlbum private
Referenced by CQueryParams(), GetAlbumId(), and SetQueryParam().
m_idContent
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::m_idContent private
Referenced by CQueryParams(), GetContentType(), and SetQueryParam().
m_idCountry
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::m_idCountry private
Referenced by CQueryParams(), GetCountryId(), and SetQueryParam().
m_idDirector
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::m_idDirector private
Referenced by CQueryParams(), GetDirectorId(), and SetQueryParam().
m_idEpisode
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::m_idEpisode private
Referenced by CQueryParams(), GetEpisodeId(), and SetQueryParam().
m_idGenre
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::m_idGenre private
Referenced by CQueryParams(), GetGenreId(), and SetQueryParam().
m_idMovie
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::m_idMovie private
Referenced by CQueryParams(), GetMovieId(), and SetQueryParam().
m_idMVideo
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::m_idMVideo private
Referenced by CQueryParams(), GetMVideoId(), and SetQueryParam().
m_idSeason
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::m_idSeason private
Referenced by CQueryParams(), GetSeason(), and SetQueryParam().
m_idSet
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::m_idSet private
Referenced by CQueryParams(), GetSetId(), and SetQueryParam().
m_idShow
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::m_idShow private
Referenced by CQueryParams(), GetTvShowId(), and SetQueryParam().
m_idStudio
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::m_idStudio private
Referenced by CQueryParams(), GetStudioId(), and SetQueryParam().
m_idTag
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::m_idTag private
Referenced by CQueryParams(), GetTagId(), and SetQueryParam().
m_idVideoVersion
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::m_idVideoVersion {-1} private
Referenced by GetVideoVersionId(), and SetQueryParam().
m_idYear
long XFILE::VIDEODATABASEDIRECTORY::CQueryParams::m_idYear private
Referenced by CQueryParams(), GetYear(), and SetQueryParam().
The documentation for this class was generated from the following files:
VideoDatabaseDirectory/QueryParams.h
VideoDatabaseDirectory/QueryParams.cpp