Kodi Documentation: CSettingBool Class Reference
CSettingBool Class Reference
Settings
Boolean setting implementation.
#include <Setting.h>
Public Member Functions
CSettingBool (const std::string &id, CSettingsManager *settingsManager=nullptr)
CSettingBool (const std::string &id, const CSettingBool &setting)
CSettingBool (const std::string &id, int label, bool value, CSettingsManager *settingsManager=nullptr)
~CSettingBool () override=default
std::shared_ptr< CSetting > Clone (const std::string &id) const override
void MergeDetails (const CSetting &other) override
bool Deserialize (const TiXmlNode *node, bool update=false) override
Deserializes the given XML node into the properties of the setting object.
bool FromString (const std::string &value) override
std::string ToString () const override
bool Equals (const std::string &value) const override
bool CheckValidity (const std::string &value) const override
void Reset () override
bool GetValue () const
bool SetValue (bool value)
bool GetDefault () const
void SetDefault (bool value)
Public Member Functions inherited from CTraitedSetting< bool, SettingType::Boolean >
SettingType GetType () const override
Public Member Functions inherited from CSetting
CSetting (const std::string &id, CSettingsManager *settingsManager=nullptr)
CSetting (const std::string &id, const CSetting &setting)
~CSetting () override=default
void MergeBasics (const CSetting &other)
bool IsEnabled () const
bool GetEnabled () const
void SetEnabled (bool enabled)
bool IsDefault () const
const std::string & GetParent () const
void SetParent (const std::string &parentSetting)
SettingLevel GetLevel () const
void SetLevel (SettingLevel level)
std::shared_ptr< const ISettingControl > GetControl () const
std::shared_ptr< ISettingControl > GetControl ()
void SetControl (std::shared_ptr< ISettingControl > control)
const SettingDependencies & GetDependencies () const
void SetDependencies (const SettingDependencies &dependencies)
const std::set< CSettingUpdate > & GetUpdates () const
void SetCallback (ISettingCallback *callback)
bool IsReference () const
const std::string & GetReferencedId () const
void SetReferencedId (const std::string &referencedId)
void MakeReference (const std::string &referencedId="")
bool GetVisible () const
bool IsVisible () const override
Whether the setting object is visible or hidden.
void OnSettingAction (const std::shared_ptr< const CSetting > &setting) override
The given setting has been activated.
Public Member Functions inherited from ISetting
ISetting (const std::string &id, CSettingsManager *settingsManager=nullptr)
Creates a new setting object with the given identifier.
virtual ~ISetting ()=default
const std::string & GetId () const
Gets the identifier of the setting object.
virtual void SetVisible (bool visible)
Sets the visibility state of the setting object.
int GetLabel () const
Gets the localizeable label ID of the setting group.
void SetLabel (int label)
Sets the localizeable label ID of the setting group.
int GetHelp () const
Gets the localizeable help ID of the setting group.
void SetHelp (int help)
Sets the localizeable help ID of the setting group.
virtual bool MeetsRequirements () const
Whether the setting object meets all necessary requirements.
virtual void CheckRequirements ()
Checks if the setting object meets all necessary requirements.
virtual void SetRequirementsMet (bool requirementsMet)
Sets whether the setting object meets all necessary requirements.
Private Member Functions
void copy (const CSettingBool &setting)
bool fromString (const std::string &strValue, bool &value) const
Private Attributes
bool m_value = DefaultValue
bool m_default = DefaultValue
Static Private Attributes
static constexpr Value DefaultValue = false
static Logger s_logger
Additional Inherited Members
Public Types inherited from CTraitedSetting< bool, SettingType::Boolean >
typedef bool Value
Static Public Member Functions inherited from CTraitedSetting< bool, SettingType::Boolean >
static SettingType Type ()
Static Public Member Functions inherited from CSetting
static bool DeserializeIdentification (const TiXmlNode *node, std::string &identification, bool &isReference)
Deserializes the given XML node to retrieve a setting object's identifier and whether the setting is a reference to another setting or not.
Static Public Member Functions inherited from ISetting
static bool DeserializeIdentification (const TiXmlNode *node, std::string &identification)
Deserializes the given XML node to retrieve a setting object's identifier.
Protected Member Functions inherited from CTraitedSetting< bool, SettingType::Boolean >
CTraitedSetting (const std::string &id, CSettingsManager *settingsManager=nullptr)
CTraitedSetting (const std::string &id, const CTraitedSetting &setting)
~CTraitedSetting () override=default
Protected Member Functions inherited from CSetting
bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting is being changed.
void OnSettingChanged (const std::shared_ptr< const CSetting > &setting) override
The value of the given setting has changed.
bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode) override
The given setting needs to be updated.
void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName) override
The given property of the given setting has changed.
void Copy (const CSetting &setting)
template<class TSetting >
std::shared_ptr< TSetting > shared_from_base ()
Protected Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
Static Protected Member Functions inherited from ISetting
static bool DeserializeIdentificationFromAttribute (const TiXmlNode *node, const std::string &attribute, std::string &identification)
Deserializes the given XML node to retrieve a setting object's identifier from the given attribute.
Protected Attributes inherited from CSetting
ISettingCallback * m_callback = nullptr
bool m_enabled = true
std::string m_parentSetting
SettingLevel m_level = SettingLevel::Standard
std::shared_ptr< ISettingControl > m_control
SettingDependencies m_dependencies
std::set< CSettingUpdate > m_updates
bool m_changed = false
CSharedSection m_critical
std::string m_referencedId
Protected Attributes inherited from ISetting
std::string m_id
CSettingsManager * m_settingsManager
Static Protected Attributes inherited from ISetting
static constexpr int DefaultLabel = -1
Detailed Description
Boolean setting implementation.
See also
CSetting
Constructor & Destructor Documentation
CSettingBool() [1/3]
CSettingBool::CSettingBool (const std::string & id, CSettingsManager * settingsManager = nullptr)
CSettingBool() [2/3]
CSettingBool::CSettingBool (const std::string & id, const CSettingBool & setting)
References copy().
CSettingBool() [3/3]
CSettingBool::CSettingBool (const std::string & id, int label, bool value, CSettingsManager * settingsManager = nullptr)
References CLog::GetLogger(), CServiceBroker::GetLogging(), label, s_logger, and ISetting::SetLabel().
~CSettingBool()
CSettingBool::~CSettingBool () override default
Member Function Documentation
CheckValidity()
bool CSettingBool::CheckValidity (const std::string & value) const override virtual
Implements CSetting.
References fromString(), and value.
Clone()
SettingPtr CSettingBool::Clone (const std::string & id) const override virtual
Implements CSetting.
copy()
void CSettingBool::copy (const CSettingBool & setting) private
References CSetting::Copy(), m_default, and m_value.
Referenced by CSettingBool().
Deserialize()
bool CSettingBool::Deserialize (const TiXmlNode * node, bool update = false) override virtual
Deserializes the given XML node into the properties of the setting object.
If the update parameter is true, the checks for mandatory properties are skipped and values are only updated.
Parameters
node XML node containing the properties of the setting object
update Whether to perform checks for mandatory properties or not
Returns
True if deserialization was successful, false otherwise
Reimplemented from CSetting.
References CSetting::Deserialize(), XMLUtils::GetBoolean(), CSetting::m_critical, m_default, ISetting::m_id, m_value, node, s_logger, SETTING_XML_ELM_DEFAULT, and value.
Equals()
bool CSettingBool::Equals (const std::string & value) const override virtual
Implements CSetting.
References fromString(), m_value, and value.
fromString()
bool CSettingBool::fromString (const std::string & strValue, bool & value) const private
References value.
Referenced by CheckValidity(), Equals(), and FromString().
FromString()
bool CSettingBool::FromString (const std::string & value) override virtual
Implements CSetting.
References fromString(), SetValue(), and value.
GetDefault()
bool CSettingBool::GetDefault () const inline
References m_default.
GetValue()
bool CSettingBool::GetValue () const inline
References CSetting::m_critical, and m_value.
Referenced by CApplicationVolumeHandling::OnSettingChanged().
MergeDetails()
void CSettingBool::MergeDetails (const CSetting & other) override virtual
Implements CSetting.
References Boolean, CSetting::GetType(), m_default, and m_value.
Reset()
void CSettingBool::Reset () inline override virtual
Implements CSetting.
References m_default, and SetValue().
SetDefault()
void CSettingBool::SetDefault (bool value)
References CSetting::m_changed, CSetting::m_critical, m_default, m_value, and value.
SetValue()
bool CSettingBool::SetValue (bool value)
References CSetting::m_changed, CSetting::m_critical, m_default, m_value, CSetting::OnSettingChanged(), CSetting::OnSettingChanging(), and value.
Referenced by FromString(), and Reset().
ToString()
std::string CSettingBool::ToString () const override virtual
Implements CSetting.
References m_value.
Member Data Documentation
DefaultValue
constexpr Value CSettingBool::DefaultValue = false static constexpr private
m_default
bool CSettingBool::m_default = DefaultValue private
Referenced by copy(), Deserialize(), GetDefault(), MergeDetails(), Reset(), SetDefault(), and SetValue().
m_value
bool CSettingBool::m_value = DefaultValue private
Referenced by copy(), Deserialize(), Equals(), GetValue(), MergeDetails(), SetDefault(), SetValue(), and ToString().
s_logger
Logger CSettingBool::s_logger static private
Referenced by CSettingBool(), and Deserialize().
The documentation for this class was generated from the following files:
Setting.h
Setting.cpp