Kodi Documentation: CXRandR Class Reference
CXRandR Class Reference
#include <XRandR.h>
Public Member Functions
CXRandR (bool query=false)
bool Query (bool force=false, bool ignoreoff=true)
bool Query (bool force, int screennum, bool ignoreoff=true)
std::vector< XOutput > GetModes (void)
XMode GetCurrentMode (const std::string &outputName)
XMode GetPreferredMode (const std::string &outputName)
XOutput * GetOutput (const std::string &outputName)
bool SetMode (const XOutput &output, const XMode &mode)
void LoadCustomModeLinesToAllOutputs (void)
void SaveState ()
void SetNumScreens (unsigned int num)
bool IsOutputConnected (const std::string &name)
bool TurnOffOutput (const std::string &name)
bool TurnOnOutput (const std::string &name)
int GetCrtc (int x, int y, float &hz)
Private Attributes
bool m_bInit
std::vector< XOutput > m_outputs
std::string m_currentOutput
std::string m_currentMode
unsigned int m_numScreens
Constructor & Destructor Documentation
CXRandR()
CXRandR::CXRandR (bool query = false) explicit
References m_bInit, m_numScreens, and Query().
Member Function Documentation
GetCrtc()
int CXRandR::GetCrtc (int x, int y, float & hz)
References XOutput::crtc, and m_outputs.
Referenced by KODI::WINDOWING::X11::CWinSystemX11::UpdateCrtc().
GetCurrentMode()
XMode CXRandR::GetCurrentMode (const std::string & outputName)
References m_outputs, name, and Query().
Referenced by KODI::WINDOWING::X11::CWinSystemX11::FinishWindowResize(), KODI::WINDOWING::X11::CWinSystemX11::RecreateWindow(), KODI::WINDOWING::X11::CWinSystemX11::ResizeWindow(), KODI::WINDOWING::X11::CWinSystemX11::SetFullScreen(), TurnOnOutput(), and KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions().
GetModes()
std::vector< XOutput > CXRandR::GetModes (void)
References m_outputs, and Query().
Referenced by KODI::WINDOWING::X11::CWinSystemX11::FinishWindowResize(), KODI::WINDOWING::X11::CWinSystemX11::GetConnectedOutputs(), KODI::WINDOWING::X11::CWinSystemX11::ResizeWindow(), and KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions().
GetOutput()
XOutput * CXRandR::GetOutput (const std::string & outputName)
References m_outputs, name, and Query().
Referenced by KODI::WINDOWING::X11::CWinSystemX11::FinishWindowResize(), KODI::WINDOWING::X11::CWinSystemX11::HasCalibration(), KODI::WINDOWING::X11::CWinSystemX11::RecreateWindow(), KODI::WINDOWING::X11::CWinSystemX11::ResizeWindow(), KODI::WINDOWING::X11::CWinSystemX11::SetWindow(), TurnOffOutput(), TurnOnOutput(), and KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions().
GetPreferredMode()
XMode CXRandR::GetPreferredMode (const std::string & outputName)
References m_outputs, name, and Query().
Referenced by KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions().
IsOutputConnected()
bool CXRandR::IsOutputConnected (const std::string & name)
References m_outputs, name, and Query().
LoadCustomModeLinesToAllOutputs()
void CXRandR::LoadCustomModeLinesToAllOutputs (void)
Todo:
ERROR
References CCompileInfo::GetAppName(), CXBMCTinyXML2::LoadFile(), CLog::Log(), LOGERROR, m_outputs, name, and Query().
Query() [1/2]
bool CXRandR::Query (bool force, int screennum, bool ignoreoff = true)
Todo:
ERROR
References XOutput::crtc, CCompileInfo::GetAppName(), XMode::h, XOutput::h, XOutput::hmm, XMode::hz, XMode::id, XOutput::isConnected, XMode::isCurrent, XMode::isPreferred, XOutput::isRotated, CXBMCTinyXML2::LoadFile(), CLog::Log(), LOGERROR, LOGWARNING, m_outputs, XOutput::modes, XMode::name, XOutput::name, XOutput::screen, XMode::w, XOutput::w, XOutput::wmm, XOutput::x, and XOutput::y.
Query() [2/2]
bool CXRandR::Query (bool force = false, bool ignoreoff = true)
References m_bInit, m_numScreens, m_outputs, Query(), and success.
Referenced by CXRandR(), KODI::WINDOWING::X11::CWinSystemX11::GetConnectedOutputs(), GetCurrentMode(), GetModes(), GetOutput(), GetPreferredMode(), IsOutputConnected(), LoadCustomModeLinesToAllOutputs(), KODI::WINDOWING::X11::CWinSystemX11::NotifyXRREvent(), Query(), SaveState(), SetMode(), TurnOnOutput(), and KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions().
SaveState()
void CXRandR::SaveState ()
References Query().
SetMode()
bool CXRandR::SetMode (const XOutput & output, const XMode & mode)
References CCompileInfo::GetAppName(), XMode::h, XMode::hz, XMode::id, CLog::Log(), LOGERROR, LOGINFO, LOGWARNING, m_currentMode, m_currentOutput, m_outputs, XOutput::modes, name, XOutput::name, Query(), XOutput::screen, and XMode::w.
Referenced by KODI::WINDOWING::X11::CWinSystemX11::DestroyWindowSystem(), KODI::WINDOWING::X11::CWinSystemX11::SetFullScreen(), and TurnOnOutput().
SetNumScreens()
void CXRandR::SetNumScreens (unsigned int num)
References m_bInit, and m_numScreens.
Referenced by KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions().
TurnOffOutput()
bool CXRandR::TurnOffOutput (const std::string & name)
References CCompileInfo::GetAppName(), GetOutput(), name, and XOutput::screen.
Referenced by KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions().
TurnOnOutput()
bool CXRandR::TurnOnOutput (const std::string & name)
References GetCurrentMode(), GetOutput(), XOutput::h, XMode::isCurrent, XMode::isPreferred, m_outputs, name, XOutput::name, Query(), SetMode(), and KODI::TIME::Sleep().
Referenced by KODI::WINDOWING::X11::CWinSystemX11::UpdateResolutions().
Member Data Documentation
m_bInit
bool CXRandR::m_bInit private
Referenced by CXRandR(), Query(), and SetNumScreens().
m_currentMode
std::string CXRandR::m_currentMode private
Referenced by SetMode().
m_currentOutput
std::string CXRandR::m_currentOutput private
Referenced by SetMode().
m_numScreens
unsigned int CXRandR::m_numScreens private
Referenced by CXRandR(), Query(), and SetNumScreens().
m_outputs
std::vector<XOutput> CXRandR::m_outputs private
Referenced by GetCrtc(), GetCurrentMode(), GetModes(), GetOutput(), GetPreferredMode(), IsOutputConnected(), LoadCustomModeLinesToAllOutputs(), Query(), Query(), SetMode(), and TurnOnOutput().
The documentation for this class was generated from the following files:
XRandR.h
XRandR.cpp