Kodi Documentation: thread Class Reference
thread Class Reference
#include <TestHelpers.h>
Public Member Functions
thread (IRunnable &runnable)
void join ()
bool timed_join (std::chrono::milliseconds duration)
Private Attributes
std::unique_ptr< CThread > cthread
Constructor & Destructor Documentation
thread()
thread::thread (IRunnable & runnable) inline explicit
References cthread.
Member Function Documentation
join()
void thread::join () inline
References cthread.
timed_join()
bool thread::timed_join (std::chrono::milliseconds duration) inline
References cthread.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
Member Data Documentation
cthread
std::unique_ptr<CThread> thread::cthread private
Referenced by join(), thread(), and timed_join().
The documentation for this class was generated from the following file:
TestHelpers.h