Kodi Documentation: CGUIControlListSetting Class Reference
CGUIControlListSetting Class Reference
#include <GUIControlSettings.h>
Public Member Functions
CGUIControlListSetting (CGUIButtonControl *pButton, int id, std::shared_ptr< CSetting > pSetting, ILocalizer *localizer)
~CGUIControlListSetting () override
CGUIControl * GetControl () override
bool OnClick () override
void Clear () override
Clears the attached control.
Public Member Functions inherited from CGUIControlBaseSetting
CGUIControlBaseSetting (int id, std::shared_ptr< CSetting > pSetting, ILocalizer *localizer)
~CGUIControlBaseSetting () override=default
int GetID () const
std::shared_ptr< CSetting > GetSetting ()
void SetDelayed ()
Specifies that this setting should update after a delay Useful for settings that have options to navigate through and may take a while, or require additional input to update once the final setting is chosen. Settings default to updating instantly.
bool IsDelayed () const
Returns whether this setting should have delayed update.
bool IsEnabled () const
Returns whether this setting is enabled or disabled This state is independent of the real enabled state of a setting control but represents the enabled state of the setting itself based on specific conditions.
bool IsValid () const
Returns whether the setting's value is valid or not.
void SetValid (bool valid)
void UpdateFromControl ()
void UpdateFromSetting (bool updateDisplayOnly=false)
Protected Member Functions
void Update (bool fromControl, bool updateDisplayOnly) override
Protected Member Functions inherited from CGUIControlBaseSetting
std::string Localize (std::uint32_t code) const override
Protected Member Functions inherited from ILocalizer
ILocalizer ()=default
virtual ~ILocalizer ()=default
Private Member Functions
bool GetItems (const std::shared_ptr< const CSetting > &setting, CFileItemList &items, bool updateItems) const
bool GetIntegerItems (const std::shared_ptr< const CSetting > &setting, CFileItemList &items, bool updateItems) const
bool GetStringItems (const std::shared_ptr< const CSetting > &setting, CFileItemList &items, bool updateItems) const
Private Attributes
CGUIButtonControl * m_pButton
Additional Inherited Members
Protected Attributes inherited from CGUIControlBaseSetting
int m_id
std::shared_ptr< CSetting > m_pSetting
ILocalizer * m_localizer
bool m_delayed = false
bool m_valid = true
Constructor & Destructor Documentation
CGUIControlListSetting()
CGUIControlListSetting::CGUIControlListSetting (CGUIButtonControl * pButton, int id, std::shared_ptr< CSetting > pSetting, ILocalizer * localizer)
References m_pButton, and CGUIControl::SetID().
~CGUIControlListSetting()
CGUIControlListSetting::~CGUIControlListSetting () override default
Member Function Documentation
Clear()
void CGUIControlListSetting::Clear () inline override virtual
Clears the attached control.
Implements CGUIControlBaseSetting.
References m_pButton.
GetControl()
CGUIControl * CGUIControlListSetting::GetControl () inline override virtual
Reimplemented from CGUIControlBaseSetting.
References m_pButton.
GetIntegerItems()
bool CGUIControlListSetting::GetIntegerItems (const std::shared_ptr< const CSetting > & setting, CFileItemList & items, bool updateItems) const private
References CFileItemList::Add(), GetFileItem(), GetIntegerOptions(), and CGUIControlBaseSetting::m_localizer.
Referenced by GetItems().
GetItems()
bool CGUIControlListSetting::GetItems (const std::shared_ptr< const CSetting > & setting, CFileItemList & items, bool updateItems) const private
References GetIntegerItems(), GetStringItems(), Integer, List, and String.
Referenced by OnClick(), and Update().
GetStringItems()
bool CGUIControlListSetting::GetStringItems (const std::shared_ptr< const CSetting > & setting, CFileItemList & items, bool updateItems) const private
References CFileItemList::Add(), GetFileItem(), GetStringOptions(), and CGUIControlBaseSetting::m_localizer.
Referenced by GetItems().
OnClick()
bool CGUIControlListSetting::OnClick () override virtual
Reimplemented from CGUIControlBaseSetting.
References CGUIDialogSelect::EnableButton2(), CServiceBroker::GetGUI(), GetItems(), CSettingUtils::GetList(), CGUIDialogSelect::GetSelectedItems(), CGUIComponent::GetWindowManager(), Integer, CGUIDialogSelect::IsButton2Pressed(), CGUIDialogBoxBase::IsConfirmed(), CGUIControlBaseSetting::IsValid(), List, CGUIControlBaseSetting::Localize(), m_pButton, CGUIControlBaseSetting::m_pSetting, CGUIDialog::Open(), CGUIDialogSelect::Reset(), CGUIDialogBoxBase::SetHeading(), CGUIDialogSelect::SetItems(), CSettingUtils::SetList(), CGUIDialogSelect::SetMultiSelection(), CGUIDialogSelect::SetUseDetails(), CGUIControlBaseSetting::SetValid(), CGUIKeyboardFactory::ShowAndGetInput(), String, CGUIControlBaseSetting::UpdateFromSetting(), value, values, and WINDOW_DIALOG_SELECT.
Update()
void CGUIControlListSetting::Update (bool fromControl, bool updateDisplayOnly) override protected virtual
Reimplemented from CGUIControlBaseSetting.
References GetItems(), index(), CGUIControl::IsDisabled(), List, m_pButton, CGUIControlBaseSetting::m_pSetting, CGUIControl::SetEnabled(), CGUIButtonControl::SetLabel2(), String, and CGUIControlBaseSetting::Update().
Member Data Documentation
m_pButton
CGUIButtonControl* CGUIControlListSetting::m_pButton private
Referenced by CGUIControlListSetting(), Clear(), GetControl(), OnClick(), and Update().
The documentation for this class was generated from the following files:
GUIControlSettings.h
GUIControlSettings.cpp