Kodi Documentation: jni::CJNIXBMCAudioManagerOnAudioFocusChangeListener Class Reference
jni::CJNIXBMCAudioManagerOnAudioFocusChangeListener Class Reference
#include <JNIXBMCAudioManagerOnAudioFocusChangeListener.h>
Public Member Functions
CJNIXBMCAudioManagerOnAudioFocusChangeListener ()
CJNIXBMCAudioManagerOnAudioFocusChangeListener (const CJNIXBMCAudioManagerOnAudioFocusChangeListener &other)
CJNIXBMCAudioManagerOnAudioFocusChangeListener (const jni::jhobject &object)
~CJNIXBMCAudioManagerOnAudioFocusChangeListener () override
void onAudioFocusChange (int focusChange) override
Static Public Member Functions
static void RegisterNatives (JNIEnv *env)
Static Protected Member Functions
static void _onAudioFocusChange (JNIEnv *env, jobject thiz, jint focusChange)
Constructor & Destructor Documentation
CJNIXBMCAudioManagerOnAudioFocusChangeListener() [1/3]
CJNIXBMCAudioManagerOnAudioFocusChangeListener::CJNIXBMCAudioManagerOnAudioFocusChangeListener ()
References s_className.
CJNIXBMCAudioManagerOnAudioFocusChangeListener() [2/3]
CJNIXBMCAudioManagerOnAudioFocusChangeListener::CJNIXBMCAudioManagerOnAudioFocusChangeListener (const CJNIXBMCAudioManagerOnAudioFocusChangeListener & other)
CJNIXBMCAudioManagerOnAudioFocusChangeListener() [3/3]
jni::CJNIXBMCAudioManagerOnAudioFocusChangeListener::CJNIXBMCAudioManagerOnAudioFocusChangeListener (const jni::jhobject & object) inline explicit
~CJNIXBMCAudioManagerOnAudioFocusChangeListener()
CJNIXBMCAudioManagerOnAudioFocusChangeListener::~CJNIXBMCAudioManagerOnAudioFocusChangeListener () override
Member Function Documentation
_onAudioFocusChange()
void CJNIXBMCAudioManagerOnAudioFocusChangeListener::_onAudioFocusChange (JNIEnv * env, jobject thiz, jint focusChange) static protected
References onAudioFocusChange(), and void().
Referenced by RegisterNatives().
onAudioFocusChange()
void CJNIXBMCAudioManagerOnAudioFocusChangeListener::onAudioFocusChange (int focusChange) override
References CXBMCApp::Get(), and CXBMCApp::onAudioFocusChange().
Referenced by _onAudioFocusChange().
RegisterNatives()
void CJNIXBMCAudioManagerOnAudioFocusChangeListener::RegisterNatives (JNIEnv * env) static
References _onAudioFocusChange(), and s_className.
Referenced by JNI_OnLoad().
The documentation for this class was generated from the following files:
JNIXBMCAudioManagerOnAudioFocusChangeListener.h
JNIXBMCAudioManagerOnAudioFocusChangeListener.cpp