Kodi Documentation: MEDIA_DETECT::CCdInfo Class Reference
MEDIA_DETECT::CCdInfo Class Reference
#include <cdioSupport.h>
Public Member Functions
CCdInfo ()
trackinfo GetTrackInformation (int nTrack)
const xbmc_cdtext_t & GetDiscCDTextInformation () const
bool HasDataTracks ()
bool HasAudioTracks ()
int GetFirstTrack ()
int GetTrackCount ()
int GetFirstAudioTrack ()
int GetFirstDataTrack ()
int GetDataTrackCount ()
int GetAudioTrackCount ()
uint32_t GetCddbDiscId ()
int GetDiscLength ()
const std::string & GetDiscLabel () const
bool IsIso9660 (int nTrack)
bool IsJoliet (int nTrack)
int GetJolietLevel (int nTrack)
int GetIsoSize (int nTrack)
bool IsRockridge (int nTrack)
bool IsIso9660Interactive (int nTrack)
bool IsHighSierra (int nTrack)
bool IsCDInteractive (int nTrack)
bool IsHFS (int nTrack)
bool IsISOHFS (int nTrack)
bool IsISOUDF (int nTrack)
bool IsUFS (int nTrack)
bool IsEXT2 (int nTrack)
bool Is3DO (int nTrack)
bool IsMixedMode (int nTrack)
bool IsXA (int nTrack)
bool IsMultiSession (int nTrack)
int GetMultisessionOffset (int nTrack)
bool IsHiddenTrack (int nTrack)
bool IsPhotoCd (int nTrack)
bool IsCdTv (int nTrack)
bool IsCDExtra (int nTrack)
bool IsBootable (int nTrack)
bool IsVideoCd (int nTrack)
bool IsChaojiVideoCD (int nTrack)
bool IsAudio (int nTrack)
bool IsUDF (int nTrack)
bool IsValidFs ()
void SetFirstTrack (int nTrack)
void SetTrackCount (int nCount)
void SetFirstAudioTrack (int nTrack)
void SetFirstDataTrack (int nTrack)
void SetDataTrackCount (int nCount)
void SetAudioTrackCount (int nCount)
void SetTrackInformation (int nTrack, trackinfo nInfo)
void SetDiscCDTextInformation (xbmc_cdtext_t cdtext)
void SetCddbDiscId (uint32_t ulCddbDiscId)
void SetDiscLength (int nLength)
bool HasCDDBInfo ()
void SetNoCDDBInfo ()
void SetDiscLabel (const std::string &strDiscLabel)
Private Attributes
int m_nFirstData
int m_nNumData
int m_nFirstAudio
int m_nNumAudio
int m_nNumTrack
int m_nFirstTrack
trackinfo m_ti [100]
uint32_t m_ulCddbDiscId
int m_nLength
bool m_bHasCDDBInfo
std::string m_strDiscLabel
xbmc_cdtext_t m_cdtext
Constructor & Destructor Documentation
CCdInfo()
MEDIA_DETECT::CCdInfo::CCdInfo () inline
References m_bHasCDDBInfo, m_nFirstAudio, m_nFirstData, m_nFirstTrack, m_nLength, m_nNumAudio, m_nNumData, and m_nNumTrack.
Member Function Documentation
GetAudioTrackCount()
int MEDIA_DETECT::CCdInfo::GetAudioTrackCount () inline
References m_nNumAudio.
GetCddbDiscId()
uint32_t MEDIA_DETECT::CCdInfo::GetCddbDiscId () inline
References m_ulCddbDiscId.
Referenced by CDDB::Xcddb::isCDCached(), CMusicDatabase::LookupCDDBInfo(), CDDB::Xcddb::queryCDinfo(), and CDDB::Xcddb::queryCDinfo().
GetDataTrackCount()
int MEDIA_DETECT::CCdInfo::GetDataTrackCount () inline
References m_nNumData.
GetDiscCDTextInformation()
const xbmc_cdtext_t & MEDIA_DETECT::CCdInfo::GetDiscCDTextInformation () const inline
References m_cdtext.
Referenced by MUSIC_INFO::CMusicInfoTagLoaderCDDA::Load().
GetDiscLabel()
const std::string & MEDIA_DETECT::CCdInfo::GetDiscLabel () const inline
References m_strDiscLabel.
GetDiscLength()
int MEDIA_DETECT::CCdInfo::GetDiscLength () inline
References m_nLength.
Referenced by CDDB::Xcddb::queryCDinfo().
GetFirstAudioTrack()
int MEDIA_DETECT::CCdInfo::GetFirstAudioTrack () inline
References m_nFirstAudio.
GetFirstDataTrack()
int MEDIA_DETECT::CCdInfo::GetFirstDataTrack () inline
References m_nFirstData.
GetFirstTrack()
int MEDIA_DETECT::CCdInfo::GetFirstTrack () inline
References m_nFirstTrack.
GetIsoSize()
int MEDIA_DETECT::CCdInfo::GetIsoSize (int nTrack) inline
References MEDIA_DETECT::TRACKINFO::isofs_size, and m_ti.
GetJolietLevel()
int MEDIA_DETECT::CCdInfo::GetJolietLevel (int nTrack) inline
References m_ti, and MEDIA_DETECT::TRACKINFO::nJolietLevel.
GetMultisessionOffset()
int MEDIA_DETECT::CCdInfo::GetMultisessionOffset (int nTrack) inline
References m_ti, and MEDIA_DETECT::TRACKINFO::ms_offset.
GetTrackCount()
int MEDIA_DETECT::CCdInfo::GetTrackCount () inline
References m_nNumTrack.
Referenced by XFILE::CCDDADirectory::GetDirectory(), CMusicDatabase::LookupCDDBInfo(), and CDDB::Xcddb::queryCDinfo().
GetTrackInformation()
trackinfo MEDIA_DETECT::CCdInfo::GetTrackInformation (int nTrack) inline
References m_ti.
Referenced by MUSIC_INFO::CMusicInfoTagLoaderCDDA::Load(), and CDDB::Xcddb::queryCDinfo().
HasAudioTracks()
bool MEDIA_DETECT::CCdInfo::HasAudioTracks () inline
References m_nNumAudio.
HasCDDBInfo()
bool MEDIA_DETECT::CCdInfo::HasCDDBInfo () inline
References m_bHasCDDBInfo.
Referenced by MUSIC_INFO::CMusicInfoTagLoaderCDDA::Load(), and CMusicDatabase::LookupCDDBInfo().
HasDataTracks()
bool MEDIA_DETECT::CCdInfo::HasDataTracks () inline
References m_nNumData.
Is3DO()
bool MEDIA_DETECT::CCdInfo::Is3DO (int nTrack) inline
References FS_3DO, FS_MASK, and m_ti.
IsAudio()
bool MEDIA_DETECT::CCdInfo::IsAudio (int nTrack) inline
References FS_MASK, FS_NO_DATA, and m_ti.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), CGUIWindowMusicBase::GetContextButtons(), CGUIWindowMusicNav::GetContextButtons(), XFILE::CCDDADirectory::GetDirectory(), CMediaManager::IsAudio(), IsValidFs(), and KODI::CDRIP::CCDDARipper::RipCD().
IsBootable()
bool MEDIA_DETECT::CCdInfo::IsBootable (int nTrack) inline
References BOOTABLE, and m_ti.
IsCDExtra()
bool MEDIA_DETECT::CCdInfo::IsCDExtra (int nTrack) inline
References m_nFirstData.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), CGUIWindowMusicBase::GetContextButtons(), and CGUIWindowMusicNav::GetContextButtons().
IsCDInteractive()
bool MEDIA_DETECT::CCdInfo::IsCDInteractive (int nTrack) inline
References FS_INTERACTIVE, FS_MASK, and m_ti.
IsCdTv()
bool MEDIA_DETECT::CCdInfo::IsCdTv (int nTrack) inline
References CDTV, and m_ti.
IsChaojiVideoCD()
bool MEDIA_DETECT::CCdInfo::IsChaojiVideoCD (int nTrack) inline
References CVD, and m_ti.
IsEXT2()
bool MEDIA_DETECT::CCdInfo::IsEXT2 (int nTrack) inline
References FS_EXT2, FS_MASK, and m_ti.
IsHFS()
bool MEDIA_DETECT::CCdInfo::IsHFS (int nTrack) inline
References FS_HFS, FS_MASK, and m_ti.
IsHiddenTrack()
bool MEDIA_DETECT::CCdInfo::IsHiddenTrack (int nTrack) inline
References HIDDEN_TRACK, and m_ti.
IsHighSierra()
bool MEDIA_DETECT::CCdInfo::IsHighSierra (int nTrack) inline
References FS_HIGH_SIERRA, FS_MASK, and m_ti.
IsIso9660()
bool MEDIA_DETECT::CCdInfo::IsIso9660 (int nTrack) inline
References FS_ISO_9660, FS_MASK, and m_ti.
Referenced by IsValidFs().
IsIso9660Interactive()
bool MEDIA_DETECT::CCdInfo::IsIso9660Interactive (int nTrack) inline
References FS_ISO_9660_INTERACTIVE, FS_MASK, and m_ti.
Referenced by IsValidFs().
IsISOHFS()
bool MEDIA_DETECT::CCdInfo::IsISOHFS (int nTrack) inline
References FS_ISO_HFS, FS_MASK, and m_ti.
Referenced by IsValidFs().
IsISOUDF()
bool MEDIA_DETECT::CCdInfo::IsISOUDF (int nTrack) inline
References FS_ISO_UDF, FS_MASK, and m_ti.
Referenced by IsValidFs().
IsJoliet()
bool MEDIA_DETECT::CCdInfo::IsJoliet (int nTrack) inline
References JOLIET, and m_ti.
IsMixedMode()
bool MEDIA_DETECT::CCdInfo::IsMixedMode (int nTrack) inline
References m_nFirstData, and m_nNumAudio.
Referenced by KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), CGUIWindowMusicBase::GetContextButtons(), and CGUIWindowMusicNav::GetContextButtons().
IsMultiSession()
bool MEDIA_DETECT::CCdInfo::IsMultiSession (int nTrack) inline
References m_ti, and MULTISESSION.
IsPhotoCd()
bool MEDIA_DETECT::CCdInfo::IsPhotoCd (int nTrack) inline
References m_ti, and PHOTO_CD.
IsRockridge()
bool MEDIA_DETECT::CCdInfo::IsRockridge (int nTrack) inline
References m_ti, and ROCKRIDGE.
IsUDF()
bool MEDIA_DETECT::CCdInfo::IsUDF (int nTrack) inline
References FS_MASK, FS_UDF, and m_ti.
Referenced by IsValidFs().
IsUFS()
bool MEDIA_DETECT::CCdInfo::IsUFS (int nTrack) inline
References FS_MASK, FS_UFS, and m_ti.
IsValidFs()
bool MEDIA_DETECT::CCdInfo::IsValidFs () inline
References IsAudio(), IsIso9660(), IsIso9660Interactive(), IsISOHFS(), IsISOUDF(), and IsUDF().
IsVideoCd()
bool MEDIA_DETECT::CCdInfo::IsVideoCd (int nTrack) inline
References m_nNumAudio, m_ti, and VIDEOCDI.
Referenced by CUtil::GetDVDDriveIcon().
IsXA()
bool MEDIA_DETECT::CCdInfo::IsXA (int nTrack) inline
References m_ti, and XA.
SetAudioTrackCount()
void MEDIA_DETECT::CCdInfo::SetAudioTrackCount (int nCount) inline
References m_nNumAudio.
SetCddbDiscId()
void MEDIA_DETECT::CCdInfo::SetCddbDiscId (uint32_t ulCddbDiscId) inline
References m_ulCddbDiscId.
SetDataTrackCount()
void MEDIA_DETECT::CCdInfo::SetDataTrackCount (int nCount) inline
References m_nNumData.
SetDiscCDTextInformation()
void MEDIA_DETECT::CCdInfo::SetDiscCDTextInformation (xbmc_cdtext_t cdtext) inline
References m_cdtext.
SetDiscLabel()
void MEDIA_DETECT::CCdInfo::SetDiscLabel (const std::string & strDiscLabel) inline
References m_strDiscLabel.
SetDiscLength()
void MEDIA_DETECT::CCdInfo::SetDiscLength (int nLength) inline
References m_nLength.
SetFirstAudioTrack()
void MEDIA_DETECT::CCdInfo::SetFirstAudioTrack (int nTrack) inline
References m_nFirstAudio.
SetFirstDataTrack()
void MEDIA_DETECT::CCdInfo::SetFirstDataTrack (int nTrack) inline
References m_nFirstData.
SetFirstTrack()
void MEDIA_DETECT::CCdInfo::SetFirstTrack (int nTrack) inline
References m_nFirstTrack.
Referenced by MEDIA_DETECT::CCdIoSupport::GetCdInfo().
SetNoCDDBInfo()
void MEDIA_DETECT::CCdInfo::SetNoCDDBInfo () inline
References m_bHasCDDBInfo.
Referenced by CMusicDatabase::LookupCDDBInfo().
SetTrackCount()
void MEDIA_DETECT::CCdInfo::SetTrackCount (int nCount) inline
References m_nNumTrack.
SetTrackInformation()
void MEDIA_DETECT::CCdInfo::SetTrackInformation (int nTrack, trackinfo nInfo) inline
References m_ti.
Member Data Documentation
m_bHasCDDBInfo
bool MEDIA_DETECT::CCdInfo::m_bHasCDDBInfo private
Referenced by CCdInfo(), HasCDDBInfo(), and SetNoCDDBInfo().
m_cdtext
xbmc_cdtext_t MEDIA_DETECT::CCdInfo::m_cdtext private
Referenced by GetDiscCDTextInformation(), and SetDiscCDTextInformation().
m_nFirstAudio
int MEDIA_DETECT::CCdInfo::m_nFirstAudio private
Referenced by CCdInfo(), GetFirstAudioTrack(), and SetFirstAudioTrack().
m_nFirstData
int MEDIA_DETECT::CCdInfo::m_nFirstData private
Referenced by CCdInfo(), GetFirstDataTrack(), IsCDExtra(), IsMixedMode(), and SetFirstDataTrack().
m_nFirstTrack
int MEDIA_DETECT::CCdInfo::m_nFirstTrack private
Referenced by CCdInfo(), GetFirstTrack(), and SetFirstTrack().
m_nLength
int MEDIA_DETECT::CCdInfo::m_nLength private
Referenced by CCdInfo(), GetDiscLength(), and SetDiscLength().
m_nNumAudio
int MEDIA_DETECT::CCdInfo::m_nNumAudio private
Referenced by CCdInfo(), GetAudioTrackCount(), HasAudioTracks(), IsMixedMode(), IsVideoCd(), and SetAudioTrackCount().
m_nNumData
int MEDIA_DETECT::CCdInfo::m_nNumData private
Referenced by CCdInfo(), GetDataTrackCount(), HasDataTracks(), and SetDataTrackCount().
m_nNumTrack
int MEDIA_DETECT::CCdInfo::m_nNumTrack private
Referenced by CCdInfo(), GetTrackCount(), and SetTrackCount().
m_strDiscLabel
std::string MEDIA_DETECT::CCdInfo::m_strDiscLabel private
Referenced by GetDiscLabel(), and SetDiscLabel().
m_ti
trackinfo MEDIA_DETECT::CCdInfo::m_ti[100] private
Referenced by GetIsoSize(), GetJolietLevel(), GetMultisessionOffset(), GetTrackInformation(), Is3DO(), IsAudio(), IsBootable(), IsCDInteractive(), IsCdTv(), IsChaojiVideoCD(), IsEXT2(), IsHFS(), IsHiddenTrack(), IsHighSierra(), IsIso9660(), IsIso9660Interactive(), IsISOHFS(), IsISOUDF(), IsJoliet(), IsMultiSession(), IsPhotoCd(), IsRockridge(), IsUDF(), IsUFS(), IsVideoCd(), IsXA(), and SetTrackInformation().
m_ulCddbDiscId
uint32_t MEDIA_DETECT::CCdInfo::m_ulCddbDiscId private
Referenced by GetCddbDiscId(), and SetCddbDiscId().
The documentation for this class was generated from the following file:
cdioSupport.h