Kodi Documentation: CWeatherJob Class Reference
CWeatherJob Class Reference
#include <WeatherJob.h>
Classes
struct ci_less
Public Member Functions
CWeatherJob (int location)
bool DoWork () override
Main workhorse function of CJob instances.
const CWeatherInfo & GetInfo () const
Public Member Functions inherited from CJob
CJob ()
virtual ~CJob ()=default
Destructor for job objects.
virtual const char * GetType () const
Function that returns the type of job.
virtual bool operator== (const CJob *job) const
virtual bool ShouldCancel (unsigned int progress, unsigned int total) const
Function for longer jobs to report progress and check whether they have been cancelled.
Private Types
typedef std::map< std::string, int, ci_less >::const_iterator ilocalizedTokens
Private Member Functions
void LocalizeOverview (std::string &str)
void LocalizeOverviewToken (std::string &str)
void LoadLocalizedToken ()
void SetFromProperties ()
Static Private Member Functions
static std::string ConstructPath (std::string in)
static int ConvertSpeed (int speed)
static void FormatTemperature (std::string &text, double temp)
Formats a celsius temperature into a string based on the users locale.
Private Attributes
std::map< std::string, int, ci_less > m_localizedTokens
CWeatherInfo m_info
int m_location
Static Private Attributes
static bool m_imagesOkay
Additional Inherited Members
Public Types inherited from CJob
enum PRIORITY {
PRIORITY_LOW_PAUSABLE = 0 , PRIORITY_LOW , PRIORITY_NORMAL , PRIORITY_HIGH ,
PRIORITY_DEDICATED
}
Priority levels for jobs, specified by clients when adding jobs to the CJobManager.
Member Typedef Documentation
ilocalizedTokens
typedef std::map<std::string,int,ci_less>::const_iterator CWeatherJob::ilocalizedTokens private
Constructor & Destructor Documentation
CWeatherJob()
CWeatherJob::CWeatherJob (int location) explicit
References m_location.
Member Function Documentation
ConstructPath()
std::string CWeatherJob::ConstructPath (std::string in) static private
References URIUtils::AddFileToFolder(), and ICON_ADDON_PATH.
Referenced by SetFromProperties().
ConvertSpeed()
static int CWeatherJob::ConvertSpeed (int speed) static private
DoWork()
bool CWeatherJob::DoWork () override virtual
Main workhorse function of CJob instances.
All CJob subclasses must implement this function, performing all processing. Once this function is complete, the OnJobComplete() callback is called, and the job is then destroyed.
See also
CJobManager, IJobCallback::OnJobComplete()
Implements CJob.
References CServiceBroker::GetAddonMgr(), CServiceBroker::GetGUI(), CScriptInvocationManager::GetInstance(), CServiceBroker::GetNetwork(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_WEATHER_FETCHED, CLog::Log(), LOGERROR, LOGINFO, m_location, SetFromProperties(), CSettings::SETTING_WEATHER_ADDON, and KODI::TIME::Sleep().
FormatTemperature()
void CWeatherJob::FormatTemperature (std::string & text, double temp) static private
Formats a celsius temperature into a string based on the users locale.
Parameters
text the string to format
temp the temperature (in degrees celsius).
References CTemperature::CreateFromCelsius(), g_langInfo, text, and CTemperature::To().
Referenced by SetFromProperties().
GetInfo()
const CWeatherInfo & CWeatherJob::GetInfo () const
References m_info.
LoadLocalizedToken()
void CWeatherJob::LoadLocalizedToken () private
References URIUtils::AddFileToFolder(), CPODocument::GetEntryID(), CPODocument::GetEntryType(), CLangInfo::GetLanguagePath(), CPODocument::GetMsgid(), CPODocument::GetNextEntry(), CServiceBroker::GetSettingsComponent(), ID_FOUND, ISSOURCELANG, LANGUAGE_DEFAULT, CPODocument::LoadFile(), LOCALIZED_TOKEN_FIRSTID, LOCALIZED_TOKEN_FIRSTID2, LOCALIZED_TOKEN_FIRSTID3, LOCALIZED_TOKEN_FIRSTID4, LOCALIZED_TOKEN_LASTID, LOCALIZED_TOKEN_LASTID2, LOCALIZED_TOKEN_LASTID3, LOCALIZED_TOKEN_LASTID4, CLog::Log(), LOGDEBUG, m_localizedTokens, CPODocument::ParseEntry(), and CSettings::SETTING_LOCALE_LANGUAGE.
Referenced by SetFromProperties().
LocalizeOverview()
void CWeatherJob::LocalizeOverview (std::string & str) private
References LocalizeOverviewToken().
Referenced by SetFromProperties().
LocalizeOverviewToken()
void CWeatherJob::LocalizeOverviewToken (std::string & str) private
References g_localizeStrings, CLocalizeStrings::Get(), and m_localizedTokens.
Referenced by LocalizeOverview(), and SetFromProperties().
SetFromProperties()
void CWeatherJob::SetFromProperties () private
References CVariant::asString(), ConstructPath(), CSpeed::CreateFromKilometresPerHour(), CWeatherInfo::currentConditions, CWeatherInfo::currentDewPoint, CWeatherInfo::currentFeelsLike, CWeatherInfo::currentHumidity, CWeatherInfo::currentIcon, CWeatherInfo::currentTemperature, CWeatherInfo::currentUVIndex, CWeatherInfo::currentWind, CWeatherInfo::forecast, FormatTemperature(), g_langInfo, g_localizeStrings, CLocalizeStrings::Get(), CDateTime::GetCurrentDateTime(), CServiceBroker::GetGUI(), CGUIWindow::GetProperty(), CGUIComponent::GetWindowManager(), CWeatherInfo::lastUpdateTime, LoadLocalizedToken(), LocalizeOverview(), LocalizeOverviewToken(), CWeatherInfo::location, ForecastDay::m_day, ForecastDay::m_high, ForecastDay::m_icon, m_info, m_localizedTokens, ForecastDay::m_low, ForecastDay::m_overview, NUM_DAYS, CGUIWindow::SetProperty(), CSpeed::To(), and WINDOW_WEATHER.
Referenced by DoWork().
Member Data Documentation
m_imagesOkay
bool CWeatherJob::m_imagesOkay static private
m_info
CWeatherInfo CWeatherJob::m_info private
Referenced by GetInfo(), and SetFromProperties().
m_localizedTokens
std::map<std::string, int, ci_less> CWeatherJob::m_localizedTokens private
Referenced by LoadLocalizedToken(), LocalizeOverviewToken(), and SetFromProperties().
m_location
int CWeatherJob::m_location private
Referenced by CWeatherJob(), and DoWork().
The documentation for this class was generated from the following files:
WeatherJob.h
WeatherJob.cpp