Kodi Documentation: DRMHELPERS Namespace Reference
DRMHELPERS Namespace Reference
Functions
std::string FourCCToString (uint32_t fourcc)
std::string ModifierToString (uint64_t modifier)
Function Documentation
FourCCToString()
std::string DRMHELPERS::FourCCToString (uint32_t fourcc)
Referenced by CVideoBufferDMA::Alloc(), CEGLImage::CreateImage(), CVideoBufferDMA::Export(), CVideoBufferDMA::SetDimensions(), and KODI::WINDOWING::GBM::CDRMPlane::SupportsFormatAndModifier().
ModifierToString()
std::string DRMHELPERS::ModifierToString (uint64_t modifier)
Referenced by KODI::WINDOWING::GBM::CDRMUtils::DrmFbGetFromBo(), and KODI::WINDOWING::GBM::CDRMPlane::SupportsFormatAndModifier().