Kodi Documentation: CAutoSwitch Class Reference
CAutoSwitch Class Reference
#include <AutoSwitch.h>
Public Member Functions
CAutoSwitch (void)
virtual ~CAutoSwitch (void)
Static Public Member Functions
static int GetView (const CFileItemList &vecItems)
Generic function to add a layer of transparency to the calling window.
static bool ByFolders (const CFileItemList &vecItems)
Auto Switch method based on the current directory containing ALL folders and atleast one non-default thumb.
static bool ByFiles (bool bHideParentDirItems, const CFileItemList &vecItems)
Auto Switch method based on the current directory not containing ALL files and atleast one non-default thumb.
static bool ByThumbPercent (bool bHideParentDirItems, int iPercent, const CFileItemList &vecItems)
Auto Switch method based on the percentage of non-default thumbs in the current directory.
static bool ByFileCount (const CFileItemList &vecItems)
Auto Switch method based on whether there is more than 25% files.
static bool ByFolderThumbPercentage (bool hideParentDirItems, int percent, const CFileItemList &vecItems)
static float MetadataPercentage (const CFileItemList &vecItems)
Constructor & Destructor Documentation
CAutoSwitch()
CAutoSwitch::CAutoSwitch (void) default
~CAutoSwitch()
CAutoSwitch::~CAutoSwitch (void) virtual default
Member Function Documentation
ByFileCount()
bool CAutoSwitch::ByFileCount (const CFileItemList & vecItems) static
Auto Switch method based on whether there is more than 25% files.
Parameters
iPercent Percent of non-default thumbs to autoswitch on
References CFileItemList::GetFileCount(), and CFileItemList::Size().
Referenced by GetView(), and CGUIDialogFileBrowser::Update().
ByFiles()
bool CAutoSwitch::ByFiles (bool bHideParentDirItems, const CFileItemList & vecItems) static
Auto Switch method based on the current directory not containing ALL files and atleast one non-default thumb.
Parameters
bHideParentDirItems - are we not counting the ".." item?
vecItems Vector of FileItems
References CFileItemList::GetFolderCount(), and CFileItemList::Size().
Referenced by GetView().
ByFolders()
bool CAutoSwitch::ByFolders (const CFileItemList & vecItems) static
Auto Switch method based on the current directory containing ALL folders and atleast one non-default thumb.
Parameters
vecItems Vector of FileItems
References CFileItemList::GetFolderCount(), and CFileItemList::Size().
Referenced by GetView().
ByFolderThumbPercentage()
bool CAutoSwitch::ByFolderThumbPercentage (bool hideParentDirItems, int percent, const CFileItemList & vecItems) static
References CFileItemList::GetFileCount(), and CFileItemList::Size().
Referenced by GetView().
ByThumbPercent()
bool CAutoSwitch::ByThumbPercent (bool bHideParentDirItems, int iPercent, const CFileItemList & vecItems) static
Auto Switch method based on the percentage of non-default thumbs in the current directory.
Parameters
iPercent Percent of non-default thumbs to autoswitch on
vecItems Vector of FileItems
References CFileItemList::Size().
Referenced by GetView().
GetView()
int CAutoSwitch::GetView (const CFileItemList & vecItems) static
Generic function to add a layer of transparency to the calling window.
Parameters
vecItems Vector of FileItems passed from the calling window
References ByFileCount(), ByFiles(), ByFolders(), ByFolderThumbPercentage(), ByThumbPercent(), DEFAULT_VIEW_BIG_ICONS, DEFAULT_VIEW_INFO, DEFAULT_VIEW_LIST, CServiceBroker::GetGUI(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), MetadataPercentage(), METHOD_BYFILECOUNT, METHOD_BYFILES, METHOD_BYFOLDERS, METHOD_BYFOLDERTHUMBS, METHOD_BYTHUMBPERCENT, CSettings::SETTING_FILELISTS_SHOWPARENTDIRITEMS, WINDOW_PICTURES, and WINDOW_PROGRAMS.
Referenced by CGUIViewState::SetViewAsControl().
MetadataPercentage()
float CAutoSwitch::MetadataPercentage (const CFileItemList & vecItems) static
References CFileItemList::Size().
Referenced by GetView().
The documentation for this class was generated from the following files:
AutoSwitch.h
AutoSwitch.cpp