Kodi Documentation: CDVDFactoryCodec Class Reference
CDVDFactoryCodec Class Reference
#include <DVDFactoryCodec.h>
Static Public Member Functions
static std::unique_ptr< CDVDVideoCodec > CreateVideoCodec (CDVDStreamInfo &hint, CProcessInfo &processInfo)
static IHardwareDecoder * CreateVideoCodecHWAccel (const std::string &id, CDVDStreamInfo &hint, CProcessInfo &processInfo, AVPixelFormat fmt)
static std::unique_ptr< CDVDAudioCodec > CreateAudioCodec (CDVDStreamInfo &hint, CProcessInfo &processInfo, bool allowpassthrough, bool allowdtshddecode, CAEStreamInfo::DataType ptStreamType)
static std::unique_ptr< CDVDOverlayCodec > CreateOverlayCodec (CDVDStreamInfo &hint)
static void RegisterHWVideoCodec (const std::string &id, CreateHWVideoCodec createFunc)
static void ClearHWVideoCodecs ()
static void RegisterHWAccel (const std::string &id, CreateHWAccel createFunc)
static std::vector< std::string > GetHWAccels ()
static void ClearHWAccels ()
static void RegisterHWAudioCodec (const std::string &id, CreateHWAudioCodec createFunc)
static void ClearHWAudioCodecs ()
Static Protected Member Functions
static std::unique_ptr< CDVDVideoCodec > CreateVideoCodecHW (const std::string &id, CProcessInfo &processInfo)
static std::unique_ptr< CDVDAudioCodec > CreateAudioCodecHW (const std::string &id, CProcessInfo &processInfo)
Static Protected Attributes
static std::map< std::string, CreateHWVideoCodec > m_hwVideoCodecs
static std::map< std::string, CreateHWAccel > m_hwAccels
static std::map< std::string, CreateHWAudioCodec > m_hwAudioCodecs
Member Function Documentation
ClearHWAccels()
void CDVDFactoryCodec::ClearHWAccels () static
References m_hwAccels, and videoCodecSection.
Referenced by CWinSystemIOS::CreateNewWindow(), CWinSystemOSX::CreateNewWindow(), CWinSystemTVOS::CreateNewWindow(), KODI::WINDOWING::GBM::CWinSystemGbmEGLContext::DestroyWindowSystem(), CRenderSystemDX::InitRenderSystem(), KODI::WINDOWING::GBM::CWinSystemGbmGLContext::InitWindowSystem(), KODI::WINDOWING::GBM::CWinSystemGbmGLESContext::InitWindowSystem(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandEGLContext::InitWindowSystemEGL(), KODI::WINDOWING::X11::CWinSystemX11GLContext::RefreshGLContext(), and KODI::WINDOWING::X11::CWinSystemX11GLESContext::RefreshGLContext().
ClearHWAudioCodecs()
void CDVDFactoryCodec::ClearHWAudioCodecs () static
References audioCodecSection, and m_hwAudioCodecs.
ClearHWVideoCodecs()
void CDVDFactoryCodec::ClearHWVideoCodecs () static
References m_hwVideoCodecs, and videoCodecSection.
CreateAudioCodec()
std::unique_ptr< CDVDAudioCodec > CDVDFactoryCodec::CreateAudioCodec (CDVDStreamInfo & hint, CProcessInfo & processInfo, bool allowpassthrough, bool allowdtshddecode, CAEStreamInfo::DataType ptStreamType) static
References CreateAudioCodecHW(), m_hwAudioCodecs, and CAEStreamInfo::STREAM_TYPE_NULL.
Referenced by VideoPlayerCodec::Init(), CVideoPlayerAudio::OpenStream(), and CVideoPlayerAudio::SwitchCodecIfNeeded().
CreateAudioCodecHW()
std::unique_ptr< CDVDAudioCodec > CDVDFactoryCodec::CreateAudioCodecHW (const std::string & id, CProcessInfo & processInfo) static protected
References audioCodecSection, and m_hwAudioCodecs.
Referenced by CreateAudioCodec().
CreateOverlayCodec()
std::unique_ptr< CDVDOverlayCodec > CDVDFactoryCodec::CreateOverlayCodec (CDVDStreamInfo & hint) static
References CDVDStreamInfo::codec, CDVDStreamInfo::source, and STREAM_SOURCE_VIDEOMUX.
Referenced by CVideoPlayerSubtitle::OpenStream().
CreateVideoCodec()
std::unique_ptr< CDVDVideoCodec > CDVDFactoryCodec::CreateVideoCodec (CDVDStreamInfo & hint, CProcessInfo & processInfo) static
References CODEC_ALLOW_FALLBACK, CODEC_FORCE_SOFTWARE, CDVDStreamInfo::codecOptions, CreateVideoCodecHW(), CDVDStreamInfo::externalInterfaces, ADDON::IAddonProvider::INSTANCE_VIDEOCODEC, m_hwVideoCodecs, and videoCodecSection.
Referenced by CDVDFileInfo::ExtractThumbToTexture(), CVideoPlayerVideo::OpenStream(), and CVideoPlayerVideo::OpenStream().
CreateVideoCodecHW()
std::unique_ptr< CDVDVideoCodec > CDVDFactoryCodec::CreateVideoCodecHW (const std::string & id, CProcessInfo & processInfo) static protected
References m_hwVideoCodecs, and videoCodecSection.
Referenced by CreateVideoCodec().
CreateVideoCodecHWAccel()
IHardwareDecoder * CDVDFactoryCodec::CreateVideoCodecHWAccel (const std::string & id, CDVDStreamInfo & hint, CProcessInfo & processInfo, AVPixelFormat fmt) static
References m_hwAccels, and videoCodecSection.
Referenced by CDVDVideoCodecFFmpeg::GetFormat().
GetHWAccels()
std::vector< std::string > CDVDFactoryCodec::GetHWAccels () static
References m_hwAccels, and videoCodecSection.
Referenced by CDVDVideoCodecFFmpeg::GetFormat().
RegisterHWAccel()
void CDVDFactoryCodec::RegisterHWAccel (const std::string & id, CreateHWAccel createFunc) static
References id, m_hwAccels, and videoCodecSection.
Referenced by DXVA::CDecoder::Register(), VDPAU::CDecoder::Register(), VTB::CDecoder::Register(), and VAAPI::CDecoder::Register().
RegisterHWAudioCodec()
void CDVDFactoryCodec::RegisterHWAudioCodec (const std::string & id, CreateHWAudioCodec createFunc) static
References audioCodecSection, id, and m_hwAudioCodecs.
Referenced by CDVDAudioCodecAndroidMediaCodec::Register().
RegisterHWVideoCodec()
void CDVDFactoryCodec::RegisterHWVideoCodec (const std::string & id, CreateHWVideoCodec createFunc) static
References id, m_hwVideoCodecs, and videoCodecSection.
Referenced by CDVDVideoCodecAndroidMediaCodec::Register(), CDVDVideoCodecDRMPRIME::Register(), and CDVDVideoCodecStarfish::Register().
Member Data Documentation
m_hwAccels
std::map< std::string, CreateHWAccel > CDVDFactoryCodec::m_hwAccels static protected
Referenced by ClearHWAccels(), CreateVideoCodecHWAccel(), GetHWAccels(), and RegisterHWAccel().
m_hwAudioCodecs
std::map< std::string, CreateHWAudioCodec > CDVDFactoryCodec::m_hwAudioCodecs static protected
Referenced by ClearHWAudioCodecs(), CreateAudioCodec(), CreateAudioCodecHW(), and RegisterHWAudioCodec().
m_hwVideoCodecs
std::map< std::string, CreateHWVideoCodec > CDVDFactoryCodec::m_hwVideoCodecs static protected
Referenced by ClearHWVideoCodecs(), CreateVideoCodec(), CreateVideoCodecHW(), and RegisterHWVideoCodec().
The documentation for this class was generated from the following files:
DVDFactoryCodec.h
DVDFactoryCodec.cpp