Kodi Documentation: XSLTUtils.cpp File Reference
XSLTUtils.cpp File Reference
#include "XSLTUtils.h"
#include "log.h"
#include <libxslt/xslt.h>
#include <libxslt/transform.h>
#include <iostream>
Macros
#define TMP_BUF_SIZE 512
Functions
void err (void *ctx, const char *msg,...)
Macro Definition Documentation
TMP_BUF_SIZE
#define TMP_BUF_SIZE 512
Function Documentation
err()
void err (void * ctx, const char * msg, ...)
References CLog::Log(), LOGDEBUG, and TMP_BUF_SIZE.
Referenced by _VerifyGLState(), CDVDAudioCodecAndroidMediaCodec::AddData(), CDVDVideoCodecDRMPRIME::AddData(), kodi::addon::CInstancePeripheral::ADDON_GetAppearance(), kodi::addon::CInstancePVRClient::ADDON_GetBackendHostname(), kodi::addon::CInstancePVRClient::ADDON_GetBackendName(), kodi::addon::CInstancePVRClient::ADDON_GetBackendVersion(), kodi::addon::CInstancePVRClient::ADDON_GetConnectionString(), kodi::addon::CInstancePeripheral::ADDON_GetEvents(), kodi::addon::CInstancePeripheral::ADDON_GetFeatures(), kodi::addon::CInstancePeripheral::ADDON_GetIgnoredPrimitives(), kodi::addon::CInstancePeripheral::ADDON_GetJoystickInfo(), kodi::addon::CInstancePVRClient::ADDON_GetStreamProperties(), kodi::addon::CInstancePeripheral::ADDON_PerformDeviceScan(), CAESinkALSA::ALSAchmapToString(), KODI::WINDOWING::WAYLAND::CConnection::CConnection(), deactivateAudioSession(), XFILE::CZipFile::DecompressGzip(), dll_read(), dll_write(), CZeroconfBrowserMDNS::doAddServiceType(), CZeroconfMDNS::doPublishService(), CZeroconfBrowserMDNS::doResolveService(), CDVDVideoCodecDRMPRIME::Drain(), CAEEncoderFFmpeg::Encode(), CAESinkALSA::EnumerateDevice(), dbiplus::SqliteDataset::exec(), FFMPEG_HELP_TOOLS::FFMpegErrorToString(), CGUIControlSliderSetting::FormatText(), GetBSDProcessList(), CDVDAudioCodecAndroidMediaCodec::GetData(), CDVDVideoCodecDRMPRIME::GetPicture(), CAESinkALSA::HandleError(), KODI::CDRIP::CEncoderFFmpeg::Init(), CZeroconfMDNS::IsZCdaemonRunning(), dbiplus::SqliteDataset::make_query(), VAAPI::CVaapi1Texture::Map(), MapErrno(), VDPAU::CVdpauTexture::MapRGB(), UPNP::CUPnPServer::OnUpdateObject(), CDDB::Xcddb::openSocket(), CRenderManager::PrepareNextRender(), CFDEventMonitor::Process(), CZeroconfBrowserMDNS::ProcessResults(), CZeroconfMDNS::ProcessResults(), CDVDVideoCodecDRMPRIME::Reset(), CZeroconfBrowserMDNS::ResolveCallback(), setAVAudioSessionProperties(), dbiplus::MysqlDatabase::setErr(), CAESinkALSA::sndLibErrorHandler(), CALSADeviceMonitor::Start(), CWinSystemOSX::SwitchToVideoMode(), KODI::PLATFORM::FILESYSTEM::anonymous_namespace{Filesystem.cpp}::temp_directory_path_w(), CAESinkALSA::TryDevice(), KODI::CDRIP::CEncoderFFmpeg::WriteFrame(), and XSLTUtils::XSLTUtils().