Kodi Documentation: CRotateEffect Class Reference
CRotateEffect Class Reference
#include <VisibleEffect.h>
Public Member Functions
CRotateEffect (const TiXmlElement *node, EFFECT_TYPE effect)
~CRotateEffect () override=default
Public Member Functions inherited from CAnimEffect
CAnimEffect (const TiXmlElement *node, EFFECT_TYPE effect)
CAnimEffect (unsigned int delay, unsigned int length, EFFECT_TYPE effect)
CAnimEffect (const CAnimEffect &src)
virtual ~CAnimEffect ()
CAnimEffect & operator= (const CAnimEffect &src)
void Calculate (unsigned int time, const CPoint &center)
void ApplyState (ANIMATION_STATE state, const CPoint &center)
unsigned int GetDelay () const
unsigned int GetLength () const
const TransformMatrix & GetTransform () const
EFFECT_TYPE GetType () const
Private Member Functions
void ApplyEffect (float offset, const CPoint &center) override
Private Attributes
float m_startAngle
float m_endAngle
bool m_autoCenter
CPoint m_center
Additional Inherited Members
Public Types inherited from CAnimEffect
enum EFFECT_TYPE {
EFFECT_TYPE_NONE = 0 , EFFECT_TYPE_FADE , EFFECT_TYPE_FADE_DIFFUSE , EFFECT_TYPE_SLIDE ,
EFFECT_TYPE_ROTATE_X , EFFECT_TYPE_ROTATE_Y , EFFECT_TYPE_ROTATE_Z , EFFECT_TYPE_ZOOM
}
Static Public Member Functions inherited from CAnimEffect
static std::shared_ptr< Tweener > GetTweener (const TiXmlElement *pAnimationNode)
Protected Attributes inherited from CAnimEffect
TransformMatrix m_matrix
EFFECT_TYPE m_effect
Constructor & Destructor Documentation
CRotateEffect()
CRotateEffect::CRotateEffect (const TiXmlElement * node, EFFECT_TYPE effect)
References m_autoCenter, m_center, m_endAngle, m_startAngle, node, CPointGen< T >::x, and CPointGen< T >::y.
~CRotateEffect()
CRotateEffect::~CRotateEffect () override default
Member Function Documentation
ApplyEffect()
void CRotateEffect::ApplyEffect (float offset, const CPoint & center) override private virtual
Implements CAnimEffect.
References center, CAnimEffect::EFFECT_TYPE_ROTATE_X, CAnimEffect::EFFECT_TYPE_ROTATE_Y, CAnimEffect::EFFECT_TYPE_ROTATE_Z, CWinSystemBase::GetGfxContext(), CGraphicContext::GetScalingPixelRatio(), CServiceBroker::GetWinSystem(), m_autoCenter, m_center, CAnimEffect::m_effect, m_endAngle, CAnimEffect::m_matrix, m_startAngle, TransformMatrix::SetXRotation(), TransformMatrix::SetYRotation(), TransformMatrix::SetZRotation(), CPointGen< T >::x, and CPointGen< T >::y.
Member Data Documentation
m_autoCenter
bool CRotateEffect::m_autoCenter private
Referenced by ApplyEffect(), and CRotateEffect().
m_center
CPoint CRotateEffect::m_center private
Referenced by ApplyEffect(), and CRotateEffect().
m_endAngle
float CRotateEffect::m_endAngle private
Referenced by ApplyEffect(), and CRotateEffect().
m_startAngle
float CRotateEffect::m_startAngle private
Referenced by ApplyEffect(), and CRotateEffect().
The documentation for this class was generated from the following files:
VisibleEffect.h
VisibleEffect.cpp