Kodi Documentation: anonymous_namespace{PVRTimers.cpp} Namespace Reference
anonymous_namespace{PVRTimers.cpp} Namespace Reference
Functions
std::vector< std::shared_ptr< CPVREpgInfoTag > > GetEpgTagsForTimerRule (const CPVRTimerRuleMatcher &matcher)
void AddTimerRuleToEpgMap (const std::shared_ptr< CPVRTimerInfoTag > &timer, const CDateTime &now, std::map< std::shared_ptr< CPVREpg >, std::vector< std::shared_ptr< CPVRTimerRuleMatcher > > > &epgMap, bool &bFetchedAllEpgs)
Variables
constexpr auto MAX_NOTIFICATION_DELAY = 10s
Function Documentation
AddTimerRuleToEpgMap()
void anonymous_namespace{PVRTimers.cpp}::AddTimerRuleToEpgMap (const std::shared_ptr< CPVRTimerInfoTag > & timer, const CDateTime & now, std::map< std::shared_ptr< CPVREpg >, std::vector< std::shared_ptr< CPVRTimerRuleMatcher > > > & epgMap, bool & bFetchedAllEpgs)
References AddTimerRuleToEpgMap(), PVR::CPVRManager::EpgContainer(), PVR::CPVREpgContainer::GetAllEpgs(), and CServiceBroker::GetPVRManager().
Referenced by AddTimerRuleToEpgMap().
GetEpgTagsForTimerRule()
std::vector< std::shared_ptr< CPVREpgInfoTag > > anonymous_namespace{PVRTimers.cpp}::GetEpgTagsForTimerRule (const CPVRTimerRuleMatcher & matcher)
References PVR::CPVRManager::EpgContainer(), PVR::CPVREpgContainer::GetAllEpgs(), PVR::CPVRTimerRuleMatcher::GetChannel(), GetEpgTagsForTimerRule(), CServiceBroker::GetPVRManager(), and tags.
Referenced by GetEpgTagsForTimerRule().
Variable Documentation
MAX_NOTIFICATION_DELAY
constexpr auto anonymous_namespace{PVRTimers.cpp}::MAX_NOTIFICATION_DELAY = 10s constexpr