Kodi Documentation: TestFileItem.cpp File Reference
TestFileItem.cpp File Reference
#include "FileItem.h"
#include "ServiceBroker.h"
#include "URL.h"
#include "settings/AdvancedSettings.h"
#include "settings/Settings.h"
#include "settings/SettingsComponent.h"
#include "settings/lib/SettingsManager.h"
#include <gtest/gtest.h>
Classes
struct TestFileData
class AdvancedSettingsResetBase
class TestFileItemBasePath
Functions
TEST_P (TestFileItemBasePath, GetBaseMoviePath)
INSTANTIATE_TEST_SUITE_P (BaseNameMovies, TestFileItemBasePath, ValuesIn(BaseMovies))
Variables
const TestFileData BaseMovies []
Function Documentation
INSTANTIATE_TEST_SUITE_P()
INSTANTIATE_TEST_SUITE_P (BaseNameMovies , TestFileItemBasePath , ValuesIn(BaseMovies))
TEST_P()
TEST_P (TestFileItemBasePath , GetBaseMoviePath)
References CURL, EXPECT_EQ(), CFileItem::GetBaseMoviePath(), and CFileItem::SetPath().
Variable Documentation
BaseMovies
const TestFileData BaseMovies[]
Initial value:
= {{ "c:\\dir\\filename.avi", false, "c:\\dir\\filename.avi" },
                                   { "c:\\dir\\filename.avi", true,  "c:\\dir\\" },
                                   { "/dir/filename.avi", false, "/dir/filename.avi" },
                                   { "/dir/filename.avi", true,  "/dir/" },
                                   { "smb://somepath/file.avi", false, "smb://somepath/file.avi" },
                                   { "smb://somepath/file.avi", true, "smb://somepath/" },
                                   { "stack:///path/to/movie_name/cd1/some_file1.avi , /path/to/movie_name/cd2/some_file2.avi", false, "stack:///path/to/movie_name/cd1/some_file1.avi , /path/to/movie_name/cd2/some_file2.avi" },
                                   { "stack:///path/to/movie_name/cd1/some_file1.avi , /path/to/movie_name/cd2/some_file2.avi", true,  "/path/to/movie_name/" },
                                   { "/home/user/TV Shows/Dexter/S1/1x01.avi", false, "/home/user/TV Shows/Dexter/S1/1x01.avi" },
                                   { "/home/user/TV Shows/Dexter/S1/1x01.avi", true, "/home/user/TV Shows/Dexter/S1/" },
                                   { "zip://g%3a%5cmultimedia%5cmovies%5cSphere%2ezip/Sphere.avi", true, "g:\\multimedia\\movies\\" },
                                   { "/home/user/movies/movie_name/video_ts/VIDEO_TS.IFO", false, "/home/user/movies/movie_name/" },
                                   { "/home/user/movies/movie_name/video_ts/VIDEO_TS.IFO", true, "/home/user/movies/movie_name/" },
                                   { "/home/user/movies/movie_name/BDMV/index.bdmv", false, "/home/user/movies/movie_name/" },
                                   { "/home/user/movies/movie_name/BDMV/index.bdmv", true, "/home/user/movies/movie_name/" }}