Kodi Documentation: KODI::GAME::IConfigurationWizard Class Reference
KODI::GAME::IConfigurationWizard Class Reference abstract
Games
A wizard to direct user input.
#include <IConfigurationWindow.h>
Public Member Functions
virtual ~IConfigurationWizard ()=default
virtual void Run (const std::string &strControllerId, const std::vector< IFeatureButton * > &buttons)=0
Start the wizard for the specified buttons.
virtual void OnUnfocus (IFeatureButton *button)=0
Callback for feature losing focus.
virtual bool Abort (bool bWait=true)=0
Abort a running wizard.
virtual void RegisterKey (const CPhysicalFeature &key)=0
Register a key by its keycode.
virtual void UnregisterKeys ()=0
Unregister all registered keys.
Detailed Description
A wizard to direct user input.
The wizard is run for the current controller selected in the controller list (IControllerList). It prompts the user for input for each feature (IFeatureButton) in the feature list (IFeatureList).
Constructor & Destructor Documentation
~IConfigurationWizard()
virtual KODI::GAME::IConfigurationWizard::~IConfigurationWizard () virtual default
Member Function Documentation
Abort()
virtual bool KODI::GAME::IConfigurationWizard::Abort (bool bWait = true) pure virtual
Abort a running wizard.
Parameters
bWait True if the call should block until the wizard is fully aborted
Returns
true if aborted, or false if the wizard wasn't running
Implemented in KODI::GAME::CGUIConfigurationWizard.
Referenced by KODI::GAME::CGUIFeatureList::CleanupButtons().
OnUnfocus()
virtual void KODI::GAME::IConfigurationWizard::OnUnfocus (IFeatureButton * button) pure virtual
Callback for feature losing focus.
Parameters
button The feature button losing focus
Implemented in KODI::GAME::CGUIConfigurationWizard.
Referenced by KODI::GAME::CGUIFeatureButton::OnUnFocus().
RegisterKey()
virtual void KODI::GAME::IConfigurationWizard::RegisterKey (const CPhysicalFeature & key) pure virtual
Register a key by its keycode.
Parameters
key A key with a valid keycode
This should be called before Run(). It allows the user to choose a key to map instead of scrolling through a long list.
Implemented in KODI::GAME::CGUIConfigurationWizard.
Referenced by KODI::GAME::CGUIFeatureList::GetSelectKeyButton().
Run()
virtual void KODI::GAME::IConfigurationWizard::Run (const std::string & strControllerId, const std::vector< IFeatureButton * > & buttons) pure virtual
Start the wizard for the specified buttons.
Parameters
controllerId The controller ID being mapped
buttons The buttons to map
Implemented in KODI::GAME::CGUIConfigurationWizard.
Referenced by KODI::GAME::CGUIFeatureList::OnSelect().
UnregisterKeys()
virtual void KODI::GAME::IConfigurationWizard::UnregisterKeys () pure virtual
Unregister all registered keys.
Implemented in KODI::GAME::CGUIConfigurationWizard.
Referenced by KODI::GAME::CGUIFeatureList::CleanupButtons().
The documentation for this class was generated from the following file:
IConfigurationWindow.h