Kodi Documentation: JSONRPC::CJSONServiceDescription::CJsonRpcMethodMap Class Reference
JSONRPC::CJSONServiceDescription::CJsonRpcMethodMap Class Reference
Public Types
typedef std::map< std::string, JsonRpcMethod >::const_iterator JsonRpcMethodIterator
Public Member Functions
CJsonRpcMethodMap ()
void add (const JsonRpcMethod &method)
JsonRpcMethodIterator begin () const
JsonRpcMethodIterator find (const std::string &key) const
JsonRpcMethodIterator end () const
void clear ()
Private Attributes
std::map< std::string, JsonRpcMethod > m_actionmap
Member Typedef Documentation
JsonRpcMethodIterator
typedef std::map<std::string,JsonRpcMethod>::const_iterator JSONRPC::CJSONServiceDescription::CJsonRpcMethodMap::JsonRpcMethodIterator
Constructor & Destructor Documentation
CJsonRpcMethodMap()
CJSONServiceDescription::CJsonRpcMethodMap::CJsonRpcMethodMap ()
Member Function Documentation
add()
void CJSONServiceDescription::CJsonRpcMethodMap::add (const JsonRpcMethod & method)
References name, and JSONRPC::JsonRpcMethod::name.
Referenced by JSONRPC::CJSONServiceDescription::addMethod(), and JSONRPC::CJSONServiceDescription::Print().
begin()
CJSONServiceDescription::CJsonRpcMethodMap::JsonRpcMethodIterator CJSONServiceDescription::CJsonRpcMethodMap::begin () const
Referenced by JSONRPC::CJSONServiceDescription::Print().
clear()
void CJSONServiceDescription::CJsonRpcMethodMap::clear ()
Referenced by JSONRPC::CJSONServiceDescription::Cleanup().
end()
CJSONServiceDescription::CJsonRpcMethodMap::JsonRpcMethodIterator CJSONServiceDescription::CJsonRpcMethodMap::end () const
Referenced by JSONRPC::CJSONServiceDescription::addMethod(), JSONRPC::CJSONServiceDescription::CheckCall(), and JSONRPC::CJSONServiceDescription::Print().
find()
CJSONServiceDescription::CJsonRpcMethodMap::JsonRpcMethodIterator CJSONServiceDescription::CJsonRpcMethodMap::find (const std::string & key) const
Referenced by JSONRPC::CJSONServiceDescription::addMethod(), JSONRPC::CJSONServiceDescription::CheckCall(), and JSONRPC::CJSONServiceDescription::Print().
Member Data Documentation
m_actionmap
std::map<std::string, JsonRpcMethod> JSONRPC::CJSONServiceDescription::CJsonRpcMethodMap::m_actionmap private
The documentation for this class was generated from the following files:
JSONServiceDescription.h
JSONServiceDescription.cpp