Kodi Documentation: anonymous_namespace{VideoUtils.cpp} Namespace Reference
anonymous_namespace{VideoUtils.cpp} Namespace Reference
Functions
KODI::VIDEO::UTILS::ResumeInformation GetFolderItemResumeInformation (const CFileItem &item)
KODI::VIDEO::UTILS::ResumeInformation GetNonFolderItemResumeInformation (const CFileItem &item)
Function Documentation
GetFolderItemResumeInformation()
KODI::VIDEO::UTILS::ResumeInformation anonymous_namespace{VideoUtils.cpp}::GetFolderItemResumeInformation (const CFileItem & item)
References XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetDatabaseInfo(), CFileItem::GetPath(), PVR::CPVRGUIDirectory::GetRecordingsDirectoryInfo(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetSeason(), CVideoDatabase::GetSeasonId(), CVideoDatabase::GetSeasonInfo(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetSetId(), CVideoDatabase::GetSetInfo(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetTvShowId(), CVideoDatabase::GetTvShowInfo(), CGUIListItem::HasProperty(), URIUtils::IsPVRRecordingFileOrFolder(), CFileItem::IsResumable(), KODI::VIDEO::UTILS::ResumeInformation::isResumable, CGUIListItem::m_bIsFolder, and CVideoDatabase::Open().
GetNonFolderItemResumeInformation()
KODI::VIDEO::UTILS::ResumeInformation anonymous_namespace{VideoUtils.cpp}::GetNonFolderItemResumeInformation (const CFileItem & item)
References CDatabase::Close(), CUtil::ConvertSecsToMilliSecs(), EPISODES, CFileItem::GetCurrentResumeTimeAndPartNumber(), XFILE::VIDEODATABASEDIRECTORY::CDirectoryNode::GetDatabaseInfo(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetEpisodeId(), CVideoDatabase::GetFilePathById(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetMovieId(), XFILE::VIDEODATABASEDIRECTORY::CQueryParams::GetMVideoId(), CFileItem::GetPath(), CVideoDatabase::GetResumeBookMark(), CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), CFileItem::IsDeleted(), CFileItem::IsDVD(), CFileItem::IsLiveTV(), CFileItem::IsNFO(), CBookmark::IsPartWay(), KODI::PLAYLIST::IsPlayList(), KODI::VIDEO::UTILS::ResumeInformation::isResumable, CBookmark::IsSet(), CFileItem::IsType(), LOGERROR, CVideoInfoTag::m_strFileNameAndPath, MOVIES, MUSICVIDEOS, CVideoDatabase::Open(), CBookmark::partNumber, KODI::VIDEO::UTILS::ResumeInformation::partNumber, KODI::VIDEO::UTILS::ResumeInformation::startOffset, and CBookmark::timeInSeconds.