Kodi Documentation: CGUIPassword Class Reference
CGUIPassword Class Reference
#include <GUIPassword.h>
Public Member Functions
CGUIPassword (void)
~CGUIPassword (void) override
template<typename T >
bool IsItemUnlocked (T pItem, const std::string &strType, const std::string &strLabel, const std::string &strHeading)
bool IsItemUnlocked (CFileItem *pItem, const std::string &strType)
Tests if the user is allowed to access the share folder.
bool IsItemUnlocked (CMediaSource *pItem, const std::string &strType)
Tests if the user is allowed to access the Mediasource.
bool CheckLock (LockType btnType, const std::string &strPassword, int iHeading)
bool CheckLock (LockType btnType, const std::string &strPassword, int iHeading, bool &bCanceled)
bool IsProfileLockUnlocked (int iProfile=-1)
bool IsProfileLockUnlocked (int iProfile, bool &bCanceled, bool prompt=true)
bool IsMasterLockUnlocked (bool bPromptUser)
bool IsMasterLockUnlocked (bool bPromptUser, bool &bCanceled)
void UpdateMasterLockRetryCount (bool bResetCount)
bool CheckStartUpLock ()
bool CheckSettingLevelLock (const SettingLevel &level, bool enforce=false)
Checks if the current profile is allowed to access the given settings level.
bool CheckMenuLock (int iWindowID)
bool IsVideoUnlocked ()
bool IsMusicUnlocked ()
bool SetMasterLockMode (bool bDetails=true)
bool LockSource (const std::string &strType, const std::string &strName, bool bState)
void LockSources (bool lock)
void RemoveSourceLocks ()
bool IsDatabasePathUnlocked (const std::string &strPath, std::vector< CMediaSource > &sources)
bool IsMediaFileUnlocked (const std::string &type, const std::string &file) const
Helper function to test if a matching mediasource is currently unlocked for a given media file.
void SetMediaSourcePath (const std::string &strMediaSourcePath)
void OnSettingAction (const std::shared_ptr< const CSetting > &setting) override
The given setting has been activated.
Public Member Functions inherited from ISettingCallback
virtual ~ISettingCallback ()=default
virtual bool OnSettingChanging (const std::shared_ptr< const CSetting > &setting)
The value of the given setting is being changed.
virtual void OnSettingChanged (const std::shared_ptr< const CSetting > &setting)
The value of the given setting has changed.
virtual bool OnSettingUpdate (const std::shared_ptr< CSetting > &setting, const char *oldSettingId, const TiXmlNode *oldSettingNode)
The given setting needs to be updated.
virtual void OnSettingPropertyChanged (const std::shared_ptr< const CSetting > &setting, const char *propertyName)
The given property of the given setting has changed.
Public Attributes
bool bMasterUser
int iMasterLockRetriesLeft
Private Member Functions
bool IsMediaPathUnlocked (const std::shared_ptr< CProfileManager > &profileManager, const std::string &strType) const
Helper function to test if the user is allowed to access the path by looking up the matching Mediasource. Used internally by CheckMenuLock.
int VerifyPassword (LockType btnType, const std::string &strPassword, const std::string &strHeading)
Private Attributes
std::string m_strMediaSourcePath
Constructor & Destructor Documentation
CGUIPassword()
CGUIPassword::CGUIPassword (void)
References bMasterUser, and iMasterLockRetriesLeft.
~CGUIPassword()
CGUIPassword::~CGUIPassword (void) override default
Member Function Documentation
CheckLock() [1/2]
bool CGUIPassword::CheckLock (LockType btnType, const std::string & strPassword, int iHeading)
References CheckLock().
Referenced by CheckLock(), IsProfileLockUnlocked(), and CGUIWindowLoginScreen::OnPopupMenu().
CheckLock() [2/2]
bool CGUIPassword::CheckLock (LockType btnType, const std::string & strPassword, int iHeading, bool & bCanceled)
References bMasterUser, g_localizeStrings, g_passwordManager, CLocalizeStrings::Get(), CServiceBroker::GetSettingsComponent(), LOCK_MODE_EVERYONE, and VerifyPassword().
CheckMenuLock()
bool CGUIPassword::CheckMenuLock (int iWindowID)
References CheckSettingLevelLock(), g_passwordManager, CServiceBroker::GetGUI(), CViewStateSettings::GetInstance(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), IsMasterLockUnlocked(), IsMediaPathUnlocked(), IsSettingsWindow(), m_strMediaSourcePath, WINDOW_ADDON_BROWSER, WINDOW_FILES, WINDOW_GAMES, WINDOW_HOME, WINDOW_MUSIC_NAV, WINDOW_PICTURES, WINDOW_PROGRAMS, WINDOW_SETTINGS_MENU, WINDOW_SETTINGS_PROFILES, and WINDOW_VIDEO_NAV.
Referenced by EnableAddon(), ADDON::CAddonInstaller::InstallFromZip(), ADDON::CAddonInstaller::InstallModal(), CGUIDialogAddonInfo::OnEnableDisable(), CGUIDialogAddonInfo::OnInstall(), CGUIDialogAddonInfo::OnUninstall(), CGUIDialogAddonSettings::SaveAndClose(), and CGUIDialogAddonSettings::ShowForAddon().
CheckSettingLevelLock()
bool CGUIPassword::CheckSettingLevelLock (const SettingLevel & level, bool enforce = false)
Checks if the current profile is allowed to access the given settings level.
Parameters
level - The level to check
enforce - If false, CheckSettingLevelLock is allowed to lower the current settings level to a level we're allowed to access
Returns
true if we're allowed to access the settings
References LOCK_LEVEL::ALL, CServiceBroker::GetGUI(), CViewStateSettings::GetInstance(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), IsMasterLockUnlocked(), LOCK_LEVEL::NONE, CViewStateSettings::SetSettingLevel(), WINDOW_SCREEN_CALIBRATION, WINDOW_SETTINGS_MENU, and WINDOW_SETTINGS_MYPVR.
Referenced by CheckMenuLock(), CGUIDialogAddonSettings::OnAction(), CGUIWindowSettingsCategory::OnAction(), CGUIDialogVideoSettings::OnSettingAction(), CGUIDialogAudioSettings::Save(), CGUIDialogSubtitleSettings::Save(), and CGUIDialogVideoSettings::Save().
CheckStartUpLock()
bool CGUIPassword::CheckStartUpLock ()
References g_localizeStrings, g_passwordManager, CLocalizeStrings::Get(), CServiceBroker::GetAppMessenger(), CServiceBroker::GetSettingsComponent(), iMasterLockRetriesLeft, CSettings::SETTING_MASTERLOCK_MAXRETRIES, KODI::MESSAGING::HELPERS::ShowOKDialogLines(), TMSG_SHUTDOWN, and VerifyPassword().
Referenced by CApplication::Initialize().
IsDatabasePathUnlocked()
bool CGUIPassword::IsDatabasePathUnlocked (const std::string & strPath, std::vector< CMediaSource > & sources)
References bMasterUser, g_passwordManager, CServiceBroker::GetGUI(), CUtil::GetMatchingSource(), CServiceBroker::GetSettingsComponent(), CGUIComponent::GetWindowManager(), LOCK_MODE_EVERYONE, LOCK_STATE_LOCKED, and WINDOW_VIDEO_NAV.
Referenced by CVideoDatabase::GetEpisodesByName(), CVideoDatabase::GetEpisodesByPlot(), CVideoDatabase::GetEpisodesByWhere(), CVideoDatabase::GetMatchingMusicVideo(), CVideoDatabase::GetMovieActorsByName(), CVideoDatabase::GetMovieCountriesByName(), CVideoDatabase::GetMovieDirectorsByName(), CVideoDatabase::GetMovieGenresByName(), CVideoDatabase::GetMoviesByName(), CVideoDatabase::GetMoviesByPlot(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideoAlbumsByName(), CVideoDatabase::GetMusicVideoAlbumsNav(), CVideoDatabase::GetMusicVideoArtistsByName(), CVideoDatabase::GetMusicVideoDirectorsByName(), CVideoDatabase::GetMusicVideoGenresByName(), CVideoDatabase::GetMusicVideosByAlbum(), CVideoDatabase::GetMusicVideosByName(), CVideoDatabase::GetMusicVideosByWhere(), CVideoDatabase::GetNavCommon(), CVideoDatabase::GetPeopleNav(), CVideoDatabase::GetSeasonsByWhere(), CVideoDatabase::GetTvShowGenresByName(), CVideoDatabase::GetTvShowsActorsByName(), CVideoDatabase::GetTvShowsByName(), CVideoDatabase::GetTvShowsByWhere(), CVideoDatabase::GetTvShowsDirectorsByName(), and CVideoDatabase::GetYearsNav().
IsItemUnlocked() [1/3]
bool CGUIPassword::IsItemUnlocked (CFileItem * pItem, const std::string & strType)
Tests if the user is allowed to access the share folder.
Parameters
pItem The share folder item to access
strType The type of share being accessed, e.g. "music", "video", etc. See CSettings::UpdateSources()
Returns
If access is granted, returns true
References g_localizeStrings, CLocalizeStrings::Get(), CGUIListItem::GetLabel(), and CGUIListItem::m_bIsFolder.
IsItemUnlocked() [2/3]
bool CGUIPassword::IsItemUnlocked (CMediaSource * pItem, const std::string & strType)
Tests if the user is allowed to access the Mediasource.
Parameters
pItem The share folder item to access
strType The type of share being accessed, e.g. "music", "video", etc. See CSettings::UpdateSources()
Returns
If access is granted, returns true
References g_localizeStrings, CLocalizeStrings::Get(), and CMediaSource::strName.
IsItemUnlocked() [3/3]
template<typename T > bool CGUIPassword::IsItemUnlocked (T pItem, const std::string & strType, const std::string & strLabel, const std::string & strHeading)
References bMasterUser, g_passwordManager, CServiceBroker::GetFavouritesService(), CMediaSourceSettings::GetInstance(), CServiceBroker::GetSettingsComponent(), LOCK_MODE_EVERYONE, LOCK_STATE_LOCK_BUT_UNLOCKED, LockSource(), CFavouritesService::RefreshFavourites(), CMediaSourceSettings::Save(), CSettings::SETTING_MASTERLOCK_MAXRETRIES, KODI::MESSAGING::HELPERS::ShowOKDialogText(), CMediaSourceSettings::UpdateSource(), and VerifyPassword().
Referenced by anonymous_namespace{MusicUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::anonymous_namespace{VideoGUIUtils.cpp}::CAsyncGetItemsForPlaylist::GetItemsForPlaylist(), KODI::GAME::CGUIWindowGames::GetStartFolder(), CGUIWindowPictures::GetStartFolder(), CGUIWindowPrograms::GetStartFolder(), IsMediaPathUnlocked(), CGUIMediaWindow::OnClick(), and CGUIWindowFileManager::OnClick().
IsMasterLockUnlocked() [1/2]
bool CGUIPassword::IsMasterLockUnlocked (bool bPromptUser)
References IsMasterLockUnlocked().
Referenced by anonymous_namespace{SettingConditions.cpp}::CheckMasterLock(), CheckMenuLock(), CheckSettingLevelLock(), CGUIDialogVideoInfo::DeleteVideoItem(), CFavouritesService::GetAll(), IsMasterLockUnlocked(), IsMusicUnlocked(), IsProfileLockUnlocked(), IsVideoUnlocked(), MasterMode(), CGUIMediaWindow::OnClick(), CGUIDialogContextMenu::OnContextButton(), CGUIWindowVideoBase::OnDeleteItem(), CGUIMediaWindow::OnDeleteItem(), CGUIWindowLoginScreen::OnPopupMenu(), and CGUIMediaWindow::OnRenameItem().
IsMasterLockUnlocked() [2/2]
bool CGUIPassword::IsMasterLockUnlocked (bool bPromptUser, bool & bCanceled)
References bMasterUser, g_localizeStrings, g_passwordManager, CLocalizeStrings::Get(), CServiceBroker::GetSettingsComponent(), iMasterLockRetriesLeft, LOCK_MODE_EVERYONE, CSettings::SETTING_MASTERLOCK_MAXRETRIES, UpdateMasterLockRetryCount(), and VerifyPassword().
IsMediaFileUnlocked()
bool CGUIPassword::IsMediaFileUnlocked (const std::string & type, const std::string & file) const
Helper function to test if a matching mediasource is currently unlocked for a given media file.
Note
this function only returns the lock state. it does not provide unlock functionality
Parameters
type The type of share being accessed, e.g. "music", "video", etc.
file The file to check lock state for
Returns
If access is granted, returns true
References URIUtils::GetBasePath(), CMediaSourceSettings::GetInstance(), CUtil::GetMatchingSource(), CMediaSourceSettings::GetSources(), LOCK_STATE_LOCKED, CLog::Log(), and LOGERROR.
Referenced by anonymous_namespace{FavouritesService.cpp}::IsMediasourceOfFavItemUnlocked().
IsMediaPathUnlocked()
bool CGUIPassword::IsMediaPathUnlocked (const std::shared_ptr< CProfileManager > & profileManager, const std::string & strType) const private
Helper function to test if the user is allowed to access the path by looking up the matching Mediasource. Used internally by CheckMenuLock.
Parameters
profileManager instance passed by ref. see CGUIPassword::CheckMenuLock
strType The type of share being accessed, e.g. "music", "video", etc.
Returns
If access is granted, returns true
References bMasterUser, g_passwordManager, CMediaSourceSettings::GetInstance(), CUtil::GetMatchingSource(), CMediaSourceSettings::GetSources(), IsItemUnlocked(), LOCK_MODE_EVERYONE, and m_strMediaSourcePath.
Referenced by CheckMenuLock(), IsMusicUnlocked(), and IsVideoUnlocked().
IsMusicUnlocked()
bool CGUIPassword::IsMusicUnlocked ()
References g_passwordManager, CServiceBroker::GetSettingsComponent(), IsMasterLockUnlocked(), IsMediaPathUnlocked(), and m_strMediaSourcePath.
Referenced by KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), and anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia().
IsProfileLockUnlocked() [1/2]
bool CGUIPassword::IsProfileLockUnlocked (int iProfile, bool & bCanceled, bool prompt = true)
References bMasterUser, CheckLock(), g_passwordManager, CProfile::getDate(), CProfile::getLockCode(), CProfile::getLockMode(), CServiceBroker::GetSettingsComponent(), IsMasterLockUnlocked(), LOCK_MODE_EVERYONE, and CGUIDialogProfileSettings::ShowForProfile().
IsProfileLockUnlocked() [2/2]
bool CGUIPassword::IsProfileLockUnlocked (int iProfile = -1)
References IsProfileLockUnlocked().
Referenced by IsProfileLockUnlocked(), JSONRPC::CProfilesOperations::LoadProfile(), LoadProfile(), CGUIMediaWindow::OnClick(), PVR::CGUIDialogPVRChannelManager::OnClickButtonChannelLogo(), CGUIDialogContextMenu::OnContextButton(), CGUIWindowLoginScreen::OnMessage(), and CGUIWindowScreensaver::OnMessage().
IsVideoUnlocked()
bool CGUIPassword::IsVideoUnlocked ()
References g_passwordManager, CServiceBroker::GetSettingsComponent(), IsMasterLockUnlocked(), IsMediaPathUnlocked(), and m_strMediaSourcePath.
Referenced by KODI::PLAYLIST::CPlayListPlayer::OnApplicationMessage(), and anonymous_namespace{PlayerBuiltins.cpp}::PlayOrQueueMedia().
LockSource()
bool CGUIPassword::LockSource (const std::string & strType, const std::string & strName, bool bState)
References CServiceBroker::GetGUI(), CMediaSourceSettings::GetInstance(), CMediaSourceSettings::GetSources(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE_SOURCES, LOCK_STATE_LOCK_BUT_UNLOCKED, LOCK_STATE_LOCKED, and LOCK_STATE_NO_LOCK.
Referenced by IsItemUnlocked(), and CGUIDialogContextMenu::OnContextButton().
LockSources()
void CGUIPassword::LockSources (bool lock)
References CServiceBroker::GetGUI(), CMediaSourceSettings::GetInstance(), CMediaSourceSettings::GetSources(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE_SOURCES, LOCK_MODE_EVERYONE, LOCK_STATE_LOCK_BUT_UNLOCKED, and LOCK_STATE_LOCKED.
Referenced by MasterMode().
OnSettingAction()
void CGUIPassword::OnSettingAction (const std::shared_ptr< const CSetting > & setting) override virtual
The given setting has been activated.
This callback is triggered whenever the given setting has been activated. This callback is only fired for CSettingAction settings.
Parameters
setting The setting which has been activated.
Reimplemented from ISettingCallback.
References SetMasterLockMode(), and CSettings::SETTING_MASTERLOCK_LOCKCODE.
RemoveSourceLocks()
void CGUIPassword::RemoveSourceLocks ()
References CServiceBroker::GetGUI(), CMediaSourceSettings::GetInstance(), CMediaSourceSettings::GetSources(), CGUIComponent::GetWindowManager(), GUI_MSG_NOTIFY_ALL, GUI_MSG_UPDATE_SOURCES, LOCK_MODE_EVERYONE, LOCK_STATE_NO_LOCK, CMediaSourceSettings::Save(), and CMediaSourceSettings::UpdateSource().
SetMasterLockMode()
bool CGUIPassword::SetMasterLockMode (bool bDetails = true)
References CProfile::GetLocks(), CServiceBroker::GetSettingsComponent(), CProfile::SetLocks(), and CGUIDialogLockSettings::ShowAndGetLock().
Referenced by OnSettingAction(), and CGUIDialogProfileSettings::OnSettingAction().
SetMediaSourcePath()
void CGUIPassword::SetMediaSourcePath (const std::string & strMediaSourcePath) inline
References m_strMediaSourcePath.
UpdateMasterLockRetryCount()
void CGUIPassword::UpdateMasterLockRetryCount (bool bResetCount)
References g_localizeStrings, g_passwordManager, CLocalizeStrings::Get(), CServiceBroker::GetSettingsComponent(), iMasterLockRetriesLeft, CSettings::SETTING_MASTERLOCK_MAXRETRIES, KODI::MESSAGING::HELPERS::ShowOKDialogLines(), and KODI::MESSAGING::HELPERS::ShowOKDialogText().
Referenced by IsMasterLockUnlocked().
VerifyPassword()
int CGUIPassword::VerifyPassword (LockType btnType, const std::string & strPassword, const std::string & strHeading) private
References LOCK_MODE_GAMEPAD, LOCK_MODE_NUMERIC, LOCK_MODE_QWERTY, CGUIDialogGamepad::ShowAndVerifyPassword(), CGUIDialogNumeric::ShowAndVerifyPassword(), and CGUIKeyboardFactory::ShowAndVerifyPassword().
Referenced by CheckLock(), CheckStartUpLock(), IsItemUnlocked(), and IsMasterLockUnlocked().
Member Data Documentation
bMasterUser
bool CGUIPassword::bMasterUser
Referenced by CGUIPassword(), CheckLock(), CGUIViewState::DisableAddSourceButtons(), KODI::GUILIB::GUIINFO::CSystemGUIInfo::GetBool(), CGUIDialogContextMenu::GetContextButtons(), CGUIWindowMusicBase::GetContextButtons(), CGUIWindowMusicNav::GetContextButtons(), CGUIWindowVideoNav::GetContextButtons(), CVideoDatabase::GetEpisodesByName(), CVideoDatabase::GetEpisodesByPlot(), CVideoDatabase::GetEpisodesByWhere(), CVideoDatabase::GetMatchingMusicVideo(), CVideoDatabase::GetMovieActorsByName(), CVideoDatabase::GetMovieCountriesByName(), CVideoDatabase::GetMovieDirectorsByName(), CVideoDatabase::GetMovieGenresByName(), CVideoDatabase::GetMoviesByName(), CVideoDatabase::GetMoviesByPlot(), CVideoDatabase::GetMoviesByWhere(), CVideoDatabase::GetMusicVideoAlbumsByName(), CVideoDatabase::GetMusicVideoArtistsByName(), CVideoDatabase::GetMusicVideoDirectorsByName(), CVideoDatabase::GetMusicVideoGenresByName(), CVideoDatabase::GetMusicVideosByAlbum(), CVideoDatabase::GetMusicVideosByName(), CVideoDatabase::GetMusicVideosByWhere(), CVideoDatabase::GetNavCommon(), CVideoDatabase::GetPeopleNav(), CVideoDatabase::GetSeasonsByWhere(), CVideoDatabase::GetTvShowGenresByName(), CVideoDatabase::GetTvShowsActorsByName(), CVideoDatabase::GetTvShowsByName(), CVideoDatabase::GetTvShowsByWhere(), CVideoDatabase::GetTvShowsDirectorsByName(), CVideoDatabase::GetYearsNav(), IsDatabasePathUnlocked(), IsItemUnlocked(), IsMasterLockUnlocked(), anonymous_namespace{SettingConditions.cpp}::IsMasterUser(), IsMediaPathUnlocked(), IsProfileLockUnlocked(), CProfileManager::LogOff(), MasterMode(), CGUIDialogSongInfo::OnInitWindow(), CGUIDialogVideoInfo::OnInitWindow(), CGUIWindowVideoBase::PlayItem(), CGUIDialogMusicInfo::RefreshInfo(), CGUIDialogProfileSettings::ShowForProfile(), CGUIWindowVideoBase::ShowInfo(), CGUIDialogMusicInfo::Update(), and CGUIDialogFileBrowser::Update().
iMasterLockRetriesLeft
int CGUIPassword::iMasterLockRetriesLeft
Referenced by CGUIPassword(), CheckStartUpLock(), IsMasterLockUnlocked(), CGUIWindowLoginScreen::OnPopupMenu(), and UpdateMasterLockRetryCount().
m_strMediaSourcePath
std::string CGUIPassword::m_strMediaSourcePath private
Referenced by CheckMenuLock(), IsMediaPathUnlocked(), IsMusicUnlocked(), IsVideoUnlocked(), and SetMediaSourcePath().
The documentation for this class was generated from the following files:
GUIPassword.h
GUIPassword.cpp