Kodi Documentation: CSettingDependencyCondition Class Reference
CSettingDependencyCondition Class Reference
#include <SettingDependency.h>
Public Member Functions
CSettingDependencyCondition (CSettingsManager *settingsManager=nullptr)
CSettingDependencyCondition (const std::string &setting, const std::string &value, SettingDependencyOperator op, bool negated=false, CSettingsManager *settingsManager=nullptr)
CSettingDependencyCondition (const std::string &strProperty, const std::string &value, const std::string &setting="", bool negated=false, CSettingsManager *settingsManager=nullptr)
~CSettingDependencyCondition () override=default
bool Deserialize (const TiXmlNode *node) override
bool Check () const override
const std::string & GetName () const
const std::string & GetSetting () const
SettingDependencyTarget GetTarget () const
SettingDependencyOperator GetOperator () const
Public Member Functions inherited from CSettingConditionItem
CSettingConditionItem (CSettingsManager *settingsManager=nullptr)
~CSettingConditionItem () override=default
const char * GetTag () const override
Public Member Functions inherited from CBooleanLogicValue
CBooleanLogicValue (const std::string &value="", bool negated=false)
~CBooleanLogicValue () override=default
virtual const std::string & GetValue () const
virtual bool IsNegated () const
virtual void SetValue (const std::string &value)
virtual void SetNegated (bool negated)
Public Member Functions inherited from IXmlDeserializable
virtual ~IXmlDeserializable ()=default
Public Member Functions inherited from ISettingCondition
ISettingCondition (CSettingsManager *settingsManager)
virtual ~ISettingCondition ()=default
Private Member Functions
CSettingDependencyCondition (CSettingsManager *settingsManager, const std::string &strProperty, const std::string &setting, const std::string &value, SettingDependencyTarget target=SettingDependencyTarget::Unknown, SettingDependencyOperator op=SettingDependencyOperator::Equals, bool negated=false)
bool setTarget (const std::string &target)
bool setOperator (const std::string &op)
Private Attributes
SettingDependencyTarget m_target = SettingDependencyTarget::Unknown
SettingDependencyOperator m_operator = SettingDependencyOperator::Equals
Static Private Attributes
static Logger s_logger
Additional Inherited Members
Protected Attributes inherited from CSettingConditionItem
std::string m_name
std::string m_setting
Protected Attributes inherited from CBooleanLogicValue
std::string m_value
bool m_negated
Protected Attributes inherited from ISettingCondition
CSettingsManager * m_settingsManager
Constructor & Destructor Documentation
CSettingDependencyCondition() [1/4]
CSettingDependencyCondition::CSettingDependencyCondition (CSettingsManager * settingsManager = nullptr) explicit
CSettingDependencyCondition() [2/4]
CSettingDependencyCondition::CSettingDependencyCondition (const std::string & setting, const std::string & value, SettingDependencyOperator op, bool negated = false, CSettingsManager * settingsManager = nullptr)
CSettingDependencyCondition() [3/4]
CSettingDependencyCondition::CSettingDependencyCondition (const std::string & strProperty, const std::string & value, const std::string & setting = "", bool negated = false, CSettingsManager * settingsManager = nullptr)
~CSettingDependencyCondition()
CSettingDependencyCondition::~CSettingDependencyCondition () override default
CSettingDependencyCondition() [4/4]
CSettingDependencyCondition::CSettingDependencyCondition (CSettingsManager * settingsManager, const std::string & strProperty, const std::string & setting, const std::string & value, SettingDependencyTarget target = SettingDependencyTarget::Unknown, SettingDependencyOperator op = SettingDependencyOperator::Equals, bool negated = false) private
References CLog::GetLogger(), CServiceBroker::GetLogging(), CSettingConditionItem::m_name, CBooleanLogicValue::m_negated, CSettingConditionItem::m_setting, CBooleanLogicValue::m_value, s_logger, and value.
Member Function Documentation
Check()
bool CSettingDependencyCondition::Check () const override virtual
Reimplemented from CSettingConditionItem.
References CSettingConditionsManager::Check(), Contains, Equals, CSettingsManager::GetConditions(), CSettingsManager::GetSetting(), GreaterThan, LessThan, CSettingConditionItem::m_name, CBooleanLogicValue::m_negated, m_operator, CSettingConditionItem::m_setting, ISettingCondition::m_settingsManager, m_target, CBooleanLogicValue::m_value, Property, s_logger, Setting, Unknown, and value.
Deserialize()
bool CSettingDependencyCondition::Deserialize (const TiXmlNode * node) override virtual
Reimplemented from CSettingConditionItem.
References CSettingConditionItem::Deserialize(), Equals, CSettingConditionItem::m_name, m_operator, CSettingConditionItem::m_setting, m_target, node, s_logger, setOperator(), setTarget(), Setting, SETTING_XML_ATTR_ON, and SETTING_XML_ATTR_OPERATOR.
GetName()
const std::string & CSettingDependencyCondition::GetName () const inline
References CSettingConditionItem::m_name.
GetOperator()
SettingDependencyOperator CSettingDependencyCondition::GetOperator () const inline
References m_operator.
GetSetting()
const std::string & CSettingDependencyCondition::GetSetting () const inline
References CSettingConditionItem::m_setting.
Referenced by CSettingDependencyConditionCombination::Deserialize().
GetTarget()
SettingDependencyTarget CSettingDependencyCondition::GetTarget () const inline
References m_target.
setOperator()
bool CSettingDependencyCondition::setOperator (const std::string & op) private
References Contains, Equals, GreaterThan, LessThan, CBooleanLogicValue::m_negated, and m_operator.
Referenced by Deserialize().
setTarget()
bool CSettingDependencyCondition::setTarget (const std::string & target) private
References m_target, Property, and Setting.
Referenced by Deserialize().
Member Data Documentation
m_operator
SettingDependencyOperator CSettingDependencyCondition::m_operator = SettingDependencyOperator::Equals private
Referenced by Check(), Deserialize(), GetOperator(), and setOperator().
m_target
SettingDependencyTarget CSettingDependencyCondition::m_target = SettingDependencyTarget::Unknown private
Referenced by Check(), Deserialize(), GetTarget(), and setTarget().
s_logger
Logger CSettingDependencyCondition::s_logger static private
Referenced by Check(), CSettingDependencyCondition(), and Deserialize().
The documentation for this class was generated from the following files:
SettingDependency.h
SettingDependency.cpp