Kodi Documentation: KODI::UTILS::COLOR Namespace Reference
KODI::UTILS::COLOR Namespace Reference
Namespaces
namespace anonymous_namespace{ColorUtils.cpp}
Classes
struct ColorFloats
struct ColorInfo
Typedefs
typedef uint32_t Color
Functions
Color ChangeOpacity (const Color argb, const float opacity)
Change the opacity of a given ARGB color.
Color ConvertToRGBA (const Color argb)
Convert given ARGB color to RGBA color value.
Color ConvertToARGB (const Color rgba)
Convert given RGBA color to ARGB color value.
Color ConvertToBGR (const Color argb)
Convert given ARGB color to BGR color value.
Color ConvertHexToColor (const std::string &hexColor)
Convert given hex value to Color value.
Color ConvertIntToRGB (int r, int g, int b)
Convert given RGB int values to RGB color value.
ColorInfo MakeColorInfo (const Color &argb)
Create a ColorInfo from an ARGB Color to get additional information of the color and allow to be sorted with a color comparer.
ColorInfo MakeColorInfo (const std::string &hexColor)
Create a ColorInfo from an HEX color value to get additional information of the color and allow to be sorted with a color comparer.
bool comparePairColorInfo (const std::pair< std::string, ColorInfo > &a, const std::pair< std::string, ColorInfo > &b)
Comparer for pair string/ColorInfo to sort colors in a hue scale.
ColorFloats ConvertToFloats (const Color argb)
Convert given ARGB color to ColorFloats.
std::string ConvertToHexRGB (const Color argb)
Convert given ARGB color to hex RGB color value.
Variables
constexpr Color NONE = 0x00000000
constexpr Color LIMITED_BLACK = 0xFF101010
constexpr Color WHITE = 0xFFFFFFFF
constexpr Color SILVER = 0xFFC0C0C0
constexpr Color GRAY = 0xFF808080
constexpr Color BLACK = 0xFF000000
constexpr Color RED = 0xFFFF0000
constexpr Color MAROON = 0xFF800000
constexpr Color YELLOW = 0xFFFFFF00
constexpr Color OLIVE = 0xFF808000
constexpr Color LIME = 0xFF00FF00
constexpr Color GREEN = 0xFF008000
constexpr Color AQUA = 0xFF00FFFF
constexpr Color TEAL = 0xFF008080
constexpr Color BLUE = 0xFF0000FF
constexpr Color NAVY = 0xFF000080
constexpr Color FUCHSIA = 0xFFFF00FF
constexpr Color PURPLE = 0xFF800080
constexpr Color MAGENTA = 0xFFFF00FF
constexpr Color CYAN = 0xFF00FFFF
constexpr auto HTML_BASIC_COLORS
W3C HTML 16 basic color list.
Typedef Documentation
Color
typedef uint32_t KODI::UTILS::COLOR::Color
Function Documentation
ChangeOpacity()
Color KODI::UTILS::COLOR::ChangeOpacity (const Color argb, const float opacity)
Change the opacity of a given ARGB color.
Parameters
color The original color
opacity The opacity value as a float
Returns
the original color with the changed opacity/alpha value
Referenced by anonymous_namespace{DVDSubtitlesLibass.cpp}::ConvColor().
comparePairColorInfo()
bool KODI::UTILS::COLOR::comparePairColorInfo (const std::pair< std::string, ColorInfo > & a, const std::pair< std::string, ColorInfo > & b)
Comparer for pair string/ColorInfo to sort colors in a hue scale.
Referenced by CGUIColorManager::LoadColorsListFromXML().
ConvertHexToColor()
Color KODI::UTILS::COLOR::ConvertHexToColor (const std::string & hexColor)
Convert given hex value to Color value.
Parameters
hexColor The original hex color
Returns
the original hex color converted to Color value
References value.
Referenced by KODI::SUBTITLES::CSubtitlesSettings::GetBackgroundColor(), KODI::SUBTITLES::CSubtitlesSettings::GetBorderColor(), KODI::SUBTITLES::CSubtitlesSettings::GetFontColor(), KODI::SUBTITLES::CSubtitlesSettings::GetShadowColor(), MakeColorInfo(), and CGUIColorButtonControl::SetImageBoxColor().
ConvertIntToRGB()
Color KODI::UTILS::COLOR::ConvertIntToRGB (int r, int g, int b)
Convert given RGB int values to RGB color value.
Parameters
r The red value
g The green value
b The blue value
Returns
the color as RGB value
Referenced by CWebVTTHandler::DecodeLine().
ConvertToARGB()
Color KODI::UTILS::COLOR::ConvertToARGB (const Color rgba)
Convert given RGBA color to ARGB color value.
Parameters
color The original color
Returns
the original color converted to ARGB value
Referenced by CDVDOverlayCodecTX3G::Decode().
ConvertToBGR()
Color KODI::UTILS::COLOR::ConvertToBGR (const Color argb)
Convert given ARGB color to BGR color value.
Parameters
color The original color
Returns
the original color converted to BGR value
Referenced by anonymous_namespace{DVDOverlayCodecTX3G.cpp}::ConvertStyleToTags(), and CWebVTTHandler::DecodeLine().
ConvertToFloats()
ColorFloats KODI::UTILS::COLOR::ConvertToFloats (const Color argb)
Convert given ARGB color to ColorFloats.
Parameters
color The original color
Returns
the original color converted to ColorFloats
References KODI::UTILS::COLOR::ColorFloats::alpha, KODI::UTILS::COLOR::ColorFloats::blue, KODI::UTILS::COLOR::ColorFloats::green, and KODI::UTILS::COLOR::ColorFloats::red.
Referenced by CFadeEffect::CFadeEffect().
ConvertToHexRGB()
std::string KODI::UTILS::COLOR::ConvertToHexRGB (const Color argb)
Convert given ARGB color to hex RGB color value.
Parameters
color The original color
Returns
The original color converted to hex RGB
References KODI::UTILS::StringUtils::Format().
Referenced by anonymous_namespace{DVDDemuxCC.cpp}::ApplyStyleModifiers(), and anonymous_namespace{DVDSubtitleTagSami.cpp}::TranslateColorValue().
ConvertToRGBA()
Color KODI::UTILS::COLOR::ConvertToRGBA (const Color argb)
Convert given ARGB color to RGBA color value.
Parameters
color The original color
Returns
the original color converted to RGBA value
Referenced by anonymous_namespace{DVDSubtitlesLibass.cpp}::ConvColor().
MakeColorInfo() [1/2]
ColorInfo KODI::UTILS::COLOR::MakeColorInfo (const Color & argb)
Create a ColorInfo from an ARGB Color to get additional information of the color and allow to be sorted with a color comparer.
Parameters
argb The original ARGB color
Returns
the ColorInfo
References KODI::UTILS::COLOR::ColorInfo::colorARGB.
Referenced by CGUIColorManager::LoadColorsListFromXML().
MakeColorInfo() [2/2]
ColorInfo KODI::UTILS::COLOR::MakeColorInfo (const std::string & hexColor)
Create a ColorInfo from an HEX color value to get additional information of the color and allow to be sorted with a color comparer.
Parameters
hexColor The original ARGB color
Returns
the ColorInfo
References KODI::UTILS::COLOR::ColorInfo::colorARGB, and ConvertHexToColor().
Variable Documentation
AQUA
constexpr Color KODI::UTILS::COLOR::AQUA = 0xFF00FFFF constexpr
BLACK
constexpr Color KODI::UTILS::COLOR::BLACK = 0xFF000000 constexpr
Referenced by CDVDSubtitlesLibass::ApplyStyle(), anonymous_namespace{DVDDemuxCC.cpp}::CCColorConversion(), GUIFontManager::GetDefaultFont(), KODI::RETRO::CRPBaseRenderer::PreRender(), CGUIWindowScreensaver::Render(), and KODI::RETRO::CRPRenderManager::RenderControl().
BLUE
constexpr Color KODI::UTILS::COLOR::BLUE = 0xFF0000FF constexpr
Referenced by anonymous_namespace{DVDDemuxCC.cpp}::CCColorConversion().
CYAN
constexpr Color KODI::UTILS::COLOR::CYAN = 0xFF00FFFF constexpr
Referenced by anonymous_namespace{DVDDemuxCC.cpp}::CCColorConversion().
FUCHSIA
constexpr Color KODI::UTILS::COLOR::FUCHSIA = 0xFFFF00FF constexpr
GRAY
constexpr Color KODI::UTILS::COLOR::GRAY = 0xFF808080 constexpr
GREEN
constexpr Color KODI::UTILS::COLOR::GREEN = 0xFF008000 constexpr
Referenced by anonymous_namespace{DVDDemuxCC.cpp}::CCColorConversion().
HTML_BASIC_COLORS
constexpr auto KODI::UTILS::COLOR::HTML_BASIC_COLORS constexpr
Initial value:
= make_map<std::string_view, Color>({{"white", WHITE},
                                                                      {"silver", SILVER},
                                                                      {"gray", GRAY},
                                                                      {"black", BLACK},
                                                                      {"red", RED},
                                                                      {"maroon", MAROON},
                                                                      {"yellow", YELLOW},
                                                                      {"olive", OLIVE},
                                                                      {"lime", LIME},
                                                                      {"green", GREEN},
                                                                      {"aqua", AQUA},
                                                                      {"teal", TEAL},
                                                                      {"blue", BLUE},
                                                                      {"navy", NAVY},
                                                                      {"fuchsia", FUCHSIA},
                                                                      {"purple", PURPLE}})
W3C HTML 16 basic color list.
Referenced by anonymous_namespace{DVDSubtitleTagSami.cpp}::TranslateColorValue().
LIME
constexpr Color KODI::UTILS::COLOR::LIME = 0xFF00FF00 constexpr
LIMITED_BLACK
constexpr Color KODI::UTILS::COLOR::LIMITED_BLACK = 0xFF101010 constexpr
Referenced by KODI::RETRO::CRPBaseRenderer::PreRender().
MAGENTA
constexpr Color KODI::UTILS::COLOR::MAGENTA = 0xFFFF00FF constexpr
Referenced by anonymous_namespace{DVDDemuxCC.cpp}::CCColorConversion().
MAROON
constexpr Color KODI::UTILS::COLOR::MAROON = 0xFF800000 constexpr
NAVY
constexpr Color KODI::UTILS::COLOR::NAVY = 0xFF000080 constexpr
NONE
constexpr Color KODI::UTILS::COLOR::NONE = 0x00000000 constexpr
Referenced by CDVDSubtitlesLibass::ApplyStyle(), anonymous_namespace{DVDDemuxCC.cpp}::CCColorConversion(), CGUIColorButtonControl::CGUIColorButtonControl(), and CGUIColorButtonControl::SetImageBoxColor().
OLIVE
constexpr Color KODI::UTILS::COLOR::OLIVE = 0xFF808000 constexpr
PURPLE
constexpr Color KODI::UTILS::COLOR::PURPLE = 0xFF800080 constexpr
RED
constexpr Color KODI::UTILS::COLOR::RED = 0xFFFF0000 constexpr
Referenced by anonymous_namespace{DVDDemuxCC.cpp}::CCColorConversion().
SILVER
constexpr Color KODI::UTILS::COLOR::SILVER = 0xFFC0C0C0 constexpr
TEAL
constexpr Color KODI::UTILS::COLOR::TEAL = 0xFF008080 constexpr
WHITE
constexpr Color KODI::UTILS::COLOR::WHITE = 0xFFFFFFFF constexpr
Referenced by anonymous_namespace{DVDDemuxCC.cpp}::CCColorConversion(), and anonymous_namespace{DVDOverlayCodecTX3G.cpp}::ConvertStyleToTags().
YELLOW
constexpr Color KODI::UTILS::COLOR::YELLOW = 0xFFFFFF00 constexpr
Referenced by anonymous_namespace{DVDDemuxCC.cpp}::CCColorConversion().