Kodi Documentation: CDVDFileInfo Class Reference
CDVDFileInfo Class Reference
#include <DVDFileInfo.h>
Static Public Member Functions
static std::unique_ptr< CTexture > ExtractThumbToTexture (const CFileItem &fileItem, int chapterNumber=0)
static bool CanExtract (const CFileItem &fileItem)
Can a thumbnail image and file stream details be extracted from this file item?
static bool GetFileStreamDetails (CFileItem *pItem)
Open the item pointed to by pItem and extract streamdetails.
static bool GetFileDuration (const std::string &path, int &duration)
Static Private Member Functions
static bool DemuxerToStreamDetails (const std::shared_ptr< CDVDInputStream > &pInputStream, CDVDDemux *pDemux, CStreamDetails &details, const std::string &path="")
static bool DemuxerToStreamDetails (const std::shared_ptr< CDVDInputStream > &pInputStream, CDVDDemux *pDemuxer, const std::vector< CStreamDetailSubtitle > &subs, CStreamDetails &details)
Probe the file's internal and external streams and store the info in the StreamDetails parameter.
static bool AddExternalSubtitleToDetails (const std::string &path, CStreamDetails &details, const std::string &filename, const std::string &subfilename="")
Probe the streams of an external subtitle file and store the info in the StreamDetails parameter.
static void ProcessExternalSubtitles (CFileItem *item)
Checks external subtitles for a given item and adds any existing ones to the item stream details.
Member Function Documentation
AddExternalSubtitleToDetails()
bool CDVDFileInfo::AddExternalSubtitleToDetails (const std::string & path, CStreamDetails & details, const std::string & filename, const std::string & subfilename = "") static private
Probe the streams of an external subtitle file and store the info in the StreamDetails parameter.
Parameters
[out] details The external subtitle file's StreamDetails.
References CStreamDetails::AddStream(), CLangCodeExpander::ConvertToISO6392B(), XFILE::CFile::Exists(), g_LangCodeExpander, URIUtils::GetExtension(), CUtil::GetExternalStreamDetailsFromFilename(), CDVDDemuxVobsub::GetStreams(), CStreamDetailSubtitle::m_strLanguage, CDVDDemuxVobsub::Open(), URIUtils::ReplaceExtension(), STREAM_SOURCE_NONE, and strReplace().
Referenced by ProcessExternalSubtitles().
CanExtract()
bool CDVDFileInfo::CanExtract (const CFileItem & fileItem) static
Can a thumbnail image and file stream details be extracted from this file item?
References CFileItem::GetDynPath(), CFileItem::GetPath(), URIUtils::IsBluray(), CFileItem::IsDiscImage(), CFileItem::IsDVD(), URIUtils::IsFTP(), URIUtils::IsHTTP(), KODI::NETWORK::IsInternetStream(), URIUtils::IsOnLAN(), KODI::PLAYLIST::IsPlayList(), URIUtils::IsPlugin(), URIUtils::IsPVR(), URIUtils::IsRemote(), URIUtils::IsUPnP(), CGUIListItem::m_bIsFolder, and CInputStreamPVRBase::ProvidesStreamForMetaDataExtraction().
Referenced by ExtractThumbToTexture(), KODI::VIDEO::CVideoInfoScanner::GetArtwork(), GetFileStreamDetails(), and CVideoThumbLoader::LoadItemLookup().
DemuxerToStreamDetails() [1/2]
bool CDVDFileInfo::DemuxerToStreamDetails (const std::shared_ptr< CDVDInputStream > & pInputStream, CDVDDemux * pDemux, CStreamDetails & details, const std::string & path = "") static private
References CStreamDetails::AddStream(), CStreamDetails::DetermineBestStreams(), DVDSTREAM_TYPE_BLURAY, CDemuxStreamVideo::fAspect, XFILE::CStackDirectory::GetDirectory(), GetFileDuration(), CStreamDetails::GetNthStream(), CDVDDemux::GetStreamCodecName(), CDVDDemux::GetStreamLength(), CDVDDemux::GetStreams(), CDemuxStreamVideo::hdr_type, CStreamDetails::HdrTypeToString(), CDemuxStreamVideo::iHeight, URIUtils::IsStack(), CDemuxStreamVideo::iWidth, CDemuxStream::language, CStreamDetailVideo::m_fAspect, CStreamDetailAudio::m_iChannels, CStreamDetailVideo::m_iDuration, CStreamDetailVideo::m_iHeight, CStreamDetailVideo::m_iWidth, CStreamDetailVideo::m_strCodec, CStreamDetailAudio::m_strCodec, CStreamDetailVideo::m_strHdrType, CStreamDetailVideo::m_strLanguage, CStreamDetailAudio::m_strLanguage, CStreamDetailSubtitle::m_strLanguage, CStreamDetailVideo::m_strStereoMode, CStreamDetails::Reset(), CFileItemList::Size(), CDemuxStreamVideo::stereo_mode, STREAM_AUDIO, STREAM_SUBTITLE, STREAM_VIDEO, and CStreamDetail::VIDEO.
Referenced by DemuxerToStreamDetails(), and GetFileStreamDetails().
DemuxerToStreamDetails() [2/2]
bool CDVDFileInfo::DemuxerToStreamDetails (const std::shared_ptr< CDVDInputStream > & pInputStream, CDVDDemux * pDemuxer, const std::vector< CStreamDetailSubtitle > & subs, CStreamDetails & details) static private
Probe the file's internal and external streams and store the info in the StreamDetails parameter.
Parameters
[out] details The file's StreamDetails consisting of internal streams and external subtitle streams.
References CStreamDetails::AddStream(), DemuxerToStreamDetails(), and CStreamDetailSubtitle::m_strLanguage.
ExtractThumbToTexture()
std::unique_ptr< CTexture > CDVDFileInfo::ExtractThumbToTexture (const CFileItem & fileItem, int chapterNumber = 0) static
References CDVDStreamInfo::aspect, CanExtract(), CODEC_FORCE_SOFTWARE, CDVDStreamInfo::codecOptions, CDVDFactoryDemuxer::CreateDemuxer(), CDVDFactoryInputStream::CreateInputStream(), CProcessInfo::CreateInstance(), CTexture::CreateTexture(), CDVDFactoryCodec::CreateVideoCodec(), DegreeToOrientation(), DVP_FLAG_DROPPED, end(), CDVDStreamInfo::forced_aspect, CDVDDemuxUtils::FreeDemuxPacket(), CFileItem::GetPath(), CVideoBuffer::GetPlanes(), CServiceBroker::GetSettingsComponent(), CVideoBuffer::GetStrides(), VideoPicture::iDisplayHeight, VideoPicture::iDisplayWidth, VideoPicture::iFlags, VideoPicture::iHeight, int64_t(), DEMUX_PACKET::iStreamId, VideoPicture::iWidth, CLog::Log(), LOGDEBUG, LOGERROR, YuvImage::MAX_PLANES, CDVDStreamInfo::orientation, CFileItem::SetMimeTypeForInternetFile(), STREAM_VIDEO, CDVDVideoCodec::VC_NONE, CDVDVideoCodec::VC_PICTURE, and VideoPicture::videoBuffer.
Referenced by KODI::VIDEO::CVideoGeneratedImageFileLoader::Load().
GetFileDuration()
bool CDVDFileInfo::GetFileDuration (const std::string & path, int & duration) static
References CDVDFactoryDemuxer::CreateDemuxer(), and CDVDFactoryInputStream::CreateInputStream().
Referenced by DemuxerToStreamDetails(), and CApplicationStackHelper::InitializeStackStartPartAndOffset().
GetFileStreamDetails()
bool CDVDFileInfo::GetFileStreamDetails (CFileItem * pItem) static
Open the item pointed to by pItem and extract streamdetails.
Returns
true if the stream details have changed
References CanExtract(), CDVDFactoryDemuxer::CreateDemuxer(), CDVDFactoryInputStream::CreateInputStream(), DemuxerToStreamDetails(), DVDSTREAM_TYPE_DVD, DVDSTREAM_TYPE_PVRMANAGER, CFileItem::GetDynPath(), XFILE::CStackDirectory::GetFirstStackedFile(), CFileItem::GetVideoInfoTag(), CFileItem::HasVideoInfoTag(), URIUtils::IsStack(), CVideoInfoTag::m_streamDetails, CVideoInfoTag::m_strFileNameAndPath, ProcessExternalSubtitles(), and CFileItem::SetMimeTypeForInternetFile().
Referenced by KODI::VIDEO::CVideoInfoScanner::AddVideo(), CGUIDialogVideoManagerExtras::AddVideoExtra(), KODI::VIDEO::CVideoInfoScanner::AddVideoExtras(), CGUIDialogVideoManagerVersions::AddVideoVersionFilePicker(), and CVideoThumbLoader::LoadItemLookup().
ProcessExternalSubtitles()
void CDVDFileInfo::ProcessExternalSubtitles (CFileItem * item) static private
Checks external subtitles for a given item and adds any existing ones to the item stream details.
Parameters
item The video item
See also
AddExternalSubtitleToDetails
References AddExternalSubtitleToDetails(), CUtil::FindVobSubPair(), CFileItem::GetDynPath(), URIUtils::GetExtension(), CFileItem::GetVideoInfoTag(), CUtil::IsVobSub(), CVideoInfoTag::m_streamDetails, and CUtil::ScanForExternalSubtitles().
Referenced by GetFileStreamDetails().
The documentation for this class was generated from the following files:
DVDFileInfo.h
DVDFileInfo.cpp