Kodi Documentation: ZeroconfBrowser.h File Reference
ZeroconfBrowser.h File Reference
#include <string>
#include <set>
#include <vector>
#include <map>
#include <iostream>
Classes
class CZeroconfBrowser
this class provides support for zeroconf browsing
class CZeroconfBrowser::ZeroconfService
struct CZeroconfBrowser::ServiceInfo
Functions
std::ostream & operator<< (std::ostream &o, const CZeroconfBrowser::ZeroconfService &service)
bool operator< (CZeroconfBrowser::ZeroconfService const &fcr_lhs, CZeroconfBrowser::ZeroconfService const &fcr_rhs)
bool operator== (CZeroconfBrowser::ZeroconfService const &fcr_lhs, CZeroconfBrowser::ZeroconfService const &fcr_rhs)
Function Documentation
operator<()
bool operator< (CZeroconfBrowser::ZeroconfService const & fcr_lhs, CZeroconfBrowser::ZeroconfService const & fcr_rhs) inline
References CZeroconfBrowser::ZeroconfService::GetDomain(), CZeroconfBrowser::ZeroconfService::GetName(), and CZeroconfBrowser::ZeroconfService::GetType().
operator<<()
std::ostream & operator<< (std::ostream & o, const CZeroconfBrowser::ZeroconfService & service) inline
References CZeroconfBrowser::ZeroconfService::GetDomain(), CZeroconfBrowser::ZeroconfService::GetName(), and CZeroconfBrowser::ZeroconfService::GetType().
operator==()
bool operator== (CZeroconfBrowser::ZeroconfService const & fcr_lhs, CZeroconfBrowser::ZeroconfService const & fcr_rhs) inline
References CZeroconfBrowser::ZeroconfService::GetDomain(), CZeroconfBrowser::ZeroconfService::GetName(), and CZeroconfBrowser::ZeroconfService::GetType().