Kodi Documentation: KODI::KEYBOARD::CKeyboardStat Class Reference
KODI::KEYBOARD::CKeyboardStat Class Reference
Input » Keyboard
#include <KeyboardStat.h>
Public Member Functions
CKeyboardStat ()
~CKeyboardStat ()=default
void Initialize ()
CKey TranslateKey (XBMC_keysym &keysym) const
void ProcessKeyDown (XBMC_keysym &keysym)
void ProcessKeyUp (void)
std::string GetKeyName (int KeyID)
Static Private Member Functions
static bool LookupSymAndUnicodePeripherals (XBMC_keysym &keysym, uint8_t *key, char *unicode)
Private Attributes
XBMC_keysym m_lastKeysym
std::chrono::time_point< std::chrono::steady_clock > m_lastKeyTime
Constructor & Destructor Documentation
CKeyboardStat()
CKeyboardStat::CKeyboardStat ()
References m_lastKeysym, and m_lastKeyTime.
~CKeyboardStat()
KODI::KEYBOARD::CKeyboardStat::~CKeyboardStat () default
Member Function Documentation
GetKeyName()
std::string CKeyboardStat::GetKeyName (int KeyID)
References KODI::KEYBOARD::XBMCKEYTABLE::keyname, KODI::KEYBOARD::KeyTable::LookupVKeyName(), CKey::MODIFIER_ALT, CKey::MODIFIER_CTRL, CKey::MODIFIER_LONG, CKey::MODIFIER_META, CKey::MODIFIER_SHIFT, and CKey::MODIFIER_SUPER.
Referenced by CInputManager::HandleKey().
Initialize()
void CKeyboardStat::Initialize ()
Referenced by CInputManager::InitializeInputs().
LookupSymAndUnicodePeripherals()
bool CKeyboardStat::LookupSymAndUnicodePeripherals (XBMC_keysym & keysym, uint8_t * key, char * unicode) static private
References CServiceBroker::GetPeripherals().
Referenced by TranslateKey().
ProcessKeyDown()
void CKeyboardStat::ProcessKeyDown (XBMC_keysym & keysym)
References m_lastKeysym, and m_lastKeyTime.
Referenced by CInputManager::OnEvent().
ProcessKeyUp()
void CKeyboardStat::ProcessKeyUp (void)
References m_lastKeysym, and m_lastKeyTime.
Referenced by CInputManager::OnEvent().
TranslateKey()
CKey CKeyboardStat::TranslateKey (XBMC_keysym & keysym) const
References KODI::KEYBOARD::XBMCKEYTABLE::ascii, KODI::KEYBOARD::KEY_HOLD_TRESHOLD, CLog::Log(), LOGDEBUG, KODI::KEYBOARD::KeyTable::LookupSym(), KODI::KEYBOARD::KeyTable::LookupSymAndUnicode(), LookupSymAndUnicodePeripherals(), KODI::KEYBOARD::KeyTable::LookupUnicode(), m_lastKeysym, m_lastKeyTime, XBMC_keysym::mod, CKey::MODIFIER_ALT, CKey::MODIFIER_CAPSLOCK, CKey::MODIFIER_CTRL, CKey::MODIFIER_LONG, CKey::MODIFIER_META, CKey::MODIFIER_NUMLOCK, CKey::MODIFIER_SCROLLLOCK, CKey::MODIFIER_SHIFT, CKey::MODIFIER_SUPER, XBMC_keysym::scancode, XBMC_keysym::sym, KODI::KEYBOARD::XBMCKEYTABLE::sym, KODI::KEYBOARD::CKeyboardTranslator::TranslateKeycode(), XBMC_keysym::unicode, KODI::KEYBOARD::XBMCKEYTABLE::unicode, KODI::KEYBOARD::XBMCKEYTABLE::vkey, XBMCKMOD_ALT, XBMCKMOD_CAPS, XBMCKMOD_CTRL, XBMCKMOD_LALT, XBMCKMOD_LCTRL, XBMCKMOD_LSHIFT, XBMCKMOD_META, XBMCKMOD_MODE, XBMCKMOD_NUM, XBMCKMOD_RALT, XBMCKMOD_RCTRL, XBMCKMOD_RSHIFT, XBMCKMOD_SHIFT, XBMCKMOD_SUPER, and XBMCVK_F24.
Referenced by CInputManager::OnEvent().
Member Data Documentation
m_lastKeysym
XBMC_keysym KODI::KEYBOARD::CKeyboardStat::m_lastKeysym private
Referenced by CKeyboardStat(), ProcessKeyDown(), ProcessKeyUp(), and TranslateKey().
m_lastKeyTime
std::chrono::time_point<std::chrono::steady_clock> KODI::KEYBOARD::CKeyboardStat::m_lastKeyTime private
Referenced by CKeyboardStat(), ProcessKeyDown(), ProcessKeyUp(), and TranslateKey().
The documentation for this class was generated from the following files:
KeyboardStat.h
KeyboardStat.cpp