Kodi Documentation: KODI::WINDOWING::WAYLAND::CRegistry Class Reference
KODI::WINDOWING::WAYLAND::CRegistry Class Reference
#include <Registry.h>
Classes
struct BindInfo
struct SingletonBindInfo
Public Types
using AddHandler = std::function< void(std::uint32_t, wayland::proxy_t &&)>
using RemoveHandler = std::function< void(std::uint32_t) >
Public Member Functions
CRegistry (CConnection &connection)
template<typename T >
void RequestSingleton (T &target, std::uint32_t minVersion, std::uint32_t maxVersion, bool required=true)
template<typename T >
void Request (std::uint32_t minVersion, std::uint32_t maxVersion, const AddHandler &addHandler, const RemoveHandler &removeHandler)
void Bind ()
void UnbindSingletons ()
Private Member Functions
CRegistry (CRegistry const &other)=delete
CRegistry & operator= (CRegistry const &other)=delete
void RequestSingletonInternal (wayland::proxy_t &target, std::string const &interfaceName, std::uint32_t minVersion, std::uint32_t maxVersion, bool required)
void RequestInternal (std::function< wayland::proxy_t()> constructor, std::string const &interfaceName, std::uint32_t minVersion, std::uint32_t maxVersion, AddHandler addHandler, RemoveHandler removeHandler)
void CheckRequired ()
Private Attributes
CConnection & m_connection
wayland::registry_t m_registry
std::map< std::string, SingletonBindInfo > m_singletonBinds
std::map< std::string, BindInfo > m_binds
std::map< std::uint32_t, std::reference_wrapper< BindInfo > > m_boundNames
Detailed Description
Handle Wayland globals
Request singletons (bound once) with RequestSingleton, non-singletons such as wl_output with Request, then call Bind once.
Make sure to destroy all registries before destroying the CConnection.
Member Typedef Documentation
AddHandler
using KODI::WINDOWING::WAYLAND::CRegistry::AddHandler = std::function<void(std::uint32_t , wayland::proxy_t&&)>
RemoveHandler
using KODI::WINDOWING::WAYLAND::CRegistry::RemoveHandler = std::function<void(std::uint32_t) >
Constructor & Destructor Documentation
CRegistry() [1/2]
CRegistry::CRegistry (CConnection & connection) explicit
CRegistry() [2/2]
KODI::WINDOWING::WAYLAND::CRegistry::CRegistry (CRegistry const & other) private delete
Member Function Documentation
Bind()
void CRegistry::Bind ()
Create a registry object at the compositor and do an roundtrip to bind objects
This function blocks until the initial roundtrip is complete. All statically requested singletons that were available will be bound then.
Neither statically nor dynamically requested proxies will be bound before this function is called.
May throw std::runtime_error if a required global was not found.
Can only be called once for the same CRegistry object.
References CheckRequired(), KODI::WINDOWING::WAYLAND::CConnection::GetDisplay(), CLog::Log(), LOGDEBUG, m_binds, m_boundNames, m_connection, m_registry, m_singletonBinds, name, and KODI::WINDOWING::WAYLAND::CWinEventsWayland::RoundtripQueue().
Referenced by KODI::WINDOWING::WAYLAND::CWindowDecorator::CWindowDecorator().
CheckRequired()
void CRegistry::CheckRequired () private
References m_singletonBinds.
Referenced by Bind().
operator=()
CRegistry & KODI::WINDOWING::WAYLAND::CRegistry::operator= (CRegistry const & other) private delete
Request()
template<typename T > void KODI::WINDOWING::WAYLAND::CRegistry::Request (std::uint32_t minVersion, std::uint32_t maxVersion, const AddHandler & addHandler, const RemoveHandler & removeHandler) inline
Request a callback when a dynamic global appears or disappears
The callbacks may be called from the thread that calls Bind or the global Wayland message pump thread during Bind (but never at the same time) and only from the global thread after Bind returns.
Events that occur immediately upon binding are only delivered reliably if Bind is called from the Wayland message pump thread.
Cannot be called after Bind has been called.
Parameters
minVersion minimum version to bind
maxVersion maximum version to bind
addHandler function that is called when a global of the requested type is added
removeHandler function that is called when a global of the requested type is removed
References RequestInternal().
RequestInternal()
void CRegistry::RequestInternal (std::function< wayland::proxy_t()> constructor, std::string const & interfaceName, std::uint32_t minVersion, std::uint32_t maxVersion, AddHandler addHandler, RemoveHandler removeHandler) private
References m_binds, and m_registry.
Referenced by Request().
RequestSingleton()
template<typename T > void KODI::WINDOWING::WAYLAND::CRegistry::RequestSingleton (T & target, std::uint32_t minVersion, std::uint32_t maxVersion, bool required = true) inline
Request a static singleton global to be bound to a proxy
You should only use this if the singleton is announced at registry bind time (not dynamically) and you do not need to catch events that are sent immediately in response to the bind. Use Request in that case, even if there is ever only one instance of the object at maximum.
Cannot be called after Bind has been called.
Parameters
target target of waylandpp proxy type
minVersion minimum version to bind
maxVersion maximum version to bind
required whether to throw an exception when the bind cannot be satisfied by the compositor - exception is thrown in Bind
References RequestSingletonInternal().
Referenced by KODI::WINDOWING::WAYLAND::CWindowDecorator::CWindowDecorator().
RequestSingletonInternal()
void CRegistry::RequestSingletonInternal (wayland::proxy_t & target, std::string const & interfaceName, std::uint32_t minVersion, std::uint32_t maxVersion, bool required) private
References m_registry, and m_singletonBinds.
Referenced by RequestSingleton().
UnbindSingletons()
void CRegistry::UnbindSingletons ()
Unbind all singletons requested with RequestSingleton
References m_singletonBinds.
Member Data Documentation
m_binds
std::map<std::string, BindInfo> KODI::WINDOWING::WAYLAND::CRegistry::m_binds private
Referenced by Bind(), and RequestInternal().
m_boundNames
std::map<std::uint32_t, std::reference_wrapper<BindInfo> > KODI::WINDOWING::WAYLAND::CRegistry::m_boundNames private
Referenced by Bind().
m_connection
CConnection& KODI::WINDOWING::WAYLAND::CRegistry::m_connection private
Referenced by Bind().
m_registry
wayland::registry_t KODI::WINDOWING::WAYLAND::CRegistry::m_registry private
Referenced by Bind(), RequestInternal(), and RequestSingletonInternal().
m_singletonBinds
std::map<std::string, SingletonBindInfo> KODI::WINDOWING::WAYLAND::CRegistry::m_singletonBinds private
Referenced by Bind(), CheckRequired(), RequestSingletonInternal(), and UnbindSingletons().
The documentation for this class was generated from the following files:
Registry.h
Registry.cpp