Kodi Documentation: KODI::KEYMAP::IKeyHandler Class Reference
KODI::KEYMAP::IKeyHandler Class Reference abstract
Interface for handling keymap keys.
#include <IKeyHandler.h>
Public Member Functions
virtual ~IKeyHandler ()=default
virtual bool IsPressed () const =0
Return true if the key is "pressed" (has a magnitude greater than 0.5)
virtual bool OnDigitalMotion (bool bPressed, unsigned int holdTimeMs)=0
A key mapped to a digital feature has been pressed or released.
virtual bool OnAnalogMotion (float magnitude, unsigned int motionTimeMs)=0
Callback for keys mapped to analog features.
Detailed Description
Interface for handling keymap keys.
Keys can be mapped to analog actions (e.g. "AnalogSeekForward") or digital actions (e.g. "Up").
Constructor & Destructor Documentation
~IKeyHandler()
virtual KODI::KEYMAP::IKeyHandler::~IKeyHandler () virtual default
Member Function Documentation
IsPressed()
virtual bool KODI::KEYMAP::IKeyHandler::IsPressed () const pure virtual
Return true if the key is "pressed" (has a magnitude greater than 0.5)
Returns
True if the key is "pressed", false otherwise
Implemented in KODI::KEYMAP::CKeyHandler.
OnAnalogMotion()
virtual bool KODI::KEYMAP::IKeyHandler::OnAnalogMotion (float magnitude, unsigned int motionTimeMs) pure virtual
Callback for keys mapped to analog features.
Parameters
magnitude The amount of the analog action
motionTimeMs The time since the magnitude was 0
Returns
True if the key is mapped to an action, false otherwise
Implemented in KODI::KEYMAP::CKeyHandler.
Referenced by KODI::KEYMAP::CKeymapHandler::ActivateDirection(), KODI::KEYMAP::CKeymapHandler::ActivateDirection(), KODI::KEYMAP::CKeymapHandler::ActivateDirection(), KODI::KEYMAP::CKeymapHandler::DeactivateDirection(), KODI::KEYMAP::CKeymapHandler::DeactivateDirection(), KODI::KEYMAP::CKeymapHandler::DeactivateDirection(), and KODI::KEYMAP::CKeymapHandler::OnButtonMotion().
OnDigitalMotion()
virtual bool KODI::KEYMAP::IKeyHandler::OnDigitalMotion (bool bPressed, unsigned int holdTimeMs) pure virtual
A key mapped to a digital feature has been pressed or released.
Parameters
bPressed true if the key's button/axis is activated, false if deactivated
holdTimeMs The held time in ms for pressed buttons, or 0 for released
Returns
True if the key is mapped to an action, false otherwise
Implemented in KODI::KEYMAP::CKeyHandler.
Referenced by KODI::KEYMAP::CKeymapHandler::OnButtonHold(), and KODI::KEYMAP::CKeymapHandler::OnButtonPress().
The documentation for this class was generated from the following file:
IKeyHandler.h