Kodi Documentation: anonymous_namespace{PVRBuiltins.cpp} Namespace Reference
anonymous_namespace{PVRBuiltins.cpp} Namespace Reference
Functions
int EpgGridControl (const std::vector< std::string > &params)
Control PVR Guide window's EPG grid.
Function Documentation
EpgGridControl()
int anonymous_namespace{PVRBuiltins.cpp}::EpgGridControl (const std::vector< std::string > & params)
Control PVR Guide window's EPG grid.
Parameters
params The parameters
params[0] = Control to execute.
References PVR::CGUIWindowPVRBase::ActivateNextChannelGroup(), PVR::CGUIWindowPVRBase::ActivatePreviousChannelGroup(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), PVR::CGUIWindowPVRGuideBase::GotoBegin(), PVR::CGUIWindowPVRGuideBase::GotoCurrentProgramme(), PVR::CGUIWindowPVRGuideBase::GotoDate(), PVR::CGUIWindowPVRGuideBase::GotoEnd(), PVR::CGUIWindowPVRGuideBase::GotoFirstChannel(), PVR::CGUIWindowPVRGuideBase::GotoLastChannel(), PVR::CGUIWindowPVRGuideBase::GotoPlayingChannel(), CLog::Log(), LOGERROR, PVR::CGUIWindowPVRBase::OpenChannelGroupSelectionDialog(), PVR::CGUIWindowPVRGuideBase::OpenDateSelectionDialog(), KODI::UTILS::StringUtils::StartsWithNoCase(), KODI::UTILS::StringUtils::ToLower(), WINDOW_RADIO_GUIDE, and WINDOW_TV_GUIDE.