Kodi Documentation: KODI::KEYBOARD::CKeyboardTranslator Class Reference
KODI::KEYBOARD::CKeyboardTranslator Class Reference
Keyboard translation utilities.
#include <KeyboardTranslator.h>
Static Public Member Functions
static XBMCKey TranslateKeysym (const SymbolName &symbolName)
Translate a keyboard symbol to a Kodi key code.
static const char * TranslateKeycode (XBMCKey keycode)
Translate a Kodi key code to a keyboard symbol.
Detailed Description
Keyboard translation utilities.
Member Function Documentation
TranslateKeycode()
const char * CKeyboardTranslator::TranslateKeycode (XBMCKey keycode) static
Translate a Kodi key code to a keyboard symbol.
Parameters
keycode The Kodi key code
Returns
The key's symbol, or an empty string if no symbol is defined for the keycode
References KODI::KEYBOARD::KEY_SYMBOL_0, KODI::KEYBOARD::KEY_SYMBOL_1, KODI::KEYBOARD::KEY_SYMBOL_2, KODI::KEYBOARD::KEY_SYMBOL_3, KODI::KEYBOARD::KEY_SYMBOL_4, KODI::KEYBOARD::KEY_SYMBOL_5, KODI::KEYBOARD::KEY_SYMBOL_6, KODI::KEYBOARD::KEY_SYMBOL_7, KODI::KEYBOARD::KEY_SYMBOL_8, KODI::KEYBOARD::KEY_SYMBOL_9, KODI::KEYBOARD::KEY_SYMBOL_A, KODI::KEYBOARD::KEY_SYMBOL_AMPERSAND, KODI::KEYBOARD::KEY_SYMBOL_ASTERISK, KODI::KEYBOARD::KEY_SYMBOL_AT, KODI::KEYBOARD::KEY_SYMBOL_B, KODI::KEYBOARD::KEY_SYMBOL_BACKSLASH, KODI::KEYBOARD::KEY_SYMBOL_BACKSPACE, KODI::KEYBOARD::KEY_SYMBOL_BAR, KODI::KEYBOARD::KEY_SYMBOL_BREAK, KODI::KEYBOARD::KEY_SYMBOL_C, KODI::KEYBOARD::KEY_SYMBOL_CAPSLOCK, KODI::KEYBOARD::KEY_SYMBOL_CARET, KODI::KEYBOARD::KEY_SYMBOL_CLEAR, KODI::KEYBOARD::KEY_SYMBOL_COLON, KODI::KEYBOARD::KEY_SYMBOL_COMMA, KODI::KEYBOARD::KEY_SYMBOL_COMPOSE, KODI::KEYBOARD::KEY_SYMBOL_D, KODI::KEYBOARD::KEY_SYMBOL_DELETE, KODI::KEYBOARD::KEY_SYMBOL_DOLLAR, KODI::KEYBOARD::KEY_SYMBOL_DOUBLEQUOTE, KODI::KEYBOARD::KEY_SYMBOL_DOWN, KODI::KEYBOARD::KEY_SYMBOL_E, KODI::KEYBOARD::KEY_SYMBOL_END, KODI::KEYBOARD::KEY_SYMBOL_ENTER, KODI::KEYBOARD::KEY_SYMBOL_EQUALS, KODI::KEYBOARD::KEY_SYMBOL_ESCAPE, KODI::KEYBOARD::KEY_SYMBOL_EURO, KODI::KEYBOARD::KEY_SYMBOL_EXCLAIM, KODI::KEYBOARD::KEY_SYMBOL_F, KODI::KEYBOARD::KEY_SYMBOL_F1, KODI::KEYBOARD::KEY_SYMBOL_F10, KODI::KEYBOARD::KEY_SYMBOL_F11, KODI::KEYBOARD::KEY_SYMBOL_F12, KODI::KEYBOARD::KEY_SYMBOL_F13, KODI::KEYBOARD::KEY_SYMBOL_F14, KODI::KEYBOARD::KEY_SYMBOL_F15, KODI::KEYBOARD::KEY_SYMBOL_F2, KODI::KEYBOARD::KEY_SYMBOL_F3, KODI::KEYBOARD::KEY_SYMBOL_F4, KODI::KEYBOARD::KEY_SYMBOL_F5, KODI::KEYBOARD::KEY_SYMBOL_F6, KODI::KEYBOARD::KEY_SYMBOL_F7, KODI::KEYBOARD::KEY_SYMBOL_F8, KODI::KEYBOARD::KEY_SYMBOL_F9, KODI::KEYBOARD::KEY_SYMBOL_G, KODI::KEYBOARD::KEY_SYMBOL_GRAVE, KODI::KEYBOARD::KEY_SYMBOL_GREATER, KODI::KEYBOARD::KEY_SYMBOL_H, KODI::KEYBOARD::KEY_SYMBOL_HASH, KODI::KEYBOARD::KEY_SYMBOL_HELP, KODI::KEYBOARD::KEY_SYMBOL_HOME, KODI::KEYBOARD::KEY_SYMBOL_I, KODI::KEYBOARD::KEY_SYMBOL_INSERT, KODI::KEYBOARD::KEY_SYMBOL_J, KODI::KEYBOARD::KEY_SYMBOL_K, KODI::KEYBOARD::KEY_SYMBOL_KP0, KODI::KEYBOARD::KEY_SYMBOL_KP1, KODI::KEYBOARD::KEY_SYMBOL_KP2, KODI::KEYBOARD::KEY_SYMBOL_KP3, KODI::KEYBOARD::KEY_SYMBOL_KP4, KODI::KEYBOARD::KEY_SYMBOL_KP5, KODI::KEYBOARD::KEY_SYMBOL_KP6, KODI::KEYBOARD::KEY_SYMBOL_KP7, KODI::KEYBOARD::KEY_SYMBOL_KP8, KODI::KEYBOARD::KEY_SYMBOL_KP9, KODI::KEYBOARD::KEY_SYMBOL_KPDIVIDE, KODI::KEYBOARD::KEY_SYMBOL_KPENTER, KODI::KEYBOARD::KEY_SYMBOL_KPEQUALS, KODI::KEYBOARD::KEY_SYMBOL_KPMINUS, KODI::KEYBOARD::KEY_SYMBOL_KPMULTIPLY, KODI::KEYBOARD::KEY_SYMBOL_KPPERIOD, KODI::KEYBOARD::KEY_SYMBOL_KPPLUS, KODI::KEYBOARD::KEY_SYMBOL_L, KODI::KEYBOARD::KEY_SYMBOL_LEFT, KODI::KEYBOARD::KEY_SYMBOL_LEFTALT, KODI::KEYBOARD::KEY_SYMBOL_LEFTBRACE, KODI::KEYBOARD::KEY_SYMBOL_LEFTBRACKET, KODI::KEYBOARD::KEY_SYMBOL_LEFTCTRL, KODI::KEYBOARD::KEY_SYMBOL_LEFTMETA, KODI::KEYBOARD::KEY_SYMBOL_LEFTPAREN, KODI::KEYBOARD::KEY_SYMBOL_LEFTSHIFT, KODI::KEYBOARD::KEY_SYMBOL_LEFTSUPER, KODI::KEYBOARD::KEY_SYMBOL_LESS, KODI::KEYBOARD::KEY_SYMBOL_M, KODI::KEYBOARD::KEY_SYMBOL_MENU, KODI::KEYBOARD::KEY_SYMBOL_MINUS, KODI::KEYBOARD::KEY_SYMBOL_MODE, KODI::KEYBOARD::KEY_SYMBOL_N, KODI::KEYBOARD::KEY_SYMBOL_NUMLOCK, KODI::KEYBOARD::KEY_SYMBOL_O, KODI::KEYBOARD::KEY_SYMBOL_OEM102, KODI::KEYBOARD::KEY_SYMBOL_P, KODI::KEYBOARD::KEY_SYMBOL_PAGEDOWN, KODI::KEYBOARD::KEY_SYMBOL_PAGEUP, KODI::KEYBOARD::KEY_SYMBOL_PAUSE, KODI::KEYBOARD::KEY_SYMBOL_PERIOD, KODI::KEYBOARD::KEY_SYMBOL_PLUS, KODI::KEYBOARD::KEY_SYMBOL_POWER, KODI::KEYBOARD::KEY_SYMBOL_PRINTSCREEN, KODI::KEYBOARD::KEY_SYMBOL_Q, KODI::KEYBOARD::KEY_SYMBOL_QUESTION, KODI::KEYBOARD::KEY_SYMBOL_QUOTE, KODI::KEYBOARD::KEY_SYMBOL_R, KODI::KEYBOARD::KEY_SYMBOL_RIGHT, KODI::KEYBOARD::KEY_SYMBOL_RIGHTALT, KODI::KEYBOARD::KEY_SYMBOL_RIGHTBRACE, KODI::KEYBOARD::KEY_SYMBOL_RIGHTBRACKET, KODI::KEYBOARD::KEY_SYMBOL_RIGHTCTRL, KODI::KEYBOARD::KEY_SYMBOL_RIGHTMETA, KODI::KEYBOARD::KEY_SYMBOL_RIGHTPAREN, KODI::KEYBOARD::KEY_SYMBOL_RIGHTSHIFT, KODI::KEYBOARD::KEY_SYMBOL_RIGHTSUPER, KODI::KEYBOARD::KEY_SYMBOL_S, KODI::KEYBOARD::KEY_SYMBOL_SCROLLLOCK, KODI::KEYBOARD::KEY_SYMBOL_SEMICOLON, KODI::KEYBOARD::KEY_SYMBOL_SLASH, KODI::KEYBOARD::KEY_SYMBOL_SPACE, KODI::KEYBOARD::KEY_SYMBOL_SYSREQ, KODI::KEYBOARD::KEY_SYMBOL_T, KODI::KEYBOARD::KEY_SYMBOL_TAB, KODI::KEYBOARD::KEY_SYMBOL_TILDE, KODI::KEYBOARD::KEY_SYMBOL_U, KODI::KEYBOARD::KEY_SYMBOL_UNDERSCORE, KODI::KEYBOARD::KEY_SYMBOL_UNDO, KODI::KEYBOARD::KEY_SYMBOL_UP, KODI::KEYBOARD::KEY_SYMBOL_V, KODI::KEYBOARD::KEY_SYMBOL_W, KODI::KEYBOARD::KEY_SYMBOL_X, KODI::KEYBOARD::KEY_SYMBOL_Y, KODI::KEYBOARD::KEY_SYMBOL_Z, XBMCK_0, XBMCK_1, XBMCK_2, XBMCK_3, XBMCK_4, XBMCK_5, XBMCK_6, XBMCK_7, XBMCK_8, XBMCK_9, XBMCK_a, XBMCK_AMPERSAND, XBMCK_ASTERISK, XBMCK_AT, XBMCK_b, XBMCK_BACKQUOTE, XBMCK_BACKSLASH, XBMCK_BACKSPACE, XBMCK_BREAK, XBMCK_c, XBMCK_CAPSLOCK, XBMCK_CARET, XBMCK_CLEAR, XBMCK_COLON, XBMCK_COMMA, XBMCK_COMPOSE, XBMCK_d, XBMCK_DELETE, XBMCK_DOLLAR, XBMCK_DOWN, XBMCK_e, XBMCK_END, XBMCK_EQUALS, XBMCK_ESCAPE, XBMCK_EURO, XBMCK_EXCLAIM, XBMCK_f, XBMCK_F1, XBMCK_F10, XBMCK_F11, XBMCK_F12, XBMCK_F13, XBMCK_F14, XBMCK_F15, XBMCK_F2, XBMCK_F3, XBMCK_F4, XBMCK_F5, XBMCK_F6, XBMCK_F7, XBMCK_F8, XBMCK_F9, XBMCK_g, XBMCK_GREATER, XBMCK_h, XBMCK_HASH, XBMCK_HELP, XBMCK_HOME, XBMCK_i, XBMCK_INSERT, XBMCK_j, XBMCK_k, XBMCK_KP0, XBMCK_KP1, XBMCK_KP2, XBMCK_KP3, XBMCK_KP4, XBMCK_KP5, XBMCK_KP6, XBMCK_KP7, XBMCK_KP8, XBMCK_KP9, XBMCK_KP_DIVIDE, XBMCK_KP_ENTER, XBMCK_KP_EQUALS, XBMCK_KP_MINUS, XBMCK_KP_MULTIPLY, XBMCK_KP_PERIOD, XBMCK_KP_PLUS, XBMCK_l, XBMCK_LALT, XBMCK_LCTRL, XBMCK_LEFT, XBMCK_LEFTBRACE, XBMCK_LEFTBRACKET, XBMCK_LEFTPAREN, XBMCK_LESS, XBMCK_LMETA, XBMCK_LSHIFT, XBMCK_LSUPER, XBMCK_m, XBMCK_MENU, XBMCK_MINUS, XBMCK_MODE, XBMCK_n, XBMCK_NUMLOCK, XBMCK_o, XBMCK_OEM_102, XBMCK_p, XBMCK_PAGEDOWN, XBMCK_PAGEUP, XBMCK_PAUSE, XBMCK_PERIOD, XBMCK_PIPE, XBMCK_PLUS, XBMCK_POWER, XBMCK_PRINT, XBMCK_q, XBMCK_QUESTION, XBMCK_QUOTE, XBMCK_QUOTEDBL, XBMCK_r, XBMCK_RALT, XBMCK_RCTRL, XBMCK_RETURN, XBMCK_RIGHT, XBMCK_RIGHTBRACE, XBMCK_RIGHTBRACKET, XBMCK_RIGHTPAREN, XBMCK_RMETA, XBMCK_RSHIFT, XBMCK_RSUPER, XBMCK_s, XBMCK_SCROLLOCK, XBMCK_SEMICOLON, XBMCK_SLASH, XBMCK_SPACE, XBMCK_SYSREQ, XBMCK_t, XBMCK_TAB, XBMCK_TILDE, XBMCK_u, XBMCK_UNDERSCORE, XBMCK_UNDO, XBMCK_UP, XBMCK_v, XBMCK_w, XBMCK_x, XBMCK_XKB_KP0, XBMCK_XKB_KP1, XBMCK_XKB_KP2, XBMCK_XKB_KP3, XBMCK_XKB_KP4, XBMCK_XKB_KP5, XBMCK_XKB_KP6, XBMCK_XKB_KP7, XBMCK_XKB_KP8, XBMCK_XKB_KP9, XBMCK_XKB_KP_ADD, XBMCK_XKB_KP_BEGIN, XBMCK_XKB_KP_DECIMAL, XBMCK_XKB_KP_DELETE, XBMCK_XKB_KP_DIVIDE, XBMCK_XKB_KP_DOWN, XBMCK_XKB_KP_END, XBMCK_XKB_KP_ENTER, XBMCK_XKB_KP_EQUALS, XBMCK_XKB_KP_F1, XBMCK_XKB_KP_F2, XBMCK_XKB_KP_F3, XBMCK_XKB_KP_F4, XBMCK_XKB_KP_HOME, XBMCK_XKB_KP_INSERT, XBMCK_XKB_KP_LEFT, XBMCK_XKB_KP_MULTIPLY, XBMCK_XKB_KP_PAGE_DOWN, XBMCK_XKB_KP_PAGE_UP, XBMCK_XKB_KP_RIGHT, XBMCK_XKB_KP_SPACE, XBMCK_XKB_KP_SUBTRACT, XBMCK_XKB_KP_TAB, XBMCK_XKB_KP_UP, XBMCK_y, and XBMCK_z.
Referenced by KODI::GAME::CGUIConfigurationWizard::MapPrimitive(), KODI::GAME::CGUIConfigurationWizard::RegisterKey(), TEST(), KODI::JOYSTICK::CDriverPrimitive::ToString(), KODI::KEYBOARD::CKeyboardStat::TranslateKey(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
TranslateKeysym()
XBMCKey CKeyboardTranslator::TranslateKeysym (const SymbolName & symbolName) static
Translate a keyboard symbol to a Kodi key code.
Keyboard symbols are hardware-independent virtual key representations. They are used to help facilitate keyboard mapping.
Parameters
symbol The key's symbol, defined in the Controller Topology Project: https://github.com/kodi-game/controller-topology-project/blob/master/Readme-Keyboard.md
Returns
The layout-independent keycode associated with the key
References XBMCK_UNKNOWN.
Referenced by KODI::GAME::CPhysicalFeature::Deserialize(), TEST(), and PERIPHERALS::CPeripheralAddonTranslator::TranslatePrimitive().
The documentation for this class was generated from the following files:
keyboard/KeyboardTranslator.h
keyboard/KeyboardTranslator.cpp