Kodi Documentation: DllLoaderContainer Class Reference
DllLoaderContainer Class Reference
#include <DllLoaderContainer.h>
Static Public Member Functions
static LibraryLoader * GetModule (const char *sName)
static LibraryLoader * GetModule (const HMODULE hModule)
static LibraryLoader * LoadModule (const char *sName, const char *sCurrentDir=NULL, bool bLoadSymbols=false)
static void ReleaseModule (LibraryLoader *&pDll)
static void RegisterDll (LibraryLoader *pDll)
static void UnRegisterDll (LibraryLoader *pDll)
Static Private Member Functions
static LibraryLoader * FindModule (const char *sName, const char *sCurrentDir, bool bLoadSymbols)
static LibraryLoader * LoadDll (const char *sName, bool bLoadSymbols)
static bool IsSystemDll (const char *sName)
Static Private Attributes
static LibraryLoader * m_dlls [64] = {}
static int m_iNrOfDlls = 0
Member Function Documentation
FindModule()
LibraryLoader * DllLoaderContainer::FindModule (const char * sName, const char * sCurrentDir, bool bLoadSymbols) static private
References URIUtils::AddSlashAtEnd(), XFILE::CFile::Copy(), ENV_PATH, XFILE::CFile::Exists(), FindModule(), CURL::GetFileName(), GetModule(), URIUtils::IsInArchive(), LoadDll(), CLog::Log(), and LOGDEBUG.
Referenced by FindModule(), and LoadModule().
GetModule() [1/2]
LibraryLoader * DllLoaderContainer::GetModule (const char * sName) static
References IsSystemDll(), m_dlls, and m_iNrOfDlls.
Referenced by dllFreeLibrary(), dllGetModuleHandleA(), FindModule(), LoadModule(), and Win32DllLoader::NeedsHooking().
GetModule() [2/2]
LibraryLoader * DllLoaderContainer::GetModule (const HMODULE hModule) static
References m_dlls, and m_iNrOfDlls.
IsSystemDll()
bool DllLoaderContainer::IsSystemDll (const char * sName) static private
References IsSystemDll(), m_dlls, and m_iNrOfDlls.
Referenced by GetModule(), IsSystemDll(), and LoadModule().
LoadDll()
LibraryLoader * DllLoaderContainer::LoadDll (const char * sName, bool bLoadSymbols) static private
References LibraryLoader::Load(), CLog::Log(), LOGDEBUG, and LOGERROR.
Referenced by FindModule().
LoadModule()
LibraryLoader * DllLoaderContainer::LoadModule (const char * sName, const char * sCurrentDir = NULL, bool bLoadSymbols = false) static
References FindModule(), LibraryLoader::GetFileName(), GetModule(), LibraryLoader::IncrRef(), LibraryLoader::IsSystemDll(), IsSystemDll(), CLog::Log(), and LOGDEBUG.
Referenced by dllLoadLibraryExtended(), and CSectionLoader::LoadDLL().
RegisterDll()
void DllLoaderContainer::RegisterDll (LibraryLoader * pDll) static
References m_dlls, and m_iNrOfDlls.
Referenced by Win32DllLoader::Win32DllLoader().
ReleaseModule()
void DllLoaderContainer::ReleaseModule (LibraryLoader *& pDll) static
References LibraryLoader::DecrRef(), LibraryLoader::GetFileName(), LibraryLoader::GetName(), LibraryLoader::HasSymbols(), LibraryLoader::IsSystemDll(), CLog::Log(), LOGDEBUG, LOGFATAL, LOGINFO, and LibraryLoader::Unload().
Referenced by dllFreeLibrary(), CSectionLoader::UnloadAll(), CSectionLoader::UnloadDelayed(), and CSectionLoader::UnloadDLL().
UnRegisterDll()
void DllLoaderContainer::UnRegisterDll (LibraryLoader * pDll) static
References LibraryLoader::GetName(), LibraryLoader::IsSystemDll(), CLog::Log(), LOGFATAL, m_dlls, and m_iNrOfDlls.
Referenced by Win32DllLoader::~Win32DllLoader().
Member Data Documentation
m_dlls
LibraryLoader * DllLoaderContainer::m_dlls = {} static private
Referenced by GetModule(), GetModule(), IsSystemDll(), RegisterDll(), and UnRegisterDll().
m_iNrOfDlls
int DllLoaderContainer::m_iNrOfDlls = 0 static private
Referenced by GetModule(), GetModule(), IsSystemDll(), RegisterDll(), and UnRegisterDll().
The documentation for this class was generated from the following files:
DllLoaderContainer.h
DllLoaderContainer.cpp