Kodi Documentation: ADDON::Interface_AudioEngine Struct Reference
ADDON::Interface_AudioEngine Struct Reference
#include <AudioEngine.h>
Static Public Member Functions
static void Init (AddonGlobalInterface *addonInterface)
static void DeInit (AddonGlobalInterface *addonInterface)
static AEChannel TranslateAEChannelToKodi (AudioEngineChannel channel)
Translation functions to separate Kodi and addons.
static AudioEngineChannel TranslateAEChannelToAddon (AEChannel channel)
static AEDataFormat TranslateAEFormatToKodi (AudioEngineDataFormat format)
static AudioEngineDataFormat TranslateAEFormatToAddon (AEDataFormat format)
static AEStreamHandle * audioengine_make_stream (void *kodiBase, AUDIO_ENGINE_FORMAT *streamFormat, unsigned int options)
static void audioengine_free_stream (void *kodiBase, AEStreamHandle *streamHandle)
static bool get_current_sink_format (void *kodiBase, AUDIO_ENGINE_FORMAT *sinkFormat)
static unsigned int aestream_get_space (void *kodiBase, AEStreamHandle *streamHandle)
static unsigned int aestream_add_data (void *kodiBase, AEStreamHandle *streamHandle, uint8_t *const *data, unsigned int offset, unsigned int frames, double pts, bool hasDownmix, double centerMixLevel)
static double aestream_get_delay (void *kodiBase, AEStreamHandle *streamHandle)
static bool aestream_is_buffering (void *kodiBase, AEStreamHandle *streamHandle)
static double aestream_get_cache_time (void *kodiBase, AEStreamHandle *streamHandle)
static double aestream_get_cache_total (void *kodiBase, AEStreamHandle *streamHandle)
static void aestream_pause (void *kodiBase, AEStreamHandle *streamHandle)
static void aestream_resume (void *kodiBase, AEStreamHandle *streamHandle)
static void aestream_drain (void *kodiBase, AEStreamHandle *streamHandle, bool wait)
static bool aestream_is_draining (void *kodiBase, AEStreamHandle *streamHandle)
static bool aestream_is_drained (void *kodiBase, AEStreamHandle *streamHandle)
static void aestream_flush (void *kodiBase, AEStreamHandle *streamHandle)
static float aestream_get_volume (void *kodiBase, AEStreamHandle *streamHandle)
static void aestream_set_volume (void *kodiBase, AEStreamHandle *streamHandle, float volume)
static float aestream_get_amplification (void *kodiBase, AEStreamHandle *streamHandle)
static void aestream_set_amplification (void *kodiBase, AEStreamHandle *streamHandle, float amplify)
static unsigned int aestream_get_frame_size (void *kodiBase, AEStreamHandle *streamHandle)
static unsigned int aestream_get_channel_count (void *kodiBase, AEStreamHandle *streamHandle)
static unsigned int aestream_get_sample_rate (void *kodiBase, AEStreamHandle *streamHandle)
static AudioEngineDataFormat aestream_get_data_format (void *kodiBase, AEStreamHandle *streamHandle)
static double aestream_get_resample_ratio (void *kodiBase, AEStreamHandle *streamHandle)
static void aestream_set_resample_ratio (void *kodiBase, AEStreamHandle *streamHandle, double ratio)
Member Function Documentation
aestream_add_data()
unsigned int ADDON::Interface_AudioEngine::aestream_add_data (void * kodiBase, AEStreamHandle * streamHandle, uint8_t *const * data, unsigned int offset, unsigned int frames, double pts, bool hasDownmix, double centerMixLevel) static
Add planar or interleaved PCM data to the stream
Parameters
[in] data array of pointers to the planes
[in] offset to frame in frames
[in] frames number of frames
Returns
The number of frames consumed
References IAEStream::ExtData::centerMixLevel, data(), CServiceBroker::GetActiveAE(), IAEStream::ExtData::hasDownmix, CLog::Log(), LOGERROR, and IAEStream::ExtData::pts.
Referenced by Init().
aestream_drain()
void ADDON::Interface_AudioEngine::aestream_drain (void * kodiBase, AEStreamHandle * streamHandle, bool wait) static
Start draining the stream
Note
Once called AddData will not consume more data.
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_flush()
void ADDON::Interface_AudioEngine::aestream_flush (void * kodiBase, AEStreamHandle * streamHandle) static
Flush all buffers dropping the audio data
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_get_amplification()
float ADDON::Interface_AudioEngine::aestream_get_amplification (void * kodiBase, AEStreamHandle * streamHandle) static
Gets the stream's volume amplification in linear units.
Returns
The volume amplification factor between 1.0 and 1000.0
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_get_cache_time()
double ADDON::Interface_AudioEngine::aestream_get_cache_time (void * kodiBase, AEStreamHandle * streamHandle) static
Returns the time in seconds that it will take to underrun the cache if no sample is added.
Returns
seconds
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_get_cache_total()
double ADDON::Interface_AudioEngine::aestream_get_cache_total (void * kodiBase, AEStreamHandle * streamHandle) static
Returns the total time in seconds of the cache
Returns
seconds
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_get_channel_count()
unsigned int ADDON::Interface_AudioEngine::aestream_get_channel_count (void * kodiBase, AEStreamHandle * streamHandle) static
Returns the number of channels the stream is configured to accept
Returns
The channel count
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_get_data_format()
AudioEngineDataFormat ADDON::Interface_AudioEngine::aestream_get_data_format (void * kodiBase, AEStreamHandle * streamHandle) static
Return the data format the stream has been configured with
Returns
The stream's data format (eg, AE_FMT_S16LE)
References AUDIOENGINE_FMT_INVALID, CServiceBroker::GetActiveAE(), CLog::Log(), LOGERROR, and TranslateAEFormatToAddon().
Referenced by Init().
aestream_get_delay()
double ADDON::Interface_AudioEngine::aestream_get_delay (void * kodiBase, AEStreamHandle * streamHandle) static
Returns the time in seconds that it will take for the next added packet to be heard from the speakers.
Returns
seconds
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_get_frame_size()
unsigned int ADDON::Interface_AudioEngine::aestream_get_frame_size (void * kodiBase, AEStreamHandle * streamHandle) static
Returns the size of one audio frame in bytes (channelCount * resolution)
Returns
The size in bytes of one frame
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_get_resample_ratio()
double ADDON::Interface_AudioEngine::aestream_get_resample_ratio (void * kodiBase, AEStreamHandle * streamHandle) static
Return the resample ratio
Note
This will return an undefined value if the stream is not resampling
Returns
the current resample ratio or undefined if the stream is not resampling
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_get_sample_rate()
unsigned int ADDON::Interface_AudioEngine::aestream_get_sample_rate (void * kodiBase, AEStreamHandle * streamHandle) static
Returns the stream's sample rate, if the stream is using a dynamic sample rate, this value will NOT reflect any changes made by calls to SetResampleRatio()
Returns
The stream's sample rate (eg, 48000)
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_get_space()
unsigned int ADDON::Interface_AudioEngine::aestream_get_space (void * kodiBase, AEStreamHandle * streamHandle) static
Returns the amount of space available in the stream
Returns
The number of bytes AddData will consume
References CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_get_volume()
float ADDON::Interface_AudioEngine::aestream_get_volume (void * kodiBase, AEStreamHandle * streamHandle) static
Return the stream's current volume level
Returns
The volume level between 0.0 and 1.0
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_is_buffering()
bool ADDON::Interface_AudioEngine::aestream_is_buffering (void * kodiBase, AEStreamHandle * streamHandle) static
Returns if the stream is buffering
Returns
True if the stream is buffering
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_is_drained()
bool ADDON::Interface_AudioEngine::aestream_is_drained (void * kodiBase, AEStreamHandle * streamHandle) static
Returns true if the is stream has finished draining
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_is_draining()
bool ADDON::Interface_AudioEngine::aestream_is_draining (void * kodiBase, AEStreamHandle * streamHandle) static
Returns true if the is stream draining
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_pause()
void ADDON::Interface_AudioEngine::aestream_pause (void * kodiBase, AEStreamHandle * streamHandle) static
Pauses the stream playback
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_resume()
void ADDON::Interface_AudioEngine::aestream_resume (void * kodiBase, AEStreamHandle * streamHandle) static
Resumes the stream after pausing
References CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_set_amplification()
void ADDON::Interface_AudioEngine::aestream_set_amplification (void * kodiBase, AEStreamHandle * streamHandle, float amplify) static
Sets the stream's volume amplification in linear units.
Parameters
amplify The volume amplification factor between 1.0 and 1000.0
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_set_resample_ratio()
void ADDON::Interface_AudioEngine::aestream_set_resample_ratio (void * kodiBase, AEStreamHandle * streamHandle, double ratio) static
Sets the resample ratio
Note
This function may return false if the stream is not resampling, if you wish to use this be sure to set the AESTREAM_FORCE_RESAMPLE option
Parameters
[in] ratio the new sample rate ratio, calculated by ((double)desiredRate / (double)GetSampleRate())
References CServiceBroker::GetActiveAE(), CLog::Log(), and LOGERROR.
Referenced by Init().
aestream_set_volume()
void ADDON::Interface_AudioEngine::aestream_set_volume (void * kodiBase, AEStreamHandle * streamHandle, float volume) static
Set the stream's volume level
Parameters
volume The new volume level between 0.0 and 1.0
References CServiceBroker::GetActiveAE(), CLog::Log(), LOGERROR, and SetVolume().
Referenced by Init().
audioengine_free_stream()
void ADDON::Interface_AudioEngine::audioengine_free_stream (void * kodiBase, AEStreamHandle * streamHandle) static
This method will remove the specified stream from the engine. For OSX/IOS this is essential to reconfigure the audio output.
Parameters
[in] streamHandle The stream to be altered
References IAE::FreeStream(), CServiceBroker::GetActiveAE(), CLog::Log(), and LOGERROR.
Referenced by Init().
audioengine_make_stream()
AEStreamHandle * ADDON::Interface_AudioEngine::audioengine_make_stream (void * kodiBase, AUDIO_ENGINE_FORMAT * streamFormat, unsigned int options) static
Creates and returns a new handle to an IAEStream in the format specified, this function should never fail
Parameters
[in] streamFormat Format to use for stream
[in] options A bit field of stream options (see: enum AEStreamOptions)
Returns
a new Handle to an IAEStream that will accept data in the requested format
References AESTREAM_AUTOSTART, AESTREAM_FORCE_RESAMPLE, AESTREAM_PAUSED, AUDIO_STREAM_AUTOSTART, AUDIO_STREAM_FORCE_RESAMPLE, AUDIO_STREAM_PAUSED, AUDIOENGINE_CH_MAX, AUDIOENGINE_CH_NULL, CServiceBroker::GetActiveAE(), CLog::Log(), LOGERROR, AEAudioFormat::m_channelLayout, AUDIO_ENGINE_FORMAT::m_channels, AUDIO_ENGINE_FORMAT::m_dataFormat, AUDIO_ENGINE_FORMAT::m_sampleRate, IAE::MakeStream(), TranslateAEChannelToKodi(), and TranslateAEFormatToKodi().
Referenced by Init().
DeInit()
void ADDON::Interface_AudioEngine::DeInit (AddonGlobalInterface * addonInterface) static
References AddonToKodiFuncTable_Addon::kodi_audioengine, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_Base::DeInitInterface().
get_current_sink_format()
bool ADDON::Interface_AudioEngine::get_current_sink_format (void * kodiBase, AUDIO_ENGINE_FORMAT * sinkFormat) static
Get the current sink data format
Parameters
[in] sinkFormat sink data format. For more details see AUDIO_ENGINE_FORMAT.
Returns
Returns true on success, else false.
References AUDIOENGINE_CH_MAX, CAEChannelInfo::Count(), CServiceBroker::GetActiveAE(), IAE::GetCurrentSinkFormat(), CLog::Log(), LOGERROR, AEAudioFormat::m_channelLayout, AEAudioFormat::m_dataFormat, AEAudioFormat::m_frames, AEAudioFormat::m_frameSize, AEAudioFormat::m_sampleRate, TranslateAEChannelToAddon(), and TranslateAEFormatToAddon().
Referenced by Init().
Init()
void ADDON::Interface_AudioEngine::Init (AddonGlobalInterface * addonInterface) static
References aestream_add_data(), AddonToKodiFuncTable_kodi_audioengine::aestream_add_data, aestream_drain(), AddonToKodiFuncTable_kodi_audioengine::aestream_drain, aestream_flush(), AddonToKodiFuncTable_kodi_audioengine::aestream_flush, aestream_get_amplification(), AddonToKodiFuncTable_kodi_audioengine::aestream_get_amplification, aestream_get_cache_time(), AddonToKodiFuncTable_kodi_audioengine::aestream_get_cache_time, aestream_get_cache_total(), AddonToKodiFuncTable_kodi_audioengine::aestream_get_cache_total, aestream_get_channel_count(), AddonToKodiFuncTable_kodi_audioengine::aestream_get_channel_count, aestream_get_data_format(), AddonToKodiFuncTable_kodi_audioengine::aestream_get_data_format, aestream_get_delay(), AddonToKodiFuncTable_kodi_audioengine::aestream_get_delay, aestream_get_frame_size(), AddonToKodiFuncTable_kodi_audioengine::aestream_get_frame_size, aestream_get_resample_ratio(), AddonToKodiFuncTable_kodi_audioengine::aestream_get_resample_ratio, aestream_get_sample_rate(), AddonToKodiFuncTable_kodi_audioengine::aestream_get_sample_rate, aestream_get_space(), AddonToKodiFuncTable_kodi_audioengine::aestream_get_space, aestream_get_volume(), AddonToKodiFuncTable_kodi_audioengine::aestream_get_volume, aestream_is_buffering(), AddonToKodiFuncTable_kodi_audioengine::aestream_is_buffering, aestream_is_drained(), AddonToKodiFuncTable_kodi_audioengine::aestream_is_drained, aestream_is_draining(), AddonToKodiFuncTable_kodi_audioengine::aestream_is_draining, aestream_pause(), AddonToKodiFuncTable_kodi_audioengine::aestream_pause, aestream_resume(), AddonToKodiFuncTable_kodi_audioengine::aestream_resume, aestream_set_amplification(), AddonToKodiFuncTable_kodi_audioengine::aestream_set_amplification, aestream_set_resample_ratio(), AddonToKodiFuncTable_kodi_audioengine::aestream_set_resample_ratio, aestream_set_volume(), AddonToKodiFuncTable_kodi_audioengine::aestream_set_volume, audioengine_free_stream(), audioengine_make_stream(), AddonToKodiFuncTable_kodi_audioengine::free_stream, get_current_sink_format(), AddonToKodiFuncTable_kodi_audioengine::get_current_sink_format, AddonToKodiFuncTable_Addon::kodi_audioengine, AddonToKodiFuncTable_kodi_audioengine::make_stream, and AddonGlobalInterface::toKodi.
Referenced by ADDON::Interface_Base::InitInterface().
TranslateAEChannelToAddon()
AudioEngineChannel ADDON::Interface_AudioEngine::TranslateAEChannelToAddon (AEChannel channel) static
References AE_CH_BC, AE_CH_BL, AE_CH_BLOC, AE_CH_BR, AE_CH_BROC, AE_CH_FC, AE_CH_FL, AE_CH_FLOC, AE_CH_FR, AE_CH_FROC, AE_CH_LFE, AE_CH_MAX, AE_CH_NULL, AE_CH_RAW, AE_CH_SL, AE_CH_SR, AE_CH_TBC, AE_CH_TBL, AE_CH_TBR, AE_CH_TC, AE_CH_TFC, AE_CH_TFL, AE_CH_TFR, AUDIOENGINE_CH_BC, AUDIOENGINE_CH_BL, AUDIOENGINE_CH_BLOC, AUDIOENGINE_CH_BR, AUDIOENGINE_CH_BROC, AUDIOENGINE_CH_FC, AUDIOENGINE_CH_FL, AUDIOENGINE_CH_FLOC, AUDIOENGINE_CH_FR, AUDIOENGINE_CH_FROC, AUDIOENGINE_CH_LFE, AUDIOENGINE_CH_MAX, AUDIOENGINE_CH_NULL, AUDIOENGINE_CH_RAW, AUDIOENGINE_CH_SL, AUDIOENGINE_CH_SR, AUDIOENGINE_CH_TBC, AUDIOENGINE_CH_TBL, AUDIOENGINE_CH_TBR, AUDIOENGINE_CH_TC, AUDIOENGINE_CH_TFC, AUDIOENGINE_CH_TFL, and AUDIOENGINE_CH_TFR.
Referenced by get_current_sink_format().
TranslateAEChannelToKodi()
AEChannel ADDON::Interface_AudioEngine::TranslateAEChannelToKodi (AudioEngineChannel channel) static
Translation functions to separate Kodi and addons.
This thought to make it more safe for cases as something changed inside Kodi, addons overseen and breaks API, further to have on addons a better documentation about this parts.
References AE_CH_BC, AE_CH_BL, AE_CH_BLOC, AE_CH_BR, AE_CH_BROC, AE_CH_FC, AE_CH_FL, AE_CH_FLOC, AE_CH_FR, AE_CH_FROC, AE_CH_LFE, AE_CH_MAX, AE_CH_NULL, AE_CH_RAW, AE_CH_SL, AE_CH_SR, AE_CH_TBC, AE_CH_TBL, AE_CH_TBR, AE_CH_TC, AE_CH_TFC, AE_CH_TFL, AE_CH_TFR, AUDIOENGINE_CH_BC, AUDIOENGINE_CH_BL, AUDIOENGINE_CH_BLOC, AUDIOENGINE_CH_BR, AUDIOENGINE_CH_BROC, AUDIOENGINE_CH_FC, AUDIOENGINE_CH_FL, AUDIOENGINE_CH_FLOC, AUDIOENGINE_CH_FR, AUDIOENGINE_CH_FROC, AUDIOENGINE_CH_LFE, AUDIOENGINE_CH_MAX, AUDIOENGINE_CH_NULL, AUDIOENGINE_CH_RAW, AUDIOENGINE_CH_SL, AUDIOENGINE_CH_SR, AUDIOENGINE_CH_TBC, AUDIOENGINE_CH_TBL, AUDIOENGINE_CH_TBR, AUDIOENGINE_CH_TC, AUDIOENGINE_CH_TFC, AUDIOENGINE_CH_TFL, and AUDIOENGINE_CH_TFR.
Referenced by audioengine_make_stream(), and KODI::ADDONS::CAudioDecoder::Init().
TranslateAEFormatToAddon()
AudioEngineDataFormat ADDON::Interface_AudioEngine::TranslateAEFormatToAddon (AEDataFormat format) static
References AE_FMT_DOUBLE, AE_FMT_DOUBLEP, AE_FMT_FLOAT, AE_FMT_FLOATP, AE_FMT_INVALID, AE_FMT_MAX, AE_FMT_RAW, AE_FMT_S16BE, AE_FMT_S16LE, AE_FMT_S16NE, AE_FMT_S16NEP, AE_FMT_S24BE3, AE_FMT_S24BE4, AE_FMT_S24LE3, AE_FMT_S24LE4, AE_FMT_S24NE3, AE_FMT_S24NE3P, AE_FMT_S24NE4, AE_FMT_S24NE4MSB, AE_FMT_S24NE4MSBP, AE_FMT_S24NE4P, AE_FMT_S32BE, AE_FMT_S32LE, AE_FMT_S32NE, AE_FMT_S32NEP, AE_FMT_U8, AE_FMT_U8P, AUDIOENGINE_FMT_DOUBLE, AUDIOENGINE_FMT_DOUBLEP, AUDIOENGINE_FMT_FLOAT, AUDIOENGINE_FMT_FLOATP, AUDIOENGINE_FMT_INVALID, AUDIOENGINE_FMT_MAX, AUDIOENGINE_FMT_RAW, AUDIOENGINE_FMT_S16BE, AUDIOENGINE_FMT_S16LE, AUDIOENGINE_FMT_S16NE, AUDIOENGINE_FMT_S16NEP, AUDIOENGINE_FMT_S24BE3, AUDIOENGINE_FMT_S24BE4, AUDIOENGINE_FMT_S24LE3, AUDIOENGINE_FMT_S24LE4, AUDIOENGINE_FMT_S24NE3, AUDIOENGINE_FMT_S24NE3P, AUDIOENGINE_FMT_S24NE4, AUDIOENGINE_FMT_S24NE4MSB, AUDIOENGINE_FMT_S24NE4MSBP, AUDIOENGINE_FMT_S24NE4P, AUDIOENGINE_FMT_S32BE, AUDIOENGINE_FMT_S32LE, AUDIOENGINE_FMT_S32NE, AUDIOENGINE_FMT_S32NEP, AUDIOENGINE_FMT_U8, and AUDIOENGINE_FMT_U8P.
Referenced by aestream_get_data_format(), and get_current_sink_format().
TranslateAEFormatToKodi()
AEDataFormat ADDON::Interface_AudioEngine::TranslateAEFormatToKodi (AudioEngineDataFormat format) static
References AE_FMT_DOUBLE, AE_FMT_DOUBLEP, AE_FMT_FLOAT, AE_FMT_FLOATP, AE_FMT_INVALID, AE_FMT_MAX, AE_FMT_RAW, AE_FMT_S16BE, AE_FMT_S16LE, AE_FMT_S16NE, AE_FMT_S16NEP, AE_FMT_S24BE3, AE_FMT_S24BE4, AE_FMT_S24LE3, AE_FMT_S24LE4, AE_FMT_S24NE3, AE_FMT_S24NE3P, AE_FMT_S24NE4, AE_FMT_S24NE4MSB, AE_FMT_S24NE4MSBP, AE_FMT_S24NE4P, AE_FMT_S32BE, AE_FMT_S32LE, AE_FMT_S32NE, AE_FMT_S32NEP, AE_FMT_U8, AE_FMT_U8P, AUDIOENGINE_FMT_DOUBLE, AUDIOENGINE_FMT_DOUBLEP, AUDIOENGINE_FMT_FLOAT, AUDIOENGINE_FMT_FLOATP, AUDIOENGINE_FMT_INVALID, AUDIOENGINE_FMT_MAX, AUDIOENGINE_FMT_RAW, AUDIOENGINE_FMT_S16BE, AUDIOENGINE_FMT_S16LE, AUDIOENGINE_FMT_S16NE, AUDIOENGINE_FMT_S16NEP, AUDIOENGINE_FMT_S24BE3, AUDIOENGINE_FMT_S24BE4, AUDIOENGINE_FMT_S24LE3, AUDIOENGINE_FMT_S24LE4, AUDIOENGINE_FMT_S24NE3, AUDIOENGINE_FMT_S24NE3P, AUDIOENGINE_FMT_S24NE4, AUDIOENGINE_FMT_S24NE4MSB, AUDIOENGINE_FMT_S24NE4MSBP, AUDIOENGINE_FMT_S24NE4P, AUDIOENGINE_FMT_S32BE, AUDIOENGINE_FMT_S32LE, AUDIOENGINE_FMT_S32NE, AUDIOENGINE_FMT_S32NEP, AUDIOENGINE_FMT_U8, and AUDIOENGINE_FMT_U8P.
Referenced by audioengine_make_stream(), and KODI::ADDONS::CAudioDecoder::Init().
The documentation for this struct was generated from the following files:
interfaces/AudioEngine.h
AudioEngine.cpp