Kodi Documentation: CColorManager Class Reference
CColorManager Class Reference
#include <ColorManager.h>
Public Member Functions
CColorManager ()
virtual ~CColorManager ()
bool IsEnabled () const
Check if user has requested color management.
bool IsValid () const
Check if configuration of color management is valid.
bool GetVideo3dLut (AVColorPrimaries srcPrimaries, int *cmsToken, CMS_DATA_FORMAT format, int clutSize, uint16_t *clutData)
Get a 3D LUT for video color correction.
bool CheckConfiguration (int cmsToken, AVColorPrimaries srcPrimaries)
Check if a 3D LUT is still valid.
Static Public Member Functions
static bool Get3dLutSize (CMS_DATA_FORMAT format, int *clutSize, int *dataSize)
Get a 3D LUT dimension and data size for video color correction.
Static Private Member Functions
static bool Probe3dLut (const std::string &filename, int *clutSize)
Check .3dlut file validity.
static bool Load3dLut (const std::string &filename, CMS_DATA_FORMAT format, int clutSize, uint16_t *clutData)
Load a .3dlut file.
Private Attributes
CMS_PRIMARIES m_curVideoPrimaries
int m_curClutSize
int m_curCmsToken
int m_curCmsMode
std::string m_cur3dlutFile
std::string m_curIccProfile
Constructor & Destructor Documentation
CColorManager()
CColorManager::CColorManager ()
References CMS_PRIMARIES_AUTO, m_curClutSize, m_curCmsMode, m_curCmsToken, and m_curVideoPrimaries.
~CColorManager()
CColorManager::~CColorManager () virtual default
Member Function Documentation
CheckConfiguration()
bool CColorManager::CheckConfiguration (int cmsToken, AVColorPrimaries srcPrimaries)
Check if a 3D LUT is still valid.
Parameters
cmsToken pointer to a color manager configuration token
srcPrimaries video primaries (see AVColorPrimaries)
Returns
true on valid, false if 3D LUT should be reloaded
References avColorToCmsPrimaries(), CMS_MODE_3DLUT, CMS_MODE_PROFILE, CMS_PRIMARIES_AUTO, CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGERROR, m_cur3dlutFile, m_curClutSize, m_curCmsMode, m_curCmsToken, and m_curIccProfile.
Get3dLutSize()
bool CColorManager::Get3dLutSize (CMS_DATA_FORMAT format, int * clutSize, int * dataSize) static
Get a 3D LUT dimension and data size for video color correction.
Parameters
format required format of CLUT data
clutSize pointer to CLUT resolution
dataSize pointer to CLUT data size
Returns
true on success, false otherwise
References CMS_DATA_FMT_RGBA, CMS_MODE_3DLUT, CMS_MODE_PROFILE, CServiceBroker::GetSettingsComponent(), CLog::Log(), LOGDEBUG, and Probe3dLut().
Referenced by CLinuxRendererGL::LoadCLUT(), and CRendererBase::OnCMSConfigChanged().
GetVideo3dLut()
bool CColorManager::GetVideo3dLut (AVColorPrimaries srcPrimaries, int * cmsToken, CMS_DATA_FORMAT format, int clutSize, uint16_t * clutData)
Get a 3D LUT for video color correction.
Parameters
srcPrimaries video primaries (see AVColorPrimaries)
cmsToken pointer to a color manager configuration token
format of CLUT data
clutSize CLUT resolution
clutData pointer to CLUT data
Returns
true on success, false otherwise
References avColorToCmsPrimaries(), CMS_DATA_FMT_RGBA, CMS_MODE_3DLUT, CMS_MODE_PROFILE, CMS_PRIMARIES_AUTO, CServiceBroker::GetSettingsComponent(), Load3dLut(), CLog::Log(), LOGDEBUG, m_cur3dlutFile, m_curClutSize, m_curCmsMode, m_curCmsToken, m_curIccProfile, and m_curVideoPrimaries.
IsEnabled()
bool CColorManager::IsEnabled () const
Check if user has requested color management.
Returns
true on enabled, false otherwise
References CServiceBroker::GetSettingsComponent(), and IsValid().
IsValid()
bool CColorManager::IsValid () const
Check if configuration of color management is valid.
Returns
true on valid, false otherwise
References CMS_MODE_3DLUT, CMS_MODE_PROFILE, XFILE::CFile::Exists(), and CServiceBroker::GetSettingsComponent().
Referenced by IsEnabled().
Load3dLut()
bool CColorManager::Load3dLut (const std::string & filename, CMS_DATA_FORMAT format, int clutSize, uint16_t * clutData) static private
Load a .3dlut file.
Parameters
filename full path and filename
format of CLUT data
clutSize CLUT resolution
clutData pointer to CLUT data
Returns
true on success, false otherwise
References CMS_DATA_FMT_RGBA, index(), H3DLUT::inputBitDepth, CLog::Log(), LOGERROR, and H3DLUT::lutFileOffset.
Referenced by GetVideo3dLut().
Probe3dLut()
bool CColorManager::Probe3dLut (const std::string & filename, int * clutSize) static private
Check .3dlut file validity.
Parameters
filename full path and filename
clutSize pointer to CLUT resolution
Returns
true if the file can be loaded, false otherwise
References H3DLUT::fileVersion, H3DLUT::inputBitDepth, H3DLUT::inputColorEncoding, CLog::Log(), LOGERROR, H3DLUT::lutCompressionMethod, H3DLUT::outputColorEncoding, and H3DLUT::signature.
Referenced by Get3dLutSize().
Member Data Documentation
m_cur3dlutFile
std::string CColorManager::m_cur3dlutFile private
Referenced by CheckConfiguration(), and GetVideo3dLut().
m_curClutSize
int CColorManager::m_curClutSize private
Referenced by CColorManager(), CheckConfiguration(), and GetVideo3dLut().
m_curCmsMode
int CColorManager::m_curCmsMode private
Referenced by CColorManager(), CheckConfiguration(), and GetVideo3dLut().
m_curCmsToken
int CColorManager::m_curCmsToken private
Referenced by CColorManager(), CheckConfiguration(), and GetVideo3dLut().
m_curIccProfile
std::string CColorManager::m_curIccProfile private
Referenced by CheckConfiguration(), and GetVideo3dLut().
m_curVideoPrimaries
CMS_PRIMARIES CColorManager::m_curVideoPrimaries private
Referenced by CColorManager(), and GetVideo3dLut().
The documentation for this class was generated from the following files:
ColorManager.h
ColorManager.cpp