Kodi Documentation: CVideoSyncAndroid Class Reference
CVideoSyncAndroid Class Reference
#include <VideoSyncAndroid.h>
Public Member Functions
CVideoSyncAndroid (CVideoReferenceClock *clock)
bool Setup () override
void Run (CEvent &stop) override
void Cleanup () override
float GetFps () override
void OnResetDisplay () override
void FrameCallback (int64_t frameTimeNanos)
Public Member Functions inherited from CVideoSync
CVideoSync (CVideoReferenceClock *clock)
virtual ~CVideoSync ()=default
virtual void RefreshChanged ()
Private Attributes
int64_t m_LastVBlankTime
CEvent m_abortEvent
Additional Inherited Members
Protected Attributes inherited from CVideoSync
float m_fps
CVideoReferenceClock * m_refClock
Private Member Functions inherited from IDispResource
virtual ~IDispResource ()=default
virtual void OnLostDisplay ()
virtual void OnAppFocusChange (bool focus)
Constructor & Destructor Documentation
CVideoSyncAndroid()
CVideoSyncAndroid::CVideoSyncAndroid (CVideoReferenceClock * clock) inline
Member Function Documentation
Cleanup()
void CVideoSyncAndroid::Cleanup () override virtual
Implements CVideoSync.
References CXBMCApp::DeinitFrameCallback(), CXBMCApp::Get(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, and CWinSystemBase::Unregister().
FrameCallback()
void CVideoSyncAndroid::FrameCallback (int64_t frameTimeNanos)
References CurrentHostFrequency(), CVideoSync::m_fps, m_LastVBlankTime, CVideoSync::m_refClock, MathUtils::round_int(), and CVideoReferenceClock::UpdateClock().
Referenced by CXBMCApp::doFrame().
GetFps()
float CVideoSyncAndroid::GetFps () override virtual
Implements CVideoSync.
References CGraphicContext::GetFPS(), CWinSystemBase::GetGfxContext(), CServiceBroker::GetWinSystem(), CLog::Log(), LOGDEBUG, and CVideoSync::m_fps.
OnResetDisplay()
void CVideoSyncAndroid::OnResetDisplay () override virtual
Reimplemented from IDispResource.
References m_abortEvent, and CEvent::Set().
Run()
void CVideoSyncAndroid::Run (CEvent & stop) override virtual
Implements CVideoSync.
References m_abortEvent.
Setup()
bool CVideoSyncAndroid::Setup () override virtual
Implements CVideoSync.
References CurrentHostCounter(), CXBMCApp::Get(), CServiceBroker::GetWinSystem(), CXBMCApp::InitFrameCallback(), CLog::Log(), LOGDEBUG, m_abortEvent, m_LastVBlankTime, CWinSystemBase::Register(), and CEvent::Reset().
Member Data Documentation
m_abortEvent
CEvent CVideoSyncAndroid::m_abortEvent private
Referenced by OnResetDisplay(), Run(), and Setup().
m_LastVBlankTime
int64_t CVideoSyncAndroid::m_LastVBlankTime private
Initial value:
=
      0
Referenced by FrameCallback(), and Setup().
The documentation for this class was generated from the following files:
VideoSyncAndroid.h
VideoSyncAndroid.cpp