Kodi Documentation: IVideoPlayer Class Reference
IVideoPlayer Class Reference abstract
#include <IVideoPlayer.h>
Public Member Functions
virtual int OnDiscNavResult (void *pData, int iMessage)=0
virtual void GetVideoResolution (unsigned int &width, unsigned int &height)=0
virtual ~IVideoPlayer ()=default
Constructor & Destructor Documentation
~IVideoPlayer()
virtual IVideoPlayer::~IVideoPlayer () virtual default
Member Function Documentation
GetVideoResolution()
virtual void IVideoPlayer::GetVideoResolution (unsigned int & width, unsigned int & height) pure virtual
Implemented in CVideoPlayer.
Referenced by CInputStreamAddon::DetectScreenResolution().
OnDiscNavResult()
virtual int IVideoPlayer::OnDiscNavResult (void * pData, int iMessage) pure virtual
Implemented in CVideoPlayer.
Referenced by CDVDInputStreamBluray::Open(), CDVDInputStreamBluray::OverlayClose(), CDVDInputStreamBluray::OverlayFlush(), CDVDInputStreamNavigator::ProcessBlock(), CDVDInputStreamBluray::ProcessEvent(), and CDVDInputStreamNavigator::Read().
The documentation for this class was generated from the following file:
IVideoPlayer.h