Kodi Documentation: KODI::RETRO::CRetroPlayerInput Class Reference
KODI::RETRO::CRetroPlayerInput Class Reference
#include <RetroPlayerInput.h>
Public Member Functions
CRetroPlayerInput (PERIPHERALS::CPeripherals &peripheralManager, CRPProcessInfo &processInfo, GAME::GameClientPtr gameClient)
~CRetroPlayerInput () override
void StartAgentManager ()
void StopAgentManager ()
void SetSpeed (double speed)
void EnableInput (bool bEnabled)
bool AcceptsInput () const override
Return true if the input source accepts input.
void PollInput () override
Poll the input source for input.
Public Member Functions inherited from KODI::GAME::IGameInputCallback
virtual ~IGameInputCallback ()=default
Private Attributes
PERIPHERALS::CPeripherals & m_peripheralManager
CRPProcessInfo & m_processInfo
PERIPHERALS::EventPollHandlePtr m_inputPollHandle
bool m_bEnabled = false
const GAME::GameClientPtr m_gameClient
bool m_bAgentManagerStarted {false}
Constructor & Destructor Documentation
CRetroPlayerInput()
CRetroPlayerInput::CRetroPlayerInput (PERIPHERALS::CPeripherals & peripheralManager, CRPProcessInfo & processInfo, GAME::GameClientPtr gameClient)
References CLog::Log(), LOGDEBUG, m_inputPollHandle, m_peripheralManager, and PERIPHERALS::CPeripherals::RegisterEventPoller().
~CRetroPlayerInput()
CRetroPlayerInput::~CRetroPlayerInput () override
References CLog::Log(), LOGDEBUG, and m_inputPollHandle.
Member Function Documentation
AcceptsInput()
bool KODI::RETRO::CRetroPlayerInput::AcceptsInput () const inline override virtual
Return true if the input source accepts input.
Returns
True if input should be processed, false otherwise
Implements KODI::GAME::IGameInputCallback.
References m_bEnabled.
EnableInput()
void CRetroPlayerInput::EnableInput (bool bEnabled)
References m_bEnabled.
PollInput()
void CRetroPlayerInput::PollInput () override virtual
Poll the input source for input.
Implements KODI::GAME::IGameInputCallback.
References m_inputPollHandle.
SetSpeed()
void CRetroPlayerInput::SetSpeed (double speed)
References m_inputPollHandle.
StartAgentManager()
void CRetroPlayerInput::StartAgentManager ()
References KODI::RETRO::CRPProcessInfo::GetRenderContext(), m_bAgentManagerStarted, m_gameClient, m_processInfo, and KODI::RETRO::CRenderContext::StartAgentInput().
StopAgentManager()
void CRetroPlayerInput::StopAgentManager ()
References KODI::RETRO::CRPProcessInfo::GetRenderContext(), m_bAgentManagerStarted, m_processInfo, and KODI::RETRO::CRenderContext::StopAgentInput().
Member Data Documentation
m_bAgentManagerStarted
bool KODI::RETRO::CRetroPlayerInput::m_bAgentManagerStarted {false} private
Referenced by StartAgentManager(), and StopAgentManager().
m_bEnabled
bool KODI::RETRO::CRetroPlayerInput::m_bEnabled = false private
Referenced by AcceptsInput(), and EnableInput().
m_gameClient
const GAME::GameClientPtr KODI::RETRO::CRetroPlayerInput::m_gameClient private
Referenced by StartAgentManager().
m_inputPollHandle
PERIPHERALS::EventPollHandlePtr KODI::RETRO::CRetroPlayerInput::m_inputPollHandle private
Referenced by CRetroPlayerInput(), PollInput(), SetSpeed(), and ~CRetroPlayerInput().
m_peripheralManager
PERIPHERALS::CPeripherals& KODI::RETRO::CRetroPlayerInput::m_peripheralManager private
Referenced by CRetroPlayerInput().
m_processInfo
CRPProcessInfo& KODI::RETRO::CRetroPlayerInput::m_processInfo private
Referenced by StartAgentManager(), and StopAgentManager().
The documentation for this class was generated from the following files:
RetroPlayerInput.h
RetroPlayerInput.cpp