Kodi Documentation: anonymous_namespace{ContextMenus.cpp} Namespace Reference
anonymous_namespace{ContextMenus.cpp} Namespace Reference
Functions
std::shared_ptr< CFileItem > ResolveFavouriteItem (const CFileItem &item)
bool IsPlayMediaFavourite (const CFileItem &item)
bool IsActivateWindowFavourite (const CFileItem &item)
void Play (const std::shared_ptr< CFileItem > &item, const std::string &player)
std::vector< std::string > GetPlayers (const CPlayerCoreFactory &playerCoreFactory, const CFileItem &item)
bool CanQueue (const CFileItem &item)
void SelectNextItem (int windowID)
Function Documentation
CanQueue()
bool anonymous_namespace{ContextMenus.cpp}::CanQueue (const CFileItem & item)
References CFileItem::CanQueue(), CanQueue(), CServiceBroker::GetGUI(), CGUIComponent::GetWindowManager(), and WINDOW_MUSIC_PLAYLIST.
Referenced by CanQueue().
GetPlayers()
std::vector< std::string > anonymous_namespace{ContextMenus.cpp}::GetPlayers (const CPlayerCoreFactory & playerCoreFactory, const CFileItem & item)
References CPlayerCoreFactory::GetPlayers(), and GetPlayers().
Referenced by GetPlayers().
IsActivateWindowFavourite()
bool anonymous_namespace{ContextMenus.cpp}::IsActivateWindowFavourite (const CFileItem & item)
References CFavouritesURL::ACTIVATE_WINDOW, IsActivateWindowFavourite(), and CFileItem::IsFavourite().
Referenced by IsActivateWindowFavourite().
IsPlayMediaFavourite()
bool anonymous_namespace{ContextMenus.cpp}::IsPlayMediaFavourite (const CFileItem & item)
References CFileItem::IsFavourite(), IsPlayMediaFavourite(), and CFavouritesURL::PLAY_MEDIA.
Referenced by IsPlayMediaFavourite().
Play()
void anonymous_namespace{ContextMenus.cpp}::Play (const std::shared_ptr< CFileItem > & item, const std::string & player)
References ContentUtils::CHECK_AUTO_PLAY_NEXT_ITEM, Play(), ContentUtils::PLAY_ONLY_THIS, and MUSIC_UTILS::PlayItem().
Referenced by Play().
ResolveFavouriteItem()
std::shared_ptr< CFileItem > anonymous_namespace{ContextMenus.cpp}::ResolveFavouriteItem (const CFileItem & item)
References CServiceBroker::GetFavouritesService(), CFavouritesService::ResolveFavourite(), and ResolveFavouriteItem().
Referenced by ResolveFavouriteItem().
SelectNextItem()
void anonymous_namespace{ContextMenus.cpp}::SelectNextItem (int windowID)
References CServiceBroker::GetGUI(), CGUIMessage::GetParam1(), CGUIWindow::GetViewContainerID(), CGUIComponent::GetWindowManager(), GUI_MSG_ITEM_SELECT, GUI_MSG_ITEM_SELECTED, and SelectNextItem().
Referenced by SelectNextItem().