Kodi Documentation: CCompileInfo Class Reference
CCompileInfo Class Reference
#include <CompileInfo.h>
Static Public Member Functions
static int GetMajor ()
static int GetMinor ()
static const char * GetPackage ()
static const char * GetClass ()
static const char * GetAppName ()
static const char * GetSuffix ()
static const char * GetSCMID ()
static std::string GetSharedLibrarySuffix ()
static const char * GetCopyrightYears ()
static std::string GetBuildDate ()
static const char * GetVersionCode ()
static std::vector< std::string > GetAvailableWindowSystems ()
static std::vector< std::string > GetAvailableAudioBackends ()
static std::vector< std::string > GetAvailableGlInterfaces ()
static std::vector< ADDON::RepoInfo > LoadOfficialRepoInfos ()
static std::string GetPythonVersion ()
static std::vector< std::string > GetWebserverExtraWhitelist ()
Member Function Documentation
GetAppName()
static const char * CCompileInfo::GetAppName () static
Referenced by CAndroidInterfaceForCLog::AddSinks(), CWebServer::AskForAuthentication(), Cocoa_DoAppleScriptFile(), KODI::WINDOWING::WAYLAND::CWinSystemWayland::CreateShellSurface(), KODI::WINDOWING::WAYLAND::CWinSystemWaylandWebOS::CreateShellSurface(), CSysInfo::GetAppName(), CSysInfo::GetDeviceName(), XFILE::CAndroidAppDirectory::GetDirectory(), CWIN32Util::GetProfilePath(), JSONRPC::CApplicationOperations::GetPropertyValue(), CTVOSFileUtils::GetUserHomeDirectory(), KODI::WINDOWING::LINUX::COSScreenSaverFreedesktop::Inhibit(), CSettingsComponent::InitDirectoriesLinux(), CSettingsComponent::InitDirectoriesOSX(), AE::SINK::CAESinkPipewire::Initialize(), CLog::Initialize(), ADDON::Interface_General::kodi_version(), CXRandR::LoadCustomModeLinesToAllOutputs(), CHTTPPythonInvoker::onError(), DebugLogSharingPresenter::OnSettingAction(), CApplication::PrintStartupLog(), CExternalPlayer::Process(), CGUIWindowDebugInfo::Process(), CXRandR::Query(), CDDB::Xcddb::queryCDinfo(), CUtil::ResolveExecutablePath(), CXRandR::SetMode(), CXBMCApp::SetupEnv(), KODI::WINDOWING::X11::CWinSystemX11::SetWindow(), TEST_F(), TEST_F(), TEST_F(), CXRandR::TurnOffOutput(), WinMain(), and XBMCHelper::XBMCHelper().
GetAvailableAudioBackends()
static std::vector< std::string > CCompileInfo::GetAvailableAudioBackends () static
GetAvailableGlInterfaces()
static std::vector< std::string > CCompileInfo::GetAvailableGlInterfaces () static
GetAvailableWindowSystems()
static std::vector< std::string > CCompileInfo::GetAvailableWindowSystems () static
GetBuildDate()
static std::string CCompileInfo::GetBuildDate () static
Referenced by CSysInfo::GetBuildDate().
GetClass()
static const char * CCompileInfo::GetClass () static
Referenced by ADDON::Interface_Android::get_class_name(), and jni::CJNIMainActivity::RegisterNatives().
GetCopyrightYears()
static const char * CCompileInfo::GetCopyrightYears () static
Referenced by CAppParamParser::DisplayVersion().
GetMajor()
static int CCompileInfo::GetMajor () static
Referenced by JSONRPC::CApplicationOperations::GetPropertyValue(), CSysInfo::GetVersionShort(), ADDON::Interface_General::kodi_version(), and WinMain().
GetMinor()
static int CCompileInfo::GetMinor () static
Referenced by JSONRPC::CApplicationOperations::GetPropertyValue(), CSysInfo::GetVersionShort(), ADDON::Interface_General::kodi_version(), and WinMain().
GetPackage()
static const char * CCompileInfo::GetPackage () static
Referenced by KODI::WINDOWING::WAYLAND::CShellSurfaceWebOSShell::CShellSurfaceWebOSShell(), XFILE::CAndroidAppDirectory::GetDirectory(), KODI::WINDOWING::WAYLAND::COSScreenSaverWebOS::Inhibit(), CAESinkStarfish::Initialize(), KODI::WINDOWING::WAYLAND::COSScreenSaverWebOS::OnScreenSaverAboutToStart(), CDVDVideoCodecStarfish::OpenInternal(), and CXBMCApp::SetupEnv().
GetPythonVersion()
static std::string CCompileInfo::GetPythonVersion () static
Referenced by init_emu_environ(), and CXBMCApp::SetupEnv().
GetSCMID()
static const char * CCompileInfo::GetSCMID () static
Referenced by JSONRPC::CApplicationOperations::GetPropertyValue(), CSysInfo::GetVersion(), CSysInfo::GetVersionGit(), ADDON::Interface_General::kodi_version(), and WinMain().
GetSharedLibrarySuffix()
static std::string CCompileInfo::GetSharedLibrarySuffix () static
GetSuffix()
static const char * CCompileInfo::GetSuffix () static
Referenced by JSONRPC::CApplicationOperations::GetPropertyValue(), CSysInfo::GetVersionShort(), ADDON::Interface_General::kodi_version(), and WinMain().
GetVersionCode()
static const char * CCompileInfo::GetVersionCode () static
Referenced by CSysInfo::GetVersion(), and CSysInfo::GetVersionCode().
GetWebserverExtraWhitelist()
static std::vector< std::string > CCompileInfo::GetWebserverExtraWhitelist () static
Referenced by CFileUtils::CheckFileAccessAllowed(), and CApplication::PrintStartupLog().
LoadOfficialRepoInfos()
static std::vector< ADDON::RepoInfo > CCompileInfo::LoadOfficialRepoInfos () static
The documentation for this class was generated from the following file:
CompileInfo.h