Kodi Documentation: TestMathUtils.cpp File Reference
TestMathUtils.cpp File Reference
#include "utils/MathUtils.h"
#include <gtest/gtest.h>
Functions
TEST (TestMathUtils, round_int)
TEST (TestMathUtils, truncate_int)
TEST (TestMathUtils, abs)
TEST (TestMathUtils, bitcount)
Function Documentation
TEST() [1/4]
TEST (TestMathUtils , abs)
References MathUtils::abs(), EXPECT_EQ(), and int64_t().
TEST() [2/4]
TEST (TestMathUtils , bitcount)
References MathUtils::bitcount(), and EXPECT_EQ().
TEST() [3/4]
TEST (TestMathUtils , round_int)
References EXPECT_EQ(), and MathUtils::round_int().
TEST() [4/4]
TEST (TestMathUtils , truncate_int)
References EXPECT_EQ(), and MathUtils::truncate_int().