Kodi Documentation: KODI::RETRO::CRetroPlayerAutoSave Class Reference
KODI::RETRO::CRetroPlayerAutoSave Class Reference
#include <RetroPlayerAutoSave.h>
Public Member Functions
CRetroPlayerAutoSave (IAutoSaveCallback &callback, GAME::CGameSettings &settings)
~CRetroPlayerAutoSave () override
Protected Member Functions
void Process () override
Protected Member Functions inherited from CThread
CThread (const char *ThreadName)
virtual void OnStartup ()
virtual void OnExit ()
WaitResponse AbortableWait (CEvent &event, std::chrono::milliseconds duration=std::chrono::milliseconds(-1))
CThread (IRunnable *pRunnable, const char *ThreadName)
virtual ~CThread ()
void Create (bool bAutoDelete=false)
template<typename Rep , typename Period >
void Sleep (std::chrono::duration< Rep, Period > duration)
bool IsAutoDelete () const
virtual void StopThread (bool bWait=true)
bool IsRunning () const
bool IsCurrentThread () const
bool Join (std::chrono::milliseconds duration)
bool SetPriority (const ThreadPriority &priority)
Set the threads priority. This uses the platforms native threading library to do so.
virtual void OnException ()
Private Attributes
IAutoSaveCallback & m_callback
GAME::CGameSettings & m_settings
Additional Inherited Members
Protected Types inherited from CThread
enum WaitResponse { WAIT_INTERRUPTED = -1 , WAIT_SIGNALED = 0 , WAIT_TIMEDOUT = 1 }
Static Protected Member Functions inherited from CThread
static const std::thread::id GetCurrentThreadId ()
static CThread * GetCurrentThread ()
Protected Attributes inherited from CThread
std::atomic< bool > m_bStop
Constructor & Destructor Documentation
CRetroPlayerAutoSave()
CRetroPlayerAutoSave::CRetroPlayerAutoSave (IAutoSaveCallback & callback, GAME::CGameSettings & settings) explicit
References CThread::Create(), CLog::Log(), and LOGDEBUG.
~CRetroPlayerAutoSave()
CRetroPlayerAutoSave::~CRetroPlayerAutoSave () override
References CLog::Log(), LOGDEBUG, and CThread::StopThread().
Member Function Documentation
Process()
void CRetroPlayerAutoSave::Process (void) override protected virtual
Reimplemented from CThread.
References KODI::GAME::CGameSettings::AutosaveEnabled(), KODI::RETRO::IAutoSaveCallback::CreateAutosave(), KODI::RETRO::IAutoSaveCallback::IsAutoSaveEnabled(), CLog::Log(), LOGDEBUG, CThread::m_bStop, m_callback, m_settings, and CThread::Sleep().
Member Data Documentation
m_callback
IAutoSaveCallback& KODI::RETRO::CRetroPlayerAutoSave::m_callback private
Referenced by Process().
m_settings
GAME::CGameSettings& KODI::RETRO::CRetroPlayerAutoSave::m_settings private
Referenced by Process().
The documentation for this class was generated from the following files:
RetroPlayerAutoSave.h
RetroPlayerAutoSave.cpp